### ISSUE TITLE
Installing CLI with setuptools style "scripts" vs "console_scripts".

### ISSUE THREAD

**Issue by grabear** [python-poetry/poetry#1023]
- [ ] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate. 
 **This is definitely a duplicate, but the Feature Request is different.**
- [X] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Feature Request

It would be nice to install **files** as command line [_scripts_](https://python-packaging.readthedocs.io/en/latest/command-line-scripts.html#the-scripts-keyword-argument) vs installing **modules** as command line [_console\_scripts_](https://python-packaging.readthedocs.io/en/latest/command-line-scripts.html#the-scripts-keyword-argument).

The current ability of poetry to include "scripts" seems slightly misleading according to the setuptools documentation.  I could be wrong, but it seems like the [tools.poetry.scripts] toml keyword should read more like [tools.poetry.console_scripts] or [tools.poetry.entry_points].

So I would like to request some clarity around this terminology in the documentation, as well as the implementation of setuptools style scripts.

I believe https://github.com/sdispater/poetry/issues/241#issuecomment-398767327 addresses this as well.  An associated PR is also open in https://github.com/sdispater/poetry/pull/304

cc: @ojii 

Thanks to any contributors to this project.  It's an amazing tools that I'm excited to continue using.

Cheers,
@grabear

**Comment by grabear** [comment]
It's also not super clear in the documentation what the difference is between '[plugins](https://poetry.eustace.io/docs/pyproject/#plugins)' and '[scripts](https://poetry.eustace.io/docs/pyproject/#scripts)' as defined in the poetry documentation.  
Based on the original comment:

* poetry's scripts == setuptools' entrypoint/console_script
* setuptools' scripts keyword != poetry (is not represented by poetry)

And new information:

* poetry's plugins == setuptools' entrypoint/[dynamic-discovery-of-services-and-plugins ](https://setuptools.readthedocs.io/en/latest/setuptools.html#dynamic-discovery-of-services-and-plugins)

By changing the link in the 'plugins' documentation to the one supplied above, I think that would also help clear things up:

From [this](https://setuptools.readthedocs.io/en/latest/setuptools.html) (main page of setuptools) to [this](https://setuptools.readthedocs.io/en/latest/setuptools.html#dynamic-discovery-of-services-and-plugins) (the actual article).

**Comment by ojii** [comment]
I could bring my PR up to date if there is a consensus on the config syntax and if this is something that poetry wants to support. I've stopped working on it because the discussion in the original ticket got way out of scope so I lost interest and found other workarounds to solve my use case.

**Comment by tedmiston** [comment]
I agree the Poetry docs would benefit from clarity around these topics.  My confusion was similar to @grabear until ending up on a few issues like this.

**Comment by funkyfuture** [comment]
yeah, it seems that a good load of topic-related issues opened here stem from that semantic twist.

**Comment by grabear** [comment]
I'm glad I'm not the only one that was confused.  I still have to come back to this issue sometimes to refresh my understanding of it all.  @sdispater are there any developments surrounding this issue as well as related issues?  https://github.com/sdispater/poetry/issues/241#issuecomment-398767327 and https://github.com/sdispater/poetry/pull/304

**Comment by grabear** [comment]
This is definitely not a stale issue..

**Comment by geckon** [comment]
For the record check #1504

**Comment by finswimmer** [comment]
I think this is solved by https://github.com/python-poetry/poetry-core/pull/40
