### ISSUE TITLE
[1.0.0a2] poetry env: can't detect virtualenv for projects with underscore in name

### ISSUE THREAD

**Issue by terminalmage** [python-poetry/poetry#1043]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Arch Linux
- **Poetry version**: 1.0.0a2
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/terminalmage/463761e26aa6a4476d578f6ebe65d6f6

## Issue

The virtualenv management in the prerelease does not list (and is not capable of removing) virtualenvs for projects with underscores in their name. When using the pyproject.toml linked above, this is the result:

```
% poetry install
Creating virtualenv foo-project-gZufGQel-py2.7 in /home/erik/.cache/pypoetry/virtualenvs
Updating dependencies
Resolving dependencies... (0.1s)


Package operations: 1 install, 0 updates, 0 removals

Writing lock file

  - Installing six (1.12.0)
% poetry env list
% poetry env remove 2.7

[ValueError]
Environment "foo_project-gZufGQel-py2.7" does not exist.
```

Note that poetry incorrectly believes that the virtualenv should be named `foo_project-gZufGQel-py2.7` while the correct virtualenv name is `foo-project-gZufGQel-py2.7` (underscore replaced by a dash).

Change the project name to remove the underscore and virtualenv management works as expected:

```
% poetry install
Creating virtualenv foo-project-uyCY9Hl4-py2.7 in /home/erik/.cache/pypoetry/virtualenvs
Updating dependencies
Resolving dependencies... (0.2s)


Package operations: 1 install, 0 updates, 0 removals

Writing lock file

  - Installing six (1.12.0)
% poetry env list
foo-project-uyCY9Hl4-py2.7 (Activated)
% poetry env remove 2.7
Deleted virtualenv: /home/erik/.cache/pypoetry/virtualenvs/foo-project-uyCY9Hl4-py2.7
```

In the second example I have edited the pyproject.toml to rename the project to `foo-project`.

**Comment by terminalmage** [comment]
Definitely not fixed yet.

**Comment by finswimmer** [comment]
Hello @terminalmage,

i'v tested it with the current release (1.0.9) and it seems to work. So I'm closing this issue. Please leave a comment if you disagree.

fin swimmer

**Comment by terminalmage** [comment]
@finswimmer Thanks for following up. I had already been using a preview release in which this was fixed, and I updated to the latest stable and confirmed that behavior has not regressed.

Thanks again!
