### ISSUE TITLE
render() missing 1 required positional argument

### ISSUE THREAD

**Issue by bmwant** [python-poetry/poetry#1077]
- [ ] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 14.04.5 LTS
- **Poetry version**: Poetry version 1.0.0a2
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/bmwant/f384559267da0b8ff3ce7c7b9ae2211a

## Issue
I'm launching `show` command e.g. `poetry show stripe` and getting the following error
```
[TypeError]
render() missing 1 required positional argument: 'io'
```

Verbose mode
```
Virtualenv venv-XnmBCwWW-py3.6 already exists.
Using virtualenv: /home/vagrant/.cache/pypoetry/virtualenvs/venv-XnmBCwWW-py3.6

[TypeError]
render() missing 1 required positional argument: 'io'

Traceback (most recent call last):
  File "/home/vagrant/.poetry/lib/poetry/_vendor/py3.6/clikit/console_application.py", line 131, in run
    status_code = command.handle(parsed_args, io)
  File "/home/vagrant/.poetry/lib/poetry/_vendor/py3.6/clikit/api/command/command.py", line 112, in handle
    status_code = self._do_handle(args, io)
  File "/home/vagrant/.poetry/lib/poetry/_vendor/py3.6/clikit/api/command/command.py", line 160, in _do_handle
    return getattr(handler, handler_method)(args, io, self)
  File "/home/vagrant/.poetry/lib/poetry/_vendor/py3.6/cleo/commands/command.py", line 92, in wrap_handle
    return self.handle()
  File "/home/vagrant/.poetry/lib/poetry/console/commands/show.py", line 78, in handle
    table.render()
```

Python version used is `3.6.8` installed with pyenv.

**Comment by chrahunt** [comment]
It looks like `Table.render` changed between cleo ([here](https://github.com/sdispater/cleo/blob/a4d0ab11bf4d0effb69ebd9f4f685cf7ab26719b/cleo/helpers/table.py#L154)) and clikit ([here](https://github.com/sdispater/clikit/blob/323c87822f6e89ad5af8548d2e3c18410a5ae648/src/clikit/ui/components/table.py#L82)). We should now be passing `self.io` to `table.render()`.

**Comment by ekhaydarov** [comment]
This seems to be still broken? any update on this or a workaround?
