### ISSUE TITLE
poetry.masonry.api.build_wheel disregards metadata_directory

### ISSUE THREAD

**Issue by chrahunt** [python-poetry/poetry#1078]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 18.04
- **Poetry version**: Poetry 0.12.15
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: N/A

## Issue

The current implementation of [`poetry.masontry.api:build_wheel`](https://github.com/sdispater/poetry/blob/2c37180f06add2648b01c5134c4d3335dbda41a5/poetry/masonry/api.py#L55) does not use `metadata_directory` per [PEP-517](https://www.python.org/dev/peps/pep-0517/#build-wheel). This makes it difficult to implement customizations by overriding `prepare_metadata_for_build_wheel` since the output files are not actually used in the wheel. For example, the following does not work:

```toml
# pyproject.toml
# ...
[tool.intreehooks]
build-backend = "pyproject"

[build-system]
requires = ["poetry>=0.12", "intreehooks"]
build-backend = "intreehooks:loader"
```

```python
# pyproject.py
from pathlib import Path

from poetry.masonry.api import (
    build_sdist,
    build_wheel,
    get_requires_for_build_wheel,
    get_requires_for_build_sdist,
    prepare_metadata_for_build_wheel as _prepare_metadata_for_build_wheel,
)
from poetry.poetry import Poetry

def prepare_metadata_for_build_wheel(metadata_directory, config_settings=None):
    name = _prepare_metadata_for_build_wheel(metadata_directory, config_settings)

    poetry = Poetry.create(".")

    metadata = Path(metadata_directory) / name / 'METADATA'

    deps = [d.to_pep_508() for d in poetry.package.dev_requires]

    text = metadata.read_text(encoding='utf-8')

    try:
        index = text.index('\n\n')
    except ValueError:
        index = len(text)

    new_requires = '\n'.join(
        f'Requires-Dist: {d}'
        for d in deps
    )

    new_text = f'{text[:index]}\n{new_requires}{text[index:]}'

    metadata.write_text(new_text, encoding='utf-8')

    return name
```

The `METADATA` file edited by `prepare_metadata_for_build_wheel` is used by pip for the wheel requirements, however the file is not included in the wheel, since `build_wheel` seems to generate a new one.

**Comment by chrahunt** [comment]
Still relevant.

**Comment by finswimmer** [comment]
Also discussed on https://discuss.python.org/t/nobody-is-following-the-metadata-directory-promise-in-pep-517/6964
