### ISSUE TITLE
Installing executables (e.g. flake8) in Pyenv-managed virtual environment not creating alias to executable

### ISSUE THREAD

**Issue by pydolan** [python-poetry/poetry#1131]
- [X] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Mac 10.14.1
- **Poetry version**: 0.12.16
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/pydolan/dbdf25379d0f0f7b626e894b59d79e0b

## Issue
When using Pyenv to make and activate a virtual environment (e.g., `pyenv virtualenv myproject; pyenv activate myproject`), if one uses `pip` to install a package that has an executable (e.g., Flake8 or Black), a "shim" file will be created in the pyenv directory (e.g., `~/.pyenv/shims/flake8` for the Flake8 package).  

However, if installing the same package via Poetry, this shim file is not created -- assuming the shim file does not exist beforehand (i.e., from another project or if using pip to install).  This results in the executable (e.g. flake8) not being available to run without specifying the full path.

It looks like Pyenv has a "rehashing" feature, which I assume is run immediately after calling `pip install flake8`.  For some reason, this is not triggered when using Poetry.  One can manually fix this by running `pyenv rehash`.

Here's an example of the Shim file that gets created (which has the same contents as the script `pip` points to):
```bash
#!/usr/bin/env bash
set -e
[ -n "$PYENV_DEBUG" ] && set -x

program="${0##*/}"
if [[ "$program" = "python"* ]]; then
  for arg; do
    case "$arg" in
    -c* | -- ) break ;;
    */* )
      if [ -f "$arg" ]; then
        export PYENV_FILE_ARG="$arg"
        break
      fi
      ;;
    esac
  done
fi

export PYENV_ROOT="/Users/dol/.pyenv"
exec "/Users/dol/.pyenv/libexec/pyenv" exec "$program" "$@"
```

If you have a code point handy where pip is called, I'm happy to debug further.

**Comment by bboe** [comment]
I just started playing with poetry after years of manually working with virtualenv and virtualenv wrapper, and manually building packages. What I really like about poetry is the virtual environment that appears to automatically exist for each project. What I have yet to figure out conveniently is this same issue.

While I can `poetry add flake8` to have the package installed to my virtual environment, `flake8` is not made available on my path. I can however, run `poetry run flake8` but that's certainly not the behavior I would expect.

**Comment by a-musing-moose** [comment]
@pydolan & @bboe I too had similar confusions as a long time pyenv/pyenv-virtualenv user. The key thing I found is to recognise that poetry is managing the venv _for you_. You don't _need_ to use pyenv-virtualenv, just pyenv itself.

When you do a `poetry install` for the first time it will _create_ a venv for you, and install all dependencies within that venv. i.e. it does not know or care that you are already in a venv.

As such executable scripts like `flake8` have to be run _through_ poetry as you found: `poetry run flake8`.

There are a couple of options here, although personally I just run things through poetry itself now.

`poetry shell` - Will activate the venv and drop you install a shell within in (kind of like activate does for a regular venv)
`poetry config settings.virtualenvs.create false` will *globally* turn off poetry's venv creation functionality, e.g. it will use the existing one provided by pyenv-virtualenv.

From a personal point of view, to avoid confusion I have now effectively dropped the use of `pyenv-virtualenv`. When starting a new project instead I just use the pyenv installed version of python. e.g. I just `cd` into the project directory and run `pyenv local 3.7.3`. Poetry is already installed within the `3.7.3`. So I can just start using it. Yes it is a bit less pleasant to prefix everything with `poetry run` but I find it a small price to pay for the benefits that poetry itself brings

**Comment by pydolan** [comment]
Thanks @a-musing-moose, some good points.  

One of the features I like about pyenv-virtualenv is it's ability to read a `.python-version` file with the virtualenv name and auto-activate that environment when cd'ing into the directory.  I'm not aware of poetry supporting this (although I'm sure there's a way to hack this together with bash/sh/fish if one really wanted).

Poetry is at least good about detecting if one is already in a virtual environment and use it automatically when running Poetry commands. 

For now, I'll just run `pyenv rehash` if a command doesn't work in my setup

**Comment by bboe** [comment]
The main problem I figured out was that I had to change the order of my path as it was loading global functions above the poetry shell functions. With that using `poetry shell` now has the behavior that I actually expect.

**Comment by pydolan** [comment]
@sdispater – got a code point to help track down a fix for this issue?

**Comment by pszynk** [comment]
+1 yep, issue still present

**Comment by charlielin** [comment]
+1, issue still present

**Comment by finswimmer** [comment]
Hello,

we don't plan any tight coupling to `pyenv`. So something like what `pyenv rehash` is doing won't probably be included in poetry.

fin swimmer
