### ISSUE TITLE
ContextualVersionConflictError dependency resolution error for setuptools on Linux

### ISSUE THREAD

**Issue by adithyabsk** [python-poetry/poetry#1197]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 16.04
- **Poetry version**: 0.12.16
- **pyproject.toml file**: [pyproject.toml](https://github.com/georgianpartners/foreshadow/blob/master/pyproject.toml) and
[poetry.lock](https://github.com/georgianpartners/foreshadow/blob/master/poetry.lock)

## Issue
Follow up as per https://github.com/sdispater/poetry/issues/1194#issuecomment-505650820. I am encountering a very difficult to debug issue. [On fresh linux](https://dev.azure.com/georgianpartners/foreshadow/_build/results?buildId=13) boxes (CI), [poetry errors out (stack trace)](https://gist.github.com/adithyabsk/24898d4538bce76693384ce3149c60ef) on the first install. On future install the project seems to install find making this bug quite difficult to reproduce.

**Comment by adithyabsk** [comment]
@stephsamson I'd love to be able to debug this issue if I could be pointed in the right direction. Do you know what might be causing the issue?

**Comment by finswimmer** [comment]
Because there were no more comments to this issue for a very long time, I assume it is solved. So I will close it.

Feel free to leave a comment if someone disagree.

fin swimmer
