### ISSUE TITLE
test token-based upload to PyPI?

### ISSUE THREAD

**Issue by brainwane** [python-poetry/poetry#1250]
Hi! PyPI's getting ready to add upload tokens to its API, so packagers can upload using tokens instead of username/password.

I thought you might want to test and verify that poetry's publish command works with this. Instructions for testing the pull request: https://github.com/pypa/warehouse/issues/994#issuecomment-512634222

It would be great if you could leave a comment on https://github.com/pypa/warehouse/pull/6084 telling us whether it works for you! This will help us avoid headaches when we roll out the feature on pypi.org, which might be within the next week.

And you might want to get an update ready for [the credential configuration instructions in the Poetry docs](https://poetry.eustace.io/docs/repositories/#configuring-credentials).

**Comment by brainwane** [comment]
This beta feature is now live on PyPI and Test PyPI: https://pypi.org/help/#apitoken

**Comment by sdispater** [comment]
@brainwane Thanks for the heads up!

I will test it this week and add a simple way to set it up with Poetry.

**Comment by sdispater** [comment]
As of release `1.0.0`, Poetry now supports token based uploads (see https://python-poetry.org/docs/repositories/#configuring-credentials).
