### ISSUE TITLE
Feature request: pyproject.toml option (or install option) to only install dev dependencies

### ISSUE THREAD

**Issue by mwchase** [python-poetry/poetry#1254]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Feature Request

I've used Poetry for some projects in which I'm never running the project's code in the virtualenv that I'm running the dev dependencies from; instead, I'm building the project, then installing the built project in multiple other virtualenvs.

The dev dependencies include task runners that coordinate development tasks, so the dev dependencies must be installed—in this context through Poetry—to be able to accomplish anything. At the same time, I'm not interested in installing the project itself, _or_ its runtime dependencies in the same environment as the dev dependencies (so I believe this goes beyond `--no-root`). (In fact, in one project, the dev dependencies need to be installed and invoked in a particular manner before building the project is even possible.)

I'd like to have a simple Poetry invocation for getting a project ready to develop; since the project is defining how it is interacted with, I think it would make sense to alter the behavior of `poetry install` through configuration values in pyproject.toml. Defining a new option to `poetry install` would satisfy my use case, but IMO not be as nice.

(Now that I've described what I'm trying to do, I have to admit I'm not sure whether it makes sense to insist on using Poetry for it. The main draw I have to Poetry is that it simultaneously easily supports src layout, and is declarative, as opposed to copy-and-pasting a setup.py file. Is this workflow within Poetry's scope, or should I be making my own tool that works the way I want?)

**Comment by robertlagrant** [comment]
This feature can also be useful in multi-stage build Docker images.

**Comment by mwchase** [comment]
I'd certainly like to see it. I'll try to put together a PR and see if that spurs any more discussion.

**Comment by mwchase** [comment]
It looks to me like this would require changes to the Installer class to support this behavior; I don't have a good sense yet of whether this would miss some cases that also need changes, or, conversely, if a naive implementation would over-apply the changes.

Glancing over the code, it looks... approximately right, to change it in the Installer.

**Comment by mwchase** [comment]
Okay, I'm working on a PR, and it desperately needs tests. Is there any kind of writeup of how Poetry's internals are organized so I can figure out where best to put tests?

**Comment by finswimmer** [comment]
> Is there any kind of writeup of how Poetry's internals are organized so I can figure out where best to put tests?

There is a folder `tests` which mimics the code structure of the project files itself, but prefix the filenames with `test_` as `pytest` expect it. I recommend having a look at the already existing tests to learn how it works.

**Comment by blaggacao** [comment]
> This feature can also be useful in multi-stage build Docker images.

Then it'd rather be a command line flag, I guess...

I don't believe it belongs to the `toml` declarative spec but rather might be an invocation detail of how you'd use poetry in a specific context, hence I think a flag to `install` is preferable.

**Comment by mwchase** [comment]
> I think a flag to `install` is preferable.

... And to `add`, `remove`, and `update`? Maybe `lock` as well, I'm not as familiar with it.

For the record, my PR *barely* changed the implementation of `install`. All it really did was make the field I added to the `toml` basically force it to act like `no-root` was specified.

For the specific project that inspired this request, I don't like the idea of saying "Okay, to get started with this, install `poetry`, and run specifically `poetry install --no-root`. It'll install a bunch of runtime dependencies you'll never use because all of the testing is done in isolated environments." This feature request/PR changes that to "Install `poetry`, and run `poetry install`. It'll install exactly what you need to get started."

**Comment by blaggacao** [comment]
I agree, there are concurrent legit goals:
- package specification
- dev tooling

But I insist one should not override the other.

I left a few questions / comments on the PR, now I'd like to fully understand the use case. :wink:

**Comment by finswimmer** [comment]
https://github.com/python-poetry/poetry/pull/2917 implements a `--dev-only` flag for `poetry install` and is available in poetry 1.2.0a1.
