### ISSUE TITLE
Support file/archive for dependencies

### ISSUE THREAD

**Issue by zyegfryed** [python-poetry/poetry#1263]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Feature Request

AFAIK, `pip` allows to install a package from a remote archive and I would like to be able to do the same with `poetry`, for example:

```
# pyproject.toml

[tool.poetry.dependencies]
django-devserver = {file = "https://github.com/dcramer/django-devserver/archive/35f9abf601e6cc2ed3cdbb78fb60018d7bd5a48d.tar.gz"}
```

This way we don't need `git` client/library to be installed on the targeted machine.

At this time of writing, when trying to install a dependency via a file the following error is raised:

```
$ poetry install

[ValueError]
File https:/github.com/dcramer/django-devserver/archive/35f9abf601e6cc2ed3cdbb78fb60018d7bd5a48d.tar.gz does not exist

install [--no-dev] [--dry-run] [-E|--extras EXTRAS] [--develop DEVELOP]
```

**Comment by PAStheLoD** [comment]
Please stale bot spare this feature request!

**Comment by finswimmer** [comment]
This should be support [now](https://python-poetry.org/docs/dependency-specification/#url-dependencies)

```toml
[tool.poetry.dependencies]
my-package = { url = "https://example.com/my-package-0.1.0.tar.gz" }
```
