### ISSUE TITLE
Version solving fails for transitive dependencies of another local poetry package

### ISSUE THREAD

**Issue by gusostow** [python-poetry/poetry#1274]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: OSX 10.14.5
- **Poetry version**: 0.12.17
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/gusostow/c24ac3d29bb2d8230addebad049f0925
## Issue

My poetry package (`db_scripts`) depends on another local poetry package (`lib`) that I created also. In the lib package I was able to install `psycopg2-binary = "^2.8.3"` just fine, but when I try to install `lib` in `db_scripts` I get the exception:

```
[SolverProblemError]
Because no versions of lib match !=0.1.0
 and lib (0.1.0) depends on psycopg2-binary (^2.8.3), every version of lib requires psycopg2-binary (^2.8.3).
So, because no versions of psycopg2-binary match >=2.8.3,<3.0.0
 and db-scripts depends on lib (*), version solving failed.
```

Which doesn't make sense because I was able to install it in the other package via poetry just beforehand. And `poetry search psycopg2-binary=2.8.3` comes up with the desired result.

Why can I install a package in a poetry project, but not in another poetry project that depends on the first one? Help is appreciated

**Comment by gusostow** [comment]
Any updates on this? This is clearly a bug. I've been having a lot trouble with using poetry for multiple projects that depend on each other.

**Comment by brycedrennan** [comment]
This bug does sound concerning.

Sorry we're a little swamped.  Until we're caught up we'll be prioritizing issues with pull requests.  If you'd like to submit a fix that would be much appreciated.

**Comment by gusostow** [comment]
@brycedrennan I'm unfamiliar with the project. Would you be able to give me a rough idea where to look

**Comment by severinsimmler** [comment]
+1

Same happens, if I add a new dependency to e.g. `lib`, and update `db_scripts` (to lock `lib`'s new dependency):
```
~/db_scripts$ poetry update ../lib
Updating dependencies
Resolving dependencies... (1.1s)

[SolverProblemError]
```

@gusostow, is a `poetry.lock` file present in your `db_scripts`? Does it work, if you delete it and let Poetry resolve all dependencies from scratch? In my case, this works (which is of course not an acceptable workflow), but we could narrow the problem down to the lock file and not to the resolver itself. This would also explain that you are able to install `lib` and do `poetry search psycopg2-binary=2.8.3`?

**Comment by sdispater** [comment]
@gusostow and @severinsimmler: Could you test with the `1.0.0b2` version to see if it's fixed?

**Comment by severinsimmler** [comment]
Unfortunately, the error still occurs in `1.0.0b2`, at least in the scenario I've described – btw, it makes no difference if I use `update` or `install`. Without a `poetry.lock` file both commands work.

**Comment by severinsimmler** [comment]
I'd like to help fixing this, but I don't have an overview of this (beautiful) project yet, a hint where to start would nice :)

**Comment by sdispater** [comment]
I just tried with the given examples and I can't reproduce the issue so there must be something else that I am not seeing

**Comment by gusostow** [comment]
Hey sorry to be chiming in late here... I investigated this more a few weeks ago and noticed that running `poetry lock` again seemed to solve it. Apologies if it was user error on my part.

If it wasn't user error there and you're having trouble reproducing it, I actually do have an archive of my project at a state where I was experiencing this problem. I'd be happy share after sanitizing it of my companies IP. Let me know if anybody wants.

I (like @severinsimmler) would also be happy to take a crack at it with the tiniest bit of initial direction.

**Comment by severinsimmler** [comment]
Oh yes, after running `poetry lock` everything works – thank you!

**Comment by agoose77** [comment]
I can confirm that I too had this issue before calling lock. I can't reproduce unfortunately as I'm using a private repo. This comment is just to reinforce the observation that it seems to resolve following a call to `lock`. Thanks for all the hard work everyone.

**Comment by avshyz** [comment]
Hi y'all.
Like @agoose77, I've also encountered the same issue until I've called `lock`

**Comment by tupui** [comment]
@finswimmer  While recreating a lock file solves the issue. The error message is still confusing and could be improved. I need to handcraft my lock files (because we still cannot exclude some deps which would be wrongly set like enum34 and functools32 with python 3.7) and adding another poetry repo led to the same issue.
