### ISSUE TITLE
poetry is undecided as to whether it really wants a blank line at the end of a `[package.source]` block

### ISSUE THREAD

**Issue by twhaples** [python-poetry/poetry#1283]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).
- **OS version and name**: `Darwin 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64` 
- **Poetry version**: `0.12.17`
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/twhaples/3596db7c5c987bb185143404f58b5183

## Issue
Poetry can't decide whether it wants a blank line at the end of a `[package.source]` block in the `poetry.lock` file. `poetry install` and `poetry update` generate a file without this blank line, while `poetry add` and `poetry remove` generate a file with this blank line.

### Steps to reproduce
1. Create a `pyproject.toml` with contents of the gist above, or another equivalent package 
2. `poetry install` to generate a new `poetry.lock` file.
3. Commit the generated `poetry.lock` to source control.
4. `poetry add envdir`
5. `poetry remove envdir`

**Expected behavior**: The changes made to `poetry.lock` have been reversed. There is no outstanding diff.

**Actual behavior**: `poetry.lock` contains a diff adding a blank line

**Impact**: Running `poetry` commands results in an outstanding git diff during normal workflow steps that should not result in an outstanding diff.

**Comment by twhaples** [comment]
stalebot, this is still a Poetry bug

**Comment by sdispater** [comment]
@twhaples Can you test with the latest beta release (`1.0.0b4`) ?

**Comment by AndrewPix** [comment]
This is still a bug with 1.0.0 release

**Comment by finswimmer** [comment]
This seems to be solved now.
