### ISSUE TITLE
poetry run script evaluates quotes

### ISSUE THREAD

**Issue by roee-allegro** [python-poetry/poetry#1302]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Linux mint
- **Poetry version**: Poetry version 1.0.0b1
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/roee-allegro/8bdac47daaf647fd909a243f25b61576

## Issue
When running a script created by `[tool.poetry.scripts]` with `poetry run`, quotes get evaluated.
Steps to reproduce:
1. run this snippet:
```
mkdir foo
cd foo
poetry init -n
mkdir foo
cat >foo/__main__.py <<EOF
import sys


def main():
    print(sys.argv[1])


if __name__ == "__main__":
    main()
EOF
```
2. Add this section to pyproject.toml:
```
[tool.poetry.scripts]
foo='foo.__main__:main'
```
3. run `poetry install`
4. run `poetry run foo '"bar"'`
5. open a poetry shell (`poetry shell`)
6. run `foo '"bar"'`

## Actual result (steps 4-6)
Inner quotes appear correctly in `poetry shell` but disappear on `poetry run`:
```
$ poetry run foo '"bar"'
bar
$ poetry shell
Spawning shell within /home/roee/.cache/pypoetry/virtualenvs/foo-YjY_nC4M-py3.6
$ foo '"bar"'
"bar"
```

## Expected result
Inner quotes appear correctly in both cases.

**Comment by Las-Wonho** [comment]
I want to work on it. Can I submit for PR for this?

**Comment by fonsecapeter** [comment]
I noticed this too, but from a slightly different angle -- looks like something about `poetry run` is updating `sys.argv` and eating quotes. 

I saw it with [a package I maintain](https://github.com/fonsecapeter/api-buddy) that takes a json string as a cli arg. Same behavior when running via poetry:
```bash
$ poetry run api post some-endpoint '{"json": "should", "keep": "doublequotes"}'
# => JSONDecodeError
# sys.argv[-1]: '{json: should, keep: doublequotes}'
```
But not if I run it on my system instead of through poetry:
```bash
$ api post some-endpoint '{"json": "should", "keep": "doublequotes"}'
# => works just fine
# sys.argv[-1]: '{"json": "should", "keep": "doublequotes"}'
```

**Comment by bertjwregeer** [comment]
Is this still an issue in the latest poetry master? There were some changes made to `poetry run` to use exec instead of popen.

**Comment by fonsecapeter** [comment]
Hi @bertjwregeer, thanks for the reply! Yep, this is in `0.12.17`. Also to be clear, this bug isn't blocking me or anything, just noticed it while I was working on that project.

Haven't looked too deep in the Poetry code, but I am noticing another error that might be a clue -- it only comes up if the run command is executed as one of the scripts defined in `pyproject.toml`. If I use @roee-allegro's example, but with `#!/usr/bin/env python` at the top of the file:

(This is all not in a `poetry shell` and on OSX, not windows)

```shell
$ ./foo.py '"can haz quotes plz"' 
# => '"can haz quotes plz"'
```

```shell
$ poetry run ./foo.py '"can haz quotes plz"'
# => "can haz quotes plz"
```

```shell
$ poetry run foo '"can haz quotes plz"' 
#   File "<string>", line 1
#     import sys; from importlib import import_module; sys.argv = ['foo', 'can
#                                                                            ^
# SyntaxError: EOL while scanning string literal
```

**Comment by bertjwregeer** [comment]
@fonsecapeter the change I am talking about is in `1.0.0b2` and is not in `0.12.17`. That is why I was asking if this was happening on the `master` branch of poetry since it should include some changes in `poetry run`.

https://github.com/sdispater/poetry/releases/tag/1.0.0b2 

> The poetry run command now uses os.execvp() rather than spawning a new subprocess.

**Comment by finswimmer** [comment]
This issue seems to be solved in the meantime. So I'm closing this.

Feel free to leave a comment if you disagree.
