### ISSUE TITLE
Remove "" from sys.path in the Python script get-poetry.py

### ISSUE THREAD

**Issue by dclong** [python-poetry/poetry#1304]
This helps avoid tricky issues when users run the command `curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
` in a directory containing Python scripts with names conflicting with official Python modules. For example, if users run the command in a directory containing his own version of `datetime.py`, the command will likely throw an exception.

**Comment by dclong** [comment]
I would be happy to submit a patch for this if it is considered as good fix.

**Comment by brycedrennan** [comment]
Makes sense. I can't think of any downsides but am worried that there's something I'm forgetting. Would be happy to look at a patch.

**Comment by dclong** [comment]
@brycedrennan Can we reopen this issue? 

BTW, I'm working a PR to fix this issue.

**Comment by abn** [comment]
`get-poetry.py` is now deprecated, please use [`install-poetry.py`](https://github.com/abn/install.python-poetry.org) instead.
