### ISSUE TITLE
Make poetry build remove older versions of packages in the dist directory

### ISSUE THREAD

**Issue by dclong** [python-poetry/poetry#1329]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Feature Request
Make `poetry build` remove older versions of packages (built before) in the dist directory. For example, support the current version of the project/package is 0.4.3 and there is a previous built package with the version 0.4.2. `poetry build` should remove the previous built package with version 0.4.2 after generating the package with version 0.4.3.

**Comment by wagnerluis1982** [comment]
I feel the request is valid, but it shouldn't be set as default operation.

I think a new argument would be the best idea here.

Something like the following would make sense...
```
poetry build --clean
```

**Comment by LukeSavefrogs** [comment]
> I think a new argument would be the best idea here.
> 
> Something like the following would make sense...
> ```
> $ poetry build --clean
> ```

I agree, that would be the best.

**Comment by LaoshuBaby** [comment]
Issue that may related to this request: #3331
