### ISSUE TITLE
License Files listing in Metadata

### ISSUE THREAD

**Issue by techdragon** [python-poetry/poetry#1350]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Feature Request

Poetry does not currently specify which files are included as license files in the appropraite Metadata field for license file names. The appropriate section of code:

https://github.com/sdispater/poetry/blob/2ed53be4f7d9c86087e4a0b82984b9a718211a9b/poetry/masonry/builders/builder.py#L158-L204 

Just needs to be extended so that it includes the gathered license files in the package metadata with the appropriate formatting. I suspect it will also need https://github.com/sdispater/poetry/blob/master/poetry/masonry/builders/builder.py#L128-L136 to be modified so that it emits a list of license specific file names that can be used when generating the license metadata. As otherwise it will not be possible to tell which of the added files are actually license files. It may be worth including a change to allow manually specifying the license files by a package maintainer while making these changes since it will probably require changes to the license file gathering code anyway.

**Comment by techdragon** [comment]
I should hopefully be able to update the PR #1367 this week.

**Comment by techdragon** [comment]
Ive updated the PR, but its still based on the develop branch, should I perhaps rebase this onto the master branch?

**Comment by brandon-leapyear** [comment]
+1 to this. It seems like a new PR needs to be opened into the `poetry-core` repo:

https://github.com/python-poetry/poetry-core/blob/403a7544cd625599e10858529aa253e67519a32b/src/poetry/core/masonry/builders/builder.py#L231

Specifically, I think the PR should include the following behavior:
* `license-file` and/or `license-files` being added to `pyproject.toml`
* Include the license file in the distribution (both sdist + wheel)
* Add `License-File` to the `METADATA` file

**Comment by jlipponen** [comment]
Any news on this feature request?

**Comment by Secrus** [comment]
Superseded by #9670
