### ISSUE TITLE
Fails to install dependencies with build dependencies on private repository

### ISSUE THREAD

**Issue by baxen** [python-poetry/poetry#1353]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: docker python:3.7
- **Poetry version**: 1.0.0b1 (and 0.12.17)
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/baxen/dd0ebec458875895494ae5ea0020a977

## Issue
I'm trying to use poetry to build a package ("test") that depends on an internal library ("sq-shoot"). That library is also built with poetry and is **hosted on a private repository**. During `poetry install` for the top level project ("test"), the install step for the dependency ("sq-shoot") fails because it can't install the build dependencies.

I am pretty sure this is because of the index-urls provided to the pip command. 

In 0.12.17 it looks like:

    ['/usr/local/bin/python',  '-m', 'pip', 'install', '--no-deps', '-index-url', 'https://nexus3.sqcorp.co/repository/pypi-square-general/simple', 'sq-shoot==1.0.3']

This one fails because it can't find the build dependencies (poetry) in that index. 

In 1.0.0b1 it is closer:

    ['/usr/local/bin/python', '-m', 'pip', 'install', '--no-deps', '--index-url', 'https://nexus3.sqcorp.co/repository/pypi-square-general/simple', '--extra-index-url', 'https://pypi.org/', 'sq-shoot==1.0.3']

where it has clearly set pypi as a backup index but I believe the url is wrong. Should be `https://pypi.org/simple`?

I can fix the issue in 1.0.0b1 by manually setting a default source: https://gist.github.com/baxen/87ff019bbbe08acfadfa107a845e939d . But I imagine that this is supposed to work with pypi out of the box. I am not exactly sure where in the code base this should be fixed, but I was able to make a quick patch by adding `+ '/simple'` to the `authenticated_url` here: https://github.com/sdispater/poetry/blob/develop/poetry/repositories/pypi_repository.py#L87

If that solution sounds good I'm happy to open a PR! And thanks for the wonderful tool :)

**Comment by igolan89** [comment]
same problem here.
when trying to install an sdist (tar.gz) from a private repo, the build backend tries to search for poetry in the private repo, and it's not there.

**Comment by drrlvn** [comment]
I'm having this issue as well and I too think the issue is that the index passed is `https://pypi.org/` instead of `https://pypi.org/simple`.

**Comment by baxen** [comment]
This appears to be fixed in 1.0.5! 🙏
