### ISSUE TITLE
pip doesn't use repository defined in pyproject.toml

### ISSUE THREAD

**Issue by maksbotan** [python-poetry/poetry#1356]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS 10.14.6
- **Poetry version**: 0.12.17

## Issue

I have a project with `pyproject.toml` which references a private PyPI with `[[tool.poetry.source]]` and uses some dependencies available only in that PyPI.

Next, I try to install this project using only pip like so:

```console
$ pip install git+ssh://git@github.com/USER/REPO
```

`pip` is able to clone repo, install poetry and run as per PEP 517/518, but fails to find the private dependency.

Currently to overcome this I have to specify index url explicitly:

```console
$ pip install --index-url MY_PYPI git+ssh://git@github.com/USER/REPO
```

In my opinion, this is not very convenient for users of my project. Is there any way to make poetry add extra sources when executed in PEP 517 workflow?

**Comment by pgilad** [comment]
I think this problem goes even further, if you do `poetry build` and then try to install your package the source (index-url) isn't preserved at all

**Comment by abn** [comment]
This is expected behaviour. If you require a direct reference to the package instead, add it as a URL dependency. This is because wheel metadata has no mechanism to define source indexes. See also [PEP 508](https://peps.python.org/pep-0508/).

The source configurations are specific to poetry and is not understood by other PEP 517 frontends like pip.
