### ISSUE TITLE
Progress bar bug while publishing packages

### ISSUE THREAD

**Issue by maggyero** [python-poetry/poetry#1370]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows 10
- **Poetry version**: 0.12.17

## Issue

While publishing a Python package to a private repository, the "- Uploading {file} {percentage}" line gets printed _three times_ for each file instead of _once_:

```
$ poetry publish -r local -u . -p .

Publishing file_proxy (0.0.1) to local
 - Uploading file_proxy-0.0.1-py3-none-any.whl 0%
 - Uploading file_proxy-0.0.1-py3-none-any.whl 100%
 - Uploading file_proxy-0.0.1-py3-none-any.whl 100%
 - Uploading file_proxy-0.0.1.tar.gz 0%
 - Uploading file_proxy-0.0.1.tar.gz 100%
 - Uploading file_proxy-0.0.1.tar.gz 100%
```

The body of the [`poetry.masonry.publishing.uploader._upload_file`](https://github.com/sdispater/poetry/blob/master/poetry/masonry/publishing/uploader.py#L206) method indicates that a `requests_toolbelt.multipart.MultipartEncoderMonitor` decorator is used with a `lambda monitor: bar.set_progress(monitor.bytes_read)` callback. Here the progress bar is an instance of the `clikit.ui.components.progress_bar.ProgressBar` class (Clikit is a library used by Poetry from the same author). Looking at the method [`clikit.ui.components.progress_bar.ProgressBar.__init__`](https://github.com/sdispater/clikit/blob/master/src/clikit/ui/components/progress_bar.py#L58) method, we see that output overwrite is disabled when the `self._io.error_output.supports_ansi` function considers that the output does not support ANSI code pages.

On Windows:

- [ANSI code pages](https://en.wikipedia.org/wiki/Windows_code_page#ANSI_code_page) (such as CP-1252) are used for applications with a _graphical_ user interface;
- [OEM code pages](https://en.wikipedia.org/wiki/Windows_code_page#OEM_code_page) (such as CP-437 or CP-850) are used for applications with a _textual_ user interface.

I am using Powershell 5.1 with the default OEM code page CP-850. Since it is not an ANSI code page, Poetry output is expected. However, switching to the ANSI code page CP-1252 gives the same output:

```
$ chcp 1252
$ poetry publish -r local -u . -p .

Publishing file_proxy (0.0.1) to local
 - Uploading file_proxy-0.0.1-py3-none-any.whl 0%
 - Uploading file_proxy-0.0.1-py3-none-any.whl 100%
 - Uploading file_proxy-0.0.1-py3-none-any.whl 100%
 - Uploading file_proxy-0.0.1.tar.gz 0%
 - Uploading file_proxy-0.0.1.tar.gz 100%
 - Uploading file_proxy-0.0.1.tar.gz 100%
```

So the only solution is to force ANSI output using the `--ansi` command-line argument:

```
$ poetry publish --ansi -r local -u . -p .

Publishing file_proxy (0.0.1) to local
 - Uploading file_proxy-0.0.1-py3-none-any.whl 100%
 - Uploading file_proxy-0.0.1.tar.gz 100%
```

But this is a workaround. Why does the `self._io.error_output.supports_ansi` function considers that Powershell 5.1 does not support ANSI code pages when using the ANSI code page CP-1252?

**Comment by maggyero** [comment]
@sdispater Tu as une idée Sébastien ?

**Comment by maggyero** [comment]
Up.

**Comment by Secrus** [comment]
This issue has long been stale, I am going to close it now. Please open a new issue with a reproduction if you believe this happens in a supported version of Poetry.
