### ISSUE TITLE
Can I obfuscate source code when 'build' or 'publish'

### ISSUE THREAD

**Issue by newbieh4cker** [python-poetry/poetry#1385]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Question

Can I obfuscate the source code of .py file while 'poetry build' or 'poetry publish' ??

**Comment by mwchase** [comment]
I handled code generation in a project by invoking Poetry in a task runner, and having the code generation run as a prerequisite task. This does have the slight disadvantage that, while #1094 is a thing, you need to either carefully keep the generated code in sync, or have uselessly huge status output, or don't use git.

**Comment by stinovlas** [comment]
You can add your own build script that does arbitrary job. This is an undocumented feature at the moment, see #1453. Please note, that only your `wheel` distribution will be affected, not `sdist` (your build script will be added to generated `setup.py`, but it will only be executed upon installation, which is how `sdist` works, basically).
