### ISSUE TITLE
support for venv --system-site-packages

### ISSUE THREAD

**Issue by TwinT** [python-poetry/poetry#1393]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Feature Request

Adding support for **--system-site-packages**, as described in [venv documentation](https://docs.python.org/3/library/venv.html), makes possible to have a set of base common packages available for a number of virtual environments, thus saving disk space and reducing environment creation time. I believe that this option gives some useful extra flexibility on package and environment management.

**Comment by kam1sh** [comment]
As I see, virtual environments creates via `venv.EnvBuilder` and `virtualenv.create_environment`:
https://github.com/sdispater/poetry/blob/df98fd289b9b629d2171900c1b1bddcee3696cff/poetry/utils/env.py#L301-L319
...so it shouldn'be hard.

I see this as a setting in `poetry config` with somethink like `settings.virtualenvs.include-system-packages`. Will (try to) implement tomorrow.

**Comment by rnc** [comment]
This would be very useful as its a significant space saving - e.g. on a single small repository the difference was 150MB of dependencies - multiply that out and its soon worthwhile.

**Comment by danielsig727** [comment]
someone please revive #1404 :'( 
I also need that feature since I have some private packages needs to be globally available, otherwise poetry cannot even run its `setup.py` since missing packages.

**Comment by frankier** [comment]
I agree this functionality would be useful in Poetry, but for the meantime here are some workarounds (cross-posting across related issues):

Use case 1) I just want to save space use by my virtualenvs:

1. Install https://rdfind.pauldreik.se/
2. cd ~/.cache/pypoetry/virtualenvs/ && rdfind -makehardlinks true .

Use case 2) I need to use a globally installed package from my poetry venv.

1. Open ~/.cache/pypoetry/virtualenvs/myvenv/pyvenv.cfg
2. Set `include-system-site-packages = true`

**Comment by stackErr-NameNotResolved** [comment]
This issue seems to be merged and closed but actually never released? Using Poetry 1.1.13:

poetry config virtualenvs.options.system-site-packages true

  ValueError

  Setting virtualenvs.options.system-site-packages does not exist

**Comment by Eric-Swiftly** [comment]
It looks like it is included in the [release notes for 1.2.0a1](https://github.com/python-poetry/poetry/releases/tag/1.2.0a1)

**Comment by couling** [comment]
What's the behaviour of this? Will it default to using the system site package versions when doing `poetry update` or `poetry install` without a lock file?

**Comment by rpdelaney** [comment]
@awoimbee Can't you just install whatever dependencies at build time? I would think that dockerizing the environment would obviate a `--system-site-packages` option, but maybe I don't understand your use case?

**Comment by awoimbee** [comment]
As is often the case here, my issue is mostly with pytorch. It's >1GB, which is an issue when building/pushing/pulling the same container again and again (my `poetry install` layer is way too big).
To reuse image layers (faster image build/push/pull), I want a base image with cuda, torch, ... (think https://hub.docker.com/r/pytorch/pytorch but custom) and then I want to build my application container on top of this base image.
The resulting application container shall be used in prod and as a dev container (with minor differences between the two).

Possible solutions:
- `virtualenvs.create false`: breaks some system dependencies, is not suitable for a dev env 
- conda environments: not the best (I won't go into details)
- `settings.virtualenvs.include-system-packages`: seems like the perfect solution
  But no ! `poetry` with `settings.virtualenvs.include-system-packages` will re-install torch (and other packages), leading to an even slower build time and an even larger container.

**Comment by jemshit** [comment]
Any way to include brew's pip environment packages?

**Comment by rpdelaney** [comment]
OK, thanks for the explanation. My docker-fu is not strong enough to suggest solutions in that direction...
