### ISSUE TITLE
Installing wheel fails with "[ValueError] Could not parse version constraint"

### ISSUE THREAD

**Issue by willcl-ark** [python-poetry/poetry#1409]
- [x ] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x ] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: MacOS 10.14
- **Poetry version**: 0.12.17
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue
trying to `poetry add` a wheel hosted on GitHub fails with `[ValueError] Could not parse version constraint`. Specifically, this wheel: https://github.com/gotenna/PublicSDK/raw/master/python-public-sdk/goTenna-0.12.5-py3-none-any.whl

I also tried downloading the wheel and installing from local disk, with same error.

**Comment by HacKanCuBa** [comment]
Try running `poetry add -vvv ...` to get traceback information

**Comment by src-r-r** [comment]
I can confirm the bug for URLs:

```
> poetry add git+https://github.com/django-nonrel/django.git
                                                                             
[ValueError]                                                  
Could not parse version constraint: //github.com/django-nonrel/django.git  
                                                                             
add [-D|--dev] [--git GIT] [--path PATH] [-E|--extras EXTRAS] [--optional] [--python PYTHON] [--platform PLATFORM] [--allow-prereleases] [--dry-run] [--] <name> (<name>)...
```

**Comment by HacKanCuBa** [comment]
> I can confirm the bug for URLs:
> 
> ```
> > poetry add git+https://github.com/django-nonrel/django.git
>                                                                              
> [ValueError]                                                  
> Could not parse version constraint: //github.com/django-nonrel/django.git  
>                                                                              
> add [-D|--dev] [--git GIT] [--path PATH] [-E|--extras EXTRAS] [--optional] [--python PYTHON] [--platform PLATFORM] [--allow-prereleases] [--dry-run] [--] <name> (<name>)...
> ```

Can you run `poetry add -vvv ...`  to get more info?

**Comment by finswimmer** [comment]
Hello @src-r-r ,

this issue is talking about version parsing problems during installing a wheel and not a plain project from git.

The original issue seems to be fixed in the current release. So I will close it.

In your case the problem is, that poetry needs to parse the `setup.py`. There the version is loaded dynamically from another resource. Because poetry doesn't run the `setup.py` it is unable to get the version.

fin swimmer
