### ISSUE TITLE
Feature Request: add lock file versioning

### ISSUE THREAD

**Issue by janw** [python-poetry/poetry#1410]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Feature Request

Feature: A version field to Poetry's lock file

Hey! 👋  I'd like to propose adding a `version` (or similar) metadata field to the poetry lock file to allow for future changes to the lock file layout. I know this is not at all planned but it might be a good idea to start versioning the lock file as early as possible, and especially before Poetry 1.0.

### Reasoning

Extraneous tools might want to read the contents of the lock file, for example for dependency scanning (as implemented by GitLab, or GitHub) which want to be able to rely on a certain layout of the lock file.

Disclaimer: I'm currently contributing added support for Poetry to GitLab's Dependency Scanning feature, and therefore am interested to see the versioning implemented for Poetry's lock file. 

Apart from that even Poetry itself might at some point want to change the lock file layout, and want to differentiate between the different layout versions.

### Examples from other tools

* Yarn's `yarn.lock` file [has a comment stating the version](https://yarnpkg.com/lang/en/docs/yarn-lock/)
* Pipenv has a [`pipfile-spec` versioning](https://github.com/pypa/pipenv/blob/master/Pipfile.lock#L6)
* Npm has the [`lockfileVersion](https://docs.npmjs.com/files/package-lock.json#lockfileversion)

### Required work

Adding a "1.0" version tag to the current state of the lock file is trivial. I'd place it in the `[metadata]` section. Loading the lock file in Poetry should then have a version check as well.

Of course I'd be happy to implement the feature if it is agreed upon!

**Comment by janw** [comment]
Of course I'd be happy to implement the feature if it is agreed upon!

**Comment by janw** [comment]
@sdispater Any comment on this?

**Comment by finswimmer** [comment]
Hello,

lock file versioning is available since poetry 1.0.10: https://github.com/python-poetry/poetry/releases/tag/1.0.10

fin swimmer
