### ISSUE TITLE
Installer does not crate .profile or .zprofile if it doesn't exist

### ISSUE THREAD

**Issue by smtc-andre** [python-poetry/poetry#1429]
By executing `curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python` the installer does not set the path variable `$HOME/.poetry/bin` if the files `.profile` and `.zprofile` do not exist.

Would be nice, if it would be created if it does not exist.

**Comment by mtizima** [comment]
I will take this task

**Comment by augustonasser** [comment]
I've run into this issue as well. Took me a while to figure out what was wrong. 
I'll try to fix this.

**Comment by finswimmer** [comment]
The `get-poetry.py` scrip is deprecated and will be replaced by `install-poetry.py`. It was decided to not modify any dot file at all.

See https://python-poetry.org/blog/announcing-poetry-1.2.0a1/#deprecation-of-the-get-poetrypy-script
