### ISSUE TITLE
Provide way to export only development dependencies

### ISSUE THREAD

**Issue by homeworkprod** [python-poetry/poetry#1441]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Feature Request

I'm using Poetry v1.0.0b for this, which (as opposed to v0.12.x) includes the `export` command.

I come from a background where core dependencies are defined in `requirements.txt` and development ones in `requirements-dev.txt` (or similar). Test dependencies might have their own file as well (e.g. to only install what's necessary to test on CI systems, but not debug and documentation tools).

My issue is that while I can (re-)create the core requirements file via `poetry export -f requirements.txt --without-hashes -o requirements.txt`, I cannot do the same for the list of (only) development dependencies.

There is the `--dev` option for the `export` command ("Include development dependencies."), but it *includes* the core dependencies, too. Thus, the result is not the list of additional dependencies that required for development purposes only.

I'm not sure how this can be solved without breaking the (probably useful) use case of exporting all dependencies together.
- Maybe a `--dev-only` option? 
- Or make `--dev` output only development dependencies, but not core ones? And
- introduce `--all` to output both core and development dependencies?
  - Should these include extras? If not, and I don't think they should, is the name "all" appropriate?

**Comment by finswimmer** [comment]
I like the idea, and I think it would be a useful feature for the `--extras` packages as well. My two favorite implementation would be:

* `--dev-only`/ `--extras-only` as parameters
* ` -f requirements-dev.txt`/`-f requirements-extra.txt`

If we can get a consensus about the way, I think I would be able to implement  such feature. 

@sdispater What's you opinion?

**Comment by RCheese** [comment]
https://github.com/RCheese/deplodocker
now I am using not enough DRY )

**Comment by kodekracker** [comment]
@python-poetry/triage Any new updates on this issue ? This feature would be very useful.

**Comment by njoyce** [comment]
I just started looking at moving from pipenv to poetry and this issue came up.

**Comment by vchrombie** [comment]
I have faced a similar situation and wrote this small tool [vchrombie/peodd](https://github.com/vchrombie/peodd) (poetry export, but only for dev-dependencies) for this purpose.

You can install using pip
```
$ pip install peodd
```
and use it direclty from the command line
```
$ peodd -o requirements-dev.txt
```

The `requirements-dev.txt` would have the dev-dependencies (in the requirements.txt format) which would be ready to use.
I have tested the poetry versions format `^n.n.n`, `>=n.n.n`, `n.n.n` and they worked fine. Hoping to add the rest of the formats too.

It would be great if you can try using the tool and provide feedback.

Thanks in advance.

**Comment by mkniewallner** [comment]
`export` command is being replaced by [a plugin](https://github.com/python-poetry/poetry-plugin-export) in Poetry 1.2, which should solve the use cases you mentioned.

Tested on latest version with the plugin:
```shell
curl -sSL https://install.python-poetry.org | python - --git https://github.com/python-poetry/poetry.git@master
poetry plugin add poetry-plugin-export
```

Then:
```shell
# Export main + dev dependencies
poetry export -f requirements.txt --output requirements.txt --with dev

# Export main dependencies
poetry export -f requirements.txt --output requirements_without_dev.txt

# Export dev dependencies only
poetry export -f requirements.txt --output requirements_only_dev.txt --only dev
```

Could you confirm if it solves all your use cases?

**Comment by mkniewallner** [comment]
Closing, since this is implemented now (see https://github.com/python-poetry/poetry/issues/1441#issuecomment-1140246353).
