### ISSUE TITLE
Poetry version command format first without bumping

### ISSUE THREAD

**Issue by Lothiraldan** [python-poetry/poetry#1442]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Fedora 29
- **Poetry version**: 1.0.0b1
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://bitbucket.org/lothiraldan/mercurial_litf/src/0a7289b41ade534da56b9c40118c7fb6ea3a06c2/pyproject.toml

## Issue

I have added a `scripts` section to my pyproject.toml at the end then I tried to run `poetry version minor -vvv` which seems to output the right thing:

```
Bumping version from 0.1.1 to 0.2.0
```

But checking the diff, the `scripts` section was only moved to its right place:

```diff
diff --git a/pyproject.toml b/pyproject.toml
--- a/pyproject.toml
+++ b/pyproject.toml
@@ -13,9 +13,9 @@ python = "^2.7 || ^3.6 || ^3.7"
 
 [tool.poetry.dev-dependencies]
 
+[tool.poetry.scripts]
+mercurial-litf = "mercurial_litf.cli:main"
 [build-system]
 requires = ["poetry>=0.12"]
 build-backend = "poetry.masonry.api"
 
-[tool.poetry.scripts]
-mercurial-litf = "mercurial_litf.cli:main"
```

If I rerun once again `poetry version minor -vvv`, the version is correctly bumped:

```diff
diff --git a/pyproject.toml b/pyproject.toml
--- a/pyproject.toml
+++ b/pyproject.toml
@@ -1,6 +1,6 @@
 [tool.poetry]
 name = "mercurial-litf"
-version = "0.1.1"
+version = "0.2.0"
 description = "A litf plugin for the Mercurial test runner"
 authors = ["Boris Feld <lothiraldan@gmail.com>"]
 license = "MIT"
@@ -13,9 +13,9 @@ python = "^2.7 || ^3.6 || ^3.7"
 
 [tool.poetry.dev-dependencies]
 
+[tool.poetry.scripts]
+mercurial-litf = "mercurial_litf.cli:main"
 [build-system]
 requires = ["poetry>=0.12"]
 build-backend = "poetry.masonry.api"
 
-[tool.poetry.scripts]
-mercurial-litf = "mercurial_litf.cli:main"
```

I can reproduce every time and I was on the latest release of poetry so it's not a regression on the `1.0.0b1`.

I just wanted to confirm that it's indeed a bug before submitting a patch.

**Comment by finswimmer** [comment]
Hey @Lothiraldan ,

could you please check the behavior with the latest preview? For me it works.

Thanks!
