### ISSUE TITLE
Installing *.whl from GitHub release url from private repo

### ISSUE THREAD

**Issue by hc2683** [python-poetry/poetry#1444]
- [ x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [ x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Feature Request

I think it would be immensely useful for development purposes for it to be possible to add the ability to install from a GitHub release. It doesn't fall under the banner of the git feature because we don't want to actually copy or compile the repository, and the url= functionality in project.toml doesn't work because that doesn't pass the correct GitHub credentials (when required).

Since Github releases ask for compiled binaries, installation files etc., being able to install from these links would be immensely useful when in the development stage (where using a public or private repo is not yet possible).

**Comment by conraddd** [comment]
Any update on this feature request? It would be very useful if poetry supports github private repo's release wheel file.

**Comment by ruohola** [comment]
Any update on this?

**Comment by el-iot** [comment]
I would also be very interested in this :+1:

**Comment by Philippe-Neveux** [comment]
Hello everyone, this feature also interested me :)
