### ISSUE TITLE
Add command with git+http fails

### ISSUE THREAD

**Issue by HacKanCuBa** [python-poetry/poetry#1452]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Debian GNU/Linux 10 (buster)
- **Poetry version**: 1.0.0b1
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue

Executing `poetry add git+http://my.repo/group/project.git` fails because of a parsing error in 

https://github.com/sdispater/poetry/blob/develop/poetry/console/commands/init.py#L365

Given that `git+http` is not supported. I know that we shouldn't use non-https repos but, VPN and policies and so on, we have to.

An easy solution is to avoid the add command altogether and just write it manually into pyproject.toml and then run `poetry update`.  
But a better fix would be to add `git+http` to the list, which is what I did locally and the issue got fixed.

**Comment by HacKanCuBa** [comment]
Well, should I submit a patch to support `git+http`? It's simply adding it to the mentioned list :P

**Comment by finswimmer** [comment]
Hello @HacKanCuBa ,

this should work with latest release.

fin swimmer

**Comment by HacKanCuBa** [comment]
Hmmm i'm not seeing any change neither in master nor develop regarding this, but i'm no longer able to test this isse, so i'm leaving it closed.
