### ISSUE TITLE
Support for extra entrypoints / plugins / scripts

### ISSUE THREAD

**Issue by funkyfuture** [python-poetry/poetry#1454]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Feature Request

package metadata allows entrypoints (plugins and scripts in poetry) to depend on specific extras. [here](https://packaging.python.org/specifications/entry-points/#file-format) this example is given:

```ini
[console_scripts]
foobar = foomod:main_bar [bar,baz]
```

so the console script `foobar` would only get installed when the extras `bar` and `baz` are specified.

afaict this is currently not supported. if i'm wrong with that, i'd be happy to extend the docs in this regards, but i would need advice about the configurations syntax.

**Comment by bradsbrown** [comment]
@funkyfuture I opened a PR to extend the docs for this very topic a while back that is still pending but may be helpful to you -- https://github.com/sdispater/poetry/pull/1181/files

**Comment by funkyfuture** [comment]
thanks for the hint! i leave it to the maintainers whether to keep this issue open as reminder until a release.

**Comment by funkyfuture** [comment]
looking at the schema, it seems that isn't implemented for plugins yet.

**Comment by pawamoy** [comment]
So if I understand correctly, extras are implemented for poetry's `scripts` but not for poetry's `plugins`? And a PR is pending to improve the documentation on that matter.

In this case, @funkyfuture could you change the title to contain "plugins" only?

**Comment by funkyfuture** [comment]
yes, that is correct.

i deliberately chose all the terms in the title in order for the issue to be found. eg me would search for entrypoints.

**Comment by pawamoy** [comment]
And I found your issue too but it was a false positive haha 😄 But I do get your point

**Comment by funkyfuture** [comment]
@sdispater i think this feature should be available with the first major release.

**Comment by abn** [comment]
This should looked at after #2310 is ready. We could add this as a property of the script or the better the extras themselves similar to optional dependencies.

**Comment by Secrus** [comment]
I am going to pull the plug on this. According to [this](https://packaging.python.org/en/latest/specifications/entry-points/#data-model):
> Using extras for an entry point is no longer recommended. Consumers should support parsing them from existing distributions, but may then ignore them. New publishing tools need not support specifying extras. The functionality of handling extras was tied to setuptools’ model of managing ‘egg’ packages, but newer tools such as pip and virtualenv use a different model.

So basically, while I understand that this could be a nice option, this is something that is not supported by other tools in Python ecosystem. We are working towards better integration with official standards, so as this is not recommended, it's unlikely that Poetry will support it.

**Comment by Nicoretti** [comment]
@Secrus thanks for the fast feedback!
It wasn't the answer I hoped to hear, but one I can work with, thx.
