### ISSUE TITLE
Support for Nix package manager as recommended installer `nix-env`

### ISSUE THREAD

**Issue by jamesohortle** [python-poetry/poetry#1472]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Feature Request

I am pretty new to both [Nix](https://nixos.org/nix/) and Poetry, but it would be nice to have it supported as a recommended installer so we can simply go `poetry self:update` instead of `nix-env -u poetry` when stable releases come out. I have read the docs and have seen the warning `The self:update command will only work if you used the recommended installer to install Poetry.` so my request is simply to make Nix a recommended installer.

However, I am not sure how this interacts with Nix itself, given that packages that update themselves in-place seem to throw errors? The only thing I could really find was [this thread from 2014](https://nixos.org/nix-dev/2014-September/014476.html).

Perhaps calling `poetry self:update` should just call `nix-env -u poetry`, if Poetry was installed using Nix.

At the moment, of course, I just receive the following error.

```bash
[RuntimeError]                                                    
Poetry was not installed with the recommended installer. Cannot update automa  
tically.                                                                       
                                                                                 
self:update [--preview] [--] [<version>]
```

**Comment by jnoortheen** [comment]
nix-env is not the only way to install packages. If one is using nixOS or home-manager, they would be declaring it inside a file.
