### ISSUE TITLE
Document/publish API to parse the pyproject.toml [tool.poetry] table

### ISSUE THREAD

**Issue by dev-zero** [python-poetry/poetry#1478]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Feature Request

A project I'm contributing to uses the `entry point` system to register plugins. To get a list of plugins in a [registry](https://github.com/aiidateam/aiida-registry) they parse the "in-vcs" `setup.json/setup.py` files of the registered plugin packages to get the number and type of plugins an external package provides.
While we could easily parse the relevant list of `plugins`, I feel it would be more appropriate to implement and document some sort of Python API to access the parsed and interpreted information from Poetry itself.

**Comment by finswimmer** [comment]
Hello,

there are python libraries out there that can parse `*.toml` files easily like [toml](https://pypi.org/project/toml/) or [tomlkit](https://pypi.org/project/tomlkit/).

So there is no need that poetry itself provide an API to parse it :)

fin swimmer
