### ISSUE TITLE
Custom build steps to generate files

### ISSUE THREAD

**Issue by foogod** [python-poetry/poetry#1486]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Feature Request

I've searched through the docs and tried to search through the issue tracker and as far as I can tell there's currently no support for this in Poetry?

I have a project which requires automatically generating some of the *.py files that should be bundled into the final wheel package.  Is there any way to add an extra build step to call a custom entrypoint or execute a custom script before bundling everything up?

If not, are there any plans to implement this?  (I would be happy to help with implementing this..)

**Comment by stinovlas** [comment]
See  #1453.

**Comment by nealkruis** [comment]
@finswimmer, can you explain why this was closed?

**Comment by ben-xD** [comment]
@finswimmer, #1453 is also closed (since 2019). I guess the idea is to leave 1 relevant issue open?

That was closed in 2019 because the feature was not finished. It's not too relevant to close this (#1486) now. Can we re-open it>
