### ISSUE TITLE
keep old line breaker

### ISSUE THREAD

**Issue by Trim21** [python-poetry/poetry#1488]
- [X] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Feature Request

I'm using poetry on windows or Linux.

So I may lock deps both on windows and Linux. But the line endings of `poetry.lock` and `pyproject.toml` are different on Linux and windows. 

I'm considering if poetry could check original line endings and keep it when generating a new lock file.

**Comment by Trim21** [comment]
Or make it `LF` in any system to make sure it's same on all system.

**Comment by tigerhawkvok** [comment]
A config option to always use one or the other would work, too. I always want LF endings, never CRLF, even on Windows.

**Comment by Trim21** [comment]
Looks like this feature has already been added. so closing it.
