### ISSUE TITLE
Ability to do custom actions before build

### ISSUE THREAD

**Issue by vBLFTePebWNi6c** [python-poetry/poetry#1490]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Question
Our team have a private repository in which we develops python-packages that later includes in our main projects. We prefer to install these packages directly from git. The problem is that these packages requires download some binaries before building. Am I right that this problem can not be solved in described settings untill the plugin system release?

**Comment by finswimmer** [comment]
The plugin-system can now be tested with the current preview release 1.2.0a. See: https://python-poetry.org/blog/announcing-poetry-1.2.0a1/#deprecation-of-the-get-poetrypy-script
