### ISSUE TITLE
Do not accept abbreviations as commands

### ISSUE THREAD

**Issue by sassanh** [python-poetry/poetry#1496]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Feature Request

First of all I want to thank you for this fantastic tool you've created.

I was using poetry stable release 0.12 and wanted to complain about abbreviated commands being accepted, I checked prerelease version 1.0.0b2 and saw that it doesn't accept abbreviated commands anymore. I wanted to make sure it's intentional so I did a bisect and saw this commit is responsible for this change: https://github.com/sdispater/poetry/commit/2ff796ed4914253a110aa0632e0598aa2967dcf9

It just updates the cleo version. So I got worried that this change wasn't intentional. So I'm gonna share my reasoning why I think we should not accept abbreviated commands (keep it as it is in 1.0.0b2 and not treat it as a regression):

I think accepting abbreviated version of commands (like `poetry up` for `poetry update`) is not appropriate for python community. This kind of stuff are welcomed in JS community (for example `npm i`) but I don't think it's appropriate here. My reasoning is that it encourages cryptic and unreadable commands. Suppose that someone writing a blog puts a lot of `poetry ad` and `poetry up` commands in his blog post, it's ugly, it's not readable, Python is known for being a readable language, many Python statements can be read like human language statements. Python blocks are defined by indentation. So I think it's very important for tools created for Python environment to follow this philosophy and avoid introducing cryptic syntax. Someone may argue that poetry can support both syntax and user can chose but I don't think it's a valid reasoning, because we should enforce complete readable syntax so that every code/document/blog post/etc that's created in this environment satisfies readability standards of the environment.

So I ask you to don't treat this change introduced by commit above as a regression and instead embrace it and update the docs (like this one https://poetry.eustace.io/docs/cli/) accordingly so that we never see some ugly cryptic stuff like `poetry ab` or `poetry ad` or `poetry ins` in a document ever again.

P.S. I noticed I created this issue as a feature request, at the time of choosing between different types of issues I wasn't aware it's solved in 1.0.0b2 and I noticed when I already wrote most of it. Maybe we should change the label. The purpose of this issue is solely to bring the attention of repository maintainers to the concern discussed above.

**Comment by finswimmer** [comment]
Hello,

the current version doesn't accept abbreviations any longer. Instead the user will receive a message like this: "Did you mean this? add"?

fin swimmer

**Comment by sassanh** [comment]
@finswimmer I suggest keeping this issue open until this doc is updated: https://python-poetry.org/docs/cli/
Currently it explicitly says that abbreviations are accepted which is misleading.

**Comment by finswimmer** [comment]
Good catch @sassanh :+1: 

Documentation fix is on the way: #2379
