### ISSUE TITLE
`poetry run` regression for handling command flags

### ISSUE THREAD

**Issue by wesleykendall** [python-poetry/poetry#1500]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Darwin 10.14.6
- **Poetry version**: 1.0.0.b3
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue
In `poetry==1.0.0.b3`, it seems that `poetry run` interprets any CLI options as its own rather than passing them through.

For example:

```
poetry run python manage.py makemigrations --check

> [NoSuchOptionException]
> The "--check" option does not exist.
```

In `poetry==1.0.0.b1`, this was not an issue.

This can be re-created by basic commands like so:

```
poetry run ls -l

[NoSuchOptionException]
The "-l" option does not exist.
```

**Comment by wesleykendall** [comment]
@sdispater just wanted to bring this to your attention since the upgrade of `clikit` to `0.4` caused a regression in `poetry==1.0.0b1`, which led me to try out using `poetry==1.0.0.b3` and find this issue

**Comment by wesleykendall** [comment]
The workaround that I'm going to try doing for this is reverting back to `poetry==1.0.0.b1` and then pinning `clikit` to an earlier version. Or making my own fork of `poetry==1.0.0.b1` and restricting this subdependency in the `pyproject.toml`

**Comment by wesleykendall** [comment]
I made a couple follow-up comments on this thread that were inaccurate, so I deleted them in order to avoid confusion.

The workaround I'm going to use for now is reverting back to `poetry==1.0.0b1` since it seems to be working fine still.

**Comment by wesleykendall** [comment]
For those running into issues installing `poetry==1.0.0.b1` with pipx, this is the workaround I did:

```
pipx install poetry==1.0.0.b1
pipx runpip poetry==1.0.0b1 install cleo==0.7.5 clikit==0.3.2
```

**Comment by M5oul** [comment]
For Pip:
```bash
pip3 install --user poetry==1.0.0b2 cleo==0.7.5 clikit==0.3.2
```

**Comment by max-wittig** [comment]
Same here.

**Comment by n8sty** [comment]
I'm experiencing this on Ubunut 18 as well. An example when trying to invoke `pre-commit`:

```
15:15 $ poetry run pre-commit run --all-files

[NoSuchOptionException]
The "--all-files" option does not exist.
```

**Comment by c0state** [comment]
If you upgrade to `1.0.0b3`, you need to use `--` to stop options parsing now it looks like.

See this change in the `clikit` dependency which poetry uses:
https://github.com/sdispater/clikit/pull/2

**Comment by 515hikaru** [comment]
I could show `python --help` with `poetry run` by following:

```
poetry run python -- --help
```

In Poetry version 1.0.0b3

**Comment by n8sty** [comment]
> I'm experiencing this on Ubuntu 18 with 1.0.0b3 as well. An example when trying to invoke `pre-commit`:
> 
> ```
> 15:15 $ poetry run pre-commit run --all-files
> 
> [NoSuchOptionException]
> The "--all-files" option does not exist.
> ```

I can confirm that `poetry run pre-commit -- run --all-files` works. It seems like it doesn't particularly matter where the `--` gets put in the command as `poetry run -- pre-commit run --all-files` and `poetry run pre-commit run -- --all-files` seem to have the same effect.

**Comment by itajaja** [comment]
This is really surprising and unexpected behavior. compare:

```sh
poetry run python abc
poetry run python --abc
```

in the former case, `abc` is passed to python, in the latter it is passed to poetry. It's really weird that the discriminant is whether is an option or a vararg. afaict no state of the art cli behaves this way. if you really wanted to discriminate where an argument is passed, the `docker` behavior is more suitable

```sh
docker run --foo image bash # foo passed to docker
docker run image bash --foo # foo passed to subcommand
```

**Comment by itajaja** [comment]
usage of -- is legitimate when there is an ambiguity, which is not the case for `poetry run`

**Comment by sdispater** [comment]
Commit 85dc9a1 should fix most of the issues with the `run` command.

I will try to make a new beta release this week.

**Comment by n8sty** [comment]
Seems like with version 1.0.0b4 this is working again - at least in my case above

**Comment by bersace** [comment]
I confirm the fix. 1.0.0b4 is ok. Merci @sdispater !

**Comment by wesleykendall** [comment]
Thanks @sdispater ! Should I close this?

**Comment by applied-mathematician** [comment]
I'm still having this issue with poetry 1.0.5.  In my Ansible script I have the shell command
```"poetry run manage sync_worker_commands --settings {{ django_settings_module }}"```
which fails unless I add an extra --.

**Comment by 1oglop1** [comment]
@sdispater Has this been resolved?
I'm still getting an issue when I run `poetry -v run pytest --record-mode=none`
The same thing is wrong in when run in `tox` :( 
I'm on `Poetry version 1.0.10`

**Comment by ekamperi** [comment]
Hi folks, the issue is still there in 1.1.13. Very frustrating. Any workarounds? Thanks!
