### ISSUE TITLE
Resolver writes incorrect version into the lock file for packages with numbers in the name

### ISSUE THREAD

**Issue by kleschenko** [python-poetry/poetry#1506]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: osx
- **Poetry version**: 1.0.0b3
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/kleschenko/4a694278ea08be4bce9f48926985a952

## Issue
I've found an issue with packages that have a hyphen followed by the number in their name. (for legacy repositories)
For example, I have this line in my `pyproject.toml`:
```
mandrill-37 = ">=1.1.0"
```
and after the `poetry lock` command there will be a following entry in the `poetry.lock`:
```
[[package]]
description = "A CLI client and Python API library for the Mandrill email as a service platform. Forked fork python 3.7 support"
name = "mandrill-37"
optional = false
python-versions = "*"
version = "37-1.1.0"
```
The problem here is in the incorrect version being written down to the lock-file which couldn't be installed later.

Looks like an issue is with the version regex used to split filename and get a version from it:
```
In [1]: import re                                                                                                      

In [2]: VERSION_REGEX = re.compile(r"(?i)([a-z0-9_\-.]+?)-(?=\d)([a-z0-9_.!+-]+)")                                     

In [3]: VERSION_REGEX.match('mandrill-37-1.1.0')                                                                       
Out[3]: <re.Match object; span=(0, 17), match='mandrill-37-1.1.0'>

In [4]: VERSION_REGEX.match('mandrill-37-1.1.0').groups()                                                              
Out[4]: ('mandrill', '37-1.1.0')
```

**Comment by finswimmer** [comment]
Hello @kleschenko,

thanks a lot for reporting. It seems that this is solved in the meantime. At least with poetry 1.0.3 I get:

```
[[package]]
category = "main"
description = "A CLI client and Python API library for the Mandrill email as a service platform. Forked fork python 3.7 support"
name = "mandrill-37"
optional = false
python-versions = "*"
version = "1.1.0"
```

fin swimmer
