### ISSUE TITLE
Feature Request: OR package requirements

### ISSUE THREAD

**Issue by cognifloyd** [python-poetry/poetry#1532]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Feature Request
Some projects need to declare OR dependencies: At least one of package A OR package B must be installed.

This feature is not supported by requirements.txt or requires.txt (in egg-info or generated from contents of setup.py). So, projects that have an OR dependency (not an extra, but a dep where at least one MUST be installed) have to implement with hacks in setup.py. But then poetry cannot discover the dep because it does not execute setup.py.

For now, it would be awesome if poetry supported defining OR deps in pyproject.toml, and then maybe some kind of declarative interface can be added for projects that do not use poetry but would like to support installation through poetry. Again, the machinery to handle OR deps is necessary before we can figure out what kind of interface could be created. So, this feature request is only for pure poetry projects for now.

## Background

In #581, poetry cannot detect Ansible's dependencies because Ansible has an OR dependency. So, they codified their dependency `cryptography or pycrypto` (cryptography is the default if neither are installed) using custom functions that read requirements.txt and replace the cryptography dep on the fly if pycrypto is installed.

In that issue @sdispater suggested building wheels or including .egg-info in the sdist, however wheels do not support symlinks (which ansible requires ansible/ansible#12610) and `*.egg-info/requires.txt` does not support the OR dependency, so there is no way for ansible to declare its dependencies.

I also filed ansible/ansible#64299 to try and find any other way for ansible to declare its deps so that poetry can understand them, but I am stymied with how to handle the OR dep. Thus, this feature request.

**Comment by finswimmer** [comment]
Hey,

I can imagine that an OR declaration for dependencies might be useful (but it will be most likely a hell for the dependency resolver). But this is something that should be discussed and defined by the Python community via a PEP. You can try to start a discussion about it on https://discuss.python.org.

fin swimmer
