### ISSUE TITLE
Package resolution does not (seem to) honour python version flags.

### ISSUE THREAD

**Issue by EdgyEdgemond** [python-poetry/poetry#1539]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

I am using Poetry 0.12.17

This is potentially a formatting issue on my side, but...

I have a pyproject.toml with the following dependency based on python version.

```
[tool.poetry.dependencies]
python = "^3.6 || ^3.7"

tensorflow = [
    { version = "=1.15.0", python = ">=3.7" },
    { version = "=1.8.0", python = "<3.7" }
]
```

This resolves fine locally and creates the following in `poetry.lock`:

```

[[package]]
category = "main"
description = "TensorFlow helps the tensors flow"
marker = "python_version < \"3.7\""
name = "tensorflow"
optional = false
python-versions = "*"
version = "1.8.0"

[[package]]
category = "main"
description = "TensorFlow is an open source machine learning framework for everyone."
marker = "python_version >= \"3.7\""
name = "tensorflow"
optional = false
python-versions = "*"
version = "1.15.0"
```

When installed against py3.6/3.7 it correctly picks the tensorflow version to suit.

However when this library is installed as a dependency, poetry lock only detects that it requires  `1.15.0` despite the virtualenv using python3.6:

```
   1: fact: blstm-cnn-crf (0.1.1) depends on tensorflow (=1.15.0)
   1: selecting blstm-cnn-crf (0.1.1 0.1.1)
   1: derived: tensorflow (=1.15.0)
```

Installing projects pyproject.toml:

```
[tool.poetry.dependencies]
python = "^3.6.5"

blstm_cnn_crf = { git = "ssh://git@gitlab.com/****/blstm-cnn-crf.git", tag = "0.1.1" }
```
Is this a bug, or is this a formatting issue with my pyproject.toml/poetry.lock files?

**Comment by EdgyEdgemond** [comment]
When rolling back to previous version, which used setup.py and had the same python_version dependencies, poetry can detect the correct version of tensorflow from the child, just fine.

**Comment by EdgyEdgemond** [comment]
I have set up two very small projects to give an example:

https://github.com/EdgyEdgemond/poetry_parent
https://github.com/EdgyEdgemond/poetry_child

poetry_child poetry.lock has both 1.15.0 and 1.8.0 with python version flags.
poetry_parent poetry.lock only has 1.15.0 (but defines its python version as 3.6)

Additionally if poetry_parent marks 3.6 and 3.7 supported it does not get both versions locked either.

**Comment by EdgyEdgemond** [comment]
So I've worked out that part of my issue is that `^3.6` was not doing what I thought it did.

Changing to `~3.6` has fixed the issue with it trying to always enforce tensorflow 1.15.0.

I am still seeing the issue that if poetry_parent supports `~3.6 || ~3.7` it only detects the 3.7 branch in poetry.lock and does not resolve to py3.6 requiring tensorflow `=1.8.0`

changes to include ~ requirements pushed to demo repos.

**Comment by finswimmer** [comment]
Hello @EdgyEdgemond ,

could you please check if this issue still exists in the latest release?

Thanks a lot!

fin swimmer
