### ISSUE TITLE
`poetry init` interactive dependency tool doesn't catch error

### ISSUE THREAD

**Issue by ezdac** [python-poetry/poetry#1544]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**:  MacOS Mojave 10.14.5
- **Poetry version**:  Poetry 0.12.17
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**:  Not relevant for issue

## Issue

When using the interactive dependency tool when initialising a project,
the tool quits on an error, which to me is not as expected.
All previous user input is rendered invalid, since the initialising command fails and no `.toml` file is created. I don't, as a user, have a way to catch and reiterate the command causing the error.

```
[ValueError]
Could not find a matching version of package rdkit

Exception trace:
 /Users/Max/.poetry/lib/poetry/_vendor/py3.7/cleo/application.py in run() at line 94
   status_code = self.do_run(input_, output_)
 /Users/Max/.poetry/lib/poetry/console/application.py in do_run() at line 88
   return super(Application, self).do_run(i, o)
 /Users/Max/.poetry/lib/poetry/_vendor/py3.7/cleo/application.py in do_run() at line 197
   status_code = command.run(input_, output_)
 /Users/Max/.poetry/lib/poetry/console/commands/command.py in run() at line 77
   return super(BaseCommand, self).run(i, o)
 /Users/Max/.poetry/lib/poetry/_vendor/py3.7/cleo/commands/base_command.py in run() at line 146
   status_code = self.execute(input_, output_)
 /Users/Max/.poetry/lib/poetry/_vendor/py3.7/cleo/commands/command.py in execute() at line 107
   return self.handle()
 /Users/Max/.poetry/lib/poetry/console/commands/init.py in handle() at line 126
   self._determine_requirements(self.option("dependency"))
 /Users/Max/.poetry/lib/poetry/console/commands/init.py in _determine_requirements() at line 207
   _, constraint = self._find_best_version_for_package(package)
 /Users/Max/.poetry/lib/poetry/console/commands/init.py in _find_best_version_for_package() at line 266
   "Could not find a matching version of package {}".format(name)
```

**Comment by finswimmer** [comment]
Hello @ezdac ,

could you tell us which dependencies other then `rdkit` you have used during the process?

I'm quite sure, I have found the corresponding code, that need to catch the exception, but I need something to test it with something that should fail :)

fin swimmer

**Comment by finswimmer** [comment]
Because there were no more comments to this issue for a very long time, I assume it is solved. So I will close it.

Feel free to leave a comment if someone disagree.

fin swimmer
