### ISSUE TITLE
poetry not recording hashes of modules from pypicloud server

### ISSUE THREAD

**Issue by thehesiod** [python-poetry/poetry#1553]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OSX 10.15.1**: 
- **Poetry version: 1.0.0b3**: 

## Issue
We have a pypi cloud server (https://github.com/stevearc/pypicloud) which doesn't return hashes of the files it stores.  On it we have several .tar.gz sdist packages.  Via pipenv it generates hashes for modules that it picks up from that server, but via poetry they're all missing hashes, ex:
```
fbn-aaa = []
fbn-bbb = []
fbn-ccc = []
```

seems like it's missing the codepath to download the module and generate a hash for the file it's going to lock to.

**Comment by leorochael** [comment]
This looks to be the same issue as #1631.

As of version 1.1.0, pypicloud does [generate hashes for its links](https://github.com/stevearc/pypicloud/commit/b81d3fd32eb0c9f9fc75bac8d91ab76e1417d8bf).

If you have a mass of packages without hashes, there are scripts for recalculating those hashes which should make pypicloud serve the hashes correctly for already uploaded packages:

https://github.com/stevearc/pypicloud/tree/master/scripts

**Comment by abn** [comment]
Resolved-by: #2958
