### ISSUE TITLE
poetry dependencies fail to import relative packages

### ISSUE THREAD

**Issue by Granitosaurus** [python-poetry/poetry#1580]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: linux
- **Poetry version**: 0.12.17

## Issue

There's a very peculiar issue that I just can't replicate. It happens when poetry is using a dependency that does relative imports.

Lets assume we have package X that comes with an entry point and does this:

    # main.py
    from importlib import import_module
    import_module('tests.sometest')

Our poetry project in `pyproject.toml` has:
    
    [tool.poetry.dependencies]
    packagex = "^1.0"

we also have this project tree:

    ├── pyproject.toml
    └── tests
        └── sometest.py

Finally if we run `poetry run packagex` we'll see:

    ModuleNotFoundError: No module named 'tests.sometest'

However if we run `poetry run python` and do the same routine manually it will import just fine:

    
    from importlib import import_module
    import_module('tests.sometest')
    <module 'tests.sometest' from '/home/...'>

There is a lot of inconsistency with this behaviour. Sometimes clearing all poetry data and doing a fresh `poetry install` helps, most of the times explicitly specifying `PYTHONPATH` helps: 

    export PYTHONPATH=`pwd`

I can't reliably replicate this issue - there seems to be some weirdness going on with PYTHONPATH as if dependency entry points don't consider current working directory as part of PYTHONPATH

**Comment by finswimmer** [comment]
Hello @Granitosaurus ,

could you please check if the issue exists in the latest preview version of poetry?

Thanks!

**Comment by Granitosaurus** [comment]
> could you please check if the issue exists in the latest preview version of poetry?

I've tried the latest master branch with no success unfortunately.

**Comment by atoav** [comment]
I have a similar issue:
My module directory looks like
```
testmodule
├── __init__.py
├── testmodule.py
└── config.py
```
In `testmodule.py` I import `config.py` like this:
```
from config import Config
```
The script defined in my `pyproject.toml` looks like this:
```
[tool.poetry.scripts]
testmodule = "testmodule.testmodule:main"
```
When run `poetry run testmodule` I get the following Error:
```
  File "/mnt/e/Coding/work/testmodule/testmodule/testmodule.py", line 13, in <module>
    from config import Config
ModuleNotFoundError: No module named 'config'
```

Weirdly enough this works however:
```
poetry run python3 testmodule/testmodule.py
```
(this uses a `main()` function call in a `if __name__ == "__main__":` block)

**Comment by atoav** [comment]
@finswimmer told me how to fix this on discord, posting it here for future reference:
> Use relative import from .config import Config or better absolute import from testmodule.config import Config

**Comment by finswimmer** [comment]
Closing this because it's not a poetry issue. It is about how `import` works in the python land.
