### ISSUE TITLE
Please submit poetry as proposal for pip 2020 RfP

### ISSUE THREAD

**Issue by dekoza** [python-poetry/poetry#1581]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Issue

Please submit this project as proposal for [pip 2020 RfP](https://github.com/python/request-for/blob/master/2020-pip/RFP.md#pip-2020-request-for-proposals)

**Comment by techdragon** [comment]
Since the pip 2020 RfP has closed, this could also probably be closed... @sdispater @dekoza @stephsamson
