### ISSUE TITLE
Poetry wants to install mac version of pyhocon on linux system

### ISSUE THREAD

**Issue by P1zz4br0etch3n** [python-poetry/poetry#1583]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Fedora 31
- **Poetry version**: 1.0.0b4
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/P1zz4br0etch3n/aee95c7bcc1d696db961d8db835a2a68

## Issue
I set-up a new project and tried to install pyhocon. The latest available version seems to be `0.3.53.macosx-10.14-x86_64` which poetry wants to install. But obviously that's a mac version and I'm on linux. I tried `poetry add pyhocon --platform=linux` but there's no difference. If I set the version to `0.3.51` everything works fine.

**Comment by finswimmer** [comment]
This was due to a wrong package file format of `pyhcon` in `0.3.53`.
