### ISSUE TITLE
Instructions for changing shell

### ISSUE THREAD

**Issue by khalibloo** [python-poetry/poetry#1599]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue
The documentation is missing instructions on changing the shell type for poetry. On windows, it defaults to cmd, at least for me. Took a while to figure out why certain commands suddenly broke. It should be mentioned in the docs along with instructions on how to change the shell type.

**Comment by TBBle** [comment]
Windows always running `cmd` is a particular issue, see #2030. It also doesn't honour $SHELL on Windows, and falls back to cmd.exe if it can't find the current shell.

**Comment by abn** [comment]
The shell command doc was improved in #9060.

See https://python-poetry.org/docs/main/cli/#shell
