### ISSUE TITLE
Poetry not running setup.py as pip does

### ISSUE THREAD

**Issue by harrybiddle** [python-poetry/poetry#1615]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Mac 10.15 
- **Poetry version**: 0.12.17
- **Contents of your pyproject.toml file**:
   ```
   [tool.poetry]
   name = "test"
   version = "0.1.0"
   description = ""
   authors = ["Nobody <nobody@noreply.com>"]

   [tool.poetry.dependencies]
   python = "^3.6"
   jupyter = "^1.0"
   jupyterlab = "^1.2"
   jupyterlab-git = {git = "https://github.com/jupyterlab/jupyterlab-git.git", rev = "master"}

   [tool.poetry.dev-dependencies]

   [build-system]
   requires = ["poetry>=0.12"]
   build-backend = "poetry.masonry.api"
  ```

## Expected Behaviour

`poetry add` should behave the same way as `pip install`

## Issue

The package "jupyterlab-git" runs some extra steps during install for a better user experience. These steps run correctly when installing using `pip install jupyterlab-git` within a Poetry venv. However, they are not run if the dependency is included in the `pyproject.toml` file as above and `poetry install` is run, nor if they are added to a project using `poetry add`.

The steps that jupyterlab-git runs are:

 1. Compile the frontend jupyterlab extension:
   https://github.com/jupyterlab/jupyterlab-git/blob/50952c9c8ba8ba6c4dab3eca217e8cba08655d56/setup.py#L48
 2. Put the resulting package in labextension folder
 3. Copy the package file in the default extension folder of Jupyterlab:
   https://github.com/jupyterlab/jupyterlab-git/blob/50952c9c8ba8ba6c4dab3eca217e8cba08655d56/setup.py#L37

I would expect Poetry to behave in the same way as pip. Is Poetry perhaps not running setup.py correctly? Or is this intended behaviour?

This ticket came out of a discussion on https://github.com/jupyterlab/jupyterlab-git/issues/452, where I also [provided a repro](https://github.com/jupyterlab/jupyterlab-git/issues/452#issuecomment-556999585). Note that this setup.py behaviour is (at the time of writing) pre-release.

**Comment by sloria** [comment]
I ran into this issue as well. It looks like git-installed packages don't get installed via `setup.py`. This breaks installation of nested packages via `package_dir`, e.g.

```
setup(
    # ...
    package_dir={"mynestedpackage": "packages/mynestedpackage"},
    packages=["mynestedpackage"],
)
```

**Comment by finswimmer** [comment]
Hello,

running automatically commands after a package is installed is a security issue and this function by `setuptools` is discussed controversially at other places. This is why we don't want to support it.

fin swimmer
