### ISSUE TITLE
GitHub package registry support

### ISSUE THREAD

**Issue by RDIL** [python-poetry/poetry#1624]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Feature Request

I think adding support to the deploy command for uploading packages directly to the new GitHub package repository may be a good idea.  

I haven't checked the docs yet, but I am guessing there is already custom index support.  I just feel that since the GitHub package repository is a bit different, it would make sense to add direct support for it.

**Comment by gifflen** [comment]
As far as I can tell there isn't any support in github packages for python yet.

**Comment by CfirTsabari** [comment]
linking the tracking issue in github:
https://github.com/github/roadmap/issues/94
