### ISSUE TITLE
poetry complains about missing argument when using `--help`

### ISSUE THREAD

**Issue by finswimmer** [python-poetry/poetry#1625]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

## Issue

I don't know whether this is a poetry issue or cleo and if this problem arises in earlier versions.

When I type `poetry add --help` I receive the error message

```
Not enough arguments (missing: "name").
```

Similar for `poetry remove --help`

```
Not enough arguments (missing: "packages").
```

If I append any name I get the help page.

The expected behavior would be, that whenever I use `--help`, the help page should be displayed and mandatory arguments for sub command shouldn't be checked.

Saw this with version 1.0.0b6 and 1.0.0b7

**Comment by kawing-chiu** [comment]
Same issue here at 1.0.0b7 :)

**Comment by mrezzamoradi** [comment]
```poetry <command> --help``` does not work for the following commands:

- add
- remove
- search
- run
- new

poetry version: 1.0.0
OS: Ubuntu 18.04.2 LTS
