### ISSUE TITLE
is there any Poetry plugin or hook to alternate the installation process?

### ISSUE THREAD

**Issue by lxsameer** [python-poetry/poetry#1629]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

Hey folks I read the two lines of docs about plugins and couldn't figure out how they work in Poetry, i'm using version 0.12.11 and was wondering is there any way to alternate the installation process ? I need to collect some metric from the process.

**Comment by finswimmer** [comment]
A plugin system will be available in Poetry 1.2: https://python-poetry.org/docs/master/plugins/
