### ISSUE TITLE
'poetry init' should use existing pyproject.toml file

### ISSUE THREAD

**Issue by dekoza** [python-poetry/poetry#1639]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Feature Request

I think that `poetry init` should detect if existing pyproject.toml already contains poetry entries and if not, it should add itself to it instead of exiting with error. I have basic (almost brute-force) method prepared but I want to make it in more elegant way. Anyway, expect PR soon :smile:

**Comment by finswimmer** [comment]
Hello @dekoza ,

sounds like a good idea to me :+1: 

I would really like to see your PR :)

fin swimmer

**Comment by ttimbers** [comment]
I would like to see this feature too! It would be very helpful when paired with Cookiecutter templates.

**Comment by dekoza** [comment]
I'm sorry, my commercial project really eats up a lot of my time lately. If anyone wants to take over, don't hesitate :slightly_smiling_face:
