### ISSUE TITLE
poetry export help doesn't provide the format options

### ISSUE THREAD

**Issue by absassi** [python-poetry/poetry#1640]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: any
- **Poetry version**: 1.0.0b8
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue

One needs to browse Poetry docs (which are not even online for 1.0 beta yet, or I couldn't find a link) or the source code to find out how to use the **poetry export** command, because the help text doesn't provide the list of available formats.

```
$ poetry export

[ValueError]
Invalid export format: None
$ poetry export --help
USAGE
  poetry export [-f <...>] [-o <...>] [--without-hashes] [--dev] [-E <...>] [--with-credentials]

OPTIONS
  -f (--format)          Format to export to.
  -o (--output)          The name of the output file.
  --without-hashes       Exclude hashes from the exported file.
  --dev                  Include development dependencies.
  -E (--extras)          Extra sets of dependencies to include. (multiple values allowed)
  --with-credentials     Include credentials for extra indices.

GLOBAL OPTIONS
  -h (--help)            Display this help message
  -q (--quiet)           Do not output any message
  -v (--verbose)         Increase the verbosity of messages: "-v" for normal output, "-vv" for more verbose output and "-vvv" for debug
  -V (--version)         Display this application version
  --ansi                 Force ANSI output
  --no-ansi              Disable ANSI output
  -n (--no-interaction)  Do not ask any interactive question

$ poetry export -f anything

[ValueError]
Invalid export format: anything
```

In the [current docs](https://github.com/sdispater/poetry/blob/master/docs/docs/cli.md), the option `-f` is documented as:

> * `--format (-f)`: The format to export to. Currently, only `requirements.txt` is supported.

This should be in the command help too.

**Comment by finswimmer** [comment]
Hello @absassi,

thanks a lot for reporting. Must get lost somewhere. Will be fixed with https://github.com/sdispater/poetry/pull/1653.

fin swimmer
