### ISSUE TITLE
Support ctrl+d to quit the shell

### ISSUE THREAD

**Issue by rfkortekaas** [python-poetry/poetry#1643]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Feature Request

Support ctrl+d to quit the shell.

**Comment by pawamoy** [comment]
It's already the case, at least for me, on Linux Bash/Zsh and on Windows Git-Bash.

**Comment by finswimmer** [comment]
Hello @rfkortekaas ,

could you please add the information about the poetry version and what OS you are using to your issues. That would really help us, to catch the problem as fast as possible.

Thanks a lot for your contribution!

fin swimmer

**Comment by rfkortekaas** [comment]
I'm using windows 10. Command lines i tries: cmder, windows cmd and powershell

**Comment by TBBle** [comment]
Ctrl+D is a facet of the shell process, not Poetry. Bash supports Ctrl+D, but cmd and ps do not. Use `exit` there instead.

**Comment by pawamoy** [comment]
I think this issue can be closed.

**Comment by dimbleby** [comment]
indeed this should be closed
