### ISSUE TITLE
test_none_activated fails

### ISSUE THREAD

**Issue by mcepl** [python-poetry/poetry#1646]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: openSUSE/Tumbleweed
- **Poetry version**: 1.0.0b8
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue
Test test_none_activated fails with this traceback:
```
[   82s] _____________________________ test_none_activated ______________________________
[   82s] 
[   82s] app = <tests.console.conftest.Application object at 0x7f5eb21f5f28>
[   82s] tmp_dir = '/tmp/poetry_8y6qqpk7'
[   82s] 
[   82s]     def test_none_activated(app, tmp_dir):
[   82s]         app.poetry.config.merge({"virtualenvs": {"path": str(tmp_dir)}})
[   82s]     
[   82s]         venv_name = EnvManager.generate_env_name(
[   82s]             "simple-project", str(app.poetry.file.parent)
[   82s]         )
[   82s]         (Path(tmp_dir) / "{}-py3.7".format(venv_name)).mkdir()
[   82s]         (Path(tmp_dir) / "{}-py3.6".format(venv_name)).mkdir()
[   82s]     
[   82s]         command = app.find("env list")
[   82s]         tester = CommandTester(command)
[   82s]         tester.execute()
[   82s]     
[   82s]         expected = """\
[   82s]     {}-py3.6
[   82s]     {}-py3.7
[   82s]     """.format(
[   82s]             venv_name, venv_name
[   82s]         )
[   82s]     
[   82s] >       assert expected == tester.io.fetch_output()
[   82s] E       AssertionError: assert 'simple-proje...1YLO2-py3.7\n' == 'simple-proje...(Activated)\n'
[   82s] E           simple-project-i8E1YLO2-py3.6
[   82s] E         - simple-project-i8E1YLO2-py3.7
[   82s] E         + simple-project-i8E1YLO2-py3.7 (Activated)
[   82s] E         ?                              ++++++++++++
[   82s] 
[   82s] tests/console/commands/env/test_list.py:30: AssertionError
```
[Complete build log](https://github.com/sdispater/poetry/files/3902686/_log.txt)

**Comment by finswimmer** [comment]
Hello @mcepl ,

can you please add some more context to your issue? What are you trying to do? What is your expected behavior?

Thanks a lot.

fin swimmer

**Comment by mcepl** [comment]
https://github.com/sdispater/poetry/issues/1645#issuecomment-559891651

**Comment by bnavigator** [comment]
This one and many more tests are still failing without venv (https://github.com/python-poetry/poetry/issues/1645#issuecomment-713109037)

**Comment by bnavigator** [comment]
Workaround: https://github.com/python-poetry/poetry/issues/1645#issuecomment-713179414

**Comment by mcepl** [comment]
> Workaround: [#1645 (comment)](https://github.com/python-poetry/poetry/issues/1645#issuecomment-713179414)

@bnavigator Could I hope for some submit request with this, please?

**Comment by bnavigator** [comment]
It's just a change in the test suite, no functional change. But here you go:
https://build.opensuse.org/request/show/843165

Note that it will be stuck in Staging:H (https://build.opensuse.org/request/show/841923)
