### ISSUE TITLE
support $XDG_CONFIG_HOME on linux

### ISSUE THREAD

**Issue by hyperupcall** [python-poetry/poetry#1659]
- [x] i have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] i have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## feature request
i noticed that `$XDG_CONFIG_HOME` is supported on mac from [this issue](https://github.com/sdispater/poetry/issues/1239), but are there plans for it (or other variables from the xdg base directory specification) to be supported on linux? i ask because poetry still installs to `$HOME/.poetry/bin` even though i explicitly set `$XDG_DATA_HOME`. it would be great if configuration files would also be put in $XDG_CONFIG_HOME/poetry

i think it would be great for the behaviour to be consistent as possible between operating systems, especially considering that macos and gnu/linux are both *nix operating systems.

**Comment by MestreLion** [comment]
`$XDG_CONFIG_HOME` is meant for configuration files, not software data. Maybe you mean `$XDG_DATA_HOME`? If so, then yes, I strongly support this request. Poetry should install itself to `$XDG_DATA_HOME/poetry` (which defaults to `~/.local/share/poetry`), and copy (or symlink) its CLI executable to `~/.local/bin`.

**Comment by eankeen** [comment]
oops! yeah that's exactly what i meant. lemmie fix that

**Comment by finswimmer** [comment]
The new `install-poetry.py` installer script should do this.
