### ISSUE TITLE
Poetry Build not honouring .gitignore

### ISSUE THREAD

**Issue by SimonBiggs** [python-poetry/poetry#1660]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Manjaro Linux Latest
- **Poetry version**: 1.0.0b8
- **`pyproject.toml`**: https://github.com/pymedphys/pymedphys/blob/9b24bad2520684793b35193191cdb470809b8b05/pyproject.toml

## Issue

It appears as though the following line within a `.gitignore` file is not being honoured by poetry build:

https://github.com/pymedphys/pymedphys/blob/9b24bad2520684793b35193191cdb470809b8b05/pymedphys/_app/.gitignore#L10

See the corresponding PyPI release which contains the build directory which should not have been included:

https://pypi.org/project/pymedphys/0.13.0.dev0/#files

![image](https://user-images.githubusercontent.com/6559099/69955412-af8cdc80-1551-11ea-8eb0-3c1760f44ff7.png)

Keen for any pointers on how to get this directory not included within the release artefact.

Cheers,
Simon

**Comment by finswimmer** [comment]
Hello @SimonBiggs,

could you please check if all files of the folders are listed in the output of ```git ls-files --others -i --exclude-standard```. This is what poetry does, to get the files excluded by `.gitgnore`.

If not all files are listed here, you most likely added them to get tracked by git, before creating the entry in ` .gitignore`. If this is the case, remove these files from tracking by `git rm --cached <file-name>` or `git rm -r --cached <folder-name>`

fin swimmer

**Comment by SimonBiggs** [comment]
Thanks for the tip. I just rebuilt it at work on a Windows 10 PC and I didn't encounter the same issue (without any changes undergone to the repo).

I'll investigate regarding your tip tonight on my Linux PC.

Cheers,
Simon

**Comment by finswimmer** [comment]
Hey @SimonBiggs ,

any news on this?

fin swimmer
