### ISSUE TITLE
No documentation on the --allow-prereleases flag

### ISSUE THREAD

**Issue by skylarjhdownes** [python-poetry/poetry#1665]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue
  Hello!  I'm trying to find out how to do the equivalent of `pip install --pre` in poetry.  I saw that poetry has an `--allow-prereleases` flag, but running `poetry add --allow-prereleases lib_to_install` only installed the latest released version of the library I need, not the prerelease.  

I was unable to find any documentation on how to use the `--allow-prereleases` flag other than the `--help` text.

**Comment by Nirvi1** [comment]
Hey,

I have added a fix for this by introducing a document for this! Have a look - https://github.com/python-poetry/poetry/pull/1950

Thanks!

**Comment by finswimmer** [comment]
It's now mentioned in the [docs](https://python-poetry.org/docs/master/cli/#options-3).
