### ISSUE TITLE
Add Python shebang to get-poetry.py script

### ISSUE THREAD

**Issue by n8sty** [python-poetry/poetry#1668]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Feature Request
I use Poetry as part of a few different CI flows. In some of these I put (and cache) `get-poetry.py` into `/usr/local/bin/` ie:

```
sudo curl -sSL --output /usr/local/bin/get-poetry https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py
```

Since `get-poetry` doesn't have a shebang, it's not executable. This isn't a big deal, it's not too difficult to call `python /usr/local/bin/get-poetry` or add an appropriate shebang at the top of the file, but why not just add `#!/usr/bin/env python` as a shebang to the file to support this use case?

**Comment by finswimmer** [comment]
Hello @n8sty,


the `get-poetry` script is now deprecated in favor of the new `install-poetry` script. This is why I close your ticket.

fin swimmer
