### ISSUE TITLE
Poetry breaks when package name starts with/ends in space

### ISSUE THREAD

**Issue by Emerentius** [python-poetry/poetry#1670]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows 10 1903, Ubuntu 18.04
- **Poetry version**: 0.12.17, 1.0.0b8
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/Emerentius/52d8b4708c93d252dce068ca46c37e99

## Issue

When the package name starts or ends with a space (typo), then poetry subcommands fail with various confusing errors. 

```
$ poetry install
Updating dependencies
Resolving dependencies... (0.0s)
                           
[KeyError]  
'foo-test'

$ poetry add django
Using version ^3.0 for django

Updating dependencies
Resolving dependencies... (0.3s)
                                    
[PackageNotFound]    
Package [poetry-test] not found.
```

After switching the package name between various valid and invalid names, I even got a `[KeyError] '<object object at 0x7fc8ae6fc810>'` after `poetry add django`.

The issue is mainly one of bad error messages. If a package name is invalid, poetry should ideally tell you so.

**Comment by dimbleby** [comment]
Seems to be fixed on recent code

**Comment by abn** [comment]
Thanks @dimbleby. Closing for now. 

Please let us know if this is still an issue with the code on master.
