### ISSUE TITLE
A simple command to execute python in virtualenv

### ISSUE THREAD

**Issue by silverwind** [python-poetry/poetry#1671]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Feature Request
To run a python script inside the virtualenv created by poetry, one has to to through a few hoops:

- `cd <project-dir>` (`poetry run` currently seems to require this to work)
- `poetry run python script.py [args]`

This could be simplified via a new command installed alongside the `poetry` command, let's call it `popy` (short for poetry python) which would ensures the provided script is ran inside the virtualenv. It would enable a shebang like `#!/usr/bin/env popy` which would then allow the script to be invoked via `./script.py` and automatically run in the virtualenv.

**Comment by rpdelaney** [comment]
You may be looking for [pipx](https://pypi.org/project/pipx/).

**Comment by e3krisztian** [comment]
> pipx is not a tool for development

**Comment by e3krisztian** [comment]
I liked the proposal and the proposed tool name, it looked easy enough to implement, so I made a failed attempt.

It quickly turned out, that `cleo`/`clikit`, the used command line library is unknown to me, have some learning curve, so it is not that trivial as I thought - and when wanted to try out an experiment I run into #1510. I have given up at this point - did not want to upgrade to preview.

I still hope this proposal will be implemented, though.

**Comment by silverwind** [comment]
Not sure I like the name personally. I think I'd actually lean more towards a `poetry-python` or `poetryx` but I guess that it should be up to the maintainers anways, if we're moving forward with this. I guess a implementation could already be published to PyPi now and later included in poetry.

**Comment by rpdelaney** [comment]
> pipx is not a tool for development

Maybe I misunderstand the ask. `poetry run` gets the job done for dev purposes, from my POV. 

> would ensures the provided script is ran inside the virtualenv

Which virtualenv? I have many, and often times a different version of a thing is in each of them.

**Comment by e3krisztian** [comment]
PyPI is not for applications, but for libraries.
For me, the main feature of the proposal is convenience: less to type to run python scripts, so a shorter name is better.
Actually a simple `alias popy='poetry run python'` would do it for me - most of the time I want to run scripts from within the current directory.

@rpdelaney was right with one half of the functionality: the `#!/usr/bin/env popy` part is indeed like `pipx`.  I have overlooked it, it requires finding the Poetry environment of the script and using the python in the poetry environment, something like this:

```python
#!/usr/bin/env python
import os, sys, subprocess

orig_dir = os.getcwd()
script_path = os.path.abspath(sys.argv[1])
if os.path.isdir(script_path):
    # we can run directories with python if they have __main__.py
    script_dir = script_path
else:
    script_dir = os.path.dirname(script_path)

os.chdir(script_dir)
python = subprocess.getoutput("poetry run which python")
os.chdir(orig_dir)

os.execv(python, sys.argv)
```

It is slow, as it starts further processes, that can be optimized/sped up by being part of and using internal knowledge of Poetry.

**Comment by rpdelaney** [comment]
> PyPI is not for applications, but for libraries.

My impression is that it is for modules, which can (and often do) include elements of both. That's why `pipx` is useful, I think.

> something like this

I'm confused. You find python by doing `poetry run which python` but this will give you an executable only if you are already in a directory with a venv. In that scenario `poetry run` would give you the same behavior, as far as I can tell?

**Comment by e3krisztian** [comment]
> In that scenario `poetry run` would give you the same behavior, as far as I can tell?

There is one significant difference: the current working directory will be different. Please note, that there are `os.chdir()`-s around the call to get the `python` executable.

Once a python program is started with the proper python executable, the python executable will resolve the library references to file paths relative to itself (that's how virtualenvs work).

So we need the path of the python executable of that virtualenv.  This *cd script_dir; poetry please tell me the python executable path; cd back* gives that path, but it could be implemented better (cheaper=faster) inside of Poetry.
