### ISSUE TITLE
`poetry shell` with fish does not echo in python REPL

### ISSUE THREAD

**Issue by jmaroeder** [python-poetry/poetry#1672]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: MacOS Catalina 10.15.1
- **Poetry version**: 1.0.0b8
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: N/A

## Issue
As described by [L0stLink](https://github.com/sdispater/poetry/issues/1593#issuecomment-555132468) in a now-closed issue, `fish` still appears to have some issues when using `poetry shell`. Specifically, in the Python REPL "typed text not visible, but pressing enter shows that the input was registered and whatever was typed, executes".

It appears that the fix in #1621 only addressed the `bash` case.

**Comment by itsthejoker** [comment]
Wait, it's a fish issue? It didn't occur to me to try this in bash. I reported this earlier here: https://github.com/sdispater/poetry/issues/1664

**Comment by rvanlaar** [comment]
Yeah, it happens with fish and not with bash.

I'm on poetry 1.0.0 and fish 3.0.2.

And it's not only the python shell. The echo issue seems to be with every subshell that is spawned. 

https://asciinema.org/a/oxuANMb20AI6eOCAQ5aCvwX2y

**Comment by L0stLink** [comment]
Experiencing the same issue again with poetry version 1.0.0 on python 3.8.1, it was all working fine before the update from `3.8.0->3.8.1`, the issue only presents itself if I run `poetry shell` and only in fish shell (fish version is 3.0.2), bash (version 5.0.11(1)-release) is unaffected, if i source the `activate.fish` file directly then it works normally as one expects this is on ArchLinux.
