### ISSUE TITLE
Thank you for all your work!

### ISSUE THREAD

**Issue by TheButlah** [python-poetry/poetry#1686]
- [X] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Issue

After using poetry for about a month now, I wanted to thank the developers for all the hard work that they have put into this system. In particular, I started out using pipenv and quickly realized that in addition to technical reasons that made me prefer poetry over that tool, the poetry developers have done a really good job of listening to the community and incorporating their feedback. I know it must be exhausting to have so many github issues to handle and people to deal with, so I'm really grateful for your continued engagement with the community.

Thanks so much for making this tool, and by extension the python ecosystem, better and better!

**Comment by finswimmer** [comment]
We are always glad to hear a "Thank you" :smiley:
