### ISSUE TITLE
Readme says `poetry self:update` instead of `poetry self update`

### ISSUE THREAD

**Issue by ric2b** [python-poetry/poetry#1688]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue
The updating poetry section of the README says that the command is `poetry self:update` but it's actually `poetry self update` (no `:`): https://github.com/sdispater/poetry#updating-poetry

**Comment by finswimmer** [comment]
Hello @ric2b ,

thanks a lot for the reminder. This is definitely something we had to change with the 1.0 release. I'm not sure if it's a good idea to do it know. I guess most people will have installed 0.12 before they are looking into the git. And there the syntax is correct.

Maybe we should include a note about the different syntax in the different versions :thinking: .

fin swimmer

**Comment by 515hikaru** [comment]
At the moment, I think there should be a note for preview users. For example:

Note for preview users: The update syntax is different from the latest stable version. See `poetry self --help` for details.

**Comment by slhck** [comment]
I'm relying heavily on the preview version, and this has confused me before.

In my opinion, the Git master should always be coherent, so the README should always document the behavior for whatever you get when checking out the latest revision. This is the case for most projects I've come across.

If users want documentation for older or stable releases, they should look at the respective documentation website (https://poetry.eustace.io/docs/).

Probably it would even make sense to remove the duplication between the README and documentation. I think this has been mentioned in other places before. Then the README can purely focus on installation. An example for this is [pyenv](https://github.com/pyenv/pyenv#command-reference).

**Comment by pawamoy** [comment]
Maybe documentation could be versioned? With something like https://github.com/zayd62/mkdocs-versioning?

**Comment by slhck** [comment]
@pawamoy That makes a lot of sense and is what is commonly done in other projects.
