### ISSUE TITLE
Github SSH String and SdistBuilder Incompatible

### ISSUE THREAD

**Issue by wakemaster39** [python-poetry/poetry#1697]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **MaxOS 10.14**: 
- **1.0.0b8**: 

## Issue
When working with git dependency such as `git@github.com:sdispater/poetry.git`. Working with poetry everything is totally fine things install and function properly and it makes it seem like you have configured poetry correctly.

This falls apart when you try and install that package in another repo. Basically the `SdistBuilder` outputs a string like `git+git@github.com:sdispater/poetry.git@master`. What it actually needs to be is `git+ssh://git@github.com/sdispater/poetry.git`.

This can easily be fixed in the package by changing the git url to be `ssh://git@github.com/sdispater/poetry.git`. The issue is there is no way to know that this is a problem until you are trying to consume your work and the terrible output messages from pip when you try and install this will leave you in debugging hell especially since poetry deletes the `setup.py` file it generates so you can't view it to rerun it.

There are two different ways to handle this problem as I see it, the first would be to make it so that poetry does not accept git urls that are not compliant with [PEP-508](https://www.python.org/dev/peps/pep-0508/). 

The second option is to upgrade `VCSDependency` so that it detects urls in this format and converts them to a compliant format when `dependency.to_pep_508()` is called. 

I personally prefer the second because it is easier to copy and paste out of GitHub and would hopefully make the friction less when new users are adopting poetry.

I am happy to implement either, I just need to know the preferred direction.

**Comment by finswimmer** [comment]
Hey @wakemaster39 ,

I'm not sure if I understand your problem. Could you please provide a step-by-step manual to see where your problem arises?

Thanks a lot!

fin swimmer

**Comment by wakemaster39** [comment]
1. Create a project with a git dependency, add it using the ssh URL copied from Github such as `git@github.com:pallets/flask.git`
2. Build your new package `poetry build`
3. Open the outputted tar.gz and edit the setup.py file
4. view the `install_requires` section and see the illegal line similar to `flask @ git+git@github.com:pallets/flask.git@master`

The legal format would be `flask @ git+ssh://git@github.com/pallets/flask.git@master`

5. Try and install this package in a different project and see the error message pip gives you


The problem becomes if you don't build the package and simply add this first project as a git dependency it is not possible to inspect the setup.py file and determine what the root cause of the problem is.

**Comment by matemax** [comment]
+1. I have same problem
