### ISSUE TITLE
Version constraint for Windows

### ISSUE THREAD

**Issue by tigerhawkvok** [python-poetry/poetry#1699]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Feature Request

Windows is sometimes idiosyncratic, especially with binaries. So, it'd make sense if the version constraint language could target "Windows" and "not Windows", for example:

```toml
# https://poetry.eustace.io/docs/versions/
[tool.poetry.dependencies]
foo = [
    {version = "<=1.9", python = "^2.7"},
    {version = "~2.0.0", python = "^3.4", windows= True},
    {version = "^2.1", python = "^3.4", windows= False}
]
```

To bring it home, here's an actual example: `python-snappy` from pip fails to build on Windows without [convoluted steps to get it working](https://stackoverflow.com/questions/42979544/how-to-install-snappy-c-libraries-on-windows-10-for-use-with-python-snappy-in-an). Precompiled binaries, such as from https://www.lfd.uci.edu/~gohlke/pythonlibs/#python-snappy , will work much better. So, to share with my Windows colleagues, I'd want to have the dependency

`python-snappy = {path = "python_snappy-0.5.4-cp36-cp36m-win_amd64.whl"}`

with the version I put in VCS for redist. But for everyone else, I'd want it to be

`python-snappy = "~0.5.4"`

Right now, I have no way to include these two same-but-different dependencies. (Something like "IfError" or "OnError" logic would also work on a per-dependency basis).

Using the syntax above, then, I'd have instead

```toml
[tool.poetry.dependencies]
python-snappy = [
    {path = "python_snappy-0.5.4-cp36-cp36m-win_amd64.whl", windows= True},
    {version = "~0.5.4", windows= False}
]
```

**Comment by finswimmer** [comment]
This can be achieved by using [environment markers](https://python-poetry.org/docs/dependency-specification/#using-environment-markers), e.g.:

```
[tool.poetry.dependencies]
foo = [
    {version = "~2.0.0", markers = "python_version >= '3.4' and sys_platform == 'win32'"},
    {version = "^2.1", markers = "python_version >= '3.4' and sys_platform != 'win32'"}
]
```
