### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by rvanlaar** [python-poetry/poetry#1704]
- [X] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Issue

Hi, I'm new to using poetry, 
Poetry's tag line is: Python packaging and dependency management made easy

That sounds great, however the tag line seems to be more of a wish
than a promise I can count on.

For example I'm running into these hurdles:
  - virtual env not activating with `poetry shell`
  - no support for activating the shell within fish
  - lacking vscode support
  - it not working in pre-receive hooks
  - lacking documentation

To that end I would like the following:

## A channel to request help or information.
  Either slack, discord, irc or a mailing list to get quick feedback on questions.

## More and better documentation:
  - A faq that has way more questions
  - Information from issues moving towards the documentation before the issue get's closed.
  - searchable documentation
  - 'Options' in the docs are not commands, and should have smaller headers.

So, how can I help with this?

**Comment by rvanlaar** [comment]
I'll keep a list for reference:

- The github readme specifies the 'clean' command, which isn't defined.
- I had multiple versions of poetry installed, which didn't work together. 
  `whereis poetry` was helpfull in solving this.

**Comment by 515hikaru** [comment]
> A channel to request help or information.
> Either slack, discord, irc or a mailing list to get quick feedback on questions.

You can join Discord community by this link: https://discordapp.com/invite/awxPgve

**Comment by cjolowicz** [comment]
> no support for activating the shell within fish

I use this function to activate Poetry virtualenv inside fish:

```fish
function poetry-env-activate --description "Activate the virtualenv of a Poetry-managed Python project"
    source (dirname (poetry run which python))/activate.fish
end
```

https://github.com/cjolowicz/dotfiles/blob/master/fish/.config/fish/functions/poetry-env-activate.fish

**Comment by finswimmer** [comment]
Hello @rvanlaar ,

> virtual env not activating with poetry shell

if this is the case, and you've tested it with the latest preview release, please open a new issue with more information about your settings.

> no support for activating the shell within fish
Have you tested it with the latest preview release? I've found some issues in the tracker that reported problems with fish, but they seems to be fixed.

> lacking vscode support
You mean the code editor vscode? That's definitely nothing poetry will care about. If you like to have poetry support within your favorite IDE, please contact the maintainers of the IDE.

> it not working in pre-receive hooks
Can you elaborate what this should be in the scope of poetry? 

> lacking documentation
> [...]
> So, how can I help with this?

We always appreciate any kind of help. If you like to improve the documentation fork the repository edit the README or any other file within the doc folder and create a Pull Request with an explanation what you've done. 

fin swimmer

**Comment by rvanlaar** [comment]
The preview release doesn't have the shell not activating problem.

**Comment by rvanlaar** [comment]
I'm closing this issue. The shell not activating is solved.
