### ISSUE TITLE
Configuration files in /etc/pypoetry instead of $HOME/.config/pypoetry

### ISSUE THREAD

**Issue by neimad1985** [python-poetry/poetry#1709]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

Hi,

Firstly thanks for the great work done on this lib, especially the dependencies solver.
Secondly, I've searched for an answer to my question in the opened/closed issues and the documentation but couldn't find one, sorry if there is one and I missed it. (I even tried to read the code but did not succeed)

The question now.
I'm wondering if it is possible to centralize the poetry configuration inside the /etc/pypoetry directory instead of a per user-basis in $HOME/.config/pypoetry.
I have machines used by several users and I would like to hide the configuration from them so they just have to focus on the packages part and not configuration one.
It would by nice to be able to centralize this.

Thanks in advance.

Regards

**Comment by jpyams** [comment]
You can make an /etc/config/pypoetry directory and set `XDG_CONFIG_HOME=/etc/config/pypoetry` for your users to share a configuration.
