### ISSUE TITLE
poetry re-installs up-to-date packages when virtualenvs.create is false

### ISSUE THREAD

**Issue by jstriebel** [python-poetry/poetry#1711]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version. (`1.0.0b9`)
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Debian buster
- **Poetry version**: `1.0.0b9`

## Issue
Thanks for the great work! With current releases we experience that already up-to-date packages (with the correct versions) are reinstalled by poetry, as it tries to update them. This seems to happen because we don't use poetry's virtualenv feature (using `poetry config virtualenvs.create false`).

Here's a part of the `poetry install` output, when running it the second time:
```
  - Updating humanfriendly (4.18 /usr/local/lib/python3.6/dist-packages -> 4.18)
  - Updating imageio (2.6.1 /usr/local/lib/python3.6/dist-packages -> 2.6.1)
  - Updating importlab (0.5.1 /usr/local/lib/python3.6/dist-packages -> 0.5.1)
```

It seems that dist-packages can never match the version, so poetry tries to upgrade them, even when the version actually matches.

Output of `poetry debug info`:
```
Poetry
Version: 1.0.0b9
Python:  3.6.8

Virtualenv
Python:         3.6.8
Implementation: CPython
Path:           NA

System
Platform: linux
OS:       posix
Python:   /usr
```

**Comment by jstriebel** [comment]
Just tested this again with poetry `1.0.0`, this behavior did not change.

#1732 seems to be a duplicate of this one.

**Comment by etijskens** [comment]
a similar problem:
I would like to deploy my projects on a HPC cluster. On this system Python versions are made available by loading modules, and they come with a number of pre-installed python packages that are optimised for our hardware, e.g. numpy 1.17.0. I create a virtual environment in the project root directory like this:

`python -m venv .venv --system-site-packages`

In this way the optimised Numpy is visible in the virtual environment. My project has a dependency
`numpy = "^1.17.0"` specified in the pyproject.toml file. When running `poetry install` it updates to the latest numpy 1.17.4. The newly installed numpy is not optimised for our hardware and in addition it consumes a lot of my file quota on the machine. This is certainly not desired behaviour, at least not in my case. Is there a way to tell poetry not to update if there is a version available that satisfies the version specification?

**Comment by etijskens** [comment]
On the other hand `pip install my_project` does exactly what I need - with exactly the same requirements. It looks to me that `poetry install` behaves rather as `poetry update`.

Still I would expect `poetry install` not to install dependencies if they are already present in the
virtual environment and satisfy the requirements, or at least to have a switch available to make it do so, although I do not see the need for a `poetry update` command in that case

**Comment by TheButlah** [comment]
My issue might be slightly different, but poetry also reinstalls dependencies for me. In my case, I have a VSCode development container. In the Dockerfile, I run `poetry install --no-root` to install the dependencies of my project based on a copied in `pyproject.toml` and `poetry.lock` without needing the project to be mounted to the docker image. Then, once the image is built, VSCode makes a container and runs `poetry install`. I would expect this second invocation of the installation should only install the current project root and not its dependencies, as the dependencies were already installed in the docker image. Poetry v1.0.0 (stable)

**Comment by simoncoulton** [comment]
Noticing this here as well. This is particularly an issue with docker multistage builds and anything that requires psycopg2 (since you want your containers to be small, you're doing any build from source related tasks in the build stage, but then Poetry tries to reinstall it and it crashes and burns).

**Comment by jstriebel** [comment]
@etijskens This issue is about re-installing *exactly* the same version. One part of your issue can be solved by fixing the exact version in the `pyproject.toml`, e.g. `numpy = "1.17.0"`. Unfortunately you will then run into the problem this issue is about, because even then the package will be re-installed, which should not be the case. If you don't need the poetry `1.0.0` features using an older poetry version (e.g. `0.12.17`) might be a viable workaround for you.

**Comment by jstriebel** [comment]
Thanks @sdispater, I can confirm that this is fixed in the current master :+1:

**Comment by jstriebel** [comment]
@sdispater Unfortunately the same issue is happening now with poetry `1.0.1` and `1.0.2` for `site-packages`. I opened a seperate issue for this, #1882.
