### ISSUE TITLE
Support `Funding` in `project_urls`

### ISSUE THREAD

**Issue by sobolevn** [python-poetry/poetry#1713]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

Currently `poetry` supports `homepage =` and `documentation =` link in `pyproject.toml`, but there's also a Funding link available. Example: https://pypi.org/project/djangorestframework/

I suggest to add `funding = ` to allow this link.

**Comment by ArtemKolichenkov** [comment]
[It is already possible.  
](https://python-poetry.org/docs/pyproject/#urls)

You put this in pyproject.toml
```
[tool.poetry.urls]
"Source" = "https://github.com/python-poetry/poetry"
"Funding" = "https://issuehunt.io/"
```

And funding link appears after you publish. It has a coin/money icon too.

**Comment by laike9m** [comment]
Does it support a list?
