### ISSUE TITLE
Install script details old API

### ISSUE THREAD

**Issue by SimonBiggs** [python-poetry/poetry#1720]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows 10
- **Poetry version**: 1.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue

The download and install script still states "You can uninstall at any time with `poetry self:uninstall`"

![image](https://user-images.githubusercontent.com/6559099/70766221-31ca9b80-1db1-11ea-869c-ee7f234c88b8.png)

**Comment by finswimmer** [comment]
Hello @SimonBiggs ,

thanks a lot for the hint. Will be fixed with #1722 .

fin swimmer

**Comment by SimonBiggs** [comment]
My pleasure :) thanks for all the hard work!!
