### ISSUE TITLE
equivalent of pip download -r requirements

### ISSUE THREAD

**Issue by jkr06** [python-poetry/poetry#1726]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

Hello,
The way we deploy our project is that all the packages are downloaded, copied to the server and installed there since the server itself doesn't have access to internet. 
To do this, it would be useful for a command like "poetry download". As a workaround, we do "poetry show" and use some awk to create a requirements.txt, which is then used to download packages using pip.

Unless I missed it somehow, I couldn't find any way of doing it with poetry itself. Probably a minor thing, but this together with an equivalent of "pip install --no-index --find-links" would make this our sole tool for package management.

**Comment by finswimmer** [comment]
Hello @jkr06 ,

there is a command to create a `requirements.txt`:

```
poetry export -f requirements.txt
```

If you would like to include development dependencies as well use the `--dev` flag. If you don't need the hashes use the `--without-hashes` argument. Then you don't need any awk for parsing.

fin swimmer

**Comment by jkr06** [comment]
Thanks @finswinner. Didn't know about that. At least we can get the requirements.txt. 
It would still be useful to have a "poetry download" option to download packages to a folder.

**Comment by chobeat** [comment]
at that point isn't enough to do `poetry run pip install ...`?

**Comment by jkr06** [comment]
Okay, I just wanted to avoid using requirements.txt. Will close this issue now.
