### ISSUE TITLE
installation through `pip` does not work

### ISSUE THREAD

**Issue by klingtnet** [python-poetry/poetry#1727]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: `Linux m604 5.4.2-arch1-1 #1 SMP PREEMPT Thu, 05 Dec 2019 12:29:40 +0000 x86_64 GNU/Linux` (output of `uname -a`)
- **Poetry version**: Installation failed.
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: None.

## Issue

```sh
$ pip list --user
# empty, no other packages installed
$ pip install --user poetry
# ...
Successfully installed cachy-0.3.0 cleo-0.7.6 clikit-0.4.1 jeepney-0.4.1 keyring-19.3.0 pastel-0.1.1 pkginfo-1.5.0.1 poetry-1.0.0 pylev-1.3.0 pyrsistent-0.14.11 requests-toolbelt-0.8.0 secretstorage-3.1.1 shellingham-1.3.1 tomlkit-0.5.8
$ poetry
Traceback (most recent call last):
  File "/home/anli/.poetry/bin/poetry", line 11, in <module>
    from poetry.console import main
  File "/home/anli/.poetry/lib/poetry/console/__init__.py", line 1, in <module>
    from .application import Application
  File "/home/anli/.poetry/lib/poetry/console/application.py", line 7, in <module>
    from cleo.formatters import Formatter
ModuleNotFoundError: No module named 'cleo.formatters'
```

**Comment by finswimmer** [comment]
Hello @klingtnet ,

have you installed poetry before with the [recommended way](https://python-poetry.org/docs/#osx-linux-bashonwindows-install-instructions) instead of using pip? What's the output of `which -a poetry` ?

fin swimmer

**Comment by klingtnet** [comment]
```sh
$ which -a poetry
/home/anli/.local/bin/poetry
/home/anli/.poetry/bin/poetry
```

**Comment by klingtnet** [comment]
Ah, `/home/anli/.poetry/bin/poetry` is the broken one. Maybe I installed it with the shell installer some time ago.

**Comment by klingtnet** [comment]
@finswimmer Thank you for the quick response, the failure was on my side. I did have two versions installed where this `/home/anli/.poetry/bin/poetry` one was broken.
