### ISSUE TITLE
Add scoop install option for Windows

### ISSUE THREAD

**Issue by ciarancourtney** [python-poetry/poetry#1730]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request
Similar to issue I opened in [pyflow](https://github.com/David-OConnor/pyflow/issues/12) which has worked great for me.

I understand this is not easy due to the python dependancy, but could poetry be bundled/frozen with pyinstaller (e.g. youtube-dl) or semi-compiled (PyOxidizer)? Are there any projects doing this?

**Comment by Secrus** [comment]
Poetry team resigned from providing distro/system-specific installers due to a lack of manpower to maintain those.
