### ISSUE TITLE
Poetry 1.0.0 always updates site-packages, is this expected behaviour?

### ISSUE THREAD

**Issue by sirmarcel** [python-poetry/poetry#1732]
I've noticed that with 1.0.0, `poetry` is now always updating packages in `site-packages`, even if no different version is available and no update is necessary:

```
  - Updating numpy (1.17.4 ~/conda-envs/clean_py37/lib/python3.7/site-packages -> 1.17.4)
```

In this case, it replaces `numpy` with the same version, but installed via `poetry` and not `conda`.

If this is the expected behaviour, it catastrophically breaks my workflow for having a fast `numpy`  (i.e. the `conda` distribution linked against `mkl`) coexist with proper dependency management via `poetry`. 

Currently, I (and many colleagues in the high performance computing corner) do the following:

- Create a minimal `conda` environment with `numpy`, `scipy`
- Create a `venv` with `--system-site-packages`, install `poetry`, disable `venv` creation with `poetry`
- Create a `pyproject.toml` specifying the exact `numpy` version already installed, and additional dependencies that `poetry` should manage

This results in (largely) properly managed dependencies for "pure python" packages and fast numerical packages. With this change, this is no longer possible.

- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

Thanks, Marcel.

**Comment by jstriebel** [comment]
See also #1711, seems to be a duplicate.

**Comment by sirmarcel** [comment]
Yes, looks like the same problem! So I guess it's not expected behaviour. Should I close this?

**Comment by finswimmer** [comment]
Closing as a duplicate pf #1711.

**Comment by etijskens** [comment]
I would like to deploy my projects on a HPC cluster. On this system Python versions are made available by loading modules, and they come with a number of pre-installed python packages that are optimised for our hardware, e.g. numpy 1.17.0. I create a virtual environment in the project root directory like this:

`python -m venv .venv --system-site-packages`

In this way the optimised Numpy is visible in the virtual environment. My project has a dependency 
`numpy = "^1.17.0"` specified in the pyproject.toml file. When running `poetry install` it updates to the latest numpy 1.17.4. The newly installed numpy is not optimised for our hardware and in addition it consumes a lot of my file quota on the machine. This is certainly not desired behaviour, at least not in my case. Is there a way to tell poetry not to update if there is a version available that satisfies the version specification?
