### ISSUE TITLE
html5lib prevents poetry running on Python3.9

### ISSUE THREAD

**Issue by ghost** [python-poetry/poetry#1733]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Any linux, have tried debian buster in a docker box, and alpine.
- **Poetry version**: 1.0.0

## Issue
html5lib, which appears to have not been updated for more than 2 years on pypi, and is only marked as supporting up to Python3.6, breaks on Python3.9. This makes poetry unusable on Python3.9a1

Since I couldn't use poetry to bootstrap poetry for this reason, I had to replicate this by making a requirements.txt that mirrors the pyproject.toml:
```
$ cat requirements.txt 
cleo>=0.7.6
clikit>=0.4.1
requests>=2.18
cachy>=0.3.0
requests-toolbelt>=0.8.0
jsonschema>=3.1
pyrsistent>=0.14.2
pyparsing>=2.2
pkginfo>=1.4
html5lib>=1.0
shellingham>=1.1
tomlkit>=0.5.8
pexpect>=4.7.0
keyring>=19.0
importlib-metadata>=0.23
cachecontrol>=0.12.4
```
...and a docker configuration like so: (you could just run this on your PC, I just used docker to ensure nothing I had could conflict with this)
```dockerfile
FROM python:3.9-rc
COPY . /poetry
WORKDIR /poetry
RUN  python -m pip install -r requirements.txt
RUN  python -m poetry show -v
```
When running this, the following behaviour will be seen:
```
Step 5/5 : RUN  python -m poetry show -v
 ---> Running in 30e3ed6a3585
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/poetry/poetry/__main__.py", line 5, in <module>
    from .console import main
  File "/poetry/poetry/console/__init__.py", line 1, in <module>
    from .application import Application
  File "/poetry/poetry/console/application.py", line 5, in <module>
    from .commands.about import AboutCommand
  File "/poetry/poetry/console/commands/__init__.py", line 4, in <module>
    from .check import CheckCommand
  File "/poetry/poetry/console/commands/check.py", line 1, in <module>
    from poetry.factory import Factory
  File "/poetry/poetry/factory.py", line 21, in <module>
    from .repositories.pypi_repository import PyPiRepository
  File "/poetry/poetry/repositories/pypi_repository.py", line 13, in <module>
    from html5lib.html5parser import parse
  File "/usr/local/lib/python3.9/site-packages/html5lib/__init__.py", line 25, in <module>
    from .html5parser import HTMLParser, parse, parseFragment
  File "/usr/local/lib/python3.9/site-packages/html5lib/html5parser.py", line 8, in <module>
    from . import _tokenizer
  File "/usr/local/lib/python3.9/site-packages/html5lib/_tokenizer.py", line 16, in <module>
    from ._trie import Trie
  File "/usr/local/lib/python3.9/site-packages/html5lib/_trie/__init__.py", line 3, in <module>
    from .py import Trie as PyTrie
  File "/usr/local/lib/python3.9/site-packages/html5lib/_trie/py.py", line 6, in <module>
    from ._base import Trie as ABCTrie
  File "/usr/local/lib/python3.9/site-packages/html5lib/_trie/_base.py", line 3, in <module>
    from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/local/lib/python3.9/collections/__init__.py)
ERROR: Service 'poetry' failed to build: The command '/bin/sh -c python -m poetry show -v' returned a non-zero code: 1
```
The [changelog for Python3.9a1](https://docs.python.org/3.9/whatsnew/3.9.html#removed) backs this up with proof that `collections` has been changed for this release of Python:
> The abstract base classes in collections.abc no longer are exposed in the regular collections module. This will help create a clearer distinction between the concrete classes and the abstract base classes.

**Comment by nekokatt** [comment]
One alternative would be to switch html5lib over to lxml, as that supports the same xmlpath syntax that html5lib does, except it is kept up to date. This would have the downside of dropping python3.4 support, however, as lxml requires Python3.5 and newer. **Alternatively** you could use a slightly outdated version of [LXML](https://pypi.org/project/lxml/4.3.5/) for the time being which does still support Python3.4, this was released at the end of July this year, so is still pretty up-to-date.

The main method that seems to use html5lib is the `search` method in pypi_repository. At a glance, this appears to just be performing a search on pypi, which can be replicated without an HTML parser using their XML-RPC api, but that is marked as deprecated and may be removed at any time, which is not ideal. Searching the source code for [warehouse](https://github.com/pypa/warehouse) seems to indicate that no search json endpoint exists.

**Comment by nekokatt** [comment]
on closer inspection, it would appear that html5lib is kept somewhat up to date, but is just not ever pushed to the html5lib pypi package you are using. This issue was fixed as of https://github.com/html5lib/html5lib-python/commit/4f9235752cea29c5a31721440578b430823a1e69

I propose that the pyproject.toml is updated to read the following:

```diff
diff --git a/pyproject.toml b/pyproject.toml
index 2aea502..f607513 100644
--- a/pyproject.toml
+++ b/pyproject.toml
@@ -33,7 +33,7 @@ pyrsistent = "^0.14.2"
 pyparsing = "^2.2"
 cachecontrol = { version = "^0.12.4", extras = ["filecache"] }
 pkginfo = "^1.4"
-html5lib = "^1.0"
+html5lib = { url = "https://github.com/html5lib/html5lib-python/zipball/4f9235752cea29c5a31721440578b430823a1e69" }
 shellingham = "^1.1"
 tomlkit = "^0.5.8"
 pexpect = "^4.7.0"
```

This fixes the issue:

```bash
/bin/sh $ python -m poetry --version
Poetry version 1.0.0
/bin/sh $ python --version
Python 3.9.0a1
/bin/sh $ python -m poetry search ping

ping (0.2)
 An implementation of ICMP ping in Python

ping3 (2.4.0)
 A pure python3 version of ICMP ping implementation using raw socket.

... ... ...
```

**Comment by dimaqq** [comment]
I guess that the trouble with `lxml` is that is requires a compiled `libxml2`, while `html5lib` is pure-Python.
Since `html5lib` is vendored, let's just hack around the limitation, either by `s/collections/collections.abc/` or by pulling an unpushed release :)

**Comment by nekokatt** [comment]
FYI: https://github.com/html5lib/html5lib-python/issues/419#issuecomment-591039618

Maintainer's response today for a course of action

**Comment by stephanlukasczyk** [comment]
FYI: Poetry 1.0.5 now runs with Python 3.9.0a4 in a Debian Buster container (container `3.9-rc-buster` from https://hub.docker.com/_/python) on my machine. I am not sure, however, whether it is because of yesterday's Poetry release or because of the fourth alpha of Python.

**Comment by hugovk** [comment]
The collections.abc removal has been postponed to Python 3.10, so the removal was reverted in the new 3.9 alpha. 

https://github.com/python/cpython/pull/18545

**Comment by pikeas** [comment]
Assuming that html5lib's master branch doesn't break enough relative to their old PyPi release, a temporary solution is to update your html5lib package **in your poetry venv** rather than your project.

With pipx, I did:
```
pipx inject poetry git+https://github.com/html5lib/html5lib-python.git@d49afd350c06339a8c59299664b8a73a3b2c3f64
```

**Comment by finswimmer** [comment]
Because poetry is runnnig fine with pythn3.9 for a long time now, I guess we can close this here.
