### ISSUE TITLE
`pip check` raises `you have importlib-metadata 1.2.0`

### ISSUE THREAD

**Issue by sobolevn** [python-poetry/poetry#1740]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **Poetry version**: 1.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

https://github.com/wemake-services/wemake-django-template/blob/master/%7B%7Bcookiecutter.project_name%7D%7D/pyproject.toml

## Issue

When I install my dependencies inside a docker container and run `pip check`, I get this error:

```
poetry 1.0.0 has requirement importlib-metadata<0.24,>=0.23; python_version < "3.8", but you have importlib-metadata 1.2.0.
```

Link: https://travis-ci.com/wemake-services/wemake-django-template/jobs/267099147#L998

I guess that it is related to https://github.com/python-poetry/poetry/issues/1487

As a workaround I just install the version it requires with `pip install -U 'importlib-metadata<0.24,>=0.23'` or it can be possibly added to `pyproject.toml`

**Comment by sobolevn** [comment]
Related: https://github.com/wemake-services/wemake-django-template/issues/1015

**Comment by sobolevn** [comment]
This change did the trick for me: https://github.com/wemake-services/wemake-django-template/commit/550016cc6af55af86435e8edc507ead202943579#diff-5da2e59adac77c3a7b06177ffd67ed34R33-R36 But, it is a dirty hack not a solution I can be proud of.

**Comment by damienallen** [comment]
As @ajslater found in his linked issue, this dep has been removed somewhere between v1.0 and v1.1 releases.

We are running poetry v1.1.4 and no longer need a workaround to avoid the `pip check` issue. I think this can be closed.
