### ISSUE TITLE
Adding git dependency from subproject failes

### ISSUE THREAD

**Issue by finswimmer** [python-poetry/poetry#1746]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **Poetry version**: 1.0.0.

## Issue

At least with gitlab it is possible to organize your repositories in project and subprojects. This results in longer path names, e.g. `https://example.org/project/subproject/rep.git`

Trying to add this to a poetry project results in:

```
[CalledProcessError]
Command '['git', 'clone', 'git+https://example.org/project/subproject/rep.git', '/tmp/pypoetry-git-repuqxf81sd']' returned non-zero exit status 128.
```

The cause for this is that no regex in `git.py` matches this path.

I've already started to fix it.

fin swimmer

**Comment by languitar** [comment]
This is still not solved generically, even with Gitlab. URLs of the following form also do not work:
```
git+https://gitlab.com/org/group/project.git#12345678"
```
An if you're hosting the Git repo on your own, levels can go as deep as you want.

**Comment by languitar** [comment]
Ok, I see, there is a fix for that case on master, but it hasn't been released yet.
