### ISSUE TITLE
venvs get orphaned after 1.0.0 upgrade

### ISSUE THREAD

**Issue by MadWombat** [python-poetry/poetry#1749]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: OS X
- **Poetry version**: 1.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 
https://gist.github.com/MadWombat/119e51ea342e269ff979becb79c721d5

## Issue
Had a project using poetry. After the upgrade to 1.0.0 poetry created a new venv and I had to run `poetry install` to install all the dependencies again. When I checked in ~/Library/Caches/pypoetry/virtualenvs the original venv was still there, but it is not detected and is not listed in `poetry env list` output.

Looks like naming convention for venvs changed in 1.0.0, but it would be nice if old style venvs were still detected and maybe renamed instead of just abandoning them.

Pipenv got a lot of flak for doing this exact thing, by the way.

**Comment by finswimmer** [comment]
Hello @MadWombat ,

yes this was one of the few breaking changes when switching to 1.0.0. I guess there will be no implementation to detect the old venvs as it would be not a good idea to still support something you like to get rid of.

fin swimmer

**Comment by MadWombat** [comment]
You don't have to support the old style. You could rename old style venv to the new naming convention. But the way it is, you are orphaning potentially gigabytes of disk space in a hidden location, you are breaking the user experience, since poetry install needs to run and anything that was not managed by poetry in the venv has to be configured again etc. 

But hey, whatever, thank you for the wonderful thing you are making. Hope this kind of breakage only happened as a transition between 0.x and 1.0
