### ISSUE TITLE
Self signed certificates for seconday repositories broken

### ISSUE THREAD

**Issue by nylocx** [python-poetry/poetry#1752]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Arch Linux (5.4.2-arch1-1)
- **Poetry version**: 1.0.0

## Issue
I have a private repository with a self signed certificate and I was not able to find an option like the pip --trusted-host switch to enable poetry to pull packages from this repository without complaining about the untrusted certificate.
I first tried with the solution from the documentation of:
`poetry config certificates.my_repo.cert ~/my_cert.pem `

After that the Install from the repo worked but I got an certificate error for other packages from host='pypi.org', port=443 saying: 

> certificate verify failed: unable to get local issuer certificate

In the bug tracker I found the hint of using `REQUESTS_CA_BUNDLE`. So I added the certificate to my system cert-store rebuild trust and exported the environment variable. But this seems really cumbersome in a local secure network where I don't expect any from of MITM attacks. So my only options are providing my repo without https (wich gave me some problems with other tools) or using this ugly workaround.
It would be really nice if the  `[[tool.poetry.source]] ` section would have a simple flag like validate_tls=false or something like this.

-- Edit
I tried to review the feature (https://github.com/python-poetry/poetry/pull/1325) to see where it fails but I could not spot it at the first glance. But for a start I think it would be a good test case to check that installation from pypi still work after adding a certificate for a custom repository.

After this bit *rantishly* report I would like to add that I really love what you have created here and I hope you will keep up this great project. I also could not find a donate section on you homepage so maybe you could add this for others that don't have time to contribute content but would like to help the project financially.

**Comment by polski-g** [comment]
I am not able to reproduce your issue. If I set the certificates.my_repo.cert with full path to the CA bundle, I can use a local devpi install behind an HTTPS reverse proxy.

**Comment by nylocx** [comment]
> If I set the certificates.my_repo.cert with full path to the CA bundle

If I add my own certificate to the system CA bundle this works, but what I would really like to be able to is to tell poetry to accept a specified certificate in addition to the system default certs.
I have not tested this for a while as we provisioned the hosts with the cert, but I think adding an additional certificate would be a good thing.

**Comment by absassi** [comment]
I'm not sure if that's the same issue you have, but at least for me, `poetry config repositories.foo.cert path` is broken. It creates a repository called `foo.cert` with the (invalid) URL `path`, instead of setting the `cert` property of repository `foo` to `path`.

However, even fixing this by editing the `config.toml` manually, it still doesn't work for me.

**Comment by stevenayers** [comment]
We ran into this issue, and adding the SSL certs to the system store across multiple different operating systems can be a pain, and relying on env vars can sometimes be a little flakey depending on how many python environments you have set up.

I hope anyone reading this thread finds this script useful in future: https://gist.github.com/stevenayers/f15866f4aec83e645c7b42ec60a9721b
