### ISSUE TITLE
Private Repo dependency requires verbose install

### ISSUE THREAD

**Issue by nathanrpage97** [python-poetry/poetry#1758]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Raspbian GNU/Linux 10 (buster)
- **Poetry version**: 1.0.0

## Issue

When having a private https repo (requiring user to input credentials)
```
poetry install
``` 
will be stuck in resolving dependencies (I assume it is stuck waiting for credential input) .

I get it to work by running verbosely:
```
poetry install -vv
```
where it successfully provides login prompts. I am not sure if that is intended behavior, if so I have not found it documented anywhere.

**Comment by AlJohri** [comment]
I highly recommend caching your github password with the git: https://help.github.com/en/github/using-git/caching-your-github-password-in-git

**Comment by tetienne** [comment]
@AlJohri With Jenkins, Travis or similar how will you configure the helper?

**Comment by PierreAndreNoel** [comment]
I can confirm this behavior in 1.0.5 under Ubuntu 18.04. I believe this needs triage.

**Comment by mkniewallner** [comment]
Hi, this issue has been open for quite a while. Does anyone of you still reproduce on the recently released [1.2.0](https://github.com/python-poetry/poetry/releases/tag/1.2.0)?

**Comment by finswimmer** [comment]
Hey,

this should be fixed by #6966.

Please leave a comment if you disagree.

fin swimmer
