### ISSUE TITLE
Install git: Setup.py Parsing

### ISSUE THREAD

**Issue by duichwer** [python-poetry/poetry#1761]
Hello,

I tried to install a git dependency since the master branch include needed fixes for the development.
Then I received the following error:
```bash
[RuntimeError]                                                 
Unable to retrieve the package version for /tmp/pypoetry-git-self-attentive-parserXXXXX
```

Based on this error I found the following issue describing a similar problem: https://github.com/python-poetry/poetry/issues/673

I tried to add setuptools as `dev dependency` and installed it as suggested. 
This doesn't helped me and I still recieved the same error message.

Then I took a deeper look into the `setup.py` of this project (https://github.com/nikitakit/self-attentive-parser/blob/master/setup.py#L23)

There I have seen that `setup(` was called as `setuptools.setup(` instead of the most common way to import the setup command directly.

After changing this to `setup` on my fork everything worked fine.

- [x ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x ] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Issue

Now my question:

Is this an issue with `ast` parsing and can this be solved in poetry itself or should I ask the project owner to change its `setup.py`?

**Comment by finswimmer** [comment]
In my opinion `poetry` should be able to parse `setuptools.setup()`.

Fix is on the way: #1764 

Thanks a lot for reporting!
