### ISSUE TITLE
`poetry cache clear --all` does not work

### ISSUE THREAD

**Issue by sobolevn** [python-poetry/poetry#1763]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macos
- **Poetry version**: `1.0`
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**:  (not related) https://github.com/wemake-services/wemake-python-styleguide/blob/master/pyproject.toml

## Issue

When I try to run `poetry cache clear --all` it does not work.

```
(.venv) ~/Documents/github/wemake-python-styleguide  master ✗                     1 ⚠️
» poetry cache clear --all
Not enough arguments (missing: "cache").

(.venv) ~/Documents/github/wemake-python-styleguide  master ✗                     1 ⚠️
» poetry cache clear --all all
No cache entries for all

(.venv) ~/Documents/github/wemake-python-styleguide  master ✗                        
» poetry cache clear --all .  
Delete 1048 entries? (yes/no) [no] yes
```

Solution: `poetry cache clear --all .`
But, this was unexpected. I suggest to allow `poetry cache clear --all` to clear the cache.

**Comment by 515hikaru** [comment]
This is similar to #521

**Comment by sobolevn** [comment]
Yes, this is a duplicate. Closing in favour of https://github.com/python-poetry/poetry/issues/1763
Thanks!
