### ISSUE TITLE
Update version 1.0.0+ doc and installation , configurations

### ISSUE THREAD

**Issue by auvipy** [python-poetry/poetry#1769]
Installing version: 1.0.0
  - Downloading poetry-1.0.0-linux.tar.gz (27.76MB)

Poetry (1.0.0) is installed now. Great!

To get started you need Poetry's bin directory ($HOME/.poetry/bin) in your `PATH`
environment variable. Next time you log in this will be done
automatically.

To configure your current shell run `source $HOME/.poetry/env`

asif@ck ~> poetry self update --preview
poetry: command not found

**Comment by tomzx** [comment]
Could you please add more context to your issue, it is not clear what you would like to see changed.

**Comment by auvipy** [comment]
the default install and usage is not working on ubuntu 19.10 mate as described in readme

**Comment by finswimmer** [comment]
Hello @auvipy ,

which shell are you using? What's the output of `echo $PATH`?

fin swimmer

**Comment by auvipy** [comment]
bash, and fish some times. But the issue is about the new setup process for poetry.

~> echo $PATH
/home/asif/.poetry/bin /home/asif/.local/bin /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /usr/games /usr/local/games /snap/bin /home/asif/.local/bin /home/asif/.local/bin

**Comment by auvipy** [comment]
poetry
/home/asif/.poetry/lib/poetry/_vendor/py2.7/subprocess32.py:149: RuntimeWarning: The _posixsubprocess module is not being used. Child process reliability may suffer if your program uses threads.
  "program uses threads.", RuntimeWarning)
Poetry version 1.0.0
  and now working after restarting pc!
