### ISSUE TITLE
[TypeError] distributions() got an unexpected keyword argument 'path'

### ISSUE THREAD

**Issue by gregthewhite** [python-poetry/poetry#1775]
- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

```
Poetry
Version: 1.0.0
Python:  3.6.8

Virtualenv
Python:         3.6.8
Implementation: CPython
Path:           NA

System
Platform: linux
OS:       posix
Python:   /usr/local
```

- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/gregthewhite/e2bbd4c30d6aeefb7efcb51eac53564f
## Issue
Running
`poetry add sendgrid-django -vvv`
spits out
```
Skipping virtualenv creation, as specified in config file.
PyPI: 18 packages found for sendgrid-django *
Using version ^4.2.0 for sendgrid-django


[TypeError]
distributions() got an unexpected keyword argument 'path'

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/clikit/console_application.py", line 131, in run
    status_code = command.handle(parsed_args, io)
  File "/usr/local/lib/python3.6/site-packages/clikit/api/command/command.py", line 120, in handle
    status_code = self._do_handle(args, io)
  File "/usr/local/lib/python3.6/site-packages/clikit/api/command/command.py", line 171, in _do_handle
    return getattr(handler, handler_method)(args, io, self)
  File "/usr/local/lib/python3.6/site-packages/cleo/commands/command.py", line 92, in wrap_handle
    return self.handle()
  File "/usr/local/lib/python3.6/site-packages/poetry/console/commands/add.py", line 141, in handle
    self.io, self.env, self.poetry.package, self.poetry.locker, self.poetry.pool
  File "/usr/local/lib/python3.6/site-packages/poetry/installation/installer.py", line 55, in __init__
    installed = self._get_installed()
  File "/usr/local/lib/python3.6/site-packages/poetry/installation/installer.py", line 488, in _get_installed
    return InstalledRepository.load(self._env)
  File "/usr/local/lib/python3.6/site-packages/poetry/repositories/installed_repository.py", line 20, in load
    metadata.distributions(path=env.sys_path), key=lambda d: str(d._path),
```

**Comment by gregthewhite** [comment]
For added context, no matter what I try to install this error happens. It adds to the toml file but doesn't get far enough to update the lock file.

Happens when I run an add or remove command.

**Comment by gregthewhite** [comment]
I saw this issue but couldn't figure out how to fix using the guidance from the commenter. https://github.com/python-poetry/poetry/issues/1691

**Comment by gregthewhite** [comment]
For more details for the next person, I had to manually update the poetry.lock file to use a higher version `for importlib_metadata` (in this case `0.24`) then `poetry remove importlib_metadata`(to get it out of the lock file as a dependency) and then `poetry add importlib_metadata`

Had to do the poetry version of turning it off and turning back on again, but that smacked some sense into the dependency resolver.

**Comment by cromefire** [comment]
I removed the lock file but still got that problem

**Comment by adarmaor** [comment]
My `importlib_metadata` needed to be pip uninstalled before poetry could install the correct version itself and lock dependencies. (it was `0.19`)

**Comment by ribitskiyb** [comment]
Just a follow-up comment for those who like me wasn't able to solve that problem using info from both of the GH Issues above:

solved by upgrading my python version in pyenv from 3.8.0b4 to 3.8.10
