### ISSUE TITLE
could poetry env info tell what kind of virtual environment is used? venv/virtualenv/conda

### ISSUE THREAD

**Issue by etijskens** [python-poetry/poetry#1777]
would be useful info.

**Comment by etijskens** [comment]
I have a conda environment activated, here is the output I get. Especially the first line is confusing:

> poetry env info 

**Virtualenv**
Python:         3.7.5
Implementation: CPython
Path:           /Users/etijskens/software/dev/workspace/ET-dot/.cenv37
Valid:          True

System
Platform: darwin
OS:       posix
Python:   /Users/etijskens/software/dev/workspace/ET-dot/.cenv37

**Comment by finswimmer** [comment]
Hey,

while it would be possible to tell if the environment is a conda environment or not, there is no way to tell which tools was used to create the venv (if not conda).

fin swimmer
