### ISSUE TITLE
Install libs to a target dir

### ISSUE THREAD

**Issue by c0debreaker** [python-poetry/poetry#1778]
Hi all. I can't figure out a way in poetry where I can specifically install 3rd party libraries to a specific directory. This feature helps with deploying python functions that will be used in AWS Lambda.

Currently I'm doing this. `pip install request --target vendor`.

The vendor is just a directory that will be included the zip when I make a AWS cdk deployment.

**Comment by sisp** [comment]
A workaround is to export your dependencies as `requirements.txt` with `poetry` and install them using `pip`:

```bash
$ pip install -r requirements.txt --target vendor
```

**Comment by c0debreaker** [comment]
Hi @sisp I'm new to poetry. How can I export the deps as requirements.txt? do I just execute `ls` on the directory where modules are installed and copy all the diriectory names and put them in requirements.txt file?

**Comment by sisp** [comment]
Poetry 1.0 introduced the export command. See https://python-poetry.org/docs/cli/#export for more details.

**Comment by c0debreaker** [comment]
Thank you!
