### ISSUE TITLE
Nested packages fail to build

### ISSUE THREAD

**Issue by MatanRubin** [python-poetry/poetry#1787]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS Catalina
- **Poetry version**: 1.0.0

### tl;dr 
The following script:

```
poetry new code-generator
cd code-generator
git init
poetry install
mkdir build && cd build
poetry new generated-project
cd generated-project
poetry install
poetry build
```
 fails for a reason I cannot understand, with the following message:

```
Using virtualenv: /private/tmp/code-generator/build/generated-project/.venv
Building generated-project (0.1.0)
 - Building sdist
 - Adding: pyproject.toml
 - Built generated-project-0.1.0.tar.gz


[ModuleOrPackageNotFound]
No file/folder found for package generated-project

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/clikit/console_application.py", line 131, in run
    status_code = command.handle(parsed_args, io)
  File "/usr/local/lib/python3.7/site-packages/clikit/api/command/command.py", line 120, in handle
    status_code = self._do_handle(args, io)
  File "/usr/local/lib/python3.7/site-packages/clikit/api/command/command.py", line 171, in _do_handle
    return getattr(handler, handler_method)(args, io, self)
  File "/usr/local/lib/python3.7/site-packages/cleo/commands/command.py", line 92, in wrap_handle
    return self.handle()
  File "/usr/local/lib/python3.7/site-packages/poetry/console/commands/build.py", line 30, in handle
    builder.build(fmt)
  File "/usr/local/lib/python3.7/site-packages/poetry/masonry/builder.py", line 21, in build
    return builder.build()
  File "/usr/local/lib/python3.7/site-packages/poetry/masonry/builders/complete.py", line 59, in build
    original=self._poetry,
  File "/usr/local/lib/python3.7/site-packages/poetry/masonry/builders/wheel.py", line 54, in make_in
    wb = WheelBuilder(poetry, env, io, target_dir=directory, original=original)
  File "/usr/local/lib/python3.7/site-packages/poetry/masonry/builders/wheel.py", line 44, in __init__
    super(WheelBuilder, self).__init__(poetry, env, io)
  File "/usr/local/lib/python3.7/site-packages/poetry/masonry/builders/builder.py", line 68, in __init__
    includes=self._package.include,
  File "/usr/local/lib/python3.7/site-packages/poetry/masonry/utils/module.py", line 59, in __init__
    'No file/folder found for package {}'.format(name)
```
### Long version:
I'm building a Python code generator that builds other Python projects. 
Both the code-generator and the generated project (which resides in the `build` directory) use Poetry to manage dependencies.
When I try to package the generated project - I get the above error.

Some weird things I noticed are:
1. The above script does not fail if I remove the `git init` step
1. The above script does not fail if I remove the `mkdir build && cd build` step
1. The script does not fail if I add a `git init` after `cd generated-project` 

From my perspective, these are just two unrelated projects that happen to sit in the same directory tree. Obviously Poetry sees things differently, and git has something to do with it. 
Does Poetry use git to locate the root of the project or something like that? Maybe that's the issue?

P.S. Poetry is awesome! Great work!

**Comment by finswimmer** [comment]
Hello @MatanRubin,

do you have a `.gitignore` file that contain something like `build`?

`poetry build` checks for excluded files that are excluded by `git`. Your subfolders belong all to the same git projects.

fin swimmer

**Comment by MatanRubin** [comment]
Indeed, the `build` directory is gitignored, as the build output (i.e. the generated project) should not be committed.

I understand why Poetry ignores files in gitignore, so what would be the best solution for me?

I can think of the following workarounds, but was wondering if you can think of a less hacky way:

1. Do `git init` in the generated project before building the package.
2. Move the generated project to a directory which is not ignored before building it.

I'm building the package as part of an automatic pipeline, so I'm ok with adding this to the pipeline  (as it wouldn't impact developers, just the pipeline), but if there's a better solution please let me know.

**Comment by finswimmer** [comment]
IMO 

> Move the generated project to a directory which is not ignored before building it.

do this or just use a different name then `build` for the directory.

Merry Christmas :christmas_tree:

**Comment by MatanRubin** [comment]
Thanks. The problem is not that the directory name is "build".

"build" is ignored on purpose because I really do want to ignore build outputs and never commit them to git. The problem is that my build output is a Python project which I want to package using poetry.

Anyways, thanks for your help and Merry Christmas!
