### ISSUE TITLE
Poetry and build dependencies

### ISSUE THREAD

**Issue by zsol** [python-poetry/poetry#1792]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Issue

The `build-system.requires` section in `pyproject.toml` describes packages that need to be present for building the project. Should `poetry build` make sure they are present before it starts the build process? That's the behavior of `pip` anyway as far as I can tell. 

Note that these dependencies are different from dev-dependencies; the main use case I have in mind is poetry "plugins" (namely `poetry-dynamic-versioning`).

**Comment by finswimmer** [comment]
Hello @zsol,

as long as poetry doesn't support officially custom build scripts, this is not necessary. But as soon as this is  officially supported, this will be necessary.

fin swimmer

**Comment by zsol** [comment]
Not sure I fully understand how custom build scripts enter the picture. PEP-518 says those packages are dependencies of the build as far as I can tell, they're not specific to poetry at all. Shouldn't `poetry build` install those in some environment and then invoke `build-backend` in it?

**Comment by finswimmer** [comment]
Ah, now I see what's your point (At least I guess I see it ;) ) 

At the moment `poetry build` can just build packages from poetry projects. It doesn't run any other `build-backend` given in the `pyproject.toml` and therefore does not need to take care of any `build-system.requires`.
