### ISSUE TITLE
Possibility to create and use sub venvs `using poetry shell/install` while already in a venv

### ISSUE THREAD

**Issue by FransDel** [python-poetry/poetry#1795]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Issue

Hello, I've started using poetry to replace pipenv in a project and I haven't seen any issue/documentation discussing this matter. If something already exists discussing this matter I would like to apologise in advance.

I'm currently using poetry inside a virtualenv with other build dependencies and I have a script building and packaging all sub-parts the project which all have their separate environments. I used to use pipenv shell/install which would create new venv's for each sub-part of my project in my build directory. Right now poetry shell doesn't create a new sub-virtualenv since my building virtualenv is already activated. I still need to create the sub-virtualenvs since the sub-projects built code are sent to run on different targets. 

I'm not sure if I'm doing everything properly and any suggestions on how to better build the project would be great. Still I think that it would be great if a parameter in `poetry.toml` or in poetry shell (or install) allowed poetry to override the current venv to create and activate another sub-venv. 

I'm currently using this configuration in all the sub components of the project : 
```
[virtualenvs]
create = true
in-project = true
virtualenvs.path = "./.venv"
```

Notice that even if virtualenvs.path is different then the building venv path it won't create and activate the new sub-project venvs. Another solution could be to create and activate a new venv if the designated sub-venv isn't the same as the root one.

**Comment by neersighted** [comment]
Duplicate #4055
