### ISSUE TITLE
"poetry list" is not defined

### ISSUE THREAD

**Issue by michaelaye** [python-poetry/poetry#1798]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

2nd paragraph on https://python-poetry.org/docs/cli/ says I could do `poetry list` to see a list of commands, but doing so issues `not defined`:

```bash
$ poetry list                                                                                (base)
The command "list" is not defined.
```

**Comment by finswimmer** [comment]
Thanks a lot for the hint!
