### ISSUE TITLE
`poetry update` has inconsistent behaviour

### ISSUE THREAD

**Issue by skorokithakis** [python-poetry/poetry#1804]
- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 19.04
- **Poetry version**: 1.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://www.pastery.net/fhuqdt/

## Issue

Trying to upgrade a single package upgrades others. Also, `pygments` is pinned to `^2.4.2` but poetry upgraded it to 2.5.2.

```
14:35:39 $ poetry update django-webauthin
Updating dependencies
Resolving dependencies... (0.4s)


Package operations: 0 installs, 13 updates, 0 removals

  - Updating parso (0.5.1 -> 0.5.2)
  - Updating jedi (0.15.1 -> 0.15.2)
  - Updating prompt-toolkit (2.0.10 -> 3.0.2)
  - Updating pygments (2.4.2 -> 2.5.2)
  - Updating ansible (2.9.0 -> 2.9.2)
  - Updating django-annoying (0.10.5 -> 0.10.6)
  - Updating django-bootstrap3 (11.1.0 -> 12.0.3)
  - Updating django-redis (4.10.0 -> 4.11.0)
  - Updating django-sendgrid-v5 (0.8.0 -> 0.8.1)
  - Updating django-tokenauth (0.3.0 -> 0.4.0)
  - Updating django-webauthin (0.0.3 -> 0.0.4)
  - Updating ipython (7.9.0 -> 7.11.0)
  - Updating whitenoise (4.1.4 -> 5.0)
```

**Comment by skorokithakis** [comment]
Also, trying to upgrade `django-webauthin` from 0.0.3 to 0.0.4 does nothing most of the time I run it (I suspect a caching issue).

**Comment by eugenetriguba** [comment]
@skorokithakis In regard to your comment on `pygments` being pinned to `^2.4.2` but poetry upgraded it to `2.5.2`, is that not the intended behavior with the `^` version constraint? Same with your comment on `django-webauthin`. 

https://python-poetry.org/docs/versions/

**Comment by skorokithakis** [comment]
@eugenetriguba ah, it appears I had conflated `^` and `~`, thank you.
