### ISSUE TITLE
Annotate generated requirements.txt with origin of dependency

### ISSUE THREAD

**Issue by jimmywan** [python-poetry/poetry#1805]
In the process of switching from pip/pip-tools to poetry for dependency resolution and noticed that I lost the annotations around the origin of a dependency. I found these to be pretty helpful, especially when you notice a whole bunch of dependencies being pulled in by something that you might not actually need.
I hope that you consider implementing this!

Example before:
```
cachetools==3.1.1         # via google-auth
certifi==2019.11.28       # via requests
chardet==3.0.4            # via requests
```

Example after:
```
cachetools==4.0.0
certifi==2019.11.28
chardet==3.0.4
```

**Comment by n8sty** [comment]
Even though it's more difficult to grok at a glance I think `poetry.lock` accomplishes this. Here's a really quick take at parsing the lock file into something a bit more readable:

```
import toml
with open("poetry.lock", "r") as f:
    lock = toml.load(f)
for package in lock["package"]:
    print(package["name"], f"({package['version']})", package.get("dependencies"))
```

which returns:

```
dj-database-url (0.5.0) None
django (3.0.1) {'asgiref': '>=3.2,<4.0', 'pytz': '*', 'sqlparse': '>=0.2.2'}
django-health-check (3.11.1) {'django': '>=1.11'}
django-split-settings (1.0.0) None
django-stubs (1.4.0) {'django': '*', 'mypy': '>=0.760,<0.770', 'typing-extensions': '*'}
```

**Comment by jimmywan** [comment]
Now that I'm more familiar with poetry.lock, I'm not sure my original request is really required. Closing.
