### ISSUE TITLE
Equivalent of "pip wheel"/"pip download" commands

### ISSUE THREAD

**Issue by enpaul** [python-poetry/poetry#1806]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

Let me first open with saying how much I am loving using Poetry. It's solved a number of problems and we (my department at work) are currently working on restructuring a lot of our build infrastructure around it.

Something I've encountered that would be useful for our build systems would be introducing an equivalent of the [`pip download ...`](https://pip.pypa.io/en/stable/reference/pip_download/) and/or [`pip wheel ...`](https://pip.pypa.io/en/stable/reference/pip_wheel/) commands to the `PipInstaller` class. I believe that this could be accomplished by an adjustment to how the arguments are built up for [`PipInstaller().run()`](https://github.com/python-poetry/poetry/blob/master/poetry/installation/pip_installer.py#L117).

This would allow us to take advantage of Poetry's locking system without having to install to a virtualenv, or having to interact with Pip at all. Specifically, we're looking to be able to do this programmatically, using Poetry as a library rather than as a command line tool (which unfortunately makes the answer to [this question](https://github.com/python-poetry/poetry/issues/1726) inapplicable). If there is interest, the new options could be exposed in the CLI as well; something like `poetry download` with an optional `--wheel` flag.

If this feature is accepted I could work on implementing it.

Summary:
* Add new method `download` to the `PipInstaller` class: downloads the specified package to a directory
* Add new method `wheel` to the `PipInstaller` class: downloads the specified package to a directory and builds it to a wheel
* **Optionally** add `poetry download` command to download one or more packages to a directory
  * Include `--wheel` flag to automatically build downloaded packages into wheels

**Comment by mburszley** [comment]
It looks like all of the cli commands are [here](https://github.com/python-poetry/poetry/tree/master/poetry/console/commands) so this feature would need something akin to `download.py` that inherits from `Command` here.

**Comment by earonesty** [comment]
i'm assuming your use case is to snapshot all the deps to a build cache so that they can be loaded on a runner/server that doesn't necessarily have access to the internet?  or to get-around the inability for virtual envs to be effectively reused (due to hardcoded paths in the venv).

**Comment by obviousrebel** [comment]
This would be very useful for our project as deploy environment is air-gapped. Workaround is to export from poetry to requirments.txt then do pip download on the resulting requirments.txt.

**Comment by neersighted** [comment]
Duplicate #2184
