### ISSUE TITLE
No module named 'dataclasses' for py3.6 when poetry reports it is installed

### ISSUE THREAD

**Issue by dazza-codes** [python-poetry/poetry#1821]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).
  - no exception is reported

## Versions

```
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"
$ poetry --version
Poetry version 1.0.0
$ which conda
/opt/conda/condabin/conda
$ conda --version
conda 4.8.0
$ which python
/opt/conda/envs/project/bin/python
$ python --version
Python 3.6.7
```

## Issue

```
$ conda create -y -n project python=3.6
$ conda activate project
$ poetry add dataclasses
$ poetry show -t | grep dataclasses
dataclasses 0.7 A backport of the dataclasses module for Python 3.6

$ python
Python 3.6.7 | packaged by conda-forge | (default, Nov  6 2019, 16:19:42) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dataclasses
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'dataclasses'
```

**Comment by bertjwregeer** [comment]
poetry creates it's own virtualenv, try running:

```
poetry run python
```

And attempt to import data classes again.

**Comment by dazza-codes** [comment]
But poetry 1.x responds to `poetry shell` with a message that the virtualenv is already active, so that means `poetry run` is no longer needed, if I understand this correctly.

**Comment by finswimmer** [comment]
Hello @dazza-codes,

you haven't come back to this issue for a long while. So I assume this is solved in the meantime and I can close this ticket.

Feel free to leave a comment if you disagree.

fin swimmer
