### ISSUE TITLE
Failed to add dependency with extras

### ISSUE THREAD

**Issue by AndreGuerra123** [python-poetry/poetry#1827]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS Catalina latest
- **Poetry version**: 1.0.0

## Issue

I get the following error when trying to add dependencies with extras, namely:

`poetry add dynaconf[yaml]
`

but It happens with every dependency with extras such as the one present in the documentation example:

`poetry add requests[security,socks] -vvv
`
The error is always the same:

> zsh: no matches found: requests[security,socks]

Best regards,

**Comment by AndreGuerra123** [comment]
Ok, I found out the docs are misleading. 
The correct command would be `poetry add dynaconf --extras yaml`
Works like a charm. Closing.

**Comment by Pycz** [comment]
> Ok, I found out the docs are misleading.
> The correct command would be `poetry add dynaconf --extras yaml`
> Works like a charm. Closing.

`poetry add 'dynaconf[yaml]'` must work as well.
