### ISSUE TITLE
Poetry using dependency that I haven't installed

### ISSUE THREAD

**Issue by zachvalenta** [python-poetry/poetry#1842]
- **OS version and name**: macOS Mojave 10.14.13
- **Poetry version**: 1.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/zachvalenta/66cb520ba2fcbdb980e5c248acefacb4

## Issue

* tldr: Poetry is using a dependency it didn't install.
* context: porting a Flask project from pip to Poetry

---

In a Makefile, I have a rule using `httpie` to hit an endpoint:
```make
get:
    source venv/bin/activate; http http://localhost:500
```

I'm porting the project to Poetry, so I updated the Makefile:
```make
get:
    poetry run http http://localhost:500
```

However, I did not install `httpie` yet, as the [`pyproject.toml`](https://gist.github.com/zachvalenta/66cb520ba2fcbdb980e5c248acefacb4) and `poetry show` displays:
```log
flask 1.1.1 A simple framework for building complex web applications.
├── click >=5.1
├── itsdangerous >=0.24
├── jinja2 >=2.10.1
│   └── markupsafe >=0.23
└── werkzeug >=0.15

python-dotenv 0.10.3 Add .env support to your django/flask apps in development and deployments
```

And yet when I use the Makefile command (`make get` updated to use `poetry run` ) Poetry is still able to locate and use `httpie`, even though I haven't installed `httpie` yet.

At first I thought maybe I had `httpie` installed in some global way, but it's neither installed by pipx nor pip.

I suspect I've overlooked something obvious but at present can't figure out what, hence this ticket.

**Comment by tomzx** [comment]
What does `which http` return you? I'd investigate where the `http` binary is found and I'd also try running `http` outside of your python project. If it still works, that's unrelated to poetry.

**Comment by zachvalenta** [comment]
I did overlook something obvious. `httpie` was installed as a transitive dep for another Homebrew package. @tomzx thanks for the help, appreciate it.
