### ISSUE TITLE
Does not work with python from windows store

### ISSUE THREAD

**Issue by gazpachoking** [python-poetry/poetry#1850]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows 10
- **Poetry version**: 1.0.0

## Issue

It seems poetry has a problem when using python installed via the windows store. I believe this is related to #816 Poetry believes it has created a venv in my AppData folder, however this folder is never created, and thus gives a filenotfound error when trying to use this venv.

The following are the errors when I try to add an environment based on a windows store python, and then again on a non-windows store python. I believe the latter isn't working because I installed poetry using the python version from the windows store.

https://gist.github.com/gazpachoking/1dd3fdfd9be5d65882e3506864e1522c

**Comment by gazpachoking** [comment]
I have verified that everything does indeed work once the cache directory is moved with

```
poetry config cache-dir "%USERPROFILE%\pypoetry\Cache"
```

**Comment by radek-sprta** [comment]
I can confirm the issue..

**Comment by ofek** [comment]
https://github.com/ofek/userpath/issues/25#issuecomment-652009503

**Comment by nstrelow** [comment]
Is this now working? I am still having problems

**Comment by finswimmer** [comment]
Closing this in favor of https://github.com/python-poetry/poetry/issues/5331
