### ISSUE TITLE
Why can't poetry install the virtual environment on the specified path?

### ISSUE THREAD

**Issue by abersheeran** [python-poetry/poetry#1852]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

Why can't poetry install the virtual environment into the project like pipenv or npm, so that when we clean up the project, we can clean up the virtual environment together, instead of executing the commands one by one.

**Comment by finswimmer** [comment]
Hello @abersheeran,

`poetry` can do this. But you have to change the config first. It's mentioned in the [docs](https://python-poetry.org/docs/configuration/#virtualenvsin-project-boolean)

```
$ poetry config virtualenvs.in-project true
```

fin swimmer
