### ISSUE TITLE
Config: Disable environment prompt when using shell

### ISSUE THREAD

**Issue by MooseV2** [python-poetry/poetry#1853]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

Recently, a feature was added that allows `poetry shell` to modify the prompt (PS1 in some shells) to show the current environment. See #1642.

However, this conflicts with prompts that already show the environment, causing text duplication.
<img width="443" alt="poetry" src="https://user-images.githubusercontent.com/6157758/72076531-a6ff9280-32c3-11ea-8496-9f543ca7a2be.png">

A configuration option to prevent the prompt from being modified would resolve this.

### My configuration
OS: macOS Catalina 10.15.1
Shell: Fish 3.0.2
Poetry: 1.0.0

**Comment by MooseV2** [comment]
Ah, upon further research, I have discovered the environment variable, `VIRTUAL_ENV_DISABLE_PROMPT`.

Because Poetry uses Virtualenv internally, exporting this with `export VIRTUAL_ENV_DISABLE_PROMPT=1` (or in Fish, `set -x VIRTUAL_ENV_DISABLE_PROMPT 1`) appears to resolve this issue.

Perhaps this is a documentation issue instead? People who are using Poetry as a turnkey solution shouldn't have to dig into the internal workings (ie virtualenv).

Otherwise, a config variable could set `VIRTUAL_ENV_DISABLE_PROMPT` before spawning the virtualenv when `poetry shell` is issued.

**Comment by grisaitis** [comment]
I second this. 

I would also like a config variable to prevent the `PS1` modification. Or at least document it. 

In my situation, I use [bash-it](https://github.com/Bash-it/bash-it) to have a cute shell prompt. `poetry shell` totally vanquishes this.

Where would this setting be (@MooseV2)? in the `[tools.poetry]` section of `pyproject.toml`? `[tools.poetry.env]`?

**Comment by grisaitis** [comment]
Sorry, I'm an idiot - I just needed to move bash configurations from `.bash_profile` to `.bashrc`. Dotfile drama. `poetry shell` creates a new bash shell, but it's not a "login" shell. So `.bashrc` is sourced but `.bash_profile` is not. This is unlike a new terminal window on a Mac (which _is_ a login shell).

**Comment by grisaitis** [comment]
My issues aside, @MooseV2 recommendations still make sense. Some documentation would help, at least.

**Comment by 0trenixjetix** [comment]
I have this problem, i use powerline_shell and i am getting two times the virtualenv name.
Please fish. :)

**Comment by neersighted** [comment]
Poetry just uses upstream virtualenv -- as such, this is a docs issue.

**Comment by matiaslagoevia** [comment]
Hello, I'd like to tackle this issue if possible. If so, could I have some guidance of the updates needed for the docs? I'd be happy to groom the issue further with assistance, thanks!

**Comment by tamakiii** [comment]
Setting `virtualenv.prompt` config worked for me.
```sh
python3 -m poetry config --list
python3 -m poetry config --local --list
python3 -m poetry config virtualenvs.prompt
```
```sh
python3 -m poetry config --local virtualenvs.promptpython3 -m poetry config --local virtualenvs.prompt null
```
https://gist.github.com/tamakiii/6946265e53872882d2114b1a50bb828a
