### ISSUE TITLE
`poetry new` to support --dependency & --dev-dependency

### ISSUE THREAD

**Issue by juhoautio** [python-poetry/poetry#1854]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

Could these options be added to the `poetry new` command (non-interactive):

- `--dependency`: Package to require with a version constraint
- `--dev-dependency`: Development packages

The `poetry init` command (interactive) already supports these flags.

Both with `multiple=True`.

----

Maybe also these (`init` supports but `new` doesn't):
- `--description`: Description of the package.
- `--author`: Author of the package.

----

I can implement & make a PR if this makes sense to you.

**Comment by Secrus** [comment]
That could be something to be considered for future release.

**Comment by juhoautio** [comment]
Are you open to reviewing a pull request that implements this?

**Comment by Secrus** [comment]
> Are you open to reviewing a pull request that implements this?

If you are willing to make one, sure. However, I can't guarantee that it will be part of the next release.

**Comment by juhoautio** [comment]
@Secrus I'm hoping to get feedback on my PR, I wonder if you could help with that?

I tried to tag @neersighted, but no response so far: https://github.com/python-poetry/poetry/pull/5710#issuecomment-1152708230.

Thanks!

**Comment by finswimmer** [comment]
I think we should make `poetry new` an extension of `poetry init`. This is why I'm closing this in favor of #2563.
