### ISSUE TITLE
Poetry v1 poetry install fails when a dependency setup.py "author" is not of type array

### ISSUE THREAD

**Issue by pk8189** [python-poetry/poetry#1861]
```
poetry install
Updating dependencies
Resolving dependencies... (6.7s)

[RuntimeError]
The Poetry configuration is invalid:
  - [authors] 'Terry Peng (pengtaoo@gmail.com), Mikhail Korobov (kmike84@gmail.com)' is not of type 'array'
```

One of my dependencies is on python-crfsuite (which I believe is the package that is raising this error) https://github.com/scrapinghub/python-crfsuite/blob/8eff0272f1a5bd24a0768220e64e05dfff67a793/setup.py#L51

I believe this error should only be raised when the poetry user's project isn't formatted properly

**Comment by ibegleris** [comment]
This problem persists in 1.0.9

**Comment by finswimmer** [comment]
Hello @ibegleris,

can you please provide more detail about your case? How can I reproduce it?

fin swimmer

**Comment by pk8189** [comment]
Hi all, sorry for incorrectly flagging this, it was actually an issue with an internal forked version of a dependency @ibegleris turns out you work at the same place as me :)
