### ISSUE TITLE
Allow the creation of new environments without pip

### ISSUE THREAD

**Issue by mmartinortiz** [python-poetry/poetry#1863]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

This feature request is based on problems I had using poetry. In my case, I have several Python 3 interpreters installed on the system (Ubuntu 18.04) via PPA. There is only one `pip3` (attached to Pytohn 3.6)

Poetry fails if I want to create an environment with Python 3.5 or 3.7 (the other two interpreters) because `pip3` is not installed for them. I can install `pip` for them with `python3.5 -m pip install pip`, but it is a local install, and Poetry will fail again when creating the environment, because `pip` for Python 3.5 is not available globally.

As a workaround, or in case `ensurepip` fails, my feature request ask for the `--without-pip` [parameter](https://docs.python.org/3/library/venv.html#creating-virtual-environments) of the `venv` module, allowing for a correct creation of the environment, and after that, install `pip` with the new environment interpreter by means of `curl https://bootstrap.pypa.io/get-pip.py | python`

**Comment by finswimmer** [comment]
Hello @mmartinortiz,

the current version of poetry now uses `virtualenv` to create the venv. So your problem should be fixed.

fin swimmer
