### ISSUE TITLE
self update doesn't respect $POETRY_HOME

### ISSUE THREAD

**Issue by iamkroot** [python-poetry/poetry#1872]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Manjaro latest
- **Poetry version**: 1.0.2

## Issue
The `poetry self update` command reports that `Poetry was not installed with the recommended installer...` when trying to run it in an environment where poetry was *not* installed to `~/.poetry`, even when the `$POETRY_HOME` var is set and pointing to the actual install location. 

Culprit line in source code can be found [here](https://github.com/python-poetry/poetry/blob/636ce8b0eba7dfa390b3fd961d1b9fb533d5d033/poetry/console/commands/self/update.py#L44). Should probably be extended to first check for `POETRY_HOME` and then fallback to `~/.poetry`.

**Comment by finswimmer** [comment]
Closed via https://github.com/python-poetry/poetry/commit/5e70eb8d1843c03d8e4bd812b4b18ba0ec52be4a
