### ISSUE TITLE
`--help` option doesn't work for some sub commands

### ISSUE THREAD

**Issue by tkossak** [python-poetry/poetry#1873]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate. (This issue https://github.com/python-poetry/poetry/issues/1161 concerns `help` sub command, while mine concerns `--help` option)
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Linux Manjaro 18.1.5 XFCE
- **Poetry version**: 1.0.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/792b8bb8f0ec0b8950034ab5db82a60a

## Issue
`poetry add --help` should display help for command `add`, instead it tries to install package. Help is displayed only after providing any package name:

```
$ poetry add --help
Not enough arguments (missing: "name").

$ poetry add requests --help                                                                                                           1 
USAGE
  poetry add [-D] [-E <...>] [--optional] [--python <...>] [--platform <...>] [--allow-prereleases] [--dry-run] <name1> ... [<nameN>]

ARGUMENTS
  <name>                 The packages to add.
(...)
```

This is the case also for some other sub commands like `poetry new --help`, `poetry remove --help`, etc. For `poetry run --help` you get:

```
$ poetry run --help
Creating virtualenv test369-GUmPI0iX-py3.6 in /home/kossak/.cache/pypoetry/virtualenvs

[FileNotFoundError]
[Errno 2] No such file or directory
```

**Comment by finswimmer** [comment]
Hello @tkossak ,

this is already reported in https://github.com/python-poetry/poetry/issues/1625

Thanks for confirming :smiley: 

fin swimmer
