### ISSUE TITLE
poetry install fails on pre-release

### ISSUE THREAD

**Issue by hixus** [python-poetry/poetry#1876]
- [ x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [ x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Debian 10
- **Poetry version**: 1.0.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/hixus/6e5c15869afed95e54b5e689c27b33b8

## Issue
When I run `poetry add cloudml-hypertune` everything works but when ci-machine runs `poetry install` it fails with "Because model-xxx depends on cloudml-hypertune (^0.1.0-alpha.6) which doesn't match any versions, version solving failed."

Running `poetry update cloudml-hypertune` also installs latest pre-release version (0.1.0.dev6) correctly

**Comment by hixus** [comment]
Workaround in ci is to run `
poetry remove cloudml-hypertune &&
poetry install &&
poetry add --allow-prereleases cloudml-hypertune`

**Comment by hixus** [comment]
Actually better solution is to use just `{version = "*", allow-prereleases = true}` Not sure if this is a issue with poetry old the cloudml-hypertune package. Poetry says `Installing cloudml-hypertune (0.1.0.dev6)` but in the pyproject.toml we get `cloudml-hypertune = {version = "^0.1.0.dev6", allow-prereleases = true}`

**Comment by abn** [comment]
Your linked `pyproject.toml` file has `^0.1.0-alpha.6` which is a nonexistant version. So, I'd imagine your CI tries to use the pyproject file to try find the version and fails.

**Comment by mkniewallner** [comment]
Closing, since it's a quite old issue that is most likely obsolete, and we didn't hear back from the author.

If you still reproduce the issue with recent versions of Poetry, feel free to reopen the issue.
