### ISSUE TITLE
poetry bootstrap is unable to fallback on `python3` executable

### ISSUE THREAD

**Issue by jonapich** [python-poetry/poetry#1877]
The `get-poetry.py` script relies on `python` being available in the shell.

It should be a little more flexible, such as allowing `python3` and supporting [PEP 397](https://www.python.org/dev/peps/pep-0397/).

**Comment by finswimmer** [comment]
The `get-poetry.py` script is now deprecated and will be replaced by `installed-poetry.py`. See: https://python-poetry.org/blog/announcing-poetry-1.2.0a1/#deprecation-of-the-get-poetrypy-script
