### ISSUE TITLE
Document docker poetry best practices

### ISSUE THREAD

**Issue by mxab** [python-poetry/poetry#1879]
- [x ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

There are several discussions on how to build your final application for a docker image

- https://github.com/python-poetry/poetry/issues/1178
- https://stackoverflow.com/questions/53835198/integrating-python-poetry-with-docker

Would be great if the poetry team could provide a how to poetry with docker documentation

**Comment by bufke** [comment]
I would add #1227 to this as well.

**Comment by fralik** [comment]
I recently described usage of Poetry with [private repos](https://github.com/fralik/poetry-with-private-repos).

**Comment by michael0liver** [comment]
I have been playing around with multi-stage builds and came up with this example:

```dockerfile
# `python-base` sets up all our shared environment variables
FROM python:3.8.1-slim as python-base

    # python
ENV PYTHONUNBUFFERED=1 \
    # prevents python creating .pyc files
    PYTHONDONTWRITEBYTECODE=1 \
    \
    # pip
    PIP_NO_CACHE_DIR=off \
    PIP_DISABLE_PIP_VERSION_CHECK=on \
    PIP_DEFAULT_TIMEOUT=100 \
    \
    # poetry
    # https://python-poetry.org/docs/configuration/#using-environment-variables
    POETRY_VERSION=1.0.3 \
    # make poetry install to this location
    POETRY_HOME="/opt/poetry" \
    # make poetry create the virtual environment in the project's root
    # it gets named `.venv`
    POETRY_VIRTUALENVS_IN_PROJECT=true \
    # do not ask any interactive question
    POETRY_NO_INTERACTION=1 \
    \
    # paths
    # this is where our requirements + virtual environment will live
    PYSETUP_PATH="/opt/pysetup" \
    VENV_PATH="/opt/pysetup/.venv"


# prepend poetry and venv to path
ENV PATH="$POETRY_HOME/bin:$VENV_PATH/bin:$PATH"


# `builder-base` stage is used to build deps + create our virtual environment
FROM python-base as builder-base
RUN apt-get update \
    && apt-get install --no-install-recommends -y \
        # deps for installing poetry
        curl \
        # deps for building python deps
        build-essential

# install poetry - respects $POETRY_VERSION & $POETRY_HOME
RUN curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python

# copy project requirement files here to ensure they will be cached.
WORKDIR $PYSETUP_PATH
COPY poetry.lock pyproject.toml ./

# install runtime deps - uses $POETRY_VIRTUALENVS_IN_PROJECT internally
RUN poetry install --no-dev


# `development` image is used during development / testing
FROM python-base as development
ENV FASTAPI_ENV=development
WORKDIR $PYSETUP_PATH

# copy in our built poetry + venv
COPY --from=builder-base $POETRY_HOME $POETRY_HOME
COPY --from=builder-base $PYSETUP_PATH $PYSETUP_PATH

# quicker install as runtime deps are already installed
RUN poetry install

# will become mountpoint of our code
WORKDIR /app

EXPOSE 8000
CMD ["uvicorn", "--reload", "main:app"]


# `production` image used for runtime
FROM python-base as production
ENV FASTAPI_ENV=production
COPY --from=builder-base $PYSETUP_PATH $PYSETUP_PATH
COPY ./app /app/
WORKDIR /app
CMD ["gunicorn", "-k", "uvicorn.workers.UvicornWorker", "main:app"]
```

**Comment by mxab** [comment]
@michael0liver do you know if there is the requirement for the python:3.8.1-slim in the production step? Since you copy the .venv isn't do we have two python runtimes installed?

I know in the Dockerfile of  python:3.8.1-slim happens a bit more then installing python but still isn't there some redundancy when using the venv? (I don't know that much about venvs)

**Comment by michael0liver** [comment]
@mxab Yes you do.  Virtual environments are really just an isolated directory where you can install third party packages without affecting the global site-packages.  They contain symlinks to the Python executable's installed on your system.

There are the `--symlinks` & `--copies` optional arguments [documented here](https://docs.python.org/3/library/venv.html) which could change the default behavior but I have never messed with these. 
 
I created a [python-poetry-docker-example](https://github.com/michael0liver/python-poetry-docker-example) repo with a more concrete example than above.  It can still be improved but maybe it could serve as a reference.

**Comment by n8sty** [comment]
The pattern I've used when building Docker images with Poetry is to use it's `export` functionality, build wheels based on the `requirements.txt` file, and then `COPY` or make those wheels available to a final, production ready image. Happy to share an example if that would be useful.

**Comment by mxab** [comment]
@n8sty I read about this way also in the stackoverflow thread.
Last time I tried it I had problems, since I had path dependencies, not sure if this is resolved yet.

Would be cool to see if we had use cases demonstrate how to handle this also (also git and private repos)

**Comment by arlyon** [comment]
> The pattern I've used when building Docker images with Poetry is to use it's `export` functionality, build wheels based on the `requirements.txt` file, and then `COPY` or make those wheels available to a final, production ready image. Happy to share an example if that would be useful.

it should be noted that this doesn't work with dependencies on non-hashable projects (ie. github repos) which is a pain if you, for example, are waiting for patches to land upstream. will update with any workarounds I find

**Comment by dvf** [comment]
What a fantastic Dockerfile. Thanks @michael0liver :champagne:

**Comment by adamwojt** [comment]
@michael0liver What a great build. It really helped me with my URL shortener project https://github.com/adamwojt/ur_l
I expanded upon it and used docker-compose to utilize multi-stage. Anyone feel free to use it, it's MIT too.

**Comment by tetienne** [comment]
@michael0liver Thx for your great example. I use it for my VS code dev container. 
I have just one trouble. What do you suggest when we set up some private pypy repositories in pyproject.toml? We have to pass two env variables at build time: POETRY_HTTP_BASIC_XXX_USERNAME and POETRY_HTTP_BASIC_XXX_PASSWORD, and docker suggest to not use ARG for confidential information.

**Comment by michael0liver** [comment]
> @michael0liver Thx for your great example. I use it for my VS code dev container.
> I have just one trouble. What do you suggest when we set up some private pypy repositories in pyproject.toml? We have to pass two env variables at build time: POETRY_HTTP_BASIC_XXX_USERNAME and POETRY_HTTP_BASIC_XXX_PASSWORD, and docker suggest to not use ARG for confidential information.

You should use docker [--build-arg](https://docs.docker.com/engine/reference/commandline/build/#set-build-time-variables---build-arg). These variables only exist within the build stage and will not persist in the built image. Expose these variables inside your CI pipeline (for example as secrets inside a GitHub actions workflow).

**Comment by mxab** [comment]
In case someone uses the buildkit feature of docker you can also use the secret mount

https://docs.docker.com/develop/develop-images/build_enhancements/#new-docker-build-secret-information

You also need to put the `# syntax` block
```Dockerfile
# syntax=docker/dockerfile:experimental
FROM python:3.6.9-slim-buster as build
....
# then specify a secret id
RUN --mount=type=secret,id=poetry_auth,dst=/root/.config/pypoetry/auth.toml poetry install -n --no-dev
```

```bash
# mount in the secret file
docker build --secret id=poetry_auth,src=$HOME/.config/pypoetry/auth.toml
```

**Comment by mxab** [comment]
On other issue we are facing in our case we use sqlalchemy and alembic.
Although alembic says you should install it in the same venv as your project, in my opinion these are two different applications. Therefore my docker application should have internally two seperated venvs, one for alembics migration run and one for the application itself.

Does anyone else do it like this?

**Comment by n8sty** [comment]
I think that's a bit of a weird setup. Seems like it'd be conceptually simpler if you had two separate containers, one for running migrations and one for running the application itself. I don't there's anything necessarily wrong with this, but unless there's a really important reason (maybe limiting the ability to use additional functional during migrations?) to have multiple virtual environments in a container, I'd think it best to separate them into dedicated containers or combine them into a single environment.

Since this discussion is within the Poetry project, I don't think it supports this particular workflow particularly well either. I can imagine it working with a bunch of different optional dependency groups, and I've seen some issues relating to adding support for more detailed grouping of dependencies, but as of right now, I don't think the current feature set supports this in a particular seamless way.

**Comment by mxab** [comment]
I also thought about two seperated containers for that case, but depending on the container scheduler you use it is something tricky to ensure the correct starting and waiting for order.
The idea with the two venvs was to avoid potential but unnecessary depedendency conflicts

**Comment by shughes-uk** [comment]
Is there any way to just have poetry dump out the wheels of the packages that would be installed?

For using just pip to create a multistage build I usually do `pip wheel --wheel-dir /pkgs -r requirements.txt` then copy `/pkgs` into the next layer and `pip install --no-index --find-links /pkg /pkg/* && rm -rf /pkg`

This wheel method works for poetry projects that do not have relative directorys in their dependencies but breaks for that as `pip wheel /some-package` seems to set the CWD to be a temporary directory while creating the wheels, which messes things up.

@michael0liver's solution looks great but is very verbose compared to the pip only solution.

**Comment by abn** [comment]
@shughes-uk this came up at https://github.com/python-poetry/poetry/issues/2873#issuecomment-684007824

**Comment by tau-lex** [comment]
It can be useful:
You can use this a small Docker layer if you just need to install dependencies in the system python.
```
RUN poetry env use system && \
    poetry export --without-hashes -f requirements.txt > r.txt && \
    pip install -r r.txt
```
* A text file is used to work around the error when the stdout stream is closed before pip reads it.

**Comment by bneijt** [comment]
Example docker file using pip is:
```
FROM python:3.8-slim

WORKDIR /project

RUN pip install poetry==1.1.0rc1

COPY pyproject.toml poetry.lock /project/

RUN poetry export --without-hashes -f requirements.txt > reqs.txt \
    && pip install -r reqs.txt \
    && rm reqs.txt

#Requires poetry build before docker build
COPY dist /project/dist

RUN pip install --no-deps dist/*.whl

CMD ["python", "-m", "your-module-or-executable"]
```

This is nice because quick changing `your-module` is in another layer than your dependencies, resulting in quick rebuilds by re-using the earlier layer. However, there is still an open issue making this impossible to use without grepping out windows dependencies ( #2662 )

The cleanest way I'm currently fan of is a hybrid approach: poetry for the dependencies, pip for the final wheel.
```
FROM python:3.8-slim

WORKDIR /project

RUN pip install poetry==1.1.0rc1

COPY pyproject.toml poetry.lock /project/
RUN POETRY_VIRTUALENVS_IN_PROJECT=true poetry install --no-dev --no-root

COPY dist /project/dist

# hadolint ignore=DL3013
RUN /project/.venv/bin/pip install --no-deps dist/*.whl \
    && rm -rf dist

CMD ["/project/.venv/bin/python", "-m", "your_module"]
```
It could be slimmed down a bit by using a multi-stage build and only keeping your final /project in the last step. I leave that as a exercise to the reader ;)

**Comment by mafeko** [comment]
Thanks @michael0liver for this blueprint.
Running CICD (jenkins) this container is launched with a fixed `uid:gid`.

Running as another user I also faced some issues regarding the `poetry-cache` which I fixed by setting it to a sub-directory of my POETRY_HOME.
```
ENV
# make poetry cache into the subfolder of POETRY_HOME
POETRY_CACHE_DIR="/opt/poetry/.cache" \
# POETRY_CACHE_DIR is not respected currently see https://github.com/python-poetry/poetry/issues/2445#issuecomment-670829271
XDG_CACHE_HOME="/opt/poetry/.cache" \

# somewhere further down I gave all users rw access in the container
RUN chmod 777 -R $POETRY_HOME
```

**Comment by anentropic** [comment]
@michael0liver thanks for the example

I have a question, why do you set `PYTHONDONTWRITEBYTECODE=1`?

Is that just so that poetry etc don't create them while installing deps in the dockerfile, i.e. to have cleaner layers?  Wouldn't you want to have compiled bytecode when you run the app in the `production` stage though?

**Comment by anentropic** [comment]
I'm trying to understand the merits of the various approaches used here

@bneijt what is the point of doing:
```Dockerfile
RUN POETRY_VIRTUALENVS_IN_PROJECT=true poetry install --no-dev --no-root

COPY dist /project/dist

# hadolint ignore=DL3013
RUN /project/.venv/bin/pip install --no-deps dist/*.whl \
    && rm -rf dist
```
instead of just:
```Dockerfile
RUN POETRY_VIRTUALENVS_IN_PROJECT=true poetry install --no-dev
```
?

Is it just that you expect `dist/` to already exist in your dev environment, or there is some other benefit?

**Comment by anentropic** [comment]
Hmm, I guess you avoid having to `COPY` all your .py sources into the Docker image and build it there

Just using the pre-existing wheel artefact is cleaner - is that it?

**Comment by michael0liver** [comment]
> @michael0liver thanks for the example
> 
> I have a question, why do you set `PYTHONDONTWRITEBYTECODE=1`?
> 
> Is that just so that poetry etc don't create them while installing deps in the dockerfile, i.e. to have cleaner layers? Wouldn't you want to have compiled bytecode when you run the app in the `production` stage though?
> 
> Or... the `ENV` setting doesn't carry across into the later stages?

I seen quite a few tutorials where they used that option. Supposedly it reduces image size and depending on the use case it shouldn't impact performance as the .pyc files are generated at import time. So for a long running application it _should_ be fine.


> I'm trying to understand the merits of the various approaches used here
> 
> @bneijt what is the point of doing:
> 
> ```dockerfile
> RUN POETRY_VIRTUALENVS_IN_PROJECT=true poetry install --no-dev --no-root
> 
> COPY dist /project/dist
> 
> # hadolint ignore=DL3013
> RUN /project/.venv/bin/pip install --no-deps dist/*.whl \
>     && rm -rf dist
> ```
> 
> instead of just:
> 
> ```dockerfile
> RUN POETRY_VIRTUALENVS_IN_PROJECT=true poetry install --no-dev
> ```
> 
> ?
> 
> Is it just that you expect `dist/` to already exist in your dev environment, or there is some other benefit?


The `--no-root` option won't install the project package which is useful when you want to use the docker caching effectively. The rationale is that your code will change quite often whereas dependencies don't change as frequently. Combining these steps in a single `RUN` means that when our application code changes we will invalidate the cache and have to reinstall all of our third party libraries again.

**Comment by anentropic** [comment]
> @anentropic
> 
> > @michael0liver thanks for the example
> > I have a question, why do you set `PYTHONDONTWRITEBYTECODE=1`?
> > Is that just so that poetry etc don't create them while installing deps in the dockerfile, i.e. to have cleaner layers? Wouldn't you want to have compiled bytecode when you run the app in the `production` stage though?
> > Or... the `ENV` setting doesn't carry across into the later stages?
> 
> I seen quite a few tutorials where they used that option. Supposedly it reduces image size and depending on the use case it shouldn't impact performance as the .pyc files are generated at import time. So for a long running application it _should_ be fine.

Hmm, the docs seem to say that it prevents generating .pyc files at import time (not just when installing packages)
https://docs.python.org/3/using/cmdline.html#envvar-PYTHONDONTWRITEBYTECODE

**Comment by michael0liver** [comment]
@anentropic

> Hmm, the docs seem to say that it prevents generating .pyc files at import time (not just when installing packages)
> https://docs.python.org/3/using/cmdline.html#envvar-PYTHONDONTWRITEBYTECODE

It still generates the .pyc files but it won't write them to disk. Python will generate them on the fly every time you start your application.

A few places where I have seen it:
* https://sourcery.ai/blog/python-docker/
* https://testdriven.io/blog/dockerizing-django-with-postgres-gunicorn-and-nginx/
