### ISSUE TITLE
Failure to install from source flit project

### ISSUE THREAD

**Issue by aviramha** [python-poetry/poetry#1881]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: MacOS 10.7
- **Poetry version**: 1.0.2

## Issue
When specifying git repository to build from, if the source doesn't contain setup.py (for example, if it has pypoetry.toml of another format, like flit) poetry fails to find version and raises RuntimeError.
I think the solution would be supporting retrieval of version from the __version__ variable that flit is standardised to have.

**Comment by aviramha** [comment]
I don't mind sending a PR for adding support for __version__ var obtaining. Just want to make sure it's OK for the maintainers.

**Comment by TheLazzziest** [comment]
I faced with almost the same type of error, except I catched ValueError from poetry-core as it failed to resolve the flit format.
Can poetry support flit format somehow, I mean theoretically, or it's out of scope of this library at all ?

**Comment by finswimmer** [comment]
In the meantime this should work now.
