### ISSUE TITLE
Conditional dependencies results in exceeeding maximum recursion depth (for manimlib with pycairo)

### ISSUE THREAD

**Issue by JulianStier** [python-poetry/poetry#1885]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate. It might be related to
  - https://github.com/python-poetry/poetry/issues/1222
  - https://github.com/python-poetry/poetry/issues/1238
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 18.04.3 LTS // Linux 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- **Poetry version**: 1.0.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/JulianStier/e8b041396b26bdc3b542530404e28277

## Issue
Trying to install manimlib:
``poetry add manimlib``

Error:
> [RecursionError]
maximum recursion depth exceeded while calling a Python object

Executed with *-vv*:
>    0: Duplicate dependencies for pycairo
   0: Different requirements found for pycairo (1.17.1) and pycairo (>=1.18.0).

A look into *https://github.com/3b1b/manim/blob/master/requirements.txt*:
> pycairo==1.17.1; sys_platform == 'linux'
pycairo>=1.18.1; sys_platform == 'win32'

Apparently poetry does not recognize conditionally defined requirements based on "sys_platform".

**Comment by lvkswrks** [comment]
Probably related / same as #992

**Comment by abn** [comment]
Fixed in `1.1.0b2`. Requires regeneration of lock file. Note that new lock file is not compatible with older versions of `poetry`.
