### ISSUE TITLE
Unexpected Python version used

### ISSUE THREAD

**Issue by pikeas** [python-poetry/poetry#1888]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS 10.15.2
- **Poetry version**: 1.0.2

## Issue
```
$ poetry new foo
$ poetry debug
[...]
Virtualenv
Python:         3.8.1
Implementation: CPython
Path:           <user>/Library/Caches/pypoetry/virtualenvs/foo-y-IvgPhK-py3.8
Valid:          True

System
Platform: darwin
OS:       posix
Python:   <user>/.asdf/installs/python/3.8.1

$ ls -l ~/Library/Caches/pypoetry/virtualenvs/foo-y-IvgPhK-py3.8/bin/python
lrwxr-xr-x  1 <user>  staff  49 Jan 14 13:46 <user>/Library/Caches/pypoetry/virtualenvs/foo-y-IvgPhK-py3.8/bin/python -> <user>/.local/pipx/venvs/poetry/bin/python
```

I manage Python versions with [asdf](https://github.com/asdf-vm/asdf) and Poetry with pipx. I expected Poetry to symlink my default Python (the one from asdf), instead it used the one from poetry's environment.

There have been some other issues regarding how Poetry chooses which Python to use. The above behavior seems either incorrect, in which case this is a bug, or counterintuitive, in which case perhaps the docs  for `poetry new` could describe how the Python executable is chosen?

**Comment by finswimmer** [comment]
Hello @pikeas,

poetry takes the python version that is available when running `python` in the environment it is in. That's in behavior I would expect and that's the reason why the recommended installation way is `curl`. With `pip` or `pipx` poetry will always be in it's own environment and will catch up the python that is available there.

fin swimmer

**Comment by pikeas** [comment]
The issue seems to go a bit deeper than that.

With Poetry installed via pipx into Python 3.8.1, a Poetry-managed project running under Python 2.7 displays a warning on every invocation.

```pyproject.toml
[tool.poetry]
name = "foo"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^2.7"

[tool.poetry.dev-dependencies]
pylint = "1.9.5"
yapf = "^0.29.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```

```
$ poetry debug

Poetry
Version: 1.0.2
Python:  3.8.1

Virtualenv
Python:         3.8.1
Implementation: CPython
Path:           NA

System
Platform: darwin
OS:       posix
Python:   <user>/.local/pipx/venvs/poetry
$ poetry shell
The currently activated Python version 3.8.1 is not supported by the project (^2.7).
Trying to find and use a compatible version.
Using python2 (2.7.17)
Spawning shell within <user>/Library/Caches/pypoetry/virtualenvs/foo-PxKbcfXG-py2.7
```

The virtualenv appears to be functional, the warning doesn't seem accurate, and the debug output for the virtualenv is incorrect.

It looks like Poetry is running its commands in the context of its Python, rather than in the context of the project's virtualenv Python.

**Comment by finswimmer** [comment]
Setting `virtualenvs.prefer-active-python` to `true` is the correct way now to solve this. See https://python-poetry.org/docs/configuration/#virtualenvsprefer-active-python-experimental
