### ISSUE TITLE
How should the file structure be?

### ISSUE THREAD

**Issue by cubetastic33** [python-poetry/poetry#1891]
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

I feel it extremely hard to understand where I'm supposed to write my code when using poetry. I ran `poetry new <name>`, and it came up with this file structure. Unlike rust's cargo, which has extensive documentation and it's very easy to understand how you're supposed to structure your code, I don't understand at all what any of the files other than `pyproject.toml` and `poetry.lock` are supposed to do. The documentation seems to only talk about `pyproject.toml`, calling it the most important file, seemingly completely ignoring all of the other files. Why is a `test` directory created? I write my tests there, right? How am I supposed to mark the tests and run them? Does poetry offer tools for that? Why are there `__init__.py` files? [This](https://docs.python.org/3/reference/import.html#regular-packages) seems to say that using `__init__.py` files is the old pre-python 3.3 way and now you're supposed to do something called namespace packages, which again I don't understand at all. So where am I even supposed to write my code?

I understand that most of what I complained about might be basic python knowledge, but I tried quite a bit to figure this out and I couldn't. I can't find tutorials explaining this stuff, and I really need help now. I tried asking people, but they don't know. Is all this actually in the documentation and I'm just an idiot and couldn't find it?

**Comment by finswimmer** [comment]
Hello @cubetastic33 ,

thanks for your interested on poetry. The issue tracker is not the correct place for learning about how packages work in python. Please use other sources, e.g. [RealPython](https://realpython.com/python-modules-packages/).

fin swimmer
