### ISSUE TITLE
poetry export: missing --trusted-host argument for non-HTTPS repos

### ISSUE THREAD

**Issue by 1somorphism** [python-poetry/poetry#1894]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 16.04.2 TLS and Windows 10
- **Poetry version**: 1.0.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/1somorphism/f3a1ced4e6507383b5f16daffcb7a140

## Issue
Ideally line 1 of the output of ```poetry export -f requirements.txt``` for the file above should be

```--extra-index-url http://10.0.0.0:8080/repository/pypi-hosted/simple --trusted-host 10.0.0.0```

**Comment by 0xADD1E** [comment]
I've just worked around this by just writing out the trusted host line first 
```
echo --trusted-host 10.0.0.0 > requirements.txt
poetry export -f requirements.txt >> requirements.txt
```

But I also agree that this is somewhat unexpected behaviour.

My intuition for how this would work was that there would be an option in `tool.poetry.source` that would allow for this (and possibly also turn off the somewhat annoying "insecure host" notice when installing packages)

**Comment by gusbemacbe** [comment]
@1somorphism, @0xADD1E, @edwardgeorge, @bmispelon, @blueyed, @estyxx, @abn, @finswimmer 

Please check my discussion topic #4869.

**Comment by japita-se** [comment]
this very useful issue has been merged?
