### ISSUE TITLE
CLI Short names are broken

### ISSUE THREAD

**Issue by jonapich** [python-poetry/poetry#1898]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

**poetry 1.0.2**

```
    $ poetry ver
    The command "ver" is not defined.

    Did you mean this?
        version

    $ poetry up
    The command "up" is not defined.

    Did you mean this?
        update
```

It looks like the partial-command matching was broken at some point.

Ref: https://python-poetry.org/docs/cli/#commands mentions:

> As Poetry uses cleo you can call commands by short name if it's not ambiguous.

**Comment by jonapich** [comment]
HOWEVER, I kind of agree with click's author here:

https://click.palletsprojects.com/en/7.x/why/#why-no-auto-correction

> The reason for this is that it’s a liability for backwards compatibility. If people start relying on automatically modified parameters and someone adds a new parameter in the future, the script might stop working.

I can imagine someone writing "poetry up" in his jenkins files, and then have it break because someone adds an "upload" command creating an ambiguity. In most cases this is easy to address, but if the script would be, say, some sort of server bootstrap in production, it could even be difficult to identify.

We can't rely on all python developers to have good practices of version-pinning and testing/CI/CD all the way from dev to production (especially given the historical state of python packaging/dependency management in general; thanks for fixing this by the way :wink:). Since poetry is going to be at the core of machine setups, I believe being defensive on CLI commands can only be a good thing.

**Comment by finswimmer** [comment]
IIRC the partial-matching of commands was removed by cleo some day.
