### ISSUE TITLE
generated `setup.py` after `poetry build` does not include source information

### ISSUE THREAD

**Issue by pgilad** [python-poetry/poetry#1901]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: OSX Catalina
- **Poetry version**: 1.0.2

## Issue

When creating a `pyproject.toml` with a non-standard source `[source]`, and then running `poetry build` the generated `setup.py` does not include mention of the extra source (Probably using `dependency_links` section).

This results that when installing the artifact (Using pipx for example) the source artifactory isn't being used and so installation fails due to missing package.

I've tried both `source` type combinations:
` default = true` and `secondary = true` (and specifying the `source` manually in the packages). Both methods fail to address this.

A possible solution is to override pip global artifactory (or install using `--index-url`) but this is a weird workaround.

**Comment by sdispater** [comment]
As far as I know the `setup.py` file does not support specifying private indices in dependency specifications. That's why it does not appear in the `setup.py` generated by Poetry.

And since the `setup.py` is bound to become obsolete with PEP 518, it will no longer be generated in future versions of Poetry to avoid this kind of issues.

**Comment by pgilad** [comment]
@sdispater Thanks for the response. Is there anything I can do in order to preserve installing deps from private indices? It works perfectly when using `poetry install` but once I create an artifact `poetry build` then when I install it (for example using `pipx install`) it no longer maintains the notion of the private indices..

🙏

**Comment by mkniewallner** [comment]
Since the generation of `setup.py` during `poetry build` will be removed eventually, this is not something that is planned.
