### ISSUE TITLE
Downgrade interpreter version

### ISSUE THREAD

**Issue by IamGianluca** [python-poetry/poetry#1903]
I was wondering if there was a way, after a project was created, to downgrade the version of the interpreter.

I've started a project setting python `^3.8` but some dependencies I need to use I suspect are only supporting Python up to 3.7. I've tried to change edit in the `pyproject.toml` file the version for Python to `^3.6` and then going a `poetry add <mynewdependency` but that keep complaining that 

```
[ValueError]
Could not find a matching version of package <mynewdependency>
```

**Comment by finswimmer** [comment]
Hello @IamGianluca,

you have to remove the virtualenv and recreate it by making sure the correct interpreter is available. Because once a virtualenv is created the interpreter within it is fixed.

fin swimmer
