### ISSUE TITLE
Install package from Version Control System (git) where  setup.py is in subdirectory

### ISSUE THREAD

**Issue by mohelm** [python-poetry/poetry#1915]
- [x ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [ x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS Catalina - Version 10.15.2
- **Poetry version**: 1.02.
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**:  https://gist.github.com/mohelm/5c6f36913338f81a42d02a31e8ece35c

## Issue
I a m trying to execute a command like this:

```
 poetry add  "git+ssh://git@gitlab.XXX.io:XX/XX.git#egg=pkg&subdirectory=app"
```

That is, I am seek to install from a repo on Gitlab where the `setup.py` is in a subdirectory app. I got the above command from  [here on stackoverflow](https://stackoverflow.com/questions/13566200/how-can-i-install-from-a-git-subdirectory-with-pip), and it works when I do `poetry run pip install ...`.

However when doing `poetry add` as above, I am getting:

```
[CalledProcessError]
Command '['git', '--git-dir', '/var/folders/gd/1lpddhjd5fq2zh0ktw4q26z5xm6fsn/T/pypoetry-git-rsdslo4r2dqx/.git', '--work-tree', '/var/folders/gd/1lpddhjd5fq2zh0ktw4q26z5xm6fsn/T/pypoetry-git-rsdslo4r2dqx', 'checkout', 'egg=pkg&subdirectory=app']' returned non-zero exit status 1.
```

Is this an issue on my or on Poetry's side? 

Many thanks.

**Comment by finswimmer** [comment]
Hello @mohelm,

installing packages in a subfolder  of git is currently not supported by `poetry`. There is already a feature request for it (#755) and I started to work on that (#1822).

I close this as a duplicate.

fin swimmer
