### ISSUE TITLE
poetry tries to reinstall from git when using annotated tags as references

### ISSUE THREAD

**Issue by jrmlhermitte** [python-poetry/poetry#1916]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Debian Buster
- **Poetry version**: 1.0.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/jrmlhermitte/bbfda76d59b820560bf2ff4a1e57d42d

## Issue
This came from a discussion on issue #691 

If we re-run the gist included above, poetry will try re-installing the referred library, even though the git tag has not changed.

This was discovered on the issue mentioned above. Here is the reply from @bibz 
> Thanks for the MRE.

> I can reproduce your example now.
> You found a different bug than we had, due to how git handled signed annotated tags.

> To summarise:

>    The (annotated) tag v5.1.3 itself is a git object with the short sha 73f60e6
>    The tree pointed to by the tag has the short sha 4056bbb

> The lock file refers to the tag object, because it is what v5.1.3 resolves to directly.
 Since the checked-out tree has a different sha, poetry thinks it is not up-to-date (the references are      different) and then re-install it.

> I think we need a new issue for this.

Would it be possible to investigate this, and possibly change the behaviour to not re-install the package?

Thanks for the great work on this wonderful library, keep it up!

**Comment by jrmlhermitte** [comment]
Would you guys need help with this?
I can try to use [this commit](https://github.com/python-poetry/poetry/commit/bf2d515a1bc53e0d913ef117f3bd0656b57680a1) as a model (referenced by @bibz). I'm a bit busy until the weekend though, and I may be slow.

If you have it covered, no worries, just trying to offer help when I can, awesome library :)

(PS: I've switched to non-annotated tags so it's not pressing for me, but I don't want others to encounter this :) )

**Comment by finswimmer** [comment]
Hello @jrmlhermitte ,

we appreciate any help. So if you like to work on this issue, just go on. :+1: 

Thank you for your help!

fin swimmer

**Comment by jrmlhermitte** [comment]
@finswimmer I think #1948 is all we need.
I would like to test this by actually running poetry. Is there a recommended way to do that?

I would like to poetry install poetry from a virtual environment and then poetry install another package from this environment. Would that be the right way to do it?
