### ISSUE TITLE
No matching distribution found for pip install [extra] package managed by poetry

### ISSUE THREAD

**Issue by CrispyCrafter** [python-poetry/poetry#1924]
---
No matching distribution found for pip install [extra] package managed by poetry
---

- [x ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 18.04.2 LTS
- **Poetry version**: poetry==1.0.2

## Issue
In our current workflow we use poetry to maintain an internal package, hosted on a private pypi server. For local R&D we install this package using pip into a different virtual-environment.

One of the core requirements inside the poetry maintained package contains an optional extra dep.
`daiquiri[json]==1.5.0`

When building our R&D docker image (Ubuntu 18.04.2 LTS) we install the internal package using pip.

`pip install 'internal-package'  -i <repo_url> -v --trusted-host <repo_host>`

This command however fails when looking for `daiquiri[json]==1.5.0` i.e. package
`ERROR: No matching distribution found for daiquiri[json]==1.5.0 `

I anticipate this has something to do with globbing, as this behavior is know to [plague zsh users](https://stackoverflow.com/questions/30539798/zsh-no-matches-found-requestssecurity)

Is there perhaps an issue in the way poetry created the setup.py file using optional packages, or would the issue originate inside the docker stack?

**Comment by finswimmer** [comment]
Hello @CrispyCrafter,

you haven't come back to this issue for a long while. So I assume this is solved in the meantime and I can close this ticket.

Feel free to leave a comment if you disagree.

fin swimmer
