### ISSUE TITLE
Improve 'poetry add x y z' behavior when either x, y or z are already installed.

### ISSUE THREAD

**Issue by mbello** [python-poetry/poetry#1925]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

The command `poetry add x` fails with an error if `x` is already installed. It is common to write scripts where one issues the full command e.g. 'apt-get install --y x y z' when you want to make sure x, y and z are installed without first checking whether any of those pieces are already present in the system. Similarly, I would like my script to not abort because poetry errors out when I ask it to add a package that is already installed.
Worse yet, when issuing `poetry add x y z`, if x is already installed, it will fail before installing y and z so it is not even possible to just ignore the error. 

Possible solution 1: make poetry ignore installed packages, just issue a warning in those cases and then skip to the next package that needs to be added.

Possible solution 2: to avoid changing behavior in these cases (which I do not think would be a big deal), add a command switch to enable this desirable behavior

**Comment by seansfkelley** [comment]
FWIW, Yarn treats adding a package you already have the same as adding it anew: it sets the declared version range in package.json (i.e., pyproject.toml) to match at least the latest available version, then re-resolves and re-locks. I quite like this behavior, and often do `poetry add` by accident.

**Comment by finswimmer** [comment]
This was implemented in https://github.com/python-poetry/poetry/pull/2886
