### ISSUE TITLE
Support --help switch on commands: new, add, remove, run, search

### ISSUE THREAD

**Issue by mbello** [python-poetry/poetry#1926]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

Tested on poetry v1.0.2

## Feature Request
I find poetry very user friendly, when I am in doubt of the command line options for a given command I can always call `poetry <command> --help`.
Except, not always. A few commands do not follow the rule/convention and I get an error when I try it with the commands: `new, add, remove, run, search`.

Of all 23 commands, only these 5 do not support the --help switch.
I found out that `poetry help <command>` works for these 5 commands as well. So maybe point `<command> --help` to the same output of `help <command>`?

**Comment by finswimmer** [comment]
Hello @mbello,

this was already reported earlier:

* #1625
* #1873 
* #1920 

and will be fixed soon (#1910).

fin swimmer
