### ISSUE TITLE
Wheel doesn't contain generated python files

### ISSUE THREAD

**Issue by xppt** [python-poetry/poetry#1933]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Win10 64-bit, 18362.592
- **Poetry version**: 1.0.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/xppt/d3d3d3db24adb3c59a0105ab6197ca68

## Issue

Hello!

I'm using custom build command, which is generating some additional .py files (it is compiling protobuf in my real project) during build. It then places them inside {build_dir}/lib. Command is attached with the gist link above.
Unfortunately these files are not copied inside wheel archive after invocation of `poetry build`, and therefore it is not usable.

Seems like this is because poetry only copies `lib.*/` contents, but not `lib/`:
https://github.com/python-poetry/poetry/blob/dbe2c38/poetry/masonry/builders/wheel.py#L110

So, the question is
- Why isn't `lib/` contents get copied inside wheel?
- Is there some better way to generate python files during build with poetry?

**Comment by abn** [comment]
You will need to specify these packages separately using https://python-poetry.org/docs/pyproject/#packages.
