### ISSUE TITLE
Replace blue color, very hard to read in dark consoles

### ISSUE THREAD

**Issue by a666** [python-poetry/poetry#1934]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

Just as an example:
![2020-01-22_13-28](https://user-images.githubusercontent.com/19142162/72927184-548a9100-3d1b-11ea-936a-6a21b959fbb5.png)

I know that cleo only has 8 colors (...). 

Perhaps the info messages could be set to cyan? Or could another solution be proposed?

**Comment by sdispater** [comment]
I don't think this is an issue with Poetry. I think it's your terminal color theme that should be modified so that every color is readable on dark background.

**Comment by a666** [comment]
You're right, this is a local env problem, sorry.
Thanks for the support.
