### ISSUE TITLE
Execute pre-build tasks

### ISSUE THREAD

**Issue by multipitch** [python-poetry/poetry#1938]
It would be useful to have the ability to run command line scripts from poetry as precursors to building a package.
One specific example is to have poetry build documentation that will be included in a package before building the package itself e.g. by getting poetry to execute...
```
$ cd docs/
$ make latexpdf
```
I'm aware that the same could be achieved by creating a `Makefile` or a bash script to do these tasks and also run `poetry build`, but this goes against the idea of  using poetry and `pyproject.toml` to cut down on the number of config files in the project root.

**Comment by AndrewSpittlemeister** [comment]
I would take a look at [borca](https://github.com/AndrewSpittlemeister/borca) or [Taskipy](https://github.com/illBeRoy/taskipy). They are similar but each have their strengths as well.

**Comment by thomas6g** [comment]
Yes, it would be great to have the ability to execute scripts during the build process. 
I'm using the poetry-dynamic-versioning plugin to retrieve version information from the git
commit history. 

The plugin patches the version information during the build process and 
recovers the default values afterwards. It would  be nice if I could run the Sphinx documentation 
generation during the build process to patch the version information within the documentation, too.

**Comment by sonotley** [comment]
I like this idea too, although I suppose you could argue that whatever calls `poetry build` could also call the prebuild tasks (if you're using Jenkins for example).

Given that the poetry-dynamic-versioning plugin is effectively (I think?) a pre-build task I would have thought it should be fairly straightforward to develop a plug-in that calls prebuild jobs. Perhaps this would be preferable to adding a feature.

I've taken a look at the code of the plugin above and it's only 100 lines which are virtually all business logic. However one thing I'm uncertain about is how (or if) it limits itself to only being invoked on build, it seems to just run at soon as it is loaded.

**Comment by maelp** [comment]
Pre-build steps would indeed be useful if they can be called when installing a package in "developper mode". I'm working in a monorepo with Python packages in developper mode, and some require some pre-build steps (like compiling protobuf definitions to python), it would be nice if that could be run automatically.

**Comment by dimbleby** [comment]
poetry is not a general purpose task runner and IMO it shouldn't become one.  (If anything, it already does too many things for my taste.)  As the original report acknowledges, there are plenty of other solutions for that sort of thing.

Also this has been open nearly three years now - I think it's reasonable to conclude that there's no-one who both thinks that this is a good idea and also cares enough to put together a pull request.  

Time to close it I reckon.
