### ISSUE TITLE
`poetry export -f requirements.txt` outputs invalid line for path dependency managed by poetry

### ISSUE THREAD

**Issue by tamuhey** [python-poetry/poetry#1940]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**:  macos
- **Poetry version**:  1.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**:  https://gist.github.com/tamuhey/0354a87c2ff1f4b55efddb30ec7d871d

## Issue

I have a nested projects managed by poetry, like below:

```
foo/
  |- pyproject.toml
  |- bar/
        |- pyproject.toml
```

And foo depends on bar:

```toml
# foo/pyproject.toml
[tool.poetry.dependencies]
python = "^3.7"
bar = {path = "bar"}
```

I want to export `foo/pyproject.toml` to build docker faster:

```bash
$ poetry export -f requirements.txt > requirements.txt
```

```
# requirements.txt
-e bar
```

The problem is, I cannot `pip install -r requirements.txt` with the following error:

```
File "setup.py" not found. Directory cannot be installed in editable mode:
(A "pyproject.toml" file was found, but editable mode currently requires a setup.py based build.)
```

It can be avoided if the `requirements.txt` becomes:

```
./bar
```

**Comment by finswimmer** [comment]
Hello @tamuhey ,

why do you have this nested project? Just put a `__init__.py` in `bar` (and remove the `pyprject.toml`) and you can access this package by `import foo.bar`.

That poetry export the path dependency as editable is the correct behavior. Because this dependency is installed as editable by default. If you don't want/need this, you have to set `develop=false` before installing in your `pyproject.toml `:

```
[tool.poetry.dependencies]
python = "^3.7"
bar = {path = "bar", develop=false}
```

fin swimmer

**Comment by tamuhey** [comment]
@finswimmer Thanks for reply!

> why do you have this nested project? Just put a __init__.py in bar (and remove the pyprject.toml) and you can access this package by import foo.bar.

Because `bar` is another libary, and it is hosted in my private repository.

> Because this dependency is installed as editable by default.

I know that, but `pip` cannot install poetry project as editable.
I think `poetry export -f requirements.txt` should output what pip can install.
If not, why `poetry export` exists?
