### ISSUE TITLE
Feature Request: Add testpypi by default

### ISSUE THREAD

**Issue by BeatLink** [python-poetry/poetry#1943]
Would it be possible to add the TestPyPI repository by default?

**Comment by dimbleby** [comment]
clearly not going to happen

**Comment by abn** [comment]
While, personally, this is tempting for publishing; I do not think this is common enough to warrant default inclusion.

This can be easily done for publishing as shown here.

```bash
# via env var
export POETRY_REPOSITORIES_TESTPYPI_URL=https://upload.test.pypi.org/legacy/
export POETRY_PYPI_TOKEN_TESTPYPI=my-token

# or via config
poetry config repositories.testpypi https://test.pypi.org/legacy/
poetry config pypi-token.testpypi my-token
```

Or For adding as a package source, you co do as shown here.

```bash
poetry source add testpypi https://test.pypi.org/simple/
```

For more information see https://python-poetry.org/docs/repositories/.
