### ISSUE TITLE
poetry update --latest (w/ ignoring current pinning)

### ISSUE THREAD

**Issue by Uninen** [python-poetry/poetry#1944]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

I've tried to search both documentation, issues and Web, but haven't found a solution for use case of "please update this package to newest version without reading current pinning in  `pyproject.toml`". This is something I do quite often and so far I haven't found a clean way of doing it with Poetry. 

For example: I currently have `django = "^2.0.0"` in my `pyproject.toml` but I'd like to upgrade that to the very latest version (3.0.2). I can of course change the pinning by hand to `pyproject.toml` but what if I want to upgrade my whole project to latest everything (every package)? What I'd like to is something like `poetry update --latest`

Is there currently a way to do this without too much manual work (for one or many packages)?

**Comment by AndreCNF** [comment]
I'd also prefer to have a more intuitive way of updating packages to the latest version. Right now, to update packages, I run this command, which seems to work fine (although it's not as clear as using a command called 'update'):
`poetry add PACKAGE_NAME@latest`

**Comment by Yajo** [comment]
@AndreCNF Thanks! It works like a charm! If that were documented somewhere, it'd be enough for me.

**Comment by Garrett-R** [comment]
I do notice that using this will change your version specification a bit.  For example, if you have
```toml
Flask = "1.1.1"
``` 

and then do `poetry add PACKAGE_NAME@latest`, it will change it to:
```toml
Flask = "^1.1.2"
```

**Comment by sinoroc** [comment]
@Garrett-R That seems normal. What else were you expecting?

**Comment by finswimmer** [comment]
Hello,

the `poetry add PACKAGE_NAME@latest` syntax is mentioned in the [docs](https://python-poetry.org/docs/cli/#add). A command to upgrade all packages to the latest version is already requested in https://github.com/python-poetry/poetry/issues/461

fin swimmer

**Comment by Garrett-R** [comment]
@sinoroc I was expecting it to not add the caret.  I started an issue [here](https://github.com/python-poetry/poetry/issues/3503).

**Comment by wyattowalsh** [comment]
I recently created a Python3 script to update all Poetry packages to their latest version while preserving extras and dependency groups. Check it out [here](https://github.com/wyattowalsh/poetry-dependency-updater)

**Comment by cfxegbert** [comment]
> I recently created a Python3 script to update all Poetry packages to their latest version while preserving extras and dependency groups. Check it out [here](https://github.com/wyattowalsh/poetry-dependency-updater)

https://github.com/MousaZeidBaker/poetry-plugin-up

**Comment by sinoroc** [comment]
Isn't it faster to delete the `poetry.lock` file and the environment and recreate them from scratch? Poetry would normally get the latest, unless there is a reason not to (the lock file being one of those possible reasons).
