### ISSUE TITLE
Extend `poetry version xxx` commands to support `-beta.#` and `-rc.#`

### ISSUE THREAD

**Issue by joeb1415** [python-poetry/poetry#1959]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

`poetry version prepatch` (or prerelease, etc.) is great for incrementing the version from `1.2.3` to `1.2.4-alpha.0`, and then to `1.2.4-alpha.1`, etc. but this is the extent of the functionality. 
https://python-poetry.org/docs/cli/#version

It would be great if we could add a few other commands to allow for pre-release name patterns. Adding `alpha`, `beta`, and `rc` would make sense as the other available commands to support other pre-release versions. This could work as:
```
$ poetry version alpha
Bumping version from 1.2.3 to 1.2.4-alpha.0
$ poetry version alpha
Bumping version from 1.2.4-alpha.0 to 1.2.4-alpha.1
$ poetry version beta
Bumping version from 1.2.4-alpha.1 to 1.2.4-beta.0
$ poetry version rc
Bumping version from 1.2.4-beta.0 to 1.2.4-rc.0
$ poetry version rc
Bumping version from 1.2.4-rc.0 to 1.2.4-rc.1
$ poetry version patch
Bumping version from 1.2.4-rc.1 to 1.2.4
```

This would adhere to the pre-release precedence order described here: 
https://semver.org/#spec-item-11

Thanks for considering!

**Comment by joeb1415** [comment]
Perhaps adding an options flag `--modifier=xxx` here:
https://github.com/python-poetry/poetry/blob/affe32d8d41c76b5cb908fca492d36b6cebb0f76/poetry/console/commands/version.py#L14-L21

Where `modifier` matches these: 
https://github.com/python-poetry/poetry/blob/affe32d8d41c76b5cb908fca492d36b6cebb0f76/poetry/semver/version.py#L300

**Comment by timorkal** [comment]
will it ever be made?
I need to bump versions between branches with bash commands because "poetry version" command doesn't support it.

**Comment by PabloEmidio** [comment]
@python-poetry/triage

**Comment by PabloEmidio** [comment]
@python-poetry/triage

**Comment by q-wertz** [comment]
A problem is that the library [`semantic_version`](https://pypi.org/project/semantic-version/) crashes on the current poetry pre* version strings as it is strictly following the [semver specification](https://semver.org/).

```python
import semantic_version

semantic_version.Version("0.19.0a1")
```
Results in 
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[48], line 1
----> 1 semantic_version.Version("0.19.0a1")

File ~/VCS/ads-b_simulator/.venv/lib/python3.11/site-packages/semantic_version/base.py:105, in Version.__init__(self, version_string, major, minor, patch, prerelease, build, partial)
    102     raise ValueError("Call either Version('1.2.3') or Version(major=1, ...).")
    104 if has_text:
--> 105     major, minor, patch, prerelease, build = self.parse(version_string, partial)
    106 else:
    107     # Convenience: allow to omit prerelease/build.
    108     prerelease = tuple(prerelease or ())

File ~/VCS/ads-b_simulator/.venv/lib/python3.11/site-packages/semantic_version/base.py:318, in Version.parse(cls, version_string, partial, coerce)
    316 match = version_re.match(version_string)
    317 if not match:
--> 318     raise ValueError('Invalid version string: %r' % version_string)
    320 major, minor, patch, prerelease, build = match.groups()
    322 if _has_leading_zero(major):

ValueError: Invalid version string: '0.19.0a1'
```

**Comment by peterwwillis** [comment]
This is still an issue... would like to be able to iterate on prepatch versions of a patch without overwriting previous alpha versions. Bumping the patch version isn't what we want because the patch hasn't been released yet.

**Comment by radoering** [comment]
To those who are still waiting this feature: Can you please have a look whether #8089 satisfies your use cases? It's different from the original proposal in this issue, but seems to offer similar functionality from my perspective. (Since I'm not using `poetry version` to bump versions myself, I don't have strong feelings.)

**Comment by eliorc** [comment]
> To those who are still waiting this feature: Can you please have a look whether #8089 satisfies your use cases? It's different from the original proposal in this issue, but seems to offer similar functionality from my perspective. (Since I'm not using `poetry version` to bump versions myself, I don't have strong feelings.)

looks awesome

**Comment by froy001** [comment]
> To those who are still waiting this feature: Can you please have a look whether #8089 satisfies your use cases? It's different from the original proposal in this issue, but seems to offer similar functionality from my perspective. (Since I'm not using `poetry version` to bump versions myself, I don't have strong feelings.)

It's works for my usecase requiring an RC version. 
Is there an estimate on when this will be released?
