### ISSUE TITLE
Extend to support authentication token (PAT)

### ISSUE THREAD

**Issue by huntzhan** [python-poetry/poetry#1973]
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

I'm considering setup a private Github-hosted repository and hence require the `LegacyRepository` to support requests with authentication token (with the header `Authorization: token <github-pat>`). For now, only the username/password authentication is supported. I wonder if `poetry` could support this kind of authentication, probably by adding a new `--auth-token` CLI parameter and adjust the `Auth` class a little bit? I can help submit a PR if your bandwidth is limited.

**Comment by huntzhan** [comment]
Find a better way to solve this problem, close.

**Comment by espoirMur** [comment]
@huntzhan would you mind sharing what was the best way to solve the problem.?
