### ISSUE TITLE
cannot remove root package

### ISSUE THREAD

**Issue by nicolas33** [python-poetry/poetry#1976]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

Once installed the root package with `poetry install` I couldn't find a way to remove the root package to get the dependencies as `poetry install --no-root` would install them.

```
> poetry remove PACKAGE_ROOT_NAME
[ValueError]
Package PACKAGE_ROOT_NAME not found
>
```

**Comment by finswimmer** [comment]
Hello  @nicolas33,

you can remove the root package from the env using `pip`:

```
poetry run pip uninstall PACKAGE_ROOT_NAME
```

fin swimmer

**Comment by nicolas33** [comment]
Thank you much fin. I would expect to be able to do this with `poetry remove`, though.

**Comment by awilkins** [comment]
On top of this, doing

```
poetry install
poetry install --no-root
```

Doesn't remove the root package as you may expect.
