### ISSUE TITLE
`long_description` support

### ISSUE THREAD

**Issue by theonewolf** [python-poetry/poetry#1979]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

Can we support `long_description` similar to `setup.py` (https://packaging.python.org/guides/making-a-pypi-friendly-readme/#including-your-readme-in-your-package-s-metadata)?

Is there some method of doing that with `poetry` that I'm missing?

`description` is supposed to be a "short" description (https://python-poetry.org/docs/pyproject/#description).

**Comment by jedie** [comment]
Use readme: https://python-poetry.org/docs/pyproject/#readme

**Comment by theonewolf** [comment]
Ah if that accomplishes the same thing then thanks!
