### ISSUE TITLE
Spaces in Path to Virtualenv Fail to Spawn `fish` Shell

### ISSUE THREAD

**Issue by theonewolf** [python-poetry/poetry#1980]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 18.04, WSL 2
- **Poetry version**: 1.0.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: Not easily possible (proprietary project).

## Issue

1. I overrode where virtualenvs get installed.
2. My full path to the virtualenv includes a folder with spaces in the name.
3. When spawning the shell with `poetry shell`, it chokes with `fish` trying to 'source ....' a path with non-escaped or quoted spaces.

Otherwise, `poetry install` and other related commands all work.

**Comment by zezic** [comment]
I can confirm that this affects Bash as well.

**Comment by atomobianco** [comment]
Hello there,
I stumbled on this open issue and I hope to give more info about a working context.
I use fish (version 3.1.2) and poetry (Poetry version 1.1.4).
I installed https://github.com/ryoppippi/fish-poetry with `fisher install 'ryoppippi/fish-poetry'`.
Whenever I enter a poetry folder with the local virtual environment `.venv` the shell automatically activates it:
```
Spawning shell within /home/me/project/.venv
source /home/me/project/.venv/bin/activate.fish
...
```
and when running within this I get
```
Virtual environment already activated: /home/me/project/.venv
```
All works fine in my case.

**Comment by zezic** [comment]
@atomobianco This issue is about paths with spaces.

**Comment by rben01** [comment]
Should this be closed now? https://github.com/python-poetry/poetry/commit/bc3ad7db771bfeabf1fcea6c9b402c279ff54866 seems like it fixes this.

**Comment by theonewolf** [comment]
That PR supposedly closed https://github.com/python-poetry/poetry/issues/3630.

Which looks like a duplicate issue for what I reported 1 year ago, almost to the day.

Based on the commit and that issue, I _believe_ we can safely close this.  I will re-open this issue if I notice it cropping up in the future.
