### ISSUE TITLE
Poetry's package detection from url does not match pips standard

### ISSUE THREAD

**Issue by edrodri2** [python-poetry/poetry#1983]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.

- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS 10.15: Catalina
- **Poetry version**: 1.0.3

## Issue
Pip requires pypi and other repositories file names to match the project name while poetry ignores this requirement.

Thus if any other files with the same format i.e. <wrong_package>-<wrong-version>.zip are uploaded to the repository in the folder corresponding to a given package, then poetry will incorrectly use the wrong-version in it's dependency resolver. Had this issue on a private repository with multiple accidentally uploaded zip files.

See [pip's LinkEvaluator](https://github.com/pypa/pip/blob/19665791fa81e3e540721928430e656d167fe307/src/pip/_internal/index/package_finder.py#L104) for more information on pip's link handling.

**Comment by finswimmer** [comment]
Hello @edrodri2 ,

can you please give a more specific example, that shows your issue?

AFAIK `poetry` doesn't take care of filenames in case of URL dependencies. Instead it tries to figure out package name and version directly from the `pyproject.toml` or `setup.py` in the given path. This is more reliable then trust on any filenames.

But maybe I misunderstood your issue. :smiley: 

fin swimmer

**Comment by edrodri2** [comment]
Sure so let's say for example the if the link https://pypi.org/simple/requests/ which contains a list of all the request versions were to have a file with the name wrong-package-5000.zip mistakenly uploaded (actually happened to me in a managed private repository). Then any attempt to poetry add requests will resolve requests version to 5000. It will then attempt to pip install requests==5000 which will fail because pip only detects versions from files matching the package name we are trying to install.

Since we are using pip to install packages it does not make sense to have different behavior to detect versions. So the bug is that the version detection does not match up with Pip's

Does that clarify the issue?
