### ISSUE TITLE
poetry init fails randomly during interactive package installation if package isn't in list of suggestions

### ISSUE THREAD

**Issue by krp** [python-poetry/poetry#1984]
- **OS version and name**: macOS Catalina v10.15.2
- **Poetry version**: 1.0.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: pyproject.toml fails to be created.

## Issue
I'm running `poetry init` on an existing project, and after completing the package name, version, description, author, license, and compatible Python versions it prompts whether or not you wish to define your main dependencies interactively.

Sometimes the package you've searched for doesn't appear in the list of 10 suggestions (probably async related), and you're prompted to complete the package name. This doesn't work.

For example, when successful it looks like this:

![image](https://user-images.githubusercontent.com/2504972/73894345-14add700-48e1-11ea-8033-5b5ba83b2b4c.png)

When it fails it looks like this (Faker - https://pypi.org/project/Faker/ and gunicorn - https://pypi.org/project/gunicorn/ are both valid package names, I just used gunicorn because there's no prompt to search for another package): 
![image](https://user-images.githubusercontent.com/2504972/73895257-db2a9b00-48e3-11ea-83ae-d49546c12803.png)

Poetry seems to exit / crash after `n <= 3` failed attempts.

Sometimes a package that worked the first time doesn't work on a second attempt (again probably async related). e.g. Here with Django:

![image](https://user-images.githubusercontent.com/2504972/73894468-72daba00-48e1-11ea-9d94-246e3a630298.png)

This can happen on multiple attempts. Hitting enter on a blank package tries to call string.replace instead of returning you to the add-package prompt.

![image](https://user-images.githubusercontent.com/2504972/73895586-f6e27100-48e4-11ea-9374-e7d0af89b0bf.png)

**Comment by finswimmer** [comment]
Hello @krp,

this should be solved at least in the latest preview release (1.2.0b3).

Feel free to leave a comment if you disagree.

fin swimmer
