### ISSUE TITLE
poetry show --leaves

### ISSUE THREAD

**Issue by zachvalenta** [python-poetry/poetry#1990]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

`poetry show -t` outputs a tree of top-level dependencies and their sub-dependencies. Be nice if there was a separate command to output only the top-level dependencies (similar to Homebrew's `brew leaves`), especially as a project's number of dependencies increases and you want a snapshot of everything.

**Comment by uselessscat** [comment]
I think it would be great to have this and the possibility to use with `-o` like comments on #2684

While you can use grep like this

    poetry show -t | grep '^[[:blank:]]*[^[:blank:]|`]'

**Comment by ThatXliner** [comment]
On this, `poetry show --only=main` doesn't work
