### ISSUE TITLE
warn/error if poetry install doesn't install any packages from the project itself.

### ISSUE THREAD

**Issue by cjw296** [python-poetry/poetry#1997]
- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: RHEL 7.5
- **Poetry version**:1.0.3

## Issue

Scripts like this, defined in pyproject.toml:
```
[tool.poetry.scripts]
foo= 'foo.bar:baz'
```

...appear to be totally ignored by `poetry install` when poetry is version 1.0.3 :-(

What might I be doing wrong?

**Comment by cjw296** [comment]
Hmm, this looks like poetry is not actually installing the project. All it's deps, but not the project.
Why might that be?

**Comment by cjw296** [comment]
Turns out my project name was not the same as the package name, so it wasn't installing any packages.
A warning or error then might make sense.

The fix was:

```
[tool.poetry]
name = "project-name"
...
packages = [{ include = "the_package" }]
```

**Comment by finswimmer** [comment]
Hello,

during `poetry install` is printing what it is installing. In case the project itself is installed one receive something like `Installing the current project: `. If this is missing the project was not installed.

fin swimmer
