### ISSUE TITLE
[Feature Request] "poetry new" command allows specifying Python version

### ISSUE THREAD

**Issue by btegs** [python-poetry/poetry#2005]
When currently doing the command `poetry new my-project` it will create the .toml file with the currently active Python version as the default [tool.poetry.dependencies] with no option to set it in the command line from the start.

For users that may have pyenv installed, there are the usual options like `pyenv global` to set the global Python version before running `poetry new` or `pyenv local` to set the current directory with that verison, but it would be nice to have a command for `new` along the lines of `--python X.XX` where the X.XX could be 3.8 for example or directly 3.8.1.

In the past with Poetry on macOS and Linux, I had to install 3.8.1 via pyenv, change my system version to that, run poetry new so it registers that project and venv with that, and switch back to the system version of Python. I try to keep my version in pyenv to the one that ships with the OS by default to avoid any Python packages in Ubuntu having a conflict if it may rely on that Python for main operating system features.

So what do you think?

**Comment by finswimmer** [comment]
I think we should make `poetry new` an extension of `poetry init`. This is why I'm closing this in favor of #2563.
