### ISSUE TITLE
Poetry fails to find wheel on pypi when 'latest' versions differ per OS

### ISSUE THREAD

**Issue by cbcoutinho** [python-poetry/poetry#2012]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Mac OS X 10.15.3
- **Poetry version**: 1.0.3

## Issue

I tried adding a dependency to a project I am working on that only uploaded the latest version of their package for Windows-based systems [mkleehammer/pyodbc/issues/704](https://github.com/mkleehammer/pyodbc/issues/704). The problem is, `poetry` still expects to find the latest version of the library for my operating system, which is not available.

I expect this issue to solve itself for the `pyodbc` package as the maintainer has published it on his side, but the error should still not occur, and I would suggest poetry fall back to the latest available version available for that operating system.

```shell
$ cd /tmp
$ poetry new test && cd test
$ poetry add pyodbc
Creating virtualenv test-8DRKBHXr-py2.7 in /Users/chris/Library/Caches/pypoetry/virtualenvs
Using version ^4.0.30 for pyodbc

Updating dependencies
Resolving dependencies... (2.4s)

Writing lock file


Package operations: 18 installs, 0 updates, 0 removals

  - Installing contextlib2 (0.6.0.post1)
  - Installing scandir (1.10.0)
  - Installing six (1.14.0)
  - Installing configparser (4.0.2)
  - Installing pathlib2 (2.3.5)
  - Installing zipp (1.1.0)
  - Installing importlib-metadata (1.5.0)
  - Installing pyparsing (2.4.6)
  - Installing atomicwrites (1.3.0)
  - Installing attrs (19.3.0)
  - Installing funcsigs (1.0.2)
  - Installing more-itertools (5.0.0)
  - Installing packaging (20.1)
  - Installing pluggy (0.13.1)
  - Installing py (1.8.1)
  - Installing wcwidth (0.1.8)
  - Installing pyodbc (4.0.30)

[EnvCommandError]
Command ['/Users/chris/Library/Caches/pypoetry/virtualenvs/test-8DRKBHXr-py2.7/bin/pip', 'install', '--no-deps', 'pyodbc==4.0.30'] errored with the following return code 1, and output:
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Looking in links: file:///Users/chris/.cache/pip/wheelhouse
ERROR: Could not find a version that satisfies the requirement pyodbc==4.0.30 (from versions: 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.1.5, 2.1.6, 2.1.7, 2.1.8, 2.1.9, 2.1.10, 2.1.11, 3.0.3, 3.0.6, 3.0.7, 3.0.8, 3.0.9, 3.0.10, 3.1.1, 4.0.0, 4.0.1, 4.0.2, 4.0.3, 4.0.5, 4.0.6, 4.0.7, 4.0.8, 4.0.9, 4.0.10, 4.0.11, 4.0.12, 4.0.13, 4.0.14, 4.0.15, 4.0.16, 4.0.17, 4.0.18, 4.0.19, 4.0.20, 4.0.21, 4.0.22, 4.0.23, 4.0.24, 4.0.25, 4.0.26, 4.0.27, 4.0.28, 4.0.30b1)
ERROR: No matching distribution found for pyodbc==4.0.30
WARNING: You are using pip version 19.3.1; however, version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

## Compared to pip

This is what happens when using python3 and virtualenv - note how it uses 4.0.28, which is the latest published version for Mac OS X.

```shell
$ cd /tmp
$ python3 -m venv venv
$ source venv/bin/activate
(venv) $ python3 -m pip install pyodbc
Looking in links: file:///Users/chris/.cache/pip/wheelhouse
Collecting pyodbc
  Using cached https://files.pythonhosted.org/packages/f7/ef/f12302217eb6070f39cca87b719abf68a962896f7b7f3dd0a7b4e718a3f7/pyodbc-4.0.28-cp37-cp37m-macosx_10_9_x86_64.whl
Installing collected packages: pyodbc
Successfully installed pyodbc-4.0.28
WARNING: You are using pip version 19.2.3, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by neersighted** [comment]
This is as-designed -- Poetry does not factor wheel availability into version solving. Thus, Poetry will choose a version that is newer but does not have a wheel for the current platform over a version that is older, but has a wheel. This is not intended to change, as Poetry considers a holistic solution and locks/solves for all platforms at once, instead of changing behavior based on the current platform.
