### ISSUE TITLE
[Feature Request] "poetry init" to read .python-version to autodetect default Python version

### ISSUE THREAD

**Issue by btegs** [python-poetry/poetry#2019]
If pyenv created a `.python-version` file inside of the current directory through `pyenv local X.XX` (where X.XX is the version of course), there should be a check in `poetry init` to read the `.python-version` file if it exists and if the user did not specify a version (just hit enter or left blank), the creation of the pyproject.toml will set the python version under [tool.poetry.dependencies] to the version set in that file. You could also have it show the version loaded from the file as the default version in the interactive questions.

This would be an excellent feature for a future release. :-)

**Comment by finswimmer** [comment]
At Poetry we try to avoid implementations specific for third-party tools. But maybe it's possible to implement it as a [plugin](https://python-poetry.org/docs/master/plugins/). Or you give https://github.com/python-poetry/poetry/pull/4852 a try. Maybe this works as well :)
