### ISSUE TITLE
Multithreading operations

### ISSUE THREAD

**Issue by Vedrillan** [python-poetry/poetry#2021]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

Having operations multi threaded could be a good performance improvement without changing the code too much.

A new command option should exists to customize the number of parallel threads, and be able to set it to 1 to be basically disabled. The number of thread by default should be automatic and based on current CPU spec, which is usually already done by python multi thread classes.

The operation are currently made sequentially to avoid failure for some cases where packages installation depends on other packages, in this case it could be solved by simply disabling the multi threading by setting the number of job to 1. This must be well documented to allow quick resolution.

In any case I think that multi threading should exists in Poetry, the real question is to decide if it should be enabled by default or not.

**Comment by finswimmer** [comment]
Installing packages already happens with multiple processes. With poetry 1.2.0b1 it is now possible to limit the number of parallel processes. See https://python-poetry.org/blog/announcing-poetry-1.2.0b1/#configure-the-number-of-parallel-processes.
