### ISSUE TITLE
During init, misspelling a dependency then picking it from the list adds the misspelling to pyproject.toml

### ISSUE THREAD

**Issue by Dvlv** [python-poetry/poetry#2022]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: OpenSuse Leap 15.1
- **Poetry version**: 1.0.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: N/A

## Issue
Hello,

If you typo a package name, then select the correct one from the list, the resulting toml file ends up with your typo.

Example:

```bash
(env) > poetry init

This command will guide you through creating your pyproject.toml config.

Package name [timekeeping]:  
Version [0.1.0]:  
Description []:  
Author [D L <Dvlv@users.noreply.github.com>, n to skip]:  
License []:  
Compatible Python versions [^3.6]:  

Would you like to define your main dependencies interactively? (yes/no) [yes] 
You can specify a package in the following forms:
  - A single name (requests)
  - A name and a constraint (requests ^2.23.0)
  - A git url (git+https://github.com/python-poetry/poetry.git)
  - A git url with a revision (git+https://github.com/python-poetry/poetry.git#develop)
  - A file path (../my-package/my-package.whl)
  - A directory (../my-package/)
  - An url (https://example.com/packages/my-package-0.1.0.tar.gz)

Search for package to add (or leave blank to continue): psycopg-binar
Found 20 packages matching psycopg-binar

Enter package # to add, or the complete package name if it is not listed: 
 [0] psycopg3
 [1] psycopg2
 [2] psycopg
 [3] Psycopg2Database
 [4] psycopg2ct
 [5] psycopg2-wrapper
 [6] psycopg2transaction
 [7] db-psycopg2
 [8] psycopg2-mq
 [9] psycopg2cffi
 > 1
Enter the version constraint to require (or leave blank to use the latest version): 
Using version ^2.8.4 for psycopg2

Add a package: 

Would you like to define your dev dependencies (require-dev) interactively (yes/no) [yes] no
Generated file

[tool.poetry]
name = "timekeeping"
version = "0.1.0"
description = ""
authors = ["D L <Dvlv@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.6"
psycopg-binar = "^2.8.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

Do you confirm generation? (yes/no) [yes]
```

As I chose option 1 and the prompt said "Using version ^2.8.4 for psycopg2", I expected psycopg2 in my .toml file, but instead it wrote the typo "psycopg-binar".

I believe the fix for this would be to change `console/commands/init.py` at around line 286 and add `constraint["name"] = package`.

Full if statement block:

```python
if package is not False:
    constraint["name"] = package
    requires.append(constraint)
```

I wanted to do a PR for this but the unit tests have multiple fails even with a fresh repo (Both OpenSuse and Arch linux) so I can't get a working unit test for the patch.

Thanks.

**Comment by finswimmer** [comment]
Seems to be fixed in the meantime. Thanks for reporting :+1:
