### ISSUE TITLE
ability to skip updating the lockfile in the update command

### ISSUE THREAD

**Issue by dedsm** [python-poetry/poetry#2023]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

Hello, 

I have a CI flow where I like to run the tests against locked _and_ updated dependencies, which is perfectly achievable just by running `poetry install` in the first case and `poetry update` in the second.

It would be nice if the update command had a `--skip-lock` or something similar that does the inverse as `--lock`, it would just install all the updates without writing poetry.lock at the end.

**Comment by finswimmer** [comment]
Hello,

keeping the lock file in sync when changing dependencies via cli is a core feature of Poetry. Skip the locking doesn't sound like a good feature.

I'm closing this for now. If you still believe this is something useful, feel free to leave a comment with a detailed use case.

fin swimmer
