### ISSUE TITLE
Virtualenv.create_environment no longer exists

### ISSUE THREAD

**Issue by schinckel** [python-poetry/poetry#2026]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS
- **Poetry version**: 1.0.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: Not relevant

## Issue

It seems that the latest version of virtualenv (for Python2) stopped having a `create_environment` function: https://github.com/pypa/virtualenv/issues/1585

**Comment by schinckel** [comment]
In the meantime, you can install version `16.7.9` of virtualenv, and it will work.

**Comment by finswimmer** [comment]
Hello @schinckel,

according to the linked issue it was a virtualenv problem which is fixed with version 20.0.2.

fin swimmer
