### ISSUE TITLE
Add dependencies automatically which are used in python sources

### ISSUE THREAD

**Issue by musaprg** [python-poetry/poetry#2029]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

Hello. Thank you for developing this awesome tools and I'm glad to use them.

It would be helpful to create subcommand to add dependencies automatically which are used in actual Python source files.
Currently, we should check and specify which package is used in the sources. It is very annoying to check and specify dependencies when we get some unkind source codes with no requirements.txt or something like that.

**Comment by finswimmer** [comment]
Hello,

this is something out of scope for Poetry. This would require source code parsing.
