### ISSUE TITLE
Unable to get package version from vcs/directory if the given package has a build dependency which require python>3

### ISSUE THREAD

**Issue by az0uz** [python-poetry/poetry#2031]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS 10.14.6 (Mojave)
- **Poetry version**: 1.0.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/az0uz/63e97522637927b97a9b8d2883eb5286

### Step to reproduce
- your system `python` command point to python 2 (python2.7.16)
- lastest poetry installed with the piped bash script (poetry is being run using python2 from the shebang in ~/.poetry/bin/poetry which is `#!/usr/bin/env python`)
- create a directory with the given [pyproject.toml](https://gist.github.com/az0uz/63e97522637927b97a9b8d2883eb5286/raw/daa10e4b39db295362bf2fa4bb66b6d888117ada/pyproject.toml) file
- run `poetry install` 
- We get:
```
The currently activated Python version 2.7.16 is not supported by the project (^3.6).
Trying to find and use a compatible version. 
Using python3 (3.7.6)
Creating virtualenv poetry-proj-W5RSEvjt-py3.7 in [...]

Updating dependencies
Resolving dependencies...

[RuntimeError]
Unable to retrieve the package version for /var/folders/0b/5v8bx55j0h7bpx_5jjh2hgf80000gn/T/pypoetry-git-py-foo-pkdLKuon
```

### Understanding
- It seems that poetry detects that my project needs to run in python>=3.6 so creates the virtualenv accordingly.
- when resolving package version and dependency from a directory (or vcs after clonning the directory) poetry creates a virtualenv using the system env (python2) to run `python setup.py egg_info` -> I think poetry should create a virtualenv with the same python version as the project which would avoid some errors
- in some cases where a dependency has a `setup_requires` or a pyproject.toml with custom build-system.requires (PEP518), distutils will try to install the setup dependencies which will fail if that setup dependency requires python>=3

### related poetry code
* when resolving dependency, poetry is using `EnvManager.build_venv()` [see here](https://github.com/python-poetry/poetry/blob/7d5934e5c8a7463a930bf46ba3882434953183ca/poetry/puzzle/provider.py#L330)
* when creating project virtualenv, poetry is using `EnvManager.create_venv()` [see here](https://github.com/python-poetry/poetry/blob/7d5934e5c8a7463a930bf46ba3882434953183ca/poetry/console/config/application_config.py#L89)
* Only `create_venv()` tries to find a compatible python version to create the virtual env [see here](https://github.com/python-poetry/poetry/blob/7d5934e5c8a7463a930bf46ba3882434953183ca/poetry/utils/env.py#L516)

Shouldn't the version solver be aware of the project required python version and use the same to solve dependencies ?

**Comment by finswimmer** [comment]
Hello @az0uz,

thanks a lot for reporting and your analysis.

What happens here is:

`poetry` clones the repository to `pypoetry-git-py-foo-pkdLKuon`. This is just a "normal" folder and not a virtual environment. It then tries to parse the `setup.py` to received the version number. Parsing the `setup.py` is only supported if poetry runs with at least python 3.5. The parsing is not initiated by running a new python job within the created venv. It's the normal python processed started with initial `poetry` command. And this uses python2.

So this issue is at the moment by design. Not sure if there is an easy way to solve this within poetry.

Workarounds would be to use pyenv and activate python3 or create a virtualenv with python3 by hand (`python3 -m venv .venv`), activate it (`source .venv/bin/activate`) and run `poetry install` within this venv.

fin swimmer

**Comment by colini** [comment]
I am also running into this issue.  In my case, poetry (1.0.5 on macOS) is unable to install the correct dependencies for flask-openid, b/c its setup.py checks sys.version_info[0] to determine how to set install_requires.  Code is here:
https://github.com/mitsuhiko/flask-openid/blob/master/setup.py#L30

I agree w/ @az0uz that it seems the dependency resolver should use the same version of python3 and the project request, especially if it's going to execute setup.py scripts.

**Comment by az0uz** [comment]
@colini yes I think it would make more sense / resolve some deeply hidden issues

I think that having to run poetry inside a virtualenv is the best ways to get others lost on how to run your project. So as a workaround, I recommend re-installing poetry using this command (replace `python3.7` by your up to date python version) :
```
pip uninstall poetry
python3.7 -m "pip" install poetry
```
but poetry kind of fails to fulfill its purpose of being able to lock every versions (including python) and be easy to run for others.

**Comment by jedie** [comment]
I am also running into this issue.

@az0uz i deinstall poetry via get-poetry.py and install it via pip3 and then it worked. But it's currently not recommended, see: https://python-poetry.org/docs/#alternative-installation-methods-not-recommended :(

**Comment by finswimmer** [comment]
This should be no problem any longer, as we fall back to build the wheel package and extract the metadata from there if parsing the setup.py fails.
