### ISSUE TITLE
Add @generated to poetry.lock for Phabricator support

### ISSUE THREAD

**Issue by lovesegfault** [python-poetry/poetry#2034]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

The company I work at uses Phabricator internally, which in turn uses the `@generated` string to detected whether a file shouldn't be diffed due to being generated by a tool. Would it be possible to add a header with that text to `poetry.lock`?

I'll note that there is some precedent, at least in Rust's Cargo, to do this: https://github.com/rust-lang/cargo/issues/6180

**Comment by lovesegfault** [comment]
cc. @finswimmer @sdispater

**Comment by vishalkuo** [comment]
I'd be happy to tackle this if there's no traction
