### ISSUE TITLE
[AttributeError] "Call" object has no attribute "id"

### ISSUE THREAD

**Issue by Prakashvanapalli** [python-poetry/poetry#2038]
- [x ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 16.04
- **Poetry version**: 1.0.3

The following command is throwing error
```
pip add -vvv git+https://github.com/Prakashvanapalli/mmdetection.git 
```

error:

```
[AttributeError]
'Call' object has no attribute 'id'
```

In the debug mode, I see the following changes have been made from [1.0.2 to 1.0.3](https://github.com/python-poetry/poetry/commit/945ca1d365d66489858e05b4b50d06e579af56ba#diff-f5ad95b60af5a28873167edf20f99c87) 

- previously it was 

```python
if not isinstance(func, ast.Name):
    continue 
if func.id != "setup":
    continue
```
- Now it was 

```python
if not (isinstance(func, ast.Name) and func.id == "setup") and not (
    isinstance(func, ast.Attribute)
    and func.value.id == "setuptools"
    and func.attr == "setup"
):
    continue
```

when I changed the code to the old version. the installation is working fine. May I know why is this problem occurring?

**Comment by finswimmer** [comment]
Thanks a lot for reporting. :+1: 

Fix is on the way: #2041
