### ISSUE TITLE
Automatically execute `poetry install` if venv doesn't exist

### ISSUE THREAD

**Issue by jmcs** [python-poetry/poetry#2039]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request
(this might be partially related with #75)
When I clone a repository that uses poetry and try to use `poetry run...` without running `poetry install` first, it (usually) fails because the new Virtual Environment doesn't have the necessary dependencies.

I think poetry automatically run `install` after creating the Virtual Environment in this case.

**Comment by motin** [comment]
Workaround: Replace your `poetry run ...` with `poetry install && poetry run ...`. This adds <1s runtime and has the desired behavior: The venv is created with the relevant dependencies in case it doesn't exist.

**Comment by neersighted** [comment]
I'm skeptical this is desired as a stand-alone feature -- as described, it introduces inconsistency as `poetry install` is necessary after an install when the pyproject.toml is edited, but not if the install was never performed. This is rather surprising and magical. I think that this should be considered a specialized variant of #75 instead.
