### ISSUE TITLE
pip check fails because of the importlib-metadata version

### ISSUE THREAD

**Issue by sobolevn** [python-poetry/poetry#2042]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: 
- **Poetry version**: 1.0.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://github.com/wemake-services/wemake-django-template/blob/b4102849daf420bc3a6af673ff5cfd8af9a70835/%7B%7Bcookiecutter.project_name%7D%7D/pyproject.toml

When installing `poetry` with `pip install` inside the Docker container, `pip check` command fails.
Dockerfile: https://github.com/wemake-services/wemake-django-template/blob/master/%7B%7Bcookiecutter.project_name%7D%7D/docker/django/Dockerfile

Current solution is to limit the `importlib-metadata` version to `<1.2.0,>=1.1.3` in `pyproject.toml`

But, I guess the full solution is to remove version restriction from `poetry`'s side.

**Comment by abn** [comment]
@sobolevn does this still happen with 1.0.5 in your environment?

**Comment by sobolevn** [comment]
Yes, this still happens:

```
poetry 1.0.5 has requirement importlib-metadata<1.2.0,>=1.1.3; python_version < "3.8", but you have importlib-metadata 1.6.0.
```

**Comment by gregelin** [comment]
@abn Bumping this version because I am having the same issues as @sobolevn.

**Comment by finswimmer** [comment]
At the moment the version for `importlib-metadata` is fixed to `~1.1.3`. I guess we can set it to `^1.1.3`, can we @sdispater ?

**Comment by sobolevn** [comment]
Maybe even `>=1.1.3`?

**Comment by finswimmer** [comment]
Hello,

in the current preview release (1.1.0b3) the importlib-metadata dependency is defined as `importlib-metadata = {version = "^1.6.0", python = "<3.8"}`.

So this issue should be fixed.

fin swimmer
