### ISSUE TITLE
Tab completion with Prezto (Zsh)

### ISSUE THREAD

**Issue by jayBana** [python-poetry/poetry#2048]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Issue
Did anyone manage to get tab completion working with [Prezto](https://github.com/sorin-ionescu/prezto) for ZSH? If so, please advise.

Is there a Prezto plugin for it?

**Comment by Palisand** [comment]
```shell
poetry completions zsh > ~/.zprezto/modules/completion/external/src/_poetry
```
worked for me.
