### ISSUE TITLE
Add OAuth support for repositories on Google Cloud Storage

### ISSUE THREAD

**Issue by lorddaedra** [python-poetry/poetry#2053]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request
Add OAuth support for repositories on Google Cloud Storage

I would like to generate .whl's and static html files compatible with PEP 503 on CI after library test stage. I upload them to Google Cloud Storage. They are available at https://storage.googleapis.com/some-repo/simple/.

I would like make repository private and read-only for developers (and read/write for CI). But I must teach poetry how to use OAuth or create basic auth to OAuth proxy...

I can use nginx or Caddy as proxy and use Google Cloud Run (or may be adapt Google Cloud Functions) but fixing poetry looks better. 

I would like to add repository to poetry config and describe how to get token.

I can get my token via command `gcloud auth print-identity-token`.
And after that poetry should add `Authorization: Bearer <token>` to all requests...

This is how we can generate repository on Google Cloud Storage: https://github.com/donaldrauscher/gcs-pypi

**Comment by ralbertazzi** [comment]
Now Google has a dedicated [Artifact Registry](https://cloud.google.com/artifact-registry) service so I feel like the need to hack a repository out of GCS is not very relevant anymore.

Integration between Poetry and Artifact Registry is also quite easy:
1. Have Poetry >= 1.2
2. `poetry self add "keyrings.google-artifactregistry-auth"`
3. Being locally authenticated to GCP the usual way with `gcloud`
4. Have a Poetry source of this type
```toml
[[tool.poetry.source]]
secondary = true
name = "<choose-any-name>"
url = "https://<region>-python.pkg.dev/<project-id>/<repository>/simple/"
```

For maintainers reading this, it would be nice to have this documented somewhere!

**Comment by abn** [comment]
The original request is also now supported by poetry via https://python-poetry.org/docs/repositories/#simple-api-repository.
