### ISSUE TITLE
How to specifiy python version for virtualenv besides the default

### ISSUE THREAD

**Issue by codeman101** [python-poetry/poetry#2059]
- [x ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

I'm trying to install a dependency which is forcing python 3.6 (via ~3.6) and my default is python 3.7.5. I installed python 3.6.0 and I tried editing the toml file of my project where the python requirement is specified to be ~3.6. When that didn't work I tried rerunning `poetry init` and when I got to the python version prompt I wrote ~3.6. Still the dependency failed to install and I couldn't find anything in the docs on how to resolve this (or here in the issues when I searched "specific python vitrualenv"

Does the need to use a specific python version force me to have manually create the virtualenv before running `poetry init`? I was under the impression that it's possible to do something like `poetry init --use python3.6(or the path to it though I hope not for cross compatibility sake (Windows/*nix)` but I don't see any docs on that kind of command.

**Comment by graphman65** [comment]
The version of python used by the virtualenv can be set using:
`poetry env use <python-version>` (eg. `poetry env use 3.7`)

Check #731 for more details.

**Comment by finswimmer** [comment]
This is described [here](https://python-poetry.org/docs/managing-environments/#switching-between-environments) as well.
