### ISSUE TITLE
Dependency not installed for pygit2

### ISSUE THREAD

**Issue by matteli** [python-poetry/poetry#2066]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **Ubuntu 19.10**: 
- **1.0.3**: 
- **https://gist.github.com/matteli/9239b9eab5120f1ff775031036246657**: 

## Issue

When i install [pygit2](https://pypi.org/project/pygit2/#files) with :
`poetry add pygit2`
pygit2 is installed but the dependency [cffi](https://pypi.org/project/cffi/#files) is not.

When i install pygit2 with pip, everything works fine.

Matthieu

**Comment by loudsquelch** [comment]
I have the same issue with Ubuntu 18.04 and Poetry 1.0.5.

**Comment by finswimmer** [comment]
Seems to be fixed.
