### ISSUE TITLE
Ctrl-C during interactive dependency selection breaks bash

### ISSUE THREAD

**Issue by gjoseph92** [python-poetry/poetry#2067]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS High Sierra 10.13.6, bash 3.2 (system)
- **Poetry version**: 1.0.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: N/A

## Issue

Likely very related to #1593.

If I interrupt (ctrl-c) while interactively selecting dependencies, no characters are echoed in the shell, and prompts show up on the same line when hitting Return. Blindly typing `reset` (as mentioned [here](https://github.com/python-poetry/poetry/issues/1503#issuecomment-547304090)) fixes things.

```bash
gabejoseph ~/proj/poetry-test3 $ poetry init

This command will guide you through creating your pyproject.toml config.

Package name [poetry-test3]:  
Version [0.1.0]:  
Description []:  
Author [Gabe Joseph <gabe@descarteslabs.com>, n to skip]:  
License []:  
Compatible Python versions [^3.6]:  

Would you like to define your main dependencies interactively? (yes/no) [yes] 
You can specify a package in the following forms:
  - A single name (requests)
  - A name and a constraint (requests ^2.23.0)
  - A git url (git+https://github.com/python-poetry/poetry.git)
  - A git url with a revision (git+https://github.com/python-poetry/poetry.git#develop)
  - A file path (../my-package/my-package.whl)
  - A directory (../my-package/)
  - An url (https://example.com/packages/my-package-0.1.0.tar.gz)

Search for package to add (or leave blank to continue): foobar
Found 20 packages matching foobar

Enter package # to add, or the complete package name if it is not listed: 
 [0] foobar
 [1] foobar2
 [2] duckietown-foobar
 [3] django-foobar
 [4] ModernGL.ext.foobar
 [5] pytest-check-mk
 [6] qoob
 [7] pyfoobar
 [8] sower
 [9] pyctrie
# I hit Ctrl-C here. Poetry exits, but the shell is then in a 'broken state'
 > gabejoseph ~/proj/poetry-test3 $ gabejoseph ~/proj/poetry-test3 $ gabejoseph ~/proj/poetry-test3 $ 
# ^ hitting return puts a new prompt on the same line. no characters are echoed when typing.
```

**Comment by finswimmer** [comment]
Fixed on cleo's side https://github.com/python-poetry/cleo/pull/240
