### ISSUE TITLE
Allow self update for user prefixed installs

### ISSUE THREAD

**Issue by ocehugo** [python-poetry/poetry#2081]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: doens't matter
- **Poetry version**: 1.0.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: doesnt matter

## Issue
Poetry is not very smart. It can't handle self-updates when the poetry install folder is a prefix set by POETRY_HOME.

```bash
curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | POETRY_HOME=/tmp/my_poetry_prefix python
bash
poetry self update -vvv

[RuntimeError]
Poetry was not installed with the recommended installer. Cannot update automatically.

Traceback (most recent call last):
  File "/tmp/my_poetry_prefix/lib/poetry/_vendor/py3.6/clikit/console_application.py", line 131, in run
    status_code = command.handle(parsed_args, io)
  File "/tmp/my_poetry_prefix/lib/poetry/_vendor/py3.6/clikit/api/command/command.py", line 120, in handle
    status_code = self._do_handle(args, io)
  File "/tmp/my_poetry_prefix/lib/poetry/_vendor/py3.6/clikit/api/command/command.py", line 171, in _do_handle
    return getattr(handler, handler_method)(args, io, self)
  File "/tmp/my_poetry_prefix/lib/poetry/_vendor/py3.6/cleo/commands/command.py", line 92, in wrap_handle
    return self.handle()
  File "/tmp/my_poetry_prefix/lib/poetry/console/commands/self/update.py", line 65, in handle
    'Poetry was not installed with the recommended installer. '

```

maybe you guys can follow what pyenv do for custom prefixes?

**Comment by SylleoYr** [comment]
It seems that this issue hasn't been fixed yet? I met the same question in my Windows machine, but when I set the environment variable `POETRY_HOME` to my prefix setting permanently (not at installing the poetry), `poetry self update` works correctly.

- **Windows version**: Windows 10 2004 update (19041.450)
- **Poetry version**: 1.0.10

And I found that the `poetry` installer `get-poetry.py` doesn't set the environment variable `POETRY_HOME` automatically, thus I recommend adding this feature into the installer.

**Comment by sethwoodworth** [comment]
I started to add this feature to my installed poetry revision 1.0.10, got it working, and began creating a PR.  But I found that the master branch already implemented this feature:
https://github.com/python-poetry/poetry/blob/8b8b97a652178788bf5751ad8a372ceb161965be/poetry/console/commands/self/update.py#L65 as of this commit: https://github.com/python-poetry/poetry/commit/5e70eb8d1843c03d8e4bd812b4b18ba0ec52be4a#diff-c08f6677a8d9cc1f87cab1aecd7b8e56 in april

**Comment by sethwoodworth** [comment]
And I can confirm that the feature exists in version `1.1.0b2`.  Should this issue be closed when the feature leaves beta or should it be closed now?

**Comment by sethwoodworth** [comment]
duplicated of #1872
