### ISSUE TITLE
Feature: transform a feature into a dev feature

### ISSUE THREAD

**Issue by ValentinCalomme** [python-poetry/poetry#2082]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

First off, thanks for all the work on Poetry! This feature request is purely about usability

I believe I'm not the only one who added a dependency but forgot the `--dev` flag. At the moment, it seems that there are two options to fix this:

- remove and reinstall with the `--dev` flag
- modify `pyproject.toml` manually and reinstall

It would be great if there was a single command-line option/flag which allows us to move a dependency from/to dev. Or perhaps, there is a third option I am not aware of?

**Comment by finswimmer** [comment]
Hello,

there's no need to reinstall after modifying the `pyproject.toml`. Just run a `poetry lock --no-update` afterwards, to notify the lock file, that the dependency is now a dev dependency.

fin swimmer
