### ISSUE TITLE
Local package install is slow due to creation of temporary virtual environments

### ISSUE THREAD

**Issue by iwanb** [python-poetry/poetry#2083]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **Fedora 30**: 
- **1.0.3**: 

## Issue

I have a project with quite a few local paths in the `pyproject.toml`:
```
mylib = {path = "libraries/mylib"}
```

With each path being a setuptools type of package (with `setup.py`, but it should also impact packages which simply do not use poetry).

With that, `poetry install --dry-run` takes very long because it creates a virtual env for each package to run `egg_info`. https://github.com/python-poetry/poetry/blob/6e053e5599acdf1e186a8853c6256646c56a4a7d/poetry/puzzle/provider.py#L293

That takes 2 extra seconds on my system per package.

Is it necessary to create a new virtual environment every time? Could there be at least a cached one per run? Or even just use the existing venv?

As a workaround I will try to port the packages to use poetry, then it seems it will only need to read the `pyproject.toml` file, but it seems the `egg_info` method should be made faster as well.

**Comment by iwanb** [comment]
Most of the time seems to be spent running `ensurepip`.

Maybe the created virtual environment could be cached, and then copied when a new one is needed?
The main issue is that AFAIK a virtual environment is not relocatable, it could only be cached for one path, or it needs some hacks to relocate it.

**Comment by iwanb** [comment]
Using `system_site_packages=True` instead of `with_pip=True` and assuming that `setuptools` and `pip` are available is another thing which speeds this up. I think poetry already assumes that pip is available, so it could be a reasonable solution. But it does not isolate the package setup as much.

**Comment by finswimmer** [comment]
There's not really something Poetry can do here. It needs to gather metadata. If it's possible Poetry tries to parse the `setup.py` for those information. If it cannot found it there, because they are dynamically, a wheel needs to be build to get those information from there. This build step happens in a clean environment.

**Comment by iwanb** [comment]
I understand the metadata is needed, but the current way to get it is (was?) not the most efficient way to do it.

I can't find any reference to `ensurepip`, so I suppose the implementation has been changed since the issue was open. I haven't recently tested if the slowness is still there or not.

**Comment by neersighted** [comment]
Poetry used multiple methods to gather metadata, and building dependencies is a last resort. That being said, it cannot be avoided in some cases depending on the type of distfiles available. See `inspection.py` for the implementation.
