### ISSUE TITLE
cannot import name create_environment with virtualenv >= 20

### ISSUE THREAD

**Issue by cjw296** [python-poetry/poetry#2093]
- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [ ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **Poetry version**: 1.0.3
- **pyproject.toml file**: https://github.com/cjw296/carly/blob/master/pyproject.toml

## Issue

virtualenv 20 was released earlier this month, and looks like CircleCI's images were just rebuilt to use it. So, now, on Python 2, `poetry install` fails as follows:

```
circleci@32ce45b8e19b:~/project$ poetry install -v
Creating virtualenv carly-3aSsmiER-py2.7 in /home/circleci/.cache/pypoetry/virtualenvs

[ImportError]
cannot import name create_environment

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/clikit/console_application.py", line 131, in run
    status_code = command.handle(parsed_args, io)
  File "/usr/local/lib/python2.7/site-packages/clikit/api/command/command.py", line 120, in handle
    status_code = self._do_handle(args, io)
  File "/usr/local/lib/python2.7/site-packages/clikit/api/command/command.py", line 163, in _do_handle
    self._dispatcher.dispatch(PRE_HANDLE, event)
  File "/usr/local/lib/python2.7/site-packages/clikit/api/event/event_dispatcher.py", line 22, in dispatch
    self._do_dispatch(listeners, event_name, event)
  File "/usr/local/lib/python2.7/site-packages/clikit/api/event/event_dispatcher.py", line 89, in _do_dispatch
    listener(event, event_name, self)
  File "/usr/local/lib/python2.7/site-packages/poetry/console/config/application_config.py", line 89, in set_env
    env = env_manager.create_venv(io)
  File "/usr/local/lib/python2.7/site-packages/poetry/utils/env.py", line 610, in create_venv
    self.build_venv(str(venv), executable=executable)
  File "/usr/local/lib/python2.7/site-packages/poetry/utils/env.py", line 674, in build_venv
    from virtualenv import create_environment
```

The most pragmatic solution, at this point, is to have poetry pin the virtualenv it uses to `<20`, or just vendor it, since realistically, it's only going to be used on Python 2, right?

**Comment by finswimmer** [comment]
Hey @cjw296,

could you please test if #2096 fixes this problem?

fin swimmer

**Comment by cjw296** [comment]
Not easily, how would you recommend I do that?

**Comment by sdispater** [comment]
@cjw296 I don't understand how you end up with `virtualenv >20` since Poetry restricts the `virtualenv` version: https://github.com/python-poetry/poetry/blob/master/pyproject.toml#L49. So there must be something wrong with your environment.

**Comment by Drarok** [comment]
@sdispater I'm also a user of CircleCI and seeing the same issue. CircleCI appear to pre-install poetry on their image, but have also upgraded the system `virtualenv` to 20. 😕

**Comment by cjw296** [comment]
Here's the relevant bit of their Dockerfile:
https://github.com/CircleCI-Public/circleci-dockerfiles/blob/master/python/images/2.7.17/Dockerfile#L95

**Comment by cjw296** [comment]
I wonder where pip is coming from and what version it is? Maybe @felicianotech can help with this?

**Comment by cjw296** [comment]
Where do we find the docker file for the upstream Python image?
