### ISSUE TITLE
get_vcs fails if git is not installed

### ISSUE THREAD

**Issue by jr314159** [python-poetry/poetry#2107]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 16.04
- **Poetry version**: 1.0.4
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/jr314159/55e9fbf3dc3ed7166d2026132cd2d639

## Issue
I am using poetry with tox.  This commit breaks tox+poetry in an environment where git is not installed.  https://github.com/python-poetry/poetry/commit/ab66bb9d5c278ec1645fea5bc3205c5e4b11d6b4

Reverting to version 1.0.3 solves the issue.

My tox.ini looks like this:
```
[tox]
isolated_build = true
envlist = py37

[testenv]
deps = poetry
commands =
    poetry install -v
    poetry run pytest -s --doctest-modules
```

**Comment by funkyfuture** [comment]
i think poetry shouldn't depend on an expected binary, but rather use [dulwich](https://www.dulwich.io/) or another Python library.

**Comment by jr314159** [comment]
Ah looks like https://github.com/python-poetry/poetry/pull/2105 will resolve this once merged

**Comment by Jihadik** [comment]
I tried Poetry 1.0.5 and it didn't help. I don't have a .git repository and Poetry fails
```
Installing dependencies from lock file

[FileNotFoundError]
[Errno 2] No such file or directory: 'git': 'git'
```
