### ISSUE TITLE
"Unable to detect the current shell." when running Vagrant command

### ISSUE THREAD

**Issue by dms-cat** [python-poetry/poetry#2115]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 18.04
- **Poetry version**: 1.0.5
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/dms-cat/651c4fe2e55a83984b6cdb436eb102a1

## Issue

`vagrant ssh default --command='poetry shell'` fails with

> Unable to detect the current shell.

If I instead run `vagrant ssh default` and then `poetry shell` it works fine.

I've also tried variants like `vagrant ssh default --command='bash -ic "poetry shell"'` with the same result.

**Comment by sambonner** [comment]
It looks the maintainer of Shellington [recommends providing a default shell as a fallback](https://github.com/sarugaku/shellingham#notes-for-application-developers). Is there a reason why this was not implemented for Poetry?

**Comment by finswimmer** [comment]
Hello @sambonner,

thanks a lot for reporting and linking to a possible solution.

Fix is on the way: #2147 

fin swimmer

**Comment by johannesgiani** [comment]
@dms-cat can you provide an example vagrant file of how you provision poetry? I am stuck here.
