### ISSUE TITLE
Peotry leaves POETRY_ACTIVE set after deactivate

### ISSUE THREAD

**Issue by mosesontheweb** [python-poetry/poetry#2131]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 18.04.4 LTS
- **Poetry version**: 1.0.5
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue
I just switched from pipenv to poetry and it looks pretty awesome. One thing I recognized is that whenever I switch to a shell-mode and deactivate it again, Poetry leaves the environment variable `POETRY_ACTIVE=1` back in the settings. With this it's not possible to enter any shell mode again.

Workaround:
- close the terminal and start a new one (of course)
- `unset POETRY_ACTIVE` (nicer)

Regards, Thomas

**Comment by finswimmer** [comment]
Hello @mosesontheweb,

`poetry shell` spawns a new shell and activate the virtual environment. Saying this, a `deactivate` just closes the virtual environment but keeps you in the shell spawned by poetry.

You have to use `exit` instead.

fin swimmer
