### ISSUE TITLE
[RecursionError] maximum recursion depth exceeded while calling a Python object with Spyder-kernels

### ISSUE THREAD

**Issue by danieltomasz** [python-poetry/poetry#2133]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`` option).

- **OS version and name**: Mac Catalina darwin
- **Poetry version**: 1.0.5 
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue
```
poetry add -D spyder-kernels
Using version ^1.8.1 for spyder-kernels

Updating dependencies
Resolving dependencies... (41.1s)

[RecursionError]
maximum recursion depth exceeded while calling a Python object
```

I was able to pinpoint problem to this
```
Duplicate dependencies for ipykernel
   0: Different requirements found for ipykernel (*) and ipykernel (>=5.1.3).
   1: Version solving took 0.029 seconds.
   1: Tried 1 solutions.
   0: Retrying dependency resolution for Python (>=3.8,<4.0).
```

which was caused by `spyder-kernels`requirements
```

REQUIREMENTS = [
  ...
    'ipykernel',
    'ipykernel>=5.1.3; python_version>"2"',
  ...
]
```

after  removing  first `ipykernel` I was able to install spyder-kernels from my fork

**Comment by abn** [comment]
Fixed in `1.1.0b2`.
