### ISSUE TITLE
Add support for subversion Dependencies?

### ISSUE THREAD

**Issue by berhoel** [python-poetry/poetry#2141]
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

pip allows for subversion depencies in the same way as for git dependencies. poetry supports git only. Is there anyone else who would like subversion support for dependencies in poetry?

**Comment by dimbleby** [comment]
slightly surprising to me that anyone wanted this as recently as 2020: with each passing day it is surely becoming less relevant...

Anyway this seems to have attracted on enthusiasm: suggest it's time to acknowledge that this is not planned, and close it out.

**Comment by Secrus** [comment]
Closing, as there doesn't seem to be that much need for this feature.
