### ISSUE TITLE
ResourceWarning: unclosed socket

### ISSUE THREAD

**Issue by kbaikov** [python-poetry/poetry#2153]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Issue

If i run python with warnings enabled (set the env var `PYTHONWARNINGS="default"` ), and try to do `poetry update` or any remote connection related operation i get the following message:
```bash
C:\Users\<username>\.poetry\lib\poetry\console\application.py:54: ResourceWarning: unclosed <ssl.SSLSocket fd=868, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('157.163.199.78', 57798), raddr=('151.101.192.223', 443)>
  self._poetry = None
ResourceWarning: Enable tracemalloc to get the object allocation traceback
```

Poetry version 1.0.5
Python 3.8.2 x64
Windows 10

Update: added the fuller message with the location of the warning in code: `C:\Users\<username>\.poetry\lib\poetry\console\application.py:54:`

**Comment by kbaikov** [comment]
Ping @stephsamson 
Any activity on this bug?

**Comment by ShahriyarR** [comment]
The same warning I got while doing:

```
$ poetry install
Updating dependencies
Resolving dependencies... (0.4s)/home/shako/.poetry/lib/poetry/repositories/pypi_repository.py:207: ResourceWarning: unclosed <ssl.SSLSocket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('192.168.1.57', 50624), raddr=('151.101.64.223', 443)>
  data = self._get("pypi/{}/json".format(name))
ResourceWarning: Enable tracemalloc to get the object allocation traceback
```

**Comment by kbaikov** [comment]
Works for me with Poetry (version 1.2.0a2) and Python 3.10
