### ISSUE TITLE
Duplicated package websockets in poetry.lock and requirements.txt

### ISSUE THREAD

**Issue by snguyenthanh** [python-poetry/poetry#2165]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS 10.14.6
- **Poetry version**: 1.0.5
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/snguyenthanh/34a4fd230c2e1e4141680f2cccf1660d

## Issue

The dependency `websockets` is duplicated in `poetry.lock` and `requirements.txt` from command `export`.

The command used to `export` requirements.txt
```
poetry export -f requirements.txt --dev --without-hashes > requirements.txt
```

The output `requirements.txt`:
```
aiocache==0.11.1
aiofiles==0.4.0
aioredis==1.3.1; python_version < "3.7" or python_version >= "3.7"
aiosqlite==0.11.0
async-timeout==3.0.1; python_version < "3.7" or python_version >= "3.7"
attrs==19.3.0
cattrs==1.0.0
click==7.1.1
h11==0.9.0
hiredis==1.0.1
httptools==0.1.1; sys_platform != "win32" and sys_platform != "cygwin" and platform_python_implementation != "PyPy"
python-multipart==0.0.5
six==1.14.0
starlette==0.13.2
ujson==1.35
uvicorn==0.11.3
uvloop==0.14.0; sys_platform != "win32" and sys_platform != "cygwin" and platform_python_implementation != "PyPy" or implementation_name != "pypy" and platform_system != "Windows"
websockets==8.0.2
websockets==8.1
```

As you can see, the package `websockets` at the end of the file has two different versions, which causes `virtualenv` and `pip` to raise an exception:
```
>>> pip install -r requirements.txt
Ignoring atomicwrites: markers 'sys_platform == "win32"' don't match your environment
Ignoring colorama: markers 'sys_platform == "win32"' don't match your environment
Double requirement given: websockets==8.1 (from -r /home/travis/build/gianghta/Lisa/requirements/dev.txt (line 51)) (already in websockets==8.0.2 (from -r /home/travis/build/gianghta/Lisa/requirements/dev.txt (line 50)), name='websockets')
```

More details of the Travis job can be found [here](https://travis-ci.com/gianghta/Lisa/jobs/296433227).

**Comment by finswimmer** [comment]
Hello @snguyenthanh,

thanks a lot for reporting.

It looks like this was reported earlier in #1970. This is why I close yours. If you disagree, please leave a comment.

fin swimmer
