### ISSUE TITLE
Add --only-root option for install command.

### ISSUE THREAD

**Issue by jancespivo** [python-poetry/poetry#2166]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

It would be nice if the `--only-root` option for install command will be introduced. We have a use-case with the multistage docker build. At first, we install dependencies with `--no-root` option because dependencies are not changing so often. During the second stage, we would like to install only the application. Unfortunately, there are some git dependencies so the second stage requires git installed even no dependencies are finally installed.

**Comment by brettdh** [comment]
Also interested in this feature. I have a similar multistage build, with the added constraint that the second stage has no network connectivity, so as to isolate the parts of the build that depend on external data. We could remove `--no-root` from the first-stage installation, but this would require moving build steps to the first stage as well, which defeats the purpose of them taking place in a second, isolated environment. Current workaround is to run `poetry install` during the second stage as well - which works, as long as the venv has not changed between the stages - but it makes me uneasy that I can't explicitly say "only install the root package".

**Comment by elliott-imhoff** [comment]
I'd like to add support for this feature.  I have repos with C++ extensions I need to edit and rebuild while developing.  Right now, the only way for me to do so is rerun ``poetry install`` after making changes to the C++ code, which then leads to poetry trying to reinstall all dependencies.  Some of these dependencies include git repos that have C extensions of their own for which I need to wait for everything to clone and rebuild.  Being able to just rebuild the root package I'm working on would drastically speed up my development cadence.

**Comment by hjwp** [comment]
Curious if anyone has found a manual workaround for this?  is there a way to use `pip install -e` or similar to install the packages specified in tool.poetry.packages in pyproject.tom?  maybe by duplicating that info somehow?

**Comment by sh-at-cs** [comment]
This seems to have been implemented recently in #5783.

**Comment by radoering** [comment]
Resolved by #5783
