### ISSUE TITLE
Unable to retrieve the package version

### ISSUE THREAD

**Issue by leibowitz** [python-poetry/poetry#2175]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS Catalina 10.15.2
- **Poetry version**: 1.0.5
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.githubusercontent.com/leibowitz/ac9f42e0b3925ca7d01f81e26f3bb292/raw/009eef68c7527d486b4538a60503cbdaea3b0a1a/pyproject.toml

## Issue

I am trying to install a package from a git repository (because I had to fork the original package, and I haven't published it to pypi) with:

```sh
poetry add git+https://github.com/carlospalol/django-moneyfield.git
```

But I get the following error:

> [RuntimeError]
> Unable to retrieve the package version for /var/folders/5f/134_dwks64jfppffv26mvkbr0000gn/T/pypoetry-git-django-moneyfieldrvmFVf

The package is [django-moneyfield](https://pypi.org/project/django-moneyfield/), and the [`setup.py`](https://github.com/carlospalol/django-moneyfield/blob/master/setup.py) is using `setup` from `distutils`:
```python
from distutils.core import setup
```

This seems to be the issue, as any package I try to install in this way (using the git repository url) which has this import seems to fail with the same error.

Using `poetry -vvv` return the traceback, in case it is useful:
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/site-packages/clikit/console_application.py", line 131, in run
>     status_code = command.handle(parsed_args, io)
>   File "/usr/local/lib/python2.7/site-packages/clikit/api/command/command.py", line 120, in handle
>     status_code = self._do_handle(args, io)
>   File "/usr/local/lib/python2.7/site-packages/clikit/api/command/command.py", line 171, in _do_handle
>     return getattr(handler, handler_method)(args, io, self)
>   File "/usr/local/lib/python2.7/site-packages/cleo/commands/command.py", line 92, in wrap_handle
>     return self.handle()
>   File "/usr/local/lib/python2.7/site-packages/poetry/console/commands/add.py", line 89, in handle
>     packages, allow_prereleases=self.option('allow-prereleases')
>   File "/usr/local/lib/python2.7/site-packages/poetry/console/commands/init.py", line 293, in _determine_requirements
>     requires = self._parse_requirements(requires)
>   File "/usr/local/lib/python2.7/site-packages/poetry/console/commands/init.py", line 381, in _parse_requirements
>     "git", url.url, reference=pair.get("rev")
>   File "/usr/local/lib/python2.7/site-packages/poetry/puzzle/provider.py", line 204, in get_package_from_vcs
>     package = cls.get_package_from_directory(tmp_dir, name=name)
>   File "/usr/local/lib/python2.7/site-packages/poetry/puzzle/provider.py", line 345, in get_package_from_directory
>     directory
> 

Reading other issues, I can see some comments about installing setuptools, to allow parsing. This doesn't seem to help.
Reference: https://github.com/python-poetry/poetry/issues/673#issuecomment-441795522

Another one mention changing the `setup.py` to use setuptools. Is this the only potential solution I could try?
Reference: https://github.com/python-poetry/poetry/issues/835#issuecomment-573210764

I tried with python 3.7.4 (with `poetry add -vvv ...`), and got another error:
> [AttributeError]
> 'NoneType' object has no attribute 'group'

Not sure what this one is all about. Doesn't even seems related to this issue... Indeed, removing the `-vvv` argument (using `poetry add ...`) seems to work ?! Therefore, ignoring the `NoneType` error, it seems to be related to the python version.
Is this then related to https://github.com/python-poetry/poetry/issues/661?

Feel free to close if this is a duplicate issue of the above

**Comment by finswimmer** [comment]
Hello @leibowitz,

the issue is the same as explained in #673. poetry itself is running with python2. There there is no support for parsing the `setup.py`, which is necessary to receive the version number.

The only chance to get it work is to make sure poetry runs with python3.

fin swimmer

**Comment by leibowitz** [comment]
Did you mean it is a duplicate of https://github.com/python-poetry/poetry/issues/661?

**Comment by cyberbudy** [comment]
Have the same issue while installing this package https://github.com/preusx/python-chain-caller
Tried the last stable and prerelease versions

**Comment by finswimmer** [comment]
@cyberbudy this work for me with no problems with the latest pre-release (1.1.0b2)
