### ISSUE TITLE
Poetry cannot find the existing virtualenv

### ISSUE THREAD

**Issue by gorjanradevski** [python-poetry/poetry#2182]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS Mojave 10.14.6
- **Poetry version**: 1.0.5
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**:  N/A

## Issue

After updating to Poetry 1.0.5, Poetry cannot find the existing virtual environments for the projects, and instead creates a new ones. For example, in case a project has an existing virtual environment in `/Users/firstnamelastname/Library/Caches/pypoetry/virtualenvs/project-name-py3.7/`, after running any Poetry related command in the project directory such as `poetry add package_name`, Poetry creates a new virtual environment in `/Users/firstnamelastname/Library/Caches/pypoetry/virtualenvs/project-name-zFnHsez3-py3.7` and then executes the command. On the other hand, if I activate the existing virtual environment beforehand by running `source /Users/firstnamelastname/Library/Caches/pypoetry/virtualenvs/project-name-py3.7/bin/activate`, and the execute the commands, everything is working fine.

I am not sure whether this is a bug or something wrong with my modus operandi (I never activate the virtual environments I just run everything from inside the project directory as `poetry run python some_file.py`), but since it started occurring since updating I am submitting an issue. Please feel free to close it/add a different label if needed.

Thank you for your time!

**Comment by finswimmer** [comment]
Hello @gorjanradevski,

the naming schema for the virtual env's has changed in poetry 1.0 and there is no automatic conversion. So poetry cannot find the old env and creates a new one.

This was one of the breaking changes with the 1.0 release.

fin swimmer
