### ISSUE TITLE
Poetry installation instructions do not work on system without /usr/bin/python

### ISSUE THREAD

**Issue by tzickel** [python-poetry/poetry#2183]
Since Ubuntu server has long dropped python 2 being default installed, and I think Ubuntu 20.4 (coming very soon) will too, the Installation instruction for poetry simply break, because the script thinks that you have /usr/bin/python:
```
curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
```
and the script itself starts with
```
#!/usr/bin/env python
```
Most users would not understand how to fix the problem (and the documentation does not talk about it):
```
https://python-poetry.org/docs/
```
Maybe an poetry3 script should be added (which does #!/usr/bin/env python3) and the documentation should state that an error on | python should to | python3 ?

Just skimming the first page of open issue, and I read this:
https://github.com/python-poetry/poetry/issues/1505#issuecomment-595209474
```
I edited the first line of ~/.poetry/bin/poetry to #!/usr/bin/env python3
```

**Comment by finswimmer** [comment]
Hello @tzickel,

this has been reported already earlier. See: https://github.com/python-poetry/poetry/issues/1877

fin swimmer
