### ISSUE TITLE
poetry command executed in python raise [UnicodeEncodeError]

### ISSUE THREAD

**Issue by leileigong** [python-poetry/poetry#2185]
- [ ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [ ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: 
- **Poetry version**: 
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## poetry command executed in python raise [UnicodeEncodeError]

i wanna to do deploy in python script. so i write an python script to auto execute poetry command.
like this deploy.py:
```py
import subprocess
exitcode, output = subprocess.getstatusoutput('poetry')
print("exitcoe=", exitcode)
if exitcode != 0:
    print("poetry error：{}".format(output))
```

then run python script on windows dos cmdline:
```
python.exe deploy.py
```

then i got this error:
```
exitcoe= 1
poetry error：Poetry version 1.0.5

USAGE

[UnicodeEncodeError]
'gbk' codec can't encode character '\xa0' in position 22: illegal multibyte sequence
```

**Comment by finswimmer** [comment]
Hello @leileigong,

in the code you've posted there is a strange character right after `poetry error`. Remove it if not neccessary or write this at the top of your file to tell python this file contains utf-8 characters:

```
# -*- coding: utf-8 -*-
```

fin swimmer

**Comment by leileigong** [comment]
@finswimmer i have use utf8 at the top of my python file and remove character **：**, but the this problem still exists.
i think the the exit code  of **exitcode, output = subprocess.getstatusoutput('poetry')** is number 1, mybe poetry execution gets someting wrong.

**Comment by leileigong** [comment]
@finswimmer 

non ascii charactor in the usage info.
poetry [-h] [-q] **[-v [<...>]]**

```
exitcoe= (0, 'Poetry version 1.0.5\n\nUSAGE\n  poetry [-h] [-q] [-v聽[<...>]] [-V] [--ansi] [--no-ansi] [-n] <command>\n         [<arg1>] ... [<argN>]\n\nARGUMENTS\n  <command>              The command to execute\n  <arg>                  The arguments of the command\n\nGLOBAL OPTIONS\n  -h (--help)            Display this help message\n  -q (--quiet)           Do not output any message\n  -v (--verbose)         Increase the verbosity of messages: "-v" for normal\n                         output, "-vv" for more verbose output and "-vvv" for\n                         debug\n  -V (--version)         Display this application version\n  --ansi                 Force ANSI output\n  --no-ansi              Disable ANSI output\n  -n (--no-interaction)  Do not ask any interactive question\n\nAVAILABLE COMMANDS\n  about                  Shows information about Poetry.\n  add                    Adds a new dependency to pyproject.toml.\n  build                  Builds a package, as a tarball and a wheel by default.\n  cache                  Interact with Poetry\'s cache\n  check                  Checks the validity of the\n                         pyproject.toml file.\n  config                 Manages configuration settings.\n  debug                  Debug various elements of Poetry.\n  env                    Interact with Poetry\'s project environments.\n  export                 Exports the lock file to alternative formats.\n  help                   Display the manual of a command\n  init                   Creates a basic pyproject.toml file in the\n                         current directory.\n  install                Installs the project dependencies.\n  lock                   Locks the project dependencies.\n  new                    Creates a new Python project at <path>.\n  publish                Publishes a package to a remote repository.\n  remove                 Removes a package from the project dependencies.\n  run                    Runs a command in the appropriate environment.\n  search                 Searches for packages on remote repositories.\n  self                   Interact with Poetry directly.\n  shell                  Spawns a shell within the virtual environment.\n  show                   Shows information about packages.\n  update                 Update the dependencies as according to the\n                         pyproject.toml file.\n  version                Shows the version of the project or bumps it when a\n                         valid bump rule is provided.\n')

```

**Comment by FGG100y** [comment]
@leileigong maybe it's the problem of console:
![py_poetry_gbk_encode_issue](https://user-images.githubusercontent.com/34432871/82637421-53b92b80-9c37-11ea-8a37-1e4b1eadb532.jpg)
this is in windows10 git-bash.
`poetry --help`
this command reported the same error message.

![py_poetry_gbk_encode_issue2](https://user-images.githubusercontent.com/34432871/82637485-73e8ea80-9c37-11ea-97f0-70940b69423e.jpg)
this is in windows10 Alacritty. And no error any longer.
