### ISSUE TITLE
command "poetry install" on pycharm shell can not dectect dependencies

### ISSUE THREAD

**Issue by leileigong** [python-poetry/poetry#2186]
- [ ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [ ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: 
- **Poetry version**: 
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## command "poetry install" on pycharm shell can not dectect dependencies

```py
exitcode = exitcode, output = subprocess.getstatusoutput('poetry install')
print("code=", exitcode)
print("output=", output)
```

pycharm terminal output:
```sh
FIRST INSTALL DENPEND:
code= 0
output= Installing dependencies from lock file

No dependencies to install or update


Process finished with exit code 0

```

But on windows dos shell.
Exceute deploy.py works fine.

**Comment by finswimmer** [comment]
Hey @leileigong,

I would guess the virtual environment is already installed. Do you have a `.venv` folder in the same folder as your `pyproject.toml`? If not, what's the output of `poetry env list --full-path`?

fin swimmer

**Comment by leileigong** [comment]
Hi @finswimmer 
I make sure that the virtual environment is not installed yet! 
I do not have **.venv** foldler in the same folder as my **pyproject.toml".

**Comment by finswimmer** [comment]
Hi,

what's the output of `poetry config --list`?

**Comment by leileigong** [comment]
the output on pycharm shell is the same as windows dos command shell.
```
cache-dir = "C:\\Users\\lei\\AppData\\Local\\pypoetry\\Cache"
virtualenvs.create = true
virtualenvs.in-project = false
virtualenvs.path = "{cache-dir}\\virtualenvs"  # C:\Users\lei\AppData\Local\pypoetry\Cache\virtualenvs
```

**Comment by finswimmer** [comment]
Closing this because we haven't received more information for a long time.

Feel free to leave a comment if you disagree.
