### ISSUE TITLE
SSH dependency does not work

### ISSUE THREAD

**Issue by slhck** [python-poetry/poetry#2189]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**:  Ubuntu 19.10
- **Poetry version**: 1.0.5
- **Gist**: https://gist.github.com/slhck/b4f71a266984049a063c16348f3d7cbf

## Issue

I cannot use the `git+ssh://...` syntax for specifying a private repository requirement. When I try adding it, I get:

```
➜ poetry add ssh://git@github.com:slhck/ffmpeg-bitrate-stats.git

[ValueError]
Could not parse version constraint: //git@github.com:slhck/ffmpeg-bitrate-stats.git
```

When I want to install it, I get:

```
➜ poetry install
Updating dependencies
Resolving dependencies... (0.0s)

[CalledProcessError]
Command '['git', 'clone', 'ssh://git@github.com:slhck/ffmpeg-bitrate-stats.git', '/tmp/pypoetry-git-ffmpeg-bitrate-statsllzoo8d6']' returned non-zero exit status 128.
```

This specification is valid for `requirements.txt` and is needed to resolve private keys before installation.

Also, the solution suggested here (https://github.com/python-poetry/poetry/issues/1964#issuecomment-580803549) does not work:

```
➜ poetry add git+ssh://git@github.com:slhck/ffmpeg-bitrate-stats.git

Updating dependencies
Resolving dependencies... (0.0s)

[CalledProcessError]
Command '['git', 'clone', 'ssh://git@github.com:slhck/ffmpeg-bitrate-stats.git', '/tmp/pypoetry-git-ffmpeg-bitrate-stats8jwupxi9']' returned non-zero exit status 128.
```

**Comment by clintonroy** [comment]
try:
```
poetry add git+https://github.com/slhck/ffmpeg-bitrate-stats.git
```

which seemed to work for me. Replace the colon with a slash.

**Comment by slhck** [comment]
As mentioned, I need to use SSH in order to resolve the private key when accessing the repository. This is in an automated build step, and using HTTP credentials is not possib.e

**Comment by slhck** [comment]
This is weird. After setting up the project again and running the same command, adding the repo works:

```
➜ poetry add "git+ssh://git@github.com:slhck/ffmpeg-bitrate-stats.git"

Updating dependencies
Resolving dependencies... (3.1s)

Writing lock file


Package operations: 1 install, 0 updates, 0 removals

  - Installing ffmpeg-bitrate-stats (0.2.0 267a27d)
```

However, the repo specification in `pyproject.toml` is missing the SSH protocol specifier:

```
ffmpeg-bitrate-stats = {git = "git@github.com:slhck/ffmpeg-bitrate-stats.git"}
```

This means that it will actually not be able to use SSH/private keys when subsequently cloning/installing.

**Comment by finswimmer** [comment]
Hello @slhck,

the entry in the `pyproject.toml` looks good to me. poetry is able to recognize it as a ssh protocol.

Just try if you can successfully run `poetry install` after removing the venv and `poetry.lock`.

fin swimmer

**Comment by slhck** [comment]
Hey @finswimmer – that's true, it works now.

But pip, according to its documentation:

> currently supports cloning over git, git+http, git+https, git+ssh, git+git and git+file

So,  I thought I could use the explicit protocol specifiers. I guess that is not possible for the time being, as `ssh://` URLs (described here: https://git-scm.com/book/en/v2/Git-on-the-Server-The-Protocols) are not correctly parsed.
