### ISSUE TITLE
Config option to set Python version for Poetry

### ISSUE THREAD

**Issue by nihaals** [python-poetry/poetry#2190]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request
When I run `poetry debug info` when not in a venv or after running `poetry use system`, I get:
```
Poetry
Version: 1.0.5
Python:  2.7.10

Virtualenv
Python:         2.7.10
Implementation: CPython
Path:           NA
...
```
After looking at some bug reports it seems it gets this from `python`. It seems some packages expect `python` to be Python 2 and `python3` to be Python 3, meaning that changing the link for `python` could cause other problems. Having a config option to be able to set the system Python path could change both the Poetry Python version (which I believe will help bump the default Python version when installing so you don't get something like
```
The currently activated Python version 2.7.10 is not supported by the project (^3.8).
Trying to find and use a compatible version. 
Using python3 (3.8.2)
```
and the default Python version being accurate could help the system environment be more accurate).

**Comment by finswimmer** [comment]
With the new installer script `install-poetry.py` Poetry no longer use the activated python as the default python for new virtual environment. Instead it uses the one it was installed with.
