### ISSUE TITLE
Question: Is it possible to make a build without the dev dependencies?

### ISSUE THREAD

**Issue by berislavlopac** [python-poetry/poetry#2191]
I'm using Poetry to package a library, and every time when that library is installed all of the dev dependencies get installed as well even though they are not needed for the regular operation (for example, `mkdocs`. Have I missed something or is there no way to remove the dev dependencies when building a wheel -- just like one can specify `--no-dev` when installing? Thank you!

**Comment by finswimmer** [comment]
Hello @berislavlopac,

could please in more details what you have done? Devdependencies aren't included in the wheel or sdist produced by `poetry build`. So they should not be installed when installing these packages.

fin swimmer

**Comment by berislavlopac** [comment]
I don't think I've done anything special -- I simply do `poetry build` and `poetry publish` to PyPI. When I include the package in another project's `requirements.txt` and do `pip install -r requirements.txt` I can see that all the dev dependency for my package get installed as well.

The package in question is https://github.com/berislavlopac/pyotr so you can try it out yourself. Thank you!

**Comment by finswimmer** [comment]
Hey @berislavlopac,

`mkdoc` is listed in the `[tool.poetry.dependencies]` and `[tool.poetry.dev-dependencies]`. If it is really only needed for development you must remove id from the "normal" dependency list.

fin swimmer

**Comment by berislavlopac** [comment]
Oh indeed it is, I completely missed it! Thank you for catching this! :blush:
