### ISSUE TITLE
RuntimeError thrown when executing `poetry publish -r <name>` with environment variable `POETRY_REPOSITORIES_<NAME>` set

### ISSUE THREAD

**Issue by esciara** [python-poetry/poetry#2204]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: 10.15.3 Mac OS X
- **Poetry version**: 1.0.5
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/esciara/dfc058348e597f8586d4f678cc163182

## Issue
According to the [doc on using environment variables for configuration](https://python-poetry.org/docs/configuration/#using-environment-variables), I should be able to declare an alternative package repository to publish to by setting an environment variable of format `POETRY_REPOSITORIES_<NAME>` (like `POETRY_REPOSITORIES_MYREPO`).

However, when running the following commands:
```
$ export POETRY_REPOSITORIES_MYREPO=http://myrepo.url
$ poetry publish -r myrepo
```
The following error is thrown:
```
[RuntimeError]
Repository myrepo is not defined
```
This is due to the fact that the following code for storing the config
https://github.com/python-poetry/poetry/blob/754dbf80dc022b89974288cff10b40ab2f1c2697/poetry/console/commands/config.py#L168-L170
transforms `"repositories.<name>"` into `"repositories.<name>.url"`, and the following code for publishing
https://github.com/python-poetry/poetry/blob/754dbf80dc022b89974288cff10b40ab2f1c2697/poetry/masonry/publishing/publisher.py#L51-L56
looks for `"repositories.<name>.url"`.

However, the code handling environment variables (in the `poetry.config.config.Config.get` method) does not treat the `POETRY_REPOSITORIES_<NAME>` environment variables in any particular way, and hence presents with an equivalent to `"repositories.<name>"`, not `"repositories.<name>.url"`:
https://github.com/python-poetry/poetry/blob/754dbf80dc022b89974288cff10b40ab2f1c2697/poetry/config/config.py#L109-L115

## Workaround
A workaround to this is to add `_URL` as a suffix to the variables (here `POETRY_REPOSITORIES_MYREPO_URL`), but this does not follow the simple and elegant rule for setting poetry though environment variables as defined in the doc.

## Corrective options
There are several way this could be corrected:

*Option 1: change the config setting `repositories.<name>` to `repositories.<name>.url`*

* Pros: 
   * does not change current way the settings are stored
   * backwards compatibility for existing scripts (ci/cd and other automation) could be kept by allowing the usage of `repositories.<name>`
* Cons:
   * the addition of `.url` does not seem to make much sens - appart perhaps for config file readability, which IMHO is questionable - since there is no other setting required to repositories than their url
   * backward compatibility fix feels a bit like a dirty hack

*Option 2: change the config setting storage from `repositories.<name>.url` to `repositories.<name>`*

* Pros: 
   * removes the use of `.url`
   * backwards compatibility for existing configuration files could be kept by looking also for `repositories.<name>.url` when searching for `repositories.<name>`
* Cons:
   * backward compatibility fix feels a bit like a dirty hack, but is probably necessary to not break existing systems (unless an upgrade process is created)

*Option 3: apply to the environment variables the same transformation that that to the comfig setting (`POETRY_REPOSITORIES_<NAME>` transformed on the fly to the equivalent of `POETRY_REPOSITORIES_<NAME>_URL`)*

* Pros: 
   * keeps much of the code the same
   * no need for backward compatibility
* Cons:
   * does not remove the use of `.url`

Any preferred option? My personal vote goes as first best for option 2 with an upgrade process and as second best to option 3.

**Comment by janjagusch** [comment]
Thank you for the *excellent*  issue description. I encountered the same issue on Poetry 1.0.9 and you workaround worked like a charm.

**Comment by 4F2E4A2E** [comment]
For us it's working the following way :

* config: `poetry config repositories.acme http://localhost:8080/repository/acme-pypi/`
* config: `poetry config http-basic.acme <user> <password>`
* build: `poetry build`
* publish: `poetry publish -r acme`

_Poetry version 1.0.5_

**Comment by abn** [comment]
Most likely related: #2359 #2210

**Comment by spencercjh** [comment]
Had the same problem :sob:

**Comment by assuiedmilan** [comment]
I am sad to see that this is two years old and not fixed. I am having the same issue, trying to use `poetry publish -r <url> -u <username> -p <password>` to upload to a private repository and it just will not work

```
Repository is not defined

url = self._poetry.config.get("repositories.{}.url".format(repository_name))
```

Would be great to see it fixed soon, moving to twine in the meantime

**Comment by abn** [comment]
This is a documentation issue. The expected env var is `POETRY_REPOSITORIES_<NAME>_URL` for the url configuration.

#9121 should resolve documentation issue.
