### ISSUE TITLE
Poetry incorrectly resolves tensorflow-estimator

### ISSUE THREAD

**Issue by alkamid** [python-poetry/poetry#2205]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 18.04
- **Poetry version**: 1.0.5
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/alkamid/2656f56e095e1e6040637e13d06f7239

## Issue
`tensorflow==2.1.0` depends on `tensorflow-estimator`. This is the relevant output from `poetry lock -vvv`:
```
   1: fact: tensorflow (2.1.0) depends on tensorflow-estimator (>=2.1.0rc0,<2.2.0)   
   1: derived: tensorflow-estimator (>=2.1.0rc0,<2.2.0)
PyPI: 3 packages found for tensorflow-estimator >=2.1.0rc0,<2.2.0 
   1: selecting tensorflow-estimator (2.2.0rc0)  
```
`tensorflow-estimator==2.1.0` is available on PyPI (https://pypi.org/project/tensorflow-estimator/#history), so I'd expect `poetry` to select `2.1.0` rather than `2.2.0rc0`. Is this expected behaviour?

See https://github.com/tensorflow/tensorflow/issues/37525 for the issue it's causing.

**Comment by ClementWalter** [comment]
Same issue here. I would not expect that poetry select any release candidate package by default. Thanks

**Comment by charmasaur** [comment]
FYI I think the underlying issue here is https://github.com/python-poetry/poetry/issues/2271

**Comment by ClementWalter** [comment]
This issue as a real impact on tensorflowjs as `poetry add tensorflowjs` will resolve with `tensorflow-estimator==2.2.0rc0` which in turns make tf js unusable.

MWE:

```
pyenv virtualenv 3.6.9 test_tfjs
pyenv activate test_tfjs
poetry add tensorflowjs
python -c "import tensorflowjs"
```

**Comment by dimbleby** [comment]
Works as expected today  

(after tweaking the provided pyproject.toml to specify `tensorflow = "=2.1.0"`, then indeed poetry derives `tensorflow-estimator (>=2.1.0rc0,<2.2.0)`, but now it installs 2.1.0 as desired)

**Comment by mkniewallner** [comment]
Closing, since this appears to be fixed now.
