### ISSUE TITLE
How to create two virtual envs(python-64bit and python-32bit) for one project directory?

### ISSUE THREAD

**Issue by leileigong** [python-poetry/poetry#2213]
- [ ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## How to create two virtual envs(python-64bit and python-32bit) for one project directory?

Now i got such demand.

I hava one project, project directory name is myproject1.
I want to create two python virtual envs, one is python3 with 64bit, another is python3 with 32bit.

**I want to dist an exe for x86_64 OS, so use python3 [64 bit] .
and also dist an exe for x86 OS, so  use python3 [32 bit] .**

could i create two **pyproject.toml** files or two **poetry.lock** files, control two python versions.
thus i can create two python virual envs for the same project.
i can choose any virtual envs according the python version.

**Comment by meakbiyik** [comment]
As far as I understand this is not under the scope of poetry, but you can achieve your goal using conda and creating two different environments, one with `CONDA_FORCE_32BIT=1` and one without. Then using the same pyproject.toml, `poetry install` command will use the activated environment's pip (whether 32-bit or 64-bit) and install the appropriate dependencies.

**Comment by leileigong** [comment]
@meakbiyik 
thanks your tip.  Does not  `poetry install`  use the environment which `poetry init` creates?

**Comment by meakbiyik** [comment]
If no environment is active, `poetry install` looks at the directory first to find a .venv folder, and tries to use that. If an environment is already active, `poetry install` directly uses that --it has no memory of already created environments.

**Comment by stephsamson** [comment]
@meakbiyik is correct. More information on how Poetry manages environments can be found in the [docs](https://python-poetry.org/docs/managing-environments/).

@leileigong I will be closing this issue and would invite you to ask further questions on either the [Discord server](https://discord.gg/23CxY5) or [StackOverflow](https://stackoverflow.com/tags/python-poetry/info).
