### ISSUE TITLE
Why does poetry resolve a RC version for tensorflow-estimator?

### ISSUE THREAD

**Issue by zachmoshe** [python-poetry/poetry#2219]
There seems to be a difference in the resolved dependencies between `pip` and `poetry` when I try to install `Tensorflow==2.1`:

WIth `pip`:
```
$ pip install tensorflow==2.1
...
$ pip freeze | grep tensorflow-estimator
tensorflow-estimator==2.1.0
```
(as expected)

With `poetry`:
```
$ poetry init
$ poetry add tensorflow==2.1
$ poetry run pip freeze | grep tensorflow-estimator
tensorflow-estimator==2.2.0rc0
```

Why is that? Why is poetry resolving the dependency with the RC version of 2.2?

Down the line, this causes me a problem where the installed `tensorflow-estimator` version doesn't match TF's requirement:
`tensorflow==2.1.0 requires tensorflow-estimator<2.2.0,>=2.1.0rc0 but tensorflow-estimator 2.2.0rc0 was resolved`

**Comment by HalCooper** [comment]
Also having this issue. Temporarily resolving it by pinning the version of tensorflow-estimator. Would prefer this not be necessary.

**Comment by finswimmer** [comment]
Hello,

thanks a lot for reporting. However this was reported earlier in #2205. So I will close this here as a duplicate.

fin swimmer
