### ISSUE TITLE
poetry export -f requiretments.txt exports git dependencies as editable

### ISSUE THREAD

**Issue by retrry** [python-poetry/poetry#2220]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS 10.15
- **Poetry version**: 1.0.5
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/retrry/da92d547e30b57dda8f7252b033dcf03

## Issue

Poetry exports git dependencies as editable (-e), when exporting with poetry export -f requirements.txt

Result:
```
-e git+https://github.com/sdispater/cleo.git@9a1ccc785838e3ab8737ee17bbc00d66c2796eef#egg=cleo
clikit==0.4.3
pastel==0.2.0
pylev==1.3.0
```

Expected:
```
git+https://github.com/sdispater/cleo.git@9a1ccc785838e3ab8737ee17bbc00d66c2796eef#egg=cleo
clikit==0.4.3
pastel==0.2.0
pylev==1.3.0
```

**Comment by finswimmer** [comment]
Hello @retrry,

git dependencies are currently installed in editable mode. So the export with `-e` is correct. There is already a feature request (https://github.com/python-poetry/poetry/issues/1816) and a corresponding PR (https://github.com/python-poetry/poetry/pull/1810) to be able to change the behavior.

fin swimmer
