### ISSUE TITLE
 poetry add djoser Using version ^2.0.3 for djoser  Updating dependencies Resolving dependencies...  [PackageNotFound] Package djoser (2.0.3) not found.

### ISSUE THREAD

**Issue by hian18** [python-poetry/poetry#2224]
- [ ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [ ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: 
- **Poetry version**: 
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**:

**Comment by hian18** [comment]
poetry add djoser
Using version ^2.0.3 for djoser

Updating dependencies
Resolving dependencies...

[PackageNotFound]
Package djoser (2.0.3) not found.

**Comment by simion** [comment]
Maybe duplicate of https://github.com/python-poetry/poetry/issues/2223

**Comment by finswimmer** [comment]
Yes, it's a duplicate of #2223.
