### ISSUE TITLE
Poetry stuck at using virtualenv for new project

### ISSUE THREAD

**Issue by timbmg** [python-poetry/poetry#2227]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS 10.15.3 
- **Poetry version**: 1.0.5
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/timbmg/2435eb6f42de90c6b4ffc4aebc1bf648

## Issue
I created a new project like this:
```
poetry new test
Created package test in test
cd test
poetry add numpy -vvv
Creating virtualenv test-8n5DPpuh-py3.7 in /Users/<username>/Library/Caches/pypoetry/virtualenvs
Using virtualenv: /Users/<username>/Library/Caches/pypoetry/virtualenvs/test-8n5DPpuh-py3.7
```

But it seems poetry is stuck at this point. The virtual environment was created, but nothing ever gets added to the .toml file. Also, poetry install does never finish solving the dependencies, although there aren't any.

**Comment by gcoakes** [comment]
Why was this closed? I'm experiencing nearly the same symptoms. It seems to work, but just take a ridiculously long time. This happens for both `poetry install` and `poetry add`.
