### ISSUE TITLE
System-wide Poetry Installation

### ISSUE THREAD

**Issue by ketozhang** [python-poetry/poetry#2237]
**Current Behavior:**
The following install poetry to `$HOME/.poetry/bin`

```sh
curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python 
```

**Desired Behavior:**
I have some use cases (may or may not be a good idea) where I'd like to have poetry to be available system wide (e.g., in `/usr/bin`).

Case for me is, I have many members on the same server that may edit the same project folder where poetry is used. Having all those members and newcomers install poetry individually seems cumbersome.

**Comment by finswimmer** [comment]
Hello @ketozhang ,

you can change the install directory by setting the environment variable `POETRY_HOME` before installing, e.g.:

```
POETRY_HOME=/opt/poetry/ curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python 
```
This is mentioned in the [docs](https://python-poetry.org/docs/)

fin swimmer

**Comment by ketozhang** [comment]
Thank you! I must've brainfarted not seeing that. I do wish it was placed immediately after the curl instruction.

**Comment by arnegroskurth** [comment]
> Hello @ketozhang ,
> 
> you can change the install directory by setting the environment variable `POETRY_HOME` before installing, e.g.:
> 
> ```
> POETRY_HOME=/opt/poetry/ curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python 
> ```
> 
> This is mentioned in the [docs](https://python-poetry.org/docs/)
> 
> fin swimmer

Not sure where this is coming from but when trying to install poetry in a Dockerfile I had to explicitly define the env-var before the receiving process of the pipe:

```
curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | POETRY_HOME=/opt/poetry/ python -
```
