### ISSUE TITLE
Error while running poetry init: "codec can't encode character u'\xf3'"

### ISSUE THREAD

**Issue by Abuelodelanada** [python-poetry/poetry#2241]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

When running `init` to generate a pyproject.toml I get the following no matter if i write something or not in Description

```bash
➜  rgh git:(develop) poetry  init -vvv

This command will guide you through creating your pyproject.toml config.

Package name [rgh]:
Version [0.1.0]:
Description []:
'ascii' codec can't encode character u'\xf3' in position 29: ordinal not in range(128)
'ascii' codec can't encode character u'\xf3' in position 29: ordinal not in range(128)
'ascii' codec can't encode character u'\xf3' in position 29: ordinal not in range(128)
...
```

- **OS version and name**:  Ubuntu 19.10
- **Poetry version**:  1.0.5
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**:

**Comment by finswimmer** [comment]
Hello @Abuelodelanada ,

this was reported earlier in https://github.com/python-poetry/poetry/issues/221 and seems to be a problem with special characters in your git config.

fin swimmer

**Comment by Abuelodelanada** [comment]
Hi fin!

Thanks! 
Yes, my lastname has an ó in .gitconfig.
