### ISSUE TITLE
Increase the verbosity of poetry so I know what it is doing when fails

### ISSUE THREAD

**Issue by klahnakoski** [python-poetry/poetry#2244]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

My coworkers are starting to use poetry in their projects, but poetry locks up on windows.  I would like to submit a more detailed issue, but even verbose mode tells me nothing about what step is failing.  

I can `poetry export` and then `pip install` the requirements just fine.

Here is my full run

```
C:\Users\kyle\code-ss\mozci>poetry install -vvv
Creating virtualenv mozci-whf49Q9--py3.7 in C:\Users\kyle\AppData\Local\pypoetry\Cache\virtualenvs
Installing dependencies from lock file


Package operations: 58 installs, 0 updates, 0 removals

  - Installing zipp (3.1.0)
  - Installing appdirs (1.4.3)
  - Installing certifi (2019.11.28)
  - Installing chardet (3.0.4)
  - Installing colorama (0.4.3)
  - Installing distlib (0.3.0)
  - Installing filelock (3.0.12)
  - Installing idna (2.9)
  - Installing importlib-metadata (1.5.0)
  - Installing markupsafe (1.1.1)
  - Installing pyparsing (2.4.6)
  - Installing pytz (2019.3)
  - Installing six (1.14.0)
  - Installing urllib3 (1.25.8)
  - Installing win32-setctime (1.0.1)
  - Installing alabaster (0.7.12)
  - Installing atomicwrites (1.3.0)
  - Installing attrs (19.3.0)
  - Installing babel (2.8.0)
  - Installing cachy (0.3.0)
  - Installing cfgv (3.1.0)
  - Installing docutils (0.16)
  - Installing identify (1.4.13)
  - Installing imagesize (1.2.0)
  - Installing jinja2 (2.11.1)
  - Installing json-e (3.0.2)
  - Installing loguru (0.4.1)
  - Installing markdown (3.2.1)
  - Installing more-itertools (8.2.0)
  - Installing nodeenv (1.3.5)
  - Installing packaging (20.3)
```

... at which point the process is frozen

**Comment by finswimmer** [comment]
Hey,

this issue is quite old and steps to reproduce are missing. That's why I'm closing this one.

fin swimmer

**Comment by Alex-EEE** [comment]
this is the dumbest close I've ever seen!  just install anything that takes a while.  try cppyy-cling for instance.  now, it just hangs....JUST LIKE THE POSTER said

**Comment by Alex-EEE** [comment]
please reopen, this is not resolved
