### ISSUE TITLE
Plugin package from git can't be installed

### ISSUE THREAD

**Issue by Evgenus** [python-poetry/poetry#2246]
When I'm trying to install a package that should be installed as a part of other package it is not installed. 
Example: `poetry add git+https://github.com/althonos/fs.archive.git`
I debugged a bit and found that the reason is in `--editable` option to pip. When package is installed from git it is always applied. Why do we need it in editable mode?
I'm on latest version (master)
OS: Macos
Python 2.7

What is going on:
`fs` is installed into `env/s-p/lib` from pypi in common way
repository clonned into `env/src`
pip tries to install it in editable mode (as symlink I guess)
modules in `env/src/fs.archive/fs/archive` are detached from `env/s-p/lib/fs`

**Comment by finswimmer** [comment]
Hello @Evgenus,

at the moment poetry installs git dependencies only in editable mode. This might change in the future with this PR: https://github.com/python-poetry/poetry/pull/1810

fin swimmer
