### ISSUE TITLE
poetry cannot install the latest torch version

### ISSUE THREAD

**Issue by vikigenius** [python-poetry/poetry#2247]
- [*] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [*] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [*] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: void linux x86_64 kernel: 5.4.28_1
- **Poetry version**: 1.0.5
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/vikigenius/49fe838e6d23648bbe1b6761c1d5d0e2

## Issue
Tried to add torch 1.4 with no success. It goes into some kind of infinite loop and never stops. It also seems to be downloading the wrong wheel and then just gets stuck.

`poetry add torch --platform linux --python 3.8 -vvv`

Tries to download the following wheel: `PyPI: Downloading wheel: torch-1.4.0-cp27-cp27m-manylinux1_x86_64.whl` and then gets stuck here.

The correct wheel would be `torch-1.4.0-cp38-cp38-manylinux1_x86_64.whl`

**EDIT:**
Simply trying to `poetry add torch` also leads to the same issue

**Comment by huntzhan** [comment]
Same issue here:
- OS: macOS 10.15.3
- Poetry version: 1.0.5

**Comment by seanytak** [comment]
Same issue:
- OS: Windows 10.0.18363
- Poetry version: 1.0.5

**Comment by abn** [comment]
The "Download wheel" log relates to a missing `requires_dist` in the pypi json data for the package, thereby causing poetry to fallback to downloading the first available wheel to introspect.

This will still lead to the correct version of the package being installed as the initial download is performed only for metadata parsing. See blow. Additionally, the delay is because the package `torch` is larger than your usual package on PyPI. Waiting for it to download will succeed. Once the cache is available there should no longer be a wait.

```console
$ poetry add torch --platform linux --python "^3.7" -vvv
Using virtualenv: ***/.venv
PyPI: 18 packages found for torch *
Using version ^1.4.0 for torch

Updating dependencies
Resolving dependencies...
   1: fact: platform-detection is 0.1.0
   1: derived: platform-detection
   1: fact: platform-detection depends on torch (^1.4.0)
   1: selecting platform-detection (0.1.0)
   1: derived: torch (^1.4.0)
PyPI: 1 packages found for torch >=1.4.0,<2.0.0
PyPI: Getting info for torch (1.4.0) from PyPI
PyPI: No dependencies found, downloading archives
PyPI: Downloading wheel: torch-1.4.0-cp27-cp27m-manylinux1_x86_64.whl
   1: selecting torch (1.4.0)
   1: Version solving took 27.945 seconds.
   1: Tried 1 solutions.

Writing lock file


Package operations: 1 install, 0 updates, 0 removals

  - Installing torch (1.4.0)
$ cat .venv/lib/python3.7/site-packages/torch-1.4.0.dist-info/WHEEL 
Wheel-Version: 1.0
Generator: bdist_wheel (0.33.6)
Root-Is-Purelib: false
Tag: cp37-cp37m-linux_x86_64
```

Closing this as this is not an issue. The situation will be improved via #2284 and #999.

**Comment by mzhadigerov** [comment]
@abn What If I want to keep torch dependency platform independent?
