### ISSUE TITLE
Display progress bar when downloading wheels

### ISSUE THREAD

**Issue by vikigenius** [python-poetry/poetry#2249]
- [*] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

Opening this, since #999 became stale. Is there any plan to add a progress bar when downloading wheels. Even with the -vvv flag, it is difficult to tell whether the download is actually happening or the program is stuck, especially if the wheel is known to be large.

**Comment by abn** [comment]
Closing this in favour of #999 as that one has more information.
