### ISSUE TITLE
ansible dependencies are not extracted from requires.txt

### ISSUE THREAD

**Issue by FiloSottile** [python-poetry/poetry#2251]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS Catalina
- **Poetry version**: 1.0.5
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/FiloSottile/73e6c754924afd9e482a970ac85c1b77

## Issue

When installing `ansible`, none of its dependencies are installed.

This was previously discussed in #581, but it looks like ansible now comes with a `ansible-2.9.6-py3.7.egg-info/requires.txt` metadata file which should make it possible to safely extract the dependencies.

**Comment by abn** [comment]
@FiloSottile this is still an issue with ansible. The tarball does not containe `egg-info`.

https://pypi.org/project/ansible/#files
