### ISSUE TITLE
Poetry fails to set path properly on fish

### ISSUE THREAD

**Issue by yunti** [python-poetry/poetry#2253]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [-] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS Catalina 10.15.3
- **Poetry version**: 1.05
- fish version: 3.1.0

## Issue
Poetry when installed with the recommend method (curl) fails to setup the path properly for use with fish. 
from the fish install ouput
`Poetry's bin directory ($HOME/.poetry/bin) has been added to your `PATH`
environment variable by modifying the `fish_user_paths` universal variable.`

and then Path details:
`echo $PATH
/usr/local/sbin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /Applications/Wireshark.app/Contents/MacOS`

**Comment by abn** [comment]
@yunti is this the case even after opening a new shell instance?

**Comment by stephsamson** [comment]
This does not seem to be an issue on macOS Catalina 10.15.5 anymore. @yunti can you confirm?

**Comment by LECbg** [comment]
I just installed Poetry using Curl and the same thing happened. I'm on macOS Big Sur v 11.2.3. I tried to open a new shell but `$HOME/.poetry/bin` was not added to `fish_user_paths`.

**Comment by finswimmer** [comment]
The `get-poetry.py` is now deprecated and will be replaced by `install-poetry.py` which will not change any env variables at all.

See https://python-poetry.org/blog/announcing-poetry-1.2.0a1/#deprecation-of-the-get-poetrypy-script
