### ISSUE TITLE
Add --skip-existing option to poetry publish

### ISSUE THREAD

**Issue by jonathanunderwood** [python-poetry/poetry#2254]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request
The twine tool for publishing to PyPi style repos has a very useful option `--skip-existing` for the `twine upload` command. This option basically says "don't error out if a file already exists on PyPi, continue to the next". 

This is super useful in a number of cases, including with CI/CD pipelines where, on branching, the pipeline will trigger a build for the new branch, but of course that first build will already have a corresponding package in PyPi as the commit it's being built from has already been built on the branch that the new branch was created from. In that case, it's fine for the pipeline to fail to upload the file as it already exists.

There are various other use cases for this flag. Could we have an equivalent flag for `poetry publish` ?

**Comment by davidszotten** [comment]
would you accept a patch that adds this?

**Comment by abn** [comment]
@davidszotten feel free to propose an implementation for this. You can either create a draft PR to discuss implementation or mention how you would want to approach this here. Couple of things that comes to mind:

1. Would this mean that we ignore all errors?
2. Can we identify "existing" vs "other error" accurately?
3. How do we handle other errors if this flag is set?

Happy to help review etc.

**Comment by davidszotten** [comment]
i would probably do something similar to [twine](https://github.com/pypa/twine/blob/master/twine/commands/upload.py#L32) (heuristics for a few package index implementations that try to detect this particular error) 

i explicitly don't want to ignore all errors, only "this file already exists"

**Comment by Casyfill** [comment]
Any hope to get this feature? Can't find discussion on  what happened to above.. 😟

**Comment by Incognito** [comment]
How can I help get this feature merged?

**Comment by Leem0sh** [comment]
Even tho I really like this project I'm forced to use twine for publishing generated clients :( This would be awesome to merge!

**Comment by KRunchPL** [comment]
I agree that this feature would be great. The PR looks good too me (although I did not check all possible responses :) ).
