### ISSUE TITLE
Solver tries to resolve dependencies not required on platform

### ISSUE THREAD

**Issue by ErikBjare** [python-poetry/poetry#2275]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Any
- **Poetry version**: v1.0.5
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://github.com/ActivityWatch/aw-watcher-afk/blob/dev/removed-excessive-windows-deps/pyproject.toml

## Issue

I'm trying to remove some unneeded dependencies from my project since they are no longer used (pypiwin32 and pyHook). 

However, a dependency (PyUserInput) that is still needed on Linux depends on these two old dependencies, *but only on Windows*. 

Since PyUserInput is only a dependency for Linux (selected with `platform = "linux"`) I shouldn't need to install these other two dependencies on Windows anymore, yet the solver complains:

```
[SolverProblemError]
Because no versions of pyuserinput match !=0.1.12
 and pyuserinput (0.1.12) depends on pypiwin32 (*), every version of pyuserinput requires pypiwin32 (*).
So, because no versions of pypiwin32 match *
 and aw-watcher-afk depends on pyuserinput (*), version solving failed.
```

PR with changes here: https://github.com/ActivityWatch/aw-watcher-afk/pull/39

Failing CI run here: https://github.com/ActivityWatch/aw-watcher-afk/pull/39/checks?check_run_id=564392363

**Comment by abn** [comment]
This could be related to issue 1 identified in https://github.com/python-poetry/poetry/issues/2138#issuecomment-596250583.

**Comment by ErikBjare** [comment]
I believe this should have the tag: https://github.com/python-poetry/poetry/labels/Dependency%20resolution

Out of curiosity, I'd be interested to have a look at this myself (depending on how messy it may be). But I'm having a bit trouble trying to figure exactly where in https://github.com/python-poetry/poetry/blob/288d99739fba4425def7c567d71537ce5bd2a0f9/poetry/puzzle/solver.py#L23 that the platform check should be made, so if anyone could point me in the right direction it'd be appreciated.

**Comment by abn** [comment]
@ErikBjare the traceback with `-vvv` should provide an idea of the codepath.

The relevant block here could be https://github.com/python-poetry/poetry/blob/6e053e5599acdf1e186a8853c6256646c56a4a7d/poetry/puzzle/solver.py#L102-L103

The issue seems to be that poetry is requesting an install operation even if that package is not required. It could also be handled deeper in the `Install` logic too. Ideally, it should both skip the package and ensure that any unnecessary install/solve operation is not performed during instsall time.

**Comment by ErikBjare** [comment]
I've taken a look at it and from my limited understanding of poetry it seems I should check the marker using `Env.is_valid_for_marker` and if not matched then skip the operation (not easily done from `Solver`, since an instance of `Env` is not accessible from there, as it probably shouldn't be).

I also obtained the verbose traceback:

```
[SolverProblemError]
Because no versions of pyuserinput match !=0.1.12
 and pyuserinput (0.1.12) depends on pypiwin32 (*), every version of pyuserinput requires pypiwin32 (*).
So, because no versions of pypiwin32 match *
 and aw-watcher-afk depends on pyuserinput (*), version solving failed.

Traceback (most recent call last):
  File "c:\hostedtoolcache\windows\python\3.6.8\x64\lib\site-packages\clikit\console_application.py", line 131, in run
    status_code = command.handle(parsed_args, io)
  File "c:\hostedtoolcache\windows\python\3.6.8\x64\lib\site-packages\clikit\api\command\command.py", line 120, in handle
    status_code = self._do_handle(args, io)
  File "c:\hostedtoolcache\windows\python\3.6.8\x64\lib\site-packages\clikit\api\command\command.py", line 171, in _do_handle
    return getattr(handler, handler_method)(args, io, self)
  File "c:\hostedtoolcache\windows\python\3.6.8\x64\lib\site-packages\cleo\commands\command.py", line 92, in wrap_handle
    return self.handle()
  File "c:\hostedtoolcache\windows\python\3.6.8\x64\lib\site-packages\poetry\console\commands\install.py", line 63, in handle
    return_code = installer.run()
  File "c:\hostedtoolcache\windows\python\3.6.8\x64\lib\site-packages\poetry\installation\installer.py", line 74, in run
    self._do_install(local_repo)
  File "c:\hostedtoolcache\windows\python\3.6.8\x64\lib\site-packages\poetry\installation\installer.py", line 225, in _do_install
    ops = solver.solve(use_latest=whitelist)
  File "c:\hostedtoolcache\windows\python\3.6.8\x64\lib\site-packages\poetry\puzzle\solver.py", line 36, in solve
    packages, depths = self._solve(use_latest=use_latest)
  File "c:\hostedtoolcache\windows\python\3.6.8\x64\lib\site-packages\poetry\puzzle\solver.py", line 190, in _solve
    raise SolverProblemError(e)
```

I traced the cause of the SolverProblemError to a SolveFailure being thrown in `poetry/mixology/version_solver.py`, which is too complicated for me to grok.

Right after the `solver.solve` is called in `Installer._do_install` the `_filter_operations` is called which would, as far as I can tell, successfully filter away the package by checking the marker.

Further guidance welcome.

**Comment by finswimmer** [comment]
Closing this as an upstream issue, as explained by @dimbleby. Please contact the maintainer of this package and ask them to fix it.
