### ISSUE TITLE
Poetry fails to install fish terminal completions

### ISSUE THREAD

**Issue by yunti** [python-poetry/poetry#2278]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [-] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS Catalina 10.15.3
- **Poetry version**: 1.05
- fish version: 3.1.0
## Issue
Following the instructions on the readme to install fish completions fails with the below error:
```
❯❯❯ poetry completions fish > $(brew --prefix)/share/fish/vendor_completions.d/poetry.fish
fish: Invalid redirection target:
poetry completions fish > $(brew --prefix)/share/fish/vendor_completions.d/poetry.fish
```

**Comment by mathieucaroff** [comment]
```
poetry completions fish > $(brew --prefix)/share/fish/vendor_completions.d/poetry.fish
```

is meant to be run from a bash-compatible shell.

For fish, you need to drop the `$`:

```
poetry completions fish > (brew --prefix)/share/fish/vendor_completions.d/poetry.fish
```

I think that the #enable-tab-completion-for-bash-fish-or-zsh section of the README.md is not clear in that regard and thus should be updated.
