### ISSUE TITLE
Include optional path to python executable in install command to fix python version issues

### ISSUE THREAD

**Issue by TomMalkin** [python-poetry/poetry#2286]
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

I can see a lot of issues around specifying the python version, especially on windows that doesn't have access to pyenv. I guess this is because poetry uses `python` under the hood somewhere, so that needs to be linked to the python version you want as your environment. This is irrespective to what python version is actually running poetry.

Would it be possible to specify which python executable to use in the install command itself?

Say you are on Windows with python 3.6, 3.7 and 3.8 installed with python.exe linked to version 3.6, and poetry installed on 3.7:

`poetry install --python-executable=C:\path\to\python3.7`

and then python can use that executable instead of the first python.exe on the path?

Forgive me if I'm misunderstanding how this works.

Thanks!

**Comment by yelled1** [comment]
Actually there is https://github.com/pyenv-win/pyenv-win. I have been using it & it's got some quirks,  but it works well enough especially w/ Python 3.x's venv. Just remember to use pyenv rehash alot (which, I aliased to rehash), and need virtualenvironment package installed with python 2.x. I have been using with pipenv but attempting to use it w/ Poetry instead.
So, this is not direct answer to your Q, but...

**Comment by finswimmer** [comment]
> Would it be possible to specify which python executable to use in the install command itself?

This is already possible by running `poetry env use /path/to/python` before `poetry install`. A `pyproject.toml` with the correct python version specified must be present in the folder.

fin swimmer
