### ISSUE TITLE
Support `--no-compile` when installing a package

### ISSUE THREAD

**Issue by laike9m** [python-poetry/poetry#2288]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request
Pip supports the [`--no-compile`](https://pip.pypa.io/en/stable/reference/pip_install/#cmdoption-no-compile) option when installing a package. I want to install a [library](https://github.com/thautwarm/moshmosh) that requires this flag, but find it hard to achieve using Poetry.

**Comment by KotlinIsland** [comment]
> #2288 is solved here too now.

\- https://github.com/python-poetry/poetry/pull/6205#issuecomment-1356133534

@Secrus Is this resolved? Can this be closed?

**Comment by radoering** [comment]
Yep, "no-compile" is the default now unless `installer.modern-installation` is set to `false`. See https://python-poetry.org/docs/cli/#install
