### ISSUE TITLE
Add the ability to specify the version of the package during the build

### ISSUE THREAD

**Issue by SailingYYC** [python-poetry/poetry#2290]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request
During CI builds it would be highly beneficial to be able to pass the version of the build to `poetry build`, ensuring that is the version identifier baked into the `sdist` and `wheel`, but without updating `pyproject.toml`.

I would suggest `poetry build --version <version number>`.

**Comment by finswimmer** [comment]
Hello @SailingYYC ,

the version must be updated in the `pyproject.toml` as it is packed within the `sdist` as well.

What I could imagine is, that `poetry build --version <version number>` becomes a shorthand for `poetry version <version number> && poetry build`.

fin swimmer

**Comment by SailingYYC** [comment]
My dilemma with this is that  `pyproject.toml` is used as a cache key for the build (so subsequent builds don’t have to always redownload packages) and changing it during the run invalidates the cache. Many other build systems (Across stacks) support this, Eg. Helm https://helm.sh/docs/helm/helm_package/

**Comment by dimbleby** [comment]
the version is stored in pyproject.toml, there's no intention to change that, this can be closed

**Comment by wagnerluis1982** [comment]
Is there a reason for this issue be still open?

**Comment by neersighted** [comment]
No is temporary, yes is forever... Let's close this as firmly rejected for now; there has been no movement to make me think that this would be accepted now/in the near future.
