### ISSUE TITLE
Use separate “publish” URL for a private PyPI feed

### ISSUE THREAD

**Issue by SailingYYC** [python-poetry/poetry#2291]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request
We currently use Azure DevOps Artifacts and it uses two different URLs, I feel this is similar to Artifactory and other feeds. 

For pulling packages, the familiar `https://.../.../pypi/simple` index URL is used, but for submitting packages, `https://.../.../pypi/upload` Is used. 

I am not aware if this is common for PyPI feeds or not, it would be great if poetry could auto-detect this and use the correct URL, or at least provide a mechanism to specify a separate publish URL for the same feed.

**Comment by jtratner** [comment]
Since `poetry publish` accepts repository + username and password, could you handle this by specifying: `poetry publish -r https://.../.../pypi/upload` instead?  (you can still leave the other feed for sources)

**Comment by xM8WVqaG** [comment]
> I am not aware if this is common for PyPI feeds or not <snip>

This is also true for GitLab's current PyPi implementation:

You publish packages to:
```
https://gitlab.com/api/v4/projects/{REPO_ID}/packages/pypi
```
But you install packages from:
```
https://gitlab.com/api/v4/projects/{REPO_ID}/packages/pypi/simple
```

**Comment by SailingYYC** [comment]
> Since `poetry publish` accepts repository + username and password, could you handle this by specifying: `poetry publish -r https://.../.../pypi/upload` instead? (you can still leave the other feed for sources)

@jtratner Once we have a few more teams look to adopt `poetry`, we will more likely need to write a custom Azure DevOps task for it to make it as simple to use as standard PIP (acquiring authorization for feeds, setting up caching directories for download/built modules, disabling venv, etc.)

We are currently achieving this with lots of bash scripting in each pipeline.

**Comment by jtratner** [comment]
@SailingYYC - not to push too hard, but could you specifically address why the `-r` flag doesn’t work for your purposes?

If you need an env var this is easy to do.

```
export FEED_BASE=...
poetry publish -r ${FEED_BASE}/publish -u $USERNAME -p $PASSWORD
```

Whole CI just becomes:

```
poetry install # existing lock file specifies main feed
poetry run pytest
poetry build
poetry publish -r https://.../upload -u username -p password
```

I believe the publish command explicitly supports the second half of your request in this issue.

**Comment by xM8WVqaG** [comment]
(not OP but same issue)

I'm not able to pass the URL in under the `--repository` flag. I have to define the repo first.

```
[]$ poetry --version
Poetry version 1.0.5

[]$ poetry publish -n --build \
      --repository https://gitlab.com/api/v4/projects/{REPO_ID}/packages/pypi \
      -u __token__ \
      -p REDACTED                                    
Building my_package (0.1.4)
 - Building sdist
 - Built my_package-0.1.4.tar.gz

 - Building wheel
 - Built my_package-0.1.4-py3-none-any.whl

Publishing my_package (0.1.4) to https://gitlab.com/api/v4/projects/{REPO_ID}/packages/pypi

[RuntimeError]
Repository https://gitlab.com/api/v4/projects/{REPO_ID}/packages/pypi is not defined
```

On the CI I'm doing:
```
- poetry config repositories.this "https://gitlab.com/api/v4/projects/{REPO_ID}/packages/pypi"
- >
  poetry publish -n --build
  -r this
  -u $POETRY_HTTP_BASIC_GITLAB_USERNAME
  -p $POETRY_HTTP_BASIC_GITLAB_PASSWORD
```

Automatically creating `this` is fine to do in a CI lifecycle that's destroyed after but would be inappropriate to do on a local environment. We were already discouraging manually publishing builds so I've been pretending this is a feature!

**Comment by jtratner** [comment]
Gotcha, that’s a really helpful explanation! maybe there’s space for a
`--repository-url` In addition to repository?

**Comment by caseydialpad** [comment]
This issue is also relevant for GCP Artifact Registry.
