### ISSUE TITLE
Installing bash completion requires root privileges

### ISSUE THREAD

**Issue by mathieucaroff** [python-poetry/poetry#2295]
In README.md, enabling tab completion for bash requires root privileges. This is inconsistent with (non-hombrew) fish and zsh completion definitions.

## Related issue

Bash completion permission denied (#1017)

Note: The solution to the above issue is to use tee:

```
poetry completions bash | sudo tee /etc/bash_completion.d/poetry.bash-completion
```

## Looking for a solution

Asking google yields this serverfault page: [Standard place for user defined bash_completion.d scripts](https://serverfault.com/q/506612/standard-place-for-user-defined-bash-completion-d-scripts)

The bash_completion tool actually sources `~/.bash_completion` file [see their FAQ "Where should I install my own local completions?"](https://github.com/scop/bash-completion/#faq). I thus believe the command for bash completion in README.md should be

```
poetry completions bash >> ~/.bash_completion
```

instead of

```
poetry completions bash > /etc/bash_completion.d/poetry.bash-completion
```

.

**Comment by dlech** [comment]
My solution was to add this to my `~/.bashrc`. This way I don't have to remember to update completions if I update `poetry`.

    . <(poetry completions bash)

**Comment by finswimmer** [comment]
It would be a good idea to show it in the docs, how to add this to the users home folder. Just like for the other shells.

Happy to review a PR for this :)

fin swimmer
