### ISSUE TITLE
Dependency resolution loop with Sphinx and Zappa

### ISSUE THREAD

**Issue by ryancausey** [python-poetry/poetry#2298]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 18.04.4 LTS (Bionic Beaver)
- **Poetry version**: `Poetry version 1.0.5`
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**:  https://gist.github.com/ryancausey/219419d2316514c7f1c60f3e60296869

## Issue

The dependency resolution seems to get stuck in a loop due to the derived `botocore` dependency requiring `docutils<0.16`. This dependency comes from `Zappa` requiring `boto3` which requires `botocore`. I'm not sure why poetry is selecting `docutils==0.16` and then getting stuck in a loop trying to resolve `boto3` and `botocore`.

The workaround is to add `boto3` directly as a dependency, I.E. `poetry add boto3`. Then poetry correctly selects `docutils<0.16`.

The pyproject.toml GIST linked above is the minimum required to reproduce this issue.

Here's a gist containing some of the verbose output of the loop: https://gist.github.com/ryancausey/25c01d8a06fcdc7aef40424168dfdbb5

**Comment by finswimmer** [comment]
Hello,

this seems to solved in the meantime.

fin swimmer
