### ISSUE TITLE
Private repo causes transient extra dependencies to be tossed

### ISSUE THREAD

**Issue by madig** [python-poetry/poetry#2300]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows 10 1909 x64
- **Poetry version**: 1.0.5
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/madig/de961d21c8f796b4fc86d984dece0fd4

## Issue
The presence of a secondary package index and a package from there as a dependency messes with dependency resolution.

To reproduce:

1. `poetry new test && cd test`
2. Insert content of https://gist.github.com/madig/de961d21c8f796b4fc86d984dece0fd4 into `pyproject.toml`
3. `poetry install` -- note how this installs `appdirs`, `fs`, `pytz` and `six`.
4. `poetry update` -- removes these packages again when it shouldn't.
5. Comment out the test repository and the `poetry-resolver-bug-test` package
6. `poetry update` reinstalls `appdirs` and friends
7. Reenable repo and package
8. `poetry update` -- installs the `poetry-resolver-bug-test` package but leaves `appdirs`, etc. alone
9. Redoing `poetry update` then tosses them again when it shouldn't.

In my actual package, the `toml` package (via `isort[pyproject]`) also gets tossed out, but I can't reproduce this here easily.

**Comment by vbersier** [comment]
Can reproduce with the following package (that has a dependency on `dask[dataframe]`):

```
$ poetry new test_proj
$ cd test_proj
$ poetry install
$ poetry add tsfresh  # here everything gets installed as it should
$ poetry update  # here fsspec, locket and partd are removed
```

Similar bug to https://github.com/python-poetry/poetry/issues/2494 and https://github.com/python-poetry/poetry/issues/2080 IMO
