### ISSUE TITLE
ERROR: tox config file (either pyproject.toml, tox.ini, setup.cfg) not found

### ISSUE THREAD

**Issue by sathwik04** [python-poetry/poetry#2317]
iam a beginner and i have installed tox using pip install tox and  dont know how to create a tox.ini and 
setup.cfg  i mean in which location thats needs to be created beacuse i tried by creating tox.ini in my project folder but its showing as unsolved reference .could any one guide how to start with this i already read tutorials about this but no use .  can anyone help me this out

**Comment by stephsamson** [comment]
Hi @sathwik04, here's a [guide on how to use `poetry`](https://python-poetry.org/docs/basic-usage/#basic-usage). To use `tox` with your `poetry` project, you can emulate the [`tox.ini`](https://github.com/python-poetry/poetry/blob/master/tox.ini) that is used in Poetry.
