### ISSUE TITLE
Poetry installing python3 versions with 2.7 required

### ISSUE THREAD

**Issue by thoward27** [python-poetry/poetry#2319]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Mac OSx and Ubuntu
- **Poetry version**: 1.0.5

```
[tool.poetry.dependencies]
python = "^2.7"
django-select2 = "6.3.1"
```

## Issue
Specifying python 2 in dependencies with `django-select2` installs `django-appconf==1.0.4`, which is not compatible with `python2`

https://pypi.org/project/django-appconf/#history

**Comment by finswimmer** [comment]
Hello @thoward27,

why do you think 1.0.4 isn't compatible to python2? According to https://pypi.org/project/django-appconf/1.0.4/#files the wheel is usable for python2. Even in the `setup.py` I cannot see any restriction to the python version.

fin swimmer

**Comment by thoward27** [comment]
@finswimmer the classifiers specify python3 tags only, and the commit that breaks python2 is here: https://github.com/django-compressor/django-appconf/commit/8dcd89d5d386d4b3f09ca85d549a706bae12d8e3#diff-2eeaed663bd0d25b7e608891384b7298

**Comment by finswimmer** [comment]
Hello again,

the classifiers are just informational metadata. The correct place for the python version requirement is [python_requires](https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires).

Please be so kind and report it to the package authors.

fin swimmer

**Comment by thoward27** [comment]
Raised an issue there. Thanks @finswimmer
