### ISSUE TITLE
presence of setup.py breaks entrypoint generation

### ISSUE THREAD

**Issue by wichert** [python-poetry/poetry#2324]
- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS 10.15.4
- **Poetry version**: 1.0.5

## Issue

I had a dummy setup.py (based on [this post](https://snarky.ca/what-the-heck-is-pyproject-toml/)):

```python
#!/usr/bin/env python

import setuptools

if __name__ == "__main__":
    setuptools.setup()
```

When that file is present two things happen when doing `poetry install`:

* egg info is now created under `UNKNOWN.egg-info`
* `entry_points.txt` is no longer generated

Interestingly enough `entry_points.txt` is still present in a generated wheel.

## Steps to reproduce

```shell
poetry new testpoint
cd testpoint
printf '\n[tool.poetry.plugins.test]\nmain = "foo"' >> pyproject.toml
echo 'import setuptools; setuptools.setup()' > setup.py
poetry install
```

**Comment by finswimmer** [comment]
Hello @wichert,

as the last step in `poetry install` poetry creates a temporary `setup.py` and uses `pip` to install the package itself in editable mode (`pip`can't do this at the moment with a `pyproject.toml`). If there is already a `setup.py` poetry will not overwrite this one, so `pip` will use the one already present.

Is there any reason why you've created the `setup.py`? This is not necessary when using `poetry`. Just remove the file and everything should work fine.

fin swimmer

**Comment by wichert** [comment]
Hi fin,

I have to admit that with all the changes in `setup.py`, `setup.cfg` and `pyproject.toml` I am having a hard time figuring out what exactly goes where and why. I hadn't realised not having a setup.py was actually a viable approach here, and since this project was migrated to poetry it already had a `setup.py`. Perhaps it would be helpful if poetry could give a warning if `setup.py` already exists?

**Comment by mhtb32** [comment]
> Is there any reason why you've created the `setup.py`? This is not necessary when using `poetry`. Just remove the file and everything should work fine.

So if some user of some package wants to install it from the latest source(for example from Github), she could just install it with poetry? @finswimmer

**Comment by louwers** [comment]
`setup.py` is still needed for Cython extensions, for intergration with some versioning systems or for better support for namespace packages, e.g.

```
    packages=find_namespace_packages(include=['pkg.*']),
```

**Comment by abn** [comment]
@louwers can't this be done via poetry's `packages` configuration? Also note that poetry detects namespace packages without any issues.

**Comment by abn** [comment]
@wichert with `1.1.0` poetry will not use `setuptools` for the editable installs. The presence of a setup file should not impact this anymore.

See: #2360
