### ISSUE TITLE
multiple optional path for one dependency

### ISSUE THREAD

**Issue by Biber05** [python-poetry/poetry#2334]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

Currently I am working on GitLab CI including poetry builds. The problem I have is that GitLab CI won´t accept relative path in my _pyproject.toml_. As a workaround and maybe for other reasons I wish that there is a possibility to have two separat paths (relative and absolute) for a single dependency. 
Like this: 

`
commons = [
{ path = "./lib/commons-1.0.0-py3-none-any.whl", optional=true },
{ path = "/absolute/path/to/project/lib/commons-1.0.0-py3-none-any.whl", optional=true }
]
`

Other options or suggestions are welcome 

THANKS - great job BTW ❤️

**Comment by finswimmer** [comment]
Hey @Biber05,

having multiple sources for one package doesn't work in the python ecosystem. It is unclear how the decision is made about which source should be used.

You should better find out why relative paths don't work in your CI.

fin swimmer
