### ISSUE TITLE
`pip install -e .` installs poetry projects with name `UNKNOWN-0.0.0`

### ISSUE THREAD

**Issue by Akuli** [python-poetry/poetry#2343]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: an OS based on debian 10
- **Poetry version**: Poetry version 1.0.5
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**:  https://gist.github.com/Akuli/29c23a4815d6ecb51964669459ebd4af

## Issue
Trying to install sansio-lsp-client created by @PurpleMyst with `pip install -e .`. Seems like pip doesn't find any metadata, even after copy/pasting `[tool.poetry]` stuff like `name` and `version` into `[project]`.

Is `pip install -e .` supposed to to work on *any* project, regardless of whether it uses setuptools, poetry, flit or something else? It would be nice if I didn't need to learn about poetry just to get something installed with `-e`.

I installed poetry tried `poetry develop` which I found from issue #34 

```
(env) akuli@akuli-desktop:~/porcu/sansio-lsp-client$ poetry develop
The command "develop" is not defined.
(env) akuli@akuli-desktop:~/porcu/sansio-lsp-client$ poetry -vvv develop
USAGE
  poetry help [<command1>] ... [<commandN>]

ARGUMENTS
  <command>              The command name

GLOBAL OPTIONS
  -h (--help)            Display this help message
  -q (--quiet)           Do not output any message
  -v (--verbose)         Increase the verbosity of messages: "-v" for normal
                         output, "-vv" for more verbose output and "-vvv" for
                         debug
  -V (--version)         Display this application version
  --ansi                 Force ANSI output
  --no-ansi              Disable ANSI output
  -n (--no-interaction)  Do not ask any interactive question

```

Also, `poetry install --help` says nothing about `-e` or editable.

**Comment by Akuli** [comment]
now i got an error that i hadn't gotten before.I don't know what's going on, but I don't think it's poetry's fault so I'll close this

```
(env) akuli@akuli-desktop:~/porcu/sansio-lsp-client$ pip install -e .
ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: /home/akuli/porcu/sansio-lsp-client
(A "pyproject.toml" file was found, but editable mode currently requires a setup.py based build.)
```

**Comment by Akuli** [comment]
I finally managed to get the project installed with `-e` by first converting its pyproject.toml to `setup.py` with dephell like in [this comment](https://github.com/python-poetry/poetry/issues/761#issuecomment-521124268), then `pip install -e .`

I wish that it was possible to just `pip install -e .` anything, but the error message makes it seem like this is a pip problem, so I'll keep this issue closed

**Comment by thumperward** [comment]
leaving this note here for future archeologists: the problem is that your `pyproject.toml` didn't contain any `build-system` section, so pip didn't know how to build it. Adding the likes of the following would have fixed the problem:

```toml
[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```
