### ISSUE TITLE
poetry-core: consider *not* to vendor dependencies

### ISSUE THREAD

**Issue by decathorpe** [python-poetry/poetry#2346]
Python projects are starting to rely on pyproject.toml / poetry based build systems now, and this is also affecting fedora packages, for example. In this context, it's important to have a working, "native" poetry package.

However, using vendored dependencies - like in this project (which looks like will be required by what will be poetry 1.1.0) - will make it almost impossible to package poetry, let alone package it correctly.

Please reconsider the decision to use bundled dependencies.

**Comment by hroncok** [comment]
Thanks!

**Comment by abn** [comment]
@hroncok I might have not answered your question.

> E.g. if Poetry itself runs on Python 3.8 to manage a Python 3.6 project, is importlib-metadata ever used?

Poetry, when run on 3.8 to manage a 3.6 project, it does not need `importlib-metadata` package. The dependencies are for Poetry itself. Poetry, will be able to manage Python 2.7 projects even after Poetry itself drops runtime support for Python 2.7.

**Comment by abn** [comment]
This was resolved via python-poetry/poetry#2346

**Comment by pradyunsg** [comment]
> [doesn't pip do the same thing?](https://github.com/pypa/pip/tree/master/src/pip/_vendor)

pip's has a published rationale for doing so: https://pip.pypa.io/en/latest/development/vendoring-policy/#rationale. As noted by others, it's uniquely positioned in this situation. :)
