### ISSUE TITLE
I recently tried to install poetry in a fresh ubuntu 20.04 env, with python3 as default version i experienced unpredictable behaviour.

### ISSUE THREAD

**Issue by zero-shubham** [python-poetry/poetry#2352]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Issue

when using with python3.8-venv activated  and sometimes without that i got /usr/bin/env python not found error.

**Comment by abn** [comment]
@zero-shubham any additional information to reproduce this issue might be helpful. For example, 

1. how python was installed?
2. how poetry was installed?
3. what steps did you follow to encounter the issue?
4. what does `python -VV` return?

**Comment by zero-shubham** [comment]
Okay this is confirmed, you need to install Python2.7 manually for a fresh ubuntu 20.04 env.
To answer above -
1. I didn't Ubuntu 20.04 has Py3.8.2 by default
2. I used get-poetry.py
3. with and without Py3.8 venv activated this issue is confirmed, `/usr/bin/env python not found error`

So what i did was to install py2.7 manually installed poetry using python2 now and everything worked as it used be for Ubuntu 18.04
Python3.8-venv activated works, didn't test for Python2.7.

**Comment by finswimmer** [comment]
Hello @zero-shubham,

I found your description a little bit confusing. But I guess you don't have a `python` executable in your `PATH`. Most likely you just have `python2` and/or `python3`, but `poetry` expect to find `python`. See the PRs #1042 and #1518

fin swimmer

**Comment by zero-shubham** [comment]
Hey @finswimmer yes poetry does need "python" as a command i.e. it needs to be in PATH 
Since ubuntu 20.04 comes with python3 and adding a symlink or alias where `python` points to `python3` will also not work. Since python2.7 is no more officially supported poetry should to python3, just suggestion. Thanks!

**Comment by rajuah** [comment]
@zero-shubham You can `apt-get install python-is-python3`. It'll create the symlink - https://packages.ubuntu.com/focal/python-is-python3

**Comment by zero-shubham** [comment]
Aaha didn't know about that exists. Thanks!
