### ISSUE TITLE
Upgrade tomlkit dependency version ^0.6.0

### ISSUE THREAD

**Issue by llybin** [python-poetry/poetry#2362]
Hello. We, in Archlinux, have a trouble: https://bugs.archlinux.org/task/66442

The package tomlkit was upgraded to 0.6.0 version, but [poetry is required tomlkit version below 0.6.0](https://github.com/python-poetry/poetry/blob/master/pyproject.toml#L38)

Looks like new version doesn't contain break backwards compatibility: https://github.com/sdispater/tomlkit/blob/master/CHANGELOG.md#060---2020-04-15

Could you please upgrade in next release tomlkit dependency version.

**Comment by pradyunsg** [comment]
I'd requested poetry to not start using a newer version of tomlkit (which supports TOML 1.0.0-rc1) while other tooling in the ecosystem (like pip) catch up to newer TOML language specifications.

Is there some reason the Arch Linux package for python-poetry can't reflect the < 0.6.0 constraint on python-tomlkit?

**Comment by llybin** [comment]
Archlinux is rolling release. I think dependecies was configured not correctly for poetry, one maintainer upgraded tomlkit, and didn't saw any problems and now poetry is broken there.. If you think upgrade tomlkit package is not good idea - ok. Just was thinking as simple solution how to can fix this trouble in Arch. Feel free close, thanks.

**Comment by llybin** [comment]
They made patch: https://git.archlinux.org/svntogit/community.git/commit/trunk?h=packages/python-poetry&id=614b05aab10fa9ccb6038b1de63edf4c542b00dd
