### ISSUE TITLE
poetry does not always respect environment variables on MacOS

### ISSUE THREAD

**Issue by bdmayes** [python-poetry/poetry#2363]
- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: MacOS 10.15.4
- **Poetry version**: 1.0.5
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: N/A

## Issue

TL;DR: You probably want to allow the POETRY_HTTP_BASIC_REPO_PASSWORD variable to be read from the environment in password_manager.py, even if the auth.toml file exists.

I am using poetry as part of my Jenkins pipeline, on a Mac. My team ships a small piece of desktop software for both Windows and Mac, which is really just a thin shell around some python code. Our users cannot install this code on Catalina because our app isn't notarized by Apple, so to make that happen, I had to update this machine to Catalina yesterday.

In Mojave, I stored the username/password for our artifactory server in the keychain via `poetry config http-basic.myrepo $MY_AWESOME_USERNAME $MY_SECRET_PASSWORD`. This now fails on Catalina, which is actually the bug I was going to report, until I realized it's a problem with the keyring module. It seems you cannot access the keyring without a GUI available. The command below that fails via an SSH session (or when run as part of a Jenkins build), will work fine when run from a VNC session. 😑 

```
>>> import keyring
>>> keyring.set_password("my-fake-keychain-item", "foo", "bar")
Traceback (most recent call last):
  File "/Users/jenkins/testenv/lib/python3.7/site-packages/keyring/backends/OS_X.py", line 38, in set_password
    api.set_generic_password(self.keychain, service, username, password)
  File "/Users/jenkins/testenv/lib/python3.7/site-packages/keyring/backends/_OS_X_API.py", line 256, in set_generic_password
    Error.raise_for_status(status)
  File "/Users/jenkins/testenv/lib/python3.7/site-packages/keyring/backends/_OS_X_API.py", line 50, in raise_for_status
    raise cls(status, "Unknown Error")
keyring.backends._OS_X_API.Error: (-25308, 'Unknown Error')
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jenkins/testenv/lib/python3.7/site-packages/keyring/core.py", line 62, in set_password
    _keyring_backend.set_password(service_name, username, password)
  File "/Users/jenkins/testenv/lib/python3.7/site-packages/keyring/backends/OS_X.py", line 42, in set_password
    raise PasswordSetError("Can't store password on keychain: " "{}".format(e))
keyring.errors.PasswordSetError: Can't store password on keychain: (-25308, 'Unknown Error')
```

Furthermore, even when I set that via VNC, attempting to retrieve it via Jenkins/SSH was unsuccessful. Thus, I set `POETRY_HTTP_BASIC_MYREPO_USERNAME` and `POETRY_HTTP_BASIC_MYREPO_PASSWORD` in my environment and ran another build. However, because I had previously run the command `poetry config http-basic.myrepo $USER $PASS` it created an auth.toml file. On a Mac, the file only contains the username, and the password is expected to come from the keychain. But reading/writing to the keychain fails on this machine. Unfortunately, password_manager.py will _only_ invoke `self._config.get("http-basic.{}.password".format(name))` if auth.toml does not exist. If it does, then it always reads the password from the keychain even if you have the environment variable set. See https://github.com/python-poetry/poetry/blob/master/poetry/utils/password_manager.py#L165

I think you need to modify password_manager.py to read from the environment variable even _if_ auth.toml exists. Having a cascading configuration where values in one location have a higher priority/override other definitions of the same config is a pretty natural and common thing to do. Typically environment variables are among the highest priority. Furthermore, it seems like this might trip up people who test it manually on a machine first (where the keychain access will work), and then try to automate it later only to see it fail. Ask me how I know!

Maybe check the environment variable first and only _then_ if the password is still `None` then you should attempt to read it from the keychain? I can probably open a PR if you're interested.

**Comment by finswimmer** [comment]
Hello @bdmayes,

you haven't come back to this issue for a long while. So I assume this is solved in the meantime and I can close this ticket.

Feel free to leave a comment if you disagree.

fin swimmer
