### ISSUE TITLE
Option to initialize version control with poetry new

### ISSUE THREAD

**Issue by LovecraftianHorror** [python-poetry/poetry#2364]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

Hello, I'd like to start of by saying thanks for helping make `poetry`. Something that I think would be a nice feature to have would be an option to initialize version control with `poetry new`. I'm only really familiar with `git`, but it would be along the lines of `git init` and including an appropriate `.gitignore` file as well. I would assume that a large number of people would normally want to keep their poetry projects in version control anyways so this is likely common behavior.

One tool that does this well, in my opinion, is `cargo` with `rust` which has a `--vcs <VCS>` flag where you can pass the type of version control to initialize with or `none` to not initialize version control automatically.

**Comment by finswimmer** [comment]
Hello @LovecraftianHorror,

those individual project things are better handled by [cookiecutter](https://github.com/cookiecutter/cookiecutter).

fin swimmer
