### ISSUE TITLE
build --format and TOML packages.format behave differently

### ISSUE THREAD

**Issue by george-hawkins** [python-poetry/poetry#2365]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 18.04 LTS
- **Poetry version**: 1.0.5
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: <https://gist.github.com/george-hawkins/3fe1fb89ed1a726884eaf27bad1de120>

## Issue

I thought I would be able to use `format = "sdist"` in my `pyproject.toml` to achieve the same effect as using `--format=sdist` when running `poetry build`. However, currently `format` in `pyproject.toml` has no effect on whether the wheel is built or not - in fact there seems to be no way to disable building the wheel via `pyproject.toml`.

Perhaps this is intentional, but it seems confusing that `format` (with value `sdist`) means one thing in one context and another thing elsewhere.

Example output:

```
$ poetry build --format=sdist
Building foo-bar-cb3da32 (0.1.1)
 - Building sdist
 - Built foo-bar-cb3da32-0.1.1.tar.gz
```

Above only the `sdist` format gets built, however here both `sdist` and `wheel` get built:

```
$ fgrep format pyproject.toml 
    { include = "foo_bar_cb3da32", format = "sdist" },
$ poetry build
Building foo-bar-cb3da32 (0.1.1)
 - Building sdist
 - Built foo-bar-cb3da32-0.1.1.tar.gz

 - Building wheel
 - Built foo_bar_cb3da32-0.1.1-py3-none-any.whl
```

If I look at `build` in [`complete.py`](https://github.com/python-poetry/poetry/blob/master/poetry/masonry/builders/complete.py#L17) I see that explicitly setting `format` in my `pyproject.toml` causes `build_for_all_formats` to be set to `False` but that this does not prevent the wheel from being built. See the `if build_for_all_formats` line, here we jump to the `else` and the wheel is always built.

**Comment by finswimmer** [comment]
Hello @george-hawkins,

the `format` is only available in the `pyproject.toml` for explicit included files, to limit the inclusion to only one build format. See https://python-poetry.org/docs/master/pyproject/#include-and-exclude

There is no general option, to say: Build only a "sdist" or "wheel", regardless o the cli parameter.

fin swimmer
