### ISSUE TITLE
Set user agent for pip install

### ISSUE THREAD

**Issue by jtrakk** [python-poetry/poetry#2367]
[Pip now supports](https://pip.pypa.io/en/stable/news/#id195) an environment variable `PIP_USER_AGENT_USER_DATA` that will let PyPI report statistics on how many downloads happen via Poetry. That would be nice for marketing and to inform decisions based on which packages Poetry users use.

**Comment by pradyunsg** [comment]
PyPI's BigQuery database doesn't expose the key that's being set by pip there, so it is unlikely that it would allow for checking download counts.

The best approach would likely be to set the user agent directly, but IIRC, pip hasn't added that functionality yet.

**Comment by jtrakk** [comment]
Sure. The custom user-agent feature was only merged into pip last week. There probably isn't a lot of interesting variation in the PyPI data yet. Setting the environment variable from Poetry would make it more worthwhile for PyPI to start presenting that data.
