### ISSUE TITLE
breaking change: invert --remove-untracked to --keep-untracked

### ISSUE THREAD

**Issue by seansfkelley** [python-poetry/poetry#2370]
Now that https://github.com/python-poetry/poetry/pull/2172 is merged to address https://github.com/python-poetry/poetry/issues/648 (yay!), I'd like to propose a breaking change to switch the default from keeping untracked files to removing them.

It seems like the main reason that `--remove-untracked` was chosen over `--keep-untracked` was for backwards compatibility concerns, per https://github.com/python-poetry/poetry/issues/648#issuecomment-600514025. https://github.com/python-poetry/poetry/issues/648#issuecomment-594747724 and other comments on that issue generally lean towards remove-by-default as the preferred behavior.

I filed this as a tracking issue under the assumption that it'll have to wait around for v2.

See also the philosophically-related https://github.com/python-poetry/poetry/issues/3248.

**Comment by PetterS** [comment]
May be better with an option in pyproject.toml to opt in to always remove untracked.

**Comment by seansfkelley** [comment]
> May be better with an option in pyproject.toml to opt in to always remove untracked.

That's a good path forward leading up to a breaking change, but I'm specifically making this suggestion as a breaking change because I think it makes the default behavior less surprising and more in line with dependency management in other languages. I left more thoughts about this at https://github.com/python-poetry/poetry/issues/648#issuecomment-483064487 as well.

**Comment by finswimmer** [comment]
Note: `--remove-untracked` will be renamed into `--sync` in poetry 1.2.

We've decided that the default behavior is to never remove any packages from a venv unless this option is given. Due to the number of issues about it, it seems to be the expected behavior for many users.
