### ISSUE TITLE
AttributeError on running "poetry install"

### ISSUE THREAD

**Issue by pavdmyt** [python-poetry/poetry#2372]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS Mojave, version 10.14.6
- **Poetry version**: 1.0.5

## Issue

Having a `pyproject.toml` with the following `tool.poetry.dependencies` section: 

```
[tool.poetry.dependencies]
python = "~2.7, >=3.4, <3.8"
```

Running `poetry install` results in `AttributeError`:

```
$ poetry install -vvv

[AttributeError]
EmptyConstraint instance has no attribute 'min'

Traceback (most recent call last):
  File "/Users/me/.poetry/lib/poetry/_vendor/py2.7/clikit/console_application.py", line 131, in run
    status_code = command.handle(parsed_args, io)
  File "/Users/me/.poetry/lib/poetry/_vendor/py2.7/clikit/api/command/command.py", line 120, in handle
    status_code = self._do_handle(args, io)
  File "/Users/me/.poetry/lib/poetry/_vendor/py2.7/clikit/api/command/command.py", line 163, in _do_handle
    self._dispatcher.dispatch(PRE_HANDLE, event)
  File "/Users/me/.poetry/lib/poetry/_vendor/py2.7/clikit/api/event/event_dispatcher.py", line 22, in dispatch
    self._do_dispatch(listeners, event_name, event)
  File "/Users/me/.poetry/lib/poetry/_vendor/py2.7/clikit/api/event/event_dispatcher.py", line 89, in _do_dispatch
    listener(event, event_name, self)
  File "/Users/me/.poetry/lib/poetry/console/config/application_config.py", line 86, in set_env
    poetry = command.poetry
  File "/Users/me/.poetry/lib/poetry/console/commands/command.py", line 10, in poetry
    return self.application.poetry
  File "/Users/me/.poetry/lib/poetry/console/application.py", line 49, in poetry
    self._poetry = Factory().create_poetry(Path.cwd())
  File "/Users/me/.poetry/lib/poetry/factory.py", line 90, in create_poetry
    package.python_versions = constraint
  File "/Users/me/.poetry/lib/poetry/packages/project_package.py", line 45, in python_versions
    create_nested_marker('python_version', self._python_constraint)
  File "/Users/me/.poetry/lib/poetry/packages/utils/utils.py", line 214, in create_nested_marker
    if constraint.min is not None:
```

However, `poetry check` returns no errors:

```
$ poetry check
All set!
```

So, I'm making a conclusion that `python = "~2.7, >=3.4, <3.8"` is a valid version constraint.

**Comment by abn** [comment]
@pavdmyt I beielve the constraint you are looking for is `^2.7 || >=3.4 <3.8`.

**Comment by pavdmyt** [comment]
@abn Thanks! I didn't find OR operator in docs.

My point is more about that in described case the `AttributeError: EmptyConstraint instance has no attribute 'min'` is not really helpful and `poetry check` accepts obviously invalid requirement: `python = "~2.7, >=3.4, <3.8"`, without failure.

**Comment by andreoliwa** [comment]
I'm having the same error on Poetry 1.0.9.

The package I'm trying ([AuHau/toggl-cli](https://github.com/AuHau/toggl-cli/blob/master/setup.cfg#L10)) has:

```
python_requires = >=3.6.0, <3.9.0
```

This is my debug info, and a gist below with `pyproject.toml` and the full error log.
```
Poetry
Version: 1.0.9
Python:  3.8.3

Virtualenv
Python:         3.8.3
Implementation: CPython
Path:           /Users/wagneraugusto/Library/Caches/pypoetry/virtualenvs/toggl-cli-bug-t9z0mPRw-py3.8
Valid:          True

System
Platform: darwin
OS:       posix
Python:   /Users/wagneraugusto/.pyenv/versions/3.8.3
```

[Poetry [AttributeError] 'EmptyConstraint' object has no attribute 'min'](https://gist.github.com/andreoliwa/252642640bd51ba958ddd01dcdde2de8)

(Note: yesterday I didn't see this open issue, so I left [the same comment](https://github.com/python-poetry/poetry/issues/534#issuecomment-648487291) on #534, which I believe is a closed duplicated issue)

**Comment by nikmolnar** [comment]
I'm experiencing this error in Poetry 1.1.5 when python `^2.7` and pytest are both listed. Here is a minimal example:

```toml
[tool.poetry]
name = "poetry-bug"
version = "0.1.0"
description = ""
authors = ["Me"]

[tool.poetry.dependencies]
python = "^2.7"

[tool.poetry.dev-dependencies]
pytest = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

Running `poetry lock` will result in the aforementioned `EmptyConstraint` error. Changing the Python version to `^3.6` or removing the `pytest` dev dependency will work correctly.

**Comment by pawamoy** [comment]
Experiencing the same thing with `python = "^3.6"`.

**Comment by kitanata** [comment]
👍 Also encountering this issue today.

**Comment by jedie** [comment]
I ran into this bug, too. And yes, it's caused by **pytest-randomly**

Work-a-round: **pytest-randomly = "!=3.6.0"**

But i think poetry should raise a better error messages than this:

![grafik](https://user-images.githubusercontent.com/71315/113577208-31e35000-9621-11eb-986a-d22be14d1755.png)

Think we should get the package name that caused the error, isn't it?

**Comment by mforbes** [comment]
This is probably a documentation issue. According to [the docs](https://python-poetry.org/docs/dependency-specification/#multiple-requirements):

> Multiple version requirements can also be separated with a comma, e.g. `>= 1.2, < 1.5`.

This should probably explicitly state that a comma in this corresponds to logical and, and an example with logical or `||` should be included.
