### ISSUE TITLE
RecursionError when installing mkdocs-material

### ISSUE THREAD

**Issue by ndevln** [python-poetry/poetry#2376]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows 10 Pro 1909 18363.719
- **Poetry version**:  1.0.5
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/ndevln/f27b5b64251241d40e1b960ec96b8b68

## Issue
Hi,

when running: `poetry install -E docs_material` I get the following error:

```
[RecursionError]
maximum recursion depth exceeded
```

There are quite a few similar issues (like #2329), but it seems that this problem is package specific?!?

Thank you for poetry and your effort :)

**Comment by ndevln** [comment]
Could be fixed by #2342 and #2361. I can test it when these PR are part of the pre-release version.

**Comment by ndevln** [comment]
The problem persists in 1.1.0a2 (and 1.0.9). 

```
Installing dependencies from lock file

  RecursionError

  maximum recursion depth exceeded

  at ~\.poetry\lib\poetry\utils\extras.py:47 in <genexpr>
      43│             if package:
      44│                 yield package.name
      45│                 # Recurse for dependencies
      46│                 for dependency_package_name in _extra_packages(
    → 47│                     dependency.name for dependency in package.requires
      48│                 ):
      49│                     yield dependency_package_name
      50│
      51│     return _extra_packages(extra_package_names)

```

**Comment by sdispater** [comment]
@ndevln When using 1.1.0a2 did you regenerate your lock file?

**Comment by ndevln** [comment]
I did not.

I tried again with 1) regeneration the lock file, 2) deleting the lock file and creating it new. For my last test I used the minimal example from the gist above and created a new virtual environment. But still all 3 tests resulted in the same error. Sry
