### ISSUE TITLE
Cannot select Python version in pyproject.toml

### ISSUE THREAD

**Issue by certik** [python-poetry/poetry#2382]
I have installed poetry by following: https://python-poetry.org/docs/ on Ubuntu 18.04:
```
curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
```
note that the default python in Ubuntu 18.04 is Python 2.7. I then created my first project:
```
poetry new t1
cd t1
```
Then I upgraded to Python 3.8:
```diff
diff --git a/pyproject.toml b/pyproject.toml
index 279ce97..4335789 100644
--- a/pyproject.toml
+++ b/pyproject.toml
@@ -5,7 +5,7 @@ description = ""
 authors = ["Ondřej Čertík <ondrej@certik.us>"]
 
 [tool.poetry.dependencies]
-python = "^2.7"
+python = "^3.8"
 
 [tool.poetry.dev-dependencies]
 pytest = "^4.6"
```
and install the dependencies:
```
$ poetry install
/home/ondrej/.poetry/lib/poetry/_vendor/py2.7/subprocess32.py:149: RuntimeWarning: The _posixsubprocess module is not being used. Child process reliability may suffer if your program uses threads.
  "program uses threads.", RuntimeWarning)
Updating dependencies
Resolving dependencies... (0.1s)

Writing lock file

No dependencies to install or update

  - Installing t1 (0.1.0)

[EnvCommandError]
Command ['/home/ondrej/.cache/pypoetry/virtualenvs/t1-Lx7eoTS_-py2.7/bin/pip', u'install', u'-e', '/tmp/t1'] errored with the following return code 1, and output: 
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Obtaining file:///tmp/t1
ERROR: Package 't1' requires a different Python: 2.7.17 not in '>=3.8,<4.0'
WARNING: You are using pip version 19.3.1; however, version 20.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```
And it fails.

**Comment by melMass** [comment]
`poetry update` should reinstall the env

**Comment by PfeifferJosef-96** [comment]
Maybe a bit late - but you could try to run: 
```shell
poetry env use python3.8

```
See: [Poetry - Switching between environments](https://python-poetry.org/docs/managing-environments/#switching-between-environments)

**Comment by finswimmer** [comment]
Hello @certik ,

it looks like you are still in your python2 venv, because of the path given here:

```
Command ['/home/ondrej/.cache/pypoetry/virtualenvs/t1-Lx7eoTS_-py2.7/bin/pip', u'install', u'-e', '/tmp/t1'] errored with the following return code 1, and output
```

Restart your terminal to get out of it and run `poetry install` again.

fin swimmer

**Comment by finswimmer** [comment]
Hello @certik,

we haven't heard something from you for a long time now. So I guess you issue is solved?

I will close this ticket. Feel free to leave a comment if you disagree.

fin swimmer

**Comment by certik** [comment]
I haven't used poetry since I reported this, so you can close it. 

Good luck with poetry, the idea behind it is the way to go (in my opinion). We recently started a Fortran Package Manager (https://github.com/fortran-lang/fpm/), modeled by Cargo also. I believe both Cargo and fpm is a lot simpler than a package manager for Python, because the majority of code for Rust is in Rust, and Fortran in Fortran. But Python code contains C, C++ and Fortran often times, and it's this compiled code that fails many times in my experience. I don't even know to be honest what the best approach is for Python because of that. I am personally just concentrating on Fortran now, and see if we can figure out a good solution there. One of our goals is to be able to take care of the Fortran side of things for other languages such as Python down the road.
