### ISSUE TITLE
Dependencies are unordered in pyproject.toml when installed with `poetry add`

### ISSUE THREAD

**Issue by nmay231** [python-poetry/poetry#2383]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Feature Request

This is a minor issue, but having your dependencies ordered can help you when manually scanning the `pyproject.toml` for the dependencies you have installed. As an example, if you install pytest and black, in that order, dependencies will currently be listed like so:

```
[tool.poetry.dependencies]
python = "^3.8"
pytest = "^5.4.1"
black = "^19.10b0"
```

I think it would be beneficial to list all dependencies with python first and all others in alphabetical order no matter which order you installed them in. E.g.

```
[tool.poetry.dependencies]
python = "^3.8"
black = "^19.10b0"
pytest = "^5.4.1"
```

I would be willing to implement this myself if the maintainers are open to the change.

**EDIT:**

I gave this a shot, but there is a big issue.

`poetry add` should not rearrange the (dev-)dependencies sections when there are comments/whitespace because these might represent manual grouping of packages. As an example, poetry's [pyptoject.toml](https://github.com/python-poetry/poetry/blob/9f5cedfc373272616f9c3dcb7f4cb320a299da47/pyproject.toml#L41:L58) lists all of the dependencies for python2 after the regular dependencies.

I actually anticipated this, but I didn't expect it to be as big of an issue. At the moment, the library used to manipulate toml files (`tomlkit v0.5.11`) does not have a convenient method to change table values *and* the comments/whitespace in them. The only way I found to do it is to mung with the internal values of the table, and even that does not produce the correct results (randomly inserted newlines, etc).

Note for the maintainers: Feel free to close this if you do not feel it is worth the trouble for you yourselves to implement this.

**Comment by Object905** [comment]
For people using vscode.

Extension [Even Better TOML](https://marketplace.visualstudio.com/items?itemName=tamasfe.even-better-toml) has formatting option `evenBetterToml.formatter.reorderKeys` that sorts keys not separated by empty lines, which does the job.

**Comment by finswimmer** [comment]
Hello @nmay231,

as you said, developer might have an intention how they sorted the dependencies. So poetry shouldn't change anything here.

fin swimmer

**Comment by nyuszika7h** [comment]
That's exactly why there was a proposed solution to that (allow dependency groups separated by whitespace which would be left alone). I don't think we should need an external tool to clean up after poetry's mess. Editor plugins are not a very helpful solution to this when the whole point is that I don't want to have to open pyproject.toml every time I add a new dependency. It would be nice to have this at least as an option in poetry (doesn't even necessarily have to be the default). But if not, I suppose a pre-commit hook would be a better alternative than editor plugins.
