### ISSUE TITLE
Support PEP440 version specifiers in Poetry installer

### ISSUE THREAD

**Issue by sisp** [python-poetry/poetry#2385]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

I suggest adding support for installing Poetry using the `get-poetry.py` installer script with a version specifier, e.g. `python get-poetry.py --version ^1.0.5`. This could be useful in CI pipelines where the latest compatible-release version shall be installed. I think it should be relatively easy to implement this feature as the available releases can be extracted from PyPI as already done in `get-poetry.py`. Comparing versions with [`packaging`](https://packaging.pypa.io/en/latest/) would probably be easiest, but it's not part of the standard library.

**Comment by TheErk** [comment]
Did you try with env var?
POETRY_VERSION=1.0.5 python get-poetry.py

this should already work.

**Comment by funkyfuture** [comment]
the `^` specifier is *not* [PEP-440](https://www.python.org/dev/peps/pep-0440/#version-specifiers) compliant.

**Comment by sisp** [comment]
My bad, you're right. I meant the compatible release clause, so the PEP-440 compliant example would be `python get-poetry.py --version ~=1.0.5`.

**Comment by Secrus** [comment]
`get-poetry.py` script is outdated and will be removed in Poetry 1.2 release. New `install-poetry.py` script supports version option: https://python-poetry.org/docs/master/#installing-with-the-official-installer
