### ISSUE TITLE
Running deactivate inside a poetry shell breaks it

### ISSUE THREAD

**Issue by jjconti** [python-poetry/poetry#2387]
- [ ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

- **OS version and name**: macOS Catalina
- **Poetry version**: 1.0.5

## Issue

After running `poetry shell` I tried to exit running `deactivate`. That deactivated the virtualenv, that is, I was not able to access anymore the version of de libs installed for my project.
But when I tried to run `poetry shell` again, I got this message:

`Virtual environment already activated...`

Then I discovered I should exit using the `exit` command.

I think the `deactivate` command should be disabled inside the poetry shell.

**Comment by 0xF4D3C0D3** [comment]
I totally agree with this and if it is allowed I think it would be better that don't depend on the environment variable

**Comment by finswimmer** [comment]
Hello, 

the reason for this behavior is, that `poetry shell` does two things:

1. start a new shell
2. activate the virtual environment

The command `deactivate` is provided by the venv and `exit` is provided by the shell itself. `poetry` has no influence on that commands.

So to leave the env and the shell using `exit` is the intended way.

fin swimmer

**Comment by 0xF4D3C0D3** [comment]
@finswimmer Oh, I see. I hadn't been accustomed to `poetry shell` but I understand it now. Thank you for your reply.

**Comment by cwkang1998** [comment]
I think this should be included in the documentation on the shell command here: https://python-poetry.org/docs/cli/#shell.
May I add a pull request to indicate the use of `exit` instead of `deactivate` ?

**Comment by bencwallace** [comment]
> I think this should be included in the documentation on the shell command here: https://python-poetry.org/docs/cli/#shell. May I add a pull request to indicate the use of `exit` instead of `deactivate` ?

Are you going to do this? I have time to do this as well.

**Comment by cwkang1998** [comment]
> > I think this should be included in the documentation on the shell command here: https://python-poetry.org/docs/cli/#shell. May I add a pull request to indicate the use of `exit` instead of `deactivate` ?
> 
> Are you going to do this? I have time to do this as well.

Yup. Sorry, I didn't get an email for this until now so I didn't know I got a go. I'll add it by today and submit the PR.
