### ISSUE TITLE
Standardizing the ^ version specifier

### ISSUE THREAD

**Issue by pradyunsg** [python-poetry/poetry#2390]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Issue

Would poetry's maintainers be willing to help standardize the `^1.0.0` style version specifier, as a broader Python Packaging standard? Any indication on whether this is a priority or not?

**Comment by pradyunsg** [comment]
Nudge.

**Comment by funkyfuture** [comment]
it is equivalent to `~=` from [PEP-440](https://www.python.org/dev/peps/pep-0440/#version-specifiers), isn't it?

**Comment by sdispater** [comment]
Not strictly a priority but, ideally, it would be good to see it standardized, along with the `||` operator, to avoid cases like this: `>=2.7,!=3.0.*,!=3.1.*,3.2.*,3.3.*,3.4.*` (it could be simplified to `^2.7 || >=3.5`

**Comment by neersighted** [comment]
@pradyunsg It's been a long time -- still interested in this? I get the impression that several PyPA members may be opposed to this syntax.

**Comment by Secrus** [comment]
@pradyunsg nudge.

**Comment by pradyunsg** [comment]
Oh, I won't be driving this personally -- it's not a priority for me and not something that I personally care much about.

I've since have had my understanding/opinion change around this operator, based on discussions with multiple folks, that the semantics of this are the wrong approach for code that claims to be a reusable chunk of code (i.e. library) but is fine/good for a non-reusable piece (i.e. application), but I digress.
