### ISSUE TITLE
Specify version for git dependency

### ISSUE THREAD

**Issue by tbenst** [python-poetry/poetry#2391]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request
poetry is unable to parse all valid `setup.py` files, [by design](https://github.com/python-poetry/poetry/issues/2176#issuecomment-598880700). As such, I do not believe it's currently possible to install [CaImAn](https://github.com/flatironinstitute/CaImAn) with poetry, as [version info is read from another file](https://github.com/flatironinstitute/CaImAn/blob/master/setup.py#L22).

I suggest that we allow specifiying `version` for git repos: 

```
caiman = { git = "https://github.com/flatironinstitute/CaImAn.git", tag = "v1.8.4", version="1.8.4" }}
```

**Comment by mjlbach** [comment]
I just ran into this issue installing vispy (poetry add git+https://github.com/vispy/vispy.git)

**Comment by jfaleiro** [comment]
similar issue on `path` dependencies as well

**Comment by fugkco** [comment]
A vote from me too. This should also help in cases where the original package doesn't have a `setup.py` at all.

**Comment by fugkco** [comment]
This should also help in cases where the original package doesn't have a setup.py at all, as it the case with me.

**Comment by synek** [comment]
+1

I need this.

**Comment by ntoshev** [comment]
[nbdev](http://nbdev.fast.ai/)-generated packages' version can't be retrieved by Poetry too.

**Comment by finswimmer** [comment]
Poetry is able to get metadata, that are generated dynamically, for a longer time now.
