### ISSUE TITLE
Project package not installed by `poetry install`

### ISSUE THREAD

**Issue by jlevers** [python-poetry/poetry#2397]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 18.04.4
- **Poetry version**: 1.0.5
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: [pyproject.toml](https://gist.github.com/jlevers/dd5ef08527b43e994642430b4109fa85)

## Issue
When I run `poetry install` _without_ `--no-root`, my project package is not installed. This has been an issue for me across multiple projects. I expected that the project I'm working on would be installed by `poetry install`, because that's what it says in the [docs](https://python-poetry.org/docs/cli/#install): `By default poetry will install your project's package everytime you run install`. 

When I run `poetry run pip install -e .`, my package is installed as expected.

**Comment by finswimmer** [comment]
Hello @jlevers,

how does your folder structure looks like. According to your pyproject.toml there must be a folder `app_api` at the same level and it must contain a `__init__. py`.

fin swimmer

**Comment by jlevers** [comment]
Ah, totally misunderstood the expected file structure. That fixes it. Sorry for the faulty bug report.
