### ISSUE TITLE
Poetry chooses the wheel package for a different Python version

### ISSUE THREAD

**Issue by jakobkogler** [python-poetry/poetry#2401]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Linux 5.4.36-1-MANJARO x86_64
- **Poetry version**: 1.0.5
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/jakobkogler/02dff357fd0b1fa077026ab0cc15eba7

## Issue

I'm trying to install the library [scrapy-rss](https://pypi.org/project/scrapy-rss).
On Pypi there are multiple different wheels, one for each Python version. Those wheels have actually different dependencies. The wheel `scrapy_rss-0.1.9-py38-none-any.whl ` (for Python 3.8.2) simply has the dependency `scrapy>=1.3.1`, while the wheel `scrapy_rss-0.1.9-py33-none-any.whl` has the dependency `scrapy<1.5.0`. 

I'm using Python 3.8.2 inside the poetry virtualenv. If I download the 38 wheel, and manually install it with `poetry add ./scrapy_rss-0.1.9-py38-none-any.whl`, it will install fine and choose the newest version of `scrapy`, namely `scrapy=2.1.0`. However If I just say: `poetry add scrapy-rss`, it will install the 33 wheel, and demand the scrapy version `scrapy=1.4.0`. 

Why does poetry pick the wrong wheel in this case? 

Here's the output of `poetry add`:

```
>> poetry add "scrapy-rss" --dry-run -vvv 
Using virtualenv: /home/jakob/.cache/pypoetry/virtualenvs/aab-HyhLZxPz-py3.8
PyPI: No release information found for scrapy-rss-0.1.2, skipping
PyPI: 9 packages found for scrapy-rss *
Using version ^0.1.9 for scrapy-rss

Updating dependencies
Resolving dependencies...
   1: fact: aab is 0.1.0
   1: derived: aab
   1: fact: aab depends on scrapy-rss (^0.1.9)
   1: selecting aab (0.1.0)
   1: derived: scrapy-rss (^0.1.9)
PyPI: No release information found for scrapy-rss-0.1.2, skipping
PyPI: 1 packages found for scrapy-rss >=0.1.9,<0.2.0
   1: fact: scrapy-rss (0.1.9) depends on cryptography (<2.0)
   1: fact: scrapy-rss (0.1.9) depends on pyOpenSSL (<17.3.0)
   1: fact: scrapy-rss (0.1.9) depends on python-dateutil (*)
   1: fact: scrapy-rss (0.1.9) depends on scrapy (<1.5.0)
   1: fact: scrapy-rss (0.1.9) depends on six (*)
   1: selecting scrapy-rss (0.1.9)
...
```

Btw, `pip` will choose the correct version. In a new virtualenv, running `pip install scrapy-rss` will install the 38 wheel. So this must be a bug on the poetry side.

**Comment by mikenerone** [comment]
Duplicates #2284
