### ISSUE TITLE
Cannot use multiple environment per project with virtualenvs.in-project=True

### ISSUE THREAD

**Issue by melMass** [python-poetry/poetry#2404]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **Mojave 10.4.6**: 
- **Poetry version 1.0.5**: 

## Issue

Hi,

I'm switching from Pipenv to Poetry, and for now, it's been all for the better!

One aspect of poetry that I like a lot it multiple environments per project [As shown in the doc here](https://python-poetry.org/docs/managing-environments/)

The first setting I set in Poetry was virtualenvs.in-project which create a `.venv` in the project root.

Now let's say I want to be able to run tests on both python 2 and python 3, one cannot just switch the environment but the environment gets overwritten.

Is there a way to use both features at the same time? If so how?

Thanks a lot

**Comment by finswimmer** [comment]
Hello @melMass,

if you have an in-project virtual environment this will always take precedence over any other location. So if you plan to use multiple envs you have to set in-project to false. This can be done also on a per project base using the `--local` parameter.

fin swimmer

**Comment by melMass** [comment]
Hello @finswimmer,

Thanks for the confirmation, is there a reason for this? 
Can't we create a `.venv2.7.15` & `.venv3.7.xx` and use `poetry use` to switch between them?

The general idea is that I don't write anything to the system disk (well as little as possible).
I don't like the concept of having a general place for all envs but if there is no plan for any of this I will find a way using custom path and your `--local` trick for the projects that use multiple python!

**Comment by finswimmer** [comment]
Hello again,

I just made a short test, but it looks like `poetry config virtualenvs.path ./` would achieve what you are asking for.

**Comment by melMass** [comment]
Perfect !!

This is exactly what I was after.
I will look into it but is there a way to customize the name of the folder :) ?

**Comment by finswimmer** [comment]
Fine :)

You cannot modify the name of the virtual environment folder itself. `poetry` expect a specific format to be able to find the correct venv for the project and python version. With `virtualenvs.path` you just define the place where it should search.

fin swimmer

**Comment by melMass** [comment]
Thanks for the support!
Yes I realized the names weren’t random but linked to the project which is fine also.

Coming from pipenv poetry has been a bless!!
