### ISSUE TITLE
Installer: suppress profile modification via script parameter or environment variable

### ISSUE THREAD

**Issue by sergei-ivanov** [python-poetry/poetry#2408]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

There are cases when `$PATH` is managed by other tools, for example `asdf` creates shims for the tools that it installs. We use `asdf` combined with `direnv` for automatic tool installation and configuration per project. In our case it would be good to suppress the prompt for `~/.profile` modification in the Poetry installer and skip that step altogether.

There already is a class member called `modify_path` in the installer script, but there is no way to set it to `False` upfront. The proposal is to add a command line parameter and an environment variable, so that by setting them the calling script can suppress profile modification and the associated prompt.

**Comment by sergei-ivanov** [comment]
I had a pull request ready against `master`, but I have just realised that someone else has already implemented the changes in `develop`: b6f849ea54003e10884533cb5c4fa409e65ca799. I traced it back to #2292. Feel free to close this issue or add it to future release notes instead.

**Comment by dbalabka** [comment]
I support @sergei-ivanov idea. Recently, faced with the following situation:
```
# .bash_profile  # Get the aliases and functions if [ -f ~/.bashrc ]; then         . ~/.bashrc fi  # User specific environment and startup programs  PATH=$PATH:$HOME/.local/bin:$HOME/bin  export PATH  export PATH="$HOME/.poetry/bin:$PATH"  export PATH="$HOME/src/releases/1/.poetry/bin:$PATH"  export PATH="$HOME/src/releases/2/.poetry/bin:$PATH"  export PATH="$HOME/src/releases/3/.poetry/bin:$PATH"  export PATH="$HOME/src/releases/4/.poetry/bin:$PATH"  export PATH="$HOME/src/releases/5/.poetry/bin:$PATH"  export PATH="$HOME/src/releases/6/.poetry/bin:$PATH"  export PATH="$HOME/src/releases/7/.poetry/bin:$PATH"  export PATH="$HOME/src/releases/8/.poetry/bin:$PATH"  export PATH="$HOME/src/releases/9/.poetry/bin:$PATH"  export PATH="$HOME/src/releases/10/.poetry/bin:$PATH"  export PATH="$HOME/src/releases/11/.poetry/bin:$PATH"  export 
...
```
Poetry constantly adding new paths into profile which are useless, because I'm using `in-project=true` to install dependencies for each new release. 

It would be great to disable the profile modification in `poetry.toml`.

**Comment by abn** [comment]
Poetry's new installer `install-poetry.py` no longer modifies the profiles. This should be resolved as `get-poetry.py` is now deprecated and will be removed soon.
