### ISSUE TITLE
Non-semver packages cannot be specified as "*"

### ISSUE THREAD

**Issue by SwampFalc** [python-poetry/poetry#2413]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

Possibly somewhat related to #1505 

I would like to add black as a dev-dependency. I honestly don't care what version (we'll see what happens if I ever run into an uncompatible version) so I started out with ``poetry add black`` and then I edited the pyproject.toml to read ``black = "*"``. Yet whenever I try using it like that, I get this error:

```
 [SolverProblemError]
Because fedasit depends on black (*) which doesn't match any versions, version solving failed.
```

I removed black and then tried to add it back in using ``poetry add black@*" and that failed in the exact same way.

I have other packages listed as ``"*"`` in my project (pylint f.ex.) and those work fine, with the major difference being that those use semver and black doesn't...

So I am assuming there is a bug in the code that makes ``"*"`` not match anything that is not semver...

**Comment by PetterS** [comment]
It is because black only has pre-releases. You have to allow prereleases.

**Comment by SwampFalc** [comment]
Aha, that does indeed work, thanks.
