### ISSUE TITLE
Always use virtualenv 20.x

### ISSUE THREAD

**Issue by Senpos** [python-poetry/poetry#2420]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

It is been a while, since [`virtualenv`](https://github.com/pypa/virtualenv) was completely rewritten.
The new version (`20.x`) and is [a lot faster](https://twitter.com/sethmlarson/status/1229816638733737990) than both Python's built-in `venv` module and `virtualenv 16.x`.

It might be a good idea to always use new `virtualenv 20.x` in `poetry`.

At the moment, [`poetry` uses `virtualenv` only for older Python versions](https://github.com/python-poetry/poetry/blob/develop/pyproject.toml#L48).
In other cases, it uses `venv`.

I can see why Python may use an older and cut version of `virtualenv` in the standart library, it may be hard to maintain a bleeding-edge software.

But this change may add some value to such a modern dependency & enviroment management tool like `poetry`.

Would love to see `poetry` running even faster! :)

**Comment by finswimmer** [comment]
Hello @Senpos ,

can you imagine more benefits beside that the initial creation of a venv reduces from 2 to 0.2 seconds?

fin swimmer

**Comment by pradyunsg** [comment]
@finswimmer You can find more details in the original RFC for the virtualenv 20.0 rewrite: https://github.com/pypa/virtualenv/issues/1366

**Comment by Senpos** [comment]
Since #2666 is merged, should I close the issue? :)
