### ISSUE TITLE
Improve poetry export help

### ISSUE THREAD

**Issue by ChristianSauer** [python-poetry/poetry#2423]
- [x ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x ] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request
poetry export --help does not list the available formats, e.g.
`
poetry export -f --help
USAGE
  poetry export [-f <...>] [-o <...>] [--without-hashes] [--dev] [-E <...>] [--with-credentials]

OPTIONS
  -f (--format)          Format to export to.
`
Running poetry export -f pip (or any other invalid value) also returns a generic error.

Since requirements.txt is the only allowed value, it would be great if poetry export would mention that.
Sure, it's mentioned in the docs, but I like to be able to use the cmd without consulting docs if possible.

**Comment by SanketDG** [comment]
This is already fixed by https://github.com/python-poetry/poetry/commit/9e1324e1fbf4d42141dce959d877571d424ee8aa

@ChristianSauer can you try it with the pre-release?

**Comment by ChristianSauer** [comment]
Will do, thx!
