### ISSUE TITLE
Request: poetry add <package> --markers="<environment marker>"

### ISSUE THREAD

**Issue by mickeykkim** [python-poetry/poetry#2425]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

`poetry add` does not currently accept an option to set a marker, e.g.:

`poetry add smbus2 --markers="platform_machine == 'armv7l'"` ->

`smbus2 = {version = "^0.3.0", markers = "platform_machine == 'armv7l'" }`

This would be useful to add a dependency without having to write it in `pyproject.toml` manually and running `poetry update`, which may undesirably update other dependencies.

**Comment by Secrus** [comment]
This is already added to the incoming `1.2` release. Check out master branch.

**Comment by jdratlif** [comment]
```
$ poetry add -G dev ansible-lint --markers='platform_system != "Windows"'
Creating virtualenv ansib-BvRGSxlr-py3.8 in /home/jdratlif/.cache/pypoetry/virtualenvs

The option "--markers" does not exist
```

I'm using poetry 1.4.0. Am I using the command wrong, because it doesn't seem like it was added.

**Comment by NicoLivesey** [comment]
Hey just to confirm there currently no way to specify `--markers` from command line ?
