### ISSUE TITLE
How to use poetry just to manage my dependencies

### ISSUE THREAD

**Issue by kaldown** [python-poetry/poetry#2430]
> Poetry is a tool for dependency management and packaging in Python. It allows you to declare the libraries your project depends on and it will manage (install/update) them for you.

`poetry init` asks too much questions that aren't related to manage dependencies. This is a responsibility violation in my opinion. If I ever want to publish package - I will call other procedures to establish product scaffolding. Now i just want my dependencies to take decent management.

_My point is_ - I expecting **Poetry** to work the similar way **Pipenv** does.

How to achieve my goal straight away?

_More precise example_:
This project [python-trio](https://github.com/python-trio/trio/blob/master/pyproject.toml) already has **pyproject.toml** .
I won't add anything that is not mandatory and probably wouldn't be convenient for other developers.

Now with all of that explanation oif a situation:
How to use **Poetry** for my local development, without making unnecessary commits?

**Comment by SanketDG** [comment]
You can use poetry to _just_ manage your dependencies, it's not that problematic. You can also take a look at `pip-tools` if you just need version pinning.

> `poetry init` asks too much questions

Just pass `--no-interaction`


> How to use **Poetry** for my local development, without making unnecessary commits?

What unnecessary comments?

**Comment by kaldown** [comment]
Thank you. Hm

> What unnecessary comments?

using Poetry without making changes into existent file. Otherwise, I would need remove indexing from **pyproject.toml** in order to not interfere with others, who won't use Poetry.


> Just pass --no-interaction
```
poetry init -n
A pyproject.toml file already exists.
```

Sorry, I don't want to be mean, just confused a bit with the interface. Still can't find an answer in this situation.

**Comment by SanketDG** [comment]
> Asking from the other side: how to split production and development dependencies?

https://github.com/python-poetry/poetry/blob/master/pyproject.toml

`tool.poetry.dependencies` and `tool.poetry.dev-dependencies`

> using Poetry without making changes into existent file. Otherwise, I would need to remove indexing from **pyproject.toml** in order to not interfere with others, who won't use Poetry.

I don't get your usecase at all. Maybe you can explain a bit more or someone else can understand.

**Comment by kaldown** [comment]
I think it's worthless to try any workaround. Especially when it's hard to explain a problem which is inconvenient for the framework to deal with. Just using `virtualenv` seems okay.

Thank you.
