### ISSUE TITLE
Ability to specify installtion directory in editable install from git repository

### ISSUE THREAD

**Issue by mhtb32** [python-poetry/poetry#2431]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request
When installing a package with `pip` as editable, you can specify installation directory like:
```Shell
pip install -e some-pkg --src <dir>
```
Since poetry installs git dependencies as editable by default, it would be useful if the user can specify the installation directory other than the default one(which is in the src folder of virtualenv's directory).

**P.S**: it may be related to #1816

**Comment by dimbleby** [comment]
duplicate #2188
