### ISSUE TITLE
Optional dev-dependencies do not install

### ISSUE THREAD

**Issue by daegontaven** [python-poetry/poetry#2432]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: `Ubuntu 20.04 LTS`
- **Poetry version**: `1.0.5`
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: [pyproject.toml](https://gist.github.com/daegontaven/7dcf9d32ead02fc1bc7a8add82ac5f95)

### Expected Result
`poetry install -E "docs tests build_tools"` will install [`extras`](https://gist.github.com/daegontaven/7dcf9d32ead02fc1bc7a8add82ac5f95#file-pyproject-toml-L42-L55) defined in [`dev-dependencies`](https://gist.github.com/daegontaven/7dcf9d32ead02fc1bc7a8add82ac5f95#file-pyproject-toml-L31-L37)

### Actual Result
`poetry install -E "docs tests build_tools"` does not install any of the [`dev-dependencies`](https://gist.github.com/daegontaven/7dcf9d32ead02fc1bc7a8add82ac5f95#file-pyproject-toml-L31-L37).

**Comment by ndevln** [comment]
Duplicate? #606

**Comment by dekoza** [comment]
Duplicate of #2073

**Comment by daegontaven** [comment]
#606 is a pull request that was closed. #2073 isn't even about dev-dependencies. Still closing this since #606 mentions that it's not possible to solve.
