### ISSUE TITLE
virtualenv path name

### ISSUE THREAD

**Issue by shiveringbulbul** [python-poetry/poetry#2438]
Are there any arguments that could make the folder name without random letters, when I do `poetry init`?

I don't want the name like this `**MY_NAME**-U7NkVg5Y-py3.7`.

**Comment by 0xF4D3C0D3** [comment]
the poetry virtualenv is basically system global unless you set the `virtualenvs.in-project` to true. Therefore, It could be conflicted with other directories within another path like /.../foo/spam, /.../bar/spam. That's the reason why poetry uses hash(that random letters) as the whole path.

If you wanna make a virtualenv without that random letters, how about
`poetry config virtualenvs.in-project true`?

It would create a virtualenv in your project not /.../caches/pypoetry/virtualenvs/...

**Comment by shiveringbulbul** [comment]
I got the reason.
It makes sense!
