### ISSUE TITLE
UX: `poetry install` lists own project as 'installed' 

### ISSUE THREAD

**Issue by mgrandi** [python-poetry/poetry#2440]
- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: windows 10
- **Poetry version**: 1.0.5
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://github.com/mgrandi/telegram_dl/blob/master/pyproject.toml

## Issue

When doing `poetry install`, it lists all the requirements being installed, EXCEPT it _also_ lists the project itself as being installed too:

```plaintext
PS C:\Users\auror\Code\personal\telegram_dl> poetry install
Creating virtualenv telegram-dl-a1fmb41G-py3.8 in C:\Users\mark\AppData\Local\pypoetry\Cache\virtualenvs
Updating dependencies
Resolving dependencies...

Writing lock file


Package operations: 18 installs, 0 updates, 0 removals

  - Installing markupsafe (1.1.1)
  - Installing six (1.14.0)
  - Installing attrs (19.3.0)
  - Installing mako (1.1.2)
  - Installing orderedmultidict (1.0.1)
  - Installing pyparsing (2.4.7)
  - Installing python-dateutil (2.8.1)
  - Installing python-editor (1.0.4)
  - Installing sqlalchemy (1.3.17)
  - Installing alembic (1.4.2)
  - Installing arrow (0.15.6)
  - Installing cattrs (1.0.0)
  - Installing furl (2.1.0)
  - Installing logging-tree (1.8.1)
  - Installing phonenumberslite (8.12.3)
  - Installing pyhocon (0.3.54)
  - Installing sqlalchemy-repr (0.0.2)
  - Installing sqlalchemy-utils (0.36.5)
  - Installing telegram_dl (0.0.1)
```

now this just seems like a UX bug, as when I saw this, I thought that i had messed up somewhere and that I had listed my own project as a dependency, because when developing a library/application, you don't want to install it because then python will 2 versions of the project, the one in the folder you are developing in and then one with all the other libraries in the virtualenv, and it could lead to it using the virtualenv version being picked, which would cause confusion when changes made aren't reflected

However I checked the virtualenv directory and my project was not installed, which is good, but I thought the behavior of listing the package like that was confusing , so I looked at the code:

https://github.com/python-poetry/poetry/blob/master/poetry/console/commands/install.py#L85-L88

seems like there it is just printing out output that matches the output of the `Installer` class. so maybe that should be changed to be like `Requirements for package <package_pretty_name> <package_version> ` installed?

**Comment by finswimmer** [comment]
Hello @mgrandi ,

`poetry` _is_ installing the current project in the virtual environment. It's installed in development mode. This is what you want, otherwise you cannot import any module with `import myproject` in your code.

fin swimmer

**Comment by mgrandi** [comment]
well, i did look again and there IS a `egg-link` file which points back to the original directory, i guess this means that you can run your code if you are not in the current directory where the code is located? which is a bit strange since i think you need to be in the directory where the pyproject.toml file is in to do stuff like `poetry run` or `poetry shell`

regardless, i still think the phrasing of that log message can be improved, perhaps "installed <project> <ver> (in development mode)" might suffice? My main problem is that i thought it was "installing" it normally, as in NOT using a egg-link file that pointed back to the directory everything is in

**Comment by mgrandi** [comment]
This seems to be fixed as a result of https://github.com/python-poetry/poetry/pull/2595:

https://github.com/python-poetry/poetry/commit/c7055be9b4d34f61721da45ebb4994597fa3b05b#diff-4d02770efb95861ef5a4a2e3054e43fcf688ad882fdd166a79a6765f5fe16570R90

where now it lists it is installing the current project, which I think makes the UX better and therefore resolves this bug
