### ISSUE TITLE
Solver Error when extras depend on same package

### ISSUE THREAD

**Issue by vsriram11** [python-poetry/poetry#2442]
```
[tool.poetry.dependencies]
a1 = {name="a", version="^0.3.0", extras = ["databricks-connect"], source="private-pypi", allow-prereleases = true}
a2= {name="a", version="^0.3.0", extras = ["pyspark"], source="private-pypi", allow-prereleases = true}
a3 = {name="a", version="^0.3.0", source="private-pypi", allow-prereleases = true}

[tool.poetry.extras]
a1 = ["a1"]
a2 = ["a2"]
a3 = ["a3"]
```

This will result in a SolverError. 

Had to migrate to using setuptools backend to support this, as we wanted to support multiple installation path extras for a single package. Would be great to use Poetry instead of setuptools, as I really love the simplicity/elegance of this project, but need support for this use case.

**Comment by dimbleby** [comment]
private repository, made-up example... hard to see how anyone could expect to reproduce and verify / investigate this

**Comment by finswimmer** [comment]
Hello @vsriram11,

you haven't come back to this issue for a long while. So I assume this is solved in the meantime and I can close this ticket.

Feel free to leave a comment if you disagree.

fin swimmer
