### ISSUE TITLE
dependency resolution bug: kedro range not satisfied despite it actually being satisfied

### ISSUE THREAD

**Issue by amasad** [python-poetry/poetry#2444]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Reproducible on macOS 10.13.6 and on Ubuntu 18.04.4 LTS
- **Poetry version**: reproducible on 0.12.16 and 0.12.17
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: this has the full repro: https://repl.it/@amasad/kedro

## Issue

Kedro package 0.16 [specifies](https://github.com/quantumblacklabs/kedro/blob/f78ed4742c6de4bdff7bd6a0185074c15a3b40eb/setup.py#L154) python version to be in the range `>=3.6, <3.9` but when you try to install on a project with Python 3.8 it errors out:

```
Resolving dependencies...
   1: fact: poetrybug is 0.1.0
   1: derived: poetrybug
   1: fact: poetrybug depends on kedro (^0.16.0)
   1: selecting poetrybug (0.1.0)
   1: derived: kedro (^0.16.0)
PyPI: 1 packages found for kedro >=0.16.0,<0.17.0
PyPI: Getting info for kedro (0.16.0) from PyPI
   1: fact: kedro (0.16.0) requires Python >=3.6, <3.9
   1: derived: not kedro (0.16.0)
   1: fact: no versions of kedro match >0.16.0,<0.17.0
   1: conflict: no versions of kedro match >0.16.0,<0.17.0
   1: ! kedro (>0.16.0,<0.17.0) is partially satisfied by not kedro (0.16.0)
   1: ! which is caused by "kedro (0.16.0) requires Python >=3.6, <3.9"
   1: ! thus: kedro is forbidden
   1: ! kedro (>=0.16.0,<0.17.0) is satisfied by kedro (^0.16.0)
   1: ! which is caused by "poetrybug depends on kedro (^0.16.0)"
   1: ! thus: version solving failed
   1: Version solving took 0.240 seconds.
   1: Tried 1 solutions.
```

I made a full repro here https://repl.it/@amasad/poetrybug

**Comment by finswimmer** [comment]
Hello @amasad ,

you are using a very outdated version of poetry. Please update to newest one by running `poetry self:update`.

With the current release you will see this error message:

```
Using version ^0.16.1 for kedro

Updating dependencies
Resolving dependencies... (0.6s)

[SolverProblemError]
The current project's Python requirement (^3.8) is not compatible with some of the required packages Python requirement:
  - kedro requires Python >=3.6, <3.9

Because no versions of kedro match >0.16.1,<0.17.0
 and kedro (0.16.1) requires Python >=3.6, <3.9, kedro is forbidden.
So, because poetrybug depends on kedro (^0.16.1), version solving failed.
```

`poetry`'s version solving is fundamental different to other programs in that way,  that it tries to find a major version of a package, that is compatible to **_all_** python versions, to which the current project is compatible, and not just the one you are currently using.

So, in your `pyproject.toml`you define a python version `^3.8` which means `>=3.8,<4.0`. As the error message stated out `kedro` is only compatible to `>=3.6, <3.9`. You have to adopt this in your `pyproject.toml` to be able to install this package.

fin swimmer
