### ISSUE TITLE
develop option for path dependency specification is undocumented

### ISSUE THREAD

**Issue by rainyday** [python-poetry/poetry#2447]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

Browsing current issues I discovered there is a `develop` parameter that can be used to, apparently, install path dependencies to the environment's site-packages instead of simply creating a .egg-link file, but it doesn't appear to be documented. Is this a supported feature? If so, it seems like it should be mentioned in dependency-specifications.

**Comment by finswimmer** [comment]
Hello,

in the meantime the default behavior has changed and it is documented here: https://python-poetry.org/docs/dependency-specification/#path-dependencies

fin swimmer
