### ISSUE TITLE
Wrong sub-dependency version selected

### ISSUE THREAD

**Issue by dimaqq** [python-poetry/poetry#2451]
- **OS version and name**: macOS, py3.8, py3.9
- **Poetry version**: 1.0.5

#### Reproduce

* `poetry init`
* `poetry add beautifulsoup4`

Installs sub-dep `soupsieve==1.9.8` even though `soupsieve==2.0.1` is available:

```sh
> poetry run pip freeze
beautifulsoup4==4.9.1
soupsieve==1.9.6
```

`beautifulsoup4` has these lines in `setup.py`:

```py
install_requires=["soupsieve>1.2"]
if sys.version_info.major == 2:
    install_requires.append("soupsieve<2.0")
```

ref: https://bazaar.launchpad.net/~leonardr/beautifulsoup/bs4/view/head:/setup.py#L11

poetry somehow picks up this restriction:

```sh
> poetry show --tree
beautifulsoup4 4.9.1 Screen-scraping library
├── soupsieve >1.2
└── soupsieve <2.0
```

and also shows the sub-dep as outdated:

```sh
> poetry show --outdated
soupsieve 1.9.6 2.0.1 A modern CSS selector implementation for Beautiful Soup.
```

This is all I know for now... I'll look into the wheels, etc.

**Comment by dimaqq** [comment]
Cache data:

```
~/Library/Caches/pypoetry/cache/repositories/pypi/bc/9e/6e/8e/0d/95/2f/e2/bc9e6e8e0d952fe2e74b356b2fb5c33bb31101cdc5be468e28f67449206d0554
1:9999999999{"name": "beautifulsoup4", "version": "4.9.1", "summary": "Screen-scraping library", "platform": "", "requires_dist": ["soupsieve (>1.2)", "soupsieve (<2.0)", ...
```

**Comment by dimaqq** [comment]
Meanwhile `beautifulsoup4` wheels are build properly:

```sh
unzip beautifulsoup4-4.9.1-py3-none-any.whl
...
ag soupsieve
beautifulsoup4-4.9.1.dist-info/METADATA
22:Requires-Dist: soupsieve (>1.2)

```

Contrast with Python2 version:

```sh
unzip beautifulsoup4-4.9.1-py2-none-any.whl
...
ag soupsieve
beautifulsoup4-4.9.1.dist-info/METADATA
24:Requires-Dist: soupsieve (>1.2)
25:Requires-Dist: soupsieve (<2.0)
```

**Comment by dimaqq** [comment]
The tarball is a bit suspect, egg info has both restrictions, but setup.py has a conditional restriction.

```sh
tar xzf beautifulsoup4-4.9.1.tar.gz
...
ag soupsieve
...
beautifulsoup4-4.9.1/beautifulsoup4.egg-info/requires.txt
1:soupsieve>1.2
2:soupsieve<2.0
...
beautifulsoup4-4.9.1/setup.py
10:install_requires=["soupsieve>1.2"]
12:    install_requires.append("soupsieve<2.0")
...
```

If poetry evaluates tarball egg info, how should `beautifulsoup4` author write their library so that poetry picks up correct sub-dependency versions for Python3 and Python2?

**Comment by rushton** [comment]
Believe I have the same issue, `python-avro-json-serializer` has rules around python 2 vs 3:
```python
if version_info[:2] <= (3, 0):
    install_requires.append('avro==1.8.2')
else:
    install_requires.append('avro-python3==1.8.2')
```
ref: https://github.com/linkedin/python-avro-json-serializer/blob/master/setup.py#L22-L25

but when installing with poetry, we get the python2 version of the avro sub-dependency:

```shell
poetry export --without-hashes --format requirements.txt   | grep avro
avro==1.8.2; python_version == "3.7"
avro-json-serializer==1.0.1; python_version == "3.7"
```

**Comment by dimbleby** [comment]
Poetry is not a python interpreter and so when people execute conditional logic in their `setup.py` things are liable to go wrong. 

Please encourage projects to use markers to declare their dependencies.  It looks as though you already [submitted a fix](https://github.com/linkedin/python-avro-json-serializer/pull/11) to avro-json-serializer, and beautifulsoup has dropped python2 support, so I guess this issue is no longer relevant.

**Comment by dimaqq** [comment]
`beautifulsoup4` project has since removed the Python major conditional entirely.
I guess the original issue is now "gone".
