### ISSUE TITLE
Implement PEP-610

### ISSUE THREAD

**Issue by sdispater** [python-poetry/poetry#2452]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

`pip` recently added support for [PEP-610](https://www.python.org/dev/peps/pep-0610/) which gives the possibility to track the origin of an installed distribution via a `direct_url.json` file in the `.dist-info` directory.

This feature request is two-fold:

* Properly read and handle the `direct_url.json` file. This will avoid some heuristics we do in the `InstalledRepository` class.
* Generate the `direct_url.json` file when installing packages with Poetry. This is especially necessary since we will eventually move away from `pip` for the package installation.

Ideally, this should be implemented as soon as possible. However, since there are still quite a few features left to do for the `1.1` release, this might have to wait for the `1.2` release.

**Comment by mvoitko** [comment]
Can I help with this?

**Comment by abn** [comment]
@mvoitko sure thing, feel free to submit a draft PR. If you want guidance around the code base, ping me on our discord server. I will post some more details on here later.
