### ISSUE TITLE
Installing pandas and Python versioning

### ISSUE THREAD

**Issue by mosesontheweb** [python-poetry/poetry#2454]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 18.04 LTS
- **Poetry version**: 1.0.5
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue

I tried to install pandas todady using Poetry and it failed several times.
The result was:
```
[SolverProblemError]
The current project's Python requirement (^3.6) is not compatible with some of the required packages Python requirement:
  - pandas requires Python >=3.6.1

Because pandas (1.0.3) requires Python >=3.6.1
 and no versions of pandas match >1.0.3,<2.0.0, pandas is forbidden.
So, because edis depends on pandas (^1.0.3), version solving failed.
```
I had `python = "^3.6"` in my pyproject.toml, originally set by Poetry on initializing the virtual environment. I then tried different values in the order `python = "3.6"`, `python = ">=3.6.1, < 3.7"` until I set it to `python = ">=3.6.1"` and then succeeded with the installation. Python version used in the environment is 3.6.9. Somehow weird.
Regards, Thomas

**Comment by finswimmer** [comment]
Hello @mosesontheweb,

short answer: poetry resolves the dependencies for all python versions declared in the `pyproject.toml` and not just the one currently used.

Long answer: Please see my comment in https://github.com/python-poetry/poetry/issues/2444#issuecomment-632471356

Setting `python = ^3.6.1` should solve your problem.

fin swimmer
