### ISSUE TITLE
More information for failing `poetry run` would be helpful

### ISSUE THREAD

**Issue by viraptor** [python-poetry/poetry#2455]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

Sometimes when I try to run an entrypoint from a package, I get a very non-descriptive message:
```
$ poetry run somescript

[FileNotFoundError]
[Errno 2] No such file or directory
```

It doesn't help me solve the problem unfortunately - I don't know what file exactly was not found, so I can only guess at solutions.

It would be great to have at least the path printed. Some description why that path was tried would be good too.

**Comment by finswimmer** [comment]
Hello @viraptor,

> It would be great to have at least the path printed. Some description why that path was tried would be good too.

maybe I get you wrong, but what do expect to get here? You are trying to run `somescript` which cannot be found. So the path is `somescript` and this path was tried because you invoke this ;) Joke aside, can you please clarify your expectation?

fin swimmer

**Comment by viraptor** [comment]
When I see an error like that, my process is:
- this looks like an internal error: is poetry failing to find its own file somewhere, or is it about my script?
- where would that script be installed, I need to find the venv location
- did I make a typo or is the file actually missing

Here's what my ideal message would look like for this error:
> Script (...) has not been found (searched in virtual environment path (...))
Additionally, if the script is defined as an endpoint in pyproject:
> This script is defined in the pyproject file, but has not been installed yet. Try "poetry install"
Alternatively, if there are close fuzzy matches in venv already:
> Did you mean: (...) ?

**Comment by dnunez24** [comment]
I would also like to see more information from poetry about what it thinks it can't find. This is a very opaque error message that is hard to debug. I've experienced issues like this when trying to set it up to run with tox inside a Docker container and it's pretty impossible to tell what's actually missing.

![image](https://user-images.githubusercontent.com/323802/107548609-b9fa2b80-6b83-11eb-927c-1f6c4c3638d8.png)

At first I thought it was the program I was trying to run from poetry but as you can see in the screenshot above even if I just try to get help from `poetry run` it fails with the same message. Verbosity flags do nothing to improve this.

**Comment by branchvincent** [comment]
Thanks for filing. I agree this UX is jarring, and I'm currently trying to address it. Feel free to follow #1567, which is for the same issue
