### ISSUE TITLE
Install command sometimes prints lots of Python code in version string

### ISSUE THREAD

**Issue by PetterS** [python-poetry/poetry#2462]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version. Using the latest `develop` branch.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu LTS 18.04
- **Poetry version**: `develop`
- **Line in my pyproject file**:  `pytest-cov = "*"`

## Issue
Every time I execute `poetry install`, I get the following output:
>Installing dependencies from lock file

>Package operations: 0 installs, 1 update, 0 removals

>  - Updating pytest-cov (2.8.1 import os, sys;exec('if \'COV_CORE_SOURCE\' in os.environ:\n try:\n  from pytest_cov.embed import init\n  init()\n except Exception as exc:\n  sys.stderr.write(\n   "pytest-cov: Failed to setup subprocess coverage. "\n   "Environ: {0!r} "\n   "Exception: {1!r}\\n".format(\n    dict((k, v) for k, v in os.environ.items() if k.startswith(\'COV_CORE\')),\n    exc\n   )\n  )\n') -> 2.8.1)

For some reason, lots of Python code is included in the version string.

**Comment by PetterS** [comment]
#2462 is a duplicate.

**Comment by PetterS** [comment]
#2597 is a duplicate.

**Comment by snejus** [comment]
Same here:
```bash
Package operations: 0 installs, 8 updates, 0 removals
  ...
  - Updating pytest-cov (2.10.0 import os, sys;exec('if \'COV_CORE_SOURCE\' in os.environ:\n try:\n  from pytest_cov.embed import init\n  init()\n except Exception as exc:\n  sys.stderr.write(\n   "pytest-cov: Failed to setup subprocess coverage. "\n   "Environ: {0!r} "\n   "Exception: {1!r}\\n".format(\n    dict((k, v) for k, v in os.environ.items() if k.startswith(\'COV_CORE\')),\n    exc\n   )\n  )\n') -> 2.10.0)
  ...
