### ISSUE TITLE
Make the documentation searchable

### ISSUE THREAD

**Issue by pawamoy** [python-poetry/poetry#2465]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate. **The keywords "search" and "documentation" in the issues return something like 400+ issues unfortunately.**

## Issue
I find myself coming back  often to the docs, and I terribly miss a "Search" input field. I know the item is here somewhere, I just can't remember in what section, so I have to click on several section and run Ctrl-F.

I believe you are using MkDocs to render your documentation. Wouldn't it be easy to add the native search plugin of MkDocs to the generated site? I think you are using a custom theme so it might not be actually easy though.

**Comment by wshayes** [comment]
I was looking at creating a PR for this, but after cloning poetry, running `poetry install` and running `cd docs; mkdocs serve`  - I had an error that CONTRIBUTING.md couldn't be found and the docs were not themed at all.  I also couldn't find any special instructions on running mkdocs for poetry documentation.

**Comment by pawamoy** [comment]
It seems you have to run it from the root:

```
poetry run mkdocs serve -f docs/mkdocs.yml
```

...though I only got the HTML, no styling :confused:

**Comment by finswimmer** [comment]
Searching within the docs is now possible. 

![image](https://user-images.githubusercontent.com/2164565/128017939-a1b84236-f55e-4b08-913f-4a68242fde97.png)
