### ISSUE TITLE
poetry init -y for initializing with all defaults

### ISSUE THREAD

**Issue by meetmangukiya** [python-poetry/poetry#2466]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

Equivalent of `npm init -y` create `pyproject.toml` considering all the defaults that we currently have on pressing enter for each of the questions.

**Comment by finswimmer** [comment]
Hello @meetmangukiya,

sounds like you are looking for `poetry init -n` (or `poetry init --no-interaction`), are you?

fin swimmer

**Comment by meetmangukiya** [comment]
Yes, that's the one. Sorry I couldn't find it when I searched before opening the issue, it's not in `poetry init --help` or `poetry --help` or at https://python-poetry.org/docs/cli/ . Also used to `-y` for no interaction like in `apt`, `npm`.

**Comment by finswimmer** [comment]
Hello @meetmangukiya ,

this option is listed under the `Global Options` sections, when running `poetry --help` or `poetry init --help`. But yes it's missing on the website, and needs to be added there.

fin swimmer

**Comment by meetmangukiya** [comment]
Probably best to generate the options in CLI page of docs from a template in CI?
