### ISSUE TITLE
Ability to add or change dependency version without installing it

### ISSUE THREAD

**Issue by timorkal** [python-poetry/poetry#2469]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

Hello, I would like that the "poetry add dependency" will be able to update the pyproject.toml file without installing the actual dependency, some sort of --without-installing switch.
I need that for CI process that is updating the pyproject.toml from outside and do locking, then doing the build via docker with cache layers from previous builds.
I know that as a workaround I could play with some bash find-and-replace commands like "sed" but I prefer poetry will give me that option out of the box.

Thank you,

**Comment by finswimmer** [comment]
`poetry add` now provides a `--lock` flag for this. https://python-poetry.org/docs/cli/#options-3
