### ISSUE TITLE
the docs is outdated for Ubuntu 20.04

### ISSUE THREAD

**Issue by jabbalaci** [python-poetry/poetry#2471]
I tried to install poetry on a freshly installed Ubuntu 20.04 and the command `python` is not available there. Only `python3` exists. Thus, on https://python-poetry.org/docs/ , the following line should be updated:

    curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python

Instead of `python` at the end, use `python3`.

Once I installed it, it created the script `~/.poetry/bin/poetry`, whose first line also includes `python`. The script's first line should be:

    #!/usr/bin/env python3

**Comment by SanketDG** [comment]
Please see https://github.com/python-poetry/poetry/issues/721

**Comment by jabbalaci** [comment]
Why is it still an issue? Python 2 was deprecated in January 2020. A new version of poetry should come out with Python 3 support only!

**Comment by neroanalytics** [comment]
I have same issue. Am I missing something? Is this the 21st century? I thought Poetry was a dependency management solution? You think they could get the dependency issues right with their own solution
