### ISSUE TITLE
Unable to clearly install poetry in Docker container

### ISSUE THREAD

**Issue by cdeler** [python-poetry/poetry#2476]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request
I cannot clearly install poetry into Docker container. I'm not sure if it's a bug or feature request. I decided it's a new feature.

So if you want to install poetry into Docker container, you have to do either
```
RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
ENV PATH="${PATH}:/root/.poetry/bin"```
or 
```
pip install poetry==1.0.5
```

The problem in first command is that I haven't found a way ho to install poetry into `/usr/bin` or `/usr/local/bin`, therefore I have to add `/root/.poetry/bin` to the $PATH

The second command installs the binaries into `/root/.local/bin` which obliviously is not in the PATH. 

So is it possible to ask you provide us with a command-line option to poetry installator to install your tool system-wide?

**Comment by finswimmer** [comment]
Hello @cdeler,

you can already do this by providing an env variable POETRY_HOME with the path where to install poetry. See also the example in the [docs] (https://python-poetry.org/docs/#installation).

fin swimmer
