### ISSUE TITLE
OS Specific dependencies 

### ISSUE THREAD

**Issue by nihaals** [python-poetry/poetry#2479]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request
[StackOverflow post for non-poetry specific case](https://stackoverflow.com/questions/58927064/pip-package-with-os-specififc-dependency)
It may be useful to expand this to OS specific wheels with different code in case the project can't easily be made universal. If this approach is used, there may be a separate table in the config file for each OS where you can select a different package directory.
Some packages also have requirements for certain versions of Python, usually backports, which would be helpful here too.

**Comment by nihaals** [comment]
It looks like this is covered in [markers](https://python-poetry.org/docs/dependency-specification/#using-environment-markers). Maybe this should be referenced on the pyproject.toml page where people would expect it?

**Comment by nihaals** [comment]
Is this a won't fix? Maybe a more general solution would be linking to [dependency specification](https://python-poetry.org/docs/dependency-specification/) in [`dependencies`and `dev-dependencies`](https://python-poetry.org/docs/pyproject/#dependencies-and-dev-dependencies) as it includes more relevant information and can be missed when looking at the pyproject.toml reference.

**Comment by Secrus** [comment]
> Is this a won't fix? Maybe a more general solution would be linking to [dependency specification](https://python-poetry.org/docs/dependency-specification/) in [`dependencies`and `dev-dependencies`](https://python-poetry.org/docs/pyproject/#dependencies-and-dev-dependencies) as it includes more relevant information and can be missed when looking at the pyproject.toml reference.

You are welcome to make a PR adding this link.
