### ISSUE TITLE
Unexpected behavior when calling `env use` with activated venv and local venv.

### ISSUE THREAD

**Issue by linw1995** [python-poetry/poetry#2483]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: MacOS 10.15.4
- **Poetry version**: 1.0.5
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: unuseful

## Issue

> it will first check if it's currently running inside a virtual environment. If it is, it will use it directly without creating a new one.

poetry does not work like the [document](https://python-poetry.org/docs/managing-environments/) says.

Before calling `poetry env use`, same as `poetry env use system`, the strategy of choosing what environment to be used is:

1. Activated virtualenv (After calling `source another_venv/bin/activate`)
2. Local virtualenv (.venv in project root)
3. Virutalenv created by poetry

After calling `poetry env use`, it becomes:

1. Local virtualenv (.venv in project root)
2. Virutalenv created by poetry
3. Activated virtualenv (After calling `source another_venv/bin/activate`)

**Comment by finswimmer** [comment]
This seems to be fixed in the meantime.
