### ISSUE TITLE
Does not detect swagger_spec_validator-2.6.0-py2.py3-none-any.whl in PyPI

### ISSUE THREAD

**Issue by l0b0** [python-poetry/poetry#2490]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option). *Not applicable*

- **OS version and name**: Ubuntu 18.04
- **Poetry version**: 1.0.5
- **Relevant line in pyproject.toml**: `swagger-spec-validator = "*"` 

## Issue

When running `poetry update` just now the entry in the lock file is

```
swagger-spec-validator = [
    {file = "swagger-spec-validator-2.6.0.macosx-10.15-x86_64.tar.gz", hash = "sha256:8cefd19349681531b07a187eee85c2ffe39353a0f1f21989ec29da6af618424b"},
]
```

despite there being [another file in the same release](https://pypi.org/project/swagger-spec-validator/2.6.0/#files). This release fails to install on Linux. Is the problem the non-standard filename, containing underscores rather than the actual package name?

**Workaround:** Manually add the relevant line to the lock file:

```
{file = "swagger_spec_validator-2.6.0-py2.py3-none-any.whl", hash = "sha256:ba4e636d89bf547a6f41a6945bb503cf06dde13664ad978a7407aaed772ae75f"},
```

**Comment by finswimmer** [comment]
Hello @l0b0,

poetry prefers wheel packages if they are available. `swagger-spec-validator` provides one without any restriction to a platform. If this one doesn't work, please report it to the authors of the packages. This is not on poetry's site.

fin swimmer
