### ISSUE TITLE
Poetry 1.0.6 raises TypeError

### ISSUE THREAD

**Issue by PetterS** [python-poetry/poetry#2498]
I am using the new Poetry that was released 6 minutes ago (1.0.6).

It gives me the following output on my repo:
```
Installing dependencies from lock file
[TypeError] 
_execute_setup() missing 1 required positional argument: 'self'
```

Poetry 1.0.5 works.

**Comment by PetterS** [comment]
@sdispater

**Comment by sdispater** [comment]
I know where the issue is coming from. I'll fix it and make a new release.

**Comment by PetterS** [comment]
Cheers! This broke our CI.

**Comment by PetterS** [comment]
Thanks!

**Comment by sdispater** [comment]
Version`1.0.7` has just been releases!

**Comment by atugushev** [comment]
@sdispater 

FYI, install from path still doesn't work, see:

```console
root@0f4156cb9a15:/home/apron# cat pyproject.toml
...
[tool.poetry.dependencies]
foo = {path = "deps/foo"}
...

root@0f4156cb9a15:/home/apron# poetry --version
Poetry version 1.0.7
root@0f4156cb9a15:/home/apron# poetry install --no-dev --no-root
Installing dependencies from lock file


Package operations: 1 installs, 0 updates, 0 removals

  - Installing foo (0.4.0-dev deps/foo)


root@0f4156cb9a15:/home/apron# poetry run python
Python 3.6.9 (default, Jun  5 2020, 14:13:12)
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import foo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'foo'
>>>
```

**Comment by PetterS** [comment]
Perhaps we could change our CI tests so that they use the `master` version of Poetry to install and run tests? We could also execute a few other commans (add, remove etc). These tests would increase confidence of a release.

**Comment by sdispater** [comment]
@atugushev What does the pyproject.toml of the dependency look like?

**Comment by sdispater** [comment]
Nevermind, I found the root cause of the issue and a fix is coming.

**Comment by atugushev** [comment]
@sdispater 

> Nevermind, I found the root cause of the issue and a fix is coming.

FWIW https://github.com/atugushev-dev/poetry-bug-install-from-path

**Comment by sdispater** [comment]
Release `1.0.8` is out!

**Comment by atugushev** [comment]
@sdispater 

Thanks! It works now.
