### ISSUE TITLE
Poetry 1.0.6 fails to install another poetry project from a sub-folder

### ISSUE THREAD

**Issue by graffic** [python-poetry/poetry#2501]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Archlinux
- **Poetry version**: 1.0.6
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/graffic/53aad7feb76f11c524a1172458d4d1ed

## Issue
The `pyproject.toml` file has a dependency on another poetry project. But it seems after poetry install, it fails to install. This was working with `1.0.5`. If I go to the `schemas` folder and execute a poetry install inside the virtual-env, I can install the main package afterwards.

Output I get

```

Package operations: 1 install, 0 updates, 0 removals

  - Installing ovat-schemas-metrics (0.6.0 schemas)
  - Installing metrics (0.20.0)

[EnvCommandError]
Command ['/redacted/metrics/.venv/bin/pip', 'install', '-e', '/redacted/metrics'] errored with the following return code 1, and output: 
Obtaining file:///redacted/metrics
Requirement already satisfied: Faker<5.0.0,>=4.0.2 in ./.venv/lib/python3.8/site-packages (from metrics==0.20.0) (4.1.0)
Requirement already satisfied: alembic<2.0.0,>=1.4.2 in ./.venv/lib/python3.8/site-packages (from metrics==0.20.0) (1.4.2)
Requirement already satisfied: click<8.0,>=7.0 in ./.venv/lib/python3.8/site-packages (from metrics==0.20.0) (7.1.2)
Requirement already satisfied: databases<1,>=0 in ./.venv/lib/python3.8/site-packages (from metrics==0.20.0) (0.3.2)
Requirement already satisfied: fastapi<0.55.0,>=0.54.1 in ./.venv/lib/python3.8/site-packages (from metrics==0.20.0) (0.54.2)
Requirement already satisfied: httpx<0.14.0,>=0.13.2 in ./.venv/lib/python3.8/site-packages (from metrics==0.20.0) (0.13.3)
ERROR: Could not find a version that satisfies the requirement ovat-schemas-metrics==0.6.0 (from metrics==0.20.0) (from versions: none)
ERROR: No matching distribution found for ovat-schemas-metrics==0.6.0 (from metrics==0.20.0)
```

**Comment by sdispater** [comment]
What's the structure of both you projects?

**Comment by graffic** [comment]
I publish a small example here: https://github.com/graffic/poetry-106-issue

`poetry install` will finish in 1.0.5

**Comment by sdispater** [comment]
I found the root cause. I will fix it and make a new release.

**Comment by graffic** [comment]
Thanks!
