### ISSUE TITLE
poetry add installs dev dependencies (or, has no --no-dev)

### ISSUE THREAD

**Issue by matthijskooijman** [python-poetry/poetry#2503]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

- **OS version and name**: Ubuntu 19.10
- **Poetry version**: 1.0.7

## Issue
In a production install of my application (i.e. created with `poetry install --no-dev`), I tried adding a package (in particular `poetry add mysqlclient`), and then poetry started installing all dev packages.

I guess this is somewhat expected, since poetry probably doesn't remember that this was a `--no-dev` installation. So maybe:
 - Poetry should remember that an installation is `--no-dev`. This is probably fragile.
 - `poetry add` should get a `--no-dev` option (with the same meaning as for `poetry install`). This is probably confusing, since then `--no-dev` and `--dev` (add package as dev-only) end up as option with completely different (i.e. not inversed) meanings.

As a workaround, I believe you can:
 1. Add the dependency to `pyproject.toml` manually.
 2. Run `poetry lock` to update the lock file
 3. Run `poetry install --no-dev` to install the new package, but not all dev packages.

This has the side effect of updating *all* packages (which is what `poetry lock` does), so it is not a complete alternative to running `poetry add`.

A workaround that works slightly better, is to just run e.g. `poetry add mysqlclient`, wait for the lock file to be written and then just as it starts installing, kill it with ctrl-c. Then run `poetry install --no-dev` to just install the added package(s) (and remove any dev packages that were already installed if you killed it too late).

This seems to work fine, but is of course not really a solution.

**Comment by ArtistsTechGuy** [comment]
Could we just add a section to the poetry.lock file if it is a --no-dev  install and check that before the add install?

**Comment by abn** [comment]
This can be performed as follows:

```sh
poetry add --lock mysqlclient
poetry install --no-dev
```

**Comment by matthijskooijman** [comment]
@abn, cool, that sounds like a reasonable approach indeed (seems that `add --lock` was not available yet when I submitted the original issue, so with that added recently, this is indeed possible). I wonder if this warrants a bit of documentation somewhere to help people figure this out, but I'm not so sure where that would live exactly, though.
