### ISSUE TITLE
Poetry Install/Update Failing on 1.0.7 with git repositories (works on 1.0.5)

### ISSUE THREAD

**Issue by badrobit** [python-poetry/poetry#2504]
- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate. (there are similar but not specific)
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option). (No exception occurs)

- **OS version and name**: Ubuntu 18.04, 20.04, Debian (from Python 3.8.2 Docker Image)
- **Poetry version**: 1.0.7
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: Not allowed to sorry, (Work Defined Rule).

## Issue
When using dependencies defined as git based repositories poetry reports that it installs the repository but when we source the poetry created virtual environment and try to run unit tests or an interactive terminal we are unable to find the package poetry reported as installed.

**Comment by sdispater** [comment]
https://github.com/python-poetry/poetry/pull/2505 should fix the issue.

A bugfix release will be out in a few minutes.

**Comment by sdispater** [comment]
Release `1.0.8` is out!

**Comment by obviousrebel** [comment]
> Release `1.0.8` is out!
@sdispater 
Confirmed working on pipelines, thanks!
