### ISSUE TITLE
Unable to download from Python repository hosted in Artifactory

### ISSUE THREAD

**Issue by snambi** [python-poetry/poetry#2507]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Mac OS X 10.14.6 , Mojave 
- **Poetry version**: 1.0.5 
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: [pyproject.toml](https://gist.github.com/snambi/f4fecc78e96a1cb7e3aa3f3c47c806b0)

## Issue

The legacy repositories have versions found in child pages

**PYPI Repository:**

Please take a look at the Flask package in PyPI repository
[https://pypi.org/simple/flask/](https://pypi.org/simple/flask/) 

Package page contains href elements that point to .whl, tar.gz etc.
` <a href="https://files.pythonhosted.org/packages/d8/94/7350820/Flask-1.0.4-py2.py3-none-any.whl#sha256=1a21ccc" data-requires-python="&gt;=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*">Flask-1.0.4-py2.py3-none-any.whl</a>`

 **Artifactory (Legacy) Repository**

However the artifactory doesn't follow the same convention as the PYPI repository.
[https://artifactory.repo.com/artifactory/my-repo/py-pkg](https://artifactory.repo.com/artifactory/my-repo/py-pkg/ )

The package page simply have links to the child pages.
**The actual binaries are only found in the child pages.** 

Versions are provided by following pages

[https://artifactory.repo.com/artifactory/my-repo/py-pkg/0.1.0](https://artifactory.repo.com/artifactory/my-repo/py-pkg/0.1.0)
[https://artifactory.repo.com/artifactory/my-repo/py-pkg/0.2.0](https://artifactory.repo.com/artifactory/my-repo/py-pkg/0.2.0)
            
**_For legacy repositories, child pages must be read_**

**Comment by sdispater** [comment]
I just took a look at the documentation of artifactory and the repository url should be in the following form: `<Artifactory URL>/api/pypi/<repository key>/simple`

See https://www.jfrog.com/confluence/display/JFROG/PyPI+Repositories#PyPIRepositories-SpecifyingtheRepositoryontheCommandLine

Did you try that already?

**Comment by snambi** [comment]
@sdispater I have tried the following 4 methods, all of them are not working. This repository was setup quite new, like less than 2 months.

404 https://artifactory.corp.company.com/api/pypi/<repository>/
404 https://artifactory.corp.company.com/api/pypi/<repository>/simple

404 https://artifactory.corp.company.com/artifactory/<repository>/
404 https://artifactory.corp.company.com/artifactory/<repository>/simple

Artifactory repository is structured as follows,
https://artifactory.corp.company.com/artifactory/<repository>/<package>
https://artifactory.corp.company.com/artifactory/<repository>/<package>/0.1.0/
https://artifactory.corp.company.com/artifactory/<repository>/<package>/0.2.0/

As the docs claim, the repo does work with `pip`
I have tried it with `pip` and it was not working for `poetry`. I thought it was some misconfiguration. To find the problem , I started look into the code. Then I realized "artifactory" is structured like a maven repository.

**Comment by sdispater** [comment]
@snambi Unfortunately, Poetry only recognize properly structured repositories that expose a Simple API as specified in PEP-503: https://www.python.org/dev/peps/pep-0503/

From the examples you provided, shouldn't the url be https://artifactory.corp.company.com/artifactory/api/pypi/repository/simple which follows the structure I mentioned above?

**Comment by snambi** [comment]
@sdispater thanks for the quick response. Unfortunately, the artifactory pypi repository doesn't confirm to PEP-503. 

The URL for uploading is [https://artifactory.corp.company.com/artifactory/api/pypi/repository](https://artifactory.corp.company.com/artifactory/api/pypi/repository) and it works fine.

but, if I add "simple" to [https://artifactory.corp.company.com/artifactory/api/pypi/repository](https://artifactory.corp.company.com/artifactory/api/pypi/repository/simple), the request  results in 404.

Following URLs work fine.
https://artifactory.corp.company.com/artifactory/repository/package/
https://artifactory.corp.company.com/artifactory/repository/package/0.1.0/
https://artifactory.corp.company.com/artifactory/repository/package/0.2.0/

**Comment by danieleades** [comment]
I can confirm that Poetry works with our artifactory pypi repository.

The only catch is that we can't get it to work with the artifactory API token. We've only been able to get it to work with username/password, while twine works perfectly with the API token

**Comment by austinbutler** [comment]
See also: https://github.com/python-poetry/poetry/issues/233.

**Comment by snambi** [comment]
Thanks @sdispater @danieleades for providing help.

I talked with the artifactory admin. Now, poetry install works with pypi repository hosted in Artifactory. I'm going to try downloading from various machines to make sure it works well, before closing the issue.

The source of confusion seems to be artifactory itself, which misleads the user in every possible way.

- There pypi local repository page shows the incorrect URL that is not "Simple" compatible.
- The "Simple" url doesn't load properly in the browser. ( atleast the internal repo that I work with)
- `curl` on the "simple" produces status code 302. 

```
> GET /artifactory/api/pypi/pypi-pynlp/simple HTTP/1.1
> Host: artifactory.corp.ebay.com
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 302 Found
< Server: Artifactory/6.14.1
< X-Artifactory-Id: aabf7b48f509972462419d87c82685fca0e66adc
< X-Artifactory-Node-Id: node-58f2f1a483ba
< Location: http://artifactory.corp.company.com/artifactory/api/pypi/pypi-pynlp/simple/
< Content-Length: 0
< Date: Tue, 09 Jun 2020 01:06:49 GMT
```

**Comment by snambi** [comment]
The browser hangs if there is no trailing "/" at the end of the URL. We filed request to fix Artifcatory, I am closing this issue. 

Thanks @sdispater

**Comment by mikeymop** [comment]
> I can confirm that Poetry works with our artifactory pypi repository.
> 
> The only catch is that we can't get it to work with the artifactory API token. We've only been able to get it to work with username/password, while twine works perfectly with the API token

Hello @danieleades sorry to necro post, but I have been hitting many dead ends with poetry + artifactory.
Just recently I managed to get to work by hardcoding my http basic auth url into my `pyproject.toml`

eg:
```toml
[[tool.poetry.source]]
name = "artifactory"
url = "https://mikeymop:AbCd3Fgh1jK1Mn0@artifactory.example.com/artifactory/api/pypi/<python_repo_name>/simple/"
default = true
secondary = false
```

I noticed that using `poetry config http-basic.artifactory` like with the docs results in 404 errors when requesting a package. Are you hardcoding your basic auth into the source url? Curious because this would complicate ci.

**Comment by danieleades** [comment]
@mikeymop we're not hardcoding the values, we're using environment variables to set the auth
