### ISSUE TITLE
Add `--no-install` option to only update files without installing

### ISSUE THREAD

**Issue by jtrakk** [python-poetry/poetry#2514]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

I want to add/remove a dependency and generate the lock file without installing. For example,

```
poetry remove --no-install requests
poetry add --no-install httpx
```

would update the pyproject.toml and poetry.lock but not install anything. Maybe someone can think of a better name than `--no-install` that would make sense for the `remove` case too.

**Comment by Cielquan** [comment]
For clarification:

With `poetry remove --no-install requests` you want poetry to remove requests from `pyproject.toml` and update the lock-file but not uninstall it?

Because if you remove a dependency that's not installed poetry will remove it, cannot uninstall it but still succeeds.

**Comment by jtrakk** [comment]
The goal is to prevent Poetry from installing or uninstalling anything, because that is slow and I don't need it. I only want it to manage the `pyproject.toml` and `poetry.lock` files, not create a virtualenv or install anything.

**Comment by Cielquan** [comment]
For the first part you can disable poetry from creating venvs: https://python-poetry.org/docs/configuration/#virtualenvscreate-boolean

I think it would probably be a good idea to set the install thing also via config so you can disable it global or local. But in addition a flag for onetime deactivation would also be nice.

**Comment by eeshugerman** [comment]
+1 for a for a `dont_manage_environment` config file setting -- I think this would be exactly what I need. I realize env management is a big part of what Poetry does, but it would still be nice to be able to make use of the rest of it in projects where env management doesn't make sense.

My usecase is a project where development is in 100% in Docker, so it doesn't make sense to have a venv on the host.

Also, if I understand correctly, poetry's dependency resolver gives it a unique advantage here over, say, pip-tools, because `pip-compile` needs to run from within the container.

**Comment by jtrakk** [comment]
@eeshugerman 
> Just to clarify -- in this case the dependencies would still be installed, just not to a virtualenv (unless one is already activated) -- correct?

[Looks like it, yes.](https://github.com/python-poetry/poetry/blob/master/poetry/utils/env.py#L334-L337)

**Comment by Cielquan** [comment]
Yes it will still install. This was for the bold marked part:

> The goal is to prevent Poetry from installing or uninstalling anything, because that is slow and I don't need it. I only want it to manage the `pyproject.toml` and `poetry.lock` files, **not create a virtualenv** or install anything.

---

From the docker side I did not view this till now and it makes absolute sense to me.

I think it would be nice to have a config variable to set via `poetry config` and also have a flag for the cli like suggested in the OP.

**Comment by abcdw** [comment]
Great idea. I'm looking for such option too.

**Comment by abn** [comment]
`poetry add --lock` option already exists to handle this in `1.1.0b2`. This can also be added into `poetry remove` command.

```console
$ poetry@1.1.0b2 add --help | grep lockfile
  --lock                 Do not perform operations (only update the lockfile).
```

**Comment by abcdw** [comment]
Super cool! Thank you!

**Comment by fgervais** [comment]
Unfortunately `--lock` will still try to create the virtual environment.

**Comment by finswimmer** [comment]
`poetry add --lock` exists. For `poetry remove --lock` there is another issue: #3971 Closing this one here in favor of the other.

**Comment by NightMachinery** [comment]
This `--lock` thing still downloads the dependencies, which I don't want, as I am managing the virtual env using conda myself.

**Comment by roelzkie15** [comment]
There's a different approach, only you'll need to add the dependency in the `pyproject.toml` file with a version manually for example:

```patch
[tool.poetry.dependencies]
python = "3.11.2"
+ psycopg = "2.9.3"
```

Then do the `poetry lock --no-update`. It will update the lock file without installing anything.

**Comment by GillesJ** [comment]
+1 for this, I regularly need to specify image builds on a local environment which is completely different from the build environment. E.g. work laptop has no GPU and is behind a corporate proxy and firewall, disallowing all alternative pypi indexes. The remote cloud build environment does not have these restrictions. Would be nice if I could specify my pyproject.toml locally, and push my build remote without the need to download or install packages.
