### ISSUE TITLE
poetry.lock missing conditional dependencies

### ISSUE THREAD

**Issue by adisbladis** [python-poetry/poetry#2520]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: 
- **Poetry version**: 
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue
Poetry 1.0.8 has two versions of `cryptography` in it's `poetry.lock`, this is all well and good.

The problem is that only the latest one has a full dependency specification.
My observation is that any dependency that has conditionals only ends up on one version of a package.

In particular `cryptography` is missing `enum34` & `ipaddress`: https://github.com/python-poetry/poetry/blob/6f9d6b0e1b7b1d3a7d7b2ca3478ad2cb0a7188e2/poetry.lock#L294-L300.

**Comment by adisbladis** [comment]
Could you check this out @sdispater or @finswimmer ?

It looks like a fairly critical bug to me.

**Comment by mkniewallner** [comment]
Nowadays, Poetry only has one version of `cryptography` in its lock file, so this is no longer relevant I believe. Closing.
