### ISSUE TITLE
Unable to install subdirectory dependencies (1.0.8)

### ISSUE THREAD

**Issue by bmckalla** [python-poetry/poetry#2521]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: MacOS Catalina 10.15.5
- **Poetry version**: 1.08
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/bmckalla/5d618cd741525c402c2329c1082b6c7a

## Issue
I have a directory structure that looks like this:

```
blah/
    pyproject.toml
    common/
        pyroject.toml
        cli/
            pyproject.toml
            common/
                cli/
                    __init__.py
        misc/
            (structure matches cli)
```

As you see from my gist above, the top level project depends on `common`, and `common` depends on `cli` which is a namespace package that provides cli tools in the `common` namespace.

Common's `pyproject.toml` looks like:

```
[tool.poetry]
name = "common"
version = "0.1.0"
description = "Blah common utilities"
authors = [
    "me <me@gmail.com>"
]
packages = []

[tool.poetry.dependencies]
python = "^3.8"
blah-cli = {path = "common/cli"}
blah-misc = {path = "common/misc"}

[tool.poetry.dev-dependencies]

[tool.poetry.extras]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```

And cli's `pyproject.toml` looks like:

```
[tool.poetry]
name = "blah-cli"
version = "0.1.0"
description = ""
authors = [
    "me <me@gmail.com>"
]
packages = [
    { include = "common" }
]

[tool.poetry.dependencies]
python = "^3.8"
logzero = "^1.5.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```

When I go to install in the top level package, I get the following error:

```
  - Installing blah-cli (0.1.0 common/common/cli)

[EnvCommandError]
Command ['/path/Library/Caches/pypoetry/virtualenvs/blah-fXXQF3S5-py3.8/bin/pip', 'install', '--no-deps', '-U', '-e', '/path/to/blah/common/common/cli'] errored with the following return code 1, and output: 
ERROR: /path/to/blah/common/common/cli is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with svn+, git+, hg+, or bzr+).
```

It seems to be adding an extra `common`.

Additionally, when I tried to add another `common` directory (`blah/common/common`) and move `cli` and `misc` under it to match the expected path, it has the same issue (`blah/common/common/common`)

**Comment by schukerzheng** [comment]
I can install successfully, but it's raise a ModuleNotFoundError exception which I installed
Poetry version 1.1.2

**Comment by shovradas** [comment]
Any update to this yet? or any workaround, please!

**Comment by neersighted** [comment]
Closed as stale and lacking a reproduction
