### ISSUE TITLE
InvalidVersion: Inconsistency in version handling

### ISSUE THREAD

**Issue by djjudas21** [python-poetry/poetry#2524]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Running in Github Actions on `ubuntu-latest`
- **Poetry version**: 1.0.8
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/djjudas21/c239c36a51385f40f7b97baa751027a5

## Issue
I'm using Poetry in a Github Actions pipeline to set the version based on the git tag, and then to build and publish my project. My pipeline is configured [like this](https://github.com/djjudas21/camerahub/blob/188b_poetry/.github/workflows/publish.yml#L23) but effectively runs:

```sh
poetry version <git tag>
poetry publish -n --build --username __token__ --password ${{ secrets.pypi_password }}
```

The git tag is a semver with an optional trailing name and the `poetry version` command succeeds in setting the version, but then `poetry publish` rejects the version. In this case the version is `0.9.4-poetry5` and it yields the following output:

```
# Run poetry version 0.9.4-poetry5
Bumping version from 0.0.0 to 0.9.4-poetry5

# Run poetry publish -n --build --username __token__ --password ***

[InvalidVersion]
Invalid version: '0.9.4-poetry5'
##[error]Process completed with exit code 1.
```

[Full output of the pipeline](https://github.com/djjudas21/camerahub/runs/753470062?check_suite_focus=true) is available.

Why does Poetry accept the version in `poetry version` and later reject it in `poetry publish`? Thanks

**Comment by djjudas21** [comment]
It works properly/consistently if I use a pure semver of `0.9.4`. It only breaks when it's semver+tag like `0.9.4-beta`

**Comment by alexifm** [comment]
I think I have a similar problem.  I want to publish a temporary branch version with this: `X.Y.Z-<branch>+<build>`

`poetry version` has no problem with that but `poetry build` can't handle it.

I feel like this may be part of it:
https://github.com/python-poetry/poetry-core/blob/master/poetry/core/version/version.py#L14-L48

Basically, the regex seems to have a particularly demanding format.  I tested with some of the tags in the regex like `dev` and it worked.

Official SemVer says the prerelease component can be an arbitrary string.
https://semver.org/#spec-item-9

Also, the SemVer provides a regex that could be used:
https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string

**Comment by eikevons** [comment]
IMHO, restricting versions to the PEP 440 regex excludes a lot of use-cases.

**Comment by abn** [comment]
Python packaging's [core metadata specification](https://packaging.python.org/specifications/core-metadata/#version) requires that the version identfieir must be specified in PEP 440. This is enforced when a package is published to an index. You will note that the [warehouse upload api](https://warehouse.pypa.io/api-reference/legacy/#upload-api) requires the package metadata to be set according to the previously mentione core metadata specifications. This is why publish enforces this. 

The `version` command itself does not enforce this because it is not necessary at this point and poetry is used for packages that are never published as well (eg: applications). We could enforce it here, but I think this is not required.

You should consider using a version of one of the following formats making use of the [local version identifiers](https://www.python.org/dev/peps/pep-0440/#local-version-identifiers).
```
0.9.4+poetry.5
X.Y.Z+<branch>.<build>

**Comment by dmyersturnbull** [comment]
For anyone's reference, from the link alexifm shared, [PEP 440 states semver is incompatible](https://www.python.org/dev/peps/pep-0440/#semantic-versioning):

> Semantic versions containing a hyphen (pre-releases - clause 10) or a plus sign (builds - clause 11) are not compatible with this PEP and are not permitted in the public version field.

(Ironically, they suggest using semver in the same section, saying "Even if a project chooses not to abide [...] by semver [...]".)

**Comment by reitzig** [comment]
> One possible mechanism to translate such semantic versioning based source labels to compatible public versions is to use the .devN suffix to specify the appropriate version order.

Another problem with that is that it's unnecessarily hard to determine `N` in CI-pipelines; for dev releases, I want to use Git hashes for unique identifiers but PEP 440 disallows that.

Ironically, the documentation of PIP [says](https://pip.pypa.io/en/stable/cli/pip_install/#pre-release-versions):

> If a version cannot be parsed as a compliant PEP 440 version then it is assumed to be a pre-release.

So I can't publish a version with poetry that pip _would_ install.
