### ISSUE TITLE
Poetry doesn't install github .tar.gz file but goes to pypi.

### ISSUE THREAD

**Issue by rvanlaar** [python-poetry/poetry#2527]
- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 16.04
- **Poetry version**: python 3.5.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/rvanlaar/23478879d7a084fdd5e2cd655f8187f8

## Issue
Poetry installs the original google charts wrapper from pypi instead of our version pinned via a tar.gz link.

Specifically:
This package is installed: https://github.com/kiesopmaat/google-chartwrapper as a source package via this link: https://github.com/kiesopmaat/google-chartwrapper/archive/e7bd81713daf0e4700e2c5bff56f5fdec0b15940.tar.gz

What happens is that poetry installs the 0.7 version package from PyPI.

**Comment by sdispater** [comment]
Poetry properly installs the package from the url (you can check your lock file which references the url).

The issue here is Poetry tries to retrieve the package version from the `PKGINFO` file which has this line `Version: 0.7` that's why it's reporting the version `0.7` being installed.

**Comment by neersighted** [comment]
There's no reported Poetry version and this issue has long been stale -- I am going to close it now. Please open a new issue with a reproduction if you believe this happens in a supported version of Poetry.
