### ISSUE TITLE
add a command to  uninstalls all packages not specified in poetry.lock

### ISSUE THREAD

**Issue by kwinstonix** [python-poetry/poetry#2528]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

Just like pipenv clean cmd
>   clean      Uninstalls all packages not specified in Pipfile.lock.

Benifit：

when run poetry in gitlab CI,  we usually use the feature of `Cache dependencies`,  It is better to remove old unused  packages. For example flake8 plugins `flake8-xxx` 

https://docs.gitlab.com/ee/ci/caching/

**Comment by sdispater** [comment]
This has already been implemented (see #2172) and it will be available in the next feature release.
