### ISSUE TITLE
`init` option to select Python version.

### ISSUE THREAD

**Issue by fcoclavero** [python-poetry/poetry#2529]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

Hello,

I wanted to add an option to the `init` command to select the Python version. This would be really useful when running in non-interactive mode, and a version different from the default is needed.

Thanks!

Resolves #2529

**Comment by hedythedev** [comment]
Shouldn't this be closed because #2561 is merged? Wonder why the pr wasn't linked even when `Resolves #2529` is in pr body

**Comment by fcoclavero** [comment]
> Shouldn't this be closed because #2561 is merged? Wonder why the pr wasn't linked even when `Resolves #2529` is in pr body

You're absolutely right. I'm closing this issue.
