### ISSUE TITLE
Un-pinned refs in pre-commit config can cause arbitrary code execution

### ISSUE THREAD

**Issue by ericfrederich** [python-poetry/poetry#2530]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu Linux 20.04
- **Poetry version**: Git's `master` branch

## Issue

The `rev` attribute for each pre-commit hook is currently set to a tag instead of Git SHA-1 checksum.  This is potentially dangerous for developers if the developers of `black`, `flake8`, `isort`, or `pre-commit-hooks` decided to be malicious and force-push an existing tag with malicious code.

The `pre-commit` command now supports `pre-commit autoupdate --freeze` which uses checksums in place of tags, but still preserves the tag as a comment.  This should be done.

**Comment by Secrus** [comment]
`black` is now part of PSF organization and the rest of mentioned are either PyCQA or maintained by the same people. Those are established organizations in Python community. I think they are ok to be trusted.

**Comment by neersighted** [comment]
I think for now we're going to consider this an acceptable risk given the state of the pre-commit ecosystem. This can be changed in the future, but I would want to make sure `pre-commit.ci` gains frozen autoupdate support before we change over.
