### ISSUE TITLE
Poetry doesn't appear to allow for efficient docker caching when using /src

### ISSUE THREAD

**Issue by curtiscook** [python-poetry/poetry#2549]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

From: https://python-poetry.org/docs/pyproject/#packages%C2%A0

If your package is included in a subdirectory (i.e. /src), you need to include the path as follows:

```
[tool.poetry]
# ...
packages = [
    { include = "my_package", from = "src" },
]
```

The problem is that if you have an actively developed package it's generally more efficient to cache requirements in the base image. This is normally easily accomplished by running `poetry install --no-dev --no-interaction` 

Unfortunately, if you have a /src directory and implement the package syntax, poetry will fail if the package is not there with the following error

```
/src/my_package does not contain any element
```

Suggestion/feature request: a flag to skip the packages block when installing the base image

**Comment by finswimmer** [comment]
Hello @curtiscook,

I don't really understand your use-case. But is the `--no-root` parameter for `poetry install` what you are looking for?

fin swimmer

**Comment by curtiscook** [comment]
it's not clear that --no-root supports skipping packages? 

If it does, it could possibly work?

As for my use case -- 

I want to install the base image with deps into an intermediate container & then install my package into a new container. This increases docker's ability to cache the repo. Currently, it wants to just fail the build. Maybe this should throw a warning w/ a suggestion with --no-root? 

I was able to work around it, but everything feels very abusive/hacky so I think that there should be more direct support (or documentation) for docker builds

**Comment by finswimmer** [comment]
> I want to install the base image with deps into an intermediate container & then install my package into a new container.

I'm not familiar with the docker stuff. But that sounds exactly like what `--no-root` is doing. It installs all you dependencies, but will not install the project's package itself.

**Comment by neersighted** [comment]
Duplicate #1132.
