### ISSUE TITLE
Select appropriate Python version from pyenv

### ISSUE THREAD

**Issue by tmshn** [python-poetry/poetry#2558]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

As of 2020 (at least on macOS), the most convenient way to manage (install, list, etc) multiple versions of Python is by using [`pyenv`](https://github.com/pyenv/pyenv) (although we don't need some mechanism like shims).

It'd be like a charm if Poetry automatically looks for Python versions listed by `pyenv` and choose appropriate one based on constraint (choose the best one from `pyenv versions list --bare` if the command is available).

**Comment by tmshn** [comment]
Just made very rough version of PR to how it might work: https://github.com/python-poetry/poetry/pull/2566

**Comment by finswimmer** [comment]
At Poetry we try to avoid implementations specific for third-party tools. But maybe it's possible to implement it as a plugin. Or you give #4852 a try. Maybe this works as well :)
