### ISSUE TITLE
Pip local install (via PEP 517) fails if a folder named LICENSES is present in the source code

### ISSUE THREAD

**Issue by MrJohz** [python-poetry/poetry#2565]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Linux (Pop OS 20.04)
- **Poetry version**: 1.0.9
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: See project [here](https://github.com/MrJohz/poetry-license-error-demo)

## Issue
Running `pip install .` in a poetry project that has a folder named `LICENSES` will fail with the following exception:
```
$ pip install .
Processing /home/frere76/projects/tests/poetry-licenses-bug
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Building wheels for collected packages: poetry-licenses-bug
  Building wheel for poetry-licenses-bug (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/frere76/.asdf/installs/python/3.8.3/bin/python3.8 /home/frere76/.asdf/installs/python/3.8.3/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmpjwp444l1
       cwd: /tmp/pip-req-build-u5w5jo8u
  Complete output (18 lines):
  Traceback (most recent call last):
    File "/home/frere76/.asdf/installs/python/3.8.3/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/home/frere76/.asdf/installs/python/3.8.3/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/frere76/.asdf/installs/python/3.8.3/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 204, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/tmp/pip-build-env-0mpwncyw/overlay/lib/python3.8/site-packages/poetry/masonry/api.py", line 62, in build_wheel
      WheelBuilder.make_in(
    File "/tmp/pip-build-env-0mpwncyw/overlay/lib/python3.8/site-packages/poetry/masonry/builders/wheel.py", line 55, in make_in
      wb.build()
    File "/tmp/pip-build-env-0mpwncyw/overlay/lib/python3.8/site-packages/poetry/masonry/builders/wheel.py", line 82, in build
      self._write_metadata(zip_file)
    File "/tmp/pip-build-env-0mpwncyw/overlay/lib/python3.8/site-packages/poetry/masonry/builders/wheel.py", line 188, in _write_metadata
      self._add_file(wheel, path, "%s/%s" % (self.dist_info, path.name))
    File "/tmp/pip-build-env-0mpwncyw/overlay/lib/python3.8/site-packages/poetry/masonry/builders/wheel.py", line 265, in _add_file
      with open(full_path, "rb") as src:
  IsADirectoryError: [Errno 21] Is a directory: 'LICENSES'
  ----------------------------------------
  ERROR: Failed building wheel for poetry-licenses-bug
Failed to build poetry-licenses-bug
ERROR: Could not build wheels for poetry-licenses-bug which use PEP 517 and cannot be installed directly
```

See the linked repository (https://github.com/MrJohz/poetry-license-error-demo) for a full reproduction example.

**Comment by MrJohz** [comment]
Having looked briefly through the source, I think the issue is here: https://github.com/python-poetry/poetry/blob/65e506879fa4b55b10bc8c984697eb660e3bf89a/poetry/masonry/builders/wheel.py#L186

Poetry automatically adds any `COPYING*` and `LICENSE*` files to the wheel if they exist.  The directory name `LICENSES` technically matches the second glob pattern, but as it is a directory it causes issues.

Perhaps a way of solving this would be to enumerate a few more different options for these automatic inclusion files:
* `LICENSE` and `COPYING` (with no extension, and not if they are directories)
* `LICENSE.*` and `COPYING.*` (with any extensions, and not if they are directories)
* `LICENSES/**` (any file that is in the folder LICENSES, as matches the [REUSE spec](https://reuse.software/spec/))

In addition, it would probably be useful to also allow the user to specify these included files manually, probably overwriting these defaults, but I think that is perhaps a bigger task and maybe requires its own feature request issue?

If it helps, I can create a pull request to implement the above changes (not including the manual file include part!)

**Comment by abn** [comment]
Another way to solve this and any similar issues might be to fix `_add_file` in `core` to recurse through all files correctly if directory.

https://github.com/python-poetry/core/blob/d582844eb503e6b0232c72680add2eb8b498a854/poetry/core/masonry/builders/wheel.py#L205-L236

**Comment by MrJohz** [comment]
@abn - would you prefer me to go down that route to fixing this issue?  I have a potential fix in PR #2573 - could you review this and check if this is sufficient?  If not I could create an alternative PR going down the route you suggest.

**Comment by milliams** [comment]
This issue is affecting `poetry build` as well which is preventing us from being able to make a release of our software. While waiting for a fix, is there a possible workaround?

As alluded to by @MrJohz, the use of the `LICENSES` directory will increase as it is a requirement of the [REUSE spec](https://reuse.software/spec/#license-files):

> Each License File MUST be placed in the `LICENSES/` directory in the root of the Project. The name of the License File MUST be the SPDX License Identifier of the license followed by an appropriate file extension (example: `LICENSES/GPL-3.0-or-later.txt`). The License File MUST be in plain text format.

**Comment by MrJohz** [comment]
As an aside, it looks like since I last looked at this, the relevant code moved to `python-poetry/poetry-core` [here](https://github.com/python-poetry/poetry-core/blob/ffc3d54ab6967c02a709ded79d579ced78e8ad49/poetry/core/masonry/builders/wheel.py#L169), which also makes the current pull request kind of useless.  @finswimmer / @abn  - is there a way for you to move this issue & PR to the other repository, or should I just create a new issue there?

I would second @milliams' point about the REUSE spec - it's becoming increasingly common to see this in research software engineering, and the fact that anyone trying to implement this spec cannot, by default, use poetry to manage their project makes this a bit of a blocker.
