### ISSUE TITLE
Bad link to "Managing environments" page.

### ISSUE THREAD

**Issue by knmarvel** [python-poetry/poetry#2570]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

On the [Commands](https://python-poetry.org/docs/cli/#env) page of the docs, in the `env` section, the `Managing environments` link is `https://python-poetry.org/docs/managing-environments.md`, which leads to a 404. The link should be `https://python-poetry.org/docs/managing-environments`.

**Comment by finswimmer** [comment]
Hello @knmarvel,

thanks a lot for reporting. :+1 However this was already fixed some days ago (https://github.com/python-poetry/poetry/pull/2559) and will be published with a new release.

fin swimmer
