### ISSUE TITLE
Type = "legacy" for all dependencies from custom package source

### ISSUE THREAD

**Issue by cpvandehey** [python-poetry/poetry#2571]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: 
- **Poetry version**: 
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue
Hello, ever since upgrading to `1.0.9`, I am starting to see type = "legacy" added to ALL ~80 dependencies in my project. It appears that even if they are at their most updated version, Poetry adds "legacy" as the type. 

I don't quite understand the process, but poetry deems anything from a private repository (all of my dependencies are from a custom source) as type "legacy". This seems super important to document and rename. The type should be something like "custom" or "private". Legacy gives the wrong idea. There could be underlying behavior tied to "legacy" that "private" might not need.

**Comment by abn** [comment]
@cpvandehey I believe this is in reference to the use of the [Warehouse Legacy API](https://warehouse.pypa.io/api-reference/legacy/) as the source. Most self-hosted repositories like Nexus, Artifactory etc. use this.

**Comment by abn** [comment]
Prior to `1.0.7`, source references for packages sourced from the [PyPI Legacy API](https://warehouse.pypa.io/api-reference/legacy/) were not correctly persisted. This was resolved in #1635.

Closing this issue as this is expected behaviour.

**Comment by cpvandehey** [comment]
Thanks @abn !
