### ISSUE TITLE
Add configuration to specify path to virtualenv / commandline

### ISSUE THREAD

**Issue by goodwillcoding** [python-poetry/poetry#2575]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request
**Configuration setting to specify which virtualenv script to use.**

Currently the virtualenv script is being looked for in the path, but for isolation issues it would be nice there could be a setting which sets the path to the virtualenv to use. Currently I work around this by having poetry run inside a virtualenv which seems like major overkill. Please let me know what you think of this.

Addititionally this setting could include the full call to virtualenv for example with "--no-download" and others which is crucial in isolated deployment.

**Comment by finswimmer** [comment]
Hello @goodwillcoding ,

there is already a feature request for this here: https://github.com/python-poetry/poetry/issues/1579

fin swimmer

**Comment by goodwillcoding** [comment]
@finswimmer Are you sure that's the same bug, I found issue #1579 and read it as specifying path to an existing virtual environment. Which to me read differently then path to virtualenv script which will create environment.

**Comment by finswimmer** [comment]
> Which to me read differently then path to virtualenv script which will create environment.

@goodwillcoding: Oh, then I misunderstood your request. What should be the benefit of this? I don't think this will get included to poetry directly, but it sounds that this might be something for the upcoming [plugin system](https://github.com/python-poetry/poetry/pull/1237)

fin swimmer

**Comment by goodwillcoding** [comment]
@finswimmer I've learned over the years is that having versions of virtualenv (and it's embedded packages) creates problems. Using specific virtualenv script (of specific version) has long added to stability and reproducibitly of the system.

**Comment by finswimmer** [comment]
Can you give an example of such a script, so I can better understand the use case?
