### ISSUE TITLE
Private Repositories Fail Silently on Auth Errors

### ISSUE THREAD

**Issue by TimOrme** [python-poetry/poetry#2576]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: MacOS 10.15.5
- **Poetry version**: 1.0.9
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/TimOrme/d69dc1f3ee6ce31cf93d154bd62d0595

## Issue
If using a private repository to install external dependencies, it currently fails silently if that private repository rejects the request due to authentication issues.  It would be good to instead at least log a warning to inform the user that the server didn't accept the request.  Otherwise, it seems to indicate a problem with the packages actually being present.

```bash
 % poetry add mypackage

[ValueError]
Could not find a matching version of package mypackage
```

If `mypackage` is only present in the private repo, but they don't have credentials set properly, it should indicate to the user that there was auth error on that repo.

**Comment by diogo-gaivota** [comment]
How did you know that it was authentication problem? I'm having a similar issue here, but even with -vvv, i hadn't any point on it.

**Comment by TimOrme** [comment]
I actually attached a debugger to discover it.  I also added the PR here https://github.com/python-poetry/poetry/pull/2577 which adds logging for that case, so I was able to verify in that branch that the return status was 403.

**Comment by diogo-gaivota** [comment]
The problem is the same to me. I got an 401 that failed silently.
