### ISSUE TITLE
GPG Package Signing CLI Feature

### ISSUE THREAD

**Issue by bitnom** [python-poetry/poetry#2578]
Let us consider the following twine options: 

`--sign --sign-with <gpg bin> --identity <key name>`

as important for package/repo security. These options should be added to the poetry CLI. If there are no objections (No reason it wouldn't be merged and not already in some branch or fork), I'll work on it.

I was just doing a bit more research at https://github.com/pypa/twine/issues/157 which gives me a good idea. This could be a nice feature for poetry. It could be the only module tool able to verify keys. We could establish a standard of adding the pgp public key to the page referenced in _pyproject.toml_ by `repository = <url>` or make a new parameter like `public-key = <url>`.

Example:
```
[tool.poetry]
public-key = https://github.com/python-poetry/poetry/blob/master/PGP
```

This would give a new CLI option: `poetry verify <packagename>`

what think?

**Comment by Secrus** [comment]
https://blog.pypi.org/posts/2023-05-23-removing-pgp/ PyPI no longer supports it, so I don't think it's worth anyone's time to implement.
