### ISSUE TITLE
Source Trove classifiers from canonical PyPA definitions

### ISSUE THREAD

**Issue by kdeldycke** [python-poetry/poetry#2579]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

I just stumble upon https://github.com/pypa/trove-classifiers , a package published and maintained by PyPA that is cataloguing all current and deprecated classifiers recognized on pypi.org . This is the canonical source of all trove definitions.

I propose to rely on this package to validate and check classifiers produced by poetry. Is that a good idea?

**Comment by kdeldycke** [comment]
Oh. One more thing: with the advance of a plugin system in the upcoming Poetry 1.1 release (see: https://github.com/python-poetry/poetry/issues/1856), shouldn't we send there a PR to add a new classifier dedicated to Poetry? Something like: `Framework :: Poetry`.

**Comment by pradyunsg** [comment]
For a new classifier, a request needs to be made to PyPI admins, and one of the criterion is that the classifier is immediately useful to at least 10 other packages/package maintainers (to avoid the case of adding classifiers for folks' pet projects that no one else uses).

I think it'd be worthwhile to wait until after the 1.1 release, before requesting for addition of the trove classifier.

**Comment by kdeldycke** [comment]
@pradyunsg oh yes you're right. In the mean time I checked the criterions for new inclusion and indeed, the classifier needs an existing base of relative popularity before being admitted into the reference. And I totally get it to not pollute the catalogue with short-lived or unmaintained projects.

**Comment by abn** [comment]
@kdeldycke I think it is reasonable to add this into the `check` command. I'd be hesitent to enforce this elsewhere however.

**Comment by kdeldycke** [comment]
Thanks @abn for the suggestion! I just pushed a PR at https://github.com/python-poetry/poetry/pull/2881 that is doing exactly that.
