### ISSUE TITLE
Poetry failed to detect conflicts between package "scikit-learn 0.23.1" and "python2.7"

### ISSUE THREAD

**Issue by zbw0046** [python-poetry/poetry#2588]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Debian 9.0
- **Poetry version**: 1.0.9
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/zbw0046/d0ee62349a162c2e173329636e61fa13

### Description

I'm using python2.7, and write a `pyproject.toml` file with the requirement `scikit-learn == 0.23.1`. Poetry is expected to raise an error because `scikit-learn` does not support python2 at version `0.23.1`. However, in my poetry it passed conflict checking.

### Step to reproduce
1. Using this toml file: https://gist.github.com/zbw0046/d0ee62349a162c2e173329636e61fa13
2. Run `poetry debug resolve -vvv`
3. You will get: 
```
Resolution results:

future                 0.18.2   python_version ~= "2.7" and sys_platform == "linux2"
numpy                  1.16.5   python_version ~= "2.7" and sys_platform == "linux2"
crcmod                 1.7      python_version ~= "2.7" and sys_platform == "linux2"
ffmpeg-python          0.1.17   python_version ~= "2.7" and sys_platform == "linux2"
opencv-python-headless 3.4.2.17 python_version ~= "2.7" and sys_platform == "linux2"
scikit-learn           0.23.1   python_version == "2.7" and sys_platform == "linux2"
```
### Expected behavior
Poetry should raise an error that `scikit-learn 0.23.1` conflicts with `python 2.7`.

**Comment by finswimmer** [comment]
Hello @zbw0046 ,

you are using a custom repository. In the repository there is only a `sdist` for `scikit-learn`. This `sdist` doesn't provide any information which python version it needs within the `PKG-INFO`, which is what `poetry` relies on. So this is something on `scikit-learn` side. Could you please report it there?

Concerning your PR: It is a very good idea to consider the anchor in the link, as this would improve the speed if dependency resolving if we could skip downloading some files :+1: I haven't went through the code until now, but in my opinion we should only take this into account for the question whether a file should be downloaded for inspection or not. The final python requirements should be read from the package itself.

fin swimmer

**Comment by zbw0046** [comment]
Hello @finswimmer ,

Thanks for your attention! I almost agree with your opinion. And I have some additional ideas: 

`scikit-learn` does not follow the rule. However, it is a well-known package among users in machine learning community. Furthermore, not following this rule seems to have no impact on installing this package using `pip` tool. Maybe we can use the anchor as a way of fault tolerance? For example, when `Requires-Python` does not exist in `PKG-INFO`, and it exists in anchor, we use the anchor to set the `requires-python` rather than do nothing. In `scikit-learn` case, this can prevent `poetry` to generate a requirement list that `pip` cannot successfully installs.

**Comment by finswimmer** [comment]
Hello @zbw0046,

you second idea should be the way to go :+1: 

I understand, that your first idea would be comfortable for poetry users, as it fixes mistakes made by package authors. But poetry tries to be as close as possible to standards and thus forcing package authors and others to do there job as responsable as possible as well. This will lead to less problems in the future hopefully. :crossed_fingers: 

fin swimmer

**Comment by dimbleby** [comment]
Today, locking the given pyproject.toml fails with this:
```
  SolverProblemError
                                                                                                                                 The current project's Python requirement (>=2.7,<3.0) is not compatible with some of the required packages Python requirement
:
    - scikit-learn requires Python >=3.6, so it will not be satisfied for Python >=2.7,<3.0

  Because test depends on scikit-learn (0.23.1) which requires Python >=3.6, version solving failed.
...
```
which seems to be approximately the desired outcome.

**Comment by Secrus** [comment]
Closing, as the issue seems to be resolved.
