### ISSUE TITLE
error message on malformed authors is not helpful

### ISSUE THREAD

**Issue by seansfkelley** [python-poetry/poetry#2592]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS Mojave
- **Poetry version**: 1.0.5
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: see below

```toml
[tool.poetry]
name = "docs"
version = "0.1.0"
description = ""
authors = ["foo@bar.com"]
```

## Issue

When trying to install with the above project configuration, I get something like:

```
$ poetry install
Installing dependencies from lock file

No dependencies to install or update


[AttributeError]
'NoneType' object has no attribute 'group'
```

As noted in https://github.com/python-poetry/poetry/issues/2263, Poetry expects the format `author <email>`. That's fine, but I had to run `poetry install -v` and read the implementation to realize that the problem was with the authors field. I won't try argue that it should accept plain emails here (though I personally think it should), but it definitely should try to be a bit more helpful with the messaging.

**Comment by finswimmer** [comment]
Hello @seansfkelley,

thanks for reporting and giving feedback :+1: However, this was reported already earlier in https://github.com/python-poetry/poetry/issues/1143 and a solution is in progress (https://github.com/python-poetry/poetry/pull/1935).

fin swimmer

**Comment by seansfkelley** [comment]
Hm, not sure how I didn’t turn that one up during search. Thanks!
