### ISSUE TITLE
poetry config certificates.my-private-pypi.cert doesn't work

### ISSUE THREAD

**Issue by z0h** [python-poetry/poetry#2593]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: MacOS 10.15.5
- **Poetry version**: 1.09
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/nbka/5cca8fdacc04700a1abbbfd4b31e8d4a
(irrelevant bits omitted)

## Issue
Configuring a certificate for a private repo via the below doesn't work:

`poetry config certificates.my-private-pypi.cert /Users/xxx/yyy_ca.pem`

However pointing to the pem file via "export REQUESTS_CA_BUNDLE" will make it work. If it matters the below configs are also set:

```
virtualenvs.create = true
virtualenvs.in-project = true
```

**Comment by jamiemoore** [comment]
I can't seem to make export REQUESTS_CA_BUNDLE work either.  When set, Pip works fine.  Poetry not so much.  Configured as per the documentation. https://python-poetry.org/docs/repositories/ using poetry version 1.1.4

**Comment by pierresouchay** [comment]
same issue here

**Comment by intgr** [comment]
I can confirm this is fixed in Poetry 1.2.0b2
