### ISSUE TITLE
Poetry 1.1.0a2 SolverProblemError: Failure to resolve dependencies when environment markers are used

### ISSUE THREAD

**Issue by hukkinj1** [python-poetry/poetry#2604]
Poetry 1.1.0a2 fails at resolving dependencies in `poetry-core` CI. I've described the problem more thoroughly in a PR here https://github.com/python-poetry/poetry-core/pull/39

**Comment by sdispater** [comment]
I know where the issue is coming from and I should have a fix ready this week. It will be available in the next prerelease.

**Comment by hukkinj1** [comment]
This seems fixed now in the latest alpha. Closing
