### ISSUE TITLE
CLI: `poetry init -n` logs misleading messages

### ISSUE THREAD

**Issue by seansfkelley** [python-poetry/poetry#2606]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS Mojave
- **Poetry version**: 1.0.9
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: n/a

## Issue

```
$ poetry init -n

This command will guide you through creating your pyproject.toml config.


You can specify a package in the following forms:
  - A single name (requests)
  - A name and a constraint (requests ^2.23.0)
  - A git url (git+https://github.com/python-poetry/poetry.git)
  - A git url with a revision (git+https://github.com/python-poetry/poetry.git#develop)
  - A file path (../my-package/my-package.whl)
  - A directory (../my-package/)
  - A url (https://example.com/packages/my-package-0.1.0.tar.gz)

$ 
```

Looks like the interactive-by-default behavior is leaking through. FWIW, I like the `-n` flag because I never want to specify my dependencies interactively, so this is not a veiled suggestion to remove it. I just wanted to bring this to your attention as it could be potentially confusing to users new to Poetry and/or look broken.

**Comment by finswimmer** [comment]
This is fixed in the current preview released (1.2.0a2).
