### ISSUE TITLE
Asking for package the vendors libs

### ISSUE THREAD

**Issue by eamanu** [python-poetry/poetry#2607]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

Hi Everybody,

Currenlty, I'm working on Poetry package on Debian [0]. Poetry, depends from many modules
that currently are not in Debian yet. I start working on someone of them, but the process to accept
a new package could be long.

I would really like that poetry could be into Debian before the freeze for the next release of Debian.

Will be very appreciate if you can package the dependencies. This kind of package
is common on pipenv [1]  an pip [2], just for give some examples.

[0] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=947261
[1] https://github.com/pypa/pipenv/tree/master/pipenv/vendor
[2] https://github.com/pypa/pip/tree/master/src/pip/_vendor

Thanks!

**Comment by abn** [comment]
@eamanu I'd recommend reading the thread on #2346. We have made the decision not to vendor dependencies for the `poetry` project itself. The `poetry-core` project itself is a special case more similar to `pip` and hence why vendor a small set of dependencies there. This is done in such a way that it can be dbundled by package maintainers as bundling is not recommended by distribution packaging guidelines ususally.

**Here be dragons**
As for your case, you could temporarily (until all the required dependencies get packaged) make use of the `sonnet` script that is used to generate the poetry distribution artifact used by the `get-poetry.py` script. However, it is important to note that this is not a *supported* method and you will be doing this at your own risk of breakage.
