### ISSUE TITLE
Poetry crashing on empty dist-info folder

### ISSUE THREAD

**Issue by bharel** [python-poetry/poetry#2608]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOSX 15
- **Poetry version**: 1.1.0a2

## Issue
If you try to run `poetry update` when you have an empty .dist-info folder in your current working directory, or inside any other directory on the `sys.path`, poetry will crash with a random non-indicative exception, and you'll stand there crying, not knowing what you did wrong.

![image](https://user-images.githubusercontent.com/742359/86182741-2e261880-bb39-11ea-9f79-65bf72f8d77c.png)

After crying for 2 hours, I've figured out the issue and created a PR.

Now I'm happy.

**Comment by Secrus** [comment]
The problem seems to no longer exist. Closing
