### ISSUE TITLE
How to have `my-script --version` return version

### ISSUE THREAD

**Issue by alexbode** [python-poetry/poetry#2612]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Issue

```[tool.poetry]
version = "0.1.21"
[tool.poetry.scripts]
my-script = 'poetry.console:run'
```

Is there an easy way to have `my-script --version` return 0.1.21? I am using fire cli to create a cli tool and I can create a function that returns the value 0.1.21. But, since I did not see anything in the documentation about this I was wondering if this can be done through poetry, which would make version control much easier.

Update:
Is there any way to update the executable file during buidl time from 
```
#!/usr/local/opt/python/bin/python3.7
# -*- coding: utf-8 -*-
import re
import sys
from src.cli import wrapper
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(wrapper())
```

to:
```
#!/usr/local/opt/python/bin/python3.7
# -*- coding: utf-8 -*-
import re
import sys
import argparse
from src.cli import wrapper
if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument("-v", "--version", action='version', version='0.1.21')
    parser.parse_args(['--version'])
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(wrapper())
```

**Comment by finswimmer** [comment]
Hello @alexbode,

thanks a lot for your interest on poetry. However this is a plain python question.

Nevertheless I'll answer :)

The version specified in your `pyproject.tom` can be received by using `importlib.meta` within your script after your package is installed. See https://github.com/python-poetry/poetry/pull/2366#issuecomment-652418094

As a complete example:

```bash
mypackage
├── mypackage
│   ├── __init__.py
│   └── console.py
└── pyproject.toml
```

`pyproject.toml`:

```
[tool.poetry]
name = "mypackage"
version = "0.1.0"
description = ""
authors = ["finswimmer <finswimmer@example.com>"]

[tool.poetry.scripts]
my-script = "mypackage.console:run"

[tool.poetry.dependencies]
python = "^3.6"
importlib-metadata = {version = "^1.0", python = "<3.8"}

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"
```

`__init__.py`:

```python
try:
    import importlib.metadata as importlib_metadata
except ModuleNotFoundError:
    import importlib_metadata

__version__ = importlib_metadata.version("mypackage")
```

`console.py`:

```python
import argparse
import sys

from mypackage import __version__


def get_arguments():
    parser = argparse.ArgumentParser()
    parser.add_argument("-v", "--version", action="store_true")
    return parser.parse_args()


def run():
    args = get_arguments()

    if args.version:
        print(__version__)
        sys.exit()


if __name__ == "__main__":
    run()
```

```bash
$  poetry run my-script --version
0.1.0
```

**Comment by alexbode** [comment]
@finswimmer 
Thank you very much for the help, I was not away of importlib_metadata.version function but it solves my use case perfectly.

Have a great day!
