### ISSUE TITLE
poetry version - increment __version__ in __init__.py too!

### ISSUE THREAD

**Issue by logangrado** [python-poetry/poetry#2614]
When running the command `poetry version`, it increments the version in the `pyproject.toml`. However, the version in the project itself remains the same. 

It should be straightforward to also update the version in `<project>/__init__.py` to ensure they match.

Without incrementing this version, you will see different versions in `pip list` as you do when you actually import the package and call `<package>.__version__`

**Comment by finswimmer** [comment]
Hello @logangrado,

this was requested earlier in https://github.com/python-poetry/poetry/issues/144

The solution is to use `importlib.metadata` (`importlib_metadata` for python <3.8). See:

- https://github.com/python-poetry/poetry/issues/1036#issuecomment-489880822
- https://github.com/python-poetry/poetry/issues/144#issuecomment-623927302
- https://github.com/python-poetry/poetry/pull/2366#issuecomment-652418094

fin swimmer

**Comment by omry** [comment]
This solution is incompatible with tools that are parsing the __init__.py file to extract the version.
An example is towncrier, which is used to generate project release notes.
