### ISSUE TITLE
Black console output is invisible

### ISSUE THREAD

**Issue by FichteFoll** [python-poetry/poetry#2616]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option). 

- **OS version and name**: Arch Linux
- **Poetry version**: 1.0.9
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: *skip*

## Issue

When using lock with debug mode `-vvv`, poetry uses black text (ANSI escapes) for some of its messages that are simply unreadable on dark consoles. Following is an example image:

![2020-07-02_14-49-19_cli_poetry-black](https://user-images.githubusercontent.com/931051/86361005-7e08fa80-bc73-11ea-939a-5346b928f078.png)

While one could say this is a terminal emulator issue, I don't think it's ever reasonable to use black or white color codes without also setting a background color, which would be totally inappropriate as that grabs a lot of attention. If this text is not deemed important, some dimmed text might be more reasonable? Or just use normal text color since this is debug mode only.

Related: #1934

**Comment by sdispater** [comment]
This is fixed on the `develop` branch, and available in the latest `1.1` prerelease, by dimming the message instead of setting to black.
