### ISSUE TITLE
Add ability to specify a set of dev dependencies to install toghether with all regular dependencies

### ISSUE THREAD

**Issue by fredrikaverpil** [python-poetry/poetry#2628]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

I use poetry together with nox or tox. I then run multiple nox or tox sessions in CI, all of them starting with a `poetry install`. This installation takes up a lot of time, as this will install ~100 packages on my end.

I could look into venv caching, but I would rather start fresh each time and install my package and then a selection packages relevant to my nox or tox session.

I would've wanted to take the approach seen in the [Hypermodern Python setup](https://github.com/cjolowicz/hypermodern-python/blob/264698776f40b3a902a658b24ef49add7d2bb1f6/noxfile.py#L14-L39), where you can install one ore more dependencies (and its sub-dependencies) only, and constrain all versions to poetry's lockfile.

So, imagine something like;

```bash
$ poetry install --no-dev flake8 mypy pytest
```

The above would then install my package and its production requirements. But it would also install flake8, mypy and pytest, all constrained to the versions stipulated by poetry.lock.

However, if I want to do this today, I would need to define flake8, mypy and pytest twice in my `pyproject.toml` file, both as extras/opional under dependencies and again under dev-dependencies.

It would be nice to instead simply be able to pick dev-dependencies already specified.

**Comment by finswimmer** [comment]
Hello @fredrikaverpil,

your feature request sounds similar to https://github.com/python-poetry/poetry/issues/1644, is it?

fin swimmer

**Comment by fredrikaverpil** [comment]
Oh, indeed it is. I will close this issue in favor for #1644

Thanks for letting me know!
