### ISSUE TITLE
Basic Usage doesn't include directions for active projects

### ISSUE THREAD

**Issue by Natetronn** [python-poetry/poetry#2630]
- [x ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

Basic usage: https://python-poetry.org/docs/basic-usage/

Please add a note about setting up poetry inside a project when the project previously existed i.e. `poetry new poetry-demo` isn't available to us because poetry-demo (or whatever) already exists.

**Comment by 8F3E** [comment]
For those who want a quick fix now:
```bash
$ cd pre-existing-project
$ poetry init
```

I'm happy to modify the documentation.
