### ISSUE TITLE
30 minutes and still not done installing

### ISSUE THREAD

**Issue by Natetronn** [python-poetry/poetry#2631]
- [x ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [ x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Manjaro 20.0.3
- **Poetry version**: 1.0.9
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/Natetronn/55a22d921be54ee2c88d4006f05a8f16
## Issue

It seems this is a recurring issue and it may not be addressable under the current ecosystem, from what I've read in the other reports but, thought I'd share the pyproject.toml in case it could somehow be useful. In particular, pyqt5 takes over 30 minutes all by itself.

**Comment by finswimmer** [comment]
Hello @Natetronn ,

`poetry` and `pip` both choose the `sdist` for installing. And this one needs to get compiled. This is why it takes so long to install.

fin swimmer

**Comment by Natetronn** [comment]
Thanks for the reply!

Too bad we couldn't choose our own local compiler instead. PyQt5 takes all of 20 seconds to download and build using the AUR.
Or at least be able to easily point poetry virtual environments to a system resource that's already in place. Not sure if any of that is possible or without issue, of course, just saying.
