### ISSUE TITLE
An option for `--system-site-packages` in virtual environment creation

### ISSUE THREAD

**Issue by thanhnguyen2187** [python-poetry/poetry#2634]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request
Hi,

I encountered a weird bug while trying to install Kivy along with a project created by Poetry. The versions are like this:
- Linux (Kubuntu 20)
- PyCharm Professional 2020.1.2
- Python 3.8
- Poetry 1.0.9

My steps were:
- Follow the guide on [Kivy's Linux installation page](https://kivy.org/doc/stable/installation/installation-linux.html) that should be shortened to: `sudo apt-get install python3-kivy`.
- Create a new project with Poetry.
- Set the environment to be locally created (let Poetry create a folder named `.venv` inside the source folder).
- Try `import kivy` in a file.

I expected using Kivy would work this way, but it did not. After a while tinkering around, I finally found the solution:
- Remove `.venv`.
- Create `.venv` again using the command `python3 -m venv .venv --system-site-packages`.

I think an option like this in Poetry would be nice to have. The document should warn people to use the option if their Python code have some system-specific installation (e.g. `sudo apt install python3-...`).

Thanks for reading.

**Comment by samvasko** [comment]
Some prior work done here
https://github.com/python-poetry/poetry/pull/1404 and  https://github.com/python-poetry/poetry/pull/1982

**Comment by thanhnguyen2187** [comment]
> 
> 
> Some prior work done here #1404 and #1982

Thanks. I really did a poor job searching for the issues 🤦‍♀️... Let us hope that this will be resolved soon.
