### ISSUE TITLE
Licence missing from .egg-info

### ISSUE THREAD

**Issue by Corfucinas** [python-poetry/poetry#2635]
- [ x ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [ x ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

- **OS version and name**: Windows 10 
- **Poetry version**:  1.0.9

<details open>
<summary> pyproject.toml </summary>

[tool.poetry]
name = "my-project"
version = "0.1.0"
description = "A description"
authors = ["Name <email>"]
license = "MIT"
readme = "README.md"
homepage = "repo"
repository = "repo"
keywords = ["a", "b", "b"]

[tool.poetry.dependencies]
python = "^3.8"
pandas = "^1.0.5"
numpy = "^1.19.0"
requests = "^2.24.0"
click = "^7.1.2"
retry = "^0.9.2"
tqdm = "^4.47.0"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
mypy = "^0.782"
sphinx = "^3.1.1"
pytest = "^5.4.3"
coverage = {extras = ["toml"], version = "^5.1"}
pytest-cov = "^2.10.0"
pytest-mock = "^3.1.1"
sphinx-autodoc-typehints = "^1.11.0"
nox = "^2020.5.24"
flake8-annotations = "^2.1.0"
flake8-bandit = "^2.1.2"
flake8-black = "^0.2.0"
flake8-docstrings = "^1.5.0"
flake8-import-order = "^0.18.1"
safety = "^1.9.0"
darglint = "^1.4.1"
wemake-python-styleguide = "^0.14.0"
xdoctest = "^0.12.0"
bump2version = "^1.0.0"
sphinx_autodoc_typehints = "^1.11.0"
isort = "^5.0.3"

[tool.black]
line-length = 79
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
)
'''

[tool.coverage.paths]
source = ["src", "*/site-packages"]

[tool.coverage.run]
branch = true
source = ["project"]

[tool.coverage.report]
show_missing = true

[tool.poetry.scripts]
project= "project.main:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

## Issue

I noticed that the licence is currently missing on the .egg-info generated by the install function. 
Currently, it shows up as `License: UNKNOWN`.
However, when using `Poetry build`, the licence does shows up. 
Inquiring if this is normal behavior, thanks for the response

**Comment by err931** [comment]
I had the same issue.

I think the following patch will fix it. Apply it in the "lib" directory of the installation.

```diff
diff --git a/poetry/masonry/builders/sdist.py b/poetry/masonry/builders/sdist.py
index 5408922..d513b23 100644
--- a/poetry/masonry/builders/sdist.py
+++ b/poetry/masonry/builders/sdist.py
@@ -30,6 +30,7 @@ setup_kwargs = {{
     'version': {version!r},
     'description': {description!r},
     'long_description': {long_description!r},
+    'license': {license!r},
     'author': {author!r},
     'author_email': {author_email!r},
     'maintainer': {maintainer!r},
@@ -185,6 +186,7 @@ class SdistBuilder(Builder):
                 version=to_str(self._meta.version),
                 description=to_str(self._meta.summary),
                 long_description=to_str(self._meta.description),
+                license=to_str(self._meta.license),
                 author=to_str(self._meta.author),
                 author_email=to_str(self._meta.author_email),
                 maintainer=to_str(self._meta.maintainer),
```

-----

__This problem also occurs in the pre-release version.__
Send a pull request if needed. Please let me know which branch I should apply it to.

**Comment by err931** [comment]
We have confirmed that this issue has been fixed in __1.1.0b1.__

I suggest you run `poetry self update --preview` to install the pre-release version.

**Comment by err931** [comment]
@finswimmer Since this issue seems to be resolved, is it possible to close it instead?

**Comment by Corfucinas** [comment]
Yes, thanks for the reply!
