### ISSUE TITLE
Path dependencies are not installed correctly

### ISSUE THREAD

**Issue by albireox** [python-poetry/poetry#2638]
- **OS version and name**: macOS 10.15.5
- **Poetry version**: 1.1.0a2

I have a package that uses Poetry and has the structure `sdsstools/src/sdsstools` with the `pyproject.toml` being at the root of that directory tree. If I add it as a path dependency as

```
sdsstools = {path = '../sdsstools/'}
```

the package is installed in editable mode but then it cannot find the sdsstools module. The `site-packages/sdsstools.pth` file create contains `/Users/albireo/Documents/Code/sdss5/sdsstools` where it should be `/Users/albireo/Documents/Code/sdss5/sdsstools/src`.

On a side note, every time I run `poetry update` the path dependency is installed anew with the message

```
- Updating sdsstools (0.1.0 /Users/albireo/Documents/Code/sdss5/sdsstools -> 0.1.11-alpha.0 /Users/albireo/Documents/Code/sdss5/sdsstools)
```

which is doubly weird because versions `0.1.0` doesn't make sense at all.

**Comment by samatjain** [comment]
I've noticed the same on 1.1.0a2, different way to get there trying to add a script.

With a src directory layout:

```
.
├── pyproject.toml
├── README.rst
├── src
   └── testmodule
      ├── __init__.py
      ├── __main__.py
```

and pyproject.toml:

```
[tool.poetry]
name = "testmodule"
version = "0.1.0"

[tool.poetry.scripts]
argh = "testmodule.__main__:main"

[tool.poetry.dependencies]
python = "^3.8"

[build-system]
requires = ["poetry-core>=1.0.0a5"]
build-backend = "poetry.core.masonry.api"
```

attempting to run "argh" fails:

```
$ poetry run argh
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'testmodule'
```

The .pth file for "testmodule" should have "src", as the OP mentions. Add it manually to poetry's venv's `site-packages/testmodule.pth` and everything works fine.

**Comment by albireox** [comment]
It seems 1.1.0a3 fixed the original problems but it's also removing the dependencies of the path dependency so it cannot be imported.

**Comment by finswimmer** [comment]
Seems to be fixed.

Feel free to leave a comment if you disagree.
