### ISSUE TITLE
Suddenly unable to run Poetry

### ISSUE THREAD

**Issue by shrvtv** [python-poetry/poetry#2639]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 20.04 LTS
- **Poetry version**: 1.0.9
-**Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/shrvtv/ce0577fa7cd34971ca8e00483ee42aa2

## Issue
Whenever I try to run poetry with poetry run or poetry update etc it stops working and exits with this:

```
shrvtv@shrvtv-T470:~/python-project-lvl1$ poetry update
/home/shrvtv/.poetry/lib/poetry/_vendor/py2.7/subprocess32.py:149: RuntimeWarning: The _posixsubprocess module is not being used. Child process reliability may suffer if your program uses threads.
  "program uses threads.", RuntimeWarning)

[UnexpectedCharError]
Unexpected character: u'T' at line 8 col 4
```

How do I fix this? Reinstallation didn't work

**Comment by finswimmer** [comment]
Hello @shrvtv ,

```
classifiers = [
    Topic :: Games/Entertainment
]
```

you are missing quotes around the classifiers:

```
classifiers = [
    "Topic :: Games/Entertainment"
]
```

fin swimmer
