### ISSUE TITLE
Strange downgrades when adding new deps.

### ISSUE THREAD

**Issue by dekoza** [python-poetry/poetry#2642]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Manjaro Linux, latest
- **Poetry version**: 1.0.9
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/dekoza/cb68a98e677c984c1188fc2a634ada41

## Issue
I observed strange downgrade when adding new deps to my project. Aside the fact that whole process takes almost 15 minutes (8 minutes resolving, 7 minutes lock writing; I blame it on `aws-cdk` galaxy), some packages get downgraded. Then, after the install, I run `poetry update` (another 15 minutes) - each downgraded package is upgraded back to latest version.

Both my pyproject.toml and example process is attached in gist link above.

**Comment by tomzx** [comment]
It appears that for the dependencies you've specified, it takes about 10s to do version solving, but that it takes a large amount of time to go through graph building (`Solver._build_graph()`) using `poetry` 1.1.10.

Through a process of adding dependencies, I've identified that `aws-cdk.aws-rds` and `ws-cdk.aws-ecs` (together), `aws-cdk.aws-ecs-patterns` (by itself) seems to be causing some issue. There's over 700k calls  (I had to kill it) to `Solver._build_graph()` which doesn't appear to be normal.

Graph building will need to have better logging facilities to debug this issue :)

**Comment by abn** [comment]
Is this still an issue? With the `pyprojec.toml` provided:

```console
   1: Version solving took 74.620 seconds.
   1: Tried 1 solutions.

Writing lock file
```

Unable to reproduce the downgrades with the version on master. If this is still an issue please comment.
