### ISSUE TITLE
False SolverProblemError with Python version

### ISSUE THREAD

**Issue by atollk** [python-poetry/poetry#2646]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

- **OS version and name**: Microsoft Windows 10 Enterprise, Build 18363
- **Poetry version**: 1.0.9
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/atollk/8726831acc855e44993bbaaefcccc9c2

## Issue
Running `poetry update` results in:
```[SolverProblemError]
The current project's Python requirement (^3.8) is not compatible with some of the required packages Python requirement:
  - flake8-annotations requires Python >=3.6.1,<3.9

Because no versions of flake8-annotations match >2.2.0,<3.0.0
 and flake8-annotations (2.2.0) requires Python >=3.6.1,<3.9, flake8-annotations is forbidden.
So, because xxx depends on flake8-annotations (^2.2.0), version solving failed.
```

Which obviously doesn't make any sense. flake8-annotations would be completely fine with a Python 3.8. In fact, changing the version to "3.8.2" explicitly rather than "^3.8" removes the error.

**Comment by finswimmer** [comment]
Hello @atollk,

please see me answer in https://github.com/python-poetry/poetry/issues/1930#issuecomment-653906544 for what's going on here.

fin swimmer
