### ISSUE TITLE
Poetry Setting for PyPI Name (different from module name)

### ISSUE THREAD

**Issue by EntilZha** [python-poetry/poetry#2647]
- [x ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

I tried using the `poetry publish` command for my package

* Github: https://github.com/EntilZha/PyFunctional
* PyPI: https://pypi.org/project/PyFunctional/

and got an error indicating I don't have permission to upload for the project `functional`. I looked at the source code https://github.com/python-poetry/poetry/blob/b19873ae4f4391b89bd6fe89aed52963c44db078/poetry/masonry/publishing/publisher.py#L29 and fairly certain that it is because it uses the package name, but my PyPI name is different (`functional` vs `PyFunctional`).

My feature request is that poetry should provide a setting to change the name of the PyPI project, separately from the python module name, but with the default being the module name.

**Comment by sdispater** [comment]
This is expected since the `name` property will be used when publishing. So you should set it to `PyFunctional` and add the `packages` property to your `pyproject.toml` file, like so:

```toml
[tool.poetry]
name = "PyFunctional"
# ...
packages = [
    {include = "functional"}
]
```

Here is the relevant documentation section: https://python-poetry.org/docs/pyproject/#packages
