### ISSUE TITLE
Add `--system` option to `poetry install`

### ISSUE THREAD

**Issue by logangrado** [python-poetry/poetry#2652]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

As the title suggests, I'd like the option to install to the system python, as opposed to always creating a virtual environment.

Before you say "but you should ALWAYS be in a virtual environment!", that's mostly true. However, when submitting jobs to clusters, you often must install your dependencies and launch the task within a shell script, and `poetry shell` launches an interactive shell, which breaks this usage pattern.

Yes, I know it's possible to just use `poetry run`. However, the system I'm creating is supposed to support poetry, Pipenv AND plain old requirements.txt files, which means I need to launch the actual python code with `python`. 

An alternative solution, if you all are really against a `--system` option, would be to add a `poetry source` command (in addition to `poetry shell`), which WOULD NOT launch a subshell.

**Comment by finswimmer** [comment]
Hello @logangrado,

this is already possible by setting `virtualenvs.create` to `false` in the config, either global with `poetry config virtualenvs.create false` or for the project only with `poetry config --local virtualenvs.create false`.

fin swimmer

**Comment by logangrado** [comment]
Oh thanks fin, couldn't find that anywhere in the docs.
