### ISSUE TITLE
Add Dockerfiles

### ISSUE THREAD

**Issue by roipoussiere** [python-poetry/poetry#2653]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

Docker images of Python shipped with Poetry could be very useful for Continuous Integration tools.

I just created one [here](https://github.com/roipoussiere/python-poetry-dockerfile), and I can do the same for all Python versions and make a PR here if you want.

**Comment by abersheeran** [comment]
https://github.com/Docker-s-IMAGES/no-pypoetry 

I created a mirror that can help any project that contains poetry to build a mirror that does not contain poetry. This can greatly reduce the size of the final image.

By the way, I don't think it is necessary to include poetry/pipenv in the final image.

**Comment by max-wittig** [comment]
This would be very nice. Currently we also do this in another private repo. Just using the upstream poetry image would simplify things a lot

**Comment by mkniewallner** [comment]
There's another open issue with a bit more details on the implementation and a linked draft PR, so closing this one in favor of https://github.com/python-poetry/poetry/issues/4036.
