### ISSUE TITLE
Local path dependencies cannot be updated/rebuilt on update

### ISSUE THREAD

**Issue by supermihi** [python-poetry/poetry#2660]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows 10 Version 2004
- **Poetry version**: 1.0.9
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: not relevant

## Issue
I have added a dependency to a setuptools package in a local path (`poetry add <...path to setup.py directory>`). That package contains native python modules which are built by setuptools. Poetry did build and install the package on the initial `add` command.

Now, the external package is updated via `git pull`. Another manual call to `setup.py build` or `setup.py install` in that package's directory causes te native modules to be rebuilt. However, it does not seem possible to trigger such a rebuilt from poetry. I have tried `poetry install` but that command does not seem to notice that the dependency has changed.

*Hint*: the dependency is *not* under semantic versioning. I noticed that manually increasing the version in `setup.py` *does* cause a subsequent `poetry install` to recompile the module. But is it possible to rebuild without increasing the version?

**Comment by finswimmer** [comment]
Hello @supermihi,

path dependencies are installed as "editable" by default. This means any change in the code of this dependency is immediately available to your project.

The only time `poetry install` will show you that it will update this path dependency, is when the version number in the `setup.py` has changed.

fin swimmer

**Comment by supermihi** [comment]
Hello @finswimmer,
that might be true for pure python modules, but what about modules written in C/C++ that need to be compiled through `setup.py build`?

Apparently, poetry  *does* call something like `setup.py install` or `setup.py build` upon `poetry add`, but I did not find a way to re-trigger the compilation after updating the `cpp` sources. Are you saying that running `poetry run python <path/to/setup.py> install` is the way to go?

**Comment by finswimmer** [comment]
Hello again,

if you C sources that need to get compiled, than you cannot use the development mode. Add an `develop=false` to the dependency in the `pyproject.toml` for this, e.g.

```
[tool.poetry.dependencies]
python = "^3.6"
testproject = {path = "../testproject", develop=false}
```

But you have to change the version number within your `setup.py`. Otherwise poetry has no chance to recognize that there is an update.

So if you switch off development mode like above, make a change to your code of this dependency, change the version number in the `setup.py` and rerun `poetry install`.

**Comment by supermihi** [comment]
Thanks for the clarification.
