### ISSUE TITLE
--remove-untracked does not work

### ISSUE THREAD

**Issue by cw-intellineers** [python-poetry/poetry#2661]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **Poetry version**: 1.0.9

## Issue
According to the documentation `poetry install --remove-untracked` should work. In version 1.0.9 however, it gives me a `NoSuchOptionException`.

**Comment by PetterS** [comment]
Yes, the documentation on the home page is for an unreleased version of Poetry.

**Comment by cw-intellineers** [comment]
Ah ok. Any idea when this will happen? And in the meantime, is there a workaround instead of deleting the virtualenv and installing everything from scratch?

**Comment by PetterS** [comment]
No, you have to delete the virtualenv.

**Comment by cw-intellineers** [comment]
Thanks for the answer. Any ETA when the version of poetry is released?

**Comment by stephsamson** [comment]
> Thanks for the answer. Any ETA when the version of poetry is released?

It should be in late August or early September.
