### ISSUE TITLE
[1.1.0a3] Does not export env markers

### ISSUE THREAD

**Issue by s0undt3ch** [python-poetry/poetry#2662]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Arch Linux
- **Poetry version**: 1.1.0a3
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: [using `platform`](https://gist.github.com/s0undt3ch/1f0cbe44d170bb2a02bb9eb9e9f3f1f6#file-pyproject-toml) and [using `markers`](https://gist.github.com/s0undt3ch/4f2cc21faacb2f9f377bcd3579683300#file-pyproject-toml)

## Issue
Poetry 1.1.0a3 does not "export" environment markers either by using `platform` or `markers` in the dependency definition

**Comment by myoung34** [comment]
I can confirm this behavior.

for now I'm having to work around it with 

```
gen_requirements_dev:
        poetry export --without-hashes --dev -f requirements.txt | sed 's/\(pybluez==.*\)/\1; platform_system == "Linux"/g' >requirements-dev.txt
```

which feels really dirty

**Comment by bneijt** [comment]
This is a regression from 1.0.10. We get python markers but not platform markers:
```
FROM python:3.8-slim

WORKDIR /project

RUN pip install poetry==1.0.10 \
    && poetry new 1010 \
    && cd 1010 \
    && poetry add loguru \
    && poetry export --without-hashes -f requirements.txt |sort > reqs.txt \
    && pip uninstall -y poetry

RUN pip install poetry==1.1.0rc1 \
    && poetry new 110rc1 \
    && cd 110rc1 \
    && poetry add loguru \
    && poetry export --without-hashes -f requirements.txt |sort > reqs.txt \
    && pip uninstall -y poetry

RUN grep marker */poetry.lock

RUN cat 1010/reqs.txt

RUN cat 110rc1/reqs.txt

ENTRYPOINT "/bin/bash"
```
will result in:
```
Step 6/8 : RUN cat 1010/reqs.txt
 ---> Running in e6cc151075fa
colorama==0.4.3; sys_platform == "win32"
loguru==0.5.3
win32-setctime==1.0.2; sys_platform == "win32"
Removing intermediate container e6cc151075fa
 ---> 7568f92263c2
Step 7/8 : RUN cat 110rc1/reqs.txt
 ---> Running in 201adead5df8
colorama==0.4.3; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.5.0"
loguru==0.5.3; python_version >= "3.5"
win32-setctime==1.0.2; python_version >= "3.5"
Removing intermediate container 201adead5df8
```
showing that RC1 does not add the `sys_platform` markers that 1.0.10 did add.

**Comment by bneijt** [comment]
After reviewing the above docker build, it's clear that the sys platform marker is missing in the lock file, so the exporter is probably doing the right thing and this is just the lock mechanism not picking up on the platform marker anymore:
```
root@055eb589ab63:/project# grep -A20 -B2 'name = "win32-setctime' */poetry.lock
1010/poetry.lock-description = "A small Python utility to set file creation time on Windows"
1010/poetry.lock-marker = "sys_platform == \"win32\""
1010/poetry.lock:name = "win32-setctime"
1010/poetry.lock-optional = false
1010/poetry.lock-python-versions = ">=3.5"
1010/poetry.lock-version = "1.0.2"
1010/poetry.lock-
--
110rc1/poetry.lock-
110rc1/poetry.lock-[[package]]
110rc1/poetry.lock:name = "win32-setctime"
110rc1/poetry.lock-version = "1.0.2"
110rc1/poetry.lock-description = "A small Python utility to set file creation time on Windows"
110rc1/poetry.lock-category = "main"
110rc1/poetry.lock-optional = false
110rc1/poetry.lock-python-versions = ">=3.5"
110rc1/poetry.lock-
```
