### ISSUE TITLE
Consistent naming for package files

### ISSUE THREAD

**Issue by allyraza** [python-poetry/poetry#2669]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

First thank you for this wonderful project!

I have been meaning to start something to consolidate current package management tools to make it something that gives you unified and deterministic package management experience never, then a colleague told me about `poetry`.

I would like to know was there any particular reason for not using a consistent naming for `.toml` and `.lock` files, what about `poetry.toml` for toml file and `poetry.lock`  for lock file

**Comment by abn** [comment]
Poetry makes use of the [tool table](https://www.python.org/dev/peps/pep-0518/#tool-table) as defined in [PEP 518](https://www.python.org/dev/peps/pep-0518/#file-format) to store its configuration. TLDR; poetry likes to adhere to defined standards rather than introduced a bespoke configuration file.

**Comment by allyraza** [comment]
I am wondering why you were so quick to close the issue.

I am not taking about any bespoke configuration format I am talking about file names it should consistent look at the any other package manager (e.g. cargo) they have `Cargo.toml`, `Cargo.lock` which btw poetry is using as inspiration.

**Comment by finswimmer** [comment]
Hello @allyraza,

the `pyproject.toml` is at least needed for defining `poetry` as a build-backend as defined by PEP 518.  So the name of the file is not an invention by poetry. `poetry` could have chosen to store all it's tool specific configuration in a separate `poetry.toml` file. But this would introduce a new file and you have to care about both. Also as @abn mentioned the `tool` section was introduced (even if it was not intended at first place) to store tool specific thing.

`poetry.lock` is a file that only contains things maintained by poetry itself. So naming it this way makes perfectly sense.

fin swimmer
