### ISSUE TITLE
Ability to install project dependencies into arbitrary virtualenv specified by path

### ISSUE THREAD

**Issue by m-khvoinitsky** [python-poetry/poetry#2670]
Right now it's possible to only specify directory where poetry will create virtualenv, not the final virtualenv directory (or am I missing something?) which is extremely inconvenient during deployment.

There *is* a workaround: install poetry itself into desired virtualenv and it will use it which is what I'm doing now, but there is a problem: project dependencies may conflict with poetry dependencies (which is happening in my case).

**Comment by stephsamson** [comment]
If I understand this correctly, you want to be able to name your own virtualenv directory and not just specify the path, correct?

If so, something that I do is actually create the virtualenv directory with [`venv`](https://docs.python.org/3/library/venv.html), `cd` into that, activate that virtualenv, and run `poetry install`. Poetry will [check if it's in a virtualenv and use that](https://python-poetry.org/docs/managing-environments/).

**Comment by finswimmer** [comment]
Hello @m-khvoinitsky,

this was ask earlier in #1579. Please also have a look at my concerns about in https://github.com/python-poetry/poetry/issues/1579#issuecomment-561153861 and https://github.com/python-poetry/poetry/issues/1579#issuecomment-561276121.

fin swimmer
