### ISSUE TITLE
How to build for manylinux2014

### ISSUE THREAD

**Issue by dimaqq** [python-poetry/poetry#2672]
What I've tried so far:

`docker run -v (pwd):/src -it quay.io/pypa/manylinux2014_x86_64 sh`

```sh
source $HOME/.poetry/env
cd /src
poetry env use /opt/python/cp38-cp38/bin/python
poetry install
poetry run pytest
poetry build
```

Builds: `mypackage-V.V-cp38-cp38-linux_x86_64.whl`

I'd expect it to build `mypackage-V.V-cp38-cp38-manylinux2014_x86_64.whl` instead

**Comment by sdispater** [comment]
You need https://github.com/pypa/auditwheel as far as I know to build manylinux wheels

**Comment by TheErk** [comment]
Right after the wheel has been built by poetry you need to call:

auditwheel repair dist/*.whl

then you'll get the manylinux wheel.

and you need to install auditwheel.

**Comment by dimaqq** [comment]
Yes indeed, with a small correction: wheels must be processed one at a time.
