### ISSUE TITLE
allow poetry new in a current project

### ISSUE THREAD

**Issue by roipoussiere** [python-poetry/poetry#2675]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

I usually don't start a Python project with a `poetry new`. I start a Python project by writing a simple script, then several Python files, and when the project starts to grow, I wonder about the packaging.

Let a project `foo`, at this point, I have to:

- go to the parent folder: `cd ..`;
- rename my project to a temporary name: `mv foo _foo`;
- create a new poetry project with the project name: `poetry new foo`;
- move the files generated by poetry to my project folder: `mv foo/pyproject.toml _foo`, `mv foo/foo _foo/foo`, etc. (and not the reverse to keep VCS history);
- remove the folder generated by Poetry: `rmdir foo`
- rename by project folder to actual name: `mv _foo foo`
- go to that folder: `cd foo`

That's a lot of steps. I suggest the possibility to create a new project in the current folder (just like `git init` for instance), with the command `poetry new` (without argument). Then the user just moves the files according to the new hierarchy.

If there are file name conflicts, Poetry could do nothing and print warnings (or ideally, ask what to do).

I know the `poetry init` command, but I like `poetry new` because it produce a nice project hierarchy.

**Comment by finswimmer** [comment]
At the moment we don't plan anything like this. I would recommend to always start with `poetry new` regardless whether you plan to create a package or not.
