### ISSUE TITLE
`SolverProblemError` happens with unclear version specification error

### ISSUE THREAD

**Issue by himkt** [python-poetry/poetry#2676]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 20.04
- **Poetry version**: 1.0.9
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/himkt/b92e6391b150fa320fa7813df4738943
- `setup.py`: https://gist.github.com/himkt/832038a04fd0f81f66d67553b5a847c8
- PyPI: https://pypi.org/project/konoha
- Raw log of `poetry add -vvv konoha -E all_with_integrations`: https://gist.github.com/himkt/0cbdb631d1555cb96aafea347c5da1bb

## Issue

I encountered the error in installing a third-party library, named [Konoha](https://github.com/himkt/konoha) which I'm developing myself.
When I try to install konoha with extras by running the following command: `poetry add konoha -E all_with_integrations`, I got the following error message.

```bash
[SolverProblemError]
Because no versions of konoha match >4.4.0,<5.0.0
 and konoha (4.4.0) depends on sudachidict_core (>=20200330,<20200331), konoha (>=4.4.0,<5.0.0) requires sudachidict_core (>=20200330,<20200331).
So, because no versions of sudachidict-core match >=20200330,<20200331
 and sample depends on konoha (^4.4.0), version solving failed.
The command '/bin/sh -c poetry add konoha -E all_with_integrations' returned a non-zero code: 1
```

> konoha (4.4.0) depends on sudachidict_core (>=20200330,<20200331), konoha (>=4.4.0,<5.0.0) requires sudachidict_core (>=20200330,<20200331)

It doesn't make sense for me because the depending and the requiring are identical.
(`sudachidict_core (>=20200330,<20200331)`)

You can reproduce the results by executing the following step.

```
git clone git@github.com:himkt/poetry-failure.git && \
  cd poetry-failure && docker build -t himkt/poetry-failure .
```

I'm not sure if it is the problem of Poetry or the problem of my `pyproject.toml`.
So I'd really appreciate if someone gives me any kind of information or pointers. 🙇‍♂️ 

Maybe duplicate of https://github.com/python-poetry/poetry/issues/1589,
but let me keep the issue open, as it was opened half a year ago with no update.

Thanks,

**Comment by himkt** [comment]
Note that `pip==20.0.2` and `pipenv==2020.6.2` work well.
- pip: https://github.com/himkt/poetry-failure/blob/master/Dockerfile.pip
- pipenv: https://github.com/himkt/poetry-failure/blob/master/Dockerfile.pipenv

**Comment by sanzoghenzo** [comment]
I'm having the same problem with poetry 1.0.10.

Adding the dependency to a new project without extras runs fine, but if I use `poetry add pyswsutils[all]` or `poetry add pyswsutils -E all` I got the same kind of error as @himkt .

[Gist with poetry output and pyproject.toml](https://gist.github.com/sanzoghenzo/c0ce4aa0d6bc62db3883484879d720c9)

using `poetry run pip install pyswsutils` (it's on a private repo) works fine, and seeing the `extra == "gis" or extra == "all"` I can see that the test in #2680 is covering the problem.

**Comment by himkt** [comment]
@sanzoghenzo 

FIY but in my environment, `poetry 1.1.0a3` works fine.
(`pip install --pre poetry` installs the latest non-stable version of poetry)

**Comment by sanzoghenzo** [comment]
You're right @himkt , I just updated to `poetry 1.1.0b2` and it works!

Thanks
