### ISSUE TITLE
The Pytest module automatically installed by Poetry is outdated

### ISSUE THREAD

**Issue by roipoussiere** [python-poetry/poetry#2679]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Manjaro
- **Poetry version**: 1.0.9
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: *not relevant*

## Issue

After a `poetry new`, Poetry installs Pytest, but the installed version is `3.10.3`, the current Pytest version is `5.4.3`.

**Comment by zyrikby** [comment]
It took me a while to find out that outdated pytest dependency causes an issue in my newly created projects. I wrote about my current detour in a [blog post](https://zhauniarovich.com/post/2020/2020-09-poetry-pytest/).

**Comment by abn** [comment]
The new command is more a convenience. This means that it is the responsibility of the project maintainer to update their dependencies.

As a quick fix you can simply do `poetry add -D pytest@latest`. And it should update to the latest version of `pytest`.

In the long run, the `new` command will no longer add any dependencies by default and leave that to the maintainers. (#2768). 

Closing this as this is not really an issue that needs any further action at the moment.
