### ISSUE TITLE
How do I find outdated dependencies?

### ISSUE THREAD

**Issue by WhyNotHugo** [python-poetry/poetry#2684]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue
I've a large project with ~32 pinned dependencies.

`poetry update` is good for updating within the constraints of these project.

However, I want to find which dependencies are out of date. E.g.: list all dependencies for which I've pinned a specific version, but has newer releases.

I try to proactively keep my deps up to date, but so far I've been manually checking in pypi if each one has a new version. How can I figure out this using poetry?

**Comment by sdispater** [comment]
You can use the `poetry show` command with the `--outdated/-o` option:

```bash
poetry show -o
```

For more information, you can check out the documentation: https://python-poetry.org/docs/cli/#show

**Comment by levrik** [comment]
@sdispater Is there a way to filter this to top-level dependencies only? Without this the option is quite useless for me.

**Comment by WhyNotHugo** [comment]
Is this issue a WONTFIX?

This is becoming super annoying to deal with manually, especially for large projects.

**Comment by SamuelMS** [comment]
@abn I agree here – I only care about our top-level dependencies, not the stuff five levels deep. `poetry show -o` is really noisy for large projects.

**Comment by vertti** [comment]
It seems crazy that the default isn't just showing the outdated top-level dependencies. That is usually the only thing that a project has control over and/or should mess with. So why, by default, show a lot of unnecessary info mixed in?

**Comment by sinoroc** [comment]
From my point of view...

When talking about dependencies, there are 2 cases:
* either you are working on an application, that should be installed in isolation (so you can control all requirements in the virtual environment), in which case all dependencies matter, you may want total control and pin everything.
* either you are working on a library, that should be installed alongside other libraries and the parent application, in which case you only want to specify version ranges of the direct top-level dependencies of your own library.

So from my point of view, if you care about outdated dependencies then you are most likely in the first case and so you should care about all dependencies not only the top-level ones.

**Comment by SamuelMS** [comment]
> either you are working on an application, that should be installed in isolation (so you can control all requirements in the virtual environment), in which case all dependencies matter, you may want total control and pin everything.

I think this is rather pedantic. In my experience, most developers don't care about second- or third-level dependencies – just the top-level dependencies that their application directly relies on – in the same way that they don't think about OS-level dependencies (i.e. what version of g++ is installed, or even Python).

We use automated code-/dependency-scanning tools (HP Fortify, Whitesource, Snyk, etc) to look for CVEs, license or breaking changes, etc – and these are helpful for monitoring dependencies deeper down the stack, both in and outside of Python. These tools go hand-in-hand with the current default behavior of the `show` command.

Still, it would be very helpful to help developers filter out the noise and be able to ask "which of the stuff that **I installed directly** (read: listed in `pyproject.toml`) has new versions available?" – this seems like a pretty natural feature to have.

**Comment by ruohola** [comment]
```
poetry show --outdated | grep --file=<(poetry show --tree | grep '^\w' | cut -d' ' -f1)
```

seems to work okishly to only show outdated top-level dependencies.

**Comment by plazmakeks** [comment]
Following the approach by @ruohola I noticed `flake8` has a dependency called `mccabe` which notes `flake8` in its description and would be returned be the upper solution. To avoid this i'm using this one now:

`poetry show --outdated | grep -P "^($(poetry show --tree | grep '^\w' | cut -d' ' -f1 | paste -s -d"|" -))"`

**Comment by ruohola** [comment]
> Following the approach by @ruohola I noticed `flake8` has a dependency called `mccabe` which notes `flake8` in its description and would be returned by the upper solution. To avoid this i'm using this one now:
> 
> `poetry show --outdated | grep -P "^($(poetry show --tree | grep '^\w' | cut -d' ' -f1 | paste -s -d"|" -))"`

This fails with macOS `grep`:

```
$ poetry show --outdated | grep -P "^($(poetry show --tree | grep '^\w' | cut -d' ' -f1 | paste -s -d"|" -))"
grep: invalid option -- P
usage: grep [-abcdDEFGHhIiJLlMmnOopqRSsUVvwXxZz] [-A num] [-B num] [-C[num]]
	[-e pattern] [-f file] [--binary-files=value] [--color=when]
	[--context[=num]] [--directories=action] [--label] [--line-buffered]
	[--null] [pattern] [file ...]
```

This

```
poetry show --outdated | grep --file=<(poetry show --tree | grep '^\w' | sed 's/^\([^ ]*\).*/^\1/')
```

should accomplish the same and work with any `grep` and `sed`.

**Comment by Hultner** [comment]
> ```
> poetry show --outdated | grep --file=<(poetry show --tree | grep '^\w' | cut -d' ' -f1)
> ```
> 
> 
>      
>   
> 
> seems to work okishly to only show outdated top-level dependencies.

Looks like this is already covered, I ran into the same problem with dependencies either mentioning a top level one or if their name contains it for instance `coollib-extension` showing up due to `coollib` being a top level dependency. I just added `^coollib\s` to the final grep pattern so it would enforce an exact match on the leading word.

Looks like you did almost the same thing but without the requirment for a full match. However my command is uglier since I just tacked the sed on after the cut. Anyway this is useful to me so thought I'd share.
`poetry show --outdated | grep --file=<(poetry show --tree | grep '^\w' | cut -d' ' -f1 | sed 's/.*/^&\\s/')`

**Comment by torstenrudolf** [comment]
Why is this issue closed? Why do the maintainers regard this as a solution to the feature request? 
It would be nice to have a simple option on `poetry show` to see this information without piping in 2 `grep`s and a `sed`.

---
Ultimately, it would be great to have something like [scala-steward](https://github.com/scala-steward-org/scala-steward) for python.

**Comment by pySilver** [comment]
I'd love to see this option built-in

**Comment by ralphbird** [comment]
It would be even better if it updated the pyproject.toml on either directly or allow the user to approve/reject each update.  For the majority of packages we use we don't mind what version it is **provided everyone on the team is using the same version** but some have very specific requirements that we don't want to update without thought.

**Comment by darkpixel** [comment]
Looks like there's an open issue where the discussion continues: #4175
