### ISSUE TITLE
[Linux, 1.1.0a3, Python3.6] X is not a supported wheel on this platform.

### ISSUE THREAD

**Issue by scoiatael** [python-poetry/poetry#2688]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Linux; Docker `python:3.6` image
- **Poetry version**: 1.1.0a3
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://github.com/scoiatael/poetry-grpcio-issue/blob/master/pyproject.toml

## Problem with installation of `grpcio` on Python 3.6 with Poetry 1.1.0a3

First of all looks like faster installation in 1.1 will be a great feature, can't wait to have it on stable :)

However when I tried using that feature to speed up our Docker build I encountered a problem with installation of `grpcio` on python 3.6 (works on 3.8 fine, also works with Poetry 1.0.9 on both Python versions):
```
Command ['/root/.cache/pypoetry/virtualenvs/poetry-grpcio-issue-o9msT97p-py3.6/bin/python', '-m', 'pip', 'install', '--no-deps', '/root/.cache/pypoetry/artifacts/e4/1a/fb/cc14443ebcdd3b0d5df7ca7fbffdc7d9343564703a67906925174cd179/grpcio-1.30.0-cp36-cp36m-manylinux2010_x86_64.whl'] errored with the following return code 1, and output:
  grpcio-1.30.0-cp36-cp36m-manylinux2010_x86_64.whl is not a supported wheel on this platform.
  You are using pip version 18.1, however version 20.2b1 is available.
  You should consider upgrading via the 'pip install --upgrade pip' command.


  at /usr/local/lib/python3.6/site-packages/poetry/utils/env.py:937 in _run
       933│                 output = subprocess.check_output(
       934│                     cmd, stderr=subprocess.STDOUT, **kwargs
       935│                 )
       936│         except CalledProcessError as e:
    →  937│             raise EnvCommandError(e, input=input_)
       938│
       939│         return decode(output)
       940│
       941│     def execute(self, bin, *args, **kwargs):

```

You can find minimal working example [here](https://github.com/scoiatael/poetry-grpcio-issue).

Cheers!

**Comment by scoiatael** [comment]
@abn I confirmed it works with `develop` branch (https://github.com/scoiatael/poetry-grpcio-issue/commit/0d3f83de3ebc8f29c210880993e0f12ad23c01fa).
Awesome, thanks for quick response and I'm waiting for next pre-release then :)

**Comment by dbalabka** [comment]
It seems I'm getting the same error on `1.1.4`

**Comment by sinoroc** [comment]
@dbalabka Are you sure it is the same error? Would you mind showing us the full console output of the command (in _verbose_ mode `-vvv`) containing you error?

**Comment by dbalabka** [comment]
@sinoroc it looks like the same error but for a different package.
```
You can uninstall at any time by executing this script with the --uninstall option,
and these changes will be reverted.
Installing version: 1.1.4
  - Downloading poetry-1.1.4-linux.tar.gz (57.03MB)
Poetry (1.1.4) is installed now. Great!
To get started you need Poetry's bin directory ($HOME/src/releases/76/.poetry/bin) in your `PATH`
environment variable. Next time you log in this will be done
automatically.
To configure your current shell run `source $HOME/src/releases/76/.poetry/env`
Installing dependencies from lock file
Package operations: 87 installs, 0 updates, 0 removals
  • Installing pyasn1 (0.4.8)
  • Installing six (1.15.0)
  • Installing cachetools (4.1.0)
  • Installing certifi (2020.4.5.1)
  • Installing chardet (3.0.4)
  • Installing idna (2.9)
  • Installing protobuf (3.12.1)
  • Installing pyasn1-modules (0.2.8)
  • Installing pycparser (2.20)
  • Installing rsa (4.0)
  • Installing urllib3 (1.25.9)
  • Installing cffi (1.14.0)
  • Installing google-auth (1.15.0)
  • Installing pytz (2020.1)
  • Installing zipp (3.1.0)
  • Installing requests (2.23.0)
  • Installing googleapis-common-protos (1.51.0)
  • Installing bcrypt (3.1.7)
  • Installing cryptography (2.9.2)
  • Installing google-api-core (1.17.0)
  • Installing importlib-metadata (1.6.1)
  • Installing lazy-object-proxy (1.4.3)
  • Installing pynacl (1.3.0)
  • Installing numpy (1.17.4)
  • Installing dataclasses (0.7)
  • Installing pyparsing (2.4.7)
  • Installing typed-ast (1.4.1)
  • Installing wrapt (1.11.2)
  EnvCommandError
  Command ['/home/src/releases/76/.venv/bin/pip', 'install', '--no-deps', '/home/.cache/pypoetry/artifacts/0b/fe/ce/206b9be2dff6f98091c9f1ea636402b3cb4a72afce26b0478f0508fd0c/cryptography-2.9.2-cp35-abi3-manylinux2010_x86_64.whl'] errored with the following return code 1, and output: 
  cryptography-2.9.2-cp35-abi3-manylinux2010_x86_64.whl is not a supported wheel on this platform.
  You are using pip version 9.0.3, however version 20.2.4 is available.
  You should consider upgrading via the 'pip install --upgrade pip' command.
  
  at .poetry/lib/poetry/utils/env.py:1074 in _run
      1070│                 output = subprocess.check_output(
      1071│                     cmd, stderr=subprocess.STDOUT, **kwargs
      1072│                 )
      1073│         except CalledProcessError as e:
    → 1074│             raise EnvCommandError(e, input=input_)
      1075│ 
      1076│         return decode(output)
      1077│ 
      1078│     def execute(self, bin, *args, **kwargs):
```

**Comment by sinoroc** [comment]
_cryptography_ again? There have been quite some reports of failures on the _cryptography_ dependency. Not sure what the root link between those reports is if any, or if it is just a coincidence. In one of the cases, it turned out to be that the _pip_ version used was too old somehow.

**Comment by dbalabka** [comment]
@sinoroc I've rollback to Poetry version `1.0.10` and it works. It seems I'm running a pretty old version of pip `9.0.3`. If it is the cause then it would be good to set a minimum required pip version or report a warning.

**Comment by sinoroc** [comment]
@dbalabka Oh, yes, the pip version string is right there in the error message you posted. I had not seen it earlier: "_pip version 9.0.3_". Which is quite old indeed (and might have issues with the _manylinux2010_ tag maybe?). Although I am a bit surprised that this version of _pip_  is used at all. As far as I know, poetry relies on _virtualenv_. And virtualenv usually installs up-to-date pip versions in the virtual environments it creates. I wonder if maybe at this point, we are not in a usual virtual environment but maybe in a temporary build environment. Those environment might follow different rules.

Not sure it has an influence on the _pip_ version issue, but @dbalabka what installation method did you use to install _poetry_ itself? The `get-poetry.py` method or a different one?

**Comment by dbalabka** [comment]
@sinoroc sorry about the delay. Here is the script which I use to install poetry during the build:
```
curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | POETRY_VERSION=1.0.10 POETRY_HOME="$(pwd)/.poetry/" python
```

**Comment by sinoroc** [comment]
@dbalabka Have you tried removing the `.venv` directory and restarting from scratch?

**Comment by dbalabka** [comment]
@sinoroc I've fixed the by installing the latest version of pip. So, it would be great to add some warning message which warns the user about possible issues.

**Comment by sinoroc** [comment]
@dbalabka But there was a warning message from _pip_:

> You are using pip version 9.0.3, however version 20.2.4 is available.
> You should consider upgrading via the 'pip install --upgrade pip' command.

The default behaviour is for _poetry_ to delegate the creation of virtual environments to _virtualenv_, and _virtualenv_ takes care of installing recent versions of _pip_, _setuptools_, etc.

Not sure how it happened that you had such an old _pip_ in that virtual environment.

**Comment by dbalabka** [comment]
@sinoroc poetry uses OS's preinstalled pip if it is not installed in venv. I don't have permissions to updated OS pip. I have to install newest version of pip under venv and it solves the problem.

**Comment by sinoroc** [comment]
@dbalabka What poetry version are you using?

**Comment by dbalabka** [comment]
> @sinoroc sorry about the delay. Here is the script which I use to install poetry during the build:
> 
> ```
> 
> curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | POETRY_VERSION=1.0.10 POETRY_HOME="$(pwd)/.poetry/" python
> 
> ```

@sinoroc it is `POETRY_VERSION=1.0.10`

**Comment by sinoroc** [comment]
@dbalabka I see... I am not sure how it is supposed to behave in that older version. With poetry 1.1 it seems it always uses virtualenv and thus pip is always quite recent. At least that is what I understood, I might be wrong.

**Comment by dbalabka** [comment]
@sinoroc thanks for your time. I think the problem is solved.

**Comment by amjltc295** [comment]
I got a similar error:
```
  EnvCommandError

  Command ['/Users/allen.c/Library/Caches/pypoetry/virtualenvs/app-6aZ328yD-py3.8/bin/pip', 'install', '--no-deps', '-U', '/Users/allen.c/Library/Caches/pypoetry/artifacts/cd/11/54/fd481eec49cddc06876e526483e7ee8675d0910fed2aa7668a9fc88e62/MarkupSafe-2.0.1-cp38-cp38-mac
osx_10_9_x86_64.whl'] errored with the following return code 1, and output:
  ERROR: MarkupSafe-2.0.1-cp38-cp38-macosx_10_9_x86_64.whl is not a supported wheel on this platform.
  WARNING: You are using pip version 20.2.2; however, version 21.1.2 is available.
  You should consider upgrading via the '/Users/allen.c/Library/Caches/pypoetry/virtualenvs/app-6aZ328yD-py3.8/bin/python -m pip install --upgrade pip' command.
```
That pip version was a warning and I ignored it. However, at the end I found that by running what it says 
```
/Users/allen.c/Library/Caches/pypoetry/virtualenvs/app-6aZ328yD-py3.8/bin/python -m pip install --upgrade pip
``` 
fixed the problem.
