### ISSUE TITLE
"--author" option for "new"

### ISSUE THREAD

**Issue by tmywada** [python-poetry/poetry#2697]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request
Scenario:
Generate new folder with specific author name(s)
Command:
poetry new --src "XXX" (--author "xxx yy@gmail.com")
Expected outcome:
new directory, and a toml file with defined authors

Current version returns an error message ('' The "--author" option does not exist.") We can get the expected output by:
1) generate folder with "new" and swap toml file
2) generate toml file with "initi" option
It would be nice to add "--author" option for "new" command. 

The following is the error message when I use "--author" option for "new" command:
```
  Stack trace:

  11  ~/.poetry/lib/poetry/_vendor/py3.7/clikit/console_application.py:124 in run
      self, args, input_stream, output_stream, error_stream

  10  ~/.poetry/lib/poetry/console/config/application_config.py:213 in create_io
      resolved_command = application.resolve_command(args)

   9  ~/.poetry/lib/poetry/_vendor/py3.7/clikit/console_application.py:110 in resolve_command
      return self._config.command_resolver.resolve(args, self)

   8  ~/.poetry/lib/poetry/_vendor/py3.7/clikit/resolver/default_resolver.py:34 in resolve
      return self.create_resolved_command(result)

   7  ~/.poetry/lib/poetry/_vendor/py3.7/clikit/resolver/default_resolver.py:166 in create_resolved_command
      if not result.is_parsable():

   6  ~/.poetry/lib/poetry/_vendor/py3.7/clikit/resolver/resolve_result.py:43 in is_parsable
      self._parse()

   5  ~/.poetry/lib/poetry/_vendor/py3.7/clikit/resolver/resolve_result.py:49 in _parse
      self._parsed_args = self._command.parse(self._raw_args)

   4  ~/.poetry/lib/poetry/_vendor/py3.7/clikit/api/command/command.py:113 in parse
      return self._config.args_parser.parse(args, self._args_format, lenient)

   3  ~/.poetry/lib/poetry/_vendor/py3.7/clikit/args/default_args_parser.py:53 in parse
      self._parse(args, _fmt, lenient)

   2  ~/.poetry/lib/poetry/_vendor/py3.7/clikit/args/default_args_parser.py:101 in _parse
      self._parse_long_option(token, tokens, fmt, lenient)

   1  ~/.poetry/lib/poetry/_vendor/py3.7/clikit/args/default_args_parser.py:247 in _parse_long_option
      self._add_long_option(name, None, tokens, fmt, lenient)

  NoSuchOptionException

  The "--author" option does not exist.

  at ~/.poetry/lib/poetry/_vendor/py3.7/clikit/args/default_args_parser.py:300 in _add_long_option
      296│     def _add_long_option(
      297│         self, name, value, tokens, fmt, lenient
      298│     ):  # type: (str, Optional[str], List[str], ArgsFormat, bool) -> None
      299│         if not fmt.has_option(name):
    → 300│             raise NoSuchOptionException(name)
      301│ 
      302│         option = fmt.get_option(name)
      303│ 
      304│         if value is False:
```

**Comment by palette-swapped-serra** [comment]
Just a quick related question: where does `poetry new`  read the *default* author name from? It seems to work transparently (using the user's .gitconfig data) on one of my Windows accounts, but not another (where it just defaults to `"Your Name <you@example.com>"`).

**Comment by zahlman** [comment]
Just a quick related question: whence exactly does `poetry new` read the *default* author info? It seemed to come from the signed-in user's `.gitconfig`, but it doesn't seem to work consistently.

**Comment by finswimmer** [comment]
I think we should make `poetry new` an extension of `poetry init`. This is why I'm closing this in favor of #2563.
