### ISSUE TITLE
Restrictive transitive versioning of Python

### ISSUE THREAD

**Issue by atollk** [python-poetry/poetry#2700]
-  [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Microsoft Windows 10 Enterprise Build 18363
- **Poetry version**: 1.1.0a3
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/atollk/db657cf9d4d869ee2d89273c4a9926a3

## Issue
As described in issues such as #2646, Python versioning transitively "corrupts" project dependencies. In the gist above, if `private_pkg` requires `python = "^3.8,<3.9"` (which is very common to see on PyPi), poetry will raise a SolverProblemError because my `"^3.8"` includes 3.9 which would conflict with `private_pkg`'s `<3.9`. This forces me to add the constraint `<3.9` to all of my packages until 3.9 releases at which point I will have to manually change all of them again.

Solving problems like this is the very point why one uses a dependency manager. poetry should recognize that version 3.8 is a valid solution to both constraints and thus be able to install it. Is there a reason why it works the way it does?

If you point me to a starting point in the code, I'd be willing to make a PR to fix this.

**Comment by finswimmer** [comment]
Hello @atollk,

poetry's version solver does not solve the dependencies for the currently used python version. Instead it makes sure that all dependencies can be solved for all python version to which the project should be compatible. That's one of the goals of poetry: Describing a valid configuration for the project. That's a big advantage over other tools.

> If you point me to a starting point in the code, I'd be willing to make a PR to fix this.

We really appreciate that you like to contribute to poetry. Thanks a lot :+1: But in this case there is nothing to change, as this behavior works exactly as it is intended.

fin swimmer

**Comment by atollk** [comment]
@finswimmer 
How is forcing the user to add constraints that they do not care about an advantage? What exactly is that "goal" you're describing for poetry? 
Can you point me to where this has been thoroughly discussed and decided?

**Comment by finswimmer** [comment]
Hello @atollk,

the general goal is described in the [introduction of the docs](https://python-poetry.org/docs/#introduction) as:

> Poetry is a tool for dependency management and packaging in Python. It allows you to declare the libraries **_your project depends on_** and it will manage (install/update) them for you.

If one say that the project depends on python >=3.8,<4.0, but declares a library that is not available for python 3.9, poetry take care about it and tell you that. This is an advantage, as you can already react on this fact during development.

**Comment by atollk** [comment]
How would I react on that? If a library is not available for 3.9 at the moment then I can't change that. Printing a warning such as "Your project won't support 3.9 because you use package X"? That's fine, sure. I still don't see what advantage one gains from making this a hard error. 

Neither do I see how that relates to the paragraph you cited. My project requires any version from 3.8 up. The code that I have written uses features from 3.8 but is still compatible with 3.9. If some other library, maybe five levels down the dependency chain, differs from that, that should not force me to change my project.
And certainly the paragraph does not talk about delibaretly not automatizing certain steps.

**Comment by finswimmer** [comment]
> I still don't see what advantage one gains from making this a hard error.

`poetry` protects you to declare project dependencies that will not work.

> Neither do I see how that relates to the paragraph you cited

The importent part was in bold. With `poetry` you declare the libraries the whole project depends on. This is different to other tools, which usually only take the current environment into account or let you write anything in, without making sure that it is correct.

> The code that I have written uses features from 3.8 but is still compatible with 3.9. If some other library, maybe five levels down the dependency chain, differs from that, that should not force me to change my project.

If any of the dependencies is not compatible to version 3.9 your whole project isn't compatible to version 3.9, because you need a package that is not supported for this. What you should do in such a case is:

* Check if you realy need this package or if there are alternatives
* Check if you realy need to support python 3.9
* If the answer is yes: Contact the maintainer of the package and asked them why there is a restriction in the supported python version and if this can be changed
* Fork the project and change the restriction on your own

There might be cases, where a package is only needed up to a specific python version, e.g. `imortlib_metadata` for python <3.8. Then you can use [multiple constraints definition](https://python-poetry.org/docs/dependency-specification/#multiple-constraints-dependencies).

**Comment by atollk** [comment]
> poetry protects you to declare project dependencies that will not work.

How is that an advantage? What gain do I have from not being able to write "^3.8" when that is all my code requires?

> The importent part was in bold. With poetry you declare the libraries the whole project depends on. This is different to other tools, which usually only take the current environment into account or let you write anything in, without making sure that it is correct.

By that logic, why is it acceptable that I don't have to list transitive requirements? If my project uses package A and A uses package B, my project depends on B. So with the same argument, I should have to declare B as a dependency. But that doesn't make sense, the same way that having to restrict my versioning because of some dependency doesn't make sense.

> What you should do in such a case is: [...]

And the fact that this list is considered to be "work that just has to be done" is the huge disadvantage this bug (or missing feature, however you want to call it) brings.

**Comment by sdispater** [comment]
@atollk 

> What gain do I have from not being able to write "^3.8" when that is all my code requires?

You can and should put `^3.8` if that's what your project support.

What you need to understand is why this feature has been implemented. Let's say we have this configuration:

```toml
[tool.poetry.package]
name = "project"
version = "1.2.3"

[tool.poetry.dependencies]
python = "^3.8"
my-package = "^1.0.0"
```

and that `my-package` has the following Python restriction "<3.9".

Now, Poetry will resolve the dependencies but will see that the `my-package` will not be satisfied for Python `>=3.9,<4.0`, hence the error you see. However, you can circumvent that by adding a `python` restriction to the `my-package` dependency, like so:

```toml
my-package = {version = "^1.0.0", python = ">=3.8,<3.9"}
```

Now, the dependencies will be properly resolved.

In the next `1.1.0`, you will even get this suggestion directly from the command line (see https://github.com/python-poetry/poetry/pull/2396):

```text
• Check your dependencies Python requirement: The Python requirement can be specified via the `python` or `markers` properties

  For my-package, a possible solution would be to set the `python` property to ">=3.8,<3.9"

  https://python-poetry.org/docs/dependency-specification/#python-restricted-dependencies,
  https://python-poetry.org/docs/dependency-specification/#using-environment-markers
```

**Comment by atollk** [comment]
Thanks for joining the conversation, @sdispater .

> What you need to understand is why this feature has been implemented.

Which is what I am trying to do. 

> Now, Poetry will resolve the dependencies but will see that the my-package will not be satisfied for Python >=3.9,<4.0, hence the error you see.

Sure, I understand where the error comes from. But, as you said, I am questioning _why_ it exists and whether this behavior is the best it could be.

> `my-package = {version = "^1.0.0", python = ">=3.8,<3.9"}` 

That certainly looks like a better solution than having to restrict the Python version globally just from a syntax pov.
However, if the dependency changes from `^3.8` to `^3.9`, the error becomes hard to find. `poetry update` will finish successfully and only when importing `my-package` will an `ImportError` be raised.

What advantage does this approach offer over having poetry find suitable versions on its own and issuing warnings to the user?

**Comment by atollk** [comment]
Bumping. @sdispater 

I realize that you seem to have a hard time catching up with the number of issues coming in each day. But considering I have already offered to take care of this issue myself, I am wondering, why you are rejecting it so much without having any clear reason to do so. At this point, it looks to me like you are rejecting the idea just on principle because it wasn't made by a poetry contributor.

**Comment by sdispater** [comment]
@atollk 

> why you are rejecting it so much without having any clear reason to do so

There is a valid reason to do so, which I explained above. Poetry's behavior is the right one in this case because otherwise it would lead to inconsistencies.

> At this point, it looks to me like you are rejecting the idea just on principle because it wasn't made by a poetry contributor.

That's not true and I would have rejected the idea even if it had come from a core contributor. Even if it's one of the most misunderstood feature of Poetry, it's one that has been carefully and purposefully designed.

So, I appreciate the fact that you are willing to take some of your time to work on Poetry however there is nothing to change or fix in this particular case.

**Comment by atollk** [comment]
@sdispater Thanks for your reply.
Sorry, I don't see what inconsistencies you are referring to. Could you elaborate?

Do you mean an inconsistency between the specification within pyproject.toml and the actual requirements of the built package? I understand that those exist, which is why (1.) propose simply to change these error messages to warnings, not too deactivate them at all. I do so because (2.) I assume the majority of users cares more about not being negatively influenced by packages they use than they care about having perfect consistency in that regard. Now, of course, this is just an assumption, which is why (3.) I was asking whether there was data collected on this issue in any way, or how this was determined to be the right choice otherwise.
(4.) What seems most odd to me though, is that, unless my understanding is wrong, package dependencies do allow this inconsistency; when `mypkg` uses `x=^1.1` and `deppkg` and `deppkg` uses `x=^1.2`, then the final package will not support `x==1.1`, so the same inconsistency which I guess you are referring to is introduced.
