### ISSUE TITLE
Add command line option to display only the system Python path.

### ISSUE THREAD

**Issue by MiMiMeowMeow** [python-poetry/poetry#2702]
- [X ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ X] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request
Similar to the "poetry env info -p" command to only display the enivroment's full path.  Is there a way to just print out the System Python path?  I see that when you do a "poetry env info", that the System Python path is known, I would just like to use that information without parsing it out.

Thanks in Advance!

**Comment by finswimmer** [comment]
Hey,

IMO this is a bit out of scope for Poetry. You can get the path to the system python via `which python` or `where python` on windows (replace `python` by whatever your system python is called),

fin swimmer
