### ISSUE TITLE
Poetry does not gracefully error when trying to install malformed packages

### ISSUE THREAD

**Issue by demus** [python-poetry/poetry#2704]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

1. add a file to pyproject.toml, from local source:

```package = {path = "package"}```

2.
```
mkdir package
touch package/setup.py
```

3. 

```poetry install```

and you'll receive a stack trace with a StopIteration error.

I understand this is user error and also a really weird edge case, but it's something I ran into and thought that it might be worth reporting as an improvement.

**Comment by dimbleby** [comment]
behaviour today is:
```
Unable to determine package info for path: /home/dimbleby/poetry-test/package

Exhausted all core metadata sources.
```

which if not crystal clear is an improvement on a stack trace
