### ISSUE TITLE
The poetry build command forces the pre-release identifer to 'rc'

### ISSUE THREAD

**Issue by ginty** [python-poetry/poetry#2705]
- [x ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

## Issue

My project version is something like `2.0.0-pre1` and I want to build a wheel with that version, however in doing so the pre-release identifier gets converted from `-pre` to `rc`:

~~~
stephen@falcon:~/Code/github/o2/python$ poetry build
Building origen (2.0.0-pre1)
 - Building sdist
 - Built origen-2.0.0rc1.tar.gz
~~~

**Comment by tomzx** [comment]
According to the logic in https://github.com/python-poetry/poetry-core/blob/master/poetry/core/version/version.py#L160-L161, `pre`/`preview` gets mapped to `rc`. According to the surrounding comments, it appears that there was a need to standardize names.

Could you give more context as to why the naming standardization might be an issue for you?

**Comment by ginty** [comment]
Thanks for the reply, here are the reasons why I don't want to use 'rc':

Firstly, there is a semantic distinction between a pre-release and a release-candidate and when doing the former I don't want it forced to be identified as the latter.

Secondly, the project I encountered this on is comprised of multiple packages across different languages all built via various flows - even in Python I have a package built by Poetry and another package built by another flow. All other flows except for Poetry agree that -preX is a perfectly valid pre-release identifier.

Thirdly PyPi has no issue with a -preX identifier, nor do other build tools. I'm working around this by modifying the wheel built by Poetry, but that's pretty unsatisfying.

**Comment by ginty** [comment]
On reflection, I think we can close this.
My complaint is really with Python and why it decided to implement its own version rules rather than following semver like everyone else (maybe it preceded it, I don't know), but in any case given the existence of PEP440 I agree with Poetry's stance on enforcing it.
