### ISSUE TITLE
The new `--no-modify-path` argument to `get-poetry.py` is misleading

### ISSUE THREAD

**Issue by birnbera** [python-poetry/poetry#2707]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Centos7
- **Poetry version**: 1.0.10
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue

The **_very recent_** update to the `get-poetry.py` script (was just merged into `master` from `develop`) includes a command line argument `--no-modify-path` to allow users to configure whether to modify their shell startup scripts by prepending `POETRY_HOME/bin` to the `PATH` variable. While this is a great addition, it unfortunately only has any effect when used in conjunction with the `--yes` command line argument, which is supposed to indicate that the user wishes to answer any input prompts in the affirmative. As it happens, the only input prompt in the script is regarding whether to modify the user's `PATH`. Thus, you weirdly have to agree to modify your `PATH` in order to also opt out of that behavior.

The offending lines are [here](https://github.com/python-poetry/poetry/blob/02d4d0c4fff8270c01fde399a7fb6ad1ad51f56c/get-poetry.py#L479-L485). Essentially, unless `self._accept_all` is `True`, the block asking about `PATH` modification still gets executed and replaces the value of `self._modify_path` with the input from the user.

**Comment by louwers** [comment]
This is indeed annoying and misleading.

**Comment by finswimmer** [comment]
Hello,

`get-poetry.py` is now deprecated and will be replaced by `install-poetry.py`. This script will not modify the PATH variable at all.

See: https://python-poetry.org/blog/announcing-poetry-1.2.0a1/#deprecation-of-the-get-poetrypy-script

fin swimmer
