### ISSUE TITLE
Error import: not found on Windows 10 WSL2 - Ubuntu 20.04

### ISSUE THREAD

**Issue by ThePresence** [python-poetry/poetry#2708]
- **OS version and name**: Ubuntu 20.04 on Windows 10 WSL2
- **Poetry version**: 1.0.9
---

## Issue -

Whenever I try to use poetry I'm getting below error message -
```
poetry shell
/mnt/c/Users/viren/.poetry/bin/poetry: 2: import: not found
/mnt/c/Users/viren/.poetry/bin/poetry: 3: import: not found
/mnt/c/Users/viren/.poetry/bin/poetry: 4: import: not found
: not founds/viren/.poetry/bin/poetry: 5: 
/mnt/c/Users/viren/.poetry/bin/poetry: 6: Syntax error: "(" unexpected
```
I'm only getting this error on Ubuntu wsl2, but on Windows 10 it's working flawlessly.

Please find the screenshot below -

![image](https://user-images.githubusercontent.com/19200271/88373388-6118a080-cdb5-11ea-9a11-eaadc57dec93.png)

**Comment by abn** [comment]
@ThePresence can you post the output of the `cat $(which poetry)`?

**Comment by ThePresence** [comment]
Please find below -

```
$ cat $(which poetry)
# -*- coding: utf-8 -*-
import glob
import sys
import os

lib = os.path.normpath(os.path.join(os.path.realpath(__file__), "../..", "lib"))
vendors = os.path.join(lib, "poetry", "_vendor")
current_vendors = os.path.join(
    vendors, "py{}".format(".".join(str(v) for v in sys.version_info[:2]))
)
sys.path.insert(0, lib)
sys.path.insert(0, current_vendors)

if __name__ == "__main__":
    from poetry.console import main

    main()
```

**Comment by ShoorDay** [comment]
@abn I have a similar problem on Windows 10 WSL2 - Ubuntu.
```bash
➜  ~ poetry --version
/usr/bin/env: ‘python\r’: No such file or directory
➜  ~ which poetry
/mnt/c/Users/surez/.poetry/bin/poetry
```
As shown above, `poetry`  point to the One installed on Windows. And poetry works well on Windows.

**Comment by ShoorDay** [comment]
I reinstall it again and it works now. But I don't know what happened. 😭

**Comment by ThePresence** [comment]
> I see what the problem is. The install script didn't modify the `$HOME/.zprofile` (It didn't exist before).
> ```bash
> ➜  ~ which poetry
> /home/sure/.poetry/bin/poetry
> ```

Did you find any solution?

**Comment by ShoorDay** [comment]
@ThePresence Just add `Poetry` to Path in `.zprofile`:
```zsh
export PATH="$HOME/.poetry/bin:$PATH"
```

**Comment by ThePresence** [comment]
> 
> 
> @ThePresence Just add `poetry` to PATH in `.zprofile`:
> 
> ```shell
> export PATH="$HOME/.poetry/bin:$PATH"
> ```

@ShoorDay 
Thank you so much it worked.
