### ISSUE TITLE
Restore working version of poetry.lock after SolverProblemError

### ISSUE THREAD

**Issue by dazza-codes** [python-poetry/poetry#2723]
The `poetry.lock` file that was previously working before trying to install/update packages should be restored after encountering a `SolverProblemError`.

```
$ poetry add pyyaml@^5.2.0

Updating dependencies
Resolving dependencies... (4.7s)

Writing lock file

[SolverProblemError]
reason for error etc etc
```

This leaves the `poetry.lock` in a broken state and subsequent `poetry update` processes seem to try to resolve a nearly impossible conflict to resolve, taking too long to identify that the `poetry.lock` file is broken already.

The proposed request is to cache a working `poetry.lock` state and to restore it on failure (i.e. some form of transaction rollback).

```
```
$ poetry add pyyaml@^5.2.0

Updating dependencies
Resolving dependencies... (4.7s)

Writing lock file

[SolverProblemError]
reason for error etc etc

rollback in progress...
- restore poetry.lock
- restore venv packages
```

**Comment by finswimmer** [comment]
This should be solved in the meantime.
