### ISSUE TITLE
1.1a3/b2 does not detect installed packages as git

### ISSUE THREAD

**Issue by wakemaster39** [python-poetry/poetry#2730]
- [ x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [ x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: MacOs 10.15
- **Poetry version**: 1.1a3/b2

## Issue
This issues was found trying to validate the change set presented in #2327.  In 1.0.9 where the PR was inititated, the 

https://github.com/python-poetry/poetry/blob/4769f72a052743691a5c073777aaf07f72f94e74/poetry/puzzle/solver.py#L87 `pkg.source_type` value was git, in the current master and develop, the pkg.source is returning None.

Back tracking this issue, lead me to the InstalledRepository load method, https://github.com/python-poetry/poetry/blob/4769f72a052743691a5c073777aaf07f72f94e74/poetry/repositories/installed_repository.py#L55-L57

I have a test test up where my only dependency is a test git repo, I added the following to try and diagnose the problem. 

```python
        for entry in reversed(env.sys_path):
            print(entry, list(metadata.distributions(path=[entry])))
            for distribution in sorted(
                metadata.distributions(path=[entry]), key=lambda d: str(d._path),
            ):
```

The output is:

```
/Users/cahurst/code/test2/.venv/src/test-abc/src []
/Users/cahurst/code/test2/.venv/lib/python3.8/site-packages [<importlib.metadata.PathDistribution object at 0x109a84af0>, <importlib.metadata.PathDistribution object at 0x109a84a90>, <importlib.metadata.PathDistribution object at 0x109a84c70>, <importlib.metadata.PathDistribution object at 0x109a84dc0>, <importlib.metadata.PathDistribution object at 0x109a84c40>]
/Users/cahurst/.pyenv/versions/3.8.0/lib/python3.8/lib-dynload []
/Users/cahurst/.pyenv/versions/3.8.0/lib/python3.8 []
/Users/cahurst/.pyenv/versions/3.8.0/lib/python38.zip []
 []
```

My test repo is not returning any metadata distributions and during the next loop, the `dist-info` file is being detected and the package is being treated as a standard package and things try and get updated based on that.

Forcibly adding the following if condition to see if they is the root cause resolves the issue and `pkg.source_type` is being properly populated.

```python
            for distribution in sorted(
                metadata.distributions(path=[entry]), key=lambda d: str(d._path),
            ):
                name = distribution.metadata["name"]
                path = Path(str(distribution._path))
                if name == "test-abc":
                    path = Path("/Users/cahurst/code/test2/.venv/src/test-abc/src")
```

Unfortunately, `metadata.distributions` is out of my knowledge base and I am unsure what should be changed here  as I looked to try and see if something further in the chain might be wrong as well but this following gate fails unless that first entry is passed in and set.

https://github.com/python-poetry/poetry/blob/4769f72a052743691a5c073777aaf07f72f94e74/poetry/repositories/installed_repository.py#L100-L105

**Comment by abn** [comment]
@wakemaster39 can you try the fix in #2722, I think that should resolve this issue.

**Comment by wakemaster39** [comment]
@abn no, this isn't resolving the problem. I think it definitely could but there is one problem I am not sure how to best resolve.

My test library is named `test-abc`, and the `.pth` file that is being installed is called `test_abc.pth`

`-` is not a valid character in python packages so my source folder contains `test_abc` as its root folder. Now I am not sure if the process is installed based on this name or if the package name is purely getting a replace done on it. 

Adjusting line 40 to be `pth_file = lib_path.joinpath(name.replace("-", "_")).with_suffix(".pth")` fixed the issue for me but I am not sure if this is the right way to do it.

**Comment by abn** [comment]
@wakemaster39 i have pushed a new fix to that branch

**Comment by wakemaster39** [comment]
@abn looks good now :)
