### ISSUE TITLE
Tilde operator (`~=`) in dependencies fails silently in 1.1.0b2

### ISSUE THREAD

**Issue by ewjoachim** [python-poetry/poetry#2737]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version. (unstable)
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: N/A
- **Poetry version**: 1.1.0b2 (and not in stable)
- **pyproject.toml**:
```
[tool.poetry]
name = "foo"
version = "0.1.0"
description = ""
authors = ["Joachim Jablon"]

[tool.poetry.dependencies]
python = "^3.6"
ewjoachim-poetry-bug-2020-07-28 = "0.0.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0a5"]
build-backend = "poetry.core.masonry.api"
```

## Issue
The package `ewjoachim-poetry-bug-2020-07-28` consists of a single line:
```python
setup(name="ewjoachim-poetry-bug-2020-07-28", install_requires=["requests~=2.24.0"])
```

When launching `poetry debug resolve -vvv` I expect to find `requests`, yet: 
```
poetry debug resolve -vvv                    
Resolving dependencies...
   1: fact: foo is 0.1.0
   1: derived: foo
   1: fact: foo depends on ewjoachim-poetry-bug-2020-07-28 (0.0.0)
   1: selecting foo (0.1.0)
   1: derived: ewjoachim-poetry-bug-2020-07-28 (0.0.0)
PyPI: 1 packages found for ewjoachim-poetry-bug-2020-07-28 0.0.0
   1: selecting ewjoachim-poetry-bug-2020-07-28 (0.0.0)
   1: Version solving took 0.010 seconds.
   1: Tried 1 solutions.

Resolution results:

ewjoachim-poetry-bug-2020-07-28 0.0.0
```

As seen with @sdispater, this is because `~=` operator is missing from the `LEGACY_VERSION_CONSTRAINT` in
https://github.com/python-poetry/poetry-core/blob/2409e6d980d310791d4ee23ef40623c0cfa884b4/poetry/core/version/grammars/pep508.lark#L17

There are 2 issues:
- The missing operator
- The fact that it fails silently and completely ignores the dependency instead of crashing loudly.

**Comment by abn** [comment]
@ewjoachim I have raised #2738 to handle the "silent failure" issue.

**Comment by ewjoachim** [comment]
Ok, we can close this one then :)
