### ISSUE TITLE
Improve how internal errors are propagated to users and when debugging issues

### ISSUE THREAD

**Issue by abn** [python-poetry/poetry#2738]
As things stand today, the internal errors that happen when issues like #2737 #2734 are encountered are lost to the logger.

https://github.com/python-poetry/poetry/blob/cae154c26485e3177f994f828b73d342aec12810/poetry/inspection/info.py#L153-L160

This needs to be improved such that we use an application level logger with an option to generate debug logs if/when required without interfering with the CLI UX.

**Comment by ewjoachim** [comment]
(perfect :+1: thank you)

**Comment by abn** [comment]
@sdispater Is there some processing missing here?
```console
PyPI: No release information found for django-1.1.2, skipping
PyPI: 1 packages found for django >=3.0.8,<4.0.0
<debug>PackageInfo:</debug> Invalid constraint (asgiref (~=3.2)) found in django-3.0.8 dependencies, skipping
   1: fact: django (3.0.8) depends on pytz (*)
   1: fact: django (3.0.8) depends on sqlparse (>=0.2.2)
```

I was expecting `<debug>` to be rendered correctly.

**Comment by sdispater** [comment]
@abn It's rendered correctly on my end:

<img width="694" alt="Screenshot 2020-07-28 at 17 00 33" src="https://user-images.githubusercontent.com/555648/88683319-ef618f00-d0f3-11ea-9913-0d17b851007f.png">

**Comment by abn** [comment]
> @abn It's rendered correctly on my end:
> 

Strange. Not sure why that single debug won't render as expected on mine. Will debug later then.
