### ISSUE TITLE
Poetry does not work with tomlkit 0.6.0

### ISSUE THREAD

**Issue by tlc28** [python-poetry/poetry#2752]
Hi Poetry!

Poetry 1.0.10 is unfortunately broken on Guix (https://guix.gnu.org) since I upgraded tomlkit to version 0.6.0!
The version required by Poetry is "^0.5.11", which translates to ">=0.5.11,<0.6.0". We only have one version of tomlkit packaged, and it's the latest one, 0.6.0.

From what I understand reading SemVer (https://semver.org), minor versions should only "add functionality in a backwards compatible manner", and so the API should be stable. So 0.6.0 should work with Poetry. And, as a matter of fact, when I force it (by modifying the requirements), Poetry seems to be working as expected.

I have 3 options:
- modify the requirements at build time (quick fix);
- package tomlkit version "0.5" alongside the "latest" version (long term solution);
- report the problem upstream to see if there's a cleaner solution.

For the time being, I'll implement solution 1. I'll implement solution 2 if you don't see it as a problem that should be fixed upstream.

WDYT?

**Comment by tlc28** [comment]
Thanks @abn!
Actually, we have the same problem with cleo and clikit… but the versions have been updated in dev. So we'll have to live with a patch until 1.1.0 is out and can be packaged.

**Comment by abn** [comment]
@tlc28 just so you know, 1.1.0 will require `tomlkit-0.7.0` see comments on #2753. I suspect so will cleo and clikit.

**Comment by tlc28** [comment]
Thanks @abn
