### ISSUE TITLE
Comment in pyproject.toml breaks new lines

### ISSUE THREAD

**Issue by jaklan** [python-poetry/poetry#2755]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS Mojave 10.14.6
- **Poetry version**: 1.1.0b2

## Issue
We have a cookiecutter template for poetry-based projects. Initial `pyproject.toml` looks this way:
```
[tool.poetry.dependencies]
python = "^3.8"
# template packages (don't remove them!)
black = "^19.10b0"
(...)
# project packages

[tool.poetry.dev-dependencies]
```
After *project packages* comment there's an empty area. And now, when you try to add a package, e.g. `poetry add pandas`, that's the effect:
```
[tool.poetry.dependencies]
python = "^3.8"
# template packages (don't remove them!)
black = "^19.10b0"
(...)
# project packages

pandas = "^1.1.0"
[tool.poetry.dev-dependencies]
```
so as you can see - there's some small error with handling new lines (new line should be after the new package, not before).

**Comment by tomzx** [comment]
In https://github.com/python-poetry/poetry-core/blob/master/poetry/core/_vendor/tomlkit/container.py#L177

Replace 
```
if key_after + 1 < len(self._body) - 1
```
with
```
if key_after + 1 <= len(self._body) - 1
```
or
```
if key_after + 1 < len(self._body)
```
will append the package right after the comment and put an empty line between the package and the `[tool.poetry.dev-dependencies]` section. Given there doesn't seem to be any test for the `tomlkit` implementation, I don't know how safe such change is. All the tests in the `test_add` file appear to pass however.

**Comment by finswimmer** [comment]
Hey,

if this is issue is still relevant it's more an issue of `tomlkit`. Please report it there if necessary: https://github.com/sdispater/tomlkit

fin swimmer
