### ISSUE TITLE
Poetry says that "environment seems to be broken" all the time

### ISSUE THREAD

**Issue by keddad** [python-poetry/poetry#2756]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Fedora 32
- **Poetry version**: 1.0.10
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: [Link](https://gist.github.com/keddad/3d34e7a03ee1e87b12518599962f4651)
- I've also done `poetry config virtualenvs.path .venv`

## Issue

Apparently, poetry invalidates virtual environment even if literally nothing happened to it. Here is an example where I install a package and and try to list packages, but it says that environment is broken and installs it again: [Gist](https://gist.github.com/keddad/d46026eeeb8142687b4ebfd22ca70c0d). My only idea is that PyCharm, which is configured to use the venv, messes something up but it shouldn't write anything in venv, I guess.

**Comment by finswimmer** [comment]
@keddad I encountered this problem, when the venv is activated and poetry detect it as broken and than try to recreate it. So make sure your venv is deactivated and run `poetry install` once again. Afterwards everything should work normal.

**Comment by keddad** [comment]
Sadly, that didn't really work in my case. I'm clearly not running any venvs:
```
[keddad@localhost socialcomp]$ which python
/usr/bin/python
```

but `poetry install && poetry show` still results in "broken environment" issues.

**Comment by keddad** [comment]
Ok, that's clearly an issue with how `VirtualEnv.is_sane()` works. It simply checks if there are python and pip present:
```
def is_sane(self): # 
        # A virtualenv is considered sane if both "python" and "pip" exist.
        return os.path.exists(self._bin("python")) and os.path.exists(self._bin("pip"))
```
[
github.com/python-poetry/poetry/blob/master/poetry/utils/env.py#L1168](
github.com/python-poetry/poetry/blob/master/poetry/utils/env.py#L1168)

Since after `poetry install` my venv contains there files, it is probably looking for them in the wrong spot.

**Comment by keddad** [comment]
I've recorded a [trace](https://gist.github.com/keddad/2e22d67bd7763929f2a04b15d3188b4c) of `poetry show` running in "broken env". I'm not really sure why is that happening, but here is a thing:
* It removes my venv `22146 rmdir(".venv/socialcomp-nXpxZNnR-py3.8") = 0`
* And only then checks if `pip` binary exists `22149 stat("/home/keddad/Documents/hseproject/socialcomp/.venv/socialcomp-nXpxZNnR-py3.8/bin/pip", 0x7ffe35267450) = -1 ENOENT (Нет такого файла или каталога)`

But I'm still not sure on why is this happening

**Comment by taranlu-houzz** [comment]
I think I am also running into the same issue.

I have a local `poetry.toml`:
```toml
[virtualenvs]
path = ".venv"
```
And `virtualenvs.in-project` is set to `false` globally.

**Comment by finswimmer** [comment]
Ah, now I see what's going on. At the moment you cannot point `virtualenvs.path` to `.venv` as this is some kind of reserved location for poetry. Whenever it finds a `.venv` folder within the project it asumes that this is the folder with the venv. But this is not the case here with this setting, because it just defines the root folder in which the  folders for the venvs will be placed.

Related: https://github.com/python-poetry/poetry/issues/1770

fin swimmer

**Comment by HuM4NoiD** [comment]
I am still facing this issue, every time I use any poetry command in the project directory

poetry config: 
```
cache-dir = "C:\\Users\\jugal.mistry\\AppData\\Local\\pypoetry\\Cache"
experimental.new-installer = true
installer.parallel = true
virtualenvs.create = true
virtualenvs.in-project = true
virtualenvs.path = "{cache-dir}\\virtualenvs"  # C:\Users\jugal.mistry\AppData\Local\pypoetry\Cache\virtualenvs
```

This creates a `.venv` in any new poetry project

On further inspection I found out that pip executable/script was not present in `.venv/Scripts/`

**Comment by neersighted** [comment]
This is a really old issue and if you're currently experiencing this, I suggest you open a new issue with a reproduction. Make sure that you do not have an existing venv active (especially a deleted or partially broken one) before you run Poetry commands if you want `virtualenvs.in-project` to be respected and for Poetry to choose the in-project env (as an activate env will always override the Poetry env, unless it is invalid).

`poetry env info` is also your friend when it comes to debugging this.

**Comment by Photon1c** [comment]
This went away for me when I deactivated my environment and just let poetry create it itself through the automated installation process.
