### ISSUE TITLE
how to install it on google colab?

### ISSUE THREAD

**Issue by shangguan91** [python-poetry/poetry#2762]
name 'poetry' is not defined after i installed, and run poetry --version

**Comment by abn** [comment]
@shangguan91 you could install it like shown below. Note that I am using `--pre` here, this is because the default python version does not come with `ensurepip` and the `1.1.x` releases of peotry will be using `virtualenv` which handles this scenario.

```
!pip install -q --pre poetry
!poetry --version
```
