### ISSUE TITLE
Poetry refuses to install isort > 5.

### ISSUE THREAD

**Issue by sfermigier** [python-poetry/poetry#2764]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: MacOS X 10.13.6 or Ubuntu 18.04
- **Poetry version**: 1.0.10
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: <https://gist.github.com/sfermigier/91fcfa81c0b7dcde50c14070855372a4>

## Issue

The project won't install, complaining that "isort requires Python >=3.6,<4.0", even when we are using Python 3.7 or Python 3.6.

**Comment by finswimmer** [comment]
Hello @sfermigier,

you've defined that your project is compatible to python>=3.7. So there is no upper boundary. But isort has one. Change 

```
[tool.poetry.dependencies]
python = ">=3.7"
```

to

```
[tool.poetry.dependencies]
python = "^3.7"
```

Please see also my comment in https://github.com/python-poetry/poetry/issues/1930#issuecomment-653906544

fin swimmer
