### ISSUE TITLE
Poetry should validate that the canonicalized name for packages is consistent.

### ISSUE THREAD

**Issue by bennycooly** [python-poetry/poetry#2770]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: MacOS Catalina
- **Poetry version**: 1.0.10
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**:

## Issue

For privately hosted repositories such as a private Artifactory repo, it is possible for the repository URL for a package to contain artifacts other than the package itself. For example, for the `requests` package. `<REPO_URL>/artifactory/api/pypi/internal-repo/simple/requests/` should only contain distributions where the canonicalized name is `requests`. However, it is possible that since the repo is just a simple HTTP server, the URL can contain a random distribution such as `RANDOM_NAME_HERE-3.0.0`. Since Poetry doesn't check that all distributions in the URL have the correct canonicalized name, it thinks that the latest version for `requests` should be `3.0.0`, which is obviously incorrect. Pip will then return an error during installation:
```
ERROR: Could not find a version that satisfies the requirement requests=RANDOM_NAME_HERE-3.0.0
```

Searching the exact same Repository using `pip search` shows the valid versions, so it seems that Poetry is considering versions that correspond to invalid distributions since Pip can't find them.

Now, I know that the misplaced distributions shouldn't be there in the first place, but this could happen for a variety of reasons out of my control since Artifactory allows it. If Poetry just does a simple check when resolving dependencies to ensure that the canonicalized name is indeed the package we're looking for, then that would resolve this issue. I think this should be a simple validation check and would be happy to submit a PR but wanted some feedback from the Poetry team first.

**Comment by ralbertazzi** [comment]
Hello, it looks like this has been fixed in some Poetry version. In fact I [added a test for it](https://github.com/python-poetry/poetry/pull/7980) and it's passing. Let me know if the edge case in the test is the one you were expecting. If that's it then we'll close the issue when the PR is merged.
