### ISSUE TITLE
Installing `scrapy`: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by dmiwell** [python-poetry/poetry#2772]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Linux Mint 20
- **Poetry version**: 1.0.10
- **Link of a [Gist](https://gist.github.com/dmiwell/8cd15375642fdbf3215bf93430bebbf3) with the contents of your pyproject.toml file**: https://gist.github.com/dmiwell/8cd15375642fdbf3215bf93430bebbf3

## Issue

I'm trying to install scrapy, but getting:
```
[RecursionError]
maximum recursion depth exceeded while calling a Python object
```

With `-vvv` I see:
```
0: Duplicate dependencies for lxml
0: Different requirements found for lxml (>=3.5.0) and lxml (>=4.0.0).
```

It seems it happens because of latest [setup.py](https://github.com/scrapy/scrapy/blob/1278e76d9093b1c5c9ec810768d1066772a8a134/setup.py#L39)

**Comment by finswimmer** [comment]
Hello @dmiwell,

could you try it with the latest preview release of poetry? With this I'm not able to reproduce your problem.

fin swimmer

**Comment by dmiwell** [comment]
Hi @finswimmer 

Thanks for the quick response. I can confirm that it works fine with `Poetry version 1.1.0b2`
