### ISSUE TITLE
Poetry unnecessarily creates a tty

### ISSUE THREAD

**Issue by himat** [python-poetry/poetry#2774]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Mac OS Mojave 10.14.5
- **Poetry version**: 1.0.5

## Issue

When I run poetry shell, why does that create another sub-tty. Using a regular virtualenv doesn't create a tty

With poetry:
```
> tty
/dev/ttys004 # original shell

> poetry shell
Spawning shell within /Users/x/x/.venv

> . /Users/x/.venv/bin/activate

> tty
/dev/ttys017 # shell with poetry activated
```

With virtualenv
```
> tty
/dev/ttys004 # original shell

> source ./venv/bin/activate

> tty
/dev/ttys004 # shell with venv activated
```

This is presenting an issue to me when I use tmux since I have some commands in tmux that run based on checking what programs are running in the current tty. But those are now failing because tmux returns the original tty 004 of the shell I'm in and doesn't see that poetry has created a new tty in which I have other programs running.

**Comment by finswimmer** [comment]
Hello @himat,rHehttps://github.com/python-poetry/poetry/issues/2792#issuecomment-672730038llo 

please see @abn's comment here https://github.com/python-poetry/poetry/issues/2792#issuecomment-672730038 for the answer.

fin swimme

**Comment by romkatv** [comment]
I know it's an old issue but I'm also wondering why poetry creates a TTY. The linked comment explains why it creates a subshell but not the TTY. Here's what I mean.

Suppose my shell is `zsh`. If I run `zsh`, I'll create a subshell -- a new process. However, this subshell will be connected to the same TTY. We can see this by running `ps -o tty -p $$` in the top-level shell and then again in the subshell. However, when using `poetry shell`, the subshell will be attached to a different TTY. The question is why that TTY is needed.
