### ISSUE TITLE
Tensorflow-gpu does not recognize my NVIDIA GPU when using Poetry

### ISSUE THREAD

**Issue by igormcsouza** [python-poetry/poetry#2779]
- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

- **Ubuntu 20.04**:
- **Poetry 1.0.0**:

## Issue
Hello! Firstly Nice work of yours! 

Well, I'm getting this issue and, for some reason, I couldn't find anything related in my previous research. 

I was building a package for my classification task using tensorflow-gpu and it was working just fine. I'm using tensorflow-gpu on version 2.2.0 and my CUDA version is 10.1, all fine to work with this kind of task and requirements. 

Well, for some personal reasons I decide to use poetry to deal with versioning, but just after all the dependencies were installed with poetry tensorflow-gpu stop to recognize my GPU. Even though its all installed and working fine. 

Commnad:
```
tf.config.experimental.list_physical_devices('GPU')
```

Result:
```
2020-08-07 22:49:36.619079: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2020-08-07 22:49:36.619139: E tensorflow/stream_executor/cuda/cuda_driver.cc:313] failed call to cuInit: UNKNOWN ERROR (303)
2020-08-07 22:49:36.619165: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: lead-XPS-8930
2020-08-07 22:49:36.619500: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: lead-XPS-8930
2020-08-07 22:49:36.619548: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: Not found: was unable to find libcuda.so DSO loaded into this program
2020-08-07 22:49:36.619716: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 435.21.0
```

Anything outside poetry environment runs the command above just fine!

Have no IDEA whats happening. If you guys could give me a hint on how to solve this I'd be greatful! 👍

**Comment by tomzx** [comment]
Not likely to be related to `poetry` itself but rather that it cannot find the CUDA library (`libcuda.so.1`) on the machine you're running the code on. See https://stackoverflow.com/questions/41890549/tensorflow-cannot-open-libcuda-so-1.

**Comment by abn** [comment]
@igormcsouza I am afraid the issue is as indicated by @tomzx. 

This might be related to the use of a virtual environment. Any chance you can try reproduce this without poetry by following the below steps?

1. Create new virtual environment. Either `python -m venv venv-test` (if using python 3) or `virtualenv venv-test` (if you have `virtualenv` installed).
2. Activate environment `source venv-test/bin/activate`.
3. Install `tensorflow-gpu` using pip.
4. Try reproducing the issue now.

**Comment by igormcsouza** [comment]
Thanks for you guys answers! Well, I've been using Docker to isolate my project, and there no issue happens!

But I'm going to try using a python virtual environment on my machine and I'll update here the results

**Comment by igormcsouza** [comment]
Hello dear friends! I actually run the python virtualenv and the same error happened! So I conclude the issue is related to enviroment rather than poetry itself. Just to give an answer... I used poetry in a tensorflow image (docker), outside an enviroment as poetry let it happens, and it worked! Thanks for helping!

**Comment by joooeey** [comment]
See also: my similar issue on the `tensorflow` issue tracker: https://github.com/tensorflow/tensorflow/issues/48939

**Comment by igormcsouza** [comment]
Thanks for the advice!
