### ISSUE TITLE
poetry add breaks existing [build-system]

### ISSUE THREAD

**Issue by ycd** [python-poetry/poetry#2782]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04

- **Poetry version**: Poetry version 1.0.10
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/ycd/2311f6e9a48cb7e1e8811c87247dc3a6

## Issue

When adding a new dependency with `poetry add example[extra1, extra2]` it tries to override existing [build-system] and breaks it.

```
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```

![poetry](https://user-images.githubusercontent.com/62724709/89717048-4fd9b180-d9bb-11ea-8103-fcfd5ec54bb2.gif)
Also streamable link: https://streamable.com/xwvej8

**Comment by abn** [comment]
@ycd this should be resolved in the latest pre-release. Can you give that a try please?

**Comment by ycd** [comment]
Hello @abn i installed the latest pre release **1.1.0b2**.

```shell
poetry --version
Poetry version 1.1.0b2
```
I can confirm that the issue is resolved. Huge thanks! But another thing to mention `poetry add databases[postgresql,sqlite]` is working, but when you add a space inside square brackets like `poetry add databases[postgresql, sqlite]` 

```shell
poetry add databases[postgresql, sqlite]
```

It throws the following error.

```
  ValueError

  Could not find a matching version of package databases[postgresql,

  at ~/.poetry/lib/poetry/console/commands/init.py:343 in _find_best_version_for_package
      339│         )
      340│ 
      341│         if not package:
      342│             # TODO: find similar
    → 343│             raise ValueError(
      344│                 "Could not find a matching version of package {}".format(name)
      345│             )
      346│ 
      347│         return package.pretty_name, selector.find_recommended_require_version(package)
```

https://github.com/python-poetry/poetry/blob/fa87f7be55abd45520283ff7844feb3052f78e8e/poetry/console/commands/init.py#L331-L347

**Comment by abn** [comment]
@ycd looks like that is a shell issue, maybe try adding quotes around `databases[postgresql, sqlite]`.

**Comment by ycd** [comment]
I tried adding quotes around, here is what i tried

- **`poetry add "databases[postgresql, sqlite]"`**
```
 ParseConstraintError

  Could not parse version constraint: sqlite]

  at ~/.poetry/lib/poetry/_vendor/py3.8/poetry/core/semver/__init__.py:163 in parse_single_constraint
      159│             return VersionUnion(VersionRange(max=version), VersionRange(min=version))
      160│         else:
      161│             return version
      162│ 
    → 163│     raise ParseConstraintError(
      164│         "Could not parse version constraint: {}".format(constraint)
      165│     )
      166│ 
```


- **`poetry add databases["postgresql", "sqlite"]`**
```
  ValueError

  Could not find a matching version of package databases[postgresql,

  at ~/.poetry/lib/poetry/console/commands/init.py:343 in _find_best_version_for_package
      339│         )
      340│ 
      341│         if not package:
      342│             # TODO: find similar
    → 343│             raise ValueError(
      344│                 "Could not find a matching version of package {}".format(name)
      345│             )
      346│ 
      347│         return package.pretty_name, selector.find_recommended_require_version(package)
```

- **`poetry add databases["postgresql, sqlite"]`**
```
  ParseConstraintError

  Could not parse version constraint: sqlite]

  at ~/.poetry/lib/poetry/_vendor/py3.8/poetry/core/semver/__init__.py:163 in parse_single_constraint
      159│             return VersionUnion(VersionRange(max=version), VersionRange(min=version))
      160│         else:
      161│             return version
      162│ 
    → 163│     raise ParseConstraintError(
      164│         "Could not parse version constraint: {}".format(constraint)
      165│     )
      166│ 
```

- **`poetry add databases"[postgresql, sqlite]"`**

```
  ValueError

  Could not find a matching version of package databases[postgresql,

  at ~/.poetry/lib/poetry/console/commands/init.py:343 in _find_best_version_for_package
      339│         )
      340│ 
      341│         if not package:
      342│             # TODO: find similar
    → 343│             raise ValueError(
      344│                 "Could not find a matching version of package {}".format(name)
      345│             )
      346│ 
      347│         return package.pretty_name, selector.find_recommended_require_version(package)
```

**Comment by abn** [comment]
Had a quick look, it's a bug in how we parse the name. That should really change and be normalised in core.

**Comment by jaklan** [comment]
@abn the biggest issue is resolved, but it's not yet working correctly (I'm using the latest pre-release). That's the end of my `pyproject.toml`:
```toml
[build-system]
requires = ["poetry-core>=1.0.0a5"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
known_first_party = ["{{cookiecutter.project_package}}"]
profile = "black"
```
When I run `poetry add ...` TOML tables are automatically reordered, but there's an empty line missing between tables:
```toml
[tool.isort]
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
known_first_party = ["{{cookiecutter.project_package}}"]
profile = "black"
[build-system]
requires = ["poetry-core>=1.0.0a5"]
build-backend = "poetry.core.masonry.api"
```
To make it work properly, you have to have an additional empty line at the end of the file, but it would be really annoying to especially exclude `pyproject.toml` from `end-of-file-fixer` pre-commit hook to fix this behaviour.
