### ISSUE TITLE
Thank you for this project!

### ISSUE THREAD

**Issue by tony** [python-poetry/poetry#2785]
Dear authors and contributors of poetry,

I thank you very much for this project. I'd like to express my delight with the project

Currently I am using poetry on 2 large team projects, as well a few projects I ported to poetry over the weekend (that includes publishing) [1]:

- https://github.com/cihai/cihai
- https://github.com/cihai/cihai-cli
- https://github.com/cihai/unihan-etl
- https://github.com/cihai/unihan-db

That's not to mention old projects brought back to life: https://github.com/develtech/django-slugify-processor, https://github.com/tony/django-docutils/tree/v0.5.0

What a time savings. Everything from virtualenv, package versioning, building and publishing. And it even does wheels 🏎️ 

I look forward to continued releases and seeing improvements with this project

[1] Please feel free to remove these links if conflicting, I'm not trying to advertise for the sake of themselves, but as a case study of poetry renovating python projects that were stale for a long time :)

Feel free to close! I don't want to take up space on the tracker 😄

**Comment by neersighted** [comment]
Thanks for the kind words/kudos, on behalf of the whole team!
