### ISSUE TITLE
failed to configure private pipy registry on aarch64

### ISSUE THREAD

**Issue by lironmo** [python-poetry/poetry#2786]
Hello,
i am trying to use poetry on jetson nano or TX2 of nvidia, and i am getting the following error:

[ImportError]
/home/edgify/.poetry/lib/poetry/_vendor/py3.7/cryptography/hazmat/bindings/_openssl.abi3.so: cannot open shared object file: No such file or director

i installed cryptography, but still it's seesm that the poetry binary look for _openssl.abi3.so in different location.

can i build it from source  for aarch64? this will resolve my problem?

**Comment by lironmo** [comment]
the file_openssl.abi3.s  exists. and has read permissions

**Comment by abn** [comment]
@lironmo can you try installing either using `pip` or `pipx`? That should avoid the vendoring issue.

**Comment by abn** [comment]
Looks like this is relying on the older distribution mechanism. Since we are now using `install-poetry.py` script and that simply uses `pip` in an isolated environment this issue should be resolved now.
