### ISSUE TITLE
Inconsistency with pip when handling versions with "+" in their name.

### ISSUE THREAD

**Issue by pkubik** [python-poetry/poetry#2791]
- **OS version and name**: Ubuntu 18.04
- **Poetry version**: 1.0.10

Deps:
```
torch = "^1.6"
kornia = "^0.4"
```

## Issue

The default behavior is correct. Even if I remove `torch` dependency it is being installed as a dependency for `kornia`.

Yet for my server machine I need to use a specific manually installed version of torch which is `1.6.0+cu101`. This dependency is already installed on the system and should be reused. `pip install` properly recognize that the existing version `1.6.0+cu101` matches the requirement `^1.6`, but Poetry tries to "upgrade" the package and thus replaces it with a version that does not work in my setup:

```
- Updating torch (1.6.0+cu101 -> 1.6.0)
```

Not that I've added `kornia` library because it depend on torch 1.6. Otherwise I could just remove `torch` from my requirements and move on with my life. Also note that this specific `1.6.0+cu101` version is not available on PyPI, so I can't simply provide this version in my TOML - besides I wouldn't like to hardcore a version that is needed only by some of my environments.

Edit:
Handling this `+something` suffixes is backed by PEP-440
https://www.python.org/dev/peps/pep-0440/#id25

**Comment by abn** [comment]
Relates to #2543

**Comment by pkubik** [comment]
@abn, yes, this is a duplicate to #2543. Sorry, I didn't have the right keywords when I was creating this issue.

**Comment by abn** [comment]
@pkubik not a problem. Appreciate you raising the issue. :)
