### ISSUE TITLE
Virtual Environment Does Not Appear Next to Path in Shell

### ISSUE THREAD

**Issue by adam-grant-hendry** [python-poetry/poetry#2793]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: <Windows 10, Version 1809>
- **Poetry version**: <1.1.0a3>
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue

Moved #2788 to Bug as `activate` scripts within virtual environment folder indicate virtual environment name is supposed to appear next to path in parentheses (as is typical when using, e.g., `virtualenv`). This does not work (at least for Windows Command Prompt).

**Action:**
```
C:\Users\example\Desktop\Project>poetry shell
```

**Expected Result:**
```
Spawning shell within C:\Users\example\AppData\Local\pypoetry\Cache\virtualenvs\project-####-py#.#
Microsoft Windows [Version 10.0.17763.1339]
(c) 2018 Microsoft Corporation. All rights reserved.

(project-####-py#.#) C:\Users\example\Desktop\Project>
```

**Actual Result:**
```
Spawning shell within C:\Users\example\AppData\Local\pypoetry\Cache\virtualenvs\project-####-py#.#
Microsoft Windows [Version 10.0.17763.1339]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\example\Desktop\Project>
```

**Comment by adam-grant-hendry** [comment]
**Update"** Using VSCode, I can set

```
"python.venvPath": "C:\\Users\\example\\AppData\\Local\\pypoetry\\Cache\\virtualenvs"
```

after which the virtualenv is activated upon opening VSCode. I can know use commands `activate` and `deactivate` to show the virtual environment next to the path. However, after deactivating, entering `poetry env info` still gives me virtual environment information.

I'm unsure if the environment has been deactivated or not. How do I know the poetry virtual environment is active or deactive?

**Comment by venaturum** [comment]
+1 on this issue

**Comment by hms5232** [comment]
Poetry version 1.1.7 has same problem on Windows 10 1909 (build 18363.1556).
Any solution or idea?
