### ISSUE TITLE
Default README format to Markdown in "new"?

### ISSUE THREAD

**Issue by taion** [python-poetry/poetry#280]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue
When Markdown support was initially added in https://github.com/sdispater/poetry/issues/15, Warehouse had somewhat questionable Markdown rendering. At this point, however, it appears that those issues have been resolved, and things like syntax highlighting now work.

As such, given the relative popularity of Markdown even for Python projects, it might make more sense for `new` to default to creating a `README.md` rather than a `README.rst`.

**Comment by nanthony007** [comment]
This is a small issue I understand but has there been any resolution or progress on this? I would be open to contributing if needed.

**Comment by chemsaf3** [comment]
any progress on this? seems like most use md due to github so may not know rst much, would make sense to change to md as default

**Comment by Frank5000** [comment]
Looks like there are a few open PRs that seem to work
