### ISSUE TITLE
poetry should have a native namespace (poetry-core conflicts)

### ISSUE THREAD

**Issue by jonringer** [python-poetry/poetry#2800]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: NixOS (unstable)
```
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.7.13, NixOS, 20.09pre237807.0dc87c6e54f (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(jon): `"home-manager, nixpkgs-20.09pre237807.0dc87c6e54f"`
 - channels(root): `"nixos-20.09pre237807.0dc87c6e54f"`
 - nixpkgs: `/home/jon/.nix-defexpr/channels/nixpkgs`
```
- **Poetry version**: 1.0.10
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue

I noticed when using `poetry` and `poetry-core`, that the two packages both contain a `poetry/__init__.py`. For normal package installation, this isn't an issue, but for nixpkgs, this is an issue, as it only allows for one of the packages to be present (python build environments are created by constructing a PYTHONPATH which points to the package directories individually, so only poetry or poetry-core can be imported, but not both)

The package https://github.com/NixOS/nixpkgs/pull/95211 was still able to be packaged because i could "get away with" only using `poetry-core`, but it would have been a problem if both `poetry` and `poetry-core` were needed. 

And future facing, if poetry is going to have additional packages within the poetry namespace, it would be beneficial to have a coherent namespace in which they can co-exist.

**Comment by abn** [comment]
@jonringer we unfortunately cannot move to native namespaces until Python 2.7 support is dropped (`1.2.0`). Until then we need to use [pkgutil-style](https://packaging.python.org/guides/packaging-namespace-packages/#pkgutil-style-namespace-packages). Also, this should not affect `1.0.10` as we do not use `poetry-core` for `1.0.z` releases.

For all poetry managed projects, as long as `poetry-core` build backend is used, that is all you need to build the project using PEP 517.

**Comment by jonringer** [comment]
We can fix it on the `nixpkgs` end, however I noticed that your `__init__.py` does more than just the `pkgutil-style` namespace in 1.0.10:
```
$ cat ./result/lib/python3.8/site-packages/poetry/__init__.py
import os
import sys

from .__version__ import __version__  # noqa


_ROOT = os.path.dirname(os.path.realpath(__file__))
_VENDOR = os.path.join(_ROOT, "_vendor")
_CURRENT_VENDOR = os.path.join(
    _VENDOR, "py{}".format(".".join(str(v) for v in sys.version_info[:2]))
)

# Add vendored dependencies to path.
sys.path.insert(0, _CURRENT_VENDOR)
```

**Comment by jonringer** [comment]
also, the setuptools `find_namespace_packages` allowed you to make compatible python2 and python3 wheels, but I haven't used that in several months.

**Comment by abn** [comment]
The namespace packaging was only introduced in `1.1.z`. Since `1.0.10` does not use `poetry-core` that should not be an issue and the content above is expected.

The [find_namespace_packages()](https://setuptools.readthedocs.io/en/latest/setuptools.html#find-namespace-packages) method is for Python 3.3+, and supported only [PEP 420](https://www.python.org/dev/peps/pep-0420/) implicit namespaces as per documentation.

**Comment by jonringer** [comment]
sounds like this will eventually be remedied in later poetry updates. However, poetry-core will also need to adhere to PEP 420 as well.

Going to close as this seems to be on the roadmap

**Comment by yaitskov** [comment]
@jonringer, is there a combination of versions for poetry and poetry-core working on nix?
I get the collision.
Do you patch one of them to remove init code?

**Comment by yaitskov** [comment]
My workaround is 
```
        poetry = python39-super.poetry.overridePythonAttrs(old: {
          prePatch = ''                                                                                                       
            rm poetry/__init__.py                                                                                             
          '';
        });
```

**Comment by jonringer** [comment]
I created a PR to support native namespaces with nixpkgs, I would have done this a year ago, but didn't want to invalidate any potential assumptions there were in the `__init__.py`
