### ISSUE TITLE
Poetry cannot resolve dependency from Qiskit Aer 0.6.0

### ISSUE THREAD

**Issue by ikkoham** [python-poetry/poetry#2807]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS 10.15.6 
- **Poetry version**: 1.0.10 and prerelease

## How to reproduce?

`poetry add qiskit-aer==0.6.0` to the blank env.

## Issue

`poetry add qiskit-aer==0.5.2` can resolve the dependency and install required packages.
However, from qiskit-aer==0.6.0, the dependency cannot be resolved, so poetry installs only qiskit-aer.

Related issue: https://github.com/Qiskit/qiskit-aer/issues/880

**Comment by ikkoham** [comment]
Caused by https://github.com/Qiskit/qiskit-aer/pull/775/files

**Comment by abn** [comment]
When poetry inspects this package the `sdist` tarball gets downloaded. This is unpacked and inspected. The `PKG-INFO` contains the following.

```
Metadata-Version: 2.1
Name: qiskit-aer
Version: 0.6.1
Summary: Qiskit Aer - High performance simulators for Qiskit
Home-page: https://github.com/Qiskit/qiskit-aer
Author: AER Development Team
Author-email: qiskit@us.ibm.com
License: Apache 2.0
Description: # Qiskit Aer
<-- SNIPPED -->
Keywords: qiskit aer simulator quantum addon backend
Platform: UNKNOWN
Classifier: Environment :: Console
Classifier: License :: OSI Approved :: Apache Software License
Classifier: Intended Audience :: Developers
Classifier: Intended Audience :: Science/Research
Classifier: Operating System :: Microsoft :: Windows
Classifier: Operating System :: MacOS
Classifier: Operating System :: POSIX :: Linux
Classifier: Programming Language :: C++
Classifier: Programming Language :: Python :: 3 :: Only
Classifier: Programming Language :: Python :: 3.5
Classifier: Programming Language :: Python :: 3.6
Classifier: Programming Language :: Python :: 3.7
Classifier: Programming Language :: Python :: 3.8
Classifier: Topic :: Scientific/Engineering
Description-Content-Type: text/markdown
```

Note that this does not contain any requirement specifications (`Requires-Dist: `). This causes poetry to fallback to parsing the `setup.py`. In `qiskit-aer-0.5.2`, this was easily parsed without error. However, `qiskit-aer-0.6.2` contains the following that wil lcause the AST parser used to fail causing no dependencies to be detected.

```py
PACKAGE_NAME = os.getenv('QISKIT_AER_PACKAGE_NAME', 'qiskit-aer')
...
setup(
    name=PACKAGE_NAME,
    ...
)
```
