### ISSUE TITLE
Can't include a folder that is a subfolder of one excluded by gitignore

### ISSUE THREAD

**Issue by multipitch** [python-poetry/poetry#2809]
- **OS version and name**: Arch Linux
- **Poetry version**: 1.0.10

Relevant part of `pyproject.toml`:
```
[tool.poetry]
authors = ["<...>"]
description = "Solution preparation optimization."
exclude = ["examples/*.xlsx", "src/preppy/z_*"]
include = ["docs/_build/latex/*.pdf", "docs/_build/html/", "examples/*.toml"]
name = "preppy"
readme = "README.md"
version = "0.1.18"
```

Relevant lines in `.gitignore`:
```
# Sphinx documentation
docs/_build/
```

With the above configuration, my pdf documentation, `docs/_build/latex/preppy.pdf`, is included, but the `docs/_build/html/` folder is not.
If I change the include to...
```
include = ["docs/_build/latex/*.pdf", "docs/_build/html/*html", "examples/*.toml"]
```
...it does include the various `*.html` files, but this isn't sufficient as there are other artifacts and subfolders in html I also wish to include.

I thought maybe the issue was my syntax, so I tried the following variations, which didn't work either:
```
include = ["docs/_build/latex/*.pdf", "docs/_build/html", "examples/*.toml"]
```
```
include = ["docs/_build/latex/*.pdf", "docs/_build/html/*", "examples/*.toml"]
```

It seems as if there is some issue in including a folder (but not a file or group of files) that is a subfolder of one ignored by .gitignore.

**Comment by multipitch** [comment]
I've created a simple example: [https://github.com/multipitch/poetry-test](url)

Steps to reproduce:
```
$ cd docs
$ make latexpdf
$ make html
$ cd ..
$ poetry build
````

If you look in the both the sdist and the wheel, the html folder is not included.

The same occurs if you build the sdist and wheel separately.

**Comment by finswimmer** [comment]
Hello @multipitch ,

currently `poetry` does not include a folder recursive (while it does for export). You can do it by using this patter: `"docs/_build/html/**/*"`

fin swimmer

**Comment by multipitch** [comment]
Thanks @finswimmer  - I wasn't familiar with the ** glob pattern.
That's working for my use case.

Do you want to leave this open due to your comment below? ...

> currently poetry does not include a folder recursive (while it does for export)

**Comment by finswimmer** [comment]
Yes, I think we should implement to include a folder recursive, like we do for excluding. That gives more consistency in user experience.

**Comment by rfaircloth-splunk** [comment]
I am also impacted by this problem I have a use case where certain files are generated at build time and need to be included in the package for use at run time however these build time files should not be in my git repo

**Comment by Halkcyon** [comment]
+1.  I build webapps and have a static folder for js-generated bundles that should not be included in the repo but do get added to the generated sdist artifact.  The `include` key _does not_ override exclusions from the `exclude` key (seeded with `.gitignore`) from the `pyproject.toml`.

I've written a very hacky build script that removes the line from `.gitignore` before building, but this is obviously non-ideal.

@finswimmer do you think this is the same problem as this overall issue, or should I open a new issue for this behavior?

**Comment by sinoroc** [comment]
Related: https://github.com/python-poetry/poetry/issues/3380

**Comment by cwegener** [comment]
This behaviour (parsing of a `.gitignore` file) is annoying.

It breaks the principle of least surprise.

There is hardly any clear mention of how this works in the documentation either.

The documentation just says:

> If a VCS is being used for a package, the exclude field will be seeded with the VCS’ ignore settings (.gitignore for git for example).

But it is not clear at all what "If a VCS is being used for a package" actually means. There is no reference of how to "use a VCS" anywhere in the documentation.

Why is this behaviour the default? And is it possible to turn this behaviour off somehow?

**Comment by ppena-LiveData** [comment]
Usually built files are files that are meant to be included in a distributed package but not included in version control, so I find this behavior very counterintuitive. If Poetry is going to continue to ignore VCS-ignored files, then at the minimum, the documentation should REALLY be explicit about that and have an example that includes something like `build/**/*`, since [Path.glob()](https://docs.python.org/3/library/pathlib.html#pathlib.Path.glob)'s `**` is quite confusing, and all the built files (including under subdirectories) are usually what someone would want to include.

**Comment by finswimmer** [comment]
Poetry now includes the given folder  recursive by default.
