### ISSUE TITLE
FreeBSD Releases Broken

### ISSUE THREAD

**Issue by neersighted** [python-poetry/poetry#2815]
After changes to the `make-nix-release.sh` [script](1), FreeBSD releases are [broken](2), as they require the latest stable version of Poetry to have a FreeBSD binary, in order for `get-poetry.py` to work. A simple `uname` check might be able to fix this, or maybe a switch back to installing from PyPI is needed.

[1]: https://github.com/python-poetry/poetry/commits/master/make-nix-release.sh
[2]: https://github.com/python-poetry/poetry/runs/907658577

**Comment by abn** [comment]
Breaking commit is https://github.com/python-poetry/poetry/commit/21867a17c1b3ebe8ffe5879a624eeaf54bb3cc3c
