### ISSUE TITLE
Install poetry behind a proxy

### ISSUE THREAD

**Issue by waszil** [python-poetry/poetry#2833]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request
Hi, I tried to install poetry on Centos8, however I could not even do this behind a corporate proxy. I could pass the proxy settings to curl, however I see that the installer script uses urllib, and I can see no way to pass proxy settings to that. It would be nice to have such an option for the installation.

**Comment by abn** [comment]
@waszil does `pipx` or `pip` install of `poetry` work for you?

Also, since the script uses `urllib` internally and `pip`/`poetry` uses `requests`, you can set your http proxy in your shell. Probably drop this into your `~/.bashrc` to cover your bases. Be sure to specify both upper and lower case variables.

```
export HTTP_PROXY="http://127.0.0.1:8000"
export http_proxy="http://127.0.0.1:8000"
export HTTPS_PROXY="http://127.0.0.1:8443"
export https-proxy="http://127.0.0.1:8443"

**Comment by waszil** [comment]
Standalone pip works fine. pip of poetry: I don't know, as I still cannot install poetry itself.
I have the env-vars exported, both in .bashrc and in /etc/profile.d/proxy.sh, however it still does not work. Even curl only works if I specify it explicitely with the --proxy option.
If I run the get-poetry.py, I get this:

 File "/usr/lib64/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer

**Comment by abn** [comment]
@waszil the environment variable should be handled by `urrlib.request` transparently.

> In addition, if proxy settings are detected (for example, when a *_proxy environment variable like http_proxy is set), ProxyHandler is default installed and makes sure the requests are handled through the proxy.
> 
> The legacy urllib.urlopen function from Python 2.6 and earlier has been discontinued; urllib.request.urlopen() corresponds to the old urllib2.urlopen. Proxy handling, which was done by passing a dictionary parameter to urllib.urlopen, can be obtained by using ProxyHandler objects.

See: https://docs.python.org/3/library/urllib.request.html

Assuming you are not using Python 2.7, this should work. It mighjt be that your proxy is terminating the connection. 

As a workaround you can use the `--file` option. You can download the release tarball from [releases](https://github.com/python-poetry/poetry/releases). And ask the instlaler to use it.

**Comment by waszil** [comment]
I'm using Python 3.8.0.
I guess the corporate proxy is not so helpful. I'll try the --file option, however I just opened this issue, because I periodically face this problem with a bunch of packages/libraries, and one of those can handle the life behind the proxy, others cannot, and it is quite frustrating, that there is no way to globally configure the proxy for everything.
