### ISSUE TITLE
Enable reading project's version number dynamically from somewhere other than pyproject.toml

### ISSUE THREAD

**Issue by maxgrenderjones** [python-poetry/poetry#2843]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

I'm working on a project where we would like to adopt poetry. One aspect of our long-established workflow is that our version numbers are maintained a changelog file. We currently parse that file in `setup.py` to ensure that when we install the project, the version number is always correct. 

`poetry` seems to only support reading the version from `pyproject.toml` which is obviously a static configuration file and so doesn't support logic as `setup.py` does. Is there, or could there be, a way to dynamically read the version from somewhere else? (The obvious workaround is to make the change manually ourselves as part of our release process, but anything you rely on a human to do is liable to suffer human error sooner or later!)

**Comment by finswimmer** [comment]
Hello @burrscurr,

please see my comment at https://github.com/python-poetry/poetry/pull/2366#issuecomment-652418094 about what you can do.

Hello @maxgrenderjones,

this is a question that raises from time to time. Also me was asking this a while ago (https://github.com/python-poetry/poetry/issues/1314#issuecomment-530366576). However, generate or read the version number dynamic from somewhere, makes it hard for dependency resolution tools like `poetry`, to get this value, when it needs to install something from source. Version numbers should belong to the static metadata and there should be only one place of truth for it. In case of `poetry` this is the `pyproject.toml`. Saying this we currently tend to not implement any dynamic reading from another place.

fin swimmer

**Comment by berislavlopac** [comment]
I would propose to use an option for the `poetry build` command, allowing a custom version string to be used for a particular build. This would allow both manual and scripted invocation to override the `pyproject.toml` version. So something like:

```shell
poetry build -f wheel --release-version 1.2.3-build872364872634
```

It might make sense only when building a wheel; I'm not sure. Additionally, would it make sense to be able to dynamically alter other compatibility tags? :thinking:

**Comment by chayim** [comment]
I'd echo @berislavlopac comment on specifying a --build-version on the command line, though injection with an environment variable would also be great.

**Comment by akvadrako** [comment]
@tiangolo Could you also make your plugin support reading version numbers for the environment?

**Comment by pgbradbury** [comment]
So to set the version in the pyproject.toml using poetry during CI, I use the following

`poetry version $ENV_VARIABLE`

But what I then want to do is read that into my FastAPI app to set the version in the docs. Which I tried by doing

```
from importlib.metadata import version
version_no=version("pkg_name")
```

But this is throwing an error. @tiangolo any ideas as FastAPI is your brilliant framework

**Comment by finswimmer** [comment]
Closing as not planned for the reasons outlined above. Since Poetry 1.2 we have a plugin system and a plugin like the one by @tiangolo can provide such a feature to users, who really need it.

**Comment by Sispheor** [comment]
This is pretty common behavior for people exposing the app version. Like Django apps or CLI through the `-v` of the arg parser.
You should definitively consider including this feature natively guys !

Thanks for the plugin anyway.

**Comment by godfryd** [comment]
You can solve this problem also using my plugin:
https://github.com/godfryd/poetry-arbitrary-version-plugin/

**Comment by martinda** [comment]
Our version numbers are computed dynamically then applied to git commits as tags. We never put version numbers in the source code because it creates a chicken an egg problem, and with hundreds of builds per day, that would create too many useless commits.  Relying on a community plugin maintained by a single user is not sustainable in the long term. Please take no offense, I am on both sides of the fence. Poetry should have built-in support for reading the version number from a property or an environment variable instead of relying on a plugin (or it should integrate the plugin as a core plugin like the core plugins of gradle).
