### ISSUE TITLE
Document the proper metadata for Python libraries

### ISSUE THREAD

**Issue by NathanDeMaria** [python-poetry/poetry#2847]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

In [the first FAQ](https://github.com/python-poetry/poetry/blob/d2fd581c9a856a5c4e60a25acb95d06d2a963cf2/docs/docs/faq.md#why-is-the-dependency-resolution-process-slow), it's mentioned that, "not all libraries on PyPI have properly declared their metadata". Are there specific pieces of metadata that would help `poetry` avoid needing to download and inspect packages?

As a reader of that doc who occasionally puts packages on PyPI, it would be helpful for me to know specifically what I can do to make sure libraries I contribute to have the metadata `poetry` uses properly set

**Comment by abn** [comment]
@NathanDeMaria the short answer is https://github.com/python-poetry/poetry/blob/master/poetry/inspection/info.py#L64-L70

Or you could make sure you use poetry to build and upload the package :)

**Comment by NathanDeMaria** [comment]
Is there a way to get more specific than that? I'm looking for some way to know if `poetry` is needing to download/inspect specific packages/why. Specifically, my questions when reading that are:
- Do I _need_ to set all of those fields? Or just the applicable subset? In particular, what happens if I don't set python versions? Poetry assumes all are fine? Or does that trigger a download?
- Are there ways I can set those values incorrectly? How can I know if I've done that? The _properly_ part of the docs makes me curious on that front
