### ISSUE TITLE
Poetry 1.1.0b2 PackageInfoError

### ISSUE THREAD

**Issue by giantas** [python-poetry/poetry#2850]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: OpenSUSE 15.1
- **Poetry version**: 1.1.0b2
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: My [pyproject.toml](https://gist.github.com/giantas/2781996de859c25822467663cc79984f)

## Issue

When running `poetry add PyPDF2`, I get:

```bash
Using version ^1.26.0 for PyPDF2

Updating dependencies
Resolving dependencies... (0.0s)

  PackageInfoError

  Unable to determine package info for path: /tmp/tmpvrzu96mh/PyPDF2-1.26.0

  at ~/.poetry/lib/poetry/inspection/info.py:322 in from_setup_files
      318│         )
      319│ 
      320│         if not (info.name and info.version) and not info.requires_dist:
      321│             # there is nothing useful here
    → 322│             raise PackageInfoError(path)
      323│ 
      324│         return info
      325│ 
      326│     @staticmethod
```

**Comment by finswimmer** [comment]
Hello @giantas,

this will be fixed if https://github.com/python-poetry/poetry/pull/2810 is merged.

fin swimmer
