### ISSUE TITLE
Improved error message for EmptyKeyError

### ISSUE THREAD

**Issue by rdmolony** [python-poetry/poetry#2851]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request
Hey, I had a similar issue to #2849 where my `poetry` Github Action failed with `EmptyKeyError` with 

```bash
 [EmptyKeyError]
Empty key at line 3 col 0
##[error]Process completed with exit code 1.
```

@finswimmer pointed out in #2849 that:
> could you please show your complete pyproject.toml? It looks like there is something malformed. Especially around line 12.

There was a merge conflict in my `pyproject.toml` - removing this fixed my issue.

Would it be possible to improve this error message to prompt the user to check their `pyproject.toml`?

**Comment by rdmolony** [comment]
To reproduce bug enter a line such as `<<<<<<<<<<<<<<` in `pyproject.toml`

such as:

```python
[tool.poetry]
<<<<<<<<<<<<<<<<<<<<<<<<<<<<
name = "poetry"
version = "1.1.0b2"
```

and run `poetry config` in the same directory as `pyproject.toml`

**Comment by abn** [comment]
Re-opening as this needs #2982 to close.
