### ISSUE TITLE
If .venv is an empty directory, poetry installs dependencies globally

### ISSUE THREAD

**Issue by jacebrowning** [python-poetry/poetry#286]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS 10.13.5
- **Poetry version**: 0.11.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**:  N/A

## Issue

1. Check out any poetry project
2. `$ rm -rf .venv && mkdir .venv`
3. ⚠️ `$ poetry install` ⚠️ 
4. Your dependencies are now installed globally

**Comment by jacebrowning** [comment]
At a minimum, we need an assertion to prevent this, but it would be nice if Poetry could turn an empty directory into a virtual environment.

And perhaps "empty" should mean that "bin/python" is absent.

**Comment by drunkwcodes** [comment]
Does it mean it has to be `if env.is_venv() and env.is_sane()` in https://github.com/sdispater/poetry/blob/master/poetry/utils/env.py#L209

**Comment by Strayer** [comment]
To add a realistic situation where this can happen: We do our development in Docker containers and mount a volume in the container at `/app/.venv` – meaning an empty `.venv` directory just as described will exist and break poetry.

For now, we just mount the volume at `$HOME/.cache/pypoetry/virtualenvs` and let poetry handle virtualenvs there to avoid this issue, but we'd prefer to keep using `settings.virtualenvs.in-project`.

**Comment by eff917** [comment]
This is still an issue in 1.0.0b5

Another use case is creating it with a placeholder file in code repository, that way poetry automatically uses it without having to explicitly set poetry settings.

**Comment by TheButlah** [comment]
I'm also running into this issue. in my case, .venv is a docker volume so it has already been mounted and therefore the folder is empty. This means that poetry installs its dependencies globally instead of in the volume. This is annoying because whenever the docker container gets destroyed, i have to reinstall all the dependencies since I cant install them in the volume's empty `.venv` folder.
