### ISSUE TITLE
poetry can not match package version with string like : fastapi_pypi_test-latest-py3-none-any.whl

### ISSUE THREAD

**Issue by logerror** [python-poetry/poetry#2860]
I found that poetry can only match packages of digital version type, it may due to regular expression constraints.

the file is : `lib/poetry/utils/patters.py` . regular expression  is 

```
 r"""^(?P<namever>(?P<name>.+?)(-(?P<ver>\d.+?))?)
        ((-(?P<build>\d.*?))?-(?P<pyver>.+?)-(?P<abi>.+?)-(?P<plat>.+?)
        \.whl|\.dist-info)$"""
```

**Comment by abn** [comment]
@logerror what is your use case here? Are you adding a local file dependency or a direct url reference? And in what step is this failing? I was unable to trigger any error for a wheel named as described. 

The regex follows [PEP 427](https://www.python.org/dev/peps/pep-0427/#file-name-convention).

**Comment by logerror** [comment]
i use the private repository, you can try this to Recurring problem。

1.  build a pypi pachage with version name like  "fasttest-latest-py3-none-any.whl" , tips: version is a string , not number
2.  publish to the repository
3.  poetry add this repository like ： poetry add fasttest

**Comment by logerror** [comment]
so ?

**Comment by finswimmer** [comment]
Hey,

`latest` is not a valid version. Versions must follow [PEP 440](https://peps.python.org/pep-0440/).

fin swimmer
