### ISSUE TITLE
Mandatory dataclasses module dependency not installed

### ISSUE THREAD

**Issue by l0b0** [python-poetry/poetry#2862]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 18.04
- **Poetry version**: 1.0.10
- **Relevant pyproject.toml line**: `black = {version = "*", allow-prereleases = true}`

## Issue

(Copied from [duplicate issue](https://github.com/psf/black/issues/1645).)

I tried changing pyproject.toml from `black = {version = "^19.10b0", allow-prereleases = true}` to `black = {version = "*", allow-prereleases = true}`. This results in an upgrade to 20.8b1 (`poetry update` prints "Updating black (19.10b0 -> 20.8b1)") and an entry in poetry.lock for the "dataclasses" package:

```toml
[[package]]
category = "main"
description = "A backport of the dataclasses module for Python 3.6"
marker = "python_version < \"3.7\""
name = "dataclasses"
optional = false
python-versions = ">=3.6, <3.7"
version = "0.7"

[package.source]
reference = "package proxy"
type = "legacy"
url = "http://…/root/pypi/+simple"
```

But for whatever reason it looks like it's not being installed - `poetry update` doesn't print anything about the "dataclasses" package, and the Virtualenv doesn't have it:

```text
$ find .venv -name '*dataclasses*'
.venv/lib/python3.6/site-packages/isort/_future/__pycache__/_dataclasses.cpython-36.pyc
.venv/lib/python3.6/site-packages/isort/_future/_dataclasses.py
.venv/lib/python3.6/site-packages/astroid/brain/__pycache__/brain_dataclasses.cpython-36.pyc
.venv/lib/python3.6/site-packages/astroid/brain/brain_dataclasses.py
.venv/lib/python3.6/site-packages/mypy/plugins/dataclasses.py
.venv/lib/python3.6/site-packages/mypy/plugins/dataclasses.cpython-36m-x86_64-linux-gnu.so
.venv/lib/python3.6/site-packages/mypy/plugins/__pycache__/dataclasses.cpython-36.pyc
.venv/lib/python3.6/site-packages/mypy/typeshed/stdlib/3.7/dataclasses.pyi
.venv/lib/python3.6/site-packages/mypy/typeshed/third_party/3/dataclasses.pyi
```

This results in the following error when running `black`:

```text
Traceback (most recent call last):
  File "…/.venv/bin/black", line 7, in <module>
    from black import patched_main
  File "…/.venv/lib/python3.6/site-packages/black/__init__.py", line 49, in <module>
    from dataclasses import dataclass, field, replace
```

Running `poetry install` afterwards doesn't make any difference.

**Comment by finswimmer** [comment]
Hello @l0b0,

I cannot reproduce it at with the latest pre-release of poetry. Can you try it out as well?

fin swimmer

**Comment by pedroig** [comment]
@l0b0, which python version did you use? I believe the issue is because [dataclasses](https://pypi.org/project/dataclasses/) doesn't support Python 3.7 anymore as `dataclasses` are already built-in. I had the same issue and solved it by using Python 3.6 for everything.

**Comment by l0b0** [comment]
Sorry I didn't close this earlier; the project no longer uses Poetry.

**Comment by kervel** [comment]
I think the issue is still there ... 
The problem is that conditional dependencies are not supported by poetry. If you look at blacks setup.py:
https://github.com/psf/black/blob/master/setup.py

```python
    install_requires=[
        "click>=7.1.2",
        "appdirs",
        "toml>=0.10.1",
        "typed-ast>=1.4.0",
        "regex>=2020.1.8",
        "pathspec>=0.6, <1",
        "dataclasses>=0.6; python_version < '3.7'",
        "typing_extensions>=3.7.4",
        "mypy_extensions>=0.4.3",
    ],
```

so the dataclasses dependency should be installed if the python_version < 3.7. I think poetry does not support that.

Frank

**Comment by finswimmer** [comment]
Hello @kervel,

of course poetry supports conditional dependencies. If you find a case where it does not, than it's probably a bug. But in the case reported here I'm unable to reproduce it, using poetry 1.1.4. dataclasses gets installed fine, in case the python version is <3.6.

fin swimmer
