### ISSUE TITLE
pre-commit hooks to always be sync after a git checkout

### ISSUE THREAD

**Issue by tetienne** [python-poetry/poetry#2863]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Issue

Hi, 

I have several projects where we update regularly the dependencies thank to [dependabot](dependabot.com/). My collaborators and I have to think to redo `poetry update` each time we `git pull` or `git checkout`.

So I wrote a small pre-commit hook to ease this process: https://github.com/tetienne/pre-commit-hooks

It will be interesting to host such hooks directly under https://github.com/python-poetry/poetry or perhaps under a dedicated project https://github.com/python-poetry/pre-commit-hooks.

What do you think?

**Comment by finswimmer** [comment]
Hey @tetienne,

sounds like in interesting idea. In the meantime we provide some pre-commit hooks and I think your suggestion would fit quite nice. Do you mind providing a PR for it?

fin swimmer

**Comment by tetienne** [comment]
Thx for this ping. I didn't notice there was now some hooks hosted here. That's great. 
Sure I will try to open a PR with my suggestion.

**Comment by Secrus** [comment]
@tetienne are you still interested in doing this?

**Comment by alsmnn** [comment]
@Secrus are you already on this? I just wanted to create a PR.
