### ISSUE TITLE
installing scrapy=2.3.0 using poetry fails with [RecursionError]

### ISSUE THREAD

**Issue by yeus** [python-poetry/poetry#2866]
- [X ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [ X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 20.04
- **Poetry version**: 1.0.10
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: n.a.

## Issue

```
mkdir test
cd test
poetry init
poetry add scrapy=2.3.0 #scrapy=2.2.0 works!
poetry lock
```  
fails with:

```
Updating dependencies
Resolving dependencies... (6.2s)

[RecursionError]
maximum recursion depth exceeded while calling a Python object
```

debugging with -vvv gives:

```
   0: Different requirements found for lxml (>=3.5.0) and lxml (>=4.0.0).
   1: Version solving took 0.017 seconds.
   1: Tried 1 solutions.
   0: Retrying dependency resolution for Python (>=3.8,<4.0).
   1: fact: test is 0.1.0
   1: derived: test
   1: fact: test depends on scrapy (^2.3.0)
   1: selecting test (0.1.0)
   1: derived: scrapy (^2.3.0)
   0: Duplicate dependencies for lxml
```

This problem might be related to the specific way scrapy sets up their dependencies:

https://github.com/scrapy/scrapy/blob/be655b855da3f5643b004e9f2d5b9161266c17f4/setup.py#L40

I also opened a scrapy-issue on this:

https://github.com/scrapy/scrapy/issues/4767

**Comment by finswimmer** [comment]
Hello @yeus,

could you try it with the latest preview release? I'm not able to reproduce it with this version.

Thanks!

fin swimmer

**Comment by yeus** [comment]
> Hello @yeus,
> 
> could you try it with the latest preview release? I'm not able to reproduce it with this version.
> 
> Thanks!
> 
> fin swimmer

thx, that worked!  that was a quick fix... ;).

**Comment by travelist** [comment]
I had the same issue and the following command worked, thanks!

```shell
pip install poetry==1.1.0rc1
```
