### ISSUE TITLE
Improve error message on I/O error crash

### ISSUE THREAD

**Issue by fredrikaverpil** [python-poetry/poetry#2870]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: RHEL 7
- **Poetry version**: 1.1.0b2 (but I believe this was updated to include the fix for #2721)

## Issue

I got hit by this: #2721 
@abn requested me to create an issue here on improving the error message on I/O error crash.

Possibly related: #2869

**Comment by 0xMRTT** [comment]
The PR has been merged, and it's available since 1.1.0b3
