### ISSUE TITLE
Publish prints "publishing to PyPI", even in case of private repository

### ISSUE THREAD

**Issue by ariebovenberg** [python-poetry/poetry#2872]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

Other details:

- **Poetry version**: 1.1.0b2

## Issue

When publishing to a private repository, poetry still outputs `publishing <file> to PyPI`.

I traced it to this code, which puzzles me a bit. It seems it will always output `PyPI`

https://github.com/python-poetry/poetry/blob/02d4d0c4fff8270c01fde399a7fb6ad1ad51f56c/poetry/publishing/publisher.py#L84-L91

Is there something I'm missing here? Should it just be `{"pypi": "PyPI"}.get(repository_name, repository_name)` instead? If so, I'd be happy to make a PR.

**Comment by finswimmer** [comment]
Hello @ariebovenberg,

yes this line does not make sense to me either. This will always return `PyPI`. Your suggestion looks good to me. Even if I'm thinking about whether `{"pypi": "PyPI"}.get(repository_name) or repository_name` might be more clear :thinking: No idea :)

**Comment by ariebovenberg** [comment]
The larger issue seems to be that a repository has a "slug" name (e.g.`pypi`) and a "display" name (e.g. `PyPI`). I could imagine this would be useful to support for private repositories as well.

I'll submit a PR for the bug soon. I'm leaning towards the explicit `"PyPI" if repsitory_name == "pypi" else repository_name`.
