### ISSUE TITLE
Can Poetry colors be changed?

### ISSUE THREAD

**Issue by albertotb** [python-poetry/poetry#2874]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Issue
Is it possible to change Poetry output colors? I was thinking it would be nice to change them similarly to how you can change the color of the prompt or the different file types

**Comment by 8F3E** [comment]
Whilst not a poetry-specific solution, changing your terminal emulator's default colours will change the look of poetry's output. For instance, when using `gnome-terminal` creating a new profile allows you to select a new palette of default colours.

I personally use the [nord](https://github.com/arcticicestudio/nord-gnome-terminal) colourscheme, which creates a new profile with new default/system colours.

**Comment by albertotb** [comment]
I understand, but that will change the colors for all the programs running in that terminal. My question is that if I can do it for poetry only
