### ISSUE TITLE
Lock for other platforms

### ISSUE THREAD

**Issue by bentheiii** [python-poetry/poetry#2879]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

Many projects need to support multiple platforms and versions, and checking that all dependencies are supported on all platforms is a constant need. A tool to help resolve this is the ability to lock a project for a platform other than the one machine uses. By performing, say, `poetry update --dry-run --platform win32`, we can check that a project's dependencies are resolvable for windows, even from a non-windows machine.
The primary use case for this is automated testing, where we need to be sure that adding dependencies doesn't break compatibility with other platforms.

**Comment by sdispater** [comment]
The lock file generated by Poetry is already platform agnostic, meaning that it's compatible with any platform regardless of the one it has been generated on. This is also true for Python versions, as long as the Python version being used is compatible with the range specified in the `python` requirement.
