### ISSUE TITLE
Http basic config password starting with "-"

### ISSUE THREAD

**Issue by jeremad** [python-poetry/poetry#2889]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: ubuntu 20.04 (also tested on mac)
- **Poetry version**: 1.0.10
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: N/A

## Issue

I way to use poetry with a private repository, as described in the [documentation](https://python-poetry.org/docs/repositories/#configuring-credentials) I run:
```bash
poetry -vvv config http-basic.foo username "-some_password"
```
Note the `-` at the beginning of the password

I have the following error:
```
[NoSuchOptionException]
The "-s" option does not exist.

Traceback (most recent call last):
  File "/home/jeremad/.poetry/lib/poetry/_vendor/py3.8/clikit/console_application.py", line 123, in run
    io = io_factory(
  File "/home/jeremad/.poetry/lib/poetry/console/config/application_config.py", line 168, in create_io
    resolved_command = application.resolve_command(args)
  File "/home/jeremad/.poetry/lib/poetry/_vendor/py3.8/clikit/console_application.py", line 110, in resolve_command
    return self._config.command_resolver.resolve(args, self)
  File "/home/jeremad/.poetry/lib/poetry/_vendor/py3.8/clikit/resolver/default_resolver.py", line 43, in resolve
    result = self.process_default_commands(args, application.default_commands)
  File "/home/jeremad/.poetry/lib/poetry/_vendor/py3.8/clikit/resolver/default_resolver.py", line 104, in process_default_commands
    if resolved_command.is_parsable():
  File "/home/jeremad/.poetry/lib/poetry/_vendor/py3.8/clikit/resolver/resolve_result.py", line 43, in is_parsable
    self._parse()
  File "/home/jeremad/.poetry/lib/poetry/_vendor/py3.8/clikit/resolver/resolve_result.py", line 49, in _parse
    self._parsed_args = self._command.parse(self._raw_args)
  File "/home/jeremad/.poetry/lib/poetry/_vendor/py3.8/clikit/api/command/command.py", line 113, in parse
    return self._config.args_parser.parse(args, self._args_format, lenient)
  File "/home/jeremad/.poetry/lib/poetry/_vendor/py3.8/clikit/args/default_args_parser.py", line 53, in parse
    self._parse(args, _fmt, lenient)
  File "/home/jeremad/.poetry/lib/poetry/_vendor/py3.8/clikit/args/default_args_parser.py", line 103, in _parse
    self._parse_short_option(token, tokens, fmt, lenient)
  File "/home/jeremad/.poetry/lib/poetry/_vendor/py3.8/clikit/args/default_args_parser.py", line 258, in _parse_short_option
    self._parse_short_option_set(name, tokens, fmt, lenient)
  File "/home/jeremad/.poetry/lib/poetry/_vendor/py3.8/clikit/args/default_args_parser.py", line 280, in _parse_short_option_set
    raise NoSuchOptionException(name[i])
```

**Comment by jeremad** [comment]
a test that reproduces the error: https://github.com/jeremad/poetry/commit/72331565222834b123406e237bc99cf1c4bfd39d

**Comment by bneijt** [comment]
Sounds a lot like https://github.com/python-poetry/poetry/pull/929 where people noticed the run command does not support the double dash approach to stop the argument parser from parsing further commands. The ArgvArgs clikit argument parser has the proper "takewhile" approach witch stops at a double dash, we should consider trying to mimic that approach in my opinion.

**Comment by jeremad** [comment]
It sure does look like it!

**Comment by szEvEz** [comment]
We are also running in the exact same issue. We're running poetry config in our Gitlab CI and make use of `$CI_REGISTRY_PASSWORD"`, which also can start with a `-` , therefore resulting into the following stacktrace

```
poetry config http-basic.gitlab -xtihg              

  Stack trace:

  11  ~/.poetry/lib/poetry/_vendor/py3.8/clikit/console_application.py:123 in run
      io = io_factory(

  10  ~/.poetry/lib/poetry/console/config/application_config.py:221 in create_io
      resolved_command = application.resolve_command(args)

   9  ~/.poetry/lib/poetry/_vendor/py3.8/clikit/console_application.py:110 in resolve_command
      return self._config.command_resolver.resolve(args, self)

   8  ~/.poetry/lib/poetry/_vendor/py3.8/clikit/resolver/default_resolver.py:34 in resolve
      return self.create_resolved_command(result)

   7  ~/.poetry/lib/poetry/_vendor/py3.8/clikit/resolver/default_resolver.py:166 in create_resolved_command
      if not result.is_parsable():

   6  ~/.poetry/lib/poetry/_vendor/py3.8/clikit/resolver/resolve_result.py:43 in is_parsable
      self._parse()

   5  ~/.poetry/lib/poetry/_vendor/py3.8/clikit/resolver/resolve_result.py:49 in _parse
      self._parsed_args = self._command.parse(self._raw_args)

   4  ~/.poetry/lib/poetry/_vendor/py3.8/clikit/api/command/command.py:113 in parse
      return self._config.args_parser.parse(args, self._args_format, lenient)

   3  ~/.poetry/lib/poetry/_vendor/py3.8/clikit/args/default_args_parser.py:53 in parse
      self._parse(args, _fmt, lenient)

   2  ~/.poetry/lib/poetry/_vendor/py3.8/clikit/args/default_args_parser.py:103 in _parse
      self._parse_short_option(token, tokens, fmt, lenient)

   1  ~/.poetry/lib/poetry/_vendor/py3.8/clikit/args/default_args_parser.py:258 in _parse_short_option
      self._parse_short_option_set(name, tokens, fmt, lenient)

  NoSuchOptionException

  The "-x" option does not exist.

  at ~/.poetry/lib/poetry/_vendor/py3.8/clikit/args/default_args_parser.py:280 in _parse_short_option_set
      276│     ):  # type: (str, List[str], ArgsFormat, bool) -> None
      277│         l = len(name)
      278│         for i in range(0, l):
      279│             if not fmt.has_option(name[i]):
    → 280│                 raise NoSuchOptionException(name[i])
      281│ 
      282│             option = fmt.get_option(name[i])
      283│             if option.accepts_value():
      284│                 self._add_long_option(
```

Is there a way to workaround this issue?

**Comment by bneijt** [comment]
You could add the password to the configuration file yourself. If you do not have a functioning keyring backend (often the case with CI) an `auth.toml` file will be created with the password in plaintext. Creating that file using a shell script should be quite trivial.

**Comment by DrLuke** [comment]
This works:
`poetry config -- http-basic.foo username -some_password`

The `--` part makes the argument parser stop parsing anything starting with dashes as options. This also means that you need to put all your options before the double dashes.

**Comment by bneijt** [comment]
If what @DrLuke says is true, then this bug can be closed as it must have been fixed in a newer release (mind you, the bug is already a year old).

I do not have the rights to close it, but @abn is probably allowed to close this issue till further notice then.

**Comment by DrLuke** [comment]
I'm not sure if this really was a bug in the first place, but rather unfortunate CLI design instead. When configuring basic auth credentials, only the username is required, and the password is optional. So the parser is given the choice if you're providing another optional argument or if you're inputting options, and I'd go for parsing it as options as well.

Maybe it makes sense to document this in the official docs?

**Comment by jeremad** [comment]
> I'm not sure if this really was a bug in the first place, but rather unfortunate CLI design instead. When configuring basic auth credentials, only the username is required, and the password is optional. So the parser is given the choice if you're providing another optional argument or if you're inputting options, and I'd go for parsing it as options as well.
> 
> Maybe it makes sense to document this [here](https://python-poetry.org/docs/repositories/#configuring-credentials)?

totally works for me
