### ISSUE TITLE
Poetry freezing

### ISSUE THREAD

**Issue by AstraLuma** [python-poetry/poetry#2891]
- **OS version and name**: Debian Testing
- **Poetry version**: 1.0.10

## Issue
I'm seeing poetry freezing, like so:

```
🐚 poetry update --verbose                                                                                                
Resolving dependencies... (0.0s)Updating dependencies
Resolving dependencies... 
```

I strongly suspect this is https://github.com/pypa/pip/issues/7883#issuecomment-688478103 , but I figured it would be good to file an issue in case other users are seeing the same problem.

**Comment by AstraLuma** [comment]
Oh, maybe not. Simply setting `$PYTHON_KEYRING_BACKEND` as suggested in the pip bug does not clear the issue.

**Comment by AstraLuma** [comment]
This is happening as far back as 1.0.0.

**Comment by AstraLuma** [comment]
```
🐚 poetry add -vvv -D pytest
Using virtualenv: /home/astraluma/.virtualenvs/clomp
```

**Comment by abn** [comment]
@AstraLuma was the existing lock file generated by a poetry pre-release?

**Comment by AstraLuma** [comment]
Nope. There is currently no lock file.

I've traced it to blocking on an HTTP request to pypi, but IDK from there.

**Comment by AstraLuma** [comment]
it might be my network? bare `requests` is being very slow to make requests to pypi.org, a behavior I can't replicate in cURL or firefox.

**Comment by AstraLuma** [comment]
Ok, this might not be poetry. `pip` is also very slow and requests with `requests` and `urlopen` both hang/take far far too long.

Now why only python is doing this is still a mystery.

**Comment by AstraLuma** [comment]
Able to confirm, it doesn't actually freeze, it just takes far, far too long to process anything.

I'm going to close this, as this seems to be "idk networking" than anything poetry has done.

**Comment by abn** [comment]
> Able to confirm, it doesn't actually freeze, it just takes far, far too long to process anything.
> 
> I'm going to close this, as this seems to be "idk networking" than anything poetry has done.

IIRC, there was some issues with IPv6 and pip/pypi. Try disabling v6?
