### ISSUE TITLE
[RuntimeError] Poetry was not installed with the recommended installer. Cannot update automatically.

### ISSUE THREAD

**Issue by timkofu** [python-poetry/poetry#2897]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS 10.15.6
- **Poetry version**: 1.0.10
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: Not Applicable

## Issue
I installed Poetry using `curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python`. It installed okay, and every operation is working well. However, `poetry self update` raises the exception `[RuntimeError] Poetry was not installed with the recommended installer. Cannot update automatically`. Below is the full traceback (obtained from running it with `-vvv`:
```
Traceback (most recent call last):
  File ".../lib/python3.8/site-packages/clikit/console_application.py", line 131, in run
    status_code = command.handle(parsed_args, io)
  File ".../lib/python3.8/site-packages/clikit/api/command/command.py", line 120, in handle
    status_code = self._do_handle(args, io)
  File ".../lib/python3.8/site-packages/clikit/api/command/command.py", line 171, in _do_handle
    return getattr(handler, handler_method)(args, io, self)
  File ".../lib/python3.8/site-packages/cleo/commands/command.py", line 92, in wrap_handle
    return self.handle()
  File ".../lib/python3.8/site-packages/poetry/console/commands/self/update.py", line 90, in handle
    self._check_recommended_installation()
  File ".../lib/python3.8/site-packages/poetry/console/commands/self/update.py", line 252, in _check_recommended_installation
    raise RuntimeError(
```

**Comment by finswimmer** [comment]
Hello @timkofu,

it looks like you have poetry installed at least a second time in another way, have you?

What's the output of `which -a poetry`?

fin swimmer

**Comment by timkofu** [comment]
That was it.

There was two of them, one installed via pip. I uninstalled both and reinstalled with `curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python`. Now `poetry self update` returns `You are using the latest version`.

**Comment by mfoglio** [comment]
I got just one installed:
`❯ which -a poetry
/usr/local/bin/poetry
`
Still run poetry update self:
❯ poetry self update

  RuntimeError

  Poetry was not installed with the recommended installer. Cannot update automatically.
```

  at /usr/local/Cellar/poetry/1.1.4/libexec/lib/python3.9/site-packages/poetry/console/commands/self/update.py:248 in _check_recommended_installation
      244│         current = Path(__file__)
      245│         try:
      246│             current.relative_to(self.home)
      247│         except ValueError:
    → 248│             raise RuntimeError(
      249│                 "Poetry was not installed with the recommended installer. "
      250│                 "Cannot update automatically."
      251│             )
      252│ 

```

Also, note I used `curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python`. 

Running on macOS.

**Comment by ahogen** [comment]
I'm on Windows 10 but was seeing this same error after installing with the recommended (Powershell) method, to the default location.

I uninstalled using `python ./get-poetry.py --uninstall`

Then set the `POETRY_HOME` environment variable (via the Windows env var editor).

Lastly re-installed using the [same script](https://github.com/python-poetry/poetry/blob/8b479d1559808adc6a03fcee4c42df2250363769/get-poetry.py).

`poetry self update` seems to work now, with the `POETRY_HOME` env var set.

**Comment by geo7** [comment]
Adding to say I have a similar issue:

```
  RuntimeError

  Poetry was not installed with the recommended installer. Cannot update automatically.

  at ~/.pyenv/versions/3.9.1/lib/python3.9/site-packages/poetry/console/commands/self/update.py:248 in _check_recommended_installation
      244│         current = Path(__file__)
      245│         try:
      246│             current.relative_to(self.home)
      247│         except ValueError:
    → 248│             raise RuntimeError(
      249│                 "Poetry was not installed with the recommended installer. "
      250│                 "Cannot update automatically."
      251│             )
      252│
```

and 

```
which -a poetry
/Users/g/.pyenv/shims/poetry
```

**Comment by kkirsche** [comment]
This occurred to me because I accidentally updated a dependency of poetry and tried to fix it by re-installing poetry's pip package to ensure Poetry's installed dependencies are accurate. Potentially a `--repair` option would be valuable?
