### ISSUE TITLE
Password represented as plain-text on CLI

### ISSUE THREAD

**Issue by cholmes047** [python-poetry/poetry#2901]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows 10 - Build 18363
- **Poetry version**: 1.0.9
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: N/A

## Issue
I'm using Poetry in conjunction with a privately hosted repository (Nexus) for installing Python packages. Everything works fine but we noticed something unnerving when running "poetry install" for a user that didn't quite have their access to our repository configured correctly. We get console output that looks like this:

`
[EnvCommandError]
Command ['C:\\Users\\user\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\project-name-NeU8dmQa-py3.8\\Scripts\\pip.exe', 'install', '--no-deps', '--index-url', 'https://user:password@nexus_url:port/repository/pypi/simple', 'ipython-genutils==0.2.0'] errored with the following return code 1, and output:
`

`
Looking in indexes: https://user:****@nexus_url:port/repository/pypi/simple
`

`
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x0000026943FE36D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /repository/pypi/simple/ipython-genutils/
`

This error is expected. The key takeaway here is that "https://user:password@nexus_url:port/repository/pypi/simple" reference in the first block. The user's password is represented there as **plain-text** and is not masked. This seems insecure and also inconsistent with the second block where the password is masked. I don't know if this is intended functionality or something that is preventable but we thought we should bring it to your attention.

Please let me know if there are any additional questions I can answer.

Thanks!

**Comment by abn** [comment]
Thanks for reporting the issue @cholmes047. While the concern is valid, this is not so straightforward to solve across the baord. The current pre-release release, `1.1.0b2`, should be slightly better here as we di not use pip to dowload the packages but rather do that internally, so the credentials are ... hopefully not exposed anymore. Will need to confirm. If it still does, it will have to be explcitily masked and re-reaised/handled.

As with any CLI tools, exceptions can leak credentials, and I would recommend anyone using shared CI environments enable using secrets and masking in logs. Most widely used CIs already support this.

**Comment by cholmes047** [comment]
@abn - thanks for your quick response!

Happy to hear that this is an issue that will hopefully go away in future releases! Thanks for all the work that you and the rest of the team are doing. I think Poetry is a great step forward in managing the package ecosystem for Python. Thanks for all your hard work!

**Comment by dimbleby** [comment]
the change mentioned above has long since happened, this can be closed
