### ISSUE TITLE
Can't use poetry env

### ISSUE THREAD

**Issue by lvar** [python-poetry/poetry#2902]
I try to use poetry for make some python projects.
When I run _**poetry install**_ get this error:

`$ poetry install /c/Users/el_sh/.poetry/bin/poetry: line 2: import: command not found /c/Users/el_sh/.poetry/bin/poetry: line 3: import: command not found /c/Users/el_sh/.poetry/bin/poetry: line 4: import: command not found /c/Users/el_sh/.poetry/bin/poetry: line 6: syntax error near unexpected token ('/c/Users/el_sh/.poetry/bin/poetry: line 6: lib = os.path.normpath(os.path.join(os.path.realpath(__file__), "../..", "lib"))'`

Any idea ? Thanks for your help.

**Comment by abn** [comment]
Looks like the `#!` was incorrect on your installation. The python executable might have been incorrectly detected. This could be that you install in bat and is using it from bash.

You can edit `/c/Users/el_sh/.poetry/bin/poetry` manually to fix it. 

You can also try re-installing in bash or even try `pipx` to install it.
