### ISSUE TITLE
poetry env remove does not work with in-project = true

### ISSUE THREAD

**Issue by ericriff** [python-poetry/poetry#2908]
Hi Guys, 

I'm using a poetry virtual env with `in-project = true` to have the environment created inside the project.
Anyways, if I run the command `poetry env remove python3` instead of removing `.venv` it errors out saying that `
Environment "poetry-project-RoyKdWrW-py3.5" does not exist.`

This command does work as expected if we store the environments in the regular cache.

It is a very minor bug since I can always do `rm -rf .venv` though.

Thanks for the amazing work.

- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 16.04
- **Poetry version**: 1.1.0a2

**Comment by 8F3E** [comment]
Think this is because, unlike `poetry env list`, removal doesn't check for a `.venv` file if `in-project = true`. Happy to try and patch.

**Comment by ericriff** [comment]
Thanks for looking into this!
I have another question regardless using `in-project = true`. This is a very useful feature since it allows us to easily integrate Poetry to our builds with docker/devcontainers since we don't have to mount external folders if we keep the environment in the project root.
The way Poetry implements this (which is the same way Pipenv does it AFAIK) is creating a `.venv` folder in the root of the project if the `in-project` flag is set.  This has a big limitation compared to using the global cache approach: you can only have one environment "ready to go" at the time, breaking the `poetry env use xxx` functionality. Usually this is not a problem since a project is locked to a given environment, but there are cases when it would be really cool to have multiple environments ready and switch between them with a simple command. They way it works now means that we have to delete `.venv` and re-build another environment.
Would it be possible to have something like `in-project` that makes Poetry generate different environments inside the root of the project?
Like .venv-python3.5, `.venv-python3.6`.

Thanks!

**Comment by 8F3E** [comment]
Sounds reasonable. Perhaps open a new issue as it would (I assume) require a change in the way poetry treats `in-project = true` globally, as opposed to implementing missing functionality?

**Comment by max-sixty** [comment]
Is this a duplicate of https://github.com/python-poetry/poetry/issues/2124?

**Comment by ericriff** [comment]
In deed it it. I'll close it.
