### ISSUE TITLE
Extras don't work with dev-dependencies

### ISSUE THREAD

**Issue by viq** [python-poetry/poetry#2909]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

- **OS version and name**: Fedora 32
- **Poetry version**: Poetry version 1.0.10
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/viq/0d09c834ea797f9a0a52522af6b4e3e7

## Issue

Either a bug, or a documentation issue. I wanted to add optional, development time dependencies, and even looking at https://github.com/python-poetry/poetry/issues/2749 I wasn't able to make this work. Turns out, apparently extras don't work for dev-dependencies, only for dependencies. Either this should work for both, or it should be documented that it supported only for one and not the other.

**Comment by mhamiltonj** [comment]
Is there any chance of a feature addition to make extras for with optional dependencies. I'm not quite sure what the reasoning behind the current limitation is.
