### ISSUE TITLE
Add "Typing :: Typed" classifier for porjects with `py.typed`

### ISSUE THREAD

**Issue by sobolevn** [python-poetry/poetry#2913]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

If `py.typed` file exists, `poetry` should added `"Typing :: Typed"` classifier, so the library can be found in PyPI in this section: https://pypi.org/search/?c=Typing+%3A%3A+Typed&o=&q=

Currently (1.0.10) it does not happen

**Comment by finswimmer** [comment]
Hello @sobolevn,

I don't think we should add this classifier automatically to a package. Any metadata should be set explicit in the `pyproject.toml`. Classifiers can be set by the `classifier` key. See the [docs](https://python-poetry.org/docs/pyproject/#classifiers) for an example.

fin swimmer

**Comment by sobolevn** [comment]
Fair enough! 👍

**Comment by pradyunsg** [comment]
@finswimmer Given that poetry is already being smart and adding License and Python classifiers, I think this would definitely be a nice-to-have along with them, especially since it's fairly straight-forward to infer this.

**Comment by zillionare** [comment]
I see this issue was closed, but don't know if the feature has been implemented or rejected.

I have made test, seems no such classifier was added
