### ISSUE TITLE
Using @latest on already existing dependency fails because of case sensitive matching of poetry

### ISSUE THREAD

**Issue by hwalinga** [python-poetry/poetry#2914]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: MX Linux 19 (Debian 10 derivative) 
- **Poetry version**: 1.1.0b2
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/hwalinga/21d833d0a3b6ca7a8724698df4736349

## Issue
By the documentation it seems that if I already have an existing dependency I can update it to the latest. However, I try to update a specific package that is installed by the name `pint`, but the official name is `Pint`. 

The debug clearly shows poetry's confusion about this:

```
   1: derived: Pint (^0.16)
   1: conflict: demap depends on pint (^0.15)
   1: ! not pint (^0.15) is satisfied by Pint (^0.16)
   1: ! which is caused by "demap depends on Pint (^0.16)"
   1: ! thus: version solving failed
```

Full debug can be found here: https://gist.github.com/hwalinga/b2bc4f2425c69cfafb836790e737d65a

Poetry should, just like `pip`, be case-insensitive on the dependency matching. You can install any package with pip without having the correct case and Poetry should not fail of that. (This is not just the first letter, `pip install PiNt` will also work for example, but capitalization of the first letter is of course something that is commonly encountered, Biopython is another example of that.)

**Comment by finswimmer** [comment]
Hm, strange. I'm not able to reproduce it :(

**Comment by hwalinga** [comment]
Ha, that is weird. If you try to reproduce this in complete isolation by just running `poetry add pint@0.15` and subsequently `poetry add pint@latest` you won't get an error, but if you try it with the pyproject.toml file I provided you will get an error. 

Here the steps to reproduce it from scratch:

```py
poetry new testing-poetry
cd testing-poetry 
curl -o pyproject.toml 'https://gist.githubusercontent.com/hwalinga/21d833d0a3b6ca7a8724698df4736349/raw/d2c8ba3629962393938f1bbb66c66dc9edaf2567/pyproject.toml'
poetry install
poetry add -vvv pint@latest
```

**Comment by finswimmer** [comment]
Hello @hwalinga,

still no problem here. Are you sure you are using the latest pre-release (1.1.0b2)?

fin swimmer

**Comment by hwalinga** [comment]
Yes, I am positive that I have the latest pre-release. 

However, I have reinstalled and the issue went away. Weird, but thanks for your time.

**Comment by hwalinga** [comment]
The problem has resurfaced!

Since we had some problems reproducing this the last time I made sure I could reproduce this in a fresh docker instance (I have also truncated the pyproject.toml file from last time to something much smaller):

```shell
docker run -it --rm python:3.8.6-buster /bin/bash
curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
source $HOME/.poetry/env
poetry new testing
cd testing
curl -o pyproject.toml 'https://gist.githubusercontent.com/hwalinga/939510e7ba84b58e17a5f0448a666126/raw/60eac3a754bae9892d815dd3746d700b7aeefd12/pyproject.toml'
poetry add -vvv pint@latest
```

**Comment by shughes-uk** [comment]
As pypi repos follow [PEP 426](https://www.python.org/dev/peps/pep-0426/#name):
```
All comparisons of distribution names MUST be case insensitive, and MUST consider hyphens and underscores to be equivalent.
```

It would honestly be very nice is poetry started lowercasing and converting underscores to hyphens (or the other way around), when adding packages to pyproject.toml` . That would resolve issues like these. I believe there's also another issue open for alpha sorting packages as they are added. All that together would make viewing diffs of changed dependencies so much easier.

**Comment by hwalinga** [comment]
I just tested this with the reproducible steps in my last comment and I can confirm this is still present in master.

**Comment by finswimmer** [comment]
This seems to be solved. Feel free to leave a comment if you disagree.

**Comment by hwalinga** [comment]
Whoops, I still have issues with this  : (

Here is another reproducible example, not case sensitive this time: 

```sh
docker run -it --rm python:3.8.6-buster /bin/bash
curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py > install-poetry.py
python install-poetry.py --pre
export PATH="/root/.local/bin:$PATH"
poetry new testing
cd testing
curl -o pyproject.toml 'https://gist.githubusercontent.com/hwalinga/f3b51fd69c4284f15ee53f17980e0d94/raw/2833e068603b89e897562b372d8455784388e03f/pyproject.toml'
poetry install
poetry add -vvv pytest@latest
```

And the corresponding error log: 

https://gist.github.com/a3a99dad6c0eb492f4d1c2748b60f52a
