### ISSUE TITLE
[1.1.0b2] Bumping version leaves orphaned dist-info in site-packages

### ISSUE THREAD

**Issue by MrGreenTea** [python-poetry/poetry#2918]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: elementary OS 5.1 Hera
- **Poetry version**: 1.1.0b2
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/MrGreenTea/992a1795471c00d727c02920d4288f16

## Issue
When updating my packages version with `poetry version` old dist-info directories are left in `site-packages`.
This trips up `pip`, `importlib` and `pkg_resources` for example when trying to find the packages information.
To reproduce:
(run with `poetry config virtualenvs.in-project true`)
1. `❯ poetry new example` 
2. `❯ poetry install`
3. `❯ ls .venv/lib/python3.8/site-packages/example*.dist-info`
```
.venv/lib/python3.8/site-packages/example-0.1.0.dist-info:
INSTALLER  METADATA  RECORD
```
4. `❯ poetry version minor && poetry install`
5. `❯ ls .venv/lib/python3.8/site-packages/example*.dist-info`
```
.venv/lib/python3.8/site-packages/example-0.1.0.dist-info:
INSTALLER  METADATA  RECORD

.venv/lib/python3.8/site-packages/example-0.2.0.dist-info:
INSTALLER  METADATA  RECORD
```
6. `❯ poetry run pip show example`
```
Name: example
Version: 0.2.0
Summary: 
Home-page: None
Author: Jonas Bulik
Author-email: jonas@bulik.dev
License: None
Location: /tmp/example/.venv/lib/python3.8/site-packages
Requires: 
Required-by: 
```
7. `❯ poetry version 0.1.0`
7. `❯ poetry run pip show example`
```
Name: example
Version: 0.2.0
Summary: 
Home-page: None
Author: Jonas Bulik
Author-email: jonas@bulik.dev
License: None
Location: /tmp/example/.venv/lib/python3.8/site-packages
Requires: 
Required-by: 
```

**Comment by finswimmer** [comment]
Hello @MrGreenTea,

I guess https://github.com/python-poetry/poetry/issues/2855 is related, is it?

fin swimmer

**Comment by MrGreenTea** [comment]
> Hello @MrGreenTea,
> 
> I guess #2855 is related, is it?
> 
> fin swimmer

@finswimmer Looks like the same cause, yeah.

**Comment by jkbecker** [comment]
I can reproduce that, and problematically, version bumping will
* always report the newest version as being installed during `poetry install`
* **however**, the actual code being run may or may not be the newest version

For example [excerpt from a discussion I had with sinoroc on the Discord trying to debug version issues of my project):
![image](https://user-images.githubusercontent.com/31668498/106673116-24f1a400-657f-11eb-8917-5df2a227bf6a.png)

Is this currently being worked on somehow, or is there a clean workaround in the meantime?

**Comment by sinoroc** [comment]
Does running `poetry run python -m pip uninstall YourProjectName` before running `poetry install` again help? It might be necessary to run the `pip uninstall` step more than one time until all old `dist-info` directories are removed. Otherwise removing the old `dist-info` directories manually seems like a good workaround. Another thing would be to delete the virtual environment and recreate it from scratch.

**Comment by ns-admetrics** [comment]
Using `pip uninstall` has the issue that you don't know how often to run it (potentially there are multiple old versions), but `pip uninstall` does not return an error code if there was no such package.

**Comment by fredrikaverpil** [comment]
@ns-admetrics 

> Using pip uninstall has the issue that you don't know how often to run it (potentially there are multiple old versions), but pip uninstall does not return an error code if there was no such package.

It seems however, that you will get a certain error message whenever pip has removed all the different versions:

```bash
$ pip uninstall b
Found existing installation: b 0.0.5
Uninstalling b-0.0.5:
  Would remove:
    /home/fredrik/code/repos/a/.venv/bin/bclix
    /home/fredrik/code/repos/a/.venv/lib/python3.9/site-packages/b-0.0.5.dist-info/*
    /home/fredrik/code/repos/a/.venv/lib/python3.9/site-packages/b.pth
Proceed (y/n)? y
  Successfully uninstalled b-0.0.5

$ pip uninstall b
Found existing installation: b 0.0.4
Uninstalling b-0.0.4:
  Would remove:
    /home/fredrik/code/repos/a/.venv/lib/python3.9/site-packages/b-0.0.4.dist-info/*
Proceed (y/n)? y
  Successfully uninstalled b-0.0.4

$ pip uninstall b
WARNING: Skipping b as it is not installed.
```

**Comment by ns-admetrics** [comment]
> It seems however, that you will get a certain error message whenever pip has removed all the different versions:

Yup but parsing messages is silly :) Re. `pip`, if the semantics of `uninstall` are declarative then it should uninstall all versions if multiple, if the semantics are imperative then it should fail in this WARNING case.

**Comment by jkbecker** [comment]
It's kind of annoying that pip doesn't exit with something non-zero when a package was not installed. I understand why it doesn't but if it did, one could just run uninstall in a while loop until the command fails to be sure it was completely cleaned up...

**Comment by sinoroc** [comment]
`pip show ProjectName` seems to give a usable return value.

**Comment by jkbecker** [comment]
Nice! Thank you, that is actually really helpful in my project as workaround for now.

**Comment by abn** [comment]
Can you please try the fix at #3900.

### Using pipx
```sh
pipx install --suffix=@3900 'poetry @ git+https://github.com/python-poetry/poetry.git@refs/pull/3900/head'
alias poetry=poetry@3900
poetry config virtualenvs.in-project true
poetry new example
pushd example
poetry install
find .venv/ -type d -name 'example*.dist-info'
poetry version minor
poetry install
find .venv/ -type d -name 'example*.dist-info'
poetry run pip show example
poetry version 0.1.0
poetry install
poetry run pip show example
```

### Using a container (podman | docker)
```sh
podman run --rm -i --entrypoint bash python:3.8 <<EOF
set -xe
python -m pip install -q git+https://github.com/python-poetry/poetry.git@refs/pull/3900/head
poetry config virtualenvs.in-project true
poetry new example
pushd example
poetry install
find .venv/ -type d -name 'example*.dist-info'
poetry version minor
poetry install
find .venv/ -type d -name 'example*.dist-info'
poetry run pip show example
poetry version 0.1.0
poetry install
poetry run pip show example
EOF
```

**Comment by fredrikaverpil** [comment]
@abn I just tried the #3900 fix (pipx approach) and I no longer see the lingering .dist-info folders accumulating. 👍 
I tested this with path dependencies and git dependencies.

However, I can see a couple of weird things. Maybe expected, but I figured I would mention them...

I've tested this on Python 3.9.2 and 3.6.10.

Output on Python 3.9.2 below. You can see how the "Installing..." never turns into the actual version on completed installation:

```
$ poetry@3900 install
Installing dependencies from lock file

Package operations: 6 installs, 0 updates, 0 removals

  • Installing certifi (2020.12.5): Installing...
  • Installing chardet (3.0.4): Installing...
  • Installing idna (2.8): Installing...
  • Installing urllib3 (1.22): Installing...
  • Installing requests (2.21.0): Installing...
  • Installing b (2.1.2 /home/fredrik/code/repos/b)

Installing the current project: a (1.0.0)
```

What was also a bit weird was that I somehow managed to break the output by first using a poetry 1.1.5:

```
$ poetry@work install
The virtual environment found in /home/fredrik/code/repos/a/.venv seems to be broken.
Recreating virtualenv a in /home/fredrik/code/repos/a/.venv
Installing dependencies from lock file

Package operations: 6 installs, 0 updates, 0 removals

  • Installing certifi (2020.12.5)
  • Installing chardet (3.0.4)
  • Installing idna (2.8)
  • Installing urllib3 (1.22)
  • Installing requests (2.21.0)
  • Installing b (2.1.2 /home/fredrik/code/repos/b)

Installing the current project: a (1.0.0)
```

and then I tried poetry@3900 again:

```
$ poetry@3900 install
Installing dependencies from lock file

Package operations: 0 installs, 5 updates, 0 removals

  • Updating certifi (2020.12.5 /home/fredrik/.cache/pyp
  • Updating certifi (2020.12.5 /home/fredrik/.cache/pypoetry/artifacts/d8/df/24/ed696681f34f8916b0aef99138db9a94e37d54684b9829af34a7fd4e39/certifi-2020.12.5-py2.py3-none-any.whl -> 2020.12.5): Installing...
  • Updating chardet (3.0.4 /home/fredrik/.cache/pypoetry/artifacts/8f/6f/1c/8085d730ad63c462222af30d0d01c4bd0caca5287e40b63c1fe8f529b7/chardet-3.0.4-py2.py3-none-any.whl -> 3.0.4): Installing...
  • Updating idna (2.8 /home/fredrik/.cache/pypoetry/artifacts/06/ea/a8/977db370296c645a9f7e1d772193cb28e1805639dace642b579a7d2cc0/idna-2.8-py2.py3-none-any.whl -> 2.8): Installing...
  • Updating urllib3 (1.22 /home/fredrik/.cache/pypoetry/artifacts/8a/d2/c3/8140b9cc76677757ce1397e48fec8a4c4c92e0ba44d0aa2aeb9bcf9b03/urllib3-1.22-py2.py3-none-any.whl -> 1.22): Installing...
  • Updating requests (2.21.0 /home/fredrik/.cache/pypoetry/artifacts/a2/2c/c6/5d7a41c3f8574633f2e590d06f41b47df7c5590c8ef73061d8941f8f45/requests-2.21.0-py2.py3-none-any.whl -> 2.21.0): Installing...

Installing the current project: a (1.0.0)
```

As you can see, that last time the output was very messy... I'm including a screenshot. Maybe this was because I was mixing poetry 1.1.5 and poetry@3900?

![image](https://user-images.githubusercontent.com/994357/114226521-f2479b80-9973-11eb-84db-3580d7320b04.png)

**Comment by abn** [comment]
That is expected. Because of #3876. There are followup fixes for that in #3891 and #3900.

**Comment by abn** [comment]
Oh, I misread the issue. Looks like there is a new issue in the lines not being updated during install. But this might not be related to the #3900 fix. 

Also you will note that in `1.1.5` you will have seen;
```
The virtual environment found in /home/fredrik/code/repos/a/.venv seems to be broken.
```

This is because the new venv does not have pip in it (#2826).

**Comment by dstnceswmer** [comment]
Still seeing this behavior in v1.1.15
