### ISSUE TITLE
Install Module Subsets

### ISSUE THREAD

**Issue by rdmolony** [python-poetry/poetry#2919]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**:  Docker container of
```
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
- **Poetry version**: 1.0.10
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue

I was tried to replicate `pip install "dask[dataframe]"` in poetry using `poetry add "dask[dataframe]"` but this only seemed to install the core dependencies (so it functioned like `pip install dask`).  I managed to get around it by using `poetry add` to install all "dask[dataframe]" dependencies indicated by Dask's `setup.py`.  Apologies if this issue has already been raised but I found it difficult to query `poetry add "module[submodule]"` or `pip install "module[submodule]"` or `poetry add submodule`!

**Comment by finswimmer** [comment]
Hello @rdmolony,

I'm not able to reproduce the issue with poetry 1.1.0b2.

This is what gets installed by `poetry add "dask[dataframe]"`:

```
Using version ^2.26.0 for dask

Updating dependencies
Resolving dependencies... (1.8s)

Writing lock file

Package operations: 11 installs, 0 updates, 0 removals

  • Installing six (1.15.0)
  • Installing locket (0.2.0)
  • Installing numpy (1.19.2)
  • Installing python-dateutil (2.8.1)
  • Installing pytz (2020.1)
  • Installing toolz (0.10.0)
  • Installing fsspec (0.8.2)
  • Installing pandas (1.1.2)
  • Installing partd (1.1.0)
  • Installing pyyaml (5.3.1)
  • Installing dask (2.26.0)
```

Looks good to me, as the extra `dataframe` consists of:

```
"numpy >= 1.13.0",
"pandas >= 0.23.0",
"toolz >= 0.8.2",
"partd >= 0.3.10",
"fsspec >= 0.6.0",
```

fin swimmer

**Comment by rdmolony** [comment]
I tried again just now and it's working perfectly with a nice pyproject.toml, sorry about this must have been something weird at my end!
```
dask = {extras = ["dataframe"], version = "^2.26.0"}
```

Thanks for your help @finswimmer !
