### ISSUE TITLE
poetry install: missing linebreaks with --no-ansi

### ISSUE THREAD

**Issue by Eugeny** [python-poetry/poetry#2922]
## Issue
As per above, `poetry install` doesn't output linebreaks between "Installing X(Y)..." lines and no linebreak at the very end either when `--no-ansi` is set.

**Comment by Alabate** [comment]
I've found a weird workaround: Piping the output of the command to anything make line break "appear".

So this command show linebreaks
```
poetry install --no-ansi | cat
```

**Comment by Eugeny** [comment]
Nice trick, thanks!
