### ISSUE TITLE
New `black` version breaks CI - linting

### ISSUE THREAD

**Issue by Cielquan** [python-poetry/poetry#2923]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: irrelevant
- **Poetry version**: current master & develop

## Issue
3 weeks ago a new version of `black` was released: `20.8b1`. The current states of `master` and `develop` are incompatible with the new version, but of course still compatible with `19.10b0`. Even so the older version is specified in the `.pre-commit-config.yaml` the CI fails for my PRs (#2511 #2548) in the linting part because of black:

```
black....................................................................Failed
- hook id: black
- files were modified by this hook

reformatted /home/runner/work/poetry/poetry/poetry/console/commands/install.py
reformatted /home/runner/work/poetry/poetry/poetry/installation/executor.py
reformatted /home/runner/work/poetry/poetry/poetry/mixology/version_solver.py
reformatted /home/runner/work/poetry/poetry/poetry/puzzle/solver.py
reformatted /home/runner/work/poetry/poetry/poetry/repositories/installed_repository.py
reformatted /home/runner/work/poetry/poetry/poetry/puzzle/provider.py
reformatted /home/runner/work/poetry/poetry/tests/console/conftest.py
reformatted /home/runner/work/poetry/poetry/tests/installation/test_authenticator.py
reformatted /home/runner/work/poetry/poetry/tests/installation/test_chooser.py
reformatted /home/runner/work/poetry/poetry/tests/installation/test_executor.py
reformatted /home/runner/work/poetry/poetry/tests/masonry/builders/test_editable_builder.py
reformatted /home/runner/work/poetry/poetry/tests/installation/test_installer.py
reformatted /home/runner/work/poetry/poetry/tests/utils/test_exporter.py
reformatted /home/runner/work/poetry/poetry/tests/puzzle/test_solver.py
All done! ✨ 🍰 ✨
14 files reformatted, 251 files left unchanged.
```

I tested it locally. I installed black `19.10b0` and let it run over `master` and `develop`. Both were ok. Then I updated `black` to 20.8b1` and for `develop` I got the exact same files that were changed. On master 17 files are changed:

```
$ black .
reformatted /home/krys/Python_Projects/.contributions/poetry/poetry/console/commands/install.py
reformatted /home/krys/Python_Projects/.contributions/poetry/poetry/mixology/version_solver.py
reformatted /home/krys/Python_Projects/.contributions/poetry/poetry/repositories/installed_repository.py
reformatted /home/krys/Python_Projects/.contributions/poetry/poetry/installation/executor.py
reformatted /home/krys/Python_Projects/.contributions/poetry/poetry/puzzle/solver.py
reformatted /home/krys/Python_Projects/.contributions/poetry/poetry/puzzle/provider.py
reformatted /home/krys/Python_Projects/.contributions/poetry/tests/conftest.py
reformatted /home/krys/Python_Projects/.contributions/poetry/tests/console/conftest.py
reformatted /home/krys/Python_Projects/.contributions/poetry/tests/inspection/test_info.py
reformatted /home/krys/Python_Projects/.contributions/poetry/tests/installation/test_chef.py
reformatted /home/krys/Python_Projects/.contributions/poetry/tests/installation/test_authenticator.py
reformatted /home/krys/Python_Projects/.contributions/poetry/tests/installation/test_chooser.py
reformatted /home/krys/Python_Projects/.contributions/poetry/tests/installation/test_executor.py
reformatted /home/krys/Python_Projects/.contributions/poetry/tests/masonry/builders/test_editable_builder.py
reformatted /home/krys/Python_Projects/.contributions/poetry/tests/utils/test_exporter.py
reformatted /home/krys/Python_Projects/.contributions/poetry/tests/installation/test_installer.py
reformatted /home/krys/Python_Projects/.contributions/poetry/tests/puzzle/test_solver.py
All done! ✨ 🍰 ✨
17 files reformatted, 257 files left unchanged.
```

## Problem

`master` and `develop` are no longer compliant to the current version off `black` but whats more important is why does the CI seemingly uses a newer version of `black` then specified?

**Comment by abn** [comment]
@Cielquan `develop` branch is no longer used, it is only maintained till the active PRs are rebased.

**Comment by abn** [comment]
Closing as things are, as expected.

**Comment by Cielquan** [comment]
Well I rebased my PRs onto current master and CI (linting) works/succeeds now. :+1: 

I know that the older version of black is fixed and specified. Thats what confused me.

> `master` and `develop` are no longer compliant to the current version off `black` but whats more important is why does the CI seemingly uses a newer version of `black` then specified?

_____

But fortunately it works on master as it should.
