### ISSUE TITLE
Dependencies aren't resolved as expected

### ISSUE THREAD

**Issue by aviramha** [python-poetry/poetry#2926]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS Catalina 10.15.6
- **Poetry version**: 1.1.0b2

Poetry seems to fail to resolve dependencies correctly of async-asgi-testclient library.
`poetry add -D async-asgi-testclient`
`pip freeze | grep requests`
You'll see that requests library wasn't installed, even though it's required.
Running pip install does install requests.

**Comment by jeffcasavant** [comment]
I've had similar issues with transitive deps.  Most recently `pylint` needed `wrapt` but it was not installed.

**Comment by aviramha** [comment]
Was this fixed by https://github.com/python-poetry/poetry/commit/5acf8fa6eccc08053e8f3b4164e164256ba146cf ?
