### ISSUE TITLE
Create virtual env hash based on lock file instead of parent directory

### ISSUE THREAD

**Issue by matzhaugen** [python-poetry/poetry#2927]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request
When building the same poetry package with the same lock file on a different machine, e.g. On different VMs in a jenkins PR build cluster, the virtual environment will hash to something different if the VM is not the same. This is because the folder parent directory is different, e.g. `/home/PR123/pyproject.toml` vs/ `/home/PR124/pyproject.toml`.

I think it would be nice to have the virtual env hash be the same in these to instances *if and only if* the lock file is identical.

**Comment by abn** [comment]
@matzhaugen I do not think this is feasible; since this would mean that everytinme the lock changes, poetry re-creates a venv. While that is okay and even preferred in a CI environment, not so much for development environments.

You should consider using `poetry config virtualenvs.in-project true`.

**Comment by matzhaugen** [comment]
Thanks for the quick response. Yes that is a good point. It probably isn't feasible for development environments, but maybe if it were an optional argument? With `poetry config virtualenvs.in-project true` you will not have a way to label your venv and share it, unless you hash based on the lock file. How about this: When you specify `poetry config virtualenvs.in-project true` Instead of calling it `.venv` call it `.venv-{hash}` where `hash` is based on the lock file? :)

**Comment by abn** [comment]
Unfortunately, same issue. Also, I would not recommend sharing virtualenvironments unless the systems are identical in the first place. In cases like CI environments, typically you cache the venv based on `<os>-<python-version>-<lock hash>` if you are inclined to do so. Couldn't your ci environment do the same? As in, cache the `.venv` directory with the above key?

https://github.com/python-poetry/poetry/blob/dfa5c0f61b417dc47ab5d91405fb5d8bb6446017/.github/workflows/main.yml#L45-L59

I am not sure if this is a large enough use case that cannot be solved elswhere. If it is, we could look at enabling some sort of option for this, `virtualenvs.use-lock-hash`. If we do implement something like this, this also will need to be handled by #2924 for `in-project` virtualenvs. Using any other name than `.venv` for the root directory in this scenario is something that I am not in favour for, as it is convention (eg: ignored by default gitignores etc).

**Comment by matzhaugen** [comment]
The code you give above is actually a nice way to solve this in a CI setting. I'll just do that.

More generally, I agree that changing the `.venv` name would not be ideal. Another option could be to add an `poetry export venv` option which hashes based on what you specify above, but given your proposed solution, this is not so important for me.
