### ISSUE TITLE
'poetry run/shell' behavior when the environment hasn't been created yet

### ISSUE THREAD

**Issue by ericriff** [python-poetry/poetry#2932]
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request
When you run `poetry run someScript.py` on a folder which has the required `pyproject.toml` but the environment has not been created yet, poetry will happily create one for you, but it will be "empty" This means that your script will fail to run.

I believe it would be extremely useful if poetry not only creates a new environment, but also runs the `install` command, in order to have a working environment.

As a possible use case, you can embed the poetry files in a project and instruct the developers and/or users to just run `poetry run someScript.py` and that will always work, without a previous "set up" of the environment.

Thanks for the amazing work!

**Comment by cauebs** [comment]
I agree with you, that is my intuition as well. I'm on it!

We just have to figure out if it then makes sense to have a flag for all commands that use a venv to not run `install` automatically when creating a new venv. I'm not sure.

**Comment by cauebs** [comment]
Actually, it wasn't as trivial as I imagined. Creation is not done directly by a `Command`, it's done by an `Env` when `EnvCommand.env.execute` is called. I can think of two options, both bad: instantiate a `InstallCommand` inside the `utils/env.py:Env`, or find some way to bubble up to `Command` whether a venv had to be created or not.

Not sure how to proceed, so I'll wait for feedback from the maintainers.

**Comment by neersighted** [comment]
Duplicate #2039.
