### ISSUE TITLE
Docs: Update bash completions for more distros

### ISSUE THREAD

**Issue by WSLUser** [python-poetry/poetry#2934]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

Under https://python-poetry.org/docs/#enable-tab-completion-for-bash-fish-or-zsh, add 

`poetry completions bash > /usr/share/bash-completion/completions/poetry.bash-completion`. 

Some distros such as [Clear Linux](https://github.com/clearlinux/distribution) (a stateless distro) and [Pengwin](https://github.com/WhitewaterFoundry/Pengwin) (a custom WSL distro) don't rely on `/etc`  for bash completions. Instead they rely upon `/usr/share`. So please add this as another option under 

> Enable tab completion for Bash, Fish, or Zsh

**Comment by Secrus** [comment]
The distros you mentioned seem to be for more advanced users, which are aware of the differences in their OS. For now I see this as `wontfix`, but PRs are welcome if you feel that this is required.
