### ISSUE TITLE
Poetry picks up the wrong version of python

### ISSUE THREAD

**Issue by ericriff** [python-poetry/poetry#2938]
- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 16.04
- **Poetry version**: 1.1.0b2

I have required vesion of python listed in `pyproject.toml` as fallows:
```
[tool.poetry.dependencies]
python = "==3.5.2"
```
So I'm requiring the environment to use python 3.5.
On my PC I have `python3.5` and `python3.6` installed, and I have poetry installed for both of them via `pip`, using `update-alternatives` I have `python3 -> python3.5` as the default.

If you don't have an environment created for the project and you run `poetry shell`, poetry first creates the environment and then launches the shell for you. It reports that is using python3.5 but it is not. See the following snippet:

```
$ python3.6 -m poetry shell               
The currently activated Python version 3.6.12 is not supported by the project (==3.5.2).
Trying to find and use a compatible version. 
Using python3 (3.5.2)
Creating virtualenv poetry-test-RoyKdWrW-py3.5 in /home/eric/.cache/pypoetry/virtualenvs
Spawning shell within /home/eric/.cache/pypoetry/virtualenvs/poetry-test-RoyKdWrW-py3.5
(poetry-test-RoyKdWrW-py3.5)  $ python --version         
Python 3.6.12
```
As you can see, poetry sees that it should be using python 3.5, and even creates an environment with `py35` in its name, but when you launch the environment and check the version, it is python 3.6.

If we remove the environment and start over, but running poetry with python 3.5, it works:
```
$ python3.6 -m poetry env remove python3.5
$ python3.5 -m poetry shell                                                      

Python 3.5 will no longer be supported in the next feature release of Poetry (1.2).
You should consider updating your Python version to a supported one.

Note that you will still be able to manage Python 3.5 projects by using the env command.
See https://python-poetry.org/docs/managing-environments/ for more information.

Creating virtualenv poetry-test-RoyKdWrW-py3.5 in /home/eric/.cache/pypoetry/virtualenvs
Spawning shell within /home/eric/.cache/pypoetry/virtualenvs/poetry-test-RoyKdWrW-py3.5
(poetry-test-RoyKdWrW-py3.5)  $ python --version         
Python 3.5.2
```

This is not a limitation of poetry being installed via pip, because this works:
```
$ python3.6 -m poetry env use python3.5   
Creating virtualenv poetry-test-RoyKdWrW-py3.5 in /home/eric/.cache/pypoetry/virtualenvs
Using virtualenv: /home/eric/.cache/pypoetry/virtualenvs/poetry-test-RoyKdWrW-py3.5
$ python3.6 -m poetry shell            
Spawning shell within /home/eric/.cache/pypoetry/virtualenvs/poetry-test-RoyKdWrW-py3.5
(poetry-test-RoyKdWrW-py3.5)  $ python --version         
Python 3.5.2
```

So poetry is able to create an environment using a python version that is not the one activated.
This problem persists if we use `in-project = true` and `poetry run script.py` shows the same behavior.

This is a big deal since it is lying to the user about the python version used!

Thanks!

EDIT: This works with poetry installed via `get-poetry.py`.

**Comment by max-sixty** [comment]
I see something similar:

poetry initially chooses to install for python3.8:

```sh
$ poetry install

The currently activated Python version 3.9.0 is not supported by the project (>=3.6.9, <3.9).
Trying to find and use a compatible version.
Using python3 (3.8.6)
Creating virtualenv nimbus-cyukv0jK-py3.8 in /Users/maximilian/Library/Caches/pypoetry/virtualenvs
Installing dependencies from lock file
...
```

And reports it as such:

```sh
$ poetry env list

nimbus-cyukv0jK-py3.8
```

But then actually sets up a python3.9 env:

```sh
$ poetry env info

Virtualenv
Python:         3.9.0
Implementation: CPython
Path:           NA

System
Platform: darwin
OS:       posix
Python:   /usr/local/Cellar/python@3.9/3.9.0/Frameworks/Python.framework/Versions/3.9
```

Prior to running those commands, I'd removed any envs, such that `poetry env list` returned nothing.

Let me know any other details that would be helpful as a test case; here's a [`pyproject.toml`](https://gist.github.com/max-sixty/fe075c006482a5560ce15d747007e7ad)

**Comment by max-sixty** [comment]
FWIW running `poetry env use 3.8` makes this work!

**Comment by max-sixty** [comment]
Unfortunately `poetry env use 3.8` is fickle, and doesn't work on a colleague's system, who still sees:

![image](https://user-images.githubusercontent.com/5635139/96490021-1ad8af00-11f5-11eb-8321-c38afc7859f5.png)

Is this expected? Am I doing something wrong to make this happen or is this a bug? Is there anything I can do to fix this?

**Comment by ericriff** [comment]
The easiest way to get around this is to remove all the versions installed with `pip` and then install it using `get-poetry.py` which is the recommended method.

**Comment by max-sixty** [comment]
Yes, I had some separate issues with `PATH` when using that approach, which using Brew takes care of. But potentially dealing with those issues is less work than dealing with these issues.

**Comment by arthur-morgan-712** [comment]
Nothing seems to work for me, I even deleted my local Python 3.9, reinstalled poetry using my 3.8 python, the venv name is 3.8, yet the version is still 3.9.1 even after executing `poetry env use 3.8`

**Comment by ericriff** [comment]
This looks related to https://github.com/python-poetry/poetry/issues/3785

**Comment by finswimmer** [comment]
Hey @ericriff,

lots of improvements were made since you open the issue. I guess your problem is solved in the meantime. Also se
setting `virtualenvs.prefer-active-python` to `true` might be a good idea.

fin swimmer
