### ISSUE TITLE
poetry shell does not work on my msys2( virtual linux + windows python )

### ISSUE THREAD

**Issue by gaoming714** [python-poetry/poetry#2961]
- [ x ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [ ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: 
- **Poetry version**: 
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue

System windows, shell is msys2, 
But python is winpython,( python on windows)

Normally, I need to run `source activate.bat` for windows. 
But for my msys2 , I need to run `source activate`.
So the `poetry shell` does not work.

I can use `source .../Scripts/activate` manually.
the pipenv has the save issue.
can you support to fix?

E.g.
➜  selenium_DR4 git:(master) ✗ poetry shell -v
Using virtualenv: D:\Portable\Python\virtualenvs\selenium-dr4-mtk5ooG4-py3.8
Spawning shell within D:\Portable\Python\virtualenvs\selenium-dr4-mtk5ooG4-py3.8
➜  selenium_DR4 git:(master) ✗

**Comment by abn** [comment]
@gaoming714 the example you have provided seems unclear since there are no errors. Is this simply an issue of the prompt not being updated?

**Comment by gaoming714** [comment]
uanme -a 
`MSYS_NT-10.0-19041 DESKTOP-EE9SP20 3.1.7-340.x86_64 2020-08-27 11:03 UTC x86_64 Msys`

Manual & Good
```
➜  arkham git:(master) ✗ source /d/Portable/Python/virtualenvs/arkham-CFMpiRAH-py3.8/Scripts/activate
(arkham-CFMpiRAH-py3.8) ➜  arkham git:(master) ✗
```

poetry shell ， which is not ok.:
```
➜  arkham git:(master) ✗ poetry shell
Spawning shell within D:\Portable\Python\virtualenvs\arkham-CFMpiRAH-py3.8
➜  arkham git:(master) ✗
```

I know for windows, Spawning shell is needed by run activate.bat, but my environment is linux-like system. It needs source activate.

**Is there any way to see the  actual commands for ` poetry shell ` ?**

**Comment by abn** [comment]
The relevant lines are here.

https://github.com/python-poetry/poetry/blob/d4eb422e453b0b153e6bacd21dbc5ae372e59f98/poetry/console/commands/shell.py#L38-L39

You can follow the code from here to do a sheel specific fix.

https://github.com/python-poetry/poetry/blob/d4eb422e453b0b153e6bacd21dbc5ae372e59f98/poetry/utils/shell.py#L62-L64

**Comment by gaoming714** [comment]
I think my env( msys2+ winpython ) is not a typical shell, 
acrivate for windows, shell for linux. as the follow

```
>>> from poetry.utils.shell import Shell
>>> Shell.get()
Shell("cmd", "C:\WINDOWS\system32\cmd.exe")
```

I think  a manual way is better.

**Comment by gaoming714** [comment]
@abn can you tell me the website  theme, https://python-poetry.org/ ?

By the way,

**Comment by akpircher** [comment]
> I think my env( msys2+ winpython ) is not a typical shell,

For what it's worth, my personal laptop is Windows where I also run msys2 (or git bash) + winpython, or specifically pyenv-win.
Simply sourcing the activate bash script works for me without needing to run activate.bat at all. 

Running `poetry shell` seems to always switch to a cmd.exe shell, instead of activating the virtual environment for the appropriate shell.  (This includes powershell consoles as well). Meanwhile `shellingham.detect_shell()` correctly detects the console I'm in.

@gaoming714 @abn, do you mind if I take a stab at this?

**Comment by gaoming714** [comment]
@akpircher 
I think in this kind of cross environment, poetry does not know what environment I need (.bat .ps1 or none)
It may be caused by `shellingham.detect_shell()`, but poetry is required to handle such a complicated environment. 
I think it adds unnecessary logic to the program.

I personally think that an activate script can be added manually because the user knows which one needs to be run. 
you can use `@create` to create activate file, then `@act` to activate(like `poetry shell`), then `@dct` to deactivate.

This is my script, it works on my windows + msys2 + winpython:


```shell
# create_activate
#!/bin/bash                                                                       
if [ -f "activate" ];then                                                         
  rm -f activate                                                                  
fi                                                                                
path=`poetry env info -p`                                                         
ln -s $path\\Scripts\\activate
# edit this activate 
```

```shell
# in bashrc
alias @create="bash create_activate"                                              
alias @act="source activate"                                                      
alias @dct="deactivate" 
```
