### ISSUE TITLE
[Windows] Poetry doesn't Remove Virtual Environment when Python version Number is given

### ISSUE THREAD

**Issue by naveen521kk** [python-poetry/poetry#2964]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Microsoft Windows 7 Ultimate 6.1.7601 Service Pack 1 Build 7601
- **Poetry version**: 1.0.10
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: [pyproject](https://github.com/ManimCommunity/manim/blob/master/pyproject.toml)

## Issue
When I install any project virtualvenv gets created but when removing the virtualenv using command 
```sh
poetry env remove 3.7
```
It gives the following error.
```sh
'python3.7' is not recognized as an internal or external command,
operable program or batch file.

[EnvCommandError]
Command python3.7 -c "import sys; print('.'.join([str(s) for s in sys.version_in
fo[:3]]))" errored with the following return code 1, and output:


Traceback (most recent call last):
  File "C:\Users\xyz\.poetry\lib\poetry\_vendor\py3.7\clikit\console_app
lication.py", line 131, in run
    status_code = command.handle(parsed_args, io)
  File "C:\Users\xyz\.poetry\lib\poetry\_vendor\py3.7\clikit\api\command
\command.py", line 120, in handle
    status_code = self._do_handle(args, io)
  File "C:\Users\xyz\.poetry\lib\poetry\_vendor\py3.7\clikit\api\command
\command.py", line 171, in _do_handle
    return getattr(handler, handler_method)(args, io, self)
  File "C:\Users\xyz\.poetry\lib\poetry\_vendor\py3.7\cleo\commands\comm
and.py", line 92, in wrap_handle
    return self.handle()
  File "C:\Users\xyz\.poetry\lib\poetry\console\commands\env\remove.py",
 line 19, in handle
    venv = manager.remove(self.argument('python'))
  File "C:\Users\xyz\.poetry\lib\poetry\utils\env.py", line 456, in remo
ve
    raise EnvCommandError(e)
```
On investigating, 
https://github.com/python-poetry/poetry/blob/ad0cea97aa24903be584b571e4b6f9d89a977a5f/poetry/utils/env.py#L453-L457
Pretty it is because `python3.7` can't be called using `python3.7` command in windows. It needs to called using
```sh
py -3.7
```
command in Windows. Ref this docs https://docs.python.org/3/using/windows.html#from-the-command-line

**Comment by finswimmer** [comment]
Hello @naveen521kk,

the correct usage of `poetry env remove` is to provide the correct python executable.

```bash
$ poetry env remove --help         
USAGE
  poetry env remove <python>

ARGUMENTS
  <python>               The python executable to remove the virtualenv for.
```

Providing just the version number is some syntactic sugar, that works for the most system.

So it works like intended.

fin swimmer
