### ISSUE TITLE
Old version pip can't install opencv-python

### ISSUE THREAD

**Issue by Vozf** [python-poetry/poetry#2966]
- **OS version and name**: Ubuntu
- **Poetry version**: 1.0.10

## Issue

I'm trying to install opencv-python with poetry
`poetry add opencv-python`
It hangs onn this line
`  - Installing opencv-python (4.4.0.44)`
It succeeds only after pip upgrade
`poetry run pip install --upgrade pip`
First I had 
`pip 19.2.3`
After upgrade 
`pip 20.2.3`

**Comment by abn** [comment]
#2666 upgrades the version pip used. However, I suspect the issue here more to do with the large artifacts. The second run might have had it cached.
