### ISSUE TITLE
Support For TLS Certificate Mutual Authentication

### ISSUE THREAD

**Issue by j5awry** [python-poetry/poetry#297]
- [X] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

For publishing, Pip and Twine allow for TLS Certificate mutual authentication instead of basic auth. In our enterprise environment, basic auth is disallowed, and only various forms of multi-factor are allowed. Please consider having more methods of authentication beyond basic auth, including mutual auth. Example Twine command

`twine upload -u myuser -p "" --cert /Users/user/.certs/myca.pem --client-cert /Users/user/mycert.pem --repository-url https:/internalpypi.com/api/pypi/pypi-internal dist/*`

Note the weird empty password, which is a bug in twine.

**Comment by Caligatio** [comment]
I'm forgetting if GitHub emails people on cross ticket mentions but I have a PR, #1325, that addresses this request. The developers said in Discord that they're ranking PRs by number of votes so please +1 the PR :)

**Comment by sdispater** [comment]
This is now supported in the latest `1.0.0` release (see https://python-poetry.org/docs/repositories/#custom-certificate-authority-and-mutual-tls-authentication).
