### ISSUE TITLE
How to configure poetry to build sdist as .zip file

### ISSUE THREAD

**Issue by FelixKJose** [python-poetry/poetry#2970]
I am trying to build a source distribution as .zip file since pyspark requires its scripts common dependencies as a .zip file. 
But I couldn't find a way in poetry to configure poetry to output zip file rather than tar.gz file. Could someone please let me know whether this is supported, if yes how do I achieve the same?

Thank you

**Comment by FelixKJose** [comment]
Could someone help me?
@abn @mbelang ^^

**Comment by abn** [comment]
There is no option for that at the moment. Although wheels are zip files, and I suspect pyspark supports them.

**Comment by TheErk** [comment]
+1 as a hack you can try to build a wheel and rename it as .zip 
It seems to work: https://bytes.grubhub.com/managing-dependencies-and-artifacts-in-pyspark-7641aa89ddb7

> Now that we have all the components to make our distribution files, we need to rename our 'wheel' files as zip files and provide them to '--py-files' option.

note that I am no pyspark expert so this is a wild guess.

**Comment by innerNULL** [comment]
Yep, I'm also finding that if poetry can support building zipapp (ref to ([this](28.4. zipapp — Manage executable python zip archives) and [PEP 441](https://www.python.org/dev/peps/pep-0441/))，with this feature, when submitting jobs to spark is much more convinent for poetry-building projects~

**Comment by pedrocava** [comment]
We use poetry and need to package dependencies in a `.zip` to create an AWS Lambda layer. I've [found this post](https://chariotsolutions.com/blog/post/building-lambdas-with-poetry/) and it suggests this command:

```shell
poetry run pip install --upgrade -t package dist/*.whl
cd package 
zip -r ../artifact.zip . -x '*.pyc'
```

It works, apparently, but it'd sure be nice to have that wrapped in a single poetry command.

**Comment by mbelang** [comment]
In fact if you do that you will have a hard time as pip will upgrade all packages. You need to get dependencies from the lock file otherwise you will end up with discrepancies between poetry and aws.

Here is how we do it.

```shell
poetry export -f requirements.txt --without-hashes -o requirements.txt
poetry run pip install . -r requirements.txt -t package_tmp
cd package_tmp
find . -name "*.pyc" -delete
zip -r ../"$param_package_name" .
```

Agreed that the zip command could be optimized to removed `find` command

**Comment by mousedownmike** [comment]
With the help of this thread, I used `poetry export` and was able to use the `sam build` with a `Runtime: python3.9` in my Poetry Lambda project.
If this Zip output format gets implemented, it should make it possible to move to a Makefile build using the SAM CLI.

**Comment by Secrus** [comment]
As Poetry is complying with PEP 517, which defines building `sdist`s as tarballs ([link](https://peps.python.org/pep-0517/#build-sdist)) and `*.tar.gz` is *de facto* standard in Python community, we won't be providing such functionality in foreseeable future. If the situation changes and some new standardization documents appear allowing other formats, Poetry will comply. Until then, I deem this discussion resolved.
