### ISSUE TITLE
parsing issue when we have extras with poetry add

### ISSUE THREAD

**Issue by ycd** [python-poetry/poetry#2980]
I mentioned this problem in #2782 but it still occurs in version **1.0.10**

@abn approved it's a bug in parsing, see [here](https://github.com/python-poetry/poetry/issues/2782#issuecomment-671458256)

### Reproducing the problem

When we have space after comma it can't parses the rest of extras. 

```python
poetry add databases[postgresql, sqlite]

[ValueError]
Could not find a matching version of package databases[postgresql,
```

It works perfectly fine without a space.

```python
poetry add databases[postgresql,sqlite]
Using version ^0.3.2 for databases
```

**Comment by ycd** [comment]
Thanks for such a quick fix @finswimmer , @abn

**Comment by abn** [comment]
@ycd thank you for testing and reporting. :)
