### ISSUE TITLE
poetry add python-i18n[YAML]

### ISSUE THREAD

**Issue by CarolHsu** [python-poetry/poetry#2992]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
probably relates to #79 

## Issue

So I encounter a weird issue with [python-i18n](https://github.com/danhper/python-i18n), I noticed that it installs with `extras(require_extras)` `pyyaml`, but it doesn't really load `i18n.loaders.yaml_loader` on my end.

you can probably re-present this issue by

```
$ poetry add python-i18n[YAML]
$ poetry run python3

import i18n
i18n.loaders.yaml_loader 
> #AttributeError: module 'i18n.loaders' has no attribute 'yaml_loader'

---
$ pip3 install python-i18n[YAML]
$ python3

import i18n
i18n.loaders.yaml_loader 
```

Please do advice, appreciate!

**Comment by abn** [comment]
@CarolHsu can you try with the latest preview?

**Comment by CarolHsu** [comment]
yes, that works!
