### ISSUE TITLE
keep old line breaking in toml files

### ISSUE THREAD

**Issue by Trim21** [python-poetry/poetry#2993]
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

I keep pyproject.toml and lock file in my code repo with \n as eol. but poetry will always make it crlf on Windows, it's pretty annoying.

create a pr in https://github.com/sdispater/tomlkit/pull/110

**Comment by abn** [comment]
@Trim21 happy to see a PR to preserve line endings.  But I suspect change might be in `tomlkit`.

**Comment by Trim21** [comment]
@abn I'm not sure if `tomlkit` should take care of line breaking... :thinking:

**Comment by finswimmer** [comment]
Should be fixed by tomlkit.

**Comment by trim21** [comment]
this is broken.

Can maintainers re-open this issue?

**Comment by trim21** [comment]
this is broken again,, can we re-open this issue?

```text
❯❯ ~\..\..\poetry-plugin-bump git:(master) poetry --version
Poetry (version 1.6.1)
❯❯ ~\..\..\poetry-plugin-bump git:(master) file poetry.lock
poetry.lock: ASCII text
❯❯ ~\..\..\poetry-plugin-bump git:(master) poetry lock
Updating dependencies
Resolving dependencies...

Writing lock file
❯❯ ~\..\..\poetry-plugin-bump git:(master) file poetry.lock
poetry.lock: ASCII text, with CRLF line terminators
```

**Comment by dimbleby** [comment]
No.  #7527.
