### ISSUE TITLE
"AssertionError: assert by_ref[ref] is not None" with previously working pyproject.toml

### ISSUE THREAD

**Issue by konstin** [python-poetry/poetry#3016]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate. _There are similar bug reports, but all for older versions_
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 20.04
- **Poetry version**: 1.1.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/konstin/8d8c412fdd1ed76e2c42cea8e444f891

## Issue

After updating to poetry 1.1.0, poetry fails with an AssertionError. You can reproduce this by adding the pyproject.toml linked above to an empty directory and running `poetry install`.

### Logs

After `1: Version solving took 0.600 seconds.` and `1: Tried 1 solutions.`, I get:

```
  AssertionError

  

  at ~/.poetry/lib/poetry/mixology/incompatibility.py:60 in __init__
       56│                     # intersection, they're mutually exclusive, making this incompatibility
       57│                     # irrelevant, since we already know that mutually exclusive version
       58│                     # ranges are incompatible. We should never derive an irrelevant
       59│                     # incompatibility.
    →  60│                     assert by_ref[ref] is not None
       61│                 else:
       62│                     by_ref[ref] = term
       63│ 
       64│             new_terms = []
```

**Comment by abn** [comment]
@konstin `poetry add --lock django-anymail@^7.2` should resolve your issue.

**Comment by tony** [comment]
@abn If we do that, then the `extras` don't show in pyproject.toml (in my case, I would need those), would the workaround also include extras?

**Comment by tony** [comment]
I made an issue at #3017 - same error message - but I'm not sure if it's related (at the core of things) or not yet.

I added a full traceback via `-vvv`.  Please feel free to close #3017 if its a duplicate / handled via this issue

Thank you!

**Comment by aaaaahaaaaa** [comment]
@abn Any recommendation for a workaround while waiting for 1.2 to be released? This is currently breaking multiple of our pipelines.

**Comment by abn** [comment]
@aaaaahaaaaa we will be releasing a bug fix release `1.1.1` soon :)

**Comment by aaaaahaaaaa** [comment]
@abn Any rought ETA?

**Comment by abn** [comment]
@aaaaahaaaaa if the current open bugfix PRs get reviewed and verified,  this weekend. Otherwise early next week.

**Comment by cuducos** [comment]
For those with broken pipelines: downgrading to 1.0.10 (`poetry self update 1.0.10`) did the trick for me. So I can wait withj green pipelines until 1.1.1 is rolled out : )
