### ISSUE TITLE
CANNOT UNINSTALL POETRY

### ISSUE THREAD

**Issue by rarenatoe** [python-poetry/poetry#3021]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: MacOS 10.15.7
- **Poetry version**: 1.1.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: No idea what this is, I just installed poetry.

## Issue
I installed poetry through:
`curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -`

but shortly after I got the following message when getting the version through `poetry --version`:

> Python 2.7 will no longer be supported in the next feature release of Poetry (1.2).
> You should consider updating your Python version to a supported one.

So I tried to run:
`curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3 -`

But I got this:
> Latest version already installed.

So I tried running this, as specified in the docs:
`python get-poetry.py --uninstall`

BUT I GOT THIS:
`/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'get-poetry.py': [Errno 2] No such file or directory`

Please at the very least I want to get my computer to the way it was before. I didn't know this software was so faulty.

**Comment by severinsimmler** [comment]
You have to make sure that the file `get-poetry.py` actually _exists_ on your machine. The error you got says it doesn't. So what about:

```
$ wget https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py
$ python get-poetry.py --uninstall
```

**Comment by severinsimmler** [comment]
And actually this software isn't that faulty at all.

**Comment by rarenatoe** [comment]
thanks! that solved it. I guess it was my fault for assuming the installation would get the file to my computer.
