### ISSUE TITLE
Poetry prints tracebacks to stdout

### ISSUE THREAD

**Issue by remram44** [python-poetry/poetry#3025]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- ~~If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).~~

- **OS version and name**: linux, probably affects all
- **Poetry version**: 1.1.0
- ~~**Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**:~~

## Issue

Poetry prints tracebacks to stdout. This is problematic because some commands are meant to be piped, for example `poetry export`.

See #3023: running `poetry export --format requirements.txt >requirements.txt` currently fails but the traceback goes in the file.

**Comment by iksteen** [comment]
While I agree that errors should go to stderr, you can use the `--output requirements.txt` option to not have to rely on redirection.

**Comment by christopherpickering** [comment]
This seems like it was fixed in release [1.8](https://python-poetry.org/history/#118---2021-08-19)?

**Comment by dimbleby** [comment]
> This seems like it was fixed 

yes, can be closed
