### ISSUE TITLE
package = repository.find_packages(dependency=dependency)[0]

### ISSUE THREAD

**Issue by faylor** [python-poetry/poetry#3044]
Builds are now failing due to change in Poetry version 1.1.0:
At: exporter.py:76
Error: List index out of range.
Running bash command: poetry export -f requirements.txt 

Works perfectly when revert to v1.0.10.

**Comment by andreevdanil** [comment]
Duplicate: https://github.com/python-poetry/poetry/issues/3043

**Comment by faylor** [comment]
Sorry, clearly dupe.
