### ISSUE TITLE
Unhelpful stack traces in `poetry install`

### ISSUE THREAD

**Issue by matejcik** [python-poetry/poetry#3050]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Linux Mint 20, Python 3.8.2
- **Poetry version**: 1.1.0, master

## Issue
When encountering a bug, the displayed stack trace is less than helpful.

For example, when debugging #3049, the following (and nothing else) is shown regardless of the number of `-vvvvvv`s on the command line:

![image](https://user-images.githubusercontent.com/596073/94917366-b2799600-04b0-11eb-9eb1-0398e783bdf3.png)

Getting an actual stack trace seems impossible without changing code of the exception handler in `installation/executor.py`

**Comment by Secrus** [comment]
Stack traces are now not showing after change in [`cleo`](https://github.com/python-poetry/cleo).
