### ISSUE TITLE
Pass --prompt to be project name

### ISSUE THREAD

**Issue by Tadaboody** [python-poetry/poetry#3055]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

Currently the prompt is either way too long in the case of generated global venvs, or useless in the case of `.venv`.  
Virtualenv already supports passing `--prompt` to customize this, so I propose using the project name.  

I do not use `poetry env` or anything other than one venv per project, so I'm open to propositions on other customization options.

**Comment by abn** [comment]
Maybe project name name and python version might be appropriate.

**Comment by Tadaboody** [comment]
Saw you added `Good First Issue` - already implementing ^_^

**Comment by Tadaboody** [comment]
Also my gripe with having `{name} {version}` is that some prompts (like [starship](github.com/starship/starship) which I use) already display the python version :/
<img width="548" alt="image" src="https://user-images.githubusercontent.com/6463334/94959884-9e5a8680-04fa-11eb-99e6-3d72430386ed.png">

Actually I can configure that in starship so it's not that bad :U

**Comment by abn** [comment]
The only reason why I mention the python version (atleast major and minor) is that majority shells do not have that :). The promt could just be something like `py37`. 

This could in theory be also configurable in `poetry config virtualenvs.prompt {project}-py{python}`. See other configurations for using templates.
