### ISSUE TITLE
ModuleNotFoundError: No module named 'cleo'

### ISSUE THREAD

**Issue by gh640** [python-poetry/poetry#3071]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **Mac OS X / 10.14.6 / 18G5033**: 
- **1.1.0**: 

## Issue

After updating poetry to 1.1.0 with `poetry self update`, it stopped working. I cannot run even `poetry --version` now.

```bash
$ poetry self update
Updating to 1.1.0
 - Downloading poetry-1.1.0-darwin.tar.gz 100%

Poetry (1.1.0) is installed now. Great!

$ poetry
Traceback (most recent call last):
  File "/Users/username/.poetry/bin/poetry", line 12, in <module>
    from poetry.console import main
  File "/Users/username/.poetry/lib/poetry/console/__init__.py", line 1, in <module>
    from .application import Application
  File "/Users/username/.poetry/lib/poetry/console/application.py", line 3, in <module>
    from cleo import Application as BaseApplication
ModuleNotFoundError: No module named 'cleo'

$ poetry --version
Traceback (most recent call last):
  File "/Users/username/.poetry/bin/poetry", line 12, in <module>
    from poetry.console import main
  File "/Users/username/.poetry/lib/poetry/console/__init__.py", line 1, in <module>
    from .application import Application
  File "/Users/username/.poetry/lib/poetry/console/application.py", line 3, in <module>
    from cleo import Application as BaseApplication
ModuleNotFoundError: No module named 'cleo'
```

I searched for an issue but couldn't find one. #2991 was for a different problem.

**Comment by gh640** [comment]
`poetry -vvv` generates the following output:

```bash
$ poetry -vvv
Traceback (most recent call last):
  File "/Users/username/.poetry/bin/poetry", line 12, in <module>
    from poetry.console import main
  File "/Users/username/.poetry/lib/poetry/console/__init__.py", line 1, in <module>
    from .application import Application
  File "/Users/username/.poetry/lib/poetry/console/application.py", line 3, in <module>
    from cleo import Application as BaseApplication
ModuleNotFoundError: No module named 'cleo'
```

**Comment by gh640** [comment]
I needed to use Poetry soon and re-installed it.

```bash
python get-poetry.py --uninstall
python get-poetry.py
```

The error has gone.

I hope this helps other people.

**Comment by laike9m** [comment]
Same here

**Comment by Hultner** [comment]
I had to do the same thing after adding python 3.9 to my pyenv and update poetry, re-install was the only thing that would do it.

**Comment by MamadouSDiallo** [comment]
I had the same problem after updating to python 3.9 but the issue went away after "pip install --user poetry". Note that I use python through pyenv.

**Comment by paulmattheww** [comment]
> I needed to use Poetry soon and re-installed it.
> 
> ```shell
> python get-poetry.py --uninstall
> python get-poetry.py
> ```
> 
> The error has gone.
> 
> I hope this helps other people.

Of course you'll need the file as such

```bash
curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
```

**Comment by laike9m** [comment]
This still happens

**Comment by tomjohnburton** [comment]
I'm getting this error running ubuntu all of a sudden

**Comment by plyte** [comment]
> I'm getting this error running ubuntu all of a sudden

I'm getting the same after using:
`curl -sSL --proxy $https_proxy https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python`

**Comment by plyte** [comment]
> For me, changing the python version back to `3.9.7` fixed the issued. I was running `poetry` in a Docker container. Using this as the base fixed it:
> 
> ```
> FROM python:3.9.7-bullseye
> ...
> ```

Ah ok I'll give that shot. I've been using the python:slim container which I believe is on 3.9.5

**Comment by anpr** [comment]
I use python with pyenv, and experienced the same issue if I tried to run poetry with Python 3.10.

I fixed it with 
```
$ curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py > get-poetry.py
$ pyenv local 3.9.9
$ python get-poetry.py --uninstall
$ python get-poetry.py
```

It seems like there is maybe a bug in poetry if it's run with Python 3.10?

**Comment by Ben-Hampson** [comment]
@anpr I struggled to get this working on Python 3.10 too. The following worked:

`pip install cleo tomlkit poetry.core requests cachecontrol cachy html5lib pkginfo virtualenv lockfile`

**Comment by nazmicancalik** [comment]
@Ben-Hampson Same for me. All of a sudden my poetry also stopped working, I was running system update on arch at the time and it updated python from 3.9 to 3.10 and I think this was the reason why it stopped working. I installed the required packages like you and it started working again.

**Comment by SamCrabtree** [comment]
> @anpr I struggled to get this working on Python 3.10 too. The following worked:
> 
> `pip install cleo tomlkit poetry.core requests cachecontrol cachy html5lib pkginfo virtualenv lockfile`

Thank you @Ben-Hampson . After searching for a solution for over 2 hours this seemed to do the trick!

**Comment by moattarwork** [comment]
> > @anpr I struggled to get this working on Python 3.10 too. The following worked:
> > `pip install cleo tomlkit poetry.core requests cachecontrol cachy html5lib pkginfo virtualenv lockfile`
> 
> Thank you @Ben-Hampson . After searching for a solution for over 2 hours this seemed to do the trick!

It is working but if you spawn a new shell, that will be the same and you need to run the command again

**Comment by rosbly** [comment]
I got this error and though it was a bug, until I figured out I was within a Poetry shell/virtual env (which is automatically activated by Pycharm).

Everything works fine outside Poetry shell.

```bash
$ poetry run poetry --version
Traceback (most recent call last):
  File "/home/syr/.poetry/bin/poetry", line 17, in <module>
    from poetry.console import main
  File "/home/syr/.poetry/lib/poetry/console/__init__.py", line 1, in <module>
    from .application import Application
  File "/home/syr/.poetry/lib/poetry/console/application.py", line 3, in <module>
    from cleo import Application as BaseApplication
ModuleNotFoundError: No module named 'cleo'

$ poetry --version
Poetry version 1.1.12
```

Maybe Poetry should do like Pipenv: detect this situation, print a warning, and execute outside the virtualenv?
This is very unlikely anyone would want to execute Poetry within Poetry (except maybe for Poetry developers, in which case some opt-in option could be handy).

**Comment by vuongtuha** [comment]
@Ben-Hampson thank you. Solve after 1 year!
