### ISSUE TITLE
Poetry Never Updates pywin32

### ISSUE THREAD

**Issue by adam-grant-hendry** [python-poetry/poetry#3077]
- [x ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows 10, version 1909
- **Poetry version**: 1.1.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue

`poetry update` always attempts to update `pywin32`, but never does. Every new install lists `pywin32` as requiring update

```
>>> poetry update
Updating dependencies
Resolving dependencies...

Package operations: 0 installs, 1 update, 0 removals

  • Updating pywin32 (228 C:/Code/project/.venv/Lib/site-packages/pythonwin -> 228)
```

The `pyproject.toml` file is as follows:

```
[tool.poetry]
name = "project"
version = "0.1.0"
description = "test"
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.19.2"
matplotlib = "^3.3.2"
pywin32 = "^228"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
flake8 = "^3.8.4"
pytest = "^6.1.1"
pylint = "^2.6.0"
jupyter = "^1.0.0"
notebook = "^6.1.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

I am running Python 3.8.6.

**Comment by adam-grant-hendry** [comment]
Reverting `poetry` to version `1.0.10` resolves this issue, but it is still uncertain to me why this occurs with version `1.1.0`.

**Comment by abn** [comment]
Have you tried re-creating the virtual environment?

**Comment by adam-grant-hendry** [comment]
Recreating the venv, I still have the error. Not working now with 1.0.10 either.

**Comment by adam-grant-hendry** [comment]
Occurs in version 1.1.1 as well.

**Comment by rajuah** [comment]
I see this as well starting with version `1.1.0`
Updating to `1.1.1` didnt resolve the issue

**Comment by jgentil** [comment]
I have this same problem.  Following for solution...

**Comment by jgentil** [comment]
Actually mine is slightly different.  It *always* tries to upgrade it, even if it's the same version.  I see the same thing you do though, and I feel like that's also what you're experiencing.  It has version 228 installed, but tries to update to version 228 for some reason.

**Comment by absassi** [comment]
It seems this is due to pywin32 installing a `pywin32.pth` file in site-packages, which causes Poetry to think it is installed in develop mode (and also that's why the "Updating" line it prints has a path) and thus needs to be reinstalled in non-develop mode.

**Comment by adam-grant-hendry** [comment]
@jgentil Yes, you are correct. My error is the same as yours. It always tries to "update" from 228 to 228, but nothing ever seems to get resolved (it continues to do this every time I run `poetry install` or `poetry update`).

@absassi Is the `pywin32.pth` file necessary? I could delete the file locally and see if this resolves the issue, but then somone would need to create a pull request to `pywin32` to remove the file from being downloaded. Is it needed for anything else?

**Comment by wlievens** [comment]
I get this issue too.

**Comment by abn** [comment]
@absassi @adam-grant-hendry can one of you give me a tree listing of your `site-packages` directory where `pywin32` gets installed please?

My guess is that this check is incomplete somehow.

https://github.com/python-poetry/poetry/blob/3b3791d3cac8b7d583699ac28086c10dc850b370/poetry/repositories/installed_repository.py#L137-L149

**Comment by haenry** [comment]
There are quite a few folders. The actual one should be the last I guess.
```
~~win32_system32
~-win32_system32
~ywin32_system32

pywin32_system32
```
all contain
```
pythoncom37.dll
pywintypes37.dll
```

This is the error-message
```
Installing collected packages: pywin32
    Attempting uninstall: pywin32
      Found existing installation: pywin32 228
      Uninstalling pywin32-228:
        Successfully uninstalled pywin32-228
  ERROR: Could not install packages due to an EnvironmentError: [WinError 5] Access denied: 'c:\\users\\me\\\appdata\\local\\pypoetry\\cache\\virtualenvs\\project-5vzw2i23-py3.7\\lib\\site-packages\\~ywin32_system32\\pythoncom37.dll'
  Consider using the `--user` option or check the permissions.



  at ~\.poetry\lib\poetry\utils\env.py:948 in _run
       944│                 output = subprocess.check_output(
       945│                     cmd, stderr=subprocess.STDOUT, **kwargs
       946│                 )
       947│         except CalledProcessError as e:
    →  948│             raise EnvCommandError(e, input=input_)
       949│
       950│         return decode(output)
       951│
       952│     def execute(self, bin, *args, **kwargs):```

**Comment by abn** [comment]
@haenry the error message is interesting. So it seems pip is unable uninstall the existing packages. I believe this is a seperate issue to the one reported (albeit definitely related).

Is the file `pythoncom37.dll` link? Or does it have any permissions set? Also, can you try manually removing the package? `poetry run pip uninstall pywin32` ?

**Comment by haenry** [comment]
No, they are regular files. Permissions are 
```
Path                     Owner         Access
----                      -----           ------
pythoncom37.dll  ME             NT-AUTHORITY\SYSTEM Allow  FullControl...
pywintypes37.dll  ME             NT-AUTHORITY\SYSTEM Allow  FullControl...
```
same as other files in site-packages

`poetry run pip uninstall pywin32` removes the package but cannot remove the `pythoncom37.dll` (` Successfully uninstalled pywin32-228` and then the `Acces denied` is thrown)
Afterwards the poetry install runs normally once and installs pywin32 again. Then it returns to the loop updating 228 -> 228.

**Comment by alimantu** [comment]
Same issue here.

**OS version and name:** Windows 10 Pro, Build 19041
**Poetry version:** 1.1.2

**Comment by jgentil** [comment]
Something to try:  Make sure you aren't running `poetry install` from inside a `poetry shell` or have an active poetry shell running.

Moving out of the shell fixed it for me.  I had to stop _all_ instances of the shell though.

**Comment by abn** [comment]
Dug into this a further. Found the root cause.

https://github.com/python-poetry/poetry/blob/20a3161b0e3f417f04b833c192dcb72076098a4b/poetry/repositories/installed_repository.py#L141-L148

We seem to be assuming that a package is a "path" package because the `.pth` file lists multiple paths but none of them are vcs pakcages. The else block should only set `source_type = "directory"` if at least one of the paths listed is outside the site package directories (ie. editable package).

**Comment by abn** [comment]
Can you please try the fix at #3210.

### Using pipx
```sh
pipx install --suffix=@3210 'poetry @ git+https://github.com/python-poetry/poetry.git@refs/pull/3210/head'
```

**Comment by natehawkboss** [comment]
I am still seeing this issue in 1.1.4.

I will point out that it is when I have this line in the file:
`pywin32 = {version = "^228", platform = "win32"}`

Every single time it updates or installs a package, it then tries to update this one which it cannot because it runs into that permission error.

**Comment by wlievens** [comment]
Same here, still seeing this issue, is there a workaround?
I also get all sorts of spurious acess denied errors in windows from poetry which seem to be related...

**Comment by abersheeran** [comment]
WSL and Windows10, poetry 1.1.4. Same bug.

**Comment by sinoroc** [comment]
> WSL

WSL? You can not install `pywin32` on WSL, can you?

**Comment by abersheeran** [comment]
Command "poetry update" error, not "pip install pywin32" error.



---Original---

**Comment by jaepil-choi** [comment]
The issue still persists. I should not have updated poetry.
