### ISSUE TITLE
poetry install: `--no-ansi` uses non-ascii character ( `•` - `\u2022` - `BULLET`)

### ISSUE THREAD

**Issue by NovemberOscar** [python-poetry/poetry#3078]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 16.04 on Docker
- **Poetry version**: 1.1.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: Unable to expose due to company's security policy

## Issue

I got an this message from docker

```
Step 11/15 : RUN poetry config virtualenvs.create false   && poetry install --no-interaction --no-ansi
 ---> Running in 3956f57f28cd
Skipping virtualenv creation, as specified in config file.
Installing dependencies from lock file

Package operations: 80 installs, 1 update, 0 removals


  UnicodeEncodeError

  'ascii' codec can't encode character '\u2022' in position 2: ordinal not in range(128)

  at ~/.pyenv/versions/3.6.2/lib/python3.6/site-packages/clikit/io/output_stream/stream_output_stream.py:24 in write

  UnicodeEncodeError

  'ascii' codec can't encode character '\u2022' in position 2: ordinal not in range(128)

  at ~/.pyenv/versions/3.6.2/lib/python3.6/site-packages/clikit/io/output_stream/stream_output_stream.py:24 in write
The command '/bin/sh -c poetry config virtualenvs.create false   && poetry install --no-interaction --no-ansi' returned a non-zero code: 1
```

then I ran same command on macbook (iTerm2) and I could see a `BULLET`(\u2022) character. I searched about `BULLET` character on google and it is not an ascii character. 

Printing non ascii character `BULLET` in `--no-ansi` mode seems to be fixed.

```
🕙 15:41:15 
❯ poetry install --no-interaction --no-ansi                                                                 
Installing dependencies from lock file

Package operations: 20 installs, 0 updates, 0 removals

  • Installing asynctest (0.13.0): Pending...  • Installing coverage-badge (1.0.1): Pending...  • Installing emoji (0.5.4): Pending...  • Installing faker (2.0.5): Pending...  • Installing fastpbkdf2 (0.2): Pending...  • Installing freezegun (0.3.15): Pending...  • Installing <secret> (0.0.2): Pending...  • Installing <secret> (0.1.5): Pending...  • Installing <secret> (0.3.2): Pending...  • I
```

**Comment by Fuzi0n** [comment]
I confirm this issue with ``

**Comment by abn** [comment]
@NovemberOscar have you seen https://github.com/python-poetry/poetry/issues/1427#issuecomment-537260307? I am curious if the root cause is the same here.

**Comment by NovemberOscar** [comment]
Oh. I never seen it before when I searched issue 🤔 I seems very similar (docker, encoding, clikit...) I will check again soon :)

**Comment by NovemberOscar** [comment]
@abn Thanks for letting me know! after I fixed container locale, poetry install succeed.

But as you know, most people don't specify locale in Dockerfile. Using `BULLET` is likely to cause problems for many people using poetry on docker(or any ascii only environment), so I suggest going back to dash symbol as it used to be.

**Comment by abn** [comment]
This is not really a poetry specific issue. And we use non ascii characters elsewhere too. 

https://click.palletsprojects.com/en/5.x/python3/#python-3-surrogate-handling

The issue here is the Ubuntu container. Additionally, this is a non issue for python 3.7.

**Comment by valeriiisotnyk** [comment]
Hello, if you're encountering such an issue, here are a few steps you might want to try.
`sudo locale-gen en_US.UTF-8`
Then
`sudo update-locale LANG=en_US.UTF-8`
