### ISSUE TITLE
PermissionError installing root package in 1.1.0

### ISSUE THREAD

**Issue by agoose77** [python-poetry/poetry#3079]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Docker (Ubuntu 20.04)
- **Poetry version**: 1.1.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/agoose77/5b08db26a49c8119a9a943583ef724b3
- **Link to a DockerFile**: https://gist.github.com/agoose77/647769f65494f6a82ffc3f625eca0457

## Issue
This issue follows from #2996 

The line that install the `dist-info` directory uses a single env directory: 

https://github.com/python-poetry/poetry/blob/ae6f574bcb32c42675e34238be6498d585efee4f/poetry/masonry/builders/editable.py#L190

 It seems to me like the fix would be similar to #3000

Thank you for all of the hard work Poetry team.

**Comment by abn** [comment]
Verified against the 1.1 branch.

```console
podman run --rm -i --entrypoint bash python:3.7 <<EOF
pip install --quiet git+https://github.com/python-poetry/poetry.git@1.1
adduser --disabled-password --gecos "User" --uid 1000 user
su - user
poetry new foobar
cd foobar
export PYTHONDONTWRITEBYTECODE=1
export POETRY_VIRTUALENVS_CREATE=0
poetry install -vvv
EOF
```

**Comment by abn** [comment]
@agoose77 can you try #3107 please?

**Comment by agoose77** [comment]
@abn this passes my existing build-step test. Thanks for the quick turn around!
