### ISSUE TITLE
key for sequential installation

### ISSUE THREAD

**Issue by Ver1Sus** [python-poetry/poetry#3087]
The new version of Poetry 1.1.1 installs dependency parallel - but this feature broke my programm

I use `websocket` and `websocket-client`, where `websocket-client` extends `websocket` by replacin  `__init__.py` and redefines WebSocket class, adding ssl support. 

In version 1.0.0 I installed `websocket` -> `websocket-client`, but now, in CI during rpm creation, the libraries were installed as `websocket-client` -> `websocket`, and after that, rpm has the old `WebSocket` class without ssl support

**Comment by abn** [comment]
@Ver1Sus shouln't websocker-client depend on websocket? Or does it still order incorrectly when this is already the case?

**Comment by Ver1Sus** [comment]
> shouln't websocker-client depend on websocket?

Should, but it doesn't) I fixed this, by using `poetry config experimental.new-installer false` before `poetry install` - and installation become consistent.

So, this issue may be closed, but maybe need add some feature in `pyproject.toml` to set prioritet on the installed packages
