### ISSUE TITLE
poetry build wheel file. not found top_level.txt

### ISSUE THREAD

**Issue by juyoung-yoo** [python-poetry/poetry#3093]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: MacOs 10.15.6

- **Poetry version**:  1.1.0b2

- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 
```
[tool.poetry]
name = "test-common"
version = "0.1.1"
description = ""
authors = ["juy@gmail.com"]
packages = [
    { include = "test-common", from = "src" },
]

[tool.poetry.dependencies]
python = "3.7.9"
pycryptodome = "^3.9.8"
twine = "^3.2.0"
poetry-setup = "^0.3.6"

[tool.poetry.dev-dependencies]
pytz = "2019.3"
mysqlclient = "^2.0.1"
pex = "^2.1.16"
pytest = "^6.0.2"
pyspark = "^3.0.1"
pyspark-stubs = "^3.0.0"
wheel = "^0.35.1"

[build-system]
requires = ["poetry-core>=1.0.0a5"]
build-backend = "poetry.core.masonry.api"
```
``` directory construct
my-dir
.
├── README.md
├── dist
│   ├── testcommon-0.1.1-py3-none-any.whl
│   └── testcommon-0.1.1.tar.gz
├── poetry.lock
├── pyproject.toml
├── requirements.txt
├── setup.py
├── src
│   ├── __init__.py
│   ├── __pycache__
│   └── testcommon
│       ├── __init__.py
│       ├── common.py
├── tests
│   ├── __init__.py
│   └── test_common.py
```

## Issue

Hi 
I build using poetry.
and `testcommon-0.1.1-py3-none-any.whl` file unpack.
I didn't found 'top_level.txt` file

**poetry build ** 
```
.
├── testcommon
│   ├── __init__.py
│   ├── common.py
└── testcommon-0.1.1.dist-info
    ├── METADATA
    ├── RECORD
    └── WHEEL
```

**setup.py build ** 
```setup.py
...
packages=setuptools.find_packages("src"),
package_dir={"": "src"},
... 
```

$ python3 setup.py sdist bdist_wheel
```
.
├── testcommon
│   ├── __init__.py
│   ├── common.py
└── testcommon-0.0.1.dist-info
    ├── METADATA
    ├── RECORD
    ├── WHEEL
    └── **top_level.txt**
```

I think, poetry can't find the package from pyproject.toml file.
How can i found packages. 

The reason why I need a file is Pex.

**Comment by finswimmer** [comment]
Hello @juyoung-yoo,

what is this `top_level.txt`? I cannot found anything about in [PEP 491](https://www.python.org/dev/peps/pep-0491/) which poetry follows when creating a wheel. I found some reference with google, but I'm not sure what is this file for and where it comes from.

fin swimmer

**Comment by brechtm** [comment]
I was also wondering why poetry-produced wheels don't include a *top_level.txt*. I couldn't find anything official on it either but I did find this mention in [A dive into packaging native python extensions](https://blog.schuetze.link/2018/07/21/a-dive-into-packaging-native-python-extensions.html):

> ``top_level.txt``: Setuptools also add this file which contains only the name of your package. This is part of the (PEP-less) egg format, the predecessor of wheels, as described in [The Internal Structure of Python Eggs](https://setuptools.readthedocs.io/en/latest/deprecated/python_eggs.html). This file is not documented and not needed for wheels and therefore not added by other packagers such as poetry. (Interestingly enough, the [wheel repository](https://github.com/pypa/wheel), which adds the ``bdist_whl`` command to setuptools, does not even contain the string ``top_level.txt``.)

**Comment by kreyoo** [comment]
There is a workaround:

1. Create a folder named <your_package_name>.egg-info
2. Create your top_level.txt in it
3. Add the folder to your package by using this in your pyproject.toml:
```
[tool.poetry]
...
include = [""<your_package_name>.egg-info/*""]
...
```
