### ISSUE TITLE
Poetry 1.1.x breaks mypy in a project with source dependencies

### ISSUE THREAD

**Issue by kkozmic** [python-poetry/poetry#3094]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: MacOS 10.16.5
- **Poetry version**: 1.1.1
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: [link](https://gist.github.com/kkozmic/4fda179ef45b3fa7a3ad542712603e07)

## Issue

This is an issue with mypy under `.venv` created with latest Poetry (v1.1.x) which works just fine if the `.venv` was created with older version (v1.0.10 or before)

Our project has two source dependencies on other internal projects.
After the upgrade (and re-creating the `.venv`) running `poetry run mypy .` produces a whole bunch of errors like:

```
error: Cannot find implementation or library stub for module named 'our_source_project1.something'
error: Cannot find implementation or library stub for module named 'our_source_project2.something_else'
````

Digging through the logs, diffs and then mypy source code I narrowed it down to this:

Under Poetry v1.0 a `.venv/lib/python3.8/site-packages/easy-install.pth` file gets created which contains paths to each of our code dependency projects.

Under Poetry v1.1 this file doesn't get created.

Thing is, mypy reads this specific file to find these source dependencies. ([source](https://github.com/python/mypy/blob/92e3f396b03c69c1d8abc249632bfd2db02350d0/mypy/modulefinder.py#L474-L479)).
Without it it doesn't know how to find them, hence the errors, and a broken build.

**Comment by finswimmer** [comment]
Hello @kkozmic,

is this related: https://github.com/python-poetry/poetry/issues/2194#issuecomment-703246165 ?

fin swimmer

**Comment by kkozmic** [comment]
hey @finswimmer 

Yeah, I looked at that solution, but if I understand it correctly, `mypy_path`/`MYPYPATH` adds other paths to scan by mypy.

That's not what I want - I want those additional dependencies to be treated as dependencies, not as my project code.

Additionally, running mypy with `mypy_path` added fails as it ignores these projects' own mypy settings. Trying to make my project's settings accommodate those dependencies (and keeping them up to date over time) is a recipe for a headache

**Comment by abn** [comment]
@kkozmic I am guessing in this scenario your dependencies are poetry projects installed with `develop = true`? If so, they should be still written to `package-name.pth` instead of `easy-install.pth`

**Comment by abn** [comment]
Just read your pypt, this is actually https://github.com/python-poetry/poetry/issues/3086.

**Comment by kkozmic** [comment]
> Just read your pypt, this is actually #3086.

OK? I saw that issue before submitting this one, and it looked related, albeit concerned with race conditions whereas my problem is broken mypy.

> I am guessing in this scenario your dependencies are poetry projects installed with `develop = true`?

We've got `tag = something` and `branch = something`. Not sure how that affects things.

**Comment by kkozmic** [comment]
I tried it with `poetry config experimental.new-installer false --local` and that doesn't seem to affect this particular problem. Only rolling back to v1.0.10 fixed it

**Comment by abn** [comment]
@kkozmic I was on my mobile. So looking at the `mypy` code; it seems they should really be [loading all `pth` files](https://docs.python.org/3/library/site.html) as `easy-install.pth` is only guaranteed by `setuptool` installs and as a consequence `pip`. In a PEP 517 world; this is a broken assumption I feel.

**Comment by kkozmic** [comment]
Right, so you're basically saying it's more or a mypy bug than Poetry.

> EDIT2: Would be great to get a sample project to test this.

I'd have to put something together from scratch as obviously I can't use our production code. I'll look into it over the cming weekend

**Comment by abn** [comment]
> Right, so you're basically saying it's more of a mypy bug than Poetry (which is fair enough).

Yes. However, if there is anything we can do to keep things compatible, I am happy to look into it. We can, at least for `1.1` play nice and write to `easy-install.pth` as well if there are no undesired side-effects.

> I'd have to put something together from scratch as obviously I can't use our production code. I'll look into it over the coming weekend

Awesome. That would make things easier to triage/decide.

**Comment by kkozmic** [comment]
> Yes. However, if there is anything we can do to keep things compatible, I am happy to look into it

Awesome, and I appreciate it 👏

**Comment by kkozmic** [comment]
So I got carried away and created a reproduction @abn 

```bash
git clone https://github.com/bug-repros/poetry-main
cd poetry-main
poetry install
make
```

This should work under Poetry 1.0.10 and fail under 1.1.1 with the error from OP.

**Comment by bryanforbes** [comment]
The next release of mypy (0.800) will [include a fix](https://github.com/python/mypy/pull/8847) for this, but I'm not sure when it will come out since 0.790 was just released today

**Comment by kkozmic** [comment]
No worries, I'll be keeping an eye out for it. Thanks @bryanforbes

**Comment by abn** [comment]
@kkozmic thank you for the reproducer. It is extremely helpful.

Had a quick look into this, and I am leaning towards not making any changes at the moment as I could not find any other cases where the `easy-install.pth` is expected/required in a similar fashion. And considering we expect a fix in `mypy`, adding an additional point of failure seems unwise. The `easy-install.pth` file is intended to be operated on only by `setuptools` and with that in mind, poetry writing to it and removing lines from it might end up creating more problems than it solves.

If anyone has a compelling case other than `mypy` that will also beneifit from this, please do list it here.

**Comment by bryanforbes** [comment]
My only suggestion would be to add a flag to optionally generate `easy-install.pth`. Right now, I'm using [a script](https://github.com/bryanforbes/Erasmus/blob/d73508a861712760d92f3c2b7426976b163ffc6c/fix-poetry.sh) to generate `easy-install.pth` and I have to add it to a few of my projects and remember to run it. I understand, though, if you decide against it.

**Comment by kkozmic** [comment]
Fair call @abn . Now 🤞 mypy 0.800 gets released soon so I can upgrade :partyparrot:

**Comment by edmondo1984** [comment]
Can the problem I have be related to this issue https://stackoverflow.com/questions/65512870/mypy-failing-on-test-source-folders-because-of-absence-of-type-hints-or-library?noredirect=1#comment115833764_65512870 ?

**Comment by andrewtemme** [comment]
I just found this issue today when I started running into the problem. Looks like MyPy v.0.800 was released today, 22 Jan 2021. I'm getting this error with the new 0.800 version.

**Comment by dimbleby** [comment]
works fine with latest poetry / mypy - dunno which is fixed but this seems good now
