### ISSUE TITLE
Duplicate entries when running poetry update --dry-run

### ISSUE THREAD

**Issue by MarcoGlauser** [python-poetry/poetry#3097]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 20.04
- **Poetry version**: 1.1.1
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/MarcoGlauser/804cbf48001f7a7d1d94d6da9bc88071

## Issue
The command `poetry update --dry-run` duplicates the output of packages as seen below.
![image](https://user-images.githubusercontent.com/924855/95180307-173f3400-07c2-11eb-917d-230097698155.png)

I first noticed it in poetry 1.1.0. I could reproduce it on different machines with the attached gist.

**Comment by ahlaw** [comment]
Hi, can I take this issue? I think I found the problem, when the `_dry_run` attribute is set, the executor writes after passing the `_should_write_operation` check [here](https://github.com/python-poetry/poetry/blob/6a96dd22f4cf22f6f6d5bdb36c44c02097d57bee/poetry/installation/executor.py#L181) and then again inside `_do_execute_operation` [here](https://github.com/python-poetry/poetry/blob/6a96dd22f4cf22f6f6d5bdb36c44c02097d57bee/poetry/installation/executor.py#L264). `_dry_run` should be removed from one of those checks.

**Comment by abn** [comment]
@ahlaw most definitey! Feel free to create a draft PR for this if you want to discuss a solution.
