### ISSUE TITLE
Fail resolving nested git dependencies 1.1.*

### ISSUE THREAD

**Issue by lgelmi** [python-poetry/poetry#3102]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 18.04 and MacOs 10.15.7
- **Poetry version**: 1.1.*.
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/lgelmi/82142f2e092b698b8c06de6302401c9b

## Issue
Poetry fails resolving dependencies with the following message:
```
...
   1: conflict: package_b (2.4.1 git rev master) depends on package_a (0.1.15 git rev master)
   1: ! not package_a (0.1.15 git rev master) is satisfied by package_a (0.1.15 git branch master)
   1: ! which is caused by "package_c depends on package_a (0.1.15 git branch master)"
   1: ! thus: package_b is forbidden
   1: ! package_b (2.4.1 git rev master) is satisfied by package_b (2.4.1 git branch master)
   1: ! which is caused by "package_c depends on package_b (2.4.1 git branch master)"
   1: ! thus: version solving failed
...
```

As you can see package_c depends both on a and b, and b depends on a. 
This should not cause any error since they do not conflict and, as a matter of fact, in version 1.0.* it did not.

Sadly, the repos are private and I cannot provide them, but they are python packages managed with poetry themselves.

**Comment by abn** [comment]
@lgelmi can you try #3105 pelase?

**Comment by lgelmi** [comment]
I installed version 1.1.2 (which includes the PR, as far as I understand) and still have the issue. 
The error message has minimal differences (package_a "rev" became "branch") : 

```...
   1: conflict: package_b (2.4.1 git rev master) depends on package_a (0.1.15 git branch master)
   1: ! not package_a (0.1.15 git branch master) is satisfied by package_a (0.1.15 git branch master)
   1: ! which is caused by "package_c depends on package_a (0.1.15 git branch master)"
   1: ! thus: package_b is forbidden
   1: ! package_b (2.4.1 git rev master) is satisfied by package_b (2.4.1 git branch master)
   1: ! which is caused by "package_c depends on package_b (2.4.1 git branch master)"
   1: ! thus: version solving failed
...
```

Thanks for the swift answer btw! :D

**Comment by randallpittman** [comment]
I'm having a similar problem, I think.

Ref. also #3030.

 Poetry 1.1.2 doesn't like me installing both of these dependencies for my project:

```
nctemplate = {git = "https://gitlab.com/osu-nrsg/nctemplate-python.git"}
ncdataset = {git = "https://gitlab.com/osu-nrsg/ncdataset-python.git"}
```

nctemplate's `pyproject.toml` has the ncdataset git repo as a dependency, and poetry gives the following error when I try to include both and run `poetry update`:

```
  Because nctemplate (0.1.0 git rev master) depends on ncdataset (0.2.2 git branch master)
   and hpx-radar-recorder depends on ncdataset (0.2.2 git branch master), nctemplate is forbidden.
  So, because hpx-radar-recorder depends on nctemplate (0.1.0 git branch master), version solving failed.
```

**Comment by abn** [comment]
@lgelmi I suspect your issue is #3113. Try making sure that all projects refer the same source url.

**Comment by lgelmi** [comment]
Welp! That seems to have worked.
 
Thanks for your help.
