### ISSUE TITLE
Poetry using home folder pyenv version instead of current directory.

### ISSUE THREAD

**Issue by DustinMoriarty** [python-poetry/poetry#3103]
I am unable to get poetry to create an environment using the correct python version if there is a pyenv local version set in the home directory. Please see the output below.

I want poetry to use python 3.6.11 set by pyenv. However, it is using 3.6.9.

What python is available outside of poetry for 3.6?
```bash
$ python --version
Python 3.6.11
```

What python is poetry using for 3.6?
```bash
$ poetry run python --version
Python 3.6.9
```

Here is what pyenv sees outside of poetry.
```bash
$ pyenv version
3.6.11 (set by /home/vagrant/devel/signal-helper/.python-version)
3.7.8 (set by /home/vagrant/devel/signal-helper/.python-version)
3.8.5 (set by /home/vagrant/devel/signal-helper/.python-version)
```

Inside of poetry, pyenv only sees 3.7.8 as set by $PYENV_VERSION. This is odd, because I have $PYENV_VERSION set to null. Is poetry somehow running pyenv in some other shell somewhere?
```bash
$ poetry run pyenv version
3.7.8 (set by PYENV_VERSION environment variable)
```

Current poetry version info.
```bash
$ poetry --version
Poetry version 1.1.1
```

```bash
$ pyenv --version
pyenv 1.2.20-17-gc9eab47
```

Current poetry env setup.
```bash
poetry env list
signal-helper-iG4lzQ41-py3.6 (Activated)
signal-helper-iG4lzQ41-py3.7
```

Try to remove and reinstall the environment.
```bash
$ poetry env remove signal-helper-iG4lzQ41-py3.6 && poetry env use 3.6.11 && poetry run python --version
Deleted virtualenv: /home/vagrant/.cache/pypoetry/virtualenvs/signal-helper-iG4lzQ41-py3.6
Creating virtualenv signal-helper-iG4lzQ41-py3.6 in /home/vagrant/.cache/pypoetry/virtualenvs
Using virtualenv: /home/vagrant/.cache/pypoetry/virtualenvs/signal-helper-iG4lzQ41-py3.6
Python 3.6.9
```
I finally determined that in my home directory, I had a pyenv local setting.
```bash
$ cat ~/.python-version
3.7.8
```

I then removed the local setting in home.
```bash
$ rm ~/.python-version && poetry env use 3.6.11 && poetry run python --version
Recreating virtualenv signal-helper-iG4lzQ41-py3.6 in /home/vagrant/.cache/pypoetry/virtualenvs/signal-helper-iG4lzQ41-py3.6
Using virtualenv: /home/vagrant/.cache/pypoetry/virtualenvs/signal-helper-iG4lzQ41-py3.6
Python 3.6.11
```

Now everything works. However, I don't think this is expected behavior. Why is pyenv in poetry looking at the home directory first instead of the current directory?

It looks like the poetry run shell still is pointed to the current directory instead of the home directory, so I am not sure why pyenv would be any different.

```bash
$ poetry run echo $PWD
/home/vagrant/devel/signal-helper
```

**Comment by ryancausey** [comment]
Can confirm I just ran into this same issue.

**Comment by finswimmer** [comment]
Hello,

Poetry does not have any dedicated support for pyenv. Since Poetry 1.2 there is an (experimental) option [virtualenvs.prefer-active-python](https://python-poetry.org/docs/configuration/#virtualenvsprefer-active-python-experimental) that, if set to `true`, enables Poetry to find the current activate python and use it to create the new venv.

fin swimmer
