### ISSUE TITLE
Be able to explicit the path to the pyproject

### ISSUE THREAD

**Issue by ericriff** [python-poetry/poetry#3122]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request
It would be very useful to be able to be explicit about the location of the `pyptoject` file when you invoke `poetry`. This allows you, for example, to invoke poetry from an arbitrary location. Or haev multiple `pyproject`s for a given project, if that is what you need. 

`pipenv` does something similar to this through the env variable `PIPENV_PIPFILE`.

Thanks,

Eric.

**Comment by finswimmer** [comment]
Hello @ericriff,

there is already a feature request for this here: https://github.com/python-poetry/poetry/issues/2179

fin swimmer

**Comment by ericriff** [comment]
I missed it. Sorry about that.

Thanks Fin.
