### ISSUE TITLE
ssl module in Python is not available

### ISSUE THREAD

**Issue by natea** [python-poetry/poetry#3126]
I'm unable to install Poetry due to this SSL error.

- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Issue

When I try to install Poetry on Python3, I get the following error:

```
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/poetry/
  Could not fetch URL https://pypi.org/simple/poetry/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/poetry/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
  Could not find a version that satisfies the requirement poetry (from versions: )
No matching distribution found for poetry
pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
```

**Comment by abn** [comment]
@natea I don't think this has anything to do with poetry. Seems like an issue with your python installation. I have seen this before in some OSX machines due to extra flags being required when installing python via brew.

Effectively the error is pip is unable to talk to pypi .

**Comment by swamper123** [comment]
@natea I can confirm that this is a python installation problem where the ssl library is missing (has to be installed before installing the python version).
