### ISSUE TITLE
Poetry links to python3 and not python3.x

### ISSUE THREAD

**Issue by ericriff** [python-poetry/poetry#3134]
- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 16
- **Poetry version**: 1.1.1

## Issue
I have multiple versions of `python3` on my system and I use `update-alternatives` to choose where `python3` points to.

I specify the desired python version for each project in the `pyproject` file as follows:
```
[tool.poetry.dependencies]
python = "==3.5.2"
```
So in this case I enforce version 3.5.2. The problem is that poetry creates a symlink to `python3` and not `python3.5`, which works fine until I change the default python version:

```bash
$ tree .venv/bin
.venv/bin
├── activate
├── activate.csh
├── activate.fish
.
.
├── python -> /usr/bin/python3
├── python3 -> python
├── python3.5 -> python
.
.
```
If I specifically tell poetry to use `python3.5`, it creates the correct symlink:
**EDIT:** This is only true if the default version of `python` is not the one specified in the `pyprojet`. That means that, in this case, if the default version of `python3` is `3.5`, the following commands produce the same output as the previous ones.
```
$ poetry env use python3.5
$ poetry install
$ tree .venv/bin
.venv/bin
├── activate
├── activate.csh
├── activate.fish
.
.
├── python -> /usr/bin/python3.5
├── python3 -> python
├── python3.5 -> python
.
.
```
This is a huge problem for me since the python version should be enforced very strictly. I have taken a look at how `pipenv` handles this and it creates the symlink to the specific python version and not just plain `python3`.

I also don't see any reference to the python version in the `lockfile`. Is this normal?

Thanks!

**Comment by ericriff** [comment]
I did some more digging and this behavior was introduced after dropping `venv` in favor of `virtualenv`, since they work in different ways: `venv` copies over the python executables to the environment whereas `virtualenv` creates symlinks. 

```
$ m -rf .venv
$ ~/.poetry/bin/poetry shell
The currently activated Python version 2.7.12 is not supported by the project (3.5.2).
Trying to find and use a compatible version. 
Using python3 (3.5.2)
Creating virtualenv ...
...
$ tree .venv/bin
.venv/bin
├── activate
├── activate.csh
├── activate.fish
├── easy_install
├── easy_install-3.5
├── pip
├── pip3
├── pip3.5
├── python
└── python3

```

**Comment by ericriff** [comment]
Sorry about the noise, I'm trying to post all the info that I can find on this issue since it is introducing some nasty bugs. I don't know enough about the Project to patch it myself.
Changing the default `python3` version to `3.6` and running with `-vvv` shows the list of python versions it checks. It should avoid python3 if it is a symlink or maybe expand it.

```
The currently activated Python version 3.5.2 is not supported by the project (~3.6).
Trying to find and use a compatible version. 
Trying python3
Trying python3.6
Using python3.6 (3.6.12)
Creating virtualenv [...]
Using virtualenv: [...]
```

**Comment by ericriff** [comment]
I wen't further down the rabbit hole and I believe it is an issue of `virtualenv` itself.
```
$ python3 -m virtualenv .venv -p 3.5

created virtual environment CPython3.5.2.final.0-64 in 102ms
.
.
$ tree .venv/bin
.venv/bin
├── activate
├── activate.csh
├── activate.fish
.
.
├── pip
├── pip3
├── pip-3.5
├── pip3.5
├── python -> /usr/bin/python3
├── python3 -> python
├── python3.5 -> python
```
Whereas specifying the non-default version produces the correct symlink
```
$ python3 -m virtualenv .venv -p 3.7

├── python -> /usr/bin/python3.7
├── python3 -> python
├── python3.7 -> python

```

**Comment by ericriff** [comment]
For all interested parties, https://github.com/pypa/virtualenv/issues/1974

**Comment by abn** [comment]
Mitigation is available via #3157 thanks to @finswimmer

**Comment by abn** [comment]
Thank you for providing the root cause analysis @ericriff !

**Comment by ericriff** [comment]
Thank you guys for fixing it :)
