### ISSUE TITLE
poetry thinks virtual env is still active after manual deactivate

### ISSUE THREAD

**Issue by abrahamfrancis** [python-poetry/poetry#3136]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**:  Arch Linux x86_64
- **Poetry version**:  1.1.2

## Issue

After activating virtual env using `poetry shell`, running `deactivate` command deactivates the env, but poetry thinks it's still active.

Steps to reproduce:

Before,
```sh
$ poetry --version
Poetry version 1.1.2

$ which python
/usr/bin/python
```
Activate the env,
```sh
$ poetry shell -vvv
Using virtualenv: /home/eb/.cache/pypoetry/virtualenvs/alpha-28-NyTHq-py3.8
Spawning shell within /home/eb/.cache/pypoetry/virtualenvs/alpha-28-NyTHq-py3.8
. /home/eb/.cache/pypoetry/virtualenvs/alpha-28-NyTHq-py3.8/bin/activate

$ . /home/eb/.cache/pypoetry/virtualenvs/alpha-28-NyTHq-py3.8/bin/activate

$ which python
/home/eb/.cache/pypoetry/virtualenvs/alpha-28-NyTHq-py3.8/bin/python
```

Deactivate using `deactivate`, It says it's already active.
```sh
$ deactivate

$ which python
/usr/bin/python

$ poetry shell -vvv
Using virtualenv: /home/eb/.cache/pypoetry/virtualenvs/alpha-28-NyTHq-py3.8
Virtual environment already activated: /home/eb/.cache/pypoetry/virtualenvs/alpha-28-NyTHq-py3.8
```

It works properly if `exit` were used instead of `deactivate`.

**Comment by finswimmer** [comment]
Hello @abrahamfrancis,

`poetry shell` spawns a new shell and activate the venv in there. A `deactivate` just deactivates to venv but doesn't leave the shell. For this you have to type `exit` instead.

See the [docs](https://python-poetry.org/docs/basic-usage/#activating-the-virtual-environment) why this is neccessary.

fin swimmer
