### ISSUE TITLE
Supported version formats not specified

### ISSUE THREAD

**Issue by gergelyk** [python-poetry/poetry#3141]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

1. Poetry docs suggest that [any versioning scheme can be used](https://python-poetry.org/docs/pyproject/#version) :

> This should follow semantic versioning. However it will not be enforced and you remain free to follow another specification.

Indeed this possible at the time of setting version, but poetry gives an error when building package:

```sh
$ poetry -V   
Poetry version 1.1.2
$ poetry new .
Created package iss in .
$ poetry version green-apple
Bumping version from 0.1.0 to green-apple
$ poetry build              
Building iss (green-apple)

  InvalidVersion
```

2. Poetry docs suggest that packages of [any versioning scheme can be added](https://python-poetry.org/docs/libraries/#versioning) as dependencies:

> While Poetry does not enforce any convention regarding package versioning, it strongly recommends to follow semantic versioning.

However some exotic packages that I had a chance to work with still lead to parsing error:

```sh
$ poetry add 'bar==green-apple'

  ParseConstraintError

  Could not parse version constraint: green-apple

$ poetry add 'bar@green-apple'

  ParseConstraintError

  Could not parse version constraint: green-apple
```

Would it make sense to restrict poetry to the formats versions that are fully supported (e.g. [PEP-440](https://www.python.org/dev/peps/pep-0440/))? Probably documentation should be updated in this case.

Alternatively, should we expect issues described above to be solved?

**Comment by abn** [comment]
1. Is not an issue. This is expected. You cannot build a wheel that is not compliant to PEP 427 and hence an error. This is not enforced as not all projects are intended to be built.
2. The secton you are referring to refers to your project version not package dependencies.

**Comment by gergelyk** [comment]
1. In this case you may consider pointing this out in description of [build](https://python-poetry.org/docs/cli/#build) command. Regarding PEP-427, this document doesn't seem to restrict version format. PEP-440 does.

2. You are right. Chapter about [add](https://python-poetry.org/docs/cli/#add) command may be better place for specifying which version formats are supported.

**Comment by abn** [comment]
PEP 427 was the wrong reference, what I should have refered to was https://www.python.org/dev/peps/pep-0426/#version - this requires PEP 440.

As for the add command, we are using the [version constraints](https://python-poetry.org/docs/dependency-specification/#version-constraints), not necessarily PEP 440.

**Comment by Secrus** [comment]
This is now correctly pointing to PEP 440 as reference to version format.
