### ISSUE TITLE
Poetry 1.1.2 doesn't work with private packages in older lockfiles

### ISSUE THREAD

**Issue by TNMarcus** [python-poetry/poetry#3151]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS 10.15.6
- **Poetry version**: 1.1.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue

Hi there,

It looks like Poetry 1.1.x fails to install with private packages that were added with a version of Poetry prior to 1.1.1 in the lock file. The workaround for this seems to be running `poetry upgrade` which fixes the `package.source` references.

Install failure:

```
 • Installing private-package-name (1.0.0)

  RuntimeError

  Unable to find installation candidates for private-package-name (1.0.0)

  at ~/.poetry/lib/poetry/installation/chooser.py:72 in choose_for
       68│ 
       69│             links.append(link)
       70│ 
       71│         if not links:
    →  72│             raise RuntimeError(
       73│                 "Unable to find installation candidates for {}".format(package)
       74│             )
       75│ 
       76│         # Get the best link
```

Example:

Poetry 1.1.2 rewrites the following in the lockfile:

```
[package.source]
reference = "private"
url = "https://pkgs.dev.azure.com/redacted/artifacts/_packaging/python/pypi/simple"
```

to

```
[package.source]
type = "legacy"
url = "https://pkgs.dev.azure.com/redacted/artifacts/_packaging/python/pypi/simple"
reference = "private"
```

which seems to resolve the install issue.

**Comment by abn** [comment]
@TNMarcus there was a bug with the lock file generated. Recommendation is to use `poetry lock --no-update` to fix the issue.
