### ISSUE TITLE
🎁 Hacktoberfest Guidelines

### ISSUE THREAD

**Issue by abn** [python-poetry/poetry#3152]
As as small project, we appreciate all types of contributions. That said, since we are a very small team, we would like to make sure that we set the expectations right.

Here are a few things to note before submitting hacktoberfest related pull requests.

1. Please read #3061 before making any contribution.
2. If you want to contribute to documentation, read #3060.
3. Please indicate explicitly that your contribution is related to hacktoberfest, especially if it is an extremely small change (formatting fixes, typo fixes etc.). Openness and tranperency is encouraged.
4. The maintainers have very limited bandwidth in between important bug fixes and reviews, so your pull request may not be repsonded to immediately.
5. Please add [meaningful commit messages](https://chris.beams.io/posts/git-commit/). Yes, even for documentation fixes.
6. Working on an existing issue is much more appreciated than making a change for a pull request's sake.
7. Documentation improvements (documenting new features, improving examples, adding tutorials etc.) will get our attention easier than one word typo/formatting/grammar fixes.

If in doubt, reach out to the community on our [discord server](https://discordapp.com/invite/awxPgve).

**Note:** If your pull request is a rather obvious attempt to rack up your numbers, they will be either marked `invalid` and closed; or we might put off merging it till November.

**Comment by finswimmer** [comment]
IMO we can close this until we take part on one of the next hacktoberfests.
