### ISSUE TITLE
Cirrus CI: Wait for release to be ready before attempting to push an artifact to github releases

### ISSUE THREAD

**Issue by abn** [python-poetry/poetry#3154]
Presently, the cirrus ci release logic checks if release is ready, if not it simply skips the upload. This needs to be changed to ensure that we wait for a reasonable amount before skipping.

https://github.com/python-poetry/poetry/blob/6a96dd22f4cf22f6f6d5bdb36c44c02097d57bee/.cirrus.yml#L53-L59

**Comment by saifalsowaidi** [comment]
relesea assistant 12 oct 2020

**Comment by Secrus** [comment]
The code that the issue references no longer exists. Closing
