### ISSUE TITLE
`poetry run -h` result in error

### ISSUE THREAD

**Issue by CircleOnCircles** [python-poetry/poetry#3164]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows 10 2004 build 19041.508 (latest at the time)
- **Poetry version**: 1.1.2 (latest at the time)
- **Python version**: 3.9.0 (latest at the time)

## Issue
```
PS C:\Users\n2\WinDevs\contribute\poetry> poetry run -h -vvv

  FileNotFoundError

  [WinError 2] The system cannot find the file specified

  at ~\.pyenv\pyenv-win\versions\3.8.6\lib\subprocess.py:1307 in _execute_child
      1303│             sys.audit("subprocess.Popen", executable, args, cwd, env)
      1304│
      1305│             # Start the process
      1306│             try:
    → 1307│                 hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
      1308│                                          # no special security
      1309│                                          None, None,
      1310│                                          int(not close_fds),
      1311│                                          creationflags,
```

I am not sure is it intended to. but intuitively this should not be an error.

**Comment by finswimmer** [comment]
Hey @CircleOnCircles,

this was reported before in https://github.com/python-poetry/poetry/issues/1567 and https://github.com/python-poetry/poetry/issues/2741

fin swimmer
