### ISSUE TITLE
1.1.{1,2} missing from history page

### ISSUE THREAD

**Issue by davidszotten** [python-poetry/poetry#3165]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

I think the most recent patches, 1.1.1 and 1.1.2 are missing from https://python-poetry.org/history/

**Comment by tony** [comment]
I made a PR for this (I'm not fully versed on the structure of branches yet)

Changelog is not updated for 1.1.1 and 1.1.2 in master: https://github.com/python-poetry/poetry/commit/6a96dd22f4cf22f6f6d5bdb36c44c02097d57bee (yet)

- https://github.com/python-poetry/poetry/blob/1.1.1/CHANGELOG.md
- https://github.com/python-poetry/poetry/blob/1.1.2/CHANGELOG.md

I think these just need to be merged to master
