### ISSUE TITLE
Rename get-poetry.py to getpoetry.py to make it importable and testable

### ISSUE THREAD

**Issue by abitrolly** [python-poetry/poetry#3171]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

`get-poetry.py` script can not be imported, because Python doesn't allow dashes in module names. Renaming that will allow testing functions inside.

**Comment by abn** [comment]
@abitrolly this is meant to be used as a script. So, any tests, should be calling this as a script. I do not see any value in this being renamed.

**Comment by abitrolly** [comment]
@abn I'd be able to add tests to profile selection function in https://github.com/python-poetry/poetry/pull/3169 but I don't see how to test the file that can not be imported.

**Comment by n8sty** [comment]
@abitrolly you should be able to import `get-poetry.py` using `importlib` like

```
import importlib
getpoetry = importlib.import_module("get-poetry")  # assumes you're in Poetry project root
getpoetry.temporary_directory  # an object that's available in get-poetry.py
# <function get-poetry.temporary_directory(*args, **kwargs)>
```

**Comment by abitrolly** [comment]
@n8sty and if I am not in Poetry project root, but in `tests/` subdir?

**Comment by n8sty** [comment]
`importlib.import_module` allows for specifying relative paths: https://docs.python.org/3/library/importlib.html#importlib.import_module. You can use that or `pathlib.Path(__file__)` to build a path to the script in question. Using the latter option, you can define a stable absolute path which can be used to import the file.

**Comment by abitrolly** [comment]
@n8sty and how can I ship it as a module to reuse profile modification code for other Python code?

**Comment by abitrolly** [comment]
Using `importlib` machinery it is indeed possible to write tests for it.
