### ISSUE TITLE
Py3.10

### ISSUE THREAD

**Issue by dimaqq** [python-poetry/poetry#3187]
Python-3.10.0a1 is available, it would be awesome to be able to use it.

Today I can work around like so:
```command
pushd ~/.poetry/lib/poetry/_vendor/
ln -s py3.9 py3.10
```

IIRC from 3.9, following needs to be done:
- [ ] ~change in code to add vendored deps for 3.10~
- [ ] change in the test matrix to include 3.10 (#3842)
- [ ] ~change in the release script to build against 3.10 (some platforms?~

**Comment by abn** [comment]
@dimaqq you can [install poetry via `pipx`](https://python-poetry.org/docs/#installing-with-pipx) or plain old [`pip`](https://python-poetry.org/docs/#installing-with-pip) to use under python 3.10. However, note that the current "supported" python versions for discovery does not include `3.10`. However, you can manually activate an environment for your project.

**Comment by dimaqq** [comment]
Oh yes, I did use `poetry env use 3.10` for an existing project.
Simple projects (few deps) work just fine with the work-around.
Complex projects are likely to not work due to some dep stumbling on BPO-40747

**Comment by HacKanCuBa** [comment]
Note that `pip install poetry` under Python 3.10rc (alpine) fails compiling `msgpack` and `cyptography`, but I guess it's an issue for those packages. I just let this here in case someone else arrives here like me.
