### ISSUE TITLE
Including system libraries

### ISSUE THREAD

**Issue by razmarques** [python-poetry/poetry#3191]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Issue

I want to include a library [(RDKit)](https://github.com/rdkit/rdkit) which is not available in PyPI. However this package is available through homebrew in my MacOS machine. Is it possible to include it in my poetry environment? And how?

**Comment by azdkj532** [comment]
I think its out of scope of poetry, but you can still follow RDKit official installation guide to install it manually. https://www.rdkit.org/docs/Install.html#macos-10-12-sierra-python-3-environment

**Comment by azdkj532** [comment]
Or you can create a virtualenv yourself in root of you project by `python3 -m venv --system-site-packages .venv`. `.venv` is a special env that poetry will directly use it if possible. See https://python-poetry.org/docs/configuration/#virtualenvsin-project-boolean

**Comment by finswimmer** [comment]
As @squirrel532 said, this is out of scope of poetry.
