### ISSUE TITLE
Editable package command line interface installation under windows

### ISSUE THREAD

**Issue by fkromer** [python-poetry/poetry#3194]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

Under Ubuntu I'm totally happy with my current setup. However under Windows I regularly run into issues w.r.t. this. I'm not sure if this is an issue or related to undocumented instructions.

On Windows 10 I'm running `Python 3.8.6`. My `project.toml` looks like follows:

```
[virtualenvs]
in-project = true
```

My `setup.py` looks like follows:

```
from setuptools import find_packages, setup

import my-package

setup(
   ...
   entry_points={"console_scripts": [my-cli=my_package.cli:main]},
   ...
)
...
```

The project structure looks as follows:

```
my-package
  .venv (contains virtual env)
  my_package (contains production code)
  setup.py
  poetry.toml
  ...
```

On windows if I try to install the package in an editable manner via `poetry shell; pip install -e .` package import is possible. If I run `>>>import my_package; help(my_package)` I get the expected help output. However if I try to run the cli in the activated venv `my-cli --help` the executable is not found. This seems something windows specific wr.t. the PATH. What's the recommended way to handle my setup under Windows properly?

**Comment by abn** [comment]
@fkromer you are attempting to build a `setuptools` project using poetry. In order to use poetry you willl have to create a PEP 517 project with a `pyproject.toml` and not a `setup.py` file.

You cat start by using `poetry init` to create this with some basic information for you. I would also recommend adding any dependencies your project needs.

To expose your cli, you will need to add a [`tools.poetry.scripts` section](https://python-poetry.org/docs/pyproject/#scripts), similar to this.

```toml
[tool.poetry.scripts]
my-cli = "my_package.cli:main"
```

Once that is done, executing `poetry install` should have you setup and you can run your cli tool using `poetry run my-cli --help` or by activating your virtual environment manually or using `poetry shell`.

**Comment by abn** [comment]
> If I run `>>>import my_package; help(my_package)` I get the expected help output.

This is because python adds the current path to `PYTHONPATH` making it importable if a package. To avoid this gotcha, I'd recommend you adopt a `src/` layout for your project. This will ensure that you are also testing the right code if using tox.

**Comment by fkromer** [comment]
> This is because python adds the current path to PYTHONPATH making it importable if a package. To avoid this gotcha, I'd recommend you adopt a src/ layout for your project. This will ensure that you are also testing the right code if using tox.

Thanks for this hint.

**Comment by fkromer** [comment]
> Once that is done, executing poetry install should have you setup and you can run your cli tool using poetry run my-cli --help or by activating your virtual environment manually or using poetry shell.

Thanks. Activating the venv manually and executing the plain executable works. I'll consider to use https://github.com/dephell/dephell to ensure package meta data consistency (building wheels depends on `setup.py`, etc.).

**Comment by abn** [comment]
@fkromer I am not really sure what you are trying to achieve there. You do not need `setup.py` files for building wheels. You can see `poetry` itself if you would like. You can build poetry managed project wheels using `poetry build -f wheel`. And this is the whole point of [PEP 517](https://www.python.org/dev/peps/pep-0517/). Feel free to drop by our discord if you have more questions.

**Comment by fkromer** [comment]
@abn Great. Did not know that. The main point for me to use `poetry` is it's capabilities w.r.t. dependency resolution.

**Comment by abn** [comment]
I would recommend you try using only one of `setuptools` or `poetry` otherwise you are bound to end up with some pain, even if you introduce a third tool to try keep things in sync. I'd (of course biased) recommend using only poetry since you already want to rely on the dependency resolution.

**Comment by fkromer** [comment]
@abn :slightly_smiling_face: Cause poetry supports wheel building I'll stick to poetry of course. Do you know about any issues w.r.t. building Python wheels including C/C++ extensions?

**Comment by abn** [comment]
You can refer to https://github.com/python-poetry/poetry-core/tree/master/tests/masonry/builders/fixtures/extended_with_no_setup for an example. Your `build.py` should be defined to handle building etc.

A real-world example is https://github.com/sdispater/pendulum/blob/master/build.py.

**Comment by fkromer** [comment]
@abn I've tried on another windows machine with `poetry run my-cli --help` and got `ImportError: C extension: tzutc not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace --force' to build the C extensions first.` . What to do here?
