### ISSUE TITLE
poetry install does not use available binary for numpy 1.19.2

### ISSUE THREAD

**Issue by pederpansen** [python-poetry/poetry#3196]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).
- **OS version and name**: Mac OS 10.15.6
- **Poetry version**: 1.1.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/pederpansen/eb25acdfea2bc808fa907e31ee541da1

## Issue

When running `poetry install` the installation of numpy `1.19.2` (using pyenv-installed Python 3.8.2) takes very long (~minutes) and seems to compile from source.

However, running `pip install numpy==1.19.2` yields

```
Collecting numpy==1.19.2
  Using cached https://files.pythonhosted.org/packages/33/1a/d10d1c23d21c289a3e87e751a9daf0907e91665cab08d0c35033fd4f5b55/numpy-1.19.2-cp38-cp38-macosx_10_9_x86_64.whl
Installing collected packages: numpy
Successfully installed numpy-1.19.2
WARNING: You are using pip version 19.2.3, however version 20.2.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

within a few seconds.

**Comment by naveen521kk** [comment]
Did you install python 3.9 and did poetry created a venv with that?
I that is the case it is expected.

**Comment by jtc42** [comment]
We're also having this problem now which is causing significant delays in releasing a critical update.

Log available online if it's useful https://gitlab.com/openflexure/pi-gen/-/jobs/801886395

**Comment by jtc42** [comment]
Worth noting that running `poetry config experimental.new-installer false` beforehand fixes this for me.

**Comment by pederpansen** [comment]
@naveen521kk As it turns out, the poetry version installed via Homebrew uses a hardcoded Homebrew-installed Python 3.9. The maintainers do not seem to see any issues with that: https://github.com/Homebrew/homebrew-core/issues/53169

I think this restricts the functionality of poetry in an unacceptable way. Solution: Use the official installer.

```
brew uninstall poetry
curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
```

**Comment by JezuzStardust** [comment]
> @naveen521kk As it turns out, the poetry version installed via Homebrew uses a hardcoded Homebrew-installed Python 3.9. The maintainers do not seem to see any issues with that: [Homebrew/homebrew-core#53169](https://github.com/Homebrew/homebrew-core/issues/53169)
> 
> I think this restricts the functionality of poetry in an unacceptable way. Solution: Use the official installer.
> 
> ```
> brew uninstall poetry
> curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
> ```

I installed via homebrew and got everything working. Using pyenv to set the local version first, then using using poetry env use <that version> and finally using the sugggestions by @jtc42 worked for me. 

I.e. 
`pyenv local 3.x.x
poetry env use 3.x.x
poetry config experimental.new-installer false
poetry install`

Not sure, but hopefully this helps.
