### ISSUE TITLE
Make `poetry remove <package>` work on dev-dependencies

### ISSUE THREAD

**Issue by silverwind** [python-poetry/poetry#3197]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request
```console
$ poetry add -D <package>
$ poetry remove <package>

  ValueError

  Package <package> not found
```

It'd be nice if `remove` (and possibly other subcommands) would also look in the `dev-dependencies` for convenience. The error message in this case seems rather confusing. Same works for example with `yarn`.

**Comment by abn** [comment]
@silverwind how would you see this working for cases where a dependency exists in both categories? Do we then remove both? Or should we simply improve the error message to indicate that the package is present in another category?

**Comment by silverwind** [comment]
The situation where the same package is in both `dependencies` and `dev-dependencies` should be avoided with by erroring when one tries to `add` a already existing module that is present in the other group. I don't see any valid use case that would require the same module to be in both at the same time.

As for `remove`, if it detects the module in both (maybe because of manual edits), I think it's good to remove it from both.

**Comment by abn** [comment]
I do not think poetry should disallow adding different versions that do not violate compatibility. An example scenario where this is required is when development environment might need particular extras activated for a dependency. There might also be scenarios where different versions are required only in development environment, or platform specific etc. 

Removing both might be problemeatic as the above scenario is valid. I suspect a better error message or a smart interactive suggestion might be the way to go here.

**Comment by silverwind** [comment]
The scenario you describe is probably so rare that it warrants a `--force` switch or similar. I don't even know how to import a specific version of a package without messing with `sys.path` which is probably should be discouraged in itelf.

**Comment by abn** [comment]
I suspect there is a sampling bias there. :) And this is not about having two versions of a package installed in the same site. The resolver will resolve this to a single version, but the required nested dependnecies may change based on installation context.

And to be clear, this behaviour is not intended to be changed at the moment. To bring things back on topic, this issue should focus on how to deal with the sceanrio where a user does not specify the group to remove the dependency form. 

Should poetry automatically remove the package from the dev category if the user forgets to specify `--dev`? My view is that it should not, but it can indicate to the user that the package exists in another category and how they can remove it. Similar might apply for `update` as well.

**Comment by rarenatoe** [comment]
Why not show a confirm dialog.

> This package was found in the [other] category, remove? [y/N]

Personally I am glad someone spoke out about this. I found this annoying too when trying to remove packages.

**Comment by finswimmer** [comment]
There is already a feature request for this in https://github.com/python-poetry/poetry/issues/2058. That's why I will close this one here.

I think the reason for confusion about the current behavior is, that only few people are aware, that one can define the same package in both section as @abn said.

IMO a confirm dialog would be fine. But also just removing the dep if it's only in one section would be nice. (My personal opinion)

**Comment by silverwind** [comment]
Thanks for finding that one and sorry for not searching throughly enough. GitHub search was not really helpful when searching for keywords like "remove" which are found in many issues.
