### ISSUE TITLE
Mistyped package name causes infinite loop

### ISSUE THREAD

**Issue by intgr** [python-poetry/poetry#3200]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Tested on macOS & Arch Linux
- **Poetry version**: 1.1.2
- **Link of a [Gist](https://gist.github.com/intgr/902441767488eb11ff253359665c6a7f) with the contents of your pyproject.toml file**: 

## Issue
I converted my dependencies file using DepHell from Pipfile to requirements.txt to Poetry pyproject.toml. Trying to use this converted file, Poetry for some reason got stuck in an infinite loop. I tracked it down to one bad line.

The [PyPI package](https://pypi.org/project/ruamel.yaml/) has a name `ruamel.yaml` (with a dot), but my dependencies had it with a hyphen: `ruamel-yaml`
```
[tool.poetry.dependencies]
ruamel-yaml = "*"
```
Running `poetry lock` on such a file reproduces the infinite loop.

This may be partially causing #2094 ("Poetry is extremely slow when resolving the dependencies").

![image](https://user-images.githubusercontent.com/137616/95909617-7810d280-0da7-11eb-87d6-8f26c78782dc.png)

I cannot trigger this issue by using the Poetry command, however. If I write `poetry add ruamel-yaml`, it adds dependency with the correct name `"ruamel.yaml" = "^0.16.12"` and `poetry lock` works fine with that.

**Comment by abn** [comment]
Looks like there is a cyclic dependency involved here.

```
   1: selecting ruamel.yaml (0.16.12)
   1: fact: ruamel.yaml (0.16.12) depends on ruamel.yaml.clib (>=0.1.2)
   1: selecting ruamel.yaml (0.16.12)
   1: fact: ruamel.yaml (0.16.12) depends on ruamel.yaml.clib (>=0.1.2)
```

**Comment by abn** [comment]
@intgr noticed that. Appreciate the details in your issue report, it is extremely helpful.

**Comment by abn** [comment]
The issue was in how we normalised the name of the package. This needs a fix in core. And another change in poetry itself.

**Comment by domdfcoding** [comment]
Wondering whether there has been any progress on this?

**Comment by intgr** [comment]
As I understand, commit b0d90868f832e6af241e0adb91191a99f5d52847 was supposed to fix this?

**Comment by domdfcoding** [comment]
I have tested this out and there still seems to be an issue. I've installed the latest (prerelease) `poetry` and `poetry-core` from PyPI, but with the following `pyproject.toml` there's still and infinite loop:

```toml
[tool.poetry]
name = "demo"
version = "1"
description = "A Demo"
authors = []

[tool.poetry.dependencies]
python = ">= 3.6"
"ruamel-yaml" = "*"
```

```console
$ poetry lock
Updating dependencies
Resolving dependencies... (138.2s)
```

(I'm not a poetry user, so I might have gone wrong somewhere)
