### ISSUE TITLE
Platform constraint ignored

### ISSUE THREAD

**Issue by olliethomas** [python-poetry/poetry#3202]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- MacOS Catalina
- 1.1.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: [minimum replicable pyproject.toml](https://gist.github.com/olliethomas/26e5b6a4081d7dbd680167931680202e)

## Issue
Hi, I'm adding Guild AI as a dependency to a project. When I `poetry add guildai` a RuntimeError is thrown
```
  • Installing windows-curses (2.1.0): Failed

  RuntimeError

  Unable to find installation candidates for windows-curses (2.1.0)

  at ~/.poetry/lib/poetry/installation/chooser.py:72 in choose_for
       68│ 
       69│             links.append(link)
       70│ 
       71│         if not links:
    →  72│             raise RuntimeError(
       73│                 "Unable to find installation candidates for {}".format(package)
       74│             )
       75│ 
       76│         # Get the best link

```

[windows-curses](https://pypi.org/project/windows-curses/2.1.0/) is a Windows-only dependency ([link to setup.py for guildai](https://github.com/guildai/guildai/blob/master/setup.py#L42)) so it's surprising that this is trying to be installed.

If I install directly using `pip install guildai` then there is no attempt to install the Windows-only dependency and installation completes as expected.

To reproduce (only tested on MacOS):
1. create new project
2. `poetry add guildai`

---
If this is indeed expected behaviour, and it's just my understanding that's wrong, I should open a PR on Guild AI. Any advice for how I should amend the setup.py to allow for platform-specific dependencies?

**Comment by abn** [comment]
@olliethomas it looks like the metadata for `guildai` does not contain the markers. Right now poetry is told `guildai` requires `windows-curses` irrsepective of platform and it tries to find a valid version for your platform. Which, obviously in this case, does not exist. 

```console
$ curl -sL https://pypi.org/pypi/guildai/json | jq '.info.requires_dist'
[
  "Pillow (>=5.0)",
  "PyYAML (>=2.12)",
  "Werkzeug (>=0.15)",
  "chardet (>=3.0.4)",
  "daemonize (>=2.4.7)",
  "filelock (>=3.0.12)",
  "jinja2 (>=2.10)",
  "numpy (>=1.16)",
  "pkginfo",
  "scikit-learn (<0.23.0,>=0.19.1)",
  "scikit-optimize (>=0.7.1)",
  "setuptools (>=40.6.3)",
  "six (>=1.10.0)",
  "tabview (>=1.4.3)",
  "tensorboard (<2.3,>=1.15)",
  "virtualenv (>=15.1.0)",
  "windows-curses"
]
```

I would recommend that they add this to their `install_requires` instead of conditionally appending `windows-curses`.

```
windows-curses ; system_platform == "Windows"
```

**Comment by olliethomas** [comment]
Thanks for your help!
