### ISSUE TITLE
Virtual environment not created in-project on `poetry new`

### ISSUE THREAD

**Issue by pedrorrivero** [python-poetry/poetry#3206]
- [ ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS Catalina v10.15.7
- **Poetry version**: 1.1.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: N/A

## Issue

Virtual environment not created in-project on `poetry new`. Current config:
```
cache-dir = "~/Library/Caches/pypoetry"
experimental.new-installer = true
virtualenvs.create = true
virtualenvs.in-project = true
virtualenvs.path = "{cache-dir}/virtualenvs"  # ~/Library/Caches/pypoetry/virtualenvs
```

**Comment by finswimmer** [comment]
`poetry new` doesn't create a virtual env. It gives you a basic package structure with a basic `pyproject.toml`. After running `poetry new` you have to step into the folder and run `poetry install`.
