### ISSUE TITLE
poetry env remove --all?

### ISSUE THREAD

**Issue by max-sixty** [python-poetry/poetry#3208]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

In debugging some recent issues, I've wanted to clear out all poetry environments to reset state. Any thoughts on a `poetry env remove --all`?

I tried `poetry env list | xargs poetry env remove`, but unfortunately given the `(Activated)` label, this would require a more complex command.

**Comment by abn** [comment]
I do not see why not.

**Comment by DustinMoriarty** [comment]
@max-sixty : See PR #3212. I added an --all option and the ability to list multiple envs in one go. I'll check in the morning to make sure that all checks have passed.
