### ISSUE TITLE
Add ability to togglle dependency 'develop'

### ISSUE THREAD

**Issue by Seanny123** [python-poetry/poetry#3220]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

Path-dependencies in Poetry can be [optionally marked as `'develop' = True`](https://python-poetry.org/docs/dependency-specification/#path-dependencies). However, there's no way to mark it as such via the `poetry add` command.

It would be nice to set the `'develop' = True` when adding a path. For example:
```
poetry add ./my-package/ --develop
```
Or
```
poetry add ./my-package/ --editable
```

I think I can implement this myself if the core devs consider this feature to be beneficial.

**Comment by finswimmer** [comment]
Hello  @Seanny123,

yes this is something really useful :+1: 

@abn listed this also in his suggestion in https://github.com/python-poetry/poetry/issues/3004.

fin swimmer

**Comment by abn** [comment]
I think this can happen independent of #3004. If this happens first, we just update the key it operates on when #3004 lands.

**Comment by 0scarB** [comment]
@python-poetry/triage Hi, really like the project. Have used it for a couple of personal projects. Mind if I take on the issue

**Comment by finswimmer** [comment]
Hello @0scarB,

I don't know if @Seanny123 already started to work on it? Otherwise we really appreciate any contribution :+1: 

fin swimmer

**Comment by Seanny123** [comment]
Have no started yet. Go for it @0scarB

**Comment by 0scarB** [comment]
@Seanny123 thx, I will :)

**Comment by 0scarB** [comment]
Only [directory](https://github.com/python-poetry/poetry-core/blob/fa522603bc2aff99127adaf585046f0ad50db973/poetry/core/packages/directory_dependency.py#L11-L21) and [vcs dependencies](https://github.com/python-poetry/poetry-core/blob/fa522603bc2aff99127adaf585046f0ad50db973/poetry/core/packages/vcs_dependency.py#L10-L28)support the `develop` attribute. 

If we add `develop = true` without checking the `source_type` first then the follow unintuitive error message is raised for dependency that do not support it
```
RuntimeError

  The Poetry configuration is invalid:
    - [dependencies.<dependency>] {'version': '<version>', 'develop': True} is not valid under any of the given schemas
```
It would be better to raise an explicit error such as `The develop flag is not supported for dependencies of type <source_type>`
Unfortunately I don't see an elegant way of doing this without changing how `poetry-core` dependencies handle the `develop` parameter.
Thoughts?

**Comment by finswimmer** [comment]
Hello @0scarB,

the error message poetry raises are in general very technical and it is not always obvious to the end-user, but are very useful for debugging. That's a general topic we can improve. I guess there was already somewhere a ticket about this :thinking: .

fin swimmer

**Comment by 0scarB** [comment]
@finswimmer Thanks for the feedback, I totally agree. After working on [#3004](https://github.com/python-poetry/poetry/issues/3004#issue-712023603) I think that the dependency classes need to be refactored to have the `json_schema` as a single source of true, inheriting from superclasses/interfaces for common options such as `optional`, `extras` and `editable`/`develop`. I'll try and find the issue or create a new one and write up a more detailed proposal.

**Comment by finswimmer** [comment]
This is now possible in the current preview release 1.2.0a2 by:

```
-e, --editable           Add vcs/path dependencies as editable.
```
