### ISSUE TITLE
"poetry version v1.2.3" changes Quotation marks

### ISSUE THREAD

**Issue by jedie** [python-poetry/poetry#3226]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

 (`-vvv` option will not print any more informations)

- **Ubuntu-Mate 20.04** 
- **Poetry v1.1.3** 

## Issue

We use single quotation marks in our `pyproject.toml` and use `poetry version` to update the version string from our project `__version__`... But then the single quotation marks will be changed to double quotation marks. e.g.:

![grafik](https://user-images.githubusercontent.com/71315/96270131-8808fc00-0fcb-11eb-8759-f408321338ed.png)

https://github.com/boxine/bx_py_utils/pull/4/files

**Comment by finswimmer** [comment]
Hello @jedie,

was there ever a version where poetry used single quotes?

fin swimmer

**Comment by jedie** [comment]
I think no.

**Comment by abn** [comment]
@jedie I think this issue should go to `tomlkit` because it needs to preserve style. We rely on that library to load and write to the toml files.
