### ISSUE TITLE
get-poetry.py installation with --file Does not rename lib

### ISSUE THREAD

**Issue by bphunter1972** [python-poetry/poetry#3228]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: CentOS7
- **Poetry version**: 1.1.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: N/A

## Issue
I have a need to install poetry from a file because the server I'm running on is not currently allowing downloads outside of the local domain. This is fine since we have our own PyPI mirror.

Having downloaded the get-poetry.py script and the poetry-1.1.3.tar.gz from the mirror, I ran: 
./get-poetry.py --file poetry-1.1.3.tar.gz

This appears to work fine, but on closer inspection the .poetry/lib dir contains a directory named poetry-1.1.3. Simply renaming this to just poetry won't work because it really needs to poetry sub-directory to be extracted. I believe the problem is located in Installer::extract_lib.

**Comment by DustinMoriarty** [comment]
I don't see get-poetry.py in the coverage. I would be happy to take a shot at creating some unit tests for the get-poetry script to see if we can reproduce this issue with tests. However, creating tests for get-poetry.py may be a larger task, so I could create a separate issue for it.

**Comment by DustinMoriarty** [comment]
I was able to reproduce this with a unit test. I will look into the cause.

**Comment by DustinMoriarty** [comment]
@bphunter1972 : Where are you getting the tar.gz file from? It looks like there may be a difference between an sdist off of pypi and the version that the installer downloads from https://github.com/python-poetry/poetry/releases.

**Comment by DustinMoriarty** [comment]
@bphunter1972 : You should be able to install just fine from the github release location. However, see PR #3239 for support for using the sdist from your pypi mirror. I can see how in some organizations the pypi mirror could be preferred over github releases. Let me know if this works for you.

**Comment by bphunter1972** [comment]
Got it. Confirmed that this works.
Yeah, adding more help on where the --file must come from would be great!

**Comment by abn** [comment]
@bphunter1972 just to be clear you don't need the `get-poetry` script to install from PyPI or a mirror.

You can simply use `pip install` or `pipx install` (probably preferred) for those.

**Comment by bphunter1972** [comment]
Referring back to my original issue, the platform that I'm trying it from does not permit downloads from external sources. I could only push zipped files to it and download from our mirrored PyPI.

Running pip install of poetry is possible, because it's mirrored, but then nothing is set up. (In fact, I don't know how one uses poetry if you run pip install on it).

**Comment by abn** [comment]
> Running pip install of poetry is possible, because it's mirrored, but then nothing is set up. (In fact, I don't know how one uses poetry if you run pip install on it).

Just as any other `pip` installed application.

```console
$ podman run --rm -i --entrypoint bash python:3.8 <<EOF
> set -xe
> python -m pip install -q poetry
> poetry --version
> EOF
+ python -m pip install -q poetry
+ poetry --version
Poetry version 1.1.3
```
