### ISSUE TITLE
Organization: _get_validator function is not used inside the project

### ISSUE THREAD

**Issue by GabrielSimonetto** [python-poetry/poetry#3236]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Issue

I am currently trying to find missing tests on coverage, which leads me to `grep -r` some functions across the project in order to find how they are used.

However, `_get_validator()` on `poetry/config/config.py` seems to not be used inside the project, which seems especially weird since it's a private function.

```
(poetry--BSniWvU-py3.8) [bigode@coala poetry]$ grep -r _get_validator
poetry/config/config.py:    def _get_validator(self, name):  # type: (str) -> Callable
(poetry--BSniWvU-py3.8) [bigode@coala poetry]$ pwd
/home/bigode/programas_temp/poetry
```

So i used [this git command](https://stackoverflow.com/questions/4781405/git-how-do-i-view-the-change-history-of-a-method-function#33953022) to see what context this function had in the past, and arrived to its creation on commit `01fddda57b2b6d6ea486278bec568b84ba470943` and... It is not used on that version either!

I don't know if this means that the function should be removed, just raising a flag for now

**Comment by GabrielSimonetto** [comment]
Also happens with:

```
poetry/console/commands/config.py:    _list_setting()
```

**Comment by abn** [comment]
For `_get_validator`, I suspect that the original intent was to validate the values when a merge is performed. As for the other two, I think its just left over code from an older version and can be removed safely.

**Comment by Coquinho** [comment]
May I took this task?

**Comment by stephsamson** [comment]
@Coquinho I've assigned you to this task. And yes, deleting these functions and making sure the tests pass should be sufficient.
