### ISSUE TITLE
Docs: Caret requirements example incomplete

### ISSUE THREAD

**Issue by salty-horse** [python-poetry/poetry#3242]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue
The current `master` documentation in `docs/docs/dependency-specification.md` says:
>In this case, if we ran `poetry update requests`, poetry would update us to version `2.14.0` if it was available

The text is missing an example caret version requirement for `requests`. The words "In this case" don't match anything.

**Comment by finswimmer** [comment]
Hello @salty-horse,

yes this sentence seems to be a little out of context. A PR to make it better is very welcome :)

fin swimmer

**Comment by cereblanco** [comment]
Hello @salty-horse @finswimmer. I opened a PR for this issue. I hope it gave the sentence more context. 🤞🏼
