### ISSUE TITLE
Poetry doesn't work on Ubuntu 16

### ISSUE THREAD

**Issue by ericriff** [python-poetry/poetry#3256]
- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 16 + Python 3.5.2
- **Poetry version**: 1.1.3

## Issue
Installing poetry with `get-poetry.py` on Ubuntu 16 does not work. Launching poetry crashes right away with the following traceback:

```
$ poetry --version
Traceback (most recent call last):
  File "/root/.poetry/lib/poetry/_vendor/py3.5/clikit/api/config/application_config.py", line 8, in <module>
    from typing import ContextManager
ImportError: cannot import name 'ContextManager'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.poetry/bin/poetry", line 17, in <module>
    from poetry.console import main
  File "/root/.poetry/lib/poetry/console/__init__.py", line 1, in <module>
    from .application import Application
  File "/root/.poetry/lib/poetry/console/application.py", line 3, in <module>
    from cleo import Application as BaseApplication
  File "/root/.poetry/lib/poetry/_vendor/py3.5/cleo/__init__.py", line 3, in <module>
    from .application import Application
  File "/root/.poetry/lib/poetry/_vendor/py3.5/cleo/application.py", line 4, in <module>
    from clikit.console_application import ConsoleApplication
  File "/root/.poetry/lib/poetry/_vendor/py3.5/clikit/__init__.py", line 1, in <module>
    from .api.config.application_config import ApplicationConfig
  File "/root/.poetry/lib/poetry/_vendor/py3.5/clikit/api/config/__init__.py", line 1, in <module>
    from .application_config import ApplicationConfig
  File "/root/.poetry/lib/poetry/_vendor/py3.5/clikit/api/config/application_config.py", line 10, in <module>
    from typing_extensions import ContextManager
```

So basically is failing to import `typing_extensions`. Installing it with pip fixes the crash.
I know that python3.5 is nearly deprecated on poetry but I'm reporting this anyways, maybe is not a big deal to fix.

Dockerfile and steps to recreate:
```
$ docker build -t poetrybug . --network=host
$ docker run -it --rm --network=host poetrybug
$ source source $HOME/.poetry/env
$ poetry --version

#To make it work
$ curl -s https://bootstrap.pypa.io/get-pip.py -o get-pip.py && python3 get-pip.py --force-reinstall
$ python3 -m pip install typing_extensions
$ poetry --version
```

```
FROM ubuntu:16.04

RUN apt-get update && apt-get upgrade -y && apt-get clean

# Install python 3.5 (Ubuntu 16 default)
RUN apt-get install -y python3.5

RUN apt-get install -y curl tree

# Install alternatives
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.5 1

# Install poetry
RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3

```

**Comment by abn** [comment]
The problem here is the dependency specificaiton in `clikit` and how poetry's release packages are built.

https://github.com/sdispater/clikit/blob/ead8dd5375d5c16fd9c9730a012a53d580201f62/pyproject.toml#L29

The poetry `3.5` release builds happen on `3.5.10` this means this dependency does not get bundled and this ends up with the issue it seems. 

Installing using `pip` or `pipx` is recommended. I cannot justify the effort to fix this unfortunately, especially since other installation methods work.

**Comment by ericriff** [comment]
So if I build my own release (I remember seeing a bash script that generates a release somewhere in the repo) using python 3.5.2, will it work?

**Comment by abn** [comment]
In theory yes. If you need help with that feel free to drop by our discord server.

**Comment by gjask** [comment]
I've just run into same issue with debian 9 (stretch) - python 3.5.3

> Installing using `pip` or `pipx` is recommended. I cannot justify the effort to fix this unfortunately, especially since other installation methods work.

Actually your documentation says something else.

> Poetry provides a custom installer that will install poetry isolated from the rest of your system by vendorizing its dependencies. This is the recommended way of installing poetry.
> -- https://python-poetry.org/docs/

Please fix either your documentation or this issue. This is my first attempt into poetry and getting error just by following tutorial isn't very nice.

**Comment by mcspud** [comment]
@gjask we've encountered this error today too, for the exact same reason.
How about you file a PR to update the documentation?
