### ISSUE TITLE
Add Tests for Console

### ISSUE THREAD

**Issue by DustinMoriarty** [python-poetry/poetry#3281]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

There are several commands in the CLI which are not covered by unit tests.

**Comment by dimbleby** [comment]
#3282 was enough, there was no need for an issue and an MR.  This can be closed.
