### ISSUE TITLE
Poetry creates virtualenv with wrong version of Python despite finding the right one

### ISSUE THREAD

**Issue by fsouza** [python-poetry/poetry#3284]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS 10.15.7
- **Poetry version**: 1.1.4
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: no need, full reproducer listed below

## Issue

I'm running into an issue in which when creating a virtualenv with poetry, it is able to find a matching version, but still creates the virtualenv with the wrong version. Reproducer from scratch:

```
％ mkdir /tmp/sample-proj
％ cd /tmp/sample-proj
％ poetry init -n --python '~3.8'

This command will guide you through creating your pyproject.toml config.


You can specify a package in the following forms:
  - A single name (requests)
  - A name and a constraint (requests@^2.23.0)
  - A git url (git+https://github.com/python-poetry/poetry.git)
  - A git url with a revision (git+https://github.com/python-poetry/poetry.git#develop)
  - A file path (../my-package/my-package.whl)
  - A directory (../my-package/)
  - A url (https://example.com/packages/my-package-0.1.0.tar.gz)

％ poetry install
The currently activated Python version 3.9.0 is not supported by the project (~3.8).
Trying to find and use a compatible version.
Using python3 (3.8.6)
Creating virtualenv sample-proj-WINP6DfI-py3.8 in /Users/fsouza/Library/Caches/pypoetry/virtualenvs
Updating dependencies
Resolving dependencies... (0.1s)

Writing lock file
％ /Users/fsouza/Library/Caches/pypoetry/virtualenvs/sample-proj-WINP6DfI-py3.8/bin/python --version
Python 3.9.0
```

The interesting bits are:

- poetry correctly complains about my current version of Python being not supported
- poetry correctly finds a supported version
- poetry incorrectly creates the virtualenv with the wrong version

For now, as a workaround, I've been manually managing my virtualenvs.

Moreover, I am using homebrew to install poetry, so this may be a side effect of how homebrew installs poetry, and not an issue with poetry itself, but I figured using shutil.which to pass the full path of the found executable when creating the virtualenv is a harmless change. Let me know if this makes sense.

**Comment by finswimmer** [comment]
Hey @fsouza,

lots of improvement were made in the 1.2 release and your issue should be solved. 

Fell free to leave a comment if something still not work for you.


fin swimmer
