### ISSUE TITLE
poetry: command not found / Ubuntu install in conda

### ISSUE THREAD

**Issue by albertotono** [python-poetry/poetry#3302]
- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: 
- **Poetry version**: 

## Issue
I am in ubuntu, I created an environment with conda and then I run the installation for poetry, but after that I got that message?

`poetry: command not found`

**Comment by albertotono** [comment]
```
 RuntimeError

  Poetry could not find a pyproject.toml file in /home/alberto or its parents

  at .poetry/lib/poetry/_vendor/py3.8/poetry/core/factory.py:367 in locate
      363│             if poetry_file.exists():
      364│                 return poetry_file
      365│ 
      366│         else:
    → 367│             raise RuntimeError(
      368│                 "Poetry could not find a pyproject.toml file in {} or its parents".format(
      369│                     cwd
      370│                 )
      371│             )

```

**Comment by albertotono** [comment]
after running `poetry config -vvv
`
I got nothing

**Comment by albertotono** [comment]
I can't even uninstall

```
(base) alberto@tensorbook:~$ python get-poetry.py --uninstall
python: can't open file 'get-poetry.py': [Errno 2] No such file or directory
```

But it tells me the version 1.1.4

**Comment by sinoroc** [comment]
I do not think `get-poetry.py` is meant to be installed in a virtual environment (conda or other).

**Comment by s-ayush2903** [comment]
@albertotono How did you fix it? I didn't understand the previous comment.

**Comment by s-ayush2903** [comment]
Ah, ignore it I got the error :+1:
