### ISSUE TITLE
Failed to find interpreter for Builtin discover of python_spec='python3.9'

### ISSUE THREAD

**Issue by ewen-lbh** [python-poetry/poetry#3307]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 18.04.4 LTS on Windows 10 x86_64
- **Poetry version**: 1.1.4
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/ewen-lbh/1b545155a2083e561ab70b7a298f685f

## Issue
This happened just after running `poetry init`, while tring to run `poetry install`.
I verified that `python3.9` works. I even tried to specify `^3.8` in the pyproject file, as you can see, but it chose 3.9 (even though I have a working `python3.8` binary in my PATH)

<details>
<summary>This is the output of <code>poetry install -vvv</code></summary>
<pre>
The currently activated Python version 3.6.9 is not supported by the project (^3.8).
Trying to find and use a compatible version. 
Trying python3
Trying python3.9
Using python3.9 (3.9.0)
Creating virtualenv translator-7r_3xLEF-py3.9 in /home/ewen/.cache/pypoetry/virtualenvs

  Stack trace:

  10  ~/.poetry/lib/poetry/_vendor/py3.6/clikit/console_application.py:131 in run
       129│             parsed_args = resolved_command.args
       130│ 
     → 131│             status_code = command.handle(parsed_args, io)
       132│         except KeyboardInterrupt:
       133│             status_code = 1

   9  ~/.poetry/lib/poetry/_vendor/py3.6/clikit/api/command/command.py:120 in handle
       118│     def handle(self, args, io):  # type: (Args, IO) -> int
       119│         try:
     → 120│             status_code = self._do_handle(args, io)
       121│         except KeyboardInterrupt:
       122│             if io.is_debug():

   8  ~/.poetry/lib/poetry/_vendor/py3.6/clikit/api/command/command.py:163 in _do_handle
       161│         if self._dispatcher and self._dispatcher.has_listeners(PRE_HANDLE):
       162│             event = PreHandleEvent(args, io, self)
     → 163│             self._dispatcher.dispatch(PRE_HANDLE, event)
       164│ 
       165│             if event.is_handled():

   7  ~/.poetry/lib/poetry/_vendor/py3.6/clikit/api/event/event_dispatcher.py:22 in dispatch
        20│ 
        21│         if listeners:
     →  22│             self._do_dispatch(listeners, event_name, event)
        23│ 
        24│         return event

   6  ~/.poetry/lib/poetry/_vendor/py3.6/clikit/api/event/event_dispatcher.py:89 in _do_dispatch
        87│                 break
        88│ 
     →  89│             listener(event, event_name, self)
        90│ 
        91│     def _sort_listeners(self, event_name):  # type: (str) -> None

   5  ~/.poetry/lib/poetry/console/config/application_config.py:119 in set_env
       117│ 
       118│         env_manager = EnvManager(poetry)
     → 119│         env = env_manager.create_venv(io)
       120│ 
       121│         if env.is_venv() and io.is_verbose():

   4  ~/.poetry/lib/poetry/utils/env.py:761 in create_venv
        759│             )
        760│ 
     →  761│             self.build_venv(venv, executable=executable)
        762│         else:
        763│             if force:

   3  ~/.poetry/lib/poetry/utils/env.py:808 in build_venv
        806│                 "--python",
        807│                 executable or sys.executable,
     →  808│                 str(path),
        809│             ]
        810│         )

   2  ~/.poetry/lib/poetry/_vendor/py3.6/virtualenv/run/__init__.py:26 in cli_run
        24│     :return: the session object of the creation (its structure for now is experimental and might change on short notice)
        25│     """
     →  26│     of_session = session_via_cli(args, options, setup_logging)
        27│     with of_session:
        28│         of_session.run()

   1  ~/.poetry/lib/poetry/_vendor/py3.6/virtualenv/run/__init__.py:42 in session_via_cli
        40│     :return: the session object of the creation (its structure for now is experimental and might change on short notice)
        41│     """
     →  42│     parser, elements = build_parser(args, options, setup_logging)
        43│     options = parser.parse_args(args)
        44│     creator, seeder, activators = tuple(e.create(options) for e in elements)  # create types

  RuntimeError

  failed to find interpreter for Builtin discover of python_spec='python3.9'

  at ~/.poetry/lib/poetry/_vendor/py3.6/virtualenv/run/__init__.py:66 in build_parser
       62│ 
       63│     discover = get_discover(parser, args)
       64│     parser._interpreter = interpreter = discover.interpreter
       65│     if interpreter is None:
    →  66│         raise RuntimeError("failed to find interpreter for {}".format(discover))
       67│     elements = [
       68│         CreatorSelector(interpreter, parser),
       69│         SeederSelector(interpreter, parser),
       70│         ActivationSelector(interpreter, parser),
</pre>
</details>

**Comment by ewen-lbh** [comment]
This was fixed by installing `python3.9-distutils`.

**Comment by FranzForstmayr** [comment]
What's about throwing a warning, if distutils is not found?
