### ISSUE TITLE
The 'poetry run' command should not execute binaries installed outside of the environment

### ISSUE THREAD

**Issue by apost71** [python-poetry/poetry#3308]
- [ x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [ x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Mac OS Catalina 10.15.7
- **Poetry version**: 1.1.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: I'm not including this because I dont think it is useful for this report.

## Issue

I am not positive this constitutes as a bug but I wanted to raise it anyways.  I am using FastAPI and Uvicorn to run a web application and I have uvicorn installed on my global system python.  When I was messing with my dependencies, I inadvertently removed a dependency that pulled Uvicorn into my poetry environment (It was a dependency of a dependency).  When I was trying to run my service using `poetry run uvicorn service:app`, there was no error but Uvicorn raised an error saying that it could not find my dependencies in its path.  After investigation, when poetry did not find uvicorn in its environment, it ended up using the uvicorn instance that was installed on my global system.  This problem was easily resolved by adding uvicorn into my `pyproject.toml` file.  However, I believe poetry should have thrown an error if it did not find the necessary requirements in its environment.

**Comment by sinoroc** [comment]
My first impression is that it is not possible without breaking tons of other workflows. The point of `poetry run` as I understand it, is to call a binary in the context of the virtual environment, but not necessarily call a binary that is installed in the environment.

Something like the following seems like a perfectly legitimate use case to me:

```
poetry run make
```

where the `Makefile` contains rules that should be executed in the virtual environment, but the `make` tool itself does not have to be installed in the environment.

---

It reminds me of the behavior in _tox_ and [its `allowlist_externals` setting](https://tox.readthedocs.io/en/latest/config.html#conf-allowlist_externals). It makes sense in _tox_, but I am not sure it does in _poetry_.

**Comment by apost71** [comment]
That makes sense to me.  I wonder if it's something that could trigger a warning or some kind of indication to say that the binary is not actually installed in the environment.  The reason I was a bit hesitant to call this a bug is because, like you said, the point of poetry run is to run something in the context of the environment.  My biggest complaint here is that _sometimes_ it matters which installation is being used and it is very difficult to debug in those cases.

**Comment by sinoroc** [comment]
Fair enough. I understand your point, and I see how it can be very surprising. I would recommend you to rephrase the title of the ticket though:

"The 'poetry run' command should execute binaries installed outside of the environment"

Does that sound accurate to you?

**Comment by apost71** [comment]
That does sound accurate.  Consider it changed.

**Comment by Qu4tro** [comment]
I feel like this is actually the expected behavior, even if it introduces some margin for error. I'm fine with keeping this open and discuss a bit more to find a better solution for everyone, but in the meantime, can I just suggest to label this a feature and not as a bug?

**Comment by apost71** [comment]
> I feel like this is actually the expected behavior, even if it introduces some margin for error. I think it's great that we can discuss this a bit more to find a better solution for everyone, but in the meantime, can I just suggest to label this a feature and not as a bug?

I think it is fair to consider this expected behavior and the more I think about it I'm not even sure it is worth changing the behavior, I guess my request here could be modified to a request to include some indication of what is being run.  That way in cases where there are multiple instances of a binary installed on the system it would be trivial to see that the found instance is not the correct one.  Or even a warning message that only appears when the binary is not installed in the poetry environment I think would be incredibly useful.

**Comment by finswimmer** [comment]
At the moment there are no plans to change this behavior, because it works as expected.
