### ISSUE TITLE
'Key "reference" does not exist.'

### ISSUE THREAD

**Issue by keikumata** [python-poetry/poetry#3317]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**:
  - _Local Env:_
     - macOS Catalina: 10.15.6
  - _CircleCI agent:_
    - Docker Engine Version: 18.09.6
    - Kernel Version: Linux 890353da4980 4.15.0-1077-aws #81-Ubuntu SMP Wed Jun 24 16:48:15 UTC 2020 x86_64 Linux

- **Poetry version**: 1.1.4
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**:
Including the relevant snippet of the pyproject.toml file below.

## Issue

We have two poetry projects, one called `common` and another called `backend`. We are importing the `common` project in the `backend` project like this in the pyproject.toml:

```
[tool.poetry]
name = "backend"
version = "0.1.0"
authors = ["dev"]
description = "description."

[tool.poetry.dependencies]
common = {path = "../../common", develop = true}
```

In poetry version 1.1.4, the above dependency generates this in the `poetry.lock file`:
```
[package.source]
type = "directory"
url = "../../common"
```

We generate this lockfile locally using 1.14, and push this up to git. We then run `poetry update` inside the CircleCI environment, and we get this error:
```
[NonExistentKey]
'Key "reference" does not exist.'

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/clikit/console_application.py", line 131, in run
    status_code = command.handle(parsed_args, io)
  File "/usr/local/lib/python3.8/site-packages/clikit/api/command/command.py", line 120, in handle
    status_code = self._do_handle(args, io)
  File "/usr/local/lib/python3.8/site-packages/clikit/api/command/command.py", line 171, in _do_handle
    return getattr(handler, handler_method)(args, io, self)
  File "/usr/local/lib/python3.8/site-packages/cleo/commands/command.py", line 92, in wrap_handle
    return self.handle()
  File "/usr/local/lib/python3.8/site-packages/poetry/console/commands/install.py", line 63, in handle
    return_code = installer.run()
  File "/usr/local/lib/python3.8/site-packages/poetry/installation/installer.py", line 74, in run
    self._do_install(local_repo)
  File "/usr/local/lib/python3.8/site-packages/poetry/installation/installer.py", line 165, in _do_install
    locked_repository = self._locker.locked_repository(True)
  File "/usr/local/lib/python3.8/site-packages/poetry/packages/locker.py", line 147, in locked_repository
    package.source_reference = info["source"]["reference"]
  File "/usr/local/lib/python3.8/site-packages/tomlkit/items.py", line 1008, in __getitem__
    return self._value[key]
  File "/usr/local/lib/python3.8/site-packages/tomlkit/container.py", line 540, in __getitem__
    raise NonExistentKey(key)
```

I'm a little confused though cause I looked through the codebase and found that `poetry/packages/locker.py` doesn't have code like `info["source"]["reference"]` but instead uses `source.get("reference")`. But this seems to be the problem because 1.1.4 doesn't populate the "reference" field in the `poetry.lock` file anymore.

Any suggestions would be great - we had to downgrade to 1.0.10 to get it to work!

**Comment by finswimmer** [comment]
Hello @keikumata,

which version of poetry is running in your CI env? The lock file format has changed in poetry 1.1. You can used lock files generated with poetry < 1.1 in newer version, but not lock file generated with 1.1 in older version.

fin swimmer

**Comment by keikumata** [comment]
@finswimmer we're running 1.1.4 in both the local environment and the CI env, which is why I was confused - double checked this a few times!

**Comment by finswimmer** [comment]
Hm,

the error message shows this:

```
  File "/usr/local/lib/python3.8/site-packages/poetry/packages/locker.py", line 147, in locked_repository
    package.source_reference = info["source"]["reference"]
```

In poetry 1.0.10 this line has moved to another line number and since poetry 1.1. this line doesn't exists at all.

Do you have installed poetry multiple times? According to the error message it seems to me this version was installed via pip. Check the output of `which -a poetry` to see if there might be multiple versions.

fin swimmer

**Comment by keikumata** [comment]
it turns out that was exactly right - we were by default using what was already installed via the CircleCI python image. We thought we were installing poetry using the poetry install script, but we weren't reloading the $PATH variable to use the latest version. 

closing this issue! thanks for the help!
