### ISSUE TITLE
jsonschema not listed as dependency

### ISSUE THREAD

**Issue by Anthchirp** [python-poetry/poetry#3319]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

The [poetry `pyproject.toml`](https://github.com/python-poetry/poetry/blob/master/pyproject.toml) does not list jsonschema as dependency, but the code does use it
https://github.com/python-poetry/poetry/blob/6b09639002e737e76a09eb973f0049262511d3f0/poetry/json/__init__.py#L7

Presumably this is how #1252 could happen.

**Comment by finswimmer** [comment]
Hello @Anthchirp,

`poetry` depends on `poetry.core` which [vendors some of it's dependencies](https://github.com/python-poetry/poetry-core/tree/master/poetry/core/_vendor). `jsonschema` is one of them.

fin swimmer

**Comment by abn** [comment]
@finswimmer if we use it in poetry we should explicitly require it I reckon. 

However, in this case we should simply drop `poetry.json` in favour of `poetry.core.json`.
