### ISSUE TITLE
wheel_file_re does not match version correctly

### ISSUE THREAD

**Issue by radek-sprta** [python-poetry/poetry#3320]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Debian 10.6
- **Poetry version**: 1.1.4
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gitlab.com/radek-sprta/blog/-/blob/master/pyproject.toml

## Issue
wheel_file_re fails to match version for packages with single digit versions. Example is `markdown-captions` package (filename `markdown_captions-2-py3-none-any.whl`). Results in the following error:

```
  • Installing markdown-captions (2): Failed

  AttributeError

  'NoneType' object has no attribute 'replace'

  at ~/.poetry/lib/poetry/installation/chooser.py:27 in __init__
       23│             raise InvalidWheelName("{} is not a valid wheel filename.".format(filename))
       24│ 
       25│         self.filename = filename
       26│         self.name = wheel_info.group("name").replace("_", "-")
    →  27│         self.version = wheel_info.group("ver").replace("_", "-")
       28│         self.build_tag = wheel_info.group("build")
       29│         self.pyversions = wheel_info.group("pyver").split(".")
       30│         self.abis = wheel_info.group("abi").split(".")
       31│         self.plats = wheel_info.group("plat").split(".")
```

**Comment by sinoroc** [comment]
I could recreate the issue with `poetry add markdown-captions`.

@python-poetry/triage
Seems like a severe enough bug.

**Comment by abn** [comment]
@python-poetry/triage

**Comment by matinalsun** [comment]
I could recreate the issue with ```poetry run bootstrap```

**Comment by finswimmer** [comment]
Fix is ready for review #3338

**Comment by dhiltonp** [comment]
#3411 adds a test for this issue with `Wheel`

**Comment by muppetjones** [comment]
Any update on when this fix will be merged and released?

**Comment by jma** [comment]
> Any update on when this fix will be merged and released?

+1

**Comment by stephsamson** [comment]
#3338 merged.
