### ISSUE TITLE
unable to install line_profiler on alpine linux with poetry

### ISSUE THREAD

**Issue by yoav-orca** [python-poetry/poetry#3323]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Alpine Linux 3.12
- **Poetry version**: 1.1.4
- **The contents of your pyproject.toml file**:
```
[tool.poetry]
name = "tmp"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

## Issue

I'm just running `poetry add line_profiler==3.0.2`

I checked, the (pyproject.toml)[https://github.com/pyutils/line_profiler/blob/3.0.2/pyproject.toml] in line_profiler and it seems to have the right dependencies specified:
```
requires = ["setuptools>=41.0.1", "wheel",  "Cython", "scikit-build>=0.9.0", "cmake", "ninja"]
```

What am I missing?

```
Updating dependencies
Resolving dependencies... (0.1s)

Package operations: 1 install, 0 updates, 0 removals

  • Installing line-profiler (3.0.2): Failed

  EnvCommandError

  Command ['/root/.cache/pypoetry/virtualenvs/tmp-6WcazSRI-py3.8/bin/pip', 'install', '--no-deps', 'file:///root/.cache/pypoetry/artifacts/92/8f/42/023009ff7541406233be546798fbb9b4ba9d352a9c56ca9a2600bf603e/line_profiler-3.0.2.tar.gz'] errored with the following return code 1, and output:
  Processing /root/.cache/pypoetry/artifacts/92/8f/42/023009ff7541406233be546798fbb9b4ba9d352a9c56ca9a2600bf603e/line_profiler-3.0.2.tar.gz
    Installing build dependencies: started
    Installing build dependencies: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /root/.cache/pypoetry/virtualenvs/tmp-6WcazSRI-py3.8/bin/python /root/.cache/pypoetry/virtualenvs/tmp-6WcazSRI-py3.8/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-5dk4quz7/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=41.0.1' wheel Cython 'scikit-build>=0.9.0' cmake ninja
         cwd: None
    Complete output (23 lines):
    Collecting setuptools>=41.0.1
      Using cached setuptools-50.3.2-py3-none-any.whl (785 kB)
    Collecting wheel
      Using cached wheel-0.35.1-py2.py3-none-any.whl (33 kB)
    Collecting Cython
      Using cached Cython-0.29.21-py2.py3-none-any.whl (974 kB)
    Collecting scikit-build>=0.9.0
      Using cached scikit_build-0.11.1-py2.py3-none-any.whl (72 kB)
    Collecting cmake
      Using cached cmake-3.18.2.post1.tar.gz (28 kB)
        ERROR: Command errored out with exit status 1:
         command: /root/.cache/pypoetry/virtualenvs/tmp-6WcazSRI-py3.8/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-spn21evz/cmake/setup.py'"'"'; __file__='"'"'/tmp/pip-install-spn21evz/cmake/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-il31iqnt
             cwd: /tmp/pip-install-spn21evz/cmake/
        Complete output (5 lines):
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
          File "/tmp/pip-install-spn21evz/cmake/setup.py", line 7, in <module>
            from skbuild import setup
        ModuleNotFoundError: No module named 'skbuild'
        ----------------------------------------
    ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
    WARNING: You are using pip version 20.2.2; however, version 20.2.4 is available.
    You should consider upgrading via the '/root/.cache/pypoetry/virtualenvs/tmp-6WcazSRI-py3.8/bin/python -m pip install --upgrade pip' command.
    ----------------------------------------
  ERROR: Command errored out with exit status 1: /root/.cache/pypoetry/virtualenvs/tmp-6WcazSRI-py3.8/bin/python /root/.cache/pypoetry/virtualenvs/tmp-6WcazSRI-py3.8/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-5dk4quz7/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=41.0.1' wheel Cython 'scikit-build>=0.9.0' cmake ninja Check the logs for full command output.
  WARNING: You are using pip version 20.2.2; however, version 20.2.4 is available.
  You should consider upgrading via the '/root/.cache/pypoetry/virtualenvs/tmp-6WcazSRI-py3.8/bin/python -m pip install --upgrade pip' command.
```

**Comment by sinoroc** [comment]
More or less the situation (writing off the top of my head, I will most likely have some details wrong):

You are running on Alpine Linux. Alpine Linux uses a different C standard library than all other common Linux distributions (_musl_ instead of _glibc_).

At least one of the dependencies (in that case _line-profiler_), seem to have C extensions that need to be compiled. There are pre-compiled _wheels_ for that project, but not for all platforms, and definitely not for your Alpine based container with its alternative C standard library.

**Comment by yoav-orca** [comment]
Hi @sinoroc the module `skbuild` is provided `scikit-build` and is specified in the `requires` part of the `[build-system]` part of the pyproject.toml for `line_profiler`. 
It should support installing `skbuild` before calling setup.py as part of poetry, right?

**Comment by sinoroc** [comment]
Seems to me like the triggering issue is in the packaging of `cmake`.

It seems to be packaged with _setuptools_. Its [`setup.py` wants to do the import `from skbuild import setup`](https://github.com/scikit-build/cmake-python-distributions/blob/3.18.2.post1/setup.py#L7), which I assume comes from the `scikit-build` project (I did not check). But at the time _pip_ attempts to build `cmake` (runt its `setup.py`), its build dependency `scikit-build` is not fully installed and importable yet.

This `cmake` project should probably add a `pyproject.toml` with something like:

```
[build-system]
requires = [
    'setuptools',
    'scikit-build',
    # ...
]
```

**Comment by yoav-orca** [comment]
@sinoroc thanks for the quick analysis, I opened a PR for `cmake` https://github.com/scikit-build/cmake-python-distributions/pull/119 for fixing this. 
What can I do to work around this issue using poetry?

**Comment by sinoroc** [comment]
I do not think you can solve this with _poetry_ alone. Nothing that comes to mind. There are for sure solutions, but they need more tooling than just poetry.

In short, you need to ***build a wheel of `line-profiler` in advance*** so that you can reuse it in your poetry environment. In case you are using Docker containerization (which I assumed earlier, but maybe that is not the case), you could do it in an early stage of a multi-stage build.

Anyway with or without containerization, you will probably need to create a clean virtual environment, install ` scikit-build` (and other build dependencies), then install `cmake` without _build isolation_ (so that the installed scikit-build can be imported), and finally build a wheel of `line-profiler` in that environment without using _build isolation_ (so that the installed cmake can be used/imported). Something like the following (you may have to tweak the order):

```
pythonX.Y -m venv env
env/bin/python -m pip install 'setuptools>=41.0.1' 'Cython' 'scikit-build>=0.9.0' 'ninja'
env/bin/python -m pip install --no-build-isolation 'cmake'
env/bin/python -m pip wheel --no-build-isolation --no-deps 'line-profiler'
```

Once the wheel of `line-profiler` is built you will have to figure out how you want to add it to your poetry environment.

**Comment by yoav-orca** [comment]
Thanks, I would have loved for it to be an easier way to work around issues

**Comment by sinoroc** [comment]
> Thanks, I would have loved for it to be an easier way to work around issues

Probably there is an easier way. I would need to try the whole thing, and it is not really related to poetry as far as I can tell. I might be wrong, though, so feel free to reopen the ticket if needed. Good luck!
