### ISSUE TITLE
Installing cryptography on system using poetry fails

### ISSUE THREAD

**Issue by yoav-orca** [python-poetry/poetry#3329]
- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 18.04, python3.8 
- **Poetry version**: 1.1.4
- **contents of your pyproject.toml file**:
```ini
[tool.poetry]
name = "poetry_bug"
version = "0.1.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

## Issue
The issue, installing `cryptography` within a virtualenv works, but I configure `poetry config virtualenvs.create false` and try to install it fails.

It seems that for the virtualenv poetry selects `cryptography-3.2.1-cp35-abi3-manylinux1_x86_64.whl`, however for the system install it selects `cryptography-3.2.1-cp35-abi3-manylinux2010_x86_64.whl`.

The following Dockerfile reproduces the issue:
```Dockerfile
FROM ubuntu:18.04

RUN apt update && apt install -y python3.8 python3-pip curl git
RUN python3.8 -m pip install poetry
ADD pyproject.toml .
RUN poetry config virtualenvs.create false
RUN poetry add cryptography==3.2.1
```

**Comment by sinoroc** [comment]
What is the error message if any?

**Comment by sinoroc** [comment]
I quickly tried something, and looks like you may need to update _pip_, before trying to install `cryptography`. Did not dig in deeper to figure out why exactly, but in my quick test `cryptography` installed perfectly after upgrading _pip_.

Something like:

```
FROM ubuntu:18.04

RUN apt update && apt install -y python3.8 python3-pip curl git
RUN python3.8 -m pip install --upgrade pip
RUN python3.8 -m pip install poetry
ADD pyproject.toml .
RUN poetry config virtualenvs.create false
RUN poetry add cryptography==3.2.1
```

**Comment by yoav-orca** [comment]
Wow apparently the default version used by Ubuntu is `pip 9.0.1` and latest is `pip 20.2.4`.
Does poetry have a troubleshooting guide that I can contribute to this advice?

**Comment by sinoroc** [comment]
> the default version used by Ubuntu is `pip 9.0.1`

Yes, usually the default _pip_ is quite old (especially on Debian/Ubuntu as far as I know).

> Does poetry have a troubleshooting guide that I can contribute to this advice?

There is a [FAQ](https://python-poetry.org/docs/faq/), but I do not think this issue has much to do with _poetry_. _poetry_'s defaults prevent you from running into such issues so easily, because by default it uses virtual environments created by _virtualenv_ which installs recent _pip_ versions.

By deciding to opt out of this with `poetry config virtualenvs.create false` you have to somehow take parts of the responsibility of what happens next.

---

Why are you deactivating the virtual environment creation?

**Comment by yoav-orca** [comment]
I'm trying to use poetry to install all dependencies as global in a container, we are migrating away from pipenv and in pipenv we just used `pipenv install --system`.

Thanks again!

**Comment by Casyfill** [comment]
Having the same issue with cryptography, but on the newest `poetry` and with the newest pip....


end of the log:
```
    /Users/philippk/anaconda3/include/openssl/x509.h:573:45: note: passing argument to parameter 'palg' here
                               const X509_ALGOR **palg, const X509 *x);
                                                  ^
      54 warnings and 4 errors generated.
      error: command 'gcc' failed with exit status 1
      ----------------------------------------
  ERROR: Command errored out with exit status 1: /Users/philippk/Dropbox/se_projects/4_Automation/se_research/.venv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/jx/385bflkd3ldghxp3chpylgv00000gn/T/pip-req-build-u8gympth/setup.py'"'"'; __file__='"'"'/private/var/folders/jx/385bflkd3ldghxp3chpylgv00000gn/T/pip-req-build-u8gympth/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/jx/385bflkd3ldghxp3chpylgv00000gn/T/pip-record-wny5lf4q/install-record.txt --single-version-externally-managed --compile --install-headers /Users/philippk/Dropbox/se_projects/4_Automation/se_research/.venv/include/site/python3.7/cryptography Check the logs for full command output.
  

  at ~/.poetry/lib/poetry/utils/env.py:1074 in _run
      1070│                 output = subprocess.check_output(
      1071│                     cmd, stderr=subprocess.STDOUT, **kwargs
      1072│                 )
      1073│         except CalledProcessError as e:
    → 1074│             raise EnvCommandError(e, input=input_)
      1075│ 
      1076│         return decode(output)
      1077│ 
      1078│     def execute(self, bin, *args, **kwargs):

(base) ZG00021:se_research philippk$ 
```

pip is the latest one (but had issue with the earlier one as well) : `pip 21.0.1`
Poetry version 1.1.5
