### ISSUE TITLE
Poetry command to clean the package.

### ISSUE THREAD

**Issue by asiddaramappa** [python-poetry/poetry#3331]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request
Developers often want to clean the package of any file or folder which are automatically generated by the tool.
For example, developers want to remove "dist", pkg.egg-info and poetry.lock file. Probably even remove the virtual environment created as part of this package. 
It should not make any changes to pyproject.toml or any other file created/modified by developer intentionally.
This will help in ensuring that the cleaned code works fine even if other download it from github.
This feature can be easily achieved by a simple shell script to remove these files/folders. However it will be more elegant if there is a command line option in poetry in-built.
Example: "poetry clean"
This should remove dist, pkg.egg-info and poetry.lock file. It should also remove any environment created for the package.

**Comment by sinoroc** [comment]
@asiddaramappa Any details of what exactly you expect out of this command? What should be cleaned?

**Comment by asiddaramappa** [comment]
Sincere apologies. I had added details in the description, but missed removing comment tags. I have removed the comment tags now. Please see the Feature Request section above.

**Comment by tclasen** [comment]
I want to +1 this feature request and also add in a [tool.poetry] section or key to the pyproject.toml to also specify a list of files / directories to additionally remove. This way I can specify my .pytest_cache, .mypy_cache, and even the more exotic items such as .hypothesis_cache

**Comment by gotofritz** [comment]
I agree with the general idea, but it should NOT remove poetry.lock - that is supposed to be committed to the repo and is needed to create builds with predictable component versions.

**Comment by shaw-matt** [comment]
I want to +1 this feature as well as all of the previous comments.

**Comment by tclasen** [comment]
> I agree with the general idea, but it should NOT remove poetry.lock - that is supposed to be committed to the repo and is needed to create builds with predictable component versions.

Maybe add a flag to remove the poetry.lock? `--remove-lock`? But if I had to choose I would agree that the lock should not be removed.

**Comment by abn** [comment]
I doubt this is something we would want to do within Poetry. You can create a plugin if you really would like a command like this. See https://github.com/python-poetry/poetry-plugin-export for an example of a command plugin.

While Poetry can guess what the user wants to clean, that seems like a bad idea as there are always various opinions out there. And honestly, I do not think it make sense for Poetry to remove files it does not create.

Additionally, how is this different from `git clean -fx`? I get that that might not work for unversioned code bases, but ... :) 

Closing this as if there is a desire in the community for this - a plugin is better suited for this purpose.
