### ISSUE TITLE
Poetry installation gets linked with native python 2.7 in macOS, instead of using python3

### ISSUE THREAD

**Issue by tropxy** [python-poetry/poetry#3340]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: <Darwin  19.6.0 Darwin Kernel Version 19.6.0: Sun Jul  5 00:43:10 PDT 2020; root:xnu-6153.141.1~9/RELEASE_X86_64 x86_64; macOS 10.15.6 (19G73)>
- **Poetry version**: <^1.0.5>
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: <Not Relevant>

## Issue

Hi,

My problem started with version 1.0.5 and in an attempt to try to solve it, I have uninstalled this version and installed the most recent one, however the problem described below persisted. I have uninstalled 1.0.5 poetry version by issuing 

```shell
/System/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7 get-poetry.py --uninstall
```

After that, I have installed poetry using the recommended command in the docs, specifying python3:
```shell
curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3 -
```
The installation successfully finishes as expected.
<img width="728" alt="Bildschirmfoto 2020-11-08 um 01 02 11" src="https://user-images.githubusercontent.com/12515990/98453858-16514780-215e-11eb-88b2-fcd2a8b3419d.png">

However, poetry gets linked to the native python 2.7 distribution on Mac, instead of getting linked to the python3 version installed:
<img width="958" alt="Bildschirmfoto 2020-11-08 um 01 04 28" src="https://user-images.githubusercontent.com/12515990/98453884-71833a00-215e-11eb-841c-0eccb5a17162.png">

<img width="662" alt="Bildschirmfoto 2020-11-08 um 01 05 39" src="https://user-images.githubusercontent.com/12515990/98453904-95468000-215e-11eb-99a3-44b94e8980d2.png">

The correct python version gets linked to the poetry installation only if I install it using pip:
```shell
> pip3 install poetry 
```

<img width="663" alt="Bildschirmfoto 2020-11-08 um 01 10 22" src="https://user-images.githubusercontent.com/12515990/98453962-4220fd00-215f-11eb-8e13-ddbfed6abc5c.png">

Thus, now everything works, but still, I assume the way I have tried to install it should have worked as well. I have checked other issues that were similar, like this one:
https://github.com/python-poetry/poetry/issues/655

But here the problem was more about poetry not picking up the correct virtual env, which is not an issue, in my case.

Thank you all!

**Comment by finswimmer** [comment]
Hello @tropxy,

this is intended behavior and was discussed before (#3184, #3288) Please see my comments about the why: https://github.com/python-poetry/poetry/issues/3184#issuecomment-707786235 , https://github.com/python-poetry/poetry/issues/3288#issuecomment-716994034

fin swimmer
