### ISSUE TITLE
poetry always uses wrong python version

### ISSUE THREAD

**Issue by magnusja** [python-poetry/poetry#3342]
- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**:  macOS mojave
- **Poetry version**:  1.1.4
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/magnusja/4a3c11b310d5e3a70e7186593310b5d5

## Issue

```
~/D/c/d/backend.service.ocr 🔥🔥 cat .python-version
3.8.6⏎                                                                                                                                      
~/D/c/d/backend.service.ocr 🔥🔥 python --version
Python 3.8.6
~/D/c/d/backend.service.ocr 🔥🔥 pyenv shell 3.8.6  # just to be really sure ..
~/D/c/d/backend.service.ocr 🔥🔥 poetry install
The currently activated Python version 3.9.0 is not supported by the project (3.8.6).
Trying to find and use a compatible version.
Using python3 (3.8.6)
Installing dependencies from lock file

Package operations: 82 installs, 0 updates, 0 removals

    • Installing ipython-genutils (0.2.0): Cancelled
~/D/c/d/backend.service.ocr [1] 🔥🔥 poetry run python --version
The currently activated Python version 3.9.0 is not supported by the project (3.8.6).
Trying to find and use a compatible version.
Using python3 (3.8.6)
Python 3.9.0
```

**Comment by finswimmer** [comment]
Hello @magnusja,

how did you install poetry? Could it be that you set `virtualenvs.create` to `false`? (look at the output of `poetry config --list`)

fin swimmer

**Comment by magnusja** [comment]
Hey,

Installed it over homebrew. 

```
poetry config --list
cache-dir = "/Users/magnus/Library/Caches/pypoetry"
experimental.new-installer = true
installer.parallel = true
virtualenvs.create = true
virtualenvs.in-project = null
virtualenvs.path = "{cache-dir}/virtualenvs"  # /Users/magnus/Library/Caches/pypoetry/virtualenvs
```

**Comment by magnusja** [comment]
So this indeed works when using the curl installing method instead of homebrew.

I noticed these additions to the path, not sure if these might interfere and cause the problem:
```
cat /usr/local/bin/poetry
#!/usr/local/opt/python@3.9/bin/python3
import sys

sys.path.insert(0, "/usr/local/Cellar/poetry/1.1.4/libexec/lib/python3.9/site-packages")
sys.path.insert(0, "/usr/local/Cellar/poetry/1.1.4/libexec/vendor/lib/python3.9/site-packages")

if __name__ == "__main__":
    from poetry.console import main
    main()
```

**Comment by finswimmer** [comment]
Hello @magnusja,

ok that's in expected behavior. Your package manager changes the shebang, so poetry cannot pickup the python version, which is currently activated, to create the new venv. You have to run `poetry env use /path/to/python` first in your case, to point to the python that should be used in the new venv. See also my comment  here https://github.com/python-poetry/poetry/issues/3288#issuecomment-716994034

fin swimmer

**Comment by magnusja** [comment]
So I couldnt really believe that, and wrote a little test script:

```python
#!/usr/local/opt/python@3.9/bin/python3
import sys
import os

sys.path.insert(0, "/usr/local/Cellar/poetry/1.1.4/libexec/lib/python3.9/site-packages")
sys.path.insert(0, "/usr/local/Cellar/poetry/1.1.4/libexec/vendor/lib/python3.9/site-packages")

if __name__ == "__main__":
    os.system("which python")
    os.system("python --version")
```

which gives

```
~/D/c/l/shopfloor (feature/adapt-box-detection|…) 🔥🔥 ./test.py
/Users/magnus/.pyenv/shims/python
Python 3.7.5
```

so clearly it is possible for poetry to get the correct python env. 

Also imho if this is expected behavior you are following an incredibly bad & flawed UX. Basically poetry is telling me it is using python 3.8 and lying to my face instead of throwing an error. It took me quite a while to figure that out ...

**Comment by magnusja** [comment]
```
~/D/c/l/r/h/training (develop|✚4…) 🔥🔥 pyenv shell 3.8.5
                                                                                                                                   [ 0s053 | Dec 08 05:02PM ]
~/D/c/l/r/h/training (develop|✚4…) 🔥🔥 poetry env use /home/magnus/.pyenv/shims/python
Creating virtualenv training-9MFdeoy7-py3.8 in /home/magnus/.cache/pypoetry/virtualenvs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'PosixPath' is not defined
Using virtualenv: /usr
                                                                                                                                   [ 0s951 | Dec 08 05:02PM ]
~/D/c/l/r/h/training (develop|✚4…) 🔥🔥 poetry run python
Python 3.9.0 (default, Oct  7 2020, 23:09:01) 
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```
The `env` also seems broken
