### ISSUE TITLE
Unable to install poetry after Uninstalling

### ISSUE THREAD

**Issue by AshwinNS** [python-poetry/poetry#3343]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS 10.15.7
- **Poetry version**: N/A

## Issue
I accedentally misconfigured my poetry installation to `python2.7`, once i uninstalled and tried reinstalling(using installer), tool kept showing `uninstall` process message and was not installing.
 
## Steps to reproduce
- Uninstall the tool by setting environment variable `POETRY_UNINSTALL=1` and running `installer` with `--uninstall` arg

- Try installing the tool back using the installer(now with `python3` option in my case)
(curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3 -)
Terminal output provided below
```debug18:~ ashwin$ curl -H 'Cache-Control: no-cache' -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3 -
# We are sorry to see you go!

This will uninstall Poetry.

It will remove the `poetry` command from Poetry's bin directory, located at:

$HOME/.poetry/bin

This will also remove Poetry from your system's PATH.
```

Unsetting `POETRY_UNINSTALL` environment variable and run installer again, this makes the tool install. 

The `installer` should check and unset/not check the `POETRY_UNINSTALL` env variable if the user is trying to `install` the tool.

**Comment by AshwinNS** [comment]
By the code it looks like setting `POETRY_UNINSTALL=0` also can solve this problem.

**Comment by finswimmer** [comment]
Hello @AshwinNS,

how should the script know whether you set this env var by accident or explicit? It's the users responsibility to check with which parameter a script is started.

> Try installing the tool back using the installer(now with python3 option in my case)

Be aware that afterwards poetry will still run with the python version `python` links to. See https://github.com/python-poetry/poetry/issues/3288.

fin swimmer

**Comment by AshwinNS** [comment]
Thank you for sharing  [#3288](https://github.com/python-poetry/poetry/issues/3288), I was facing this issue. I wanted to document this issue in the `issues list` as new devs might face this issue and help them in future. Issue is trivial I do agree. ☺️
