### ISSUE TITLE
`poetry show package` doesn't work with private registry whereas `poetry add package` works!

### ISSUE THREAD

**Issue by limonkufu** [python-poetry/poetry#3351]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x]  I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS 10.15.7
- **Poetry version**: 1.1.4
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/Limonkufu/d30d72169ee833a0ceee55ab248cd558

## Issue

Hi when I try `poetry show package` with a seperate repository defines as above it fails even though I am able to install the package by `poetry add package`. After installing it `poetry show package` works.

Stack trace of `poetry show package`:
```
  Stack trace:

  4  ~/.poetry/lib/poetry/_vendor/py3.8/clikit/console_application.py:131 in run
      129│             parsed_args = resolved_command.args
      130│
    → 131│             status_code = command.handle(parsed_args, io)
      132│         except KeyboardInterrupt:
      133│             status_code = 1

  3  ~/.poetry/lib/poetry/_vendor/py3.8/clikit/api/command/command.py:120 in handle
      118│     def handle(self, args, io):  # type: (Args, IO) -> int
      119│         try:
    → 120│             status_code = self._do_handle(args, io)
      121│         except KeyboardInterrupt:
      122│             if io.is_debug():

  2  ~/.poetry/lib/poetry/_vendor/py3.8/clikit/api/command/command.py:171 in _do_handle
      169│         handler_method = self._config.handler_method
      170│
    → 171│         return getattr(handler, handler_method)(args, io, self)
      172│
      173│     def __repr__(self):  # type: () -> str

  1  ~/.poetry/lib/poetry/_vendor/py3.8/cleo/commands/command.py:92 in wrap_handle
       90│         self._command = command
       91│
    →  92│         return self.handle()
       93│
       94│     def handle(self):  # type: () -> Optional[int]

  ValueError

  Package <redacted> not found

  at ~/.poetry/lib/poetry/console/commands/show.py:99 in handle
       95│                     pkg = locked
       96│                     break
       97│
       98│             if not pkg:
    →  99│                 raise ValueError("Package {} not found".format(package))
      100│
      101│             if self.option("tree"):
      102│                 self.display_package_tree(self.io, pkg, locked_repo)
      103│

```

`poetry add package`:
```
X: 1 packages found for <redacted> *
PyPI: No packages found for <redacted> *
Using version ^0.1.1 for <redacted>

Updating dependencies
Resolving dependencies...
   1: fact: test is 0.1.0
   1: derived: test
   1: fact: test depends on <redacted> (^0.1.1)
   1: selecting test (0.1.0)
   1: derived: <redacted> (^0.1.1)
X: 1 packages found for <redacted> >=0.1.1,<0.2.0

... Rest is same as usual ...
```

I have come across similar issues for this for `poetry add` but could find the issue ids. Maybe the solution wasn't reflected to `show` command.

**Comment by ralbertazzi** [comment]
`poetry show` is now perfectly able to handle both packages installed from pypi and from private repositories. I think you may have misunderstood its purpose: the command shows information on locked dependencies and not on dependencies that you haven't installed yet, i.e. it doesn't query pypi or your repository.
