### ISSUE TITLE
the name of artifact

### ISSUE THREAD

**Issue by zillionare** [python-poetry/poetry#3356]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

After run peotry build, I get whl file with name as xxx-0.7.0-py3-none-any.whl

I need to indicate that the package works on linux only, i.e, I need a name like:

xxx-0.7.0-py3-linux.whl

how should I get this? Found no documentation about specify sys.platform. I tried to put it under:
```
[build-system]
sys.platform='linux'

```
with no luck.

Thanks for help!

**Comment by sinoroc** [comment]
As far as I know, the tags in the wheel name are meant to restrict the environment in which the wheel can be installed. If you want to restrict the environments your project is compatible with, you should specify the right [_trove classifiers_](https://pypi.org/classifiers/).

Trove classifiers are mostly informal (as far as I remember). They won't really prevent someone on Windows to install your project, but it's on them to check the classifiers and the documentation of your project before hand.

The wheel tags, are here to prevent to install in an environment where installation itself would most likely fail. Trove classifiers can inform (loosely) about what platforms it should run on, in other words it inform that the project would most likely fail at run-time (not at install-time) on other platforms.

Here is how to set them in a poetry project:

```
[tool.poetry]
# ...
classifiers = [
    "Operating System :: POSIX :: Linux",
]
```

* https://python-poetry.org/docs/pyproject/#classifiers

**Comment by filmor** [comment]
Classifiers are not an adequate replacement for precise build tags. This has been requested before in https://github.com/python-poetry/poetry/issues/2051, and I also require support for this. Right now, the logic is extremely simple (i.e. `py3-any` for packages that don't use a build script and a very precise one otherwise).

**Comment by sinoroc** [comment]
Alright, should we close this ticket in favour of the other one?

Duplicate: https://github.com/python-poetry/poetry/issues/2051
