### ISSUE TITLE
Poetry fails silently with broken/missing pip

### ISSUE THREAD

**Issue by ericriff** [python-poetry/poetry#3357]
- **OS version and name**: Ubuntu 18
- **Poetry version**: 1.1.3

We recently integrated poetry to a big project and I've noticed that it doesn't check pip's integrity or handle it being broken/missing well.

One example is pip config file being broken, which leads to poetry install failing silently:
```
$ python3.6 -m pip3 --version
Configuration file could not be loaded.
File contains no section headers.
file: '/home/dev/.pip/pip.conf', line: 1
```
In this situation `poetry install` lists the packages to install, remove and skip and then exits, without doing anything and without any message, error or warning.

A different scenario we've found is missing `pip`, which leads `poetry install` to get stuck forever on `Pending..`

```
$ python3 -m pip --version
no module named pip
```
Then `poetry install` list a few packages to install with status `Pending ...` and gets stuck there forever.

I know that this info is not nearly good enough but since it happened in different developers PCs is hard to get more data.

**Comment by logan-bobo** [comment]
Hey @ericriff, this issue does not look to exist in later versions of poetry (1.2.1) I have just attempted to replicate your issue there and got the following results.
```
# python3 -m pip --version
/usr/local/bin/python3: No module named pip

# poetry install
Installing dependencies from lock file

Package operations: 6 installs, 0 updates, 0 removals

  • Installing markupsafe (2.1.1)
  • Installing click (8.1.3)
  • Installing itsdangerous (2.1.2)
  • Installing jinja2 (3.1.2)
  • Installing werkzeug (2.2.2)
  • Installing flask (2.2.2)
```

Setting issue to closed. I recommend running on the latest version.
