### ISSUE TITLE
Provide standalone poetry binary

### ISSUE THREAD

**Issue by abergmeier** [python-poetry/poetry#3360]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request
Especially for Windows, installing Python is not as immediate as for Linux.
Thus I wonder whether it would make sense to package poetry in an executable and also add a working Python runtime, so that you can use poetry on a fresh system.
Bonus points for statically compiling a libc.

**Comment by gragib** [comment]
I second this. My current workaround is to
```
pipx install poetry
```

**Comment by gi0baro** [comment]
FYI, I'm doing this @ https://github.com/gi0baro/poetry-bin

I'm not sure how much the community and maintainers are interested into this. Technically speaking, I made some patches even on poetry and poetry-core dependencies, then even if community express its interest, it would probably require a new battery of tests to validate accurately also the patches.

**Comment by Secrus** [comment]
The Poetry team decided against maintaining any package format other than Python wheels. Providing binaries for multiple OS/distros would require a lot of time put into maintaining such packages and we are stretched thin as it is.

**Comment by gi0baro** [comment]
For those interested reaching this, the [poetry-bin](https://github.com/gi0baro/poetry-bin) project is all about this and maintained.

**Comment by hemnstill** [comment]
I have also build standalone version for windows and linux (on musl toolset)

Its working without any patches

https://github.com/hemnstill/StandaloneTools/releases?q=poetry
