### ISSUE TITLE
Incorrect installation of extras packages for multiple conditions

### ISSUE THREAD

**Issue by xkumiyu** [python-poetry/poetry#3361]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

- **OS version and name**: macOS 10.15
- **Poetry version**: 1.1.4

## Issue

```
[tool.poetry.dependencies]
python = "^3.8"
requests = [
    { version = "==2.24.0", python = "~3.8", optional = true },
    { version = "==2.25.0", python = "~3.9", optional = true }
]

[tool.poetry.extras]
req = ["requests"]

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

When I install my package geneated by `poetry build` with the above `pyproject.toml` file, I don't think it behaves correctly under some conditions.

Specifically, when I run `pip install my_package-0.1.0-py3-none-any.whl`,
- in python 3.9
  - expected: not install
  - actual: `requests==2.25.0` is installed. <- **Incorrect!**
- in python 3.8
  - expected: not install
  - actual: not install

I think there is a problem with the files generated by `poetry build`, as it works correctly with `poetry install`.

**Comment by sinoroc** [comment]
Could you extract the `METADATA` file of the `.whl` archive (it is a zip file, so you can just unzip it), and post here the lines `Requires-Dist: request ...` to inspect them?

**Comment by xkumiyu** [comment]
The `METADATA` file says the following:

```
...
Provides-Extra: req
Requires-Dist: requests (==2.24.0); (python_version >= "3.8" and python_version < "3.9") and (extra == "req")
Requires-Dist: requests (==2.25.0); python_version >= "3.9" and python_version < "3.10"
```

There is no mention of `extra == "req"` in python 3.9.

**Comment by sinoroc** [comment]
OK, looks to me like you found a bug indeed. Let's wait until one of the maintainers gets to this...

**Comment by xkumiyu** [comment]
@sinoroc Thanks for your reply! If you know of a workaround, please let me know.

**Comment by logileifs** [comment]
Same thing happening for me. Does nobody have a workaround or know if this works in an older version?

**Comment by dimbleby** [comment]
metadata today says:
```
Requires-Dist: requests (==2.24.0); (python_version >= "3.8" and python_version < "3.9") and (extra == "req")
Requires-Dist: requests (==2.25.0); (python_version >= "3.9" and python_version < "3.10") and (extra == "req")
```
which is correct, this can be closed
