### ISSUE TITLE
Poetry Hangs Indefinitely Resolving Dependencies

### ISSUE THREAD

**Issue by KyleKing** [python-poetry/poetry#3365]
- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
    - The only problem that might be related is #2699, but that was for the case of a private repository
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

---

- **OS version and name**: MacOS Catalina 10.15.7
- **Python**: miniconda Python 3.8.3
- **Poetry version**: 1.1.4
- **~Link of a Gist with~ the contents of your pyproject.toml file**: See detail section below (click arrow to expand)

<details>
  <summary>Simple pyproject.toml file with only a single dev-dep on pytest</summary>  
<pre><code>

[tool.poetry]
name = "spinning"
version = "0.1.0"
description = ""
authors = ["Kyle King <KyleKing@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
</code></pre>
</details>

## Issue

Poetry gets stuck resolving dependencies indefinitely. I've let it run for over ten minutes, but resolving dependencies should reasonably take only a few seconds or at least within a minute

I  tried uninstalling poetry, different versions of poetry, and removing the .venv and lock file but the problem still exists. I think this could be a problem with my computer, like a cache file or setting that is preventing poetry from accessing a networked resource, but the verbose debugging output doesn't indicate where poetry is held up

```sh
> conda activate base
> poetry lock
Creating virtualenv spinning in /Users/kyleking/Developer/Werk/__LocalProjects/spinning/.venv
Updating dependencies
Resolving dependencies... (333.3s)^C
> poetry install
Updating dependencies
Resolving dependencies... (215.7s)^C
>  poetry lock -vvv
Using virtualenv: /Users/kyleking/Developer/Werk/__LocalProjects/spinning/.venv
Updating dependencies
Resolving dependencies...
   1: fact: spinning is 0.1.0
   1: derived: spinning
   1: fact: spinning depends on pytest (*)
   1: fact: spinning depends on pytest (*)
   1: selecting spinning (0.1.0)
   1: derived: pytest (*)
PyPI: 141 packages found for pytest *
   1: fact: pytest (6.1.2) depends on attrs (>=17.4.0)
   1: fact: pytest (6.1.2) depends on iniconfig (*)
   1: fact: pytest (6.1.2) depends on packaging (*)
   1: fact: pytest (6.1.2) depends on pluggy (>=0.12,<1.0)
   1: fact: pytest (6.1.2) depends on py (>=1.8.2)
   1: fact: pytest (6.1.2) depends on toml (*)
   1: fact: pytest (6.1.2) depends on importlib-metadata (>=0.12)
   1: fact: pytest (6.1.2) depends on atomicwrites (>=1.0)
   1: fact: pytest (6.1.2) depends on colorama (*)
   1: selecting pytest (6.1.2)
   1: derived: colorama (*)
   1: derived: atomicwrites (>=1.0)
   1: derived: importlib-metadata (>=0.12)
   1: derived: toml (*)
   1: derived: py (>=1.8.2)
   1: derived: pluggy (>=0.12,<1.0)
   1: derived: packaging (*)
   1: derived: iniconfig (*)
   1: derived: attrs (>=17.4.0)
PyPI: 42 packages found for colorama *
PyPI: 7 packages found for atomicwrites >=1.0
PyPI: 27 packages found for importlib-metadata >=0.12
PyPI: 16 packages found for toml *
PyPI: No release information found for py-0.8.0-alpha2, skipping
PyPI: No release information found for py-0.9.0, skipping
PyPI: No release information found for py-1.4.32.dev1, skipping
PyPI: 2 packages found for py >=1.8.2
^C   1: Version solving took 32.510 seconds.
   1: Tried 1 solutions.
```

(Note: see ^C for when I had to stop the processes)

**Comment by sinoroc** [comment]
Duplicate? https://github.com/python-poetry/poetry/issues/2094

**Comment by KyleKing** [comment]
Thanks, I think this is the same issue as 2094 and possibly related to #3200 as well

**Comment by taylorkangbeck** [comment]
In case anyone else comes here searching, it might also be a pip problem. Setting `export PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring` worked for me.
(See https://github.com/pypa/pip/issues/7883)
