### ISSUE TITLE
Build and publsih conda package

### ISSUE THREAD

**Issue by erwanbodere** [python-poetry/poetry#3376]
Since we can export a package to `wheel` and `sdist`, it would be great to export the package in `conda` format.

```bash
poetry build --format conda
```

There is a plugin `poetry2conda` (https://github.com/dojeda/poetry2conda), but it only exports an `environment.yaml` file.

I propose to create a plugin, which :
- create a meta.yaml file
- execute the command `conda-build .`

Then, it would be great to publish the conda package :

```bash
poetry publish --target conda -r <conda_repo>
```

See the official documentation : https://docs.conda.io/projects/conda-build/en/latest/user-guide/tutorials/build-pkgs.html

**Comment by daniellivingston** [comment]
Bump - any update?

**Comment by finswimmer** [comment]
Hello,

conda has its own ecosystem. Supporting it is out of scope for Poetry, because it would make things much more complex.

Maybe the requested feature is something someone can provide by a [Plugin](https://python-poetry.org/docs/master/plugins/)?
