### ISSUE TITLE
Cannot import the installed package in a subdirectory

### ISSUE THREAD

**Issue by hyliu1989** [python-poetry/poetry#3379]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

poetry is awesome and handles the installation headache. I wonder if we can make the installed package visible inside the poetry virtual environment. Considering the following structure, when I start `poetry shell` in `test-module/script/`, not in the top level `test-module/`, the `import testmodule` does not work. I need this in order to develop some scripts and those scripts are part of the release. It is getting messy to put everything in the top directory.

It would be nice to have 
1. an option in pyproject.toml to make `testmodule` editable and put it in the search path of the virtual environment. This way `testmodule` is visible regardless when the shell is invoked. Or,
1. an option in pyproject.toml to install `testmodule` into the site-packages/ path.

## File system
```
test-module/
  + pyproject.toml
  + testmodule/
      + __init__.py
  + script/
      + some_dev_script_0.ipynb
      + some_dev_script_1.py
```

The pyproject.toml looks like this
```
[tool.poetry]
name = "test-module"
version = "0.1.0"

[tool.poetry.dependencies]
python = "^3.8"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

**Comment by finswimmer** [comment]
Hello @hyliu1989,

what you are describing is exactly how it should work, once you run `poetry install`.

fin swimmer

**Comment by hyliu1989** [comment]
This is the problem I found after running `poetry install`...

**Comment by hyliu1989** [comment]
I will close this issue. Thanks!
