### ISSUE TITLE
Please sync up docs along with the releases

### ISSUE THREAD

**Issue by sidbelbase** [python-poetry/poetry#3382]
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

Please sync/update the documentation with the official website https://python-poetry.org/ or just setup a wiki page here on Github. There are many updated sections that hasn't been synced yet.

I was having issues with **cli > cache** and found out that it's serving outdated content on the main site.

**Comment by Terseus** [comment]
Yes please, update the official site doc.

I was looking for the doc about the new plugin system implemented in https://github.com/python-poetry/poetry/pull/3733 and when looking the website I though it wasn't released but it is, it's very confusing.

Maybe it can be updated automatically with Github actions or something?

**Comment by finswimmer** [comment]
The documentation should now be in sync with the 1.1 branch and master branch automatically.
