### ISSUE TITLE
Can't close sidebar menu on small screens

### ISSUE THREAD

**Issue by sburris0** [python-poetry/poetry#3393]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

When the browser window is small enough for the sidebar navigation to be open, the X button to close it cannot be clicked because it is beneath the "Documentation" menu item and I can't read much because the menu is in the way.

Screenshot: https://u.teknik.io/Eayja.png

**Comment by tomzx** [comment]
Screenshot is down. Can you please upload by drag and dropping the screenshot into the GitHub text editor so that it is available. Thanks!

**Comment by sburris0** [comment]
![poetry_sidebar](https://user-images.githubusercontent.com/58098832/100556230-cb2bdf80-3298-11eb-9f29-81b534ff89b9.png)

**Comment by tomzx** [comment]
Thanks!

I can confirm there's an issue between 980px (included) and 992px (excluded) of viewport width.

**Comment by finswimmer** [comment]
Seems to be no problem anymore.
