### ISSUE TITLE
zsh poetry not found (issue was resolved manually but I'm proposing automatic solution)

### ISSUE THREAD

**Issue by codeman101** [python-poetry/poetry#3394]
- [x ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- Mac Caltina/Big Sur
- Version 1.1.4

## Issue
I was helping a friend who recently installed poetry and discovered that fo them even though they had poetry install zsh didn't see it when they typed "poetry" I found a similar issue on here where someone had the same problem because the .zprofile file was never created on their machine. This was also the case with my friend. I tried manually creating the .zprofile file on their machine and adding the line `export PATH="$HOME/.poetry/bin:$PATH"` to it but that didn't help so I instead added to their .zshrc file which did the trick. I want to propose that the curl install script be augmented to automatically add that line to the .zshrc file.

**Comment by finswimmer** [comment]
Hello @codeman101,

there is a PR for this (https://github.com/python-poetry/poetry/pull/3067). Also notice that there are other voices, that poetry should not modify any dot file (https://github.com/python-poetry/poetry/issues/898).

fin swimmer

**Comment by codeman101** [comment]
@finswimmer I don't see any comments on the PR against it. I hope it gets approved and merged. To the people against it I'm curious to know what their alternative solution is because having to do it manually isn't ideal.

**Comment by codeman101** [comment]
@finswimmer 

Thanks I replied to that thread. I hope something is done to solve this issue soon because it's a shame IMO.

**Comment by davidfstr** [comment]
Also see #507, which is the same issue but strangely marked as closed.

**Comment by jleclanche** [comment]
Can be closed per #898 @finswimmer

**Comment by finswimmer** [comment]
The new installer doesn't modify any dot file anymore. Instead it prints some hints what have to be done. Also the location where the Poetry binary is located has changed.
