### ISSUE TITLE
Poetry cannot match version in install stage, however the version is added by poetry itself

### ISSUE THREAD

**Issue by zillionare** [python-poetry/poetry#3402]
- [ X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [X ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu18.04.4
- **Poetry version**: 1.1.4
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://github.com/zillionare/omicron/blob/master/pyproject.toml

## Issue
1. it resolve dependency too slow. it last more than 900 seconds until I cancel it.
2. Then I tried to remove all deps in toml, and try to add them one by one by `poetry add xxx`. the first one is cfg4py, I let poetry decide its latest version, and the version is 0.7.1
3. step 2 still takes too long. So I cancel it again, and find the cfg4py is already added into [tool.poetry.dependency] section, with version = 0.7.1
4. run `poetry install -vvv`
it reports  `Because omega depends on cfg4py (^0.7.1) which doesn't match any versions, version solving failed. `
without any delay.

Why poetry can determine it's version but still failed in `install` stage?

**Comment by n8sty** [comment]
The link to you pyproject.toml throws a 404 not found error

**Comment by zillionare** [comment]
> 
> 
> The link to you pyproject.toml throws a 404 not found error

sorry, I have decide to rollback

**Comment by finswimmer** [comment]
No problem here. `cfg4py` is installed immediately.

fin swimmer

**Comment by zillionare** [comment]
close this issue, I'm managing project by setup tools now, will try poetry again maybe several months later.

Possibly the issue caused by my location.
