### ISSUE TITLE
Official instructions for installing poetry

### ISSUE THREAD

**Issue by adder46** [python-poetry/poetry#3407]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

I'm trying to install poetry using the official installation instructions, however, the installation is taking more than 10 minutes already and it still hasn't finished yet - it says it's still downloading the tarball. It would be nice if there was some progress indicator or something like that. Also, I know it's 57MB, but it shouldn't take this long, IMO. I'm on 300 Mbps cable internet. I'm watching the download speed and it's measured in KBps. I'm not sure if the problem is on my side, but I'm doing this for the second time since I made a mistake the first time by piping it to `python` (not `python3`) - which is another opportunity to enhance the instructions to be more explicit.

And it finally finished:
```

$ curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3 
Retrieving Poetry metadata

# Welcome to Poetry!

This will download and install the latest version of Poetry,
a dependency and package manager for Python.

It will add the `poetry` command to Poetry's bin directory, located at:

$HOME/.poetry/bin

This path will then be added to your `PATH` environment variable by
modifying the profile files located at:

$HOME/.profile
$HOME/.bash_profile

You can uninstall at any time by executing this script with the --uninstall option,
and these changes will be reverted.

Installing version: 1.1.4
  - Downloading poetry-1.1.4-linux.tar.gz (57.03MB)
Traceback (most recent call last):
  File "<stdin>", line 1086, in <module>
  File "<stdin>", line 1082, in main
  File "<stdin>", line 362, in run
  File "<stdin>", line 528, in install
  File "<stdin>", line 548, in make_lib
  File "<stdin>", line 613, in _make_lib
  File "/usr/lib/python3.8/http/client.py", line 458, in read
    n = self.readinto(b)
  File "/usr/lib/python3.8/http/client.py", line 502, in readinto
    n = self.fp.readinto(b)
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer
```
So I decided to try the offline installer, and I'm currently downloading the latest release, and I think it's Github that's causing the slowness. And this download timed out and cannot be continued.

Conclusion: I was able to use a VPN service to circumvent Github's location-based download speed discrimination policy. You should keep this in mind when choosing a distribution path for your software if you're targetting a worldwide audience.

**Comment by finswimmer** [comment]
> Conclusion: I was able to use a VPN service to circumvent Github's location-based download speed discrimination policy. You should keep this in mind when choosing a distribution path for your software if you're targetting a worldwide audience.

Thanks for reporting, that you've solved this on your site. I will close this issue. Leave a comment if you disagree.

fin swimmer

**Comment by dimitar-petrov** [comment]
Same issue here. 
Since `curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python` is the recommended installation procedure it woud be better for the package to be hosted on location that is accessible fast enough world wide.

**Comment by lophy95** [comment]
Hi! I was tying to install poetry with `"curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3 "`. But ended up with this error:
`curl: error while loading shared libraries: libmetalink.so.3: cannot open shared object file: No such file or directory
`
How to fix this issue?
