### ISSUE TITLE
Adding password-protected git repository via ssh is not working

### ISSUE THREAD

**Issue by hakanyi** [python-poetry/poetry#3409]
- **OS version and name**: Manjaro Linux 20.2
- **Poetry version**: 1.1.4

## Issue
I'm trying to add a git repository via `poetry add git+ssh://myrepo.git`. After invoking that command, I'm asked to provide the password for my ssh key. Then, the poetry output "Resolving dependencies..." appears which takes forever and a second password prompt flashes for a few milliseconds.

However, when invoking the same command with `-vvv`, the second prompt actually allows me to enter the password, poetry proceeds as expected and installs the remote package successfully in a few seconds.

**Comment by naterichman** [comment]
I am also having this issue on my Mac machine.

However on my Linux machine (Arch Linux 5.9.10-arch1-1) I **don't** have this issue.

Wondering if it might have to do with the terminal emulator?

**Comment by pietermarsman** [comment]
Possible duplicate of https://github.com/python-poetry/poetry/issues/2825

**Comment by dimbleby** [comment]
fixed at #5880, can be closed
