### ISSUE TITLE
Install fails with another poetry editable package in project file

### ISSUE THREAD

**Issue by michalszelagsonos** [python-poetry/poetry#3410]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 18.04
- **Poetry version**: 1.1.4
- **Python version**: 2.7

## Issue
This issue is a regression from `1.0.10` where this use case behaves as expected.  Note, the workflow in `1.0.10` did not require manual edit of `pyproject.toml` so it isn't an apples to apples comparison but the intent is the same.  I have a poetry project where I want to add an editable version of another package for development purposes and during testing create new virtualenv with the editable package for testing.  

Project structure that reproduces the issue:

```
test
|--pyproject.toml
|--poetry.lock

pkg
|--pyproject.toml
|--poetry.lock
    pkg
    |--__init__.py
    |--foo.py
```

The workflow is as follows assuming `POETRY_VIRTUALENVS_CREATE=false`:

- create virtualenv and activate it in `test`: `virtualenv -p python2.7 venv` and `source venv/bin/activate`
- install dependencies: `poetry install --no-root`
- add an editable dependency: `poetry add ../pkg`.  Note, `pkg` is another poetry project
- update `pyproject.toml` with `develop = true` to make `pkg` editable
- sync the lock file with `poetry update --lock pkg`
- now create a new venv in `test` and run `poetry install --no-root`.  The install fails with error below.

Why would I want to recreate the venv?  I test using docker so when I rebuild the image, it will build the env from scratch using the project file that includes editable package.  This is a common dev workflow.

The error:
```
Using virtualenv: /home/mszelag/workspace/test/venv
Installing dependencies from lock file

Finding the necessary packages for the current system

Package operations: 1 install, 0 updates, 0 removals

  - Installing pkg (0.1.0 /home/mszelag/workspace/pkg)

OSError

Unable to access any of "/home/mszelag/workspace/test/venv/local/lib/python2.7/dist-packages/pkg-0.1.0.dist-info"

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/clikit/console_application.py", line 131, in run
    status_code = command.handle(parsed_args, io)
  File "/usr/local/lib/python2.7/dist-packages/clikit/api/command/command.py", line 120, in handle
    status_code = self._do_handle(args, io)
  File "/usr/local/lib/python2.7/dist-packages/clikit/api/command/command.py", line 171, in _do_handle
    return getattr(handler, handler_method)(args, io, self)
  File "/usr/local/lib/python2.7/dist-packages/cleo/commands/command.py", line 92, in wrap_handle
    return self.handle()
  File "/usr/local/lib/python2.7/dist-packages/poetry/console/commands/install.py", line 71, in handle
    return_code = self._installer.run()
  File "/usr/local/lib/python2.7/dist-packages/poetry/installation/installer.py", line 103, in run
    return self._do_install(local_repo)
  File "/usr/local/lib/python2.7/dist-packages/poetry/installation/installer.py", line 316, in _do_install
    return self._execute(ops)
  File "/usr/local/lib/python2.7/dist-packages/poetry/installation/installer.py", line 370, in _execute
    self._execute_operation(op)
  File "/usr/local/lib/python2.7/dist-packages/poetry/installation/installer.py", line 380, in _execute_operation
    getattr(self, '_execute_{}'.format(method))(operation)
  File "/usr/local/lib/python2.7/dist-packages/poetry/installation/installer.py", line 405, in _execute_install
    self._installer.install(operation.package)
  File "/usr/local/lib/python2.7/dist-packages/poetry/installation/pip_installer.py", line 31, in install
    self.install_directory(package)
  File "/usr/local/lib/python2.7/dist-packages/poetry/installation/pip_installer.py", line 214, in install_directory
    builder.build()
  File "/usr/local/lib/python2.7/dist-packages/poetry/masonry/builders/editable.py", line 59, in build
    self._add_dist_info(added_files)
  File "/usr/local/lib/python2.7/dist-packages/poetry/masonry/builders/editable.py", line 207, in _add_dist_info
    dist_info = self._env.site_packages.mkdir(dist_info_path)
  File "/usr/local/lib/python2.7/dist-packages/poetry/utils/env.py", line 238, in mkdir
    return self._path_method_wrapper(path, 'mkdir', *args, **kwargs)[0]
  File "/usr/local/lib/python2.7/dist-packages/poetry/utils/env.py", line 232, in _path_method_wrapper
    raise OSError('Unable to access any of {}'.format(paths_csv(candidates)))
```

`pyproject.toml` in `test` project:
```
[tool.poetry]
name = "foo"
version = "0.1.0"
description = "bla"
authors = ["Andy James <aj@foo.com>"]

[tool.poetry.dependencies]
python = "^2.7"
pkg = {path = "../pkg", develop = true}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

`pyproject.toml` in `pkg` project:
```
[tool.poetry]
name = "pkg"
version = "0.1.0"
description = "foo"
authors = ["John Smith <a@b.com>"]

packages = [
    { include = "pkg" }
]

[tool.poetry.dependencies]
python = "^2.7"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

**Comment by EvanShenkman-Sonos** [comment]
I was able to repro this issue inside of an ubuntu 18.04 Docker container.

A couple things to note:
1. I was **only** able to repro the issue when using the system python, `/usr/bin/python`. I could not repro this issue if I installed python to the user-space, `$HOME/.pyenv/versions/2.7.17/bin/python`, using _pyenv_.
1. I was able to repro the issue no matter how I installed poetry...
   1. via pip
   1. via `get-poetry.py`
1. I was able to repro the issue no matter how the virtualenvs were created...
   1. via poetry
   1. via virtualenv and setting `POETRY_VIRTUALENVS_CREATE=false`

## Using system python

#### Repro steps

These steps are run in an `ubuntu:18.04` container and assume the same directory structure @Michal-Szelag-Sonos laid out above...

```bash
$ apt-get update && apt-get install python python-pip python-virtualenv tree && pip install poetry
$ tree .
|-- pkg
|   |-- pkg
|   |   |-- __init__.py
|   |   `-- foo.py
|   `-- pyproject.toml
`-- test
    `-- pyproject.toml
$ cd ./test
$ virtualenv -p python2.7 venv
$ source venv/bin/activate
$ poetry add ../pkg
// edit ./test/pyproject.toml to make pkg an editable dependency by setting develop = true
$ rm -rf venv && virtualenv -p python2.7 venv
$ source venv/bin/activate
$ poetry install --no-root

Package operations: 1 install, 0 updates, 0 removals

  • Installing pkg (0.1.0 /poetry-test/pkg): Failed

OSError

Unable to access any of "/poetry-test/test/venv/local/lib/python2.7/dist-packages/pkg-0.1.0.dist-info"

$ poetry env info
Virtualenv
Python:         2.7.17
Implementation: CPython
Path:           /poetry-test/test/venv
Valid:          True

System
Platform: linux2
OS:       posix
Python:   /usr
```

## Using user python

#### Repro steps

These steps are run in an `ubuntu:18.04` container and assume the same directory structure... these steps also assume that pyenv has been installed using the [pyenv-installer](https://github.com/pyenv/pyenv-installer).

```bash
$ pyenv install 2.7.17
$ pyenv shell 2.7.17
$ tree .
|-- pkg
|   |-- pkg
|   |   |-- __init__.py
|   |   `-- foo.py
|   `-- pyproject.toml
`-- test
    `-- pyproject.toml
$ cd ./test
$ virtualenv -p python2.7 venv
$ source venv/bin/activate
$ poetry add ../pkg
// edit ./test/pyproject.toml to make pkg an editable dependency by setting develop = true
$ rm -rf venv && virtualenv -p python2.7 venv
$ source venv/bin/activate
$ poetry install --no-root

Package operations: 1 install, 0 updates, 0 removals

  • Installing pkg (0.1.0 /poetry-test/pkg)

$ poetry env info
Virtualenv
Python:         2.7.17
Implementation: CPython
Path:           /poetry-test/test/venv
Valid:          True

System
Platform: linux2
OS:       posix
Python:   /root/.pyenv/versions/2.7.17
```

**Comment by EvanShenkman-Sonos** [comment]
Also, for what it's worth, I am **not** able to repro this issue when following similar steps using the `python:2.7` Docker image.

**Comment by Michal-Szelag-Sonos** [comment]
Any traction on this?

**Comment by finswimmer** [comment]
Hello @michalszelagsonos,

you haven't come back to this issue for a long while. So I assume this is solved in the meantime and I can close this ticket.

Feel free to leave a comment if you disagree.

fin swimmer
