### ISSUE TITLE
poetry install exits with exit code 1 when run in a docker container

### ISSUE THREAD

**Issue by achow101** [python-poetry/poetry#3412]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Debian stretch docker container, Arch host
- **Poetry version**: 1.1.4
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://github.com/bitcoin-core/HWI/blob/def565b5ac5d98b5fcc453328fc9a20207c6e00a/pyproject.toml

## Issue

When trying to install the dependencies with poetry for my project in a docker container, poetry just exits with no errors or warning, just an exit code of 1.

The Dockerfile is https://github.com/bitcoin-core/HWI/blob/def565b5ac5d98b5fcc453328fc9a20207c6e00a/contrib/build.Dockerfile and the script being run is https://github.com/bitcoin-core/HWI/blob/def565b5ac5d98b5fcc453328fc9a20207c6e00a/contrib/build_bin.sh. It specifically errors on the line `poetry install -E qt`. Changing this command to include `-vvv` does not effect the output.

The output is
```
+ poetry install -E qt
Creating virtualenv hwi-G-6EQZNy-py3.6 in /root/.cache/pypoetry/virtualenvs
Installing dependencies from lock file

Package operations: 28 installs, 0 updates, 0 removals
```

This previously worked when poetry 1.0.10 was used and it seems like 1.1.0 is the version where this stopped working.

If I run this on my host, also with 1.1.4, there are no issues. It seems to only be in this container. The script doesn't seem to make a difference; I can have a shell in the container, do `poetry install` manually, and it still fails in the same way.

**Comment by brandon-leapyear** [comment]
I got the same thing, and bisecting my changes, I noticed that it happens when `LANG=en_US.UTF-8` is set, but the Docker image I'm using doesn't have that locale configured. I think this is a bug, `poetry` should either be independent of a misconfigured `LANG` setting, or show better logs

**Comment by achow101** [comment]
I was able to work around this by adding

```
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8
ENV LANGUAGE=C.UTF-8
``` 

to my Dockerfile.

But I'm going to leave this issue open because I think it's a bug that poetry is existing like this when no locale is set.

***

A way to replicate this outside of docker is to temporarily unset the locale, e.g.:

```
env LC_ALL= LANG= LANGUAGE= poetry install
```

**Comment by jtmoon79** [comment]
If poetry must have LOCALE, then it must inform the user why it is failing, i.e. it should `raise` some useful error.

**Comment by brandon-leapyear** [comment]
Found the issue:
https://github.com/python-poetry/poetry/blob/a12d14285456d4fe57eac406e61444ff955c53e2/poetry/installation/executor.py#L199

```bash
LANG= python3.6 -c 'print("•")'
```
fails on python 3.6 (not on 3.9, can't speak for anything in between)
