### ISSUE TITLE
Flag to install all extras

### ISSUE THREAD

**Issue by l0b0** [python-poetry/poetry#3413]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

It would be handy to have a flag like `--all-extras` to install every package listed in any of the extras.

The specific use case is that I want the IDE to index the packages for every subsystem (AWS Lambda jobs in this case) for easier development.

Workarounds:

1. Creating a separate "extra" section with all the packages from all the other extras ([example](https://github.com/biocatchltd/yellowbox/pull/38)). This means duplication, which means it would be really easy for the sections to get out of sync.
2. Listing each extra specifically in the developer instructions.
3. [This ugly code](https://stackoverflow.com/a/68216833/96588), used in anger [here](https://github.com/linz/geostore/blob/67ac5a6f248aedb5da11f7e37d11b04a28292e8a/.github/workflows/test.yml#L39-L40): `poetry install --extras="$(sed --quiet '/\[tool\.poetry\.extras\]/,/^\[/{s/^\(.*\) = \[/\1/p}' pyproject.toml | sed --null-data 's/\n/ /g;s/ $//')" --remove-untracked`

**Comment by sinoroc** [comment]
Related: https://github.com/python-poetry/poetry/issues/3369

**Comment by thclark** [comment]
Seconded for this one - I want to provide my team a vscode devcontainer that installs everything out of the box, and don't want to have to remember to update the `.devcontainer` file if we add extras to the library we're developing... so sounds like the same use case as the OP.

**Comment by abn** [comment]
Would supporting `--extras .` or `--extras "*" ` as an alias for enabling all extras work here?

**Comment by l0b0** [comment]
`--all-extras` would be more explicit, and would avoid a) a special value and b) supporting any kind of regex, which would be another can of worms.

**Comment by kroeschl** [comment]
I don't have an opinion either way, but I'd like to use this feature to make dev testing somewhat easier. I posted a PR for `--all-extras`: #5452

**Comment by rjurney** [comment]
Any idea when this will be released?

**Comment by ecs-jnguyen** [comment]
It looks like the PR only got merged to master which is on version 1.2.0 beta. Could we get the `--all-extras` flag merged into 1.1 which is installed by default?

**Comment by rjurney** [comment]
@ecs-jnguyen @kroeschl @neersighted that would be awesome!

**Comment by Secrus** [comment]
> It looks like the PR only got merged to master which is on version 1.2.0 beta. Could we get the `--all-extras` flag merged into 1.1 which is installed by default?

There won't be any backports to 1.1 at this point. Unless anything breaks upstream (like it was for 1.1.14), there won't be another 1.1 release.

**Comment by ecs-jnguyen** [comment]
Do we have an estimate on when 1.2 stable will be released?

**Comment by neersighted** [comment]
> Do we have an estimate on when 1.2 stable will be released?

#5586
