### ISSUE TITLE
Can'add pybluez to any project: "PyObjC requires macOS to build"

### ISSUE THREAD

**Issue by sisco70** [python-poetry/poetry#3415]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- Ubuntu 20.04LTS: 
- Poetry version 1.1.4: 
- https://gist.github.com/sisco70/1bcccd9e08d2ff1d106b787112a3c40b: 

The problem is dead simple:

I can't add pybluez to any project, even an empty project:

- poetry init
- poetry shell
- poetry add pybluez -vvv

PyPI: 4 packages found for pybluez *
Using version ^0.23 for PyBluez

Updating dependencies
Resolving dependencies...
   1: fact: test is 0.1.0
   1: derived: test
   1: fact: test depends on PyBluez (^0.23)
   1: selecting test (0.1.0)
   1: derived: PyBluez (^0.23)
PyPI: 1 packages found for pybluez >=0.23,<0.24
   1: fact: pybluez (0.23) depends on pyobjc-core (>=3.1,<6)
   1: fact: pybluez (0.23) depends on pyobjc-framework-Cocoa (>=3.1,<6)
   1: selecting pybluez (0.23)
   1: derived: pyobjc-framework-Cocoa (>=3.1,<6)
   1: derived: pyobjc-core (>=3.1,<6)
   1: fact: pyobjc-framework-cocoa (5.3) depends on pyobjc-core (>=5.3)
   1: selecting pyobjc-framework-cocoa (5.3)
   1: derived: pyobjc-core (>=5.3)
   1: selecting pyobjc-core (5.3)
   1: Version solving took 0.005 seconds.
   1: Tried 1 solutions.

Finding the necessary packages for the current system

Package operations: 3 installs, 0 updates, 0 removals

  • Installing pyobjc-core (5.3): Pending...
  • Installing pyobjc-core (5.3): Installing...
  • Installing pyobjc-core (5.3): Failed

  EnvCommandError

...........

error: PyObjC requires macOS to build

**Comment by sinoroc** [comment]
I can recreate the failure. Not sure what is happening here...

**Comment by sisco70** [comment]
I'm using Ubuntu 20.04LTS, Python 3.8, Poetry version 1.1.4.

To test use a simple empty project and try to add the package pybluez.

**Comment by sisco70** [comment]
I'not sure if needs, but:

pip --version
pip 20.2.4 from /usr/local/lib/python3.8/dist-packages/pip (python 3.8)

**Comment by sinoroc** [comment]
Somehow _poetry_ thinks that _pybluez_ requires _pyobjc_, which is true only on _macos_. I do not know what is going wrong here. _pybluez_'s `setup.py` in the _sdist_ seems correct to me. But to be honest I am not sure if _poetry_ fetched the _sdist_ or some (incompatible) _wheel_, the verbose output does not say.

**Comment by sisco70** [comment]
Maybe wrong in recognizing the platform somewhere?

poetry debug
-----------------------------
Poetry
Version: 1.1.4
Python:  3.8.5

Virtualenv
Python:         3.8.5
Implementation: CPython
Path:           /home/francesco/.cache/pypoetry/virtualenvs/test-_1ZzTJc4-py3.8
Valid:          True

System
Platform: linux
OS:       posix
Python:   /usr

**Comment by michaelmior** [comment]
I'll note that I get the same issue on my Raspberry Pi but manually installing pybluez using pip from Poetry's virtualenv works fine.

**Comment by sisco70** [comment]
Yes. Same issue. The problem lies in Poetry..

**Comment by FraBle** [comment]
> I'll note that I get the same issue on my Raspberry Pi but manually installing pybluez using pip from Poetry's virtualenv works fine.

Same issue and same workaround for Debian 10 in VMWare Fusion.

**Comment by raxod502** [comment]
Confirmed this is still an issue with Poetry 1.1.5.

**Comment by raxod502** [comment]
Workaround:

```
% poetry add git+https://github.com/pybluez/pybluez#0.23
```

This generates the following statement in `pyproject.toml`:

```toml
pybluez = {git = "https://github.com/pybluez/pybluez", rev = "0.23"}
```

**Comment by finswimmer** [comment]
Hello,

poetry is reading the dependencies for a current version of a package from PyPi's API. In case of pybluez this is here: https://pypi.org/pypi/PyBluez/json

As you can see `pyobjc-core` is listed under `requires_dist` without any platform marker. Which is obviously wrong.

I have no idea how and when these information are generated for PyPi, but it might be that it ist connected to the `sdist`. Here, in the `setup.py`, the list of dependencies is generated by a python logic and doesn't add any platform markers as well.

Please be so kind and report it to the maintainers of pybluez, so they can fix it.

fin swimmer

**Comment by mrkeuz** [comment]
@raxod502, thanks!
