### ISSUE TITLE
Poetry virtual environment created with system's Python 3.x.x, now system's Python is updated to Python 3.x.y

### ISSUE THREAD

**Issue by gorjanradevski** [python-poetry/poetry#3417]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

I want to start by saying that I've been using Poetry for more than two years now and it's been an absolute pleasure. Thanks for creating such a wonderful tool. The issue I'm experiencing isn't a problem with Poetry by any means, and I'm just wondering whether there is a workaround that someone can suggest. With that said, bellow is my problem.

I have Poetry installed on a remote Linux machine that's running Python 3.x.x, and I've created a virtual environment there. Everything works nice as it should, and the output of `poetry env info` is:

```shell
Virtualenv
Python:         3.8.6
Implementation: CPython
Path:           /esat/goryu/gradevsk/Projects/something-something/.venv
Valid:          True

System
Platform: linux
OS:       posix
Python:   /usr
```
When I submit a job with the scheduling system my faculty is using, the job lands on a different machine than mine, that's running a different system Python 3.x.y. Every machine has access to the other machine's hard disks, so the job has access to the directory where the virtual environment is created. However, since the system's Python is now different, when I run the Python from the virtual environment `project_root/.venv/bin/python`, it can't access the packages installed within. Additionally, when I `ssh` to the machine where the job lands, and when I go in the project root, and do `poetry env info`, the output is:

```shell
Virtualenv
Python:         3.9.0
Implementation: CPython
Path:           /esat/goryu/gradevsk/Projects/something-something/.venv
Valid:          True

System
Platform: linux
OS:       posix
Python:   /usr
```
Therefore, unless the job lands on a machine that is running the same system Python as mine, it can't find the packages installed within the virtual environment. I want to also stress that using `pyenv` is not an option for me to install a different Python, because I don't have `sudo` permissions, i.e., `pyenv install x.y.z` fails because there are missing dependencies which I can't install due to the lack of permissions.

Does anyone know a workaround for such issue?

**Comment by sinoroc** [comment]
Am I understanding it right, that different machines have different versions of the Python interpreter, and yourself can not install any other Python interpreter on those machines? Do you by chance have access to _Docker_ (or something similar) on those machines?

---

***Aside***:

It is not recommended to share virtual environments.

> Every machine has access to the other machine's hard disks, so the job has access to the directory where the virtual environment is created.

I definitely would not recommend taking advantage of this, even if the Python interpreter versions matched perfectly. Virtual environment should be unique to a machine.

**Comment by gorjanradevski** [comment]
Hey @sinoroc, you understood everything perfectly and no, I don't have access to Docker on those machines 😞 W.r.t. your **Aside note**, the current pipeline is.

1. I submit the job from my machine.
2. The scheduler assigns the first available machine that meets my job requirements.
3. The job starts executing on the assigned machine &#8594; literally a `.sh` file that `cd`s into the project directory and does `.venv/bin/python my_python_file.py`.

Do you have a suggestion for a better alternative to do the above mentioned? If there is a better option, it can maybe solve my issue as well.

**Comment by sinoroc** [comment]
I think in a first step I would make it so that the virtual environment is created from scratch on each remote job run. Once it runs reliably, I would see which aspects of this I can optimize to spare resources (disk space, CPU time, network traffic, etc.). 

But if already you have no control over the exact version of Python interpreter those are not good conditions.

> first available machine that meets my job requirements

Could one of those requirements be set to the version of the Python interpreter?

>  a `.sh` file that `cd`s into the project directory and does `.venv/bin/python my_python_file.py`

As I said, I would not do that. Do not reuse virtual environments on different machines. Maybe it is better to change this to simply `python3 my_python_file.py`.

---

Honestly something does not seem right in your first message. It looks like poetry reuses the `.venv` environment with a different python interpreter. That seems unexpected to me.

**Comment by gorjanradevski** [comment]
Thanks for the suggestions @sinoroc.

>Could one of those requirements be set to the version of the Python interpreter?

I don't think so, the scheduler ([Condor](https://htcondor.readthedocs.io/en/v8_8/)), assigns a machine based on the hardware requirements.

> As I said, I would not do that. Do not reuse virtual environments on different machines. Maybe it is better to change this to simply `python3 my_python_file.py`.

The virtual environment is created on my machine, on my hard disk. The machine that is assigned to me has access to the hard disk of my machine, hence I am doing `.venv/bin/python my_pythonfile.py`. If I do `python3 my_python_file.py`, by default I don't have access to any of the dependencies I assume?

> Honestly something does not seem right in your first message. It looks like poetry reuses the `.venv` environment with a different python interpreter. That seems unexpected to me.

That's exactly what happens, I also find it weird unless there is another cause that I can't figure out yet. Here is the `.venv/pyvenv.cfg` content.

```shell
home = /usr
implementation = CPython
version_info = 3.8.6.final.0
virtualenv = 20.0.31
include-system-site-packages = false
base-prefix = /usr
base-exec-prefix = /usr
base-executable = /usr/bin/python
```

The `base-executable` is `/usr/bin/python`, which changes from one machine to another, i.e., `/usr/bin/python --version` outputs `Python 3.8.6` on my machine, and `Python 3.9.0` on some of the other machines. Simply put, my machine still runs on Fedora 32, and some of the other machine run on Fedora 33 (which comes with Python 3.9.0).

**Comment by sinoroc** [comment]
I do not know what the restrictions on those machines are. But I think I would try to start with a job that looks like this:

```bash
#!/usr/bin/env bash
PROJECT_DIR="path/to/project"
VENV_DIR="$(mktemp -d)"
python3 -m venv "${VENV_DIR}"
"${VENV_DIR}/bin/python" -m pip install poetry
POETRY_BIN="${VENV_DIR}/bin/poetry"
pushd "${PROJECT_DIR}"
export POETRY_VIRTUALENVS_IN_PROJECT=false
"${POETRY_BIN}" install
"${POETRY_BIN}" run python my_python_file.py
```

Note the usage of [`virtualenvs.in-project`](https://python-poetry.org/docs/configuration/#virtualenvsin-project-boolean), since you seem to have a `.venv` directory in your project directory.

Then I do not know if the cache has to be considered or not. There are many things that could have an influence on this, but without knowing more details it is difficult.

**Comment by gorjanradevski** [comment]
Thanks a lot for looking into this and the help @sinoroc. In the end, I found a workaround. I managed to install a different Python with `miniconda`. Once I had a Python installation different than the system one, I do the following:

```shell
cd project_root
poetry config virtualenvs.in-project true # Once for all projects
poetry init
poetry env use /path_to_miniconda/miniconda3/bin/python
poetry add whatever_I_need
``` 

Then, in the `.sh` script that is executed by the assigned machine I have the essentially the same thing as before`./venv/bin/python my_python_file.py` and it works as it should. Also, now, the content of the `pyvenv.cfg` file is:

```shell

home = /path_to_miniconda/miniconda3
implementation = CPython
version_info = 3.8.5.final.0
virtualenv = 20.0.31
include-system-site-packages = false
base-prefix = /path_to_miniconda/miniconda3
base-exec-prefix = /path_to_miniconda/miniconda3
base-executable = /path_to_miniconda/miniconda3/bin/python

```

Which is what I need. Thanks again for your help! Since my issue is resolved, I will close it.
