### ISSUE TITLE
Allow using cloned VCS (git) repositories for `update` and `lock` instead of cloning it to `/tmp` all the time to save on data traffic

### ISSUE THREAD

**Issue by dolfandringa** [python-poetry/poetry#3420]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request
For large git repositories, cloning them all the time takes a considerable amount of time. I have a dependency in git that is 1.8Gb in size. Every `poetry update` and similar calls results in a full clone of that repository to /tmp, even with `develop=True` in the dependency config. Even on a decent internet connection that takes a lot of time. It would be a lot faster if there was an option that would cause poetry to clone that repository to a dedicated folder and just do a git pull on it, instead of a full clone to `/tmp`.

I am thinking of 2 options: 
1. When`develop=True` make sure to just clone to `{virtualenv.path}/src` directory if the package isn't there yet, or do a `git pull` there if it does exist, and use that directory in the `update` command. 
2. Add a separate option `keep_source` to the dependency config that makes  `poetry update` use the checked out code in `{virtualenv.path}/src` for the update (or check it out if it's not there yet).

**Comment by dimbleby** [comment]
fixed, #6131 prevents unnecessary updates when nothing has changed, this can be closed
