### ISSUE TITLE
git deps don't get installed properly (`src` folder not added to path)

### ISSUE THREAD

**Issue by djrobstep** [python-poetry/poetry#3421]
- [ ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [ ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: MacOS 10.14.6
- **Poetry version**: 1.1.14
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue

I have a number of private git dependencies installed with poetry as follows:

```
mypackage = {git = "git+ssh://git@github.com/myorg/mypackage.git"}
```

On running a fresh `poetry install` (in a docker container build), these packages install, but aren't importable, because their `src` paths don't get added to the sys.path.

If I downgrade to `1.0.10`, everything works great.

Not sure if related to: https://github.com/python-poetry/poetry/issues/2657

**Comment by Semtexcz** [comment]
I have similar problem as well. I can add log from travis: https://travis-ci.com/github/Narodni-repozitar/nr-theses/builds/204647502. Solution was same as @djrobstep , downgrade to the 1.0.10 helped.

**Comment by stefan-falk** [comment]
Has his been fixed?

**Comment by arnegroskurth** [comment]
*push*

**Comment by djrobstep** [comment]
I found that this was happening if I had a missing `build-system` section in my `pyproject.toml`:

```
[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

Once that got added, git deps installed fine. Unfortunately, there is no indication that this is the problem!

**Comment by finswimmer** [comment]
Hello @djrobstep,

you haven't come back to this issue for a long while. So I assume this is solved in the meantime and I can close this ticket.

Feel free to leave a comment if you disagree.

fin swimmer
