### ISSUE TITLE
poetry add robotframework

### ISSUE THREAD

**Issue by cleversondeveloper** [python-poetry/poetry#3424]
- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **Linux Mint 20 Cinnamon**: 
- **Poetry 1.1.4**: 
- **[pyproject.toml](https://gist.github.com/cleversondeveloper/b2eee0917559385dc74c23a13b58def9)**: 

## Issue

Using ```pip install robotframework```  the installation is successful.
But, the following [error](https://gist.github.com/cleversondeveloper/1cb586ee24ad5c5a1cdcfd40605cc3a3) happens when using ```poetry add robotframework -vvv```

**Comment by tomzx** [comment]
Works fine for me with poetry `1.1.4`, Windows 7 x64 SP1, Python 3.8.5.

Can you provide the version of python you are using?

**Comment by cleversondeveloper** [comment]
> Works fine for me with poetry `1.1.4`, Windows 7 x64 SP1, Python 3.8.5.
> 
> It looks like you called your package `robotframework` when you ran `poetry init`? Is that correct? I'm basing this on the fact that your output says
> 
> ```
> Resolving dependencies...
>    1: fact: robotframework is 0.1.0
> ```
> 
> where it should be something like `your-library`. It seems to be failing because it's resolving to itself instead of finding `robotframework` on PyPI. I would suggest you rename your package to something else to avoid this conflict.

3.8.6

**Comment by sinoroc** [comment]
@cleversondeveloper As @tomzx said: you can't name your project "_robotframework_" and add a dependency of the same name. That can not possibly work. This is not allowed in Python. Not just with poetry.

**Comment by cleversondeveloper** [comment]
as @sinoroc  wrote!
