### ISSUE TITLE
Auto detect the location of pyproject.toml

### ISSUE THREAD

**Issue by qiankunxienb** [python-poetry/poetry#3430]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

When I am in the environment of poetry but in another folder beside the project, please let me execute `poetry add <package>` instead of raise Error.

Say, my project location is `~/project/xxx`, I have already executed `poetry shell` in the location so I am in the poetry shell already. 

Now, I change to another folder: `cd ~/project/yyy`。And then execute `poetry add <package>`。Poetry raises an error to say it could not find `pyproject.toml`.

However, as I am already in the poetry shell, poetry should know the location of the project's pyproject.toml. Why not just install the package in that place? 

As an example, Pipenv will do the right thing.

**Comment by neersighted** [comment]
I don't think this is helpful/useful at all -- Poetry normally reasons about projects in terms of directory layout, and the `poetry` command reaching across directories to mutate state in a totally different tree is incredibly magical and unexpected to me.

If you can find evidence that this is widely used/desired and that it's idiomatic in other tools, that might be one thing, but without evidence this is a very popular usage of other tools that Poetry uses would like to see, it seems firmly out of scope and ill-advised.
