### ISSUE TITLE
tool.poetry.source does not match configured authentication

### ISSUE THREAD

**Issue by samedii** [python-poetry/poetry#3432]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 18.04.3
- **Poetry version**: 1.1.4
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/samedii/111920400eeca3794ddf2409c9e29a22

## Issue
The souce specified below should not work if I have not configured the authentication for "should-not-work".
```
[[tool.poetry.source]]
name = "should-not-work"
url = "SOME SOURCE"
```

However, it uses the config of another source and is able to access the packages. This is a significant problem when the source has two different user authentications which yield different packages

**Comment by abn** [comment]
@samedii can you clarify the scenario here please? Can you provide a more specific example? How is this "another source" configured? Do they use the same url?

**Comment by samedii** [comment]
This was a long time ago but yes they had the same url. The other source was only configured globally and not present locally in the project. It seemed that the authentication was not matched by name of the source but by url.

**Comment by neersighted** [comment]
This doesn't reproduce for me on 1.2.x -- with the rework of the authenticator, we don't match on URLs unless falling back to PyPI-style keyring auth.
