### ISSUE TITLE
Poetry updates another package on poetry remove

### ISSUE THREAD

**Issue by mvoitko** [python-poetry/poetry#3436]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 18.04
- **Poetry version**: 1.4.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue
When I run:
`poetry remove pytest-faker`
I got:
```
$ poetry remove --dev pytest-faker
Updating dependencies
Resolving dependencies... (2.0s)
Writing lock file
Package operations: 0 installs, 1 update, 3 removals
  • Removing faker (4.14.2)
  • Removing pytest-faker (2.0.0)
  • Removing text-unidecode (1.3)
  • Updating google-cloud-bigquery (2.3.1 -> 2.4.0)
```
This behavior is not specified in the documentation and is counter-intuitive.
When one runs `rm` Unix does not run `apt-get update` additionally.

**Comment by glencairn** [comment]
Hi @mvoitko, can you provide an example `pyproject.toml` to help repro?

I suspect you're seeing this behavior because another one of your project's dependencies also depends on `google-cloud-bigquery`, however it specifies a higher version constraint. It's my understanding that _any time_ you modify your project's dependencies, poetry will resolve and re-lock them which could result in an upgrade (or downgrade) like you're seeing here.

**Comment by finswimmer** [comment]
Hello @mvoitko,

it works exactly how @glencairn described it.

fin swimmer

**Comment by mvoitko** [comment]
@finswimmer I fully understand how it works. And as I have mentioned it seems completely unlogical. Why update dependencies when removing?

**Comment by mvoitko** [comment]
pyproject.toml
```
[tool.poetry]
name = "game-semantic-statsportal-backend"
version = "0.1.0"
description = "Game semantic statistics portal back end"
authors = ["Maksym Voitko <maksym.voitko@betconstruct.com>"]

[tool.poetry.dependencies]
python = "^3.8"
fastapi = "^0.61.1"
uvicorn = "^0.11.8"
starlette-prometheus = "^0.7.0"
alembic = "^1.4.3"
async-exit-stack = "^1.0.1"
async-generator = "^1.10"
passlib = "^1.7.2"
bcrypt = "^3.2.0"
pyjwt = {extras = ["crypto"], version = "^1.7.1"}
pydantic = "^1.6.1"
python-multipart = "^0.0.5"
google-auth-oauthlib = "^0.4.1"
google-cloud-bigquery = {extras = ["pandas"], version = "^2.1.0"}
asyncpg = "^0.21.0"
databases = {extras = ["postgresql"], version = "^0.3.2"}
PyYAML = "^5.3.1"

[tool.poetry.dev-dependencies]
pytest-asyncio = "^0.14.0"
pytest-flake8 = "^1.0.6"
pytest-mypy = "^0.7.0"
requests = "^2.24.0"
httpx = "^0.14.3"
pytest-cov = "^2.10.1"
pytest-dependency = "^0.5.1"
flake8-quotes = "^3.2.0"
flake8-forbid-visual-indent = "0.0.2"
sqltap = "^0.3.11"
pytest-faker = "^2.0.0"
sqlalchemy-stubs = "^0.3"

[[tool.poetry.source]]
name = "game-semantic"
url = "http://pypi-gs.bc-stage.club"
secondary = true

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

```

**Comment by glencairn** [comment]
Why is it illogical? In your pyproject.toml file you're specifying _constraints_, not _exact versions_.

One of the key features of poetry is a deterministic dependency resolution system. When you remove a dependency, you're removing a set of constraints from the solver. If poetry doesn't resolve your project's environment after _any_ operation the determinism goes away.

You can avoid this behavior by specifying exact versions for a dependencies.

**Comment by mvoitko** [comment]
@glehmann 
1. WDYT about my example with `rm`? It's illogical because when I remove dependency I expect the removal procedure of specified dependency and only it. Instead, I get unobvious behavior with no control over it.
2. How can I update dependencies with specified exact versions?

**Comment by sinoroc** [comment]
Maybe it should be seen from this angle: you are not uninstalling a library, you are removing a dependency constraint, so the dependency resolver is triggered again to fulfil this new set of constraints and a new combination of dependency versions is generated. To remove a library one could do `poetry run pip uninstall Library`. Obviously it is more complicated than that, but maybe it helps...
