### ISSUE TITLE
[regression] Local / relative packages do not install correctly in 1.1.4

### ISSUE THREAD

**Issue by niparis** [python-poetry/poetry#3441]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Both Macos big sur /  debian slim buster (docker)
- **Poetry version**: 1.1.4
- **Link of a [GITHUB REPO](https://github.com/niparis/poetry-localpackagebug) with instructions demonstrating the error**

## Issue

On poetry 1.0.9, it was possible to install a relative package with `poetry add ../../library`

Trying this on 1.1.4, no exceptions occur, but it is not possible to import `library`

**Expected behaviour:**

```
poetry add ../../library
poetry update
poetry install
```

Then importing the library should succeed

```
poetry shell
python
>> import library 
```

** Actual behavior**

The import fails with `ModuleNotFoundError`

_The following repo [GITHUB REPO](https://github.com/niparis/poetry-localpackagebug) includes file structure and exact steps to reproduce the error_

**Comment by niparis** [comment]
Extra info (i'm still testing this):

- The regression happened between 1.0.9 and 1.10
- The issue seems to be tied to the lockfile. 

Poetry 1.1.0:
```
[package.source]
type = "directory"
url = "../../utils/library"
```

Poetry 1.0.9
```
[package.source]
reference = ""  << this was removed
type = "directory"
url = "../../utils/library"
```

**Comment by sinoroc** [comment]
This might not be the cause of the issue, but I thought I'd mention it anyway:

> Before poetry 1.1 directory path dependencies were installed in editable mode by default. You should set the `develop` attribute explicitly, to make sure the behavior is the same for all poetry versions.

-- https://python-poetry.org/docs/dependency-specification/#path-dependencies

**Comment by niparis** [comment]
> This might not be the cause of the issue, but I thought I'd mention it anyway:
> 
> > Before poetry 1.1 directory path dependencies were installed in editable mode by default. You should set the `develop` attribute explicitly, to make sure the behavior is the same for all poetry versions.
> 
> -- https://python-poetry.org/docs/dependency-specification/#path-dependencies

adding `develop = true` to library1  fixes the behavior reported.

I'm going to leave this issue open, as the default behaviour right now is very confusing, and appears as a bug from a user's perspective (there's no warning, and the environment does not work as expected)

**Comment by finswimmer** [comment]
Hello @niparis,

I could understand that a user is a bit frustrating if a behavior of  a program changes. However, this change was already introduced during beta phase of the 1.1 release and was announced in the [release notes](https://github.com/python-poetry/poetry/releases/tag/1.1.0b3). Furthermore it was mentioned in the [official blog post](https://python-poetry.org/blog/announcing-poetry-1-1-0.html) on release.

fin swimmer
