### ISSUE TITLE
Provide signature for poetry installation script

### ISSUE THREAD

**Issue by macgeneral** [python-poetry/poetry#3442]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

Related: Issue #127

I think the current preferred way of installing poetry is relative insecure. Piping a script directly from curl or wget to python or the shell is always a risk in case someone manages to modify the file on the server (even if it is a multi-factor secured Github repository). While signatures still require that you trust the key in the first place, they can help detect files that were tampered on the server.

Of course experienced users can download the file first and inspect it afterwards before running it with python (if he or she knows what to look for and if that file doesn't consist of hundreds or thousands of lines like in `get-poetry.py`'s case), but this does not work for automated installs in a headless (e.g. Docker) environment and can be very time consuming.

Therefore I suggest to sign the `get-poetry.py` file with a separate gpg key of which the public key is stored on [your website](https://python-poetry.org/). Then users can at least verify that it was a developer they (have to) trust who released this version.

```console
dev@vm:~$ gpg --full-gen-key
dev@vm:~$ gpg --list-secret-keys --keyid-format LONG
dev@vm:~$ gpg --export [KEYID] > poetry_pub.gpg
```

When committing a new version to Github developers have to (automatically) sign it first
```console
dev@vm:~$ gpg --local-user [KEYID] --detach-sign get-poetry.py
```

Users now have the possibility to verify the file integrity with
```console
user@pc:~$ curl -fsO https://python-poetry.org/poetry_pub.gpg
user@pc:~$ curl -fsO https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py
user@pc:~$ curl -fsO https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py.sig
user@pc:~$ gpg --no-default-keyring --keyring poetry_pub.gpg --verify get-poetry.py.sig
user@pc:~$ python get-poetry.py
```

and integrate it in their `Dockerfile` like this:
```shell
WORKDIR /tmp
RUN curl -fsO https://python-poetry.org/poetry_pub.gpg
# verify poetry public key's SHA256 hashsum - the pipeline will fail if the key doesn't match
RUN echo "sha256sum_of_poetry_pub.gpg  poetry_pub.gpg" > poetry_pub.sha256
RUN sha256sum -c poetry_pub.sha256
# get the install script and signature
RUN curl -fsO https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py
RUN curl -fsO https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py.sig
# verify the get-poetry.py file
RUN gpg --no-default-keyring --keyring poetry_pub.gpg --verify get-poetry.py.sig
# install poetry
RUN python get-poetry.py
```
I know this doesn't prevent all possible attacks, but especially if I can hard code the sha256sum of your key file into my Dockerfile I can be sure that the key wasn't exchanged as well. Docker runs all commands as root by default, so installing poetry right now in your suggested way requires a lot of trust / precautions if there's no distribution managed version of it.

**Note**: I'm using the binary gpg format in this case because when using the ASCII armored version (--armor/-a) you can't use it as keyring without converting it back first. This is just an example anyways - of course you could also upload the key to a keyserver and make the user install it in his/her truststore. I prefer the separate from trust store way because then I don't have to globally trust the key.

**Edit**: Of course this only makes sense if the key is password protected and the file is signed on the developers machine and not automatically in a Github pipeline (in case someone manages to obtain a repository API token etc.).

**Comment by macgeneral** [comment]
As a small follow up why I think this is important/relevant:

- [Homebrew’s Github repo got hacked in 30 mins](https://hub.packtpub.com/homebrews-github-repo-got-hacked-in-30-mins-how-can-open-source-projects-fight-supply-chain-attacks/)
- [Hacker gains access to a small number of Microsoft's private GitHub repos](https://www.zdnet.com/article/hacker-gains-access-to-a-small-number-of-microsofts-private-github-repos/)

and there are probably many more examples (those were just the ones that instantly came to my mind)

**Comment by macgeneral** [comment]
Just a small update with a recent case which uses a similar install procedure:
* [Codecov Bash Uploader Dev Tool Compromised in Supply Chain Hack (Security Week)](https://www.securityweek.com/codecov-bash-uploader-dev-tool-compromised-supply-chain-hack)

**Comment by tarkatronic** [comment]
I'd just like to add on here in the hopes that this ticket can get some attention. While the practice of `curl | bash` has never been a great one security-wise, I believe that the Codecov compromise has brought this issues far more to light. What this means for poetry is that this may soon (if it has not already) become a hard blocker for people wanting to use the tool. I fear that this may become a restriction from my employer, and from others as well, as we look to follow more secure practices in our work. And the last thing I want to have to do is go back to setuptools.

**Comment by abn** [comment]
Would be great if someone can look into getting the script signed via https://www.sigstore.dev/ in our ci and the signature uploaded somewhere. This needs to happen in https://github.com/python-poetry/install.python-poetry.org.
