### ISSUE TITLE
Installation does not work with msys with a 404 error

### ISSUE THREAD

**Issue by Cerberus1746** [python-poetry/poetry#3449]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows 10
- **Poetry version**: 1.1.4
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: Not applicable

## Issue

While trying to install Poetry with MSYS, I receive the following error:

```
Retrieving Poetry metadata

Before we start, please answer the following questions.
You may simply press the Enter key to leave unchanged.
Modify PATH variable? ([y]/n) y

# Welcome to Poetry!

This will download and install the latest version of Poetry,
a dependency and package manager for Python.

It will add the `poetry` command to Poetry's bin directory, located at:

$HOME/.poetry/bin

This path will then be added to your `PATH` environment variable by
modifying the profile files located at:

$HOME/.profile
$HOME/.bash_profile

You can uninstall at any time by executing this script with the --uninstall option,
and these changes will be reverted.

Installing version: 1.1.4
Traceback (most recent call last):
  File "get-poetry.py", line 580, in _make_lib
    r = urlopen(url + "{}".format(checksum))
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "get-poetry.py", line 1086, in <module>
    sys.exit(main())
  File "get-poetry.py", line 1082, in main
    return installer.run()
  File "get-poetry.py", line 362, in run
    self.install(
  File "get-poetry.py", line 528, in install
    self.make_lib(version)
  File "get-poetry.py", line 548, in make_lib
    self._make_lib(version)
  File "get-poetry.py", line 583, in _make_lib
    raise RuntimeError("Could not find {} file".format(checksum))
RuntimeError: Could not find poetry-1.1.4-msys.sha256sum file
```

Researching into it I realized that `platform` variable is set to `msys`. I've created a pull request to fix that issue. To be more specific #3450

**Comment by sinoroc** [comment]
Aren't we supposed to use one of the _mingw_ environments, and avoid using the _msys_ one? At least that was the conclusion I came to when I used to use _msys_. If I remember right, in the _msys_ environment I would only use what was installable with _pacman_, and avoid installing anything else (especially with Python).

**Comment by Cerberus1746** [comment]
> Aren't we supposed to use one of the _mingw_ environments, and avoid using the _msys_ one? At least that was the conclusion I came to when I used to use _msys_. If I remember right, in the _msys_ environment I would only use what was installable with _pacman_, and avoid installing anything else (especially with Python).

Ah, thanks, I forgot to specify that I've tried using `mingw` indeed, and I've tried using sh console from vscode

**Comment by mkniewallner** [comment]
Hi, is this issue still relevant, or should it be closed?

**Comment by dimbleby** [comment]
get-poetry.py is deprecated and the new installer doesn't use github releases, so this can be closed

**Comment by mkniewallner** [comment]
As mentioned, `get-poetry.py` is deprecated, so if you still encounter issues, try with https://github.com/python-poetry/poetry/blob/master/install-poetry.py or https://install.python-poetry.org/, both mentioned in https://python-poetry.org/docs/master/#installation instructions.

Closing, since we didn't get an answer and this issue is quite old, but feel free to create another one if you still have issues after trying the new scripts.
