### ISSUE TITLE
poetry add should support --develop

### ISSUE THREAD

**Issue by indigoviolet** [python-poetry/poetry#3452]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a dplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

`poetry add` does not support `--develop`, which is a problem because you can't just add `develop=true` later and `poetry update` to switch to editable mode.

**Comment by sinoroc** [comment]
Duplicate https://github.com/python-poetry/poetry/issues/3220?
