### ISSUE TITLE
Fresh installation hangs at downloading poetry-1.1.4-linux.tar.gz on WSL2 (running Ubuntu 20.10)

### ISSUE THREAD

**Issue by Toxe** [python-poetry/poetry#3462]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 20.10 running in WSL2 on Windows 10 Home 20H2
- **Poetry version**: 1.1.4
- ~**Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**:~

## Issue

get-poetry.py hangs at the "Downloading poetry-1.1.4-linux.tar.gz" message.

I am trying to install Poetry on a fresh installation of Ubuntu 20.10 on Windows WSL2 (Technically this is Ubuntu 20.04 LTS but it is upgraded to 20.10.) like this:

`$ curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3`

I get this (normal) output:

```
Retrieving Poetry metadata

# Welcome to Poetry!

This will download and install the latest version of Poetry,
a dependency and package manager for Python.

It will add the `poetry` command to Poetry's bin directory, located at:

$HOME/.poetry/bin

This path will then be added to your `PATH` environment variable by
modifying the profile files located at:

$HOME/.profile
$HOME/.zshrc

You can uninstall at any time by executing this script with the --uninstall option,
and these changes will be reverted.

Installing version: 1.1.4
  - Downloading poetry-1.1.4-linux.tar.gz (57.03MB)
```

And then the installation just hangs and nothing happens anymore.

After CTRL-C I get:

```
^CTraceback (most recent call last):
  File "<stdin>", line 1086, in <module>
  File "<stdin>", line 1082, in main
  File "<stdin>", line 362, in run
  File "<stdin>", line 528, in install
  File "<stdin>", line 548, in make_lib
  File "<stdin>", line 613, in _make_lib
  File "/usr/lib/python3.8/http/client.py", line 458, in read
    n = self.readinto(b)
  File "/usr/lib/python3.8/http/client.py", line 502, in readinto
    n = self.fp.readinto(b)
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
KeyboardInterrupt
```

Let me know if there is any way to help resolving this issue.

**Comment by klnrdknt** [comment]
I have the same issue at the moment. poetry also freezes indefinetely under normal Windows 10 when trying to install or update an environment.

**Comment by sinoroc** [comment]
In case you do not absolutely depend on the `get-poetry.py` installation method, note that there are alternative installation methods available...

You could install _poetry_ itself in a virtual environment and somehow list its `path/to/venv/bin/poetry` binary on your `PATH` environment variable (maybe with a _symlink_). Or maybe use one of those tools:
* https://pypi.org/project/pipx/
* https://pypi.org/project/dephell/ and [its _jail_ feature](https://dephell.readthedocs.io/index-jail.html)
* https://pypi.org/project/pickley/
* and others

**Comment by klnrdknt** [comment]
It is not something that was a problem previously.

**Comment by Toxe** [comment]
I had some more time to look at this further today and I noticed while looking at the `get-poetry.py` script that it *seems* like I can pass it the `poetry-1.1.4-linux.tar.gz` download file directly on the command line so I wanted to try that and download the file on my own.

While doing that I noticed that the download is *awfully slow*. Like, the ETA at the moment for this 57 MB file is 1:21 hour!

So, it might be possible that it was slow like this the other day. Obviously I waited 15 minutes or something like that but I did not expect something like this to be the case.

I'll wait for the download to finish and then try installing it by hand.

I would suggest to add a progress bar or ETA to `get-poetry.py`, just in case someone else has a slow download like this.

**Comment by Toxe** [comment]
Update: The ETA went up to 3 hours so I tried downloading the file from another computer in the same LAN (which was slow as well with 10 KB/s) and then on another server and that worked as it should.

I was able to install Poetry from this download file now. Basically:

```
$ curl -OL https://github.com/python-poetry/poetry/releases/download/1.1.4/poetry-1.1.4-linux.tar.gz
$ python3 get-poetry.py --file poetry-1.1.4-linux.tar.gz
```

**Comment by sinoroc** [comment]
@Toxe Should we close the issue, if the root cause is the download speed from some 3rd party server and thus out of _poetry_'s control?

@klnrdknt I am not sure how your issue relates to this ticket... Do yo have issues when installing with `get-poetry.py`?

**Comment by klnrdknt** [comment]
> @Toxe Should we close the issue, if the root cause is the download speed from some 3rd party server and thus out of _poetry_'s control?
> 
> @klnrdknt I am not sure how your issue relates to this ticket... Do yo have issues when installing with `get-poetry.py`?

I thought it might be, but it could be related to some VPN issue, sorry. I'll investigate further and create an issue if necessary.

**Comment by sinoroc** [comment]
@klnrdknt Do yo have issues when installing with `get-poetry.py`?

> there werent any changes to poetry, correct? Lase update was 1.1.4 in october.

Correct.

**Comment by Toxe** [comment]
> @Toxe Should we close the issue, if the root cause is the download speed from some 3rd party server and thus out of _poetry_'s control?

Yes, I'll close it now.
