### ISSUE TITLE
Request control of number of parallel processes

### ISSUE THREAD

**Issue by jmuncaster** [python-poetry/poetry#3465]
On a fast computer with a fast internet connection and a library with lots of dependencies, we get errors running the default `poetry install` because too many parallel processes are hitting the pypi servers at once.

Disabling the new installer fixes this problem.

If we could control the size of the parallel process pool we could achieve some of the speed gains of the new installer without the risks of being blocked by the pypi server.

Reference PR below

_Originally posted by @abn in https://github.com/python-poetry/poetry/issues/2595#issuecomment-704875923_

**Comment by danielloader** [comment]
This is quite the pain when you have a gigabit home connection, pypicloud is exhausting mysql connections when I try to resolve a large dependency tree.
