### ISSUE TITLE
Communicate a projects used poetry version in a team

### ISSUE THREAD

**Issue by tmbo** [python-poetry/poetry#3469]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

Since the lockfile format changed in 1.1.x an update of poetry requires all developers working on the project to upgrade their poetry version. 

Previously, the `pyproject.toml` contained the version of the recommended poetry version to use for a project, e.g.
```
[build-system]
requires = [ "poetry>=1.0.4",]
build-backend = "poetry.masonry.api"
```

This got replaced though, with a reference to the `poetry-core` builder (which uses independent versioning scheme). Therefore, it is unclear what the recommended way is to communicate the used poetry version. Do you have any recommendations?

**Comment by sinoroc** [comment]
Duplicate of https://github.com/python-poetry/poetry/issues/3316 ?

**Comment by tmbo** [comment]
yes you are right. thanks for the pointer - the combination "poetry version" is just very hard to search for 😂
