### ISSUE TITLE
poetry publish fails for multiple pyproject.toml authors

### ISSUE THREAD

**Issue by rdmolony** [python-poetry/poetry#3473]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows Subsystem for Linux 2 with ...
```
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic
```
- **Poetry version**: v1.1.4
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/rdmolony/723039a9f0a53bc07770cea04db14723

## Issue

`poetry publish` fails when `pyproject.toml` contains multiple authors with ...

```bash
❯ poetry publish -vvv

No suitable keyring backend found
No suitable keyring backends were found
Using a plaintext file to store and retrieve credentials
Username: rdmolony
Password: 
Publishing berpublicsearch (0.1.0) to PyPI
 - Uploading berpublicsearch-0.1.0-py3-none-any.whl 100%

  Stack trace:

  7  ~/miniconda3/envs/ber/lib/python3.8/site-packages/clikit/console_application.py:131 in run
      129│             parsed_args = resolved_command.args
      130│ 
    → 131│             status_code = command.handle(parsed_args, io)
      132│         except KeyboardInterrupt:
      133│             status_code = 1

  6  ~/miniconda3/envs/ber/lib/python3.8/site-packages/clikit/api/command/command.py:120 in handle
      118│     def handle(self, args, io):  # type: (Args, IO) -> int
      119│         try:
    → 120│             status_code = self._do_handle(args, io)
      121│         except KeyboardInterrupt:
      122│             if io.is_debug():

  5  ~/miniconda3/envs/ber/lib/python3.8/site-packages/clikit/api/command/command.py:171 in _do_handle
      169│         handler_method = self._config.handler_method
      170│ 
    → 171│         return getattr(handler, handler_method)(args, io, self)
      172│ 
      173│     def __repr__(self):  # type: () -> str

  4  ~/miniconda3/envs/ber/lib/python3.8/site-packages/cleo/commands/command.py:92 in wrap_handle
       90│         self._command = command
       91│ 
    →  92│         return self.handle()
       93│ 
       94│     def handle(self):  # type: () -> Optional[int]

  3  ~/miniconda3/envs/ber/lib/python3.8/site-packages/poetry/console/commands/publish.py:77 in handle
      75│         )
      76│ 
    → 77│         publisher.publish(
      78│             self.option("repository"),
      79│             self.option("username"),

  2  ~/miniconda3/envs/ber/lib/python3.8/site-packages/poetry/publishing/publisher.py:93 in publish
      91│         )
      92│ 
    → 93│         self._uploader.upload(
      94│             url,
      95│             cert=cert or get_cert(self._poetry.config, repository_name),

  1  ~/miniconda3/envs/ber/lib/python3.8/site-packages/poetry/publishing/uploader.py:119 in upload
      117│ 
      118│         try:
    → 119│             self._upload(session, url, dry_run)
      120│         finally:
      121│             session.close()

  UploadError

  HTTP Error 400: 'rowan.molony@codema.ie>, Oisin Doherty <oisin.doherty@codema.ie' is an invalid value for Author-email. Error: Use a valid email address See https://packaging.python.org/specifications/core-metadata for more information.

  at ~/miniconda3/envs/ber/lib/python3.8/site-packages/poetry/publishing/uploader.py:216 in _upload
      212│                     self._register(session, url)
      213│                 except HTTPError as e:
      214│                     raise UploadError(e)
      215│ 
    → 216│             raise UploadError(e)
      217│ 
      218│     def _do_upload(
      219│         self, session, url, dry_run=False
      220│     ):  # type: (requests.Session, str, Optional[bool]) -> None
```
---

To reproduce try `poetry publish` for any `pyproject.toml` based repository containing multiple authors

---

btw thanks for creating and maintaining `poetry`, it's a ridiculously useful tool!

**Comment by sinoroc** [comment]
Your `pyproject.toml` reads:

```
authors = ["Rowan Molony <rowan.molony@codema.ie>, Oisin Doherty <oisin.doherty@codema.ie>"]
```

But instead it should read:

```
authors = ["Rowan Molony <rowan.molony@codema.ie>", "Oisin Doherty <oisin.doherty@codema.ie>"]
```

or formatted differently:

```
authors = [
    "Rowan Molony <rowan.molony@codema.ie>",
    "Oisin Doherty <oisin.doherty@codema.ie>",
]
```

Notice how each name and email has to be enclosed in double quotes. Those are partly missing in your `pyproject.toml`.

**Comment by rdmolony** [comment]
Wow I can't believe I missed that, thanks @sinoroc 😃 

For future eejits like myself this bug occured as a result of entering multiple authors during `poetry init`

```bash
Author [Rowan Molony <rowan.molony@codema.ie>, n to skip]: Rowan Molony <rowan.molony@codema.ie>, Oisin Doherty <oisin.doherty@codema.ie>
```

**Comment by sinoroc** [comment]
Glad we fixed it. Should the ticket be closed then?

**Comment by rdmolony** [comment]
Sure thing, wanted to leave it up to you to decide whether or not the `poetry init` mistake is worth looking into further but imo this issue is probably enough!

**Comment by sinoroc** [comment]
> wanted to leave it up to you to decide whether or not the `poetry init` mistake is worth looking into further

Ah, I see. I am not one of the maintainers, so can't decide for them. From my point of view `poetry init` asks for `Author` and not `Author(s)` and the default value that is shown is a single name/email, so it seems explicit enough. Maybe it might be worth opening a _feature request_ ticket (not a bug ticket) to ask for the possibility to add multiple authors via `poetry init`.

**Comment by sinoroc** [comment]
On the other hand, maybe the pyproject parser could catch up on this (`poetry check` as well). And then the distribution core metadata generated by poetry (`poetry build`) seems a bit shaky, not sure it is valid.

**Comment by shasherazi** [comment]
Even after adding multiple authors correctly, my pypi page only shows the first one

**Comment by mkniewallner** [comment]
> Even after adding multiple authors correctly, my pypi page only shows the first one

Packaging core metadata specification [only allows one author](https://packaging.python.org/en/latest/specifications/core-metadata/#author), so if you define multiple ones, only the first one will be used when uploading the package to PyPI.

**Comment by shasherazi** [comment]
> > Even after adding multiple authors correctly, my pypi page only shows the first one
> 
> Packaging core metadata specification [only allows one author](https://packaging.python.org/en/latest/specifications/core-metadata/#author), so if you define multiple ones, only the first one will be used when uploading the package to PyPI.

Anyway to ask for this shiny feature?

**Comment by Secrus** [comment]
> > Packaging core metadata specification [only allows one author](https://packaging.python.org/en/latest/specifications/core-metadata/#author), so if you define multiple ones, only the first one will be used when uploading the package to PyPI.
> 
> Anyway to ask for this shiny feature?

What feature do you mean? If you want to see multiple authors on PyPI page, you should raise an issue in [warehouse repo](https://github.com/pypi/warehouse) (this is the project that powers PyPI)

**Comment by sinoroc** [comment]
@shasherazi @Secrus This is not to be solved by `warehouse` solely. Changing "packaging core metadata" would need agreement of the whole packaging ecosystem (starting with PyPA).

Anyway, I am confused. As already mentioned: in Core Metadata "Author" seems to not be marked as "multiple use". But if we look at [_PEP 621_' `authors`](https://peps.python.org/pep-0621/#authors-maintainers), it seems to allow multiple use.

**Comment by sinoroc** [comment]
It was discussed here: https://discuss.python.org/t/pep-621-round-3/5472/72

I do not seem to find any conclusion in the discussion.

Closest to a conclusion is that if there are multiple authors then they should be all added to the same `Author` core metadata field separated by commas. Which in my opinion does not align with the definition and example given in core metadata doc where there is a comma but used for something else:

```
Author: C. Schultz, Universal Features Syndicate,
        Los Angeles, CA <cschultz@peanuts.example.com>```

**Comment by ankit48365** [comment]
> authors = ["Rowan Molony <rowan.molony@codema.ie>, Oisin Doherty <oisin.doherty@codema.ie>"]

Guys, I am facing similar issue 

- if i try this (below) it errors out at poetry publish command
- authors = ["Rowan Molony <rowan.molony@codema.ie>, Oisin Doherty <oisin.doherty@codema.ie>"]

if I try below - then it doesn't error out, but just shows first author name in pypi.org
- authors = ["Rowan Molony <rowan.molony@codema.ie>","Oisin Doherty <oisin.doherty@codema.ie>"]

**Comment by neersighted** [comment]
The first is invalid, the second is as expected -- the [Core Metadata](https://packaging.python.org/en/latest/specifications/core-metadata/#author) only supports one author. See #7229 for a duplicate question.
