### ISSUE TITLE
Help reques - How to speed up poetry dependancy resovle/install?

### ISSUE THREAD

**Issue by zillionare** [python-poetry/poetry#3479]
- [ x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Issue

The problem is deps resolve is very slow in **China mainland.** ,due to poetry need to access pypi.org. Usually with pip/conda, we'll set their source to mirrors which located in china mainland, so the speed is very fast. However, poetry won't use these mirrors for index lookup (this include download packages). In installation step, it seems to leverage these mirrors, but works occasionally (I don't know when exactly it download packages from mirrors, but I have observed several times).

I have experienced more than 30 minutes dependancy resolution (not finished yet). Then I tried to add packages one by one, yesterday with pandas it failed again and again, even I have tried use proxy to speed.

So I'm here to ask for help, how to speed up this process? The possible solutions I know are:

### 1. pyproject.toml

add this to pyproject.toml:
```
[[tool.poetry.source]]
name = "ali"
url = "https://mirrors.aliyun.com/pypi/simple/"
default = true
```

Actually this solution is meant to add private repo, other than speed up deps resolving.  Poetry still has to (by design) access pypi.org to get index info, so it can not solve speed problem perfectly. And in my case, seems poetry still download from pypi in most case.

### 2. use a https proxy server

I have used this solution and successfully solved one of my project. But it fail yesterday night when resolve/install pandas. Proxy in china is still slow and not stable.

### 3. setup a custom proxy server with address rewrite

setup a local nginx server, use proxy_pass to redirect pypi requests  to their mirror sites in china.  I tried this but I'm not famliar with nginx, so failed yesterday. Anyone else have tried this?

### 4. Modify poetry

Modify poetry's source code in local, overwrite all request to pypi to their mirror site. How and where?

### 5. use proxypi

as suggested by @jaharkes, setup a proxpi server at local. I haven't tried this solution, but the key point is how to let poetry, other than pip to use this server. Actually we have a lot of mirror sites quite fast in China, the issue is how to let poetry use it.

### 6. share cache with pip

is it possible to let poetry and pip share cache? if possible, then it's possible to download files manually from mirror sites. 

### 7. any other solutioins?

Does anyone sufferred same issue and is seeking solution? Would you please share your thoughts?

**Comment by jaharkes** [comment]
I don't think this is really directly related to poetry. Your problem is that you don't own the pypi.org domain, so your server can't provide the right SSL certificate for a secure connection.

At some point I did set up a local pypi proxy for CI jobs. I used https://pypi.org/project/proxpi/ and it required setting some environment variables in the containers to tell pip to use (and trust) a local http server, so without needing SSL between pip and the proxy.

So you might just need to look into setting the right PIP_INDEX_URL and PIP_TRUSTED_HOST environment to point at your local nginx.

**Comment by zillionare** [comment]
> 
> 
> I don't think this is really directly related to poetry. Your problem is that you don't own the pypi.org domain, so your server can't provide the right SSL certificate for a secure connection.
> 
> At some point I did set up a local pypi proxy for CI jobs. I used https://pypi.org/project/proxpi/ and it required setting some environment variables in the containers to tell pip to use (and trust) a local http server, so without needing SSL between pip and the proxy.
> 
> So you might just need to look into setting the right PIP_INDEX_URL and PIP_TRUSTED_HOST environment to point at your local nginx.

Thanks @jaharkes ! I've modified my question so it describe my situation and problems well. If you're watching this, please help share more.

**Comment by ZeroAurora** [comment]
I've drafted a PR allowing poetry to use mirror source. I'd love you to give it a shot and feedback. See #3624

**Comment by sinoroc** [comment]
@zillionare There is a PR that could solve this issue. Would you be able to test it, give feedback? https://github.com/python-poetry/poetry/pull/3624

**Comment by dimaqq** [comment]
I wonder if https://github.com/pypa/warehouse needs to know, could own or could solve this...
