### ISSUE TITLE
Make "virtualenv" an optional requirement

### ISSUE THREAD

**Issue by phacic** [python-poetry/poetry#3482]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

Virtualenv looks to be a redundant requirement when using poetry with docker. I believe it would be helpful if it was made an optional requirement. This will reduce the install time when having a bad internet (like where I am) also reduce the docker image size.

Thanks

**Comment by sinoroc** [comment]
Personally I do not find this a compelling argument to make _virtualenv_ an optional dependency. I would rather say you probably should figure out a way to not use poetry in the containers. And I would also point out that using virtual environments in a container is not that uncommon and is often recommended.

**Comment by phacic** [comment]
@sinoroc so you saying you would rather not use poetry with docker. Do you have reasons to back your argument?

**Comment by sinoroc** [comment]
@phacic All depends on the use cases. But the typical use case I can think of is that you simply install the application in the container. So you usually only need _pip_ to install an application, not _poetry_. Basically you would `poetry export --output requirements.txt` outside of the container, and `pip install --requirement requirements.txt` in the container (in a virtual environment). Even better I would use a _wheelhouse_ (i.e. download all the wheels in advance), and `pip install --no-index path/to/wheelhouse/*.whl`.

**Comment by n8sty** [comment]
I would check out this comment: https://github.com/python-poetry/poetry/issues/1879#issuecomment-592133519. Farther down in the issue the comment's author links to a sample repo that's good for inspiration.

**Comment by finswimmer** [comment]
Hello @phacic,

creating venv is a core feature for poetry. Saying this, it would confuse most people if `virtualenv` would be an optional dependency.

fin swimmer
