### ISSUE TITLE
If it's worthwhile for poetry to support generate executable and self-contained python zip archives(zipapp)?

### ISSUE THREAD

**Issue by innerNULL** [python-poetry/poetry#3488]
Hi, recently I'm thinking about that if poetry can support building **zipapp** (ref to [28.4. zipapp — Manage executable python zip archives](https://python.readthedocs.io/en/latest/library/zipapp.html) and [PEP 441](https://www.python.org/dev/peps/pep-0441/))，with this feature, when submitting jobs to clusters such as spark is much more convinent for poetry-building projects~

**Comment by sinoroc** [comment]
Maintainers somewhat have this feature in mind. I could not find a specific dedicated ticket on this though, but here are somewhat related tickets:

* https://github.com/python-poetry/poetry/pull/2682
* https://github.com/python-poetry/poetry/issues/2778
* https://github.com/python-poetry/poetry/issues/2873
* https://github.com/python-poetry/poetry/pull/3341

**Comment by hyliu1989** [comment]
Our group decided to use `shiv` to create the zip archives. You can also check that out. At current stage, unfortunately, to communicate the python environment specification with our collaborators and even within our group needs this tool...

**Comment by innerNULL** [comment]
> Our group decided to use `shiv` to create the zip archives. You can also check that out. At current stage, unfortunately, to communicate the python environment specification with our collaborators and even within our group needs this tool...

@hyliu1989 Got it~thank u for your work~

**Comment by sinoroc** [comment]
Ah yes, if you are open to 3rd party tools then _shiv is a good one. There is also _pex_. And I wrote _zapp_ that has very limited features but works well enough for very simple projects (without C extensions, etc.):

* https://pypi.org/project/shiv/
* https://pypi.org/project/pex/
* https://pypi.org/project/zapp/

**Comment by innerNULL** [comment]
> Ah yes, if you are open to 3rd party tools then _shiv_ is a good one. There is also _pex_. And I wrote _zapp_ that has very limited features but works well enough for very simple projects (without C extensions, etc.):
> 
>     * https://pypi.org/project/shiv/
> 
>     * https://pypi.org/project/pex/
> 
>     * https://pypi.org/project/zapp/

@sinoroc haha for now, I'm using a trick that 1st execute `poetry run which python` to get the virtual python env path, and then I can copy and archive the whole path as a zip file and using this zip when running some jobs on clusters such as spark : )
