### ISSUE TITLE
Poetry does not clean up unfinished downloads when canceling resulting in errors

### ISSUE THREAD

**Issue by atigbadr** [python-poetry/poetry#3496]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **Manjaro Linux 20.2 (Nibia)**: 
- *1.1.4**: 
- **Not needed**: 

## Issue

I have been playing around with poetry when i came into an interesting bug, i've initialized a project and started adding packages using `poetry add package`

However when i cancel a package mid installation, and the next time i try to upgrade the package with `poetry add package@latest` i get the following error: 
```python
EnvCommandError

  Command ['/home/badr/.cache/pypoetry/virtualenvs/test-1TUJnh2D-py3.8/bin/pip', 'install', '--no-deps', 'file:///home/badr/.cache/pypoetry/artifacts/28/f1/1f/0c02253ed24d65eeec11e5e60bda6c8ef6695aca52cffdfaef1d854be3/scipy-1.5.4-cp38-cp38-manylinux1_x86_64.whl'] errored with the following return code 2, and output: 
  Looking in indexes: https://casa.registry.saas.cagip.gca/api/pypi/casa-datalab-pypi-scratch-intranet/simple, https://casa.registry.saas.cagip.gca/api/pypi/pypi-remote/simple
  Processing /home/badr/.cache/pypoetry/artifacts/28/f1/1f/0c02253ed24d65eeec11e5e60bda6c8ef6695aca52cffdfaef1d854be3/scipy-1.5.4-cp38-cp38-manylinux1_x86_64.whl
  ERROR: Exception:
  Traceback (most recent call last):
    File "/home/badr/.cache/pypoetry/virtualenvs/test-1TUJnh2D-py3.8/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 216, in _main
      status = self.run(options, args)
    File "/home/badr/.cache/pypoetry/virtualenvs/test-1TUJnh2D-py3.8/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 182, in wrapper
      return func(self, options, args)
    File "/home/badr/.cache/pypoetry/virtualenvs/test-1TUJnh2D-py3.8/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 324, in run
      requirement_set = resolver.resolve(
    File "/home/badr/.cache/pypoetry/virtualenvs/test-1TUJnh2D-py3.8/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 183, in resolve
      discovered_reqs.extend(self._resolve_one(requirement_set, req))
    File "/home/badr/.cache/pypoetry/virtualenvs/test-1TUJnh2D-py3.8/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 391, in _resolve_one
      dist = abstract_dist.get_pkg_resources_distribution()
    File "/home/badr/.cache/pypoetry/virtualenvs/test-1TUJnh2D-py3.8/lib/python3.8/site-packages/pip/_internal/distributions/wheel.py", line 29, in get_pkg_resources_distribution
      with ZipFile(self.req.local_file_path, allowZip64=True) as z:
    File "/home/badr/miniconda3/lib/python3.8/zipfile.py", line 1269, in __init__
      self._RealGetContents()
    File "/home/badr/miniconda3/lib/python3.8/zipfile.py", line 1336, in _RealGetContents
      raise BadZipFile("File is not a zip file")
  zipfile.BadZipFile: File is not a zip file
  WARNING: You are using pip version 20.2.2; however, version 20.3.3 is available.
  You should consider upgrading via the '/home/badr/.cache/pypoetry/virtualenvs/test-1TUJnh2D-py3.8/bin/python -m pip install --upgrade pip' command.
  

  at ~/.poetry/lib/poetry/utils/env.py:1074 in _run
      1070│                 output = subprocess.check_output(
      1071│                     cmd, stderr=subprocess.STDOUT, **kwargs
      1072│                 )
      1073│         except CalledProcessError as e:
    → 1074│             raise EnvCommandError(e, input=input_)
      1075│ 
      1076│         return decode(output)
      1077│ 
      1078│     def execute(self, bin, *args, **kwargs):
```

In order to resolve this i have to clean up all the artificats manually for example `/home/badr/.cache/pypoetry/artifacts/28/f1/1f/0c02253ed24d65eeec11e5e60bda6c8ef6695aca52cffdfaef1d854be3/scipy-1.5.4-cp38-cp38-manylinux1_x86_64.whl`

#### How to reproduce this bug:
1. poetry init
2. poetry add scitkit-learn
3. Ctrl-C mid installation
4. poetry add scitkit-learn@latest
5. Notice error

It seems to be trouble some, i have experieced the same issue when i lost internet mid package downloads, it would be nice if poetry could clean up these unfinished packages.

**Comment by sinoroc** [comment]
Related:

* https://github.com/python-poetry/poetry/issues/3326

**Comment by mario-bermonti** [comment]
I can confirm this happens to me on MacOS, python 3.7.0, pip 20.2.2, poetry 1.1.4. It occurs with some packages (ex., pytest), but not others. However, it occurs even if the installation is not canceled. It just happens. I am able to solve the issue by removing all artifacts manually as done by @atigbadr  and @alimantu in issue #2388. 

Should I open a new issue if in my case it happens even when the download is not canceled?

**Comment by mario-bermonti** [comment]
It works if I disable the new installer as was recommended by @abn in issue #2388
