### ISSUE TITLE
Installation script doesn't set the path to the poetry installation dir to $PATH on MacOS without $ZDOTDIR specified

### ISSUE THREAD

**Issue by anton-kozlovsky** [python-poetry/poetry#3513]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **MacOS BigSur 11.1 (20C69)**: 
- **P1.1.4**: 

## Issue
After I'd executed `curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3 -` I tried to get the version:
```
$ poetry --version                                                                                
zsh: command not found: poetry
```

I checked `.zshrc` and didn't found anything related to poetry. Then I reviewed the code of `get-poetry.py` and found that in order to setup the path to poetry ZDOTDIR env variable should be set. But there is nothing in the docs about it. By default it is not set.

**Comment by maximiliancw** [comment]
Can confirm this on macOS Catalina 10.15.7

**Comment by anton-kozlovsky** [comment]
Recently my colleague faced the same problem on Ubuntu with bash.

**Comment by davidfstr** [comment]
Confirmed on macOS 11.2.3 (Big Sur), the latest version of macOS at the time of writing.

Impact is that Poetry is not usable after installation on the latest macOS 11, for a fresh macOS 11. This is a **poor first-time run experience for the latest version of macOS** and I would advocate it be treated as high priority.

**Comment by davidfstr** [comment]
[Related issue](https://github.com/python-poetry/poetry/issues/3394), which more directly addresses that Poetry is not usable directly after installation on macOS.

**Comment by finswimmer** [comment]
`get-poetry.py` is deprecated. Use `install-poetry.py` from now on. Here we decided to not set any environment variables at all, because people don't like it.
