### ISSUE TITLE
poetry add fails on ubuntu18.04 docker on Mac

### ISSUE THREAD

**Issue by haizumi-kyohei** [python-poetry/poetry#3518]
hello.

I use mac and use docker to use ubuntu environment.
I failed to poetry add.
what is wrong?

```
docker run -it ubuntu:18.04 bash
apt update
apt install -y python3 python3-pip curl
ln -s /usr/bin/python3 /usr/bin/python
curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
export PATH=$PATH:/root/.poetry/bin
poetry new test
cd test
poetry add numpy

------
root@710eab950aa0:/test# poetry add numpy
Creating virtualenv test-swbZ_4R8-py3.6 in /root/.cache/pypoetry/virtualenvs
Using version ^1.19.4 for numpy
Updating dependencies
Resolving dependencies... (36.6s)
Writing lock file
Failed to add packages, reverting the pyproject.toml file to its original content.
--------

```

**Comment by sinoroc** [comment]
Don't know. You might want to use `poetry add -vvv numpy` for the verbose output so that we can see more details and try to pinpoint what is going wrong.

**Comment by haizumi-kyohei** [comment]
thank you.
I tried that but I don't know where is the problem.

root@2b91258775cf:~/test# poetry add numpy -vvv
Using virtualenv: /root/.cache/pypoetry/virtualenvs/test-DVdBw2hf-py3.6
PyPI: No release information found for numpy-0.9.6, skipping
PyPI: No release information found for numpy-0.9.8, skipping
PyPI: No release information found for numpy-1.0.3, skipping
PyPI: No release information found for numpy-1.0.4, skipping
PyPI: No release information found for numpy-1.0b1, skipping
PyPI: No release information found for numpy-1.0b4, skipping
PyPI: No release information found for numpy-1.0b5, skipping
PyPI: No release information found for numpy-1.0rc1, skipping
PyPI: No release information found for numpy-1.0rc2, skipping
PyPI: No release information found for numpy-1.0rc3, skipping
PyPI: No release information found for numpy-1.1.1, skipping
PyPI: No release information found for numpy-1.2.0, skipping
PyPI: No release information found for numpy-1.2.1, skipping
PyPI: No release information found for numpy-1.4.0, skipping
PyPI: 68 packages found for numpy *
Using version ^1.19.4 for numpy

Updating dependencies
Resolving dependencies...
   1: fact: test is 0.1.0
   1: derived: test
   1: fact: test depends on numpy (^1.19.4)
   1: fact: test depends on pytest (^5.2)
   1: fact: test depends on pytest (^5.2)
   1: selecting test (0.1.0)
   1: derived: pytest (^5.2)
   1: derived: numpy (^1.19.4)
   1: fact: pytest (5.4.3) depends on py (>=1.5.0)
   1: fact: pytest (5.4.3) depends on packaging (*)
   1: fact: pytest (5.4.3) depends on attrs (>=17.4.0)
   1: fact: pytest (5.4.3) depends on more-itertools (>=4.0.0)
   1: fact: pytest (5.4.3) depends on pluggy (>=0.12,<1.0)
   1: fact: pytest (5.4.3) depends on wcwidth (*)
   1: fact: pytest (5.4.3) depends on importlib-metadata (>=0.12)
   1: fact: pytest (5.4.3) depends on atomicwrites (>=1.0)
   1: fact: pytest (5.4.3) depends on colorama (*)
   1: selecting pytest (5.4.3)
   1: derived: colorama (*)
   1: derived: atomicwrites (>=1.0)
   1: derived: importlib-metadata (>=0.12)
   1: derived: wcwidth (*)
   1: derived: pluggy (>=0.12,<1.0)
   1: derived: more-itertools (>=4.0.0)
   1: derived: attrs (>=17.4.0)
   1: derived: packaging (*)
   1: derived: py (>=1.5.0)
PyPI: No release information found for numpy-0.9.6, skipping
PyPI: No release information found for numpy-0.9.8, skipping
PyPI: No release information found for numpy-1.0.3, skipping
PyPI: No release information found for numpy-1.0.4, skipping
PyPI: No release information found for numpy-1.0b1, skipping
PyPI: No release information found for numpy-1.0b4, skipping
PyPI: No release information found for numpy-1.0b5, skipping
PyPI: No release information found for numpy-1.0rc1, skipping
PyPI: No release information found for numpy-1.0rc2, skipping
PyPI: No release information found for numpy-1.0rc3, skipping
PyPI: No release information found for numpy-1.1.1, skipping
PyPI: No release information found for numpy-1.2.0, skipping
PyPI: No release information found for numpy-1.2.1, skipping
PyPI: No release information found for numpy-1.4.0, skipping
PyPI: 1 packages found for numpy >=1.19.4,<2.0.0
PyPI: Getting info for numpy (1.19.4) from PyPI
PyPI: No dependencies found, downloading archives
PyPI: Downloading sdist: numpy-1.19.4.zip
   1: selecting numpy (1.19.4)
   1: selecting colorama (0.4.4)
   1: selecting atomicwrites (1.4.0)
   1: fact: importlib-metadata (3.3.0) depends on zipp (>=0.5)
   1: fact: importlib-metadata (3.3.0) depends on typing-extensions (>=3.6.4)
   1: selecting importlib-metadata (3.3.0)
   1: derived: typing-extensions (>=3.6.4)
   1: derived: zipp (>=0.5)
   1: selecting wcwidth (0.2.5)
   1: fact: pluggy (0.13.1) depends on importlib-metadata (>=0.12)
   1: selecting pluggy (0.13.1)
   1: selecting more-itertools (8.6.0)
   1: selecting attrs (20.3.0)
   1: fact: packaging (20.8) depends on pyparsing (>=2.0.2)
   1: selecting packaging (20.8)
   1: derived: pyparsing (>=2.0.2)
   1: selecting py (1.10.0)
   1: selecting typing-extensions (3.7.4.3)
   1: selecting zipp (3.4.0)
   1: selecting pyparsing (2.4.7)
   1: Version solving took 27.577 seconds.
   1: Tried 1 solutions.

Writing lock file

Finding the necessary packages for the current system

Package operations: 12 installs, 0 updates, 0 removals, 3 skipped


Failed to add packages, reverting the pyproject.toml file to its original content.

**Comment by sinoroc** [comment]
I can recreate the behaviour, on Ubuntu and with other dependencies. Looks like it has nothing to do with _Mac_ or _numpy_.

**Comment by mkniewallner** [comment]
This issue is quite old. Is it still relevant, or should it be closed?

**Comment by dimbleby** [comment]
I verified that poetry 1.2.0b2 installs numpy 1.19.4 successfully in a python 3.6 environment on ubuntu 18.04

(not completely trivial to do these days because recent poetry has dropped support for python 3.6, so to get a recent poetry on an old ubuntu you first need to install a recent python...)

anyway this seems now fixed, can be closed
