### ISSUE TITLE
Python 2 used, then warned about, for all new installs

### ISSUE THREAD

**Issue by ron-wolf** [python-poetry/poetry#3519]
The warning presented by the following piece of code appears every time I run Poetry: https://github.com/python-poetry/poetry/blob/2aab9bcd495e11e5f4491aa72a9510773cc4a90e/poetry/console/application.py#L50-L52

However, the Python executable used to run Poetry was set to `python` (the Python 2 command) when I installed it: https://github.com/python-poetry/poetry/blob/2aab9bcd495e11e5f4491aa72a9510773cc4a90e/get-poetry.py#L676 https://github.com/python-poetry/poetry/blob/2aab9bcd495e11e5f4491aa72a9510773cc4a90e/get-poetry.py#L695

This is because I ran `get-poetry.py` using `python`, as instructed in the docs: https://github.com/python-poetry/poetry/blob/2aab9bcd495e11e5f4491aa72a9510773cc4a90e/docs/docs/index.md#L24-L27

It seems like this is the only place that the version of Python is hard-coded, as the only other place the Python executable or version is referenced is [`console/commands/self/update.py`](https://github.com/python-poetry/poetry/blob/2aab9bcd495e11e5f4491aa72a9510773cc4a90e/poetry/console/commands/self/update.py) (lines 49 and 265–282). Do I just manually change the shebang at the top of `$POETRY_HOME/bin/poetry` to read `#!/usr/bin/env python3`? Or will this be done for me automatically when Poetry 1.2 is installed?

**Comment by sinoroc** [comment]
***Related***

* [_How to disable Poetry 1.1 warnings? (#3029)_](https://github.com/python-poetry/poetry/issues/3029)
* [_No method to control the python version used (#522)_](https://github.com/python-poetry/poetry/issues/522)
* [_poetry default to using python instead of python3 (#3184)_](https://github.com/python-poetry/poetry/issues/3184)
* [_Choose the host Python version used when running poetry installed with 'get-poetry.py'_ (#3288)](https://github.com/python-poetry/poetry/issues/3288)

**Comment by finswimmer** [comment]
Hello @ron-wolf,

as @sinoroc showed, this topic already exists. That's why I'm closing yours.

fin swimmer

**Comment by MPvHarmelen** [comment]
@finswimmer, I would want to vouch for reopening this issue: the related issues mentioned by @sinoroc are indeed related, but do not cover the fact that the _recommended_ way of installing poetry leads to warnings on systems that already support python3.

1. The [installation instructions](https://python-poetry.org/docs/#installation) mention explicitly that installing using `get-poetry.py` is the recommended way:
    > Poetry provides a custom installer that will install poetry isolated from the rest of your system by vendorizing its dependencies. This is the recommended way of installing poetry.
2. After having run the recommended installation, practically any invocation of poetry leads to the deprecation warning mentioned above.

While #3029, #522 and #3288 are about _configuring_ the used python version and #3184 is about _changing_ the default version (of which most are possible solutions to this issue), _this issue_ is about making sure the recommended way of installing does not lead to warnings on supported systems, irrespective of the solution.

Importantly, the solution to this issue should not require configuration using other programs (like `pyenv`). Put frankly: the recommended way of installing poetry should "Just Work™".
