### ISSUE TITLE
PyPI Project Description Missing

### ISSUE THREAD

**Issue by SeanPedersen** [python-poetry/poetry#3532]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Issue
I have just published my first package on PyPI [https://pypi.org/project/hypertag/](https://pypi.org/project/hypertag/) using poetry and everything went smooth but one little thing: The project description is missing. I expected poetry to automatically insert the projects README file. Is that working as expected? How do I add the project description?

**Comment by sinoroc** [comment]
The [notation](https://github.com/SeanPedersen/HyperTag/blob/b13b4c9b651f134c9ed2c917d6786e11dc6cba00/pyproject.toml#L5) seems correct. But looks like the distributions that have been uploaded were built without the `readme` setting. You can check this by downloading and inspecting the [_sdist_](https://files.pythonhosted.org/packages/0f/d9/a5dedcba813eb26c580766967cb2024376d46e86bc40e3c78d1fcd5bb481/hypertag-0.1.0.tar.gz) from [_PyPI_](https://pypi.org/project/hypertag/0.1.0/#files).

**Comment by SeanPedersen** [comment]
Ah thank you so much! I bumped the version rebuilt and published again. Now it works.
