### ISSUE TITLE
How to include an executable from the dependency to my own app?

### ISSUE THREAD

**Issue by kakyoism** [python-poetry/poetry#3533]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Issue

I'm using Poetry to manage my application dependency and virtual environment.

Although the PyPI package publication can be handled seamlessly with Poetry, I'm unable to find docs on how to solve my case:

 - My app depends on a package which includes an executable.
 - In the dev environment, this executable can only be installed to cache folder via `poetry install`.
 - The executable has its own sub-dependencies in the cache folder, but it's unclear to me what exactly those sub-dependencies are.

The app's runtime needs to use this executable, but I'm not sure how to extract this executable and all its own dependency and ship with my app.

Is there a poetry command or pattern for this scenario?

**Comment by finswimmer** [comment]
Hello @kakyoism,

it's unclear to me how your situation looks like. If the executable is part of another package, you can just declare that package as a dependency and it will get installed when you install your package.

Could you please add some more information, to make your situation clearer?

fin swimmer

**Comment by kakyoism** [comment]
> 
> Could you please add some more information, to make your situation clearer?
> 
@finswimmer OK. I'm going to freeze my Python app into a DMG and ship it to other macOS users. So I expect this DMG to be an all-in-one package, so that the end users won't have to download anything. 

However, one dependency of my app itself has an executable that is built from its own pipeline during the `poetry install`. This package gets installed into the cache folder includes the executable, say under here

```
/Users/me/Library/Caches/pypoetry/virtualenvs/myapp-deX2xl2G-py3.8/bin/theirexec
```

It has other dependencies under those cached bin/lib folders.
To my understanding, all mainstream freezers such as PyInstaller will then have to specify those dependencies in their `setup.py`. But this would be super hard, because it'd be very difficult to manually specify those sub-dependencies. And even we could, according to my test, some sub-dependencies such as dynamic libraries are linked to the executable using their absolute paths. Those must be updated to the end-user paths or @rpaths on installation time. 

Correct me if I'm wrong. It seems that my dependencies are already "installed" onto my machine. To ship to another machine, I would then have to somehow turn them into another form to be able to install to other machines, if we do not use the PyPI or github repositories. 

Would this be more clear now?
Thanks in advance.

**Comment by sinoroc** [comment]
* Maybe we should move this to: https://github.com/python-poetry/poetry/discussions

* I see you asked the question here as well: https://stackoverflow.com/questions/65546669/how-to-ship-an-executable-from-a-dependency

---

Your question does not make much sense to me. Seems like maybe it is out of scope for poetry.

For example poetry does not handle building DMG files as far as I can tell, it is out of scope for poetry. And in general I do not really understand what is the blocker.

Maybe you are looking for something like [_BeeWare_'s _`briefcase`_](https://pypi.org/project/briefcase/).

**Comment by kakyoism** [comment]
@sinoroc Thanks for the recommendation. Beeware looks good for what I need and handles dependency with its own toml.

But that looks like yet another solution of handling dependencies. 

I would like to clarify a few things:

- Is Poetry just a package manager living inside the Python PiPy package ecosystem, in the sense that Poetry's end product is meant to be a PiPy package used by another Python package? 
- To go from a Poetry build to a redistributable executable that the end user can run on their computer, I would need things like `briefcase`, correct?

If the above is correct, then I misunderstood Poetry's feature scope. I was trying to find a solution to managing the entire build and distribution pipeline for a Python-based cross-platform project, all the way to the application installer for each platform.

**Comment by stephsamson** [comment]
> * Is Poetry just a package manager living inside the Python PiPy package ecosystem, in the sense that Poetry's end product is meant to be a PiPy package used by another Python package?

Yes, that's correct (in addition to a bit of project management, though that will also have to depend on the Python community's adoption of pyproject.toml as a standard configuration file).

>     * To go from a Poetry build to a redistributable executable that the end user can run on their computer, I would need things like `briefcase`, correct?

That's right.

> I was trying to find a solution to managing the entire build and distribution pipeline for a Python-based cross-platform project, all the way to the application installer for each platform. Something like the Electron eco-system, where you use yarn/npm to manage packages, and a few packages such as electron-forge/electron-builder to create an installer. You can pretty much create the entire application in a standard way.

As far as I know, poetry has no ambitions to do something like Electron but perhaps @sdispater or @abn can chime in.

**Comment by sinoroc** [comment]
I would say, the end goal of poetry (at least right now, as far as I can tell) is to let you distribute your project (library, application, etc.) on _PyPI_. If you want to go further than that you will need additional tools on top of poetry or other tools in replacement of poetry.

**Comment by sinoroc** [comment]
In addition to _briefcase_, you could look into [_kivy_](https://kivy.org/): https://kivy.org/doc/stable/guide/packaging.html

I am sure there plenty of other tools whose end goal is to have a full installer for the target platform (executable installer on windows, dmg on mac, etc.). Maybe in the Qt ecosystem.

**Comment by sinoroc** [comment]
Some more links/ideas:

* https://www.riverbankcomputing.com/software/pyqtdeploy/
* https://doc.qt.io/qtforpython/deployment.html
* https://build-system.fman.io/
* https://github.com/r0x0r/pywebview

**Comment by stephsamson** [comment]
@kakyoism I will close this issue for now, but if you have any more questions, please feel free to re-open it. Thanks 🙌🏽
