### ISSUE TITLE
why get-poetry.py still prompting for PATH modification even after providing --no-modify-path?

### ISSUE THREAD

**Issue by mohan43u** [python-poetry/poetry#3542]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Linux
## Issue

I downloaded get-poetry.py as per the Documentation (https://python-poetry.org/docs/#osx-linux-bashonwindows-install-instructions) and disabled modifying PATH using (--no-modify-path). But still get-poetry.py prompting to modify shell rc files or not, why? isn't explicitly setting modify_path (through --no-modify-path) not enough for get-poetry.py to understand the intention of the user?

This prompting becomes irritating when automating poetry installation, I have to do `"echo 'n' | python3 get-poetry.py --no-modify-path"` instead of simply saying `"python3 get-poetry.py --no-modify-path"`.

**Comment by finswimmer** [comment]
The `get-poetry.py` is now deprecated and will be replaced by `install-poetry.py` which will not change any env variables at all.

See https://python-poetry.org/blog/announcing-poetry-1.2.0a1/#deprecation-of-the-get-poetrypy-script
