### ISSUE TITLE
Add flag for `poetry add` command for when adding local path to use edit mode (a.k.a set develop = true)

### ISSUE THREAD

**Issue by chrisdruta** [python-poetry/poetry#3546]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

Add flag for `poetry add` command for when adding local path to use edit mode (a.k.a set develop = true)

This would be super useful and easy to add, thanks

**Comment by sinoroc** [comment]
Duplicate?

* https://github.com/python-poetry/poetry/issues/3220
* https://github.com/python-poetry/poetry/issues/3452

**Comment by chrisdruta** [comment]
Yes sorry, my search was apparently not good enough, mb
