### ISSUE TITLE
Why is it so low even if  I modify poetry's source?

### ISSUE THREAD

**Issue by Chise1** [python-poetry/poetry#3547]
When I use poetry ,it spent so much time in Resolving dependencies... (602.3s).

I has add this config code in pyproject.toml

`

[[tool.poetry.source]]
url = "https://mirrors.aliyun.com/pypi/simple/"
name = "aliyun"
default = true

`
If I use pip,I can install a package so faster.
I don't know why poetry spent so much time in Resolving dependencies

**Comment by sinoroc** [comment]
Duplicate of https://github.com/python-poetry/poetry/issues/3479 ?

From that ticket, it seems like even though the default source is not _PyPI_, poetry still connects to _PyPI_ for some of its operations...

**Comment by Chise1** [comment]
That's a terrible thing...
