### ISSUE TITLE
Is the PR #3350 for docs NOT reflected?

### ISSUE THREAD

**Issue by nukopy** [python-poetry/poetry#3558]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

Hi:) Thanks for excellent tool "Poetry".

## Issue

A wrong command ``source`poetry env info --path`/bin/activate is found`` in docs, the section "Using your virtual environment" in "Basic Usage". A whitespace is missing.

Although this is fixed in PR #3350, but the view of documentation in a browser is not fixed like below(inside the red frame):

![104107012-cbd67d80-52fc-11eb-88ea-4764dc9c0d45](https://user-images.githubusercontent.com/42367320/104107494-e1997200-52ff-11eb-8847-cddd10fcddce.png)

(the screenshot at 2021/01/10 4am JST(+0900))

I think this is because the previous PR #3350 is reflected to the repository, NOT the server Poetry's documentation is put on. Please investigate this issue.

Thanks.

**Comment by finswimmer** [comment]
This is fixed in master. Thanks for reporting :+1:
