### ISSUE TITLE
support i18n

### ISSUE THREAD

**Issue by renmu123** [python-poetry/poetry#3559]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

It would be great if poetry supports i18n(Internationalization). l want to translate th docs to my local language,so more people may know this great tool.

**Comment by ruohola** [comment]
Waste of time to support this.

**Comment by Secrus** [comment]
@renmu123 committing to i18n would require having dedicated translators, that would make sure every change in documentation is translated. Poetry team has no such capabilities at this moment.
