### ISSUE TITLE
(Activated) but it's not

### ISSUE THREAD

**Issue by kaldown** [python-poetry/poetry#3560]
```
list
    Lists all virtualenvs associated with the current project.

    --full-path          Output the full paths of the virtualenvs.
```
but then 
```
✗ poetry env list --full-path
/home/kaldown/.cache/pypoetry/virtualenvs/dorm-worker-qqMHwzdW-py3.9 (Activated)
```
I created two projects with two envs and they are completely fresh.
Why two identical fresh project with different envs have different (Activated) status?
Assuming shell called this command should be "activated"?
But it is not!

What is `(Activated)` then?
And please, add this note into documentation.

**Comment by ericriff** [comment]
I also find this terminology confusing.
In this context, `Activated` means something like "Selected". It means that that it the environment that poetry will use if you invoke a command like `poetry run`, `poetry shell`, `poetry install`, etc.
If you do something like `poetry env use 3.8` (asumming that you have python 3.8 installed) poetry will create a new environment  for python 3.8 and that will be the one listed as `Activated`.
To activate the 3.9 one again, do `poetry env use 3.9`.

**Comment by kaldown** [comment]
If what you say is the actual flow, then one of the environments must be activated all the time.
But, shows me single one, and it's not activated:
```
✗  poetry env list
dir1-ohFkNBde-py3.9
```


while it is for the other project dir
```
✗ poetry env list
dir2-qqMHwzdW-py3.9 (Activated)
```

**Comment by kaldown** [comment]
after doing `poetry env use 3.9` it becomes activated.
But I **never** did it by my own for the second project.
It confuses me to the ground

**Comment by kaldown** [comment]
I think it shouldn't be in one line. Sine why it does many things at once:
1) showing full path
2) telling me it is activated
let's split it with flags at least.
Think it's not big of a deal, since you changed interface drastically since prev. versions anyway.

**Comment by ericriff** [comment]
> I think it shouldn't be in one line. Sine why it does many things at once:
> 
> 1. showing full path
> 2. telling me it is activated
> 
> Let's split it with flags at least.
> Think it's not big of a deal, since you changed interface drastically since prev. versions anyway.

You can totally do this i.e. `poetry env info --path`



> If what you say is the actual flow, then one of the environments must be activated all the time.
> But, shows me single one, and it's not activated:
> 
> ```
> ✗  poetry env list
> dir1-ohFkNBde-py3.9
> ```
> 
> while it is for the other project dir
> 
> ```
> ✗ poetry env list
> dir2-qqMHwzdW-py3.9 (Activated)
> ```

It was my understading that always one env had to be activated. Maybe it has a deeper meaning than just 'selected'.

**Comment by kaldown** [comment]
`poetry env info --path` returns nothing if it's not activated. But `poetry shell` works as expected. That's why it's confusing.

> It was my understading that always one env had to be activated. Maybe it has a deeper meaning than just 'selected'.
I think the same. As it will auto-activate when necessary. Then `Activated` flag only useful when there are multiple envs for a project. But why would anyone need that one - I don't know.

**Comment by finswimmer** [comment]
Hello @kaldown,

you haven't come back to this issue for a long while. So I assume this is solved in the meantime and I can close this ticket.

Feel free to leave a comment if you disagree.

fin swimmer
