### ISSUE TITLE
Multiple Platform syntax not working

### ISSUE THREAD

**Issue by Leon0402** [python-poetry/poetry#3561]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Linux, Windows
- **Poetry version**: 1.1.0 - 1.4.0

## Issue

Specifying multiple entries for a dependency doesn't work. This basically continues https://github.com/python-poetry/poetry/issues/2138, which has been marked as resolved. 

I tried several combinations and none worked. Among the things I tried were the following things:

torch = [
    {url = "https://download.pytorch.org/whl/cu102/torch-1.6.0-cp38-cp38-win_amd64.whl", python = "~3.8", markers = "sys_platform == 'win32'" },
    {version = "1.6.0", markers = "sys_platform != 'win32'" }
]

torch = [
    {url = "https://download.pytorch.org/whl/cu102/torch-1.6.0-cp38-cp38-win_amd64.whl", python = "~3.8", platform = "win32" },
    {version = "1.6.0", platform = "linux || darwin" }
]

I tried both and similar variations of the two above with poetry 1.1.0, 1.1.1, 1.1.2, 1.1.3 and 1.1.4

In all cases, the first entry was always used no matter what platform I was on. So on Linux it downloaded the windows wheel. And On Windows, if you changed the order, it took the instructions for linux / mac os.

**Comment by johnmacnamararseg** [comment]
might be same as what I ran into here [3511](https://github.com/python-poetry/poetry/issues/3511). 

submitted PR [3512](https://github.com/python-poetry/poetry/pull/3512) to fix but waiting for triage and response

**Comment by Leon0402** [comment]
I'm not quite sure, it doesn't work on 1.1.3 either (whereas you reported the issue is just in 1.1.4). 

I ran it in debug mode and got the following output: 
```
   0: Duplicate dependencies for torch
   0: Merging requirements for torch (=1.6.0)
   0: Duplicate dependencies for torchvision
   0: Merging requirements for torchvision (=0.7.0)
```

Before that poetry also needs ages, seems almost stuck.

**Comment by LironEr** [comment]
Im using the latest poetry (1.2.0a1)

when using version & markers it's working ok
```
[tool.poetry.dependencies]
python = "~3.7"
example-package = [
    { version = "0.5.0", markers = "sys_platform != 'darwin'" },
    { version = "0.4.1", markers = "sys_platform == 'darwin'" },
]
```
on mac poetry install 0.4.1, and generate lock file for both versions


But when using path & markers, it just takes the first entry in the package array

```
example-package = [
    { version = "0.5.0", markers = "sys_platform != 'darwin'" },
    { path = "libs/example-package-0.5-mac.tar.gz", markers = "sys_platform == 'darwin'" },
]
```
regardless my OS poetry install & lock only 0.5

**Comment by xinyangyuan** [comment]
> Im using the latest poetry (1.2.0a1)
> 
> when using version & markers it's working ok
> 
> ```
> [tool.poetry.dependencies]
> python = "~3.7"
> example-package = [
>     { version = "0.5.0", markers = "sys_platform != 'darwin'" },
>     { version = "0.4.1", markers = "sys_platform == 'darwin'" },
> ]
> ```
> 
> on mac poetry install 0.4.1, and generate lock file for both versions
> 
> But when using path & markers, it just takes the first entry in the package array
> 
> ```
> example-package = [
>     { version = "0.5.0", markers = "sys_platform != 'darwin'" },
>     { path = "libs/example-package-0.5-mac.tar.gz", markers = "sys_platform == 'darwin'" },
> ]
> ```
> 
> regardless my OS poetry install & lock only 0.5


same issue when using URL & markers:

```
torch = [
    { version = "^1.9.0", platform = "darwin" },
    { url = "https://download.pytorch.org/whl/cu111/torch-1.9.0%2Bcu111-cp39-cp39-win_amd64.whl", platform = "win32" },
]
````

**Comment by Yevgnen** [comment]
Same issue here...

**Comment by dimbleby** [comment]
seems to work fine on master

**Comment by neersighted** [comment]
Unable to reproduce on 1.2.x -- please open a issue with a detailed reproduction if you think you are running into this.
