### ISSUE TITLE
Carriage Return Or In Progress Download Disabling

### ISSUE THREAD

**Issue by cpvandehey** [python-poetry/poetry#3568]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request
Hi Poetry Team!

This is very simple and would help readability in CI builds.

We are using poetry 1.1.4 in our CI building system right now (_based off of Jenkins_). The output for `poetry install` has exploded in length due to the new and cool carriage return download progress features that were put in recently.

Heres an example of what can be seen in Jenkins/TravisCI/{Any CI Building system}
```
       • Installing zipp (3.4.0): Pending...
       • Installing zipp (3.4.0): Downloading... 0%
       • Installing zipp (3.4.0): Downloading... 100%
       • Installing zipp (3.4.0): Downloading... 100%
       • Installing zipp (3.4.0): Installing...
       • Installing zipp (3.4.0)
       • Removing zipp (3.4.0): Pending...
       • Removing pytest (6.1.2): Pending...
       • Removing toml (0.10.2): Pending...
       • Removing pluggy (0.13.1): Pending...
       • Removing pytest (6.1.2): Pending...
       • Removing toml (0.10.2): Pending...
       • Removing zipp (3.4.0): Skipped for the following reason: Not currently installed
```
`zipp` is one of many dependencies that will be outputted many, many times.

Carriage returns and download progress should be disabled for continuous integration systems that do not support these types of terminal output. Our workaround has been to work in silent mode and results in less "debug ability" when installations are problematic. Ideally, `poetry install -v` should support a primitive terminal mode to prevent output explosions.

Thanks for your time!

**Comment by brandon-leapyear** [comment]
Echo this. IIUC most tools only have fancy overwriting output behavior in a tty; shouldn't poetry also check if the terminal is a tty?

**Comment by dimbleby** [comment]
> The problem remains that a single dependency repeats its status continuously causing 10-100 lines per dependency installed being logged.

presumably something has changed since this was written, `--no-ansi` is now sufficient to keep that from happening

this can be closed

**Comment by neersighted** [comment]
Appears to have been fixed in Cleo; `--no-ansi` to a non-TTY does not print duplicate output on 1.2.2.
