### ISSUE TITLE
poetry on win10 returns poetry.utils._compat.CalledProcessError

### ISSUE THREAD

**Issue by egor187** [python-poetry/poetry#3571]
- [ x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [ x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: 
- **Poetry version**: 
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue

Everytime when i try to create env in NEW project or when try it in exist project poetry.utils._compat.CalledProcessError: Command 'C:\Users\home_\AppData\Local\pypoetry\Cache\virtualenvs\study-JYh534Fc-py3.9\Scripts\python.exe -' returned non-zero exit status 1. 

Working on win 10 and ubuntu with WSL. 
Try to run poetry from PyCharm community in cloned project from Github.
Poetry plugin installed on PyCharm.

It looks like a problem creating a virtual environment at the specified location. However, I cannot fully understand what the problem is. Has anyone come across a similar one?

In addition, when running poetry run python through Powershell in the finished project, it gives the following error:

  Command C:\Users\home_\AppData\Local\pypoetry\Cache\virtualenvs\study-JYh534Fc-py3.9\Scripts\python.exe - errored with the following return code 1, and output:
  ¨áâ¥¬¥ ­¥ ã¤ ¥âáï ­ ©â¨ ãª § ­­ë© ¯ãâì.
  input was : import sys

  if hasattr(sys, "real_prefix"):
      print(sys.real_prefix)
  elif hasattr(sys, "base_prefix"):
      print(sys.base_prefix)
  else:
      print(sys.prefix)

  at ~\.poetry\lib\poetry\utils\env.py:1074 in _run
      1070│                 output = subprocess.check_output(
      1071│                     cmd, stderr=subprocess.STDOUT, **kwargs
      1072│                 )
      1073│         except CalledProcessError as e:
    → 1074│             raise EnvCommandError(e, input=input_)
      1075│
      1076│         return decode(output)
      1077│
      1078│     def execute(self, bin, *args, **kwargs):

Please tell me how to solve this problem

**Comment by youguanxinqing** [comment]
Pls write steps for reproduce it or more details. Poetry works on my win10 machine.

**Comment by egor187** [comment]
I don't know what exactly happened, but everything started working correctly when I configured "poetry virtualenvs.in-project: True". After that, PyCharm was able to correctly configure the poetry environment, and no longer gave the specified error

**Comment by TextileTopher** [comment]
I'm having this issue as well...
