### ISSUE TITLE
Add link to dependency specification in the add command documentation

### ISSUE THREAD

**Issue by tpow** [python-poetry/poetry#3573]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue
It took me much too long to figure out how to specify package versions and what the caret meant. I looked at the documentation for the `add` command, but it only gives a cursory overview of setting constraints. I tried to find it with Google and ended up with [PEP-440](https://www.python.org/dev/peps/pep-0440/) which was good, but doesn't explain the caret. For some reason I completely missed the dependency specification in the Poetry documentation sidebar. I guess that is not the terminology I was looking for, even though it makes sense.

Adding a message like the following to the [Add command](https://python-poetry.org/docs/cli/#add) documentation would really help:

> See the [dependency specification](https://python-poetry.org/docs/dependency-specification/) for more information on setting the version constraints for a package.

I think part of what made this difficult is that it is a different mindset than how I normally work with python packages. With pip, I'm typically installing an exact version or latest. With poetry, I'm trying to put constraints in place so it can upgrade reasonably "safely" and get me the version I want now. I therefore needed more details about how to specify the constraints.

**Comment by Secrus** [comment]
PRs on that are welcome.
