### ISSUE TITLE
--short has no effect when `poetry version` is passed a new version

### ISSUE THREAD

**Issue by sprt** [python-poetry/poetry#3577]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 16.04
- **Poetry version**: 1.1.4
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: n/a

## Issue

Hi there!

Assuming the current version of a project is 0.1.0, this is what happens when trying to update to the next patch version with the `--short` option:

```console
$ poetry version patch --short
Bumping version from 0.1.0 to 0.1.1
```

Instead, I would like this to be output (only the new version number):

```console
$ poetry version patch --short
0.1.1
```

My use case is scripting: if the user only provides a bump rule to my script, I'd like to be able to easily parse the new version computed by poetry so that I can e.g. create a new git tag easily, and so on.

Thanks!

**Comment by sprt** [comment]
PS: I'm happy to contribute a PR. @stephsamson please let me know if I can proceed. :)

**Comment by stephsamson** [comment]
@sprt Yes, that would be much appreciate! 💫 I will assign you to this issue then.
