### ISSUE TITLE
How to use poetry with Django project (make application portable)

### ISSUE THREAD

**Issue by zvolsky** [python-poetry/poetry#3578]
This is a question.
I want reopen this issue or question
https://github.com/python-poetry/poetry/issues/1050
to know more about usage with Django.

Django as whole project has its dependencies typically in a virtual environment so I think it is usual to use poetry for the whole project.

However poetry has build/publish features.
And we usually want make a single django (custom) application portable.
**Is it possible build/publish single application with poetry, while poetry root (.toml+.lock) is at the main project level?**

I have made a new .toml inside the application directory (project's subdirectory) but have had no success with this.

Later I have copied the application folder into an empty folder with same name. And inside the outer folder I can make a .toml file and I am able to build. I have no idea if the result is correct.

I think things could work so that in the main .toml file we will create subsections for applications we want to build separately, and the `poetry build` command we could start with optional parameter (application ie. subsection name). Of course, this is not possible.

Is there a good approach how to build portable django application using Poetry?

**Comment by sinoroc** [comment]
There is a place for Q&A: https://github.com/python-poetry/poetry/discussions/categories/q-a

**Comment by zvolsky** [comment]
Thank you. I made this: https://github.com/python-poetry/poetry/discussions/3582
So the issue can be closed.
