### ISSUE TITLE
Override dependencies during development

### ISSUE THREAD

**Issue by DorianCzichotzki** [python-poetry/poetry#3593]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Issue
Is there a way to add a path dependency only during development?
Imagine you have two packages A and B and A has a dependency on B.

What I would like to do is to use B as a path dependency in A for concurrent development on both packages.
But as soon as A is built it should use a default dependency on B (e.g from pypi).

It would be nice if one could override dependencies for the local environment, without changing the pyproject.toml.

**Comment by sinoroc** [comment]
There are tickets on this topic already. Notably this one: https://github.com/python-poetry/poetry/issues/1168. Do you agree?

**Comment by DorianCzichotzki** [comment]
@sinoroc You are right. Missed that.

Closing in favor of #1168
