### ISSUE TITLE
get-poetry.py should fail with exit code > 1 if an invalid version is specified with --version

### ISSUE THREAD

**Issue by torlenor** [python-poetry/poetry#3595]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 20.04
- **Poetry version**: 1.1.4
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: N/A 

## Issue

When executing get-poetry.py and specifying a non-existing version the script exits with an exit code of 0. In such a case the script should exit with an exit code > 0, because clearly an error happened. This would help to know that something goes wrong without the need to parse the output of the script when, for example, installing it during a Docker build.

Here is an example:
```bash
$ python3 ./get-poetry.py --version 1.2.3
Retrieving Poetry metadata

Version 1.2.3 does not exist.

$ echo $?
0
```

The script should return an exit code > 0 in that case.

**Comment by finswimmer** [comment]
The `get-poetry.py` is deprecated and will be replaced by the `install-poetry.py` script. The issue seems to exist there as well. Would be happy to review a PR (https://github.com/python-poetry/install.python-poetry.org) :)

**Comment by stinodego** [comment]
@finswimmer I opened a PR in the repo you linked. Let me know if this is what you were looking for :)

**Comment by stinodego** [comment]
Since @abn merged my PR, this ticket can now be closed!

**Comment by abn** [comment]
Resolved via python-poetry/install.python-poetry.org#10
