### ISSUE TITLE
Poetry Add (Permission Denied)

### ISSUE THREAD

**Issue by waynegrigsby** [python-poetry/poetry#3596]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS Big Sur (Its also happening on my Windows 10 Machine)
- **Poetry version**: 1.1.4
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/waynegrigsby/c09092f66f4bf5ddf0550e13237b740a

## Issue
This is a recent occurrence. I use to be able to spin up poetry environments without error: 

`pyenv shell 3.9.1`

`poetry new projectxyz`

`cd projectxyz`

`poetry shell`

But now when I attempt to add libraries I get this bizarre error I haven't seen before. The interesting piece is I get it on both MAC and Windows environments. I must be doing something wrong. 

`poetry add pandas` <-- gets me an error

```
Updating dependencies
Resolving dependencies... (0.1s)

  PermissionError

  [Errno 13] Permission denied: '/Users/user/Library/Caches/pypoetry/cache/repositories/pypi/_http/b/3/e/8/6/b3e86e7c2d7427a3cd7b7079a8af58ef4e48403cb0fe68a48de599a2'

  at ~/.poetry/lib/poetry/_vendor/py3.9/cachecontrol/caches/file_cache.py:111 in get
      107│ 
      108│     def get(self, key):
      109│         name = self._fn(key)
      110│         try:
    → 111│             with open(name, "rb") as fh:
      112│                 return fh.read()
      113│ 
      114│         except FileNotFoundError:
      115│             return None
```
Here is my poetry debug: 

```
Poetry
Version: 1.1.4
Python:  3.9.1

Virtualenv
Python:         3.9.1
Implementation: CPython
Path:           /Users/wgrigsby/Library/Caches/pypoetry/virtualenvs/gu-C0nDFtAR-py3.9
Valid:          True

System
Platform: darwin
OS:       posix
Python:   /Users/wgrigsby/.pyenv/versions/3.9.1
```

**Comment by sinoroc** [comment]
You might want to check what is going on permission-wise on that folder: `/Users/user/Library/Caches/pypoetry/cache/repositories/pypi/_http/b/3/e/8/6/b3e86e7c2d7427a3cd7b7079a8af58ef4e48403cb0fe68a48de599a2`

**Comment by waynegrigsby** [comment]
> You might want to check what is going on permission-wise on that folder: `/Users/user/Library/Caches/pypoetry/cache/repositories/pypi/_http/b/3/e/8/6/b3e86e7c2d7427a3cd7b7079a8af58ef4e48403cb0fe68a48de599a2`

Well damn, sometimes the most obvious solution is the right one. Whats odd is I (as a user) already had direct permissions to that directory, but when I granted "everyone" access to not only read but write, it worked. Thanks @sinoroc! Appreciate the assist!

**Comment by engineerkong** [comment]
> You might want to check what is going on permission-wise on that folder: `/Users/user/Library/Caches/pypoetry/cache/repositories/pypi/_http/b/3/e/8/6/b3e86e7c2d7427a3cd7b7079a8af58ef4e48403cb0fe68a48de599a2`

Hi I want to ask where did you find this folder?
