### ISSUE TITLE
Command to check if virtualenv is out of sync with lockfile

### ISSUE THREAD

**Issue by justinaustin** [python-poetry/poetry#3599]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

Poetry command to check if the virtualenv is out of sync with the lockfile. For example, this can be useful to discover potential bugs if a user manually pip installs something in the virtualenv and then forgets or if a user checks out a new branch with a different lockfile than what `poetry install` was run on. This could even be a warning whenever `poetry run` or similar is executed.

**Comment by sinoroc** [comment]
Doesn't `poetry show` already displays information in that direction? Or maybe `poetry update --dry-run`? But yes a dedicated command could be helpful.

**Comment by alexifm** [comment]
I found `poetry install --dry-run` to be very informative on this.  An actual poetry command to just verify the venv could be incorporated off of that logic but for the time being, parsing the output from the install dry-run could be the way to do this.

**Comment by dimbleby** [comment]
`poetry install --sync --dry-run` is sufficient, if slightly awkward.

given lack of interest in anyone implementing this in the last two years, probably time to close it

**Comment by justinaustin** [comment]
thank you for update
