### ISSUE TITLE
Are binary extensions supported?

### ISSUE THREAD

**Issue by igo95862** [python-poetry/poetry#3604]
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

Under binary extensions I mean [Python C API](https://packaging.python.org/guides/packaging-binary-extensions/) 

I looked through entire documentation and did not find anything related.

Maybe this question and the answer should be added to FAQ.

**Comment by sinoroc** [comment]
Unofficially. You can look for [`build.py`](https://github.com/python-poetry/poetry/issues?q=is%3Aissue+build.py) or [`tool.poetry.build`](https://github.com/python-poetry/poetry/issues?q=is%3Aissue+tool.poetry.build) and read threads like this one https://github.com/python-poetry/poetry/issues/2740. Is that what you are asking for?

**Comment by igo95862** [comment]
It can work. Definitely should be documented somewhere. I would have never found it. You can close the issue.

**Comment by sinoroc** [comment]
> Definitely should be documented somewhere. I would have never found it.

That is what "unofficial" means in this case.

> You can close the issue.

I can't, but as the author of the ticket you can.
