### ISSUE TITLE
Unable to find installation candidates, but can install via pip

### ISSUE THREAD

**Issue by furgoose** [python-poetry/poetry#3621]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: MacOS 11.1
- **Poetry version**: 1.1.4
- **Link of a [Gist](https://gist.github.com) with the contents of your pyproject.toml file**: https://gist.github.com/furgoose/11d52aedff9652f2d20b80962591f0e4

## Issue

When trying to install PySide6 via `poetry add PySide6`, it fails to find a candidate for the dependency shiboken6, despite being able to install normally using `pip install PySide6` within the environment. I've tried running with debug mode as noted above, but no additional helpful information is revealed.

**Comment by dbanty** [comment]
This is probably a duplicate of #3591.

**Comment by sinoroc** [comment]
Probably the most complete ticket is this one: https://github.com/python-poetry/poetry/issues/3458 (assuming it is indeed the same root cause).

**Comment by furgoose** [comment]
Ah yeah I missed those issues, looks to be the same cause. This can be closed then 👍🏻
