### ISSUE TITLE
poetry shell fails because of a space in path to env

### ISSUE THREAD

**Issue by mklengel** [python-poetry/poetry#3630]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **macOS 10.15.7**: 
- **Poetry 1.1.4**: 
- **https://gist.github.com/mklengel/e9c0d5e140769eedcf810c6a0c521380**: 

## Issue

The problem can be recreated with
```
$ cd /Volumes/Macintosh SR0/Users/mklengel/Development
$ mkdir poetry-test
$ cd poetry-test
$ poetry init
$ poetry-test poetry shell -vvv
Using virtualenv: /Volumes/Macintosh SR0/Users/mklengel/Development/poetry-test/.venv
Spawning shell within /Volumes/Macintosh SR0/Users/mklengel/Development/poetry-test/.venv
➜  poetry-test . /Volumes/Macintosh SR0/Users/mklengel/Development/poetry-test/.venv/bin/activate
.: no such file or directory: /Volumes/Macintosh
```
So the problem is most likely the space in the path.

**Comment by onnoeberhard** [comment]
I still have this exact same problem. My poetry version is 1.1.11.

**Comment by martin-kirilov** [comment]
I also have the same problem with version 1.1.13 on MacOS.

**Comment by mklengel** [comment]
According to https://github.com/python-poetry/poetry/pull/3631 this should be fixed?!
