### ISSUE TITLE
module not found: clikit ( master)

### ISSUE THREAD

**Issue by pwoolvett** [python-poetry/poetry#3633]
- [x ] I am on master

## Issue

* `poetry shell` still uses `from clikit.utils.terminal import Terminal`, but its not a cleo dependency

* ATM there are no tests for poetry shell

* 855bc88
* https://github.com/sdispater/cleo/commit/de55578da25c6b1736b8b818f21c1bacf7c2475d

**Comment by finswimmer** [comment]
Thanks a lot for reporting. Fix is in progress. (#3634)
