### ISSUE TITLE
Add option to build nightly packages

### ISSUE THREAD

**Issue by qiuwei** [python-poetry/poetry#3637]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request
add an option to build nightly packages. 
A possible cli usage
```
poetry build --nightly
```
outputs a package like `blahblah1.1.3.dev2021023`

**Comment by qiuwei** [comment]
I think it is already supported using prepatch etc versions.

**Comment by sinoroc** [comment]
You could also look into this: https://pypi.org/project/poetry-scmver/
(not a personal endorsement, I have never tried it)
