### ISSUE TITLE
Virtual environment using Python3's venv module rather than virtualenv

### ISSUE THREAD

**Issue by ppo** [python-poetry/poetry#3642]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

… sorry if it's a duplicate, there are too much content about venv/virtualenv!

## Feature Request

Apparently there's no option to have the virtual environments created/managed by Poetry using Python's native `venv` module instead of via `virtualenv` (and therefore not needing that extra pip package).

Could this option be implemented?

PS: Currently I defined `virtualenvs.create=false` and I create the virtual environment manually… manually 😕

**Comment by finswimmer** [comment]
Hello @ppo,

poetry decided some time ago to rely on `virtualenv` instead of pythons build-in `venv` module. The main reason for doing this was, that `virtualenv` makes sure to have a (more a less) current version of `pip` and `setuptools` in your new `venv`.

> PS: Currently I defined virtualenvs.create=false and I create the virtual environment manually… manually confused

You don't have to set `virtualenvs.create=false`. If poetry detects it's running within a `venv` it will not create a new one.

fin swimmer

**Comment by ppo** [comment]
Thanks for the answer @finswimmer 

As I'm not sure my request was crystal clear.  
So there's no chance to have an option like `virtualenvs.virtualenv=false` (default: `true`)?

_(not to debate, just saying…)_ Regarding the main reason of that decision, I always do anyway a `pip install --upgrade pip setuptools` right after creating a virtualenv, to be sure 😉

**Comment by finswimmer** [comment]
Hello @ppo,

> So there's no chance to have an option like virtualenvs.virtualenv=false (default: true)?

at least at the moment there is no chance, yes. Because poetry respects if there is already a venv, the user already have a method to create a venv in the way she/he like to.

fin swimmer

**Comment by gusutabopb** [comment]
@finswimmer Would Poetry maintainers be open to a PR to add this feature? I am also not a huge fan of `virtualenv` and would much rather use the native `venv` instead. I often find myself doing the following due to forgetting to create a venv before `poetry install`:

```bash
rm -rf .venv && python -m venv .venv && poetry install
```
