### ISSUE TITLE
poetry unable to install hbmqtt

### ISSUE THREAD

**Issue by FlorianLudwig** [python-poetry/poetry#3649]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Linux
- **Poetry version**: 1.1.4
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue

poetry is unable to install hbmqtt.

```
# poetry add -vvv hbmqtt

[...]

      Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "/usr/lib64/python3.9/tokenize.py", line 392, in open
          buffer = _builtin_open(filename, 'rb')
      FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-38j5rmex/setup.py'
```

Doing `pip install hbmqtt` works fine.

**Comment by flyte** [comment]
Thanks for issuing the PR to fix this, but in the mean time, is there a workaround available at all? I'd like to publish a new version of my project to PyPI but without changing back to using `setup.py` I can't.

**Comment by FlorianLudwig** [comment]
To be honest, I didn't spent time investigating a workaround as my workaround is to fork hbmqtt :]
