### ISSUE TITLE
Command to `exit 1` when lock is out-of-date.

### ISSUE THREAD

**Issue by Incognito** [python-poetry/poetry#3655]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

I want to check that my CI pipeline enforces pyproject.toml to always have an updated poetry.lock file.

It seems this feature _nearly_ already exists in because I can get a `warning` when doing a `poetry install --dry-run`, however, I'd like to fail early and not attempt any install.

Is it possible to get this feature added in one of these following ways via CLI?

- `poetry install --enforce-integrity`
- `poetry check --check-lock`
- `poetry verify-lock`

I recall some similar projects (like composer) lacked this feature and people introduced a lot of shell-hacks into their CI pipelines (parsing out warnings with grep, or re-calculating the hash with external scripts). It's possible but fragile, and it looks like most of the code to implement this feature already exists.

What do you think?

**Comment by sinoroc** [comment]
Maybe duplicate of https://github.com/python-poetry/poetry/pull/1954

**Comment by Incognito** [comment]
You're right, thanks!
