### ISSUE TITLE
Poetry could not find a matching version of package in windows

### ISSUE THREAD

**Issue by itobysq** [python-poetry/poetry#3665]
- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows 10 Enterprise 19041.746
- **Poetry version**: 1.1.4
- **Link of my super simple [Gist](https://gist.github.com/itobysq/b22b9669edc5a714d28ab89d6781a9c0) with the contents of my super simple pyproject.toml file**: 

## Issue

I am trying to install a python package in a private repo. The following command works

```
pip install --extra-index-url private-repo/simple private-package
```
Which tells me that it's not a permissions issue

If I try to use poetry from a clean project
1. poetry new debug
2. add the private-repo to the pyproject.toml
3. run poetry add -vvv private-package

I get the following
```
6  ~\.poetry\lib\poetry\_vendor\py3.8\clikit\console_application.py:131 in run
      129│             parsed_args = resolved_command.args
      130│
    → 131│             status_code = command.handle(parsed_args, io)
      132│         except KeyboardInterrupt:
      133│             status_code = 1

  5  ~\.poetry\lib\poetry\_vendor\py3.8\clikit\api\command\command.py:120 in handle
      118│     def handle(self, args, io):  # type: (Args, IO) -> int
      119│         try:
    → 120│             status_code = self._do_handle(args, io)
      121│         except KeyboardInterrupt:
      122│             if io.is_debug():

  4  ~\.poetry\lib\poetry\_vendor\py3.8\clikit\api\command\command.py:171 in _do_handle
      169│         handler_method = self._config.handler_method
      170│
    → 171│         return getattr(handler, handler_method)(args, io, self)
      172│
      173│     def __repr__(self):  # type: () -> str

  3  ~\.poetry\lib\poetry\_vendor\py3.8\cleo\commands\command.py:92 in wrap_handle
       90│         self._command = command
       91│
    →  92│         return self.handle()
       93│
       94│     def handle(self):  # type: () -> Optional[int]

  2  ~\.poetry\lib\poetry\console\commands\add.py:107 in handle
      105│             return 0
      106│
    → 107│         requirements = self._determine_requirements(
      108│             packages,
      109│             allow_prereleases=self.option("allow-prereleases"),

  1  ~\.poetry\lib\poetry\console\commands\init.py:328 in _determine_requirements
      326│             elif "version" not in requirement:
      327│                 # determine the best version automatically
    → 328│                 name, version = self._find_best_version_for_package(
      329│                     requirement["name"],
      330│                     allow_prereleases=allow_prereleases,

  ValueError

  Could not find a matching version of package private-package

  at ~\.poetry\lib\poetry\console\commands\init.py:367 in _find_best_version_for_package
      363│         )
      364│
      365│         if not package:
      366│             # TODO: find similar
    → 367│             raise ValueError(
      368│                 "Could not find a matching version of package {}".format(name)
      369│             )
      370│
      371│         return package.pretty_name, selector.find_recommended_require_version(package)
```

Thank you for reading my issue and for helping to develop poetry ❤️

**Comment by itobysq** [comment]
Some additional helpful information:

Cross posting from discord:

I don't have a scripts section in the pyproject.toml. What's in the gist is all there is [link](https://gist.github.com/itobysq/b22b9669edc5a714d28ab89d6781a9c0) 

private-package is also a poetry project. private-package was published on a mac and is a .whl file

The private repo is just internal. No auth required.

**Comment by sinoroc** [comment]
Is it normal that your URL field is not an actual URL?
```
[[tool.poetry.source]]
name = "cell"
url = "private-repo/simple"
default = true
```

**Comment by itobysq** [comment]
Thank you for taking a look @sinoroc ! The URL is just a toy URL. I was able to get some help on the discord server in this discussion

https://discord.com/channels/487711540787675139/487711540787675143/809109668563124224

It looks like the issue is related to the private repo permissions and is not an issue with poetry

**Comment by tylermanning** [comment]
@itobysq How did you solve this? I'm having the same issue adding private repos from git of the form:
`poetry add my-repo git+ssh://git@git.drwholdings.com/my-team/my-repo.git`

Some work, some don't and i can't figure out why. Getting same error as you did above.

**Comment by sinoroc** [comment]
> @itobysq How did you solve this? I'm having the same issue adding private repos from git of the form:
> `poetry add my-repo git+ssh://git@git.drwholdings.com/my-team/my-repo.git`
> 
> Some work, some don't and i can't figure out why. Getting same error as you did above.

You do not have the same issue. Your issue seems to me like an error in the command line. You would need to do `poetry add git+ssh://...`. Note how I removed the single `my-repo` and went straight to the git URI.

**Comment by danielbellhv** [comment]
Sometimes, the `import <NAME>` **isn't** the same as `pip install <NAME>` / `poetry add <NAME>` :

Example:
```python
import icd10
```

Install / Poetry:
```
pip install icd10-cm
poetry add icd10-cm
```

It's convention that the import name is the same as the install name - which isn't always the case.
