### ISSUE TITLE
poetry remove --dry-run modifies poetry.lock

### ISSUE THREAD

**Issue by samestep** [python-poetry/poetry#3666]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS Big Sur Version 11.2
- **Python version**: Python 3.8.3
- **Poetry version**: Poetry version 1.1.4
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/samestep/7fab4df48b7b4f89ea5fe5c29f7d4692

## Issue

As the title states, running `poetry remove --dry-run` modifies `poetry.lock`. Example:
```sh
poetry new remove-dry-run-bug
cd $_
sed -i '' 's/^authors = \[".*"\]/authors = []/' pyproject.toml
cat pyproject.toml # see gist
poetry add pyyaml
cp poetry.lock{,.old}
poetry remove --dry-run pyyaml
git diff --no-index poetry.lock{.old,} | tee poetry.lock.diff # see gist
```
This causes subsequent commands (such as `poetry show`) to fail.

**Comment by getup8** [comment]
Yeah I'm on the latest version of poetry and just ran:

`poetry add djangorestframework@latest --dry-run` just to test what it would do and it updated `poetry.lock` (it did not update the actual package locally).

This seems pretty bad no?
