### ISSUE TITLE
Add support for CI-based build number in version

### ISSUE THREAD

**Issue by aaronsteers** [python-poetry/poetry#3670]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

Currently, Poetry supports 3-part build numbers with `major.minor.patch` but there does not to be any support for a fourth build-number part. This is problematic because pypi will only accept unique version numbers and these can only be generated by way of updating the source code in `pyproject.toml` (manually or via `version bump`) followed by: `git commit` and `git push`.

In supporting a fourth `build` part into the version string, we would allow a version increment on subsequent code modifications without forcing developers to push a code-committed modification on `pyproject.toml`.

Proposed solution:

Using something like the below, we would set the (optional) build number portion of the version. When implemented, the version string will be a four-part identifier `major.minor.patch.build` - with only the first three parts being permanently committed to the code repo.

```bash
> poetry version --short
1.2.3
> poetry version --build-num $GITLAB_BUILD_NUM
Build number `101` appended to version string.
> poetry version --short
1.2.3.101
```

In contrast with a version bump command, the build number portion is time-bound (sequentially incremented over all builds and branches) but does not require modifying source code (`pyproject.toml`) and it is always guaranteed to be unique - so long as the CI engine provides support for the build number argument.

**Comment by aaronsteers** [comment]
UPDATE:

I was able to implement the following workaround:

```bash
poetry version $(poetry version --short).$GITHUB_RUN_NUMBER
```

Run from the CI pipeline, this will append the build number (`$GITHUB_RUN_NUMBER`) to the three-part name. Since this version of the code is not idempotent, it's important not to commit the resulting update. For CI pipelines, however, that seems appropriate and workable for this case.

**Comment by sinoroc** [comment]
I guess, maybe there are some 3rd party tools that can help with that. For example, maybe https://pypi.org/project/poetry-dynamic-versioning/

Otherwise, once the plugin system for poetry is ready and released this could be made easier.

**Comment by dimbleby** [comment]
18 months of silence later I think we can say there's no great enthusiasm for this; and indeed `poetry version` as it stands seems to me sufficient.

suggest closing

**Comment by neersighted** [comment]
I agree that is particularly niche and the ability to set the version with a shell command is intended to allow arbitrary templating using shell variables.

**Comment by aaronsteers** [comment]
Thanks, @neersighted. I think this plugin may do the trick for us:

- https://pypi.org/project/poetry-dynamic-versioning/

**Comment by godfryd** [comment]
I implemented a plugin that allows the version override:
https://github.com/godfryd/poetry-arbitrary-version-plugin
