### ISSUE TITLE
UnicodeEncodeError while doing docker setup.

### ISSUE THREAD

**Issue by viksts** [python-poetry/poetry#3672]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: 
- **Poetry version**: 
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue
Trying to do setup of my project through docker on my development server. While installing poetry it is giving error
`UnicodeEncodeError
'ascii' codec can't encode character '\u2022' in position 2: ordinal not in range(128)
at ~/.poetry/lib/poetry/_vendor/py3.6/clikit/io/output_stream/stream_output_stream.py:24 in write
The command '/bin/sh -c python3 ~/.poetry/bin/poetry install -n' returned a non-zero code: 1` but when i downgraded the poetry version to 1.0.10 it got installed properly.
Command :- curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python

**Comment by orlevii** [comment]
@viksts 
Hey, please try setting an env var in your `Dockerfile`:
```dockerfile
ENV PYTHONIOENCODING=utf-8
```

**Comment by chintan2181997** [comment]
> @viksts Hey, please try setting an env var in your `Dockerfile`:
> 
> ```dockerfile
> ENV PYTHONIOENCODING=utf-8
> ```

This didn't work for me. If you are using `docker-compose.yaml` then add the below environment into your container.

```
environment:
    - PYTHONIOENCODING
```=utf-8

**Comment by abn** [comment]
Related: https://github.com/python-poetry/poetry/issues/1427#issuecomment-537260307
