### ISSUE TITLE
Adding extras does not quite add extras

### ISSUE THREAD

**Issue by berislavlopac** [python-poetry/poetry#3674]
## Feature Request

I'm not sure if this is a feature request or a bug, but I was expecting that adding an extra dependency to a `pyproject.toml` file without a `[tool.poetry.extras]` section would add one automatically.

Basically, starting with this:

```
[tool.poetry.dependencies]
python = "==3.7"
```
And running:
```
poetry add -E foo requests
```
Results in:
```
[tool.poetry.dependencies]
python = "==3.7"
requests = {version = "^2.25.1", extras = ["foo"]}
```
Instead of the expected:
```
[tool.poetry.extras]
foo = ["requests"]

[tool.poetry.dependencies]
python = "==3.7"
requests = {version = "^2.25.1", extras = ["foo"]}
```
An attempt to install results in error:
```
poetry install --no-root -E foo

  ValueError

  Extra [foo] is not specified.

  at ~/.pyenv/versions/3.7.9/lib/python3.7/site-packages/poetry/installation/installer.py:223 in _do_install
      219│ 
      220│             # Checking extras
      221│             for extra in self._extras:
      222│                 if extra not in self._package.extras:
    → 223│                     raise ValueError("Extra [{}] is not specified.".format(extra))
      224│ 
      225│             self._io.write_line("Updating dependencies")
      226│             solver = Solver(
      227│                 self._package,
```
Similarly, removing an extra does not remove the extra specification; starting from:
```
[tool.poetry.extras]
foo = ["requests"]

[tool.poetry.dependencies]
python = "==3.7"
requests = {version = "^2.25.1", extras = ["foo"]}
```
This command:
```
poetry remove requests
```
results in:
```
[tool.poetry.extras]
foo = ["requests"]

[tool.poetry.dependencies]
python = "==3.7"
```
While I would have expected at least:
```
[tool.poetry.extras]
foo = []

[tool.poetry.dependencies]
python = "==3.7"
```
Would this make sense? :thinking:

**Comment by berislavlopac** [comment]
Come to think of it, do we even need `tool.poetry.extras`? I mean, it can easily be constructed when parsing `pyproject.toml` from the `extras = ["foo"]` part of a dependency definition... :thinking:

**Comment by finswimmer** [comment]
Hello @berislavlopac,

I thinks you are misunderstanding "extras" here.

A `poetry add -E foo requests` adds `requests` together with the extra `foo` provided by `requests`. So `requests` must have defined that it provides an extra named like this. The result of this command is the entry `requests = {version = "^2.25.1", extras = ["foo"]}` in the dependency section.

In the `[tool.poetry.extras]` you define extras your project provide. So that everyone who is installing your package, can say that the extras should be installed as well.

I hope I could clarify some things. If not, just leave a comment :)

fin swimmer

**Comment by berislavlopac** [comment]
Uhh doh, of course! You're right, I've misunderstood it completely... :flushed: I get it now, although it would be cool to have a `poetry` command to manage the `tool.poetry.extras` when adding dependencies... Thank you! :blush:
