### ISSUE TITLE
no .dist-info at ~~~ has pip

### ISSUE THREAD

**Issue by mjmaurer** [python-poetry/poetry#3683]
Just wanted to document the `no .dist-info at ~~~ has pip` error message. I ran into this when trying to install a venv with poetry. 

afaict, this was because poetry was using a system install of `virtualenv` for something. Uninstalling virtualenv by itself didn't work for me. I also had to remove virtualenv's config in `~/.local/share/virtualenv`. NOTE: if you plan on using `virtualenv` in the future, back up that directory as it might contain user state.

This issue can be closed

- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

**Comment by reinvantveer** [comment]
Thank you! This did it for me:
```shell
pip uninstall virtualenv
rm -r ~/.local/share/virtualenv 
pip install virtualenv
```

**Comment by BEEugene** [comment]
Same thing on windows 10.
Fixed similar to @reinvantveer by deleting C:\Users\{USERNAME}\AppData\Local\pypa
```
pip uninstall virtualenv
Manually delete C:\Users\{USERNAME}\AppData\Local\pypa
pip install virtualenv
```
