### ISSUE TITLE
Feature idea: setup() function

### ISSUE THREAD

**Issue by berislavlopac** [python-poetry/poetry#3693]
## Feature Idea: `setup()` function

Some organisations have a build pipeline which heavily depends on running `python setup.py build` and/or `python setup.py install`; it might be helpful to ease migration to poetry by providing a self- contained `setup` function which would work as a drop-in replacement for the one in `setuptools`. That way, we could have a `setup.py` file looking something like this:

```python
install poetry
poetry.setup()
```
It would work the same way as standard `setup.py`, or at the very least would provide a subset of standard commands compatible with Poetry.

Any thoughts?

**Comment by finswimmer** [comment]
Hello @berislavlopac,

it is not the goal of poetry to be a drop-in replacement of `setuptools`. So I don't think we will implement such a function.

Maybe what is currently discussed for [PEP 650](https://discuss.python.org/t/pep-650-specifying-installer-requirements-for-python-projects/6657) is interesting for you?

fin swimmer

**Comment by berislavlopac** [comment]
Yes, I saw that PEP, but a) I'm not sure if it's the right approach (I'd be happier with a standard lock file format), and b) that does not this particular use case. But it's fine, I'm considering potentially writing a custom wrapper that would do what I have in mind. Thank you! :slightly_smiling_face:
