### ISSUE TITLE
get-poetry.py: --no-modify-path does not work

### ISSUE THREAD

**Issue by terminalmage** [python-poetry/poetry#3703]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: CentOS 7.7
- **Poetry version**: N/A
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: N/A

## Issue
```
$ curl -sSLO https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py
$ python get-poetry.py -h | grep modify
usage: get-poetry.py [-h] [-p] [--version VERSION] [-f] [--no-modify-path]
  --no-modify-path   do not modify $PATH
$ python get-poetry.py --no-modify-path
Retrieving Poetry metadata

Before we start, please answer the following questions.
You may simply press the Enter key to leave unchanged.
Modify PATH variable? ([y]/n)
```

This prevents the script from being run non-interactively, unless you pipe some text in via stdin (i.e. `echo foo | python get-poetry.py`) which is a hacky workaround.

**Comment by terminalmage** [comment]
I've opened #3704 to fix this.

**Comment by neersighted** [comment]
Closing this as `get-poetry.py` is deprecated and frozen. Please test `install-poetry.py`/`install.python-poetry.org` and create issues for any deficiencies you find.
