### ISSUE TITLE
Poetry fails to install wheel package when needed

### ISSUE THREAD

**Issue by darakian** [python-poetry/poetry#3707]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: MacOS 11.2.1
- **Poetry version**: 1.1.4

## Issue
With new venvs I've been running into issue installing the package `kiwisolver` at version `1.3.1`. Issuing a `poetry install` fails with 
```
error: invalid command 'bdist_wheel'
        ----------------------------------------
        ERROR: Failed building wheel for cppy
      ERROR: Failed to build one or more wheels
      Traceback (most recent call last):
        File "/Users/jon/tmp/venv/lib/python3.9/site-packages/setuptools/installer.py", line 75, in fetch_build_egg
          subprocess.check_call(cmd)
        File "/usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
```

Installing the `wheel` package with `pip install wheel` allows for the install to work. Can functionality be added to poetry to install `wheel` itself if it needs to install a wheel package?

Minimal toml to reproduce
```
[tool.poetry]
name = "foo"
version = "1"
description = ""
authors = [""]

[tool.poetry.dependencies]
python = "^3.8"
kiwisolver = "=1.3.1"
```

**Comment by ryboe** [comment]
This is a dup of #3591. Installing wheels doesn't work on Big Sur. [The fix has already landed on `master`](https://github.com/python-poetry/poetry/pull/3678).

See #3530 for more details.

**Comment by darakian** [comment]
Awesome. I'll close this issue then. Thanks 👍
