### ISSUE TITLE
Poetry does nothing

### ISSUE THREAD

**Issue by facundopadilla** [python-poetry/poetry#3708]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 20.04
- **Poetry version**: 1.1.4
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/facundopadilla/f3f770e0e7680ddc5a7530a016938a6a

## Issue
I was using "poetry" normally but then it stopped working, it does absolutely nothing, I don't understand why if I was using it normally. 

I want to add "python-multipart" but absolutely nothing happens, I tried with "django" but it does nothing either, I run "poetry update" and more than 400 seconds passed without doing anything, it is more explicit in the image, I also run "source $HOME/.poetry/env" and nothing, I'm still in the same, but if I run "poetry run uvicorn my_app.asgi:app --reload", it works without any problem.

![image](https://user-images.githubusercontent.com/64610246/108537644-a013c380-72bc-11eb-9bc7-7fb55273f1bf.png)

**Comment by finswimmer** [comment]
Closing this because we haven't received more information for a long time.

Feel free to leave a comment if you disagree.
