### ISSUE TITLE
Unclear that default setting of virtualenvs.in-project means that venvs are created in cache-dir

### ISSUE THREAD

**Issue by marko-galesic** [python-poetry/poetry#3709]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue
Can something be added to the `virtualenvs.in-project` setting documentation that mentions that without a `.venv` in the project and with the default value of `virtualenvs.in-project` that `poetry install` will create a `venv` under the directory 
 in `cache-dir`?

**Comment by vmorris** [comment]
Wow thank you @tavor ... I was really scratching my head on this one.

Based on the documentation I was expecting `poetry` to create a `.venv` within my project directory if one did not exist. Very confusing!

**Comment by finswimmer** [comment]
Maybe just copy the first sentence from here: https://python-poetry.org/docs/basic-usage/#using-your-virtual-environment to here: https://python-poetry.org/docs/configuration/#virtualenvsin-project-boolean ?

**Comment by Secrus** [comment]
I think adding a short note, about the default path of virtualenvs when `virtualenvs.in-project` is set to false, would be enough. PRs on that are welcome.
