### ISSUE TITLE
Ability to add package to both dependencies and dev-dependencies with different extras.

### ISSUE THREAD

**Issue by MikiGrit** [python-poetry/poetry#3714]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

Hi, it seems to me that currently it is not possible such thing (respective, that `dependencies` takes precedence). Could it be done?

Example `pyproject.toml`:
```
[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
python = "^3.8"
dask = {version = "^2021.1.0", extras = ["distributed"]}

[tool.poetry.dev-dependencies]
dask = {version = "^2021.1.0", extras = ["distributed, diagnostics"]}
```

**Comment by finswimmer** [comment]
Hello @MikiGrit,

this already works. But you have a mistake in your `pyproject.toml`. Each extra must be quoted. So instead of `["distributed, diagnostics"]` it must be `["distributed", "diagnostics"]`.

fin swimmer
