### ISSUE TITLE
Add option to silence poetry but not program in `poetry run`

### ISSUE THREAD

**Issue by pbsds** [python-poetry/poetry#3715]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

When using `poetry run` in a project constrained to an older python version than the one currently activated, poetry prints 3 additional lines to stdout. This can be a problem when the output of the command being run is structured.

Here is an example where a malformed `requirements.txt` gets made:

```sh
$ poetry run pip freeze > requirements.txt
$ head -n3 requirements.txt 
The currently activated Python version 3.9.1 is not supported by the project (~3.7).
Trying to find and use a compatible version. 
Using python3.7 (3.7.7)
```

Poetry does have a `-q` flag which disables all output, but this includes the output of the command being in the environment as well. For this reason i request a flag which either reduces the verbosity of poetry or one just for `poetry run` specifically.

**Comment by drwilly** [comment]
That kind of output belongs to stderr anyways.

**Comment by dimbleby** [comment]
that output now goes to stderr, this can be closed
