### ISSUE TITLE
Add option to make Warnings an error

### ISSUE THREAD

**Issue by awilkins** [python-poetry/poetry#3716]
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

Please provide a way to make warnings an error that terminates execution and returns a nonzero exit code.

Specifically I'm thinking of the warning where your `pyproject.toml` file has been updated but your `poetry.lock` has not - ie when `not locker.is_fresh()`.

This condition should not arise in CI builds where the project and lock file should be compatible. A flag or option to render warnings an error would allow you to enforce this quality constraint.

**Comment by finswimmer** [comment]
Hello @awilkins,

your use case is covered in the current pre-release (1.2.0b1) by `poetry lock --check`.

fin swimmer
