### ISSUE TITLE
"poetry install" returns a zero exit status when build.py failed

### ISSUE THREAD

**Issue by tueda** [python-poetry/poetry#3717]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 18.04.5 LTS / WSL 2
- **Poetry version**: 1.1.4
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/tueda/7d970d66245106352ce56d3f5edb5fc3

## Issue

If I use the "build.py" feature without generating `setup.py` (though it has not been stabilized yet, #2740), namely,
```toml
[tool.poetry.build]
script = "build.py"
generate-setup-file = false
```
then `poetry install` gives a zero exit status even when `build.py` failed:
```
$ cat build.py
raise AssertionError("Failed!")

$ poetry install -vvv; echo $?

...

Installing the current project: example (0.1.0)
  - Building package example in editable mode
  - Executing build script: build.py
Traceback (most recent call last):
  File "/home/tueda/tmp/test-poetry-build-failure/build.py", line 1, in <module>
    raise AssertionError("Failed!")
AssertionError: Failed!
  - Adding example.pth to /home/tueda/tmp/test-poetry-build-failure/.venv/lib/python3.9/site-packages for /home/tueda/tmp/test-poetry-build-failure
  - Removing existing example-0.1.0.dist-info directory from /home/tueda/tmp/test-poetry-build-failure/.venv/lib/python3.9/site-packages
  - Adding the example-0.1.0.dist-info directory to /home/tueda/tmp/test-poetry-build-failure/.venv/lib/python3.9/site-packages
0
```

The same thing occurs even when `build.py` does not exist:
```
$ cat build.py
cat: build.py: No such file or directory

$ poetry install -vvv; echo $?

...

Installing the current project: example (0.1.0)
  - Building package example in editable mode
  - Executing build script: build.py
/home/tueda/tmp/test-poetry-build-failure/.venv/bin/python: can't open file '/home/tueda/tmp/test-poetry-build-failure/build.py': [Errno 2] No such file or directory
  - Adding example.pth to /home/tueda/tmp/test-poetry-build-failure/.venv/lib/python3.9/site-packages for /home/tueda/tmp/test-poetry-build-failure
  - Removing existing example-0.1.0.dist-info directory from /home/tueda/tmp/test-poetry-build-failure/.venv/lib/python3.9/site-packages
  - Adding the example-0.1.0.dist-info directory to /home/tueda/tmp/test-poetry-build-failure/.venv/lib/python3.9/site-packages
0
```

In these cases, Poetry should report a build error with returning a non-zero exit status.

**Comment by logan-bobo** [comment]
Looking over this and in the latest version of poetry (1.2.1) and its looks as if you are correct a failure or the file not existing does not produce an exit code 1 with the following config.

```
[tool.poetry.build]
script = "build.py"
generate-setup-file = false
```
