### ISSUE TITLE
Unable to add dependencies with private extra_requires

### ISSUE THREAD

**Issue by shinybrar** [python-poetry/poetry#3720]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: 
- **Poetry version**: 
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue

I am working on an a project which depends on an open source project, which has an optional private extra. I do not need this private extra install, and nor has it been made publicly available by the project developers. However, I am unable add this project as a dependency, and it causes the following error in poetry:
```
$ poetry add -vvv 'git+https://github.com/chime-experiment/ch_util.git'
```
```
Using virtualenv: /home/trythis/.cache/pypoetry/virtualenvs/thing-3uda7doQ-py3.8

Updating dependencies
Resolving dependencies...
   1: fact: thing is 0.1.0
   1: derived: thing
   1: fact: thing depends on ch-util (20.10.0+35.g6382660 git branch master)
   1: fact: thing depends on pytest (^5.2)
   1: fact: thing depends on pytest (^5.2)
   1: selecting thing (0.1.0)
   1: derived: pytest (^5.2)
   1: derived: ch-util (20.10.0+35.g6382660 git branch master)
PyPI: 15 packages found for pytest >=5.2,<6.0
   1: Version solving took 63.900 seconds.
   1: Tried 1 solutions.

  Stack trace:

  18  ~/.pex/installed_wheels/126dc213d0bf69ccd3cd34ceea39c718e5570c87/clikit-0.6.2-py2.py3-none-any.whl/clikit/console_application.py:131 in run
       129│             parsed_args = resolved_command.args
       130│ 
     → 131│             status_code = command.handle(parsed_args, io)
       132│         except KeyboardInterrupt:
       133│             status_code = 1
[...]
```

The `setup.py` file for the project in question is,
```python
from setuptools import setup, find_packages

import versioneer

ch_util_data = {
    "ch_util": ["catalogs/*.json"],
}

# Load the PEP508 formatted requirements from the requirements.txt file. Needs
# pip version > 19.0
with open("requirements.txt", "r") as fh:
    requires = fh.readlines()

setup(
    name="ch_util",
    version=versioneer.get_version(),
    cmdclass=versioneer.get_cmdclass(),
    packages=find_packages(),
    python_requires=">=3.7",
    install_requires=requires,
    extras_require={
        "chimedb_config": [
            "chimedb.config @ git+ssh://git@github.com/chime-experiment/chimedb_config.git"
        ]
    },
    package_data=ch_util_data,
    # metadata for upload to PyPI
    author="",
    author_email="",
    description="Utilities for CHIME.",
    license="MIT",
    url="",
)
```

I understand, poetry is checking the optional dependencies for version conflicts, but in this case, the optional dependency is not required or needed.

Is this an expected behavior? Or is this a bug with poetry? Is there a way for poetry to ignore this case altogether? Should I work with a solution with developers of project?

Any help would be greatly appreciated.

**Comment by dimbleby** [comment]
Today I can lock `ch-util` just fine, the private extra dependency is recorded in the lockfile, but poetry makes no attempt to install it

Possibly this was never the problem in the first place, OP has omitted the relevant bit of the stack that would have shown this.  Or possibly it has been fixed since then.

All this time later I guess this should just be closed out.
