### ISSUE TITLE
Issue with google-cloud-bigquery

### ISSUE THREAD

**Issue by atellier** [python-poetry/poetry#3721]
Google Cloud BigQuery 2.9.0 fails with Python 3.9.1:

- **OS version and name**: OSX Big Sur
- **Poetry version**: 1.1.4

## Test Project TOML
```
[tool.poetry]
name = "test"
version = "0.1.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "^3.8"
google-cloud-bigquery = "^2.9.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

## Error Message
```
 The current project's Python requirement (>=3.8,<4.0) is not compatible with some of the required packages Python requirement:
    - google-cloud-bigquery requires Python >=3.6, <3.10, so it will not be satisfied for Python >=3.10,<4.0
  
  Because google-cloud-bigquery (2.9.0) requires Python >=3.6, <3.10
   and no versions of google-cloud-bigquery match >2.9.0,<3.0.0, google-cloud-bigquery is forbidden.
  So, because market-making-engine depends on google-cloud-bigquery (^2.9.0), version solving failed.

  at ~/.poetry/lib/poetry/puzzle/solver.py:241 in _solve
      237│             packages = result.packages
      238│         except OverrideNeeded as e:
      239│             return self.solve_in_compatibility_mode(e.overrides, use_latest=use_latest)
      240│         except SolveFailure as e:
    → 241│             raise SolverProblemError(e)
      242│ 
      243│         results = dict(
      244│             depth_first_search(
      245│                 PackageNode(self._package, packages), aggregate_package_nodes

  • Check your dependencies Python requirement: The Python requirement can be specified via the `python` or `markers` properties
    
    For google-cloud-bigquery, a possible solution would be to set the `python` property to ">=3.8,<3.10"
```

Using `">=3.8,<3.10"` for the Python's dependency does solve the issue though.

Thanks

**Comment by apollo13** [comment]
This is not a bug. `python = "^3.8"` allows the range `>=3.8,<4.0` but `google-cloud-bigquery` requires `>=3.6, <3.10`. So all python versions between 3.10 and 4.0 would not be able to install `google-cloud-bigquery`. This is why you need to set a more specific python constraint.

**Comment by yingbo** [comment]
I think it is bug in fact @apollo13 . The `google-cloud-bigquery` requires version range [3.6, 3.10), and 3.8 should be in the range. I feel it's poetry's bug that didn't know "3.8" < "3.10".

**Comment by apollo13** [comment]
No, you wrote ^3.8 which means >=3.8.0,<4.0.0 -- so this would allow for python 3.40 which is outside the range of [3.6, 3.10)

**Comment by yingbo** [comment]
@apollo13 thanks for your quick reply. I just found out why, came back and saw your had commented already! 

You are totally right, the problem is in the TOML file the python version range is larger than the `google-cloud-bigquery` range.

**Comment by Kache** [comment]
@apollo13 Isn't it sufficient for the version ranges to overlap? I wouldn't have thought it's necessary for one version range to be contained within the other.

Why is 3.40 being outside of [3.6, 310) relevant? I would think it'd be sufficient that the current version satisfies all specified version ranges. And if the current version doesn't satisfy but there exists versions that do, poetry could/would suggest them to you.

**Comment by apollo13** [comment]
Because with ^3.8 you are telling poetry that you also want to support installation on a (even if not yet existing) python 3.40. hence poetry tries to generate a lockfile for all the supported python versions and not just the one you are running.

**Comment by brno32** [comment]
Just wanted to say this thread was helpful for me! Thanks for the explanation @apollo13!

**Comment by Haebuk** [comment]
you can resolve this problem simply fixing `python = "^3.8"` to `python = ">=3.8,<3.11"` in pyproject.toml [tool.poetry.dependencies] section. It should works.
