### ISSUE TITLE
ModuleNotFoundError: No module named 'powerline'

### ISSUE THREAD

**Issue by meesha7** [python-poetry/poetry#3726]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Fedora 33
- **Poetry version**: 1.1.4
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: [here](https://gist.github.com/meesha7/1b6e213833ce79aa7a51a2d37942a5aa)

## Issue
Using shell **fish** or **bash** I jump into the venv (`poetry shell`) and then try to run `vi .gitignore`, the following message is displayed:

```
Traceback (most recent call last):
  File "<string>", line 4, in <module>
ModuleNotFoundError: No module named 'powerline'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<string>", line 9, in <module>
ModuleNotFoundError: No module named 'powerline'
An error occurred while importing powerline module.
This could be caused by invalid sys.path setting,
or by an incompatible Python version (powerline requires
Python 2.6, 2.7 or 3.2 and later to work). Please consult
the troubleshooting section in the documentation for
possible solutions.
Unable to import powerline, is it installed?
Press ENTER or type command to continue
```
`powerline` module is not installed. This doesn't happen with `pipenv` or outside the venv.
What is poetry trying to do? Why doesn't it install `powerline` when running `pip install --user poetry`?

**Comment by stephsamson** [comment]
I don't see `powerline` as a dependency in the `pyproject.toml` you've provided. How did you install `poetry`?

**Comment by meesha7** [comment]
Installed by `pip3 install --user poetry`. I can see a package `vim-powerline` installed on my system, though I haven't configured it in any way and I don't know if they're related. But this issue happens with `vi` and not for example with `nano`.

**Comment by abn** [comment]
The issue here is vi loads your user config and any plugins, which I presume might have powerline enabled. This requires the powerline python package to be present in the sys path. 

When poetry spawns a shell, the sys path only contains the project's virtual environment. Which does not contain the powerline package, thereby causing the error you are seeing when vi tried to load it.

**Comment by abn** [comment]
Related: https://github.com/powerline/powerline/issues/1908

**Comment by meesha7** [comment]
Thank you @abn, I have no idea why I had that package on my system and why the config defaulted to what caused this issues for me. After removing the package, I no longer get that error. I'll try to fix the config, but good to know that the issues is on my end!

**Comment by firsthubgit** [comment]
https://jugmac00.github.io/blog/sudo-dnf-install-beautiful-problems/

`python3 import sys;sys.path.append("/usr/lib/python3.6/site-packages/")
`

**Comment by rakeshgm** [comment]
Still seeing the error in fedora 37, modified the above line like this and added in `~/.vimrc`
```
python3 <<EOF
import sys; sys.path.append("/usr/lib/python3.11/site-packages/")
EOF
```
I believe this would be less error-prone. One needs to source vimrc file: `source ~/.vimrc`

**Comment by staticf0x** [comment]
@rakeshgm Wouldn't extending the `PYTHONPATH` env variable work as well? In your `.bashrc` (or similar for other shells)?

**Comment by rakeshgm** [comment]
@staticf0x Well, I tried that too, but somehow the PYTHONPATH gets reset in virtualenv. the above code worked and I just left it there. :)
