### ISSUE TITLE
Documented options for "poetry add" do not match actual options

### ISSUE THREAD

**Issue by emddudley** [python-poetry/poetry#3728]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue
The documented options for `poetry add` [on the website](https://python-poetry.org/docs/cli/#options_3) do not match the [actual options](https://github.com/python-poetry/poetry/blob/1.1/poetry/console/commands/add.py#L18) available in Poetry 1.1.4.

The `--path` option is documented on the website but does not seem to exist.

The following options exist but are not listed in the website documentation:

- `--extras`
- `--python`
- `--platform`
- `--source`
- `--allow-prereleases`

Also, as a side note, I would like to say that I am using Poetry for the first time and I am extremely pleased with it. I am grateful that it is so easy to add dependencies from a local file paths. I am developing software with a 10+ year lifespan and I wanted to vendor my dependency wheels. Poetry seems to support that no problem.

**Comment by emddudley** [comment]
Seems like it was already patched?
https://github.com/python-poetry/poetry/commit/e36fb739ee7be9748e1176bd10030760473e880c

So maybe the website just needs the latest docs to be uploaded?

**Comment by finswimmer** [comment]
Yes, this is already in master, but not on the website itself.
