### ISSUE TITLE
Poetry "depends on" debug regex fails to match if dependancy has missing version info

### ISSUE THREAD

**Issue by joshuakraitberg** [python-poetry/poetry#3729]
Happens with `poetry update -vv`, workaround is to just do `poetry update`.

https://github.com/python-poetry/poetry/blob/8312e3f2dbfa126cd311c666fea30656941e1bd3/poetry/puzzle/provider.py#L692-L699

If `message == "fact: xxx (==1.7.0) depends on cryptography"` you'll end up with `m == None` and an `AttributeError` on the next line.

**Comment by dimbleby** [comment]
I don't know in what circumstances the version info would be missing. 

But that this has had no further interest in the last 18 months or so hints that it is either already fixed, or so rare that no-one is hitting it.

Suggest closing this and associated MR.

**Comment by Secrus** [comment]
Closing for reasons mentioned above. Also, no other reports on this were filed. If you stumble over this bug, feel free to open a new issue.
