### ISSUE TITLE
`poetry/__init__.py` is provided by both poetry and poetry-core

### ISSUE THREAD

**Issue by nchepanov** [python-poetry/poetry#3735]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: N/A
- **Poetry version**: 1.1.4
- **Poetry-core version**: 1.0.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: N.A.

## Issue

It appears that both `poetry-core-1.0.2.tar.gz` and `poetry-1.1.4.tar.gz` attempt to install `poetry/__init__.py`. 

While this may not be a problem now, since `pip` will silently overwrite one file with another https://github.com/pypa/pip/issues/4625

It does become a problem when the two are repackaged via a more strict package management system, e.g. in our internal debian distribution both binary packages would contain `$prefix/lib/python3.9/site-packages/poetry/__init__.py`. Consequently, they cannot be installed with something like `apt-get install`: 

```
.$prefix/lib/python3.9/site-packages/poetry/__init__.py duplicated when installing python3.9-poetry and python3.9-poetry-core.
```

It appears that this can be solved by treating `poetry/` as   [PEP420](https://www.python.org/dev/peps/pep-0420/) implicit namespace by removing `__init__.py` from both the `poetry` and `poetry.core` packages.

This can be done without affecting any users. I'm happy to submit a PR if needed.

**Comment by finswimmer** [comment]
Hello @nchepanov,

the current version of poetry support python2 and python3. Namespace packages were introduced somewhere in python3. This is why we need to use [pkgutil-style namespace packages](https://packaging.python.org/guides/packaging-namespace-packages/#pkgutil-style-namespace-packages).

With the next minor release (1.2), we are dropping python2 support. So I guess we can switch to real namespace packages then.

fin swimmer

**Comment by neersighted** [comment]
Hi @nchepanov, would you like to create that PR you mentioned? `master` is now the head for 1.2 and can drop Python 2 support. Note you'll also need to submit a PR to poetry-core (but you likely already realized that).

**Comment by nchepanov** [comment]
Hi @neersighted I'm afraid I'm not going to have time for this in the near future, thank you for asking!
FYI: @mariocj89 @godlygeek

**Comment by neersighted** [comment]
Closing this for now as the immediate issue (the collision) is solved by poetry-core moving to an implicit namespace package. Whether or not Poetry does the same is immaterial to this issue.
