### ISSUE TITLE
poetry install not removing previous version of package under development

### ISSUE THREAD

**Issue by ns-admetrics** [python-poetry/poetry#3741]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

- **OS version and name**: Arch Linux
- **Poetry version**: 1.1.4
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://github.com/ns-admetrics/poetry-version-bumping/blob/main/pyproject.toml
- System Python: 3.9
- poetry env Python versions 3.7 (main), 3.8, 3.9

## Issue
When I bump the version of the package I'm developing (e.g. with `python version minor`), and run `poetry install`, then I end up with multiple versions of it in `$(poetry env info -p)/lib/python3.7/site-packages`, e.g.

```
mypackage.pth
mypackage-0.1.0a1.dist-info
mypackage-0.1.0a2.dist-info
mypackage-0.1.0.dist-info
mypackage-0.2.0.dist-info
```

My expectation is that `poetry install` would declaratively install the version that is currently defined in `pyproject.toml`, and remove other versions.

Is this expectation incorrect? I don't see a `poetry clean` type command; maybe there is another intended way to bump versions.

Here's a setup that reproduces (not quite portable): https://github.com/ns-admetrics/poetry-version-bumping/blob/main/playbook.sh

<sub>
For prereleases at least (0.1.0-alpha.N), it seems a bit undeterministic what is seen as "the installed package version" then, e.g. what `pip uninstall mypackage` removes, but also the [recommended approach](https://github.com/python-poetry/poetry/pull/2366#issuecomment-652418094) to deal with `__version__` redundancy breaks. This latter might be an upstream bug in `importlib_metadata`; when there's 0.1.0a1, 0.1.0a2 and 0.1.0, then 0.1.0a1 is picked -- mentioning only for context.
</sub>

**Comment by finswimmer** [comment]
I guess this a duplicate of https://github.com/python-poetry/poetry/issues/2855, is it?

**Comment by ns-admetrics** [comment]
Right, my issue search foo failed me, apologies.
