### ISSUE TITLE
Poetry version command should manage versions closer to whats outlined in PEP440.

### ISSUE THREAD

**Issue by shadycuz** [python-poetry/poetry#3752]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

Poetry doesn't seem to have the ability to manage versions according to [PEP440](https://www.python.org/dev/peps/pep-0440/).

Lets look at an example from PEP440:

```
0.9
1.0a1
1.0a2
1.0b1
1.0rc1
1.0
1.1a1
```

Lets try and replicate this with poetry:

```bash
shadycuz-> poetry version -s
0.9

shadycuz-> poetry version premajor
Bumping version from 0.9 to 1.0.0-alpha.0  # So far so good

shadycuz-> poetry version prerelease
Bumping version from 1.0.0-alpha.0 to 1.0.0-alpha.1 # This is nice...

shadycuz-> poetry version prerelease
Bumping version from 1.0.0-alpha.1 to 1.0.0-alpha.2

shadycuz-> poetry version prerelease
Bumping version from 1.0.0-alpha.2 to 1.0.0-alpha.3

shadycuz-> poetry version prerelease
Bumping version from 1.0.0-alpha.3 to 1.0.0-alpha.4

# ugh how do I remove the alpha to get back to 1.0.0?
```

So it turns out you can remove the alpha but it didn't make sense to me. 

```bash
shadycuz-> poetry version major
Bumping version from 1.0.0-alpha.4 to 1.0.0
```

Wait what?  Since `premajor` went from `0.9` to `1.0.0-alpha.0` I was expecting `major` to go from `1.0.0-alpha.4` to `2.0.0`. 

Here is some other odd behavior:
```bash
shadycuz-> poetry version -s 
1.1.0

shadycuz-> poetry version prerelease
Bumping version from 1.1.0 to 1.1.1-alpha.0
```

So `prerelease` does a patch bump automatically. Even though we already have `prepatch`. 

> Explicit is better than implicit.

Something something zen of python.

What I would recommend is that `prerelease` handle changing a non-prerelease version into a prerelease version and bumping `alpha.N`.  It should throw an error if you try to `prerelease` on a version that is already a pre-release. We should also add a `release` bump rule that turns a pre-release into a normal version and throws an error if you try to "release" a release version. 

This simple change in behavior would allow me to manage versions of my python package according to the examples in PEP440 with Poetry. It will also make my CICD pipeline so much simpler. I'm also wanting to contribute the PR to implement this feature if this is something Poetry maintainers would like to see added.

**Comment by Aloisius** [comment]
I must be missing something because it looks like it is doing the correct thing to me.

If you're at 0.9, `premajor` gives the next possible premajor version which is 1.0.0-alpha.0.

If you're at 1.0.0-alpha.4, `major` gives the next possible final release major version, which is 1.0.0. It isn't 2.0.0 because >=1.0.0 hasn't been released yet. 1.0.0-alpha.4 is < 1.0.0 according to PEP440.

If you're at 1.1.0, `prerelease` gives you the next possible prerelease possible which is 1.1.1-alpha0. Well, technically according to PEP440, it 

It looks PEP440 compliant to me, though it is lacking release-candidate, post-release, developmental release commands. I'd like the developmental release one for CI purposes.

**Comment by dimbleby** [comment]
All the examples in this bug report looks good to me too, suggest this should be closed.

(which is not to say that `poetry version` is perfect eg #879 looks to have some valid concerns)

**Comment by shadycuz** [comment]
@neersighted I just realized I was the first to ask for PEP440 tags and now I'm the first to ask to switch back 😊
