### ISSUE TITLE
Issue when using build

### ISSUE THREAD

**Issue by galleon** [python-poetry/poetry#3753]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS Catalina 10.15.7
- **Poetry version**: Poetry version 1.1.5
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/galleon/a514a509878fdec1a953885a8470d5b0

## Issue
> `poetry install` runs fine locally
but when I run `python -m build --sdist --wheel` to test the  generation of my artifacts (without poetry)
I have the following error message
```
/Users/alleon_g/Documents/0x-TechWork/scikit-decide/tmp/galleon/scikit-decide/.build/lib/python3.8/site-packages/setuptools/distutils_patch.py:25: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
  warnings.warn(```

According to build discord channel this is a poetry issue.

**Comment by abn** [comment]
Looks like the issue here is caused by the following section as the build script gets executed.

https://github.com/galleon/scikit-decide/blob/309abe2fcfad760e1d206389917fa8f906511b01/builder.py#L12-L16

This does not seem to be a poetry issue. Additionally, the logs indicate a `UserWarning` not an error.
