### ISSUE TITLE
Issue: Building wheel for pikepdf (PEP 517) - Unknown distribution option: 'cmd_class'

### ISSUE THREAD

**Issue by joeld1** [python-poetry/poetry#3762]
- [x ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [ ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS Big Sur - Apple M1
- **Poetry version**: 1.15
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/20f77a7881f974e86c580f3446e34683

## Issue
I'm having difficulties installing `ocrmypdf`, which depends on `pikepdf`, which depends on a built version of `qpdf`.

I've updated `pip`, `setuptools`, `poetry`, `pyenv`, and added the following environmental variables:

`export SYSTEM_VERSION_COMPAT=1`

`export LDFLAGS="-L$(brew --prefix openssl@1.1)/lib"`
`export CPPFLAGS="-I$(brew --prefix openssl@1.1)/include"`
`export PKG_CONFIG_PATH="$(brew --prefix openssl@1.1)/lib/pkgconfig"`

and have also tried

`export LDFLAGS="-L/opt/homebrew/opt/openblas/lib"`
`export CPPFLAGS="-I/opt/homebrew/opt/openblas/include"`
`export PKG_CONFIG_PATH="/opt/homebrew/opt/openblas/lib/pkgconfig"`

I'm not so sure what to do next. I'm interested in using Poetry to install this package, so any help or guidance would truly be appreciate.

Thank you!

EDIT: Added OS Version & Name

**Comment by joeld1** [comment]
A link to the output of the installation is found on my gist [here](https://gist.github.com/fe640696fb113c71a95b8df3f3826a77)

**Comment by abn** [comment]
@joeld1 I tried to reproduce the issue. Could not do so. 

```sh
podman run --rm -i --entrypoint bash python:3.9 <<EOF
set -xe
python -m pip install -q poetry
install -d foobar
pushd foobar
curl -sL --output pyproject.toml https://gist.githubusercontent.com/joeld1/20f77a7881f974e86c580f3446e34683/raw/78dedb5fd7c448a5d11544dc12c47138aad4cbed/pyproject.toml
poetry install
poetry add ocrmypdf
EOF
```

**Output:**
```console
+ poetry install
Creating virtualenv code-to-share-lWDpn5M1-py3.9 in /root/.cache/pypoetry/virtualenvs
Updating dependencies
Resolving dependencies...

Writing lock file

Package operations: 30 installs, 0 updates, 0 removals

  • Installing h11 (0.12.0)
<snipped>
  • Installing uvicorn (0.13.4)
+ poetry add ocrmypdf
Using version ^11.7.3 for ocrmypdf

Updating dependencies
Resolving dependencies...

Writing lock file

Package operations: 14 installs, 0 updates, 0 removals

  • Installing pycparser (2.20)
  • Installing cffi (1.14.5)
  • Installing lxml (4.6.3)
  • Installing pillow (8.1.2)
  • Installing cryptography (3.4.6)
  • Installing humanfriendly (9.1)
  • Installing pikepdf (2.9.1)
  • Installing sortedcontainers (2.3.0)
  • Installing coloredlogs (15.0)
  • Installing img2pdf (0.4.0)
  • Installing pdfminer.six (20201018)
  • Installing reportlab (3.5.66)
  • Installing tqdm (4.59.0)
  • Installing ocrmypdf (11.7.3)
```

**Comment by abn** [comment]
Forcing a no-binary build seems to have triggered the issue in the container. You can try this outside of poetry to see if you can even build the wheel.

```sh
pip wheel --no-deps --no-binary :all: pikepdf
```

**Comment by abn** [comment]
Looks like the issue is in the source itself.

```console
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/tmp/pip-build-env-alo5f4l4/overlay/lib/python3.9/site-packages/pybind11/include -I/usr/local/include/python3.9 -c src/qpdf/qpdf.cpp -o build/temp.linux-x86_64-3.9/src/qpdf/qpdf.o -fvisibility=hidden -g0 -std=c++14
  src/qpdf/annotation.cpp:11:10: fatal error: qpdf/Constants.h: No such file or directory
   #include <qpdf/Constants.h>
            ^~~~~~~~~~~~~~~~~~
  compilation terminated.
```

```console
root@1d6543b04782:/tmp# curl -sSL https://files.pythonhosted.org/packages/c6/7c/521a6920d5373c1fb8bfe8077162184b9c2b3d9ee2e20d4b47bc9cc3da55/pikepdf-2.9.1.tar.gz | tar -ztvf - pikepdf-2.9.1/src/qpdf/
drwxr-xr-x runner/docker     0 2021-03-20 07:38 pikepdf-2.9.1/src/qpdf/
-rw-r--r-- runner/docker  2047 2021-03-20 07:35 pikepdf-2.9.1/src/qpdf/annotation.cpp
-rw-r--r-- runner/docker  1807 2021-03-20 07:35 pikepdf-2.9.1/src/qpdf/gsl.h
-rw-r--r-- runner/docker  4558 2021-03-20 07:35 pikepdf-2.9.1/src/qpdf/mmap_inputsource.h
-rw-r--r-- runner/docker 34906 2021-03-20 07:35 pikepdf-2.9.1/src/qpdf/object.cpp
-rw-r--r-- runner/docker  5435 2021-03-20 07:35 pikepdf-2.9.1/src/qpdf/object_convert.cpp
-rw-r--r-- runner/docker  4391 2021-03-20 07:35 pikepdf-2.9.1/src/qpdf/object_parsers.h
-rw-r--r-- runner/docker  7912 2021-03-20 07:35 pikepdf-2.9.1/src/qpdf/object_repr.cpp
-rw-r--r-- runner/docker 15564 2021-03-20 07:35 pikepdf-2.9.1/src/qpdf/page.cpp
-rw-r--r-- runner/docker  5851 2021-03-20 07:35 pikepdf-2.9.1/src/qpdf/pikepdf.cpp
-rw-r--r-- runner/docker  7087 2021-03-20 07:35 pikepdf-2.9.1/src/qpdf/pikepdf.h
-rw-r--r-- runner/docker  1599 2021-03-20 07:35 pikepdf-2.9.1/src/qpdf/pipeline.cpp
-rw-r--r-- runner/docker  1239 2021-03-20 07:35 pikepdf-2.9.1/src/qpdf/pipeline.h
-rw-r--r-- runner/docker 32105 2021-03-20 07:35 pikepdf-2.9.1/src/qpdf/qpdf.cpp
-rw-r--r-- runner/docker  4924 2021-03-20 07:35 pikepdf-2.9.1/src/qpdf/qpdf_inputsource.h
-rw-r--r-- runner/docker 11639 2021-03-20 07:35 pikepdf-2.9.1/src/qpdf/qpdf_pagelist.cpp
-rw-r--r-- runner/docker  1092 2021-03-20 07:35 pikepdf-2.9.1/src/qpdf/qpdf_pagelist.h
-rw-r--r-- runner/docker  1012 2021-03-20 07:35 pikepdf-2.9.1/src/qpdf/utils.cpp
-rw-r--r-- runner/docker   504 2021-03-20 07:35 pikepdf-2.9.1/src/qpdf/utils.h
```

**Comment by joeld1** [comment]
Hi @abn , thanks for taking a look at this! I wasn't so sure whether it was Poetry or a dependency. One thing I forgot to mention is that I'm running Poetry on macOS Big Sur (M1 Chip). Many packages aren't easily available for the M1 computers, but I've figured out that most of my dependency issues are resolved if I use a Conda virtual environment instead of a .venv environment created by Poetry. I created a [small script](https://gist.github.com/joeld1/c48fda0c312e1ae0715b73877d50f131) to create these environments for me.

By specifying a `Conda` env, I'm able to add `ocrmypdf` to the poetry project without a problem. I do run into a `$PATH` issue for `leptonica` but that's something I have to troubleshoot separately; however, this issue goes away if I perform a `conda install` instead of a `poetry add`. It's not ideal, but it's a fallback when I can't add packages on my Mac M1. 

Anyhow, thanks again for taking a look at this, and thanks again for poetry - it's amazing!

 Please feel free to close this ticket!
