### ISSUE TITLE
`poetry update --dry-run` modifies poetry.lock

### ISSUE THREAD

**Issue by martinmo** [python-poetry/poetry#3766]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS 10.15.7
- **Poetry version**: 1.1.5
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/martinmo/bf32a5e6278f9edc74eb3f7787e5b372

## Issue

When `poetry update` is called with the `--dry-run` argument, the expected outcome is that the file `poetry.lock` remains unmodified.

However, a regression introduced in poetry version 1.1.1 (it seems, via PR #3034) modifies this file regardless of the `--dry-run` flag.

To reproduce using the above gist:

```
$ git clone https://gist.github.com/bf32a5e6278f9edc74eb3f7787e5b372.git poetry-bug && cd poetry-bug
$ poetry -V
Poetry version 1.1.5
$ poetry config --list
cache-dir = "/Users/martin/Library/Caches/pypoetry"
experimental.new-installer = false
installer.parallel = false
virtualenvs.create = true
virtualenvs.in-project = true
virtualenvs.path = "{cache-dir}/virtualenvs"  # /Users/martin/Library/Caches/pypoetry/virtualenvs
$ poetry update --dry-run
Updating dependencies
Resolving dependencies... (0.1s)

Writing lock file

Package operations: 1 install, 0 updates, 0 removals

  - Installing defusedxml (0.7.1)
$ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   poetry.lock

no changes added to commit (use "git add" and/or "git commit -a")
```

With poetry 1.1.0, it works as expected:

```
$ git checkout poetry.lock
$ pipx install --suffix @1.1.0 'poetry==1.1.0'
$ poetry@1.1.0 -V
Poetry version 1.1.0
$ poetry@1.1.0 update --dry-run
Updating dependencies
Resolving dependencies... (0.1s)

Package operations: 1 install, 0 updates, 0 removals

  - Installing defusedxml (0.7.1)
$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

As of now, poetry's `master` is also affected. It happens regardless of the `experimental.new-installer` and `installer.parallel` settings.

I have already written a unit test to reproduce this and an according fix that I'll submit as a PR in a minute.

**Comment by justinmayer** [comment]
See also: #3739 #3666

**Comment by languitar** [comment]
This is highly annoying in case of merge conflicts in the lock file. Using `poetry lock --no-update` would be one version to resolve the conflicts, but implicitly changing versions with this command might trigger a cascade of further errors.

**Comment by brettborowski** [comment]
Does this also affect `poetry add --dry-run` as well?

**Comment by martinmo** [comment]
Yes, I would think so, because in addition to the `update` command it was also reported that the `remove` and `lock` commands are affected. This makes sense, as the function `_write_lock_file(…)` in [poetry/installation/installer.py#L335](https://github.com/python-poetry/poetry/blob/master/poetry/installation/installer.py#L335) sets `force` to `True` by default and modifies the lockfile if `force` is `True`. This is what I've changed in my PR (see above).

**Comment by zEdS15B3GCwq** [comment]
Still present in 1.2.0b1. Please proceed with PR. Much appreciated.
