### ISSUE TITLE
Failed to install poetry into /usr/local via installer

### ISSUE THREAD

**Issue by squirrel532** [python-poetry/poetry#3770]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: 
- **Poetry version**: 
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue

Failed to install poetry at `/usr/local`, and I saw the installer checks `POETRY_LIB` instead of `POETRY_LIB/poetry/__version__.py` before reading the current version.
```
root@907d114df4d9:/# POETRY_HOME=/usr/local /usr/bin/python3 get-poetry.py
Traceback (most recent call last):
  File "get-poetry.py", line 1086, in <module>
    sys.exit(main())
  File "get-poetry.py", line 1082, in main
    return installer.run()
  File "get-poetry.py", line 352, in run
    version, current_version = self.get_version()
  File "get-poetry.py", line 387, in get_version
    with open(
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/poetry/__version__.py'
```

**Comment by dimbleby** [comment]
get-poetry is deprecated, no point in leaving this open
