### ISSUE TITLE
Local path dependencies are not updated when code is updated

### ISSUE THREAD

**Issue by felixgao** [python-poetry/poetry#3775]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: OSX 10.15.7
- **Poetry version**: 1.1.5
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 
https://gist.github.com/felixgao/55328920933bb4ca8cbbd43d8a89f8f1

I am trying to create a monorepo for my project.  the code in the libs are added as path dependencies of the project.  However the updates to the library seems are not updated in the projects.

for example, in my deco module at `libs/deco` I have a piece of code as 
```
def test():
    from loguru import logger
    logger.info("hello from deco")
    print("Done")
```
then went to my `projects/project-one` directory after `poetry install` the depdency is added into my venv when run
> poetry run python -m project_two
```
2021-03-11 14:37:59.466 | INFO     | deco.main:test:55 - hello from deco
Done
test executed in 0.0169 seconds
```
which is expected.  Then I updated the code in `test()` to 
```
def test():
    from loguru import logger
    logger.info("hello from deco".upper())
    print("Done")
```
In `projects/project-one` I did `poetry update` then `poetry run python -m project_two` still getting the same output.
```
2021-03-11 15:18:38.621 | INFO     | deco.main:test:55 - hello from deco
Done
test executed in 0.0273 seconds
```

This is unexpected. I am wondering what is the correct way to reference path dependencies and have the code updated once modified.

**Comment by finswimmer** [comment]
Hello @felixgao,

since poetry 1.1 path dependencies are no longer installed in editable mode by default. (https://python-poetry.org/docs/dependency-specification/#path-dependencies). You have to set the `develop` flag to `true`manually:

```
deco = {path = "../../libs/deco", develop = true}
```

fin swimmer
