### ISSUE TITLE
Git fetch

### ISSUE THREAD

**Issue by ArthurTlprt** [python-poetry/poetry#3777]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request
I'm trying to fix the following issue on Poetry:  https://github.com/python-poetry/poetry/issues/2921

And I'm wondering if there is a way to check if a git dependency needs to be updated whithout cloning it beforehand.
From what I have seen, there is no git fetch implemented in poetry-core.

Is it needed in my case?

Thanks

**Comment by finswimmer** [comment]
#2921 is fixed. So I guess we can close this issue as well.
