### ISSUE TITLE
Failing to install tensorflow==2.x

### ISSUE THREAD

**Issue by Mahelita** [python-poetry/poetry#3778]
- [X ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
```
> poetry --version
Poetry version 1.1.5
```
- [X ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
There are many issues with installation of tensorflow but no solution seems to fit
- [X ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).
```
  Installing collected packages: tensorflow
  ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: 'C:\\Users\\***********\\Lib\\site-packages\\tensorflow\\include\\external\\llvm-project\\mlir\\_virtual_includes\\AffineMemoryOpInterfacesIncGen\\mlir\\Dialect\\Affine\\IR\\AffineMemoryOpInterfaces.cpp.inc'



  at ~\.poetry\lib\poetry\utils\env.py:1074 in _run
      1070│                 output = subprocess.check_output(
      1071│                     cmd, stderr=subprocess.STDOUT, **kwargs
      1072│                 )
      1073│         except CalledProcessError as e:
    → 1074│             raise EnvCommandError(e, input=input_)
      1075│
      1076│         return decode(output)
      1077│
      1078│     def execute(self, bin, *args, **kwargs):


Failed to add packages, reverting the pyproject.toml file to its original content.
```
The file is indeed not present: (unable to upload screenshot)

- **OS version and name**: Windows 10, powershell
- **Poetry version**: 1.1.5

## Issue
I tried to `poetry add tensorflow==`2.1.0, 2.3.1 and 2.4.1 with python 3.7 and 3.8 but always get missing files during the installation. 
My pip version is 
```
>pip --version
pip 21.0.1 
```
tensorflow 2.4.1 requires:
  * Python 3.5–3.8
    * Python 3.8 support requires TensorFlow 2.2 or later.
  * pip 19.0 or later (requires manylinux2010 support)
  * Windows 7 or later (64-bit)
    * Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019

Previously I had the same problem with conda, using an incompatible python version (3.8 with version 2.1.0). With poetry, downgrading to python 3.7, which solved the problem with conda, does not solve it.
Am I missing something?
Thanks!

**Comment by matteosantama** [comment]
Try to run it again, I've had `ERROR: Could not install packages due to an OSError` pop up before, and re-running the command usually fixes it. Seems like there's a race condition somewhere.

**Comment by Mahelita** [comment]
Turns out I had a Windows long path problem...
Moving the poetry env cache to C: solves it:
e.g., `poetry config virtualenvs.path C:\envs`
