### ISSUE TITLE
Set prefered python version on pyprpject.toml

### ISSUE THREAD

**Issue by ericriff** [python-poetry/poetry#3782]
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Issue
We have a Linux dev environment where python 3.5, 3.6 and 3.7 are installed. We have our `pyproject.toml` set to match that
```
[tool.poetry.dependencies] 
python = ">=3.5 <3.8"
```

This means that developers can choose which version to use by doing
`poetry env use 3.x`
Which is extremely convenient.

Now we're trying to push devs to use 3.7 so we can remove support for older versions. Is there a way to set a "preference" for a given python version?
The easy solution would be to make our `pyproject.toml` allow only 3.7, but that would remove the possibility of using `poetry env use 3.x` to change the version used.

```
[tool.poetry.dependencies] 
python = "3.7"
```

Thanks!

**Comment by n8sty** [comment]
This doesn't seem like a great feature for Poetry to support, but you can probably achieve it using a tool like `pyenv` or `asdf`. I use `asdf`, which creates a `.tool-versions` file that can look like
```
python 3.8.6 3.9.2
nodejs 14.15.5
```

`pyenv` has similar functionality.

**Comment by finswimmer** [comment]
This is out of scope for poetry. If the package aims to be compatible for a certain python range, it doesn't matter which version is used exactly during development.
