### ISSUE TITLE
Notebooks/script don't recognize project package

### ISSUE THREAD

**Issue by jralfonsog** [python-poetry/poetry#3787]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Linux Mint 19.3
- **Poetry version**: 1.1.5 
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: [Link](https://gist.github.com/jralfonsog/22cdd5feeb3f7ca7e4ecd3a65edb17bf)

## Issue

Hello there.

I'm trying to use my project package from notebooks or some scripts placed outside of the source code folder. My project structure is the following:

├── notebooks
│   └── Untitled.ipynb
├── poetry.lock
├── pyproject.toml
├── scripts
│   ├── __init__.py
│   └── hello.py
├── source
│   ├── __init__.py
│   └── utils.py
├── tests
│   └── __init__.py
└── zip_project.py

After running `poetry install`, If I try to import anything from `source`, whether it's from the notebook or from that `hello.py` script, it can't find the source module. It works if I do `poetry run python scripts/hello.py`, but it shouldn't be the solution as it would still not work for the notebooks. I use pyenv for python version management, in case it is relevant.

I'm pretty sure I've done this before, but I don't know if there's something I'm doing wrong.

**Comment by jralfonsog** [comment]
After checking out [this](https://python-poetry.org/docs/cli/#add), I've tried to run "poetry add ./source/", but got the following error:

>   TypeError
> 
>   expected string or bytes-like object
> 
>   at ~/.poetry/lib/poetry/_vendor/py3.7/poetry/core/utils/helpers.py:27 in canonicalize_name
>        23│ _canonicalize_regex = re.compile(r"[-_]+")
>        24│ 
>        25│ 
>        26│ def canonicalize_name(name):  # type: (str) -> str
>     →  27│     return _canonicalize_regex.sub("-", name).lower()
>        28│ 
>        29│ 
>        30│ def module_name(name):  # type: (str) -> str
>        31│     return canonicalize_name(name).replace(".", "_").replace("-", "_")
>

**Comment by stephsamson** [comment]
If `init.py` is supposed to be `__init__.py` then that's no longer necessary in Python 3. You can check the [docs](https://python-poetry.org/docs/pyproject/#packages) on how Poetry can find your non-standard modules. Also you need to replace the underscores in your pyproject.toml to dashes (click [here](https://gist.github.com/jralfonsog/22cdd5feeb3f7ca7e4ecd3a65edb17bf#file-pyproject-toml-L2) to see what I'm referring to).

**Comment by jralfonsog** [comment]
Hi, @stephsamson, and thanks for your help.

After checking again the docs, and trying my best, I keep getting a "Directory {} does not seem to be a Python package" message every time I try to run `poetry update`.

The structure is now this one:

_____zip_project.py
|____source
| |____utils.py
|____pyproject.toml
|____tests
|____models
| |____mlruns.db
|____scripts
| |____hello.py
|____poetry.lock
|____notebooks
| |____Untitled.ipynb

The last `pyproject.toml` is in the [updated gist](https://gist.github.com/jralfonsog/22cdd5feeb3f7ca7e4ecd3a65edb17bf).

I've tried with or without `__init__` files. I've checked with a package named `mlflow_sqlite_template` as well, without luck.
