### ISSUE TITLE
entry_points.txt not generated for entry point

### ISSUE THREAD

**Issue by volkerjaenisch** [python-poetry/poetry#3793]
- [x ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **Debian Buster**: 
- **Poetry 1.1.5**: 
- **https://gist.github.com/volkerjaenisch/259be02cd765d89e8280e7e1b5a2d16e**: 

## Issue
To reproduce:

```
$ poetry --version
Poetry version 1.1.5
$ poetry new noplugin
$ cd noplugin
$ poetry install

$ poetry shell

(noplugins-crV9IH3A-py3.7) volker@debian10:~/noplugins$ ls -al /home/volker/.cache/pypoetry/virtualenvs/noplugins-crV9IH3A-py3.7/lib/python3.7/site-packages/noplugins-0.1.0.dist-info
insgesamt 20
drwxr-xr-x  2 volker volker 4096 Mär 16 23:23 .
drwxr-xr-x 32 volker volker 4096 Mär 16 23:23 ..
-rw-r--r--  1 volker volker    6 Mär 16 23:23 INSTALLER
-rw-r--r--  1 volker volker  337 Mär 16 23:23 METADATA
-rw-r--r--  1 volker volker  658 Mär 16 23:23 RECORD
```

so far so good.

Then change the pyproject.toml file to

```
[tool.poetry]
name = "noplugin"
version = "0.1.0"
description = ""
authors = ["volker <volker.jaenisch@inqbus.de>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."noplugin_group"]
no_plugin = "noplugin.nopluginlib:NoPlugin"
```

and did

`$ poetry update
`
Expected behavior: 
  A file 'entry_points.txt' should be created in the sitepackages dir of the module

Observed behavior:
  No file 'entry_points.txt' is created in the sitepackages dir of the module

I checked this on my dev system. Then to make sure that I do not have any glitches I fired up a brand new debian buster VM - same behavior.

Any help appreciated, probably I did something wrong or stupid.

Cheers,

Volker

**Comment by mgjo5899** [comment]
Have you tried matching your `tool.poetry.name` with your source directory you are trying to refer to? Is `noplugin` folder in the root of project? So if the name of the project is `noplugin`, `noplugin/noplugin/nopluginlib` should be a valid directory, I think.

**Comment by finswimmer** [comment]
The metadata of the current project is only updated on `poetry install`. A `poetry update` updates the dependencies of the project within the given ranges.

So whenever you change metadata (scripts and plugins belong to them) run `poetry install` afterwards.

**Comment by neersighted** [comment]
Related: #6639
