### ISSUE TITLE
Change default branch to main

### ISSUE THREAD

**Issue by michalszelagsonos** [python-poetry/poetry#3796]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Issue
The world is moving on from `master` as default main branch for a project, since it is now increasingly considered offensive.  Many big projects have now converted to using `main` and I'd like to request that we do the same for poetry.  GitHub offers tooling to make this transition smoother:

https://github.com/github/renaming

Please consider making the change to `main` since it is now the defacto standard.

**Comment by mkniewallner** [comment]
While I personally think that this would be great (we did that for other projects in the organization, after all), we need to make sure that renaming the branch won't break the workflows of users relying on the branch name in scripts.

From https://github.com/github/renaming, there may be some things done GitHub side to help on that, but we need to dig a bit more into that before deciding anything.
