### ISSUE TITLE
ModuleNotFoundError: No module named 'pip._internal.cli.main'

### ISSUE THREAD

**Issue by bphunter1972** [python-poetry/poetry#3806]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: CentOS 7
- **Poetry version**: 1.10
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**:

## Issue
I am flagrantly flaunting the rules here because the earlier version of this bug clearly should not have been closed. 

I installed poetry on a system with version 19 of pip. The “main” function of pip keeps moving around, but pip’s virtual environment always installs a /bin/pip Python file that looks for pip._internal.cli.main, which isn’t located there for this version. 

Why not check the version of pip in this script and find main in the right place each time?

**Comment by logan-bobo** [comment]
The current version of poetry does not look to reproduce this error (1.2.1). Marking bug as closed.
