### ISSUE TITLE
[[tool.poetry.source]] limit of extra source repos

### ISSUE THREAD

**Issue by fliiiix** [python-poetry/poetry#3807]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 18.04.4 LTS
- **Poetry version**: 1.1.5
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/fliiiix/aac596c80d9c7f7a20571eb5c5b1e073

## Issue

It seems to me that there is a limit to how many extra pip sources I can add to the config.

I have 3 custom dependencies 
```
transportlayerskynet = "*"
ricofile = "*"
rico = "*"
```

And for each dependency I have a custom registry. 
So I added all 3 sources:

```
# rico file
[[tool.poetry.source]]
name = "gitlab"
url = "https://$gitlab/api/v4/projects/9954/packages/pypi/simple"

# rico
[[tool.poetry.source]]
name = "gitlab"
url = "https://$gitlab/api/v4/projects/9956/packages/pypi/simple"

# transport lib
[[tool.poetry.source]]
name = "gitlab"
url = "https://$gitlab/api/v4/projects/8984/packages/pypi/simple"
``` 

```
$ poetry update
  • Installing ricofile (2.1.7): Pending...
  • Installing ricofile (2.1.7): Failed

  RuntimeError

  Unable to find installation candidates for ricofile (2.1.7)

  at poetry/installation/chooser.py:72 in choose_for
       68│ 
       69│             links.append(link)
       70│ 
       71│         if not links:
    →  72│             raise RuntimeError(
       73│                 "Unable to find installation candidates for {}".format(package)
       74│             )
       75│ 
       76│         # Get the best link
```

While writing this issue I found a solution for me I will publish all packages to the same gitlab pip repo.
But I think there are valid use cases to have more than one or two extra sources.

**Comment by itssimon** [comment]
This might be related to or the reason for #3802.

**Comment by fliiiix** [comment]
Oh yeah this looks very much the same I will close my issue here and you can link to it from your bug report as an other case where this happens.
