### ISSUE TITLE
add --dry-run isn't very dry

### ISSUE THREAD

**Issue by habnabit** [python-poetry/poetry#381]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS 10.13.5
- **Poetry version**: Poetry 0.11.4
- **pyproject.toml file**: unchanged from `poetry new test`

## Issue

Doing `poetry add --dry-run {any package}` seems to add the package to `pyproject.toml`, do some work, and then revert `pyproject.toml`. I noticed this because interrupting the `poetry add` does not do the revert, and the dependency was effectively saved.

**Comment by Keyurkariya** [comment]
Can I work on this issue? I did figure out the cause of this here : 

https://github.com/python-poetry/poetry/blob/9c085a585c093a722717fec318bfc6610e93a9f1/poetry/console/commands/add.py#L173-L178

While the installer is running only `Exception` is being caught and not the `KeyboardInterrupt`. Also this issue would also be faced even without using `--dry-run `

**Comment by abn** [comment]
@Keyurkariya sure. Migth want to just use `BaseException` instead of `Exception`.

**Comment by Keyurkariya** [comment]
Yeah @abn `BaseException` is the `Baseclass` of both the `Exception`

**Comment by estyxx** [comment]
I was working on this, I did a Draft PR #3233,  I need to change to BaseException!  :)

**Comment by estyxx** [comment]
As #3233 was merged, think this issue can be closed maybe :)
