### ISSUE TITLE
Add a configuration option for `get-poetry.py` to only install `_vendor` dependencies for the current Python version.

### ISSUE THREAD

**Issue by ruohola** [python-poetry/poetry#3819]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

Currently the `get-poetry.py` install script installs Poetry's dependencies for Python versions `2.7`, `3.5`, `3.6`, `3.7`, `3.8`, and `3.9` to `.poetry/lib/poetry/_vendor/`, and they all take around 30MB each. This is annoying when trying to make minimal Docker images. Could there be an environment variable or another configuration option to only install these for the currently used Python version?

**Comment by ruohola** [comment]
In the mean time, I've been using:

```
find /home/user/.poetry/lib/poetry/_vendor/ -mindepth 1 -maxdepth 1 -not -name py3.9 -type d | xargs rm -rf 
```

in my `Dockerfile`s.

**Comment by abn** [comment]
This should go away with the new bootstrapping mechanism (see #3706). Feel free to test it out. Additionally, you could simply use `pip install poetry` in your `Dockerfile`.

**Comment by ruohola** [comment]
>This should go away with the new bootstrapping mechanism (see #3706). 

Looks promising, thanks!

>Additionally, you could simply use pip install poetry in your Dockerfile.

Yeah I know, but I really like the fact that by installing with the `get-poetry.py` script Poetry's own dependencies are completely isolated from my other packages.
