### ISSUE TITLE
First time without success

### ISSUE THREAD

**Issue by seghier** [python-poetry/poetry#3832]
Hello, please help
I try to use poetry without success and i don't know if it will work in my case or not
I have two files: **_pymaxwell5.pyd**  and  **pymaxwell.py**
How i can build a package? and than install it in **C:\Python39\Lib\site-packages** not in a separated folder

i tried with `poetry init`

![image](https://user-images.githubusercontent.com/6026588/112470390-e4d2c480-8d6a-11eb-845b-b799af9146bb.png)

**Comment by stephsamson** [comment]
Hi @seghier, for questions, please go to our [Discussions](https://github.com/python-poetry/poetry/discussions) page, or ask a question on [StackOverflow with the #python-poetry tag](https://stackoverflow.com/questions/tagged/python-poetry). 

You can also read more about how to use Poetry on our [docs](https://python-poetry.org/docs/basic-usage/).

Thanks!

**Comment by seghier** [comment]
@stephsamson , thanks
i found a solution
