### ISSUE TITLE
default pytest version doesn't support pyproject.toml configuration

### ISSUE THREAD

**Issue by howeaj** [python-poetry/poetry#3834]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows 10
- **Poetry version**: 1.1.5

## Issue
The default pyproject.toml that `poetry new` creates includes an old version of pytest that is not compatible with pyproject.toml configuration. I'd expect it to give you the same version you'd get if adding it with `poetry add`.

i.e. the `pytest = "^5.2"` that it gives you will ignore any config such as
```
[tool.pytest.ini_options]
log_cli=true
log_level="DEBUG"
```
Which is quite unhelpful.

I'd assumed poetry would have just given me the latest version of pytest, as it does when running `poetry add`, and so wasted an hour or so trying to debug this issue, thinking I had done something wrong in configuring poetry.

**Comment by pmav99** [comment]
https://github.com/python-poetry/poetry/blob/cdfcd146ebe54b4277346a6cb9bfb57cb835e2b5/poetry/console/commands/new.py#L65-L68

**Comment by finswimmer** [comment]
Hello @pmav99,

we will most likely remove this in a future release completely. See https://github.com/python-poetry/poetry/pull/2768

fin swimmer
