### ISSUE TITLE
Unable to find installation candidates for pyqt5

### ISSUE THREAD

**Issue by jasperjonker** [python-poetry/poetry#3837]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Raspberry pi - Raspbian 10
- **Poetry version**: 1.1.5
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: [pyproject.toml](https://gist.github.com/jasperjonker/179d40e3eee06090c3391d9ca541a1c4)

## Issue
I'm getting issues updating my current poetry setup. When running `poetry update -vvv`:
```sh
.
.
   1: Version solving took 31.418 seconds.
   1: Tried 1 solutions.

Writing lock file

Finding the necessary packages for the current system

Package operations: 1 install, 23 updates, 0 removals

  • Updating cryptography (3.4.6 -> 3.4.7): Downloading... 100%
  • Updating cryptography (3.4.6 -> 3.4.7): Installing...
  • Updating cryptography (3.4.6 -> 3.4.7)
  • Installing pyqt5-qt5 (5.15.2): Pending...
  • Installing pyqt5-qt5 (5.15.2): Failed

  RuntimeError

  Unable to find installation candidates for pyqt5-qt5 (5.15.2)

  at ~/.poetry/lib/poetry/installation/chooser.py:72 in choose_for
       68│ 
       69│             links.append(link)
       70│ 
       71│         if not links:
    →  72│             raise RuntimeError(
       73│                 "Unable to find installation candidates for {}".format(package)
       74│             )
       75│ 
       76│         # Get the best link

  • Updating sqlalchemy (1.4.2 -> 1.4.3): Downloading... 100%
  • Updating sqlalchemy (1.4.2 -> 1.4.3): Installing...
  • Updating sqlalchemy (1.4.2 -> 1.4.3)
```

Does this mean there is no pyqt5 version available that the other packages support? As I have no problem installing pyqt5==5.15.2 using pip.

**Comment by BruceZhang1993** [comment]
I have a problem related with this issue. poetry cannot find wheel package for PyQt5, instead, it tries to build from source

**Comment by abn** [comment]
Based on the original report, and looking at https://pypi.org/project/PyQt5-Qt5/#files the behavior is expected.

This is because,

1. The package does not seem to publish sdists.
2. There exists not arm (raspberry pi) compatible wheel available for the package in question.
3. The pip command is using `pyqt5` and not `pyqt5-qt5`. The former has sdists available (https://pypi.org/project/PyQt5/#files), and would be used to build from source since no arm wheel exist.

**Comment by jasperjonker** [comment]
Thank you for your comment @abn. However, I have specified `pyqt5` in my `pyproject.toml`, not `pyqt5-qt5`. Why does it search for `pyqt5-qt5` in the first place?

**Comment by npielawski** [comment]
I have the same issue, did you find any solution @jasperjonker?

**Comment by jasperjonker** [comment]
Unfortunately the wheels provided by PyQt5 is only for a few platforms (only x86 on mac, linux & windows). It works for me on arm (raspberry pi) specifying `PyQt5 = "=5.15.2"` in `pyproject.toml`. The source files are included there, so it'll compile it from source (note that installing it will take a long time).

If that doesn't work, [download](https://www.riverbankcomputing.com/software/pyqt/download) the source code and [compile](https://www.riverbankcomputing.com/static/Docs/PyQt5/installation.html#building-pyqt5) it yourself.

**Comment by dimbleby** [comment]
if a project provides neither a source distribution nor a binary distribution suitable for your platform, there is nothing that poetry can do about this.  

this can be closed
