### ISSUE TITLE
[docs] Build section specifies poetry_core in docs but uses poetry-core per default

### ISSUE THREAD

**Issue by raman-nbg** [python-poetry/poetry#3849]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue
According to the documentation (https://python-poetry.org/docs/pyproject/#poetry-and-pep-517) the `[build-section]` should contain a `requires` property with the value `poetry_core>=1.0.0`.

When I create a new poetry project with `poetry init`, the default value is `poetry-core>=1.0.0` (hyphen instead of underscore).

What is the correct value? Hyphen or underscore?

**Comment by stephsamson** [comment]
Hiya, it should be with a dash, see #3758 and #3808.
