### ISSUE TITLE
poetry pollutes PATH 

### ISSUE THREAD

**Issue by jottr** [python-poetry/poetry#3850]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: 
- **Poetry version**: 
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue
Relates to https://github.com/python-poetry/poetry/issues/2620

The fix for above issue introduced in PR **https://github.com/python-poetry/poetry/pull/3169** creates another issue.
Poetry used to be exported to the `$PATH` variable from `.zprofile`  before this change.

Exporting from `~/.zshrc` causes pollution of the`$PATH`-variable and slower shell load times for anyone anyone using a shell multiplexer like `screen` or `tmux`: 

```
$ echo "export PATH="$HOME/.poetry/bin:$PATH" >> ~/.zshrc
echo $PATH | tr ':' '\n' | sort | uniq -d # empty
tmux # start tmux
echo $PATH | tr ':' '\n' | sort | uniq -d # duplicate exports
/Users/jottr/.poetry/bin

```

I suggest that https://github.com/python-poetry/poetry/pull/3169 be reverted until an appropriate fix for https://github.com/python-poetry/poetry/issues/2620 has been found.

**Comment by finswimmer** [comment]
Hello @jottr,

the [new installer script](https://python-poetry.org/blog/announcing-poetry-1.2.0a1/#deprecation-of-the-get-poetrypy-script) should close this ticket, because the executable is now located in  `~/.local/bin`.

fin swimmer
