### ISSUE TITLE
Poetry doesn’t find the right thing to download

### ISSUE THREAD

**Issue by ThatXliner** [python-poetry/poetry#3852]
- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate. (At least, [abn](https://github.com/abn) told me [this is a new bug](https://discord.com/channels/487711540787675139/487711540787675143/825664421145215008) (discord))
- [X] If an `exception` occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**:  11.2.1 (macOS Bjg Sur)
- **Poetry version**: 
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 
(See below)
## Issue

Alrighty. I'm on Big Sur, and I want to install [Jinja2](https://github.com/pallets/jinja). Jinja2 has no wheel for Big Sur. Yet Poetry still chooses the latest macOS wheel (Catalina). Then it fails because it is not the right one. Poetry *should* be able to detect that it is not the correct wheel and/or fallback to installing via sdist.

This [hack](https://discord.com/channels/487711540787675139/487711540787675143/825477394441699338) (a little modified) worked!

Before the hack, it looked a little like this:

[![](https://cdn.discordapp.com/attachments/487711540787675143/825474790369919006/Screen_Shot_2021-03-27_at_2.02.02_PM.png)](https://discord.com/channels/487711540787675139/487711540787675143/825474795549360198)

**Comment by abn** [comment]
```sh
poetry run python -c 'import packaging.tags; print(list(str(t) for t in packaging.tags.sys_tags()))'
```

Returns: https://gist.github.com/ThatXliner/5cc7a5ecdb86f0308cd9c7ae1267707e

**Comment by abn** [comment]
This looks like it is caused by https://github.com/pypa/packaging/issues/318. Effectively we use `pacakging.tags.sys_tags()` internally to identify supported tags.

Master should be using a fixed packaging version. 

You can test using poetry from master, as follows.

### Using pipx
```sh
pipx install --force --suffix=@master 'poetry @ git+https://github.com/python-poetry/poetry.git@master'
poetry@master new foobar
poetry@master add MarkupSafe
```

**Comment by ThatXliner** [comment]
It works (although now the normal poetry `1.1.5` works too). Just saying, the UI for `1.2.0a0` (master version as of writing this comment) is whack.
<img width="1472" alt="Screen Shot 2021-04-10 at 7 06 50 PM" src="https://user-images.githubusercontent.com/66848002/114289833-e9b49b00-9a2f-11eb-8a26-acead18e6caa.png">
It just stays at "installing"

**Comment by abn** [comment]
`1.1.5` might work because it got cached?

**Comment by ThatXliner** [comment]
Hm true! I will try again probably this weekend

**Comment by ThatXliner** [comment]
Cannot reproduce anymore (even with deleted cache)
