### ISSUE TITLE
Install a single package from poetry.lock

### ISSUE THREAD

**Issue by cprevosteau** [python-poetry/poetry#3854]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

Hi,
Thanks for this marvellous tool.

I often find myself wanting to install a single package from `poetry.lock`.
For instance, in my CI/CD pipeline I have a task to check my code against a linter.
And I would like to install the version of `flake8` defined in the `poetry.lock` without installing the whole file.

Today the only way to get this version is to parse the result of the command `poetry show flake8`.

It would be nice to able to do so with a command like:
```
poetry install flake8
```
in order to only install `flake8`.

Or at least there is an option to the command `poetry show` to only return the version of the package. Something like:
```
$ poetry show flake8 --only-version
3.9.0
```

This way a simple `pip install flake8==$(poetry show flake8 --only-version)` will do the trick in my CI/CD task.

**Comment by finswimmer** [comment]
Hello @cprevosteau,

this was requested earlier in https://github.com/python-poetry/poetry/issues/3570. I've made a PR for it in https://github.com/python-poetry/poetry/pull/3623. But maybe it get superseded by the implementation for https://github.com/python-poetry/poetry/issues/1644.

fin swimmer
