### ISSUE TITLE
'EmptyConstraint' object has no attribute 'min' with pytest and Python 2.7

### ISSUE THREAD

**Issue by nikmolnar** [python-poetry/poetry#3862]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS 11.1 Big Sur
- **Poetry version**: 1.1.5
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/nikmolnar/cc95e80d0cf6c9256b53294b759b3881

## Issue

I've discovered a bug that arises when `pytest` is combined with Python `^2.7` in `pyproject.toml`. The Gist linked above provides a minimal example of this issue. Running `poetry lock` with the above file results in the following exception:

```
AttributeError

  'EmptyConstraint' object has no attribute 'min'
```

The error does not appear if either `pytest` is removed or the Python version is changed to `^3.6`. I originally reported this as part of #2372, but then realized that that issue related to error handing in response to an error in `pyproject.toml`. As this error occurs in a correctly-formatted `pyproject.toml`, I believe it is a distinct issue.

**Comment by Nitori-** [comment]
After some debugging I think I narrowed down the problem to a recent backports.functools-lru-cache package release. Changing the dev-deps to this still reproduces the problem:

```toml
[tool.poetry.dev-dependencies]
"backports.functools-lru-cache" = "*"
```

As a temporary workaround, you can pin this dependency back like this:
```toml
"backports.functools-lru-cache" = "1.6.1"
```

poetry seems to be tripping up on this line from their `setup.cfg`:
```
	pytest-mypy; python_implementation != "PyPy" and python_version < "3.10" and python_version > "3"
```

**Comment by nikmolnar** [comment]
Thanks for the workaround, @Nitori- !

**Comment by pawamoy** [comment]
Experiencing the same thing with `python = "^3.6"`. I tried adding `"backports.functools-lru-cache" = "1.6.1"` to my deps or dev-deps, but it didn't solve the issue.

**Comment by Nitori-** [comment]
My suspicion is that there might be another dependency out in the wild that also exposes the bug. If you can get poetry onto a debugger that's how I found out that the lru-cache package was causing issues.

**Comment by pawamoy** [comment]
I patched Poetry's source to catch the exception and print the package name:

`~/.local/pipx/venvs/poetry/lib/python3.9/site-packages/poetry/core/packages/__init__.py` line 219
```python
        try:
            dep.python_versions = " || ".join(ors)
        except AttributeError:
            print(name)
```

The output showed `pytest-mypy`. Oh well I see now it was mentioned in your comments :weary:

**Comment by Nitori-** [comment]
If you jump up maybe 2-3 stacks, you'll see the package that was depending on pytest-mypy. That's probably the one that needs to get pinned.

**Comment by Nitori-** [comment]
@pawamoy I did some digging and the issue you're seeing is from `backports.entry_points_selectable`. Unfortunately it looks like there is no release to pin back to, the very first release has the same problematic line as the other backports module I mentioned above. I think the only way to work around this one would be to find what's depending on this backports package and pin that instead.

Of course, all of this is just workarounds. It's still fundamentally a bug in poetry that can't seem to handle this dependency line:

```
	pytest-mypy; python_implementation != "PyPy" and python_version < "3.10" and python_version > "3"
```

**Comment by pawamoy** [comment]
Damn, I can't work on any project now, nothing will resolve :sweat_smile: 
I'll have to debug this first!

**Comment by pawamoy** [comment]
I wonder if `pytest-mypy; python_implementation != "PyPy" and python_version < "3.10" and python_version > "3"` is valid though:

- `> "3"` suggests *strictly higher than version 3*, and Poetry deduces `>=4`, which seems correct to me?
- then `< "3.10"` makes it impossible

**Comment by dkasak** [comment]
`> "3"` could also be understood as `> "3.0"`, in which case the inequality makes sense so perhaps that was the intent?

**Comment by pawamoy** [comment]
@dkasak maybe! However I think it's parsed as precision 1, entering this condition:

```python
                    if parsed_version.precision == 1:
                        if op == "<=":
                            op = "<"
                            version = parsed_version.next_major.text
                        elif op == ">":
                            op = ">="
                            version = parsed_version.next_major.text
```

**Comment by pawamoy** [comment]
OK, PEP508 says [versions comparison is done according to PEP440](https://www.python.org/dev/peps/pep-0508/#versions).

**Comment by pawamoy** [comment]
And using PEP440 version parsing, it seems Poetry should not consider `>3` to be `>=4` since

```python
>>> import packaging
>>> from packaging import version
>>> version.parse("3.6") > version.parse("3")
True
```

**Comment by pawamoy** [comment]
Poetry core has a 1.1.0a1 release that refactored all this, I'll try it and report back.

**Comment by pawamoy** [comment]
Ah, there's a related PR https://github.com/python-poetry/poetry-core/pull/154

**Comment by pawamoy** [comment]
I've identified the package who recently released a new version depending on backports.entry_points_selectable: pytest-randomly v3.6.0: https://github.com/pytest-dev/pytest-randomly/compare/3.5.0...3.6.0#diff-2d88edd924033b49783dcb4f93a0ed0ec8aae0b6aac3bad984a2c1d323b93c37R1

I was able to fix that issue in CI with the following hack:

```yaml
    - name: Set up Poetry
      # HACK: https://github.com/python-poetry/poetry-core/pull/154
      run: |
        pip install git+https://github.com/python-poetry/poetry
        pip uninstall -y poetry-core
        pip install git+https://github.com/pbzweihander/poetry-core@resolve-invalid-python-version-constraint
```

**Comment by nikmolnar** [comment]
Thanks for the quick work on this, @sdispater et. al!

**Comment by sobolevn** [comment]
I would love to see this fix released, as it hits me really hard in __all__ (>50) my projects.
