### ISSUE TITLE
Poetry from `install-poetry.py` does not install packages to system Python even with `POETRY_VIRTUALENVS_CREATE=0`

### ISSUE THREAD

**Issue by ruohola** [python-poetry/poetry#3870]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

Poetry installed from the [latest `install-poetry.py`](https://github.com/python-poetry/poetry/blob/45a9b8f20384591d0a33ae876bcf23656f928ec0/install-poetry.py) does not install packages to system Python even with `POETRY_VIRTUALENVS_CREATE=0`.

### Steps to reproduce:

Spin up a fresh container for demoing:
```
$ docker run -it python:3.9.2-buster bash
```

In the container:
```
$ curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/45a9b8f20384591d0a33ae876bcf23656f928ec0/install-poetry.py | python -
$ export PATH="/root/.local/bin:$PATH"
$ export POETRY_VIRTUALENVS_CREATE=0
$ poetry --version
Poetry version 1.1.5
$ poetry init  # go with the bare defaults
```

Install a package (note the "Skipping virtualenv creation" message):
```
$ poetry add django
Skipping virtualenv creation, as specified in config file.
Using version ^3.1.7 for Django

Updating dependencies
Resolving dependencies... (0.6s)

Writing lock file

Package operations: 4 installs, 0 updates, 0 removals

  • Installing asgiref (3.3.1)
  • Installing pytz (2021.1)
  • Installing sqlparse (0.4.1)
  • Installing django (3.1.7)
```

Then try to run
```
$ python -c 'import django'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'django'
```

We can see that `django` got installed to here:
```
$ find / -type d -name django
/root/.local/share/pypoetry/venv/lib/python3.9/site-packages/django
/root/.local/share/pypoetry/venv/lib/python3.9/site-packages/django/forms/templates/django
/root/.local/share/pypoetry/venv/lib/python3.9/site-packages/django/forms/jinja2/django
```

When `pip` would install it here:
```
$ pip install django
$ python -c 'import django'  # no errors
$ find / -type d -name django
/usr/local/lib/python3.9/site-packages/django
/usr/local/lib/python3.9/site-packages/django/forms/templates/django
/usr/local/lib/python3.9/site-packages/django/forms/jinja2/django
/root/.local/share/pypoetry/venv/lib/python3.9/site-packages/django
/root/.local/share/pypoetry/venv/lib/python3.9/site-packages/django/forms/templates/django
/root/.local/share/pypoetry/venv/lib/python3.9/site-packages/django/forms/jinja2/django
```

The same thing also happens with non-root users. This issue does NOT happen with Poetry installed from the [latest `get-poetry.py`](https://github.com/python-poetry/poetry/blob/45a9b8f20384591d0a33ae876bcf23656f928ec0/get-poetry.py) NOR with `poetry==1.1.5` installed from `pip`.

**Comment by sdispater** [comment]
Thanks for testing the new bootstrap method and for reporting this issue!

I think I know where the issue is coming from (Poetry's own virtual environment is mistakenly seen as the system environment).

I'll try to come up with a fix and let you know.

**Comment by nuffan** [comment]
I have the some problem when i use poetry install packages in docker

**Comment by ClementWalter** [comment]
I have a possibly related issue. I am working inside a venv that I created by hand not using poetry, and poetry while seeing the deps already existing, download and install it again, see below:

```
(.venv) clementwalter@tmp$ poetry config --list
cache-dir = "/home/clementwalter/.cache/pypoetry"
experimental.new-installer = true
installer.parallel = true
virtualenvs.create = false
virtualenvs.in-project = null
virtualenvs.path = "{cache-dir}/virtualenvs"  # /home/clementwalter/.cache/pypoetry/virtualenvs

(.venv) clementwalter@tmp$ poetry env info

Virtualenv
Python:         3.7.10
Implementation: CPython
Path:           /home/clementwalter/tmp/.venv
Valid:          True

System
Platform: linux
OS:       posix
Python:   /opt/miniconda

(.venv) clementwalter@tmp$ poetry add numpy==1.19.2

Updating dependencies
Resolving dependencies... (0.1s)

Writing lock file

Package operations: 0 installs, 1 update, 0 removals

  • Updating numpy (1.19.2 /opt/miniconda/lib/python3.7/site-packages -> 1.19.2)

(.venv) clementwalter@tmp$ python -c "import numpy; print(numpy.__file__)"
/home/clementwalter/tmp/.venv/lib/python3.7/site-packages/numpy/__init__.py

(.venv) clementwalter@tmp$ poetry remove numpy
Updating dependencies
Resolving dependencies... (0.1s)

Writing lock file

Package operations: 0 installs, 0 updates, 1 removal

  • Removing numpy (1.19.2)

(.venv) clementwalter@tmp$ pip install numpy==1.19.2
Requirement already satisfied: numpy==1.19.2 in /opt/miniconda/lib/python3.7/site-packages (1.19.2)

(.venv) clementwalter@tmp$ python -c "import numpy; print(numpy.__file__)"
/opt/miniconda/lib/python3.7/site-packages/numpy/__init__.py
```

So here poetry does an extra install while pip does not and poetry is not supposed to manage env, so why not keeping the version that already exists?

**Comment by ruohola** [comment]
> I have a possibly related issue. I am working inside a venv that I created by hand not using poetry (with --system-site-package), and poetry while seeing the deps already existing, download and install it again, see below:
> 
> ```
> (.venv) clementwalter@tmp$ poetry config --list
> cache-dir = "/home/clementwalter/.cache/pypoetry"
> experimental.new-installer = true
> installer.parallel = true
> virtualenvs.create = false
> virtualenvs.in-project = null
> virtualenvs.path = "{cache-dir}/virtualenvs"  # /home/clementwalter/.cache/pypoetry/virtualenvs
> 
> (.venv) clementwalter@tmp$ poetry env info
> 
> Virtualenv
> Python:         3.7.10
> Implementation: CPython
> Path:           /home/clementwalter/tmp/.venv
> Valid:          True
> 
> System
> Platform: linux
> OS:       posix
> Python:   /opt/miniconda
> 
> (.venv) clementwalter@tmp$ poetry add numpy==1.19.2
> 
> Updating dependencies
> Resolving dependencies... (0.1s)
> 
> Writing lock file
> 
> Package operations: 0 installs, 1 update, 0 removals
> 
>   • Updating numpy (1.19.2 /opt/miniconda/lib/python3.7/site-packages -> 1.19.2)
> 
> (.venv) clementwalter@tmp$ python -c "import numpy; print(numpy.__file__)"
> /home/clementwalter/tmp/.venv/lib/python3.7/site-packages/numpy/__init__.py
> 
> (.venv) clementwalter@tmp$ poetry remove numpy
> Updating dependencies
> Resolving dependencies... (0.1s)
> 
> Writing lock file
> 
> Package operations: 0 installs, 0 updates, 1 removal
> 
>   • Removing numpy (1.19.2)
> 
> (.venv) clementwalter@tmp$ pip install numpy==1.19.2
> Requirement already satisfied: numpy==1.19.2 in /opt/miniconda/lib/python3.7/site-packages (1.19.2)
> 
> (.venv) clementwalter@tmp$ python -c "import numpy; print(numpy.__file__)"
> /opt/miniconda/lib/python3.7/site-packages/numpy/__init__.py
> ```
> 
> So here poetry does an extra install while pip does not and poetry is not supposed to manage env, so why not keeping the version that already exists?

That seems like a separate issue, but I'm not sure.

**Comment by JamesXNelson** [comment]
a :raised_hand_with_fingers_splayed: from me too.  cannot use install-poetry.sh on relatively clean ubuntu 20.04, but get-poetry.sh works perfectly.

**Comment by SaulAryehKohn** [comment]
I found that I was able to remove this issue on Ubuntu 20.04 by specifying a particular release of `virtualenv` in `install-poetry.py`:

```
517         with temporary_directory() as tmp_dir:
518             subprocess.call(
519                 [sys.executable, "-m", "pip", "install", "virtualenv==20.0.23", "-t", tmp_dir], # <-- changed from just "virtualenv"
520                 stdout=subprocess.PIPE,
521                 stderr=subprocess.STDOUT,
522             )
```
