### ISSUE TITLE
Not able to install package from work private repo

### ISSUE THREAD

**Issue by beauremus** [python-poetry/poetry#3880]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS Big Sur 11.2.3
- **Poetry version**: 1.1.5
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/beauremus/e9e5ab98ba30cfb6cf08e9ccb942cb25

## Issue

I believe that these issues are related to mine, #1851 and #517.

When I try to install a package from our work repo, `pip` tells me that it can't install a non-gzip file.

When `pip` gets called to install the downloaded package from a simple repo, I get a stack saying `errored with the following return code 2`, `OSError: Not a gzipped file (b'./')`, `During handling of the above exception, another exception occurred:`, `tarfile.ReadError: not a gzip file`

```bash
at ~/.poetry/lib/poetry/utils/env.py:1074 in _run
      1070│                 output = subprocess.check_output(
      1071│                     cmd, stderr=subprocess.STDOUT, **kwargs
      1072│                 )
      1073│         except CalledProcessError as e:
    → 1074│             raise EnvCommandError(e, input=input_)
      1075│ 
      1076│         return decode(output)
      1077│ 
      1078│     def execute(self, bin, *args, **kwargs):
```

This isn't the issue; it's the symptom. `pip` doesn't know what to do with the downloaded POSIX archive. I used `file` to tell me that it's a POSIX archive and not a gzip.

The issue is in how the file is downloaded. Line [672 in poetry/installation/executor.py](https://github.com/python-poetry/poetry/blob/fcc2c839952a57e0268b623b319fa512982ca405/poetry/installation/executor.py#L672) uses `iter_content` but the `requests` documentation says

>Note
>An important note about using Response.iter_content versus Response.raw. Response.iter_content will automatically decode the gzip and deflate transfer-encodings. Response.raw is a raw stream of bytes – it does not transform the response content. If you really need access to the bytes as they were returned, use Response.raw.

So, using `raw.stream` instead seems like the best option.

I'm willing to open a PR if this is the correct path forward.

Thanks

**Comment by dimbleby** [comment]
you have certainly misunderstood something.  That requests documentation is talking about the transfer encoding, it is not not saying that requests will present you with an unzipped file even though the server provided a zipped file.

18 months later I guess you have either sorted this our or don't care any more and this should be closed.

**Comment by beauremus** [comment]
It just means I'm not using Poetry.
