### ISSUE TITLE
peotry add pprint results in an error. Other packages like bpython work.

### ISSUE THREAD

**Issue by cocoonkid** [python-poetry/poetry#3882]
- [ x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [ x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **Arch Linux 5.1
- **Poetry version 1.15
 ValueError

  Could not find a matching version of package pprint

  at ~/.asdf/installs/poetry/1.1.5/lib/poetry/console/commands/init.py:367 in _find_best_version_for_package
      363│         )
      364│ 
      365│         if not package:
      366│             # TODO: find similar
    → 367│             raise ValueError(
      368│                 "Could not find a matching version of package {}".format(name)
      369│             )
      370│ 
      371│         return package.pretty_name, selector.find_recommended_require_version(package)

peotry add pprint 
results in an error. Other like bpython work,

 I tried via natively install poetry and asdf and venv.

They all give the same error.

**Comment by toyjack** [comment]
actually you don't  have to install pprint before using it.
just put `from pprint import pprint` in your file.

and the error means "didn't find it".

**Comment by mkniewallner** [comment]
As explained, `pprint` is part of [Python stdlib](https://docs.python.org/3/library/pprint.html), and is not a package that is present on PyPI, so you do not need to add it to use it.

**Comment by cocoonkid** [comment]
Yes everything works. Thanks!
