### ISSUE TITLE
Remove the description field from poetry.lock

### ISSUE THREAD

**Issue by ClementWalter** [python-poetry/poetry#3888]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

The "description" field of the `poetry.lock` appears to be useless while it can causes some trouble because it adds random contents from the packages authors into a repository.

For example, the `absl-py` package has a url in its description (`"Abseil Python Common Libraries, see https://github.com/abseil/abseil-py."`) which does not pass a custom check in my CI.

Looking into the [locker.py](https://github.com/python-poetry/poetry/blob/b753aaf4c3c08ef0e54941a6616fe318fdf4f6e4/poetry/packages/locker.py) file I think it would be better to simply remove it because it is always optional.

Otherwise a config could be added and then used therein.

**Comment by dimbleby** [comment]
this would prevent `poetry show` from providing descriptions.

**Comment by Secrus** [comment]
For the reason mentioned above, closing.
