### ISSUE TITLE
Failure while installing package with a sub-dependency package of form (../xxx)

### ISSUE THREAD

**Issue by ws1088** [python-poetry/poetry#3896]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**:  Windows 10, Unix
- **Poetry version**: 1.1.5

## Issue
Exception `ValueError Directory ../pack1 does not exist` raised

### How to reproduce:
```
mkdir test1; cd test1
poetry new app1
poetry new pack1
poetry new pack2
cd pack2
poetry add ../pack1
cd ../app1
poetry add ../pack2
```

**Comment by finswimmer** [comment]
Hello @ws1088,

since poetry 1.1 path dependencies are not installed in editable mode by default anymore. So the relative pathes are interpreted relative to the build env.

You have to set `develop=False` in your `pyproject.toml` for those packages. At the moment we have no parameter for `poetry add` that is doing this for you.

```toml
[tool.poetry.dependencies]
my-package = { path = "../my-package/", develop = false }
```

This also described in the [docs](https://python-poetry.org/docs/dependency-specification/#path-dependencies)

fin swimmer

**Comment by ws1088** [comment]
@finswimmer I don't think I am specifying any packages in *editable* mode. None of the `pyproject.toml` has `develop` set to `true`. Can you please try the steps I outlined in your system and tell me if I have done anything wrong (I don't think so). Thanks!

**Comment by finswimmer** [comment]
Sorry, my example snippet was wrong. I corrected it.

**Comment by ws1088** [comment]
thanks, i have to add `develop = true` for the `pyproject.toml` for app1. This means any packages which use `poetry add ../xxx` cannot be added by another package unless the other package use `develop = true`. It almost mean whenether we add a package with `poetry add ../yyy` we should use `develop = true` because we don't know if `yyy` includes sub-packages in the form of `../<path>`. 

So this means `develop = true` should be default if we use `poetry add ../<path>`

Is my logic right?

**Comment by ws1088** [comment]
@finswimmer I am not sure about what you mean here as well: 
> since poetry 1.1 path dependencies are not installed in editable mode by default anymore. So the relative paths are interpreted relative to the build env.

The sample instructions to reproduce the problem is not dealing with `editable mode`.  Also there is no option to add package with 'absolute path`. The options with `add` are:

```
  You can specify a package in the following forms:
    - A single name (requests)
    - A name and a constraint (requests@^2.23.0)
    - A git url (git+https://github.com/python-poetry/poetry.git)
    - A git url with a revision (git+https://github.com/python-poetry/poetry.git#develop)
    - A file path (../my-package/my-package.whl)
    - A directory (../my-package/)
    - A url (https://example.com/packages/my-package-0.1.0.tar.gz
  ```
You can't add an absolute path with `add`. It will give the following error:

```py3
       879│         cf = self._flavour.casefold_parts
       880│         if (root or drv) if n == 0 else cf(abs_parts[:n]) != cf(to_abs_parts):
       881│             formatted = self._format_parsed_parts(to_drv, to_root, to_parts)
       882│             raise ValueError("{!r} does not start with {!r}"
    →  883│                              .format(str(self), str(formatted)))
       884│         return self._from_parsed_parts('', root if n == 1 else '',
```

**Comment by finswimmer** [comment]
>  It almost means whenever we add a package with poetry add ../yyy we should use develop = true because we don't know if yyy includes sub-packages in the form of ../<path>.

Correct.

> The sample instructions to reproduce the problem is not dealing with editable mode.

You are adding `pack1` as a path dependency without editable mode to `pack2`. Then you are adding `pack2` as a path dependency without editable mode to `app1`.  So for `pack2` a `wheel` gets build, which happens in a temporary folder. From there the relative path to `pack1` cannot be resolved. This is why you have to write `pack2 = {path = "../pack2", develop=true}` into the `pyproject.toml` of `app1`.

**Comment by ws1088** [comment]
Why would we not able to use absolute path? in `pack = { path = "/an/absolute/path/to/pack2" }` ? Wouldn't it solve the problem?
