### ISSUE TITLE
Silence Python version mismatch warning

### ISSUE THREAD

**Issue by ulope** [python-poetry/poetry#3902]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
  - #3715 touches this but seems to be more generic about poetry output in general
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

Poetry recently gained the ability to find other python versions when the default executable doesn't match the project requirements.

Unfortunately this currently always causes the following warning to be printed:
```
The currently activated Python version 3.a.b is not supported by the project (^3.x).
Trying to find and use a compatible version.
Using python3.x (3.x.y)
```

This message serves no useful purpose in most cases, esp. when looking for a suitable version was successful.

Please add an option to disable it or better yet remove it by default and only show it in verbose mode.

**Comment by finswimmer** [comment]
Hello,

this message is printed to stderr, so it should not cause any harm. It is important to give a feedback to the user, if the default behavior wasn't successfully and another approach will be tried.

fin swimmer
