### ISSUE TITLE
Virtual environment is not registered with poetry shell

### ISSUE THREAD

**Issue by Pandawan** [python-poetry/poetry#3912]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS Big Sur 11.2.3 (default python install v3.8.2)
- **Poetry version**: 1.1.5
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/Pandawan/414c10c38be67ff22c7c4efb843f1f0b

## Issue

Note: This may or may not be related to #1604 and #1821 but the issue was closed as this was supposedly fixed a while ago so I'm opting to create a new issue for this.

So the issue is, when I use `poetry shell` it seems as though the virtual environment is not registered—the libraries/modules installed through it cannot be found. However, when I use `poetry run`, everything works great and my `python` is able to see the modules I wanted.

To be more precise: I initialized a simple project using `poetry init` and got the resulting `pyproject.toml` file (linked above). I added only one library/dependency, the `ezgraphics-2.1.tar.gz` file [which I downloaded online](http://www.ezgraphics.org/Software/Download) and is included in the `pyproject.toml` file. Then, I ran `poetry install` to make sure the library was installed. 
Now to the issue. If I run `poetry shell` followed by `python -c "import ezgraphics"`, I get the error 
```sh
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'ezgraphics'
```
However, if I run `poetry run python -c "import ezgraphics"` no error occurs (implying that the import was successful). In fact, if I run `poetry run python -c "import ezgraphics; print(ezgraphics.__file__)"`, I get the correct path
```
/Users/migueltenant/Library/Caches/pypoetry/virtualenvs/poetry-issue-FrwnS6VY-py3.8/lib/python3.8/site-packages/ezgraphics/__init__.py`
``` 
so I don't think it's an issue with the library itself.

So yeah, for some reason, the virtual environment is setting correctly with `poetry run` but not with `poetry shell`.

PS: This also happens with vscode. When I set the `python.pythonPath` and `python.venvPath` properties to the correct location, it doesn't work. When I do `poetry shell` followed by `code .`, and try again, it still doesn't work. However, when I do `poetry run code .` only then does vscode recognize the `ezgraphics` module with intellisense.

**Comment by sinoroc** [comment]
Do you also encounter the issue with poetry 1.1.4?

**Comment by Pandawan** [comment]
Yes, this also occurs with 1.1.4

And do note that the `ezgraphics` package does not seem to be related. When I create a blank poetry project, and `poetry shell` into it, the virtual environment from `sys.prefix` is not modified.

```
➜  poetry_issue_2 poetry install
Installing dependencies from lock file
➜  poetry_issue_2 poetry show
➜  poetry_issue_2 poetry shell
Spawning shell within /Users/migueltenant/Library/Caches/pypoetry/virtualenvs/poetry-issue-2-j52ZJotV-py3.8
➜  poetry_issue_2 . /Users/migueltenant/Library/Caches/pypoetry/virtualenvs/poetry-i
ssue-2-j52ZJotV-py3.8/bin/activate
(poetry-issue-2-j52ZJotV-py3.8) ➜  poetry_issue_2 python -c "import sys; print(sys.prefix)"
/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8
(poetry-issue-2-j52ZJotV-py3.8) ➜  poetry_issue_2 poetry run python -c "import sys; print(sys.prefix)"
/Users/migueltenant/Library/Caches/pypoetry/virtualenvs/poetry-issue-2-j52ZJotV-py3.8
```

**Comment by joelb123** [comment]
I can confirm that sys.prefix is not set properly with "poetry shell" under MacOS and Apple python3.8.2 and poetry 1.1.6.   The sys.prefix that is reported under "poetry shell" is sys.base_exec_prefix.

The problem seems to be in poetry; using "source ~/Library/Caches/pypoetry/virtualenv/mypackagevirtualenv/bin/activate" reports the virtualenv directory as sys.prefix while "poetry shell" reports sys.prefix as equal to sys.base_exec_prefix.  

Wiping my user python library and poetry installation clean and updating the Apple-supplied system python packages [pip, setuptools, wheel, six] to latest before installing poetry from scratch in the recommended way did not fix the problem.  Using "source ~/Library/Caches/pypoetry/virtualenv/mypackagevirtualenv/bin/activate"  instead of "poetry shell" is a workaround.  That this workaround works strongly suggests that the problem is in "poetry shell" rather than in anything about the installation.

**Comment by lefi7z** [comment]
I experienced this issue running `zsh`. Using `poetry run` and `poetry shell` points to different `python` executables:

```
$ poetry run which python
/home/lefitz/.cache/pypoetry/virtualenvs/project-Clp9SLk2-py3.8/bin/python
$ poetry shell
Spawning shell within /home/lefitz/.cache/pypoetry/virtualenvs/project-Clp9SLk2-py3.8
$ . /home/lefitz/.cache/pypoetry/virtualenvs/project-Clp9SLk2-py3.8/bin/activate
(project-Clp9SLk2-py3.8) $ which python
python: aliased to /usr/bin/python3
```

Running this from `bash` works just fine, so this might be something to check for `zsh` users.

**Comment by joelb123** [comment]
Can you elaborate on how you got things to work just fine from bash?  Neither simply running bash from inside a zsh session nor using "cash -z /bin/bash" and starting a new window works for me.  In both cases, "which python" reports the virtualenv python properly but sys.prefix points at the system python:
`$ poetry shell
Spawning shell within /Users/jb/Library/Caches/pypoetry/virtualenvs/mypackage-iQNcg5TA-py3.8

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
bash-3.2$ . /Users/jb/Library/Caches/pypoetry/virtualenvs/mypackage-iQNcg5TA-py3.8/bin/activate
(svante-iQNcg5TA-py3.8) bash-3.2$ python -c "import sys; print(sys.prefix)"
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8
(mypackage-iQNcg5TA-py3.8) bash-3.2$ echo $SHELL
/bin/bash
`

The continual nagging about the default shell caused me to change to zsh to begin with.  There are many advantages to develop in a default environment.

**Comment by sinoroc** [comment]
@lefi7z 

> ```
> (project-Clp9SLk2-py3.8) $ which python
> python: aliased to /usr/bin/python3
> ```

Do you have an hard-coded alias somewhere? What does the output of `alias` give you? (I am thinking in bash, I don't know exactly how it is in zsh, but probably similar.)

**Comment by joelb123** [comment]
No, my installation is clean.

I just spent a good deal of time blowing away and re-installing the very many stateful things in my installation including:

- ~.profile, zsh and bash rc's
- /usr/bin/python3
- Cruft from non-command-line Xcode left behind
- Command-line Xcode in /Library/Developer
- ~/.poetry installation
- ~/Library/Caches/pypoetry

I then rebooted and in a zsh window reinstalled command-line Xcode, poetry, and the poetry virtualenv.  

The same problem still happens:
`jb@jbmac2 mypackage % poetry shell
Spawning shell within /Users/jb/Library/Caches/pypoetry/virtualenvs/mypackage-iQNcg5TA-py3.8
Restored session: Fri Apr 30 11:42:39 MDT 2021
jb@jbmac2 mypackage % . /Users/jb/Library/Caches/pypoetry/virtualenvs/mypackage-iQNcg5TA-py3.8/bin/activate
(mypackage-iQNcg5TA-py3.8) jb@jbmac2 mypackage % which python
/Users/jb/Library/Caches/pypoetry/virtualenvs/mypackage-iQNcg5TA-py3.8/bin/python
(mypackage-iQNcg5TA-py3.8) jb@jbmac2 mypackage % python -c "import sys; print(sys.prefix)"
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8`

The output of alias is:
`% alias
run-help=man
which-command=whence
`

So what is your assertion that a clean installation works under bash?  When I try bash with a clean installation, I have the same problem with sys.prefix not getting set properly.  However, I have not ever seen a "which python" that reports the alias to /usr/bin/python3 that you see.

**Comment by sinoroc** [comment]
@joelb123 My comment was targeting @lefi7z specifically.

I don't know zsh and I don't have it installed to test this, but this [page](https://aviaryan.com/blog/python-mac-setup) seems to confirm my suspicion. When you see the output `python: aliased to /usr/bin/python3` it means that there is a hard-coded alias. And if the behavior is the same as I recall it in bash, then it does not matter if a virtual environment is activated or not, typing `python` will always use the defined alias (not what is set on `PATH`). In general it is such a bad idea to overshadow an existing binary/command with an alias to something else, even more so with python.

@joelb123 I have no idea how to help you.

**Comment by joelb123** [comment]
@sinoroc, thanks for responding, but I think you're misunderstanding me on the critical point.

I never see the output `python: aliased to /usr/bin/python3`, although you and @lefi7z do, but I do still have the sys.prefix error.  Therefore I conclude the alias artifact that is neither a symptom of, nor causative of, the sys.prefix problem.  I don't have any aliases installed that Apple doesn't ship.  

I'm inclined to ignore any directions that begin with "first install homebrew" or "first install conda", unless the vendor-supplied python is hopelessly mangled (as was Apple's 2.X the last time I tried it).  Installing a complex environment puts a burden on downstream users that I can't bring myself to accept when I'm testing installation of my software.

My guess is that the problem is arising from either something a bit odd with the way the Xcode command-line library is installed with `\usr\bin\python3` being a shell that checks for installation of Xcode command-line.  Whatever the problem is, manual activation doesn't cause a problem but `poetry shell` does.

**Comment by lefi7z** [comment]
@sinoroc Yes, you're completely right, there was a hardcoded alias involved. Thanks for the hint! After removing this non-sense, spawning a `poetry shell` worked as expected. The name resolution should be done by soft-links in the `/usr/bin` directory.

**Comment by nothead31** [comment]
I'm having this same issue on Poetry 1.1.7, however I don't have any aliases beyond what my terminal set up by default (some ls and grep shortcuts). I'm using Ubuntu 21.04. Using `poetry run`, `python -m module`, `pytest`, or any other method of running a module gives errors related to missing imports. 

Running `poetry install` says all imports are properly installed, and running `pip list` shows that all the dependencies are installed. If I exit the poetry shell and run `pip list` it shows a different list entirely, which does not include my dependencies, which I take to indicate that the virtual environment is working for everything except actually executing modules. I even tried removing the environment with `poetry env remove` and remaking one with `poetry shell` followed by `poetry install` to see if it was just a corrupted environment, but that failed to resolve the issue.

**Comment by wonderchang** [comment]
> So yeah, for some reason, the virtual environment is setting correctly with `poetry run` but not with `poetry shell`.

I've got the same problem too. My information:

  - OS version and name: macOS Big Sur 11.5.1 (default python install v3.8.12)
  - Poetry version: 1.1.10

**Comment by mote** [comment]
Also seeing this. My situation looks the same as joelb123.

zsh
poetry 1.1.11
python 3.8.2
Big Sur 11.6.1
