### ISSUE TITLE
poetry install fails

### ISSUE THREAD

**Issue by Dragonlord1005** [python-poetry/poetry#3918]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows 10 Pro 20H2
- **Poetry version**: 1.1.5
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/Dragonlord1005/362a57a757a1d3a67377648cacd419fd

## Issue

Poetry install won't install, after checking the error the folder located in AppData/local/pypoetry doesn't even exist, I used the windows PowerShell method on a non-admin account, here is the log I get

C:\Users\user\Documents\GitHub\Bettery-python-testing>poetry install

  EnvCommandError

  Command C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\better-python-testing-GjVyA-0D-py3.8\Scripts\python.exe - errored with the following return code 1, and output:
  The system cannot find the path specified.
  input was : import sys

  if hasattr(sys, "real_prefix"):
      print(sys.real_prefix)
  elif hasattr(sys, "base_prefix"):
      print(sys.base_prefix)
  else:
      print(sys.prefix)

  at ~\.poetry\lib\poetry\utils\env.py:1074 in _run
      1070│                 output = subprocess.check_output(
      1071│                     cmd, stderr=subprocess.STDOUT, **kwargs
      1072│                 )
      1073│         except CalledProcessError as e:
    → 1074│             raise EnvCommandError(e, input=input_)
      1075│
      1076│         return decode(output)
      1077│
      1078│     def execute(self, bin, *args, **kwargs):

The only reason I can think of that could cause this is a failed installation of poetry itself, I have attempted to reinstall it twice and I still get the error

**Comment by laggardkernel** [comment]
Installation failed on macOS as well.

```
❯ POETRY_HOME= /usr/local/bin/python3 install-poetry.py
Retrieving Poetry metadata

# Welcome to Poetry!

This will download and install the latest version of Poetry,
a dependency and package manager for Python.

It will add the `poetry` command to Poetry's bin directory, located at:

/Users/username/Library/Python/3.9/bin

You can uninstall at any time by executing this script with the --uninstall option,
and these changes will be reverted.

Installing Poetry (1.1.6): Done

Poetry (1.1.6) is installed now. Great!

To get started you need Poetry's bin directory (/Users/username/Library/Python/3.9/bin) in your `PATH`
environment variable.

Add `export PATH="/Users/username/Library/Python/3.9/bin:$PATH"` to your shell configuration file.

Alternatively, you can call Poetry explicitly with `/Users/username/Library/Python/3.9/bin/poetry`.

You can test that everything is set up by executing:

`poetry --version`
```

The target of `/Users/username/Library/Python/3.9/bin/poetry` doesn't exist. There's an venv `/Users/username/Library/Application Support/pypoetry/venv`, but no poetry installed within.

I'll stick with the old `get-poetry.py`, it just works. And `POETRY_HOME` is supported by it now.

**Comment by Dragonlord1005** [comment]
Recently tried using the prerelease, still didn’t work, went as far as deleting all the modules on my system, no change

**Comment by Dragonlord1005** [comment]
Managed to find a fix, use pyenv.
