### ISSUE TITLE
Automatically make a github release when running poetry publish

### ISSUE THREAD

**Issue by aahnik** [python-poetry/poetry#3925]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

When we run `poetry publish` it uploads all the builded files to PyPI. 

It would be great, if a github release was also created, with the build files attached.

**Comment by abn** [comment]
This might not be something that we would consider for the core project. However, this might be a reasonable plugin if the community has an appetite for it.

**Comment by aahnik** [comment]
thanks.

I got a cool idea from seeing the Makefile in the poetry's repo.

I could use  github cli for my use case.

`gh release create` is perfect for my purpose.

i could include the multiple commands in my Makefile, and just run `make release`.
