### ISSUE TITLE
The version command should increment the version in all files instead of only pyproject.toml

### ISSUE THREAD

**Issue by aahnik** [python-poetry/poetry#3926]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

![poetry_version_patch](https://user-images.githubusercontent.com/66209958/114415665-86606f80-9bcd-11eb-86a7-3a333dedbea4.gif)

running `poetry version patch` does not update version string in `__init__.py` files.

poetry would be more wholesome if it did so. I am aware of [bumpversion](https://github.com/c4urself/bump2version), but having version management, natively in poetry would be awesome.

**Comment by finswimmer** [comment]
Hello @aahnik,

this has been asked before: https://github.com/python-poetry/poetry/issues/144

Use `importlib.metadata` (`importlib_metadata` for python < 3.8): https://github.com/python-poetry/poetry/issues/1036#issuecomment-489880822

fin swimmer
