### ISSUE TITLE
Poetry install with path dependencies and entry points is unable to load the package

### ISSUE THREAD

**Issue by kalyangvs** [python-poetry/poetry#3930]
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Issue

If there are path dependencies and an entry point present as poetry plugin, the entry point is unable to be loaded.

```bash
poetry new aa
poetry new bb
poetry new cc
cd cc
sed -i  '/\python*/a  aa = {path = "../aa"} \nbb = {path = "../bb"}' pyproject.toml
echo '
[tool.poetry.plugins."service"]
"cc" = "cc.service:CCService"' >> pyproject.toml
poetry install
```

In python:
```python
import pkg_resources
for entry_point in  pkg_resources.iter_entry_points("service"):
    service = entry_point.load()
```
results in `pkg_resources.extern.packaging.requirements.InvalidRequirement: Invalid URL: ../aa`

Please look into the issue.

**Comment by gvskalyan** [comment]
The current workaround is to re-install the packages using pip by removing path dependencies from toml file, is there a clean solution to this?
@finswimmer @abn

**Comment by finswimmer** [comment]
Hello @kalyangvs,

you haven't come back to this issue for a long while. So I assume this is solved in the meantime and I can close this ticket.

Feel free to leave a comment if you disagree.

fin swimmer
