### ISSUE TITLE
Equivalent of pip --force-reinstall

### ISSUE THREAD

**Issue by zhzhang** [python-poetry/poetry#3931]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

Does poetry have (or have a roadmap for) the `--force-reinstall` feature in pip?
My use case is iterating on a library locally, and reinstalling it frequently to test my changes in a separate poetry project that contains a client application that's using the library I'm developing.
The current process of `remove` and `install` removes and reinstalls the dependencies, which takes a long time. It would be better to have a `--force-reinstall` flag like in pip that just installs the contents of the library without touching the dependencies.

**Comment by abn** [comment]
I don't think this is required. `poetry install` will, by default, "reinstall" the root project. And note that the project is installed as an editable install. This means, the only scenario where you might need to reinstall is in cases where console scripts for the project have changed, metadata for the project has changed and/or new paths were added to the project (packages).

**Comment by zhzhang** [comment]
I'm finding that that's not the case as far as my usage goes. My steps are:
- and a print statement in to `mylibrary.mymodule.main`
- run `poetry update ../../mylibrary` from a test project. This prints `No dependencies to install or update`
- run `poetry run python -m mylibrary.mymodule.main`. This does not print the new message.
- Go to `mylibrary` and upgrade the patch version by 1.
- run `poetry update ../../mylibrary` from a test project. This prints `Package operations: 0 installs, 1 update, 0 removals`
- run `poetry run python -m mylibrary.mymodule.main`. This does print the new message.

So this suggests to me that unless the version number changes, the root project is not reinstalled. Upgrading my patch version to force reinstalls during dev is not a terrible state to be in, but it does add an extra step (and an extra source of error if I forget to drop the patch version counter back down before deploying) to my process.

**Comment by abn** [comment]
@zhzhang Seems you are instaling a local path dependency. My statement was regarding the root project, ie. the current project managed by poetry.

You can install the local library path as an [editable dependency](https://python-poetry.org/docs/dependency-specification/#path-dependencies), ie. `{ ...., develop = true }`.

**Comment by zhzhang** [comment]
Nice! Thanks for the pointer! Only suggestion is to maybe add a flag for `develop` or `editable` under the `poetry add` command. Will close the issue.
