### ISSUE TITLE
install: ui does not update progress/completion

### ISSUE THREAD

**Issue by abn** [python-poetry/poetry#3934]
The UI for `1.2.0a0` (master version as of writing this comment) is whack.
<img width="1472" alt="Screen Shot 2021-04-10 at 7 06 50 PM" src="https://user-images.githubusercontent.com/66848002/114289833-e9b49b00-9a2f-11eb-8a26-acead18e6caa.png">
It just stays at "installing"

_Originally posted by @ThatXliner in https://github.com/python-poetry/poetry/issues/3852#issuecomment-817234844_

Also posted in https://github.com/python-poetry/poetry/issues/2918#issuecomment-816884068 by @fredrikaverpil 

> As you can see, that last time the output was very messy... I'm including a screenshot. Maybe this was because I was mixing poetry 1.1.5 and poetry@3900?
> 
> ![image](https://user-images.githubusercontent.com/994357/114226521-f2479b80-9973-11eb-84db-3580d7320b04.png)
> 

Relates-to: #3881

**Comment by ThatXliner** [comment]
Both of us were mixing poetry 1.1.5 and the master version. Probably an issue with combining them.

**Comment by lafrenierejm** [comment]
Anecdotally, current master c1475a0b6dd6f4a3e99112cc36b8c0d1024e4048 is working fine for me:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/11155300/173196284-fc344b1e-03de-4629-9f4c-5268539cd873.png">

**Comment by lafrenierejm** [comment]
@abn Is there anything specific you'd like to see before this can be considered closed?

**Comment by jeffwidman** [comment]
This is one of the last two remaining issues on the `1.2` release milestone, but users are reporting current `master` works fine... is it still blocking the `1.2` release?

**Comment by ThatXliner** [comment]
Fixed now
