### ISSUE TITLE
Poetry pulling in windows-only dependency causing conflicts

### ISSUE THREAD

**Issue by jtratner** [python-poetry/poetry#3935]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version. - poetry 1.1.5
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option). - included in gist

- **OS version and name**: macOS Catalina - 10.15.7 
- **Poetry version**: 1.1.5 
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: [pyproject.toml](https://gist.github.com/jtratner/160fb6790897446546aa9885c5a9fffe)

## Issue

To reproduce:

```
# add pyproject.toml from gist
poetry lock
```

dxpy has a windows-only dependency on a very old version of colorama (from 2014 :O ). For some reason when poetry attempts to lock with dxpy, it picks up the windows-only colorama and pyreadline dependencies.  For me, ideal would be to not include windows dependencies if not locking on windows.  Not sure whether poetry attempts to be cross-platform or not.

Also going to try to get dxpy developers to unpin colorama, but figured I'd take both approaches!

Thanks for the great tool :)

**Comment by finswimmer** [comment]
Poetry doesn't care about your current environment. It creates a universal lock file. See https://python-poetry.org/docs/faq/#why-is-poetry-telling-me-that-the-current-projects-python-requirement-is-not-compatible-with-one-or-more-packages-python-requirements.

You can help Poetry to find a solution if it cannot one, by using [environment markers for dependencies](https://python-poetry.org/docs/dependency-specification/#using-environment-markers) or use [multiple constraints](https://python-poetry.org/docs/dependency-specification/#multiple-constraints-dependencies).
