### ISSUE TITLE
`poetry env list` does not list in-project environment even though it is currently activated

### ISSUE THREAD

**Issue by karrtikr** [python-poetry/poetry#3939]
Hi VSCode Python extension dev here 👋

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows_NT x64 10.0.19042
- **Poetry version**: 1.1.5
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/karrtikr/cfa99d02f962431a491088d86fd30146

## Issue

Unless the `virtualenvs.in-project` is explicitly set to `true`, `poetry env list` does not display local `.venv` named environment. If setting is not set to true, poetry will use the virtualenv from the `.venv` directory when one is available as stated in [the docs](https://python-poetry.org/docs/configuration/#virtualenvsin-project-boolean). In that case I would also expect `poetry env list` to contain the active poetry environment, which is the local `.venv`.

So it seems that our extension cannot rely on `poetry env list` to discover all poetry environments https://github.com/microsoft/vscode-python/issues/8372 for a project atm.

**Comment by StigKorsnes** [comment]
I have it explicitly set to true (AppData/Roaming/pypoetry/config.toml). Further to the mentioned issue, the select interpreter command does not display the environment even if activated, and same goes for jupyter notebooks (Select Kernel). Opening up a new blank notebook, it displays the activated venv under the kernel field, but is lost once you save. However, if you open up a new blank workbook and run something before you save, it remembers. VsCode 1.56.0
