### ISSUE TITLE
Change to installation script causes exit code 1 when the correct version is already installed

### ISSUE THREAD

**Issue by vbersier** [python-poetry/poetry#3942]
See commit https://github.com/python-poetry/poetry/commit/cd8ac0d229e8fbd181725f1c9397ace003145ca1

My CI reports a failure when trying to install poetry through the documented command (curl the script and execute with python) because the correct version was already installed previously.

The script reports "Latest version already installed." and exits with 1.

Having the correct version should not cause an exit code > 0.

As a temporary workaround, using the `--force` option allows the installation to happen without a bad exit code.

**Comment by jacek-jablonski** [comment]
Same here, this change forces change of hundreds of GitHub actions scrips.

**Comment by vbersier** [comment]
Thanks for the quick fix @abn

**Comment by abn** [comment]
Can thank @stephsamson for the work :)  I just pushed buttons!

**Comment by blueyed** [comment]
Sorry for the trouble - only noticed it by now that it has been reverted..

https://github.com/python-poetry/poetry/pull/4028 fixes it.
