### ISSUE TITLE
EnvCommandError with multiple Python installations

### ISSUE THREAD

**Issue by RashiqAzhan** [python-poetry/poetry#3948]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: 10.0.19041 Build 19041 + Windows 10 Enterprise
- **Poetry version**: 1.1.5
- **Link of a [Gist](https://gist.github.com/RashiqAzhan/c3089eae40c35e5a6d6964ec82b89660)**: 

## Issue

This is a new project and I have been getting this `EnvCommandError` whenever I run the command `poetry install`.
I have used the `poetry env use C:\Python39\python.exe` to specify the location of my Python 3.9 installation location.

Terminal Output:
```py
  EnvCommandError

  Command ...\.venv\Scripts\pip.exe install --no-deps ...\AppData\Local\pypoetry\Cache\artifacts\60\33\fe\95dd0fc907c4928d9faa8b47ae9cac8bd9ef64deb0b7911a520cae9404\BeautifulSoup-3.2.1.tar.gz errored with the following return code 1, and output:
  Processing ...\appdata\local\pypoetry\cache\artifacts\60\33\fe\95dd0fc907c4928d9faa8b47ae9cac8bd9ef64deb0b7911a520cae9404\beautifulsoup-3.2.1.tar.gz
      ERROR: Command errored out with exit status 1:
       command: '...\.venv\Scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'...\\AppData\\Local\\Temp\\pip-req-build-sx1pybj6\\setup.py'"'"'; __file__='"'"'...\\AppData\\Local\\Temp\\pip-req-build-sx1pybj6\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base '...\AppData\Local\Temp\pip-pip-egg-info-aoghjj5v'
           cwd: ...\AppData\Local\Temp\pip-req-build-sx1pybj6\
      Complete output (6 lines):
      Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "...\AppData\Local\Temp\pip-req-build-sx1pybj6\setup.py", line 22
          print "Unit tests have failed!"
                ^
      SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Unit tests have failed!")?
      ----------------------------------------
  WARNING: Discarding file:///.../AppData/Local/pypoetry/Cache/artifacts/60/33/fe/95dd0fc907c4928d9faa8b47ae9cac8bd9ef64deb0b7911a520cae9404/BeautifulSoup-3.2.1.tar.gz. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command
output.
  ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.


  at ~\AppData\Roaming\Python\Python310\site-packages\poetry\utils\env.py:1074 in _run
      1070│                 output = subprocess.check_output(
      1071│                     cmd, stderr=subprocess.STDOUT, **kwargs
      1072│                 )
      1073│         except CalledProcessError as e:
    → 1074│             raise EnvCommandError(e, input=input_)
      1075│
      1076│         return decode(output)
      1077│
      1078│     def execute(self, bin, *args, **kwargs):
```

One thing I have noticed is that `Python310` shows up in the terminal output. Not sure why this appears even after specifying the python version. I have confirmed the installation of my Python 3.9 is not corrupted as I can use it for a brand new project using pip.

Any guidance is appretiated.

**Comment by abn** [comment]
Looks like one of your dependencies is requesting [`beautifulsoup (3.2.1)`](https://pypi.org/project/BeautifulSoup/), which does not support Python 3.

I would recommend adding the dependencies one at a time, and perhaps also using better constraints for each dependency.

**Comment by finswimmer** [comment]
Hello @RashiqAzhan,

you haven't come back to this issue for a long while. So I assume this is solved in the meantime and I can close this ticket.

Feel free to leave a comment if you disagree.

fin swimmer
