### ISSUE TITLE
If installation of a dependency fails, it remains in the lock file until it is updated with `poetry lock`

### ISSUE THREAD

**Issue by 13steinj** [python-poetry/poetry#395]
- [X] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows 10 64-bit
- **Poetry version**: 0.11.4
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: not really applicable

## Issue
When installation of a dependency fails, such as for example, it requires a system component that you do not have to complete the build process, the package/hash combo is still added to the pyproject.lock file, even though the dependency has not installed.

The pyproject.toml file *does not* incorrectly retain the dependency.

Example: `poetry add -D yappi` without the MSVC++ 14.0 build tools causes a VenvCommandError. This is fine and expected. However, after running this, the following lines was added to my pyproject.lock:

```toml
[[package]]
category = "dev"
description = "Yet Another Python Profiler"
name = "yappi"
optional = false
platform = "UNKNOWN"
python-versions = "*"
version = "0.98"
```

and 

```
yappi = ["5f657129e1b9b952379ffbc009357d0dcdb58c50f3bfe88ffbb992e4b27b263c"]
```

My pyproject.toml was unaffected, as mentioned.

Running `poetry lock` clears this anomaly.

**Comment by sdispater** [comment]
I agree this is an undesired behavior.

The installer should be more clever when rollbacking if an error occurs during installation.

**Comment by wagnerluis1982** [comment]
I can reproduce this bug on latest (1.2.1). I tried to install a difficult dependency on Linux, called `pyaudio`.

```console
$ poetry add pyaudio
Using version ^0.2.12 for PyAudio

Updating dependencies
Resolving dependencies... (0.5s)

Writing lock file

Package operations: 1 install, 0 updates, 0 removals

  • Installing pyaudio (0.2.12): Failed

...stack tracebacks...
```

```console
$ git st -s
 M poetry.lock
```
```patch
$ git diff
diff --git a/poetry.lock b/poetry.lock
index f1d2d23..a26c47d 100644
--- a/poetry.lock
+++ b/poetry.lock
@@ -224,6 +224,17 @@ category = "dev"
 optional = false
 python-versions = ">=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*"
 
+[[package]]
+name = "PyAudio"
+version = "0.2.12"
+description = "Cross-platform audio I/O with PortAudio"
+category = "main"
+optional = false
+python-versions = "*"
```

**Comment by wagnerluis1982** [comment]
I probably can work to solve this issue.

**Comment by wagnerluis1982** [comment]
I opened a PR with a fix for this issue
