### ISSUE TITLE
Poetry reuses the same virtual environment for different projects

### ISSUE THREAD

**Issue by frafra** [python-poetry/poetry#3953]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **Poetry version**: https://github.com/python-poetry/poetry/commit/3a789a7a2d9d82d57d388957f70cc985fa19d22f

## Issue
```
for dir in dir1 dir2; do
    mkdir -p "$dir"/proj
    cd "$dir"/proj
    poetry new .
    poetry update
    poetry env info | grep Path
    poetry run python -c "import rpm"
    cd ../..
done
```

That is a problem, because you can use `poetry config virtualenvs.options.system-site-packages true` which would affect both projects

**Comment by finswimmer** [comment]
Hello @frafra,

please show us the output of your script and also your configs (`poetry config --list`). I cannot see the that poetry reuses a venv for different projects.

Thanks!

fin swimmer

**Comment by frafra** [comment]
I am sorry, but after reinstalling Poetry to the latest master commit I am unable to replicate reuse of environments across different projects, even if they both have the same folder name.
