### ISSUE TITLE
How to use --verbose in poetry run?

### ISSUE THREAD

**Issue by gc-ss** [python-poetry/poetry#3960]
Using poetry 1.1.4:

When using `--verbose` with `poetry run` I would expect to see some details like env. vars, and relevant context in which the `poetry run` is executed to show up so that I have more details to figure out why a certain `poetry run` fails.

However, when I try and place `--verbose` in these two ways, neither seems to work as expected although the `USAGE` docs as printed seems to suggest `--verbose` is supported:

`-vvv` to poetry:

```
  # poetry -vvv run bash
  USAGE
    poetry help [<command1>] ... [<commandN>]

  ARGUMENTS
    <command>              The command name

  GLOBAL OPTIONS
    -h (--help)            Display this help message
    -q (--quiet)           Do not output any message
    -v (--verbose)         Increase the verbosity of messages: "-v" for normal output, "-vv" for more verbose output and "-vvv" for debug
    -V (--version)         Display this application version
    --ansi                 Force ANSI output
    --no-ansi              Disable ANSI output
    -n (--no-interaction)  Do not ask any interactive question
```

`-vvv` to poetry run:

```
  # poetry run -vvv bash

    FileNotFoundError

    [Errno 2] No such file or directory

    at /usr/local/lib/python3.9/os.py:607 in _execvpe
         603│         path_list = map(fsencode, path_list)
         604│     for dir in path_list:
         605│         fullname = path.join(dir, file)
         606│         try:
      →  607│             exec_func(fullname, *argrest)
         608│         except (FileNotFoundError, NotADirectoryError) as e:
         609│             last_exc = e
         610│         except OSError as e:
         611│             last_exc = e
```
It seems to me that `poetry` is trying to run `-vvv` but the message:

`[Errno 2] No such file or directory`

does not give any context.

A properly implemented `--verbose` option could helpfully printout that information, the PATH and so on.

**Comment by sinoroc** [comment]
Duplicate: https://github.com/python-poetry/poetry/issues/2266

**Comment by abn** [comment]
Closing as this is a duplicate.
