### ISSUE TITLE
GitHub Actions CI failing with `[FileNotFoundError]'

### ISSUE THREAD

**Issue by joshmgrant** [python-poetry/poetry#3961]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 20.04
- **Poetry version**: 1.1.6
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://github.com/joshmgrant/corsica/blob/main/pyproject.toml

## Issue

When trying to install and execute poetry for use on a Github Actions pipeline, I am unable to run `poetry run pytest tests/unit` and get the following error from the console: 

```
Creating virtualenv corsica-LQJB_-y5-py3.8 in /home/runner/.cache/pypoetry/virtualenvs

  FileNotFoundError

  [Errno 2] No such file or directory: b'/snap/bin/pytest'

  at /opt/hostedtoolcache/Python/3.8.9/x64/lib/python3.8/os.py:601 in _execvpe
       597│         path_list = map(fsencode, path_list)
       598│     for dir in path_list:
       599│         fullname = path.join(dir, file)
       600│         try:
    →  601│             exec_func(fullname, *argrest)
       602│         except (FileNotFoundError, NotADirectoryError) as e:
       603│             last_exc = e
       604│         except OSError as e:
       605│             last_exc = e
Error: Process completed with exit code 1.
```

Let me know what else I can provide!

**Comment by abn** [comment]
```
Creating virtualenv corsica-LQJB_-y5-py3.8 in /home/runner/.cache/pypoetry/virtualenvs

```

This indicates that a virtual environment did not exist, and was created. Looks like `poetry install` was never run.

**Comment by joshmgrant** [comment]
This is exactly correct. Looks like poetry did install properly but I didn't call `poetry install`. Thanks for the response!
