### ISSUE TITLE
What's the proper `poetry add` syntax with `develop=true`?

### ISSUE THREAD

**Issue by gc-ss** [python-poetry/poetry#3962]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

Using poetry 1.1.4:

What's the proper `poetry add` syntax such that `develop=true` gets added in the TOML file?

For example, what do I type in addition to `poetry add ../../my_lib` so that `develop=true` gets added in the TOML file and I see:

```
[tool.poetry.dependencies]
my_lib = {path = "../../my_lib", develop = true}
```

**Comment by finswimmer** [comment]
Hello @gc-ss,

this has been asked before in https://github.com/python-poetry/poetry/issues/3220, https://github.com/python-poetry/poetry/issues/3004

PRs are on the road: https://github.com/python-poetry/poetry/pull/3250, https://github.com/python-poetry/poetry/pull/3940

fin swimmer
