### ISSUE TITLE
What's the proper "poetry add" syntax to add a git repo with "/" in the branch name?

### ISSUE THREAD

**Issue by gc-ss** [python-poetry/poetry#3963]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

`poetry add` allows the following syntax:

`poetry add git+https://github.com/python-poetry/poetry.git#develop`

Now, what if the branch has a '/' in it like `develop/dev-candidate-1` vs just `develop`, as in:

`poetry add git+https://github.com/python-poetry/poetry.git#develop/dev-candidate-1`

**Comment by finswimmer** [comment]
Hello @gc-ss,

> poetry add git+https://github.com/python-poetry/poetry.git#develop/dev-candidate-1

that's exactly how it works. Everything that comes after the `#` is used to identify the branch.

fin swimmer
