### ISSUE TITLE
The following sequence leaves folders behind in site-packages (`master`)

### ISSUE THREAD

**Issue by abn** [python-poetry/poetry#3964]
On my machine, the following sequence leaves folders behind in site-packages:

Install `b` from path:

```bash
$ poetry@3940 add ../b/

Updating dependencies
Resolving dependencies... (0.1s)

Writing lock file

Package operations: 1 install, 0 updates, 0 removals

  • Installing b (0.0.0 /home/fredrik/code/repos/b): Building...
```

Then I wanted to see what happens if I try to add it again but with the `--editable` arg:

```bash
$ poetry@3940 add --editable ../b/

Updating dependencies
Resolving dependencies... (0.1s)

Writing lock file

Package operations: 0 installs, 1 update, 0 removals

  • Updating b (2.1.3.dev0+g77bcc5e.d20210417114942 /home/fredrik/code/repos/b -> 0.0.0 /home/fredrik/code/repos/b)
```

Finally uninstalling `b`:

```bash
$ poetry@3940 remove b
Updating dependencies
Resolving dependencies... (0.1s)

Writing lock file

Package operations: 0 installs, 0 updates, 1 removal

  • Removing b (0.0.0 /home/fredrik/code/repos/b)
```

But unfortunately, `b` was not completely removed, likely due to the fact that I was able to run `poetry add` twice:

![image](https://user-images.githubusercontent.com/994357/115108952-7650e300-9f73-11eb-9efe-7d460854e4c8.png)

And now it seems the .venv is b0rked, as there is suddenly a `None` package:

```bash
$ poetry@3940 show

  TypeError

  expected string or bytes-like object

  at ~/.local/pipx/venvs/poetry@3940/lib/python3.9/site-packages/poetry/core/utils/helpers.py:27 in canonicalize_name
       23│ _canonicalize_regex = re.compile(r"[-_]+")
       24│
       25│
       26│ def canonicalize_name(name: str) -> str:
    →  27│     return _canonicalize_regex.sub("-", name).lower()
       28│
       29│
       30│ def module_name(name: str) -> str:
       31│     return canonicalize_name(name).replace(".", "_").replace("-", "_")
```

_Originally posted by @fredrikaverpil in https://github.com/python-poetry/poetry/pull/3940#issuecomment-821798593_

**Comment by abn** [comment]
This is likely related to #3900.

**Comment by fredrikaverpil** [comment]
I don't know if you want to do it like this, but at least this patch actually fixes the issue. The solution was to add the `direct_url.json` to `RECORD`, after the .json file was created.

https://github.com/python-poetry/poetry/compare/master...fredrikaverpil:patch-1

But something tells me importlib is supposed to scan for this file, and add it to RECORD if it detects it?
I've [reached out here](https://discuss.python.org/t/pep-610-recording-the-origin-of-distributions-installed-from-direct-url-references/1535/72?u=fredrikaverpil) and asked how this file should be added to RECORD.
