### ISSUE TITLE
Autogeneration of system specific installation artifacts

### ISSUE THREAD

**Issue by kishaningithub** [python-poetry/poetry#3968]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

This feature request is very much inspired the super awesome [goreleaser tool](https://goreleaser.com/) tool which is present for [go lang](https://golang.org/)

As of now poetry super fast package publishing to pypi. We can take 1-Step further i.e. auto generation of system specific installation artifacts. For example
- Create [Homebrew](https://brew.sh/) taps
- Create Linux packages(Snaps, debs, rpms etc)
- Docker images

**Comment by kishaningithub** [comment]
I also happened to read this nice gist on the publishing python apps across platforms

https://gist.github.com/ForgottenUmbrella/ce6ecd8983e76f6d8ef47e07240eb4ac#notlinux

I really feel poetry can simplify this process just like the [goreleaser tool](https://goreleaser.com/) for golang

**Comment by neersighted** [comment]
Closing as out of scope for the core Poetry project -- this kind of functionality makes more sense as a plugin in the long run.
