### ISSUE TITLE
Add --lock option to "poetry remove"

### ISSUE THREAD

**Issue by agronholm** [python-poetry/poetry#3971]
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

Poetry already has `add --lock` and `update --lock`. In order to have a workflow that does not involve virtualenvs, this is a missing piece.

**Comment by v-goncharenko** [comment]
Yes, this is very handy functionality which `poetry` currently lacks
