### ISSUE TITLE
Private PyPi repository dependencies only given precedence if more up-to-date than public PyPi.

### ISSUE THREAD

**Issue by OrEisenberg** [python-poetry/poetry#3974]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS Big Sur 11.2.3
- **Poetry version**: 1.1.5
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: Sorry, I work for a company with pretty stringent nondisclosure laws (and as you'll see in the description of the issue, there is some sensitive info in my `pyproject.toml`, but I'd be happy to answer an questions which you might have about it's configuration in the abstract, though I doubt you'll have any.

## Issue
I'm using `poetry`'s private PyPi repo functionality and have configured a project to search both a private PyPi and the public one for dependencies. I've done so by including the following section into the `pyproject.toml` of the package I'm attempting to install.

```
[[tool.poetry.source]]
name = "private-pypi"
url = "url.for.private.pypi.com"
```

My issue concerns the logic behind which package is installed when there exist packages on both the private PyPi repo and the public one that are of the same name. For example, suppose that my project has a single dependency named `dep` and that there exists a package called `dep` in both the public PyPi and in my private PyPi. Suppose furthermore that the latest version of `dep` on the public PyPi is `1.0`, while the latest version on my private PyPi is `0.0`. Then if the dependencies for my project are listed in my `pyproject.toml` as

```
[tool.poetry.dependencies]
python = "~3.8"
dep = "*"
```

then `poetry` installs version `1.0` of `dep` from the public PyPi! Meanwhile, if my `pyproject.toml` lists dependencies

```
[tool.poetry.dependencies]
python = "~3.8"
dep = "0.0"
```
then even if the public PyPi repo also has a version `0.0` available for `dep`, it installs my version. So it seems to me that the logic which poetry uses for which package to install is "install the most up-to-date relevant version with a preference for the private repository". 

Now, I appreciate that this may just be a simple misunderstanding, but I was under the impression that the logic was more along the lines of "install from the repository with the highest preference the most up-to-date relevant version". I.e., determine which repository to install from *first*, while being agnostic as to which repository has the more up-to-date version available globally, then pick the most up-to-date version from that repository.

If this is an intended feature, could you please provide me some recommendations as to how I might be able to specify a dependency along the lines of "install the most recent version of such-and-such package from my private repository, disregarding the versions available on the public PyPi"? I've been struggling to find a way to have my cake and eat it to vis-a-vis naming my packages what I want, versioning them as I like, and still having access to the public PyPi in my installs. 

Thanks so much in advance!

**Comment by jschlyter** [comment]
I'm having the same issue, with the end result that private repositories does not work at all for me.

**Comment by Ovsyanka83** [comment]
I suggest using "source" to solve this problem:
https://python-poetry.org/docs/repositories/#secondary-package-sources

**Comment by dimbleby** [comment]
this was always working as designed, the recent introduction of `explicit` and `supplemental` repositories offers new ways to handle such cases.

(But a better answer is: don't publish private packages with the same names as public packages)

please close
