### ISSUE TITLE
Export as setup.py

### ISSUE THREAD

**Issue by BD103** [python-poetry/poetry#3975]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

This feature would enable exporting a `pyproject.toml` file to a `setup.py` file. I found that locking the `pyproject.toml` file gives the temp file and a `setup.py`. Running this command would follow the same process, but would not remove `setup.py`.

```console
$ poetry export -f setup.py
# -*- coding: utf-8 -*-
from setuptools import setup

packages = \
['pkg']

package_data = \
{'': ['*']}

install_requires = \
['dependency>=1.0.0<2.0.0']

setup_kwargs = {
  'name': 'pkg',
  ...
}

setup(**setup_kwargs)
```

**Comment by abn** [comment]
This is not something that we will support in poetry. This was discussed a few times before, see the following for context.

- https://github.com/python-poetry/poetry/pull/3736#issuecomment-803664855
- https://github.com/python-poetry/poetry/issues/761#issuecomment-803487606
