### ISSUE TITLE
How to use poetry when developing a package

### ISSUE THREAD

**Issue by FenryrMKIII** [python-poetry/poetry#3979]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

I am currently developing a package with poetry. My package uses a structure such as this one : 
``` bash
--my_package
   --bin
   --src
      --my_package
```

I have well understood the use of Poetry I think. I also succeeded in installing the package in a test environment. In my `.toml` file I have the following lines to handle my particular hierarchy: 
``` python
packages = [ 
	{include = 'my_package', from='src'}
	]
```

What I struggle with is how to use Poetry during development for my case. 

Indeed, in my case, I have a `bin` directory. 
This directory contains launch scripts that needs to import my_package to call specific functions/methods.  The idea is to provide the user with examples. 
I would like to be able to test my_package "online" along with the launch scripts without the need to use commands such as `poetry build/poetry install` in a separate test environments. 
And I don't see a clean way of making this work with poetry unless I modify the `sys.path` variable during development to include the `src` directory.
Does anyone have a clean way of handling such a use case ? Or am I missing something ?

**Comment by FenryrMKIII** [comment]
To try to make things work, I stumbled across this discussion #3962 and thought this might be the solution.

I created a new virtual environment with poetry 

```bash
 poetry env use python
```
and spawned a new shell 
```bash
 poetry shell
```
Then I installed my package in this new environment :
```bash
 poetry install
```
which installed the dependencies and the package itself. 

I tested with 
```python
import my_package
```
and it works. It also automatically takes the updates to the package. All this without putting the following line in my toml file : 

```python
[tool.poetry.dependencies]
my_package = {path = "../../my_package", develop = true}
```
I don't understand why it works. But it works.

**Comment by gc-ss** [comment]
You found the solution.

You can now generate the `my_package = {path = "../../my_package", develop = true}` entry using the `--editable` option that was merged in this week.

**Comment by FenryrMKIII** [comment]
> You found the solution.
> 
> You can now generate the `my_package = {path = "../../my_package", develop = true}` entry using the `--editable` option that was merged in this week.

Hey thanks for the reply. But do you understand why it works without this line? That’s why I am bit puzzled :)

**Comment by finswimmer** [comment]
Hello @FenryrMKIII,

when you run `poetry install` these things happens:

1. create a venv if no one already exists or is activated
2. if no `poetry.lock` file exists: resolves your dependencies and write the result in the `poetry.lock`
3. install the packages locked in the poetry.lock
4. install the current project in an editable mode

Step 4 is the reasons why you have no problem to import your packages modules if you are in the activated environment.

fin swimmer
