### ISSUE TITLE
Option to use pip install --use-feature=in-tree-build

### ISSUE THREAD

**Issue by fx-kirin** [python-poetry/poetry#3982]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

https://github.com/pypa/pip/pull/9091

The option of `pip` `--use-feature=in-tree-build` will be added on the version  `21.1`. 

I want to use it with `poetry` because of [this problem](https://github.com/pypa/pip/issues/9819).

**Comment by abn** [comment]
@fx-kirin how do you think this be used within the poetry context? Is this for cases where nested local path dependencies refer to relative paths within their own dependencies?

**Comment by fx-kirin** [comment]
I'm not sure what it should be because I"m not a heavy user of poetry. But I hope I can set an option with something like `poetry config` because I think normally, local packages doesn't need to be copied to temporary folder to build the package. 

Sorry I couldn't get the meaning of what you said "cases" exactcly. But if you use the relative path to outside of the package in `Cargo.toml`, it should be happened.

**Comment by fx-kirin** [comment]
`in-tree-build` is not default to pip.
