### ISSUE TITLE
Add a way to disable cache like PIP_NO_CACHE_DIR=off

### ISSUE THREAD

**Issue by awoimbee** [python-poetry/poetry#3997]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

### Use case
Building a container for a project with lots of big dependencies.

### The issue
We had >1GB of data in `~/.cache/pypoetry`

### The current solution
Run `rm -rf ~/.cache/pypoetry/` after each call to poetry

### The requested feature
A setting to disable cache completely, juste like we can use `PIP_NO_CACHE_DIR=off` for pip.
Poetry already has a setting for [cache-dir](https://python-poetry.org/docs/configuration/#cache-dir-string), `poetry config cache-dir /dev/null` doesn't work (`NotADirectoryError`).
Maybe we could set `cache-dir` to none or something like that ?

**Comment by abn** [comment]
We should really add `--no-cache | --disable-cache` options to commands that need them.

**Comment by mkniewallner** [comment]
Since #5519 has been merged and released in [1.2.0b2](https://github.com/python-poetry/poetry/releases/tag/1.2.0b2), I believe that this issue can be closed?
