### ISSUE TITLE
Use the requires-python metadata field from pyproject.toml

### ISSUE THREAD

**Issue by bolinocroustibat** [python-poetry/poetry#4001]
Now that [PEP 621](https://www.python.org/dev/peps/pep-0621) is final, wouldn't that make more sense to use the [requires-python metadata field](https://www.python.org/dev/peps/pep-0621/#requires-python) instead of `tool -> poetry -> dependencies -> python` in `pyproject.toml` for the project Python version(s)?

**Comment by finswimmer** [comment]
Hello @bolinocroustibat,

there is already a discussion about PEP 621 in https://github.com/python-poetry/poetry/issues/3332.

fin swimmer
