### ISSUE TITLE
Poetry does not store its own package information in poetry.lock

### ISSUE THREAD

**Issue by Teslafly** [python-poetry/poetry#4006]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

I recently debugged a problem where I needed to know what version of poetry generated a lockfile as the lockfile was broken.
Poetry does not seem to store it's own version information in the lockfile. As lockfile generation can change over versions, I think it would be a good idea to store the version of poetry used to generate the lockfile in the lockfile as well. This could also be used to prompt(or force) the user to regenerate the lockfile if it was generated by an older poetry version.

**Comment by abn** [comment]
Thank you for raising the issue. However, we track the lock file version already. https://github.com/python-poetry/poetry/blob/f23bd4a661d26cc493fd8940bce68888b94757aa/poetry.lock#L715

We do expect the lock file itself to be consistent as long as the lock file version is the same. I do not think adding the poetry version will add much. Given this, we might not consider this as a change at this time.

**Comment by Lexicality** [comment]
We are having problems where engineers working on our large repo have a variety of different poetry versions and get wildly different results for updating the lockfile which causes merge conflicts.
Here is an example:
```
$ poetry --version
Poetry version 1.1.6

$ poetry update affiliate_utils
Updating dependencies
Resolving dependencies... (1.6s)

Writing lock file

No dependencies to install or update

$ git diff --stat
 poetry.lock | 6 +++---
 1 file changed, 3 insertions(+), 3 deletions(-)

$ git restore .

$ pip install poetry==1.1.3
# ...

$ poetry --version
Poetry version 1.1.3

$ poetry update affiliate_utils
Updating dependencies
Resolving dependencies... (5.0s)

Writing lock file
 
No dependencies to install or update

$ git diff --stat
 poetry.lock | 969 ++++++++-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 1 file changed, 40 insertions(+), 929 deletions(-)
```

The lock version is 1.1 in both cases but we'd like a way to block changes like this

**Comment by finswimmer** [comment]
Poetry writes a comment like this to the lock file for some time now:

```
# This file is automatically @generated by Poetry 1.8.3 and should not be changed by hand.
```
