### ISSUE TITLE
Unable to update poetry

### ISSUE THREAD

**Issue by dakide** [python-poetry/poetry#4012]
Hello, I'm having trouble updating poetry. I am running Ubuntu 20.04 in wsl2.

I installed poetry using the command in this doc:
`curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python3 -`

The output was a success:
```
Installing Poetry (1.1.6): Done

Poetry (1.1.6) is installed now. Great!
```

I then ran `poetry self update` but I get an error that it was not installed the recommended way:
```

  RuntimeError

  Poetry was not installed with the recommended installer. Cannot update automatically.

  at ~/.local/share/pypoetry/venv/lib/python3.8/site-packages/poetry/console/commands/self/update.py:248 in _check_recommended_installation
      244│         current = Path(__file__)
      245│         try:
      246│             current.relative_to(self.home)
      247│         except ValueError:
    → 248│             raise RuntimeError(
      249│                 "Poetry was not installed with the recommended installer. "
      250│                 "Cannot update automatically."
      251│             )
      252│ 
```

What is the recommended way of installing poetry?

Thanks

**Comment by abn** [comment]
Hi @dakide. This is a side-effect of us deprecating the old method that used `get-poetry.py`. 

The new script (`install-poetry.py`) installs using a virtual env. This is not something 1.1 releases are aware of and hence the `poetry self update` commands do not work. This issue will go away once 1.2 is released and installed. 

Until 1.2 is stable, the `get-poetry.py` is what you'd want to use if you plan on using the `self upgrade` command. 

Alternatively, consider using `pipx` to manage poetry installation.
