### ISSUE TITLE
Ability to change poetry downloader backend to conda or mamba

### ISSUE THREAD

**Issue by kitmonisit** [python-poetry/poetry#4020]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

Hi everyone, I am trying to combine usage of pyenv, conda, and poetry.  I need `pyenv` for clean management of python versions.  I need `conda` because `rapidsai` is easily downloadable from there.  I need `poetry`  for clean management of the project dependencies (for example `poetry show --tree`).

Instructions for installing the RAPIDS suite of machine learning libraries says

```sh
conda install rapids-blazing=0.19
```

All is well and good that way.

However I want to be able to keep a record of its dependency tree the way poetry does it. So I try:

```sh
poetry add rapids-blazing=0.19
```

Poetry cannot find `rapids-blazing`.  This is probably because poetry does not use conda to search for packages.

**Is it possible to change the poetry downloader backend to conda (or even better, `mamba`)?**

And getting ahead a little bit: `mamba` has `mamba repoquery depends --tree rapids-blazing`

**Comment by finswimmer** [comment]
Hello @kitmonisit,

this has been asked before, e.g. in https://github.com/python-poetry/poetry/issues/1904

But this is definitely out of scope for poetry (yet). conda has it's complete own ecosystem and it would require a lot of work to include it to poetry.

fin swimmer
