### ISSUE TITLE
Installer should exit non-zero in case of non-existent/invalid --version

### ISSUE THREAD

**Issue by blueyed** [python-poetry/poetry#4027]
`python get-poetry.py --version 0.12.34` should exit non-zero.

This apparently regressed in 23667d28a96cd [1].

1: https://github.com/python-poetry/poetry/commit/23667d28a96cdf62a83e944ac977e22d3ced7590#diff-952871ed95a893e0348aa1269bf15e689d18756657cfec5c7316d05e55eb6dc6R302

Ref: https://github.com/python-poetry/poetry/pull/378

Initially fixed in https://github.com/python-poetry/poetry/pull/3927, but incomplete and has been reverted therefore.

**Comment by neersighted** [comment]
Closing this issue as `get-poetry.py` is deprecated.
