### ISSUE TITLE
Poetry install fails to download new setuptools if 'system-site-packages' option enabled

### ISSUE THREAD

**Issue by vlad0337187** [python-poetry/poetry#4032]
- [ ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **Linux Mint 20.4**: 
- **git: master**: 
- **it doesn't depend on pyproject.toml** 

## Issue

Steps:
- use Linix Mint 20.4
- ensure python3 and python3-setuptools packages are installed. setuptools should have some updates on PyPi
- create new project with: `poetry init`
- enable system-site-packages: `poetry config virtualenvs.options.system-site-packages true --local`
- run `poetry install`
- see error: `Link object has no is_absolute attribute`

Reason:
- I think it appeared after some refactor
- `installation/executor.py` `Excecutor._download_link` sometimes can pass `Link` instance to `FileDependency.__init__`, which expects `Path` instance
- it can happen when `self._chef.get_cached_archive_for_link()` will return Link instance or None, but it wont be the same object as `link`

Fix:
- https://github.com/python-poetry/poetry/pull/4031

**Comment by dimbleby** [comment]
no debug output so hard to tell where this is happening, but `Chef.get_cached_archive_for_link()` now always returns `Path` rather than `Link` so this error has surely gone away.

**Comment by neersighted** [comment]
Agreed, this does not reproduce for me on 1.2.2.
