### ISSUE TITLE
Poetry install tries to update system packages is 'system-site-packages' option enabled

### ISSUE THREAD

**Issue by vlad0337187** [python-poetry/poetry#4033]
- [ ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **Linux Mint 20.4**: 
- **git: master**: 
- **doesn't depend on pyproject.toml file** 

## Issue

Steps:
- use Linix Mint 20.4
- ensure python3 and python3-setuptools packages are installed. setuptools should have some updates on PyPi
- create new project with: `poetry init`
- enable system-site-packages: `poetry config virtualenvs.options.system-site-packages true --local`
- apply fixes for issue: https://github.com/python-poetry/poetry/issues/4032
- run `poetry install`
- see that it'll try to update system setuptools (in my case - from 45.2.0 to 56.0.0)

Reasons:
- `installation/installer.py`  `Installer._installed_repository` contains outdated setuptools in list
- `repositories/installed_repository.py`  `InstalledRepository.load` obtains `sys.path` from venv, receives all packages from all paths from last to first path. If package already added - skips. This simulates behavior searching packages during import statement execution
- `env.sys_path` example: 
```
['',
 '/usr/lib/python38.zip',
 '/usr/lib/python3.8',
 '/usr/lib/python3.8/lib-dynload',
 '/home/vlad/.cache/pypoetry/virtualenvs/remember-me-bVccPGGr-py3.8/lib/python3.8/site-packages',
 '/home/vlad/Programs/planning/remember_me',
 '/home/vlad/.local/lib/python3.8/site-packages',
 '/usr/local/lib/python3.8/dist-packages',
 '/usr/lib/python3/dist-packages',
 '/usr/lib/python3.8/dist-packages']
```
- here we see that venv's dist-packages will be overriden by system dist-packages  (even if venv will have more recent versions)
- same `env.sys_path` for venv without `system-site-packages` enabled:
```
['',
 '/usr/lib/python38.zip',
 '/usr/lib/python3.8',
 '/usr/lib/python3.8/lib-dynload',
 '/home/vlad/.cache/pypoetry/virtualenvs/poetry-test-project-WlHBwTtI-py3.8/lib/python3.8/site-packages']
```

Question:
1. Will it be appropriate somehow to change order of entries in sys.path for venv packages to take precedence over system dist-packages ?  Example:
```
['',
 '/usr/lib/python38.zip',
 '/usr/lib/python3.8',
 '/usr/lib/python3.8/lib-dynload',
 '/home/vlad/.local/lib/python3.8/site-packages',
 '/usr/local/lib/python3.8/dist-packages',
 '/usr/lib/python3/dist-packages',
 '/usr/lib/python3.8/dist-packages']
 '/home/vlad/.cache/pypoetry/virtualenvs/remember-me-bVccPGGr-py3.8/lib/python3.8/site-packages',
 '/home/vlad/Programs/planning/remember_me',
```
2. Can anybody suggest me some tips on how it would be better to fix this issue or how to implement fix from question 1 ?

Thanks.

**Comment by logan-bobo** [comment]
Hi @vlad0337187 I have just followed your reproduction steps on the latest version of poetry `1.2.2` and the issue looks to be resolved and `setuptools` was not updated. I am going to close this issue.
