### ISSUE TITLE
poetry export is inconsistent with poetry install

### ISSUE THREAD

**Issue by dazza-codes** [python-poetry/poetry#4037]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: private, sorry

```
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"

$ poetry --version
Poetry version 1.1.5
```

## Issue

It is assumed that `poetry export` without asking for any optional extra packages would result in a requirements.txt file that matches all the packages installed by `poetry install`, but it does not.

```shell
$ poetry install
$ poetry export  --without-hashes --format requirements.txt --output requirements.txt

# the 'pillow' and 'distributed' packages are optional extras that should not be installed
# or in the requirements.txt exported by poetry

$ grep -i 'pillow' requirements.txt 
pillow==8.2.0; python_version >= "3.6"
$ grep -i 'distributed' requirements.txt 
distributed==2.30.1; python_version >= "3.7" and python_version < "4.0"

$ pip show pillow
WARNING: Package(s) not found: pillow
$ pip show distributed
WARNING: Package(s) not found: distributed
$ pip list | grep -i 'pillow'
$ pip list | grep -i 'distributed'
```

There are some optional packages in the `pyproject.toml` file (sorry, cannot share this private file, just assume there are optional dependencies, like `dask[complete]` for example).  It is assumed that `poetry export` will not include any of the optional extra packages unless they are explicitly requested for the export command. In the example above, the `pillow` and `distributed` packages should _not_ be in the requirements.txt file.

**Comment by dazza-codes** [comment]
This is related to https://github.com/python-poetry/poetry/issues/3451 and this issue might simply rephrase the problem with regard to expectations about how `poetry install` and `poetry export` should behave.  For my part, whether it is correct or not, I assume that `poetry export` can create a `requirements.txt` file that would closely match a `pip freeze` after a `poetry install`, where the requested package options or extras are the same for `poetry install` and `poetry export`.

**Comment by finswimmer** [comment]
Hello @dazza-codes,

I'm not able to reproduce your problem. Neither with poetry 1.1.5 nor a more recent version. Extras are always only included if requested by the `-E` parameter. So I guess your deps shown up, are also dependency of other packages that are not optional.

If you disagree feel free to leave a comment and a reproducible example, so we can analyze it further.

fin swimmer

**Comment by dazza-codes** [comment]
For my part, I've abandoned `poetry export` and replaced it with workflows that rely on `poetry build` and pip installs for the package.

**Comment by TreeKat71** [comment]
The results of `poetry export` and `pip list` are almost the same but some package versions are different. I would like to know why and how...

**Comment by neersighted** [comment]
This is a closed and long resolved issue. Please request support on Discord or Discussions, or open an issue with a detailed reproduction/example commands/outputs if you think you have encountered a bug.
