### ISSUE TITLE
Website Official Instructions still reference `get-poetry.py`  

### ISSUE THREAD

**Issue by auphofBSF** [python-poetry/poetry#4043]
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue
The website  https://python-poetry.org/docs/#installation does not reflect the  new `install-poetry.py`  bootstrapping method introduced by  #3706. 
![image](https://user-images.githubusercontent.com/11743864/117232569-86bef400-ae75-11eb-8b79-d5128e7c0153.png)

It appears the docs files are correct and the readme was updated also but those changes are not coming through to the website

**Comment by abn** [comment]
The documentation site reflects the state of latest stable version. The documentation from master does not get published automatically. 

The new bootstrap method will only become the default with the release of 1.2.0.
