### ISSUE TITLE
Poetry auto-deleting just created 

### ISSUE THREAD

**Issue by dadyarri** [python-poetry/poetry#4049]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Manjaro Linux @ 5.10 kernel
- **Poetry version**: 1.1.6
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file and log of** `poetry install`: https://gist.github.com/dadyarri/ab0581429aa2c7343d39e4aa66a91ddf

## Issue
On latest version (1.1.6 at the moment) after installing dependencies environment automatically deletes
Does not always happen

**Comment by finswimmer** [comment]
Hello @dadyarri,

I cannot follow your issue. Can you please add some more information?

fin swimmer

**Comment by dadyarri** [comment]
Hi @finswimmer, i dont know in which cases this happens, so can't give any information
