### ISSUE TITLE
Poetry ignores virtualenvs.in-project when initialized within a conda environment

### ISSUE THREAD

**Issue by dmcauslan** [python-poetry/poetry#4050]
- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOs 10.15.7
- **Poetry version**: 1.1.6
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**:
```
[tool.poetry]
name = "poetry-envs"
version = "0.1.0"
description = ""
authors = ["Don McAuslan"]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.25.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

## Issue
When creating a new project with `poetry init` inside an activated `conda` environment, Poetry will install packages into that environment rather than creating a local virtual env in `.venv`.

```
$ poetry --version
Poetry version 1.1.6

$ poetry config --list
cache-dir = "/Users/[my user id]/Library/Caches/pypoetry"
experimental.new-installer = true
installer.parallel = true
virtualenvs.create = true
virtualenvs.in-project = true
virtualenvs.path = "{cache-dir}/virtualenvs"  # /Users/[my user id]/Library/Caches/pypoetry/virtualenv

$ conda create -n py38_poetry python=3.8
... create the environment

$ conda activate py38_poetry

(py38_poetry) $ poetry init
... accept all defaults

(py38_poetry) $ poetry add requests@latest
Using version ^2.25.1 for requests
...

(py38_poetry) $ poetry env info

Virtualenv
Python:         3.8.8
Implementation: CPython
Path:           /usr/local/Caskroom/miniconda/base/envs/py38_poetry
Valid:          True

System
Platform: darwin
OS:       posix
Python:   /usr/local/Caskroom/miniconda/base/envs/py38_poetry

(py38_poetry)  $ poetry run which python
/usr/local/Caskroom/miniconda/base/envs/py38_poetry/bin/python
```

Since `virtualenvs.create` and `virtualenvs.in-project` are both `true`, I would expect the virtualenv path to be `.venv` within the current folder rather than `/usr/local/Caskroom/miniconda/base/envs/py38_poetry`

**Comment by mforbes** [comment]
I believe this is related to the discussion in issue #1724 and is consistent with the current design of poetry, hence, not a bug.  Still, I think it would be useful to be able to turn this feature off somehow.

**Comment by finswimmer** [comment]
Hello @dmcauslan,

as @mforbes explained this is the expected behavior. I would suggest you add you reasons why this would be useful to #4055 

fin swimmer
