### ISSUE TITLE
Provide a way to show executed system/pip commands

### ISSUE THREAD

**Issue by HeinrichHartmann** [python-poetry/poetry#4052]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

When debugging problems with poetry commands, I want to be able to print the `pip` commands that are executed behind the scenes.

Context: I was debugging issues with installing dependencies from private repositories the other day, and was not able to get this information. 

Related: When working with Make-based build systems there is the `VERBOSE=1`, `V=1` flag; bash has `-x` to print executed commands.

**Comment by Secrus** [comment]
The team is working on moving away from calls to other shell commands, so this is not going to be relevant soon.
