### ISSUE TITLE
install extra doesn't work for optional development dependencies

### ISSUE THREAD

**Issue by robin-moss** [python-poetry/poetry#4062]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **Ubuntu 20LTS**: 
- **1.1.6**: 
- **Link of a [Gist](https://gist.github.com/robin-moss/fc878ec212dbeb331ed5174a16db3010)**: 

## Issue

If the optional dependency is listed under dev dependencies, then calling install extra still skips the dependency:

```
$ poetry install -v
The currently activated Python version 3.8.5 is not supported by the project (^3.9).
Trying to find and use a compatible version. 
Using python3.9 (3.9.0)
Creating virtualenv gist-QVO4invi-py3.9 in /home/robin.moss/.cache/pypoetry/virtualenvs
Using virtualenv: /home/robin.moss/.cache/pypoetry/virtualenvs/gist-QVO4invi-py3.9
Updating dependencies
Resolving dependencies... (0.2s)

Writing lock file

Finding the necessary packages for the current system

Package operations: 0 installs, 0 updates, 0 removals, 1 skipped

  • Installing graphviz (0.16): Skipped for the following reason: Not required
$ poetry install -v -E bob
The currently activated Python version 3.8.5 is not supported by the project (^3.9).
Trying to find and use a compatible version. 
Using python3.9 (3.9.0)
Using virtualenv: /home/robin.moss/.cache/pypoetry/virtualenvs/gist-QVO4invi-py3.9
Installing dependencies from lock file

Finding the necessary packages for the current system

Package operations: 0 installs, 0 updates, 0 removals, 1 skipped

  • Installing graphviz (0.16): Skipped for the following reason: Not required
```

However, moving the dev dependency to dependency works. Is it intentional that extras do not work for dev dependencies? If so what is the standard way to install an optional dev dependency?

**Comment by finswimmer** [comment]
Hello @robin-moss,

yes that behavior is expected. "extras" are only meant for normal deps. "extras" for dev dependencies is what is discussed as [dependency groups](https://github.com/python-poetry/poetry/issues/1644) and is planned for poetry 1.2.

fin swimmer
