### ISSUE TITLE
Error initializing the virtual environment when there is a space in the path to .venv

### ISSUE THREAD

**Issue by StreetWanderer** [python-poetry/poetry#4067]
- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: MacOS 10.13 High Sierra
- **Poetry version**: 1.1.6
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: [pyproject.toml](https://gist.github.com/StreetWanderer/7282f04670a6df10ecb40e634e6c3cfd)

## Issue

I know this problem was supposed to be fixed by  da9746a10310f916c0707a3ec6e783072686b9b9 but this issue is still present on version 1.1.6 for me.
Thanks for the help!

Details to reproduce
```bash
$ poetry --version    
Poetry version 1.1.6    
$ poetry config --list
cache-dir = "/Users/Aust/Library/Caches/pypoetry"
experimental.new-installer = true
installer.parallel = true
virtualenvs.create = true
virtualenvs.in-project = true
$ cd "/Volumes/Macintosh HD/MyFiles/Documents/_Various-Programming/"
$ poetry new poetry-demo
Created package poetry_demo in poetry-demo
$ cd poetry-demo
$ poetry shell -vvv
Creating virtualenv poetry-demo in /Volumes/Macintosh HD/MyFiles/Documents/_Various-Programming/poetry-demo/.venv
Using virtualenv: /Volumes/Macintosh HD/MyFiles/Documents/_Various-Programming/poetry-demo/.venv
Spawning shell within /Volumes/Macintosh HD/MyFiles/Documents/_Various-Programming/poetry-demo/.venv
% . /Volumes/Macintosh HD/MyFiles/Documents/_Various-Programming/poetry-demo/.venv/bin/activate
.: no such file or directory: /Volumes/Macintosh
%
```

**Comment by schwa** [comment]
Seeing the same issue...

```
schwa@schwa-iMac-Pro PoetryTest on  main is 📦 v0.1.0 via 🐍 v2.7.18 poetry shell
Spawning shell within /Users/schwa/Library/Mobile Documents/com~apple~CloudDocs/Projects/PoetryTest/.venv
source /Users/schwa/Library/Mobile Documents/com~apple~CloudDocs/Projects/PoetryTest/.venv/bin/activate.fish
schwa@schwa-iMac-Pro PoetryTest on  main is 📦 v0.1.0 via 🐍 v2.7.18 source /Users/schwa/Library/Mobile Documents/com~apple~CloudDocs/Projects/PoetryTest/.venv/bin/activate.fish
source: Error encountered while sourcing file '/Users/schwa/Library/Mobile':
source: No such file or directory
```

**Comment by finswimmer** [comment]
Hello @StreetWanderer,

you haven't come back to this issue for a long while. So I assume this is solved in the meantime and I can close this ticket.

Feel free to leave a comment if you disagree.

fin swimmer
