### ISSUE TITLE
poetry new generate _version.py and just use it, for bump version

### ISSUE THREAD

**Issue by podhmo** [python-poetry/poetry#4070]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

I read #144 and https://github.com/python-poetry/poetry/issues/2614#issuecomment-652766308

## Feature Request

First of all, `poetry version <version>` not a bumping version of the `__init__.py`'s `__version__`. this is discussed many times, and a workaround exists.
But, current work-around,  using `importlib.metadata.version()` seem overkill for me.

This is the minimum approach of the crazy idea using astor https://github.com/python-poetry/poetry/pull/1354.

### details

in `poetry new`.

1.  generate `_version.py` (or `__version__.py` ?) 
2.  generated `__init__.py` reference it

in `poetry version <version>`

1. bump version of `pyproject.toml`
2. if `_version.py` exists, regenerate `_version.py`

That's all. 

### examples

_version.py

```py
# (the comment, something like "this is auto generated file")
__version__ = "0.1.0"
```

__init__.py

```py
from <package name>._version import __version__  # noqa: F401
```

**Comment by finswimmer** [comment]
Hello @podhmo,

using `importlib.metadata.version()` is not a workaround. It is the solution, because it reads the metadata that were installed. Since python 3.8 this is also build-in in python. So you get this method for free, without any additional dependencies.

fin swimmer

**Comment by podhmo** [comment]
Yes, I know using importlib.metadata.version() can solve this problem.

This is just an implementation detail, but when loading a package created by poetry, each of this for-loop to get the package costs a bit with a huge virtualenv.

https://github.com/python/cpython/blob/fa106a685c1f199aca5be5c2d0277a14cc9057bd/Lib/importlib/metadata/__init__.py#L520-L526

However, if you treat it as a fixed cost when loading. the closing of this issue is ok.
(performance issue has not occurred, currently)

**Comment by podhmo** [comment]
https://github.com/python-poetry/poetry/pull/2768

Oh, I see.

In this PR, the output of version information to the source code is stopped. 
I like this.  The version info in the package is out of poetry's Responsibilities.
