### ISSUE TITLE
Collaborate on a standardized lock file format?

### ISSUE THREAD

**Issue by brettcannon** [python-poetry/poetry#4072]
I have been working on a standardized lock file format with representatives from pip and pipenv and we would like to expand the participants to include Poetry (we have also reached out to pdm and pyflow). Is there a **single** representative from the project who would like to provide input? I realize you have `poetry export` so the actual format isn't critical to you, but having your input based on your experience would still be appreciated.

If there is interest, then please let me know who I should invite to the private repo.

**Comment by sdispater** [comment]
@brettcannon Thanks for reaching out!

Since I am the one who designed and implemented the logic around the lock file of Poetry, it would make the most sense for me to be the one to provide input and feedback on this matter. So feel free to invite me :-)

**Comment by brettcannon** [comment]
Done!
