### ISSUE TITLE
Automatic Activation of Virtual Environment and integration with  Pyenv

### ISSUE THREAD

**Issue by farhansaed** [python-poetry/poetry#4079]
Background: 
Pipenv allows automatic activation (as I CD into the project root folder containing Pipfile and Pipfile.lock) of virtual environment based on python version in pipefile/lock file.
I don't have to do pipenv shell to activate the virtual environment every time.

Also If python version version is not available on your system, and you have pyenv installed then pipenv automatically detects pyenv and pop up a message that python version is not available would you like to install it. Upon "Yes" pyenv starts installing required python version and after that pipenv automatically activates virtual environment.

Would poetry be able to develop those features.
Also I have observed that even if toml files specifies python 3.7 but if system have 3.9 available, doing poetry shell will use 3.9 and creates virtual environment. Can we remove default ^ in version declaration in toml file and make toml file source of truth for python versions make consistent development environments across team members.

These are some missing features that are stopping me to switch to poetry from pipenv.

**Comment by finswimmer** [comment]
Hello @farhansaed,

automatic activation of venv's is out of scope for poetry. It would require a lot of hacking around the several shells out there.

fin swimmer
