### ISSUE TITLE
poetry-1.2.0a1-linux.sha256sum

### ISSUE THREAD

**Issue by hengryLi** [python-poetry/poetry#4087]
hi ，When I install it, I am prompted that the latest version is poetry-1.2.0a1-linux.sha256sum ， But it doesn't exist 。Please pack it for me

**Comment by hengryLi** [comment]
Retrieving Poetry metadata

# Welcome to Poetry!

This will download and install the latest version of Poetry,
a dependency and package manager for Python.

It will add the `poetry` command to Poetry's bin directory, located at:

$HOME/.poetry/bin

This path will then be added to your `PATH` environment variable by
modifying the profile file located at:

$HOME/.profile

You can uninstall at any time by executing this script with the --uninstall option,
and these changes will be reverted.

Installing version: 1.2.0a1
Traceback (most recent call last):
  File "<stdin>", line 580, in _make_lib
  File "/usr/local/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/local/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1086, in <module>
  File "<stdin>", line 1082, in main
  File "<stdin>", line 362, in run
  File "<stdin>", line 528, in install
  File "<stdin>", line 548, in make_lib
  File "<stdin>", line 583, in _make_lib
RuntimeError: Could not find poetry-1.2.0a1-linux.sha256sum file
ERROR: Service 'django' failed to build: The command '/bin/sh -c curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | POETRY_PREVIEW=1 python' returned a non-zero code: 1

**Comment by manlix** [comment]
Hi @sdispater and thank you for interesting new features in `1.2.0a1` (like ability to add packages in `editable mode`) but I have the same issue during install `preview` version `1.2.0a1` — there is not ` poetry-1.2.0a1-linux.sha256sum` file.

Steps to reproduce on `Ubuntu 20.04.2 LTS`:

1) Install `poetry` by custom installer:
```bash
$ curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3 -
...
Installing version: 1.1.6
  - Downloading poetry-1.1.6-linux.tar.gz (72.33MB)

Poetry (1.1.6) is installed now. Great!
...
```

2)  Configuring shell:

```bash
$ source $HOME/.poetry/env
```

3) Check installed version:

```bash
$ poetry -V
Poetry version 1.1.6
```

4) Try to install preview version (`1.2.0a1`):

```python3
$ poetry self update --preview
Updating to 1.2.0a1

  RuntimeError

  Could not find poetry-1.2.0a1-linux.sha256sum file

  at ~/.poetry/lib/poetry/console/commands/self/update.py:181 in _update
      177│         try:
      178│             r = urlopen(base_url + "/{}/{}".format(version, checksum))
      179│         except HTTPError as e:
      180│             if e.code == 404:
    → 181│                 raise RuntimeError("Could not find {} file".format(checksum))
      182│ 
      183│             raise
      184│ 
      185│         checksum = r.read().decode().strip()
```

**Comment by abn** [comment]
Please note that with 1.2.0a1, [the usage of `get-poetry.py` script is deprecated](https://python-poetry.org/blog/announcing-poetry-1-2-0a1.html#deprecation-of-the-get-poetry-py-script). The new installation mechanism means that you cannot upgrade from `1.1.z` via `self update` comment. See https://github.com/python-poetry/poetry/issues/4040#issuecomment-834283739 for context on why this might not be supported. The recommended upgrade path is to uninstall `1.1.z` and use `install-poetry.py` script.

Further, the new installation mechanism no longer requires the vendored release artifacts, hence platform specific distributions are not provided with releases going forward.
