### ISSUE TITLE
Asking questions

### ISSUE THREAD

**Issue by Tegomena** [python-poetry/poetry#4090]
Hi,

I like Poetry very much and using it in a middle sized project. I have some questions about its usage which is not covered in the documentation, is there a place to ask these questions? Not sure if the issue tracker here is the right place because its not about an "issue", but it was the only place I found to communicate. If useful, i would also extend the documentation with your answers ;-)

**Comment by finswimmer** [comment]
Hello @Tegomena,

general questions are best asked at [github's Discussion](https://github.com/python-poetry/poetry/discussions). You can also join our [Discord Server](https://discordapp.com/invite/awxPgve).

fin swimmer
