### ISSUE TITLE
install-poetry in docker 

### ISSUE THREAD

**Issue by peter-dimov** [python-poetry/poetry#4093]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**:  Debian GNU/Linux 10 (buster)
- **Poetry version**:  1.1.6

## Issue

Installing poetry in docker using the recommended method does not work as a layer in the dockerfile but works fine when -it'ing into the container and running it.

`RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python -`

produces the expected output:

`(...)
Poetry (1.1.6) is installed now. Great!

You can test that everything is set up by executing:

'poetry --version'`

but when jumping into the directory (home/.local/share/pypoetry/venv/bin), these are the available executables:

- activate  
- activate.csh  
- activate.fish  
- activate.ps1  
- activate.xsh  
- activate_this.py  
- pip  
- pip-3.7  
- pip3  
- pip3.7  
- python  
- python3  
- python3.7  
- wheel  
- wheel-3.7  
- wheel3  
- wheel3.7

In contrast, when omitting the line in the dockerfile, running the container interactively and curl'ing install-poetry, the installation works fine.

In addition, it seems that pip install virtualenv needs to be done manually as well or the layer fails to build with:

`ModuleNotFoundError: No module named 'virtualenv'`

Here is a barebones replication:

Dockerfile:
`FROM apache/airflow:latest

USER root

RUN apt-get update && apt-get install -y make build-essential libssl-dev zlib1g-dev \
  libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev \
  libncursesw5-dev xz-utils tk-dev libffi-dev liblzma-dev python-openssl git python

RUN pip install virtualenv

RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python -
RUN poetry -V`

**Comment by abn** [comment]
The issue here is caused by the following line in the base image.

https://github.com/apache/airflow/blob/74821c8d999fad129b905a8698df7c897941e069/Dockerfile#L375

As a workaround you can update your Dockerfile like so.
```Dockerfile
FROM apache/airflow:latest

USER root

RUN apt-get update && apt-get install -y make build-essential libssl-dev zlib1g-dev
libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev
libncursesw5-dev xz-utils tk-dev libffi-dev liblzma-dev python-openssl git python

RUN pip install virtualenv

RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | PIP_USER= python -
RUN /root/.local/bin/poetry -V
```

The installer will need to unser env vars to prevent similar class of issues, and should also surface errors in the log. Will follow up with a PR later.
