### ISSUE TITLE
poetry update modifies lock file differently for linux and macOS.

### ISSUE THREAD

**Issue by jvineet** [python-poetry/poetry#4104]
- [ ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: MacOS Big Sur vs Ubuntu 20.04 
- **Poetry version**: 1.1.4
- **Link of a [Gist](https://gist.github.com/jvineet/41a65a670c6c1d995963c76bc706710c) with the contents of pyproject.toml file**: 

## Issue

I came across a strange behavior with poetry where running `poetry update <some package>` updates the lockfile a little differently depending on the OS. I was not expecting to see any change in lock file after running poetry update in an existing lockfile on macOS vs on ubuntu. 

Steps to reproduce:

1. I created two images to mirror the OS environment where I was running poetry update. The images can be downloaded from Dockerhub with
```
docker pull jvineet/poetry-test-ubuntu:latest
docker pull jvineet/poetry-test-macos:latest 
```
2. Run a container from each image 
```
docker run -d --rm --entrypoint tail --name poetry_ubuntu jvineet/poetry-test-ubuntu:latest -f /dev/null
docker run -d --rm --entrypoint tail --name poetry_macos jvineet/poetry-test-macos:latest -f /dev/null
```
3. Run poetry update in each container and check for diff in poetry.lock
```
docker exec -it poetry_ubuntu bash -c 'poetry update numpy && git diff poetry.lock'
docker exec -it poetry_macos /bin/bash -c '. ~/.bashrc && poetry update numpy && git diff poetry.lock'
```

Only the ubuntu container should show a diff like below:
```
funcsigs = {version = ">=1.0", markers = "python_version < \"3.0\""}
 importlib-metadata = {version = ">=0.12", markers = "python_version < \"3.8\""}
-more-itertools = {version = ">=4.0.0", markers = "python_version > \"2.7\""}
+more-itertools = [
+    {version = ">=4.0.0,<6.0.0", markers = "python_version <= \"2.7\""},
+    {version = ">=4.0.0", markers = "python_version > \"2.7\""},
+]
 packaging = "*"
 pathlib2 = {version = ">=2.2.0", markers = "python_version < \"3.6\""}
```
**Expectation**: None of the containers would have shown any diffs.

The poetry.lock file in both images was initially created in macOS and then added to each image during docker build without any change. The `pyproject.toml` for this lock file can be found in the gist above (It should also be in the containers). The change in poetry lock file in ubuntu happens at the `package.dependencies` section for `pytest` package. The more-itertools requirements in Metadata for the `pytest` package itself are same on both images. They can be inspected quickly with
```
docker exec -it poetry_ubuntu grep more-itertools .venv/lib/python2.7/site-packages/pytest-4.6.9.dist-info/METADATA
docker exec -it poetry_macos grep more-itertools .venv/lib/python2.7/site-packages/pytest-4.6.9.dist-info/METADATA
```

`pyproject.toml` file in both instances is configured to work with python `^2.7.9`, so it is also a bit weird that Poetry lock file in macOS picks `more-itertools = {version = ">=4.0.0", markers = "python_version > \"2.7\""}` from package metadata since that has python >2.7. 

I should also note here that although these differences don't affect which version of `more-itertools` package is resolved by poetry, I am not sure if it that will always be the case in other similar situations with maybe different packages.

**Comment by dimbleby** [comment]
The update that gives two variations for more-itertools is correct, derived from pytest 4.6.9.

With poetry 1.2.1 I see that happening in both images provided.

So this seems to be fixed and can be closed.
