### ISSUE TITLE
poetry lock file is created slightly differently with and without supplying python patch version in pyproject.toml on macOS

### ISSUE THREAD

**Issue by jvineet** [python-poetry/poetry#4105]
- [ ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: MacOS BigSur and Catalina
- **Poetry version**: 1.1.4
- **Link of a [Gist](https://gist.github.com/jvineet/41a65a670c6c1d995963c76bc706710c) with the contents of your pyproject.toml file**: 

## Issue

I noticed when pinning version for python in `pyproject.toml`, depending on whether I supplied a patch version for python or not, the `poetry.lock` file created had slightly different `package.dependencies` for pytest, specifically the `more-itertools` package dependency. I noticed this behavior in macOS Big Sur as well as Catalina.

On using python version as `python = "^2.7"` (no patch version) the `[package.dependencies]` section for pytest in `poetry.lock` looks like this
```
[package.dependencies]
...
more-itertools = [
    {version = ">=4.0.0,<6.0.0", markers = "python_version <= \"2.7\""},
    {version = ">=4.0.0", markers = "python_version > \"2.7\""},
]
...
```

On using python version as `python = "^2.7.9"` (with patch version) the `[package.dependencies]` section for pytest in `poetry.lock` looks like this
```
[package.dependencies]
...
more-itertools = {version = ">=4.0.0", markers = "python_version > \"2.7\""}
...
```

Incidentally, I only saw this behavior in macOS and not ubuntu, where  ubuntu had the following output on both occasions
```
[package.dependencies]
...
more-itertools = [
    {version = ">=4.0.0,<6.0.0", markers = "python_version <= \"2.7\""},
    {version = ">=4.0.0", markers = "python_version > \"2.7\""},
]
...
```

I am not exactly sure what is going on here and what is the correct output that I should expect. It appears that when I supply a patch version for python such as `^2.7.9`, poetry might be evaluating `2.7.9` as greater than `2.7` (`2.7.9 > 2.7`) for python dependency resolution in macOS.

Steps to reproduce:
1. Create a `poetry.lock` file from the `pyproject.toml` supplied in the gist above. 
2. Run `git add poetry.lock`
3. Edit the python version dependency in `pyproject.toml` from `python = "^2.7.9"` to `python = "^2.7"`
4. Run `poetry update`
5. Now running `git diff poetry.lock` should show this (besides changes to python version and content-hash)
```
-more-itertools = {version = ">=4.0.0", markers = "python_version > \"2.7\""}
+more-itertools = [
+    {version = ">=4.0.0,<6.0.0", markers = "python_version <= \"2.7\""},
+    {version = ">=4.0.0", markers = "python_version > \"2.7\""},
+]
```
**Expectation**: I'd have expected to not see any diffs here.

I should also note here that although these differences don't affect which version of `more-itertools` package is resolved by poetry, I am not sure if it that will always be the case in other similar situations with maybe different packages.

**Comment by dimbleby** [comment]
both variants lock the same way today, I'm not sure that it was ever an interesting difference anyway to be honest.  

Reckon this wants closing out.
