### ISSUE TITLE
Chains of private repositories

### ISSUE THREAD

**Issue by algebravic** [python-poetry/poetry#4115]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: 
- **Poetry version**: 
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue

Running poetry 1.1.6

In a fresh directory I do the following:

poetry new fizz_buzz
poetry new foo
poetry new bar
cd foo
poetry add fizz_buzz
cd ../bar
poetry add ../foo

I get the following error:
`` Command ['/home/victor/.cache/pypoetry/virtualenvs/bar-SqDtZOvU-py3.7/bin/pip', 'install', '--no-deps', '-U', '/home/victor/Programming/test/foo'] errored with the following return code 1, and output: 
  Processing /home/victor/Programming/test/foo
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
      Preparing wheel metadata: started
      Preparing wheel metadata: finished with status 'error'
      ERROR: Command errored out with exit status 1:
       command: /home/victor/.cache/pypoetry/virtualenvs/bar-SqDtZOvU-py3.7/bin/python /home/victor/.cache/pypoetry/virtualenvs/bar-SqDtZOvU-py3.7/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpp1ybla8u
           cwd: /tmp/pip-req-build-o0a011md
      Complete output (16 lines):
      Traceback (most recent call last):
        File "/home/victor/.cache/pypoetry/virtualenvs/bar-SqDtZOvU-py3.7/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
          main()
        File "/home/victor/.cache/pypoetry/virtualenvs/bar-SqDtZOvU-py3.7/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/victor/.cache/pypoetry/virtualenvs/bar-SqDtZOvU-py3.7/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 133, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/tmp/pip-build-env-97enakmq/overlay/lib/python3.7/site-packages/poetry/core/masonry/api.py", line 43, in prepare_metadata_for_build_wheel
          poetry = Factory().create_poetry(Path(".").resolve(), with_dev=False)
        File "/tmp/pip-build-env-97enakmq/overlay/lib/python3.7/site-packages/poetry/core/factory.py", line 93, in create_poetry
          self.create_dependency(name, constraint, root_dir=package.root_dir)
        File "/tmp/pip-build-env-97enakmq/overlay/lib/python3.7/site-packages/poetry/core/factory.py", line 251, in create_dependency
          extras=constraint.get("extras", []),
        File "/tmp/pip-build-env-97enakmq/overlay/lib/python3.7/site-packages/poetry/core/packages/directory_dependency.py", line 41, in __init__
          raise ValueError("Directory {} does not exist".format(self._path))
      ValueError: Directory ../fizz_buzz does not exist
      ----------------------------------------
  WARNING: Discarding file:///home/victor/Programming/test/foo. Command errored out with exit status 1: /home/victor/.cache/pypoetry/virtualenvs/bar-SqDtZOvU-py3.7/bin/python /home/victor/.cache/pypoetry/virtualenvs/bar-SqDtZOvU-py3.7/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpp1ybla8u Check the logs for full command output.
  ERROR: Command errored out with exit status 1: /home/victor/.cache/pypoetry/virtualenvs/bar-SqDtZOvU-py3.7/bin/python /home/victor/.cache/pypoetry/virtualenvs/bar-SqDtZOvU-py3.7/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpp1ybla8u Check the logs for full command output.
  WARNING: You are using pip version 21.0.1; however, version 21.1.2 is available.
  You should consider upgrading via the '/home/victor/.cache/pypoetry/virtualenvs/bar-SqDtZOvU-py3.7/bin/python -m pip install --upgrade pip' command.
  

  at ~/.poetry/lib/poetry/utils/env.py:1075 in _run
      1071│                 output = subprocess.check_output(
      1072│                     cmd, stderr=subprocess.STDOUT, **kwargs
      1073│                 )
      1074│         except CalledProcessError as e:
    → 1075│             raise EnvCommandError(e, input=input_)
      1076│ 
      1077│         return decode(output)
      1078│ 
      1079│     def execute(self, bin, *args, **kwargs):
``

**Comment by algebravic** [comment]
Here's the pyproject.toml and trace with -vvv option [https://gist.github.com/algebravic/7be5fc8756fa6d7bf2cc3c5621a2847b](url)

**Comment by finswimmer** [comment]
Hello @algebravic,

those nested path dependencies only works, if you have set `develop = true` in the `pyproject.toml` for any path dependency. Without it, a path dependency is build as a real package. This is done in a temporary folder and from there relative paths doesn't point to the intended folder.

At the moment there is no flag for the cli to add this automatically in the `pyproject.toml ` but it will be in the next minor release.

fin swimmer
