### ISSUE TITLE
Poetry fails to execute pip installed package when using run 

### ISSUE THREAD

**Issue by assassinsorrow** [python-poetry/poetry#4116]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows 19041.985
- **Poetry version**: 1.1.6
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://github.com/assassinsorrow/RhythmPy/blob/Bot-Refactor/pyproject.toml

## Issue
Poetry fails to run a pip installed package (pycallgraph) when run with ```poetry run pycallgraph``` but succeeds when the command is issued while inside of ```poetry shell```
# Error
```
$ poetry run pycallgraph graphviz __main__.py -vvv

  FileNotFoundError

  [WinError 2] The system cannot find the file specified

  at ~\AppData\Local\Programs\Python\Python37\lib\subprocess.py:1207 in _execute_child
      1203│                                          int(not close_fds),
      1204│                                          creationflags,
      1205│                                          env,
      1206│                                          os.fspath(cwd) if cwd is not None else None,
    → 1207│                                          startupinfo)
      1208│             finally:
      1209│                 # Child is launched. Close the parent's copy of those pipe
      1210│                 # handles that only the child should have open.  You need
      1211│                 # to make sure that no handles to the write end of the
```

**Comment by sinoroc** [comment]
The link to your `pyproject.toml` leads nowhere.

**Comment by sinoroc** [comment]
Maybe a duplicate of:
* https://github.com/python-poetry/poetry/issues/2481
* https://github.com/python-poetry/poetry/issues/3265

**Comment by sinoroc** [comment]
In your case `pycallgraph` does not declare "console script" but a simple "script":

https://github.com/gak/pycallgraph/blob/develop/setup.py#L43

And I am not entirely sure that `poetry run` is able to catch on this...

**Comment by assassinsorrow** [comment]
here is a updated version of the `pyproject.toml`
https://github.com/assassinsorrow/RhythmPy/blob/master/pyproject.toml
and iis the reason that `poetry run` is not able to be utilized stems from the fact that `pycallgraph` does not declare a "console script"?

**Comment by sinoroc** [comment]
> is the reason that `poetry run` is not able to be utilized stems from the fact that `pycallgraph` does not declare a "console script"?

I might be wrong, but in regard to the other tickets: it seems to me like it is the case, yes. It also seems like it is more of a Windows-specific behavior. Some fixes are mentioned in the other tickets, I do not know if these fixes ever made it into a poetry release.

**Comment by assassinsorrow** [comment]
After doing some testing on my machines that are running linux i can confirm that this issue only exists on windows
