### ISSUE TITLE
Allow extra dependencies to be installed automatically as dev

### ISSUE THREAD

**Issue by pedrorrivero** [python-poetry/poetry#4118]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request
Allow extra dependencies to be installed automatically as dev without need for duplicating their entry in pyproject.toml

**Comment by finswimmer** [comment]
Hello @pedrorrivero,

can you please give some more words about the what and why?

"extras" are dependencies that add extra functionality during runtime of the package. dev dependencies are such deps, that are needed only during development, e.g. linter, testing frameworks...

Having duplicate entry is usually only needed if you have a dependency, that should have a smaller version range during development in comparison to the resulting wheel file.

fin swimmer

**Comment by pedrorrivero** [comment]
Hi @finswimmer, thanks for reaching back.

Keeping in mind your definition of extras and dev, let me present you with two cases:
1. The library needs only one of a number of different dependencies, so we mark them all as extras and let the user decide (e.g. you are creating an adapter). The end user will only have installed one of the many possible libraries, however, as a developer I want to have all of them installed.
2. I have git hooks that run tests on my software before committing. Said tests need to have all extra dependencies installed.

In my case ([QRAND](https://github.com/pedrorrivero/qrand)) both those scenarios apply.

**Comment by finswimmer** [comment]
So your suggestion would be for example a new flag `--all-extras` for `poetry install` that will automatically install all listed extras?

**Comment by pedrorrivero** [comment]
Well, my suggestion was more in line with adding some label in pyproject.toml such as:
```toml
[tool.poetry.dependencies]
numpy = { version = "^1.19.4", optional = true, dev = true }
```
To force installation as a dev dependency without need to duplicate the entry in `[tool.poetry.dev-dependencies]`.

Alternatively, there could also be a way of referencing extra dependencies to install inside the `[tool.poetry.dev-dependencies]`, but I think this would be less versatile.

Nonetheless, the `--all-extras` flag is nice as well. I would argue in favor of implementing both options.

**Comment by paulmelnikow** [comment]
I have a similar use case. I have a complicated project with many different CI jobs and AWS Lambda functions. I have defined 11 extras: format, lint, test, integration, e2e, provisioning, build, lambda_common, and then one for each lambda.

In local development, I run a script which runs `poetry install` (with `--remove-untracked`) and then a long list of these extras.

Ideally I would have the developer run `poetry install` and it would _automatically_ install all the extras… and without them needing to know they need to specify `--all-extras`.

So what I'd really like is `--all-extras` _plus_ a config option that enables `--all-extras` by default. Whenever any extras are defined on the command line, only those extras would be installed. And `--no-extras` would override the config setting.

For my use case, installing all extras works, though to add flexibility, it would be good if you could also configure default extras that are a subset of the full list.

**Comment by caniko** [comment]
The issue is that some extras don't play well together. I think a more explicit approach is required. Include the extras you want installed under `dev` is probably the best way to go.

**Comment by finswimmer** [comment]
`poetry install` now have a `--all-extras` flag.
