### ISSUE TITLE
pywin32 install  on a 64bit machine 

### ISSUE THREAD

**Issue by teucer** [python-poetry/poetry#4119]
- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Window 10 Enterprise
- **Python version**: 3.9.5
- **Poetry version**: 1.16

## Issue

We have an internal PyPI repository which contains the following versions of `pywin32`

- pywin32-301-cp35-cp35m-win32.whl
- pywin32-301-cp39-cp39-win_amd64.whl

I am trying to install jupyterlab  which depends on jupyter_core.  The latter has the following dependency:

`pywin32>=1.0 ; sys_platform == 'win32`

When I execute `pip install jupyterlab` everything works and it downloads **pywin32-301-cp39-cp39-win_amd64.whl**.

Due to some internal security reasons **pywin32-301-cp35-cp35m-win32.whl** is quarantined (it is absurd, trying to change it!), but the package is still listed. My understanding is that poetry is trying to get some information from the first wheel listed (**pywin32-301-cp35-cp35m-win32.whl**) which is blocked in this situation and leads to a bug. 

I think poetry should check the first wheel that is compatible with the Python version (i.e. **pywin32-301-cp39-cp39-win_amd64.whl**).

**Comment by dimbleby** [comment]
when getting metadata poetry assumes all wheels are equivalent.  What you have is an issue with your "internal security reasons", not with poetry.

**Comment by neersighted** [comment]
Indeed, the current way metadata gathering works is to pick the first wheel. As they should all have equivalent metadata (or at least, Poetry successfully makes this assumption and has pushed the ecosystem this way), there is no reason to prefer any one wheel, and doing so would make locking less deterministic. I don't think Poetry should do anything here as this is a very weird edge case, and is better solved by your $CORP.
