### ISSUE TITLE
Documenting the limitations of adding packages that depend on versions of CUDA

### ISSUE THREAD

**Issue by caniko** [python-poetry/poetry#4124]
The documentation doesn't mention how to deal with situations in which the package to be added depends on version of external drivers such as CUDA. My specific case is that poetry can't detect the installed CUDA version appropriately when downloading from [this repo](https://eternalphane.github.io/pytorch-pypi/torch/). This repository is PEP 503 compliant.

My scenario:
I have added the repo to my `pyproject.toml`:
```
[[tool.poetry.source]]
name = "torch_rep"
url = "https://eternalphane.github.io/pytorch-pypi"
```
Lets say that I have CUDA 11.1 installed, what do I do? `poetry add torch`, just installs torch with ROCM when in fact I don't have an AMD GPU. CUDA or ROCM version on the computer should be detected, and if neither is present the fallback should be CPU.

From what I understand, this is a little outside of the scope of Poetry, and it would be nice to know why this isn't supported in the documentation. I think the Python ML community would appreciate a line or two about the problem, and potential solutions to pursue outside of poetry in the documentation.

PS:
For those wondering, the best solution at the moment would be to have separate package directories for cuda, rocm, and cpu on the PyPi repository; have cpu as the default for the poetry project, and install the alternative versions as extra.

**Comment by caniko** [comment]
PEP 440 does sum up the issue; moreover, I still think an example implementation would be nice. I'll make a PR when I find the time.

**Comment by ralbertazzi** [comment]
Closing as it doesn't add more than https://github.com/python-poetry/poetry/issues/6409 and https://github.com/python-poetry/poetry/issues/2613
