### ISSUE TITLE
get-python has become incompatible with Python2

### ISSUE THREAD

**Issue by MrWeeble** [python-poetry/poetry#4131]
- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 16.04
- **Poetry version**: 1.1.6
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: N/A

## Issue
The 1.1 branch is supposed to still be compatible with Python 2 so there should be a way to install it. However when I attempt to install poetry 1.1.x with the recommended method from the documentation
`curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -`
where `python` is a python 2 interpreter, it fails with a syntax error due to the use of f-strings introduced in change c28728fbe3e69c9995a4ea132dd767074f00e6f8

While I understand there is a new shiny installer for 1.2+ and python2 is deprecated, those of us who still rely on using poetry 1.1 on python 2 should not be locked out

Related to #4128

**Comment by finswimmer** [comment]
You are right @MrWeeble. Thanks for reporting :+1:
