### ISSUE TITLE
Install editable local dependency is not working

### ISSUE THREAD

**Issue by benlau** [python-poetry/poetry#4133]
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Issue

According to the document: "If you want the dependency to be installed in editable mode you can specify it in the pyproject.toml file. It means that changes in the local directory will be reflected directly in environment."

https://python-poetry.org/docs/cli/#add

If I understand correctly, it should create an egg-link file in the site-packages folder which is equivalent to the result of `pip install -e` so that it will always import the latest version automatically. However, I couldn't get it to works. 

Here is my procedure:

```
$ poetry --version
Poetry version 1.1.6
```

```
$ git clone https://github.com/ya-mori/python-monorepo.git
$ cd python-monorepo/projects/project-one/
```

Edit pyproject.toml

replace 

```
logger = {path = "../../libs/logger"}
```

by 

```
logger = {path = "../../libs/logger", develop=true}
```

```
$ poetry install 
$ find `poetry env info -p`/lib -name "logger*"

/Users/benlau/tmp/poetry/virtualenvs/project-one-vNJ7BUfg-py3.9/lib/python3.9/site-packages/logger-0.1.0.dist-info
/Users/benlau/tmp/poetry/virtualenvs/project-one-vNJ7BUfg-py3.9/lib/python3.9/site-packages/logger
/Users/benlau/tmp/poetry/virtualenvs/project-one-vNJ7BUfg-py3.9/lib/python3.9/site-packages/logger/__pycache__/logger.cpython-39.pyc
/Users/benlau/tmp/poetry/virtualenvs/project-one-vNJ7BUfg-py3.9/lib/python3.9/site-packages/logger/logger.py
```

I couldn't find a link file in the site-packages and of coz it won't update the logger package automatically.

Any steps I have missed?

Thanks for any advice.

**Comment by finswimmer** [comment]
Hello @benlau,

poetry doesn't use egg-link files to realize editable installs. Instead it uses `.pth` files to add the path to the root folder, that contains the package, to `sys.path`. See: https://docs.python.org/3/library/site.html

So there should be a `logger.pth` file within the site-packages folder.

fin swimmer

**Comment by benlau** [comment]
hi @finswimmer ,

Thanks for your reply. But logger.pth is also not generated. I could only find project-one.pth (The name of the project).

**Comment by benlau** [comment]
Finally, I found out what is wrong. It works after I have removed the poetry.lock and run `poetry install` again. The poetry.lock cached the `develop = false` option.

**Comment by finswimmer** [comment]
Hello again,

whenever you manually edit your `pyproject.toml` you should run `poetry lock` and `poetry install` afterwards. Whatever you have in your `poetry.lock` takes precedence over the `pyproject.toml`, so the lock file has to be generate again. Usually poetry warns you if it detects that `pyproject.toml` and `poetry.lock` are out of sync.

fin swimmer
