### ISSUE TITLE
Prune unused packages in pyproject.toml

### ISSUE THREAD

**Issue by robinderat** [python-poetry/poetry#4135]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

I have no idea whether this is possible but I'll mention my wish regardless.

After many reworks and changes to one of my projects, I have a huge list of dependencies in my pyproject.toml. I am sure some of these are no longer used and I want to remove them. I feel like there should be a better way than "removing a package to see if something breaks".

Would it be possible for poetry to check whether dependencies from the pyproject.toml are actually used in the project and perhaps automatically prune those that aren't?

**Comment by paulmelnikow** [comment]
> Would it be possible for poetry to check whether dependencies from the pyproject.toml are actually used in the project and perhaps automatically prune those that aren't?

How would that work?

Only idea I can really think of is "loop over packages, and remove a package and see if it breaks," using some test command you provide.

It seems like this is way out of scope for poetry, and should be built as a separate tool which reads poetry.toml.

**Comment by robinderat** [comment]
As I mentioned I am not so sure myself how this could be implemented. I agree your proposed solution does not sound great.

I believe this behavior is supported by pycharm when using a requirements file. I guess they look at all the imports in your code and flag any unmentioned packages as obsolete? Perhaps such an approach could work?

**Comment by paulmelnikow** [comment]
Maybe you could open an issue in Pycharm asking if they would support reading the Poetry sections of pyproject.toml.

If not, maybe a flag could be added to `poetry export` which generates a requirements.txt, but without including the transitive dependencies.

**Comment by guzuomuse** [comment]
any plane on this?

**Comment by finswimmer** [comment]
Hello,

this is something out of scope for Poetry, because it would require source code parsing.

**Comment by vihardesu** [comment]
I know this was closed, but this would be an incredibly useful feature. Because of AWS Lambda size limits, pandas and numpy account for the lion's share of any Lambda. While it may not be possible in `poetry`, if you could make a utility or something to help prune unused dependencies, that would be ~ incredible ~

**Comment by nietzscheson** [comment]
> I know this was closed, but this would be an incredibly useful feature. Because of AWS Lambda size limits, pandas and numpy account for the lion's share of any Lambda. While it may not be possible in `poetry`, if you could make a utility or something to help prune unused dependencies, that would be ~ incredible ~

The size in AWS Lambda no is an issue. [With Support to Docker](https://aws.amazon.com/blogs/aws/new-for-aws-lambda-container-image-support/), the size increase up to 10GB...

**Comment by LesRamer** [comment]
> I believe this behavior is supported by pycharm when using a requirements file. I guess they look at all the imports in your code and flag any unmentioned packages as obsolete? Perhaps such an approach could work?

In this case, you might use poetry to generate a requirements.txt file and let pycharm weed out the unused parts.

We use something like this to generate the requirements.txt for use with aws sam:
`poetry export --without-hashes -o ./requirements.txt`

**Comment by fpgmaas** [comment]
I found that my projects usually have a bloated list of dependencies as well, so I recently started developing a small tool to help find obsolete dependencies in a poetry project: 

[deptry](https://fpgmaas.github.io/deptry/)

Maybe some of the people stumbling onto this issue might find it useful. Currently in very active development, so if you decide to give it a try and encounter a bug, have a feature request, or if you have any other kind of feedback, I'd be happy to hear it.

**Comment by AleksandrLiadov** [comment]
@fpgmaas great work! 
That exactly what we searched for our CI.

**Comment by lukehsiao** [comment]
Another option for a tool is [`poetry-udeps`](https://github.com/lukehsiao/poetry-udeps), which I wrote to be a simpler/faster alternative to deptry.
