### ISSUE TITLE
Patch revision specification in pyproject.toml breaks creating new venv

### ISSUE THREAD

**Issue by tigerhawkvok** [python-poetry/poetry#4136]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows 10
- **Poetry version**: 1.1.6
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/tigerhawkvok/6a85ae71e7e24eed92acd561b28724e3

## Issue

Similar to #1735 . 

I only have one version of Python on this machine, 3.7.8; but the requirement `^3.7.1` throws an error:

![image](https://user-images.githubusercontent.com/165937/120696999-08e50d00-c462-11eb-9732-f287b31c70fc.png)

This can be corrected by removing the patch revision, then later updating pyproject.toml doesn't cause further poetry commands to fail.

**Comment by finswimmer** [comment]
Hello @tigerhawkvok,

can you show the out of `which poetry` and `head $(which poetry)`?

fin swimmer

**Comment by tigerhawkvok** [comment]
`head` isn't a valid command in my Powershell setup (strangely, because I have most *nix commands), so here are the results from git bash. It's the same poetry `which` as pure powershell.

![image](https://user-images.githubusercontent.com/165937/121738062-8fc36680-caae-11eb-98ff-31d30b6872c5.png)


```
pkahn@SFPKAHN1 MINGW64 ~
$ which poetry
/c/Users/pkahn/.poetry/bin/poetry

pkahn@SFPKAHN1 MINGW64 ~
$ head $(which poetry)
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import glob
import sys
import os

lib = os.path.normpath(os.path.join(os.path.realpath(__file__), "../..", "lib"))
vendors = os.path.join(lib, "poetry", "_vendor")
current_vendors = os.path.join(
    vendors, "py{}".format(".".join(str(v) for v in sys.version_info[:2]))
```

**Comment by tigerhawkvok** [comment]
Seems like instead of a string comparison, following [PEP 440](https://www.python.org/dev/peps/pep-0440/) Poetry should use something like [`packaging`](https://pypi.org/project/packaging/) which is [vendored into `setuptools`](https://github.com/pypa/setuptools/tree/a94ccbf404a79d56f9b171024dee361de9a948da/pkg_resources/_vendor/packaging) and [vendored into `pip`](https://github.com/pypa/pip/tree/7ec0fa5142466f8402bb866a1dcfb8ca6ffdc66b/src/pip/_vendor/packaging) to compare versions:


```
>>> from packaging import version
>>> version.parse("2.3.1") < version.parse("10.1.2")
True
```

Pulling the first two tuple elements in `sys.version_info` will always fail patch revisions, which can break package dependencies when, for example, `pandas==1.0.5` requires python to be newer than 3.7.1

**Comment by tigerhawkvok** [comment]
I propose something like this:

```python
from packaging.version import parse as parsePyVersion
from packaging.version import VERSION_PATTERN
from platform import python_version
import re
def validPyVersion(required:str, debug:bool= False) -> bool:
    """
    Compare a match string to the running Python version
    """
    required = str(required)
    # Our running version
    CURRENT_VERSION = parsePyVersion(python_version())
    # The package minimum required version
    versionMatch = re.search(r"^[\^=~]*([0-9](?:\.\d*)?(?:\.[a-z\d]*)?)$", required.strip(), re.IGNORECASE | re.DOTALL | re.MULTILINE)
    if not versionMatch:
        raise ValueError("Invalid version string")
    versionString = versionMatch.group(1)
    versionParts = versionString.split(".")
    COMPARE_VERSION = parsePyVersion(versionString)
    # The next revision up, for the package's specificity
    try:
        if len(versionParts) == 1:
            raise IndexError
        versionSpecificity = versionParts.copy().pop() if len(versionParts) < 3 else versionParts[:-1].pop()
        versionStub = [versionParts[0]]
    except IndexError:
        versionSpecificity = versionString
        versionStub = []
    try:
        nextVersion = int(versionSpecificity) + 1
    except TypeError:
        thisDigitMatch = re.search(r"^(\d+)", versionSpecificity, re.IGNORECASE | re.DOTALL | re.MULTILINE)
        thisDigit = 0 if thisDigitMatch is None else thisDigitMatch.group(0)
        nextVersion = int(thisDigit) + 1
    PACKAGE_LESS_THAN_VERSION = parsePyVersion('.'.join([str(x) for x in versionStub + [nextVersion]]))
    # tidy the match type. Remove `=` as to play nice with
    # some version strings that have extra `=` in them, like pip
    matchType = required.strip().replace(versionString, '')
    if len(matchType) > 1:
        matchType = matchType.replace('=', '')
    if len(matchType) == 0:
        matchType = '=' if len(versionParts) == 3 else "~"
    comparisonMapper = {
        '=': COMPARE_VERSION == CURRENT_VERSION,
        '^': CURRENT_VERSION >= COMPARE_VERSION,
        '~': (CURRENT_VERSION >= COMPARE_VERSION) and (CURRENT_VERSION < PACKAGE_LESS_THAN_VERSION),
    }
    if debug:
        return comparisonMapper[matchType], COMPARE_VERSION, PACKAGE_LESS_THAN_VERSION, CURRENT_VERSION, matchType
    return comparisonMapper[matchType]
```


![image](https://user-images.githubusercontent.com/165937/121746283-7c1dfd00-caba-11eb-8c74-e727f78ef077.png)

**Comment by finswimmer** [comment]
Hello @tigerhawkvok,

I guess your suggestion refers to this line in the poetry executable? 

```
current_vendors = os.path.join(
    vendors, "py{}".format(".".join(str(v) for v in sys.version_info[:2]))
```

This is only needed to tell poetry where it can find it's vendored dependencies. And this location depends on the currently activate python minor version.

This has nothing to do with comparing version requirements for dependencies. So it's still unclear why poetry believes you are using python 3.7.0. Can you show the output of `python -c "import sys;print(sys.version_info)"`?

fin swimmer

**Comment by finswimmer** [comment]
I'm closing this because we haven't receive no more information for a long time now.

Feel free to leave a comment if you disagree.
