### ISSUE TITLE
Adding dep from git fails if package doesn't contain "**/*.egg-info"

### ISSUE THREAD

**Issue by karantan** [python-poetry/poetry#414]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Darwin Kernel Version 17.7.0
- **Poetry version**: 0.11.4
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/karantan/4ae73250fb269d8667c9df282ee3607e

## Issue

I'm trying to install my fork of ansible package. I've tried pinning revision and branch but the result is the same. It fails with the following error: `OSError: [Errno 62] Too many levels of symbolic links: `.

This line https://github.com/sdispater/poetry/blob/master/poetry/puzzle/provider.py#L196 throws `OSError: [Errno 62] Too many levels of symbolic links: ` because it can't find any `**/*.egg-info` files. 

Is this functionality intended?

**Comment by sdispater** [comment]
The issue does not come from the fact that there is no `**/*.egg-info` but because there is a recursive symlink in the test folder.

From I can tell this is an issue in `pathlib` but strangely enough `pathlib2`, which is a backport of `pathlib`, does not raise this error.

**Comment by sdispater** [comment]
Commit 228f0f9 should fix the issue.

It will land in the next bugfix release.

**Comment by karantan** [comment]
What is the estimation for the next release?
