### ISSUE TITLE
Dependency with version "^0" does not work in 1.2.0a1

### ISSUE THREAD

**Issue by joshorr** [python-poetry/poetry#4153]
- [x] I am on the 1.2.0a1 alpha Poetry version (1.2.0a1)
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: MacOS 11.4; BigSur
- **Poetry version**: 1.2.0a1
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/joshorr/d25b9edb7e20d00dab565dce771b69dd

## Issue
When you have a dependency with version set to "^0", it errors out while executing `poetry update`.  Currently released 1.1.6 version works fine with this.  It's the new 1.2.0a1 that has the problem.

According to docs at (https://python-poetry.org/docs/versions/),  you should be able to do this.  It's equivalent to doing `>=0.0.0 <1.0.0`.  If you do `>=0.0.0 <1.0.0`, that works for 1.2.0a1, so that's the workaround at the moment.

You can test it by creating a new project via:

`poetry new`

And then adding this dependency to the `pyproject.toml` file:

`pendulum = "^0"`

Then, finally doing an update:

`poetry update`

If you do these steps with version 1.1.6, it works fine.  But version 1.2.0a1 will error out with this output (-vvv):

https://gist.github.com/joshorr/9093c552515451f9e1037adff54a990a

**Comment by apollo13** [comment]
This is explicitly tested in
https://github.com/python-poetry/poetry-core/blob/ad33bc2f92be03dc5b31a666664903c439fb1173/tests/semver/test_helpers.py#L194
but I agree that this does go against the documentation. It seems to have been changed by @abn via 
https://github.com/python-poetry/poetry-core/commit/748157e58b4676f9d2706e525c2a3f13cbda8ca4#diff-097699e72f731cb04c9485e35af6cf0b1f8201e8ebb39bd26a0be8e4b5dfea19L85-R194

I found this article https://nodesource.com/blog/semver-tilde-and-caret/ which links to gems like this https://twitter.com/jo_liss/status/494986913124990977 -- but either way, the docs or the code should be fixed. @abn can you shed any light on the reason why you wrote the test like you did?
