### ISSUE TITLE
Version solving stuck at the very beginning (22 deps takes ~25 sec)

### ISSUE THREAD

**Issue by ZhukovGreen** [python-poetry/poetry#4155]
- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: 
- **Poetry version**: 1.1.6
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/ZhukovGreen/6acff5e2404f92546f6b0206b06f4be1

## Issue
I think it might be not related to #2094 
When I run poetry update -vvv, then the process seems to stuck at the very beginning (https://asciinema.org/a/kthS4hDyrNsZVE5F0rJpDJA3B):
```
Using virtualenv: /home/azhukov/.cache/pypoetry/virtualenvs/zhukovgreen111-qI5AUrnU-py3.9
Updating dependencies
Resolving dependencies...
   1: fact: zhukovgreen111 is 0.1.0
   1: derived: zhukovgreen111
```
Then, the rest part of the version solving works quite fast.

**Comment by finswimmer** [comment]
Hello @ZhukovGreen,

the time consuming part is the cloning of the git repo for the ipython dependency. Once this is done, everything then works fast.

fin swimmer

**Comment by ZhukovGreen** [comment]
Thx for the clarification @finswimmer
