### ISSUE TITLE
Attempting to install mkdocs using poetry raises an AssertionError

### ISSUE THREAD

**Issue by vivekhub** [python-poetry/poetry#4156]
- [x ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [ x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: OSX catalina 10.15.7
- **Poetry version**: Poetry version 1.1.6

- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/vivekhub/655375ab0c92053be9398cb912c921f6
## Issue

This toml file causes poetry to raise an AssertionError when run.  It was generated by Poetry automatically

```
[vivekv@mbp ~/projects/mkdocs]$ poetry install
Updating dependencies
Resolving dependencies... (0.0s)

  AssertionError

  

  at ~/.poetry/lib/poetry/mixology/incompatibility.py:111 in __str__
      107│         )
      108│ 
      109│     def __str__(self):
      110│         if isinstance(self._cause, DependencyCause):
    → 111│             assert len(self._terms) == 2
      112│ 
      113│             depender = self._terms[0]
      114│             dependee = self._terms[1]
      115│             assert depender.is_positive()
```

**Comment by finswimmer** [comment]
Hello @vivekhub,

you cannot name you project like a dependency.

The error message could be cleaner here. A ticket already exists: https://github.com/python-poetry/poetry/issues/236

fin swimmer
