### ISSUE TITLE
Website not working on Firefox

### ISSUE THREAD

**Issue by johan010** [python-poetry/poetry#4158]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

When I try and go to the website using Firefox, I get Secure Connection Failed error. Are you aware of this? Or is this an error on my side? I am using Version 89.0 (64-bit) with Ubuntu 20.04

**Comment by finswimmer** [comment]
Hello @johan010,

thanks for reporting. We are aware of this. @sdispater wrote this on our discord server:

> Regarding the website, we are aware of the issue. There was (and still is) a problem with the certificate generation while moving to a new provider. We'll keep you posted when this is fixed. The website should be accessible without SSL (http). Sorry about that :frowning:

fin swimmer

**Comment by johan010** [comment]
Ok can I leave this up for people who are not on discord to track the issue?

**Comment by dcarbone** [comment]
> Ok can I leave this up for people who are not on discord to track the issue?

This would be appreciated for those who do not want to use discord on work machines.

**Comment by staticdev** [comment]
Same goes to Chrome.

**Comment by sdispater** [comment]
The website should be available again!

**Comment by staticdev** [comment]
@sdispater seems there is still some problem, look:

![image](https://user-images.githubusercontent.com/1446633/121213308-67552580-c87e-11eb-89d2-6ee0e94feaa5.png)
