### ISSUE TITLE
poetry show --outdated doesn't work properly if version history has mix of strings and numbers

### ISSUE THREAD

**Issue by dekim24** [python-poetry/poetry#4159]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Mac OS X 10.15.7
- **Poetry version**: 1.1.6
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: N/A

## Issue

We have a few private packages in our `pyproject.toml` that follow normal semantic versioning (eg. `2.52.0`), but at some point in the past, some version numbers were accidentally released that are timestamps (eg. `2020-01-14T22.05.35`). The actual latest version of the package in question is `2.61.0`.

I noticed that if you run `poetry show --outdated`, it it shows the latest version available as `2020-01-14T22.05.35`. I'm guessing the reason is because it's directly comparing the "major version numbers" and `"2020-01-14T22" > "2" == True` in python world.

I know it's our mistake in the first place to have these weird timestamp version numbers, but I'm wondering also on poetry's end - in a situation like this, if the `<major>/<minor>/<patch>` version of the current package is a number (or specifically an integer), should the dependency resolver only be comparing against semantic versions of the same type in the registry (rather than comparing the string representation of a valid integer to a string)? In this example that would cause the latest version to (correctly) show up as `2.61.0`.

I can't provide the exact package to reproduce this bug, because it's a private package on a private registry, but you should be able to reproduce it by finding (or creating) a package that has a few versions w/ all numbers, and one or more versions containing a "larger" string as the major version.

**Comment by finswimmer** [comment]
Hey,

this issue is "solved" in that way, that Poetry no longer allows packages with invalid PEP-440 versions in the environment.

fin swimmer
