### ISSUE TITLE
ValueError, whl in cache does not exist when running poetry install again

### ISSUE THREAD

**Issue by Transmitt0r** [python-poetry/poetry#4163]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- Windows 10 1909
- poetry version: 1.2.0a1
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/Transmitt0r/ed8414abd90efaef9d4453ec05c48e1c

## Issue

Hey everyone, I'm having issues when trying to run poetry install via jenkins. poetry config virtualenvs.in-project is true.
The install fails on the second installation attempt (always). It seems that there is an issue with the way caching works. Here is the trace:
Thanks in advance!

```
de\user@PC C:\workspace>poetry install -vvv 
Loading configuration file C:\Users\user\AppData\Roaming\pypoetry\config.toml
Adding repository private (https://artifactory-url.de)
Creating virtualenv envname in C:\workspace\.venv
Using virtualenv: C:\workspace\.venv
Installing dependencies from lock file

Finding the necessary packages for the current system

Package operations: 20 installs, 0 updates, 0 removals, 3 skipped

  • Removing importlib-metadata (4.5.0): Skipped for the following reason: Not currently installed
  • Removing typing-extensions (3.10.0.0): Skipped for the following reason: Not currently installed
  • Removing zipp (3.4.1): Skipped for the following reason: Not currently installed
  • Installing pyparsing (2.4.7)

  Stack trace:

  6  c:\users\user\appdata\roaming\pypoetry\venv\lib\site-packages\poetry\installation\executor.py:244 in _execute_operation
      242| 
      243|             try:
    > 244|                 result = self._do_execute_operation(operation)
      245|             except EnvCommandError as e:
      246|                 if e.e.returncode == -2:

  5  c:\users\user\appdata\roaming\pypoetry\venv\lib\site-packages\poetry\installation\executor.py:321 in _do_execute_operation
      319|             return 0
      320| 
    > 321|         result = getattr(self, f"_execute_{method}")(operation)
      322| 
      323|         if result != 0:

  4  c:\users\user\appdata\roaming\pypoetry\venv\lib\site-packages\poetry\installation\executor.py:462 in _execute_install
      460| 
      461|     def _execute_install(self, operation: Union[Install, Update]) -> int:
    > 462|         status_code = self._install(operation)
      463| 
      464|         self._save_url_reference(operation)

  3  c:\users\user\appdata\roaming\pypoetry\venv\lib\site-packages\poetry\installation\executor.py:498 in _install
      496|             archive = self._download_link(operation, Link(package.source_url))
      497|         else:
    > 498|             archive = self._download(operation)
      499| 
      500|         operation_message = self.get_operation_message(operation)

  2  c:\users\user\appdata\roaming\pypoetry\venv\lib\site-packages\poetry\installation\executor.py:648 in _download
      646|         link = self._chooser.choose_for(operation.package)
      647| 
    > 648|         return self._download_link(operation, link)
      649| 
      650|     def _download_link(self, operation: Union[Install, Update], link: Link) -> Link:

  1  c:\users\user\appdata\roaming\pypoetry\venv\lib\site-packages\poetry\installation\executor.py:676 in _download_link
      674|             archive_hash = (
      675|                 "sha256:"
    > 676|                 + FileDependency(
      677|                     package.name,
      678|                     Path(archive.path) if isinstance(archive, Link) else archive,

  ValueError

  File \C:\Users\user\AppData\Local\pypoetry\Cache\artifacts\92\0f\cf\effdcd5d76a6186df0969f85b3b030284ff8058936d5016540b5258ea3\pyparsing-2.4.7-py2.py3-none-any.whl does not exist

  at c:\users\user\appdata\roaming\pypoetry\venv\lib\site-packages\poetry\core\packages\file_dependency.py:41 in __init__
       37|             except FileNotFoundError:
       38|                 raise ValueError("Directory {} does not exist".format(self._path))
       39| 
       40|         if not self._full_path.exists():
    >  41|             raise ValueError("File {} does not exist".format(self._path))
       42| 
       43|         if self._full_path.is_dir():
       44|             raise ValueError("{} is a directory, expected a file".format(self._path))
       45| 
```

**Comment by Knaifhogg** [comment]
Same issue for me using Windows and Poetry 1.2.0a1 and trying to install pywin32. The file does exist in cache, but I noticed the file path written in the ValueError is "\C:\Users". Is that the issue?

**Comment by gygabyte017** [comment]
Same here, I as well noticed the "\" before the absolute path, may that be the reason why it is not finding the whl even though it exist?

**Comment by vsutardja** [comment]
I ran into this same issue today.

Calling `urllib.parse.urlsplit` on a Windows `file` scheme URI (`file:///C:/Users/...`) leaves the extra leading `/` in the result's `path` attribute.

We can strip this character by passing the malformed `path` into `urllib.request.url2pathname()` to get a valid Windows-style path string.

```
>>> url = 'file:///C:/Users/foo/bar'
>>> split = urllib.parse.urlsplit(url)
>>> split.path
'/C:/Users/foo/bar'
>>> urllib.request.url2pathname(split.path)
'C:\\Users\\foo\\bar'
```

Note that `url2pathname` is only recommended for use on `file` scheme URIs, and it basically just wraps `urllib.parse.unquote` on non-Windows systems.[0] On Windows, it ends up using `nturl2path.url2pathname`.[1]

In fact, `pip` also uses `url2pathname`, along with some extra logic to handle the special case of a Windows UNC path (e.g. for shared network folders).[2]

[0] https://github.com/python/cpython/blob/3.9/Lib/urllib/request.py#L1675
[1] https://github.com/python/cpython/blob/v3.6.1/Lib/nturl2path.py#L3
[2] https://github.com/pypa/pip/blob/9.0.1/pip/download.py#L442

**Comment by MrHappy** [comment]
I ran into this yesterday also... Is there a temporary fix (workaround) until this is fixed permanently?

**Comment by Transmitt0r** [comment]
> I ran into this yesterday also... Is there a temporary fix (workaround) until this is fixed permanently?

My workaround is a short batch script that deletes the poetry cache as part of my ci pipeline before poetry install is executed.

**Comment by jgentil** [comment]
This bug actually gets stranger.  The error message is also incorrect.  If you look here:

https://github.com/python-poetry/poetry-core/blob/ad33bc2f92be03dc5b31a666664903c439fb1173/poetry/core/packages/file_dependency.py#L40-L41

We see that it tests `self._full_path.exists()` but when it raises `ValueError` it puts the raw `self._path` in instead.

I'm not sure why `self._path` is being given a bad URL but I'm working through tracing that still.

**Comment by jgentil** [comment]
I found the culprit!

https://github.com/python-poetry/poetry/blob/e180aab14bdc1d0c9e76b2717fd0de189d26fddd/poetry/installation/executor.py#L673-L680

At this point, `archive` is always going to be a file URL because it's been downloaded and cached.  But `Link.path` is broken for file URLs on Windows, so the patch is as follows:

https://github.com/python-poetry/poetry-core/blob/ad33bc2f92be03dc5b31a666664903c439fb1173/poetry/core/packages/utils/link.py#L9
becomes:
```python

```
and 

https://github.com/python-poetry/poetry-core/blob/ad33bc2f92be03dc5b31a666664903c439fb1173/poetry/core/packages/utils/link.py#L103-L105
becomes
```python
    @property
    def path(self) -> str:
        if self.url.startswith("file:"):
            p = str(url_to_path(self.url))
        else:
            p = urlparse.unquote(urlparse.urlsplit(self.url)[2])
        return p
```

Unfortunately this impacts a number of places where improper path handling happens, mainly in the executor module.  It's a rabbit hole for sure and I need to look at my local edits and compare with a fresh clone to get ALL of the spots I changed code.

**Comment by gwdekker** [comment]
Is it known in which version this was introduced? I am seeing something very similar in poetry 1.1.9.

**Comment by mensch272** [comment]
As a workaround you could add the dependencies to `pyproject.toml` manually, then install them by generating the requirements.txt file.

```bash
poetry lock --no-update
poetry poetry export -f requirements.txt > requirements.txt
pip install -r requirements.txt
```

The downside is that this wont install the dev dependencies.

**Comment by PablocFonseca** [comment]
using version 1.1.10 here, same issue

**Comment by simontuohy** [comment]
Had this as well downgrading to 1.1.8 fixed for me on Windows 10 

python get-poetry.py --version 1.1.8

**Comment by Jackiexiao** [comment]
I downgrade to 1.1.8 then encounter this issue: https://github.com/python-poetry/poetry/issues/4409

**Comment by MadJlzz** [comment]
Also have this issue with 1.1.8 on Windows 10.
My workaround is to go to the path specified, delete the cache and run `poetry install` again.

e.g.
```
PS C:\GithubTech\ngx\ngx-cli> poetry install
Installing dependencies from lock file

Package operations: 32 installs, 0 updates, 0 removals

  • Installing pyparsing (2.4.7)

  ValueError

  File \C:\Users\julie\AppData\Local\pypoetry\Cache\artifacts\92\0f\cf\effdcd5d76a6186df0969f85b3b030284ff8058936d5016540b5258ea3\pyparsing-2.4.7-py2.py3-none-any.whl does not exist

  at c:\users\julie\.pyenv\pyenv-win\versions\3.9.6\lib\site-packages\poetry\core\packages\file_dependency.py:40 in __init__
       36│             except FileNotFoundError:
       37│                 raise ValueError("Directory {} does not exist".format(self._path))
       38│
       39│         if not self._full_path.exists():
    →  40│             raise ValueError("File {} does not exist".format(self._path))
       41│
       42│         if self._full_path.is_dir():
       43│             raise ValueError("{} is a directory, expected a file".format(self._path))
       44│
```

Go to `C:\Users\julie\AppData\Local\pypoetry\Cache`, delete everything.

Run `poetry install` again and:
```
PS C:\GithubTech\ngx\ngx-cli> poetry install
Installing dependencies from lock file

Package operations: 32 installs, 0 updates, 0 removals

  • Installing pyparsing (2.4.7)
  • Installing atomicwrites (1.4.0)
  • Installing attrs (21.2.0)
  • Installing backports.entry-points-selectable (1.1.0)
  • Installing filelock (3.0.12)
  • Installing iniconfig (1.1.1)
  • Installing lazy-object-proxy (1.6.0)
  • Installing packaging (21.0)
  • Installing platformdirs (2.3.0)
  • Installing pluggy (0.13.1)
  • Installing py (1.10.0)
  • Installing six (1.16.0)
  • Installing toml (0.10.2)
  • Installing wrapt (1.12.1)
  • Installing astroid (2.7.3)
  • Installing identify (2.2.14)
  • Installing mccabe (0.6.1)
  • Installing mypy-extensions (0.4.3)
  • Installing pytest (6.2.4)
  • Installing typing-extensions (3.10.0.2)
  • Installing cfgv (3.3.1)
  • Installing nodeenv (1.6.0)
  • Installing isort (5.9.3)
  • Installing pyyaml (5.4.1)
  • Installing virtualenv (20.7.2)
  • Installing mypy (0.910)
  • Installing pylint (2.10.2)
  • Installing pre-commit (2.14.0)
  • Installing yapf (0.31.0)
  • Installing pytest-mock (3.6.1)

Installing the current project: ngx-cli (0.1.0)
```

Hope it helps other people in the meantime!

**Comment by petermbauer** [comment]
> ...
> 
> With these two changes, I can successfully install from the cache.

Can this be made into a PR or is there something else to consider?

**Comment by f0ff886f** [comment]
I made two PRs:

https://github.com/python-poetry/poetry/pull/4651 and https://github.com/python-poetry/poetry-core/pull/222

I made them with the suggestions from this issue. I can not repro @vsutardja's issue that required a fixed executor (when I applied the fixes to Link.path my repro went away). I don't know if the fixes @jgentil is mentioning in executor.py still need to be put into the PRs.
