### ISSUE TITLE
`$POETRY_HOME/env` should respect `$POETRY_HOME`

### ISSUE THREAD

**Issue by zevisert** [python-poetry/poetry#4186]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Preface
The contents of `$POETRY_HOME/env` are currently computed here:
https://github.com/python-poetry/poetry/blob/6bd4f1a6c6416d18749c6a230fb85c61f7ebd2a0/get-poetry.py#L922-L926

Which when custom install locations are used, like `POETRY_HOME=/some/path python get-poetry.py` results in the file containing something like: 
```shell
export PATH="/some/path/bin:$PATH"
```
## Feature Request

In addition to replacing `$HOME`, I would like for the resulting `env` script to also respect the current value of `$POETRY_HOME`. 

My use case is in CI where the build folder isn't the same every time, and I'm using dependency caching to speed up my builds. The dependency caching includes poetry, so for one run the location where my cache containing `$POETRY_HOME` might  get extracted could be `/builds/324ad89e/.cache/poetry` while on the next build it might be `/builds/9820cd21/.cache/poetry`. So, if the first build sets up the cache, the contents of `env` will as follows, resulting in the second job failing to use the cache, since the path to `$POETRY_HOME` is different (and eg on gitlab, defined by `$CI_PROJECT_DIR`).
```shell
export PATH="/builds/324ad89e/.cache/poetry/bin:$PATH"
```

I'd like to see `$POETRY_HOME/env` end up looking something like this, which results in the ability to move `$POETRY_HOME`, and still doesn't depend on `$POETRY_HOME` being defined. 
```shell
POETRY_HOME="${POETRY_HOME:-'/builds/324ad89e/.cache/poetry'}"
export PATH="$POETRY_HOME/bin:$PATH"
```

**Comment by finswimmer** [comment]
Hey @zevisert,

the `get-poetry.py` script is deprecated for more than a year now and cannot be used anymore to install the latest Poetry version.

Suggestions for improvements of the official installer now go to https://github.com/python-poetry/install.python-poetry.org

fin swimmer
