### ISSUE TITLE
Allow content hash to be externally managed

### ISSUE THREAD

**Issue by kislyuk** [python-poetry/poetry#4189]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request
The poetry.lock content-hash is effectively a checksum of the file's contents. This means whenever collaborating in a repo that uses poetry.lock to manage the dependency graph, concurrent changes to any part of the file will cause merge conflicts.

I would like to be able to save the content hash into a separate file that can be managed outside source control, or find another similar solution. This would avoid the expensive and cumbersome merge conflicts that must be manually resolved whenever two developers edit the file in separate branches.

Thanks!

**Comment by dimbleby** [comment]
duplicate #496, can be closed
