### ISSUE TITLE
poetry prompts user for username during publish to PyPI with no auth

### ISSUE THREAD

**Issue by kakarukeys** [python-poetry/poetry#4190]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option). no exception occurred.

- **OS version and name**: MacOS Mojave 10.14.6
- **Poetry version**: 1.1.6
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: it's a default toml with no added values.

## Issue

I've set up a private pypi with no auth on my local PC

```sh
$ poetry config --list 
cache-dir = "..."
experimental.new-installer = true
installer.parallel = true
repositories.foo.url = "http://localhost"
virtualenvs.create = true
virtualenvs.in-project = null
virtualenvs.path = "{cache-dir}/virtualenvs" 
```

The PyPI is not secured by HTTP auth, so there's no need to fill in `auth.toml`.

Running `poetry publish --build -r foo`, I get a prompt:

```sh
poetry publish --build -r foo
Building dep (0.1.3)
  - Building sdist
  - Built dep-0.1.3.tar.gz
  - Building wheel
  - Built dep-0.1.3-py3-none-any.whl

Username: 
```
This is inconvenient for scripting, as user input is required.

workaround:
this command runs successfully with no prompt `poetry publish --build -r foo -u . -p .` it looks wierd.

**Comment by dimbleby** [comment]
it doesn't do this any more, this can be closed
