### ISSUE TITLE
`poetry update` determines latest package versions from pypi.org even when a private repository is specified

### ISSUE THREAD

**Issue by tobi-lipede-oodle** [python-poetry/poetry#4197]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Linux 5.10.42-1-MANJARO
- **Poetry version**: 1.1.6
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: pyproject.toml has some private information

## Issue

We've been using a private CodeArtifact repository for our packages, and have found that occasionally syncing issues between PyPI and CodeArtifact cause poetry issues. Here's an excerpt from my debug log taken shortly after Numpy 1.21.0 was released:

```
codeartifact: 3 packages found for numpy >=1.20.1,<2.0.0
PyPI: No release information found for numpy-0.9.6, skipping
PyPI: No release information found for numpy-0.9.8, skipping
PyPI: No release information found for numpy-1.0.3, skipping
PyPI: No release information found for numpy-1.0.4, skipping
PyPI: No release information found for numpy-1.0b1, skipping
PyPI: No release information found for numpy-1.0b4, skipping
PyPI: No release information found for numpy-1.0b5, skipping
PyPI: No release information found for numpy-1.0rc1, skipping
PyPI: No release information found for numpy-1.0rc2, skipping
PyPI: No release information found for numpy-1.0rc3, skipping
PyPI: No release information found for numpy-1.1.1, skipping
PyPI: No release information found for numpy-1.2.0, skipping
PyPI: No release information found for numpy-1.2.1, skipping
PyPI: No release information found for numpy-1.4.0, skipping
PyPI: 4 packages found for numpy >=1.20.1,<2.0.0
   1: selecting numpy (1.21.0)
```
This occurred before Numpy 1.21.0 had proliferated to CodeArtifact, and so made Numpy uninstallable. I think that the correct behaviour should be to *either* exclusively use the specified repo(s) as index-url, *or* allow the user to specify an alternative extra-index-url (falling back to PyPI if not provided)

**Comment by ralbertazzi** [comment]
HI @tobi-lipede-oodle , the new `priority` flag introduced in Poetry 1.5 should allow you to achieve all kind of repository combinations that you want - please check the documentation. I'll close this for now, feel free to comment if you believe the new options are not satisfactory enough.
