### ISSUE TITLE
`poetry debug info` fails with `RuntimeError: could not find pyproject.toml`

### ISSUE THREAD

**Issue by 9999years** [python-poetry/poetry#4198]
- **OS version and name**: Fedora 34 (Workstation Edition)
- **Poetry version**: 1.2.0a1
- **Python version**: 3.10.0b2

<details>
<summary><code>poetry debug info</code></summary>

<pre><code>Poetry
Version: 1.2.0a1
Python:  3.10.0

Virtualenv
Python:         3.10.0
Implementation: CPython
Path:           NA

System
Platform: linux
OS:       posix
Python:   /home/rturner/.local/share/pypoetry/venv
</code></pre>
</details>

## Issue
Running `poetry debug info` fails with a `RuntimeError` if there's no `pyproject.toml` file in the current directory.
Fortunately, Poetry prints a helpful and accurate error message: `Poetry could not find a pyproject.toml file in /tmp or its parents`.

<details><summary>Stack trace with <code>-vvv</code></summary>

<pre><code>Poetry

  Stack trace:

  12  ~/.local/share/pypoetry/venv/lib/python3.10/site-packages/cleo/application.py:314 in run
       312│
       313│             try:
     → 314│                 exit_code = self._run(io)
       315│             except Exception as e:
       316│                 if not self._catch_exceptions:

  11  ~/.local/share/pypoetry/venv/lib/python3.10/site-packages/poetry/console/application.py:167 in _run
       165│         self._load_plugins(io)
       166│
     → 167│         return super()._run(io)
       168│
       169│     def _configure_io(self, io: IO) -> None:

  10  ~/.local/share/pypoetry/venv/lib/python3.10/site-packages/cleo/application.py:409 in _run
       407│                 io.set_input(ArgvInput(argv))
       408│
     → 409│         exit_code = self._run_command(command, io)
       410│         self._running_command = None
       411│

   9  ~/.local/share/pypoetry/venv/lib/python3.10/site-packages/cleo/application.py:451 in _run_command
       449│
       450│         if error is not None:
     → 451│             raise error
       452│
       453│         return event.exit_code

   8  ~/.local/share/pypoetry/venv/lib/python3.10/site-packages/cleo/application.py:435 in _run_command
       433│
       434│             if event.command_should_run():
     → 435│                 exit_code = command.run(io)
       436│             else:
       437│                 exit_code = ConsoleCommandEvent.RETURN_CODE_DISABLED

   7  ~/.local/share/pypoetry/venv/lib/python3.10/site-packages/cleo/commands/base_command.py:118 in run
       116│         io.input.validate()
       117│
     → 118│         status_code = self.execute(io)
       119│
       120│         if status_code is None:

   6  ~/.local/share/pypoetry/venv/lib/python3.10/site-packages/cleo/commands/command.py:85 in execute
        83│
        84│         try:
     →  85│             return self.handle()
        86│         except KeyboardInterrupt:
        87│             return 1

   5  ~/.local/share/pypoetry/venv/lib/python3.10/site-packages/poetry/console/commands/debug/info.py:19 in handle
        17│             "\n".join(
        18│                 [
     →  19│                     "Version: {}".format(self.poetry.VERSION),
        20│                     "Python:  {}".format(
        21│                         poetry_python_version

   4  ~/.local/share/pypoetry/venv/lib/python3.10/site-packages/poetry/console/commands/command.py:20 in poetry
        18│     def poetry(self) -> "Poetry":
        19│         if self._poetry is None:
     →  20│             return self.get_application().poetry
        21│
        22│         return self._poetry

   3  ~/.local/share/pypoetry/venv/lib/python3.10/site-packages/poetry/console/application.py:119 in poetry
       117│             return self._poetry
       118│
     → 119│         self._poetry = Factory().create_poetry(
       120│             Path.cwd(), io=self._io, disable_plugins=self._disable_plugins
       121│         )

   2  ~/.local/share/pypoetry/venv/lib/python3.10/site-packages/poetry/factory.py:44 in create_poetry
        42│             io = NullIO()
        43│
     →  44│         base_poetry = super(Factory, self).create_poetry(cwd)
        45│
        46│         locker = Locker(

   1  ~/.local/share/pypoetry/venv/lib/python3.10/site-packages/poetry/core/factory.py:35 in create_poetry
        33│         from .pyproject.toml import PyProjectTOML
        34│
     →  35│         poetry_file = self.locate(cwd)
        36│         local_config = PyProjectTOML(path=poetry_file).poetry_config
        37│

  RuntimeError

  Poetry could not find a pyproject.toml file in /tmp or its parents

  at ~/.local/share/pypoetry/venv/lib/python3.10/site-packages/poetry/core/factory.py:395 in locate
      391│             if poetry_file.exists():
      392│                 return poetry_file
      393│
      394│         else:
    → 395│             raise RuntimeError(
      396│                 "Poetry could not find a pyproject.toml file in {} or its parents".format(
      397│                     cwd
      398│                 )
      399│             )
</code></pre>
</details>

Abbreviated stack trace:
```
12  cleo/application.py:314                   in run
11  poetry/console/application.py:167         in _run
10  cleo/application.py:409                   in _run
 9  cleo/application.py:451                   in _run_command
 8  cleo/application.py:435                   in _run_command
 7  cleo/commands/base_command.py:118         in run
 6  cleo/commands/command.py:85               in execute
 5  poetry/console/commands/debug/info.py:19  in handle
 4  poetry/console/commands/command.py:20     in poetry
 3  poetry/console/application.py:119         in poetry
 2  poetry/factory.py:44                      in create_poetry
 1  poetry/core/factory.py:35                 in create_poetry
at  poetry/core/factory.py:395                in locate
```

**Comment by 9999years** [comment]
This might not be a bug, per-se -- I'm seeing the virtualenv info in the `debug info` output -- but it would be nice to get the _other_ debug info at least.

**Comment by 9999years** [comment]
Actually, it looks like it fails while getting the Poetry version (see the `poetry/console/commands/debug/info.py:19` frame in the stack trace), which makes me suspect this is unexpected behavior.

**Comment by dimbleby** [comment]
behaviour today is
```
$ ~/.virtualenvs/poetry/bin/poetry debug info

Poetry

Poetry could not find a pyproject.toml file in /home/dimbleby or its parents
```
this can be closed
