### ISSUE TITLE
After the installation of poetry via the new script `install-poetry.py` poetry ignores pyenv local python version

### ISSUE THREAD

**Issue by skei0** [python-poetry/poetry#4199]
- [x ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

- **OS version and name**: Kernel: 5.4.0-74-generic x86_64 bits: 64 compiler: gcc v: 9.3.0 Desktop: MATE 1.24.0 
           wm: marco dm: LightDM Distro: Linux Mint 20.1 Ulyssa base: Ubuntu 20.04 focal
- **Poetry version**: 1.1.6

## Issue
After the installation of poetry via the new script `install-poetry.py` poetry ignores pyenv local python version. I don’t know why. I checked those issue [1](https://github.com/python-poetry/poetry/issues/1870), [2](https://github.com/python-poetry/poetry/issues/651), [3](https://github.com/python-poetry/poetry/issues/172) but nothing work for me. After uninstalling and installing via old script `get-poetry.py` all semis to work. Except of this bug mentioned [hier](https://github.com/python-poetry/poetry/issues/4166).

**Comment by finswimmer** [comment]
Hello @skei0,

please see @sdispater's and my comment in:

* https://github.com/python-poetry/poetry/issues/651#issuecomment-864533910
* https://github.com/python-poetry/poetry/issues/4187#issuecomment-863881765

fin swimmer

**Comment by zyv** [comment]
Related to #4207?

**Comment by theirix** [comment]
Seems like only `poetry env use "/path/to/pyenv/python"` works. Activating via [standard pyenv ways](https://github.com/pyenv/pyenv#choosing-the-python-version) like env var or `.python-version` does not work. 

Reproduced with 1.1.7 and a new `install-poetry.py` installer. The effective version can be checked via `poetry env info | grep '^Python'`.

The unrelated but important thing - I think the [documentation page](https://python-poetry.org/docs/managing-environments/) must be updated to omit `pyenv local` instructions for a while. File an issue?

**Comment by techdragon** [comment]
Not working well with `pyenv` like previous versions did, feels more like the sort of thing that belongs in a a `x.0.0` major release. This significantly affects how I have to manage my python environments in order to have poetry just recognise a version. 

In previous behaviour I could have a 3.6,3.7,3.8,3.9 all installed via `pyenv` and poetry would automatically use the right one for the python version inside `pyproject.toml`, it was the best python environment management has ever been. While the new changes are I'm sure (from what I have read of the rationale, and my experience as a fellow python dev who has looked into this sort of thing) a significant improvement in maintainability... it is a degradation of functionality for the end users that needs promptly addressing. So, with that In mind, how can I help? Anyone got PRs for this that need testing or extra eyeballs on potential fixes?

**Comment by vikigenius** [comment]
This seems to be a complete breaking change, and the documentation and readme should reflect this.
Previously just `poetry install` would automatically determine the correct python version I set using pyenv.

But now, I have to do `poetry env use` and then a `poetry install`

And after the documentation reflects this, as @techdragon suggested this is a big degradation of functionality here, it would be good to have an issue tracking this, if not already there.

**Comment by Kurt-von-Laven** [comment]
@vikigenius, refer to [#1888](https://github.com/python-poetry/poetry/issues/1888) (linked above), the 3 issues already linked to it, as well as [#651](https://github.com/python-poetry/poetry/issues/651#issuecomment-864902413) and [#4187](https://github.com/python-poetry/poetry/issues/4187#issuecomment-863881765). I am not affiliated with Poetry, but @sdispater, the author, has mentioned this change was made to reduce Poetry's maintenance burden and improve security. To my knowledge, there is presently no intention of changing it back.

**Comment by istrupin** [comment]
` poetry env use $(pyenv which python)` seems to get me unblocked, but it would be nice for this to "just work", or at the very least, for it to be included in the docs, since they imply that local pyenv settings should get picked up.

**Comment by finswimmer** [comment]
Everyone interested can try out https://github.com/python-poetry/poetry/pull/4852 and give feedback :)
