### ISSUE TITLE
`poetry install` reported python version and installed venv python version differ

### ISSUE THREAD

**Issue by stohrendorf** [python-poetry/poetry#4207]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: opensuse leap 15.3 / conda
- **Poetry version**: 1.1.6
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://github.com/moneymeets/ghd/blob/6449eb2ef0cffe63d6f4ff2502ffab688c0305d4/docker/pyproject.toml

## Issue
I used the new installer, which installed `poetry` using python 3.8.5. Additionally, I have installed conda, with a python 3.9.5 virtual environment, which is prefixed to `$PATH` so it is preferred over the system installed python version - this was added _after_ installing `poetry`.

When doing a `poetry install` without any existing prior virtualenv, the following is printed to the console:
```
$ poetry install
The currently activated Python version 3.8.5 is not supported by the project (3.9.5).
Trying to find and use a compatible version. 
Using python3 (3.9.5)
Creating virtualenv ghd-m2Y1OWxf-py3.9 in /home/steffen/.cache/pypoetry/virtualenvs
Installing dependencies from lock file

Package operations: 55 installs, 0 updates, 0 removals
<<< snip >>>
```

poetry correctly reports that it uses python 3.9.5, as this exact version is specified in `pyproject.toml`. However...
```
$ /home/steffen/.cache/pypoetry/virtualenvs/ghd-m2Y1OWxf-py3.9/bin/python --version
Python 3.8.5
/usr/bin/python3 --version
Python 3.6.13
/home/steffen/.local/share/pypoetry/venv/bin/python3 --version
Python 3.8.5
$ which python3
/home/steffen/miniconda3/envs/python-3.9/bin/python3
$ python3 --version
Python 3.9.5
```
which is clearly *not* python 3.9.5. The creation of the virtualenv can be done correctly if I'm doing a `poetry env use $(which python3)`, but this shouldn't be necessary as `poetry` reported it was using the correct version.

**Comment by finswimmer** [comment]
Hey,

this should now work correctly by setting `virtualenvs.prefer-active-python` to `true`.

fin swimmer
