### ISSUE TITLE
env remove cannot be used when virtualenvs.in-project is true  

### ISSUE THREAD

**Issue by dclayh** [python-poetry/poetry#4211]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**:  OSX 10.15.7 (also occurs on various Linux flavors)
- **Poetry version**: 1.1.6
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: Can be reproduced with the generic `poetry new` file.

## Issue
When `virtualenvs.in-project` is set to `true`, there is no way to remove the virtualenv with a `poetry env remove` command. Obviously it could be removed with `rm -rf .venv`, but why be inconsistent? Furthermore, with this setting there's no way to support multiple concurrent venv installations (as the venv is wiped on any new `poetry env use` command). 

### Steps to reproduce
```
poetry new poetry_test
cd poetry_test
poetry config virtualenvs.in-project true
poetry install
poetry env remove -vvv 3.7
```

### Proposed Fix
The cleanest fix would be to install venvs in standard-named subfolders of `.venv` when `virtualenvs.in-project = true`. E.g. fr the example above, `.venv/poetry-test-zx0a_HHx-py3.7`. Or if that breaks the `venv` standard, then something like `.venv-poetry/poetry-test-zx0a_HHx-py3.7`. This would allow `poetry env remove` to work as normal, and multiple concurrent venvs to be supported, while still adhering to the spirit of the `virtualenvs.in-project` setting (i.e. the venv files are contained within the project root directory).

An alternative, minimal fix would be to have `poetry env remove X` simply execute `rm -rf .venv` as long as X matches the installed python version.

**Comment by finswimmer** [comment]
Hello @dclayh,

the topic about removing in-projects via `poetry env remove` is already discussed at https://github.com/python-poetry/poetry/issues/2124. A PR exists but must be reviewed (https://github.com/python-poetry/poetry/issues/2124).

The topic about multiple in-projects venv is also already discussed in https://github.com/python-poetry/poetry/issues/2124.

fin swimmer
