### ISSUE TITLE
Needs a `--user` flag to avoid virtualenv issues

### ISSUE THREAD

**Issue by sboomi** [python-poetry/poetry#4222]
https://github.com/python-poetry/poetry/blob/22c3aaddc20ad74d3633738093f685fd6dbb998a/install-poetry.py#L519

When I installed the new version of Poetry, I modified the subprocess command to include a `--user` flag, as per virtualenv's [recommendation](https://virtualenv.pypa.io/en/latest/installation.html):

> Alternatively you can install it within the global Python interpreter itself (perhaps as a user package via the `--user` flag). Be cautious if you are using a python install that is managed by your operating system or another package manager. `pip` might not coordinate with those tools, and may leave your system in an inconsistent state. Note, if you go down this path you need to ensure pip is new enough per the subsections below:

```shell
python -m pip install --user virtualenv
python -m virtualenv --help
```

Not doing so would return a `ModuleNotFoundError` since it can't find the `virtualenv.seed.via_app_data` module.

**Comment by dimbleby** [comment]
the code in question has long since disappeared, this can be closed
