### ISSUE TITLE
poetry version manager

### ISSUE THREAD

**Issue by tony** [python-poetry/poetry#4235]
I have some projects using poetry 1.0 (due to other teammates being on it), but I have other projects I'd like to use 1.1, and so on.

- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

Different projects have different Poetry lockfile versions. However it looks like systems can only support one poetry at a time.

- Can poetry support multiple versions on a system at once? (nvm / pyenv / asdf style?)
- Can projects automatically shim and use the project's poetry version?  Like `nvm`'s `.nvmrc` has?
- Can `poetry` command itself be a shim that points to 1.0, 1.1, etc. depending on environment?

**Comment by samueldeklund** [comment]
You can use [`asdf`](https://asdf-vm.com/) to manage the version of `poetry` that gets used per directory. 

If you install `poetry` with `asdf install poetry <version>`, then you can do `asdf local poetry <version>` in a particular folder. Then `asdf` should create a `.tool-versions` file in that folder with the contents `poetry <version>`. 

Of course, this is outside the `pyproject.toml` file, so poetry wouldn't pick up the change itself, but `asdf` would, so it's effectively the same thing. 

Of course, this doesn't solve this for anyone who doesn't use asdf.

**Comment by tony** [comment]
@samueldeklund There is a VM for poetry? Wow!

https://github.com/asdf-community/asdf-poetry

Thank you so much for linking this in!  I will give this a shot.

**Comment by tony** [comment]
@samueldeklund Thank you!

`~/.tool-versions`:

`poetry 1.0.10 1.1.7`

Works like a charm!  I am going to close this for now as this seems adequate for me.  If anyone else bumps into this please feel free to make a separate issue
