### ISSUE TITLE
recommended install command installs older version

### ISSUE THREAD

**Issue by dimaqq** [python-poetry/poetry#4237]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

## Issue

I ran `~ > curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python -` as recommended by the project readme.

That installed poetry version 1.1.5

I was able to `poetry self update` to 1.1.7 immediately after.

I'm curious why 1.1.7 was not installed right away.

### pro forma

- **OS version and name**: macOS 11.4
- **Poetry version**: 1.15 vs 1.1.7
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: N/A

**Comment by finswimmer** [comment]
Hello @dimaqq,

this is weird. I'm not able to reproduce it. Does this still happens to you or does it disappear somehow?

fin swimmer

**Comment by dimaqq** [comment]
Yes, my environment: `macOS 11.4`; `Python 3.9.5` (universal2, from python.org);

```
Installing Poetry (1.1.7): Installing Poetry
```

Then it shows:

```
Installing Poetry (1.1.7): Done

Poetry (1.1.7) is installed now. Great!
```

The binary gets installed into `~/Library/Python/3.9/bin` and its guts in `~/Library/Application Support/pypoetry`

I think I've cleaned any possible caches, though maybe there's some download cache that I'm not aware of?

**Comment by dimaqq** [comment]
I can also run the installed with `-p` in which case I get `Poetry (1.2.0a1)`  🤔
