### ISSUE TITLE
`poetry new` is not using recommended pattern for __version__ variable

### ISSUE THREAD

**Issue by polvoazul** [python-poetry/poetry#4238]
> Closing this as importlib.metadata is the way to go. A possible pattern to support python <3.8 and >=3.8 I described here.

If this is the recommended solution, then `poetry new` should be updated to use it. Currently, the `poetry new` command adds `__version__` to `__init__.py`, but then `poetry version` doesn't update it. This incompatibility between the two commands is confusing for me, and I imagine other newcomers.

_Originally posted by @albrow in https://github.com/python-poetry/poetry/issues/144#issuecomment-780943725_

**Comment by finswimmer** [comment]
Hello @polvoazul,

with poetry 1.2.0a1 will not add any `__version__` to the `__init__.py`. (https://github.com/python-poetry/poetry/pull/2768)

fin swimmer
