### ISSUE TITLE
`poetry env use /usr/bin/python3.7` creates environment with actual version of python3.6

### ISSUE THREAD

**Issue by pryadchenko** [python-poetry/poetry#4240]
- [ x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [ x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: 18.04.1-Ubuntu
- **Poetry version**: 1.1.7
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/pryadchenko/0c82e3e8e1c8e19d275bccc1f7cd3901

## Issue

Hello everyone. I'd try to use specific version of python via `poetry env use /usr/bin/python3.7`. This creates some folder named like `~/.cache/pypoetry/virtualenvs/calibration-bLctCmPV-py3.7` but with binaries of python3.6. I dont use neither pyenv nor virtualenv, just have both version systemwide (i.e. 3.6 and 3.7).
I expect that specifying python version by `poetry env use` must create virtual environment whith the specified version of python.
```
poetry env info -vvv  

Virtualenv
Python:         3.6.9
Implementation: CPython
Path:           /home/vpryadchenko/.cache/pypoetry/virtualenvs/calibration-bLctCmPV-py3.7
Valid:          True

System
Platform: linux
OS:       posix
Python:   /usr
```

**Comment by simonrouse9461** [comment]
I have the same problem, `poetry env use system` doesn't work as well.

**Comment by finswimmer** [comment]
Hello @pryadchenko ,

you haven't come back to this issue for a long while. So I assume this is solved in the meantime and I can close this ticket.

Also lots of improvements were made in this area in Poetry 1.2.

Feel free to leave a comment if you disagree.

fin swimmer
