### ISSUE TITLE
No correct way to install Poetry?

### ISSUE THREAD

**Issue by remram44** [python-poetry/poetry#4248]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate (though #4147 is related)

## Issue

The README recommends `install-poetry.py`. The docs recommend `get-poetry.py`. In either case, there is a warning message letting the user know that using that installer will not support upgrading to later versions. The `get-poetry.py` script, although the website claims "This is the recommended way of installing poetry.", literally states on use "This installer is deprecated."

**I don't think installers should be both recommended and deprecated**, and I think enough information should be given to users to determine whether they have done the wrong thing.

![website screenshot](https://user-images.githubusercontent.com/426784/124360897-46bc8900-dbfa-11eb-9152-78dd94857419.png)

![terminal screenshot](https://user-images.githubusercontent.com/426784/124360847-fe04d000-dbf9-11eb-9fb6-16fdc0cd9e55.png)

Proposed actions:

* If there is no way to update from 1.2 using either installer, I think that's fine, but the warning in the installation script should make it clear that it is for technical reasons and not because they grabbed the wrong script.
* The README here should match the website, and either both recommend `get-poetry.py` (mentioning that the recommended way will change for 1.2 is fine) or both `install-poetry.py` (with whatever caveats)
* If the `get-poetry.py` is still the recommended way to install current Poetry (even if that will change), as per website, don't claim it is "deprecated". A tool is only "deprecated" once its replacement is generally available.

**Comment by rlam3** [comment]
@remram44 I agree with your discussion here. This is happening similar to Docker installation approach to installing this poetry

https://github.com/python-poetry/poetry/discussions/1879#discussioncomment-346113

**Comment by 13steinj** [comment]
I think the major issue here is that the master branch is out of sync with the website, whereas the website assumes the master branch is the (most current) release branch.

Perhaps the git-flow (pun intended) of things here is just wrong. Perhaps have a `release` branch that always points to the most current release. The website can reference it as necessary. The website is generated off of this branch.

And master (rename or not to develop) is used as the development branch. 

All that said and done, if get_poetry.py should only be available when 1.2 is out as a release. Whereas currently, it is out as an alpha, with install_poetry meant to only install the alpha.

The "recommended" installer should never install alpha software.

**Comment by PaluMacil** [comment]
This caused me a good deal of time and frustration. The install instructions pointing to the website and then getting a warning that I was using a bad installer sent me in circles with install/uninstall and tweaking of Python and env vars. Finally I noticed that the script names were different, and a short time later I think I figured out which installer I was supposed to use.

**Comment by finswimmer** [comment]
With #4257 and #4249 I hopefully could fix the irritations.
