### ISSUE TITLE
Update packages with update command is not working as expected

### ISSUE THREAD

**Issue by senciucserban** [python-poetry/poetry#4251]
- **OS version and name**: Ubuntu 20.04
- **Poetry version**: 1.1.7

## Issue
I have a package made with poetry and I have a dependency for `mypy` .
Using `poetry show` it said: `mypy 0.790` but the latest version is `0.910`.

I want to update the mypy to latest version, I tried: `poetry update` and `poetry update mypy` but nothing...
In order to update it to latest version I used:
* `poetry remove mypy`
* `poetry add mypy --optional`

When I run `poetry update mypy -vvv` I saw that :
```
1: fact: jara-utils depends on mypy (^0.790)
1: derived: mypy (>=0.790,<0.791)
```

[Toml file](https://github.com/senciucserban/jara-utils/blob/main/pyproject.toml) | [lock file](https://github.com/senciucserban/jara-utils/blob/main/poetry.lock)

There is any way to update the package using `update` command? Also I noticed this also if the package is NOT optional.

**Comment by finswimmer** [comment]
Hello @senciucserban ,

a `poetry update` updates the package withing the version range given in your `pyproject.toml`. For `mypy` you have `^0.790` which means `>=0.790,<0.791`.

To upgrade to the latest version outside the version constraint in your `pyproject.toml` you have to use `poetry add mypy@latest`.

fin swimmer

**Comment by senciucserban** [comment]
Hey @finswimmer ,

Nope, not working... 

`poetry update mypy@latest -vvv` said the same thing as `poetry update mypy`.

You have the repo there, can you try to clone it and update the mypy?

Again, the only solution I found was to remove and add the package again.

Thank you

**Comment by finswimmer** [comment]
It must be `poetry add` and not `poetry update` ;)

**Comment by senciucserban** [comment]
ohhh, correct. Thank you.

And when a new version of `mypy` will be released, `poetry update` will do the trick? Or I need again to run `poetry add mypy@latest`?
