### ISSUE TITLE
Poetry uninstall thinks poetry is not currently installed, but it is

### ISSUE THREAD

**Issue by ExtraE113** [python-poetry/poetry#4253]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

- **OS version and name**: Windows 10 Home 10.0.19041 N/A Build 19041
- **Poetry version**: 

## Issue

When I run (in powershell) `(Invoke-WebRequest -Uri https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py -UseBasicParsing).Content | python3 - --uninstall`
The installer/uninstaller prints `Poetry is not currently installed.`

However, when I run `poetry` or `poetry --version` it is clear that poetry *is* installed, even after restarting the shell.

`poetry` output:

```
Poetry version 1.1.7

USAGE
  poetry [-h] [-q] [-vá[<...>]] [-V] [--ansi] [--no-ansi] [-n] <command> [<arg1>] ... [<argN>]

ARGUMENTS
  <command>              The command to execute
  <arg>                  The arguments of the command

GLOBAL OPTIONS
  -h (--help)            Display this help message
  -q (--quiet)           Do not output any message
  -v (--verbose)         Increase the verbosity of messages: "-v" for normal output, "-vv" for more verbose output and "-vvv" for debug
  -V (--version)         Display this application version
  --ansi                 Force ANSI output
  --no-ansi              Disable ANSI output
  -n (--no-interaction)  Do not ask any interactive question

AVAILABLE COMMANDS
  about                  Shows information about Poetry.
  add                    Adds a new dependency to pyproject.toml.
  build                  Builds a package, as a tarball and a wheel by default.
  cache                  Interact with Poetry's cache
  check                  Checks the validity of the pyproject.toml file.
  config                 Manages configuration settings.
  debug                  Debug various elements of Poetry.
  env                    Interact with Poetry's project environments.
  export                 Exports the lock file to alternative formats.
  help                   Display the manual of a command
  init                   Creates a basic pyproject.toml file in the current directory.
  install                Installs the project dependencies.
  lock                   Locks the project dependencies.
  new                    Creates a new Python project at <path>.
  publish                Publishes a package to a remote repository.
  remove                 Removes a package from the project dependencies.
  run                    Runs a command in the appropriate environment.
  search                 Searches for packages on remote repositories.
  self                   Interact with Poetry directly.
  shell                  Spawns a shell within the virtual environment.
  show                   Shows information about packages.
  update                 Update the dependencies as according to the pyproject.toml file.
  version                Shows the version of the project or bumps it when a valid bump rule is provided.

```

I have tried the steps here: https://github.com/python-poetry/poetry/issues/644 but they have not worked. One person there mentioned using the wrong python version. Running the above command with `python` instead of `python3` results in a syntax error from the type hints in the installer, so I don't think that's it.

**Comment by ExtraE113** [comment]
I think this may be because I accidentally installed poetry originally from a venv created by pycham, but I've sense deleted that project... so I can't get back into that venv.

**Comment by ExtraE113** [comment]
I *think* I have a workaround. I read through the poetry uninstall code, and all it seems to be doing is: 
1. Removing the files from the disc
2. Removing poetry from the path

So I just did that by hand. I found where poetry was by running `where poetry` in command prompt.

The relevant code from the installer, for reference:
```python3
    def uninstall(self) -> int:
        if not self._data_dir.exists():
            self._write(
                "{} is not currently installed.".format(colorize("info", "Poetry"))
            )

            return 1

        version = None
        if self._data_dir.joinpath("VERSION").exists():
            version = self._data_dir.joinpath("VERSION").read_text().strip()

        if version:
            self._write(
                "Removing {} ({})".format(
                    colorize("info", "Poetry"), colorize("b", version)
                )
            )
        else:
            self._write("Removing {}".format(colorize("info", "Poetry")))

        shutil.rmtree(str(self._data_dir))
        for script in ["poetry", "poetry.bat"]:
            if self._bin_dir.joinpath(script).exists():
                self._bin_dir.joinpath(script).unlink()

        return 0
```

**Comment by finswimmer** [comment]
Hello @ExtraE113,

I don't understand how you've installed poetry before. Can you explain it a little bit more, please?

To use the `install-poetry.py` script for deinstalling, poetry has to be installed by this script before. If you've used `get-poetry.py` instead to install or any other method this will not work.

fin swimmer

**Comment by ExtraE113** [comment]
That might have been it, I might have used get-poetry.py. Either way, I've fixed my problem (for now at least, maybe this will bite me later). Closing.

**Comment by genagurbanguliyev** [comment]
I deleted all poetry files from all `dir`s. (They're not a lot)
in ubuntu:
go Computer and search with `poetry` keyword
go all poetry files directories and open terminal with that directory and delete:
```sh
# for remove file with root permission:
sudo rm <filename>

# for remove folder with files inside:
sudo rm -rf <foldername>
```

after that open new terminal and check:
`poetry --version`

Happy hack!
