### ISSUE TITLE
Packaging 21.0

### ISSUE THREAD

**Issue by frenzymadness** [python-poetry/poetry#4264]
According to my testing in Fedora with more than 180 RPM packages, poetry and poetry-core packages are compatible with the latest packaging version 21.0. The main reason for the major release is that packaging 21 no longer supports Python < 3.6.

So I think that you can update it.

- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

**Comment by hroncok** [comment]
> According to my testing in Fedora with more than 180 RPM packages, poetry and poetry-core packages are compatible with the latest packaging version 21.0.

I am afraid there is a problem: https://src.fedoraproject.org/rpms/poetry/pull-request/17#comment-83627

**Comment by hroncok** [comment]
Packaging 21.0 also drops support for Python 2.7 and Poetry executes a file from it with the venv's Python interpreter:

https://github.com/python-poetry/poetry/blob/cd511298a9a0c041ec365adb3cb1bbf3e8eab7d2/poetry/utils/env.py#L1491-L1519

**Comment by sammko** [comment]
#5216 is a result of packaging 21. (Archlinux testing repo). Downstream https://bugs.archlinux.org/task/73867
