### ISSUE TITLE
Use canonical PEP440 versions

### ISSUE THREAD

**Issue by ulope** [python-poetry/poetry#4277]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request
Related: #3752

Currently the version numbers generated by the `poetry version` command are PEP440 compliant but don't follow the recommended 'canonical' style but rather use some of the allowed alternative syntaxes.

It would be nice if poetry would generate version numbers according to the [canonical scheme](https://www.python.org/dev/peps/pep-0440/#public-version-identifiers).

**Comment by dimbleby** [comment]
this is fixed in more recent versions
