### ISSUE TITLE
Add an option to 'ignore' a package when doing `poetry show --outdated`

### ISSUE THREAD

**Issue by sevaho** [python-poetry/poetry#4300]
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

Atm I am using [piprot](https://github.com/sesh/piprot) to give a list of outdated packages. I have a package which I don't what to update so I can add `# norot` next to the package in my requirements.txt file. This way piprot will skip checking this package.

Is it possible to add this as well to poetry?

Thanks in advance

**Comment by Secrus** [comment]
Let me clarify. You want Poetry to change its behavior to match a specific tool you are using?
