### ISSUE TITLE
Have poetry shell accept a command line to execute first in the new shell

### ISSUE THREAD

**Issue by CmdQ** [python-poetry/poetry#4306]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

I would like Poetry's shell command to also accept a command line to execute first in the new shell.

Just like

- `bash -c ls`
- `python -c 'print("Hi from Python")'`

with the difference of __keeping the shell open__ afterwards.

### Why?

This would be very helpful for automation. Have a look at this line from a Jenkinsfile

    sh '(cd docs && make html) && (cd build/sphinx/html && zip -r ../../product-docs .)'

Of course I could insert a `poetry run` right before the `make`, but it isn't immediately obvious where it's needed (especially longer command like they do occur in build scripts).

### How?

There were several times already—also in the terminal—where I wished I could just

    poetry shell -- (cd docs && make html) && (cd build/sphinx/html && zip -r ../../product-docs .)

It should

1. start a sub-shell and
2. execute the command line after the double dashes and
3. keep the (new) prompt open for me to continue executing commands.

That would also make the Jenkinsfile easier because I then could create a custom `shPoetry` that executes whatever is passed in a new Poetry shell.

### Failed

I already tried all kinds of piping to work around this limitation, but to no avail

```sh
echo isort | po shell
Spawning shell within /home/tsbr/src/code.lumira.mp-labs.de/adk-analytics/tsv-tools/.venv

  error

  (25, 'Inappropriate ioctl for device')

  at ~/.poetry/lib/poetry/_vendor/py3.7/pexpect/pty_spawn.py:788 in interact
      784│         # Flush the buffer.
      785│         self.write_to_stdout(self.buffer)
      786│         self.stdout.flush()
      787│         self._buffer = self.buffer_type()
    → 788│         mode = tty.tcgetattr(self.STDIN_FILENO)
      789│         tty.setraw(self.STDIN_FILENO)
      790│         if escape_character is not None and PY3:
      791│             escape_character = escape_character.encode('latin-1')
      792│         try:
```

### Final Words

I think this would make a great addition and it shouldn't clash with/break anything as the shell command doesn't know many arguments and they're all simple anyway.

**Comment by finswimmer** [comment]
Hello @CmdQ,

IMO this is out of scope for Poetry. But I guess https://github.com/nat-n/poethepoet might be suitable for your usecase.

fin swimmer
