### ISSUE TITLE
Feature request: compiler options for packages

### ISSUE THREAD

**Issue by rproskuryakov** [python-poetry/poetry#4310]
## Feature Request
Hello! I develop a machine learning package for experimentation and stuck with the following problem. Some packages from pip (especially ML-related packages, e.g. pandas, PyTorch e.t.c) are really big if I want to create a production-ready Docker image with poetry. But that could be potentially solved by using compiler options during their installation. Is there an option to add such a feature to poetry? I guess that option is needed by many people cause a lot of python packages for ML take a lot of disk space and it's crucial for developers to be able to provide small Docker images for production purposes.

**Comment by Secrus** [comment]
Poetry uses PEP 518 spec for installation, and this doesn't include any compiler options AFAIK. The packages you are talking about should expose the options in some other way (environment variables for example).
