### ISSUE TITLE
Verbose, somewhat misleading error trying to add `scipy`

### ISSUE THREAD

**Issue by dimaqq** [python-poetry/poetry#4316]
`poetry init` generates a `pyproject.toml` file with a reasonable `python = "^3.9"` tool dependency.

trying to `poetry add scipy` fails with an error:

```py
> poetry add scipy
Using version ^1.7.0 for scipy

Updating dependencies
Resolving dependencies... (0.0s)

  SolverProblemError

  The current project's Python requirement (>=3.9,<4.0) is not compatible with some of the required packages Python requirement:
    - scipy requires Python >=3.7,<3.10, so it will not be satisfied for Python >=3.10,<4.0

  Because no versions of scipy match >1.7.0,<2.0.0
   and scipy (1.7.0) requires Python >=3.7,<3.10, scipy is forbidden.
  So, because randomness-testsuite depends on scipy (^1.7.0), version solving failed.

  at ~/Library/Application Support/pypoetry/venv/lib/python3.9/site-packages/poetry/puzzle/solver.py:241 in _solve
      237│             packages = result.packages
      238│         except OverrideNeeded as e:
      239│             return self.solve_in_compatibility_mode(e.overrides, use_latest=use_latest)
      240│         except SolveFailure as e:
    → 241│             raise SolverProblemError(e)
      242│
      243│         results = dict(
      244│             depth_first_search(
      245│                 PackageNode(self._package, packages), aggregate_package_nodes

  • Check your dependencies Python requirement: The Python requirement can be specified via the `python` or `markers` properties

    For scipy, a possible solution would be to set the `python` property to ">=3.9,<3.10"

    https://python-poetry.org/docs/dependency-specification/#python-restricted-dependencies,
    https://python-poetry.org/docs/dependency-specification/#using-environment-markers
```

for a new user, this is quite hard to understand:
* at first it seems odd why poetry can't find intersection between `>=3.7,<3.10` and `>=3.9,<4.0`
* then it's quite confusing what `>=3.10,<4.0` is
* then there's a traceback, which is a red herring
* finally, there's a practical advice about "python property", which is useful
* however, I feel that most users wouldn't necessarily know what that is or where it is defined
* the actual definition of "python property" is presented in a different format
* ultimately, why does `poetry` complain about a hypothetical, future, unreleased version of python?

I wish this error was not tripped at all, given that current Python version is OK.

If it must be tripped, I wish that the error was more to the point and less verbose, e.g.:
* the project is set up with `python = "^3.9"`
   * for Python 3.9.x, I would use scipy 1.7.0
   * for Python 3.10.x, I can't find usable scipy version, STOP

**Comment by clintonroy** [comment]
I think: ^3.9 allows 3.10, which is incompatible with scipy. It's nothing to do with your currently installed version of python, only to do with what's specified in pyproject.toml.
Try ~3.9 as the python version.

**Comment by gaoming714** [comment]
@clintonroy You are correct.

I had the same problem, and I suspected that poetry had some minor problem with the string "(>,3.9, <4.0) "but could have installed it after changing version (in file pyproject.toml)  to "~3.9"

**Comment by finswimmer** [comment]
Hello @gaoming714 ,

`~3.9` is not the same as `>3.9, <4.0`. It means `>=3.9,<3.10`.

Regarding the original issue: It's exactly like @clintonroy said.

fin swimmer

**Comment by lassepe** [comment]
I guess what is confusing here is that python is a somewhat special dependency here: In contrast to normal package dependencies for which poetry only tries to find *some* version that satisfies all constraints, for python it requires that the specified dependencies work for *all* python versions in the specified bounds. I think that makes sense but it also took me a minute to figure out. Maybe the error message could be enhanced to clarify this?

**Comment by stefansjs** [comment]
This seems similar to #1431

I'm having essentially the same issue with numpy (perhaps because they depend on each other 😇).

I completely understand and agree with the notion that requiring support for a given python version should prevent depending on incompatible packages. In my case I deploy to production servers that have python3.6 available, which means when I declare "please support as low as python3.6" I really hope poetry tells me "you can't have that package AND support python3.6" 🙌

However, it seems at least misleading, at most wrong, to fail on a package that does support my python constraints _in other versions_. For example, when I do `poetry add numpy`, the latest version of numpy does not support python 3.6. But I'm 100% sure that some version does. 

To me it _does_ seem like a bug that when you do `poetry add` it imposes a `^latest` constraint. That's the part that seems wrong to me. 

```
$ poetry add numpy -vvv
Using virtualenv: .venv
PyPI: No release information found for numpy-0.9.6, skipping
PyPI: No release information found for numpy-0.9.8, skipping
PyPI: No release information found for numpy-1.0.3, skipping
PyPI: No release information found for numpy-1.0.4, skipping
PyPI: No release information found for numpy-1.0b1, skipping
PyPI: No release information found for numpy-1.0b4, skipping
PyPI: No release information found for numpy-1.0b5, skipping
PyPI: No release information found for numpy-1.0rc1, skipping
PyPI: No release information found for numpy-1.0rc2, skipping
PyPI: No release information found for numpy-1.0rc3, skipping
PyPI: No release information found for numpy-1.1.1, skipping
PyPI: No release information found for numpy-1.2.0, skipping
PyPI: No release information found for numpy-1.2.1, skipping
PyPI: No release information found for numpy-1.4.0, skipping
PyPI: 76 packages found for numpy *
Using version ^1.21.2 for numpy
...
```

Why did poetry decide that `^1.21.2` was the right constraint instead of `>1.4.0`?

However, If I do impose an upper bound of any kind it does seem to resolve correctly. It seems like this should be the default (or fallback?) behavior for new pacakges. Especially for a fresh package, where I don't yet know what my dependency constraints are.

```
% poetry add 'numpy<1.21.1' -vv 
Using virtualenv: .venv

Updating dependencies
Resolving dependencies...
   1: fact: android-latency is 0.1.0
   1: derived: android-latency
   1: fact: android-latency depends on numpy (<1.21.1)
   1: selecting android-latency (0.1.0)
   1: derived: numpy (<1.21.1)
   1: fact: numpy (1.21.0) requires Python >=3.7
   1: derived: not numpy (1.21.0)
   1: fact: numpy (1.20.3) requires Python >=3.7
   1: derived: not numpy (1.20.3)
   1: fact: numpy (1.20.2) requires Python >=3.7
   1: derived: not numpy (1.20.2)
   1: fact: numpy (1.20.1) requires Python >=3.7
   1: derived: not numpy (1.20.1)
   1: fact: numpy (1.20.0) requires Python >=3.7
   1: derived: not numpy (1.20.0)
   1: selecting numpy (1.19.5)
   1: Version solving took 0.026 seconds.
   1: Tried 1 solutions.

Finding the necessary packages for the current system

Package operations: 0 installs, 0 updates, 0 removals, 1 skipped

  • Installing numpy (1.19.5): Skipped for the following reason: Already installed
```

**Comment by nishkarshv** [comment]
> I think: ^3.9 allows 3.10, which is incompatible with scipy. It's nothing to do with your currently installed version of python, only to do with what's specified in pyproject.toml. Try ~3.9 as the python version.

I tried this but still getting error

**Comment by adamryczkowski** [comment]
What is the walk-around for this problem?

It is disappointing that I can't have
```
[tool.poetry.dependencies]
python = "^3.10"
scipy = "^1.8"
```
in my dependencies, and I am forced to constrain the python version like this instead:
```
[tool.poetry.dependencies]
python = ">=3.10,<3.11"
scipy = "^1.8"
```

**Comment by newTypeGeek** [comment]
> What is the walk-around for this problem?
> 
> It is disappointing that I can't have
> 
> ```
> [tool.poetry.dependencies]
> python = "^3.10"
> scipy = "^1.8"
> ```
> 
> in my dependencies, and I am forced to constrain the python version like this instead:
> 
> ```
> [tool.poetry.dependencies]
> python = ">=3.10,<3.11"
> scipy = "^1.8"
> ```

This method works for me. And it is still required for poetry `1.6.1`
