### ISSUE TITLE
Poetry stuck at `pyenv` Python version active during `install-poetry`, broken after version uninstall

### ISSUE THREAD

**Issue by sandpipersburg** [python-poetry/poetry#4317]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).
    - **no exception occurs, only Shell error**

- **OS version and name**: 
    - macOS Big Sur 11.2.3
- **Poetry version**:
    - 1.1.7 via `install-poetry.py`
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**:
    - provided inside **[Issue]** section

## Issue

Below scenarios demonstrate that:
1. Poetry 1.1.7 which was installed via `install-poetry.py`, does not recognize the changes in Python version made via `pyenv local <version>`. The expected behavior is to recognize Python version activated via pyenv. Similar issue: [Poetry does not use active pyenv when creating virtual environment #651](https://github.com/python-poetry/poetry/issues/651)
2. Poetry becomes broken after pyenv Python version, which have been active at a time of Poetry installation via `install-poetry.py`, was uninstalled via pyenv. 

Out-of-the-head suggestion is that`/Users/username/Library/Application Support/pypoetry/venv/bin/python` should link to pyenv Python shims, not to a specific pyenv Python version, as it happens currently. 

**The environment:**
- pyenv 2.0.3 via Homebrew
- Python 3.8.8 installed via pyenv, activated in a Poetry project dir via `.python-version` file. No other versions of Python installed via pyenv
- Poetry 1.1.7 installed via curl + `install-poetry.py` from the Poetry project dir, i.e. an active version of Python at a time of installation was 3.8.8
- Poetry appended to PATH via `.zshrc`: `export PATH="$PATH:$HOME/.local/bin"`, `echo $PATH` output:
`/Users/username/.pyenv/shims:/usr/local/bin:<skipped>:/Users/username/.local/bin`
- `pyproject.toml` specifies Python version requirement via `[tool.poetry.dependencies]`: `python = "^3.8.8"`
- `poetry.lock` specifies Python version requirement: `python-versions = "^3.8.8"`
- `poetry.toml`: `in-project = true`
- at the beginning, no `.venv` present in a Poetry project dir

Commands in below scenarios executed from Poetry project dir `/Users/username/workspace/project/`.

**Scenario 1 (positive). Poetry Python version is the same as pyenv Python version:**
- `pyenv versions`. The result (`w` and `p` are softlinks to `workspace` and `project` dirs):
```zsh
  system
  3.8.8 (set by /Users/username/w/p/.python-version)
```
- `python --version`. The result:
`Python 3.8.8`
- `poetry run python --version`. The result:
```zsh
Creating virtualenv project in /Users/username/workspace/project/.venv
Python 3.8.8
```

**Scenario 2 (negative). Switchinig Python version via pyenv:**
- follow **[Scenario 1]**
- delete `.venv` from Poetry project dir
- install Python 3.7.11 via pyenv, activate it: `pyenv install 3.7.11`, `pyenv local 3.7.11`
- `pyenv versions`. The result:
```zsh
  system
* 3.7.11 (set by /Users/username/w/p/.python-version)
  3.8.8
```
- `python --version`. The result:
`Python 3.7.11`
- `poetry run python --version`. The result:
```zsh
Creating virtualenv project in /Users/username/workspace/project/.venv
Python 3.8.8
```

**Expected result:**
poetry prints Python version `Python 3.7.11`, or maybe a Python version compatibility error (because the Poetry project requires a version 3.8.8 or later). 

**Scenario 3 (negative). Uninstalling of non-active pyenv Python version, `.venv` is still present:**
- follow **[Scenario 2]**
- `pyenv uninstall 3.8.8`, after that: `poetry run python --version`. The result:
```zsh
/Users/username/.local/bin/poetry: line 2: /Users/username/Library/Application Support/pypoetry/venv/bin/python: No such file or directory
/Users/username/.local/bin/poetry: line 2: exec: /Users/username/Library/Application Support/pypoetry/venv/bin/python: cannot execute: No such file or directory
```

**Expected result:**
Poetry is not broken, and either prints the actual Python version, or a reasonable and meaningful error. 

**Scenario 4 (negative). Uninstalling of non-active pyenv Python version, `.venv` is absent:**
- follow **[Scenario 3]**
- delete `.venv` from Poetry project dir
- `poetry run python --version`. The result: 
the same result as for **[Scenario 3]**.

**Expected result:**
The same expected result as for **[Scenario 3]**.

**Comment by hashzmr** [comment]
> Scenario 2 (negative). Switchinig Python version via pyenv:

I tried to execute `` poetry env use `which python` ``  before `poetry run python --version. The result:`.

After that I tried to execute `poetry run python --version`, `poetry` raises `NoCompatiblePythonVersionFound`.
(The execution result is shown below)

I think this is the expected behavior presented by @sandpipersburg , but how about it?

```sh
▲  test/  poetry env use `which python`

  NoCompatiblePythonVersionFound

  The specified Python version (3.7.10) is not supported by the project (^3.8.8).
  Please choose a compatible version or loosen the python constraint specified in the pyproject.toml file.

  at ~/Library/Application Support/pypoetry/venv/lib/python3.8/site-packages/poetry/utils/env.py:676 in create_venv
       672│             # If an executable has been specified, we stop there
       673│             # and notify the user of the incompatibility.
       674│             # Otherwise, we try to find a compatible Python version.
       675│             if executable:
    →  676│                 raise NoCompatiblePythonVersionFound(
       677│                     self._poetry.package.python_versions, python_patch
       678│                 )
       679│
       680│             io.write_line(
```

**Comment by mbahri** [comment]
I think this change although understandable is a bit unfortunate, as the pyenv + poetry workflow is quite popular and powerful.

It would be good to at least explain this limitation in the documentation, though. I spent hours today trying to figure out why the workflow was broken, before I noticed it was working fine with the old get-poetry.py

**Comment by ferreteleco** [comment]
Any update / solution on this? I would love to keep mantaining my 'pyenv workflow' using poetry as smooth as possible.

Thanks in advance!

**Comment by finswimmer** [comment]
> Any update / solution on this?

The next preview release will contain an experimental option to detect the current activated python, regardless on how poetry was installed. See https://github.com/python-poetry/poetry/pull/4852

Poetry's own environment shouldn't break anymore, when the Python version used during installation get's removed. Symlinks are not used anymore:

 https://github.com/python-poetry/install.python-poetry.org/blob/767db614c92afb79fde1b85cd0614bf3f75e8389/install-poetry.py#L299 

https://github.com/python-poetry/install.python-poetry.org/blob/767db614c92afb79fde1b85cd0614bf3f75e8389/install-poetry.py#L316

**Comment by princelySid** [comment]
Just in case someone end up here after hours debugging do the usual flow then `poetry env use <python version>`. Should work after that
