### ISSUE TITLE
Document workaround for "urllib.error.URLError" when installing via install script on macOS

### ISSUE THREAD

**Issue by jSadoski** [python-poetry/poetry#4338]
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

When trying to install via the install script, `curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python3 -`, I encountered this error (macOS 11.5.1, python 3.8.6):

```bash
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)>
```

Which seems to be similar to a couple of issues reported here. [The fix for me was simple](https://stackoverflow.com/a/57968930/705296):

```bash
open /Applications/Python\ 3.8/Install\ Certificates.command
```

While a more permanent resolution to this would be preferred, it would be nice if the documentation could reflect this. I'm willing to make the PR myself, but I'm not entirely sure what systems and python versions are affected by this.

**Comment by Secrus** [comment]
From what I have found, this is a MacOS-specific issue. I don't think this is gonna be added to docs. If we were to include every possible error on every available OS, it would be impossible to maintain it.

**Comment by jSadoski** [comment]
Thank you! Hopefully this issue post will serve as a reference.

**Comment by hhourston** [comment]
> From what I have found, this is a MacOS-specific issue. I don't think this is gonna be added to docs. If we were to include every possible error on every available OS, it would be impossible to maintain it.

Hi @Secrus, I just wanted to mention that I've also encountered this issue using a Linux machine. The Linux version information is:

Linux version 4.15.0-180-generic (buildd@lcy02-amd64-097) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #189-Ubuntu SMP Wed May 18 14:13:57 UTC 2022

**Comment by RayJason** [comment]
Thx! I'm having this problem after update python 3.10.
