### ISSUE TITLE
Poetry silently fails authentication to publish --repository reponame

### ISSUE THREAD

**Issue by staticdev** [python-poetry/poetry#4344]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Debian 11
- **Poetry version**: 1.1.7
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**:

```
[tool.poetry]
name = "mymodule"
version = "0.1.0"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[tool.coverage.paths]
source = ["src", "*/site-packages"]

[tool.coverage.run]
branch = true
source = ["mymodule"]

[[tool.poetry.source]]
name = "artifactory"
url = "https://artifactory.swisscom.com/api/pypi/myrepo"
default = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

```

## Issue

This is somewhat related to https://github.com/python-poetry/poetry/issues/4190, but I build a python lib and I do a `poetry publish --repository artifactory -vvv` with wrong credentials. It shows are success and 100% upload. Also option `-vvv` does not increase verbosity to try do discover what is wrong.

Output:

```
poetry publish --repository artifactory -vvv

No suitable keyring backend found
No suitable keyring backends were found
Using a plaintext file to store and retrieve credentials
Username: inexistingusername
Password:
Publishing mymodule (0.1.0) to artifactory
 - Uploading mymodule-0.1.0.tar.gz 100%
 - Uploading mymodule-0.1.0-py2.py3-none-any.whl 100%
```

**Comment by dimbleby** [comment]
duplicate #920, per recent update there this works as expected today
