### ISSUE TITLE
after downgrade importlib.metadata.version(__name__) reports wrong version

### ISSUE THREAD

**Issue by RafalSkolasinski** [python-poetry/poetry#4350]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Linux, PopOS, 21.04
- **Poetry version**: Poetry version 1.1.7
- **Link of a [Gist](https://gist.github.com/RafalSkolasinski/947c5d684087762aafe5daac59324dfd) with the contents of your pyproject.toml file**: 

## Issue

Using following code in `ml_env/__ini__.py` to get version of installed package:
```python
try:
    import importlib.metadata as importlib_metadata
except ModuleNotFoundError:
    import importlib_metadata


try:
    # This will read version from pyproject.toml
    __version__ = importlib_metadata.version(__name__)
except Exception:
    __version__ = "unknown"
```

After bumping `version = "0.3.0"` in pyproject.toml to `0.4` and later downgrading back 
```
poetry run python3 -c 'import ml_env; print(ml_env.__version__)'
```
gives the wrong output even after issuing `poetry install`  again
```
╭─rskolasinski at petrucci [~/p/n/data-science] (master ✚4…1) (18:32:59)                                                                     
╰λ poetry install
Installing dependencies from lock file

No dependencies to install or update

Installing the current project: ml-env (0.3.0)
╭─rskolasinski at petrucci [~/p/n/data-science] (master ✚4…1) (18:33:04)                                                                     
╰λ poetry run python3 -c 'import ml_env; print(ml_env.__version__)'
0.4.0
```

I believe that this is due to alter versions being left in `site-packages`:
```
╭─rskolasinski at petrucci [~/p/n/data-science] (master ✚4…1) (18:33:08)                                                                     
╰λ ls /home/rskolasinski/.cache/pypoetry/virtualenvs/ml-env-XXP60kA0-py3.8/lib/python3.8/site-packages/ | grep ml_env
ml_env-0.2.0.dev0.dist-info
ml_env-0.2.0.dev1.dist-info
ml_env-0.3.0.dist-info
ml_env-0.4.0.dist-info
ml_env.pth
```

**Comment by RafalSkolasinski** [comment]
It seems that either I need to `poetry env remove python` and `poetry install` again or issue repeatedly 
```
poetry run pip uninstall ml-env
```
until all version of local package are removed.

**Comment by finswimmer** [comment]
Hello @RafalSkolasinski,

this should be fixed in the latest preview release: https://github.com/python-poetry/poetry/pull/3900

fin swimmer
