### ISSUE TITLE
poetry install doesn't work with quiet flag

### ISSUE THREAD

**Issue by zyzzyxdonta** [python-poetry/poetry#4352]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Debian Buster (Docker image python:3.9)
- **Poetry version**: 1.1.7
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/zyzzyxdonta/674572a80e88002933f6af5093a31ee8

## Issue

I noticed that `poetry install` does not work correctly when adding the quiet flag, i.e. `poetry -q install`. In this case, no venv is created and nothing is installed. Here is an example from a CI job in which you can see that the venv is only created in the `poetry run` step rather than during `poetry -q install`:

```
$ pip install -qqq poetry
$ cd my_tool
$ poetry --version
Poetry version 1.1.7
$ poetry -q install
$ poetry run black --check .
Creating virtualenv my-tool-nDf_KNJO-py3.9 in /root/.cache/pypoetry/virtualenvs
  FileNotFoundError
  [Errno 2] No such file or directory: b'/bin/black'
  at /usr/local/lib/python3.9/os.py:607 in _execvpe
       603│         path_list = map(fsencode, path_list)
       604│     for dir in path_list:
       605│         fullname = path.join(dir, file)
       606│         try:
    →  607│             exec_func(fullname, *argrest)
       608│         except (FileNotFoundError, NotADirectoryError) as e:
       609│             last_exc = e
       610│         except OSError as e:
       611│             last_exc = e
```

**Comment by branchvincent** [comment]
Thanks for the report! This has been fixed on `master` and will be released with the upcoming `1.2`:

```console
$ poetry --version
Poetry (version 1.2.0a2)
$ poetry -q install
$ poetry run pip list
Package            Version
------------------ -------
black              21.12b0
click              8.0.4
flake8             3.9.2
fuzzywuzzy         0.18.0
mccabe             0.6.1
mypy               0.910
mypy-extensions    0.4.3
pathspec           0.9.0
Pillow             8.4.0
pip                21.3.1
platformdirs       2.5.1
pycodestyle        2.7.0
pyflakes           2.3.1
python-Levenshtein 0.12.2
setuptools         60.9.3
toml               0.10.2
tomli              1.2.3
typing_extensions  4.1.1
wheel              0.37.1
```
