### ISSUE TITLE
Cannot install 1.2.0a2

### ISSUE THREAD

**Issue by ngtrunghuan** [python-poetry/poetry#4356]
It seems that the build for Linux hasn't been published. I did manage to `pip install <wheel_url>` directly, but it would be great if the appropriate channel releases are published too.

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Linux version 5.4.72-microsoft-standard-WSL2 (Ubuntu 20.x distro)
- **Poetry version**: 1.7.0

## Issue
```
# _ @ _ in ~ [11:29:08] C:1
$ poetry self update
You are using the latest version

# _ @ _ in ~ [11:29:11] 
$ poetry self update --preview
Updating to 1.2.0a2

  RuntimeError

  Could not find poetry-1.2.0a2-linux.sha256sum file

  at .poetry/lib/poetry/console/commands/self/update.py:260 in _update
      256│         try:
      257│             r = urlopen(base_url + "/{}/{}".format(version, checksum))
      258│         except HTTPError as e:
      259│             if e.code == 404:
    → 260│                 raise RuntimeError("Could not find {} file".format(checksum))
      261│ 
      262│             raise
      263│ 
      264│         checksum = r.read().decode().strip()
```

**Comment by ngtrunghuan** [comment]
Update to those who'd like to install to make use of the keyring functionality recently released: `pip install https://github.com/python-poetry/poetry/releases/download/1.2.0a2/poetry-1.2.0a2-py3-none-any.whl` should work, as long as you fix your path etc.

**Comment by vlcinsky** [comment]
Using `pipx install poetry==1.2.0a2` worked for me too.

**Comment by akurtz** [comment]
I was able to use `curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | POETRY_PREVIEW=1 python -` to successfully install 1.2.0a2 on macOS.  More details here: https://python-poetry.org/docs/master/#installation

**Comment by RileyMShea** [comment]
While both solutions, https://github.com/python-poetry/poetry/issues/4356#issuecomment-898752603 using pipx and https://github.com/python-poetry/poetry/issues/4356#issuecomment-899016055 usage of a fresh install from the new installer script have worked for the install, only the `pipx` install method has allowed me to use poetry with python 3.10 virtualenv's.

The curl shell script installation method causes errors when trying to install packages in an active python3.10 virtualenv .venv/

**Comment by neersighted** [comment]
This is by design -- the old installer/self update was not supported for 1.2.0a1 or newer. This is now well documented (we're in a post-1.2 release world), and long stale.
