### ISSUE TITLE
Integrate poetry.toml into pyproject.toml when using virtualenvs.in-project config

### ISSUE THREAD

**Issue by miro-mlynarik** [python-poetry/poetry#4359]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request
Hi, 

as you all probably know, when the virtual environment is set up using the config
```
poetry config --local virtualenvs.in-project true
```
the poetry will add a new config file `poetry.toml` into the root of the project folder. This file has only two rows and nothing else in it. As one of the benefits of using poetry is getting rid of many configuration files in the project root, would it be possible to divert this venv configuration into `pyproject.toml` file instead? The whole poetry configuration would then only depend on two files (`pyproject.toml` and `poetry.lock`) which would be really nice and convenient.

Thanks.

**Comment by xrogaan** [comment]
The issue with using pyproject.toml is that you will force every contributors to use the local venv model, while the settings can remain local with a poetry.toml.

**Comment by finswimmer** [comment]
Hello @miro-mlynarik,

it's exactly how @xrogaan explained. So we don't plan to combine these file.

fin swimmer
