### ISSUE TITLE
doc on website is behind readme

### ISSUE THREAD

**Issue by deogracia** [python-poetry/poetry#4363]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue
Hi,

When following https://python-poetry.org/docs/#installation, I ran into the following warning (with either python2 or python3)

```
$ curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
Retrieving Poetry metadata

This installer is deprecated. Poetry versions installed using this script will not be able to use 'self update' command to upgrade to 1.2.0a1 or later.
# Welcome to Poetry!
```

Here's what the website says on how to install poetry un Unix

```
curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
```

Here's what the README.md says:

```
curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python -
```

I've got no warning when using `install-poetry.py`

It seems that the website isn't up to date on this topic.

**Comment by finswimmer** [comment]
Hello @deogracia,

the docs for the current stable release [contains the information](https://python-poetry.org/docs/#installation), that the `get-poetry.py` script is deprecated and will be replaced by the `install-poetry.py` script from 1.2 onwards. It also contains the [link](https://python-poetry.org/docs/master/#installation) to the description of this installation script.

fin swimmer

BTW: "Deprecated" doesn't mean "don't use it". It just means "we are planing to change this in a future version".
