### ISSUE TITLE
Poetry Installation Issue

### ISSUE THREAD

**Issue by ehassan66** [python-poetry/poetry#4368]
When I want to install poetry from below mentioned command as recommended by (https://python-poetry.org/docs/#installation)

(Invoke-WebRequest -Uri https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py -UseBasicParsing).Content | python -

But its hows this message 
**.Content was unexpected at this time.**

**Comment by brandonaut** [comment]
Are you running the command from within a Powershell terminal? The error message looks like something that a cmd prompt would throw.

**Comment by dimbleby** [comment]
The above sounds right.

In the event that there is a problem with get-poetry.py: it's not deprecated anyway and I don't expect anyone will be making fixes to it, so either way this issue can be closed.

**Comment by EmmaWebGH** [comment]
Opening again
Cannot run from powershell as using a conda venv
So need to be in Anaconda Prompt, and so the error still occurs.

Also tried via pipx:
`pipx install poetry`
Which seems to work for a lot of people, but not me. After adding to system path, it still can't find poetry.
`set "PATH=%USERPROFILE%\.local\pipx\venvs\poetry\Scripts;%PATH%"`
But poetry not found.

Don't understand, why does it only work in powershell, meaning we can't use Poetry with Conda??
