### ISSUE TITLE
"poetry add <package>" fails on Window 10

### ISSUE THREAD

**Issue by Marmeladenbrot** [python-poetry/poetry#4370]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows 10 Professional 64bit 21H1
- **Poetry version**: 1.1.7
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**:

[tool.poetry]
name = ".work"
version = "0.1.0"
description = ""
authors = [""]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

## Issue

- Installing poetry via Powershell with "(Invoke-WebRequest -Uri https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py -UseBasicParsing).Content | python -"
- >cd C:\Users\Marmeladenbrot\
- >poetry new .work
- >cd .work
- >poetry add pandas

fails with this error:

```
Command C:\Users\Marmeladenbrot\AppData\Local\pypoetry\Cache\virtualenvs\.work-mVmjjJbe-py3.9\Scripts\python.exe - errored with the following return code 1, and output:
  Das System kann den angegebenen Pfad nicht finden.
  c:\users\Marmeladenbrot\appdata\local\programs\python\python39
  input was : import sys

  if hasattr(sys, "real_prefix"):
      print(sys.real_prefix)
  elif hasattr(sys, "base_prefix"):
      print(sys.base_prefix)
  else:
      print(sys.prefix)


  at c:\users\Marmeladenbrot\appdata\local\programs\python\python39\lib\site-packages\poetry\utils\env.py:1101 in _run
      1097│                 output = subprocess.check_output(
      1098│                     cmd, stderr=subprocess.STDOUT, **kwargs
      1099│                 )
      1100│         except CalledProcessError as e:
    → 1101│             raise EnvCommandError(e, input=input_)
      1102│
      1103│         return decode(output)
      1104│
      1105│     def execute(self, bin, *args, **kwargs):
```

but Python 3.9.6 is installed

> PS C:\Users\Marmeladenbrot\.work> where.exe python
> C:\Users\Marmeladenbrot\AppData\Local\Programs\Python\Python39\python.exe

Already tried reinstalling poetry and restarting the PC.

**Comment by tonybaloney** [comment]
I had the same issue. Noticed that the `cache-dir` setting was set to the wrong place during installation.

Fixed this by changing it to the local cache for Python, which is something like `C:\Users\myuser\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_xxxxx\LocalCache\Local\pypoetry\Cache`

**Comment by mrmijus** [comment]
Removing the **artifacts** folder from C:\Users\{USERNAME}\AppData\Local\pypoetry\Cache solved my problem temporarily.

**Comment by finswimmer** [comment]
Hello @Marmeladenbrot ,

you haven't come back to this issue for a long while. So I assume this is solved in the meantime and I can close this ticket.

Feel free to leave a comment if you disagree.

fin swimmer
