### ISSUE TITLE
`ERROR: File "setup.py" not found for legacy project`

### ISSUE THREAD

**Issue by paw-lu** [python-poetry/poetry#4372]
Trying to install [`libsixel-python`](https://pypi.org/project/libsixel-python/) via Poetry results in a

```sh
% ❯ poetry add libsixel-python
Using version ^0.5.0 for libsixel-python

Updating dependencies
Resolving dependencies... (0.6s)

Package operations: 1 install, 0 updates, 0 removals

  • Installing libsixel-python (0.5.0): Failed

  EnvCommandError

  Command ['/Users/pawlu/Library/Caches/pypoetry/virtualenvs/nbpreview-fES2tmKb-py3.9/bin/pip', 'install', '--no-deps', 'file:///Users/pawlu/Library/Caches/pypoetry/artifacts/17/97/77/36c11dc77874fbb3ae7fb5d439eafb9b008ed60870b9fcd39ca0172297/libsixel-python-0.5.0.macosx-10.13-x86_64.tar.gz'] errored with the following return code 1, and output: 
  Processing /Users/pawlu/Library/Caches/pypoetry/artifacts/17/97/77/36c11dc77874fbb3ae7fb5d439eafb9b008ed60870b9fcd39ca0172297/libsixel-python-0.5.0.macosx-10.13-x86_64.tar.gz
  ERROR: File "setup.py" not found for legacy project file:///Users/pawlu/Library/Caches/pypoetry/artifacts/17/97/77/36c11dc77874fbb3ae7fb5d439eafb9b008ed60870b9fcd39ca0172297/libsixel-python-0.5.0.macosx-10.13-x86_64.tar.gz.
```

However, `pip` succeeds.

```sh
% python -m pip intstall libsixel-python
```

Both are using the same version of pip (21.1.3).

What's going on here? What does Poetry do differently that results in a failure?
How is this fixed?

_Originally posted by @paw-lu in https://github.com/python-poetry/poetry/discussions/4263_

**Comment by jules-ch** [comment]
There is no `setup.py` in the distribution of this library for the macosx archive, it is flagged as a dumb binary.

https://pypi.org/project/libsixel-python

https://files.pythonhosted.org/packages/5a/77/2cef6c04b8cbd6d22f6e059f8fa6e94ba3065bad5f1a1a12e451fb9dcfde/libsixel-python-0.5.0.macosx-10.13-x86_64.tar.gz

I don't think poetry handles those kind of distribution as it installs the package at a specific location.

In your example, `/usr/local/lib/python2.7/site-packages/libsixel/`

I'm not familiar with those distributions.

**Comment by DandyDev** [comment]
I feel this is some sort of regression. I have the same problem with the [sqlalchemy-repr](https://pypi.org/project/sqlalchemy-repr/) package and Poetry used to install it just fine a couple of months ago.

**Comment by finswimmer** [comment]
Due to https://github.com/python-poetry/poetry/pull/5767 `
libsixel-python-0.5.0.macosx-10.13-x86_64.tar.gz ` should not be selected anymore.
