### ISSUE TITLE
`poetry build` from source distribution creates empty wheel (dist-info only, no python code)

### ISSUE THREAD

**Issue by flying-sheep** [python-poetry/poetry#4374]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Arch Linux (up-to-date)
- **Poetry version**: 1.1.7
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://github.com/niksite/url-normalize/blob/25439f9fd25aa599a90234a150c86bfbe8718554/pyproject.toml

## Issue

A wheel build from a source distribution doesn’t include code:

```console
$ wget https://github.com/niksite/url-normalize/archive/1.4.3.tar.gz
$ tar xf 1.4.3.tar.gz
$ cd url-normalize-1.4.3
$ poetry build --format wheel
$ unzip -l dist/url_normalize-1.4.3-py2.py3-none-any.whl
Archive:  dist/url_normalize-1.4.3-py2.py3-none-any.whl
  Length      Date    Time    Name
---------  ---------- -----   ----
     1070  1980-01-01 00:00   url_normalize-1.4.3.dist-info/LICENSE
       87  2016-01-01 00:00   url_normalize-1.4.3.dist-info/WHEEL
     3142  2016-01-01 00:00   url_normalize-1.4.3.dist-info/METADATA
      318  2016-01-01 00:00   url_normalize-1.4.3.dist-info/RECORD
---------                     -------
     4617                     4 files
```

**Comment by dimbleby** [comment]
seems fixed on more recent code
