### ISSUE TITLE
Upgrading the version of python

### ISSUE THREAD

**Issue by algebravic** [python-poetry/poetry#4376]
I created a poetry package with a particular version of python in the virtual environment.  How do I upgrade it to a newer version of python?   Do I have to blow away the virtual environment and start over?  Or is there some less radical way of doing this?

**Comment by omadson** [comment]
Hi @algebravic. You could try using [pyenv](https://github.com/pyenv/pyenv). It allows you to install different versions of Python on your computer without compromising your system's Python version. Also, you can configure a local Python version for each project.

**Comment by finswimmer** [comment]
Hello @algebravic,

updating the python version of a venv always requires to throw away the current venv and rebuild a new one from scratch.

If you haven't set poetry's config `virtualenvs.in-project` to `true` poetry supports having multiple venv per project based on the interpreter. You can switch between them with `poetry env use /path/to/python`. See the [docs](https://python-poetry.org/docs/master/managing-environments/#switching-between-environments) for more information.

fin swimmer
