### ISSUE TITLE
can't set system site package with `poetry config`

### ISSUE THREAD

**Issue by redthing1** [python-poetry/poetry#4377]
- [ ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [ ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Arch Linux, Latest
- **Poetry version**: `1.1.7`
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://github.com/xdrie/aitextgen_host/blob/master/src/pyproject.toml

## Issue

I am trying to enable system site packages, using poetry config:

```
❯ poetry config --local virtualenvs.options.system-site-packages true

  ValueError

  Setting virtualenvs.options.system-site-packages does not exist

  at /usr/lib/python3.9/site-packages/poetry/console/commands/config.py:248 in handle
      244│                 raise ValueError("You must pass exactly 1 value")
      245│ 
      246│             return 0
      247│ 
    → 248│         raise ValueError("Setting {} does not exist".format(self.argument("key")))
      249│ 
      250│     def _handle_single_value(self, source, key, callbacks, values):
      251│         validator, normalizer, _ = callbacks
      252│ 
```

I am getting an error that it doesn't exist?

**Comment by ben-xD** [comment]
It's still not available (even in yesterday's release). However, the feature is documented in the `master` documentation: https://python-poetry.org/docs/master/configuration#virtualenvsoptionssystem-site-packages

**Comment by dflock** [comment]
This happens to me when running poetry from master:

I install poetry like this:

```console
$ python -m pip install pipx && \
    python -m pipx ensurepath && \
    pipx install git+https://github.com/python-poetry/poetry.git
$ PATH="/root/.local/bin:$PATH"
$ poetry --version
Poetry (version 1.2.0a2)
```
but when I use it, I get this error:

```console
$ poetry config --list
cache-dir = "/root/.cache/pypoetry"
experimental.new-installer = true
installer.max-workers = null
installer.parallel = true
virtualenvs.create = true
virtualenvs.in-project = null
virtualenvs.options.always-copy = false
virtualenvs.options.system-site-packages = false
virtualenvs.path = "{cache-dir}/virtualenvs"  # /root/.cache/pypoetry/virtualenvs
virtualenvs.prefer-active-python = false

$ poetry config virtualenvs.system-site-packages true --local
  ValueError
  Setting virtualenvs.system-site-packages does not exist
  at ~/.local/pipx/venvs/poetry/lib/python3.9/site-packages/poetry/console/commands/config.py:277 in handle
      273│                 raise ValueError("You must pass exactly 1 value")
      274│ 
      275│             return 0
      276│ 
    → 277│         raise ValueError(f"Setting {self.argument('key')} does not exist")
      278│ 
      279│     def _handle_single_value(
      280│         self,
      281│         source: ConfigSource,
```

**Comment by finswimmer** [comment]
Hello,

this option is only available in the current preview release and not in the stable.

@dflock: You typed `virtualenvs.system-site-packages` as an argument for `poetry config`. But it must be `virtualenvs.options.system-site-packages`.

fin swimmer

**Comment by redthing1** [comment]
😁👍😎
