### ISSUE TITLE
`poetry publish --cleanup` for cleaning up outdated wheel files in pypi

### ISSUE THREAD

**Issue by jaeyoo** [python-poetry/poetry#4382]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

If we can't upload wheel files at `pypi.org` anymore due to disk size limit, I hope to clean up the outdated `whl` files with `poetry` seemlessly.

**Comment by jaeyoo** [comment]
as arguments, for example,

```
poetry publish # error due to pypi disk size limit!
poetry publish --cleanup '<=0.5.0dev20210101'  # shows all matched wheel files older than 0.5.0dev20210101 version (dry-run)
poetry publish --cleanup '<=0.5.0dev20210101' --do-it  # removes all wheel files older than 0.5.0dev20210101 version
```

**Comment by Secrus** [comment]
Managing files on PyPI is definitely out of the scope of Poetry. To add to that, Warehouse (the software behind PyPI) doesn't offer any API to do it, so it would be a pain to implement.
