### ISSUE TITLE
Poetry can't resolve some dependencies for packages

### ISSUE THREAD

**Issue by Jawdeath** [python-poetry/poetry#4397]
## Issue
Poetry v. 1.2.0a2, Mac os 11.5.2

### Steps to reproduce issue:

**- Create test directory with pyproject.toml file:**

[tool.poetry]
name = "test"
version = "0.1.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "^3.8"
black = "^21.7b0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]

**- Run commands**

sudo pip3 uninstall poetry
sudo pip3 install poetry==1.2.0a2
poetry --version
poetry install
poetry run black #error

**- Get the dependency error** 
 
![image](https://user-images.githubusercontent.com/22244600/129864347-e8528ef1-cfcd-426b-9b91-821270c89f4d.png)

If you will add missing package to the config manually, Poetry will install it, but you will still see this error.

**Comment by AndrejSayadov** [comment]
Indicates that the package is installed
<img width="888" alt="image" src="https://user-images.githubusercontent.com/89129698/129865685-d6d834b6-8468-484d-a132-5a59b1885a5a.png">

**Comment by finswimmer** [comment]
Hello ,

you haven't come back to this issue for a long while. So I assume this is solved in the meantime and I can close this ticket.

Feel free to leave a comment if you disagree.

fin swimmer
