### ISSUE TITLE
Requests retries for http requests for finding candidates and/or Package installation retry

### ISSUE THREAD

**Issue by rootcss** [python-poetry/poetry#4404]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

Hi,
For larger projects, sometimes requests to fetch candidates from PyPi fails (transient network errors). Can we support retries at two places:
1. HTTP requests that pulls package metadata
2. During package installation it might fail due to a transient network error which causes the entire build to fail, can we add a retry for package installations

Thank you ❤️

**Comment by rootcss** [comment]
@finswimmer can you please help with this issue?

**Comment by luisacabs-out** [comment]
Any updates on this issue? @sdispater @abn

**Comment by dimbleby** [comment]
retries were implemented in 1.2, this can be closed

**Comment by neersighted** [comment]
Indeed, this can be closed. Please refrain from randomly pinging active contributors -- that will usually have the opposite of the desired effect.

Looks to duplicate #2736 as well.
