### ISSUE TITLE
Poetry 1.1.8 does not include the security fix for mismatching package hashes

### ISSUE THREAD

**Issue by pietrodn** [python-poetry/poetry#4409]
Hello, it appears to me that the latest Poetry release (1.1.8) does not contain [this important security fix](https://github.com/python-poetry/poetry/pull/3885) that makes Poetry actually check the hashes of downloaded files against the hashes in `poetry.lock`.

I tried to alter the hashes in my `poetry.lock` and reinstall one package on Poetry 1.1.8, and it did not complain.
Also, it's evident that [this commit](https://github.com/python-poetry/poetry/pull/3885/commits/b5b68a2bb1dba94e5696b6052e4baa7ceaa6a828) is not present in the [`chooser.py` file in the `release-1.1.8` branch](https://github.com/python-poetry/poetry/blob/release-1.1.8/poetry/installation/chooser.py), but it is present in the [`master` version of the file](https://github.com/python-poetry/poetry/blob/master/poetry/installation/chooser.py).

It looks like some weird Git merging issue.
Can we make sure this security fix gets included ASAP in the next release? Thank you 🙏🏼

**Comment by mkniewallner** [comment]
The pull request containing the fix was made against `master` branch, which represents the development of version 1.2. Thus it's expected that version 1.1.8 doesn't contain the fix.

If the fix were to also be included in 1.1.x versions, it would need to be backported by doing a pull request against `1.1` branch (for instance https://github.com/python-poetry/poetry/pull/4331).

**Comment by pietrodn** [comment]
I did as you suggested, creating [this PR](https://github.com/python-poetry/poetry/pull/4420) to backport the fix.

Unfortunately this PR isn't sufficient to correct the bug, as [this other PR](https://github.com/python-poetry/poetry-core/pull/159) needs to be backported to `poetry-core` 1.0.

I tried to do so, but with the given change `poetry install` crashes and I can't seem to find the cause.

**Comment by pietrodn** [comment]
More precisely, if I backport the poetry-core PR, Poetry fails with the following:

```
$ ~/git/poetry/.venv/bin/poetry install
Creating virtualenv tmp in /Users/pietro/tmp/.venv
Installing dependencies from lock file

Package operations: 1 install, 0 updates, 0 removals

  • Installing attrs (21.2.0): Failed

  AttributeError

  'Link' object has no attribute 'is_absolute'

  at ~/git/poetry/.venv/lib/python3.9/site-packages/poetry/core/packages/file_dependency.py:34 in __init__
       30│         self._base = base or Path.cwd()
       31│         self._full_path = path
       32│
       33│         #raise ValueError(type(path))
    →  34│         if not self._path.is_absolute():
       35│             try:
       36│                 self._full_path = self._base.joinpath(self._path).resolve()
       37│             except FileNotFoundError:
       38│                 raise ValueError("Directory {} does not exist".format(self._path))
```

I think that there is an underlying bug where an object that should be a `Path` is actually a `Link`, and that is exposed by the fact that the `Package.files` attribute gets cloned, and not lost as of now in Poetry 1.1.8.

**Comment by pietrodn** [comment]
It is fixed in 1.1.9, I just checked that `poetry install` correctly detects a corrupt hash. Thanks!

**Comment by dougn** [comment]
Granted, now I get this error:
  • Installing auth-client (1.6.0): Failed

  AttributeError

  'Link' object has no attribute 'name'

  at ~/.pyenv/versions/3.7.9/lib/python3.7/site-packages/poetry/installation/executor.py:620 in _download_link
      616│                 ).hash()
      617│             )
      618│             if archive_hash not in {f["hash"] for f in package.files}:
      619│                 raise RuntimeError(
    → 620│                     "Invalid hash for {} using archive {}".format(package, archive.name)
  • Installing auth-client (1.6.0): Failed

  AttributeError

  'Link' object has no attribute 'name'


WHY exactly auth-client, and another internal to my company package are failing the hash check is a different and scary question.

**Comment by j-a-n** [comment]
> The hash being calculated here is sha256, but the one in the lock file is md5?

I had the same problem with our internal pypiserver.
After adding ` --hash-algo=sha256` to the pypiserver cmdline and clearing poetry cache it works again.

**Comment by dougn** [comment]
Not an option for our artifactory server :-(
