### ISSUE TITLE
Installing packages from SVN fails

### ISSUE THREAD

**Issue by mcdevitts** [python-poetry/poetry#4419]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows 10
- **Poetry version**: 1.1.8

## Issue
I have a number of legacy projects that are still in SVN. I have not found any examples of how to install a project from SVN, so I can only assume this is unsupported at the moment.

I've tried:
`
poetry add svn+https://{url}/{project_name}/trunk
poetry add svn+https://{url}/{project_name}/trunk#egg={project_name}
poetry add https://{url}/{project_name}/trunk
`

The install attempt fails with:
`
  TooManyRedirects

  Exceeded 30 redirects.

  at ~\.local\pipx\venvs\poetry\lib\site-packages\requests\sessions.py:166 in resolve_redirects
      162│             except (ChunkedEncodingError, ContentDecodingError, RuntimeError):
      163│                 resp.raw.read(decode_content=False)
      164│
      165│             if len(resp.history) >= self.max_redirects:
    → 166│                 raise TooManyRedirects('Exceeded {} redirects.'.format(self.max_redirects), response=resp)
      167│
      168│             # Release the connection back into the pool.
      169│             resp.close()
      170│
`
These projects are installable via pip (normal or editable).

Thanks!

**Comment by finswimmer** [comment]
Related: https://github.com/python-poetry/poetry/issues/2141
