### ISSUE TITLE
 Permission denied when attempting `poetry self update --preview`

### ISSUE THREAD

**Issue by bennylut** [python-poetry/poetry#4426]
- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Linux Mint 19 Cinnamon
- **Poetry version**: 1.1.8

## Issue
I installed poetry using the new `install-poetry.py` script as described [here](https://python-poetry.org/docs/master/#installation).
I then proceeded to attempt and upgrade to 1.2.0a2 by running the command:
`poetry self update --preview` and got the following error: 

```
 EnvCommandError

  Command ['pip', 'uninstall', 'urllib3', '-y'] errored with the following return code 2, and output: 
  Found existing installation: urllib3 1.22
  Uninstalling urllib3-1.22:
  ERROR: Exception:
  Traceback (most recent call last):
    File "/usr/lib/python3.6/shutil.py", line 550, in move
      os.rename(src, real_dst)
  PermissionError: [Errno 13] Permission denied: '/usr/lib/python3/dist-packages/urllib3' -> '/tmp/pip-uninstall-m6nzl8u_'
```

**Comment by Kurt-von-Laven** [comment]
I am able to replicate this  when I attempt `poetry self update` from 1.1.8 to 1.1.10 or `poetry self update --preview` from 1.1.10 to 1.2.0a2. I also used the new `install-poetry.py` script and am running Ubuntu 21.04.

```
  - Updating certifi (2020.6.20 /usr/lib/python3/dist-packages -> 2021.5.30)

  EnvCommandError

  Command ['/usr/bin/pip3', 'uninstall', 'certifi', '-y'] errored with the following return code 2, and output: 
  Found existing installation: certifi 2020.6.20
  Uninstalling certifi-2020.6.20:
  ERROR: Exception:
  Traceback (most recent call last):
    File "/usr/lib/python3.9/shutil.py", line 806, in move
      os.rename(src, real_dst)
  OSError: [Errno 18] Invalid cross-device link: '/usr/lib/python3/dist-packages/certifi' -> '/tmp/pip-uninstall-0btivxm3'
```

**Comment by ruancomelli** [comment]
For anyone getting a similar error, I was able to update to v1.1.12 by running:
```zsh
$ exit
$ deactivate
$ poetry self update
```

**Comment by jedie** [comment]
Maybe it's duplication of https://github.com/python-poetry/poetry/issues/5490 and the real problem is https://github.com/pypa/setuptools/issues/3278 ?

**Comment by neersighted** [comment]
I'm closing this as there is no reproduction overall; this appears to mostly be an artifact of trying to self upgrade a distro-installed Poetry (which will not work). @jedie this is unrelated to #6371 or pypa/setuptools#3278.
