### ISSUE TITLE
Poetry 1.1.8 does't install all project dependencies, but 1.1.7 does

### ISSUE THREAD

**Issue by the-papi** [python-poetry/poetry#4427]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Debian buster
- **Poetry version**: 1.1.8
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/the-papi/de61802c74fca0c1c8165c76408e2e7b

## Issue
After upgrading Poetry to 1.1.8, it doesn't install all the required dependencies, but only a few. `poetry isntall` and `poetry show` tells me they're installed, but python raises `ModuleNotFoundError`. I tried to run `poetry lock` again, but it didn't help.

**Comment by Rydra** [comment]
I'm experiencing the same problem with git dependencies retrieved from a private repository through SSH. `poetry install` just shows that it's installing those dependencies over and over again, without actually never installing them (running another `poetry install` just tries to do the same.

**Comment by NiklasBeierl** [comment]
This happened to me as well but with poetry 1.1.7.
I was using `poetry config virtualenvs.create false` in case that matters.
One package I know for sure wasn't installed is `pydantic`.
Also the three `packages` specified in pyproject.toml where not installed. 
The output of `poetry install` claimed that one of them got installed, but I got nada. 

Excerpts from my shell:
```root@setup-fixes-test:/opt/vendor/project# poetry --version
Poetry version 1.1.7
root@setup-fixes-test:/opt/vendor/project# poetry install
Skipping virtualenv creation, as specified in config file. <--- NOT USING VENV!
Installing dependencies from lock file

Package operations: 117 installs, 3 updates, 0 removals

  • Installing < redacted >
  • Installing pydantic (1.8.2) <---- ALSO WAS NOT INSTALLED!
  • Installing < redacted >

Installing the current project: arcusteam (0.3.0) <---- WAS NOT INSTALLED
root@setup-fixes-test:/opt/vendor/project# pip freeze | grep pydantic <--- NO RESULTS!
root@setup-fixes-test:/opt/vendor/project# cat pyproject.toml | grep pydantic
pydantic = "^1.8.2"

root@setup-fixes-test:/opt/vendor/project# poetry install
Skipping virtualenv creation, as specified in config file.
Installing dependencies from lock file

No dependencies to install or update

Installing the current project: my-project (0.3.0)
root@setup-fixes-test:/opt/vendor/project# pip freeze | grep pydantic <---- NO RESULTS!
root@setup-fixes-test:/opt/vendor/project# rm poetry.lock <--- ALSO TRIED NUKING THE LOCKFILE!
root@setup-fixes-test:/opt/vendor/project# poetry install
Skipping virtualenv creation, as specified in config file.
Updating dependencies
Resolving dependencies... (150.6s)

Writing lock file

Package operations: 0 installs, 7 updates, 0 removals

  • Updating importlib-metadata (4.6.4 -> 4.8.1)
  • Updating more-itertools (8.8.0 -> 8.9.0)
  • Updating msal (1.13.0 -> 1.14.0)
  • Updating tqdm (4.62.1 -> 4.62.2)
  • Updating typing-extensions (3.10.0.0 -> 3.10.0.2)
  • Updating azure-core (1.17.0 -> 1.18.0)
  • Updating setuptools-scm (6.2.0 -> 6.3.2)

Installing the current project: my-project (0.3.0)
root@setup-fixes-test:/opt/vendor/project# pip freeze | grep pydantic
root@setup-fixes-test:/opt/vendor/project# cat pyproject.toml | grep pydantic
pydantic = "^1.8.2"
root@setup-fixes-test:/opt/vendor/project# pip3 install pydantic
Collecting pydantic
  Downloading pydantic-1.8.2-cp38-cp38-manylinux2014_x86_64.whl (13.7 MB)
     |████████████████████████████████| 13.7 MB 25.2 MB/s
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.8/dist-packages (from pydantic) (3.10.0.2)
Installing collected packages: pydantic
Successfully installed pydantic-1.8.2
root@setup-fixes-test:/opt/vendor/project# pip freeze | grep pydantic # <--- PIP DID IT!
pydantic==1.8.2
```

**Comment by bifshteks** [comment]
I had the same. The problem was that some time ago I set pip's configuration `target` to some different location.
Check that `pip config list` does not shows you `global.target = /some/dir`
