### ISSUE TITLE
`poetry export` compose conditions with `and`, but should use `or`

### ISSUE THREAD

**Issue by kenoss** [python-poetry/poetry#4428]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubunto 20.04
- **Poetry version**: 1.2.0a2
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://github.com/kenoss/bug-report-poetry-export-mistake-and-or/tree/poetry-1.2.0a2

## Issue

`poetry export` seems to compose conditions with `and`, but it should use `or`.

### How to reproduce

```console
$ poetry new hoge
$ poetry add 'gevent==1.4.0' 'greenlet==0.4.15'
$ poetry add cryptography
$ poetry export -f requirements.txt -o requirements.txt
```

This produces `requirements.txt` including the following line:

```
cffi==1.14.6; sys_platform == "win32" and platform_python_implementation == "CPython" and (python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.4.0") and python_version >= "3.6" \
```

The part `sys_platform == "win32" and platform_python_implementation == "CPython" and (python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.4.0")` comes from `gevent`, `python_version >= "3.6"` comes from `cryptography`.

### Effect

This wrong result of export makes `pip install` failed.

```
+ pip3 install -r requirements.txt
...(snip)...
Ignoring cffi: markers 'sys_platform == "win32" and platform_python_implementation == "CPython" and (python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.4.0") and python_version >= "3.6" and (python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.5.0" and python_version >= "3.6")' don't match your environment
...(snip)...
Collecting werkzeug==1.0.1
  Downloading https://www.piwheels.org/simple/werkzeug/Werkzeug-1.0.1-py2.py3-none-any.whl (298 kB)
Collecting cffi>=1.12
ERROR: In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
    cffi>=1.12 from https://www.piwheels.org/simple/cffi/cffi-1.14.6-cp37-cp37m-linux_armv7l.whl#sha256=c993e9eefcd5d3b6ff6bf16e85a3c5c331ec8ac47d4b1a942da58aaf46f16519 (from cryptography==3.4.7->-r /tmp/work/on_build/actsim/requirements.txt (line 48))

Exited with code exit status 1
```

### Mitigation

Use `poetry export -f requirements.txt -o requirements.txt --without-hashes` (add `--without-hashes`) or add direct dependency `poetry add cffi`.

**Comment by atakanokan** [comment]
I think my issue is related to yours (however on Poetry 1.1.7). I have a dependency installation criteria based on the OS and the requirements.txt output is wrong:

`pyproject.toml`:
```
internal_pkg = [
   {markers = "sys_platform == 'win32'", url = "url_to_windows_package_in_artifactory"},
   {markers = "sys_platform == 'linux'", url = "url_to_windows_package_in_artifactory"}
]
```  

The exported `requirements.txt` is:
```
internal_pkg @ url_to_windows_package_in_artifactory ; sys_platform == "win32" or sys_platform == "linux"
```
where it should have an `and` instead of the `or` between `sys_platform` conditions

**Comment by neersighted** [comment]
Can you please test this on master and indicate the commit hash you test with?

**Comment by finswimmer** [comment]
Closing this, because it seems to be fixed. Feel free to leave a comment if you disagree.
