### ISSUE TITLE
Transitive multiple constraint dependency is incorrectly locked

### ISSUE THREAD

**Issue by mitchhentges** [python-poetry/poetry#4435]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Fedora 34
- **Poetry version**: `1.1.8`
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: [gist](https://gist.github.com/mitchhentges/27b67b75a1130b965241a987eeaa52a7)

## Issue
A dependency is using environment markers in its `setup.py` to conditionally set its dependency's version (in the [gist example](https://gist.github.com/mitchhentges/27b67b75a1130b965241a987eeaa52a7), `six==1.15.0` when Python <3.7, otherwise `six==1.16.0`).

When `poetry.lock` is generated, `[package.dependencies]` does not contain a cross-platform result: it just shows the expected `six` version for the current environment
```
[package.dependencies]
six = {version = "1.16.0", markers = "python_version >= \"3.7\""}

[package.source]
...
```
I was expecting it to do something like:
```
[package.dependencies]
six = [
    {version = "1.15.0", markers = "python_version < \"3.7\""},
    {version = "1.16.0", markers = "python_version >= \"3.7\""}
]
```

When I commit `poetry.lock` to version control [as recommended](https://python-poetry.org/docs/basic-usage/#commit-your-poetrylock-file-to-version-control), there will be "thrashing" when other differing environments generate the lockfile themselves.

**Comment by dimbleby** [comment]
latest master produces
```
[package.dependencies]
six = [
    {version = "1.15.0", markers = "python_version < \"3.7\""},
    {version = "1.16.0", markers = "python_version >= \"3.7\""},
]
```

**Comment by dimbleby** [comment]
so this can be closed
