### ISSUE TITLE
Command not found after fresh installation

### ISSUE THREAD

**Issue by snthibaud** [python-poetry/poetry#4440]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS**: Kubuntu 20.04
- **Poetry version**: 1.1.8

I tried to install poetry after removing miniconda. It seems to go well, but then executing Poetry fails with 'command not found'. I inspected the '~/.local/bin/poetry' symlink and found it pointed to a non-existing file in a virtual environment that poetry has created. Any suggestions?

**Comment by mateusdoiim** [comment]
I'm having something related to this, but on macOS and Python 3.8 🤔
Tracked on #4477
