### ISSUE TITLE
cannot install fastapi

### ISSUE THREAD

**Issue by jabbalaci** [python-poetry/poetry#4449]
OS: Manjaro Linux
poetry version: 1.1.8
Python version: Python 3.9.6

Problem:
```
$ poetry add fastapi
Using version ^0.68.1 for fastapi

Updating dependencies
Resolving dependencies... (0.0s)

  AssertionError

  

  at /usr/lib/python3.9/site-packages/poetry/mixology/incompatibility.py:111 in __str__
      107│         )
      108│ 
      109│     def __str__(self):
      110│         if isinstance(self._cause, DependencyCause):
    → 111│             assert len(self._terms) == 2
      112│ 
      113│             depender = self._terms[0]
      114│             dependee = self._terms[1]
      115│             assert depender.is_positive()
```

With poetry, I cannot install the package fastapi. With `pip`, installation goes without problem.

**Comment by sanders41** [comment]
I am also using Manjaro with the same version of poetry and python am able to add fastapi without error. Do you already have pydantic and/or starlette installed? If so maybe they are incompatible versions with fastapi 0.68.1?

**Comment by jabbalaci** [comment]
@sanders41 : Thanks! **Solved!**

It was my bad. I created a subdirectory called "fastapi", it was the project directory, and this name caused the error. When I used a different name for the folder, installation went smoothly.
