### ISSUE TITLE
Unable to install project with cython module

### ISSUE THREAD

**Issue by LouisTrezzini** [python-poetry/poetry#4455]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOs Big Sur 11.4
- **Poetry version**: 1.0.9 (working) / 1.1.8 (not working)
- **Minimal reproducible example**:  https://github.com/LouisTrezzini/poetry-bug 
- **Failed test matrix with verbose logs**: https://github.com/LouisTrezzini/poetry-bug/runs/3464418588

## Issue
Hello! We are trying to update our monorepo to use poetry 1.1.8 (from 1.0.9) and we fail to install one of our apps, that use some cython modules.

The error message is the following:
```
EnvCommandError

  Command ['/home/runner/.cache/pypoetry/virtualenvs/app-tM7F9sOs-py3.7/bin/pip', 'install', '-e', '/home/runner/work/poetry-bug/poetry-bug/app', '--no-deps'] errored with the following return code 1, and output: 
  Obtaining file:///home/runner/work/poetry-bug/poetry-bug/app
      ERROR: Command errored out with exit status 1:
       command: /home/runner/.cache/pypoetry/virtualenvs/app-tM7F9sOs-py3.7/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/runner/work/poetry-bug/poetry-bug/app/setup.py'"'"'; __file__='"'"'/home/runner/work/poetry-bug/poetry-bug/app/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-v2y02v_r
           cwd: /home/runner/work/poetry-bug/poetry-bug/app/
      Complete output (5 lines):
      Compiling src/app/_ops.pyx because it changed.
      [1/1] Cythonizing src/app/_ops.pyx
      /home/runner/.cache/pypoetry/virtualenvs/app-tM7F9sOs-py3.7/lib/python3.7/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/runner/work/poetry-bug/poetry-bug/app/src/app/_ops.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      error in app setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Invalid URL: ../mylib
      ----------------------------------------
  WARNING: Discarding file:///home/runner/work/poetry-bug/poetry-bug/app. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  WARNING: You are using pip version 21.2.3; however, version 21.2.4 is available.
```

Note that it works just fine on 1.1.8 for other apps that don't have a custom build step specified by `build = "build.py"`.

It seems like the build logic changed for custom build steps (see logs of the test run), and that it doesn't properly support path dependencies. However, the path dependency is NOT a build-time dependency, only a runtime dependency (not set in `build-system.requires`), so I'm wondering what's going on here. 
I'm not familiar with poetry internals, so it's hard for me to help or provide suggestions.

I'm hoping it's clear and there's an easy fix, let me know if there's anything I can do to help!

Thanks!

**Comment by dimbleby** [comment]
works fine with recent poetry
