### ISSUE TITLE
Cannot install cffi with pip 20.1.1

### ISSUE THREAD

**Issue by gsemet** [python-poetry/poetry#4459]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: MacOS Big Sur
- **Poetry version**: 1.1.8

## Issue

When installing cffi package on my machine, I get the following message:
```

  Command ['/Users/username/path/to/my/project/.venv/bin/pip', 'install', '--no-deps', 'file:///Users/username/Library/Caches/pypoetry/artifacts/7f/04/24/060e6112b020f63cd46fd340dba7c0bd3000a2e0ded5e6dace14fcd228/cffi-1.14.6-cp37-cp37m-macosx_10_9_x86_64.whl'] errored with the following return code 1, and output:
  ERROR: cffi-1.14.6-cp37-cp37m-macosx_10_9_x86_64.whl is not a supported wheel on this platform.
  WARNING: You are using pip version 20.1.1; however, version 21.2.4 is available.
  You should consider upgrading via the '/Users/username/path/to/my/project/.venv/bin/python -m pip install --upgrade pip' command.
```

It fails with this version of pip (20.1.1) which is installed in the virtualenv. However, from here if I manually execute the recommended command and install pip 21.2.4, then the next poetry install with successfully install cffi.

It looks like pip that is within the virtualenv cannot be upgraded even by defining it in the pyproject.toml.

**Comment by finswimmer** [comment]
Hello @gsemet,

poetry uses `virtualenv` under the hood which has its own mechanism to install `pip` and `setuptools` into the venv during creation. It's more or less the latest version of these packages it will install.

So if your venv still have pip 20.1.1 I guess it exists for a longer time. You can remove the venv and run `poetry install` once again or you upgrade `pip` in the venv on your own by `poetry run pip install -U pip`.

fin swimmer
