### ISSUE TITLE
Provide ability to read another .toml file instead of pyproject.toml

### ISSUE THREAD

**Issue by brechtm** [python-poetry/poetry#4460]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

I am aware that _pyproject.toml_ is a standard in the Python world, but in some cases it can be useful to add another `.toml` file beside it that builds a different kind of package. This requires Poetry to accept a command line option to point it to this other TOML file. I'm failing to think of a proper name, but something like:

    poetry --pyproject alt.toml build

As I'm writing this more and more questions are surfacing [1], so I'm not sure this is a good idea but I'll still post this here for consideration.

[1] e.g. what to do with the venv when switching from one TOML to another

Somewhat related: Ability to specify the directory to run poetry in instead of always using current directory #2179

**Comment by finswimmer** [comment]
Hello @brechtm,

thanks for your suggestion. However, poetry follows the principal that there should be only one single source of truth for project metadata (and it should always be the same place). So I don't think we will implement such a feature. Maybe this is something that can be provided by a plugin? The plugin feature is available int the current preview release (1.2.0a2).

Specify the directory where poetry should run in, is another topic as you already linked.

fin swimmer

**Comment by brechtm** [comment]
The use case I had in mind is probably better served by support for specifying multiple projects in the same `pyproject.toml` (#2270).

**Comment by guitarmanvt** [comment]
This doesn't entirely duplicate https://github.com/python-poetry/poetry/issues/2179 , and this ticket actually gets at what I want to do better than that other ticket.

The repo I'm working on provides a pyproject.toml that does not include a `[tool.poetry]` section. It does include sections for other tools, like `black` and `flake8`. I can run `poetry init` and create the necessary section, but poetry isn't widely-accepted at this company (yet), so I don't want to checkin these changes. That means it's a chore to avoid committing this updated pyproject.toml for every commit.

I want to specify a pyproject.toml file *just for poetry*, and not for anything else. I can add this special `poetry.pyproject.toml` to my `.gitignore` file, and this will satisfy my workflow.

**Comment by heimalne** [comment]
This feature would also be great to work around quirky packages like `wxpython` or some `torch` derivatives that expect you to install packages in several steps https://github.com/wxWidgets/Phoenix/issues/2225. With pip you could use call pip twice
```bash
pip install attrdict
pip install wxpython ...
```
With Poetry that's not so easy.

**Comment by Kache** [comment]
Another use-case for this: transitional upgrades, either for frameworks or for Python version

e.g. having two pyproject.toml's, one for Python 3.x and another for 3.x+1

in order to have an overlap period where CI needs to pass both builds
