### ISSUE TITLE
poetry export makes faulty conditions for package

### ISSUE THREAD

**Issue by SinSquare** [python-poetry/poetry#4461]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**:   Ubuntu 20.04.2 LTS (Focal Fossa)
- **Poetry version**: 1.1.8
- **Link of a [Gist](https://gist.github.com/SinSquare/e39244e36bf1d5f706108323497f9fc8) with the contents of your pyproject.toml file**: 

## Issue
Created a sample project with 2 dependencies ([Gist](https://gist.github.com/SinSquare/e39244e36bf1d5f706108323497f9fc8)).

When running `poetry export --without-hashes -f requirements.txt -o requirements.txt` the requirements.txt contains the following line:
```
colorama==0.4.4; python_version >= "3.7" and python_full_version < "3.0.0" and sys_platform == "win32" or sys_platform == "win32" and python_version >= "3.7" and python_full_version >= "3.5.0"
```
The problem here is that the `colorama` package will be installed only on win32 machines, however the poetry.lock contains the following package/dep:
```
[[package]]
name = "crayons"
version = "0.4.0"
description = "TextUI colors for Python."
category = "main"
optional = false
python-versions = "*"

[package.dependencies]
colorama = "*"
```

If I remove the `ipython` package, it works as expected, and the requirements will contain
```
colorama==0.4.4; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.5.0"
```

In my understanding the `requirements.txt` should contain a non-platform dependent entry for the `colorama` package

**Comment by SinSquare** [comment]
Also if I add `colorama` package to the `pyproject.toml`, the exported requirements will contain 
```
colorama==0.4.4; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.5.0")
```
which could be a temporary workaround

**Comment by astrojuanlu** [comment]
Came here to report this same issue.

**Comment by dimbleby** [comment]
with latest versions of poetry and poetry-core we get
```
colorama==0.4.4 ; python_version >= "3.8" and python_version < "4.0"
```
which looks perfect, this can be closed
