### ISSUE TITLE
GCP keyring is not used

### ISSUE THREAD

**Issue by snthibaud** [python-poetry/poetry#4464]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Kubuntu 20.04 LTS
- **Poetry version**: 1.1.8
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/snthibaud/93a9e72d8d0081b0dcadfe1b11c282e2

## Issue
I followed the steps to [set up authentication](https://cloud.google.com/artifact-registry/docs/python/authentication) for my Google Artifacts repository. After that, I also installed the keyring and keyrings.google-artifactregistry-auth packages inside the Poetry virtual environment (possibly unnecessarily, because they were installed in the base environment already).
I also added the repo URL to poetry with `poetry config repositories.myrepository https://myurl.com/simple/`
Installing packages with pip works and pip indicates it is also considering my repository.
Poetry still prompts for a username and password when trying to publish, however:

```
(mailer-0cRDLs4C-py3.8) abc@def:~/PycharmProjects/mailer$ poetry publish -r myrepository

Username: 
```

Am I doing something wrong or is GCP keyring authentication not supported by Poetry?

**Comment by caseydialpad** [comment]
Handled in upcoming version `1.2.0`.  Try the alpha version `1.2.0a`.

See https://github.com/python-poetry/poetry/pull/4086

**Comment by ralbertazzi** [comment]
Working since 1.2 and plugins have been added. https://github.com/GoogleCloudPlatform/artifact-registry-python-tools/issues/17#issuecomment-1040309388
