### ISSUE TITLE
Untracked dependencies are removed without --remote-untracked

### ISSUE THREAD

**Issue by 54sledgehammer45** [python-poetry/poetry#4485]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: docker
- **Poetry version**: 1.1.8
- **Link of a  repo with the scenario**: https://github.com/54sledgehammer45/poetry_remove_tracked_issue

## Issue

With `poetry config virtualenvs.create false`, and packages that somehow don't require `requests` (and possibly other packages), when running `poetry install --no-dev` the unnecessary packages are removed. This can lead to a broken `pip` and even broken `poetry` - without requests `poetry` can't talk to the internet.

**Comment by finswimmer** [comment]
Hello @54sledgehammer45,

please see my answer in https://github.com/python-poetry/poetry/issues/4493#issuecomment-916771927 to understand what's going on and how to avoid it.

fin swimmer
