### ISSUE TITLE
Unable to install package ("tables") with build extensions.

### ISSUE THREAD

**Issue by jrouly** [python-poetry/poetry#4491]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Mac OS Big Sur 11.5.2
- **Poetry version**: `1.2.0a2`
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/jrouly/631d9ccad230ab102c9eff275362791d

## Issue

Hello. When upgrading Poetry from 1.1.8 to 1.2.0a2 I stopped being able to install the package [`tables`](https://pypi.org/project/tables/) (aka PyTables).

Full installation log on a fresh virtual environment is also included in the linked [gist](https://gist.github.com/jrouly/631d9ccad230ab102c9eff275362791d).

When installed with Poetry 1.1.8 there are no issues.

Based on what I think are the relevant logs from the error output:
```
...

    Traceback (most recent call last):
      File "/private/var/folders/2_/2p3bkfd56qx6x8njjbvln3840000gq/T/pip-build-env-q1p49hjd/overlay/lib/python3.9/site-packages/pkg_resources/__init__.py", line 344, in get_provider
        module = sys.modules[moduleOrReq]
    KeyError: 'numpy'

...

      File "/private/var/folders/2_/2p3bkfd56qx6x8njjbvln3840000gq/T/pip-build-env-q1p49hjd/overlay/lib/python3.9/site-packages/pkg_resources/__init__.py", line 346, in get_provider
        __import__(moduleOrReq)
    ModuleNotFoundError: No module named 'numpy'
    ----------------------------------------
    ERROR: Failed building wheel for tables
  Failed to build tables
  ERROR: Could not build wheels for tables which use PEP 517 and cannot be installed directly

...
```

this might be being caused by the build extension in PyTable's [`setup.py`](https://github.com/PyTables/PyTables/blob/v3.6.1/setup.py#L53-L74)? Although I don't know for sure.

If useful, here is the `pip freeze` after installation fails (it's empty prior):
```
(issue) [issue]$ pip freeze
numexpr==2.7.3
numpy==1.21.1
```

**Comment by jrouly** [comment]
I've also filed an issue against PyTable: https://github.com/PyTables/PyTables/issues/907

**Comment by finswimmer** [comment]
Hello @jrouly,

I'm not sure why poetry >1.1.8 doesn't find a suitable wheel file for the package and falls back to the sdist. I guess this is something we have to investigate.

But pytables really should include a `pyproject.toml` defining their build-dependencies according to [PEP 518](https://www.python.org/dev/peps/pep-0518/).

fin swimmer

**Comment by jrouly** [comment]
Thanks for the quick reply @finswimmer.

I noted this on the PyTables issue I filed (https://github.com/PyTables/PyTables/issues/907), but it turns out that `pip install --use-pep517` also fails for that package. So this may not actually be a bug/issue with Poetry.

I _suspect_ not finding a suitable wheel file is due to my OS version. The [list of published files](https://pypi.org/project/tables/#files) seems to include Mac OS major version 10 builds, whereas I'm on major version 11. Does that sound plausible to you? I'm admittedly a newcomer to Python build systems and artifacts.

**Comment by jrouly** [comment]
this seems to be an issue entirely with Pytables. I'll close this issue.
