### ISSUE TITLE
`include` files are not stored in the right directory in the wheel package

### ISSUE THREAD

**Issue by vchrombie** [python-poetry/poetry#4494]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Kubuntu 20.04
- **Poetry version**: 1.1.8
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://github.com/chaoss/grimoirelab-toolkit/blob/cc5a14a1c353f4389b1b70fa8aef1c61881bc8da/pyproject.toml

## Issue

When we build the wheel packages, the files which are configured using `include` are added to the root directory.

```
include = [
    "AUTHORS",
    "README.md",
    "LICENSE",
    "NEWS"
]
```

```
$ poetry build -f wheel -vvv
Using virtualenv: /home/p0tt3r/dev/sources/grimoirelab-toolkit/.venv
Building grimoirelab-toolkit (0.2.0)
  - Building wheel
  - Adding: /home/p0tt3r/dev/sources/grimoirelab-toolkit/grimoirelab_toolkit/__init__.py
  - Adding: /home/p0tt3r/dev/sources/grimoirelab-toolkit/grimoirelab_toolkit/_version.py
  - Adding: /home/p0tt3r/dev/sources/grimoirelab-toolkit/grimoirelab_toolkit/datetime.py
  - Adding: /home/p0tt3r/dev/sources/grimoirelab-toolkit/grimoirelab_toolkit/introspect.py
  - Adding: /home/p0tt3r/dev/sources/grimoirelab-toolkit/grimoirelab_toolkit/uris.py
  - Adding: /home/p0tt3r/dev/sources/grimoirelab-toolkit/AUTHORS
  - Adding: /home/p0tt3r/dev/sources/grimoirelab-toolkit/README.md
  - Adding: /home/p0tt3r/dev/sources/grimoirelab-toolkit/LICENSE
  - Adding: /home/p0tt3r/dev/sources/grimoirelab-toolkit/NEWS
Skipping: /home/p0tt3r/dev/sources/grimoirelab-toolkit/COPYING
  - Built grimoirelab_toolkit-0.2.0-py3-none-any.whl

$ python -m zipfile -l dist/grimoirelab_toolkit-0.2.0-py3-none-any.whl
File Name                                             Modified             Size
AUTHORS                                        1980-01-01 00:00:00          218
LICENSE                                        1980-01-01 00:00:00        35147
NEWS                                           1980-01-01 00:00:00          503
README.md                                      1980-01-01 00:00:00          842
grimoirelab_toolkit/__init__.py                1980-01-01 00:00:00         1011
grimoirelab_toolkit/_version.py                1980-01-01 00:00:00           97
grimoirelab_toolkit/datetime.py                1980-01-01 00:00:00         5606
grimoirelab_toolkit/introspect.py              1980-01-01 00:00:00         3846
grimoirelab_toolkit/uris.py                    1980-01-01 00:00:00         1383
grimoirelab_toolkit-0.2.0.dist-info/LICENSE    1980-01-01 00:00:00        35147
grimoirelab_toolkit-0.2.0.dist-info/WHEEL      2016-01-01 00:00:00           83
grimoirelab_toolkit-0.2.0.dist-info/METADATA   2016-01-01 00:00:00         1751
grimoirelab_toolkit-0.2.0.dist-info/RECORD     2016-01-01 00:00:00         1032
```

When the package is installed using pip, the files are inflated into the `/lib/python3.8/site-packages/` folder directly.
```
$ python3 -m venv /tmp/myvenv
$ source /tmp/myvenv/bin/activate/
(myvenv) $ pip install grimoirelab-toolkit
(myvenv) $ ls /tmp/myvenv/lib/python3.8/site-packages/
AUTHORS                              LICENSE               pkg_resources-0.0.0.dist-info    setuptools-44.0.0.dist-info
dateutil                             NEWS                  __pycache__                      six-1.16.0.dist-info
easy_install.py                      pip                   python_dateutil-2.8.2.dist-info  six.py
grimoirelab_toolkit                  pip-20.0.2.dist-info  README.md
grimoirelab_toolkit-0.2.0.dist-info  pkg_resources         setuptools
```

I feel the files should be inflated into the `grimoirelab_toolkit-0.2.0.dist-info` folder like how it happens with `python setup.py bdist_wheel`. 
```
$ python setup.py bdist_wheel

$ python -m zipfile -l dist/grimoirelab_toolkit-0.2.0-py3-none-any.whl
File Name                                             Modified             Size
grimoirelab_toolkit/__init__.py                2021-04-26 13:43:42         1011
grimoirelab_toolkit/_version.py                2021-04-26 13:43:42           97
grimoirelab_toolkit/datetime.py                2021-04-26 13:43:42         5606
grimoirelab_toolkit/introspect.py              2021-04-26 13:43:42         3846
grimoirelab_toolkit/uris.py                    2021-04-26 13:43:42         1383
grimoirelab_toolkit-0.2.0.dist-info/AUTHORS    2021-09-09 13:35:48          218
grimoirelab_toolkit-0.2.0.dist-info/LICENSE    2021-09-09 13:35:48        35147
grimoirelab_toolkit-0.2.0.dist-info/METADATA   2021-09-09 13:35:48         1503
grimoirelab_toolkit-0.2.0.dist-info/WHEEL      2021-09-09 13:35:48           92
grimoirelab_toolkit-0.2.0.dist-info/top_level.txt 2021-09-09 13:35:48           20
grimoirelab_toolkit-0.2.0.dist-info/RECORD     2021-09-09 13:35:48          982
```

I would appreciate it if someone can confirm it's a bug else I would like to know if there are any workarounds for fixing the problem.

Thank you in advance.

_Originally reported by @sduenas at https://github.com/chaoss/grimoirelab-toolkit/issues/44._

**Comment by filip-halemba** [comment]
@vchrombie - I can confirm that I have the same situation in my project.

**Comment by finswimmer** [comment]
Hello,

it's not that easy as I first thought. We cannot put any file included from the root folder into dist-info, because in case of "module only" packages, we exactly want the current behavior.

Further investigation shows, that poetry already include files from the root folder, that matches the pattern `COPYING*` and `LICENSE*`, into the dist-info folder of the wheel. So just remove those entries from the `include`list. `wheel` is doing this for some more patterns (see: https://wheel.readthedocs.io/en/stable/user_guide.html#including-license-files-in-the-generated-wheel-file). We maybe should include these patterns as well.

Including license information into the wheel makes absolutely sense for legal reasons. Other files like README or NEWS are more for `sdist`'s. That's why I think there is no strong reason for an option to include in arbitrary number of files to the dist-info folder of a wheel.

fin swimmer

**Comment by vchrombie** [comment]
Hi finswimmer, thanks a lot for trying out the experiments and for the suggestions.

> it's not that easy as I first thought. We cannot put any file included from the root folder into dist-info, because in case of "module only" packages, we exactly want the current behavior.

Ok, I understand that poetry needs this behaviour.

> Further investigation shows, that poetry already include files from the root folder, that matches the pattern `COPYING*` and `LICENSE*`, into the dist-info folder of the wheel. So just remove those entries from the `include`list. `wheel` is doing this for some more patterns (see: https://wheel.readthedocs.io/en/stable/user_guide.html#including-license-files-in-the-generated-wheel-file). We maybe should include these patterns as well.

Yes, I think keeping updated with the wheel supported formats would be great. Do you think we can open another issue/pr for this particular case?

> Including license information into the wheel makes absolutely sense for legal reasons. Other files like README or NEWS are more for `sdist`'s. That's why I think there is no strong reason for an option to include in arbitrary number of files to the dist-info folder of a wheel.

Hmm, I don't have any strong reason to argue the files should be moved into the `.dist-info` folder.

**Comment by vchrombie** [comment]
Closing the issue in favor of the [explanation by finswimmer](https://github.com/python-poetry/poetry/issues/4494#issuecomment-926557216)

**Comment by JanMalte** [comment]
Just a note for anyone who comes here with the same question.

You can add the `README.md`, or any other file, to only the `sdist` package using the following in your `pyproject.toml`

```toml
# ...
include = [
    { path = "CHANGELOG.md", format = "sdist" },
]
```
