### ISSUE TITLE
How to create whl files without showing source code?

### ISSUE THREAD

**Issue by vneseresearcher** [python-poetry/poetry#4496]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

Hi all,
As title, I want to find a way to build whl file without including source code (binary lib)

Thank you

**Comment by finswimmer** [comment]
Hi @vneseresearcher,

it's not clear to me what you trying to achieve. Please add more detailed information.

Thanks.

fin swimmer

**Comment by finswimmer** [comment]
I'm closing this because we haven't receive no more information for a long time now.

Feel free to leave a comment if you disagree.
