### ISSUE TITLE
Credentials passed to private PyPI server maintained for all requests

### ISSUE THREAD

**Issue by kabirkhan** [python-poetry/poetry#4497]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 20.04
- **Poetry version**: 1.1.8
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/kabirkhan/4bc063c148b28ada980f08a79cc5f35c

## Issue

My team has an s3-backed private PyPI server which is secured using a LICENSE_KEY. Users purchase a license and can use the key to download any past version of the .whl. The implementation of the server uses this LICENSE_KEY as the username in HTTP Basic Auth, with an empty password. If we can validate that LICENSE_KEY, we fetch a list of .whl files from an AWS S3 bucket for all past versions + platforms and return a pre-signed URL using the boto3 library. 

If I pip install from this server:

```bash
pip install my_package -f https://{LICENSE_KEY}:@my_server.com
```
this installs the package correctly.

However, when I add this server as a secondary source in poetry:

```toml
[tool.poetry.source]
name = "private_pypi"
url = "http://TEST_LICENSE:@my_server.com"
secondary = true
```

the install fails with a 400 error. The error occurs due to poetry passing my HTTP Basic auth credentials to the AWS S3 pre-signed URL. AWS throws the error saying there can only be 1 auth method (which is the pre-signed URL) but Basic Auth credentials were also passed.

The error seems to occur due to the request Session being retained here: 
**Repository passing requests.Session with basic auth creds** - [`repositories/legacy_repository.py`](https://github.com/python-poetry/poetry/blob/c320955007a36173245c24d16076f9cf06b334c9/poetry/repositories/legacy_repository.py#L449)
**Using provided session** [`helpers.py`](https://github.com/python-poetry/poetry/blob/c320955007a36173245c24d16076f9cf06b334c9/poetry/utils/helpers.py#L98)

I can definitely see scenarios where the auth credentials should be retained so it makes sense why the session is used here but I'd love the ability to turn this off, maybe as a setting in the `[tool.poetry.source]` section. 

Since this works with a pip install I'd expect it to work with poetry as well.

Gist with the basics of my PyPI server are [here](https://gist.github.com/kabirkhan/4bc063c148b28ada980f08a79cc5f35c)

Happy to help contribute as well and thanks for the great project!

Thanks @willfrey for helping identify this bug.

**Comment by mr-bjerre** [comment]
This is also an issue for people using `prodigy`: https://support.prodi.gy/t/400-client-error-when-trying-to-install-prodigy-using-poetry/5212

**Comment by neersighted** [comment]
This code is entirely replaced in Poetry 1.2 -- please open an issue if you still observe unexpected credentials being passed.
