### ISSUE TITLE
installer not getting the latest files from repo (poetry new --readme argument missing and not defaulting to markdown)

### ISSUE THREAD

**Issue by tekdj7** [python-poetry/poetry#4500]
- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS Big Sur 11.5.2
- **Poetry version**: 1.1.8
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: N/A

## Issue
- Installed Poetry via the [curl command](https://github.com/python-poetry/poetry#osx--linux--bashonwindows-install-instructions)
- `poetry new --help`, does not show the `--readme` argument.
- `new.py` file that was installed on my computer to `/Users/<USER>/Library/Application Support/pypoetry/venv/lib/python3.9/site-packages/poetry/console/commands\` is missing the `--readme` argument code.
- Yet, `new.py` on [GitHub](https://github.com/python-poetry/poetry/blob/master/poetry/console/commands/new.py) has the `--readme` argument code.  
- I'm sure the same applies to other files, but didn't dig further.  Please look into why the 1.1.8 poetry version being installed via the curl command, and/or using [install-poetry.py](https://github.com/python-poetry/poetry/blob/master/install-poetry.py) is not getting the latest files from your Git repo.  
- FYI, ran into this, because was trying to get poetry to create `README.md`, instead its still creating for me, `README.rst`.  Per [pull-request 2768](https://github.com/python-poetry/poetry/pull/2768), support for readme markdown was included here.

**Comment by tekdj7** [comment]
Grouping dependencies doesn't work either, the `--group` argument not available with the `poetry add` commands, etc.  Though in your [documentation](https://python-poetry.org/docs/master/managing-dependencies/#adding-a-dependency-to-a-group), it should exist.

**Comment by finswimmer** [comment]
Hello @tekdj7,

this is expected. The install script installs the latest stable release by default. The features you are missing are included in the preview release. You can install it with `curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python - --preview`

fin swimmer
