### ISSUE TITLE
Allow use of `poetry` to check that a package has well-formed dependency data by running the solver

### ISSUE THREAD

**Issue by sirosen** [python-poetry/poetry#4512]
**Use Case**

I recently ran into a bug with a package which I maintain (but which does not publish using `poetry`) was not installable with `poetry`.
Specifically, the PEP508 metadata was malformed and had an invalid `python_version` spec: `typing_extensions; python_version<"3,8"`

The `3,8` is not merely ambiguous in meaning -- it's invalid under the grammar for PEP508.

We had no idea the dependency spec was malformed until using `poetry` to grab the package, which, correctly, fails on this malformed data. (The failure mode is not particularly great, but the package data is bad, so it's probably fine to leave that alone.)

I want to be able to use `poetry` to check either from the `setup.py` or a built package (sdist, wheel, etc) that package metadata will be satisfactory.

**Current State of the Art**

`pip` seems to ignore the malformed data and `twine check` does not catch it either. I guess they don't consider it an error, perhaps to be "future compatible" with changes to the spec?

For now, I've added a build step which runs `poetry lock` in a dir where `pyproject.toml` has a dependency spec like `foo = { path = "../.." }` and this seems to work as a test.
However, I'd prefer not to have to setup this structure in every/any package I want to test in this way.

**Feature Proposal**

It would be great if I could run poetry without a pyproject file using some invocation like
```
poetry check --other foo.whl
```
to check that `foo.whl` specifies a package whose metadata will solve correctly under `poetry`.

**Comment by ralbertazzi** [comment]
This looks an interesting idea... for a plugin 😄 As you pointed out, you want to use Poetry for managing something outside of Poetry's scope. Poetry does already a lot of stuff and it doesn't necessarily have to do everything, that's why plugins exist :)

I'll close this as not planned. In case you end up creating a plugin feel free to post it here!
