### ISSUE TITLE
Exception: `No module named 'virtualenv.activation.nushell'`

### ISSUE THREAD

**Issue by shahinism** [python-poetry/poetry#4515]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: python:3.9 Docker container (Debian GNU/Linux 11 (bullseye))
- **Poetry version**: 1.1.8
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/shahinism/c24445184019d5568dac4717dd7253a5

## Issue

Hi, 

Starting yesterday afternoon, on our Gitlab CI runners, `poetry install` and `poetry run` commands are failing with the following error:

```
  ModuleNotFoundError
  No module named 'virtualenv.activation.nushell'
  at <frozen importlib._bootstrap>:984 in _find_and_load_unlocked
```
I suspect this is related to yesterday's release of the pypa/virtualenv#2170 [release](https://github.com/pypa/virtualenv/releases/tag/20.8.0) which added [nutshell support](https://github.com/pypa/virtualenv/blob/d810ce1c0613d1b955576bca644335b7a00b5bc0/docs/changelog.rst#v2080-2021-09-16). 

However, the reason I report it here, is that I can't reproduce it with normal virtualenv creation commands when this version of virtualenv is installed. I tried to resolve this issue by setting `SHELL` environment variable to `bash` (as expected to inform `poetry` about the desired shell), and failed. However, running `poetry` commands like:

```
bash -c poetry install
bash -c poetry run ...
```
Works with no problem. You can find a more detailed log output on [this gist](https://gist.github.com/shahinism/92d47e1acf2b0c3667bf3232a2cdd9f1).

**Comment by theelderbeever** [comment]
Having this same issue on MacOS when attempting to `poetry add 'dvc[s3]'` into a python 3.8.10 virtualenv created with `pyenv`.

**Comment by linzwatt** [comment]
I was getting the same issue. Rolling back `virtualenv` to the previous version fixed this for me...
`pip install virtualenv==20.7.2`

**Comment by garciparedes** [comment]
I had the same problem, but it was fixed simply updating `poetry` to the latest version with:
```bash
poetry self update
```

**Comment by AliyevH** [comment]
I could fix this issue with pip uninstall virtualenv.

**Comment by neersighted** [comment]
Should be resolved -- this is an issue with versions of the virtualenv module. If anyone can identify the bad versions we can exclude them from our constraints -- otherwise simply updating to a modern version should fix this.

**Comment by MythicManiac** [comment]
Started facing a similar issue with poetry versions 1.4.0 and above, older versions work.

> I was getting the same issue. Rolling back virtualenv to the previous version fixed this for me...
> pip install virtualenv==20.7.2

This seems to have fixed it, but I'm still unsure what the root cause is. I tried to look through the diffs between [1.3.2 and 1.4.0](https://github.com/python-poetry/poetry/compare/1.3.2...1.4.0) but nothing immediately seems suspicious. The version pin did change, so perhaps 1.3.2 resolved to a virtualenv version that didn't have the issue, whereas 1.4.0 resolves to a version that does (by default anyway).
