### ISSUE TITLE
It is recommended that the `poetry new` command does not simply convert .  (Dot) to _(Underline)

### ISSUE THREAD

**Issue by Andy-AO** [python-poetry/poetry#4518]
`poetry new plone.scale` will automatically generate `plone_scale` to import package, although `. ` and `-` cannot be used as package names, but the former has a practical meaning, it represents this hierarchy.

When the user uses `poetry new plone.scale`, what he wants to do is probably create the `plone/scale` folder, which in the perspective of importing package names would represent `plone.scale`.

In fact, the actual directory structure of the [plone.scale - PyPI](https://pypi.org/project/plone.scale/#files) project is `plone/scale`.

Confirm that this is not mentioned on [documentation](https://python-poetry.org/docs/cli/).

**Comment by finswimmer** [comment]
Hello @Andy-AO,

creating namespace packages via `poetry new` is is supported in the current pre-release (1.2.0a2):

```
$ poetry new plone.scale
$ tree plone.scale
plone.scale
├── README.md
├── plone
│   └── scale
│       └── __init__.py
├── pyproject.toml
└── tests
    └── __init__.py
```

fin swimmer

**Comment by Andy-AO** [comment]
@finswimmer 
I would also like to ask you a question, under what circumstances would a namespace package be used? Under what circumstances would a hyphen package be used?

For example, there is such a distribution package `django-localflavor` in django and such a distribution package `plone.scale` in plone.

**Comment by finswimmer** [comment]
Naming the package and how the package data is organized are two different things.

Namespace package makes it possible to split one package into multiple ones. But once there are installed they share the same import path. You can find a more deeper explanation [here](https://packaging.python.org/guides/packaging-namespace-packages/)

There is no way to say whether a package is a namespace package or a "normal" package by looking at the name. Names are just conventions that can be used or not. Dots in folder names can sometimes be tricky when parsing those names. So most people (including me) avoids them and use a `-` instead for project folders.
