### ISSUE TITLE
command to check lock file

### ISSUE THREAD

**Issue by cjw296** [python-poetry/poetry#453]
- [X] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

Would it be possible to add a `poetry check` command (oh, I see you'e used that already, maybe the command could be extended or have a `poetry lock --check`?) that will return zero if the current poetry.lock is both correct w.r.t. the pyproject.toml (ie: packages match) *and* that it matches the output of `poetry lock`.

**Comment by b0g3r** [comment]
It's very useful in CI/CD. With this command we could check that programmer didn't forget re-lock requirements.

**Comment by cjw296** [comment]
This feature request is still valid.

**Comment by gpkc** [comment]
I agree that this would be a nice feature!

**Comment by ocavue** [comment]
This feature is available in some other package managers. I list some examples below:  

- `npm ci`: https://docs.npmjs.com/cli/ci.html
- `yarn install --frozen-lockfile`: https://yarnpkg.com/lang/en/docs/cli/install/#toc-yarn-install-frozen-lockfile

**Comment by littlebtc** [comment]
I had figure out script to emulate the behavior of #1954 and fortunately it is simple:
```shell
python -c "from poetry.factory import Factory; l = Factory().create_poetry('.').locker; exit(0) if l.is_locked() and l.is_fresh() else exit(1)" 
```

**Comment by clintmod** [comment]
worth mentioning that you need poetry on your `PYTHONPATH` which you can do like:
```
PYTHONPATH="${PYTHONPATH}:${HOME}/.poetry/lib" \
python -c "from poetry.factory import Factory; l = Factory().create_poetry('.').locker; exit(0) if l.is_locked() and l.is_fresh() else exit(1)"  && echo 'OK'
```

**Comment by Qu4tro** [comment]
Thank you both!

I think it's also worth mentioning if you have not followed the recommended install, the necessary changes to PYTHONPATH might differ.

In my case, on ArchLinux, where I installed poetry via `pacman`, I had to:
```
PYTHONPATH="${PYTHONPATH}:/usr/lib/python3.8/site-packages"
poetry run python -c "from poetry.factory import Factory; l = Factory().create_poetry('.').locker; exit(0) if l.is_locked() and l.is_fresh() else exit(1)" && echo 'OK'
```

**Comment by cjw296** [comment]
I'll add to my requirements wishlist for this: also check that the .lock file is consistent with what's actually in the managed python environment.

I've commented on @cliebBS pull request #1954, but thought I'd mention it here too for completeness.

**Comment by clintmod** [comment]
I'd like to repot back and say this check in it's current form isn't really useful for me… it only checks to make sure that `poetry update` would result in no updates.

I thought it would function more like [bundlers deployment mode](https://bundler.io/man/bundle-install.1.html#DEPLOYMENT-MODE). So that it errors if the pyproject.toml has been modified but the lock file is out of date.

**Comment by hrist0stoichev** [comment]
If you use `poetry-dynamic-versioning` and the above mentioned script is failing, you can try this one:
```
PYTHONPATH="${PYTHONPATH}:${HOME}/.poetry/lib:${HOME}/.poetry/lib/poetry/_vendor/py3.6/" python -c "from poetry.factory import Factory; from pathlib import Path; l = Factory().create_poetry(Path('.')).locker; exit(0) if l.is_locked() and l.is_fresh() else exit(1)"  && echo 'OK' || (echo 'Lock file out of date. Maybe you need to do "poetry lock"'; exit 1)
```

**Comment by marwinxxii** [comment]
Another couple of ideas what can be done in CI scripts:

Generate `requirements.txt` before and after updating the lock:
```
poetry export -f requirements.txt --output requirements-expected.txt
poetry lock --no-update
poetry export -f requirements.txt --output requirements-actual.txt
if ! diff --ignore-all-space "requirements-expected.txt" "requirements-actual.txt"; then
  echo "poetry.lock file is outdated, please run 'poetry lock' and commit updated poetry.lock"
  exit 1
fi
```
(additional flags could be used: `poetry --dev --without-hashes export …`).

Or slightly simpler approach (but less reliable) is to generate lock file and check if differences were found in it using git:
```
poetry lock --no-update
if ! git diff --exit-code; then
  echo "poetry.lock file is outdated, please run 'poetry lock' and commit updated poetry.lock"
  exit 1
fi
```

**Comment by KonstantinSchubert** [comment]
The problem is that `poetry update` does two things, if my understanding is right:

1. Updates/installs/removes packages to match changes  that were made to pyproject.toml

2. Updates packages even their specification did not change in pyproject.toml wasn’t changed because it finds a new version which is allowed by semver

In CI, you usually want to force a `poetry update` in the first case, but not the second.
