### ISSUE TITLE
Docs: Make table of contents more usable and accessible

### ISSUE THREAD

**Issue by tharradine** [python-poetry/poetry#4540]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue
Hi,

There used to be a table of contents in the sidebar of the documentation. Now it's gone, and the only table of contents seems to be at the bottom of the page, which is very hidden and (in my opinion) not particularly user friendly.

The docs are very pretty, but usability counts.

Would you consider putting the table of contents back in the sidebar?

Thanks!

**Comment by finswimmer** [comment]
Hello @tharradine,

which browser are you using and which device (mobile, pc, tablet ...). Can you post a screenshot? For the table of content is still on the left site or on the top of the page if there is not enough space.

fin swimmer

**Comment by tharradine** [comment]
Hi @finswimmer,

Thanks for the quick response!

Sorry for assuming the change was a conscious one on your end. In hindsight I should have tried a different browser.

I'm using Firefox on a 1920x1080 24" monitor, and have diagnosed the issue as coming from the Keeper Password Manager browser extension. Annoyingly I can't seem to disable the extension just for python-poetry.org, so I'll probably just disable it entirely. Keeper Security applications tend to be a bit of a disaster unfortunately.

Weirdly it blocks out the entire sidebar and most of the navbar.

With Keeper Extension enabled:
![image](https://user-images.githubusercontent.com/65383009/134290347-84665515-dffd-4f9b-912c-36fb001e546e.png)

With Keeper Extension disabled:
![image](https://user-images.githubusercontent.com/65383009/134290376-ecf83a74-72a3-46ab-a920-3b0be71b0da6.png)

You're welcome to close the issue if you don't think this is possible to fix / worth addressing on your end.

Regards,
Toby

**Comment by finswimmer** [comment]
Hello @tharradine,

thanks for these information. It's not obvious what this extension is actually doing with the website. I think it not worth it to investigate it further. Feel free to do it on your own or maybe report it to the maintainer of the extension. Maybe they can easy clarify if it's a bug in their extension or if there something we can do. Just post your findings here.

fin swimmer
