### ISSUE TITLE
Installation of packages with build-time dependencies fail in some cases

### ISSUE THREAD

**Issue by mbahri** [python-poetry/poetry#4543]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 20.10
- **Poetry version**: 1.2.0a2
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/mbahri/e0f084f715178a3558d61dbc69b0a619

## Issue
Installation of packages that have build-time dependencies fails in some cases.

Example here: mayavi depends on numpy at build time.
```
$ poetry add mayavi

RuntimeError:
          Numpy is required to build Mayavi correctly, please install it first.
```
Pre-installing numpy:
```
$ poetry add numpy
$ poetry add mayavi

RuntimeError:
          Numpy is required to build Mayavi correctly, please install it first.
```

Other example:
```
$ poetry add POT

Installation crashes due to being unable to import cython
```
pre-installing cython:
```
$ poetry add cython
$ poetry add POT

Installation crashes due to being unable to import cython
```

This problem seems to depend on the version of python used for the project. The POT examples both work fine with Python 3.7 but crash with Python 3.9. However:
```
$ poetry shell
$ pip install POT
```

Works with Python 3.9.

**Comment by finswimmer** [comment]
Hello @mbahri,

these packages doesn't provide a wheel in all cases. So it's necessary to build them from the sdist files. The build step happens in a temporary build environment. That's why you don't have success by installing the build-dependency manually. All these package doesn't provide a `pyproject.toml` containing build-system requirements according to [PEP 518](https://www.python.org/dev/peps/pep-0518/). Please report it to the maintainer of the projects.

There's nothing poetry can do here.

fin swimmer

**Comment by mbahri** [comment]
Hello @finswimmer 

Thank you for the explanation, I will report the missing build-system requirements.

Do you have any idea why installation of POT works with poetry when using Python 3.7 but not with Python 3.9?

**Comment by finswimmer** [comment]
> Do you have any idea why installation of POT works with poetry when using Python 3.7 but not with Python 3.9?

[It looks like POT provide wheel files for python < 3.9.](https://pypi.org/project/POT/#files) So there is no need to build the package.

**Comment by mbahri** [comment]
Reported the issue to both projects, thanks!
