### ISSUE TITLE
poetry and poetry-core both install `poetry/__init__py`

### ISSUE THREAD

**Issue by sochotnicky** [python-poetry/poetry#4544]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Linux, 5.14.6 (but this doesn't matter all that much)
- **Poetry version**: git master
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: Not relevant here

## Issue

Right now poetry depends on poetry-core https://github.com/python-poetry/poetry/blob/1.1/pyproject.toml#L27 (guess there was a split at some point?). However both projects provide the same file - `poetry/__init__.py`:
https://github.com/python-poetry/poetry-core/blob/master/poetry/__init__.py
https://github.com/python-poetry/poetry/blob/master/poetry/__init__.py

I understand that poetry-core provides it so that it's usable outside poetry itself. However what this means is that they overwrite each others files. I found out while installing poetry when my packaging system (Gentoo/Portage) detected that one package was trying to overwrite files of another package.

Now - as long as the `__init__.py` files stay identical I guess this is not a practical issue for most people (and I can workaround), but it feels like sooner or later something will break. I don't have a good solution to offer either - other than perhaps renaming poetry-core module to something like "poetry_core" and then alias it within poetry itself? There might be better ways I guess...

**Comment by finswimmer** [comment]
Hello @sochotnicky,

please see https://github.com/python-poetry/poetry/issues/2800 why we need to do it like this until poetry 1.2.0.

fin swimmer

**Comment by sochotnicky** [comment]
Ah, sorry - I tried looking but didn't find the issue. Thanks for quick triage though :-)
