### ISSUE TITLE
Please merge PR #1511 🙏

### ISSUE THREAD

**Issue by simonrouse9461** [python-poetry/poetry#4547]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request
PR #1511 has been opened for almost 2 years. Is there any specific reason why it is still not merged? This PR is the major roadblock for my project to adopt poetry. I really hope it can be merged soon. Appreciate in advance.

**Comment by mkniewallner** [comment]
As stated in https://github.com/python-poetry/poetry/pull/1511#issuecomment-1134341524, single page repositories can now be defined using https://python-poetry.org/docs/master/repositories/#single-page-link-source, which should work similarly to `--find-links`.

This should be testable in the recently released [1.2.0b2](https://github.com/python-poetry/poetry/releases/tag/1.2.0b2) pre-release.
