### ISSUE TITLE
poetry install fails for dependencies using 2to3

### ISSUE THREAD

**Issue by DeltaWhy** [python-poetry/poetry#4557]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Debian Bullseye (Docker `python:3.9`)
- **Poetry version**: 1.1.10
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/DeltaWhy/e38a2231706cc97ea9011e5eb461eec5

## Issue
I am unable to install a poetry project containing `simpleeval` as a (transitive) dependency. I found out this issue is due to setuptools 58 removing support for 2to3. However I'm unable to fix this by pinning setuptools to a lower version, as poetry ignores my version specification (either in build-requirements or dependencies) and always installs the latest setuptools (currently 58.1.0) when creating its virtualenv. Is there any way to specify what is pre-installed into the virtualenv?

**Comment by finswimmer** [comment]
Hello @DeltaWhy,

pinning `setuptools` via `pyproject.toml` is supported in the current preview release (1.2.0a2).

But I'm not sure if this helps in your case. This package only provides an sdist file, so creating a wheel from it is necessary and this happens in a temporary venv which most likely will have a more recent version of setuptools. Correct solution would be to report to the maintainers of this package that they should include a `pyproject.toml` according to [PEP 518](https://www.python.org/dev/peps/pep-0518/) to define the build-dependencies.

fin swimmer

**Comment by DeltaWhy** [comment]
For anyone else encountering this issue, `poetry config virtualenvs.create false` allows install to succeed with poetry 1.1.10, but still fails with 1.2.0a2.
