### ISSUE TITLE
stdin or stdout error v1.1.10 on win10

### ISSUE THREAD

**Issue by shinegrin** [python-poetry/poetry#4563]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**:  windows10 + python3.8.0
- **Poetry version**: 1.1.10 
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue

 I cant install poetry v1.1.10 on my win10 computer machine.
![image](https://user-images.githubusercontent.com/18009347/134838240-2c426540-0401-4a39-94df-8a729fee1575.png)

**Comment by hsajib-jsf** [comment]
@shinegrin You are using deprecated version of the script. May be that is the reason. Did you try the updated script?:

`(Invoke-WebRequest -Uri https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py -UseBasicParsing).Content | python -`

**Comment by shinegrin** [comment]
> @shinegrin You are using deprecated version of the script. May be that is the reason. Did you try the updated script?:
> 
> `(Invoke-WebRequest -Uri https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py -UseBasicParsing).Content | python -`

Thanks a lot. By the way, https://python-poetry.org/docs/ does not upgrade.

**Comment by shinegrin** [comment]
Another stdin error occur when poetry add.
![image](https://user-images.githubusercontent.com/18009347/135196862-bdacd099-1c80-4764-afec-8059995d9fd4.png)
Could you please give me some advice?
