### ISSUE TITLE
Unable to install pyats with poetry due to RuntimeError- wheels for macOS are skipped

### ISSUE THREAD

**Issue by dmfigol** [python-poetry/poetry#4565]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS 11.6 x86_64
- **Poetry version**: 1.1.10
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: [pyproject.toml](https://gist.github.com/dmfigol/ef02d76b0fb23a5b9afd2e119c6bb8d2)

## Issue
I am unable to install pyats versions 21.8 or 21.8.1 with poetry, while I can install them with latest pip or I can install 21.7 pyats with poetry. The lock file is created, but wheels for my platform are not being added to it and consequently the installation fails with the RuntimeError.

```
-> % poetry install -vvv
Using virtualenv: /Users/dmfigol/projects/tmp/test-pyats/.venv
Updating dependencies
Resolving dependencies..
...
   1: derived: pyats (==21.8.1)
   1: fact: pyats (21.8.1) depends on pyats.aereport (>=21.8.0,<21.9.0)
   1: fact: pyats (21.8.1) depends on pyats.aetest (>=21.8.0,<21.9.0)
   1: fact: pyats (21.8.1) depends on pyats.async (>=21.8.0,<21.9.0)
   1: fact: pyats (21.8.1) depends on pyats.log (>=21.8.0,<21.9.0)
   1: fact: pyats (21.8.1) depends on pyats.kleenex (>=21.8.0,<21.9.0)
   1: fact: pyats (21.8.1) depends on pyats.connections (>=21.8.0,<21.9.0)
   1: fact: pyats (21.8.1) depends on pyats.datastructures (>=21.8.0,<21.9.0)
   1: fact: pyats (21.8.1) depends on pyats.easypy (>=21.8.0,<21.9.0)
   1: fact: pyats (21.8.1) depends on pyats.results (>=21.8.0,<21.9.0)
   1: fact: pyats (21.8.1) depends on pyats.reporter (>=21.8.0,<21.9.0)
   1: fact: pyats (21.8.1) depends on pyats.tcl (>=21.8.0,<21.9.0)
   1: fact: pyats (21.8.1) depends on pyats.topology (>=21.8.0,<21.9.0)
   1: fact: pyats (21.8.1) depends on pyats.utils (>=21.8.0,<21.9.0)
...
  1: derived: pyats.datastructures (>=21.8.0,<21.9.0)
...
   1: Version solving took 0.886 seconds.
   1: Tried 1 solutions.

Writing lock file

Finding the necessary packages for the current system

Package operations: 46 installs, 0 updates, 0 removals
...
  • Installing pyats.datastructures (21.8.1): Pending...
  • Installing pyats.datastructures (21.8.1): Failed

  RuntimeError

  Unable to find installation candidates for pyats.datastructures (21.8.1)

  at ~/Library/Application Support/pypoetry/venv/lib/python3.6/site-packages/poetry/installation/chooser.py:73 in choose_for
       69│             links.append(link)
       70│
       71│         if not links:
       72│             raise RuntimeError(
    →  73│                 "Unable to find installation candidates for {}".format(package)
       74│             )
       75│
       76│         # Get the best link
       77│         chosen = max(links, key=lambda link: self._sort_key(package, link))
```
**poetry.lock**
```
...
pyats = [
    {file = "pyats-21.8.1-cp36-cp36m-macosx_10_10_x86_64.whl", hash = "sha256:985a599feeb407cc41716f2ed4e11ac697343e0f530dcdcb1dc4aa040ed46281"},
    {file = "pyats-21.8.1-cp36-cp36m-macosx_10_16_x86_64.whl", hash = "sha256:4905b8ab5127916be6b281275df71b6437d4378dcfad9b93991e2e74ebb5ffd4"},
    {file = "pyats-21.8.1-cp36-cp36m-manylinux1_x86_64.whl", hash = "sha256:12dcb329b96cc20f0ef3e1df06a8e073daa8f88908aa2087d783510006533610"},
    {file = "pyats-21.8.1-cp37-cp37m-macosx_10_10_x86_64.whl", hash = "sha256:596bd19f01e2e2055abb84df7c3ee0d755284dba290a17ac3fb6208386c4e196"},
    {file = "pyats-21.8.1-cp37-cp37m-macosx_10_16_x86_64.whl", hash = "sha256:c62ba2ac2bf34a0cdd89754be0b5e40494c5075a31cdfec44d13ff05b5f4b2d8"},
    {file = "pyats-21.8.1-cp37-cp37m-manylinux1_x86_64.whl", hash = "sha256:69ab9fa828e0d8cb7d161213db926f13156dd7177ded2494a49c3717bd0798a6"},
    {file = "pyats-21.8.1-cp38-cp38-macosx_10_10_x86_64.whl", hash = "sha256:ae2b1a72c776fc43bbd31b1547a259adeb5f91bbe2c1e8cdedb8ae16e6e65dc2"},
    {file = "pyats-21.8.1-cp38-cp38-macosx_10_16_x86_64.whl", hash = "sha256:9c2c2522e3c0c278826dd206454ba5578c3e512612549b8277beb5b9463a9934"},
    {file = "pyats-21.8.1-cp38-cp38-manylinux1_x86_64.whl", hash = "sha256:2071c9a47890bffa6c5615dc5f76bddafc150ae101d57ca4f640b9916276a965"},
    {file = "pyats-21.8.1-cp39-cp39-macosx_10_10_x86_64.whl", hash = "sha256:8d9c7f1a999413fab576309405fe7b743541f5aeeb5a669c640e0e8b4cb8fc65"},
    {file = "pyats-21.8.1-cp39-cp39-macosx_10_16_x86_64.whl", hash = "sha256:7d33420c7d3e8c2080da6f4bff75b0dd566804b0c656d08a11d623270d2a7c94"},
    {file = "pyats-21.8.1-cp39-cp39-manylinux1_x86_64.whl", hash = "sha256:a1c6146f7a4dca86d45a27a318c35f3aca27a8c35e7cb15bcd9b15450dbb2808"},
]
...
"pyats.datastructures" = [
    {file = "pyats.datastructures-21.8.1-cp36-cp36m-manylinux1_x86_64.whl", hash = "sha256:9281f2c3a53c6bf830f04d7eacf42dd4f40ade205b9ebdb69b1503e973665e9f"},
    {file = "pyats.datastructures-21.8.1-cp37-cp37m-manylinux1_x86_64.whl", hash = "sha256:07518f32178938dca2b63caa2e1aa33ca6953b7b732294ccd3d9d607b3597fe6"},
    {file = "pyats.datastructures-21.8.1-cp38-cp38-manylinux1_x86_64.whl", hash = "sha256:d3d58ce383d8f36e1bab23d12da453c254da9c1608dd44313b55be979bf129a9"},
    {file = "pyats.datastructures-21.8.1-cp39-cp39-manylinux1_x86_64.whl", hash = "sha256:a88079d2e0ad3beb1e39c115e3c583d408fa98053d758a27780160f7d405376e"},
    # no wheels for macos even though they are published on pypi
]

**Comment by automateyournetwork** [comment]
I am having the same issue with pyats.datastructures (22.1)

• Installing pyats.datastructures (22.1)

  RuntimeError

  Unable to find installation candidates for pyats.datastructures (22.1)

  at C:\business\lib\site-packages\poetry\installation\chooser.py:72 in choose_for
       68│ 
       69│             links.append(link)
       70│
       71│         if not links:
    →  72│             raise RuntimeError(
       73│                 "Unable to find installation candidates for {}".format(package)
       74│             )
       75│
       76│         # Get the best link

**Comment by radoering** [comment]
If wheels are missing in the lock file, it may help to [clear the cache](https://python-poetry.org/docs/master/cli/#cache-clear) (at least for the concerning package).

**Comment by scetron** [comment]
I'm having the same issue with pyats.datastructures (23.11)

**Comment by jillesca** [comment]
Got same issue with `pyats.datastructures (23.11)`. Surprisingly `23.10` works, so based on the times from previous comments I think it might be an issue with the latest release on pypi. 

Since I'm installing pyats, what I did was to install the previous release to the lastest. At the time writting, latest is `23.11` and I installed `23.10`

```bash
poetry add pyats==23.10
```

This worked for me.

**Comment by dimbleby** [comment]
- if a suitable distribution for your platform exists at https://pypi.org/project/pyats.datastructures/#files but is not listed in `poetry.lock`: then per https://github.com/python-poetry/poetry/issues/4565#issuecomment-1032815693 you need to clear the poetry cache and re-lock

- if there is no suitable distribution for your platform then of course poetry can do nothing about that

either way there is no poetry bug here and this can be closed

**Comment by jillesca** [comment]
thanks for the reply @dimbleby. The link https://pypi.org/project/pyats.datastructures/#files helped to find out that at the time of writing this comment there are not wheels for my platform but there are for 23.10. 

It makes sense it failed and I think the solution is to ask the maintainers of `pyats.datastructures` for wheels for my platform.
