### ISSUE TITLE
Update Readme to include pip option for poetry install

### ISSUE THREAD

**Issue by rohanagrawal-amex** [python-poetry/poetry#4570]
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue
Could the documentation be updated to also provide pip as an alternative option to install poetry as facing issues described in https://github.com/python-poetry/poetry/issues/976

**Comment by finswimmer** [comment]
Hello @rohanagrawal-amex,

it is already documented, but not recommended: https://python-poetry.org/docs/#alternative-installation-methods-not-recommended

fin swimmer
