### ISSUE TITLE
Incorrect requirements.txt formatting in poetry export 

### ISSUE THREAD

**Issue by alexifm** [python-poetry/poetry#4575]
The `requirements.txt` format needs to put a space in front of the semicolon that specifies the package and the pyversion and platform constraints.  Right now, without the space, the semicolon will be interpreted as part of a URL.  See this issue in `packaging`:
https://github.com/pypa/packaging/issues/456

**Comment by pmav99** [comment]
@alexifm which poetry version do you use? In poetry 1.2 this will probably need to get fixed in https://github.com/python-poetry/poetry-export-plugin

I will open a ticket there.

**Comment by alexifm** [comment]
```sh
─❯ poetry -V
Poetry version 1.1.10
```
