### ISSUE TITLE
Enable multiple file hashing methods for backwards and forwards compatibility

### ISSUE THREAD

**Issue by colindean** [python-poetry/poetry#4578]
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Issue

My PR #4573 improves where the hash of an archive is checked against the hashes in the lockfile. While working on that PR, I spotted a potential improvement but want to collect feedback before I implement it.

I think this area could be further improved by representing the hashes as a `dataclass` or something containing the hash type and the string digest. The types of hashes would be more robust then instead of hardcoding sha256 in `poetry/installation/executor.py` and in `FileDependency.hash()`. It would also enable enumeration of hash types of known hashes so that `FileDependency.hash()` could return a list of hashes based on requested types. Doing this might alleviate the md5/sha256 problems arising from changes in poetry-core 1.0.6+ that affect Poetry 1.1.7+ users using Artifactory in at least https://github.com/python-poetry/poetry/issues/4523.

I'm willing to undertake this implementation if no maintainers object.

**Comment by colindean** [comment]
I'm going to undertake this!

**Comment by colindean** [comment]
https://github.com/python-poetry/poetry-core/commit/68bf05242e16f46640b0063677a80a1b8cf7f56e implemented a key part of this and I think @sdispater is heading in a similar direction…

**Comment by colindean** [comment]
python-poetry/poetry-core@68bf052 is not yet in 1.0 branch nor is it in a 1.1.0 alpha release. I'm not sure of the best way to consume `poetry-core` master in `poetry` other than just changing the dependency declaration temporarily. Ideally, I'd like to see that change released…

**Comment by neersighted** [comment]
This in in progress in #4486.

**Comment by colindean** [comment]
Thank you all especially @GMouzourou for picking up where I left off and finishing this finally!
