### ISSUE TITLE
can't install shiboken6 package not found, pip install finds package without issue

### ISSUE THREAD

**Issue by jjgalvez** [python-poetry/poetry#4582]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate. It may be a duplicate, not sure
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **Arch linux updated this morning: 
- **Poetry (version 1.2.0a2): 
- **https://gist.github.com/jjgalvez/eee152ae5ef60b3696828ff038fbaf61

## Issue
I am trying to install pyside6 which has shiboken6 as a dependancy. When installing I get the following error:
 Unable to find installation candidates for shiboken6 (6.2.0)
if I activate the env with poetry shell I can install shiboken with pip

**Comment by remram44** [comment]
`shiboken6` only has a wheel for Windows: https://pypi.org/project/shiboken6/6.2.0/#files That's a little curious :thinking:

`poetry add pyside6` fails because it assumes you want 6.2.0 and can't install on Linux, but `poetry add pyside6@6.1.3` works for me (Ubuntu), though I had to set `python = "<=3.8,<3.10"`

**Comment by jjgalvez** [comment]
I was going to take this up with QT because your right, and I'm not sure why only windows is linked when they have wheels for not Mac and linux

**Comment by jjgalvez** [comment]
still have not heard back from QT, but again the really odd thing is that PIP can find shiboken6 6.2.0 and pydise6 6.2.0 while poetry can't

**Comment by remram44** [comment]
Can it? `pip install pyside6` just installs `6.1.3` for me, since I'm not on Windows.

**Comment by jjgalvez** [comment]
I stand corrected, @remram44 you are correct pip only finds 6.1.3, ok back to waiting to see if someone from QT responds

**Comment by remram44** [comment]
Should this issue stay open? It looks like Poetry is working correctly

**Comment by jjgalvez** [comment]
@remram44 I suspect you're right it really looks like it is a qt/pypi issue and unrelated to poetry. this ticket should be closed.

**Comment by jjgalvez** [comment]
Issue unrelated to Poetry, Poetry working as intended.
