### ISSUE TITLE
Improve error message on PEP 440 constraint parsing failure

### ISSUE THREAD

**Issue by roganartu** [python-poetry/poetry#4597]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request
Poetry version: 1.2.0a2

### Problem

When any dependency in the dependency tree contains an invalid PEP 440 constraint, Poetry fails with the following error:
```
❯ poetry lock  
Updating dependencies
Resolving dependencies... (14.1s)

  InvalidVersion

  Invalid PEP 440 version: '3.5.'

  at /usr/scratch/xar/2ce5d136/lib/python3.8/site-packages/poetry/core/version/pep440/parser.py:67 in parse
       63│     @classmethod
       64│     def parse(cls, value: str, version_class: Optional[Type["PEP440Version"]] = None):
       65│         match = cls._regex.search(value) if value else None
       66│         if not match:
    →  67│             raise InvalidVersion(f"Invalid PEP 440 version: '{value}'")
       68│ 
       69│         if version_class is None:
       70│             from poetry.core.version.pep440.version import PEP440Version
       71│ 

The following error occurred when trying to handle this error:


  ValueError

  Could not parse version constraint: >=3.5.*

  at /usr/scratch/xar/2ce5d136/lib/python3.8/site-packages/poetry/core/semver/helpers.py:139 in parse_single_constraint
      135│ 
      136│         try:
      137│             version = Version.parse(version)
      138│         except ValueError:
    → 139│             raise ValueError(
      140│                 "Could not parse version constraint: {}".format(constraint)
      141│             )
      142│ 
      143│         if op == "<":
```

There is no mention of which package Poetry is attempting to parse the constraint for. This makes it extremely difficult to find out where the problem lies. In a project with even ten dependencies there could be hundreds of derived dependencies, and it could be any one of those which is failing.

I have attempted to increase the verbosity, but it is still rather difficult to work with. One needs to look at the dependencies that appear last in the output and then look for them in the output of `poetry show --tree` and then go looking up the `setup.py` for each of those until you find one with a constraint that matches the error.

### Proposal
I propose that Poetry add the package name and version being parsed to this error message. eg:
```
  Could not parse version constraint: >=3.5.* from foo==1.2.3 (derived from bar=1.2.3)
```

### Workaround

You can use pdb to find the package and version causing you problems, though it's non-obvious and has some issues so it's not really a workable solution for most users.
1. startup pdb with poetry (you may need to specify absolute paths to poetry here)
```
✗❯ python -m pdb poetry lock
> /usr/scratch/xar/2ce5d136/bin/poetry(3)<module>()
-> import re
```
2. set a breakpoint. We're running `poetry==1.2.0a2` and the constraint exception raises from here:
```
(Pdb) b poetry/core/semver/helpers.py:139
```
3. let poetry run. It will be slower because pdb slows runtime down
```
(Pdb) c
```
4. This is where it gets tricky. The progress output continues printing, so you need to type pdb commands through it as they will get overwritten by shell escape sequences. When you see the following, you are actually getting a pdb prompt and can enter commands:
```
(Pdb) c
Updating dependencies
Resolving dependencies... (46.1s)> /path/to/python/lib/python3.8/site-packages/poetry/core/semver/helpers.py(139)parse_single_constraint()
-> raise ValueError(
Resolving dependencies... (109.8s) 
```
5. send the pdb commands `up` and `args` a few times to walk back up the stack, until you see something like this:
```
Resolving dependencies... (137.8s)
constraint = '>=3.5.*'
Resolving dependencies... (143.0s)
> /path/to/python/lib/python3.8/site-packages/poetry/core/semver/helpers.py(35)parse_constraint()
-> constraint_objects.append(parse_single_constraint(and_constraints[0]))
Resolving dependencies... (145.4s)
constraints = '>=3.5.*'
Resolving dependencies... (147.2s)
> /path/to/python/lib/python3.8/site-packages/poetry/core/packages/package.py(253)python_versions()
-> self._python_constraint = parse_constraint(value)
Resolving dependencies... (148.3s)
self = Package('pylint', '2.6.2')
value = '>=3.5.*'
```
Voila! This is the package that triggered the constraint exception. Bump it or pin it to a version that has a valid constraint (and if it's the latest release for that package, help out the maintainer with an issue or PR to fix it up!).
7. Send the `q` pdb command twice to exit the interpreter.

**Comment by drcongo** [comment]
This issue is currently driving me round the bend...

```
~ poetry install --no-dev
Creating virtualenv ***** in /srv/www/app/.venv

Invalid PEP 440 version: '1.1build1'
```

```
~ poetry lock
The virtual environment found in /srv/www/app/.venv seems to be broken.
Recreating virtualenv opendemocracy in /srv/www/app/.venv

Invalid PEP 440 version: '1.1build1'
```

```
~ python -m pdb poetry lock
Error: poetry does not exist
```

```
~ python -m pdb /root/.local/bin/poetry lock
> /root/.local/share/pypoetry/venv/bin/poetry(3)<module>()
-> import re
(Pdb) b poetry/core/semver/helpers.py:139
*** 'poetry/core/semver/helpers.py' not found from sys.path
(Pdb) q
```

```
~ poetry --version
Poetry (version 1.2.0)
```

Using the official `install.python-poetry.org` installer on a freshly built Ubuntu 22.04 box.

**Comment by drcongo** [comment]
Actually, it's worse than that. I've just hosed the entire .venv, pyproject.toml and poetry.lock and started again so I could add packages one by one until something breaks, but I get this no matter what I try to add...

```
~ poetry add requests
Creating virtualenv opendemocracy in /srv/www/app/.venv

Invalid PEP 440 version: '1.1build1'
```

Same result for every single package I've tried.

**Comment by drcongo** [comment]
For anyone coming here by search, the workaround for the above is apparently to use `python -m venv .venv` before trying to use poetry for anything at all. 

However, I've now discovered that the latest greatest poetry install script installs poetry in a private directory accessible only to the user that installed it, instead of `/usr/local/bin` like it used to. So if you install poetry as the root user it ends up in `/root/.local/bin/poetry` and other users can't use it, and if you try to install it again for each individual user this happens...

```
curl -sSL https://install.python-poetry.org | python3 -
Retrieving Poetry metadata

# Welcome to Poetry!

This will download and install the latest version of Poetry,
a dependency and package manager for Python.

It will add the `poetry` command to Poetry's bin directory, located at:

/home/deploy/.local/bin

You can uninstall at any time by executing this script with the --uninstall option,
and these changes will be reverted.

Installing Poetry (1.2.0): An error occurred. Removing partial environment.
Traceback (most recent call last):
  File "<stdin>", line 528, in run
  File "<stdin>", line 549, in install
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "<stdin>", line 621, in make_env
  File "<stdin>", line 607, in make_env
  File "<stdin>", line 314, in make
  File "/usr/lib/python3.10/venv/__init__.py", line 75, in create
    self._setup_pip(context)
  File "/usr/lib/python3.10/venv/__init__.py", line 318, in _setup_pip
    subprocess.check_output(
  File "/usr/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/deploy/.local/share/pypoetry/venv/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 913, in <module>
  File "<stdin>", line 892, in main
  File "<stdin>", line 531, in run
AttributeError: 'str' object has no attribute 'decode'. Did you mean: 'encode'?
```

How are other system users supposed to be able to use poetry? Do I need to manually symlink the binary in `/root/.local/bin/poetry` to somewhere sensible? Why does everything need a manual hack workaround now?

**Comment by neersighted** [comment]
We test on Ubuntu 22.04 and have not run into this -- it seems like another distro packaging issue where they are leaking system `site-packages` into venvs by default... Support for distro-packaged Python is very much on a best-effort basis, as sometimes they make questionable decisions that violate assumptions made by upstream (Python.org) and consumers (us).

That's neither here nor there however -- regarding the issues you are having, the per-user install is meant for development use or simple CI pipelines where multiple users do not come into play. We are intentionally trying to minimize the magic the installer does to make it **easier** to debug/support more advanced cases.

First off, I suspect you are missing the `python3.10-venv` package (or similar) -- because these are part of the stdlib, detecting them being missing is always a challenge.

In order to install globally, a manually-managed virtual environment is the suggested tool for the job.

```
python -m venv /opt/poetry
/opt/poetry/bin/pip install poetry==1.2.0
# /opt/poetry/bin/poetry is now available
```

This is getting off-topic. If you have identified a definite bug in Poetry itself please open a new issue here, if you have identified an issue with the installer, please open an issue [there](https://github.com/python-poetry/install.python-poetry.org/issues), and if you need general support join the Discord server or start a discussion.

**Comment by drcongo** [comment]
Thanks @neersighted, sorry for dragging the issue off topic. I'd much rather keep with the official installer as I've had way more problems in the past using poetry installed via pip so I'll try some symlinking hacks or something just so that our provisioners are able to run. Is there somewhere where us end users are able to grok the design changes? None of these issues are particularly clear from the change logs or the installation docs.

**Comment by idantene** [comment]
I'm also hitting this head-on and have to resort to `source .venv/bin/activate` first. Installed with a basic `pip install poetry` on the user-level, and anything following that (e.g. `poetry install` in a repo with `poetry.lock`) fails.

**Comment by neersighted** [comment]
You haven't provided sufficient detail to understand your particular scenario, but it sounds like you may be trying to install Poetry and your project both outside a virtual environment. That is full of foot-guns and ill-advised. Use of a virtual environment is strongly suggested and protects you against all manner of surprises.

**Comment by idantene** [comment]
I'm not sure I follow. Running `poetry install` creates the virtual environment and installs the dependencies in it.

Poetry itself is installed in the user space via `pip`.

**Comment by neersighted** [comment]
You mentioned manually managing a virtual environment -- without individual steps and command, what workflow you are using/what problem you are running into is unclear.

**Comment by robtaylor** [comment]
I'm still seeing the old error message as of head today:
poetry --version
Poetry (version 1.3.0.dev0)
poetry self show

Invalid PEP 440 version: '0.23ubuntu1'

**Comment by neersighted** [comment]
You're not on a HEAD version of poetry-core.

**Comment by robtaylor** [comment]
ahah, thank you!

**Comment by robtaylor** [comment]
Ok, defintely on head python-core now, Still same behaviour. 
Looks like the try needs to move further up, as the exception is thrown on line 219:  if not isinstance(version, Version):

package = Package(
> /home/robtaylor/.local/lib/python3.9/site-packages/poetry/core/packages/package.py(81)__init__()
->
  /home/robtaylor/.local/lib/python3.9/site-packages/poetry/core/packages/package.py(219)_set_version()
-> if not isinstance(version, Version):
  /home/robtaylor/.local/lib/python3.9/site-packages/poetry/core/version/pep440/version.py(182)parse()
-> return parse_pep440(value, cls)
  /home/robtaylor/.local/lib/python3.9/site-packages/poetry/core/version/pep440/parser.py(83)parse_pep440()
-> return PEP440Parser.parse(value, version_class)
  /home/robtaylor/.local/lib/python3.9/site-packages/poetry/core/version/pep440/parser.py(69)parse()
-> raise InvalidVersion(f"Invalid PEP 440 version: '{value}'")
