### ISSUE TITLE
SolveFailure is very confusing. Please help

### ISSUE THREAD

**Issue by adnion** [python-poetry/poetry#4600]
- [x ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x ] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Issue

  SolveFailure

  The current project's Python requirement (>=3.9,<4.0) is not compatible with some of the required packages Python requirement:
    - numba requires Python >=3.7,<3.10, so it will not be satisfied for Python >=3.10,<4.0

  Because numba (0.54.0) requires Python >=3.7,<3.10
   and no versions of numba match >0.54.0,<0.55.0, numba is forbidden.
  So, because work depends on numba (^0.54.0), version solving failed.

My project has Python 3.9 and numba requires >=3.7, <3.10 which includes 3.9.
I don't get the logic. I'm very confused. How to fix?

**Comment by clintonroy** [comment]
Lets take a specific failure point. Your project allows python 3.10, which is not compatible with numba, therefore your entire
project is incompatible with numba.

Assuming that you really need numba as a dependency, reduce your project's acceptable python versions to those of numba's.

Try python = ~3.9, which will allow any version of 3.9.1 to 3.9.99, but not 3.10

Hope that helps.

**Comment by adnion** [comment]
Thank you so much. I changed it to
```
[tool.poetry.dependencies]
python = "3.9"
```
