### ISSUE TITLE
Poetry and PEP-517: build-system requirement string falsely ends up replacing dash with underscore

### ISSUE THREAD

**Issue by cybniv** [python-poetry/poetry#4601]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

Even though it's correct [in the source](https://github.com/python-poetry/poetry/blob/master/docs/pyproject.md), when reading the docs at https://python-poetry.org/docs/pyproject/, the current default configuration blob for `build_system` is displayed falsely with `poetry_core` instead of `poetry-core` as a version constraint string within the `requires` list. Illustration helps:

![Screenshot 2021-10-06 at 09 43 20](https://user-images.githubusercontent.com/5002075/136160837-2e2c4081-c5a5-468c-a021-f32c6ed2a55b.png)

compared to:
![Screenshot 2021-10-06 at 09 45 59](https://user-images.githubusercontent.com/5002075/136161234-38a6dec0-6ac2-41ec-9e74-ed566ded9e18.png)

**Comment by Secrus** [comment]
This is already corrected in master version of docs
