### ISSUE TITLE
Error due to dev-dependency despite using "poetry install --no-dev"

### ISSUE THREAD

**Issue by juliuskittler** [python-poetry/poetry#4603]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: MacOS Big Sur 11.6
- **Poetry version**: Poetry version 1.1.11
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/juliuskittler/34201e75addf9ef4fd79aef9bc663d68

## Issue

I am getting an error because of a package from my dev dependencies even though I am conducting an installation with excluding the dev dependencies (with `poetry install --no-dev`). This error is expected for `poetry install` because said dev dependency is installed from a local directory which is missing. However, I expect that it does not occur with `poetry install --no-dev` because then this dependency is not meant to be installed.

To reproduce: 

1. Download the pyproject.toml from the gist link (above), put it in a folder and navigate into the folder from your terminal.
2. Run  `poetry install --no-dev`.
3. You will get the error:

```shell
ValueError

  Directory ../Merlion/ts_datasets does not exist

  at ~/anaconda3/lib/python3.8/site-packages/poetry/core/packages/directory_dependency.py:41 in __init__
       37│         self._develop = develop
       38│         self._supports_poetry = False
       39│ 
       40│         if not self._full_path.exists():
    →  41│             raise ValueError("Directory {} does not exist".format(self._path))
       42│ 
       43│         if self._full_path.is_file():
       44│             raise ValueError("{} is a file, expected a directory".format(self._path))
```

**Comment by finswimmer** [comment]
Hello @juliuskittler,

this was ask earlier in https://github.com/python-poetry/poetry/issues/668

fin swimmer
