### ISSUE TITLE
poetry tries to locate commands in weird `$PATH` and doesn't work

### ISSUE THREAD

**Issue by astrojuanlu** [python-poetry/poetry#4611]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Linux Mint 20.2 Cinnamon
- **Poetry version**: 1.1.11
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/astrojuanlu/005d420f612117878c85173adb68d9b5

## Issue

I just installed poetry with pipx, but nothing works:

```
$ poetry run

  FileNotFoundError

  [Errno 2] No such file or directory: b'/home/juanlu/.fzf/bin/run'

  at /usr/lib/python3.8/os.py:601 in _execvpe
       597│         path_list = map(fsencode, path_list)
       598│     for dir in path_list:
       599│         fullname = path.join(dir, file)
       600│         try:
    →  601│             exec_func(fullname, *argrest)
       602│         except (FileNotFoundError, NotADirectoryError) as e:
       603│             last_exc = e
       604│         except OSError as e:
       605│             last_exc = e

```

This `~/.fzf` location belongs to https://github.com/junegunn/fzf and is at the end of my `$PATH`, so I have no clue why poetry is looking there:

```
$ which poetry
/home/juanlu/.local/bin/poetry
$ echo $PATH
/home/juanlu/.local/bin:/home/juanlu/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/juanlu/.fzf/bin
```

And it looks like verbose won't help either:

```
$ poetry run -vvv

  FileNotFoundError

  [Errno 2] No such file or directory: b'/home/juanlu/.fzf/bin/-vvv'

  at /usr/lib/python3.8/os.py:601 in _execvpe
       597│         path_list = map(fsencode, path_list)
       598│     for dir in path_list:
       599│         fullname = path.join(dir, file)
       600│         try:
    →  601│             exec_func(fullname, *argrest)
       602│         except (FileNotFoundError, NotADirectoryError) as e:
       603│             last_exc = e
       604│         except OSError as e:
       605│             last_exc = e

```

Same happens if I try any actual command:

```
$ poetry run jupyter notebook -vvv

  FileNotFoundError

  [Errno 2] No such file or directory: b'/home/juanlu/.fzf/bin/jupyter'

  at /usr/lib/python3.8/os.py:601 in _execvpe
       597│         path_list = map(fsencode, path_list)
       598│     for dir in path_list:
       599│         fullname = path.join(dir, file)
       600│         try:
    →  601│             exec_func(fullname, *argrest)
       602│         except (FileNotFoundError, NotADirectoryError) as e:
       603│             last_exc = e
       604│         except OSError as e:
       605│             last_exc = e
```

This is the output of `poetry debug`:

```
$ poetry debug

Poetry
Version: 1.1.11
Python:  3.8.10

Virtualenv
Python:         3.8.10
Implementation: CPython
Path:           /home/juanlu/.cache/pypoetry/virtualenvs/reports-9dIDX6xF-py3.8
Valid:          True

System
Platform: linux
OS:       posix
Python:   /usr
```

**Comment by Teagum** [comment]
I seems that you did not specify a command to run. Try, for example, `poetry run python3`. 

Without an argument, `poetry run` tries to execute a command named `''` (empty string), which, of course, cannot be found in `~/.local/bin`, the first entry in you `PATH`. It then iterates trough the remaining entries in `PATH` searching for `''`. The last directory happens to be `~/.fzf/bin`, where `poetry` cannot find the specified command either. So it raises an `FileNotFoundError`.

You already verified this with your second examples `poertry run -vvv` which tells `poetry` to run the non-existent command `-vvv`. You can also try anything else, like `poetry run beer23`, with the same result.

This does, however, not explain why cannot run jupyter. The only reason I can come up with right now is that you might not have jupyter installed in the venv that `poetry run` uses.

**Comment by astrojuanlu** [comment]
Thanks @Teagum , that is probably it. It was my first time using poetry and I got it all wrong. I expected more informative error messages though :)

Feel free to close this issue or keep it open.

**Comment by branchvincent** [comment]
Hi @astrojuanlu, thanks for reporting. I completely agree this is confusing and am working on a fix. We've had a lot of similar issues so I'm going to mark this as a duplicate. See more at https://github.com/python-poetry/poetry/issues/1567#issuecomment-1053210055.
