### ISSUE TITLE
False notice from setup regarding usability of poetry after install

### ISSUE THREAD

**Issue by 62f** [python-poetry/poetry#4613]
<details>

- [ y] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ z] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.
- [ i] have recently tried the product and confirmed that despite both the above caveats, the issue still exists in the latest version or in the version automatically installed by using the current init process did contain the bug(s).
## Issue

</details>'''
To get started you need Poetry's bin directory (C:\Users\R\AppData\Roaming\Python\Scr
ipts) in your `PATH`
environment variable.

Alternatively, you can call Poetry explicitly with `C:\Users\R\AppData\Roaming\Python
\Scripts\poetry`.

You can test that everything is set up by executing:

`poetry --version`

PS C:\WINDOWS\system32> poetry --version
poetry : The term 'poetry' is not recognized as the name of a cmdlet, function, 
script file, or operable program. Check the spelling of the name, or if a path was 
included, verify that the path is correct and try again.
At line:1 char:1
+ poetry --version
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (poetry:String) [], CommandNotFoundExc 
   eption
    + FullyQualifiedErrorId : CommandNotFoundException
 

PS C:\WINDOWS\system32> echo $path

PS C:\WINDOWS\system32> echo $PATH

PS C:\WINDOWS\system32> C:\Users\R\AppData\Roaming\Python
\Scripts\poetry --version
C:\Users\R\AppData\Roaming\Python : The term 'C:\Users\R\AppData\Roaming\Python' is 
not recognized as the name of a cmdlet, function, script file, or operable program. 
Check the spelling of the name, or if a path was included, verify that the path is 
correct and try again.
At line:1 char:1
+ C:\Users\R\AppData\Roaming\Python
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\R\AppData\Roaming\Python:Str 
   ing) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
\Scripts\poetry : The term '\Scripts\poetry' is not recognized as the name of a 
cmdlet, function, script file, or operable program. Check the spelling of the name, 
or if a path was included, verify that the path is correct and try again.
At line:2 char:1
+ \Scripts\poetry --version
+ ~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (\Scripts\poetry:String) [], CommandNo 
   tFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
'''

**Comment by finswimmer** [comment]
Hello @62f,

you haven't come back to this issue for a long while. So I assume this is solved in the meantime and I can close this ticket.

Feel free to leave a comment if you disagree.

fin swimmer
