### ISSUE TITLE
better support for using poetry-managed scripts in crontabs

### ISSUE THREAD

**Issue by cjw296** [python-poetry/poetry#462]
As requested on Discord...

@sdispater 's current answer was: Well, since Poetry needs to be run inside the directory of the project, you would have to create a shell script that cd into the project's directory then execute poetry install and finally poetry run my-script.

I hope that install step would only need to be done once? I'm wondering if using `cd /abs/to/folder-containing-pyprojects.toml/ && /abs/to/poetry run my_command and --its options` would currently work?

Anyway, this feature request is to support this with something nice, the idea I suggested was:

`/abs/to/poetry -p /abs/to/folder-containing-pyprojects.toml/ run my_command and --its options`

Maybe `-p` could even be `--cd`. I'm happy to work on a PR for this as soon as it's confirmed that it would likely be merged...

**Comment by cjw296** [comment]
My workaround is to directly use the entrypoints installed in the poetry-managed virtualenv, but this is definitely not stale.

**Comment by danielloader** [comment]
Anyone got any ideas on this? I'd hate to have to use pipenv for cron scheduled scripts.

**Comment by Apreche** [comment]
The stale bot already marked this as stale once. It's been about 7 months since the last post. This issue keeps coming up for me, and there hasn't been any activity on it.

**Comment by finswimmer** [comment]
Hello,

similar discussion is going on in https://github.com/python-poetry/poetry/issues/2179. So I will close this one here.

fin swimmer
