### ISSUE TITLE
Poetry uninstalls all dependencies when removing any dependency via `poetry remove`

### ISSUE THREAD

**Issue by provinzkraut** [python-poetry/poetry#4632]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 20.04.3
- **Poetry version**: 1.2.0a2
- **Python version**: 3.10.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/provinzkraut/b0522eae0003f71c9767ca7a2ce93ee0

## Issue

When removing a dependency via `poetry remove`, poetry will uninstall every dependency in the `pyproject.toml`. It will however not remove them from `pyproject.toml`. This behavior exists for packages without any interdependence whatsoever.

Output of running `poetry remove tqdm -vvv` on the provided `pyproject.toml`:

```
Loading configuration file ~/.config/pypoetry/config.toml
Using virtualenv: ~/.cache/pypoetry/virtualenvs/poetry-test-y2U66Zct-py3.10
Updating dependencies
Resolving dependencies...
   1: fact: poetry-test is 0.1.0
   1: derived: poetry-test
   1: selecting poetry-test (0.1.0)
   1: Version solving took 0.003 seconds.
   1: Tried 1 solutions.

Writing lock file

Finding the necessary packages for the current system

Package operations: 0 installs, 0 updates, 2 removals

  • Removing dnspython (2.1.0): Pending...
  • Removing dnspython (2.1.0): Removing...
  • Removing dnspython (2.1.0)
  • Removing tqdm (4.62.3): Pending...
  • Removing tqdm (4.62.3): Removing...
  • Removing tqdm (4.62.3)
```

A subsequent `poetry update` will re-install all previously unnecessarily removed packages.

**Comment by nikokaoja** [comment]
This is still an issue in `Poetry (version 1.2.0a2)` , when removing a specific package all packages are removed.

**Comment by thomasjo** [comment]
> This is still an issue in `Poetry (version 1.2.0a2)` , when removing a specific package all packages are removed.

@nikokaoja You need to install [Poetry 1.2.0b1](https://pypi.org/project/poetry/1.2.0b1/). Only the latest (beta) release has the required poetry-core dependency that contains the bug fix.

_For reference: [poetry-core 1.1.7a1](https://pypi.org/project/poetry-core/1.1.0a7/) (and newer) contains the [relevant fix](https://github.com/python-poetry/poetry-core/pull/220)._
