### ISSUE TITLE
Installation fails due to missing gcc-5

### ISSUE THREAD

**Issue by albireox** [python-poetry/poetry#4638]
- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 20.04
- **Poetry version**: 1.1.11
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/albireox/6bc9d3a01dee12897507937890fea0d4

## Issue

I'm seeing a weird problem. I have a package (`sdss-kaiju`) that compiles a C++ extension during build. When I try to install it directly with pip everything works fine (I'm pointing to a branch since this code is not yet tagged)

```
pip install sdss-kaiju@git+ssh://git@github.com/csayres/kaiju@albireox/kaiju-vs-jaeger
```

However when I try to install it from a poetry-managed package with

```
sdss-kaiju = { git = "https://github.com/csayres/kaiju", branch = "albireox/kaiju-vs-jaeger", optional = true }
```

the installation fails because it's trying to compile the code using `gcc-5`. `gcc-5` is not present in my system, nor is hardcoded anywhere in the code, nor I have any environment variables that could be pointing to it.

```
    gcc-5 -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -O3 -Wall -fPIC -Icextern/sofa -I/home/linuxbrew/.linuxbrew/include -I/home/linuxbrew/.linuxbrew/opt/openssl@1.1/include -I/home/linuxbrew/.linuxbrew/opt/sqlite/include -I/tmp/tmp8s0mnec9/.venv/include -I/home/linuxbrew/.linuxbrew/opt/python@3.9/include/python3.9 -c cextern/sofa/a2af.c -o build/temp.linux-x86_64-3.9/cextern/sofa/a2af.o -c -pedantic -Wall -W -O
    error: command 'gcc-5' failed: No such file or directory
    ----------------------------------------
    ERROR: Failed building wheel for sdss-coordio
  ERROR: Failed to build one or more wheels
  found packages ['kaiju']
  Traceback (most recent call last):
    File "/tmp/tmp8s0mnec9/.venv/lib/python3.9/site-packages/setuptools/installer.py", line 75, in fetch_build_egg
      subprocess.check_call(cmd)
    File "/home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/subprocess.py", line 373, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['/tmp/tmp8s0mnec9/.venv/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpj79jk3h9', '--quiet', 'git+ssh://git@github.com/sdss/coordio.git@albireox/jaeger-integration']' returned non-zero exit status 1.
```

This happens whether the package is optional or not. Any ideas what may be going on here?

**Comment by finswimmer** [comment]
Thanks for sharing your solution :+1:
