### ISSUE TITLE
Unabe to add `opentelemetry-exporter-otlp-proto-grpc` dependency

### ISSUE THREAD

**Issue by owais** [python-poetry/poetry#4640]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS 11.6
- **Poetry version**: 1.1.11 (also tried with 1.8 and 1.2a1)
- **Link of a [Gist](hhttps://gist.github.com/owais/c0da8e89e3a39b59d645f425823d3dd7) with the contents of your pyproject.toml file**: https://gist.github.com/owais/c0da8e89e3a39b59d645f425823d3dd7

## Issue

I'm unable to add or update `opentelemetry-exporter-otlp-proto-grpc` package. People freezes when trying to update it from 1.5 to 1.6 on an existing project or adding it to a new project.

The freezes forever on a new project:
`poetry add opentelemetry-exporter-otlp-proto-grpc -vvv` 

An existing project that uses v1.5 of the package is unable to update it to v1.6 as it also freezes indefinitely. Even if I change version from 1.5 to 1.6 manually, `poetry update` and `poetry lock` still freeze indefinitely.

### Steps to reproduce:

- use the pyproject file linked above and add the package with `poetry add` command.
- or try to update github.com/signalfx/splunk-otel-python to opentelemetry-exporter-otlp-proto-grpc 1.6

**Comment by ryaminal** [comment]
have you tried poetry 1.2.0a2? i ask because i'm able to add and update the package on 1.2.0a2.

**Comment by owais** [comment]
I am pretty sure I did but I can try again if it helps identify the issue

**Comment by mkniewallner** [comment]
Closing this, since this doesn't seem actionable.
