### ISSUE TITLE
poetry not installing dependencies from install_requires

### ISSUE THREAD

**Issue by BeyondEvil** [python-poetry/poetry#4648]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: osx 10.15.7
- **Poetry version**: 1.1.11
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://github.com/pytest-dev/pytest-selenium/pull/278

## Issue
I expect `poetry install` to install my projects dependencies, as outlined by `install_requires` in `setup.cfg`.

It didn't work when it was defined in `setup.py` either.

**Comment by clintonroy** [comment]
Poetry only looks in pyproject.toml for dependencies.
