### ISSUE TITLE
Poetry does not distinguish between dev and alpha versions

### ISSUE THREAD

**Issue by konradkalita** [python-poetry/poetry#4653]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: MacOS BigSur
- **Poetry version**: 1.1.11

## Issue
Hi, I have a private repository in which I have a library in both dev and alpha versions like this:
```
0.1.0.dev0/		
0.1.0.dev1/		
0.1.0.dev2/		
0.1.0.dev3/	
0.1.0a1/	
0.1.0a2/	
0.1.0a3/
```
Although I specify a `0.1.0a3` version (`poetry add lib=='0.1.0a3'`) poetry always install  a`0.1.0.dev3` version although the `0.1.0a3` is newer. Also in pyproject.toml poetry writes that the package is in a version `0.1.0a3` although in lock.file there is a version which is actually installed `0.1.0.dev3`. When I install package with pip it works correctly.

**Comment by finswimmer** [comment]
@kjaquier: I'm able to reproduce it with poetry 1.1.11 but not with the preview release 1.2.0a2. Could you please test it as well?

@konradkalita: Maybe your case is also solved by 1.20a2. So please give it a try.
