### ISSUE TITLE
When moving a project, the hard-coded absolute interpreter path in bins break

### ISSUE THREAD

**Issue by vjpr** [python-poetry/poetry#4654]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS
- **Poetry version**: 1.1.11
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue

When using an in-project venv:

__.venv/bin/black__

```
#!/my/projects/project/.venv/bin/python
# -*- coding: utf-8 -*-
import re
import sys
from black import patched_main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(patched_main())

```

This breaks when relocating a project.

Not sure best approach but some suggestions here: [shebang: use interpreter relative to the script path](https://stackoverflow.com/questions/20095351/shebang-use-interpreter-relative-to-the-script-path)

Maybe some kind of wrapper is needed, but this would be ugly.

Maybe an option to allow specifying a custom interpreter script to use.

**Comment by finswimmer** [comment]
Pythons virtual environments are not meant for relocation. They make heavy use of symlink that break quite easily. Also the given example is not produced by Poetry. That's why I close this issue.
