### ISSUE TITLE
RFC: Community-run server that can accelerate `poetry update` by pre-computing dependency resolutions 

### ISSUE THREAD

**Issue by creatorrr** [python-poetry/poetry#4680]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

Love poetry and use it every day but as my project is growing, `poetry update` is starting to take painstakingly long to run sometimes in excess of 300-400 seconds (depending on how PyPI is doing). This is much worse when starting from scratch without a `poetry.lock` file and `~/.cache/pypoetry/`. 

Please humor me for a second here but would it somehow be feasible to have a community-run server that can accelerate `poetry update`s by pre-computing dependency resolutions for let's say the top 5000 projects on pypi?

**Comment by Secrus** [comment]
While the idea is nice, it's impossible to implement without an extra team of maintainers for such a server, devs to implement it, and a funding source to pay for the infrastructure.

**Comment by creatorrr** [comment]
yeah that makes sense @Secrus but fwiw, I could help find sponsors for something like this
