### ISSUE TITLE
Poetry keeps updating the same packages on poetry install

### ISSUE THREAD

**Issue by Zethson** [python-poetry/poetry#4687]
- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Arch Linux
- **Poetry version**: 1.1.11
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/Zethson/db62c32e6113279d23d52b5c6d248c04

## Issue

Every time I run poetry install the same packages get updated.

```
⋊> ~/P/ehrapy on development ⨯ poetry install                                                                                                                                (ehrapy) 12:00:59
Installing dependencies from lock file

Package operations: 0 installs, 5 updates, 0 removals

  • Updating idna (3.2 -> 3.3)
  • Updating pyrsistent (0.17.3 -> 0.18.0)
  • Updating charset-normalizer (2.0.0 -> 2.0.7)
  • Updating pyparsing (2.4.7 -> 3.0.3)
  • Updating pyzmq (22.2.1 -> 22.3.0)

Installing the current project: ehrapy (0.1.0)
⋊> ~/P/ehrapy on development ⨯ poetry install                                                                                                                                (ehrapy) 12:01:08
Installing dependencies from lock file

Package operations: 0 installs, 5 updates, 0 removals

  • Updating idna (3.2 -> 3.3)
  • Updating pyrsistent (0.17.3 -> 0.18.0)
  • Updating charset-normalizer (2.0.0 -> 2.0.7)
  • Updating pyparsing (2.4.7 -> 3.0.3)
  • Updating pyzmq (22.2.1 -> 22.3.0)

Installing the current project: ehrapy (0.1.0)
```

**Comment by MatthieuBizien** [comment]
Same problem here, for packages installed with git+ssh.

**Comment by fmr** [comment]
I'm also getting this, even though everything's being installed from pypi sources

**Comment by neersighted** [comment]
Not enough details here to reproduce -- if you're turning off virtualenv creation and on Debian/Ubuntu, it likely is #4358.
