### ISSUE TITLE
When installing ,`email.utils` is not a package

### ISSUE THREAD

**Issue by transcental** [python-poetry/poetry#4690]
- [N/A] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [N/A] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS Catalina 10.15.7
- **Poetry version**: *Not applicable*
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: *Not applicable*

## Issue

When I try to install Poetry, I get an error(*below*):

```zsh
dillonbarnes@Downstairs-iMac ~ % curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python - 

Traceback (most recent call last):
  File "<stdin>", line 32, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 86, in <module>
    import email
  File "/Users/dillonbarnes/email.py", line 1, in <module>
    import smtplib
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/smtplib.py", line 47, in <module>
    import email.utils
ModuleNotFoundError: No module named 'email.utils'; 'email' is not a package
dillonbarnes@Downstairs-iMac ~ % 
```

With a knowledge of Python packages, this confused me because `email` is a built-in Python package.

Am I doing something wrong here?

**Comment by shivv-001** [comment]
did it work?
