### ISSUE TITLE
Setting credentials fails when password starts with a hyphen

### ISSUE THREAD

**Issue by twoolie** [python-poetry/poetry#4699]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: NixOS 21.05
- **Poetry version**: 1.1.11

## Issue

When setting repository credentials with `poetry config http-basic.custom-repo gitlab-ci-token ${GITLAB_JOB_TOKEN}` the command will fail any time the GITLAB_JOB_TOKEN begins with a hyphen. The command line parser tries to treat the password as an option.

The current workaround is to use double hyphen e.g.  `poetry config http-basic.custom-repo -- gitlab-ci-token ${GITLAB_JOB_TOKEN}`

This should either be fixed in the option parser, or the workaround documented in the manual.

**Comment by paketb0te** [comment]
We ran into the same issue due to the `${GITLAB_JOB_TOKEN}` (which is generated by GitLab dynamically) sometimes starting with a dash - and thus, poetry interpreting the next character as an option, which it then obviously can't find.

**Comment by dimbleby** [comment]
this is just regular behaviour for command line programs.  eg try to `grep` for a string that begins with a  hyphen: it'll try to interpret it as an option.

See also #4853.

Nothing to do here.

**Comment by neersighted** [comment]
Agreed, this is standard behavior of CLI applications, and there is no need for a workaround as the proper solution (`--` to terminate options parsing in the Unix tradition) is available. I'm leaving this open as this seems like an excellent FAQ candidate.

**Comment by clintonroy** [comment]
we could modify the input maybe, poetry config key==--value would get around it.

**Comment by neersighted** [comment]
I'm personally not enthused about adding some custom tokenization/splitting when what we have works fine and is stable, especially as certain usernames with whatever token we choose would become impossible to express.

**Comment by twoolie** [comment]
@paketb0te the workaround works well. I feel that it's a good enough solution. I think that it should be documented and that the examples in the docs should always use `--` so that people don't get caught out when try to do this in their CI scripts. Admittedly this is less critical for me personally since gitlab started prefixing their tokens.

**Comment by paketb0te** [comment]
@twoolie yeah it works great, I just was not aware that this exists (using double hyphen to stop parsing options) :smile: 

I agree there is nothing to fix here, except maybe adding a hint in the docs / FAQ.
