### ISSUE TITLE
install-poetry.py doesn't save POETRY_HOME

### ISSUE THREAD

**Issue by QuentinSoubeyran** [python-poetry/poetry#4707]
- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 20.04
- **Poetry version**: `1.11.0`
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: Not applicable

## Issue

Not sure if this is an actual bug or a documentation issue, feel free to change accordingly.

When using `POETRY_HOME` to install poetry in a non-default location, [as documented in the doc](https://python-poetry.org/docs/master/#osx--linux--bashonwindows-install-instructions) (i.e. with the environment variable defined at the command invocation), poetry does not save this location. Subsequent `poetry self update` report that `Poetry was not installed with the recommended installer. Cannot update automatically.`.

This is linked to #1872 and #2081. Those issue were fixed, and providing `POETRY_HOME` again for `poetry self update` works. However, the documentation [does not mention](https://python-poetry.org/docs/master/#updating-poetry) that the environment variable should be provided again for the update, and it is not ideal to have to type it each time (and remembering that this is the problem). The documentation also doesn't advise defining `POETRY_HOME` in `.bashrc` or similar files, which could be a solution.

To reproduce:

```bash
$ POETRY_HOME=~/bin/poetry python install-poetry.py
$ poetry --version
Poetry version 1.1.11

$ poetry self update --preview

  RuntimeError

  Poetry was not installed with the recommended installer. Cannot update automatically.

  at bin/poetry/venv/lib/python3.8/site-packages/poetry/console/commands/self/update.py:389 in _check_recommended_installation
      385│         current = Path(__file__)
      386│         try:
      387│             current.relative_to(self.home)
      388│         except ValueError:
    → 389│             raise RuntimeError(
      390│                 "Poetry was not installed with the recommended installer. "
      391│                 "Cannot update automatically."
      392│             )
      393│ 
```

**Comment by neersighted** [comment]
I think I'm going to go ahead and close this -- generally, providing an environmental variable is an exercise left to the user. Depending on the setup and preferences of the user it could come from a shell startup file, a terminal emulator config, something like Nix, or even the kernel command line. Overall however, it's reasonable to expect the user to know to provide the variable consistently if the user is sophisticated enough to overload the install directory.

Pull requests adding some examples to the docs are welcome!
