### ISSUE TITLE
Unable to update package PyInstaller due to Python version constraint 

### ISSUE THREAD

**Issue by armingerten** [python-poetry/poetry#4708]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Mac OS 12.0.1
- **Poetry version**: `1.11.1`
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/armingerten/08760ee996d30e02fda9e29d46412111

## Issue

The [most recent PyInstaller version (4.6)](https://pypi.org/project/pyinstaller/4.6/) has introduced a version range for Python `<3.11, >=3.6`. 

Poetry is instructed to use Python 3.9 for the project:

```ini
[tool.poetry.dependencies]
python = "^3.9"
pyinstaller = "^4.0.0"
```

Now I'd like to run `poetry update pyinstaller` to update to the most recent version.

### Expected behavior

Poetry updates the package `pyinstaller` to version `4.6`

### Actual behavior 

Poetry does not consider pyinstaller's Python requirements to be in range:

```sh
   1: fact: pyinstaller (4.6) requires Python <3.11,>=3.6
   1: derived: not pyinstaller (==4.6)
   1: fact: pyinstaller (4.5.1) depends on altgraph (*)
   1: fact: pyinstaller (4.5.1) depends on pyinstaller-hooks-contrib (>=2020.6)
   1: fact: pyinstaller (4.5.1) depends on macholib (>=1.8)
   1: fact: pyinstaller (4.5.1) depends on pefile (>=2017.8.1)
   1: fact: pyinstaller (4.5.1) depends on pywin32-ctypes (>=0.2.0)
   1: selecting pyinstaller (4.5.1)
```

This might be related to https://github.com/python-poetry/poetry/issues/1413 .

**Comment by armingerten** [comment]
Okay https://github.com/python-poetry/poetry/issues/1413 seems to point towards the correct solution... Either my project must adopt the same upper boundary 
```ini
[tool.poetry.dependencies]
python = ">=3.9,<3.11"
pyinstaller = "^4.0.0"
```
or use `~` instead:
```ini
[tool.poetry.dependencies]
python = "~3.9"
pyinstaller = "^4.0.0"
```
/close

**Comment by tewfik-ghariani** [comment]
This is caused by https://github.com/pyinstaller/pyinstaller/pull/6322
