### ISSUE TITLE
Local path in wheel metadata seems wrong

### ISSUE THREAD

**Issue by Hartorn** [python-poetry/poetry#4709]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Docker container Ubuntu 18.04
- **Poetry version**: 1.1.11
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue

We have a pyproject.toml with deps towards local non-poetry python project, declared in subfolder.
```
local_package = {path = "./subfolder/local_package", develop = true}
```
Everything is working fine (install, lockfile, and so on), except when creating a package. 
I built the wheel using `poetry build`, and when trying to install the package with pip afterwards, I got an error
```
  File "/poetry_cache/virtualenvs/hawk-AVX97199-py3.6/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3103, in __init__
    raise RequirementParseError(str(e))
pip._vendor.pkg_resources.RequirementParseError: Invalid URL: subfolder/local_package
```

I tried the `poetry export` function (worked fine), and noticed the local deps are written as `vaedataset @ file:///full/path/to/subfolder/local_package`

I checked the inside of the wheel and it's written in the metadata `Requires-Dist: local_package @ subfolder/local_package`
I think the error comes from here, shouldn't it be something similar, like an URI `file://./subfolder/local_package` or something like this ?

**Comment by Hartorn** [comment]
Additional info : 
I made some tests, seems like it's not supported to have relative URI inside wheel, so `file://./foo/bar` is a no-go 
`ValueError: non-local file URIs are not supported on this platform: 'file://./foo/bar'`.

Finally, URI should be the same as in poetry export, full path : `file:///path/to/foo/bar`
With full path, the wheel is working

**Comment by jsirois** [comment]
This is a definitive bug via:
1. https://www.python.org/dev/peps/pep-0345/#version-specifiers ->
2. https://www.python.org/dev/peps/pep-0440/#file-urls

In fact, if attempting to publish wheels to PyPI for others to use, the file:// url presented in `poetry export` wouldn't work either. For `publish` the requirement must be switched to be the project==version of that local project.

**Comment by dimbleby** [comment]
duplicate #5273

(Per https://github.com/python-poetry/poetry/issues/5273#issuecomment-1272571033 it should be an easy fix to use an absolute path.  Though I still don't understand the use case for a wheel that points at a local path, it's not as though you can distribute that wheel and expect anyone else to be able install it)

**Comment by jsirois** [comment]
@dimbleby you absolutely can in a corporate environment with consistent network mounts via, say, NFS. So no PyPI involved here and folks can assume the mount.

**Comment by dimbleby** [comment]
pull request is invited
