### ISSUE TITLE
poetry got error at installing localstack 

### ISSUE THREAD

**Issue by RaphaelSilva** [python-poetry/poetry#4713]
- **OS version and name**: macOS Big Sur
- **Poetry version**: 1.1.11

When I trying to run the add command, I've been getting some errors!

```shell
poetry add localstack -D
```
Using version ^0.12.19 for localstack

Updating dependencies
Resolving dependencies... (9.0s)

  PackageInfoError

  Unable to determine package info for path: /var/folders/78/w9b7jv812111g633_gxg9rkcx3j5cy/T/pypoetry-git-pyminifierreytrdhj
  
  Fallback egg_info generation failed.
  
  Command ['/var/folders/78/w9b7jv812111g633_gxg9rkcx3j5cy/T/tmp06v0yqjj/.venv/bin/python', 'setup.py', 'egg_info'] errored with the following return code 1, and output: 
  error in pyminifier setup command: use_2to3 is invalid.

  at /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/poetry/inspection/info.py:500 in _pep517_metadata
      496│                 try:
      497│                     venv.run_python("setup.py", "egg_info")
      498│                     return cls.from_metadata(path)
      499│                 except EnvCommandError as fbe:
    → 500│                     raise PackageInfoError(
      501│                         path, "Fallback egg_info generation failed.", fbe
      502│                     )
      503│                 finally:
      504│                     os.chdir(cwd.as_posix())
## Issue
![image](https://user-images.githubusercontent.com/1675717/140518327-bf37967b-c8fe-457a-94f9-24304d911c0a.png)

**Comment by davclark** [comment]
I'm experiencing a similar error. `poetry update -vv` doesn't show pyminifier at all, so I'm confused about where this dependency is coming from.
