### ISSUE TITLE
Bump Packaging library to major version 21

### ISSUE THREAD

**Issue by virenshub** [python-poetry/poetry#4714]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

### Bump [Packaging](https://github.com/python-poetry/poetry/blob/master/pyproject.toml#L46) library to major version 21

**Why?**
I ran into "No module named 'distutils.util'" while configuring Poetry to pull private packages. My environment is: _Poetry 1.1.6 on a debian:buster docker image with python 3.8.10_. From my quick research, it seems like distutils is not included in the newer versions of debian. Poetry uses ^20.4 version of the Packaging library, which uses Distutils for tagging. Distutils has been replaced with sysconfig in Packaging version 21.0 ( [issue 396](https://github.com/pypa/packaging/pull/396)).

As distutils is being deprecated with python 3.12 ([PEP 632](https://www.python.org/dev/peps/pep-0632/)), I think the Packaging library should be bumped to major version 21.

**Workaround:**
For now, I am installing distutils explicitly on my debian image
`apt-get install python3-distutils`

**Comment by finswimmer** [comment]
Done in https://github.com/python-poetry/poetry/pull/4749
