### ISSUE TITLE
Documentation on main website installs version 1.11.1, which then can't be uninstalled

### ISSUE THREAD

**Issue by Grimmstar** [python-poetry/poetry#4724]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

If you're following the installation instructions on https://python-poetry.org/docs/, the version that gets installed is not the latest version (it installs 1.11.1), which if you then turn around and try to uninstall using the instructions on the same page, it fails.

I did work out how to uninstall it on my own, but for a newer user, this might be a pretty frustrating situation.

![poetry-issue-1](https://user-images.githubusercontent.com/25069268/140857342-09fd877b-e99b-4d17-87cf-4f40bd7a58c8.png)
![poetry-issue-2](https://user-images.githubusercontent.com/25069268/140857346-99de27cf-3668-42ab-a0fb-a9cc58164b44.png)

**Comment by jaklan** [comment]
@Grimmstar `1.1.11` **IS** the latest version. You try to use the uninstall option on the file which doesn't exists, so obviously it doesn't work. 

First - download the file with `curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py`, then run the command...
