### ISSUE TITLE
poetry issue

### ISSUE THREAD

**Issue by monaSalih** [python-poetry/poetry#4725]
i try to install discord using ``` poetry add discord ``` but didnt work show this error msg 
```
static_login
    raise LoginFailure('Improper token has been passed.') from exc
discord.errors.LoginFailure: Improper token has been passed.
```

**Comment by clintonroy** [comment]
I did not get that error when doing a test install of discord. Is that actually an error when trying to use the library? If so, that's not a problem poetry can do anything about.

**Comment by monaSalih** [comment]
this error show when i try to run the code 🤦‍♀️ but any way thank you

**Comment by jaklan** [comment]
@monaSalih so please close the issue, because that's the reason why we have over 1000 open issues in the repo and maintainers are not able to pick up the actual problems with `poetry` from among all these completely unrelated issues.
