### ISSUE TITLE
Multiple entry points

### ISSUE THREAD

**Issue by seekingThat** [python-poetry/poetry#4727]
- [ ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

Is it possible to provide multiple entry points without any optional packages and one with mainstream package ? Apologies for my ignorance if such a thing exists

**Comment by clintonroy** [comment]
Yup, you can point to multiple functions in a package to get multiple entry points.

Did you try this and something didn't work?

**Comment by seekingThat** [comment]
Thanks clinton  .. yeah looks like the entrypoints defined like these works with the run command .. but it crashes and I need to debug that ..

[tool.poetry.scripts]  # for normal user actions
asyncapi-subscriber = "asyncapi:run_subscriber"
asyncapi-docs = "asyncapi:run_docs"

**Comment by seekingThat** [comment]
closing this issue as the functionality was verified
