### ISSUE TITLE
Invalid URI scheme: mongodb+srv

### ISSUE THREAD

**Issue by mohammedtibas** [python-poetry/poetry#4730]
I am trying to connect my python application. Every time I am getting Invalid URI scheme: mongodb+srv. I upgraded my dnspython (v2.1.0) and pymongo (v3.12.1) and tried all the solutions recommended but I still have this error

```
repository.py", line 157, in __enter__
    self._client = MongoClient(f"mongodb+srv://{username}:{password}@{database}")
```
`pymongo.errors.ConfigurationError: Invalid URI host: none is not a valid hostname for 'mongodb+srv://'. Did you mean to use 'mongodb://'?`

**Comment by neersighted** [comment]
Hi, thanks for opening an issue! I am reasonably certain that the bug/problem you're facing is not in Poetry, but in the PyPI modules you are using.

If you think this is related to Poetry, please re-open this issue with steps to reproduce the bug. Thanks!
