### ISSUE TITLE
ConnectionError when installing dependencies

### ISSUE THREAD

**Issue by cposada23** [python-poetry/poetry#4731]
- Operating system: Windows and Mac
- Poetry version 1.1.10, 1.1.11 and preview
- 

- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Issue

When I run poetry install or poetry add y get the following error: 

`poetry-example % : poetry install
Creating virtualenv poetry-example-brjVAFjw-py3.8 in /Users/camiloposada/Library/Caches/pypoetry/virtualenvs
Updating dependencies
Resolving dependencies... (23.7s)

  ConnectionError

  ('Connection aborted.', TimeoutError(60, 'Operation timed out'))

  at ~/.pyenv/versions/3.8.6/lib/python3.8/site-packages/requests/adapters.py:498 in send
      494│                     low_conn.close()
      495│                     raise
      496│ 
      497│         except (ProtocolError, socket.error) as err:
    → 498│             raise ConnectionError(err, request=request)
      499│ 
      500│         except MaxRetryError as e:
      501│             if isinstance(e.reason, ConnectTimeoutError):
      502│                 # TODO: Remove this in 3.0.0: see #2811`

I have tried on different computers, one using Windows 10 and the other is a MacBook pro. I have not been able to install any dependencies nor initialize a new project, so I've been thinking of coming back to pipenv (which works totally fine). Can anybody provide some insight on why this is happening ?  Thanks a lot

**Comment by liju-bidaya** [comment]
- I do have the same issue when when I try adding packages 
- I am using using poetry 1.1.12 on windows 11
- retrying the same command *poetry add <package>* eventually help me to install the same package
- pip install works fins on the same
- 
![image](https://user-images.githubusercontent.com/87894321/149796866-89b79a25-70b2-4966-9222-432f449f6500.png)
- this happens every time I install any packages from remote

**Comment by neersighted** [comment]
This is a local/transient network issue -- there's nothing Poetry can do here, as we just use `requests` to send HTTP requests like everyone else.
