### ISSUE TITLE
poetry change project name to lowercase

### ISSUE THREAD

**Issue by vtexier** [python-poetry/poetry#4734]
- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu Mate 18.04 
- **Poetry version**: 1.1.11
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/vtexier/9abdded5d0910f79c60c05ec0fe7d0a7

## Issue

I use CAPITAL letters in the project name: MADAM-MAM

When poetry build and publish the project, name is fine and untouched in the logs:

```bash
> poetry publish --build --repository test-pypi

Building MADAM-MAM (0.5.8)
  - Building sdist
  - Built MADAM-MAM-0.5.8.tar.gz
  - Building wheel
  - Built MADAM_MAM-0.5.8-py3-none-any.whl

Username: vtexier
Password: 
Publishing MADAM-MAM (0.5.8) to test-pypi
 - Uploading MADAM-MAM-0.5.8.tar.gz 100%
 - Uploading MADAM_MAM-0.5.8-py3-none-any.whl 100%
```

But on the PyPI repository, the name is lower case!

See https://test.pypi.org/project/madam-mam/

I know it is possible to have CAPITAL letters for a project, as this other project:

See https://test.pypi.org/project/MADAM/

The command `poetry version` has the same bug with lowercase output:

```bash
> poetry version 
madam-mam 0.5.8
```

**Comment by pimoens** [comment]
This is something that has been annoying me too, project names based on abbreviations can be difficult to read when everything is converted to lowercase.

**Comment by neersighted** [comment]
Duplicate #1202
