### ISSUE TITLE
add "--without-index-url" option to poetry export

### ISSUE THREAD

**Issue by jrobbins-LiveData** [python-poetry/poetry#4741]
- [ x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

I am working with a private PyPi repository (AWS CodeArtifact).  I need access to my locked dependencies inside a docker build.  While there is more than one way to accomplish this, the simplest way for me is to run `poetry export -f requirements.txt ...` and use the following code in the Dockerfile:

```
COPY requirements.txt .
RUN pip install --index-url ${CODEARTIFACT_URL} -t . -r requirements.txt
RUN rm requirements.txt
```

But `poetry export` is adding this line to the top of my `requirements.txt` file, breaking my docker build:

```
--index-url https://[REDACTED DOMAIN]-[REDACTED ACCOUNT].d.codeartifact.us-east-2.amazonaws.com/pypi/[REDACTED REPO]/simple
```

Adding an option to suppress adding this `--index-url` would let me capture the locked dependencies and take care of the private CodeArtifact PyPi repo myself.

**Comment by DustinMoriarty** [comment]
I also found it a little odd for poetry to add the index URL's to the requirements file. I would be happy to look at making a PR for this.
