### ISSUE TITLE
Python2 compat in poetry-core

### ISSUE THREAD

**Issue by danieleades** [python-poetry/poetry#4746]
There's a massive amount of python2 compatibility code in the `poetry-core` repo. Is there a technical reason that's still required, or can it be stripped out?

**Comment by abn** [comment]
It can be stripped out. But might want to check if any of the compat code is used downstream in poetry first. 

https://github.com/python-poetry/poetry-core/blob/master/pyproject.toml#L36

**Comment by danieleades** [comment]
> But might want to check if any of the compat code is used downstream in poetry first.

how could poetry make use of the compat code downstream? it only supports python 3.6+, right?

there's a pull request here - https://github.com/python-poetry/poetry-core/pull/230

but there's a *lot* more unneeded python2 compat code in the vendored code which is not needed. I'm not sure how those packages are managed, but I suspect updating them would eliminate a lot of the compat code

**Comment by neersighted** [comment]
I'm currently working on this in `poetry` itself but have not started in core. I'd suggest a `pyupgrade` pass for syntax and then manual removal of Python 2-related constructions/workarounds.

I think @abn is referring to any hypothetical compatibility layers used downstream in Poetry (e.g. a compatibility wrapper or re-implementation of stdlib functionality). I think those should be rare, but it reminds me that a good long term goal would be running the `poetry` test suite against new `poetry-core` PRs to test any downstream consequences like that.

**Comment by abn** [comment]
We already run the downstream suite :) so yeah firing up a draft pr is probably the best way to know.

**Comment by neersighted** [comment]
> 
> 
> We already run the downstream suite :) so yeah firing up a draft pr is probably the best way to know.

I just noticed that as you replied! Neat!

**Comment by danieleades** [comment]
Cool beans. I've not touched the vendored code, I have given it a once over with pyupgrade. I've not added a pyupgrade hook. Any reason not to?
