### ISSUE TITLE
Assertion Error when running `poetry install`

### ISSUE THREAD

**Issue by DillonB07** [python-poetry/poetry#4756]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS Catalina 10.15.7
- **Poetry version**: 1.1.11
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/DillonB07/327e3fa548134c97f1afad2c3bca226f - Also contains error log

## Issue

`poetry install` kept giving me an Assertion Error. For more details visit the gist.

I tried remaking and installing all of my dependencies via `poetry init`. I should also mention that `poetry init` occasionally gave me an Assertion Error as well when defining dependencies.

**Comment by dimbleby** [comment]
poetry now fails with the much more helpful error:

```
  Package 'dill-tils' is listed as a dependency of itself.
```

which should tell you what the problem is.

**Comment by DillonB07** [comment]
Thanks. That's a much more helpful error message.
