### ISSUE TITLE
Dependency not found when running in subshell

### ISSUE THREAD

**Issue by rbhalla** [python-poetry/poetry#4757]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS 10.15.5
- **Poetry version**: 1.1.11
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**:
```
[tool.poetry]
name = "server"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
elasticsearch = "^7.15.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

## Issue

Currently I am working in a monorepo and use make files to execute local dev commands in the relevant folders. Before I used poetry I used to have a make that did this:

`(cd server/src && python scripts/my_script.py)`

When I started using poetry I changed that to:

`(cd server/src && poetry run python scripts/my_script.py)`

When I did that I started getting the following error:

```
ModuleNotFoundError: No module named 'elasticsearch'
```

Where elasticsearch is one of the dependencies I have in my `pyproject.toml`.

What's odd is this does work:

`cd server/src && poetry run python scripts/my_script.py`

Note, the only difference is the parentheses. I used the parentheses to run the command in a subshell which means I don't actually change directory. This however no longer works when using `poetry run`.

Does anyone know why this might be the case? And/or if there is a way I can address this issue?

**Comment by neersighted** [comment]
This does not reproduce for me on 1.2 (or, 1.1.15, in fact) on the same macOS version in a VM. I can only conclude it was some sort of local config issue -- if this still reproduces for you on current versions and you have time to debug it, feel free to comment and reopen this.
