### ISSUE TITLE
Inconsistent compatible Python versions with poetry init command and --python option

### ISSUE THREAD

**Issue by Kaltsoon** [python-poetry/poetry#4765]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows 10
- **Poetry version**: 1.1.11

## Issue

`poetry init --python ^3.8` has different behavior on macOS and Windows. On Windows the generated pyproject.toml file has `python = "3.8"` (the exact version) where as on macOS it has `python = "^3.8"`.

**Comment by clintonroy** [comment]
I don't do windows at all, but a quick google suggests caret might be an escape character.

Try "poetry init --pyhton ^^3.8" maybe, as in, two carets.

**Comment by finswimmer** [comment]
`^` have special meanings in some shells. So it is often a good idea to quote it:

```
poetry init --python "^3.8"
```

fin swimmer

**Comment by Kaltsoon** [comment]
> I don't do windows at all, but a quick google suggests caret might be an escape character.
> 
> Try "poetry init --python ^^3.8" maybe, as in, two carets.


> `^` have special meanings in some shells. So it is often a good idea to quote it:
> 
> ```
> poetry init --python "^3.8"
> ```
> 
> fin swimmer

Thanks for the suggestions, but both produce the same pyproject.toml
