### ISSUE TITLE
Conda has a good solver to properly resolve dependencies in Python (and any other language ecosystem)

### ISSUE THREAD

**Issue by mingwandroid** [python-poetry/poetry#477]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.

The documentation states:

> And, finally, there is no reliable tool to properly resolve dependencies in Python.

This in untrue, conda has used a good solver for years now. Please update this.

**Comment by stephsamson** [comment]
Hi @mingwandroid, we have discussed wording about this issue in #1594. Can you check there and see my initial PR and Sebastién's answer?
