### ISSUE TITLE
Install script location in documentation is outdated

### ISSUE THREAD

**Issue by nyuszika7h** [python-poetry/poetry#4774]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

https://python-poetry.org/docs/master/#installation lists the following command:
```
curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python -
```

When running it, I get this warning:
```
The canonical source for Poetry's installation script is now https://install.python-poetry.org. Please update your usage to reflect this.
```

The docs should be updated to point to the new URL.

**Comment by abn** [comment]
The docs have not yet been regenerated and deployed from master. The change in the doc source is already on `master`.

**Comment by LawrenceMachia** [comment]
Running on Debian (specifically Raspian) I found that the install command line given generates the following error:

`  File "install-poetry.py", line 135
    def data_dir(version: Optional[str] = None) -> Path:
                        ^
SyntaxError: invalid syntax`

Fix was to change `| python - ` to `| python3 -`

Suggest the link be changed or a note added.  Please forgive me if I've misunderstood how something works here, I am new to GitHub and coding in general.

**Comment by nyuszika7h** [comment]
Yes, that's a good idea. Most distros apart from Arch defaulted `python` to `python3` until recently. On newer versions of Debian/Ubuntu the default is to not have a `python` command at all unless you install `python-is-python3`z

**Comment by lutoma** [comment]
Are there any plans to fix this anytime soon? Almost all Google searches on the installation of poetry point at that documentation, so most new users are going to install Poetry the "wrong" way. And if you're trying to reinstall poetry like me, you might suddenly end up with two installations of poetry in different locations if you don't pay attention..

**Comment by mkniewallner** [comment]
[Documentation](https://python-poetry.org/docs/master/#installation) now use `https://install.python-poetry.org` for the installation instructions, so closing this.
