### ISSUE TITLE
Code Quality: Additional lints in this repository (help wanted!)

### ISSUE THREAD

**Issue by neersighted** [python-poetry/poetry#4776]
We're doing a bunch of code quality cleanup, and as part of that effort I'd like to implement some additional lints/coding conventions. There will be a lot of manual changes here, so I think these will be some items to have multiple people tackle. 

In no particular order:

- ~Add `ban-relative-imports = true` to `.flake8` and remove relative imports from the repo.~
- ~Add `flake8-type-checking==1.0.4` to `.pre-commit-config.yaml` with `enable-extensions = TC, TC2` in `.flake8`, and rework our type annotations for zero runtime cost using string constants. When we drop Python 3.6 support, pyupgrade will be used to automatically switch to `from __future__ import annotations` and unquote the annotations.~
- ~Add `flake8-use-fstring==1.3` to `.pre-commit-config.yaml` and fix all the use of `.format()` on string constants in the repo. Start at level 0, and try level 1 if possible. Level 2 is likely useless in this repo (I think we will always use `.format()` on string variables), but you could prove me wrong.~
- ~Remove `E501` from `.flake8` -- currently, black leaves our long comments, docstrings, and string constants alone -- let's hand-format them to comply with the line length limit.~

Please call dibs in this issue to prevent duplicated effort.

(suggestions for additional code quality improvements/tools to enforce them are also welcomed here)

**Comment by neersighted** [comment]
(suggestions for additional code quality improvements/tools to enforce them are also welcomed here)

**Comment by neersighted** [comment]
Here are some other tools I have glanced at, but not yet fully investigated for usefulness (of the tool itself, or the change):

* https://github.com/best-doctor/flake8-class-attributes-order
* https://github.com/wemake-services/flake8-eradicate
* https://github.com/MartinThoma/flake8-simplify
* https://github.com/m-burst/flake8-pytest-style
* https://github.com/PyCQA/pep8-naming
* https://github.com/pycqa/flake8-docstrings
* https://github.com/gforcada/flake8-builtins

**Comment by neersighted** [comment]
This comment tracks the implementation status of new lints:

* https://github.com/sco1/flake8-annotations @ 4775

**Comment by branchvincent** [comment]
> * Add `ban-relative-imports = true` to `.flake8` and remove relative imports from the repo.

happy to take this one!

**Comment by danieleades** [comment]
i'll take `pep8-naming`

**Comment by wagnerluis1982** [comment]
Taking the occasion, I'd like to discuss the following, in the hope of be handled as part of this effort:

`poetry-schema.json`: I noticed that both projects ([poetry](https://github.com/python-poetry/poetry/blob/master/src/poetry/json/schemas/poetry-schema.json) and [poetry-core](https://github.com/python-poetry/poetry-core/blob/master/poetry/core/json/schemas/poetry-schema.json)) carry a schema file. Is that really required? I guess we could have only one file in **poetry-core** and be consumed by **poetry** when/if required.

**Comment by abn** [comment]
@wagnerluis1982 I have moved that to https://github.com/python-poetry/poetry/discussions/4780

**Comment by branchvincent** [comment]
> * Add `flake8-use-fstring==1.3`

I'll take this one as well

**Comment by branchvincent** [comment]
Added `flake8-use-fstring` to `poetry-core`. Before adding here, we prob want to merge #4758?

**Comment by danieleades** [comment]
Are any of these plugins redundant? For example, does it make sense to use both `pyupgrade` *and* `use-f-strings`?

**Comment by neersighted** [comment]
> 
> 
> Are any of these plugins redundant? For example, does it make sense to use both `pyupgrade` _and_ `use-f-strings`?

`pyupgrade` does not enforce f-strings exactly -- it's only clever enough to do maybe 40% of the job (check out my PR). As far as the ones I have not researched/trialed in detail, they could be -- we'll have to discuss that on the individual PRs (or someone can do some research into actual usefulness and post here if they want to, I suppose).

**Comment by radoering** [comment]
>     * Add `flake8-type-checking==1.0.4`

I'll give this one a try.

**Comment by finswimmer** [comment]
Hello @radoering,

I played around with it locally and it worked quite well. The only thing I dislike is, that it forces on to put import from typing like `List` or `Dict` into the type-checking block and so they need to be quoted. This looks quite ugly.

I would suggest keeping these imports outside the type-checking block and mark them with `# noqa: TC002`.

**Comment by radoering** [comment]
> I would suggest keeping these imports outside the type-checking block and mark them with `# noqa: TC002`.

@finswimmer: Easier said than done 😉:  snok/flake8-type-checking#49 Fortunately, the maintainer released a new version with my patch as quick as greased lightning. He even made an offer to _"add a setting to allow specific module imports - like a whitelist/passlist for modules exempt from checking"_. For now, I'll add the `# noqa: TC002`. Maybe, you can comment on the linked issue if you think that poetry will benefit from such a setting.

**Comment by neersighted** [comment]
@radoering @finswimmer https://pypi.org/project/future-annotations/ is available as a third option. I'm inclined to just live with strings for now because we can remove them in a month or two when we drop 3.6 support, but if you really want to, there is an option to use the future syntax now.

**Comment by finswimmer** [comment]
Here are two more flake8-plugins I find useful:

* https://github.com/adamchainz/flake8-comprehensions
* https://github.com/best-doctor/flake8-functions

**Comment by neersighted** [comment]
> Here are two more flake8-plugins I find useful:
> 
>     * https://github.com/adamchainz/flake8-comprehensions
>     ...

That one is actually already implemented! It's pretty useful, yeah.

**Comment by neersighted** [comment]
Added a new item to the list of 'wanted' lints:

> Remove `E501` from `.flake8` -- currently, black leaves our long comments, docstrings, and string constants alone -- let's hand-format them to comply with the line length limit.

**Comment by radoering** [comment]
I'll have a look at `flake8-simplify` in the next few days. (Please have a look at the PR for a first question.)

**Comment by stinodego** [comment]
I'll gladly pick up the removal of `E501` and fix some line lengths. Expect a PR tomorrow :)

**Comment by finswimmer** [comment]
I learned about [nitpick](https://nitpick.readthedocs.io/en/latest/) these days. I wonder if we like to use it, to enforce a minimum set of checks across our repos?

**Comment by Secrus** [comment]
is this still active? are tools that are not crossed out still to be implemented?

**Comment by finswimmer** [comment]
Hey @Secrus,

I would say the tools that are not crossed are debatable, whether we really want to use or not.  The only one I really want to see is `flake8-functions`. But I guess this is not an easy one, as it would require some refactoring. If you like to pick this one, I would suggest starting applying it to `poetry-core` and split the PR's into chunks that can be reviewed easily.

fin swimmer

**Comment by dogweather** [comment]
Hey @finswimmer,

> The only one I really want to see is `flake8-functions`. But I guess this is not an easy one, as it would require some refactoring. If you like to pick this one, I would suggest starting applying it to `poetry-core` and split the PR's into chunks that can be reviewed easily.

I'd like to give this a shot. I saw that `flake8-function` checks if [a function is not pure](https://pypi.org/project/flake8-functions/) which would be amazing. I didn't know that such a linter existed for Python.

**Comment by Secrus** [comment]
> Hey @finswimmer, 
> 
> I'd like to give this a shot. I saw that `flake8-function` checks if [a function is not pure](https://pypi.org/project/flake8-functions/) which would be amazing. I didn't know that such a linter existed for Python.
@dogweather I tried flak8-functions myself, and have few conclusions:
- „purity” checks are probably broken. In both `poetry` and `poetry-core` I got 0 functions reported as „not pure”. 
- Adding this would require a lot of refactors (function lengths and amount of arguments of the function), so it would probably need to be multi-PR job, going module by module with incremental addoption.
- With how much refactors there would be, I believe this is not something we want to touch before version 1.2 is released. Post-1.2 is planned as refactoring time, so I would hołd on with the changes until then.

**Comment by dimbleby** [comment]
I find quite a lot to like in [flake8-pie](https://github.com/sbdchd/flake8-pie).  

Not sure I agree with absolutely everything it warns about, but you can always disable the things that you don't want.

(I don't plan to work on adding this to the repository, if anyone wants to have a go then we will not be duplicating one another.)

**Comment by AlpAribal** [comment]
I would like to add [flake8-pie](https://github.com/sbdchd/flake8-pie). Can make a PR today or tomorrow.

**Comment by neersighted** [comment]
I'm going to close this for now as the original effort discussed here has largely concluded over the last year. However, please do suggest new linters/code quality tools if you think they may bring improvements to the project's code, or head off common footguns.
