### ISSUE TITLE
"Invalid constraint" message for package dependencies, but they are valid for pip

### ISSUE THREAD

**Issue by violuke** [python-poetry/poetry#4777]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Docker debian bullseye
- **Poetry version**: 1.1.11

## Issue
```bash
> poetry add markdown==3.3.5

Updating dependencies
Resolving dependencies... (0.0s)PackageInfo: Invalid constraint (importlib-metadata (>='4.4') ; python_version < "3.10") found in markdown-3.3.5 dependencies, skipping
Resolving dependencies... (0.1s)

Writing lock file

No dependencies to install or update
```

Full discussion on markdown package https://github.com/Python-Markdown/markdown/issues/1195, where they are saying that the versioning is correct and this is a Poetry problem. I'm no expert, but given it can install with pip, I think this likely is a Poetry issue.

**Comment by kevr** [comment]
I'm getting the same issue here; same exact package.

**Comment by violuke** [comment]
I honestly don't know if this is Poetry or markdown (it's outside my area of expertise), but the guys on the thread https://github.com/Python-Markdown/markdown/issues/1195 in the markdown repo are pretty adamant that this is a Poetry issue, not a markdown issue, and to back up this theory, markdown 3.3.5 can be installed just fine with pip.

The version constraints did change in markdown 3.3.5 but they claim that the format used is valid:

```
install_requires=["importlib-metadata>='4.4';python_version<'3.10'"], 
```

https://github.com/Python-Markdown/markdown/blob/7919bfd8cf44e4fb50a3ccbd82b725db34b66a08/setup.py#L77

**Comment by matousek-martin** [comment]
Also running into the issue. Everything else works, it just posts a lot of warnings.

**Comment by abn** [comment]
Hmm. As far as I can tell according to [PEP 508](https://www.python.org/dev/peps/pep-0508/#complete-grammar), the single quotes are invalid.

```
wsp           = ' ' | '\t'
version_cmp   = wsp* <'<=' | '<' | '!=' | '==' | '>=' | '>' | '~=' | '==='>
version       = wsp* <( letterOrDigit | '-' | '_' | '.' | '*' | '+' | '!' )+>
version_one   = version_cmp:op version:v wsp* -> (op, v)
version_many  = version_one:v1 (wsp* ',' version_one)*:v2 -> [v1] + v2
versionspec   = ('(' version_many:v ')' ->v) | version_many
```

**Comment by abn** [comment]
As a workaround you can add `importlib-metadata` explicitly to your project. The warnings won't go away though.

**Comment by abn** [comment]
Resolved in `markdown` via https://github.com/Python-Markdown/markdown/pull/1197.
