### ISSUE TITLE
`ImportError: No module named entry_points_selectable`

### ISSUE THREAD

**Issue by TinDang97** [python-poetry/poetry#4795]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 20.04 LST
- **Poetry version**: 1.1.8 -> 1.1.11

## Issue
I have been to make a new repository but I got this issue with any command of poetry.

`/home/tindang/.poetry/lib/poetry/_vendor/py2.7/subprocess32.py:149: RuntimeWarning: The _posixsubprocess module is not being used. Child process reliability may suffer if your program uses threads.
  "program uses threads.", RuntimeWarning)
Traceback (most recent call last):
  File "/home/tindang/.poetry/bin/poetry", line 16, in <module>
    from poetry.console import main
  File "/home/tindang/.poetry/lib/poetry/console/__init__.py", line 1, in <module>
    from .application import Application
  File "/home/tindang/.poetry/lib/poetry/console/application.py", line 7, in <module>
    from .commands.about import AboutCommand
  File "/home/tindang/.poetry/lib/poetry/console/commands/__init__.py", line 4, in <module>
    from .check import CheckCommand
  File "/home/tindang/.poetry/lib/poetry/console/commands/check.py", line 2, in <module>
    from poetry.factory import Factory
  File "/home/tindang/.poetry/lib/poetry/factory.py", line 18, in <module>
    from .repositories.pypi_repository import PyPiRepository
  File "/home/tindang/.poetry/lib/poetry/repositories/pypi_repository.py", line 33, in <module>
    from ..inspection.info import PackageInfo
  File "/home/tindang/.poetry/lib/poetry/inspection/info.py", line 25, in <module>
    from poetry.utils.env import EnvCommandError
  File "/home/tindang/.poetry/lib/poetry/utils/env.py", line 23, in <module>
    import virtualenv
  File "/home/tindang/.poetry/lib/poetry/_vendor/py2.7/virtualenv/__init__.py", line 3, in <module>
    from .run import cli_run, session_via_cli
  File "/home/tindang/.poetry/lib/poetry/_vendor/py2.7/virtualenv/run/__init__.py", line 13, in <module>
    from .plugin.activators import ActivationSelector
  File "/home/tindang/.poetry/lib/poetry/_vendor/py2.7/virtualenv/run/plugin/activators.py", line 6, in <module>
    from .base import ComponentBuilder
  File "/home/tindang/.poetry/lib/poetry/_vendor/py2.7/virtualenv/run/plugin/base.py", line 5, in <module>
    from backports.entry_points_selectable import entry_points
ImportError: No module named entry_points_selectable
`

**Comment by abn** [comment]
@TinDang97 try uninstalling Poetry (assuing you used the `get-poetry.py` script) and then using the following command to install Poetry.

```sh
curl -sSL https://install.python-poetry.org/ | python3 - 
```

Alternatively, you can install poetry using `pipx`.

```sh
pip install pipx
pipx install poetry
```

**Comment by TinDang97** [comment]
> @TinDang97 try uninstalling Poetry (assuing you used the `get-poetry.py` script) and then using the following command to install Poetry. Looks like you installed it under python 2.7, which is no longer supported.
> 
> ```sh
> curl -sSL https://install.python-poetry.org/ | python3 - 
> ```
> 
> Alternatively, you can install poetry using `pipx`.
> 
> ```sh
> pip install pipx
> pipx install poetry
> ```
> 

Hi @abn,
I have been installed it under python 3.8 at begin. 
I can't understand why it switch to 2.7 at now. I will try your solutions.
Thank you.

**Comment by andrewrosss** [comment]
Same bug. Uninstalling and re-installing with

```bash
curl -sSL https://install.python-poetry.org/ | python3 - 
```

worked for me.

For convenience, if you installed poetry via `get-poetry.py` you can uninstall with:

```bash
curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python - --uninstall
```

**Comment by TinDang97** [comment]
> Same bug. Uninstalling and re-installing with
> 
> ```shell
> curl -sSL https://install.python-poetry.org/ | python3 - 
> ```
> 
> worked for me.
> 
> For convenience, if you installed poetry via `get-poetry.py` you can uninstall with:
> 
> ```shell
> curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python - --uninstall
> ```

Thank @abn and @andrewrosss ,
I solved. :D

Hope a nice day!

**Comment by bostonrwalker** [comment]
I am having this issue only @abn's solution does not work for me. I am not able to get past the `poetry init` phase.

I tried uninstall and reinstalling with Python 3.6, 3.7, 3.8, 3.9, and 3.10. I am running macOS 12.1 on Apple Silicon.
