### ISSUE TITLE
"This installer is deprecated." when using linux installer from https://python-poetry.org/docs/

### ISSUE THREAD

**Issue by Pand9** [python-poetry/poetry#4804]
I don't think it's a documentation issue, rather it's a bug as it's preventing me from installing poetry (a new user).

> $ curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3 -
> Retrieving Poetry metadata
> 
> This installer is deprecated. Poetry versions installed using this script will not be able to use 'self update' command to upgrade to 1.2.0a1 or later.
> 

The command is taken from https://python-poetry.org/docs/ .

**Comment by Pand9** [comment]
I've since noticed this and installed the proper version:
![image](https://user-images.githubusercontent.com/2797779/142712454-bd58f5c2-6d7c-41ca-9f7a-d94898837878.png)
The message above suggested that it's the only right way to do this, I'd suggest fixing the messaging. I've solved my issue so if the feedback is not useful, feel free to close.

**Comment by abn** [comment]
@Pand9 if it led to a misunderstanding, how would you recommend we rephrase the message? Are you talking about the message in the installer or the documentation?

**Comment by opyate** [comment]
Hello, I went to https://python-poetry.org/docs/
Saw this command: 
```
curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -

```

And immediately see the warning in the OP:

```
Retrieving Poetry metadata

This installer is deprecated. Poetry versions installed using this script will not be able to use 'self update' command to upgrade to 1.2.0a1 or later.
# Welcome to Poetry!

This will download and install the latest version of Poetry,
a dependency and package manager for Python.

It will add the `poetry` command to Poetry's bin directory, located at:

$HOME/.poetry/bin

This path will then be added to your `PATH` environment variable by
modifying the profile file located at:

$HOME/.profile

You can uninstall at any time by executing this script with the --uninstall option,
and these changes will be reverted.

Installing version: 1.1.12
  - Downloading poetry-1.1.12-linux.tar.gz (78.78MB)

Poetry (1.1.12) is installed now. Great!

To get started you need Poetry's bin directory ($HOME/.poetry/bin) in your `PATH`
environment variable. Next time you log in this will be done
automatically.

To configure your current shell run `source $HOME/.poetry/env`
```

Not sure about the UX here, as it feels like I made a mistake?
