### ISSUE TITLE
Error installing latest numpy version for python 3.10

### ISSUE THREAD

**Issue by rvaquerizor** [python-poetry/poetry#4808]
- [ x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [ x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: 21.10 ubuntu
- **Poetry version**: 1.1.11
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 
```
[tool.poetry]
name = "mytest"
version = "0.1.0"
description = ""
authors = ["Me <meagain156378@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
ipython = "^7.29.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api" 
```  
## Issue

I get the following error when trying to add numpy to my poetry project:
```
$ poetry add numpy
Using version ^1.21.4 for numpy

Updating dependencies
Resolving dependencies... (0.0s)

  SolverProblemError

  The current project's Python requirement (>=3.10,<4.0) is not compatible with some of the required packages Python requirement:
    - numpy requires Python >=3.7,<3.11, so it will not be satisfied for Python >=3.11,<4.0
  
  Because numpy (1.21.4) requires Python >=3.7,<3.11
   and no versions of numpy match >1.21.4,<2.0.0, numpy is forbidden.
  So, because mytest depends on numpy (^1.21.4), version solving failed.

  at ~/.poetry/lib/poetry/puzzle/solver.py:241 in _solve
      237│             packages = result.packages
      238│         except OverrideNeeded as e:
      239│             return self.solve_in_compatibility_mode(e.overrides, use_latest=use_latest)
      240│         except SolveFailure as e:
    → 241│             raise SolverProblemError(e)
      242│ 
      243│         results = dict(
      244│             depth_first_search(
      245│                 PackageNode(self._package, packages), aggregate_package_nodes

  • Check your dependencies Python requirement: The Python requirement can be specified via the `python` or `markers` properties
    
    For numpy, a possible solution would be to set the `python` property to ">=3.10,<3.11"

    https://python-poetry.org/docs/dependency-specification/#python-restricted-dependencies,
    https://python-poetry.org/docs/dependency-specification/#using-environment-markers
```

And this is my env information:

```
$ poetry env info

Virtualenv
Python:         3.10.0
Implementation: CPython
Path:           /home/me/.cache/pypoetry/virtualenvs/mytest-hpOzj5D9-py3.10
Valid:          True

System
Platform: linux
OS:       posix
Python:   /usr/local 
```

Why does poetry use this constraint?
_no versions of numpy match >1.21.4,<2.0.0_
instead of this one?
_>=1.21.4,<2.0.0_
Given that the latest numpy version chosen is 1.21.4, the >1.21.4 requirement seems to be wrong.

Also, the potential solution provided seems redundant:
    _For numpy, a possible solution would be to set the `python` property to ">=3.10,<3.11"_
Given that python is already set to 3.10.

**Comment by clintonroy** [comment]
Poetry is complaining about the versions of python allowed in your pyproject.toml, not in your environment:

python = "^3.10"

means python3.10, 3.11, 3.12, .. , 3.99, which is not compatitble with numpy.

Please try what poetry suggests, and set 

python = ">=3.10,<3.11"

**Comment by rvaquerizor** [comment]
@clintonroy 
You are absolutely right. My bad.
Changing mt pyproject.toml to what you suggested did the trick.

Thanks!
