### ISSUE TITLE
Cannot Install Proper Version of Libraries

### ISSUE THREAD

**Issue by Alpheron** [python-poetry/poetry#4809]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS 12.0.1
- **Poetry version**: 1.1.11
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: [Gist of Pyproject](https://gist.github.com/Alpheron/a67db651548f0719c2bbec6e46872bf6)

## Issue
So I have been trying to install specific versions of libraries that I require for my project. The `poetry.lock` file ends up stating that all the dependencies can use anything beyond a specific version of numpy and for this reason I should be able to install the latest version. However, the resolver states the following:
```
SolverProblemError

  The current project's Python requirement (>=3.8,<4.0) is not compatible with some of the required packages Python requirement:
    - numpy requires Python >=3.7,<3.11, so it will not be satisfied for Python >=3.11,<4.0

  Because no versions of numpy match >1.21.4,<2.0.0
   and numpy (1.21.4) requires Python >=3.7,<3.11, numpy is forbidden.
  So, because pressure-based-tumor-detection depends on numpy (^1.21.4), version solving failed.

  at /usr/local/Cellar/poetry/1.1.11/libexec/lib/python3.9/site-packages/poetry/puzzle/solver.py:241 in _solve
      237│             packages = result.packages
      238│         except OverrideNeeded as e:
      239│             return self.solve_in_compatibility_mode(e.overrides, use_latest=use_latest)
      240│         except SolveFailure as e:
    → 241│             raise SolverProblemError(e)
      242│
      243│         results = dict(
      244│             depth_first_search(
      245│                 PackageNode(self._package, packages), aggregate_package_nodes

  • Check your dependencies Python requirement: The Python requirement can be specified via the `python` or `markers` properties

    For numpy, a possible solution would be to set the `python` property to ">=3.8,<3.11"

    https://python-poetry.org/docs/dependency-specification/#python-restricted-dependencies,
    https://python-poetry.org/docs/dependency-specification/#using-environment-markers
```
My project's python version is 3.8.11 and I am confused as to why this is not working when I can install the proper version of numpy on the same Python version using pip in another virtual environment. Does anyone know any potential reasons why this might not be working? At first, I would assume this would be due to other project dependencies but all of them have no upper limit of a numpy version. They would want anything above say 1.17 or 1.12 but never specific an upper limit. Is there a reason why poetry does not default to using the highest version possible? My project has other libraries that depend on numpy and due to numpy's low version, they are not updated either.

EDIT: When testing on a separate repository with no pre-existing packages, it still results in the same error. Do poetry virtual environments change per project or is there one only poetry virtual environment used for all other projects?

**Comment by neersighted** [comment]
Hi @Alpheron! The error here is related to Python version constraints. The reason you only encounter this with Poetry is it has a much more robust dependency solver that tries to account for things like this.

Essentially, your pyproject.toml says that you are compatible with all Python versions greater than/equal to 3.8 but lesser than 4.0. Numpy has version markers allowing for compatibility with Python versions greater than/equal to 3.7 (not an issue) but less than 3.11 (a problem, as you can be more restrictive than a dep, but not more permissive).

The likely best solution is actually near the bottom of the error message.

> For numpy, a possible solution would be to set the `python` property to ">=3.8,<3.11"

It would look like this in your pyproject.toml:

```toml
numpy = {version = "^1.21.4", python = ">=3.8,<3.11"}
```

This version of Numpy would therefore only be installed in the listed Python range. Future versions of Python will have future versions of Numpy to go with them, and you'll be able to add multiple Numpy-Python version pairs if needed.

Alternatively, you could set your `python` dependency to match and restrict the compatible range of Pythons for your project to match Numpy. To do that, you would leave the `numpy` dependency alone and change your `python` to the following:

```toml
python = ">=3.8,<3.11"
```

I hope that makes sense! New tools like poetry can be confusing, as they make sure your code/project is more correct, but they also enforce invariants you are not used to from pip and the like.
