### ISSUE TITLE
Incorrect locking of platform-specific wheel dependencies

### ISSUE THREAD

**Issue by nyuszika7h** [python-poetry/poetry#4810]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Debian 11
- **Poetry version**: 1.1.1 / 1.2.0a2
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/nyuszika7h/3b26db37f0cdfe6ecc7f5bd9e2522c06

## Issue

When given the above `pyproject.toml` file, running `poetry lock` on Linux generates the following `poetry.lock`:
```toml
[[package]]                                      
name = "test"                                  
version = "1.0"                                  
description = ""                                 
category = "main"                                
optional = false                                 
python-versions = "*"                            
                                                 
[package.source]                                 
type = "file"                                    
url = "wheels/test-1.0-cp34-abi3-win_amd64.whl"
```

Also, `poetry export` outputs:
```
test @ file:///home/nyuszika7h/example/wheels/test-1.0-cp34-abi3-win_amd64.whl; sys_platform == "win32" or sys_platform == "linux" or sys_platform == "darwin"                               
```

The expected behavior would be to include 3 separate entries, one for each platform.

Interestingly enough, `poetry install` is smart enough to pick the correct version for the platform despite the incorrect locking. But the lock file is incomplete, and the requirements.txt output is just completely wrong.

**Comment by nyuszika7h** [comment]
If the dependencies are provided as URLs rather than local files, it seems like it's even worse: `poetry install` actually picks the incorrectly locked Windows version for Linux as well.

**Comment by teaVeloper** [comment]
I also have a similar issue with `poetry 1.2.0b1` locking some dependencies as windows and creating a `requirements.txt` mentioning windows, and thus install failed on a system I can only use `requirements.txt` - `poetry 1.1.13` did resolve the same `pyproject.toml` correctly.

If helpful, I can create an Issue for that with more details.
