### ISSUE TITLE
Install dependencies from private repository based on global configuration

### ISSUE THREAD

**Issue by JaviFuentes94** [python-poetry/poetry#4817]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request
Hey poetry people! 

In the process of migrating to poetry, we have found a blocker with relation to how extra indexes for downloading packages are handled. 

The situation is that while in other tools you can just set `PIP_EXTRA_INDEX_URL` env variable with your private registry and you are set everywhere, poetry enforces you to add this index URL in every single project through the `pyproject.toml` file. This means that when an organization changes the registry the link to this registry needs to be updated in every single repository manually. This doesn't sound like a good design to me.  

Given that the possibility to add repositories for publishing globally already exists, would it be possible to do the same for downloading packages? In my opinion, it is confusing that that feature only works for publishing but not downloading. 

Looking forward to hearing your thoughts.

**Comment by geudrik** [comment]
We just ran into this as well.. unless we're missing something too, this is kind of a big deal for us before we can really pull the trigger on poetry :S

**Comment by geudrik** [comment]
> This means that when an organization changes the registry the link to this registry needs to be updated in every single repository manually.

This also means that users of scaffolding you build have to constantly remember to add in extra lines (plus a couple more to handle TLS CA's) for every single project they make, on top of the few hundred projects that we make

Pls to global package indexes 😢

**Comment by neersighted** [comment]
Tracked in #5958.
