### ISSUE TITLE
Random locking failure due to CacheControl returning an empty bytes response

### ISSUE THREAD

**Issue by j-martin** [python-poetry/poetry#4821]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS Monterey
- **Poetry version**: 1.1.11

## Issue

When adding new packages or locking we observed random failures where the JSON response is empty (as in `b""`).

Through https://github.com/python-poetry/poetry/pull/4717 and https://github.com/pypa/warehouse/issues/10387 we (myself and @kapilt) found that CacheControl is returning empty data even though there should be serialized JSON object.

Removing session CacheControl seems to solve the issue.

**Comment by kapilt** [comment]
fwiw, i haven't actually hit this in a while using latest poetry releases.. i think the actual issue was solved on the pypi cdn side.
