### ISSUE TITLE
Add possibility to configure the package name that will be built in pyproject.toml

### ISSUE THREAD

**Issue by mvoitko** [python-poetry/poetry#4826]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

Add possibility to configure the package name that will be built in pyproject.toml. Probably add a `name` parameter in the 
```toml
packages = [
    { include = "src/models/*.py", from = ".", name = "cltv" },
    { include = "src/*.py", from = ".", name = "cltv" },
]
```

**Comment by finswimmer** [comment]
Hello @mvoitko,

could you please explain a bit more what you trying to do and why? It smells like an [XY-Problem](https://xyproblem.info)

fin swimmer

**Comment by finswimmer** [comment]
We haven't receive more information about it for a long time now. This is why I close this ticket.
