### ISSUE TITLE
psycopg2-binary not adequate for `import psycopg2` when `poetry add --path`

### ISSUE THREAD

**Issue by patarapolw** [python-poetry/poetry#483]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.

- **OS version and name**: macOS 10.13.6
- **Poetry version**: 0.11.5

## Issue

I am trying to use either `peewee` or `SQLAlchemy` for PostGRES.

When testing inside the package, installing only `psycopg2-binary` works fine. But when I need to use it in my another project, like

    poetry add imserv --path ../imserv

It complains that I don't have `psycopg2` installed.

Now, I can installed `psycopg2` to resolve the issue, but it comes with a warning.

    UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)

**Comment by songww** [comment]
Can you elaborate on why you can't install it? Or what went wrong during the installation process?

**Comment by patarapolw** [comment]
For installation, there is no problem. But, there are problems on import, or running PostGres-required engine.

I'll reply later if I can replicate the problem.

**Comment by songww** [comment]
You can install `psycopg2`, but can not import it?

**Comment by patarapolw** [comment]
No, I mean, if I install only `psycopg2-binary` (without `install psycopg2`), I can perfectly `import psycopg2` only while developing the package.

But when I `poetry add --path` to another project, I need `psycopg2` (and I probably don't need `psycopg2-binary`).

I can install `psycopg2-binary`, but cannot import it to another project via `poetry add --path`.

**Comment by songww** [comment]
> Can you elaborate on why you can't install it? Or what went wrong during the installation process?
Why you can not install `psycopg2`?

**Comment by patarapolw** [comment]
I can install `psycopg2`, but it gives a warning on every first usage in a script. `psycopg2-binary` gives no warning.

**Comment by bersace** [comment]
I see two solutions:

- poetry installs psycopg2 from source
- poetry installs psycopg2-binary as wheel for psycopg2 (maybe through an or dependency).

psycopg2 and its named wheel is out of bound in Python world. :/

**Comment by bertjwregeer** [comment]
There is currently no way for psycopg2-binary to state that it satisfies the psycopg2 dependency.

**Comment by kindjacket** [comment]
this is now a problem now that Psycopg 2.8 has been released

**Comment by bertjwregeer** [comment]
The author of `psycopg2` has explicitly mentioned that using `psycopg2-binary` as a dependency is not supported, and in multiple places has mentioned that people using/pinning `psycopg2-binary` other than end-users are doing it wrong.

http://initd.org/psycopg/articles/2018/02/08/psycopg-274-released/

**Comment by bersace** [comment]
Could poetry accepts `psycopg2-binary` as *providing* `psycopg2` distribution ? Something like an OR dependency ?

**Comment by bertjwregeer** [comment]
Poetry would have to special case it, this could be dangerous territory... also, for things like console scripts if there is a dependency in the chain that requires `psycopg2` but `psycopg2-binary` is installed the console script will fail to run because it can't find the required distribution.

So poetry would have to special case installing the correct information so that it looks to `pkg_resources` that `psycopg2` is installed and not `psycopg2-binary`.

This is a problem that isn't going to be easy to solve.

**Comment by kindjacket** [comment]
Just tried `poetry update` to `psycopg2 v2.8.2` with the latest poetry release (`0.12.12`) and everything worked smoothly. Working fine and no warnings. I think we can close this issue now.

**Comment by kindjacket** [comment]
scratch that - issue remains on ubuntu.

**Comment by butla** [comment]
I'm using Poetry to manage dependencies in an internal web app that's being built to a Docker image. Guess that makes me an end-user.

Would just like to report that running `poetry add psycopg2-binary` and then `poetry remove psycopg2` works fine for that case (and for my Ubuntu machine).

Poetry doesn't throw any fits and other projects depending on psycopg2 don't add it back into the dependency graph (and I wass afraid that this would happen). Nice. Though I don't know how's that happening, exactly.

@patarapolw maybe just set psycopg2-binary only in your top-level project and leave psycopg2 as the dependency for libraries?

**Comment by kindjacket** [comment]
Tried `poetry add psycopg2-binary` method. Causes problem when using peewee (ORM) as @bertjwregeer predicted above. 

```
self = <peewee.PostgresqlDatabase object at 0x110cafeb8>

    def _connect(self):
        if psycopg2 is None:
>           raise ImproperlyConfigured('Postgres driver not installed!')
E           peewee.ImproperlyConfigured: Postgres driver not installed!
```

**Comment by kindjacket** [comment]
this is still an issue :/

**Comment by bersace** [comment]
I removed explicit dependency on psycopg2 in my projects and document installing psycopg2 the way user want it (be it pip, source, wheel, rpm, deb, etc.)

poetry won't support OR dependency until wheel format supports it. That's fair;

**Comment by kindjacket** [comment]
@bersace Yeah that's fair. For people searching this - documentation on the correct installation of pyscopg2 can found here - http://initd.org/psycopg/docs/install.html#build-prerequisites

**Comment by kindjacket** [comment]
So you can still have psycopg2 as a dependency and install from poetry but you need to make sure the build requirements are satisfied as stated in - http://initd.org/psycopg/docs/install.html#build-prerequisites 

This should be closed as this is out of poetry's control.
