### ISSUE TITLE
OSError directory is not empty while running poetry install

### ISSUE THREAD

**Issue by HenriqueAJNB** [python-poetry/poetry#4833]
- **OS version and name**: Windows Server 2012 R2
- **Poetry version**: 1.1.11
- **Python version**: 3.9.9
- **Content of `pyproject.toml` file**: 
```
[tool.poetry]
name = ""
version = "0.1.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "^3.9,<3.10"
pandas = "^1.3.0"
pyarrow = "^4.0.1"
scikit-learn = "^0.24"
scipy = "^1.7.0"
pandarallel = "^1.5.2"
lightgbm = "^3.2.1"
optuna = "^2.9.1"
xgboost = "^1.4.2"
catboost = "^0.26"
python-dotenv = "^0.19.0"
SQLAlchemy = "^1.4.22"
sqlalchemy-hana = "^0.5.0"
hdbcli = "^2.9.23"
PyYAML = "^5.4.1"
joblib = "^1.0.1"
openpyxl = "^3.0.7"
ibm-db = "^3.0.4"
ibm-db-sa = "^0.3.7"
pandera = "^0.7"
loguru = "^0.5.3"
TM1py = "^1.3.1"

[tool.poetry.dev-dependencies]
bandit = "^1.7.0"
black = "^21.6b0"
isort = "^5.9.2"
pytest = "^6.2.4"
ipykernel = "^6.0.3"
rope = "^0.19.0"
coverage = "^5.5"
nbformat = "^5.1.3"
graphviz = "^0.17"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line_length = 100

[tool.bandit]
exclude = "./.venv/*"
skips = "B101"

[tool.pytest.ini_options]
testpaths = "test"
addopts = "-p no:warnings"

[tool.coverage.run]
data_file  = "docs/coverage/.coverage"
branch = true
omit = [".venv/*"]

[tool.coverage.html]
directory = "docs/coverage/"
```
## Issue

When I run `python.exe -m poetry install` an exception is raised:
Ps: Just inserted the full python path, since it's not in environment variables.

![2021-11-26_08h59_56](https://user-images.githubusercontent.com/54143210/143579012-1a07d92b-95d8-49ca-9237-a7fd376b7c62.png)

It seems that poetry itself can't clean the `Temp` file.

**Comment by HenriqueAJNB** [comment]
Just to add: the `temp` folder pointed it's already empty!

**Comment by finswimmer** [comment]
Hello @HenriqueAJNB,

you haven't come back to this issue for a long while. So I assume this is solved in the meantime and I can close this ticket.

Feel free to leave a comment if you disagree.

fin swimmer
