### ISSUE TITLE
Documentation fix - poetry add with square brackets requires quotes

### ISSUE THREAD

**Issue by ttamg** [python-poetry/poetry#4844]
A small documentation fix required to make it more intuitive how to install packages with options. An example would be `uvicorn` with dependencies such as `uvicorn[standard]'

When using poetry to add this in the default way we get an error 

```
poetry add uvicorn[standard]
```

The error such as ... `zsh: no matches found: uvicorn[standard]`.  This is on a Mac and using zsh.

Calling the `poetry add` but using quotes works just fine.  

```
poetry add 'uvicorn[standard]'
```

It took me 10 mins to find this little hack as this doesn't seem to be a `pip` requirement.  So that others don't have the same hassle, could we make this clear in the documentation please?

The poetry documentation here https://python-poetry.org/docs/cli/#add has the following which I think is misleading

```python
poetry add requests[security,socks]
poetry add "requests[security,socks]~=2.22.0"
poetry add "git+https://github.com/pallets/flask.git@1.1.1[dotenv,dev]"
```

My suggestion is
1.  Remove the first line as it doesn't work (on Mac anyway)
2. Add in a note saying that when there are options in `[]` then make sure you use quotes in the name of the package.

I'd be happy to do the PR on this but first let me know if you think this is a good idea.  I see there are 148 PRs open so not sure if they are getting airtime.

Thanks
Matt

**Comment by neersighted** [comment]
This is not related to Poetry, but your shell. ZSH is treating the braces as a special expansion syntax.

That being said, a PR adding double quotes would be welcome -- it's safe in all shells, even if the user is using a shell that does implicit square brace expansion.

**Comment by ttamg** [comment]
@neersighted OK here's a simple docs PR that adds in comment for these shells that have issues.
#4847
