### ISSUE TITLE
poetry windows powershell install not working

### ISSUE THREAD

**Issue by yalunren** [python-poetry/poetry#4845]
I used the code '(Invoke-WebRequest -Uri https://install.python-poetry.org -UseBasicParsing).Content | python -' to install poetry through windows 11 powershell. After I pressed enter, nothing happenes. I tried multiple times, it just changes to a new lines and nothing happens.. It just won't install. Tried whole day and it's working. Very frustrating. 

Anyone can help? Thanks!

Allan

- [x ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Issue
![poetry](https://user-images.githubusercontent.com/23251243/143866441-36c1c2cf-23ee-4dea-9f9e-4b675068592c.png)

**Comment by neersighted** [comment]
Do you have a working Python? Try running `python.exe` and see if you get the interactive console. I've usually seen this happen when the only `python.exe` available is the Microsoft Store stub.

**Comment by yalunren** [comment]
> Try this: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python -

Tried this, but it doesn't work under windows. The error message says 'Invoke-WebRequest: can't find parameter match sSL'

I also tried get rid of the -sSL parameter, then the error message becomes 'SyntaxError: EOF while scanning triple-quoted string literal'

Thanks for the help.

**Comment by yalunren** [comment]
> Do you have a working Python? Try running `python.exe` and see if you get the interactive console. I've usually seen this happen when the only `python.exe` available is the Microsoft Store stub.

Yes, it has. Windows 11 have python 3.9 comes with it. I run other python file fine.

Actually, I tried to use pip to install first, it finished install. However, there are some path issues that poetry just comes out with all types of errors. So I remove the installation and tried to use the invoke webrequest method to install. Just doesn't seem working.

Thanks.

**Comment by zEdS15B3GCwq** [comment]
You could try to isolate the problem by taking things step-by-step:

1. Download install-poetry.py
2. Execute it with Python

You can download the script with any web browser by opening https://install.python-poetry.org; or use ` Invoke-WebRequest -Uri https://install.python-poetry.org -UseBasicParsing -OutFile install-poetry.py`; or use wget in a basic command prompt, etc. Verify that the file looks like a python script.

Once you have the file, you can execute it with `python install-poetry.py` or python3 or py or whatever works on your system to invoke python.

If either of these steps fails, you can dig further to understand what's wrong.

**Comment by yalunren** [comment]
> You could try to isolate the problem by taking things step-by-step:
> 
> 1. Download install-poetry.py
> 2. Execute it with Python
> 
> You can download the script with any web browser by opening https://install.python-poetry.org; or use ` Invoke-WebRequest -Uri https://install.python-poetry.org -UseBasicParsing -OutFile install-poetry.py`; or use wget in a basic command prompt, etc. Verify that the file looks like a python script.
> 
> Once you have the file, you can execute it with `python install-poetry.py` or python3 or py or whatever works on your system to invoke python.
> 
> If either of these steps fails, you can dig further to understand what's wrong.

Tried it and it shows error occurred.

Checked the error log , it says "No pyvenv.cfg file and a bunch of python errors"

Where can I find the pyvenv.cfg file? or do I have to install some dependency first?

Thanks.

**Comment by kawo** [comment]
Hello!

Had the exact same issue while installing Poetry on Windows 11: nothing happen.

Installing step by step as @zEdS15B3GCwq suggested showed the same error as @yalunren: "No pyvenv.cfg file found".

I was using the MS Store version of Python. Uninstalling it and properly install it from https://www.python.org/ fixed the issue (don't forget to add the 'Scripts' python39 folder and the 'Python/Scripts' folder generated by Poetry to your system PATH!).

![Capture d’écran 2021-11-30 162409](https://user-images.githubusercontent.com/548404/144075817-6838f75a-880d-40f0-afeb-670851a43241.png)

**Comment by zEdS15B3GCwq** [comment]
I've never tried installing Python through the MS Store; the official installer from pyton.org has not failed me yet. Instead of adding the Python installation's scripts folder to the path, you can just install the python launcher bundled with the official python installer. I believe this is the recommended way. In this case you can just invoke python with `py.exe` - of course, poetry's install script should also be executed with it instead of python.exe.

**Comment by JurajKlacansky** [comment]
Same issue here...
When I try install poetry with `(Invoke-WebRequest -Uri https://install.python-poetry.org -UseBasicParsing).Content | python -` nothing happenes.
With `(Invoke-WebRequest -Uri https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py -UseBasicParsing).Content | python -` installation was successful.

OS: Microsoft Windows 10 Home (10.0.19042 Build 19042)
PowerShell: v7.2.0
Python: Python 3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)] on win32

![image](https://user-images.githubusercontent.com/50420930/144127751-e4f1021b-6ad8-4d58-8515-03cc021d05c7.png)

**Comment by yalunren** [comment]
> Same issue here... When I try install poetry with `(Invoke-WebRequest -Uri https://install.python-poetry.org -UseBasicParsing).Content | python -` nothing happenes. With `(Invoke-WebRequest -Uri https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py -UseBasicParsing).Content | python -` installation was successful.
> 
> OS: Microsoft Windows 10 Home (10.0.19042 Build 19042) PowerShell: v7.2.0 Python: Python 3.10.0 (tags/v3.10.0:b494f59, Oct 4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)] on win32
> 
> ![image](https://user-images.githubusercontent.com/50420930/144127751-e4f1021b-6ad8-4d58-8515-03cc021d05c7.png)

The link works but installation was still failed in Win11. Still show "No pyvenv.cfg " 

Guess has to do with the python path.

Thanks!

**Comment by zEdS15B3GCwq** [comment]
I suggest that instead of just reporting "nothing happens", those who have issues do some troubleshooting what the issue could be. Poetry developers, if they grace us with their attention, won't be able to do much with reports that state that things just don't work.

Try to isolate the problem by breaking up the process into steps, e.g. downloading the install script, verifying its contents, and then executing it with python. Several possible issues have been mentioned here already, e.g. Python installed through the MS Store doesn't seem to work well, and where the script is downloaded from may also matter (see post by @JurajKlacansky), etc. @JurajKlacansky, for example, could compare if there's a difference between scripts downloaded from the two sources, to see why one didn't work. @yalunren , have you tried reinstalling python (remove the one from MS store, install from python.org) as @kawo suggested?

Also, try methods that worked for others. For me, Python installer from python.org + downloaded install script + executing script with the python launcher `py` has never had any issues.

**Comment by yalunren** [comment]
> Hello!
> 
> Had the exact same issue while installing Poetry on Windows 11: nothing happen.
> 
> Installing step by step as @zEdS15B3GCwq suggested showed the same error as @yalunren: "No pyvenv.cfg file found".
> 
> I was using the MS Store version of Python. Uninstalling it and properly install it from https://www.python.org/ fixed the issue (don't forget to add the 'Scripts' python39 folder and the 'Python/Scripts' folder generated by Poetry to your system PATH!).
> 
> ![Capture d’écran 2021-11-30 162409](https://user-images.githubusercontent.com/548404/144075817-6838f75a-880d-40f0-afeb-670851a43241.png)

Thanks for sharing.

My python comes with Win11, didn't install from the MS store.

It seems its Win11's python path problem. Its default python path is 

'c:\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0'

So poetry installation probably can't find the python path.

Not sure if installation can be improve so I don't have to reinstall python in windows.

> Hello!
> 
> Had the exact same issue while installing Poetry on Windows 11: nothing happen.
> 
> Installing step by step as @zEdS15B3GCwq suggested showed the same error as @yalunren: "No pyvenv.cfg file found".
> 
> I was using the MS Store version of Python. Uninstalling it and properly install it from https://www.python.org/ fixed the issue (don't forget to add the 'Scripts' python39 folder and the 'Python/Scripts' folder generated by Poetry to your system PATH!).
> 
> ![Capture d’écran 2021-11-30 162409](https://user-images.githubusercontent.com/548404/144075817-6838f75a-880d-40f0-afeb-670851a43241.png)

Thanks for sharing.

My python comes with Win11, didn't install from the MS store.

It seems its Win11's python path problem. Its default python path is 

'c:\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0'

So poetry installation probably can't find the python path.

Not sure if installation can be improve so I don't have to reinstall python in windows.

**Comment by yalunren** [comment]
> I suggest that instead of just reporting "nothing happens", those who have issues do some troubleshooting what the issue could be. Poetry developers, if they grace us with their attention, won't be able to do much with reports that state that things just don't work.
> 
> Try to isolate the problem by breaking up the process into steps, e.g. downloading the install script, verifying its contents, and then executing it with python. Several possible issues have been mentioned here already, e.g. Python installed through the MS Store doesn't seem to work well, and where the script is downloaded from may also matter (see post by @JurajKlacansky), etc. @JurajKlacansky, for example, could compare if there's a difference between scripts downloaded from the two sources, to see why one didn't work. @yalunren , have you tried reinstalling python (remove the one from MS store, install from python.org) as @kawo suggested?

I haven't tried to reinstall python because I have other program running with default python. Not sure if remove it and reinstall will cause other problem.

Also ,the error logs seems different with the ' https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py' installation url.

========
No pyvenv.cfg file


Traceback:

  File "<stdin>", line 872, in main
  File "<stdin>", line 503, in run
  File "<stdin>", line 524, in install
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "<stdin>", line 596, in make_env
  File "<stdin>", line 582, in make_env
  File "<stdin>", line 317, in make
  File "<stdin>", line 340, in pip
  File "<stdin>", line 337, in python
  File "<stdin>", line 330, in run
==========

Thanks

**Comment by zEdS15B3GCwq** [comment]
I think in general you'll be much better off with the python.org version instead of something managed by Microsoft, if you can make the transition. You can just install python 3.9 and your other programs should be able to use that. Not sure what else I can say, since unless you look into it yourself and find out the real reason, based on what's been written here it seems likely that the installation is what's causing your problem.

As far as I recall (can't verify now), my Windows 11 didn't come with Python installed; it only had a stub that when you tried to execute python would prompt an install from the store. Check your MS store apps and if it's from there, you should be able reinstall it from the store later if needed.

**Comment by yalunren** [comment]
> I think in general you'll be much better off with the python.org version instead of something managed by Microsoft, if you can make the transition. You can just install python 3.9 and your other programs should be able to use that. Not sure what else I can say, since unless you look into it yourself and find out the real reason, based on what's been written here it seems likely that the installation is what's causing your problem.
> 
> As far as I recall (can't verify now), my Windows 11 didn't come with Python installed; it only had a stub that when you tried to execute python would prompt an install from the store. Check your MS store apps and if it's from there, you should be able reinstall it from the store later if needed.
> 
> BtW, it appears that pyvenv.cfg is something that is placed into appdata\roaming\pypoetry\venv by the installation script.

I reinstalled python  from python.org and ran the "(Invoke-WebRequest -Uri https://install.python-poetry.org -UseBasicParsing).Content | python -" install link. It still has no respones. 

So I tried the "(Invoke-WebRequest -Uri https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py -UseBasicParsing).Content | python -" link. It started installation but it fails to install at the end. 

Then I downloaded the py file and run the installation locally, and it worked. It also tells me to add path to the system path. I add it and finally it's done. Anyway, I guess it has to do with the python installation location.

Thanks for all the helps.

**Comment by zEdS15B3GCwq** [comment]
First of all, I'm glad to hear it worked out for you in the end, @yalunren .

No idea why the installer on one link would not produce response while the other ran (but failed) - I compared the two scripts and they're essentially the same except for a warning in the one at raw.githubusercontent.com to use the other one; and different carriage return types that shouldn't be an issue. However, unless you added python to the path or you're using some kind of virtual environment manager, running `python` very likely still launched the python version installed from the windows store. If I remember correctly, the python.org installer offers to include the _python launcher_, which allows python to be run with the `py` command - and not `python`. Just make sure you are using the correct one.

**Comment by yalunren** [comment]
Thanks, I guess it might because of some network issue. When I click the poetry.org link through browser, it downloads the file. When I click github link, it directly shows the script in the browser. Not sure if this has to do with how powershell runs the code.

**Comment by mtnpke** [comment]
Hi all,

the reason (AFAICT) is a misconfiguration of the webserver at https://install.python-poetry.org/

The headers returned there include `Content-Type: application/octet-stream`. This means that PowerShell does not decode the response and that the `.Content` property is a byte array. If you look at `.Content` you will only get numbers. Python can't use this. See https://stackoverflow.com/questions/51333965/invoke-webrequest-returning-unexpected-results-for-some-addresses

If the web server is fixed to return a proper text Content-Type, everything should be fine :)

**Comment by zEdS15B3GCwq** [comment]
> Hi all,
> 
> the reason (AFAICT) is a misconfiguration of the webserver at https://install.python-poetry.org/
> 
> The headers returned there include `Content-Type: application/octet-stream`. This means that PowerShell does not decode the response and that the `.Content` property is a byte array. If you look at `.Content` you will only get numbers. Python can't use this. See https://stackoverflow.com/questions/51333965/invoke-webrequest-returning-unexpected-results-for-some-addresses
> 
> If the web server is fixed to return a proper text Content-Type, everything should be fine :)

Everything will be fine as far as the script is concerned. Python installed through the app store (automatically by Windows) seems to be an issue too, regardless of the script. (I'm pointing this out just to make sure that people who come here for a quick solution and don't read all the messages aren't mislead into thinking that the sole issue was with the download script.)

**Comment by liudonghua123** [comment]
I have the same issue, my python was installed from ms store.

**Comment by liudonghua123** [comment]
> > I suggest that instead of just reporting "nothing happens", those who have issues do some troubleshooting what the issue could be. Poetry developers, if they grace us with their attention, won't be able to do much with reports that state that things just don't work.
> > Try to isolate the problem by breaking up the process into steps, e.g. downloading the install script, verifying its contents, and then executing it with python. Several possible issues have been mentioned here already, e.g. Python installed through the MS Store doesn't seem to work well, and where the script is downloaded from may also matter (see post by @JurajKlacansky), etc. @JurajKlacansky, for example, could compare if there's a difference between scripts downloaded from the two sources, to see why one didn't work. @yalunren , have you tried reinstalling python (remove the one from MS store, install from python.org) as @kawo suggested?
> 
> I haven't tried to reinstall python because I have other program running with default python. Not sure if remove it and reinstall will cause other problem.
> 
> Also ,the error logs seems different with the ' https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py' installation url.
> 
> No pyvenv.cfg file
> 
> Traceback:
> 
> ## File "", line 872, in main
> File "", line 503, in run
> File "", line 524, in install
> File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\contextlib.py", line 119, in **enter**
> return next(self.gen)
> File "", line 596, in make_env
> File "", line 582, in make_env
> File "", line 317, in make
> File "", line 340, in pip
> File "", line 337, in python
> File "", line 330, in run
> Thanks

After a long time of debugging. I found the problem.

```shell
D:\code\python\pyoxidizer_example>python
Python 3.10.1 (tags/v3.10.1:2cd268a, Dec  6 2021, 19:10:37) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import subprocess
>>> subprocess.run(('C:/Users/Liu.D.H/AppData/Roaming/pypoetry/venv/Scripts/python.exe', '-m', 'pip', '--isolated', 'install', '-v','--disable-pip-version-check', '--upgrade', 'pip'))
No pyvenv.cfg file
urncode=106)
>>> import os
>>> os.path.realpath('C:/Users/Liu.D.H/AppData/Roaming/pypoetry/venv/Scripts/python.exe')
'C:\\Users\\Liu.D.H\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\Roaming\\pypoetry\\venv\\Scripts\\python.exe'
>>> subprocess.run((os.path.realpath('C:/Users/Liu.D.H/AppData/Roaming/pypoetry/venv/Scripts/python.exe'), '-m', 'pip', '--isolated', 'install', '-v','--disable-pip-version-check', '--upgrade', 'pip'))   
Using pip 21.3.1 from C:\Users\Liu.D.H\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Roaming\pypoetry\venv\lib\site-packages\pip (python 3.10)Requirement already satisfied: pip in c:\users\liu.d.h\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\roaming\pypoetry\venv\lib\site-packages (21.3.1)CompletedProcess(args=('C:\\Users\\Liu.D.H\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\Roaming\\pypoetry\\venv\\Scripts\\python.exe', '-m', 'pip', '--isolated', 'install', '-v', '--disable-pip-version-check', '--upgrade', 'pip'), returncode=0)
>>>
```

So I download `install-poetry.py` and change the following code 

https://github.com/python-poetry/poetry/blob/6a35cc41e950d4ff0f1efad649c1d15d689a9ce2/install-poetry.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L277-L279
to
```python
        self._python = os.path.realpath(str(
            self._path.joinpath("Scripts/python.exe" if WINDOWS else "bin/python")
        ))
```

**Comment by liudonghua123** [comment]
> > I suggest that instead of just reporting "nothing happens", those who have issues do some troubleshooting what the issue could be. Poetry developers, if they grace us with their attention, won't be able to do much with reports that state that things just don't work.
> > Try to isolate the problem by breaking up the process into steps, e.g. downloading the install script, verifying its contents, and then executing it with python. Several possible issues have been mentioned here already, e.g. Python installed through the MS Store doesn't seem to work well, and where the script is downloaded from may also matter (see post by @JurajKlacansky), etc. @JurajKlacansky, for example, could compare if there's a difference between scripts downloaded from the two sources, to see why one didn't work. @yalunren , have you tried reinstalling python (remove the one from MS store, install from python.org) as @kawo suggested?
> 
> I haven't tried to reinstall python because I have other program running with default python. Not sure if remove it and reinstall will cause other problem.
> 
> Also ,the error logs seems different with the ' https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py' installation url.
> 
> No pyvenv.cfg file
> 
> Traceback:
> 
> ## File "", line 872, in main
> File "", line 503, in run
> File "", line 524, in install
> File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\contextlib.py", line 119, in **enter**
> return next(self.gen)
> File "", line 596, in make_env
> File "", line 582, in make_env
> File "", line 317, in make
> File "", line 340, in pip
> File "", line 337, in python
> File "", line 330, in run
> Thanks

After a long time of debugging. I found the problem.

```shell
D:\code\python\pyoxidizer_example>python
Python 3.10.1 (tags/v3.10.1:2cd268a, Dec  6 2021, 19:10:37) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import subprocess>>> subprocess.run(('C:/Users/Liu.D.H/AppData/Roaming/pypoetry/venv/Scripts/python.exe', '-m', 'pip', '--isolated', 'install', '-v','--disable-pip-version-check', '--upgrade', 'pip'))
No pyvenv.cfg file
urncode=106)>>> import os
>>> os.path.realpath('C:/Users/Liu.D.H/AppData/Roaming/pypoetry/venv/Scripts/python.exe')
'C:\\Users\\Liu.D.H\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\Roaming\\pypoetry\\venv\\Scripts\\python.exe'>>> subprocess.run((os.path.realpath('C:/Users/Liu.D.H/AppData/Roaming/pypoetry/venv/Scripts/python.exe'), '-m', 'pip', '--isolated', 'install', '-v','--disable-pip-version-check', '--upgrade', 'pip'))   
Using pip 21.3.1 from C:\Users\Liu.D.H\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Roaming\pypoetry\venv\lib\site-packages\pip (python 3.10)Requirement already satisfied: pip in c:\users\liu.d.h\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\roaming\pypoetry\venv\lib\site-packages (21.3.1)CompletedProcess(args=('C:\\Users\\Liu.D.H\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\Roaming\\pypoetry\\venv\\Scripts\\python.exe', '-m', 'pip', '--isolated', 'install', '-v', '--disable-pip-version-check', '--upgrade', 'pip'), returncode=0)
>>>
```

So I download `install-poetry.py` and change the following code 

https://github.com/python-poetry/poetry/blob/6a35cc41e950d4ff0f1efad649c1d15d689a9ce2/install-poetry.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L277-L279
to
```python
        self._python = os.path.realpath(str(
            self._path.joinpath("Scripts/python.exe" if WINDOWS else "bin/python")
        ))
```

**Comment by Kaltsoon** [comment]
Any progress related to this? The suggested `(Invoke-WebRequest -Uri https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py -UseBasicParsing).Content | python -` seems to work, but it is extremely inconvenient that the official installation instructions don't work.

**Comment by dimasahmad** [comment]
While both URLs has the same content, they have different HTTP headers, specifically the `Content-Type` header.

- `https://install.python-poetry.org/`:
```
content-type: application/octet-stream
```

- `https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py`:
```
content-type: text/plain; charset=utf-8
```

The type of `Content` is byte array by default (See https://docs.microsoft.com/en-us/dotnet/api/microsoft.powershell.commands.webresponseobject.content?view=powershellsdk-7.0.0). You can try running `(Invoke-WebRequest -Uri https://install.python-poetry.org).Content` and it will print out a bunch of byte arrays instead of human readable text, hence why python can't run the script. We have to use the correct `content-type` for `Invoke-WebRequest` to properly recognize the encoding.

There's two way to fix this:

1. Change the `Content-Type` http header of https://install.python-poetry.org/ to `text/plain; charset=utf-8`
2. Change the install command (as a temporary workaround)
```powershell
[System.Text.Encoding]::UTF8.GetString((Invoke-WebRequest -Uri https://install.python-poetry.org -UseBasicParsing).Content) | python -
```

**Comment by bbecausereasonss** [comment]
Having same issue with MS Store Python :/

**Comment by jmcneil1** [comment]
I had no issues with running the installer from the python-poetry.org but I can't seem to run the command "poetry" after the installation even with it being in the correct PATH for system and user. I have to be in the exact directory of the installation and run it like .\poetry to do anything. Also in Windows 11. It does recognize that poetry and python are installed (Poetry version 1.6.1, Python version 3.11.5) 
Im trying to complete a Cognite training course and in order to pass the test I have to actually copy a github repository and run things in order to get the data out.

**Comment by jgentes** [comment]
In my case (using the Windows installer from the Python website), Python worked fine, Poetry installed but wouldn't run.

Adding the Python scripts path to my Windows Path environment variable did the trick:
`C:\Users\me\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\Scripts`
