### ISSUE TITLE
Poetry can't add any package anymore in a reasonable amount of time

### ISSUE THREAD

**Issue by floatingpurr** [python-poetry/poetry#4855]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Issue
Here's my env:
* macOS Big Sur
* pyenv (Python 3.10)
* Poetry version `1.1.12` (installed with pipx)
* My config
```bash
$ poetry config --list
cache-dir = "/myPath"
experimental.new-installer = true
installer.parallel = true
virtualenvs.create = true
virtualenvs.in-project = true
virtualenvs.path = "{cache-dir}/virtualenvs"  # /myPath/virtualenvs
```

I have worked with poetry smoothly so far. Suddenly, it looks like poetry can't resolve dependencies anymore in a reasonable amount of time. It happens, for example, with `pytest`. This is my starting `pyproject.toml`

<details>
<summary>click to expand my pyproject.toml</summary>

```toml
[tool.poetry]
name = "foo"
version = "0.1.0"
description = ""
authors = ["Foo <foo@example.org>"]

# ciao
[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```
</details>

if I run `$ poetry add pytest --dev -vvv` 

I get this output (ie: poetry stuck in _Resolving dependencies..._ )

<details>
<summary>click to expand command output</summary>

```bash
Using virtualenv: /projectPath/foo/.venv
PyPI: 147 packages found for pytest *
Using version ^6.2.5 for pytest

Updating dependencies
Resolving dependencies...
   1: fact: foo is 0.1.0
   1: derived: foo
   1: fact: foo depends on pytest (^6.2.5)
   1: fact: foo depends on pytest (^6.2.5)
   1: selecting foo (0.1.0)
   1: derived: pytest (>=6.2.5,<7.0.0)
PyPI: 1 packages found for pytest >=6.2.5,<7.0.0
   1: fact: pytest (6.2.5) depends on attrs (>=19.2.0)
   1: fact: pytest (6.2.5) depends on iniconfig (*)
   1: fact: pytest (6.2.5) depends on packaging (*)
   1: fact: pytest (6.2.5) depends on pluggy (>=0.12,<2.0)
   1: fact: pytest (6.2.5) depends on py (>=1.8.2)
   1: fact: pytest (6.2.5) depends on toml (*)
   1: fact: pytest (6.2.5) depends on atomicwrites (>=1.0)
   1: fact: pytest (6.2.5) depends on colorama (*)
   1: selecting pytest (6.2.5)
   1: derived: colorama
   1: derived: atomicwrites (>=1.0)
   1: derived: toml
   1: derived: py (>=1.8.2)
   1: derived: pluggy (>=0.12,<2.0)
   1: derived: packaging
   1: derived: iniconfig
   1: derived: attrs (>=19.2.0)
PyPI: 42 packages found for colorama *
^C   1: Version solving took 93.503 seconds.
   1: Tried 1 solutions.
```
</details>

As you can see, I stopped the process after 96s. I can't understand what is going on and why it suddenly started taking so long for installing just `pytest`. How can I fix it up?

PS: this issue started after installing `ruamel.yaml` with poetry. I'm quite sure it was just a coincidence. But that is what happened.

PPS: the issue persists also after clearing cache with `$ poetry cache clear --all pypi`

**Comment by floatingpurr** [comment]
Edit: Looks like I can't even start a new project from scratch

```bash
$ poetry new foo
$ cd foo
foo$ poetry install
Creating virtualenv foo in /mypath/foo/.venv
Updating dependencies
Resolving dependencies... (210.8s) 
```
...still hanging

**Comment by clintonroy** [comment]
Can you truss it? see what it's hanging on

**Comment by floatingpurr** [comment]
It depends on the run. It looks like it could be related to networking problems https://github.com/python-poetry/poetry/issues/2094#issuecomment-988194630 Still investigating on it. Hints welcome.

**Comment by floatingpurr** [comment]
Any updates about it?

**Comment by Alfro** [comment]
Hey @floatingpurr are you still reproducing this issue consistently on 1.1.13? I gave it a try with your toml and had no issues, but the command output is very different as of now. Did you discard network issues on your environment?

**Comment by floatingpurr** [comment]
Unfortunately this issue doesn't happen programmatically. Read #2094 for more.

**Comment by Alfro** [comment]
Ah, it indeed seems quite the non-deterministic issue. Would this count as duplicated of #2094? Might be worth closing in favor of that one.

**Comment by floatingpurr** [comment]
Yep, sure. Pls, reference https://github.com/python-poetry/poetry/issues/2094 for further details

**Comment by floatingpurr** [comment]
See also https://github.com/python-poetry/poetry/issues/2094#issuecomment-1106447343 as a possible solution
