### ISSUE TITLE
Install R in a poetry env

### ISSUE THREAD

**Issue by ZenBel** [python-poetry/poetry#4858]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Issue
I have a poetry environment that I spawn with ```poetry shell```. I would like to install ```R``` in this local environment and then install ```rpy2``` to call some ```R``` functions from ```python```. How can I achieve this?

**Comment by finswimmer** [comment]
Hello @ZenBel,

this cannot be achieved by poetry. Just like `pip` Poetry can only handle python packages.

fin swimmer
