### ISSUE TITLE
Time until `poetry-core` release 1.1.0a7?

### ISSUE THREAD

**Issue by dataframing** [python-poetry/poetry#4859]
Hi,

I'm dealing with https://github.com/python-poetry/poetry/issues/4523 across quite a few `poetry` projects. The problem appeared to be some regression between `poetry-core` 1.0.4 and 1.0.5. Pinning the `poetry` client's `poetry-core==1.0.4` seems to work in the short-term, but I'm not crazy about the hack/patch.

`poetry` itself depends on `poetry-core^1.1.0a6`, which was released on July 30th, 2021, when the latest `1.0.x` release was `1.0.3` on April 2021. Since then, the `1.0.x` releases have seen updates up to `1.0.7`, notably where `1.0.6` claims to have fixed this (via #207).

https://github.com/python-poetry/poetry/blob/e1235188d09e3688338867ae0897b79251c63bf9/pyproject.toml#L37

My question is: **would it be possible to release `1.1.0a7` that includes the recent updates to the `1.0.x` releases so that `poetry` is installed with a version of `poetry-core` that addresses this issue?**

- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

**Comment by radoering** [comment]
> My question is: **would it be possible to release `1.1.0a7` that includes the recent updates to the `1.0.x` releases so that `poetry` is installed with a version of `poetry-core` that addresses this issue?**

Resolved by python-poetry/poetry-core#289. The pre-release is built from `master` branch which should include all fixes of `1.0` branch (and many more).

However, the issue you mention is still open. (By the way, if you want to link a PR from `poetry-core`, you have to add the prefix `python-poetry/poetry-core`. I was a little confused for a moment as to what the two Issues were supposed to have to do with each other. 😉)
