### ISSUE TITLE
Read Source URLs from pyproject.toml During Publishing

### ISSUE THREAD

**Issue by kevinkjt2000** [python-poetry/poetry#486]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue
When attempting to publish packages from CI infrastructure, such as Jenkins, poetry will fail when a config file cannot be found and a `--repository=something` option is present.  Instead of throwing a RuntimeError, the URL for the source could be read from the `[[tool.poetry.source]]` section(s) in a pyproject.toml file.  Whether reading from pyproject.toml should happen upfront or be the fallback behavior, does not make a difference to me.

https://github.com/sdispater/poetry/blob/9dac5bf0ad36415592fd03d049cd8d1adedd161f/poetry/masonry/publishing/publisher.py#L42-L53

**Comment by kevinkjt2000** [comment]
Beep-boop, might be stale, but still an issue

**Comment by abn** [comment]
This will not work. As endpoints required for simple api and upload apis are different. A potential feature could be the addition of publish targets within the `pyproject.toml`. I do not think you can avoid having these configured separately.

**Comment by kevinkjt2000** [comment]
@abn Perhaps my suggested fix is incorrect, but this is still a bug, no?

**Comment by abn** [comment]
I do not think so. If the specified repository is not configured, it is an error. We could change it to be not a `RunTimeError` but a more graceful error. However, the behaviour itself is not a bug. We cannot published to an undefined repository.

**Comment by abn** [comment]
Partialy correct. It today supports only configuration via env vars or via config files. In, `--repository=something` `something` should always be the name of a configured publishable repository. At present there are no plans to include the upload api endpoint as a configurable in the `tool.poetry.source` section. This is the status quo. This might change if there is a reasonable proposal. I suspect there has been talks about allowing a new section to let a project specify where it should be uploaded by default. But that is outside the scope of this issue I feel. Feel free to raise a discussion and/or propose a change in a PR.

See also https://python-poetry.org/docs/master/repositories/#publishable-repositories.
