### ISSUE TITLE
Install only dev dependencies

### ISSUE THREAD

**Issue by juliuskittler** [python-poetry/poetry#4864]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

The documentation mentions "The `--dev-only` option is now deprecated. You should use the `--only dev` notation instead." (https://python-poetry.org/docs/master/cli/)

However, this functionality is not actually available in poetry 1.1.11 (see `poetry install --help`). It would be great if you could bring it back (there have been other issues related to this).

**Comment by finswimmer** [comment]
The documentation is a little bit misleading here. The `--dev-only` option was never available in a release, but was already available in the master branch. Because it's a feature we will probably not backport this to the 1.1 branch.
