### ISSUE TITLE
Poetry is impossible to install on the python docker images.

### ISSUE THREAD

**Issue by tedivm** [python-poetry/poetry#4865]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

## Issue

Poetry will not install on the docker images.

> curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -

This gives the "module not found" error with "cleo" as the missing module, same as #3345.

If I try the workaround in that issue-

```
install_url="https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py"
curl -sSL "$install_url" | POETRY_HOME=$install_path python3 - --git "https://github.com/python-poetry/poetry.git@master"
```

I just get more errors-

```
app_1  | The canonical source for Poetry's installation script is now https://install.python-poetry.org. Please update your usage to reflect this.
app_1  | # Welcome to Poetry!
app_1  |
app_1  | This will download and install the latest version of Poetry,
app_1  | a dependency and package manager for Python.
app_1  |
app_1  | It will add the `poetry` command to Poetry's bin directory, located at:
app_1  |
app_1  | /root/.local/bin
app_1  |
app_1  | You can uninstall at any time by executing this script with the --uninstall option,
app_1  | and these changes will be reverted.
app_1  |
app_1  | Installing Poetry (https://github.com/python-poetry/poetry.git@)
app_1  | Installing Poetry (https://github.com/python-poetry/poetry.git@): Creating environment
app_1  | Installing Poetry (https://github.com/python-poetry/poetry.git@): Installing Poetry
app_1  | Installing Poetry (https://github.com/python-poetry/poetry.git@): An error occurred. Removing partial environment.
app_1  | Poetry installation failed.
app_1  | See /app/poetry-installer-error-txk2xmfn.log for error logs.
```

The installation log-

```

app-1  | Collecting git+https://github.com/python-poetry/poetry.git@
app-1  | ERROR: The URL 'git+https://github.com/python-poetry/poetry.git@' has an empty revision (after @) which is not supported. Include a revision after @ or remove @ from the URL.
app-1  |
app-1  | Traceback:
app-1  |
app-1  |   File "<stdin>", line 872, in main
app-1 |   File "<stdin>", line 503, in run
app-1 |   File "<stdin>", line 525, in install
app-1  |   File "<stdin>", line 632, in install_poetry
app-1  |   File "<stdin>", line 340, in pip
app-1  |   File "<stdin>", line 337, in python
app-1  |   File "<stdin>", line 330, in run
app-1  | Collecting git+https://github.com/python-poetry/poetry.git@
app-1  | ERROR: The URL 'git+https://github.com/python-poetry/poetry.git@' has an empty revision (after @) which is not supported. Include a revision after @ or remove @ from the URL.
app-1 |
app-1  | Traceback:
app-1 |
app-1  |   File "<stdin>", line 872, in main
app-1  |   File "<stdin>", line 503, in run
app-1  |   File "<stdin>", line 525, in install
app-1  |   File "<stdin>", line 632, in install_poetry
app-1  |   File "<stdin>", line 340, in pip
app-1  |   File "<stdin>", line 337, in python
app-1 |   File "<stdin>", line 330, in run
app-1 exited with code 2
```

It seems like the installer is ignoring the git branch that is passed to it.

I've tried this with the python3.9 and python 3.10 containers.

**Comment by tedivm** [comment]
The same error occurs with just-

```
install_url="https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py"
curl -sSL "$install_url" | python3
```

**Comment by neersighted** [comment]
Hi @tedivm! I think more detailed reproduction instructions will be needed to understand what you are trying to do. That being said, I did my best to create a simple reproduction and am unable to replicate what you are experiencing:

```sh
printf "
set -xe
curl -sSL https://install.python-poetry.org | python3 - --git https://github.com/python-poetry/poetry.git@master
export PATH="/root/.local/bin:$PATH"
poetry --version
poetry new foobar
pushd foobar
poetry add pycowsay
poetry run pycowsay 'Hello world!'
" | docker run --rm -i --entrypoint bash python:3.10
```

Please try this out on your system and let us know if it works! We'll probably move this to a discussion at that point if it proves not to be a bug in poetry.

**Comment by SpangleLabs** [comment]
Hey there, I'm seeing a very similar issue, and I've been struggling against it for a couple days now.

Dockerfile:
```
FROM python:3.10
RUN set -xe
RUN curl -sSL https://install.python-poetry.org | python3 - --git https://github.com/python-poetry/poetry.git@master
RUN export PATH="/root/.local/bin:$PATH"
RUN poetry --version
RUN poetry new foobar
RUN pushd foobar
RUN poetry add pycowsay
RUN poetry run pycowsay 'Hello world!'
```

And fails with:
```
 => ERROR [ 5/11] RUN poetry --version                                                                    52.6s 
------
 > [ 5/11] RUN poetry --version:
#9 51.65 /bin/sh: 1: poetry: not found
------
executor failed running [/bin/sh -c poetry --version]: exit code: 127
```

**Comment by clintonroy** [comment]
Docker context is different to shell context, you need to use ENV and WORKDIR:

```
FROM python:3.10
RUN set -xe
RUN curl -sSL https://install.python-poetry.org | python3 - --git https://github.com/python-poetry/poetry.git@master
ENV PATH="/root/.local/bin:$PATH"
RUN poetry --version
RUN poetry new foobar
WORKDIR foobar
RUN poetry add pycowsay
RUN poetry run pycowsay 'Hello world!'
```

**Comment by SpangleLabs** [comment]
That works!
Ahh heck, I was sure I had tried with an `ENV` line there, and had no luck. Had burnt way too much time on this
Thank you so much!

Though, doesn't work on alpine, not sure why, but happy to accept whatever works at this point

**Comment by caniko** [comment]
Created a [request](https://forums.docker.com/t/request-docker-images-with-python-poetry/122509) on Docker Hub to create poetry-based images, please support!

**Comment by akozyreva** [comment]
> Possibly try this, if you are trying to install it via `Dockerfile`
> 
> ```
> # install poetry
> RUN pip install poetry
> RUN poetry config virtualenvs.create false
> RUN poetry install --no-dev
> ```
According official documentation, it's not recommended to use `pip` for poetry installation

**Comment by mhassan5809** [comment]
> Docker context is different to shell context, you need to use ENV and WORKDIR:
> 
> ```
> FROM python:3.10
> RUN set -xe
> RUN curl -sSL https://install.python-poetry.org | python3 - --git https://github.com/python-poetry/poetry.git@master
> ENV PATH="/root/.local/bin:$PATH"
> RUN poetry --version
> RUN poetry new foobar
> WORKDIR foobar
> RUN poetry add pycowsay
> RUN poetry run pycowsay 'Hello world!'
> ```

in case FROM python:3.10-slim not works but FROM python:3.10 works
