### ISSUE TITLE
Failed User Installs on 1.2

### ISSUE THREAD

**Issue by HassanAbouelela** [python-poetry/poetry#4866]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**:  Windows 10, Debian Bullseye (`python:3.9-slim` docker image)
- **Poetry version**:  1.2.0a2 and master
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: It's mostly meaningless, but [here](https://gist.github.com/HassanAbouelela/2448369c96e09c56f5cdd78e98fed587). Docker reproduction included as well.

## Issue

When running poetry in an environment where `PIP_USER` is set to True, poetry 1.2+ will attempt to run pip with both `--user` (implicit) and `--prefix` (explicit), generating an unresolvable error. In versions prior to 1.2, `prefix` was not set. Note that I also disable virtualenvs.

The dockerfile reproduction demonstrates the problem, and shows that it was not present prior to 1.2.

I believe the correct behavior in this scenario should be skipping the `--prefix` flag. Perhaps that can be done by checking for the environment variable?

**Comment by HassanAbouelela** [comment]
@python-poetry/triage This issue has been sititng for a while, but I believe it should be relatively easy to fix cleanly (see attached patch). Could this be triaged and I get assigned? Thanks

```patch
Index: src/poetry/utils/env.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/poetry/utils/env.py b/src/poetry/utils/env.py
--- a/src/poetry/utils/env.py	(revision fb13b3a676f476177f7937ffa480ee5cff9a90a5)
+++ b/src/poetry/utils/env.py	(date 1649018164762)
@@ -1124,6 +1124,7 @@
         self._is_windows = sys.platform == "win32"
         self._is_mingw = sysconfig.get_platform().startswith("mingw")
         self._is_conda = bool(os.environ.get("CONDA_DEFAULT_ENV"))
+        self._is_user_install = bool(os.environ.get("PIP_USER"))
 
         if not self._is_windows or self._is_mingw:
             bin_dir = "bin"
@@ -1184,6 +1185,10 @@
     def parent_env(self) -> GenericEnv:
         return GenericEnv(self.base, child_env=self)
 
+    @property
+    def is_user_install(self) -> bool:
+        return self._is_user_install
+
     def _find_python_executable(self) -> None:
         bin_dir = self._bin_dir
 
Index: src/poetry/utils/pip.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/poetry/utils/pip.py b/src/poetry/utils/pip.py
--- a/src/poetry/utils/pip.py	(revision fb13b3a676f476177f7937ffa480ee5cff9a90a5)
+++ b/src/poetry/utils/pip.py	(date 1649018664234)
@@ -29,7 +29,11 @@
     # either the virtual environment or the virtualenv package embedded wheel. Version
     # checks are a wasteful network call that adds a lot of wait time when installing a
     # lot of packages.
-    args = ["install", "--disable-pip-version-check", "--prefix", str(environment.path)]
+    args = ["install", "--disable-pip-version-check"]
+
+    if not environment.is_user_install:
+        # User install and prefix options are mutually exclusive
+        args.extend(["--prefix", str(environment.path)])
 
     if not is_wheel:
         args.insert(1, "--use-pep517")
```

Linting and testing passed on the above (technically one test `test_env_commands_with_spaces_in_their_arg_work_as_expected` failed, but that was failing before my changes).

**Comment by abn** [comment]
I suspect the fix here needs to be to drop the `PIP_USER` env var for the duration of the installer execution.

Happy to review a PR for this.

**Comment by HassanAbouelela** [comment]
I'm conflicted about that behavior. I get why'd you'd want to have poetry manage everything, but in some cases it's more convenient to have user installs, and have everything accessible. In CI for instance, it's more convenient to have everything available.

**Comment by HassanAbouelela** [comment]
The behavior of `PIP_USER` and `POETRY_VIRTUALENVS_CREATE` is slightly different. `PIP_USER` should install to site packages, which makes the application available only to the python installation. For instance, you'd be able to see it under `pip list` and can not invoke it without python. Just disabling virtualenvs installs the module to /usr/bin which means it won't be visible via something like pip list, and it can be invoked globally outside of python (in the case of the included pyproject, that means you can run `mypy` globally instead of `python -m mypy`).

**Comment by abn** [comment]
The behaviour you are describing is a side-effect if you not having `$(python -c 'import site; print(site.USER_BASE)')/bin` in your `PATH`. On most systems this is `$HOME/.local/bin`.

**Comment by HassanAbouelela** [comment]
This is on the official python docker image 😅.

**Comment by Agalin** [comment]
In our environment difference is between installing to `/usr/local/bin` (current prefix - which doesn't work in our Dockerfile due to file permissions) and `$HOME/.local/bin` (where we want to install packages).

As a workaround we're exporting to requirements file and installing through Pip but it's not a clean solution and heavily affected by various `export` bugs.

**Comment by HassanAbouelela** [comment]
@abn Now that poetry 1.2 is released, I imagine more and more people are going to stumble onto this issue. How could we move it forward?

**Comment by neersighted** [comment]
I'm not sure I understand what the use case here is -- what does `PIP_USER` offer that use of a venv doesn't? Not using venvs in containers is a fallacy -- especially in the Python ecosystem. Just because you have a 'single purpose' system doesn't mean the other constraints of Python packaging/distribution go away.

Additionally, `pip` is an implementation detail of Poetry not exposed to the end user. We are very likely to simply stop consuming pip internally in the next version or two -- so I'm not sure there's a lot of value in trying to enable this unsupported workflow (it was never something supported/tested in 1.1) when we intend to stop using pip entirely...

**Comment by neersighted** [comment]
Dupe #1214
