### ISSUE TITLE
OSError when trying to run code in a new project

### ISSUE THREAD

**Issue by OliverFM** [python-poetry/poetry#4877]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: MacOs BigSur 11.6 -- on an Apple M1.
- **Poetry version**: `1.1.12`
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: [gist](https://gist.github.com/OliverFM/b996e8b90109504afa30c6ee148646c0)

## Issue

When I try an run my python file, it fails:

```
❯ poetry run poetry_ml/main.py -vvv

  OSError

  [Errno 8] Exec format error: 'poetry_ml/main.py'

  at /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/os.py:591 in _execvpe
       587│         argrest = (args,)
       588│         env = environ
       589│
       590│     if path.dirname(file):
    →  591│         exec_func(file, *argrest)
       592│         return
       593│     saved_exc = None
       594│     path_list = get_exec_path(env)
       595│     if name != 'nt':
```

Details on the file:
```
❯ ll poetry_ml
total 16
-rw-r--r--  1 oliver  staff    22B  9 Dec 18:13 __init__.py
-rwxr-xr-x  1 oliver  staff   104B  9 Dec 18:24 main.py
```
I gave all users execute permission, since before I did that, I would get a Permission error, which seemed odd:
```
❯ poetry run poetry_ml/main.py

  PermissionError

  [Errno 13] Permission denied: 'poetry_ml/main.py'

  at /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/os.py:591 in _execvpe
       587│         argrest = (args,)
       588│         env = environ
       589│
       590│     if path.dirname(file):
    →  591│         exec_func(file, *argrest)
       592│         return
       593│     saved_exc = None
       594│     path_list = get_exec_path(env)
       595│     if name != 'nt':
```

Contents of the file:
```python
import torch

if __name__ == "__main__":
    print("hello")
    print(torch.sum(torch.tensor([1,2,3])))
```

Any help would be appreciated!

**Comment by int8** [comment]
Hi man, 

just got the same issue and I landed here - I solved it, it was  really just a silly mistake of mine, 

I believe same applies here

you run 
`poetry run main.py`  but `main.py` is not executable - what you want to do instead is: 

```python
poetry run python main.py
```

hope that helps

**Comment by finswimmer** [comment]
Hello @OliverFM,

the correct syntax is `poetry run python poetry_ml/main.py`.

fin swimmer
