### ISSUE TITLE
Specifying private repository URL via environment variable not possible

### ISSUE THREAD

**Issue by JnsLns** [python-poetry/poetry#4880]
- [ ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Debian GNU/Linux 10 (buster)
- **Poetry version**: 1.1.8

## Issue

Specifying the URL of a private repository via an environment variable does not result in a working configuration. For instance after
`export POETRY_REPOSITORIES_MYREPO=https://my-repo-url/` 
running `poetry add some_package` results in 

```
  AttributeError

  'str' object has no attribute 'get'

  at ~/.poetry/lib/poetry/installation/authenticator.py:151 in _get_credentials_for_netloc_from_config
      147│             )
      148│             if not repository_config:
      149│                 continue
      150│
    → 151│             url = repository_config.get("url")
      152│             if not url:
      153│                 continue
      154│
      155│             parsed_url = urlparse.urlsplit(url)
```

In contrast, it works without issues when specifying the URL via `poetry config`, such as
`poetry config --local repositories.myrepo https://my-repo-url/`
Meaning the repository is accessed without exceptions doing e.g. `poetry add some_package`.

I have tracked down the cause to this code
https://github.com/python-poetry/poetry/blob/master/src/poetry/config/config.py#L113-L126

It seems that the code that invokes `Config.get()` expects a dictionary such as `{url : "https://my-repo-url/"}` to be returned when `Config.get()` is called with `repositories.myrepo` as argument. And that _is_ what happens in the lower portion of `Config.get`. That code is reached only when the env variable is not set though.

When the env variable is set, the upper portion is used, which always returns a string (`'https://my-repo-url/'` in this case), leading to the exception.

**Comment by vergenzt** [comment]
I'm interested in this! I'd like to use a private enterprise PyPI mirror (which is only accessible on a VPN) in CI, but default to using the live package index from developers local machines.

**Comment by abn** [comment]
@JnsLns can you try a version `>1.2.0b2` please? This should have been resolved with recent changes.

**Comment by tilsche** [comment]
I have a similar issue, a repository that contains "secret" information in its url. That should not be in a file, but in environment variable.

I have tried it with the current **master**. Unfortunately neither using `POETRY_REPOSITORIES_XXX_URL` nor `poetry config --local repositories.xxx` does the trick for me. In both cases `poetry add` fails with `Could not find a matching version of package ...`.

**Comment by brandon-leapyear** [comment]
Note: `POETRY_REPOSITORIES_XXX_URL` and `poetry config repositories.xxx` are only for publishing packages, not downloading (see https://github.com/python-poetry/poetry/issues/6004#issuecomment-1194822105). See https://github.com/python-poetry/poetry/issues/5958 for discussion on configuring sources outside of `pyproject.toml`

**Comment by neersighted** [comment]
This doesn't reproduce for me on 1.2.x. @vergenzt and @tilsche are interested in something different -- either #5958 or #1632.
