### ISSUE TITLE
poetry 1.1.9 update selects most recent version of typing

### ISSUE THREAD

**Issue by bphunter1972** [python-poetry/poetry#4881]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**:  CentOS7
- **Poetry version**: 1.1.8
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: N/A

## Issue

My poetry 1.1.8 was installed using python 3.8.8. I'm trying to update to the latest, but moving to >=1.1.9 causes issues. 1.1.8, of course, built just fine.

Running `poetry self update --preview --vvv` tries to unnecessarily upgrade typing from 3.7.4.1 to 3.10.0.0, but this version is not available for python3.8. I believe that you will find the latest version available for 3.8 is typing-3.7.4.3.

As you can see from the following, poetry-core relies on 3.7.4.1:
`
   1: derived: typing (>=3.7.4.1,<4.0.0.0)
`

It seems to me that upon hitting this exception, poetry should be satisfied that the currently installed version is sufficient.

```
  EnvCommandError

  Command ['pip', 'install', '--no-deps', '-U', 'typing==3.10.0.0'] errored with the following return code 1, and output:
  Defaulting to user installation because normal site-packages is not writeable
  Looking in indexes: https://pypi.apple.com/simple
  ERROR: Could not find a version that satisfies the requirement typing==3.10.0.0 (from versions: 3.5.0b1, 3.5.0, 3.5.0.1, 3.5.1.0, 3.5.2.2, 3.5.3.0, 3.6.1, 3.6.2, 3.6.4, 3.6.6, 3.7.4, 3.7.4.1, 3.7.4.3)
  ERROR: No matching distribution found for typing==3.10.0.0
[poetry_typing.txt](https://github.com/python-poetry/poetry/files/7688879/poetry_typing.txt)

```

**Comment by mkniewallner** [comment]
`--preview` argument will try to install preview releases, so at the time this issue was created, I believe it would have tried to install [1.2.0a2](https://github.com/python-poetry/poetry/releases/tag/1.2.0a2).

From the [installation instructions](https://python-poetry.org/docs/master/#installation), it is noted that:
```
Poetry 1.1 series releases are not able to update in-place to 1.2 or newer series releases. To migrate to newer releases, uninstall using your original install method, and then reinstall using the [methods above](https://python-poetry.org/docs/master/#installation).
```

So the recommendation would be to uninstall Poetry, then reinstalling it following [the installation instructions](https://python-poetry.org/docs/master/#installation).
