### ISSUE TITLE
"Too many arguments" error when trying to install a dependency

### ISSUE THREAD

**Issue by hummblebee** [python-poetry/poetry#4887]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 21.10
- **Poetry version**: 1.1.12
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: [pyproject.toml](https://gist.github.com/hummblebee/fde637b8465ddcf93ccebd9aad6e6630) 

## Issue
I get an error saying "Too many arguments" when I try to install [this library](https://github.com/gateio/gateapi-python) but when I manually edit the `pyproject.toml` and add `gate-api = "^4.23.0"` to the dependencies, and run `update` it installs with no problem!

I should mention this project was created by PyCharm CE which added support for Poetry projects in version 2021.3.

Here's the output from `poetry debug -vvv`:
```
Poetry
Version: 1.1.12
Python:  3.9.7

Virtualenv
Python:         3.9.7
Implementation: CPython
Path:           /home/humblebee/.cache/pypoetry/virtualenvs/my_project-Ff_indqG-py3.9
Valid:          True

System
Platform: linux
OS:       posix
Python:   /usr
```

**Comment by clintonroy** [comment]
Please give us the exact command you used and the exact error you got.

`poetry add gate-api` works for me.

**Comment by hummblebee** [comment]
Hello @clintonroy , I was under the impression I should use `poetry install` to install dependecies (based on the [documentation](https://python-poetry.org/docs/basic-usage/#installing-dependencies)) but now I that tried `poetry add` it worked! So which one is the correct command? 

Thank you! :)

```
❯ poetry add gate-api
Using version ^4.23.0 for gate-api

Updating dependencies
Resolving dependencies... (0.9s)

Writing lock file

Package operations: 3 installs, 0 updates, 0 removals

  • Installing six (1.16.0)
  • Installing python-dateutil (2.8.2)
  • Installing gate-api (4.23.0)
```
```
❯ poetry install gate-api
Too many arguments.

```

**Comment by clintonroy** [comment]
They're both correct commands, depending on what you want to do and what state you're in.

poetry add will add a dependency to your project and install it to your activated virtual environment. poetry install will install all your dependencies and your actual project itself, into your virtual environment, creating it if necessary.

details at https://python-poetry.org/docs/basic-usage/

**Comment by hummblebee** [comment]
Thanks for clearing that up. Based on your explanation, I believe the right command for my use case is `poetry add`. I checked the documentation page you mentioned, and I'm positive I skimmed through the page and the `add` command didn't catch my eye for this scenario! Maybe we could give the `poetry add`  a special section to get more attention it deserves.

Thanks again! :)
