### ISSUE TITLE
SolverError happens when constraints can be met

### ISSUE THREAD

**Issue by DandyDev** [python-poetry/poetry#4889]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: MacOS Monterey 12.0.1
- **Poetry version**: 1.1.12
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/DandyDev/99c68d5206e01747feee09933256f4a3

## Issue

I'm trying to install SciPy through Poetry by doing `poetry add scipy` in a Poetry project that has no other dependencies installed. Poetry tries to install the latest SciPy version (1.7.3 at the time of writing) but fails with a `SolverProblemError` due to perceived incompatible constraints on the Python version.

<details>
	<summary>Here is the relevant stacktrace:</summary>
	
	  Using version ^1.7.3 for scipy
	  
	  Updating dependencies
	  Resolving dependencies...
	     1: fact: test-statsmodels is 0.1.0
	     1: derived: test-statsmodels
	     1: fact: test-statsmodels depends on scipy (^1.7.3)
	     1: selecting test-statsmodels (0.1.0)
	     1: derived: scipy (>=1.7.3,<2.0.0)
	  PyPI: No release information found for scipy-0.4.4, skipping
	  PyPI: No release information found for scipy-0.5.2, skipping
	  PyPI: No release information found for scipy-0.6.0, skipping
	  PyPI: No release information found for scipy-0.7.0, skipping
	  PyPI: No release information found for scipy-0.7.2, skipping
	  PyPI: 1 packages found for scipy >=1.7.3,<2.0.0
	     1: fact: scipy (1.7.3) requires Python >=3.7,<3.11
	     1: derived: not scipy (==1.7.3)
	     1: fact: no versions of scipy match >1.7.3,<2.0.0
	     1: conflict: no versions of scipy match >1.7.3,<2.0.0
	     1: !  scipy (>1.7.3,<2.0.0) is partially satisfied by not  scipy (1.7.3)
	     1: ! which is caused by "scipy (1.7.3) requires Python >=3.7,<3.11"
	     1: ! thus: scipy is forbidden
	     1: !  scipy (>=1.7.3,<2.0.0) is satisfied by  scipy (^1.7.3)
	     1: ! which is caused by "test-statsmodels depends on scipy (^1.7.3)"
	     1: ! thus: version solving failed
	     1: Version solving took 0.004 seconds.
	     1: Tried 1 solutions.

	[...]

	SolverProblemError

	    The current project's Python requirement (>=3.9,<4.0) is not compatible with some of the required packages Python requirement:
	      - scipy requires Python >=3.7,<3.11, so it will not be satisfied for Python >=3.11,<4.0
	  
	    Because no versions of scipy match >1.7.3,<2.0.0
	     and scipy (1.7.3) requires Python >=3.7,<3.11, scipy is forbidden.
	    So, because test-statsmodels depends on scipy (^1.7.3), version solving failed.
	  
	    at ~/.local/pipx/venvs/poetry/lib/python3.10/site-packages/poetry/puzzle/solver.py:241 in _solve
	        237│             packages = result.packages
	        238│         except OverrideNeeded as e:
	        239│             return self.solve_in_compatibility_mode(e.overrides, use_latest=use_latest)
	        240│         except SolveFailure as e:
	      → 241│             raise SolverProblemError(e)
	        242│
	        243│         results = dict(
	        244│             depth_first_search(
	        245│                 PackageNode(self._package, packages), aggregate_package_nodes
	  
	    • Check your dependencies Python requirement: The Python requirement can be specified via the `python` or `markers` properties
	  
	      For scipy, a possible solution would be to set the `python` property to ">=3.9,<3.11"

</details>

It says that SciPy requires Python `>=3.7,<3.11`, and I don't understand why that fails, given the projects Python requirement `python = "^3.9"`. The latter can be read as `>=3.9,<4.0` right? Which means any Python 3.9.x or 3.10.x should work?

**Comment by finswimmer** [comment]
Your project aims to be compatible for any version `>=3.9,<4.0` which includes 3.12, 3.13 etc. With this version scipy is explicit not   compatible. poetry doesn't care about your current environment. It cares about your project definition.

The error message already told you what you should do:

```
• Check your dependencies Python requirement: The Python requirement can be specified via the `python` or `markers` properties
  
      For scipy, a possible solution would be to set the `python` property to ">=3.9,<3.11"
```

fin swimmer
