### ISSUE TITLE
Poetry reinstall a wheel

### ISSUE THREAD

**Issue by 0mars** [python-poetry/poetry#4898]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

so I have this wheel I produced for a local package other than the main package
and I'm including it as follows
```
[tool.poetry.dependencies]
mailgun-python-sdk = { file = "lib/mailgun_python_sdk-0.3-py3-none-any.whl" }
```

it installs correctly for the first time, but how to uprade it, do I need to up the version of the wheel itself ?

**Comment by neersighted** [comment]
Yes, if you want to install a newer version, you need to build a wheel for that version and update the path reference. Hopefully that is self-evident, but if you think this needs better docs, please feel free to send a PR.
