### ISSUE TITLE
Can not install 'stylus': EnvCommandError

### ISSUE THREAD

**Issue by amhndu** [python-poetry/poetry#4903]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: OpenSUSE Tumbleweed with Python 3.8.12, also tested on Ubuntu 20.04
- **Poetry version**: 1.1.12
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/amhndu/4f2a92a1687f6dfac0e458f61e4c0d08

## Issue

I can not install [stylus](https://pypi.org/project/stylus/) with poetry on Linux. (tried on both opensuse and ubuntu). It appears to try installing some macos package and fails. Using regular `pip install stylus` however works. Also, explicitly adding the source tar.gz link works.

Steps to reproduce:
```sh
$ mkdir stylusmvp && cd stylusmvp
$ poetry init -n
$ poetry add stylus
```

Verbose logs: [here](https://gist.github.com/amhndu/a90e3faa2aaa06428935c96ba1a3f1e1)

**Comment by finswimmer** [comment]
Hello @amhndu,

seems to the same issue as in #3649.

Can you test my PR #3656?

```
pix install poetry --suffix=@fix 'poetry @ git+https://github.com/finswimmer/poetry.git@issue/3649-package-types'
poetry@fix init -n
poetry@fix add stylus
```

**Comment by amhndu** [comment]
That works! 
(Aside: had to remove that suffix flag).

Closing this issue since it's a duplicate.
