### ISSUE TITLE
PyPI recently changed their scheme, and poetry shows PackageNotFound error

### ISSUE THREAD

**Issue by jaeyoo** [python-poetry/poetry#4905]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [ ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: ubuntu18.04
- **Poetry version**: 1.1.12
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue

```
Creating virtualenv qhbmlib-y9vFc9rY-py3.8 in /home/runner/.cache/pypoetry/virtualenvs
Updating dependencies
Resolving dependencies...

  PackageNotFound

  Package pytest (6.2.4) not found.

  at ~/.local/lib/python3.8/site-packages/poetry/repositories/pool.py:149 in package
      145│                     self._packages.append(package)
      146│ 
      147│                     return package
      148│ 
    → 149│         raise PackageNotFound("Package {} ({}) not found.".format(name, version))
      150│ 
      151│     def find_packages(
      152│         self, dependency,
      153│     ):
```

after this recent PyPI PR : https://github.com/pypa/warehouse/pull/10482

**Comment by cedmt** [comment]
I had the same issue and it's resolved now. I believe it was because Pypi was down : [https://status.python.org/](https://status.python.org/). The error message could be clearer I guess.

**Comment by alex-tsukanov** [comment]
Same as @cedmt Resolved now for me

**Comment by jaeyoo** [comment]
Thank you for double checks :) Yes, I also got success again!
