### ISSUE TITLE
poetry cannot find Cython

### ISSUE THREAD

**Issue by algebravic** [python-poetry/poetry#4913]
I'm trying to install git+https://github.com/dylanpeifer/deepgroebner.git via poetry add.  I'm using poetry version 1.1.9 on MacOs Monterey, with python version 3.9.1.  When I try the poetry add on the above package I always get the error below.  I have cython installed globally, and even tried to install it via poetry add to the package, but the error persists.  Is there something special that needs to be done for cython?

PackageInfoError

  Unable to determine package info for path: /var/folders/zs/sfhqf6rs4dgdjf89wmqsc6440000gn/T/pypoetry-git-deepgroebnercnk2w2i6
  
  Fallback egg_info generation failed.
  
  Command ['/var/folders/zs/sfhqf6rs4dgdjf89wmqsc6440000gn/T/tmpowu8atq_/.venv/bin/python', 'setup.py', 'egg_info'] errored with the following return code 1, and output: 
  Traceback (most recent call last):
    File "/private/var/folders/zs/sfhqf6rs4dgdjf89wmqsc6440000gn/T/pypoetry-git-deepgroebnercnk2w2i6/setup.py", line 2, in <module>
      from Cython.Build import cythonize
  ModuleNotFoundError: No module named 'Cython'

  at ~/.poetry/lib/poetry/inspection/info.py:500 in _pep517_metadata
      496│                 try:
      497│                     venv.run_python("setup.py", "egg_info")
      498│                     return cls.from_metadata(path)
      499│                 except EnvCommandError as fbe:
    → 500│                     raise PackageInfoError(
      501│                         path, "Fallback egg_info generation failed.", fbe
      502│                     )
      503│                 finally:
      504│                     os.chdir(cwd.as_posix())

**Comment by finswimmer** [comment]
Hello,

building the package is done in a fresh temporary virtual environment. Your dependency has to provide a pyproject.toml which contains the necessary build dependencies according to [PEP 518](https://www.python.org/dev/peps/pep-0518/). Please report this to the maintainers.

fin swimmer
