### ISSUE TITLE
Poetry packages fail to install from source with pip when setuptools 60.0.0 is installed, including Poetry itself.

### ISSUE THREAD

**Issue by alkasm** [python-poetry/poetry#4915]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS 11.5.2
- **Poetry version**: Poetry version 1.1.2

## Issue

Installing poetry packages, including poetry itself, from source currently fails with the newest version of setuptools. I opened up an issue on their tracker as well with all the details.

See https://github.com/pypa/setuptools/issues/2939

Edit: Note that this issue has been resolved with setuptools 60.1.1.

Note that `poetry install` does not fail; only `pip install .`

**Comment by layday** [comment]
See https://github.com/pypa/setuptools/issues/2939#issuecomment-999040464 for what I think is happening.

**Comment by benjaminbauer** [comment]
After adding `setuptools` as an explicit `build-system` requirement in a project, I was able to install it from source again. Is this possibly a problem with some changes from poetry 1.2 bleeding into the main branch?

**Comment by jjorissen52** [comment]
I have this problem when a new version of setuptools is installed, specifically `setuptools==60.1.0`.

For me, I must explicitly pin an older version of setuptools, e.g.:
```toml
# pyproject.toml
[build-system]
requires = ["setuptools==58.3.0", "poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

This works when a project dependency must run a `setup()` command.

**Comment by edgarrmondragon** [comment]
@jjorissen52 setuptools `60.1.1` was released earlier today. That solved the issue for me 😄

**Comment by finswimmer** [comment]
Thanks a lot for reporting this @alkasm :+1:  

I followed the issue on setuptools and was glad they found out the problem was on their site :)

**Comment by rafalkrupinski** [comment]
I wish poetry had pipx as it's official installation method and kept all its deps in its own venv

**Comment by finswimmer** [comment]
> [...] and kept all its deps in its own venv

The `install-poetry.py` installer is exactly doing this.

**Comment by rafalkrupinski** [comment]
> > [...] and kept all its deps in its own venv
> 
> The `install-poetry.py` installer is exactly doing this.

Hm... I had this error and it got fixed by upgrading system-wide setuptools and virtualenv
