### ISSUE TITLE
installer doesn't put poetry executable in bin directory on windows

### ISSUE THREAD

**Issue by DetachHead** [python-poetry/poetry#4927]
- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: windows 10
- **Poetry version**: 1.1.12
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue

1. run the install script from [here](https://python-poetry.org/docs/master#windows-powershell-install-instructions)
    ```powershell
    (Invoke-WebRequest -Uri https://install.python-poetry.org -UseBasicParsing).Content | python -
    ```
2. check `%APPDATA%\Python\Scripts`
![image](https://user-images.githubusercontent.com/57028336/147010661-93cfa12d-851e-4f41-a4a8-4688840d0df2.png)

**Comment by Kaltsoon** [comment]
Isn't this a feature of the new installer? The Linux/macOS installer doesn't alter the PATH either. The docs say this:

> If this directory is not on your PATH, you will need to add it manually if you want to invoke Poetry with simply poetry.

https://python-poetry.org/docs/master/#installation

**Comment by DetachHead** [comment]
the issue isn't that the directory isn't added to the path, it's that it doesn't put the executable in that directory at all, so even when that directory is in the path it still can't find the executable.

this seems to only be an issue with the install script in the master documentation:
```powershell
(Invoke-WebRequest -Uri https://install.python-poetry.org -UseBasicParsing).Content | python -
```
but the one in the 1.1 documentation works fine:
```powershell
(Invoke-WebRequest -Uri https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py -UseBasicParsing).Content | python -

```

**Comment by Kaltsoon** [comment]
I see, my bad. Could this issue be related to https://github.com/python-poetry/poetry/issues/4845? In my case the installation URL in the docs doesn't work at all on Windows. However `(Invoke-WebRequest -Uri https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py -UseBasicParsing).Content | python -` seems to work.

**Comment by DetachHead** [comment]
yeah looks like it's the same issue, thanks
