### ISSUE TITLE
'dephell' package is deprecated: implement in Poetry import from 'requirements.txt' file

### ISSUE THREAD

**Issue by AIGeneratedUsername** [python-poetry/poetry#4929]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

Some people used https://dephell.readthedocs.io/cmd-deps-convert.html, but it is deprecated and not maintained now.

Importing packages from 'requirements.txt' file seems like a very basic and critical functionality for Poetry. I just wonder why it was not implemented yet.

People often have multiple projects with dozens of packages in every 'requirements.txt" file. Manually adding packages one by one is just madness :)

Remember, "requirements.txt" is not just a list of packages: it also may have comments, some conditions, etc. 

**It will be great to have at least a simple basic functionality that strips versions, comments, conditions in a "requirements.txt" file, and add all packages.**

**Comment by david-fortini** [comment]
something like this is useful to start with
```
cat requirements.txt|xargs poetry add
```
[More info this so post](https://stackoverflow.com/questions/62764148/how-to-import-requirements-txt-from-an-existing-project-using-poetry)

**Comment by abn** [comment]
This is probably better implemented in a plugin. However, Poetry add now supports PEP 508 strings.

```console
$ poetry add --lock 'aiohttp==3.8.1 ; python_version >= "3.7" and python_version < "4.0"'
Creating virtualenv foobar in /tmp/foobar/.venv

Updating dependencies
Resolving dependencies... (0.2s)

Writing lock file
$ cat pyproject.toml | grep aiohttp
aiohttp = {version = "3.8.1", markers = "python_version >= \"3.7\" and python_version < \"4.0\""}
```
