### ISSUE TITLE
installer script deletes existing contents of $POETRY_HOME/venv without warning

### ISSUE THREAD

**Issue by wouterel** [python-poetry/poetry#4934]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: MacOS 12.1 (Monterey)
- **Poetry version**: 1.1.12
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: not applicable

## Issue
The installer script from https://install.python-poetry.org contains a try-except-else block (lines 580-599) which in the very last line of the else block removes $POETRY_HOME/venv.save . The script reaches this line upon successful installation (after the contents of the with-block that uses the VirtualEnvironment have been successfully executed), so that the original contents of $POETRY_HOME/venv, which had been saved as $POETRY_HOME/venv.save at the beginning of the process, are now removed after all, negating the idea of having them saved in the first place.

I went through the process a few times in a debugger to establish the above. I would suggest a fix if I had any idea why the shutil.rmtree is there in the first place. I cannot think of a reason why one would ever want to delete the saved old contents of this directory. So for me deleting the three lines of this else-block would fix this. But I'll gladly leave the decision for the best solution to you.

I would like to add that this is a pretty nasty bug. Deleting existing files without warning is, I would say, a feature no installer scripts should have. I actually found this out because I was setting $POETRY_HOME to the directory under which I keep all my virtual environments, for which I happen to also use the "venv" name as a convention, so the result of this was that all my virtual environments were gone.

I could file this as a separate issue but since it's so closely related I'll say it here: Even if you fix the issue just described, there is another place where the installer script removes existing files without warning: If $POETRY_HOME/venv and $POETRY_HOME/venv.save both already exist (not unlikely if someone executes the installer script several times), the contents of the latter will also be removed without warning in line 577.

In case it might matter: I'm using Python 3.9.9 (installed via macports).

**Comment by finswimmer** [comment]
Hey @wouterel,

> I would like to add that this is a pretty nasty bug.

I don't see why this should be a bug. The installer script temporary saves the current installation to be able to restore it, if something get wrong during another run of the installation. Once the installation was successful this temporary backup is no longer needed and gets removed. Why it shouldn't?

fin swimmer

**Comment by wouterel** [comment]
OK maybe my use of the term "bug" presumed too much about the intentions of the programmer. But it's still true that
- The instructions tell the user they can set $POETRY_HOME to indicate where they want poetry installed.
- The instructions do not warn the user that part of the existing contents of $POETRY_HOME will be deleted without warning, nor do they advise the user to never set $POETRY_HOME to a directory that already exists.
- The install script deletes whatever the user had in $POETRY_HOME/venv (by first saving it somewhere but then deleting the saved stuff before the user gets a chance to intervene).

I agree this could be called "not a bug". But I'd still call it an unwanted feature. Installer scripts that delete user's existing files without warning would seem a big no-no to me. I see what you mean with "once the installation was succesful the temporary backup is no longer needed", but that argument assumes that whatever was in $POETRY_HOME/venv was a previous attempt at installing poetry, which is an assumption that is not guaranteed to be correct (it wasn't for me, when I discovered this issue two days ago).

Anyway, the cases in which this goes wrong are rare, so I understand if you decide not to change the workings of the installer script, but then at least adding something to the documentation about never setting $POETRY_HOME to anything that already contains files might be a nice idea.

**Comment by finswimmer** [comment]
Closing this as a non-issue. If you still think the current behavior should be changed/improved please open a new issue in https://github.com/python-poetry/install.python-poetry.org
