### ISSUE TITLE
The Poetry configuration is invalid: Additional properties are not allowed ('group' was unexpected) with cattrs

### ISSUE THREAD

**Issue by sandrotosi** [python-poetry/poetry#4938]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Debian unstable
- **Poetry version**: 1.1.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://github.com/python-attrs/cattrs/blob/main/pyproject.toml#L29

hello, when installing cattrs with poetry, this exception is triggered:

```
$  poetry debug

Poetry

  RuntimeError

  The Poetry configuration is invalid:
    - Additional properties are not allowed ('group' was unexpected)
  

  at /usr/lib/python3/dist-packages/poetry/core/factory.py:43 in create_poetry
       39│             message = ""
       40│             for error in check_result["errors"]:
       41│                 message += "  - {}\n".format(error)
       42│ 
    →  43│             raise RuntimeError("The Poetry configuration is invalid:\n" + message)
       44│ 
       45│         # Load package
       46│         name = local_config["name"]
       47│         version = local_config["version"]
root@zion:/build/python-cattrs-1.9.0# 
```

this is caused by `[tool.poetry.group.dev.dependencies]` in [cattrs pyproject.toml](https://github.com/python-attrs/cattrs/blob/main/pyproject.toml#L29), but this should be supported, for example as part of the tests in poetry repo: https://github.com/python-poetry/poetry/blob/5814e335221047bbd5ca4d7def6994acc0a9c1ca/tests/console/commands/test_init.py#L162

the issue goes away if `[tool.poetry.group.dev.dependencies]` is converted to something like `[tool.poetry.dev-dependencies]`

**Comment by finswimmer** [comment]
Hello @sandrotosi,

dependency groups are only available from the current preview release (1.2.0a2) of poetry onwards.

fin swimmer

**Comment by sandrotosi** [comment]
thanks! the `poetry-core>=1.0.0` defined by cattrs is not strict enough, thanks for letting me know!

**Comment by eltbus** [comment]
Hi,

I'm running into this same issue. I'm trying to use the features announced here: https://python-poetry.org/blog/announcing-poetry-1.2.0a2/

Installed the latest version using:
```
curl -sSL https://install.python-poetry.org | python3 - --git https://github.com/python-poetry/poetry.git@master
```

Version check
```
$ poetry --version
Poetry (version 1.2.0a2)
```

The error:
```
  NoSuchOptionException

  The option "--default" does not exist

  at ~/.local/lib/python3.8/site-packages/cleo/io/inputs/argv_input.py:270 in _add_long_option
      266│         )
      267│
      268│     def _add_long_option(self, name: str, value: Any) -> None:
      269│         if not self._definition.has_option(name):
    → 270│             raise NoSuchOptionException(f'The option "--{name}" does not exist')
      271│
      272│         option = self._definition.option(name)
      273│
      274│         if value is not None and not option.accepts_value():
```
I used these features before, but they no longer work.


Also, new options are not show in the help.
```
$ poetry export -h

Description:
  Exports the lock file to alternative formats.

Usage:
  export [options]

Options:
  -f, --format=FORMAT     Format to export to. Currently, only requirements.txt is supported. [default: "requirements.txt"]
  -o, --output=OUTPUT     The name of the output file.
      --without-hashes    Exclude hashes from the exported file.
      --dev               Include development dependencies.
  -E, --extras=EXTRAS     Extra sets of dependencies to include. (multiple values allowed)
      --with-credentials  Include credentials for extra indices.
  -h, --help              Display help for the given command. When no command is given display help for the list command.
  -q, --quiet             Do not output any message.
  -V, --version           Display this application version.
      --ansi              Force ANSI output.
      --no-ansi           Disable ANSI output.
  -n, --no-interaction    Do not ask any interactive question.
      --no-plugins        Disables plugins.
  -v|vv|vvv, --verbose    Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug.
```

**Comment by Ashad001** [comment]
> 

Hey, Do you remember where did you access the file?
