### ISSUE TITLE
Exclude `.venv` from backups when it's not in a cache directory

### ISSUE THREAD

**Issue by probablykasper** [python-poetry/poetry#4948]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request
By default `.venv` folders are in `~/Library/Caches`, but they can also be stored in project folders using the `virtualenvs.in-project` config option. When this happens, cache is being stored in a non-standard location, so it makes sense to let backup solutions know that it should be excluded from backups.

Rust's package manager already does this, and Node.js' package manager is planning to add it. My PR #4599 implements this for Poetry, but there are some mixed opinions so I'm opening this issue for it.

**Comment by reitzig** [comment]
I agree with this, although I don't know if there's a truly effective, cross-plattform solution for this.

I'll note that [cachedir](https://bford.info/cachedir/) stands as a proposal, and at the very least a marker-file approach is supported by all backup software I've encountered (and even plain `tar`).

**Comment by probablykasper** [comment]
`CACHEDIR.TAG` seems to be the best you can get. Rust supports this as well

**Comment by finswimmer** [comment]
Resolved by #4599

**Comment by reitzig** [comment]
@finswimmer How is this solved by that PR for any platform that's _not_ MacOS?
