### ISSUE TITLE
documentation hover menu sometimes bugs out

### ISSUE THREAD

**Issue by DetachHead** [python-poetry/poetry#4954]
microsoft edge 96.0.1054.62
![asdf](https://user-images.githubusercontent.com/57028336/147726592-1a617f6a-99f1-486d-ba18-bb8a28ba185e.gif)

**Comment by finswimmer** [comment]
The website has undergo several improvements since this was reported. I'm not able to reproduce this today. That's why I close it.

Feel free to leave a comment if you disagree.

fin swimmer

**Comment by DetachHead** [comment]
@finswimmer it's still happening for me. try moving your mouse real quickly on and off the documentation link, that seems to consistently reproduce the issue
