### ISSUE TITLE
Duplicate name while building wheel of packages

### ISSUE THREAD

**Issue by I-love-study** [python-poetry/poetry#4960]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**:  Windows11
- **Poetry version**:  1.1.12
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**:  https://github.com/I-love-study/graiax-silkcoder/blob/6791fe239c3872a6a2c109b3e5ab91245c91c87a/pyproject.toml

## Issue

Hello, I try to use poetry to build and publish my packages(which have c extension in it).
But when I try to build wheel. It'll warn me `Duplicate name`
<img width="662" alt="image" src="https://user-images.githubusercontent.com/39652142/147827963-8deccbdb-cfad-4bef-bbc1-a654a4ae2c64.png">

And when I check the `.whl` file. I'm surprised that all the `.py` file have a exactly the same file in it(including name)
![image](https://user-images.githubusercontent.com/39652142/147828243-f16e4d66-60b6-4157-a03c-4c7044b28a02.png)

I don't know how to solve this problem so I open a issue to ask.
And my package is in here
https://github.com/I-love-study/graiax-silkcoder/blob/6791fe239c3872a6a2c109b3e5ab91245c91c87a

Sorry for my poor English because I'm not a native english speaker.

**Comment by dimbleby** [comment]
I cloned that repository at that commit, and `poetry build` today does not reproduce this problem

**Comment by dimbleby** [comment]
previous failure to reproduce was likely because I was not on Windows: however this looks like it was #7505 and therefore now _has_ been fixed for real.
