### ISSUE TITLE
Missing return for link.is_wheel==True

### ISSUE THREAD

**Issue by Anselmoo** [python-poetry/poetry#4966]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

- **OS version and name**: macOS:latest
- **Poetry version**: **1.1.12**
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue

According to PR #4962, there is the question left, if `pass` should not be replaced by a `return`. This would be also consistent with the typing definition `Optional[Link]`.

https://github.com/python-poetry/poetry/blob/1aa4d5b8b0114baa9e878e5692addbebb62c3e72/src/poetry/installation/chef.py#L44-L47

At the moment 
```python 
archives = self.get_cached_archives_for_link(link)
``` 
will be always excetuded.

**Comment by Anselmoo** [comment]
@finswimmer issue is assigend

**Comment by finswimmer** [comment]
Thanks @Anselmoo :+1: I've asked the other maintainers to have a look onto the PR, because I cannot estimate the impact of this change (Even if I guess it's correct).
