### ISSUE TITLE
Default python dependency version is too broad and should restrict to current Python minor version only

### ISSUE THREAD

**Issue by Jubijub** [python-poetry/poetry#4975]
- [ x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [ x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Archlinux 5.15.10-arch1-1 with python 3.10.1
- **Poetry version**: 1.1.12
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/Jubijub/0b2afa6fcb58f2d6995aab8f07504670

### Steps to reproduce

- `poetry new /data/Projects/testPoetry`
- it creates /data/Projects/testPoetry with the default `pyproject.toml` (see Gist above)
- `poetry add scipy -vvv`

### actual behaviour 
scipy install fails due to python version mismatch, because current scipy package expects the current 3.10 version to be installed, and not the next release (3.11)

```shell
Using virtualenv: /data/Projects/.virtualenvs/virtualenvs/testpoetry-jdNS9vbq-py3.10
PyPI: No release information found for scipy-0.4.4, skipping
PyPI: No release information found for scipy-0.5.2, skipping
PyPI: No release information found for scipy-0.6.0, skipping
PyPI: No release information found for scipy-0.7.0, skipping
PyPI: No release information found for scipy-0.7.2, skipping
PyPI: 49 packages found for scipy *
Using version ^1.7.3 for scipy

Updating dependencies
Resolving dependencies...
   1: fact: testpoetry is 0.1.0
   1: derived: testpoetry
   1: fact: testpoetry depends on scipy (^1.7.3)
   1: fact: testpoetry depends on pytest (^5.2)
   1: fact: testpoetry depends on pytest (^5.2)
   1: selecting testpoetry (0.1.0)
   1: derived: pytest (>=5.2,<6.0)
   1: derived: scipy (>=1.7.3,<2.0.0)
PyPI: 15 packages found for pytest >=5.2,<6.0
PyPI: No release information found for scipy-0.4.4, skipping
PyPI: No release information found for scipy-0.5.2, skipping
PyPI: No release information found for scipy-0.6.0, skipping
PyPI: No release information found for scipy-0.7.0, skipping
PyPI: No release information found for scipy-0.7.2, skipping
PyPI: 1 packages found for scipy >=1.7.3,<2.0.0
   1: fact: scipy (1.7.3) requires Python >=3.7,<3.11
   1: derived: not scipy (==1.7.3)
   1: fact: no versions of scipy match >1.7.3,<2.0.0
   1: conflict: no versions of scipy match >1.7.3,<2.0.0
   1: !  scipy (>1.7.3,<2.0.0) is partially satisfied by not  scipy (1.7.3)
   1: ! which is caused by "scipy (1.7.3) requires Python >=3.7,<3.11"
   1: ! thus: scipy is forbidden
   1: !  scipy (>=1.7.3,<2.0.0) is satisfied by  scipy (^1.7.3)
   1: ! which is caused by "testpoetry depends on scipy (^1.7.3)"
   1: ! thus: version solving failed
   1: Version solving took 0.007 seconds.
   1: Tried 1 solutions.

[... removed stacktrace...]
SolverProblemError

  The current project's Python requirement (>=3.10,<4.0) is not compatible with some of the required packages Python requirement:
    - scipy requires Python >=3.7,<3.11, so it will not be satisfied for Python >=3.11,<4.0
  
  Because no versions of scipy match >1.7.3,<2.0.0
   and scipy (1.7.3) requires Python >=3.7,<3.11, scipy is forbidden.
  So, because testpoetry depends on scipy (^1.7.3), version solving failed.

```

The issue : the default `pyproject.toml` adds `python = "^3.10"` which resolves to `>=3.10<4.0` which is too broad. Granted python doesn't really follow semver as the major release number barely changes (and may never change again), and major releases are released as minor versions (3.10, 3.11, etc.... I however doubt poetry will change [Guido's mind](https://www.techrepublic.com/article/programming-languages-why-python-4-0-will-probably-never-arrive-according-to-its-creator/) on this, so out of caution Python should be restricted to the current minor version, which is de facto "the current release of Python".
The current setting practically says : "support any python future release for the foreseable future" which IMHO defeats the point of using Poetry.

### Expected behaviour
The default version should be set as `~3.10` to restrict to the current Python "major" release.
Changing the `pyproject.toml` as suggested removes all issues to install numpy, scipy, seaborn and jupyterlab with no error message

### Related
This could help to fix https://github.com/python-poetry/poetry/issues/4316 which is related.

**Comment by finswimmer** [comment]
Hello @Jubijub,

you are right that Python itself doesn't follow SemVer. However, the breaking changes between between python minor versions are usually rare and a broad range of python versions are available one can test the code against. Furthermore there are a lot of discussions on the python community if upper caps for python should be supported at all, e.g. https://discuss.python.org/t/requires-python-upper-limits/12663

So Poetry's default to cap by the next major version is a good compromise. You are free to edit your `pyproject.toml` as you like.

This is why there are no plans to change this.

fin swimmer

**Comment by Jubijub** [comment]
I understand, although this has as a consequence that Poetry is the sole "environment manager" between Conda, Pip, and Pipenv to fail with its current default to install a basic data science environment (ie pandas). Yes there is a workaround (editing `pyproject.toml` ) but identifying the problem is not necessarily trivial either given the error messages
