### ISSUE TITLE
Copy to clipboard buttons for codes snippets in the docs(📚)

### ISSUE THREAD

**Issue by KotlinIsland** [python-poetry/poetry#4981]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

When I went to the poetry website I was presented with these massive commands with scrollbars and everything!
# 😳
![image](https://user-images.githubusercontent.com/65446343/148180881-57f5a69f-4d8c-436a-8ab6-8473769d1b36.png)

I had to copy paste the command manually and when I pasted it into my shell I got a really serious warning that I should think again.
# 😳
![image](https://user-images.githubusercontent.com/65446343/148181960-fe2edcae-4e83-4eab-b9fd-d4c071f8d870.png)

After some investigation I found out the the warning message wasn't regarding virus's or Log4Shell vulnerabilities, but was in fact that copy pasting from the website has accidentally captured a whole bunch of unintended characters/whitespace and other such things 😵😵😵😵😵.

Could you please add a copy to clipboard 📋 button to the commands in the docs. 😁😁😁😁😁

# 😁📋🚀🚀🚀🚀🚀

**Comment by Secrus** [comment]
Closing this, in favour of #5619 as it provides more info on how to handle the task to be done.
