### ISSUE TITLE
Is a new 1.2.0 prerelease version planned anytime soon?

### ISSUE THREAD

**Issue by eaplatanios** [python-poetry/poetry#4984]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Issue

Is a new 1.2.0 prerelease version planned anytime soon?

I'm mainly asking because I'm interested in [this fix](https://github.com/python-poetry/poetry/pull/4549) which has been merged into main. Without it, using the current Poetry 1.2.0 prerelease on Windows is a bit of a pain as I have to keep deleting the artifacts folder.

**Comment by tfishr** [comment]
#3516 is another critical fix that needs to be in a release as soon as possible.

**Comment by coderanger** [comment]
Would be great to get #3516 in (pre)release, our cloud CI boxes have enough cores that we are hitting PyPI connection limits if we leave parallel workers enabled but without them things are very slow :-/

**Comment by radoering** [comment]
Resolved by #5280.
