### ISSUE TITLE
`authors` is a required property but is not reported as such on `poetry install`

### ISSUE THREAD

**Issue by KotlinIsland** [python-poetry/poetry#4990]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows 10
- **Poetry version**: Poetry (version 1.2.0a2)                                  
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**:
```toml
[tool.poetry]
```

## Issue

```bash
> poetry install

  RuntimeError

  The Poetry configuration is invalid:
    - 'name' is a required property
    - 'version' is a required property
    - 'description' is a required property

[snippet removed]
```

The docs say that authors is a required property:
![image](https://user-images.githubusercontent.com/65446343/148331213-908375f9-5cbb-4c97-ae19-1be815f75b87.png)

When you add name, version, and description, and run again you get a more less informative error:
```bash
> poetry install

  NonExistentKey

  'Key "authors" does not exist.'

[snippet removed]
```

**Comment by mkniewallner** [comment]
This is not on the same command, but the root cause should be the same as for https://github.com/python-poetry/poetry/issues/4303, so this is probably a duplicate.

The isssue is on [poetry-core](https://github.com/python-poetry/poetry-core), and a PR (https://github.com/python-poetry/poetry-core/pull/99) exists to fix the issue.

**Comment by KotlinIsland** [comment]
@mkniewallner Thanks! this does look like a duplicate, I'll add a comment to that pr so that `poetry install` is tested in that pr.
