### ISSUE TITLE
(🐞) `deactivate`-ing a `poetry shell` doesn't work (on windows?)

### ISSUE THREAD

**Issue by KotlinIsland** [python-poetry/poetry#4993]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows 10
- **Poetry version**: Poetry (version 1.2.0a2)
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 
```toml
[tool.poetry]
name = "test"
version = "1"
description = "test"
authors = []
```

## Issue
When I am in a shell created by `poetry shell` the `deactivate` command doesn't deactivate the env.

> To deactivate the virtual environment without leaving the shell use `deactivate`.
\- https://python-poetry.org/docs/basic-usage#activating-the-virtual-environment

```bash
> poetry shell
Spawning shell within C:\Users\amongus\AppData\Local\pypoetry\Cache\virtualenvs\test-O3eWbxRl-py3.10
> (Get-Command python).Path
C:\Users\amongus\AppData\Local\pypoetry\Cache\virtualenvs\test-O3eWbxRl-py3.10\Scripts\python.exe
> deactivate
> (Get-Command python).Path
C:\Users\amongus\AppData\Local\pypoetry\Cache\virtualenvs\test-O3eWbxRl-py3.10\Scripts\python.exe
> exit
> (Get-Command python).Path
C:\Users\amongus\AppData\Local\Programs\Python\Python311\python.exe
```

**Comment by coconutattitude** [comment]
I also have this error, when I run which python it gives me the path to virtual environment and when I run "deactivate" I get "deactivate: command not found"
