### ISSUE TITLE
poetry cache clear doesn't work in non interactive mode

### ISSUE THREAD

**Issue by ni-fgenois** [python-poetry/poetry#4998]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows 10 (probably for other platforms too)
- **Poetry version**: 1.1.12

## Issue

When running  `poetry cache clear -n FEED_NAME --all` (note the `-n` flag) it doesn't clear the cache
Expected : When `-n` is specified, the clearing of the cache should be executed, not skipped.
Workaround : `echo yes | poetry cache clear --all FEED_NAME`

(Thanks for maintaining this tool 😃)

**Comment by branchvincent** [comment]
Thanks for filing! I just fixed this via #6338
