### ISSUE TITLE
Installing a package with extras only installs the package depencencies when run in a 3.10 venv

### ISSUE THREAD

**Issue by provinzkraut** [python-poetry/poetry#5010]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 20.04.3
- **Poetry version**: 1.2.0a2
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/provinzkraut/6347124cdbb33e8e584cf6a3acdeb3c8
- **Python version**: 3.10.0

## Issue

When adding a package with extras (ie via `poetry add tablib[xlsx]`) poetry subsequently only install this packages' dependencies, and not the package itself. The same behavior occurs when installing from a `poetry.lock` or `pyproject.toml` with such a dependency specified.

Note that this issue only occurs when using a Python 3.10 venv.

**Comment by nandanrao** [comment]
Having the same issue, with a number of libraries (psycopg, uvicorn) on python 3.10 too.

**Comment by hmsgit** [comment]
Encountered the same issue while installing libs from internal pypi with extras.

**Comment by hmsgit** [comment]
> Encountered the same issue while installing libs from internal pypi with extras.

Looks like 1.1.13 resolved this issue.

**Comment by finswimmer** [comment]
Hello @provinzkraut,

you haven't come back to this issue for a long while. So I assume this is solved in the meantime and I can close this ticket.

Feel free to leave a comment if you disagree.

fin swimmer
