### ISSUE TITLE
Add ability to create README.md instead of README.rst

### ISSUE THREAD

**Issue by zahlman** [python-poetry/poetry#5011]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

After I use `poetry new`, the new project - as described in the documentation - contains a blank README.rst file. I greatly prefer working with Markdown and thus would like for the new project to contain a blank README.md instead. (After all, Poetry itself uses .md for its own documentation.)

Could we please at least have a configuration option and/or command-line flag for this? I would prefer not having to rename the file on first edit. Especially since I generally do a dummy initial commit before writing anything, and don't want that commit to have the wrong filename.

**Comment by finswimmer** [comment]
Hello,

this is already possible in the current preview release (1.2.0a2) by the `--readme` flag. Also the new default is then md.

```
poetry new --help       

Description:
  Creates a new Python project at <path>.

Usage:
  new [options] [--] <path>

Arguments:
  path                  The path to create the project at.

Options:
      --name=NAME       Set the resulting package name.
      --src             Use the src layout for the project.
      --readme=README   Specify the readme file format. One of md (default) or rst
  -h, --help            Display help for the given command. When no command is given display help for the list command.
  -q, --quiet           Do not output any message.
  -V, --version         Display this application version.
      --ansi            Force ANSI output.
      --no-ansi         Disable ANSI output.
  -n, --no-interaction  Do not ask any interactive question.
      --no-plugins      Disables plugins.
  -v|vv|vvv, --verbose  Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug.
```

**Comment by zahlman** [comment]
Excellent, I'll be sure to keep an eye out for the stable release then. Thanks!
