### ISSUE TITLE
Project scripts removed from pyproject.toml not removed from system on `poetry install`

### ISSUE THREAD

**Issue by pwschaedler** [python-poetry/poetry#5014]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS Big Sur 11.6.2
- **Poetry version**: 1.1.12
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: see example below

## Issue

After running `poetry install`, the current project is installed in editable mode. Along with that, any scripts from pyproject.toml are installed as well. For example, with the following in my pyproject.toml:

```toml
[tool.poetry.scripts]
bad_name = "my_package.main:main"
```

After installing, you can run `bad_name` and it'll run. However, if I then change my pyproject.toml to:

```toml
[tool.poetry.scripts]
good_name = "my_package.main:main"
```

and re-run `poetry install`, it'll install the new script, but the old one remains (and still works). The debug output notes that it installed a new script but says nothing about deleting an old one (despite checking for and deleting other old dist-info).

Relevant debug output:
```
Installing the current project: my_package (0.1.0)
  - Building package my_package in editable mode
  - Adding my_package.pth to /Users/pwschaedler/.pyenv/versions/3.10.0/envs/my_package/lib/python3.10/site-packages for /Users/pwschaedler/my_package
  - Adding the good_name script to /Users/pwschaedler/.pyenv/versions/3.10.0/envs/my_package/bin
  - Removing existing my_package-0.1.0.dist-info directory from /Users/pwschaedler/.pyenv/versions/3.10.0/envs/my_package/lib/python3.10/site-packages
  - Adding the my_package-0.1.0.dist-info directory to /Users/pwschaedler/.pyenv/versions/3.10.0/envs/my_package/lib/python3.10/site-packages
```

I tested this with setuptools and it seems their solution is just to always uninstall the entire old package and reinstall. E.g.

```
$ pip install -e .
Obtaining file:///Users/pwschaedler/test-package
  Preparing metadata (setup.py) ... done
Installing collected packages: test-package
  Attempting uninstall: test-package
    Found existing installation: test-package 0.1.0
    Uninstalling test-package-0.1.0:
      Successfully uninstalled test-package-0.1.0
  Running setup.py develop for test-package
Successfully installed test-package-0.1.0
```

Would it make sense to do something similar for poetry? From what I could find, I think the relevant code is somewhere around here:

https://github.com/python-poetry/poetry/blob/b4f13de7d9268c0b67a07783c4b87a9b512968ba/src/poetry/masonry/builders/editable.py#L48-L72

**Comment by finswimmer** [comment]
Hello @pwschaedler,

I'm able to reproduce this with Poetry 1.1.14, but not with latest version in `master`. So I assume this is solved.

fin swimmer
