### ISSUE TITLE
KeyError 'None' after doing 'poetry install'

### ISSUE THREAD

**Issue by cyberfox1** [python-poetry/poetry#5016]
- [ X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [ X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 20.04.3 LTS
- **Poetry version**: Poetry version 1.1.12
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: (https://gist.github.com/cyberfox1/e60ab7e50aa77f57c9372c6df63dfcde)

## Issue

Running poetry install with above pyproject.toml yield the error:

```
$ poetry install
Updating dependencies
Resolving dependencies... (5.2s)

  KeyError

  'None'

  at ~/dev/venv/lib/python3.8/site-packages/poetry/mixology/version_solver.py:112 in _propagate
      108│             # Iterate in reverse because conflict resolution tends to produce more
      109│             # general incompatibilities as time goes on. If we look at those first,
      110│             # we can derive stronger assignments sooner and more eagerly find
      111│             # conflicts.
    → 112│             for incompatibility in reversed(self._incompatibilities[package]):
      113│                 result = self._propagate_incompatibility(incompatibility)
      114│ 
      115│                 if result is _conflict:
      116│                     # If the incompatibility is satisfied by the solution, we use

```

**Comment by finswimmer** [comment]
Hello @cyberfox1,

I can reproduce this with poetry 1.1.12. This seems to be fixed already in the current preview release (1.2.0a2). There you get a different message.

```
SolveFailure

  Because no versions of prospector match >1.5.3,<1.5.3.1 || >1.5.3.1,<2.0.0
   and prospector (1.5.3) depends on pyflakes (>=2.2.0,<2.4.0), prospector (>=1.5.3,<1.5.3.1 || >1.5.3.1,<2.0.0) requires pyflakes (>=2.2.0,<2.4.0).
  And because prospector (1.5.3.1) depends on pyflakes (>=2.2.0,<2.4.0), prospector (>=1.5.3,<2.0.0) requires pyflakes (>=2.2.0,<2.4.0).
  Because no versions of flake8 match >4.0.1,<5.0.0
   and flake8 (4.0.1) depends on pyflakes (>=2.4.0,<2.5.0), flake8 (>=4.0.1,<5.0.0) requires pyflakes (>=2.4.0,<2.5.0).
  Thus, flake8 (>=4.0.1,<5.0.0) is incompatible with prospector (>=1.5.3,<2.0.0).
  So, because test project depends on both prospector (^1.5.3) and flake8 (^4.0.1), version solving failed.
```

This means `prospector` needs a `pyflakes` version `>=2.2.0,<2.4.0` and `flake8` needs the same package but with version `>=2.4.0,<2.5.0`. This cannot be resolved.

If you remove `flake8` from the dependencies, you will see that it gets installed as a dependency by `prospector` but in version `2.3.0`.

TL,DR: It is not possible to have `prospector` and `flake8` in its latest version at the same time.

fin swimmer
