### ISSUE TITLE
Code Quality: Incremental adoption of mypy type checks

### ISSUE THREAD

**Issue by finswimmer** [python-poetry/poetry#5017]
`poetry` and `poetry-core` are full type annotated and checking types by mypy is prepared. However these checks are deactivated for most of the modules.

In this ticket I like to invite everybody to pick one or more modules in `poetry` and `poetry-core` and fix errors reported by mypy. Please link any PR you are starting to this issue. 

In process:

* [x] https://github.com/python-poetry/poetry-core/pull/253
* [ ] https://github.com/python-poetry/poetry/pull/5262
* [ ] https://github.com/python-poetry/poetry/pull/5260
* [x] https://github.com/python-poetry/poetry/pull/5258
* [x] https://github.com/python-poetry/poetry/pull/5255
* [x] https://github.com/python-poetry/poetry/pull/5399
* [x] https://github.com/python-poetry/poetry/pull/5402

**Comment by dimbleby** [comment]
@finswimmer can I suggest that you'll likely get better engagement with this sort of thing if maintainers are able to merge the PRs reasonably promptly?  I know that I would much more likely have felt encouraged to continue the work of https://github.com/python-poetry/poetry-core/pull/253 if I saw it being committed.

**Comment by finswimmer** [comment]
Hello @dimbleby,

I'm one of the maintainers (just if you haven't know it). I absolutely agree with your sentiment that reacting on a PR in short time would get better engagement. But unfortunately this is not always possible. I think you already know it. We are all doing this in our free time. And sometimes one has to decide whether to review a PR a comment on some of the 30-50 new issues/questions/feature request per week. Some reviews require also discussion between the maintainers, which takes time.

If you feel that something takes to long, please ping us in the isssue/PR or on the discord server.

fin swimmer

**Comment by dimbleby** [comment]
I intend no upset, I'm here because I think poetry is a good thing, and I'm nothing but grateful to those who've got us this far.  Please be assured that I am not trying to knock or discourage anyone, my apologies if it seemed otherwise.

But yeah, my experience is that contributing to poetry generally is a slow business.  Probably #4595 would have been a better place to talk about it though.

**Comment by KrakenBite** [comment]
Hi! I would like to work on this issue as I am interested in adoption of mypy. Can I just start?

**Comment by abn** [comment]
@KrakenBite this is already under way. I'd recommend you pick a module or test ignored (https://github.com/python-poetry/poetry/blob/master/pyproject.toml#L113) and fix it. Don't try to do it all in a single PR that's hard to review. :)

**Comment by KrakenBite** [comment]
> @KrakenBite this is already under way. I'd recommend you pick a module or test ignored (https://github.com/python-poetry/poetry/blob/master/pyproject.toml#L113) and fix it. Don't try to do it all in a single PR that's hard to review. :)

Sure, will try that! Thanks for your fast reply, have a nice day/evening :)

**Comment by tarun-jethwani** [comment]
Hi @abn, I would also like to work on this issue, infact started working on it, I am a first time contributor to poetry, have read already read that Contributing.md guidelines and familiar, I would like to submit PR one per module out of all the approx. 25 modules listed under **[[tool.mypy.overrides]]** , for starting I would like to pick up this "**poetry.console.application**", 

I will also try to submit PR with only closely related changes and will not try not to do too much at once in single PR, I will first try to submit a Draft PR also

Please allow me to work on this issue

Thanks

**Comment by tarun-jethwani** [comment]
Hi @abn, @finswimmer @branchvincent , I will take up poetry.mixology to solve for myoy errors, as there is already an open PR for poetry.console

**Comment by anthonymichaelclark** [comment]
[Link](https://github.com/python-poetry/poetry/pull/5399) to PR for `password_manager`

**Comment by tarun-jethwani** [comment]
@branchvincent  please find my PR [https://github.com/python-poetry/poetry/pull/5402] - fix for **mypy errors in **poetry.mixology** package**

**Comment by tarun-jethwani** [comment]
Hi @abn , @finswimmer , @branchvincent @dimbleby , Please approve my PR [https://github.com/python-poetry/poetry/pull/5402]() pending since yesterday, I have completed all the required changes

**Comment by tarun-jethwani** [comment]
Hi @abn , @finswimmer , @branchvincent , I have resolved merge conflicts in this PR [fix mypy errors for poetry.mixology ](https://github.com/python-poetry/poetry/pull/5402), please review this PR

**Comment by dimbleby** [comment]
open typechecking MRs (list may not be complete) include

- https://github.com/python-poetry/poetry/pull/5485
- https://github.com/python-poetry/poetry/pull/5464
- https://github.com/python-poetry/poetry/pull/5402
- https://github.com/python-poetry/poetry-core/pull/331
- https://github.com/python-poetry/poetry-core/pull/274

**Comment by Secrus** [comment]
As of today, only `poetry.utils.env` is left to be properly typed. Good job everyone!

**Comment by Secrus** [comment]
This is now completed.
