### ISSUE TITLE
Poetry tries to install win32 dependency on Linux in a project with a default private repository and fails

### ISSUE THREAD

**Issue by ido50** [python-poetry/poetry#5027]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Arch Linux
- **Poetry version**: 1.1.12
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/ido50/693356526a48dbdc814908517472cf0e

## Issue
I have a project that can only install dependencies from a private repository containing mirrors of projects from PyPI. This project depends on the [docker](https://pypi.org/project/docker/) package. This dependency, in turn, depends on `pywin32`, but only on Windows systems. Yet, when I use `poetry install` to install dependencies for the project, it fails because poetry cannot resolve the pywin32 dependency (which doesn't exist in the private repository at all, as it only contains linux packages).

The linked gist includes both the output of `poetry install -vvv` and the contents of pyproject.toml. Some non-relevant information has been redacted.

Thanks!

**Comment by ido50** [comment]
I was able to workaround this issue by forcing the private repository to have `pywin32`. The `poetry install` command actually downloaded the win32 wheel from the repository, though I do not know if it did anything with the downloaded wheel.

**Comment by dimbleby** [comment]
Not a bug, poetry builds cross-platform lockfiles and so if your project depends on docker and docker depends on pywin32, then poetry has to explore that part of the dependency tree.

If you don't want to support windows, add suitable markers to your dependencies.

**Comment by radoering** [comment]
In addition: Poetry does not try to install the win32 dependency on Linux. It downloads the dependency to generate the lock file. (If there is no lock file, `poetry install` creates a lock file before installing anything.)
