### ISSUE TITLE
poetry-core updated pre-release

### ISSUE THREAD

**Issue by furlongm** [python-poetry/poetry#5028]
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Issue
Would be possible to make a new pre-release of poetry-core? Looks like the last one is ~5 months old and a bunch of stuff has been fixed in master since then.

Specifically waiting on this PR to be contained in a (pre-)release for a while now: https://github.com/python-poetry/poetry-core/pull/186

**Comment by radoering** [comment]
Resolved by python-poetry/poetry-core#289.
