### ISSUE TITLE
`poetry init` finds 20 packages but only shows 10

### ISSUE THREAD

**Issue by cu** [python-poetry/poetry#5033]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Pop OS 21.04
- **Poetry version**: 1.1.12
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue

When running the `poetry init` wizard to initialize a new project, the section to define dependencies will find up to 20 matches but only display 10, with no (obvious) way to see the others

```
$ poetry init -vvv

This command will guide you through creating your pyproject.toml config.

Package name [foo]:  
Version [0.1.0]:  
Description []:  
Author [<censored>, n to skip]:  
License []:  
Compatible Python versions [^3.9]:  

Would you like to define your main dependencies interactively? (yes/no) [yes] 
You can specify a package in the following forms:
  - A single name (requests)
  - A name and a constraint (requests@^2.23.0)
  - A git url (git+https://github.com/python-poetry/poetry.git)
  - A git url with a revision (git+https://github.com/python-poetry/poetry.git#develop)
  - A file path (../my-package/my-package.whl)
  - A directory (../my-package/)
  - A url (https://example.com/packages/my-package-0.1.0.tar.gz)

Search for package to add (or leave blank to continue): python
Found 20 packages matching python

Enter package # to add, or the complete package name if it is not listed: 
 [0] python101
 [1] Python123
 [2] python4
 [3] python2
 [4] python7
 [5] python9909
 [6] python-42
 [7] python42
 [8] python-geoip-python3
 [9] python-dubbo-support-python3
 > 
```

**Comment by finswimmer** [comment]
Hello @cu,

that's intended. It doesn't make sense to show all results and the user has to scroll to in endless list. Of course we could improve the message to let the user know that Poetry cuts the result.

fin swimmer

**Comment by albertogomcas** [comment]
> Hello @cu,
> 
> that's intended. It doesn't make sense to show all results and the user has to scroll to in endless list. Of course we could improve the message to let the user know that Poetry cuts the result.
> 
> fin swimmer

It does not really make sense if it refuses to take the name for the package and keeps showing the partial list

```
Search for package to add (or leave blank to continue): PyQt5
Found 20 packages matching PyQt5

Enter package # to add, or the complete package name if it is not listed:
 [0] PyQt6
 [1] PyQt6-Charts
 [2] PyQt5-stubs
 [3] pyqt4topyqt5
 [4] pyqt2waybinding
 [5] PyQt-builder
 [6] pyqt_client
 [7] vsutillib-pyqt
 [8] PyQt5Designer
 [9] pyqt5ac

 > PyQt5
Value "PyQt5" is invalid

Enter package # to add, or the complete package name if it is not listed:
 [0] PyQt6
 [1] PyQt6-Charts
 [2] PyQt5-stubs
 [3] pyqt4topyqt5
 [4] pyqt2waybinding
 [5] PyQt-builder
 [6] pyqt_client
 [7] vsutillib-pyqt
 [8] PyQt5Designer
 [9] pyqt5ac
 >
```

poetry add PyQt5 works, BTW.
