### ISSUE TITLE
`poetry init` does not restore terminal echo when exited with Ctrl+C

### ISSUE THREAD

**Issue by cu** [python-poetry/poetry#5034]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Pop OS 21.04
- **Poetry version**: 1.1.12
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue

When running `poetry init` to initialize an existing project, the package selection part of the wizard turns off terminal echo when selecting a result. If the user types Ctrl+C to exit the wizard at this point, echo is not turned back on and the user has to type `stty echo` at the shell to restore the terminal to a usable state.

Ctrl+C (`KeyboardInterrupt`) should be trapped and terminal echo should be turned on within the trap.

**Comment by finswimmer** [comment]
Hello @cu,

unfortunately I cannot follow you here. What isn't working anymore after hitting CTRL+C? My terminal is working normal after doing :thinking: 

fin swimmer

**Comment by finswimmer** [comment]
Hello,

because you haven't provide more information for a long time I assume this is issue is not relevant anymore. This is why I close this ticket. Feel free to leave a comment if you disagree.

fin swimmer
