### ISSUE TITLE
`poetry init` does not find the package if the search string is capitalized

### ISSUE THREAD

**Issue by cu** [python-poetry/poetry#5035]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Pop OS 21.04
- **Poetry version**: 1.1.12
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue

In the package selection part of the `poetry init` wizard, package selection only works reliably if you use a fully lowercase search string. If you capitalize the search string, a package matching that string will not show up in the results.

Say I want to add Flask as a dependency. The package name on this project is capitalized on PyPI. If I search for `flask`, the package will show up in the results. If I search for `Flask`, it will not.

```
$ poetry init -vvv

This command will guide you through creating your pyproject.toml config.

Package name [notes]:  
Version [0.1.0]:  
Description []:  
Author [<censored>, n to skip]:  
License []:  
Compatible Python versions [^3.9]:  

Would you like to define your main dependencies interactively? (yes/no) [yes] 
You can specify a package in the following forms:
  - A single name (requests)
  - A name and a constraint (requests@^2.23.0)
  - A git url (git+https://github.com/python-poetry/poetry.git)
  - A git url with a revision (git+https://github.com/python-poetry/poetry.git#develop)
  - A file path (../my-package/my-package.whl)
  - A directory (../my-package/)
  - A url (https://example.com/packages/my-package-0.1.0.tar.gz)

Search for package to add (or leave blank to continue): Flask
Found 20 packages matching Flask

Enter package # to add, or the complete package name if it is not listed: 
 [0] Flask-Zipper
 [1] Flask-DB
 [2] flask-beans
 [3] Flask-Sessions
 [4] Flask-SimpleACL
 [5] flask-blacklist
 [6] Flask-Shelve
 [7] flask_wifiqr
 [8] Flask-Account
 [9] Flask-OpenID
 > 
```

**Comment by finswimmer** [comment]
Hello @cu,

thanks for reporting. 

The problem are in these lines: https://github.com/python-poetry/poetry/blob/ecb030e1f0b7c13cc11971f00ee5012e82a892bc/src/poetry/console/commands/init.py#L272-L278

We should use the canonical name of `constraint["name"]` to find in "exact" match in the list of results. Because we don't do it now, the result for "Flask" isn't put in front of the result list we present to the user. Together with the fact that the result list is [cut down to 10 result](https://github.com/python-poetry/poetry/issues/5033#issuecomment-1012333004) this package is hide.

fin swimmer

**Comment by evanrittenhouse** [comment]
@finswimmer mind if I take this one?

**Comment by finswimmer** [comment]
Hey @evanrittenhouse,

yes, feel free to start working on it :+1: 

fin swimmer
