### ISSUE TITLE
`poetry lock --check` has no output

### ISSUE THREAD

**Issue by DetachHead** [python-poetry/poetry#5038]
- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: windows 10
- **Poetry version**: 1.2.0a2

## Issue
it would be nice if there was some sort of output other than just the exit code
```py
> poetry lock --check

> echo %errorlevel%
1
```

perhaps an error message like
```
Error: poetry.lock is out of date. run `poetry update` to fix it
```

**Comment by radoering** [comment]
Sounds good. I am just wondering if `poetry update` is the most suitable recommendation or if `poetry lock [--no-update]` is better suited? It seemed natural to me to call `lock` if `lock --check` failed. That way you can decide if you only want to bring `pyproject.toml` and `poetry.lock` in line (without updating already locked dependencies) or if you want to update these, too. As far as I understand, `poetry lock` is the same as `poetry update --lock`. Probably, the advantage of `poetry update` over `poetry lock` is that you don't have to call `poetry install` separately.

**Comment by artemrys** [comment]
@radoering I can take this one, it seems to be an easy change. Do we just need to add some a log here https://github.com/python-poetry/poetry/blob/335f209c2dd96cb33e75279c4a52cb25b1966bc3/src/poetry/console/commands/lock.py#L39-L44 and update / create tests?

**Comment by radoering** [comment]
@artemrys: Yes, that seems to be the correct part of the code. Tests are in [test_lock.py](https://github.com/python-poetry/poetry/blob/335f209c2dd96cb33e75279c4a52cb25b1966bc3/tests/console/commands/test_lock.py). There are also tests for other commands that already check output. You can use these tests as a guide.

Further, I think in case of success (if `poetry.lock` is consistent with `pyproject.toml`, exit code 0) there should be a message, too.
