### ISSUE TITLE
subprocess.CalledProcessError: Command '['python', 'manage.py', 'runserver']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by robert-dm** [python-poetry/poetry#5042]
- [x ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**:  Windows 11 
- **Poetry version**:  1.1.12 
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**:  https://gist.github.com/robert-dm/336596fafb4254d255313b8cc898ef6e

## Issue
Running poetry run start in this project, returns this error in Windows 11, however in Mac using same python version works fine, same code.
Tried with python 3.7, 3.8, 3.9 all with same result

```
C:\Users\rober\OneDrive\Documents\Robert\workspace\mentee\backend>poetry run start -vvv
Traceback (most recent call last):
  File "C:\Users\rober\OneDrive\Documents\Robert\workspace\mentee\backend\manage.py", line 7, in <module>
    app = create_app()
  File "C:\Users\rober\OneDrive\Documents\Robert\workspace\mentee\backend\api\__init__.py", line 80, in create_app
    from api.views import (
  File "C:\Users\rober\OneDrive\Documents\Robert\workspace\mentee\backend\api\views\messages.py", line 1, in <module>
    from os import confstr, path
ImportError: cannot import name 'confstr' from 'os' (C:\Users\rober\AppData\Local\Programs\Python\Python39\lib\os.py)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\rober\OneDrive\Documents\Robert\workspace\mentee\backend\scripts.py", line 5, in runserver
    check_call(["python", "manage.py", "runserver"])
  File "C:\Users\rober\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['python', 'manage.py', 'runserver']' returned non-zero exit status 1.


C:\Users\rober\OneDrive\Documents\Robert\workspace\mentee\backend>poetry --version
Poetry version 1.1.12
```

**Comment by eyllanesc** [comment]
@robert-dm I think the problem is not poetry. Relative paths are one of the main causes of bugs, instead of using relative paths build the absolute path (I suspect the manage.py path is not handled correctly)

**Comment by robert-dm** [comment]
> @robert-dm I think the problem is not poetry. Relative paths are one of the main causes of bugs, instead of using relative paths build the absolute path (I suspect the manage.py path is not handled correctly).
> 
> Note: Relative paths will depend on the environment (OS for example)

I think the problem is poetry in Windows.  I am able to run the project in MacOS and Ubuntu with no issues, only issue is Windows OS I can say.

**Comment by robert-dm** [comment]
I tried to run my project in MacOS - worked fine.  Tried in Ubuntu - worked fine.  Tried in Windows - throwing error detailed in this issue.

**Comment by dimbleby** [comment]
> ImportError: cannot import name 'confstr' from 'os'

`confstr` is only available on unix.  This is your bug, not poetry's.
