### ISSUE TITLE
`poetry-core` PEP 517 build with a `--no-root` option?

### ISSUE THREAD

**Issue by michaeloliverx** [python-poetry/poetry#5052]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

I have been using PEP 517 `pip install /poetry/managed/project` for a while now and it works great. I have found the need for an option similar to the `--no-root` option of `poetry install`. This option would be especially helpful in a Dockerfile where you would ideally like to install dependencies first in a separate step and then your install your own project after to take advantage of Docker's cache.

My Dockerfile currently does something like this this as a workaround:

```Dockerfile
COPY pyproject.toml poetry.lock ./
RUN mkdir app && touch app/__init__.py
RUN pip install ./

COPY src/ .
RUN pip install .
```

Without the `RUN mkdir app && touch app/__init__.py` line I get the error  `poetry.core.masonry.utils.module.ModuleOrPackageNotFound: No file/folder found for package app`.

Could `poetry-core` respect a `POETRY_NO_ROOT` environment variable?

**Comment by finswimmer** [comment]
Hello @michaeloliverx,

I'm not a docker expert, but what you are trying to achieve is not possible with `pip install /poetry/managed/project`. This would trigger to build a wheel file for the package and pass it back to `pip` so it can install the package. To build a wheel file it is necessary to include at least one file.

Please have a look at this [discussion](https://github.com/python-poetry/poetry/discussions/1879). I guess there are some solutions for you.

fin swimmer
