### ISSUE TITLE
poetry add snowflake-sqlalchemy does not complete

### ISSUE THREAD

**Issue by luiscapella** [python-poetry/poetry#5067]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Version 11.6 macOS Big Sur
- **Poetry version**: 1.1.12
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/luiscapella/65356c0071514a8fb78a6e5122a4cd7e

## Issue

When attempting to execute `poetry add snowflake-sqlalchemy`, it continues to try to resolve dependencies and does not complete. It ran for 133 mins without completing.

**Comment by artemrys** [comment]
I could not reproduce that, I have the same OS version and poetry version. What I tried:

1. Exact the same [file](https://gist.github.com/luiscapella/65356c0071514a8fb78a6e5122a4cd7e) you have in Gist and run `poetry install`, took 23 seconds to install everything.

2. Same file, but without `snowflake-sqlalchemy` dependency. Then I run `poetry install`, it took 19 seconds, then I run `poetry add snowflake-sqlalchemy`, it took 2.6 seconds to finish.

**Comment by artemrys** [comment]
@luiscapella you can share debug logs when running that command?
