### ISSUE TITLE
Please do a new release for `virtualenvs.prefer-active-python`

### ISSUE THREAD

**Issue by loynoir** [python-poetry/poetry#5072]
### Background

Archlinux user here, try to use [poetry 1.1.12](https://github.com/archlinux/svntogit-community/blob/e0b9c2968506260522e4783f145d2956b5b11986/trunk/PKGBUILD#L7) with `PYENV_VERSION=3.9.9` to solve [pyfuse3](https://github.com/libfuse/pyfuse3/issues/52) not working under latest `python 3.10.1`

### Reproduce
```sh
$ poetry config virtualenvs.prefer-active-python true --local
```

Got error
```txt
  ValueError

  Setting virtualenvs.prefer-active-python does not exist
```

### Question
Are there any alternative poetry option, other than `virtualenvs.prefer-active-python`, which can make poetry using `python 3.9.9`, while system having `python 3.10.1`?

### Else
Seems docker can be [workaround](https://github.com/libfuse/pyfuse3/issues/52)

**Comment by loynoir** [comment]
This works
```
$cat ~/.zshrc

eval "$(pyenv init --path)"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

$ python --version
Python 3.10.1
$ poetry new foobar
$ PYENV_VERSION=3.9.9 pyenv virtualenv foobar
$ cat foobar/.python-version 
3.9.9/envs/foobar
$ cd foobar
$ python --version
Python 3.9.9
$ poetry install
$ poetry shell
```

```
$ python --version
Python 3.9.9
```

**Comment by finswimmer** [comment]
Hello @loynoir,

the setting `virtualenvs.prefer-active-python` is only available in the master branch and will be available in the next preview release. There will be no backport to poetry 1.1. Here you have to use the `get-poetry.py` installer script for poetry, if you want poetry to pick up the current activated python.

As in alternative you can always run `poetry env use /path/to/python` before a `poetry install`. See [docs](https://python-poetry.org/docs/managing-environments/#switching-between-environments).

fin swimmer
