### ISSUE TITLE
[FeatureRequest] integrate with pyenv

### ISSUE THREAD

**Issue by loynoir** [python-poetry/poetry#5073]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

```sh
$ poetry new foobar {{PYTHON_VERSION}} SHELL={{SHELL}}
```

## Example
On a machine maybe **without** `pyenv` installed, but with `poetry` installed.
And system python is `3.10.1`, current shell is `zsh`

Eg

```sh
$ poetry new foobar 3.9.9 SHELL=bash
```

When do `poetry shell` later, default python is `3.9.9`, default shell is `bash`

## Why
1. I like poetry! It's amazing. Its default behavior is not going into system global, but local `virtualenv`. Very neat.

2. But famous python version manage tool `pyenv`, have a lot of things goings into global `.XXXshrc` and global environment variables. Not very neat.

3. So I request poetry integrate with pyenv. `pyenv`'s **global** shell functions and **global** environment variable, all move into **local** `virtualenv`'s shell functions and environment. 

4. Thus, user no bother to install pyenv and it's config in a global place. Neat.

## Test
 pre-feat
```sh
# Ensure user have new python.
zsh $ python --version
Python 3.10.1

# Ensure this feat works even there is no pyenv installed.
zsh $ pyenv
command not found: pyenv
# Ensure this feat works even there is no pyenv config installed.
zsh $ grep pyenv ~/.zshrc || echo OK
OK 
```

feat
```sh
zsh $ poetry new foobar 3.9.9 SHELL=bash
```

post-feat
```
zsh $ cd foobar
zsh $ poetry install

# or SHELL=bash poetry shell
zsh $ poetry shell

# Ensure not system python, and not system shell
bash $ python --version
Python 3.9.9
```

### Related
https://github.com/python-poetry/poetry/issues/5072

**Comment by finswimmer** [comment]
Hey again @loynoir,

please see my comment in https://github.com/python-poetry/poetry/issues/5072#issuecomment-1017710019

fin swimmer
