### ISSUE TITLE
Option to skip resolving locked dependencies?

### ISSUE THREAD

**Issue by vinchg** [python-poetry/poetry#5080]
Hey there, I'm relatively new to Poetry. After searching issues and documentation, I don't think this was brought up before.

While overall poetry has been a pleasant experience, my biggest gripe is how long it takes to add a new dependency (easily takes more than 10 minutes with my current project). It would be nice if there was an option to pin the previous versions in the lock file, and only resolve dependencies for anything that was newly added to pyproject.

**Comment by radoering** [comment]
How do you add a new dependency?

If you add the dependency manually in the `pyproject.toml`, you can run `poetry lock --no-update` in order to not update already locked dependencies.

If you use `poetry add`, I suppose already locked dependencies are not updated by default.

**Comment by finswimmer** [comment]
> If you use poetry add, I suppose already locked dependencies are not updated by default.

Yes, this is the case as long as the new dependency is happy with locked versions.
