### ISSUE TITLE
Scipy 1.7.3 fails with Python 3.10, but is within the dependency window

### ISSUE THREAD

**Issue by jameswinegar** [python-poetry/poetry#5093]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**:  MacOS 12.1
- **Poetry version**:  1.1.12
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**:  https://gist.github.com/jameswinegar/779bad48d2c8a40dee497ee9eed6cdff

## Issue

`python` version is ^3.10 however when trying to `poetry add scipy=1.7.3`  poetry thinks that the python version is `^3.11` effectively. 

```
PyPI: 1 packages found for scipy 1.7.3
   1: fact: scipy (1.7.3) requires Python >=3.7,<3.11
   1: conflict: scipy (1.7.3) requires Python >=3.7,<3.11
   1: !  scipy (1.7.3) is satisfied by  scipy (1.7.3)
   1: ! which is caused by "lab2 depends on scipy (1.7.3)"
   1: ! thus: version solving failed
   1: Version solving took 0.088 seconds.
   1: Tried 1 solutions.
```

```
  The current project's Python requirement (>=3.10.0,<4.0.0) is not compatible with some of the required packages Python requirement:
    - scipy requires Python >=3.7,<3.11, so it will not be satisfied for Python >=3.11,<4.0.0
```

**Comment by clintonroy** [comment]
The error message is pretty good here, I think. python ^3.10 means (>=3.10.0,<4.0.0) so yes, you are asking your package to work with pyhton3.11 (and 3.12 etc)

Restrict your python version to ~3.10.0 and scipy will be happy.

**Comment by finswimmer** [comment]
It's exactly how @clintonroy explained it. Because it's a recurrent questions I've prepared a PR for updating our FAQ: https://github.com/python-poetry/poetry/pull/5094
