### ISSUE TITLE
Add equivalent of `--copies`when creating a virtualenv.

### ISSUE THREAD

**Issue by theArtechnology** [python-poetry/poetry#5095]
- [ x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request
It would be interesting to have the `--copies` from the command `python -m venv .venv --copies`. Where the python binary inside (in this case) `.venv/bin/python` is a copy not just a symbolic link. See usage: https://docs.python.org/3/library/venv.html#creating-virtual-environments

This is useful when we a developing inside a Docker Image a doing a mapping of the `.venv` inside the docker and host (ex. on a mac). Vscode and PyCharm can easily detect the virtual environment, without the need to the container.

**Comment by finswimmer** [comment]
Hey @theArtechnology,

this is already possible in the current preview release. See here: https://python-poetry.org/docs/master/configuration/#virtualenvsoptionsalways-copy

fin swimmer
