### ISSUE TITLE
Dependency resolution much slower when adding secondary sources

### ISSUE THREAD

**Issue by anth2o** [python-poetry/poetry#5096]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Mac OS 12.0.1
- **Poetry version**: 1.1.12
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://github.com/anth2o/poetry_slow_additional_source

## Issue

Hello, `poetry lock` is much slower in my project when I add internal pypi repositories as additional sources. My issue is strongly related to [this one](https://github.com/python-poetry/poetry/issues/4113), but the main difference with mine is that I set the `secondary = True` for the additional repo.
I would have expected this secondary repo to be ignored when a dependency was found in the main  Pypi because of the `secondary = True`.
[This repo](https://github.com/anth2o/poetry_slow_additional_source) gives a reproducible example of my issue

**Comment by neersighted** [comment]
Duplicate #5096

**Comment by JacobHayes** [comment]
@neersighted this is #5096, do you mean this duplicates #5959 (or perhaps #4113)?

**Comment by neersighted** [comment]
Ah, thanks, yes, I meant #4113
