### ISSUE TITLE
Installation fails: No module named ensurepip

### ISSUE THREAD

**Issue by Tilix4** [python-poetry/poetry#5097]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 20.04
- **Poetry version**: 1.1.12

## Issue
Following install instructions, using python 3.7, the installation command `python -m pip install ensurepip` fails and the `.log` content shows:
```
/home/felix/.local/share/pypoetry/venv/bin/python: No module named ensurepip

Traceback:

  File "<stdin>", line 877, in main
  File "<stdin>", line 515, in run

```
I must mention this version of ubuntu has pythn3.8 by default and I installed 3.7 following: https://linuxconfig.org/ubuntu-20-04-python-version-switch-manager.

```bash
$ python -V 
Python 3.7.12
```

**Comment by neersighted** [comment]
Hi @Tilix4! Could you first please post the complete output and commands used to install Poetry? `ensurepip` is not part of any of the install methods, as far as I am aware.

Additionally, `ensurepip` is part of the Python standard distribution, and is expected to be present to have a functional Python. Ubuntu/Debian ship a modified Python with `pip`, the `venv` module, and `ensurepip` separated out. While we do our best to work around this, please understand that the packaging choices made by some distros make support harder as their Pythons are not shipped in the way intended by upstream.

**Comment by Tilix4** [comment]
Hi @neersighted, thanks for answering, I was following building steps from: https://openpype.io/docs/dev_build

I finally managed to make it work, I'm not sure how I could write something helpful here. AFAIK the `venv` I was trying to install `poetry` in was messed up, then I deleted it and made it from scratch again.
