### ISSUE TITLE
"X is not a supported wheel on this platform" when running on certain Docker image (e.g. `nvidia/cuda:11.3.1-cudnn8-devel-ubuntu20.04`)

### ISSUE THREAD

**Issue by ben-xD** [python-poetry/poetry#5104]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS (M1 mac) running in Docker (Ubuntu, aarch64 architecture, specifically with base image: "nvidia/cuda:11.3.1-cudnn8-devel-ubuntu20.04")
- **Poetry version**: Poetry version 1.1.12
- More details
  - `poetry run python3 --version` gives `Python 3.8.10`
  - `poetry run python3 -m pip --version` gives `pip 21.3.1 from /usr/local/lib/python3.8/dist-packages/pip (python 3.8)`
  - `uname -a` gives `Linux f8833b73788c 5.10.76-linuxkit #1 SMP PREEMPT Mon Nov 8 11:22:26 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux`
- Link of a [pyproject.toml](https://github.com/ben-xD/reproducible_example_poetry_fails_grpcio/blob/main/pyproject.toml)

You can take a look at the simplest **reproducible example** I could create in this repo - [`reproducible_example_poetry_fails_grpcio`](https://github.com/ben-xD/reproducible_example_poetry_fails_grpcio). Just clone, and run `docker compose up`, and the error should show up. The error is caused by `RUN poetry install` step, which is described below.

## Issue

My `pyproject.toml` contains grpcio

The error is:
```
  • Installing wcwidth (0.2.5): Downloading... 100%
  • Installing wcwidth (0.2.5): Installing...
  • Installing wcwidth (0.2.5)
  • Installing grpcio (1.43.0): Downloading... 100%
  • Installing grpcio (1.43.0): Installing...
  • Installing grpcio (1.43.0): Failed

  EnvCommandError

  Command ['/usr/bin/pip3', 'install', '--no-deps', '/root/.cache/pypoetry/artifacts/70/29/58/8f9ec0af4f3b8c2001879d97d9d082ca9ef00e3d9dedc0586a2a567157/grpcio-1.43.0-cp38-cp38-manylinux_2_17_aarch64.whl'] errored with the following return code 1, and output: 
  ERROR: grpcio-1.43.0-cp38-cp38-manylinux_2_17_aarch64.whl is not a supported wheel on this platform.
  

  at /etc/poetry/venv/lib/python3.8/site-packages/poetry/utils/env.py:1183 in _run
      1179│                 output = subprocess.check_output(
      1180│                     cmd, stderr=subprocess.STDOUT, **kwargs
      1181│                 )
      1182│         except CalledProcessError as e:
    → 1183│             raise EnvCommandError(e, input=input_)
      1184│ 
      1185│         return decode(output)
      1186│ 
      1187│     def execute(self, bin, *args, **kwargs):
```

## Some key points:

- This only happens in a docker **container**.
  - It does not happen on a fresh Ubuntu install without a docker container.
  - It does not happen on macOS
- This only happens when the virtualenv is **disabled**.
  - Command to disable virtualenv: `poetry config virtualenvs.create false`
  - This doesn't happen when I use a `virtualenv`.
- This has been seen in previous issues (e.g. https://github.com/python-poetry/poetry/issues/2688) but referred to older versions of Poetry - "that" bug was fixed. This issue also happens with `grpcio-testing` and `grpcio-tools`, as both depend on `grpcio`.

I would greatly appreciate some help. I've tried to give as much information as possible. Thanks in advance :)

**Comment by Byloth** [comment]
Me too, here!  
I'm experiencing your same exact problem.

I'm using `nvidia/cuda:11.6.2-cudnn8-devel-ubuntu20.04` and Poetry fails to install `Pillow` package.

It tries to install the `Pillow-9.2.0-cp38-cp38-manylinux_2_28_x86_64.whl` wheel file and fails with your exact same error.

<details>
<summary><strong>Stack trace:</strong></summary>

```
  7  /opt/poetry/venv/lib/python3.8/site-packages/poetry/installation/executor.py:203 in _execute_operation
      201│
      202│             try:
    → 203│                 result = self._do_execute_operation(operation)
      204│             except EnvCommandError as e:
      205│                 if e.e.returncode == -2:

  6  /opt/poetry/venv/lib/python3.8/site-packages/poetry/installation/executor.py:277 in _do_execute_operation
      275│             return 0
      276│
    → 277│         result = getattr(self, "_execute_{}".format(method))(operation)
      278│
      279│         if result != 0:

  5  /opt/poetry/venv/lib/python3.8/site-packages/poetry/installation/executor.py:412 in _execute_install
      410│
      411│     def _execute_install(self, operation):  # type: (Install) -> None
    → 412│         return self._install(operation)
      413│
      414│     def _execute_update(self, operation):  # type: (Update) -> None

  4  /opt/poetry/venv/lib/python3.8/site-packages/poetry/installation/executor.py:450 in _install
      448│             args.insert(2, "-U")
      449│
    → 450│         return self.run_pip(*args)
      451│
      452│     def _update(self, operation):

  3  /opt/poetry/venv/lib/python3.8/site-packages/poetry/installation/executor.py:301 in run_pip
      299│     def run_pip(self, *args, **kwargs):  # type: (...) -> int
      300│         try:
    → 301│             self._env.run_pip(*args, **kwargs)
      302│         except EnvCommandError as e:
      303│             output = decode(e.e.output)

  2  /opt/poetry/venv/lib/python3.8/site-packages/poetry/utils/env.py:1160 in run_pip
      1158│         pip = self.get_pip_command()
      1159│         cmd = pip + list(args)
    → 1160│         return self._run(cmd, **kwargs)
      1161│
      1162│     def run_python_script(self, content, **kwargs):  # type: (str, Any) -> str

  1  /opt/poetry/venv/lib/python3.8/site-packages/poetry/utils/env.py:1566 in _run
      1564│
      1565│     def _run(self, cmd, **kwargs):  # type: (List[str], Any) -> Optional[int]
    → 1566│         return super(VirtualEnv, self)._run(cmd, **kwargs)
      1567│
      1568│     def is_venv(self):  # type: () -> bool

  EnvCommandError

  Command ['/usr/bin/pip3', 'install', '--no-deps', '/root/.cache/pypoetry/artifacts/d5/ef/90/d3e7af61c9a736d9ca32bd09c4fa0ada8c54eab7dbc5a7b137a28a1302/Pillow-9.2.0-cp38-cp38-manylinux_2_28_x86_64.whl'] errored with the following return code 1, and output:
  ERROR: Pillow-9.2.0-cp38-cp38-manylinux_2_28_x86_64.whl is not a supported wheel on this platform.


  at /opt/poetry/venv/lib/python3.8/site-packages/poetry/utils/env.py:1195 in _run
      1191│                 output = subprocess.check_output(
      1192│                     cmd, stderr=subprocess.STDOUT, **kwargs
      1193│                 )
      1194│         except CalledProcessError as e:
    → 1195│             raise EnvCommandError(e, input=input_)
      1196│
      1197│         return decode(output)
      1198│
      1199│     def execute(self, bin, *args, **kwargs):

The command 'poetry install -vvv --no-dev --no-root' returned a non-zero code: 1
```

</details>

---

One thing I noticed is that if you try to install `Pillow` manually using plain `pip`, it will install `Pillow-9.2.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl` without any problem.

So, it seems, for some reason Poetry picks the wrong version of the wheel file to install... `2_28` instead of `2_17`.

---

Were you able, @ben-xD, to solve your problem, in the meantime? 🥺

**Comment by dimbleby** [comment]
@ben-xD's dockerfile builds just fine today, with poetry 1.1.14.

Adding pillow fails in the way that @Byloth describes: but switching the dockerfile to use the latest beta (as below) solves that too.
```
RUN curl -sSL https://install.python-poetry.org | python3 - --version 1.2.0b2
```
ie this is already fixed.

**Comment by sveint** [comment]
This worked using `1.2.0`, but has resurfaced in both `1.2.1` and `1.2.2` for me.

As mentioned previously, pip chooses `Pillow-9.2.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl` while poetry chooses `Pillow-9.2.0-cp38-cp38-manylinux_2_28_x86_64.whl`. The latter gives:

`Pillow-9.2.0-cp38-cp38-manylinux_2_28_x86_64.whl is not a supported wheel on this platform.`

I'm happy to help debugging if someone could give me a pointer for where to look. Adding `-vvv` doesn't seem to provide enough information.
