### ISSUE TITLE
"poetry build" changes package version in distribution

### ISSUE THREAD

**Issue by vinnyfuria** [python-poetry/poetry#5110]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
    * See closed (stale) issue #843
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).
   * No exception observed

- **Ubuntu 20.04**: 
- **Poetry version 1.1.12**: 
- **Link of a [Gist](https://gist.github.com/vinnyfuria/52ba054e0c0c9828ccc43b28cd2f905f) with the contents of your pyproject.toml file**: 

## Issue

Poetry documentation states: _"While Poetry does not enforce any convention regarding package versioning, it strongly recommends to follow semantic versioning."_ Unfortunately I'm constrained to using versioning of the format NN-A (e,g., `01-A`). When executing `poetry build`, the version number of the built package gets translated to `1a0` (for example above) or `4a0` (for version `04-A` as shown in pyproject.toml gist linked above). This is used in the distribution package filename (`package-4a0.tar.gz`) as well as the dist-info package information. The expected behaviour would be a package filename `package-04-A.tar.gz` and the version in the built dist-info package information to be `04-A`.

The root of the problem appears to be the use of `poetry.utils.helpers.normalize_version` which is called from `Metadata.from_package()` which appears to be run when the poetry generated package is loaded (as far as I can follow).

The behaviour can be easily reproduced in any poetry project:

```bash
poetry version 04-A
poetry build
```

**Comment by finswimmer** [comment]
Hello @vinnyfuria,

[PEP 440](https://www.python.org/dev/peps/pep-0440/) describes how a version number of python package must look like. Whenever poetry builds a package, it will convert the SemVer notation to a valid PEP 440 version identifier.

This is by design and will not be changed.

fin swimmer
