### ISSUE TITLE
Allow `poetry add` with a `--frozen` flag to freeze current/specified version of dependency  

### ISSUE THREAD

**Issue by aalok-sathe** [python-poetry/poetry#5116]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

It would be useful to be able to freeze the version of a dependency at the same time as `add`. Some dependencies can be volatile, and even with the expectation that a minor revision should not chage the interface of any dependency, to certain projects, this risk may not be tolerable. Whereas we can already manually edit the `pyproject.toml` file to achieve this, an option to the `add` command to by default add a specific version `3.1.4` rather than `^3.1.4` or no version at all, would be useful.

Being able to do this retroactively could also be useful, using, say, `poetry freeze numpy`, which will freeze the `numpy` dependency to its current version in the lock file.

**Comment by clintonroy** [comment]
You can already do this.

poetry add pytest==6.2.4

for example.
