### ISSUE TITLE
Fourth number in package version is ignored

### ISSUE THREAD

**Issue by kabell** [python-poetry/poetry#5120]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 20.04 
- **Poetry version**: 1.1.12
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue

When I create an empty poetry project by 
```bash
poetry init
```
and then I try to add the following dependencies
```bash
poetry add pycurl==7.43.0.1 grab==0.6.41
```
it throws an error
```
  SolverProblemError

  Because kabell depends on grab (0.6.41) which depends on pycurl (<7.43.0.2), pycurl is required.
  So, because kabell depends on pycurl (7.43.0.1), version solving failed.
```

If the version of pycurl is not specified, poetry installs `7.21.5`. But there are two newer versions `7.43.0` and `7.43.0.1` which poetry is unable to install. It seems poetry ignores the 4th number in the versions and therefore considers `7.43.0.2 == 7.43.0.1 == 7.43.0` which isn't lower than `7.43.0.2`.

**Comment by finswimmer** [comment]
Hey @kabell,

I'm not able to reproduce this :thinking: Maybe there is an old `poetry.lock` file within your folder?

fin swimmer

**Comment by kabell** [comment]
Hi, sry it should be `grab==0.6.41`. `grab==0.6.40` works fine, because it has no dependencies constraints. Updated also in issue description. Please recheck.

**Comment by finswimmer** [comment]
Now I'm able to reproduce it with poetry 1.1.12. But it seems to work in the current preview release.

Can you test it?

```
pip install pipx
pipx install --suffix=@preview poetry==1.2.0a2
poetry@preview add pycurl==7.43.0.1 grab==0.6.41
```

**Comment by kabell** [comment]
Ok, thanks, it works with the current preview version.
