### ISSUE TITLE
Wrong dependency resolving

### ISSUE THREAD

**Issue by Virviil** [python-poetry/poetry#5127]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: MacOS 15.1
- **Poetry version**: 1.12

## Issue

```
PyPI: 2 packages found for logzio-python-handler >=3.0.0,<4.0.0
   1: fact: logzio-python-handler (3.1.0) depends on requests (>=2.27.0)
   1: derived: not logzio-python-handler (==3.1.0)
   1: fact: logzio-python-handler (3.0.0) depends on requests (>=2.27.0)
```

This is what I'm getting in command line. The fact is that `logzio-python-hendler`'s metadata looks like this:

```
Metadata-Version: 2.1
Name: logzio-python-handler
Version: 3.0.0
Summary: Logging handler to send logs to your Logz.io account with bulk SSL
Home-page: https://github.com/logzio/logzio-python-handler/
Author: roiravhon
Author-email: roi@logz.io
License: Apache License 2
Keywords: logging handler logz.io bulk https
Platform: UNKNOWN
Classifier: Development Status :: 5 - Production/Stable
Classifier: Intended Audience :: Developers
Classifier: Programming Language :: Python :: 2.7
License-File: LICENSE
Requires-Dist: requests (>=2.23.0)

UNKNOWN
```

How 2.23 turns into 2.27 - no ideas

**Comment by radoering** [comment]
There are two wheels for `logzio-python-handler 3.0.0` on PyPI. The first one has `Requires-Dist: requests (>=2.27.0)` in its metadata.

**Comment by Virviil** [comment]
Ok, it’s very bad. The question is - how can I continue to develop?

**Comment by finswimmer** [comment]
> The question is - how can I continue to develop?

You haven't specify what your problem is. So we cannot answer to this question :smiley:

**Comment by Virviil** [comment]
The problem is that pip installs package with 2.23 requests. And I have 2.23 requests. 

More than that, poetry v1.6 installs also package with requests 2.23.

**Comment by radoering** [comment]
This may be an issue of `logzio-python-handler`. I don't know if it is valid (or what it means) that there are the following [two wheels for 3.0.0](https://pypi.org/project/logzio-python-handler/3.0.0/#files):

- logzio_python_handler-3.0.0-py2.py3-none-any.whl
- logzio_python_handler-3.0.0-1-py2.py3-none-any.whl

It would be helpful if you could find out. Maybe, there is some general documentation about the "-1" in wheels. Maybe, you can ask the maintainers of `logzio-python-handler` what's the reason behind the two wheels.

As a workaround, you can try using an [url dependency](https://python-poetry.org/docs/dependency-specification/#url-dependencies) directly pointing to the wheel with the requests requirement you like.

**Comment by dimbleby** [comment]
if there's a bug here it seems to be with a now-old version of logzio-python-handler, I'd think this can safely be closed.
