### ISSUE TITLE
Private PyPI repository not honored on poetry search command

### ISSUE THREAD

**Issue by volkerjaenisch** [python-poetry/poetry#5132]
- [x ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **Debian bullyseye**: 
- **1.1.12**: 
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue

When setting a private PyPI the search function does allways search on PyPI.

This is the relevant code portion. In any case PyPiRepository Repository is used but not the repositories from the pool.
```Python
class SearchCommand(Command):

    name = "search"
    description = "Searches for packages on remote repositories."

    arguments = [argument("tokens", "The tokens to search for.", multiple=True)]

    def handle(self):
        from poetry.repositories.pypi_repository import PyPiRepository

        results = PyPiRepository().search(self.argument("tokens"))
```

This is my poetry.toml:
```python
[[tool.poetry.source]]
name = "foo"
url = "http://localhost:8888/simple/"
default = true
```
Which is used on other operations.

Cheers,
Volker

**Comment by neersighted** [comment]
Fixed in #3868
