### ISSUE TITLE
What does the @ in `poetry add pendulum@^2.0.5` in a docs example mean?

### ISSUE THREAD

**Issue by DFEvans** [python-poetry/poetry#5136]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue
In the CLI docs page (`cli.md`), the documentation for `add` gives two examples for specifying a constraint:

```
poetry add pendulum@^2.0.5
poetry add "pendulum>=2.0.5"
```

In the first line, what is the meaning of `@` in addition to `^`? Is this a symbol that modifies the behaviour of `^`, some shell-specific escape sequence (I know that `<` and `>` can be troublesome), or just a small typo? It's never referenced again in the accompanying text, or the Dependency Specification docs page (`dependency-specification.md`).

(It's been in the example ever since it was first added in c6a2d6e17772baf31fae4ece3f8b2449e2a36d97)

My reason for looking at this is that I've had another developer a little confused why `poetry add foo@1.2.3` isn't working to update a required version. I think it's simply that `@` isn't a valid specifier, and they've copied (part of) this example.

**Comment by dimbleby** [comment]
Looks like not a typo, the `@` is usual in 'direct' references (files, git repositories) and poetry tolerates it (but as far as I can tell ignores it) in regular version specifiers at `poetry add`.

In particular `poetry add foo@1.2.3` works just fine for me (with some package that actually exists)

**Comment by dimbleby** [comment]
also duplicates #3142
