### ISSUE TITLE
(🎁) `poetry export` still has a `--dev` option which just includes all groups

### ISSUE THREAD

**Issue by KotlinIsland** [python-poetry/poetry#5140]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

`poetry help export`:
```
--dev               Include development dependencies.
```

Should `poetry export` have `--with` and `--without` flags like other commands?

Or maybe just update the text on that help message to say something like "Include dependencies from all required groups."

**Comment by finswimmer** [comment]
Hello @KotlinIsland,

the `poetry export` command will be replaced by the [poetry-export-plugin](https://github.com/python-poetry/poetry-export-plugin) in the final 1.2 release. See https://github.com/python-poetry/poetry/pull/4824. Once this happend `--with` and `--without` will be available.

fin swimmer
