### ISSUE TITLE
pyproject.toml author, does not pull the correct info if there is an includeif.gitdir directive

### ISSUE THREAD

**Issue by rcepeda95** [python-poetry/poetry#5161]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **Poetry version**: 1.1.12

## Issue
I have a per-directory git config set up, where if a git repo is created under `~/work` then my work email gets used by git to sign off my commits instead of my personal email. This is accomplished using `includeIf.gitdir` in git's global config. When I make a new project using poetry, the `pyproject.toml` auto-populates an author based on the values that show up as `user.name` and `user.email`  from the command `git config -l`. Since a git repo is not initialized when `poetry new` is called, none of the `includeif.gitdir` commands have been executed by git, causing those values to not be seen by poetry and to potentially pull incorrect values from the ones that have been specified under a certain directory (in this case my work email).

```
# ~/.gitconfig

[user]
   name = John Doe
   email = john@personal.com

...

[includeIf "gitdir:~/work/"]
    path = ~/work/.gitconfig
```

```
# ~/work/.gitconfig

[user]
   email = john@work.com
```

```
$ cd ~/work
$ poetry new project-name
$ cd project-name
$ cat pyproject.toml
[tool.poetry]
name = "project-name"
description = ""
authors = ["John Doe <john@personal.com>"]
...
```

**Comment by finswimmer** [comment]
Hello @rcepeda95,

I see your problem. But that's a chicken-egg-problem that cannot be solved by Poetry. 

To work around this you could delete the `pyproject.toml` after the `poetry new` and recreate it via `poetry init` once you've initialize the git repo.

A better solution is probably using [cookiecutter](https://github.com/cookiecutter/cookiecutter) which gives you much more flexibility when setting up new projects.

fin swimmer

**Comment by rcepeda95** [comment]
Thanks @finswimmer  for your response. Could a git repo be initialized before `pyproject.toml` gets created? I would assume a large majority of projects end up initializing git on their own after calling `poetry new`. Would that be a feature request?
