### ISSUE TITLE
Add Command Does Not Allow Wildcards '*'

### ISSUE THREAD

**Issue by ronaldnwilliams** [python-poetry/poetry#5162]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS Monterey
- **Poetry version**: 1.1.12
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

[tool.poetry]
name = "anonymous-name"
version = "0.1.0"
description = ""
authors = ["author@gmail.com"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

## Issue
Poetry 'add' command does not allow you to use a wildcard for the version. 
`poetry add package_name@*`

(Sorry not sure if this is a bug or a feature request.)

**Comment by finswimmer** [comment]
Hello @ronaldnwilliams,

you've missed to post any error messages, so we can only guess what happens. The `*` has usually a special meaning in shells, so you have to quote it like this:

```
poetry add "package_name@*
```

fin swimmer

**Comment by ronaldnwilliams** [comment]
Sorry about that, no error messages. Just the package could not be found. Thanks @finswimmer that worked when I put it in quotes.
