### ISSUE TITLE
Unable to import TFLearn and aiofiles when added using `poetry add`

### ISSUE THREAD

**Issue by EpicBirb** [python-poetry/poetry#5168]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows 10 21H1
- **Poetry version**: 1.1.12
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/EpicBirb/2b69a9b7310bbfe5cb82ad87bf924c12

## Issue
Adding TFLearn and aiofiles using `poetry add` worked, but the modules couldn't be imported. Since I am using VS Code. I found that poetry did not actually installed TFLearn, nor aiofiles (found via pip manager).

screenshots
![image](https://user-images.githubusercontent.com/68750348/153081145-e0e3f3cc-2c14-445b-8511-ee30819c3db3.png)
![image](https://user-images.githubusercontent.com/68750348/153081176-bb753751-9803-4bc9-9ea1-5e3a63ff0798.png)
![image](https://user-images.githubusercontent.com/68750348/153081331-f5c1b8d2-30e0-4a87-a3cb-85bca6d8fdb5.png)
![image](https://user-images.githubusercontent.com/68750348/153081367-22d91a96-72a3-4feb-8cf6-7040a9131d89.png)

**Comment by clintonroy** [comment]
You do need to do a `poetry install` at some point, I have no idea how that integrates with any editor though. Please try to post text to bug reports, some of the above is very hard to read.

**Comment by EpicBirb** [comment]
![image](https://user-images.githubusercontent.com/68750348/153086551-e7b3d105-cb44-4956-8bdd-c9be37c0e3d9.png)

**Comment by EpicBirb** [comment]
sorry

**Comment by EpicBirb** [comment]
Oh yeah btw. screen shot 3-4 is basically the packages in A-Z, packages TFLearn and aiofiles are not listed

1-2: yellow underline = import error

**Comment by EpicBirb** [comment]
update:
changed environments. works now.
