### ISSUE TITLE
Unable to configure installer.max-workers

### ISSUE THREAD

**Issue by mcyprian** [python-poetry/poetry#5169]
- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS Monterey 12.1
- **Poetry version**: 1.1.12 and 1.2.0a2

## Issue

I try to configure the maximum number of workers while using the parallel installer as documented [here](https://python-poetry.org/docs/master/configuration/#installermax-workers)
`
$ poetry config --local installer.max-workers 4`

command fails with
```
ValueError
Setting installer.max-workers does not exist
```

**Comment by clintonroy** [comment]
Right up the top, you can switch the branch the documentation is built from, that's from the master branch, which is not the version of poetry you have installed
