### ISSUE TITLE
add a `reinstall` flag for poetry

### ISSUE THREAD

**Issue by EpicBirb** [python-poetry/poetry#5183]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request
Removing packages and re-adding them because of an error or something else might take a lot of time depending on the circumstances. 

Adding a `reinstall` flag would be very handy.
It will basically remove the package and re-add it.

**Comment by mkniewallner** [comment]
Did you encounter specific errors that could require this feature, where running `poetry install` again would not be enough?

Note that you can completely delete a virtual environment created by Poetry by using `poetry env remove <VIRTUAL_ENV>` (you can list all virtual envs for a project using `poetry env list` to get the name of the virtual env to delete).

**Comment by neersighted** [comment]
Hey @EpicBirb -- thanks for creating this issue! Since you opened it and people asked what use-case you had in mind, a very clear one materialized at https://github.com/python-poetry/poetry/issues/6639. I'm going to re-open this to track the feature request.

**Comment by neersighted** [comment]
Actually, I've decided to make #6639 canon since the discussion there is very valuable. Closing this as a duplicate instead.
