### ISSUE TITLE
`poetry add` updates the version of the other dependencies

### ISSUE THREAD

**Issue by zyrikby** [python-poetry/poetry#5185]
- [ ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

**OS version and name**:  Kubuntu 20.04
**Poetry version**:  1.1.12

## Issue
Hi there! First of all, thank you very much for this tool!

Recently, I have found out a weird behavior to me. However, maybe it poetry works as expected, so please then explain this behavior to me.

The issue is the following. When you add a new dependency to a project using the `poetry add` command, poetry also updates the versions of other libraries if the updates are available despite that the previous version is recorded in the *poetry.lock* file.  Such behavior to me is unexpected and may lead to bugs in the developed application.

**Comment by zyrikby** [comment]
Interesting, I cannot now reproduce this behavior with minimum working version. However, here is the output that I've experienced in the morning:

```console
$ poetry add pyhash
Using version ^0.9.3 for pyhash

Updating dependencies
Resolving dependencies... (1.3s)

Writing lock file

Package operations: 1 install, 1 update, 0 removals

• Updating datasketch (1.5.6 -> 1.5.7)
• Installing pyhash (0.9.3)
```

**Comment by quantus** [comment]
I can reproduce this issue locally on both `poetry add` and `poetry update` commands. In my case it's always the `coverage` dependency that is being updated unexpectedly and after doing a bit more searching I found an existing issue #4612 which looks really similar to my situation. So something similar might have been happening here.

**Comment by radoering** [comment]
If your issue looks similar to #4612, you may want to check if #4618 solves your issue. If it does not solve your issue, please provide the state of `pyproject.toml` and `poetry.lock` before running `poetry add` or `poetry update` and give the exact command you run to trigger the issue.

**Comment by quantus** [comment]
I just tested and #4618 does solve the issue I'm seeing.
