### ISSUE TITLE
Poetry ignores manually activated virtualenv

### ISSUE THREAD

**Issue by maksbotan** [python-poetry/poetry#5193]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS Big Sur + nix package manager
- **Poetry version**: 1.1.10 through 1.1.13
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: not relevant

## Issue

I'm not sure if this is a bug or desired behavior, so I'd like to hear developers' opinion.

During my experiments I tried to manually create a virtual env and then I hoped poetry would pick it up instead of using its own one in `virtualenvs.path`, as I remember it worked somewhere in 1.0.x. However, I was surprised that that was not the case, and with my custom env active all poetry commands were still referring to some env in `virtualenvs.path`, also confirmed by `poetry env info` output.

A bigger surprise was that when I deleted that poetry's virtualenv (using `rm`), `poetry env info` started just showing my system python, completely ignoring my virtualenv:

```console
$ poetry env info

Virtualenv
Python:         3.8.8
Implementation: CPython
Path:           /Users/maksbotan/.nix-profile
Valid:          True

System
Platform: darwin
OS:       posix
Python:   /nix/store/xf3244kbn36z04yw98mpgvvsgdcbz438-python3-3.8.8
```

Of course `$VIRTUAL_ENV` is set in the shell where I activated my env.

As far as I understand, this behavior was introduced in this commit:

https://github.com/python-poetry/poetry/commit/3c26c8d009366a35669bfd4ef01af4cb32d113e3#diff-48120c42d1d0a5860b317966e7d1e0a65e48e4fee6f6a0795fad5848dcf43ef0R267

```python
if not in_venv or env is not None:
```

If I remove the second part of that if statement (`or env is not None`) I start to see expected behavior:

```console
(venv) $ poetry env info

Virtualenv
Python:         3.8.8
Implementation: CPython
Path:           /Users/maksbotan/temp/venv
Valid:          True

System
Platform: darwin
OS:       posix
Python:   /nix/store/xf3244kbn36z04yw98mpgvvsgdcbz438-python3-3.8.8
```

Seeing that this condition was introduced deliberately, I ask for clarification if this behavior is intended or accidental. And if it is intended, I'd like to know the justification.

Thanks!

P.S.  Just in case, my `python` in `$PATH` is actually a symlink:

```console
$ ls -l $(which python)
lrwxr-xr-x  1 maksbotan  admin  68 Jan  1  1970 /Users/maksbotan/.nix-profile/bin/python -> /nix/store/xf3244kbn36z04yw98mpgvvsgdcbz438-python3-3.8.8/bin/python
```

**Comment by finswimmer** [comment]
Hello @maksbotan,

you haven't come back to this issue for a long while. So I assume this is solved in the meantime and I can close this ticket.

Feel free to leave a comment if you disagree.

fin swimmer
