### ISSUE TITLE
Recreate virtualenv automatically if needed

### ISSUE THREAD

**Issue by LifeIsStrange** [python-poetry/poetry#5196]
I am not a python expert used much to the concept of virtualenvs but I had [this issue](https://github.com/python-poetry/poetry/issues/1004)
In 2022 when you go back months later to a project, it is expected to build, to just works. The error was obscure, it seems that since my python version was upgraded from 3.9 to 3.10 the virtualenv was broken? If so, poetry should simply detect such cases and automatically recreate the virtualenv instead of showing an obscure error
for posterity envs are default located in .cache/pypoetry/virtualenvs
.

**Comment by Cajuteq** [comment]
this little side note for posterity just had a huge value for me, thank you

**Comment by finswimmer** [comment]
It's hard to detect if an environment is really broken and must be recreated or if it just a temporary issue. So it's unlikely we will implement something like this.

What we are doing already is to recreate the venv if Poetry cannot find the `python` binary in the venv.
