### ISSUE TITLE
poetry init fails on bash for Windows

### ISSUE THREAD

**Issue by btonasse** [python-poetry/poetry#5198]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows 10
- **Poetry version**: 1.1.13
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: N/A

## Issue
Trying to run `poetry init` on git bash for Windows fails, but it works without any issues on PS or cmd. See verbose error message:

> $ poetry init -vvv

> This command will guide you through creating your pyproject.toml config.
> 
> 
>   Stack trace:
> 
>   14  ~\AppData\Roaming\pypoetry\venv\lib\site-packages\clikit\console_application.py:131 in run
>        129│             parsed_args = resolved_command.args
>        130│ 
>      → 131│             status_code = command.handle(parsed_args, io)
>        132│         except KeyboardInterrupt:
>        133│             status_code = 1
> 
>   13  ~\AppData\Roaming\pypoetry\venv\lib\site-packages\clikit\api\command\command.py:120 in handle
>        118│     def handle(self, args, io):  # type: (Args, IO) -> int
>        119│         try:
>      → 120│             status_code = self._do_handle(args, io)
>        121│         except KeyboardInterrupt:
>        122│             if io.is_debug():
> 
>   12  ~\AppData\Roaming\pypoetry\venv\lib\site-packages\clikit\api\command\command.py:171 in _do_handle
>        169│         handler_method = self._config.handler_method
>        170│
>      → 171│         return getattr(handler, handler_method)(args, io, self)
>        172│
>        173│     def __repr__(self):  # type: () -> str
> 
>   11  ~\AppData\Roaming\pypoetry\venv\lib\site-packages\cleo\commands\command.py:92 in wrap_handle
>         90│         self._command = command
>         91│
>      →  92│         return self.handle()
>         93│
>         94│     def handle(self):  # type: () -> Optional[int]
> 
>   10  ~\AppData\Roaming\pypoetry\venv\lib\site-packages\poetry\console\commands\init.py:101 in handle
>         99│                 "Package name [{}]: ".format(name), default=name
>        100│             )
>      → 101│             name = self.ask(question)
>        102│
>        103│         version = "0.1.0"
> 
>    9  ~\AppData\Roaming\pypoetry\venv\lib\site-packages\cleo\commands\command.py:153 in ask
>        151│         """
>        152│         if isinstance(question, Question):
>      → 153│             return self._io.ask_question(question)
>        154│
>        155│         return self._io.ask(question, default)
> 
>    8  ~\AppData\Roaming\pypoetry\venv\lib\site-packages\cleo\io\io_mixin.py:50 in ask_question
>         48│         Asks a question.
>         49│         """
>      →  50│         answer = question.ask(self)
>         51│
>         52│         return answer
> 
>    7  ~\AppData\Roaming\pypoetry\venv\lib\site-packages\clikit\ui\components\question.py:76 in ask
>         74│ 
>         75│         if not self._validator:
>      →  76│             return self._do_ask(io)
>         77│
>         78│         interviewer = lambda: self._do_ask(io)
> 
>    6  ~\AppData\Roaming\pypoetry\venv\lib\site-packages\clikit\ui\components\question.py:86 in _do_ask
>         84│         Asks the question to the user.
>         85│         """
>      →  86│         self._write_prompt(io)
>         87│
>         88│         autocomplete = self._autocomplete_values
> 
>    5  ~\AppData\Roaming\pypoetry\venv\lib\site-packages\clikit\ui\components\question.py:119 in _write_prompt
>        117│         message = self._question
>        118│
>      → 119│         io.error("{} ".format(message))
>        120│
>        121│     def _write_error(self, io, error):
> 
>    4  ~\AppData\Roaming\pypoetry\venv\lib\site-packages\cleo\io\io_mixin.py:60 in error
>         58│
>         59│     def error(self, string, flags=0):
>      →  60│         super(IOMixin, self).error(string, flags)
>         61│
>         62│         self._last_message = string
> 
>    3  ~\AppData\Roaming\pypoetry\venv\lib\site-packages\clikit\api\io\io.py:86 in error
>         84│         The string is formatted before it is written to the output.
>         85│         """
>      →  86│         self._error_output.write(string, flags=flags)
>         87│
>         88│     def error_line(self, string, flags=None):  # type: (str, Optional[int]) -> None
> 
>    2  ~\AppData\Roaming\pypoetry\venv\lib\site-packages\clikit\api\io\output.py:61 in write
>         59│                 formatted += "\n"
>         60│
>      →  61│             self._stream.write(to_str(formatted))
>         62│
>         63│     def write_line(self, string, flags=None):  # type: (str, Optional[int]) -> None
> 
>    1  ~\AppData\Roaming\pypoetry\venv\lib\site-packages\clikit\io\output_stream\stream_output_stream.py:21 in write
>         19│         Writes a string to the stream.
>         20│         """
>      →  21│         if self.is_closed():
>         22│             raise io.UnsupportedOperation("Cannot write to a closed input.")
>         23│
> 
>   AttributeError
> 
>   'NoneType' object has no attribute 'closed'
> 
>   at ~\AppData\Roaming\pypoetry\venv\lib\site-packages\clikit\io\output_stream\stream_output_stream.py:116 in is_closed
>       112│     def is_closed(self):  # type: () -> bool
>       113│
>       114│         Returns whether the stream is closed.
>       115│         """
>     → 116│         return self._stream.closed
>       117│

**Comment by John15321** [comment]
Could you @btonasse post the stack trace using code snippets In markdown?
<img width="378" alt="image" src="https://user-images.githubusercontent.com/56229312/174481915-89c7fb94-cc48-4ad9-8f04-e30e57abc1ae.png">

**Comment by dimbleby** [comment]
I wouldn't bother, none of this code exists any more on master (because cleo has changed so much).  Repro with 1.1.13 is pointless at this point.

Suggest close out, and if folk still hit problems with 1.2 then they'll raise new issues.
