### ISSUE TITLE
Support PEP 517 config settings

### ISSUE THREAD

**Issue by yajo** [python-poetry/poetry#5202]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

[PEP517 declares support for something called "config settings"](https://www.python.org/dev/peps/pep-0517/#config-settings), which allows passing arbitrary parameters to the build backend, allowing to specify custom logic for it.

[Pip doesn't support it yet, but there's a proposal](https://github.com/pypa/pip/issues/5771).

[Build supports it](https://pypa-build.readthedocs.io/en/latest/#python--m-build---config-setting).

Poetry should support it.

**Comment by neimad1985** [comment]
@yajo I kindly think that you _should_ stop telling people what they _should_ do or not. No pun intended. This would prevent you from getting a stalling issue.

**Comment by yajo** [comment]
Sorry I didn't mean to offend anyone 😔 

I'll close the issue so maintainers can focus on whatever they think it's better for the project. 

Thanks everybody!
