### ISSUE TITLE
How to add custom installation steps in poetry setup script ? I want to build librealsense sdk from source using poetry.

### ISSUE THREAD

**Issue by deepak-asink** [python-poetry/poetry#5206]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

**Comment by clintonroy** [comment]
There is an API for doing this, but it's not currently considered released, and it's not documented.
https://stackoverflow.com/questions/60073711/how-to-build-c-extensions-via-poetry

**Comment by deepak-asink** [comment]
thanks @clintonroy
