### ISSUE TITLE
Poetry commands produce SetuptoolsDeprecationWarning

### ISSUE THREAD

**Issue by edran** [python-poetry/poetry#5210]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- N/A If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: MacOS 11.6.2
- **Poetry version**: `1.2.0a2`
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/edran/94390e75b37579c96f8f733acafb0062

## Issue

When running `poetry run python` (or `poetry shell/install/lock ...`), I get the following warning:

```
/Users/nantas/Library/Application Support/pypoetry/venv/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
```

This warning is then present across any invocations of `poetry run python`. However inside a sourced shell -- i.e. after `poetry shell` -- running `python` does not produce the warning (which makes me think it's an issue with the poetry build that is pulled by `install-poetry.py`).

Interestingly, though, simply running `poetry` does not produce the warning.

---

To install poetry I did:

```sh
curl -sSL https://install.python-poetry.org | POETRY_VERSION=1.2.0a2 python3 -
```

with python3 being:

```sh
$ which python3                                                                                            
/opt/homebrew/bin/python3
```

The problem was mentioned in #4085, but this seems different enough to warrant a separate issue for discoverability.

**Comment by dimbleby** [comment]
it is different from #5157?
