### ISSUE TITLE
Git-Dependency handled wrongly if python3.10 is used as poetry base

### ISSUE THREAD

**Issue by mosauter** [python-poetry/poetry#5211]
- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: arch-linux
- **Poetry version**: 1.1.13
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: [pyproject.toml](https://gist.github.com/mosauter/d41b141069230bddb8f23f21a7040229)

## Issue

I installed poetry via the normal:
```
curl -sSL https://install.python-poetry.org | python3 -
```
Important to note here is that my system-python is a 3.10 version. If I now run
```
poetry update
```
with the linked [pyproject.toml](https://gist.github.com/mosauter/d41b141069230bddb8f23f21a7040229) it fails with the error that `torch` is missing. This is a known issue with the yolox-project, which is why in the `pyproject.toml` specifies one specific commit where this was fixed by them for a very short time (and then broke again, but this is a different issue).

It seems to me that poetry with a 3.10 base cannot correctly checkout the `rev` given in the `pyproject.toml` when it is in `update`-mode. 

If I do the exact same thing in a default `ubuntu:20.04` docker-container with poetry installed this runs through without any issue. 

If you want to replicate the container <details>install: `curl git python3.8-venv build-essential python3-dev` for full installation</details>

Note: If I now use the `poetry.lock` that was generated in the container, the `poetry install` on my host system works fine. So only the update mode is affected.

**Comment by finswimmer** [comment]
Hello @mosauter ,

you haven't come back to this issue for a long while. So I assume this is solved in the meantime and I can close this ticket.

Feel free to leave a comment if you disagree.

fin swimmer
