### ISSUE TITLE
Installation fails with 'Key "metadata" does not exist.' error.

### ISSUE THREAD

**Issue by castagninojose** [python-poetry/poetry#5212]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Docker version `20.10.12`, build `e91ed57` with `python:3.8.10` image. Host system: `ubuntu 20.04`
- **Poetry version**: 1.1.13
- **pyproject.toml**:
```
[tool.poetry]
name = "localpg"
version = "0.1.0"
description = ""
authors = ["José Castagnino"]
packages = [{include = "localpg"}]

[tool.poetry.dependencies]
python = "3.8.10"
pandas = "^1.3.5"
alembic = "^1.7.5"
muttlib = "1.4.12"
python-decouple = "^3.5"
pangres = "^3.0"
psycopg2 = "^2.9.3"

[tool.poetry.dev-dependencies]
black = "^21.12b0"
pdbpp = "^0.10.3"
pylint = "^2.12.2"
isort = "^5.10.1"
flake8 = "^4.0.1"
pre-commit-hooks = "^4.1.0"
mypy = "^0.931"

[tool.black]
line_length = 88
skip-string-normalization = true

[tool.mypy]
ignore_missing_imports = true
follow_imports = 'skip'

[tool.isort]
multi_line_output = 3
line_length = 88
include_trailing_comma = true

[tool.pylint.master]
jobs = 0
 
[tool.pylint.'MESSAGES CONTROL']
disable = [
  'C',
  'R',
  'fixme',
  'logging-format-interpolation',
  'logging-fstring-interpolation',
  'unspecified-encoding'
]

[tool.pylint.'FORMAT']
max-line-length = 88  # as in black

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

## Issue
I'm trying to build a custom docker image with my python app using `python:3.8.10` as a base image and the following `Dockerfile`:

```
FROM python:3.8.10

RUN apt-get update \
    && apt-get install -y neovim \
    && apt-get install -y --no-install-recommends gcc git \
    && apt-get install --no-install-recommends --no-install-suggests --assume-yes curl

ENV PATH="/root/.local/bin:$PATH"

RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
RUN . $HOME/.poetry/env
ENV PATH="${PATH}:/root/.poetry/bin"

COPY pyproject.toml /silico-local-pg/pyproject.toml
WORKDIR /silico-local-pg
RUN poetry config virtualenvs.create false
RUN poetry install --no-root
COPY . /silico-local-pg
RUN poetry install --no-interaction
```

Everything seems to go ok until the very last command `poetry install --no-interaction`. I keep getting 
```
NonExistentKey
'Key "metadata" does not exist.'
at ~/.poetry/lib/poetry/_vendor/py3.8/tomlkit/container.py:553 in __getitem__
549│             key = Key(key)
550│ 
551│         idx = self._map.get(key, None)
552│         if idx is None:
→ 553│             raise NonExistentKey(key)
554│ 
555│         if isinstance(idx, tuple):
556│             # The item we are getting is an out of order table
557│             # so we need a proxy to retrieve the proper objects
The command '/bin/sh -c poetry install --no-interaction' returned a non-zero code: 1
```
My project has the following structure

```
silico-local-pg
|_/localpg
    |_<my python source code>
|_/docker
    |_Dockerfile
    |_pyproject.toml
    |_poetry.lock
```
Please let me know of any additional information I might have missed and feel free to close if this is a duplicate or not related to poetry.

**Comment by clintonroy** [comment]
Bit of a stab in the dark here, but metadata is a key in the poetry.lock file, which I don't think you're copying across, maybe that file is being corrupted or something.

**Comment by castagninojose** [comment]
That's a good guess, but I've already been through my `poetry.lock` file and could not find any reference to `metadata` anywhere. In fact I first tried copying both pyproject and lock files and was getting the same error. I then tried without copying the lock file in the hopes that regenerating it would fix it, but no luck either :|

**Comment by clintonroy** [comment]
Something sounds very wonky, i'm no expert in the poetry.lock format, but I suspect metadata is mandatory:

```
[metadata]
lock-version = "1.1"
python-versions = "3.10.2"
content-hash = "10360ec0d8952171dab729fce98197b683d22ecbe0dd44c71ecad12fed1954d4"
```

is a top level section, and metadata.files contains all the hashes of the deps:

```
[metadata.files]
alembic = [
    {file = "alembic-1.7.6-py3-none-any.whl", hash = "sha256:ad842f2c3ab5c5d4861232730779c05e33db4ba880a08b85eb505e87c01095bc"},
    {file = "alembic-1.7.6.tar.gz", hash = "sha256:6c0c05e9768a896d804387e20b299880fe01bc56484246b0dffe8075d6d3d847"},
]
```

I may well be wrong, but I think something is off with the poetry.lock file creation.

**Comment by castagninojose** [comment]
Something sounds wonky indeed, IIUC the lock file is being regenerated when not copied so I don't know how it can be corrupted :thinking: 
I'll check the lock file again tomorrow to look for any clues.

**Comment by clintonroy** [comment]
very random guess, due to permisisons it's not being written and is being seen as empty or some such.

**Comment by castagninojose** [comment]
The lockfile was indeed messed up, most likely by me when copying it into the `docker` directory to make it available at build time. After deleting it and regenerating it without using docker, I ended up moving the dockerfile instead so they all live in the same directory (repo's root).

I believe this was a combination of both myself messing up and the docker build context being a PITA to configure.

In any case I'll be closing this, thanks for your help @clintonroy
