### ISSUE TITLE
Version resolving using caret for python dependency not working with range requirements.

### ISSUE THREAD

**Issue by jaydosi** [python-poetry/poetry#5214]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows 10
- **Poetry version**: 1.1.13
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 
https://gist.github.com/jaydosi/96cf7a0bd09adb101e3fdd83fddf4945

## Issue

My test contains two dependencies
(numba is just an example which demonstrates the issue):
```
python = "^3.9"
numba = "0.55.1"
```

Calling poetry install produces following output:

```
(.venv) C:\git\test>poetry install
Creating virtualenv test in C:\git\test\.venv
Updating dependencies
Resolving dependencies...

  SolverProblemError

  The current project's Python requirement (>=3.9,<4.0) is not compatible with some of the required packages Python requirement:
    - numba requires Python >=3.7,<3.11, so it will not be satisfied for Python >=3.11,<4.0

  Because test depends on numba (0.55.1) which requires Python >=3.7,<3.11, version solving failed.

  at ~\.poetry\lib\poetry\puzzle\solver.py:241 in _solve
      237│             packages = result.packages
      238│         except OverrideNeeded as e:
      239│             return self.solve_in_compatibility_mode(e.overrides, use_latest=use_latest)
      240│         except SolveFailure as e:
    → 241│             raise SolverProblemError(e)
      242│
      243│         results = dict(
      244│             depth_first_search(
      245│                 PackageNode(self._package, packages), aggregate_package_nodes

  • Check your dependencies Python requirement: The Python requirement can be specified via the `python` or `markers` properties

    For numba, a possible solution would be to set the `python` property to ">=3.9,<3.11"

    https://python-poetry.org/docs/dependency-specification/#python-restricted-dependencies,
    https://python-poetry.org/docs/dependency-specification/#using-environment-markers

```

If my project requires "^3.9" and numba requires ">=3.7,<3.11", then this is satisfied for python 3.9 and 3.10.
The output says this will not be satisfied for python ">=3.11,<4.0" - which is obviously wrong.

According to the dependency specification
(https://python-poetry.org/docs/dependency-specification/#caret-requirements)
^3.9 is equivalent to >=3.9.0 < 4.0.0

When I change the configuration in pyproject.toml to ">=3.9,<3.11" everything works fine,
but this is too restrictive and not logical.

**Comment by finswimmer** [comment]
Hello @jaydosi,

this is by design. See https://github.com/python-poetry/poetry/blob/master/docs/faq.md#L86

fin swimmer

**Comment by nyanpasu64** [comment]
The [FAQ](https://github.com/python-poetry/poetry/blob/master/docs/faq.md#why-is-poetry-telling-me-that-the-current-projects-python-requirement-is-not-compatible-with-one-or-more-packages-python-requirements) links to https://github.com/python-poetry/poetry/blob/master/docs/dependency-specification/#multiple-constraints-dependencies which is a dead link. Is this intentional or not?

(https://python-poetry.org/docs/dependency-specification/ lacks a .md extension, but https://python-poetry.org/docs/faq/ lacks the link altogether.)
