### ISSUE TITLE
`ImportError: attempted relative import with no known parent package` when attempting install

### ISSUE THREAD

**Issue by devyntk** [python-poetry/poetry#5216]
- **OS version and name**: Arch Linux (last updated today)
- **Poetry version**: 1.1.13
- **pyproject.toml file**: https://github.com/first-illinois-robotics/firweb/blob/e54d45d91e52cbacccd9e55a114a6ae41c79e175/pyproject.toml
- **error log**: https://gist.github.com/devyntk/565b3cad4afc98f08729488f5f8921d9 

## Issue
I can't seem to install this project no matter what. I've tried using both 3.9 and 3.10 on my local arch machine. It always errors out in this same way. I can install the project correctly on a Ubuntu 20.04 install. I have already tried reinstalling both python and poetry (through the official arch repos) and also clearing the entire `~/.cache/pypoetry` directory.

**Comment by felixonmars** [comment]
A dirty workaround could be: https://github.com/felixonmars/poetry/commit/b4a74c7f366e1846c26808641649cbbbbfcb8577

Not submitting a real fix because I am unsure about how to properly address this.

**Comment by alerque** [comment]
I added @felixonmars's dirty patch to the Arch Linux packaging, currently in [community-testing]. I would encourage everyone on Arch that was having this issue to test, as well as everybody that wasn't to also test and make sure it doesn't regress anything else serious. I understand this will probably eventually get fixed upstream a different way, but in a distro context where we know what packages are and are not available it seems like a workable hack that solves a very real problem people keep hitting.

**Comment by abn** [comment]
This should be resolved by #4749.

**Comment by spoorn** [comment]
I ran into this same problem in a Plugin I created which adds new commands.  Fixed it by adding `from packaging.tags import sys_tags` to my Plugin imports
