### ISSUE TITLE
SolverProblemError with version requirement depending on Python version

### ISSUE THREAD

**Issue by foucdeg** [python-poetry/poetry#5218]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 20.04
- **Poetry version**: 1.1.13
- **Link of a Gist with the contents of your pyproject.toml file**: [Gist](https://gist.github.com/foucdeg/804716dcf064eca904b987216e458bee)

## Issue

Using the linked pyproject.toml file and Python 3.10.1, Poetry reports a SolverProblemError.

Specifically, Poetry reports that:

- `pubcontrol (3.2.1) depends on PyJWT (<=1, <2)`
- `djangorestframework-simplejwt (5.0.0) depends on PyJWT (>=2,<3)`

But Poetry is wrong about pubcontrol, because https://github.com/fanout/pypubcontrol/blob/master/setup.py shows that when running Python3, `pubcontrol` accepts `PyJWT` >= 2.

So, PyJWT 2 would be a valid resolution.

How can I get poetry to resolve these dependencies together using PyJWT 2?

**Comment by dimbleby** [comment]
The requires.txt in https://files.pythonhosted.org/packages/77/3c/853b0d11ee0438e78ae258908c2ecef8c70394e0dd3d68320a1b59674533/pubcontrol-3.2.1.tar.gz says 
```
PyJWT<2,>=1
requests<3,>=2.4
```
I guess that pubcontrol is Doing It Wrong, it should use markers for its dependencies.  Not much that poetry can do about that.

(Guessing, but I bet they have published from a python 2 environment and so their published package has the python 2 version of the dependencies.)

**Comment by foucdeg** [comment]
Fixed with https://github.com/fanout/pypubcontrol/issues/5.
