### ISSUE TITLE
Docs recommend using an outdated powershell command for Windows installation

### ISSUE THREAD

**Issue by trosel** [python-poetry/poetry#5220]
https://python-poetry.org/docs/#windows-powershell-install-instructions

On this page, it recommends the following script `(Invoke-WebRequest -Uri https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py -UseBasicParsing).Content | python -`

When this is run, it gives the following warning:

`This installer is deprecated. Poetry versions installed using this script will not be able to use 'self update' command to upgrade to 1.2.0a1 or later.`

Is there a new recommended installation script for Windows? Or what is the best new way to install?

**Comment by radoering** [comment]
Two sections above, the new `install-poetry.py` script is mentioned: https://python-poetry.org/docs/#installation

Personally, I like `pipx` which is also described.

**Comment by trosel** [comment]
@radoering 
![image](https://user-images.githubusercontent.com/1299322/154855248-2d0938a3-d475-457e-b9df-a00b4be82932.png)

This section merely describes the installer. It doesn't describe where or how to get that installer. 

So the reader necessarily reads on below to see where to get that installer. 

"Ah, here is the windows script..."

![image](https://user-images.githubusercontent.com/1299322/154855316-d6b02c22-2042-4157-80e5-d6b536c3f1ee.png)

This is very confusing.

**Comment by radoering** [comment]
I can understand your confusion. However, I don't expect it to be changed for version 1.1. With poetry 1.2 the situation will improve. If you click on the _"described here"_ link in the box mentioning the new installer, you are forwarded to the current `master` version of the documentation. (You can also switch between `1.1` documentation and `master` at the top of the page.)

**Comment by finswimmer** [comment]
It seems that many (?) people miss the link in the info box (There were similar issues before). Any recommendation about how to make it clearer is welcome @trosel :)
