### ISSUE TITLE
Invalid "setup.py" file "extra_require" attribute definition.

### ISSUE THREAD

**Issue by KelSolaar** [python-poetry/poetry#5223]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [N/A] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS Monterey 12.1
- **Poetry version**: Poetry 1.1.13
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/KelSolaar/1333fb7cf1a5caf65634891ab06cd6ca

## Issue

Hi,

Shortly after releasing Colour 0.4.0, we got a report that the MSYS2 package build broke: colour-science/colour#945

The exception raised while invoking `python setup.py build` is as follows:

> error in colour-science setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.

Looking at how the `setup.py` file `extras_require` attribute is defined, there is a highly suspicious key, i.e. `':extra == "read-the-docs"'`:

```python
extras_require = \
{':extra == "read-the-docs"': ['numpy>=1.19,<2'],
 'development': ['biblib-simple',
                 'black',
                 'coverage!=6.3',
                 'coveralls',
                 'flake8',
                 'flynt',
                 'invoke',
                 'jupyter',
                 'mypy',
                 'pre-commit',
                 'pydata-sphinx-theme',
                 'pydocstyle',
                 'pytest',
                 'pytest-cov',
                 'pyupgrade',
                 'restructuredtext-lint',
                 'sphinx>=4,<5',
                 'sphinxcontrib-bibtex',
                 'toml',
                 'twine'],
 'graphviz': ['pygraphviz>=1,<2'],
 'meshing': ['trimesh>=3,<4'],
 'optional': ['networkx>=2,<3',
              'pandas>=1,<2',
              'scikit-learn>=1,<2',
              'tqdm>=4,<5'],
 'plotting': ['matplotlib>=3.2,!=3.5.0,!=3.5.1'],
 'read-the-docs': ['matplotlib>=3.2,!=3.5.0,!=3.5.1',
                   'networkx>=2,<3',
                   'pygraphviz>=1,<2',
                   'trimesh>=3,<4',
                   'pydata-sphinx-theme',
                   'sphinxcontrib-bibtex']}
```

Changing the key to `"read-the-docs"` or entirely removing it because it is present at the end of the `dict` fixes the issue.

@kmilos for VIS.

Cheers,

Thomas

**Comment by kmilos** [comment]
Confirming that removing the `':extra == "read-the-docs"': ['numpy>=1.19,<2'],` line works around the problem on MSYS2 w/ setuptools 59.8.0

**Comment by finswimmer** [comment]
Hello @kmilos,

the problem here is that you've listed `numpy` as a member of an `extra` group, but `numpy` itself isn't marked as `optional`. This is invalid and the logic that creates the `setup.py` file assumes a valid definition. This is something we could improve.

However, please note that we are planning to deprecate the creation of the `setup.py` soon and will than remove this function completely.

fin swimmer

**Comment by kmilos** [comment]
Thanks @finswimmer, but it is @KelSolaar who is owning the project definition as reported, I was just trying to package.

We did however, find a workaround that helps us build the package using pyproject.toml only and poetry-core (sole library available on MSYS2, not the full poetry one), so this is no longer a blocker.

**Comment by KelSolaar** [comment]
> Hello @kmilos,
> 
> the problem here is that you've listed `numpy` as a member of an `extra` group, but `numpy` itself isn't marked as `optional`. This is invalid and the logic that creates the `setup.py` file assumes a valid definition. This is something we could improve.
> 
> However, please note that we are planning to deprecate the creation of the `setup.py` soon and will than remove this function completely.
> 
> fin swimmer

Hi @finswimmer,

Thanks now that you point that out, it makes total sense! I have fixed our `pyproject.toml` file(s) accordingly. An error/exception would certainly be welcome!

Cheers,

Thomas
