### ISSUE TITLE
Poetry fails to check package from PyPI if it was found for another arch on a private repo

### ISSUE THREAD

**Issue by Mindstan** [python-poetry/poetry#5227]
- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 20.04 amd64 with pyenv (python 3.6)
- **Poetry version**: 1.1.13
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/Mindstan/a39bd8d014c8e9b4e4f47535e755ba68

## Issue

We are a team using machine/deep learning on Nvidia Jetson devices (aarch64), and our project depends on `scipy@1.5.2`. Because its wheel is not available on pypi.org, we built it once and uploaded it on our private Python repository (and only for this architecture).

Until now, we were using `pip`, and pip's behavior is to search on our private repo, and if it does not find the wheel, then it looks on official PyPI for it.

We are trying now to migrate our infrastructure on poetry. I started by an empty `pyproject.toml`, added our private source, then tried to add the dependencies one-by-one, until it failed on `scipy` (`poetry add scipy@1.5.2`). By looking at the logs (joined in the gist), it is clear that poetry found the package in both private and official repositories, but didn't want to look for wheels in the pypi.org one.

**Comment by sneakers-the-rat** [comment]
Seems related to https://github.com/python-poetry/poetry/issues/5205 (in that case the private repo got wheels for a different architecture, but not including wheels from PyPI when an additional repository is the same)

**Comment by neersighted** [comment]
What you want is not possible -- Poetry will not merge dists across repos, especially as we have no way to know if a package is truly the same. However, what you are trying to achieve is possible/soon will be -- see #5205.
