### ISSUE TITLE
Poetry not listing all virtualenvs for a directory

### ISSUE THREAD

**Issue by mjohnson324-ingenovis** [python-poetry/poetry#5231]
- **OS version and name**: Mac Big Sur, 11.6.2
- **Poetry version**: 1.1.13
- **Gist:** [pyproject.toml](https://gist.github.com/mjohnson324-ingenovis/522f2c893dda0d958ebb6b54cb030cb6)

## Issue

As I understand from the documentation, running `poetry env list` in the same directory as my pyproject.toml file will list out the virtual environments associated with that directory. This command is not finding all the virtual environments.

At **/Users/<me>/Library/Caches/pypoetry/virtualenvs**:

```zsh
➜   virtualenvs ls
blaze-util-4O_h4wMZ-py3.8 search-wMNy943s-py3.8     test-api-0rvIvVuR-py3.8
```
When I go to the **search** directory I don't see search-wMNy943s-py3.8. I get nothing back when running `poetry env list`. I may have switched git branches at one point, but shouldn't poetry reference the same virtual environment as long as the path doesn't change? I've never altered the path.

**Comment by finswimmer** [comment]
Hello @mjohnson324-ingenovis,

the hash in the middle of the venv name is based on the location of the project. So maybe you've change this location at some point?

fin swimmer

**Comment by mjohnson324-ingenovis** [comment]
Maybe. If I can't figure out the original location for a virtual environment, how can I safely delete it?

**Comment by finswimmer** [comment]
> how can I safely delete it?

Just delete the venv folder.

**Comment by mjohnson324-ingenovis** [comment]
Ok. I'll let you know if a similar issue arises again; I'll close this for now.
