### ISSUE TITLE
poetry show gives clickit "NoSuchOptionException(name)" error

### ISSUE THREAD

**Issue by swills1** [python-poetry/poetry#5240]
- [x ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Fedora 35
- **Poetry version**: 3.10.1
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: N/A
## Issue
Hello.

I am getting this clickit error;

```
NoSuchOptionException

  The "--show" option does not exist.

  at ~/.local/lib/python3.10/site-packages/clikit/args/default_args_parser.py:300 in _add_long_option
      296│     def _add_long_option(
      297│         self, name, value, tokens, fmt, lenient
      298│     ):  # type: (str, Optional[str], List[str], ArgsFormat, bool) -> None
      299│         if not fmt.has_option(name):
    → 300│             raise NoSuchOptionException(name)
      301│ 
      302│         option = fmt.get_option(name);
      303│ 
      304│         if value is False:
```

These are the steps to reproduce

 ```
poetry new packagename
cd packagename
poetry shell
poetry --show
```

This isn't preventing work, I just wanted to report it. I did search issues, but I may have missed one talking about this.

**EDIT**

I was turned around on what I was doing - true issue is - https://github.com/python-poetry/poetry/issues/5240#issuecomment-1052926766

**Comment by branchvincent** [comment]
I believe you're looking for the [`poetry show`](https://python-poetry.org/docs/cli/#show) command

**Comment by swills1** [comment]
I apologize, I wasn't thinking when I posted.. I do get an error with poetry show, I completely typed up the wrong thing. So

- poetry new package
- cd package
- poetry shell
- poetry show

SolverProblemError

  Because test depends on pytest (^5.2) which doesn't match any versions, version solving failed.

  at ~/.local/lib/python3.10/site-packages/poetry/puzzle/solver.py:241 in _solve
      237│             packages = result.packages
      238│         except OverrideNeeded as e:
      239│             return self.solve_in_compatibility_mode(e.overrides, use_latest=use_latest)
      240│         except SolveFailure as e:
    → 241│             raise SolverProblemError(e)
      242│ 
      243│         results = dict(
      244│             depth_first_search(
      245│                 PackageNode(self._package, packages), aggregate_package_nodes

**Comment by swills1** [comment]
I apologize, I wasn't thinking when I posted.. I do get an error with `poetry show`, I completely typed up the wrong thing. Basically I got this earlier today, came back and wasn't thinking and id --show and got a different error and posted all of that without thinking.. The true issue I have is the following;

1. poetry new package
2. cd package
3. poetry shell
4. poetry show

```
SolverProblemError

  Because test depends on pytest (^5.2) which doesn't match any versions, version solving failed.

  at ~/.local/lib/python3.10/site-packages/poetry/puzzle/solver.py:241 in _solve
      237│             packages = result.packages
      238│         except OverrideNeeded as e:
      239│             return self.solve_in_compatibility_mode(e.overrides, use_latest=use_latest)
      240│         except SolveFailure as e:
    → 241│             raise SolverProblemError(e)
      242│ 
      243│         results = dict(
      244│             depth_first_search(
      245│                 PackageNode(self._package, packages), aggregate_package_nodes
```

**Comment by branchvincent** [comment]
Ah, no worries. Indeed, I can reproduce. Thanks for the report!

It seems this bug is triggered by a missing `poetry.lock` file, which `show` implicitly uses to display your dependencies. I'll try to spend time on a fix later.
