### ISSUE TITLE
Make `poetry version` change the `__version__` variable automatically

### ISSUE THREAD

**Issue by John15321** [python-poetry/poetry#5245]
I know there is an issue for that but I don't think there is a feature request for that
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

Please make the `poetry version x.x.x` command update the version not only in the `pyproject.toml` file but also in the created `__init__.py` file. Otherwise, I really don't see the point of this command for bumping versions if it's not bumping it everywhere

**Comment by finswimmer** [comment]
Hello @John15321,

please see https://github.com/python-poetry/poetry/issues/2614#issuecomment-652766308.

fin swimmer
