### ISSUE TITLE
Can I use `core.vcs.git` in `libvcs`?

### ISSUE THREAD

**Issue by tony** [python-poetry/poetry#5253]
Hi!

@abn @branchvincent @dimbleby

Can I have your permission to use your changes from [`poetry.core.vcs`](https://github.com/python-poetry/poetry-core/blob/fa93845ed48f8ba392da3628fd5718a84ebae5d6/src/poetry/core/vcs/__init__.py) + [`poetry.core.vcs.git`](https://github.com/python-poetry/poetry-core/blob/d9ed333ef0c98e185a79e0f98093e7c5c4d817be/src/poetry/core/vcs/git.py) in [libvcs](https://github.com/vcs-python/libvcs/) for [`libvcs.git`](https://github.com/vcs-python/libvcs/blob/11b4993/libvcs/git.py)?

It's one of the first python projects I made. I was literally mashing together pip and saltstack from from first half 2010 and I had zero experience making a maintainable API.

libvcs is MIT and poetry core is MIT.

**Comment by dimbleby** [comment]
> poetry core is MIT

is all you need to know

**Comment by tony** [comment]
I've found this was more effort than I realized. On GitHub, the history is `--follow`'d, there's quite a few committers.

https://github.com/python-poetry/poetry-core/commits/c21fd678/poetry/core/vcs/git.py

I'm leaning toward closing this and reaching out to big committers on my own

**Comment by tony** [comment]
I've found this was more effort than I realized. On GitHub, the history is `--follow`'d, there's quite a few committers.

https://github.com/python-poetry/poetry-core/commits/c21fd678/poetry/core/vcs/git.py

I've closed this
