### ISSUE TITLE
Poetry upgrade not updating packages

### ISSUE THREAD

**Issue by JoeyG1973** [python-poetry/poetry#5257]
There is clearly an upgrade for top level packages like fastapi, but poetry is not updating them even though the toml file is not locked to a specific version.  This could very well be me not knowing the tool well enough but every indication I have says that it should be updating them, but it won't.  What I am not capturing here because of the lack of ansi is that it is only updating the ones that are RED when `poetry update` is run.  This is either a defect, there needs to be a switch to `update` that handles the updates that show in YELLOW when running `poertry show -o`, or I have no clue what is going on and I need to be educated.  The 3rd option in this scenario is the most likely.

[myserver]$ poetry --version
Poetry version 1.1.13

```
poetry show -o
black      21.12b0 22.1.0 The uncompromising code formatter.
boto3      1.21.5  1.21.9 The AWS SDK for Python
botocore   1.24.5  1.24.9 Low-level, data-driven core of boto 3.
fastapi    0.70.1  0.74.1 FastAPI framework, high performance, easy to learn, fast to code, ready for production
s3transfer 0.5.1   0.5.2  An Amazon S3 Transfer Manager
starlette  0.16.0  0.18.0 The little ASGI library that shines.
tomli      1.2.3   2.0.1  A lil' TOML parser
uvicorn    0.16.0  0.17.5 The lightning-fast ASGI server.
```

```
poetry update
Updating dependencies
Resolving dependencies... (9.6s)

Writing lock file

Package operations: 0 installs, 3 updates, 0 removals

  • Updating botocore (1.24.5 -> 1.24.9)
  • Updating s3transfer (0.5.1 -> 0.5.2)
  • Updating boto3 (1.21.5 -> 1.21.9)

```

```
poetry show -o
black     21.12b0 22.1.0 The uncompromising code formatter.
fastapi   0.70.1  0.74.1 FastAPI framework, high performance, easy to learn, fast to code, ready for production
starlette 0.16.0  0.18.0 The little ASGI library that shines.
tomli     1.2.3   2.0.1  A lil' TOML parser
uvicorn   0.16.0  0.17.5 The lightning-fast ASGI server.
```

```
[tool.poetry]
name = "name"
version = "0.1.0"
description = ""
authors = ["no-emai@nunya.biz"]

[tool.poetry.dependencies]
python = "^3.8"
fastapi = "^0.70.1"
boto3 = "^1.20.26"
python-json-logger = "^2.0.2"
uvicorn = "^0.16.0"
PyYAML = "^6.0"

[tool.poetry.dev-dependencies]
black = "^21.12b0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[settings.virtualenvs]
in-project = "true"
```

**Comment by finswimmer** [comment]
Hey @JoeyG1973 ,

`poetry update` updates the packages within the version range given in the `pyproject.toml`. So in case of `fastapi` and the version constraint `^0.70.1` it will update to any version between >=0.70.1 and <0.71. To get the latest version do a `poetry add fastapi@latest`.

Currently there is no upgrade command that upgrade all dependency to its latest version regardless of the given version constraint.

fin swimmer

**Comment by acdha** [comment]
I created a discussion about how Poetry's UI could make this situation less surprising: https://github.com/orgs/python-poetry/discussions/8158
