### ISSUE TITLE
Poetry to define virtualenvs regardless of a package

### ISSUE THREAD

**Issue by stefanoborini** [python-poetry/poetry#5263]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

Poetry is, by nature, connected to PEP-517 and the pyproject.toml specifications, so it is tailored to something that is fundamentally a python package, such as a library or an application. However, in some cases, I would like to define a well-constructed python environment that is not associated to a package, because it would make little sense to do so.

For example, I currently have a source code in R, but to test and stress the web application I use selenium and python with pytest. To run this testsuite, I need pytest, some pytest plugins, selenium, and many other packages. At the moment, I use simple pip installs, but it would be nice to be able to specify these dependencies and the management of a virtual env using poetry.

This issue would require specification of poetry config outside of a pyproject.toml, because it is intrinsically not a package. It's just a bunch of python test files, ran by pytest. Of course I could misuse the pyproject.toml file and claim it's a package, but it's a bit wrong. 

I see other scenarios where poetry would be managing just virtualenvs without necessarily handling an associated python package.

**Comment by finswimmer** [comment]
Hello @stefanoborini,

something like this has been asked before in https://github.com/python-poetry/poetry/issues/1132.

fin swimmer
