### ISSUE TITLE
Add more details on the name field

### ISSUE THREAD

**Issue by simgunz** [python-poetry/poetry#5267]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

The description of the `name` field should include what are the supported formats for the name (supports capital case? spaces?) and how it relates to the package name.

**Comment by Secrus** [comment]
This is package name as specified by PyPA and [PEP-508](https://peps.python.org/pep-0508/#names). This indeed could be described better. PRs are welcome.
