### ISSUE TITLE
Support auth token to publish

### ISSUE THREAD

**Issue by whchun** [python-poetry/poetry#5285]
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

Currently, poetry config supports `http-basic` which requires username and password or ` pypi-token` which requires API Token in order to publish. Package manager like `yarn` also allow `authToken` (JWT Authentication Token) to publish to registry. I can also use `curl` command and set Authorization Header with `authToken`, and can upload (or PUT) poetry build to pypi repo.

Can poetry supports additional config `authToken`, like  `poetry config auth-token.<repo> <value>` for publishing?

**Comment by whchun** [comment]
It's my mistake and the feature  already exists. `authToken` is achievable using `http-basic` and provide as a password. Closing since no further action is needed.

**Comment by miohtama** [comment]
Just for a clarification for anyone who is looking for this information.

If you do not want to create Poetry configuration you can publish on PyPi simply with:

```shell
poetry publish -u __token__ -p pypi-yourlongtokengoeshere...
```

You can get the token from *Add API Token* page on your PyPi profile.
