### ISSUE TITLE
Version constraints on extras

### ISSUE THREAD

**Issue by gregorybchris** [python-poetry/poetry#5287]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request
I'm surprised this issue/feature request does not exist, so maybe this feature is already supported and I totally missed it or its implementation is impossible/impractical for some reason.

It would be nice if there were a way to constrain the versions of "extras". This is useful when package `X` doesn't ship with dependency `Y`, but `X` does support some feature that depends on `Y` and only for versions of `Y` in the range `[a, b)`. Since `X` is not guaranteed to work with versions of `Y` outside `[a, b)`, that constraint should be specified to Poetry in the `pyproject.toml` file.

```toml
[tool.poetry.extras]
visualization = [
    { package = "matplotlib", version = "^3.4.0" },
]
```

In this toy example we specify that our optional visualization features rely on `matplotlib` functionality introduced in or after version `3.4.0`. We indicate that earlier versions of `matplotlib` (e.g. version `3.3.4`) are not compatible with our package and our visualization features are not guaranteed to work.

**Comment by dimbleby** [comment]
Specify it like this in `[tool.poetry.dependencies]`.
```
matplotlib = { version = "^3.4.0", optional = true }
```

Maybe the documentation has improved since this was raised, https://python-poetry.org/docs/pyproject#extras seems pretty clear, reckon this can be closed

**Comment by HarHarLinks** [comment]
This should include extra dependencies' extras as well, e.g. I want to use

```
[tool.poetry.dependencies]
matrix-nio = "^0.19.0"

[tool.poetry.extras]
e2e = {package = "matrix-nio", extras = ["e2e"], version = "^0.19.1"}
```

in order to add the extra `e2e` to my package. Upon installing my package with the `e2e` extra, poetry should pull in matrix-nio's `e2e` extra.

I don't think this case is currently possible, is it?
