### ISSUE TITLE
poetry install gives strange error

### ISSUE THREAD

**Issue by mhoangvslev** [python-poetry/poetry#5294]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: MacOS 12.2.1 Monerey with Apple M1
- **Poetry version**: 1.11.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: None

## Issue

When I execute `poetry run`, it tells me that the file I am executing is not in a completely different directory.

```bash
FileNotFoundError

  [Errno 2] No such file or directory: b'/Library/TeX/texbin/main.py'

  at ~/miniconda3/envs/sparql-vis/lib/python3.9/os.py:607 in _execvpe
       603│         path_list = map(fsencode, path_list)
       604│     for dir in path_list:
       605│         fullname = path.join(dir, file)
       606│         try:
    →  607│             exec_func(fullname, *argrest)
       608│         except (FileNotFoundError, NotADirectoryError) as e:
       609│             last_exc = e
       610│         except OSError as e:
       611│             last_exc = e
```
`/Library/TeX/texbin/main.py` is not where the project is located

**Comment by finswimmer** [comment]
Hello @mhoangvslev,

`poetry run` expects an argument to know what should run within the venv. Something like `poetry run python --version`.

The error message is already better in the current preview release (1.2.0a2):

```
$ poetry run

Not enough arguments (missing: "args")
```

fin swimmer
