### ISSUE TITLE
poetry add pulls incorrect python version of package

### ISSUE THREAD

**Issue by MaineTim** [python-poetry/poetry#5296]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Linux helios 5.16.11-1 x86_64
- **Poetry version**: Poetry version 1.1.13
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/MaineTim/1c647fa935d6cd08d7815f43b6e02ff8

## Issue

Attempting to use getch via "poetry add getch" fails, apparently because it pulls the python 2 version of getch. pip3 install selects correct version. Is there a way to force poetry to use the python 3 version?

```
(process-csv-wi9Py-Ow-py3.10) tim@helios:~/Sync/programs/process_csv> poetry add getch
Using version ^1.0 for getch

Updating dependencies
Resolving dependencies... (6.8s)

Writing lock file

Package operations: 1 install, 0 updates, 0 removals

  • Installing getch (1.0)

(process-csv-wi9Py-Ow-py3.10) tim@helios:~/Sync/Data/expenses> python ~/Sync/programs/process_csv/process_csv/process_csv.py -m 20220216.csv -o newstuff.csv CSV/*
Traceback (most recent call last):
  File "/home/tim/Sync/programs/process_csv/process_csv/process_csv.py", line 3, in <module>
    import getch
ImportError: /home/tim/.cache/pypoetry/virtualenvs/process-csv-wi9Py-Ow-py3.10/lib/python3.10/site-packages/getch.cpython-310-x86_64-linux-gnu.so: undefined symbol: Py_InitModule

(process-csv-wi9Py-Ow-py3.10) tim@helios:~/Sync/programs/process_csv> poetry remove getch
Updating dependencies
Resolving dependencies... (0.2s)

Writing lock file

Package operations: 0 installs, 0 updates, 1 removal

  • Removing getch (1.0)
(process-csv-wi9Py-Ow-py3.10) tim@helios:~/Sync/programs/process_csv> pip3 install getch
Collecting getch
  Downloading getch-1.0.tar.gz (1.3 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: getch
  Building wheel for getch (setup.py) ... done
  Created wheel for getch: filename=getch-1.0-cp310-cp310-linux_x86_64.whl size=9995 sha256=f6517afaf51d90474347617cfd0bbbf58d30d20cc769c498fc563a4ef387c86f
  Stored in directory: /home/tim/.cache/pip/wheels/ac/c4/98/3509ed1eea91cd925ecf8601b085d8faf13c9d5269653f4325
Successfully built getch
Installing collected packages: getch
Successfully installed getch-1.0

```
I tried specifying the python version in pyproject.toml directly, but it still pulls the python 2 version.

```
getch = { version = "*", python = "^3.0" }
```

Thanks!

**Comment by dimbleby** [comment]
getch provides two separate source tarballs and trusts that downloaders will pick the right one.  

So far as I know this is more hope than expectation, poetry has no reason to guess which is better.  It happens to guess wrong.

I believe that the expected approach is that packages such as getch should provide a single source, making use of `#if PY_MAJOR_VERSION >= 3` to compile the appropriate code for python2 / python3 eg see http://python3porting.com/cextensions.html for more.

Last (and only) release was in 2013 so I doubt that there's a getch maintainer out there who's likely to fix this; but I don't see a poetry bug.

**Comment by MaineTim** [comment]
Thanks for following up on it. I'll close this and ask about mitigation strategies in the discussion forums.
