### ISSUE TITLE
EnvCommandError "[...] is not a supported wheel on this platform"

### ISSUE THREAD

**Issue by TheDataScientistNL** [python-poetry/poetry#5302]
[x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
[x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
[x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Win10Pro, build 19044
- **Poetry version**: 1.1.13
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/TheDataScientistNL/6875cf5c40e9bdc6ad466a78395c49b6

## Issue
When locally using the command *poetry install* with the pyproject.toml file as attached via gist.github, I get a successful install of all packages. However, as soon as I build inside a Docker, I hit upon an EnvCommandError:

`Command ['/opt/venv/bin/python3', '-m', 'pip', 'install', '--no-deps', '/app/build_wheels/GDAL-3.2.3-cp39-cp39-win_amd64.whl'] errored with the following return code 1, and output:        
ERROR: GDAL-3.2.3-cp39-cp39-win_amd64.whl is not a supported wheel on this platform.`

The error occurs when trying to install build wheels in Docker that have been placed in a folder "build_wheels". Poetry is able to install the three build wheels perfectly locally (outside Docker), but not when building the Dockerfile (see attached in Gist).

What am I doing wrong? Or is this a bug in poetry?

**Comment by eyllanesc** [comment]
@TheDataScientistNL The docker image is based on Linux (`python:3.9-slim-buster`) but you are trying a wheel for Windows: `./build_wheels/GDAL-3.2.3-cp39-cp39-win_amd64.whl` don't you think it is inconsistent?

**Comment by TheDataScientistNL** [comment]
I put some ice on that burn. Thanks, that was stupid from my side.

**Comment by TheDataScientistNL** [comment]
@eyllanesc and others.

Update: I rebuilt the Dockerfile purely windows-based. However, the same error still occurs. Here's a link to the new gist: https://gist.github.com/TheDataScientistNL/689433aa3f3319845338aeada087cc3a

Meanwhile, same error but different basis might be: [#5104](https://github.com/python-poetry/poetry/issues/5104).

Error: 
`
  EnvCommandError

  Command C:\app\.venv\Scripts\pip.exe install --no-deps C:\app\build_wheels\GDAL-3.2.3-cp39-cp39-win_amd64.whl errored with the following return code 1, and output:
  ERROR: GDAL-3.2.3-cp39-cp39-win_amd64.whl is not a supported wheel on this platform.


  at ~\.poetry\lib\poetry\utils\env.py:1195 in _run
      1191│                 output = subprocess.check_output(
      1192│                     cmd, stderr=subprocess.STDOUT, **kwargs
      1193│                 )
      1194│         except CalledProcessError as e:
    → 1195│             raise EnvCommandError(e, input=input_)
      1196│
      1197│         return decode(output)
      1198│
      1199│     def execute(self, bin, *args, **kwargs):
`

**Comment by eyllanesc** [comment]
@TheDataScientistNL What version of python is used inside docker? I'm pointing this out because the image looks like it uses python3.10 by default and your wheel is for python 3.9. 

Try with:

```dockerfile
# --- BASE IMAGE WITH GENERAL SETTINGS --- #
FROM winamd64/python:3.9 AS base

```

**Comment by TheDataScientistNL** [comment]
@eyllanesc  I tried your suggestion. That solved it. Again, obvious in hindsight. Was a good learning exercise on my side. Thanks a lot!

Closing issue again.
