### ISSUE TITLE
"Search for package" during poetry init does not work behind a corporate proxy

### ISSUE THREAD

**Issue by mulcahys** [python-poetry/poetry#531]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 18.04.1 LTS
- **Poetry version**: 0.12.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: n/a poetry init fails without generating pyproject.toml file

## Issue

When running poetry init in an environment behind a corporate proxy, and attempting to interactively resolve dependencies, it times out during the first run of "Search for package" with the following trace

```
Would you like to define your dependencies (require) interactively? (yes/no) [yes]    



Search for package: requests

                       
[error]  
[Errno 110] Connection timed out                
                        
Exception trace:
 /home/smulcahy/.poetry/lib/poetry/_vendor/py2.7/cleo/application.py in run() at line 94
   status_code = self.do_run(input_, output_)
 /home/smulcahy/.poetry/lib/poetry/console/application.py in do_run() at line 88
   return super(Application, self).do_run(i, o)
 /home/smulcahy/.poetry/lib/poetry/_vendor/py2.7/cleo/application.py in do_run() at line 197
   status_code = command.run(input_, output_)
 /home/smulcahy/.poetry/lib/poetry/console/commands/command.py in run() at line 77
   return super(BaseCommand, self).run(i, o)
 /home/smulcahy/.poetry/lib/poetry/_vendor/py2.7/cleo/commands/base_command.py in run() at line 146
   status_code = self.execute(input_, output_)
 /home/smulcahy/.poetry/lib/poetry/_vendor/py2.7/cleo/commands/command.py in execute() at line 107
   return self.handle()
 /home/smulcahy/.poetry/lib/poetry/console/commands/init.py in handle() at line 116
   self._determine_requirements(self.option("dependency"))
 /home/smulcahy/.poetry/lib/poetry/console/commands/init.py in _determine_requirements() at line 162
   matches = self._get_pool().search(package)
 /home/smulcahy/.poetry/lib/poetry/repositories/pool.py in search() at line 98
   results += repository.search(query, mode=mode)
 /home/smulcahy/.poetry/lib/poetry/repositories/pypi_repository.py in search() at line 203
   hits = client.search(search, "or")
 /usr/lib/python2.7/xmlrpclib.py in __call__() at line 1243
   return self.__send(self.__name, args)
 /usr/lib/python2.7/xmlrpclib.py in __request() at line 1602
   verbose=self.__verbose
 /usr/lib/python2.7/xmlrpclib.py in request() at line 1283
   return self.single_request(host, handler, request_body, verbose)
 /usr/lib/python2.7/xmlrpclib.py in single_request() at line 1311
   self.send_content(h, request_body)
 /usr/lib/python2.7/xmlrpclib.py in send_content() at line 1459
   connection.endheaders(request_body)
 /usr/lib/python2.7/httplib.py in endheaders() at line 1038
   self._send_output(message_body)
 /usr/lib/python2.7/httplib.py in _send_output() at line 882
   self.send(msg)
 /usr/lib/python2.7/httplib.py in send() at line 844
   self.connect()
 /usr/lib/python2.7/httplib.py in connect() at line 1255
   HTTPConnection.connect(self)
 /usr/lib/python2.7/httplib.py in connect() at line 821
   self.timeout, self.source_address)
 /usr/lib/python2.7/socket.py in create_connection() at line 575
   raise err
```

The problem seems to arise in xmlrpclib which doesn't include built-in support for http or https proxies. https://docs.python.org/2/library/xmlrpclib.html#example-of-client-usage includes an example of how to instruct xmlrpclib to use a proxy. I'm not sure if the same approach will work for xmlrpc.client.

I'm not sure if poetry wants to default to the proxies defined in the users environment variables if they're set (typically some of http_proxy, https_proxy, no_proxy, HTTP_PROXY, HTTPS_PROXY, NO_PROXY) or to explicitly require a user to pass a proxy arg to poetry. Either one works although using the environment variables if set is what other tools do by default.

Thanks

**Comment by danyeaw** [comment]
I just tried this in Windows, and I was able to get the proxy to work using:
`$ set HTTPS_PROXY=<proxyHost>:<proxyPort>`
I think the equivalent in Ubuntu is:
`$ export HTTPS_PROXY=<proxyHost>:<proxyPort>`

If it works, this could be added to your ~/.bashrc as a setting.

If we verify that this works in Ubuntu, this would be a great addition to submit a PR to the documentation.

**Comment by mulcahys** [comment]
Thanks for the suggestion @danyeaw but I already have these variables set in my environment and they are working for other commands. I moved to latest release of poetry to retry this  (0.12.10) and now getting a different error - not sure if thats still due to the proxy issue?

Would you like to define your dependencies (require) interactively? (yes/no) [yes] 


```
Search for package: requests

                                       
[ImportError]           
cannot import name LegacyRepository  
                                       
init [--name NAME] [--description DESCRIPTION] [--author AUTHOR] [--dependency DEPENDENCY] [--dev-dependency DEV-DEPENDENCY] [-l|--license LICENSE]



```

**Comment by silenc3r** [comment]
I'm getting the same ImportError and I'm not using any proxy.

**Comment by kkirsche** [comment]
I also get the timeout the original issue submitter included, even though the proxy variables are set:

```
 ~/git/python/emailer $ echo $HTTP_PROXY
http://redacted.company.com:80/
 ~/git/python/emailer $ echo $HTTPS_PROXY
http://redacted.company.com:80/
 ~/git/python/emailer $ echo $http_proxy
http://redacted.company.com:80/
 ~/git/python/emailer $ echo $https_proxy
http://redacted.company.com:80/
 ~/git/python/emailer $ poetry init --name emailer

This command will guide you through creating your pyproject.toml config.

Version [0.1.0]:
Description []:
Author [Kevin Kirsche <kevin.kirsche@company.com>, n to skip]:
License []:
Compatible Python versions [^3.7]: ^3.4

Would you like to define your dependencies (require) interactively? (yes/no) [yes] yes



Search for package: requests


[TimeoutError]
[Errno 60] Operation timed out

init [--name NAME] [--description DESCRIPTION] [--author AUTHOR] [--dependency DEPENDENCY] [--dev-dependency DEV-DEPENDENCY] [-l|--license LICENSE]
```

**Comment by aihuasxy** [comment]
> I'm getting the same ImportError and I'm not using any proxy.
> 
> Edit: traceback (poetry init -vvv)
> 
> ```
> Would you like to define your dependencies (require) interactively? (yes/no) [yes] 
> 
> 
> 
> Search for package: beautifulsoup4
> 
>                                                                                                                        
> [ImportError]                                                                                           
> cannot import name 'LegacyRepository' from 'poetry.repositories.legacy_repository' (/home/dawid/.local/lib/python3.  
> 7/site-packages/poetry/repositories/legacy_repository.py)                                                            
>                                                                                                                        
> Exception trace:
>  /home/dawid/.local/lib/python3.7/site-packages/cleo/application.py in run() at line 94
>    status_code = self.do_run(input_, output_)
>  /home/dawid/.local/lib/python3.7/site-packages/poetry/console/application.py in do_run() at line 88
>    return super(Application, self).do_run(i, o)
>  /home/dawid/.local/lib/python3.7/site-packages/cleo/application.py in do_run() at line 197
>    status_code = command.run(input_, output_)
>  /home/dawid/.local/lib/python3.7/site-packages/poetry/console/commands/command.py in run() at line 77
>    return super(BaseCommand, self).run(i, o)
>  /home/dawid/.local/lib/python3.7/site-packages/cleo/commands/base_command.py in run() at line 146
>    status_code = self.execute(input_, output_)
>  /home/dawid/.local/lib/python3.7/site-packages/cleo/commands/command.py in execute() at line 107
>    return self.handle()
>  /home/dawid/.local/lib/python3.7/site-packages/poetry/console/commands/init.py in handle() at line 126
>    self._determine_requirements(self.option("dependency"))
>  /home/dawid/.local/lib/python3.7/site-packages/poetry/console/commands/init.py in _determine_requirements() at line 172
>    matches = self._get_pool().search(package)
>  /home/dawid/.local/lib/python3.7/site-packages/poetry/repositories/pool.py in search() at line 73
>    from .legacy_repository import LegacyRepository
>  /home/dawid/.local/lib/python3.7/site-packages/poetry/repositories/legacy_repository.py in <module>() at line 33
>    from poetry.masonry.publishing.uploader import wheel_file_re
>  /home/dawid/.local/lib/python3.7/site-packages/poetry/masonry/__init__.py in <module>() at line 10
>    from .builder import Builder
>  /home/dawid/.local/lib/python3.7/site-packages/poetry/masonry/builder.py in <module>() at line 1
>    from .builders import CompleteBuilder
>  /home/dawid/.local/lib/python3.7/site-packages/poetry/masonry/builders/__init__.py in <module>() at line 1
>    from .complete import CompleteBuilder
>  /home/dawid/.local/lib/python3.7/site-packages/poetry/masonry/builders/complete.py in <module>() at line 4
>    import poetry.poetry
>  /home/dawid/.local/lib/python3.7/site-packages/poetry/poetry.py in <module>() at line 18
>    from .repositories.legacy_repository import LegacyRepository
> ```
> Edit2: this seems to be fixed in [750e31d](https://github.com/sdispater/poetry/commit/750e31de98b84e294ac6c5798ad8c4656be9dd2e)
> cc @mulcahys

I have the same problem
upgrade to 1.0.0a2 not resolve it

**Comment by JnyJny** [comment]
I am also getting the timeout  with poetry 0.12.12 with proxies set in the environment and confirmed valid.

**Comment by Kulakoff1988** [comment]
I'v got the similar problem with poetry `0.12.16`, on `upload` command. I tried to set the environment variables, all of theese: 
`set http_proxy=http://user:pwd@ip:port
set HTTP_PROXY=http://user:pwd@ip:port
set https_proxy=http://user:pwd@ip:port
set HTTPS_PROXY=http://user:pwd@ip:port`
but it doesn't work.

`[ConnectionError]
('Connection aborted.', OSError(0, 'Error'))

Exception trace:
 C:\Users\suser-0428.S1GROUP\AppData\Roaming\Python\Python37\site-packages\cleo\application.py in run() at line 94
   status_code = self.do_run(input_, output_)
 c:\users\suser-0428.s1group\appdata\local\programs\python\python37-32\lib\site-packages\poetry\console\application.py in do_run() at line 88
   return super(Application, self).do_run(i, o)
 C:\Users\suser-0428.S1GROUP\AppData\Roaming\Python\Python37\site-packages\cleo\application.py in do_run() at line 197
   status_code = command.run(input_, output_)
 c:\users\suser-0428.s1group\appdata\local\programs\python\python37-32\lib\site-packages\poetry\console\commands\command.py in run() at line 77
   return super(BaseCommand, self).run(i, o)
 C:\Users\suser-0428.S1GROUP\AppData\Roaming\Python\Python37\site-packages\cleo\commands\base_command.py in run() at line 146
   status_code = self.execute(input_, output_)
 C:\Users\suser-0428.S1GROUP\AppData\Roaming\Python\Python37\site-packages\cleo\commands\command.py in execute() at line 107
   return self.handle()
 c:\users\suser-0428.s1group\appdata\local\programs\python\python37-32\lib\site-packages\poetry\console\commands\publish.py in handle() at line 54
   self.option("repository"), self.option("username"), self.option("password")
 c:\users\suser-0428.s1group\appdata\local\programs\python\python37-32\lib\site-packages\poetry\masonry\publishing\publisher.py in publish() at line 84
   return self._uploader.upload(url)
 c:\users\suser-0428.s1group\appdata\local\programs\python\python37-32\lib\site-packages\poetry\masonry\publishing\uploader.py in upload() at line 101
   self._upload(session, url)
 c:\users\suser-0428.s1group\appdata\local\programs\python\python37-32\lib\site-packages\poetry\masonry\publishing\uploader.py in _upload() at line 185
   self._do_upload(session, url)
 c:\users\suser-0428.s1group\appdata\local\programs\python\python37-32\lib\site-packages\poetry\masonry\publishing\uploader.py in _do_upload() at line 202
   resp = self._upload_file(session, url, file)
 c:\users\suser-0428.s1group\appdata\local\programs\python\python37-32\lib\site-packages\poetry\masonry\publishing\uploader.py in _upload_file() at line 237
   headers={"Content-Type": monitor.content_type},
 C:\Users\suser-0428.S1GROUP\AppData\Roaming\Python\Python37\site-packages\requests\sessions.py in post() at line 581
   return self.request('POST', url, data=data, json=json, **kwargs)
 C:\Users\suser-0428.S1GROUP\AppData\Roaming\Python\Python37\site-packages\requests\sessions.py in request() at line 533
   resp = self.send(prep, **send_kwargs)
 C:\Users\suser-0428.S1GROUP\AppData\Roaming\Python\Python37\site-packages\requests\sessions.py in send() at line 646
   r = adapter.send(request, **kwargs)
 C:\Users\suser-0428.S1GROUP\AppData\Roaming\Python\Python37\site-packages\requests\adapters.py in send() at line 498
   raise ConnectionError(err, request=request)

publish [-r|--repository REPOSITORY] [-u|--username USERNAME] [-p|--password PASSWORD] [--build]`

**Comment by Kulakoff1988** [comment]
I'v got the similar problem with poetry 0.12.16, on upload command. I tried to set the environment variables, all of theese:
```set http_proxy=http://user:pwd@ip:port 
set HTTP_PROXY=http://user:pwd@ip:port 
set https_proxy=http://user:pwd@ip:port 
set HTTPS_PROXY=http://user:pwd@ip:port```
but it doesn't work.
```[ConnectionError]
('Connection aborted.', OSError(0, 'Error'))
Exception trace:
C:\Users\suser-0428.S1GROUP\AppData\Roaming\Python\Python37\site-packages\cleo\application.py in run() at line 94
status_code = self.do_run(input_, output_)
c:\users\suser-0428.s1group\appdata\local\programs\python\python37-32\lib\site-packages\poetry\console\application.py in do_run() at line 88
return super(Application, self).do_run(i, o)
C:\Users\suser-0428.S1GROUP\AppData\Roaming\Python\Python37\site-packages\cleo\application.py in do_run() at line 197
status_code = command.run(input_, output_)
c:\users\suser-0428.s1group\appdata\local\programs\python\python37-32\lib\site-packages\poetry\console\commands\command.py in run() at line 77
return super(BaseCommand, self).run(i, o)
C:\Users\suser-0428.S1GROUP\AppData\Roaming\Python\Python37\site-packages\cleo\commands\base_command.py in run() at line 146
status_code = self.execute(input_, output_)
C:\Users\suser-0428.S1GROUP\AppData\Roaming\Python\Python37\site-packages\cleo\commands\command.py in execute() at line 107
return self.handle()
c:\users\suser-0428.s1group\appdata\local\programs\python\python37-32\lib\site-packages\poetry\console\commands\publish.py in handle() at line 54
self.option("repository"), self.option("username"), self.option("password")
c:\users\suser-0428.s1group\appdata\local\programs\python\python37-32\lib\site-packages\poetry\masonry\publishing\publisher.py in publish() at line 84
return self._uploader.upload(url)
c:\users\suser-0428.s1group\appdata\local\programs\python\python37-32\lib\site-packages\poetry\masonry\publishing\uploader.py in upload() at line 101
self._upload(session, url)
c:\users\suser-0428.s1group\appdata\local\programs\python\python37-32\lib\site-packages\poetry\masonry\publishing\uploader.py in _upload() at line 185
self._do_upload(session, url)
c:\users\suser-0428.s1group\appdata\local\programs\python\python37-32\lib\site-packages\poetry\masonry\publishing\uploader.py in _do_upload() at line 202
resp = self._upload_file(session, url, file)
c:\users\suser-0428.s1group\appdata\local\programs\python\python37-32\lib\site-packages\poetry\masonry\publishing\uploader.py in _upload_file() at line 237
headers={"Content-Type": monitor.content_type},
C:\Users\suser-0428.S1GROUP\AppData\Roaming\Python\Python37\site-packages\requests\sessions.py in post() at line 581
return self.request('POST', url, data=data, json=json, **kwargs)
C:\Users\suser-0428.S1GROUP\AppData\Roaming\Python\Python37\site-packages\requests\sessions.py in request() at line 533
resp = self.send(prep, **send_kwargs)
C:\Users\suser-0428.S1GROUP\AppData\Roaming\Python\Python37\site-packages\requests\sessions.py in send() at line 646
r = adapter.send(request, **kwargs)
C:\Users\suser-0428.S1GROUP\AppData\Roaming\Python\Python37\site-packages\requests\adapters.py in send() at line 498
raise ConnectionError(err, request=request)
publish [-r|--repository REPOSITORY] [-u|--username USERNAME] [-p|--password PASSWORD] [--build]```

**Comment by Kulakoff1988** [comment]
I'v got the similar problem with poetry 0.12.16, on upload command. I tried to set the environment variables, all of theese:
```
set http_proxy=http://user:pwd@ip:port 
set HTTP_PROXY=http://user:pwd@ip:port 
set https_proxy=http://user:pwd@ip:port 
set HTTPS_PROXY=http://user:pwd@ip:port
```
but it doesn't work.
```
[ConnectionError]
('Connection aborted.', OSError(0, 'Error'))
Exception trace:
C:\Users\suser-0428.S1GROUP\AppData\Roaming\Python\Python37\site-packages\cleo\application.py in run() at line 94
status_code = self.do_run(input_, output_)
c:\users\suser-0428.s1group\appdata\local\programs\python\python37-32\lib\site-packages\poetry\console\application.py in do_run() at line 88
return super(Application, self).do_run(i, o)
C:\Users\suser-0428.S1GROUP\AppData\Roaming\Python\Python37\site-packages\cleo\application.py in do_run() at line 197
status_code = command.run(input_, output_)
c:\users\suser-0428.s1group\appdata\local\programs\python\python37-32\lib\site-packages\poetry\console\commands\command.py in run() at line 77
return super(BaseCommand, self).run(i, o)
C:\Users\suser-0428.S1GROUP\AppData\Roaming\Python\Python37\site-packages\cleo\commands\base_command.py in run() at line 146
status_code = self.execute(input_, output_)
C:\Users\suser-0428.S1GROUP\AppData\Roaming\Python\Python37\site-packages\cleo\commands\command.py in execute() at line 107
return self.handle()
c:\users\suser-0428.s1group\appdata\local\programs\python\python37-32\lib\site-packages\poetry\console\commands\publish.py in handle() at line 54
self.option("repository"), self.option("username"), self.option("password")
c:\users\suser-0428.s1group\appdata\local\programs\python\python37-32\lib\site-packages\poetry\masonry\publishing\publisher.py in publish() at line 84
return self._uploader.upload(url)
c:\users\suser-0428.s1group\appdata\local\programs\python\python37-32\lib\site-packages\poetry\masonry\publishing\uploader.py in upload() at line 101
self._upload(session, url)
c:\users\suser-0428.s1group\appdata\local\programs\python\python37-32\lib\site-packages\poetry\masonry\publishing\uploader.py in _upload() at line 185
self._do_upload(session, url)
c:\users\suser-0428.s1group\appdata\local\programs\python\python37-32\lib\site-packages\poetry\masonry\publishing\uploader.py in _do_upload() at line 202
resp = self._upload_file(session, url, file)
c:\users\suser-0428.s1group\appdata\local\programs\python\python37-32\lib\site-packages\poetry\masonry\publishing\uploader.py in _upload_file() at line 237
headers={"Content-Type": monitor.content_type},
C:\Users\suser-0428.S1GROUP\AppData\Roaming\Python\Python37\site-packages\requests\sessions.py in post() at line 581
return self.request('POST', url, data=data, json=json, **kwargs)
C:\Users\suser-0428.S1GROUP\AppData\Roaming\Python\Python37\site-packages\requests\sessions.py in request() at line 533
resp = self.send(prep, **send_kwargs)
C:\Users\suser-0428.S1GROUP\AppData\Roaming\Python\Python37\site-packages\requests\sessions.py in send() at line 646
r = adapter.send(request, **kwargs)
C:\Users\suser-0428.S1GROUP\AppData\Roaming\Python\Python37\site-packages\requests\adapters.py in send() at line 498
raise ConnectionError(err, request=request)
publish [-r|--repository REPOSITORY] [-u|--username USERNAME] [-p|--password PASSWORD] [--build]
```

**Comment by Kulakoff1988** [comment]
I'v got the similar problem with poetry 0.12.16, on upload command. I tried to set the environment variables, all of these:
```
set http_proxy=http://user:pwd@ip:port 
set HTTP_PROXY=http://user:pwd@ip:port 
set https_proxy=http://user:pwd@ip:port 
set HTTPS_PROXY=http://user:pwd@ip:port
```
but it doesn't work.
```
[ConnectionError]
('Connection aborted.', OSError(0, 'Error'))
Exception trace:
C:\Users\suser-0428.S1GROUP\AppData\Roaming\Python\Python37\site-packages\cleo\application.py in run() at line 94
status_code = self.do_run(input_, output_)
c:\users\suser-0428.s1group\appdata\local\programs\python\python37-32\lib\site-packages\poetry\console\application.py in do_run() at line 88
return super(Application, self).do_run(i, o)
C:\Users\suser-0428.S1GROUP\AppData\Roaming\Python\Python37\site-packages\cleo\application.py in do_run() at line 197
status_code = command.run(input_, output_)
c:\users\suser-0428.s1group\appdata\local\programs\python\python37-32\lib\site-packages\poetry\console\commands\command.py in run() at line 77
return super(BaseCommand, self).run(i, o)
C:\Users\suser-0428.S1GROUP\AppData\Roaming\Python\Python37\site-packages\cleo\commands\base_command.py in run() at line 146
status_code = self.execute(input_, output_)
C:\Users\suser-0428.S1GROUP\AppData\Roaming\Python\Python37\site-packages\cleo\commands\command.py in execute() at line 107
return self.handle()
c:\users\suser-0428.s1group\appdata\local\programs\python\python37-32\lib\site-packages\poetry\console\commands\publish.py in handle() at line 54
self.option("repository"), self.option("username"), self.option("password")
c:\users\suser-0428.s1group\appdata\local\programs\python\python37-32\lib\site-packages\poetry\masonry\publishing\publisher.py in publish() at line 84
return self._uploader.upload(url)
c:\users\suser-0428.s1group\appdata\local\programs\python\python37-32\lib\site-packages\poetry\masonry\publishing\uploader.py in upload() at line 101
self._upload(session, url)
c:\users\suser-0428.s1group\appdata\local\programs\python\python37-32\lib\site-packages\poetry\masonry\publishing\uploader.py in _upload() at line 185
self._do_upload(session, url)
c:\users\suser-0428.s1group\appdata\local\programs\python\python37-32\lib\site-packages\poetry\masonry\publishing\uploader.py in _do_upload() at line 202
resp = self._upload_file(session, url, file)
c:\users\suser-0428.s1group\appdata\local\programs\python\python37-32\lib\site-packages\poetry\masonry\publishing\uploader.py in _upload_file() at line 237
headers={"Content-Type": monitor.content_type},
C:\Users\suser-0428.S1GROUP\AppData\Roaming\Python\Python37\site-packages\requests\sessions.py in post() at line 581
return self.request('POST', url, data=data, json=json, **kwargs)
C:\Users\suser-0428.S1GROUP\AppData\Roaming\Python\Python37\site-packages\requests\sessions.py in request() at line 533
resp = self.send(prep, **send_kwargs)
C:\Users\suser-0428.S1GROUP\AppData\Roaming\Python\Python37\site-packages\requests\sessions.py in send() at line 646
r = adapter.send(request, **kwargs)
C:\Users\suser-0428.S1GROUP\AppData\Roaming\Python\Python37\site-packages\requests\adapters.py in send() at line 498
raise ConnectionError(err, request=request)
publish [-r|--repository REPOSITORY] [-u|--username USERNAME] [-p|--password PASSWORD] [--build]
```

**Comment by NargiT** [comment]
I have same issue.

Poetry 0.12.17 install with pip

```
poetry -vvv init

This command will guide you through creating your pyproject.toml config.

Package name [wesh]: 
Version [0.1.0]: 
Description []: 
Author [toto <toto@gmail.com>, n to skip]: 
License []: 
Compatible Python versions [^3.6]: 

Would you like to define your dependencies (require) interactively? (yes/no) [yes] 



Search for package: requests

                                      
[OSError]              
[Errno 101] Network is unreachable  
                                      
Exception trace:
 /home/ttchougo/.local/lib/python3.6/site-packages/cleo/application.py in run() at line 94
   status_code = self.do_run(input_, output_)
 /home/ttchougo/.local/lib/python3.6/site-packages/poetry/console/application.py in do_run() at line 88
   return super(Application, self).do_run(i, o)
 /home/ttchougo/.local/lib/python3.6/site-packages/cleo/application.py in do_run() at line 197
   status_code = command.run(input_, output_)
 /home/ttchougo/.local/lib/python3.6/site-packages/poetry/console/commands/command.py in run() at line 77
   return super(BaseCommand, self).run(i, o)
 /home/ttchougo/.local/lib/python3.6/site-packages/cleo/commands/base_command.py in run() at line 146
   status_code = self.execute(input_, output_)
 /home/ttchougo/.local/lib/python3.6/site-packages/cleo/commands/command.py in execute() at line 107
   return self.handle()
 /home/ttchougo/.local/lib/python3.6/site-packages/poetry/console/commands/init.py in handle() at line 126
   self._determine_requirements(self.option("dependency"))
 /home/ttchougo/.local/lib/python3.6/site-packages/poetry/console/commands/init.py in _determine_requirements() at line 172
   matches = self._get_pool().search(package)
 /home/ttchougo/.local/lib/python3.6/site-packages/poetry/repositories/pool.py in search() at line 80
   results += repository.search(query, mode=mode)
 /home/ttchougo/.local/lib/python3.6/site-packages/poetry/repositories/pypi_repository.py in search() at line 221
   hits = client.search(search, "or")
 /usr/lib/python3.6/xmlrpc/client.py in __call__() at line 1112
   return self.__send(self.__name, args)
 /usr/lib/python3.6/xmlrpc/client.py in __request() at line 1452
   verbose=self.__verbose
 /usr/lib/python3.6/xmlrpc/client.py in request() at line 1154
   return self.single_request(host, handler, request_body, verbose)
 /usr/lib/python3.6/xmlrpc/client.py in single_request() at line 1166
   http_conn = self.send_request(host, handler, request_body, verbose)
 /usr/lib/python3.6/xmlrpc/client.py in send_request() at line 1279
   self.send_content(connection, request_body)
 /usr/lib/python3.6/xmlrpc/client.py in send_content() at line 1309
   connection.endheaders(request_body)
 /usr/lib/python3.6/http/client.py in endheaders() at line 1234
   self._send_output(message_body, encode_chunked=encode_chunked)
 /usr/lib/python3.6/http/client.py in _send_output() at line 1026
   self.send(msg)
 /usr/lib/python3.6/http/client.py in send() at line 964
   self.connect()
 /usr/lib/python3.6/http/client.py in connect() at line 1392
   super().connect()
 /usr/lib/python3.6/http/client.py in connect() at line 936
   (self.host,self.port), self.timeout, self.source_address)
 /usr/lib/python3.6/socket.py in create_connection() at line 724
   raise err
 /usr/lib/python3.6/socket.py in create_connection() at line 713
   sock.connect(sa)

init [--name NAME] [--description DESCRIPTION] [--author AUTHOR] [--dependency DEPENDENCY] [--dev-dependency DEV-DEPENDENCY] [-l|--license LICENSE]
```

We have a proxy and a self signed certificate.
Did the job for the selfsign `REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt` but still does not work. all my http_proxy, https_proxy are set with the UPPER CASE version.

other python applications works to access outside my company with proxy + ssl.

**Comment by alexchandel** [comment]
XML RPC was dropped, yet this issue still exists.  Poetry isn't passing proxies correctly.

**Comment by alkuzad** [comment]
@alexchandel can't confirm, setting https proxy redirects correctly. Keep in mind that `http_proxy` won't work as pypi is not http but https.

**Comment by robvdl** [comment]
Today I installed poetry on a corporate network and I can confirm that poetry still does not handle being behind a proxy, a shame because I had to drop the idea of using poetry over this, such a shame.

I think I found a duplicate: https://github.com/python-poetry/poetry/issues/2833

This issue really needs to be fixed, eithe Poetry needs to respect the HTTP_PROXY / HTTPS_PROXY env vars, or provide a way to pass a proxy URL via the command line.

It does neither so I couldn't use it.

**Comment by alkuzad** [comment]
@robvdl are you sure ? From what I see the RPC api is not used anymore, just standard HTTPS api, using standard Requests session object. My experiments show it uses it correctly:

```batch
λ poetry search awscli
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): pypi.org:443
DEBUG:urllib3.connectionpool:https://pypi.org:443 "GET /search?q=awscli HTTP/1.1" 301 214
DEBUG:urllib3.connectionpool:https://pypi.org:443 "GET /search/?q=awscli HTTP/1.1" 200 21520
...

λ set HTTPS_PROXY=https://not-routable.example.com
λ poetry search awscli
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): pypi.org:443

  ProxyError

  HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /search?q=awscli (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022A6E1002C8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')))
```

Modification is simple, add this to poetry.py:
```python
import logging

logging.basicConfig(level=logging.DEBUG)
```

**Comment by robvdl** [comment]
I haven't forgotten about this, just trying to find a time to get this tested.

**Comment by alkuzad** [comment]
@robvdl if you need help I could do some meeting with you on discord or https://freeconferencing.vonage.com/ to show you the stuff

**Comment by alexKiew** [comment]
@alkuzad Hello Dawid, i have Problem same as @robvdl. I have Raspberry Pi4 Board behind proxi and I don't know how overcam this Problem from poetry. Can you explain me? Where can I write proxy data, for poetry?
regards

**Comment by sify21** [comment]
Hi everyone, I'm trying to update poetry behind a socks5 proxy, and it reports this error, maybe it's a related problem?
```
❯ poetry self update --preview

  InvalidSchema

  Missing dependencies for SOCKS support.

  at .poetry/lib/poetry/_vendor/py3.9/requests/adapters.py:47 in SOCKSProxyManager
       43│ try:
       44│     from urllib3.contrib.socks import SOCKSProxyManager
       45│ except ImportError:
       46│     def SOCKSProxyManager(*args, **kwargs):
    →  47│         raise InvalidSchema("Missing dependencies for SOCKS support.")
       48│ 
       49│ DEFAULT_POOLBLOCK = False
       50│ DEFAULT_POOLSIZE = 10
       51│ DEFAULT_RETRIES = 0
```

**Comment by neersighted** [comment]
Current versions of Poetry respect the `PROXY_`/`proxy_` environmental variables in `poetry search`.

**Comment by bjmd** [comment]
> Hi everyone, I'm trying to update poetry behind a socks5 proxy, and it reports this error, maybe it's a related problem?
> 
> ```
> ❯ poetry self update --preview
> 
>   InvalidSchema
> 
>   Missing dependencies for SOCKS support.
> 
>   at .poetry/lib/poetry/_vendor/py3.9/requests/adapters.py:47 in SOCKSProxyManager
>        43│ try:
>        44│     from urllib3.contrib.socks import SOCKSProxyManager
>        45│ except ImportError:
>        46│     def SOCKSProxyManager(*args, **kwargs):
>     →  47│         raise InvalidSchema("Missing dependencies for SOCKS support.")
>        48│ 
>        49│ DEFAULT_POOLBLOCK = False
>        50│ DEFAULT_POOLSIZE = 10
>        51│ DEFAULT_RETRIES = 0
> ```

Hi. Did you get this resolved? I see the issue was closed and marked as completed, but it still doesn't work for me.

**Comment by neersighted** [comment]
Your Python does not support `SOCKSProxyManager` -- this is not an issue with Poetry, but an issue with the Python on your local machine.
