### ISSUE TITLE
Build-System dependency install fails with 1.2.0a2

### ISSUE THREAD

**Issue by Freddy-scieneers** [python-poetry/poetry#5310]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS 12.1 (21C52)
- **Poetry version**: 1.2.0a2
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 
- [pyproject.toml](https://gist.github.com/freddy35/2f1bfe1882921b0459dd6e3e4c4b6c6d)
- [Log poetry 1.2.0a2](https://gist.github.com/freddy35/8fe3729144cef4ba8f481b4c63a2c6f6)
- [Log poetry 1.1.13](https://gist.github.com/freddy35/938e50723f65930c8f978f6d9e13ae99)
## Issue

Hey guys,

I have problems installing dependencies with 1.2.0a2 when they require a build-system. I try to install fasttext, this requires pybind11 as dependency. When I specify the necessary packages under [build-system] as required in my pyproject.toml, this only works with 1.1.13 and not with 1.2.0a2.

Cheers

Freddy

**Comment by mastern2k3** [comment]
Hey @freddy35, I forked **fasttext** and added the required `pyproject.toml` with the required build section.
https://github.com/mastern2k3/fastText
The following works for me now:
```
poetry add git+https://github.com/mastern2k3/fastText.git#main
```
