### ISSUE TITLE
poetry is really slow and no useful information is displayed to show what it is doing. 

### ISSUE THREAD

**Issue by felixgao** [python-poetry/poetry#5327]
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Issue

I have poetry installed with 1.1.13 and I have tried to downgrade to 1.1.12 but the same behavior is observed.  

The commands issued within certain repositories are order of magnitude slower compared to other repositories. 
![image](https://user-images.githubusercontent.com/1153820/158692624-e7674c7c-3b84-4c71-8a11-01fff1377dfe.png)

The above image, I have to ctrl-c to stop it because those command does not seems to be responding after waiting a while.
![image](https://user-images.githubusercontent.com/1153820/158692783-e9d2671c-8788-403a-9ff2-fa5d5a38cd89.png)
while the same version of the poetry in a different repository seems to be running much faster. 

![image](https://user-images.githubusercontent.com/1153820/158693357-80753e91-13ba-47a2-821a-78a91d062939.png)
I even tried the verbose mode and nothing is showing what it is doing.

**Comment by dimbleby** [comment]
this is unactionable.  

You have deleted the part of the issue template that asks for your pyproject.toml and poetry.lock, which are the things that would at least give other people a chance of reproducing what you see.

**Comment by finswimmer** [comment]
Hello @felixgao,

you haven't come back to this issue for a long while. So I assume this is solved in the meantime and I can close this ticket.

Feel free to leave a comment if you disagree.

fin swimmer
