### ISSUE TITLE
Poetry ignores `install-requires` in git dependency

### ISSUE THREAD

**Issue by devyntk** [python-poetry/poetry#5329]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**:  Arch Linux
- **Poetry version**: 1.1.13
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/devyntk/7156d2e21af2c6992cd579812db5b35e

## Issue

This is somewhat related to #4648 but fundamentally a different issue: the issue here is that I'm installing a dependency that _only_ defines a setup.cfg and setup.py, no presence of pyproject.toml or any other poetry related dependencies. In this instance, it should indeed be respecting the install_requires section of setup.cfg (of my fork of django-cms) which would install django, but this seems to be not happening. As such, the install fails as the `__init__` file cannot import django.

**Comment by finswimmer** [comment]
Hello @devyntk,

`install_requires` is the `setuptools` way to declare the runtime dependencies. See https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#install-requires. It is not meant for declaring dependencies needed for build the package. This must be done via the `build-system` section in the `pyproject.toml`.

Please contact the maintainers of `django-cms` and tell them, there is a need for either define the build dependencies in the `pyroject.toml` or they refactor how they read the `__version__` in the `setup.py` in a way that `django` will not be imported as well.

fin swimmer
