### ISSUE TITLE
Poetry should check for and disallow duplicate, unnormalized dependency names.

### ISSUE THREAD

**Issue by ncoish** [python-poetry/poetry#5340]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

Recently, my organization started shipping one of our tools using [namespace packaging](https://packaging.python.org/en/latest/guides/packaging-namespace-packages/), which essentially allows the deployment of code which appears to be in a single "package" to be split across multiple Python packages, but shares a root package namespace.

This has allowed us to ship, for example, 3 packages which can be imported in this form:
```python
import my_package.A
import my_package.B
import my_package.C
```

With users sometimes installing these packages in their own projects as:
```bash
$ poetry add my_package.A
$ poetry add my_package.B
$ poetry add my_package.C
```

This actually works fine, but adds the packages to `pyproject.toml` in quotes, presumably to ensure it is still valid TOML.

The problem is that users can install these packages using completely different delimiters, and poetry will not disallow, or give any warning about this. For example, each of the following calls will install the same package from pypi:
```bash
$ poetry add my.package.A
$ poetry add my.package_A
$ poetry add my_package.A
$ poetry add my_package_A
```
But will result in a `pyproject.toml` which looks like this:
![image](https://user-images.githubusercontent.com/1967292/159389222-5722bbe4-2f8c-4ff4-b50b-89c2929c48b6.png)

This becomes more problematic if one name for the package is installed with version A, then a user tries to add the same package with a different name at version B. Poetry has no issues with this, and will even generate a lockfile containing both package versions. I have seen different behaviour in different tests with regards to what happens when you then try to use `poetry install` with this lockfile. Occasionally it errors out, explicitly saying that the project requires two versions of the same package and won't allow it. In other cases it happily installs the package twice, leaving it at whichever version if happened to pick last.

According to [PEP 503](https://peps.python.org/pep-0503/#normalized-names), these name specifications are all valid, and there shouldn't be any ambiguity. Because of this, I think that Poetry should check the names of all specified dependencies during relevant operations, and throw an error if two names actually represent the same package.

I was unsure of whether to submit this as a feature request, or a bug. Happy to move this if it seems more bug-like! Also happy to help contribute a fix if this all makes sense.

**Comment by dimbleby** [comment]
I tried (on master) a series like
```
poetry add zope.interface
poetry add zope_interface
poetry add zope-interface
```
etc and at the end of it all I only have one `"zope.interface"` in `pyproject.toml`.

So this seems fixed.

**Comment by neersighted** [comment]
This is no longer reproducible thanks to normalization improvements.
