### ISSUE TITLE
"poetry show" option "--no-dev" is not working 

### ISSUE THREAD

**Issue by fbrodrigorezino** [python-poetry/poetry#5347]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: MacOS 12.3
- **Poetry version**: 1.1.13
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: [here](https://gist.github.com/fbrodrigorezino/fda41f15c2dfe7928b5f47f565195457)

## Issue
When I use 'poetry show mypy --no-dev' it outputs all the dependencies. I took a look at the [code](https://github.com/python-poetry/poetry/blob/15f6ec1758d783d4cb3070a8027725bc611c0a90/src/poetry/console/commands/show.py#L99), at it seems it is about to be deprecated but the `--without dev` also does not work.

**Comment by radoering** [comment]
`--without` will be introduced in poetry `1.2.0` and is not yet available in `1.1.x`. You can try `1.2.0b1` if you like. (But you should keep in mind that there are still some improvements and bugfixes on the way. See #5338)
