### ISSUE TITLE
`poetry shell` not use `nushell` when spawning shell for virtual environment

### ISSUE THREAD

**Issue by gunungpw** [python-poetry/poetry#5349]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows 10
- **Poetry version**: 1.1.13
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**:
```
[tool.poetry]
name = "demo-shellingham"
version = "0.1.0"
description = ""
authors = ["Gunung Pambudi W. <gunungpambudiw@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
shellingham = "^1.4.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

## Issue

Poetry shell command doesn't spawn virtual environment with intended shell. In this case poetry not use [Nushell](https://www.nushell.sh/). This problem is caused by `shellingham` dependency not detect `nushell` in this case `nu.exe` but detect other shell like `pwsh.exe` or `cmd.exe` following COMSPEC env variable in Windows.
I make PR in `shellingham` to include `nushell`

sarugaku/shellingham#56

edit: PR already merge

**Comment by Secrus** [comment]
`shellingham` might have merged your PR, but it still didn't make new release (since 2019 from the looks of it). I doubt Poetry core team will be willing to source package from repo master.

**Comment by gunungpw** [comment]
`shellingham` last release was Feb 2021, and the maintainer is very active in packaging python community, also that package used in `PDM`, `poetry`, and `Pipenv`. the aim for this issue is not to pressure poetry to vendor the package, because it's not an urgent matter. it is just info, for other people that use `nushell` so they can just patch the lib for themself
