### ISSUE TITLE
Allow specification of minimum required poetry version

### ISSUE THREAD

**Issue by kasium** [python-poetry/poetry#5350]
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request
A project might use newer poetry versions or rely on a poetry bug fix. Currently, the project either needs to state the minimum needed poetry version somewhere in their docs or have a kind of bootstramp to enforce that.
However, it would be nice if poetry would allow users to define that in the toml.

```toml
[tool.poetry]
poetry_version = ">1.1"
```

Please note, that this is different from the build backend. The main poetry version e.g. creates the lock file and here a different poetry version can make a huge differce.

In the case, that the current version doesn't match the one in the toml, a error should be raised

**Comment by finswimmer** [comment]
Hello @kasium,

this has been asked earlier in https://github.com/python-poetry/poetry/issues/3316.

fin swimmer
