### ISSUE TITLE
ParseVersionError when calling poetry env use "version" on Windows (in combination with pyenv)

### ISSUE THREAD

**Issue by MennoK** [python-poetry/poetry#5353]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows 10
- **Poetry version**:  1.1.13
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue

I installed poetry using the recommended powershell command in the readme

```powershell
C:\Users\my_user\Desktop> Invoke-WebRequest -Uri https://install.python-poetry.org -UseBasicParsing).Content | python -
C:\Users\my_user\Desktop> poetry --version
Poetry version 1.1.13
```

I use pyenv-win for managing python versions

```powershell
C:\Users\my_user\Desktop> pyenv --version
pyenv 2.64.11
C:\Users\my_user\Desktop> pyenv versions
  3.8.0
* 3.8.5 (set by %PYENV_VERSION%)
  3.9.5 
```

Next I create a standard poetry project

```powershell
C:\Users\my_user\Desktop> mkdir test


    Directory: C:\Users\my_user\Desktop


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        3/24/2022  10:04 AM                test


C:\Users\my_user\Desktop> cd test
C:\Users\my_user\Desktop\test> poetry init

This command will guide you through creating your pyproject.toml config.

Package name [test]:  test
Version [0.1.0]:
Description []:
Author [None, n to skip]:  n
License []:
Compatible Python versions [^3.9]:

Would you like to define your main dependencies interactively? (yes/no) [yes] n
Would you like to define your development dependencies interactively? (yes/no) [yes] n
Generated file

[tool.poetry]
name = "test"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


Do you confirm generation? (yes/no) [yes] y
```

Next when I want to switch the env using `poetry env use 3.9`, it also happens for version 3.8. for example, I receive a parse error

```powershell
C:\Users\my_user\Desktop\test> pyenv shell 3.9.5
C:\Users\my_user\Desktop\test> poetry env use 3.9.5

  ParseVersionError

  Unable to parse "".

  at ~\AppData\Roaming\pypoetry\venv\lib\site-packages\poetry\core\semver\version.py:211 in parse
      207│         except TypeError:
      208│             match = None
      209│
      210│         if match is None:
    → 211│             raise ParseVersionError('Unable to parse "{}".'.format(text))
      212│
      213│         text = text.rstrip(".")
      214│
      215│         major = int(match.group(1))
```

Also, following pop-up appears:
![image](https://user-images.githubusercontent.com/3978425/159884530-e1ceee8d-d118-4f0d-a083-0fa718197bb7.png)

Something I noticed if I install via the get-poetry.py installer which is not recommended anymore, the error does not occur, so alternatively I could install via 

```powershell
C:\Users\my_user\Desktop> (Invoke-WebRequest -Uri https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py -UseBasicParsing).Content | python -
C:\Users\my_user\Desktop> poetry --version
Poetry version 1.1.13
```

Next I make the same test project, and try to switch the environment

```powershell
C:\Users\my_user\Desktop\test> pyenv shell 3.9.5
C:\Users\my_user\Desktop\test> poetry env use 3.9.5
Creating virtualenv test-uV6MlDwc-py3.9 in C:\Users\my_user\AppData\Local\pypoetry\Cache\virtualenvs
Using virtualenv: C:\Users\my_user\AppData\Local\pypoetry\Cache\virtualenvs\test-uV6MlDwc-py3.9
C:\Users\my_user\Desktop\test> poetry run python --version
Python 3.9.5
```

**Comment by MennoK** [comment]
Yes, it happens as well with typing `poetry env use python3.9`

Currently I'm using this: `poetry env use $(pyenv which python)`

 `$(pyenv which python)`  is the absolute path to the python executable.

**Comment by MSLeiter** [comment]
I have a similar problem getting a ParseVersionError with `poetry install`:

```shell
$ poetry install

  ParseVersionError

  Unable to parse "R2018a".

  at d:\apps\python37\lib\site-packages\poetry\core\semver\version.py:211 in parse
      207│         except TypeError:
      208│             match = None
      209│
      210│         if match is None:
    → 211│             raise ParseVersionError('Unable to parse "{}".'.format(text))
      212│
      213│         text = text.rstrip(".")
      214│
      215│         major = int(match.group(1))
```

There is no context provided, I didn't have 'R2018a' anywhere in my codebase.

However, I had just installed "python for Matlab" addon to Matlab in my venv, and taking that hint, I did a `pip list -v` from my virtual environment, and found this row:

```shell
Package                 Version            Editable project location                                Location                                                                                               Installer
----------------------- ------------------ -------------------------------------------------------- ------------------------------------------------------------------------------------------------------ ---------
matlabengineforpython   r2018a                                                                      d:\code\mca_app\app_container_inspector\.venv\lib\site-packages\matlabengineforpython-r2018a-py3.7.egg
```

R2018a is a matlab version, that doesn't match semver, because it maps to the major release of Matlab itself, which is not a semver style.

Is there any way to get Poetry to ignore this version and any related dependencies?  I do not need to install it with Poetry, but I need Poetry to coexist with it being installed separately.


I'm using Poetry version 1.1.13

**Comment by erewok** [comment]
I am not sure if this will help anyone else, but this seems to happen to me every time I `poetry install` my own project. In order to "resolve" it, I have to locate my project somewhere in PYTHONPATH and remove it:

```sh
❯ poetry update

  ParseVersionError

  Unable to parse "Unknown".

  at ~/.pyenv/versions/3.10.4/lib/python3.10/site-packages/poetry/core/semver/version.py:211 in parse
      207│         except TypeError:
      208│             match = None
      209│
      210│         if match is None:
    → 211│             raise ParseVersionError('Unable to parse "{}".'.format(text))
      212│
      213│         text = text.rstrip(".")
      214│
      215│         major = int(match.group(1))

❯ rm -rf partner_portal.egg-info  # This is the name of my project and it's in current dir, but could also be in site-packages...

❯ poetry update
Updating dependencies
Resolving dependencies... (4.9s)

Writing lock file... # Works fine now.
```

I would love to see this issue resolved, but I haven't really examined why it occurs.

Also, I have hit this on poetry versions 1.1.13, 1.1.14, and the newest beta release as well 1.2.0b2.

**Comment by MSLeiter** [comment]
Regarding my post above, it appears the problem with "R2018a" as a version may be a pip issue, rather than poetry. I've seen the error just using pip for other purposes as well.

There are also other warnings with this package when it is installs, as it is still using distutils instead of setuptools. So I manually update the version in setup.py when installing this package to get a semver style of version.

**Comment by finswimmer** [comment]
Hello @MennoK,

you haven't come back to this issue for a long while. So I assume this is solved in the meantime and I can close this ticket.

Feel free to leave a comment if you disagree.

fin swimmer
