### ISSUE TITLE
Adding a dependency removes some entries from poetry.lock

### ISSUE THREAD

**Issue by Opalo** [python-poetry/poetry#5355]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Issue
I add a new dependency with the following command:
```
poetry add isort@5.10.3 --dev
```
and it's all good, dependency gets added to `pyproject.toml` and `poetry.lock`. However some dependencies got removed from `poetry.lock` file and I've no idea whether this is expected and safe. The dependencies are:
- importlib-metadata
- typed-ast
- zipp (dependency of importlib-metadata)
The listed dependencies were not used in the project - no idea why they were present there. I've seen (this)[https://github.com/python-poetry/poetry/issues/2102] issue, however no idea if it applies here.

**Comment by abn** [comment]
As a package gets updated, it may drop dependencies or its dependencies may drop their dependencies etc. My guess is the new isort version did not need the compatibility dependency of `importlib-metadata` etc.

So TL;DR, this is expected behavior and perfectly safe.

**Comment by Opalo** [comment]
Thanks @abn. However there was no `isort` version present in `pyproject.toml` previously. That is what worries me.

**Comment by abn** [comment]
My guess is a nested dependency that was already locked got updated since the solved version now was higher or lower than previously locked. So, it is still reasonably to assume it is doing the right thing here.
