### ISSUE TITLE
Poetry 1.2 `export` command should acknowledge dependency groups

### ISSUE THREAD

**Issue by collang** [python-poetry/poetry#5367]
- [ x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

With the new concept of dependency groups being added in the 1.2 release I think it's probably important that all the commands use the concept in a similar, predictable way. Presently, the `export` command only has a `--dev` flag to install all optional dependencies even though similar commands have been deprecated elsewhere. I believe this has probably just been overlooked so I wanted to make sure this was on the radar of those working on this project.

Thanks to everyone who contributes to this project, this is shaping up to be a great release 👍

**Comment by finswimmer** [comment]
Hello @collang,

the implementation of the `export` command will move to a plugin. See https://github.com/python-poetry/poetry/pull/4824. This plugin will acknowledge the dependency groups. See https://github.com/python-poetry/poetry-export-plugin

fin swimmer

**Comment by jaymegordo** [comment]
@finswimmer that PR you mentioned seems to be closed? Is there any way to work around this currently to use `poetry export --with my_group`?
