### ISSUE TITLE
(🐞) `poetry show --outdated` should only list direct('top level') dependencies, not transitive dependencies

### ISSUE THREAD

**Issue by KotlinIsland** [python-poetry/poetry#5373]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**:  N/A
- **Poetry version**:  N/A
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue

From #2684

I want a simple way to discover outdated dependencies, I can't see any  real value in listing transitive dependencies.

I made this a bug because it's not really a feature request, more like a usability issue.

**Comment by dimbleby** [comment]
duplicate #4342

**Comment by Secrus** [comment]
Closing as duplicate.
