### ISSUE TITLE
poetry.exe breaks after self upgrade on Windows

### ISSUE THREAD

**Issue by MathijsdeBoer** [python-poetry/poetry#5377]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version (sort of).
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **Windows 10**: 
- **1.1.13 upgraded to 1.12.0b1**: 

## Issue
When upgrading poetry using `poetry self update --preview`, poetry is no longer operable.

Log from a fresh poetry 1.1.13 install:
```
> (Invoke-WebRequest -Uri https://install.python-poetry.org -UseBasicParsing).Content | python - --uninstall
Poetry is not currently installed.
> poetry
Fatal error in launcher: Unable to create process using '"...\AppData\Roaming\pypoetry\venv\Scripts\python.ex
> (Invoke-WebRequest -Uri https://install.python-poetry.org -UseBasicParsing).Content | python -
Retrieving Poetry metadata

# Welcome to Poetry!

This will download and install the latest version of Poetry,
a dependency and package manager for Python.

It will add the `poetry` command to Poetry's bin directory, located at:

...\AppData\Roaming\Python\Scripts

You can uninstall at any time by executing this script with the --uninstall option,
and these changes will be reverted.

Installing Poetry (1.1.13)
Installing Poetry (1.1.13): Creating environment
Installing Poetry (1.1.13): Installing Poetry
Installing Poetry (1.1.13): Creating script
Installing Poetry (1.1.13): Done

Poetry (1.1.13) is installed now. Great!


`poetry --version`

> poetry --version
Poetry version 1.1.13
> poetry self --help
USAGE
      poetry self
  or: poetry self update [--preview] [<version>]

COMMANDS
  update
    Updates Poetry to the latest version.

    <version>            The version to update to.
    --preview            Install prereleases.

GLOBAL OPTIONS
  -h (--help)            Display this help message
  -q (--quiet)           Do not output any message
  -v (--verbose)         Increase the verbosity of messages: "-v" for normal output, "-vv" for more verbose output and
                         "-vvv" for debug
  -V (--version)         Display this application version
  -n (--no-interaction)  Do not ask any interactive question

> poetry self update --preview
Updating Poetry to 1.2.0b1
Updating dependencies                                                                                                   
Resolving dependencies...
Package operations: 1 install, 3 updates, 0 removals

  - Updating cleo (0.8.1 -> 1.0.0a4)                                                                                      
  - Installing entrypoints (0.3)                                                                                          
  - Updating poetry-core (1.0.8 -> 1.1.0a7)                                                                               
  - Updating poetry (1.1.13 -> 1.2.0b1)                                                                                 
Updating the poetry script

Poetry (1.2.0b1) is installed now. Great!
> poetry --version
Traceback (most recent call last):
  File "...\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "...\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "...\AppData\Roaming\Python\Scripts\poetry.exe\__main__.py", line 4, in <module>
ImportError: cannot import name 'main' from 'poetry.console' (...\AppData\Roaming\pypoetry\venv\lib\site-packages\poetry\console\__init__.py)
> (Invoke-WebRequest -Uri https://install.python-poetry.org -UseBasicParsing).Content | python - --uninstall
Removing Poetry (1.1.13)
```

I needed to update to `1.2.0b1` due to the bug where I could not install CUDA versions of TorchVision and PyTorch together, but this unfortunately seems to have completely bricked my poetry install, requiring a manual deletion of remaining files.

A fully fresh install with `(Invoke-WebRequest -Uri https://install.python-poetry.org -UseBasicParsing).Content | python - --version 1.2.0b1` does seem to work, however.

```
> (Invoke-WebRequest -Uri https://install.python-poetry.org -UseBasicParsing).Content | python - --version 1.2.0b1
Retrieving Poetry metadata

# Welcome to Poetry!

This will download and install the latest version of Poetry,
a dependency and package manager for Python.

It will add the `poetry` command to Poetry's bin directory, located at:

...\AppData\Roaming\Python\Scripts

You can uninstall at any time by executing this script with the --uninstall option,
and these changes will be reverted.

Installing Poetry (1.2.0b1)
Installing Poetry (1.2.0b1): Creating environment
Installing Poetry (1.2.0b1): Installing Poetry
Installing Poetry (1.2.0b1): Creating script
Installing Poetry (1.2.0b1): Done

Poetry (1.2.0b1) is installed now. Great!

You can test that everything is set up by executing:

`poetry --version`

> poetry --version
Poetry (version 1.2.0b1)
```

**Comment by Gakai** [comment]
Also happens on Windows 11 with Python 3.10.4

**Comment by Euraxluo** [comment]
https://stackoverflow.com/questions/49836676/error-after-upgrading-pip-cannot-import-name-main

**Comment by Euraxluo** [comment]
u can try：
1. uninstall pip :`python -m pip uninstall pip`
2. uninstall poetry  :`(Invoke-WebRequest -Uri https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py -UseBasicParsing).Content | python - --uninstall`
3. install pip ： `(Invoke-WebRequest -Uri https://bootstrap.pypa.io/get-pip.py -UseBasicParsing).Content | python -`
4. install poetry -p with new script ： `(Invoke-WebRequest -Uri https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py -UseBasicParsing).Content | python - -p`

**Comment by Czorio** [comment]
I don't think this is a pip issue, it's not in the stacktrace.

**Comment by Euraxluo** [comment]
yes,see source:
![image](https://user-images.githubusercontent.com/34028978/161237202-a329de29-9725-4fab-a3d1-741891dc2d48.png)

poetry-p:
```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import sys
if __name__ == "__main__":
    from poetry.console.application import main

    sys.exit(main())


```
poetry-p.bat:
```
@echo off

python "%USERPROFILE%\.poetry\bin\poetry-p" %*


```
powershell:
```
PS C:\Users\Administrator> poetry-p --version
Poetry (version 1.2.0a2)
```

**Comment by Euraxluo** [comment]
That's all it takes to install poetry's the poetry.__main__.py
![image](https://user-images.githubusercontent.com/34028978/161237904-6cd4f2a9-2a04-40f1-a971-f72704cd6b5a.png)
Believe that the official is making

**Comment by spex66** [comment]
I'm on Windows 11 running Python 3.8 installed from python.org with `py.exe` support 

1. initially installed poetry with
```powershell
  # use `| py -` instead of `| python -`!
  (Invoke-WebRequest -Uri https://install.python-poetry.org -UseBasicParsing).Content | py -

  # add to path (use double-quotes for $env variable expansion)
  $env:Path += ";$env:APPDATA\Python\Scripts"

  # check
  poetry --version

  Poetry version 1.1.13
```

2. updated to preview which failed (after successful update) as described in OP
```powershell
poetry self update --preview
Updating Poetry to 1.2.0a2

Poetry (1.2.0b1) is installed now. Great!
```

3. recognized that my `poetry.exe` from path `$env:APPDATA\Python\Scripts` has no updated timestamp
4. copied over the one I found in `$env:APPDATA\pypoetry\poetry.exe` 
   - not fiddled with the sources in `$env:APPDATA\pypoetry\venv\Lib\site-packages\poetry`
6. new EXE works like expected
```powershell
poetry --version
Poetry (version 1.2.0b1)
```

As it is hard on Windows to compare who installed which Python (Microsoft Store vs python.org) your mileage (folder locations) may vary.
- pls check how this relies to your environment
- maybe a copy of the new `exe` to the `Script` folder is all what is missing on Windows?

**Comment by xyxz-web** [comment]
I can confirm the process for manually fixing this works as mentioned by spex66

**Comment by davidgilbertson** [comment]
This is an issue in the `1.2.0` version also. Just ran `poetry self update` and now get this error:
```
File "C:\Users\david\AppData\Roaming\Python\Scripts\poetry.exe\__main__.py", line 4, in <module>
ImportError: cannot import name 'main' from 'poetry.console' (C:\Users\david\AppData\Roaming\pypoetry\venv\lib\site-packages\poetry\console\__init__.py)
```

**Comment by neersighted** [comment]
@davidgilbertson details on your environment will be needed to determine if this is something new, or the lingering MS Store funk -- what version of Windows are you on, with what version of Python, installed using what method, from what vendor (Python.org, MS Store, other?).

Also, what method did you use to install Poetry? Thanks!

**Comment by xyxz-web** [comment]
I've also had this problem.
Environment was miniconda 3.7.13, so not a MS Store install.
Upgrade from one of the prereleases to the final release worked without problems though.

**Comment by davidgilbertson** [comment]
@neersighted I installed Poetry with:
```ps
(Invoke-WebRequest -Uri https://install.python-poetry.org -UseBasicParsing).Content | py -
```
This was just last week I think so would have been 1.1.15.

One funky thing I did when learning my way around Poetry was I accidentally did `--preview` (thinking it was like `--dry-run` from `npm`) at some point which installed the preview version of Poetry, so I uninstalled and started again. Perhaps that put me in a weird state?

I do have the Microsoft store Python on my system (which I don't use) as well as python.org Windows installs of Python 3.8 and 3.10. If I run `py` in the terminal, then `sys.executable`, I get `C:\\Program Files\\Python310\\python.exe`

I'm on Windows 11.

The trick from @spex66 worked for me.

**Comment by neersighted** [comment]
Given the tip from spex I wonder if we're writing `poetry.exe` to the wrong spot during `self upgrade` on Windows -- I cannot get this to reproduce myself, though I am yet to try a Windows container.

I also wonder if this might be some Windows file locking issues popping up again -- self-upgrading Windows software is always a bit of a song and dance.

**Comment by kenchoong** [comment]
I also having this issue. 
Fix it by 
- go to `%APPDATA/programs/python/scripts` which already add to environment PATH 
- then inside it have `poetry.exe`, this executable is not updated one, 
- so delete this.
- Then go  `%APPDATA%\pypoetry\venv\Scripts`, copy the `poetry.exe` 
- Then paste it back to `%APPDATA/programs/python/scripts`

Now you can `poetry --version` again

**Comment by demberto** [comment]
> * go to `%APPDATA/programs/python/scripts` which already add to environment PATH
> * then inside it have `poetry.exe`, this executable is not updated one,
> * so delete this.
> * Then go  `%APPDATA%\pypoetry\venv\Scripts`, copy the `poetry.exe`
> * Then paste it back to `%APPDATA/programs/python/scripts`
> 
> Now you can `poetry --version` again

Didn't work for me, I get this error

```py
Traceback (most recent call last):
  File "AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "AppData\Roaming\Python\Scripts\poetry.exe\__main__.py", line 4, in <module>
ModuleNotFoundError: No module named 'poetry.console'
```

**Comment by aprath1** [comment]
If someone else have trouble in locating old poetry.exe, it might not be at `%APPDATA/programs/python/scripts`.
For me the old version of poetry.exe was at `%APPDATA%\Python\Scripts`
=> Copying and pasting the updated poetry.exe from `%APPDATA%\pypoetry\venv\Scripts` to `%APPDATA%\Python\Scripts` worked

**Comment by sir-kokabi** [comment]
This is how I fixed the problem:

1. `(Invoke-WebRequest -Uri https://install.python-poetry.org -UseBasicParsing).Content | python - --uninstall`
2. **Remove the `pypoetry` folder from `%APPDATA%/pypoetry`**
3. `(Invoke-WebRequest -Uri https://install.python-poetry.org -UseBasicParsing).Content | python -`
4. `poetry shell`

**Comment by finswimmer** [comment]
We recommend now to use `pipx` to install Poetry. (https://python-poetry.org/docs/#installing-with-pipx) This should avoid problems described in the issue.
