### ISSUE TITLE
missing 1 required positional argument: 'self'

### ISSUE THREAD

**Issue by Pankaj2201** [python-poetry/poetry#5389]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: 
- **Poetry version**: 
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue

``
I am using poetry with click library. I wrote the code in a OOP manner. While I am running code from CLI, I am getting an error as shown below. 
`Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: main() missing 1 required positional argument: 'self'
`
FYI: I have added the module.pakage:class.function in pyproject.toml as shown below.
`[tool.poetry.scripts]
findata = "investment.ParseFinData:CalculateEtfsYahoo.main"`

I do not know how to get rid of this error.

**Comment by finswimmer** [comment]
Hello @Pankaj2201,

this doesn't look like a problem by Poetry. It seems to be more a problem with your code. Please asked on other platforms like stackoverflow first, by showing your code and explaining what you are trying to achieve.

fin swimmer
