### ISSUE TITLE
Poetry gets confused by portable python install

### ISSUE THREAD

**Issue by damienrj** [python-poetry/poetry#5397]
- [ X ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [ X ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ X ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- OSX 12.2.1 
- Poetry version 1.1.13

## Issue
I am using a portable install of python via Hermit (https://cashapp.github.io/hermit/) and that in general has been working great. But when using poetry there is a problem that even though the package version is the same it keeps trying to update the package. This is at best slow, but for some cases it then tried to build the package instead of using a wheel and fails. 

```
  • Updating rsa (4.7.2 /Users/damien/Development/myrepo/.hermit/python/lib/python3.8/site-packages -> 4.7.2)
  • Updating tornado (6.1 /Users/damien/Development/myrepo/.hermit/python/lib/python3.8/site-packages -> 6.1)
  • Updating urllib3 (1.26.7 /Users/damien/Development/myrepo/.hermit/python/lib/python3.8/site-packages -> 1.26.7)
  • Updating pyzmq (22.3.0 /Users/damien/Development/myrepo/.hermit/python/lib/python3.8/site-packages -> 22.3.0): Failed
```

**Comment by damienrj** [comment]
Looks like a fix is on master

**Comment by stefaneidelloth** [comment]
How did you manage that poetry uses a relative path for its settings? Also see
https://github.com/python-poetry/poetry/issues/6875
