### ISSUE TITLE
Poetry couldn't resolve/upadte/install anything 

### ISSUE THREAD

**Issue by dganev-cb** [python-poetry/poetry#5398]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: WSL2 Ubuntu 20.04
- **Poetry version**: Poetry version 1.1.13
- [Gist](https://gist.github.com/dganev-cb/f81e906c7372414f932ece7d9849a71b)

## Issue
I cannot install/update/resolve anything using poetry, I've reinstalled it a couple of times with `get-poetry` and with `pip` as well. It is always stuck at some dependency: 

## Examples: 
This is a log of an example of how it gets stuck using `-vvv`: https://gist.github.com/dganev-cb/3481dccf24f103b8f8f29412dbbf213d 
The update also doesn't work it gets stuck here: https://gist.github.com/dganev-cb/7c34534fdec506d2199c1386f554f1a3 

The package doesn't matter here, it is mostly random. Also, another thing that I've noticed is that I have to run `poetry update` a couple of times and when it gets stuck I would just cancel it and run it again until it updates everything it's really annoying. 

I don't get why no errors are ever thrown, my `pyproject.toml` file is quite simple. This irritates me so much that I would just remove poetry from my project.

**Comment by dganev-cb** [comment]
Just tried it on Ubuntu 20.04 and I didn't have any errors/stucks its probably something in WSL.

**Comment by abn** [comment]
Is this still an issue? Have you tried poetry@master?

**Comment by dganev-cb** [comment]
Yes, unfortunately, I cannot replicate it because it happens randomly. I would assume that there is something wrong with the WSL itself rather than something in poetry though.
