### ISSUE TITLE
Is adding parameter/option for package installation possible with Poetry?

### ISSUE THREAD

**Issue by j-adamczyk** [python-poetry/poetry#5400]
## Issue

Does Poetry support adding parameters/options for package installation? I need to install CPU-only PyTorch, and I used to do:
```
pip install torch --extra-index-url https://download.pytorch.org/whl/cpu
```

Is there any way to pass parameters/options like `--extra-index-url` to Poetry through `pyproject.toml`?

I know I can use the wheel URL:
```
torch = { url = "https://download.pytorch.org/whl/cpu/torch-1.11.0%2Bcpu-cp38-cp38-linux_x86_64.whl"}
```

But does Poetry resolve dependencies in this case? I.e. does it know that this is in fact PyTorch and has its regular requirements? Additionally this looks pretty bad.

- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

**Comment by anthonymichaelclark** [comment]
@j-adamczyk Yes, poetry supports installing from secondary sources -- see [docs](https://download.pytorch.org/whl/cpu) on configuring and adding additional sources.

Installing from url as in your example should install dependencies as wheels are packaged with a list of dependencies.

**Comment by j-adamczyk** [comment]
@anthonymichaelclark

1. I see that in the docs [docs](https://python-poetry.org/docs/repositories/) now. But is it possible to have an extra repository for just one dependency? Or do I have to make PyTorch wheels repository primary for all packages? If so, won't it slow down the installation process for every package?
2. In case of installing from URL, is it then roughly equivalent to setting `torch = "1.11.0"` and installing the exact dependencies of that wheel version? And this is then taken into consideration during dependency resolution?

**Comment by abn** [comment]
1. You can configure it as a secondary source. However, it will still be queried when Poetry searches for packages. See updated docs for more information https://python-poetry.org/docs/master/repositories/#package-sources (applies to 1.2)
2. Yes, poetry will use the metadata from the package found at the URL. The difference is that only that url will be used for everyone. This can be an issue when let's say the package depends on an x86_64 wheel and a user of your package tries to install it on an arm machine.

**Comment by fgervais** [comment]
> You can configure it as a secondary source. However, it will still be queried when Poetry searches for packages.

I think this might get flagged as a bruteforce attempt at some point.

![image](https://user-images.githubusercontent.com/5411996/212766989-63759936-8521-4399-b896-54508dbdf9da.png)
