### ISSUE TITLE
Frequent OSErrors on `nfs` filesystems

### ISSUE THREAD

**Issue by aalok-sathe** [python-poetry/poetry#5404]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: RHEL CentOS 7

## Issue
I very frequently get `OSError` while doing any `install` or `update` operation using `poetry` on a networked filesystem (NFS) computer (an institute server). This is specific to poetry, as `pip` installs and `conda` work fine in isolation. I suspect it may be due to the concurrent operations of poetry, which somehow interferes with the NFS workings. 

As an effect, I have to monitor `poetry` commands and retry them until they work, which can be several times. Usually they end up working after several retries, but it would be nice if I didn't have to retry several times.

Maybe it would help to turn off concurrency with a flag `--no-parallel` to prevent such errors on NFS systems (although I'm not sure the concurrency is what's causing the issue). 

Example below:

```python
  Collecting pillow==9.1.0
    Downloading Pillow-9.1.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.3 MB)
  Installing collected packages: pillow
    Attempting uninstall: pillow
      Found existing installation: Pillow 9.0.1
      Uninstalling Pillow-9.0.1:
        Successfully uninstalled Pillow-9.0.1
  ERROR: Could not install packages due to an OSError: [Errno 16] Device or resource busy: '.nfs23fa2dcde2b24c6300005655'
```

**Comment by finswimmer** [comment]
Hello @aalok-sathe,

if you suspect the parallel install as the source for the error you can disable it by setting the `experimental.new-installer` config to `false`.

fin swimmer

**Comment by abn** [comment]
The above workaround is replaced by `poetry config installer.max-workers 1`.

**Comment by abn** [comment]
The workaround might be the fix for the issue here, and the logs sprovided seems to be from pip not Poetry. Closing as original request is already possible.
