### ISSUE TITLE
poetry export produces unresolvable requirements.txt

### ISSUE THREAD

**Issue by Mchristos** [python-poetry/poetry#5407]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**:  Ubuntu 20.04 (WSL)
- **Poetry version**: 1.1.13
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 
  [pyproject.toml](https://gist.github.com/Mchristos/83b524d022be9bc561b75e68d39d7305)
  [poetry.lock](https://gist.github.com/Mchristos/62eea04e582790616f634ed3e48f5fb6)

## Issue
Doing `poetry export -f requirements.txt` and installing dependencies in a fresh virtual environment from the resulting requirements, creates a situation where pip is unable to resolve the dependencies, due to conflicting version requirements among packages. 

Specifically, I am doing the following (inside a docker build, I should add)

```
python -m venv /venv
poetry export -f requirements.txt | /venv/bin/pip install -r /dev/stdin
```
This yields the following ResolutionImpossible error from pip: 

```
#9 335.2 ERROR: Cannot install -r /dev/stdin (line 62), -r /dev/stdin (line 843) and torch==1.10.2 because these package versions have conflicting dependencies.
#9 335.2 
#9 335.2 The conflict is caused by:
#9 335.2     The user requested torch==1.10.2
#9 335.2     fastai 2.5.3 depends on torch<1.11 and >=1.7.0
#9 335.2     torchvision 0.12.0 depends on torch==1.11.0
#9 335.2 
#9 335.2 To fix this you could try to:
#9 335.2 1. loosen the range of package versions you've specified
#9 335.2 2. remove package versions to allow pip attempt to solve the dependency conflict
#9 335.2 
#9 335.2 ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
------
```

**Comment by finswimmer** [comment]
Hello @Mchristos,

please add your `pyproject.toml` and `poetry.lock`. Without them no one can try to reproduce your issue.

Thanks!

fin swimmer

**Comment by Mchristos** [comment]
Apologies, thought I had linked the pyproject gist. Both pyproject and lockfile are linked now: 

https://gist.github.com/Mchristos/83b524d022be9bc561b75e68d39d7305

https://gist.github.com/Mchristos/62eea04e582790616f634ed3e48f5fb6

**Comment by dimbleby** [comment]
Your lockfile says:
```
[[package]]
name = "torchvision"
version = "0.12.0"
description = "image and video datasets and models for torch deep learning"
category = "main"
optional = false
python-versions = ">=3.7"

[package.dependencies]
numpy = "*"
pillow = ">=5.3.0,<8.3.0 || >=8.4.0"
requests = "*"
torch = "*"
typing-extensions = "*"
```
which is to say that poetry does not think that torchvision 0.12.0 depends on any particular version of torch, contrary to what pip says.

https://pypi.org/pypi/torchvision/0.12.0/json agrees with poetry, whereas the METADATA in the torchvision .whl agrees with pip.

Suggest raise an MR against torchvision asking them to publish consistent information to pypi.

**Comment by Mchristos** [comment]
Great, thanks for looking into and giving feedback. Appreciate it!
