### ISSUE TITLE
Sort hashes when exporting "requirements.txt"

### ISSUE THREAD

**Issue by mitchhentges** [python-poetry/poetry#5408]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

When `pip-compile` generates a `requirements.txt`, the `--hash` lines are sorted.
I'm [porting my project to use `poetry` instead](https://bugzilla.mozilla.org/show_bug.cgi?id=1659593) (your handling of environment markers is phenomenal!), but it's causing my diff to be larger than necessary due to the hash line reorderings.

**Comment by abn** [comment]
The should be in the export plugin code.

https://github.com/python-poetry/poetry-plugin-export/blob/f54094bef720410a546a83f19cb0e80878cb2c8a/src/poetry_plugin_export/exporter.py#L159-L160

This is a good first issue for contributors. This requires a single line change and a test case. Happy to review .

**Comment by cgkoutzigiannis** [comment]
Hi @abn! I just created a [pr](https://github.com/python-poetry/poetry-plugin-export/pull/54) for this.
