### ISSUE TITLE
`poetry add` says wrong Python Version

### ISSUE THREAD

**Issue by thinkrapido** [python-poetry/poetry#5416]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: 
```
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="22.05pre360796.73ad5f9e147"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID="nixos"
LOGO="nix-snowflake"
NAME="NixOS"
PRETTY_NAME="NixOS 22.05 (Quokka)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="22.05 (Quokka)"
VERSION_CODENAME="quokka"
VERSION_ID="22.05"
```
- **Poetry version**: Poetry version 1.1.12

- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: [pypoetry.toml + shell.nix + dir tree](https://gist.github.com/thinkrapido/769eed2e199160f1ede919d4dbccfa1c)
## Issue

```
[nix-shell:~/Sync/Work/indi/analytics/pex-test]$ poetry add -D pex
Using version ^2.1.76 for pex

Updating dependencies
Resolving dependencies... (0.0s)

  SolverProblemError

  The current project's Python requirement (>=3.9,<4.0) is not compatible with some of the required packages Python requirement:
    - pex requires Python >=2.7,<3.11,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*, so it will not be satisfied for Python >=3.11,<4.0
  
  Because no versions of pex match >2.1.76,<3.0.0
   and pex (2.1.76) requires Python >=2.7,<3.11,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*, pex is forbidden.
  So, because pex-test depends on pex (^2.1.76), version solving failed.

  at /nix/store/y3dkgclc7vvzpqhd63rgrmdb581mwcl8-python3.9-poetry-1.1.12/lib/python3.9/site-packages/poetry/puzzle/solver.py:241 in _solve
      237│             packages = result.packages
      238│         except OverrideNeeded as e:
      239│             return self.solve_in_compatibility_mode(e.overrides, use_latest=use_latest)
      240│         except SolveFailure as e:
    → 241│             raise SolverProblemError(e)
      242│ 
      243│         results = dict(
      244│             depth_first_search(
      245│                 PackageNode(self._package, packages), aggregate_package_nodes

  • Check your dependencies Python requirement: The Python requirement can be specified via the `python` or `markers` properties
    
    For pex, a possible solution would be to set the `python` property to ">=3.9,<3.11"

    https://python-poetry.org/docs/dependency-specification/#python-restricted-dependencies,
    https://python-poetry.org/docs/dependency-specification/#using-environment-markers
```

What's the matter?

I deleted all virtual envs and also the cache, but this error still persists.
I also nix-shell --delete `poetry dependency`

Why does it bother the python version?

**Comment by clintonroy** [comment]
Poetry is not looking at your local version of python, it's looking at what is configured as your project's acceptable python versions in pyproject.toml. The point is that if you distribute your project, it's dependency information will be valid. Poetry is even telling you how to move forward:

    For pex, a possible solution would be to set the `python` property to ">=3.9,<3.11"

**Comment by finswimmer** [comment]
Hello @thinkrapido,

@clintonroy already explains what's going on. This is also a [FAQ](https://python-poetry.org/docs/master/faq/#why-is-poetry-telling-me-that-the-current-projects-python-requirement-is-not-compatible-with-one-or-more-packages-python-requirements).

fin swimmer
