### ISSUE TITLE
Plugin show shows nothing after installing. pyproject not changed.

### ISSUE THREAD

**Issue by banuni** [python-poetry/poetry#5419]
- [ ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version. **(No, on --preview)**
- [ x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

- **OS version and name**: MacOS 12.3
- **Poetry version**: 1.2.0b1

## Issue
Trying the `plugin` feature... I don't know where it installs it, but it does. however, I can't seem to use the plugin in the project:

**Short version:**
```bash
~/projects/my_prject ❯ poetry plugin add example                                                    13:03:09
Using version ^0.1.0 for example
Updating dependencies
Resolving dependencies... (0.2s)

Writing lock file

Package operations: 1 install, 0 updates, 0 removals

  • Installing example (0.1.0)
~/projects/my_prject ❯ poetry plugin show                                                           13:03:43
~/projects/my_prject ❯ poetry plugin add example                                                    13:03:48
The following plugins are already present in the pyproject.toml file and will be skipped:

  • example

If you want to update it to the latest compatible version, you can use `poetry plugin update package`.
If you prefer to upgrade it to the latest available version, you can use `poetry plugin add package@latest`.
~/projects/my_prject ❯
```
**Full version:**
```bash
~/projects/my_prject ❯ cat pyproject.toml                                                           13:03:05
[tool.poetry]
name = "my-prject"
version = "0.1.0"
description = ""
authors = ["Banuni"]
readme = "README.md"
packages = [{include = "my_prject"}]

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
~/projects/my_prject ❯ poetry plugin add example                                                    13:03:09
Using version ^0.1.0 for example
Updating dependencies
Resolving dependencies... (0.2s)

Writing lock file

Package operations: 1 install, 0 updates, 0 removals

  • Installing example (0.1.0)
~/projects/my_prject ❯ cat pyproject.toml                                                       10s 13:03:22
[tool.poetry]
name = "my-prject"
version = "0.1.0"
description = ""
authors = ["Banuni"]
readme = "README.md"
packages = [{include = "my_prject"}]

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

~/projects/my_prject ❯ poetry plugin show                                                           13:03:43
~/projects/my_prject ❯ poetry plugin add example                                                    13:03:48
The following plugins are already present in the pyproject.toml file and will be skipped:

  • example

If you want to update it to the latest compatible version, you can use `poetry plugin update package`.
If you prefer to upgrade it to the latest available version, you can use `poetry plugin add package@latest`.

~/projects/my_prject ❯
```

**Comment by abn** [comment]
This is because https://pypi.org/project/example/ is not a poetry plugin. 

Additionally, the project's toml file is not modified by this command. The plugin added to the system environment (environment that poetry is installed under).

If you are installing a path dependency, use `./example`.

**Comment by banuni** [comment]
this is also the case with `export` and the original plugin I wanted to install: `keyrings.google-artifactregistry-auth`

**Comment by abn** [comment]
Unsure what you mean here. How did you install the export plugin? For poetry 1.2.0b1 you'll have to use the following. 

```sh
poetry plugin add poetry-export-plugin
```

For the version on master and later, you'll need to use the latest release renamed to `poetry-plugin-export`.


As for `keyrings.google-artifactregistry-auth`, it is not a poetry plugin. It won't get listed. 

I suspect it still works the way you expect it to since `poetry plugin add` simply adds the package. However, no entrypoint group that poetry looks for will not be found when `poetry plugin show` searches.

**Comment by banuni** [comment]
@abn , you were absolutely right, sorry for this confusion, perhaps it could be beneficial to add a Warning of some sort if an installed plugin has no entry point.

thanks for your help!
