### ISSUE TITLE
Error when running `poetry new` in parent directory of "git.exe".

### ISSUE THREAD

**Issue by michiharu2017** [python-poetry/poetry#5420]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows 10 Pro
- **Poetry version**: 1.1.13
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: None (This is `poetry new` issue.)

## Issue

When I run `poetry new` in the parent directory of the directory where Git is installed, I get the following error:
```
C:\Users\personal>poetry new poetry_demo

  RuntimeError

  Unable to find a valid git executable

  at AppData\Roaming\pypoetry\venv\lib\site-packages\poetry\core\vcs\git.py:189 in executable
      185│     else:
      186│         _executable = "git"
      187│
      188│     if _executable is None:
    → 189│         raise RuntimeError("Unable to find a valid git executable")
      190│
      191│     return _executable
      192│
      193│
```

The path to Git is as follows: 
```
C:\Users\personal>where git
C:\Users\personal\AppData\Local\Programs\Git\cmd\git.exe
```

If it is not the parent directory of Git, no error will occur.
```
C:\Users\personal>mkdir tmp_dir
C:\Users\personal>cd tmp_dir
C:\Users\personal\tmp_dir>poetry new poetry-demo
Created package poetry_demo in poetry-demo
```

The code that causes is as follows
If `ValueError` is not raised (i.e., if the git path can be converted to a path relative to the current directory), the next process raises `RuntimeError`.

`poetry/core/vcs/git.py`
```python:poetry/core/vcs/git.py
    if WINDOWS and PY36:
        # Finding git via where.exe
        where = "%WINDIR%\\System32\\where.exe"
        paths = decode(
            subprocess.check_output([where, "git"], shell=True, encoding="oem")
        ).split("\n")
        for path in paths:
            if not path:
                continue

            path = Path(path.strip())
            try:
                path.relative_to(Path.cwd())
            except ValueError:
                _executable = str(path)

                break
    else:
        _executable = "git"

    if _executable is None:
        raise RuntimeError("Unable to find a valid git executable")
```

I don't know the details of this function, but I think the error message should say that 'the poetry project cannot be created in the parent directory of "git.exe"'.

This is my first Issue, so I apologize if anything is incomplete. 
I hope this helps.

**Comment by Rafeqm** [comment]
Yea I get this error as well.

**Comment by clintonroy** [comment]
There's work being done to git stuff with a library, without relying on an external git command: https://github.com/python-poetry/poetry/pull/5428

So I would just work around this.

**Comment by finswimmer** [comment]
Closing this, because Poetry now uses dulwich for git interaction by default.

**Comment by LexSong** [comment]
I'm having the exact same issue with poetry 1.4.0 on Windows. The calling stack is the same as above. And I think dulwich didn't help solve this issue.
