### ISSUE TITLE
`brew install poetry` depends on `python@3.10` and not using pyenv python (macOS)

### ISSUE THREAD

**Issue by xareelee** [python-poetry/poetry#5423]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS 12.3.1
- **Poetry version**: 1.1.13
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/xareelee/eafcac5d14c37b19b3e727bc307ba193

## Issue

I installed both pyenv and poetry by homebrew on macOS.

```shell
$ brew install pyenv
$ pyenv --version
pyenv 2.2.5

$ brew install poetry
$ poetry --version
Poetry version 1.1.13
```

I installed python 3.10.3 by pyenv

```shell
$ pyenv install 3.10.3
$ pyenv global 3.10.3
$ pyenv versions
  system
* 3.10.3 (set by ~/.pyenv/version)

# check python version and path
$ python --version
Python 3.10.3
$ ls -lh `which python`
-rwxr-xr-x  1 xaree  staff   182B Mar 23 06:44 /Users/xaree/.pyenv/shims/python
```

Now I create a python project using poetry

```shell
$ mkdir hello
$ cd hello
$ poetry init -n

# enter venv
$ poetry shell

# Check python version. It's not 3.10.3
$ python --version
Python 3.10.2
$ ls -lh `which python`
lrwxr-xr-x  1 xaree  staff    44B Apr  7 12:59 /Users/xaree/dev/playground/hello/.venv/bin/python -> /opt/homebrew/opt/python@3.10/bin/python3.10
```

The poetry uses brew's python, not pyenv's python. I did not install brew's python manually, but [brew's poetry did](https://raw.githubusercontent.com/Homebrew/homebrew-core/33863a345964ca2f4155bc7fa899297f286f1cc9/Formula/poetry.rb).

Questions:

- Is the dependency `python@3.10` necessary in `poetry.rb` for brew installation?
- How could I initiate a poetry project with specific pyenv's python?

This issue may associate with https://github.com/python-poetry/poetry/issues/4646.

**Comment by xareelee** [comment]
BTW, this issue could be resolved by reinstalling poetry with the official way:

```shell
# Uninstall poetry from brew
$ brew uninstall poetry

# Install poetry by official method
$ curl -sSL https://install.python-poetry.org | python3 -
```

I leave the issue opened for installing with brew.

**Comment by Rafeqm** [comment]
_Opened issue means unresolved issue_.

Google can track closed issue as well so there is no need to leave this issue opened.

**Comment by trallnag** [comment]
I wonder why Homebrew is not installing Poetry in a self-contained manner.

**Comment by Secrus** [comment]
Homebrew installation is not an official one and is not maintained by the Poetry team. The only official ways are the ones that are mentioned in Poetry documentation.
