### ISSUE TITLE
Any way to run `arch -arm64 pip3 install` + options through poetry?

### ISSUE THREAD

**Issue by rarenatoe** [python-poetry/poetry#5436]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

I need to install psycopg2 through poetry, on my M1 mac, however installing it through `poetry add psycopg2` or `poetry add psycopg2-binary` gives errors.

I have found that doing `arch -arm64 pip3 install psycopg2 --no-binary :all:` fixes the issue, however I have no idea how to add this to the `pyproject.toml` file, nor how to have it updated in `poetry.lock`.

If I missed any important section of the documentation, I'd appreciate any pointers.

**Comment by abn** [comment]
Try aliasing `poetry` to `arch -arm64 poetry` (unsure how this might go as your poetry install uses an interpreter compiled for M1) ? 

Alternatively, as a work around you can manually add the dependency (this won't update the lock file). 

```sh
poetry run arch -arm64 pip install psycopg-binary
```

**Comment by rarenatoe** [comment]
Not an issue anymore since psycopg2 has now been fix for M1.
