### ISSUE TITLE
Support Installation via requirements.txt

### ISSUE THREAD

**Issue by AtakanTekparmak** [python-poetry/poetry#5437]
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

For **poetry** to be the [yarn](https://yarnpkg.com/) of the Python ecosystem, it needs to support installation via **requirements.txt** files as does **yarn** for **package.json**. The one-way relationship between poetry and requirements.txt is preventing many legacy codebases from switching to poetry.

**Comment by clintonroy** [comment]
Poetry is fundamentally designed around using pyproject.toml, and I don't see that ever changing.

**Comment by AtakanTekparmak** [comment]
So it will stay a very opinionated tool that has fundamental barriers for new users?

**Comment by Secrus** [comment]
That could be solved in 1.2 via a plugin. Poetry team is working on moving `export` feature to a plugin, so I don't think that this issue will be addressed in the main `poetry` code. 

Also, I don't think that `poetry` is to be "yarn of the Python ecosystem" so comparing those, makes no sense.

**Comment by finswimmer** [comment]
Hello @AtakanTekparmak,

as other already mentioned, Poetry is and will be opinionated here and will only support one source for the dependency definitions by default. A plugin by a community member to support the desired feature could be possible.

fin swimmer
