### ISSUE TITLE
Poetry does not tag OS-specific dependencies properly

### ISSUE THREAD

**Issue by cro** [python-poetry/poetry#5439]
- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- OS: Linux, Rocky Linux 8.5, Debian Buster official Python 3.9 container
- Poetry Version: 1.13 (also tried 1.2.0b1)
- Gist: https://gist.github.com/cro/62d32d67a78eca29fb26872000ea3502

## Issue

Salt on macOS needs a number of libraries that Linux does not, notably the PyObjC libraries.  PyObjC won't build on Linux (for obvious reasons).  However, when I create a poetry.lock file that contains Salt on Linux, that lockfile contains all the dependencies from macOS, and `poetry install` attemps to build PyObjC.  Thus the install fails. 

`pip show salt` on Linux does not show PyObjC as a dependency:

on Linux:

```
$ pip show salt   # Linux
Name: salt
Version: 3004.1
Summary: Portable, distributed, remote execution and configuration management system
Home-page: https://saltproject.io
Author: Thomas S Hatch
Author-email: thatch45@gmail.com
License: Apache Software License 2.0
Location: /usr/local/lib/python3.9/site-packages
Requires: contextvars, distro, Jinja2, MarkupSafe, msgpack, psutil, pycryptodomex, PyYAML, pyzmq, requests
```

on macOS:

```
$ pip show salt  # macOS
Name: salt
Version: 3004.1
Summary: Portable, distributed, remote execution and configuration management system
Home-page: https://saltproject.io
Author: Thomas S Hatch
Author-email: thatch45@gmail.com
License: Apache Software License 2.0
Location: /Users/coldham/.pyenv/versions/3.9.12/envs/tmp/lib/python3.9/site-packages
Requires: apache-libcloud, certifi, cffi, chardet, cheroot, cherrypy, contextvars, cryptography, distro, gitdb, gitpython, idna, immutables, importlib-metadata, jaraco.classes, jaraco.collections, jaraco.functools, jaraco.text, jinja2, linode-python, mako, markupsafe, more-itertools, msgpack, portend, psutil, pyasn1, pycparser, pycryptodomex, pyobjc-framework-cocoa, pyobjc-framework-servernotification, pyopenssl, python-dateutil, python-gnupg, pytz, pyyaml, pyzmq, requests, setproctitle, six, smmap, tempora, timelib, urllib3, vultr, zc.lockfile, zipp
Required-by:
```

**Comment by dimbleby** [comment]
cf #2275
