### ISSUE TITLE
Exclude does not work for binary artifacts

### ISSUE THREAD

**Issue by nylocx** [python-poetry/poetry#5441]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Arch Linux x64 Kernel 5.17.1
- **Poetry version**: 1.1.13, 1.2.0b1 and master
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: [pyproject.toml](https://gist.github.com/nylocx/527a6beacb47ea97d6f7194f7192b5a9)

## Issue
First thanks for this great project, can't be said too often.

This issue was partially fixed by the commit mentioned in https://github.com/python-poetry/poetry/issues/4711, but there is still a bug in poetry core (current master).
https://github.com/python-poetry/poetry-core/blob/master/src/poetry/core/masonry/builders/wheel.py#L181-L184

This get the relative path after the `is_excluded` test but the `is_excluded` function expects a path relative to the source root. So even if you ignore a file that is later build into `build/lib*/` it is then copied into the wheel.
This can be easily fixed by changing the order and doing it like

```
rel_path = str(pkg.relative_to(lib))
if pkg.is_dir() or self.is_excluded(rel_path):
    continue

 if rel_path in wheel.namelist():
    continue
```

I hope I got it right, it is a bit hard without a debugger to get the application flow.

Kind regards,
Alex

**Comment by nylocx** [comment]
Any chance someone could have a look at this? I currently manually edit my install to get it to work. I could try to create a PR for the change above, but I'm not sure if I am missing something important.

**Comment by horta** [comment]
Same here: the binaries are being included into `sdist` and `wheel`. Significant part of `pyproject.toml`:

```
packages = [{ include = "hmmer" }]
exclude = [{ path = "hmmer/data/bin/*", format = "sdist" }]
include = [
  { path = "hmmer/data/bin/*", format = "wheel" },
  { path = "build_hmmer.py", format = "sdist" },
  { path = "build_hmmer.sh", format = "sdist" },
]
```

Files inside `hmmer/data/bin/*

Repo: https://github.com/EBI-Metagenomics/hmmer-py

**Comment by finswimmer** [comment]
I cannot reproduce the behavior anymore with the minimal example given by @nylocx in https://github.com/python-poetry/poetry/issues/5441#issuecomment-1156251608

So I assume we have fixed it at some point.

If anyone disagree, feel free to leave a comment and a new minimal example to reproduce the issue.

**Comment by tueda** [comment]
It now works for [my case above](https://github.com/python-poetry/poetry/issues/5441#issuecomment-1180124971). Thanks!
