### ISSUE TITLE
Poetry doesn't install the correct dependency according to its supported Python version

### ISSUE THREAD

**Issue by roipoussiere** [python-poetry/poetry#5447]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: ubuntu 21.10
- **Poetry version**: 1.1.13
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/roipoussiere/94e123906e86448e755f04a1ad798d77

## Issue

I have a wheel dependency on specific url for many platforms (Linuw/macOS/Windows) and many Python version (3.8, 3.9, 3.10).

Despite the fact I use Python 3.9, when I try `poetry install`, the python 3.8 version of the wheel is downloaded.

I also tried to:
- replace `python = "^3.8"` by `python = "^3.9"` (same thing);
- replace `python = "~3.8",  markers = "platform_system == 'Linux'",` by `markers = "python_version ~= '3.8' and platform_system == 'Linux'",` (same thing).

Maybe related to #5378 or #5205, I don't think it's the same issue but I'm not sure.

**Comment by kmsquire** [comment]
I've seen a similar problem with something like the following:

```
package = [
  { platform = "linux", python = "~3.7", url = "https://some.url.com/path/to/package-cp37-cp37-linux_x86_64.whl" },
  { platform = "linux", python = "~3.8", url = "https://some.url.com/path/to/package-cp38-cp38-linux_x86_64.whl" },
  { platform = "linux", python = "~3.9", url = "https://some.url.com/path/to/package-cp39-cp39-linux_x86_64.whl" },
  { platform = "darwin", python = "~3.7", url = "https://some.url.com/path/to/package-cp37-cp37-macosx_10_14_x86_64.whl" },
  { platform = "darwin", python = "~3.8", url = "https://some.url.com/path/to/package-cp38-cp38-macosx_10_14_x86_64.whl" },
  { platform = "darwin", python = "~3.9", url = "https://some.url.com/path/to/package-cp39-cp39-macosx_10_14_x86_64.whl" },
]
```

In this case, poetry attempts to install only the first URL--if I look at `poetry.lock`, I see something like

```
[[package]]
name = "package"
version = "1.2.3"
description = ""
category = "main"
optional = false
python-versions = "*"

[package.source]
type = "url"
url = "https://some.url.com/path/to/package-cp37-cp37-linux_x86_64.whl"
```

So, poetry only stores a single URL in the lock file, despite there being multiple URLs specified in `pyproject.toml`

**Comment by roipoussiere** [comment]
If I use the `{ platform = "linux", python = "~3.8",  url = ...}` approach, Poetry doesn't even try to download the wheel. :thinking:

**Comment by dimbleby** [comment]
@roipoussiere it looks as though you have now published ocp-vtk to pypi, so you should be able simply to go: `ocp-vtk = "^7.5.3"` - right?  

Not to say that this isn't a valid bug report - possibly poetry should do a better job with the list of urls and markers that you were using.  But I expect that the main line case should work just fine with different python versions and platforms and so on.

(by the way the `pyproject.toml` that you linked to is broken, it has a whole series of dead urls because you have `ocpvtk` where you want `ocp_vtk`)

**Comment by roipoussiere** [comment]
> it looks as though you have now published ocp-vtk to pypi, so you should be able simply to go: `ocp-vtk = "^7.5.3"` - right?

Yes, I don't need to specify wheel urls now.

> by the way the pyproject.toml that you linked to is broken, it has a whole series of dead urls because you have ocpvtk where you want ocp_vtk

fixed

> Not to say that this isn't a valid bug report

I don't understand why this isn't a valid bug report. Poetry downloads the wrong wheel according to my python version, this is not an expected behavior, so I made a bug report. Since the dependency is published on PyPI I don't personally need a response now, so feel free to close this if you think is not relevant.

**Comment by dimbleby** [comment]
>  > Not to say that this isn't a valid bug report

>  I don't understand why this isn't a valid bug report.

Apologies if my double-negative confused you.  We are agreeing.
