### ISSUE TITLE
Support for pipwin dependencies.

### ISSUE THREAD

**Issue by bitnom** [python-poetry/poetry#5454]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request
[pipwin](https://pypi.org/project/pipwin/) offers binary wheels for windows for [many packages](https://www.lfd.uci.edu/~gohlke/pythonlibs/) some of which are otherwise difficult to get working. pyaudio is the one I was just having to deal with but the repo has many packages. This request would see the ability to specify pipwin deps in `pyproject.toml` and `poetry add` added.

**Comment by finswimmer** [comment]
Hello @bitnom,

the only way I see to achieve is, to ask the maintainer of this package collection to provide them via a [Simple Repository API](https://peps.python.org/pep-0503/). Once this is done you can define the source in your `pyproject.toml`: https://python-poetry.org/docs/master/dependency-specification/#source-dependencies

fin swimmer
