### ISSUE TITLE
Package is already installed but poetry tries to reinstall it again

### ISSUE THREAD

**Issue by AqeelAT** [python-poetry/poetry#5466]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: MacOS 12.2.1
- **Poetry version**: 1.1.13

## Issue
I had to build `psycopg2-binary@2.8.6` on my machine because the regular package installer does not support m1. I also have it on pyproject.toml. However, every time I try to install or update any other package, it tries to install the library again, and because it is not supported, the operation fails and pyproject is reverted.

Notes:
1. I have to stick with 2.8.6 because it is the latest version supported by django 2.2
2. I'm currently solving it by commenting out `psycopg2-binary@2.8.6` on pyproject, installing or updating whatever I wanted, then uncomment it and run `poetry lock`.

**Comment by abn** [comment]
The issue does not have sufficient information triage.

Can you add some logs, pyproject file etc? Have you set pyproject for psycopg to be an exact version? 

Additionally, is this still an issue with poetry@master?

**Comment by finswimmer** [comment]
Hello @AqeelAT,

you haven't come back to this issue for a long while. So I assume this is solved in the meantime and I can close this ticket.

Feel free to leave a comment if you disagree.

fin swimmer
