### ISSUE TITLE
Unable to find installation candidates for vtk

### ISSUE THREAD

**Issue by Retiefasuarus** [python-poetry/poetry#5478]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 22.04 LTS
- **Poetry version**: 1.1.13
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: [pyproject.toml](https://gist.github.com/Retiefasuarus/666ee1fd18367bf57c08955a9bce9208)

## Issue
Good day,

There seems to be an issue when adding the vtk 9.1

**How to reproduce**
`poetry add vtk`

Error: 

>   • Installing vtk (9.1.0): Pending...
>   • Installing vtk (9.1.0): Failed
> 
>   RuntimeError
> 
>   Unable to find installation candidates for vtk (9.1.0)
> 
>   at ~/.poetry/lib/poetry/installation/chooser.py:72 in choose_for
>        68│ 
>        69│             links.append(link)
>        70│ 
>        71│         if not links:
>     →  72│             raise RuntimeError(
>        73│                 "Unable to find installation candidates for {}".format(package)
>        74│             )
>        75│ 
>        76│         # Get the best link
> 
> 
> Failed to add packages, reverting the pyproject.toml file to its original content.
> 

It is strange since vtk is suppose to be in the remote repositories:

`poetry search vtk`
output: 

> vtk (9.1.0)
>  VTK is an open-source toolkit for 3D computer graphics, image processing, and visualization
> 
> dune-vtk (2.8.0.dev20210524)
>  File reader and writer for the VTK Format
>  . . . `

**Comment by clintonroy** [comment]
Have a gander at https://pypi.org/project/vtk/#files 

You've asked for a version of VTK compiled against python 3.10, and there is none. There is also no source dist to download and attempt a compile.

If vtk is super important to your project, I would change your python version to one that vtk supports.

**Comment by pohlt** [comment]
Or you could download the wheel matching your Python version from https://vtk.org/download/

Then do a `poetry add what_you_just_downloaded.whl`. Voilà. 🥳
