### ISSUE TITLE
Can't install JAX with poetry

### ISSUE THREAD

**Issue by pablo2909** [python-poetry/poetry#5481]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: MacOS 12.3 M1Pro
- **Poetry version**: 1.1.13
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/pablo2909/5990d089042c9729f95672e699be7bca

## Issue

Hello,

I am trying to install JAX (v.0.3.6) using poetry by running `poetry add jax,` which unfortunately fails, and returns **`Failed to add packages, reverting the pyproject.toml file to its original content.`**. I can post the full error message, that is very long. However if I run `pip install jax`, it installs without any problem. 

Has someone encountered the same issue and/or has an idea how to fix it ?

Thank you!

**Comment by Alfro** [comment]
In my environment, `poetry add jax` installs jax correctly using your .toml. I am testing on the Ubuntu WSL, Poetry version 1.1.13.

@pablo2909 do post that full error message. Maybe add it as a Gist?

**Comment by pablo2909** [comment]
HI @Alfro 

Thank you for looking into it. I ran `poetry add tax -vvv` and received this as output https://gist.github.com/pablo2909/9ceba34903bdeb2a21d5fe95dd76cd90 

Weird thing is that I installed JAX a couple of weeks ago with poetry and it worked. Here is the `.toml` of the time it worked: https://gist.github.com/pablo2909/09bf59c6ac959e4377e59c70f4d840df

**Comment by pablo2909** [comment]
I managed to install jax by changing manually in `pyproject.toml` the requirement `python = ^3.8` to `python = ~3.8`. I think the issue comes from script that requires `python <3.11`

**Comment by dimbleby** [comment]
good to close, then?

**Comment by sudomaze** [comment]
I have been trying to install `jax` with `tpu` option on but I couldn't find a way to make to work. I have looked into different issues but nothing worked for my case. Here is the `pip` command that I have used to install `jax` with `tpu` option:

```bash
python -m pip install --upgrade "jax[tpu]==0.3.10" -f https://storage.googleapis.com/jax-releases/libtpu_releases.html
```

I don't want to hardcode things to `.lock` file as I just want it to be part of `pyproject.toml` so in future development and dependencies changes, `poetry` would handle any conflicts/updates. Thanks!

**Comment by abn** [comment]
@sudomaze you can use a Single Page Link Source as described under https://python-poetry.org/docs/master/repositories/#supported-package-sources for this.

Note that this currently only works with poetry from git. Next pre-release should contain it.

**Comment by sudomaze** [comment]
I have tried this and it worked out!

```
jaxlib = { extras = ["tpu"], version = "0.3.10" }
```

I have run a simple unit test to check if tpu was enabled and it seems. Thanks!
