### ISSUE TITLE
Poetry can't install httpx

### ISSUE THREAD

**Issue by sfermigier** [python-poetry/poetry#5497]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: MacOS X 11.6.1
- **Poetry version**: ~1.1.6~ [1.1.13 actually]
- Here's my `pyproject.toml` after much simplification:

```
[tool.poetry]
name = "poetry-bug"
version = "0.1.0"
description = ""
authors = ["Stefane Fermigier <sf@abilian.com>"]

[tool.poetry.dependencies]
python = "^3.10"
httpx = "0.22.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

## Issue

Poetry hangs trying to compute the resolution.

Here's what happens with `poetry install -vvv`:

```
$ poetry install -vvv
Using virtualenv: /Users/fermigier/.virtualenvs/tmp
Updating dependencies
Resolving dependencies...
   1: fact: poetry-bug is 0.1.0
   1: derived: poetry-bug
   1: fact: poetry-bug depends on httpx (0.22.0)
   1: selecting poetry-bug (0.1.0)
   1: derived: httpx (==0.22.0)
   1: fact: httpx (0.22.0) depends on certifi (*)
   1: fact: httpx (0.22.0) depends on charset-normalizer (*)
   1: fact: httpx (0.22.0) depends on sniffio (*)
   1: fact: httpx (0.22.0) depends on rfc3986 (>=1.3,<2)
   1: fact: httpx (0.22.0) depends on httpcore (>=0.14.5,<0.15.0)
   1: selecting httpx (0.22.0)
   1: derived: httpcore (>=0.14.5,<0.15.0)
   1: derived: rfc3986[idna2008] (>=1.3,<2)
   1: derived: sniffio
   1: derived: charset-normalizer
   1: derived: certifi
[hangs]
```

**Comment by sfermigier** [comment]
Well I thought the problem was with the resolution algorithm, but after trying to debug a bit more, I found this:

```
$ poetry add -vvv rfc3986
Using virtualenv: /Users/fermigier/.virtualenvs/tmp
[hangs]
```

vs.

```
$ pip install rfc3986
Collecting rfc3986
  Downloading rfc3986-2.0.0-py2.py3-none-any.whl (31 kB)
Installing collected packages: rfc3986
Successfully installed rfc3986-2.0.0
```

**Comment by abn** [comment]
@sfermigier I cannot reproduce this.

```console
root@6074a0d8f605:/foobar# poetry --version
pPoetry version 1.1.13
root@6074a0d8f605:/foobar# poetry add httpx
Using version ^0.22.0 for httpx

Updating dependencies
Resolving dependencies... (2.4s)

Writing lock file

Package operations: 9 installs, 0 updates, 0 removals

  • Installing idna (3.3)
  • Installing sniffio (1.2.0)
  • Installing anyio (3.5.0)
  • Installing certifi (2021.10.8)
  • Installing h11 (0.12.0)
  • Installing charset-normalizer (2.0.12)
  • Installing httpcore (0.14.7)
  • Installing rfc3986 (1.5.0)
  • Installing httpx (0.22.0)
root@6074a0d8f605:/foobar# 
```

Can you try updating your poetry version? If that does not help, is this an M1 chip or intel machine?

**Comment by sfermigier** [comment]
@abn: Thanks for trying to reproduce.

I'm using the latest published Poetry version (1.1.13), installed via Homebrew. (Sorry I mistyped in the initial bug report).

And that's a M1 chip. It works on Linux, so this is probably related to OSX or the M1 chip.

**Comment by sfermigier** [comment]
Thanks for the reproduction attempts @bbuscarino and @abn. I will close the issue then, to ease the task of the maintainers.

**Comment by vladimirshkoda** [comment]
@sfermigier I faced the same issue, what helped me: clear the cache `poetry cache clear pypi --all`
