### ISSUE TITLE
Nushell 0.6x

### ISSUE THREAD

**Issue by fellnerse** [python-poetry/poetry#5498]
- [x ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [ x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **Mac**: 
- **Latest**: 

## Issue

Nushell got an update to 0.60 last month and as such the current `activate.nu` script does not work anymore (most notably, the syntax for `if...else` changed, but it got a complete rework). If you want I can support you there as well, I have a working version of the scripts now, but could not find the part in your repo that generates this.

**Comment by abn** [comment]
This is not managed by Poetry, but rather via `virtualenv`. See https://github.com/pypa/virtualenv/blob/main/src/virtualenv/activation/nushell/activate.nu. You can update the `virtualenv` package installed in your Poetry runtime environment once there is an upstream fix.

For now, nothing for Poetry to do.

**Comment by fellnerse** [comment]
Aah thanks for pointing this out!

**Comment by abn** [comment]
Did you try a reinstall of poetry via brew?

You need to upgrade the virtualenv version in the envrionment where poetry is installed. You can do it like this maybe.

```console
$ cat $(which poetry) | head -n 1
#!/home/abn/.local/pipx/venvs/poetry/bin/python
$ /home/abn/.local/pipx/venvs/poetry/bin/python -m pip install --upgrade virutalenv
```
