### ISSUE TITLE
Conflict between git and wildcard dependency

### ISSUE THREAD

**Issue by henhuy** [python-poetry/poetry#5507]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 18.04
- **Poetry version**: 1.1.13
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/henhuy/180e51fcb7f1361860b9cd959ebbc051

## Issue

My project depends on two libraries, which both rely on same dependency (here `oemof.solph`).
One library needs a specific branch of the dependency (in this example oemoflex->oemof.tabular->`"oemof.solph @ git+https://git@github.com/oemof/oemof-solph@v0.4#egg=oemof.solph"`) and the other uses a wildcard version (`"oemof.solph" = "*"`). 
In my understanding, this should work, as wildcard stands for any version?!
But `poetry install` throws following error:
```
SolverProblemError

Because oemoflex (rev dev) depends on oemof.tabular (rev dev)
and oemof.tabular (rev dev) depends on oemof.solph (rev v0.4), oemoflex (rev dev) requires oemof.solph (rev v0.4).
So, because solphdep depends on both oemof.solph (*) and oemoflex (branch dev), version solving failed.
```
If you ask yourself, why I am not pinning `oemof.solph` to git branch: Above pyproject.toml is only a minimal working example - in my code `oemof.solph` is dependency from another high-level library...

Or did I misunderstood _wildcard_ versioning?

**Comment by abn** [comment]
This should work find with the code on master. The locking takes around ~180 seconds on my machine. You can get that down to below 30s by using the constraint `"oemof.solph" = "^0.4"` instead of the wildcard.

```sh
podman run --rm -i --entrypoint bash docker.io/python:3.10 <<EOF
set -xe
python -m pip install --disable-pip-version-check -q git+https://github.com/python-poetry/poetry.git
install -d foobar
pushd foobar
curl -sL --output pyproject.toml https://gist.githubusercontent.com/henhuy/180e51fcb7f1361860b9cd959ebbc051/raw/0c3354f0e92846bd8d43909d16c1547958d99d54/pyproject.toml
poetry lock
poetry install
EOF
```
