### ISSUE TITLE
How to create .deb from pyproject.toml and poetry.lock files

### ISSUE THREAD

**Issue by darshan-spd** [python-poetry/poetry#5511]
I am using poetry in my project. I have pyproject.toml file and poetry.lock file.
Since poetry build is creating .tar.gz and .whl files.

I need to create debian package ( .deb) file using poetry.
I don't have setup.py file in the directory.
How to do this?

@abn @venthur can you please help on this.

**Comment by abn** [comment]
This is not within the scope of Poetry. You may want to look at projects like [py2deb](https://py2deb.readthedocs.io/en/latest/). You can either pass it your package or use the output of `poetry export` as it also supports requirements.txt.

**Comment by darshan-spd** [comment]
@abn  As I am new to python programming.
I am using poetry in windows and working fine for my project.

Now i need to build my project for linux use.
so i need steps to build debian package with poetry.

**Comment by abn** [comment]
Assuming you are not building platform specific packages, the same wheels built on Windows will work on Linux machines. 

Poetry works within the Python ecosystem, this means that Poetry builds python sdists (tarballs) and bdists (wheels).

Maybe see https://packaging.python.org/en/latest/overview/ for more information around this.

The .deb packages are specific to Debian, similarly .rpm are specific to redhat distros etc. Poetry is not intended to build these. Your project can be installed and managed without these anyway as Poetry works cross platform.

**Comment by darshan-spd** [comment]
I used poetry-build 
It creates .tar.gz  and .whl

Is that enough for packaging and same files can be installed on linux machine right?

**Comment by abn** [comment]
The wheels can be installed as any python package. Either via pip or another frontend like Poetry. You can also consider distributing your package (if public) to https://pypi.org via `poetry publish`.

Maybe best to ask this either on Poetry's community Discord or at https://www.pythondiscord.com/.

**Comment by darshan-spd** [comment]
@abn 
Thanks a lot for your valuable answers. 
Now i know the end usecase of poetry.
Thank you
