### ISSUE TITLE
poetry add of a GitHub repo with subdirectory fails

### ISSUE THREAD

**Issue by rht** [python-poetry/poetry#5521]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: NixOS unstable
- **Poetry version**: latest master as of https://github.com/python-poetry/poetry/commit/6721ebe0f0c201d50862e8d37ed2c6bfaa03d190

## Issue
I am aware that the Git subdirectory feature was merged in [#192](https://github.com/python-poetry/poetry-core/pull/192). I have also read #755. My goal is to install this [repo](https://github.com/zulip/talon/tree/talon-core-split/talon-core).
This is the syntax that works in requirements.txt (but I want to convert it to Poetry):
```
https://github.com/zulip/talon/archive/1711705c952806d4a704c7dbf58f21db8e11756a.zip#egg=talon-core==1.4.8.zulip1&subdirectory=talon-core
```

I have tried adding this to my pyproject.toml:
```
talon-core = {git = "https://github.com/zulip/talon.git", rev = "1711705c952806d4a704c7dbf58f21db8e11756a", subdirectory = "talon-core" }
```
then ran `poetry lock --no-update` but this fails with
```
  PackageInfoError

  Unable to determine package info for path: /tmp/pypoetry-git-talonlh1f69va
  
  Command ['/tmp/tmp9vi34lbc/.venv/bin/python', '-'] errored with the following return code 1, and output: 
  Traceback (most recent call last):
    File "<stdin>", line 9, in <module>
    File "/tmp/tmp9vi34lbc/.venv/lib/python3.10/site-packages/build/__init__.py", line 208, in __init__
      _validate_source_directory(srcdir)
    File "/tmp/tmp9vi34lbc/.venv/lib/python3.10/site-packages/build/__init__.py", line 109, in _validate_source_directory
      raise BuildException(f'Source {srcdir} does not appear to be a Python project: no pyproject.toml or setup.py')
  build.BuildException: Source /tmp/pypoetry-git-talonlh1f69va does not appear to be a Python project: no pyproject.toml or setup.py
```
This is because it looks like the subdirectory is not passed to `build.ProjectBuilder`. I checked the content of /tmp/pypoetry-git-talonlh1f69va, and it actually the root of the repo, not the subdirectory (the one that actually has setup.py).

Then, I tried `poetry add -v 'git+https://github.com/zulip/talon.git#1711705c952806d4a704c7dbf58f21db8e11756a&subdirectory=talon-core'`. I got an identical error message.

**Comment by rht** [comment]
I think this is the cause of the problem: in https://github.com/python-poetry/poetry/blob/4d0b710daaddb53afc876a95533f620bd21ac120/src/poetry/console/commands/init.py#L444-L446, the subdirectory is not parsed and passed to `get_package_from_vcs`.

This is the stack trace:
```

  Stack trace:

  13  ~/.local/pipx/venvs/poetry/lib/python3.10/site-packages/cleo/application.py:330 in run
        exit_code = self._run(io)

  12  ~/.local/pipx/venvs/poetry/lib/python3.10/site-packages/poetry/console/application.py:174 in _run
        return super()._run(io)

  11  ~/.local/pipx/venvs/poetry/lib/python3.10/site-packages/cleo/application.py:425 in _run
        exit_code = self._run_command(command, io)

  10  ~/.local/pipx/venvs/poetry/lib/python3.10/site-packages/cleo/application.py:467 in _run_command
        raise error

   9  ~/.local/pipx/venvs/poetry/lib/python3.10/site-packages/cleo/application.py:451 in _run_command
        exit_code = command.run(io)

   8  ~/.local/pipx/venvs/poetry/lib/python3.10/site-packages/cleo/commands/base_command.py:118 in run
        status_code = self.execute(io)

   7  ~/.local/pipx/venvs/poetry/lib/python3.10/site-packages/cleo/commands/command.py:85 in execute
        return self.handle()

   6  ~/.local/pipx/venvs/poetry/lib/python3.10/site-packages/poetry/console/commands/add.py:154 in handle
        requirements = self._determine_requirements(

   5  ~/.local/pipx/venvs/poetry/lib/python3.10/site-packages/poetry/console/commands/init.py:349 in _determine_requirements
        requires = self._parse_requirements(requires)

   4  ~/.local/pipx/venvs/poetry/lib/python3.10/site-packages/poetry/console/commands/init.py:439 in _parse_requirements
        package = Provider.get_package_from_vcs(

   3  ~/.local/pipx/venvs/poetry/lib/python3.10/site-packages/poetry/puzzle/provider.py:206 in get_package_from_vcs
        package = cls.get_package_from_directory(tmp_dir, name=name)

   2  ~/.local/pipx/venvs/poetry/lib/python3.10/site-packages/poetry/puzzle/provider.py:286 in get_package_from_directory
        package = PackageInfo.from_directory(path=directory).to_package(

   1  ~/.local/pipx/venvs/poetry/lib/python3.10/site-packages/poetry/inspection/info.py:545 in from_directory
        info = cls._pep517_metadata(path)
```

**Comment by dimbleby** [comment]
duplicate #755

**Comment by rht** [comment]
I opened this issue because #755 was closed at the time.

**Comment by dimbleby** [comment]
I think #755 has been (re)opened since January 2020.  But that's not important, what matters is that we currently have two issues tracking the same thing.

#755 is active, can you close this one please?
