### ISSUE TITLE
Build artifacts omit period from `.dev` segment (1.2.0b1)

### ISSUE THREAD

**Issue by mtkennerly** [python-poetry/poetry#5534]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows 11
- **Poetry version**: 1.2.0b1
- [pyproject.toml](https://github.com/mtkennerly/dunamai/blob/cc1b8c1fc84d33695eabd37d0156a07ced2be287/pyproject.toml) (just change the `version` to `1.11.1.dev1`)

## Issue

On 1.1.13, when the project version contains `.devN`, the build artifacts correctly contain a dot before `dev`:

```console
$ grep -m 1 'version =' pyproject.toml
version = "1.11.1.dev1"

$ pip list | grep poetry
poetry                            1.1.13
poetry-core                       1.0.8

$ poetry version --short
1.11.1.dev1

$ poetry build
Building dunamai (1.11.1.dev1)
  - Building sdist
  - Built dunamai-1.11.1.dev1.tar.gz
  - Building wheel
  - Built dunamai-1.11.1.dev1-py3-none-any.whl
```

However, on 1.2.0b1, the dot is omitted, which violates PEP 440:

```console
$ pip list | grep poetry
poetry                            1.2.0b1
poetry-core                       1.1.0a7

$ poetry version --short
1.11.1.dev1

$ poetry build
Building dunamai (1.11.1.dev1)
  - Building sdist
  - Built dunamai-1.11.1dev1.tar.gz
  - Building wheel
  - Built dunamai-1.11.1dev1-py3-none-any.whl
```

**Comment by dimbleby** [comment]
https://github.com/python-poetry/poetry-core/pull/140. 

Consider:
```python
from poetry.core.utils.helpers import normalize_version

output = normalize_version("1.2.3.dev0")
```
Before, the output is `1.2.3.dev0`. After, `1.2.3dev0`.
