### ISSUE TITLE
Poetry doesn't raise error if using wrong python version

### ISSUE THREAD

**Issue by anth2o** [python-poetry/poetry#5540]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS 12.2.1
- **Poetry version**: 1.1.13
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/anth2o/17c459b8d1e188b8f31791aca79e9b58

## Issue

I have an issue when using Poetry. If I use a `pyproject.toml` similar to the one of the Gist, I want to constrain Python versio  to be 3.10.*.
But if I'm trying to install this package using a lower version (for instance 3.9), I don't have any error displayed:
```bash
$ python -V
Python 3.9.12
$ poetry env info
poet
Virtualenv
Python:         3.9.12
Implementation: CPython
Path:           venv
Valid:          True

System
Platform: darwin
OS:       posix
Python:   /usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9
r%
$ poetry install
Updating dependencies
Resolving dependencies... (0.1s)

Writing lock file
```

I think this is a serious issue since might want to force some Python version and this conflict is silently ignored. The issue is the same if I specify a lower version in the `pyproject.toml`.

**Comment by finswimmer** [comment]
Hello @anth2o,

this is already improved in the latest preview version (1.2.0b1) by https://github.com/python-poetry/poetry/pull/4520.

fin swimmer
