### ISSUE TITLE
Poetry Shell changes the path order

### ISSUE THREAD

**Issue by damienrj** [python-poetry/poetry#5550]
- [ X ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [ X ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ X ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: OSX 12.3.1
- **Poetry version**:  Poetry version 1.1.13

## Issue
When activating a venv with poetry shell the path changes which breaks some packages by changing which version of the package gets found first.

## Before
```
❯ echo $PATH
/Users/damien/Development/notebooks/bin:/Users/damien/Development/notebooks/.hermit/python/bin
```

## Manual activation
`/Users/damien/Development/notebooks/.venv/bin:` is placed correcting at the front of the path.
```
❯ source ./.venv/bin/activate
❯ echo $PATH
/Users/damien/Development/notebooks/.venv/bin:/Users/damien/Development/notebooks/bin:/Users/damien/Development/notebooks/.hermit/python/bin:
```

## poetry shell
`/Users/damien/Development/notebooks/.venv/bin:`  is placed at the front but now the path behind it has been reordered.  We are expecting the same result from shell.
```
❯ poetry shell
Spawning shell within /Users/damien/Development/notebooks/.venv
❯ echo $PATH
/Users/damien/Development/notebooks/.venv/bin:/Users/damien/.zplug/bin:/opt/homebrew/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin:
```

**Comment by dimbleby** [comment]
> the path behind it has been reordered.

This simply isn't a thing that poetry does - it just executes the `activate` script - https://github.com/python-poetry/poetry/blob/f0f5ae22886eebb0359291abc8cbd39c0d16da15/src/poetry/utils/shell.py#L74.

Your third path looks completely different from the first two.  It seems likely that it was that way before venv activation.

**Comment by dimbleby** [comment]
No response, very likely to be user error, should close I reckon
