### ISSUE TITLE
PermissionError  ~/PATH/poetry.lock'

### ISSUE THREAD

**Issue by Sasha-bill** [python-poetry/poetry#5553]
-  I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
-  I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

OS version and name: MacOS Monterey 12.3.1, Python 3.9.12, Python 3.8.10
I have a trouble with `poetry install` and 'poetry add package'

`
      PermissionError
      
        [Errno 1] Operation not permitted: '/Users/alex/PycharmProjects/PROJECT_PATH/poetry.lock'
      
        at /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tomlkit/toml_file.py:17 in read
            13│         self._path = path
            14│ 
            15│     def read(self) -> TOMLDocument:
            16│         """Read the file content as a :class:`tomlkit.toml_document.TOMLDocument`."""
          → 17│         with open(self._path, encoding="utf-8", newline="") as f:
            18│             return loads(f.read())
            19│ 
            20│     def write(self, data: TOMLDocument) -> None:
            21│         """Write the TOMLDocument to the file."""
`
I've tried to reinstall poetry and python, run with root,  grant permissions with chmod 666, chmod 777, remove poetry.lock

**Comment by abn** [comment]
From what I can tell this is not a Poetry issue but rather an environment permission issue. Maybe try the discord channel? Feel free to comment here if you there is more information to go by that indicates a fix in Poetry. For now, closing the issue as there is no action for the project.
