### ISSUE TITLE
Sub module distribution in poetry

### ISSUE THREAD

**Issue by sravix8** [python-poetry/poetry#5555]
I have a repo and I have root folder. Inside that root folder I have a department folder. Inside that I have a year folder. So inside my year folder I have a python script. In init.py I want to use 

```py
try:
    import importlib.metadata as importlib_metadata
except ModuleNotFoundError:
    import importlib_metadata

__version__ = importlib_metadata.version(__name__)
```

I am getting an error NoModuleFoundError when trying to run my tests from poetry. Please advise.

**Comment by Secrus** [comment]
could you please post your directory tree? would be easier to help you.

**Comment by sravix8** [comment]
project-python
v college
   v department
      v class
          __init__.py
          __main__.py
          myclass.py
      __init__.py


Regards
Santosh
Machine Learning Engineering Team
Data Science & Artificial Intelligence

**Comment by Secrus** [comment]
The directory structure you provided is not matching your description in the original issue message. Also I don't see how it is connected to `poetry` itself.  Please provide more info on the matter and how your issue is related to `poetry`, otherwise issue will be closed.

**Comment by finswimmer** [comment]
Hello @sravix8,

you haven't come back to this issue for a long while. So I assume this is solved in the meantime and I can close this ticket.

Feel free to leave a comment if you disagree.

fin swimmer
