### ISSUE TITLE
Poetry 1.1.13 install ziglang 0.8.0 failed in Docker environment

### ISSUE THREAD

**Issue by Droid-MAX** [python-poetry/poetry#5560]
more info in link: https://github.com/Droid-MAX/luna-test

**Comment by clintonroy** [comment]
If you're going to ask for help from people, please don't force the legwork on others. I can't actually see any ziglang in here either.

When attempting to build the docker image, I get:

```Step 5/9 : RUN pip install poetry yowasp-yosys yowasp-nextpnr-ecp5 -i https://pypi.tuna.tsinghua.edu.cn/simple/
 ---> Running in fb2cf8c2198d
/bin/sh: pip: not found
The command '/bin/sh -c pip install poetry yowasp-yosys yowasp-nextpnr-ecp5 -i https://pypi.tuna.tsinghua.edu.cn/simple/' returned a non-zero code: 127
```
This is not a poetry problem. At a guess you need to call pip3 here.

If I make this change, I eventually get:

```
  error: Rust 1.34.2 does not match extension requirement >=1.41.0
  ----------------------------------------
  ERROR: Failed building wheel for cryptography
```

This clearly has nothing to do with poetry.

**Comment by Droid-MAX** [comment]
For some network reason, I modified some repository code to make download process normal in china. And  finally prompt Runtime Error about ziglang.

**Comment by Droid-MAX** [comment]
But I can manually install Ziglang.

**Comment by clintonroy** [comment]
Please always use text to show text errors. And always show the full traceback.

Check https://pypi.org/project/ziglang/0.8.1/#files (which is an old version of ziglang, btw)

There's no source distribution there, and your docker image is using alpine, which i think uses musl libc, and there's no pre-compiled form of the package there.

**Comment by Droid-MAX** [comment]
thx, now I know how should I do.

**Comment by Droid-MAX** [comment]
Issue resolved, closed
