### ISSUE TITLE
Poetry offline installation

### ISSUE THREAD

**Issue by labdmitriy** [python-poetry/poetry#5562]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

Hi, 

I was searching for information about Poetry offline installation, but only found old (almost 2.5 years without updates) and still opened GitHub issue #1783 without answers, so I decided to describe the possible pipeline to install Poetry on machine without internet and also:
- Wrote the [blog post](https://labdmitriy.github.io/blog/poetry-installation-offline), where I suggested possible changes in "Conclusion" section for installation script of the new installer to support offline installation out-of-the-box.
- Prepared [shell scripts](https://github.com/labdmitriy/poetry-offline) which automate preparation and offline installation steps.

Could you please tell how interesting, correct and relevant it is to add changes to the current functionality for offline installation support?

Thank you.

**Comment by kfot** [comment]
@labdmitriy Could you share why have you closed the issue? Have you found a better solution?

**Comment by labdmitriy** [comment]
@kfot I thought that maybe this question will be ignored because there is related issue already opened which is mentioned above.
I have only this solution and in my opinion it could be the simplest method both to install poetry in offline mode and to change current poetry implementation to support it out-of-the-box.
