### ISSUE TITLE
Editable package metadata

### ISSUE THREAD

**Issue by petrprikryl** [python-poetry/poetry#5566]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Editable package metadata

Hi I am using local package installation combining it with Docker this way:
```
[tool.poetry.dependencies]
...
my-lib = {path = "/app/.src/my-lib", develop = true}
```

_Dockerfile:_
```
COPY .src /app/.src
RUN poetry install --no-root
```

_docker-compose.yml_
```
  volumes:
    - .:/app
```

Everything works fine except `console_scripts`. The problem is that the bind mount will remove `.egg-info` directory in `/app/.src/my-lib/src` which has been created in Docker build. And this is leading into this error:
```
Traceback (most recent call last):
  File "/usr/local/bin/depsync", line 33, in <module>
    sys.exit(load_entry_point('my-lib', 'console_scripts', 'depsync')())
  File "/usr/local/bin/depsync", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/local/lib/python3.10/importlib/metadata/__init__.py", line 957, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/local/lib/python3.10/importlib/metadata/__init__.py", line 548, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for my-lib
```

And I found that it could be fixed by changing path to `site-packages` while installing editable package https://jbhannah.net/articles/python-docker-disappearing-egg-info

Would it be possible to integrate this technique into Poetry? 🙏

**Comment by finswimmer** [comment]
Hello @petrprikryl,

which version of Poetry are you using. Poetry doesn't create an `.egg-info` folder anymore for path dependencies for a very long time.

fin swimmer

**Comment by neersighted** [comment]
Closing as there is no good reproduction and this code has long been removed from Poetry.
