### ISSUE TITLE
Poetry dynamic versioning not adhering to SemVer 2.0 when setting `style=semver` and `bump=true` but not with `bump=false`

### ISSUE THREAD

**Issue by jmartens** [python-poetry/poetry#5575]
- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: 
```
systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.19044 N/A Build 19044
```

- **Poetry version**: 
```
pip show poetry
Name: poetry
Version: 1.1.13
Summary: Python dependency management and packaging made easy.
Home-page: https://python-poetry.org/
Author: Sébastien Eustace
Author-email: sebastien@eustace.io
License: MIT
Location: **RECACTED**\venv\lib\site-packages
Requires: cachecontrol, cachy, cleo, clikit, crashtest, html5lib, keyring, packaging, pexpect, pkginfo, poetry-core, requests, requests-toolbelt, shellingham, tomlkit, virtualenv
Required-by:
```
- **python version**: 3.9.12

- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 
Relevant configuration from pyrpoject.toml:
```
[tool.poetry]
...
version = "0.0.0"
...

[tool.poetry-dynamic-versioning]
enable = true
bump = true
style = "semver"

[tool.poetry.scripts]
poetry-dynamic-versioning = 'poetry_dynamic_versioning.__main__:main'
```
## Issue

When building a python project on Windows using Poetry I get below exception when I set `bump` to `true`.

```(venv) ***REDACTED***>poetry build -vvv
Using virtualenv: ***REDACTED***\venv
Building **REDACTED** (1.0.0-rc.2.pre.8+b504267)

  Stack trace:

  9  venv\lib\site-packages\clikit\console_application.py:131 in run
      129│             parsed_args = resolved_command.args
      130│
    → 131│             status_code = command.handle(parsed_args, io)
      132│         except KeyboardInterrupt:
      133│             status_code = 1

  8  venv\lib\site-packages\clikit\api\command\command.py:120 in handle
      118│     def handle(self, args, io):  # type: (Args, IO) -> int
      119│         try:
    → 120│             status_code = self._do_handle(args, io)
      121│         except KeyboardInterrupt:
      122│             if io.is_debug():

  7  venv\lib\site-packages\clikit\api\command\command.py:171 in _do_handle
      169│         handler_method = self._config.handler_method
      170│
    → 171│         return getattr(handler, handler_method)(args, io, self)
      172│
      173│     def __repr__(self):  # type: () -> str

  6  venv\lib\site-packages\cleo\commands\command.py:92 in wrap_handle
       90│         self._command = command
       91│
    →  92│         return self.handle()
       93│
       94│     def handle(self):  # type: () -> Optional[int]

  5  venv\lib\site-packages\poetry\console\commands\build.py:36 in handle
      34│
      35│         builder = Builder(self.poetry)
    → 36│         builder.build(fmt, executable=self.env.python)
      37│

  4  venv\lib\site-packages\poetry\core\masonry\builder.py:35 in build
      33│
      34│         for builder in builders:
    → 35│             builder(self._poetry, executable=executable).build()
      36│

  3  venv\lib\site-packages\poetry\core\masonry\builders\builder.py:92 in __init__
       90│         )
       91│
    →  92│         self._meta = Metadata.from_package(self._package)
       93│
       94│     @property

  2  venv\lib\site-packages\poetry\core\masonry\metadata.py:52 in from_package
      50│
      51│         meta.name = canonicalize_name(package.name)
    → 52│         meta.version = normalize_version(package.version.text)
      53│         meta.summary = package.description
      54│         if package.readme:

  1  venv\lib\site-packages\poetry\core\utils\helpers.py:35 in normalize_version
       33│
       34│ def normalize_version(version):  # type: (str) -> str
    →  35│     return str(Version(version))
       36│
       37│

  InvalidVersion

  Invalid version: '1.0.0-rc.2.pre.8+b504267'

  at venv\lib\site-packages\poetry\core\version\version.py:61 in __init__
       57│     def __init__(self, version):  # type: (str) -> None
       58│         # Validate the version and parse it into pieces
       59│         match = VERSION_PATTERN.match(version)
       60│         if not match:
    →  61│             raise InvalidVersion("Invalid version: '{0}'".format(version))
       62│
       63│         # Store the parsed out pieces of the version
       64│         self._version = _Version(
       65│             epoch=int(match.group("epoch")) if match.group("epoch") else 0,
```

The generated version number fails to build due to not adhering to SemVer scheme, although with `bump` to `false` it seems `` is OK and runs a successful build:
```
poetry build -vvv
Using virtualenv: **REDACTED**\venv
Building **REDACTED** (1.0.0-rc.1.post.8+b504267)
  - Building sdist
  - Adding: **REDACTED**\runner\__init__.py
  - Adding: **REDACTED**\runner\_version.py
  - Adding: **REDACTED**\runner\config.py
  - Adding: **REDACTED**\runner\constants.py
  - Adding: **REDACTED**\runner\logging.py
  - Adding: **REDACTED**\runner\runner.py
  - Adding: **REDACTED**\runner\utils.py
  - Adding: pyproject.toml
  - Built **REDACTED**-1.0.0rc1.post8+b504267.tar.gz
  - Building wheel
  - Adding: **REDACTED**\runner\__init__.py
  - Adding: **REDACTED**\runner\_version.py
  - Adding: **REDACTED**\runner\config.py
  - Adding: **REDACTED**\runner\constants.py
  - Adding: **REDACTED**\runner\logging.py
  - Adding: **REDACTED**\runner\runner.py
  - Adding: **REDACTED**\runner\utils.py
Skipping: **REDACTED**/COPYING
Skipping: **REDACTED**/LICENSE
  - Built **REDACTED**-1.0.0rc1.post8+b504267-py3-none-any.whl
```

**Expected behavior**
AFAICT both version numbers adhere to SemVer 2.0 especially [item 9](https://semver.org/spec/v2.0.0.html#spec-item-9) and [item 10](https://semver.org/spec/v2.0.0.html#spec-item-10) so I expect them both to either fail or pass, instead of the current behavior.

**Comment by abn** [comment]
Do not think this is a Poetry issue, but rather an issue with https://github.com/mtkennerly/poetry-dynamic-versioning plugin?

Additionally note that Poetry enforces PEP 440 when building projects. And PEP 440 is not a 100% compliant with semver.

**Comment by abn** [comment]
Related: #4811

**Comment by jmartens** [comment]
> Do not think this is a Poetry issue, but rather an issue with https://github.com/mtkennerly/poetry-dynamic-versioning plugin?

I think this issue is dismissed to early and easy since my complaint is not based on the dynamic versioning part, but on the difference in behavior of Poetry core functionality allowing one generated version number while disallowing another similar one that both adhere to SemVer 2.0.

> Additionally note that Poetry enforces PEP 440 when building projects. And PEP 440 is not a 100% compliant with semver.
I was unaware that it does not enforce SemVer which I explicitly configured as can be seen in my opening statement. If it does not enforce SemVer why does it than even complain the version number is invalid and raise an exception?

**Comment by jmartens** [comment]
I have ran both builds in a debugger and the version numbers are generated properly by the dynamic versioning plugin and are both valid SemVer 2.0 version strings.
The problem however occurs at build time where version enforcement is performed using Poetry internal normalization functions in `version.py` using `VERSION_PATTERN` regex.

**Comment by jmartens** [comment]
Since you state you verify for PEP 440 I would expect verification (and normalization) to be ignored and the version number to be applied regardless when any other style is specified. 

Now you seem to support SemVer but instead sometimes fail the build (QED) by enforcing validation using a PEP 440 normalization which is not applicable.

**Comment by jmartens** [comment]
Somehow [your Factory method ran in application.py](https://github.com/python-poetry/poetry/blob/68649946fe09d52ed1a5844bda6690ba6327c408/poetry/console/application.py#L69) seems to be capable of extracting/generating the correct version using a plugin into the `self.poetry.package.version` is there realy no way of reusing this for proper validation according to the style chosen?

**Comment by abn** [comment]
This is not about PyPA alone, we need artifacts and metadata to play well with other tools too.

On `poetry@master`, this will fail early.

```console
$ poetry version 1.0.0-rc.2.pre.8+b504267

  InvalidVersion

  Invalid PEP 440 version: '1.0.0-rc.2.pre.8+b504267'
```
