### ISSUE TITLE
Poetry export: include "via" information, like pip-compile

### ISSUE THREAD

**Issue by mitchhentges** [python-poetry/poetry#5580]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

When `pip-compile` creates a `requirements.txt`, it will include a "via" line for each requirement: this line defines the rationale for why the requirement was included, such as "via -r requirements.in" or "via requests"

`poetry` has access to this information, it would be cool if it could be propagated to the file created by `poetry export`.

Example from `pip-compile`:
```
#
# This file is autogenerated by pip-compile with python 3.10
# To update, run:
#
#    pip-compile
#
certifi==2021.10.8
    # via requests
charset-normalizer==2.0.12
    # via requests
idna==3.3
    # via requests
requests==2.27.1
    # via -r requirements.in
urllib3==1.26.9
    # via requests
```

**Comment by abn** [comment]
@mitchhentges what exactly is the point of this? Shouldn't `poetry show --tree` or the proposed `--why` (#5444) solve the use case?

**Comment by mitchhentges** [comment]
I'm trying to target the use case of people migrating away from `pip-compile`: I'm building a tool to ease that migration [over here](https://gitlab.com/mitchhentges/pip-compile-cross-platform).

Essentially, its goal is to allow developers to continue interacting with a raw `requirements.in` and `requirements.txt`, but to inject `poetry` into the middle so that the `requirements.txt` has environment markers.

The bummer here (for this use case, specifically) is that `poetry` only keeps the "via" information in the `poetry.lock`, which is thrown out in the process described above (aside: the tool re-feeds the `requirements.txt` back through `poetry` to act as a lockfile, which allows developers to not have to store _two_ lockfiles, in a sense).

**Comment by abn** [comment]
@mitchhentges sounds like you are better off implementing a new format in the https://github.com/python-poetry/poetry-plugin-export project that is specific to `pip-compile`.

Alternatively, you can try creating a plugin of your own to handle that. Based on this being an esoteric use case, you might be better off implementing something separate.

Either way, I do not tihnk this is something that will be handled by the Poetry itself. I am going to close this now.
