### ISSUE TITLE
macOS - the clang compiler does not support '-march=native'

### ISSUE THREAD

**Issue by leschiffres** [python-poetry/poetry#5615]
Hi,

I was able to install the `annoy` python module (https://github.com/spotify/annoy) using pip, but weirdly enough when using poetry I am getting the issue `clang: error: the clang compiler does not support '-march=native'`

- I’ve tried python 3.8, 3.9 and it fails on both python versions
- I tried to install it by adding the line `annoy = { git = "https://github.com/spotify/annoy/", tag = "v1.17.0" }` in the `pyproject.toml` file and this did not work either.
- I also installed gcc with brew using brew install gcc.

Any ideas? ( I am using macOS Monterrey 12.3.1. and poetry version 1.1.9)

**Comment by Secrus** [comment]
Hi. Please update your `poetry` to latest version (1.1.13) and check if that helps. If not, please attach debug (`-vvv` option) and steps to recreate.

**Comment by abn** [comment]
Might be related - https://stackoverflow.com/a/66333485

Additionally, it seems [annoy does not have any wheels for M1 on PyPI](https://pypi.org/project/annoy/#files) this would explain why poetry tries to build from source. And obviously from source when adding the dependency as a vcs dependency.

**Comment by leschiffres** [comment]
Thanks for the responses @Secrus, @abn.

> Hi. Please update your poetry to latest version (1.1.13) and check if that helps. If not, please attach debug (-vvv option) and steps to recreate.

Initially I had an issue because I could not update the poetry version with `poetry self update`, but I found a workaround.
Anyway, I was able to update it and now `annoy` was installed just fine.

Thanks
