### ISSUE TITLE
ValueError: <src_root> is not in the subpath of <project_root>

### ISSUE THREAD

**Issue by alextremblay** [python-poetry/poetry#5621]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **Ubuntu 20.04 & MacOS 11.6**: 
- **Poetry version**: 
- **[Example pyproject file](https://gist.github.com/alextremblay/427e54bd1a0eaa38646875ec0cf1a214#file-example-pyproject-toml)**: 

## Issue

Hello!

I maintain a python monorepo called utsc-networking containing multiple packages under a pep420 namespace called `utsc`.
my repository structure has all python source for all packages in a single source tree, and all project metadata for individual packages in separate project directories. Ex:
```console
 $ tree
.
├── projects
│   ├── core
│   │   ├── pyproject.toml
│   │   └── readme.md
│   └── proj1
│       ├── pyproject.toml
│       └── readme.md
└── src
    └── utsc
        ├── core
        │   └── __init__.py
        └── proj1
            └── __init__.py
```

I want to package these projects such that the `pyproject.toml` file for "core" packages `utsc/core` from the `src` folder.
in `projects/core/pyproject.toml` (referenced in the above gist), i set:
```toml
packages = [
  { include = "utsc/core", from = "../../src" }
]
```

there is no particul'ar reason why this should fail, except that:

```console
Building utsc.core (2022.5.13)
  - Building sdist

  Stack trace:

  10  /opt/pipx/venvs/poetry/lib/python3.10/site-packages/clikit/console_application.py:131 in run
      status_code = command.handle(parsed_args, io)

   9  /opt/pipx/venvs/poetry/lib/python3.10/site-packages/clikit/api/command/command.py:120 in handle
      status_code = self._do_handle(args, io)

   8  /opt/pipx/venvs/poetry/lib/python3.10/site-packages/clikit/api/command/command.py:171 in _do_handle
      return getattr(handler, handler_method)(args, io, self)

   7  /opt/pipx/venvs/poetry/lib/python3.10/site-packages/cleo/commands/command.py:92 in wrap_handle
      return self.handle()

   6  /opt/pipx/venvs/poetry/lib/python3.10/site-packages/poetry/console/commands/build.py:36 in handle
      builder.build(fmt, executable=self.env.python)

   5  /opt/pipx/venvs/poetry/lib/python3.10/site-packages/poetry/core/masonry/builder.py:35 in build
      builder(self._poetry, executable=executable).build()

   4  /opt/pipx/venvs/poetry/lib/python3.10/site-packages/poetry/core/masonry/builders/sdist.py:87 in build
      files_to_add = self.find_files_to_add(exclude_build=False)

   3  /opt/pipx/venvs/poetry/lib/python3.10/site-packages/poetry/core/masonry/builders/sdist.py:319 in find_files_to_add
      to_add = super(SdistBuilder, self).find_files_to_add(exclude_build)

   2  /opt/pipx/venvs/poetry/lib/python3.10/site-packages/poetry/core/masonry/builders/builder.py:196 in find_files_to_add
      include_file.relative_to_project_root()

   1  /opt/pipx/venvs/poetry/lib/python3.10/site-packages/poetry/core/masonry/builders/builder.py:369 in relative_to_project_root
      return self.path.relative_to(self.project_root)

  ValueError

  '/home/atremblay/test/src/utsc/core/__init__.py' is not in the subpath of '/home/atremblay/test/projects/core' OR one path is relative and the other is absolute.

  at /usr/local/lib/python3.10/pathlib.py:816 in relative_to
       812│         n = len(to_abs_parts)
       813│         cf = self._flavour.casefold_parts
       814│         if (root or drv) if n == 0 else cf(abs_parts[:n]) != cf(to_abs_parts):
       815│             formatted = self._format_parsed_parts(to_drv, to_root, to_parts)
    →  816│             raise ValueError("{!r} is not in the subpath of {!r}"
       817│                     " OR one path is relative and the other is absolute."
       818│                              .format(str(self), str(formatted)))
       819│         return self._from_parsed_parts('', root if n == 1 else '',
       820│                                        abs_parts[n:])
```

This error is caused by a limitation in `pathlib.Path.relative_to`, as described here: https://stackoverflow.com/questions/67452690/pathlib-path-relative-to-vs-os-path-relpath

This issue can be fixed by using `os.path.relpath` instead of `pathlib.Path.relative_to`  on lines 397 and 401 of `src/poetry/core/masonry/builders/builder.py`.

I will submit a PR for this fix momentarily

**Comment by urig** [comment]
Just wanted to add that this fix would be most useful to me too (as described in [a question I posted on stackoverflow.com](https://stackoverflow.com/questions/72629578/python-how-to-make-poetry-include-a-package-module-thats-not-on-a-subpath)).

**Comment by finswimmer** [comment]
Hello @alextremblay,

all packages must be a subpath of the project root, because otherwise it's not possible to put all packages in the `sdist`. And even if that would be possible, than the paths to that packages would be in the `sdist` different to those in the system and one cannot build a `wheel` from it.

Instead of defining the `utsc/*` stuff as packages, make them a poetry project as well and define them as dependencies.

fin swimmer

**Comment by alextremblay** [comment]
Hi @finswimmer , I'm not sure I understand your comment. How would I go about doing that?

**Comment by urig** [comment]
@finswimmer it is not technically impossible to get this done. For example, [hatch ](https://github.com/pypa/hatch)supports this via a feature called [forced inclusion](https://hatch.pypa.io/latest/config/build/#forced-inclusion).

Defining external source code as poetry projects and consuming them as dependencies is not an optimal solution as it introduces some of yak shaving in that the project needs to be rebuilt every time code changes. As a fan of both poetry and hatch I would love to see poetry gain this ability. May I kindly ask that this issue be re-opened? Thank you.

**Comment by dimbleby** [comment]
[#356](https://github.com/python-poetry/poetry-core/pull/356) is still alive - and I see you're in the discussion already - getting that MR or one like it to the point where folk are happy with it is likely a more effective way to progress your use case.
