### ISSUE TITLE
How do I temporarily set a config option on the command line?

### ISSUE THREAD

**Issue by tddschn** [python-poetry/poetry#5622]
Most of the times I prefer `virtualenvs.in-project = null`, but sometimes I want to use `virtualenvs.in-project = true` for a project.

I want to temporarily set a config option on the command line, how do I do that?

**Comment by Secrus** [comment]
I am not sure what you mean by "temporarily", but you can use `--local` option (only mentioned in ["configuration" page](https://python-poetry.org/docs/master/configuration/#local-configuration), there is an issue to fix this). Does that satisfy your needs?

**Comment by tddschn** [comment]
Yes, that works for me. Thank you! @Secrus 

By `temporarily`, I mean configure this option only for this command run,
like doing `poetry install -o virtualenvs.in-project=true`.
