### ISSUE TITLE
`poetry show` `--why` option requires `--tree` 

### ISSUE THREAD

**Issue by Secrus** [python-poetry/poetry#5625]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue
`--why` option on `poetry show` command is dependent on `--tree` option, but documentation doesn't reflect that. `--why` should be listed as suboption under `--tree`, have note about it in its description or be denoted the same way `--only` is (note box).

**Comment by tgolsson** [comment]
It shouldn't, but I agree I didn't write docs clearly. You should be able to show `--why` for the full table as well; and it'll include it in the table. So it's either package + tree + why or why without either.

**Comment by Secrus** [comment]
@tgolsson can it be assumed, that you will make a PR fixing the docs?

**Comment by tgolsson** [comment]
Yes, sorry! Wanted to make one yesterday but got caught up in other things.

**Comment by Secrus** [comment]
> Yes, sorry! Wanted to make one yesterday but got caught up in other things.

No worries. Just wanted to know whether to expect anything. Take your time
