### ISSUE TITLE
Poetry picks wrong platform when resolving a package with setup.py

### ISSUE THREAD

**Issue by ampx-mg** [python-poetry/poetry#5639]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 20.04.4 LTS
- **Poetry version**: 1.1.13
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue
Poetry does not respect markers for platform dependency when resolving a project which uses `setup.py`. In my case, `imported_project` is a library which uses `setup.py` and there is no problem installing it, but if I try to add it to `test_project`, which uses poetry, as a dependency it picks the wrong platform for its dependencies.

Steps to reproduce:
1. create 2 empty folders - `test_project`, `imported_project`
2. in `test_project/pyproject.toml` have
```
[tool.poetry]
name = "test_project"
version = "0.1.0"
description = "Test"
authors = []

[tool.poetry.dependencies]
python = "^3.8"
imported_project = {path = "../imported_project"}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```
3. in `imported_project/setup.py` have (changing the order here does not seem to help)
```
import os
from setuptools import setup
NAME = "imported_project"
setup(
    name=NAME,
    version=os.getenv("TARGET_RELEASE"),
    install_requires=install_requires=[
        'numpy==1.21.6',
        'numba==0.55.1; sys_platform == "linux"',
        'importlib-metadata; sys_platform == "darwin"',
        'llvmlite==0.38.0; sys_platform == "linux"',
        'llvmlite @ https://anaconda.org/numba/llvmlite/0.39.0.dev0%2B61.gf27ac6f/download/llvmlite-0.39.0.dev0%2B61.gf27ac6f-cp38-cp38-macosx_11_0_arm64.whl ; sys_platform == "darwin"',
        'numba @ https://pypi.anaconda.org/numba/label/wheels_experimental_m1/simple/numba/0.56.0.dev0%2B418.g637a75023/numba-0.56.0.dev0%2B418.g637a75023-cp38-cp38-macosx_11_0_arm64.whl ; sys_platform == "darwin"'
    ],
)
```
4. back in `test_project` when trying to run
```
poetry lock -vvv
```
I get on my linux machine
```
SolverProblemError

  Because numba (0.55.1) depends on llvmlite (>=0.38.0rc1,<0.39)
   and imported-project (0.0.0) depends on llvmlite (0.39.0.dev0+61.gf27ac6f), numba (0.55.1) is incompatible with imported-project (0.0.0).
  So, because test-project depends on imported_project (0.0.0) which depends on numba (0.55.1), version solving failed.
```

I would expect poetry to resolve to linux dependent packages. Looking through `imported_project/imported_project.egg-info/requires.txt` it appears alright
```
numpy==1.21.6

[:sys_platform == "darwin"]
importlib-metadata
llvmlite@ https://anaconda.org/numba/llvmlite/0.39.0.dev0%2B61.gf27ac6f/download/llvmlite-0.39.0.dev0%2B61.gf27ac6f-cp38-cp38-macosx_11_0_arm64.whl
numba@ https://pypi.anaconda.org/numba/label/wheels_experimental_m1/simple/numba/0.56.0.dev0%2B418.g637a75023/numba-0.56.0.dev0%2B418.g637a75023-cp38-cp38-macosx_11_0_arm64.whl

[:sys_platform == "linux"]
numba==0.55.1
llvmlite==0.38.0
```
Can provide more information if needed.

**Comment by Secrus** [comment]
Could you please try it with poetry from master branch? Best way it tou use `pipx`.
#### Install Poetry from VCS
```sh
pipx install --force --suffix=@git 'poetry @ git+https://github.com/python-poetry/poetry.git'
```

#### Install Poetry Core from VCS
```sh
pipx inject --force poetry@git 'poetry-core @ git+https://github.com/python-poetry/poetry-core.git'
```

Note `poetry@git` refers to the vcs version of Poetry installed above.

**Comment by ampx-mg** [comment]
@Secrus 
Can confirm this resolves correctly with master branch on Linux, I do not have the opportunity to test it on MacOS now. Does this mean I need to wait for `poetry=1.2.0` to get released to use this functionality?

**Comment by Secrus** [comment]
The plan is for 1.2  to be released before July. Until then, I would recommend using the master version or patience ;)
