### ISSUE TITLE
Provide option to raise error if package cannot be retrieved from specified index

### ISSUE THREAD

**Issue by Korijn** [python-poetry/poetry#5646]
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request
Assume the following situation:

* Default package index is pypi
* Alternative package index is private, needs authentication
* Package `foo` can be found both on pypi, and on the alternative package index
* Package `foo` is specified in `pyproject.toml` to be sourced from the alternative package index using the `index` option

If I run `poetry lock`, and my authentication details for the alternative package index are expired or invalid, poetry will silently fall back to locking package `foo` to the found package in the `pypi` index.

It would be great if poetry instead gave an error, informing the user that the package was not retrieved from the index that was specified.

Bonus points if it can also tell the user about the underlying issue (invalid credentials in this example).

Since I realize this would be a change in established behavior, it might be good to add a configuration option to enable this behavior.

**Comment by abn** [comment]
@Korijn is this still the case on master? 

https://github.com/python-poetry/poetry/blob/48171301ef032fec1e3ec1ae5d40f71e45c680ea/src/poetry/repositories/pool.py#L155-L167

**Comment by finswimmer** [comment]
Hello @Korijn,

you haven't come back to this issue for a long while. So I assume this is solved in the meantime and I can close this ticket.

Feel free to leave a comment if you disagree.

fin swimmer
