### ISSUE TITLE
Credentials missing in pip when resolving deps

### ISSUE THREAD

**Issue by RoloffMatek** [python-poetry/poetry#5649]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Win10
- **Poetry version**: 1.1.13
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue
Hi all,

today I was finally able to figure out why my poetry add/install/update commands got stuck. I am using poetry behind a proxy and therefore configured poetry to use a private pypi repo. For this repo I also configured the credentials. When I add/install pypi packages that consist of simple whl files everything is fine. However when I install big packages like numpy or scipy that consist of zipped src files poetry gets stuck. At the beginning I thought it was a credentials/network problem. However today I stepped with a debugger through the process of adding for example numpy and I could see that the download worked. Poetry got stuck when it tried to install numpy into a venv in a temp folder, I guess it makes it to figure out the dependencies. The problem is that the process gets stuck in `poetry/inspection/info.py` in line 467. Due to the debugger I saw the arguments that were used to execute pip and I ran them in a cmd in the tempfolder by myself. And tada - this pip was asking to enter username and password. This is why it got stuck infinetely. As a workaround I added a global pip.ini file where the username and password of the private pypi is specified. Now it runs like a charm. My question ist is that behavior intended? Did I make a mistake in my setup?

**Comment by Secrus** [comment]
Hi. Have you configured your credentials as in docs: https://python-poetry.org/docs/repositories/#configuring-credentials ?

**Comment by RoloffMatek** [comment]
Hi,

yes I used `poetry config http-basic.my-private-pypi username password`. Like I said the credentials work when I installed/added simple whl files.

**Comment by Secrus** [comment]
Ok, could you try `master` branch please? Easiest way is to use `pipx` (so you won't break your stable poetry installation). 

#### Install Poetry from VCS
```sh
pipx install --force --suffix=@git 'poetry @ git+https://github.com/python-poetry/poetry.git'
```

#### Install Poetry Core from VCS
```sh
pipx inject --force poetry@git 'poetry-core @ git+https://github.com/python-poetry/poetry-core.git'
```

Note `poetry@git` refers to the vcs version of Poetry installed above.

**Comment by RoloffMatek** [comment]
It seems like I am unable to connect to GitHub due to my proxy restrictions. I think somebody who knwos really well what's going on inside poetry's dependency resolution should check whether the credentials of private repos are forwarded correctly to the temporary pip in the venv where packages are installed in order to resolve their dependencies. Otherwise this fresh pip doesn't have the credentials for the private repo and asks for them. Since this happens in a subprocess the process gets stuck forever.

**Comment by neersighted** [comment]
Addressed by https://github.com/python-poetry/poetry/pull/6724 (that is to say, we now will error out instead of hanging).
