### ISSUE TITLE
Terminal initialization fails due to poetry autocomplete with oh-mz-zsh 

### ISSUE THREAD

**Issue by tunayokumus** [python-poetry/poetry#5652]
- [ ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [X] I am on the most recent pre-release version
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **Ubuntu 20.04** 
- **Poetry 1.2.0b1** 

## Issue

Hi there,

I installed poetry via the new install-poetry.py installer. And configured autocomplete for oh-my-zsh according to poetry docs.
Poetry works fine in my existing project folder. Also terminal initialization and autocomplete works fine when I'm on an existing project folder with a pyproject.toml file.

However when I open a new terminal on a non-poetry-project folder (e.g. home folder). I get the following error:
I'm not sure why poetry needs an existing pyproject.toml file to use the autocomplete feature.

```
-- console output produced during zsh initialization follows --


  RuntimeError

  Poetry could not find a pyproject.toml file in /home/my_user_name or its parents

  at .local/share/pypoetry/venv/lib/python3.9/site-packages/poetry/core/factory.py:455 in locate
      451│             if poetry_file.exists():
      452│                 return poetry_file
      453│
      454│         else:
    → 455│             raise RuntimeError(
      456│                 f"Poetry could not find a pyproject.toml file in {cwd} or its parents"
      457│             )
      458│
```

Any idea why this happens? Is anyone able to reproduce this?
Thanks

**Comment by tunayokumus** [comment]
This issue seems to be relevant if not same to #5411

**Comment by tunayokumus** [comment]
This seems to be related to a poetry plugin. The issue is gone after removing the plugin poetry-dynamic-versioning-plugin.

**Comment by dimbleby** [comment]
then I guess this should be closed and you can take the but report to that plugin
