### ISSUE TITLE
Wheels for `armv7` and `armv8`

### ISSUE THREAD

**Issue by PaTara43** [python-poetry/poetry#5684]
Hi, is it possible to add wheels for this kernels? Otherwise it takes quite a while installing a `cryptography` dependency which requires Rust.

Thanks.

**Comment by finswimmer** [comment]
Hello @PaTara43,

a wheel does not contain the dependencies of the package. So it will not help you, if there where a specific wheel of `poetry` for your requested architecture. You have to ask the `cryptography` maintainers to provide such wheels.

fin swimmer
