### ISSUE TITLE
Poetry install behaves different on Windows10 and Ubuntu 18.04

### ISSUE THREAD

**Issue by martin-91x** [python-poetry/poetry#5685]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows 10 21H2 / Ubuntu 18.04.6 LTS 
- **Poetry version**: 1.1.13
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/martin-91x/7a2140f42bf5f09c9cc9208b683f7aec

## Issue

When running `poetry install` on a machine with Windows 10, everything seems to work fine. With a current lock file present and an already prepared environment (miniconda), the output is:
```
Installing dependencies from lock file
No dependencies to install or update
Installing the current project: ProjectBlackthorn (0.1.0)
```

Now, I cloned the exact same repository to a Ubuntu 18.04 device (with venv properly set up). Here I get the following output from `poetry install`:
```
Installing dependencies from lock file
No dependencies to install or update
```

And there is the problem I have: On Ubuntu, my current project gets not installed and running `poetry install -vvv` does not provide any output besides that all dependencies are already installed.

**Comment by martin-91x** [comment]
Hi,

this is the folder structure of my project. I removed most of the python files to keep it clean.

```
ProjectBlackthorn
├─ .git
├─ .github
├─ .gitignore
├─ config
├─ data
├─ docs
├─ LICENSE
├─ models.py
├─ poetry.lock
├─ pyproject.toml
├─ pytest.ini
├─ samples
│  └─ onnx
├─ scripts
├─ src
│  └─ ProjectBlackthorn
│     ├─ backends
│     ├─ benchmark_logging
│     ├─ blackthorn_benchmark.py
│     ├─ blackthorn_onnx
│     ├─ common
│     ├─ data
│     ├─ fitting
│     ├─ layers
│     ├─ model_graph
│     └─ __init__.py
├─ target_setup.py
├─ test
│  ├─ conftest.py
│  ├─ layers_test
```

**Comment by finswimmer** [comment]
Yep, this is an issue with upper/lower cases.

The package autodiscovery feature by Poetry is looking for a folder with a normalized version of `name`. On Windows `ProjectBlackthorn` and `projectblackthorn` are the same, but not on Linux.

You could either rename `src/ProjectBlackthorn` to `src/projectblackthorn` (and adopt `import` statements) or explicit tell Poetry where the package is located (https://python-poetry.org/docs/pyproject/#packages):

```toml
[tool.poetry]
# ...
packages = [
    { include = "ProjectBlackthorn", from="src" },
]
```
