### ISSUE TITLE
poetry shell failing to set up my .venv local environment

### ISSUE THREAD

**Issue by epomatti** [python-poetry/poetry#5690]
- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 22.04 (WSL2)
- **Poetry version**: 1.1.13
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/epomatti/68b318e2cda239dfda5f317f170b0243

## Issue

My project is set up to use in-project virtual environments. My `poetry.toml`:

```toml
[virtualenvs]
in-project = true
```

I make sure that my envs are empty:

```sh
$ poetry env list
# envs are empty
```

I install the dependencies, and it creates the `.venv` directory in the root of my project. The command appears to complete successfully, but there is a problem.

```sh
$ poetry install
```

<img src="https://user-images.githubusercontent.com/6530769/170406159-76f663b1-afdb-40c5-ab50-ad9a46690a19.png" width=200 />

The problem is that virtual env shell did not initiate. It doesn't have the `(.venv)` prefix in my terminal.

If I try `poetry shell` I get the following warning:

```
$ poetry shell
The virtual environment found in /home/pomatti/pjs/azure/azure-multiregion-aks-cluster/microservices/utils/.venv seems to be broken.
```

It appears to be broken. But why didn't it tell me so in the previous command?

Now if I exit and try again, then it shows what it seems to be the root cause:

```
$ exit
exit
pomatti@DESKTOP-DP18TG3:~/pjs/azure/azure-multiregion-aks-cluster/microservices/utils$ poetry shell
The virtual environment found in /home/pomatti/pjs/azure/azure-multiregion-aks-cluster/microservices/utils/.venv seems to be broken.
Recreating virtualenv aksmr-utils in /home/pomatti/pjs/azure/azure-multiregion-aks-cluster/microservices/utils/.venv
Spawning shell within /home/pomatti/pjs/azure/azure-multiregion-aks-cluster/microservices/utils/.venv
pomatti@DESKTOP-DP18TG3:~/pjs/azure/azure-multiregion-aks-cluster/microservices/utils$ . /home/pomatti/pjs/azure/azure-multiregion-aks-cluster/microservices/utils/.venv/bin/activate
bash: /home/pomatti/pjs/azure/azure-multiregion-aks-cluster/microservices/utils/.venv/bin/activate: No such file or directory
```

It is trying to to call `.venv/bin/activate` which doesn't exist, because it has been created as `.venv/local/bin/activate`. Why?

Now to add to this whole thing, even if I manually activate it with `source .venv/local/bin/activate`, VS Code is not recognizing the environment, and I also can't add new packages.

```
$ poetry add azure.identity
The virtual environment found in /home/pomatti/pjs/azure/azure-multiregion-aks-cluster/microservices/utils/.venv seems to be broken.
Recreating virtualenv aksmr-utils in /home/pomatti/pjs/azure/azure-multiregion-aks-cluster/microservices/utils/.venv

  FileNotFoundError

  [Errno 2] No such file or directory: '/home/pomatti/pjs/azure/azure-multiregion-aks-cluster/microservices/utils/.venv/local/bin/python3'

  at ~/.poetry/lib/poetry/_vendor/py3.10/virtualenv/discovery/builtin.py:91 in propose_interpreters
       87│ 
       88│     # 1. if it's a path and exists
       89│     if spec.path is not None:
       90│         try:
    →  91│             os.lstat(spec.path)  # Windows Store Python does not work with os.path.exists, but does for os.lstat
       92│         except OSError:
       93│             if spec.is_abs:
       94│                 raise
       95│         else:
```

What is going on?

**Comment by abn** [comment]
@epomatti can you try manually creating a virtual env and see what you get?

```sh
# if you are using a specific python binary, use that instead 
python -m pip install virtualenv
python -m virtualenv venv-test
```

And maybe also post the output of `python -m site`.


It is likely that sys.prefix is incorrectly used when creating the venv.

**Comment by epomatti** [comment]
@abn I got this

![image](https://user-images.githubusercontent.com/6530769/170524550-6b6a69a4-7367-4c9e-9b4f-1a789f865941.png)

And the site:

```
$ python3 -m site
sys.path = [
    '/home/pomatti/pjs/azure/azure-multiregion-aks-cluster/microservices/utils',
    '/usr/lib/python310.zip',
    '/usr/lib/python3.10',
    '/usr/lib/python3.10/lib-dynload',
    '/home/pomatti/.local/lib/python3.10/site-packages',
    '/usr/local/lib/python3.10/dist-packages',
    '/usr/lib/python3/dist-packages',
]
USER_BASE: '/home/pomatti/.local' (exists)
USER_SITE: '/home/pomatti/.local/lib/python3.10/site-packages' (exists)
ENABLE_USER_SITE: True
```

**Comment by abn** [comment]
@epomatti from what I can tell, the issue is most likely with `virtualenv`. Poetry simply uses `virtualenv` to create a new environment (similar to what you did to create the environment manualy).

**Comment by epomatti** [comment]
@abn I'll keep reading venv docs. In the meanwhile I opened an SO and will report here if I find it. Loos like we can close it.

https://stackoverflow.com/q/65390129/3231778

**Comment by epomatti** [comment]
This creates the subdirectories accordingly. Will try to figure out why.
```
python3 -m venv .venv
```

**Comment by epomatti** [comment]
I ended up re-creating my Ubuntu installation it works normally now.

**Comment by abn** [comment]
Odd. Thanks for closing the loop @epomatti .

**Comment by epomatti** [comment]
@abn here is the explanation: https://github.com/pypa/setuptools/issues/3278

Case closed.

**Comment by abn** [comment]
Thanks for closing the loop @epomatti. Much appreciated. 💜
