### ISSUE TITLE
Poetry doesn't recognize setuptools based project if it has no setup.py (only setup.cfg)

### ISSUE THREAD

**Issue by fmagin** [python-poetry/poetry#5692]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Arch Linux
- **Poetry version**: `1.2.0b1`
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://github.com/angr/angr-dev/blob/28531802747918c5610e3e5f239d98eb9015afd4/pyproject.toml

## Issue

the angr project has various subprojects that only have a `setup.cfg` file and no `setup.py` file. This results in poetry throwing an exception when trying to use them as a local path package: i.e. `Directory /home/fmagin/Projects/angr-dev/archinfo does not seem to be a Python package`. in `poetry/core/packages/directory_dependency.py:54`. Specifically this happens because the check only checks if a `setup.py` exists or if the `pyproject.toml` has `tool.poetry` keys. Both aren't true for the angr subprojects. If I edit the poetry source code and add a check for the existence of `setup.cfg` file then poetry works as expected (and like if I had specified the dependency as a pinned git commit from GitHub directly), so I am considering this a bug

**Comment by abn** [comment]
@fmagin can you try the fix at https://github.com/python-poetry/poetry-core/pull/368#issue-1246356001 please?

**Comment by fmagin** [comment]
@abn yep that fix works! I searched the previous issues for `setup.cfg` and didn't find any, so I didn't realize there was such a recent issue/PR for this already
