### ISSUE TITLE
Quick intro shall include `poetry init` or `poetry new`

### ISSUE THREAD

**Issue by vlcinsky** [python-poetry/poetry#570]
## Issue
Current animated screen play looks nice.

However, experienced python programmer is likely to start experiments quickly as follows:
- see nice animated screenplay, deciding to test it (without diving into documentation yet)
- create new empty directory for experiments and cd into it
- install poetry (e.g. using `pip install --user poetry`)
- try to do what is shown in the screenplay, thus `$ poetry add pendulum`
- and the frustration comes as it complains about missing `pyproject.toml` and not hinting what to do.

Proposal:
Add just following line before using initial `poetry add pendulum`:

```
$ # ensure existence of pyproject.toml by `poetry init` or `poetry new`
$ poetry init -n

This command will guide you through creating your pyproject.toml config.

$ poetry add pendulum
``` 
and continue as today.

This small change can save some initial frustration to newcomers.

**Comment by vlcinsky** [comment]
Hi stale[bot]. Thanks for your kick to an activity.

Here is my initial take on updating screenplay on poetry.

Scenario:
- find .
- poetry new demo
- cd demo
- ^L-----
- find .
- poetry install
- poetry add pendulum
- ^L-----
- poetry show
- poetry show --tree
- (wait)
- poetry remove pendulum
- cd ..
- find .
- (wait)

![poetry5](https://user-images.githubusercontent.com/635911/68816053-8e854a00-067d-11ea-9e6a-8c58264c2f3a.gif)

Any comments?

My current ideas are:
- Visual stuff:
  - remove the `javl@T810` prompt
  - consider using the shell originally used by @sdispater (is that zsh?)
  - consider using the same theme (any advice?)
- Scenario
  - currently no idea, adding more features would make it too long

**Comment by Secrus** [comment]
This is covered in documentation: https://python-poetry.org/docs/basic-usage/
