### ISSUE TITLE
poetry lock does not specify correct dependency groups

### ISSUE THREAD

**Issue by aljabadi** [python-poetry/poetry#5702]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS Monterey 12.3.1
- **Poetry version**: 1.2.0b1
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/aljabadi/18d2abc464c4b54b2c96fbdb097d5acc

## Issue

Trying to add new dependencies using `poetry add <dep>`, the dependencies are added as `category = "main"` in the lock file. While `poetry lock` re-assigns the dependency to `category = "dev"`. In fact, when running `poetry lock`, all dependencies in the lock file use `category = "dev"`. Nevertheless, Installation behaves as it should, that is `poetry install --no-root` will in fact install only the main dependencies and `poetry install --no-root --with dev` will also include the dev dependencies as specified in `pyrpoject.toml`. However, I find the lock file's behaviour confusing.

**Comment by abn** [comment]
The lockfile's categories are not related to dependency groups. These are legacy properties that are no longer used in Poetry and will be removed in a future release. As far as lockfiles are considred, the `main` and `dev` categories originally existed to filter out dependencies based on the pre `1.2.0` distinction of dependencies, which was largely binary.

The "group" information today only exists within the `pyproject.toml`. A future release might include this in the lockfile. However, as it stands today this is not the case.

Additionally, please note that behaviour of groups were inaccurate in `<=1.2.0b1`. This has now been resolved and will be available in future pre-release of `1.2.0`.
