### ISSUE TITLE
poetry update failed

### ISSUE THREAD

**Issue by shelper** [python-poetry/poetry#5706]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: ubuntu 18.04, python 3.8.13,
- **Poetry version**: 1.2.0b1 (also tried 1.2.0a1)
- **Link of a Gist with the contents of your pyproject.toml file**: [pyproject.toml](https://gist.github.com/shelper/a9ce70b434287808cab47d0aaa878723)

## Issue

when have tensorflow included in a group called `ml`, poetry takes forever to update, along comes with repeated message of:

`<debug>PackageInfo:</debug> Invalid constraint (tinycss2 (>=1.1.0<1.2) ; extra == 'css') found in bleach-5.0.0 dependencies, skipping`

tried to save the log by
` poetry update -vvv  | tee ./poetry_update.log`
but that gives endless log that never stops outputting. 

**UPDATE**
Now if I comment out the line 40 of `pyproject.toml` for tensorflow, then i was able to finish the update, although still have the message (but only a few) of `<debug>PackageInfo:</debug> Invalid constraint (tinycss2 (>=1.1.0<1.2) ; extra == 'css') found in bleach-5.0.0 dependencies, skipping`
This `poetry_update.log` file was uploaded to Gist at [here](https://gist.github.com/shelper/eb2206a9df90a53e09c08c7be98f9bdc)

after i finished updating by commenting out the tensorflow line, i uncomment it and run poetry update again, still poetry stuck. for ever, I also tried to fix the version range for tinycss2, that removes the <debug> message but does not solve the stuck update

**Comment by dimbleby** [comment]
Well that is an invalid constraint!  Looks like bleach has fixed it - https://github.com/mozilla/bleach/pull/655 - but not yet published that.

(Could consider raising an issue against pypi, it would be nice of folk were prevented from publishing invalid metadata)

**Comment by shelper** [comment]
@dimbleby  thanks for that info, this is useful and resolves that specific message
but i dont think that causes poetry failed to update, 
see my post update above. 

It is the tensorflow that puts poetry into something like infinite loop...

**Comment by shelper** [comment]
well, i dident put author to the shared toml file 'cus privacy, my local toml file has author section and still does not work....

I have more to report here, and i suspect this is what happened.
I logged update log again, and found  poetry keep outputing messages for tensorflow repeatedly, and the repeated message is something like this:
```
conflict: tensorflow (2.5.0) depends on numpy (>=1.19.2,<1.20.0)
   1: fact: tensorflow (2.5.0) depends on numpy (>=1.19.2,<1.20.0)
   1: fact: tensorflow (2.5.0) depends on absl-py (>=0.10,<1.0)
   1: fact: tensorflow (2.5.0) depends on astunparse (>=1.6.3,<1.7.0)
   1: fact: tensorflow (2.5.0) depends on flatbuffers (>=1.12.0,<1.13.0)
   1: fact: tensorflow (2.5.0) depends on google-pasta (>=0.2,<1.0)
   1: fact: tensorflow (2.5.0) depends on h5py (>=3.1.0,<3.2.0)
   1: fact: tensorflow (2.5.0) depends on keras-preprocessing (>=1.1.2,<1.2.0)
   1: fact: tensorflow (2.5.0) depends on opt-einsum (>=3.3.0,<3.4.0)
   1: fact: tensorflow (2.5.0) depends on protobuf (>=3.9.2)
   1: fact: tensorflow (2.5.0) depends on six (>=1.15.0,<1.16.0)
   1: fact: tensorflow (2.5.0) depends on termcolor (>=1.1.0,<1.2.0)
   1: fact: tensorflow (2.5.0) depends on typing-extensions (>=3.7.4,<3.8.0)
   1: fact: tensorflow (2.5.0) depends on wheel (>=0.35,<1.0)
   1: fact: tensorflow (2.5.0) depends on wrapt (>=1.12.1,<1.13.0)
   1: fact: tensorflow (2.5.0) depends on gast (0.4.0)
   1: fact: tensorflow (2.5.0) depends on tensorboard (>=2.5,<3.0)
   1: fact: tensorflow (2.5.0) depends on tensorflow-estimator (>=2.5.0rc0,<2.6.0)
   1: fact: tensorflow (2.5.0) depends on keras-nightly (>=2.5.0.dev,<2.6.0)
   1: fact: tensorflow (2.5.0) depends on grpcio (>=1.34.0,<1.35.0)
   2: selecting tensorflow (2.5.0)
   2: derived: tensorflow-estimator (>=2.5.0rc0,<2.6.0)
   1: fact: zetta depends on tensorflow (2.5.0)
   1: derived: tensorflow (==2.5.0)
   1: fact: tensorflow (2.5.0) depends on numpy (>=1.19.2,<1.20.0)
   1: fact: tensorflow (2.5.0) depends on absl-py (>=0.10,<1.0)
   1: fact: tensorflow (2.5.0) depends on astunparse (>=1.6.3,<1.7.0)
   1: fact: tensorflow (2.5.0) depends on flatbuffers (>=1.12.0,<1.13.0)
   1: fact: tensorflow (2.5.0) depends on google-pasta (>=0.2,<1.0)
   1: fact: tensorflow (2.5.0) depends on h5py (>=3.1.0,<3.2.0)
   1: fact: tensorflow (2.5.0) depends on keras-preprocessing (>=1.1.2,<1.2.0)
   1: fact: tensorflow (2.5.0) depends on opt-einsum (>=3.3.0,<3.4.0)
   1: fact: tensorflow (2.5.0) depends on protobuf (>=3.9.2)
   1: fact: tensorflow (2.5.0) depends on six (>=1.15.0,<1.16.0)
   1: fact: tensorflow (2.5.0) depends on termcolor (>=1.1.0,<1.2.0)
   1: fact: tensorflow (2.5.0) depends on typing-extensions (>=3.7.4,<3.8.0)
   1: fact: tensorflow (2.5.0) depends on wheel (>=0.35,<1.0)
   1: fact: tensorflow (2.5.0) depends on wrapt (>=1.12.1,<1.13.0)
   1: fact: tensorflow (2.5.0) depends on gast (0.4.0)
   1: fact: tensorflow (2.5.0) depends on tensorboard (>=2.5,<3.0)
   1: fact: tensorflow (2.5.0) depends on tensorflow-estimator (>=2.5.0rc0,<2.6.0)
   1: fact: tensorflow (2.5.0) depends on keras-nightly (>=2.5.0.dev,<2.6.0)
   1: fact: tensorflow (2.5.0) depends on grpcio (>=1.34.0,<1.35.0)
   1: derived: tensorflow-estimator (>=2.5.0rc0,<2.6.0)
... (repeat above message again)
```

**Comment by dimbleby** [comment]
What I am telling you is that the master branch solves this: ie so far as I can see whatever issue you are hitting is already resolved in the codebase.

**Comment by shelper** [comment]
you are right, Poetry (version 1.2.0b2.dev0) solves this issue, close the ticket, 

thanks!
