### ISSUE TITLE
Is handling of `python_version` correct?

### ISSUE THREAD

**Issue by dimbleby** [python-poetry/poetry#5717]
Currently poetry mostly treats `python_version x.y` as equivalent to `python_full_version x.y.0`, but is it necessarily so?
```python
#!/usr/bin/env python3

from poetry.core.version.markers import parse_marker

m1 = parse_marker('python_version > "3.6"')
m2 = parse_marker('python_full_version == "3.6.2"')
allowed = m1.constraint.allows(m2.constraint)
print(allowed)
```
This prints `True`.  But surely PEP508 says that the `python_version` at 3.6.2 is exactly 3.6, which does not satisfy `m1`.

related https://github.com/python-poetry/poetry/issues/2480.

**Comment by radoering** [comment]
Seems to be wrong. Probably, it is only correct for `>=` and `<`, but fails for `>` and `<=`. In `get_python_constraint_from_marker()`, there is even a special handling for these cases: https://github.com/python-poetry/poetry-core/blob/dfd1b39ffec8bfad027a6dda0c31bab24b4c6019/src/poetry/core/packages/utils/utils.py#L310-L325 I assume that is required in other places, too.

**Comment by dimbleby** [comment]
For a start, we should roll back the marker simplifications that treat these two the same.

That _might_ be enough, if we never compare `python_version` and `python_full_version` directly perhaps we're ok

**Comment by dimbleby** [comment]
https://github.com/python-poetry/poetry-core/blob/63322f630b40a261c26644d4b82324a44b6aafe0/src/poetry/core/packages/utils/utils.py#L162-L165 looks highly suspicious

```python
        # python_full_version is equivalent to python_version
        # for Poetry so we merge them
        if marker_name == "python_full_version":
            marker_name = "python_version"
```

**Comment by dimbleby** [comment]
You've probably seen that I've reverted the naive merging.  No, I don't have plans to implement a smarter version.

**Comment by dimbleby** [comment]
The `marker` setter on a `Dependency` only cares about `python_version`: so if I set the marker `python_full_version >= 3.6` (for example), the dependency's python constraint is `*`.

**Comment by dimbleby** [comment]
Gonna call this done, it has triggered some good fixes, if there are more bugs then they can be tracked as they are found
