### ISSUE TITLE
Poetry solve unnecessary dependency path

### ISSUE THREAD

**Issue by hungbie** [python-poetry/poetry#5731]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: ubuntu 20.04 and MacOS 12.3.1
- **Poetry version**: 1.1.13
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 
example pyproject.toml that can reproduce the behavior:
```
[build-system]
requires = ["poetry-core<=1.0.4"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "package"
version = "0.0.0"
description = "Application"
authors = ['author']

[tool.poetry.dependencies]
python = "3.8.*"
azure-identity = "^1.5"
portalocker = "^1.6"

[tool.poetry.dev-dependencies]
pytest = "*"
pytest-cov = "*"
```

## Issue
`azure-identity` depends on `msal-extension` that in turn depends on `portalocker`.
`msal-extension` has this requirement:
```
"portalocker<3,>=1.0;python_version>='3.5' and platform_system!='Windows'",
"portalocker<3,>=1.6;python_version>='3.5' and platform_system=='Windows'",
``` 
Running in debug mode show that poetry tried to resolve 3 times:
```
 1: Version solving took 0.547 seconds.
   1: Tried 1 solutions.
   0: Retrying dependency resolution with the following overrides ({Package('msal-extensions', '0.3.0'): {'portalocker': <Dependency portalocker (>=1.6,<2.0)>}}).
  ....
 0: Different requirements found for portalocker (>=1.0,<2.0) with markers platform_system != "Windows" and portalocker (>=1.6,<2.0) with markers platform_system == "Windows".
   1: Version solving took 0.085 seconds.
   1: Tried 1 solutions.
   0: Retrying dependency resolution with the following overrides ({Package('msal-extensions', '0.3.0'): {'portalocker': <Dependency portalocker (>=1.0,<2.0)>}}).
   ...
 1: Version solving took 0.232 seconds.
   1: Tried 1 solutions.
   0: Complete version solving took 1.151 seconds with 2 overrides
   0: Resolved with overrides: ({Package('msal-extensions', '0.3.0'): {'portalocker': <Dependency portalocker (>=1.0,<2.0)>}}), ({Package('msal-extensions', '0.3.0'): {'portalocker': <Dependency portalocker (>=1.6,<2.0)>}})
```
In normal situation I understand why it would have this behaviour, but I wonder if there is anyway to optimize it? For example, the OS is definitely not Window, why do we have to try this?
Next, I tried to pin the version of portalocker to >=1.6 so that it would ignore the other condition, but it still tried to resolve for portalocker version >=1.0. 
Would this be a waste of resource? In this toy example it seems ok, but in our current project, each run of the solver cost us 10 minutes, so rerun this 3 times and the poetry lock time is 30 minutes. 
And we have this similar problem with other dependencies (for example pandas and numpy), making the numbers of retry bigger, and hence the lock time becomes hours.

**Comment by hungbie** [comment]
> poetry tries to produce a solution that is valid everywhere, not only in the place where you are running `poetry lock`.
> 
> #4956 contains work in the general direction that you suggest, I think this can be treated as a duplicate of that.

Yes this seems like what we need, especially for big project where we have our own targeted environment and don’t need to produce a solution that valid everywhere! Hope it will be released soon!

**Comment by dimbleby** [comment]
so please close this as a duplicate
