### ISSUE TITLE
http url for a library is not satisfied

### ISSUE THREAD

**Issue by jylind** [python-poetry/poetry#5734]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows 10, Ubuntu 20.04
- **Poetry version**: 1.2.0b1

## Issue
I'm using version 1.2.0b1 which is installed using script install-poetry.py and --preview flag.
I installed it soon after it was release.
Today I reinstalled the same version and after that I could not `poetry install` my project anymore (first noticed this on a container I recreated but same thing started to happen on Windows).

Anyway, after reinstalling poetry started to fail with this error message:
```  RuntimeError

  [BUG] csiclient (0.20.3 url) is not satisfied.

  at ~\AppData\Roaming\pypoetry\venv\lib\site-packages\poetry\mixology\partial_solution.py:204 in satisfier
      200│             # As soon as we have enough assignments to satisfy term, return them.
      201│             if assigned_term.satisfies(term):
      202│                 return assignment
      203│
    → 204│         raise RuntimeError(f"[BUG] {term} is not satisfied.")
      205│
      206│     def satisfies(self, term: Term) -> bool:
      207│         return self.relation(term) == SetRelation.SUBSET
      208│
```
The dependency in the pyproject.toml looks something like this:
```
csicommon = { url = "http://my.server.com/files/csi-python-repo/csicommon-0.20.3-py3-none-any.whl" }
``` 
One thing to note is that between the working installation and failing one the poetry.lock has not changed.

Now how would I get that working version installed?

**Comment by jylind** [comment]
@abn Thank you for you info.

Poetry (install) from github (1.2.0b2.dev0 with poetry-core 1.1.0b2) did work as expected.
Thank you.

**Comment by finswimmer** [comment]
Thanks for coming back and reporting  @jylind. :+1:
