### ISSUE TITLE
Version problem with PyQt6-tools and PyQt5-tools | SolverProblemError

### ISSUE THREAD

**Issue by HappyCthulhu** [python-poetry/poetry#5736]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- Ubuntu 20.04 focal
- Poetry version 1.1.13
- [Gist](https://github.com/HappyCthulhu/braw_to_mov) 

## Issue
Hello. Im trying to install pyqt6 and pyqt6-tools. 

I dont have any problems with pyqt6, but attempt to install poetry6-tools crashed with this error message:

```
Using version ^6.1.0 for pyqt6-tools

Updating dependencies
Resolving dependencies... (0.0s)

  SolverProblemError

  Because no versions of pyqt6-tools match >=6.1.0,<6.1.0.3.2 || >6.1.0.3.2,<7.0.0
   and pyqt6-tools (6.1.0.3.2) depends on pyqt6 (6.1.0), pyqt6-tools (>=6.1.0,<7.0.0) requires pyqt6 (6.1.0).
  So, because braw-to-mov depends on both PyQt6 (^6.3.0) and pyqt6-tools (^6.1.0), version solving failed.

  at ~/.poetry/lib/poetry/puzzle/solver.py:241 in _solve
      237│             packages = result.packages
      238│         except OverrideNeeded as e:
      239│             return self.solve_in_compatibility_mode(e.overrides, use_latest=use_latest)
      240│         except SolveFailure as e:
    → 241│             raise SolverProblemError(e)
      242│
      243│         results = dict(
      244│             depth_first_search(
      245│                 PackageNode(self._package, packages), aggregate_package_nodes

```

I tried to install version PyQt6=6.1.0, tried PyQt5... But PyQt5-tools also doesnt work. Btw, pip doing this work well, i have no issues during pyqt6-tools instalations with pipenv.

Lib *pyqt-plugins* give this error too. 

The problem is reprodusing on all my devices: laptop, pc and server

Why is this happening and how can i solve this problem?

P.S. How can i run debug command? Is it `poetry -vvv add pyqt6-tools`?

**Comment by dimbleby** [comment]
> ... pyqt6-tools (>=6.1.0,<7.0.0) requires pyqt6 (6.1.0) 
>So, because braw-to-mov depends on both PyQt6 (^6.3.0) and pyqt6-tools (^6.1.0), version solving failed.

Seems reasonably clear that you're asking for something impossible?

**Comment by HappyCthulhu** [comment]
I just want to install this lib) 

Commands:
`poetry add pyqt6
poetry add pyqt6-tools
`
What impossible in those commands?

> > ... pyqt6-tools (>=6.1.0,<7.0.0) requires pyqt6 (6.1.0) 
> 
> >So, because braw-to-mov depends on both PyQt6 (^6.3.0) and pyqt6-tools (^6.1.0), version solving failed.
> 
> 
> 
> Seems reasonably clear that you're asking for something impossible?

**Comment by dimbleby** [comment]
Please read and understand the error message.  Your project definition is asking for pyqt (^6.3.0) and pyqt6-tools (^6.1.0) and these are not compatible.

Update your pyproject.toml so that it asks for compatible versions.

**Comment by HappyCthulhu** [comment]
> Please read and understand the error message. Your project definition is asking for pyqt (^6.3.0) and pyqt6-tools (^6.1.0) and these are not compatible.
> 
> Update your pyproject.toml so that it asks for compatible versions.

Pls, try to listen to me a little bit. Problem IS NOT in versions.

U can just run commands:

```
poetry init
poetry shell
poetry add pyqt6-tools

```

And this will return u same error message. Or u can do this:
```
poetry add pyqt6=6.1.0
poetry add pyqt6-tools
```

Or:
```
poetry init
poetry shell
poetry add pyqt6-**plugins**
```

Guess what? That will return same error.
Idk, why is this happening, thats why i created this issue. 

My guess:
Roots of this problem - circular import:
pyqt6-tools [need pyqt6-plugins](https://github.com/altendky/pyqt-tools/blob/2583303f213bcb69f5f16716a2563301481d1530/setup.py#L91)
pyqt6-plugins [need pyqt6-plugins](https://github.com/altendky/pyqt-plugins/blob/8138b740346f475181a94729832a6095e0ac1d24/setup.py#L109)

And poetry cant process this...

If you try to reproduce this issue and it doesn't reproduce, I will pay u hundred dollars. Just pls, try to put in shell command, that i mension in this message.

**Comment by dimbleby** [comment]
> Problem IS NOT in versions.

The only error that you have shown is definitely a version incompatibility.  If you're seeing something else, please say so.

> If you try to reproduce this issue and it doesn't reproduce, I will pay u hundred dollars.

```
poetry add pyqt6-tools
Using version ^6.1.0.3.2 for pyqt6-tools

Updating dependencies
Resolving dependencies... (0.1s)

Writing lock file

Package operations: 9 installs, 0 updates, 0 removals

  • Installing click (7.1.2)
  • Installing pyqt6-qt6 (6.3.0)
  • Installing pyqt6-sip (13.3.1)
  • Installing qt6-applications (6.1.0.2.2)
  • Installing pyqt6 (6.1.0)
  • Installing qt6-tools (6.1.0.1.2)
  • Installing pyqt6-plugins (6.1.0.2.2)
  • Installing python-dotenv (0.20.0)
  • Installing pyqt6-tools (6.1.0.3.2)
```
I am using the master branch of poetry.

**Comment by HappyCthulhu** [comment]
> > Problem IS NOT in versions.
> 
> The only error that you have shown is definitely a version incompatibility. If you're seeing something else, please say so.
> 
> > If you try to reproduce this issue and it doesn't reproduce, I will pay u hundred dollars.
> 
> ```
> poetry add pyqt6-tools
> Using version ^6.1.0.3.2 for pyqt6-tools
> 
> Updating dependencies
> Resolving dependencies... (0.1s)
> 
> Writing lock file
> 
> Package operations: 9 installs, 0 updates, 0 removals
> 
>   • Installing click (7.1.2)
>   • Installing pyqt6-qt6 (6.3.0)
>   • Installing pyqt6-sip (13.3.1)
>   • Installing qt6-applications (6.1.0.2.2)
>   • Installing pyqt6 (6.1.0)
>   • Installing qt6-tools (6.1.0.1.2)
>   • Installing pyqt6-plugins (6.1.0.2.2)
>   • Installing python-dotenv (0.20.0)
>   • Installing pyqt6-tools (6.1.0.3.2)
> ```
> 
> I am using the master branch of poetry.

ok, how can i send u money?

![image](https://user-images.githubusercontent.com/23531195/171675718-3d493e62-8bc4-445f-b0c9-906986cbda04.png)
![image](https://user-images.githubusercontent.com/23531195/171676037-c1fc8ad0-3f67-4416-b895-65abedd5a37e.png)

**Comment by dimbleby** [comment]
That error is not the same error you previously reported.  (Also images are a terrible way of showing text.)

So that one looks like it may be a real bug: but per my experiment it seems to be fixed on master.  If you don't want to use master you could try the latest poetry beta, perhaps that has the fix or perhaps it doesn't, I don't know.

Anyway: this seems to be fixed on the latest code, so there's nothing more to do on the poetry side.  Please keep your money, and close this out.

**Comment by HappyCthulhu** [comment]
I installed master-version of poetry with `curl -sSL https://install.python-poetry.org | python3 -`

Then installed pyqt5 with `poetry add pyqt5=5.15.4
Then i tried to install pyqt5-tools:
```
> poetry add pyqt5-tools
Using version ^5.15.4 for pyqt5-tools

Updating dependencies
Resolving dependencies... (0.0s)

  SolverProblemError

  Because pyqt5-tools (5.15.4.3.0.3) depends on both pyqt5-plugins (<empty>) and pyqt5-plugins (<empty>), pyqt5-tools is forbidden.
  And because no versions of pyqt5-tools match >=5.15.4,<5.15.4.3.0.3 || >5.15.4.3.0.3,<5.15.4.3.1 || >5.15.4.3.1,<5.15.4.3.2 || >5.15.4.3.2,<6.0.0, pyqt5-tools is forbidden.
  Because pyqt5-tools (5.15.4.3.1) depends on both pyqt5-plugins (<empty>) and pyqt5-plugins (<empty>), pyqt5-tools is forbidden.
  Thus, pyqt5-tools is forbidden.
  Because pyqt5-tools (5.15.4.3.2) depends on both pyqt5-plugins (<empty>) and pyqt5-plugins (<empty>), pyqt5-tools is forbidden.
  Thus, pyqt5-tools is forbidden.
  So, because test-poetry depends on pyqt5-tools (^5.15.4), version solving failed.

  at ~/.local/share/pypoetry/venv/lib/python3.8/site-packages/poetry/puzzle/solver.py:241 in _solve
      237│             packages = result.packages
      238│         except OverrideNeeded as e:
      239│             return self.solve_in_compatibility_mode(e.overrides, use_latest=use_latest)
      240│         except SolveFailure as e:
    → 241│             raise SolverProblemError(e)
      242│
      243│         results = dict(
      244│             depth_first_search(
      245│                 PackageNode(self._package, packages), aggregate_package_nodes

```

What else should i do to finally solve this issue?

P.S. I installed pyqt5=5.15.4, because when i installed latest version of pyqt5, poetry told me:

```
> poetry add pyqt5-tools
Using version ^5.15.4 for pyqt5-tools

Updating dependencies
Resolving dependencies... (0.0s)

  SolverProblemError

  Because no versions of pyqt5-tools match >=5.15.4,<5.15.4.3.0.3 || >5.15.4.3.0.3,<5.15.4.3.1 || >5.15.4.3.1,<5.15.4.3.2 || >5.15.4.3.2,<6.0.0
   and pyqt5-tools (5.15.4.3.0.3) depends on pyqt5 (5.15.4), pyqt5-tools (>=5.15.4,<5.15.4.3.1 || >5.15.4.3.1,<5.15.4.3.2 || >5.15.4.3.2,<6.0.0) requires pyqt5 (5.15.4).
  And because pyqt5-tools (5.15.4.3.1) depends on pyqt5 (5.15.4)
   and pyqt5-tools (5.15.4.3.2) depends on pyqt5 (5.15.4), pyqt5-tools (>=5.15.4,<6.0.0) requires pyqt5 (5.15.4).
  So, because test-poetry depends on both PyQt5 (^5.15.6) and pyqt5-tools (^5.15.4), version solving failed.

  at ~/.local/share/pypoetry/venv/lib/python3.8/site-packages/poetry/puzzle/solver.py:241 in _solve
      237│             packages = result.packages
      238│         except OverrideNeeded as e:
      239│             return self.solve_in_compatibility_mode(e.overrides, use_latest=use_latest)
      240│         except SolveFailure as e:
    → 241│             raise SolverProblemError(e)
      242│
      243│         results = dict(
      244│             depth_first_search(
      245│                 PackageNode(self._package, packages), aggregate_package_nodes

```

**Comment by dimbleby** [comment]
> I installed master-version of poetry with curl -sSL https://install.python-poetry.org | python3 -

this does not install the master version of poetry

**Comment by mkniewallner** [comment]
You can use either:
```shell
# Install latest git master version of Poetry
curl -sSL https://install.python-poetry.org/ | python3 - --git https://github.com/python-poetry/poetry.git@master

# Install latest 1.2 beta of Poetry
curl -sSL https://install.python-poetry.org/ | python3 - --preview
```
then retry to see if this does fix the issue.

**Comment by HappyCthulhu** [comment]
That finally worked. Pls, last question, i just want to understand the logic:
Why command curl `-sSL https://install.python-poetry.org | python3 -` doesnt install master version?

![image](https://user-images.githubusercontent.com/23531195/175249168-bb484d0d-e54c-4502-a5b0-fc0f18ec7fec.png)

**Comment by Secrus** [comment]
Because the version on master is still formally "pre-release". The script installs the latest stable release unless you add the `--preview` argument (mentioned in step 2 of installation).

**Comment by mkniewallner** [comment]
Closing, since the reported issue was resolved.
