### ISSUE TITLE
Fail to install any package when env var PYTHONWARNINGS set to "ignore,default:::__main__" (solution provided)

### ISSUE THREAD

**Issue by ksamuel** [python-poetry/poetry#5737]
- [ x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [ x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS**: Ubuntu 20.04 
- **Poetry**: 1.1.13 
- **pyproject.toml**:  https://gist.github.com/ksamuel/830d3c5b5811e478f3eb2006b4db748d

## Issue

When setting the env var `PYTHONWARNINGS` to `ignore,default:::__main__`, running `poetry add` for any package, we get:

```  JSONDecodeError: Expecting value: line 1 column 1 (char 0)```

I'm assuming issue `https://github.com/python-poetry/poetry/issues/654` is related, although it's difficult to know for sure.

But in this particular case, it is because in "utils/env.py(1424)get_supported_tags()", poetry calls `run_python_script` which in turn does `self.run(self._executable, "-W", "ignore", "-", input_=content, **kwargs)` which ultimately make a subproces call to an external python script and reads the output.

Unfortunately, "-W ignore" doesn't seem to be sufficient to override the `ignore,default:::__main__`, and the output ends up containing a warning. E.G:

```
<stdin>:7: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
[["cp310", "cp310", "manylinux_2_31_x86_64"], ["cp310", "cp310", "manylinux_2_30_x86_64"], ["cp310", "cp310", "manylinux_2_29_x86_64"], ["cp310", "cp310", "manylinux_2_28_x86_64"], ["cp310", "cp310", 
```

This is, of course, not valid json, and fails to be parsed later by poetry.

To fix this, we can force the environment variable value that will be eventually used in the subprocess call:

```python
    def run_python_script(self, content, **kwargs):  # type: (str, Any) -> str

        env = kwargs.get("env", {})
        env["PYTHONWARNINGS"] = "ignore"
        kwargs["env"] = env

        return self.run(self._executable, "-W", "ignore", "-", input_=content, **kwargs)
```

For people needing a workaround, make all your poetry calls with warnings disabled. E.G for unix:

```bash
PYTHONWARNING="ignore" poetry ...
```

**Comment by finswimmer** [comment]
Hello @ksamuel,

you haven't come back to this issue for a long while. So I assume this is solved in the meantime and I can close this ticket.

Feel free to leave a comment if you disagree.

fin swimmer
