### ISSUE TITLE
Unable to import package with a name different from the project name

### ISSUE THREAD

**Issue by fabiobatalha** [python-poetry/poetry#5744]
I'm moving a library to use poetry. This library has a name that is different from the main package. It works well with setuptools and the function : packages=find_packages().

With poetry I have the following configuration:

![Screenshot from 2022-06-01 08-55-07](https://user-images.githubusercontent.com/504142/171409629-fcd3a45f-bea5-40b4-b93c-b6eae7ff0892.png)

But the package crossref is still not available for import.

I don't know what could be wrong.

**Comment by GenosW** [comment]
Hey, I think what you want to use is:

`packages = [{ from = "src", include = "crossref" }]`

**Comment by fabiobatalha** [comment]
Hi @GenosW 

Even with this configuration, it still not works, but now with a different error.

![Screenshot from 2022-06-01 10-12-14](https://user-images.githubusercontent.com/504142/171425542-c764dbcd-2a19-4e3d-9b99-f377bba5902c.png)

**Comment by GenosW** [comment]
What are you trying to do? Which command are you invoking? --> There is some context missing to effectively help you.

Did `poetry install` work and are you able to import your package now in that env?

Note: I'm not a poetry developer, just an avid user.

**Comment by abn** [comment]
@fabiobatalha recreate your virtualenv. `rm -rf .venv; poetry install`.

**Comment by finswimmer** [comment]
> VERSION = pkg_resources.get_distribution("crossref").version

Your distribution is still `crossrefapi`, even if it contains a package `crossref`. That's one of the reasons, why the distribution name shouldn't differ from the actual package name.

**Comment by fabiobatalha** [comment]
thanks @abn and @GenosW it works with importlib.metadata.
