### ISSUE TITLE
poetry 1.2.0b1 fails to install some packages only when plugins are installed.

### ISSUE THREAD

**Issue by danielknell** [python-poetry/poetry#5747]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: debian bullseye docker container
- **Poetry version**: 1.2.0b1
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue

when plugins are enabled some installs seem to fail

the error is `ImportError: attempted relative import with no known parent package` and the releveant code seems to be `from . import _manylinux, _musllinux` i am not sure where the code comes from though?

you can recreate by running:

```
curl -sSL https://install.python-poetry.org | python3 - --preview
poetry plugin add poetry-workspaces
poetry init -q
poetry -vvv add aiofiles
```

full log: https://gist.github.com/danielknell/3cc0e8a9af799efacc1d061eb2151b18

if you disable the plugins then things work fine.

```
poetry -vvv add aiofiles --no-plugins
```
<details>
  <summary>full log</summary>

```
Loading configuration file /home/vscode/.config/pypoetry/config.toml
Using virtualenv: /home/vscode/.cache/pypoetry/virtualenvs/xxx-76ftnvza-py3.10
PyPI: 163 packages found for aiohttp *
Using version ^3.8.1 for aiohttp

Updating dependencies
Resolving dependencies...
   1: fact: xxx is 0.1.0
   1: derived: xxx
   1: fact: xxx depends on aiohttp (^3.8.1)
   1: selecting xxx (0.1.0)
   1: derived: aiohttp (>=3.8.1,<4.0.0)
PyPI: 1 packages found for aiohttp >=3.8.1,<4.0.0
   1: fact: aiohttp (3.8.1) depends on attrs (>=17.3.0)
   1: fact: aiohttp (3.8.1) depends on charset-normalizer (>=2.0,<3.0)
   1: fact: aiohttp (3.8.1) depends on multidict (>=4.5,<7.0)
   1: fact: aiohttp (3.8.1) depends on async-timeout (>=4.0.0a3,<5.0)
   1: fact: aiohttp (3.8.1) depends on yarl (>=1.0,<2.0)
   1: fact: aiohttp (3.8.1) depends on frozenlist (>=1.1.1)
   1: fact: aiohttp (3.8.1) depends on aiosignal (>=1.1.2)
   1: selecting aiohttp (3.8.1)
   1: derived: aiosignal (>=1.1.2)
   1: derived: frozenlist (>=1.1.1)
   1: derived: yarl (>=1.0,<2.0)
   1: derived: async-timeout (>=4.0.0a3,<5.0)
   1: derived: multidict (>=4.5,<7.0)
   1: derived: charset-normalizer (>=2.0,<3.0)
   1: derived: attrs (>=17.3.0)
   1: fact: aiosignal (1.2.0) depends on frozenlist (>=1.1.0)
   1: selecting aiosignal (1.2.0)
   1: selecting frozenlist (1.3.0)
   1: fact: yarl (1.7.2) depends on multidict (>=4.0)
   1: fact: yarl (1.7.2) depends on idna (>=2.0)
   1: selecting yarl (1.7.2)
   1: derived: idna (>=2.0)
   1: selecting async-timeout (4.0.2)
   1: selecting multidict (6.0.2)
   1: selecting charset-normalizer (2.0.12)
   1: selecting attrs (21.4.0)
   1: selecting idna (3.3)
   1: Version solving took 0.027 seconds.
   1: Tried 1 solutions.

Finding the necessary packages for the current system

Package operations: 9 installs, 0 updates, 0 removals

  • Installing frozenlist (1.3.0): Pending...
  • Installing frozenlist (1.3.0): Downloading... 100%
  • Installing frozenlist (1.3.0): Installing...
  • Installing frozenlist (1.3.0)
  • Installing idna (3.3): Pending...
  • Installing idna (3.3): Downloading... 100%
  • Installing idna (3.3): Installing...
  • Installing idna (3.3)
  • Installing multidict (6.0.2): Pending...
  • Installing multidict (6.0.2): Downloading... 100%
  • Installing multidict (6.0.2): Installing...
  • Installing multidict (6.0.2)
  • Installing aiosignal (1.2.0): Pending...
  • Installing aiosignal (1.2.0): Downloading... 100%
  • Installing aiosignal (1.2.0): Installing...
  • Installing aiosignal (1.2.0)
  • Installing async-timeout (4.0.2): Pending...
  • Installing async-timeout (4.0.2): Downloading... 100%
  • Installing async-timeout (4.0.2): Installing...
  • Installing async-timeout (4.0.2)
  • Installing attrs (21.4.0): Pending...
  • Installing attrs (21.4.0): Downloading... 100%
  • Installing attrs (21.4.0): Installing...
  • Installing attrs (21.4.0)
  • Installing charset-normalizer (2.0.12): Pending...
  • Installing charset-normalizer (2.0.12): Downloading... 100%
  • Installing charset-normalizer (2.0.12): Installing...
  • Installing charset-normalizer (2.0.12)
  • Installing yarl (1.7.2): Pending...
  • Installing yarl (1.7.2): Downloading... 100%
  • Installing yarl (1.7.2): Installing...
  • Installing yarl (1.7.2)
  • Installing aiohttp (3.8.1): Pending...
  • Installing aiohttp (3.8.1): Downloading... 100%
  • Installing aiohttp (3.8.1): Installing...
  • Installing aiohttp (3.8.1)
```
</details>

**Comment by Maciej-Zwolinski** [comment]
Same happens to `poethepoet[poetry_plugin]` if installed via `poetry plugin add` but not if it's added to and run directly from `venv`. Curiously `poetry plugin add poetry-dotenv-plugin` works like a charm.

**Comment by nat-n** [comment]
I also encountered this issue when trying to install poethepoet with poetry 1.2.01b.

I managed to deduce that the error originates from here: https://github.com/python-poetry/poetry/blob/53e50d95d771adb2066e1068f03956fbb5954b26/src/poetry/utils/env.py#L1466-L1473

when it tries to execute the script from `poetry/core/_vendor/packaging/tags.py` by piping it into a python interpreter. Since that script [contains a relative import](https://github.com/python-poetry/poetry-core/blob/main/src/poetry/core/_vendor/packaging/tags.py#L23), I don't understand how this code path would ever work as it is.


> @danielknell i suspect the issue is the plugin downgrades packaging version in the poetry system envrionment causing the sys tags command to fail on your system.
> 
> Consider using the latest version from git, should work as long as the plugin does not modify poetry's dependencies. If you want to find out what changed you could also run `python -m pip freeze` before and after plugin installation from within Poetry's installed environment.

@abn I'm not sure understand how that could happen. Poethepoet is [not very picky about dependencies](https://github.com/nat-n/poethepoet/blob/main/pyproject.toml#L11-L15). Do you think there's anything that could be done on the plugin side to avoid this?

**Comment by Secrus** [comment]
@nat-n could you try with the version from the `master` branch? plugin handling was refactored recently, maybe it's already fixed.

**Comment by nat-n** [comment]
@Secrus Yep, seems to be fixed on master, thanks 👍

**Comment by danielknell** [comment]
I have had no problems since updating to 1.2.0b2 so closing this.
