### ISSUE TITLE
Confusing error reporting for faulty git dependencies

### ISSUE THREAD

**Issue by harahu** [python-poetry/poetry#5761]
- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 21.10
- **Poetry version**: 1.1.13

## Issue
I tried to add `pendulum` as a git dependency, but I am pointing to a rev where `pendulum`s `pyproject.toml` file is in an invalid state:
```toml
[tool.poetry.dependencies]
pendulum = {git = "https://github.com/sdispater/pendulum.git", rev = "7e3880abbc51387f75644754f6f437dc515ed7e3"}
```

Running `poetry update` then leads to the following error:

```
Updating dependencies
Resolving dependencies... (1.3s)

  RuntimeError

  The Poetry configuration is invalid:
    - Additional properties are not allowed ('group' was unexpected)
  

  at ~/.poetry/lib/poetry/_vendor/py3.8/poetry/core/factory.py:43 in create_poetry
       39│             message = ""
       40│             for error in check_result["errors"]:
       41│                 message += "  - {}\n".format(error)
       42│ 
    →  43│             raise RuntimeError("The Poetry configuration is invalid:\n" + message)
       44│ 
       45│         # Load package
       46│         name = local_config["name"]
       47│         version = local_config["version"]

```

Upon seeing this error, my initial reaction was to assume that I had messed up _my own_ poetry configuration, but this isn't the case. This error originates from the `pendulum` resolution process.

From a user perspective, it would be helpful if I was told this in the error message, so that I know where to look for issues. I think it could suffice to just prepend the error message above with:
```
Error when resolving dependency `pendulum`:
```

**Comment by harahu** [comment]
This one might be closable now? Haven't checked.

**Comment by neersighted** [comment]
The specific error is resolved.
