### ISSUE TITLE
freshly installed 1.1.13, poetry self show -> Too many arguments.

### ISSUE THREAD

**Issue by wenhoujx** [python-poetry/poetry#5774]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: mac monterey, M1 
- **Poetry version**: 1.1.13
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: see below inline 

## Issue

i installed poetry with the recommended way. poetry new works, but poetry self show and self add <plugin> doesn't 
```
$ poetry --version 
Poetry version 1.1.13
$ poetry self show    
Too many arguments.
$ poetry self show -vvv     
Too many arguments.
$ poetry self add poetry-multiproject-plugin
Too many arguments.
$ poetry self add -vvv poetry-multiproject-plugin
Too many arguments.
```

**Comment by finswimmer** [comment]
Hello @wenhoujx,

these commands are only available in the master branch and not yet released. They will be included in the next beta release.

fin swimmer
