### ISSUE TITLE
Initial `pytest tests/` ModuleNotFoundError httpretty in local MacOS dev env

### ISSUE THREAD

**Issue by cnpryer** [python-poetry/poetry#5777]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS Montery 12.4
- **Poetry version**: 1.1.13
- **Python version**: 3.10.4

## Issue

Submitting this issue for visibility in-case this isn't a user error and is unexpected.

After forking the repo and running `poetry install` I get `ModuleNotFoundError` for `httpretty` after running `poetry run pytest tests/`.

```
The virtual environment found in /Users/chris/github/poetry/.venv seems to be broken.
Recreating virtualenv poetry-siMYI5IH-py3.10 in .venv/poetry-siMYI5IH-py3.10
ImportError while loading conftest '/Users/chris/github/poetry/tests/conftest.py'.
tests/conftest.py:16: in <module>
    import httpretty
E   ModuleNotFoundError: No module named 'httpretty'
```

## Other

What's been done so far:
- [x] attempt with 3.10.3
- [x] updated to 3.10.4 using `pyenv`
- [x] recreated `.venv` 
- [x] try fresh `pyenv` install (removed Python)
- [x] try [another version of poetry](https://github.com/python-poetry/poetry/blob/master/CONTRIBUTING.md#multiple-versions)
  - [1.2.0b1](https://github.com/python-poetry/poetry/releases/tag/1.2.0b1)
  - [1.1.11](https://github.com/python-poetry/poetry/releases/tag/1.2.0b1)

### Additional context

New to mac. Historically a windows user.

**Comment by clintonroy** [comment]
The first line suggests that the virtual environment isn't in a healthy state, scrub it and try again. The configuration to look for a local virtual environment is probably causing issues after the in place .venv is found to be iffy.

**Comment by cnpryer** [comment]
hmm do you mean 

>  - [x] recreated .venv

**Comment by clintonroy** [comment]
The virtual environment found in /Users/chris/github/poetry/.venv seems to be broken.

Which means poetry couldn't find .venv/bin/python (from memory), so it makes a new virtual environment, in which nothing is installed, hence the poetry run fails.

Blow the .venv away, (rm -r .venv) blow the newly created virtual environment away (poetry env list; poetry env remove ...)

Anytime a virtual environment breaks, that's the point to stop, wipe the slate clean, and try again.

**Comment by cnpryer** [comment]
yea I'm thinking it's something wonky about the virtualenvs config. Updating to to point at `venv` instead works. I could try the remove method you mentioned next.

**Comment by cnpryer** [comment]
```
The virtual environment found in /Users/chrispryer/github/poetry/.venv seems to be broken.
```
But `.venv/poetry-siMYI5IH-py3.10` is what's used.

**Comment by cnpryer** [comment]
🟥 `rm -rf .venv && poetry env remove poetry-siMYI5IH-py3.10`
✅ `poetry config virtualenvs.path "venv"`

so far

**Comment by ralbertazzi** [comment]
Closing as that seems fixed. I also didn't experience these issues on Mac.
