### ISSUE TITLE
Poetry skips virtualenv creation, even though explicitly configured to do so

### ISSUE THREAD

**Issue by MitchK** [python-poetry/poetry#5785]
- [ ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Debian Linux 11
- **Poetry version**: 1.1.13 (latest)
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/MitchK/17ecf71b3784921ccea086fce30cf241

## Issue

Poetry skips virtualenv creation, even though explicitly configured to do so.

```
$ poetry --version
Poetry version 1.1.13
$ cat /etc/os-release || false
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
$ uname -r || false
5.4.149-73.2[59](<truncated>).amzn2.x86_[64](<truncated>)
$ poetry config virtualenvs.create true
$ poetry config virtualenvs.in-project true
$ poetry config virtualenvs.create true --local
$ poetry config virtualenvs.in-project true --local
$ poetry config --list
cache-dir = "/root/.cache/pypoetry"
experimental.new-installer = true
installer.parallel = true
virtualenvs.create = false
virtualenvs.in-project = true
virtualenvs.path = "{cache-dir}/virtualenvs"  # /root/.cache/pypoetry/virtualenvs
$ poetry install -vvv
Skipping virtualenv creation, as specified in config file.
```

**Comment by John15321** [comment]
Have you tried reopening your terminal? Maybe a shell restart will help for those options to load

**Comment by finswimmer** [comment]
Hello @MitchK ,

you haven't come back to this issue for a long while. So I assume this is solved in the meantime and I can close this ticket.

Feel free to leave a comment if you disagree.

fin swimmer
