### ISSUE TITLE
poetry add not working, but pip install yes

### ISSUE THREAD

**Issue by alanwilter** [python-poetry/poetry#5788]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

## Issue

Using docker so anyone can reproduce it. 

**Poetry 1.1.13 and 1.2.0b2**

This used to work (at least 5 months ago, it's an adaptation of github action):

```bash
docker run -i -t -w /wdir ubuntu:latest bash

# now, inside docker:

apt-get update && \
apt-get install -y curl python3.8-venv python3-pip && \
curl -sSL https://install.python-poetry.org | POETRY_HOME=/usr/local python3 -

cat << EOF >| pyproject.toml
[tool.poetry]
name = "poetry_test"
version = "0.1.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "^3.8"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
EOF

poetry add openbabel-wheel
poetry run python3 -c 'from openbabel.openbabel import OBReleaseVersion; print(OBReleaseVersion())'
```
However it now throws this error:

```bash
root@d10a3ad11f99:/wdir# poetry add openbabel-wheel
Creating virtualenv poetry-test-_njGwaMt-py3.8 in /root/.cache/pypoetry/virtualenvs
Using version ^3.1.1 for openbabel-wheel

Updating dependencies
Resolving dependencies... (24.9s)

Writing lock file

Package operations: 1 install, 0 updates, 0 removals

  • Installing openbabel-wheel (3.1.1.6)

root@763b089b1910:/wdir# poetry run python3 -c 'from openbabel.openbabel import OBReleaseVersion; print(OBReleaseVersion())'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'openbabel.openbabel'
```

Weirdly,

```bash
root@763b089b1910:/wdir# poetry run python3 -c 'import openbabel; print(dir(openbabel))'
['__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__']
```

So, the package namespace exists but something is clearly wrong.

Now, if I do:

```bash
poetry remove openbabel-wheel
poetry run pip3 install openbabel-wheel
poetry run python3 -c 'from openbabel.openbabel import OBReleaseVersion; print(OBReleaseVersion())'
3.1.0
```

It does work!

What's happening here?

**Comment by dimbleby** [comment]
openbabel-wheel 3.1.1.6 was yanked, I guess because it is broken in the way that you have discovered.

pip understands yanked releases, poetry doesn't.  So you are getting different versions of openbabel-wheel according to which method you use.

Suggest stick to 3.1.1.5 for now.

**Comment by dimbleby** [comment]
#2453 covers support for understanding yanked, so no need to keep this open

**Comment by alanwilter** [comment]
Thanks for that, learnt a new thing.
