### ISSUE TITLE
Creating new virtualenv fails with cryptic error for project with empty name

### ISSUE THREAD

**Issue by mlegner** [python-poetry/poetry#5794]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Linux (Ubuntu 20.04)
- **Poetry version**: 1.2.0b2
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**:  https://gist.github.com/mlegner/39a29fa3d3678a8aedcde45d215e2897

## Issue
When creating a new virtualenv via `poetry env use python` or `poetry add someproject` for a project with an empty name, it fails with the following output:

```sh
$ poetry env use python
Creating virtualenv -6WcazSRI-py3.8 in /home/markus/.cache/pypoetry/virtualenvs
usage: virtualenv [--version] [--with-traceback] [-v | -q] [--read-only-app-data] [--app-data APP_DATA] [--reset-app-data] [--upgrade-embed-wheels] [--discovery {builtin}] [-p py] [--try-first-with py_exe]
                  [--creator {builtin,cpython3-posix,venv}] [--seeder {app-data,pip}] [--no-seed] [--activators comma_sep_list] [--clear] [--no-vcs-ignore] [--system-site-packages] [--symlinks | --copies] [--no-download | --download]
                  [--extra-search-dir d [d ...]] [--pip version] [--setuptools version] [--wheel version] [--no-pip] [--no-setuptools] [--no-wheel] [--no-periodic-update] [--symlink-app-data] [--prompt prompt] [-h]
                  dest
virtualenv: error: argument --prompt: expected one argument
```

The root of the problem is the `virtualenvs.prompt` option added in #5606: The standard value there, `{project_name}-py{python_version}` expands to something like `-py3.8` for a project with empty name, which is interpreted as an option in the call to `virtualenv` instead of the value of `--prompt`.

I suggest to either add a check for an empty name or add quotes for the call to `virtualenv`.

**Comment by abn** [comment]
While a project without a name is invalid, we should still handle the case be defaulting to "py{python-version}" if `project_name` is empty or otherwise unavailable.

**Comment by mlegner** [comment]
> While a project without a name is invalid, we should still handle the case be defaulting to `py{python-version}` if `project_name` is empty or otherwise unavailable.

How about instead changing https://github.com/python-poetry/poetry/blob/master/src/poetry/utils/env.py#L1083? From
```python
            args.extend(["--prompt", prompt])
```
to
```python
            args.extend(["--prompt", f'"{prompt}"'])
```

This would also fix some other potential issues when users change the `virtualenvs.prompt` setting.
