### ISSUE TITLE
Installing poetry built package from git repo hangs at installing build dependencies

### ISSUE THREAD

**Issue by matt-karas-hdai** [python-poetry/poetry#5796]
- [x ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Mac OS Monterrey 12.4
- **Poetry version**: 1.1.13
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: [GIST](https://gist.github.com/matt-karas-hdai/997f9bff4ae5a9b89c80c63cf3251e2b)

## Issue
poetry project A is trying to "poetry add" the simplest possible library made with poetry called "common-python" and pushed to a git repo.  I try to poetry add <proper link to git repo>.  Everything goes ok up until this...

```
Installing common-python (0.1.0 MY_SHA): Building...
```
And it just hangs there - no exceptions - just stays there - no progress.

Same behavior when I try to run "poetry run python -m pip install GIT_REPO_HERE"

```
Running command pip subprocess to install build dependencies
```

**Comment by dimbleby** [comment]
What if you just go into a virtual environment and `pip install`?  Does that hang?  That would seem to make this not a poetry problem.

You've provided no means to reproduce this so it's not clear how anyone could help you.

**Comment by matt-karas-hdai** [comment]
The package was created using poetry.  Trying to use pip install it hangs as well.  I tried to poetry add it as a path as well - and that hangs as well.

It only works when I poetry build "common-python" - and then install on my dependent repo as a wheel.  But that would mean I can't use GitHub to share the code.  Let me see if I can build something simple as possible as an example.

**Comment by dimbleby** [comment]
if you can make pip hang just by trying to install something you probably want to take this bug report to pip

**Comment by dimbleby** [comment]
I notice that in the pyproject.toml you have declared a dependency on pip itself, which feels like it might be a little screwy.  But still: if that's enough to cause pip to hang, that's pip's problem.

**Comment by abn** [comment]
I agree, seems like the problem is not Poetry here. 

Kinda feels like the issue is with your git credentials. Assuming this is a private git repository considering the lack of a link to it :)

I'd recommend you use the ssh link to it than http if you do not already. I'd also recommend trying the latest preview release of poetry to make use of dulwich, which might surface the errors clearer.

**Comment by matt-karas-hdai** [comment]
I did the simplest possible A uses B library locally and got it to work.  It just completes the build no problem.  So I don't know why the more complex program yesterday that uses the simple library hangs on install - when the old one and simple new one installing the same library.  /shrug

Now my problem is getting poetry to work with this stuff on GitHub Actions.
