### ISSUE TITLE
poetry removes the "entrypoints" package causing its own demise

### ISSUE THREAD

**Issue by aviau** [python-poetry/poetry#5797]
- [x] I am on 1.2.0b2
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

Running `poetry install` in the same env as poetry is installed results in poetry removing the `entrypoints` package, making poetry subsequently unusable.

```
  • Removing entrypoints (0.4)
  • Removing webencodings (0.5.1)
```

AFAIK for versions before 1.2, it wasn't required to put poetry in the lockfile and it wouldn't kill itself.

It could be that it isn't a bug, and I wouldn't argue against it. However if poetry remove its own dependencies then maybe it should also remove itself and go for a full-suicide.

**Comment by dimbleby** [comment]
Do I understand that you are:
- defining an environment with poetry / pyproject.toml
- that definition does not include poetry
- but you nevertheless have installed poetry in that environment?

And when you `poetry install`, poetry is trying to make the environment be as you have said it should be - which does not include `entrypoints` (among other things)?

If so I think the answer is simply: don't do that.  Normally you want your poetry installation to be completely separate from the environments that you are managing; if for some reason you want the managed environment to include poetry then you need to say so.

**Comment by aviau** [comment]
Then why does poetry not remove the poetry module? Isn't that inconsistent?

**Comment by dimbleby** [comment]
dunno; but it's hard to get excited about this - either way, it's simply not a supported use case.

**Comment by aviau** [comment]
Right, I understand. I don't mind closing this.
