### ISSUE TITLE
Poetry fails to properly parse dependencies

### ISSUE THREAD

**Issue by scott-8** [python-poetry/poetry#5806]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows 10, Python 3.9
- **Poetry version**: 1.1.13
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue

I've encountered an issue installing [this](https://github.com/enricobacis/wos) package through Poetry. According to the `setup.py` file, it has `suds` as a dependency it's installed in a Python 2 environment, and `suds-py3` in Python 3. 

If I run `pip install wos`, `suds-py3` is installed as it should be. If I run `poetry add wos`, it adds `suds` as a dependency, instead of `suds-py3`. This causes the package not to function.

**Comment by dimbleby** [comment]
poetry is not a python interpreter.  Please encourage packages to use pep508 markers when declaring dependencies, rather than conditional logic in setup.py

**Comment by mkniewallner** [comment]
Closing, since it's an upstream issue.
Linking https://github.com/enricobacis/wos/pull/42 for reference though about a potential fix.
