### ISSUE TITLE
Unable to find installation candidates for opencv-python-headless (4.6.0.66)

### ISSUE THREAD

**Issue by cgerum** [python-poetry/poetry#5810]
Adding the most recent opencv-python as a dependency with poetry 1.1.13 fails with:

   Unable to find installation candidates for opencv-python (4.6.0.66)

To reproduce run:

```
mkdir opencv-test
cd opencv-test/
poetry init -n --dependency=opencv-python
poetry install
```
This is the full output:

```
poetry install -vvv
Using virtualenv: /local/gerum/.cache/pypoetry/virtualenvs/opencv-test-ab-ul6ZH-py3.9
Installing dependencies from lock file

Finding the necessary packages for the current system

Package operations: 1 install, 0 updates, 0 removals, 1 skipped

  • Installing numpy (1.22.4): Pending...
  • Installing numpy (1.22.4): Skipped for the following reason: Already installed
  • Installing opencv-python (4.6.0.66): Pending...
  • Installing opencv-python (4.6.0.66): Failed

  RuntimeError

  Unable to find installation candidates for opencv-python (4.6.0.66)

  at ~/.local/pipx/venvs/poetry/lib/python3.9/site-packages/poetry/installation/chooser.py:72 in choose_for
       68│ 
       69│             links.append(link)
       70│ 
       71│         if not links:
    →  72│             raise RuntimeError(
       73│                 "Unable to find installation candidates for {}".format(package)
       74│             )
       75│ 
       76│         # Get the best link
```

**Comment by mkniewallner** [comment]
It works on my side on Poetry 1.1.13 and Python 3.9.

Could you try recreating your virtualenv by running `poetry env remove opencv-test-ab-ul6ZH-py3.9` then retry the install?
If it doesn't solve the issue, try locking your dependencies just in case (`poetry lock --no-update`) then retry the install.

**Comment by cgerum** [comment]
@mkniewallner Thanks, a lot for your information. 

The reason was that my `poetry.lock` file was missing the information for `opencv_python-4.6.0.66-cp36-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl`.

These where still missing after `poetry env remove opencv-test-ab-ul6ZH-py3.9` and `poetry lock --no-update`, but appeared after removing the poetry cache using `rm -rf ~/.cache/pypoetry/cache/repositories/pypi/`.
