### ISSUE TITLE
Update version number in pyproject.toml and update lock file without dependency resolution

### ISSUE THREAD

**Issue by Korijn** [python-poetry/poetry#5812]
When performing a release of my library or application, I typically bump the version number in `pyproject.toml`.

However, that means the lockfile is now out of sync (as it includes a content-hash of `pyproject.toml`). The only way to resolve is to re-run `poetry lock`, or to compute the content-hash myself and update `poetry.lock` manually 🤮.

If I choose to apply `poetry lock`, dependency resolution is performed, but I don't want to do that right before a release of my software!

Is there a command or option that I'm overlooking to deal with this situation?

- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

**Comment by dimbleby** [comment]
You have checked the "I have searched the documentation" box, but have you really?  `poetry lock` has exactly one option and it does what you want.

**Comment by Korijn** [comment]
Well, I just tried that, but it still changes the locked versions of packages. I'm on v1.1.12. Reopening.

**Comment by dimbleby** [comment]
Sounds like a duplicate then, if so then it looks as though it should be fixed in the latest beta

**Comment by radoering** [comment]
The content hash does not include every part of `pyproject.toml`. If I remember correctly, only dependency sections are considered.

**Comment by Korijn** [comment]
> The content hash does not include every part of `pyproject.toml`. If I remember correctly, only dependency sections are considered.

Ahh! That makes sense. OK thanks!
