### ISSUE TITLE
Poetry does not show the virtualenv prefix on PowerShell

### ISSUE THREAD

**Issue by Lazza** [python-poetry/poetry#5824]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows 10
- **Poetry version**: 1.1.13 installed via Pip
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: N/A

## Issue

When running `poetry shell`, it looks like Poetry runs the `virtualenv` activation. However, it does not show the visual cue in the command prompt, e.g.:

```
D:\repo\REDACTED [master ≡]> poetry shell
Spawning shell within C:\Users\andrea\AppData\Local\pypoetry\Cache\virtualenvs\REDACTED-WpnDpl_K-py3.9
Windows PowerShell
Copyright (C) Microsoft Corporation. Tutti i diritti riservati.

Prova la nuova PowerShell multipiattaforma https://aka.ms/pscore6

D:\repo\REDACTED [master ≡]>
```

The same happens if I intentionally run the "wrong" activation script (the `cmd` one) manually:

```
C:\Users\andrea\AppData\Local\pypoetry\Cache\virtualenvs\REDACTED-WpnDpl_K-py3.9\Scripts\activate
```

However, the virtual environment name is shown when manually running the PowerShell activation script:

```
C:\Users\andrea\AppData\Local\pypoetry\Cache\virtualenvs\REDACTED-WpnDpl_K-py3.9\Scripts\activate.ps1
```

Sadly, the virtualenv name is added at the end, and not at the beginning of the prompt, like the standard `venv` module (not `virtualenv`) does. But that's just a personal preference.

**Comment by bmarroquin** [comment]
closed by #5053. already available in 1.2 beta
