### ISSUE TITLE
Poetry unable to find tensorflow-macos

### ISSUE THREAD

**Issue by ankurt** [python-poetry/poetry#5844]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

Using Github [action](https://github.com/snok/install-poetry):

- macOS 11.6.6 (Big Sur) x64 architecture 
- Poetry v1.1.13
- pyproject.toml: https://gist.github.com/ankurt/45c36e676338eb51d58c6fb818347b7c
- github workflow: https://gist.github.com/ankurt/e9aad5ee8b334a62db362278d01ed557

## Issue
When I run the same command on my macbook pro, `tensorflow-macos@2.9.2` is installed correctly and there are no issues. However in the Github actions which is just a containerized version of my setup, I get the below.

tensorflow-macos 2.9.2 was last released on June 6, 2022 at the time of writing this (June 14, 2022) and is available on PyPi:
https://pypi.org/project/tensorflow-macos/

I'm using python 3.9.7 on the github action.

Command:
```
poetry install --remove-untracked
```

Error message (verbose):
```
  • Installing tensorflow-macos (2.9.2)
  Stack trace:
  5  ~/.local/venv/lib/python3.9/site-packages/poetry/installation/executor.py:203 in _execute_operation
      201│ 
      202│             try:
    → 203│                 result = self._do_execute_operation(operation)
      204│             except EnvCommandError as e:
      205│                 if e.e.returncode == -2:
  4  ~/.local/venv/lib/python3.9/site-packages/poetry/installation/executor.py:277 in _do_execute_operation
      275│             return 0
      276│ 
    → 277│         result = getattr(self, "_execute_{}".format(method))(operation)
      278│ 
      279│         if result != 0:
  3  ~/.local/venv/lib/python3.9/site-packages/poetry/installation/executor.py:412 in _execute_install
      410│ 
      411│     def _execute_install(self, operation):  # type: (Install) -> None
    → 412│         return self._install(operation)
      413│ 
      414│     def _execute_update(self, operation):  # type: (Update) -> None
  2  ~/.local/venv/lib/python3.9/site-packages/poetry/installation/executor.py:438 in _install
      436│             archive = self._download_link(operation, Link(package.source_url))
      437│         else:
    → 438│             archive = self._download(operation)
      439│ 
      440│         operation_message = self.get_operation_message(operation)
  1  ~/.local/venv/lib/python3.9/site-packages/poetry/installation/executor.py:584 in _download
      582│ 
      583│     def _download(self, operation):  # type: (Operation) -> Path
    → 584│         link = self._chooser.choose_for(operation.package)
      585│ 
      586│         return self._download_link(operation, link)
  RuntimeError
  Unable to find installation candidates for tensorflow-macos (2.9.2)
  at ~/.local/venv/lib/python3.9/site-packages/poetry/installation/chooser.py:72 in choose_for
       68│ 
       69│             links.append(link)
       70│ 
       71│         if not links:
    →  72│             raise RuntimeError(
       73│                 "Unable to find installation candidates for {}".format(package)
       74│             )
       75│ 
       76│         # Get the best link
```

I have tried with python 3.8.12 as well with no success.

**Comment by mkniewallner** [comment]
Hi, could you also share your `poetry.lock` file by any chance?

It may also be worth testing with Poetry [1.2.0b2](https://github.com/python-poetry/poetry/releases/tag/1.2.0b2), to see if you encounter the same issue:
```yaml
- name: Install poetry
  uses: snok/install-poetry@v1
  with:
    version: 1.2.0b2
```

**Comment by ankurt** [comment]
> Hi, could you also share your `poetry.lock` file by any chance?
> 
> It may also be worth testing with Poetry [1.2.0b2](https://github.com/python-poetry/poetry/releases/tag/1.2.0b2), to see if you encounter the same issue:
> 
> ```yaml
> - name: Install poetry
>   uses: snok/install-poetry@v1
>   with:
>     version: 1.2.0b2
> ```

Ah, apologies. I forgot to add that I have already tried the latest beta without success just as you suggested.
I tried it with:
```
version: 1.2.0b2
virtualenvs-create: true
virtualenvs-in-project: true
```

My poetry.lock file:
https://gist.github.com/ankurt/062f55ccbb3058688f31a162ea3f1c24

**Comment by dimbleby** [comment]
Suggest that you're going to need to figure out the difference between the environment where it works and the environment where it doesn't - and that you're much better placed to do that than anyone else.

Wild speculation: perhaps github have started using macos-12 for macos-latest, and forgotten to tell anyone.  Anyway macos-11 would be more explicit, could be worth a try.

Good luck!

**Comment by ankurt** [comment]
I took the macOS version I reported here from the output of the job, not from the documentation.

<img width="924" alt="image" src="https://user-images.githubusercontent.com/4619775/173717271-14358bde-da0c-4e34-8dfd-4a760ff3c888.png">

I'd be shocked if both the documentation and the output is incorrect haha. I think there would be a lot of complaints flooding in about builds breaking. Appreciate the suggestion and I'll make the change regardless to make sure there's stability in the workflow.

I'll keep trying myself of course, but I'd like to keep this issue open in case others run into it as well or anyone has solved it. If I fix it, I'll be sure to post my solution.

**Comment by finswimmer** [comment]
Hello @ankurt,

you haven't come back to this issue for a long while. So I assume this is solved in the meantime and I can close this ticket.

Feel free to leave a comment if you disagree.

fin swimmer

**Comment by ankurt** [comment]
> you haven't come back to this issue for a long while. So I assume this is solved in the meantime and I can close this ticket.

We ended up ditching the dependency in our project for now, however we will be returning to this later in the year possibly. I think it is reasonable to close it since our deps and environment will be so different when we try later this year compared to the details of this issue that if I encounter issues it will likely be a separate issue. Thanks for the follow up!
