### ISSUE TITLE
Poetry can't find version in a private repository without a version number folder

### ISSUE THREAD

**Issue by lalmei** [python-poetry/poetry#5847]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I execute it again in debug mode (`-vvv` option).

- **OS version and name**:  ubuntu 20.04 and Mac OSX 
- **Poetry version**: 1.1.12 - 1.2.0b2
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue

Poetry can't find package versions (x.y.z) from private repositories organized as `<package_name>/<package_name>-x.y.z-py2.py3-none-any.whl`
This seems to be an issue with the legacy repositories. However, the latest `pip` release can find the package version without problem.

**Comment by mkniewallner** [comment]
Could you provide a bit more details on how you configured access to private repositories?

Ideally, if we could have a `pyproject.toml`, the error message you have, and the possible commands you typed to configure access to the private repositories (make sure to redact sensitive information like repository URL, credentials, etc.), this would help us better understand the issue.

**Comment by lalmei** [comment]
`pyproject.toml` is here https://gist.github.com/lalmei/4685d0369a9db99da3dd0ce8b037d42c
I run 
```bash
poetry config repositories.mypypi ${ARTIFACTORY_URL}/artifactory/api/pypi/pypi
poetry config http-basic.mypi ${ACCT_NAME} ${ACCT_PWD}
```

**Comment by dimbleby** [comment]
did you try configuring poetry to use `myartifactory.com/artifactory/api/pypi/pypi/simple`?  (You dropped the `simple` above)

**Comment by lalmei** [comment]
yeah, fixed.

**Comment by dimbleby** [comment]
@lalmei then please close the issue

**Comment by lalmei** [comment]
> @lalmei then please close the issue

Sorry poor choice of words above, the issue itself is not fixed

**Comment by dimbleby** [comment]
You also have a mismatch between `mypi` and `mypypi` - is that real or another copy-paste fail?

I am expecting this to be user / config error because we use artifactory at $WORK, and I know that what you are trying to do works just fine there.

**Comment by finswimmer** [comment]
Hello @lalmei,

you haven't come back to this issue for a long while. So I assume this is solved in the meantime and I can close this ticket.

Feel free to leave a comment if you disagree.

fin swimmer
