### ISSUE TITLE
Resolver prioritizes dependencies

### ISSUE THREAD

**Issue by FredrikWallstrom** [python-poetry/poetry#5852]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request
I have one dependency in my project that acts like a wrapper and bundles several dependencies. I’m continuously releasing new versions of this wrapper. The problem I have is that the sub-dependencies that is installed by the wrapper have strict versions constraints.

Example:

```
Main project:
[tool.poetry.dependencies]
wrapper = ">=2.0.0,<2.100.0"
flake8 = "^3"

wrapper: 
[tool.poetry.dependencies]
flake8 = "3.0.0"
```

Let's say there are 100 available versions of the wrapper package, all of them have flake8 locked to version 3.0.0. The resolver will start resolving from the flake8 dependency because it has [fewest available versions](https://github.com/python-poetry/poetry/blob/3f54fdc96432a7313ea00df52ba6808465519b10/src/poetry/mixology/version_solver.py#L378). It will start with the latest flake8 version and check for a solution, it wont find a solution because the requirement is not fulfilled by any version of the wrapper. The resolver will continue until it reaches flake8 version 3.0.0.

This is of course a stupid example but imagine what will happen with the resolve time if the bundler bundles more dependencies and the main project depends on additional dependencies where sub-dependencies conflicts with wrappers' dependencies.

In this example and also in my real project, it would be beneficial if the resolver started to resolve from the wrapper dependency instead of picking the dependency with the fewest available versions. I know it is not recommended to have strict dependencies like this but restructure my project setup requires too much of an effort.  

I have been digging but I haven’t find a way around this, is there something I can do to reduce the resolve time?
 What about adding a flag where you can tell the resolver to start resolve from a specific dependency, like this?

`wrapper = {"version" = ">=2.0.0,<2.100.0", prioritize = true}`

**Comment by dimbleby** [comment]
#5217 was similar, in that one many hundreds of versions of awscli were incompatible with recent pyyaml: so it was unfortunate that poetry tried to fix pyyaml first.

Best advice I have is to restrict the space that you have to search: eg prefer `wrapper = ">= 2.100.0"`. Or explicitly require lower flake8 from your main project - or make `wrapper` compatible with recent flake8!

Pretty sure that in general dependency resolution is NP-hard.  I don't at all mean that poetry is unimprovable, that would be nonsense: but whatever heuristics you use or add there will always be hard cases to solve.

**Comment by FredrikWallstrom** [comment]
> Best advice I have is to restrict the space that you have to search: eg prefer wrapper = ">= 2.100.0". Or explicitly require lower flake8 from your main project - or make wrapper compatible with recent flake8!

Unfortunately it is not an option to give hints to the resolver like this because I need to stay backwards compatible with old integrations.

Yea, I understand that dependency resolution is difficult and that there won't be a heuristic that solves all cases. I'm not 100% into this topic or the inner working of poetry, but for me it feels feasible to add an optional possibility to define a starting node, without interfering the standard behavior beyond that. I think that will bring a lot of value.

**Comment by dimbleby** [comment]
You could still stay backwards compatible with old versions of `wrapper` by specifying `flake8 = "3.0.0"` in your main project.  If you know that's the answer that you're going to get anyway, why not save yourself and poetry the pain of working it out?

I fear that what you suggest is quickly going to get hairy, and deal with only a small set of special cases - I worry that it would likely cause more confusion than it solves.

Anyway: you found the right bit of code for where the heuristic about "which package should I try to decide next" goes, if you - or anyone else - is motivated to put together an MR then no doubt maintainers would take a view on it.

(Actually at #5217 I considered reversing that heuristic completely, which works well in that particular example.  But I was afraid that it would just introduce different bad examples!  If you can convince yourself that this reversal would tend to make things better rather than worse, perhaps that's a case worth making.)

**Comment by dimbleby** [comment]
Actually one more thing to add: I did get some performance improvements merged at #5217 which - while very much not solving this case - did help somewhat.  

If you haven't already tried the latest beta it's probably worth you doing so and seeing if that improves things for you.

**Comment by FredrikWallstrom** [comment]
I did a quick hack where I hard coded my wrapper package as starting point, which worked out quite well. I then saw the possibility to make this more dynamic by letting the user define the starting point. However, I'm just seeing things from my perspective and my project and hence I wanted to raise the question here (before the implementation) to get some more insights if this is a good idea, bad idea, if it adds confusions, if it will make things worse, if there are other ways etc. So, very greatful for you responses 👍

I will think about this a little bit more. If I can give the resolver some hints in my project to reduce the resolve time, or I might open a PR here and then we will see where that lands.

**Comment by radoering** [comment]
If we wanted to include such a feature, an integer for priority might be better than a boolean flag, so you can have an order for several dependencies. I think it's feasible. However, I'm not sure if it's worth it. I ask myself how many users would be able to make use of such a feature and how many users would shoot themselves in the foot...

**Comment by FredrikWallstrom** [comment]
I created one PR for this, please let me know what you think.

**Comment by dimbleby** [comment]
Personally I remain un-persuaded - it seems to me that by the time you've figured out how to guide the solver with the magic priority, you might just as well have told it more explicitly what you'd like the solution to look like ie add a constraint on the problematic package.

(I speak only for myself, others might feel differently)

**Comment by neersighted** [comment]
https://github.com/python-poetry/poetry/pull/6011#issuecomment-1250358696
