### ISSUE TITLE
Cant install poetry ("The latest version (1.1.13) is already installed.")

### ISSUE THREAD

**Issue by HappyCthulhu** [python-poetry/poetry#5853]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

* Ubuntu 20.04 focal
* Poetry version 1.1.13

## Issue
I installed master-version of poetry with `curl -sSL https://install.python-poetry.org | python3 -`
I wanted to reinstall Poetry. I was to lazy to spent 1 minute for google "Correct way to uninstall poetry". And just delete ~/local/bin/poetry. I thought, that it is ok, Expecialy consider that fact, that i didnt that previsusly and everyfing worked fine. But not this time

This time after i tried `curl -sSL https://install.python-poetry.org | python3 -`, it gives me:

Retrieving Poetry metadata

The latest version (1.1.13) is already installed.

After multiple tries to install master-version of poetry, i just did `find / -iname poetry | xargs -d '\n' rm -r`.
That didn`t help at all. Can u tell me, what can i do to fix this? Maybe u can tell me, where do u store poetry metadata?

P.s. BTW, pip install poetry working fine.

**Comment by dimbleby** [comment]
> I installed master-version of poetry with curl -sSL https://install.python-poetry.org | python3 -

That would install poetry 1.1.13.  Which, presumably, would make the error message exactly right.

**Comment by finswimmer** [comment]
Hey @HappyCthulhu,

the `install-poetry.py` script installs poetry to `/~/.local/share/pypoetry`.

The correct way of uninstalling is documented here: https://python-poetry.org/docs/master/#installation

```
curl -sSL https://install.python-poetry.org | python3 - --uninstall
```

fin swimmer

**Comment by HappyCthulhu** [comment]
> Hey @HappyCthulhu,
> 
> the `install-poetry.py` script installs poetry to `/~/.local/share/pypoetry`.
> 
> The correct way of uninstalling is documented here: https://python-poetry.org/docs/master/#installation
> 
> ```
> curl -sSL https://install.python-poetry.org | python3 - --uninstall
> ```
> 
> fin swimmer

U right. poetry was installed in ~/.local/share/pypoetry
I delete this dir and, finally, poetry got the opportunity to install master-version of poetry again
