### ISSUE TITLE
Poetry ignores extra dependency of an extra dependency

### ISSUE THREAD

**Issue by tusharsnn** [python-poetry/poetry#5862]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: windows 11
- **Poetry version**: 1.1.13
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: [link](https://gist.github.com/tusharsnn/8615918e33f79015462ffa1b67448c18)

## Issue 
I tried to install motor's(pymongo mongoDB wrapper) extra dep `srv` using:
```sh
poetry add 'motor[srv]'
```
but it does not seems to install the extras. whereas doing something like:
```sh
poetry add 'pymongo[srv]'
```
works fine, which is exactly what motor's `srv` should install indirectly. Motor mirrors all extra dependency of pymongo without any modifications.

In a successful operation this should install [motor](https://github.com/mongodb/motor) and [pymongo](https://github.com/mongodb/mongo-python-driver) with `dnspython`

link to debug output(installing motor\[srv\]): [link](https://gist.github.com/tusharsnn/d1f8fb06e620fa5ca2d9aa882da4d934)

**Comment by tusharsnn** [comment]
`pypi.org/pypi/motor/json`  returns:
```json
{
    ...
    "requires_dist" : [
         "pymongo (<5,>=4.1)",
         "pymongo[aws] (<5,>=4.1) ; extra == 'aws' ",
         "pymongo[encryption] (<5,>=4.1) ; extra == 'encryption'",
         "pymongo[gssapi] (<5,>=4.1) ; extra == 'gssapi'",
         "pymongo[ocsp] (<5,>=4.1) ; extra == 'ocsp'",
         "pymongo[snappy] (<5,>=4.1) ; extra == 'snappy'",
         "pymongo[srv] (<5,>=4.1) ; extra == 'srv'", 
         "pymongo[zstd] (<5,>=4.1) ; extra == 'zstd'"
     ],
     ...
}
```
Poetry should be getting required details regarding which extra dependencies are available to install and should install the right one as well?

**Comment by dimbleby** [comment]
On master:
```
$ poetry add 'motor[srv]'
Using version ^3.0.0 for motor

Updating dependencies
Resolving dependencies... (0.5s)

Writing lock file

Package operations: 3 installs, 0 updates, 0 removals

  • Installing dnspython (2.2.1)
  • Installing pymongo (4.1.1)
  • Installing motor (3.0.0)
```
which seems to be what is desired

**Comment by tusharsnn** [comment]
@dimbleby thanks for the quick reply. I tried installing the packages with 1.2.0b2 and it working as expected. closing this now in favour of future stable release.
