### ISSUE TITLE
Poetry fails when install is executed multiple times

### ISSUE THREAD

**Issue by lorenzocesconetto** [python-poetry/poetry#5867]
- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: MacOS M1 chip, but within this Docker image: python:3.10.4-slim-bullseye
- **Poetry version**: 1.1.13
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/lorenzocesconetto/babddc1f33bec791c1671b5adb55c145

## Issue

When I execute `poetry install --no-root --no-dev` in a step and then execute `poetry install --no-root` in another step in order to download dev requirements as well, poetry throws an error. But if I execute only one install, it does not break.

The error it throws is:

ModuleNotFoundError: No module named 'webencodings'

**Comment by dimbleby** [comment]
installing poetry should install webencodings (via html5lib).

You've somehow not done that, or uninstalled it from a good installation.

It's unlikely that this is a problem with the poetry install procedure - else everyone would be hitting this - and more likely that you have done something funky to your installation.

**Comment by dimbleby** [comment]
No response, almost surely user error, can close

**Comment by stephenostermiller** [comment]
I get this particular error sometimes when installing poetry with `conda install poetry`.  Conda is currently installing poetry 1.4.0.  After installation, poetry works fine.  

Then later when I perform certain operations, such as updating my `pyproject.toml` using `poetry update`, poetry will no longer be able to find `webencodings`.   I can fix it with `conda remove poetry && conda install poetry`. 

Installing files from my lock file with `poetry install` seems to work fine, it seems to be only the `poetry update` that causes the problem for me.
