### ISSUE TITLE
Integration between pyenv virtualenvs and poetry envs?

### ISSUE THREAD

**Issue by John15321** [python-poetry/poetry#5875]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

I love Poetry and I also love using Pyenv. I think both of those tools are great and that's what everyone using Python should have as their primary tools for development. 😁

My idea is to have some better integration between those two. Pyenv installs python versions and creates their virtual environments, which is great but Poetry kinda does the same thing at least with the virtual envs (please correct me if Im wrong). Maybe it would be nice to have some more integration between those two? So that Poetry could create a virtualenv using pyenv or install some additional python versions using pyenv? Im not sure if this is hard or easy to do but I will gladly contribute to the project myself ☺️

**Comment by Secrus** [comment]
`pyenv` by default only installs and manages active python versions. It does not manage virtualenvs unless used with a plugin. If you are using some other tool for virtualenv management, you can set [`virtualenvs.create](https://python-poetry.org/docs/master/configuration/#virtualenvscreate) option to `false` in your poetry config. Then, poetry will install dependencies to currently active virtualenv or (if none is activated) to system packages (not recommended).

**Comment by John15321** [comment]
> `pyenv` by default only installs and manages active python versions. It does not manage virtualenvs unless used with a plugin. If you are using some other tool for virtualenv management, you can set [`virtualenvs.create](https://python-poetry.org/docs/master/configuration/#virtualenvscreate) option to `false` in your poetry config. Then, poetry will install dependencies to currently active virtualenv or (if none is activated) to system packages (not recommended).

Hm, yes I know all of that, I just thought that maybe having an option for forwarding that virtual env creation to pyenv with the virtualenv plugin would be nice. This way you can have a full connection within your toolchain

**Comment by Secrus** [comment]
I don't think it's something we want. Poetry tries to keep away from tightly integrating with too many external tools as this needs extra maintenance in case when something changes upstream. This feature would add some complexity, especially since `pyenv` has a fork to work on Windows and it might not be compatible.
