### ISSUE TITLE
Updating with "--only dev" causes prod dependencies to be updated too

### ISSUE THREAD

**Issue by fredrikaverpil** [python-poetry/poetry#5876]
- [x] I am on 1.2.0b2
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate. **But it sure is a lot to search through - so I might have missed it.**
- [x] No exception occurs.

- **OS version and name**: macOS Monterey 12.4 (21F79)
- **Poetry version**: 1.2.0b2
- Gist with pyproject.toml, poetry.lock: https://gist.github.com/fredrikaverpil/830b18230e539f8e7f1fda5dedad52ea

## Issue

I wanted to run `poetry update --only dev` to update developer dependencies only. But this ended up updating my prod dependency too.

I have:

```toml
[tool.poetry.dependencies]
python = "^3.10"
watchdog = "^2.1.6"

[tool.poetry.dev-dependencies]
mkdocs = "^1.3.0"
mkdocs-material = "^8.2.11"
```

I don't know if this is the expected behavior, as the production dependency of `watchdog` is also a sub-dependency of the developer dependencies `mkdocs` and `mkdocs-material`.

I was hoping that I could invoke an update of developer dependencies and not touch the production dependencies.

## Log output

```
$ poetry@1.2.0b2 update --only dev 
Configuration file exists at /Users/fredrik/Library/Application Support/pypoetry, reusing this directory.

Consider moving configuration to /Users/fredrik/Library/Preferences/pypoetry, as support for the legacy directory will be removed in an upcoming release.
Updating dependencies
Resolving dependencies... (0.2s)

Writing lock file

Package operations: 0 installs, 5 updates, 0 removals

  • Updating watchdog (2.1.6 /Users/fredrik/Library/Caches/pypoetry/artifacts/34/3c/de/71d3e8ca9ff6fc93539ab50bca2af0f1dcc6797d232a9be264e3987c97/watchdog-2.1.6-cp310-cp310-macosx_11_0_arm64.whl -> 2.1.9)
  • Updating mkdocs-material-extensions (1.0.3 /Users/fredrik/Library/Caches/pypoetry/artifacts/fb/07/d5/363eebdd3040635d645a694c8c209113f724b04cff89d59a21a7852412/mkdocs_material_extensions-1.0.3-py3-none-any.whl -> 1.0.3)
  • Updating pygments (2.12.0 /Users/fredrik/Library/Caches/pypoetry/artifacts/a4/25/5e/e91fc50f64ea2fdfe34dda0c549820b87ebed679822b94b690f8ab80d3/Pygments-2.12.0-py3-none-any.whl -> 2.12.0)
  • Updating pymdown-extensions (9.4 /Users/fredrik/Library/Caches/pypoetry/artifacts/33/0a/24/6659c7de12f94a18eab2391d6bab65aaef69a6ab9377defe89e74eaea0/pymdown_extensions-9.4-py3-none-any.whl -> 9.5)
  • Updating mkdocs-material (8.3.4 /Users/fredrik/Library/Caches/pypoetry/artifacts/d6/c3/6d/18db40a739d31997678baa90aaa3e1bb4d422a2ec8cb4d5664901ab0ab/mkdocs_material-8.3.4-py2.py3-none-any.whl -> 8.3.6)
```

For an even more minimal reproducible setup, run:

```
$ poetry remove --dev mkdocs

$ poetry@1.2.0b2 update --only dev
Configuration file exists at /Users/fredrik/Library/Application Support/pypoetry, reusing this directory.

Consider moving configuration to /Users/fredrik/Library/Preferences/pypoetry, as support for the legacy directory will be removed in an upcoming release.
Updating dependencies
Resolving dependencies... (0.5s)

Writing lock file

Package operations: 0 installs, 3 updates, 0 removals

  • Updating watchdog (2.1.6 /Users/fredrik/Library/Caches/pypoetry/artifacts/34/3c/de/71d3e8ca9ff6fc93539ab50bca2af0f1dcc6797d232a9be264e3987c97/watchdog-2.1.6-cp310-cp310-macosx_11_0_arm64.whl -> 2.1.9)
  • Updating pymdown-extensions (9.4 /Users/fredrik/Library/Caches/pypoetry/artifacts/33/0a/24/6659c7de12f94a18eab2391d6bab65aaef69a6ab9377defe89e74eaea0/pymdown_extensions-9.4-py3-none-any.whl -> 9.5)
  • Updating mkdocs-material (8.3.4 /Users/fredrik/Library/Caches/pypoetry/artifacts/d6/c3/6d/18db40a739d31997678baa90aaa3e1bb4d422a2ec8cb4d5664901ab0ab/mkdocs_material-8.3.4-py2.py3-none-any.whl -> 8.3.6)
```

**Comment by fredrikaverpil** [comment]
A side-note: I've created a GitHub Action https://github.com/fredrikaverpil/poetry-update which utilize the `update --only` arguments, to avoid "dependabot updating fatigue". This could be great for e.g. developer dependencies. But then it's quite important that the production dependencies are not being updated.

**Comment by mkniewallner** [comment]
This is not an easy case, IMO, because people may have different expectations.

I personally would expect that `--only dev` at least doesn't update direct dependencies that are not in dev, even if they are sub-dependencies of dev dependencies.

That being said, what about if `watchdog` was not a direct main dependency, but was used indirectly by both a main and a dev dependency?
Would the user expects `--only dev` to update `watchdog` in that case?

**Comment by fredrikaverpil** [comment]
> That being said, what about if watchdog was not a direct main dependency, but was used indirectly by both a main and a dev dependency?
Would the user expects --only dev to update watchdog in that case?

I think I would expect that if `watchdog` is explicitly defined in any other dependency group, it wouldn't be touched. But if it was just a (shared) sub-dep it would be updated.

**Comment by mkniewallner** [comment]
> > That being said, what about if watchdog was not a direct main dependency, but was used indirectly by both a main and a dev dependency?
> > Would the user expects --only dev to update watchdog in that case?
> 
> I think I would expect that if `watchdog` is explicitly defined in any other dependency group, it wouldn't be touched. But if it was just a (shared) sub-dep it would be updated.

That would also be my personal expectations, but again, some people may think otherwise.

At least for the first case (having `watchdog` as a direct dependency), I would tend to think that people expect `watchdog` to not be updated (but I may be wrong here since I don't have data to back that).

For one (or both) case(s), we may be able to provide a flag to control the behavior in different ways, but I'm afraid that it would complicate the logic and add too many options to the command.

Regardless of the behavior, the documentation today [doesn't say much](https://python-poetry.org/docs/master/cli/#update) about what happens on update when specifying groups, so at least we should make that clearer, once we either confirm that this is the expected behavior or that there is something to change.

**Comment by last-partizan** [comment]
I stumbled upon this issue also, and using following workaround:

```python
# get-dev-deps.py
import toml

if __name__ == "__main__":
    data = toml.load("pyproject.toml")
    deps = data["tool"]["poetry"]["group"]["dev"]["dependencies"]
    print(" ".join(deps.keys()))
```

```
poetry update $(python get-dev-deps.py)
```

it works as expected - it updates only dev dependencies. And i expect `--only dev` to work exactly the same way.
