### ISSUE TITLE
When will the next major version be released?

### ISSUE THREAD

**Issue by beck3905** [python-poetry/poetry#5882]
- [x ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Issue

I see some really interesting looking features in the docs for the current `master` version of Poetry.  Is there a timeline set for when that version will be released as a stable version?

BTW, thanks for this tool.  So far it has been a great addition to my Python workflow.

**Comment by Secrus** [comment]
You can check out #5586 for some info about some blockers for 1.2. There is no set date for the 1.2 release. Just a reminder, everyone working on poetry is doing it in their free time. We all have private affairs and daywork.
