### ISSUE TITLE
Homebrew as an alternative to install Poetry on macOS

### ISSUE THREAD

**Issue by nelsoncardenas** [python-poetry/poetry#5886]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

I was reading the documentation, and I think it could be improved for macOS users. Specifically, I used _Homebrew_ to install _Poetry_, but the documentation says nothing about it. My suggestion is:

- Clarify, maybe with a section,  the alternative of using `homebrew` to install poetry in macOS as a good or bad practice.

**Edit 1:** I'm a new user, but I wanted to add this issue to avoid forgetting to create it. Now I think it must be advised to avoid using _homebrew_ due to the problems with the command `poetry self update`. If you install _Poetry_ using _Homebrew_ and perform that command, you will get the message `"Poetry was not installed with the recommended installer. Cannot update automatically."` Evidence:

```bash

  RuntimeError

  **Poetry was not installed with the recommended installer. Cannot update automatically.**

  at /opt/homebrew/Cellar/poetry/1.1.13/libexec/lib/python3.10/site-packages/poetry/console/commands/self/update.py:389 in _check_recommended_installation
      385│         current = Path(__file__)
      386│         try:
      387│             current.relative_to(self.home)
      388│         except ValueError:
    → 389│             raise RuntimeError(
      390│                 "Poetry was not installed with the recommended installer. "
      391│                 "Cannot update automatically."
      392│             )
      393│ 

```

**Comment by Secrus** [comment]
1. Any means of installation that are not mentioned in the documentation, are 3rd party and can be prone to breakage
2. Poetry team decided against providing system/distro-specific means of installation. Those require extra maintenance and we prefer to spend our time working on Poetry rather than fixing system-specific installer issues.
