### ISSUE TITLE
Duplicated console output in 1.2.0b2

### ISSUE THREAD

**Issue by andreymal** [python-poetry/poetry#5888]
Poetry 1.2.0b1:

```
$ poetry build -f wheel
Building projectname (0.1.0)
  - Building wheel
  - Built projectname-0.1.0-py3-none-any.whl
```

Poetry 1.2.0b2 (and latest master):

```
$ poetry build -f wheel
Building projectname (0.1.0)
  - Building wheel
  - Building wheel
  - Built projectname-0.1.0-py3-none-any.whl
  - Built projectname-0.1.0-py3-none-any.whl
```

After some testing I found the behavior changed after commit https://github.com/python-poetry/poetry/commit/50ef22753b4aec2a9825a4b74531b3d99e285678

(Tested in Kubuntu 22.04, Python 3.10.4)

**Comment by dimbleby** [comment]
Probably [this line](https://github.com/python-poetry/poetry/blob/9932e2608d5a50e9cbe512574b3f2504f5c3ca7c/src/poetry/console/application.py#L267) just wants removing: the handler is attached to the root logger ten lines previously and does not need separately to be added to the individual loggers.
