### ISSUE TITLE
Poetry remove not aware of underscores in packages names

### ISSUE THREAD

**Issue by corentinbettiol** [python-poetry/poetry#5892]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu flavor
- **Poetry version**: 1.1.13
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: *no gist*

## Issue

Hi!

When we install a package using poetry, using underscores instead of dashes works because poetry is smart (eg `poetry add dangocms_page_meta`), but when using `poetry remove` it doesn't work (eg `poetry remove djangocms_page_meta` fail with message `ValueError Package djangocms_page_meta not found`).

It could be cool to unify the install/remove "awareness", because it can be confusing to be able to install a package, and to not be able to remove it using the same name.

**Comment by finswimmer** [comment]
Hello  @corentinbettiol,

please try with the latest preview release (1.2.0b2). It should be fixed there.

fin swimmer

BTW: The correct command is `poetry add djangocms_page_meta`. :)

**Comment by corentinbettiol** [comment]
> please try with the latest preview release (1.2.0b2). It should be fixed there.

I'll give it a try, I didn't think to try an unstable version.

> BTW: The correct command is poetry add djangocms_page_meta. :)

Oops, fixed thanks!

**Comment by corentinbettiol** [comment]
Can confirm it works using 1.2.0b2, sorry for opening this issue!

```
$ poetry --version 
Poetry (version 1.2.0b2)
$ poetry add django_check_seo
Creating virtualenv test in /home/co/test/.venv
Using version ^0.5.1 for django-check-seo
Writing lock file
Package operations: 34 installs, 0 updates, 0 removals
[...]
$ poetry remove django_check_seo
Updating dependencies
Resolving dependencies... (0.1s)
Writing lock file
Package operations: 0 installs, 0 updates, 34 removals
[...]
```
