### ISSUE TITLE
Downloaded packages with explicit compression fail hash verification

### ISSUE THREAD

**Issue by EpicWink** [python-poetry/poetry#5901]
### Checklist
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

### Environment
- **OS version and name**: Ubuntu 20.04
- **Poetry version**: 1.1.13
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: N/A 

### Issue
If an index server serves a file with `Content-Encoding` set, Requests (via `urllib3`) will automatically decode (ie decompress) the file, while Poetry assumes the file is not decoded. This causes the file (for an sdist, now just a plan TAR archive) to have a different hash from what the index reported (and therefore the hash in the lock file).

More information: https://github.com/EpicWink/proxpi/issues/9#issuecomment-1164318555

I'm not sure if an sdist should be considered arbitrary bytes (in which case `proxpi` should always be setting content-type to 'application/octet-stream' and not setting content-encoding).

If you wanted to bypass `urllib3`'s automatic decoding, set `response.raw.CONTENT_DECODERS = ()` in `Executor._download_archive` before reading the contents.

**Comment by neersighted** [comment]
The issue is on the server end, I believe. The intention is to serve a `.tar.gz` file, so you shouldn't encourage clients to try and decode it. The same will happen with a web browser downloading such a file from your server, resulting in the same hash mismatches.

**Comment by EpicWink** [comment]
Right, so you're saying I should continue to set the content-type to binary. Fell free to close this issue as won't-fix
