### ISSUE TITLE
Poetry repeadetly re-downloads url dependencies during dependency solving

### ISSUE THREAD

**Issue by Jinior** [python-poetry/poetry#5902]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: ArchLinux with kernel 5.18.5-arch1-1
- **Poetry version**: version 1.2.0b3.dev0
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: [https://gist.github.com/Jinior/3dbc15a9118dc3dd470c3f2c9ad33124](https://gist.github.com/Jinior/3dbc15a9118dc3dd470c3f2c9ad33124)

## Issue

When solving dependencies poetry repeadetly re-downloads url dependencies. As can be seen in the attached pyproject.toml I have a url dependency which is downloaded many times during solving. This not only makes the resolving slower, but also makes it impossible in some cases because the server will give "429 too many tries" error after a while.

When running the `poetry lock -vvv` command the output shows that the package is constantly redownloaded.

I suspect the bug is due to cache misses in the deferred cache of the Provider class.

**Comment by dimbleby** [comment]
duplicate #2415

**Comment by Jinior** [comment]
It is indeed a duplicate. When I initially read #2415 I thought it was about re-downloading a package during installing while it was already downloaded during locking; while my issue is about re-downloading packages during only locking. But I now see that #2415 covers both cases.
