### ISSUE TITLE
Poetry stuck while trying to add pre-commit package

### ISSUE THREAD

**Issue by vmgustavo** [python-poetry/poetry#5905]
- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 20.04.4 LTS
- **Poetry version**: 1.1.13
- **Contents of your pyproject.toml file**: It is a brand new toml file with the only requirement being `python = "3.7.12"`

## Issue

I am simply trying to add pre-commit to a brand new poetry environment and it is getting stuck at the first try. The log below is all that is printed at the highest verbose level.

```bash
❯ poetry add -D pre-commit -vvv
Using virtualenv: /home/use/repos/mydirectory/.venv
PyPI: 169 packages found for pre-commit *
Using version ^2.19.0 for pre-commit

Updating dependencies
Resolving dependencies...
   1: fact: mymodule is 2022.06.2a
   1: derived: mymodule
   1: fact: mymodule depends on pre-commit (^2.19.0)
   1: fact: mymodule depends on pre-commit (^2.19.0)
   1: selecting mymodule (2022.06.2a)
   1: derived: pre-commit (>=2.19.0,<3.0.0)
PyPI: 1 packages found for pre-commit >=2.19.0,<3.0.0
   1: fact: pre-commit (2.19.0) depends on cfgv (>=2.0.0)
   1: fact: pre-commit (2.19.0) depends on identify (>=1.0.0)
   1: fact: pre-commit (2.19.0) depends on nodeenv (>=0.11.1)
   1: fact: pre-commit (2.19.0) depends on pyyaml (>=5.1)
   1: fact: pre-commit (2.19.0) depends on toml (*)
   1: fact: pre-commit (2.19.0) depends on virtualenv (>=20.0.8)
   1: fact: pre-commit (2.19.0) depends on importlib-metadata (*)
   1: selecting pre-commit (2.19.0)
   1: derived: importlib-metadata
   1: derived: virtualenv (>=20.0.8)
   1: derived: toml
   1: derived: pyyaml (>=5.1)
   1: derived: nodeenv (>=0.11.1)
   1: derived: identify (>=1.0.0)
   1: derived: cfgv (>=2.0.0)
PyPI: 89 packages found for importlib-metadata *
PyPI: 63 packages found for virtualenv >=20.0.8
PyPI: 16 packages found for toml *
PyPI: No release information found for pyyaml-3.01, skipping
PyPI: No release information found for pyyaml-3.02, skipping
PyPI: No release information found for pyyaml-3.03, skipping
PyPI: No release information found for pyyaml-3.04, skipping
PyPI: No release information found for pyyaml-3.05, skipping
PyPI: No release information found for pyyaml-3.06, skipping
PyPI: No release information found for pyyaml-3.07, skipping
PyPI: No release information found for pyyaml-3.08, skipping
PyPI: No release information found for pyyaml-3.09, skipping
PyPI: 9 packages found for pyyaml >=5.1
PyPI: 28 packages found for nodeenv >=0.11.1
PyPI: No release information found for identify-0.0.0.dev1, skipping
PyPI: 126 packages found for identify >=1.0.0
PyPI: 7 packages found for cfgv >=2.0.0
   1: selecting cfgv (3.3.1)
   1: selecting pyyaml (6.0)
   1: selecting toml (0.10.2)
   1: selecting nodeenv (1.6.0)
   1: fact: virtualenv (20.14.1) depends on distlib (>=0.3.1,<1)
   1: fact: virtualenv (20.14.1) depends on filelock (>=3.2,<4)
   1: fact: virtualenv (20.14.1) depends on platformdirs (>=2,<3)
   1: fact: virtualenv (20.14.1) depends on six (>=1.9.0,<2)
   1: fact: virtualenv (20.14.1) depends on importlib-metadata (>=0.12)
   1: selecting virtualenv (20.14.1)
   1: derived: importlib-metadata (>=0.12)
   1: derived: six (>=1.9.0,<2)
   1: derived: platformdirs (>=2,<3)
   1: derived: filelock (>=3.2,<4)
   1: derived: distlib (>=0.3.1,<1)
PyPI: 8 packages found for six >=1.9.0,<2
```

The message after I force close the process is this:
```
1: Version solving took 47.674 seconds.
1: Tried 1 solutions.
```

It only tries one solution no matter how long I leave it there processing something. The environment is using Python 3.7.12 and Poetry (1.1.13) is installed using pipx in an environment using Python 3.8.5

I tried changing the versions of the pre-commit package but it still gets stuck at the same spot, I tried forcing different versions of the virtualenv package also and the result is the same.

**Comment by vmgustavo** [comment]
By forcing the versions of six and pre-commit it was able to install, but still poetry shouldn't just freeze when it can't solve the environment versions.

```
six = "<1.9"
pre-commit = "<2.19"
```

**Comment by dimbleby** [comment]
works fine here.  Networking problem?  cf #5881, maybe??

**Comment by vmgustavo** [comment]
Wouldn't it happen in other situations if it was a networking problem? I tried the same thing now and it is still getting stuck. Do you have any suggestions of how to debug to find out if it is a networking problem?

**Comment by dimbleby** [comment]
Sorry, if you've got something weird that only happens on your computer then I duck out!

Clearing the cache is also sometimes worth a try when strange stuff happens: `rm -fr ~/.cache/pypoetry`

**Comment by vmgustavo** [comment]
Clearing the cache fixed it. Thanks
