### ISSUE TITLE
Shouldn't poetry not use latest version of pytest

### ISSUE THREAD

**Issue by cryptable** [python-poetry/poetry#5912]
I'm just wondering if you start a new project with the latest version of poetry, shouldn't it use the latest stable version of pytest (version 7.1.2 at 25/06/2022). I saw it used "^5.2" and install pytest 5.4.3.
I'm using versions:
poetry 1.1.3
python 3.8.10

Non-priority issue, it is not much work to change the toml-file. It is just a best security practice to use the latest stable releases.

**Comment by Secrus** [comment]
This is a `wontfix`. While you are right, Poetry 1.1.x won't get any more releases as 1.2 is right around the corner. This is not the case in the 1.2 version (available as a preview and on the master branch).
