### ISSUE TITLE
Take package version from text file

### ISSUE THREAD

**Issue by gsemet** [python-poetry/poetry#5916]
Hello. Version ing package is pretty easy to do, but automatising is a bit tricky. I use Python-dynamic-versionning but I would like to have a more generic solution based on an external, simple to manage text file.

actually, I have a job in our CI that basically compute the version of the package no matter its language, configured by the version scheme to use (pep440 for Python, semver for npm or Conan packages,…). They all behave the same, taking the distance from the prerious release and creating “prerelease” version. It basically writes a text file with the version to apply.

and what I look for is a simple way to inject it into the package version with poetry and without any additional tool

**Comment by dimbleby** [comment]
`poetry version $(<version.txt)`

**Comment by finswimmer** [comment]
Hello @gsemet,

At Poetry we believe that there should be only one source of truth for package metadata and this one should be the `pyproject.toml`. This is why there are no plans to integrate something, that link to other sources for versions etc.

With the command line `poetry version` you have always the ability to set your version within a CI/CD pipeline. @dimbleby showed a good solution for this already.

fin swimmer
