### ISSUE TITLE
New install of poetry with virtualenvs.in-project=true and virtualenvs.create=false crashes

### ISSUE THREAD

**Issue by christopherpickering** [python-poetry/poetry#5923]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 20.04.4
- **Poetry version**: latest

## Issue

On ubuntu server with python, I'm using poetry to just install the deps from an existing pyproject.toml, not to manage projects.

```bash
# create a virtual env
virtualenv venv

# install poetry
venv/bin/pip install --disable-pip-version-check --quiet poetry

# configure poetry
venv/bin/poetry env use venv/bin/python
venv/bin/poetry config --local virtualenvs.in-project true
venv/bin/poetry config --local virtualenvs.create false
venv/bin/poetry lock --no-update

# install my project
venv/bin/poetry install
```

On a computer where I have used poetry before this works.

On my ubuntu server where I have never created a poetry env I get this error:

```bash
Skipping virtualenv creation, as specified in config file.

  FileNotFoundError

  [Errno 2] No such file or directory: '/home/webapp/.cache/pypoetry/virtualenvs/envs.toml'

  at venv/lib/python3.8/site-packages/tomlkit/toml_file.py:22 in write
      18│             return loads(f.read())
      19│ 
      20│     def write(self, data: TOMLDocument) -> None:
      21│         """Write the TOMLDocument to the file."""
    → 22│         with open(self._path, "w", encoding="utf-8", newline="") as f:
      23│             f.write(data.as_string())
      24│ 
```

I've resolved by error by creating a blank file `/home/webapp/.cache/pypoetry/virtualenvs/envs.toml`, and now poetry works well. I suppose line 22 there should create the file if it doesn't exist instead of failing?

**Comment by christopherpickering** [comment]
Yep 👍🏽  I guess it needs fixed again?

**Comment by PavloPanchyshak** [comment]
I installed the latest Poetry version `curl -sSL https://install.python-poetry.org | python3 -`
And have the same problem `No such file or directory: 'MyHomePath/Library/Caches/pypoetry/virtualenvs/envs.toml'`

**Comment by finswimmer** [comment]
Hello @christopherpickering,

you haven't come back to this issue for a long while. So I assume this is solved in the meantime and I can close this ticket.

Feel free to leave a comment if you disagree.

fin swimmer
