### ISSUE TITLE
`Latest version already installed` but `poetry: command not found`

### ISSUE THREAD

**Issue by danielbellhv** [python-poetry/poetry#5940]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows 10
- **Poetry version**: 1.1.13
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: [gist](https://gist.github.com/danielbellhv/9934acc860f38093474d67afff7be736)

## Issue

Based on [SO post](https://stackoverflow.com/q/72829246/16852041).

Goal: Finally get **Poetry** working in **Git Bash** !

I've literally tried everything you can think of.

- Completely wiped my PC,
- Tried Anaconda and Miniconda versions (installing and uninstalling),
- Setup Conda with Git Bash,
- Experimented with WSL 2 and PowerShell,
- Advanced System Settings - PATH vars,
- Installed and uninstalled Poetry (curl, conda, pip),

Yet, I cannot for the life of me get Poetry working.

---

### Latest

Miniconda3:
```bash
HDS+dabell@PF2DCSXD MINGW64 /
$ conda info

     active environment : None
            shell level : 0
       user config file : C:\Users\dabell\.condarc
 populated config files :
          conda version : 4.12.0
    conda-build version : not installed
         python version : 3.9.12.final.0
       virtual packages : __win=0=0
                          __archspec=1=x86_64
       base environment : C:\Users\dabell\Miniconda3  (writable)
      conda av data dir : C:\Users\dabell\Miniconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\dabell\Miniconda3\pkgs
                          C:\Users\dabell\.conda\pkgs
                          C:\Users\dabell\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\dabell\Miniconda3\envs
                          C:\Users\dabell\.conda\envs
                          C:\Users\dabell\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.12.0 requests/2.27.1 CPython/3.9.12 Windows/10 Windows/10.0.19041
          administrator : False
             netrc file : None
           offline mode : False
```

Poetry:
```bash
HDS+dabell@PF2DCSXD MINGW64 /
$ curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
Retrieving Poetry metadata

This installer is deprecated. Poetry versions installed using this script will not be able to use 'self update' command to upgrade to 1.2.0a1 or later.
Latest version already installed.

HDS+dabell@PF2DCSXD MINGW64 /
$ export PATH="$HOME/.poetry/bin:$PATH"

HDS+dabell@PF2DCSXD MINGW64 /
$ poetry self update
bash: poetry: command not found
```

**Comment by danielbellhv** [comment]
Trying `conda install -c conda-forge poetry`

**Comment by dimbleby** [comment]
I don't know why this is different from #5930: but you are again using the deprecated installer and no-one is going to be interested in making fixes to that.

**Comment by danielbellhv** [comment]
@dimbleby Awesome, ok. So what steps should I take to get Poetry working?

**Comment by dimbleby** [comment]
Clean up whatever mess you have gotten yourself into, and start over, using the new installer.

You are going to have to figure out for yourself what "whatever mess you have gotten yourself into" means.  

There will be clues in the errors that you are seeing: for instance you could read the `get-poetry.py` script to learn why it thinks that poetry is already installed - it must be finding some file or directory somewhere, and you should remove that.

Again, best of luck: but please stop raising issues against the old installer, and no more @'s please.

**Comment by danielbellhv** [comment]
Could you link me the latest installer, please?

I've been using these commands, from these sources:
- `conda install -c conda-forge poetry` [source](https://anaconda.org/conda-forge/poetry)
- `curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python(3)` [source](https://python-poetry.org/docs/#osx--linux--bashonwindows-install-instructions)
- `(Invoke-WebRequest -Uri https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py -UseBasicParsing).Content | python(3)` [source](https://python-poetry.org/docs/#windows-powershell-install-instructions)

Supposedly, `pip install poetry` is **not** recommended.

**Comment by gunungpw** [comment]
Please read the docs first for recommended way to install poetry, this link for [Latest Official Installer](https://python-poetry.org/docs/master/#installing-with-the-official-installer)

**Comment by mkniewallner** [comment]
There's quite a lot of issues where people use `get-poetry.py`. I feel that the deprecated message in https://python-poetry.org/docs/#installation may not be enough.

Maybe we should update the installation instructions to use `install-poetry.py` or https://install.python-poetry.org instead of `get-poetry.py`?
We do have a message specifying that `get-poetry.py` is deprecated, but I'm not sure that people all read that, given the number of issues still mentioning it.

Additionally, while the script specifies that it is deprecated, it [doesn't specify](https://github.com/python-poetry/poetry/blob/720c3589be9443e9ec80424cc5113d98974b827d/get-poetry.py#L470-L477) the recommend way to install Poetry, so I feel that this would also help.

**Comment by dimbleby** [comment]
@mkniewallner cf #5877

**Comment by mkniewallner** [comment]
Made https://github.com/python-poetry/poetry/pull/5944 and its companion https://github.com/python-poetry/poetry/pull/5945 to recommend installation through https://install.python-poetry.org/ both in `1.1` documentation and `get-poetry.py`.

**Comment by danielbellhv** [comment]
I installed **Poetry 1.1.13**, yet `poetry --version Poetry 1.0.10`.
**WSL 2:**
```
danielbellhv@PF2DCSXD:/mnt/c/Users/dabell$ curl -sSL https://install.python-poetry.org | python3 -
Retrieving Poetry metadata

# Welcome to Poetry!

This will download and install the latest version of Poetry,
a dependency and package manager for Python.

It will add the `poetry` command to Poetry's bin directory, located at:

/home/danielbellhv/.local/bin

You can uninstall at any time by executing this script with the --uninstall option,
and these changes will be reverted.

Installing Poetry (1.1.13): Creating environment
The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt install python3.8-venv

You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.

Failing command: ['/home/danielbellhv/.local/share/pypoetry/venv/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']

danielbellhv@PF2DCSXD:/mnt/c/Users/dabell$ apt install python3.8-venv
E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?
danielbellhv@PF2DCSXD:/mnt/c/Users/dabell$ sudo apt install python3.8-venv
[sudo] password for danielbellhv:
Sorry, try again.
[sudo] password for danielbellhv:
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  python3.8-venv
0 upgraded, 1 newly installed, 0 to remove and 114 not upgraded.
Need to get 5448 B of archives.
After this operation, 27.6 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 python3.8-venv amd64 3.8.10-0ubuntu1~20.04.4 [5448 B]
Fetched 5448 B in 1s (5333 B/s)
Selecting previously unselected package python3.8-venv.
(Reading database ... 38402 files and directories currently installed.)
Preparing to unpack .../python3.8-venv_3.8.10-0ubuntu1~20.04.4_amd64.deb ...
Unpacking python3.8-venv (3.8.10-0ubuntu1~20.04.4) ...
Setting up python3.8-venv (3.8.10-0ubuntu1~20.04.4) ...
danielbellhv@PF2DCSXD:/mnt/c/Users/dabell$ curl -sSL https://install.python-poetry.org | python3 -
Retrieving Poetry metadata

# Welcome to Poetry!

This will download and install the latest version of Poetry,
a dependency and package manager for Python.

It will add the `poetry` command to Poetry's bin directory, located at:

/home/danielbellhv/.local/bin

You can uninstall at any time by executing this script with the --uninstall option,
and these changes will be reverted.

Installing Poetry (1.1.13): Done

Poetry (1.1.13) is installed now. Great!

You can test that everything is set up by executing:

`poetry --version`

danielbellhv@PF2DCSXD:/mnt/c/Users/dabell$ poetry --version
Poetry version 1.0.10
```

I then added to `PATH`:.
**Both in WSL 2 and Git Bash:**
```
PATH=$PATH:%APPDATA%\pypoetry\Scripts\poetry
```

Failed to recognise:
**Git Bash:**
```
$ poetry install
bash: poetry: command not found
```

WSL 2 refuses to work with conda ;(

**Comment by neersighted** [comment]
Configuration issue/issues with the deprecated installer -- use the supported install methods and follow the instructions to add Poetry to your PATH.

**Comment by justinTM** [comment]
still not working:

```dockerfile
# Dockerfile
FROM python:3.8-alpine

SHELL [ "/bin/sh", "-c" ]

RUN curl -sSL https://install.python-poetry.org | python3 - \
    && export PATH="/root/.local/bin:$PATH" \
    && poetry --version 

COPY . /app
WORKDIR /app

CMD [ "sh" ]
```

build the Dockerfile run within the container:

```console
65746ffa161a:/workspaces/XXXXX# poetry
/bin/ash: poetry: not found

65746ffa161a:/workspaces/XXXXX# curl -sSL https://install.python-poetry.org | python3 -
Retrieving Poetry metadata

The latest version (1.2.2) is already installed.
```

## Problem
running `export VAR=value` in Dockerfile does not persist into the image.

## Solution
```Dockerfile
ENV PATH="/root/.local/bin:$PATH"
```

## Question
if the install script can find poetry, why can't the install script just fix it? `pip install poetry` isn't recommended but yet it works fine without any PATH fixing...

**Comment by clintonroy** [comment]
Please look at the output of the build:
```
/bin/sh: curl: not found
/bin/sh: poetry: not found
```

**Comment by justinTM** [comment]
@clintonroy can you please be more specific?

> Please look at the output of the build:
> 
> ```
> 
> /bin/sh: curl: not found
> 
> /bin/sh: poetry: not found
> 
> ```

**Comment by chambliss** [comment]
In case this helps anyone: I had a similar error to OP (trying to use new installer, it claimed latest was already installed and exited, but then `poetry` returned command not found). I had installed poetry > a year ago and hadn't used it since, and could not figure out how to fully uninstall it today.

Eventually I found the `~/Library/Application Support/pypoetry` folder and removed it manually, then the installer started working.

**Comment by Rubauliant** [comment]
I had the same issue on wsl2. 

Interestingly, they have written where the source files should be installed, but couldn't  find exactly where on their documentation it has been written, only found by google snippet:

![image](https://github.com/python-poetry/poetry/assets/19616931/ddc5d8a0-ab1f-4241-bc87-9b49fef55a3a)

So adding the source path to PATH solves:

export PATH=$PATH:~/.local/share/pypoetry

this is also printed when [installing trough curl](https://python-poetry.org/docs/#installing-with-the-official-installer:~:text=Linux%2C%20macOS%2C%20Windows%20(WSL))
