### ISSUE TITLE
no uninstall available, no get-poetry.py

### ISSUE THREAD

**Issue by scosm** [python-poetry/poetry#5941]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

I'm trying to uninstall poetry, but the documentation appears to be incorrect.
(I'm uninstalling in order to re-install by a different method.)
I'm on Windows 10. I installed with the PowerShell command. My Windows user is only a standard user, not an admin.
This method seems to invoke admin mode on the machine, so my poetry was installed under another account, which was admin privilege. But I don't want it there. So, I'm trying to uninstall, so I can re-install with pip.

The docs say do this: python get-poetry.py --uninstall
This fails, because get-poetry.py is not in the path, and not in the poetry path.
I searched in the poetry directory, but get-poetry.py is not anywhere there. There is no etc directory created too, on Windows.
So, there is no script for uninstalling.
That's painful, because it looks like I have to clean up everything manually, if I even guess right as to what/how poetry was installed.
Is there a working uninstall somewhere?
Could you update the documentation at the site?
Thanks.

**Comment by finswimmer** [comment]
Hello @scosm,

you have to download `get-poetry.py` first, exactly the same way you are doing this for installing. As a oneliner the uninstall looks like this:

```
curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py |python - --uninstall
```

fin swimmer

**Comment by scosm** [comment]
Thanks. That helps. But fyi, it fails. The file that curl produces is not the script itself, but a result file. So, that shows up as syntax errors, because it's not a valid Python file at all. So, I just used my browser to copy and save the raw .py file. But then this fails:

SyntaxError: Non-UTF-8 code starting with '\xff' in file C:\users\ScobieSmith'sAdminAc\.poetry\lib\poetry\installation\get-poetry.py on line 2, but no encoding declared; see https://python.org/dev/peps/pep-0263/ for details

So, I'm debugging your uninstall script. Not good. And this shouldn't have happened in the first place, but the PowerShell install method uses admin mode, which screwed me up, because I'm installing for a standard user. I'm losing confidence in this tool, because installation/uninstallation should be smoother and more seamless. Debugging your install script???

**Comment by scosm** [comment]
Ok, despite my griping, I got it to work. The curl line won't work. You to download the file maybe with the browser. Make sure it is saved as UTF-8, and you can do this using Notepad on Windows. Save it in some other folder, not in .poetry... or else there will be an error that a file or folder is being used by another process. So, just save it in the user's top-level folder. Then in the admin-mode PowerShell prompt, navigate to that folder and run: python get-poetry.py --uninstall

That worked. In general, (un)install scripts should both be part of a distribution, and they should just work.

Thanks.
