### ISSUE TITLE
"poetry add" fails to update constraint for packages with a capitalized name

### ISSUE THREAD

**Issue by shaib** [python-poetry/poetry#5948]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Debian testing (bookworm=12)
- **Poetry version**: 1.1.13 (this was present in 1.2.0b1 but seems to be solved in 1.2.0b2)
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/shaib/3834afb7b1bddbb9f2fc95db130b329b

## Issue
It seems that, when a package specifies its name in the metadata as capitalized, poetry fails to understand that the capitalized and lower-case names refer to the same package, for the sake of updating the constraint; it then has two constraints for the package, which it does realize are conflicting -- and so, fails to install.

This issue applies to some very popular packages, such as [Django](https://pypi.org/project/Django/) and [Pillow](https://pypi.org/project/Pillow/).

Workaround: Edit `pyproject.toml` manually.

**Comment by mkniewallner** [comment]
Hi, the `1.1` branch is unmaintained, since `1.2` is around the corner and all focus is currently on it, in order to get `1.2.0` released as soon as possible and have a stable version that users of `1.1` could switch to.

Since this is fixed in `1.2.0b2`, as you correctly mentioned, closing this issue.

**Comment by shaib** [comment]
Ok, thanks for your attention.
