### ISSUE TITLE
What is the effect of `at` operator?

### ISSUE THREAD

**Issue by a-takahashi223** [python-poetry/poetry#5953]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: CentOS Stream
- **Poetry version**: 1.1.13
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: None

## Issue

[The documentation](https://python-poetry.org/docs/master/dependency-specification/#using-the--operator) says

> When adding dependencies via poetry add, you can use the @ operator. This is understood similarly to the == syntax, but also allows prefixing any specifiers that are valid in pyproject.toml.

And it shows the example that `poetry add django@^4.0.0` will add the line `Django = "^4.0.0"` to `pyproject.toml`. But what version is installed (written to `poetry.lock`) is not shown.
As "`@` operator is understood similarly to the == syntax", django 4.0.0 is expected to be installed. But no.

```
$ poetry show django
name         : django
version      : 4.0.6
```

This result seems to be the same as `poetry add django^4.0.0`. What is the difference? What is the effect of `@` operator?

#3142 and #5136 is the similar questions, and #5822 says it solved them, but I can't understand the effect of `@` operator by reading the documentation.

**Comment by a-takahashi223** [comment]
I tried some other patterns.

`django@4.0.0` is the same as `django==4.0.0`.
`django@latest` add the dependency `django = "^4.0.6"` for now. `django^latest` is not allowed.
`django@^latest` is not allowed.

So in conclusion, "@" operator is useful only in the form of "@latest"? "Prefixing any specifiers that are valid in pyproject.toml" (like "@^") seems to have the same effect as the specifier itself ("^").

**Comment by finswimmer** [comment]
Hello @a-takahashi223,

I think you overlook the `^` in `django@^4.0.0`. The caret operator is described in the [docs](https://python-poetry.org/docs/dependency-specification/#caret-requirements). In this case `django@^4.0.0` would be equal to `django>=4.0.0,<5.0`

fin swimmer

**Comment by a-takahashi223** [comment]
so `django>=4.0.0,<5.0` is equal to `django^4.0.0`, then `django@^4.0.0` is equal to `django^4.0.0`?

**Comment by Secrus** [comment]
The `@` operator is described in [docs](https://python-poetry.org/docs/master/dependency-specification/#using-the--operator) for version 1.2, as this is the main focus right now.
