### ISSUE TITLE
sdist builds fail if files are out-of-tree

### ISSUE THREAD

**Issue by antdking** [python-poetry/poetry#5960]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Fedora 36
- **Poetry version**: 1.1.13
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/antdking/3102d627511e517bcfefb803e8a9f8fb#file-pyproject-toml

## Issue

Currently, `sdist` builds don't allow drawing in files from out-of-tree, either with an explicit reference (`readme = "../../README.md"`), or with a symlink.

Our usecase is to use the repo's README for one or more of the projects.

`wheel` builds work as I expect, bundling the out-of-tree files.

Log output: https://gist.github.com/antdking/3102d627511e517bcfefb803e8a9f8fb#file-output-py

```
 ValueError

  '/home/anthony/experiments/monorepo/README.md' is not in the subpath of '/home/anthony/experiments/monorepo/projects/pyproject' OR one path is relative and the other is absolute.
```

**Comment by finswimmer** [comment]
Hello @antdking,

an `sdist` is literally a source distribution. It must be possible to unpack the file and build a `wheel` from there. This is not possible if there are files outside of the project folder.

fin swimmer
