### ISSUE TITLE
Automatically pick up installed python versions

### ISSUE THREAD

**Issue by Diggsey** [python-poetry/poetry#5968]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

I shouldn't have to specify the full path to the python executable when setting up a new project. `py -0p` will happily locate all my installed python versions, so poetry should be able to use that.

**Comment by radoering** [comment]
There is a draft PR to use `pythonfinder` for that purpose. Have a look at #5778.

Duplicates: #3520, #2117
