### ISSUE TITLE
Breaking change in Warehouse breaks poetry lock file creation

### ISSUE THREAD

**Issue by cyraxjoe** [python-poetry/poetry#5970]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **Linux/Debian bookworm**: 
- **1.2.0b2**: 
- **Sample [pyproject](https://gist.github.com/cyraxjoe/9fb478d87ef69bef839f771e0f1561bf)**: 

## Issue

The warehouse project (backend of pypi.org) applied a [breaking change ](https://github.com/pypi/warehouse/pull/11775) that affects `poetry lock` the `releases` key is no longer present in the responses, required for the [pypi_repository](https://github.com/python-poetry/poetry/blob/master/src/poetry/repositories/pypi_repository.py#L207) implementation.

It can be easily verified by removing the local cache and inspecting the generated lock file, it would have an empty `metadata.files` property, something like: 
```
[[package]]
name = "beautifulsoup4"
version = "4.11.1"
description = "Screen-scraping library"
category = "main"
optional = false
python-versions = ">=3.6.0"

[package.dependencies]
soupsieve = ">1.2"

[package.extras]
html5lib = ["html5lib"]
lxml = ["lxml"]

[[package]]
name = "soupsieve"
version = "2.3.2.post1"
description = "A modern CSS selector implementation for Beautiful Soup."
category = "main"
optional = false
python-versions = ">=3.6"

[metadata]
lock-version = "1.1"
python-versions = "^3.10"
content-hash = "36fc53f6339e375f6295378c7a8ecea11e3a04ba0adcbfa7aeb812e30500aad0"

[metadata.files]
beautifulsoup4 = []
soupsieve = []
```

**Comment by Kurt-von-Laven** [comment]
I can confirm that this issue is also affecting Poetry 1.1.13 as it is taking down all of our builds.

**Comment by novotl** [comment]
👍 We're seeing the same with Poetry 1.1.8

**Comment by dimbleby** [comment]
I suspect a lot of people are about to learn a hard lesson about the dangers of relying on public repositories....

```diff
diff --git a/src/poetry/repositories/pypi_repository.py b/src/poetry/repositories/pypi_repository.py
index 0e5beab6..142b29d8 100644
--- a/src/poetry/repositories/pypi_repository.py
+++ b/src/poetry/repositories/pypi_repository.py
@@ -204,7 +204,7 @@ class PyPiRepository(HTTPRepository):
         )

         try:
-            version_info = json_data["releases"][version]
+            version_info = json_data["urls"]
         except KeyError:
             version_info = []
```
looks like it should fix things on master.

**Comment by mkniewallner** [comment]
https://github.com/python-poetry/poetry/pull/5972 draft for now, because there may be other places where `releases` is used, don't know the codebase well enough.
Tested locally, and it seems to work fine.

Also backported the change for 1.1 in https://github.com/mkniewallner/poetry/commits/fix/fix-releases-key-pypi-repository-1.1

**Comment by finswimmer** [comment]
Thanks a lot everyone for reporting, debugging and starting a PR :+1:  Will have a look at your PR @mkniewallner

**Comment by Natim** [comment]
It seems that Poetry 1.2.2 fixed it but 1.3.1 is back with the same issue, any idea why?

**Comment by finswimmer** [comment]
@Natim: Please open a new issue with steps to reproduce if you encounter any problems (I don't have any).

**Comment by Kurt-von-Laven** [comment]
We haven't encountered this issue on Poetry 1.3.1 either.

**Comment by Natim** [comment]
Sorry, you are both right, the issue is not related, the poetry.lock file structure changed in between 1.2.2 and 1.3.1 which made disappear the metadata section, but the hashes are correctly computed in the package file section in 1.3.1/
