### ISSUE TITLE
can't update poetry (pipx installation)

### ISSUE THREAD

**Issue by scosm** [python-poetry/poetry#5978]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- Windows 10
- 1.1.13
- https://gist.github.com/scosm/ce00b9084021892d3d6b5a0e4c46b717

I am also using pyenv (2.54.11). And in this repo's environment, it is using Python 3.8.6.

## Issue
I installed poetry using pipx. (Reason: Using the PowerShell install script in my environment will install poetry under the local admin user account, which is different from my own standard-user account. So, I used pipx instead.)

But now I cannot update poetry. Running:

poetry update
or
poetry self update
fails.

**poetry update:**

Updating dependencies
Resolving dependencies...

  RepositoryError

  401 Client Error: Unauthorized for url: https://us-west2-python.pkg.dev/thankful-stingray-e342/staas-python-repository/simple/mock/

  at ~\.local\pipx\venvs\poetry\lib\site-packages\poetry\repositories\legacy_repository.py:393 in _get
      389│             if response.status_code == 404:
      390│                 return
      391│             response.raise_for_status()
      392│         except requests.HTTPError as e:
    → 393│             raise RepositoryError(e)
      394│
      395│         if response.status_code in (401, 403):
      396│             self._log(
      397│                 "Authorization error accessing {url}".format(url=response.url),

Or...

**poetry self update:**

RuntimeError

  Poetry was not installed with the recommended installer. Cannot update automatically.

  at ~\.local\pipx\venvs\poetry\lib\site-packages\poetry\console\commands\self\update.py:389 in _check_recommended_installation
      385│         current = Path(__file__)
      386│         try:
      387│             current.relative_to(self.home)
      388│         except ValueError:
    → 389│             raise RuntimeError(
      390│                 "Poetry was not installed with the recommended installer. "
      391│                 "Cannot update automatically."
      392│             )
      393│

So, I don't know if there is any way to remediate my installation, which was done using pipx. Or maybe there is a way to update manually, since it says it can't update "automatically".

**Comment by dimbleby** [comment]
> I installed poetry using pipx

then upgrade it using pipx too

**Comment by mkniewallner** [comment]
The error message quite explicitly says that `poetry self update` won't work, since you didn't install Poetry with the recommended installer.

`pipx upgrade poetry` and you should be good to go (documented [here](https://pypa.github.io/pipx/docs/#pipx-upgrade)).
