### ISSUE TITLE
Installing poetry using python2.7 in docker image

### ISSUE THREAD

**Issue by elados93** [python-poetry/poetry#5989]
- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: MacOS Monterey 12.4
- **Poetry version**: 1.1.14
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue
I'm trying to write a `Dockerfile` for my setup, installing poetry using python2.7.18. I'm installing poetry the recommended way which according to docs should support python2.7 & 3.5. Lately, I encountered `UnicodeDecodeError` & noticed https://github.com/python-poetry/poetry/issues/3672 so I added `PYTHONIOENCODING` although it didn't seems to help.

### Dockerfile
```
# latest python2 version
FROM python:2.7.18-slim

# pin poetry version
ENV POETRY_VERSION="1.1.14"

# https://github.com/python-poetry/poetry/issues/3672
ENV PYTHONIOENCODING=utf8

# install poetry using official website recomended way
RUN apt-get update; apt-get install curl -y
RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
```

### Build Error
```
 => ERROR [3/8] RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -               1.1s
------                                                                                                                                  
 > [3/8] RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -:                          
#6 1.031 Retrieving Poetry metadata                                                                                                     
#6 1.032 Traceback (most recent call last):                                                                                             
#6 1.032   File "<stdin>", line 1117, in <module>                                                                                       
#6 1.032   File "<stdin>", line 1113, in main
#6 1.032   File "<stdin>", line 351, in run
#6 1.032   File "<stdin>", line 414, in get_version
#6 1.032 UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 20: ordinal not in range(128)
```
 what am I missing here?

Thanks.

**Comment by dimbleby** [comment]
AFAICS this has been broken since https://github.com/python-poetry/poetry-core/commit/964ed3194875b0e0ec74aeb689566de219a78539, which seems infeasibly long ago.

It's choking on the `é` of `"Sébastien Eustace"`.

I don't know whether anyone cares enough about the old installer and python 2 to do anything about this - I know that I don't - so probably you will need either to find some other way to install poetry, or to install it in a python3 environment.

Note that the poetry environment should be independent of the managed environment and eg a python3 poetry can still manage a python2 project.

**Comment by mathieu-lemay** [comment]
I have the same issue, appeared a few days ago. This is how I fixed it: https://github.com/mathieu-lemay/python-poetry/blob/47a00fc43235396c8f537c3c4dbc2bd9ada3dcd0/2.7/Dockerfile#L9
