### ISSUE TITLE
Dev dependency get locked as main dependency when constraint is a list

### ISSUE THREAD

**Issue by ISO-morphism** [python-poetry/poetry#599]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 18.10
- **Poetry version**: 0.12.5
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/ISO-morphism/1ffe8786755057778b00b845d2d471fc

## Issue

While perusing the Poetry source code I stumbled across [this block](https://github.com/sdispater/poetry/blob/35044652360e9518cb09c79f738c5a9597928b43/poetry/poetry.py#L152) that looked like it could cause a bug. When a member of `dev-dependencies` has multiple constraints expressed as a list (like [this](https://gist.github.com/ISO-morphism/1ffe8786755057778b00b845d2d471fc#file-poetry-pyproject-toml-L61)), `poetry lock` will lock it as a `main` dependency (like [this](https://gist.github.com/ISO-morphism/d6d9c9c2e8f7aefef0376e52ffa58fb0#file-poetry-poetry-lock-L367)).

When reading in a `.pyproject.toml` file, Poetry will internally [add](https://github.com/sdispater/poetry/blob/master/poetry/packages/package.py#L234) a [Dependency](https://github.com/sdispater/poetry/blob/master/poetry/packages/dependency.py#L18) to a [Package](https://github.com/sdispater/poetry/blob/35044652360e9518cb09c79f738c5a9597928b43/poetry/packages/package.py#L28) that gets [initialized](https://github.com/sdispater/poetry/blob/35044652360e9518cb09c79f738c5a9597928b43/poetry/poetry.py#L109) from reading a `pyproject.toml` [file](https://github.com/sdispater/poetry/blob/35044652360e9518cb09c79f738c5a9597928b43/poetry/poetry.py#L96).

### Steps to reproduce

1. `$ git clone https://github.com/sdispater/poetry.git`
2. Add `keyring = ["16.0.0", "16.0.0"]` to `[tool.poetry.dev-dependencies]` in `pyproject.toml`
3. `$ poetry lock`
4. Search `poetry.lock` for `keyring`, see that `category = "main"`

or in one line:

```sh
git clone https://github.com/sdispater/poetry.git && \
cd poetry && \
mv pyproject.toml pyproject.toml.bak && \
sed -e '/\[tool.poetry.dev-dependencies\]/a\' -e 'keyring = ["16.0.0", "16.0.0"]' pyproject.toml.bak > pyproject.toml && \
poetry lock && \
grep -C3 'name = "keyring"' poetry.lock
```

produces for me:

```sh
$ git clone https://github.com/sdispater/poetry.git && \
> cd poetry && \
> mv pyproject.toml pyproject.toml.bak && \
> sed -e '/\[tool.poetry.dev-dependencies\]/a\' -e 'keyring = ["16.0.0", "16.0.0"]' pyproject.toml.bak > pyproject.toml && \
> poetry lock && \
> grep -C3 'name = "keyring"' poetry.lock
Cloning into 'poetry'...
remote: Enumerating objects: 73, done.
remote: Counting objects: 100% (73/73), done.
remote: Compressing objects: 100% (57/57), done.
remote: Total 7105 (delta 26), reused 39 (delta 14), pack-reused 7032
Receiving objects: 100% (7105/7105), 7.85 MiB | 1.22 MiB/s, done.
Resolving deltas: 100% (4703/4703), done.
Updating dependencies
Resolving dependencies... (1.4s)


Writing lock file

[[package]]
category = "main"
description = "Store and access your passwords safely."
name = "keyring"
optional = false
python-versions = ">=2.7"
version = "16.0.0"
```

This particular example also violates the `!!!note` found in the [docs](https://github.com/sdispater/poetry/blob/master/docs/docs/versions.md#multiple-constraints-dependencies) in that identical constraints do not cause an error.

**Comment by ISO-morphism** [comment]
I was mistaken on the **Poetry version**, this issue was found on the latest master but also exists for the `0.12.5` tag.

**Comment by azag0** [comment]
It also happens with a git dependency with a specified commit.

**Comment by zyv** [comment]
Also got hit by this one, using git commit pinning.

**Comment by mm-matthias** [comment]
It seems the code here https://github.com/sdispater/poetry/blob/c497a5d836d72395bda8476edb24bacc698ea9b7/poetry/packages/package.py#L251 does not forward `category` to `VCSDependency`. Actually `VCSDependency` subclasses `Dependency`, but does not have a `category` parameter in __init__() as the other dependency classes have. Changing this is likely trivial, but I wonder:

- which consequences does changing this behaviour have for existing projects? Does poetry have some kind of backwards-compatibility policy here?
- is there a reason why VCSDependency does not have this parameter while the other dependency classes do have it?

@zyv fyi

**Comment by drunkwcodes** [comment]
@mm-matthias 

1. Just do it if it's a bug.
2. No. What it missed is passing a **kwargs to `super().__init__()`.

**Comment by jimbo1qaz** [comment]
Oh I'm working on a "fix" locally... am I racing against anyone else?

@drunkwcodes are you a contributor or a user like me?

Do I add `**kwargs` to `VCSDependency.__init__()`, and *not* add `category="main",`?

**Comment by drunkwcodes** [comment]
@jimbo1qaz A user just had a glance at this.

**Comment by jimbo1qaz** [comment]
will my PR be reviewed and likely accepted? Should I ask discussions in this issue or PR?

do I remove `VCSDependency(optional=False)` and rely on **kwargs for that argument as well?

**Comment by drunkwcodes** [comment]
@jimbo1qaz I will make a PR if you are not working on this.

No. I will just add it and don't remove anything.

**Comment by jimbo1qaz** [comment]
is this still broken? i didn't check

**Comment by AndrewPix** [comment]
@jimbo1qaz Yes, this is still happening with a git dependency with a specified commit

**Comment by jimbo1qaz** [comment]
Fixed in https://github.com/python-poetry/poetry/pull/1725. This issue should be closed.

**Comment by finswimmer** [comment]
Thanks a lot for coming back and reporting it as closed :+1:
