### ISSUE TITLE
Add transitive dependency pinning.

### ISSUE THREAD

**Issue by busykoala** [python-poetry/poetry#5995]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request
It would be awesome if there was a way of pinning transitive dependencies without needing to add them as a direct dependencies.

My most common use case is that there is a vulnerability in a transitive dependency which needs to be fixed very fast and even before the maintainers of the third party package react to the issue.

An example how this could look like is shown in [this yarn feature](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/).

**Comment by dimbleby** [comment]
duplicate #4991

**Comment by mkniewallner** [comment]
Closing as duplicate of https://github.com/python-poetry/poetry/issues/4991.
