### ISSUE TITLE
lock --no-update leads to unnecessary updates

### ISSUE THREAD

**Issue by westandskif** [python-poetry/poetry#5996]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS 12.4
- **Poetry version**: 1.1.14
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: see below
```
# pyproject.toml
sentry-sdk = {version = "~1", extras = ["django", "celery", "sqlalchemy"]}

# prev poetry.lock
 [[package]]
 name = "sentry-sdk"
 version = "1.6.0"

# new poetry.lock
 [[package]]
 name = "sentry-sdk"
 version = "1.7.0"
```

## Issue
Hello everyone! Thanks for the great tool!
I'm having a question, whether it's a bug that poetry updates libraries even though I pass ``--no-update`` option like this:
``poetry lock --no-update -vv``

My assumption is that once you pass this option, no versions should be changed except ones, which have to be changed because of libraries, added or changed in ``pyproject.toml``

**Comment by dimbleby** [comment]
already fixed in latest beta, this can be closed

**Comment by westandskif** [comment]
This is great, thank you!
