### ISSUE TITLE
Poetry install doesn't work behind corporate firewall/proxy

### ISSUE THREAD

**Issue by jarrod817** [python-poetry/poetry#6001]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows 10
- **Poetry version**: 1.1.14
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: File is the basic created file from running poetry init and using the wizard to add pandas. 

## Issue
In researching this issue, I found many similar issues where users were needing to use private repos. To be clear, I don't have a private repo and am using the standard python built in pip going to pypi. Due to my corporate proxy/firewall, when I use pip I have to use --trusted-host files.pythonhosted.org in order not to get a SSL error.  Thinking maybe poetry under the hood is running pip install pandas, I tried to use poetry install --trusted-host files.pythonhosted.org, which didn't work. I 
then installed the package pip_system_certs which allows me to be able to use the standard "pip install pandas" successfully (no --trusted-host anymore). However when using poetry install I get the same SSL error. 

I have tried a suggestion that I found to take the cert from a HTTPS site and save the pem key in poetry certifi directory with no luck.

**Comment by BrenoJesusFernandes** [comment]
Same issue here, any luck with a new approach?

**Comment by jarrod817** [comment]
No, I couldn't find anything to get around it.

**Comment by Mazyod** [comment]
The docs point to the following recommendation, although I haven't tried it yet:

> The value of certificates.<repository>.cert can be set to false if certificate verification is required to be skipped. This is useful for cases where a package source with self-signed certificates are used.

```
poetry config certificates.foo.cert false
```

https://python-poetry.org/docs/repositories/#certificates

**Comment by Ninpo** [comment]
https://github.com/python-poetry/poetry/issues/6670 issue being tracked here

**Comment by yhyu13** [comment]
https://github.com/python-poetry/poetry/issues/3748 from this thread, 

can confirm only `pip config set global.proxy xxx` works for petry, env var all not working
