### ISSUE TITLE
Please add option to 'poetry add' that will set 'develop' to true

### ISSUE THREAD

**Issue by rzuckerm** [python-poetry/poetry#6002]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

It would be nice if `poetry add` had a command line option that would set `develop` to `true`. For example:
```
poetry add ./local-path --develop
```

**Comment by rzuckerm** [comment]
It looks like this option is already available in 1.2 with the `-e/--editable` option. However, it would be nice if this were backported to 1.1.

**Comment by Secrus** [comment]
There won't be a backport for sure. The team is working on releasing Poetry 1.2 ASAP and no new releases of the 1.1 version are planned  (even 1.1.14 was not planned, but PyPI changes forced our hand).
