### ISSUE TITLE
[Question] Override source repository through environment variable or config

### ISSUE THREAD

**Issue by serpa-dystematic** [python-poetry/poetry#6004]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Issue

I'm running `poetry` during the CI process and I need to override the source repository from where it installs the dependencies without updating the URL on `pyproject.toml`.

I've tried some environment variables as described [here](https://python-poetry.org/docs/configuration/#using-environment-variables) but without success.

Is is possible to do it? If yes, how would I override this source:
```
    [[tool.poetry.source]]
      default = true
      name = "companypypi"
      url = "https://nexus.company.com/repository/pypi-company/simple"
```

I've tried:
```
POETRY_REPOSITORIES_COMPANYPYPI_URL
POETRY_TOOL_POETRY_SOURCE_COMPANYPYPI_URL
```

Any help is appreciated!
Thanks

**Comment by vergenzt** [comment]
Related to #4880 (was looking for this, but found that issue first)

Browsing the source, it look like the `default` attribute on a repository can't currently be set from the environment; [`Config._get_environment_repositories`](https://github.com/python-poetry/poetry/blob/bf0dbc076be94b4709981c902e6f2d613240b56d/src/poetry/config/config.py#L190-L202) only populates a "url" attribute. Checking for environment variables to set "default" (and maybe also "secondary", for completeness) attribute(s) on environment-defined repositories seems to me like the proper resolution to this.

**Comment by dimbleby** [comment]
seems like this duplicates one or both of #4880, #5992

**Comment by abn** [comment]
[Sources](https://python-poetry.org/docs/master/repositories/#package-sources) are not designed to be overridden via the environment variables.

The `POETRY_REPOSITORIES_XXX_URL` environment variable is primarily intended to configure [publishable repositories](https://python-poetry.org/docs/master/repositories/#publishable-repositories).

**Comment by arichtman** [comment]
I have a similar issue, I'm attempting to build containers that have dependencies in our company PyPi repository (which requires authentication). I'm trying *not* to bake any credentials into our images. A build-time environment variable would have been handy for that. I suppose we could use the imperative commands + build arguments to set the config then remove it before ending the `RUN` command and hopefully keeping it out of the layer commit?

**Comment by brandon-leapyear** [comment]
@arichtman you can do this today:
```bash
poetry source add --default foo https://pypi-internal.company.com
export POETRY_HTTP_BASIC_FOO_USERNAME=...
export POETRY_HTTP_BASIC_FOO_PASSWORD=...
poetry lock --no-update
```
This uses env vars for auth, but puts the source into `pyproject.toml`. See https://github.com/python-poetry/poetry/issues/5958 for the discussion on configuring the source outside `pyproject.toml`

**Comment by arichtman** [comment]
Thanks! I have been successfully using the source in `pyproject.toml` and environment variables for authentication and multi-stage builds to keep credentials out of the final image. I'll keep an eye on the other issues to see what emerges that might suit CI use cases better.
Once again thanks for your time!
