### ISSUE TITLE
[Question] Is it possible to specify python distribution (universal2/intel) on MacOS?

### ISSUE THREAD

**Issue by Mr-Milk** [python-poetry/poetry#6005]
I'm running on an intel mac but i want to use the universal2 python distribution, by default poetry seems to download the intel-only distribution of Python when available. Is it possible to change this behavior?

- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

**Comment by ibaranov-t1a** [comment]
@Mr-Milk how did you solve this problem by the way?

**Comment by Mr-Milk** [comment]
Poetry doesn't handle Python interpreter, it uses the active one. You can just download a specific Python distribution and configure poetry to use it.
