### ISSUE TITLE
poetry shell isn't setting the virtualenv prompt prefix in ZSH

### ISSUE THREAD

**Issue by cquick01** [python-poetry/poetry#6012]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 22.04 LTS (WSL2)
- **Poetry version**: 1.2.0b3
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/cquick01/b780e3ed8192c16991805a62db3785f7

## Issue

```

➜  ~/test poetry shell -vvv
Loading configuration file /home/cquick/.config/pypoetry/config.toml
Using virtualenv: /home/cquick/.cache/pypoetry/virtualenvs/test-zxyBamcN-py3.10
Spawning shell within /home/cquick/.cache/pypoetry/virtualenvs/test-zxyBamcN-py3.10
➜  ~/test echo $POETRY_ACTIVE
1
# no prompt prefix, but poetry is active
➜  ~/test exit
➜  ~/test echo $POETRY_ACTIVE

➜  ~/test bash
cquick@CQuick:~/test$ poetry shell
Spawning shell within /home/cquick/.cache/pypoetry/virtualenvs/test-zxyBamcN-py3.10
. /home/cquick/.cache/pypoetry/virtualenvs/test-zxyBamcN-py3.10/bin/activate
cquick@CQuick:~/test$ . /home/cquick/.cache/pypoetry/virtualenvs/test-zxyBamcN-py3.10/bin/activate
# has prompt prefix (test-py3.10)
(test-py3.10) cquick@CQuick:~/test$ exit
exit
cquick@CQuick:~/test$ poetry -V
Poetry (version 1.2.0b3)
cquick@CQuick:~/test$ zsh --version
zsh 5.8.1 (x86_64-ubuntu-linux-gnu)
```

The prefix `(test-py3.10)` isn't set properly in ZSH, but works fine in bash. The `POETRY_ACTIVE` env var is set properly in ZSH, but the prefix still isn't there.

I've never had issues with this before. I was on v1.1.13 this morning when I noticed it, but updating to v1.1.14 and v1.2.0b3 didn't make a difference.

Edit: it looks like the `activate` script isn't being automatically sourced when starting the shell, because I can source it manually and the prompt gets updated

```➜  ~/test poetry shell
Spawning shell within /home/cquick/.cache/pypoetry/virtualenvs/test-zxyBamcN-py3.10
➜  ~/test  # no prefix
➜  ~/test . /home/cquick/.cache/pypoetry/virtualenvs/test-zxyBamcN-py3.10/bin/activate  # manually source activate script
(test-py3.10) ➜  ~/test  # now prefix is shown
```

**Comment by cquick01** [comment]
It seems like this line isn't working properly for me.

https://github.com/python-poetry/poetry/blob/c8ae868472d9e6e4fc281adc08f2d14e374d35c8/src/poetry/utils/shell.py#L99

I've tried changing it to this to test

```python
print("test")
c.sendline("echo test > /tmp/test")
c.sendline(f"{self._get_source_command()} {shlex.quote(str(activate_path))}")
```

And when starting a shell I see "test" printed, but neither of the `c.sendline` lines work

```zsh
➜  ~/test poetry shell
Spawning shell within /home/cquick/.cache/pypoetry/virtualenvs/test-zxyBamcN-py3.10
test
➜  ~/test cat /tmp/test
cat: /tmp/test: No such file or directory
```

Running `pexpect` in a similar way seems to work fine.

```python
➜  ~ cat /tmp/test
cat: /tmp/test: No such file or directory
➜  ~ python
Python 3.10.5 (main, Jul 14 2022, 12:24:26) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pexpect
>>> c = pexpect.spawn("/usr/bin/zsh", ["-i"])
>>> c.sendline("echo asdf > /tmp/test")
>>> exit()
➜  ~ cat /tmp/test
asdf
```

I've since completely wiped Poetry from my system, and uninstalled all old Python versions from pyenv. Then I reinstalled Python 3.10.5 and Poetry 1.2.0b3, and I'm seeing the same behavior.

**Comment by ruslaniv** [comment]
This is still broken. 
I don't have this line:
`wsl.exe -u root -e sh -c "service docker status || service docker start" &> /dev/null`
in my `.zshrc`

And this:
`alias poetry_activate='source "$( poetry env info --path )/bin/activate"'`
did not solve the problem. 

I still can't activate poetry virtual environment in ZSH.

`which python` still points to default  system python after running:
```
poetry shell
poetry_activate
source <path/to/activate>
```
