### ISSUE TITLE
Unable to add package icc_rt to project

### ISSUE THREAD

**Issue by abianco88** [python-poetry/poetry#6020]
- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows 10 Pro, version 21H2, build 19044.1826
- **Poetry version**: 1.1.14
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: [link](https://gist.github.com/abianco88/004ed99f553f39ee038cf5d29f21c012#file-pyproject-toml)

## Issue
I encounter a runtime error when I try to add the package `icc_rt` to my pyproject.toml file (see below). I tried clearing the cache to no avail (the execution of the command `poetry cache clear --all` returns the message `Not enough arguments (missing: "cache").` even though the command `poetry cache list` returns `pypi`). An online search found that it may be due to a problem accessing non-public repos, however, this package is published by Intel and available via pip. Moreover, I understood that said issue was fixed with a Poetry version above 1.1.4 and I'm currently running 1.11.4. **Any idea how I can get around this?**

```
C:\my_path>poetry add icc_rt
Using version ^2020.0.133 for icc-rt

Updating dependencies
Resolving dependencies...

Package operations: 2 installs, 0 updates, 0 removals

  • Installing intel-openmp (2020.0.133)

  RuntimeError

  Unable to find installation candidates for intel-openmp (2020.0.133)

  at ~\AppData\Roaming\pypoetry\venv\lib\site-packages\poetry\installation\chooser.py:72 in choose_for
       68│
       69│             links.append(link)
       70│
       71│         if not links:
    →  72│             raise RuntimeError(
       73│                 "Unable to find installation candidates for {}".format(package)
       74│             )
       75│
       76│         # Get the best link


Failed to add packages, reverting the pyproject.toml file to its original content.
```

**Comment by finswimmer** [comment]
Hello @abianco88,

> the execution of the command `poetry cache clear --all` returns the message `Not enough arguments (missing: "cache")`

the correct command would be `poetry cache clear --all pypi`. Please try this first and see if this helps.

fin swimmer

**Comment by abianco88** [comment]
Hi @finswimmer ,

I followed your suggestion, but I don't think the command worked as it still shows _pypi_ in my cache after executing it:

```
C:\my_path>poetry cache list
pypi

C:\my_path>poetry cache clear pypi --all
Delete 255 entries? (yes/no) [no] yes

C:\my_path>poetry cache list
pypi
```

**Comment by dimbleby** [comment]
https://pypi.org/project/icc-rt/#files

only a linux build is available, you've reported that you're on windows

**Comment by finswimmer** [comment]
> only a linux build is available, you've reported that you're on windows

Good catch :+1: 

So, the only thing you can do, is to tell poetry to use in older version, where builds for windows exists, e.g. `poetry add icc-rt@2019.0`.

fin swimmer

**Comment by abianco88** [comment]
Thank you! Generally speaking, should it be possible to build the package for Win? Or put it differently, would it be possible to use the most recent package on a non-Linux platform?
