### ISSUE TITLE
Support pkg_dir AND py_file

### ISSUE THREAD

**Issue by shoxxdj** [python-poetry/poetry#6025]
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

Hi, 

I noticed that you can't have a directory named "ilovebeer" and a script named "ilovebeer.py". The following project directory is not possible : 

```
pyproject.toml
ilovebeer.py
ilovebeer
---- script.py
```

This is not possible because of : 
```
~/.poetry/lib/poetry/_vendor/py3.10/poetry/core/masonry/utils/module.py:35 in __init__
 31│             # It must exist either as a .py file or a directory, but not both
 32│             pkg_dir = Path(directory, self._name)
 33│             py_file = Path(directory, self._name + ".py")
 34│             if pkg_dir.is_dir() and py_file.is_file():
 35│                 raise ValueError("Both {} and {} exist".format(pkg_dir, py_file))
```

My request would be to have an option to specify if the project must follow the pkg or pyfile in this case rather than just drop everything. 

Thanks for all your job ! 
Regards,

**Comment by dimbleby** [comment]
Just rename whichever you don't want to be packaged (probably `ilovebeer.py`).  

Your module structure is ambiguous and poetry is doing you a favour by saying so.  

I could just about see a case for poetry always picking whichever of the two it is that the python interpreter picks, when given this choice.  Probably the directory, I guess.

But adding an option to say which you mean is way more trouble than it's worth: just clean up your project structure.

**Comment by shoxxdj** [comment]
I understand the argument "clean up your project structure" 
but sometimes, you did not create everything and just want to "poetrify" a project :)

My idea was to do not change the filenames when adding poetry after a project has started, but whatever, this could be mandatory.

**Comment by neersighted** [comment]
This is a major footgun -- I have to agree that Poetry is doing you a favor by failing rather than picking one and not telling you, or having a config option -- removing the ambiguity is much better than adding some config option.
