### ISSUE TITLE
Submodules are not checked out recursively

### ISSUE THREAD

**Issue by tomuben** [python-poetry/poetry#6033]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 20.04
- **Poetry version**: 1.1.14
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://github.com/exasol/script-languages-release/tree/develop

## Issue
My [project](https://github.com/exasol/script-languages-release/) contains a submodule. (Actually the pyproject.toml is in the submodule, but I think this does not matter). The [clone](https://github.com/python-poetry/poetry-core/blob/cd444099391eaf237fbe2aea0e82f5e296f06b1b/src/poetry/core/vcs/git.py#L270) works as expected, considering the submodule. However, the `checkout` for a specific branch, does not update the submodule:
[This](https://github.com/python-poetry/poetry-core/blob/cd444099391eaf237fbe2aea0e82f5e296f06b1b/src/poetry/core/vcs/git.py#L295) line should be:
```
args += ["checkout", "--recurse-submodules", rev]
```

**Comment by finswimmer** [comment]
Hello @tomuben,

thanks a lot for reporting. Your suggestion looks reasonable to me. I'm happy to review a PR ;)

fin swimmer

**Comment by evanrittenhouse** [comment]
@finswimmer Sorry for the basic question, but how do I submit a PR for `poetry-core` changes when the issue is filed in `poetry`? Should I just replicate the issue in `poetry-core` and then submit the PR against that repo? I have the code ready on my local.

**Comment by radoering** [comment]
We don't track poetry-core issues separately. Just submit the PR and link this issue (`python-poetry/poetry#6033`). See also other poetry-core PRs for example.
