### ISSUE TITLE
Poetry wants to reinstall every system package to the venv when using virtualenvs.options.system-site-packages

### ISSUE THREAD

**Issue by awoimbee** [python-poetry/poetry#6035]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **Poetry version**: 1.2.0b3

## Issue

When I set `virtualenvs.options.system-site-packages` to `true`, my program running inside the poetry venv has access to the system deps (good). But when I run `poetry install`, poetry wants to re-download and re-install everything (bad).

Either I use `virtualenvs.options.system-site-packages true` and poetry should use the system deps (unless not possible, eg not if version mismatch). Or I use `virtualenvs.options.system-site-packages false` and system deps are never used.

Currently If I want to use a dependency from the system site-packages I have to remove it from pyproject.toml and poetry.lock before `poetry install`.

## To reproduce

```bash
docker run -it --rm python:3.10 bash

pip install poetry==1.2.0b3
poetry config virtualenvs.options.system-site-packages true
cat <<EOT > pyproject.toml
[tool.poetry]
name = "gros-zozo"
version = "0.0.0"
description = "saussice"
authors = ["superman"]

[tool.poetry.dependencies]
python = "^3.8"
six = "*"

[build-system]
requires = ["poetry>=1.1"]
build-backend = "poetry.masonry.api"
EOT
poetry install --dry-run
```
output is:
```log
Creating virtualenv gros-zozo-il7asoJj-py3.10 in /root/.cache/pypoetry/virtualenvs
Updating dependencies
Resolving dependencies... (0.3s)

Package operations: 0 installs, 1 update, 0 removals

  • Updating six (1.16.0 /usr/local/lib/python3.10/site-packages -> 1.16.0)
```

Here I use `--dry-run` for the example, but without `--dry-run` poetry downloads the packages then installs then to the venv (but I already have these packages ! I don't want to re-download everything !).

see https://github.com/python-poetry/poetry/issues/1393#issuecomment-1189239876

**Comment by awoimbee** [comment]
1. I tracked down where poetry triggers an update:
    1. There is a weird condition in poetry about package source [here](https://github.com/python-poetry/poetry/blob/5ad517cafd12b563d61dea0f2951827c8cb35f82/src/poetry/puzzle/transaction.py#L47)
    2. poetry-core, in [is_same_package_as](https://github.com/python-poetry/poetry-core/blob/70cd4186771b5c63c4be29fca7c74e29efe4152d/src/poetry/core/packages/specification.py#L158), calls [is_same_source_as](https://github.com/python-poetry/poetry-core/blob/70cd4186771b5c63c4be29fca7c74e29efe4152d/src/poetry/core/packages/specification.py#L103).

2. System deps are treated as `source_type="directory"`, this seems like an issue to me as a random dir (`toto = { path = "../toto", develop = true }` is treated the same as a system dep).
    1. System deps are treated as `source_type="directory"` because of [`is_standard_package = env.is_path_relative_to_lib(path)`](https://github.com/python-poetry/poetry/blob/5ad517cafd12b563d61dea0f2951827c8cb35f82/src/poetry/repositories/installed_repository.py#L121). As a workaround I add `if self.is_venv(): return self.parent_env.is_path_relative_to_lib(path)` [here](https://github.com/python-poetry/poetry/blob/5ad517cafd12b563d61dea0f2951827c8cb35f82/src/poetry/utils/env.py#L1353).
    2. But then I have an issue with poetry looking in `site-packages` & ubuntu using `dist-packages`.
      `poetry`'s env is:
        ```
        {'stdlib': '/usr/lib/python3.7', 'platstdlib': '/usr/lib/python3.7', 'purelib': '/usr/lib/python3.7/site-packages', 'platlib': '/usr/lib/python3.7/site-packages', 'include': '/usr/include/python3.7m', 'platinclude': '/usr/include/python3.7m', 'scripts': '/usr/bin', 'data': '/usr', 'usersite': '/root/.local/lib/python3.7/site-packages', 'userbase': '/root/.local'}
        ```
        But: 
        ```
        root@0fc309583485:/opt/app#  python3 -m site
        sys.path = [
            '/opt/app',
            '/usr/lib/python37.zip',
            '/usr/lib/python3.7',
            '/usr/lib/python3.7/lib-dynload',
            '/usr/local/lib/python3.7/dist-packages',
            '/usr/lib/python3/dist-packages',
        ]
        USER_BASE: '/root/.local' (exists)
        USER_SITE: '/root/.local/lib/python3.7/site-packages' (doesn't exist)
        ENABLE_USER_SITE: True
        ```
        I tested both `GET_PATHS` and `GET_PATHS_FOR_GENERIC_ENVS`, both point to site-packages.
        I'm stuck here.

**Comment by ashleysommer** [comment]
Having this same problem.

In my docker container, I install some system packages, then in my poetry project, I turn on system-site-packages option, and pin the package version in my `poetry.toml` (and in poetry.lock) to the exact same package version that is already installed.

But when running `poetry install --no-root`, poetry goes ahead and re-installs the same packages, but from PIP. This fails, because these packages cannot be compiled in my docker container. (and defeats the purpose, because the compiled package is already installed by the system).

**Comment by neersighted** [comment]
PTAL @radoering -- looks like more fallout from the work on dependency origins (and could be intended behavior that we need to document).

**Comment by radoering** [comment]
I wonder if `system-site-packages` has ever worked. It seems like the code in question is older than the option.

I'd say this `else` is too much of a generalization:

https://github.com/python-poetry/poetry/blob/cf3dcad04ef0e792e95583a9b70c9d40da2fcad2/src/poetry/repositories/installed_repository.py#L161-L164

**Comment by marekro** [comment]
Yes, looks like I did not find this issue before filing #7234 - apologies. Maybe I can make up for it with another workaround:
I use the following sequence to avoid running into the bug, but keep the goodness of poetry's dependency resolution:

With a poetry.toml:
```
[virtualenvs.options]
system-site-packages = true
```
Run this:
```
poetry use env python3.10
poetry lock
poetry export > requirements.txt
poetry run pip3 install -r requirements.txt
```

It seems that pip is smart enough to "see" the already available packages in the system-wide Python site-packages, and skips the redundant build. I would be happy if the poetry installation manager would do the same.

**Comment by awoimbee** [comment]
@neersighted any comment as to why this is not planned ?
You might as well just remove `virtualenvs.options.system-site-packages` at this point.

**Comment by neersighted** [comment]
Looks like I got a wire crossed and closed the wrong issue (#7234 is a duplicate). That being said, `system-site-packages` is not Poetry's option and that should be kept in mind -- it is functionality of the virtualenv package and PEP being exposed for power users; it is not intended to be

**Comment by marekro** [comment]
Clearly, system-site-packages is a venv option, not a native option of poetry. That said, poetry uses and supports venv. So when a (power) user wants to make venv use system-site-packages, then poetry should respect this choice - and be happy with the packages seen in the venv - regardless whether found in the venv itself or in the underlying Python’s system-site-packages. Needless to say that poetry should install a package version in venv in case the version does not match. Thanks for reopening this ticket and I hope this can be fixed soon.

**Comment by GingerIndustries** [comment]
Is this ever going to be fixed? It's been a thorn in my side for using Poetry on a Raspberry Pi, where I often install packages system-wide to avoid needless hours of building.

**Comment by dimbleby** [comment]
Like all bugs: this will not be fixed before someone who cares about it shows up and fixes it.  Is that you?

**Comment by niniack** [comment]
Hi @abompard, I'm not quite certain that this issue is fixed by #8359. I am using the master branch on poetry and despite having a package installed in my container, I still run into the same issue where poetry reinstalls existing packages, like this:

```
root@a9ea362e494d:/# poetry config virtualenvs.options.system-site-packages true
root@a9ea362e494d:/# cat pyproject.toml 
[tool.poetry]
name = "myproject"
version = "0.0.0"
description = "myproject"
authors = ["me"]
license = "MIT"
readme = "README.md"

[build-system]
requires = ["poetry-core>=1.5.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
python = ">=3.8.1,<3.11"
toml = { version = "*"}
requests = { version = "*"}
spython = { version = "*"}
typer = {version = "*", extras = ["all"]}

[tool.poetry.group.torch]
optional = true

[tool.poetry.group.torch.dependencies]
torch = {version = ">=2.1.0", source = "torch", allow-prereleases = true}
torchvision = {version = "*", source = "torch", allow-prereleases = true}
torchaudio = {version = "*", source = "torch", allow-prereleases = true}

[[tool.poetry.source]]
name = "torch"
url = "https://download.pytorch.org/whl/cu118"
root@a9ea362e494d:/# poetry install --no-root --only torch --dry-run
Installing dependencies from lock file

Package operations: 0 installs, 19 updates, 0 removals

  - Updating filelock (3.9.0 /usr/local/lib/python3.10/dist-packages -> 3.13.1)
  - Updating markupsafe (2.1.3 /usr/local/lib/python3.10/dist-packages -> 2.1.3)
  - Updating mpmath (1.3.0 /usr/local/lib/python3.10/dist-packages -> 1.3.0)
  - Updating certifi (2022.12.7 /usr/local/lib/python3.10/dist-packages -> 2023.11.17)
  - Updating charset-normalizer (2.1.1 /usr/local/lib/python3.10/dist-packages -> 3.3.2)
  - Updating fsspec (2023.4.0 /usr/local/lib/python3.10/dist-packages -> 2023.10.0)
  - Updating idna (3.4 /usr/local/lib/python3.10/dist-packages -> 3.4)
  - Updating jinja2 (3.1.2 /usr/local/lib/python3.10/dist-packages -> 3.1.2)
  - Updating sympy (1.12 /usr/local/lib/python3.10/dist-packages -> 1.12)
  - Updating triton (2.1.0 /usr/local/lib/python3.10/dist-packages -> 2.1.0)
  - Updating typing-extensions (4.4.0 /usr/local/lib/python3.10/dist-packages -> 4.4.0)
  - Updating urllib3 (1.26.13 /usr/local/lib/python3.10/dist-packages -> 2.1.0)
  - Updating networkx (3.0 /usr/local/lib/python3.10/dist-packages -> 3.1)
  - Updating numpy (1.24.1 /usr/local/lib/python3.10/dist-packages -> 1.24.4)
  - Updating pillow (9.3.0 /usr/local/lib/python3.10/dist-packages -> 10.1.0)
  - Updating torch (2.1.1+cu118 /usr/local/lib/python3.10/dist-packages -> 2.1.1+cu118)
  - Updating requests (2.28.1 /usr/local/lib/python3.10/dist-packages -> 2.31.0)
  - Updating torchaudio (2.1.1+cu118 /usr/local/lib/python3.10/dist-packages -> 2.1.1+cu118)
  - Updating torchvision (0.16.1+cu118 /usr/local/lib/python3.10/dist-packages -> 0.16.1+cu118)
  ```

Now, I understand that my issue could stem from something different because, well, Pytorch. However, it also happens for Pytorch's dependencies, which is why I wanted to raise this here.

If I am misunderstanding something, I would greatly appreciate being pointed in the right direction. Thank you.

**Comment by awoimbee** [comment]
It works for me (`Installing torch (2.0.0+cu117): Skipped for the following reason: Already installed`) (tested poetry 1.7 and master `31540a802e7779ab13bbfc39c8eefd6402a59605`).

```bash
# find / -name 'torch' 2>/dev/null
/usr/local/lib/python3.10/dist-packages/torch
```

My "source" is setup as `explicit` and torch is not in a dependency group. These and the fact that your group is optional might be triggering a bug ?

**Comment by niniack** [comment]
Thanks for testing! Would you mind sharing your pyproject.toml for the pytorch case?

**Comment by UFO-101** [comment]
I also have a simple example of this not working in a Docker build:

https://github.com/UFO-101/auto-circuit/blob/main/Dockerfile

```
# Based on https://github.com/AlignmentResearch/flamingo/blob/main/examples/devbox/Dockerfile
# and https://nanmu.me/en/posts/2023/quick-dockerfile-for-python-poetry-projects/
FROM pytorch/pytorch as base

ARG UID=10000
ARG GID=101
ARG USERNAME=dev

ENV PYTHONUNBUFFERED=1 \
    # pip
    PIP_DISABLE_PIP_VERSION_CHECK=on \
    PIP_DEFAULT_TIMEOUT=100 \
    \
    # Poetry
    # https://python-poetry.org/docs/configuration/#using-environment-variables
    POETRY_VERSION=1.7.1 \
    # make poetry install to this location
    POETRY_HOME="/opt/poetry" \
    # do not ask any interactive question
    POETRY_NO_INTERACTION=1 \
    POETRY_VIRTUALENVS_PATH=/home \
    POETRY_VIRTUALENVS_IN_PROJECT=false \
    POETRY_VIRTUALENVS_OPTIONS_SYSTEM_SITE_PACKAGES=true

# prepend poetry and venv to path
ENV PATH="$POETRY_HOME/bin:$PATH"

# Update the package list, install sudo, create a non-root user, and grant password-less sudo permissions
RUN apt update && \
    apt install -y sudo && \
    addgroup --gid $GID ${USERNAME} && \
    adduser --uid $UID --gid $GID --disabled-password --gecos "" ${USERNAME} && \
    usermod -aG sudo ${USERNAME} && \
    echo "${USERNAME} ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

# Install some useful packages
RUN apt update && \
    apt install -y rsync git vim

# Install Poetry
RUN apt install -y curl && \
    curl -sSL https://install.python-poetry.org | python3 -

RUN chmod 777 /home

# Set the non-root user as the default user
USER ${USERNAME}
WORKDIR /home/${USERNAME}/auto-circuit

# Copying the Python project files
COPY --chown=${USERNAME}:${USERNAME} . /home/${USERNAME}/auto-circuit

# Install dependencies
RUN poetry install --with dev

WORKDIR /home
RUN rm -rf /home/${USERNAME}
```

**Comment by ashleysommer** [comment]
@birdcolour Thanks for sharing that, and it does help with my use-case too.
In my case, we were using poetry since before the new dependency-groups come in, so we still mark system-provided dependencies as optional dependencies in the "old" way, like:

```
[tool.poetry.dependencies]
foo = {version=bar, optional=True}
```
