### ISSUE TITLE
Facing one error 

### ISSUE THREAD

**Issue by deep9888** [python-poetry/poetry#6036]
hello guys, how are you? I hope you're doing well.
While deploying flask and deep learning based web app on replit it gives me an error of one module but in python that module didn't exist, where is the issue or bug?
![6](https://user-images.githubusercontent.com/103727216/179911001-f659eff4-3503-4fda-b743-f2b08e4abcaa.JPG)

**Comment by matteosantama** [comment]
This is not the correct way to use Poetry -- it does not support the usage of the `-m` flag. You should instead try to run Poetry directory, ie. `poetry lock`

**Comment by finswimmer** [comment]
Hello @deep9888,

it's exactly like @matteosantama. If you really want to use the `-m` flag you have to run it like this: `python -m poetry.console.application --version`.

But this requires that Poetry is installed in the same environment as the current python interpreter and this is discouraged.

fin swimmer
