### ISSUE TITLE
Fail to install Poetry with FileExistsError

### ISSUE THREAD

**Issue by zlenyk** [python-poetry/poetry#6038]
- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 20.04
- **Poetry version**: trying to install latest one
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: n/a

## Issue

When executing: curl -sSL https://install.python-poetry.org | python -
I'm getting output:
```
  Retrieving Poetry metadata
  
  # Welcome to Poetry!
  
  This will download and install the latest version of Poetry,
  a dependency and package manager for Python.
  
  It will add the `poetry` command to Poetry's bin directory, located at:
  
  /home/user/.local/bin
  
  You can uninstall at any time by executing this script with the --uninstall option,
  and these changes will be reverted.
  
  Traceback (most recent call last):
    File "<stdin>", line 908, in <module>
    File "<stdin>", line 887, in main
    File "<stdin>", line 497, in run
    File "<stdin>", line 739, in ensure_directories
    File "/home/user/miniconda3/envs/grfyn_3.8/lib/python3.8/pathlib.py", line 1288, in mkdir
      self._accessor.mkdir(self, mode)
  FileExistsError: [Errno 17] File exists: '/home/user/.local/bin'
```
I made sure that no previous verisons of poetry are installed.
I'm running this inside conda environment with python 3.8

**Comment by zlenyk** [comment]
I can workaround it via manuall setting POETRY_HOME env variable. Is this expected?

**Comment by matteosantama** [comment]
Here is the implementation of `ensure_directories`, as you can see we have `exist_ok=True`.

```python
    def ensure_directories(self) -> None:
        self._data_dir.mkdir(parents=True, exist_ok=True)
        self._bin_dir.mkdir(parents=True, exist_ok=True)
```
BUT if you look at the [documentation](https://docs.python.org/3/library/pathlib.html#pathlib.Path.mkdir) for `Path.mkdir` it says

> If exist_ok is true, [FileExistsError](https://docs.python.org/3/library/exceptions.html#FileExistsError) exceptions will be ignored (same behavior as the POSIX mkdir -p command), but only if the last path component is not an existing non-directory file.

If I'm interpreting that correctly, it means `/home/user/.local/bin` is a likely pre-existing **file** on your machine. What is the output of 

```python
from pathlib import Path

path = Path("/home/user/.local/bin")
path.is_file()
```

**Comment by zlenyk** [comment]
It is "False".

**Comment by zlenyk** [comment]
Thank you for your response!
You're right, due to a weird coincidence, this was a file on my computer. Now everything works.

Thank you!
