### ISSUE TITLE
Usage instructions are wrong for `poetry -v install`

### ISSUE THREAD

**Issue by WhyNotHugo** [python-poetry/poetry#6039]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Arch
- **Poetry version**: 1.1.14
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: n/a

## Issue

```
$ poetry -v install
Poetry version 1.1.14

USAGE
  poetry [-h] [-q] [-v [<...>]] [-V] [--ansi] [--no-ansi] [-n] <command> [<arg1>] ... [<argN>]
...
```

The usage output here seems to indicate that my usage is correct. `install` is listed as a command further below.

Using `poetry install -v` _does_ work, but the usage is very clear in that this is the wrong usage.

Also, when running `poetry -vv install`, an entirely different error is shown:

```
$ poetry -vv install
USAGE
  poetry help [<command1>] ... [<commandN>]

ARGUMENTS
  <command>              The command name
```

Remotely related to https://github.com/python-poetry/poetry/issues/5657

**Comment by dimbleby** [comment]
already fixed in 1.2.0 betas, please close
