### ISSUE TITLE
Installed but not worked

### ISSUE THREAD

**Issue by DecentrilizedMan** [python-poetry/poetry#6040]
I install poetry through this command  : curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python - 

And it shows that the lastest version is installed as : 
<img width="707" alt="image" src="https://user-images.githubusercontent.com/43113774/179995009-b0ed762d-805c-466a-919d-3235f35326cb.png">

But when i run poetry version , it shows :  
<img width="360" alt="image" src="https://user-images.githubusercontent.com/43113774/179995118-685081f3-be9b-40b0-98ec-bb8327de3f89.png">

**Comment by matteosantama** [comment]
A couple of questions that will help with debugging

1. If you quit out of terminal (CMD + Q) and re-open it, is the `poetry` command available?
2. Are you using `zsh` or `bash`?
3. What is the output of `echo $PATH`?

**Comment by dimbleby** [comment]
but even in the event that you find a bug in the deprecated installer, no-one will care to fix it.  Use the new installer.

**Comment by neersighted** [comment]
Closing as this is for the deprecated and unsupported installer.
