### ISSUE TITLE
Exported requirements.txt fails to install

### ISSUE THREAD

**Issue by jonathan-boudreau-work** [python-poetry/poetry#6041]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 20.04.4 LTS
- **Poetry version**:   1.1.14
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**:  https://gist.github.com/jonathan-boudreau-work/0d7b014894623449d104a131e5d9b2f1

## Issue
When I try to install the exported requirement.txt generated by poetry, pip fails the installation stating there are missing hashes. This only seems to happen when I try to export projects with `gql` package. More detailed pip logs:
```
Collecting backoff==2.1.2
  Using cached backoff-2.1.2-py3-none-any.whl (14 kB)
Collecting gql==3.4.0
  Using cached gql-3.4.0-py2.py3-none-any.whl (65 kB)
Collecting graphql-core==3.2.1
  Using cached graphql_core-3.2.1-py3-none-any.whl (202 kB)
Collecting idna==3.3
  Using cached idna-3.3-py3-none-any.whl (61 kB)
Collecting multidict==6.0.2
  Using cached multidict-6.0.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (121 kB)
Collecting yarl==1.7.2
  Using cached yarl-1.7.2-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (308 kB)
ERROR: Hashes are required in --require-hashes mode, but they are missing from some requirements. Here is a list of those requirements along with the hashes their downloaded archives actually had. Add lines like these to your requirements files to prevent tampering. (If you did not enable --require-hashes manually, note that it turns on automatically when any package has a hash.)
    backoff==2.1.2 --hash=sha256:b135e6d7c7513ba2bfd6895bc32bc8c66c6f3b0279b4c6cd866053cfd7d3126b
    gql==3.4.0 --hash=sha256:59c8a0b8f0a2f3b0b2ff970c94de86f82f65cb1da3340bfe57143e5f7ea82f71
```

**Comment by defel** [comment]
thanks @dimbleby - this fixed it for me

A more verbose description of steps I had to do: 

```shell
# upgrade poetry to >=1.1.14
pip install --upgrade poetry

# clear caches
poetry cache clear artifact --all
poetry cache clear pypi --all

# remove old lock file
rm poetry.lock

# reinstall (and generate lock-file)
poetry install
```

**Comment by jedie** [comment]
Can confirm this bug.

Only delete `poetry.lock` but keep the cache results in the same error.
The fix is to clear poetry cache.

**Comment by jedie** [comment]
delete lock file + clear `cache` seems seems to be not enough. Clear `artifact` is also needed :(

**Comment by dimbleby** [comment]
this can be closed

**Comment by jedie** [comment]
@dimbleby why closed? The problem with missing hashes are still there with poetry v1.1.15
Deleting cache / artifact is a work-a-round, but didn't work all the time :(

**Comment by jedie** [comment]
Closed because of: https://github.com/python-poetry/poetry/issues/4523 ?

**Comment by dimbleby** [comment]
closed because this was clearly a duplicate of #5970, and it is resolved by clearing your cache, updating poetry, and re-locking

**Comment by jedie** [comment]
Thanks for the feedback. My suggestion is to always mention the reason when closing and link to an OR or an other ticket. Then there will be no misunderstandings ;)

**Comment by dimbleby** [comment]
The entire meaningful content of this thread was "here's how to fix it", "thanks that fixed it".  Thanks anyway,
