### ISSUE TITLE
Poetry can find PyPI package using "add" but not "init"

### ISSUE THREAD

**Issue by grahamfindlay** [python-poetry/poetry#6042]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 20.04.4 LTS
- **Poetry version**: 1.1.14

## Issue

Poetry fails to find the PyPI package [pyEDFlib](https://pypi.org/project/pyEDFlib/) when dependencies are specified interactively during `poetry init`, but has no problem finding and installing using `poety add pyEDFlib`. I have a totally unsubstantiated hunch that this is somehow due to the use of capital letters in the package name. 

Interestingly, during `poetry init`, poetry reports having "found 5 packages matching pyEFDlib," but only presents 4 options, none of which are correct: 

![image](https://user-images.githubusercontent.com/4753005/180097225-75f364df-55d9-449a-9f2b-e8f59fa9e6fb.png)

**Comment by dimbleby** [comment]
already fixed, per this on the latest beta:
```
Package to add or search for (leave blank to skip): pyEDFlib
Found 5 packages matching pyEDFlib

Enter package # to add, or the complete package name if it is not listed []:
 [0] pyEDFlib
...etc
```
