### ISSUE TITLE
Wrong environment markers generated when poetry export

### ISSUE THREAD

**Issue by icyblade** [python-poetry/poetry#6044]
- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 18.04.6 LTS
- **Poetry version**: 1.1.14
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: [https://gist.github.com/icyblade/732f87f76955d68dfa7addf42dec32cf](https://gist.github.com/icyblade/732f87f76955d68dfa7addf42dec32cf)

## Issue

Poetry creates wrong environment markers when `poetry export`.

With above [pyproject.toml](https://gist.github.com/icyblade/732f87f76955d68dfa7addf42dec32cf), such requirements.txt will be generated:
```
py==1.11.0; python_version >= "3.7" and python_full_version < "3.0.0" and sys_platform == "linux" and implementation_name == "pypy" or python_version >= "3.7" and sys_platform == "linux" and python_full_version >= "3.5.0" and implementation_name == "pypy"
```
However, this is not correct because `py` is required for `pytest`.

Installing this requirements.txt will not install `py` and will cause `pytest` not functional:
```
(/home/venv/poetry) username@hostname:~/test$ poetry export --without-hashes | grep -i "^py==" | pip install -r /dev/stdin
Ignoring py: markers 'python_version >= "3.7" and python_full_version < "3.0.0" and sys_platform == "linux" and implementation_name == "pypy" or python_version >= "3.7" and sys_platform == "linux" and python_full_version >= "3.5.0" and implementation_name == "pypy"' don't match your environment
(/home/venv/poetry) username@hostname:~/test$ pytest
Traceback (most recent call last):
  File "/home/venv/poetry/bin/pytest", line 5, in <module>
    from pytest import console_main
  File "/home/venv/poetry/lib/python3.8/site-packages/pytest/__init__.py", line 5, in <module>
    from _pytest._code import ExceptionInfo
  File "/home/venv/poetry/lib/python3.8/site-packages/_pytest/_code/__init__.py", line 2, in <module>
    from .code import Code
  File "/home/venv/poetry/lib/python3.8/site-packages/_pytest/_code/code.py", line 43, in <module>
    from _pytest._io import TerminalWriter
  File "/home/venv/poetry/lib/python3.8/site-packages/_pytest/_io/__init__.py", line 1, in <module>
    from .terminalwriter import get_terminal_width
  File "/home/venv/poetry/lib/python3.8/site-packages/_pytest/_io/terminalwriter.py", line 10, in <module>
    from _pytest.compat import final
  File "/home/venv/poetry/lib/python3.8/site-packages/_pytest/compat.py", line 20, in <module>
    import py
ModuleNotFoundError: No module named 'py'
(/home/venv/poetry) username@hostname:~/test$ 
```

**Comment by dimbleby** [comment]
please try the latest beta, export is much improved there and I'm pretty confident this is already fixed

**Comment by icyblade** [comment]
@dimbleby Thanks for the quick response. Confirmed the issue is mitigated in latest beta [1.2.0b3](https://github.com/python-poetry/poetry/releases/tag/1.2.0b3). Generated `requirements.txt` shows:
```
py==1.11.0 ; python_version >= "3.8" and python_version < "3.9" and sys_platform == "linux"
```
