### ISSUE TITLE
Missing wheels (metadata.files all empty lists)

### ISSUE THREAD

**Issue by jstriebel** [python-poetry/poetry#6045]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Debian 10.12
- **Poetry version**: Tested with poetry `1.1.11`, `1.1.14` and `1.2.0b3`

## Issue
When updating dependencies (e.g. via `poetry update <my_dep>`), wheels are not listed anymore under `metadata.files` in the `poetry.lock` file. At first this happened only for a single updated dependency, after clearing the pypi cache (via `rm -rf ~/.cache/pypoetry/cache` or `poetry cache clear pypi --all`) they are missing for all packages, even when wheels have been available before and listed. The same versions as before (that were not changed on pypi since) are now missing the files, `poetry.lock` looks like this now:
```toml
…

[metadata.files]
aiobotocore = []
aiohttp = []
aioitertools = []
aiosignal = []
anyio = []
appdirs = []
asciitree = []
astroid = []
…
```

I suspect that a recent change in the PyPI API might be the source of this issue:
https://discuss.python.org/t/backwards-incompatible-change-to-pypi-json-api/17154

I believe this is a critical bug, since wheels can not easily be installed anymore due to it.

PS: Thanks for all your great work with poetry! :heart:

**Comment by dimbleby** [comment]
#5970, clear your cache, retry with 1.1.14 (or 1.2.0b3), then please close - thanks

**Comment by jstriebel** [comment]
Seems like I didn't update poetry properly when testing this, sorry for the duplicate. Works with proper `1.1.14` indeed, thanks!
