### ISSUE TITLE
Dependency Tree Caching Service?

### ISSUE THREAD

**Issue by logannc** [python-poetry/poetry#6049]
> At this point, Poetry has no choice but downloading the packages and inspect them to get the necessary information. This is an expensive operation, both in bandwidth and time, which is why it seems this is a long process.
> At the moment there is no way around it.
> Once Poetry has cached the releases' information, the dependency resolution process will be much faster.

As I see it, there are a couple options

1. "Fix" PyPI by having PyPI perform this parsing and caching
2. Host a separate service that has this dependency tree cached (configurable)
3. ~~Fix all those python packages to declare their dependencies~~

My question is twofold

1. Has PyPI been approached or asked about maintaining this dependency map via inspection? 
2. If someone set up a dependency tree cache service, would that "solve" this issue and would this project be interested in using it?
Bonus question: can this be done via a plugin?

This is something I'm interested in doing. If this project is willing to use such a caching service, I am here to get some details for what the format and information required might look like. (As well as some pointers for where in the codebase poetry currently does its parsing to maintain compatibility.)

Sincerely,
Someone Waiting
<img width="256" alt="Screen Shot 2022-07-21 at 6 47 03 PM" src="https://user-images.githubusercontent.com/93951871/180338320-7c7aa8dc-0d3d-4d44-a4f3-170fa9db23aa.png">

**Comment by dimbleby** [comment]
times of that magnitude are unlikely to be about download speed unless you really have a very slow network connection (and then you're going to have fun installing too...)

more likely you have either hit some pathological case in the search tree, or stalled completely (eg per https://github.com/python-poetry/poetry/issues/6030)

sensible things to try:
- clear your cache
- use the latest beta
- use `-vvv` to see what poetry is doing, and when you see which packages it is struggling to resolve provide tighter bounds (usually higher lower bounds) on those packages in your pyproject.toml - so as to reduce the size of the search space

**Comment by neersighted** [comment]
Closing as this is not really in the scope of the Poetry project, and is in fact what [PEP 658](https://peps.python.org/pep-0658/) sets out to do. Poetry does not implement 658 yet, but plans to when PyPI gains support (at which point we can stop special-casing PyPI).
