### ISSUE TITLE
Incorrect Python version installed in virtual environment

### ISSUE THREAD

**Issue by cifkao** [python-poetry/poetry#6051]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Linux nef-devel 3.10.0-693.17.1.el7.x86_64 # 1 SMP Thu Jan 25 20:13:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- **Poetry version**: 1.1.14
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**:
https://gist.github.com/cifkao/cf3e0b23bc075bda6700400c3b1bebfc

## Issue
I have a project that requires Python ^3.9. The system installation in `/usr/bin/python3` is Python 3.6 and I'm in a Conda environment with Python 3.9.7.

Running `poetry install` gives:
```
The currently activated Python version 3.6.8 is not supported by the project (^3.9).
Trying to find and use a compatible version. 
Using python3 (3.9.7)
Creating virtualenv poetry-test-PDOMCCYP-py3.9 in /home/ocifka/.cache/pypoetry/virtualenvs
Updating dependencies
Resolving dependencies... (0.1s)

Writing lock file
```

However, this is _the opposite_ of what happens.

Firstly, the activated Python was version 3.9.7 (from Conda) and not 3.6.8:
```
$ python --version
Python 3.9.7
```
Secondly, Poetry goes ahead and installs Python 3.6.8:
```
$ ~/.cache/pypoetry/virtualenvs/poetry-test-PDOMCCYP-py3.9/bin/python --version
Python 3.6.8
```

**Comment by finswimmer** [comment]
Hey,

lots of improvements have been made in this area in the 1.2 release and should be solved. Maybe it's necessary to 
set `virtualenvs.prefer-active-python` to `true` in your use case.

fin swimmer
