### ISSUE TITLE
Change dependency's extras through own extras

### ISSUE THREAD

**Issue by HarHarLinks** [python-poetry/poetry#6053]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

I want to use

```
[tool.poetry.dependencies]
matrix-nio = "^0.19.0"

[tool.poetry.extras]
e2e = {package = "matrix-nio", extras = ["e2e"], version = "^0.19.1"}
```

in order to add the extra `e2e` to my package. Upon installing my package with the `e2e` extra, poetry should pull in matrix-nio's `e2e` extra.

I don't think this case is currently possible, is it?

**Comment by dimbleby** [comment]
duplicate #834, #3913

**Comment by neumantm** [comment]
I think this is also related to https://github.com/python-poetry/poetry/issues/5733?
It contain a solution for poetry version 1.2.0, so we just need to wait.

**Comment by neersighted** [comment]
Closing as duplicate
