### ISSUE TITLE
no information on currently released version 1.1.14 in CHANGELOG

### ISSUE THREAD

**Issue by Lx** [python-poetry/poetry#6056]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

[Poetry v1.1.14](https://pypi.org/project/poetry/1.1.14/) is currently the latest release shown on PyPI, but there is no corresponding 1.1.14 section in the [CHANGELOG](https://github.com/python-poetry/poetry/blob/master/CHANGELOG.md), which jumps from 1.1.13 to 1.2.0b1.

**Comment by Secrus** [comment]
There was info on our blog: https://python-poetry.org/blog/announcing-poetry-1.1.14/. This update was rushed because without it PyPI was unavailable when using Poetry.

**Comment by neersighted** [comment]
Please note that the CHANGELOG was updated on the correct branch, and merely not cherry-picked into master.

https://github.com/python-poetry/poetry/blob/1.1/CHANGELOG.md
