### ISSUE TITLE
List of packages is not sorted as intended (thus allow-prereleases=true doesn't work)

### ISSUE THREAD

**Issue by disafr** [python-poetry/poetry#6068]
- **OS version and name**: Windows 10
- **Poetry version**: 1.1.14
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/disasick/b477d46a556c18571ebc2fc87991f792

# The issue
I have created a custom package in a custom PiPy repository. I am using PEP440 version notation to build development packages. With the switch `allow-prereleases=true` I would expect the latest prerelease (development) package to be installed. However, always the latest release is installed.

By debugging, I found that Poetry finds all these versions of `myCustomPackage`:
```
3.0.4
3.0.4.dev471202
3.0.4.dev471203
3.0.4.dev471205
3.0.4.dev471427
3.0.4.dev471430
3.0.4.dev471448
3.0.4.dev471455
3.0.4.dev471469
3.0.4.dev471544
3.0.4.dev471561
3.0.4.dev471573
3.0.4.dev471606
3.0.4.dev471740
3.0.5
3.0.5.dev471664
3.0.5.dev471693
```

In my `pyproject.toml` I specified
```
[tool.poetry.dependencies]
myCustomPackage = { version = "^3.0.0*", allow-prereleases = true}
```
so I'd expect the latest development version `3.0.5.dev471693` to be installed on `poetry install`. However, `3.0.5` is installed.

# The cause of the issue
https://github.com/python-poetry/poetry/blob/c5ce4d03de9b37ab3db521fd5c195cb45e5ea216/src/poetry/puzzle/provider.py#L274-L282
Using `p.version` as a key for `sort()` in line `279` does not behave as expected. The resulting sorted list is (shortened):
```
['3.0.5', '3.0.5.dev471693', '3.0.5.dev471664', '3.0.4', '3.0.4.dev471740', '3.0.4.dev471606', '3.0.4.dev471573', '3.0.4.dev471561', '3.0.4.dev471544', '3.0.4.dev471469', '3.0.4.dev471455', '3.0.4.dev471448', '3.0.4.dev471430', '3.0.4.dev471427', '3.0.4.dev471205', '3.0.4.dev471203', '3.0.4.dev471202']
```
Obviously it's sorting wrongly as `3.0.5` shouldn't be the first item. As `p.version` is an instance of the `Version` class (`core/semver/version.py`), possibly `sort()` is not calling its `__repr__()` method correctly.

# The solution
Calling `str()` on the `version` property in line `279` seems to convert the version object in a format which `sort()` can handle properly. Accordingly, the fix would be:
```
 packages.sort( 
     key=lambda p: ( 
         not p.is_prerelease() and not dependency.allows_prereleases(), 
         str(p.version),
     ), 
     reverse=True, 
 ) 
```
With this small change, Poetry installs the desired prerelease version:
```
  • Installing myCustomPackage (3.0.5.dev471693)
```

Would be good to see this fix implemented soon :)

**Comment by finswimmer** [comment]
Hello @disafr,

the ordering here is correct. dev releases have to become before non-dev releases. See https://peps.python.org/pep-0440/#summary-of-permitted-suffixes-and-relative-ordering

fin swimmer

**Comment by disafr** [comment]
@finswimmer According to your statement and that link, Poetry does actually not sort correctly at the moment. Currently, dev releases are _not_ before non-dev releases. Please re-check the issue description.

**Comment by disafr** [comment]
@finswimmer As I understand your statement and the PEP440 docu, the ordering of the suffixes must always be:
```
.devN, aN, bN, rcN, <no suffix>, .postN
```
But Poetry currently sorts it 
```
<no suffix>, .devN, ...
```

**Comment by finswimmer** [comment]
Hey,

in the lines of code you've linked to, Poetry is doing a reverse sort. So the result is a list of package versions from the latest to the oldest, thus the first element is always the latest version.

I guess your confusing is because you think `3.0.5.dev471693` is based on `3.0.5` and must therefor be newer? That's not the case. If there is already a `3.0.5` a next `dev` version must at least increase the patch number, e.g. `3.0.6.dev42`.

**Comment by disafr** [comment]
Hi @finswimmer,

thanks for your reply. I am aware of the reversed sorting. My point is basically that the sorting (reverse or not) is currently not done lexigraphically. With a classic alphabetical reverse sort (on strings), the order would be 
`['3.0.5.dev471693', '3.0.5.dev471664', '3.0.5', '3.0.4.dev471740', '3.0.4']`
but somehow with the reverse sort in Poetry it's 
`['3.0.5', '3.0.5.dev471693', '3.0.5.dev471664', '3.0.4', '3.0.4.dev471740']`

That being my point, given your input I can accept that this is the desired behavior, although it's not intuitive to me.
It's new to me that the patch version must be incremented for a new dev version. I can't find anything about that in the PEP440 documentation or elsewhere. However, I can work with this new information now :)

**Comment by neersighted** [comment]
Hi @disafr -- dev versions are meant to be a precursor version, not unlike a `beta` or `rc`. If you think of them that way, it will make sense -- `b1` and `rc2` come before the stable version. When you `allow-prereleases` you allow future versions that are excluded due to being non-stable versions to be considered. If you are looking to suffix the current patch version, that is what `postXXX` versions are for -- they will do what you expect.
