### ISSUE TITLE
Virtual env name in PS1 when in-project=true is not ideal

### ISSUE THREAD

**Issue by borice** [python-poetry/poetry#6070]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Issue

When using `virtualenvs.in-project = true` and running `poetry install`, the output reads:

```
Creating virtualenv test-poetry in /Users/capitanu/Projects/Personal/Python/Testing/poetry/.venv
Updating dependencies
Resolving dependencies... (0.1s)

Writing lock file
```
So, it reports the name of the virtual environment is "test-poetry";  but then, executing `poetry shell` results in:
```
(.venv) capitanu@leo:~/Projects/Personal/Python/Testing/poetry$
```
where `(.venv)` (confusingly) seems to be indicating the virtual environment's name. 

When one has multiple Python projects opened in various terminal tabs, and all of them have a `(.venv)` prefix at the prompt, it's very hard to distinguish between them...    it seems to me that the more correct (or useful) behavior is to show the `(test-poetry)` prefix for the shell prompt.  Is this possible?  (I still want the `in-project=true` setting)

Pretty please, with sugar on top 🙏

**Comment by neersighted** [comment]
There is a new setting, `virtualenvs.prompt` available on the 1.2 betas: https://python-poetry.org/docs/master/configuration/#virtualenvsprompt

This should let you customize the prompt to be something other than the name of the venv directory :smile:
