### ISSUE TITLE
Conditional URL logic for packages in pyproject.toml

### ISSUE THREAD

**Issue by elicutler** [python-poetry/poetry#6071]
Hello,
Great work on poetry! It is my go-to python virtual env and package manager.

I have a poetry project that depends on a private repo my company maintains. On our primary dev box we have to install it over ssh, so my `pyproject.toml` dependency list specifies:
```
pkg = {git = "ssh://git@altssh.bitbucket.org:443/company/pkg.git"}
```
But now we need to work on another machine without SSH where we must install it over HTTP, so on that box I have to modify the `pyproject.toml` line to:
```
pkg = {git = "https://my-username@bitbucket.org/company/pkg.git"}
```

It would be great if I could write conditional logic directly in `pyproject.toml` to account for the different download paths depending on which machine I'm working on, as opposed to having to manually modify the file.

Thanks

**Comment by dimbleby** [comment]
this is an extremely niche request - I'd be surprised if poetry ever did anything like this.

**Comment by abn** [comment]
@elicutler is the issue that the ssh client is not available on the second machine? or is it that you cannot use ssh keys on the machine? If it is the former, I can see us allowing a fallback to paramiko via dulwich.

Alternatively, you can use http auth on your development machine to avoid changing the urls. See https://python-poetry.org/docs/master/dependency-specification/#git-dependencies.

**Comment by elicutler** [comment]
@abn The issue I believe is the latter, that SSH keys can't be used for accessing bitbucket from the second dev machine. However, it turns out HTTP auth on the first dev machine is in fact available, so I will just change pypoetry.toml to use the HTTP URL.

**Comment by dimbleby** [comment]
please close
