### ISSUE TITLE
Docker + poetry install on Google Cloud Build - inconsistent log lines

### ISSUE THREAD

**Issue by treecoder** [python-poetry/poetry#6072]
- [ ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu
- **Poetry version**: 1.1.13

## Issue

I am using Google Cloud Build for my CI pipeline to build a Docker image.
During `poetry install --no-dev`, the output looks something like this:

```shell
Step #0: Package operations: 44 installs, 0 updates, 0 removals
Step #0: 
Step #0:   • Installing pyasn1 (0.4.8)
tep #0:   • Installing cachetools (5.0.0)
Step #0:   • Installing certifi (2021.10.8)
Step #0:   • Installing charset-normalizer (2.0.12)
Step #0:   • Installing idna (3.3)
Step #0:   • Installing protobuf (3.19.4)
Step #0:   • Installing pyasn1-modules (0.2.8)
Step #0:   • Installing rsa (4.8)
Step #0:   • Installing six (1.16.0)
ep #0:   • Installing urllib3 (1.26.8)
tep #0:   • Installing google-auth (2.6.0)
Step #0:   • Installing googleapis-common-protos (1.55.0)
Step #0:   • Installing grpcio (1.44.0)
Step #0:   • Installing pyparsing (3.0.7)
Step #0:   • Installing requests (2.27.1)
ep #0:   • Installing google-api-core (2.7.1)
Step #0:   • Installing google-crc32c (1.3.0)
Step #0:   • Installing grpcio-status (1.44.0)
Step #0:   • Installing httplib2 (0.20.4)
)
Step #0:   • Installing google-auth-httplib2 (0.1.0)
Step #0:   • Installing google-cloud-core (2.2.3)
Step #0:   • Installing google-resumable-media (2.3.2)
Step #0:   • Installing msgpack (1.0.3)
Step #0:   • Installing packaging (21.3)
Step #0:   • Installing proto-plus (1.20.3)
Step #0:   • Installing uritemplate (4.1.1)
tep #0:   • Installing cachecontrol (0.12.10)
Step #0:   • Installing dnspython (2.2.0)
```

Note that on some lines it is only "ep" or "tep" instead of "Step". On one of the lines, there is the ")".
I am not sure if this is because of Docker or Poetry.

**Comment by Secrus** [comment]
The "Step" part is not from Poetry. Probably Docker TUI framework fighting with Poetry TUI framework (Cleo). Don't think it's something really actionable. Is it something of great significance to you?

**Comment by treecoder** [comment]
Nope. Not at all.
I just created a report here thinking this could be a console printing issue from Poetry side.
Closing this then.
