### ISSUE TITLE
Poetry may send credentials to a hacker controlled server

### ISSUE THREAD

**Issue by kamrup** [python-poetry/poetry#6075]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Fedora 35
- **Poetry version**: 1.1.14
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/kamrup/8965ee09116b386f250086a8180975c2

## Issue
TLDR: Poetry may send your private repository credentials to a hacker controlled server if you run `poetry install` in a hacker controlled project.

I'm not sure whether you would characterize this as a security issue, as you probably shouldn't run `poetry install` in any random project anyway, at least not without verifying that it doesn't do anything malicious beforehand.

### How to reproduce

1. The victim uses a private PyPi repository in one of her projects and has configured credentials for it: `poetry config http-basic.private-pypi-repo janedoe secret_p@a$$w0rd`
2. The hacker guesses the name of that repository and creates a project with this [pyproject.toml](https://gist.github.com/kamrup/8965ee09116b386f250086a8180975c2)
3. The hacker makes the victim run `poetry install` in that project.
4. The victim's credentials have now been sent off to https://malicious-site

### Possible way to fix this
Require that credentials correspond to a locally configured repository URL and then verify that both the name and URL in `pyproject.toml` matches the local configuration.
Then in step 3. above, `poetry install` would fail since the locally configured repository URL wouldn't match the one in `pyproject.toml`.

**Comment by dimbleby** [comment]
If an attacker can persuade a user to `poetry install` their `pyproject.toml` then it's already game over because they can install any package they like and run arbitrary code at install time.

(The same is true if an attacker can persuade a user to `pip install -r` a `requirements.txt` of their choice.)

Not to say that this is wrong, exactly, but in that context I'm not sure it's worth special treatment.

**Comment by neersighted** [comment]
`poetry install` already implies arbitrary code execution of Python, from any dep in the tree. I'm not sure this is even worth noting in the docs, but I think we should leave this issue open for a little bit to see if anyone else has input.

**Comment by kamrup** [comment]
I just discussed the problem with a colleague and it's not only a credential leak issue but also a name-clash issue:

You'll get into problems if you have two projects using different repositories (requiring different credentials) but the same repository name. Then you'll have to reconfigure your credentials depending on which project you are working on, or change the name used in one of the projects (which may not be possible if you aren't the maintainer).

Extending on "_Possible way to fix this_" these two issues could be solved by:

* Getting rid of the repository name in `pyproject.toml` (or start ignoring it) and start using only the URL to lookup credentials.
* When configuring credentials, require that you have configured a repository URL beforehand.
* Start using the repository name as a UI-only feature and only to refer to your local configuration (i.e. not `pyproject.toml`).
  I.e. it will still be possible to e.g. `poetry add --source=<repository name> mypackage` and `poetry config http-basic.<repository name> ...`.
