### ISSUE TITLE
Allow `poetry build` to create "editable" wheels

### ISSUE THREAD

**Issue by edgarrmondragon** [python-poetry/poetry#6080]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

Sometimes it's desirable to build a wheel that installs the package in "editable mode", just like [editables](https://pypi.org/project/editables/) does.

If the feature is of interest, perhaps it can be enabled with an `--editable` flag for `poetry build` that only works when the format is not `sdist`.

**Comment by finswimmer** [comment]
Hey @edgarrmondragon,

can you explain your use case for this a little bit more please?

fin swimmer

**Comment by Secrus** [comment]
Closing, since no response from the author.
