### ISSUE TITLE
cache-dir doesn't seem to work for repository_cache_directory

### ISSUE THREAD

**Issue by vmaurin** [python-poetry/poetry#6082]
- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 22.04
- **Poetry version**: 1.1.14

## Issue

When running a poetry lock command, the repository_cache_directory is still in my home folder, despite the fact I have set cache-dir config

```bash
developer@ce0157dc003a:/opt/app$ poetry config --list
cache-dir = "/opt/app/.cache/pypoetry"
experimental.new-installer = true
installer.parallel = true
virtualenvs.create = true
virtualenvs.in-project = true
virtualenvs.path = "{cache-dir}/virtualenvs"  # /opt/app/.cache/pypoetry/virtualenvs

developer@ce0157dc003a:/opt/app$ poetry lock
Updating dependencies
Resolving dependencies... (98.7s)

developer@ce0157dc003a:/opt/app$ ls /opt/app/.cache/pypoetry/
artifacts

developer@ce0157dc003a:/opt/app$ ls ~/.cache/pypoetry/cache/
repositories
```

The expected behavior would be to see `cache/repositories/` inside the cache-dir, not my HOME .cache

Looking in the code, I am not sure I am seeing an obvious reason for that, maybe lock is using the default config ?

It might be that my issue is similar to https://github.com/python-poetry/poetry/issues/2519

**Comment by Secrus** [comment]
Could you try this with Poetry 1.2.0b3? I think it should be fixed there.

**Comment by vmaurin** [comment]
It is working as expected with 1.2.0b3. Now I understand, I was looking to the master branch code, and not the 1.1 version. Do you think it is possible to backport this fix to 1.1 or should we go for the 1.2 version ?

**Comment by Secrus** [comment]
Go with 1.2. We won't do any backports or releases with the 1.1 version (unless something crucial breaks in 3rd party API like it was with the 1.1.14 release).

**Comment by vmaurin** [comment]
Got it, thank you for the help and the insights !
