### ISSUE TITLE
a way to enforce the poetry version in `pyproject.toml`

### ISSUE THREAD

**Issue by DetachHead** [python-poetry/poetry#6088]
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

i would like to be able to pin the poetry version in `pyproject.toml` to make sure that other developers working on my project do not generate incompatible `poetry.lock` files.

apparently you can set the version in `build-system.requires`, but that's only for building wheels? my project does not build wheels so other collaborators will never get an error if they're using an incorrect version of poetry.

**Comment by finswimmer** [comment]
Hey @DetachHead,

this was asked for earlier in https://github.com/python-poetry/poetry/issues/3316

fin swimmer
