### ISSUE TITLE
FAQ entry - Using poetry in a Github Action

### ISSUE THREAD

**Issue by sffjunkie** [python-poetry/poetry#6090]
## Issue
This is a possible FAQ entry for using `poetry` within a Github Action (with in my case `pytest` but probably for other tools as well.)

An action I set up wasn't finding packages installed with poetry in a previous step.

To fix this I added `source $(poetry env info -p)/bin/activate` before the `pytest` command to activate the virtualenv.

```
      - name: Test with pytest
        run: |
          source $(poetry env info -p)/bin/activate
          pytest
```

**Comment by Secrus** [comment]
The way Poetry and surrounding projects (tomlkit, cleo, poetry-core) have GH Actions set up, might be a good reference point.

**Comment by dimbleby** [comment]
duplicate #5772

**Comment by Secrus** [comment]
Closing as duplicate.
