### ISSUE TITLE
Regression in Poetry 1.2.0: modifies dots in package names to dashes

### ISSUE THREAD

**Issue by hwalinga** [python-poetry/poetry#6092]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Debian 11
- **Poetry version**: 1.2.0
 

## Issue

The beta release of poetry 1.2.0 is modifying dots to dashes again. This used to be fixed here https://github.com/python-poetry/poetry/pull/115 but the problem reappeared. 

Pinging @bertjwregeer as you have fixed this in the past. 

For example for `ruamel.yaml`, dependency of `drf-yasg`.

**Comment by dimbleby** [comment]
not a regression but a fix - this is the correct normalization.

What problem is this causing you?

**Comment by bertjwregeer** [comment]
@dimbleby does it allow you to install packages with dots in them? For example: "zope.sqlalchemy"? Or "ruamel.yaml".

That is why I originally made the fix.

**Comment by dimbleby** [comment]
yes, as you easily can verify

**Comment by hwalinga** [comment]
Yes, it will install packages with dots, but compatibility will break with older lock files.

TOML will accept names with dots just fine.

**Comment by dimbleby** [comment]
> compatibility will break with older lock files.

please explain what you mean: what are you doing, and what is going wrong?

**Comment by hwalinga** [comment]
Yes, but not the other way around. 

Here is how to repeat: 

```sh
curl -sSL https://install.python-poetry.org | POETRY_PREVIEW=1 python3 -
poetry new test-dots-new-to-old
cd new test-dots-new-to-old
poetry add drf-yasg
poetry install
curl -sSL https://install.python-poetry.org | python3 -
poetry install
```

Gives: 

```(demap-kqoNszLJ-py3.10) ~/tmp/test-dots-new-to-old                                                                                                            
» poetry --version
Poetry version 1.1.14

(demap-kqoNszLJ-py3.10) ~/tmp/test-dots-new-to-old                                                                                                            
» poetry install  
Installing dependencies from lock file

  SolverProblemError

  Because no versions of drf-yasg match >1.21.3,<2.0.0
   and drf-yasg (1.21.3) depends on ruamel.yaml (>=0.16.13), drf-yasg (>=1.21.3,<2.0.0) requires ruamel.yaml (>=0.16.13).
  So, because no versions of ruamel.yaml match >=0.16.13
   and test-dots-new-to-old depends on drf-yasg (^1.21.3), version solving failed.

  at ~/.local/share/pypoetry/venv/lib/python3.10/site-packages/poetry/puzzle/solver.py:241 in _solve
      237│             packages = result.packages
      238│         except OverrideNeeded as e:
      239│             return self.solve_in_compatibility_mode(e.overrides, use_latest=use_latest)
      240│         except SolveFailure as e:
    → 241│             raise SolverProblemError(e)
      242│ 
      243│         results = dict(
      244│             depth_first_search(
      245│                 PackageNode(self._package, packages), aggregate_package_nodes
```

**Comment by dimbleby** [comment]
Yep, that's true.

However I think it's unlikely that it'll be fixed, the solution is to upgrade your poetry.

(Previously we hit infinite loops as poetry confused itself about the difference between foo.bar and foo-bar, that's much worse).
