### ISSUE TITLE
The `include` doc is missing the `type` key

### ISSUE THREAD

**Issue by mgorny** [python-poetry/poetry#6094]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue
https://python-poetry.org/docs/pyproject/#include-and-exclude

The first example states:

```
[tool.poetry]
# ...
include = ["CHANGELOG.md"]
```

However, this will cause the ChangeLog to be included in the wheel, and therefore installed into `site-packages`! In fact, it doesn't seem that the `{ path = ..., type = ... }` variant is documented at all.

**Comment by RichardBruskiewich** [comment]
I've just noted a similar issue, again somewhat inspired by the same document section... in that I added the following directive to a **pyproject.toml** file:

```
include = [
    "CHANGELOG.md",
    { path = "tests" },
    { path = "docs" }
]
```
triggers a `IndexError: list index out of range` exception reading in deep in the toml **decoder.py** module here:

```python
                    while (not self.bounded_string(ab) or
                           (len(ab) > 2 and
                            ab[0] == ab[1] == ab[2] and
                            ab[-2] != ab[0] and
                            ab[-3] != ab[0])):
                        a[b] = a[b] + ',' + a[b + 1]  # <= site of error
```
but this error is not triggered either by 

```
include = [
    "CHANGELOG.md"
]
```
alone, nor

```
include = [
    { path = "tests" },
    { path = "docs" }
]
```
alone.

I guess I'll remove one or the other components of the include, but it would be helpful to know what's happening (and fix it!) or, at least, document the constraints of `include` usage accordingly.

**Comment by dimbleby** [comment]
This issue seems to be asking for documentation of an option that doesn't exist.

`format` exists, and the examples in the documentation do include examples of that.

please close
