### ISSUE TITLE
Poetry does not find hashes for `looseversion==1.0.1`

### ISSUE THREAD

**Issue by ahal** [python-poetry/poetry#6104]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 20.04 (WSL)
- **Poetry version**: 1.1.14

## Issue
Poetry does not grab any hashes for `looseversion==1.0.1`. This is reproducible with the following contrived example:
```
$ ls
pyproject.toml
$ cat pyproject.toml
[tool]

[tool.poetry]
name = "poetry-test"
description = ""
version = "0"
authors = []

[tool.poetry.dependencies]
python = "^3.6"
looseversion = "==1.0.1"
```

Now run lock:
```
$ poetry lock -vvv
Using virtualenv: ~/.cache/pypoetry/virtualenvs/poetry-test-jYNuYAZf-py3.10
Updating dependencies
Resolving dependencies...
   1: fact: poetry-test is 0
   1: derived: poetry-test
   1: fact: poetry-test depends on looseversion (==1.0.1)
   1: selecting poetry-test (0)
   1: derived: looseversion (==1.0.1)
PyPI: 1 packages found for looseversion 1.0.1
   1: selecting looseversion (1.0.1)
   1: Version solving took 0.005 seconds.
   1: Tried 1 solutions.

Writing lock file
```

Notice how hashes are missing:
```
$ cat poetry.lock
[[package]]
name = "looseversion"
version = "1.0.1"
description = "Version numbering for anarchists and software realists"
category = "main"
optional = false
python-versions = ">=3"

[metadata]
lock-version = "1.1"
python-versions = "^3.6"
content-hash = "ca07de38c66a51c2ec36155db9f2d3c67f663fda7b772380df80681904b73140"

[metadata.files]
looseversion = []
```

As far as I can tell, the hashes for this package are [readily available](https://pypi.org/project/looseversion/1.0.1/#files).

**Comment by Secrus** [comment]
Did you clear your cache after updating to 1.1.14 version?

**Comment by ahal** [comment]
Thanks, that was it.

Fixed by running `poetry cache clear pypi --all`
