### ISSUE TITLE
I can't uninstall poetry

### ISSUE THREAD

**Issue by AnnaCanada** [python-poetry/poetry#6107]
Good day, I am sorry that I have to bother you, but I have a problem with poetry. I can't delete poetry from my system. 
![Screenshot from 2022-08-03 13-43-57](https://user-images.githubusercontent.com/91414670/182589791-ca9fa642-6eb3-40ac-80a2-f1861bb8b2d7.png)

**Comment by mkniewallner** [comment]
Are you sure you installed Poetry with the official installer, and not by other means, like with [pipx](https://github.com/pypa/pipx)?
Do you have a `~/.local/bin/poetry` or `~/.poetry/bin` directory on your system?
What does `which poetry` return?

**Comment by mkniewallner** [comment]
Closing, since we had no answer. Feel free to re-open if you still encounter the issue.

**Comment by mgarbade** [comment]
is it save to simply remove `~/.local/bin/poetry`?
