### ISSUE TITLE
Why does running jupyter notebook use different python? 

### ISSUE THREAD

**Issue by lena-kru** [python-poetry/poetry#6115]
I try to import something from my project inside notebook.

And I unexpectedly got an error `ModuleNotFoundError: No module named 'amr'`

My `poetry env info` is

```
Virtualenv
Python:         3.8.13
Implementation: CPython
Path:           /home/krupenina/anaconda3/envs/amr
Valid:          True

System
Platform: linux
OS:       posix
Python:   /home/krupenina/anaconda3/envs/amr
```
But when I run jupyter notebook `poetry run jupyter notebook` and tried to check the python version I got

`/home/krupenina/anaconda3/bin/python`.

I tried to use `poetry shell` but I got the same result.

The project structure is

```
.
├── amr
│   ├── __init__.py
│   └── ...
├── amr_config.yaml
├── data
│   ├── ...
├── install_nltk_dependencies.py
├── notebooks
│   ├── ...
├── poetry.lock
├── pyproject.toml
└──README.md
```

Why does it happen? And what is the way to change that? Only use kernels or change python manually?

**Comment by finswimmer** [comment]
Hello @lena-kru,

you haven't come back to this issue for a long while. So I assume this is solved in the meantime and I can close this ticket.

Feel free to leave a comment if you disagree.

fin swimmer
