### ISSUE TITLE
Chained path dependencies fail to add/install

### ISSUE THREAD

**Issue by albertogomcas** [python-poetry/poetry#6116]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows 10
- **Poetry version**: 1.1.14
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: n/a

## Issue

I have three packages (on the same repo):
```
myrepo/A
myrepo/B
myrepo/C
```

A (no dependencies), all ok
B with a dependency like: A =path = "../A", develop = true}, which was added with `poetry add ../A/` while being in myrepo/B
C with a dependency like: B={path = "../B", develop = true}, which cannot be added with `poetry add ../B/` while being in myrepo/C

The error when I execute `poetry add ../B/` is `ValueError: Directory ..\A does not exist`

I don't understand why it fails (even if it would fail to make cwd on the package B source folder while it is being installed ../A is still correct from the context of myrepo/C)

**Comment by finswimmer** [comment]
Hello @albertogomcas,

you haven't come back to this issue for a long while. So I assume this is solved in the meantime and I can close this ticket.

Feel free to leave a comment if you disagree.

fin swimmer
