### ISSUE TITLE
Importlib doesn't get updated __version__ after it is changed in pyproject.toml and `poetry update`

### ISSUE THREAD

**Issue by aatkinson** [python-poetry/poetry#6119]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 20.04.1 LTS on WSL 2
- **Poetry version**: 1.1.14
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: [][Gist](https://gist.github.com/aatkinson/3fb785de2f901c00a81185c93dbf1bbd)

## Issue
When I update the version of my poetry package in pyproject.toml, the new version isn't reflected in importlib
Importlib grabs the version of the package when it was first installed
This is problematic when testing in a dev environment, eg some tests or code depends on __version__

Package has right version when `pip freeze` though
Happens with latest poetry and `importlib-metadata==4.12.0`

### Steps to reproduce
1. `pip install poetry==1.1.14` 
2. `poetry install` your package, at version 0.2.6
3. Change `[tool.poetry]:version` in pyproject.toml. Bump version to say 0.2.7
4. `poetry update`
5. `import importlib.metadata; print(importlib.metadata.version("mypkg")`

### Expected
5. 0.2.7

### Actual
5. 0.2.6

**Comment by dimbleby** [comment]
rerun `poetry install`

**Comment by Secrus** [comment]
`poetry update` only updates project dependencies. Changes to the project itself like new/changed scripts or, like in this case, version, require `poetry install`.

**Comment by aatkinson** [comment]
Got it, thanks, fixed the issue for me. Closing
