### ISSUE TITLE
[since 1.2.0b1] Docs are not up to date with the functionality of "poetry install --only" 

### ISSUE THREAD

**Issue by 1oglop1** [python-poetry/poetry#6122]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: 
- **Poetry version**: 1.2.0b3 
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: [pyproject.toml](https://gist.github.com/1oglop1/35755bb749f166676bbce4306c5a8a2c)

## Issue

This PR introduced that `--only` also installs `root` by default. https://github.com/python-poetry/poetry/pull/5338 
However, docs are not up to date and say that `root` is not installed.

https://github.com/python-poetry/poetry/blob/93b313b790c13267f7df87e383c61610fd732d0f/docs/cli.md?plain=1#L221-L222

Also, the note in Changelog.MD seems to be missing.

**Comment by dimbleby** [comment]
well this was clearly deliberate - https://github.com/python-poetry/poetry/commit/c52a21304af5d4dc11a98d7ada32bae9cbe54fa0 - so I guess it's a docs problem now

**Comment by 1oglop1** [comment]
Thanks for pointing out the commit, I was not able to find it since I'm not so familiar with the codebase. 
I read the PR and I agree with it. I wanted to see the discussion but the link gave me 404 https://github.com/orgs/python-poetry/teams/core/discussions/8 

@dimbleby If there isn't an existing issue we can repurpose this one to misleading docs or close and open a specific issue. Let me know your preference.

**Comment by radoering** [comment]
Yeah, seems the discussion is internal. Reasoning was:

> I think we should go with the simplest and least surprising behavior: the install command should always install the current project – regardless of group options – unless --no-root is used.
> 
> This will simplify the implementation and makes more sense since the root project is not part of any group and, as such, should not be impacted by any group option.

Imho it's not necessary to close and open a new issue.

**Comment by 1oglop1** [comment]
I updated the ticket to reflect that this is a docs issue. Unfortunately, I do not have enough time to contribute to this change, yet.
