### ISSUE TITLE
PEP 427 not fully supported?

### ISSUE THREAD

**Issue by melMass** [python-poetry/poetry#6123]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Any
- **Poetry version**: 1.1.14
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: Not relevant but I can provide if really needed.

## Issue
I'm trying to use the "dirty trick" allowed by [PEP 427](https://peps.python.org/pep-0427/#file-name-convention)'s build tag.

This means that if you publish `0.5.0.whl` you are allowed to also publish `0.5.0-1.whl`, this registers as the same version but a newer build.
To do that I simply renamed the wheel after `poetry build`, I did rename the tar source accordingly but only the wheel is published:

![image](https://user-images.githubusercontent.com/7041726/183128550-fc8c3dc2-6650-42bf-9430-78a871bf7ab2.png)

This is working in plain pip, it properly fetches the latest wheel, but not in poetry. I managed to trick it by manually editing the lock file's whl name and SHA but I wonder if there is a better way? I don't plan to rely on this trick a lot but it can save bad situations.

You can live test it from the package I published here: https://pypi.org/project/mtb-log:

```ruby
pip install mtb-log 
Collecting mtb-log
  Downloading mtb_log-0.5.0-1-py3-none-any.whl (11 kB)
Installing collected packages: mtb-log
Successfully installed mtb-log-0.5.0
```
whereas poetry fetches the first one only.

Thanks

**Comment by melMass** [comment]
So I was wrong, pip requires `--no-cache-dir` to actually refetch the last build.
To mimick in poetry you can remove the entry from the lock, run `poetry cache clear pypi:mtb_log:0.5.0` .

I don't can't edit the type/label of the issue but maybe this is a feature request, something like adding `no-cache` to the dependency's dict like so:

```toml
mtb-log = {version = "^0.5.0", platform = "win32", no_cache = true}
```

**Comment by dimbleby** [comment]
latest code has a `--no-cache` option, sounds like that would do what you want

**Comment by melMass** [comment]
Oh nice indeed, pip is still on 1.1.14 I will update

**Comment by melMass** [comment]
All right all the issues I stumbled upon recently are solved by this release 😅 , I'll just wait:
https://github.com/python-poetry/poetry/releases/tag/1.2.0b3
