### ISSUE TITLE
Ctrl-C doesn't cancel poetry install on 1.2.0b3

### ISSUE THREAD

**Issue by xyxz-web** [python-poetry/poetry#6136]
If you run poetry install on 1.2.0.b3 you can't cancel the whole installation process by hitting Ctrl-C in Windows 10.
It only cancels the install of the current package and then resumes installation of the remaining packages.
This is bad if the list of packages to be installed is long and you really want to cancel.

**Comment by finswimmer** [comment]
Hey @xyxz-web,

if you think this issue still exists please open a new issue over at https://github.com/python-poetry/install.python-poetry.org.

fin swimmer
