### ISSUE TITLE
Poetry using linux-only `python3.x` commands with `env use 3.x` on windows.

### ISSUE THREAD

**Issue by laundmo** [python-poetry/poetry#6155]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows 10
- **Poetry version**: Poetry version 1.1.14

## Issue
On Windows, `poetry env use 3.10` tries to run `python3.10` which causes windows to throw an "is not recognized as a command" error.
Windows does not have any command called `python3.10` even if python 3.10 is installed - that way of specifying versions is linux-only.

On Windows the best approach to selecting version is to use the `py` command, `py -3.10` will act the same as `python3.10` on Linux.

**Comment by dimbleby** [comment]
duplicate #3520, please close
