### ISSUE TITLE
source command in windows

### ISSUE THREAD

**Issue by maheshs11** [python-poetry/poetry#6158]
https://python-poetry.org/docs/basic-usage#activating-the-virtual-environment

source {path_to_venv}\Scripts\activate.bat on Windows).

![image](https://user-images.githubusercontent.com/7268915/184468205-d8ed4bd7-8cda-4473-9f08-14def0747997.png)

it is working without source command on windows but throws error for source command.

**Comment by Secrus** [comment]
The requested change was already made.
