### ISSUE TITLE
poetry init error on windows

### ISSUE THREAD

**Issue by wn0x00** [python-poetry/poetry#6173]
[WinError 1920] 系统无法访问此文件。: 'C:\\Users\\32075\\AppData\\Local\\Microsoft\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\python.exe\\Scripts'

  at C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1776.0_x64__qbz5n2kfra8p0\lib\pathlib.py:1097 in stat
      1093│
      1094│         Return the result of the stat() system call on this path, like
      1095│         os.stat() does.
      1096│         """
    → 1097│         return self._accessor.stat(self, follow_symlinks=follow_symlinks)
      1098│ 
      1099│     def owner(self):
      1100│
      1101│         Return the login name of the file owner.

**Comment by Secrus** [comment]
Could you add information about what Python installation you use (official installer from Python.org or MS Store?), what Poetry version this error occurred on and what Poetry installation method you used? Right now it's hard to tell what could be the reason for this error without more data.

**Comment by finswimmer** [comment]
Hello @wn0x00 ,

you haven't come back to this issue for a long while. So I assume this is solved in the meantime and I can close this ticket.

Feel free to leave a comment if you disagree.

fin swimmer
