### ISSUE TITLE
UnicodeDecodeError with `get-poetry.py` script.

### ISSUE THREAD

**Issue by thoward27** [python-poetry/poetry#6176]
- **OS version and name**: MacOS and Ubuntu Linux
- **Poetry version**: 1.1.13

## Issue

Executing this curl-to-python script results in a failure while installing with `python2`. I know the plan is for this functionality to be deprecated in `v1.2`, but since I am trying to install a `v1.1.x` version, I assume this should still work.

```bash
curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/1.1.13/get-poetry.py | python - --version 1.1.13
```

The error is 

```bash
Traceback (most recent call last):
   File "<stdin>", line 1086, in <module>
   File "<stdin>", line 1082, in main
   File "<stdin>", line 352, in run
   File "<stdin>", line 415, in get_version
 UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 20: ordinal not in range(128)
```

The `get_version` call that is failing is

```python
...
            return "from an offline file", current_version

        print(colorize("info", "Retrieving Poetry metadata"))

        metadata = json.loads(self._get(self.METADATA_URL).decode()) # This is failing.

        def _compare_versions(x, y):
            mx = self.VERSION_REGEX.match(x)
            my = self.VERSION_REGEX.match(y)
...
```

The snippet of JSON it is complaining about is this

```
>>> val[10:25]
'author":"S\xc3\xa9bas'
```

The issue is resolved if I add `utf-8` into the decode arguments.

```
metadata = json.loads(self._get(self.METADATA_URL).decode("utf-8")) # This successfully loads
```

I would be more than happy to contribute a PR to fix, but I am not certain if this should target `master` or just the `1.1` branch, as this issue is not present in python3

**Comment by finswimmer** [comment]
Hello @thoward27,

thanks a lot that you like to contribute to Poetry. We really appreciate it :+1: 

However, we consider the get-poetry.py script as stale, because the new install script is working alternativ and we are hoping to release Poetry 1.2 soon.

fin swimmer

**Comment by thoward27** [comment]
The new installation method stipulates that it needs python3 to run, but poetry 1.1.x should still run under python2, shouldn't it? Is there any way to install 1.1.13 with python2?

**Comment by finswimmer** [comment]
You can simply pip-install Poetry (and cross fingers that no other package, you will pip-install afterwards, will break it).

I'm very sorry, if you belong to those people, who have to work with a software that is deprecated for 14 years now and is dead for more than two years (https://www.python.org/doc/sunset-python-2/). 

We've decided to not put any effort into supporting python2 because Poetry 1.2 will come soon.

**Comment by kelbyers** [comment]
@thoward27 

This workaround worked for me:
```
curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | \
    sed '/METADATA_URL/ s/\.decode()//' | \
    python - --no-modify-path
```
