### ISSUE TITLE
[BUG] Rendering glitch for ncurses applications after entering virtual environment

### ISSUE THREAD

**Issue by philipGaudreau** [python-poetry/poetry#6179]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 20.04
- **Poetry version**: 1.2.0b3
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: A project created through `poetry new test` will do.

## Issue
When instantiating a virtual environment and then resizing terminal window, the rendering of some  applications using *ncurses*, like *vim* and *tmux* gets glitchy. The first picture is the normal behavior (application uses all space before and after resize). The second picture has been produced like so: `poetry shell` in the project, then resizing the window, then opening *vim*.

<img width="600" alt="normal" src="https://user-images.githubusercontent.com/22773951/185007060-75e245b0-a1b4-461d-9d47-f0d3df94bbc4.png">
<img width="600" alt="abnormal" src="https://user-images.githubusercontent.com/22773951/185007057-dd9cf6d6-8c29-4f13-a9dc-c6dc087438c9.png">

**Comment by tony** [comment]
I also get this same behavior on 1.2.0

Side note: @philipGaudreau Do you use a tmux session manager (tmuxp, tmuxinator, teamocil), tmux scripting, or launch tmux by hand?

**Comment by neersighted** [comment]
Duplicate #6351
