### ISSUE TITLE
Incorrect version after poetry install

### ISSUE THREAD

**Issue by piotr-kubiak** [python-poetry/poetry#6188]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- Windows 10
- 1.1.14

## Issue
```
$ poetry new my-package
$ cd my-package/
$ poetry install
Installing dependencies from lock file
[stripped]
Installing the current project: my-package (0.1.0)

$ poetry run python -c 'from importlib.metadata import version; print (version("my-package"));'
0.1.0

$ poetry version patch
Bumping version from 0.1.0 to 0.1.1

$ poetry install
Installing dependencies from lock file

No dependencies to install or update

Installing the current project: my-package (0.1.1)

$ poetry run python -c 'from importlib.metadata import version; print (version("my-package"));'
0.1.0
```

I believe that the version number of my-package should be 0.1.1.

**Comment by finswimmer** [comment]
Hello @piotr-kubiak,

this is a known bug in 1.1 and is already fixed for a while in the master branch. You can check this by testing the latest preview release (1.2.0b3).

fin swimmer
