### ISSUE TITLE
Poetry run doesn't exit with the exit code from the CMD called

### ISSUE THREAD

**Issue by fbrodrigorezino** [python-poetry/poetry#6190]
I'm running poetry to run some checks, and when those checks fail I expect to return with <> 0, so the CI can also fail.
Though, `poetry run myscript.py` doesn't exit with the `myscript.py` exit code. How. can I make that happen?

**Comment by dimbleby** [comment]
works fine for me.  You'll have to provide more detail about how to reproduce.

Also you don't say what version of poetry you're using, try the latest beta.

**Comment by fbrodrigorezino** [comment]
Interesting, what happened, I created a `main.py` with nothing but the code `exit(1)`.
If I run `poetry run python main.py; echo $?` it shows 1, as expected. But If I put anything beyond 255, it starts to return wrong numbers, as it expected to get a small int. 
But my system is returning `512`, which if you check in `exit(512)` running from poetry, returns 0

**Comment by dimbleby** [comment]
You are trying to fit 10 bits into an 8-bit number

```
$ bash -c "exit 255" ; echo $?
255
$ bash -c "exit 256" ; echo $?
0
$ bash -c "exit 257" ; echo $?
1
```

This is nothing to do with poetry, please close.
