### ISSUE TITLE
InterpreterNotFound running tox locally

### ISSUE THREAD

**Issue by dhvcc** [python-poetry/poetry#6193]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 22.04
- **Poetry version**: master branch
- **Tox version**: 3.25.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://github.com/python-poetry/poetry/blob/master/pyproject.toml

## Issue

Hey, I encountered issues with running `tox` locally for this repo when working on an issue. I saw a similar error for different projects which were using `py37` notation instead of `python3.7`. May be this is an issue with `pyenv`/`conda` (but it still doesn't work if I don't initialize pyenv in my rc file). My suggestion would be to use `python{major}.{minor}` notation for tox as I believe it's more comptaible. I can confirm it's working for me that way, but for now unable to test on other machines. [Solution reference](https://stackoverflow.com/a/68413752/10691794). I'd like to test it more and possibly understand what's the issue, but would appreciate if somebody knows anything about it.

`py` is [an alias](https://tox.wiki/en/latest/config.html#conf-basepython) to `python`, so I think using `python` is a safer option anyways since then it works for everyone including at least me and, I guess, `conda` users. 

This is the log of `tox --verbose`

```
using tox.ini: /home/dhvcc/PycharmProjects/poetry/tox.ini (pid 224789)
using tox-3.25.0 from /home/dhvcc/.cache/pypoetry/virtualenvs/poetry-4pWfmigs-py3.10/lib/python3.10/site-packages/tox/__init__.py (pid 224789)
.package reusing: /home/dhvcc/PycharmProjects/poetry/.tox/.package
[224797] /home/dhvcc/PycharmProjects/poetry$ /home/dhvcc/PycharmProjects/poetry/.tox/.package/bin/python /home/dhvcc/.cache/pypoetry/virtualenvs/poetry-4pWfmigs-py3.10/lib/python3.10/site-packages/tox/helper/build_requires.py poetry.core.masonry.api '' '' >.tox/.package/log/.package-12.log
[224798] /home/dhvcc/PycharmProjects/poetry$ /home/dhvcc/PycharmProjects/poetry/.tox/.package/bin/python /home/dhvcc/.cache/pypoetry/virtualenvs/poetry-4pWfmigs-py3.10/lib/python3.10/site-packages/tox/helper/build_isolated.py .tox/dist poetry.core.masonry.api '' '' >.tox/.package/log/.package-13.log
package .tmp/package/1/poetry-1.2.0rc1.dev0.tar.gz links to dist/poetry-1.2.0rc1.dev0.tar.gz (/home/dhvcc/PycharmProjects/poetry/.tox)
py37 cannot reuse: no previous config /home/dhvcc/PycharmProjects/poetry/.tox/py37/.tox-config1
py37 create: /home/dhvcc/PycharmProjects/poetry/.tox/py37
ERROR: InterpreterNotFound: python3.7
py38 cannot reuse: no previous config /home/dhvcc/PycharmProjects/poetry/.tox/py38/.tox-config1
py38 create: /home/dhvcc/PycharmProjects/poetry/.tox/py38
ERROR: InterpreterNotFound: python3.8
py39 cannot reuse: no previous config /home/dhvcc/PycharmProjects/poetry/.tox/py39/.tox-config1
py39 create: /home/dhvcc/PycharmProjects/poetry/.tox/py39
ERROR: InterpreterNotFound: python3.9
__________________________________________________________________________________________________ summary ___________________________________________________________________________________________________
ERROR:  py37: InterpreterNotFound: python3.7
ERROR:  py38: InterpreterNotFound: python3.8
ERROR:  py39: InterpreterNotFound: python3.9

```

**Comment by finswimmer** [comment]
Hello @dhvcc,

I cannot see how this is related to Poetry. Looks more like tox issue/question.

So please add more information about why you think this is poetry related.

fin swimmer

**Comment by dhvcc** [comment]
Hi @finswimmer, it's not poetry-as-a-package related, but relates to this **repo**. I'm saying that even though this might be an issue with `tox`, I think it's still safer to use different notaion so that it surely for for **everyone**.

**Comment by mhwaage** [comment]
From the comments on the referenced solution:

> I just tried this myself. It seemed to work, but then I noticed it runs everything with the default Python (3.9 in my case)! I get messages with paths like /[pathredacted]/.tox/python3.7/lib/python3.9/site-packages/ in them ("python3.7" is the tox environment, and "python3.9" is the Python installed into it). I won't say it never works, but it apparently doesn't work on Linux with tox 3.24.3. – 
> [Tim Pederick](https://stackoverflow.com/users/3623267/tim-pederick)
>  [Aug 31, 2021 at 13:37](https://stackoverflow.com/questions/63180349/error-py37-interpreternotfound-python3-7-when-running-tox-from-github/68413752#comment121946697_68413752)
> July 2022 I still receive the issue pointed out By Tim Pederick, also on Ubuntu 22.04, and now my code is breaking because it is running Python3.10 even though tox says it's running Python3.9 – 
> [Justin Furuness](https://stackoverflow.com/users/8903959/justin-furuness)
>  [Jul 1 at 5:14](https://stackoverflow.com/questions/63180349/error-py37-interpreternotfound-python3-7-when-running-tox-from-github/68413752#comment128629273_68413752)
> @TimPederick is right, this is just using the most recent available python and not the specified one. You can change it to something crazy like python9000 and it'll still just "work" because that's not a predefined tag like py37 is. – 
> [Izkata](https://stackoverflow.com/users/500202/izkata)
>  [Jul 20 at 20:56](https://stackoverflow.com/questions/63180349/error-py37-interpreternotfound-python3-7-when-running-tox-from-github/68413752#comment129033124_68413752)

The proposed change seems like it would actually break the tox settings.

**Comment by Secrus** [comment]
We no longer have tox support for our repo, so I consider this issue resolved.

**Comment by dhvcc** [comment]
Right, thanks for the update!
