### ISSUE TITLE
Wheel missing files generated at build

### ISSUE THREAD

**Issue by egorchakov** [python-poetry/poetry#6197]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS 12.3k
- **Poetry version**: 1.2.0b3
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue 
Python files generated during a build step (protobufs in my original case) don't make it into the wheel built with `poetry build`.

I do realize based on previous discussions around here that this particular combo is perhaps somewhat non-standard:
```toml
[tool.poetry.build]
generate-setup-file = true
script = "build.py"
```

I've put together a minimal project to demonstrate the issue at https://github.com/egorchakov/poetry-build-issue. To reproduce:

1. clone the repo:
```
git clone https://github.com/egorchakov/poetry-build-issue
cd poetry-build-issue
```

2. build:
```
make cleanbuild
```

3. unzip the resulting wheel:
```
unzip dist/*.whl -d dist/wheel
```

4. observe that the wheel is missing a file generated during a build step:
```
 ls dist/wheel/poetry_build_issue/generated
```

**Comment by robtaylor** [comment]
I'm also hitting this issue with a project that generates scripts for install. The problem seems to be that poetry-core only sources its list of scripts from local_config (in `poetry.core.masonry.Builder.convert_script_files`). Its not immediately obvious what a sensible fix would be.

I'm probably going to do some script stubs to get around the issue.

**Comment by robtaylor** [comment]
oh actually, maybe it is relatively simple to fix - in WheelBuilder._build look for `scripts-${PYVER}` in `self._path / "build"` and then add them appropriately .

I could probably throw a patch together tomorrow if there is interest

**Comment by egorchakov** [comment]
FWIW I ended up with a hacky workaround: renaming the `lib` dir to `lib.blah` in order to match the `"lib."` glob from https://github.com/python-poetry/poetry-core/blob/main/src/poetry/core/masonry/builders/wheel.py#L184:

```python
# build.py
from setuptools.command.build_py import build_py

class BuildPyCommand(build_py):
    def finalize_options(self):
        super().finalize_options()
        self.build_lib = f"{self.build_lib}.blah"

    def run(self):
        ...


def build(setup_kwargs):
    setup_kwargs.update(
        {
            "cmdclass": {
                "build_py": BuildPyCommand,
            },
        }
    )

```

**Comment by dimbleby** [comment]
> FWIW I ended up with a hacky workaround: renaming the lib dir to lib.blah in order to match the "lib." glob from https://github.com/python-poetry/poetry-core/blob/main/src/poetry/core/masonry/builders/wheel.py#L184:

the needed fix is probably as simple as changing that glob, then
