### ISSUE TITLE
poetry removes all wheels sometimes... randomly

### ISSUE THREAD

**Issue by earonesty** [python-poetry/poetry#6199]
When i ran `poetry update --lock notanorm` , poetry decided to zero-out all of the wheels and hashes in my file

Is this because i'm on windows and the original developer was on linux?

Shouldn't poetry fail if it can't generate a valid lockfile?   This is really bad for security, which is one of the primary jobs of a lockfile
```
-typing-extensions = [
-    {file = "typing_extensions-4.3.0-py3-none-any.whl", hash = "sha256:25642c956049920a5aa49edcdd6ab1e06d7e5d467fc00e0506c44ac86fbfca02"},
-    {file = "typing_extensions-4.3.0.tar.gz", hash = "sha256:e6d2677a32f47fc7eb2795db1dd15c1f34eff616bcaf2cfb5e997f854fa1c4a6"},
-]
-urllib3 = [
-    {file = "urllib3-1.26.11-py2.py3-none-any.whl", hash = "sha256:c33ccba33c819596124764c23a97d25f32b28433ba0dedeb77d873a38722c9bc"},
-    {file = "urllib3-1.26.11.tar.gz", hash = "sha256:ea6e8fb210b19d950fab93b60c9009226c63a28808bc8386e05301e25883ac0a"},
-]
+typing-extensions = []
+urllib3 = []
```

**Comment by dimbleby** [comment]
#5970, clear your cache, use a recent poetry

**Comment by finswimmer** [comment]
In addition to @dimbleby : https://python-poetry.org/blog/announcing-poetry-1.1.14/
