### ISSUE TITLE
sdist dont use tool.poetry.source

### ISSUE THREAD

**Issue by djkcyl** [python-poetry/poetry#6202]
Even though I fill in `tool.poetry.source` in `pyproject.toml`, poetry still can't resolve dependencies quickly. and always times out. It seems that no matter what I do, poetry always gets stuck on a step

my nginx conf
```conf
server {
	server_name localhost;
	listen 80 default_server;

	location /simple {
		proxy_pass https://pypi.org;
		proxy_set_header Host pypi.org;
		proxy_set_header Accept-Encoding "identity";
		proxy_ssl_name pypi.org;
		proxy_ssl_server_name on;
		sub_filter_once off;
		sub_filter ://files.pythonhosted.org/ ://$host/;
	}
	location /packages {
		proxy_pass https://files.pythonhosted.org;
		proxy_set_header Host files.pythonhosted.org;
		proxy_ssl_name files.pythonhosted.org;
		proxy_ssl_server_name on;
	}
}
```

**Comment by dimbleby** [comment]
Not clear what you're asking for here.  What is the poetry bug?  What would you like poetry to do differently?

**Comment by djkcyl** [comment]
In my testing, I found that poetry does not use `tool.poetry.source` during the download of **sdist**, which is very unfriendly to some regions that cannot access pypi.org

![image](https://user-images.githubusercontent.com/59153990/185760444-85c1026f-b763-4f2c-8524-16336b286990.png)

**Comment by dimbleby** [comment]
still not clear what you think the bug is.  poetry will download sdists from wherever the repository tells it that the sources live - what are you expecting to happen?

**Comment by dimbleby** [comment]
NB you can create a source with "default = true" to stop using pypi altogether if you have some other repository that works better for you

**Comment by djkcyl** [comment]
> NB you can create a source with "default = true" to stop using pypi altogether if you have some other repository that works better for you - https://python-poetry.org/docs/repositories/#disabling-the-pypi-repository

![image](https://user-images.githubusercontent.com/59153990/185760861-e159e5da-41ef-4b10-b4b4-2258439ca303.png)

**Comment by dimbleby** [comment]
if your `aunly` repository says that sdists live on pypi.org, then that's where poetry will get them from

**Comment by djkcyl** [comment]
But according to the picture above, regardless of whether other sources are set, pypi.org will still be accessed when downloading sdist (maybe not), in short, poetry will access pypi at a certain step and cause the process to get stuck

**Comment by djkcyl** [comment]
> if your `aunly` repository says that sdists live on pypi.org, then that's where poetry will get them from

ok let me check

**Comment by djkcyl** [comment]
> if your `aunly` repository says that sdists live on pypi.org, then that's where poetry will get them from

> https://pypi-test.xxxxxxxxx.xxx/packages/f4/66/17b8e95770478436bf968353c89683ce6f9e14d92e0d4fb3111c09ba18d2/numpy-1.23.2.tar.gz#sha256=b78d00e48261fbbd04aa0d7427cf78d18401ee0abd89c7559bbf422e5b1c7d01

I think my mirror is fine
![image](https://user-images.githubusercontent.com/59153990/185761302-8deb4bcc-1933-4baa-bbc8-365c559822d6.png)
![image](https://user-images.githubusercontent.com/59153990/185761304-c9f21848-adb3-43d8-b5f2-3ea3bc675dc2.png)

**Comment by djkcyl** [comment]
Is poetry likely to return pypi after a timeout?

**Comment by dimbleby** [comment]
no, poetry simply doesn't use pypi if you have a default repository instead.  I know this works because this is what we do at $WORK.

I don't know what you're seeing.  Which pages is something trying to read?

Perhaps you are installing a package which tries to access pypi during its own setup?!?

**Comment by djkcyl** [comment]
> no, poetry simply doesn't use pypi if you have a default repository instead. I know this works because this is what we do at $WORK.
> 
> I don't know what you're seeing. Which pages is something trying to read?
> 
> Perhaps you are installing a package which tries to access pypi during its own setup?!?

yep

I use poetry add nuppy@latest -vvv to add a package, but it gets stuck somewhere and through the traffic monitor I can see that poetry is trying to access pypi, which obviously doesn't work

**Comment by dimbleby** [comment]
what I am suggesting is that it is not _poetry_ that is trying to access pypi but code in the setup of `nuppy` or whatever.

Does the same happen for every package that you install, or only for some?  Do you have a `pip.conf` telling `pip` to avoid pypi?

**Comment by djkcyl** [comment]
ok. I'm setting up my pip conf and retesting

**Comment by djkcyl** [comment]
I think I understand that the process is stuck because setup.py is executing something else

**Comment by djkcyl** [comment]
But why does it get stuck in `Download sdist` instead of the final installation stage

**Comment by dimbleby** [comment]
eg there are cases where poetry has to attempt install of a source package (because no other mechanism is available) to figure out dependencies.  There may be other reasons.

Sounds like this is good to close, then?

**Comment by djkcyl** [comment]
Ok, thanks for your help, I understand
