### ISSUE TITLE
Import/depend poetry packages

### ISSUE THREAD

**Issue by keriksson-rosenqvist** [python-poetry/poetry#6209]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

I have a number of related packages, all stored locally and with their own individual pyproject.toml files. I would like to be able to set up a new pyproject.toml file in a separate directory and add them as imports or dependencies, pulling in all sub-dependencies etc. with them. I know I could achieve this by building wheels and installing, but I want this in my development environments and without having to build and install.

**E.g.**
Structure
```
.
├── package_a/
│   ├── pyproject.toml
│   ├── poetry.lock
│   └── src/
├── package_b/
│   ├── pyproject.toml
│   ├── poetry.lock
│   └── src/
├── pyproject.toml
└── poetry.lock
```

root pyproject.toml example
```
[tool.poetry]
# ...
packages = [
    { include = "package_a", from = "pyproject" },
    { include = "package_b", from = "pyproject" },
]

OR

[tool.poetry.dependencies]
# ...
package_a = { poetry = "./package_a" }
package_b = { poetry = "./package_b" }

```

**Comment by dimbleby** [comment]
Did you really search the documentation?

**Comment by keriksson-rosenqvist** [comment]
> Did you really search the documentation?
> 
> https://python-poetry.org/docs/dependency-specification/#path-dependencies

So that is a path to a built package, I want it to load directly from the pyproject.toml/poetry.lock files and source code folder, without requiring to build the package.

**Comment by dimbleby** [comment]
> So that is a path to a built package

this is not true

**Comment by keriksson-rosenqvist** [comment]
> > So that is a path to a built package
> 
> this is not true

I agree that it does not have to be, but in the case it is a directory, will all dependencies from the package pyproject.toml file also be installed? If so, this functionality is not clear from the documentation.

**Comment by dimbleby** [comment]
why don't you try it?

**Comment by neersighted** [comment]
A path dependency is simply a Python project at a given path. Poetry conforms to PEP 517 and will build any project according to the steps there (we should support any pyproject.toml build-system as well as setuptools, with any combination of pyproject.toml/setup.cfg/setup.py). Poetry never supports built distributions as a path dependency for myriad reasons.

I'm not sure the docs are really deficient here as I feel that this is a very obvious set of assumptions common across the ecosystem (that is to say, being 'pip compatible') -- but if you have suggested improvements, please open a PR.

**Comment by keriksson-rosenqvist** [comment]
Still having issues getting the sub-package dev-dependencies installed. Can anyone help?

**Comment by dimbleby** [comment]
if A depends on B and B has dev dependencies, then it's expected that installing A will not install B's dev dependencies.

**Comment by keriksson-rosenqvist** [comment]
> if A depends on B and B has dev dependencies, then it's expected that installing A will not install B's dev dependencies.

OK but this is exactly what I want to do. Kind of "fuse" my development environments so that I can run things like integration tests in a single environment.

**Comment by neersighted** [comment]
Poetry dependencies do not have any special relationship currently. If you're looking for a unified development environment across projects, you're likely looking for workspace/monorepo support as requested in #936.

You could 'fake' this in the mean time by sharing a venv between projects, but obviously that is a bit brittle and you will have to manage your own guarantees vis-a-vis order of operations and compatibility.
