### ISSUE TITLE
Add `pip-audit` to poetry operations that touch the lockfile

### ISSUE THREAD

**Issue by tigerhawkvok** [python-poetry/poetry#6220]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

Adding a tool like [pip-audit](https://github.com/trailofbits/pip-audit) to operations that touch the lockfile adds a measure of security to Poetry. Poetry knows the source of the files and can, correctly, only inspect the dependencies that come directly from PyPI; and further, since Poetry stores hashes in the lockfile once a dependency is known safe it doesn't have to be checked again. This helps mitigate [PyPI poisoning](https://arstechnica.com/gadgets/2021/03/more-top-tier-companies-targeted-by-new-type-of-potentially-serious-attack/) attacks.

Possibly if performance is an issue its functionality (and the state of "is it default") can be a global Poetry config flag.

**Comment by dimbleby** [comment]
Way out of scope IMO.  If you like pip-audit, run pip-audit!

**Comment by finswimmer** [comment]
Hey @tigerhawkvok,

this is definitely something out of scope for Poetry. Maybe it's possible that somebody will provide a [plugin](https://python-poetry.org/docs/1.2/plugins/) in the future.

fin swimmer

**Comment by severo** [comment]
Related issue on pip-audit: https://github.com/pypa/pip-audit/issues/84. They suggest adding `poetry audit`
