### ISSUE TITLE
Update install directions with URL to install script for latest version of Poetry

### ISSUE THREAD

**Issue by jocassid** [python-poetry/poetry#6238]
- [ ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

The download script and run it commands for the various operating systems should have the new URL https://install.python-poetry.org/ instead of the old https://install.python-poetry.org/.  I went to https://python-poetry.org/docs/ clicked the "osx / linux / bashonwindows install instructions" which scrolled the page right past the "by the way the URL has changed" warning.  When I ran the script I saw the error page and switched to that script.  I think the download and run commands should be for the latest version of poetry.

**Comment by dimbleby** [comment]
I see you haven't checked the "I searched for duplicates" box.  Please do search for duplicates before raising issues.

This duplicates #6221 and, like that one, will be made redundant by the upcoming 1.2 release.

**Comment by neersighted** [comment]
Duplicate/resolved
