### ISSUE TITLE
Upgrade Pytest version to 7.1

### ISSUE THREAD

**Issue by Enforcer007** [python-poetry/poetry#6266]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 22.04
- **Poetry version**: 1.1.15

## Issue

Running `pytest` (^5.2) on default poetry project gives error: `TypeError: required field "lineno" missing from alias`.

It got to do with bug in python 3.10 [https://github.com/pytest-dev/pytest/pull/8540].

There's a fix for pytest given in version ^6.0. Checked with latest pytest version 7.1 there's no issue.

It also makes sense to upgrade pytest as 5.2 dates back to Sep 2019

**Comment by Secrus** [comment]
Since we release 1.2 tomorrow, we don't plan to apply any more changes to the 1.1 branch. This problem does not exist on 1.2+, as we don't install pytest in default projects.
