### ISSUE TITLE
Updating to Poetry 1.2.0 fails because of missing file (poetry-1.2.0-darwin.sha256sum)

### ISSUE THREAD

**Issue by jdmartin** [python-poetry/poetry#6269]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **macOS Monterey 12.5.1**: 
- **1.1.15**: 

## Issue

Hello!  

I am attempting to use `poetry self update` to update from 1.1.15 to 1.2.0 on Mac, but I am encountering a RuntimeError 'Could not find poetry-1.2.0-darwin.sha256sum file'.  That error, plus a stack trace, is as follows. (A TL;DR version in image format  is also provdied.)  Thanks, in advance, for any assistance... and, of course, thanks for all your hard work on Poetry!  I really love it. ❤️ 
> Stack trace:

>   6  .config/python/poetry/lib/poetry/_vendor/py3.10/clikit/console_application.py:131 in run
>       129│             parsed_args = resolved_command.args
>       130│
>     → 131│             status_code = command.handle(parsed_args, io)
>       132│         except KeyboardInterrupt:
>       133│             status_code = 1
> 
>   5  .config/python/poetry/lib/poetry/_vendor/py3.10/clikit/api/command/command.py:120 in handle
>       118│     def handle(self, args, io):  # type: (Args, IO) -> int
>       119│         try:
>     → 120│             status_code = self._do_handle(args, io)
>       121│         except KeyboardInterrupt:
>       122│             if io.is_debug():
> 
>   4  .config/python/poetry/lib/poetry/_vendor/py3.10/clikit/api/command/command.py:171 in _do_handle
>       169│         handler_method = self._config.handler_method
>       170│
>     → 171│         return getattr(handler, handler_method)(args, io, self)
>       172│
>       173│     def __repr__(self):  # type: () -> str
> 
>   3  .config/python/poetry/lib/poetry/_vendor/py3.10/cleo/commands/command.py:92 in wrap_handle
>        90│         self._command = command
>        91│
>     →  92│         return self.handle()
>        93│
>        94│     def handle(self):  # type: () -> Optional[int]
> 
>   2  .config/python/poetry/lib/poetry/console/commands/self/update.py:197 in handle
>       195│             return self.update_with_new_method(release.version)
>       196│
>     → 197│         self.update(release)
>       198│
>       199│     def update(self, release):
> 
>   1  .config/python/poetry/lib/poetry/console/commands/self/update.py:212 in update
>       210│
>       211│         try:
>     → 212│             self._update(version)
>       213│         except Exception:
>       214│             if not self.lib_backup.exists():
> 
>   RuntimeError
> 
>   Could not find poetry-1.2.0-darwin.sha256sum file
> 
>   at .config/python/poetry/lib/poetry/console/commands/self/update.py:260 in _update
>       256│         try:
>       257│             r = urlopen(base_url + "/{}/{}".format(version, checksum))
>       258│         except HTTPError as e:
>       259│             if e.code == 404:
>     → 260│                 raise RuntimeError("Could not find {} file".format(checksum))
>       261│
>       262│             raise
>       263│
>       264│         checksum = r.read().decode().strip()
<img width="752" alt="Screen Shot 2022-08-30 at 9 14 42 PM" src="https://user-images.githubusercontent.com/1966209/187592069-c8b717d6-b09e-4f02-9df2-b98a3b1c2033.png">

**Comment by neersighted** [comment]
This is expected as you installed using the `get-poetry.py` script. The [release announcement](https://python-poetry.org/blog/announcing-poetry-1.2.0) has the best directions for upgrading, but you can also find them in the [install directions](https://python-poetry.org/docs/1.2/#installation).

Please reinstall with the new script, and you'll be good to go!

**Comment by jdmartin** [comment]
Oh, ok!  Sorry about that and thanks for the quick response! :)
