### ISSUE TITLE
exporting packages to stdout adds 'creating virtualenv ...' in v 1.2.0

### ISSUE THREAD

**Issue by jegger** [python-poetry/poetry#6275]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Issue
Not sure if that should be considered a bug - maybe more an annoying change. However it broke our pipelines this morning as the new version 1.2.0 came out :)
I don't mind if you close this in case you think that it should be like that. Maybe it is helpful for others which use poetry in the same way we do.

We pipe the output of package export to pip for installation. 
E.g. `poetry export -f requirements.txt | poetry run pip install -r /dev/stdin`

In case there is not virtualenv created yet, poetry prints to stdout `Creating virtualenv foobar-pyXX in /foo/bar` which will result in pip trying to install a package called "Creating virtualenv...", which then ofc. fails.

### Workaround
As a workaround, we can simply export the dependencies to a file, and use pip to query the file instead of stdin.
`poetry export -f requirements.txt --output requirements.txt && poetry run pip install -r requirements.txt`

Thanks!

**Comment by neersighted** [comment]
Likely related to the plugin migration. Going to tag in @finswimmer as he was doing work on environment commands (and implicit environment creation) recently.

**Comment by dimbleby** [comment]
`-o requirements.txt` was always the contract: IMO this is indeed "annoying change" rather than "bug".

That `poetry export` creates a virtual environment is covered at https://github.com/python-poetry/poetry-plugin-export/issues/78.  You can run the command with `POETRY_VIRTUALENVS_CREATE=false` to avoid that, if you care to do so.

**Comment by dimbleby** [comment]
Also `--quiet`, probably

**Comment by alex** [comment]
FWIW `-o` doesn't seem to be compatible with using the results with pip's `-c`: https://github.com/pyca/cryptography/pull/7553 (the certbot-josepy job)

**Comment by alex** [comment]
This was working under the previous version of poetry with the ` > constraints.txt` operation. This thread suggests that the redirect was never supported, and `-o` should be used. Perhaps `constraints.txt` was never supported in either of them, but just happened to work?

**Comment by dimbleby** [comment]
I don't know how to be clearer so I guess I'll just repeat myself.  The output format is (and always was) `requirements.txt`, not `constraints.txt`.

**Comment by adferrand** [comment]
I am a little confused here. The poetry documentation about `export` states that if the `--output` flag is omitted, stdin will be used. So we should be able to pipe the result of `poetry export` to `pip` via the `-c` or `-r` flag no ?

To clarify about `pip -c`, an interesting usage of `poetry export` is to generate the dependency tree maintained by poetry into an understandable format for pip (the so-called "requirements.txt" format), then use the `-c` flag of pip to have reproducible `pip install` (typically in CI/CD pipelines).

**Comment by dimbleby** [comment]
`pip install -c` expects a different input format than `pip install -r`.  `poetry export` produces the latter format.  If it used to work with `pip install -c` then that was just lucky.

This is nothing to do with the stdout / `--output` thing (and this whole discussion doesn't belong in this issue at all)

**Comment by neersighted** [comment]
Closing this as duplicate -- the bug is tracked at https://github.com/python-poetry/poetry-plugin-export/issues/78 and things have gone off-topic.
