### ISSUE TITLE
Poetry export starts virtual environment

### ISSUE THREAD

**Issue by BenjiTrapp** [python-poetry/poetry#6280]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Amazon Machine Linux 2 
- **Poetry version**: 1.2.0

## Issue

For installing all dependencies in my AWS CodePipeline I currently use `poetry export` as a command. With the change to 1.2.0 poetry is new starting a virtual environment before exporting the dependencies. This causes some issues within my AWS CodePipeline. 

Is this behavior intended? Is there an option to disable the starting of the virtual environment?

**Comment by dimbleby** [comment]
the export plugin now lives in its own repository, and this duplicates https://github.com/python-poetry/poetry-plugin-export/issues/78 - please close

**Comment by neersighted** [comment]
Duplicate
