### ISSUE TITLE
Poetry configuration invalid

### ISSUE THREAD

**Issue by adam-mrozik** [python-poetry/poetry#6283]
Hi,

After 1 year of having no issues with CICD, today we started seeing this kind of error:

```
The Poetry configuration is invalid:
  - [scripts.requires] ['poetry>=0.12'] is not valid under any of the given schemas
```

This in of `pyproject.toml` is supposedly a culprit, but never was:
```
[tool.poetry.scripts]
requires = ["poetry>=0.12"]
```

Is there some new feature that might have introduced it?

**Comment by dimbleby** [comment]
poetry 1.2 was released today.

You'll want to pin your dependencies in CI pipelines so that they don't break when strangers on the internet change things.

**Comment by finswimmer** [comment]
Looks like that some validation hasn't work in Poetry 1.1.x and is now fixed. Correct syntax is shown here: https://python-poetry.org/docs/pyproject/#scripts
