### ISSUE TITLE
`poetry cache clear` no longer respects `--no-interaction` flag

### ISSUE THREAD

**Issue by graipher** [python-poetry/poetry#6291]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 22.04
- **Poetry version**: 1.2.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue

Since poetry version 1.2.0, the `poetry cache clear` command no longer respects the `--no-interaction` flag:

```
$ poetry cache clear --all --no-interaction .
Delete 1882 entries? (yes/no) [no] ^C
```

**Comment by dimbleby** [comment]
duplicate #6212, please close

**Comment by neersighted** [comment]
Not quite duplicate, but known and tracked by two different PRs at different points. I'll leave this open since we didn't have an issue tracking it (and the author may not come back to that PR).

**Comment by neersighted** [comment]
I was referring to python-poetry/cleo#234 -- or did I misunderstand, and was that fix not needed for this particular usage in Poetry?

**Comment by Secrus** [comment]
> I was referring to [python-poetry/cleo#234](https://github.com/python-poetry/cleo/pull/234) -- or did I misunderstand, and was that fix not needed for this particular usage in Poetry?

Kinda, but the explanation I linked also stands if I remember correctly. I will check it, but 90% sure python-poetry/cleo#234 is not enough

**Comment by branchvincent** [comment]
So https://github.com/python-poetry/cleo/pull/234 indeed fixes respecting `--no-interaction`, but the second part is changing the default response to `True` (otherwise, the cache won't actually be cleared): #6338
