### ISSUE TITLE
After upgrading to poetry 1.2, "poetry shell" fails

### ISSUE THREAD

**Issue by emacsuser123** [python-poetry/poetry#6292]
- [x ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**:  Ubuntu 22.04.1 LTS
- **Poetry version**:  1.2.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue

I've just upgraded some of my projects to poetry 1.2.0, and now my virtualenv is not activated automatically anymore when cd'ing into them.

I have been checking, and the problem is that **poetry shell** does not work. It returns an error saying the _pyproject.toml_ file does not exist, which is not true:

```
$ poetry shell
pyproject.toml file not found  
`````

thanks.

**Comment by emacsuser123** [comment]
> This is not poetry function, sounds like you've set up something interesting, maybe that's worth investigating.

Of course it is not, but that is not the point.

Just creating a brand new project with poetry new and having the zsh plugin deactivated, I get the same thing:

```
$ poetry new test
Created package test in test                                                                                                                                                             /
$ cd test                                                                                                                                                                                /0,9s
$ ll
total 20
drwxrwxr-x  4 roberto roberto 4096 ago 31 17:15 ./
drwxr--r-- 12 roberto roberto 4096 ago 31 17:15 ../
-rw-rw-r--  1 roberto roberto  279 ago 31 17:15 pyproject.toml
-rw-rw-r--  1 roberto roberto    0 ago 31 17:15 README.md
drwxrwxr-x  2 roberto roberto 4096 ago 31 17:15 test/
drwxrwxr-x  2 roberto roberto 4096 ago 31 17:15 tests/                                                                                                                                   
$ poetry --version
Poetry (version 1.2.0)                                                                                                                                                                   /
$ poetry shell
pyproject.toml file not found  
```

**Comment by dimbleby** [comment]
Again, this works fine for lots of folk, myself included, you'll have to investigate what's special about your environment
```
$ poetry new test
Created package test in test
$ cd test
$ poetry --version
Poetry (version 1.2.0)
$ poetry shell
Creating virtualenv test-ICLQk27m-py3.8 in /home/dch/.virtualenvs
Spawning shell within /home/dch/.virtualenvs/test-ICLQk27m-py3.8
. /home/dch/.virtualenvs/test-ICLQk27m-py3.8/bin/activate
dch@DESKTOP-NA4O3IV:~/test$ . /home/dch/.virtualenvs/test-ICLQk27m-py3.8/bin/activate
(test-py3.8) ~/test$
```

**Comment by TheErk** [comment]
@emacsuser123 didn't you tell poetry not to create venv?
In your case, when `poetry shell` is invoked you do not have
`Creating virtualenv test-ICLQk27m-py3.8 in /home/dch/.virtualenvs`

**Comment by set92** [comment]
Could this be related to the new configuration parameters? https://python-poetry.org/docs/configuration/#virtualenvsprefer-active-python-experimental. It would be weird, but maybe Poetry doesn't which is your active Python and it can't create the virtualenv...

**Comment by emacsuser123** [comment]
I finally managed to get this fixed .....
the problem was that `poetry debug` now in poetry 1.2 does not return the env info.

The new version needs a **subcommand** info to be provided¨
`$ poetry debug info `

Thanks a lot for your help.

**Comment by neersighted** [comment]
Could you please explain what the underlying error was, and how you solved it for those that come after you?

Were you parsing the output of `poetry debug`? A debug command is inherently unstable -- `poetry env info --path` has been supported for a long time and is stable, and `poetry env info` has not changed since it was introduced.
