### ISSUE TITLE
Release notes for 1.2.0 link to install.python.org

### ISSUE THREAD

**Issue by remram44** [python-poetry/poetry#6295]
- [ ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: 
- **Poetry version**: 1.2.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue

[The release notes for 1.2.0](https://github.com/python-poetry/poetry/releases/tag/1.2.0) have a link that says `[install.python-poetry.org](https://install.python.org/)`, e.g. the text is correct but the link is wrong.

**Comment by finswimmer** [comment]
Thanks a lot :+1: Fixed it.
