### ISSUE TITLE
Flatpak poetry package for Linux

### ISSUE THREAD

**Issue by caniko** [python-poetry/poetry#6305]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

Flatpak being pretty nice, should also have poetry. It would make everything about using `poetry` on Linux much easier.

**Comment by Secrus** [comment]
It was discussed in the past and the Poetry team does not plan on making any distro/OS-specific packages aside from Python wheel. Those packages require extra maintenance and Maintainers are stretched thin as it is.

**Comment by caniko** [comment]
I don't understand, can't there just be a build job? Flatpak is for Linux in its entirity.

**Comment by neersighted** [comment]
We've taken a stance of not officially supporting packages beyond the standard Python sdist/bdist due to limited time and bandwidth for debugging disparate platforms. It's not something we'll never offer, but we don't have anyone on the team to drive this (and it would take someone strongly owning it to ever make it viable).

**Comment by caniko** [comment]
For what its worth, I feel like doing Linux support over flatpak makes more sense of the current installation method. I understand that it shares installation with macOS, but I also see an avenue to just use homebrew for MacOS users (ask a MacOS user).

Thank you for your work, I understand how hard it can be to run a FOSS project.

**Comment by neersighted** [comment]
The thing is, we don't distribute a Linux installer or Linux packages -- we distribute a Python package and rely on the ecosystem of tooling for installing said packages on any platform.

Poetry will always provide Python packages first and foremost as we are a Python project and need to be consumed by the Python ecosystem (as well as our own plugin ecosystem) -- anything on top of that is a bonus, but is too coupled to specific platforms for the level of bandwidth we have now.

Thanks for your input -- if we ever do offer Linux packages, it will likely be snap/flatpak and not distro packages (as those are very difficult to make robust without being part of the distro itself).

**Comment by caniko** [comment]
I understand, best wishes!
