### ISSUE TITLE
poetry 1.2.0 breaks CI for pandas-stubs on Windows

### ISSUE THREAD

**Issue by Dr-Irv** [python-poetry/poetry#6306]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.  (version 1.2.0)
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [N/A] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows Server 2002
- **Poetry version**: 1.2.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://github.com/pandas-dev/pandas-stubs/pull/241/files

## Issue

We had a pretty simple CI running on Github for the pandas-stubs project.  It started to fail on Windows, because it started pulling in version 1.2.0 of poetry.

When I pinned the poetry version to 1.1.5, our CI worked fine.   The linked pull request shows that change, and you can visit https://github.com/pandas-dev/pandas-stubs/actions to see what we are seeing in the logs of failed runs, which were failing because a package couldn't be found that poetry said it installed.

**Comment by neersighted** [comment]
Hi, this needs a minimal reproduction to be addressable -- it is highly unlikely that anyone will find the time or interest to debug the CI pipeline of a different project. Could you please create a minimal reproduction (preferably, but not required to be in a Windows container)?

**Comment by dimbleby** [comment]
besides which, the failures that you are attributing to poetry 1.2 are happening with your CI using poetry 1.1.15 eg https://github.com/pandas-dev/pandas-stubs/runs/8105323908?check_suite_focus=true

So you'll want to dig a bit deeper yourself I reckon

**Comment by Dr-Irv** [comment]
> Hi, this needs a minimal reproduction to be addressable -- it is highly unlikely that anyone will find the time or interest to debug the CI pipeline of a different project. Could you please create a minimal reproduction (preferably, but not required to be in a Windows container)?

That will take a bit of work on our part to isolate.  It could be only in CI, or maybe regular Windows, or due to combinations of versions of software.   I'll see what we can do.  What I do know is that pinning poetry back to 1.1.5 makes our CI work.

**Comment by Dr-Irv** [comment]
> besides which, the failures that you are attributing to poetry 1.2 are happening with your CI using poetry 1.1.15 eg https://github.com/pandas-dev/pandas-stubs/runs/8105323908?check_suite_focus=true
> 
> So you'll want to dig a bit deeper yourself I reckon

No, that run was failing for other reasons.

If you look at the successful run here:  https://github.com/pandas-dev/pandas-stubs/actions/runs/2958394397
versus the unsuccessful run here:  https://github.com/pandas-dev/pandas-stubs/actions/runs/2962734028

on the same PR, the difference in the logs revealed poetry 1.1.5 worked and poetry 1.2.0 did not.

**Comment by dimbleby** [comment]
well one of us is having a reading comprehension problem, maybe it's me.

How is the run that I pointed at different?  Looks exactly like the windows-only loguru stuff in the other one to me.

(You keep typing 1.1.5 - can you really mean that or is 1.1.15 intended?)

**Comment by Dr-Irv** [comment]
> well one of us is having a reading comprehension problem, maybe it's me.
> 
> How is the run that I pointed at different? Looks exactly like the windows-only loguru stuff in the other one to me.

Fair enough.  I was concentrating on the PRs that were working and started failing after the upgrade to poetry.  Can't say what happened on that particular one that you found.
> 
> (You keep typing 1.1.5 - can you really mean that or is 1.1.15 intended?)

Ugh, I keep making the same typo!!!  I meant 1.1.15.

**Comment by dimbleby** [comment]
So I also don't know what happened here but if we agree that the attribution to poetry 1.2.0 is faulty then probably this issue should be closed.

(I guess you hit something transient or cache-y or something on github, and coincidentally it fixed itself when you changed poetry version.  But as neersighted suggests, I don't really care to investigate...)

**Comment by Dr-Irv** [comment]
> So I also don't know what happened here but if we agree that the attribution to poetry 1.2.0 is faulty then probably this issue should be closed.

I'm not sure that I agree that the attribution to poetry is faulty.....

**Comment by dimbleby** [comment]
well you agree that the same thing happened at poetry 1.1.15, which makes it pretty darned suspect

**Comment by Dr-Irv** [comment]
And I just replicated it with poetry 1.1.15, so I guess that wasn't it.  I think it has to do with how we are caching poetry.lock

Thanks for finding that it wasn't working with 1.1.15
