### ISSUE TITLE
poetry lock adds duplicate hashes when using multiple constraint dependences

### ISSUE THREAD

**Issue by intgr** [python-poetry/poetry#6327]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS
- **Poetry version**: 1.2.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/intgr/efc96c44c3919189c3757275f0239eb6

## Issue

With a dependency specification like
```toml
python-ldap = [
  { platform = "linux", version = "3.4.0" },
  { platform = "win32", url = "https://download.lfd.uci.edu/pythonlibs/archived/python_ldap-3.4.0-cp310-cp310-win_amd64.whl" },
]
```

Every time I run `poetry lock --no-update`, Poetry adds duplicated hashes for `python-ldap` to the `poetry.lock` file.

After the first lock command, the content ends with:
```toml
python-ldap = [
    {file = "python-ldap-3.4.0.tar.gz", hash = "sha256:60464c8fc25e71e0fd40449a24eae482dcd0fb7fcf823e7de627a6525b3e0d12"},
]
```
After the second run, it's:
```toml
python-ldap = [
    {file = "python-ldap-3.4.0.tar.gz", hash = "sha256:60464c8fc25e71e0fd40449a24eae482dcd0fb7fcf823e7de627a6525b3e0d12"},
    {file = "python-ldap-3.4.0.tar.gz", hash = "sha256:60464c8fc25e71e0fd40449a24eae482dcd0fb7fcf823e7de627a6525b3e0d12"},
]
```
Etc, every run adds yet another entry there.

The contents of the lockfile should be deterministic.

**Comment by radoering** [comment]
All locked filenames/hashes are duplicated once for each direct origin dependency among the multiple constraints dependencies. This issue doesn't occur in poetry 1.1 because direct origin dependencies are always updated (even with `--no-update` flag). I created a PR to fix this regression.

**Comment by intgr** [comment]
Thanks! I can confirm that this is fixed in Poetry master branch.
