### ISSUE TITLE
Option to disable SSL verification

### ISSUE THREAD

**Issue by simonvdk** [python-poetry/poetry#6331]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

This is mainly a revival of https://github.com/python-poetry/poetry/issues/1556, following 1.2.0 release.

**Why reopen this feature request**:
- when using poetry in a corporate environment, it can make sense to trust the host and deactivate SSL verification; above old issue received quite a few upvotes
- to do so, the popular workaround was setting `CURL_CA_BUNDLE=""` so that `requests` does not verify SSL
- `poetry` 1.2.0 is based on a recent version of `requests`, which removed this workaround recently and refuse to have a way to set this using environment variables (even a very specific one). Their (valid) argument is that it should be the responsibility of tools/applications using requests (e.g. poetry) to expose a way to deactivate it, then internally using the `verify` `requests` argument (https://github.com/psf/requests/issues/6071#issuecomment-1059528942)
- this feature is preventing people to switch from `pipenv` (or other dependency management tools that have that option) to the awesome `poetry`

Being able to set this from the CLI and `pyproject.toml` would help people transition to `poetry`

**Comment by dimbleby** [comment]
https://python-poetry.org/docs/repositories/#certificates

> The value of certificates.<repository>.cert can be set to false if certificate verification is required to be skipped. 

?

**Comment by simonvdk** [comment]
Thanks a lot, missed that from the documentation !

**Comment by radiophysicist** [comment]
Hello,

I have not effect with this setting -- poetry (version 1.4.1) still throws a certificate validation error:
```
SSLError(SSLError(1, '[SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:997)')))
```
