### ISSUE TITLE
'poetry version' does not seem to change the current package version

### ISSUE THREAD

**Issue by gsemet** [python-poetry/poetry#6333]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

## Issue

if seems like "poetry version" does not set the version of the package in the build environment, like "poetry install" does. 

Give this code to retrieve the version using 'importlib.metadata':
```
from importlib_metadata import version as importlib_version
__version__ = importlib_version("my-pkg-name")
```

during the development, `importlib_version("my-pkg-name")` always returns the value that where in the `pyproject.toml` at the moment of the `poetry install`. Any call to `poetry version` will change `pyproject.toml`, but `importlib_version("my-pkg-name")` will not reflect this new value.

Thanks

**Comment by finswimmer** [comment]
Hello @gsemet,

this is an expected behavior. `poetry version` just bumps the version in the pyproject.toml. Another round of `poetry install`  is needed to update the metadata in the environment.

fin swimmer

**Comment by gsemet** [comment]
Ok I understand. Would it be possible to add this information in the "poetry version" documentation page?
