### ISSUE TITLE
SSL certificate verify failed during poetry install on 1.2.0

### ISSUE THREAD

**Issue by Kuba314** [python-poetry/poetry#6340]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Fedora 35
- **Poetry version**: 1.2.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/Kuba314/5936b2642de9bf3d349a9580a711d891

## Issue
Git repository hidden behind a company VPN needing company SSL certificates apparently can't be verified. This worked on 1.1.15 just fine. I can clone the repository manually.

`poetry install -vvv` is failing. See the [log](https://gist.github.com/Kuba314/0858841d064a84e1697076d02a55bdd1) (keep in mind that I replaced the url and repository path).

**Comment by dimbleby** [comment]
https://python-poetry.org/docs/repositories/#certificates

**Comment by Kuba314** [comment]
> https://python-poetry.org/docs/repositories/#certificates

This doesn't work for me. Setting the certificate doesn't solve the issue, nor does setting it to false.

**Comment by Kuba314** [comment]
Looks like an issue with dulwich not using system certificates. Not sure though.

This is a reproducer:
```py
from dulwich import porcelain

porcelain.clone("https://company.gitlab.instance.com/namespace/project.git", "test-repo")
```

**Comment by dimbleby** [comment]
sounds like you should raise this at the dulwich repository then

**Comment by dimbleby** [comment]
fixed at https://github.com/jelmer/dulwich/pull/1029
