### ISSUE TITLE
`poetry export > requirements.txt` without a virtualenv produces an invalid requirements file

### ISSUE THREAD

**Issue by andreareina** [python-poetry/poetry#6347]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Linux, various versions
- **Poetry version**: >= 1.2.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/andreareina/03b937a2789e82b68d45d53467224f7e

## Issue

Starting with v1.2.0 `poetry export` creates a virtualenv if one is not already present. This causes a message ("Creating virtualenv ...") to be printed to stdout and so results in an invalid requirements file. We run `poetry export > requirements.txt` as part of a CI/CD build so there isn't an existing virtualenv.

```
/tmp/poetry-repro $ docker build -t poetry-repro .
Sending build context to Docker daemon  16.77MB
Step 1/3 : FROM public.ecr.aws/lambda/python:3.8
 ---> 247b5632d3d3
Step 2/3 : COPY pyproject.toml .
 ---> Using cache
 ---> 2a74b8c9b9a7
Step 3/3 : COPY poetry.lock .
 ---> Using cache
 ---> d92fc10d399b
Successfully built d92fc10d399b
Successfully tagged poetry-repro:latest

/tmp/poetry-repro $ docker run --rm -aSTDOUT --entrypoint /bin/bash poetry-repro -c "pip3 install 'poetry<1.2.0' > /dev/null && poetry --version && poetry export | head"
Poetry version 1.1.15
bottle==0.12.23

/tmp/poetry-repro $ docker run --rm -aSTDOUT --entrypoint /bin/bash poetry-repro -c "pip3 install 'poetry==1.2.0' > /dev/null && poetry --version && poetry export | head"
Poetry (version 1.2.0)
Creating virtualenv poetry-repro-AsW4q1BB-py3.8 in /root/.cache/pypoetry/virtualenvs
bottle==0.12.23 ; python_version >= "3.8" and python_version < "4.0"
```

**Comment by kigawas** [comment]
Same here. `Creating virtualenv ...` breaks lots of build

**Comment by finswimmer** [comment]
Hey,

the export command is now a plugin and is developed in it's own repository: https://github.com/python-poetry/poetry-plugin-export

There this was already reported in https://github.com/python-poetry/poetry-plugin-export/issues/78

fin swimmer

**Comment by andreareina** [comment]
Thanks, I saw somewhere that it had gotten split out to a plugin, didn't realize that meant a new repo. 

Future searchers: replace `> requirements.txt` with `--output requirements.txt`
