### ISSUE TITLE
Incorrect wheel dependencies when optional packages are combined with platform markers

### ISSUE THREAD

**Issue by anaoum** [python-poetry/poetry#6350]
- **OS version and name**: Ubuntu 20.04.2 LTS
- **Poetry version**: 1.2.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/anaoum/1dc485b52bc33bff4e729ee9a3959d50

## Issue
The above pyproject.toml has two versions of torch as a dependency, one for platform==linux, and one for platform==darwin. Both are marked as optional=true, and appear in the "mle" and "all" extras groups. When I generate the wheel package, the following METADATA is produced:

```
Metadata-Version: 2.1
Name: platras
Version: 0.1.0
Summary: 
Author: anaoum
Requires-Python: >=3.8,<3.9
Classifier: Programming Language :: Python :: 3
Classifier: Programming Language :: Python :: 3.8
Provides-Extra: all
Provides-Extra: mle
Requires-Dist: loguru (>=0.6.0,<0.7.0)
Requires-Dist: torch @ https://download.pytorch.org/whl/cpu/torch-1.12.1-cp38-none-macosx_10_9_x86_64.whl ; sys_platform == "darwin"
Requires-Dist: torch @ https://download.pytorch.org/whl/cu113/torch-1.12.1%2Bcu113-cp38-cp38-linux_x86_64.whl ; (sys_platform == "linux") and (extra == "mle" or extra == "all")
```

Note that the _darwin_ version of the torch dependency does not also condition on `(extra == "mle" or extra == "all")`

This can be easily reproduced using the linked pyproject.toml above and running `poetry build`.

This issue causes problems in downstream projects that attempt to install the package with extras, as poetry will see two incompatible versions of the same dependency and fail.

**Comment by dimbleby** [comment]
I think the fix should be as straightforward as removing [this line](https://github.com/python-poetry/poetry-core/blob/0ea6fd285db997f2dfa2dfbb7b32bdbef1d0d549/src/poetry/core/factory.py#L189) if you - or anyone else - care to put together an MR.

Writing a testcase will be harder than making the fix

**Comment by anaoum** [comment]
Thanks for the direction @dimbleby. I have confirmed that this resolves the issue, and implemented the fix/unit test in https://github.com/python-poetry/poetry-core/pull/462
