### ISSUE TITLE
Backport stable Cleo to Poetry 1.2 when available

### ISSUE THREAD

**Issue by dvzrv** [python-poetry/poetry#6353]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Arch Linux
- **Poetry version**: 1.2.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: n/a

## Issue

When packaging poetry for a downstream Linux distribution (in this case Arch Linux) it became clear, that [the release of 1.2.0 relies on an alpha prerelease version of cleo](https://github.com/python-poetry/poetry/blob/f667d48bcc320c3a5d1f7b929266b4d5cdf54227/pyproject.toml#L51). A stable version of poetry relies on an unstable version of a component.

This is problematic, as downstreams usually have a policy of not shipping pre-release versions. This means, that shipping poetry in 1.2.0 breaks, because cleo is not available in a version that poetry requires, or that poetry 1.2.0 can not be shipped until cleo 1.0.0 is released.

Please make sure to use only stable components when releasing a stable version of poetry, as anything else is problematic for downstreams.

**Comment by neersighted** [comment]
Hi @dvzrv -- we try to support downstream packaging on a best-effort basis. In this case, Cleo was not ready for a final release in time for Poetry's release. As soon as Cleo has a stable release available, we do plan to make a patch release of Poetry 1.2 depending on it.

In general unreleased fixes are not something we want to depend on either -- however we have only recently started work to get Cleo development moving again and to fix longstanding bugs, which creates this awkward situation. 

I'm going to leave this open to track the bump of Cleo once it hits stable status.
