### ISSUE TITLE
Keyring not working correctly on Ubuntu

### ISSUE THREAD

**Issue by eduDorus** [python-poetry/poetry#6354]
- **OS version and name**: Ubuntu 20.04 LTS
- **Poetry version**: 1.2.0
- **Python version**: 3.10.6

## Issue
Ubuntu 20.04 LTS seems to have a problem with the cleo poetry uses. The keyring is not willing to authenticate unless I set the keyring backend to null.
```
Project environment contains an empty path in sys_path, ignoring.
[keyring.backend] Loading KWallet
[keyring.backend] Loading SecretService
[keyring.backend] Loading Windows
[keyring.backend] Loading chainer
[keyring.backend] Loading libsecret
[keyring.backend] Loading macOS

  Stack trace:

  29  ~/.local/share/pypoetry/venv/lib/python3.10/site-packages/cleo/application.py:329 in run
       327│
       328│             try:
     → 329│                 exit_code = self._run(io)
       330│             except Exception as e:
       331│                 if not self._catch_exceptions:
```
```
  KeyringLocked

  Failed to unlock the collection!

  at ~/.local/share/pypoetry/venv/lib/python3.10/site-packages/keyring/backends/SecretService.py:67 in get_preferred_collection
       63│             raise InitError("Failed to create the collection: %s." % e)
       64│         if collection.is_locked():
       65│             collection.unlock()
       66│             if collection.is_locked():  # User dismissed the prompt
    →  67│                 raise KeyringLocked("Failed to unlock the collection!")
       68│         return collection
       69│
       70│     def unlock(self, item):
       71│         if hasattr(item, 'unlock'):
```
## Solution
```
export PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring
```

**Comment by neersighted** [comment]
Duplicate #1917 (also, not related to Cleo, but to Keyring)

**Comment by vahvero** [comment]
> `export PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring`

This resolved our install error today which froze to

```
[keyring.backend] Loading KWallet
[keyring.backend] Loading SecretService
[keyring.backend] Loading Windows
[keyring.backend] Loading chainer
[keyring.backend] Loading libsecret
[keyring.backend] Loading macOS
# nothing happens after this, execution is in frozen state
```
text when installing with maximum verbosity. I could not deduce whether this is an issue with poetry or some derivative libraries.

`Poetry (version 1.2.1)`

**Comment by pranavm1502** [comment]
> > `export PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring`
> 
> This resolved our install error today which froze to
> 
> ```
> [keyring.backend] Loading KWallet
> [keyring.backend] Loading SecretService
> [keyring.backend] Loading Windows
> [keyring.backend] Loading chainer
> [keyring.backend] Loading libsecret
> [keyring.backend] Loading macOS
> # nothing happens after this, execution is in frozen state
> ```
> 
> text when installing with maximum verbosity. I could not deduce whether this is an issue with poetry or some derivative libraries.
> 
> `Poetry (version 1.2.1)`

This also holds true for Peotry (version 1.4.2) and Ubuntu 20.04 LTS
