### ISSUE TITLE
Installing torch with a specific wheel causes the wheel to be downloaded twice

### ISSUE THREAD

**Issue by then4p** [python-poetry/poetry#6355]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: kubuntu 22.04.1
- **Poetry version**: 1.2.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/then4p/1329aa984e003d98c714151c8ed4fc72#file-pyproject-toml

## Issue
For latest CUDA support I need to use a specific torch version, which is available here: https://download.pytorch.org/whl/cu116/torch-1.12.1%2Bcu116-cp39-cp39-linux_x86_64.whl

I can install it just fine, by specifying: `torch = {url = "https://download.pytorch.org/whl/cu116/torch-1.12.1%2Bcu116-cp39-cp39-linux_x86_64.whl"}`in my pyproject.toml. After doing so though, every poetry add or poetry install takes ages and seems to download the 2GB file again. Would it be possible to only download it once and then cache it?

**Comment by dimbleby** [comment]
duplicate #2415

**Comment by then4p** [comment]
> duplicate #2415

Yep, looks like I've overlooked that. Seems to be the same issue.
