### ISSUE TITLE
Lowercase `-g` for `--group`?

### ISSUE THREAD

**Issue by nyuszika7h** [python-poetry/poetry#6358]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

Is there any reason uppercase `-G` was chosen for `--group` rather than lowercase `-g`? The latter appears unused and would be easier to type.

**Comment by neersighted** [comment]
My understanding from the time/PR that this was introduced in (https://github.com/python-poetry/poetry/pull/4260), was that it was done to avoid confusion with `npm install -g` (`npm add` is a deprecated alias for `npm install`), as installing to the system site-packages is (or hopefully was) rather popular (see `poetry config virtualenvs.create false`).

@sdispater can correct me if I recall incorrectly of course.

Regardless of how we feel about the reasons behind the capitalization, the decision was made and to try and change it now would require a rather costly (if low risk) migration/transition -- are there any compelling reasons to do so (beyond the obvious aesthetic and keystroke-saving concerns)?

**Comment by neersighted** [comment]
I suspect not, unless something really compelling pops up. Thanks for the suggestion!
