### ISSUE TITLE
Removal of get-poetry.py

### ISSUE THREAD

**Issue by neersighted** [python-poetry/poetry#6377]
This issue tracks the removal of `get-poetry.py` from this repository. After discussion triggered by the release of 1.2.0, and an attempt to bring awareness to the deprecation of this script, it has been decided that we will remove `get-poetry.py` from this repo on or after **January 1, 2023**.

A PR that changes `get-poetry.py` to have the following flow will be merged:

- When run without an explicit version, 1.2.x will be selected (as it is the latest) and the installer will fail as it cannot install 1.2.0a1 or newer.
- Any explicit version can be selected, and the installer will succeed for versions it understands.
- If `GET_POETRY_IGNORE_DEPRECATION=1` in set the environment, the latest installable version will be used even when no explicit version is selected.
- In all cases a deprecation message will be printed, and warnings will be issued when uninstallable versions of Poetry are skipped.
- A target removal date of January 1, 2023 will be printed, with a link to this issue, and a blog post linking here as well.

The `get-poetry.py` script is considered frozen, and will not receive fixes if it is broken by external factors.

For previous discussion of this process, see #6314.

**Comment by neersighted** [comment]
For those following along at home, the PR is merged and the above behaviors are accurate for `get-poetry.py`. No more changes are planned for this script before removal.

**Comment by BurekPrime** [comment]
@neersighted
I would like to ask you if changing:
`curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -`
to:
`curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/901bdf0491005f1b3db41947d0d938da6838ecb9/get-poetry.py | python -`
will still work after 01.01.2023?

To give some context I develop a platform that is scheduled to be closed, somewhere in February 2023 and all of our Python component build pipelines depend on the old install script still working (they broke, but after your fix they are working again, so thank you for that). I'm only interested in the poetry installation working up util then (in case of some hot fix release) and don't want to introduce to much changes. Can I count that the master branch won't be rebased or something and that the script from the commit will be still working? You mentioned that script can break due to "external factors", could you please elaborate.
Sorry if I picked up a wrong channel for such question, but I'm not aware of a more appropriate place.
Thanks for the answer in advance.

**Comment by neersighted** [comment]
The commit will remain in history -- Poetry as a project has a linear history and we do not rebase or drop commits from the stable/protected branches. In short: you will be able to keep using the script from that URL indefinitely.

When I refer to external factors, I mean any changes in common external components (Python, pip, your operating system or distro's packaging thereof, etc.) -- we don't plan to make any changes even if something somebody else changes causes the script to not function.

**Comment by BurekPrime** [comment]
@neersighted Thank you for such a great and quick answer.

**Comment by caniko** [comment]
@remram44, where is the [virtue signaling](https://github.com/python-poetry/poetry/pull/6297#issuecomment-1268497002)?

**Comment by caniko** [comment]
Excuse me @remram44, you mentioned me first... I wasn't directing any part of my initial comment at you. 

Also, I don't think I said escalation was your intention, it is your language that is escalating—food for thought.

**Comment by neersighted** [comment]
I am hesitant to lock this thread as I do believe that discussing how we handled this, and how to move forward can be valuable. However, it is clear that tempers are still running high, and the Youtube video/Twitter comments are likely the reason for it (they seemed to coincide with emails, and comments here). I will be locking this thread for now for the next week or so -- I hope that by then, better tempers will have prevailed, and we can have a productive dialogue.

**Comment by Crosse** [comment]
Hi!

I think the docs need to be updated to reflect that this script has been removed, and perhaps give alternate instructions for uninstallation:

https://github.com/python-poetry/poetry/blob/7c86992909257caa4f51a50c001f5894bfe5065e/docs/_index.md?plain=1#L184-L190

I just happened to try to update a (clearly) seldom-used install of Poetry this morning and ran across this. I solved my issue by downloading the script at commit 901bdf04, as mentioned in a comment above, so this is more an FYI than anything else.

**Comment by sebastianfelipe** [comment]
Hey folks! Is this `GET_POETRY_IGNORE_DEPRECATION=1` env used after the change in the installation process? Thanks!

**Comment by ak-empiak** [comment]
> Hi!
> 
> I think the docs need to be updated to reflect that this script has been removed, and perhaps give alternate instructions for uninstallation:
> 
> https://github.com/python-poetry/poetry/blob/7c86992909257caa4f51a50c001f5894bfe5065e/docs/_index.md?plain=1#L184-L190
> 
> I just happened to try to update a (clearly) seldom-used install of Poetry this morning and ran across this. I solved my issue by downloading the script at commit [901bdf0](https://github.com/python-poetry/poetry/commit/901bdf0491005f1b3db41947d0d938da6838ecb9), as mentioned in a comment above, so this is more an FYI than anything else.

If someone needs the command : curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/901bdf0491005f1b3db41947d0d938da6838ecb9/get-poetry.py | python3 - --uninstall
