### ISSUE TITLE
Name of a file and directory conflicts

### ISSUE THREAD

**Issue by volucris1** [python-poetry/poetry#6382]
- [ x ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [ x ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ x ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Linux laptop 5.19.6-arch1-1
- **Poetry version**: Poetry (version 1.2.0)

If i already have file with name same as my new project:
```bash
~/Projects
❯ touch project_name

~/Projects
❯ poetry new project_name

[Errno 17] File exists: '/home/yura/Projects/project_name'
```
I think file and directory may have same name.

**Comment by finswimmer** [comment]
Hello @volucris1,

you cannot have a file and a directory with the same name at the same place. This is not a Poetry issue, this is how file systems work.

fin swimmer
