### ISSUE TITLE
incorrect ~/.bash_completion 

### ISSUE THREAD

**Issue by xkxixnxgx** [python-poetry/poetry#6384]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: 5.18.0-kali5-amd64 (debian)
- **Poetry version**: Poetry (version 1.2.0)
- **Link with the contents of your pyproject.toml file**: [](https://gist.github.com/xkxixnxgx/2281f22e6ea94a620e72c874cb65ff4f)

## Issue
After installing Poetry, I executed the command according to the documentation to add tab completion .
https://python-poetry.org/docs/#auto-loaded-recommended
```
poetry completions bash >> ~/.bash_completion
```
When opening a new bash shell, an error message appears in `~/.bash_completion`
```
bash: /home/user/.bash_completion: line 40: syntax error next to unexpected "clear" marker
bash: /home/user/.bash_completion: line 40: `            (cache clear)'
```
And so on all lines where the value in the lines consists of two words.
```
->        (debug info)
            opts="${opts} "
            ;;

->        (debug resolve)
            opts="${opts} --extras --install --python --tree"
            ;;
```

I wrapped such variables in quotes and the problem went away. 
```
            ("debug info")
            opts="${opts} "
            ;;

            ("debug resolve")
            opts="${opts} --extras --install --python --tree"
            ;;
```

Tab completion works, but only for the first word.

**Comment by dimbleby** [comment]
this comes from cleo so wants raising and fixing over there.

https://github.com/python-poetry/cleo/blob/efb274f445a939ee805f93ec7b8cd73cba5337e8/src/cleo/commands/completions_command.py#L165 I reckon, if you care to put together an MR

**Comment by dimbleby** [comment]
ah, duplicate #4572 (and per that issue, tracked upstream at https://github.com/python-poetry/cleo/issues/133)
