### ISSUE TITLE
Poetry: No such file or directory

### ISSUE THREAD

**Issue by MaxDragonheart** [python-poetry/poetry#6385]
- **OS version and name**: Ubuntu 22.04
- **Poetry version**: 1.2.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: [pyproject.toml](https://github.com/MaxDragonheart/OpenGeoData/blob/main/website/pyproject.toml)

## Issue
Yesterday I've formatted the laptop and I've installaed Ubuntu 22.04; previously I was on Ubuntu 20.04, probably with poetry 1.1.0(I don't rember).
Using directly `curl -sSL https://install.python-poetry.org | python3 -` I've the same problem of #6371.
So, I've installed Python's stuff: `sudo apt install python3-pip python3-venv`.
After this step I've cleaned the [cache](https://github.com/python-poetry/poetry/issues/4542#issuecomment-1181515560): `rm -rf ~/Library/Caches/pypoetry`.
Then I've tried to install poetry again: `curl -sSL https://install.python-poetry.org | python3 -`

```
Retrieving Poetry metadata

# Welcome to Poetry!

This will download and install the latest version of Poetry,
a dependency and package manager for Python.

It will add the `poetry` command to Poetry's bin directory, located at:

/home/max/.local/bin

You can uninstall at any time by executing this script with the --uninstall option,
and these changes will be reverted.

Installing Poetry (1.2.0): Done

Poetry (1.2.0) is installed now. Great!

To get started you need Poetry's bin directory (/home/max/.local/bin) in your `PATH`
environment variable.

Add `export PATH="/home/max/.local/bin:$PATH"` to your shell configuration file.

Alternatively, you can call Poetry explicitly with `/home/max/.local/bin/poetry`.

You can test that everything is set up by executing:

`poetry --version`
```

When I try to check the version using `poetry --version` I see this message:
```
-bash: /usr/bin/poetry: No such file or directory
```

Searching into my folders I see that poetry is here: `/home/max/.local/share/pypoetry/venv/bin/poetry`

How I can solve?

**Comment by MaxDragonheart** [comment]
It is a my misunderstanding. I've forgot to use `export PATH="/home/max/.local/bin:$PATH"`.

**Comment by SRIKANTH-KUMAR** [comment]
I had a similar issue which got fixed with the following: 

- source /home/kumar/.cache/pypoetry/virtualenvs/geoips-OIax34WL-py3.9/bin/activate
-  /home/kumar/.local/bin/poetry env use /home/kumar/.cache/pypoetry/virtualenvs/geoips-OIax34WL-py3.9/bin/python
