### ISSUE TITLE
install inside github actions fails with `poetry==1.2.0`

### ISSUE THREAD

**Issue by fruch** [python-poetry/poetry#6397]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Docker build inside github actions
- **Poetry version**: 1.2.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/fruch/e29e311e8edfe390acdd55f09f6102ea

## Issue

running `poetry install` inside docker build when running on github action started failing once 1.2.0 was released: (4 days ago)

Dockerfile:
```Dockerfile
FROM python:3.10.6-bullseye
...
RUN poetry config virtualenvs.create false && poetry install --only main --no-root

```

the command returned with status code 1, without anymore information
adding 

full log of the github action with `-vvv`:
https://gist.github.com/fruch/f4d542dba9533eb3a31b9824e7cfb102

locally on people's laptops this command was working just fine (including inside the `docker build`)

adding the following command, elevated the issue:
```
poetry config installer.max-workers 2
```

seems that the default `number_of_cpus + 4` is problematic inside github action that has 2 cores only.

But couldn't figure exactly why...

**Comment by dimbleby** [comment]
you seem to be installing poetry system 1.2.0 system-wide, and then also system-wide installing a package that has an explicit dependency on poetry 1.1.13.

Probably it's obvious that this is a bad idea, I'm surprised it works ever.

**Comment by neersighted** [comment]
Both Poetry and your project need to be installed in to their own virtual environments -- please take a look at the following pattern in Docker for a minimal way to install Poetry and a package:

```dockerfile
FROM python:3.10

ENV POETRY_HOME=/opt/poetry
RUN python3 -m venv $POETRY_HOME && \
    $POETRY_HOME/bin/pip install poetry==1.2.0

RUN git clone https://github.com/python-poetry/poetry /poetry

WORKDIR /poetry

ENV VIRTUAL_ENV=/poetry-env \
    PATH="/poetry-env/bin:$POETRY_HOME/bin:$PATH"

RUN python3 -m venv $VIRTUAL_ENV && \
    poetry install
    
CMD "pytest"
```
