### ISSUE TITLE
Back compatibility is completely broken since 1.2, curious about poetry versioning

### ISSUE THREAD

**Issue by kevr** [python-poetry/poetry#6403]
## Problem

Minor version was bumped to 2, but this minor release breaks back compatibility. Semver says that back compatibility breakage should come in the form of major bumps. What's up, doc?

## Reproduction

1. Install `poetry 1.2`
2. Add a development dependency to a project
    1. `$ poetry add --group dev some-dependency`
3. Bring the updated poetry.lock/pyproject.toml over to a system with `poetry 1.1.15`
4. Install dependencies
    1. `$ poetry install`
5. Receive errors about the dev group format from 1.2 being unsupported

**Comment by neersighted** [comment]
If you want your project to work on 1.1, don't use 1.2-only features. Please see the [relevant section](https://python-poetry.org/blog/announcing-poetry-1.2.0/#dependency-groups) on the release announcement. This was not a breaking change as you can simply opt out of it -- and Poetry does not strictly follow semver, though we try to use it as a guideline (semver is often too strict 'in the real world' -- and if we just keep incrementing the major version nearly every release, there would be no practical difference as the same number of versions would be maintained).

**Comment by finswimmer** [comment]
Hey @kevr,

the break you are talking about is not a backward incompatible change. "Being backward compatible" means, that you can use older input formats to the new release and it must work - and not the other way round.

fin swimmer
