### ISSUE TITLE
Poetry 1.1.14 can't `self update` to Poetry 1.2.0, hash sum file is missing

### ISSUE THREAD

**Issue by zyv** [python-poetry/poetry#6410]
- [ ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 20.04.5 LTS
- **Poetry version**: 1.1.14

## Issue

```
zaytsev@parallels:~$ poetry --version
Poetry version 1.1.14
zaytsev@parallels:~$ poetry self update -vvv
Updating to 1.2.0

  Stack trace:

  6  .poetry/lib/poetry/_vendor/py3.8/clikit/console_application.py:131 in run
      129│             parsed_args = resolved_command.args
      130│ 
    → 131│             status_code = command.handle(parsed_args, io)
      132│         except KeyboardInterrupt:
      133│             status_code = 1

  5  .poetry/lib/poetry/_vendor/py3.8/clikit/api/command/command.py:120 in handle
      118│     def handle(self, args, io):  # type: (Args, IO) -> int
      119│         try:
    → 120│             status_code = self._do_handle(args, io)
      121│         except KeyboardInterrupt:
      122│             if io.is_debug():

  4  .poetry/lib/poetry/_vendor/py3.8/clikit/api/command/command.py:171 in _do_handle
      169│         handler_method = self._config.handler_method
      170│ 
    → 171│         return getattr(handler, handler_method)(args, io, self)
      172│ 
      173│     def __repr__(self):  # type: () -> str

  3  .poetry/lib/poetry/_vendor/py3.8/cleo/commands/command.py:92 in wrap_handle
       90│         self._command = command
       91│ 
    →  92│         return self.handle()
       93│ 
       94│     def handle(self):  # type: () -> Optional[int]

  2  .poetry/lib/poetry/console/commands/self/update.py:197 in handle
      195│             return self.update_with_new_method(release.version)
      196│ 
    → 197│         self.update(release)
      198│ 
      199│     def update(self, release):

  1  .poetry/lib/poetry/console/commands/self/update.py:212 in update
      210│ 
      211│         try:
    → 212│             self._update(version)
      213│         except Exception:
      214│             if not self.lib_backup.exists():

  RuntimeError

  Could not find poetry-1.2.0-linux.sha256sum file

  at .poetry/lib/poetry/console/commands/self/update.py:260 in _update
      256│         try:
      257│             r = urlopen(base_url + "/{}/{}".format(version, checksum))
      258│         except HTTPError as e:
      259│             if e.code == 404:
    → 260│                 raise RuntimeError("Could not find {} file".format(checksum))
      261│ 
      262│             raise
      263│ 
      264│         checksum = r.read().decode().strip()

```

**Comment by finswimmer** [comment]
This is expected as you installed using the get-poetry.py script. The [release announcement](https://python-poetry.org/blog/announcing-poetry-1.2.0) has the best directions for upgrading, but you can also find them in the [install directions](https://python-poetry.org/docs/1.2/#installation).

Please reinstall with the new script, and you'll be good to go!

**Comment by zyv** [comment]
@finswimmer alright thank you for your help, thank was quick! It worked - I wish it weren't necessary or this announcement would have been more visible though - but at least now hopefully folks will be able to find this ticket by googling for the error message or search GitHub issues.

**Comment by Secrus** [comment]
> @finswimmer alright thank you for your help, that was quick! It worked - I wish it weren't necessary or this announcement would have been more visible though - but at least now hopefully folks will be able to find this ticket by googling for the error message or search GitHub issues.

We had announcements on our website and Discord. Do you have any pointers on where it should be posted so it's more visible?

**Comment by zyv** [comment]
@secrus well, as you can see, not everybody reads the announcements and Discord doesn't cover the complete user base.

The worst part for me was not being able to find it by googling for the error message. So if I were you, I would have added the error message to the release announcement along the lines of

> ... if you are getting "Could not find poetry-1.2.0-linux.sha256sum file" when running `self update`, then you must have installed Poetry using `get-poetry.py` script and need to do this & that ...

This way you'd get to this explanation as soon as you search for the error message.
