### ISSUE TITLE
Poetry 1.1 Upgrade to 1.2 instructions unclear

### ISSUE THREAD

**Issue by EldarSehayekZenity** [python-poetry/poetry#6420]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue
I tried to follow the Poetry 1.2 instructions to upgrade from Poetry 1.1.14 version I have. I run on Windows 11.
When I tried to run "poetry self update" from admin terminal, I get errors: 

![image](https://user-images.githubusercontent.com/94788315/188600660-acff21da-7bc3-4498-b847-236e03e44d74.png)

So I figured perhaps I should uninstall since I used the previous official installer, only that the instructions say it's deprecated but they don't say from where I can retrieve it to perform the uninstall and re-install using new script.

![image](https://user-images.githubusercontent.com/94788315/188600896-57eb2d63-3068-40c7-9746-1db2ca1315da.png)

My team is upgrading to Poetry 1.2 and I must upgrade as well, can you please assist?

**Comment by Secrus** [comment]
See point 6 of the instruction you screenshotted. 
![Screenshot from 2022-09-06 11-39-55](https://user-images.githubusercontent.com/26322915/188602316-343bba7c-88f8-402d-8c48-e22cf232407f.png)

**Comment by EldarSehayekZenity** [comment]
> See point 6 of the instruction you screenshotted. ![Screenshot from 2022-09-06 11-39-55](https://user-images.githubusercontent.com/26322915/188602316-343bba7c-88f8-402d-8c48-e22cf232407f.png)

Worked thank you!
