### ISSUE TITLE
Fails updating with "authorization error" (private repos)

### ISSUE THREAD

**Issue by sr-verde** [python-poetry/poetry#6422]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: `Linux XYZ 5.19.6-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 31 Aug 2022 22:09:40 +0000 x86_64 GNU/Linux`
- **Poetry version**: 1.2.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: [pyproject.toml](https://gist.github.com/sr-verde/6a668959c8a1c33f76e16a2fe0a86365)

## Issue

When trying to updating dependencies using `poetry update` poetry fails with following error messages (truncated):

```
$ poetry --version
Poetry (version 1.2.0)
$ poetry update
Updating dependencies
Resolving dependencies... (0.6s)Source (xxx1): Authorization error accessing https://git.xxx.de/api/v4/projects/1/packages/pypi/simple/pylint/
Resolving dependencies... (2.0s)Source (xxx1): Authorization error accessing https://git.xxx.de/api/v4/projects/1/packages/pypi/simple/pyflakes/
Resolving dependencies... (2.8s)Source (xxx1): Authorization error accessing https://git.xxx.de/api/v4/projects/1/packages/pypi/simple/xenon/
…
```

It looks like Poetry is trying to install the dependencies all from the private repositories instead from pypi.

When downgrading to poetry 1.1.15 updating works as expected:

```
$ poetry --version
Poetry version 1.1.15
$ poetry update
Updating dependencies
Resolving dependencies... (123.5s)

Writing lock file

Package operations: 0 installs, 20 updates, 0 removals

  • Updating greenlet (1.1.2 -> 1.1.3)
  • Updating prompt-toolkit (3.0.30 -> 3.0.31)
  • Updating werkzeug (2.2.0 -> 2.2.2)
  • Updating flask (2.1.3 -> 2.2.2)
  • Updating mako (1.2.1 -> 1.2.2)
  • Updating sqlalchemy (1.4.39 -> 1.4.40)
  • Updating charset-normalizer (2.1.0 -> 2.1.1)
  • Updating urllib3 (1.26.11 -> 1.26.12)
  • Updating astroid (2.11.7 -> 2.12.6)
  • Updating dparse (0.5.1 -> 0.5.2)
  • Updating flask-security-too (4.1.4 -> 4.1.5)
  • Updating pathspec (0.9.0 -> 0.10.1)
  • Updating tomlkit (0.11.1 -> 0.11.4)
  • Updating black (22.6.0 -> 22.8.0)
  • Updating coverage (6.4.2 -> 6.4.4)
  • Updating freezegun (1.2.1 -> 1.2.2)
  • Updating pyflakes (2.4.0 -> 2.5.0)
  • Updating pylint (2.14.5 -> 2.15.0)
  • Updating setproctitle (1.2.3 -> 1.3.2)
  • Updating types-six (1.16.18 -> 1.16.19)
```

**Comment by dimbleby** [comment]
that's not a failure, that's just a new log

**Comment by sr-verde** [comment]
And one cannot suppress that? :open_mouth: Is there more info about that new "feature"?

**Comment by dimbleby** [comment]
what info could you possibly want?

#5984 contains some discussion around the fact that poetry currently likes to try all sources for all packages, and an embryonic plan to change that

**Comment by clintonroy** [comment]
Check out https://python-poetry.org/docs/repositories/, in particular ``If package sources are defined for a project, these will take precedence over [PyPI](https://pypi.org/). If you do not want this to be the case, you should declare all package sources to be [secondary](https://python-poetry.org/docs/repositories/#secondary-package-sources).''

Give that a burl.

**Comment by dimbleby** [comment]
I don't expect that to help, poetry has always tried secondary sources for packages even if the package was already found in a primary source.  That's exactlyw hat #5984 is about.

This one can safely be closed as a duplicate, though

**Comment by sr-verde** [comment]
Yeah, I just don't want to see those error messages.

> This one can safely be closed as a duplicate, though

I agree. Thanks!
