### ISSUE TITLE
Required dependency missing from lockfile

### ISSUE THREAD

**Issue by levrik** [python-poetry/poetry#6434]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS 12.5.1
- **Poetry version**: 1.2.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/levrik/a4b55e147eafc9817cf82c5a92b801fd

## Issue

Adding the package `ariadne` to an empty project via `poetry add ariadne` results in a lockfile being generated with the `starlette` dependency missing from it.
We discovered it by upgrading an existing project to Poetry 1.2.0 and re-installing `ariadne`. It resulted in the following diff:

![image](https://user-images.githubusercontent.com/9491603/188818718-0b6f19e5-0124-43f1-9c97-6da5a03641bc.png)

The package clearly defines `starlette` as an required dependency, as can be seen here: https://github.com/mirumee/ariadne/blob/0.15.1/setup.py#L36

The `METADATA` file in the downloaded Wheel also contains this line: `Requires-Dist: starlette (>0.17<0.20)`

**Comment by levrik** [comment]
I just realized that the version range defined by `ariadne` is just wrong, missing a comma between `>0.17` and `<0.20` ?

**Comment by levrik** [comment]
Okay. Seems to have been fixed already on their side: https://github.com/mirumee/ariadne/pull/877

So no bug on Poetry's side. Still it would be great if Poetry could maybe output a warning during installation instead of silently ignoring the dependency?

**Comment by dimbleby** [comment]
There's a debug log for this, I expect that an MR making this a warning would be welcome

https://github.com/python-poetry/poetry/blob/28d0175dc599dca3d582c2c110a6ea6fe39049c7/src/poetry/inspection/info.py#L208-L211

**Comment by levrik** [comment]
@dimbleby Thanks for pointing this out. I'll try to create a PR when I have time.
