### ISSUE TITLE
Authorization error using poetry 1.2 

### ISSUE THREAD

**Issue by dougpool** [python-poetry/poetry#6439]
- [ x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version 1.2
- [ x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 20.04
- **Poetry version**: 1.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: N/A
- 
## Issue

When running `poetry install` under 1.2 against a private pypi repo hosted in gitlab, I now get an authorization error. This previously worked under poetry 1.1.15

Note that the variable PROJECT_ACCESS_TOKEN is being properly dereferenced and as mentioned, this does work under poetry 1.1.15

## CICD log file

poetry config repositories.abcd https://git.somedomain.com/api/v4/projects/76/packages/pypi
$ poetry config http-basic.abcd pypi-tokens $PROJECT_ACCESS_TOKEN
Using a plaintext file to store credentials
$ poetry config virtualenvs.create false
Updating dependencies
Resolving dependencies...
Source (ABCD_Gitlab): Authorization error accessing https://git.somedomain.com/api/v4/projects/76/packages/pypi/simple/pytest-mock/
Source (ABCD_Gitlab): Authorization error accessing https://git.somedomain.com/api/v4/projects/76/packages/pypi/simple/pytest-asyncio/
[Same authorization error then repeats for all python dependencies]

## Work Around

Install/use poetry <1.2

**Comment by dimbleby** [comment]
It's just a log.  Duplicate #6422 / #5984

**Comment by dougpool** [comment]
Not sure how I missed those issues, then I guess I have another problem somewhere in my build because with poetry 1.2, the CICD job fails with `ERROR: Job failed: exit code 1` but works just fine with 1.1.15

Thanks for the prompt reply and I will dive deeper on my end (waybe how gitlab is processing the log, idk)

**Comment by neersighted** [comment]
Failures to authenticate shouldn't cause Poetry to exit with a failure status -- if there was an issue getting all the packages needed during `poetry install` you should get an exception stating as much. Good luck in your debugging!

**Comment by neersighted** [comment]
I see a `poetry config virtualenvs.create false` in there -- there's a solid chance your build is broken as installing to the system environment (especially if Poetry is there) is a bit fraught. You'll need to closely inspect your logs, but I wouldn't be surprised if there were weird errors about invalid version numbers or missing files because of that line.
