### ISSUE TITLE
Add breaking change to 'poetry run' to changelog

### ISSUE THREAD

**Issue by brandon-leapyear** [python-poetry/poetry#6440]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue
The changelog currently mentions a bug fix around `poetry run`:

> Fixed an error where command line options were not taken into account when using the run command. (https://github.com/python-poetry/poetry/pull/3618)
>
> ([link](https://github.com/python-poetry/poetry/blob/master/CHANGELOG.md#fixed-14))

But this is actually a breaking change. On Poetry 1.1, the following:
```bash
poetry run foo -- arg1 arg2
```
would run `foo -- arg1 arg2` in the poetry environment, but on Poetry 1.2, the `--` is handled by `poetry` and stripped. This causes issues with tox, because `tox -- arg1 arg2` is very different from `tox arg1 arg2`. With Poetry 1.2, the following is now required (as opposed to before, when it was optional): `poetry run -- foo -- arg1 arg2`. It's currently very difficult to search for this change in behavior in the CHANGELOG (I had to search for any instances of `run` in the CHANGELOG, and it ended up being under the 1.2.0a section)

**Comment by catcombo** [comment]
We have the same problem running custom Django command that accepts another command with arguments.
