### ISSUE TITLE
Cyclic dependency between poetry and poetry-plugin-export

### ISSUE THREAD

**Issue by maresb** [python-poetry/poetry#6441]
`poetry-plugin-export` v1.0.4 (and earlier) depends on `poetry = "^1.2.0b1dev0"`.

Poetry `1.2.0b2` introduces a dependency on `poetry-plugin-export = "^1.0.4"`.

While this might not be immediately problematic, ideally the directed dependencies graph should remain acyclic. This is already causing trouble in https://github.com/conda-forge/poetry-feedstock/pull/67.

**Comment by xylar** [comment]
Just a note to say that I think we can actually handle circular dependencies on conda-forge, it's just a bit awkward.  If the circular dependencies can't be satisfied for either package with existing package builds, we have to do a build of one or the other package without the circular dependency and then another build with it.  It's not elegant but it works.  So we may be able to close this issue.
