### ISSUE TITLE
Debug level logging (-vvv) should report when a .gitignore file was used to ignore a potential package file

### ISSUE THREAD

**Issue by shaunco** [python-poetry/poetry#6443]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request
After a very frustrating two days of trying to figure out why `poetry build` was silently ignoring all of the .py files in my package, I finally renamed a .gitignore file that was 3 parent directories above (`../../../.gitignore`) where I was running `poetry build` and my files were finally included.

While this is totally on me, as the docs point out that .gitignore files will be used, those two days would have been reduced to about 5 seconds if `-vvv` output something like:
```
Building myproj (0.1.0)
  - Building sdist
  - Ignoring: /home/test/some/dir/structure/myproj/myproj/__init__.py   (per /home/test/some/.gitignore)
  - Adding: pyproject.toml
  - Adding: README.md
  - Built myproj-0.1.0.tar.gz
  - Building wheel
  - Ignoring: /home/test/some/dir/structure/myproj/myproj/__init__.py   (per /home/test/some/.gitignore)
  - Ignoring: /home/test/some/dir/structure/myproj/myproj/test/__init__.py   (per /home/test/some/.gitignore)
Skipping: /home/test/some/dir/structure/myproj/myproj/LICENSE
Skipping: /home/test/some/dir/structure/myproj/myproj/COPYING
  - Built myproj-0.1.0-py3-none-any.whl
```

Where the lines that start with `Ignoring` is new, as currently it will just show:
```
Building myproj (0.1.0)
  - Building sdist
  - Adding: pyproject.toml
  - Adding: README.md
  - Built myproj-0.1.0.tar.gz
  - Building wheel
Skipping: /home/test/some/dir/structure/myproj/myproj/LICENSE
Skipping: /home/test/some/dir/structure/myproj/myproj/COPYING
  - Built myproj-0.1.0-py3-none-any.whl
```

**Comment by dimbleby** [comment]
Code is [here](https://github.com/python-poetry/poetry-core/blob/0a1d5f194b1a7b6a11624ec6548ba0d8aa2e52bc/src/poetry/core/masonry/builders/builder.py#L112) if you'd like to submit an MR

**Comment by evanrittenhouse** [comment]
@dimbleby I've got a local branch with a `logger.debug` call to print out the ignored files. Should I submit the PR against the core Poetry repo or Poetry-Core?

**Comment by dimbleby** [comment]
the code is in poetry-core, that's where the MR will be
