### ISSUE TITLE
Move virtualenvs from ~/.cache to ~/.local/share (or ~/.poetry)

### ISSUE THREAD

**Issue by egormkn** [python-poetry/poetry#6444]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

On linux, Poetry stores its virtual environments under `~/.cache/pypoetry/virtualenvs`, however it's not really a cache. As far as I know, the `~/.cache` directory is meant to be used for the files that are safe to delete, and programs are expected to simply recreate them if needed without user interaction. `~/.cache/pypoetry/virtualenvs` does not follow this semantics, as after clearing `~/.cache` the user must run `poetry install` again to be able to use `poetry run`. This also complicates the usage of Docker BuildKit caching, as one can not simply use 
```dockerfile
RUN --mount=type=cache,target=/home/user/.cache ...
```
but more complex directory layout should be specified:
```dockerfile
RUN --mount=type=cache,target=/home/user/.cache/pip \
    --mount=type=cache,target=/home/user/.cache/pypoetry/cache \
    --mount=type=cache,target=/home/user/.cache/pypoetry/artifacts \
    ...
```

I suggest to think about moving virtualenvs to the data directory (`~/.local/share/pypoetry` or `~/pypoetry`), as this directory is used for [storing various user specific data](https://specifications.freedesktop.org/basedir-spec/latest/ar01s03.html).

**Comment by dimbleby** [comment]
duplicate #3346

**Comment by egormkn** [comment]
Oh, I really tried to find duplicates, but missed that. Closing the issue.
