### ISSUE TITLE
Unclear which poetry version is actually installed

### ISSUE THREAD

**Issue by 4sfaloth** [python-poetry/poetry#6462]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS Monterey 12.5.1
- **Poetry version**: 1.2.0 / 1.1.15 (see description below)
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: NA

## Issue
Hi,

I'm getting contradictory statements on which poetry version is installed when I run `poetry -V` or when I try to uninstall it from the system. See the screenshot below:

![Screenshot 2022-09-09 at 13 21 17](https://user-images.githubusercontent.com/8202087/189350139-40666563-844f-4b35-ae01-72cb8d7c5a2b.png)

For extra context I have been doing multiple experiments over the last few weeks, installing/uninstalling the 1.2.0 beta release, then back to 1.1.x and now recently had installed the 1.2.0 stable. 

Anything in particular that could cause this confusion, and how should I go about and fix it?
thanks in advance 🙏

**Comment by neersighted** [comment]
The old `get-poetry.py` script installs and uninstalls from `~/.poetry`. The official installer writes to a OS-specific path (see the docstring/install docs). If you still have a Poetry after uninstalling with both installers, do `which poetry` -- you likely installed it with pip, pipx, or your OS package manager.

**Comment by 4sfaloth** [comment]
so after running
`curl -sSL https://install.python-poetry.org | POETRY_UNINSTALL=1 python3 -`
`which poetry` was unable to find any installed version (same for `poetry -V`). 

`~/.poetry` doesn't exist so it looks like I don't have any legacy install leftovers.

I tried installing and uninstalling both 1.2.0 and 1.1.15 using the official installers and this timer there was no version mismatch. Not sure what happened, but most likely a leftover from my extensive tests and seems to be fixed now. Thanks for the quick reply and sorry for the bother @neersighted , closing
