### ISSUE TITLE
Issue with filename for wheel with epoch version

### ISSUE THREAD

**Issue by wenkokke** [python-poetry/poetry#6466]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS 11
- **Poetry version**: 1.2.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: n/a

## Issue

When using a version number such as "1!1.0.0", the wheels generated by poetry have a filename with "1_1.0.0". This causes pip install to crash with the following error:
"ERROR: Could not build wheels for *, which is required to install pyproject.toml-based projects".

I believe that the following regular expression is at fault as it replaces the `!` with `_`:
https://github.com/python-poetry/poetry/blob/6fe7f54a83c59131d4e291084c3496a0c513cfaa/poetry/masonry/builders/wheel.py#L197-L203

**Comment by dimbleby** [comment]
That seems to be what the spec says should be done: https://peps.python.org/pep-0427/#escaping-and-unicode

> Each component of the filename is escaped by replacing runs of non-alphanumeric characters with an underscore 

(I think you are confusing hyphens and underscores in your report, I don't think hyphens should be introduced)

**Comment by wenkokke** [comment]
Yeah, it's an underscore, that was a typo.

Unfortunately, that does break installing with the latest pip.

**Comment by dimbleby** [comment]
I dunno, I'm curious about whether PEP-427 is really the final word here.  If it is then I guess you should report this to pip.

However I could believe that there's more to be said about this and that poetry might not be right.

Would be interesting to know what other tooling does when building a wheel with a version that contains an epoch, or to see any published examples on pypi of such a wheel...

**Comment by wenkokke** [comment]
I've also submitted this to pip, hopefully we can figure out which implementation is correct.

**Comment by wenkokke** [comment]
> The rule you referenced from PEP 427 is outdated. The most up-to-date and canonical specification of wheel file names (among other things) [can be found on packaging.python.org](https://packaging.python.org/en/latest/specifications/binary-distribution-format/):
> 
> > Version numbers should be normalised according to [PEP 440](https://peps.python.org/pep-0440/). Normalised version numbers cannot contain `-`.
> 
> A wheel builder should retain the `!` character, and Poetry’s current implementation is incorrect.

**Comment by dimbleby** [comment]
Then I expect an MR fixing this would be welcome

I see you've linked above to some truly ancient code, the fix should now be over in poetry-core, something like this

- copy the existing [fixture](https://github.com/python-poetry/poetry-core/tree/main/tests/masonry/builders/fixtures/localversionlabel) and [testcase](https://github.com/python-poetry/poetry-core/blob/37cee90a5dd4c7ee2c5ee836216ba813242b3ade/tests/masonry/builders/test_wheel.py#L125-L135) for localversionlabel, but switching in a version with an epoch to hit your case
- fix [`escape_version()`](https://github.com/python-poetry/poetry-core/blob/37cee90a5dd4c7ee2c5ee836216ba813242b3ade/src/poetry/core/masonry/utils/helpers.py#L22-L28)
- job done

**Comment by radoering** [comment]
> Version numbers should be normalised according to [PEP 440](https://peps.python.org/pep-0440/). Normalised version numbers cannot contain -.

Sounds like we should just do `return str(Version.parse(version))` in `escape_version()`.

**Comment by dimbleby** [comment]
I'm now pretty sure that the version being passed to `escape_version()` is already normalized and `escape_version()` is simply counterproductive and wants removing altogether.

**Comment by dimbleby** [comment]
fixed in https://github.com/python-poetry/poetry-core/pull/469, this can be closed
