### ISSUE TITLE
Simple api repository creates a file sourced package in lock file.

### ISSUE THREAD

**Issue by mjfitzge** [python-poetry/poetry#6467]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 20.04.5 LTS
- **Poetry version**: 1.2.0

## Issue
Using a private, simple, secondary repository the source is then created as a "file" type source in the poetry lock file. This means that the lock file cannot be used in CI/CD or automated build systems as the file won't exist. Poetry should provide the link to the file instead.

The relevant parts of the pyproject.toml:

```
[tool.poetry.dependencies]
proto-bindings = { version = "3.0.0+3171.72", source = "proto-bindings" }

[[tool.poetry.source]]
name = "proto-bindings"
url = "https://{key}:@packagecloud.io/company_name/protobufs/pypi/simple/"
default = false
secondary = true
```

Produces a lock file that contains

```
[[package]]
name = "proto-bindings"
version = "3.0.0+3171.72"
description = ""
category = "main"
optional = false
python-versions = "*"

[package.source]
type = "file"
url = "../../../home/{username}/.cache/pypoetry/artifacts/0d/cc/11/3db39cfb34d8773d984d71356dab1119a2dc176635011acaa9129eabd7/proto_bindings-3.0.0_3171.72-py3-none-any.whl"
```

I believe the lock file should contain a link to the file or back to the repository and not a cached file.

**Comment by dimbleby** [comment]
please provide a way to reproduce.

(I set up a test using test.pypi as a secondary source and poetry behaves exactly as expected, not as you describe)

**Comment by mjfitzge** [comment]
Never mind, this bug was actually caused by poetry's cache using a cached file when it couldn't find it remotely, probably would be smart to not have that be default behavior with no log output without -vvv during the update. 

The actual issue I'm experiencing, after getting rid of that cache and recreating the virtual env is that poetry doesn't recognize the package version as being valid.. it used to in previous versions of poetry but apparently it doesn't now. 
Skipping url (https://{key}:@packagecloud.io/company_name/agent-protobufs/pypi/packages/proto_bindings-3.0.0_3171.72-py3-none-any.whl#sha1=aabf2e1478dc50459cc547d330d1040122c79305) due to invalid version (None)

And it was looking for version "3.0.0+3171.72". I think this is partially just an issue with package cloud and then a behavior change in poetry.
