### ISSUE TITLE
Version constraints on extra dependencies possibly not honored

### ISSUE THREAD

**Issue by gilbahat** [python-poetry/poetry#6474]
- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Darwin arm64 - MacOS Monterey
- **Poetry version**: 1.2.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: (confidential)

the following may be enough to trigger this:

[tool.poetry.dependencies]
aiohttp = {extras = ["speedups"], version = "^3.8.1"}

## Issue

Hi,

aiohttp has an extra set called 'speedups'. extras is defined as follows in setup.cfg:

[options.extras_require]
speedups =
  aiodns >= 1.1
  Brotli
  cchardet; python_version < "3.10"

my generated poetry.lock however contains cchardet with no version constraint, causing the extra to be installed on python3.10 as well:

[[package]]
name = "aiohttp"
version = "3.8.1"
description = "Async http client/server framework (asyncio)"
category = "main"
optional = false
python-versions = ">=3.6"

[package.dependencies]
aiodns = {version = "*", optional = true, markers = "extra == \"speedups\""}
aiosignal = ">=1.1.2"
async-timeout = ">=4.0.0a3,<5.0"
attrs = ">=17.3.0"
Brotli = {version = "*", optional = true, markers = "extra == \"speedups\""}
cchardet = {version = "*", optional = true, markers = "extra == \"speedups\""}
charset-normalizer = ">=2.0,<3.0"
frozenlist = ">=1.1.1"
multidict = ">=4.5,<7.0"
yarl = ">=1.0,<2.0"

[package.extras]
speedups = ["Brotli", "aiodns", "cchardet"]

also when doing a poetry export, I get:
cchardet==2.1.7 ; python_version >= "3.10" and python_version < "4.0"

I believe this is unintended behaviour.

**Comment by dimbleby** [comment]
```
$ curl -s https://pypi.org/pypi/aiohttp/json | jq ".info.requires_dist"
[
  "attrs (>=17.3.0)",
  "charset-normalizer (<3.0,>=2.0)",
  "multidict (<7.0,>=4.5)",
  "async-timeout (<5.0,>=4.0.0a3)",
  "yarl (<2.0,>=1.0)",
  "frozenlist (>=1.1.1)",
  "aiosignal (>=1.1.2)",
  "idna-ssl (>=1.0) ; python_version < \"3.7\"",
  "asynctest (==0.13.0) ; python_version < \"3.8\"",
  "typing-extensions (>=3.7.4) ; python_version < \"3.8\"",
  "aiodns ; extra == 'speedups'",
  "Brotli ; extra == 'speedups'",
  "cchardet ; extra == 'speedups'"
]
```
which shows that indeed aiohttp puts no constraint on the cchardet version

**Comment by gilbahat** [comment]
interesting. perhaps the bug is with aiohttp then? I will file an issue with them and close this one.
