### ISSUE TITLE
HTTP 407 error when using a git source

### ISSUE THREAD

**Issue by jakecoffman** [python-poetry/poetry#6485]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**:  macOS 12.5.1, Debian 11 
- **Poetry version**:  1.2.0, also tested against master and older 1.1 releases 
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://github.com/dsp-testing/poetry-407/blob/main/pyproject.toml
## Issue

 Hi Poetry friends 👋 

In Dependabot we're seeing an issue where when pyproject.toml contains a git source for a dependency we get a 407 Proxy Authentication Required. Dependabot uses a proxy that requires authentication to do updates. To reproduce the issue, I created https://github.com/dsp-testing/poetry-407 since it takes a bit of setup.

It seems that when the git source is present, Poetry loses the username and password to the proxy. 

Let me know if you have other questions or I've left something out. Thanks!

**Comment by dimbleby** [comment]
if this is specifically a problem with git dependencies then probably it's a [dulwich](https://github.com/jelmer/dulwich) issue and wants reporting there.  

Even better if you can create a standalone repro using dulwich code.

Looks like dulwich does have code to try to handle this - https://github.com/jelmer/dulwich/blob/3d4322c06fa79ddfff95e09dbc365b83d9b3f15b/dulwich/client.py#L1834.  I could believe either that that's not working properly, or that poetry is somehow doing it wrong.

meanwhile you could try sidestepping dulwich and falling back to system git per https://python-poetry.org/docs/configuration/#experimentalsystem-git-client

**Comment by dimbleby** [comment]
Just to confirm: I updated your repro so that script.sh ends with `git clone https://github.com/uiri/toml` and doesn't do anything poetry at all.

That sees the same output:
```
Cloning into 'toml'...
127.0.0.1:59226: client connect
127.0.0.1:59226: CONNECT github.com:443
              << 407 Proxy Authentication Required 129b
```
which seems to make clear that poetry is not introducing a problem here.

**Comment by jakecoffman** [comment]
Yes I did the same thing! I think the repro isn't quite right and your analysis that it may be `dulwich` is correct.

I'm updating Dependabot to use Poetry's `experimental.system-git-client` feature which seems to have taken care of it locally for me. 

Thanks for the help!

**Comment by dimbleby** [comment]
No worries.

dulwich is reasonably active, if you do find the time to reproduce accurately they'd likely welcome the report.

**Comment by neersighted** [comment]
I would encourage getting support into dulwich -- long-term we don't plan to keep the system-git-client option, but only after dulwich proves stable/feature complete for our uses.
