### ISSUE TITLE
bash completion has syntax errors

### ISSUE THREAD

**Issue by danielhoherd** [python-poetry/poetry#6486]
- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: raspios, macos
- **Poetry version**: 1.2.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: N/A, this is just for the completion code
- **Bash versions tested**:
  - GNU bash, version 5.1.16(1)-release (aarch64-apple-darwin21.1.0)
  - GNU bash, version 3.2.57(1)-release (arm64-apple-darwin21)
  - GNU bash, version 5.1.4(1)-release (aarch64-unknown-linux-gnu)

## Issue

`poetry completions bash` generates syntactically incorrect bash code.

### Steps to reproduce

```
$ poetry completions bash > poetry-completion.sh
$ source poetry-completion.sh
-bash: poetry-completion.sh: line 40: syntax error near unexpected token `clear'
-bash: poetry-completion.sh: line 40: `            (cache clear)'
$ shellcheck poetry-completion.sh

In poetry-completion.sh line 26:
        case "$com" in
        ^-- SC1009 (info): The mentioned syntax error was in this case expression.


In poetry-completion.sh line 40:
            (cache clear)
            ^-- SC1073 (error): Couldn't parse this case item. Fix to allow more checks.
                   ^-- SC1072 (error): Expected ) to open a new case item. Fix any mentioned problems and try again.
                   ^-- SC1085 (error): Did you forget to move the ;; after extending this case item?

For more information:
  https://www.shellcheck.net/wiki/SC1085 -- Did you forget to move the ;; aft...
  https://www.shellcheck.net/wiki/SC1072 -- Expected ) to open a new case ite...
  https://www.shellcheck.net/wiki/SC1073 -- Couldn't parse this case item. Fi...
```

**Comment by danielhoherd** [comment]
I see a few issues with the completion code.

First, bash `case` statement items are not wrapped in parenthesis, they are delimited by a closing parenthesis.

```sh
        case "$com" in
            (about)
            opts="${opts} "
            ;;
```

Should be

```sh
        case "$com" in
            about)
            opts="${opts} "
            ;;
```

Secondly, and a bigger problem to solve, the comparisons being made in the case statement are trying to compare multiple words when only one word is being checked. This is a problem both syntactically and in terms of how the code is structured.

```
            cache clear)
            opts="${opts} --all"
            ;;
```

That code is syntactically invalid because there is unquoted whitespace in it. `cache clear)` is an invalid case match. `"cache clear")` would work, but that would be wrong for poetry, requiring users to run `poetry "cache clear"` or equivalent. EG:

```sh
#!/usr/bin/env bash
# cat example-1.sh
case "$1" in
  "cache clear")
    echo "1 is $1"
    ;;
  *)
    echo "default target"
    ;;
esac
```
```
$ shellcheck example-1.sh ; echo $? ;
0
$ ./example-1.sh cache clear
default target
$ ./example-1.sh "cache clear"
1 is cache clear
```

So the way this needs to be structured is to check each word individually, then any more words beyond that one, in a tree structure of completions rather than a flat list of possible completions:

```sh
#!/usr/bin/env bash
# example-2.sh
case "$1" in
  cache)
    echo "1 is $1"
    case "$2" in
      clear)
        echo "2 is $2"
        ;;
      *)
        echo "default cache target"
        ;;
      esac
    ;;
  *)
    echo "default target"
    ;;
esac
```
```
$ shellcheck example-2.sh ; echo $? ;
0
$ ./example-2.sh cache clear
1 is cache
2 is clear
$ ./example-2.sh cache jklsjdfk
1 is cache
default cache target
```

**Comment by dimbleby** [comment]
duplicate #4572, and the several other duplicates linked from that

**Comment by Secrus** [comment]
As mentioned in the previous comment, it's a duplicate. What's more, a fix was made upstream in [`cleo`](https://github.com/python-poetry/cleo), pending release.
