### ISSUE TITLE
Fail to pip install after poetry export

### ISSUE THREAD

**Issue by shencar** [python-poetry/poetry#6487]
- [x ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [ x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- Mac OSX
- poetry version == 1.2.0

## Issue
When running 
```
poetry export -f requirements.txt > requirements.txt --without-hashes
pip install -r requirements.txt
```
installation immediately fails on 
```
 Invalid requirement: 'Creating virtualenv my-repo-AsW4q1BB-py3.9 in /root/.cache/pypoetry/virtualenvs' (from line 1 of requirements.txt)
 It looks like a path. File 'Creating virtualenv  my-repo-AsW4q1BB-py3.9 in /root/.cache/pypoetry/virtualenvs' does not exist.
```

**Comment by dimbleby** [comment]
duplicate #6347, among others

**Comment by neersighted** [comment]
Duplicate, solved in master, and there's a current workaround using `-o <file>`
