### ISSUE TITLE
Cannot install psycopg2 from poetry in Mac M1&M2 

### ISSUE THREAD

**Issue by Shayan-Shabanzadeh** [python-poetry/poetry#6489]
it appears that there is a problem in installing psycopg2 from poetry in mac M2 but the weirdest thing about it is that pyscopg2 is available from pip and it works perfectly but for some reason is not available from Poetry.

**my system is MacBook Pro 2022 M2 processor
**pip version is pip (python 3.10).
**Poetry (version 1.2.0)

**Comment by neersighted** [comment]
Without a `pyproject.toml` it is impossible to reproduce this or offer significant assistance. However, it is worth noting that the [psycopg2 files available](https://pypi.org/project/psycopg2/#files) do not include wheels for any non-Windows platform. This does not appear to be a Poetry issue -- you will need a working C compiler and the relevant headers to build `psycopg2` on your Mac in this case, as there are no prebuilt binaries.

It is possible that you have a working compiler environment, but the `psycopg2` package is not PEP 517 compliant and cannot be built by Poetry. You can test this by running `pip install --use-pep517 psycopg2` and checking if it still installs -- if not, it's an upstream issue with `psycopg2` itself.

There is a pure Python substitute available in the `psycopg` package, as well as the `psycopg-native` package with macOS wheels for C-based acceleration -- maybe that will work for your situation if there is an issue with the `psycopg2` package.

Regardless, please request a re-open if you perform some of the troubleshooting steps listed here and still believe Poetry to be involved. If you do do so, please follow the issue reporting instructions, including posting a `pyproject.toml`.
