### ISSUE TITLE
Horovod installation fails with new installer

### ISSUE THREAD

**Issue by joeyearsley** [python-poetry/poetry#6492]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: 
- **Poetry version**: 
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue

When installing horovod it fails, stating its CMake command can't find the TensorFlow libraries.

Reproducible example:

pyproject.toml
```
[tool.poetry]
name = "tmp"
version = "0.1.0"
description = ""
authors = ["None"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.8"
tensorflow = "2.8.1"
horovod = {version="^0.25.0", extras=["tensorflow"]}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

**Comment by neersighted** [comment]
This will be an issue with a combination of your local environment and wheels built by tensorflow -- if you need to build tensorflow from source you will need the local build requirements. If you don't want to build from source, the upstream project will need to provide wheels for your platform.

**Comment by joeyearsley** [comment]
Just to clarify, do you mean built with TensorFlow?

Horovod utilises the TF shared objects from the TF Lib which is already installed via poetry, and this was working/building within poetry pre-1.2.0.

This seems like a regression within poetry rather than an external issue.

**Comment by neersighted** [comment]
This will still be an upstream issue then, but of a different variety -- what is likely occurring is a failure to build because of an undeclared build-time dependency on `tensorflow` during a PEP 517/PEP 518 isolated build. 

Indeed, this reproduces for me using `pip install --use-pep517 horovod[tensorflow]`. I suggest you open an issue upstream with horovod to make sure they are buildable in an isolated build environment.

In the future when reporting issues like this, please include a log and a detailed summary of what you expect, as well as Poetry version and OS version. A lot of similar issues center around platform specifics, and without the specific error message you are seeing it is hard to ensure we are talking about the same issue.

**Comment by joeyearsley** [comment]
Thanks for your help, I'll pass it on to them.

**Comment by joeyearsley** [comment]
@neersighted For projects like horovod where they have dynamic linking, do you believe there needs to be another PEP such that build systems like poetry can expose tensorflow to the isolated build environments without needing the requirement to be in the pyproject/setup_requires?

For example to enable poetry to expose tensorflow to the horovod build env without tensorflow being in the pyproject.toml/setup.py of horovod

**Comment by neersighted** [comment]
I don't think a PEP is needed necessarily -- to me it seems like reporting the build-time dependency when the extra is requested is enough. Wheels will not have any issue with the dependency not being reported as the binary parts will already be built.

I suppose it is possible that the current tooling is insufficient for this scenario, but my knowledge of the problem space is from the perspective of a packager and implementer, and not as a Python developer/standards author. If the existing tooling has trade-offs for this situation that make it untenable for horovod, starting a discussion on [DPO](https://discuss.python.org) would likely be the next best step.
