### ISSUE TITLE
Poetry Install fails on remote shell using credssp

### ISSUE THREAD

**Issue by LevonW-IIS** [python-poetry/poetry#6496]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows 2022 Standard 64 bit 21H2
- **Poetry version**: 1.2.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: [pyproject.toml](https://gist.github.com/LevonW-IIS/7314609f1e372114d336ff477856b8e3)

## Issue

I am trying to run poetry install from a remote session using CredSSP authentication, but poetry is running into an error. I have included the full output below with the -vvv flag on.

[pwsh.txt](https://github.com/python-poetry/poetry/files/9552844/pwsh.txt)

This fails with the error:
[WinError 1312] A specified logon session does not exist. It may already have been terminated.

To Reproduce:
- ensure host and client are [set up](https://docs.microsoft.com/en-us/powershell/module/microsoft.wsman.management/enable-wsmancredssp?view=powershell-7.2) for winrm with credssp authentication
- run the following commands:
```
$cred = Get-Credential
New-PSSession -Authentication Credssp -Credential $cred -ComputerName "HostNameOfRemoteComputer"
Invoke-Command -Session $s {cd location/of/test/project/toml ; poetry install -vvv}
```

Will try downgrade poetry and see if the issue persists and update this with the results of that test

**Comment by LevonW-IIS** [comment]
No issue running this on poetry 1.1.7. Works as expected.

**Comment by neersighted** [comment]
Try setting `PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring` and report back, please.

**Comment by LevonW-IIS** [comment]
Added in ``` [Environment]::SetEnvironmentVariable("PYTHON_KEYRING_BACKEND", 'keyring.backends.null.Keyring', [System.EnvironmentVariableTarget]::Machine); ``` to the powershell script but got the same error

**Comment by mhwaage** [comment]
> Added in `[Environment]::SetEnvironmentVariable("PYTHON_KEYRING_BACKEND", 'keyring.backends.null.Keyring', [System.EnvironmentVariableTarget]::Machine);` to the powershell script but got the same error

If you target Machine, the environment variable should not be visible until a new process spawns (c.f. examples in icrosoft's [docs](https://docs.microsoft.com/en-us/dotnet/api/system.environment.setenvironmentvariable?view=net-6.0#system-environment-setenvironmentvariable(system-string-system-string-system-environmentvariabletarget)) ); try targeting `EnvironmentVariableTarget.Process` instead.

**Comment by LevonW-IIS** [comment]
That worked a treat, thanks. Should've spotted that one

**Comment by neersighted** [comment]
Duplicate #1917, then
