### ISSUE TITLE
poetry fails to create env `env use python3.xx`

### ISSUE THREAD

**Issue by simonpercivall** [python-poetry/poetry#6500]
OS: macOS 12.6
Xcode 14.0
Poetry version: 1.2.0
Installed through official installer, through `homebrew`, and through `pipx`. Not running which `pyenv` or similar (symlinking `python`, or going through `pyenv` works).

So sorry if this is a dup, I get that y'all have been kinda overwhelmed after the 1.2.0 release. I've seen _similar_ reports, but this may be yet another case that goes wrong.

The latest macOS version and latest Xcode version has removed the plain `python`, the same goes for Homebrew, of course.

(Btw, using the official installer fails with the system `python3` install, but let's ignore that.)

Trying to use poetry's `env use` results in:

```
> poetry env use python3.10
[Errno 2] No such file or directory: 'python'
```

Not surprising, since no `python` executable exists.

**Comment by clintonroy** [comment]
I can't help with mac issues, but maybe the output of "poetry debug info" would be useful to those that can.

**Comment by alain-odea-sequence** [comment]
Assuming you've installed Python 3 with Homebrew, I have a an _objectively terrible_ workaround that likely has consequences for other stuff depending on python:
```
ln -s /usr/local/bin/python3 /usr/local/bin/python
```

Or on Apple Silicon:
```
ln -s /opt/homebrew/bin/python3 /opt/homebrew/bin/python
```

I really dislike this, but I have stuff I need to run immediately and I needed a duct tape solution.

**Comment by simonpercivall** [comment]
After more debugging, turns out this is because I had `VIRTUAL_ENV` set without that virtual environment actually existing.

So closing this.

It could turn into a feature request for `poetry` to run more validation to protect against people doing weird things with their environment, but not a bug anymore.
