### ISSUE TITLE
"__vte_prompt_command: command not found" when using poetry shell

### ISSUE THREAD

**Issue by catsclaw** [python-poetry/poetry#6501]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Pop!_OS 22.04 LTS
- **Poetry version**: Poetry (version 1.2.0)
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: [Gist](https://gist.github.com/catsclaw/425751f661e22cb06445f3b761def987)

## Issue
Whenever I run `poetry shell` every invocation of the command line says "__vte_prompt_command: command not found"

**Comment by neersighted** [comment]
This is an issue with your shell configuration -- `poetry shell` spawns a non-login interactive copy of `$SHELL` and then feeds it keyboard input to source the virtual environment activation script. If your shell is not properly configured, things like this may happen. A quick Google search turns this up as a common issue with VTE-based terminals: try [here](https://stackoverflow.com/questions/22281875/bash-vte-prompt-command-command-not-found) to get started.

**Comment by catsclaw** [comment]
I'm not using a VTE-based terminal and the issue only happens with `poetry`.

**Comment by neersighted** [comment]
I'm still not sure what to tell you, other than to inspect your `.bashrc`. 

The invocation inside Poetry is very simple, and without a container reproduction, no one will be able to offer much help as this should be entirely related to local configuration:

https://github.com/python-poetry/poetry/blob/bacef6a5be897192ce7d80e650fba2eafc13c194/src/poetry/utils/shell.py#L71-L111

**Comment by catsclaw** [comment]
I can comment out the entirety of my .bashrc and the problem still occurs.
When I run "poetry shell" I get the error. It doesn't show up if I don't.
poetry is doing *something* to trigger the error.

**Comment by neersighted** [comment]
If you would like to confirm Poetry is not involved, you should be able to modify your copy of `shell.py` locally to add `--norc --noprofile` to the invocation of the shell. I suspect that you may be experiencing some odd interaction between something in /etc/profile.d or similar.

I would be happy to help walk you through basic troubleshooting of shell issues on Discord -- this tracker is not a great venue for it.
