### ISSUE TITLE
`Unidecode` error while exporting in Poetry 1.2

### ISSUE THREAD

**Issue by nbro10** [python-poetry/poetry#6514]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS Monterey (version 2.4)
- **Poetry version**: 1.2.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: [gist](https://gist.github.com/nbro10/8c3f1bc25074422d7c79120b61ae8bc1)

## Issue

I am getting a `Unidecode` error. Here's how to reproduce it.

1. Create a `pyproject.toml` as follows

```
[tool.poetry]
name = "poetry-unidecode-issue"
version = "0.1.0"
description = ""
authors = ["me"]
readme = "README.md"
packages = [{include = "poetry_unidecode_issue"}]

[tool.poetry.dependencies]
python = "^3.8"

python-slugify = {version = "^6.1.2", extras = ["Unidecode"]}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

2. Do `poetry update`
3. Do ` poetry export -f requirements.txt --without-hashes  --output requirements.txt` and get the very useful `'Unidecode'` error message. If you use the debug mode, you will also get a `KeyError`.

## Solution

Change `python-slugify = {version = "^6.1.2", extras = ["Unidecode"]}` to `python-slugify = {version = "^6.1.2", extras = ["unidecode"]}`. So, clearly, Poetry searches for an extra dep, but it's case sensitive.

**Comment by dimbleby** [comment]
duplicate https://github.com/python-poetry/poetry-plugin-export/issues/107

**Comment by dimbleby** [comment]
nevertheless, it really is

**Comment by dimbleby** [comment]
if you separately want to raise an issue about the case-sensitivity of extras - well that will duplicate https://github.com/python-poetry/poetry/issues/6321 so we don't need that either!
