### ISSUE TITLE
Installing custom plugin from private repository

### ISSUE THREAD

**Issue by jo014670** [python-poetry/poetry#6528]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows 10
- **Poetry version**: 1.2.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: N/A

## Issue
There does not appear to be a way to install a custom plugin from a private repository. There is no option like `poetry self source add` or anything like that, and if you try adding it manually to the poetry global `pyproject.toml`, it gets overwritten.

**Comment by neersighted** [comment]
Duplicate #6529 ultimately, as it is more of a question
