### ISSUE TITLE
.bash_completion Syntax error message after `poetry shell` command

### ISSUE THREAD

**Issue by atakanokan** [python-poetry/poetry#6543]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows 10 & WSL2
- **Poetry version**: 1.2.1
- **WSL2 Bash version**: 5.0.17(1)-release

## Issue
In VSCode WSL Ubuntu, when I do `poetry shell` I get the following error message (environment shell is activated without any problems):
```
username@username-SB2:/c/Users/username/Projects/project$ poetry shell -vvv
Loading configuration file /home/username/.config/pypoetry/config.toml
Using virtualenv: /home/username/.cache/pypoetry/virtualenvs/project-o_Fxvhls-py3.8
Spawning shell within /home/username/.cache/pypoetry/virtualenvs/project-o_Fxvhls-py3.8
bash: /home/username/.bash_completion: line 40: syntax error near unexpected token `clear'
bash: /home/username/.bash_completion: line 40: `            (cache clear)'
username@username-SB2:/c/Users/username/Projects/project$ . /home/username/.cache/pypoetry/virtualenvs/project-o_Fxvhls-py3.8/bin/activate
```

**Comment by dimbleby** [comment]
duplicate #4572 among others

**Comment by atakanokan** [comment]
@dimbleby thanks, they didn't show up when searched. Closing the issue
