### ISSUE TITLE
Could not find poetry-1.2.1-darwin.sha256sum file

### ISSUE THREAD

**Issue by trv-rachit** [python-poetry/poetry#6548]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Mac OS v2.6, Monterey
- **Poetry version**: Poetry version 1.1.14
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: Not project dependent

## Issue
Could not update poetry to 1.2.1 using command `poetry self update`. Throws below error:
`  RuntimeError

  Could not find poetry-1.2.1-darwin.sha256sum file

  at .poetry/lib/poetry/console/commands/self/update.py:260 in _update
      256│         try:
      257│             r = urlopen(base_url + "/{}/{}".format(version, checksum))
      258│         except HTTPError as e:
      259│             if e.code == 404:
    → 260│                 raise RuntimeError("Could not find {} file".format(checksum))
      261│
      262│             raise
      263│
      264│         checksum = r.read().decode().strip()`

**Comment by neersighted** [comment]
Duplicates a lot of issues -- this is known and intended as 1.1.x installed using the old get-poetry.py cannot `self update` -- please follow the instructions in [the docs](https://python-poetry.org/docs) to migrate to 1.2.x.
