### ISSUE TITLE
ModuleNotFoundError: No module named 'poetry.core.packages.dependency_group'

### ISSUE THREAD

**Issue by SebAlbert** [python-poetry/poetry#6556]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Gentoo GNU/Linux (rolling)
- **Poetry version**: 1.2.1 (Core 1.2.0)
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: not applicable

## Issue
After a fresh install `pip install --user poetry`, I wanted to start with `poetry --help`. I get the following error:

```
$ poetry --help -vvv
Traceback (most recent call last):
  File "/home/seb/.local/lib/python3.10/site-packages/cleo/application.py", line 329, in run
    exit_code = self._run(io)
  File "/home/seb/.local/lib/python3.10/site-packages/poetry/console/application.py", line 183, in _run
    self._load_plugins(io)
  File "/home/seb/.local/lib/python3.10/site-packages/poetry/console/application.py", line 349, in _load_plugins
    manager.load_plugins()
  File "/home/seb/.local/lib/python3.10/site-packages/poetry/plugins/plugin_manager.py", line 38, in load_plugins
    self._load_plugin_entry_point(ep)
  File "/home/seb/.local/lib/python3.10/site-packages/poetry/plugins/plugin_manager.py", line 76, in _load_plugin_entry_point
    plugin = ep.load()  # type: ignore[no-untyped-call]
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/seb/.local/lib/python3.10/site-packages/poetry_plugin_export/plugins.py", line 7, in <module>
    from poetry_plugin_export.command import ExportCommand
  File "/home/seb/.local/lib/python3.10/site-packages/poetry_plugin_export/command.py", line 4, in <module>
    from poetry.console.commands.group_command import GroupCommand
  File "/home/seb/.local/lib/python3.10/site-packages/poetry/console/commands/group_command.py", line 6, in <module>
    from poetry.core.packages.dependency_group import MAIN_GROUP
ModuleNotFoundError: No module named 'poetry.core.packages.dependency_group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/seb/.local/bin/poetry", line 8, in <module>
    sys.exit(main())
  File "/home/seb/.local/lib/python3.10/site-packages/poetry/console/application.py", line 388, in main
    exit_code: int = Application().run()
  File "/home/seb/.local/lib/python3.10/site-packages/cleo/application.py", line 334, in run
    self.render_error(e, io)
  File "/home/seb/.local/lib/python3.10/site-packages/poetry/console/application.py", line 175, in render_error
    self.set_solution_provider_repository(self._get_solution_provider_repository())
  File "/home/seb/.local/lib/python3.10/site-packages/poetry/console/application.py", line 377, in _get_solution_provider_repository
    from poetry.mixology.solutions.providers.python_requirement_solution_provider import (  # noqa: E501
  File "/home/seb/.local/lib/python3.10/site-packages/poetry/mixology/__init__.py", line 5, in <module>
    from poetry.mixology.version_solver import VersionSolver
  File "/home/seb/.local/lib/python3.10/site-packages/poetry/mixology/version_solver.py", line 11, in <module>
    from poetry.mixology.failure import SolveFailure
  File "/home/seb/.local/lib/python3.10/site-packages/poetry/mixology/failure.py", line 6, in <module>
    from poetry.core.semver.helpers import parse_constraint
ModuleNotFoundError: No module named 'poetry.core.semver.helpers'
```

I actually installed `poetry-core` via my operating system's package manager beforehands, which installed poetry-core 1.0.8 in the system, but this should not be a problem, since it was installed into `/usr/lib/python3.10/site-packages`, which comes *after* `/home/seb/.local/lib/python3.10/site-packages` on `sys.path`. (still, `/usr/lib/python3.10` comes before it, if that is of any relevance). The `pip install --user poetry` *did* install `poetry-core` 1.2.0 in my .local folder.

**Comment by dimbleby** [comment]
as you easily can verify, these modules do exist in the latest code.  Clearly you have somehow mixed things up with an older version.

This is not a poetry bug.

**Comment by SebAlbert** [comment]
Thanks. I would like to understand how this was mixed up. In my naive reasoning, any package that the command `pip install --user poetry` assumed as already satisfied and thus did not install explicitly in the actually required version must be a "missing requirement (version constraint)" of poetry, but I may be mistaken in thinking so.

**Comment by dimbleby** [comment]
poetry is not responsible for either pip or your system's package manager.

I'd suggest uninstall everything, start a fresh terminal, use the official poetry installer.  Then at least if something goes wrong, this will be a sensible place to ask for help!

(though even then you're likely better on discord than in the issue tracker, unless you really think you've found a bug)

**Comment by SebAlbert** [comment]
Thanks again. It was obviously my fault in assuming `pip install` was a viable (official) way of installing poetry.

**Comment by dimbleby** [comment]
(it is, but if you confuse your installation with a system installation then it's not a poetry bug!)

**Comment by SebAlbert** [comment]
Just in case somebody finds this issue, here is my tentative conclusion from digging into the import machinery.
The following `strace` output suggests to me that failing to find a `__init__.py` in `/home/seb/.local/lib/python3.10/site-packages/poetry`, but actually finding one in `/usr/lib/python3.10/site-packages/poetry`, has the import machinery choose the latter though it comes after the user-local path.

This is what I typed interactively:

```
>>> import sys
>>> sys.meta_path
[<_distutils_hack.DistutilsMetaFinder object at 0x7f3e4cb32a40>, <class '_frozen_importlib.BuiltinImporter'>, <class '_frozen_importlib.FrozenImporter'>, <class '_frozen_importlib_external.PathFinder'>]
>>> sys.meta_path[3].find_spec("poetry")
ModuleSpec(name='poetry', loader=<_frozen_importlib_external.SourceFileLoader object at 0x7f3e4cbbb1f0>, origin='/usr/lib/python3.10/site-packages/poetry/__init__.py', submodule_search_locations=['/usr/lib/python3.10/site-packages/poetry'])
```

Here is what `strace` shows during the last command:

```
newfstatat(AT_FDCWD, "/home/seb", {st_mode=S_IFDIR|0700, st_size=61440, ...}, 0) = 0
newfstatat(AT_FDCWD, "/usr/lib/python3.10", {st_mode=S_IFDIR|0755, st_size=12288, ...}, 0) = 0
newfstatat(AT_FDCWD, "/usr/lib/python3.10/lib-dynload", {st_mode=S_IFDIR|0755, st_size=4096, ...}, 0) = 0
newfstatat(AT_FDCWD, "/home/seb/.local/lib/python3.10/site-packages", {st_mode=S_IFDIR|0755, st_size=4096, ...}, 0) = 0
newfstatat(AT_FDCWD, "/home/seb/.local/lib/python3.10/site-packages/poetry/__init__.cpython-310-x86_64-linux-gnu.so", 0x7ffe8c892140, 0) = -1 ENOENT (Datei oder Verzeichnis nicht gefunden)
newfstatat(AT_FDCWD, "/home/seb/.local/lib/python3.10/site-packages/poetry/__init__.abi3.so", 0x7ffe8c892140, 0) = -1 ENOENT (Datei oder Verzeichnis nicht gefunden)
newfstatat(AT_FDCWD, "/home/seb/.local/lib/python3.10/site-packages/poetry/__init__.so", 0x7ffe8c892140, 0) = -1 ENOENT (Datei oder Verzeichnis nicht gefunden)
newfstatat(AT_FDCWD, "/home/seb/.local/lib/python3.10/site-packages/poetry/__init__.py", 0x7ffe8c892140, 0) = -1 ENOENT (Datei oder Verzeichnis nicht gefunden)
newfstatat(AT_FDCWD, "/home/seb/.local/lib/python3.10/site-packages/poetry/__init__.pyc", 0x7ffe8c892140, 0) = -1 ENOENT (Datei oder Verzeichnis nicht gefunden)
newfstatat(AT_FDCWD, "/home/seb/.local/lib/python3.10/site-packages/poetry", {st_mode=S_IFDIR|0755, st_size=4096, ...}, 0) = 0
newfstatat(AT_FDCWD, "/usr/lib/python3.10/site-packages", {st_mode=S_IFDIR|0755, st_size=36864, ...}, 0) = 0
newfstatat(AT_FDCWD, "/usr/lib/python3.10/site-packages/poetry/__init__.cpython-310-x86_64-linux-gnu.so", 0x7ffe8c892140, 0) = -1 ENOENT (Datei oder Verzeichnis nicht gefunden)
newfstatat(AT_FDCWD, "/usr/lib/python3.10/site-packages/poetry/__init__.abi3.so", 0x7ffe8c892140, 0) = -1 ENOENT (Datei oder Verzeichnis nicht gefunden)
newfstatat(AT_FDCWD, "/usr/lib/python3.10/site-packages/poetry/__init__.so", 0x7ffe8c892140, 0) = -1 ENOENT (Datei oder Verzeichnis nicht gefunden)
newfstatat(AT_FDCWD, "/usr/lib/python3.10/site-packages/poetry/__init__.py", {st_mode=S_IFREG|0644, st_size=77, ...}, 0) = 0
```

**Comment by SebAlbert** [comment]
I can confirm: Creating an empty file `/home/seb/.local/lib/python3.10/site-packages/poetry/__init__.py` solved the issue without any other steps.

**Comment by SebAlbert** [comment]
So I've essentially found that `poetry-core` used to be an explicit package in 1.0.8 and has become a namespace package as of 1.1.0. (see https://github.com/python-poetry/poetry-core/commit/fa93845ed48f8ba392da3628fd5718a84ebae5d6 )
Bottom line: One must be aware that Python "namespace packages" can lead to version conflicts that are not fully mitigated by just the order of the import path.
A clear explanation (easier to read than official Python docs) is on this StackOverflow answer:
https://stackoverflow.com/questions/21819649/namespace-vs-regular-package

> If either one of them gain an `__init__.py` that becomes *the* package - and you no longer get the unification as the other directory is ignored.

**Comment by neersighted** [comment]
Keep in mind that user installs are not suggested for exactly this reason -- use of a virtual environment will prevent this kind of issue. Thanks for digging in!
