### ISSUE TITLE
`-n` does not auto-accept prompts for `poetry cache clear`

### ISSUE THREAD

**Issue by novafacing** [python-poetry/poetry#6572]
- **Poetry version**: 1.2.1
- **Python version**: 3.8
- **OS version and name**: Fedora Linux Rawhide
- **pyproject.toml**: Not relevant for this issue.

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

Pretty simple issue, the `--no-interaction` flag does not actually ensure no interaction for
`poetry cache clear --all PyPI` for example, it just fails because it didn't get the `yes`
response to the prompt.

What I'd like to see is either:
- `-n` implicitly respond `yes` to this prompt or
- `-y` option added to explicitly respond `yes` to this prompt

I don't have time to add it myself right this second, but I may get to it myself if this is a feature others agree with.

**Comment by dimbleby** [comment]
duplicate #6291
