### ISSUE TITLE
On install, poetry removes setuptools + pip even if listed in deps - resulting in broken virtualenv

### ISSUE THREAD

**Issue by philippefutureboy** [python-poetry/poetry#6575]
- **Poetry version**: 1.1.12
- **Python version**: 3.8.7 
- **OS version and name**: MacOS Monterey 12.5.1 
- **pyproject.toml+poetry.lock+log**: https://gist.github.com/philippefutureboy/97443a5c95e33e12158650d196c853db 

- [ ] ~I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.~ I could not update poetry using `poetry self update`, due to error `Could not find poetry-1.2.1-darwin.sha256sum file`
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
  - This _may_ be related to #6567.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.
  - See gist > poetry_install.log

## Issue

When attempting to run `poetry install` (on either a pre-existing env or on a new one after nuking with `poetry env remove {name}`):

1. poetry starts by removing pip and setuptools (which are both specified in pyproject.toml: pip@>=21 as dep, setuptools@^56.2.0 as dev-dep)
2. poetry then proceeds to install the dependencies
3. Due to (1), the dependency `future` fails to install and the virtual environment becomes broken.

The issue is on a dependabot branch for bumping google-cloud-bigquery from 2.33.0 to 2.34.4, but the issue is also reproducible on our base branch without the dependabot bump - but instead it's jupyter-core that fails for the same reason (missing setuptools).

Is there anything I can do to have a non-broken virtualenv? Should I pin the version of pip?

**Comment by neersighted** [comment]
Duplicate #4242 (also see the update to the blog @ https://github.com/python-poetry/website/pull/79).

**Comment by philippefutureboy** [comment]
Noice. Thanks @neersighted!
( tfw the answer is 4242 :) )
