### ISSUE TITLE
bash_completion issue: solved

### ISSUE THREAD

**Issue by consultit** [python-poetry/poetry#6577]
- **Poetry version**: Poetry (version 1.2.1)
- **Python version**: Python:  3.10.4
- **OS version and name**: Ubuntu 22.04
- **pyproject.toml**: https://gist.github.com/consultit/3fa3efe50ff1a63d389b578ed5066f2c

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
I've installed poetry:
```
curl -sSL https://install.python-poetry.org | python3 -
```
Then I've enabled `bash` completion:
```
poetry completions bash >> ~/.bash_completion
```
But there were several issues when starting `bash` session:
```
...
bash: /home/ubuntu/.bash_completion: line 168: syntax error near unexpected token `show'
bash: /home/ubuntu/.bash_completion: line 168: `            (source show)'
...
```
Then I've quoted multi-word items inside `case` statement,  e.g.:
```
...
            ("source show")
            opts="${opts} "
            ;;
...
```
and the problem was solved.

**Comment by neersighted** [comment]
Duplicate #6543, #6523, #6486, #6465, #6446, #6384, #4572, python-poetry/cleo#133,

**Comment by welrbraga** [comment]
Same here, but solved with @consultit tip. Really thanks, guy.

OS version:
`
cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
[...]
`

Bash version:
` echo $BASH_VERSION
5.1.16(1)-release
`

Default Python Version
`
python --version
Python 3.10.6
`

Python 3 Version
`
python3 --version
Python 3.10.6
`

Poetry Version
`
poetry --version
Poetry (version 1.2.2)
`

Poetry completions install
`
poetry completions >/home/wbraga/.bash_completion
`

Poetry completions loading
`
. /home/wbraga/.bash_completion
bash: /home/wbraga/.bash_completion: linha 40: erro de sintaxe próximo ao token inesperado `clear'
bash: /home/wbraga/.bash_completion: linha 40: `            (cache clear)'
`

Like @consultit said, but all mutiword option in quotes, solved (maybe temporary, I don't know). The options was found with this regex in a grep command line:
`
grep -E ' \(([a-z]* [a-z]*)( [a-z]*)?\)' ~/.bash_completion
            (cache clear)
            (cache list)
            (debug info)
            (debug resolve)
            (env info)
            (env list)
            (env remove)
            (env use)
            (self add)
            (self install)
            (self lock)
            (self remove)
            (self show)
            (self show plugins)
            (self update)
            (source add)
            (source remove)
            (source show)
`

And a temporary solution for me was parse the poetry output (or the .bash_completion file) in a sed command and quoting all multiword options, like that:

`
sed -i.bk -E  's@ \(([a-z]* [a-z]*)( [a-z]*)?\)@ ("\1\2")@g' ~/.bash_completion
`

Of course, I could simply edit my .bash_completion manually.
