### ISSUE TITLE
Issue with parsing `x.y.z*` in dependencies.

### ISSUE THREAD

**Issue by EdgyEdgemond** [python-poetry/poetry#6578]
- **Poetry version**: 1.2.1
- **Python version**: 3.7
- **OS version and name**: linux (arch, ubuntu)

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
Up until v1.2.0 the following worked
```
module = {version="^0.0.1*", allow-prereleases=true}
```

with release of 1.2.1 release
```
Could not parse version constraint: ^0.0.1*
```

**Comment by dimbleby** [comment]
indeed it's not a valid version constraint.  

previous releases treated invalid versions as `*`: so you should either use that or some other valid constraint.
