### ISSUE TITLE
Poetry can not resolve pyspark == 3.1.3 dependency 

### ISSUE THREAD

**Issue by ckusheva** [python-poetry/poetry#6581]
- **Poetry version**: 1.2.1
- **Python version**: 3.9.9
- **OS version and name**: macOS Monterey 12.1, 2020 M1 MacBook Pro
- **pyproject.toml**: https://gist.github.com/ckusheva/7f0b519bf2ae15c1c03accde6fb6d1d7

- [ x ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [ x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
Steps to reproduce 
1. Copy the pyproject.toml into a fresh directory
2. Run `poetry install -vvv`

Every time I try this, the install hangs for several minutes before I cancel it.

**Comment by neersighted** [comment]
Try clearing your cache -- e.g. `poetry cache clear --all pypi`

**Comment by ckusheva** [comment]
Thank you so much! It worked!
