### ISSUE TITLE
Poetry uses `--prefix` in pip subcommand but doesn't respect `PIP_PREFIX` environment variable.

### ISSUE THREAD

**Issue by tcjennings** [python-poetry/poetry#6585]
- **Poetry version**: 1.2.0
- **Python version**: 3.7.14
- **OS version and name**: Docker (Debian 10)
- **pyproject.toml**: NA

- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

With Poetry 1.2.0, when not in a venv, the PipInstaller environment uses the `sys.prefix` value to build a subcommand argument list that includes `--prefix` without considering that `PIP_PREFIX` may be set in the environment (or other pip configuration location). 

This also incidentally disallows the use of both the `PIP_TARGET=/path` and `PIP_USER=1` configurations, as these may not be used together with `--prefix`.

Use Case
----------
I am using poetry in a Docker multi-stage build environment where one build stage installs the project requirements to a well-known clean location (e.g., "/opt/python"). I have typically used the `PIP_TARGET` environment variable to steer the installation to this location, that can be simply copied from one build stage to the next within the Docker context.

Workaround
------------
Use `PIP_ROOT` and traverse the enclosed `./usr/bin` directory.

**Comment by neersighted** [comment]
Not a bug -- pip is an implementation detail of Poetry and not meant to be perturbed by end users. Additionally, you can steer Poetry to install to arbitrary paths by activating an environment before running Poetry commands -- that virtual environment will be used.

Poetry needs to gather facts from the target environment -- trying to go 'split brain' so that Poetry introspects one virtual environment and installs to a different prefix is not supported, and will result in unexpected behavior.

**Comment by neersighted** [comment]
Addendum: See the bundle plugin (`poetry-plugin-bundle`) which can install to arbitrary paths and create a venv there. It could also be extended to support a simple 'target' for `sys.path`, like `pip install --target` if someone was interested.

**Comment by tcjennings** [comment]
Thank you for the guidance, I will refactor away from manipulating PIP.
