### ISSUE TITLE
AWS CodeArtifact token exceed Windows Credential Manager maximum length

### ISSUE THREAD

**Issue by haoguo-wdc** [python-poetry/poetry#6597]
- **Poetry version**: 1.2.1
- **Python version**: 3.10.4
- **OS version and name**: windows 10 pro, 21H1

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
Hi team,
When I am trying to add AWS CodeArtifact as my private repo's password with the command 'poetry config http-basic.artifact aws {some_long_token}'.
And then I hit an error "(1783, 'CredWrite', 'The stub received bad data.')".  After some googling, it seems the token length hit the maximum length of Windows Credential Manager. I have tried to do workaround by setting passwords as an environment variable with the command '$env:POETRY_HTTP_BASIC_ARTIFACT_PASSWORD={some_long_token}', but this resulted in a 401 error in the 'poetry install' step.
The same operation works fine in windows WSL2. But I hope to make native windows poetry works, so my IDE can read the libraries.

Thank you for looking into this.

Debug output with 'poetry config http-basic.artifact aws {some_long_token}'
>  Stack trace:
>
>  2  ~\AppData\Roaming\pypoetry\venv\lib\site-packages\win32ctypes\pywin32\pywintypes.py:35 in pywin32error
>       33│ def pywin32error():
>       34│     try:
>    →  35│         yield
>       36│     except WindowsError as exception:
>       37│         raise error(exception.winerror, exception.function, exception.strerror)
>
>  1  ~\AppData\Roaming\pypoetry\venv\lib\site-packages\win32ctypes\pywin32\win32cred.py:37 in CredWrite
>       35│     c_pcreds = _authentication.PCREDENTIAL(c_creds)
>       36│     with _pywin32error():
>    →  37│         _authentication._CredWrite(c_pcreds, 0)
>       38│
>       39│
>
>  OSError
>
>  [WinError 1783] The stub received bad data.
>
>  at ~\AppData\Roaming\pypoetry\venv\lib\site-packages\win32ctypes\core\ctypes\_util.py:53 in check_zero
>       49│
>       50│ def check_zero_factory(function_name=None):
>       51│     def check_zero(result, function, arguments, *args):
>       52│         if result == 0:
>    →  53│             raise make_error(function, function_name)
>       54│         return result
>       55│     return check_zero
>       56│
>       57│
>
>The following error occurred when trying to handle this error:
>
>
>  Stack trace:
>
>  15  ~\AppData\Roaming\pypoetry\venv\lib\site-packages\cleo\application.py:329 in run
>       327│
>       328│             try:
>     → 329│                 exit_code = self._run(io)
>       330│             except Exception as e:
>       331│                 if not self._catch_exceptions:
>
>  14  ~\AppData\Roaming\pypoetry\venv\lib\site-packages\poetry\console\application.py:185 in _run
>       183│         self._load_plugins(io)
>       184│
>     → 185│         exit_code: int = super()._run(io)
>       186│         return exit_code
>       187│
>
>  13  ~\AppData\Roaming\pypoetry\venv\lib\site-packages\cleo\application.py:423 in _run
>       421│             io.input.set_stream(stream)
>       422│
>     → 423│         exit_code = self._run_command(command, io)
>       424│         self._running_command = None
>       425│
>
>  12  ~\AppData\Roaming\pypoetry\venv\lib\site-packages\cleo\application.py:465 in _run_command
>       463│
>       464│         if error is not None:
>     → 465│             raise error
>       466│
>       467│         return event.exit_code
>
>  11  ~\AppData\Roaming\pypoetry\venv\lib\site-packages\cleo\application.py:449 in _run_command
>       447│
>       448│             if event.command_should_run():
>     → 449│                 exit_code = command.run(io)
>       450│             else:
>       451│                 exit_code = ConsoleCommandEvent.RETURN_CODE_DISABLED
>
>  10  ~\AppData\Roaming\pypoetry\venv\lib\site-packages\cleo\commands\base_command.py:119 in run
>       117│         io.input.validate()
>       118│
>     → 119│         status_code = self.execute(io)
>       120│
>       121│         if status_code is None:
>
>   9  ~\AppData\Roaming\pypoetry\venv\lib\site-packages\cleo\commands\command.py:83 in execute
>        81│
>        82│         try:
>     →  83│             return self.handle()
>        84│         except KeyboardInterrupt:
>        85│             return 1
>
>   8  ~\AppData\Roaming\pypoetry\venv\lib\site-packages\poetry\console\commands\config.py:267 in handle
>       265│                     password = values[1]
>       266│
>     → 267│                 password_manager.set_http_password(m.group(2), username, password)
>       268│             elif m.group(1) == "pypi-token":
>       269│                 if len(values) != 1:
>
>   7  ~\AppData\Roaming\pypoetry\venv\lib\site-packages\poetry\utils\password_manager.py:219 in set_http_password
>       217│             auth["password"] = password
>       218│         else:
>     → 219│             self.keyring.set_password(name, username, password)
>       220│
>       221│         self._config.auth_config_source.add_property(f"http-basic.{name}", auth)
>
>   6  ~\AppData\Roaming\pypoetry\venv\lib\site-packages\poetry\utils\password_manager.py:85 in set_password
>        83│
>        84│         try:
>     →  85│             keyring.set_password(name, username, password)
>        86│         except (RuntimeError, keyring.errors.KeyringError) as e:
>        87│             raise PoetryKeyringError(
>
>   5  ~\AppData\Roaming\pypoetry\venv\lib\site-packages\keyring\core.py:60 in set_password
>        58│ def set_password(service_name: str, username: str, password: str) -> None:
>        59│     """Set password for the user in the specified service."""
>     →  60│     get_keyring().set_password(service_name, username, password)
>        61│
>        62│
>
>   4  ~\AppData\Roaming\pypoetry\venv\lib\site-packages\keyring\backends\Windows.py:128 in set_password
>       126│                 existing_pw.value,
>       127│             )
>     → 128│         self._set_password(service, username, str(password))
>       129│
>       130│     def _set_password(self, target, username, password):
>
>   3  ~\AppData\Roaming\pypoetry\venv\lib\site-packages\keyring\backends\Windows.py:139 in _set_password
>       137│             Persist=self.persist,
>       138│         )
>     → 139│         win32cred.CredWrite(credential, 0)
>       140│
>       141│     def delete_password(self, service, username):
>
>   2  ~\AppData\Roaming\pypoetry\venv\lib\site-packages\win32ctypes\pywin32\win32cred.py:36 in CredWrite
>        34│     c_creds = _authentication.CREDENTIAL.fromdict(Credential, Flags)
>        35│     c_pcreds = _authentication.PCREDENTIAL(c_creds)
>     →  36│     with _pywin32error():
>        37│         _authentication._CredWrite(c_pcreds, 0)
>        38│
>
>   1  ~\AppData\Local\Programs\Python\Python310\lib\contextlib.py:153 in __exit__
>       151│                 value = typ()
>       152│             try:
>     → 153│                 self.gen.throw(typ, value, traceback)
>       154│             except StopIteration as exc:
>       155│                 # Suppress StopIteration *unless* it's the same exception that
>
>  error
>
>  (1783, 'CredWrite', 'The stub received bad data.')
>
>  at ~\AppData\Roaming\pypoetry\venv\lib\site-packages\win32ctypes\pywin32\pywintypes.py:37 in pywin32error
>       33│ def pywin32error():
>       34│     try:
>       35│         yield
>       36│     except WindowsError as exception:
>    →  37│         raise error(exception.winerror, exception.function, exception.strerror)
>       38│

**Comment by neersighted** [comment]
External to Poetry, tracked upstream as https://github.com/jaraco/keyring/issues/355 and https://github.com/jaraco/keyring/issues/540

**Comment by haoguo-wdc** [comment]
@neersighted  thank you for the quick reply!
Is there any Poetry workaround that you know? I was trying to use the env variables instead like setting 'env:POETRY_HTTP_BASIC_ARTIFACT_PASSWORD'. but it doesn't work, straight 401 error with "poetry install"

**Comment by neersighted** [comment]
I would check how you're setting the env variable and make sure it's actually set in your Powershell script -- I seem to recall that there are multiple methods in Powershell, and some are not propagated to child processes.

**Comment by neersighted** [comment]
Also a user is working on a credential helper that uses AWS SSO -- see https://github.com/returntocorp/poetry-codeartifact-plugin.

**Comment by haoguo-wdc** [comment]
@neersighted thank you for the info, I will look into it.

**Comment by gelodefaultbrain** [comment]
How did you guys solve the issue?

Got an error 

```
  OSError

  [WinError 1783] The stub received bad data.

  at ~\.pyenv\pyenv-win\versions\3.11.2\Lib\site-packages\win32ctypes\core\ctypes\_util.py:53 in check_zero
       49│
       50│ def check_zero_factory(function_name=None):
       51│     def check_zero(result, function, arguments, *args):
       52│         if result == 0:
    →  53│             raise make_error(function, function_name)
       54│         return result
       55│     return check_zero
       56│
       57│

The following error occurred when trying to handle this error:


  error

  (1783, 'CredWrite', 'The stub received bad data.')

  at ~\.pyenv\pyenv-win\versions\3.11.2\Lib\site-packages\win32ctypes\pywin32\pywintypes.py:37 in pywin32error
       33│ def pywin32error():
       34│     try:
       35│         yield
       36│     except WindowsError as exception:
    →  37│         raise error(exception.winerror, exception.function, exception.strerror)
       38│


  OSError

  [WinError 1783] The stub received bad data.

  at ~\.pyenv\pyenv-win\versions\3.11.2\Lib\site-packages\win32ctypes\core\ctypes\_util.py:53 in check_zero
       49│
       50│ def check_zero_factory(function_name=None):
       51│     def check_zero(result, function, arguments, *args):
       52│         if result == 0:
    →  53│             raise make_error(function, function_name)
       54│         return result
       55│     return check_zero
       56│
       57│

The following error occurred when trying to handle this error:


  error

  (1783, 'CredWrite', 'The stub received bad data.')

  at ~\.pyenv\pyenv-win\versions\3.11.2\Lib\site-packages\win32ctypes\pywin32\pywintypes.py:37 in pywin32error
       33│ def pywin32error():
       34│     try:
       35│         yield
       36│     except WindowsError as exception:
    →  37│         raise error(exception.winerror, exception.function, exception.strerror)
       38│
```

**Comment by radoering** [comment]
@jonapich suggests that `poetry config keyring.enabled false` solves the issue. See #9791 for details.
