### ISSUE TITLE
Path dependency files not installed when listed in `.gitignore`

### ISSUE THREAD

**Issue by vwxyzjn** [python-poetry/poetry#6624]
- **Poetry version**: Poetry (version 1.2.1)
- **Python version**: 
```
Poetry
Version: 1.2.1
Python:  3.9.5

Virtualenv
Python:         3.9.5
Implementation: CPython
Path:           /home/costa/.cache/pypoetry/virtualenvs/poetry12bug-cjZNteOe-py3.9
Executable:     /home/costa/.cache/pypoetry/virtualenvs/poetry12bug-cjZNteOe-py3.9/bin/python
Valid:          True

System
Platform:   linux
OS:         posix
Python:     3.9.5
Path:       /home/costa/.pyenv/versions/3.9.5
Executable: /home/costa/.pyenv/versions/3.9.5/bin/python3.9
```
- **OS version and name**: 
```
             /////////////                costa@pop-os 
         /////////////////////            ------------ 
      ///////*767////////////////         OS: Pop!_OS 21.10 x86_64 
    //////7676767676*//////////////       Kernel: 5.17.5-76051705-generic 
   /////76767//7676767//////////////      Uptime: 45 days, 9 hours, 57 mins 
  /////767676///*76767///////////////     Packages: 3025 (dpkg), 6 (flatpak), 2 (snap) 
 ///////767676///76767.///7676*///////    Shell: zsh 5.8 
/////////767676//76767///767676////////   Terminal: node 
//////////76767676767////76767/////////   CPU: AMD Ryzen 9 3900X (24) @ 3.800GHz 
///////////76767676//////7676//////////   GPU: NVIDIA GeForce RTX 3060 Ti 
////////////,7676,///////767///////////   GPU: NVIDIA GeForce RTX 3060 Ti 
/////////////*7676///////76////////////   Memory: 7434MiB / 64237MiB 
///////////////7676////////////////////
 ///////////////7676///767////////////                            
  //////////////////////'////////////                             
   //////.7676767676767676767,//////
    /////767676767676767676767/////
      ///////////////////////////
         /////////////////////
             /////////////
```
- **pyproject.toml**: https://github.com/vwxyzjn/poetry12bug/blob/master/pyproject.toml

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

When installing a sub-project via relative path, the sub-project is not importable when the its path is in the `.gitignore`.  See a demo below and a minimal reproduction [here](https://github.com/vwxyzjn/poetry12bug/blob/master/pyproject.toml).

[![asciicast](https://asciinema.org/a/523710.svg)](https://asciinema.org/a/523710)

**Comment by neersighted** [comment]
I suspect this is an artifact of our `.gitignore` support excluding files from builds. It's somewhat surprising to me that these two parts of the code base interact, but I don't think it's necessarily wrong -- it looks like Poetry is just ignoring files earlier than the build step without documenting that behavior explicitly.

We honestly could go either way on this -- it could just be a docs fix to codify this behavior. Could you please explain why it might be desirable to install Python code from a path you have explicitly excluded from your repo? Typically relative parent paths are used, and they're generally preferable for this as it makes it clear they're not under the aegis of source control/missing files from a local clone.

**Comment by vwxyzjn** [comment]
Thanks for the prompt response. This is actually a pretty strange use case. NVIDIA's `isaacgym` is a python package that is not on PyPi (see https://github.com/NVIDIA-Omniverse/IsaacGymEnvs/issues/23) , so we have to manually download it... But we couldn't keep it in source control because of the license agreement, so we have to manually put it in the gitingore. 

Previously we were installing [via the `-E` option](https://docs.cleanrl.dev/rl-algorithms/ppo/#usage_8), which works fine.. However, lately, we are migrating to poetry 1.2 (see https://github.com/vwxyzjn/cleanrl/pull/271) and we are trying to use dependency groups, so this is where the bug happened. 

We can keep the -E option specifically for this dependency, but not sure if this is the desired behavior for groups, too.

**Comment by dimbleby** [comment]
Your attempt to include looks wrong, I think you want something like
```diff
diff --git a/test/inner_project/pyproject.toml b/test/inner_project/pyproject.toml
index 2c6411b..c586da4 100644
--- a/test/inner_project/pyproject.toml
+++ b/test/inner_project/pyproject.toml
@@ -4,10 +4,10 @@ version = "0.1.0"
 description = ""
 authors = ["Costa Huang <costa.huang@outlook.com>"]
 readme = "README.md"
-packages = [{include = "inner_project"}]
+include = ["inner_project/*"]
```

**Comment by dimbleby** [comment]
I was going to suggest that all there is to do here is maybe improve the docs, but actually https://python-poetry.org/docs/pyproject#include-and-exclude looks pretty reasonable - not sure how you decided to do something quite different?

If you think the docs can be improved then MR welcome, I don't think there's a bug though.

**Comment by neersighted** [comment]
Ah, now I understand the interaction. The inner Poetry instance is recursing up and finding itself in the `.gitignore`, and thus ignoring all files during the build. This is a duplicate and specialized variant of #5547 -- with that understood, I will close it. I would suggest using @dimbleby's fix which will work as advertised -- and if you require support/have more questions, ask that we migrate this issue to a discussion, or join us on Discord.

**Comment by vwxyzjn** [comment]
Thank you! I tried that `include = [“inner_project/**/*”]` and it worked!
