### ISSUE TITLE
Namespace Package Error - dots replaced with dashes

### ISSUE THREAD

**Issue by dholland42** [python-poetry/poetry#6631]
- **Poetry version**: 1.2.1
- **Python version**: Python 3.8.14
- **OS version and name**: Debian GNU/Linux 11 (bullseye)
- **pyproject.toml**: [repo link](https://github.com/dholland42/poetry-test)

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

Hi, first off thanks for the great software! I've been using it for some time now and it's fantastic.

I recently ran into what may be a regression of [issue #109](https://github.com/python-poetry/poetry/issues/109). My use case is _slightly_ different than the one listed there as I am attempting to create a namespace package, but the behavior is similar: I am seeing the dot (`.`) in my package name being replaced by a dash (`-`).

I have created a small example repo to illustrate the problem [here](https://github.com/dholland42/poetry-test). In that repo, I have the following project structure:

```
.
├── README.md
├── mynamespace
│   └── mypackage
│       ├── __init__.py
│       └── constants.py
├── poetry.lock
├── poetry.toml
├── pyproject.toml
└── tests
    ├── __init__.py
    └── test_mynamespace.py
```

In the `pyproject.toml` file, I have `name = "mynamespace.mypackage"` and `packages = [{ include = "mynamespace" }]`.

After running a `poetry install`, running the line `pkg_resources.get_distribution('mynamespace.mypackage').version` raises the error `pkg_resources.DistributionNotFound: The 'mynamespace.mypackage' distribution was not found and is required by the application`.

I also see this behavior if I run a `poetry build` and attempt to install the `.whl` file with `pip`:

```sh
root@b6dc891939b0:/code# pip install -q dist/mynamespace_mypackage-0.1.0-py3-none-any.whl 
root@b6dc891939b0:/code# pip show mynamespace.mypackage
Name: mynamespace-mypackage
Version: 0.1.0
...
```

I do _not_ see this issue on poetry version `1.1.13`, the repo I linked above has examples of running tests on both version `1.1.13` and `1.2.1`.

Any help is greatly appreciated! Also, if this ends up being something simple and good for a new contributor I'd be happy to take a pass at implementing a fix.

**Comment by neersighted** [comment]
Duplicate #6413 / #6198 -- we could probably use a dedicated docs/FAQ section on name canonicalization and when to use pretty vs normalized names if you are looking to make a contribution.

**Comment by dholland42** [comment]
Ah, thanks @neersighted! I'll read through these and once I understand better I'd be more than happy to contribute to the documentation.
