### ISSUE TITLE
poetry lock fails to find the latest dependency from pypi

### ISSUE THREAD

**Issue by spapanik** [python-poetry/poetry#6636]
- **Poetry version**: 1.2.1
- **Python version**: 3.10.6
- **OS version and name**: Arch Linux
- **pyproject.toml**: The only relevant line is:
```toml
mypy = "^0.981"
```

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

  Because cryptonium depends on mypy (^0.981) which doesn't match any versions, version solving failed.

  at ~/.local/pipx/venvs/poetry/lib/python3.10/site-packages/poetry/puzzle/solver.py:159 in _solve
      155│             packages = result.packages
      156│         except OverrideNeeded as e:
      157│             return self.solve_in_compatibility_mode(e.overrides, use_latest=use_latest)
      158│         except SolveFailure as e:
    → 159│             raise SolverProblemError(e)
      160│
      161│         combined_nodes = depth_first_search(PackageNode(self._package, packages))
      162│         results = dict(aggregate_package_nodes(nodes) for nodes in combined_nodes)
      163│

## Issue

This is a recurring issue, that happens when I try to update a dependency to its latest version. This time it happened with mypy.

I changed the mypy version in `pyproject.toml`, and afterwards did a `poetry lock`. This raised an error: 

```console
stephanos@sanji $ poetry lock
Updating dependencies
Resolving dependencies... (0.8s)

Because cryptonium depends on mypy (^0.981) which doesn't match any versions, version solving failed.
```

But mypy  0.981 had already been published in PyPI, and the normal caching dance (reboot, deleting ~/.cache/pypoetry, etc) doesn't work, until I manually do `pip install "mypy==0.981"`, and afterwards `poetrty lock` starts finding the version.

**Comment by finswimmer** [comment]
Hello @spapanik,

Poetry uses PyPi JSON API to gather information. The package in request is not yet available there. See https://pypi.org/pypi/mypy/json

Things like this where reported for other packages earlier as well. But unfortunately the only thing you can do for now is wait.

fin swimmer

**Comment by spapanik** [comment]
@finswimmer  I would like to re-open this issue, as this is issue is not caused by the json API. as you can see from here:

The json API has the latest version, when I curl:
```venv:(euler)$ ~/programming/personal/leet/project_euler/python git:(main) ✗
stephanos@marco $ curl https://pypi.org/pypi/mathlib/json | jq | grep '"version": '
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 17500  100 17500    0     0  64866      0 --:--:-- --:--:-- --:--:-- 66287
    "version": "0.5.0",```

But even after the curl, when I call poetry:
```venv:(euler)$ ~/programming/personal/leet/project_euler/python git:(main) ✗
stephanos@marco $ poetry install
Installing dependencies from lock file
Warning: poetry.lock is not consistent with pyproject.toml. You may be getting improper dependencies. Run `poetry lock [--no-update]` to fix it.

Because project-euler-python depends on mathlib (^0.5) which doesn't match any versions, version solving failed.```

**Comment by finswimmer** [comment]
@spapanik Cannot test it right now. But poetry is telling you that your lock file is out of sync with your pyproject.toml. Please follow the advise of this message and try again.

**Comment by spapanik** [comment]
@finswimmer  I tried it, and nothing happens, the message about inconsistency just disappears. It happens every single time I try to update something that I have had in the requirements to a version that has been updated the last day or so. I have a workaround: clearing everything in the pypoetry caches makes this go away
