### ISSUE TITLE
[Dependency specification] Anyway to filter packages by date?

### ISSUE THREAD

**Issue by HuengchI** [python-poetry/poetry#6637]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request

I'm working on an "ancient" project which was last updated in 2018, and having a tough time dealing with its dependencies.
Its poor documentation specifies some dependencies like:
```
bokeh>=0.12.15
param>=1.8.1
matplotlib
Jinja2
Markdown
...
```
When I feed these dependency strings to `poetry add`, Poetry will happily install the latest packages like:
```
bokeh==2.4.3
param==1.12.2
matplotlib==3.6.0
...
```
But sadly there's a big chance that the code refuses to execute. These packages are just so new that a lot of APIs changed or were deprecated!
Because the project was last updated in 2018, it's a very reasonable idea to filter out all newer packages. Thus I want something like:
```
bokeh>=0.12.15, <=queryLastReleaseVersion(package='bokeh', year=2018)
param>=1.8.1, <=queryLastReleaseVersion(package='param', year=2018)
matplotlib<=queryLastReleaseVersion(package='matplotlib', year=2018)
```
Actually, my problem was solved this way.
1. First manually look up the Release History for each package on PyPI.
2. Then manually constrain the versions in `pyproject.toml`.

I'm wondering if it is possible for Poetry to handle such problems automatically?

**Comment by dimbleby** [comment]
no

**Comment by neersighted** [comment]
Poetry's resolution considers versions and compatibility only, and not "external" / "human" factors like binary availability (wheels) or temporality (dates) -- I don't forsee this changing any time soon as the amount of additional work in the solver would be... painful.

That being said, if you don't need this to be part of the strict resolution process, writing a simple tool that takes a list of additional dependencies + a date and dumps out the latest release of those dependencies on PyPI at a various date is a very solvable problem -- it won't actually get you the result you want, but it will automate the steps you took and Poetry's solver can give good feedback to solve the rest once you have the ballpark.

I'm going to close this as out of scope/won't fix -- maybe another maintainer will have a different opinion and re-open it. However, I think external tooling is a much better solution for this niche problem.
