### ISSUE TITLE
Allow release candidate builds of python to be compatible with that versions requirement

### ISSUE THREAD

**Issue by StarrFox** [python-poetry/poetry#6645]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request

I believe that release candidate builds of python should be able to install packages requiring the version the release candidate is for; i.e. I should be able to install a package requiring python version 3.11 when using python version 3.11.0rc2,

This change would allow better testing of these future releases and I don't think there are any drawbacks in allowing it.

relevant discord message thread: https://discord.com/channels/487711540787675139/974839737732964402/1024603632341102634

**Comment by dimbleby** [comment]
I don't understand the use case.  Why are you writing packages that _require_ an unreleased version of python?

That is: isn't `>=3.10` good enough?

**Comment by neersighted** [comment]
Not a bug -- you need to lower your constraint ala `>=3.11rc1`. `3.11` is a higher constraint than a 3.11 pre-release.
