### ISSUE TITLE
Setup several virtualenv for each "group"

### ISSUE THREAD

**Issue by gsemet** [python-poetry/poetry#6650]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request
Today, the "dev" and "main" groups are run from the same environment. It makes sense and life easier for static analysis tools for instance, but some "main" dependencies might be installed with a different versions in the production environment than in the dev env.

For instance if my application depends on a lib A and pylint depends on it as well, it may have introduce a restriction that I do not have or do not need. So when I perform a `poetry install` and `poetry install --dev`, it may happens than the version of A differs in each environment.

This can lead to have tested your application/module in an environment that is not reproduced when your application is installed later. It is also a point into delivering the frozen "requirements.txt" aside of the env.

My wish here would be to have each dependency group work in its own virtualenv, and still allow "poetry run" to switch easily from one to another. For instance "poetry run --group "dev" pylint myapp" would use the entrypoint "pylint" exposed in the "dev" group but still execute on the main environment so that "myapp" module exists.

**Comment by neersighted** [comment]
I think there is some misunderstanding of Poetry going on here -- Poetry solves your dependencies universally, no matter the groups you install. That is why all dependencies regardless of group, or optional status (group or extra) must be mutually compatible. 

While it is possible that things will behave differently based on installed packages in extreme edge cases, your versions should always be consistent. 

Regarding multiple environments, I can see some uses for them, but I suspect that most of the team  would consider multiple environments as out of scope for the project, as you can achieve what you want by managing environments externally to Poetry, e.g.

```sh
python3 -m venv .venv-test
source .venv-test/bin/activate
poetry install --with test
```

I'm going to close this issue as it's a bit muddy on what is wanted (and the direct problem is actually something solved by Poetry's design from version 0.1) -- however, if you'd like to come up with a design proposal for how multiple environments could be implemented, feel free to open a new issue.
