### ISSUE TITLE
Documentation does not have PowerShell one-liner to activate virtual environment

### ISSUE THREAD

**Issue by avysk** [python-poetry/poetry#6653]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

There is no PowerShell one-liner specified in the documentation to activate the project's virtual environment. The following works: `& ((poetry env info --path) + "\Scripts\activate.ps1")`

**Comment by finswimmer** [comment]
What's wrong with [poetry shell](https://python-poetry.org/docs/cli/#shell)?

**Comment by avysk** [comment]
Nothing, except it does another thing, and there's bash but not PowerShell one-liner in the docs.

**Comment by venaturum** [comment]
@avysk what's the use case for it in lieu of `poetry shell`?

**Comment by avysk** [comment]
The idea of this bug was not to discuss relative merits of `poetry shell` but to point out the obvious inconsistency in the documentation.

**Comment by dimbleby** [comment]
An MR would probably be welcome

**Comment by finswimmer** [comment]
Ah, now I see that you are talking about this page in the documentation https://python-poetry.org/docs/basic-usage/#activating-the-virtual-environment

As @dimbleby said: A Pull Request is welcome. The file that needs to be edited is https://github.com/python-poetry/poetry/blob/master/docs/basic-usage.md
