### ISSUE TITLE
virtualenv.in-project=true has no effect if project has an existing virtualenv

### ISSUE THREAD

**Issue by s7m4b4** [python-poetry/poetry#6666]
- **Poetry version**: 1.2.1
- **Python version**: 3.10.6
- **OS version and name**: Fedora 36
- https://gist.github.com/s7m4b4/c449b62e3767dfd6c518502a12bf9788

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
`virtualenvs.path` will always takes precedence once a project's virtualenv has been initialised under `{cache-dir}/virtualenvs`.
This means you can only convert to using `virtualenvs.in-project` if the original virtualenv directory is deleted - just setting `virtualenvs.in-project` to true is not enough.
This is likely intended, however it can be a bit misleading if you're unfamiliar with Poetry. It would be nice if something like the following output was displayed when adding packages -
`Installing package to /path/to/exmaple-project/virtualenv`
EDIT: I just realised the above is provided when using -v. Might still be nice to provide it by default though?

Steps -
1. Create a new Poetry project with `virtualenvs.in-project` unset
2. Install a package to populate the cache
3. Remove the package
4. Set `virtualenvs.in-project` to `true`
5. Install a package

**Comment by lovelyyfiaaa** [comment]
Hiiii~~~

I have reproduced this on Fedora 36 (Toolbox)!!

![Screenshot from 2022-10-02 09-15-28](https://user-images.githubusercontent.com/66000635/193435085-df71ba9d-57fa-4031-bfa3-a8b21fc46819.png)
![Screenshot from 2022-10-02 09-19-27](https://user-images.githubusercontent.com/66000635/193435087-6c9b6970-c8ea-4935-a15d-ebe3f6eab32e.png)
![Screenshot from 2022-10-02 09-19-41](https://user-images.githubusercontent.com/66000635/193435088-b3e84204-ee14-427e-ab83-cd8bf7b71c4a.png)
![Screenshot from 2022-10-02 09-20-09](https://user-images.githubusercontent.com/66000635/193435090-edf47c3a-2789-4d27-bb71-cd346321eae8.png)

On Poetry Shell, the output logs the where the virtualenv is but users might not notice them.

**Comment by lovelyyfiaaa** [comment]
I assume we need to log out a warning like this?

```Warning: The `virtualenvs.in-project` is set to true in your project, but we already have a virtual environment from before. Your configuration will be ignored for now. 

If you would like to immediately apply this setting. You can modify the available virtual environments and set which one to use. See poetry list env. You might also want to use poetry env remove.```

**Comment by clintonroy** [comment]
This feels like it's more user interface than anything else (which is not my area). In my mind, having a warning printed will just get ignored most of the time. 

Maybe it's best to fail the config change if there are any envs, with an error?

**Comment by jaeger-2601** [comment]
Hi  @python-poetry/triage, Can I work on this issue?

**Comment by Kronifer** [comment]
Would this be up for grabs?

**Comment by finswimmer** [comment]
This behavior is intended, otherwise all venv's of Poetry project in the systems needs to be recreated if one changes the config. A clarification in the [docs](https://python-poetry.org/docs/configuration/#virtualenvsin-project) about it should be sufficient.
