### ISSUE TITLE
Document environment variable equivalent for each configuration option

### ISSUE THREAD

**Issue by s7m4b4** [python-poetry/poetry#6667]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue
In the configuration doc, there is reference to using environment variables instead of executing config commands i.e.
 https://python-poetry.org/docs/configuration/#using-environment-variables

However for better ease of use (and dummies like me who are prone to make mistakes), it would be nice to have also display the env value for each configuration option, so it's easily copy pastable. 
Example -
```
virtualenvs.in-project
Type: boolean
Default: None
Environment Variable: POETRY_VIRTUALENVS_IN_PROJECT
```

**Comment by dimbleby** [comment]
go for it!  Docs merge requests usually seem to be welcome.

**Comment by alejandro-angulo** [comment]
I think this would be useful too. Here's some a version of the md file with envvar names inline with each confg's description https://github.com/alejandro-angulo/poetry/blob/master/docs/configuration.md (also submitted a PR just now).
