### ISSUE TITLE
Removal of install-poetry.py

### ISSUE THREAD

**Issue by Secrus** [python-poetry/poetry#6676]
This issue tracks the removal of `install-poetry.py` from this repository. This script is a snapshot of [`install.python-poetry.org`](https://github.com/python-poetry/install.python-poetry.org) before it was made a standalone repository. This older, duplicate version of the script has been kept for continuity, but is detrimental to the development of the project as it can confuse users and will not gain features/fixes like its standalone peer.

We intend to remove `install-poetry.py` from this repo **on or after June 1, 2023.** 

**NOTE**: the script will remain in the repository history.

**Comment by YDX-2147483647** [comment]
📆 Just a reminder, the deadline has passed.

https://github.com/python-poetry/poetry/blob/651d82db3d8d08070b452a8e2cf933aba7e52759/install-poetry.py might be the last version in this repo.

**Comment by neersighted** [comment]
It is not June yet.

**Comment by MeganBeckett** [comment]
Has this script been removed already? 

I am trying to follow the instructions on the website to remove poetry so I can update to the latest version but getting the following error when I try run `curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3 - --uninstall`

```
  File "<stdin>", line 1
    404: Not Found
             ^
SyntaxError: invalid syntax
```

I was referencing this: https://python-poetry.org/blog/announcing-poetry-1.2.0/

**Comment by neersighted** [comment]
`get-poetry.py` is not `install-poetry.py` -- see https://github.com/python-poetry/poetry/issues/6377

**Comment by ralbertazzi** [comment]
@schehata see just a few comments above: https://github.com/python-poetry/poetry/issues/6676#issuecomment-1505313875

**Comment by schehata** [comment]
> @schehata see just one comment above yours: [#6676 (comment)](https://github.com/python-poetry/poetry/issues/6676#issuecomment-1505313875)

I saw it, thats how I updated my comment with the correct url for the devs who are looking for the correct link.

**Comment by fahmieshaq** [comment]
> I am trying to uninstall using the get-poetry script but I am getting 404
> 
> ```
> curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3 - --uninstall
> ```
> 
> UPDATE:
> 
> This worked for me, incase if anyone still facing an issue:
> 
> ```
> curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/901bdf0491005f1b3db41947d0d938da6838ecb9/get-poetry.py | python - --uninstall
> ```

Worked!
