### ISSUE TITLE
The Unlicense not recognized as a license

### ISSUE THREAD

**Issue by zahlman** [python-poetry/poetry#6689]
- **Poetry version**: 1.2.1
- **Python version**: 3.8.10
- **OS version and name**: Linux Mint 20.3 Una
- **pyproject.toml**: https://gist.github.com/zahlman/a07c84135c4e9c0312ec11979ce307f6

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below. (not applicable)

## Issue
When I upload a package with the `pyproject.toml` linked above, the license is not properly identified.

Per https://spdx.org/licenses/, `Unlicense` is the identifier for [The Unlicense](https://spdx.org/licenses/Unlicense.html), which is an OSI-approved (and FSF Free/Libre) license. My understanding from the Poetry documentation is that [any SPDX identifier should work](https://python-poetry.org/docs/pyproject/#license), and that [a trove classifier should be generated](https://python-poetry.org/docs/pyproject/#classifiers) for any license that has a corresponding classifier (which this one [does](https://pypi.org/classifiers/)).

Expected: on the corresponding PyPI project page, the License should be described as an OSI approved license, and the trove classifiers should include `License :: OSI Approved :: The Unlicense (Unlicense)`.

Actual: no trove classifier is added for the license, and the meta section of the page states 

> **License:** Other/Proprietary License (Unlicense)

**Comment by neersighted** [comment]
The Unlicense was unknown when Poetry last synced the SPDX database. A re-sync of https://github.com/python-poetry/poetry-core/tree/main/src/poetry/core/spdx (there is tooling present to automate this) plus adding the classifier to `license.py` is fairly trivial and will resolve this.

**Comment by colindean** [comment]
I noted while searching for something similar that this seems to be handled in https://github.com/python-poetry/poetry-core/pull/489

**Comment by pmav99** [comment]
on 1.4.2 this seems to have been fixed

**Comment by stokito** [comment]
The Unlicense has some problems and you better to switch to some other well known license https://en.wikipedia.org/wiki/Unlicense
