### ISSUE TITLE
 poetry add pre-commit fails to resolve dependencies

### ISSUE THREAD

**Issue by JasonF-BJSS** [python-poetry/poetry#6697]
- **Poetry version**: Poetry (version 1.2.1)
- **Python version**: Python 3.10.4
- **OS version and name**: macOS 12.6 
- **pyproject.toml**: https://gist.github.com/JasonF-BJSS/d4fe8281cb7b21ba5eb8e90fd1cda13e

- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
With pyproject.toml https://gist.github.com/JasonF-BJSS/d4fe8281cb7b21ba5eb8e90fd1cda13e

running poetry add pre-commit fails to resolve dependencies

**Comment by JasonF-BJSS** [comment]
raised also with pre-commit:
https://github.com/pre-commit/pre-commit/issues/2536
as not sure where bug sits.

**Comment by Secrus** [comment]
could you clear your cache (`poetry cache clear pypi --all`) and try it again? it's not a bug with pre-commit for sure, because we are using pre-commit ourselves in Poetry and it resolves fine.

**Comment by dimbleby** [comment]
you forgot to provide any output that could help anyone to understand what is happening

**Comment by JasonF-BJSS** [comment]
ohh wait looks like filelock is the issue?: 

> poetry add filelock -vvv
Loading configuration file /Users/jason.francis/Library/Preferences/pypoetry/config.toml
Using virtualenv: /Users/jason.francis/Library/Caches/pypoetry/virtualenvs/jml-automation-scripts-deYEdmxQ-py3.10
Project environment contains an empty path in sys_path, ignoring.
[keyring.backend] Loading KWallet
[keyring.backend] Loading SecretService
[keyring.backend] Loading Windows
[keyring.backend] Loading chainer
[keyring.backend] Loading libsecret
[keyring.backend] Loading macOS
Creating new session for pypi.org
[urllib3.connectionpool] Starting new HTTPS connection (1): pypi.org:443
[urllib3.connectionpool] https://pypi.org:443 "GET /pypi/filelock/json HTTP/1.1" 304 0

**Comment by dimbleby** [comment]
do you mean that it is hanging at that point?  plausibly a stray `.lock` file in your cache, try `find ~/.cache/pypoetry/ -name '*.lock' -delete` (or whatever the macOS equivalent is)
