### ISSUE TITLE
Multiple projects using same env?

### ISSUE THREAD

**Issue by quaxsze** [python-poetry/poetry#6706]
Hello there!

Our project's architecture consists of one core python project, and one auxiliary python project. The auxiliary project plugs itself through the `entrypoints` specified in `setup.py`.
When developing on both projects is needed, we used to create a python environnement, make a `pip install -e .` in the core project's folder, switch to the auxiliary project's folder within the same python env and make a `pip install -e .` as well there.
The result is one python env with this two python projects installed in editable mode.

We are trying to migrate to Poetry. One way we tried to achieve this is by the following:
Doing one `poetry install`  in the core project's folder, enter the created env with `poetry shell`, switch to the auxiliary project's folder and run `poetry install` there within the activated env. This leads to poetry creating another env for the auxiliary project.
The result is two different python env with one project installed in each of them.

Is there another way to achieve this?

PS : We have seen there are some discussions on `poetry shell` not working as expected. We bypassed this by activating the python env with the environment's path directly.

**Comment by neersighted** [comment]
You can get the same effect by using the same workflow as before -- create a environment using your preferred method/tooling, activate it, and `poetry install` in both projects. Poetry will install them in editable mode + install their dependencies.
