### ISSUE TITLE
Failed to create the collection when try adding any dependencies

### ISSUE THREAD

**Issue by YongWookHa** [python-poetry/poetry#6719]
- **Poetry version**: Poetry (version 1.2.1)
- **Python version**:
  ```
  Poetry
  Version: 1.1.14
  Python:  3.9.5
  
  Virtualenv
  Python:         3.9.5
  Implementation: CPython
  Path:           /home/yongwook/test/.venv
  Valid:          True
  
  System
  Platform: linux
  OS:       posix
  Python:   /usr
  ```
- **OS version and name**: Ubuntu 20.04
- **pyproject.toml**:  
  ```
  [tool.poetry]
  name = "test"
  version = "0.1.0"
  description = ""
  authors = ["YongWook Ha <ywha12@gmail.com>"]
  
  [tool.poetry.dependencies]
  python = ">=3.9,<3.10"
  addict = "^2.4.0"
  
  [tool.poetry.dev-dependencies]
  pylint = "^2.14.5"
  
  [build-system]
  requires = ["poetry-core>=1.0.0"]
  build-backend = "poetry.core.masonry.api"
  ```

- [ v ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [ v ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ v ] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [ v ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

I bought a new workstation and installed clean Ubuntu 20.04 LTS.
As I always do, I cloned my dev repo and installed poetry and tried install dependencies

```bash
apt-get install python3-is-python

curl -sSL https://install.python-poetry.org | python3 -

git clone <my-repo> cd <my-repo>
poetry config virtualenvs.in-project true
poetry install

```

But I got this result.

```
Failed to create the collection: Prompt dismissed..
```

I get same result when I try `poetry add addcit`, `poetry add numpy`, `poetry add torch` or anything..

I fixed this problem with downgrading to `poetry==1.1.14`.

Is there any problem at `poetry==1.2.1`?

**Comment by neersighted** [comment]
Duplicate #1917 -- mitigations are in that issue.

**Comment by ryuujo1573** [comment]
https://github.com/python-poetry/poetry/issues/1917#issuecomment-1380429197
This solved the problem.
