### ISSUE TITLE
Non-optional dependency groups excluded from requirements in built wheels

### ISSUE THREAD

**Issue by jablonski-peter-bah** [python-poetry/poetry#6727]
- **Poetry version**: 1.2.1
- **Python version**: 3.9.13
- **OS version and name**: MacOS 12.6
- **pyproject.toml**: https://gist.github.com/jablonski-peter-bah/8a114c79aea195d3aa90be29ef54a562

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

Currently, when poetry-core builds a wheel distribution, it builds the METADATA file exclusively with the dependencies in the MAIN group.  It does not include those in non-optional dependency groups.  I would expect non-optional groups to be included as requirements.  A potential way of enabling this behavior would be to treat "build" as a group command, and only use activated groups, or to collect from all non-optional groups (not just main).  

As a user, I expect all of my non-optional dependencies to be treated as non-optional in the build phase.  With that said, I may also want to build multiple different wheels from the same project-- perhaps including `tensorflow` in my x86 build, and `tensorflow-aarch64` in my ARM64 build.  Making `poetry build` into a group command would enable this powerful (but safe) behavior.

**Comment by dimbleby** [comment]
This is working as designed, your expectations about groups are not aligned with poetry's intended behaviour.

Per https://python-poetry.org/docs/managing-dependencies#dependency-groups

> Dependency groups, other than the implicit main group, must only contain dependencies you need in your development process.

Therefore they are not included in distributions
