### ISSUE TITLE
poetry-core 1.3.1 + pypa/build 0.8.0 fails to build package contains "-" in its name

### ISSUE THREAD

**Issue by ymyzk** [python-poetry/poetry#6733]
- **Poetry version**: 
 ```
Poetry (version 1.2.1)
```
poetry==1.2.1 and poetry-core==1.3.1
- **Python version**:
 ```
Poetry
Version: 1.2.1
Python:  3.10.7

Virtualenv
Python:         3.10.7
Implementation: CPython
Path:           /home/yusuke/Downloads/poetry-bug-report/venv
Executable:     /home/yusuke/Downloads/poetry-bug-report/venv/bin/python
Valid:          True

System
Platform:   linux
OS:         posix
Python:     3.10.7
Path:       /usr
Executable: /usr/bin/python3.10
```
- **OS version and name**: Arch Linux
- **pyproject.toml**: https://github.com/ymyzk/poetry-bug-report/blob/main/pyproject.toml

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

We can run the following steps to reproduce the issue.
```shell
$ git clone git@github.com:ymyzk/poetry-bug-report.git
$ cd poetry-bug-report
$ python -m build
* Creating virtualenv isolated environment...
* Installing packages in isolated environment... (poetry-core==1.3.1)
* Getting dependencies for sdist...
* Building sdist...
ERROR Source /tmp/build-via-sdist-1cju5o9a/poetry_bug_report-0.1.0 is not a directory
```

Poetry should be using `/tmp/build-via-sdist-1cju5o9a/poetry-bug-report-0.1.0` instead.

It seems poetry-core 1.3.1 fails to build a package which has `-` in its name.

- This issue won't happening with poetry-core 1.2.0.
- This issue won't happen with `poetry build`.
- This issue won't happen if we replace `-` in the package name with `_`.

**Comment by neersighted** [comment]
PTAL @dimbleby

**Comment by dimbleby** [comment]
want to use the escaped name [here](https://github.com/python-poetry/poetry-core/blob/269f9402f37970be42e6749fbbfbd3c4eb0aa64e/src/poetry/core/masonry/builders/sdist.py#L77) presumably

**Comment by ymyzk** [comment]
Thank you @dimbleby and @neersighted for releasing a fix quickly. I also confirmed that poetry-core==1.3.2 fixed the issue here.
