### ISSUE TITLE
Unable to install pytest-testinfra using poetry

### ISSUE THREAD

**Issue by garar** [python-poetry/poetry#6735]
- **Poetry version**: 1.2.1 
- **Python version**: 3.10.6 
- **OS version and name**: Ubuntu 22.04 
- **pyproject.toml**: https://gist.github.com/garar/568fd6764ac88de3c1a9c2ce7a7c1b0b 

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

Commmand output: https://gist.github.com/garar/7ed31635eaba6fb7918e4063a01770b5

I have a clean, fresh poetry project. I'm trying to add pytest-testinfra and I get this error:

```
Invalid PEP 440 version: '1.1build1'
```

Can you help with this? Am I doing something wrong or is there a bug in poetry?

Thanks!

**Comment by neersighted** [comment]
It's actually related to your Python vendor: https://github.com/python-poetry/poetry/discussions/6623
