### ISSUE TITLE
Poetry self add command does not work with directories

### ISSUE THREAD

**Issue by wieczyk** [python-poetry/poetry#6742]
According to `poetry self add --help` it should work with directories, but it does not.

I want to split my package into many packages (let us say I am going to use monorepo approach) and wanted to develop a couple of plugins for poetry. I wanted to store those plugins inside the repository and develop them together with my other packages.
Unfortunately when I am doing `poetry self add ../mypoetryplugin` I see an error. It looks like poetry cannot resolve package. Unfortunately `-vvv` is not informative, it just prints stacktrace, but no additional information about resolution, anything I could follow and analyze to understand the issue.

- Operating system: Ubuntu 20.10
- Poetry debug output:

```
Poetry
Version: 1.2.1
Python:  3.10.6

Virtualenv
Python:         3.10.6
Implementation: CPython
Path:           NA
Executable:     NA

System
Platform:   linux
OS:         posix
Python:     3.10.6
Path:       /home/wieczyk/.pyenv/versions/3.10.6
Executable: /home/wieczyk/.pyenv/versions/3.10.6/bin/python3.10
```

Reproduction is quite simple, we can use any public poetry plugin to reproduce issue.

```
$ git clone https://github.com/tiangolo/poetry-version-plugin.git
$ poetry new myproject
$ cd myproject
$ poetry self add ../poetry-version-plugin

Could not find a matching version of package ../poetry-version-plugin/
```

**Comment by neersighted** [comment]
Duplicate #6529 -- PRs welcome :smile:

**Comment by wieczyk** [comment]
One question, I think more things is wrong or I do not understand something.

I created plugin and installed it in my system. It is visible via `pip list`. But then when I am doing `poetry self add mypluginpkg` it still throws the same error.

**Comment by neersighted** [comment]
`pip` and `poetry` are both manipulating the list of packages installed into Poetry's environment in this case. `pip install` doesn't make a plugin visible to `poetry self add`, it is a substitute/semi-equivalent command.
