### ISSUE TITLE
poetry install --only-root incorrectly requires presence of path dependencies

### ISSUE THREAD

**Issue by bplotnick** [python-poetry/poetry#6748]
- **Poetry version**: 1.2.1
- **Python version**: 3.9.5
- **OS version and name**: Ubuntu 20.04
- **pyproject.toml**: https://gist.github.com/bplotnick/7707e53f3e0eee037c92b53909115f0e

- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
Given a path dependency `../bar`, when installing using `poetry install --only-root`, poetry fails with `Directory ../bar does not exist`, even though that should be irrelevant. I am hitting this issue with multi-stage docker builds where I do `poetry install --no-root` in one stage to install the deps, and then `poetry install --only-root` in the next stage to install the app.

This is related to https://github.com/python-poetry/poetry/issues/936 (and associated issues), but I think this issue is a little bit more targeted. Feel free to close as a dupe if you disagree.

**Comment by neersighted** [comment]
Not a bug -- this is currently as designed. As Poetry locks universally all deps need to be available even if they are not installed.

Softening the validation to allow missing path deps has been discussed, but that would only allow install when a lock file exists, and would lead to inconsistency in installability as such.

A PR relaxing this and adding a useful explanation of why a lock is needed to install with missing path deps could be considered, but no one in core has had any issues with this design/expressed an interest in pushing it themselves.

**Comment by bplotnick** [comment]
I think I understand why this applies to most cases, but can you help me
understand why this applies with only-root? Given that the purpose of this
is to ignore deps?

**Comment by neersighted** [comment]
The install operation is designed and documented as creating the lock if it doesn't exist. While it may be possible to calculate metadata without generating the full lock, we'd have to redesign or bypass many layers of existing abstractions. If we allowed only-root to not have a lock, we'd likely have to do it at the same time or after the FR for --no-root with no pyproject.toml as the same large scale refactoring of of internals would be required.
