### ISSUE TITLE
Official Installer Steps Misleading

### ISSUE THREAD

**Issue by flywire** [python-poetry/poetry#6750]
## Issue

The official installer is misleading, it lists 5 steps but either step 1 _or_ step 2 should be completed (depending on the option selected), then the rest. Suggest Step 1a, 1b, 2, etc.

The current instructions imply the install is finished at step 1.

btw, not all windows users are familiar with ps. It would be clear with "_Start PowerShell and enter the following command._"

**Comment by dimbleby** [comment]
submit a merge request!

**Comment by flywire** [comment]
How do you change from step `1` to step `1a` in the following code?

```
{{< steps >}}
{{< step >}}
**Install Poetry**
...
{{< /step >}}
```

**Comment by neersighted** [comment]
`{{steps }}`/`{{ step }}` generates a `<ol><li></li></ol>` in essence. As such, look at the documentation for the `<li>` element. `<li value="">` could be used, or nested steps with `<ol type="a">`, but that would likely require some style work.

**Comment by neersighted** [comment]
Relevant code is at https://github.com/python-poetry/website/blob/main/src/css/_content.css#L288 and https://github.com/python-poetry/website/tree/main/layouts.
