### ISSUE TITLE
Poetry path dependency does not work with `pip install -e`

### ISSUE THREAD

**Issue by wieczyk** [python-poetry/poetry#6751]
I am not sure if I understand purpose of directory/path dependencies in poetry. They seems great to structurize application, but it seems they do not work with anything. (To make correct wheels I wrote my own plugin for poetry). 

Today I encountered yet another issue related to path dependencies. They disallow project to be installed in editable mode via pip.

Output from poetry debug

```
wieczyk@tortilla:/tmp/z/b$ poetry debug info

Poetry
Version: 1.2.1
Python:  3.10.6

Virtualenv
Python:         3.10.6
Implementation: CPython
Path:           /home/wieczyk/.cache/pypoetry/virtualenvs/b-JuwRG7ex-py3.10
Executable:     /home/wieczyk/.cache/pypoetry/virtualenvs/b-JuwRG7ex-py3.10/bin/python
Valid:          True

System
Platform:   linux
OS:         posix
Python:     3.10.6
Path:       /home/wieczyk/.pyenv/versions/3.10.6
Executable: /home/wieczyk/.pyenv/versions/3.10.6/bin/python3.10
```

Steps to reproduce:

```
$ poetry new a
$ poetry new b
$ cd b
$ poetry add ../a
$ pip install -e .

pip._vendor.pkg_resources.RequirementParseError: Invalid URL: ../a
```

If this is invalid usage of path dependencies, then could we extend documentation what is purpose of them? They do not work correctly with building wheel, do not work with `pip install -e`. With what they work normally?

**Comment by wieczyk** [comment]
I found workaround that is fine for me: `pip install -e . --no-deps`

**Comment by dimbleby** [comment]
unclear what you're tring to do - why are you `pip install`-ing your poetry project and not `poetry install`-ing it?  

If you want an editable path dependency, configure it that way - https://python-poetry.org/docs/dependency-specification/#path-dependencies

**Comment by wieczyk** [comment]
I am not installing dependency to project, but installing the project itself using feature named editable-install.

According to: https://github.com/python-poetry/poetry/issues/34#issuecomment-1054626460  poetry supports PEP660 editable installs.

**Comment by dimbleby** [comment]
> I am not installing dependency to project

this is not consistent with either your issue title or the repro that you give.  You are adding the path dependency `a` to the project `b`

>  but installing the project itself using feature named editable-install.

The question I asked was: why?  Just `poetry install` instead?

**Comment by wieczyk** [comment]
I have feeling you are trying to enforce some workflow you have in your head instead of focusing on bug.
I am not interested in installing package itself in venv used by poetry to build package. I am interested in installing the package I am developing in my environment using PEP660 editable install. Thus `pip install -e .`, not `poetry install`. 

The description is consistent, package `b` has path dependency and cannot be installed.

**Comment by dimbleby** [comment]
I am trying to solve whatever problem it is that you have.  If you want an editable install of your poetry project, the expected way to do that is `poetry install`.  So the suggestion is that you do that.

If `poetry install` doesn't work, then that's likely to attract attention and be something that maintainers will want to address.

If `poetry install` does work, then I doubt you will find much interest in "make `pip install -e .` work when there's a path dependency"

**Comment by dimbleby** [comment]
Anyway, duplicate #5273

**Comment by wieczyk** [comment]
I will not repeat myself that `poetry install` is not equivalent. 

Closing ticket since you have found duplicate.
