### ISSUE TITLE
Error upgrading poetry to 1.2.2 in arm64

### ISSUE THREAD

**Issue by sralloza** [python-poetry/poetry#6764]
- **Poetry version**: 1.1.13
- **Python version**: 3.10.6
- **OS version and name**: macOS 12.4
- **pyproject.toml**: N/A

- [ ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

Trying to upgrade poetry fails:

```shell
$ poetry self update
Updating to 1.2.2

  RuntimeError

  Could not find poetry-1.2.2-darwin.sha256sum file

  at ~/.poetry/lib/poetry/console/commands/self/update.py:260 in _update
      256│         try:
      257│             r = urlopen(base_url + "/{}/{}".format(version, checksum))
      258│         except HTTPError as e:
      259│             if e.code == 404:
    → 260│                 raise RuntimeError("Could not find {} file".format(checksum))
      261│
      262│             raise
      263│
      264│         checksum = r.read().decode().strip()
```

**Comment by neersighted** [comment]
Poetry 1.1.x cannot update to 1.2.x -- please follow [the instructions](https://python-poetry.org/docs/) to make the jump.

**Comment by sralloza** [comment]
Oh, thank you! Sorry for the noise, I didn't know that.
