### ISSUE TITLE
This should be long-solved by the authentication refactor and special casing of PyPI as a repo -- please open a new issue if you hit this in 2022 on 1.2.x.

### ISSUE THREAD

**Issue by drorata** [python-poetry/poetry#6772]
This should be long-solved by the authentication refactor and special casing of PyPI as a repo -- please open a new issue if you hit this in 2022 on 1.2.x.

_Originally posted by @neersighted in https://github.com/python-poetry/poetry/issues/2839#issuecomment-1239043278_

**Comment by neersighted** [comment]
Hi @drorata -- I assume this issue was created by mistake when trying to create a new issue. Closing as such.
