### ISSUE TITLE
[BUILD] pinned version not respected

### ISSUE THREAD

**Issue by showierdata9978** [python-poetry/poetry#6778]
- 1.2.1: 
- 3.8, 3.10: 
- umbuntu 22.04 
- https://github.com/MeowerBots/MeowerBot.py/blob/master/pyproject.toml (not gist as its open src)

- [ ]  I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method. at the time of building this release, yes. now, no
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.

## Issue

Originaly raised with pip 
https://github.com/pypa/pip/issues/11510

Poetry does not respect version pinning on package dependencies. 

in published meta: `Requires-Dist: cloudlink (>=0.1.7,<0.2.0)` in published pyproject.toml `cloudlink = "0.1.7"`

**Comment by finswimmer** [comment]
Hello @showierdata9978,

the `pyproject.toml` from the git repo is not the same as in the package published on pypi. Check the content of the [source distribution](https://pypi.org/project/meowerbot/#files).

The published package has `cloudlink = "^0.1.7"` in the `pyproject.toml`, which is the same as `>=0.1.7,<0.2.0`.

So please asked the maintainer to publish a new version of the package, which reflects the current version of the git repo.

fin swimmer

**Comment by neersighted** [comment]
I just cloned and built your project and ended up with:

```
Requires-Dist: cloudlink (==0.1.7)
```

Looks like @finswimmer beat me to closing, but the built artifacts are very much as expected as well.

---

Also, please be sure to follow the issue template and to provide a complete and descriptive issue body in the future -- those trying to help you shouldn't have to go to an external project's issue tracker to get the full context.
