### ISSUE TITLE
Unable to install poetry-package built with optional extras

### ISSUE THREAD

**Issue by MProx** [python-poetry/poetry#6785]
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

Poetry version: 1.2.2

I cannot seem to build and publish a package that includes an extra (optional) dependency. I used `poetry init` to create a basic package, and then followed along with the [docs](https://python-poetry.org/docs/pyproject/#extras) to include two dependencies: 

- `poetry add requests==2.28.1`
- `poetry add boto3==1.24.89 --optional`

I then edited the pyproject.toml file to add the `tools.poetry.extras` section. My final pyproject.toml file is as follows:

> [tool.poetry]
> name = "my-package-mprox"
> version = "0.1.0"
> description = ""
> authors = ["MProx <fake@nomail.com>"]
> readme = "README.md"
> packages = [{include = "my_package_mprox"}]
> 
> [tool.poetry.dependencies]
> python = "^3.9"
> requests = "^2.28.1"
> boto3 = {version = "1.24.89", optional = true}
> 
> [tool.poetry.extras]
> boto3 = ["boto3"]
> 
> [build-system]
> requires = ["poetry-core"]
> build-backend = "poetry.core.masonry.api"

I built and published this project:
`poetry publish --build -u $PYPI_USERNAME -p $PYPI_PASSWORD`

Then, in a new project, I am able to successfully install the base package with pip:
`python3 -m pip install my_package_mprox`

But I am not able to install it with the `boto3` extra group:
`python3 -m pip install my_package_mprox[boto3]` # fails

The error message: 
> zsh: no matches found: my_package_mprox[boto3]

The documentation explicitly says the following that "when installing or specifying Poetry-built packages, the extras defined in this section can be activated as described in [PEP 508](https://www.python.org/dev/peps/pep-0508/#extras).". So I think this is either a bug in poetry somewhere or (more likely) inadequate documentation explaining how it should work.

**Comment by dimbleby** [comment]
zsh is expanding `my_package_mprox[boto3]`, you'll want to stick some quotes around it so that it doesn't do that.  This is nothing to do with poetry.

**Comment by finswimmer** [comment]
@dimbleby beat me. Had to delete what I already wrote :smile:

**Comment by MProx** [comment]
Thanks! That does indeed seem to fix my issue (apologies for the silly question - new mac user).
