### ISSUE TITLE
Exit code relay fails when run command is a script

### ISSUE THREAD

**Issue by rc-mattschwager** [python-poetry/poetry#6801]
- **Poetry version**: `1.2.2`
- **Python version**: `3.10.6`
- **OS version and name**: macOS 12.5.1
- **pyproject.toml**: Relevant details below

```
[tool.poetry.scripts]
toolname = "toolname.__main__:main"
```

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

Hi there,

When using `poetry run` to run a script defined in the [`scripts`](https://python-poetry.org/docs/pyproject/#scripts) section of `pyproject.toml` the exit code of the script is not relayed as the final exit code of `poetry` itself. I originally noticed https://github.com/python-poetry/poetry/issues/5773 and https://github.com/python-poetry/poetry/issues/2369 and was wondering why it wasn't working for me.

Consider the following cases:

```
$ poetry run python -m toolname --version
0.5.0
$ echo $?
1
```

```
$ poetry run toolname --version
0.5.0
$ echo $?
0
```

It looks like https://github.com/python-poetry/poetry/pull/4456 did not fix https://github.com/python-poetry/poetry/issues/2369 because these are different execution paths. Looking at [`commands/run.py`](https://github.com/python-poetry/poetry/blob/16046d9ac9b72a49e1bc4618fb686695cc64821c/src/poetry/console/commands/run.py#L61), running a script (as defined in `pyproject.toml`) is a different execution path than running non-scripts. As mentioned in https://github.com/python-poetry/poetry/issues/2369, I believe the fix would be:

`f"import_module('{module}').{callable_}()"` -> `f"sys.exit(import_module('{module}').{callable_}())"`

I made this change locally and it fixed this issue for me.

Alternatively, I believe another fix would be removing the `RunCommand.run_script` special-case code. Since `poetry` knows where the script is (`$VIRTUALENV/bin/`), it could include this directory in the `$PATH` when executing the command. `poetry` would then execute the script generated by [`builders/editable.py`](https://github.com/python-poetry/poetry/blob/master/src/poetry/masonry/builders/editable.py#L31).

There may be reasons these two code paths are distinct that I don't understand, but if they can be unified to a single path that would ease maintenance burden and help alleviate situations like this where one path is updated but the other is forgotten.

**Comment by dimbleby** [comment]
works fine for me, can you put together a reproduction eg in a dockerfile?

```python
$ cat toolname/__main__.py
#!/usr/bin/env python3

def main():
    import sys
    print("hello")
    sys.exit(4)


if __name__ == "__main__":
    main()
```

```
$ poetry run python -m toolname
hello
$ echo $?
4
$ poetry run toolname
hello
$ echo $?
4
```

**Comment by dimbleby** [comment]
oh I see, you don't mean that the _exit_ code is not relayed, you mean that the _return_ code is not relayed, as an exit code.

(Apologies if this seems pedantic, but this is what confused me)

I expect an MR would be welcome, either of the approaches that you suggest sounds reasonable.
