### ISSUE TITLE
Poetry add does not resolve the correct package version given the project constraints

### ISSUE THREAD

**Issue by snejus** [python-poetry/poetry#6812]
- **Poetry version**: 1.2.2
- **Python version**: 3.9.13
- **OS version and name**: Arch Linux
- **pyproject.toml**: https://github.com/snejus/rich-tables/blob/main/pyproject.toml 

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

Currently, an attempt to add a dependency 
* without a version constraint and
* which does not _anymore_ support the lowest python version that the project supports

produces an error:

```
$ poetry add multimethod                                                                        
Using version ^1.9 for multimethod

Updating dependencies
Resolving dependencies... (0.0s)

The current project's Python requirement (>=3.6.3,<4) is not compatible with some of the required packages Python requirement:
  - multimethod requires Python >=3.7, so it will not be satisfied for Python >=3.6.3,<3.7

Because multimethod (1.9) requires Python >=3.7
 and no versions of multimethod match >1.9,<2.0, multimethod is forbidden.
So, because rich-tables depends on multimethod (^1.9), version solving failed.
...
```

In this case, 
* the project requires `python = ">=3.6.3,<4"`
* the dependency requires `python >= 3.7` (one of the recent releases)
* the dependency **used to** support python3.6

Given that `poetry add` documentation says

> If you do not specify a version constraint, poetry will choose a suitable one based on the available package versions.

I would expect `poetry` to check all previous dependency versions and use the one that fits my project constraints, if it exists. Instead, now it implicitly looks for a recent version: `Using version ^1.9 for multimethod`.

This can now be achieved by adding `multimethod = "*"` and running `poetry update` and I'd expect `poetry add` to match this behaviour when the dependency version is not specified.

**Comment by dimbleby** [comment]
duplicate #707, among others

**Comment by snejus** [comment]
I thought this must have been mentioned somewhere, but failed use the right search terms! Thanks
