### ISSUE TITLE
Windows installation fetches memray, which does not support windows

### ISSUE THREAD

**Issue by PhilipPartsch** [python-poetry/poetry#6818]
- **Poetry version**: 1.2.2
- **Python version**: 3.9.12
- **OS version and name**: Platform: win32 OS: nt Windows 10

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below. -- Comment: Not possible as output is too long and process fail

## Issue
I try to install poetry on Windows 10 after [this instruction](https://python-poetry.org/docs/#installing-with-the-official-installer).

```
(Invoke-WebRequest -Uri https://install.python-poetry.org -UseBasicParsing).Content | python -
```

After that I'm calling `poetry install`.
I get:
```
poetry install
Installing dependencies from lock file
Warning: poetry.lock is not consistent with pyproject.toml. You may be getting improper dependencies. Run `poetry lock [--no-update]` to fix it.

Package operations: 1 install, 0 updates, 0 removals

  • Installing memray (1.3.1): Failed
```
[memray ](https://github.com/bloomberg/memray) does not support Windows. So it shall not be included here.

Hint: I tried poetry lock [--no-update], but the output is the same.

**Comment by neersighted** [comment]
Not a bug -- if you want to exclude memray on Windows you need to do so [with a marker](https://python-poetry.org/docs/dependency-specification/#using-environment-markers). Also, be sure to re-lock as your pyproject and lockfile do not match.

**Comment by PhilipPartsch** [comment]
Sorry for the noob question and thanks for the hint.
