### ISSUE TITLE
Bash completions still broken in ≥1.2.2

### ISSUE THREAD

**Issue by denosaurtrain** [python-poetry/poetry#6835]
I tried with Poetry 1.2.2 and `master`, Debian bullseye and Ubuntu 22.04.

To reproduce the problem, run `docker build -t bug .` with the Dockerfile contents below:

```dockerfile
FROM docker.io/python:3.10-bullseye
RUN curl -sSL https://install.python-poetry.org | python3 - --git https://github.com/python-poetry/poetry.git@16046d9ac9b72a49e1bc4618fb686695cc64821c
RUN "$HOME/.local/bin/poetry" completions bash | bash
```

The error:

> bash: line 40: syntax error near unexpected token `clear'
>
> bash: line 40: `            (cache clear)'

Several duplicate issues have been reported on this over the last ~year, but none appear to be open anymore. Based on the title of [this recent issue](https://github.com/python-poetry/poetry/issues/6577), I got the impression that the issue might be "solved," but I can't find an associated PR.

**Comment by Secrus** [comment]
Fixes to completions are in [`cleo`](https://github.com/python-poetry/cleo), which is closing on 1.0 release which will contain those fixes. It took some time to get cleo in shape, because of some neglect the library got. It is now going better and Cleo 1.0 should be released soon.
