### ISSUE TITLE
with  `version * ` , poetry download all version packages . 

### ISSUE THREAD

**Issue by eromoe** [python-poetry/poetry#6838]
- **Poetry version**: Poetry (version 1.2.2)
- **Python version**: python 3.8
- **OS version and name**:  win10  
- **pyproject.toml**: 

```
[[tool.poetry.source]]
name = "tsinghua"
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true
# secondary = false


[tool.poetry.dependencies]
# Compatible Python versions
python = ">=3.6"

# Standard dependency with semver constraints
# Dependency with extras
# requests = { version = "^2.28", extras = ["security"] }
modin = { version="*", extras=["all"]}
jupyterlab= { version="*"}

```

## Issue

I just want to install latest `modin` , but `modin = { version="*", extras=["all"]}`  download all version of modin ,  see below 
![image](https://user-images.githubusercontent.com/3938751/196706441-72a4038d-870a-4c3d-ade9-cab2187be1b9.png)

after that, it started to download all versions of numpy . 
![image](https://user-images.githubusercontent.com/3938751/196707396-3e52edc4-7d3e-4b67-8552-9b5a65547cbf.png)

I think this is an issue, it should only download the lastest version

**Comment by dimbleby** [comment]
I expect poetry is searching for a version that is compatible with your constraint, most likely `python = ">=3.6"` is not supported by recent packages

poetry has no way to learn this except by downloading the packages and inspecting them

not a bug

**Comment by neersighted** [comment]
Indeed, not a bug, but expected behavior. Poetry can avoid this when directly interfacing with Warehouse thanks to the JSON API providing metadata, but 'standard' PEP 503 sources including that PyPI mirror require us to download packages to gather metadata.
