### ISSUE TITLE
Support Python 3.11

### ISSUE THREAD

**Issue by sp1thas** [python-poetry/poetry#6849]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request

Are you planning to support Python 3.11? I tried to add python `3.11-dev` github runner in my CI/CD pipelines and this error is raised. I was wondering if python 3.11 support is in your immediate plans.

**Comment by neersighted** [comment]
Poetry runs on Python 3.11 (we even test it [in CI](https://github.com/python-poetry/poetry/blob/16046d9ac9b72a49e1bc4618fb686695cc64821c/.github/workflows/main.yml#L31)), and 1.2.2+ has [knowledge of Python 3.11](https://github.com/python-poetry/poetry-core/pull/477) for the purpose of creating dists and virtual environments.

If you are having issues with Poetry on 3.11, it is likely some combination of Python 3.11 bugs or your deployment of it. I'd suggest reaching out on Discord or Discussions if you want to try to find someone to help you troubleshoot.
