### ISSUE TITLE
Support building abi3 wheels

### ISSUE THREAD

**Issue by erikjohnston** [python-poetry/poetry#6852]
When building wheels for a project that has a build script, it would be very useful to be able to tag the wheels as abi3 compatible (assuming the build script outputs abi3 compatible libs). 

We ([Synapse](https://github.com/matrix-org/synapse)) use a build script and `setuptools_rust` to allow us to use Rust code. In CI we use `cibuildwheel` to build wheels for various platforms and architectures, which can take a significant amount of time. Having to build a wheel for each cpython version unnecessarily is a significant chunk of that time.

I'm not familiar with how this is meant to work across different build systems, but as a first step it would be useful to have some way of forcing poetry to output the wheel with an `abi3` tag. I think the relevant line we decide on the tag for the wheel is [here](https://github.com/python-poetry/poetry-core/blob/3d0d3dc18d044dc08c24031971a030ba5c561d14/src/poetry/core/masonry/builders/wheel.py#L302).

**Comment by neersighted** [comment]
Duplicate #2051, unless I am mistaken; you want control over tags that are applied, which that issue should cover.

**Comment by erikjohnston** [comment]
Ah sorry, I was looking for ABI3 specifically. Thanks, that does look like exactly what we want!
