### ISSUE TITLE
poetry times out installing small github repo which pip can install in seconds

### ISSUE THREAD

**Issue by andrew-healx** [python-poetry/poetry#6853]
- **Poetry version**: 1.2.2
- **Python version**: 3.8.14
- **OS version and name**: Ubuntu 22.04
- **pyproject.toml**: 
```
[tool.poetry.dependencies]
python = ">=3.8,<3.11"
healx-chem = {git = "ssh://git@github.com/healx/healx-chem.git", branch = "main"}
```

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

```
poetry install -vvv
Using virtualenv: /home/andrew/.pyenv/versions/3.8.14/envs/kb
Installing dependencies from lock file
Finding the necessary packages for the current system
Cloning ssh://git@github.com/healx/healx-chem.git at 'main' to /home/andrew/.pyenv/versions/3.8.14/envs/kb/src/healx-chem
Killed
```

## Issue
When trying to install a private repo poetry simply times out without error. Running ` pip install git+ssh://git@github.com/healx/healx-chem.git#egg=healx_chem` installs in a couple of seconds. The full repo is only 3mb in size. I have tried installing other repos from the same organisation and they work without issue making it passed the Cloning stage.

**Comment by finswimmer** [comment]
Hey @andrew-healx,

could you please try if setting [experimental.system-git-client](https://python-poetry.org/docs/configuration/#virtualenvsprefer-active-python-experimental) to `true` solves your problem?

fin swimmer

**Comment by andrew-healx** [comment]
@finswimmer thanks, poetry is now able to complete the install process with this setting.

**Comment by finswimmer** [comment]
Thanks for your reply. So this in issue either by how we use `dulwich` or by `dulwich` itself :thinking:

**Comment by dimbleby** [comment]
> This in issue either by how we use dulwich or by dulwich itself

could be, however

> I have tried installing other repos from the same organisation and they work without issue

suggests that this is not in general broken, there's something about this repository that is different.

Consistent with both of these would be that the problem has to do with the state of the reporter's computer, which somehow interacts badly with the dulwich clone.  But I don't know what that's likely to be...

Without access to that computer it's hard to see how to progress this.  

If I were hitting this myself, I guess my next step would likely be to start scattering print statements around the code to try and pin down where things are stopping.

**Comment by andrew-healx** [comment]
@dimbleby The same issue occurred both on my local machine and on the CircleCI build. I will try and add some print statements to poetry and see what is happening.

**Comment by FranzForstmayr** [comment]
I think this is an issue about ssh authentification, because if I add `-vvv` a password query is shown. If the ssh-key is correctly loaded, there should be no password query.
As a workaround I use [experimental.system-git-client](https://python-poetry.org/docs/configuration/#virtualenvsprefer-active-python-experimental) = true.

Poetry 1.2.2 on Windows

**Comment by dimbleby** [comment]
@FranzForstmayr that's not what this issue covers - verbose output is included in the original report and there is no password query.

if you have a new problem, please open a new issue.

**Comment by dimbleby** [comment]
with no way to reproduce, this is unactionable and may as well be closed.
