### ISSUE TITLE
How to move configuration?

### ISSUE THREAD

**Issue by BeyondEvil** [python-poetry/poetry#6854]
```sh
❯ poetry
Configuration file exists at /Users/jimbrannlund/Library/Application Support/pypoetry, reusing this directory.

Consider moving configuration to /Users/jimbrannlund/Library/Preferences/pypoetry, as support for the legacy directory will be removed in an upcoming release.
Poetry (version 1.2.2)
```

```sh
❯ cp -R /Users/jimbrannlund/Library/Application\ Support/pypoetry/ /Users/jimbrannlund/Library/Preferences/pypoetry
```

```sh
❯ mv /Users/jimbrannlund/Library/Application\ Support/pypoetry /Users/jimbrannlund/Library/Application\ Support/ppp
```

```sh
❯ poetry         
zsh: command not found: poetry
```

```sh
❯ uname -a                                                                                                         
Darwin F8-4D-89-71-75-73 21.4.0 Darwin Kernel Version 21.4.0: Mon Feb 21 20:35:58 PST 2022; root:xnu-8020.101.4~2/RELEASE_ARM64_T6000 arm64
```

Originally installed via the official installer and updated via `poetry self update`.

**Comment by BeyondEvil** [comment]
To fix I had to update the symbolic link under the new directory `~/Library/Preferences/pypoetry`:

```
sh
❯ ls -la ~/Library/Preferences/pypoetry
total 16
drwxr-xr-x    6 jimbrannlund  staff   192 Oct 21 01:57 .
drwx------+ 271 jimbrannlund  staff  8672 Oct 21 02:04 ..
-rw-r--r--    1 jimbrannlund  staff     6 Oct 21 01:39 VERSION
-rw-------    1 jimbrannlund  staff   111 Oct 21 01:39 config.toml
lrwxr-xr-x    1 jimbrannlund  staff    64 Oct 21 01:57 poetry -> /Users/jimbrannlund/Library/Preferences/pypoetry/venv/bin/poetry
drwxr-xr-x    7 jimbrannlund  staff   224 Oct 21 01:39 venv
```

and under `.local/bin`:

```sh
❯ ls -la ~/.local/bin
lrwxr-xr-x   1 jimbrannlund  staff    64 Oct 21 02:00 poetry -> /Users/jimbrannlund/Library/Preferences/pypoetry/venv/bin/poetry
```

Be nice to have a function perform these steps for you. 😊

**Comment by neersighted** [comment]
Only the TOML files need to move -- Poetry broke because you moved the installation out from under it. We could introduce an automatic rename, but at the time the relocation was introduced there was an outcry against automatically moving a user's files. We might want to revisit that discussion.

**Comment by BeyondEvil** [comment]
Oh, I see, so only TOML needs to live under `Preferences`? The rest stays under `Application Support`?

**Comment by neersighted** [comment]
Correct!

**Comment by dariobig** [comment]
lots of words, but if I understand it correctly all that needs to be done is:
```
mv /Users/$USER/Library/Application\ Support/pypoetry/config.toml /Users/$USER/Library/Preferences/pypoetry
```

**Comment by jacklj** [comment]
@dariobig I think there's a typo, it should be:
```bash
mv /Users/$USER/Library/Application\ Support/pypoetry/config.toml /Users/$USER/Library/Preferences/pypoetry/config.toml
```

**Comment by lorenzwalthert** [comment]
@slhck with poetry 1.5, I also get that warning, and upon moving, changing a setting like 
```
poetry config virtualenvs.options.no-setuptools false      
```
I get the warning again. I had to delete the whole directory in `/Users/$USER/Library/Preferences/pypoetry` to make the warning go away (not sure that has unintended side effects!).

**Comment by dimbleby** [comment]
flip-flopping is inherited from the `platformdirs` project, which preferred one thing in its 1.0 release, then another thing in its 2.0 release, and then reverted to the 1.0 behaviour in its 3.0 release.

Hopefully they've settled on the right answer now and you should just be able to do whatever it is that poetry 1.5 says.

**Comment by slhck** [comment]
I see, thanks. I ended up removing the config and reinstalling poetry completely.

**Comment by ajatkj** [comment]
I just moved config.toml from ~/Users/Preferences/pypoetry to ~/Users/Library/Application Support/pypoetry and it worked.

**Comment by xshapira** [comment]
@slhck Thank you!

This worked perfectly with Poetry `1.5.0`:
```bash
mkdir -p /Users/$USER/Library/Application\ Support/pypoetry
mv /Users/$USER/Library/Preferences/pypoetry/config.toml /Users/$USER/Library/Application\ Support/pypoetry/config.toml
```

**Comment by camerondavison** [comment]
I had to do 
```
mkdir -p "${HOME}/Library/Application Support/pypoetry/"
mv "${HOME}/Library/Preferences/pypoetry/"*.toml "${HOME}/Library/Application Support/pypoetry/"
```

I think that it would be nice to either prompt every once in a while or provide some command that would do the move for people. Then just say run "poetry self move-config" or something like that so that people do not have to search through github to figure out what they are supposed to do.

**Comment by githuib** [comment]
Yeah it surprises me quite a bit that I still see this message (or at least in the same format without any practical information in it) that only adds noise because it's not clear what actions actually need to be taken. I've tried to resolve it last year but none of the suggestions seemed to work and all of the complaints or suggestions were then just ignored..

But I'll read this thread carefully and hopefully there's some working solution now 🙏  Thanks everyone in this thread 🙂

**Comment by ggat** [comment]
I had to do the opposite )

`mv /Users/$USER/Library/Preferences/pypoetry/config.toml /Users/$USER/Library/Application\ Support/pypoetry`

**Comment by hughperkins** [comment]
To save anyone else having to read through this llooonnnggg thread, note that I tried @camerondavison 's approach, and that worked for me.

Before using his approach:
![Screenshot 2023-12-24 at 04 14 09](https://github.com/python-poetry/poetry/assets/123560/0df92280-351b-4e3a-8b6c-a673549fa2e2)

After using his approach:
![Screenshot 2023-12-24 at 04 14 13](https://github.com/python-poetry/poetry/assets/123560/91b3a436-402e-4f5b-a822-04d5b600a7be)

**Comment by hughperkins** [comment]
PS I agree with @camerondavison 's ideas of "I think that it would be nice to either prompt every once in a while or provide some command that would do the move for people. Then just say run "poetry self move-config" or something like that so that people do not have to search through github to figure out what they are supposed to do.". I've created an issue for this at https://github.com/python-poetry/poetry/issues/8818
