### ISSUE TITLE
poetry does not support custom keyring backend

### ISSUE THREAD

**Issue by ClementPinard** [python-poetry/poetry#6858]
- **Poetry version**: 1.2.2
- **Python version**: 3.9
- **OS version and name**: Ubuntu20

- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
Hi there

Yet another keyring related problem. Following some problems with default backend, which is `keyring.backends.SecretService.Keyring` and uses gnome-keyring, I'v been trying to use another one by setting the default keyring backend to something else.

The simplest (temporary) solution is to use `keyrings.alt.file.PlaintextKeyring` , which implies we need to install `keyrings.alt` from `pip`. We just change the config file in `~/.config/python-keyring/keyringrc.cfg` or set the environment variable `export PYTHON_KEYRING_BACKEND=keyrings.alt.file.PlaintextKeyring`. Other more general (and sustainable) solutions include encrypted files (https://pypi.org/project/keyrings.cryptfile/) or using password store (https://pypi.org/project/keyrings.passwordstore/)

Works great for the keyring installed with system pip, and poetry installed with pip, but not so good with poetry installed with https://install.python-poetry.org

```bash
poetry self update
Updating Poetry version ...


No module named 'keyrings'

```

When looking into the code install-poetry.py, it's not abnormal since I understand that this script makes a new environment from scratch without symlinks. https://github.com/python-poetry/poetry/blob/16046d9ac9b72a49e1bc4618fb686695cc64821c/install-poetry.py#L291

So if I want to use the "cleanly installed" poetry with my own keyring backend, I need to install it manually from poetry's own venv pip

```bash
~/.local/share/pypoetry/venv/bin/python -m pip install keyrings.alt
```

Works as intended after that, but not the most user friendly.

Any practical solution for this ? Maybe add a new poetry specific command to add a keyring backend from pypi ?

**Comment by finswimmer** [comment]
I guess you are looking for [poetry self add](https://python-poetry.org/docs/cli/#self-add)?

**Comment by ClementPinard** [comment]
Indeed, thanks ! There's even an example to add an alternative keyring, nice.

Sorry for the inconvenience then.
