### ISSUE TITLE
Make config file relocation instructions more explicit

### ISSUE THREAD

**Issue by ulope** [python-poetry/poetry#6864]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

After upgrading from `1.1` to `1.2` I received the following message:
```
Configuration file exists at /Users/xxx/Library/Application Support/pypoetry, reusing this directory.

Consider moving configuration to /Users/xxx/Library/Preferences/pypoetry, as support for the legacy directory will be removed in an upcoming release.
```

Similar to #6854 I (naively) assumed (based on above message) that the entire directory was configuration related and therefore moved it from `~/Library/Application Support/` to `~/Library/Preferences`.

Of course this lead to poetry no longer functioning.

If an automatic move of the config file is not in the cards, at least the warning message needs to be more explicit what file(s) actually need to be moved.

**Comment by dimbleby** [comment]
merge requests improving documentation are usually welcome!

**Comment by cpate4** [comment]
Hi @dimbleby - I gave a PR a shot to try and improve the documentation. I was interested in any feedback you may have or if there is a different direction you would prefer. Thank you for the suggestion!

**Comment by dimbleby** [comment]
looks fine to me except that I see that your pipeline is failing, maybe it will attract maintainer attention
