### ISSUE TITLE
How to install Poetry on Windows so that it becomes portable?

### ISSUE THREAD

**Issue by stefaneidelloth** [python-poetry/poetry#6875]
Hello, 

I'm not sure if this is a bug or a documentation issue. Please feel free to move the issue accordingly if its only about documentation.

**A.** If I install poetry with **pip on windows**, I am able to use poetry. 
`pip install poetry`

However, if I move my **portable python instance** to another folder, poetry cannot find python any more:

Fatal error in launcher: Unable to create process using '"**C:\python_env**\App\WinPython\python-3.10.5.amd64\python.exe"  "**D:\eis\python_env**\App\WinPython\python-3.10.5
.amd64\Scripts\poetry.exe" ': The system cannot find the file specified.

=> Poetry seems to store an absolute path to python.exe and that causes issues. 

(Other python packages, e.g. pip, work fine in portable WinPython).

**B.** In the poetry documentation the **recommend way to install poetry on windows** is to use a **PowerShell script**.

https://python-poetry.org/docs/#installation

=> How can I **modify the installation command** for Windows to tell poetry to use a **relative path** to python?

I tried following:

```
PS D:\eis\python_env> (Invoke-WebRequest -Uri https://install.python-poetry.org -UseBasicParsing).Content | POETRY_HOME=./App/WinPython/python-3.10.5.amd64/Scripts |
 py -
```

However, the position for POETRY_HOME does not seem to be correct:

```
The term 'POETRY_HOME=./App/WinPython/python-3.10.5.amd64/Scripts' is not recognized as the name of a  
cmdlet, function, script file, or operable program.
```

 And even if it would work, I don't know if poetry would use an absolute or relative path for python.

=> What is the correct installation command if my python instance is currently under

`D:\eis\python_env\App\WinPython\python-3.10.5.amd64`

and I want poetry to stay portable on Windows?

**C.** Maybe there is some sort of **poetry config file** or environment variable, where I could **modify some absolute path after installation** to be a relative path, so that poetry is portable? For example:

C:\python_env\App\WinPython\python-3.10.5.amd64\python.exe

=>

../../../../App/WinPython/python-3.10.5.amd64/python.exe

I searched inside the files of the package folder

D:\eis\python_env\App\WinPython\python-3.10.5.amd64\Lib\site-packages\poetry

for occurances of "WinPython" but could not find the right place to adapt the absolute path that is currently used.

I also tried to modify POETRY_HOME and POETRY_CONFIG_DIR but that did not help. 
=> Is there something like POETRY_PYTHON_HOME ?   (Could not find it in https://python-poetry.org/docs/configuration/ )

Or can I somehow tell poetry to use PYTHON_PATH instead of a hard coded, absolute installation path?

**Comment by stefaneidelloth** [comment]
Since poetry does not seem to be portable I'll switch back to pip as package manager.

**Comment by neersighted** [comment]
Poetry creates a standard virtual environment. There is no limitation here imposed by Poetry. I would suggest you simply create a virtual environment with `/path/to/python -m venv /path/to/poetry/venv` and `/path/to/poetry/venv/pip install poetry`.

I think you're getting stuck in the weeds on what is fundamentally simple, in any case. e.g. `curl ... | POETRY_HOME= py -` will only work on Unix, you cannot export environment variables inline in cmd/PowerShell. Set the environment variable in a step **before** running `curl | py` and things will work as you expect.

That being said, you needs are specialized, so exercising more control by performing the install manually is preferred.
