### ISSUE TITLE
Replace lockfile with fasteners or oslo.concurrency

### ISSUE THREAD

**Issue by mrk-andreev** [python-poetry/poetry#6881]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request

Poetry use `lockfile==0.12.2` that deprecated. https://pypi.org/project/lockfile/

```
Note: This package is deprecated. It is highly preferred that instead of using this code base that instead [fasteners](https://pypi.python.org/pypi/fasteners) or [oslo.concurrency](http://docs.openstack.org/developer/oslo.concurrency/) is used instead. For any questions or comments or further help needed please email [openstack-dev](http://lists.openstack.org/cgi-bin/mailman/listinfo/openstack-dev) and prefix your email subject with [oslo][pylockfile] (for a faster response).
```

I suggest to migrate to non-deprecated libraries.

**Comment by Secrus** [comment]
This is not our direct dependency, but a dependency of the `cachecontrol` library, which we use. We don't have direct influence over this. `cachecontrol` has already switched to a different library, but it was not released yet.

**Comment by bryteise** [comment]
This was true in October but now https://github.com/python-poetry/poetry/blob/master/src/poetry/utils/authenticator.py#L15 is using it directly. And it was added to the pyproject with https://github.com/python-poetry/poetry/pull/7169 which seems bad.

**Comment by mrk-andreev** [comment]
@Secrus

**Comment by Secrus** [comment]
The issue remains the same. we had to include `lockfile` as direct dependency, as we had customized our lock class. The `lockfile` will be removed when we drop `cachecontrol` or when `cachecontrol` changes their implementation (or just release new version, since the change was already made).
