### ISSUE TITLE
Error when running ``poetry install`` in a new (empty) project. 

### ISSUE THREAD

**Issue by jbzdak** [python-poetry/poetry#689]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Debian buster
- **Poetry version**: 0.12.10

## Issue

I was setting up a project, first I added some dependencies via ``poetry add`` (and I didn't add any actual code). Then I issued ``poetry install`` which resulted in stacktrace below. 

It turns out I had empty directory named like the package (in poetry.toml below package name is "test" and I had empty directory named test). It looks like it triggered a bug in ``find_packages``. When I added some code to ``test`` package bug went away. 

## Error stacktrace

	[IndexError]  
	list index out of range    
		                     
	Exception trace:
	 /opt/venvs/poetry-0.12.10/lib/python3.7/site-packages/cleo/application.py in run() at line 94
	   status_code = self.do_run(input_, output_)
	 /opt/venvs/poetry-0.12.10/lib/python3.7/site-packages/poetry/console/application.py in do_run() at line 88
	   return super(Application, self).do_run(i, o)
	 /opt/venvs/poetry-0.12.10/lib/python3.7/site-packages/cleo/application.py in do_run() at line 197
	   status_code = command.run(input_, output_)
	 /opt/venvs/poetry-0.12.10/lib/python3.7/site-packages/poetry/console/commands/command.py in run() at line 77
	   return super(BaseCommand, self).run(i, o)
	 /opt/venvs/poetry-0.12.10/lib/python3.7/site-packages/cleo/commands/base_command.py in run() at line 146
	   status_code = self.execute(input_, output_)
	 /opt/venvs/poetry-0.12.10/lib/python3.7/site-packages/cleo/commands/command.py in execute() at line 107
	   return self.handle()
	 /opt/venvs/poetry-0.12.10/lib/python3.7/site-packages/poetry/console/commands/install.py in handle() at line 86
	   f.write(decode(builder.build_setup()))
	 /opt/venvs/poetry-0.12.10/lib/python3.7/site-packages/poetry/masonry/builders/sdist.py in build_setup() at line 125
	   pkg_dir, _packages, _package_data = self.find_packages(include)
	 /opt/venvs/poetry-0.12.10/lib/python3.7/site-packages/poetry/masonry/builders/sdist.py in find_packages() at line 237
	   base = str(include.elements[0].parent)

## poetry.toml
	[tool.poetry]
	name = "test"
	version = "0.1.0"
	description = ""
	authors = ["Jacek Bzdak <jbzdak@gmail.com>"]

	[tool.poetry.dependencies]
	python = "^3.7"
	six = "^1.11"

	[tool.poetry.dev-dependencies]

	[build-system]
	requires = ["poetry>=0.12"]
	build-backend = "poetry.masonry.api"

**Comment by seansfkelley** [comment]
A use-case for running install in an otherwise empty project is to improve caching behavior of Docker builds: I copy `pyproject.toml` and `poetry.lock`, then install, then copy in all the project source. I had to add an extra step to drop an empty file so Poetry wouldn't explode when I did this:

```dockerfile
RUN touch /path/to/project/.empty
```

**Comment by seansfkelley** [comment]
This is still an issue, I believe, and is stale waiting on the maintainers.

**Comment by sdispater** [comment]
Please, can you test with the latest beta version of Poetry?

**Comment by finswimmer** [comment]
In the current release, poetry ends up with

```
[ValueError]
test is not a package.
```

As all dependencies are installed before, the venv is sane. I wonder if we should just print out a warning instead of raising an exception?

fin swimmer

**Comment by Arkelis** [comment]
It seems that this error occurs when Poetry tries to install the current project's package; a workaround is to specify `--no-root` when installing the depedencies if the project-named directory is empty. We could raise `ModuleOrPackageNotFound` instead of `ValueError` as the former is handled by the `install` command.

**Comment by Goldziher** [comment]
issue occurs when --no-root is specified. 

My use case: I have a monorepo with multiple packages. At the root level there is a pyproject.toml that has all shared and dev dependencies. Now, all other sub-applications also have pyproject.toml files, but some have no dependencies because they only use the shared dependencies. For example, all fastapi apps use the same dependencies, while the ML apps also have ML dependencies. 

Thus, i have a generic docker file, which calls poetry install for each package - but for those that have no dependencies, it fails.

**Comment by John15321** [comment]
Hi
@jbzdak 
@Goldziher 
Is this still an issue?
I am on `poetry` `1.1.13` and I cannot replicate that error:

![image](https://user-images.githubusercontent.com/56229312/173410595-02f8249c-8e89-4d7d-97c0-b07fa2f8a736.png)

Am I doing something else here than you guys did?

**Comment by neersighted** [comment]
This does not reproduce, and the ask to better support non-package/container-first use-cases is tracked in #1132
