### ISSUE TITLE
Installation With Windows Package Manager Chocolatey

### ISSUE THREAD

**Issue by jm185587** [python-poetry/poetry#6890]
## Feature Request

Chocolatey is a great Windows package manager that allows easy installation and upgrading of many applications. I think it would be awesome to be able to install Poetry through it.

https://community.chocolatey.org/courses/creating-chocolatey-packages

It would also help us with our scripted environments. Thanks.

**Comment by Secrus** [comment]
The Poetry team decided against providing distro/package manager-specific installers. For the foreseeable future, the only means of installation are the ones offered on our website.
