### ISSUE TITLE
`xattr/lib_build.h` not found mac M1 install

### ISSUE THREAD

**Issue by Chichilele** [python-poetry/poetry#6891]
- **Poetry version**: `Poetry (version 1.2.2)`
- **Python version**: `Python 3.8.14`
- **OS version and name**:`macOS 12.6`
- **pyproject.toml**: from empty https://gist.github.com/Chichilele/227e7ec636c6483ae891ba0e22bba710

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below. https://gist.github.com/Chichilele/d8a01dd80b82d6a20e122f990e35cdce

## Issue
The `xattr/lib_build.h` file doesn't exist. Could there be a problem with the dependencies? 
The same problem with the following libraries:
- flask
- numy
- onnx

but works with:

- loguru 
- urllib3

So it clearly seems to be related to packages that require a build/compilation.

**Comment by dimbleby** [comment]
looks like it's a problem simply with `import xattr`.  

If you create a new virtual environment, `pip install xattr` and `python -c "import xattr"` (ie without using poetry at all) how does that go?

Perhaps we are learning that `xattr` has some system dependency that some users don't have.  

If so, suggest that submitting  a pull request putting a try-except near to https://github.com/python-poetry/poetry/blob/1ec8be3d3a6abbc434f022f812d9882ecb3a3828/src/poetry/utils/env.py#L1104-L1110 would be the way to go.

**Comment by Chichilele** [comment]
`xattr` doesn't seem to install the `lib_build.h` file it requires. I've opened an [issue there](https://github.com/xattr/xattr/issues/108) 
```python
$ python -c "import xattr"
Traceback (most recent call last):
  File "/Users/gauthiercastro/.pyenv/versions/3.8.13/lib/python3.8/site-packages/xattr/lib.py", line 7, in <module>
    from ._lib import lib, ffi
ImportError: dlopen(/Users/gauthiercastro/.pyenv/versions/3.8.13/lib/python3.8/site-packages/_cffi_backend.cpython-38-darwin.so, 0x0002): Library not loaded: '@rpath/libffi.8.dylib'
  Referenced from: '/Users/gauthiercastro/.pyenv/versions/3.8.13/lib/python3.8/site-packages/_cffi_backend.cpython-38-darwin.so'
  Reason: tried: '/Users/gauthiercastro/miniconda3/envs/speccheck_eval/lib/libffi.8.dylib' (no such file), '/Users/gauthiercastro/miniconda3/envs/speccheck_eval/lib/libffi.8.dylib' (no such file), '/Users/gauthiercastro/miniconda3/envs/speccheck_eval/lib/libffi.8.dylib' (no such file), '/Users/gauthiercastro/miniconda3/envs/speccheck_eval/lib/libffi.8.dylib' (no such file), '/opt/homebrew/lib/libffi.8.dylib' (no such file), '/opt/homebrew/lib/libffi.8.dylib' (no such file), '/opt/homebrew/lib/libffi.8.dylib' (no such file), '/opt/homebrew/lib/libffi.8.dylib' (no such file), '/opt/homebrew/lib/libffi.8.dylib' (no such file), '/opt/homebrew/lib/libffi.8.dylib' (no such file), '/usr/local/lib/libffi.8.dylib' (no such file), '/usr/lib/libffi.8.dylib' (no such file)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/gauthiercastro/.pyenv/versions/3.8.13/lib/python3.8/site-packages/xattr/__init__.py", line 13, in <module>
    from .lib import (XATTR_NOFOLLOW, XATTR_CREATE, XATTR_REPLACE,
  File "/Users/gauthiercastro/.pyenv/versions/3.8.13/lib/python3.8/site-packages/xattr/lib.py", line 9, in <module>
    from .lib_build import ffi, c_source
  File "/Users/gauthiercastro/.pyenv/versions/3.8.13/lib/python3.8/site-packages/xattr/lib_build.py", line 7, in <module>
    with open(os.path.join(PATH, 'lib_build.h')) as hf:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/gauthiercastro/.pyenv/versions/3.8.13/lib/python3.8/site-packages/xattr/lib_build.h'
```

**Comment by Chichilele** [comment]
I have uninstalled/re-installed both `pyenv` and `poetry`. Everything and got it to work. Not quite sure what is the issue... My new environments don't seem to have xattr at all. 🤷

**Comment by dimbleby** [comment]
I see that xattr say that it's a problem with your environment, and that would seem to be consistent with "well it works now".  

Anyway it seems you got far enough to prove that if this was anyone's problem it was an xattr problem and not a poetry problem: so I guess this should be closed out.

**Comment by MBARIMike** [comment]
I did the following on my Intel Mac which seems to get around this problem:
```
pip uninstall xattr
pip install xattr
```

**Comment by rec** [comment]
I encountered the same issue on an M1 Mac with a fairly recently installation of Poetry.

Reinstalling `xattr` within the poetry venv did not fix it (it doesn't seem to install that header file at all, in fact).

Uninstalling and reinstalling poetry (as per https://python-poetry.org/docs/) got everything working.

Thanks for your hard work on this excellent package!

**Comment by tduque-beon** [comment]
I've just rerun the code to install poetry and it fixed.

From official docs:

`curl -sSL https://install.python-poetry.org | python3 -`

**Comment by phdowling** [comment]
I am using python 3.12 on an M2 MBA (Sonoma) and still regularly getting this issue. I tried lots of things to no avail, including:
- using brew installed python3.12, uninstall poetry then reinstall using the same command as @tduque-beon 
- removing brew python, installing via pyenv, reinstalling poetry with that command
- install poetry via pip

Steps to reproduce:
- nuke everything, then:
- `brew install pyenv` and set up PATH, shims, etc. as per official instructions
- `pyenv install 3.12`
- `pyenv global 3.12`
- `curl -sSL https://install.python-poetry.org | python3 -`
- `mkdir my_project && cd my_project`
- `poetry init` and specify e.g. `onnx` as a depencency
- `poetry install` -> fails:
```
  FileNotFoundError

  [Errno 2] No such file or directory: '/Users/dowling/Library/Application Support/pypoetry/venv/lib/python3.12/site-packages/xattr/lib_build.h'

  at ~/Library/Application Support/pypoetry/venv/lib/python3.12/site-packages/xattr/lib_build.py:7 in <module>
        3│ from cffi import FFI
        4│ 
        5│ PATH = os.path.dirname(__file__)
        6│ 
    →   7│ with open(os.path.join(PATH, 'lib_build.h')) as hf:
        8│     c_header = hf.read()
        9│ with open(os.path.join(PATH, 'lib_build.c')) as cf:
       10│     c_source = cf.read()
       11│ 

Cannot install onnx.

```
I also tried install poetry via `pip install poetry` with the above, seems to have made no difference. My installation is not completely broken, but there are some packages where this fails. fastapi, flask, numpy actually seem to work for me, but e.g. onnx and sentencepiece break.

**Comment by samuelchrist** [comment]
I am using poetry on M1 mac os Sonoma. Tried reinstalling poetry, xattr, cffi as well as my entire python environment but python -c "import xattr" still fails:

I am using xattr 0.10.1

During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/user/Library/Caches/pypoetry/virtualenvs/venv/lib/python3.8/site-packages/xattr/__init__.py", line 13, in <module>
    from .lib import (XATTR_NOFOLLOW, XATTR_CREATE, XATTR_REPLACE,
  File "/Users/user/Library/Caches/pypoetry/virtualenvs/venv/lib/python3.8/site-packages/xattr/lib.py", line 9, in <module>
    from .lib_build import ffi, c_source
  File "/Users/user/Library/Caches/pypoetry/virtualenvs/venv/lib/python3.8/site-packages/xattr/lib_build.py", line 7, in <module>
    with open(os.path.join(PATH, 'lib_build.h')) as hf:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/user/Library/Caches/pypoetry/virtualenvs/venv/lib/python3.8/site-packages/xattr/lib_build.h'
```
Please help

To recreate this install pyenv using homebrew. Install python 3.8.17 in pyenv. Set python 3.8.17 in pyenv as global. then install poetry 1.2.0 using python 3.8.17 in pyenv. Try doing poetry add flaml==1.0.8 or python -c "import xattr"

I have raised a issue on xattr but the it was mentioned the poetry may be the issue.  Please help

**Comment by samuelchrist** [comment]
I tried reinstalling poetry, pyenv, creating new env, install poetry using pipx, poetry install using script, pip install etc

**Comment by phdowling** [comment]
xattr just got an [new release](https://github.com/xattr/xattr/releases/tag/v1.0.0) (7 hours ago as of right now), I'll try to check if that fixes things for me later, but maybe it helps someone here in the mean time.

**Comment by nholbanremedy** [comment]
Sonoma, M1
Initially I've tried to install poetry with python3.12 that in my case resulted in the error above. Installing poetry with python3.10 via pyenv solved my issue

Commands(considering pyenv installed):
```
curl -sSL https://install.python-poetry.org | python3 - --uninstall
pyenv install --skip-existing 3.10
pyenv local 3.10
curl -sSL https://install.python-poetry.org | python3 -
```
In case you want to create poetry environment with python3.10
```
poetry env use 3.10
```
In case you want to create poetry environment with python3.12
```
pyenv local 3.12
poetry env use 3.12
```

**Comment by ryan-williams** [comment]
I believe I was seeing this while switching between Python versions (e.g. 3.8 and 3.11) in a project, and re-running `poetry install`.

I needed to re-run `poetry lock` after switching Python versions, before running `poetry install`, otherwise I was e.g. in Python 3.11 trying to install dependency versions that only work in lower versions of Python.

I'm not 100% sure that's the whole story, as I believe I originally tried `poetry lock && poetry install` after switching Python versions, and it didn't fix the error, but eventually that seemed to fix the issue. It's possible I was messing something else up when I originally tried it.
