### ISSUE TITLE
Clearing cache with --no-interaction flag becomes interactive

### ISSUE THREAD

**Issue by glxplz** [python-poetry/poetry#6898]
- **Poetry version**: 1.2.2
- **Python version**: 3.8.10
- **OS version and name**: Ubuntu 20.04
- **pyproject.toml**: irrelevant

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
When clearing the cache with `poetry cache clear . --all --no-interaction` it actually becomes interactive:

`Delete 0 entries? (yes/no) [yes]`

This could be on purpose but i don't really see the point in that.

**Comment by dimbleby** [comment]
duplicate #6291
