### ISSUE TITLE
Unable to format code with yapf

### ISSUE THREAD

**Issue by wrench1815** [python-poetry/poetry#6901]
- **Poetry version**: 1.2.2
- **Python version**: 3.10.8
- **OS version and name**: Garuda Linux KDE (6.0.2-zen1-1-zen)
- **pyproject.toml**: https://gist.github.com/wrench1815/53870bec0aae3d8901df4447437a5c2c 

- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

I'm unable to format the code with `yapf` when there is a `pyproject.toml` file in the project. I usually use a `.style.yapf` file to define style and then use VS Code's 'format on save' functionality to format the code. But it's not working. Also, I tried adding yapf style config in `pyproject.toml` and it still didn't work. Manually running the `yapf -i --style .style.yapf <file.py>` gives `yapf: toml package is needed for using pyproject.toml as a configuration file
` error. And if using `pyproject.toml` to handle yapf config, I again get same error message.

Removing `pyproject.toml` makes it work normally.

```
# .style.yapf
[style]
based_on_style = pep8
```

**Comment by Secrus** [comment]
That seems like a problem with `yapf` not with Poetry. You need to install `yapf[pyproject]` if you want to use `pyproject.toml` for formatting. This is poor architecture on `yapf` side to change behavior based on the mere presence of the TOML file. 

There is also a possibility, that you don't run yapf from your environment. Use `poetry run yapf` to run the yapf installed for your project.

**Comment by wrench1815** [comment]
I see. I thought it could be something to do with poetry. I'll open an issue there.

I used `yapf[pyproject]`but it still didn't work. When in `pyproject.toml` it says `Invalid TOML file /home/wrench1815/Documents/git/vis-dash/vd-back/pyproject.toml: Unexpected character: 'p' at line 16 col 17` and with `.style.yapf` it says `yapf: toml package is needed for using pyproject.toml as a configuration file` Also yes the yapf is from env using `poetry run yapf` and yapf directly as well.

**Comment by Secrus** [comment]
Then it's 100% `yapf` issue, please raise it in their repository.
