### ISSUE TITLE
`poetry add packagename` requires keyring without any explanation

### ISSUE THREAD

**Issue by xnuk** [python-poetry/poetry#6905]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue
![](https://user-images.githubusercontent.com/3071003/198277598-536e7bee-8d7b-44bf-a3a7-79ce2205982d.png)

<details><summary>Alt text</summary>

```sh
$ cat pyproject.toml
[tool.poetry]
name = "bulb"
version = "0.1.0"
description = ""
authors = []
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
$ poetry --version
Poetry (version 1.2.2)
$ poetry add pytradfri
Creating virtualenv bulb-OqbbaJkR-py3.10 in /home/xnuk/.cache/pypoetry/virtualenvs

[ Keyring password prompt appears ]
```

</details>

I'm new to Poetry. After doing `poetry init`, I got the `pyproject.toml` above, and when adding/installing dependencies, I couldn't understand why does it want my keyrings. I just closed the prompt and Poetry said "Failed to unlock the collection!". But why? Why does it needed even if I just want to install packages not to publish?

Using:
- Arch Linux on x64
- git 2.38.1 with `commit.gpgsign` is enabled globally (disabling it doesn't solve the issue)
- Python 3.10.8
- Poetry 1.2.2, installed with `pacman -S python-poetry` <details><summary>Want more?</summary>
  - python-cachecontrol 1:0.12.11-1
  - python-cachy 0.3.0-8
  - python-cleo 1.0.0a5-2
  - python-crashtest 0.4.0-2
  - python-dulwich 0.20.46-1
  - python-html5lib 1.1-11
  - python-jsonschema 4.16.0-2
  - python-keyring 23.9.3-1
  - python-lockfile 0.12.2-11
  - python-packaging 21.3-1
  - python-pexpect 4.8.0-6
  - python-pkginfo 1.8.3-1
  - python-platformdirs 2.5.2-1
  - python-poetry 1.2.2-1
  - python-poetry-core 1.3.2-1
  - python-poetry-plugin-export 1.1.0-1
  - python-requests 2.28.1-1
  - python-requests-toolbelt 0.10.1-1
  - python-requests-unixsocket 0.3.0-1
  - python-shellingham 1.5.0-1
  - python-tomlkit 0.11.5-2
  - python-urllib3 1.26.12-1
  - python-virtualenv 20.16.6-1
  </details>

**Comment by dimbleby** [comment]
duplicate #1917, and lots of others
