### ISSUE TITLE
poetry project install on windows fails because of pywinpty

### ISSUE THREAD

**Issue by dbernstein-pallidus** [python-poetry/poetry#6908]
HI Everyone, For my project `poetry install` fails on window due to a problem with pywinpty. I believe this dependency is because of jupyter-lab but I'm not sure. It worked on one windows laptop but not on another.

The failed one is running Python 3.11.0:

Python info: Python 3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)] on win32

The error message is:

Package operations: 57 installs, 0 updates, 0 removals

 

  • Installing pywinpty (2.0.8): Failed

 

  CalledProcessError

 

  Command 'C:\Users\VictorTorres\AppData\Local\pypoetry\Cache\virtualenvs\pypallidus-rhIPZt4S-py3.11\Scripts\python.exe -m pip install --use-pep517 --disable-pip-version-check --prefix C:\Users\VictorTorres\AppData\Local\pypoetry\Cache\virtualenvs\pypallidus-rhIPZt4S-py3.11 --no-deps C:\Users\VictorTorres\AppData\Local\pypoetry\Cache\artifacts\22\14\b5\956964a9769ffe8b5b87ffc49a47814aa1b1755ee7fe881f5913494e17\pywinpty-2.0.8.tar.gz' returned non-zero exit status 1.

 

  at ~\AppData\Local\Programs\Python\Python311\Lib\subprocess.py:569 in run

       565│             # We don't call process.wait() as .__exit__ does that for us.

       566│             raise

       567│         retcode = process.poll()

       568│         if check and retcode:

    →  569│             raise CalledProcessError(retcode, process.args,

       570│                                      output=stdout, stderr=stderr)

       571│     return CompletedProcess(process.args, retcode, stdout, stderr)

       572│

       573│

 

The following error occurred when trying to handle this error:

 

 

  EnvCommandError

 

  Command C:\Users\VictorTorres\AppData\Local\pypoetry\Cache\virtualenvs\pypallidus-rhIPZt4S-py3.11\Scripts\python.exe -m pip install --use-pep517 --disable-pip-version-check --prefix C:\Users\VictorTorres\AppData\Local\pypoetry\Cache\virtualenvs\pypallidus-rhIPZt4S-py3.11 --no-deps C:\Users\VictorTorres\AppData\Local\pypoetry\Cache\artifacts\22\14\b5\956964a9769ffe8b5b87ffc49a47814aa1b1755ee7fe881f5913494e17\pywinpty-2.0.8.tar.gz errored with the following return code 1, and output:

  Processing c:\users\victortorres\appdata\local\pypoetry\cache\artifacts\22\14\b5\956964a9769ffe8b5b87ffc49a47814aa1b1755ee7fe881f5913494e17\pywinpty-2.0.8.tar.gz

    Installing build dependencies: started

    Installing build dependencies: finished with status 'done'

    Getting requirements to build wheel: started

    Getting requirements to build wheel: finished with status 'done'

    Preparing metadata (pyproject.toml): started

    Preparing metadata (pyproject.toml): finished with status 'error'

    error: subprocess-exited-with-error

 

    Preparing metadata (pyproject.toml) did not run successfully.

    exit code: 1

 

    [6 lines of output]

 

    Cargo, the Rust package manager, is not installed or is not on PATH.

    This package requires Rust and Cargo to compile extensions. Install it through

    the system's package manager or via https://rustup.rs/

**Comment by dimbleby** [comment]
presumably no binary distribution is available for python 3.11, so there's no choice but to try to compile a source distribution


Anyway this is not a poetry bug: poetry is not responsible for installing the rust compiler on your computer.

**Comment by dbernstein-pallidus** [comment]
Thank you, that makes sense. I understand it's not a bug so apologies for that.
