### ISSUE TITLE
Windows activate script: invalid escape sequence

### ISSUE THREAD

**Issue by dataspun** [python-poetry/poetry#6909]
- **Poetry version**: 1.2.2
- **Python version**: 3.9.12
- **OS version and name**: Windows 11
- **pyproject.toml**: n/a

- [ x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [ x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [ x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

Line 25 in the activate script file: `<poetry env>\Scripts\activate_this.py`

Fails to escape a path: `for lib in "..\Lib\site-packages".split(os.pathsep):`

Generating a runtime error: `invalid escape sequence \L`

**Comment by neersighted** [comment]
`activate_this.py` is not a file provided by Poetry; nor does Poetry install any scripts into an environment that are not part of your dependency tree. I'm not sure what issue you are trying to communicate, but this is not the right repository/project.

**Comment by dataspun** [comment]
@neersighted the poetry command `poetry env use /full/path/to/python` on Windows will generate a fresh environment containing Lib and Scripts folders.  Within the Scripts folder is `activate_this.py` -- is that file not provided by Poetry?

**Comment by neersighted** [comment]
It's part of virtualenv -- the source is here: https://github.com/pypa/virtualenv/blob/main/src/virtualenv/activation/python/activate_this.py

**Comment by dataspun** [comment]
Thanks, and just to confirm: 

Virtualenv is imported by Poetry [here](https://github.com/python-poetry/poetry/blob/master/src/poetry/utils/env.py) for the activation function.  But manual activation should follow [this method](https://python-poetry.org/docs/basic-usage/#activating-the-virtual-environment) which originates from a different virtualenv source here: https://github.com/pypa/virtualenv/blob/main/src/virtualenv/activation/powershell/activate.ps1 

Sound about right?

**Comment by Secrus** [comment]
> Thanks, and just to confirm: virtualenv is imported by Poetry [here](https://github.com/python-poetry/poetry/blob/master/src/poetry/utils/env.py) for the activation function. Manual activation should follow [this method](https://python-poetry.org/docs/basic-usage/#activating-the-virtual-environment) which originates from virtualenv source [here](https://github.com/pypa/virtualenv/blob/main/src/virtualenv/activation/powershell/activate.ps1).
> 
> Poetry does not appear to be using the latest virtualenv, and the old version apparently has the bug mentioned in description above. Other users could encounter this issue in using poetry so it shouldn't be labeled _invalid_.

@dataspun do you have any link to the bug report in virtualenv?
