### ISSUE TITLE
 urllib3 (1.26.12) or chardet (3.0.4) doesn't match 

### ISSUE THREAD

**Issue by Ri0nXh** [python-poetry/poetry#6918]
**python version : 3.8.10**
I use pip to install poetry , `pip install poetry`
`poetry show` will return a error
```shell
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.12) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
urllib3 1.25.11 HTTP library with thread-safe connection pooling, file post, and more.
```
then, I uninstall urllib3 and install urllib3==1.25.11, but poetry send error : 
`
poetry 1.2.0 need urllib3 >= 1.26.0
`
hope your answer

**Comment by dimbleby** [comment]
please follow poetry's installation instructions https://python-poetry.org/docs/#installation

**Comment by Ri0nXh** [comment]
Thanks your help, I have installed .

**Comment by Ri0nXh** [comment]
ok
