### ISSUE TITLE
Update requests-toolbelt dependency to allow 0.10 releases

### ISSUE THREAD

**Issue by AdamWill** [python-poetry/poetry#6922]
Sorry for wiping the template, but this isn't a functional bug so it seemed irrelevant. poetry's dependency on requests-toolbelt is listed as `^0.9.1`. Upstream has recently release 0.10.0 and 0.10.1 versions, which [don't actually look like they break any backward compatibility](https://github.com/requests/toolbelt/blob/master/HISTORY.rst) - they look like they just add new features - so this dependency can probably be relaxed; poetry likely will work fine with the new versions.

**Comment by Secrus** [comment]
Current dependency marker will allow for `0.10.0` and later without any problems.

**Comment by Secrus** [comment]
Ah, right, I rushed a bit, sorry.

**Comment by dimbleby** [comment]
@AdamWill feel free to submit a merge request!
