### ISSUE TITLE
ModuleNotFoundError: No module named 'cleo'

### ISSUE THREAD

**Issue by michealroberts** [python-poetry/poetry#6927]
- **Poetry version**: Won't let me run
- **Python version**:  Won't let me run
- **OS version and name**: 
- **pyproject.toml**: 

- [ ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

For some reason, I have tried to upgrade poetry with pipx today, and I am receiving the above error ... `ModuleNotFoundError: No module named 'cleo'`

Unfortunately, I can't debug any poetry commands, as that is the first point of failure.

The output from the verbose is as follows:

```bash
Traceback (most recent call last):
  File "/Users/michael/.poetry/bin/poetry", line 17, in <module>
    from poetry.console import main
  File "/Users/michael/.poetry/lib/poetry/console/__init__.py", line 1, in <module>
    from .application import Application
  File "/Users/michael/.poetry/lib/poetry/console/application.py", line 3, in <module>
    from cleo import Application as BaseApplication
ModuleNotFoundError: No module named 'cleo'
```

I'm lost at what to do ... 

I've tried running the uninstall commands, but still I receive this error when installing afresh ...

**Comment by neersighted** [comment]
That's not a `pipx` install of Poetry, that's an old `get-poetry.py` install. I suspect you have installed multiple times with multiple methods and have been confused by this (try `which -a poetry`). A `rm -rf ~/.poetry` and removal of `~/.poetry/bin` from your shell config should sort you out.
