### ISSUE TITLE
Run the DFS solver with something other than Python

### ISSUE THREAD

**Issue by LarsDu** [python-poetry/poetry#6931]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request
This is more of a question than a feature request

I noticed that the [solver here](https://github.com/python-poetry/poetry/blob/master/src/poetry/puzzle/solver.py#L198) is implemented as a depth-first search. At the same time the issues/faq refer the reader to the fact that each package needs to be downloaded and examined for metadata (making this IO bound more than compute bound).

I was wondering the following:

- Would implementing the DFS in a language like Rust help this speed in any significant way?
- Would moving some of the I/O to a language like Rust help the I/O in any significant way?

**Comment by dimbleby** [comment]
That particular part of the codebase is more or less irrelevant to the main solve, but I suppose the questions stand in general.

I dunno, maybe?  If you want to work on poetry performance, then you should start by profiling to decide where there are gains to be made.

I don't think anyone is likely to rewrite this code in another language any time soon.

**Comment by Secrus** [comment]
The problem here is not trivial, since writing the code might be easy, but maintaining it, in the long run, is tricky. People come and go, most contributors are Python devs, and "lower level" languages like Rust or C, are much harder to write. Not to mention the extra overhead of providing wheels for all the systems and architectures that people run Poetry on. Unless I see some significant improvements in benchmarks, I personally, would be opposed to introducing another language in the codebase

**Comment by LarsDu** [comment]
How would one go about benchmarking this within the existing codebase?

**Comment by dimbleby** [comment]
Respectfully: if you have to ask, then you're unlikely to be the one to make this happen.

Your favourite search engine is full of advice on how to profile python code, maturin is definitely an interesting project: have fun.  

But we should be realistic - we're a million miles away from actually bringing that to poetry.

**Comment by LarsDu** [comment]
@Secrus where is the main solve?

@dimbleby my main interest is not whether such an optimization could be brought to poetry or not. I am more interested in whether the primary maintainers would have any interest in absorbing such an optimization or not given the tradeoffs (additional dependencies brought on, cognitive overhead of adding a language). It would be good to ask here whether anyone has a rough idea of what percentage of dependency resolution solving is I/O bound (collecting python metadata) versus the actual solve itself.

If 10 minutes out of a 20 minute solve could be removed by switching to another language, my organization as well as certain others would probably be willing to accept that tradeoff.

**Comment by neersighted** [comment]
Most solving is not I/O bound, it is pure computation. Poetry only downloads many distfiles during the pathological case of many non-PyPI packages and lots of backtracking. That code is currently imperative and synchronous, but could easily be made parallel (if we factor out the parallel downloader) or ideally simply coroutine based if we incrementally work towards abstracting our HTTP stack so we can replace it with httpx.

In any case, introducing anything other than Python greatly reduces the portability of Poetry (e.g. we can't distribute FreeBSD wheels), increases the maintenance burden (Poetry is already relatively complex code; asking contributors to learn another language is probably a bridge too far), and doesn't solve anything we can't solve in Python itself (I/O bound tasks are typically not what one optimizes in Python now that we have good async, typically you go after CPU-bound hot loops). The hot loops in Poetry are a more likely target for such a project, but I would suspect we would choose Cython if we ever do that, and I'm not sure there's any loops that justify native code.

If we ever do introduce Cythonization, it will need to be optional as not everyone will have a working Cython implementation/C compiler or be willing to pay the build cost if wheels are unavailable for their platform. In any case, I suspect that the tradeoffs of distributing native code will be a much greater detriment than the marginal benefits that incremental refactoring/performance work can achieve over time.

**Comment by LarsDu** [comment]
Thanks @neersighted . I will close this request for now, although I would be interested if you could direct me to the specific parts of the codebase where you feel the computation could be optimized (just out of curiosity)

**Comment by LarsDu** [comment]
Maintainers expressed maintainability and portability would be negatively impacted

**Comment by micdonato** [comment]
I mean, I would like this not to happen... 
<img width="291" alt="Screen Shot 2022-11-02 at 09 58 36" src="https://user-images.githubusercontent.com/36861962/199625401-1cb1d3d2-2fb0-49f9-993f-a25c18f20616.png">

**Comment by LarsDu** [comment]
@micdonato this especially long resolution time is probably from the metadata downloads required for very broad dependency resolution

**Comment by neersighted** [comment]
That pathologically long resolution instead looks to be from a corrupted cache. This situation will improve immensely with our next minor release thanks to several contributors who have put in a good amount of effort solving it.

Please request support in appropriate channels instead of closed and unrelated issues.

**Comment by neersighted** [comment]
It's also worth noting that #5746 represents an approach to speeding up Poetry's hot loops that is harder to achieve than Cython/another language (due to the maturity of the tooling), but ultimately would be more maintainable/desirable in the long run due to it imposing no burdens on users.

**Comment by LarsDu** [comment]
@neersighted, I know this issue is closed, but I would like to express my appreciation for responding to and following up on this suggestion.

I know there are quite a few tradeoffs here with respect to dependencies that would be added, however I would suggest that if the project ever moves in the direction of using a compiled language for performance critical code, that perhaps `Rust` be considered over Cython. There are certain safety and design characteristics in Rust that make it superior to Cython for such code. Just my two cents.

Sidenote: I also noticed the pydantic has been rewriting some of its backend using `Rust` for performance: https://github.com/pydantic/pydantic-core
