### ISSUE TITLE
Poetry overwrites package dependency when adding with different extras and different platform

### ISSUE THREAD

**Issue by tbenthompson** [python-poetry/poetry#6955]
If I run:

```
poetry add "jax[cuda]" --platform linux
```

I get the attached `pyproject.toml`.

Afterwards, I run:

```
poetry add "jax[cpu]" --platform darwin
```

which causes the `jax` line in `pyproject.toml` to be overwritten with

```
jax = {extras = ["cpu"], version = "^0.3.23", platform = "darwin"}
```

deleting the linux platform-specific dependency.

I would have expected the Mac dependency to be included in addition to the existing Linux dependency.

Thanks!

Versions:
- **Poetry version**: 1.2.2
- **Python version**: 3.10.6
- **OS version and name**: Ubuntu 22.04
- **pyproject.toml**: 

```
[tool.poetry]
name = "confirm"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "~3.10"
numpy = "^1.23.4"
scipy = "^1.9.3"
typer = "^0.6.1"
jax = {extras = ["cuda"], version = "^0.3.23", platform = "linux"}
    
[tool.poetry.dev-dependencies]
jupyterlab = "^3.5.0"

[tool.poetry.group.test.dependencies]
pytest = "^7.2.0"
pre-commit = "^2.20.0"


[[tool.poetry.source]]
name = "jax"
url = "https://storage.googleapis.com/jax-releases/jax_cuda_releases.html"
default = false
secondary = false

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

```

**Comment by neersighted** [comment]
Not a bug; `poetry add` only handles simple constraints and does not manage multiple constraint versions. You should write out your platform-specific constraints by editing pyproject.toml.

**Comment by tbenthompson** [comment]
Thanks!

Just a note in case anyone finds this by searching. I was able to get I what I wanted with:
```
jax = [
    {extras = ["cpu"], version = "^0.3.23", platform = "darwin"},
    {extras = ["cuda"], version = "^0.3.23", platform = "linux"}
]
```

Without the `extra = ["cpu"]`, I wasn't getting correct results. That is to say:
```
jax = [
    {version = "^0.3.23", platform = "darwin"},
    {extras = ["cuda"], version = "^0.3.23", platform = "linux"}
]
```
did not work even though `pip install jax` normally behaves identically to `pip install jax[cpu]`. I'm assuming that's probably some issue with how JAX specifies its dependencies.
