### ISSUE TITLE
virtualenvs.create false and .venv poetry install not working

### ISSUE THREAD

**Issue by booleon** [python-poetry/poetry#696]
- [X] I am on the [latest](https://github.com/sdispater/poetry/rpoetry config settings.virtualenvs.in-project trueeleases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- Debian9-Strech: 
- 0.12.10: 
- Brand new pyproject after poetry new
## Issue
Hello, I develop a new project with poetry, the option : **_settings.virtualenvs.in-project true_** is activated
Then I COPY the folder in a docker to build it, I use then the option : _**virtualenvs.create false**_
**_poetry install -vvv_** wont build it with this error : 
```
[JSONDecodeError]             
Expecting value: line 1 column 1 (char 0)  
                                             
Exception trace:
 /root/.poetry/lib/poetry/_vendor/py3.5/cleo/application.py in run() at line 94
   status_code = self.do_run(input_, output_)
 /root/.poetry/lib/poetry/console/application.py in do_run() at line 88
   return super(Application, self).do_run(i, o)
 /root/.poetry/lib/poetry/_vendor/py3.5/cleo/application.py in do_run() at line 197
   status_code = command.run(input_, output_)
 /root/.poetry/lib/poetry/console/commands/command.py in run() at line 77
   return super(BaseCommand, self).run(i, o)
 /root/.poetry/lib/poetry/_vendor/py3.5/cleo/commands/base_command.py in run() at line 136
   self.initialize(input_, output_)
 /root/.poetry/lib/poetry/console/commands/env_command.py in initialize() at line 21
   ".".join(str(v) for v in current_env.version_info[:3])
 /root/.poetry/lib/poetry/utils/env.py in version_info() at line 128
   return tuple(self.marker_env["version_info"])
 /root/.poetry/lib/poetry/utils/env.py in marker_env() at line 144
   self._marker_env = self.get_marker_env()
 /root/.poetry/lib/poetry/utils/env.py in get_marker_env() at line 457
   return json.loads(output)
 /usr/lib/python3.5/json/__init__.py in loads() at line 319
   return _default_decoder.decode(s)
 /usr/lib/python3.5/json/decoder.py in decode() at line 339
   obj, end = self.raw_decode(s, idx=_w(s, 0).end())
 /usr/lib/python3.5/json/decoder.py in raw_decode() at line 357
   raise JSONDecodeError("Expecting value", s, err.value) from None

install [--no-dev] [--dry-run] [-E|--extras EXTRAS] [--develop DEVELOP]
```
If I remove the .venv it works again.

Thanks for your project. It's very helpful :-)

**Comment by chdsbd** [comment]
I ran into this issue too, but I was running with `settings.virtualenvs.in-project = false`.

The fix is the same, but I needed to delete the virtual environment in `settings.virtualenvs.path`

**Comment by jfyne** [comment]
I also had this issue, but my problem was a local package with the same name as a system package. Renaming that package fixed my problem

**Comment by chdsbd** [comment]
I still get this error from time to time.

**Comment by finswimmer** [comment]
As there are no more comments for a long time now I close this issue. Feel free to leave a comment if you disagree.

**Comment by chdsbd** [comment]
I think this is still an issue.

**Comment by abn** [comment]
@chdsbd I do not think mounting host virtual environments into a container environment is a reliable scenario.

I would recommend you cache the virtual environment in the container instead.

Add this to your `.dockerignore` file (assuming you use `in-project` on your host).
```
.venv
dist/
```

```Dockerfile
FROM python:3.8

RUN pip install poetry
RUN poetry config virtualenvs.-
RUN install -d /opt/src

WORKDIR /opt/src

COPY poetry.lock pyproject.toml /opt/src

RUN poetry install  --no-dev --no-root

COPY . /opt/src

RUN poetry install

ENTRYPOINT ["poetry", "run"]

CMD "bash"
```
