### ISSUE TITLE
ModuleNotFoundError for fastpbkdf2 after installing it

### ISSUE THREAD

**Issue by PKostecki** [python-poetry/poetry#6968]
- **Poetry version**: 1.2.2
- **Python version**: 3.9.5
- **OS version and name**: Ubuntu 20.04
- **pyproject.toml**: https://github.com/PKostecki/poetry_import_problem/blob/main/pyproject.toml

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
I ran into a problem trying to use the fastpbkdf2 module.
After creating the lock file and further installing it with `poetry install`, I run into the following error while trying to use the module
```python
  File "PycharmProjects/poetry_import_problem/main.py", line 1, in <module>
    from fastpbkdf2 import pbkdf2_hmac
  File "PycharmProjects/poetry_import_problem/venv/lib/python3.9/site-packages/fastpbkdf2/__init__.py", line 7, in <module>
    from fastpbkdf2._fastpbkdf2 import ffi, lib
ModuleNotFoundError: No module named 'fastpbkdf2._fastpbkd
```

In turn, by running the `poetry run pip freeze` command, I can see that the module is installed
```
$ poetry run pip freeze
cffi==1.15.1
fastpbkdf2==0.2
pycparser==2.21
six==1.16.0
```
## Repro
- ensure to have python 3.9.5
- clone https://github.com/PKostecki/poetry_import_problem
- `poetry lock`
- `poetry install`
- `python main.py`

**Comment by neersighted** [comment]
It looks like this is an external issue, as I can reproduce this without Poetry:

```sh
$ docker run --rm -it --entrypoint /bin/bash python:3.9.5
# pip install --use-pep517 fastpbkdf2
# python3 -c "from fastpbkdf2 import pbkdf2_hmac"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/fastpbkdf2/__init__.py", line 7, in <module>
    from fastpbkdf2._fastpbkdf2 import ffi, lib
ModuleNotFoundError: No module named 'fastpbkdf2._fastpbkdf2'
```
