### ISSUE TITLE
Provide some lever for controlling installer error logging in CI environments

### ISSUE THREAD

**Issue by brian-dlee** [python-poetry/poetry#6974]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request

Provide some kind of environment variables to control the Poetry installer's logging. The installer script installs to a `poetry-installer-error*.log` file, but in CI environments this can be painful to debug. There should be some kind of lever to pull to get poetry to output the installation errors directly to stderr.

Many packages automatically detect the `CI` variable (standard among the CI providers from what I can tell) to automatically change configuration parameters.

**Comment by dimbleby** [comment]
wrong repository, you want https://github.com/python-poetry/install.python-poetry.org

**Comment by brian-dlee** [comment]
Oh, man. That's a bummer. Thanks for setting me on the right path.
