### ISSUE TITLE
poetry add fails to installation from a non-SSL server using the git+http protocol.

### ISSUE THREAD

**Issue by gitnutz** [python-poetry/poetry#6982]
- **Poetry version**: 1.2.2
- **Python version**: 3.9.13
- **OS version and name**: Windows10
- **pyproject.toml**: any

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

poetry add fails to installation from a non-SSL server using the git+http protocol.

```python
$ poetry add git+http://mygitlab-server/groupname/myproject.git

Could not parse version constraint: //mygitlab-server/groupname/myproject.git
```

However, after adding the following line in a pyproject.toml,
and execute poetry update command is success.

```toml
[tool.poetry.dependencies]
myproject = {git = "http://mygitlab-server/groupname/myproject.git", branch = "main"} 
```

```shell
$ poetry update
Updating dependencies
Resolving dependencies...

Writing lock file

Package operations: 1 install, 0 updates, 0 removals

  • Installing myproject (0.1.0 fd675eb)
```

**Comment by dimbleby** [comment]
duplicate #4236
