### ISSUE TITLE
README.md is out of sync with docs/

### ISSUE THREAD

**Issue by germn** [python-poetry/poetry#699]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue
Subj. It especially easy to see comparing [README.md](https://github.com/sdispater/poetry/blob/master/README.md#commands) and [docs/docs/cli.md](https://github.com/sdispater/poetry/blob/master/docs/docs/cli.md#commands) "Commands" sections. For example in Readme.md:

- Whole introduction and section `Global options` is missing
- `--src` option is missing for `new` command
- `--git`, `--path`, `--extras` are missing for `add` command
etc.

It's confusing and hard to maintain. Solution I see is to just leave minimal text and link to full documentation at poetry.eustace.io in Readme.md. Many projects acts this way, for example: [django](https://github.com/django/django), [flask](https://github.com/pallets/flask#links), [aiohttp](https://github.com/aio-libs/aiohttp#documentation).

What do you think about it?

**Comment by darcyprice** [comment]
I have made a PR that acts as an interim solution (link to full documentation at poetry.eustace.io in Readme.md). 

The PR brings [README.md](https://github.com/sdispater/poetry/blob/master/README.md#commands) inline with [docs/docs/cli.md](https://github.com/sdispater/poetry/blob/master/docs/docs/cli.md#commands) "Commands" sections

It's my first contribution, thank you! 😃

**Comment by thernstig** [comment]
@darcyprice Nice PR! I want to note that multiple parts are still missing, The cli.md describes many commands, such as [shell](https://github.com/sdispater/poetry/blob/master/docs/docs/cli.md#shell) and [check](https://github.com/sdispater/poetry/blob/master/docs/docs/cli.md#check) that are not part of README.md. There are most likely much more missing, but I did not go through it all.

Maybe it would be better to re-write the README.md instead to point to the real documentation that is maintained, i.e. cli.md?

**Comment by thernstig** [comment]
@darcyprice Nice! I think it could require some work to refine, but it is a great start. I think the actual review is better left to a maintainer.

**Comment by thernstig** [comment]
Unstale

**Comment by finswimmer** [comment]
In the meantime the `README.md` contains only a short introduction to poetry. The complete documentation is in docs.
