### ISSUE TITLE
poetry tags aren't visible using "simple" git commands

### ISSUE THREAD

**Issue by cpcloud** [python-poetry/poetry#6990]
I wasn't entirely sure whether to file this as a bug report, but I'm going to anyway as I think it does fall into the bug bucket somewhat.

None of these I believe are relevant for the issue.

- **Poetry version**: N/A
- **Python version**: N/A
- **OS version and name**: N/A
- **pyproject.toml**: N/A

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

`poetry`'s tags appear to not be accessible using "simple" git commands:

```
❯ git rev-parse HEAD
def1ee8f3ae00c307ca028da53d2347615c5c32b
❯ git describe --tags --abbrev=0
1.2.0rc1
❯ git for-each-ref refs/tags --sort=-taggerdate --count=1 --format='%(refname:short)'
1.2.2
```

This causes problems for [`pre-commit` auto updates](https://github.com/ibis-project/ibis/pull/4792), as that's the command pre-commit runs to get the latest tags for updating a given pre-commit.

All issues on the pre-commit tracker related to this issue appear to have been closed (e.g., https://github.com/pre-commit/pre-commit/issues/2507).

I don't know exactly why poetry's tags are now like this, but it would be really nice to fix them (or at least fix the issue for the next tag) so that pre-commit isn't trying to downgrade everyone to 1.2.0rc1.

It appears that before `1.2.0rc1`, the latest tag was indeed accessible via `git describe --tags --abbrev=0`.

**Comment by neersighted** [comment]
[Addressed in the FAQ](https://python-poetry.org/docs/pre-commit-hooks/#faq); in essence pre-commit is incompatible with the branching model of Poetry and many other projects.

**Comment by cpcloud** [comment]
Ah, ok thanks for the quick reply! A little unfortunate that pre-commit is taking such a hard stance.

**Comment by Cielquan** [comment]
*Because discussions are not automatically linked by github like issues do.*

https://github.com/python-poetry/poetry/discussions/7018
