### ISSUE TITLE
Poetry 1.2 doesnt pass "--" properly to run

### ISSUE THREAD

**Issue by commentator8** [python-poetry/poetry#6991]
Hi,

poetry version: `Poetry (version 1.2.2)`
python version: 
```
❯ poetry debug info

Poetry
Version: 1.2.2
Python:  3.9.0

Virtualenv
Python:         3.9.0
Implementation: CPython
Path:           /Users/yehudalewis/Library/Caches/pypoetry/virtualenvs/x-service-R2jrR2bp-py3.9
Executable:     /Users/yehudalewis/Library/Caches/pypoetry/virtualenvs/x-service-R2jrR2bp-py3.9/bin/python
Valid:          True

System
Platform:   darwin
OS:         posix
Python:     3.9.0
Path:       /Users/yehudalewis/.pyenv/versions/3.9.0
Executable: /Users/yehudalewis/.pyenv/versions/3.9.0/bin/python3.9
```

OS version: `MacOS 12.6`

pyproject.toml - irrelevant if I understand correctly, I used the most basic version without any additions and it occurs.

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

In poetry 1.1 when I passed in an argument to nox via poetry run with a "--" e.g. `poetry run nox session_name -- arg2`, it would "work" which is to say that it would pass to nox the session_name arg and then nox would receive the "--" and know to pass arg2 to the called session. In version 1.2 (I upgraded and tested without any other changes) it seems to pass it all to nox together which chokes on the input. I tried escaping the -- with `\-\-` and using quotes but it didn't help. The -- is a convention used by argparse (used by nox) to split the input args into two (see [here](https://stackoverflow.com/a/25865012/459109)).
```
❯ poetry run nox -- blah
usage: nox [-h] [--version] [-l] [-s [SESSIONS ...]] [-p [PYTHONS ...]] [-k KEYWORDS] [-t [TAGS ...]] [-v] [-ts] [-db {none,virtualenv,conda,mamba,venv}] [-fb {none,virtualenv,conda,mamba,venv}] [--no-venv] [-r]
           [-N] [-R] [-f NOXFILE] [--envdir ENVDIR] [--extra-pythons [EXTRA_PYTHONS ...]] [--force-pythons [FORCE_PYTHONS ...]] [-x] [--no-stop-on-first-error] [--error-on-missing-interpreters]
           [--no-error-on-missing-interpreters] [--error-on-external-run] [--no-error-on-external-run] [--install-only] [--no-install] [--report REPORT] [--non-interactive] [--nocolor] [--forcecolor]
           ...
nox: error: Unknown argument(s) '-- blah'.
```

The above is a simple reproduce, the actual command used more args like this
`poetry run nox -f ../Packages/quality_package/noxfile.py --session=pre-commit -- x-service diff` and received the following output `nox: error: Unknown argument(s) 'token-service diff'`

**Comment by neersighted** [comment]
Not a bug -- Poetry consumes the first -- to terminate its own argument parsing, so you need to type it twice to pass a literal --.

**Comment by commentator8** [comment]
That... helps. Thanks a lot!
