### ISSUE TITLE
A 2nd `poetry install -E` removes optional packages previously installed

### ISSUE THREAD

**Issue by ancalita** [python-poetry/poetry#6993]
- **Poetry version**:  `1.2.2`
- **Python version**:  3.7+, <3.10
- **OS version and name**: Ubuntu 20.04
- **pyproject.toml**: https://github.com/RasaHQ/rasa/blob/ATO-527-upgrade-dependencies-for-3.10-support/pyproject.toml

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
- I recently upgraded the poetry version used by the CI at rasa to `1.2.2`.
- In the CI workflow, we have 2 consecutive executions of  `poetry install -E` of dependencies that are marked as optional. With the 2nd `poetry install -E`, most of these dependencies are removed/uninstalled, see below output.
- The dependencies that are removed are required for the CI testing jobs, at the moment tests are failing with `ModuleNotFoundError: No module named 'transformers'`

```
poetry install -E full
Installing dependencies from lock file

Package operations: 24 installs, 0 updates, 0 removals

  • Installing catalogue (2.0.8)
  • Installing cymem (2.0.7)
  • Installing murmurhash (1.0.9)
  • Installing pydantic (1.10.2)
  • Installing srsly (2.4.5)
  • Installing blis (0.7.9)
  • Installing confection (0.0.3)
  • Installing filelock (3.8.0)
  • Installing smart-open (5.2.1)
  • Installing preshed (3.0.8)
  • Installing typer (0.4.2)
  • Installing wasabi (0.10.1)
  • Installing huggingface-hub (0.10.1)
  • Installing langcodes (3.3.0)
  • Installing pathy (0.6.2)
  • Installing sacremoses (0.0.53)
  • Installing spacy-legacy (3.0.10)
  • Installing spacy-loggers (1.0.3)
  • Installing thinc (8.1.5)
  • Installing tokenizers (0.10.3)
  • Installing jieba (0.42.1)
  • Installing sentencepiece (0.1.97)
  • Installing spacy (3.4.2)
  • Installing transformers (4.13.0)

Installing the current project: rasa (3.3.0)
poetry install -E spacy
Installing dependencies from lock file

Package operations: 0 installs, 0 updates, 7 removals

  • Removing filelock (3.8.0)
  • Removing huggingface-hub (0.10.1)
  • Removing jieba (0.42.1)
  • Removing sacremoses (0.0.53)
  • Removing sentencepiece (0.1.97)
  • Removing tokenizers (0.10.3)
  • Removing transformers (4.13.0)

Installing the current project: rasa (3.3.0)
```

**Comment by neersighted** [comment]
This is the [documented behavior](https://python-poetry.org/docs/cli/#install) of `install` -- simplify specify the full set of extras you want installed during each invocation.
