### ISSUE TITLE
Please upgrade pyrsistent to 0.19.2

### ISSUE THREAD

**Issue by gilbahat** [python-poetry/poetry#6998]
Hi,

pyrsistent 0.19.2 is out. That release now offers aarch64 prebuilt wheels, significantly speeding up installation in docker environments on mac m1/m2 machines.
Please upgrade the pyrsistent dependency from 0.18.1.

**Comment by finswimmer** [comment]
Hello @gilbahat,

`pyrsistent` is not a direct dependency by Poetry. You can update Poetry's own dependencies and transient dependencies by running `poetry self lock` followed by `poetry self install --sync`.

fin swimmer
