### ISSUE TITLE
Running `install --only-root` removes optional dependencies (extras)

### ISSUE THREAD

**Issue by chopeen** [python-poetry/poetry#7000]
- **Poetry version**: Poetry (version 1.2.2)
- **Python version**: Python:  3.8.15
- **OS version and name**: Ubuntu 20.04

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

I have a project with `torch` installed as an optional dependency.

When I run `poetry install -E deep_learning`, it gets installed as expected.

However, it gets removed, when I run `poetry install --only-root`:

```
Installing dependencies from lock file
Package operations: 0 installs, 0 updates, 1 removal
  • Removing torch (1.6.0)
Installing the current project: local_clf (0.2.0)
```

According to [cli/#options-2](https://python-poetry.org/docs/cli/#options-2), the `--only-root` option is supposed to install only the root project, **excluding all dependencies**, so I think no dependency should be removed.

## Workaround

`poetry install --only-root -E deep_learning` works as expected.

**Comment by neersighted** [comment]
Not a bug; duplicate #6993.
