### ISSUE TITLE
Poetry ignoring dependency environment markers

### ISSUE THREAD

**Issue by potatochip** [python-poetry/poetry#7002]
- **Poetry version**: 1.2.2
- **Python version**: 3.8.11
- **OS version and name**: macOS 12.5.1

- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

`poetry add phoenixdb` fails because poetry tries to install dependency version that only works when python is lower than version 3.6 despite the dependency being annotated as such.

This is the relevant portion of phoenixdb setup.py:
```
if setuptools.__version__ < '20.8.1':
    # Workaround for source install on old setuptools
    # This won't be able to create a proper multi-version pacakage
    install_requires=[
        'protobuf>=3.0.0',
        'requests',
        'requests-gssapi',
        'SQLAlchemy'
    ]
    if sys.version_info < (3,6):
        install_requires.append('gssapi<1.6.0')
    #Don't build the docs on an old stack
    setup_requires=[]
else:
    install_requires=[
        'protobuf>=3.0.0',
        'requests',
        'requests-gssapi',
        'gssapi<1.6.0;python_version<"3.6"',
        'SQLAlchemy'
    ]
    setup_requires=[
        'Sphinx;python_version>="3.6"',
    ],
```

See [setup.py](https://github.com/apache/phoenix-queryserver/blob/python-phoenixdb-1.2.1/python-phoenixdb/setup.py#L37)

**Comment by dimbleby** [comment]
Not a poetry bug:
```
$ curl -s https://pypi.org/pypi/phoenixdb/json | jq ".info.requires_dist"
[
  "protobuf (>=3.0.0)",
  "requests",
  "requests-gssapi",
  "gssapi (<1.6.0)",
  "SQLAlchemy",
  "SQLAlchemy ; extra == 'sqlalchemy'"
]
```

**Comment by clintonroy** [comment]
To add a bit of filler, it appears that the metadata uploaded to pypi is different to the metadata in the wheel. Poetry uses that pypi metadata to determine dependencies. I don't think pypi allows modification of that metadata, so a new version would have to be uploaded.

**Comment by potatochip** [comment]
If anybody sees this in the future, I avoided the whole issue altogether by installing directly from GitHub instead of using pypi as source.

```
phoenixdb = {git = "https://github.com/apache/phoenix-queryserver.git/", tag = "python-phoenixdb-1.2.1", subdirectory = "python-phoenixdb"}
```
