### ISSUE TITLE
Remove `NullLocker` and satisfy `mypy` 0.990

### ISSUE THREAD

**Issue by moonsikpark** [python-poetry/poetry#7006]
Mypy introduced python/mypy#12118, and it wails `empty-body` on functions with empty body like this. https://github.com/python-poetry/poetry/blob/b28339d8b76500025fadcd23c87debfc368b609c/src/poetry/packages/locker.py#L469-L471

It seems there are no references to `NullLocker`, so I am wondering whether we can remove `NullLocker` and bump the `mypy` version to 0.990. If that's OK, I'm ready to submit a PR.

**Comment by abn** [comment]
This was originally used in the update command, which is not the case anymore.

Based on a quick scan of https://cs.github.com/?q=NullLocker+path%3A*.py it seems there is no downstream usage on GitHub that we are aware of that will break implicitly. 

So, I suspect we can drop this without any side-effects. I doubt there is much value in employing a deprecation cycle here. 

We should call it out in the change log though. There are tools out there that use poetry as a library.
