### ISSUE TITLE
Poetry complete has too many arguments (with fish)

### ISSUE THREAD

**Issue by kaprests** [python-poetry/poetry#7008]
- poetry version: 1.2.2
- python version: 3.10.8
- fish version: 3.5.1
- OS: MacOS 13.0.0 (Ventura)
- Terminal: Kitty

Seemingly pretty much the exact same issue as for [issue 7865 (fish repo)](https://github.com/fish-shell/fish-shell/issues/7865) just with poetry. Opened [this issue](https://github.com/fish-shell/fish-shell/issues/9339) there, but were told that the issue must be solved here.

Steps to reproduce:

1.  Open a fresh session of `fish`.
2. Type `poetry`
3. Press tab for auto-complete

<details>
<summary>Terminal output</summary>
/opt/homebrew/share/fish/vendor_completions.d/poetry.fish (line 25): 
complete -c poetry -f -n '__fish_poetry_aa596d7336ece196_complete_no_subcommand' -a cache clear -d 'Clears Poetry\'s cache.'
^
from sourcing file /opt/homebrew/share/fish/vendor_completions.d/poetry.fish

(Type 'help complete' for related documentation)
complete: too many arguments

/opt/homebrew/share/fish/vendor_completions.d/poetry.fish (line 26): 
complete -c poetry -f -n '__fish_poetry_aa596d7336ece196_complete_no_subcommand' -a cache list -d 'List Poetry\'s caches.'
^
from sourcing file /opt/homebrew/share/fish/vendor_completions.d/poetry.fish

(Type 'help complete' for related documentation)
complete: too many arguments

/opt/homebrew/share/fish/vendor_completions.d/poetry.fish (line 29): 
complete -c poetry -f -n '__fish_poetry_aa596d7336ece196_complete_no_subcommand' -a debug info -d 'Shows debug information.'
^
from sourcing file /opt/homebrew/share/fish/vendor_completions.d/poetry.fish

(Type 'help complete' for related documentation)
complete: too many arguments

/opt/homebrew/share/fish/vendor_completions.d/poetry.fish (line 30): 
complete -c poetry -f -n '__fish_poetry_aa596d7336ece196_complete_no_subcommand' -a debug resolve -d 'Debugs dependency resolution.'
^
from sourcing file /opt/homebrew/share/fish/vendor_completions.d/poetry.fish

(Type 'help complete' for related documentation)
complete: too many arguments

/opt/homebrew/share/fish/vendor_completions.d/poetry.fish (line 31): 
complete -c poetry -f -n '__fish_poetry_aa596d7336ece196_complete_no_subcommand' -a env info -d 'Displays information about the current environment.'
^
from sourcing file /opt/homebrew/share/fish/vendor_completions.d/poetry.fish

(Type 'help complete' for related documentation)
complete: too many arguments

/opt/homebrew/share/fish/vendor_completions.d/poetry.fish (line 32): 
complete -c poetry -f -n '__fish_poetry_aa596d7336ece196_complete_no_subcommand' -a env list -d 'Lists all virtualenvs associated with the current project.'
^
from sourcing file /opt/homebrew/share/fish/vendor_completions.d/poetry.fish

(Type 'help complete' for related documentation)
complete: too many arguments

/opt/homebrew/share/fish/vendor_completions.d/poetry.fish (line 33): 
complete -c poetry -f -n '__fish_poetry_aa596d7336ece196_complete_no_subcommand' -a env remove -d 'Remove virtual environments associated with the project.'
^
from sourcing file /opt/homebrew/share/fish/vendor_completions.d/poetry.fish

(Type 'help complete' for related documentation)
complete: too many arguments

/opt/homebrew/share/fish/vendor_completions.d/poetry.fish (line 34): 
complete -c poetry -f -n '__fish_poetry_aa596d7336ece196_complete_no_subcommand' -a env use -d 'Activates or creates a new virtualenv for the current project.'
^
from sourcing file /opt/homebrew/share/fish/vendor_completions.d/poetry.fish

(Type 'help complete' for related documentation)
complete: too many arguments

/opt/homebrew/share/fish/vendor_completions.d/poetry.fish (line 46): 
complete -c poetry -f -n '__fish_poetry_aa596d7336ece196_complete_no_subcommand' -a self add -d 'Add additional packages to Poetry\'s runtime environment.'
^
from sourcing file /opt/homebrew/share/fish/vendor_completions.d/poetry.fish

(Type 'help complete' for related documentation)
complete: too many arguments

/opt/homebrew/share/fish/vendor_completions.d/poetry.fish (line 47): 
complete -c poetry -f -n '__fish_poetry_aa596d7336ece196_complete_no_subcommand' -a self install -d 'Install locked packages (incl. addons) required by this Poetry installation.'
^
from sourcing file /opt/homebrew/share/fish/vendor_completions.d/poetry.fish

(Type 'help complete' for related documentation)
complete: too many arguments

/opt/homebrew/share/fish/vendor_completions.d/poetry.fish (line 48): 
complete -c poetry -f -n '__fish_poetry_aa596d7336ece196_complete_no_subcommand' -a self lock -d 'Lock the Poetry installation\'s system requirements.'
^
from sourcing file /opt/homebrew/share/fish/vendor_completions.d/poetry.fish

(Type 'help complete' for related documentation)
complete: too many arguments

/opt/homebrew/share/fish/vendor_completions.d/poetry.fish (line 49): 
complete -c poetry -f -n '__fish_poetry_aa596d7336ece196_complete_no_subcommand' -a self remove -d 'Remove additional packages from Poetry\'s runtime environment.'
^
from sourcing file /opt/homebrew/share/fish/vendor_completions.d/poetry.fish

(Type 'help complete' for related documentation)
complete: too many arguments

/opt/homebrew/share/fish/vendor_completions.d/poetry.fish (line 50): 
complete -c poetry -f -n '__fish_poetry_aa596d7336ece196_complete_no_subcommand' -a self show -d 'Show packages from Poetry\'s runtime environment.'
^
from sourcing file /opt/homebrew/share/fish/vendor_completions.d/poetry.fish

(Type 'help complete' for related documentation)
complete: too many arguments

/opt/homebrew/share/fish/vendor_completions.d/poetry.fish (line 51): 
complete -c poetry -f -n '__fish_poetry_aa596d7336ece196_complete_no_subcommand' -a self show plugins -d 'Shows information about the currently installed plugins.'
^
from sourcing file /opt/homebrew/share/fish/vendor_completions.d/poetry.fish

(Type 'help complete' for related documentation)
complete: too many arguments

/opt/homebrew/share/fish/vendor_completions.d/poetry.fish (line 52): 
complete -c poetry -f -n '__fish_poetry_aa596d7336ece196_complete_no_subcommand' -a self update -d 'Updates Poetry to the latest version.'
^
from sourcing file /opt/homebrew/share/fish/vendor_completions.d/poetry.fish

(Type 'help complete' for related documentation)
complete: too many arguments

/opt/homebrew/share/fish/vendor_completions.d/poetry.fish (line 55): 
complete -c poetry -f -n '__fish_poetry_aa596d7336ece196_complete_no_subcommand' -a source add -d 'Add source configuration for project.'
^
from sourcing file /opt/homebrew/share/fish/vendor_completions.d/poetry.fish

(Type 'help complete' for related documentation)
complete: too many arguments

/opt/homebrew/share/fish/vendor_completions.d/poetry.fish (line 56): 
complete -c poetry -f -n '__fish_poetry_aa596d7336ece196_complete_no_subcommand' -a source remove -d 'Remove source configured for the project.'
^
from sourcing file /opt/homebrew/share/fish/vendor_completions.d/poetry.fish

(Type 'help complete' for related documentation)
complete: too many arguments

/opt/homebrew/share/fish/vendor_completions.d/poetry.fish (line 57): 
complete -c poetry -f -n '__fish_poetry_aa596d7336ece196_complete_no_subcommand' -a source show -d 'Show information about sources configured for the project.'
^
from sourcing file /opt/homebrew/share/fish/vendor_completions.d/poetry.fish

(Type 'help complete' for related documentation)
</details>

**Comment by neersighted** [comment]
Duplicate #5929.
