### ISSUE TITLE
`poetry install` gets stuck indefinitely for >10min and even `-vvv` does not contain useful debug information

### ISSUE THREAD

**Issue by corneliusroemer** [python-poetry/poetry#7010]
## General info

- **Poetry version**: Poetry version 1.1.15
- **Python version**: 3.10.6
- **OS version and name**: macOS 13.0.1 using ARM64
- **pyproject.toml**: https://gist.github.com/corneliusroemer/e8292beef1a0610f7962f1b65c5d1eeb
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

I've just started to try out poetry. I am very surprised to find that even in debug mode (`-vvv`) the solver doesn't report any progress for 10 minutes - nothing, no information whether anything is happening or not, whether it's a bandwidth issue, the solver got stuck etc.

This is very unwelcoming to new users. I would expect that at the very least in debug mode I have granular access to logs that help me figure out the problem.

The output shown below appeared within a few seconds, after that nothing happened until I aborted.

<img width="1069" alt="image" src="https://user-images.githubusercontent.com/25161793/201356449-ec51ae9e-3c45-4b67-8056-def4028c31f9.png">

**Comment by dimbleby** [comment]
delete the cache, try again

**Comment by corneliusroemer** [comment]
Deleted cache `poetry cache clear pypi --all`, doesn't help. Sorry I realized my gist was set on secret.

I managed to make it work by changing dependencies, but that's not a solution to the problem of `poetry` getting stuck and not providing any sort of information about what's wrong.

Using the original toml, this is where it gets stuck now.

<img width="1181" alt="image" src="https://user-images.githubusercontent.com/25161793/201371850-40ee9237-2295-4412-96f6-5dc8349ff3aa.png">

**Comment by neersighted** [comment]
Your first `pyproject.toml` locks fine for me on 1.2.2 (after 120s -- it's a really wide search space) -- you likely should blow away the entirety of `~/.cache/pypoetry` as something is severely broken in there. We have much more robust prevention of corrupted caches in the upcoming 1.3 release; in the mean time try not to abort Poetry when it is solving as you can leave stale lock files.
