### ISSUE TITLE
Poetry extras not working

### ISSUE THREAD

**Issue by Leon0402** [python-poetry/poetry#7011]
- **Poetry version**: 1.2.2
- **Python version**: 3.8.6
- **OS version and name**: Windows 10

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

I can install any package with extras like for instance: 
````poetry add protobuf=3.19.4 --extras="lyft"```
or 
```poetry add nuscenes-devkit --extras="nuscenes"````
and it will result in a correct pytoml

````
nuscenes-devkit = {version = "^1.1.9", extras = ["nuscenes"]}
protobuf = {version = "3.19.4", extras = ["lyft"]}
````

but when I do `poetry install -E lyft`` I get: 
````Extra [lyft] is not specified.```

I also tried different syntaxes for extras (with own section and optional) and different command line invocations. but nothing seems to work.

**Comment by neersighted** [comment]
Solved on Discord, it was a misreading of [the docs](https://python-poetry.org/docs/pyproject/#extras)
