### ISSUE TITLE
Hide output logs option or dump logs to stderr

### ISSUE THREAD

**Issue by mrjk** [python-poetry/poetry#7014]
- **Poetry version**: Poetry (version 1.2.2)
- **Python version**: 3.9.12
- **OS version and name**: Manjaro as of November 2022
- **pyproject.toml**: https://gist.github.com/mrjk/7098e4b882025e777407e2ea8a3b7676

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue Description

While trying to get the future version of my release in for a CI/CD bash script:
```
$ FUTURE_VERSION=$(poetry version  --dry-run -s patch)
$ echo $FUTURE_VERSION
0.1.1 poetry_bumpversion: processed file myprj/__version__.py
```
But that does not work, because of extra the logging output. We can see here I use the `poetry-bumpversion` package to bump my version. I suppose the bug is relevant to poetry, even if the log message is generated by  `poetry-bumpversion`. I would love a switch to hide logs or at least to send log messages to stderr.

Expected output:
```
$ FUTURE_VERSION=$(poetry version  --dry-run -s patch)
$ echo $FUTURE_VERSION
0.1.1
```

Why raising a bug in poetry project instead of poetry-bumpversion ?

On the poetry-bumpversion code, [see this line](https://github.com/monim67/poetry-bumpversion/blob/main/src/poetry_bumpversion/plugin.py#L85), and I suppose the `command.info` object comes from poetry, like if the logging processing is delegated to poetry.

## Workaround

Let's try with this first attempt:
```
$ poetry version  --dry-run -s patch
0.1.1
poetry_bumpversion: processed file myprj/__version__.py
```
Geat, this is what I want, but there is an extra line, let's make this quiet:
```
$ poetry version  --dry-run -s -q patch 
<NOTHING>
```
Damn, let's try this then:
```
$ poetry version  --dry-run -s patch  | head -n 1
0.1.1

[Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
```
Arggg, python exception ! Let's workaround this:
```
$ poetry version  --dry-run -s patch 2>/dev/null | head -n 1 
0.1.1
```
Swell ! !

## More informations about Broken Pipe

Actually, while experimenting workarounds, I reported the broken pip error to the cleo project [here](https://github.com/python-poetry/cleo/issues/279), that will solve the broken pipe error.

A truncated stack error:
```
  1  .direnv/python-3.9.12/lib/python3.9/site-packages/cleo/io/outputs/output.py:112 in write
      110│                 message = strip_tags(self._formatter.format(message))
      111│ 
    → 112│             self._write(message, new_line=new_line)
      113│ 
      114│     def flush(self) -> None:

  BrokenPipeError

  [Errno 32] Broken pipe

```

**Comment by neersighted** [comment]
With Poetry's current logging architecture, decisions around whether to include messages are local and not global. There's not much for Poetry to do here, except maybe forcing output during `poetry version -q`; `bumpinfo` is just writing to stdout when it should not be.

**Comment by mrjk** [comment]
Hey, thanks for your answer. So if I well understood, that means this is an issue on the `poetry-bumpversion` project, which print to stdout instead of stderr. Ok.

But if I go a bit deeper into the code, and I see the plugin use `command.info(_(f"processed file {instruction.file}"))` to log output. But If I check the command object, it is composed of `Command`, herited from `BaseCommand`:

https://github.com/python-poetry/poetry/blob/master/src/poetry/console/commands/command.py#L15
https://github.com/python-poetry/cleo/blob/main/src/cleo/commands/base_command.py#L16

I don't see in the latter any method that allow you to print to stderr, excepted `line_error()`.  Is it what you mean when you say `There's not much for Poetry to do here, decisions around whether to include messages are local and not global` ? 

So my understanding is `poetry-bumpversion` needs to check if the `-v` flag is present on the command line and log to output only if present ?
