### ISSUE TITLE
Poetry has issues with version contraint ">=3.6,<3.8" when requirement is python 3.7

### ISSUE THREAD

**Issue by danielniccoli** [python-poetry/poetry#7021]
```
Poetry
Version: 1.2.2
Python:  3.10.6

Virtualenv
Python:         3.7.9
Implementation: CPython
Path:           C:\Users\Daniel\Documents\source\azwei\.venv
Executable:     C:\Users\Daniel\Documents\source\azwei\.venv\Scripts\python.exe
Valid:          True

System
Platform:   win32
OS:         nt
Python:     3.7.9
Path:       C:\Users\Daniel\AppData\Local\Programs\Python\Python37
Executable: C:\Users\Daniel\AppData\Local\Programs\Python\Python37\python.exe
```

- [ x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

### pyproject.toml
```
[tool.poetry.dependencies]
python = ">=3.6,<3.8"
```

### Error highlights:

Notice how the Python req changes from <3.8 to <3.7?

> The current project's Python requirement **(>=3.6,<3.8)** is not compatible
> black requires Python >=3.7, so it will not be satisfied for Python **>=3.6,<3.7**

`poetry lock` or `poetry lock --no-update` didn't solve it.

### Full Error
```
(azwei-py3.7) PS C:\Users\Daniel\Documents\source\azwei> poetry add black
Using version ^22.10.0 for black

Updating dependencies
Resolving dependencies...

The current project's Python requirement (>=3.6,<3.8) is not compatible with some of the required packages Python requirement:
  - black requires Python >=3.7, so it will not be satisfied for Python >=3.6,<3.7

Because no versions of black match >22.10.0,<23.0.0
 and black (22.10.0) requires Python >=3.7, black is forbidden.
So, because azwei depends on black (^22.10.0), version solving failed.

  • Check your dependencies Python requirement: The Python requirement can be specified via the `python` or `markers` properties

    For black, a possible solution would be to set the `python` property to ">=3.7,<3.8"

    https://python-poetry.org/docs/dependency-specification/#python-restricted-dependencies,
    https://python-poetry.org/docs/dependency-specification/#using-environment-markers
```

**Comment by finswimmer** [comment]
Hello @danielniccoli,

this behavior is expected. Please have a look into our [FAQ](https://python-poetry.org/docs/faq/#why-is-poetry-telling-me-that-the-current-projects-python-requirement-is-not-compatible-with-one-or-more-packages-python-requirements) for further details.

fin swimmer
