### ISSUE TITLE
`poetry lock --check` in pre-commit?

### ISSUE THREAD

**Issue by max-sixty** [python-poetry/poetry#7029]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request

Currently there is a `poetry lock` pre-commit which runs the full update, and a `poetry check` pre-commit which validates `pyproject.toml`.

It would be useful to have a hook which runs `poetry lock --check`. IIUC, this confirms that the lock file is up-to-date with `pyproject.toml`, without attempting to update the lock file for new versions of dependencies.

**Comment by Secrus** [comment]
This is already supported, you just need to add `args: [--check]` to your hook config

**Comment by max-sixty** [comment]
> This is already supported, you just need to add `args: [--check]` to your hook config

Yes. I would think (with some conviction fwiw) this would be default — it seems so unlikely that someone would want to regenerate their lock file, upgrading all dependencies, on every commit...

**Comment by neersighted** [comment]
You might be surprised -- `poetry lock` is a common workflow for those who don't curate/manage their dep locking process, and #6756 is the path forward we're looking at anyway.

**Comment by max-sixty** [comment]
#6756 would be ideal! I had originally been confused by that too
