### ISSUE TITLE
Failed to unlock the collection

### ISSUE THREAD

**Issue by cossio** [python-poetry/poetry#7032]
- **Poetry version**: Poetry (version 1.2.2)
- **Python version**: 3.9.13
- **OS version and name**: Ubuntu 20.04.3 LTS

- **pyproject.toml**:

```
[tool.poetry]
name = "celeba"
version = "0.1.0"
description = ""
authors = ["Cossio"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

```
poetry debug info
```

```
Poetry
Version: 1.2.2
Python:  3.9.13

Virtualenv
Python:         3.9.13
Implementation: CPython
Path:           /home/cossio/.cache/pypoetry/virtualenvs/celeba-z-TBHf72-py3.9
Executable:     /home/cossio/.cache/pypoetry/virtualenvs/celeba-z-TBHf72-py3.9/bin/python
Valid:          True

System
Platform:   linux
OS:         posix
Python:     3.9.13
Path:       /home/cossio/anaconda3
Executable: /home/cossio/anaconda3/bin/python3.9
```

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

```
poetry -vvv add numpy
```
Output: https://gist.github.com/cossio/c7e5b00222bfb1926d71d9a7db79c330

## Issue

Trying to add any package produces an error, `Failed to unlock the collection!`. This is on a fresh poetry install.

**Comment by neersighted** [comment]
Duplicate #1917.
