### ISSUE TITLE
poetry not correctly handling a 304 response code from pypi?

### ISSUE THREAD

**Issue by drofford** [python-poetry/poetry#7036]
- **Poetry (version 1.2.2)**
- **Python 3.10.6**
- **mac OS Ventura 13.0.1**
- **pyproject.toml** (see below).

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

I'm having a problem running poetry with the `install`, `update`, `lock` subcommands. The requested operation starts but never completes, the elapsed time keeps increasing.

Running the poetry with `-vvv`, I can see it seems to be hung up on the redirect:

```bash
$ poetry lock -vvv
Loading configuration file /Users/XXXX/Library/Preferences/pypoetry/config.toml
Using virtualenv: /Users/XXXX/venvs/py3106
Project environment contains an empty path in sys_path, ignoring.
Updating dependencies
Resolving dependencies...
   1: fact: checking is 1.1.0
   1: derived: checking
   1: fact: checking depends on daiquiri (^3.2.1)
   1: fact: checking depends on pytest (^7.1.2)
   1: selecting checking (1.1.0)
   1: derived: pytest (>=7.1.2,<8.0.0)
   1: derived: daiquiri (>=3.2.1,<4.0.0)
[keyring.backend] Loading KWallet
[keyring.backend] Loading SecretService
[keyring.backend] Loading Windows
[keyring.backend] Loading chainer
[keyring.backend] Loading libsecret
[keyring.backend] Loading macOS
Creating new session for pypi.org
[urllib3.connectionpool] Starting new HTTPS connection (1): pypi.org:443
[urllib3.connectionpool] https://pypi.org:443 "GET /simple/pytest/ HTTP/1.1" 304 0
```

My `pyproject.toml` file looks like this:
```
[tool.poetry]
name = "checking"
version = "1.1.0"
description = "XXX"
authors = ["XXX"]

[tool.poetry.dependencies]
python = "3.10.6"
daiquiri = "^3.2.1"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"

[tool.poetry.scripts]
check-json-config = 'checking.check_ext_svc_cfg.cli.__main__:main'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

And my poetry config looks like:
```
$ poetry config --list
cache-dir = "/Users/XXXX/Library/Caches/pypoetry"
experimental.new-installer = true
experimental.system-git-client = false
installer.max-workers = null
installer.no-binary = null
installer.parallel = true
virtualenvs.create = true
virtualenvs.in-project = null
virtualenvs.options.always-copy = false
virtualenvs.options.no-pip = false
virtualenvs.options.no-setuptools = false
virtualenvs.options.system-site-packages = false
virtualenvs.path = "{cache-dir}/virtualenvs"  # /Users/XXXX/Library/Caches/pypoetry/virtualenvs
virtualenvs.prefer-active-python = false
virtualenvs.prompt = "{project_name}-py{python_version}"
```

Any insights much appreciated!

**Comment by neersighted** [comment]
Looks like a corrupt cache due to stale lock files from `lockfile`. Try blowing it away with `rm -rf $(poetry config cache-dir)/cache`.

This is resolved on the 1.3 branch, for what it is worth.

**Comment by drofford** [comment]
Thanks @neersighted, that worked like a charm.

**Comment by drofford** [comment]
Thanks @neersighted, that worked like a charm.
