### ISSUE TITLE
Poetry Failing on all packages?

### ISSUE THREAD

**Issue by DrawnWren** [python-poetry/poetry#7042]
- **Poetry version**: 1.2.2
- **Python version**: 
- **OS version and name**: Various. Macos, arch, and windows
- **pyproject.toml**: any pyproject.toml. to include `poetry self update`

- [x ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

We've been using poetry for a while on a few different repos. Today, all of our docker builds started failing and poetry is unable to install any packages on any of our machines. We're a remote shop on different continents, so I'm having a hard time pinpointing.

Even `poetry self update` doesn't work. Here is the output:

```No suitable keyring backend found
No suitable keyring backends were found
Keyring is not available, credentials will be stored and retrieved from configuration files as plaintext.
Creating new session for pypi.org
[urllib3.connectionpool] Starting new HTTPS connection (1): pypi.org:443
[urllib3.connectionpool] https://pypi.org:443 "GET /simple/multidict/ HTTP/1.1" 304 0
```

pip seems to be working fine, and pypi.org seems very accessible to me.

**Comment by dimbleby** [comment]
poetry is obviously not spontaneously and universally broken.

sounds like you can reproduce this in a docker container, so please provide a reproduction.

**Comment by DrawnWren** [comment]
So our docker builds are failing on various packages, but here's the output from one of them: 
```
  • Installing sqlalchemy (1.4.42)

  HangupException

  The remote server unexpectedly closed the connection.

  at /usr/local/lib/python3.10/dist-packages/dulwich/protocol.py:220 in read_pkt_line
      216│
      217│         try:
      218│             sizestr = read(4)
      219│             if not sizestr:
    → 220│                 raise HangupException()
      221│             size = int(sizestr, 16)
      222│             if size == 0:
      223│                 if self.report_activity:
      224│                     self.report_activity(4, "read")

The following error occurred when trying to handle this error:


  GitProtocolError

  Repository not found.

  at /usr/local/lib/python3.10/dist-packages/dulwich/client.py:1151 in fetch_pack
      1147│         with proto:
      1148│             try:
      1149│                 refs, server_capabilities = read_pkt_refs(proto.read_pkt_seq())
      1150│             except HangupException as exc:
    → 1151│                 raise _remote_error_from_stderr(stderr) from exc
      1152│             (
      1153│                 negotiated_capabilities,
      1154│                 symrefs,
      1155│                 agent,
```
`poetry add sqlalchemy` cycles w/ `HangupException` as well.

**Comment by neersighted** [comment]
Please share a pyproject.toml as per the issue template (or a complete container reproduction e.g. a set of commands to copy-paste into a shell session); I suspect this may be instability in your dependencies' Git servers as Dulwich is in your partial stack trace. In addition, running the failing commands in full verbose mode and posting a **full** stack trace as mentioned in the template would be appreciated.

**Comment by DrawnWren** [comment]
Here's a relatively small pyproject.toml that fails repeatedly 
```
[tool.poetry]
name = "syncdb"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
gql = "^3.4.0"

aiobotocore = ">0.0.0"
botocore = ">0.0.0"
s3fs = ">0.0.0"
SQLAlchemy = "^1.4.41"
freqtrade = "^2022.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

**Comment by dimbleby** [comment]
That project works fine here, which suggests your problem is environmental, and local to you.

Since you say you're hitting issues on multiple machines and in docker builds, I speculate that something has changed about your network.  But there's really no way to tell from here.

Again, if you can provide a reproduction in a docker container, that might move things forwards.  Or perhaps we'll just learn that those problems also only reproduce at your end.

Meanwhile I see no poetry bug.

**Comment by DrawnWren** [comment]
I have no clue what this was. It resolved itself overnight without any intervention on our part.

**Comment by earonesty** [comment]
same issue.   i think it's a pypi problem, but poetry realllly ought to report the error better if possible.   retry settings, etc.
