### ISSUE TITLE
package name changed from version 1.1.4 to 1.2.2

### ISSUE THREAD

**Issue by idefixcert** [python-poetry/poetry#7045]
- **Poetry version**: Poetry (version 1.2.2)
- **Python version**: Python:  3.9.10
- **OS version and name**: macOS 12.6
- **pyproject.toml**: 
```
[tool.poetry]
name = "rtbrick-opsd"
stripped the rest
```

## Issue
if we do a `poetry build`
on poetry version 1.1.4 we got somewhat: `rtbrick-opsd-<version>.tar.gz`
but
on poetry version 1.2.2 we get somewhat: `rtbrick_opsd-<version>.tar.gz`

so the hyphens are replaced by underscores.

**Comment by dimbleby** [comment]
correct, per the python packaging specs and as implemented at https://github.com/python-poetry/poetry-core/pull/484

not a bug
