### ISSUE TITLE
tests/inspection runs slowly

### ISSUE THREAD

**Issue by fahaddd-git** [python-poetry/poetry#7053]
- **Poetry version**: 1.2.2
- **Python version**: 3.10.0
- **OS version and name**: Windows 10 Pro	10.0.19044 Build 19044 32bit
- **pyproject.toml**: [same from the poetry repo](https://github.com/python-poetry/poetry/blob/master/pyproject.toml)

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

Machine stats:  `Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz, 2712 Mhz, 2 Core(s), 4 Logical Processor(s)  16GB ram`

A number of the tests in `tests/inspection` are taking a ridiculously long amount of time to run locally.

![image](https://user-images.githubusercontent.com/66268023/202489576-2421dd64-d8dd-48c3-821b-e2b76f7a7466.png)

**Further profiling:**
To further illustrate this, profiling of the the cpu time and wall clock time for the test test [test_info_setup_complex_pep517_legacy](https://github.com/python-poetry/poetry/blob/master/tests/inspection/test_info.py#L222) shows a lot of time waiting is involved. 
![image](https://user-images.githubusercontent.com/66268023/202489344-7b03ca8b-15b7-488d-afd8-5d57e8365234.png)

**Call graph:**
I believe this is due to multiple calls to Python's `subprocess` which internally call the blocking `subprocess.Popen._communicate`.  Below is the call graph of the test [test_info_setup_complex_pep517_legacy](https://github.com/python-poetry/poetry/blob/master/tests/inspection/test_info.py#L222). 

![pycallgraph](https://user-images.githubusercontent.com/66268023/202485251-895fbebc-c9a6-44e4-9d6a-83a1f538f16a.png)

**Comment by neersighted** [comment]
`Popen._communicate` blocks on the pipe of the process being run -- so the issue is not the choice of method, but that an external process is blocking/"slow." More diagnosis would be needed to determine if the blocking in the external process is "legitimate" or avoidable.

This issue reads a bit like "this is slow on my machine, please fix it" -- do you plan to work on this? If not, I don't think this issue's current format is very helpful; I'd rather turn it into a meta-issue tracking slow tests in general, or replace it with such an issue, rather than fill the tracker up with more of these over time.

**Comment by Secrus** [comment]
To the person that stumbled upon this issue: if you want to contribute a performance improvement in that area of code, we would be happy to see it, but for now, we consider the test suite to be fast enough and the core team doesn't see a point in having this issue open.
