### ISSUE TITLE
Attempts to download win32 file on macOS

### ISSUE THREAD

**Issue by grant-boggess-swell** [python-poetry/poetry#7056]
- **Poetry version**: 1.2.2
- **Python version**: 3.10.8
- **OS version and name**: macOS 3.10.5
- **pyproject.toml**: https://gist.github.com/grant-boggess-swell/4a76466cf4940b3fbc429ece3c3f3250

- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

When attempting to add any package related to jupyter on macOS, poetry downloads and attempts to open a win32 whl file for pywin32. This causes two related problems. macOS wouldn't use pywin32 so it shouldn't be a dependency and when it does download the file, it is a win32 specific whl - which is what actually causes the error. This can be replicated by running poetry add jupyter, poetry add ipykernel or poetry add notebook as well as attempting to install any of these packages via pyproject.toml. For the sake of brevity, the full output is in the linked gist. I would say that this is a jupyter issue except that I've successfully installed these packages using pip on the same machine after I ran into this issue. In case it matters, this is occurring on an M1 mac. 

Thank you!

```PermissionError

  [Errno 1] Operation not permitted: '/var/folders/3p/88s577n92hl59hdtq8dcmtf40000gp/T/tmp4hn2zbs2/pywin32-305-cp310-cp310-win32.whl'

  at /opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/zipfile.py:1249 in __init__
      1245│                         'r+b': 'w+b', 'w+b': 'wb', 'x+b': 'xb'}
      1246│             filemode = modeDict[mode]
      1247│             while True:
      1248│                 try:
    → 1249│                     self.fp = io.open(file, filemode)
      1250│                 except OSError:
      1251│                     if filemode in modeDict:
      1252│                         filemode = modeDict[filemode]
      1253│                         continue
```
https://gist.github.com/grant-boggess-swell/03a8442c31741e9d20cf42a70781e293

**Comment by Secrus** [comment]
Please post the output as Gist or on other online services. Don't force people to download untrusted zip files (docx is a zip file)

**Comment by grant-boggess-swell** [comment]
> Please post the output as Gist or on other online services. Don't force people to download untrusted zip files (docx is a zip file)

Updated, thank you!

**Comment by dimbleby** [comment]
>  it is a win32 specific whl - which is what actually causes the error.

what makes you think so?  I don't see what part of the error message implies this.

poetry builds cross-platform lock files, the fact that you are running on macOS is mostly irrelevant.  poetry still has to figure out what the dependencies of pywin32 are so that it can produce a lock file that will work on windows.

**Comment by dimbleby** [comment]
looks like this is a common macos thing, I don't use macos myself but google has lots of hits about how to give applications permissions in `/var/folders`.

**Comment by grant-boggess-swell** [comment]
> > it is a win32 specific whl - which is what actually causes the error.
> 
> what makes you think so? I don't see what part of the error message implies this.
> 
> poetry builds cross-platform lock files, the fact that you are running on macOS is mostly irrelevant. poetry still has to figure out what the dependencies of pywin32 are so that it can produce a lock file that will work on windows.

The file it is attempting to open is 'pywin32-305-cp310-cp310-win32.whl'. When I download this file directly from PyPi and attempt to fh = open(filename) it fails with the same error. If I try to download and open the file ending in arm64 it works, which led me to believe that the wheels could only be opened by the system they were labeled with and for some reason the wrong file was being chosen.

**Comment by dimbleby** [comment]
Nope, it's completely normal for poetry to inspect wheels targeted at other platforms.

Sounds like you've done enough to show that this is indeed something more general with the configuration on your system: but since I don't use macos and this is not a poetry thing, I can't help more.

**Comment by dimbleby** [comment]
But do please leave a note when you figure it out, it might help the _next_ person...

**Comment by neersighted** [comment]
Wheels are zip files, and certainly, `open(2)` should work on them anywhere -- they're not magic, they're just files.

Is it possible you have some [endpoint security extension](https://developer.apple.com/documentation/endpointsecurity) running on your system and inspecting/blocking system calls?

**Comment by dimbleby** [comment]
no reason to suspect a poetry bug here, this might as well be closed
