### ISSUE TITLE
Wrong python timezone inside poetry shell

### ISSUE THREAD

**Issue by dflock** [python-poetry/poetry#7063]
- **Poetry version**: 1.2.2
- **Python version**: 3.10.8
- **OS version and name**: Ubuntu 22.04.1 LTS
- **pyproject.toml**: 

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

On my Ubuntu Linux system, the system timezone is correctly set to `America/Vancouver`:

```console
$ file /etc/localtime 
/etc/localtime: symbolic link to /usr/share/zoneinfo/America/Vancouver

$ date
Sat 19 Nov 21:27:04 PST 2022

$ date '+%Y-%m-%d %H:%M:%S%z'
2022-11-19 21:27:19-0800

$ date '+%Y-%m-%d %H:%M:%S%Z'
2022-11-19 21:27:30PST

$ which python
/usr/bin/python

$ python --version
Python 3.10.6

$ python -c "import time; print(time.tzname); print(time.localtime());"

('PST', 'PDT')
time.struct_time(tm_year=2022, tm_mon=11, tm_mday=19, tm_hour=21, tm_min=28, tm_sec=58, tm_wday=5, tm_yday=323, tm_isdst=0)
```

This is all correct and, as you can see, the system & python agree on the timezone.

However, _when inside a poetry shell_, python appears to think *its* timezone is UTC:

```console
$ poetry new poetry-demo
Created package poetry_demo in poetry-demo

$ cd poetry-demo/
$ cat pyproject.toml

[tool.poetry]
name = "poetry-demo"
version = "0.1.0"
description = ""
authors = ["Duncan Lock <duncan.lock@gmail.com>"]
readme = "README.md"
packages = [{include = "poetry_demo"}]

[tool.poetry.dependencies]
python = "^3.10"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

$ poetry debug info

Poetry
Version: 1.2.2
Python:  3.10.8

Virtualenv
Python:         3.10.8
Implementation: CPython
Path:           /home/duncan/.cache/pypoetry/virtualenvs/poetry-demo-PHf8FblR-py3.10
Executable:     /home/duncan/.cache/pypoetry/virtualenvs/poetry-demo-PHf8FblR-py3.10/bin/python
Valid:          True

System
Platform:   linux
OS:         posix
Python:     3.10.8
Path:       /home/linuxbrew/.linuxbrew/opt/python@3.10
Executable: /home/linuxbrew/.linuxbrew/opt/python@3.10/bin/python3.10

$ poetry shell

Spawning shell within /home/duncan/.cache/pypoetry/virtualenvs/poetry-demo-PHf8FblR-py3.10
. /home/duncan/.cache/pypoetry/virtualenvs/poetry-demo-PHf8FblR-py3.10/bin/activate
. /home/duncan/.cache/pypoetry/virtualenvs/poetry-demo-PHf8FblR-py3.10/bin/activate

$ which python
/home/duncan/.cache/pypoetry/virtualenvs/poetry-demo-PHf8FblR-py3.10/bin/python

$ python --version
Python 3.10.8

$ python -c "import time; print(time.tzname); print(time.localtime());"
('UTC', 'UTC')
time.struct_time(tm_year=2022, tm_mon=11, tm_mday=20, tm_hour=5, tm_min=31, tm_sec=47, tm_wday=6, tm_yday=324, tm_isdst=0)

$ python -c 'from datetime import datetime; print(datetime.utcnow()); print(datetime.now());'
2022-11-20 05:32:10.548122
2022-11-20 05:32:10.548163

$ date
Sat 19 Nov 21:35:00 PST 2022
```

So, the local system is in PDT/PST and both the system & python agree on this - but inside a poetry shell, the system is still in PST, but Python thinks it's UTC.

This system is running Python 3.10.8 & Ubuntu 22.04.1 LTS.

Am I misunderstanding something about how Pythons timezone stuff - or poetry shell works? What's going on? How do I get python's `time.tzname` to match the system timezone of `PST` when inside a poetry shell?

**Comment by dimbleby** [comment]
It seems unlikely that whatever is happening here is caused by poetry.

afaik the other thing that python uses to determine the timezone is the TZ environment variable, so you could check if anything interesting is happening with that.  Also I see that you are using different python versions inside and outside of the environment (3.10.8 vs 3.10.6) so maybe something changed there?

You're probably going to have to debug this one yourself: and if it is somehow poetry's fault come back and explain how!

**Comment by dflock** [comment]
I tried replicating this on a completely new Linux VM (rather than my rather old, many times upgraded desktop) - and everything worked properly - the timezone was correct both inside & outside the poetry shell.

None of the three Linux boxes I tried in on had the `$TZ` variable set at all, fwiw.

So, this does appear to be something subtly borked on my machine. Clues:

- Different python versions inside and outside the poetry shell (3.10.8 vs 3.10.6)
- poetry shell appears to activate twice

I will close this and leave a comment if I ever figure it out.

**Comment by dflock** [comment]
Turns out this was caused by Homebrew/linuxbrew.

It had installed its own versions of python as dependencies and poetry has picked up one of those, as you can see from the `poetry debug info`.

I removed Homebrew completely (it's Linux implementation has always felt like a bad idea to me, and this was enough for me to drop it). This broke poetry, so I uninstalled & reinstalled - and that fixed it.
