### ISSUE TITLE
Unable to upgrade to poetry version 1.2.2

### ISSUE THREAD

**Issue by jacky-lam** [python-poetry/poetry#7064]
- **Poetry version**: 1.2.2
- **Python version**: 3.9.5
- **OS version and name**: macOS 11.5.1 BigSur

- [ ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

When i try to upgrade poetry from my current version 1.1.13 to 1.2.2 by running the command `poetry self update` i get an error

```
poetry self update

Updating to 1.2.2

  RuntimeError

  Could not find poetry-1.2.2-darwin.sha256sum file

  at ~/.poetry/lib/poetry/console/commands/self/update.py:260 in _update
      256│         try:
      257│             r = urlopen(base_url + "/{}/{}".format(version, checksum))
      258│         except HTTPError as e:
      259│             if e.code == 404:
    → 260│                 raise RuntimeError("Could not find {} file".format(checksum))
      261│ 
      262│             raise
      263│ 
      264│         checksum = r.read().decode().strip()
```

This does not seem to be specific to my machine.

**Comment by dimbleby** [comment]
duplicate #6764 and probably others, you should upgrade by following the instructions on the poetry website

**Comment by dimbleby** [comment]
#6269, #6548, #6296. #6449, #5045, #5025, #4356, #6410, #5762, #5180, #4343, #4087
