### ISSUE TITLE
Cleo v1.0.0 is not compatible and breaks poetry

### ISSUE THREAD

**Issue by akshitkrnagpal** [python-poetry/poetry#7069]
- **Poetry version**: latest
- **Python version**: any
- **OS version and name**: any
- **pyproject.toml**: Not required

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

Cleo's latest release broke latest version of poetry. More specifically this change. https://github.com/python-poetry/cleo/pull/179 released in https://github.com/python-poetry/cleo/releases/tag/1.0.0.

Poetry uses `cleo = "^1.0.0a5"` which I guess satisfies `1.0.0` but now the error `cannot import name 'CleoException' from 'cleo.exceptions'` is being thrown.

PS - Sorry if it's a poorly written issue.

**Comment by akshitkrnagpal** [comment]
1.0.0 is yanked and 2.0.0 will be released. Closing this issue.

**Comment by neersighted** [comment]
From Discord:

> Cleo reached a major milestone today, with the release of the 1.0.0 version, which resolved a number of long-standing bugs, while dropping the dependency on clikit and achieving full type-checking.
>
> Unfortunately, to bring in fixes faster, Poetry had been depending on a pre-release version of Cleo. Breaking changes were made in-between releases related to typing and linting. Due to an oversight in our constraint strategy, we were using a >= range to depend on Cleo alpha versions (instead of pinning, which may have been more advisable). As such, recent versions of Poetry started to pull in Cleo 1.0.0, due to the >=1.0.0a5,<2.0.0 constraint.
>
> Cleo 1.0.0 has been yanked; please restart your CI jobs if you were affected by this broken release. 2.0.0 will be released shortly for consumption in (future versions of) Poetry; the major version bump will prevent this from repeating again.
