### ISSUE TITLE
Could not parse version constraint: mypy

### ISSUE THREAD

**Issue by alanwilter** [python-poetry/poetry#7071]
- **Poetry version**: 1.2.2
- **Python version**: Python 3.8.10
- **OS version and name**: Ubuntu 20.04.3 LTS
- **pyproject.toml**: offending line
```toml
[tool.poetry.group.dev.dependencies]
flake8 = "mypy"
``` 

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

Everything was working fine until `Poetry (version 1.2.0b3)`.

Since I have update to the latest poetry version (1.2.2) I started to see this error:

```
Could not parse version constraint: mypy
```

Every single time I try to use `poetry ...`. If I comment out the offending line in my `pyproject.toml`, then it will work.

But the point is, I don't know how to fix the offending line: `flake8 = "mypy"`

All my python projects has that and I don't even remember why it is as it is.

**Comment by Secrus** [comment]
Just as the message says, `flake8 = "mypy"` is not a valid dependency declaration. It won't work. You should change `"mypy"` to a valid `flake8` version.

**Comment by alanwilter** [comment]
I understand that and I did this change. I was trying to find out where that came from.

I've been reading about `flake8` and `pyproject.toml`. Perhaps what I'm looking for is a replacement for `flake8` that works with `pyproject.toml`, `black`, `mypy` and is supported by the community as the new way to go.

Is there such a thing?
