### ISSUE TITLE
Stuck at the starting HTTPS connection with pypi.org on Mac M1

### ISSUE THREAD

**Issue by TahirJalilov** [python-poetry/poetry#7076]
- **Poetry version**: 1.2.2
- **Python version**: 3.11.0
- **OS version and name**: macOS 13.0.1

- [x ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x ] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
poetry update stuck at the starting HTTPS connection with pypi.org

```
➜ poetry self update -vvv
Loading configuration file /Users/tahir/Library/Preferences/pypoetry/config.toml
Updating Poetry version ...

[keyring.backend] Loading KWallet
[keyring.backend] Loading SecretService
[keyring.backend] Loading Windows
[keyring.backend] Loading chainer
[keyring.backend] Loading libsecret
[keyring.backend] Loading macOS
Creating new session for pypi.org
[urllib3.connectionpool] Starting new HTTPS connection (1): pypi.org:443
[urllib3.connectionpool] https://pypi.org:443 "GET /simple/poetry/ HTTP/1.1" 304 0
```

**Comment by dimbleby** [comment]
duplicate #6030, #6906, #7010, #6526, #3352, and probably many others.

looking forward to 1.3.0 so that we can stop telling people this.

**Comment by TahirJalilov** [comment]
based on this reply https://github.com/python-poetry/poetry/issues/6526#issuecomment-1248073297 I tried 
```
poetry cache clear PyPI -all
poetry cache clear _default_cache --all
```
Now the poetry works properly
