### ISSUE TITLE
Allow to specify branch in local develop dependency

### ISSUE THREAD

**Issue by PierreSnell** [python-poetry/poetry#7077]
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request
When specifying a local dependency to be able to continue developing it at the same time (amazing feature <3 ), one can do (in poetry) 
`my_local_lib = {path = "../my_local_lib", extras=["my_super_extra"], develop=true}`

However, I'm developing my local lib on a branch... and it looks like poetry is taking the code from `main` and not `my_current_branch`. 

Is it possible to have something like git dependencies ? : 
`my_local_lib = {path = "../my_local_lib", extras=["my_super_extra"], develop=true, branch="my_current_branch"}` ? 

Thanks in advance for any help or feature. 

Have a great day.

**Comment by dimbleby** [comment]
No.

**Comment by neersighted** [comment]
Path dependencies are just that... paths, and not Git repositories. If you want a VCS dependency, you need to use a VCS dependency; deviating from this is not desirable as it changes the meaning of a dependency based on if a `.git` folder is present or not, and it breaks our ability to interoperate with other tools.

Basically what I'm saying is it's either or: Poetry can use the project at a path, or a Git repository, but we can't offer some sort of inbetween. An ask for `git+file://` might be interesting, but as it will require an absolute path you may or may not be interested.

**Comment by PierreSnell** [comment]
Hello @neersighted, thanks for the explanation. 

Indeed my question was more oriented toward a "Is it possible to have a git+file://" but I might have not conveyed it that way though. 

I'm fine with absolute paths, and the "git+file://", with a "develop" option would be exactly what I'm looking for. 
Is there any way I can use the actual "git+" to accomplish that ? 

Else, I understand that the feature is outside the main workflow. 
Thanks a lot for your answer, have a nice day.
