### ISSUE TITLE
[Bug Report] Invalid Poetry Virtualenvs with python as a symbolic link

### ISSUE THREAD

**Issue by Dragon1573** [python-poetry/poetry#7085]
## Environments

- **Poetry version**: `v1.2.2`
- **Python version**: `v3.10.6`
- **OS version and name**: `Ubuntu LTS 22.10 Kinetic` in WSL2 on `Microsoft Windows 11 Professional 22H2 (22621.819)`
- **pyproject.toml**: [GitHub Gists](https://gist.github.com/Dragon1573/66e400caa8313465620d8bde296faa21)

<details>
<summary>Console output of the above informations</summary>

```text
➜  School poetry --version
Poetry (version 1.2.2)
➜  School poetry debug info

Poetry
Version: 1.2.2
Python:  3.10.6

Virtualenv
Python:         3.10.7
Implementation: CPython
Path:           /home/dragon1573/Code/School/.venv
Executable:     python
Valid:          False

System
Platform:   linux
OS:         posix
Python:     3.10.7
Path:       /usr
Executable: /usr/bin/python3.10
➜  School wslfetch

               .-/+oossssoo+/-.               Windows Subsystem for Linux (WSL2)
           `:+ssssssssssssssssss+:`           dragon1573@MateBook-X-Pro
         -+ssssssssssssssssssyyssss+-         Build: 22621
       .ossssssssssssssssssdMMMNysssso.       Branch: ni_release
      /ssssssssssshdmmNNmmyNMMMMhssssss/      Release: Ubuntu 22.10
     +ssssssssshmydMMMMMMMNddddyssssssss+     Kernel: Linux 5.15.74.2-microsoft-standard-WSL2
    /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Uptime: 1d 21h 58m
   .ssssssssdMMMNhsssssssssshNMMMdssssssss.
   +sssshhhyNMMNyssssssssssssyNMMMysssssss+
   ossyNMMMNyMMhsssssssssssssshmmmhssssssso
   ossyNMMMNyMMhsssssssssssssshmmmhssssssso
   +sssshhhyNMMNyssssssssssssyNMMMysssssss+
   .ssssssssdMMMNhsssssssssshNMMMdssssssss.
    /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/
     +sssssssssdmydMMMMMMMMddddyssssssss+
      /ssssssssssshdmNNNNmyNMMMMhssssss/
       .ossssssssssssssssssdMMMNysssso.
         -+sssssssssssssssssyyyssss+-
           `:+ssssssssssssssssss+:`
               .-/+oossssoo+/-.

➜  School lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.10
Release:        22.10
Codename:       kinetic
```

</details>

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

<details>
<summary>Output logs from debug mode</summary>

```text
➜  School poetry env use 3.10.7 -vvv
Loading configuration file /home/dragon1573/.config/pypoetry/config.toml
Adding repository bfsu (https://mirrors.bfsu.edu.cn/pypi/web/simple) and setting it as the default one
Deactivating the PyPI repository
Creating virtualenv school in /home/dragon1573/Code/School/.venv
Using virtualenv: /home/dragon1573/Code/School/.venv
```

</details>

## Issue

Poetry create an **invalid** virtual environment inside project. `.venv/local/bin/python` is a **symbolic link** to system intepreter, not an executable "isolated" from the system one.

![image](https://user-images.githubusercontent.com/49941141/203549375-7fcb6a94-34e9-43c5-92c8-4a9913cb36a9.png)

<details>
<summary>Copied outputs from console</summary>

```text
➜  School poetry debug info

Poetry
Version: 1.2.2
Python:  3.10.6

Virtualenv
Python:         3.10.7
Implementation: CPython
Path:           /home/dragon1573/Code/School/.venv
Executable:     python
Valid:          False

System
Platform:   linux
OS:         posix
Python:     3.10.7
Path:       /usr
Executable: /usr/bin/python3.10
➜  School file .venv/local/bin/*
.venv/local/bin/activate:         ASCII text
.venv/local/bin/activate.csh:     ASCII text, with very long lines (316)
.venv/local/bin/activate.fish:    ASCII text
.venv/local/bin/activate.nu:      ASCII text
.venv/local/bin/activate.ps1:     ASCII text
.venv/local/bin/activate_this.py: Python script, ASCII text executable
.venv/local/bin/deactivate.nu:    ASCII text
.venv/local/bin/pip:              a /home/dragon1573/Code/School/.venv/local/bin/python script, ASCII text executable
.venv/local/bin/pip-3.10:         a /home/dragon1573/Code/School/.venv/local/bin/python script, ASCII text executable
.venv/local/bin/pip3:             a /home/dragon1573/Code/School/.venv/local/bin/python script, ASCII text executable
.venv/local/bin/pip3.10:          a /home/dragon1573/Code/School/.venv/local/bin/python script, ASCII text executable
.venv/local/bin/python:           symbolic link to /usr/bin/python3.10
.venv/local/bin/python3:          symbolic link to python
.venv/local/bin/python3.10:       symbolic link to python
.venv/local/bin/wheel:            a /home/dragon1573/Code/School/.venv/local/bin/python script, ASCII text executable
.venv/local/bin/wheel-3.10:       a /home/dragon1573/Code/School/.venv/local/bin/python script, ASCII text executable
.venv/local/bin/wheel3:           a /home/dragon1573/Code/School/.venv/local/bin/python script, ASCII text executable
.venv/local/bin/wheel3.10:        a /home/dragon1573/Code/School/.venv/local/bin/python script, ASCII text executable
➜  School
```

</details>

**Comment by dimbleby** [comment]
the issue is not the symlink, that's completely normal.

you seem somehow to have created some confusion about where the virtual environment is

- `poetry env info` shows it in `/home/dragon1573/Code/School/.venv` (and not a subdirectory of that, which is surprising)
- you are showing a virtual environment in `.venv/local`

I don't know how you've got into this state, but that's the mess you'll need to untangle

**Comment by Dragon1573** [comment]
Oops?! Sorry for that ...

I realized that there's no `.venv/bin/` folder when new Poetry projects created. I research the issues and find a walkaround in https://github.com/python-poetry/poetry/issues/4597#issuecomment-1233290435.

It said that there's something different on Debian/Ubuntu, which `pip list` will display a `python-debian` instead of official `python`.

Thanks for your tips! This issue can be closed (or maybe deletable?)

**Comment by neersighted** [comment]
Duplicate #6371, the environment is invalid, it is a Ubuntu/Debian bug.
