### ISSUE TITLE
Poetry cannot install `ansible-lint@6.9.0`

### ISSUE THREAD

**Issue by davidmehren** [python-poetry/poetry#7112]
- **Poetry version**: 1.2.2
- **Python version**: 3.11
- **OS version and name**: Fedora 37
- **pyproject.toml**: n/a

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
Poetry cannot install `ansible-lint@6.9.0`. To reproduce, create a new project with `poetry init` and try to add the package:
```
poetry add ansible-lint@6.9.0
Creating virtualenv repro-IHV6d_qa-py3.11 in /home/david/.cache/pypoetry/virtualenvs

Updating dependencies
Resolving dependencies... (0.7s)
Resolving dependencies... (0.8s)
Because ansible-lint (6.9.0) depends on will-not-work-on-windows-try-from-wsl-instead (*) which doesn't match any versions, ansible-lint is forbidden.
So, because repro depends on ansible-lint (6.9.0), version solving failed.
```

This has been reported (https://github.com/ansible/ansible-lint/issues/2730) over at ansible-lint, but closed as a poetry issue, hence I'm reporting it here again.

I'm guessing that Poetry does not correctly understand the line `will-not-work-on-windows-try-from-wsl-instead; platform_system=="Windows"` in ansible-lints [setup.cfg](https://github.com/ansible/ansible-lint/blob/main/setup.cfg#L66) and tries to install the nonexisting dependency even when not running on Windows.

**Comment by finswimmer** [comment]
Hello @davidmehren,

what `ansible-lint` is doing here is unusual and is a problem for any tool that produces an universal lock file. I answered in the issue you've linked. Let's see what happens.

fin swimmer

**Comment by finswimmer** [comment]
Nice workaround @radoering :+1:

**Comment by dimbleby** [comment]
poetry is behaving exactly correctly, and radoering has offered a workaround that should be completely satisfactory.  This can be closed.
