### ISSUE TITLE
Poetry doesn't correctly normalise the package name for the wheel data section

### ISSUE THREAD

**Issue by robtaylor** [python-poetry/poetry#7117]
- **Poetry version**: git head dcd48c8d, with poetry-core head d98aa6e4
- **Python version**:  3.9.15
- **OS version and name**: Ubuntu 20.04.3 LTS
- **pyproject.toml**: https://github.com/python-poetry/poetry-core/blob/fix-6197/tests/masonry/builders/fixtures/script_reference_file/pyproject.toml

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

When building a wheel, the name of the data section should be {distribution}-{version}.data, where {distribution} is the [PEP 503](https://peps.python.org/pep-0503/) normalisation followed by replacing - with _.

See [Binary distribution format](https://packaging.python.org/en/latest/specifications/binary-distribution-format/#escaping-and-unicode)

Currently the data section is using _package.name rather than distribution_version(_package.name) (https://github.com/python-poetry/poetry-core/blob/d98aa6e49f614f7631667da3144d7b291c7e7889/src/poetry/core/masonry/builders/wheel.py#L310)

**Comment by neersighted** [comment]
Please provide the versions you have tested with, as well as examples of the incorrect output, what you expect the correct output to be, and what commands/tools can be used to reproduce.

This sounds like a chore, but will get your issue looked at in a more timely fashion and ensure that those who try to help you/reproduce it can do so quickly and consistently.

**Comment by neersighted** [comment]
A pyproject.toml along with a sequence of commands you are using to build wheels, and then examples of the resulting filenames, plus what you would consider to be the correct filenames, would illustrate your issue and make it unambiguous what is wrong.

**Comment by dimbleby** [comment]
It would probably have been worth mentioning that you've already provided a pull request including unit test changes...  

https://github.com/python-poetry/poetry-core/pull/532

**Comment by robtaylor** [comment]
Thanks David!
