### ISSUE TITLE
crashtest version conflict

### ISSUE THREAD

**Issue by danielhoherd** [python-poetry/poetry#7120]
- **Poetry version**: 1.2.2
- **Python version**: 3.10.6, 3.10.8
- **OS version and name**: ubuntu 22.04, macOS 13
- **pyproject.toml**: N/A

- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

With `poetry` listed in my `requirements.in` file, I see the following error:

```
pip-compile --quiet --allow-unsafe --upgrade requirements.in
Could not find a version that matches crashtest<0.4.0,<0.5.0,>=0.3.0,>=0.4.1 (from poetry==1.2.2->-r requirements.in (line 13))
Tried: 0.3.0, 0.3.0, 0.3.1, 0.3.1, 0.4.0, 0.4.0, 0.4.1, 0.4.1
There are incompatible versions in the resolved dependencies:
  crashtest<0.5.0,>=0.4.1 (from cleo==1.0.0->poetry==1.2.2->-r requirements.in (line 13))
  crashtest<0.4.0,>=0.3.0 (from poetry==1.2.2->-r requirements.in (line 13))
```

I think this is due to the two following constraints, which are incompatible:
- https://github.com/python-poetry/poetry/blob/1.2.2/pyproject.toml#L53
- https://github.com/python-poetry/cleo/blob/2.0.1/pyproject.toml#L35

FWIW, when I `pip install poetry` I end up with `crashtest-0.3.1`

**Comment by neersighted** [comment]
`pip-compile` is trying to create a nonsense solution by pulling in the yanked `cleo==1.0.0`. I don't think there's a bug in anything but pip-tools here, since they don't support [PEP 592](https://peps.python.org/pep-0592/) they're trying to solve a nonsense solution. You might be able to coerce it into doing the right thing by also specifying `cleo==1.0.0a5`.

**Comment by danielhoherd** [comment]
[I see that cleo 1.0.0 is yanked](https://pypi.org/project/cleo/#history), and that it was the only non-pre-release version of cleo 1.x. Doing `pip-compile --pre` selects the non-yanked cleo 1.0.0a5. I think you're right that this is an incorrect behavior in pip-compile.
