### ISSUE TITLE
Uninstaller for deprecated version not working

### ISSUE THREAD

**Issue by aaronwolmutt** [python-poetry/poetry#7134]
- **Poetry version**: 1.1.13
- **Python version**: 3.9.15
- **OS version and name**: macOS 11.6 BigSur
- **pyproject.toml**: 

- [ ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [ X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ X] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

Used 
```
curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3 - --uninstall
```

Which only prints

```
# We are sorry to see you go!

This will uninstall Poetry.

It will remove the `poetry` command from Poetry's bin directory, located at:

$HOME/.poetry/bin

This will also remove Poetry from your system's PATH.
```
The script does not uninstall poetry, when i rerun
```
poetry --version
```
I get 
```
Poetry version 1.1.13
```
When running

```
where poetry
```

I still get
```
/usr/local/bin/poetry
```

**Comment by neersighted** [comment]
Not a bug; as the installer explains, you are only uninstalling the copy in your user directory managed by the installer. `/usr/local/bin` is managed by some system-level package manager; given you are on macOS, this should be Homebrew. `brew uninstall poetry` should uninstall the extra copy of Poetry.

`which -a <command>` is a helpful way to find all copies of a command in the PATH, incidentally.

**Comment by aaronwolmutt** [comment]
Yep - I've previously installed poetry with homebrew. I've tried uninstalling python with homebrew, and the copy still exists. For now - I'll probably just switch over to pyenv on my system but thought I'd post.

**Comment by neersighted** [comment]
That's not a Poetry issue; I'd first explicitly uninstall Poetry, and if that doesn't work, please reach out to the Homebrew team. That being said, I suspect you performed `pip install poetry` instead of `brew install poetry` at some point, if Homebrew didn't clear it out. Also consider that the Python formula is versioned (e.g. `python@3.6`) and Homebrew moves the 'unversioned' marker to their default version.

**Comment by aaronwolmutt** [comment]
That may be what I did on my system. I was able to complete uninstallation with brew cleanup, and am now install the latest version of poetry on my system. Thanks I'm going to close this.
