### ISSUE TITLE
`poetry install` gets stuck indefinitely if the same private repository (Google Artifac Registry) is configured as extra-index-url in pip.conf

### ISSUE THREAD

**Issue by jacek-jablonski** [python-poetry/poetry#7144]
- **Poetry version**: 1.2.2
- **Python version**: 3.10.4
- **OS version and name**: macOS 13.0.1
- **pyproject.toml**: https://gist.github.com/jacek-jablonski/3c278b7ff42800a43ac10eb1da7c2343

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

Hi,
I have noticed a strange behaviour when configuring Google Artifact Registry with python repository:
When the repository is configured in `pyproject.toml` and is not configured in `pip.conf`, everything works fine. `poetry install` works in reasonable time.
However, when the repository is configured in `pyproject.toml` and also in `pip.conf`:
```
[global]
timeout = 60
extra-index-url = https://europe-west4-python.pkg.dev/xxx/python/simple/
```
then `poetry install` never gets finished. There are no errors, just the command never completes.

I've tried clearing poetry and pip cache, but nothing helps. Configuring extra-index-url of this repo in `pip.conf` causes `poetry install` to never complete.

**Comment by dimbleby** [comment]
#6531

**Comment by neersighted** [comment]
Closed as already resolved.
