### ISSUE TITLE
`pip install` Python 3.11: `ERROR: Failed building wheel for xattr`

### ISSUE THREAD

**Issue by joeflack4** [python-poetry/poetry#7145]
- **Poetry version**: (not installed yet)
- **Python version**: 3.11
- **OS version and name**: 11.4
- **pyproject.toml**: [](https://gist.github.com/joeflack4/99960f1dbb986fd6293f1eed5e11e80d)

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
I try to do `pip install poetry` on Python 3.11, but it fails.

### Error
Short err: `ERROR: Failed building wheel for xattr`
Log: [poetry-pip-fail.txt](https://github.com/python-poetry/poetry/files/10158237/poetry-pip-fail.txt)

**Comment by dimbleby** [comment]
Not much poetry can do about this - did you ask at xattr?

**Comment by joeflack4** [comment]
You're right. I can install xattr 0.10.0 on Python 3.11 but not 0.9.9. That's what my project needs but it fails on both Poetry and normal pip. I'll use a different version of Python.
