### ISSUE TITLE
src folder is not being included in site-packages/project.pth

### ISSUE THREAD

**Issue by fabiobatalha** [python-poetry/poetry#7151]
- **Poetry version**:  1.2.2
- **Python version**: 3.8
- **OS version and name**: Ubuntu 22.04
- **pyproject.toml**:  https://gist.github.com/fabiobatalha/2d50bf9ce50e16430ae60c563db8863c

- [ * ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [  * ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ * ] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [ * ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

![Screenshot from 2022-12-06 15-55-07](https://user-images.githubusercontent.com/504142/206021961-15e5ff1a-7f42-4f60-a86b-9beb3dfa086f.png)

I'm not sure if it is a bug, but as displayed in the image, the path inside the xconverter.pth file is not including the source folder "src".

I'm using poetry in other projects, and it is first time it happens, the only difference in my experience for the other projects is:

* In this project I'm using a different project name from the main project module.
  * project-name : xconverter
  * project-module : converter

For this reason, I included in the pyproject.toml the **packages** configuration.

```
packages = [
  { include = "src/converter" }
] 
``` 

Everything seems to work when manually changing the path in xconverter.pth to /home/fabiobatalha/Work/converter/src

But it's sure it is not the solution because `poetry install` will replace again the path to /home/fabiobatalha/Work/converter.

**Comment by neersighted** [comment]
Not a bug, you need to use `{ include = "converter", from = "src" }`.

**Comment by fabiobatalha** [comment]
voilà.... thank you @neersighted
