### ISSUE TITLE
Running multiple `poetry install` in parallel causes race condition of packages

### ISSUE THREAD

**Issue by kota65535** [python-poetry/poetry#7154]
- **Poetry version**: 1.2.2
- **Python version**: 3.10.8
- **OS version and name**: macOS
- **pyproject.toml**:

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

I'm working on monorepo containing 5 poetry projects. My script executes `poetry install` in parallel to build these projects simultaneously, which causes race condition in the cached packages as shown below.

```
  RuntimeError

  Hash for pyarrow (10.0.1) from archive pyarrow-10.0.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl not found in known hashes (was: sha256:11b327120e24a84235dae756a42903b4c3455add50f37743389b35c5825916d3)

  at /opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/poetry/installation/executor.py:681 in _validate_archive_hash
      677│         archive_hash: str = "sha256:" + file_dep.hash()
      678│         known_hashes = {f["hash"] for f in package.files}
      679│ 
      680│         if archive_hash not in known_hashes:
    → 681│             raise RuntimeError(
      682│                 f"Hash for {package} from archive {archive.name} not found in"
      683│                 f" known hashes (was: {archive_hash})"
      684│             )
      685│ 
```

I tried `--no-cache` option but in vein. It seems conflicted packages are in `${cache-dir}/artifact`, not in `${cache-dir}/cache`.

**Comment by neersighted** [comment]
Duplicate #5142, fixed in (the eminent) 1.3.0.
