### ISSUE TITLE
Poetry Installation sometimes fails due to ERROR: Could not install packages due to an OSError: [WinError 32] The process cannot access the file because it is being used by another process

### ISSUE THREAD

**Issue by tomaskovalcik** [python-poetry/poetry#7162]
- **Poetry version**: 1.2.2
- **Python version**: 3.9.0
- **OS version and name**: Windows Server 2019 
- **pyproject.toml**: N/A

- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
Poetry installation fails from time to time in a non-deterministic way. I am running it in a pipeline and usually just a simple re-run of the stage resolves the issue and the poetry installation finishes successfully.

**The error: ERROR: Could not install packages due to an OSError: [WinError 32] The process cannot access the file because it is being used by another process**

See the rest of the output from a installation.

CalledProcessError

  Command 'c:\python39\python.exe -m pip install --disable-pip-version-check --prefix c:\python39 --no-deps C:\Users\ContainerAdministrator\AppData\Local\pypoetry\Cache\artifacts\59\da\ed\977af2af434f6b01b1334856fcc428d078560e9175d375721a68f924a3\psycopg2_binary-2.9.3-cp39-cp39-win_amd64.whl' returned non-zero exit status 1.

  at c:\python39\lib\subprocess.py:524 in run
       520|             # We don't call process.wait() as .__exit__ does that for us.
       521|             raise
       522|         retcode = process.poll()
       523|         if check and retcode:
    >  524|             raise CalledProcessError(retcode, process.args,
       525|                                      output=stdout, stderr=stderr)
       526|     return CompletedProcess(process.args, retcode, stdout, stderr)
       527| 
       528| 

The following error occurred when trying to handle this error:

  EnvCommandError

  Command c:\python39\python.exe -m pip install --disable-pip-version-check --prefix c:\python39 --no-deps C:\Users\ContainerAdministrator\AppData\Local\pypoetry\Cache\artifacts\59\da\ed\977af2af434f6b01b1334856fcc428d078560e9175d375721a68f924a3\psycopg2_binary-2.9.3-cp39-cp39-win_amd64.whl errored with the following return code 1, and output: 
  Processing c:\users\containeradministrator\appdata\local\pypoetry\cache\artifacts\59\da\ed\977af2af434f6b01b1334856fcc428d078560e9175d375721a68f924a3\psycopg2_binary-2.9.3-cp39-cp39-win_amd64.whl

  Installing collected packages: psycopg2-binary

  ERROR: Could not install packages due to an OSError: [WinError 32] The process cannot access the file because it is being used by another process: 'c:\\python39\\Lib\\site-packages\\psycopg2\\_psycopg.cp39-win_amd64.pyd'

  Consider using the `--user` option or check the permissions.

  
  at c:\python39\lib\site-packages\poetry\utils\env.py:1476 in _run
      1472|                 output = subprocess.check_output(
      1473|                     command, stderr=subprocess.STDOUT, env=env, **kwargs
      1474|                 )
      1475|         except CalledProcessError as e:
    > 1476|             raise EnvCommandError(e, input=input_)
      1477| 
      1478|         return decode(output)
      1479| 
      1480|     def execute(self, bin: str, *args: str, **kwargs: Any) -> int:

The following error occurred when trying to handle this error:

  PoetryException

  Failed to install C:/Users/ContainerAdministrator/AppData/Local/pypoetry/Cache/artifacts/59/da/ed/977af2af434f6b01b1334856fcc428d078560e9175d375721a68f924a3/psycopg2_binary-2.9.3-cp39-cp39-win_amd64.whl

  at c:\python39\lib\site-packages\poetry\utils\pip.py:51 in pip_install
       47| 
       48|     try:
       49|         return environment.run_pip(*args)
       50|     except EnvCommandError as e:
    >  51|         raise PoetryException(f"Failed to install {path.as_posix()}") from e

The code is running inside of a container running Windows Server 2019. The poetry is being installed with **pip install poetry**

Any help will be appreciated.

**Comment by dimbleby** [comment]
https://github.com/python-poetry/poetry/commit/b2e20458f85b7bea231faa4fad32099952e074f2

**Comment by neersighted** [comment]
Don't use Python 3.9, manually restrict your versions, or wait for 1.3; this is due to a unforeseen interaction between multiple moving pieces on your machine and we will have a mitigation for it in the next release.

**Comment by tomaskovalcik** [comment]
Just reporting the new 1.3 version seems not to resolve the issue. I will try to fix the virtualenv version as suggested.

**Comment by eKerney** [comment]
Same occurs when using:
poetry self update
Updating poetry (1.3.2 -> 1.4.0)
