### ISSUE TITLE
Trove classifiers prefixed with "Private ::" fail poetry check

### ISSUE THREAD

**Issue by sethfischer** [python-poetry/poetry#7167]
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request

[pypi.org recommends](https://pypi.org/classifiers/):

> To prevent a package from being uploaded to PyPI, use the special "Private :: Do Not Upload" classifier. PyPI will always reject packages with classifiers beginning with "Private ::".

The same recommendation is also published on [packaging.python.org](https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#classifiers).

When validating a `pyproject.toml` file with the following, `poetry check` will fail.

```toml
classifiers = [
    "Private :: Do not Upload",  # Prevent uploading to PyPI
]
```

Error message:
```
Error: Unrecognized classifiers: ['Private :: Do not Upload'].
```

This is correct behaviour for projects that are intended to be uploaded to PyPI. 

However, there are projects that are not intended to be uploaded to PyPI and follow the above recommendation. How should those projects validate their `pyproject.toml`?

### Suggestions

1. Would it be reasonable to add an option such as `--allow-private-classifiers` to `poetry check`? This option could allow classifiers with the prefix "Private ::".
2. See #1537 which discusses a number of alternatives to `"Private :: Do not Upload"`. Possibly one of these alternatives could be used as a flag which, if present, adds the `"Private :: Do not Upload"` classifier to the built package.

**Comment by johnthagen** [comment]
This is implemented here:

- https://github.com/python-poetry/poetry/blob/master/src/poetry/console/commands/check.py#L12

The current valid trove classifier list is taken from a PyPA third party library:

- https://github.com/pypa/trove-classifiers/blob/main/src/trove_classifiers/__init__.py#L4

> Would it be reasonable to add an option such as `--allow-private-classifiers` to `poetry check`? 

Given that this is the prescribed classifier to use, I don't think any special flag should be needed to allow this.

Should probably filter out any `unrecognized` here that start with `Private ::`

- https://github.com/python-poetry/poetry/blob/master/src/poetry/console/commands/check.py#L33
