### ISSUE TITLE
when supplying multiple url with non intersecting markers, poetry downloads all of them

### ISSUE THREAD

**Issue by chanansh** [python-poetry/poetry#7176]
- **Poetry version**: 1.3.0
- **Python version**: 3.10.6
- **OS version and name**: 
- **pyproject.toml**: https://gist.github.com/chanansh/bb93ee7438d6d71f8b21fea65c9aa765 

## Issue

I have used markers to support torch installation on different platforms:
```
torch = [
{markers = "sys_platform == 'macos'", url = "https://download.pytorch.org/whl/cpu/torch-1.13.0-cp310-none-macosx_11_0_arm64.whl"},
{markers = "sys_platform == 'linux' and platform_machine == 'arm64'", url="https://download.pytorch.org/whl/torch-1.13.0-cp310-cp310-manylinux2014_aarch64.whl"},
{markers = "sys_platform == 'linux' and platform_machine == 'x86_64'", url="https://download.pytorch.org/whl/cpu/torch-1.13.0%2Bcpu-cp310-cp310-linux_x86_64.whl"}]

```

However, when I do `poetry install` what happens is that all of them get downloaded, albeit only one of them is actually used. It seems like the condition logic is run only AFTER the downloads.

```
[urllib3.connectionpool] Starting new HTTPS connection (1): download.pytorch.org:443
[urllib3.connectionpool] https://download.pytorch.org:443 "GET /whl/cpu/torch-1.13.0-cp310-none-macosx_11_0_arm64.whl HTTP/1.1" 200 55694260
[urllib3.connectionpool] Starting new HTTPS connection (1): download.pytorch.org:443
[urllib3.connectionpool] https://download.pytorch.org:443 "GET /whl/torch-1.13.0-cp310-cp310-manylinux2014_aarch64.whl HTTP/1.1" 200 73237944
[urllib3.connectionpool] Starting new HTTPS connection (1): download.pytorch.org:443
[urllib3.connectionpool] https://download.pytorch.org:443 "GET /whl/cpu/torch-1.13.0%2Bcpu-cp310-cp310-linux_x86_64.whl HTTP/1.1" 200 198532501
```

Finally it installs only the correct one:
>  • Installing torch (1.13.0+cpu https://download.pytorch.org/whl/cpu/torch-1.13.0%2Bcpu-cp310-cp310-linux_x86_64.whl): Installing...

**Comment by neersighted** [comment]
Not a bug; this is by design. Poetry must gather all URLs in order to lock them (see #7121 for a recent change where we save the hash).

Note that the wheels will be fetched any time locking is performed, see #2415.
