### ISSUE TITLE
Poetry is much slower to install dependencies in containers

### ISSUE THREAD

**Issue by Hoid** [python-poetry/poetry#7183]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
Poetry version: 1.3.1
Python version: 3.10.8
OS version and name: MacOS Ventura 13.0.1 (issue also present on previous Mac version, I just upgraded yesterday and it's still an issue)
pyproject.toml: https://gist.github.com/Hoid/c188de0db19a56f024397688a5a1ec3c

For some reason, it takes much longer to run `poetry install` while building a docker container than freshly in my development environment. 

Here's how long it takes to run `time poetry install` after running `poetry env remove --all` and `poetry cache clear _default_cache --all`
```
poetry install  34.96s user 12.15s system 329% cpu 14.285 total
```

And here's how long it takes to run inside the Dockerfile (around 2 and a half minutes)
<img width="1265" alt="image" src="https://user-images.githubusercontent.com/15349440/207075632-b2567f2d-0154-4c5a-ad98-2eae0d74c0af.png">

The only difference that I can think of is that when running `poetry install` inside the Dockerfile, it's already based off of another image that contains some of the packages already that need to be upgraded, and perhaps Poetry is slower at upgrading packages than installing them from scratch. Here's how many installs there are compared to upgrades:
```
#0 8.341 Package operations: 44 installs, 53 updates, 0 removals
```

Here's what the first part of the install looks like in the container

```
#0 8.348   • Updating certifi (2021.5.30 -> 2022.12.7)
#0 8.351   • Updating charset-normalizer (2.0.0 /home/conda/feedstock_root/build_artifacts/charset-normalizer_1626371162869/work -> 2.1.1)
#0 8.354   • Updating idna (3.1 /home/conda/feedstock_root/build_artifacts/idna_1609836280497/work -> 3.4)
#0 8.356   • Installing pyasn1 (0.4.8)
#0 8.358   • Updating six (1.16.0 /home/conda/feedstock_root/build_artifacts/six_1620240208055/work -> 1.16.0)
#0 8.360   • Updating urllib3 (1.26.6 /home/conda/feedstock_root/build_artifacts/urllib3_1624634538755/work -> 1.26.13)
#0 16.15   • Installing asttokens (2.2.1)
#0 16.15   • Updating attrs (21.2.0 /home/conda/feedstock_root/build_artifacts/attrs_1620387926260/work -> 22.1.0)
#0 16.16   • Installing cachetools (5.2.0)
#0 16.16   • Installing executing (1.2.0)
#0 16.18   • Updating markupsafe (2.0.1 /home/conda/feedstock_root/build_artifacts/markupsafe_1621455668600/work -> 2.1.1)
#0 16.18   • Updating oauthlib (3.1.1 /home/conda/feedstock_root/build_artifacts/oauthlib_1622563202229/work -> 3.2.2)
#0 16.19   • Installing mdurl (0.1.2)
...
```

Note that while I'm using the `--no-interaction --no-ansi --no-root` flags in the Dockerfile, I've tried both taking those out and using them in my regular install in the terminal, neither of which changed the amount of time each took. I've also tried _enabling_ virtual environments inside the container build instead of disabling them, but that didn't decrease the install time either. 

Any ideas what might be causing this? I also tried this on 1.2.2 and had the same issue (although 1.3.1 did decrease the install time by around 5 seconds in the container).

**Comment by neersighted** [comment]
Are you sure the same amount of resources are available to the Docker Desktop VM? Are you comparing a cold artifact cache (`poetry config cache-dir`) in both instances? Are you running an x86_64 image on an x86_64 Mac, or are you using an ARM Mac?

Pro-tip: You can use a buildkit cache mount to preserve the artifacts cache in your Docker build.

**Comment by Hoid** [comment]
My Docker Desktop VM is allowed 4 CPUs, 6GB of RAM, and 1GB of Swap memory. I've tried increasing that to 6 CPUs, 16GB RAM before and that reduced the time to install to 2 minutes from 2.5, but that's pretty far from the 35 seconds it takes outside of the Dockerfile. I am using an ARM Mac, but I'm not trying to build an x86_64 image with it, which I imagine would take longer naturally, I'm just letting it it build with its normal architecture. 

I'm not sure about the `cache-dir/artifacts`. I'm running `poetry cache clear _default_cache --all` and making sure all virtual envs are destroyed before installing locally. Should I just `rm -rf` that `artifacts` directory first before each install?

**Comment by neersighted** [comment]
There is no need to delete it, however, you are not comparing apples to apples if you have an already warm artifacts cache.

Also since we're talking different platforms, there is a non-zero chance you are compiling Linux ARM wheels inside your container, as they are a lot less available than macOS ARM wheels. Are you sure that no compilation is taking place?

Overall there is so much surface area for differences here across platforms that I'm not sure we can make any valid comparisons.

**Comment by Hoid** [comment]
Fair. Is there any way to run an apples to apples test?

**Comment by neersighted** [comment]
Well, you could provide your lock file for perusal to see if wheels are being used or if source builds are occurring (or run your install in verbose mode); the closest you'll get to 'apples to apples' is to run a VM as well resourced as your base machine, and try installing in the bare VM, and then installing in a container running inside that VM using the same base OS image.

**Comment by Hoid** [comment]
Understood. I might have time to do that soon but I'm not sure. Perhaps we can close this issue for now and I'd reopen it if I find evidence using that method?

**Comment by neersighted** [comment]
That's fine by me!
