### ISSUE TITLE
Poetry flagging whl as incompatible in compatible environment

### ISSUE THREAD

**Issue by rkrishnasanka** [python-poetry/poetry#7187]
- **Poetry version**:  1.1.14
- **Python version**: 3.8.10
- **OS version and name**: Ubuntu 20.04.5 LTS
- **pyproject.toml**: [toml](https://github.com/rkrishnasanka/DAFD/blob/master/pyproject.toml)

- [ ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

It seems like poetry is flagging the `pillow` wheel to be incompatible with the OS. However, when I install the dependencies using `pip`, there are no issues.

The excerpt below shows the error message:

```
 • Updating urllib3 (1.25.8 /usr/lib/python3/dist-packages -> 1.26.11)
  • Updating requests (2.22.0 /usr/lib/python3/dist-packages -> 2.28.1)
  • Updating six (1.14.0 /usr/lib/python3/dist-packages -> 1.16.0)
  • Installing pillow (9.2.0): Failed

  EnvCommandError

  Command ['/usr/bin/python3', '-m', 'pip', 'install', '--no-deps', 'file:///root/.cache/pypoetry/artifacts/d5/ef/90/d3e7af61c9a736d9ca32bd09c4fa0ada8c54eab7dbc5a7b137a28a1302/Pillow-9.2.0-cp38-cp38-manylinux_2_28_x86_64.whl'] errored with the following return code 1, and output: 
  ERROR: Pillow-9.2.0-cp38-cp38-manylinux_2_28_x86_64.whl is not a supported wheel on this platform.
  

  at /usr/local/lib/python3.8/dist-packages/poetry/utils/env.py:1195 in _run
      1191│                 output = subprocess.check_output(
      1192│                     cmd, stderr=subprocess.STDOUT, **kwargs
      1193│                 )
      1194│         except CalledProcessError as e:
    → 1195│             raise EnvCommandError(e, input=input_)
      1196│ 
      1197│         return decode(output)
      1198│ 
      1199│     def execute(self, bin, *args, **kwargs):
```

**Comment by neersighted** [comment]
Duplicate #7177, this is solved by upgrading pip in the target environment.
