### ISSUE TITLE
Regression: Poetry output no longer keeps full log in console with no verbosity, -v, nor -vv; -vvv does but has lots of extra output.

### ISSUE THREAD

**Issue by MarximusMaximus** [python-poetry/poetry#7189]
- **Poetry version**: Poetry (version 1.3.1)
- **Python version**: Python:  3.10.8
- **OS version and name**: macOS 12.6 21G115
- **pyproject.toml**: https://gist.github.com/MarximusMaximus/4cb0eaa2ab10cf0db56bcd938f80d989

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
Previously (v1.2.2 and lower), poetry would keep all output lines (even if they were modified) in the console (stdout). In version 1.3.1, lines get modified and then removed as poetry runs with no verbosity, -v, and -vv. Lines are kept if using -vvv BUT there is a lot of additional output. Suggesting that -v and/or -vv keep lines instead of removing them (instead of introducing an additional arg, environment flag, or verbosity level between current -vv and -vvv). Thank you.

Why do I want this?
Because users like to paste the console log at me and I need to know what happened. They'll often paste the console log at me even if I explicitly request the log files instead (which I tee out, so they keep all the output). For "simple" issues, having the console log being able to be kept would speed up turnaround time on support issues for me (b/c I wouldn't need to always label them as "Need More Info"). Thank you.

**Comment by neersighted** [comment]
Are you referring to 'fancy' output from the solver/installer? That's a Cleo change, but you can easily capture this output by making stdout not a tty (e.g. `poetry | cat`). For most users, feedback showing the program is working, but without 'spamming' their shell session is a big improvement.

**Comment by MarximusMaximus** [comment]
If it's not a tty, it appears that colored output gets lost. stdout is supposed to be the actual things that happened, which is why at least -vv should not delete things from it (heck, any -v level shouldn't imo). This is very strange and unique type of behavior for a console program outside of progress bars. It's clear that it's possible to disable it b/c -vvv does.

I disagree that this is a big improvement. All my users always want to know everything that is happening and be able to look back it as desired.

As is, it even removes prior stdout output from wrapper programs. Multiple regressions that is very anti-developer/anti-engineer imo.
