### ISSUE TITLE
Initializing poetry exits in `SecretStorage required`, regardless of SecretStorage already installed

### ISSUE THREAD

**Issue by anoduck** [python-poetry/poetry#7191]
### Discussed in https://github.com/orgs/python-poetry/discussions/7119

<div type='discussions-op-text'>

<sup>Originally posted by **anoduck** November 29, 2022</sup>
Decided to start discussion rather than submit a bug, because unsure the error received is related to a bug. Just trying to figure out what is going on with poetry in my instance.

Every time I attempt to initialize a new project with poetry, it ends with the output `SecretStorage required`. This is regardless of having the SecretStorage module installed or not. 

```
Enter the version constraint to require (or leave blank to use the latest version): 

SecretStorage required
```

Cache for poetry and pip have both been purged. Currently, SecretStorage has been installed through the system package management system. </div>

**Comment by dimbleby** [comment]
continuing the anagrammatic theme... #1917

**Comment by anoduck** [comment]
@dimbleby Thanks! That surely explains it.
