### ISSUE TITLE
Broken default source repository in all projects

### ISSUE THREAD

**Issue by amarion35** [python-poetry/poetry#7192]
- **Poetry version**: 1.2.2
- **Python version**: 3.8.7
- **OS version and name**: Ubuntu 20.04.4 in WSL
- **pyproject.toml**: https://gist.github.com/amarion35/f7a7f8d5eb5a068192cd181c4f80fcee

- [ ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

I played with Azure Feed and with the help of the official [microsoft quick start](https://learn.microsoft.com/en-us/azure/devops/artifacts/quickstarts/python-packages?view=azure-devops) and [this answer](https://github.com/python-poetry/poetry/issues/3344#issuecomment-734333359) I've been able to make it work without too much trouble. I then commented the repository from the toml which give me this `pyprojet.toml` :  

      [tool.poetry]
      name = "my_package"
      version = "0.1.0"
      
      [tool.poetry.dependencies]
      python = "^3.8"
      numpy = "^1.20.1"
      
      [tool.poetry.dev-dependencies]
      pytest = "^6.2.5"
      
      [build-system]
      requires = ["poetry-core>=1.0.0"]
      build-backend = "poetry.core.masonry.api"
      
      # [[tool.poetry.source]]
      # name = "feed_name"
      # url = "https://pkgs.dev.azure.com/.../pypi/simple/"
      # default = true
      # secondary = false

I was expecting to get back to the default PyPI repository but the `poetry lock` is on hold at this step in the logs:

      (my_package-py3.8) root@amarion35:~/Projects/my_package# poetry lock -vvv
      Loading configuration file /root/.config/pypoetry/config.toml
      Using virtualenv: /root/.cache/pypoetry/virtualenvs/my_package-fKOiEnkg-py3.8
      Project environment contains an empty path in sys_path, ignoring.
      Updating dependencies
      Resolving dependencies...
         1: fact: my_package is 0.1.0
         1: derived: my_package
         1: fact: my_package depends on numpy (^1.20.1)
         1: fact: my_package depends on pytest (^6.2.5)
         1: selecting my_package (0.1.0)
         1: derived: pytest (>=6.2.5,<7.0.0)
         1: derived: numpy (>=1.20.1,<2.0.0)
      [keyring.backend] Loading KWallet
      [keyring.backend] Loading SecretService
      [keyring.backend] Loading Windows
      [keyring.backend] Loading chainer
      [keyring.backend] Loading libsecret
      [keyring.backend] Loading macOS
      No suitable keyring backend found
      No suitable keyring backends were found
      Keyring is not available, credentials will be stored and retrieved from configuration files as plaintext.
      Creating new session for pypi.org
      [urllib3.connectionpool] Starting new HTTPS connection (1): pypi.org:443
      [urllib3.connectionpool] https://pypi.org:443 "GET /simple/pytest/ HTTP/1.1" 200 25711

Poetry seems unable to connect to pypi.org but I don't receive any timeout either. I also tried `poetry install -vvv` with the former `poetry.lock` but it gets stuck at the same step in the logs. The issue is the same in all my environments. It works fine in my containers so it really looks like I messed up something in my local poetry configuration.

After some tests I find a solution with the command `poetry source add --default pypi-public https://pypi.org/simple/` but it only makes the trick for the current project.  It looks like PyPI has been removed from default source in all my projects.

**Comment by neersighted** [comment]
Your PyPI cache is corrupted, which is unrelated to the use of alternate sources. Please try `poetry cache clear --all .`, or upgrade to Poetry 1.3.1, which fixes this cache corruption. This was most like caused by interrupting Poetry in the middle of cache I/O, leaving stale lock files.
