### ISSUE TITLE
Using a version constraint as value for `tag` field for git-backed dependencies

### ISSUE THREAD

**Issue by macintacos** [python-poetry/poetry#7205]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request

When [using a dependency backed by a git repository](https://python-poetry.org/docs/dependency-specification/#git-dependencies), you can specify `rev`, `branch`, and `tag` to tell Poetry how to find that dependency for building. For `tag`, it doesn't seem to support standard version constraint like what is defined in the documentation [here](https://python-poetry.org/docs/dependency-specification/#version-constraints).

Would it be possible to add that capability to the `git`-based dependency versions in Poetry, for those module authors that use standard semver when tagging their releases? This would make things a little more streamlined as far as versioning is concerned. Perhaps it would check to see if the string provided matches the version constraints system, and if it doesn't, it falls back to looking for a tag that is an exact match?

**Comment by finswimmer** [comment]
Hello @macintacos,

a git tag is a pointer to a specific git commit. In other words it's just a part of the path to the source code. Even if Poetry starts to interpret this as a version, the rest of the python ecosystem will not do this. That's why we don't want to implement something like this.

fin swimmer
