### ISSUE TITLE
No git repository was found at [whateverlib]

### ISSUE THREAD

**Issue by roma-glushko** [python-poetry/poetry#7206]
- **Poetry version**:  1.3.1
- **Python version**: 3.9.13
- **OS version and name**: macOS 12.6.1 (21G217)

## Issue

Seems like Poetry is not handling all cases when it deal with source-based dependencies. 

In my case, we have added some external private repository to the poetry sources. Turned out that repository contained a modified version of cffi library. Poetry pulled that modified version into the `.venv/src` directory. 

Once the installation was done, I ran `poetry install` one more time and got the following error:

<img width="1442" alt="Screen Shot 2022-12-14 at 15 17 53" src="https://user-images.githubusercontent.com/9402690/208100275-7e107dcd-2733-4266-8215-ff8840c46831.png">

So Poetry warned that there is not git repository in the .venv/src/cffi directory. When I opened the .venv/src I saw the `cffi` directory: 

<img width="390" alt="Screen Shot 2022-12-14 at 15 19 42" src="https://user-images.githubusercontent.com/9402690/208100871-c6716f38-e712-45ba-8feb-c3d449510fdc.png">

There was no `.git` directory inside `.venv/src/cffi/`. I assume that was the issue. Though I doubt it was really necessary to fail the whole Poetry install process because of that following error. Some warn would be okay.

Removing the whole `.venv/src` helped to unblock the installation flow somehow.

**Comment by neersighted** [comment]
Duplicate #6322.
