### ISSUE TITLE
New poetry versions 1.3.1 creates lock files old versions 1.2.0 cant read and fails prod

### ISSUE THREAD

**Issue by opqpop** [python-poetry/poetry#7211]
- **Poetry version**: 1.3.1 (local dev), 1.2.0 (prod deployment)
- **Python version**: 
```

Poetry
Version: 1.3.1
Python:  3.10.6

Virtualenv
Python:         3.10.8
Implementation: CPython
Path:           /home/mark/.cache/pypoetry/virtualenvs/src-flPiXF7G-py3.10
Executable:     /home/mark/.cache/pypoetry/virtualenvs/src-flPiXF7G-py3.10/bin/python
Valid:          True

System
Platform:   linux
OS:         posix
Python:     3.10.8
Path:       /home/mark/.pyenv/versions/3.10.8
Executable: /home/mark/.pyenv/versions/3.10.8/bin/python3.10
```
- **OS version and name**: Ubuntu 22.04
- **pyproject.toml**: https://gist.github.com/opqpop/3a6703c71d416bd6e570b7f36e2be716

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
Our prod deployment uses docker to install a fresh poetry 1.2.0 using POETRY_VERSION=1.2.0 to force the version, and recently started failing due to 
```
The lock file is not compatible with the current version of Poetry.
Upgrade Poetry to be able to read the lock file or, alternatively, regenerate the lock file with the `poetry lock` command.
The command '/bin/sh -c poetry install --only main' returned a non-zero code: 1
```

The cause was one of our devs upgraded to 1.3.1 that was released 5d ago (he doesn't remember how either, is there some kind of forced updating mechanism going on?), and did a `poetry add some_package` which generated a `poetry.lock` file that `1.2.0` can't read anymore.

Is this intended behavior? We can't afford ANY downtime for our prod deployment, and would like to have a solution that doesn't brake when any of our devs upgrade to the latest version. We're also cautious about installing the latest version for our prod deployment, for the same reason we can't afford any downtime from latest changes. Ideally our prod deployment uses a fixed version, while new versions do not create lock files that brake this fixed version. For upgrades, we'd prefer a flow where we test out a newer version thoroughly before migrating the prod deployment to use the new version. 

Any ideas for how we can solve this?

We're really loving poetry but if this happens again, we will not be able to use it as our infra and use-case is mission critical.

**Comment by dimbleby** [comment]
Yes, this is intended behaviour.  See the changelog, and the release note.

(You checked the box "I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.", but I think that you didn't).

Either upgrade the version of poetry that you use to install with, or downgrade the version of poetry that you use to lock with.

**Comment by opqpop** [comment]
We're trying to figure out how the dev upgraded, he says he never ran `poetry self update`. Thoughts on how this might have happened?

**Comment by radoering** [comment]
> We can't afford ANY downtime for our prod deployment, and would like to have a solution that doesn't brake when any of our devs upgrade to the latest version.

Then, you should add a unit test in your CI that checks the lock file format and rejects concering commits. (I assume you are running some automated tests before rolling out arbitrary changes to your mission critical prod deployment.)

> We're trying to figure out how the dev upgraded, he says he never ran `poetry self update`. Thoughts on how this might have happened?

Removing and reinstalling poetry without pinning the version, running `pip install --upgrade poetry` in its virtual environment, running `pipx upgrade-all`, ...

**Comment by kod-kristoff** [comment]
@opqpop Have the dev installed `poetry` from distro? I'm on Arch Linux and have poetry installed from there, which updated `poetry`updated...

**Comment by Felixoid** [comment]
To add my 5 cents, did one consider that ubuntu LTS still has and will have an older poetry package `1.1.12` in the repositories forever? https://packages.ubuntu.com/search?suite=all&searchon=names&keywords=poetry

The current stable Debian release has an even older version `1.0.7` of the poetry package, and only in backports https://packages.debian.org/search?searchon=names&keywords=poetry

I consider changing of lock file as a major breaking during a minor release. And it breaks existing long-running distros.

I'd like to ask, how do maintainers see the picture? There is a zoo of distros and packages, the arch has a bleeding edge minor release of the poetry, and the fresh-brand-newest ubuntu LTS already broken with a relatively new version `1.1.12`.

**Comment by Secrus** [comment]
> To add my 5 cents, did one consider that ubuntu LTS still has and will have an older poetry package `1.1.12` in the repositories forever? https://packages.ubuntu.com/search?suite=all&searchon=names&keywords=poetry
> 
> The current stable Debian release has an even older version `1.0.7` of the poetry package, and only in backports https://packages.debian.org/search?searchon=names&keywords=poetry
> 
> I consider changing of lock file as a major breaking during a minor release. And it breaks existing long-running distros.
> 
> I'd like to ask, how do maintainers see the picture? There is a zoo of distros and packages, the arch has a bleeding edge minor release of the poetry, and the fresh-brand-newest ubuntu LTS already broken with a relatively new version `1.1.12`.

The Poetry team is not responsible for and distro-packaged version of Poetry. The only package we maintain is the python wheel and sdist available on PyPI or our GH releases page.

**Comment by Felixoid** [comment]
Thank you, I get your answer.

It's very sad that the central dependencies manager for python doesn't respect semver though.

**Comment by a-recknagel** [comment]
would it be an option to add a flag to `poetry lock` that generates a format older versions can parse (`--legacy` or something)? I won't be able to use newer versions on my workstation until all our containers have been updated, which can take a while. 

@opqpop your guy updated their poetry package, there is no auto-update unless they've set it up.
@neersighted the close seems a bit premature. this is a real issue for lots of people, and not addressing the problem will hinder adoption of newer versions and break trust.
