### ISSUE TITLE
Poetry installer on Windows does not add itself to PATH

### ISSUE THREAD

**Issue by Diggsey** [python-poetry/poetry#7212]
- **Poetry version**: 1.3.1
- **Python version**: 3.11.1
- **OS version and name**: Windows 10

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

I installed Poetry via the powershell command described on the website. The install succeeded, but `poetry` was no available on the command line. I restarted my terminal, but it was still not available. I checked my system environment variables, and the relevant path (`C:\Users\<user>\AppData\Roaming\Python\Scripts`) has not been added to PATH.

I would expect this to happen automatically during installation (or at the very least have instructions to add this manually in the post-install message). I happened to remember the path where poetry had been installed, but if I had not there's no easy way to find it out, since running the installer again just says "poetry already installed" with no indication of *where* it's been installed.

**Comment by dimbleby** [comment]
This is intended.  

Furthermore:
- the installer displays the following message (suitably filled in)
```
{poetry} ({version}) is installed now. Great!

  To get started you need {poetry}'s bin directory ({poetry_home_bin}) in your `PATH`
  environment variable.
  {configure_message}
  Alternatively, you can call {poetry} explicitly with `{poetry_executable}`.

  You can test that everything is set up by executing:

  `{test_command}`
```
- If you're following the commands described on the website you should also find bullet 3 "Add poetry to your path".

If you can think of a way to make this clearer I expect a pull request would be welcomed
