### ISSUE TITLE
ImportError: cannot import name 'Application' from 'cleo'

### ISSUE THREAD

**Issue by A-V-tor** [python-poetry/poetry#7215]
<code>previous version poetry 1.3.1</code>
<code>previous version python 3.10</code>
<code>mac os Monterey 12.5</code>

after updating python to <code>3.11</code>, poetry stopped working. Updated poetry with brew.

<code> poetry --version</code>I get <code>ModuleNotFoundError: No module named 'cleo'</code>
<code>pip3 install cleo</code>
<code>poetry --version</code>
Now I am getting

<code>Traceback (most recent call last):</code>
<code>File "/Users/name/.poetry/bin/poetry", line 17, in <module></code>
<code>from poetry.console import main</code>
<code>File "/Users/name/.poetry/lib/poetry/console/__init__.py", line 1, in <module></code>
<code>from .application import Application</code>
<code>File "/Users/name/.poetry/lib/poetry/console/application.py", line 3, in <module></code>
<code>from cleo import Application as BaseApplication</code>
<code>ImportError: cannot import name 'Application' from 'cleo' (/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/cleo/__init__.py)</code>

**Comment by dimbleby** [comment]
> Updated poetry with brew

This method for installing poetry is not developed or supported here.  You should report problems to brew, or use a supported installation method.

**Comment by A-V-tor** [comment]
Ok, I'll try. Thanks!

**Comment by A-V-tor** [comment]
i installed "poetry" via `curl -sSL https://install.python-poetry.org | python3-`
but i still get
`ImportError: cannot import name 'Application' from 'cleo' (/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/cleo/__init__.py)`

**Comment by dimbleby** [comment]
you probably didn't successfully remove the broken installation and are still hitting that

**Comment by A-V-tor** [comment]
Yes, that's right, I forgot to delete something. Problem solved. Thank you!

**Comment by ElenaGll** [comment]
> Yes, that's right, I forgot to delete something. Problem solved. Thank you!

What did you delete? I have the same problem and I can't solve it.

**Comment by A-V-tor** [comment]
> > Yes, that's right, I forgot to delete something. Problem solved. Thank you!
> 
> What did you delete? I have the same problem and I can't solve it.

initially I did not remove the old version that was not working correctly. After removing it, everything worked fine

**Comment by ElenaGll** [comment]
> > > Yes, that's right, I forgot to delete something. Problem solved. Thank you!
> > 
> > 
> > What did you delete? I have the same problem and I can't solve it.
> 
> initially I did not remove the old version that was not working correctly. After removing it, everything worked fine

I'm trying to delete the old version, but here's what I have
curl -sSL https://install.python-poetry.org | python3 - --uninstall
Poetry is not currently installed
poetry --version
...
ImportError: cannot import name 'Application' from 'cleo' ...

I've already tried everything

**Comment by A-V-tor** [comment]
> > > > Yes, that's right, I forgot to delete something. Problem solved. Thank you!
> > > 
> > > 
> > > What did you delete? I have the same problem and I can't solve it.
> > 
> > 
> > initially I did not remove the old version that was not working correctly. After removing it, everything worked fine
> 
> I'm trying to delete the old version, but here's what I have curl -sSL https://install.python-poetry.org | python3 - --uninstall Poetry is not currently installed poetry --version ... ImportError: cannot import name 'Application' from 'cleo' ...
> 
> I've already tried everything

try manually looking for files related to ''poetry'' and delete them

**Comment by ElenaGll** [comment]
> > > > > Yes, that's right, I forgot to delete something. Problem solved. Thank you!
> > > > 
> > > > 
> > > > What did you delete? I have the same problem and I can't solve it.
> > > 
> > > 
> > > initially I did not remove the old version that was not working correctly. After removing it, everything worked fine
> > 
> > 
> > I'm trying to delete the old version, but here's what I have curl -sSL https://install.python-poetry.org | python3 - --uninstall Poetry is not currently installed poetry --version ... ImportError: cannot import name 'Application' from 'cleo' ...
> > I've already tried everything
> 
> try manually looking for files related to ''poetry'' and delete them

Thank you very much for your help!

**Comment by A-V-tor** [comment]
> > > > > > Yes, that's right, I forgot to delete something. Problem solved. Thank you!
> > > > > 
> > > > > 
> > > > > What did you delete? I have the same problem and I can't solve it.
> > > > 
> > > > 
> > > > initially I did not remove the old version that was not working correctly. After removing it, everything worked fine
> > > 
> > > 
> > > I'm trying to delete the old version, but here's what I have curl -sSL https://install.python-poetry.org | python3 - --uninstall Poetry is not currently installed poetry --version ... ImportError: cannot import name 'Application' from 'cleo' ...
> > > I've already tried everything
> > 
> > 
> > try manually looking for files related to ''poetry'' and delete them
> 
> Thank you very much for your help!

Я так понимаю мы и на русском языке бы поняли друг друга)

**Comment by ElenaGll** [comment]
> > > > > > > Yes, that's right, I forgot to delete something. Problem solved. Thank you!
> > > > > > 
> > > > > > 
> > > > > > What did you delete? I have the same problem and I can't solve it.
> > > > > 
> > > > > 
> > > > > initially I did not remove the old version that was not working correctly. After removing it, everything worked fine
> > > > 
> > > > 
> > > > I'm trying to delete the old version, but here's what I have curl -sSL https://install.python-poetry.org | python3 - --uninstall Poetry is not currently installed poetry --version ... ImportError: cannot import name 'Application' from 'cleo' ...
> > > > I've already tried everything
> > > 
> > > 
> > > try manually looking for files related to ''poetry'' and delete them
> > 
> > 
> > Thank you very much for your help!
> 
> Я так понимаю мы и на русском языке бы поняли друг друга)

Ахаха. Да)

**Comment by patrick-muller** [comment]
I solve the issue on my mac with the below commands
curl -sSL https://install.python-poetry.org/ | python3 - --uninstall
brew uninstall poetry
whereis poetry
         /Users/user239345/.poetry
delete the folder
rm -rf /Users/user239345/.poetry

check the PATH
echo $PATH
        /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/user239345/.poetry

delete poetry from your $PATH, in my environment it is in the file
       /etc/paths

credits to -> https://stackoverflow.com/questions/15872666/how-to-remove-entry-from-path-on-mac

after that install poetry again, I am installing using brew
brew install poetry

**Comment by lbognotti** [comment]
POHAAAA FOI CARALHO
