### ISSUE TITLE
Dependency groups doesn't support same package having different versions in different groups.

### ISSUE THREAD

**Issue by shreyanshgautam24** [python-poetry/poetry#7231]
- **Poetry version**: 1.3 and 1.2.2
- **Python version**: 3.9.7
- **OS version and name**: Ubuntu 22.04.1 LTS 
- **pyproject.toml**: https://gist.github.com/shreyanshgautam24/597a49aa71761e44489ce129c5df72ca

- [ x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [ x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x ] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
output with -vvv option:

Updating dependencies
Resolving dependencies...
   1: fact: testme is 1.0.0
   1: derived: testme
   0: Duplicate dependencies for reportlab
   1: fact: testme depends on reportlab (3.6.12)
   1: fact: testme depends on reportlab (3.6.8)
   1: selecting testme (1.0.0)
   1: derived: reportlab (==3.6.8)
   1: conflict: testme depends on reportlab (3.6.12)
   1: ! not reportlab (==3.6.12) is satisfied by reportlab (==3.6.8)
   1: ! which is caused by "testme depends on reportlab (3.6.8)"
   1: ! thus: version solving failed
   1: Version solving took 0.005 seconds.
   1: Tried 1 solutions.

As poetry supports grouping dependency i am trying to use different versions of third party packages and some of my python packages pinning to different groups, as per my requirement i will be using different groups at different environment, for which i tried is not working. please let me know how to solve this issue

**Comment by dimbleby** [comment]
This is working as designed: it's not what groups are for.  Please read the documentation

https://python-poetry.org/docs/managing-dependencies/#dependency-groups

> All dependencies must be compatible with each other across groups since they will be resolved regardless of whether they are required for installation or not

**Comment by neersighted** [comment]
Duplicate #1168.
