### ISSUE TITLE
zsh: `poetry shell` doesn't work if space character in .venv path

### ISSUE THREAD

**Issue by dimstunt** [python-poetry/poetry#7244]
- **Poetry version**: Poetry (version 1.3.1)
- **Python version**: 
```
Poetry Version: 1.3.1
Python:  3.9.5

Virtualenv
Python:         3.9.5
Implementation: CPython
Path:           /Applications/Dwarf Fortress LMP/LNP/Utilities/Ann2/AnnouncementWindow/.venv
Executable:     /Applications/Dwarf Fortress LMP/LNP/Utilities/Ann2/AnnouncementWindow/.venv/bin/python
Valid:          True

System
Platform:   darwin
OS:         posix
Python:     3.9.5
Path:       /Users/dimstunt/.pyenv/versions/3.9.5
Executable: /Users/dimstunt/.pyenv/versions/3.9.5/bin/python3.9
```
- **OS version and name**: macOS 13.0.1
- **pyproject.toml**: any

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
If there is a space in the path to the virtual environment (e.g. when using `virtualenvs.in-project=true`) the `poetry shell` command is not executed as expected, because the `shlex.quote` function wraps that path in single quotes, and when running in `zsh`, that wrapped path is wrapped in quotes again.
### executed:
```shell
poetry shell
# Spawning shell within /Applications/Dwarf Fortress LMP/LNP/Utilities/Ann2/AnnouncementWindow/.venv
emulate bash -c '. '/Applications/Dwarf Fortress LMP/LNP/Utilities/Ann2/AnnouncementWindow/.venv/bin/activate''
# emulate: unknown argument Fortress
```
### expected:
```shell
poetry shell
# Spawning shell within /Applications/Dwarf Fortress LMP/LNP/Utilities/Ann2/AnnouncementWindow/.venv
emulate bash -c ". '/Applications/Dwarf Fortress LMP/LNP/Utilities/Ann2/AnnouncementWindow/.venv/bin/activate'"
```

**Comment by d3cryptofc** [comment]
i have the same problem..

**Comment by 2Wdavidcunliffe** [comment]
Bumping as I have the same issue, I was able to manually resolve by passing the same argument as the expected outcome to get the shell to activate in my project.

**Comment by brucey0x** [comment]
Running into the same issue. Manually resolving by escaping the spaces doesn't work for me either.

What does work is simply activating the venv like you normally would with:

`source .venv/bin/activate`

I installed Poetry with pipx and am using Oh My Zsh. Have carefully followed the instructions, including executing the following in terminal:

`mkdir $ZSH_CUSTOM/plugins/poetry
poetry completions zsh > $ZSH_CUSTOM/plugins/poetry/_poetry`

And adding the poetry plugin to the `~/.zshrc` plugin array.

**Comment by fatveg** [comment]
It appears like there is a pull request to fix this from a year ago but it hasn't been accepted (looks like there was a timeout on a test). 

In the meantime I just added:

`alias v_activate="source .venv/bin/activate" `

to my .zshrc and use that instead of `poetry shell`

**Comment by radoering** [comment]
> It appears like there is a pull request to fix this from a year ago but it hasn't been accepted (looks like there was a timeout on a test).

Thanks for the hint. The PR looks good to me.
