### ISSUE TITLE
Poerty can't find gmp.h on M1 Mac

### ISSUE THREAD

**Issue by witfyl-ravped** [python-poetry/poetry#7246]
Because Homebrew can't install packages into virtual environments I am unable to install packages that depend on gmp within poetry environments.

To be clear I can instill said packages on my computer in my main environment, but not within Poetry.

For reference see the issue I opened here before I realized it was specific to Poetry:

https://github.com/Shard-Labs/starknet-devnet/issues/371

**Comment by neersighted** [comment]
Please follow the issue template when creating an issue.

In this case, this is not a Poetry issue, but a user issue. You need to provide the correct include paths to the C compiler using `CFLAGS`/`CXXFLAGS`. Poetry only invokes a wheel build; it is the user's role to ensure that their environment is set up in such a way that the toolchain of the native extensions being built can locate their dependencies.

**Comment by witfyl-ravped** [comment]
Thank you for your reply but this doesn't answer my question.

My question is how can I provide said paths within the poetry environment? Do those flags need to go into the poetry.lock file?

Or do I include them when running `poetry install`? And if so, what is the syntax for that, pointing them to the Homebrew dir outside of the virtualenv?
