### ISSUE TITLE
ValueError: the greenlet library is required to use this function. No module named 'greenlet'

### ISSUE THREAD

**Issue by Hongbo-Miao** [python-poetry/poetry#7249]
- **Poetry version**: 1.3.1
- **Python version**: 3.11.1
- **OS version and name**: macOS 13.1
- **pyproject.toml**: https://github.com/Hongbo-Miao/bug-prefect-greenlet/blob/main/pyproject.toml

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

Here is the minimal repo to reproduce with steps in the readme: https://github.com/Hongbo-Miao/bug-prefect-greenlet
with steps inside. Thanks!

I originally posted at https://github.com/PrefectHQ/prefect/issues/7978

@madkinsz pointed me (thanks!) to another ticket which shows may be potential a Poetry bug: https://github.com/PrefectHQ/prefect/issues/6310

Please let me know if need anything else! Thanks! 😃

**Comment by madkinsz** [comment]
https://github.com/python-poetry/poetry/issues/5429 may be related.

**Comment by dimbleby** [comment]
duplicate #5429

**Comment by Hongbo-Miao** [comment]
Thanks @dimbleby for the link! I assume it has been fixed in Poetry 1.4 https://github.com/python-poetry/poetry/pull/7175
I will verify once Poetry 1.4 published! So close for now. 😃

**Comment by Hongbo-Miao** [comment]
Just add an update, confirmed, the issue has been fixed in Poetry 1.4.0 😃

**Comment by farzad-845** [comment]
- **Poetry version: 1.5.1**
- **Python version: 3.10.12**
- **OS version and name: macOS 13.4 (22F66)**

 It is failing. `ValueError: the greenlet library is required to use this function. No module named 'greenlet'`
