### ISSUE TITLE
How can I configure poetry to pass --no-cache-dir to pip so that it won't get an OOM signal

### ISSUE THREAD

**Issue by nyaachen** [python-poetry/poetry#7250]
- [ X ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ X ] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request

I am using poetry to build up the prod env for a project. When I run `poetry install` it shows that poetry is collecting torch, and then it got a OOM signal displaying Killed. And torch is a large whl about 900M and together with some dependency about another 800M.

I searched for a solution saying that when i use poetry to collect torch it is actually using pip to collect torch.
So I tried to manually install torch by running `pip3 install torch` and it received a OOM signal, too.
I searched for the web and used `pip3 install torch --no-cache-dir` and the installation succeed, but its not installed in poetry venv.

When I tries `poetry install --no-cache-dir` it tells me --no-cache-dir is not an valid option for poetry.
I search for the document but did not found a method about how to pass parameters from poetry to pip. So I wonder if poetry can use any methods to pass parameter to sub pip/python process.

My machine is 1C+2G, mem report says used 355M free 1.4G.

**Comment by nyaachen** [comment]
Somehow, I managed to installed torch successfully, by manually switching to the virtualenv poetry created and install torch into the virtual env.

**Comment by dimbleby** [comment]
poetry does not provide a way to pass parameters to pip.  More discussion in #7265, #7182, #3249, and probably others

**Comment by neersighted** [comment]
Poetry only uses pip as a minor implementation detail; Poetry is not a pip wrapper like Pipenv. 

In this case you can turn off Poetry's parallelism with `poetry config installer.parallel false` as well as use Poetry's `--no-cache` to reduce the memory overhead. There are no guarantees that this will solve your case however, downloading a 2.4Gb file in a small VM is pretty rough/dodgy as we haven't specifically optimized Poetry to behave well in such situations. Large distfiles are simply not a huge issue outside specialized niches like ML packages.

I'm going to close this for now as mostly no action possible; if with the above suggestions you still have issues, I'd suggest opening a generalized issue to examine/optimize Poetry's memory usage when downloading large (aka ML) distfiles.
