### ISSUE TITLE
Poetry is stuck at  `Loading macOS` using verbose mode no other output

### ISSUE THREAD

**Issue by damascene** [python-poetry/poetry#7253]
- **Poetry version**:  Poetry (version 1.3.1)
- **Python version**: Python 3.8.10
- **OS version and name**: Ubuntu 20.04
- **pyproject.toml**: project independent

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

Poetry is stuck at  `Loading macOS`:

```
$ poetry -vvv self update
Loading configuration file /home/user/.config/pypoetry/config.toml
Updating Poetry version ...

[keyring.backend] Loading KWallet
[keyring.backend] Loading SecretService
[keyring.backend] Loading Windows
[keyring.backend] Loading chainer
[keyring.backend] Loading libsecret
[keyring.backend] Loading macOS
```

`/home/user/.config/pypoetry/config.toml` file is empty. 

I've internet on device. I upgraded Poetry from version `1.2.1` using the install script but the issue still there.

**Comment by neersighted** [comment]
Duplicate #1917.

**Comment by damascene** [comment]
Maybe I should open a bug about improving error reporting? apparently there is something that isn't being reported probably here, no?

**Comment by neersighted** [comment]
There is an open bug for this -- #1917. There are also several PRs pending review.
