### ISSUE TITLE
poetry-lock pre-commit hook does not use the intended Python installation

### ISSUE THREAD

**Issue by brianaydemir** [python-poetry/poetry#7258]
- **Poetry version**: 1.3.1
- **Python version**: 3.10.2
- **OS version and name**: macOS 12.6.2
- **pyproject.toml**: https://gist.github.com/brianaydemir/2519a29bef261efd5101b85afec89651

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

I use [pyenv](https://github.com/pyenv/pyenv) to manage all of my Python installations and virtual environments. (I find this preferable to prefixing every command with `poetry run ...`.) Poetry itself appears to be installed under a 3.10.2-based venv.

In Project B, I have a `pyproject.toml` file (the gist linked above) and a `.python-version` file that specifies a 3.10.2-based venv (a different one than the one Poetry is installed under). This venv contains the [pre-commit](https://pre-commit.com/) installation. Somehow, the `poetry-lock` pre-commit hook ends up picking up a 3.8.5-based venv, which is incompatible with the project and leads to the following error:

```
poetry-lock..............................................................Failed
- hook id: poetry-lock
- exit code: 1

Current Python version (3.8.5) is not allowed by the project (~3.10).
Please change python executable via the "env use" command.
```

It is perhaps worth noting that I first ran the `poetry-lock` hook for Project A, which has a similar `pyproject.toml`/`.python-version` structure as Project B, except that it uses a 3.8.5-based venv.

**Comment by neersighted** [comment]
This is not related to Poetry; but instead to pre-commit. pre-commit selects the Python (and will use its own Poetry install); you need to ensure that pre-commit makes the correct choice here.

**Comment by brianaydemir** [comment]
@neersighted I don't understand why this is pre-commit's problem.

The `poetry-lock` pre-commit hook is using Poetry to analyze the project. It's Poetry's responsibility to make sure that it performs that analysis using the appropriate Python installation, regardless of the Python installation that's being used to run Poetry itself.

After all, Poetry already does this when run directly from the command line. I have Poetry installed under a Python 3.10 environment and regularly use it with Python 3.6 and Python 3.8 projects without any issues. I can run `poetry lock` by hand with no issues.

**Comment by neersighted** [comment]
That is not in fact the case; Poetry will default to `sys.executable` unless you set `virtualenvs.prefer-active-python`, which experimentally attempts to support Pyenv switching. I suspect you may have multiple copies of Poetry installed or similar. Feel free to set that variable, which the copy of Poetry used internally by pre-commit will support; if you run into bugs with it however, please reproduce them outside of pre-commit so we can verify that the issue is in fact with Poetry and not with pre-commit/your configuration of pre-commit.

**Comment by salvador-moreno-mck** [comment]
@brianaydemir did you find a solution or a workaround? I'm facing the same error in some of the projects I'm working on. Some of them raise me the same error with `poetry lock`, some others don't, but I cannot find any meaningful differences in the  poetry configuration or the steps I follow.
