### ISSUE TITLE
poetry install --without dev allow for missing dev group dependencies

### ISSUE THREAD

**Issue by scottwalshqs** [python-poetry/poetry#7259]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request
I would like to be able to have a `[tool.poetry.group.dev.dependencies]` group with local dependencies that do not exist and allow `poetry install --without dev` to continue to work in this case.  This would help with developing within a monorepo where local packages may exists in different relative paths in development compared to production.

pyproject.toml
```
[tool.poetry]
name = "testname"
version = "0.1.0"
description = ""
authors = []
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
dne = {path = "../diffpath/packages/dne", develop = true}

[tool.poetry.group.dev.dependencies]
dne = {path = "../../packages/dne", develop = true}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

```
➜  poetry install --without dev

Directory ../../packages/dne does not exist
```

**Comment by neersighted** [comment]
Duplicate #668
