### ISSUE TITLE
`poetry alias`, why not?

### ISSUE THREAD

**Issue by brunolnetto** [python-poetry/poetry#7260]
## Feature Request

I found this feature on Pypi. Since it is not official, it wakes my internal urges to notify poetry staff about `hacker-alert`.

https://pypi.org/project/poetry-alias/

**Comment by neersighted** [comment]
The Poetry project does not hold a copyright on the name; third-party plugins are welcome and encouraged. While we prefer the naming scheme `poetry-plugin-<name>` for PyPI packages, plugin authors are free to name things as they see fit.

**Comment by brunolnetto** [comment]
The action "Add tag \"status/invalid\"" makes me wonder if the OP-question is invalid by itself or if there is no explicit plan to implement the feature `poetry alias` or any other alias-related additional command to `poetry`. May you clarify it?

**Comment by neersighted** [comment]
Your issue seemed to be about the fact that something named poetry-alias is available on PyPI, but not by the official Poetry team. That is not a security/"hacker" issue at all.

Regarding the functionality of the plugin, it seems to be a fancy way to chdir. There is no want to implement something like that in Poetry itself.

If I misunderstood the intent of your, I apologize. Please follow the instructions for feature requests in the contributing guide as well as the issue template to reduce ambiguity in the future.

**Comment by brunolnetto** [comment]
Sure, your interpretation skills does not leave you unattended. The command "chdir" seems useful on the subject, but since `poetry` is a package management module, it suits well its `.toml` archictecture in the same way `git` comand places `alias` commands on path `.git/config`. 

May you forward here the proper way to request a feature?

**Comment by neersighted** [comment]
> Sure, your interpretation skills does not leave you unattended. The command "chdir" seems useful on the subject, but since `poetry` is a package management module, it suits well its `.toml` archictecture in the same way `git` comand places `alias` commands on path `.git/config`.

I'm not 100% sure what you mean, and I'm still unclear why you linked the PyPI package. It doesn't implement the functionality you seem to want. We have an existing feature request at #2496, that you seem to be already aware of.

**Comment by brunolnetto** [comment]
100% is "great", but 75% is "good", which may be better than 50%-"ok". 

The issue is 1.5 years old, which is like "much" according to [Moore's law](https://en.wikipedia.org/wiki/Moore%27s_law). Regardless of which, I know there is some relation between backlog feature requests, men-hours and product-management agreements that delays every wanted feature.  

A recommendation for such popular library like `poetry` is to publish some (estimated) release schedule to mitigate (our) expectations. :-)

**Comment by neersighted** [comment]
Poetry is a volunteer-led and developed project. The answer to "when will feature X be implemented" is "when someone interested delivers patches and they go through code review (which takes other interested parties)." Ideally we also review feature requests/proposals in the mean time to prevent false hope/wasted effort if a feature is unlikely to be accepted.

This is wildly off topic and we have an existing feature request, I'm going to lock this issue for now to nudge discussion over to the proper issue.
