### ISSUE TITLE
Could not parse version constraint when install a package on Windows

### ISSUE THREAD

**Issue by kaixinol** [python-poetry/poetry#7263]
- **Poetry version**:  Poetry (version 1.3.1)
- **Python version**: 3.10.9
- **OS version and name**: Win10 21H2
- **pyproject.toml**: https://gist.github.com/kaixinol/b099e604d04c89c5de102af490e027a1

- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
1. Type `poetry install` and execute
2. Get an error message
```
Installing dependencies from lock file

Could not parse version constraint:
```
3. Edit `pyproject.toml` and delete `sqlalchemy = "^1.4.45"`, the error disappears

**Comment by kaixinol** [comment]
PS: I can't install `sqlalchemy = "^1.4.45"` this package, but I can install it on another computer.
 By copying the `Libs folder` under the `Cache directory`, I successfully ran the program.

**Comment by finswimmer** [comment]
This looks like a cache problem. Try clearing the cache by `poetry cache clear --all PyPI` and reinstall again.

**Comment by kaixinol** [comment]
1. Reinstall Poetry
2. Delete the virtual environment cache path shown in `poetry env info` command
3. Delete `poetry.lock` file
*poetry back to normal*

**Comment by kaixinol** [comment]
> This looks like a cache problem. Try clearing the cache by `poetry cache clear --all PyPI` and reinstall again.

Before I fixed poetry, executing this command showed:
```
No cache entries for PyPI
```
Now, this instruction executes normally.
