### ISSUE TITLE
"packages were not found" when trying to remove existing package

### ISSUE THREAD

**Issue by turbotimon** [python-poetry/poetry#7264]
- **Poetry version**: 1.3.1
- **Python version**: 3.10.0
- **OS version and name**: ubuntu
- **pyproject.toml**: see below

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

A package with was installed py `poetry install` and is visible by `poetry info` but can not be removed?

```
$ poetry --version
Poetry (version 1.3.1)

$ python --version
Python 3.10.2

$ poetry show mypy
 name         : mypy                              
 version      : 0.991                             
 description  : Optional static typing for Python 

dependencies
 - mypy-extensions >=0.4.3
 - tomli >=1.1.0
 - typing-extensions >=3.10

required by
 - sqlalchemy >=0.910

$ poetry remove mypy

The following packages were not found: mypy
```

```toml
[tool.poetry.dev-dependencies]
mypy = "^0.991"
```

it may has to to with `dev-dependenies` which is deprecated (however, it should still work right)?

**Comment by finswimmer** [comment]
Hello @turbotimon,

you have to tell Poetry from which dependency group it should remove the dependency. In your case:

```
poetry remove -G dev mypy
```

See https://python-poetry.org/docs/cli/#remove

**Comment by turbotimon** [comment]
this feels awkward and not very intuitive as all e.g. `show` does not need it.  the same package can only be added once and not to serval  different group. Or do i miss something?

You may also want to change the ***can*** to a ***must*** in your docu:
> If you want to remove a package from a specific group of dependencies, you can use the --group (-G) option

Anyway, thanks for the help

**Comment by finswimmer** [comment]
> the same package can only be added once and not to serval different group. Or do i miss something?

The same package can be added multiple times and can therefor appear in multiple groups. Running `poetry remove` without any group name, tries to remove the dependency from the "main" dependency group (your normal run time dependencies). This is consistence with the behavior of `poetry add`.
