### ISSUE TITLE
In-place upgrading of Python versions for virtualenvs

### ISSUE THREAD

**Issue by 0xLem0nade** [python-poetry/poetry#7267]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request

Having worked with Poetry for a year now, I appreciate the capabilities and ease of Python dev it introduced to my workflow!

Only one other thing I'd love to see from Poetry is the ability to upgrade `virtualenvs` **in-place** with a newer Python version installed with `pyenv`. Having to re-create the `virtualenvs` and reinstall all the dependencies feels too much, at least for minor releases (e.g 3.10.x)!

This feature alongside #461 baked in Poetry would be awesome!

**Comment by finswimmer** [comment]
Hey @0xLem0nade,

while I understand that this feature would be quite useful, this is (at least at the moment) out of scope for Poetry. We simply pass the venv creation job to `virtualenv`.

I'm afraid in-place upgrading the interpreter in a venv is not a trivial job at all.

fin swimmer
