### ISSUE TITLE
Can't install Dependencies with `extras` that contain `-` 

### ISSUE THREAD

**Issue by ilkersigirci** [python-poetry/poetry#7287]
- **Poetry version**: Poetry (version 1.3.1)
- **Python version**: 3.8.15
- **OS version and name**: Ubuntu 22.04
- **pyproject.toml**: [pyproject.toml link](https://gist.github.com/ilkersigirci/b5d737b16614a2710b848b401a20362b)
- **pip version**:  22.3.1

- [ x ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [ x ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ x ] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

### BUG
If a dependency  contains `-` in its `extras` field, they can't be installed if the package is built with `poetry build` and then `pip install <package>`. It gives a warning and doesn't install those extra packages
 
### Steps
- I have added my dependency to `pyproject.toml` with `poetry add sktime[all_extras,dl]==0.15.0`
which added to toml as: `sktime = {version = "0.15.0", extras = ["all-extras", "dl"]}`
- I have built the project with `poetry build`
- I have installed the built package with `pip install <my_built_package.tar.gz>`
-  Here I got the error that says:
`WARNING: sktime 0.15.0 does not provide the extra 'all-extras'`
- And those extra packages didn't installed at the end.

### Notes
- I can successfully install `pip install sktime[all_extras, dl]`
- In the built package, `PKG-INFO` has the following content:
	- `Requires-Dist: sktime[all-extras,dl] (==0.15.0)`
	- I have changed it to `Requires-Dist: sktime[all_extras,dl] (==0.15.0)`. But it gave the same warning again.

**Comment by dimbleby** [comment]
#6819
