### ISSUE TITLE
Poetry doesn't seem to build wheel correctly for shap

### ISSUE THREAD

**Issue by bentheiii** [python-poetry/poetry#7296]
- **Poetry version**: 1.3.1
- **Python version**: 3.10.6
- **OS version and name**: Ubuntu 22.04
- **pyproject.toml**: https://gist.github.com/bentheiii/432a4e9b652a1cf85f5984db0c3d5a24

- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

Hi, the above toml installs without errors, but it does not run correctly. The example script:
```python
import shap
import xgboost

# get a dataset on income prediction
X,y = shap.datasets.adult()

# train an XGBoost model (but any other model type would also work)
model = xgboost.XGBClassifier()
model.fit(X, y)

ex = shap.TreeExplainer(model)
```

fails with the error:
```
Traceback (most recent call last):
  File "***", line 11, in <module>
    ex = shap.TreeExplainer(model)
  File "***/shap/explainers/tree.py", line 121, in __init__
    self.model = TreeEnsemble(model, self.data, self.data_missing, model_output)
  File "***/shap/explainers/tree.py", line 740, in __init__
    self.trees = xgb_loader.get_trees(data=data, data_missing=data_missing)
  File "***/shap/explainers/tree.py", line 1438, in get_trees
    }, data=data, data_missing=data_missing))
  File "***/shap/explainers/tree.py", line 1028, in __init__
    assert_import("cext")
  File "***/shap/common.py", line 21, in assert_import
    raise e
  File "***/shap/explainers/tree.py", line 17, in <module>
    from .. import _cext
ImportError: numpy.core.multiarray failed to import
C extension was not built during install!

Process finished with exit code 1
```

however, running the following commands:
```
poetry run pip uninstall shap -y
poetry run pip install "shap==0.35.0"
```
and re-running the script causes it to run correctly.

**Comment by dimbleby** [comment]
not a poetry bug, as evidenced by https://github.com/slundberg/shap/issues/1895

**Comment by bentheiii** [comment]
> not a poetry bug, as evidenced by [slundberg/shap#1895](https://github.com/slundberg/shap/issues/1895)

The issue references a different numpy version. In this case, `poetry install` fails where `pip install` succeeds

**Comment by dimbleby** [comment]
that issue shows the exact same error being hit without any poetry involvement.  It also has pip sometimes succeeding (and sometimes failing) depending on environmental factors.

Given that, it's a pretty safe bet that this is a problem in the packaging of shap

**Comment by neersighted** [comment]
Until shap resolves their packaging problem, you can pin to the version of numpy they built against by adding a top-level requirement on that version of numpy in your pyproject.toml. You can also set [`installer.no-binary`](https://python-poetry.org/docs/configuration/#installerno-binary) to force a build from source, though this will have to be set by everyone who installs your project on their local machine, unless you choose to check in poetry.toml, which is usually not recommended.

**Comment by dimbleby** [comment]
actually I think it's not exactly that, but more or less the same

- I reckon you're getting the source distribution for `shap` already
- that has `setup_requires=['numpy']` (no version constraint), so that will cause the local shap build to be against the most recent numpy
- your pyproject.toml specifies very much not the most recent numpy
- I expect those things are incompatible

**Comment by neersighted** [comment]
Ah, good call, I did not test out the difference between pip with `--use-pep517` and without, but that does reproduce for me. In this case the best move is to depend on a fork of upstream (or wait for a PR to be accepted) that correctly declares the same constraint during build and install.

**Comment by bentheiii** [comment]
Thanks @neersighted, Is there any solution to this problem that isn't slapping `poetry run pip uninstall shap -y && poetry run pip install "shap==0.35.0"` after every `poetry install`? Because that seems to work.

**Comment by neersighted** [comment]
It works because pip by default builds in the installed environment; this is quite problematic in the face of multiple build-systems and differing needs for the setuptools version (e.g. Poetry being able to lock setuptools and pip, while projects being built can request specific versions of setuptools).

Poetry thus requires PEP 517 isolated builds, performed in a disposable virtual environment. `pip install --use-pep517` triggers this mode (and is how Poetry currently performs them, though it is not the only way) and will reproduce this behavior you are running into if you `poetry export` your lock file.

I'm not sure I have a great answer on how to solve this in the mean time. I suppose the constraining the versions available to the isolated build to match the installed environment might make sense in some cases, but certainly not all the time (e.g. setuptools). I suspect that a new strategy to better support isolated builds might need to happen upstream in shap, and that this issue deserves discussion on DPO's Packaging forum as well.

**Comment by neersighted** [comment]
The only other instance of this problem I've found was this [StackOverflow answer](https://stackoverflow.com/questions/48166508/wheel-depends-on-build-time-numpy-version) -- it seems to imply that Numpy has a backwards-compatible ABI, in which case the `build-system.requires` could be pinned at the oldest version of NumPy that is to be supported.

I don't have the time to explore this myself, but it's worth considering if you want to dig into this.

**Comment by bentheiii** [comment]
@neersighted thanks for all the help. I'm not sure that I understand the issue completely but could poetry solve it by requesting to remove build-isolation for some dependencies?

```toml
[tool.poetry.dependencies]
shap = {version="0.35.0", build-isolation=false}
```

Or perhaps some way to override a dependancy's build requirements?

```toml
[tool.poetry.dependencies]
shap = {version="0.35.0", build-requires=["numpy==1.14.5"]}
```

**Comment by neersighted** [comment]
Both of those would be misfeatures -- I think that the most sane thing we could do is either set a flag to use versions from the pyproject.toml as constraints when possible, or allow for literal constraints (where constraints is a feature of pip that says "use this constraint if this package is installed"), warning at build-time when there are conflicts.

**Comment by detrin** [comment]
I am not sure if this is still relevant today. Since shap==0.35.0 is not the latest version, I would be interested if the issue persists with the newest version of shap.
