### ISSUE TITLE
poetry can't install the latest version of psutil (5.9.4) on some MacOS

### ISSUE THREAD

**Issue by tipanverella** [python-poetry/poetry#7298]
- **Poetry version**: 1.3.1
- **Python version**: 3.11.0
- **OS version and name**: macOS 12.6.1
- **pyproject.toml**: [psutil-poetry-toml](https://gist.github.com/tipanverella/d1865f4d44369f6953766487ac28761c)

I have tried to get an answer on [stackoverflow](https://stackoverflow.com/questions/74662677/psutil-fails-to-install-version-5-9-4-on-mac-with-poetry)

The issue seems to be related to the fact that poetry thinks that the sha256 checksum for, `psutil-5.9.4-cp38-abi3-macosx_11_0_arm64.whl` does not match the expected value:

```
  • Installing psutil (5.9.4): Pending...
[keyring.backend] Loading KWallet
[keyring.backend] Loading SecretService
[keyring.backend] Loading Windows
[keyring.backend] Loading chainer
[keyring.backend] Loading libsecret
[keyring.backend] Loading macOS
Creating new session for pypi.org
Skipping psutil-5.9.4-cp36-abi3-win32.whl as sha256 checksum does not match expected value
Skipping psutil-5.9.4-cp36-abi3-win_amd64.whl as sha256 checksum does not match expected value
Skipping psutil-5.9.4-cp38-abi3-macosx_11_0_arm64.whl as sha256 checksum does not match expected value
Skipping psutil-5.9.4.tar.gz as sha256 checksum does not match expected value
Skipping wheel psutil-5.9.4-cp27-cp27m-macosx_10_9_x86_64.whl as this is not supported by the current environment
Skipping wheel psutil-5.9.4-cp27-cp27m-manylinux2010_i686.whl as this is not supported by the current environment
Skipping wheel psutil-5.9.4-cp27-cp27m-manylinux2010_x86_64.whl as this is not supported by the current environment
Skipping wheel psutil-5.9.4-cp27-cp27mu-manylinux2010_i686.whl as this is not supported by the current environment
Skipping wheel psutil-5.9.4-cp27-cp27mu-manylinux2010_x86_64.whl as this is not supported by the current environment
Skipping wheel psutil-5.9.4-cp27-cp27m-win32.whl as this is not supported by the current environment
Skipping wheel psutil-5.9.4-cp27-cp27m-win_amd64.whl as this is not supported by the current environment
Skipping wheel psutil-5.9.4-cp36-abi3-macosx_10_9_x86_64.whl as this is not supported by the current environment
Skipping wheel psutil-5.9.4-cp36-abi3-manylinux_2_12_i686.manylinux2010_i686.manylinux_2_17_i686.manylinux2014_i686.whl as this is not supported by the current environment
Skipping wheel psutil-5.9.4-cp36-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl as this is not supported by the current environment
.
.
.
  RuntimeError

  Unable to find installation candidates for psutil (5.9.4)
```

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

**Comment by neersighted** [comment]
You likely have corrupted your artifacts cache from a previous aborted or simultaneous run of Poetry. This bug is prevented in the 1.3 branch, but there is no defense against a previously corrupted cache. Please `rm -rf $(poetry config cache-dir)/artifacts` and `poetry cache clear --all .`, and try again.

**Comment by tipanverella** [comment]
worked like a charm.  Thank you!
