### ISSUE TITLE
Poetry install takes too long and installs the package again unnecessarily

### ISSUE THREAD

**Issue by Alexspayne** [python-poetry/poetry#730]
- [X] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

I'm wondering why it takes 13-30 seconds to install my package (on two different machines). 
This occurs when the package and it's dependencies are already installed.
`$ time poetry install -vvv
Using virtualenv: /Users/apayne/Envs/smithers
Installing dependencies from lock file

Nothing to install or update

  - Skipping markupsafe (1.1.0) Already installed
  - Skipping click (7.0) Already installed
  - Skipping itsdangerous (1.1.0) Already installed
  - Skipping jinja2 (2.10) Already installed
  - Skipping werkzeug (0.14.1) Already installed
  - Skipping aniso8601 (4.0.1) Already installed
  - Skipping flask (1.0.2) Already installed
  - Skipping jsonschema (2.6.0) Already installed
  - Skipping pytz (2018.7) Already installed
  - Skipping six (1.11.0) Already installed
  - Skipping flask-restplus (0.12.1) Already installed
  - Skipping passlib (1.7.1) Already installed
  - Skipping peewee (3.7.1) Already installed
  - Installing smithers (0.1.0)

real	0m29.542s
user	0m5.344s
sys 0m2.370s`

Smithers is the name of the package I'm installing with poetry.  The installing smithers step takes the majority of the time.  Is poetry doing anything but creating a symlink?  I don't understand why this should take so long.  If the package is already installed in editable mode, why does poetry try installing it again?

Much thanks!

**Comment by sdispater** [comment]
The `install` command installs the current project in editable mode by internally creating a temporary `setup.py` file and executing `pip install -e .`. It does it each time `install` is executed to ensure that any new elements like entrypoints are properly installed.

I plan on adding an option to `install` to disable the installation of the current project.

**Comment by bertjwregeer** [comment]
@sdispater is there any reason for the use of a `setup.py` instead of creating the appropriate directory structure/updating the virtual env directly?

If there is a better ticket to mention this in, please let me know.

**Comment by sdispater** [comment]
@bertjwregeer For pure python projects, we could do without the `setup.py` file. This would require creating the proper files and directories which are, as far as I know, an `easy_install.pth` in the `site-packages` directory of the virtualenv and the `{project}.egg-info` directory in the current directory project.

This is not possible however for packages with C extensions for instance. Poetry does not come with a compiler and as such has to rely on the `setup.py` file.

**Comment by bertjwregeer** [comment]
The current "hack" for Poetry to do C extensions is to add extra content to the setup.py that is generated, correct? If it can be detected when that is the case and only then do the setup.py way, that would be fantastic.

Building plugins to allow building Cython/C extensions for poetry would be even better, but that can come later.

**Comment by Alexspayne** [comment]
My current workaround is to use the `--dry-run` argument as a default in my build script for development. I just override that argument when I actually want it to `poetry install`.

**Comment by sdispater** [comment]
@bertjwregeer This is one way to go, yes, and an easy one. I can probably target that for the `1.0.0` release.

**Comment by maggyero** [comment]
> The `install` command installs the current project in editable mode by internally creating a temporary `setup.py` file and executing `pip install -e .`. It does it each time `install` is executed to ensure that any new elements like entrypoints are properly installed.
> 
> I plan on adding an option to `install` to disable the installation of the current project.

Thanks for `poetry install --no-root` @sdispater!

Could you also add another _command-line_ option that allows installing projects in _non_-editable mode (e.g., `poetry install --no-editable`)?

The [documentation](https://poetry.eustace.io/docs/cli/#add) states that it is already possible for local dependencies, but only with a `develop` property from the `pyproject.toml` file (I think a command-line option would be more appropriate though, as it is something that you want to configure at each install, like `pip install -e`):

> If you don't want the dependency to be installed in editable mode you can specify it in the pyproject.toml file:
>
> [tool.poetry.dependencies]
> my-package = {path = "../my/path", develop = false}

So if you could drop the `develop` property here and allow:

- `poetry install --no-editable`
- `poetry add --no-editable`
- `poetry update --no-editable`

that would be awesome.
