### ISSUE TITLE
`poetry install --only-root` removes installed extra dependencies

### ISSUE THREAD

**Issue by cutwater** [python-poetry/poetry#7302]
- **Poetry version**: 1.3.1
- **Python version**: 3.10.9
- **OS version and name**: Arch Linux, x86_64, kernel 6.1.2-arch1-1
- **pyproject.toml**: https://gist.github.com/cutwater/a074f85f81a24c125b1ba938944272fe

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

Executing `poetry install --only-root` uninstalls previously installed extra sets of dependencies.

### Use case

When building a container image I use the following pattern to reuse cached layers and prevent dependencies installed on every source code change. Sample of `Dockerfile` \ `Containerfile`:

```
COPY pyproject.toml poetry.lock /app/src/
RUN poetry install -E psql --no-root
COPY . /app/src
RUN poetry install --only-root
```

### Steps to reproduce

1. Create a new project `poetry new sample`
2. Go to project directory `cd sample`
3. Add a package (e.g. `psycopg2` as an optional dependency, and include it into a extra set of dependencies (e.g. `psql`):

```
[tool.poetry.dependencies]
python = "^3.10"
psycopg2 = {version = "^2.9.5", optional = true}

[tool.poetry.extras]
psql = ["psycopg2"]
```
4. Install dependencies only :
```
$ poetry install -E psql --no-root
Installing dependencies from lock file

Package operations: 1 install, 0 updates, 0 removals

  • Installing psycopg2 (2.9.5)
```
5. Install only the package:
```
$ poetry install --only-root      
Installing dependencies from lock file

Package operations: 0 installs, 0 updates, 1 removal

  • Removing psycopg2 (2.9.5)

Installing the current project: sample (0.1.0)
```

### Actual behavior

Executing `poetry install --only-root` uninstalls extra sets of dependencies. On step 5 the `psycopg2` package is removed.

### Expected behavior

Executing `poetry install --only-root` should not install or uninstall any dependencies.

### Workaround

At the moment it's possible to specify the same set of extra dependencies that were used on a previous step, but this behavior is not intuitive.

```
$ poetry install -E psql --only-root
```

**Comment by cutwater** [comment]
@dimbleby thank you for referencing those issues. The issue is indeed duplicate of #7000, but I think that #7000 was mistakenly closed as a duplicate of #6993, as I believe they describe two different cases.

I can't find an explanation of the behavior described in #7000 and this issue. The documentation says:

> To only install the project itself with no dependencies, use the --only-root flag.
>
> `poetry install --only-root`

And also:

> Extras are not sensitive to --sync. Any extras not specified will always be removed.

In the example above the `--sync` option is not used, and in section related to `--only-root` option "no dependencies" is stated. Is there any reason or valid use case for deleting packages when running in "no dependencies" mode, that I may be missing?

Thank you.

**Comment by neersighted** [comment]
It is the same, as no `-E` is a variation of extras. It is an empty string, if that makes sense.

The current documented behavior is that Poetry removes extras not specified during an install; this is mostly because `-E` predates `--sync` and to change it to match groups is a major breaking change.

**Comment by cutwater** [comment]
> It is the same, as no -E is a variation of extras. It is an empty string, if that makes sense.

Yes, it makes sense. In cases when dependency installation takes place.

> The current documented behavior is that Poetry removes extras not specified during an install; this is mostly because -E predates --sync and to change it to match groups is a major breaking change.

It seems that miscommunication or misunderstanding takes place. Please allow me to restate the matter. The issue is not about the combination of a `--sync` option and `-E` option. **It is about the `--only-root` option.**

Can you please help me to understand why the `-E` option is not ignored when the poetry is executed as `poetry install --only-root`, like it happens with regular dependencies? Maybe there is a valid existing use case for a combination of `-E` and `--only-root` options besides a workaround for the current issue, that I'm missing?

**Comment by neersighted** [comment]
It sounds like you think that `--only-root` has special semantics compared to other invocations of `poetry install`, that is not true at this time.

`--only-root` is a standard `poetry install` that is roughly equivalent to `--without <special token meaning all>`; all groups including `main` are excluded.

`poetry install` installs the root package like any other package; there is no concept of 'dependency installation' or a separate operation. It makes more sense to make the breaking change of making `-E` beholden to `--sync` than it does to create a special case.

**Comment by cutwater** [comment]
@neersighted Thank you for clarifying the installation semantics for me.

I was considering `poetry install --no-root` as a rough equivalent of `pip install --no-deps --editable .`, and it seems I'm not the only one having similar expectations. 

Do you think the documentation can better explain this edge case? Will the poetry team be open to contributions to the documentation, that add more details on current behavior and\or semantics based on the information you provided?  In my opinion it will be beneficial for the users of the poetry project. 

Closing this issue for now.
