### ISSUE TITLE
Choose repository at install time

### ISSUE THREAD

**Issue by ethiy** [python-poetry/poetry#7337]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request

I usually work with two different platforms/architectures for the same project. In fact, I wish that the same project works for both a x86 architecture as well as a Raspberry Pi for instance.

This means that each time I want to switch platforms I have to change the `pyproject.toml` and lock using `poetry`. 
In addition, I can only commit one version of the lock file that works with only one platform/architecture.

Is it possible to have an option where two default repositories (or more) could be declared each corresponding to a specific platform?
In this case, the developer chooses the right platform/architecture at install time.

I know that this behavior can be simulated using markers. However, having it is too much work and is not natural for a user.

**Comment by marcelampc** [comment]
Same here!

**Comment by ethiy** [comment]
The project documentation is not thorough. I have added a documentation related issue #7345 asking for a more detailed explanation.

Incomplete documentation does not entice wide adoption of such a project by the wider public. This tool is supposed to help developers concentrate on adding value and not solving complex puzzles. Otherwise, one can just fall back to the benchmark.

I can understand that it can be easy for someone knowing the inns and outs of the project. However, a simple user is not required to be an expert to use the tool.
