### ISSUE TITLE
Issue with Poetry 1.3.1 and Python 3.10 in Github Actions.

### ISSUE THREAD

**Issue by fbalo-medium** [python-poetry/poetry#7343]
- **Poetry version**: poetry 1.3.1
- **Python version**: Python 3.10
- **OS version and name**: Ubuntu 22.04
- **pyproject.toml**: https://gist.github.com/fbalo-medium/61d6f65bb38e598a700c53dc2055c476

- [ ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
An issue I just discovered is if you are using a Python version lower than 3.10 (even if you set Poetry to accept Python 3.8 or higher in myproject.toml) in your project and try to run that project in an environment that runs 3.10, it raises an “Invalid version '1.1build1' on package distro-info” error.

I suspect Poetry sees Python 3.10 as Python 3.1.

This happened when I tried to running Poetry in a Github Action environment. When I explicit choose the version to be 3.8, it worked.

**Comment by dimbleby** [comment]
search issues in this repository for `1.1build1` to find the duplicates

**Comment by neersighted** [comment]
This is a Ubuntu python packaging quirk; use `setup-python` instead to get an upstream-style Python free of this non-compliant version.

**Comment by dhpollack** [comment]
> `setup-python`

Can you expand on this?  I am using pyenv and get this error.

**Comment by diraven** [comment]
> > `setup-python`
> 
> Can you expand on this? I am using pyenv and get this error.

I think they refer to https://github.com/actions/setup-python GitHub Action. Just put it before your requirements installation step in your workflow file and that should fix your issue.

**Comment by marcelgerber** [comment]
I'm also running into this issue.
I absolutely need to enable `system-site-packages` because I need to access a Python package that can only be installed via apt.
This issue is blocking me from using poetry, for all that I know.

**Comment by asaf-kali** [comment]
Same with `poetry==1.4.2`, python 3.9, in Github CI.

**Comment by cfreire** [comment]
I've resolved this issue installing `poetry` from original sources.

```
$ hostnamectl
Operating System: Ubuntu 22.04.2 LTS              
          Kernel: Linux 5.19.0-42-generic
    Architecture: x86-64
 Hardware Vendor: TOSHIBA
  Hardware Model: SATELLITE P70-B
```

```sh
$ python --version
Python 3.10.6
``` 
```sh
$ pip --version
pip 23.1.2
```
**Error on self update**

```
$ poetry self show

Invalid version '1.1build1' on package distro-info
```

Showing that python3-poetry-core was left out by some old `apt install python3-poetry` and was not auto removed
```sh
$ sudo apt search poetry
Sorting... Done
Full Text Search... Done

python3-poetry/jammy-updates,jammy-updates 1.1.12+dfsg-1ubuntu1 all
  Python dependency management and packaging made easy (Python 3)

python3-poetry-core/jammy,jammy,now 1.0.7-2 all [installed,auto-removable]
  Poetry PEP 517 Build Backend
```
Removing python3-poetry-core
```
$ sudo apt remove python3-poetry-core
$ sudo apt auto-remove
```

Still no luck, removing poetry previously installed by pip
```
$ poetry self update

Invalid version '1.1build1' on package distro-info

$ pip uninstall poetry
Found existing installation: poetry 1.5.1
Uninstalling poetry-1.5.1:
  Would remove:
(...)
```

Installing from original source 
```sh
$ curl -sSL https://install.python-poetry.org | python3 -
Retrieving Poetry metadata
(...)
Installing Poetry (1.5.1): Done

Poetry (1.5.1) is installed now. Great!
```

**Success**
```
$ poetry self update
Updating Poetry version ...

Using version ^1.5.1 for poetry
Updating dependencies
```

**Comment by marknet15** [comment]
So for me that wasn't enough, even when using the default recommended script I would still see the same error:
```
#13 1.245 Invalid version '1.1build1' on package distro-info
```

For me the fix was to upgrade the `distro-info` package:

```
pip install distro-info --upgrade
```

Then after the Poetry install script worked as expected and I was able to use it fine with no errors.

**Comment by sque** [comment]
The very first answer of @neersighted was spot on. The problem is that if you use actions and you rely on the python that is provided on ubuntu you may hit this problem too and has to do with the packaging of python in ubuntu.

The solution is to install another version of python by using the [setup-python](https://github.com/actions/setup-python) action just before installing poetry.

Example:
```
jobs:
  my-job:
    name: my-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'Set up Python 3.9'
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install poetry
        run: pip install poetry
# ... more steps here with poetry
```
