### ISSUE TITLE
Can't install --without-dev option in Poetry

### ISSUE THREAD

**Issue by sunnydown111** [python-poetry/poetry#7353]
Hello, I'm trying to do poetry install --without-dev but keep getting this error:

```
Command "C:\Users\Jack Shaw\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-UrucP5ur-py3.10\Scripts\python.exe" -I -W ignore - errored with the following return code 101, and output:
Unable to create process using 'C:\Users\Jack Shaw\AppData\Local\Programs\Python\Python310\python.exe -I -W ignore -'
input was : import sys

if hasattr(sys, "real_prefix"):
    print(sys.real_prefix)
elif hasattr(sys, "base_prefix"):
    print(sys.base_prefix)
else:
    print(sys.prefix)
```

I have no clue  what is going on and can't find any solution in the forums, please help.

**Comment by neersighted** [comment]
It looks like you have a broken virtual environment. Being more specific is hard as you have not followed the issue template/provided much in the way of details. Could you try blowing away the virtual environment with `poetry env remove --all` and trying again?

**Comment by sunnydown111** [comment]
> It looks like you have a broken virtual environment. Being more specific is hard as you have not followed the issue template/provided much in the way of details. Could you try blowing away the virtual environment with `poetry env remove --all` and trying again?

i can't even do that command, I get the same error

**Comment by finswimmer** [comment]
Sounds like your Poetry installation is broken. I would suggest, remove it from your system and reinstall it with the [recommended installer](https://python-poetry.org/docs/#installing-with-the-official-installer).

**Comment by finswimmer** [comment]
Hello @sunnydown111,

you haven't come back to this issue for a long while. So I assume this is solved in the meantime and I can close this ticket.

Feel free to leave a comment if you disagree.

fin swimmer
