### ISSUE TITLE
Increase default REQUESTS_TIMEOUT

### ISSUE THREAD

**Issue by stefanondisponibile** [python-poetry/poetry#7376]
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request

I'm experiencing frequent issues with the `poetry install` command failing for `ReadTimeoutError`s. That's also starting to "affect" CI builds using poetry.

Even if there are ways to work around / config that, should we think of increasing [the default `REQUESTS_TIMEOUT`](https://github.com/python-poetry/poetry/blob/master/src/poetry/utils/constants.py#L5)?

I agree with @Kaiser1989 [here](https://github.com/python-poetry/poetry/commit/584aaee5f8da9f950f98d1ef0ebc06fe835e5d96#commitcomment-86558029).

In my local poetry installation I ended up setting it to `100`.

**Comment by dimbleby** [comment]
duplicate #6009 

(per the discussion in there, most - though not necessarily all - of the people who think they would benefit from increasing this value are mistaken: they have misunderstood either what the timeout is for, or where it is used.  I don't know whether that includes you or not)

**Comment by stefanondisponibile** [comment]
Hey @dimbleby , thanks for your reply! :pray:  I saw that discussion, but I don't think that value should be configurable, I really think it should be increased. I'm going to add my two cents there :+1:
