### ISSUE TITLE
Update packages declared using git tags

### ISSUE THREAD

**Issue by maurosaladino** [python-poetry/poetry#7379]
Poetry version: 1.3.2
Python version: 3.9.16
OS version and name: MacOS 12.6.1

- [x]  I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x]  I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x]  I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x]  If an exception occurs when executing a command, I executed it again in debug mode (-vvv option) and have included the output below.

## Issue

Hi,
I have the same issue that this user is having on stackoverflow:

https://stackoverflow.com/questions/75010992/why-is-poetry-not-updating-gitssh-dependency-from-private-repo-versioned-using

How can I automatically update packages declared in pyproject.toml using git tags?
Thanks

**Comment by dimbleby** [comment]
you'll have to update your pyproject.toml

git tags are not version numbers, they are tags.  A tag is an arbitrary string pointing at exactly one revision.
