### ISSUE TITLE
No documentation about markers (such as platform)

### ISSUE THREAD

**Issue by thernstig** [python-poetry/poetry#738]
- [x ] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue
There seems to be no mention in the documentation of the usage and supported markers, but they do seem to be supported according to https://github.com/sdispater/poetry/issues/21

**Comment by jimbo1qaz** [comment]
What `platform` do I use for Windows 10 x64?

I'm using Poetry 0.12.10.

```sh
poetry remove pywin32-ctypes
pip uninstall -y pywin32-ctypes
pyinstaller
poetry add --platform=windows pywin32-ctypes
pyinstaller
```

And I"ve tried windows, Windows, nt, and pywin32-ctypes never gets installed.

**Comment by carlosperate** [comment]
I was looking into this recently and cound't find the documentation either, are platform markers officially supported?

**Comment by deepio** [comment]
Could this be documented please?
https://github.com/sdispater/poetry/issues/1189

**Comment by thernstig** [comment]
/ unstale 📦

**Comment by eterna2** [comment]
can I check if 
```
extras_require = \
{':sys_platform == "windows"': ['pywin32-ctypes>=0.2.0,<0.3.0']}
```
is a valid setup.py format? Because I get format error (extras_require must be a dict of xyz) when I tried to do `python setup.py install`

**Comment by zillionare** [comment]
where can I find the documentation for specifying sys_platform. According to the thread, it's added to the document, however I can't find it in the document.

**Comment by sinoroc** [comment]
@zillionare It's in the "_[Dependency specification -- Using environment markers](https://python-poetry.org/docs/dependency-specification/#using-environment-markers)_" section.

**Comment by dclong** [comment]
Is it possible to restrict the whole package to be on, say, Linux only? Do I have to use marker for every package or is there a simple way of specifying OS restrictions?

**Comment by sinoroc** [comment]
> Is it possible to restrict the whole package to be on, say, Linux only? Do I have to use marker for every package or is there a simple way of specifying OS restrictions?

@dclong Use trove classifiers. They are an informal (non-enforced) restriction:

```
[tool.poetry]
# ...
classifiers = [
    "Operating System :: POSIX :: Linux",
]
```

* https://github.com/python-poetry/poetry/issues/3356#issuecomment-726163405
* https://pypi.org/classifiers/
* https://python-poetry.org/docs/pyproject/#classifiers

**Comment by dclong** [comment]
@sinoroc This is awesome! Thank you very much for the links! I will check them.
