### ISSUE TITLE
Files generated during build are not included in sdist

### ISSUE THREAD

**Issue by Tbruno25** [python-poetry/poetry#7380]
- **Poetry version**:  1.3.2
- **Python version**: 3.10.6
- **OS version and name**: Linux Mint 21
- **pyproject.toml**: [link](https://pastebin.com/Qmtrr4TK)

- [x ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

Files that get dynamically generated at build time are excluded from the sdist despite being included in whl.

Steps to reproduce:

Create new poetry project named `my_pkg`
```
poetry new my_pkg
```

Add a `my_pkg/build.py` file that contains the following
```
import pathlib 

CURRENT_DIR = pathlib.Path(__file__).parent
DYNAMIC_FILE = CURRENT_DIR / "my_pkg" / "dynamic_file.txt"

DYNAMIC_FILE.touch()
assert DYNAMIC_FILE.exists()
```

Include dynamic file and allow use of custom build by adding the following to `pyproject.toml`
```
[tool.poetry]
...
include = [{path = "my_pkg/dynamic_file.txt", format=["sdist", "wheel"]}]

[tool.poetry.build]
generate-setup-file = false
script = "build.py"
```

Build the package via `poetry build`

Results:

Contents of `my_pkg/dist/my_pkg-0.1.0.tar.gz`:
```
.
├── build.py
├── my_pkg
│   └── __init__.py
├── PKG-INFO
└── pyproject.toml
```

Contents of `my_pkg/dist/my_pkg-0.1.0-cp310-cp310-manylinux_2_35_x86_64.whl`:
```
.
├── my_pkg
│   ├── dynamic_file.txt
│   └── __init__.py
└── my_pkg-0.1.0.dist-info
    ├── METADATA
    ├── RECORD
    └── WHEEL
```

**Comment by dimbleby** [comment]
#6197

**Comment by dimbleby** [comment]
Though on reflection I'm not convinced that this variation, concentrating on the source distribution, is even a bug.  The source _doesn't_ contain the "dynamically created" file: that file is created at build time.

So it seems correct that the source distribution should not contain the file, while a built distribution should.

Why do you think this file should appear in the source distribution?

**Comment by Secrus** [comment]
Exactly as dimbleby said, sdists don't go through that build step, so they won't produce that file. This is not a bug, that's how it works with python packages.

**Comment by Tbruno25** [comment]
Interesting. Thank you both for the clarification!

> Why do you think this file should appear in the source distribution?
I suppose as I explicitly call it out in `pyproject` I expected it would be included. However, I'm (obviously) not overly familiar with packaging so I appreciate the insight.

Is there another option you would recommend exploring in which the file will be included in both the sdist and whl as a result of the `poetry build` command?

**Comment by dimbleby** [comment]
why do you _want_ it in the sdist?  what you are describing is a build artifact, produced at build time.  Anyone who consumes your sdist will create their own copy of that artifact when they build your package.

If you have a file that is truly a source artifact: commit it to your repository and don't create it at build-time.

**Comment by Tbruno25** [comment]
>why do you want it in the sdist?

Essentially our use case is that we have a python package that exists as part of a much larger, multi language monorepo. 

The package depends upon non-python files that must live outside of the package itself. In an effort to avoid duplication, any time the package is built it would be awesome if we could automatically include the most up to date version of those files. The thought process was to update the files via copy inside a try except block within `build.py` -- however it now seems like that's not a viable approach?

**Comment by dimbleby** [comment]
build.py will be executed by users who install your source distribution.  Only you can say whether that's the way you want them to get this file.

If you actually need to put it in the source distribution then you need to put the file in the source tree before starting the build

**Comment by Secrus** [comment]
@Tbruno25 couldn't you distribute as wheels if this is the case?

**Comment by Tbruno25** [comment]
> couldn't you distribute as wheels if this is the case?

It's an option but correct me if I'm wrong -- I would need to generate wheels for all platform variants against all python versions we support? That's not really a road I'd like to go down.

Kind of a bummer this isn't easily possible -- definitely wish more documentation surrounding the poetry build process was available.

However, I very much appreciate the help!

**Comment by dimbleby** [comment]
If your build artifacts are different on different platforms then you need to generate different wheels for different platforms.

I don't think this was really a poetry question at all in the end - rather, a misunderstanding about the difference between source and binary/wheel distributions; you'd have had the same confusion regardless of what tool you were using.

Having said which, poetry's `build.py` is underdocumented and that's deliberate: it is formally unsupported (see #2740)

Anyway, there's no poetry bug here, this should be closed.
