### ISSUE TITLE
`poetry lock --no-update` results in diffrent output is cache is used or not

### ISSUE THREAD

**Issue by AndersKOlsson** [python-poetry/poetry#7395]
- **Poetry version**: 1.3.2
- **Python version**: 3.10.8
- **OS version and name**: Ubuntu 20.04.5 LTS
- **pyproject.toml**: https://gist.github.com/AndersKOlsson/d09c0efbe7412ed7086db068d17ec35f

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
I've noticed an issue between running `poetry lock --no-update` with and without cached packages. When having a dependency on sqlalchemy in the project, the lockfile generated for the project in the above gist by running `poetry lock --no-update` gets changed when running it without cache (`poetry lock --no-update --no-cache`). Likewise, running these commands in the inverse order changes the lockfile inversely.
Here are the diffs of what changes between the runs, depending on if `--no-cache` is passed:
[git-diff-after-poetry-lock--no-update.txt](https://github.com/python-poetry/poetry/files/10478276/git-diff-after-poetry-lock--no-update.txt)
[git-diff-after-poetry-lock--no-update--no-cache.txt](https://github.com/python-poetry/poetry/files/10478277/git-diff-after-poetry-lock--no-update--no-cache.txt)

I think the reason for the `-`s becoming `_`s is that sqlalchemy uses the wrong packages names ([cx_oracle](https://github.com/sqlalchemy/sqlalchemy/blob/2f91dd79310657814ad28b6ef64f91fff7a007c9/setup.cfg#L58), when the pypi package is named [cx-oracle](https://pypi.org/project/cx-Oracle/)). However, that shouldn't result in this switching behavior, based on the cache being used or not. I've not figured out why the macosx packages for `Pillow-9.4.0-1` and `Pillow-9.4.0-2` are removed when using the cache.

**Comment by dimbleby** [comment]
pillow has uploaded various files at various times eg some on Jan 2, some on Jan 6, some on Jan 17.

I expect you have a cache from one of the earlier dates.

**Comment by AndersKOlsson** [comment]
Yes, @dimbleby, that was it. Having manually cleared the cache folder, these issues stopped appearing. I was unaware of these pitfalls due to caching. Thank you so much!
