### ISSUE TITLE
poetry add open3d fails on win10 (possible version problem 0.16.0 vs 0.16.1)

### ISSUE THREAD

**Issue by mganglb** [python-poetry/poetry#7402]
Hi, 

- **Poetry version**: 1.3.2
- **Python version**: Python 3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AMD64)] on win32
- **OS version and name**: Windows10
- **pyproject.toml**: https://gist.github.com/mganglb/a604102d91f84b375b70e568973c8f00
- **output**: https://gist.github.com/mganglb/f9e83398b31bf2b92194293143fbd5a3
- **possibly related**: https://github.com/python-poetry/poetry/issues/7034

## Issue
Currently there are issues with adding open3d to an environment.
`poetry add open3d` -> fails (open3d version 0.16.1)
`poetry run pip install open3d` -> works (open3d version 0.16.0)
adding open3d manually to the *.toml works  `open3d ="0.16.0`

best regards
mgangl

**Comment by dimbleby** [comment]
which of these files are you hoping to install https://pypi.org/project/open3d/0.16.1/#files?  

There are no available open3d 0.16.1 distributions for windows.  You will have to pin to an earlier version.

(That `poetry add` always tries the latest is #707)

**Comment by mganglb** [comment]
Hello, thank you very much for the fast response!

i know that there is no 0.16.1 for windows as also identifiable here: https://gist.github.com/mganglb/f9e83398b31bf2b92194293143fbd5a3
i am new to poetry, so i dont know the exact behaviour of the commands yet. But this seems problematic.

**Comment by dimbleby** [comment]
that `poetry add` always tries to use the latest version of a package is already tracked by #707
that `open3d` publishes no distribution suitable for windows (not even a source distribution) is an `open3d` issue.

this issue can safely be closed

**Comment by neersighted** [comment]
Poetry never considers wheel resolution in solving, we only consider declared compatibility/the package metadata.
