### ISSUE TITLE
test_run_has_helpful_error_when_command_not_found is locale dependent

### ISSUE THREAD

**Issue by bruchar1** [python-poetry/poetry#7408]
My Windows installation is in French. When I run tests, the test_run_has_helpful_error_when_command_not_found test fails because the output is in French, not is English, on my machine.

Detecting current language is probably not trivial.

Maybe the test should only ensure that `nonexistent-command` is in the output.

**Comment by dimbleby** [comment]
probably a merge request fixing it would be welcome
