### ISSUE TITLE
Content of environment variable `POETRY_CACHE_DIR` not respected in Poetry config

### ISSUE THREAD

**Issue by paul-papacz** [python-poetry/poetry#7410]
- **Poetry version**: 1.3.2
- **Python version**: 3.10.6
- **OS version and name**: Ubuntu 22.04.1 LTS
- **pyproject.toml**: not relevant

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

When setting the environment variable `POETRY_CACHE_DIR`, the content of that variable will **not** be used as for `cache-dir`. Instead it appears as a comment after the currently set `cache-dir`.

Steps to reproduce:

* Install Poetry 1.3.2
* Set `POETRY_CACHE_DIR`, e.g:
```
export POETRY_CACHE_DIR=/path/to/cache
```
* Check Poetry config:
```
$ poetry config --list
cache-dir = "/home/.cache/pypoetry"  # /path/to/cache
experimental.new-installer = true
experimental.system-git-client = false
installer.max-workers = null
installer.no-binary = null
installer.parallel = true
virtualenvs.create = true
virtualenvs.in-project = null
virtualenvs.options.always-copy = false
virtualenvs.options.no-pip = false
virtualenvs.options.no-setuptools = false
virtualenvs.options.system-site-packages = false
virtualenvs.path = "{cache-dir}/virtualenvs"  # /path/to/cache/virtualenvs
virtualenvs.prefer-active-python = false
virtualenvs.prompt = "{project_name}-py{python_version}"
```

**Comment by dimbleby** [comment]
that's just how the `poetry config --list` command presents such things.  

what you are showing is actually evidence that `POETRY_CACHE_DIR` _is_ being respected.

**Comment by dimbleby** [comment]
again, this is all just how this works.

- `poetry config key value` updates key-value in the actual configuration file
- an environment variable obviously doesn't
- `poetry config --list` shows both the 'raw' and the overridden value
-

**Comment by neersighted** [comment]
@dimbleby has summarized this accurately, `poetry config --list` displays the actual values and the comments indicate the effective value. This could be more clear, but the solution would be primarily docs improvement with a side of UX (maybe tracking provenance for the annotating comments, e.g. 'template-eval' for `virtualenvs.dir` or 'env').

Feel free to open a feature request with suggestions for how the UX could be improved, or send a docs PR if you think there could be a better explanation of the configuration mechanism.

**Comment by paul-papacz** [comment]
@neersighted, @dimbleby - Thanks for clarifying. I will follow up on your suggestions when I have some time.

However, the behaviour still seems inconsistent.

When e.g. I instead of `POETRY_CACHE_DIR`, I set `POETRY_VIRTUALENVS_CREATE`
```
$ poetry config virtualenvs.create true
$ poetry config --list
cache-dir = "/home/.cache/pypoetry"
experimental.new-installer = true
experimental.system-git-client = false
installer.max-workers = null
installer.no-binary = null
installer.parallel = true
virtualenvs.create = true
virtualenvs.in-project = null
virtualenvs.options.always-copy = false
virtualenvs.options.no-pip = false
virtualenvs.options.no-setuptools = false
virtualenvs.options.system-site-packages = false
virtualenvs.path = "{cache-dir}/virtualenvs"  # /home/.cache/pypoetry/virtualenvs
virtualenvs.prefer-active-python = false
virtualenvs.prompt = "{project_name}-py{python_version}"
```
(:point_up: shows `virtualenvs.create` as `true`)
```
$ export POETRY_VIRTUALENVS_CREATE=false
$ poetry config --list
cache-dir = "/home/.cache/pypoetry"
experimental.new-installer = true
experimental.system-git-client = false
installer.max-workers = null
installer.no-binary = null
installer.parallel = true
virtualenvs.create = false
virtualenvs.in-project = null
virtualenvs.options.always-copy = false
virtualenvs.options.no-pip = false
virtualenvs.options.no-setuptools = false
virtualenvs.options.system-site-packages = false
virtualenvs.path = "{cache-dir}/virtualenvs"  # /home/.cache/pypoetry/virtualenvs
virtualenvs.prefer-active-python = false
virtualenvs.prompt = "{project_name}-py{python_version}"
```
(:point_up: shows `virtualenvs.create` as `false` only)

it does **not** show the "raw" value for `virtualenvs.create`.

**Comment by dimbleby** [comment]
The code is [here](https://github.com/python-poetry/poetry/blob/9a0b4af51effde0ddba53085e85e9f16e070f85a/src/poetry/console/commands/config.py#L284-L316)

indeed strings are treated differently from not-strings

If you have improvements you'd like to see, I expect that merge are welcome
