### ISSUE TITLE
Incorrect Pathing on Windows Powershell causes poetry to fail to install build cpp dependencies. 

### ISSUE THREAD

**Issue by skewballfox** [python-poetry/poetry#7413]
- **Poetry version**: 1.3.2
- **Python version**: 3.10.8
- **OS version and name**: Windows 10 Education Version 10.0.19045 Build 19045
- **pyproject.toml**: [sanitized gist](https://gist.github.com/skewballfox/c915f0c32acbec94c4ff5abe78b2091f)

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

I believe this issue may be related to an [upstream issue with virtualenv](https://github.com/pypa/virtualenv/issues/2414). It seems that path isn't set correctly causing installation of dependencies to fail when wheels need to be built. 

the windows compiler is installed, the headers stored in the python modules do not seem to be on the search path. I *think* it's looking at `.venv/` rather than `.venv/lib`, the way I resolved it with just venv directly was to switch to the scripts directory before activating `Activate.ps1`. 

[link to debug output for `poetry install` on powershell](https://gist.github.com/skewballfox/9f9d7ed431bf6e1d70e6832ed2b4fe2a)

**Comment by dimbleby** [comment]
if you've already diagnosed this as not a poetry issue, I'm not sure why you've raised it here?

you should be able to double-confirm that it's not a poetry with something like `pip install --use-pep517 --no-cachedir pyfastnoisesimd` - which I expect to fail in the same way, without poetry being anywhere near it.

**Comment by skewballfox** [comment]
> if you've already diagnosed this as not a poetry issue, I'm not sure why you've raised it here?

partially because it's still an issue that affects poetry whether the cause is upstream. partially because I'm not sure that specific upstream issue is the root cause. 

> you should be able to double-confirm that it's not a poetry problem with something like pip install --use-pep517 --no-cache-dir pyfastnoisesimd - which I expect to fail in the same way, without poetry being anywhere near it.

yeah that failed. I'll go ahead and close this. Quick question though, you think that linked issue is the cause of this?

**Comment by skewballfox** [comment]
sorry, didn't realize you couldn't comment on closed issues

**Comment by dimbleby** [comment]
> you think that linked issue is the cause of this?

No, I think not.  It's definitely not a poetry problem, but I'd guess that also it's nothing to do with the virtualenv issue that you mentioned.

Most likely you want to be raising this with pyfastnoisesimd and asking them to support PEP517 builds.
