### ISSUE TITLE
Incorrect parsing of `statsmodels` requirements file leads to incorrect SolverProblemError

### ISSUE THREAD

**Issue by matthewkdies** [python-poetry/poetry#7417]
- **Poetry version**: 1.3.2
- **Python version**: 3.9.16
- **OS version and name**: Ubuntu 22.04
- **pyproject.toml**: https://gist.github.com/matthewkdies/b518e54b9076c07a8eb48b8b73e7455b

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
I recently tried to add both `scipy` and `statsmodels` to a development container using Poetry, and was faced with a `SolverProblemError`. After searching deeper into it, I believe that Poetry is parsing [`statsmodels`'s most recent version's `requirements.txt` file](https://github.com/statsmodels/statsmodels/blob/v0.13.5/requirements.txt) incorrectly.

In the body of that `requirements.txt` file is the following:
```
# Workaround for scipy build requirement
numpy>=1.22.3; python_version=="3.10" and platform_system=="Windows" and platform_python_implementation != "PyPy"
numpy>=1.17; python_version!="3.10" or platform_system!="Windows" or platform_python_implementation=="PyPy"
...
scipy>=1.3,<1.9; python_version=="3.8" and platform_system=="Windows" and platform_machine=="x86"
scipy>=1.3,<1.9; python_version=="3.9" and platform_system=="Windows" and platform_machine=="x86"
scipy>=1.3; (python_version>"3.9" or platform_system!="Windows" or platform_machine!="x86") and python_version<"3.12"
```
The relevant information we have in this case is:
- `python_version`: 3.9.16
- `platform_version`: Linux
- `python` dependency in `pyproject.toml`: `python = ">=3.8,<3.11"`

According to our above variables, the identified requirements for each package should be `numpy>=1.17` and `scipy>=1.3`:
- `numpy>=1.17` is satisfied by `platform_system!="Windows"`
- `scipy>=1.3` is satisfied by `platform_system!="Windows" and python_version<"3.12"`. Since our Python dependency in `pyproject.toml` is listed as `python>=3.8`, the first requirement in the grouped or statement is not satisfied. However, the second is, satisfying the grouping.

[Attached in this file](https://github.com/python-poetry/poetry/files/10511601/poetry_debug_output.txt) is the output of a `poetry add scipy statsmodels -vvv` run. Some notable points in the output:
- Poetry derives that `scipy>=1.3` is valid, but not `numpy>=1.17`:
```
   1: fact: statsmodels (0.13.5) depends on scipy (>=1.3)
   1: fact: statsmodels (0.13.5) depends on numpy (>=1.22.3)
```
- Poetry ends up deriving that `numpy>=1.17`, but not `scipy>=1.3`:
```
   1: conflict: no versions of statsmodels match >0.13.5,<0.14.0
   1: ! statsmodels (>0.13.5,<0.14.0) is partially satisfied by not statsmodels (==0.13.5)
   1: ! which is caused by "statsmodels (0.13.5) depends on scipy (>=1.3,<1.9)"
   1: ! thus: statsmodels (>=0.13.5,<0.14.0) requires scipy (>=1.3,<1.9)
   1: ! not scipy (>=1.3,<1.9) is satisfied by scipy (>=1.10.0,<2.0.0)
   1: ! which is caused by "project depends on scipy (^1.10.0)"
   1: ! thus: statsmodels is forbidden
   1: ! statsmodels (>=0.13.5,<0.14.0) is satisfied by statsmodels (>=0.13.5,<0.14.0)
   1: ! which is caused by "project depends on statsmodels (^0.13.5)"
   1: ! thus: version solving failed
```

I believe there is a problem with the way this `requirements.txt` file has been parsed. Please let me know if you have any questions and I'm happy to help!

**Comment by matthewkdies** [comment]
@dimbleby Apologies, but I'm confused. According to my setup and the `statsmodels` requirements, doesn't it imply that `scipy>=1.3` is compatible, but *not* `scipy>=1.3,<1.9`? What makes you say that the most recent versions are incompatible?

Thanks for the reply, and again apologies if I'm missing something obvious 😄.

**Comment by dimbleby** [comment]
eg this line _requires_ a version between 1.3 and 1.9
```
scipy>=1.3,<1.9; python_version=="3.9" and platform_system=="Windows" and platform_machine=="x86"
```
the latest version of scipy is 1.10

**Comment by matthewkdies** [comment]
I understand that the above line requires `scipy>=1.3,<1.9`, however the setup I have implies the requirements would be `scipy>=1.3` and `numpy>=1.17`.

I should also mention that when running this on Python 3.10.X, the installation works as expected. It's merely that the command fails on 3.9.X.

I am not sure why `statsmodels 0.13.5` necessarily incompatible with `scipy 1.10.X` given that system's implied requirements do not exclude 1.9+, and Poetry is able to download the two packages when running on `3.10.X`.

**Comment by dimbleby** [comment]
poetry builds cross-platform lockfiles, the specifics of the system that you are currently on are only barely relevant.

you might not be on windows, but the next person who installs your project could be.  If poetry allowed you to write `statsmodels = "^0.13.5"` and `scipy = "^1.10.0"`, they would have no solution.  But - per #707 - that's what your `poetry add` command effectively does.

As I said some time ago: just `poetry add statsmodels` and let poetry figure out a compatible version of scipy.

**Comment by matthewkdies** [comment]
Sorry for the delayed response, and I appreciate the insight. I didn't know that about the portability of the lock files, so that helped me understand much better why the packages are incompatible. 

I did try the separate `poetry add` commands, and the second `add` fails in both cases regardless of the order. 

Regardless, due to the context of where the `poetry add` occurs, the `add`s have to happen simultaneously. It seems like the solution may be to specify a wider range of versions when running the `add` command, as you mentioned earlier.
