### ISSUE TITLE
Pip install does not respect `poetry.lock`

### ISSUE THREAD

**Issue by lrnq** [python-poetry/poetry#7419]
- **Poetry version**: 1.3.2
- **Python version**: 3.9.13
- **OS version and name**: Mac OS Monterey 12.2.1
- **pyproject.toml**: [Link to gist containing toml file](https://gist.github.com/lrnq/cce5f079e5e64f73f0695a05cc47761c)

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
The gist link contains a `pyproject.toml` file and a `poetry.lock` file. The tree structure of the project is: 
```
.
├── poetry-test
│   └── __init__.py
├── poetry.lock
└── pyproject.toml
```
The file `__init__.py` is empty.  

**Steps to recreate:** Running `pip install .` from the root directory in a fresh virtual enviroment respects the versioning specified in `pyproject.toml`, but **not** the versioning of the lock file. Specifically, it will install `apache-beam` version 2.44.0 despite the lock file specifying version 2.42.0.  

**Expected behaviour:** I expect `pip install .` to respect the lock file and install `apache-beam` version 2.42.0. My understanding (based on the information in [here](https://github.com/python-poetry/poetry-core)) is that this is part of what the following block from the toml file allows us to do.  
```
[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

**Comment by dimbleby** [comment]
poetry-core does not currently understand poetry.lock, this is known and expected behaviour

https://github.com/python-poetry/poetry-core/pull/83 is the last try I know of at making it happen

**Comment by lrnq** [comment]
Thanks, I see. Is this referenced anywhere in the docs? [Here](https://github.com/python-poetry/poetry-core#why-is-this-required) it is mentioned that 

> In order to improve the above situation, poetry-core was created. Shared functionality pertaining to PEP 517 build backends, **including reading lock file**, pyproject.toml and building wheel/sdist, were implemented in this package. This makes PEP 517 builds extremely fast for Poetry managed packages.

**Comment by dimbleby** [comment]
I dunno, I'm sure you can search the docs as well as I can!  merge requests improving them should be welcome

**Comment by neersighted** [comment]
Duplicate #2778
