### ISSUE TITLE
- [extras.pipfile_deprecated_finder.2] 'pip-shims<=0.3.4' does not match '^[a-zA-Z-_.0-9]+$'

### ISSUE THREAD

**Issue by AtitBimali** [python-poetry/poetry#7426]
- [extras.pipfile_deprecated_finder.2] 'pip-shims<=0.3.4' does not match '^[a-zA-Z-_.0-9]+$'

pre-commit log : https://pastebin.com/9mtszQdP

**Comment by dimbleby** [comment]
You've failed to follow the issue template, which makes it hard to help you.

But I expect something is wrong in your pyproject.toml, the error message is telling you where the error is, there is no poetry bug

**Comment by dimbleby** [comment]
I guess this was a duplicate of https://github.com/PyCQA/isort/issues/2077 (which, I see, you duplicated again at https://github.com/PyCQA/isort/issues/2079)

**Comment by neersighted** [comment]
Closing as this is an external issue, it appears that isort has a misspecified extra that was not detected until poetry#7226 was solved.

**Comment by MyLinhRP** [comment]
you can run 

pip install poetry -U

and try again

**Comment by javiermarcon** [comment]
pre-commit autoupdate solved the problem
