### ISSUE TITLE
Poetry ask me add strange `python = ">=3.8, <4"` while run `poetry add requests`

### ISSUE THREAD

**Issue by LaoshuBaby** [python-poetry/poetry#7428]
- **Poetry version**: 1.3.2
- **Python version**: 3.10.4
- **OS version and name**: Microsoft Windows 11 Workstation Insider Preview 10.0.25276 Build 25276
- **pyproject.toml**: https://github.com/OSMChina/Keqing/blob/cd2feb6bf1fba5c40046c2cfdbc4837b796dd0cf/pyproject.toml

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

I follow the instruction in https://python-poetry.org/docs/managing-dependencies/ to add a dependency for my project

I type a `poetry add requests` and hope it can add this package in my pyproject.toml, but error occur. **Do we need to specify python <4 because latest python version is 3.11? Because we all know there won't be python4 in near future.**

I read your FAQ and don't found a `<4` is force needed: https://python-poetry.org/docs/faq/#why-is-poetry-telling-me-that-the-current-projects-python-requirement-is-not-compatible-with-one-or-more-packages-python-requirements

Here are simple log without `-vvv` debug option, for full log with debug option I paste on [ubuntu pastebin](https://pastebin.ubuntu.com/p/D2jHygcK5M/)

```
PS D:\Git\OSMChina\Keqing> poetry add requests
Using version ^2.28.2 for requests

Updating dependencies
Resolving dependencies...

The current project's Python requirement (>=3.8) is not compatible with some of the required packages Python requirement:
  - requests requires Python >=3.7, <4, so it will not be satisfied for Python >=4

Because requests (2.28.2) requires Python >=3.7, <4
 and no versions of requests match >2.28.2,<3.0.0, requests is forbidden.
So, because keqing-sword depends on requests (^2.28.2), version solving failed.

  • Check your dependencies Python requirement: The Python requirement can be specified via the `python` or `markers` properties

    For requests, a possible solution would be to set the `python` property to ">=3.8,<4"

    https://python-poetry.org/docs/dependency-specification/#python-restricted-dependencies,
    https://python-poetry.org/docs/dependency-specification/#using-environment-markers
```

## pyproject.toml

Problem occur in this file: 
https://github.com/OSMChina/Keqing/blob/cd2feb6bf1fba5c40046c2cfdbc4837b796dd0cf/pyproject.toml

## Version

```
PS C:\Users\laoshubaby> poetry --version
Poetry (version 1.3.2)
PS C:\Users\laoshubaby> pip --version
pip 22.3.1 from C:\Environment\Python\Python310\lib\site-packages\pip (python 3.10)
PS C:\Users\laoshubaby> python --version
Python 3.10.4
```

**Comment by finswimmer** [comment]
Hey,

`requests` has defined that it is compatible with Python `>=3.7, <4`. Your project aims to be compatible with a future Python >4, which `requests` isn't compatible with.

fin swimmer
