### ISSUE TITLE
ModuleNotFoundError: No module named 'poetry.console'

### ISSUE THREAD

**Issue by yurivict** [python-poetry/poetry#7432]
```
$ poetry
Traceback (most recent call last):
  File "/usr/local/bin/poetry", line 5, in <module>
    from poetry.console.application import main
ModuleNotFoundError: No module named 'poetry.console'
```

All dependencies declared in pyproject.toml are satisfied.

Version: 1.3.2
Python-3.9
Installed from the FreeBSD port
FreeBSD 13.1

**Comment by dimbleby** [comment]
> Installed from the FreeBSD port

delete your broken installation and use one of the supported install methods per https://python-poetry.org/docs/#installation

(or if you really want to use someone else's installation method... then please take your bug reports to their issue tracker!)

**Comment by yurivict** [comment]
The port is built using the 'build' package which is PEP517 compliant.

**Comment by dimbleby** [comment]
I don't know what that's got to do with anything.  

No-one here knows is responsible for or, I guess, even knows anything about the FreeBSD port.  

If you want help from maintainers of this repository, install poetry via a mechanism that is supported from this repository.

**Comment by neersighted** [comment]
The correct venue for this is https://bugs.freebsd.org; we do not provide support for third-party packages here in the upstream.
