### ISSUE TITLE
Portry picks sys.interpreter for project

### ISSUE THREAD

**Issue by rjalexa** [python-poetry/poetry#7443]
- **Poetry version**: 1.3.2
- **Python version**:
```
Poetry
Version: 1.3.2
Python:  3.11.1

Virtualenv
Python:         3.10.9
Implementation: CPython
Path:           /Users/bob/Documents/work/code/rssita/.venv
Executable:     /Users/bob/Documents/work/code/rssita/.venv/bin/python
Valid:          True

System
Platform:   darwin
OS:         posix
Python:     3.10.9
Path:       /Users/bob/.pyenv/versions/3.10.9
Executable: /Users/bob/.pyenv/versions/3.10.9/bin/python3.10
```
- **OS version and name**: MacOS 13.1 Ventura
- **pyproject.toml**: https://gist.github.com/rjalexa/79a965f1f17e424dcfa830251f0a6a04

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
poetry new writes wrong version of python (3.11) in the newly generated pyproject.toml file, despite pyenv sets 3.10.9 as both local and global versions. python --version in the shell gives 3.10.9. 
```
(base) bob@Roberts-Mac-mini rssita % which python
/Users/bob/.pyenv/shims/python
(base) bob@Roberts-Mac-mini rssita % /Users/bob/.pyenv/shims/python --version
Python 3.10.9
```
```
pyenv versions
system
* 3.10.9 (set by /Users/bob/Documents/work/code/rssita/.python-version)
  3.11.1

```

**Comment by neersighted** [comment]
Not a bug. Per the documentation you must set `virtualenvs.prefer-active-python` to use the current Python instead of `sys.interpreter`.

**Comment by rjalexa** [comment]
I see. Thank a lot for clearing this up. Is there a forum/board/discord to ask for peer to peer help to avoid posting these non-bugs here? Ciao from Rome - Italy

**Comment by neersighted** [comment]
There are links to our [Discord server](https://discord.com/invite/awxPgve) all over the repo, and you actually had to click past one to open this issue. That same menu has links to our [GitHub discussions](https://github.com/python-poetry/poetry/discussions), which are also linked in the tabs of the GitHub UI.

**Comment by rjalexa** [comment]
LOL nice username. I'm nearsighted too and a good example of "inattentional blindness". Thank you.
