### ISSUE TITLE
Unable to install psycopg3 binary

### ISSUE THREAD

**Issue by j-adamczyk** [python-poetry/poetry#7458]
- **Poetry version**: 1.3.1
- **Python version**: 3.10.6
- **OS version and name**: Ubuntu 22.04

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
[psycopg3](https://www.psycopg.org/psycopg3/docs/basic/install.html#binary-installation) contains the "optional" binary version, installed via pip by `pip install "psycopg[binary]"`. This is not really a typical optional addition, but instead, it should install another package, `psycopg-binary`, with version compatible with `psycopg` version.

I tried using:
```
psycopg = {extras = ["binary"], version = "3.*"}
```

This should result in both `psycopg` and `psycopg-binary` installed. However, after `pip list` I get only `psycopg`:
```
psycopg                  3.1.8
```

After manual `pip install "psycopg2[binary]"` I get:
```
Requirement already satisfied: psycopg[binary] in /usr/local/lib/python3.10/site-packages (3.1.8)
Requirement already satisfied: typing-extensions>=4.1 in /usr/local/lib/python3.10/site-packages (from psycopg[binary]) (4.4.0)
Collecting psycopg-binary<=3.1.8,>=3.1.6
  Downloading psycopg_binary-3.1.8-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 5.5 MB/s eta 0:00:00
Installing collected packages: psycopg-binary
Successfully installed psycopg-binary-3.1.8
```

**Expected behavior:** all packages installed, exactly like regular `pip install`.

**Comment by dimbleby** [comment]
does not reproduce
```
$ poetry add 'psycopg[binary]'
Using version ^3.1.8 for psycopg

Updating dependencies
Resolving dependencies... (0.9s)

Writing lock file

Package operations: 3 installs, 0 updates, 0 removals

  • Installing psycopg-binary (3.1.8)
  • Installing typing-extensions (4.4.0)
  • Installing psycopg (3.1.8)

$ pip list
Package           Version
----------------- -------
pip               23.0
psycopg           3.1.8
psycopg-binary    3.1.8
setuptools        67.1.0
typing_extensions 4.4.0
```

**Comment by ruslaniv** [comment]
Ok, whoever spent like a day (like me) trying to install `psycopg3`, trying all sorts of command comninations and has been getting **ALL** kinds of errors starting from specified package not found to specified package version not  found, just add this to you `pyproject.toml`:
```
psycopg = {extras = ["binary"], version = "^3.1.9"}
```

although why I can't just specify the following as the installation docs on psycopg suggest, I don't know 
```
"psycopg[binary]" = "^3.1.9"
```
