### ISSUE TITLE
"hash" value in file direct_url.json uses incorrect separator

### ISSUE THREAD

**Issue by chopeen** [python-poetry/poetry#7460]
- **Poetry version**: 1.3.2
- **Python version**: 3.8.16
- **OS version and name**: Ubuntu 20.04.5 LTS (Focal Fossa)
- **pyproject.toml**: https://gist.github.com/chopeen/ab18e5490fad88698ac6ed2dd5ba4435

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

After running `poetry install`, there is a file `direct_url.json` under `en_core_web_sm-3.5.0.dist-info`, with the following contents (below I formatted it for readability):

```
{
  "url": "https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.5.0/en_core_web_sm-3.5.0.tar.gz",
  "archive_info": {
    "hash": "sha256:63d38fecdd4290635c7af4d4f6da50902bdc6c1732ce416b55c2b76c4b0c4626"
  }
}
```

The **colon** `:` separator after `sha256` is does not comply with the [PyPA spec](https://packaging.python.org/en/latest/specifications/direct-url/#specification:~:text=A%20deprecated%20hash%20key%20(type%20string)%20MAY%20be%20present%20for%20backwards%20compatibility%20purposes%2C%20with%20value%20%3Chash%2Dalgorithm%3E%3D%3Cexpected%2Dhash%3E.):

> A deprecated hash key (type `string`) MAY be present for backwards compatibility purposes, with value `<hash-algorithm>=<expected-hash>`.

It should be **equals** sign.

Because of that issue, pip v23.0 crashes when trying to list packages in a Poetry environment that contains archives installed from URL - see https://github.com/pypa/pip/issues/11773 for details.

**Comment by dimbleby** [comment]
```patch
diff --git a/src/poetry/installation/executor.py b/src/poetry/installation/executor.py
index 0496a5f8..e5582413 100644
--- a/src/poetry/installation/executor.py
+++ b/src/poetry/installation/executor.py
@@ -798,7 +798,8 @@ class Executor:
         archive_info = {}

         if package.name in self._hashes:
-            archive_info["hash"] = self._hashes[package.name]
+            algorithm, value = self._hashes[package.name].split(":")
+            archive_info["hashes"] = {algorithm: value}

         reference = {"url": package.source_url, "archive_info": archive_info}
```

probably, if anyone wants to put together a merge request and drive this through.

The number of testcases that fail on making that change - zero - suggests a gap that should probably be filled at the same time (which I am too lazy to fill myself!)

**Comment by chopeen** [comment]
Thank for the hint @dimbleby!

I have just submitted PR https://github.com/python-poetry/poetry/pull/7475.
