### ISSUE TITLE
Run last command in terminal

### ISSUE THREAD

**Issue by Alchemmist** [python-poetry/poetry#7466]
# Repeat last command

Hi, thanks for your answerer! I detect problem: 
Not working repeating the last command by the arrows in venv. When I activated the virtual environment (`poetry shell`) and execute some command (for example, `python main.py `) and then I want to repeat this command by clicking on the up arrow, then nothing happens.

**Comment by neersighted** [comment]
Hi, thanks for opening an issue against Poetry! We can't help you without a bunch of important information like your versions, the inputs you are feeding Poetry, the output of commands, and background information. We have an issue template that helps you gather these details. Can you please edit this issue to follow the template and comment here so we can re-open this issue, or open a new issue that follows the template properly?
