### ISSUE TITLE
Poetry + Private Gitlab Repository - Not working

### ISSUE THREAD

**Issue by burnpanck** [python-poetry/poetry#7467]
- **Poetry version**: 1.3.2
- **Python version**: 3.11.1
- **OS version and name**: macOS 13.1

- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
We have a private package registry on gitlab, to wich we have successfully published several private python packages (they are build using `setuptools`). In a new project, we want to depend on some of those private packages, and we want to use poetry to manage the dependencies. However, `poetry add private-package --source=private-registry` fails with `401 Client Error: Unauthorized for url` fails when trying to download the wheel for that package, despite successfully finding available versions from the `private-registry` beforehand. Our `pyproject.toml` includes the following configuration:
```toml
[[tool.poetry.source]]
name = "private-registry"
url = "https://<gitlab+deploy-token-name>:<token>@gitlab.com/api/v4/projects/<gitlab-project-id>/packages/pypi/simple"
default = false
secondary = true
```
This is supposed to work following [this issue comment](https://github.com/python-poetry/poetry/issues/2062#issuecomment-1056793536). The deploy token has the `read_regsitry` as-well as the `read_package_registry` permissions. We have also tried storing credentials using `poetry config ...` as detailed further down in that comment, to no avail.

The output from `poetry add ... -vvv` contains the following (some lines removed for readability):
```
Creating new session for <gitlab+deploy-token-name>:<token>@gitlab.com
[urllib3.connectionpool] https://gitlab.com:443 "GET /api/v4/projects/<gitlab-project-id>/packages/pypi/simple/private-package/ HTTP/1.1" 304 0
Source (private-repository): 2 packages found for private-package *
Source (private-repository): 1 packages found for private-package >=0.1.1,<0.2.0
Source (private-repository): Downloading wheel: private-package-0.1.1-py3-none-any.whl
Creating new session for gitlab.com
[urllib3.connectionpool] https://gitlab.com:443 "GET /api/v4/projects/<gitlab-project-id>/packages/pypi/files/b9cfe74040f6ddcc688b577f1c6b7a8a82fc656a9f991057156257ff09faff58/private-package-0.1.1-py3-none-any.whl HTTP/1.1" 401 30
```
after which the `401 Client Error` is raised. This looks to me as if the authentication that was used to query the registry is not re-used when downloading the wheel. Any hints on how this is supposed to work would be greatly appreciated.

**Comment by dimbleby** [comment]
I wouldn't expect what you're trying to do to work, for exactly the reason you give.  It surprises me that someone thinks they made it work.

I do agree with the bit of that comment that says that putting secrets in pyproject.toml is a bad idea and which says how to avoid it - did you read that bit?

Docs: https://python-poetry.org/docs/repositories/#configuring-credentials

**Comment by burnpanck** [comment]
Unfortunately, there seem to be a lot of contradictory statements on this and related issues floating around in the various threads that google brings up. So thanks for clarifying that this is not supposed to work indeed.

So I tried again using the `poetry config` approach, and somehow it does now work indeed. One gotcha definitely is that `poetry config` of auth does *not* help as long as the gitlab deploy token is still provided as part of the source link in `pyproject.toml`, probably because the urls do not match exactly.

Anyway, thanks for the help!
