### ISSUE TITLE
peotry publish don't promote for cridential

### ISSUE THREAD

**Issue by link89** [python-poetry/poetry#7476]
I am using  poetry v1.3.2 and when I run `poetry publish` it throws me with the following error

```
HTTP Error 403: Invalid or non-existent authentication information. See https://pypi.org/help/#invalid-auth for more information. | b'<html>\n <head>\n  <title>403 Invalid or non-existent authentication information. See https://pypi.org/help/#invalid-auth for more information.\n \n <body>\n  <h1>403 Invalid or non-existent authentication information. See https://pypi.org/help/#invalid-auth for more information.\n  Access was denied to this resource.<br/><br/>\nInvalid or non-existent authentication information. See https://pypi.org/help/#invalid-auth for more information.\n\n\n \n'
```
It is supposed to have a promote to allow user to type username and password if they are missing. I don't know why this don't work any more.

**Comment by dimbleby** [comment]
> It is supposed to have a promote to allow user to type username and password if they are missing

No.  Code like this existed for a while but it has been broken for years - https://github.com/python-poetry/poetry/issues/4349 - and was removed.

You should configure credentials per the docs https://python-poetry.org/docs/repositories/#configuring-credentials
