### ISSUE TITLE
Dependency group feature breaks managing environment support for python 3.5 & 3.6

### ISSUE THREAD

**Issue by garb-ma** [python-poetry/poetry#7477]
- **Poetry version**: 1.3.1
- **Python version**: 3.10.1 (pipx); 3.5 & 3.6 (environments)
- **OS version and name**: Debian GNU/Linux 9, Ubuntu 22.04
- **pyproject.toml**: 

Parent:
```
[build-system]
requires = ["poetry-core>=1.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "ParentProject"
version = "0.0.1"
description = ""

[tool.poetry.dependencies]
python = "~2.7 || ^3.5"
...

[tool.poetry.group.test.dependencies]
AFancyTestProject = { git = "<gitlab.internal>", develop=true, python = "~3.7.1" }

[tool.poetry.group.test]
optional = true
```

Child:
```
[build-system]
requires = ["poetry-core>=1.0", "mkl-devel"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "ChildProject"
version = "1.0.0"

[tool.poetry.dependencies]
python = "~2.7 || ^3.5"
...
ParentProject = { git = "<gitlab.internal>" }
```

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
I run into a discrepancy using poetry with my approach and believe this is a bug. I am trying to set up a project environment for python 3.5 & 3.6 with the latest poetry version (1.3.1) installed with pipx. This is my setup:
- I have a child project whose environment I want to manage using poetry for python 3.5 and python 3.6. This project depends on a parent project.
- The parent project uses the group dependencies feature introduced with poetry 1.2 to install additional dependencies for tests.

The sanitized pyproject.toml files can be found above.

***

Now I want to install my child project like this:

`pipx install poetry` - Install poetry 1.3.1
`poetry config virtualenvs.in-project true` - Install all dependencies within the current project.
`poetry env use py35 ; py36` - Select python version
`poetry install`

However, this fails for python 3.5 and 3.6 with the following output (shortened): 

> File "/builds/.../**ChildProject**/.venv/lib/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 164, in prepare_metadata_for_build_wheel
>         return hook(metadata_directory, config_settings)
>       File "/tmp/pip-build-env-w2xlk7i3/overlay/lib/python3.6/site-packages/poetry/core/masonry/api.py", line 43, in prepare_metadata_for_build_wheel
>         poetry = Factory().create_poetry(Path(".").resolve(), with_dev=False)
>       File "/tmp/pip-build-env-w2xlk7i3/overlay/lib/python3.6/site-packages/poetry/core/factory.py", line 43, in create_poetry
>         raise RuntimeError("The Poetry configuration is invalid:\n" + message)
>     RuntimeError: The Poetry configuration is invalid:
>       - Additional properties are not allowed ('group' was unexpected)

It works with python 3.7 and above. 

***

I already tested various workarounds, including: 
- Increasing the build-system requirement in both the parent and the child project from `>= 1.0 to >= 1.5 (latest)`
- Including all git dependencies with develop=true

But the error message remains. It seems obvious to me that this is caused by the group feature, which is not supported by older versions of poetry-core, which seems to be used during the installations process. I am aware of the following announcement with respect to environment [support](https://python-poetry.org/blog/announcing-poetry-1.2.0/). However, it clearly states that:

> This change is about installing and running Poetry itself. Managing projects requiring Python 3.5 and 3.6, as well as older Python 3 versions is still supported.

So, in my opinion, I still should be able to manage my project environment for py35 and py36 with a poetry version above 1.3 and a base python version of 3.10.x

***

Lastly, I was able to find a workaround - which further indicates to me that this behaviour is unintended. When I run:
`poetry update && poetry install` instead of just `poetry install`, everything installs perfectly. It just takes much, much longer.

Best regards,

**Comment by dimbleby** [comment]
poetry-core dropped support for python 3.6, so using it as a build backend in a python 3.6 environment will necessarily pick up an old poetry-core.

Managing python 3.6 projects using poetry does remain possible, using new poetry-core as a backend does not.

**Comment by neersighted** [comment]
This is indeed just a result of an old build-system not supporting new features; you need to not use the new features if you must use the older build-system (poetry-core on EOL Python).
