### ISSUE TITLE
'Poetry remove' removes too much

### ISSUE THREAD

**Issue by Hillowgg** [python-poetry/poetry#7479]
Poetry (version 1.3.2)
Python:         3.10.4
macOS 13.0
pyproject.toml: https://gist.github.com/Hillowgg/bcc15dd43a3dad5e99a1094e306318b9

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
1) I've installed aiogram.(so it uses other packages)
2) then i needed to delete it, i wrote "poetry remove aiogram"
3) Poetry removed all necessary dependences with ["idna", "certifi", "charset_normalizer"], which are used in requests and poetry
4) so after poetry stoped working at all, because it is in lack of its dependences

**Comment by dimbleby** [comment]
> poetry stoped working at all, because it is in lack of its dependences

it sounds as though you have installed poetry inside the virtual environment that it is also managing.  This is a bad idea, for the reasons that you are discovering.

Please follow the installation instructions https://python-poetry.org/docs/#installation

**Comment by Hillowgg** [comment]
> > poetry stoped working at all, because it is in lack of its dependences
> 
> it sounds as though you have installed poetry inside the virtual environment that it is also managing. This is a bad idea, for the reasons that you are discovering.
> 
> Please follow the installation instructions https://python-poetry.org/docs/#installation

yeah, this is in venv, but i dont think, that it is right behaviour

**Comment by dimbleby** [comment]
>  i dont think, that it is right behaviour

Nevertheless, it is.  Please follow the documented instructions for how to use poetry.
