### ISSUE TITLE
add command fetches incorrect package version

### ISSUE THREAD

**Issue by mbway** [python-poetry/poetry#7481]
- **Poetry version**: `Poetry (version 1.3.2)`
- **Python version**: `3.10.6`
- **OS version and name**: `Ubuntu 22.04.1 LTS`

- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
I am having an issue with adding a package to a project where the package is built against different interpreter versions.

Because the package contains compiled components which are expecting a particular interpreter version each build of the package has a different `Requires-Python` specifier

For example in the repository I have:

```
somepackage-0.1.0-cp310-cp310-manylinux_2_24_x86_64.whl
somepackage-0.1.0-cp38-cp38-manylinux_2_24_x86_64.whl
somepackage-0.1.0-cp39-cp39-manylinux_2_24_x86_64.whl
```

and for example the `cp310` version of the package has
```
Requires-Python: >=3.10, <3.11
```
and the `cp39` version of the package has
```
Requires-Python: >=3.9, <3.10
```

If I create a project which requires `python = "3.9.9"` and run

```
poetry config virtualenvs.prefer-active-python true
PATH=/path/to/python3.9.9 poetry add somepackage --python=3.9.9
```

poetry will download the `cp310` build of the package (because poetry itself is running under python 3.10) then fail with
```
  SolverProblemError

  The current project's Python requirement (3.9.9) is not compatible with some of the required packages Python requirement:
    - somepackage requires Python >=3.10, <3.11, so it will not be satisfied for Python 3.9.9
```

Looking at the code, as-of `Provider.complete_package()` the `DependencyPackage` object has `python_constraint=3.9.9` but this is discarded when passed to `RepositoryPool.package`. Should the python version specifier be taken into account when deciding which file to download from the repo during solving?

I have read through <https://packaging.python.org/en/latest/specifications/core-metadata/#core-metadata> but I can't see anywhere that specifies that different builds of the package must have the same metadata. If this is indeed the convention is it documented anywhere? I assume at least builds for different platforms are allowed to have different metadata?

I have also seen packages whose wheels for a specific interpreter have `Requires-Python` set loosely (eg a `cp310` package with `Requires-Python: >= 3.7`) so this issue doesn't affect all packages.

**Comment by dimbleby** [comment]
> Because the package contains compiled components which are expecting a particular interpreter version each build of the package has a different Requires-Python specifier

you should simply use `Requires-Python: >= 3.9` (or whatever the lowest supported version is) in all of the distributions of `somepackage`.  The package name is sufficient for installers to then choose the correct distribution.

**Comment by mbway** [comment]
that's what I suspected but is this requirement documented anywhere? Is the package invalid if it does not follow this?
I do happen to be in a situation where I can re-package this dependency but what if it was a third party dependency?

**Comment by dimbleby** [comment]
poetry assumes that the metadata is the same for all distributions of a package.  

This isn't required to be true in general - but in practice it holds nearly all of the time (poetry's success is kind of an existence proof that this is the case).
