### ISSUE TITLE
(📚) Include a blurb in the section for 'Exact requirements' that says the difference without the `==` 

### ISSUE THREAD

**Issue by KotlinIsland** [python-poetry/poetry#7485]
- [🚀] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

What is the difference between `pendulum = "2.1.2"` and `pendulum = "==2.1.2"`.

In fact, the 'Dependency specification' page doesn't mention bare dependencies at all, which are the type that Poetry adds.
ie: `👉 poetry add pendulum==2.1.2` -> `pendulum = "2.1.2"`.

**Comment by radoering** [comment]
There is no difference:

```
>>> from poetry.core.constraints.version import parse_constraint
>>> parse_constraint('2.1.2') == parse_constraint('==2.1.2')
True
```

Relevant part of the code: https://github.com/python-poetry/poetry-core/blob/b5d1934fed190bbfd1a303b44d5e2ef9a600efed/src/poetry/core/constraints/version/parser.py#L155-L165

**Comment by KotlinIsland** [comment]
Thought so. Is there any preference? the `==` part seems redundant at this point, I wonder why it exists, maybe it could be deprecated.

**Comment by Secrus** [comment]
> Thought so. Is there any preference? the `==` part seems redundant at this point, I wonder why it exists, maybe it could be deprecated.

We are currently working towards supporting PEP 621 (pyproject metadata spec) and there will probably be a lot of changes and deprecations then. I don't think it makes sense to deprecate this right now.

**Comment by neersighted** [comment]
It's not even redundant -- we explicitly support PEP 440 style specifiers, but have our own features 'on top' (no `==`, `^`, etc).

PEP 621 will require Poetry to drop its own custom features in favor of the ecosystem-standard specifiers; if anything we may explore deprecating our syntax sugar.
