### ISSUE TITLE
Poetry shows more files for reformatting if --exclude flag is present

### ISSUE THREAD

**Issue by VeArnold** [python-poetry/poetry#7490]
**Pre-checks**
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.

**Versions**
- **Poetry version**: Poetry (version 1.3.2)
- **Python version**: Python 3.10.9
- **OS version and name**: macOS Monterey Version 12.6

## Issue
I am getting different output from Poetry depending on whether I include the `--exclude` flag. Note that more files are checked/formatted with the flag present (which seems counter-intuitive). None of the paths/files found with the flagged command are related to the excluded path.

```
(sad) arnoldveltmann@Arnolds-MacBook-Pro builder % poetry run black --check .
All done! ✨ 🍰 ✨
62 files would be left unchanged.

(sad) arnoldveltmann@Arnolds-MacBook-Pro builder % poetry run black --check --exclude .venv .
...
...

Oh no! 💥 💔 💥
8 files would be reformatted, 201 files would be left unchanged.
```

**Comment by Secrus** [comment]
You are running `black`, and `poetry run` passes all given arguments to the executable you are running. No Poetry command has the `--exclude` option.

**Comment by VeArnold** [comment]
Thanks, sorry, I made this issue into the wrong repository.
