### ISSUE TITLE
Poetry fail to install in github actions using deploy key

### ISSUE THREAD

**Issue by shelper** [python-poetry/poetry#7491]
- **Poetry version**: 1.3.2
- **Python version**: 3.8.13
- **OS version and name**: ubuntu 22.04
- **pyproject.toml**: https://gist.github.com/shelper/74b2fd7149a220ba161fa6118d192a28 

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

I have a Python project using Poetry, and I need to access another private repo called `another_pgk` on Github when running the Github Actions. So I use [https://github.com/webfactory/ssh-agent][1] to setup my ssh key, this key is a deploy key for `another_pgk` that enables me to only have read access to this `another_pgk` repo. In my `pyproject.toml`, I have the private repo added as:

    another_pgk= {git = "git@github.com:username/another_pgk.git", branch = "main"}

It seems that the ssh key is added successfully because after the step of setting up the ssh key, the action script is able to clone the code by `git clone git@github.com:username/another_pgk.git`. But if I run `Poetry install`, it fails, with the following message:

    HangupException
    
      The remote server unexpectedly closed the connection.
    
      at C:\Program Files (x86)\pipx\venvs\poetry\lib\site-packages\dulwich\protocol.py:220 in read_pkt_line
          216| 
          217|         try:
          218|             sizestr = read(4)
          219|             if not sizestr:
        > 220|                 raise HangupException()
          221|             size = int(sizestr, 16)
          222|             if size == 0:
          223|                 if self.report_activity:
          224|                     self.report_activity(4, "read")
    
    The following error occurred when trying to handle this error:
    
    
      HangupException
    
      Warning: Permanently added the ECDSA host key for IP address '192.30.255.112' to the list of known hosts.
    
      Load key "C:\\Users\\runneradmin/.ssh/key-52016bfd3f72432689e062517edb001705ef0a8d1af12eb63b188417c75ca43e": invalid format
    
      git@github.com: Permission denied (publickey).
    
    
      at C:\Program Files (x86)\pipx\venvs\poetry\lib\site-packages\dulwich\client.py:1151 in fetch_pack
          1147|         with proto:
          1148|             try:
          1149|                 refs, server_capabilities = read_pkt_refs(proto.read_pkt_seq())
          1150|             except HangupException as exc:
        > 1151|                 raise _remote_error_from_stderr(stderr) from exc
          1152|             (
          1153|                 negotiated_capabilities,
          1154|                 symrefs,
          1155|                 agent,

so, why is that, and how do I fix it? or does poetry supports deploy key or not?

  [1]: https://github.com/webfactory/ssh-agent

**Comment by dimbleby** [comment]
#5893 describes a more complicated scenario but reported along the way that "When using 1 repository and 1 deploy key - everything works as expected."

I'd suggest that you should concentrate on this bit:
```
Load key "C:\\Users\\runneradmin/.ssh/key-52016bfd3f72432689e062517edb001705ef0a8d1af12eb63b188417c75ca43e": invalid format
```

**Comment by shelper** [comment]
okay, i think the root cause is the path cannot take "/" as path seperator for windows for ssh-agent, reported at https://github.com/webfactory/ssh-agent/issues/162, closing this one

**Comment by levrik** [comment]
I'm seeing this error suddenly happening since yesterday as well but on a Linux-based runner.

```
The following error occurred when trying to handle this error:


  HangupException

  Warning: Permanently added the ECDSA host key for IP address '140.82.113.3' to the list of known hosts.
  Load key "/home/runner/.ssh/id_rsa": invalid format
  git@github.com: Permission denied (publickey).
```

https://github.com/webfactory/ssh-agent/issues/162 seems to be unrelated.
