### ISSUE TITLE
Poetry prints my_project does not contain any element after running poetry install

### ISSUE THREAD

**Issue by keystroke3** [python-poetry/poetry#7495]
- **Poetry version**:  1.3.2
- **Python version**: 3.10.6
- **OS version and name**:  Ubuntu 22.04
- **pyproject.toml** [sample](https://gist.github.com/keystroke3/35fcb840ecf47b00d6975731e6443f3b)

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

I git cloned a python project that used poetry and ran `poetry install`. Everything installed fine and then at the end, this message was displayed:
```
/home/ubuntu/my_project/my_project does not contain any element
```
My virtual environment as not activated automatically in ZSH.

**Comment by dimbleby** [comment]
https://gist.github.com/keystroke3/35fcb840ecf47b00d6975731e6443f3b#file-pyproject-toml-L7 tells poetry that you have a package in `my_project`.  

what is the contents of `/home/ubuntu/my_project/my_project`?

If you've copied this from some broken project, please raise the issue over there

**Comment by keystroke3** [comment]
I see it was a misconfiguration during `poetry init`. Removing the line `packages = [{include = "my_project"}]` fixed it. Thanks

**Comment by anoduck** [comment]
Just as a general notation:

The same error will occur if your project name contains "-" rather than "_". Python does not like the former, but accepts the later.
