### ISSUE TITLE
Show Dependency chain during poetry install

### ISSUE THREAD

**Issue by glass-ships** [python-poetry/poetry#7496]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request
It would be quite useful if poetry organized packages being installed into dependency groups and information about dependencies of dependencies. 

For example something like:
```
> poetry install
Creating virtualenv monarch-py in D:\dev\my_project\.venv
Installing dependencies from lock file

Package operations: 131 installs, 1 update, 0 removals

=> Project dependencies
  • Installing some_library (1.2.3)
=> Project dependencies - [dev]
  • Installing pytest (7.2.1)
=> Dependencies of some_library:
  • Installing pyyaml (6.0)
  • Updating setuptools (67.1.0 -> 67.2.0)
  • Installing sh (1.14.0)
```

**Comment by dimbleby** [comment]
why would this be useful?  does `poetry show --why` meet that need?

**Comment by glass-ships** [comment]
part of me was thinking it'd be nice to see during the installation process to more immediately see which package is causing the issue, and why it's there, so a kind of tracing. 
(especially if you have access to some of the upstream packages)

but a `poetry show --why` before or after the fact would actually suffice, yeah! kinda. forgot about that option, thank you!
