### ISSUE TITLE
poetry run doesn't work well with --directory

### ISSUE THREAD

**Issue by OrangeTux** [python-poetry/poetry#7507]
- **Poetry version**: 1.3.2
- **Python version**: Python:  3.10.0
- **OS version and name**: Arch, Kernel version 6.1.10
- **pyproject.toml**: https://gist.github.com/OrangeTux/9b5269bc7070ed43e94f7ad9efb119e4

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
Calling `poetry --directory=<something> run ls` doesn't work. 

Steps to reproduce

1. Create a new project using `poetry new issue`.
2. Call `poetry --directory=issue version`. This should correctly show `issue 0.1.0` 
3. Call `poetry --directory=issue run ls`. I expect the see content of my current working directory.
```
 poetry -vv  --directory=issue run ls

  Stack trace:

  12  ~/.pyenv/versions/3.10.0/lib/python3.10/site-packages/cleo/application.py:327 in run
        exit_code = self._run(io)

  11  ~/.pyenv/versions/3.10.0/lib/python3.10/site-packages/poetry/console/application.py:190 in _run
        exit_code: int = super()._run(io)

  10  ~/.pyenv/versions/3.10.0/lib/python3.10/site-packages/cleo/application.py:431 in _run
        exit_code = self._run_command(command, io)

   9  ~/.pyenv/versions/3.10.0/lib/python3.10/site-packages/cleo/application.py:473 in _run_command
        raise error

   8  ~/.pyenv/versions/3.10.0/lib/python3.10/site-packages/cleo/application.py:454 in _run_command
        self._event_dispatcher.dispatch(command_event, COMMAND)

   7  ~/.pyenv/versions/3.10.0/lib/python3.10/site-packages/cleo/events/event_dispatcher.py:26 in dispatch
        self._do_dispatch(listeners, event_name, event)

   6  ~/.pyenv/versions/3.10.0/lib/python3.10/site-packages/cleo/events/event_dispatcher.py:89 in _do_dispatch
        listener(event, event_name, self)

   5  ~/.pyenv/versions/3.10.0/lib/python3.10/site-packages/poetry/console/application.py:296 in configure_env
        poetry = command.poetry

   4  ~/.pyenv/versions/3.10.0/lib/python3.10/site-packages/poetry/console/commands/command.py:23 in poetry
        return self.get_application().poetry

   3  ~/.pyenv/versions/3.10.0/lib/python3.10/site-packages/poetry/console/application.py:129 in poetry
        self._poetry = Factory().create_poetry(

   2  ~/.pyenv/versions/3.10.0/lib/python3.10/site-packages/poetry/factory.py:55 in create_poetry
        base_poetry = super().create_poetry(cwd=cwd, with_groups=with_groups)

   1  ~/.pyenv/versions/3.10.0/lib/python3.10/site-packages/poetry/core/factory.py:47 in create_poetry
        poetry_file = self.locate(cwd)

  RuntimeError

  Poetry could not find a pyproject.toml file in /tmp or its parents

  at ~/.pyenv/versions/3.10.0/lib/python3.10/site-packages/poetry/core/factory.py:453 in locate
      449│             if poetry_file.exists():
      450│                 return poetry_file
      451│
      452│         else:
    → 453│             raise RuntimeError(
      454│                 f"Poetry could not find a pyproject.toml file in {cwd} or its parents"
      455│             )
      456│
```

**Comment by dimbleby** [comment]
basically the same confusion as #7363 I think

**Comment by OrangeTux** [comment]
I'm not sure. For me, any command passed to `poetry run` fails when used together `--directory`.

**Comment by dimbleby** [comment]
this issue and the other both describe the (understandable) mistaken belief that `--directory` is setting the working directory for the command you are trying to run.  

It's not, it's telling poetry where to find `pyproject.toml`.

As in that one, merge requests improving the documentation are encouraged

**Comment by OrangeTux** [comment]
That is not where my confusion is. It's not the case that the `ls` returns the content of an unexpected folder. It doesn't work at all. 

I updated my openings post to avoid ambiguity

**Comment by dimbleby** [comment]
per my update, you should be calling `poetry run --directory issue ls`.  Not `poetry --directory run issue ls`.

(like what `poetry run --help` tells you)

**Comment by Agalin** [comment]
I believe there is a bug but a different one.

This works:
```
poetry --directory issue run ls
```

This does not:
```
poetry --directory=issue run ls
```

It gets even stranger when you try to pass both versions.

Check this:
```
/tmp/poetry_test # poetry --directory issue run ls # this one is ok
issue
/tmp/poetry_test # poetry --directory=issue run ls # this one is wrong

Poetry could not find a pyproject.toml file in /tmp/poetry_test or its parents
/tmp/poetry_test # poetry  --directory /tmp --directory=issue run ls # if we pass "--directory" twice and first one doesn't have "=" then it works consistently
issue
/tmp/poetry_test # poetry  --directory issue --directory=/tmp run ls

Poetry could not find a pyproject.toml file in /tmp or its parents
/tmp/poetry_test # poetry  --directory=issue --directory /tmp run ls # If we paass "directory" twice it just picks the second one? Not really...

Poetry could not find a pyproject.toml file in /tmp or its parents
/tmp/poetry_test # poetry  --directory=/tmp --directory issue run ls # this one is really strange
Command not found: run
```

So it looks like `--directory <path>` sets the global option for `pyproject.toml` location but `--directory=<path>` sets the working directory for `run` command... regardless of it appearing before or after `run`. It goes against the example in help: which uses `=`.
```
/tmp/poetry_test # poetry --help

<cut>
  -C, --directory=DIRECTORY  The working directory for the Poetry command (defaults to the current working directory).
<cut>
```

And what happens in those cases with `--directory` passed multiple times? I have absolutely no idea. Especially in the case ending with `Command not found`.
