### ISSUE TITLE
b'Head' on 'poetry update' or 'poetry lock'

### ISSUE THREAD

**Issue by betterthanever2** [python-poetry/poetry#7523]
- **Poetry version**: 1.3.2
- **Python version**: 3.10.5
- **OS version and name**: Windows10 Pro 19045.2604
- **pyproject.toml**: https://gist.github.com/betterthanever2/885e1448343a4dd9b507acd3c762f549
- 

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

There isn't much to describe: whenever invoking a `poetry update` or `poetry lock` command, with or without additional arguments, I get one line printed `b'HEAD`, and nothing else happens. No exception occurs either. 
Command `poetry show {package}` works alright, as well as `poetry help`
When this started happening first, I was on 1.2.smth version, but this compelled me to upgrade to 1.3.2, however this didn't solve the issue.

**Comment by dimbleby** [comment]
your pyproject.toml includes some local path dependencies, meaning that it's not possible for anyone else to take it and use it.  If you can provide a smaller reproducible example that would be helpful.

Previously: #6873 looks similar but that did not reproduce.  Presumably whatever was happening there was something local to the reporter's computer, but we never did get to the bottom of what it was.  

You could try creating a fresh virtual environment and seeing whether the problem persists

- if it does, then please provide a way for someone else to reproduce that
- if it doesn't, then it would be great if you could investigate what's different between broken and not-broken environments...

**Comment by betterthanever2** [comment]
Believe it or not, local dependencies have 0 to do with this.
Anyway, I created a new env, and it doesn't have this problem, all commands work just fine. Gonna investigate deeper, but I would appreciate some pointers on where to look.

**Comment by dimbleby** [comment]
you didn't show the result of adding `-vvv` to the command  - with any luck that'll give a stack that's some sort of clue.

this is surely related to a git dependency somewhere, I imagine that there's something about the state of some git checkout in the broken environment that is making something unhappy.  (It's hard to be more specific when literally all we have to go on is four characters!)

**Comment by betterthanever2** [comment]
damn, my bad. Here's the stacktrace:
```
  Stack trace:

  19  ~\AppData\Roaming\pypoetry\venv\lib\site-packages\cleo\application.py:327 in run
       325│ 
       326│             try:
     → 327│                 exit_code = self._run(io)
       328│             except BrokenPipeError:
       329│                 # If we are piped to another process, it may close early and send a

  18  ~\AppData\Roaming\pypoetry\venv\lib\site-packages\poetry\console\application.py:190 in _run
       188│         self._load_plugins(io)
       189│
     → 190│         exit_code: int = super()._run(io)
       191│         return exit_code
       192│

  17  ~\AppData\Roaming\pypoetry\venv\lib\site-packages\cleo\application.py:431 in _run
       429│             io.input.interactive(interactive)
       430│
     → 431│         exit_code = self._run_command(command, io)
       432│         self._running_command = None
       433│

  16  ~\AppData\Roaming\pypoetry\venv\lib\site-packages\cleo\application.py:473 in _run_command
       471│ 
       472│         if error is not None:
     → 473│             raise error
       474│
       475│         return terminate_event.exit_code

  15  ~\AppData\Roaming\pypoetry\venv\lib\site-packages\cleo\application.py:454 in _run_command
       452│ 
       453│         try:
     → 454│             self._event_dispatcher.dispatch(command_event, COMMAND)
       455│
       456│             if command_event.command_should_run():

  14  ~\AppData\Roaming\pypoetry\venv\lib\site-packages\cleo\events\event_dispatcher.py:26 in dispatch
        24│ 
        25│         if listeners:
     →  26│             self._do_dispatch(listeners, event_name, event)
        27│
        28│         return event

  13  ~\AppData\Roaming\pypoetry\venv\lib\site-packages\cleo\events\event_dispatcher.py:89 in _do_dispatch
        87│                 break
        88│
     →  89│             listener(event, event_name, self)
        90│
        91│     def _sort_listeners(self, event_name: str) -> None:

  12  ~\AppData\Roaming\pypoetry\venv\lib\site-packages\poetry\console\application.py:322 in configure_installer_for_event
       320│             return
       321│
     → 322│         cls.configure_installer_for_command(command, event.io)
       323│
       324│     @staticmethod

  11  ~\AppData\Roaming\pypoetry\venv\lib\site-packages\poetry\console\application.py:329 in configure_installer_for_command
       327│ 
       328│         poetry = command.poetry
     → 329│         installer = Installer(
       330│             io,
       331│             command.env,

  10  ~\AppData\Roaming\pypoetry\venv\lib\site-packages\poetry\installation\installer.py:78 in __init__
        76│         self._installer = self._get_installer()
        77│         if installed is None:
     →  78│             installed = self._get_installed()
        79│
        80│         self._installed_repository = installed

   9  ~\AppData\Roaming\pypoetry\venv\lib\site-packages\poetry\installation\installer.py:569 in _get_installed
       567│ 
       568│     def _get_installed(self) -> InstalledRepository:
     → 569│         return InstalledRepository.load(self._env)
       570│

   8  ~\AppData\Roaming\pypoetry\venv\lib\site-packages\poetry\repositories\installed_repository.py:291 in load
       289│                     continue
       290│
     → 291│                 package = cls.create_package_from_distribution(distribution, env)
       292│
       293│                 if with_dependencies:

   7  ~\AppData\Roaming\pypoetry\venv\lib\site-packages\poetry\repositories\installed_repository.py:141 in create_package_from_distribution
       139│                                 source_url,
       140│                                 source_reference,
     → 141│                             ) = cls.get_package_vcs_properties_from_path(src)
       142│                             break
       143│

   6  ~\AppData\Roaming\pypoetry\venv\lib\site-packages\poetry\repositories\installed_repository.py:89 in get_package_vcs_properties_from_path
        87│         from poetry.vcs.git import Git
        88│
     →  89│         info = Git.info(repo=src)
        90│         return "git", info.origin, info.revision
        91│

   5  ~\AppData\Roaming\pypoetry\venv\lib\site-packages\poetry\vcs\git\backend.py:174 in info
       172│     @classmethod
       173│     def info(cls, repo: Repo | Path | str) -> GitRepoLocalInfo:
     → 174│         return GitRepoLocalInfo(repo=repo)
       175│
       176│     @staticmethod

   4  <string>:3 in __init__
         1│

   3  ~\AppData\Roaming\pypoetry\venv\lib\site-packages\poetry\vcs\git\backend.py:146 in __post_init__
       144│         repo = Git.as_repo(repo=repo) if not isinstance(repo, Repo) else repo
       145│         self.origin = Git.get_remote_url(repo=repo, remote="origin")
     → 146│         self.revision = Git.get_revision(repo=repo)
       147│
       148│

   2  ~\AppData\Roaming\pypoetry\venv\lib\site-packages\poetry\vcs\git\backend.py:170 in get_revision
       168│     def get_revision(repo: Repo) -> str:
       169│         with repo:
     → 170│             return repo.head().decode("utf-8")
       171│
       172│     @classmethod

   1  ~\AppData\Roaming\pypoetry\venv\lib\site-packages\dulwich\repo.py:628 in head
        626│     def head(self) -> bytes:
        627│         """Return the SHA1 pointed at by HEAD."""
     →  628│         return self.refs[b"HEAD"]
        629│
        630│     def _get_object(self, sha, cls):

  KeyError

  b'HEAD'

  at ~\AppData\Roaming\pypoetry\venv\lib\site-packages\dulwich\refs.py:322 in __getitem__
       318│         This method follows all symbolic references.
       319│         """
       320│         _, sha = self.follow(name)
       321│         if sha is None:
    →  322│             raise KeyError(name)
       323│         return sha
       324│
       325│     def set_if_equals(
       326│         self,

```

**Comment by dimbleby** [comment]
indeed looks similar to #6873: this code is trying to read the installed packages in the environment and going wrong.

If you can make any progress understanding what it is about the relevant git checkout that dulwich doesn't like, that would be super.

**Comment by dimbleby** [comment]
alternatively if you can figure out how you got to whatever that state is and share a repro, that too would be helpful.

**Comment by betterthanever2** [comment]
A few more pieces of information:
1. When I open project settings in PyCharm, it doesn't show any packages as it should, instead I see "nothing to show"
2. Reading the stacktrace, I see there are 2 packages involved - `cleo` and `dulwich`. I installed both explicitly on the fresh test project, and I can see that versions used by poetry are different. Specifically,
3. `dulwich` is `0.20.50` at `\AppData\Local\pypoetry\venv\Lib\site-packages\`, and `0.21.2` when installed directly;
4. `cleo` is `1.0.0a5` vs. `2.0.1` respectively.
5. When I downgraded `cleo` to the version used by poetry, I can see there is a slight difference in occupied disk space btw the 2 instances. Can this mean something?
![image](https://user-images.githubusercontent.com/68774738/219607283-c4dfa003-94ce-4a0c-9e2c-486585904ade.png)

**Comment by dimbleby** [comment]
The stack tells you where the source code is, you can add print statements to answer such questions definitively.

I would start by investigating the differences between the virtual environments where this does and doesn't work.  There must surely be a git repository in the broken one that is somehow unhappy: I would be trying to find out what is interesting about the state of that repository.

**Comment by betterthanever2** [comment]
I found and resolved the issue. 
It was caused by folder `src` on the top level of the virtual env folder. The content of the folder is:
```
src
  transformers
    .git
       info
         exclude
       HEAD
       description
       config
```
Will provide the actual contents upon request.
What's more interesting, though, is where did it come from. I have the answer to that, as well. It was generated by attempting to install `huggingface.Transformers` package with this line:
```
pip install git+https://github.com/huggingface/transformers
```
That is, I tried to adapt this command to the pyproject.toml syntax, but I probably won't be able to tell you how exactly.

I did this _before_ I discovered it's on PyPI, and only because this was how it was described in [this article](https://huggingface.co/blog/fine-tune-whisper). 

Simply removing the folder resolves the problem.

**Comment by wolph** [comment]
I believe this issue should be reopened. While removing the directory in `src` resolves the issue, the issue shouldn't be there to begin with, or, at the very least, have a useful error.

Having every command only return `b'HEAD'` and nothing else is extremely useless.

**Comment by ljodal** [comment]
I'm seeing the same issue as well. Pydantic seems to get itself in this situation if it fails to add a git dependency, ie. if I mistype the repo URL. Removing the `src` directory does indeed fix it, but a better error message would help a lot here

**Comment by roysagi** [comment]
I am facing this issue as well, I've removed the `src` folder as suggested and re-ran `poetry install`.
The command ran successfully but it now returned to outputting `HEAD` - so not a real solution here

**Comment by trim21** [comment]
This problem still exists in poetry 1.5.1

**Comment by oluckyman** [comment]
same here, after trying to install `git+https://github.com/huggingface/transformers`

<img width="203" alt="image" src="https://github.com/python-poetry/poetry/assets/642673/3d5ac020-8676-441d-9a3e-50e427b84516">

**Comment by ilyagr** [comment]
I believe I ran into this when I head

```toml
ansitoimg = "git+https://github.com/ilyagr/ansitoimg.git#title"
```

in my poetry.toml, and changing it to the correct

```toml
ansitoimg = {git = "https://github.com/ilyagr/ansitoimg.git", rev = "title"}
```

fixed it. I'm not 100% sure it wasn't something else that I did that fixed it, but perhaps someone will check.

**Comment by trim21** [comment]
> I believe I ran into this when I head
> 
> ```toml
> ansitoimg = "git+https://github.com/ilyagr/ansitoimg.git#title"
> ```
> 
> in my poetry.toml, and changing it to the correct
> 
> ```toml
> ansitoimg = {git = "https://github.com/ilyagr/ansitoimg.git", rev = "title"}
> ```
> 
> fixed it. I'm not 100% sure it wasn't something else that I did that fixed it, but perhaps someone will check.

I using a config similar to `ansitoimg = {git = "...", rev = "..."}` and still encounter this problem.

**Comment by ilyagr** [comment]
Oh well. :(

**Comment by MrGreenTea** [comment]
I've had this happen to me multiple times and colleagues of mine as well. I can't provide a reproduction sadly as we've only had it happen with private git repos.

But I believe that it only happens when the initial clone is either interrupted or fails (I've both had it happen when pressing `CTRL+C` when it resolved dependencies as well as when I had network issues and `git` failed with a warning about possible man-in-the-middle). In those cases the directory inside `(poetry env info -p)/src/` is a broken git repository and then `poetry` fails until I remove the directory from `<env>/src`.

I'll look into finding some way to reproduce this for you.

**Comment by MrGreenTea** [comment]
I've also included an archive of how the `glom` folder inside the `<virtual-env>/src` folder looks. It just contains a `.git` folder and nothing else. I've not noticed anything weird about it other than it being empty.

[glom-git.tar.gz](https://github.com/python-poetry/poetry/files/12661996/glom-git.tar.gz)

**Comment by HMaker** [comment]
@MrGreenTea I managed to reproduce it another way, see https://github.com/python-poetry/poetry/issues/8384#issuecomment-1760614506

**Comment by bonlime** [comment]
I have encountered the same issue and uninstalling `transformers` library helped to solve it. 
This seems to be the root cause: https://github.com/python-poetry/poetry/issues/6077#issuecomment-1517813403

**Comment by ashishnitinpatil** [comment]
https://github.com/python-poetry/poetry/issues/6873
In case it helps, just removing the virtual env & then doing `poetry install` again may resolve this if it's a local issue.

**Comment by Ghostkeeper** [comment]
I encountered this as well and have steps that I can reproduce, but other people can't because it involves pulling a repository that is unreachable to most.

In my pyproject.toml I have the following lines:
```
[tool.poetry.dependencies]
shared-spot = { git = "git@gitlab.com:KNMI/mwi/snip/md/shared-spot.git", branch = "SNIP-783-design" }
```

However currently Gitlab is having some server issues and as a result, `poetry update` gives the following error:
```
Updating dependencies
Resolving dependencies... (19.0s)

git@gitlab.com: Permission denied (publickey).
```

However it did create the following directory in my `venv/src` directory: [shared-spot.zip](https://github.com/python-poetry/poetry/files/13207268/shared-spot.zip). Rest assured that this doesn't contain any confidential data. But I didn't edit it, it's just a partially-initialised Git repository.

While that directory is in `venv/src`, calling `poetry update` again gives the output:
```
b'HEAD'
```

**Comment by kornpow** [comment]
I did this to solve this issue:
```
 rm -r ~/.cache/pypoetry/virtualenvs/my-package-BRKj7VlA-py3.11/
deactivate
poetry shell
poetry install
 ```

**Comment by sebastian-weisshaar** [comment]
> [#6873 (comment)](https://github.com/python-poetry/poetry/issues/6873#issuecomment-1574193370) In case it helps, just removing the virtual env & then doing `poetry install` again may resolve this if it's a local issue.

Worked for me
