### ISSUE TITLE
export requirements.txt file without downloading packages

### ISSUE THREAD

**Issue by padrepitufo** [python-poetry/poetry#7524]
- [x ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x ] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request
when working with google cloud functions I have to provide a `requirements.txt` file.  While I develop locally I use poetry for my virtual environment and would like to use the same `pyproject.toml` to export a requirements.txt file in my GitHub action so that it can create this artifact.  I can do this currently via :

```
poetry export --without-hashes --without dev --format=requirements.txt > requirements.txt
```

 The only issue is that it uses more GitHub action minutes than I'd like because it always downloads all the dependencies (which I don't use) before generating the file.

**Comment by dimbleby** [comment]
No, it doesn't.  You've misunderstood something.

**Comment by radoering** [comment]
Dependencies are downloaded for locking. You probably forgot to commit your lockfile, so poetry has to lock first before exporting.

**Comment by Secrus** [comment]
Closing, as the issue at hand was explained. Feel free to open new issue if you encounter any other problems
