### ISSUE TITLE
poetry-lock pre-commit hook does not only check but also updates poetry.lock

### ISSUE THREAD

**Issue by yrro** [python-poetry/poetry#7532]
- **Poetry version**: 1.3.2
- **Python version**: 3.11.1
- **OS version and name**: Fedora 37
- **pyproject.toml**: N/A

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
I've added the `poetry-lock` pre-commit hook to my project and was surprised by the behaviour of dependencies being updated when the pre-commit hook run.

I expected the hook to only concern itself with whether I'd forgotten to update `poetry.lock` after editing `pyproject.toml`, not with additionally updating dependencies.

I worked around this by configuring the pre-commit hook as follows:

```
- repo: https://github.com/python-poetry/poetry
  rev: 1.3.2
  hooks:
  - id: poetry-lock
    args:
    - --no-update
```

I think this should be the default behaviour.

For context, there is already a request in #3248 about switching `poetry lock` to behave as if `--no-update` is passed by default.

**Comment by dimbleby** [comment]
`poetry lock --no-update` _also_ doesn't only check, sounds like you are looking for `poetry lock --check`

which would make this a duplicate of #6450

**Comment by yrro** [comment]
Agree, thanks :)
