### ISSUE TITLE
[MacOS] Need to reinstall poetry every time python updates

### ISSUE THREAD

**Issue by pkulev** [python-poetry/poetry#7535]
- **Poetry version**: 1.3.2, installed with `curl -sSL https://install.python-poetry.org | python3.10 -`
- **Python version**: 3.10.10, installed with brew (python@3.10)
- **OS version and name**: MacOS Ventura 13.2
- **pyproject.toml**: any

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

```
➜  ~ which poetry
/Users/most/Library/Python/3.10/bin/poetry
➜  ~ which python3.10
/opt/homebrew/bin/python3.10
➜  ~ ls -al `which python3.10`
lrwxr-xr-x  1 most  admin  46 Feb 20 12:15 /opt/homebrew/bin/python3.10 -> ../Cellar/python@3.10/3.10.10_1/bin/python3.10
➜  ~ head `which poetry`
#!/bin/sh
'''exec' "/Users/most/Library/Application Support/pypoetry/venv/bin/python" "$0" "$@"
' '''
```

After any python@3.10 minor update I get the same issue:
```
➜  ~ poetry
dyld[64792]: Library not loaded: /opt/homebrew/Cellar/python@3.10/3.10.10/Frameworks/Python.framework/Versions/3.10/Python
  Referenced from: <15CD67DE-FC5D-3D45-8B25-D3AEAE046ED5> /Users/most/Library/Application Support/pypoetry/venv/bin/python
  Reason: tried: '/opt/homebrew/Cellar/python@3.10/3.10.10/Frameworks/Python.framework/Versions/3.10/Python' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/python@3.10/3.10.10/Frameworks/Python.framework/Versions/3.10/Python' (no such file), '/opt/homebrew/Cellar/python@3.10/3.10.10/Frameworks/Python.framework/Versions/3.10/Python' (no such file), '/Library/Frameworks/Python.framework/Versions/3.10/Python' (no such file), '/System/Library/Frameworks/Python.framework/Versions/3.10/Python' (no such file, not in dyld cache)
[1]    64792 abort      poetry
```

And I need to reinstall it with:
```
➜  ~ curl -sSL https://install.python-poetry.org | python3.10 - --uninstall
Removing Poetry (1.3.2)
➜  ~ curl -sSL https://install.python-poetry.org | python3.10 -
```

Is there a way to avoid this? I'm wondering what I did wrong.

**Comment by dimbleby** [comment]
duplicate https://github.com/python-poetry/install.python-poetry.org/issues/71
