### ISSUE TITLE
Install all dependencies by default (if no extra is specified)

### ISSUE THREAD

**Issue by sergargar** [python-poetry/poetry#7536]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request

Is there any way to install all dependencies if no extra is specified?, i.e., `pip install .` = `pip install '.[all]'`

**Comment by finswimmer** [comment]
No, there is no way to do this, because this would be a surprise for the users.

However, there is a `--all-extras` flag for `poetry install` (https://python-poetry.org/docs/cli/#options-2). Use this one to install all extras of your project.

fin swimmer
