### ISSUE TITLE
usage on readthedocs.org

### ISSUE THREAD

**Issue by cjw296** [python-poetry/poetry#754]
- [X] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

How can I have readthedocs.org build a project that I'm developing using poetry?
Hopefully this is just a documentation issue...

**Comment by jacebrowning** [comment]
@cjw296 Did you run into a specific error when building your site?

My `mkdocs` site built fine without telling readthedocs.org anything about poetry: https://datafiles.readthedocs.io

**Comment by cjw296** [comment]
How did you install your package? Doesn’t rtd only support pip (and maybe conda if you’re very lucky?)

**Comment by jacebrowning** [comment]
The only setting I changed from the defaults was to select the framework for my docs:

![](https://zappy.zapier.com/79784D90-B23A-4DD4-ACEA-855B99964D78.png)

I don't think RTD needs the rest of your dependencies.

**Comment by cjw296** [comment]
I use Sphinx, and to build correctly, the package needs to be installed.

**Comment by cjw296** [comment]
RTD issue here: https://github.com/rtfd/readthedocs.org/issues/4912
May well be fixed by https://github.com/pypa/pip/issues/6106.

**Comment by GPMueller** [comment]
Aside from documentation I don't belive this is an issue of `poetry`, but of readthedocs.
Installing it there should not be a problem, but I was not successful running `poetry` there, because of missing system packages.

However, documentation on how to use RTD would be great! 👍

**Comment by ahal** [comment]
Not a super elegant solution, but you can use a `requirements.txt` to manually point to the packages you want `autodoc` to find. E.g add the following file to your repo root:

requirements.readthedocs.txt

    src/my_package
    src/my_other_package

Then enable `requirements.readthedocs.txt` in the readthedocs admin panel. That's enough to allow autodoc to find the package. You may need to add some dependencies there too.

**Comment by Trim21** [comment]
Is there any way to install dev-dependencies by `pip install .`  instead of put sphinx in extra requirements?

```yaml
version: 2

# Optionally set the version of Python and requirements required to build your docs
python:
  version: 3.6
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
```

**Comment by cjw296** [comment]
I suspect this requires the "editable install support as an extension to PEP 517" mentioned in https://github.com/pypa/pip/issues/6314#issuecomment-470041521.

**Comment by cjw296** [comment]
@finswimmer - can you explain why you've closed this?

**Comment by finswimmer** [comment]
Hello @cjw296,

sorry I could have written some words about it. I've closed this because there were nor more comments for more than a year. Furthermore it doesn't look like a poetry problem. If you disagree please explain it a bit more, why you think that is something poetry should solve. We can discuss about it of course.

fin swimmer

**Comment by cjw296** [comment]
Poetry's direction and approach seems pretty hostile to my use cases nowadays, and closing issues just because no-one's had time to bottom them out seems counterproductive. This isn't the first time I've disagreed with your approach, and I'm sorry to see @sdispater cede so much direction and control of this project to you; Poetry had plenty of potential, but the direction you're driving it doesn't work for me.

**Comment by sdispater** [comment]
@cjw296 

> Poetry's direction and approach seems pretty hostile to my use cases nowadays

Are you saying that we should accept and abide by your use cases, no questions asked?

The thing is that I agree with @finswimmer here: this is not an issue with Poetry but with RTD and you already pointed to an issue on the RTD repository where the discussion is more suited (https://github.com/readthedocs/readthedocs.org/issues/4912).

That being said, if you feel that Poetry could do something here and you are willing to implement it, I'd happily review a PR but for now I really think this is out of our hands.

**Comment by AKuederle** [comment]
RTD does seem to allow custom shell commands with the most recent update: https://docs.readthedocs.io/en/latest/build-customization.html

I havn't tested it yet, but I assume this should allow to install dev dependencies (or in Poetry 1.2 and higher the respective dependency groups for docs)

**Comment by rlaphoenix** [comment]
> Is there any way to install dev-dependencies by `pip install .` instead of put sphinx in extra requirements?
> 
> ```yaml
> version: 2
> 
> python:
>   version: 3.6
>   install:
>     - method: pip
>       path: .
>       extra_requirements:
>         - docs
> ```

Do note that this will install all optional dependencies, which is really not ideal.
