### ISSUE TITLE
Cross-Platform Dependency Resolution

### ISSUE THREAD

**Issue by SinOverCos** [python-poetry/poetry#7541]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request

Poetry is able to [show](https://python-poetry.org/docs/cli/#show) the dependency tree of a package. It also supports conditional installs through [environment markers](https://python-poetry.org/docs/dependency-specification/#using-environment-markers). I'm wondering if it's possible to join these two features together to make poetry a cross-platform dependency resolver?

I am looking for something like pip's [installation report](https://pip.pypa.io/en/stable/reference/installation-report/), where pip can do a dry run of an installation and outputs the list of dependencies and transitive dependencies that would be installed for a given package. pip also supports passing in values for python version, abi version, platform, and implementation values so that the installation report represents what would've been installed for a target platform, instead of the current running python interpreter version and the host machine platform/os.

**Comment by dimbleby** [comment]
poetry already performs cross-platform dependency resolution

if pip already does whatever it is you want - use pip for that!

**Comment by SinOverCos** [comment]
@dimbleby unfortunately pip isn’t able to override environment markers for conditional installs — https://github.com/pypa/pip/issues/11664

Can you share a link for the poetry cross platform dependency resolution?

**Comment by dimbleby** [comment]
I don't understand what you're asking for.

> Can you share a link for the poetry cross platform dependency resolution?

What do you mean?

When poetry performs dependency resolution, it finds a cross-platform solution.  The same poetry lockfile can be taken to any platform and used to install.

perhaps `poetry export` is something like what you want??  But I really can't tell.

**Comment by neersighted** [comment]
The issue as written is already implemented by Poetry; Poetry was the first tool to do cross-platform dependency resolution and it's still at the core of Poetry. I'm going to close this as it's not actionable, but feel free to continue to discuss here, or convert this issue to a discussion, or join us on Discord.

Please try to clarify what it is you are trying to do @SinOverCos; currently it does not make sense, and the linked pip issue doesn't make sense in terms of Poetry. Poetry is not pip, there are often no 1:1 analogies between the projects.

**Comment by SinOverCos** [comment]
My high-level goal is to answer this question:

If I wanted to install package foo on a target system that e.g.
* runs $os operator system
* with $ver version of python
* with the $impl implementation of the interpreter (e.g. cpython, jython, etc)
* with $abi ABIs accessible (e.g. cp37m, abi3)

then what are the specific packages, dependencies, and transitive dependencies that will get installed? The answer to this query varies because some dependencies might only get installed for certain versions of python (e.g. backports), or for certain OSs (e.g. graphics libraries), etc.

I want to be able to answer this query for any values of $os, $ver, $impl, and $abi on my local machine, without having to actually e.g. build an image with those parameters and then running installation on that image to find out.

**Comment by dimbleby** [comment]
Not directly

`poetry export` and then parse the markers yourself is the nearest thing that comes to mind
