### ISSUE TITLE
Where is the documentation for poetry 1.1.15 ?

### ISSUE THREAD

**Issue by dschiller** [python-poetry/poetry#7542]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

I am looking for the documentation for poetry 1.1.15. I need to read about repositories and how to add sources. In latest poetry there is a command `source` which seems not to exist in poetry 1.1.15.
eg. `poetry source add mysource https://artifactory.any.team/artifactory/api/pypi/python/simple`
It fails with:
```shell
The command "source" is not defined.
```

I would consider reading the 1.1.15 documentaiton and find out there is no `source` command but a simmilar one or doing it manually. I also would like to see in the 1.3.2 documentation when `source` was introduced.

**Comment by dimbleby** [comment]
https://github.com/python-poetry/poetry/tree/1.1.15/docs

**Comment by neersighted** [comment]
Poetry 1.1.15 is old enough that we are no longer building the docs as part of the website; the raw markdown files are still available, but are just not compatible with subsequent changes to the website code.
