### ISSUE TITLE
add -e/--executable to poetry env info to get the python executable path

### ISSUE THREAD

**Issue by sanzoghenzo** [python-poetry/poetry#7546]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request

in addition to the already present `-p/--path` option, add a `-e/--execuatble` option to return the python executable path.

My use case: I'm starting to use Taskfile and poetry on some projects; these project are developed on both linux and windows;

I would like to avoid having to install tools such as mypy in the virtual environment, since they can be run from the outside (this also allows me to have faster CI, I have set up a custom docker image with all the tools needed).

mypy in particular wants to know the exact path of the python executable to work (passed as `--python-executable` option), so having a new `poetry env info --executable` option that outputs the python path  would solve my issue in a cross-platform fashion.

**Comment by dimbleby** [comment]
If this feature is important to you, then submitting a merge request with the change you want to see is by far the most likely way to make it happen.
