### ISSUE TITLE
Poetry 1.3.1 and up (including 1.4.0) seems to strip quotes from run command

### ISSUE THREAD

**Issue by nagulv** [python-poetry/poetry#7548]
- **Poetry version**: Poetry (version 1.3.2)
- **Python version**: 3.8.8
- **OS version and name**: Windows 11

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

Running black with the --exclude ".*_pb2.py|.local_env" option works on poetry 1.1.13. It fails on upgrading to poetry 1.3.2. The command seems to behave like the double-quotes are missing (i.e. I can reproduce the same error message on 1.1.13 by running the command without the double quotes.

```
C:\dev\proj_py> poetry.exe -vvv run black --check --exclude ".*_pb2.py|.local_env" . --verbose
Loading configuration file C:\Users\Nagul\AppData\Roaming\pypoetry\config.toml
Loading configuration file C:\dev\proj_py\poetry.toml
Using virtualenv: .local_env\proj-py-hxOVy_5E-py3.8
'.local_env' is not recognized as an internal or external command,
operable program or batch file.

```

```
C:\dev\proj_py> cat poetry.toml
[virtualenvs]
path = ".local_env"

```

**Comment by finswimmer** [comment]
Hello @nagulv,

you haven't come back to this issue for a long while. So I assume this is solved in the meantime and I can close this ticket.

Feel free to leave a comment if you disagree.

fin swimmer
