### ISSUE TITLE
Dependency rooted in a subfolder of a GIT repository

### ISSUE THREAD

**Issue by sandrinr** [python-poetry/poetry#755]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.

## Feature request

Currently, as far as I can figure, it is impossible to use a GIT repository as a dependency source where the `setup.py` or `pyproject.toml` file is not in the root directory but in some sub-folder of the repository.

E.g. GIT repo structure:
* GIT root
  * pythonmodule
    * setup.py / pyproject.toml
    * module1.py
    * module2.py
  * javamodule
    * pom.xml
  * cmodule
    * Makefile

In this example I would like to be able to point poetry to the `pythonmodule` directory inside this repo, for example using `poetry add mydep --git https://github.com/foo/bar.git --path path/to/mydep`. I don't think this can be accomplished via a separate repository definition, however, the documentation is a bit scarce on that topic.

**Comment by bwdeng** [comment]
Same here, i'm able to install a git dependency using pip with its [VCS support](https://pip.readthedocs.io/en/stable/reference/pip_install/#vcs-support)

```
pip install "git+https://github.com/nmslib/hnswlib.git@bb2a1d1#egg=hnswlib&subdirectory=python_bindings"
```

It would be nice if we can do it using `poetry add`.

**Comment by zbarnett** [comment]
I would love to switch to Poetry and it looks like this is the only thing preventing me. Very excited to see this feature is in progress!

**Comment by finswimmer** [comment]
Ready for testing :)

**Comment by velovix** [comment]
@finswimmer Thank you for your work on this! Is there any way I can help with getting your PRs ready for review?

**Comment by TheButlah** [comment]
Was this functionality implemented? My team relies on poetry and we just started breaking some of our code up into a separate git repo - we would need this to continue to use poetry

**Comment by sinoroc** [comment]
> Was this functionality implemented? My team relies on poetry and we just started breaking some of our code up into a separate git repo - we would need this to continue to use poetry

As far as I can tell, it has been implemented, but not merged nor released. This still-in-progress implementation is here: https://github.com/python-poetry/poetry/pull/1822.

**Comment by finswimmer** [comment]
It isn't fully implemented until now. A lot has changed since I wrote #1822. This PR is now splitted in https://github.com/python-poetry/poetry-core/pull/9 and https://github.com/python-poetry/poetry/pull/2242 But there is still a lot to do. I cannot tell when this will be ready.

**Comment by Tinche** [comment]
We are also looking into breaking out shared modules into a separate repo, and it would be awesome to be able to keep them all in one repository and reference them by sub-directories.

**Comment by dvarrazzo** [comment]
Do I understand correctly that it is not currently possible to install psycopg3 using poetry, owing to the lack of subdirectory support?

with pip or requirement it is possible to use:

```
pip install -e "git+https://github.com/psycopg/psycopg3.git@9688cd2#egg=psycopg3&subdirectory=psycopg3"
pip install -e "git+https://github.com/psycopg/psycopg3.git@9688cd2#egg=psycopg3-c&subdirectory=psycopg3_c"
```

Is there similar support for poetry?

**Comment by golyalpha** [comment]
Right now working around this via filesystem dependencies, so, clone repo first to a known location, (preferably `../`), and define the dependency as `lib_name = {path = '../lib-name/python-module'}`

It does mean that I have to manually pull in every single repository that has the python module in a subdir, which is not ideal.

**Comment by rap1ide** [comment]
Anyone implementing this right now, would be super helpful!

**Comment by miohtama** [comment]
You can also workaround the lack of git URL subdirectory support with Git submodules.

First include the Python package you want to have as a git submodule of your application:

```shell
git submodule add https://github.com/kroitor/ccxt.pro ccxt-pro
```

Then add this as a dependency in `pyproject.toml`:

```toml
[tool.poetry.dependencies]
python = "^3.8"
ccxt = "^1.57.95"
ccxtpro = {path = "./ccxt-pro/python", develop = true}
```

**Comment by phillipuniverse** [comment]
Looks like this functionality will be available in 1.2 via #192.

**Comment by dmartin-isp** [comment]
> Looks like this functionality will be available in 1.2 via #192.

This comment makes no sense.  The link provided has nothing to do with functionality discussed in this issue and is from 2018.

**Comment by remram44** [comment]
They meant https://github.com/python-poetry/poetry-core/pull/192 (the other repository)

**Comment by mccolljr** [comment]
I've been looking around in this thread and the related threads, and I'm a bit lost:

I see that https://github.com/python-poetry/poetry-core/pull/192 has been merged into poetry-core

Is this available in any pre-release versions yet? I'm working on a project right now that needs to take advantage of this and it seems like `1.2.0a2` isn't supporting the syntax yet. I thought maybe I needed to specify a sufficient version of poetry-core, but I couldn't figure out which release contains https://github.com/python-poetry/poetry-core/pull/192 has been merged into poetry-core

**Comment by phillipuniverse** [comment]
@mccolljr doesn’t look like it’s in any pre-release versions yet. The last poetry-core alpha (1.1.0a6) was released [May 2021](https://github.com/python-poetry/poetry-core/releases/tag/1.1.0a6) and https://github.com/python-poetry/poetry-core/pull/192 wasn’t merged until September 2021.

**Comment by mccolljr** [comment]
Not sure who the correct maintainers to tag are, but:

Would you be open to cutting new pre-release versions of poetry-core and poetry with what currently exists of this feature? I would really benefit from this, and I'm willing to accept any potential instability of using ithe bleeding edge to get it.

**Comment by ashnair1** [comment]
You could use the latest version of `poetry-core` by specifying the following in your `pyproject.toml`
```toml
[build-system]
requires = ["poetry-core @ git+https://github.com/python-poetry/poetry-core.git"]
build-backend = "poetry.core.masonry.api"
```

**Comment by mccolljr** [comment]
> You could use the latest version of `poetry-core` by specifying the following in your `pyproject.toml`
> 
> ```toml
> [build-system]
> requires = ["poetry-core @ git+https://github.com/python-poetry/poetry-core.git"]
> build-backend = "poetry.core.masonry.api"
> ```

Brilliant, thanks - this is exactly what I needed

**Comment by falonso-alo** [comment]
> You can use the latest version of `poetry-core` by specifying the following in your `pyproject.toml`
> 
> ```toml
> [build-system]
> requires = ["poetry-core @ git+https://github.com/python-poetry/poetry-core.git"]
> build-backend = "poetry.core.masonry.api"
> ```

@ashnair1, 

So would this allow me to use a dependency in subfolder? If so, do you happen to know what the synatx looks like? Something like this perhaps?

```toml
[tool.poetry.dependencies]
my_module = { git = "https://github.com/my_org/my_repo.git", directory = "src/my_module_folder" }
```

**Comment by remram44** [comment]
@falonso-alo: it's `subdirectory=`

**Comment by ashnair1** [comment]
@falonso-alo 

Think it would be something like this
```toml
[tool.poetry.dependencies]
my_module = { git = "https://github.com/my_org/my_repo.git#egg=my_module_folder&subdirectory=src" }
```
which translates to install `my_module_folder` in the subdirectory `src` of `my_repo.git`

**Comment by falonso-alo** [comment]
Thank you @ashnair1 and @remram44! It does seem like this is a bit difficult right now. It may be too much of a curve ball for my team so I will probably have to wait for better support for subdirectories. 

Thanks again!

**Comment by Felix-neko** [comment]
> ```toml
> my_module = { git = "https://github.com/my_org/my_repo.git", subdirectory = "src/my_module_folder" }
> ```

Hi folks! Have anybody already tested it? It should be extremely useful, but it looks i've installed this fork in wrong way and it doesn't work correctly on my machine = (

**Comment by rickmark** [comment]
Suggest edit of title to use `subdirectory` which is the term used in PIP to help it be found by search.

**Comment by rickmark** [comment]
> ```toml
> ```toml
> my_module = { git = "https://github.com/my_org/my_repo.git", subdirectory = "src/my_module_folder" }
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> 
> Hi folks! Have anybody already tested it? It should be extremely useful, but it looks i've installed this fork in wrong way and it doesn't work correctly on my machine = (
> ```

This doesn't seem to work even with `poetry` and `poetry-core` pre (as of today).

Our "problem dependency" is this:

```
unicoirn = { git = "https://github.com/unicorn-engine/unicorn.git", branch = "dev", subdirectory="bindings/python"}
```

**Comment by StuartBertram** [comment]
I've tried this but can't even get the `subdirectory` parameter to work.

I've got:
```
[build-system]
requires = ["poetry-core @ git+https://github.com/python-poetry/poetry-core.git"]
build-backend = "poetry.core.masonry.api"
```
in my pyproject.toml. I'm using a ssh URL for a private GitHub repo. But I get "[repo definition] is not valid under any of the given schemas".

Does this need the pre-release Poetry as well as the poetry-core settings?

**Comment by b1r3k** [comment]
> seems to be working for me rocket

I think something is missing here since it does not work for me. Here is my environment:
```
$ pip freeze

poetry @ git+https://github.com/python-poetry/poetry.git@ccbeffc1f1a5809e999cc18c584ed2cee2a8f580
poetry-core==1.1.0b2

$ cat pyproject.toml

...
[tool.poetry.dependencies]
openapi-client = { git = "https://github.com/deribit/deribit-api-clients.git", subdirectory = "python" }

[build-system]
requires = ["poetry-core @ git+https://github.com/python-poetry/poetry-core.git"]
build-backend = "poetry.core.masonry.api"
```

Trying to install project with: `poetry install` ends up with:

```
  • Installing openapi-client (1.0.0 7ae49f6): Failed

  CalledProcessError

  Command '['ROOT/machine/.venv/bin/python', '/home/lukasz/.pyenv/versions/3.10.2/lib/python3.10/site-packages/virtualenv/seed/wheels/embed/pip-22.0.4-py3-none-any.whl/pip', 'install', '--use-pep517', '--disable-pip-version-check', '--prefix', 'ROOT/machine/.venv', '--upgrade', '--no-deps', 'ROOT/machine/.venv/src/deribit-api-clients']' returned non-zero exit status 1.

  at ~/.pyenv/versions/3.10.2/lib/python3.10/subprocess.py:524 in run
       520│             # We don't call process.wait() as .__exit__ does that for us.
       521│             raise
       522│         retcode = process.poll()
       523│         if check and retcode:
    →  524│             raise CalledProcessError(retcode, process.args,
       525│                                      output=stdout, stderr=stderr)
       526│     return CompletedProcess(process.args, retcode, stdout, stderr)
       527│ 
       528│ 

The following error occurred when trying to handle this error:


  EnvCommandError

  Command ['ROOT/machine/.venv/bin/python', '/home/lukasz/.pyenv/versions/3.10.2/lib/python3.10/site-packages/virtualenv/seed/wheels/embed/pip-22.0.4-py3-none-any.whl/pip', 'install', '--use-pep517', '--disable-pip-version-check', '--prefix', 'ROOT/machine/.venv', '--upgrade', '--no-deps', 'ROOT/machine/.venv/src/deribit-api-clients'] errored with the following return code 1, and output: 
  ERROR: Directory 'ROOT/machine/.venv/src/deribit-api-clients' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.
```

**Comment by andersk** [comment]
>     poetry @ git+https://github.com/python-poetry/poetry.git@ccbeffc1f1a5809e999cc18c584ed2cee2a8f580

@b1r3k ccbeffc1f1a5809e999cc18c584ed2cee2a8f580 is the 1.2.0b2 tag. You don’t have #5172, which has not yet been merged. You need to do:

```shell
pip install git+https://github.com/ashnair1/poetry.git@subdir-fix
```
