### ISSUE TITLE
poetry can't be used without internet access, because it runs pip with --isolated

### ISSUE THREAD

**Issue by smoofra** [python-poetry/poetry#7551]
- **Poetry version**:  1.3.2
- **Python version**: 3.10.8
- **OS version and name**:  Mac OS 13.0
- **pyproject.toml**: [pyproject.toml.txt](https://github.com/python-poetry/poetry/files/10818346/pyproject.toml.txt)

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

When poetry calls out to pip, it passes `--isolated`, which causes pip to ignore `$PIP_INDEX_URL` and `pip.conf`.   This makes it impossible to use poetry without access to the internet, because pip cannot be redirected to an index on the local network.   

This issue only occurs when depending on certain projects such as `pluginbase` or `patch-ng`, because pip tries to install setuptools in order to build them, even when called with `--no-deps`

This issue was casued by https://github.com/python-poetry/poetry/pull/6531/files

[log.txt](https://github.com/python-poetry/poetry/files/10818329/log.txt)

**Comment by dimbleby** [comment]
#3249, again
