### ISSUE TITLE
build function is ignored

### ISSUE THREAD

**Issue by ngoettin** [python-poetry/poetry#7553]
- **Poetry version**: 1.3.2
- **Python version**: 3.10.6
- **OS version and name**: Arch Linux (24.02.2023)
- **pyproject.toml**: 
```
[tool.poetry]
name = "test"
authors = ["me"]
version = "0.1.0"
description = "test"

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.build]
script = "build.py"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
I tried to use Cython with poetry and failed, because the `build`-function did not seem to be executed. To test this, I created a new package with the following structure:
```
.
├── build.py
├── pyproject.toml
└── test
    └── __init__.py
```
where the `pyproject.toml` is shown above and the `build.py` contains only the following:
```
print("Hi! (1)")

def build(setup_kwargs):
    print("Hi! (2)")
```
Upon building the project, however, the only output I get is
```
~/Documents/test ❯ poetry build
Preparing build environment with build-system requirements poetry-core
Building test (0.1.0)
Hi! (1)
```
but I expected to also see `Hi! (2)` in the output.

What am I doing wrong? I've looked e.g. in the pendulum sources and I don't see how the concept of what I did differs from the build files there.

**Comment by dimbleby** [comment]
```toml
generate-setup-file = true
```
probably

**Comment by ngoettin** [comment]
Thank you so much, this solved the issue for me!

**Comment by ywu** [comment]
I encountered the same problem. Where to put that `generate-setup-file=true` setting?

**Comment by ywu** [comment]
Never mind. I just figured out.
```
[tool.poetry.build]
script = "build.py"
generate-setup-file=true
```
