### ISSUE TITLE
poetry install pending

### ISSUE THREAD

**Issue by ChufanSuki** [python-poetry/poetry#7557]
- **Poetry version**: 1.3.2 
- **Python version**: 
- **OS version and name**: Ubuntu 20.04
- **pyproject.toml**: <script src="https://gist.github.com/ChufanSuki/8a148885b82e32c1403a7d874ff7fcda.js"></script>

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

poetry install pending.
```
>>> poetry install -vvv
Loading configuration file /home/chufan/.config/pypoetry/config.toml
Using virtualenv: /home/chufan/.cache/pypoetry/virtualenvs/cleanba-1vF5hBzL-py3.8
Installing dependencies from lock file

Finding the necessary packages for the current system

Package operations: 96 installs, 1 update, 0 removals, 1 skipped

  • Installing numpy (1.24.2): Pending...
[keyring.backend] Loading KWallet
[keyring.backend] Loading SecretService
[keyring.backend] Loading Windows
[keyring.backend] Loading chainer
[keyring.backend] Loading libsecret
[keyring.backend] Loading macOS

```

**Comment by dimbleby** [comment]
installs fine for me.  I see keyring stuff in the output, maybe this another variation of #1917.  We've seen issues where keyring is asking for input, but the user doesn't get to see that request.

Anyway so long as this doesn't reproduce for anyone but you, it's hard to know what to suggest.  Typical tries would be: add `-vvv` to your command in the hope that verbose output says something useful, disable the keyring, clear the cache.

If none of those helps you'll probably have to figure out for yourself what's going on, I'm afraid.

**Comment by ChufanSuki** [comment]
`PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring` solves this problem for me.

**Comment by xz-zhao** [comment]
i got exactly same issue, 
same OS but poetry version 1.4.0.
`export PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring` do not work

**Comment by ChufanSuki** [comment]
@xz-zhao You may need to provide a verbose output of your command, e.g. add `-vvv` to your command.

**Comment by Asthestarsfalll** [comment]
> i got exactly same issue, same OS but poetry version 1.4.0. `export PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring` do not work


Hi. Do you solve this ? I encounter the same issue.

**Comment by rjurney** [comment]
This solves it for me too:

```bash
export PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring
```

**Comment by dimbleby** [comment]
So far as I know no-one has ever said exactly what keyring is doing here.  Investigation welcome: perhaps python-keyring can be taught not to do whatever it is that results in this behaviour.
