### ISSUE TITLE
platformdirs 3.0.0 OSX/macOS config directory

### ISSUE THREAD

**Issue by sadikkuzu** [python-poetry/poetry#7558]
Hi,

[platformdirs 3.0.0](https://github.com/platformdirs/platformdirs/blob/main/CHANGES.rst#platformdirs-300-2023-02-06) has a breaking change on config directory again.

> platformdirs 3.0.0 corrected the OSX/macOS config directory from /Users/\<user\>/Library/Preferences/\<appname\> to /Users/\<user\>/Library/Application Support/\<appname\>. 

https://github.com/platformdirs/platformdirs/releases/tag/3.0.0
https://github.com/platformdirs/platformdirs/pull/137/files

Is it possible to remove this warning?
<img width="248" alt="image" src="https://user-images.githubusercontent.com/23168063/221348372-70959f23-2931-4072-8a7c-9a7e032fe949.png">

https://github.com/python-poetry/poetry/blob/c8945eb110aeda611cc6721565d7ad0c657d453a/src/poetry/locations.py#L24-L28

**Comment by dimbleby** [comment]
It's all quite a bit more complicated than that.

- First, poetry isn't currently using platformdirs 3.0: so your pull request is definitely wrong until that happens.
  - Getting to platformdirs 3.0 will require a virtualenv update, but per #7484 that's difficult and probably blocked for now
- Then, when the switch is made, the deprecation warnings can't just be dropped.  Rather, they need to be reversed
  - folk who have put their configuration where poetry / platformdirs 2.x have been telling them to put it should be told to put it back where platformdirs 3.x wants it

**Comment by sadikkuzu** [comment]
Oh, ok, I got it.
Thanks for fast and detailed answer.
And sorry for inconvenience.
All the best
