### ISSUE TITLE
Help with installation

### ISSUE THREAD

**Issue by lpzrulez** [python-poetry/poetry#7561]
Having error while installing poetry
Have latest version of python 
Also using the curl ssl link method 
Please help 
![1498ACFD-A46D-4C38-B18D-3A7449F1795C](https://user-images.githubusercontent.com/126184987/221369707-6ff6f737-6b4e-48b7-ba72-5efc58714d56.png)

**Comment by finswimmer** [comment]
Hello @lpzrulez,

you haven't come back to this issue for a long while. So I assume this is solved in the meantime and I can close this ticket.

Feel free to leave a comment if you disagree.

fin swimmer
