### ISSUE TITLE
Add dependency vendoring mechanism 

### ISSUE THREAD

**Issue by notkeo** [python-poetry/poetry#7566]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request

One of the cool features of pip is the ability to install dependencies without any internet/private pip repository access. This is a highly requested feature for isolated environments without any external access. 

How its works (basically):

###  Step 1. Vendoring dependencies (downloading deps locally)

```sh
mkdir vendor
pip download -r requirements.txt -d --platform manylinux1_x86_64 --python-version 3.9
git add ./vendor/*
```

###  Step 2. Installing dependencies from vendor

```sh
pip install -r -requirements.txt --find-links ./vendor/* --no-index
```

I think it is easy to add this feature to poetry. We already have lock file `poetry.lock` with the following package description:

```toml
[[package]]
name = "astor"
version = "0.8.1"
description = "Read/rewrite/write Python ASTs"
category = "dev"
optional = false
python-versions = "!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,>=2.7"
files = [
    {file = "astor-0.8.1-py2.py3-none-any.whl", hash = "sha256:070a54e890cefb5b3739d19f30f5a5ec840ffc9c50ffa7d23cc9fc1a38ebbfc5"},
    {file = "astor-0.8.1.tar.gz", hash = "sha256:6a6effda93f4e1ce9f618779b2dd1d9d84f1e32812c23a29b3fff6fd7f63fa5e"},
]
```

So, we can add the new section to `pyproject.toml` to configure vendoring feature:

```toml
[tool.poetry.vendoring]
directory = "./vendor"
```

and then the following command:

```sh
poetry add astor
```

will add new entry to  `poetry.lock` 

```toml
[[package]]
name = "astor"
version = "0.8.1"
# ...
find-links="./vendor/ " # HERE IS PATH TO DEPS 
# ...
```

**and** downloads dependency tarball locally into `/vendor` directory to allow to use it during

```sh
poetry install
```

**Comment by dimbleby** [comment]
duplicate #5983

**Comment by notkeo** [comment]
Okay. lets close issue as duplicate

**Comment by dimbleby** [comment]
you have the power to do that, I don't.  By all means please do press the 'close' button.
