### ISSUE TITLE
Poetry downloads optional packages

### ISSUE THREAD

**Issue by ashlin-k** [python-poetry/poetry#7568]
- **Poetry version**: 1.3.1
- **Python version**: 3.10.6
- **OS version and name**: Fedora 36
- **pyproject.toml**: https://gist.github.com/ashlin-k/04a723389aa6eacd776718c9b1ea6e7e

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

I have a package that I would like to mark as optional because the download takes a very long time. However, poetry is still downloading the package, even though `optional = True`. 

```
[tool.poetry.dependencies]
...
torch = {url = "https://download.pytorch.org/whl/cu116/torch-1.12.0%2Bcu116-cp310-cp310-linux_x86_64.whl", optional = true}

[tool.poetry.extras]
pytorch = ["torch"]
```

The packages are not installed (which is correct), but it would be preferred if poetry did not try to download them.

**Comment by radoering** [comment]
Poetry has to download the package for dependency resolution, i.e. creating the lock file. With an existing lock file, the dependency should not be downloaded for installation.

**Comment by dimbleby** [comment]
not a bug, should be closed
