### ISSUE TITLE
Build script not running since 1.4.0

### ISSUE THREAD

**Issue by behrj** [python-poetry/poetry#7577]
- **Poetry version**: 1.4.0
- **Python version**: 3.8.15
- **OS version and name**: Ubuntu 22.04
- **pyproject.toml**: 

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
Hey there, I hope this message finds you well. 
We noticed that since today our project does not build on github and after a bit of digging we saw that when switching to version 1.3.2, it was building just fine again. 
We saw that on version 1.4.0, the build script for c++ bindings (using pybind11) was not running at all. 
We have these bits in our toml: 
```
[build-system]
requires = ["pybind11", "setuptools", "poetry-core"]
build-backend = "poetry.core.masonry.api"
[tool.poetry.build]
script = "my/path/to/build.py" 
```
And we realised that build.py was never run under the version 1.4.0. 
No urgency from our side, we just switched back to 1.3.2 and we are fine like that. This issue report is only here to support you in your development of this super nice project. 
All the best, 
Jonas

**Comment by dimbleby** [comment]
probably duplicate #7553, probably with the same solution

**Comment by bentheiii** [comment]
Hi @dimbleby, I also ran into this, the solution proposed in #7553 (if I understand: adding `generate-setup-file = true` under `[build-system]` in `pyproject.toml`) didn't fix the issue.

Also, running with poetry 1.3.2 seems to work, indicating that this is not the same issue (since that issue also appeared in 1.3.2)

**Comment by behrj** [comment]
I also just tried the suggested fix with the same result. 
FYI @bentheiii , @dimbleby

**Comment by finswimmer** [comment]
> if I understand: adding generate-setup-file = true under [build-system] in pyproject.toml

No, you need to `generate-setup-file = true` to the `[tool.poetry.build]` section.

**Comment by behrj** [comment]
Thanks, @finswimmer, that was it. I just followed the recipe of @bentheiii and walked right into the same trap ;-). 
Anyhow, thanks to everyone. Issue is solved for me. Might still make sense to communicate this change of behaviour in the release notes, as it seems I am not the only one who suddenly finds their build stopped to work.
