### ISSUE TITLE
`poetry` fails to install the `cotengra` package all the time

### ISSUE THREAD

**Issue by joonasmalmi** [python-poetry/poetry#7596]
- **Poetry version**: 1.4.0
- **Python version**: 3.9.16
- **OS version and name**: macOS 12.6.1
- **pyproject.toml**: https://gist.github.com/joonasmalmi/e489a20a4a8632e4db5cabdb6dbaa4cd

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
Trying to install the `cotengra` package (https://github.com/jcmgray/cotengra) via poetry runs into two different types of issues. If I am in a directory that contains the above `pyproject.toml` and run `poetry install`, everything works fine. Now if I change `branch = "master"` into `rev = "1a746c6"` for example, so a commit that is not the latest, and run `poetry update`, I get the error:
`Failed to clone https://github.com/jcmgray/cotengra.git at '1a746c6', verify ref exists on remote.`
This commit still clearly exists in the repo, and this error happens for other commits as well that are not the latest. Now if I change the dependency in `pyproject.toml` back to the original `branch = "master"`, or the latest commit, and run `poetry update`, I get the error:
```
  AssertionError

  

  at ~/miniconda3/lib/python3.9/site-packages/dulwich/pack.py:699 in _object_offset
       695│ 
       696│         Args:
       697│           sha: A *binary* SHA string. (20 characters long)_
       698│         """
    →  699│         assert len(sha) == 20
       700│         idx = ord(sha[:1])
       701│         if idx == 0:
       702│             start = 0
       703│         else:
```
In order to get the installing and updating working properly again, I have to remove the poetry environment and `poetry.lock` file, and do a fresh poetry installation. 

The issue with `poetry` not finding a commit that is not the latest also occurs with a fresh installation and creation of the poetry environment, so if I have for example `rev = "1a746c6"` as the dependency for `cotengra` in `pyproject.toml`, then I still run into the error of the ref not being found.

This problem has also been tested for `poetry (version 1.3.2)` and `python (version 3.10). A friend also tested this on Arch Linux x86_64 (Kernel: 6.1.12-arch1-1), so does not appear to be an OS-specific problem.

The full debug error messages are here:
SHA error: https://gist.github.com/joonasmalmi/e43395887c2ec1235d9caf508f008100
Ref not found error: https://gist.github.com/joonasmalmi/bca1f8d7cf83c91f0f6ef08dec1fada0

**Comment by finswimmer** [comment]
Duplicate of #6455 I guess?

**Comment by joonasmalmi** [comment]
It appears so from some testing, I was able to recreate the errors with `pytest` package. I was confused as they did not report the `AssertionError` once trying to return back to the latest version, and I seem to have just gotten lucky with another package using the short hash. Will close this as a duplicate.
