### ISSUE TITLE
'poetry self update' downgrades some packages

### ISSUE THREAD

**Issue by lunarmint** [python-poetry/poetry#7600]
- **Poetry version**: 1.4.0
- **Python version**: 3.11.2
- **OS version and name**: Windows 11
- **pyproject.toml**: N/A

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
Using `poetry self update` on version 1.4.0 downgrades some of the packages:

```
PS C:\Users\lunarmint> poetry self update
Updating Poetry version ...

Using version ^1.4.0 for poetry

Updating dependencies
Resolving dependencies...

Package operations: 0 installs, 4 updates, 0 removals

  • Updating more-itertools (9.1.0 -> 9.0.0)
  • Updating zipp (3.15.0 -> 3.11.0)
  • Updating trove-classifiers (2023.2.20 -> 2023.1.20)
  • Updating virtualenv (20.20.0 -> 20.17.1)
```
Not a breaking bug but it's weird it happened.

**Comment by dimbleby** [comment]
the typical way to debug such things is to add a constraint forcing poetry to choose whatever you think it ought to have chosen all along.  Then one of two things will happen

- poetry will tell you why this solution is impossible all along
- poetry will allow you to take more recent versions of A and B, but will instead require you to downgrade C and D
  -  ie the latest versions of A, B, C, and D are not compatible, too bad

either way this is almost certainly not a bug

you didn't provide the details that the issue template asks for so it's impossible to be more specific

**Comment by iTitus** [comment]
I got the same downgrades happening after a fresh install and then directly after executing `poetry self update`.
OS is Windows 10, Python is 3.10

**Comment by finswimmer** [comment]
The initial installation of Poetry with the installer script is done by `pip` in the background. So `pip`  will resolve the dependencies. With `poetry self update` Poetry itself will do the update. `pip` and `poetry` resolves dependencies differently. So it might be, that some dependencies suddenly gets downgraded.
