### ISSUE TITLE
poetry update --only=dev updates main deps

### ISSUE THREAD

**Issue by last-partizan** [python-poetry/poetry#7616]
- **Poetry version**: 1.4.0
- **Python version**: 3.9.16
- **OS version and name**: ArchLInux

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- ~~If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.~~ (no exceptions)

## Issue

When executing `poetry update --only dev`, it will update all deps in lock-file, but updates immediately only dev group. If you run `poetry install` afterwards - it will update other deps.

## Expected behaviour

Lock-file is updated with only dev group packages.

## Reproduction

You can use https://github.com/MongoEngine/django-mongoengine package, for exampe:

```
> git clone https://github.com/MongoEngine/django-mongoengine.git
> cd django-mongoengine
> poetry install
> ...
> poetry update --only dev
Updating dependencies
Resolving dependencies... (1.5s)

Writing lock file

Package operations: 0 installs, 4 updates, 0 removals

  • Updating babel (2.11.0 -> 2.12.1)
  • Updating coverage (7.1.0 -> 7.2.1)
  • Updating pytest (7.2.1 -> 7.2.2)
  • Updating setuptools (67.2.0 -> 67.5.1)

> poetry install
Installing dependencies from lock file

Package operations: 0 installs, 1 update, 0 removals

  • Updating mongoengine (0.26.0 -> 0.27.0)

Installing the current project: django-mongoengine (0.4.6)
```

If you look at the lockfile - mongoengine is updated, but this was not expected.

**Comment by dimbleby** [comment]
duplicate #5876, please close

**Comment by last-partizan** [comment]
My bad, for some reason i didn't found it.
