### ISSUE TITLE
Distribute old versions of poetry

### ISSUE THREAD

**Issue by aerb** [python-poetry/poetry#7624]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request
There doesn't appear to be any way to download old versions of this tool. While upgrading is of course ideal its not always trivial working with old projects or building against CI's that are out of date.

**Comment by dimbleby** [comment]
please read the docs re installation, especially the bit that starts "Similarly, if you want to install a specific version, you can..."

please close

**Comment by gunungpw** [comment]
Similarly, if you want to install a specific version, you can use `--version` option or the `$POETRY_VERSION` environment variable:


```
curl -sSL https://install.python-poetry.org | python3 - --version 1.2.0
curl -sSL https://install.python-poetry.org | POETRY_VERSION=1.2.0 python3 -
```
