### ISSUE TITLE
(🎁) Provision python versions like Gradle does with toolchains

### ISSUE THREAD

**Issue by KotlinIsland** [python-poetry/poetry#7625]
- [🚀] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [🚀] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request

When working with a Gradle project, managing the install of the needed JDK is trivial due to [Toolchains](https://docs.gradle.org/current/userguide/toolchains.html), I think it would be great if Poetry could solve this same issue and automatically provision a valid python version.

**Comment by dimbleby** [comment]
this seems unlikely to happen.  Personally I don't even think it's a good idea: poetry already does too many things for my taste, and there are other tools available for managing your python installations.

Apart from anything else it's quite clear - see the issue backlog - that there's already more to do than the maintainers can keep up with, adding management of the python installation to that is not going to help.

**Comment by Secrus** [comment]
Far out of scope for Poetry.
