### ISSUE TITLE
Poetry cannot find version if platform not already included in the poetry.lock

### ISSUE THREAD

**Issue by sconti0** [python-poetry/poetry#7629]
I come with a problem, which in my opinion should be considered as a bug. But I also come with the root cause and a potential fix.

The issue is that  `poetry install` fails on platform A (let's say Linux) when the poetry.lock was committed by a platform B which updated the version of a package P to version x.x.2 whereas, at the moment when `poetry add P==x.x.2` was run, only the wheel for platform B was delivered.
The `add` command, in this case, adds an entry in the poetry.lock where only platform B is present. 
When the `poetry install` is executed on platform A, the poetry.lock is checked and only platform B is found, triggering the error: `unable to find candidates for P (x.x.2)`
This error happens even in the case, in the meanwhile, the version x.x.2 for platform A was delivered. It seems that once the platform is not present in the poetry.lock, the installation fails, without checking what's actually available in the repository.

A possible solution should be that, in case the platform A is missing in the poetry.lock, a final check is performed on the remote repo, before failing, and if the platform is present, the package is installed and the lock is updated with both platforms.

Side note: the issue is quite tricky, because even if, after running `poetry add` on platform B, someone delivers the platform A version, removing and readding the same version from platform B will not download the new entry for platform A: it seems it's cached in local.

Final information: I've noticed that if, instead, at the moment when the first `poetry add` was run, both platforms are delivered, both entries are created in the poetry.lock and no issue happens.

**Comment by dimbleby** [comment]
the way to resolve such cases is to clear your cache and re-lock.

it's obviously in the nature of a cache that if the information that it has cached changes, then the cache returns stale facts

**Comment by sconti0** [comment]
This would be a workaround, debatable, for the latest point, which I mentioned only for completeness of information. 
If I correctly understand, it doesn't address the real problem. 
Let me know if there are parts I should describe better.

**Comment by dimbleby** [comment]
the problem is completely understood: caches can become stale.  The entire fix is to clear your cache.  

There's nothing to do here except perhaps to add something to the docs to describe this - feel free to submit a merge request doing that.

**Comment by radoering** [comment]
The "real problem" (as per the title) that poetry refuses to install something that is not included in the lock file is by design. That's what the lock file is for. For convenience `poetry install` creates a lock file if there is no lock file. Apart from that, `poetry install` must not change the lock file. If some files are missing in the lock file, you have to lock again.
