### ISSUE TITLE
`poetry --version` shows `1.3.2` but, if we try to install poetry, we get an message saying that `1.4.0` is already installed

### ISSUE THREAD

**Issue by nbro10** [python-poetry/poetry#7634]
The problem is described in the title.

- **Poetry version**: 1.3.2 and 1.4.0
- **Python version**: 3.8.10
- **OS version and name**: Ubuntu 20.04.5 LTS / 20.04.5 LTS (Focal Fossa)
- **pyproject.toml**: none

- [ ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [ ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

The problem is described in the title. There isn't much more to add, except that I'm trying to install poetry with `curl -sSL https://install.python-poetry.org | python3 -` while `1.3.2` was installed with `pip` in this machine following the instructions [here](https://python-poetry.org/docs/#ci-recommendations). 

So, this may be due to the fact that two poetry installations are installed. 

In that case, how do I get rid of what of them (1.4.0)? 

Is suspect this is a linking issue because, before re-provisioning this machine with `poetry 1.3.2`, I had manually installed poetry with `curl` and exported to the PATH. This message that poetry 1.4.0 is already installed is output by `get_version` of [the installation script](https://install.python-poetry.org/).

So, two installation methods were used to install 2 different versions of poetry.

**Comment by neersighted** [comment]
This is a local configuration issue; you have multiple copies of Poetry. Indeed, you have correctly determined that multiple versions of Poetry were installed with different methods. If you want to uninstall the version installed with the installer, pass `--uninstall` as documented. If you want to uninstall the version installed with pip (I suggest doing this, as pip outside a virtual environment is not a supported method of installing Poetry), use pip to uninstall.

**Comment by neersighted** [comment]
"Hash problems" is undefined and unclear -- there is no inherent conflict from multiple copies of Poetry. I think it goes without saying that if you use multiple tools to install a program, you may end up with multiple undesired copies. This is especially obvious as we document multiple installation methods. If you think the docs would benefit in some way from specific warnings and have a wording in mind, feel free to send a PR.

**Comment by neersighted** [comment]
Right, and I'm stating that making an assertion that duplicate copies of Poetry causes an issue that is well-known, by-design, and defined by the source code of Poetry itself is spurious. It makes no sense to document that multiple copies of Poetry may cause #6301 as it is not the well understood cause of #6301. You may have found observationally that you no longer observed #6301; however, there is no reason to believe that they are causally linked ("I was indeed getting a similar error because of multiple installation of poetry.").
