### ISSUE TITLE
Install from pypi or any whl fails if filename case does not match internal dist-info case

### ISSUE THREAD

**Issue by jgentil** [python-poetry/poetry#7635]
### Boilerplate
- **Poetry version**: 1.4.0
- **Python version**: 3.11.1
- **OS version and name**: MacOS 12.6.3
- **pyproject.toml**: (irrelevant-happens in a fresh project)

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

### Traceback
`$ poetry add fastapi-restful`
```
Using version ^0.4.3 for fastapi-restful

Updating dependencies
Resolving dependencies... (0.5s)

Package operations: 1 install, 0 updates, 0 removals

  • Installing fastapi-restful (0.4.3): Failed

  KeyError

  "There is no item named 'FastApi_RESTful-0.4.3.dist-info/WHEEL' in the archive"

  at /usr/local/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/zipfile.py:1473 in getinfo
      1469│     def getinfo(self, name):
      1470│         """Return the instance of ZipInfo given 'name'."""
      1471│         info = self.NameToInfo.get(name)
      1472│         if info is None:
    → 1473│             raise KeyError(
      1474│                 'There is no item named %r in the archive' % name)
      1475│
      1476│         return info
      1477│
```

### Issue
If you download the actual wheel file from PyPI for this project, it's named `FastApi_RESTful-0.4.3-py3-none-any.whl` but internally if you unzip it, it contains these files:

`$ unzip ../FastApi_RESTful-0.4.3-py3-none-any.whl`
```
Archive:  ../FastApi_RESTful-0.4.3-py3-none-any.whl
  inflating: fastapi_restful/__init__.py
  inflating: fastapi_restful/api_model.py
  inflating: fastapi_restful/api_settings.py
  inflating: fastapi_restful/camelcase.py
  inflating: fastapi_restful/cbv.py
  inflating: fastapi_restful/cbv_base.py
  inflating: fastapi_restful/enums.py
  inflating: fastapi_restful/guid_type.py
  inflating: fastapi_restful/inferring_router.py
  inflating: fastapi_restful/openapi.py
  inflating: fastapi_restful/py.typed
  inflating: fastapi_restful/session.py
  inflating: fastapi_restful/tasks.py
  inflating: fastapi_restful/timing.py
  inflating: fastapi_restful-0.4.3.dist-info/LICENSE
  inflating: fastapi_restful-0.4.3.dist-info/WHEEL
  inflating: fastapi_restful-0.4.3.dist-info/METADATA
  inflating: fastapi_restful-0.4.3.dist-info/RECORD
```

The case discrepancy between the .whl name and the .dist-info directory is causing the issue.  PEP 427 doesn't really explicitly talk about case sensitivity.  This is a regression from Poetry 1.3.x and pip allows for the .dist-info directory to be found case-insensitively.

**Comment by dimbleby** [comment]
you've checked the "I searched for duplicates" box.  DId you really?

#7572

**Comment by jgentil** [comment]
Yeah, I searched and it didn't show up.  Too many open issues I guess?  Apologies for the duplicate.
