### ISSUE TITLE
Upgrading poetry from 1.3.1 to 1.4.0 leads to [extras.cupy.0] '^11.1.0' does not match '^[a-zA-Z-_.0-9]+$'

### ISSUE THREAD

**Issue by anates** [python-poetry/poetry#7636]
- **Poetry version**: 1.4.0
- **Python version**: 3.9.12
- **OS version and name**: Windows 10
- **pyproject.toml**: https://gist.github.com/anates/d822144f78911cf20b946d4c5faf7d15

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
After upgrading my poetry-version from 1.3.1 to 1.4.0, executing poetry fails with 
```
The poetry configuration is invalid:
 - [extras.cupy.0] '^11.1.0' does not match '^[a-zA-Z-_.0-9]+$'
```
This configuration worked fine before. What can I do to solve this issue, and to be able to run my scripts in the corresponding environment again?
Thanks!

**Comment by dimbleby** [comment]
you should read the poetry documentation regarding extras, and fix your configuration so that it is valid

**Comment by anates** [comment]
I found the solution, thanks! 
```
[tool.poetry.dependencies]
cupy = {version = "^11.1.0", optional=true}
[tool.poetry.extras]
cupy = ["cupy"]
```
Still, the toml-file was autogenerated by poetry, and therefore I assumed that it should have been valid from before? Or was there a change recently?

**Comment by dimbleby** [comment]
that section was certainly not autogenerated by poetry.  What you had has always been wrong, recent poetry tells you so.

**Comment by kkirsche** [comment]
I also ran into this, what you're implying, @dimbleby, is that extras do not support version restrictions such as `sqlalchemy>=1.4,<2` as other dependencies support. Do you have a source (not poetry's docs which are tool-specific) stating that Python doesn't support version specifications in extras? I could not locate one

**Comment by dimbleby** [comment]
> if I understood your comments properly (I may not have) is that extras do not support version restrictions such as sqlalchemy>=1.4,<2 as other dependencies support.

I haven't said anything of the sort, I have only encouraged reading the documentation.

I also don't see how the documentation could lead to that conclusion, but feel free to submit merge requests improving anything that is unclear.

**Comment by kkirsche** [comment]
The regular expression doesn't include commas, >, <, etc. Testing for me shows this to explicitly be the case

Apologies if I misunderstood you or put words in your mouth. I'll see if I have time to fix this and add the tests and all that. Last time I contributed though, I didn't feel like it was appreciated or a good interaction.

**Comment by kkirsche** [comment]
To avoid mixing this issue with that I'll make a demo repo and file a separate issue. Apologies for the confusion here

**Comment by radoering** [comment]
Poetry supports defining extras with version restrictions. See https://python-poetry.org/docs/pyproject#extras

**Comment by anates** [comment]
Anyway, I think this might stray off the initial issue, which is resolved now. Thus closing this issue.
