### ISSUE TITLE
RFE: please provide support for `platformdits` 3.x

### ISSUE THREAD

**Issue by kloczek** [python-poetry/poetry#7640]
https://github.com/python-poetry/poetry/blob/40061f9d1351a9f76d6bdc1db8b3d903864c1373/pyproject.toml#L69

**Comment by dimbleby** [comment]
https://github.com/python-poetry/poetry/issues/7558#issuecomment-1445041353

**Comment by kloczek** [comment]
How long it may take to migrate to new `platformdirs` 3.x? 🤔 
(just aasking to be able estimate other changes in my stack)

**Comment by radoering** [comment]
We'll probably update virtualenv in Poetry 1.5 (if that's the only blocker).

**Comment by Secrus** [comment]
`platformdirs` 3.x is now on master and will be available with the next release

**Comment by kloczek** [comment]
Thank you 👍 
Is it know ET when will be new release and/or what is still on outstanding list? 🤔 
(just asking to be anble coordinate my own changes)

**Comment by Secrus** [comment]
We don't have anything planned right now, but I will take a look at the open PRs and unreleased features/fixes and see what it will take to cut out a new release.

**Comment by kloczek** [comment]
Thx 👍
