### ISSUE TITLE
modern-installation fails to install setuptools `scripts`

### ISSUE THREAD

**Issue by davidszotten** [python-poetry/poetry#7641]
- **Poetry version**: 1.4
- **Python version**: 3.10.5
- **OS version and name**: official python:3.10.5-buster image
- **pyproject.toml**: private unfortunately

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
I use poetry to install a package that provides a script using the `scripts` setuptools feature. this no longer appears in my bin dir when i upgrade to poetry 1.4.  disabling the `installer.modern-installation` setting and retrying makes it install correctly

**Comment by davidszotten** [comment]
yes. found it in an internal package so didn't have an end-to-end repro

after some more digging i now know more. possibly the bug is in [installer](https://pypi.org/project/installer/) which does the actual installing

i have a wheel built with `poetry==1.2.0b3` where the script has been placed in `./my-package-0.0.1.data/scripts` instead of the normalised `./my_package-0.0.1.data/scripts` like all the other files (not in the data dir but paths are all normalised). pip happily installs this wheel correctly but installer fails to identify the correct install location

**Comment by dimbleby** [comment]
you still didn't provide a repro that would allow this project to say anything useful about what you're seeing.

this being an `installer` problem is plausible, do raise a bug there if you get far enough to decide that's right

**Comment by davidszotten** [comment]
will close for now
