### ISSUE TITLE
potential VersionRange mismatching bug

### ISSUE THREAD

**Issue by ticosax** [python-poetry/poetry#7642]
- **Poetry version**: 1.4.0
- **Python version**: 3.10.9
- **OS version and name**: Manjaro
- **pyproject.toml**: sorry, confidential. Instead I bring a regression test.

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
Hi,
I might have found a bug where VersionRange comparison is failing in a specific case,

The environment provides `<VersionRange >=3.11,<4.0>` The package requires `<VersionRange >=3.8,<3.12>`

It should be a match as python 3.11 should be accepted, in this specific example.
Instead `version_package.allows_all(version_python) is False`
I added a regression test in poetry-core to demonstrate what I believe to be a bug.

**Comment by dimbleby** [comment]
not a bug.  The package version `>=3.8,<3.12` does not allow all of the python versions `>=3.11,<4.0`.  (For example, it does not allow `3.12.0`

Therefore `False` is the correct return value for this test.

Please close.

**Comment by ticosax** [comment]
Thanks for answering.
Let me ask a question another then.
that's what `allows_all` means ? `all` versions included by the range ?
