### ISSUE TITLE
Docker build: poetry config http-basic leaks credentials in the console output

### ISSUE THREAD

**Issue by noorul** [python-poetry/poetry#7650]
- **Poetry version**:  1.3.2
- **Python version**:  3.10.5
- **OS version and name**:  Ubuntu 22.04, macOS 12.6 
- **pyproject.toml**:  N/A

- [ ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
```Dockerfile
ENV POETRY_VERSION=1.3.2
RUN poetry run pip install pip=="$PIP_VENV_VERSION" && \
    poetry config http-basic.jfrog "$JFROG_USERNAME" "$JFROG_PASSWORD" && \
    poetry install --only main
```

This outputs the following during `docker build`

```log
RUN poetry run pip install pip=="22.1.1" &&     poetry config http-basic.jfrog "secret" "secret" &&     poetry install --only main
```

**Comment by dimbleby** [comment]
this has nothing to do with poetry, that's how `docker build` works

**Comment by dimbleby** [comment]
try google

**Comment by noorul** [comment]
@lubeso Thanks for the suggestion. I choose to go with the environment variable per Pypi index. For more details https://python-poetry.org/docs/configuration/#http-basicname

**Comment by noorul** [comment]
Closing this, since nothing much can be done from poetry side.
