### ISSUE TITLE
poetry new: set python range

### ISSUE THREAD

**Issue by alanwilter** [python-poetry/poetry#7651]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request

Well, `poetry init --python ">=3.8, <3.11"` works great, so why don't we have?

```bash
poetry new hello_world --python ">=3.8, <3.11"
The option "--python" does not exist
```

**Comment by abn** [comment]
#9088 introduced the `--python` option to new.
