### ISSUE TITLE
Check path to the python file in tool.poetry.scripts

### ISSUE THREAD

**Issue by RalfKow** [python-poetry/poetry#7655]
## Feature Request
Would it somehow be possible to check whether the string is valid defined in the pyproject.toml f.e
[tool.poetry.scripts]
extract-day-ahead-prices="raw_sampleapp.feeds.extract_day_ahead_prices:cli"

**Comment by dimbleby** [comment]
there's currently no mechanism in poetry to introspect the source code of the project being managed, adding this function seems unlikely to happen.

**Comment by finswimmer** [comment]
Duplicate of #3333
