### ISSUE TITLE
Poetry incorrectly interprets PEP440 "compatible version" specifiers (`~=`) with patch version omitted

### ISSUE THREAD

**Issue by burnpanck** [python-poetry/poetry#7656]
- **Poetry version**: 1.4.0
- **Python version**:  3.10.8
- **OS version and name**: macOS 13.6.1
- **pyproject.toml**: 
```
[tool.poetry.dependencies]
python = ">=3.9"
portion = ">=2.2"
```

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
Dependency resolution fails for my project which asks for python 3.9+ and the python package [portion](https://github.com/AlexandreDecan/portion/blob/master/setup.py), which itself contains `python_requires="~= 3.7"` in it's `setup.py`. [PEP440](https://peps.python.org/pep-0440/#compatible-release) quite explicitly describes that as equivalent to `>=3.7, ==3.*`. If I read this correctly, then this really should allow *any* python 3 version, but the author probably intended to write `>=3.7` instead. In any case however, python 3.9 *should* be compatible with it. However, poetry fails the dependency resolution with
```
The current project's Python requirement (>=3.9) is not compatible with some of the required packages Python requirement:
  - portion requires Python ~= 3.7, so it will not be satisfied for Python >=4.0
  ...
```
Note that the PEP440 interpretation of the `~=X.Y` compatible version specifier is mostly equivalent with the `^=X.Y.Z` compatible version specifier, not the `~=X.Y.Z` approximate version specifier found in node. This is in contrast with PEP440's `~=X.Y.Z`, which *does* behave like node's `~=X.Y.Z` if I read both specs correctly.

**Comment by burnpanck** [comment]
Wait, I believe I did misread PEP440. The `,` of course means `AND`, not `OR`. So poetry is right, and portion is simply wrong.

**Comment by dimbleby** [comment]
https://python-poetry.org/docs/faq/#why-is-poetry-telling-me-that-the-current-projects-python-requirement-is-not-compatible-with-one-or-more-packages-python-requirements

please close

**Comment by burnpanck** [comment]
I stand proven as not having read the FAQ attentively enough - please excuse. I definitely need more sleep.

While I hear the argument for an upper bound to a compatibility specification, there is a flip-side to it: As a user, if I depend on two libraries with incompatible version specifications I'm out of luck - I either have to hope/beg the maintainers to update one of the packages, or, if licensed to, fork and fix myself. That is indeed the only option if the two libraries are truly incompatible. However, with pure-python packages, it is quite common that these are indeed almost infinitely forward compatible. While I obviously cannot guarantee that, I could be optimistic about it. This risks breaking an install for a downstream user, but in this case, the user *is not* out of luck. If my optimism was ill-advised, the user/downstream library can always narrow down my requirements specification without changing my library at all, by simply declaring a requirement itself. Of course, now there is an upper bound again, so this option is only better when the optimistic compatibility statement is *most of the time* proven true in the end.

That said, I of course respect the choice of the poetry authors here. I'm just starting to convert to poetry, so I still have to teach myself some things.

**Comment by dimbleby** [comment]
there has been lots of discussion about whether poetry's defaults re upper bounds are best, I don't want to rehash that here.

right now it's not relevant though: `portion` declares that it supports python `~= 3.7` so if your project relies on portion then - like it or not - that limits the range of python versions that you can support.
