### ISSUE TITLE
Plugin versions should be configurable as project dependencies

### ISSUE THREAD

**Issue by rowanseymour** [python-poetry/poetry#7657]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request
Plugins are super useful and we're now using https://github.com/monim67/poetry-bumpversion in our projects to keep `__version__` in the code in sync with the version in `pyproject.toml`. This plugin is configured by simply adding 

```
[tool.poetry_bumpversion.file."your_package/__init__.py"]
```

However, if someone builds the project and doesn't have `bumpversion` installed as a plugin, that is silently ignored and `__version__` is not updated. We need a way to declare that building this project requires `bumpversion>=x.y.z` to keep builds reproducible and consistent.

Or maybe at least poetry could error if it sees a config section that doesn't correspond to core or a known plugin?

**Comment by mbrignone** [comment]
This would be a great feature to have, and there seems to be quite some interest based on this issue and [this StackOverflow question](https://stackoverflow.com/questions/76329612/how-to-list-poetry-plugins-in-pyproject-toml).

**Comment by Secrus** [comment]
This feature was recently merged into main, will be available in the next release.

**Comment by allanlewis** [comment]
> This feature was recently merged into main, will be available in the next release.

This is great news - thanks to everyone who worked on this feature!

**Comment by dolfinus** [comment]
@Secrus could you please link a PR where this feature was implementing?

**Comment by jakobkogler** [comment]
This was implemented in #9547.
