### ISSUE TITLE
How to contribute to poetry: how to install from github?

### ISSUE THREAD

**Issue by garyo** [python-poetry/poetry#766]
I'd like to contribute to Poetry. In order to do it right and make sure it's working, I'd like to be able to install my fork locally, the way the `get-poetry` script does, with poetry itself and all the dependencies in `~/.poetry` separate from the system python. Are there instructions for doing that anywhere? I looked in `CONTRIBUTING.md` but didn't see anything immediately obvious.

**Comment by dubiouscript** [comment]
i just happen to have scrolled past 
https://github.com/sdispater/poetry/blob/master/get-poetry.py#L297
so it appears from 
` BASE_URL = "https://github.com/sdispater/poetry/releases/download/"`
/get-poetry.py downloads from git hub 
...
scanning the repo , perhaps this has some clues as to how poetry/releases gets packaged ?
https://github.com/sdispater/poetry/blob/master/make-linux-release.sh
+ https://github.com/sdispater/poetry/blob/master/sonnet

**Comment by garyo** [comment]
I know this got marked "stale" but I still think the original question would be nice to answer. How can people contribute to poetry's development? What's a good process to test it locally?

**Comment by GabrielSimonetto** [comment]
Maybe this is already solved by #3061 ?

**Comment by abn** [comment]
If any aspect of contribution has not yet been covered across #3061 and our `CONTRIBUTING.md` feel free to open specific issues or join the conversation on our discord server.

**Comment by abn** [comment]
Oh thank you @GabrielSimonetto for pinging this issue. :) Appreciate it.
