### ISSUE TITLE
Poetry publish returning Error 500 on a private repo during github action. Still publishes to repo

### ISSUE THREAD

**Issue by Gazzzzyy** [python-poetry/poetry#7664]
- **1.4.0**: 
- **3.10.10**: 
- **Windows 10 locally and on github actions**: 
- **https://gist.github.com/Gazzzzyy/f44d7722e50a55617fcbb37277a64dc4**: 

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

Hi all,
I've recently moved my teams python builds to use poetry, and I'm very happy with the outputs. One of the final stages in our CICD workflow is publishing our internal packages to a private MyGet repository. This was never an issue when relying on pip. However with the change over, that step in the pipeline "fails", returning an Error 500. The funny thing is, the package does get uploaded correctly however. So what ends up happening is that out github checks are flooded with failures, even though nothing as technically failed. I couldn't find anything matching this so far online, and was hoping you may have seen this before or at the least know how to supress this issue.

The workflow that triggers it is this

      - name: Build package
        run: |
          poetry build
      - name: Publish to MyGet
        run: |
          poetry publish -r myget -vvv

I'll post an example of the returned error message, but I don't know how helpful this will be for you

https://gist.github.com/Gazzzzyy/df225bd84d0e410926873e4b15f7594f

Thanks again for the great work

**Comment by dimbleby** [comment]
what do you expect poetry to do differently?  the server has reported an internal error, and poetry has told you so

seems like you want to raise this with www.myget.org

**Comment by Gazzzzyy** [comment]
Well the same publishing command via pip does not trigger this response from their servers. The only difference here is Poetry, so this to me seemed like the right place to raise this issue I'm having

**Comment by dimbleby** [comment]
myget is hitting an internal server error, this is unambiguously their issue.

if they think that poetry is doing something wrong to trigger their error, then they need to say what that is.

**Comment by Gazzzzyy** [comment]
I've raised an issue with myget and they're looking into it. If they come back to me stating that there is an issue with with Poetry I'll let you know for sure. If not, I'll close this issue after the weekend

Cheers

**Comment by Gazzzzyy** [comment]
Hi, hope you had a good weekend.
MyGet got back to me and said the issue is due to the files being corrupted on upload. 
I don't know why this would be the case but I got around to it by replacing 
`Poetry publish -r myget`
with
` poetry run twine upload dist/*.whl --repository-url <URL> -u <username> -p <password>`

If you want to look into this then I can leave this open and help you out with any more information needed. If not, then please close whenever you want

Cheers
