### ISSUE TITLE
`poetry update --only=main` changes lock file for all groups

### ISSUE THREAD

**Issue by LiquidFun** [python-poetry/poetry#7708]
- **Poetry version**: 1.4.1 
- **Python version**: 3.10.6 
- **OS version and name**: Ubuntu 22.04 

- **pyproject.toml**: [link](https://gist.github.com/LiquidFun/def4681f611f7b1b4b20ff4db2c59aa9) 

- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

I've noticed odd behaviour which does not feel right or intuitive, or at the very least I feel is not documented.

When running `poetry update --only=main` the lock file is silently modified for all dependencies in all groups, despite me expecting it to only modify it for the main group. This seems like it would quickly lead to diverging dependencies and lock file, as now my local tests will run the currently installed dependencies, but someone else would install the newest dependencies from the lock file.

In order to reproduce (install toml to **dev** group):
```
poetry new abcd
poetry add toml@0.10.1 -G dev
```
Now remove version restriction for toml (simulates there being an update for it) and update **main** group:
```
sed -i 's/0.10.1/^0.10.1/' pyproject.toml
poetry update --only=main
```

now check the lock file:
```
grep toml poetry.lock
```
it will output this (notice it has updated toml to 0.10.2, despite it being in the **dev** group, and me updating the **main** group):
```
name = "toml"
    {file = "toml-0.10.2-py2.py3-none-any.whl", hash = "sha256:806143ae5bfb6a3c6e736a764057db0e6a0e05e338b5630894a5f779cabb4f9b"},
    {file = "toml-0.10.2.tar.gz", hash = "sha256:b3bda1d108d5dd99f4a20d24d9c348e91c4db7ab1b749200bded2f839ccbe68f"},
```

The same thing happens with the `--with` and `--without` flags. This behaviour happens to any group, the `main` group was just an example.

**Comment by dimbleby** [comment]
duplicate #5876

**Comment by LiquidFun** [comment]
Oops, didn't see those!
