### ISSUE TITLE
`poetry init` should have an option to create template files similar to `poetry new`

### ISSUE THREAD

**Issue by unixorn** [python-poetry/poetry#7709]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request

Currently, `poetry init` only walks us through creating `pyproject.toml`. On the other hand, `poetry new xyz` will create a `tests` directory and an xyz source directory when it creates the new project directory which is very helpful.

I would like an option to have `poetry init --create-files` (or perhaps `poetry new --here`) also create those directories, in the current directory.

The reason I'd like this is because at work, we have a template repository for new projects that includes other configuration files - `.flake8`, `.pre-commit-config.yaml` and so on with the standard settings we want our internal tooling to use.

It would be very helpful to be able to clone the template repository that has our configuration files in it, then do `poetry init --files` and have `poetry` create the `tests` and module source skeleton directories.

**Comment by dimbleby** [comment]
is anything wrong with `poetry new .`?

**Comment by unixorn** [comment]
Well crud, I would have sworn when I tried that I got a complaint about the directory existing

**Comment by unixorn** [comment]
It only works if the current directory is empty, which it won't be in the case of cloning a repo with a bunch of configuration in it before trying the `poetry new .`

Example:
```shell
$ pwd
/Users/unixorn/s/testit
$ ls -a
.git           .gitignore        .pre-commit-config.yaml  Makefile
.editorconfig  .jscpd.json       .trivyignore             Rakefile
.flake8        .mega-linter.yml  Dockerfile               README.md
$ poetry new --src --name testit .

Destination /Users/unixorn/s/testit exists and is not empty
```

**Comment by dimbleby** [comment]
so do `poetry init` first and then `git clone`?

(or update your template files so that they include the poetry files all along)

**Comment by unixorn** [comment]
`poetry init` doesn't create the `modulename` and `tests` directories with the initial poetry templated files, only `pyproject.toml`.

I don't want the template file to include those directories because then they start out with the same module name and are frozen at the point I initially created them - I want newer poetry version changes to the templates to be automatically included.

**Comment by dimbleby** [comment]
sure, I meant `poetry new`, whatever.

But since git will also reject attempts to clone into an existing folder that doesn't work anyway...

However, this gives pretty good ballast to the idea that poetry is probably right to refuse to `poetry new` in an existing folder: it is in full agreement with `git` on this matter.  (Did you try raising a feature request against git?)

if you're unwilling to write a single template - I'd suggest that poetry's initialization doesn't change often enough that your wish to be up to date is worh worrying about - then you'll porobably have to come up with your own workaround: do the two things in different places and then merge them together yourself, or something like that.

**Comment by unixorn** [comment]
I don't expect `poetry` to overwrite existing files/directories in this case, but it seems reasonable to want to use `poetry` to add template files in an existing directory.

Creating them in a subdirectory and moving them back to the parent is the workaround we're using, it's just awkward and feels hacky.

**Comment by dimbleby** [comment]
this issue has drifted some way from where it started, suggest retitling so that someone with power to do so can more easily make a sensible decision about it

**Comment by Secrus** [comment]
`poetry new` is meant to be a simple starting point. If you want something more complex, you should look at tools like `cookiecutter` or `copier`.
