### ISSUE TITLE
Cannot install torch 1.10.2 with poetry 1.4.1 on python:3.8-slim linux/amd64 docker image

### ISSUE THREAD

**Issue by malanEvans** [python-poetry/poetry#7713]
- **Poetry 1.4.1**: 
- **When building on python:3.8-slim linux/amd64 docker base image**: 
- **[pyproject.toml](https://gist.github.com/malanEvans/1f440e9d62ca5cc043d0fec18213e21d) (Dockerfile is attached as well)**: 

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate. [([](https://github.com/python-poetry/poetry/issues/7099))](https://github.com/python-poetry/poetry/issues/7099) looks similar, but not the same.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
When the attached Dockerfile is used to build an image with following command,
`docker build .`
from the directory with `pyproject.toml` file, 'RUN poetry install' step fails with the following error,

```
` 
  _WheelFileValidationError
 
  ["In /root/.cache/pypoetry/artifacts/c8/6e/03/5c824b6564a6d8451e0fdfc8843110e61a5342f7aa62dcd8fc0b05a83e/torch-1.10.2-cp39-cp39-manylinux1_x86_64.whl, hash / size of torch-1.10.2.dist-info/METADATA didn't match RECORD"]
 
  at /opt/venv/lib/python3.9/site-packages/installer/sources.py:289 in validate_record
      285│                         f"In {self._zipfile.filename}, hash / size of {item.filename} didn't match RECORD"
      286│                     )
      287│
      288│         if issues:
    → 289│             raise _WheelFileValidationError(issues)
      290│
      291│     def get_contents(self) -> Iterator[WheelContentElement]:
      292│         """Sequential access to all contents of the wheel (including dist-info files).
      293│
` 
```

this works well when `poetry==1.4.0` is used.
This works well even with `poetry==1.4.1` if docker image is built on [arm64v8/python](https://hub.docker.com/r/arm64v8/python/) base image

**Comment by radoering** [comment]
Duplicate, see #7686

**Comment by admackin** [comment]
Thanks @radoering – we were skeptical but it looks like this is correct. So you're saying that incredibly widely-used python ML package Pytorch has had broken intel binaries in version 1.10.2 this whole time? It is not entirely clear what error to report to Pytorch maintainers, since it's been working with `pip` and `poetry` (and other packaging tools presumably) up until now.

**Comment by dimbleby** [comment]
the error message says exactly what's wrong with the wheel and it sounds as though you have verified it yourself, this should be an easy bug report
