### ISSUE TITLE
Cannot import from Git if dependency name does not match the package name

### ISSUE THREAD

**Issue by rmnvncnt** [python-poetry/poetry#7716]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request

I'm trying to collect dependencies from a Github repository. However, the name of the package does not match the Github URL extension, which causes an error : 

```
jax = "0.4.6"
jaxlib = [
    { git = "https://github.com/yoziru/jax.git", tag = "jaxlib-v0.4.6", markers = "platform_machine == 'aarch64'"},
    { git = "https://github.com/google/jax.git", tag = "jaxlib-v0.4.6", markers = "platform_machine != 'aarch64'"}
]
```
Resulting in :
```
  RuntimeError

  The dependency name for jaxlib does not match the actual package's name: jax
```
This behavior seems to be desired (as per the Poetry [source code](https://github.com/python-poetry/poetry/blob/fa5543a639e76d14e7262572ea6b06fe099c0f46/src/poetry/puzzle/provider.py#L229)), so I don't think this is a bug. But in my case, I don't really have an option to circumvent this. Would it be possible to add a config to by pass this behavior and allow recovering mismatching package and dependency names?

**Comment by finswimmer** [comment]
The package name is taken from the `setup.py` and there it is called `jax`: https://github.com/yoziru/jax/blob/f1f4840a0d7af7b206c50874d877627cdeddb004/setup.py#L56

**Comment by rmnvncnt** [comment]
Ok I tried to point to `/jax/jaxlib/setup.py` instead using the `subdirectory` directive, but I get an error due to missing `version.py` file in the subdirectory. That file should be there, the error seems to be on jax's side. I'm closing for now!

Thanks @finswimmer
