### ISSUE TITLE
poetry add incorrectly selects linux torch wheel on windows, despite explicitly setting platform too

### ISSUE THREAD

**Issue by doctorpangloss** [python-poetry/poetry#7720]
- **Poetry version**: `Poetry (version 1.4.1)`
- **Python version**: 3.10.5
```$ poetry debug info
Poetry
Version: 1.4.1
Python:  3.10.5

Virtualenv
Python:         3.10.5
Implementation: CPython
Path:           C:\Users\bberman\AppData\Local\pypoetry\Cache\virtualenvs\comfyui-9d3XUl2I-py3.10
Executable:     C:\Users\bberman\AppData\Local\pypoetry\Cache\virtualenvs\comfyui-9d3XUl2I-py3.10\Scripts\python.exe
Valid:          True

System
Platform:   win32
OS:         nt
Python:     3.10.5
Path:       C:\Python310
Executable: C:\Python310\python.exe
```
 
- **OS version and name**: Windows Server 2022 LTSC
```
$ uname -a
Windows_NT AppMana-001 10.0 20348 x86_64 MS/Windows
```

- **pyproject.toml**:
```
[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.poetry]
name = "comfyui"
version = "0.0.1"
authors = [""]
description = ""

[[tool.poetry.source]]
name = "nvidia"
url = "https://download.pytorch.org/whl/cu117"
default = false
secondary = true

[[tool.poetry.source]]
name = "amd"
url = "https://download.pytorch.org/whl/rocm5.4.2"
default = false
secondary = true
```

- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

Invoking `poetry add` incorrectly selects a Linux wheel despite the platform and other details being reported correctly by `poetry debug info`. This issue does not reproduce in `pip` or `setup.py`.

### Reproduction:

 0. Install poetry for Windows and make sure it is added to your path.
 1. Run any of the commands as an example:

```
$ poetry add --platform win32 --group nvidia --source nvidia torch==1.13.1

Updating dependencies
Resolving dependencies... Downloading https://download.pytorch.org/whl/cu117/torch-1.13.1%2Bcu117-cp310-cp310-linux_x86_64.whl   5% (1.8s)
^C
$ poetry add --platform win --group nvidia --source nvidia torch==1.13.1

Updating dependencies
Resolving dependencies... Downloading https://download.pytorch.org/whl/cu117/torch-1.13.1%2Bcu117-cp310-cp310-linux_x86_64.whl   6% (2.1s)
^C
$ poetry add --platform win_amd64 --group nvidia --source nvidia torch==1.13.1

Updating dependencies
Resolving dependencies... Downloading https://download.pytorch.org/whl/cu117/torch-1.13.1%2Bcu117-cp310-cp310-linux_x86_64.whl   3% (1.1s)
^C
$ poetry add --platform windows --group nvidia --source nvidia torch==1.13.1

Updating dependencies
Resolving dependencies... Downloading https://download.pytorch.org/whl/cu117/torch-1.13.1%2Bcu117-cp310-cp310-linux_x86_64.whl   7% (2.4s)
^C
~/Documents/ComfyUI $ poetry add --group nvidia --source nvidia torch==1.13.1

Updating dependencies
Resolving dependencies... Downloading https://download.pytorch.org/whl/cu117/torch-1.13.1%2Bcu117-cp310-cp310-linux_x86_64.whl   3% (1.1s)
```

**Comment by dimbleby** [comment]
What you are seeing is poetry downloading a wheel in order to determine the dependencies of torch - it is not trying to install the wheel.

Since poetry builds cross-platform solutions, the linux wheel is as good as any other for this purpose; that you happen to be on windows is irrelevant at this pont.

Not a bug, please close

**Comment by doctorpangloss** [comment]
This appears to be the case, sorry for jumping the gun here. Hopefully at the end of this journey, I have a snippet to end everyone's `torch` woes!
