### ISSUE TITLE
Pytorch support

### ISSUE THREAD

**Issue by doctorpangloss** [python-poetry/poetry#7721]
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request
`poetry` should support installing packages with implicit, complex device requirements.

Here is an example `pyproject.toml` that should be supported:

```
[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[project]
requires-python = "~3.9.0, ~3.10.0"

[tool.poetry]
name = "mymltool"
version = "0.0.1"
authors = [""]
description = ""


# right now, specifying exactly two python versions does not work
[tool.poetry.dependencies]
python = "~3.10.0"

[[tool.poetry.source]]
name = "nvidia"
url = "https://download.pytorch.org/whl/cu117"
default = false
secondary = true

[[tool.poetry.source]]
name = "amd"
url = "https://download.pytorch.org/whl/rocm5.4.2"
default = false
secondary = true

[tool.poetry.group.nvidia]
optional = true

[tool.poetry.group.nvidia.dependencies]
torch = { source = "nvidia", version = "1.13.1" }
torchvision = { source = "nvidia", version = "0.14.1" }
torchaudio = { source = "nvidia", version = "0.13.1" }
xformers = { version = "0.16.0" }

[tool.poetry.group.amd]
optional = true

[tool.poetry.group.amd.dependencies]
torch = { source = "amd", version = "1.13.1" }
torchvision = { source = "amd", version = "0.14.1" }
torchaudio = { source = "amd", version = "0.13.1" }
```

An end user could select `poetry install --with amd` versus `poetry install --with nvidia`. Similar to the plugin solution.

Currently, because of `xformers`, only CPU versions of torch will be selected and the `poetry.lock` will not be useful.

This is referencing https://github.com/python-poetry/poetry/issues/6409 and https://github.com/python-poetry/poetry/issues/1168

The simplest way to achieve this without using plugins appears to be maintaining N separate pyproject.toml and poetry.lock files. Since these could be templated, this should illuminate how the dependency issues caused by pytorch are an essential problem poetry should tackle.

**Comment by dimbleby** [comment]
> This is referencing https://github.com/python-poetry/poetry/issues/6409 and https://github.com/python-poetry/poetry/issues/1168

Indeed this seems like it's just a special case of mutually-exclusive groups per #1168.  Any reason not to close it as a duplicate?
