### ISSUE TITLE
Poetry 1.4.1: installing xgboost fails

### ISSUE THREAD

**Issue by ralscha** [python-poetry/poetry#7727]
- **Poetry version**: 1.4.1
- **Python version**: 3.11.1
- **OS version and name**: Windows 11 22H2 (22621.1413)
- **pyproject.toml**:  [gist](https://gist.github.com/ralscha/40e51b2fca47c58435b9d9ddff5c6027)

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
Installation (poetry install) fails with the following error

```
• Installing xgboost (1.7.4): Failed

  _WheelFileValidationError

  ['In C:\\Users\\use\\AppData\\Local\\pypoetry\\Cache\\artifacts\\22\\a3\\4d\\c286bdc72bd13f47699a5ebe1b4d9c0ec4565215cae93511681d43f34d\\xgboost-1.7.4-py3-none-win_amd64.whl, xgboost-1.7.4+36ad160501251336bfe69b602acc37ab3ec32d69.data/data/xgboost/vcomp140.dll is not mentioned in RECORD']

  at ~\AppData\Roaming\pypoetry\venv\Lib\site-packages\installer\sources.py:289 in validate_record
      285│                         f"In {self._zipfile.filename}, hash / size of {item.filename} didn't match RECORD"
      286│                     )
      287│
      288│         if issues:
    → 289│             raise _WheelFileValidationError(issues)
      290│
      291│     def get_contents(self) -> Iterator[WheelContentElement]:
      292│         """Sequential access to all contents of the wheel (including dist-info files).
      293│

  • Installing prj (0.1.0 C:/ws/home/project/core/shared/prj)
```

**Comment by dimbleby** [comment]
duplicate #7686, please close
