### ISSUE TITLE
generate-setup-file = false

### ISSUE THREAD

**Issue by jannikmi** [python-poetry/poetry#7733]
- **Poetry version**: 4.1.0
- **Python version**: 3.8, 3.9, 3.10, 3.11
- **OS version and name**: 
- **pyproject.toml**:

https://github.com/jannikmi/timezonefinder/blob/master/pyproject.toml

```
[tool.poetry.build]
script = "build.py"
generate-setup-file = false
```

- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below. (Cannot be reproduced locally)

## Issue

My GitHub Actions runs failed when using the latest poetry version `4.1.0` with the error:

```
poetry install -v
  
  [RuntimeError]
  The Poetry configuration is invalid:
    - [build] {'script': 'build.py', 'generate-setup-file': <tomlkit.items.Bool object at 0x7f0b9679fc70>} is not of type 'string'
```
(https://github.com/jannikmi/timezonefinder/actions/runs/4547527551/jobs/8017519862) 

I have checked that using the latest `tomlkit` version does not resolve the issue

I resolved the issue by pinning the previous release `pip install poetry==1.4.0`.

Locally (Macbook) i cannot reproduce the issue.

**Comment by dimbleby** [comment]
your stack shows that you were getting a truly ancient version of `poetry` in your CI pipeline.  Please close

**Comment by jannikmi** [comment]
Where can you see that? I installed poetry with pip install poetry>=1.4.1

https://github.com/jannikmi/timezonefinder/actions/runs/4547527551/jobs/8017519578#step:6:1

**Comment by dimbleby** [comment]
eg 
```
    File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/poetry/console/application.py", line 49, in poetry
      self._poetry = Factory().create_poetry(Path.cwd())
```
that hasn't been at line 49 since #2683

I expect you have somehow mixed up one virtual environment with another.  You'll figure it out, I'm sure. 

Please close
