### ISSUE TITLE
(🎁)  Per project pypi api tokens

### ISSUE THREAD

**Issue by KotlinIsland** [python-poetry/poetry#7734]
- [🚀] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [🚀] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request

Do you think it's a good idea to have separate tokens for separate projects? or a global one is fine for using with poetry???

![image](https://user-images.githubusercontent.com/65446343/228486858-210719f4-ccd4-406f-b3fc-eadb1a585b0b.png)

**Comment by dimbleby** [comment]
This is not a poetry question.

**Comment by dimbleby** [comment]
https://python-poetry.org/docs/configuration/#local-configuration, please close
