### ISSUE TITLE
Install: allow to exclude specific packages (but not their dependencies)

### ISSUE THREAD

**Issue by tomasz-sodzawiczny** [python-poetry/poetry#7735]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request

I have the following project structure:
```
.
├── my-app
│   ├── poetry.lock
│   └── pyproject.toml
└── my-lib
    └── pyproject.toml
```

`my-app` depends as a path dependency on local `my-lib`, which has some other dependencies.

Generally everything works great (🎉🎉🎉), _BUT_:

It's hard to create an optimal docker build process for it. Generally in docker you try to do "heavy things that change rarely" first (e.g. your dependencies), and layer "things that change often" (e.g. your code) on top. So in a simple case a Dockerfile with poetry could look something like:

```
COPY poetry.lock pyproject.toml ./        # this changes rarely
RUN poetry install --no-root              # this might take a long time, but that's ok, it's usually cached
COPY . ./                                 # this changes often
RUN poetry install --only-root            # this has to run almost every time, but it's ok because it's quick
```

In the above example I would love to be able to skip not only "root" but also the "local" dependencies. I could put them in a dependency group and something like `--without local`, but that would also (correctly and unsurprisingly) exclude the indirect dependencies.

You can imagine that my dependency tree looks something like:

```
my-app          (local code, changes often)
└─> my-lib      (local code, changes often)
    ├─> foo     (from registry, changes rarely, very big library)
    └─> bar     (from registry, changes rarely, very big library)
```

I want to install the heavy `foo` and `bar` first, and then my lightweight `my-*` in the next.

I don't expect that poetry would directly support this specific use-case, but it would be great if there was **a more flexible  "exclude" mechanism**, which allows to exclude specific packages (but not their dependencies)

Maybe something like `poetry install --skip <regexp>`.

Currently this can be done by `poetry export | grep <xyz> | pip install` chain, but having to escape from poetry install to pip just for this reason is very ugly.

**Comment by dimbleby** [comment]
duplicate #6845
