### ISSUE TITLE
Poetry suddenly started excluding `setuptools` after adding some group dependencies / is removing `setuptools` despite it being in the lock expected behaviour if its not in listed explicitly in project dependencies?

### ISSUE THREAD

**Issue by HarrisonWilde** [python-poetry/poetry#7742]
- **Poetry version**: 1.4.1
- **Python version**: 3.10.10
- **OS version and name**: macOS 13.2.1
- **pyproject.toml**: https://gist.github.com/HarrisonWilde/68a1f768edce110c3b940bab208e7df7

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

Happy to provide as much readout as I can once I get an initial response to this, as I am not sure what is most useful to provide. 

Basically though, I added a group of dev dependencies for building documentation and when I went to run my package noticed I was getting an error around `pkg_resources` being missing. Upen closer inspection I noticed that when I last installed the package with `poetry install --sync --with dev`, `setuptools` had been removed. I had never had `setuptools` in my `pyproject.toml` before this point (I have added it now as you can see in the gist) but I am wondering what caused this change / whether its because this was the first time I installed the package with the `--sync` flag and this is expected?

It seems odd as `setuptools` is present in the lock file and is clearly a dependency as my code crashes without it, so now I have had to manually add it to my project dependencies which I would rather not do.

**Comment by dimbleby** [comment]
if you depend on setuptools you should declare that dependency - just as for any other package that you depend on.

by the way use of pkg_resources is deprecated so you might want to look for ways to stop using it anyway

**Comment by HarrisonWilde** [comment]
Fair enough, the weird thing here is that it appears in the lock even when I don’t declare it (correctly) as SDV (one of my dependencies) uses ‘pkg_resources’. It feels hard to pin down exactly the blame here but I have a feeling in this case the package *should* be installed whether I declare it or not right?

On 30 Mar 2023, at 18:38, David Hotham ***@***.***> wrote:

﻿

if you depend on setuptools you should declare that dependency - just as for any other package that you depend on.

by the way use of pkg_resources is deprecated so you might want to look for ways to stop using it anyway

**Comment by dimbleby** [comment]
sdv does not declare a dependency on setuptools: if it is using pkg_resources without declaring that dependency then it is wrong too

**Comment by HarrisonWilde** [comment]
Ok, might be unfortunate timing as I bumped the version today, let me try and figure that out with them and report back. Cheers

On 30 Mar 2023, at 18:49, David Hotham ***@***.***> wrote:

﻿

sdv does not declare a dependency on setuptools: if it is using pkg_resources without declaring that dependency then it is wrong too

**Comment by HarrisonWilde** [comment]
So nothing has changed from the previous version to now with SDV, so I believe the issue is somewhere in my setup / the poetry side. I may be misunderstanding, but how can it be that the lock file contains a reference to `setuptools` but it is not installed upon installing the package?

**Comment by dimbleby** [comment]
lots of reasons eg it is needed only by dev packages, or on certain platforms. 

You are making this more complicated than you need to.  We have established that you and/or sdv are using `pkg_resources` without declaring a dependency on `setuptools`: so fix you code and/or submit a merge request to fix sdv so that you/they do declare that dependency.  Problem solved.

I see no reason to suspect a poetry bug, please close this issue
