### ISSUE TITLE
Poetry does not respect venvs with different architectures (32/64 bit) but same Python version

### ISSUE THREAD

**Issue by p-rogalski** [python-poetry/poetry#7765]
- **Poetry version**: 1.4.2
- **Python version**: 3.11.2
- **OS version and name**: Windows 11
- **pyproject.toml**: https://gist.github.com/p-rogalski/8a91a261c831bd8b4c336f9e7a2c0e9b

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

Try to create two venvs with same Python version, but different architecture (32/64 bit):

    poetry env use C:\Users\<USERNAME>\AppData\Local\Programs\Python\Python311-32\python.exe
    poetry env use C:\Users\<USERNAME>\AppData\Local\Programs\Python\Python311\python.exe
    
### Expected Behavior: 

Two venvs should be created:

    C:\Users\<USERNAME>\AppData\Local\pypoetry\Cache\virtualenvs\venv-test-vHa_og5L-py3.11-32
    C:\Users\<USERNAME>\AppData\Local\pypoetry\Cache\virtualenvs\venv-test-vHa_og5L-py3.11

### Observed behavior:

Only one venv was created:

    C:\Users\<USERNAME>\AppData\Local\pypoetry\Cache\virtualenvs\venv-test-vHa_og5L-py3.11

**Comment by dimbleby** [comment]
essentially duplicate #2089

If I were doing anything remotely sophisticated with environments I wouldn't use `poetry env` at all; use pyenv or `python3 -m venv` or whatever, and explicitly activate the environment before typing any `poetry` commands is my worklow.

**Comment by p-rogalski** [comment]
Thank you for your quick answer!

Sure, I will use `venv` directly.

You are right, this is essentially a duplicate issue and can be closed.
