### ISSUE TITLE
Can't publish `EPL-2.0` licensed package

### ISSUE THREAD

**Issue by PythonFZ** [python-poetry/poetry#7786]
- **Poetry version**: `Poetry (version 1.4.2)`
- **Python version**: `Python 3.10.9`
- **OS version and name**: Ubuntu 22.04
- **pyproject.toml**: https://github.com/zincware/IPSuite/blob/main/pyproject.toml

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
When using `poetry publish` with `EPL-2.0` license I get:
```
HTTP Error 400: Invalid value for classifiers. Error: Classifier 'License :: OSI Approved :: Eclipse Public License 2.0' is not a valid classifier. | b"<html>\n <head>\n  <title>400 Invalid value for classifiers. Error: Classifier 'License :: OSI Approved :: Eclipse Public License 2.0' is not a valid classifier.\n \n <body>\n  <h1>400 Invalid value for classifiers. Error: Classifier 'License :: OSI Approved :: Eclipse Public License 2.0' is not a valid classifier.\n  The server could not comply with the request since it is either malformed or otherwise incorrect.<br/><br/>\nInvalid value for classifiers. Error: Classifier &#x27;License :: OSI Approved :: Eclipse Public License 2.0&#x27; is not a valid classifier.\n\n\n \n"
```

Looking at https://pypi.org/classifiers/ PyPi seems to expect: `License :: OSI Approved :: Eclipse Public License 2.0 (EPL-2.0)` but poetry creates `License :: OSI Approved :: Eclipse Public License 2.0`

It seems like https://spdx.org/licenses/ diverges here from what PyPi expects. I'm not sure if this is a poetry issue but I don't know how to fix this otherwise.

**Comment by dimbleby** [comment]
Just change the license in pyproject.toml to be the string that pypi wants?

**Comment by gyund** [comment]
Just for clarity for anyone, in your `pyproject.toml` file, specify:

```toml
[tool.poetry]
license = "License :: OSI Approved :: Eclipse Public License 2.0 (EPL-2.0)"
```

I hit the same issue 👍

**Comment by gyund** [comment]
So in `pyproject.toml` file, I tried specifying the following:

```toml
[tool.poetry]
license = "License :: OSI Approved :: Eclipse Public License 2.0 (EPL-2.0)"
```

However pypi reports this:

```
License: Other/Proprietary License (License :: OSI Approved :: Eclipse Public License 2.0 (EPL-2.0))

Classifiers
...
[Other/Proprietary License](https://test.pypi.org/search/?c=License+%3A%3A+Other%2FProprietary+License)
```

It should actually show the following for classifiers:

```
License
[OSI Approved :: Eclipse Public License 2.0 (EPL-2.0)](https://pypi.org/search/?c=License+%3A%3A+OSI+Approved+%3A%3A+Eclipse+Public+License+2.0+%28EPL-2.0%29)
```

@PythonFZ , is this what you were suggesting or something else? AS mentioned above, if you specify `EPL-2.0` as the license, pypi errors out.

**Comment by gyund** [comment]
So just adding it to the classifiers works correctly:

```toml
classifiers = [
    "License :: OSI Approved :: Eclipse Public License 2.0 (EPL-2.0)",
```
