### ISSUE TITLE
poetry ignores for which which platforms wheels are available while locking.

### ISSUE THREAD

**Issue by randolf-scholz** [python-poetry/poetry#7796]
Occasionally, some packages releas new versions for only some platforms. For example as cvxopt recently https://github.com/cvxopt/cvxopt/issues/236. Also, even if wheels are provided for all platforms, sometimes it takes some time for all of them to be there, potentially due to long build times. For example, [tensorflow-text 2.12.1](https://pypi.org/project/tensorflow-text/#files) became available for mac-os on April 11, but wheels for Linux where only uploaded 2 days later.

If one had locked between those 2 dates it would prevent poetry install, because the solver selected 2.12.1, even though this version was not available for all platforms.

- **Poetry version**: 1.4.2
- **Python version**: 
- **OS version and name**:  Ubuntu 22.04

**Comment by dimbleby** [comment]
Correct, poetry does not take into account which distributions are available during locking.  Doing so would make the problem that it has to solve more or less intractable, this behaviour is highly unlikely to change.  Please close.

(There should be a FAQ for this, it is definitely frequently asked)
