### ISSUE TITLE
poetry install works for versions < 1.4.0 and fails for 1.4.0 (or higher)

### ISSUE THREAD

**Issue by ahmedtroudi-slimstock** [python-poetry/poetry#7805]
- **Poetry version**: 1.4.0
- **Python version**: 3.10.10
- **OS version and name**: Windows 11
- **Poetry pyproject.toml files** (refer to project structure below):
      [pyproject.toml](https://gist.github.com/ahmedtroudi-slimstock/f64e0b00bbc212c60a8052a24ccfdd24#file-pyproject-toml)
      [example_library/pyproject.toml](https://gist.github.com/ahmedtroudi-slimstock/f64e0b00bbc212c60a8052a24ccfdd24#file-example_library_pyproject-toml)
      [example_project/pyproject.toml](https://gist.github.com/ahmedtroudi-slimstock/f64e0b00bbc212c60a8052a24ccfdd24#file-example_project_pyproject-toml)

- [x ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x ] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
**Project Structure:**

parent folder is `poetry-example`
├─pyproject.toml
├───libraries
│   ├───example_library
│   │   ├───example_library
│   │   └───example_library_tests
│   │   └───pyproject.toml
└───projects
│   ├───example_project
│   │   ├───example_project
│   │   └───example_project_tests
│   │   └───pyproject.toml
 

Using the provided pyproject.toml files and the project structure described above, `poetry install` used to work without any issues for any poetry version between `1.2.0` and `1.4.0`. After upgrading to poetry `1.4.0`, I started getting the error message below:

>  ChefBuildError

 

>  Backend subprocess exited when trying to invoke get_requires_for_build_wheel
> 
>   error: Multiple top-level packages discovered in a flat-layout: ['example_library', 'example_library_tests'].
> 
>   To avoid accidental inclusion of unwanted files or directories,
>   setuptools will not proceed with this build.
> 
>   If you are trying to create a single distribution with multiple packages
>   on purpose, you should not rely on automatic discovery.
>   Instead, consider the following options:
> 
>   1. set up custom discovery (`find` directive with `include` or `exclude`)
>   2. use a `src-layout`
>   3. explicitly set `py_modules` or `packages` with a list of names
> 
>   To find more information, look for "package discovery" on setuptools docs.
> 
> 
>   at ~\AppData\Roaming\pypoetry\venv\lib\site-packages\poetry\installation\chef.py:152 in _prepare
>       148│
>       149│                 error = ChefBuildError("\n\n".join(message_parts))
>       150│
>       151│             if error is not None:
>     → 152│                 raise error from None
>       153│
>       154│             return path
>       155│
>       156│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:
> 
> Note: This error originates from the build backend, and is likely not a problem with poetry but with example-library (0.1.0 not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pep517 .

I have tried following the options listed in the error message and managed to make custom discovery work using the changes below to the `.toml` of every package (for now could only make it work using absolute paths):

> [project]
> name = "example_project"
> version = "0.0.1"
> 
> [tool.setuptools.packages.find]
> where = ["C:/Users/a.troudi/Clones/poetry-example/projects/example_project"]  # list of folders that contain the packages (["."] by default)
> include = ["example_project"]  # package names should match these glob patterns (["*"] by default)
> exclude = ["example_project_tests"]  # exclude packages matching these glob patterns (empty by default)

Changing the project layout to an `src-layout` works but is something I would‘ve liked to avoid because the project is large.

The last option of setting `packages` with a list of names likely works but requires rewriting the `.toml` file for `setuptools` instead of `poetry`.

Is this behaviour expected? I tried looking in the documentation if `PEP 517` is enforced starting version `1.4.0` but couldn‘t find anything conclusive.

Thanks!

**Comment by dimbleby** [comment]
You haven't set `build-system.requires` or `build-system.backends` in your `pyproject.toml`.

**Comment by ahmedtroudi-slimstock** [comment]
@dimbleby Thanks! That makes it work! Do you have any idea why this is now required in the newer poetry versions (>1.4.0) ?

**Comment by dimbleby** [comment]
modern installer.

please close!
