### ISSUE TITLE
(🎁) Add a `typed` option in the config

### ISSUE THREAD

**Issue by KotlinIsland** [python-poetry/poetry#7807]
- [🚀] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [🚀] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request

Somewhat related to #2913, I think it would be great if poetry had a `typed` config option, that could add the trove classifier and the `py.typed` file automatically. Personally, I think that `py.typed` files look out of place in src code, if poetry could generate one automatically in the dist, that would be awesome 🚀.

**Comment by dimbleby** [comment]
This would put poetry unnecessarily out of line with the rest of the python world, and be actively confusing eg when interacting with an editable install of a source directory.

I am sure that poetry should decline this suggestion.

**Comment by Secrus** [comment]
I agree with @dimbleby. If you don't like `py.typed` you should talk with Python authorities about changing the way that packages signal being typing-compatible globally.
