### ISSUE TITLE
Poetry resolver finds way too old `numba` dependency

### ISSUE THREAD

**Issue by nicholasjng** [python-poetry/poetry#7808]
- **Poetry version**: 1.4.2
- **Python version**: 3.11.3
- **OS version and name**: macOS 13.3
- **pyproject.toml**: https://gist.github.com/nicholasjng/4eecb8938a2452222d57978486e36585

## Issue

Consider the `pyproject.toml` linked above. poetry crashes on macOS (and Linux too, verified with a colleague) when running `poetry add mlflow` on it.

Background: `mlflow` has a dependency called `shap`, which is being resolved correctly. However, it in turn depends on `numba` via a wildcard specifier (`numba = "*"`), which resolves to `numba 0.51.2` on my machine.

This is weird to me for a couple of reasons: 

1. `numba`'s latest version is 0.56.4.
2. `numba==0.51.2` does not have wheels available for either my target Python version (`^3.9`) or my platform (macOS ARM64).

When explicitly adding numba via `poetry add numba`, the version is resolved correctly to `numba = ^0.56.4`.

NB1: The crash only happens because of the inability to build a wheel for `llvmlite` on my platform, which is a dependency of numba. So the crashing aspect is not too relevant in this case, but rather, the resolver question is.
NB2: A colleague verified that when bumping Python to 3.10 in the pyproject.toml above, the error disappears and numba is resolved to latest correctly.

Thank you for your consideration!

**Comment by dimbleby** [comment]
A sensible way to debug such things is to put an explicit constraint in your `pyproject.toml` requiring the appropriate version of the package that you would like to be installed.

Then `poetry` will spit out an error message telling you why it cannot do that.

It is highly likely that poetry is behaving correctly here, please close.

**Comment by nicholasjng** [comment]
I disagree - looking at the resulting lockfile, `numba` is not required by anything else, and specified as a wildcard exactly once (in the deps of `mlflow`), so I would expect poetry to pick the latest available release from PyPI matching both my target Python and platform.

Also, the issue mentions that poetry _can in fact_ do that, as in "install the correct package version without errors", when I explicitly force it to do so. I have the opinion that this should work without my saying so. If you think this is wrong, could you please explain why?

**Comment by dimbleby** [comment]
Did you try the experiment I proposed?  Please do so, and let poetry explain what you have missed.

**Comment by nicholasjng** [comment]
So using `poetry install --dry-run` with different constraints added to the `pyproject.toml` produces the following:

1. With only the `mlflow = "2.2.2"` constraint:  poetry resolves `numba = 0.51.2`, results in `llvmlite` build failures. Same with careted mlflow.
2. With `mlflow = "2.2.2"` and explicit `"numba = ^0.56.4` constraints: Poetry resolves `numba = 0.56.4`, resulting in a newer `llvmlite`, and no failures.

In my opinion, this proves that poetry is doing something funky in the bare `numba = "*"` resolve. There is no reason why a wildcarded numba should resolve to anything other than `latest`, right?

Side note: The package in question has more wildcarded dependencies, too, but all of them seem to appear in two or more places with semver constraints. Maybe it's a problem with single-wildcard deps?

**Comment by dimbleby** [comment]
And did you notice that when you get the latest numba, you no longer get the latest numpy?

The latest versions of numba and numpy are not compatible with one another.  Absent any explicit guidance in pyproject.toml, it's basically a coin flip which "wins",

There is no bug here, please close.
