### ISSUE TITLE
Different behavior when installing packages from a private repo than pypi

### ISSUE THREAD

**Issue by jzazo** [python-poetry/poetry#7814]
- **Poetry version**: 1.4.2
- **Python version**: 3.10.6
- **OS version and name**: Ubuntu 20.04
- **pyproject.toml**:
```
[tool.poetry]
name = "example"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
torch = "2.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```
The above `pyproject.toml` works and when I do
```
$ poetry run python
>>> import torch
```
everything works as expected.

If I add to the `pyproject.toml` the following info:
```
[[tool.poetry.source]] name = "my-private-repo" 
url = "https://pkgs.dev.azure.com/..."  # actual url
default = true
```
Then, poetry does not install pytorch correctly anymore and misses some drivers. It seems as if it does not identify all needed dependencies.

I want to ask if you think this might be an issue with poetry not behaving the same on pypi than on a private repo, or if it might be that devops does not work as pypi? The above has been working with past versions of torch<2.0.0.

Thanks.

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

**Comment by dimbleby** [comment]
non-pypi repositories are typically different than pypi repositories 

my wild guess would be that this duplicates #4000 etc (the more recent comments are more useful than the older ones)

however without a way to reproduce this it's unlikely that anyone can help you.

**Comment by martin-schulze-e2m** [comment]
I just stumbled upon the same problem using when using an Azure feed and whipped up a [reproducer](https://github.com/martin-schulze-e2m/poetry-legacy-repository-dependency-reproducer) that shows the same issue by injecting pypi as a legacy repo:
```
[[tool.poetry.source]]
name = "legacy"
url = "https://pypi.python.org/pypi"
```

We use the Azure feed as a transparent mirror for PyPi, so all packages should go through that. Nevertheless, I got a [workaround](https://github.com/martin-schulze-e2m/poetry-legacy-repository-dependency-reproducer/tree/workaround) when setting ("normal") PyPi as the source for the affected package.

@dimbleby Should I post that over at the other issue (#4000)? I think its a slightly different constellation.

**Comment by dimbleby** [comment]
No, you are duplicating https://github.com/python-poetry/poetry/pull/9130, https://github.com/python-poetry/poetry/issues/9191, https://github.com/python-poetry/poetry/issues/9195, https://github.com/python-poetry/poetry/issues/9244, https://github.com/python-poetry/poetry/issues/9266, https://github.com/python-poetry/poetry/issues/9272, https://github.com/python-poetry/poetry/issues/9288, https://github.com/python-poetry/poetry/issues/9294, #9301.

_This_ one should likely be closed, the reporter has never come back and there is not enough here to say anything useful.

**Comment by martin-schulze-e2m** [comment]
Thanks for your fast response. Just for future reference, following steps fixed it (although I did a fresh pipx install of poetry before?):

```
poetry self lock
poetry self install
poetry cache clear <affected_repo> --all
```

I think that I missed the `cache clear` part when I reinstalled. Anyways, it is working now, thanks again!
