### ISSUE TITLE
Fail to install panel without any message

### ISSUE THREAD

**Issue by xareelee** [python-poetry/poetry#7821]
- **Poetry version**: 1.4.2
- **Python version**: 3.11.3
- **OS version and name**: macOS 13.3.1
- **pyproject.toml**: https://gist.github.com/xareelee/24956d87fff89ad31a1b78dac524218b

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

I just start a playground project using `Panel`, but it failed to install it:

```sh
$ poetry new panel
$ cd panel
$ poetry add panel
Creating virtualenv panel in /Users/xaree/dev/playground/panel/.venv
Using version ^0.14.4 for panel

Updating dependencies
Resolving dependencies... (0.0s)

  AssertionError

  

  at /opt/homebrew/Cellar/poetry/1.4.2/libexec/lib/python3.11/site-packages/poetry/mixology/incompatibility.py:113 in __str__
      109│         )
      110│ 
      111│     def __str__(self) -> str:
      112│         if isinstance(self._cause, DependencyCause):
    → 113│             assert len(self._terms) == 2
      114│ 
      115│             depender = self._terms[0]
      116│             dependee = self._terms[1]
      117│             assert depender.is_positive()
```

**Comment by clintonroy** [comment]
You can't have a package depend on itself.

**Comment by xareelee** [comment]
My bad, I were not aware of the naming conflict.
