### ISSUE TITLE
sdist for poetry_core is missing tox.ini

### ISSUE THREAD

**Issue by mtelka** [python-poetry/poetry#7824]
The sdist package for poetry_core at PyPI is missing the `tox.ini` file.  Please add the missing file to sdist to make downstream testing easier.  Thank you.

**Comment by dimbleby** [comment]
I don't think you need tox.ini to run the tests.

It might be as well to remove tox altogether from poetry-core and its pipelines - it seems only to be used now for the integration tests, and I don't know whether it is bringing anything useful given that the github workflow already includes a matrix of python versions.

**Comment by mtelka** [comment]
I'm packaging poetry_core for OpenIndiana and I find testing really useful to confirm the package works as expected.  Thanks.

**Comment by dimbleby** [comment]
(let's not divide this conversation across the two issues, that's unnecessarily confusing and inconvenient)
