### ISSUE TITLE
This is expected behavior. See https://python-poetry.org/docs/master/repositories/#secondary-package-sources.

### ISSUE THREAD

**Issue by aguckenber-chwy** [python-poetry/poetry#7838]
I am slightly confused by an answer to a different closed issue.

              This is expected behavior. See https://python-poetry.org/docs/master/repositories/#secondary-package-sources.

_Originally posted by @abn in https://github.com/python-poetry/poetry/issues/4704#issuecomment-1126835357_

That documentation points to a command which is invalid:

```
poetry source add --priority=explicit foo https://foo.bar/simple/
> The option "--priority" does not exist
```

I assume this is related to the comment about `"Introduced in 1.5.0"` in the block but poetry is currently `1.4.x`. Is there a reason this feature is in the main documentation for something not release till the next minor? Also why is the verbage "Introduced" instead of "Introducing". Or was this supposed to be released currently?

**Comment by dimbleby** [comment]
That's a link to the docs for the master branch.  Of course it's expected that this includes things not yet released.  Go to the top of the page and switch to 1.4 (or 1.3) to see the docs for 1.4 (or 1.3).

I am a native English speaking and "introduced" is correct here, "introducing" would sound quite odd.

Please close.

**Comment by dimbleby** [comment]
I am not responsible for such things, sorry

**Comment by aguckenber-chwy** [comment]
No worries at all. Thank you for your time with the responses. Have a great week!
