### ISSUE TITLE
Python version compatibility variable?

### ISSUE THREAD

**Issue by akshat-cldcvr** [python-poetry/poetry#7839]
It's not clear from the document on how to mention for what all version of python are supported by a project.

Suppose I am building a package that will only work for Python 3.6 or higher, how will I configure it in pyproject.toml before publishing it on PyPi.

In tools like hatch, we mention this on the top level.
`target-version = ['py37', 'py38']`

This is an example pyproject.toml file

```
[tool.poetry]
name = "project-name"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "package_name", from = "src"}]

[tool.poetry.dependencies]
python = "^3.11"


[tool.poetry.group.test.dependencies]
pytest = "^7.3.1"
pytest-cov = "^4.0.0"
tox = "^4.4.12"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

```

**Comment by Secrus** [comment]
See `python` under `[tool.poetry.dependencies]`, that's the python version constraint for your package

**Comment by akshat-tamrakar** [comment]
@Secrus 

Thank you for replying but it's still unclear. It would be really amazing if you could provide a complete answer to how we will mention the package is compatible/supports Python versions py36, py37, py38, py39, and py310 but not py311.

These are all the variations I can think of.

1. 

> ```
> [tool.poetry.dependencies]
> python = "^3.6"
> ```

2.

>  ```
> [tool.poetry.dependencies]
> python = "~3.6"
> ```
> 

3.

> ```
>  [tool.poetry.dependencies]
> python = ">=3.6"
> 
> ```

4.

> ```
>  [tool.poetry.dependencies]
> python = ["3.6", "3.7", "3.8", "3.9", "3.10"]
> 
> ```

Sorry, it's a trivial question but I am jr developer.

**Comment by akshat-tamrakar** [comment]
Also, 
`poetry env use /full/path/to/python` command keeps on giving me `[WinError 5] Access is denied `  even after running cmd as administrator in windows

**Comment by finswimmer** [comment]
The supported Python versions are declared just as any other [dependency](https://python-poetry.org/docs/pyproject/#dependencies-and-dependency-groups). So you have to use any of the supported [version constraints](https://python-poetry.org/docs/dependency-specification/#version-constraints).

@akshat-tamrakar: Your issue is unrelated here. Please open a new one with full steps to reproduce and the complete output you see.
