### ISSUE TITLE
Files in nested folders don't get excluded along with upstream folders

### ISSUE THREAD

**Issue by TOffergeld** [python-poetry/poetry#784]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Win10 64bin
- **Poetry version**: 0.12
- **Link of a [Gist](https://gist.github.com/TOffergeld/656e46ab40ff63de3283f40d4b1b64a9) with the contents of your pyproject.toml file**: 

## Issue

Maybe this is a feature request rather than a bug, but here goes:
I would expect there to be a way to exclude nested folders and their contents by excluding the root (not necessarily project root, but root of the nested folders instead) folder (possibly with trailing wildcard characters), however this doesn't seem possible at the moment.

Perhaps either ```Builder.find_excluded_files()``` should return an exhaustive list of files within nested subfolders, or the files within nested subfolders need to be excluded somewhere down the line in the build process.

**Comment by sdispater** [comment]
Specifying only the root folder does not currently exclude nested items, like you said. However to workaround that you can specify a glob: `root/**/*` in `exclude`.

I have to agree though that it could be a nice improvement.

**Comment by sdispater** [comment]
It should be fixed in the latest `1.0.0` release.
