### ISSUE TITLE
Impossible to use 2 groups where a same package is declared but with a different URL

### ISSUE THREAD

**Issue by elapouya** [python-poetry/poetry#7841]
- **Poetry version**: 1.4
- **Python version**: 3.11.3 
- **OS version and name**: Ubuntu 22.04
- **pyproject.toml**: see below

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

I am using Poetry to manage my virtual environment. It seems impossible to use 2 groups where a same package is declared but with a different URL
For example, I would like to install `django-listing` from pypi when in production but use a local version of `django-listing` when developping, so I wrote this `pyproject.toml` file : 

```
[tool.poetry]
...

[tool.poetry.dependencies]
python = "^3.11"
Django = "^4.1.7"
...

[tool.poetry.group.prod]
optional = true

[tool.poetry.group.prod.dependencies]
django-listing = "^0.0.15"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
django-listing = {path = "../django-listing", develop = true}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

When I do :

```
poetry install --with prod --without dev
```

In a `poetry shell`, I can see with a `pip list` that It is always the develop version of django-listing that is used : It looks like the `--without dev` does not hide de `dev group` declaration : poetry is still using some informations in that group.

I tried to  clear caches, remove/re-create the environment or change declaration order in pyproject.toml but it did not help.

**Comment by Secrus** [comment]
Groups are not exclusive. This is mentioned in the documentation: https://python-poetry.org/docs/managing-dependencies/
