### ISSUE TITLE
Poetry lock pre-commit hook should skip gracefully if there's no internet connection

### ISSUE THREAD

**Issue by roblevy** [python-poetry/poetry#7855]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request

If there is no connection to the internet, the `poetry-lock` pre-commit hook will wait until a 45 second timeout, before reporting:

```
HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/responses/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8cec6d1210>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
```

And this causes the hook to fail, preventing me from making my commit:

```
poetry-lock..............................................................Failed
```

If I get impatient and press `ctrl-c` during this 45 second delay, my unstaged changes are left in the cache, and I have to do some manual work to get them back.

I like this commit hook, but I often work on a train or somewhere with spotty internet connection, and this `poetry-lock` hook is usually a nice-to-have.

Would it be possible to have the `poetry-lock` pre-commit hook be skipped when failing to connect to the internet, so I can get on with my commit (and run the pre-commit hook myself later when I'm back online.)

**Comment by finswimmer** [comment]
Hey @roblevy,

I would suggest to [temporarily disable](https://pre-commit.com/#temporarily-disabling-hooks) this hook for your use case.

fin swimmer

**Comment by roblevy** [comment]
Nice, hadn't seen that. Thanks for pointing it out. I'll definitely use that for now.

The one downside is that this CLI workaround will interrupt the workflow of anyone committing via tooling like an IDE or a desktop app.

Any unsuspecting non-CLI user will (appear to) lose their unstaged work when they try to commit, think things are hanging, then bash Ctrl+C.

**Comment by dimbleby** [comment]
poetry doesn't know that your internet is down before trying it, and that's not likely to change.

if you have something practical in mind then submitting a merge request is the way to go, else I expect this should be closed

**Comment by finswimmer** [comment]
Hey @roblevy,

I'm closing this feature request, because I don't see how Poetry can provide something like this.

fin swimmer
