### ISSUE TITLE
I request that classifiers in `METADATA` what is created at build command are unique

### ISSUE THREAD

**Issue by yuji38kwmt** [python-poetry/poetry#7857]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request

When executing `poetry build`, poetry automatically added python requirement classifiers  and license classifier.

When python requirement classifiers are already listed in  `pyproject.toml` , classifiers in `dist/*.whl/*.dist-info/METADATA` are duplicated

An example is shown below.

```
[tool.poetry]
name = "yuji38kwmt-cli"
version = "0.1.0"
description = "yuji38kwmt's CLI"
authors = ["yuji38kwmt"]
license = "MIT"
classifiers = [
    "Operating System :: OS Independent",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]

packages = [
    { include = "yuji38kwmt_cli" }
]

[tool.poetry.dependencies]
python = "^3.9"
requests = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

```
$ poetry build --quiet

$ unzip -c  dist/yuji38kwmt_cli-0.1.0-py3-none-any.whl yuji38kwmt_cli-0.1.0.dist-info/METADATA | cat
Archive:  dist/yuji38kwmt_cli-0.1.0-py3-none-any.whl
  inflating: yuji38kwmt_cli-0.1.0.dist-info/METADATA  
Metadata-Version: 2.1
Name: yuji38kwmt-cli
Version: 0.1.0
Summary: yuji38kwmt's CLI
License: MIT
Author: yuji38kwmt
Requires-Python: >=3.9,<4.0
Classifier: License :: OSI Approved :: MIT License
Classifier: Operating System :: OS Independent
Classifier: Programming Language :: Python :: 3
Classifier: Programming Language :: Python :: 3.9
Classifier: Programming Language :: Python :: 3.10
Classifier: Programming Language :: Python :: 3.11
Classifier: Programming Language :: Python :: 3
Classifier: Programming Language :: Python :: 3.10
Classifier: Programming Language :: Python :: 3.11
Classifier: Programming Language :: Python :: 3.9
Requires-Dist: requests

```

`Operating System` and `License` classifiers are unique. But `Programming Language` classifiers are duplicated.

I request that `Programming Language` classifiers are also unique.

**Comment by dimbleby** [comment]
code looks as though it's [here](https://github.com/python-poetry/poetry-core/blob/f314393bb9780f2381db7794c98e678344fad7ec/src/poetry/core/packages/package.py#L360-L361), submit a merge request!

**Comment by yuji38kwmt** [comment]
OK! I create pull request https://github.com/python-poetry/poetry-core/pull/578
