### ISSUE TITLE
Resolver appears to run forever

### ISSUE THREAD

**Issue by darkpixel** [python-poetry/poetry#7858]
- Poetry (version 1.4.2)
- Python:  3.10.6
- Linux Mint 21.1
- https://gist.github.com/darkpixel/80c5d24da1d08c75f4a30a131a75a433

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

I tried to upgrade  werkzeug, urllib3, botocore, and boto3 and the resolver appears to have hanged.

```poetry add werkzeug=^2 urllib3=^2 botocore=^1 boto3=^1```

![Screenshot from 2023-05-01 10-29-32](https://user-images.githubusercontent.com/158380/235498222-5bf7e242-b57c-45c0-8f89-7f14e9bd44e9.png)

**Comment by dimbleby** [comment]
Amazon for whatever reason publish hundreds and thousands of releases of packages like boto3.  If the solver takes an unlucky turn such that it hits a dead end not compatible with any boto3 release, it can take a long time to work through those hundreds and thousands of releases.

Provide tighter bounds - then poetry can spot the dead-end more quickly.

**Comment by darkpixel** [comment]
Thanks @dimbleby !

**Comment by ahvigil** [comment]
I understand the problem here, and the workaround works well enough, but intuitively it seems a bit silly that poetry goes back into the vast abyss of botocore releases looking for an older version of the package to support a newer version of urllib3. If two versions conflict, wouldn't it make more sense to rollback the version of the more recent package?
