### ISSUE TITLE
`poetry run` doesn't work

### ISSUE THREAD

**Issue by neuromaancer** [python-poetry/poetry#7867]
Recently, I install the `pretty-errors` package to my poetry env. When I try to run the this module by `poetry run pretty-errors` , gave me this: `Command not found: pretty-errors`. Then, I tried to run with `python -m pretty-errors` after `poetry shell` , still gave me: `No module named pretty-errors`. And I am sure, it is installed, because when I rerun: `poetry add pretty-errors`, it gave me: `Nothing to add.`. The `pretty-errors` pypi website is here: https://pypi.org/project/pretty-errors/ 

Did you do something wrong?

**Comment by dimbleby** [comment]
what makes you think that either of those things should work?  

please pay attention to the documentation of `pretty-errors`, and then close this.
