### ISSUE TITLE
is there a way to control poetry's own dependencies?

### ISSUE THREAD

**Issue by xytxytxyt** [python-poetry/poetry#7877]
poetry installs its own dependencies separately:
```
$ poetry -V
Poetry version 1.1.15
$ ls -d1 /home/circleci/.local/share/pypoetry/venv/lib/python3.9/site-packages/requests*
/home/circleci/.local/share/pypoetry/venv/lib/python3.9/site-packages/requests
/home/circleci/.local/share/pypoetry/venv/lib/python3.9/site-packages/requests-2.30.0.dist-info
/home/circleci/.local/share/pypoetry/venv/lib/python3.9/site-packages/requests_toolbelt
/home/circleci/.local/share/pypoetry/venv/lib/python3.9/site-packages/requests_toolbelt-0.9.1.dist-info
$ ls -d1 /home/circleci/.local/share/pypoetry/venv/lib/python3.9/site-packages/urllib*
/home/circleci/.local/share/pypoetry/venv/lib/python3.9/site-packages/urllib3
/home/circleci/.local/share/pypoetry/venv/lib/python3.9/site-packages/urllib3-2.0.2.dist-info
```

(this is inside a cloud ci instance that installs poetry afresh every time it runs)

both the above versions are affected by https://github.com/ionrock/cachecontrol/issues/292

so pinning versions in our projects doesn't help because the affected versions are inside poetry itself

is there a way to control this? i looked at the script from https://install.python-poetry.org and didn't see anything in the `argparse` arguments that stood out... but asking in case there is a way

**Comment by Secrus** [comment]
On such an old version, the only way is to manually get into the venv Poetry is installed in and reinstall packages you want with `pip`. This issue is not present on Poetry 1.2+, so I would highly encourage migration to newer versions.

**Comment by xytxytxyt** [comment]
i see... we have poetry pinned to 1.1.15 because we are affected by https://github.com/python-poetry/poetry/issues/6301 which we have not had time to address... thanks for the manual update suggestion, i will try it
