### ISSUE TITLE
poetry incompatible with urllib3>=2

### ISSUE THREAD

**Issue by hippalectryon-0** [python-poetry/poetry#7878]
- **Poetry version**: 1.4.2
- **Python version**: 1.11.3
- **OS version and name**: Ubuntu 22.04
- **pyproject.toml**: https://pastebin.com/Wp45qtci

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
urllib got a new release 2.0.3 yesterday. This release introduces breaking changes, and poetry now errors with `HTTPResponse.__init__() got an unexpected keyword argument 'strict'` when running `lock` or `install`.

Steps to reproduce:
* run `poetry install` on a pytoml file installing urllib>=2, see example above
* run `poetry lock`

**Comment by Secrus** [comment]
This shouldn't be appearing on versions 1.2+, since we have strict dependency specifications on `urllib3`, which rule out `urllib3 >= 2`. My guess would be that you have Poetry installed in the same environment as your project, which is discouraged and prone to breakage when your dependencies clash with Poetry's.

**Comment by hippalectryon-0** [comment]
I don't think so:

```
❯ deactivate
❯ . venv/bin/activate
❯ pip uninstall poetry
WARNING: Skipping poetry as it is not installed.                                                                                                                                                                                                  100%  
❯ pip install "urllib3<2"
Collecting urllib3<2ib3<2"                                                                                                                                                                                                                        100%  
  Using cached urllib3-1.26.15-py2.py3-none-any.whl (140 kB)
Installing collected packages: urllib3
  Attempting uninstall: urllib3
    Found existing installation: urllib3 2.0.2
    Uninstalling urllib3-2.0.2:
      Successfully uninstalled urllib3-2.0.2
Successfully installed urllib3-1.26.15
❯ poetry lock
Updating dependencies                                                                                                                                                                                                                             100%  
Resolving dependencies... (1.4s)
❯ poetry install
Installing dependencies from lock file                                                                                                                                                                                                            100%  

Package operations: 0 installs, 1 update, 0 removals

  • Updating urllib3 (1.26.15 -> 2.0.2)

Installing the current project: xrscipy (1.0.0)

```

**Comment by Secrus** [comment]
Ok, how are you installing Poetry? Could you provide a `Dockerfile` with the reproduction steps? the issue doesn't reproduce for me

**Comment by hippalectryon-0** [comment]
Here's one:

```Dockerfile
FROM python:3.11-slim

COPY pyproject.toml .
RUN pip install poetry
RUN poetry install
```

Output:
> • Installing urllib3 (2.0.2)

**Comment by hippalectryon-0** [comment]
EDIT: Even though it does install 2.0.2 inside the venv, it seems that it doesn't error anymore. I guess I've fixed it while trying to make sure that poetry wasn't installed in the venv itself, so looks like you were right :)
