### ISSUE TITLE
Arbitrary Equality operator in version specification

### ISSUE THREAD

**Issue by antonia-adler** [python-poetry/poetry#7890]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request

This feature request relates to this issue: https://github.com/python-poetry/poetry/issues/7256

- We have two versions of a package: eg 1.0.1 and 1.0.1+variant
- Poetry does not allow installing 1.0.1 - it always installs 1.0.1+variant
- The [arbitrary equality](https://peps.python.org/pep-0440/#arbitrary-equality) operator seems to be recommended in such cases (which is not supported by poetry)

Is there any other way how to make it work in poetry?

**Comment by dimbleby** [comment]
I for one have no idea what the question is.  What are you doing?  What are you expecting to happen?  What is actually happening?

**Comment by antonia-adler** [comment]
I try to install version 1.0.1, but poetry always installs 1.0.1+variant (even when specifying "==1.0.1"). The arbitrary operator should be a way to install version 1.0.1 ("===1.0.1"), but it is not supported by poetry.  (Both versions are in the same source)

**Comment by dimbleby** [comment]
duplicate #7256, please close
