### ISSUE TITLE
Poetry returns exit code 1 when called with subprocess.run() if stderr and stdout are not piped.

### ISSUE THREAD

**Issue by ericycfu** [python-poetry/poetry#7906]
- **Poetry version**: 1.4.2 
- **Python version**: 
```
Poetry
Version: 1.4.2
Python:  3.10.5

Virtualenv
Python:         3.10.5
Implementation: CPython
Path:           /Users/ericfu/src/flock-monorepo/py/data_warehouse/.venv
Executable:     /Users/ericfu/src/flock-monorepo/py/data_warehouse/.venv/bin/python
Valid:          True

System
Platform:   darwin
OS:         posix
Python:     3.10.5
Path:       /Users/ericfu/.asdf/installs/python/3.10.5
Executable: /Users/ericfu/.asdf/installs/python/3.10.5/bin/python3.10
```
- **OS version and name**: macOS 12.6.2
- **pyproject.toml**: https://gist.github.com/ericycfu/969251cd4e794183767378777ef94121

- [x ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

I am upgrading from poetry 1.1.3 to version 1.4.2 due to https://github.com/ionrock/cachecontrol/issues/292#issuecomment-1538185470. The background behind my use case is that I have a monorepo with multiple python project directories, and have a script to create and install the dependencies in a in-project virtualenv for each project, so that i can run mypy on a per project basis specifying the appropriate virtualenv. 

The following code worked fine.
```
def create_venv(directory: str) -> None:
    """Creates a virtual environment in the directory"""
    # poetry shell and deactivate is kind of buggy so directly create venv
    subprocess.run(
        ["python3", "-m", "venv", ".venv"], cwd=directory, shell=False, check=True
    )
    env = os.environ.copy()
    env["VIRTUAL_ENV"] = f"{directory}/.venv/bin/python"
    subprocess.run(["poetry install"], cwd=directory, shell=True, env=env, check=True)
```
Upon upgrading, I found that the code would return the following error:
 ```
 Running mypy_runner...
/Users/ericfu/src/flock-monorepo/py/data_warehouse does not contain a .venv folder.
The virtual environment found in /Users/ericfu/src/flock-monorepo/py/data_warehouse/.venv/bin/python seems to be broken.
Recreating virtualenv data-warehouse in /Users/ericfu/src/flock-monorepo/py/data_warehouse/.venv
Installing dependencies from lock file

Package operations: 59 installs, 1 update, 0 removals

Traceback (most recent call last):
  File "/Users/ericfu/src/flock-monorepo/py/mypy_runner/mypy_runner/runner.py", line 154, in <module>
    sys.exit(main())
  File "/Users/ericfu/src/flock-monorepo/py/mypy_runner/mypy_runner/runner.py", line 142, in main
    create_venv(python_directory)
  File "/Users/ericfu/src/flock-monorepo/py/mypy_runner/mypy_runner/runner.py", line 100, in create_venv
    raise e
  File "/Users/ericfu/src/flock-monorepo/py/mypy_runner/mypy_runner/runner.py", line 81, in create_venv
    result = subprocess.run(
  File "/Users/ericfu/.asdf/installs/python/3.10.5/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['poetry install']' returned non-zero exit status 1.


SUMMARY: (done in 4.65 seconds)
🥊  mypy
 ```
 Adding `-vvv` to the command didn't change any output.
 In my process of investigating and trying to see what the actual poetry output was, I found that changing the `subprocess.run()` call to pipe the stdout and stderr fixed the issue.
 ```
 result = subprocess.run(
            ["poetry install"],
            cwd=directory,
            shell=True,
            env=env,
            check=True,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )
```
   
I feel like this is a bug given that it worked without this change on a previous version, and wanted to post in case anyone had a similar issue. Feel free to close this if this is expected behavior.

**Comment by dimbleby** [comment]
```
    env["VIRTUAL_ENV"] = f"{directory}/.venv/bin/python"
```
looks like nonsense, that's not what that variable should be set to

**Comment by ericycfu** [comment]
I don't think it's nonsense, but I agree that it is slightly incorrect. Rather it should be set to `f"{directory}/.venv"`. 
When I run `poetry shell` and `printenv`, I get `VIRTUAL_ENV=/Users/ericfu/src/flock-monorepo/py/data_warehouse/.venv`, so now I am setting it to the correct value.

The only difference that happens once I fix this is that it doesn't recreate the virtual environment at the start. Either way, poetry manages to install the dependencies to the virtualenv correctly. Sure, manually setting this environment variable might not be a supported use case, but the fact is that it doesn't have any impact on the actual behavior I'm describing. 

The problem I'm describing is solely replicated by calling `poetry install` from `subprocess.run()` without having `stdout=subprocess.PIPE` and `stderr=subprocess.PIPE`.

I have no issues currently with the current behavior of my code, so there is no debugging that I need to do. I'm posting just to share information about behavior that I've noticed. If calling `poetry install` from a subprocess is an entirely unsupported use case, then yes I will close this issue.

**Comment by dimbleby** [comment]
Your code is faulty and your diagnosis is faulty, this is nothing to do with poetry.

You should debug this by capturing stdout / stderr from the subprocess and looking at the errors that are reported, and fixing them

None of this is anything to do with this repository.  Please close.

**Comment by ericycfu** [comment]
I think you are misunderstanding the issue, but sure I'll close.
1. I have successfully, run `poetry install` from subprocess.
2. It worked successfully without capturing the stdout/stderr on version 1.1.3.
2. On version 1.4.2, it fails without capturing the subprocess.
3. When I do capture it, the command succeeds, and the stdout is exactly as I would expect (exactly the same as running the command in my terminal).

So I am thinking something internal is causing poetry to return a non-zero exit code when there is nowhere direct the stdout/stderr, which I have no insight into.
