### ISSUE TITLE
Adding Python arguments to shebang for tool.poetry.scripts

### ISSUE THREAD

**Issue by bphunter1972** [python-poetry/poetry#7907]
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request

Don't ask why because it's a long story, but I have an application that requires the shebang line to add the -u argument, like this:

`#!/my/application/bin/python3 -u`

I've been hacking it in there after a pip install, but I'm wondering if there is a way to add arguments like this? 
Perhaps there's a pyproject.toml option for pip that I couldn't find. But in either case it might be a nice feature to abstract this problem away for non-pip experts?

Thanks!

**Comment by Secrus** [comment]
From what I can see, the `-u` switch can also be expressed by the environment variable `PYTHONUNBUFFERED`. While I understand the burden, there is nothing Poetry can do here. We are using standard Python package installation, working towards being fully compliant with PEPs and set standards. My suggestion would be to utilize the environment variable or try changing your code.
