### ISSUE TITLE
Command to get currently configured package version from poetry.lock

### ISSUE THREAD

**Issue by l0b0** [python-poetry/poetry#7926]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request

As far as I can tell there is currently no easily scriptable way to get the *current* version of a package from `poetry.lock` - `poetry show PACKAGE | grep ' version .*' | cut --delimiter=: --fields=2 | cut --delimiter=' ' --fields=2` is much more complex than it should be. It would be great if something like `poetry show --version PACKAGE` did the equivalent, printing only the package version with no surrounding decoration or spaces. (Using `sed` instead of `cut` would make the command slightly shorter, but much harder to understand.)

**Comment by dimbleby** [comment]
```
poetry show PACKAGE | awk '/version/ { print $3 }'
```
would be my suggestion

I think it's unlikely that this niche requirement is going to justify changing the output of `poetry show` or adding a new parameter

**Comment by abn** [comment]
Given that there are shell tools to do the trick here and as pointed out the need is extremely niche, it does not justify the effort involved in adding the option, docs, testing and maintenance around this feature. 

Thank you for taking the time to raise the feature request.
