### ISSUE TITLE
pep-561 tests fails (missing tests/masonry/builders/fixtures/pep_561_stub_only/pkg-stubs)

### ISSUE THREAD

**Issue by mtelka** [python-poetry/poetry#7929]
- **Poetry version**: poetry_core-1.6.0
- **Python version**: 3.9.16
- **OS version and name**: OpenIndiana Hipster
- **pyproject.toml**: NA

- [x ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x ] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

Steps to reproduce:
```
$ cd /tmp
$ wget https://github.com/python-poetry/poetry-core/releases/download/1.6.0/poetry_core-1.6.0.tar.gz
$ tar xf poetry_core-1.6.0.tar.gz
$ cd poetry_core-1.6.0
$ PYTHONPATH=$(pwd)/src pytest
... snip (see below) ...
=========================== short test summary info ============================
FAILED tests/masonry/builders/test_sdist.py::test_sdist_package_pep_561_stub_only
FAILED tests/masonry/builders/test_wheel.py::test_wheel_package_pep_561_stub_only[pep_561_stub_only]
FAILED tests/masonry/builders/test_wheel.py::test_wheel_package_pep_561_stub_only[pep_561_stub_only_partial]
FAILED tests/masonry/builders/test_wheel.py::test_wheel_package_pep_561_stub_only[pep_561_stub_only_src]
FAILED tests/masonry/builders/test_wheel.py::test_wheel_package_pep_561_stub_only_partial_namespace
FAILED tests/masonry/utils/test_package_include.py::test_pep_561_stub_only_package_good_name_suffix
FAILED tests/masonry/utils/test_package_include.py::test_pep_561_stub_only_partial_namespace_package_good_name_suffix
FAILED tests/masonry/utils/test_package_include.py::test_pep_561_stub_only_package_bad_name_suffix
FAILED tests/utils/test_helpers.py::test_robust_rmtree - AttributeError: 'Moc...
$
```
(Note to myself: there should be gcc available in PATH.)

Full log:
[poetry_core.log](https://github.com/python-poetry/poetry/files/11477875/poetry_core.log)

Apparently, the root cause is missing `tests/masonry/builders/fixtures/pep_561_stub_only/pkg-stubs` in sdist.

**Comment by mtelka** [comment]
Please note that the `test_robust_rmtree` failure is not related to this issue.

**Comment by dimbleby** [comment]
https://github.com/python-poetry/poetry-core/blob/0b4c8c70fe9520874ad274a5da3759e4b371ce45/pyproject.toml#L29

so far as I can see there's no good reason to exclude `.pyi` files - the only such files in the poetry-core repository are ones in test fixtures that probably should be present in the sdist.  So probably the fix is just: don't do that.

Feel free to put together a merge request

**Comment by dimbleby** [comment]
as for the other it looks as though you want a more recent version of pytest-mock.  Again a merge request bumping the lower bound in poetry-core's pyproject.toml is surely welcome
