### ISSUE TITLE
ModuleNotFoundError: No module named 'importlib_metadata' python 3.9.x

### ISSUE THREAD

**Issue by Tradunsky** [python-poetry/poetry#7943]
- **Poetry version**: 1.4.2
- **Python version**: 3.9.0 ... 3.9.16
- **OS version and name**: macOS 13.3.1 
- **pyproject.toml**: https://gist.github.com/Tradunsky/085093eadc4f5cdcbf550e87c263639c

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
python ^3.9.0 **does support** `importlib.metadata`
```
$ python           
Python 3.9.0 (default, May 17 2023, 22:45:04) 
[Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from importlib import metadata
>>>
```
however because of the _compat.py constraint on python 3.10 poetry tries to import importlib_metadata and fails:
```
Traceback (most recent call last):
#18 0.894   File "/usr/local/bin/poetry", line 5, in <module>
#18 0.894     from poetry.console.application import main
#18 0.894   File "/usr/local/lib/python3.9/dist-packages/poetry/console/application.py", line 19, in <module>
#18 0.895     from poetry.__version__ import __version__
#18 0.895   File "/usr/local/lib/python3.9/dist-packages/poetry/__version__.py", line 5, in <module>
#18 0.895     from poetry.utils._compat import metadata
#18 0.895   File "/usr/local/lib/python3.9/dist-packages/poetry/utils/_compat.py", line 20, in <module>
#18 0.895     import importlib_metadata as metadata
#18 0.895 ModuleNotFoundError: No module named 'importlib_metadata'
```

It only happens when poetry does remove old installation:
https://github.com/python-poetry/poetry/blob/481d81dbb9f1a1546da9bc8470f64105459e3e53/pyproject.toml#L58
```
#15 0.799 Skipping virtualenv creation, as specified in config file.
#15 1.646 
#15 1.646 Package operations: 45 installs, 3 updates, 2 removals
#15 1.646 
#15 1.648   • Removing importlib-metadata (6.6.0)
#15 2.157   • Removing zipp (3.15.0)
```

Steps To Reproduce:
1. `pip uninstall importlib_metadata`. _I am not 100% sure how to trigger uninstallation of the old `importlib_metadata` in a gist project I attached, other than explicitly removing  `importlib_metadata`._
2. `poetry about`

**Comment by radoering** [comment]
> python ^3.9.0 **does support** `importlib.metadata`

Even Python 3.8 has `importlib.metadata`. However, it's too old for us. Compare

importlib_metadata | stdlib
-- | --
6.5 | 3.12
4.13 | 3.11
4.6 | 3.10
1.4 | 3.8

from https://pypi.org/project/importlib-metadata/ with Poetry's constraint:
https://github.com/python-poetry/poetry/blob/c4c857e917c863bff9e97371c7dff45b704f6140/pyproject.toml#L60

We require `importlib-metadata>=4.4`. Thus, we can't use the version from the Python 3.9 stdlib.

> It only happens when poetry does remove old installation:

I can't follow. You can't install two versions of poetry into the same environment. If you remove an old version of Poetry from Python 3.9, `importlib-metadata` may be uninstalled, but if you install poetry 1.4 afterwards, `importlib-metadata` will be installed again.

> Steps To Reproduce:
> 
>     1. pip uninstall importlib_metadata

If you uninstall some of poetry's dependencies, of course, poetry will not work anymore...

**Comment by Tradunsky** [comment]
@radoering 

Thank you for your quick reply!

>Even Python 3.8 has importlib.metadata. However, it's too old for us.

Hm.. That's a good point, I have not looked to this compatibility table. However, when I used python 3.9 one in regular commands it did work. What is the version in python 3.9 anyway? Based on the table you shared, it may be anything before 4.6, which I think would fit the poetry requirement of >=4.4.

> I can't follow.   

by `old installation` I meant `importlib_metadata` vs `importlib.metadata`, sorry for the confusion. Definitely not installing multiple versions of poetry.

> If you uninstall some of poetry's dependencies, of course, poetry will not work anymore...  

Please pay attention on:
> I am not 100% sure how to trigger uninstallation of the old importlib_metadata in a gist project I attached, other than explicitly removing importlib_metadata.

That being said, I believe poetry automatically removes importlib_metadata in my production project that is running on python 3.9, which is causing this issue. Poetry does it because of the python constraint for this importlib_metadata library is specified for python <= 3.8, which means it will remove the latest version of importlib_metadata that is compatible with poetry (>=4.4) and cause the import error. Take a look here: https://github.com/python-poetry/poetry/blob/481d81dbb9f1a1546da9bc8470f64105459e3e53/pyproject.toml#L58

Which returns us back to the question above - what's wrong with using importlib.metadata import for python3.9 if we do not know which version of importlib.metadata was ported to python3.9? If we know it is not compatible, then we might want to change the python <= 3.8 constraint to < 3.10 to align two code places together.

Thank you

**Comment by dimbleby** [comment]
you've linked to the pyproject.toml from 2019 which is completely irrelevant.

Your failing pull request confirms what radoering said: poetry really does require importlib_metadata at python 3.9.

You need to install poetry into a separate environment than the project that you are managing

please close

**Comment by Tradunsky** [comment]
I think you are right, did not notice I copied an old reference:
https://github.com/python-poetry/poetry/blob/c4c857e917c863bff9e97371c7dff45b704f6140/pyproject.toml#L60

ok, thank you folks. at least those two constraints are aligned.
