### ISSUE TITLE
--no-directory option seems not to be working

### ISSUE THREAD

**Issue by elben10** [python-poetry/poetry#7945]
- **Poetry version**: 1.4.2
- **Python version**: 3.10.8
- **OS version and name**: Linux 80afcc38dfa0 5.10.104-linuxkit
- **pyproject.toml**: https://gist.github.com/elben10/cd1d5dfc18a1ea15de2771a622219adc

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
--no-directory seems to not be working (introduced in #6845). When i run the following command it raises the following error.
`poetry install --no-root --no-directory` 
_Path /src/dummy for dummy does not exist_

As I understand it, the sole purpose of the option is to ignore directory dependencies. I have followed the example in [FAQ](https://github.com/python-poetry/poetry/blob/master/docs/faq.md#poetry-busts-my-docker-cache-because-it-requires-me-to-copy-my-source-files-in-before-installing-3rd-party-dependencies). The dockerfile is also included in the [gist](https://gist.github.com/elben10/cd1d5dfc18a1ea15de2771a622219adc#file-dockerfile)

**Comment by elben10** [comment]
It is correct that the current directory is the root, but the package is added relative to that (poetry add -e src/dummy). The reason that the current directory is the root is that it is run within a docker container

**Comment by Secrus** [comment]
Summoning @radoering @adriangb since they were the ones working on this.

**Comment by dimbleby** [comment]
you did not provide your `poetry.lock`

**Comment by elben10** [comment]
It is now included in the gist

**Comment by dimbleby** [comment]
@adriangb

**Comment by adriangb** [comment]
See https://github.com/python-poetry/poetry/pull/7923

**Comment by dimbleby** [comment]
aha.  Looks close, just wants the testcases to be fixed...?

**Comment by adriangb** [comment]
Yes, and I'm a bit tied up this week unfortunately since we *really* want to make a V2 beta release for Pydantic. Only so much OSS one can handle 😅.

**Comment by dimbleby** [comment]
maybe an unfortunate coincidence that poetry 1.5.0 is also imminent - it would be a shame to include this new function, broken on release.  I'll leave a note in the 1.5.0 tracking issue so that someone can at least make a deliberate decision.

**Comment by elben10** [comment]
Works as expected. Thanks for the quick resolution
