### ISSUE TITLE
Poetry build does’t build metadata

### ISSUE THREAD

**Issue by TaokyleYT** [python-poetry/poetry#7965]
- **Poetry version**: 1.1.13
- **Python version**: 3.10.8
- **OS version and name**: Ubuntu 20.04.2 
- **pyproject.toml**: https://gist.github.com/TaokyleYT/c4dc540759f9892a91a3a32e80ff3c1e 

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

first of all here is screenshots of the entire traceback through the -vvv:
![5F079E17-6EFC-4D2D-BCD6-2377BCA7AD33](https://github.com/python-poetry/poetry/assets/102730210/af430b42-0c6f-429a-b7ec-98be734f2715)
![B9AE5A36-B954-4BC6-B1A3-8D46874D82E4](https://github.com/python-poetry/poetry/assets/102730210/3968a273-5ee6-41b8-8774-e5feff03d317)

And also the file structure if you need them
![A9AD751E-31B5-4018-87B5-601EEF18B351](https://github.com/python-poetry/poetry/assets/102730210/ab8a7526-d9ad-456c-bc1c-52ec192b4ade)

I didn’t change my pyproject.tmol at all throughout the latest few publish in my pypi and using the build of poetry, but after the latest update it shows that the metadata cannot be found, which I think I have filled in every required informations in my pyproject.tmol

program for publish:
`rm -r dist`
`poetry update`
`poetry publish --build -vvv -u __token__ -p $PYPI_API_KEY `

anyone know what happened?

**Comment by clintonroy** [comment]
In the future, please post text logs, not images.

What does the wheel look like?

This is a very old version of poetry, you should upgrade.

**Comment by ralbertazzi** [comment]
Might be related to pypi now serving (and thus requiring) metadata: https://discuss.python.org/t/pep-658-is-now-live-on-pypi/26693

You checked "I am on the latest stable Poetry version" but you also wrote down 1.1.13. Please upgrade to 1.5.0 and report the outcome
