### ISSUE TITLE
Request: A guide to creating and discovering plugins using poetry

### ISSUE THREAD

**Issue by TerranWorks** [python-poetry/poetry#7972]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

I am trying to build a plugin architecture for my project following [this guide]() but I haven't been able to get it to work with poetry. There have been a few discussions and issues surrounding this process, but I haven't found a solid resource. This may not be the correct place to ask this, but I think creating plugins is both common enough and obscure/quirky enough that an article about how to accomplish it in poetry would be very beneficial, especially since every tutorial I can find uses setuptools.

Specifically, I'm requesting the following:
- A companion article to [this guide](https://packaging.python.org/en/latest/guides/creating-and-discovering-plugins/) for creating and discovering python plugins that uses poetry instead of setuptools

Any information is appreciated and if this topic would be more appropriate in another place then I'd be happy to move it.

**Comment by dimbleby** [comment]
please read the docs

https://python-poetry.org/docs/pyproject#plugins

please close

**Comment by TerranWorks** [comment]
I will close, but that link seems to cause a 502 bad gateway btw

**Comment by dimbleby** [comment]
the link is fine, presumably the problem is at your end

**Comment by TerranWorks** [comment]
it seems to be working now
