### ISSUE TITLE
Issue with --without flag 

### ISSUE THREAD

**Issue by gaboc623** [python-poetry/poetry#7991]
- [x ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

* the functionality for the `--without` flag for `poetry install` seems to have changed in 1.5.0 to only allow groups as the arguments passed, whereas before we could pass individual package names separated by commas to exclude from the install
* if the functionality changed, could it be added to the release notes? 
* or if this is a bug should I open a different ticket for it?
![Screenshot 2023-05-23 at 2 28 03 PM](https://github.com/python-poetry/poetry/assets/98338242/427ee1bf-b575-41e9-8b29-552310b6d049)
In the image you see here, `a3s` and `cerberuscli` are internal packages that we exclude from our Github Actions runners as they are not needed, but are no longer accepted as arguments to the `--without` flag

**Comment by gaboc623** [comment]
sounds good thanks

**Comment by dimbleby** [comment]
Yep, #7529 - which is in fact already mentioned in the release notes.
