### ISSUE TITLE
poetry 1.5.0 with python 3.11.3 cannot install pkg titlecase (amongst others).

### ISSUE THREAD

**Issue by jonathanclark** [python-poetry/poetry#7996]
- Poetry (version 1.5.0)
- Python 3.11.3
- Arch Linux 6.3.3-arch1-1
- <script src="https://gist.github.com/jonathanclark/04de7e653a8fc97c05f8ad131dbde579.js"></script>

- [x ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [ x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

Output of `poetry -vvv update`
follows below.

This first occurred when I upgraded to python 3.11.3 and poetry 1.5.0.When I tried to do `poetry update`
the errors occurred as shown.
As part of debugging I created a new environment (poetry new app),
cd'd to app, and tried poetry add titlecase - same error. In fact the problem occurs for titlecase, python-xmp-toolkit and py3exiv2. As you will see from the messages you cannot tell (or I cannot tell) which package was tripping it up, other than by trial and error.

I also installed my own venv and then installed all the packages I need using pip install - with the same python and poetry version. With pip it all worked perfectly.

I note all these packages are somewhat old and use older methods for installing. I have searched the poetry documentation and can find nothing that says e.g. only packages using x as the installation method are supported.

Grateful for any assistance.

`poetry -vvv update
Loading configuration file /home/jon/.config/pypoetry/config.toml
Using virtualenv: /home/jon/.cache/pypoetry/virtualenvs/version2a-VV99PmAr-py3.11
Updating dependencies
Resolving dependencies...
   1: fact: version2a is 0.1.0
   1: derived: version2a
   1: fact: version2a depends on py4web (>=1.20230521.2)
   1: fact: version2a depends on pytest (>=5.2)
   1: fact: version2a depends on ipython (>=8.4.0)
   1: fact: version2a depends on titlecase (>=2.4)
   1: fact: version2a depends on pyexiftool (>=0.5.5)
   1: fact: version2a depends on click (>=8.1.3)
   1: selecting version2a (0.1.0)
   1: derived: click (>=8.1.3)
   1: derived: pyexiftool (>=0.5.5)
   1: derived: titlecase (>=2.4)
   1: derived: ipython (>=8.4.0)
   1: derived: pytest (>=5.2)
   1: derived: py4web (>=1.20230521.2)
[keyring.backend] Loading KWallet
[keyring.backend] Loading SecretService
[keyring.backend] Loading Windows
[keyring.backend] Loading chainer
[keyring.backend] Loading libsecret
[keyring.backend] Loading macOS
Creating new session for pypi.org
Source (PyPI): 1 packages found for click >=8.1.3
Source (PyPI): 1 packages found for pyexiftool >=0.5.5
Source (PyPI): 1 packages found for titlecase >=2.4
Source (PyPI): 13 packages found for ipython >=8.4.0
Source (PyPI): 38 packages found for pytest >=5.2
Source (PyPI): 1 packages found for py4web >=1.20230521.2
   1: fact: click (8.1.3) depends on colorama (*)
   1: selecting click (8.1.3)
   1: derived: colorama
Source (PyPI): 43 packages found for colorama *
   1: selecting pyexiftool (0.5.5)
Source (PyPI): The cache for titlecase 2.4 is outdated. Refreshing.
Source (PyPI): Getting info for titlecase (2.4) from PyPI
Source (PyPI): No dependencies found, downloading archives
   1: Version solving took 0.456 seconds.
   1: Tried 1 solutions.

  Stack trace:

  24  ~/.local/share/pypoetry/venv/lib/python3.11/site-packages/cleo/application.py:327 in run
       325│ 
       326│             try:
     → 327│                 exit_code = self._run(io)
       328│             except BrokenPipeError:
       329│                 # If we are piped to another process, it may close early and send a

  23  ~/.local/share/pypoetry/venv/lib/python3.11/site-packages/poetry/console/application.py:190 in _run
       188│         self._load_plugins(io)
       189│ 
     → 190│         exit_code: int = super()._run(io)
       191│         return exit_code
       192│ 

  22  ~/.local/share/pypoetry/venv/lib/python3.11/site-packages/cleo/application.py:431 in _run
       429│             io.input.interactive(interactive)
       430│ 
     → 431│         exit_code = self._run_command(command, io)
       432│         self._running_command = None
       433│ 

  21  ~/.local/share/pypoetry/venv/lib/python3.11/site-packages/cleo/application.py:473 in _run_command
       471│ 
       472│         if error is not None:
     → 473│             raise error
       474│ 
       475│         return terminate_event.exit_code

  20  ~/.local/share/pypoetry/venv/lib/python3.11/site-packages/cleo/application.py:457 in _run_command
       455│ 
       456│             if command_event.command_should_run():
     → 457│                 exit_code = command.run(io)
       458│             else:
       459│                 exit_code = ConsoleCommandEvent.RETURN_CODE_DISABLED

  19  ~/.local/share/pypoetry/venv/lib/python3.11/site-packages/cleo/commands/base_command.py:119 in run
       117│         io.input.validate()
       118│ 
     → 119│         status_code = self.execute(io)
       120│ 
       121│         if status_code is None:

  18  ~/.local/share/pypoetry/venv/lib/python3.11/site-packages/cleo/commands/command.py:62 in execute
        60│ 
        61│         try:
     →  62│             return self.handle()
        63│         except KeyboardInterrupt:
        64│             return 1

  17  ~/.local/share/pypoetry/venv/lib/python3.11/site-packages/poetry/console/commands/update.py:53 in handle
        51│         self.installer.update(True)
        52│ 
     →  53│         return self.installer.run()
        54│ 

  16  ~/.local/share/pypoetry/venv/lib/python3.11/site-packages/poetry/installation/installer.py:104 in run
       102│             self.verbose(True)
       103│ 
     → 104│         return self._do_install()
       105│ 
       106│     def dry_run(self, dry_run: bool = True) -> Installer:

  15  ~/.local/share/pypoetry/venv/lib/python3.11/site-packages/poetry/installation/installer.py:241 in _do_install
       239│                 source_root=self._env.path.joinpath("src")
       240│             ):
     → 241│                 ops = solver.solve(use_latest=self._whitelist).calculate_operations()
       242│         else:
       243│             self._io.write_line("Installing dependencies from lock file")

  14  ~/.local/share/pypoetry/venv/lib/python3.11/site-packages/poetry/puzzle/solver.py:72 in solve
        70│         with self._progress(), self._provider.use_latest_for(use_latest or []):
        71│             start = time.time()
     →  72│             packages, depths = self._solve()
        73│             end = time.time()
        74│ 

  13  ~/.local/share/pypoetry/venv/lib/python3.11/site-packages/poetry/puzzle/solver.py:155 in _solve
       153│ 
       154│         try:
     → 155│             result = resolve_version(self._package, self._provider)
       156│ 
       157│             packages = result.packages

  12  ~/.local/share/pypoetry/venv/lib/python3.11/site-packages/poetry/mixology/__init__.py:18 in resolve_version
        16│     solver = VersionSolver(root, provider)
        17│ 
     →  18│     return solver.solve()
        19│ 

  11  ~/.local/share/pypoetry/venv/lib/python3.11/site-packages/poetry/mixology/version_solver.py:112 in solve
       110│             while next is not None:
       111│                 self._propagate(next)
     → 112│                 next = self._choose_package_version()
       113│ 
       114│             return self._result()

  10  ~/.local/share/pypoetry/venv/lib/python3.11/site-packages/poetry/mixology/version_solver.py:430 in _choose_package_version
       428│             package = locked
       429│ 
     → 430│         package = self._provider.complete_package(package)
       431│ 
       432│         conflict = False

   9  ~/.local/share/pypoetry/venv/lib/python3.11/site-packages/poetry/puzzle/provider.py:482 in complete_package
       480│                 dependency_package = DependencyPackage(
       481│                     dependency,
     → 482│                     self._pool.package(
       483│                         package.pretty_name,
       484│                         package.version,

   8  ~/.local/share/pypoetry/venv/lib/python3.11/site-packages/poetry/repositories/repository_pool.py:178 in package
       176│         for repo in self.repositories:
       177│             try:
     → 178│                 return repo.package(name, version, extras=extras)
       179│             except PackageNotFound:
       180│                 continue

   7  ~/.local/share/pypoetry/venv/lib/python3.11/site-packages/poetry/repositories/cached_repository.py:76 in package
        74│         extras: list[str] | None = None,
        75│     ) -> Package:
     →  76│         return self.get_release_info(canonicalize_name(name), version).to_package(
        77│             name=name, extras=extras
        78│         )

   6  ~/.local/share/pypoetry/venv/lib/python3.11/site-packages/poetry/repositories/cached_repository.py:64 in get_release_info
        62│                 level="debug",
        63│             )
     →  64│             cached = self._get_release_info(name, version)
        65│ 
        66│             self._release_cache.put(f"{name}:{version}", cached)

   5  ~/.local/share/pypoetry/venv/lib/python3.11/site-packages/poetry/repositories/pypi_repository.py:205 in _get_release_info
       203│                 return data.asdict()
       204│ 
     → 205│             info = self._get_info_from_urls(urls)
       206│ 
       207│             data.requires_dist = info.requires_dist

   4  ~/.local/share/pypoetry/venv/lib/python3.11/site-packages/poetry/repositories/http_repository.py:205 in _get_info_from_urls
       203│                 return self._get_info_from_wheel(first_wheel)
       204│ 
     → 205│         return self._get_info_from_sdist(urls["sdist"][0])
       206│ 
       207│     def _links_to_data(self, links: list[Link], data: PackageInfo) -> dict[str, Any]:

   3  ~/.local/share/pypoetry/venv/lib/python3.11/site-packages/poetry/repositories/http_repository.py:99 in _get_info_from_sdist
        97│ 
        98│         with self._cached_or_downloaded_file(Link(url)) as filepath:
     →  99│             return PackageInfo.from_sdist(filepath)
       100│ 
       101│     def _get_info_from_urls(self, urls: dict[str, list[str]]) -> PackageInfo:

   2  ~/.local/share/pypoetry/venv/lib/python3.11/site-packages/poetry/inspection/info.py:519 in from_sdist
       517│         """
       518│         if path.is_file():
     → 519│             return cls._from_sdist_file(path=path)
       520│ 
       521│         # if we get here then it is neither an sdist instance nor a file

   1  ~/.local/share/pypoetry/venv/lib/python3.11/site-packages/poetry/inspection/info.py:313 in _from_sdist_file
       311│         with temporary_directory() as tmp_str:
       312│             tmp = Path(tmp_str)
     → 313│             with context(path.as_posix()) as archive:
       314│                 archive.extractall(tmp.as_posix())
       315│ 

  ReadError

  file could not be opened successfully:
  - method gz: ReadError('not a gzip file')
  - method bz2: ReadError('not a bzip2 file')
  - method xz: ReadError('not an lzma file')
  - method tar: ReadError('invalid header')

  at /usr/lib/python3.11/tarfile.py:1639 in open
      1635│                     if fileobj is not None:
      1636│                         fileobj.seek(saved_pos)
      1637│                     continue
      1638│             error_msgs_summary = '\n'.join(error_msgs)
    → 1639│             raise ReadError(f"file could not be opened successfully:\n{error_msgs_summary}")
      1640│ 
      1641│         elif ":" in mode:
      1642│             filemode, comptype = mode.split(":", 1)
      1643│             filemode = filemode or "r"
`

**Comment by jonathanclark** [comment]
Thank you so much. That worked. I feel a bit of a fool, but I think the documentation could be clearer on this.

**Comment by dimbleby** [comment]
should be fixed by #7971 in the next release anyway, no further action needed - please close
