### ISSUE TITLE
Poetry doesn't detect PyTorch 2.0.1 dependencies correctly

### ISSUE THREAD

**Issue by Interpause** [python-poetry/poetry#8002]
- **Poetry version**: `Poetry (version 1.5.0)`
- **Python version**: `3.9.16`
- **OS version and name**: `Ubuntu 22.04 (WSL2)`
- **pyproject.toml**: https://gist.github.com/Interpause/09bc5076c2fa52e13d7baa97a512c02e

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

Poetry pulls in `nvidia-*-cu11` dependencies of `torch` when using version `2.0.0`, but not `2.0.1`. `pip` pulls in all dependencies correctly when used, so it is unlikely to be an upstream package misconfig. Below are the outputs of `pip show torch` and `poetry show torch` for both versions:

### `pip show torch`

For version 2.0.0:

```
Name: torch
Version: 2.0.0
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: /home/jh/.conda/envs/ideadino/lib/python3.9/site-packages
Requires: filelock, jinja2, networkx, nvidia-cublas-cu11, nvidia-cuda-cupti-cu11, nvidia-cuda-nvrtc-cu11, nvidia-cuda-runtime-cu11, nvidia-cudnn-cu11, nvidia-cufft-cu11, nvidia-curand-cu11, nvidia-cusolver-cu11, nvidia-cusparse-cu11, nvidia-nccl-cu11, nvidia-nvtx-cu11, sympy, triton, typing-extensions
Required-by: torchvision, triton
```

For version 2.0.1:

```
Name: torch
Version: 2.0.1
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: /home/jh/.conda/envs/til/lib/python3.9/site-packages
Requires: filelock, jinja2, networkx, nvidia-cublas-cu11, nvidia-cuda-cupti-cu11, nvidia-cuda-nvrtc-cu11, nvidia-cuda-runtime-cu11, nvidia-cudnn-cu11, nvidia-cufft-cu11, nvidia-curand-cu11, nvidia-cusolver-cu11, nvidia-cusparse-cu11, nvidia-nccl-cu11, nvidia-nvtx-cu11, sympy, triton, typing-extensions
Required-by: til-23-cv, torchvision
```

### `poetry show torch`

For version 2.0.0:

```
 name         : torch                                                                      
 version      : 2.0.0                                                                      
 description  : Tensors and Dynamic neural networks in Python with strong GPU acceleration 

dependencies
 - filelock *
 - jinja2 *
 - networkx *
 - nvidia-cublas-cu11 11.10.3.66
 - nvidia-cuda-cupti-cu11 11.7.101
 - nvidia-cuda-nvrtc-cu11 11.7.99
 - nvidia-cuda-runtime-cu11 11.7.99
 - nvidia-cudnn-cu11 8.5.0.96
 - nvidia-cufft-cu11 10.9.0.58
 - nvidia-curand-cu11 10.2.10.91
 - nvidia-cusolver-cu11 11.4.0.1
 - nvidia-cusparse-cu11 11.7.4.91
 - nvidia-nccl-cu11 2.14.3
 - nvidia-nvtx-cu11 11.7.91
 - sympy *
 - triton 2.0.0
 - typing-extensions *

required by
 - torchvision 2.0.0
 - triton 
```

For version 2.0.1:

```
 name         : torch                                                                      
 version      : 2.0.1                                                                      
 description  : Tensors and Dynamic neural networks in Python with strong GPU acceleration 

dependencies
 - filelock *
 - jinja2 *
 - networkx *
 - sympy *
 - typing-extensions *

required by
 - torchvision 2.0.1
```

**Comment by ralbertazzi** [comment]
It looks a PyTorch issue, where they uploaded wrong metadata to PyPI: https://github.com/pytorch/pytorch/issues/100974. Until they solve it, my suggestion is to use url dependencies (https://github.com/python-poetry/poetry/issues/6409 for reference). If you agree, please close the issue.

**Comment by dimbleby** [comment]
(as previously disccused in #7902, which this duplicates)

**Comment by Interpause** [comment]
Huh, weird I did not find #7902. Okay, closing.
