### ISSUE TITLE
Support for desktop entries in build

### ISSUE THREAD

**Issue by ferreteleco** [python-poetry/poetry#8007]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request

Hi, I'm currently undergoing the development of a python GUI application thal I want delivered in the form of an installable wheel file. SO far so good, poetry solves a lot of my problems and I am able to generate such wheel. The catch is that I'd want to be able to launch the application directly from Ubuntu desktop by typing its name and without the need of a console. I thought of doing so by generating an app.desktop entry and having the generated wheel to place it in ~/.local/share/applications and I was not able so far. Do you think this may be achievable?

One approach I thought about is enabling the possibility of running a post-build script during pip installation of the wheel package, but I do not know if it's possible or if it's the best way of doing it.

Thanks in advance.

**Comment by ferreteleco** [comment]
Is it possible to build a .deb file with poetry?

**Comment by dimbleby** [comment]
no

**Comment by ferreteleco** [comment]
Thanks anyway.
