### ISSUE TITLE
Allow execution of pre/post build scripts

### ISSUE THREAD

**Issue by ferreteleco** [python-poetry/poetry#8008]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request

While I'm aware of the (undocummented) possibility of overriding the generated setup.py used to build a project, I think that it could be interesting if poetry allows to define pre or post build scripts and execute them before / after the execution of the auto generated setup.py. Most evident use case would be to generate some metadata (such as project version in a readme, destkop entry file or __init__.py) dynamically each time a poetry build command is issued.

**Comment by dimbleby** [comment]
poetry is building standard wheels, the thing you are asking for does not exist
