### ISSUE TITLE
poetry publish - Can't have direct dependency

### ISSUE THREAD

**Issue by localagi** [python-poetry/poetry#8019]
- **Poetry version**: 1.5.0
- **Python version**: 3.10
- **OS version and name**: ubuntu jammy
- **pyproject.toml**: https://github.com/localagi/AGiXT/blob/f4f1b761c188cbd0a7a1f5eb4b46d3c736a2664d/pyproject.toml

- [ x ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [ x ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

references I searched:
https://github.com/pypa/pip/issues/6301
https://github.com/python-poetry/poetry/issues/4471
https://github.com/python-poetry/poetry/issues/2828

- [ x ] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

So.. I do understand the handling of pypi here, but the issue is elsewhere:

`poetry add https://github.com/xtekky/gpt4free.git#e35264d`
works and results in 
`gpt4free = { git = "https://github.com/xtekky/gpt4free.git", rev = "e35264d" }`
which is correct
but on 
`poetry publish`
ERROR `Error: Can't have direct dependency: 'gpt4free @ git+https://github.com/xtekky/gpt4free.git@e35264d'`

**Reason: DO NOT **`@`** but DO `#` (according to pypi docs)**

Seems like an error in generation of the URL
Where is this in the source so i can fix it?

**Comment by dimbleby** [comment]
`@` is correct, please close

**Comment by localagi** [comment]
> `@` is correct, please close

Why does it fail on publish then? It seems to be correct for a tag or a branch.

**Comment by localagi** [comment]
See also https://peps.python.org/pep-0440/#direct-references
