### ISSUE TITLE
Poetry 1.5.0 updates urllib3 to v2.0.2 and breaks!

### ISSUE THREAD

**Issue by ialvata** [python-poetry/poetry#8025]
If I move back the urllib3 version to the original 1.x, then poetry is no longer broken...
![Screenshot from 2023-05-28 10-57-02](https://github.com/python-poetry/poetry/assets/110241614/efc84c68-a2fe-462d-bd7b-34426aac739e)

**Comment by dimbleby** [comment]
duplicate #7936, not a poetry bug, please close

**Comment by ialvata** [comment]
@dimbleby Not sure exactly... The package gets updated by poetry itself. I'm not the one that chose to update that package. I didn't mess anything in the venv.
It's Poetry that messes it up, by itself...

**Comment by dimbleby** [comment]
No, the error is yours.  You should not install poetry in the same environment as the project under management.  Please follow poetry installation documentation - and close this issue.

**Comment by ialvata** [comment]
I'm closing this issue then...
I would just like to point out that the simplest solution to several issues I previously had with poetry and virtual environments versions was to install poetry inside them... When I raised this issue in several forums, I would always get instructed that poetry shouldn't be used as venv manager, just a package manager.

I think, as a user, this course of action will  just making the adoption of poetry for certain projects harder.

**Comment by dimbleby** [comment]
whether you use poetry to manage your virtual environments is completely unrelated to this issue and error.  Feel free to install poetry correctly and then not use it to manage virtual environments (actually that's how I use it myself).
