### ISSUE TITLE
Poetry-core backend not using private repositories when building with pip

### ISSUE THREAD

**Issue by AdamWRichardson** [python-poetry/poetry#8048]
- **Poetry version**: 1.5.1
- **Python version**: 3.10.7
- **OS version and name**: WSL ubuntu-22.10
- **pyproject.toml**: <https://gist.github.com/AdamWRichardson/b3c3ebc64bd23e3aedabcc9511d36303>

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
When using PEP 517 frontend tool (pip) to build/install a poetry managed project which has a dependency in a private repository you get the error:
```
Could not find a version that satisfies the requirement private_dependency ... (from versions: none)
```
This may be by design but it would be good to have a work around if this is the case.

Output of `pip install -vvv .`:
```
Processing /home/arichardson/experiments/pypi-demo
  Added file:///home/arichardson/experiments/pypi-demo to build tracker '/tmp/pip-build-tracker-thhq6eik'
  Created temporary directory: /tmp/pip-build-env-y8sesycl
  Installing build dependencies: started
  Running command pip subprocess to install build dependencies
  Using pip 23.1.2 from /home/arichardson/experiments/pypi-demo/.venv/lib/python3.10/site-packages/pip (python 3.10)
  Collecting poetry-core
    Using cached poetry_core-1.6.1-py3-none-any.whl (450 kB)
  Installing collected packages: poetry-core
  Successfully installed poetry-core-1.6.1
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Running command Getting requirements to build wheel
  Getting requirements to build wheel: finished with status 'done'
  Created temporary directory: /tmp/pip-modern-metadata-opcafhpi
  Preparing metadata (pyproject.toml): started
  Running command Preparing metadata (pyproject.toml)
  Preparing metadata (pyproject.toml): finished with status 'done'
  Source in /home/arichardson/experiments/pypi-demo has version 0.1.0, which satisfies requirement pypi-demo==0.1.0 from file:///home/arichardson/experiments/pypi-demo
  Removed pypi-demo==0.1.0 from file:///home/arichardson/experiments/pypi-demo from build tracker '/tmp/pip-build-tracker-thhq6eik'
...
1 location(s) to search for versions of private_dependency:
* https://pypi.org/simple/private_dependency/
Fetching project page and analyzing links: https://pypi.org/simple/private_dependency/
Getting page https://pypi.org/simple/private_dependency/
Found index url https://pypi.org/simple/
Looking up "https://pypi.org/simple/private_dependency/" in the cache
Request header has "max_age" as 0, cache bypassed
https://pypi.org:443 "GET /simple/private_dependency/ HTTP/1.1" 404 13
Status code 404 not in (200, 203, 300, 301, 308)
Could not fetch URL https://pypi.org/simple/private_dependency/: 404 Client Error: Not Found for url: https://pypi.org/simple/private_dependency/ - skipping
Skipping link: not a file: https://pypi.org/simple/private_dependency/
Given no hashes to check 0 links for project 'private_dependency': discarding no candidates

**Comment by dimbleby** [comment]
This has nothing to do with poetry.  You need to tell pip about the private repository.

**Comment by AdamWRichardson** [comment]
Since `poetry-core` has all the information about the private repository available to it (specified in `poetry config` and added in both `pyproject.toml` and `poetry.lock`) shouldn't it use this information in it's backend, even if that means just passing that information on to pip?

**Comment by dimbleby** [comment]
The API between the front-end and back-end is limited.

What you are doing is roughly equivalent to building and publishing a wheel for your project, and then `pip install` that wheel.  Perhaps that makes it more obvious to you that what you are asking for just doesn't work: wheels have no place for information about private repositories.

If you want to make use of poetry front-end features - then use poetry as your front-end, and not pip.

**Comment by AdamWRichardson** [comment]
That make a lot of sense thank you! 
This causes headaches for us because we're using tox (sorry, I know) and using PEP 517 for that which then hits this issue (it's the same issue). Therefore using [usecase-1](https://python-poetry.org/docs/faq/#usecase-1) from the FAQs will not work with private repos (without setting those up with repos with pip)

**Comment by dimbleby** [comment]
Correct.  Please close.
