### ISSUE TITLE
When package has no constraints, Poetry assumes "^latest"

### ISSUE THREAD

**Issue by spencerwilson** [python-poetry/poetry#8052]
- **Poetry version**: 1.5.1
- **Python version**: 3.11.3
- **OS version and name**: macOS 13.0.1
- **pyproject.toml**: https://gist.github.com/spencerwilson/8a4e71d107520ed503574c3160ffbb7d

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
When running `poetry add snowflake-connector-python` I expected Poetry to add the latest version of the package for which there is a viable release on PyPI. This is what pip does:

```
% pip install snowflake-connector-python
Collecting snowflake-connector-python
  Downloading snowflake_connector_python-3.0.3-cp311-cp311-macosx_11_0_arm64.whl (13.7 MB)
```

In contrast,
```
% poetry -vvv add snowflake-connector-python
Using virtualenv: /Users/spencer/Library/Caches/pypoetry/virtualenvs/abc-z643ngl0-py3.11
[keyring.backend] Loading KWallet
[keyring.backend] Loading SecretService
[keyring.backend] Loading Windows
[keyring.backend] Loading chainer
[keyring.backend] Loading libsecret
[keyring.backend] Loading macOS
Creating new session for pypi.org
Source (PyPI): 119 packages found for snowflake-connector-python *
Using version ^3.0.4 for snowflake-connector-python
...
```

How'd it decide to use ^3.0.4 and not ^3.0.3 (which would have installed successfully)? Is this expected?

context: I was among those affected by https://github.com/snowflakedb/snowflake-connector-python/issues/1584, where this behavior of poetry resulted in some surprises.

**Comment by dimbleby** [comment]
duplicate #707, please close
