### ISSUE TITLE
version parsing error

### ISSUE THREAD

**Issue by hawktang** [python-poetry/poetry#8053]
The current project's Python requirement (>=3.11,<4.0) is not compatible with some of the required packages Python requirement:
  - qdrant-client requires Python >=3.7,<3.12, so it will not be satisfied for Python >=3.12,<4.0

Because no versions of qdrant-client match >1.2.0,<2.0.0
 and qdrant-client (1.2.0) requires Python >=3.7,<3.12, qdrant-client is forbidden.
So, because llama depends on qdrant-client (^1.2.0), version solving failed.

  • Check your dependencies Python requirement: The Python requirement can be specified via the `python` or `markers` properties

    For qdrant-client, a possible solution would be to set the `python` property to ">=3.11,<3.12"

    https://python-poetry.org/docs/dependency-specification/#python-restricted-dependencies,
    https://python-poetry.org/docs/dependency-specification/#using-environment-markers

- **1.51**: 
- **3.11.3**: 
- **Mac OS 13.3**: 
- **pyproject.toml**: 

- [Y ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [ ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

**Comment by dimbleby** [comment]
There is no version parsing error.  re the error that you are actually seeing: please respect the checklist in the issue, it is there to help avoid wasting everyone's time.  In particuar, see the faq.

Please close.
