### ISSUE TITLE
ModuleNotFoundError when installing a module with 

### ISSUE THREAD

**Issue by bennetrr** [python-poetry/poetry#8057]
- **Poetry version**: 1.5.1 (installed via script)
- **Python version**: 3.11.3
- **OS version and name**: macOS 13.4
- **pyproject.toml**: see below
- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.

### Steps to Reproduce

1. Create the folder structure:

```text
.
└── src
    ├── api
    |   ├── README.md
    │   └── src
    │       └── example
    │           ├── __init__.py
    │           └── api
    │               └── __init__.py
    └── core
        ├── README.md
        └── src
            └── example
                ├── __init__.py
                └── core
                    └── __init__.py
```

2. Run `poetry init` both in `./src/api` and `./src/core`.
3. In each of the `pyproject.toml` files remove the line that starts with `packages =` and add

```
[[tool.poetry.packages]]
include = "test"
from = "src"
```

4. Go into the `./src/api` directory and run `poetry update && poetry install`
5. Go into the `./src/core` directory and run `poetry add -e ../api && poetry update && poetry install`
6. Run `poetry run python` and in the interactive shell, `import example.api` to see, if the module was linked correctly
7. Then, in the same shell, do `import example.core`

### Expected Result (at least for me)

The import should work

### Actual Result

I get a `ModuleNotFoundError`

---

Is this normal (and if yes, why?), or is this an issue with my setup, poetry or python itself? Is it possible, that the `example.api` package, that I have installed in developer mode overwrites the `example.core` package?

<details><summary>

`pyproject.toml`'s 

</summary>

`./src/api/pyproject.toml`:

```
[tool.poetry]
name = "example-api"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[[tool.poetry.packages]]
include = "example"
from = "src"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

`./src/core/pyproject.toml`:

```
[tool.poetry]
name = "example-core"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[[tool.poetry.packages]]
include = "example"
from = "src"

[tool.poetry.dependencies]
python = "^3.11"
example-api = {path = "../api", develop = true}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

</details>

**Comment by dimbleby** [comment]
you are providing `example/__init__.py` twice.  This is nothing to do with poetry, you probably want to go and read about namespace packages.

please close

**Comment by bennetrr** [comment]
Didn't know that, thanks for the hint!
