### ISSUE TITLE
Add an option do disable "External virtual environment management"

### ISSUE THREAD

**Issue by eldargab** [python-poetry/poetry#8069]
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request

I tried to use poetry in the following manner:

* A conda environment provides `python` and `poetry` itself
* The rest is business as usual with local, per-project virtual environments

However, the above flow is not possible, because `poetry` detects the environment it is running in as an already created target environment and simply breaks it during `poetry install`. That's despite `virtualenvs.in-project` is set to `true`.

It would be nice to have an option to disable such behaviour.

**Comment by dimbleby** [comment]
duplicate #4055, #4622, please close
