### ISSUE TITLE
.venv folder disappears

### ISSUE THREAD

**Issue by xareelee** [python-poetry/poetry#8071]
- **Poetry version**: 1.5.1 
- **Python version**: 3.11.3
- **OS version and name**: macOS 13.4
- **pyproject.toml**: https://gist.github.com/xareelee/de5863a7b61ab2faff0d9f59bb1eb508
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

After update poetry from `1.4.2` to `1.5.1` a few days ago, now I find that `.venv` folder disappears after removing the project's `.venv/` and `poetry install` again. 

After a little searching, I try this:

```shell
$ poetry config --list
cache-dir = "/Users/xaree/Library/Caches/pypoetry"
experimental.system-git-client = false
installer.max-workers = null
installer.modern-installation = true
installer.no-binary = null
installer.parallel = true
virtualenvs.create = true
virtualenvs.in-project = null
virtualenvs.options.always-copy = false
virtualenvs.options.no-pip = false
virtualenvs.options.no-setuptools = false
virtualenvs.options.system-site-packages = false
virtualenvs.path = "{cache-dir}/virtualenvs"  # /Users/xaree/Library/Caches/pypoetry/virtualenvs
virtualenvs.prefer-active-python = false
virtualenvs.prompt = "{project_name}-py{python_version}"
```

and then I run this:

```shell
$ poetry config virtualenvs.in-project true
```

The `poetry install` still does not build the `.venv` folder.

**Comment by dimbleby** [comment]
works fine here.   suggest clearing your poetry cache and trying again

**Comment by xareelee** [comment]
I've just tried `poetry cache clear pypi --all`, and it still does not work.

**Comment by dimbleby** [comment]
remove the whole directory

**Comment by xareelee** [comment]
@dimbleby Thanks, it works. 

I run this to find out the cache directory:

```
$ poetry shell
Spawning shell within /Users/xaree/Library/Caches/pypoetry/virtualenvs/py-sec-edgar-el5O7TXB-py3.11
```

After I remove the `pypoetry/` folder from `~/Library/Caches` (`/Users/xaree/Library/Caches` in my case), I run `poetry install` again and the `.venv` folder is built.
