### ISSUE TITLE
System Python Used to Install Poetry Mistaken as a Venv

### ISSUE THREAD

**Issue by ginty** [python-poetry/poetry#8072]
- **Poetry version**: 1.5.1, 1.4.2, probably others (at least 1.1.7 does not have this problem)
- **Python version**: 3.9.5
- **OS version and name**: RHEL7

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

I've installed latest Poetry using this command:

```text
curl -sSL https://install.python-poetry.org | POETRY_HOME=/etc/poetry python3 -
```

For some reason it seems to interpret my system Python installation as a venv and there is nothing I can do to unset it:

```text
-bash-4.2$ poetry env info

Virtualenv
Python:         3.9.5
Implementation: CPython
Path:           /usr/local
Executable:     /usr/local/bin/python3.9
Valid:          True

System
Platform:   linux
OS:         posix
Python:     3.9.5
Path:       /usr/local/.package/python-3.9.5
Executable: /usr/local/.package/python-3.9.5/bin/python3.9
```
`/usr/local/bin/python3.9` is a symlink to `/usr/local/.package/python-3.9.5/bin/python3.9` on my system.

This results in `poetry install` etc. trying to install to the system environment where I have no write permission.

This behavior is also very confusing because `poetry env list` does not list any venvs available for a given app.

I have been able to work around by manually creating a venv and setting `VIRTUAL_ENV`, then Poetry will use it as normal, otherwise all other configuration switches, e.g. `virtualenvs.in-project` are ignored.

**Comment by dimbleby** [comment]
suggest providing a docker-ised reproduction

- if you succeed, that'll give others the opportunity to investigate what you are seeing
- just as likely, you will find it difficult to reproduce; and then that gives you the opportunity to figure out what's different about your computer

**Comment by abn** [comment]
Closing as we do not have sufficient information to reproduce the issue. If the issue persists with the latest poetry versions, please raise a new issue with a reproducer and additional information.

Thank you for taking the time to raise this issue.
