### ISSUE TITLE
Add support for project-specific "default"/"self" configuration

### ISSUE THREAD

**Issue by BEllis** [python-poetry/poetry#8083]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request

As a developer, I am wanting to have some poetry plugins loaded only for certain projects I have on my development machine and may also want to change other poetry settings between projects (i.e. do or don't create virtual environments).

I propose that poetry will look for a `.poetry` directory in the current working directory, if present, it will use this over the default system config location. I'd expect `POETRY_CONFIG_PATH` env var to take precedence over the `.poetry`

It could be initialized by running a new `init` self command, something like

```
poetry self init
```

Running this command would create a `.poetry` directory in the current working directory and generate the necessary default files (`config.toml`, `pyproject.toml`, `poetry.lock`)

This would enable me as a developer to do the following,

```
poetry self init
poetry self add my-poetry-plugin
```

and by including the `.poetry` directory in git, it would mean the dependency/usage of a poetry plugin would be automatically picked up by other developers (though they would probably still need to run `poetry self install`, not sure if this can happen implicitly elsewhere TBD)

**Comment by Secrus** [comment]
You can have per-project config just by using `poetry.toml` file. As to per-project plugins (and dev tools), we have #5740, which I am going to be working on after finishing #5509.

**Comment by BEllis** [comment]
The project-level `pyproject.toml` / `poetry.toml` isn't currently used by `self` commands as far as I can see?

This feature request is slightly more abstract that #5740 

Although the main benefit I want is fulfilled by #5740 this feature feels useful also?

I've raised a draft PR which appears to be working and doing what I've described above.

**Comment by Secrus** [comment]
The PR you prepared is not viable. `self` namespace is meant as a way to manage the installation of Poetry on your system, not for any kind of per-project commands.

**Comment by Secrus** [comment]
After discussion, core maintainers decided that this request will be rejected.
