### ISSUE TITLE
bug?: Unexpectedly convert entry points in scripts configurations to lowercase

### ISSUE THREAD

**Issue by Wansn-w** [python-poetry/poetry#8085]
- **Poetry version**: ` v1.5.1 `  // update: still the case in version 1.5.1
- **Python version**: ` Python3.10.6 `
- **OS version and name**: ` Ubuntu 22.04 `
- **pyproject.toml**: [pyproject.toml](https://gist.github.com/Wansn-w/c90aa47bd1e2df556b64e0c50ff7b494)

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [ x I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

When the package at the entry point in scripts is named CamelCase, poetry will converts it to lowercase without prompting.

![15c80691ffa2661b1e516d6187b1262e](https://github.com/python-poetry/poetry/assets/49867372/94a6b400-3ec0-444b-b996-310ffde07836)
![cfc2a87f74b2f213c16af18c7037fe9c](https://github.com/python-poetry/poetry/assets/49867372/bd736232-077b-4774-8142-dc68530ef78b)

**Comment by nlarusstone** [comment]
@Wansn-w I think I'm encountering this -- how did you end up solving this?

**Comment by Wansn-w** [comment]
> @Wansn-w I think I'm encountering this -- how did you end up solving this?

finally I converted package name to snake-case with all lowercase 😂
