### ISSUE TITLE
Issue when including a dependencies few extras as optional and other few as required dependency

### ISSUE THREAD

**Issue by arun-k-bharathan** [python-poetry/poetry#8095]
- **Poetry version**: 1.5.1
- **Python version**: 3.11.3
- **OS version and name**: Manjaro Linux 23.0.0
- **pyproject.toml**: https://github.com/arun-k-bharathan/poetry_issue_test/blob/main/pyproject.toml

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

Hi, in my project i have a dependency on [ibis-framework](https://github.com/ibis-project/ibis) which has several optional dependencies 
like `postgres, duckdb, trino, mysql`, installing optional dependency `postgres` requires libpq-dev to be already present otherwise pip install fails.

To avoid that i tried making `postgres` extra alone as optional in my project, i followed [this #5733](https://github.com/python-poetry/poetry/issues/5733#issuecomment-1151481078) which is similar to my case and there it is mentioned it works, and [this](https://github.com/arun-k-bharathan/poetry_issue_test/blob/main/pyproject.toml) is my projects pyproject.toml, were i made `duckdb` required dependency and `postgres` as optional

I created a virtual environment, this is the pip list 

pip==23.1.2,
setuptools==67.7.2,
wheel==0.40.0 

I tried to install above project in github using this command ```pip install 'poetry-issue-test @ git+https://github.com/arun-k-bharathan/poetry_issue_test.git'```

my expectation was it should install ibis-framework without postgres optional dependency.
But it did not install ibis-framework at all, this is the pip list

certifi==2023.5.7,
charset-normalizer==3.1.0,
idna==3.4,
pip==23.1.2,
poetry-issue-test==0.1.6,
requests==2.31.0,
setuptools==67.7.2,
urllib3==2.0.3,
wheel==0.40.0  

But if I install using ```pip install 'poetry-issue-test[postgres] @ git+https://github.com/arun-k-bharathan/poetry_issue_test.git'```

this will install all dependencies of ibis-framework including `postgres` and `duckdb` extras. I tried even installing from pypi and local file with pip, that too results in same outcome.

i am using python 3.11.3 and poetry 1.5.1.

What change should i make in pyproject.toml to make `ibis-framework[duckdb]` required and `ibis-framework[postgres]` optional.

**Comment by dimbleby** [comment]
Duplicate #834, #3913, #5733, #6053, #7738, #7911
