### ISSUE TITLE
System config for tool.poetry.source

### ISSUE THREAD

**Issue by julienmariethoz** [python-poetry/poetry#8099]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request
Quite a lot of parameters can be set with env variables. It would be beneficial to have the _tool.poetry.source_ configurable system-wide to avoid having to re-configure the artifactory URL on every project.

[https://python-poetry.org/docs/dependency-specification/#source-dependencies](https://python-poetry.org/docs/dependency-specification/#source-dependencies)

[[tool.poetry.source]]
name = "foo"
url = "https://foo.bar/simple/"
priority = "supplemental"

Many Thx

**Comment by dimbleby** [comment]
duplicate #5958
