### ISSUE TITLE
Explicit priority for source doesn't work with sub-dependencies that also have explicit priority for the same source

### ISSUE THREAD

**Issue by pszpetkowski** [python-poetry/poetry#8102]
- **Poetry version**: 1.5.1
- **Python version**: 3.11.3
- **OS version and name**: Fedora 38
- **pyproject.toml**: https://github.com/pszpetkowski/poetry-bug-example

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
Explicit priority for source is a great idea but so far it seems to only be useful when a dependency doesn't have any dependencies that are stored in a private source itself. I've stumbled upon a problem where I have an application, let's call it `foo_app` and it depends on the `foo` package which in turn depends on the `foo_base` package. All of the `foo_*` dependencies are stored on the private PyPI server and it seemed like a great and clean idea to utilize the `explicit` priority to tell Poetry where to look. It worked for the `foo` package, because `foo_base` doesn't have any dependencies in a private source, however if `explicit` source is used for `foo` dependency in `foo_app` I'm getting the following error when trying to generate a lockfile with `poetry lock`:
```
Because foo (0.1.0) depends on foo_base (0.1.0) which doesn't match any versions, foo is forbidden.
So, because foo-app depends on foo (0.1.0), version solving failed.
```

To make it more visual the relationship basically looks like this:
```
foo_app ---------> (depends on) foo ---------> (depends on) foo_base
```

I've saved a debug output and upload as a gist at https://gist.github.com/pszpetkowski/614605f50ba2483e14ef69c49b15ef17

Above, for the pyproject.toml, I've provided a link to [the repository](https://github.com/pszpetkowski/poetry-bug-example) that contains a minimal sample that showcases the issue. Hopefully it's enough to understand the issue, but if you need more information I'll be happy to provide it.

**Comment by radoering** [comment]
That's expected behavior. See [Package Source Constraint](https://python-poetry.org/docs/repositories/#package-source-constraint), especially the second info box starting with _"Package source keys are not inherited by their dependencies."_

Dependencies of a package that comes from source A, do not have to come from source A, too.
