### ISSUE TITLE
`pipx install poetry` gives missing symlink error

### ISSUE THREAD

**Issue by startakovsky** [python-poetry/poetry#8104]
- **Poetry version**: 1.51
- **Python version**: I used 3.11.3 to install 
- **OS version and name**:macOS 13.3.1
- **pyproject.toml**: Nothing

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

I did `pipx install poetry` and then `pipx list` and have this output, please note that `poetry` is the only package in red and it says a symlink is missing. This is the bug. What does it mean? 

```zsh
➜  code pipx list
venvs are in /Users/steven/.local/pipx/venvs
apps are exposed on your $PATH at /Users/steven/.local/bin
   package hatch 1.7.0, installed using Python 3.11.3
    - hatch
   package jupyter-repo2docker 2023.6.0, installed using Python 3.11.3
    - jupyter-repo2docker
    - repo2docker
   package pipenv 2023.6.2, installed using Python 3.11.3
    - pipenv
    - pipenv-resolver
   package poetry 1.5.1, installed using Python 3.11.3
    - **poetry** (symlink missing or pointing to unexpected location)
```

**Comment by Secrus** [comment]
Seems like an issue with `pipx` or your machine, not Poetry itself. Poetry is distributed the same way as any Python package is, so there should be no problem with installing it via `pipx`. (I am using `pipx` myself and it works fine for me)
