### ISSUE TITLE
Different platform dependencies not resolved correctly

### ISSUE THREAD

**Issue by hendrikbl** [python-poetry/poetry#8127]
- **Poetry version**: 1.5.1
- **Python version**: 3.10.12
- **OS version and name**: Debian 12 in Docker
- **pyproject.toml**: https://gist.github.com/hendrikbl/769d3fe738f019bb567dcfe5b770e0d8

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

When looking through the issues here I found similar issues but nothing describing my specific problem.
Since we can't build `python-ldap` for windows on every developers machine, we just built it once and referenced it as a `path` dependency.
When building the docker image for production, we use the official `python:3.10-slim` image, which is a Debian base image.
So I added a pypi version of the dependency and used the `platform` option to let poetry select the correct one in each use case.

Thats where things go wrong. Poetry always selects the `path` dependency wether or not I'm in my Debian Docker container or on my windows machine.

Here's the related output of `poetry lock -vvv`:
```
#15 3.286    0: Duplicate dependencies for python-ldap
#15 3.287    0: Different requirements found for python-ldap (3.4.0) with markers sys_platform == "win32" and python-ldap (3.4.0) with markers sys_platform == "linux".
#15 3.288    1: Version solving took 0.140 seconds.
#15 3.288    1: Tried 1 solutions.
#15 3.289    0: Retrying dependency resolution with the following overrides ({Package('ldap-test', '2023.6.0'): {'python-ldap': <FileDependency python-ldap (3.4.0) @ file:///opt/ldap-test/contrib/python_ldap-3.4.0-cp310-cp310-win_amd64.whl>}}).
```

Am I missing something here?

**Comment by finswimmer** [comment]
> Am I missing something here?

Poetry locks the dependencies independently of the current platform and python version. It produces a universal lock file for the whole range of supported python versions. 

`poetry install` will than decide based on the lock file, which packages are actually installed on the current system.

**Comment by hendrikbl** [comment]
Ahh I see, that makes a lot more sense actually :D

I can see now `poetry install -vvv` tells me if it installs from path or not.

Thanks a lot!
