### ISSUE TITLE
Export of requirements.txt places extra index url before index url that let pip install fail

### ISSUE THREAD

**Issue by christianknoepfle** [python-poetry/poetry#8129]
- **Poetry version**: 1.5.1
- **Python version**: 3.10
- **OS version and name**: Windows 10, Ubuntu 20.04

We use the `export` command to create a requirements.txt, then pip install into a specific folder (to create an aws lambda zip)
```
poetry export --without-hashes -f requirements.txt --output requirements.txt
poetry run pip install -r requirements.txt -t tmp_deployment/
```

We use *two* repositories (default + supplemental) and recently the pip install step fails (randomly), because the export creates a requirements file where the `--extra-index-url` entry precedes the ` --index-url` entry. So the file looks like this
```
--extra-index-url https://foo.de/artifactory/api/pypi/enya-pypi-prod-local/simple
--index-url https://foo.de/artifactory/api/pypi/pypi-remote/simple
... (all the packages)
```
Due to the pip bug https://github.com/pypa/pip/issues/11511 this won't work. pip will only look at the index-url and not at the extra-index-url. So to make this work one has to manually flip those two lines (as a workaround we added do `poetry export --without-hashes -f requirements.txt | sort -r > requirements.txt`). 

I have not seen this with poetry 1.4.x and it just randomly appeared with 1.5.x.

It would be good if poetry exports the index-url as first line 

(it is a pip bug in the first place and I could agree on not fixing this in poetry. So in case someone runs into the same problem, the reason and workaround can be found in this ticket)

Here is the toml:
```
[tool.poetry]
name = "fubar"
version = "0.5.31"
description = ""
packages = [
    {include = "pydap", from = "function"},
    {include = "*.py", from = "function"},
]

[[tool.poetry.source]]
name = "artifactory-pypi"
url = "https://foo.de/artifactory/api/pypi/pypi-remote/simple"
priority = "default"

[[tool.poetry.source]]
name = "mysource"
url = "https://foo.de/artifactory/api/pypi/enya-pypi-prod-local/simple/"
priority = "supplemental"

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
requests = "^2.25.1"
boto3 = "^1.17.96"
mypackage = {version = "^2.3.23", source = "mysource"}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

Thanks and all the best

Christian

**Comment by dimbleby** [comment]
wrong repository, and duplicate https://github.com/python-poetry/poetry-plugin-export/issues/149

(you should have read that pip issue more carefully!)

**Comment by christianknoepfle** [comment]
thanks for your feedback, haven't seen this, sorry for that. I will close this one since the issue is tracked in https://github.com/python-poetry/poetry-plugin-export/issues/149
