### ISSUE TITLE
"file could not be opened successfully" when trying to install knockapi with poetry

### ISSUE THREAD

**Issue by will-afs** [python-poetry/poetry#8133]
- **Poetry version**: Poetry (version 1.5.0)
- **Python version**: Python 3.11.3
- **OS version and name**: Ubuntu 22.04
- **pyproject.toml**: confidential

- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
When executing: `poetry add knockapi`

I'm obtaining:
```bash
Using version ^0.5.2 for knockapi

Updating dependencies
Resolving dependencies... (0.5s)

file could not be opened successfully:
- method gz: ReadError('not a gzip file')
- method bz2: ReadError('not a bzip2 file')
- method xz: ReadError('not an lzma file')
- method tar: ReadError('invalid header')
```

More details (-vvv execution of the command above) can be found in this file (some content had to be masked (*****) or omitted due to confidential reasons): [poetry_add_knock_api_vvv_output.log](https://github.com/python-poetry/poetry/files/11868661/poetry_add_knock_api_vvv_output.log)

I've tried to delete the cache with `poetry cache clear pypi --all`,  as suggested in [this other issue](https://github.com/python-poetry/poetry/issues/7996), without any success.

**Comment by dimbleby** [comment]
That other issue does not suggest the command you identified, it suggests that you clear your cache.  Delete the whole cache directory, if what you've done is not enough.

duplicate #7996, please close.

**Comment by will-afs** [comment]
Fixed by running the following commands:

`poetry cache list`

And for each cache element of this list, running:

`poetry cache clear <cache> --all`
