### ISSUE TITLE
Poetry env use changes poetry install behaviour

### ISSUE THREAD

**Issue by classiqRoi** [python-poetry/poetry#8134]
- **Poetry version**:1.5.1
- **Python version**: 3.8
- **OS version and name**: Ubuntu22.04
- **pyproject.toml**: 

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

Hi all. I have a rather complicated dependency system, and in my CI I'm required to run poetry and install some project while in another virtual environment. I'm using the `setup-python` action, which when used with poetry caching, calls `poetry env use $(which python)` for every package - to make sure the environment uses the correct python version.
When this is called on the package I want to install, poetry doesn't install the package on the current virtual environment but on the original one.
 My way around it is to use `poetry env use system` for the installed package, but it seems very weird that this behavior would occur and that this would change poetry behavior.
Step to reproduce:
```bash
cd path/to/project
poetry -C path/to/common_tests env use $(which python) #common_tests is the installed projects name
poetry install

# Try to install another project in the current virtual environment:
poetry run poetry install -vvv -C path/to/other/project
#Output:
#Installing the current project: common-tests (0.0.0)
#  - Building package common-tests in editable mode
#  - Adding common_tests.pth to /root/.cache/pypoetry/virtualenvs/common-tests-iBz2cdqa-py3.8/lib/python3.8/site-packages for ../python_libs/common_tests
#  - Adding the common_tests-0.0.0.dist-info directory to /root/.cache/pypoetry/virtualenvs/common-tests-iBz2cdqa-py3.8/lib/python3.8/site-packages
poetry run pip show common_tests # FAILS
```
I think the expected behaviour for that case is that the second project would be installed on the original virtual environment.

Thanks!

**Comment by dimbleby** [comment]
`poetry run poetry install -C /other/project` just seems like a bad idea: you are trying simultaneously to run an outer poetry command in one project and an inner poetry command in another, and then complaining when it is confusing.

I don't really follow what it is you are trying to do, but I suspect it is likely that the right answer is: "don't do that"!

**Comment by classiqRoi** [comment]
I agree it is a weird usage - I want to install another project which is not a dependency according to the pyproject.toml in my active project. I would probably not do it that way, but that's not my choice. (It's because one project is uploaded to pypi and being used, and the other is a dependency just for the tests, and is internal). 
If you have a better idea on how to achieve that I would love to hear.

**Comment by classiqRoi** [comment]
And I don'dt undetstand why the usage `poetry env use $(which python)` (in the dependency) will change somehow the way poetry installs something to the virtual environment.

**Comment by dimbleby** [comment]
if you want to install a package but it's not managed by poetry: then don't try to use poetry to install it.  `pip install` exists and is still useful.

please close

**Comment by classiqRoi** [comment]
Closing, thanks.
