### ISSUE TITLE
Poetry not using the right Python version (pyenv)

### ISSUE THREAD

**Issue by sumeeterito** [python-poetry/poetry#8141]
- **Poetry version**: 1.5.1
- **Python version**: 3.7.16
- **OS version and name**: Mac OS Ventura

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

This solution does not work for me. I am on poetry 1.5.1 and when i run

```
pyenv shell 3.7.16
poetry env use $(pyenv which python)
poetry install
poetry add scikit-learn
```

I get

```
Error: 'numpy' must be installed before running the build.

  at ~/Library/Application Support/pypoetry/venv/lib/python3.8/site-packages/poetry/installation/chef.py
```

you can see that the poetry environment is referencing a python 3.8.

even `poetry run python --version` yields 3.7.16; but still it references python 3.8

**Comment by dimbleby** [comment]
what you are seeing is that poetry itself was installed in a python 3.8 environment, this is separate from the environment under management.  

there is no bug here, please close
