### ISSUE TITLE
A SOCIAL MEDIA TEAM?

### ISSUE THREAD

**Issue by meltingturret** [python-poetry/poetry#8144]
LOVE poetry great project! But in the latest version what is going on with all these warnings about something that might happen in the future? 

Please disable. Use breaking changes in your release notes instead.

**Comment by Secrus** [comment]
No. Our experience with end users is that people don't read changelogs and rely on versions like they are semver [which Poetry does not adhere to](https://python-poetry.org/docs/faq/#why-does-poetry-not-adhere-to-semantic-versioning).
