### ISSUE TITLE
Ignore package with local version label with legacy repository

### ISSUE THREAD

**Issue by Mindstan** [python-poetry/poetry#8148]
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request

I'm trying to add a package (namely `torch`) with a `legacy` source with Poetry 1.5.1. On the webpage, the package is listed first as `x.y.z+foo` (with `x`, `y`, and `z` some numbers) for some architectures, then `x.y.z` for all architectures. To maximize the compatibility, I strictly want the version `x.y.z` (without the local version). I tried to put the following values in the field `version` :

- `x.y.z` and `==x.y.z`: Poetry selects `x.y.z+foo` because it appears first in the page;
- `==x.y.z, !=x.y.z+foo` and `>=x.y.z, <x.y.z+foo` : Poetry prints the following error

    > Because myproject depends on mydependency (==x.y.z, !=x.y.z+foo) which doesn't match any versions, version solving failed.

[Local version label in PEP-440](https://peps.python.org/pep-0440/#local-version-identifiers) is explicitly discouraged for public indexes when indicating API abilities, but this is how it is used in PyTorch public indexes.

**Comment by dimbleby** [comment]
duplicate #7256 among others, please close
