### ISSUE TITLE
Inconsistent behavior between `poetry lock` and `poetry lock --no-update`

### ISSUE THREAD

**Issue by Mindstan** [python-poetry/poetry#8149]
- **Poetry version**: 1.5.1
- **Python version**: 3.9.13
- **OS version and name**: Ubuntu 22.04
- **pyproject.toml**: https://gist.github.com/Mindstan/b88e841baf56e82548c206a7835faa43

- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

When having multiple versions of the same package using environmental markers, Poetry may select 2 different versions with the command `poetry lock` and remove one of them with `poetry lock --no-update`.

In the joined gist, `poetry lock` will select `torch==2.0.1+cpu` on Linux and `torch==2.0.1` for other platforms. If running `poetry lock --no-update` on a Linux host, it will remove `torch==2.0.1`. Running then `poetry lock` re-adds this version to the lock file.

**Comment by dimbleby** [comment]
both are legitimate solutions to the constraints you've given: and neither is what you actually want.  So while this is a bit of an oddity it's probably not very interesting!

what you likely intended was to specify `source = "PyPI"` on the not-linux dependencies, forcing poetry not to re-use the `+cpu` versions on those platforms.

**Comment by Mindstan** [comment]
Thanks for the quick answer!
Adding `source="PyPI"` does the trick, but I don't really see is why `poetry lock --no-update` removes the version if the source is not specified.

**Comment by dimbleby** [comment]
without the specific requirement that the non-linux versions come from PyPI, the `+cpu` versions from the torch source can be used to satisfy either of the constraints that you provided.  

As I say, I agree that it's an oddity that you can make this toggle in and out by re-locking: I just doubt that this is what you (or anyone else) really cares about

**Comment by Mindstan** [comment]
We are storing our `poetry.lock` in our Git repository to have the exact same environment between our development, testing, and sometimes production systems, that have different architectures.
I think the main issue here is the PyTorch team forcing everyone using Linux on x86 to install CUDA by default and optionally providing CPU-only optimised releases for computers not equipped with neither Nvidia nor AMD GPU.
As a temporary solution, we uploaded the wheels after removing the `+cpu` on our self-hosted PyPI, set as explicit source.
Thanks for the explanation!
