### ISSUE TITLE
Attempting to add repo shows filenotfound error on poetry 1.0.0a2

### ISSUE THREAD

**Issue by ghost** [python-poetry/poetry#815]
- [ ] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Linux Mint 19.1
- **Poetry version**: 1.0.0a2
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**:  https://gist.github.com/ManchurianSector/8834b95944c6671c4a8cc50b1a359afb

## Issue

attempting to run the following: poetry config repositories.testpypi https://test.pypi.org/legacy/

results in this: 

[FileNotFoundError]
[Errno 2] No such file or directory: '/home/findingnemo/.config/pypoetry/config.toml'

**Comment by ManchurianSector** [comment]
From further checking and previous experiences, i think this can be attributed to the fact that the base folder of the file $HOME/.config/pypoetry doesnt exist as yet, and must be created before opening the file can be attempted

**Comment by ManchurianSector** [comment]
Confirmed, creating the folder beforehand solves this issue. Now its just a matter of updating the code to create the folder if it doesnt exist

**Comment by finswimmer** [comment]
I guess this problem is fixed within the last year. :smiley: 

So I will close it.
