### ISSUE TITLE
Add `poetry cache clear-all`

### ISSUE THREAD

**Issue by simonrouse9461** [python-poetry/poetry#8156]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

### Problem
Currently, the only way to clear all cache is to list all caches with `poetry cache list` first, then do `poetry cache clear <cache> --all` for each cache. There is no convenient way to clear all caches directly. 
### Solution
Please support `poetry cache clear-all` subcommand to clear all poetry caches with a single command. This is especially useful for building docker images.

**Comment by Secrus** [comment]
You can use `poetry cache clear --all .` to do exactly that.

**Comment by simonrouse9461** [comment]
@Secrus Thanks for the information! Is this documented? I can't find this in the [doc](https://python-poetry.org/docs/cli/#cache-clear). It will be very helpful to write this in the doc.
