### ISSUE TITLE
Suddenly require Rust and Cargo installed?

### ISSUE THREAD

**Issue by oc-ben-ellis** [python-poetry/poetry#8160]
- **Poetry version**: 1.5.1
- **Python version**: 3.11.4
- **OS version and name**: WSL2.0 on Windows 11 running Ubuntu
- **pyproject.toml**: Not relevant.

- [*] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [*] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [*] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [*] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
Recently we've been getting the below error in our CI environments. It appears there is now a requirement for rust and cargo to be installed in order to run poetry on alpine linux? 

To reproduce,

`docker run -it --rm alpine:latest /bin/sh -c "apk add python3 py3-pip && pip install poetry"`

We get this error,

```
Collecting rpds-py>=0.7.1 (from jsonschema<5.0.0,>=4.10.0->poetry)
  Downloading rpds_py-0.8.4.tar.gz (15 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]

      Cargo, the Rust package manager, is not installed or is not on PATH.
      This package requires Rust and Cargo to compile extensions. Install it through
      the system's package manager or via https://rustup.rs/

      Checking for Rust toolchain....
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Workaround is to install rust and cargo,

`docker run -it --rm alpine:latest /bin/sh -c "apk add rust cargo python3 py3-pip && pip install poetry"`

Installs succesfully.

**Comment by oc-ben-ellis** [comment]
I suspect the issue isn't with poetry itself as I've been using the same version without issue for the last few weeks. I suspect some dependency has been release and upgraded?

**Comment by error0x001** [comment]
plus one, the same error

**Comment by oc-ben-ellis** [comment]
I should probably mention I noticed that rpds-py has a release earlier this morning BUT this was AFTER we were experiencing problems so I don't think it's that particular dependency causing issues but whatever is using it.

**Comment by oc-ben-ellis** [comment]
https://github.com/python-jsonschema/jsonschema/releases/tag/v4.18.0

This is the offender I think. I'll raise an issue there also.

**Comment by Secrus** [comment]
The dependency chain here is: `jsonschema -> referencing -> rpds-py`. `rpds-py` doesn't provide wheels for musllinux, which seems to be the core issue.

**Comment by Freakazoid182** [comment]
`jsonschema` added `rpds-py` 3 hours ago as a new dependency (4.18.0)

**Comment by oc-ben-ellis** [comment]
This comment from jsonschema guys,

```
There's a (indeed intentional) dependency on rust for building from source, and no current MUSL wheels yet. The latter is tracked at https://github.com/crate-py/rpds/issues/6 and just requires some understanding of what to tweak in maturin which hasn't been figured out yet. Help certainly welcome.
```

**Comment by Secrus** [comment]
Yeah, I have created #8161, we will stay on <4.18 until the issue with MUSL is resolved.

**Comment by Secrus** [comment]
Well, it seems the issue was resolved, Alpine is usable again.

**Comment by oc-ben-ellis** [comment]
I'm getting this error now instead? I noticed the version has gone up to 0.8.8.

Package operations: 7 installs, 6 updates, 0 removals

  • Installing rpds-py (0.8.8): Failed

  PermissionError

  [Errno 13] Permission denied: '/usr/local/lib/python3.10/site-packages/rpds_py-0.8.8.dist-info'

**Comment by radoering** [comment]
So we don't need #8161 anymore?
