### ISSUE TITLE
Pre-commit hook [poetry-export] skips because poetry.lock is in subdirectory

### ISSUE THREAD

**Issue by omar-araboghli** [python-poetry/poetry#8162]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request

The title is descriptive enough to understand the issue. This has been solved for `poetry-check` hook with #7239 and its [PR-7242](https://github.com/python-poetry/poetry/pull/7242/files). 

I assume the solution is very similar to the above mentioned issue and could look like:

````yaml
files: ^(.*/)?poetry.lock$
````

**Comment by bentocin** [comment]
I am currently preparing a PR to address handling of monorepo setups or if `pyproject.toml` files live in sub directories.

@python-poetry/triage

**Comment by bentocin** [comment]
@python-poetry/triage
