### ISSUE TITLE
'Table' object has no attribute 'decode' error after upgrading

### ISSUE THREAD

**Issue by rich9474** [python-poetry/poetry#8167]
- **Poetry version**: 1.5.1
- **Python version**: 3.9.13
- **OS version and name**: Rocky Linux 8.7
- **pyproject.toml**: NA

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
After installing v1.5.1 using the official installer method:
`curl -sSL https://install.python-poetry.org | python3.9 -`  I could no longer run any poetry commands like `poetry config --list`.  I would just get the error:
```
 master(+255/-192)* 14s ± poetry config --list

'Table' object has no attribute 'decode'
```
After purging all poetry related files from the system and re-installing it cleared the error.  I suspect the culprit was incompatible settings in one of:
```
/data/home/rhall/.config/pypoetry
/data/home/rhall/.config/pypoetry/config.toml
```
Sorry,  I don't have the contents of the files and I didn't run with -vvv as I only came to report the issue after fixing it.

I was upgrading from 1.2.  It seems that there was no conversion or validation of the config files on upgrading.

**Comment by dimbleby** [comment]
unactionable, might as well close it

**Comment by gouzmi** [comment]
In my case the file *.config/pypoetry/config.toml* was misformatted. 
Try to fix it or leave it empty.

Example of one: 

`
[virtualenvs]
in-project = true
`
