### ISSUE TITLE
Supporting Git LFS for publishing to PyPI

### ISSUE THREAD

**Issue by gustavwilliam** [python-poetry/poetry#8168]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request

I just finished a project that relies on [Git LFS](https://git-lfs.com) (Large File Storage) to store a pretty large file (more than 100MB) that the project needs to run properly. Git LFS basically creates a pointer to the large file instead of storing the large file itself.

Would it be possible to support Git LFS when publishing to PyPI? It would probably require some extra code to make sure the user is publishing the file that's a pointer to the resource, rather than the massive resource itself, and some logic to make sure the file is pulled when the repo is pip installed.

I'm quite new to using Git LFS and publishing to PyPI, so I don't know for sure if it's possible or realistic to do this, but regardless, it's a feature I'd love to see!

**Comment by Secrus** [comment]
I have consulted with the PyPI team, and what you describe is not possible with PyPI overall, so there is no chance for implementation here.
