### ISSUE TITLE
Config virtualenvs.in-project does not working

### ISSUE THREAD

**Issue by MishaVyb** [python-poetry/poetry#8172]
- **Poetry version**: version 1.5.1 
- **Python version**: 3.11.3 
- **OS version and name**: MacBook Pro Apple M1 / macOS Monterey 12.3.1 (21E258 
- **pyproject.toml**: [here](https://gist.github.com/MishaVyb/16b9f89e7bf51df34e33b6c50677ab86) (but it's almost initital, i've just add one dependencie)

- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
Hello everyone! I'm trying to install environment in project root, but it cannot be done. Below I'll try describe all my steps.

### My Steps.

- First of all, I've been trying to set the config option.
```sh
$ poetry config virtualenvs.in-project true -vvv
Loading configuration file /Users/vybornyy/Library/Application Support/pypoetry/config.toml
Loading configuration file /Users/vybornyy/dev/lern-poetry/poetry.toml
```
- Then check it. But It's still `false` 😞

```sh
$ poetry config --list
cache-dir = "/Users/vybornyy/Library/Caches/pypoetry"
experimental.system-git-client = false
installer.max-workers = null
installer.modern-installation = true
installer.no-binary = null
installer.parallel = true
virtualenvs.create = true
virtualenvs.in-project = false  # HERE
virtualenvs.options.always-copy = false
virtualenvs.options.no-pip = false
virtualenvs.options.no-setuptools = false
virtualenvs.options.system-site-packages = false
virtualenvs.path = "{cache-dir}/virtualenvs"  # /Users/vybornyy/Library/Caches/pypoetry/virtualenvs
virtualenvs.prefer-active-python = false
virtualenvs.prompt = "{project_name}-py{python_version}"
```

- Ok. Then I open config file in editor: `/Users/vybornyy/Library/Application Support/pypoetry/config.toml`
```toml
[virtualenvs]
in-project = true
```

And here it's marked as `true`. A little bit strange. 

- Also, to be sure, I've repeat all these steps for `--local` configuration. And the same behaviour.
```sh
$ poetry config virtualenvs.in-project true --local -vvv
Loading configuration file /Users/vybornyy/Library/Application Support/pypoetry/config.toml
Loading configuration file /Users/vybornyy/dev/lern-poetry/poetry.toml
```

```sh
poetry config --list --local
cache-dir = "/Users/vybornyy/Library/Caches/pypoetry"
experimental.system-git-client = false
installer.max-workers = null
installer.modern-installation = true
installer.no-binary = null
installer.parallel = true
virtualenvs.create = true
virtualenvs.in-project = false  # HERE
virtualenvs.options.always-copy = false
virtualenvs.options.no-pip = false
virtualenvs.options.no-setuptools = false
virtualenvs.options.system-site-packages = false
virtualenvs.path = "{cache-dir}/virtualenvs"  # /Users/vybornyy/Library/Caches/pypoetry/virtualenvs
virtualenvs.prefer-active-python = false
virtualenvs.prompt = "{project_name}-py{python_version}"
```

- in local config file it's marked as `true`: `/Users/vybornyy/dev/lern-poetry/poetry.toml`

```toml
[virtualenvs]
in-project = true
```

### Finally.

In spite of that strange behaviour, I've tryed use env and install packages, whatever. And I'm expecting, it will be `in-project`.

- check current state

```sh
$ poetry env info -vvv
Loading configuration file /Users/vybornyy/Library/Application Support/pypoetry/config.toml
Loading configuration file /Users/vybornyy/dev/lern-poetry/poetry.toml

Virtualenv
Python:         3.11.3
Implementation: CPython
Path:           NA
Executable:     NA

System
Platform:   darwin
OS:         posix
Python:     3.11.3
Path:       /usr/local/Cellar/poetry/1.5.1/libexec
Executable: /usr/local/Cellar/poetry/1.5.1/libexec/bin/python3.11
```

- create env 
> I expecting it will be created locally, but it's not 😢

```sh
$ poetry env use python3.11 -vv
vCreating virtualenv lern-poetry-mxIB-NH7-py3.11 in /Users/vybornyy/Library/Caches/pypoetry/virtualenvs
Using virtualenv: /Users/vybornyy/Library/Caches/pypoetry/virtualenvs/lern-poetry-mxIB-NH7-py3.11
```

Is it a bug or I did something wrong?

> P.S. I've tryed the same steps for another options (for examply I was changing `virtualenvs.options.no-pip` option), and it works as expected. The problem is only with `virtualenvs.in-project` option.

**Comment by MishaVyb** [comment]
The problem is gone after macOS restart...

**Comment by n8sty** [comment]
Please close assuming this is no longer an issue
