### ISSUE TITLE
How can I make sure `poetry` is using the latest `pyproject.toml`?

### ISSUE THREAD

**Issue by alexhallam** [python-poetry/poetry#8174]
- **Poetry version**: 1.5.1
- **Python version**:3.11
- **OS version and name**: Debian 12 Bookworm
- **pyproject.toml**: [https://github.com/alexhallam/tablespoon/blob/main/pyproject.toml](https://github.com/alexhallam/tablespoon/blob/main/pyproject.toml)

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.

## Issue

I want to change a function in my package and compare what I want to implement with the current version.

Before I dive in and make changes I wanted to make sure the poetry was picking up on my current environment.

To do this I just updated the version number of my package https://github.com/alexhallam/tablespoon/blob/4985cd56a11f82d096b81704d1faa266c53fffec/pyproject.toml#L26 to `0.5.0`

I then did

```
poetry shell
python scratch.py
```

All that is in `scratch.py` is

```py
import tablespoon as tbsp
print(tbsp.__version__)
```

The output was `0.4.7`. I was expecting `0.5.0`

# Try 1

I then decided to clear the cache. So I `exit` the poetry shell an run.

```py
poetry cache clear --all .
poety shell
python scratch.py
```

I got `0.4.7` again.

# Try 2

I then notice that when `poetry shell` is run it give this message

```
Spawning shell within /home/user/.cache/pypoetry/virtualenvs/tablespoon-mAcvscks-py3.11
```

So I run 

```
rm -rf /home/user/.cache/pypoetry/virtualenvs/*
poetry shell
poetry install
python scratch.py
```

I get `0.4.7` still! I was expecting `0.5.0`

# Try 3

```
# still in poetry shell
poetry update
poetry install
python scratch.py
```

Just to verify I ran `pip list` to make sure I did not have `tablespoon` installed locally. It was clean. I am not sure how to tell poetry to stop using `0.4.7`.

---------

How can I make sure `poetry` is using the latest `pyproject.toml`? I do not feel like I can move on with testing if I can't get it to print the correct version number.

**Comment by dimbleby** [comment]
you seem to have forgotten how you own code works

https://github.com/alexhallam/tablespoon/blob/4985cd56a11f82d096b81704d1faa266c53fffec/tablespoon/__init__.py#L1C1-L1C1

**Comment by alexhallam** [comment]
:face_with_head_bandage: ouch. Thanks!
