### ISSUE TITLE
Poetry does not correctly parse platform_release marker

### ISSUE THREAD

**Issue by antoinea-cnty** [python-poetry/poetry#8175]
- **Poetry version**: 1.5.1
- **Python version**: 3.9.1
- **OS version and name**:  Ubuntu 20.04.1

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

Trying any operation with this :
```
torchvision = [
    {version = "^0.15.2+cpu", markers = "platform_release != '5.19.0-1025'"}
]
```
in the `pyprojet.toml`, results in a `Could not parse version constraint: 5.15.0-76-generic` error.

The issue seem to be triggered by the "-gerneric" part of the string. As putting any platform release with anything else than a version number seems to trigger the issue.

At the best of my knowledge this is a [PEP 508](https://peps.python.org/pep-0508/#environment-markers) compliant string for platform_release and should be accepted by Poetry.

**Comment by dimbleby** [comment]
duplicate #7418
