### ISSUE TITLE
Poetry fails when runs pre-commit hooks in windows-2022 [GitHub Actions]

### ISSUE THREAD

**Issue by irux** [python-poetry/poetry#8180]
- **Poetry version**:  1.5.1
- **Python version**:  3.10 
- **OS version and name**: windows-2022 
- **pyproject.toml**:  https://github.com/bakdata/kpops/blob/8ac927c12123bc0395cb4881643f78a1f8e951c3/pyproject.toml

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.

## Issue

Poetry fails when runs pre-commit hooks in GitHub Windows Actions when the poetry version is 1.5.1. This doesn't happen in lower minor versions. Here you can see an example of the error: https://github.com/bakdata/kpops/actions/runs/5517162002/jobs/10059409230

**Comment by Secrus** [comment]
How did you pinpoint the poetry to be at fault? From the log you linked, I would say that pre-commit or virtualenv are more likely to be at fault, since the error origins from subprocess.

**Comment by irux** [comment]
> How did you pinpoint the poetry to be at fault? From the log you linked, I would say that pre-commit or virtualenv are more likely to be at fault, since the error origins from subprocess.

@Secrus thank you for your response. The reason to think about it (maybe it is wrong) was to see that this error doesn't happen when the version is lower than 1.5.1. But you have a good point, maybe (and high probably) it is a pre-commit problem. I will open an issue there :)

**Comment by Secrus** [comment]
Since you didn't come back to the issue, I assume it was resolved. If it still exists, please open a new report.
