### ISSUE TITLE
PEP440: Local version prioritised against public version

### ISSUE THREAD

**Issue by gianfa** [python-poetry/poetry#8181]
- **Poetry version**: 1.3, 1.4, 1.5
- **Python version**: 3.9, 3.10
- **OS version and name**: macos 12.6, ubuntu 22.05

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
I am experiencing something completely unexpected. 

I make use of a private repository, nexus, where the build packages I develop are uploaded, including the ones from features branches. 
When I launch the installation of a alpha version package via poetry, the [local version](https://peps.python.org/pep-0440/#local-version-identifiers) has higher priority than a [pre release public version](https://peps.python.org/pep-0440/#public-version-identifiers).

In order to reproduce the behavior: 
1. you must have a repository, in which to have published the builds two versions of the same package. In my case:
* `test_repo_for_cicd-0.1.0a2-py3-none-any.whl` (public version, alpha pre-release)
* `test_repo_for_cicd-0.1.0a2+todelete.mpkt-py3-none-any.whl` (local version, alpha pre-release)
2. from a new folder, create a convenience project
```bash
cd myprojdir
poetry init \
    --name="todelete2" \
    --author="gianfa <my.email@server.com>" \
    --python=">=3.9,<3.11" \
    --quiet
```
3. Do a simple install of the package, in alpha version
```bash
poetry shell
poetry lock

poetry add test_repo_for_cicd==0.1.0a2
```

Here is an example of the output I get
<img width="659" alt="Schermata 2023-07-11 alle 12 04 55" src="https://github.com/python-poetry/poetry/assets/25075574/e0db3cee-78fb-4abc-b85d-f04fef2c49fc">

Another thing I notice is that it keeps looping to request only `test_repo_for_cicd-0.1.0a2+todelete.mpkt`, when in fact there are other local `a2` versions in the nexus repository.

It looks like is violating Pep440, which states that the local version should be ignored except when fully explicit 
This causes me some serious inconsistencies in my workflow, but I would like to understand if I am doing something wrong on my side.
Please help me to understand.

Thank you very much for your great work

**Comment by dimbleby** [comment]
>  Pep440, which states that the local version should be ignored except when fully explicit

please provide a reference to the section that says this.

what I see is

> local version labels MUST be ignored entirely when checking if candidate versions match a given version specifier.

which is what poetry is doing: `0.1.0a2+todelete.mpkt1` matches the version specifier `==0.1.0a2`, after entirely ignoring the local version label.

You might be looking for #7256

**Comment by gianfa** [comment]
thank you @dimbleby,
Below you'll find the reference.

> If the specified version identifier is a public version identifier (no local version label), then the local version label of any candidate versions MUST be ignored when matching versions.
[Version Matching, PEP440](https://peps.python.org/pep-0440/#:~:text=If%20the%20specified%20version%20identifier%20is%20a%20public%20version%20identifier%20(no%20local%20version%20label)%2C%20then%20the%20local%20version%20label%20of%20any%20candidate%20versions%20MUST%20be%20ignored%20when%20matching%20versions.)

Here follows my reasoning, please tell me if I'm misunderstanding:
1. `0.1.0a2` is a [public version](https://peps.python.org/pep-0440/#public-version-identifiers).
2. `0.1.0a2+todelete.mpkt` is a [local version](https://peps.python.org/pep-0440/#local-version-identifiers).
3. during a `==0.1.0a2` any other candidates `0.1.0a2+<candidate piece>` MUST be ignored.

**Comment by dimbleby** [comment]
You are misreading the specification.  It doesn't say that "local versions" must be ignored.  It says that during matching, local version labels must be ignored.

So - at risk of repeating myself - that's exactly what poetry is doing.  The local version label on `0.1.0a2+todelete.mpkt1` is ignored, leaving `0.1.0a2`, and that is a match for the version specifier `0.1.0a2`.

**Comment by gianfa** [comment]
OK, thank you very much for the further clarification.

So if I understand correctly, in the case of pre-release comparison all versions of the same prerelease, e.g. `a1`, compete equally during a matching on `==`, i.e. none has priority, or am I missing something?

So in the case of development where 1.0 is not yet available as a public version, but there are several local versions of the same alpha, say `1.0.0a3`, which one will be chosen by `==1.0a3`?

**Comment by dimbleby** [comment]
PEP440 describes comparison rules for local labels.  Poetry may or may not have implemented them, I wouldn't like to rely on it either way: I guess that the "biggest" local version label will win, according to whatever poetry actually has implemented.

Please close

**Comment by gianfa** [comment]
why should I close?
**Poetry keeps looping the search endlessly without ever choosing a single version** . Isn't this a bug?


As for your point of view, thank you again. Then as far as I understand from your reply it is simply a literal interpretation of PEP440 that turns out to be ambiguous and the Poetry team decided by design to proceed in this way. So at most the sorting between public and local prerelease would not be a bug but if I understand you correctly more of a missing feature, which I could propose eventually.

Please bear with me as I am concerned about the sorting between public and local prerelease, from a code integration point of view.
I ask again for suggestions or help to understand better.
Let me explain the situation: my type of development makes extensive use of the _develop_ branch as a branch on which to integrate all the code coming from the feature branches that has happened and then after careful validation we proceed to bring up on main. The _develop_ branch is therefore the pre-release point of truth for anyone testing my applications.
In this scenario as you see it is not possible to gain advantage by using matching like you describe, as it is ambiguous between what comes from the _develop_ branch (being prerelease) and what comes from the feature branches children of _develop_ (local on prerelease homonymous) please explain to me how I could work effectively in this scenario using poetry. 
I don't think I'm the only one to integrate the code this way, but maybe I am misinterpreting something again.

**Comment by gianfa** [comment]
OK, I am closing this issue. I would have appreciated some more reference on the correct use of local labels and I think it would have helped to bring clarity to the topic.
