### ISSUE TITLE
Poetry add grpcio not working on Mac

### ISSUE THREAD

**Issue by TimCapes** [python-poetry/poetry#8183]
- **Poetry version**: 1.5.1
- **Python version**: Tested on 3.9.16 and 3.11.3
- **OS version and name**: macOS Ventura 13.4.1
- **pyproject.toml**:  https://gist.github.com/TimCapes/92cb076b0eb9259d5c8e344058840566

- [x ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [ x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
Poetry fails to install grpcio despite pip being able to install grpcio in both regular and --no-binary modes.
The commands poetry add grpcio and poetry add grpcio~=1.44.0 both fail with a FileNotFoundError
I'm not sure whats happening but the HTTP request appears to 200 and then the filelock appears to fail. My internet connection is working, reliable and fast so I don't think that this is caused by any type of connection issue.

I have used brew to install openssl3.

poetry add -vvv grpcio   
Loading configuration file /Users/tcapes/Library/Application Support/pypoetry/config.toml
Loading configuration file /Users/tcapes/git_repos/grpc-demo/poetry.toml
Trying to detect current active python executable as specified in the config.
Unable to detect the current active python executable. Falling back to default.
Using virtualenv: /Users/tcapes/git_repos/grpc-demo/.venv
[keyring.backend] Loading KWallet
[keyring.backend] Loading SecretService
[keyring.backend] Loading Windows
[keyring.backend] Loading chainer
[keyring.backend] Loading libsecret
[keyring.backend] Loading macOS
Creating new session for pypi.org
[urllib3.connectionpool] Starting new HTTPS connection (1): pypi.org:443
[urllib3.connectionpool] https://pypi.org:443 "GET /simple/grpcio/ HTTP/1.1" 200 618930
[filelock] Attempting to acquire lock 4335247568 on /Users/tcapes/devdisk/.cache/poetry/cache/repositories/PyPI/_http/5/a/0/e/8/5a0e822c64c6d1f33f153767105760052e23ef8293f8ec21cf53e92b.lock
Retrying HTTP request in 0.5 seconds.
[urllib3.connectionpool] Resetting dropped connection: pypi.org
[urllib3.connectionpool] https://pypi.org:443 "GET /simple/grpcio/ HTTP/1.1" 200 618930
[filelock] Attempting to acquire lock 4349515024 on /Users/tcapes/devdisk/.cache/poetry/cache/repositories/PyPI/_http/5/a/0/e/8/5a0e822c64c6d1f33f153767105760052e23ef8293f8ec21cf53e92b.lock
Retrying HTTP request in 1.0 seconds.
[urllib3.connectionpool] Resetting dropped connection: pypi.org
[urllib3.connectionpool] https://pypi.org:443 "GET /simple/grpcio/ HTTP/1.1" 200 618930
[filelock] Attempting to acquire lock 4349432336 on /Users/tcapes/devdisk/.cache/poetry/cache/repositories/PyPI/_http/5/a/0/e/8/5a0e822c64c6d1f33f153767105760052e23ef8293f8ec21cf53e92b.lock
Retrying HTTP request in 1.5 seconds.
[urllib3.connectionpool] Resetting dropped connection: pypi.org
[urllib3.connectionpool] https://pypi.org:443 "GET /simple/grpcio/ HTTP/1.1" 200 618930
[filelock] Attempting to acquire lock 4349563920 on /Users/tcapes/devdisk/.cache/poetry/cache/repositories/PyPI/_http/5/a/0/e/8/5a0e822c64c6d1f33f153767105760052e23ef8293f8ec21cf53e92b.lock
Retrying HTTP request in 2.0 seconds.
[urllib3.connectionpool] Resetting dropped connection: pypi.org
[urllib3.connectionpool] https://pypi.org:443 "GET /simple/grpcio/ HTTP/1.1" 200 618930
[filelock] Attempting to acquire lock 4349572432 on /Users/tcapes/devdisk/.cache/poetry/cache/repositories/PyPI/_http/5/a/0/e/8/5a0e822c64c6d1f33f153767105760052e23ef8293f8ec21cf53e92b.lock
Retrying HTTP request in 2.5 seconds.
[urllib3.connectionpool] Resetting dropped connection: pypi.org
[urllib3.connectionpool] https://pypi.org:443 "GET /simple/grpcio/ HTTP/1.1" 200 618930
[filelock] Attempting to acquire lock 4349596496 on /Users/tcapes/devdisk/.cache/poetry/cache/repositories/PyPI/_http/5/a/0/e/8/5a0e822c64c6d1f33f153767105760052e23ef8293f8ec21cf53e92b.lock

  Stack trace:

  12  /opt/homebrew/lib/python3.11/site-packages/urllib3/response.py:444 in _error_catcher
       442│         try:
       443│             try:
     → 444│                 yield
       445│ 
       446│             except SocketTimeout:

  11  /opt/homebrew/lib/python3.11/site-packages/urllib3/response.py:567 in read
       565│ 
       566│         with self._error_catcher():
     → 567│             data = self._fp_read(amt) if not fp_closed else b""
       568│             if amt is None:
       569│                 flush_decoder = True

  10  /opt/homebrew/lib/python3.11/site-packages/urllib3/response.py:533 in _fp_read
       531│         else:
       532│             # StringIO doesn't like amt=None
     → 533│             return self._fp.read(amt) if amt is not None else self._fp.read()
       534│ 
       535│     def read(self, amt=None, decode_content=None, cache_content=False):

   9  /opt/homebrew/lib/python3.11/site-packages/cachecontrol/filewrapper.py:96 in read
        94│             self.__buf.write(data)
        95│         if self.__is_fp_closed():
     →  96│             self._close()
        97│ 
        98│         return data

   8  /opt/homebrew/lib/python3.11/site-packages/cachecontrol/filewrapper.py:76 in _close
        74│                     mmap.mmap(self.__buf.fileno(), 0, access=mmap.ACCESS_READ)
        75│                 )
     →  76│             self.__callback(result)
        77│ 
        78│         # We assign this to None here, because otherwise we can get into

   7  /opt/homebrew/lib/python3.11/site-packages/cachecontrol/controller.py:363 in cache_response
       361│             logger.debug("etag object cached for {0} seconds".format(expires_time))
       362│             logger.debug("Caching due to etag")
     → 363│             self._cache_set(cache_url, request, response, body, expires_time)
       364│ 
       365│         # Add to the cache any permanent redirects. We do this before looking

   6  /opt/homebrew/lib/python3.11/site-packages/cachecontrol/controller.py:282 in _cache_set
       280│                 self.cache.set_body(cache_url, body)
       281│         else:
     → 282│             self.cache.set(
       283│                 cache_url,
       284│                 self.serializer.dumps(request, response, body),

   5  /opt/homebrew/lib/python3.11/site-packages/cachecontrol/caches/file_cache.py:124 in set
       122│     def set(self, key, value, expires=None):
       123│         name = self._fn(key)
     → 124│         self._write(name, value)
       125│ 
       126│     def _write(self, path, data: bytes):

   4  /opt/homebrew/lib/python3.11/site-packages/cachecontrol/caches/file_cache.py:136 in _write
       134│             pass
       135│ 
     → 136│         with self.lock_class(path) as lock:
       137│             # Write our actual file
       138│             with _secure_open_write(lock.path, self.filemode) as fh:

   3  /opt/homebrew/lib/python3.11/site-packages/lockfile/__init__.py:197 in __enter__
       195│         Context manager support.
       196│         """
     → 197│         self.acquire()
       198│         return self
       199│ 

   2  /opt/homebrew/lib/python3.11/site-packages/poetry/utils/authenticator.py:54 in acquire
        52│ 
        53│     def acquire(self, timeout: float | None = None) -> None:
     →  54│         self.file_lock.acquire(timeout=timeout)
        55│ 
        56│     def release(self) -> None:

   1  /opt/homebrew/lib/python3.11/site-packages/filelock/_api.py:213 in acquire
       211│                 if not self.is_locked:
       212│                     _LOGGER.debug("Attempting to acquire lock %s on %s", lock_id, lock_filename)
     → 213│                     self._acquire()
       214│                 if self.is_locked:
       215│                     _LOGGER.debug("Lock %s acquired on %s", lock_id, lock_filename)

  FileNotFoundError

  [Errno 2] No such file or directory: '/Users/tcapes/devdisk/.cache/poetry/cache/repositories/PyPI/_http/5/a/0/e/8/5a0e822c64c6d1f33f153767105760052e23ef8293f8ec21cf53e92b.lock'

  at /opt/homebrew/lib/python3.11/site-packages/filelock/_unix.py:37 in _acquire
       33│         """Uses the :func:`fcntl.flock` to hard lock the lock file on unix systems."""
       34│ 
       35│         def _acquire(self) -> None:
       36│             open_flags = os.O_RDWR | os.O_CREAT | os.O_TRUNC
    →  37│             fd = os.open(self.lock_file, open_flags, self._context.mode)
       38│             with suppress(PermissionError):  # This locked is not owned by this UID
       39│                 os.fchmod(fd, self._context.mode)
       40│             try:
       41│                 fcntl.flock(fd, fcntl.LOCK_EX | fcntl.LOCK_NB)

The following error occurred when trying to handle this error:

  Stack trace:

  4  /opt/homebrew/lib/python3.11/site-packages/requests/models.py:816 in generate
       814│             if hasattr(self.raw, "stream"):
       815│                 try:
    →  816│                     yield from self.raw.stream(chunk_size, decode_content=True)
       817│                 except ProtocolError as e:
       818│                     raise ChunkedEncodingError(e)

  3  /opt/homebrew/lib/python3.11/site-packages/urllib3/response.py:628 in stream
      626│         else:
      627│             while not is_fp_closed(self._fp):
    → 628│                 data = self.read(amt=amt, decode_content=decode_content)
      629│ 
      630│                 if data:

  2  /opt/homebrew/lib/python3.11/site-packages/urllib3/response.py:566 in read
      564│         fp_closed = getattr(self._fp, "closed", False)
      565│ 
    → 566│         with self._error_catcher():
      567│             data = self._fp_read(amt) if not fp_closed else b""
      568│             if amt is None:

  1  /opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py:155 in __exit__
      153│                 value = typ()
      154│             try:
    → 155│                 self.gen.throw(typ, value, traceback)
      156│             except StopIteration as exc:
      157│                 # Suppress StopIteration *unless* it's the same exception that

  ProtocolError

  ("Connection broken: FileNotFoundError(2, 'No such file or directory')", FileNotFoundError(2, 'No such file or directory'))

  at /opt/homebrew/lib/python3.11/site-packages/urllib3/response.py:461 in _error_catcher
      457│                 raise ReadTimeoutError(self._pool, None, "Read timed out.")
      458│ 
      459│             except (HTTPException, SocketError) as e:
      460│                 # This includes IncompleteRead.
    → 461│                 raise ProtocolError("Connection broken: %r" % e, e)
      462│ 
      463│             # If no exception is thrown, we should avoid cleaning up
      464│             # unnecessarily.
      465│             clean_exit = True

The following error occurred when trying to handle this error:

  Stack trace:

  23  /opt/homebrew/lib/python3.11/site-packages/cleo/application.py:327 in run
       325│ 
       326│             try:
     → 327│                 exit_code = self._run(io)
       328│             except BrokenPipeError:
       329│                 # If we are piped to another process, it may close early and send a

  22  /opt/homebrew/lib/python3.11/site-packages/poetry/console/application.py:190 in _run
       188│         self._load_plugins(io)
       189│ 
     → 190│         exit_code: int = super()._run(io)
       191│         return exit_code
       192│ 

  21  /opt/homebrew/lib/python3.11/site-packages/cleo/application.py:431 in _run
       429│             io.input.interactive(interactive)
       430│ 
     → 431│         exit_code = self._run_command(command, io)
       432│         self._running_command = None
       433│ 

  20  /opt/homebrew/lib/python3.11/site-packages/cleo/application.py:473 in _run_command
       471│ 
       472│         if error is not None:
     → 473│             raise error
       474│ 
       475│         return terminate_event.exit_code

  19  /opt/homebrew/lib/python3.11/site-packages/cleo/application.py:457 in _run_command
       455│ 
       456│             if command_event.command_should_run():
     → 457│                 exit_code = command.run(io)
       458│             else:
       459│                 exit_code = ConsoleCommandEvent.RETURN_CODE_DISABLED

  18  /opt/homebrew/lib/python3.11/site-packages/cleo/commands/base_command.py:119 in run
       117│         io.input.validate()
       118│ 
     → 119│         status_code = self.execute(io)
       120│ 
       121│         if status_code is None:

  17  /opt/homebrew/lib/python3.11/site-packages/cleo/commands/command.py:62 in execute
        60│ 
        61│         try:
     →  62│             return self.handle()
        63│         except KeyboardInterrupt:
        64│             return 1

  16  /opt/homebrew/lib/python3.11/site-packages/poetry/console/commands/add.py:164 in handle
       162│             return 0
       163│ 
     → 164│         requirements = self._determine_requirements(
       165│             packages,
       166│             allow_prereleases=self.option("allow-prereleases"),

  15  /opt/homebrew/lib/python3.11/site-packages/poetry/console/commands/init.py:387 in _determine_requirements
       385│             elif "version" not in requirement:
       386│                 # determine the best version automatically
     → 387│                 name, version = self._find_best_version_for_package(
       388│                     requirement["name"],
       389│                     allow_prereleases=allow_prereleases,

  14  /opt/homebrew/lib/python3.11/site-packages/poetry/console/commands/init.py:422 in _find_best_version_for_package
       420│ 
       421│         selector = VersionSelector(self._get_pool())
     → 422│         package = selector.find_best_candidate(
       423│             name, required_version, allow_prereleases=allow_prereleases, source=source
       424│         )

  13  /opt/homebrew/lib/python3.11/site-packages/poetry/version/version_selector.py:37 in find_best_candidate
        35│             },
        36│         )
     →  37│         candidates = self._pool.find_packages(dependency)
        38│         only_prereleases = all(c.version.is_unstable() for c in candidates)
        39│ 

  12  /opt/homebrew/lib/python3.11/site-packages/poetry/repositories/repository_pool.py:192 in find_packages
       190│             if packages and self.get_priority(repo.name) is Priority.SUPPLEMENTAL:
       191│                 break
     → 192│             packages += repo.find_packages(dependency)
       193│         return packages
       194│ 

  11  /opt/homebrew/lib/python3.11/site-packages/poetry/repositories/repository.py:40 in find_packages
        38│         constraint = dependency.constraint
        39│         allow_prereleases = dependency.allows_prereleases()
     →  40│         for package in self._find_packages(dependency.name, constraint):
        41│             if package.yanked and not isinstance(constraint, Version):
        42│                 # PEP 592: yanked files are always ignored, unless they are the only

  10  /opt/homebrew/lib/python3.11/site-packages/poetry/repositories/pypi_repository.py:114 in _find_packages
       112│         """
       113│         try:
     → 114│             json_page = self.get_page(name)
       115│         except PackageNotFound:
       116│             self._log(f"No packages found for {name}", level="debug")

   9  /opt/homebrew/lib/python3.11/site-packages/poetry/repositories/pypi_repository.py:216 in _get_page
       214│     def _get_page(self, name: NormalizedName) -> SimpleJsonPage:
       215│         source = self._base_url + f"simple/{name}/"
     → 216│         info = self.get_package_info(name)
       217│         return SimpleJsonPage(source, info)
       218│ 

   8  /opt/homebrew/lib/python3.11/site-packages/poetry/repositories/pypi_repository.py:105 in get_package_info
       103│         or retrieved from the remote server.
       104│         """
     → 105│         return self._get_package_info(name)
       106│ 
       107│     def _find_packages(

   7  /opt/homebrew/lib/python3.11/site-packages/poetry/repositories/pypi_repository.py:129 in _get_package_info
       127│     def _get_package_info(self, name: str) -> dict[str, Any]:
       128│         headers = {"Accept": "application/vnd.pypi.simple.v1+json"}
     → 129│         info = self._get(f"simple/{name}/", headers=headers)
       130│         if info is None:
       131│             raise PackageNotFound(f"Package [{name}] not found.")

   6  /opt/homebrew/lib/python3.11/site-packages/poetry/repositories/pypi_repository.py:223 in _get
       221│     ) -> dict[str, Any] | None:
       222│         try:
     → 223│             json_response = self.session.get(
       224│                 self._base_url + endpoint,
       225│                 raise_for_status=False,

   5  /opt/homebrew/lib/python3.11/site-packages/poetry/utils/authenticator.py:289 in get
       287│ 
       288│     def get(self, url: str, **kwargs: Any) -> requests.Response:
     → 289│         return self.request("get", url, **kwargs)
       290│ 
       291│     def post(self, url: str, **kwargs: Any) -> requests.Response:

   4  /opt/homebrew/lib/python3.11/site-packages/poetry/utils/authenticator.py:263 in request
       261│             except (requests.exceptions.ConnectionError, OSError) as e:
       262│                 if is_last_attempt:
     → 263│                     raise e
       264│             else:
       265│                 if resp.status_code not in STATUS_FORCELIST or is_last_attempt:

   3  /opt/homebrew/lib/python3.11/site-packages/poetry/utils/authenticator.py:260 in request
       258│             is_last_attempt = attempt >= 5
       259│             try:
     → 260│                 resp = session.send(prepared_request, **send_kwargs)
       261│             except (requests.exceptions.ConnectionError, OSError) as e:
       262│                 if is_last_attempt:

   2  /opt/homebrew/lib/python3.11/site-packages/requests/sessions.py:747 in send
       745│ 
       746│         if not stream:
     → 747│             r.content
       748│ 
       749│         return r

   1  /opt/homebrew/lib/python3.11/site-packages/requests/models.py:899 in content
        897│                 self._content = None
        898│             else:
     →  899│                 self._content = b"".join(self.iter_content(CONTENT_CHUNK_SIZE)) or b""
        900│ 
        901│         self._content_consumed = True

  ChunkedEncodingError

  ("Connection broken: FileNotFoundError(2, 'No such file or directory')", FileNotFoundError(2, 'No such file or directory'))

  at /opt/homebrew/lib/python3.11/site-packages/requests/models.py:818 in generate
       814│             if hasattr(self.raw, "stream"):
       815│                 try:
       816│                     yield from self.raw.stream(chunk_size, decode_content=True)
       817│                 except ProtocolError as e:
    →  818│                     raise ChunkedEncodingError(e)
       819│                 except DecodeError as e:
       820│                     raise ContentDecodingError(e)
       821│                 except ReadTimeoutError as e:
       822│                     raise ConnectionError(e)

**Comment by TimCapes** [comment]
poetry cache list returns "no caches found". Still generate the same pattern of errors if I try running again.

**Comment by dimbleby** [comment]
if you don't change anything then it's not surprising that nothing changes.  delete your cache directory.
