### ISSUE TITLE
Stuck adding packages

### ISSUE THREAD

**Issue by dimaqq** [python-poetry/poetry#8187]
I've just created a new poetry env using `poetry init`, all defaults no libs.

Then I tried to add some libraries and it got stuck:

```
> poetry add hypercorn fastapi bottle
Creating virtualenv test-xsgi-6aHOW7Gv-py3.11 in /home/dima/.cache/pypoetry/virtualenvs
Using version ^0.14.4 for hypercorn
Using version ^0.100.0 for fastapi
Using version ^0.12.25 for bottle

Updating dependencies
Resolving dependencies... (1.1s)

Writing lock file

Package operations: 17 installs, 0 updates, 0 removals

  • Installing idna (3.4)
  • Installing sniffio (1.3.0)
  • Installing typing-extensions (4.7.1)
  • Installing annotated-types (0.5.0): Pending...
  • Installing anyio (3.7.1)
  • Installing h11 (0.14.0)
  • Installing hpack (4.0.0)
  • Installing hyperframe (6.0.1)
  • Installing pydantic-core (2.1.2)
^C

fish: Job 1, 'poetry add hypercorn fastapi bo…' terminated by signal SIGKILL (Forced quit)
```

It wouldn't resume on ctrl-c either.

So I found the pid of the poetry chilled and `kill -9` it from another terminal.

Running the same command went OK though, so I can't reproduce.

Versions:
```
Python 3.11.4 (main, Jun  7 2023, 12:45:49) [GCC 9.4.0] on linux
Poetry (version 1.3.2)
Ubuntu 20.04.4 + kernel 6.4.2
```

In the future, if I catch it in this state, how can I generate a reasonable... core? trace? something that would help the wise ones debug a hang like this?

**Comment by dimbleby** [comment]
this is a python question, not a poetry question.  First answer that my search engine returns is https://stackoverflow.com/questions/132058/showing-the-stack-trace-from-a-running-python-application

**Comment by dimaqq** [comment]
I could not repro
