### ISSUE TITLE
improve performance of version solver for dependencies with many versions

### ISSUE THREAD

**Issue by ahvigil** [python-poetry/poetry#8191]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request

The current dependency solver can perform suboptimally for packages with many frequent releases creating long chains to explore. `botocore` in particular seems to be problematic and can produce dead ends in the graph of possible package combinations that poetry takes _a long time_ to resolve out of.

See: 

- https://github.com/python-poetry/poetry/issues/832#issuecomment-613618715
- https://github.com/python-poetry/poetry/issues/7858
- https://github.com/python-poetry/poetry/issues/7875
- https://github.com/python-poetry/poetry/issues/7856

The workarounds for these are generally of the "pin package X" variety, which works well but doesn't make for the best user experience and adds requirements to a pyproject.toml that a developer doesn't necessarily care about. The documentation section on ["why-is-the-dependency-resolution-process-slow"](https://python-poetry.org/docs/faq/#why-is-the-dependency-resolution-process-slow) also suggest adding pins as a solution for speed up resolution. 

Investigate improving the performance of the version solver in these cases, preferably without too much impact on non-pathologic cases.

**Comment by dimbleby** [comment]
the code you've linked has nothing much to do with the main part of poetry's search, which is neither depth-first nor breadth-first.

what you want to think about is changing the heuristic by which poetry chooses the next package to resolve - https://github.com/python-poetry/poetry/blob/01657ddeca182259e4350794a4f378241336085f/src/poetry/mixology/version_solver.py#L443-L475

eg most of the cases that currently go wrong are made much faster by reversing the preference for packages with fewer available versions.  However: there's every chance that making that change will introduce _new_ pathological cases - there is no silver bullet.

Feel free to experiment.

**Comment by ahvigil** [comment]
thats a great pointer, thanks! i must admit I'm not too familiar with the poetry codebase except as a user, seems I was looking in the wrong place.

**Comment by ahvigil** [comment]
using the [backtracking unit test cases](https://github.com/python-poetry/poetry/blob/master/tests/mixology/version_solver/test_backtracking.py) as a model I came up with a case that reproduces the performance issue I'm circling around
```
def test_i_can_reproduce_the_issue(
    root: ProjectPackage, provider: Provider, repo: Repository
) -> None:
    root.add_dependency(Factory.create_dependency("a", "*"))
    root.add_dependency(Factory.create_dependency("b", "*"))

    add_to_repo(repo, "a", "1.0.0", deps={"z": "<=2.0.0"})
    for i in range(500):
        add_to_repo(repo, "b", "%i.0.0" % i, deps={"z": "<=1.0.0"})
    add_to_repo(repo, "z", "1.0.0")
    add_to_repo(repo, "z", "2.0.0")

    check_solver_result(root, provider, {"a": "1.0.0", "b": "%i.0.0" % i, "z": "1.0.0"})
```
this test passes but the solver takes quite a long time
```
======================== 1 passed in 199.29s (0:03:19) =========================
```
I'll fiddle to see if I can figure out a way to get around this without breaking the solver for more common cases.
