### ISSUE TITLE
Error with Poetry Install when running in TrainingContainerDockerFile

### ISSUE THREAD

**Issue by codingwithsurya** [python-poetry/poetry#8193]
- **Poetry version**: 1.5.1
- **Python version**: 3.9.17
- **OS version and name**: macOS Ventura 13.4
- **[pyproject.toml](https://gist.github.com/codingwithsurya/02f6a0508b5f6f5c65e1465f06c15e6e)**

- [ x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [ x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x ] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

I am encountering an issue when trying to run poetry install inside a Docker container. The error message I receive is:

```
ERROR [ 4/12] RUN poetry install --no-interaction --no-ansi --no-root:
0.769 /bin/sh: 1: poetry: not found
```
Issue Details:

# Here is my full TrainingContainerDockerfile code:

```
FROM python:3.9-slim

WORKDIR /

RUN curl -sSL https://install.python-poetry.org | python -

COPY pyproject.toml poetry.lock ./

RUN poetry install --no-interaction --no-ansi --no-root


COPY . .

ARG TARGETARCH

RUN if [ "${TARGETARCH}" = "arm64" ] ; then \
        curl "https://awscli.amazonaws.com/awscli-exe-linux-aarch64.zip" -o "awscliv2.zip" ; \
    else \
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" ; \
    fi

RUN unzip awscliv2.zip
RUN ./aws/install

ARG AWS_REGION
ARG AWS_DEPLOY_ACCESS_KEY_ID
ARG AWS_DEPLOY_SECRET_ACCESS_KEY

RUN aws configure set region $AWS_REGION
RUN aws configure set aws_access_key_id $AWS_DEPLOY_ACCESS_KEY_ID
RUN aws configure set aws_secret_access_key $AWS_DEPLOY_SECRET_ACCESS_KEY

ENV SQS_QUEUE_URL='https://sqs.us-west-2.amazonaws.com/521654603461/dlp-training-queue'

CMD poetry run python -m backend.common.kernel
```

# Other:

_Main idea: Looks like its not even recognizing poetry. anyone else have any other alternatives of installing poetry?_

I have installed Poetry on my local machine, and it works fine outside the Docker container.
I have included the installation of Poetry in my Dockerfile using the official installation script.
I have verified that the necessary project files (pyproject.toml and poetry.lock) are correctly copied into the container.
The Docker build fails at the step where poetry install is executed.
It's important to note that the same poetry install function worked successfully on a regular Dockerfile (non-containerized) setup.

I expect poetry install to be executed successfully within the Docker container, installing the project dependencies specified in pyproject.toml, just as it does in a regular Dockerfile setup.

**Comment by dimbleby** [comment]
please read the docs that tell you how to install poetry, paying special attention to the bit about updating the path.

please close this issue
