### ISSUE TITLE
Executing the `poetry show --tree` command outputs Packages with inaccurate colors

### ISSUE THREAD

**Issue by AtomAsking** [python-poetry/poetry#8197]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

Env Info:
- Poetry version: Poetry (version 1.5.1)
- Python version: CPython 3.9.17
- OS version and name: macOS 10.14.6
- pyproject.toml: https://gist.github.com/AtomAsking/71529bc62f0fee91f95dcef3a158f43a

Bug Info: 
- When I execute the `poetry show` command: 
  - If I have not installed the `typing-extensions` Package, the name is Red.
  - If I have installed the `typing-extensions` Package, the name is Cyan.
- However, when I run the `poetry show -t` command, it always shows that it's all Cyan.

So, Guess: Is the `-t` argument causing the correct package name color not to be displayed?

**Comment by eamanu** [comment]
Hi,

Seems that the colors in `poetry show -t` has not the same logic than in poetry show. When --tree option is added, each color of dependencies is a level of dependency. It does not mean that the dependency is installed or not.

**Comment by AtomAsking** [comment]
@eamanu Thank you for your reply, I think you are right, after thinking, the existing design is reasonable, so I closed this issue.
