### ISSUE TITLE
Is it possible to get the version field dynamically?

### ISSUE THREAD

**Issue by Yingqingshan** [python-poetry/poetry#8199]
`[tool.poetry]
name = "weeeTest"
version = "0.2.7"
`

Can this version be obtained dynamically? Is it possible to read the value of the version from a file of type py in the project, not yet some version number written dead in the configuration?

**Comment by PeterBosch2** [comment]
What about poetry-dynamic-versioning plugin? https://pypi.org/project/poetry-dynamic-versioning/

**Comment by finswimmer** [comment]
Hey,

this is not possible. If you need the version during runtime you want to use `importlib.metadata` to read the version if the installed package:

```py
import importlib.metadata

__version__ = importlib.metadata.version("weeeTest")
```

fin swimmer

**Comment by Yingqingshan** [comment]
> Hey,
> 
> this is not possible. If you need the version during runtime you want to use `importlib.metadata` to read the version if the installed package:
> 
> ```python
> import importlib.metadata
> 
> __version__ = importlib.metadata.version("weeeTest")
> ```
> 
> fin swimmer

How to get the value of this variable from __version__. Can you write a demo?
