### ISSUE TITLE
Packages always included even if they are not listed in `packages`

### ISSUE THREAD

**Issue by antazoey** [python-poetry/poetry#8213]
- **Poetry version**: Poetry (version 1.5.1)
- **Python version**: Python:  3.10.11
- **OS version and name**: 13.4.1 (22F82)
- **pyproject.toml**: https://github.com/antazoey/ApePay/blob/fix/packages-2/pyproject.toml#L8
- 

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

So the main issue I am having is that if I don't use a `src` directory to put my packages in and reference them from there, it will always include modules from my root project that I don't want in the Python build. For example, it always includes both `scripts` and `tests` which are not part of the package.

By _includes_, this is what I mean: If I install my project that has this form and I go to my home directory, and I run:

```python
python -c "import scripts; print(scripts.__path__)"
```

it will print out the path to the project I installed. So I can import `tests` and `scripts` from anywhere on my OS, and I am just trying to exclude that from happening.

The only way I have gotten it to work is to put the actual package first in a `src` directory and reference it like:

```
packages = [ { include = "my-package", from = "src" } ]
```

But really , I was hoping to not have to change the project structure. **I don't want to have to create a src directory**

I would prefer to do this:

```
packages = [{ include = "apepay" }]
```

and have it not include `tests/` and `scripts`/.

I have tried every combo of `include` and `exclude` and `packages` but the only that actually works so far is the `src` directory.

**Comment by trag1c** [comment]
Fix the `pyproject.toml` link

**Comment by antazoey** [comment]
> Fix the `pyproject.toml` link

It's fixed now, sorry about that

**Comment by dimbleby** [comment]
what you are describing is already the default behaviour and you don't have to specify `packages` at all, please close.

(I suspect you are simply in a virtual environment where the `sys.path` includes the root of your codebase)

**Comment by antazoey** [comment]
Ok thank you, sorry I guess

**Comment by antazoey** [comment]
@dimbleby just note, it doesnt happen when I use setup.py and the `include` / `packages` field, only poetry.

**Comment by antazoey** [comment]
Like I had this same problem when I did:

```
find_packages(exclide=["scripts"])
```

but it was fixed when I did:

```
    packages=["my-package"],
```

but I tried the equivalent in Poetry and it did not fix

**Comment by antazoey** [comment]
I wish you didnt make me close without further discussion as well, that seems rushed! Why even.

**Comment by antazoey** [comment]
I either have to use `setup.py` and not poetry, or I have to change my project structure in order install in editable mode for my project, unless I am just missing something or there is a bug.

**Comment by dimbleby** [comment]
you've reopened it, but this is still nothing to do with poetry

the way editable installs work is by creating a ` .pth` file, which causes the directory that it points at to be added to the python sys.path.  See https://setuptools.pypa.io/en/latest/userguide/development_mode.html.  That's what allows your project to be imported.

so all you are seeing is - as I said - that the root of your repository is in your sys.path.

if you build the wheel you can inspect it and verify that it contains only the files that you expect.

Please close.

**Comment by antazoey** [comment]
If it did not have anything to do with Poetry, it would work on both poetry and normal setup.py approach (`pip install -e .`).
Instead, it only works on setup.py editable approach and not poetry.

but no problem I won't use poetry then.

**Comment by dimbleby** [comment]
if this is important to you then not using poetry is the right choice.  

I have confirmed that a project using `pyproject.toml` and any backend chosen from `flit`, `hatch`, `pdm`, and `setuptools` behaves in the same way as poetry, so you'll want to avoid those too.

**Comment by antazoey** [comment]
setuptools is not behaving that way for me, so maybe that is less rude answer somewhere

**Comment by antazoey** [comment]
@dimbleby as I mentioned, to fix this problem using `setuptools,` I do `packages=["my-package"],` and then when installing in editable mode, `tests` is NOT importable from anywhere on my OS, only the package is.

**Comment by antazoey** [comment]
> please read what I wrote: I specified "a project using `pyproject.toml`" behaves that way. You have - I think rightly - said that you have to use `setup.py` to avoid this behaviour.

OK, sorry for the frustration, and yes obviously this is important to me and is breaking stuff locally and causing all sorts of confusions for weeks. So sorry I am upset but it is annoying to be dismissed and told stuff I already know
