### ISSUE TITLE
Could not parse version constraint: >="3.0"

### ISSUE THREAD

**Issue by solarw** [python-poetry/poetry#8220]
python3.10.9, ubuntu 23.04
poetry==1.5.1
poetry-core==1.6.1
poetry-plugin-export==1.4.0

`poetry add opencore-api==0.13.2`
fails with 
```

Updating dependencies
Resolving dependencies... (0.0s)

The requirement is invalid: invalid version constraint ">="3.0""

```

probably comes from https://github.com/python-openapi/openapi-core/blob/0.13.2/requirements_dev.txt

pip and pipenv install it well.
looks like a bug for parsing quoted version string

**Comment by dimbleby** [comment]
I don't see any justification in PEP 440 for allowing the quote marks - please provide a reference if you believe they should be allowed.

Else please close; and open an issue against the project with the faulty dependency.

**Comment by dimbleby** [comment]
while pip doesn't barf on the bogus specifier, it clearly also doesn't understand it:
```
$ pip install openapi-core[django]==0.13.2

...
Collecting python-version>="3.0" (from openapi-core[django]==0.13.2)
  Downloading python_version-0.0.2-py2.py3-none-any.whl (3.4 kB)
```

I'd say that poetry's behaviour is actually preferable.

Please close
