### ISSUE TITLE
Strangeness when using code generated by a dependency 

### ISSUE THREAD

**Issue by dw-mt** [python-poetry/poetry#8222]
- **Poetry version**: Poetry (version 1.5.1)
- **Python version**: Python:  3.11.4
- **OS version and name**: macOS 13.4.1
- **pyproject.toml**: https://github.com/dw-mt/ExampleApplication/blob/main/pyproject.toml

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

I have a gRPC protocol definition that I want to share with multiple Python applications. The project contains a protocol definition and a build script that generates the code.

When I run `poetry install` in the protocol project, it generates the code as expected.

However, when I include the protocol project as a dependency of my application project, the code isn't generated.
I verify this by checking the virtual environment's `src/ExampleShared/protocol/` directory, which contains no generated code.
Additionally, the package install location `lib/python3.11/site-packages/protocol/` only contains `__init__.py` (as the protocol file is excluded).

But it gets strange.

When I update the protocol project and commit it, and then update the application project with `poetry update`, the source gets generated in `src/ExampleShared/protocol`. It's still missing from the install site.

So the code is generated and put in the right place in the virtual environment's clone of the source tree, but only after a new commit makes it update. And the generated code never reaches the install site.

### Minimum example

Shared project: https://github.com/dw-mt/ExampleShared

Application: https://github.com/dw-mt/ExampleApplication

**Comment by dimbleby** [comment]
duplicate #6197

**Comment by dw-mt** [comment]
Thank you. Applying the workaround in https://github.com/python-poetry/poetry/issues/6197#issuecomment-1336221319 fixed my issue.
