### ISSUE TITLE
Issue installed pandas

### ISSUE THREAD

**Issue by dreadedhamish** [python-poetry/poetry#8228]
Poetry (version 1.5.1)
Python 3.10.12
macOS 12.6.7
pyproject.toml - https://gist.github.com/dreadedhamish/55a1124306f739a6ddc3c67cd47404cc

- [ x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [ x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [ x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
I'm having trouble getting pandas installed. 
Attached is the config for a project I created to isolate it to pandas.
No error is thrown during install of pandas - reports success.
No folder is created in the .venv for pandas

**Comment by clintonroy** [comment]
By default poetry creates a virtual environment for you, and doesn't use .venv, does poetry env list help?

**Comment by dreadedhamish** [comment]
> poetry env list

sorry - yes that's my customisation.

poetry env list correctly points to this folder, and other packages are correctly installed there.

**Comment by clintonroy** [comment]
poetry install -vvv (as requested by the bug form) should show you where it's installing packages.

**Comment by dreadedhamish** [comment]
As I stated it was installing other packages in the correct location, just not pandas.
I'm not sure what it was but a clean install of poetry and deleting the existing .venv folder has resolved things.
