### ISSUE TITLE
Poetry does not install packages in docker entrypoint when tty is activated

### ISSUE THREAD

**Issue by hochstibe** [python-poetry/poetry#8230]
- **Poetry version**: 1.5.1
- **Python version**: 3.10.12 (slim-buster image)
- **OS version and name**: Debian GNU/Linux 10 (buster)
- **pyproject.toml**: [pyproject.toml](https://gist.github.com/hochstibe/e1a6371029102563812930ca7deef8bd)

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

I need to install some dependencies in the entrypoint of my docker container. The main dependencies are installed when building the image, some additional packages (groups) are installed later. For a colored logging output, I activated `tty: true` in my docker-compose.

Problem:
`poetry install` in a docker entrypoint script does not install the packages. It detects, that some packages need to be installed (`Package operations: 3 installs, 0 updates, 0 removals`), but it does not install them. There is no error message (even not in verbose mode). `poetry show` lists them as red.
Entering the running container, it is possible to install the missing packages.

When deactivating `tty` (default) in docker-compose, it installs the packages in the entrypoint.

To reproduce, i set up a [repository](https://github.com/hochstibe/test-docker-poetry) with 

* pyproject.toml
* dockerfile
* entrypoint
* docker-compose

Running `docker-compose up -d --build` and checking the logs of the 2 containers (`docker compose logs test_poetry1` tty with failed install and `docker compose logs test_poetry2` with correct install)

**Comment by dimbleby** [comment]
presumably duplicate #7184
