### ISSUE TITLE
Add option to install all optional dependencies.

### ISSUE THREAD

**Issue by PhilipMay** [python-poetry/poetry#8244]
I would like to have an option to install all optional dependencies.
When I have <s>multiple dependency groups</s> optional packages which are part of a specific group this way it would be much more simple
to install all of them.

Example:

I have somthing like this:
```
[tool.poetry.extras]
group1 = ["package1", "package2"]
group2 = ["package3", "package4"]
```

And I want to install all groups.

**Comment by dimbleby** [comment]
well this is a strange one

installing all dependency groups is the default behaviour.  The command you want is `poetry install`.

please close

**Comment by PhilipMay** [comment]
I am talking about these: `poetry add --optional <package>`.
I do not think that they are installed by default. Otherwise optional would be useless.

**Comment by PhilipMay** [comment]
And with "multiple dependency groups" I meant "optional packages which are part of a specific group".

Like this:

```
[tool.poetry.extras]
<group_name> = ["package"]
```

Sorry for the confusion.

**Comment by dimbleby** [comment]
you're not talking about dependency groups at all, but about extras?

the usual convention is just to define an extras group `all`, and put all of your extras in that

then you've got a solution where `pip install my-package[all]` works too, without any non-standard poetry specials

**Comment by PhilipMay** [comment]
> the usual convention is just to define an extras group `all`, and put all of your extras in that

Yes. But then I have to specify all optional packes twice. In `group1` and in `all`.
I want to avoid that redundancy...
What if I forget one? That is why I ask for this feature.

**Comment by dimbleby** [comment]
not an exact duplicate, but #5471 sounds like a better feature request - recommend closing this in favour of that

**Comment by dimbleby** [comment]
no wait, what you are asking for is already supported: `poetry install --all-extras`

please close

**Comment by PhilipMay** [comment]
ok. thanks and sorry for the confusion.
