### ISSUE TITLE
Optional Dependency marked as required

### ISSUE THREAD

**Issue by eamanu** [python-poetry/poetry#8248]
- **Poetry version**:  1.5.1 (1.3.2 in Debian)
- **Python version**: 3.11.4-->
- **OS version and name**: Debian Testing -->
- **pyproject.toml**:

```
[tool.poetry]
name = "test"
version = "0.1.0"
description = "test"
authors = ["test author <mail@mail.com>"]
readme = "README.md"
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.31.0"
httpcore = {version=">=0.17.3", optional=true, python=">=3.8"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.poetry.extras]
doh = ['httpx', 'h2']
idna = ['idna']
dnssec = ['cryptography']
trio = ['trio']
wmi = ['wmi']
doq = ['aioquic']
```

- [ x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [ x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [ x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

If a dependency marked as optional=True  and it is not added in extras section  poetry-core  assumes the package is required, despite the optional flag

```
Requires-Dist: httpcore (>=0.17.3) ; python_version >= "3.8"
```

If the optional dependency is added to extras section  is marked as Provides-Extra and added the extra==httpcore

```
Provides-Extra: httpcore
...
Requires-Dist: httpcore (>=0.17.3) ; (python_version >= "3.8") and (extra == "httpcore")
```

I didn't found any documentation that can explain why an optional dependency is marked as required if is not listed in extras.

The original bug was reported here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1041538

Cheers,

**Comment by clintonroy** [comment]
If a dependency is marked as optional, and is not added in an extras section, that is not a valid configuration. 

The optional flag on a dependency means nothing in a python packaging context on it's own, it only means something when that dependency is added to an extra.

Run poetry check on your configuration.

**Comment by dimbleby** [comment]
duplicate #2357

**Comment by eamanu** [comment]
Hi @clintonroy i think that  it is duplicating information, we need to mark an optional dependency in two places. If I understand correctly extra section is useful only for `-E|--extra` param.

IMO if I mark a dependency as optional it must be optional when I build my package with poetry, build, or any frontend tool.

**Comment by eamanu** [comment]
I will close this issue, it is duplicated, thanks @dimbleby
