### ISSUE TITLE
poetry add fails with wrong and useless error message

### ISSUE THREAD

**Issue by Zethson** [python-poetry/poetry#8252]
- **Poetry version**: 1.5
- **Python version**: 3.10
- **OS version and name**: Arch Linux
- **pyproject.toml**: 

```
[tool.poetry]
name = "ehrapy"
packages = [
    { include = "ehrapy" },
]

[tool.poetry.dependencies]
python = ">=3.9.0,<3.11"
dowhy = { git = "https://github.com/py-why/dowhy.git", branch = "main" }
```

- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

`poetry add statsmodels@latest` results in 

```
Because dowhy (0.0.0) @ git+https://github.com/py-why/dowhy.git@main depends on both statsmodels (^0.13.5) and statsmodels (^0.13.5), statsmodels is required.
So, because ehrapy depends on statsmodels (^0.14.0), version solving failed.
```

which doesn't make any sense to me. 0.14.0 should be fine with a ^0.13.5 requirement, right? And what is this error message?

**Comment by dimbleby** [comment]
nope

please read the docs, and then please close this issue

https://python-poetry.org/docs/dependency-specification/#caret-requirements
