### ISSUE TITLE
raise PoetryException(f"Failed to install {path.as_posix()}") for scikit-learn

### ISSUE THREAD

**Issue by RamakrishnaHande** [python-poetry/poetry#8259]
I want to use alpine image for python for my production, since it is free from security vulnerabilities.

I have a simple project 'my_project' It contains a simple helloWorld program, which is 

      # helloworld.py
      from sklearn import __version__ as sklearn_version

      def main():
        print(f"Hello, World! Using Scikit-learn {sklearn_version}.")

      if __name__ == "__main__":
        main()

My pyproject.toml is 

        [tool.poetry]
        name = "my_project"
        version = "0.1.0"
        description = "A small Python project with Scikit-learn"
        authors = ["Your Name <your@email.com>"]

        [tool.poetry.dependencies]
        python = ">=3.9,<3.10"
        scikit-learn = "^1.3.0"

        [build-system]
        requires = ["poetry>=1.1.0"]
        build-backend = "poetry.masonry.api"

        [tool.poetry.dev-dependencies]
        pytest = "^6.0"

and my Dockerfile is :

      FROM python:3.9-alpine

      WORKDIR /app
      RUN apk add --no-cache curl gcc musl-dev
      RUN curl -sSL https://install.python-poetry.org | POETRY_VERSION=1.3.2 python -

      ENV PATH="/root/.local/bin:${PATH}"

      COPY . .

      RUN poetry config virtualenvs.create false && poetry install --no-root --no-dev

      CMD ["python", "helloworld.py"]

I get below error

    The following error occurred when trying to handle this error:

    PoetryException

    Failed to install 

 
 `/root/.cache/pypoetry/artifacts/ab/bb/06/9a4febd4bdf663c71169b02b45c3bf72c69a043d8961fb0c668e8dad14/scikit-learn-1.3.0.tar.gz`

Same thing works fine for python 3.9.17 slim buster image. How to fix it for alpine ?

**Comment by dimbleby** [comment]
use recent poetry and if still broken please do the things that the issue template asks you to do

**Comment by abn** [comment]
This is likely an issue with the image missing required build time dependencies. The following is a working example under alpine (see also logs below).

```sh
podman run --rm -i --entrypoint sh docker.io/python:3.9-alpine <<EOF
set -xe
apk add --quiet --no-cache --no-progress build-base sed
python -m pip install --disable-pip-version-check -q poetry

poetry config virtualenvs.in-project true
poetry config virtualenvs.options.no-pip true
poetry config virtualenvs.options.no-setuptools true

poetry new demo
cd demo

sed -i 's/python =.*/python = "~3.9"/g' pyproject.toml

cat > helloworld.py <<PY
from sklearn import __version__ as sklearn_version

def main():
    print(f"Hello, World! Using Scikit-learn {sklearn_version}.")

if __name__ == "__main__":
    main()

PY

poetry add  scikit-learn@^1.3.0
poetry run python helloworld.py
EOF
```

<details>
<summary><b>podman.log</b></summary>
<p>

```console
+ apk add --quiet --no-cache --no-progress build-base sed
+ python -m pip install --disable-pip-version-check -q poetry
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
+ poetry config virtualenvs.in-project true
+ poetry config virtualenvs.options.no-pip true
+ poetry config virtualenvs.options.no-setuptools true
+ poetry new demo
Created package demo in demo
+ cd demo
+ sed -i 's/python =.*/python = "~3.9"/g' pyproject.toml
+ cat
+ poetry add scikit-learn@^1.3.0
Creating virtualenv demo in /demo/.venv

Updating dependencies
Resolving dependencies...

Package operations: 5 installs, 0 updates, 0 removals

  - Installing numpy (1.26.4)
  - Installing joblib (1.3.2)
  - Installing scipy (1.12.0)
  - Installing threadpoolctl (3.3.0)
  - Installing scikit-learn (1.4.1.post1)

Writing lock file
+ poetry run python helloworld.py
Hello, World! Using Scikit-learn 1.4.1.post1.
```

</p>
</details>

Closing this issue as the issue is not reproducible with the given information.
