### ISSUE TITLE
Compatibility Option for "develop" Dependencies

### ISSUE THREAD

**Issue by blewis2-blue** [python-poetry/poetry#8260]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request
Static analysis tools such as Pylance have difficulty with "develop = true" dependencies that are managed by import hooks. A compatibility mode for Poetry that instead uses .pth files for these dependencies could aid them.

I had originally opened an issue for Pylance at https://github.com/microsoft/pylance-release/issues/4664, but they recommended I open this issue instead.

**Comment by radoering** [comment]
duplicate: #7892

That's not about poetry but about setuptools. The build backend decides how to handle editable installs and in your example the build backend of the `funniest` package is setuptools, not poetry.

see pypa/setuptools#3518
