### ISSUE TITLE
Update cryptography dependency to 41.0.3

### ISSUE THREAD

**Issue by wwuck** [python-poetry/poetry#8265]
The [cryptography](https://pypi.org/project/cryptography/) python package has released a new version [41.0.3](https://cryptography.io/en/latest/changelog/#v41-0-3) fixing https://github.com/advisories/GHSA-jm77-qphf-c4w8 and I am seeing poetry still using an older version when I scan my project with [trivy](https://trivy.dev/).

Can we get this updated in poetry?

Thanks

**Comment by dimbleby** [comment]
cryptography is only an indirect dependency of poetry: this project does not impose any upper bound for it.

if some other project in the dependency tree puts an upper bound on cryptography then you should take your request to them; if not then all you need to do is reinstall your copy of poetry

there is nothing to be done here.
