### ISSUE TITLE
Docs should be very explicit that only one of the git options at a time is supported

### ISSUE THREAD

**Issue by c-p-b** [python-poetry/poetry#8266]
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue
We should make explicit this behavior in the documentation

https://github.com/python-poetry/poetry/blob/dfd0db8366301087bcb1b596e0344cd0450448e5/src/poetry/packages/direct_origin.py#L49

I went in expecting this to work:

```python
mypackage = {git = "https://github.com/myorg/myrepo.git", branch = "mybranch", rev="1b804386a51a9c5c20dc7c866708a5a7a28c35aa"}
```
When in reality, as the above code demonstrates, it does not work as I expected.

The docs should be clearer about this.

Also, and perhaps it feels like it should be a separate issue, but 

- [ ] The tool should fail when you are asking it to do something that is nonsensical, like specifying both a tag and a rev
- [ ] The tool should also allow the use-case that I specified, if it makes sense?

**Comment by dimbleby** [comment]
if you want to see a docs change: submit a merge request!

**Comment by cpdeethree** [comment]
Awesome, I will do so, just wanted to make sure that this made sense before doing so. Is it worthwhile to file a separate issue for changing the behavior of the tool as mentioned in the issue?

**Comment by dimbleby** [comment]
There are 500 open issues and this doesn't sound to me as though it's important enough that anyone other than you is especially likely to take an interest in it. 

So I'd suggest: if you want to raise a merge request then go for it, if you instead raise an issue then the likely outcome is that it will just sit around untouched forever.

**Comment by finswimmer** [comment]
In the meantime the [docs](https://python-poetry.org/docs/dependency-specification/#git-dependencies) are saying:

> You can combine the git key with the branch key to use another branch. _**Alternatively**_, use rev or tag to pin a dependency to a specific commit hash **_or_** tagged ref, **_respectively_**. 

I hope this makes it clearer. If not, still feel free to open a PR to improve it.
