### ISSUE TITLE
Private Gitlab access gives authorization error

### ISSUE THREAD

**Issue by elagil** [python-poetry/poetry#8267]
Poetry
```
Version: 1.5.1
Python:  3.10.6
```

OS
```
Version: Ubuntu 22.04
5.10.102.1-microsoft-standard-WSL2
```

Pyproject.toml
```
[tool.poetry]
name = "project_name"
version = "1.2.3"

[[tool.poetry.source]]
name = "private"
url = "https://gitlab.com/api/v4/projects/<project_id>/packages/pypi/simple"
priority = "supplemental"

[[tool.poetry.source]]
name = "PyPI"
priority = "primary"

[tool.poetry.dependencies]
python = "<3.12,>=3.8"
<further packages>

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

I am having issues installing from a private Gitlab pypi server.

Steps that were performed
- Added a supplemental source to my `pyproject.toml` file
- Added the repository with  `poetry config repositories.private https://gitlab.com/api/v4/projects/<project_id>/packages/pypi/simple`
- Added my token (`api` scope) with `poetry config pypi-token.private <my_token>`
- Run `poetry update -vvv` in my project. Relevant section:
```
Loading configuration file /home/<user>/.config/pypoetry/config.toml
Loading configuration file /home/<user>/.config/pypoetry/auth.toml
Adding repository private (https://gitlab.com/api/v4/projects/<project_id>/packages/pypi/simple) and setting it as supplemental
Adding repository PyPI (https://pypi.org/simple/) and setting it as primary
Using virtualenv: /path/to/.venv
Updating dependencies
Resolving dependencies...
    <removed dependency names>
No suitable keyring backend found
No suitable keyring backends were found
Keyring is not available, credentials will be stored and retrieved from configuration files as plaintext.
Creating new session for gitlab.com
[urllib3.connectionpool] Starting new HTTPS connection (1): gitlab.com:443
[urllib3.connectionpool] https://gitlab.com:443 "GET /api/v4/projects/<project_id>/packages/pypi/simple/<package_name>/ HTTP/1.1" 401 30
Source (private): Authorization error accessing https://gitlab.com/api/v4/projects/<project_id>/packages/pypi/simple/<package_name>/
Source (private): No packages found for <package_name>
```

Configuration files look fine to me:
```
cat ~/.config/pypoetry/config.toml 
[repositories]
[repositories.private]
url = "https://gitlab.com/api/v4/projects/<project_id>/packages/pypi/simple"
```

```
cat ~/.config/pypoetry/auth.toml
[pypi-token]
private = "<my_token>"
```

Finally, it just works with pip:
`poetry run pip install -i https://private:<my_token>@gitlab.com/api/v4/projects/<project_id>/packages/pypi/simple <package_name>`

What else can I do? The same happens on other machines (no WSL2, but still Ubuntu 22.04).

**Comment by elagil** [comment]
It works when I use `poetry config http-basic.private "" "<token>"` instead of `poetry config pypi-token.private "<token>"`.

Why is it so? It doen't make sense to me.

**Comment by dimbleby** [comment]
your private gitlab is not pypi

please submit a merge request fixing whatever documentation it is that made you think a pypi token would work here, else close

**Comment by elagil** [comment]
I see, that sounds reasonable. I will create a merge request.
