### ISSUE TITLE
Poetry creates a new virtual environment in a project that already has a functioning virtual environment

### ISSUE THREAD

**Issue by betterthanever2** [python-poetry/poetry#8269]
- **Poetry version**:  1.5.1
- **Python version**: 3.10.5
- **OS version and name**: Win10 22H2
- **pyproject.toml**:  https://gist.github.com/betterthanever2/e9ebdaf1aad2bff314dfc3b2f680b948

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
Other relevant preconditions: I'm using Pycharm.
1. In Pycharm, the path to the python executable can be controlled via `Settings -> Python interpreter`. For reference, here's the full path to the executable that is set there:
```
C:\Users\USER\AppData\Local\pypoetry\Cache\virtualenvs\wapatools-3SjGFAFe-py3.10\Scripts\python.exe
```
I will refer to it as `3SjGFAFe` for simplicity.

2. With Poetry, the path to the executable can be obtained by running `poetry env info`. Here's the result of my running this comman on that same project:
```
Virtualenv
Python:         3.10.5
Implementation: CPython
Path:           C:\Users\USER\AppData\Local\pypoetry\Cache\virtualenvs\wapatools-j7smKuLy-py3.10
Executable:     C:\Users\USER\AppData\Local\pypoetry\Cache\virtualenvs\wapatools-j7smKuLy-py3.10\Scripts\python.exe
Valid:          True


Expecting value: line 1 column 2 (char 1)
```

Nevermind the last line (although it would be nice to know what's that about). Notice, how virtual env is different - not `3SjGFAFe` but `j7smKuLy`.
**I didn't create this environment.** It was created automatically by Poetry for reason unknown to me. 

When I try to run the command `poetry env use C:\Users\USER\AppData\Local\pypoetry\Cache\virtualenvs\wapatools-3SjGFAFe-py3.10\Scripts\python.exe`, it returns `Using virtualenv: C:\Users\USER\AppData\Local\pypoetry\Cache\virtualenvs\wapatools-j7smKuLy-py3.10` - again using the newly created env instead of the correct one.

So, in effect, I have conflicting settings (IDE vs Poetry) that I cannot resolve. 

What is happening here? **What could have triggered the unwarranted env change?** Is this curable? If yes: how?

**Comment by dimbleby** [comment]
You have misunderstood what `poetry env use some\environment\python` does.  

- it does not activate that environment
- what it does is create or activate an environment, copying the python that you specified as the interpreter in the new environment

if there's some documentation somewhere that you found confusing then I expect a merge request making it clearer would be welcome

> I have conflicting settings (IDE vs Poetry) that I cannot resolve.

just reconfigure pycharm?

please close

**Comment by dimbleby** [comment]
poetry is using the correct environment.  The question you should be asking is: how did the old incorrect environment come into being?  You haven't given any clues about that but probably it was associated with a project in a different path, perhaps you have moved your pyproject.toml around.

Alternatively if you already have an environment around that you want poetry to use: just activate that environment before you do anything with poetry.

**Comment by dimbleby** [comment]
I suppose what you mean is "thank you, that has resolved my problem"

if so, please close

**Comment by betterthanever2** [comment]
Is that supposed to be a joke?

**Comment by betterthanever2** [comment]
I mean, the main issue is that this happened without any indication, or any way to figure out what is going on. I suppose, you don't consider that an issue?

**Comment by betterthanever2** [comment]
Can you point me to the page in the docs where this behavior is mentioned?

**Comment by dimbleby** [comment]
Very possible that the docs are confusing - if you read them and were confused then that's a data point!

Once again, a merge request making them clearer would likely be welcome

**Comment by betterthanever2** [comment]
Merge request? I don't mind contributing, but in order to explain anything, one must first understand it, and if you think that after your assistance I understand how poetry.toml is connected to a virtual env, you are sorely mistaken

**Comment by dimbleby** [comment]
Things which I think we have cleared up in this thread:

- `poetry env use` doesn't do what you first thought
- poetry's made up venv names are derived from the location of the pyproject.toml (and also the project name; though that much is plain for all to see)

if you didn't find or understand those things from the documentation, then clearing either or both of them up could be a useful contribution

**Comment by betterthanever2** [comment]
> poetry's made up venv names are derived from the location of the pyproject.toml 

You cleared that, just now. This wasn't mentioned before, nor was it clear or obvious.

But then it doesn't make motivation behind this any clearer. Why would you make the relation active in this way? Every technical decision is made for a reason, I'm just trying to understand what it is in this case.

**Comment by dimbleby** [comment]
in your rewrite of my answer you wrote yourself 

> "Env path is directly associated with the pyproject.toml file location"

so I cannot agree that this is new information!

As for the motivation: well, I guess you gotta do something.  If all you used was the project name, then that would cause clashes for folk who for whatever reason have two copies of a project on their machine at the same time...

**Comment by betterthanever2** [comment]
> so I cannot agree that this is new information!

The nature of the association is new information.

> If all you used was the project name, then that would cause clashes for folk who for whatever reason have two copies of a project on their machine at the same time...

Gotta say, seems like a very odd usecase. 

Also: it's one thing to base the name of the env on some combination of things, and it is quite another to make it so that the change of one of these things leads to creating a new env instead of, say, updating the association.
