### ISSUE TITLE
Poetry adds @HEAD to the repo URL which is not a recognized branch

### ISSUE THREAD

**Issue by im-n1** [python-poetry/poetry#8272]
I tried to use git repo as a repo URL based on your website:

![image](https://github.com/python-poetry/poetry/assets/198654/d1aa6708-69e4-4177-ae64-46e732413776)

- I just changed the repo URL and didn't specify a branch nor tag or rev. Just URL
- I exported the rrequirements to a requirements file as `poetry export --without-hashes --with dev`
- Poetry somehow did add `@HEAD` to the end of repo URL
- when installing dependencies with pip I get following error

```
Collecting rug@ git+https://github.com/im-n1/rug.git@HEAD (from -r requirements_dev (line 112))
  Cloning https://github.com/im-n1/rug.git (to revision HEAD) to /tmp/pip-install-2_8a4skp/rug_3b17696bf42840808211df49ea157c0f
  Running command git clone --filter=blob:none --quiet https://github.com/im-n1/rug.git /tmp/pip-install-2_8a4skp/rug_3b17696bf42840808211df49ea157c0f
  Running command git checkout -b HEAD --track origin/HEAD
  fatal: 'HEAD' is not a valid branch name
  error: subprocess-exited-with-error

  × git checkout -b HEAD --track origin/HEAD did not run successfully.
  │ exit code: 128
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git checkout -b HEAD --track origin/HEAD did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

- **Poetry version**: 1.5.1
- **Python version**:  3.11
- **OS version and name**:  Debian GNU/Linux trixie/sid
- **pyproject.toml**:  the critical line: `rug = { git = "https://github.com/im-n1/rug.git" }`

**Comment by im-n1** [comment]
Solution: specify a brach like

```
rug = { git = "https://github.com/im-n1/rug.git", branch = "master" }
```

**Comment by dimbleby** [comment]
wrong repository, and duplicate https://github.com/python-poetry/poetry-plugin-export/issues/172 - please close
