### ISSUE TITLE
Project name with dots generates subfolders

### ISSUE THREAD

**Issue by pgierz** [python-poetry/poetry#8277]
Hi there,

is this desired behaviour, or did I just not read the handbook:

```console
$ poetry new "my-cool-app.woohoo.xyz
```

Results in:

```console
$ ls -R my-cool-app.woohoo.xyz
 my_cool_app   pyproject.toml   README.md   tests

my-cool-app.woohoo.xyz/my_cool_app:
 woohoo

my-cool-app.woohoo.xyz/my_cool_app/woohoo:
 xyz

my-cool-app.woohoo.xyz/my_cool_app/woohoo/xyz:
 __init__.py

my-cool-app.woohoo.xyz/tests:
 __init__.py
```

In fairness, I might have an unforeseen use case here: I just want to name my project in the same way as it would ultimately appear online, and generating a bunch of nested sub-folders is not really what I want...

**Comment by dimbleby** [comment]
probably deliberate: looks like project names with dots in them are treated as namespace package

**Comment by finswimmer** [comment]
Hey @pgierz,

yes, this behavior is expected :smile: 

fin swimmer
