### ISSUE TITLE
Bug: Env use command need python executable to be in path

### ISSUE THREAD

**Issue by jgirardet** [python-poetry/poetry#828]
Poetry 1.0.0a2

- [ x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x ] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [ x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

```
poetry env use ~/.pyenv/versions/3.5.5/bin/python
Using virtualenv: /home/jimmy/.cache/pypoetry/virtualenvs/aaaaa-tiAQZfmi-py3.5
```
It creates the virtualenv and set the envs.toml file as well.

```
poetry env use 3.5 -vvv
pyenv: python3.5: command not found

The `python3.5' command exists in these Python versions:
  3.5.5


[EnvCommandError]
Command python3.5 -c "import sys; print('.'.join([str(s) for s in sys.version_info[:3]]))" errored with the following output: 


Traceback (most recent call last):
  File "/home/jimmy/.poetry/lib/poetry/_vendor/py3.7/clikit/console_application.py", line 131, in run
    status_code = command.handle(parsed_args, io)
  File "/home/jimmy/.poetry/lib/poetry/_vendor/py3.7/clikit/api/command/command.py", line 112, in handle
    status_code = self._do_handle(args, io)
  File "/home/jimmy/.poetry/lib/poetry/_vendor/py3.7/clikit/api/command/command.py", line 160, in _do_handle
    return getattr(handler, handler_method)(args, io, self)
  File "/home/jimmy/.poetry/lib/poetry/_vendor/py3.7/cleo/commands/command.py", line 92, in wrap_handle
    return self.handle()
  File "/home/jimmy/.poetry/lib/poetry/console/commands/env/use.py", line 23, in handle
    env = manager.activate(self.argument('python'), poetry.file.parent, self._io)
  File "/home/jimmy/.poetry/lib/poetry/utils/env.py", line 174, in activate
    raise EnvCommandError(e)
```

it fails because it can't find the executable of python3.5 in path since pyenv .python-version is not yet set.
I think it's really a bug since the `remove` commands fails as well.

**Comment by jgirardet** [comment]
some more things : 
`poetry env remove 3.5` fails but poetry `poetry env remove myproject-AdezDZ-py3.5` works.
The second one is good but makes the api very inconsistent depending the way you call it.

My suggestion to make it work :
if `poetry env use/remove 3.5` fails due to missing interpreter in path, it falls back looking for `myproject-ADZada-3.5`. it keeps the api reproducible and consistent.

I will add that since `poetry env remove myproject-FZEfezf-py3.6` works we should have `poetry env use myproject-FZEfezf-py3.6` works too. 

And finally maybe auto-completion could help dealing with all those things.

ps: env command is great by the way :-)

**Comment by peter-schmidbauer** [comment]
I ran into the same issue today. Even worse, for me the command `poetry env use python3.8` seemed to work and didn't complain, but when I went on to `poetry install` it didn't work because the virtual environment it created was incomplete (it only contained a python executable, but no pip or anything else). `poetry env info` also said "Valid: False". 

When I tried to switch back to 3.7 using `poetry env use python3.7` or any other variation of that it would always fail with the same error as @jgirardet. 

The poetry env commands are very poorly documented and behave in unexpected ways currently. They really should be overhauled for a 1.0 release, as it is part of the public interface and a really frustrating experience at the moment.

**Comment by thejohnfreeman** [comment]
I'm using Poetry 1.0.3 and experience the same problem.

```
$ poetry env use 3.7
...
$ poetry env info

Virtualenv
Python:         3.7.6
Implementation: CPython
Path:           /root/.cache/pypoetry/virtualenvs/xpring-Lrgkzala-py3.7
Valid:          False

System
Platform: linux
OS:       posix
Python:   /opt/python/3.7-dev
```

Any further poetry commands recreate the environment.

**Comment by finswimmer** [comment]
Seems to be no problem with the current release (1.1.7).

**Comment by NeilGirdhar** [comment]
Still a problem for me with the current release 1.1.12
