### ISSUE TITLE
Allow `poetry init` to use different layouts, like `poetry new`

### ISSUE THREAD

**Issue by dolfandringa** [python-poetry/poetry#8282]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request
Currently, poetry new allows specifying different layouts, like the `src` layout, which creates the `src` and `tests` directory, and adjusts the pyproject.toml to install packages from the `src` directory. This feature is really useful for new packages, but can't be used with an existing directory, like `poetry init`. Adding the option `--src` option (or other layout options if they exist) to `init` would solve this. Now there are use-cases where neither `poetry new` and `poetry init` suffice because they require manual work that normally poetry takes care of.

### use-case

* create a new git repository
* clone the repository
* create a new poetry package with the src layout.

If I want a source layout (and hence use `--src` and need to use `poetry new`), this means I have to:
* `poetry new`
* `git init`
* `git remote add origin <upstream url>`
* `git checkout origin/main`
* `git commit -a`

in order to make sure poetry is the one making the new directories.
Or with `poetry init` , I can first clone the remote repo and then run `poetry init`, but now I need to manually make the `tests` and `src` directories and modify `pyproject.toml` to add `from = `. 

Its all totally doable manually, but in the spirit of `There should be one-- and preferably only one --obvious way to do it.` it seems unnecessary to have both `new` and `init` and then have features that are useful for both be exclusively to one or the other. Once layouts exist in `init`, the `new` command really doesn't seem necessary anymore.

**Comment by dimbleby** [comment]
per duplicate #8184 this already works, please close
