### ISSUE TITLE
Poetry does not check/keep the file permissions set on executable files during the build process

### ISSUE THREAD

**Issue by info-rchitect** [python-poetry/poetry#8284]
- **Poetry version**: 1.5.1
- **Python version**: 3.8.16
- **OS version and name**: Windows 10
- **pyproject.toml**: https://gist.github.com/info-rchitect/c3974170aadaad6db43afd8656f50c6e

- [ x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [ x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

I have set certain executable files in my repo as 755 via Git:

![image](https://github.com/python-poetry/poetry/assets/26782653/bac38227-4987-40da-8b18-4a1028ced45c)

When I run `poetry build` the files show up as 644 in the published tar and wheel.  This prevents me from using my repository on remote servers.

**Comment by dimbleby** [comment]
permissions are preserved when I try it, are you sure the problem isn't at the un-packing end?

you can dig into the code round about [here](https://github.com/python-poetry/poetry-core/blob/0cfe504aabed41074650e8e4d1d053e2ae524582/src/poetry/core/masonry/builders/wheel.py#L387-L400) if you really think this is on poetry's side

**Comment by info-rchitect** [comment]
> permissions are preserved when I try it, are you sure the problem isn't at the un-packing end?
> 
> you can dig into the code round about [here](https://github.com/python-poetry/poetry-core/blob/0cfe504aabed41074650e8e4d1d053e2ae524582/src/poetry/core/masonry/builders/wheel.py#L387-L400) if you really think this is on poetry's side

Thank you for the quick response.  The reason I am assuming it is on the `poetry` side is I just untar'd the published tar.gz file and see the permissions have changed.  Am I not checking this correctly?

**Comment by dimbleby** [comment]
well know that you know that this does work for someone else I expect you'll want to double-check your working and / or setup a complete and reproducible example.  (Your pyproject.toml is obviously not much help in this case)

eg perhaps the file in question wasn't actually executable at the time you built the wheel after all

**Comment by info-rchitect** [comment]
OK this seems to be a Windows issue.  It works when building from Linux.
