### ISSUE TITLE
POETRY INSTALL ERROR

### ISSUE THREAD

**Issue by cctv130** [python-poetry/poetry#8285]
at ~\AppData\Roaming\pypoetry\venv\lib\site-packages\poetry\installation\chef.py:147 in _prepare
      143│
      144│                 error = ChefBuildError("\n\n".join(message_parts))
      145│
      146│             if error is not None:
    → 147│                 raise error from None
      148│
      149│             return path
      150│
      151│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with distorm3 (3.5.2) not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pe
p517 "distorm3 (==3.5.2)"'.

**Comment by clintonroy** [comment]
Please follow the bug template. Please read the comments and try the command. Developers try really hard to provide useful error messages.
