### ISSUE TITLE
Mark tests using internet with @pytest.mark.network 

### ISSUE THREAD

**Issue by hrnciar** [python-poetry/poetry#8288]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request

Hello,

I am maintaining `poetry` in Fedora, recently we noticed the number of tests requiring internet access has increased. Since internet access is not enabled while building the package we need to skip those tests. I am just working on updating `poetry` to `1.5.1` and it looks like this:

~~~~
%pytest -k "not executor and \
   not test_chef and \
   not test_installer_with_pypi_repository and \
   not test_info_setup_complex and not test_info_setup_complex_pep517_legacy and \
   not test_info_setup_missing_mandatory_should_trigger_pep517 and \
   not test_builder_setup_generation_runs_with_pip_editable"
~~~~

It would be nice to mark those tests to be able to disable them all at once with `pytest -m "not network"`. 
I've already prepared PR for this, I'll open it soon.

**Comment by eamanu** [comment]
Hi @hrnciar

I maintain poetry in Debian. Leave this comment here to don't add no related code comment in PR. 

This is a very important feature. Are you still interested on it? I looked that you marked only 5 tests, I think that there are more  tests, but not sure.

**Comment by hrnciar** [comment]
Hi, thank you for pinging me. It seems like I left out some tests in `test_chef.py`. Please try to see if the updated PR works for you in Debian.  I am getting a successful build in Fedora when building without internet access.
