### ISSUE TITLE
Error message for missing `name` field is just the string `'name´` when running `poetry lock`

### ISSUE THREAD

**Issue by con-f-use** [python-poetry/poetry#8293]
Error message for a missing `name` field in `pyproject.toml` is just the string `'name'` printed to stderr when running `poetry lock`. See image below:

![image](https://github.com/python-poetry/poetry/assets/11145016/86d775dc-40cf-46b4-a68a-e4fe800d2584)

**Comment by dimbleby** [comment]
duplicate #8122 (which also suggests a fix, merge request welcome)

please close
