### ISSUE TITLE
Ability for Poetry to index arbitrary (non-PEP503) file servers (that host Python wheels) and ultimately accepting them as package sources

### ISSUE THREAD

**Issue by jaspersiebring** [python-poetry/poetry#8294]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Context and problem description
I'm currently trying to improve the packaging and distribution of [this Python package](https://github.com/jaspersiebring/libretro_finder). Its exact usecase is not all that important, only that the GUI portion of the tool requires `wxPython` and that everything is built and distributed with Poetry ([automated through Github Actions](https://github.com/jaspersiebring/libretro_finder/blob/2b68fbd897edbca0405ac58e40e73c4b0ace4615/.github/workflows/main.yml)). 

This GUI toolkit `wxPython` is currently not available as a prebuilt wheel for (any) Linux distribution on PYPI which ultimately means that running `pip install libretro-finder` (i.e. installing the package in question) on Linux distributions kickstarts a build of `wxPython` from source. This takes >45 minutes on default Github Actions runners (ubuntu-latest) and requires a ton of system dependencies, both of which negatively impact the adoption rate among Linux users (if any) for what should ideally be a very simple tool.

The fine people over at [wxPython](https://wxpython.org/pages/downloads/) do host a ton of prebuilt wheels for common Linux distributions on their [own Apache file server](https://extras.wxpython.org/wxPython4/extras/linux/gtk3/) (all of which appear to follow PEP427). It's just that it doesn't conform to PEP503 like PYPI does (if you can even say it like that) so Poetry can't accept it as a [package source](https://python-poetry.org/docs/repositories/#supported-package-sources).

Sure, you can manually add one of the URLs as an explicit package source but that would ultimately mean only "supporting" the Linux distribution associated with that build (leaving other distros to build from source). It also hardcodes a package dependency and dramatically limits the value of poetry's lockfile (or that of a modern package manager in general).

## Feature Request

In short, it would be very useful if there was a way for Poetry to index arbitrary file servers (that host Python wheels) and ultimately accept them as package sources.

##### Possible approach
At the risk of sounding naive, I currently imagine scraping an arbritrary file server to find all PEP427-conforming wheels and symlinking them to an in-memory representation of a Python package repository (index.html can then be computed with a templating engine). I then imagine dumping this to a versionable file and making it searchable by an API that follows PEP503 specs (at which point Poetry can accept it as a package source).

##### Why this is useful
Besides my `wxPython` example, there are a ton of file stores (often from scientific/academic sources) that contain perfectly valid Python wheels that go unused simply because they're not available on PYPI. 
 
A simple way to index these packages **locally** and making them available again through a modern package manager can be quite valuable. Hell, renewed interest in these packages might even motivate the maintainers to finally make them properly available on PYPI (reaching here but who knows).

## What I've done, tried and considered (besides this FR)

For the sake of completion, here are the other solutions I've considered for my `wxPython` dependency issue (please comment if you have any other suggestions):

_- Moving the GUI dependencies of my package to `extras` and building two versions (libretro-finder and libretro-finder[gui])_
Practical for the people who just want the CLI but ultimately doesn't solve anything for the GUI version (I also don't really want to maintain two versions on all platforms).

_- Bundle all your binary dependencies and release your package as a conda package_
Would solve the issue for `conda` users but is just not as widespread as pip (which I assume that most casual users will still use)
 
_- Add every .whl URL as a separate (supplemental) source_
Would make the pyproject.toml very difficult to maintain since even a single package release can have ~5 versions.

_- Mirror the file server and make it PEP503 conformant yourself_
Someone actually already made a tool for this called [simple503](https://github.com/repo-helper/simple503) but this assumes that you own the file server itself (or can otherwise configure it). Not only is that not the case for my `wxPython` example, mirroring a readily available source just to index them seems like a lot of effort if you consider the required infrastructure/memory costs. I still want this feature to download from the original host

_- Cache build artifacts_ 
Already implemented with Github Actions' `actions/cache`. Dramatically speeds up builds as wxPython no longer has to be rebuild if poetry.lock doesn't change. Doesn't solve anything for people installing `libretro-finder` through `pip`/`poetry` though (naturally).

## Continuation
First and foremost, I would love to hear you guys' thoughts on this and whether this is the right approach to take. I'm not completely sure if this actually aligns with the community's needs or whether it even fits within the scope of Poetry but curious to find that out.

**Comment by dimbleby** [comment]
The wxpython post that you link explains why they can't make those wheels accessible in a pip-friendly way: the available platform tags are not expressive enough for them to be able to say which wheels go on which platforms.  

Assuming that they are right, that means that what you propose simply can't work.  poetry (like pip) would not be able to choose the right wheels based on platform markers.

If there are examples other than wxpython where this would work: much better to go raise issues against those projects and encourage them to index their repositories.  Let's not build poetry-specials, let's have repositories that can be used by poetry and pip and pdm and pipenv and all the rest.

**Comment by Secrus** [comment]
Exactly what @dimbleby wrote. We don't want to promote non-standard ways and build special handling for every available repository-like server.

**Comment by jaspersiebring** [comment]
Understood, thanks for the response.
