### ISSUE TITLE
Poetry insists on optional property

### ISSUE THREAD

**Issue by ashemedai** [python-poetry/poetry#8299]
- **Poetry version**: 1.5.1
- **Python version**: 3.11.4 (due to this bug a `poetry debug info` from the project directory won't work)
- **OS version and name**: Debian 12 on WSL2
- **pyproject.toml**: N/A

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
The PyPA [Python Packaging User Guide states](https://packaging.python.org/en/latest/specifications/declaring-project-metadata/) on declaring project metadata the following:

> The only keys required to be statically defined are:
>
> - name
>
> The keys which are required but may be specified either statically or listed as dynamic are:
>
> - version
>
> All other keys are considered optional and may be specified statically, listed as dynamic, or left unspecified.

So only `name` and `version` are required to be defined in `pyproject.toml`. However, Poetry 1.5.1 currently gives me the following:

```
The Poetry configuration is invalid:
  - 'authors' is a required property
```

This is, of course, at odds with the PyPA specifications.

**Comment by Secrus** [comment]
We don't conform to metadata spec yet. See #3332

**Comment by ashemedai** [comment]
@Secrus D'oh, mentally made `[tool.poetry]` equivalent to the PEP621/PyPA spec's `[project]`. My bad.

**Comment by 0xallie** [comment]
> We don't conform to metadata spec yet. See #3332

That doesn't mean you have to require the authors field, seems like a quite simple change to make. I could even make a PR if desired.

It has always bothered me, because I have some private projects where I don't put any author for safety reasons. At least `authors = []` works.
