### ISSUE TITLE
EXFAT a no go with Poetry and WSL2

### ISSUE THREAD

**Issue by pinballelectronica** [python-poetry/poetry#8306]
Similar/same problem as with FAT32.  
Wrenched on it for an hour and decided to install to a non EXFAT/FAT32 drive (NTFS) and it worked perfectly.
WSL2/ Ubuntu 22.04
Poetry 1.5.2 I think
PY 3.11.4

[Errno 1] Operation not permitted: '/usr/bin/python3' -> '/mnt/g/FOO/.venv/bin/python'

**Comment by dimbleby** [comment]
I don't see any poetry issue here - you've just set things up so that there's something unhelpful about the permissions on your filesystem.

What change do you hope to see in this repository?

If none, please close.

**Comment by pinballelectronica** [comment]
Good chat.
