### ISSUE TITLE
Build package from dynamically created directory via custom build.py

### ISSUE THREAD

**Issue by rragundez** [python-poetry/poetry#8312]
- **Poetry version**: 1.5.1
- **Python version**: 3.10
- **OS version and name**: macOS 13.5

- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

I have a custom build section by using the following config in my `pyproject.toml`

```[tool.poetry.build]
generate-setup-file = false
script = "build.py"
```

The `build.py` script dynamically creates my package in a dynamically created directory, let's say `my_real_package/` (does not exist at the moment of executing `poetry build`).  In my  `pyproject.toml` I have

```
[tool.poetry]
packages = [{include = "my_real_package"}]
```
Then when executing `poetry build` I am shown the error `.../my_real_package does not contain any element` at the start, because the `my_real_package` is created during the build and is not present at the start. 

I tested and if I change `packages = [{include = "package"}]` (this directory exists as a package), run the build so that `my_real_package` is created and then change back `packages = [{include = "my_real_package"}]` and run again `poetry build`, it works.
So this tells me that updating to a warning the error for special cases (like when there is a custom build script) `.../my_real_package does not contain any element` will make everything work with a single `poetry build` command where I keep `packages = [{include = "my_real_package"}]` and `my_real_package` is dynamically created by my `build.py` script.

**Comment by rragundez** [comment]
I am trying to bring poetry and best practices with pyproject.toml into the new upcoming version of the popular Keras package. But there is this last missing piece I need, where the package to build is created dynamically via a script.

https://github.com/rragundez/keras-core/pull/1

**Comment by radoering** [comment]
I suppose you have to distinguish between building an sdist and a wheel. By default, poetry will build both formats. You can just create one of both by providing the `format` option.

When building an sdist, the build script is not executed so that it makes sense that the command fails. Maybe, you have to change your include to
```
[tool.poetry]
packages = [{include = "my_real_package", format = "wheel"}]
```

When building a wheel, the [code](https://github.com/python-poetry/poetry-core/blob/c3fea062292b47e277a1a54df10696c6a004638e/src/poetry/core/masonry/builders/wheel.py#L121-L123) looks like the build script will be executed before modules are copied.

Does `poetry build -f wheel` fails, too?

**Comment by rragundez** [comment]
Yes, still fails. 
<img width="816" alt="image" src="https://github.com/python-poetry/poetry/assets/16643700/72374b8c-afe4-44ff-bfd8-748c81e233f9">

Looking into the code I find that the reason is:

The Builder base class instantiation creates a `[Module](https://github.com/python-poetry/poetry-core/blob/bb0236f1bb011284f4107166988205798f91ea49/src/poetry/core/masonry/builders/builder.py#L85)` which in turn instantiates a `[PackageInclude](https://github.com/python-poetry/poetry-core/blob/bb0236f1bb011284f4107166988205798f91ea49/src/poetry/core/masonry/utils/module.py#L79)`  which calls `[check_elements](https://github.com/python-poetry/poetry-core/blob/bb0236f1bb011284f4107166988205798f91ea49/src/poetry/core/masonry/utils/package_include.py#L29)` which checks for the `package includes directory`.

Not sure how to go about it, or perhaps I am missing some option or way of doing this.

any further ideas @radoering

**Comment by radoering** [comment]
It seems you are right. So the question is whether we can postpone the creation of the module. At first glance, it looks like the module is only used after executing the build script (at least for the WheelBuilder) so it should be possible.

**Comment by radoering** [comment]
Go ahead if you like. It may be as simple as replacing `_module` with a `cached_property`. If all existing tests still pass and you are able to add a test that fails without your change (and passes with it), it should be fine.

**Comment by rragundez** [comment]
It is not entirely obvious to me how a `cached_property` will help here but happy to give it a go. Thanks for the hint.

**Comment by radoering** [comment]
Currently, `_module` is initialized in the `__init__` (and not set elsewhere). With a `cached_property` we can postpone the initialization until it is required. So replacing

```
def __init__(...):
    self._module = Module(
        self._package.name,
        self._path.as_posix(),
        packages=packages,
        includes=includes,
    )
```

with 

```
@cached_property
def _module:
    return Module(
        self._package.name,
        self._path.as_posix(),
        packages=packages,
        includes=includes,
    )
```

will initialize `_module` on first access.

**Comment by rragundez** [comment]
@radoering please have a look at https://github.com/python-poetry/poetry-core/pull/629

**Comment by rragundez** [comment]
Closed by https://github.com/python-poetry/poetry-core/pull/629
