### ISSUE TITLE
When updating single dependency, all binary files of all dependencies are downloaded

### ISSUE THREAD

**Issue by Vorobeyko** [python-poetry/poetry#8315]
- **Poetry version**: 1.5.1
- **Python version**: 3.10.4
- **OS version and name**: macos
- **pyproject.toml**: 

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

Hi! I have a problem with update single dependency.

When i want to update only 1 dependency, for example `poetry update pytest` I`m starting to wait a long time for all the binaries of other dependencies to load

For example:
I called `poetry update ozwhc`
<img width="1274" alt="image" src="https://github.com/python-poetry/poetry/assets/11293201/09c9d139-a48f-4eac-b47e-94f6112c6b72">

And i got:
- 268s waiting for download
- downloaded all binaries.

But i need to update only  1 dependency.

Can you help with it?

**Comment by dimbleby** [comment]
or possibly poetry is downloading these files to read their metadata ie what has dependencies on what

If so then still there is nothing to be done: but this information is cached so it will be faster next time

**Comment by Vorobeyko** [comment]
its sad, because sometimes it spend a lot of time(((
