### ISSUE TITLE
Poetry includes git-ignored files in build.

### ISSUE THREAD

**Issue by elongl** [python-poetry/poetry#8316]
- **Poetry version**: Poetry (version 1.5.1)
- **Python version**: Python:  3.9.6
- **OS version and name**: macOS Ventura
- **[pyproject.toml](https://github.com/elementary-data/elementary/blob/master/pyproject.toml)**

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

We're using a tool called `dbt` within our Python package and it has a [package management](https://docs.getdbt.com/docs/build/packages) system. Packages are stored in a directory called `dbt_packages` and they're [git-ignored](https://github.com/elementary-data/elementary/blob/327ceb1844a7e375a38590c1cb1baa4fc47cbda2/elementary/monitor/dbt_project/.gitignore#L3-L4) in our repository. However, when running `poetry build`, it seems to still be included in the final build and I don't understand why because according to the docs:

> If a VCS is being used for a package, the exclude field will be seeded with the VCS’ ignore settings (.gitignore for git for example).

Here's the evidence:

```sh
(clean) ☁  elementary [master] gst
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean

# Note that dbt_packages is not tracked.

(clean) ☁  elementary [master] poetry build
Building elementary-data (0.9.2)
  - Building sdist
  - Built elementary_data-0.9.2.tar.gz
  - Building wheel
  - Built elementary_data-0.9.2-py3-none-any.whl

(clean) ☁  elementary [master] tar xvf dist/elementary_data-0.9.2.tar.gz 2>&1 | grep dbt_packages
x elementary_data-0.9.2/elementary/monitor/dbt_project/dbt_packages/elementary/.flake8
x elementary_data-0.9.2/elementary/monitor/dbt_project/dbt_packages/elementary/.git/FETCH_HEAD
x elementary_data-0.9.2/elementary/monitor/dbt_project/dbt_packages/elementary/.git/HEAD
x elementary_data-0.9.2/elementary/monitor/dbt_project/dbt_packages/elementary/.git/ORIG_HEAD
x elementary_data-0.9.2/elementary/monitor/dbt_project/dbt_packages/elementary/.git/config
x elementary_data-0.9.2/elementary/monitor/dbt_project/dbt_packages/elementary/.git/description
...

# dbt_packages is still included even though it's git-ignored.
```

I also tried moving the git-ignored records to the root of the repository but it still included them.
Why does this happen?
Thanks.

**Comment by dimbleby** [comment]
poetry asks git what it is ignoring, [here](https://github.com/python-poetry/poetry-core/blob/39e17d70941222e9818e6621cc76f99d31edb6ba/src/poetry/core/vcs/git.py#L326-L342)

you can check for yourself whether the files that you are seeing are included or not, either by putting some print statements in that code or something like:
```
git --git-dir .git --work-tree . ls-files --others -i --exclude-standard
```
from the top of your project

**Comment by elongl** [comment]
> poetry asks git what it is ignoring, [here](https://github.com/python-poetry/poetry-core/blob/39e17d70941222e9818e6621cc76f99d31edb6ba/src/poetry/core/vcs/git.py#L326-L342)
> 
> you can check for yourself whether the files that you are seeing are included or not, either by putting some print statements in that code or something like:
> 
> ```
> git --git-dir .git --work-tree . ls-files --others -i --exclude-standard
> ```
> 
> from the top of your project

@dimbleby 
Those files (`dbt_packages`) are ignored but are still included in my build:

```bash
☁  elementary [master] ⚡  git --git-dir .git --work-tree . ls-files --others -i --exclude-standard

elementary/monitor/dbt_project/dbt_packages/dbt_utils/.circleci/config.yml
elementary/monitor/dbt_project/dbt_packages/dbt_utils/.github/CODEOWNERS
elementary/monitor/dbt_project/dbt_packages/dbt_utils/.github/ISSUE_TEMPLATE/bug_report.md
elementary/monitor/dbt_project/dbt_packages/dbt_utils/.github/ISSUE_TEMPLATE/dbt_minor_release.md
elementary/monitor/dbt_project/dbt_packages/dbt_utils/.github/ISSUE_TEMPLATE/feature_request.md
elementary/monitor/dbt_project/dbt_packages/dbt_utils/.github/ISSUE_TEMPLATE/utils_minor_release.md
elementary/monitor/dbt_project/dbt_packages/dbt_utils/.github/pull_request_template.md
elementary/monitor/dbt_project/dbt_packages/dbt_utils/.gitignore
...
```

Why are they included?

**Comment by dimbleby** [comment]
I've shown you where the code is, please investigate this yourself.

**Comment by jameshilliard** [comment]
FYI I [fixed a bug](https://github.com/python-poetry/poetry-core/pull/611) that may be related to this. Try the latest poetry-core release and see if that fixes it.

**Comment by finswimmer** [comment]
Fixed by https://github.com/python-poetry/poetry-core/pull/611

**Comment by elongl** [comment]
> > Hi @jameshilliard @finswimmer, this still occurs to me on the latest release.
> > Essentially what happens is that I have a Poetry package in which there is a `.gitignore` not at the root, but rather one of the nested directories. Poetry still tries to include those files.
> 
> The fix was not released yet. This will be available in the next release

Got it, thanks a lot for updating.
1. Is there a planned released date, or a beta version I can use?
2. Also, here's my exact use-case as it's pretty weird and I want to make sure it's covered:

I have an API project (Poetry) and a Common package (also Poetry).
The API project installs the Common package using a `path` dependency.
The Common package has files that are git-ignored and Poetry currently tries to build them into the API project.
Would the fix also take into account the git-ignored files even though they're in the Common package and not the API project?

Thanks.

**Comment by elongl** [comment]
> > but rather one of the nested directories
> 
> Is the nested directory itself being entirely ignored by the project it is nested within? The purpose of [#611](https://github.com/python-poetry/poetry-core/pull/611) is to disable gitignore usage for cases when the nested directory is entirely ignored(as doing so would always result in an empty package).

The problem is that it is _not_ ignored but rather included when it shouldn't be.
