### ISSUE TITLE
Option to ignore venvs - improve isolation of poetry projects

### ISSUE THREAD

**Issue by jrosiek** [python-poetry/poetry#8318]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

### Summary
Configuration options to:
1. Reject usage of active venv (possibly with an option to override that behaviour through a command line option) AND/OR
2. Force creation of fresh isolated venv even if there is a venv already active (use active venv's base Python to create new venv)

### Motivation
Currently, even if `virtualenvs.create` is set to `true`, poetry will still use the active venv. This has undesired consequences:
1. poetry behavior is dependent on the environment it is running on (non-reproducible "builds")
2. leads to accidental installation of project dependencies into unrelated venvs.

Scenario when it is a problem: in organizations that have monolithic codebase and use plain `pip`, developers may rely on a single venv for the whole repository. This venv is often set as a global one (for example through `pyenv global`). With such setup it is very hard to incrementally introduce a tool like `poetry` without a coordinated effort. Poetry does not provide isolated environment and it's behavior may be accidentally influenced by the environment it is running in.

**Comment by dimbleby** [comment]
duplicate #4055
