### ISSUE TITLE
Installer does not work with Homebrew

### ISSUE THREAD

**Issue by DillonB07** [python-poetry/poetry#8321]
- **Poetry version**: 1.5.1
- **Python version**: 3.11.4
- **OS version and name**: macOS Monterey 12.6.8
- **pyproject.toml**: N/A

- [ ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below. - *Not applicable*

## Issue

I have Python 3.11.4 installed via Homebrew. This is available via `python` and `python3` in my terminal. However, the poetry install is searching for `/usr/local/lib/Python` or `/usr/lib/Python` which is not where my Python version is stored.

Attached is the error and log from running the recommended installer
```log
> curl -sSL https://install.python-poetry.org | python - -vvv
Retrieving Poetry metadata

# Welcome to Poetry!

This will download and install the latest version of Poetry,
a dependency and package manager for Python.

It will add the `poetry` command to Poetry's bin directory, located at:

/Users/dillonbarnes/.local/bin

You can uninstall at any time by executing this script with the --uninstall option,
and these changes will be reverted.

Installing Poetry (1.5.1): An error occurred. Removing partial environment.
Poetry installation failed.
See /Users/dillonbarnes/poetry-installer-error-misximsf.log for error logs.
```

```log
dyld[5485]: Library not loaded: '@loader_path/../Python'
  Referenced from: '/Users/dillonbarnes/Library/Application Support/pypoetry/venv/bin/python3.11'
  Reason: tried: '/Users/dillonbarnes/Library/Application Support/pypoetry/venv/bin/../Python' (no such file), '/usr/local/lib/Python' (no such file), '/usr/lib/Python' (no such file)

Traceback:

  File "<stdin>", line 923, in main
  File "<stdin>", line 562, in run
```

My suggestion for this is to use the python binary used when running the installer if possible.

My Python installation is at `/usr/local/bin/python3` and not `/usr/local/lib/Python` which seems to be hardcoded into the installer.

**Comment by dimbleby** [comment]
wrong repository, looks duplicate https://github.com/python-poetry/install.python-poetry.org/issues/24

**Comment by DillonB07** [comment]
Sorry, didn't realise it was a different repo and therefore only looked at the issues on this repo. Will try that, thanks!
