### ISSUE TITLE
Fetching release info from PyPI using the new API

### ISSUE THREAD

**Issue by bm371613** [python-poetry/poetry#8326]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request

Currently, Poetry uses the deprecated PyPI API to get release info from PyPI ([code](https://github.com/python-poetry/poetry/blob/eb74d6209ecda2840ea1c0c2375cb7f6485a39f9/src/poetry/repositories/pypi_repository.py#L129)).

This API returns metadata per release, not per artifact. With multiple artifacts in a release having different metadata, this causes missing dependencies, as in issues
- https://github.com/pytorch/pytorch/issues/104259
- https://github.com/pytorch/pytorch/issues/105731
- https://github.com/pytorch/pytorch/issues/100974
- https://github.com/python-poetry/poetry/issues/6409

[PEP-658](https://peps.python.org/pep-0658/) proposed a better API and PyPI implemented it in https://github.com/pypi/warehouse/pull/13649 

Now if Poetry switches to the new API, above mentioned issues should disappear with the next release of the library (like pytorch).

**Comment by Secrus** [comment]
This is already being worked on in #5509

**Comment by dimbleby** [comment]
> This is already being worked on in https://github.com/python-poetry/poetry/pull/5509

but not in a way that will deal with metadata-per-artifact, I assume.

I'd guess it's unlikely that poetry will ever support this in a meaningful way.

**Comment by Secrus** [comment]
Well, yeah, it's unlikely for us to switch to per-artifact metadata, since that would break the reproducible builds (unless we redo our locking mechanism completely).

**Comment by bm371613** [comment]
I have only recently discovered some details of Poetry-PyPI-pytorch interaction, so I may not see the full picture here, but my understanding is as follows:

Poetry wants to resolve dependencies for all systems and architectures, preferably without downloading too many wheels just for metadata and without relying on non-standardized mechanisms.

I may naively think that with metadata for all artifacts (including system/arch and dependencies) dependencies can be resolved.

> I'd guess it's unlikely that poetry will ever support this in a meaningful way.

> Well, yeah, it's unlikely for us to switch to per-artifact metadata, since that would break the reproducible builds (unless we redo our locking mechanism completely).

Do you mean it's
- an ill-posed problem in some way?
- out of scope for Poetry?
- too difficult?
- too difficult to be implemented soon?

Perhaps it's easy enough for simpler cases that would cover many problematic libraries?

**Comment by dimbleby** [comment]
I think it's quite infeasible to retro-fit per-artifact metadata onto poetry.  

People with better ideas are invited to make pull requests, but don't hold your breath!

**Comment by bm371613** [comment]
> I think it's quite infeasible to retro-fit per-artifact metadata onto poetry.
> 
> People with better ideas are invited to make pull requests, but don't hold your breath!

Let's consider what the possible solutions are, sticking to `torch` as the example library.

The reality we are dealing with is
- The user executes `poetry add torch` and hopes `import torch` works
- pytorch developers upload many wheels with different metadata for each release
- PyPI let's us fetch each artifact's metadata via the new-standard API
- PyPI also let's us fetch metadata of some (~random) artifact pretending to be the release's metadata via a non-standardized API the will probably be gone in the future
- poetry already has a dependency resolution mechanism that at some point determines metadata for a release (torch version), not artifact

Currently `(name, version) -> metadata` resolution required by the existing dependency resolution mechanism is implemented by querying the non-standardized API. This means metadata may come from an incompatible artifact and `import torch` fails.

As I understand, it is infeasible to consider all artifacts and resolve dependencies for all scenarios, ie. replacing `(name, version) -> metadata` resolution with `(name, version) -> list[metadata]` and generating a lock file that works on all (system, arch) combinations.

How about leaving the dependency resolution mechanism intact and implementing `(name, version) -> metadata` so that it works at least on the current (system, arch)? Instead of relying on PyPI to pick ~random metadata via the old API, poetry could fetch metadata for every release, drop those that don't match the current environment and then pick one.

Hopefully this wouldn't be that much work and would fix `poetry add torch` for most users without breaking anything.

What do you think?

**Comment by Secrus** [comment]
> > I think it's quite infeasible to retro-fit per-artifact metadata onto poetry.
> > People with better ideas are invited to make pull requests, but don't hold your breath!
> 
> Let's consider what the possible solutions are, sticking to `torch` as the example library.
> 
> The reality we are dealing with is
> 
> * The user executes `poetry add torch` and hopes `import torch` works
> * pytorch developers upload many wheels with different metadata for each release
> * PyPI let's us fetch each artifact's metadata via the new-standard API
> * PyPI also let's us fetch metadata of some (~random) artifact pretending to be the release's metadata via a non-standardized API that will probably be gone in the future
> * poetry already has a dependency resolution mechanism that at some point determines metadata for a release (torch version), not artifact
> 
> Currently `(name, version) -> metadata` resolution required by the existing dependency resolution mechanism is implemented by querying the non-standardized API. This means metadata may come from an incompatible artifact and `import torch` fails.
> 
> As I understand, it is infeasible to consider all artifacts and resolve dependencies for all scenarios, ie. replacing `(name, version) -> metadata` resolution with `(name, version) -> list[metadata]` and generating a lock file that works on all (system, arch) combinations.
> 
> How about leaving the dependency resolution mechanism intact and implementing `(name, version) -> metadata` so that it works at least on the current (system, arch)? Instead of relying on PyPI to pick ~random metadata via the old API, poetry could fetch metadata for every release, drop those that don't match the current environment and then pick one.
> 
> Hopefully this wouldn't be that much work and would fix `poetry add torch` for most users without breaking anything.
> 
> What do you think?

That would break our lock file since it would no longer be cross-platform. Personally, I'd rather see Pytorch implement proper markers on their dependencies instead of having some complex logic in their setup script. If current standards are not enough, PyTorch should work with PyPA to amend standards with new markers that allow them to express their needs properly.

**Comment by dimbleby** [comment]
if you only care about resolving dependencies for the current platform then `pip install foo` is a fine solution already.

**Comment by bm371613** [comment]
@Secrus @dimbleby  Thank you for your input. I will reference your comments in related pytorch discussions. I'm closing this issue.
