### ISSUE TITLE
Installing detectron2 errors out ("ModuleNotFoundError: No module named 'torch' even though torch is part of the environment)

### ISSUE THREAD

**Issue by ldorigo** [python-poetry/poetry#8330]
- **Poetry version**:  1.5.1
- **Python version**: 3.11.3
- **OS version and name**:  Archlinux 
- **pyproject.toml**:  https://gist.github.com/ldorigo/78c54ebf789474b4e445e1ee25665c93

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

I am trying to add Detectron2 (https://detectron2.readthedocs.io/en/latest/) to my project. I am using a very recent version of pytorch for other reasons, so I first installed a nightly build of torch/torchvision (see pyproject.toml), and am now trying to add detectron2 from this pull request https://github.com/facebookresearch/detectron2/pull/4868 :

```
poetry -vvv add git+https://github.com/johnnynunez/detectron2.git
```

I am getting the following output: https://gist.github.com/ldorigo/4bcc4b270cf24afbab3f9d20810c82a8

I am not sure whether this is an issue with Poetry or the upstream package, if so let me know and I will open an issue there.

**Comment by dimbleby** [comment]
also duplicate #3712, so please close it twice!

**Comment by ldorigo** [comment]
Sorry I missed that issue. Since apparently upstream Detectron2 https://github.com/facebookresearch/detectron2/pull/4234 does not want to fix the issue, is there anything that can be done to include detectron2 in a poetry project?

**Comment by dimbleby** [comment]
no

**Comment by radoering** [comment]
You can build wheels (with other means than poetry) and add them. (You probably need one wheel for each platform and python version you want to support.)
