### ISSUE TITLE
2-FA Error (cant use PyPI API Token)

### ISSUE THREAD

**Issue by 3verlaster** [python-poetry/poetry#8335]
- **Poetry version**:  1.5.1
- **Python version**: 3.8.10
- **OS version and name**: Windows 7
- **pyproject.toml**: -

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
When I tried to publish the project, poetry couldn't access the publish. Because I have two factor authentication enabled.
Before I used this command:
poetry publish --username ... --password ... --build
And then it says that I have 2-FA enabled on my account. I also created an API token on the PyPI site, and tried to substitute it for the password as the error said. But nothing happened. I did not find the use of the token API.
How can I publish a project?

**Comment by dimbleby** [comment]
https://python-poetry.org/docs/repositories/#configuring-credentials

please close

**Comment by 3verlaster** [comment]
thank you
