### ISSUE TITLE
Redundant prompt on slower shells (zsh)

### ISSUE THREAD

**Issue by rumbleFTW** [python-poetry/poetry#8337]
- **Poetry version**: 1.5.1
- **Python version**: 3.11.3
- **OS version and name**: Arch linux 6.4.11-arch1-1

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below. **N/A**

## Issue

This issue appears when I execute `poetry shell`. After the prompt  `Spawning shell within <path>`, an unintended prompt `emulate bash -c '. <path>` appears in my shell. I went through the code and noticed that this was unintended as the echo is set to false [`c.setecho(False)`]. This issue happens in my setup due to the slow response of my shell (`zsh`). When I disable all of my zsh plugins to improve the responsiveness of my shell, it does not appear.

![Screenshot from 2023-08-21 02-59-20](https://github.com/python-poetry/poetry/assets/85807431/faaed2e9-263e-4163-b635-bf31ef1eeaeb)

**Comment by tringwald** [comment]
For me, this happens on both `bash` and `zsh`. The additional output also persists for `zsh` if I deactivate plugins.

**Comment by rumbleFTW** [comment]
@tringwald I think your shell is slow. When I try deactivating all my `zsh` plugins, the redundant prompt is not shown.

Also, I'm pretty sure this is unintended because the pyexpect echo is set to false `c.setecho(False)`.

**Comment by abn** [comment]
I do not think this a poetry issue, without being able to reliably reproduce we cannot debug. If there is a fix that might help your case, feel free to raise a PR with the suggestion. Alternatively, raise a new issue with something we can reproduce - inside a container might work?

As right now there isn't much we can do here, closing.
