### ISSUE TITLE
Conditional dependency to other packages

### ISSUE THREAD

**Issue by doc0815** [python-poetry/poetry#8339]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
  - similar, but different: https://github.com/python-poetry/poetry/issues/868
- [x] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request
Thank you for providing an exceptional dependency resolution tool. I ❤️ it!

**I would like to ask if it would be possible to add a dependency of one package with a condition to another package.**

```
[tool.poetry.dependencies]
package_A = ">=1.0.0,<3.0.0"
package_B = { version = "^1.0", package_A = "^2.0" }
```

My concrete use case is the dependency to the package `pydantic`. The authors carved out some code from v1 to v2 into another package `pydantic-settings`, which depends on `pydantic` v2 (or greater). I would like to make my package dependent on both version of `pydantic`, but when I add `pydantic-settings` (without the conditional dependency), my package no longer supports v1 of `pydantic`.

Something similar already exists, if the condition is a Python version or a OS property:
https://python-poetry.org/docs/dependency-specification/#python-restricted-dependencies
https://python-poetry.org/docs/dependency-specification/#using-environment-markers

**Comment by Secrus** [comment]
This won't be possible, since there is no standard way to express it in package metadata markers (we translate to those on build time). See PEP 508 for more details on markers.
