### ISSUE TITLE
How can I specify differing sets of dependency extras for each of my project's extras?

### ISSUE THREAD

**Issue by kurtiss** [python-poetry/poetry#834]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Question
How can I specify differing sets of dependency extras for each of my project's extras? This is something that is relatively trivial to do with setup.py. To clarify, I would like to be able to specify the following dependency graph:

> myproject[feature-a] depends on [dependency-one, dependency-two[feature-a]]
> myproject[feature-b] depends on [dependency-one, dependency-two[feature-b]]

I'll propose a couple ways that pyproject.toml might model these graphs, but the core value of these examples is to highlight an apparent deficiency with the current model. 

1) By allowing dependency aliases that specify distinct sets of extras. For example:

```
[tool.poetry.dependencies]
…
dependency-two-a = { git = "git+ssh://git@company.githost.io/projects/dependency-two.git",optional = true,extras = ["feature-a"], provides="dependency-two" }
dependency-two-b = { git = "git+ssh://git@company.githost.io/projects/dependency-two.git",optional = true,extras = ["feature-b"], provides="dependency-two" }
…

[tool.poetry.extras]
feature-a = ["dependency-one", "dependency-two-a"]
feature-b = ["dependency-one", "dependency-two-b"]
```

2) By treating the set of extras in the dependencies section as a superset that can be further filtered down when the dependency is referenced in the extras section. For example:

```
[tool.poetry.dependencies]
…
dependency-two = { git = "git+ssh://git@company.githost.io/projects/dependency-two.git",optional = true,extras = ["feature-a", "feature-b"]}
…

[tool.poetry.extras]
feature-a = ["dependency-one", "dependency-two[feature-a]"]
feature-b = ["dependency-one", "dependency-two[feature-b]"]
```

Thanks for your time!

**Comment by kurtiss** [comment]
@sdispater Gently bumping this – is this use case compelling enough to warrant some attention?

**Comment by kurtiss** [comment]
Bumping again, because the issue is outstanding and marks a flaw in the way dependencies are modeled, preventing reasonable use of this application. Hope somebody can take a look at this.

**Comment by wshayes** [comment]
Looks like you can install multiple dependencies in a single set using the following approach:

```
poetry add -E api fastapi
poetry add -E api gunicorn
poetry add -E api uvicorn
```

resulting in the following changes to the pyproject.toml file:

```
fastapi = {version = "^0.61.0", extras = ["api"]}
gunicorn = {version = "^20.0.4", extras = ["api"]}
uvicorn = {version = "^0.11.8", extras = ["api"]}
```

But running `poetry update; poetry install -E API` doesn't work yet.

You need to add the following entry to the pyproject.toml file:

[tool.poetry.extras]
api = ["fastapi^0.61.0", "gunicorn^20.0.4", "uvicorn^0.11.8"]

and then `poetry update; poetry install -E API` works fine.

**Comment by micuda** [comment]
Thanks for creating this issue, @kurtiss. We have the same problem. I would prefer option (2) proposed by @kurtiss, because it feels more intuitive - this was the first thing I tried.

What do you think, @sdispater?


@wshayes you are describing a different use-case here.

**Comment by graingert** [comment]
I'm looking to port celery from setuptools to poetry and have this problem also

See https://github.com/python-poetry/poetry/discussions/4313

**Comment by Qsi1984** [comment]
I reported a possible solution using markers here: https://github.com/python-poetry/poetry/discussions/4313#discussioncomment-1757450.
Maybe this would be a (temporary) solution in your cases too.

**Comment by blaise17** [comment]
I have a subtly different use case, which I don't think works in solution 2 as is, but might work in solution 1 (though I do prefer the readability of solution 2). 
Specifically, I need the dependency WITHOUT extras to not be optional, but the dependency with extras to be optional and in one of my extras. (Obviously an extension of this would be for one or more of the extras for the dependency to not be optional, while one or more still are optional).

For example (NOT a suggested soltuion):
```
[tool.poetry.dependencies]
…
dependency-two = { version = "^1.2.0", provides = "dependency-two" }
dependency-two-a = {version = "^1.2.0", optional = true, extras = ["feature-a"], provides = "dependency-two" }
…

[tool.poetry.extras]
feature-a = ["dependency-one", "dependency-two-a"]
```

**Comment by sorasful** [comment]
Hi, do we have workarounds this ? 

We do have the same problem, we want to be able to specify extras that depends on each other to avoid redundancy but they are not getting installed.


Thanks!
