### ISSUE TITLE
Request to add poetry install --global to install to global environment

### ISSUE THREAD

**Issue by fritzb** [python-poetry/poetry#8343]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request
Please add a flag to install packages into global environment without of having to configure `poetry config virtualenvs.create false`

ie. 

`poetry install --global`

similar to

`pipenv install --system`

Main use case: Docker image build where virtual environment is not preferred over global installation.

**Comment by mattpeople** [comment]
> Docker image build where virtual environment is not preferred over global installation.

Why not keep everything in a local environment? Never install anything globally.

Using poetry environments inside docker works as expected.

```dockerfile
FROM python:3.11-slim

RUN pip install pip poetry -U

WORKDIR /usr/src

# Copy dependency setup
COPY pyproject.toml poetry.lock .

# install dependencies before the code copy so code updates don't trigger all deps being pulled every time
RUN poetry install --only main

# copy your code directory
COPY modulename modulename

# double install because poetry requires it to stop complaining about script commands now
# (may also require copying your README.md since poetry cares about it now too)
RUN poetry install

CMD ["poetry", "run", "my-server"]
```

**Comment by fritzb** [comment]
There are various reason, one of them is to load driver, as an example GPU driver.
I found a way, using environment variable `POETRY_VIRTUALENVS_CREATE=false`, and I'm closing this issue.

Example:

`POETRY_VIRTUALENVS_CREATE=false poetry install --only main --no-cache --no-interaction`

**Comment by dimbleby** [comment]
as you note, there is already a config option to do what you want.

making this easier is the opposite of the likely direction of travel - eg https://github.com/python-poetry/poetry/issues/6398 for more discussion - so yes, please close
