### ISSUE TITLE
ImportError: cannot import name 'decode' from 'poetry.core.utils.helpers' 

### ISSUE THREAD

**Issue by jcrada** [python-poetry/poetry#8349]
- **Poetry version**: 1.6.1
- **Python version**: 3.9.17
- **OS version and name**: macOS 13.2.1
- **pyproject.toml**: https://github.com/fuzzylite/pyfuzzylite/blob/development/pyproject.toml

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

```
 ImportError

  cannot import name 'decode' from 'poetry.core.utils.helpers' (/opt/hostedtoolcache/Python/3.9.17/x64/lib/python3.9/site-packages/poetry/core/utils/helpers.py)

  at /opt/hostedtoolcache/Python/3.9.17/x64/lib/python3.9/site-packages/poetry/core/masonry/builders/wheel.py:30 in <module>
       26│ from poetry.core.masonry.builders.sdist import SdistBuilder
       27│ from poetry.core.masonry.utils.helpers import distribution_name
       28│ from poetry.core.masonry.utils.helpers import normalize_file_permissions
       29│ from poetry.core.masonry.utils.package_include import PackageInclude
    →  30│ from poetry.core.utils.helpers import decode
       31│ from poetry.core.utils.helpers import temporary_directory
       32│ 
       33│ 
       34│ if TYPE_CHECKING:
```

See very verbose output here: https://github.com/fuzzylite/pyfuzzylite/actions/runs/5940500284/job/16109203669?pr=46

**Comment by dimbleby** [comment]
that's not what the code looks like any more as you can verify for yourself - https://github.com/python-poetry/poetry-core/blob/b111cd649f7e9d7ad01f2eab40691763d5058e7c/src/poetry/core/masonry/builders/wheel.py#L30

so you've somehow got an inconsistent installation.  Suggest uninstalling and try again

**Comment by jcrada** [comment]
That's funny because the latest version gets installed automatically in my github action and I have not configured any caching in the environment. Locally, it failed the first time after I did `poetry self update`

**Comment by dimbleby** [comment]
nevertheless the problem is clearly at your end and there's nothing that can be done here to help you.

https://github.com/python-poetry/poetry-core/pull/602 is the single MR that both removed the code that you can't find: and also removed the code that can't find it

**Comment by jcrada** [comment]
Ok. Thanks. Fixed by explicitly installing previous version 1.5.1.
