### ISSUE TITLE
Poetry can't find a matching version on a private Nexus repository

### ISSUE THREAD

**Issue by Loahrs** [python-poetry/poetry#8360]
- **Poetry version**: 1.6.1
- **Python version**: 3.9.17
- **OS version and name**: Windows 11/Ubuntu (tried it locally and from a CI-step)
- **pyproject.toml**: https://gist.github.com/Loahrs/e187ccb702b7ddc0fe09380608c9649c

- [ x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [ x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [ x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
I set up a private Nexus Server (3.59.0) and was able to publish a package of _my_project_ in a TeamCity build step via Poetry.
Now I want to add that package as a dependency to my other project. I added the private repository to my pyproject.toml and ran:

`poetry add --source nexus --group deployment <my_project> -vvv`

to add the dependency. This gives me an error: 

"Could not find a matching version of package <my_project>". 

With debug on the output looks like this:
```
Loading configuration file C:\Users\...\AppData\Roaming\pypoetry\config.toml
Adding repository nexus (http://<user>:<pwd>@<server>:<port>/repository/<repository>) and setting it as supplemental
Using virtualenv: <the virtual env>
Creating new session for <user>:<pwd>@<server>:<port>
[urllib3.connectionpool] Starting new HTTP connection (1): <server>:<port>
[urllib3.connectionpool] http://localhost:8081 "GET /repository/<repository>/<my_project>/ HTTP/1.1" 200 1837
Source (nexus): 0 packages found for <my_project> *

  Stack trace:

  9  ~\.local\pipx\venvs\poetry\lib\site-packages\cleo\application.py:327 in run
      325│ 
      326│             try:
    → 327│                 exit_code = self._run(io)
      328│             except BrokenPipeError:
      329│                 # If we are piped to another process, it may close early and send a

  8  ~\.local\pipx\venvs\poetry\lib\site-packages\poetry\console\application.py:190 in _run
      188│         self._load_plugins(io)
      189│
    → 190│         exit_code: int = super()._run(io)
      191│         return exit_code
      192│

  7  ~\.local\pipx\venvs\poetry\lib\site-packages\cleo\application.py:431 in _run
      429│             io.input.interactive(interactive)
      430│
    → 431│         exit_code = self._run_command(command, io)
      432│         self._running_command = None
      433│

  6  ~\.local\pipx\venvs\poetry\lib\site-packages\cleo\application.py:473 in _run_command
      471│ 
      472│         if error is not None:
    → 473│             raise error
      474│
      475│         return terminate_event.exit_code

  5  ~\.local\pipx\venvs\poetry\lib\site-packages\cleo\application.py:457 in _run_command
      455│ 
      456│             if command_event.command_should_run():
    → 457│                 exit_code = command.run(io)
      458│             else:
      459│                 exit_code = ConsoleCommandEvent.RETURN_CODE_DISABLED

  4  ~\.local\pipx\venvs\poetry\lib\site-packages\cleo\commands\base_command.py:119 in run
      117│         io.input.validate()
      118│
    → 119│         status_code = self.execute(io)
      120│
      121│         if status_code is None:

  3  ~\.local\pipx\venvs\poetry\lib\site-packages\cleo\commands\command.py:62 in execute
       60│ 
       61│         try:
    →  62│             return self.handle()
       63│         except KeyboardInterrupt:
       64│             return 1

  2  ~\.local\pipx\venvs\poetry\lib\site-packages\poetry\console\commands\add.py:160 in handle
      158│             return 0
      159│
    → 160│         requirements = self._determine_requirements(
      161│             packages,
      162│             allow_prereleases=self.option("allow-prereleases"),

  1  ~\.local\pipx\venvs\poetry\lib\site-packages\poetry\console\commands\init.py:381 in _determine_requirements
      379│             elif "version" not in requirement:
      380│                 # determine the best version automatically
    → 381│                 name, version = self._find_best_version_for_package(
      382│                     requirement["name"],
      383│                     allow_prereleases=allow_prereleases,

  ValueError

  Could not find a matching version of package <my_project>

  at ~\.local\pipx\venvs\poetry\lib\site-packages\poetry\console\commands\init.py:422 in _find_best_version_for_package
      418│         )
      419│
      420│         if not package:
      421│             # TODO: find similar
    → 422│             raise ValueError(f"Could not find a matching version of package {name}")
      423│
      424│         return package.pretty_name, f"^{package.version.to_string()}"
      425│
      426│     def _parse_requirements(self, requirements: list[str]) -> list[dict[str, Any]]:


```

I also tried adding the dependency manually, but that returns a similiar error. The credentials for the nexus server are fine. Without them Poetry returns with an authentication failure. 

Another thing worth mentioning is, that doing a pip install works:
`pip install --extra-index-url  http://<server>:<port>/repository/<repository>/<my_project>`
it will ask me for credentials and then installs my desired package.

Are there any known issues regarding Nexus? Have I missed some steps in the configuration?

**Comment by dimbleby** [comment]
I notice that in some places you have redacted the server and in others you have http://localhost:8081 - perhaps you've done something odd to cause this?

I'm sure poetry and nexus work fine together, there are lots of discussions in this tracker about details of nexus that would make no sense if it just didn't work.

otherwise: no known issues, please close

**Comment by Loahrs** [comment]
The localhost-thing was just an oversight on my part when redacting the urls. (Why did I even bother to redact localhost, lol?) 
After hours of trying it seems like I found the solution. 

In my pyproject.toml I defined the Nexus-url as:
`https://<server>:<port>/repository/<my repository>/` -> poetry can't find a matching package.

However, it works when I add "/simple" to the end of the url like so:
`https://<server>:<port>/repository/<my repository>/simple`

**Comment by dimbleby** [comment]
cool, please close
