### ISSUE TITLE
`poetry run` throws away the `--` pseudo-argument

### ISSUE THREAD

**Issue by Spiffyk** [python-poetry/poetry#8361]
- **Poetry version**: 1.6.1
- **Python version**: 3.11.3
- **OS version and name**: Manjaro Linux - testing branch (latest as of writing)
- **pyproject.toml**: https://gist.github.com/Spiffyk/89fbd214e6136849c1f23a2db0354650

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

When I do a `poetry run` that contains the `--` pseudo-argument, Poetry silently drops that argument (but keeps everything after it), making the script that I want to run misbehave. In the included gist, I made a simple script that demonstrates this.

When I run the script by itself, I get this:

```
$ ./argparse-thing.py sub3 asdf -- -a -b --cde
Namespace(foo='sub3', bar=['asdf'])
['-a', '-b', '--cde']
```

But when run through `poetry run`, I get this:

```
$ poetry run ./argparse-thing.py sub3 asdf -- -a -b --cde
usage: argparse-thing.py [-h] foo [bar ...]
argparse-thing.py: error: unrecognized arguments: -a -b --cde
```

I believe this is a defect that may make some scripts misbehave as they rely on the `--` pseudo-argument being present, as demonstrated. Would it be possible for `poetry` to not drop it?

**Comment by Spiffyk** [comment]
(Note: I am willing to make a patch myself, if there is interest in fixing this)

**Comment by dimbleby** [comment]
`poetry run -- ./argparse-thing.py sub3 asdf -- -a -b --cde`

**Comment by Spiffyk** [comment]
Oh, sorry about the dupe... it's pretty hard to find issues whose central part is just punctuation 😅
