### ISSUE TITLE
Poetry hangs on dependency resolution on Ubuntu 22.04

### ISSUE THREAD

**Issue by econeale** [python-poetry/poetry#8364]
- **Poetry version**: 1.6.1
- **Python version**: 3.10.12
- **OS version and name**: Ubuntu 22.04
- **pyproject.toml**: [pyproject.toml](https://gist.github.com/econeale/f03e4d0e5330979409a613e3d7bf2b60)

- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
Poetry hangs on dependency resolution on Ubuntu 22.04. The same configuration executes correctly on MacOS.

I thought this may be related to IPV6 issues (e.g., https://blog.dmac.tech/posts/IPv6-issues-with-python-package-managers/) but disabling IPV6 system wide has no impact and installing via `python3 -m pip install xxx` completes successfully in reasonable amounts of time. 

Checking the cache revealed that `~/.cache/pypoetry` didn't exist and `poetry cache list` had no entries.  

This looks like a dependency solving problem with the dependency solving library but I don't know how to diagnose any further than that. Any suggestions would be appreciated! 

```shell
$ poetry config --list
cache-dir = "/home/neale/.cache/pypoetry"
experimental.system-git-client = false
installer.max-workers = null
installer.modern-installation = true
installer.no-binary = null
installer.parallel = false
virtualenvs.create = true
virtualenvs.in-project = true
virtualenvs.options.always-copy = false
virtualenvs.options.no-pip = false
virtualenvs.options.no-setuptools = false
virtualenvs.options.system-site-packages = true
virtualenvs.path = "{cache-dir}/virtualenvs"  # /home/neale/.cache/pypoetry/virtualenvs
virtualenvs.prefer-active-python = true
virtualenvs.prompt = "{project_name}-py{python_version}"


$ poetry install -vvv --with dev 
Loading configuration file /home/neale/.config/pypoetry/config.toml
Loading configuration file /home/neale/imager/poetry.toml
Trying to detect current active python executable as specified in the config.
Unable to detect the current active python executable. Falling back to default.
Using virtualenv: /home/neale/imager/.venv
Updating dependencies
Resolving dependencies...
   1: fact: imager is 0.0.0
   1: derived: imager
   1: fact: imager depends on pygobject (^3.44.1)
   1: fact: imager depends on pydantic-settings (^2.0.2)
   1: fact: imager depends on pyyaml (^6.0.1)
   1: fact: imager depends on opencv-python (^4.8.0.74)
   1: fact: imager depends on pyserial (^3.5)
   1: fact: imager depends on black (^23.7.0)
   1: fact: imager depends on mypy (^1.2)
   1: fact: imager depends on ruff (^0.0.282)
   1: fact: imager depends on pytest (^7.4.0)
   1: fact: imager depends on types-pyyaml (^6.0.12.11)
   1: fact: imager depends on licensecheck (2023.3)
   1: fact: imager depends on lxml (^4.9.3)
   1: fact: imager depends on imgaug (^0.4.0)
   1: fact: imager depends on types-requests (^2.31.0.2)
   1: selecting panel-quality-imager (0.0.0)
   1: derived: types-requests (>=2.31.0.2,<3.0.0.0)
   1: derived: imgaug (>=0.4.0,<0.5.0)
   1: derived: lxml (>=4.9.3,<5.0.0)
   1: derived: licensecheck (==2023.3)
   1: derived: types-pyyaml (>=6.0.12.11,<7.0.0.0)
   1: derived: pytest (>=7.4.0,<8.0.0)
   1: derived: ruff (>=0.0.282,<0.0.283)
   1: derived: mypy (>=1.2,<2.0)
   1: derived: black (>=23.7.0,<24.0.0)
   1: derived: pyserial (>=3.5,<4.0)
   1: derived: opencv-python (>=4.8.0.74,<5.0.0.0)
   1: derived: pyyaml (>=6.0.1,<7.0.0)
   1: derived: pydantic-settings (>=2.0.2,<3.0.0)
   1: derived: pygobject (>=3.44.1,<4.0.0)
[keyring.backend] Loading KWallet
[keyring.backend] Loading SecretService
[keyring.backend] Loading Windows
[keyring.backend] Loading chainer
[keyring.backend] Loading libsecret
[keyring.backend] Loading macOS
```

**Comment by econeale** [comment]
Looks like the GNOME Keyring wasn't unlocked and so was hanging on that -_- Unlocking the keyring made Poetry work as expected.

**Comment by keithbentrup** [comment]
Thank you! So glad I found this. I have a ubuntu 22.04 server that I only ever ssh into. I couldn't figure out what was happening. I updated/reinstalled pyenv, poetry, etc. There were no error messages, cache, etc.  Then I read this, and uninstalled gnome keyring - worked immediately.
