### ISSUE TITLE
Poetry git dependencies on AWS CodeCommit not working with SSO

### ISSUE THREAD

**Issue by Nicktron** [python-poetry/poetry#8367]
I'm using poetry as my dependency manager for my python project, I've integrated external dependencies stored in a Git repository hosted on AWS CodeCommit. Since we changed our user management in AWS to SSO I can't use the git dependencies in poetry anymore.

To specify these dependencies in my 'pyproject.toml' file I used the given format explained in the [documentation](https://python-poetry.org/docs/dependency-specification/).

```
[tool.poetry.dependencies]
python = "^3.10"
pandas = "^2.0.3"
mylib = {git = "https://git-codecommit.eu-central-1.amazonaws.com/v1/repos/mylib.git"}
```
This approach worked fine.

However, we changed our user management in AWS to SSO (Identity Center) and I needed to use the git extension ['git-remote-codecommit'](https://pypi.org/project/git-remote-codecommit/) to communicate with my git repos in AWS CodeCommit. But now I’m unable to integrate these external dependencies within Poetry. The heart of the issue lies in the necessity to modify the method by which I invoke and interact with the git repository.

I tried the following:

```
[tool.poetry.dependencies]
python = "^3.10"
pandas = "^2.0.3"
mylib = {git = "codecommit://my_profile@mylib.git"}
```
I would be grateful for any assistance.

**Comment by dimbleby** [comment]
if you have made command line git work you could try https://python-poetry.org/docs/configuration#experimentalsystem-git-client; though per "experimental" I wouldn't rely on that lasting forever

if that doesn't work you're probably out of options

**Comment by abn** [comment]
As this is not supported via dulwich and the best option is to go via the system git client route.

Also note that using that url will likely yield non-compliant metadata for your packages as `codecommit` protocol is not a standard protocol.
