### ISSUE TITLE
Unable to find dependency solution for airflow + dbt

### ISSUE THREAD

**Issue by yucer** [python-poetry/poetry#8372]
- **Poetry version**: 1.6.1
- **Python version**: 3.10.12
- **OS version and name**: Linux Mint 21.2
- **pyproject.toml**: failing [pyproject.toml](https://gist.github.com/yucer/cd30d29b05894cb2698e3a2a693a2248) (it is the one resulting from `poetry init --no-interaction`)

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] No exception occurs when executing a command.

## Issue

I was following the initialization steps for [this article](https://medium.com/@asuarezaceves/streamlined-data-pipelines-orchestrating-dbt-transformations-with-airflow-and-cosmos-visualizing-85a200ffb6df):

```
## create project directory
mkdir airflow-dbt
cd airflow-dbt

## use poetry to initialize the project and manage our dependencies
pip3 install poetry
poetry init --no-interaction

## install our dependencies (Create our virtualenv through poetry)
poetry add apache-airflow apache-airflow-providers-postgres dbt-postgres pandas astronomer-cosmos
```

and poetry failed to find a solution for the dependencies:
```

Using version ^2.7.0 for apache-airflow
Using version ^5.6.0 for apache-airflow-providers-postgres
Using version ^1.6.1 for dbt-postgres
Using version ^2.0.3 for pandas
Using version ^1.0.5 for astronomer-cosmos

Updating dependencies
Resolving dependencies... (9.7s)

Because no versions of dbt-postgres match >1.6.1,<1.7.0b1 || >1.7.0b1,<2.0.0
 and dbt-postgres (1.7.0b1) depends on dbt-core (1.7.0b1), dbt-postgres (>1.6.1,<2.0.0) requires dbt-core (1.7.0b1).
And because dbt-core (1.7.0b1) depends on dbt-semantic-interfaces (>=0.2.0,<0.3.0), dbt-postgres (>1.6.1,<2.0.0) requires dbt-semantic-interfaces (>=0.2.0,<0.3.0).
And because dbt-postgres (1.6.1) depends on dbt-core (1.6.1)
 and dbt-core (1.6.1) depends on dbt-semantic-interfaces (>=0.2.0,<0.3.0), dbt-postgres (>=1.6.1,<2.0.0) requires dbt-semantic-interfaces (>=0.2.0,<0.3.0).
Because dbt-semantic-interfaces (0.2.0) depends on jsonschema (>=3.0,<4.0)
 and no versions of dbt-semantic-interfaces match >0.2.0,<0.3.0, dbt-semantic-interfaces (>=0.2.0,<0.3.0) requires jsonschema (>=3.0,<4.0).
Thus, dbt-postgres (>=1.6.1,<2.0.0) requires jsonschema (>=3.0,<4.0).
And because apache-airflow (2.7.0) depends on jsonschema (>=4.18.0)
 and no versions of apache-airflow match >2.7.0,<3.0.0, dbt-postgres (>=1.6.1,<2.0.0) is incompatible with apache-airflow (>=2.7.0,<3.0.0).
So, because airflow-dbt2 depends on both apache-airflow (^2.7.0) and dbt-postgres (^1.6.1), version solving failed.
```

but it works using the restrictions added by the [pyproject.toml](https://github.com/alfredosa/airflow-dbt-metabase/blob/main/pyproject.toml) of the git repository used in the article with:

```
[tool.poetry.dependencies]
python = "^3.10"
apache-airflow = "^2.6.2"
apache-airflow-providers-postgres = "^5.5.0"
dbt-postgres = "^1.5.1"
pandas = "^2.0.2"
astronomer-cosmos = "^0.7.3"
black = "^23.3.0"
```

The description of the project says:

> Poetry comes with an exhaustive dependency resolver, which will always find a solution if it exists.
>  And get a detailed explanation if no solution exists.

In this case the solution exist and was not found.

**Comment by dimbleby** [comment]
`poetry add` without further constraints always selects the latest version of the dependencies listed.  Your eventually solution uses not-the-latest eg of `apache-airflow`.

Duplicate #707, please close
