### ISSUE TITLE
Poetry >1.6.0 compiled with urllib >2 without clear indication

### ISSUE THREAD

**Issue by ebarti** [python-poetry/poetry#8381]
- **Poetry version**: 1.6.0
- **Python version**: 3.8
- **OS version and name**: `public.ecr.aws/lambda/python:3.8`
- **pyproject.toml**: N/A

- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

Starting at Poetry 1.6, it ships with a urllib>2 dependency which is incompatible with `public.ecr.aws/lambda/python:3.8`. Just adding this issue so people do not waste their time debugging a non-fixable issue.

**Comment by dimbleby** [comment]
fwiw poetry does not "ship with a urllib>2 dependency".  Indeed poetry does not mention urllib3 at all.

Rather: poetry has dependencies, and those dependencies ship with a `urllib3 < 3` dependency (nb not `urllib3 > 2`).

ie `urllib3 > 2` is not _allowed_, but not _required_.

if you want to put `urllib3 < 2` into your poetry installation then so far as I know neither poetry nor any of its dependencies will stop you.

(but you will miss out on bug fixes eg [this one](https://github.com/python-poetry/poetry/issues/7881#issuecomment-1648651432))

**Comment by dimbleby** [comment]
just `pip install urllib3==1.whatever` in the virtual environment in which you installed poetry

eg if you used pipx to install poetry then `pipx runpip ...`

**Comment by ebarti** [comment]
My bad, I never noticed that it indeed creates its own venv. Solved!
