### ISSUE TITLE
ImportError: cannot import name 'Application' from 'cleo'

### ISSUE THREAD

**Issue by lyaguxafrog** [python-poetry/poetry#8387]
- **Python version**: 3.10.12 
- **OS**: elemtary os 7 | UBUNTU_PRETTY_NAME="Ubuntu 22.04.3 LTS"
 

- [ ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

I installed poetry on the newly installed OS and encountered such an error when trying to run any command
```
Traceback (most recent call last):
  File "/home/lyaguxa/.local/bin/poetry", line 5, in <module>
    from poetry.console.application import main
  File "/usr/lib/python3/dist-packages/poetry/console/__init__.py", line 1, in <module>
    from .application import Application
  File "/usr/lib/python3/dist-packages/poetry/console/application.py", line 3, in <module>
    from cleo import Application as BaseApplication
ImportError: cannot import name 'Application' from 'cleo' (/home/lyaguxa/.local/lib/python3.10/site-packages/cleo/__init__.py)

```

**Comment by dimbleby** [comment]
obviously this works for everyone, we can't guess how you have mis-installed poetry.

suggest doing your best to remove whatever mess you have gotten into, and install by following the instructions on the website.

**Comment by dimbleby** [comment]
also your stack suggests you are using an extremely old poetry - 1.1.4 or older maybe?

no-one cares to debug such things, please close.

**Comment by Secrus** [comment]
Please install Poetry following the instructions from documentation.
