### ISSUE TITLE
WheelBuilder copies from first folder named "lib.*" - which may not be the correct one

### ISSUE THREAD

**Issue by robbotorigami** [python-poetry/poetry#8390]
- **Poetry version**: poetry-core==1.7.0

- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
in the [WheelBuilder._build](https://github.com/python-poetry/poetry-core/blob/b111cd649f7e9d7ad01f2eab40691763d5058e7c/src/poetry/core/masonry/builders/wheel.py#L186) method the built library folder is detected by looking for the first folder matching `lib.*`:
```python
libs: list[Path] = list(build_dir.glob("lib.*"))
...
lib = libs[0]
```
This works on a clean build, but may cause issues for a project with multiple build targets. E.g. on a project I have, the build directory looks like:
```
build
    > lib.linux-x86_64-cpython-39
    > lib.linux-x86_64-cpython-311
```
When a wheel is built targeting 3.11, poetry-core will incorrectly include the 3.9 libraries. 

This probably isn't a high-priority issue since there's an easy work-around of just ensuring your build directory is cleaned prior to building the wheel.

If I have time later this week I can probably make a fix/PR for this issue.

**Comment by dimbleby** [comment]
related #6197 in which generated files are put in plain `lib` and consequently omitted from the package - if you intend to tackle this then it would be good to kill two birds with one stone
