### ISSUE TITLE
Upload failed for sonartype repository

### ISSUE THREAD

**Issue by mathisloge** [python-poetry/poetry#8391]
- **Poetry version**: 1.6.1
- **Python version**: 3.10.12
- **OS version and name**: Ubuntu 22.04
- **pyproject.toml**: 
```
[[tool.poetry.source]]
name = "<myname>"
url = "https://<my-sonartype-repo-url>/repository/<myrepo>/"
priority = "primary"
```

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
Private Repository of type Sonatype Nexus Repository
When using `poetry upload -r <myname>` the upload fails with an HTTP400 Error: `Repository path must have another '/' after initial '/'`.

It would already help if the https://github.com/python-poetry/poetry/blob/eb8ada5d8cecab21a56d9a4bd4edd44faa3c56f4/src/poetry/publishing/uploader.py#L235C27-L235C27 would use exactly the url as given in `[[tool.poetry.source]]`. 
E.g. if adding `session.post(url + '/', ....` the publish is successful as expected.

**Comment by dimbleby** [comment]
the trailing slash is removed at https://github.com/python-poetry/poetry/blob/eb8ada5d8cecab21a56d9a4bd4edd44faa3c56f4/src/poetry/repositories/legacy_repository.py#L34

submit a merge request if you think this is wrong!

I expect you should be ready to make the case either that this won't break things for other users; or else that breakage is necessary and ok

**Comment by dimbleby** [comment]
actually I don't think the slash is stripped during upload - looks like the url is just read directly from configuration: https://github.com/python-poetry/poetry/blob/eb8ada5d8cecab21a56d9a4bd4edd44faa3c56f4/src/poetry/publishing/publisher.py#L52

are you sure that you included the trailing slash in your configuration?  hopefully that gives you a thread to tug on anyway

**Comment by dimbleby** [comment]
oh and now I read your report more carefully I see that you are looking at `[[tool.poetry.source]]`, which is not relevant during publishing.

So I expect this is simply: you need to correct your poetry configuration, per https://python-poetry.org/docs/repositories/#publishable-repositories

please close

**Comment by mathisloge** [comment]
Actually it will you the `[[tool.poetry.source]]` but my mistake was, that I hat previously configured one with `poetry config repositories.<myname>` after removing it, it works.
Sorry!
