### ISSUE TITLE
Platform specific extras for dependency

### ISSUE THREAD

**Issue by darsnack** [python-poetry/poetry#8392]
- **Poetry version**: 1.6.1
- **Python version**: 3.10.12
- **OS version and name**: macOS 13.5
- **pyproject.toml**: https://gist.github.com/darsnack/981ce7e407c549579e092ec81de6e21e

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

I am primarily having an issue with the dependency:
```toml
deeplabcut = [
    {version="~2.3", extras=["gui", "tf"], markers="sys_platform!='darwin'"},
    {version="~2.3", extras=["gui", "apple_mchips"], markers="sys_platform=='darwin'"}
]
```
My expectation is the the `apple_mchips` extra is only installed on `darwin` (and the opposite for `tf`). Instead, I get that all three extras: `gui`, `tf`, and `apple_mchips` are installed.

#5506 is listed as a duplicate in related issues, but I don't understand exactly how that is the case. Can the use of `markers` be clarified here? Why are these specifications being merged?

**Comment by dimbleby** [comment]
I do not reproduce.  with that dependency and on an ubuntu VM:
```
$ poetry install --dry-run | grep tensorflow
  • Installing tensorflow-estimator (2.10.0)
  • Installing tensorflow-io-gcs-filesystem (0.33.0)
  • Installing tensorflow (2.10.0)
```
note no tensorflow-macos or tensorflow-metal, which are the things provided by the apple_mchips extra.

**Comment by darsnack** [comment]
You are right, I was confused about `poetry show --tree deeplabcut` which displays both `tensorflow` and `tensorflow-macos`. I guess `poetry show` is based on the lock file which is platform agnostic, but the documentation for `poetry show --all` seems to suggest the `poetry show` is platform-specific.
