### ISSUE TITLE
Poetry reading transitive dependencies from incompatible wheel instead of sdist

### ISSUE THREAD

**Issue by matemijolovic** [python-poetry/poetry#8393]
- **Poetry version**: 1.6.1
- **Python version**: 3.11
- **OS version and name**: MacOS 13.5.1
- **pyproject.toml**: (I've removed the sensitive information)
```
[tool.poetry]
name = "a"
version = "1.0.0"
description = ""
authors = ["me"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8,<3.12"
b = "^1.0.0"
```

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

I have a package `a` that depends on package `b`. 
Package `b` has:
 - wheel distributions for certain platforms (in this case Linux) that depend on a `c_linux_specific`
 - sdist for all other platforms (I'm installing on ARM Mac) having `setup.py` that resolves the correct `c_arm_darwin_specific` dependency

When I run `poetry add /path_to_b_sdist` it installs the expected `c_arm_darwin_specific` dependency.
But when I do `poetry add b` (both wheels and sdist are available on Pypi), Poetry decides to read the dependencies from the **incompatible** wheel, which results in failed installation due to `c_linux_specific` not being available for ARM Mac (`Unable to find installation candidates for c_linux_specific`).

Is this an expected behaviour? In my opinion it would make more sense to ignore incompatible wheels as they can contain platform-specific dependencies baked into them.

**Comment by dimbleby** [comment]
poetry expects all distributions of a package to have the same metadata, with variation encoded via markers. 

your use case is not supported.

**Comment by matemijolovic** [comment]
Huh 🥲. This is a bit limiting in some cases where you don't have appropriate environment markers (e.g. when you pick a dependency depending on GPU availability).

Thanks for the explanation! Will close the ticket.
