### ISSUE TITLE
`poetry install` may uninstall poetry when runtime-venv matches target-venv and extras are used

### ISSUE THREAD

**Issue by Kakadus** [python-poetry/poetry#8395]
- **Poetry version**: 1.6.1
- **Python version**: 3.10.12
- **OS version and name**: Pop-OS 22.04
- **pyproject.toml**: [Gist](https://gist.github.com/Kakadus/4a1e80cd15466dd498f6c1cfa607b353)

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

<details>

<summary>logs of `poetry install -vvv`</summary>

> Loading configuration file /home/\*\*\*/.config/pypoetry/config.toml
Using virtualenv: /\*\*\*/venv
Installing dependencies from lock file
> 
> Finding the necessary packages for the current system
> 
> Package operations: 0 installs, 0 updates, 44 removals, 44 skipped
> 
>   • Removing attrs (23.1.0): Pending...
  •  Removing attrs (23.1.0): Removing...
  • Removing attrs (23.1.0)
  • Removing build (0.10.0): Pending...
  • Removing build (0.10.0): Removing...
  • Removing build (0.10.0)
  • Removing cachecontrol (0.13.1): Pending...
  • Removing cachecontrol (0.13.1): Removing...
  • Removing cachecontrol (0.13.1)
  • Removing certifi (2023.7.22): Pending...
  • Removing certifi (2023.7.22): Removing...
  • Removing certifi (2023.7.22)
  • Removing cffi (1.15.1): Pending...
  • Removing cffi (1.15.1): Removing...
  • Removing cffi (1.15.1)
  • Removing charset-normalizer (3.2.0): Pending...
  • Removing charset-normalizer (3.2.0): Removing...
  • Removing charset-normalizer (3.2.0)
  • Removing cleo (2.0.1): Pending...
  • Removing cleo (2.0.1): Removing...
  • Removing cleo (2.0.1)
  • Removing crashtest (0.4.1): Pending...
  • Removing crashtest (0.4.1): Removing...
  • Removing crashtest (0.4.1)
  • Removing cryptography (41.0.3): Pending...
  • Removing cryptography (41.0.3): Removing...
  • Removing cryptography (41.0.3)
  • Removing distlib (0.3.7): Pending...
  • Removing distlib (0.3.7): Removing...
  • Removing distlib (0.3.7)
  • Removing dulwich (0.21.5): Pending...
  • Removing dulwich (0.21.5): Removing...
  • Removing dulwich (0.21.5)
  • Removing filelock (3.12.3): Pending...
  • Removing filelock (3.12.3): Removing...
  • Removing filelock (3.12.3)
  • Removing idna (3.4): Pending...
  • Removing idna (3.4): Removing...
  • Removing idna (3.4)
  • Removing importlib-metadata (6.8.0): Pending...
  • Removing importlib-metadata (6.8.0): Removing...
  • Removing importlib-metadata (6.8.0)
  • Removing installer (0.7.0): Pending...
  • Removing installer (0.7.0): Removing...
  • Removing installer (0.7.0)
  • Removing jaraco-classes (3.3.0): Pending...
  • Removing jaraco-classes (3.3.0): Removing...
  • Removing jaraco-classes (3.3.0)
  • Removing jeepney (0.8.0): Pending...
  • Removing jeepney (0.8.0): Removing...
  • Removing jeepney (0.8.0)
  • Removing jsonschema (4.17.3): Pending...
  • Removing jsonschema (4.17.3): Removing...
  • Removing jsonschema (4.17.3)
  • Removing keyring (24.2.0): Pending...
  • Removing keyring (24.2.0): Removing...
  • Removing keyring (24.2.0)
  • Removing more-itertools (10.1.0): Pending...
  • Removing more-itertools (10.1.0): Removing...
  • Removing more-itertools (10.1.0)
  • Removing msgpack (1.0.5): Pending...
  • Removing msgpack (1.0.5): Removing...
  • Removing msgpack (1.0.5)
  • Removing packaging (23.1): Pending...
  • Removing packaging (23.1): Removing...
  • Removing packaging (23.1)
  • Removing pexpect (4.8.0): Pending...
  • Removing pexpect (4.8.0): Removing...
  • Removing pexpect (4.8.0)
  • Removing pkginfo (1.9.6): Pending...
  • Removing pkginfo (1.9.6): Removing...
  • Removing pkginfo (1.9.6)
  • Removing platformdirs (3.10.0): Pending...
  • Removing platformdirs (3.10.0): Removing...
  • Removing platformdirs (3.10.0)
  • Removing poetry (1.6.1): Pending...
  • Removing poetry (1.6.1): Removing...
  • Removing poetry (1.6.1)
  • Removing poetry-core (1.7.0): Pending...
  • Removing poetry-core (1.7.0): Removing...
  • Removing poetry-core (1.7.0)
  • Removing poetry-plugin-export (1.5.0): Pending...
  • Removing poetry-plugin-export (1.5.0): Removing...
  • Removing poetry-plugin-export (1.5.0)
  • Removing ptyprocess (0.7.0): Pending...
  • Removing ptyprocess (0.7.0): Removing...
  • Removing ptyprocess (0.7.0)
  • Removing pycparser (2.21): Pending...
  • Removing pycparser (2.21): Removing...
  • Removing pycparser (2.21)
  • Removing pyproject-hooks (1.0.0): Pending...
  • Removing pyproject-hooks (1.0.0): Removing...
  • Removing pyproject-hooks (1.0.0)
  • Removing pyrsistent (0.19.3): Pending...
  • Removing pyrsistent (0.19.3): Removing...
  • Removing pyrsistent (0.19.3)
  • Removing rapidfuzz (2.15.1): Pending...
  • Removing rapidfuzz (2.15.1): Removing...
  • Removing rapidfuzz (2.15.1)
  • Removing requests (2.31.0): Pending...
  • Removing requests (2.31.0): Removing...
  • Removing requests (2.31.0)
  • Removing requests-toolbelt (1.0.0): Pending...
  • Removing requests-toolbelt (1.0.0): Removing...
  • Removing requests-toolbelt (1.0.0)
  • Removing secretstorage (3.3.3): Pending...
  • Removing secretstorage (3.3.3): Removing...
  • Removing secretstorage (3.3.3)
  • Removing shellingham (1.5.3): Pending...
  • Removing shellingham (1.5.3): Removing...
  • Removing shellingham (1.5.3)
  • Removing tomli (2.0.1): Pending...
  • Removing tomli (2.0.1): Removing...
  • Removing tomli (2.0.1)
  • Removing tomlkit (0.12.1): Pending...
  • Removing tomlkit (0.12.1): Removing...
  • Removing tomlkit (0.12.1)
  • Removing trove-classifiers (2023.8.7): Pending...
  • Removing trove-classifiers (2023.8.7): Removing...
  • Removing trove-classifiers (2023.8.7)
  • Removing typing-extensions (4.7.1): Pending...
  • Removing typing-extensions (4.7.1): Removing...
  • Removing typing-extensions (4.7.1)
  • Removing urllib3 (2.0.4): Pending...
  • Removing urllib3 (2.0.4): Removing...
  • Removing urllib3 (2.0.4)
  • Removing virtualenv (20.24.4): Pending...
  • Removing virtualenv (20.24.4): Removing...
  • Removing virtualenv (20.24.4)
  • Removing zipp (3.16.2): Pending...
  • Removing zipp (3.16.2): Removing...
  • Removing zipp (3.16.2)
  • Installing attrs (23.1.0): Pending...
  • Installing attrs (23.1.0): Skipped for the following reason: Not required
  • Installing build (0.10.0): Pending...
  • Installing build (0.10.0): Skipped for the following reason: Not required
  • Installing cachecontrol (0.13.1): Pending...
  • Installing cachecontrol (0.13.1): Skipped for the following reason: Not required
  • Installing certifi (2023.7.22): Pending...
  • Installing certifi (2023.7.22): Skipped for the following reason: Not required
  • Installing cffi (1.15.1): Pending...
  • Installing cffi (1.15.1): Skipped for the following reason: Not required
  • Installing charset-normalizer (3.2.0): Pending...
  • Installing charset-normalizer (3.2.0): Skipped for the following reason: Not required
  • Installing cleo (2.0.1): Pending...
  • Installing cleo (2.0.1): Skipped for the following reason: Not required
  • Installing crashtest (0.4.1): Pending...
  • Installing crashtest (0.4.1): Skipped for the following reason: Not required
  • Installing dulwich (0.21.5): Pending...
  • Installing dulwich (0.21.5): Skipped for the following reason: Not required
  • Installing distlib (0.3.7): Pending...
  • Installing distlib (0.3.7): Skipped for the following reason: Not required
  • Installing cryptography (41.0.3): Pending...
  • Installing cryptography (41.0.3): Skipped for the following reason: Not required
  • Installing filelock (3.12.3): Pending...
  • Installing filelock (3.12.3): Skipped for the following reason: Not required
  • Installing idna (3.4): Pending...
  • Installing idna (3.4): Skipped for the following reason: Not required
  • Installing jsonschema (4.17.3): Pending...
  • Installing jsonschema (4.17.3): Skipped for the following reason: Not required
  • Installing installer (0.7.0): Pending...
  • Installing installer (0.7.0): Skipped for the following reason: Not required
  • Installing jaraco-classes (3.3.0): Pending...
  • Installing jaraco-classes (3.3.0): Skipped for the following reason: Not required
  • Installing jeepney (0.8.0): Pending...
  • Installing jeepney (0.8.0): Skipped for the following reason: Not required
  • Installing ptyprocess (0.7.0): Pending...
  • Installing ptyprocess (0.7.0): Skipped for the following reason: Not required
  • Installing keyring (24.2.0): Pending...
  • Installing keyring (24.2.0): Skipped for the following reason: Not required
  • Installing more-itertools (10.1.0): Pending...
  • Installing more-itertools (10.1.0): Skipped for the following reason: Not required
  • Installing msgpack (1.0.5): Pending...
  • Installing packaging (23.1): Pending...
  • Installing packaging (23.1): Skipped for the following reason: Not required
  • Installing msgpack (1.0.5): Skipped for the following reason: Not required
  • Installing packaging (23.1): Pending...
  • Installing packaging (23.1): Skipped for the following reason: Not required
  • Installing pexpect (4.8.0): Pending...
  • Installing pexpect (4.8.0): Skipped for the following reason: Not required
  • Installing pkginfo (1.9.6): Pending...
  • Installing pkginfo (1.9.6): Skipped for the following reason: Not required
  • Installing platformdirs (3.10.0): Pending...
  • Installing platformdirs (3.10.0): Skipped for the following reason: Not required
  • Installing poetry-core (1.7.0): Pending...
  • Installing poetry-plugin-export (1.5.0): Pending...
  • Installing poetry-plugin-export (1.5.0): Skipped for the following reason: Not required
  • Installing pycparser (2.21): Pending...
  • Installing pycparser (2.21): Skipped for the following reason: Not required
  • Installing poetry-core (1.7.0): Skipped for the following reason: Not required
  • Installing poetry-plugin-export (1.5.0): Pending...
  • Installing poetry-plugin-export (1.5.0): Skipped for the following reason: Not required
  • Installing pycparser (2.21): Pending...
  • Installing pycparser (2.21): Skipped for the following reason: Not required
  • Installing pyrsistent (0.19.3): Pending...
  • Installing pyrsistent (0.19.3): Skipped for the following reason: Not required
  • Installing rapidfuzz (2.15.1): Pending...
  • Installing rapidfuzz (2.15.1): Skipped for the following reason: Not required
  • Installing zipp (3.16.2): Pending...
  • Installing zipp (3.16.2): Skipped for the following reason: Not required
  • Installing requests-toolbelt (1.0.0): Pending...
  • Installing requests-toolbelt (1.0.0): Skipped for the following reason: Not required
  • Installing secretstorage (3.3.3): Pending...
  • Installing secretstorage (3.3.3): Skipped for the following reason: Not required
  • Installing shellingham (1.5.3): Pending...
  • Installing shellingham (1.5.3): Skipped for the following reason: Not required
  • Installing tomli (2.0.1): Pending...
  • Installing tomli (2.0.1): Skipped for the following reason: Not required
  • Installing importlib-metadata (6.8.0): Pending...
  • Installing importlib-metadata (6.8.0): Skipped for the following reason: Not required
  • Installing trove-classifiers (2023.8.7): Pending...
  • Installing trove-classifiers (2023.8.7): Skipped for the following reason: Not required
  • Installing typing-extensions (4.7.1): Pending...
  • Installing typing-extensions (4.7.1): Skipped for the following reason: Not required
  • Installing urllib3 (2.0.4): Pending...
  • Installing urllib3 (2.0.4): Skipped for the following reason: Not required
  • Installing virtualenv (20.24.4): Pending...
  • Installing virtualenv (20.24.4): Skipped for the following reason: Not required
  • Installing requests (2.31.0): Pending...
  • Installing requests (2.31.0): Skipped for the following reason: Not required
  • Installing poetry (1.6.1): Pending...
  • Installing poetry (1.6.1): Skipped for the following reason: Not required
  • Installing tomlkit (0.12.1): Pending...
  • Installing tomlkit (0.12.1): Skipped for the following reason: Not required
  • Installing pyproject-hooks (1.0.0): Pending...
  • Installing pyproject-hooks (1.0.0): Skipped for the following reason: Not required
> Traceback (most recent call last):
  File "/\*\*\*/venv/lib/python3.10/site-packages/cleo/application.py", line 327, in run
  File "/\*\*\*/venv/lib/python3.10/site-packages/poetry/console/application.py", line 190, in _run
  File "/\*\*\*/venv/lib/python3.10/site-packages/cleo/application.py", line 431, in _run
  File "/\*\*\*/venv/lib/python3.10/site-packages/cleo/application.py", line 473, in _run_command
  File "/\*\*\*/venv/lib/python3.10/site-packages/cleo/application.py", line 457, in _run_command
  File "/\*\*\*/venv/lib/python3.10/site-packages/cleo/commands/base_command.py", line 119, in run
  File "/\*\*\*/venv/lib/python3.10/site-packages/cleo/commands/command.py", line 62, in execute
  File "/\*\*\*/venv/lib/python3.10/site-packages/poetry/console/commands/install.py", line 159, in handle
  File "/\*\*\*/venv/lib/python3.10/site-packages/poetry/masonry/builders/editable.py", line 47, in __init__
  File "/\*\*\*/venv/lib/python3.10/site-packages/poetry/core/masonry/builders/builder.py", line 40, in __init__
ModuleNotFoundError: No module named 'poetry.core.masonry.metadata'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
  File "/\*\*\*/venv/bin/poetry", line 8, in <module>
  File "/\*\*\*/venv/lib/python3.10/site-packages/poetry/console/application.py", line 405, in main
  File "/\*\*\*/venv/lib/python3.10/site-packages/cleo/application.py", line 338, in run
  File "/\*\*\*/venv/lib/python3.10/site-packages/poetry/console/application.py", line 180, in render_error
  File "/\*\*\*/venv/lib/python3.10/site-packages/poetry/console/application.py", line 390, in _get_solution_provider_repository
ModuleNotFoundError: No module named 'crashtest'
</details>

## Issue

Poetry might uninstall itself (or any of its dependencies) when the project's transitive `extras` dependencies overlap with those of poetry and poetry is installed to and runned from the installation target. The latter can happen quite fast when using `virtualenvs.create=false` for instance.

1. Setup poetry [manually (advanced)](https://python-poetry.org/docs/#installing-manually)
2. Let poetry use the previously created venv (by using e.g. [virtualenvs.create](https://python-poetry.org/docs/configuration/#virtualenvscreate)=false or [virtualenvs.prefer-active-python](https://python-poetry.org/docs/configuration/#virtualenvsprefer-active-python-experimental)=true)
3. Lock via `poetry lock`
4. Install via `poetry install`

While this behaviour follows the documentation, poetry should probably detect this setup and either do not uninstall itself and its transitive dependencies or refuse to work at all. Things get messy anyway when the runtime and target virtualenv are the same, because poetry will also upgrade dependencies which are incompatible with poetry.

**Comment by dimbleby** [comment]
> when ... poetry is installed to and runned from the installation target

yeah, don't do that.  Install poetry per the docs.

please close
