### ISSUE TITLE
Django, docker and poetry: an use case

### ISSUE THREAD

**Issue by brunolnetto** [python-poetry/poetry#8398]
- **Poetry version**:  Poetry (version 1.5.1)
- **Python version**: Python 3.8.10
- **OS version and name**: Ubuntu 20.04
- **pyproject.toml**: https://github.com/trouchet/tarzan/blob/e158db854086722fd7b62e112724e22493fcaa85/pyproject.toml

Remark: I am unable to find gist url.

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

I build a Django boilerplate. Since poetry suits me well with package building, I thought app management would  work well. However, I am not able to properly setup dependencies with poetry within Dockerfile. I wrote an [issue on StackOverflow](https://stackoverflow.com/questions/77018156/i-cannot-host-django-app-with-docker-compose-and-boilerplates-request?noredirect=1#comment135777008_77018156). Refer to it for further informations. The error log from command run `docker ps -a --format "table {{.ID}}\t{{.Names}}" | grep "tarzan-box" | awk '{print $1}' | xargs docker logs` is below:

```
Traceback (most recent call last):
  File "manage.py", line 5, in <module>
    import django
ModuleNotFoundError: No module named 'django'

```

I know this is not properly an issue with poetry, but any help from poetry staff would be very appreciated. Thanks ni advance, folks.

**Comment by dimbleby** [comment]
> I know this is not properly an issue with poetry,

this is an issue tracker - it is not the right place for things that are not poetry issues.

maybe you'll have better luck on discord

please close
