### ISSUE TITLE
poetry errors if a non-poetry pyproject.toml exists in current dir

### ISSUE THREAD

**Issue by deronnax** [python-poetry/poetry#8412]
- **Poetry version**: 1.6.1
- **Python version**: 3.11.4
- **OS version and name**: macOS 13.5.1
- **pyproject.toml**: 

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
Poetry straight-out errors if there is a non-poetry pyproject.toml file in the current directory. Even `poetry --help` or `poetry --version` doesn't work anymore (and so does `poetry debug info` 🙃 ).

So if you are in non-poetry project, you can't even list poetry's command or see the version you have or anything.

reproductable case:
```
➜  cd /tmp
➜  poetry --version 
Poetry (version 1.6.1)
➜  touch pyproject.toml
➜  poetry --version

[tool.poetry] section not found in /private/tmp/pyproject.toml
➜  /poetry --help

[tool.poetry] section not found in /private/tmp/pyproject.toml
➜
```

**Comment by dimbleby** [comment]
seems reasonable

**Comment by Secrus** [comment]
How did you install Poetry? I cannot reproduce this on my machine.

**Comment by deronnax** [comment]
It was through pipx. I uninstalled it and reinstalled it through pipx again, and now I cannot reproduce the error. Which is funny because the error was not a transient one, I had it systematically for weeks. 
Maybe we can close the issue until someone come up with the error again.
