### ISSUE TITLE
install fails to find transitive dependencies when using private repository with priority explicit

### ISSUE THREAD

**Issue by lukany** [python-poetry/poetry#8416]
- **Poetry version**: 1.6.1 (tested also with 1.5.1)
- **Python version**: 3.11.5
- **OS version and name**: macOS 13.5.1, also tested on ubuntu-22.04 via GitHub Action
- **pyproject.toml**: multiple **pyproject.toml** files are required to reconstruct the bug. Here is a repo with them: https://github.com/lukany/poetry-bug-reconstruction

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

`poetry install` fails when:
 - there are dependencies from a private repository
 - the private repository source is defined with `priority="explicit"`
 - one of the direct dependencies has a transitive dependency from the same private repository

I.e. in this example:
```mermaid
graph LR
subgraph Private Repository
    pkg-b
    pkg-c
end
pkg-a[pkg-a] --depends on--> pkg-b --depends on--> pkg-c
```
running `poetry install` in `pkg-a` would result in an error that `pkg-c` could not be found.

Installation works correctly when `priority="explicit"` is changed to `priority="supplemental"` in `pkg-a`'s `pyproject.toml`.

### Bug Reconstruction

Repository with code to reconstruct the bug: https://github.com/lukany/poetry-bug-reconstruction/.
The reconstruction consists in creating a local repository with [devpi](https://devpi.net/docs/devpi/devpi/latest/+doc/index.html), uploading there packages and trying to install them.
Here is a GitHub action run fully reconstructing the bug and verifying workaround with changing `explicit` to `supplemental`: https://github.com/lukany/poetry-bug-reconstruction/actions/runs/6110568140/job/16583868289.

**Comment by dimbleby** [comment]
this is expected.  "explicit" means explicit: you are hoping that an "explicit" repository should be used for transient dependencies that do not have that explicit instruction

please close

**Comment by lukany** [comment]
> this is expected. "explicit" means explicit: you are hoping that an "explicit" repository should be used for transient dependencies that do not have that explicit instruction
> 
> please close

I am sorry, I do not understand. All the packages in my example have `explicit` instruction.

My issue is:
 - I have packages `pkg-a`, `pkg-b` and `pkg-c` that reside in a private repository — let's call the repository `devpi-repo`.
 - `pkg-a` depends on `pkg-b` and `devpi-repo` source is set to `explicit` in `pkg-a`'s `pyproject.toml`
 - `pkg-b` depends on `pkg-c` and `devpi-repo` source is set to `explicit` in `pkg-b`'s `pyproject.toml`
 - When running `poetry install` within `pkg-a` poetry says that it cannot find `pkg-c`.
 - If I change priority of `devpi-repo` from `explicit` to `supplemental` in `pkg-a`'s `pyproject.toml` `poetry install` succeeds.

I see no reason why I couldn't use `explicit` source in `pkg-a`'s `pyproject.toml`. Therefore, I consider this as a bug.

**Comment by dimbleby** [comment]
sources defined outside of pkg-a's pyproject.toml are irrelevant when locking or installing package pkg-a.

you can find other issues discussing this if you search this tracker

please close

**Comment by lukany** [comment]
I see. This is indeed an expected behaviour. Closing the issue. I am sorry for the duplicate and thank you for the explanation!

For the record:
 - duplicate issue: https://github.com/python-poetry/poetry/issues/8102
 - relevant documentation section: https://python-poetry.org/docs/repositories/#package-source-constraint

@dimbleby Just curious: is this a deliberate design or it stems from some limitations of PyPI / Python repositories in general? It would make sense to me if sources outside pkg-a's pyproject.toml were also taken into account.

**Comment by dimbleby** [comment]
sources are a poetry-special: there is no place in wheel metadata to hold this information

**Comment by lukany** [comment]
Understand, thank you!
