### ISSUE TITLE
Not finding an installed package in a Docker image

### ISSUE THREAD

**Issue by rjalexa** [python-poetry/poetry#8419]
- **Poetry version**: 1.6.1
- **Python version**: 3.10.13
- **OS version and name**:  Docker  python:3.10.13-slim-bullseye image
- **pyproject.toml**: https://gist.github.com/rjalexa/55fd29e22c8f8f0b47c2ace50764f699

- [ x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [ x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [ x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
I am installing and using Poetry as per the following Dockerfile:
```
# ---- Base Layer ----
FROM python:3.10.13-slim-bullseye AS base

# Environment settings and maintainer label
LABEL maintainer="xxxxxxxxxx"
ENV TZ=Europe/Rome \
    PYTHONUNBUFFERED=1 \
    POETRY_VERSION=1.6.1 \
    POETRY_HOME="/usr/local/bin"

# Set timezone and package preferences
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone && \
    echo 'APT::Install-Suggests "0";' > /etc/apt/apt.conf.d/00-docker && \
    echo 'APT::Install-Recommends "0";' > /etc/apt/apt.conf.d/00-docker

# Install necessary packages
RUN DEBIAN_FRONTEND=noninteractive apt-get update && \
    apt-get install -y pip ca-certificates sudo nvi net-tools tzdata curl git wget tar && \
    rm -rf /var/lib/apt/lists/* && \
    pip install "poetry==$POETRY_VERSION" && \
    poetry config virtualenvs.create false

# ---- Application Layer ----
FROM base AS application

# Set the working directory
WORKDIR /app

# Copy the Poetry dependencies manifest
COPY pyproject.toml poetry.lock ./

# Install dependencies
RUN poetry install --no-root

# Copy the source code
COPY . /app

# Install the project (no dependencies)
RUN poetry install --only-root

EXPOSE 4100

# Run the script suite
#ENTRYPOINT poetry run python src/api/mema_api.py
```
and if I enter a Bash shell in the container I can see poetry 1.6.1 is running and `poetry show connexion` will list it as installed as follows:
```
root@37e31f3c2d42:/app# poetry show connexion
 name         : connexion
 version      : 2.14.2
 description  : Connexion - API first applications with OpenAPI/Swagger and Flask

dependencies
 - clickclick >=1.2,<21
 - flask >=1.0.4,<2.3
 - inflection >=0.3.1,<0.6
 - itsdangerous >=0.24
 - jsonschema >=2.5.1,<5
 - packaging >=20
 - PyYAML >=5.1,<7
 - requests >=2.9.1,<3
 - swagger-ui-bundle >=0.0.2,<0.1
 - werkzeug >=1.0,<2.3
```
but when I run the last (currently commented) Dockerfile line:
```
root@37e31f3c2d42:/app# poetry run python src/api/mema_api.py
Traceback (most recent call last):
  File "/app/src/api/mema_api.py", line 9, in <module>
    import connexion
ModuleNotFoundError: No module named 'connexion'
```
(same happens if I launch poetry shell).

Please not that I mean to install all libraries globally since I'm in a container (but see a .venv created under my /app nevertheless)

Very confused as to how to fix the paths so that the python environment will be able to use all installed libraries.

Thanks a lot in advance.

**Comment by dimbleby** [comment]
what you are saying happens, does not happen.

you haven't provided a full reproduction so I've had to fill in the gaps, but:
```
# cat src/api/mema_api.py
import connexion

print("Hello")

# poetry run python src/api/mema_api.py
Skipping virtualenv creation, as specified in config file.
Hello
```
please close

**Comment by rjalexa** [comment]
I am inside the docker with:
`docker run -it mema-services:v0.1 /bin/bash`
within it:
```
root@d93b62e97410:/app# cat src/api/test.py
import connexion

print("Hello")
root@d93b62e97410:/app# poetry run python src/api/test.py
Traceback (most recent call last):
  File "/app/src/api/test.py", line 1, in <module>
    import connexion
ModuleNotFoundError: No module named 'connexion'
```
so in my case I confirm it is happening indeed. Not sure how you pulled it off. Did you use my very same Dockerfile?

Thank you

**Comment by rjalexa** [comment]
I have an additional insight that might give us a clue.
The behaviour I have show right above only appears when the docker build and run is performed on my M2 Mac. On an AWS node running Ubuntu it does work well as you have assessed. No clue.

**Comment by dimbleby** [comment]
if you have a working and a non-working image then I guess you are in the right starting place to figure out the difference

I don't see any reason to suspect a poetry bug though...

**Comment by rjalexa** [comment]
ok thanks. Will close.
