### ISSUE TITLE
poetry not reporting compat with python verson, even if it should be

### ISSUE THREAD

**Issue by earonesty** [python-poetry/poetry#8421]
- **Poetry version**: 1.6.1
- **Python version**: 3.11.5
- **OS version and name**: windows 10
- **pyproject.toml**: https://gist.github.com/earonesty/2910aac6cdeb21eea29813289117b377

## Issue

```
$ poetry lock
```

```
The current project's Python requirement (>=3.10) is not compatible with some of the required packages Python requirement:
  - pyinstaller requires Python <3.13,>=3.7, so it will not be satisfied for Python >=3.13
```

should work fine.   easy temp fix is to pin the python version in the toml 

```python = ">=3.10"```

replace with

```python = ">=3.10,<3.13"```

but really, the solver should see that pyinstaller's reqs and the current python version and the version in the project toml are all just peachy

**Comment by dimbleby** [comment]
please read the faq, and close

**Comment by earonesty** [comment]
https://python-poetry.org/docs/faq/#why-is-poetry-telling-me-that-the-current-projects-python-requirement-is-not-compatible-with-one-or-more-packages-python-requirements

thanks.   i wish this came up on google more.  maybe this closed ticket will help.

**Comment by dimbleby** [comment]
unlikely... I am afraid that you yourself are evidence that people neither read the docs nor search for duplicates before raising issues!

**Comment by earonesty** [comment]
i did!  just didn't find the exact error
