### ISSUE TITLE
Adding a git repo via a custom source causes pyproject.toml to fail validation

### ISSUE THREAD

**Issue by KrisDavie** [python-poetry/poetry#8431]
- **Poetry version**: 1.6.1 
- **Python version**: 3.11.5
- **OS version and name**: Debian Bullseye (python:3.11-slim-bullseye docker image)
- **pyproject.toml**:  n/a 

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

When adding a github source via `poetry source add` and then subsequently installing a package from that git repo, a line such as this is added to `pyproject.toml`:
```
alembic = {git = "https://github.com/sqlalchemy/alembic.git", source = "alembic"}
```

This line causes poetry to fail any further poetry commands with a `The Poetry configuration is invalid:` error. This was discovered while trying to add a private repository, but happens with public repos also.

The following Dockerfile reproduces the issue:

```
FROM python:3.11-slim-bullseye
RUN pip install poetry

WORKDIR /app
RUN poetry new issue
WORKDIR /app/issue

RUN poetry --version
RUN poetry debug info
RUN poetry add fastapi
RUN poetry source add alembic https://github.com/sqlalchemy/alembic --priority=supplemental 
RUN poetry add --source alembic git+https://github.com/sqlalchemy/alembic.git

RUN cat pyproject.toml

RUN poetry check -vvv
```
Here is the output of `docker build . --progress=plain --no-cache` with that dockerfile: [docker_ouput.txt](https://github.com/python-poetry/poetry/files/12586359/docker_ouput.txt)

**Comment by dimbleby** [comment]
there is no such thing as "a github source", you don't want to define a source here at all.

I expect a pull request improving the error message for would be welcome.  Suggest that the mistake is trying to define a source for a git dependency, and this can be caught in `AddCommand::handle()`

**Comment by KrisDavie** [comment]
The main reason I'm defining a source here is so that I can specify credentials for the private repository I'd like to access within docker, as follows:

```
RUN poetry source add private https://github.com/private/repo
RUN poetry config http-basic.private KrisDavie `cat ${GITHUB_PAT}`
RUN poetry add --source private git+https://github.com/private/repo.git
```
Where `GITHUB_PAT` is a file containing an access token.

This works to access the repo and get the package installed no problem, but then `pyproject.toml` can no longer be read. 

Is there some other way that would achieve this without adding a source and thus not adding the erroneous line to the `pyproject.toml`?
