### ISSUE TITLE
Mysqlclient in poetry environment is installing the wrong version of mysqldb

### ISSUE THREAD

**Issue by mljlynch** [python-poetry/poetry#8432]
- **Poetry version**: Poetry (version 1.6.1)
- **Python version**: Python:         3.11.1
- **OS version and name**: macOS 13.5.2
- **pyproject.toml**: 

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

When running pytests under my poetry environment on a mac M2 chip, I get the following error:

```
E   ImportError: dlopen(/Users/Jake/Library/Caches/pypoetry/virtualenvs/fig-etl-wTxwD1sp-py3.11/lib/python3.11/site-packages/MySQLdb/_mysql.cpython-311-darwin.so, 0x0002): symbol not found in flat namespace '_mysql_affected_rows'
```

I understand this is probably due to mismatched binaries, but since I'm not directly installing mysqldb. This seems related to this issue, but there is no specific poetry fix:

https://github.com/PyMySQL/mysqlclient/issues/496

**Comment by dimbleby** [comment]
I see no reason to suspect a poetry bug.  Indeed the repeated appearance of the same issue in the mysqlclient issue tracker from people who are not using poetry tends to lead to the opposite conclusion

please make a (much) more convincing case that this is a poetry issue - or close

**Comment by mljlynch** [comment]
Thanks @dimbleby  - you are correct, this is not related to poetry. The solution is to brew uninstall the corresponding `mysql` and `mysql-connector` packages in both the arm and x86 version of brew and then reinstall mysql.

Then you have to destroy the existing poetry environment and re-install. and It should work.
