### ISSUE TITLE
Incompatibility with python-dotenv

### ISSUE THREAD

**Issue by codingbutstillalive** [python-poetry/poetry#8444]
I want to use "load_dotenv" from the Pypi package "python-dotenv" to load key value pairs from a .env file.

These are the steps I had performed:

1.) poetry add dotenv
( I then learned that I need to use python-dotenv instead )
2.) poetry remove dotenv
3.) poetry add python-dotenv

However, when I am trying to import "load_dotenv" I get an error message that suggests that poetry still refers to "dotenv" instead of "python-dotenv" and it cannot find "load_dotenv()".

**Comment by codingbutstillalive** [comment]
The error message is: Cannot import name 'load_dotenv' from 'dotenv'

**Comment by dimbleby** [comment]
this is not going to be a poetry bug.  probably you simply haven't activated the virtual environment in which you are installing your project

**Comment by codingbutstillalive** [comment]
I have explicitly checked with "poetry run python".

**Comment by dimbleby** [comment]
```bash
$ poetry init -n
$ poetry add python-dotenv
Using version ^1.0.0 for python-dotenv

Updating dependencies
Resolving dependencies... (0.1s)

Package operations: 1 install, 0 updates, 0 removals

  • Installing python-dotenv (1.0.0)

Writing lock file
$ poetry run python -c 'from dotenv import load_dotenv'
$ echo $?
0
```
please close

**Comment by codingbutstillalive** [comment]
Thank you. It still didn't work for me. But due to your feedback, I made a reset of the whole installation based on the pyproject.toml.

I am pretty sure that "poetry remove dotenv" didn't completely work.

Further confusion came from the existence of the following project:

https://github.com/volopivoshenko/poetry-plugin-dotenv

**Comment by dimbleby** [comment]
if you are willing and able to provide a way to reproduce a poetry problem - either with a very explicit series of commands, or even better put those commands in a Dockerfile so that everyone will see the same results - then please do so.

Else please close this out
