### ISSUE TITLE
FAQ `Is tox supported?` Outdated with `tox` v4

### ISSUE THREAD

**Issue by adam-grant-hendry** [python-poetry/poetry#8445]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

The information in the [FAQ](https://python-poetry.org/docs/faq/#is-tox-supported) regarding `tox` is outdated for `tox` `v4` and above. [Isolated builds are on by default](https://tox.wiki/en/latest/upgrading.html#isolated-environment-on-by-default) now and several `tox.ini` keys [have been removed](https://tox.wiki/en/latest/upgrading.html#removed-tox-ini-keys).

This is a minor issue. At most, may warrant a small footnote to the docs in the event `tox>=4` issues a warning when trying to set a non-existent key.

**Comment by finswimmer** [comment]
@adam-grant-hendry A PR that updates the docs is always welcome :smiley:

**Comment by dimbleby** [comment]
IMO, guidance and reaction to such issues should be stronger: please open a merge request, or close it out  

I assert that if you care enough to raise an issue: then raising an issue but _not_ opening a merge request is pointless.  
- Almost certainly no-one else will bother to do anything about it so nothing is achieved.  
- But the report is not wrong exactly - so it can't be rejected either, and will just sit around forever doing no good

(I might have made the same remark on any of maybe a hundred open issues: this is meant more as a comment on the general approach than on this one in particular)

**Comment by adam-grant-hendry** [comment]
@dimbleby This is an open-source project. I cannot demand you fix something nor you me. Your tone comes across rather rude, which I don't appreciate (though I could be misreading it).

If the maintainers do not want to address the issue, they are more than welcome to close any issue they please as a won't fix (unless something else I am unaware of is preventing them, though I don't see a `CODE_OF_CONDUCT` or any such instruction in the `CONTRIBUTING` guide...?). Also, it's only been several hours since I opened the issue...it's not likely I would open a pull request simultaneously.

Either way, bringing up an issue is not pointless. I'm simply bringing it to your attention. This could also be added to a project timeline or future to-do...there are many ways to utilize issues such as these. Berating a user for opening an issue is certainly not one of them.

If I have time and am willing, I will submit a pull request. Otherwise, a simply response like [@finswimmer](https://github.com/python-poetry/poetry/issues/8445#issuecomment-1721707725) more than suffices to let me know you are welcome to me submitting a fix.

**Comment by dimbleby** [comment]
Neither of us is demanding that anyone fix anything.  If you find my tone rude you are certainly misreading my intention.  As I said, my remark might have been made of any of many issues: if anything it is meant more for finswimmer and other maintainers than for you.

From your point of view: I am advising that in my experience of contributing to and watching this project, opening a docs issue without a supporting MR _is_ pointless, or very close to it.  That's not saying that you're a bad person, or at fault for this: it's simply an assessment that the likely outcome will be: nothing happens.

In taking the trouble to figure out what you want the docs to say and engage with the project - you are doing the first 80% of the work, and will see maybe 1% of the desired result.

**Comment by radoering** [comment]
Resolved by #8658
