### ISSUE TITLE
Compressed file ended before the end-of-stream marker was reached

### ISSUE THREAD

**Issue by kerthcet** [python-poetry/poetry#8449]
- **Poetry version**:  1.6.1 
- **Python version**:  python 3.10.13
- **OS version and name**:  MacOS 11.3.1
- **pyproject.toml**: 
```
[tool.poetry.dependencies]
python = "^3.10"
fastapi = "0.103.0"
ray = {extras = ["serve"], version = "^2.6.3"}
torch = "2.0.0"
llmlite = "0.0.7"
retry = "^0.9.2"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.2"
black = "^23.9.1"
mypy = "^1.5.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

When running `poetry install torch==2.0.0`, error output: 
```
  • Installing grpcio (1.58.0): Failed

  EOFError

  Compressed file ended before the end-of-stream marker was reached
  at ~/.pyenv/versions/3.10.13/lib/python3.10/gzip.py:507 in read
      503│
      504│             if uncompress != b"":
      505│                 break
      506│             if buf == b"":
    → 507│                 raise EOFError("Compressed file ended before the "
      508│                                "end-of-stream marker was reached")
      509│
      510│         self._add_read_data( uncompress )
      511│         self._pos += len(uncompress)

```

I have no idea how to solve this, I searched the net, it may because some download files broken, but still couldn't figure out how to solve this. Thanks.

When I install this under linux, it succeeded, so I guess if I can find the broken file, and delete it, I can recover?

**Comment by dimbleby** [comment]
clear the cache

**Comment by kerthcet** [comment]
I used `poetry cache clear`, but still didn't work.

**Comment by dimbleby** [comment]
so remove the whole poetry cache directory

**Comment by kerthcet** [comment]
I removed the `artifacts` folder, which works, thanks @dimbleby , saves my time.
/close

**Comment by richin13** [comment]
For anyone wondering, in linux the artifacts folder lives in `$XDG_CACHE_HOME/pypoetry` 

By default, `$XDG_CACHE_HOME` is `$HOME/.cache`
