### ISSUE TITLE
read system-wide config on Windows

### ISSUE THREAD

**Issue by MrMontesa** [python-poetry/poetry#8451]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request
Hey Poetry team,
we're currently in the process of rolling out poetry 1.6.1 to our Windows clients as a central system-wide tool.
So we use the installer to place the venv in C:\Program Files\Poertry which works nice.

Our DEVs also requested us to place some basic config which should be the same for ALL users. Since poetry reads its Windows config from %Appdata% which always points at the user-space directory, we can hardly prepare the environment on system-wide level.

Compared to pip, where we place a config file in `C:\ProgramData\pip\`, I haven't found such feature for poetry.

Could you recommend a way to setup a system-wide config? Or add a feature so that system-wide configs are read from e.g. `C:\ProgramData\pypoetry\`?
Thanks much for your help.
best Sebastian

**Comment by dimbleby** [comment]
https://python-poetry.org/docs/configuration/#config-directory

please close

**Comment by MrMontesa** [comment]
Hey David,
Thanks for your swift reply. Appreciate your help. I'm aware of this docu, but it does not apply to our needs.
%APPDATA% points to a folder in user-space of the currently logged in user. e.g. C:\Users\sebastian\AppData\Roaming
Placing a config there wont help user David logging into the device. The APPDATA config needs to be done for EVERY user who logs into the system.

Comparing the feature set with pip:
There we have a pip.ini in C:\ProgramData\pip\. This is read by EVERY user who uses pip on the system.

In fact I'm asking for a poetry config read feature similar feature to pip. system-wide config file not tied to any user-space area.
Suggestion would be to have poetry read `C:\ProgramData\pypoetry\config.toml`. could be still overwritten by user-space config in APPDATA or project config within a venv.

Let me know if you need more details.
Thanks much

**Comment by Secrus** [comment]
@MrMontesa The linked doc also points to the `POETRY_CONFIG_DIR` env variable that you can use to point to your chosen directory.
