### ISSUE TITLE
Poetry 1.5.1 is giving 401 client error

### ISSUE THREAD

**Issue by Daydreamer05** [python-poetry/poetry#8453]
I'm using my private gitlab regsitry for downloading  packages..But when I upgraded python version 1.1.11 to 1.5.1 ..The poetry install is giving

  HTTPError
  401 Client Error: Unauthorized for url:
  
  I tried adding the credentials in the toml file under source ..still getting the same error..
  And I'm getting this error only in 1-2 repos in other repos it is working fine..

**Comment by dimbleby** [comment]
You should assume that you've added the credentials wrong, or made a typo while adding them, or your password has expired, or whatever.

Lots of us use private repositories with poetry all the time and it works fine.

**Comment by Daydreamer05** [comment]
No I don't think so..Because with the same credentials, it's working fine with the 1.1.11 version

**Comment by jammymalina** [comment]
I am facing the same issue, it was not happening in the previous versions of poetry

**Comment by Pennywise007** [comment]
Hi, the same issue with Poetry 1.6.1, I solved it in Linux by cleaning the directory
**~/.config/pypoetry**

**Comment by cute149q** [comment]
I am facing the same issue 😂

**Comment by abn** [comment]
This looks like a stale issue. A lot has changed in the credential handling of private sources.

See documentation on private repository configuration at https://python-poetry.org/docs/repositories/#private-repository-example.

GitLab is known to work file with the right tokens. Verify tokens have the right permissions and access levels, and if required rotate it.

In certain cases, old stale configuration could also be an issue. For now closing this issue. If the issue persists, please raise a new issue with all relevant details, including verbose logs as well as a reproducer. Ideally, if you have a private repo we can test and reproduce against, ping us on Discord.

**Comment by arces** [comment]
> Hi Same issue with Poetry 1.6.1. I get 401 authorization error while the token is valid. I managed to solve the problem by cleaning the following directories:
> 
> * delete all .toml files located in: **C:\Users<username>\AppData\Roaming\pypoetry**.
> * delete the cache directory located in: **C:\Users<username>\AppData\Local\pypoetry**.

This also worked for me. Once I deleted both, re configured the auth via the command line, my packages installed perfectly first try.
