### ISSUE TITLE
You can uninstall at any time by executing this script with the --uninstall option

### ISSUE THREAD

**Issue by ForwardForward** [python-poetry/poetry#8456]
After installing under Windows using PowerShell, I get the following message:

 (Invoke-WebRequest -Uri https://install.python-poetry.org -UseBasicParsing).Content | py -           Retrieving Poetry metadata

# Welcome to Poetry!

This will download and install the latest version of Poetry,
a dependency and package manager for Python.

It will add the `poetry` command to Poetry's bin directory, located at:

C:\Users\igorb\AppData\Roaming\Python\Scripts

You can uninstall at any time by executing this script with the **--uninstall option**,
and these changes will be reverted.

Installing Poetry (1.6.1)
Installing Poetry (1.6.1): Saving existing environment
Installing Poetry (1.6.1): Creating environment
Installing Poetry (1.6.1): Installing Poetry
Installing Poetry (1.6.1): Creating script
Installing Poetry (1.6.1): Done

Poetry (1.6.1) is installed now. Great!

You can test that everything is set up by executing:

`poetry --version`

Everything is fine, but the --uninstall option doesn't work with poetry.exe. How can I uninstall it?
This is not the correct uninstall information

**Comment by dimbleby** [comment]
> You can uninstall at any time by executing this script with the --uninstall option,

I'm not sure what would make "this script" clearer, but please submit a merge request if you have an improvement

**Comment by radoering** [comment]
`"this script"` is the installer script that prints this output, not poetry.exe. I think this should be clear enough. Anyway:

> I'm not sure what would make "this script" clearer, but please submit a merge request if you have an improvement
