### ISSUE TITLE
"Skipping virtualenv creation, as specified in config file."

### ISSUE THREAD

**Issue by brunolnetto** [python-poetry/poetry#8457]
- **Poetry version**: Poetry (version 1.6.1)
- **Python version**: Python 2.7.18
- **OS version and name**: Ubuntu 20.04.6
- **pyproject.toml**: https://github.com/trouchet/argentus/blob/871de4f63d2c06dd67ab686f529585ee2273a803/pyproject.toml

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

I want to report an changing behavior without any explicit change on how I deal with poetry. Today, I woke up and created a FastAPI boilerplate for learning. I use poetry because I trust you much. After running command `poetry init` and adding `fastapi` and `uvicorn`, I got my toml file. I tried to add another dependencies with command run `poetry add package_name`, and here is where the problem happened first:

```
Skipping virtualenv creation, as specified in config file.

Invalid version '0.23ubuntu1' on package distro-info
```

On previous usage routine, I used to run command `poetry shell` to activate the current environment. It has previously showed a tag on current line of terminal with activated environment name. Now, it appears this error log below:

```
Skipping virtualenv creation, as specified in config file.
Virtual environment already activated: /usr
```

I am still satisfied with package management library `poetry`. But this issue made me annoyed on this sunny morning. :-/

**Comment by brunolnetto** [comment]
I really did not set manually. I will close the issue. Do you recommend to update my operational system to a newer Ubuntu version?

**Comment by dimbleby** [comment]
> I really did not set manually

well then I guess someone else has been on your computer, you might want to worry about what else they have done

> Do you recommend to update my operational system to a newer Ubuntu version?

sure, go for it: though using virtual environments should be enough...

**Comment by brunolnetto** [comment]
Nobody touched my computer this morning. I run command `poetry config virtualenvs.create true`, but now I receive log `module 'virtualenv.create.via_global_ref.builtin.cpython.mac_os' has no attribute 'CPython2macOsArmFramework'`. Curiously, on other projects with same setup workflow, the environment activation works just fine with command `poetry shell`.
