### ISSUE TITLE
Unspecific what the scripts type in tool.poetry.scripts section of the pyproject.toml does

### ISSUE THREAD

**Issue by philipp-horstenkamp** [python-poetry/poetry#8459]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

When reading the documentation about https://python-poetry.org/docs/pyproject/#scripts it is unclear what do type definition in the extras example does.
Could you specify this with a single sentence?

**Comment by dimbleby** [comment]
merge request surely welcome, please go ahead

you might find the following helpful in writing it:
- recent discussion in https://github.com/orgs/python-poetry/discussions/8436
- schema definition at https://github.com/python-poetry/poetry-core/blob/main/src/poetry/core/json/schemas/poetry-schema.json

**Comment by philipp-horstenkamp** [comment]
Tank you for the awnser. This then seems like a dupicat. I will close this issue.
