### ISSUE TITLE
Poetry fails to install all but first dependency on Windows with Python 3.12.0-rc3

### ISSUE THREAD

**Issue by BooleanCat** [python-poetry/poetry#8461]
- **Poetry version**: 1.6.1
- **Python version**: 3.12.0-rc3
- **OS version and name**: Windows
- **pyproject.toml**: https://github.com/BooleanCat/haem/blob/p3.12/pyproject.toml

- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

Poetry seems to only install the first dependency when executing `poetry install --no-root --with=dev` on Windows using Python 3.12.0-rc3: https://github.com/BooleanCat/haem/actions/runs/6272494593/job/17034121917

My GitHub actions config uses Poetry and execute the same commands against all combinations of Python 3.8+ and Windows, Ubuntu and macOS. Only Windows on 3.12.0-rc3 seems to fail to install all dependencies. For example:

Windows + Python 3.11:

```
Run poetry install --no-root --with=dev
Creating virtualenv haem-9fcuxZH6-py3.11 in C:\Users\runneradmin\AppData\Local\pypoetry\Cache\virtualenvs
Installing dependencies from lock file

Package operations: 14 installs, 0 updates, 0 removals

  � Installing colorama (0.4.6)
  � Installing click (8.1.7)
  � Installing iniconfig (2.0.0)
  � Installing mypy-extensions (1.0.0)
  � Installing packaging (23.1)
  � Installing pathspec (0.11.2)
  � Installing platformdirs (3.10.0)
  � Installing pluggy (1.3.0)
  � Installing typing-extensions (4.8.0)
  � Installing black (23.9.1)
  � Installing isort (5.12.0)
  � Installing maturin (1.2.3)
  � Installing pytest (7.4.2)
  � Installing mypy (1.5.1)
cargo fmt --check
cargo clippy
   Compiling pyo3-build-config v0.19.2
   Compiling pyo3-ffi v0.19.2
   Compiling pyo3 v0.19.2
    Checking haem v0.1.0 (D:\a\haem\haem)
    Finished dev [unoptimized + debuginfo] target(s) in 8.75s
poetry run isort . --check
Skipped 3 files
poetry run black --check .
...
```

Windows + Python 3.12-rc3:

```
Run poetry install --no-root --with=dev
Creating virtualenv haem-9fcuxZH6-py3.12 in C:\Users\runneradmin\AppData\Local\pypoetry\Cache\virtualenvs
Installing dependencies from lock file

Package operations: 14 installs, 0 updates, 0 removals

  � Installing colorama (0.4.6)
cargo fmt --check
cargo clippy
   Compiling pyo3-build-config v0.19.2
   Compiling pyo3-ffi v0.19.2
   Compiling pyo3 v0.19.2
    Checking haem v0.1.0 (D:\a\haem\haem)
    Finished dev [unoptimized + debuginfo] target(s) in 8.21s
poetry run isort . --check
'isort' is not recognized as an internal or external command,
```

**Comment by dimbleby** [comment]
you're going to want to try again with debug logs

maybe some sort of variation on #7148?!?

poetry is working fine against python 3.12 in its own pipelines - eg https://github.com/python-poetry/poetry/actions/runs/6265070727/job/17013096810 - so you're likely going to have to figure out for yourself where this is going wrong - and consequently, whether it is or is not a poetry bug.

**Comment by BooleanCat** [comment]
Unfortunately increasing verbosity didn't reveal anything:


```
Run poetry install -vvv --no-root --with=dev
  poetry install -vvv --no-root --with=dev
  make test
  shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"
  env:
    pythonLocation: C:\hostedtoolcache\windows\Python\3.12.0-rc.3\x64
    PKG_CONFIG_PATH: C:\hostedtoolcache\windows\Python\3.12.0-rc.3\x64/lib/pkgconfig
    Python_ROOT_DIR: C:\hostedtoolcache\windows\Python\3.12.0-rc.3\x64
    Python2_ROOT_DIR: C:\hostedtoolcache\windows\Python\3.12.0-rc.3\x64
    Python3_ROOT_DIR: C:\hostedtoolcache\windows\Python\3.12.0-rc.3\x64
    CARGO_INCREMENTAL: 0
    CARGO_TERM_COLOR: always
  
Creating virtualenv haem-9fcuxZH6-py3.12 in C:\Users\runneradmin\AppData\Local\pypoetry\Cache\virtualenvs
Using virtualenv: C:\Users\runneradmin\AppData\Local\pypoetry\Cache\virtualenvs\haem-9fcuxZH6-py3.12
Installing dependencies from lock file
Finding the necessary packages for the current system
Package operations: 14 installs, 0 updates, 0 removals
  � Installing colorama (0.4.6)
cargo fmt --check
cargo clippy
   Compiling pyo3-build-config v0.19.2
   Compiling pyo3-ffi v0.19.2
   Compiling pyo3 v0.19.2
    Checking haem v0.1.0 (D:\a\haem\haem)
    Finished dev [unoptimized + debuginfo] target(s) in 8.35s
poetry run isort . --check
'isort' is not recognized as an internal or external command,
```

I'll do a bit more poking around when I get time later

**Comment by BooleanCat** [comment]
The `--no-ansi` flag also didn't help

**Comment by BooleanCat** [comment]
For some reason this error stopped happening when I re-ordered my CI steps such that I build my rust wheel (with maturin) after I install poetry dependencies. I have no idea why 🤷
