### ISSUE TITLE
Connection pool is full, discarding connection: pypi.org. Connection pool size: 10

### ISSUE THREAD

**Issue by jmgilman** [python-poetry/poetry#8469]
- **Poetry version**: v1.6.1
- **Python version**: v3.12.0rc2
- **OS version and name**: Ubuntu 22.04
- **pyproject.toml**: https://gist.github.com/jmgilman/97a3c2ee32c5c7ad5d69390790fbf377

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

It seems there's been a long-running issue when using Poetry to install dependencies on a machine with a large number of cores. Specifically, when installing, the following message is spammed many times (depending on the number of cores):

```
Connection pool is full, discarding connection: pypi.org. Connection pool size: 10
```

It appears to be related to exceeding the default connection pool size of `urllib3` which is 10. I would expect Poetry to set this value to at least be equal to the number of workers being used. As it stands, the only workaround is :

```
poetry config installer.max-workers 10
```

Is there a technical reason why this issue cannot be resolved? I've seen the above "fix" in dozens of projects. Why has it not been addressed? If there is a technical reason, why not hard code the max worker limit at 10?

**Comment by dimbleby** [comment]
this is just a benign warning, I expect no-one has found it worthwhile to do anything about it

if it bothers you, then probably a merge request tidying it up would be accepted

**Comment by florczakraf** [comment]
It seems to be related to the `HTTPRepository` not setting `Authenticator`'s `pool_size`, which then defaults to 10 (which is usually smaller than than `os.cpu_count()+4` that's used as a default value for `installer.max-workers`).
