### ISSUE TITLE
A new command that replaces pipx

### ISSUE THREAD

**Issue by robertlagrant** [python-poetry/poetry#8470]
## Feature Request

[pipx](https://github.com/pypa/pipx) allows the (installing and) running of commands in an isolated environment without installing anything into a developer's local environment, nor into the global Python interpreter.

E.g. I can execute `pipx run pip-licenses > third-party-licences.txt` and that command will run, installing if necessary, and it won't pollute the local virtual environment.

It would be a developer convenience if we didn't have to install Poetry and Pipx as global commands, but instead if Poetry had the same ability as Pipx to install to a global (but separate) environment and run commands installed from there. Then we only need to ensure Poetry is installed and another use case is covered.

E.g. `poetry runx pip-licenses`

**Comment by dimbleby** [comment]
pipx is a fine tool and I don't imagine anyone here has any wish to rewrite it.  Just use pipx!

**Comment by Secrus** [comment]
This might be a plugin candidate, but it's definitely not something we plan on adding (or maintaining later).
