### ISSUE TITLE
Python version not satisfied when it should be (?

### ISSUE THREAD

**Issue by guilledk** [python-poetry/poetry#8473]
- **Poetry version**: 1.6.1
- **Python version**: 3.11.5
- **OS version and name**: Arch Linux v6.4.12-arch1-1  x86_64 GNU/Linux 
- **pyproject.toml**: https://gist.github.com/guilledk/c826ed4ce428ffc189cac2e8082cc7f7

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

Hello I've recently started switching my projects to use `poetry` from `pip` and Its been great, only issue tho is I'm trying to convert a project that worked with `pip` and its failing during dependency resolution: 

```
Resolving dependencies... Downloading https://files.pythonhosted.org/packages/32/4d/aaf7eff5deb402fd9a24a1449a8119f00d74ae9c2efa79f8ef9994261fc2/pytz-2023.3.post1-py2.py3-none-any.whl (882.1s)

The current project's Python requirement (>=3.10.0,<4.0.0) is not compatible with some of the required packages Python requirement:
  - scipy requires Python <3.13,>=3.9, so it will not be satisfied for Python >=3.13,<4.0.0

Because scipy (1.11.2) requires Python <3.13,>=3.9
 and no versions of scipy match >1.11.2,<2.0.0, scipy is forbidden.
So, because skynet depends on scipy (^1.11.2), version solving failed.

  • Check your dependencies Python requirement: The Python requirement can be specified via the `python` or `markers` properties

    For scipy, a possible solution would be to set the `python` property to ">=3.10.0,<3.13"

    https://python-poetry.org/docs/dependency-specification/#python-restricted-dependencies,
    https://python-poetry.org/docs/dependency-specification/#using-environment-markers
```

Doing `python = ^3.10` should work if scipy requires `Python <3.13,>=3.9` right?

Thanks in advance and sorry for inconvinience

**Comment by dimbleby** [comment]
No

please read the faq - https://python-poetry.org/docs/faq/#why-is-poetry-telling-me-that-the-current-projects-python-requirement-is-not-compatible-with-one-or-more-packages-python-requirements - and close
