### ISSUE TITLE
Poetry add doesn't match pip install on adding Pytorch

### ISSUE THREAD

**Issue by alon1samuel** [python-poetry/poetry#8474]
- **Poetry version**: 1.5.1
- **Python version**: 3.11.5
- **OS version and name**: Ubuntu 22.04
- **pyproject.toml**: https://gist.github.com/alon1samuel/ae7b5817730549b7209ecbe9a35baf0b.js

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

I'm adding torch using `poetry add torch` but then when I'm importing it in python I get the following error:

```python
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "*******************/virtualenvs/torch-poetry-CmT3HHKY-py3.11/lib/python3.11/site-packages/torch/__init__.py", line 229, in <module>
    from torch._C import *  # noqa: F403
    ^^^^^^^^^^^^^^^^^^^^^^
ImportError: libcupti.so.11.7: cannot open shared object file: No such file or directory

```

Steps to reproduce (in bash):
```
poetry init
poetry add torch
poetry shell
python
>>> import torch
```

Steps to verify with pip (bash):
```
virtualenv venv
source venv/bin/activate
pip install torch
python
>>> import torch
```

**Comment by dimbleby** [comment]
duplicate #7902, #8002 etc please close
