### ISSUE TITLE
Packages in src directory cannot be imported into tests

### ISSUE THREAD

**Issue by gregbrowndev** [python-poetry/poetry#8477]
- **1.6.1**: 
- **3.10.9**: 
- **Ubuntu 23.04**: 
- **pyproject.toml**: 

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

Hi, I know there has been a lot of discussion around Poetry's support for the `src` directory. Over the last few years of revisiting this issue, I still haven't found a solution for this. When we create a package in the `src` directory, we need to be able to run tests against it as well as bundle it up into the a distribution (if we need to do that at all).

The benefits I see for using a `src` directory are mainly:

- if our project has multiple packages, its nice to separate them so we just have a `src` and ` test` directory at the top level
- putting packages in `src` forces them to be installed as a dependency within the virtual environment in order to test them (exactly the issue here). We used to use `pip install -e src/my_package` for this. This can avoid packaging issues down the line.

However, after following the steps to create a new project in Poetry, I've found that I cannot import the modules into the test (without having `src.my_package` in the import or tweaking the python path, which defeats the point of the second point above). 

Steps to reproduce:

- Create a new Poetry project with `src` directory: `poetry new --src my-package`

  This will create the directory structure:
  
  ```
  my-package/
  ├─ src/
  │  ├─ my_package/
  │  │  ├─ __init__.py
  ├─ tests/
  │  ├─ __init__.py
  ├─ pyproject.toml
  ```
  
  and a _pyproject.toml_:
  
  ```toml
  [tool.poetry]
  name = "my-package"
  version = "0.1.0"
  description = ""
  authors = []
  readme = "README.md"
  packages = [{include = "my_package", from = "src"}]
  
  [tool.poetry.dependencies]
  python = "^3.10"
  
  [build-system]
  requires = ["poetry-core"]
  build-backend = "poetry.core.masonry.api"
  ```

- Install pytest: `poetry add --dev pytest`
- Add a module to package *src/my_package/constants.py*:

  ```py
  # src/my_package/constants.py
  MESSAGE = "Hello, world!"
  ```
- Add a test: *tests/test_my_package.py*:

  ```py
  from my_package import MESSAGE
  
  def test_message():
      assert MESSAGE == "Hello, world!"
      
  ```
  
 - Run tests: `poetry run pytest tests/`
 
 Error:
 
 ```
 Traceback:
/home/greg/.pyenv/versions/3.10.9/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_my_package.py:1: in <module>
    from my_package import MESSAGE
E   ModuleNotFoundError: No module named 'my_package'
 ```
 
 I would expect the `packages` configuration in _pyproject.toml_, i.e.
 
 ```toml
packages = [{include = "my_package", from = "src"}]
 ```
 
 would make the package available to the tests to import, similar to how the `editable` flag works in `pip install`.
 
Perhaps, better documentation is needed to explain how to resolve this. Otherwise, I don't see why the `--src`  feature is advertised in the docs if you have to hack around with the `PYTHON_PATH` environment variable yourself to get your tests working. 
 
 
 Thanks a lot!

**Comment by finswimmer** [comment]
Looks like you forgot to run `poetry install`.

**Comment by gregbrowndev** [comment]
@finswimmer thanks for the suggestion but that doesn't resolve the issue. In fairness, in this simple demo I didn't run `poetry install`, but assumed running `poetry add --dev pytest` would be enough since it creates the lock file which isn't created by `poetry new`. 

But nonetheless, `poetry run pytest tests/` results in the same error. Am I missing something?

**Comment by gregbrowndev** [comment]
I saw it suggested on another thread that running `poetry show -t` should show all the installed packages as well as the ones "auto detected" or configured within the project. I don't see `my_packge` in that dependency tree.

**Comment by finswimmer** [comment]
Poetry itself uses the `src` layout without any problems. Also your demo project is working for me.

Running `poetry install` at least once is neccessary to install the current project in editable mode. You should see something like:

```
Installing the current project: my-package (0.1.0)
```

at the end of the process.

**Comment by gregbrowndev** [comment]
Thanks, it is also working now for me! I think my activated environment was skewed by another project when running these commands in my IDE. Thanks for the help will close!
