### ISSUE TITLE
poetry config virtualenvs.in-project true not working

### ISSUE THREAD

**Issue by TiansuYu** [python-poetry/poetry#8480]
- **Poetry version**:  Poetry (version 1.6.1)
- **Python version**: Python 3.11.4
- **OS version and name**: Platform:  darwin, OS:  posix (Mac M1)
- **pyproject.toml**: 

- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
`poetry config virtualenvs.in-project true`  changes nothing. Run `poetry config --list` after this returns me 
```
cache-dir = "/Users/xxxx/Library/Caches/pypoetry"
experimental.system-git-client = false
installer.max-workers = null
installer.modern-installation = true
installer.no-binary = null
installer.parallel = true
virtualenvs.create = true
virtualenvs.in-project = false
virtualenvs.options.always-copy = false
virtualenvs.options.no-pip = false
virtualenvs.options.no-setuptools = false
virtualenvs.options.system-site-packages = false
virtualenvs.path = "{cache-dir}/virtualenvs"  # /Users/tiansu.yu/Library/Caches/pypoetry/virtualenvs
virtualenvs.prefer-active-python = false
virtualenvs.prompt = "{project_name}-py{python_version}"
```

**Comment by dimbleby** [comment]
please provide a way to reproduce eg through a dockerfile

it works fine for me:
```console
$ poetry config --list | grep in-project
virtualenvs.in-project = null
$ poetry config virtualenvs.in-project true
$ poetry config --list | grep in-project
virtualenvs.in-project = true
```

**Comment by TiansuYu** [comment]
So likely would be some issues on my local env. Thanks for testing it out. Close this for now, as I likely won't be able to produce a reproducible container environment any time soon.
