### ISSUE TITLE
Installing on Windows with Microsoft Store Python is confusing

### ISSUE THREAD

**Issue by crazytan** [python-poetry/poetry#8486]
- **Poetry version**: n/a
- **Python version**: 3.11
- **OS version and name**: Windows 11
- **pyproject.toml**: 

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
I have Python 3 installed from Microsoft Store and I installed poetry with `(Invoke-WebRequest -Uri https://install.python-poetry.org -UseBasicParsing).Content | python -`. However, I am unable to find the poetry installation at `%APPDATA%\pypoetry`. I tried running the same command again but it said poetry already installed. I even tried debugging the installation script and everything including `data_dir` looks normal, but I just can't find the installation.

I suspect this is an issue caused by MS Store Python, as everything went normal after I uninstalled this version and installed one from python.org

**Comment by dimbleby** [comment]
wrong repository - you want https://github.com/python-poetry/install.python-poetry.org

this currently seems to me to be unactionable: you say you've done some debugging and everything looks normal, I don't know what you hope someone who doesn not have access to your computer can do with this information.

stll I expect a merge request will be welcome if and when you figure it out.

**Comment by crazytan** [comment]
My apology, didn't realize that there's a repo for the installation script.
