### ISSUE TITLE
ConfigParser incompatibility by multiple [tool.poetry.source] sections

### ISSUE THREAD

**Issue by Matesanz** [python-poetry/poetry#8490]
- **Poetry version**: Poetry (version 1.6.1)
- **Python version**: Python 3.11.5 [GCC 10.2.1 20210110] on linux
- **OS version and name**: Ubuntu 20.04
- **pyproject.toml**:

The important part:

```toml
[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.103"
pydantic = "^2.4"

[tool.poetry.group.dev.dependencies]
black = "^22.8.0"
isort = "^5.10.1"
pydocstyle = "^6.1.1"
pycodestyle = "^2.11.0"
pylint = "^2.17.5"
pytest = "^7.1.3"

[[tool.poetry.source]]
name = "PyPI"
priority = "primary"

[[tool.poetry.source]]
name = "torch_cpu"
url = "https://download.pytorch.org/whl/cpu"
priority = "supplemental"
```

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

:point_right:  TLDR; Current Poetry `pyproject.toml` section behaviour when adding multiple sources is not compatible with the python `configparser` module.

:information_source:  Currently, when adding multiple sources to Poetry, all of them have the **same section name** `[tool.poetry.source]` (as you can see in the pyproject.toml). So when trying to read that file with the default python **ConfigParser** Module an **`configparser.DuplicateSectionError` exception is raised**. ConfigParser is used by other packages (like, in this case, pycodestyle) to read the `pyproject.toml` file. Making them incompatible with Poetry.

```python
$ pycodestyle main.py --config=pyproject.toml

Traceback (most recent call last):
  File "/home/vscode/.pyenv/versions/3.11.5/bin/pycodestyle", line 8, in <module>
    sys.exit(_main())
             ^^^^^^^
  File "/home/vscode/.pyenv/versions/3.11.5/lib/python3.11/site-packages/pycodestyle.py", line 2636, in _main
    style_guide = StyleGuide(parse_argv=True)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.pyenv/versions/3.11.5/lib/python3.11/site-packages/pycodestyle.py", line 2295, in __init__
    options, self.paths = process_options(
                          ^^^^^^^^^^^^^^^^
  File "/home/vscode/.pyenv/versions/3.11.5/lib/python3.11/site-packages/pycodestyle.py", line 2593, in process_options
    options = read_config(options, args, arglist, parser)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.pyenv/versions/3.11.5/lib/python3.11/site-packages/pycodestyle.py", line 2518, in read_config
    config.read(cli_conf)
  File "/home/vscode/.pyenv/versions/3.11.5/lib/python3.11/configparser.py", line 713, in read
    self._read(fp, filename)
  File "/home/vscode/.pyenv/versions/3.11.5/lib/python3.11/configparser.py", line 1086, in _read
    raise DuplicateSectionError(sectname, fpname,
configparser.DuplicateSectionError: While reading from 'pyproject.toml' [line 49]: section '[tool.poetry.source]' already exists
```

**Comment by dimbleby** [comment]
`pyproject.toml` is a toml file, you should not use `ConfigParser` to parse toml.

please close.

**Comment by Matesanz** [comment]
Left [related issue in pycodestyle project](https://github.com/PyCQA/pycodestyle/issues/1198). Closing.
