### ISSUE TITLE
virtualenvs.options.system-site-packages doesn't work as expected

### ISSUE THREAD

**Issue by niniack** [python-poetry/poetry#8493]
- **Poetry version**: Poetry (version 1.7.0.dev0) and Poetry (version 1.6.1)
- **Python version**: 3.8.10
- **OS version and name**: Pop!_OS 22.04 LTS
- **pyproject.toml**: 

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## To reproduce

Create a Dockerfile
```
# Start from the NVIDIA PyTorch image
FROM nvcr.io/nvidia/pytorch:22.12-py3

ENV DEBIAN_FRONTEND=noninteractive

# Set Poetry variables
# The system site packages are important because we are using docker to give 
# us torch!
ENV POETRY_NO_INTERACTION=1 \
    POETRY_VIRTUALENVS_IN_PROJECT=1 \
    POETRY_VIRTUALENVS_CREATE=1 \
    POETRY_CACHE_DIR=/tmp/poetry_cache \
    POETRY_HOME=/opt/poetry \
    POETRY_VIRTUALENVS_OPTIONS_SYSTEM_SITE_PACKAGES=1

WORKDIR /library

# Install poetry with pinned version
RUN pip install git+https://github.com/python-poetry/poetry.git@master
ENV PATH="$PATH:$POETRY_HOME/bin"
```
Build and run docker container
```
docker build -t library .
docker run -it -v "$(pwd):/library" library
```

Verify that poetry system-site-packages is set to true
```
root@5c60f989a2c5:/library# poetry config --list
cache-dir = "/root/.cache/pypoetry"  # /tmp/poetry_cache
experimental.system-git-client = false
installer.max-workers = null
installer.modern-installation = true
installer.no-binary = null
installer.parallel = true
virtualenvs.create = true
virtualenvs.in-project = true
virtualenvs.options.always-copy = false
virtualenvs.options.no-pip = false
virtualenvs.options.no-setuptools = false
virtualenvs.options.system-site-packages = true
virtualenvs.path = "{cache-dir}/virtualenvs"  # /tmp/poetry_cache/virtualenvs
virtualenvs.prefer-active-python = false
virtualenvs.prompt = "{project_name}-py{python_version}"
```

Also check the config of virtualenv
```
root@5c60f989a2c5:/library# cat .venv/pyvenv.cfg 
home = /usr/bin
implementation = CPython
version_info = 3.8.10.final.0
virtualenv = 20.24.5
include-system-site-packages = false
base-prefix = /usr
base-exec-prefix = /usr
base-executable = /usr/bin/python3.8
prompt = continualutils-py3.8
```

Check python paths
```
root@5c60f989a2c5:/library# python -c "import sys; print(sys.path)"
['', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/usr/local/lib/python3.8/dist-packages', '/usr/lib/python3/dist-packages']

root@5c60f989a2c5:/library# poetry run python -c "import sys; print(sys.path)"
['', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/library/.venv/lib/python3.8/site-packages']
```

Import torch 
```
root@5c60f989a2c5:/library# python -c "import torch; print(torch.__version__)"
1.14.0a0+410ce96

root@5c60f989a2c5:/library# poetry run python -c "import torch; print(torch.__version__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'torch'
```

## Issue
Hi, 

I believe this is related to issue #6035, which has been closed by PR #8359. This is why I've tried this on both the 1.6.1 release as well as the master branch (1.7.0.dev0), but I get exactly the same results. Given that I have set `POETRY_VIRTUALENVS_OPTIONS_SYSTEM_SITE_PACKAGES=1` and verified that `virtualenvs.options.system-site-packages=true`, I expect that:

1) the output of ` poetry run python -c "import sys; print(sys.path)"` should include `/usr/local/lib/python3.8/dist-packages`
2) `include-system-site-packages = false` in pyenv.cfg should be `true`
3) importing torch should work with `poetry run python`

However, when I go in and manually update `pyenv.cfg`  `include-system-site-packages = true`, then

```
root@5c60f989a2c5:/library# poetry run python -c "import torch; print(torch.__version__)"
1.14.0a0+410ce96
```

works as expected. However, I feel like I shouldn't be touching that file, right? It seems like I'm doing something that could potentially have some issues?

**Comment by dimbleby** [comment]
duplicate #5906

**Comment by niniack** [comment]
Oh, thank you for the find, it seems like I did a poor job looking through past issues.
