### ISSUE TITLE
Missing value for pypi-token.pypi config value results in the wrong error message.

### ISSUE THREAD

**Issue by radoshi** [python-poetry/poetry#8503]
- **Poetry version**: 1.6.1
- **Python version**: 3.11.5
- **OS version and name**: MacOS 13.5.2
- **pyproject.toml**: https://gist.github.com/radoshi/898f4f8fad33341d0714921f378bbef6

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below. https://gist.github.com/radoshi/70f1215ca969c8055715d207586d2f80

## Issue
When executing `poetry config pypi-token.pypi`, if the value is missing, poetry returns the error 
> There is no pypi-token.pypi setting.

This error is rather confusing. It should say that the value is missing.

Real scenario where this happened: I'm using poetry to publish to pypi from a GH release action. I misconfigured the secret, so its not available, which results in an empty string. This results in the GH action failing with `There is no pypi-token.pypi setting.` 

I imagine that people trying to configure a GH action would get similarly confused as me and go down the rabbit hole of making sure that they got poetry install and version correct etc.

I have a draft PR here that I'm happy to convert into a real PR if you would like:
https://github.com/python-poetry/poetry/pull/8502

**Comment by radoering** [comment]
IMO, it makes sense to improve the message.

**Comment by radoshi** [comment]
Thanks. Took your suggestions and PR is now ready for review.
