### ISSUE TITLE
Unable to Activate Poetry venv With PowerShell AllSigned Execution Policy

### ISSUE THREAD

**Issue by jferry-pm** [python-poetry/poetry#8506]
- **Poetry version**: 1.6.1
- **Python version**: 3.8.10
- **OS version and name**: Windows 10
- **pyproject.toml**: N/A

- [x ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x ] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

Unlike activate.ps1 for virtual environments created via venv, the activate.ps1 script for virtual environments created via poetry are not digitally signed. This means that for corporations that mandate digital signing from a trusted publish for all PowerShell scripts (via an ```AllSigned``` execution policy), there is currently no way to activate a poetry virtual environment via ```poetry shell```

This issue only impacts the ability to activate a poetry created virtual environment, all other commands such as ```install, build, publish``` are not impacted.

The root cause of this seems to be due to the fact that the underlying package used for managing virtual environments ```virutalenv``` is not signing the script used to activate virtual environments. Are there any known workarounds for this without modifying the execution policy?

Export from attempting to run ```poetry shell``` below shows the blocking due to execution policy, as ```activate.ps1``` is not digitally signed.

```
PS C:\proj\tests\ProjectA> poetry shell
Spawning shell within C:\proj\pypoetry\Cache\virtualenvironments\projecta-uic7HEm2-py3.8
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

File C:\proj\pypoetry\Cache\virtualenvironments\projecta-uic7HEm2-py3.8\Scripts\activate.ps1 cannot be loaded. The
file C:\proj\pypoetry\Cache\virtualenvironments\projecta-uic7HEm2-py3.8\Scripts\activate.ps1 is not digitally signed.
You cannot run this script on the current system. For more information about running scripts and setting execution
policy, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
    + CategoryInfo          : SecurityError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnauthorizedAccess
```

PS Execution Policy is set to ```AllSigned``` at ```MachinePolicy``` scope
```
PS C:\> Get-ExecutionPolicy -list

        Scope ExecutionPolicy
        ----- ---------------
MachinePolicy       AllSigned
   UserPolicy       Undefined
      Process    Undefined
  CurrentUser       Undefined
 LocalMachine       Undefined
 ```

**Comment by dimbleby** [comment]
seems like a question for virtualenv, not poetry.  You might start at https://github.com/pypa/virtualenv/issues/816

if you don't like the virtual environments that poetry creates: just don't use them.  Create and active your own however you like.
