### ISSUE TITLE
Does poetry build support dynamic dependencies?

### ISSUE THREAD

**Issue by mil-ad** [python-poetry/poetry#8509]
I'm trying to use dynamic metadata suggested [here](https://stackoverflow.com/a/73600610/298209) to include a pinned requirements.txt for my deployable application (i.e. not a library):

```
[project]
dynamic = ["dependencies"]
[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}
```

However the generated package with `poetry build` doesn't use/include it. Is this supported by poetry?

**Comment by dimbleby** [comment]
no

**Comment by mil-ad** [comment]
any plans to add support any time soon? How does one build a package in poetry with pinned versions?

**Comment by clintonroy** [comment]
The strong theme of poetry is use and supply static metadata, there's next to no chance of adding anything dynamic, for that, use a different back end.

If you want to pin package versions, pin them as dependencies e.g. poetry add foobarbaz=1.2.3.4 will pin dependency foobarbaz at version 1.2.3.4.
