### ISSUE TITLE
Local developping modules ill referenced by VSCode's "go to definition"

### ISSUE THREAD

**Issue by francoisWeber** [python-poetry/poetry#8513]
# Context
Environment from `poetry debug info` : 
```
Poetry
Version: 1.5.1
Python:  3.11.5

Virtualenv
Python:         3.11.5
Implementation: CPython
Path:           /Users/f.weber/Library/Caches/pypoetry/virtualenvs/query-index-attribution-bB1GeDKq-py3.11
Executable:     /Users/f.weber/Library/Caches/pypoetry/virtualenvs/query-index-attribution-bB1GeDKq-py3.11/bin/python
Valid:          True

System
Platform:   darwin
OS:         posix
Python:     3.11.5
Path:       /opt/homebrew/opt/python@3.11/Frameworks/Python.framework/Versions/3.11
Executable: /opt/homebrew/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/bin/python3.11
```

OS is Mac Ventura 13.3.1

I consider a mono-repo holding a main `pyproject.toml` (see sanitized version [here](https://gist.github.com/francoisWeber/d755f87b5e3ce9d0bf114b620bf143d8)) that mainly references a few sub-libraries of my own ; among them a certain `some_local_lib`. Each sub-lib has a dedicated `pyproject.toml` holding its own requirements. See a gist for the pyproject.toml of  `some_local_lib` [here](https://gist.github.com/francoisWeber/98da1f7984859cbb905585e76db8476a).

As shown on the gist, the main `pyproject.toml` requires `some_local_lib` with a relative path and a `develop = true` tag:
```toml
some_local_lib = { path = "./lib/some_local_lib/", develop = true }
```

Finally, I have a few scripts in the project's directory that use `from some_local_lib import stuff` to work. 

When I want to init or reset my project, I just type `poetry install` in order to get every reqs in the virtualenv + making venv's Python aware of my local `some_local_lib`. Everything works fine so far and I can launch my scripts without trouble.

# Description of the problem 

My problem occurs on VSCode (I don't know if this could happen elsewhere) when I use the "go to definition" (keyboard F12) feature of some symbol `some_symbol` imported from `some_local_lib` through `from some_local_lib.stuff import symbol`. I expected this to open the symbol's definition from the path `root_dir_of_project/lib/some_local_lib/stuff.py`. What actually happens is that it opens `/Users/me/Library/Caches/pypoetry/virtualenvs/my_project_someHash-py3.11/lib/python3.11/site-packages/some_local_lib/stuff.py`.
This is very annoying since I actively work on these sources and I would like Poetry/VSCode to open the working version of `stuff.py`, not the packaged and frozen version of it. 

Is it a bug or rather a misuse of the Poetry configuration ?

Thank you :)

**Comment by dimbleby** [comment]
please figure out whether this is a poetry question or a vscode question

I expect that poetry is correctly installing the path dependency in the virtual environment that it manages, and you have vscode picking up some other virtual environment.

If so, there is nothing that poetry can do about that

**Comment by lyogev** [comment]
I think it may be related to this issue
https://github.com/microsoft/pylance-release/issues/3473
I wonder how poetry can help support compat/strict editable mode

**Comment by dimbleby** [comment]
ah yes, that sounds right.  Not a poetry bug then.

**Comment by francoisWeber** [comment]
Ok my bad, guys :) Thanks for highlighting the related PyLance issue :) I'll close the issue.

**Comment by manulera** [comment]
@francoisWeber Did you figure out a workaround?

**Comment by francoisWeber** [comment]
Not yet but I had no time to dig into this problem for the moment.
