### ISSUE TITLE
Some output from `poetry install -vvv` is lost when directing it to a file

### ISSUE THREAD

**Issue by sfrk** [python-poetry/poetry#8515]
- **Poetry version**: 1.6.1
- **Python version**: 3.11.5
- **OS version and name**: Fedora Linux 38 (Workstation Edition) 64-bit
- **pyproject.toml**: https://gist.github.com/sfrk/e8f6f10fe72373f9b8b508d86973a6ed

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

### Summary

Parts of the output of `$ poetry install -vvv` is lost when directing stdout and stderr to a file.

### Reproduction steps

1. Create an empty directory and put the [pyproject.toml file that I linked above](https://gist.github.com/sfrk/e8f6f10fe72373f9b8b508d86973a6ed) into it.
2. Run `$ poetry install` to install dependencies.
3. Run `$ poetry install -vvv`. Notice its output; on my machine, it looks like this (note the lines that say 'Pending'):

![image](https://github.com/python-poetry/poetry/assets/84384405/fe752162-0551-4d36-832d-7687d0e62865)

4. Run `$ poetry install -vvv > out.txt 2>&1` to direct both stdout and stderr to a file `out.txt`. This should produce no output in the terminal.
5. Run `$ cat out.txt`. Notice that the lines that say 'Pending' are missing from the file:

![image](https://github.com/python-poetry/poetry/assets/84384405/f1cf9bf3-9ee8-4320-9011-4c865a134c02)

#### Looking at the source

Looked at [`src/poetry/installation/executor.py:270`](https://github.com/python-poetry/poetry/blob/47a3a19c442c21aa5b2836ea092dda8ae4d13151/src/poetry/installation/executor.py#L270C41-L270C41) to see how the 'Pending' line is printed.

I can see that the 'Pending' line is printed to a 'section' [line 268](https://github.com/python-poetry/poetry/blob/47a3a19c442c21aa5b2836ea092dda8ae4d13151/src/poetry/installation/executor.py#L268) with `self._sections[id(operation)].write_line()` and that the 'Skipped' line is printed directly to `io`. 

I've tried to figure out how that fits together, so I created [a new test project that defines a cleo command that creates a section and calls `write_line` on that section]( to see if I could reproduce the issue, but I couldn't: `$ poetry run python main.py greet johndoe > out.txt` produces a file that contains both the outputs of `section.write_line` and `self.line`.

Thus, I don't think this "error" is intrinsic to how sections work in cleo; I think it must be something to do with poetry, maybe in how poetry configures cleo. I'm not sure.

#### Asking ChatGPT

I figured (still do) that there's some intricacy of Unix here that I don't understand, so I asked ChatGPT if there are other file descriptors outside of stdout and stderr that a program might write to for logging to a terminal. Its response was that the program might write "directly" to the terminal and included a Python program that it said did just that. It didn't; it just wrote to stdout.

### Workaround

I found another way of capturing all the output from the command: `$ script -c "poetry install -vvv" out.txt`

This gives me an out.txt file with the 'Pending' lines intact:

![image](https://github.com/python-poetry/poetry/assets/84384405/b8488713-fc65-4bac-8d8f-b1efbc31dc0e)

### Why I care

I'm trying to use the 'verbose' option on `$ poetry install` to debug a CI/CD pipeline in Gitlab. Specifically, I'm trying to ascertain whether `$ poetry install` installs from the local cache I've set up, or if it re-downloads dependencies. I can verify this just fine on my own machine – notice that the following doesn't say "Downloading" anywhere:

![image](https://github.com/python-poetry/poetry/assets/84384405/642f6ee3-14b2-4e98-a559-41ab42adfae8)

But in Gitlab CI/CD, all that nice output goes missing:

![image](https://github.com/python-poetry/poetry/assets/84384405/6615a4fa-a29e-43f6-aada-7792e8fd9d45)

...which is what led me to discover the "quirk" I outlined above, which I suspect might be related to my CI/CD issue.

**Comment by dimbleby** [comment]
`--ansi`

**Comment by sfrk** [comment]
@dimbleby Thanks! Running `$ poetry install -vvv --ansi > output.txt` does indeed direct everything to output.txt. If you have a couple of pointers as to why, I'd be super grateful – I don't quite understand why the choice of character set is affecting me here.

**Comment by dimbleby** [comment]
fancy colour codes and overwriting already printed lines require control characters that mostly only make sense in a terminal (and only in a terminal that supports them, come to that)

output to file is not such a terminal

**Comment by sfrk** [comment]
I've been suggested a workaround and have accepted that there are some gaps in my own understanding here. Closing.
