### ISSUE TITLE
`poetry install --sync` in conda env gives `Path [...] does not exist` error

### ISSUE THREAD

**Issue by joel-aws** [python-poetry/poetry#8516]
- **Poetry version**: 1.6.1
- **Python version**: 3.9.18
- **OS version and name**: macOS 13.5.2
- **pyproject.toml**: 
```
[tool.poetry]
name = "foo"
version = "0.0.0"
description = "foobar"
authors = ["bar"]

[tool.poetry.dependencies]
python = "^3.9"
pre-commit = "^3.3.3"

[tool.poetry.group.dev.dependencies]
pytest = "^7.3.1"
```

- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

In a conda environment (`conda activate my_env`), when running `poetry install --sync`, I get the following error:

```
  ValueError

  Path /home/conda/feedstock_root/build_artifacts/python-build_12345/work for build does not exist

  at ~/.pyenv/versions/miniconda3-latest/envs/my_env/lib/python3.9/site-packages/poetry/core/packages/path_dependency.py:80 in validate
       76│     def validate(self, *, raise_error: bool) -> bool:
       77│         if not self._validation_error:
       78│             return True
       79│         if raise_error:
    →  80│             raise ValueError(self._validation_error)
       81│         logger.warning(self._validation_error)
       82│         return False
       83│
       84│     @property

Path /home/conda/feedstock_root/build_artifacts/python-build_12345/work for build does not exist
```

I have attempted this with different versions of Python on different systems, and always get the same result. When running without `--sync`, it installs as expected.

**Comment by dimbleby** [comment]
feels like probably thisis a variation on https://github.com/python-poetry/poetry/issues/6408#issuecomment-1237278487, in which we learned that conda ships bogus `direct_url.json` files - thus confusing anyone who pays attention to them

**Comment by finswimmer** [comment]
Hello @joel-aws,

you haven't come back to this issue for a long while. So I assume this is solved in the meantime and I can close this ticket.

Feel free to leave a comment if you disagree.

fin swimmer
