### ISSUE TITLE
poetry cannot be installed in python3.12 environment

### ISSUE THREAD

**Issue by Airpy** [python-poetry/poetry#8518]
My python environment is installed using homebrew, and the current version is 3.12。

❯ python3.12 --version
Python 3.12.0

When I use the `curl -sSL https://install.python-poetry.org | python3.12 -` command to install, I get stuck at the `Installing Poetry (1.6.1): Creating environment` position and cannot continue.

I'm sure there's no problem with my network。

<img width="699" alt="image" src="https://github.com/python-poetry/poetry/assets/20046478/a744ef27-8640-44da-a5e0-9338087fe070">

**Comment by dimbleby** [comment]
Of course this works fine for lots of folk, including in poetry's own pipelines.

Do leave an update when you figure out what is different for you, perhaps the next person will appreciate it.

**Comment by Airpy** [comment]
I probably know the reason. It is caused by the company's global proxy
network. Just switch to the mobile hotspot network and it will be fine.
thank you for your reply。


David Hotham ***@***.***> 于2023年10月9日周一 04:50写道：
