### ISSUE TITLE
Poetry does not consider equivalent dependencies equivalent

### ISSUE THREAD

**Issue by td-anne** [python-poetry/poetry#8522]
- **Poetry version**: 1.6.1
- **Python version**: 3.11.4
- **OS version and name**: darwin

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

`poetry` supports depending on repositories available through git. You can specify `pydb = {git = "git@github.com:Transmission-Dynamics/pydb.git"}` and it will pull in the version from github. You can also specify this as `pydb = {git = "git+ssh://git@github.com/Transmission-Dynamics/pydb.git"}`. These are both internally normalized to the same thing. Unfortunately the dependency resolver does not consider them equivalent, giving rise to errors that look like:

```
Because da-video-tools (0.1.7) @ git+ssh://git@github.com/Transmission-Dynamics/da-video-tools.git@HEAD depends on pydb (0.1.0) @ git+ssh://git@github.com/Transmission-Dynamics/pydb.git@pip-installable
 and da-depth-reconstruction depends on pydb (0.1.0) @ git+ssh://git@github.com/Transmission-Dynamics/pydb.git, da-video-tools is forbidden.
So, because da-depth-reconstruction depends on da-video-tools (0.1.7) @ git+ssh://git@github.com/Transmission-Dynamics/da-video-tools.git, version solving failed.
```

That is, the dependency format emitted is *identical*, but because two packages in the dependency tree specify them using the two different forms, `poetry` considers them incompatible. 

Since `poetry` clearly normalizes this sort of dependency internally, it should compare the normalized versions rather than the raw. Failing that, it should report the non-normalized versions when claiming a conflict. The current situation can be mystifying.

The current workaround is to go through the whole dependency tree ensuring that every package in it uses the same form of specifying the dependency.

**Comment by dimbleby** [comment]
Duplicate #3113
