### ISSUE TITLE
Latest poetry under Python 3.8 fails to resolve numpy + opencv-python properly

### ISSUE THREAD

**Issue by andronat** [python-poetry/poetry#8525]
- **Poetry version**: 1.6.1
- **Python version**:
```
Poetry
Version: 1.6.1
Python:  3.8.17

Virtualenv
Python:         3.8.17
Implementation: CPython
Path:           /home/vscode/.cache/pypoetry/virtualenvs/test-KG2-rD7C-py3.8
Executable:     /home/vscode/.cache/pypoetry/virtualenvs/test-KG2-rD7C-py3.8/bin/python
Valid:          True

System
Platform:   linux
OS:         posix
Python:     3.8.17
Path:       /nix/store/ac4aywjapkrd2z7m9sr28xwbi30al7ws-python3-3.8.17
Executable: /nix/store/ac4aywjapkrd2z7m9sr28xwbi30al7ws-python3-3.8.17/bin/python3.8
```
- **OS version and name**:
```
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy
```
- **pyproject.toml**:
```
[tool.poetry]
name = "test"
version = "0.1.0"
description = ""
authors = ["Anastasios Andronidis"]

[tool.poetry.dependencies]
python = "~3.8"
numpy = "1.19.5"
opencv-python = "4.7.0.68"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```

## Issue
The above `pyproject.toml` fails with:
```
Because opencv-python (4.7.0.68) depends on numpy (>=1.21.0)
 and orb-core depends on numpy (1.19.5), opencv-python is forbidden.
So, because orb-core depends on opencv-python (4.7.0.68), version solving failed.
```

This doesn't make any sense as `opencv-python (4.7.0.68)` should support `numpy (1.19.5)` as I can see [here](https://github.com/opencv/opencv-python/blob/339bca572ecd866b56df1f61214cbf03c5f276f2/setup.py#L32). 

Interestingly, manual `pip` works: `pip install numpy=="1.19.5" opencv-python=="4.7.0.68"`

**Comment by dimbleby** [comment]
Poetry builds cross platform solutions and the error is correct for Darwin.  Please close.

**Comment by andronat** [comment]
Do I have any options here? Or poetry just doesn't respect and resolve different OS dependencies separately?

**Comment by dimbleby** [comment]
read the docs https://python-poetry.org/docs/dependency-specification/#python-restricted-dependencies etc
