### ISSUE TITLE
 File name too long for cache with SQLAlchemy 1.4

### ISSUE THREAD

**Issue by andyhasit** [python-poetry/poetry#8529]
- **Poetry version**: 1.6.1
- **Python version**: 3.10.12
- **OS version and name**: Linux Mint 21.1
- **pyproject.toml**: See below.

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

Basic error saving cache for a wheel with a very long filename.

**pyproject.toml**:

```
[tool.poetry.dependencies]
python = ">=3.10.3,<3.11"
sqlalchemy = "^1.4"
...
```

```
Installing dependencies from lock file

Package operations: 0 installs, 4 updates, 0 removals

  • Updating sqlalchemy (1.3.24 -> 1.4.49): Failed

  OSError

  [Errno 36] File name too long: '/home/andrew/.cache/pypoetry/artifacts/07/ef/d7/f4e72ab224633e85fd96dd6c096d8c35b025ecaa3c6d7728b6d271f83b/tmp4abpmvjf' -> '/home/andrew/.cache/pypoetry/artifacts/07/ef/d7/f4e72ab224633e85fd96dd6c096d8c35b025ecaa3c6d7728b6d271f83b/SQLAlchemy-1.4.49-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl'

  at ~/.local/share/pypoetry/venv/lib/python3.10/site-packages/requests/utils.py:307 in atomic_open
       303│     tmp_descriptor, tmp_name = tempfile.mkstemp(dir=os.path.dirname(filename))
       304│     try:
       305│         with os.fdopen(tmp_descriptor, "wb") as tmp_handler:
       306│             yield tmp_handler
    →  307│         os.replace(tmp_name, filename)
       308│     except BaseException:
       309│         os.remove(tmp_name)
       310│         raise
       311│ 

The following error occurred when trying to handle this error:


  OSError

  [Errno 36] File name too long: '/home/andrew/.cache/pypoetry/artifacts/07/ef/d7/f4e72ab224633e85fd96dd6c096d8c35b025ecaa3c6d7728b6d271f83b/SQLAlchemy-1.4.49-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl'

  at /usr/lib/python3.10/pathlib.py:1206 in unlink
      1202│         Remove this file or link.
      1203│         If the path is a directory, use rmdir() instead.
      1204│         """
      1205│         try:
    → 1206│             self._accessor.unlink(self)
      1207│         except FileNotFoundError:
      1208│             if not missing_ok:
      1209│                 raise
      1210│ 
```

I have tried clearing the cache, and removing those directories, to no avail.

**Comment by dimbleby** [comment]
Most of that filename budget is being spent by sqlalchemy, I suggest you talk to them!

**Comment by andyhasit** [comment]
> Most of that filename budget is being spent by sqlalchemy, I suggest you talk to them!

It's quite common for Python wheels to have very long names like that. If you cd to your **~/.cache/pypoetry/artifacts** and run

```
find -name *.whl
```

You will see several popular packages which use very long wheel names. Here are some examples from my cache:

```
./d1/3a/de/ea7a3a7ac340db2e8350a88d81e1e67e98490b5d72b7bdaaf4406e5c8e/websockets-11.0.3-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl
./3d/90/1f/b66797c714be4f929357f68348ca409373753fb64b47fd417494ca6922/ruamel.yaml.clib-0.2.7-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl
./36/45/59/218a996aef470b16bf2f1ecd4fe3665e6f39e10bdd0a3c78cbfb6c1b2a/httptools-0.6.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl
./07/ef/d7/f4e72ab224633e85fd96dd6c096d8c35b025ecaa3c6d7728b6d271f83b/SQLAlchemy-1.4.49-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl
```

SQLAlchemy's wheel is 159 chars, and httptools is 114, so we can't really point the finger at SQLAlchemy for being a massive outlier. We must be pretty close to the FS limit a lot of the time and I'm really surprised this error doesn't happen more often.

What I'm thinking is that these are cache artifacts, whose path is already partly mangled via a one-way hash. So I wonder whether it is necessary to preserve the original name of the wheel. If it is, I wonder if we could perhaps shorten the last part of the path?

I tried installing with `--no-cache`  but that doesn't seem to do anything. I'm obviously able to install using pip directly as a work-around, but I think this is an issue which other poetry users will face, and is worth fixing here if it is indeed possible to rename the wheels.

There is a discussion on this at PIP/PEP level here: https://discuss.python.org/t/pep-440-total-character-length-limit-for-version-scheme/20880/16

**Comment by dimbleby** [comment]
... and did you talk to the sqlalchemy folk?

**Comment by andyhasit** [comment]
@dimbleby as I detailed 3 messages above, SQLalchemy is not the issue here. There are dozens of packages which (unreasonably but legally according to PYPI so far, see linked issue) produce very long wheel names, and we can't go around asking each one of them to rename their wheel because it doesn't play nice with poetry's cache mechanism.

Until PYPI produces guiledines limiting wheel path length, this issue can only be addressed by changing the file paths which poetry generates for its cache. 

```
./d1/3a/de/ea7a3a7ac340db2e8350a88d81e1e67e98490b5d72b7bdaaf4406e5c8e/websockets-11.0.3-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl
```

If the long SHA can be changed to an 8 letter short SHA as below, perhaps via a config option, then we're probably in the clear for some, but not all wheel name lengths and still don't run the risk of clashing with another package.

```
./d1/3a/de/ea7a3a7/websockets-11.0.3-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl
```

Alternatively if we can rename the wheel file itself, that would be even better.

I fully appreciate the difficulty finding the dev power required to make this change, and would help if I could (and may have another poke around in the coming weeks) but asking SQLalchemy to make a change (if they even can, given this wheel is already published for this version) is not a solution.

I've made a previous foray into the cache code thinking I could contribute a command to clear items from the cache by keyword but gave up, as you can just run something like `find  ~/.cache/pypoetry/artifacts -name numpy*.whl -delete`

**Comment by dimbleby** [comment]
it plainly isn't the case that there are significant numbers of packages with long names that are problematic for poetry: this issue tracker would see that if it were so.

I expect if you did talk to sqlalchemy they would tell you that wheels for their recent releases do not have such long names, and so you could address this by upgrading.

I'm not opposed to poetry's cache path being shortened to leave more space: but given we know of one example that people actually care about - and that example is already resolved - I find it hard to get excited about doing so.

**Comment by andyhasit** [comment]
@dimbleby that's fair. I felt "dozens" was a significant number but unless it's showing up on the issue tracker then there's quite rightly not much to motivate undertaking the work.

The issue with SQLalchemy is that there was nothing between 1.4 and 2.0  but I see they just last week issued a patch to 1.4 (first one since July) so there's hope. Will raise with them and see what they say,

Thanks for your input.
