### ISSUE TITLE
ConnectTimeoutError if two sources exists for two isolated networks

### ISSUE THREAD

**Issue by egorgam** [python-poetry/poetry#8537]
- **Poetry version**:  1.6.1
- **Python version**: 3.10
- **OS version and name**: Any

## Issue

I want to use poetry in private network with registry, and in public network with pypi. So, there are two environments no way connect to other source, and I add two sources to toml, and trying to setup them priority.

Looks like if primary source host is down, poetry may use a supplemental. Or it may be with two supplemental sources. But in that case it crashing with:

>  HTTPConnectionPool(host='X.X.X.X', port=X): Max retries exceeded with url: /repository/pypi-proxy/simple/psycopg/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xffffa46ce830>, 'Connection to X.X.X.X timed out. (connect timeout=15)'))

I think it's a bug.

**Comment by dimbleby** [comment]
Not a bug, all sources must be available during locking

**Comment by egorgam** [comment]
I found a simple workaround - adding source with same name in different dockerfiles, and removed lock from project repo. Not great, not terrible.
