### ISSUE TITLE
Why can't you use poetry to install requests?

### ISSUE THREAD

**Issue by Airpy** [python-poetry/poetry#8546]
❯ python -V
Python 3.12.0
❯ poetry --version
Poetry (version 1.6.1)

❯ poetry add requests
Using version ^2.31.0 for requests

Updating dependencies
Resolving dependencies... (0.1s)

The current project's Python requirement (>=2.7,<2.8 || >=3.4) is not compatible with some of the required packages Python requirement:
  **- requests requires Python >=3.7, so it will not be satisfied for Python >=2.7,<2.8 || >=3.4,<3.7**

Because no versions of requests match >2.31.0,<3.0.0
 and requests (2.31.0) requires Python >=3.7, requests is forbidden.
So, because daily-test depends on requests (^2.31.0), version solving failed.

  • Check your dependencies Python requirement: The Python requirement can be specified via the `python` or `markers` properties
    
    **For requests, a possible solution would be to set the `python` property to ">=3.7"**

    https://python-poetry.org/docs/dependency-specification/#python-restricted-dependencies,
    https://python-poetry.org/docs/dependency-specification/#using-environment-markers

**Comment by dimbleby** [comment]
please read the faq, then close this issue

**Comment by Airpy** [comment]
When I added `[tool.poetry.dependencies]` to `[tool.poetry.dependencies]` in the `pyproject.toml` file it solved the issue
