### ISSUE TITLE
Poetry can not parse version constraint from markers "platform_release"

### ISSUE THREAD

**Issue by Nikita-Sobolev** [python-poetry/poetry#8547]
- **Poetry version**: 1.5.1 and 1.6.1
- **Python version**: 3.11.4
- **OS version and name**: Linux / 5.10.16.3-microsoft-standard-WSL2
- **pyproject.toml**: https://gist.github.com/Nikita-Sobolev/615431e437564a57e8ceec8f8796f1a8

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

1) I have used `markers` option in pyproject.toml to specify `platform_release` parameter. It can `poetry lock` without a problem but can not `poetry install`. The error it meets is: `Could not parse version constraint: 5.10.16.3-microsoft-standard-WSL2`. Obviously, it can not match the `platform_release` with specified CONSTRAINTS from `poetry.core.constraints.version.pattern.py`. Please, fix it.
The issue can be easily reproduced with attached `pyproject.toml` running `poetry lock` and `poetry install`.

2) As you see in my `pyproject.toml` I used `in` operator to check `platform_release`. This is because when I use `3.14.1-x86_64-linode39` (which is the example from [pep](https://peps.python.org/pep-0508/#environment-markers:~:text=3.14.1%2Dx86_64%2Dlinode39)), in `pyproject.toml` I have it: `markers = "platform_release>='3.14.1-x86_64-linode39"`, it can not even `lock` and ends up with error: `Invalid marker for 'platform_release': >=3.14.1-x86_64-linode39`

**Comment by dimbleby** [comment]
duplicate #7418

**Comment by 62f** [comment]
IMHO having a release version which looks like an IPv4 address is against the accepted industry- standard convention of ```x.x.x```
<details>

**5.10.16.3**-microsoft-standard-WSL2
</details>
and as such should be causing parsing software headaches.

**Comment by supercheetah** [comment]
I'm running into this on Fedora 40, and running into this same issue with Poetry 1.8.3 and Python 3.11.9. In my case, it seems to be trying to parse the Fedora kernel version, which shows as "_6.9.4-200.fc40.x86_64_".

**Comment by dimbleby** [comment]
Still duplicate #7418.

**Comment by cashlo** [comment]
If anyone else is still having this issue and desperate to find a workaround like I did, one way to bypass this is go to your `site-packages/poetry/core/constraints/version/parser.py`

and manually add whatever constraint is causing the issue, change this according to your error:
```
    if constraint == "5.10.16.3-microsoft-standard-WSL2":
        version = Version.parse("5.10.16.3")
        return version
```
under parse_single_constraint()
