### ISSUE TITLE
The Windows path in the installation tutorial is incorrect.

### ISSUE THREAD

**Issue by brokedarius** [python-poetry/poetry#8566]
It should be:

%appdata%\Roaming\pypoetry\venv\Scripts\

%APPDATA%\Roaming\Python\Scripts

but the tutorial indicates:

%APPDATA%\pypoetry\venv\Scripts\poetry

%APPDATA%\Python\Scripts

nothing big but I thought this would be relevant for beginners like me.

**Comment by radoering** [comment]
AFAIK, on a typical Windows machine `%APPDATA%` is the same as `C:\Users\<username>\AppData\Roaming` (and there is no other `Roaming` directory inside). Maybe, you have an uncommon setup?

**Comment by artsakenos** [comment]
I want to report a further related issue.
In my case I have this settings
* Python 3.11.6 (installed from windows store)
* pip 23.2.1 

The installation process seems to go smoothly:
* (Invoke-WebRequest -Uri https://install.python-poetry.org -UseBasicParsing).Content | python -
        * It will add the `poetry` command to Poetry's bin directory, located at:
        * C:\Users\andre\AppData\Roaming\Python\Scripts
        * You can uninstall at any time by executing this script with the --uninstall option, and these changes will be reverted.
        * Poetry (1.6.1) is installed now. Great!
        * To get started you need Poetry's bin directory (C:\Users\andre\AppData\Roaming\Python\Scripts) in your `PATH` environment variable.
        * Alternatively, you can call Poetry explicitly with `C:\Users\andre\AppData\Roaming\Python\Scripts\poetry`.
 
But poetry is nowhere to be found. After searching in all Local and Roaming folders I found it at 
* C:\Users\andre\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\Roaming\pypoetry\venv\Scripts
* C:\Users\andre\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\Roaming\Python\Scripts

this makes me think that the target poetry folder is strictly related to the pip script source folder, which in case of windows app store python is put in some random location.

**Comment by brokedarius** [comment]
> AFAIK, on a typical Windows machine `%APPDATA%` is the same as `C:\Users\<username>\AppData\Roaming` (and there is no other `Roaming` directory inside). Maybe, you have an uncommon setup?

I have a fairly normal setup, latest version of python (non ms-store version) and latest pip.

**Comment by dimbleby** [comment]
it sounds as though you are simply mistaken then about where %APPDATA% is.

the docs should not reference `%appdata%\Roaming\pypoetry\venv\Scripts\` as you suggest, because that would have two `Roaming` in the path.

**Comment by swills1** [comment]
> AFAIK, on a typical Windows machine `%APPDATA%` is the same as `C:\Users\<username>\AppData\Roaming` (and there is no other `Roaming` directory inside). Maybe, you have an uncommon setup?

This is correct. 

`%appdata%\Roaming\` would result in `C:\Users\swills1\AppData\Roaming\Roaming`

@brokedarius If you open a File Explorer and navigate to `%appdata%` - it will take you to your Roaming folder.

It may be helpful if you;

1. Provide the steps you followed to setup
2. Share any error you got.

That will give a sort of baseline on what your setup looks like. 

I read through the Windows tutorial. Something to note is, it says to run;

`curl -sSL https://install.python-poetry.org | python3 -`

I install Python from the official site install when I install Python on Windows and all I have on Windows is Python 3. So for me, I don't need to do `python3`. Instead, I can do the following. (The tutorial does share the PS invoke command, and I should have maybe done that, but it should be essentially the same.)

`curl -sSL https://install.python-poetry.org | python -`

Which results in this;

![image](https://github.com/python-poetry/poetry/assets/4749950/feb3fae6-4992-4613-9630-c6f08b181442)

And I can run a version check;

![image](https://github.com/python-poetry/poetry/assets/4749950/6b1aef01-d63a-4c40-b0e9-9ec76d9d5803)

You may uninstall entirely and try again, but I thinkthis issue can be closed.
