### ISSUE TITLE
packages not detected after installing poetry

### ISSUE THREAD

**Issue by brokedarius** [python-poetry/poetry#8567]
Hi folks, probably something to do with venv but after installing poetry I am missing a lot packages installed with pip prior to installing poetry and there is no info in the docs on how to mitigate/fix that.

I used the powershell command to install:

`(Invoke-WebRequest -Uri https://install.python-poetry.org -UseBasicParsing).Content | py -`

Also if I try to uninstall a package it will try to uninstall the system one instead of the one in the virtualenv created by poetry but when I install it's the other way around making it a pain to remove them.

**Comment by dimbleby** [comment]
installing poetry doesn't cause other packages to be uninstalled, you've misunderstood something.

**Comment by brokedarius** [comment]
No it does not cause them to be uninstalled, I meant that they were missing from the paths. It feels like my reg. environment gets replaced by the one from poetry all my old packages are still on disk but not detected and when I try to re-install them it installs them in the new env. forgetting that the old one existed.

**Comment by dimbleby** [comment]
it is hard to tell what you are trying to report.  

What did you type?  What did you expect to happen?  What happened instead?

Please show the text output, rather than saying what it feels like.

**Comment by brokedarius** [comment]
Sadly enough to reproduce the issue I would have to reinstall poetry and I had enough trouble un-messing myself up that I would prefer to pass on that risk until I get comfortable with other packaging tools.

**Comment by brokedarius** [comment]
But thanks for your offer to help nevertheless.

**Comment by dimbleby** [comment]
then please close: there is nothing here that anyone can act on.
