### ISSUE TITLE
Allow use of `==latest` for installing packages

### ISSUE THREAD

**Issue by RenDelaCruz** [python-poetry/poetry#8569]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request

Some projects only allow the use of exact versions in the lock files, and not `^` or `~`, etc.

There should be the ability to use `poetry add package==latest`, like how we can currently use `package@latest`. Or at least add configuration within poetry so that `poetry add package` does not add a caret `^` to the version.

**Comment by abn** [comment]
Lock files already use exact versions. `pyproject.toml` indicates compatible ranges. 

If the project owner wants to add an exact version, I would imagine they already know what version they need. Additionally, this would end up creating a confusing ux.

For now I do not think we would want to implement this.
