### ISSUE TITLE
SSL certificate problem: certificate has expired

### ISSUE THREAD

**Issue by frchalaoux** [python-poetry/poetry#8570]
(base) frchalaoux$ curl -sSL https://install.python-poetry.org | python3 - --uninstall
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
(base) frchalaoux$ 
(base) frchalaoux$ pwd
/Users/frchalaoux
(base) frchalaoux$ curl -sSL https://install.python-poetry.org | python3 - --uninstall
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
(base) frchalaoux$ curl -sSL https://install.python-poetry.org | python3 - --uninstall
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situat

**Comment by dimbleby** [comment]
the certificate is fine, the problem must be at your end

**Comment by FabianElsmer** [comment]
Works fine for me as well
