### ISSUE TITLE
Proxy basic authentication doesn't work

### ISSUE THREAD

**Issue by raphaeljoie** [python-poetry/poetry#8576]
- **Poetry version**: `1.6.1`
- **Python version**: `3.11.6`
- **OS version and name**: linux Ubuntu
- **pyproject.toml**: 

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
I am working in a corporate environment with HTTP proxy (not HTTPS) using basic authentication. The username and passwords are provided with the url
```
HTTP_PROXY=http://username:password@proxy.local:8080
```
Later we are installing dependencies using git
```
poetry add git+https://any.repo.git
```

And it will always fail. I won't reproduce the error message as the reason of the bug was found in the code.

## Issue related to `Dulwich` library
python Dulwich (used by Poetry for git python but without git client) uses `urllib3` under the hood. Unfortunately, when initialising the `urllib3.PoolManager` it will miss the configuration of the `proxy_header`s. Dulwich will only take the proxy url from the env (see implementation of the `default_urllib3_manager()` function [here](https://github.com/jelmer/dulwich/blob/cd0990259901351400deda93b529ec601cfa52e8/dulwich/client.py#L1797)). 

Instead, the pool manager should be initialised with a `Proxy-Authorization: Basic base64EncodedLoginPassword==` header using the provided `proxy_header` parameter.

Knowing that Dulwich is the problem, the alternative is
* ✅ disable Dulwich and fallback on client, using the `POETRY_EXPERIMENTAL_SYSTEM_GIT_CLIENT=true` environment variable. (working, but not ideal because using experimental fallback on git client)
* ❤️ improve Poetry, and provide Dulwich with an `urllib3.PoolManager` that is properly initialised. The `Urllib3HttpGitClient` class indeed takes a `pool_manager` parameter
   ```python
   class Urllib3HttpGitClient(AbstractHttpGitClient):
    def __init__(
        self,
        base_url,
        dumb=None,
        pool_manager=None,
        config=None,
        username=None,
        password=None,
        **kwargs
    ) -> None:
       pass
   ```
   ([link to the code](https://github.com/jelmer/dulwich/blob/cd0990259901351400deda93b529ec601cfa52e8/dulwich/client.py#L2187C19-L2187C19))

**Comment by dimbleby** [comment]
> HTTP_PROXY=http://username:password@proxy.local:8080

you sure you don't just need to provide the variable in lower case, since that seems to be what [dulwich actually supports](https://github.com/jelmer/dulwich/blob/cd0990259901351400deda93b529ec601cfa52e8/dulwich/client.py#L1818)?

**Comment by dimbleby** [comment]
also as I understand it dulwich is intended to support git configuration in the usual git config file: if that doesn't work then a bug report there is likely welcome

**Comment by abn** [comment]
@raphaeljoie can you try using git config to set your http proxy configuration?

```
git config --global http.proxy http://proxyuser:proxypwd@proxy.server.com:8080
```

**Comment by finswimmer** [comment]
Hello @raphaeljoie,

you haven't come back to this issue for a long while. So I assume this is solved in the meantime and I can close this ticket.

Feel free to leave a comment if you disagree.

fin swimmer
