### ISSUE TITLE
Poetry installation fails (Powershell Script on Windows 10)

### ISSUE THREAD

**Issue by fmotion1** [python-poetry/poetry#8584]
- **Poetry version**: v1.6
- **Python version**: Python 3.13 (64-bit)
- **OS version and name**: Windows 10 Pro x64 Version 22H2 (Build 19045.3448)
- **pyproject.toml**: N/A

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

I am using this command:
`(Invoke-WebRequest -Uri https://install.python-poetry.org -UseBasicParsing).Content | py -`

And getting the following output:

```plaintext
error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2

[end of output]
note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: Failed building wheel for msgpack
Failed to build dulwich msgpack

ERROR: Could not build wheels for dulwich, msgpack, which is required to install pyproject.toml-based projects

Traceback:
  File "<stdin>", line 923, in main
  File "<stdin>", line 560, in run
  File "<stdin>", line 582, in install
  File "<stdin>", line 685, in install_poetry
  File "<stdin>", line 375, in pip
  File "<stdin>", line 372, in python
  File "<stdin>", line 365, in run
```

I've truncated the above log. I've attached the full log to this post.

[poetry-installer-error-yftrk3wl.log](https://github.com/python-poetry/poetry/files/13191181/poetry-installer-error-yftrk3wl.log)

Any help at all would be great.

**Comment by Secrus** [comment]
Those dependencies don't have wheels (pre-built binaries) for Python 3.13, so pip is trying to build them from source and fails (my guess would be that there are some compilers/libraries missing on your system). 

Also Poetry doesn't provide support for Python 3.13 yet (since Python 3.12 was just released).
