### ISSUE TITLE
Feature Request - Simplifying Poetry Script Invocation

### ISSUE THREAD

**Issue by wiseaidev** [python-poetry/poetry#8590]
**Description:**

Sup maintainers. I am an avid user of Poetry and a passionate advocate for its elegant approach to Python package management. Poetry simplifies the process of dependency management and project distribution, making it a go-to tool for Python developers like me.

While Poetry is exceptionally user-friendly, I've recently identified an opportunity for further refinement. In standard Python, running a script within a package is straightforward:

```python3 package_name```

This command automatically executes the code inside the `__main__.py` file of the package. This approach is both intuitive and efficient. However, Poetry requires a slightly more verbose script command:

```toml
[tool.poetry.scripts]
start = "package_name.__main__:main"
```

which can be run using:

```poetry run start```

This contrast in command syntax between standard Python and Poetry can create a minor hurdle, especially for developers switching between different Python projects. To enhance the user experience and maintain consistency, I propose a feature that streamlines script execution in Poetry.

**Feature Proposal:**

I suggest modifying the script command in Poetry's `pyproject.toml` to implicitly check for the presence of a `__main__.py` file and execute the `main` function if it exists. The change in the `pyproject.toml` file would look like this:

```toml
[tool.poetry.scripts]
start = "package_name:main"
```

This would eliminate the need to explicitly specify the `__main__.py` file, aligning Poetry's behavior with Python's conventions. The proposed feature offers numerous benefits:

**Benefits:**

1. **Improved User Experience:** This change simplifies script execution within Poetry, making it more intuitive for both new and experienced users. Developers can transition seamlessly between standard Python projects and Poetry-managed ones.

2. **Reduced Cognitive Load:** Users no longer need to remember or specify the `__main__.py` file in the script command, reducing potential sources of error.

3. **Consistency with Python:** The proposed feature aligns Poetry's behavior with Python's established conventions, making it a more seamless part of the Python development ecosystem.

4. **Enhanced Developer Productivity:** By streamlining script execution, this feature contributes to a more efficient and productive development workflow.

**Conclusion:**

This feature request aims to enhance the user experience within Poetry by simplifying script execution. It aligns with Poetry's mission to make Python development more intuitive and efficient, reducing friction in the development process. By implementing this feature, Poetry can further establish itself as a user-centric tool that prioritizes the needs of Python developers.

I believe that this enhancement would be a valuable addition to Poetry, benefiting both new and existing users. I look forward to the consideration of this feature request and am willing to contribute to its development if required.

Thank you for your attention and dedication to improving Poetry.

Love,
Mahmoud

**Edit**: Apparently, after reading [`specifications/entry-points`](https://packaging.python.org/en/latest/specifications/entry-points/), if we rename the `__main__.py` file to `__init__.py`, we can import the function to invoke without specifying `__init__`. For instance, in our `pyproject.toml`, we can define the script entry point as follows:

```toml
[tool.poetry.scripts]
start = "package_name:main"
```

package structure:

```diff
├── package_name
-│   └── __main__.py
+│   └── __init__.py
└── pyproject.toml
```

**Comment by dimbleby** [comment]
you've misunderstood lots here, the main thing being that `tool.poetry.scripts` already corresponds closely to python standards - specifically the thing you want to learn about is "entry points".

this makes your suggestion a no-go: changing poetry to move away from those standards would not be ok.

**Comment by wiseaidev** [comment]
Given your expertise in the world of "entry points", it's quite interesting why you didn't propose renaming the `__main__` file to `__init__`, instead of rambling.

**Comment by dimbleby** [comment]
haha, surprising to look at our two comments and decide that I was the one rambling!

Anyway: no problem.  Please close.
