### ISSUE TITLE
Improve Support for Multi-Package Repositories

### ISSUE THREAD

**Issue by darthtrevino** [python-poetry/poetry#8611]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request
Several of my team's projects are structured as monorepos, but there are some awkward edge-cases that have arisen when using Poetry to manage dependencies in these packages. To give you an idea of the structure of a typical repository, it looks something like this. We generally use path dependencies to inter-link dependent packages. There are a few hitches with this structure though, and unfortunately it means we have to depend on wheel-files atm.
```md
python/
    package_a
    package_b
javascript
    webapp
```

### Invalid PEP440 Versions in CI (Azure Pipelines)
When building projects in CI, poetry will use temporary versions for path-based dependencies that are invalid, presumably because CI is operating with a detached head.

Local Form: `<version>+<branchname>.<hash>`
In CI: `<version>+.<hash>`

The CI form of the dynamic path-depenedency version is PEP440 non-compliant, which results in CI errors. Things work fine locally though.

### Conditional Path Dependencies
For libraries intended for publication, local path dependencies become problematic because they can't be swapped out when using `poetry build` to generate publication artifacts. It would be nice if `poetry build` could replace path dependencies with version numbers in the distributed pyproject.toml file. It would even be reasonable to make this explicitly configurable:

`package_b = { path = "../package-b", develop = True, published={version="^1.2.3} }`

**Comment by dimbleby** [comment]
- poetry does not make up version numbers at all, you have misunderstood something or forgotten how your CI is working
- the second suggestion is duplicate #8219, among others

**Comment by darthtrevino** [comment]
Hey @dimbleby, poetry is absolutely using branch + rev information to make a version tag when using `path` dependencies. This is happening locally and in CI.

<img width="516" alt="Screenshot 2023-11-01 at 4 23 25 PM" src="https://github.com/python-poetry/poetry/assets/113544/6e54d365-fa47-414f-be70-103e06028db0">

**Comment by darthtrevino** [comment]
Thanks for the feedback. Point 1 turned out to be due to using `poetry-dynamic-versioning`, apologies for the confusion.
