### ISSUE TITLE
Poetry enviroment that never resolves.

### ISSUE THREAD

**Issue by Davidnet** [python-poetry/poetry#8617]
- **Poetry version**: 1.7.0
- **Python version**: 3.11.5
- **OS version and name**: Ubuntu 22.04 
- **pyproject.toml**: https://gist.github.com/Davidnet/58373c02c64a582eca6ae430f8bb8e88

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
I have the above mentioned `pyproject.toml` that install kfp (Kubeflow Pipelines) and a GCP AI Platform library, the two of them are used frequently since is the standard stack for AI in GCP, if I try to generate an enviroment with only those two packages poetry never resolves the constrains and it will keep running and running, I strongly suspect that is a protobuf or some specific library that both share, but I do not have the knowledge to debug this part, so please if you can help me to have some hints on where the problem should be filled (in either kfp or gcp).

Thanks poetry team, amazing product.

**Comment by dimbleby** [comment]
duplicate #8475 surely

**Comment by Davidnet** [comment]
Closed in favour of tracking #8475
