### ISSUE TITLE
Getting invalid Poetry configuration on internal package repository

### ISSUE THREAD

**Issue by Trouler** [python-poetry/poetry#8626]
- **Poetry version**: 1.7.0
- **Python version**: 3.12
- **OS version and name**: No idea since it's running on a Gitlab runner provided by our CloudOps
- **pyproject.toml**: https://gist.github.com/Trouler/8d5ef1940cb1c9ec43d7883b919b1959

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
I can no longer build packages that requires our internal pypi Gitlab repository. The build fails with the following message:
```
The Poetry configuration is invalid:
  - data.source[0].url must be uri
```
The url provided in my config is an environment variable picked up through Gitlab, and it looks like this:
https://git.tools.dev.our_company.net/api/v4/projects/{project_id}/packages/pypi

Going back to 1.6.1 solves it, so I've currently fixed it by pinning to that version.

**Comment by dimbleby** [comment]
```toml
[[tool.poetry.source]]
name = "internal-pypi"
url = "${PYPI_PROJECT_PATH}"
```
indeed thats not a valid url.

If that is not your actual repro - please provide your actual repro.  Else please close.

**Comment by Trouler** [comment]
Why was it valid before? I would prefer having this be picked up through my environment variable

**Comment by dimbleby** [comment]
the poetry schema has always declared that this shold be a url, poetry has switched from `jsonschema` to `fastjsonschema` which validates this more carefully.

you should switch in the "real" value before running poetry commands

**Comment by Trouler** [comment]
I was a bit hasty I guess. The environment variable PYPI_PROJECT_PATH is built up like this:
`https://gitlab-ci-token:${CI_JOB_TOKEN}@git.tools.dev.our_company.net/api/v4//projects/${PYPI_PROJECT_ID}/packages/pypi/simple`

**Comment by dimbleby** [comment]
you need to provide a way to reproduce what you are seeing if you expect anyone to pay attention

**Comment by Trouler** [comment]
You seem to be telling me that I should hardcode my URL, which has secrets in it...?

**Comment by Trouler** [comment]
Nvm, I'll close and pin to the old version instead

**Comment by dimbleby** [comment]
poetry doesnt do any environment variable substitution for you, by the time it reads the pyproject.toml that file needs to contain the actual url.

if you do `envsubst` tricks or similar in your CI you need to do that _before_ passing the file to poetry
