### ISSUE TITLE
Python3.12 `Connection pool is full` - Long installs

### ISSUE THREAD

**Issue by justinjeffery-ipf** [python-poetry/poetry#8627]
- **Poetry version**: 1.7.0
- **Python version**: 3.12
- **OS version and name**: Docker: cimg/python:3.12
- **pyproject.toml**: 

- [ X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [ X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X ] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

When trying to run a poetry install on Python3.12 on a GitLab CI all the jobs are taking a long time because of the below issue.  It seems that it takes about 10 minutes for poetry to continue after the connection pool is full.

`Connection pool is full, discarding connection: pypi.org. Connection pool size: 10`

**Comment by justinjeffery-ipf** [comment]
Example Jobs:
Python3.11: https://gitlab.com/ip-fabric/integrations/python-ipfabric/-/jobs/5468275063
Python3.12: https://gitlab.com/ip-fabric/integrations/python-ipfabric/-/jobs/5468020893

**Comment by dimbleby** [comment]
I expect you've mis-identified what is happening.  Much more likely you have dependencies that did not yet publish wheels for python 3.12, and the install is slower because they therefore have to be compiled from source.

please close

**Comment by justinjeffery-ipf** [comment]
I added `-vvv` but doesn't show much however I got caching working so its much faster.
