### ISSUE TITLE
Poetry fails to use the currently activated environnement

### ISSUE THREAD

**Issue by laclouis5** [python-poetry/poetry#8631]
- **Poetry version**: 1.7.0
- **Python version**: 3.11
- **OS version and name**: Ubuntu 22.04.3 LTS
- **pyproject.toml**: Empty TOML as created by `poetry new <project>` 

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
In some circonstances Poetry fails to use the activated virtual environnement (for instance a Conda environnement). In my experiments, this seems to occur when there is an hyphen (`-`) in the name of the folder of the project (for instance `poetry-project`).

### To Reproduce

```shell
poetry new poetry-project
cd poetry-project

conda create -n poetry-project python=3.11 -y
conda activate poetry-project

poetry env info
```

This returns:

```
Virtualenv
Python:         3.10.11
Implementation: CPython
Path:           NA
Executable:     NA
```

This works correctly if I change the folder name to use an underscore(`_`) instead of the hyphen (`-`), for instance `poetry_project`.

**Comment by dimbleby** [comment]
poetry just looks at environment variables to find the current virtual environment, I don't see anything special about hyphens

https://github.com/python-poetry/poetry/blob/f004a70260404560b89334271641a7093ada6551/src/poetry/utils/env/env_manager.py#L252-L256

so you should start there to understand what's actually happening

**Comment by dimbleby** [comment]
yeah, does not reproduce.

I'm starting with this docker file:
```dockerfile
# syntax=docker/dockerfile:1.5
FROM continuumio/miniconda3:23.9.0-0

RUN apt-get update && \
    apt-get install \
      --yes \
      --no-install-recommends \
      curl && \
    curl \
      --silent \
      --show-error \
      --location \
      --output install-poetry.py \
      https://install.python-poetry.org && \
    python3 install-poetry.py

ENV PATH="/root/.local/bin:$PATH"
```

Then the sequence of commands that you give ends with:
```console
(poetry-project) root@16b75389eb12:/poetry-project# poetry env info

Virtualenv
Python:         3.11.5
Implementation: CPython
Path:           /opt/conda/envs/poetry-project
Executable:     /opt/conda/envs/poetry-project/bin/python
Valid:          True

System
Platform:   linux
OS:         posix
Python:     3.11.5
Path:       /opt/conda/envs/poetry-project
Executable: /opt/conda/envs/poetry-project/bin/python3.11
```

please provide a way to reproduce - or close

**Comment by laclouis5** [comment]
Indeed, I'm not able to reproduce the issue reliably neither. I guess its an interference with other tools I use locally (pyenv, conda, etc.).

**Comment by laclouis5** [comment]
@dimbleby It happened again on another machine so I took the time to debug this. I think now have a reproducible example:

```shell
poetry new project
cd project
poetry env use 3.11  # Assuming 3.11 is available and supported
poetry env remove --all
conda env create -n project python=3.11 -y
conda activate project
poetry env info
```

This results in the same issue as mentioned in my first post, i.e. the conda environment is not detected:

```
Virtualenv
Python:         3.10.11
Implementation: CPython
Path:           NA
Executable:     NA
```

After debugging a little, it looks like the command `poetry env remove --all` does not remove the environment from the `envs.toml`. It only removes the virtual environment directory.

Then, when getting an environment, the `EnvManager` wrongly assumes that there already is an existing environment:

https://github.com/python-poetry/poetry/blob/f004a70260404560b89334271641a7093ada6551/src/poetry/utils/env/env_manager.py#L246-L250

I believe that here the `env` local variable should be `None`. This seems to create an inconsistent state and the system environment is returned instead of the conda one, i.e no virtual environment detected.

The error does not occur removing the virtual environment explicitly (without `--all`), for instance with `poetry env remove 3.11`.

**Comment by dimbleby** [comment]
sounds like you must be about ready to submit a fix...?
