### ISSUE TITLE
Conditional python_marker dependency not respected

### ISSUE THREAD

**Issue by mjnur** [python-poetry/poetry#8636]
- **Poetry version**: 1.7.0 (also tested 1.6.1)
- **Python version**: 3.9
- **OS version and name**: Debian GNU/Linux 11
- **pyproject.toml** and **poetry.lock**: https://gist.github.com/mjnur/d75e69757292fb1ceca7e35d723a76c0

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Behavior
```python
Updating urllib3 (1.26.8 -> 2.0.7)
```

## Expected Behavior
urllib3 gets updated to something like `1.26.18`, which aligns with `<1.27` version range that is in my lock file (see gist).

## Issue
Hi, I think there's some issues with the poetry installer, or maybe I'm misunderstanding something. I'm on python3.9 and a version of urllib3 is getting installed (2.0.7) is getting installed that I don't think should be.

My project relies on `boto3`, which relies on `botocore`, and also `urllib3` transiently.

Running `poetry lock` gives me version:
```python
[[package]]
name = "botocore"
version = "1.31.81"
```
and I believe the botocore dependency section in my lock file says to install `urllib3<1.27` for python versions `<3.10`:
```python
[package.dependencies]
urllib3 = [
    {version = ">=1.25.4,<1.27", markers = "python_version < \"3.10\""},
    {version = ">=1.25.4,<2.1", markers = "python_version >= \"3.10\""},
]
```

## Strange finding
I noticed that when I addded in `types-requests`, that's when the supposedly incompatible urllib library is installed (`2.0.7`).
```
[tool.poetry.dependencies]
python = "^3.8.0"
boto3 = "^1.14.39"
types-requests = "^2.8.0"
```
`Updating urllib3 (1.26.8 -> 2.0.7)`

But when I removed `types-requests` from `pyproject.toml`, things are okay:
`Updating urllib3 (1.26.8 -> 1.26.18)`

**Comment by mjnur** [comment]
I see this in the [types-requests PyPI site](https://pypi.org/project/types-requests/):

> Note: types-requests has required urllib3>=2 since v2.31.0.7. If you need to install types-requests into an environment that must also have urllib3<2 installed into it, you will have to use types-requests<2.31.0.7.

Which I assume is why I'm getting an issue after introducing `types-requests` into the mix. But What I don't understand is why poetry doesn't choose the lower version of `types-requests` that doesn't require `urllib3>=2`.

I do see that `version = "2.31.0.6"` (should be what's chosen) and `version = "2.31.0.10"` (requires urllib3>=2, what actually gets installed) are both in the poetry.lock I linked in the gist. Not sure why the latter gets installed, but finding that out might get us closer to the root cause.

**Comment by dimbleby** [comment]
does not reproduce, in a python 3.9 environment poetry installs urllib3 1.26.18 with that pyproject.toml

perhaps you aren not using the python version you think you are using

**Comment by mjnur** [comment]
Hmm, when I run `poetry env info` I'm getting `Python: 3.9.13` for both the VirtualEnv and the System which is what I expected. Might be noteworthy that I'm using Docker, I'll try to come up with a reproducible and sanitized example with Docker.
