### ISSUE TITLE
Speeding up Solver for Projects with a Larger Number of Dependencies

### ISSUE THREAD

**Issue by tbonza** [python-poetry/poetry#8640]
Hi All,

I was hoping to discuss the feasibility of speeding up the solver for projects with a larger number of dependencies. When I looked for the solver, I found the line I've referenced below which implements depth first search using a recursive technique. This looks very clean but also has the tradeoffs of stack frames being stored in memory as this function traverses the dependency graph. I'm wondering if using an iterative implementation of using depth first search, would help improve overall performance when solving for dependencies. Pseudocode example of a Depth-First Search implementation using an iterative approach:

```python
stack = []
stack.append(root_node)

while stack:
    node = stack.pop()
    # process node
    
    for edge_node in graph[node].edges:
        stack.append(edge_node)
        
# returns with results from dfs for dependency graph
```
I haven't contributed to Poetry before so I'm hoping this post continues or starts a constructive discussion about the feasibility of optimizing the solver. It's possible that I should direct my attention to other parts of the code or that there's relevant context which I have not considered here. I'm also curious what the problem to be solved is more specifically. For example, if it's a shortest path problem, has Breadth-First Search been considered? 

https://github.com/python-poetry/poetry/blob/c6387b87e37490fca59c51365adc878c5d0ceaa2/src/poetry/puzzle/solver.py#L243

**Comment by dimbleby** [comment]
that code is basically irrelevant to the solver.  If you want to improve performance, you should start off by profiling to see where time is actually being spent.

See also https://github.com/python-poetry/poetry/issues/6931#issuecomment-1299072192

**Comment by tbonza** [comment]
Closing the issue, thanks @dimbleby
