### ISSUE TITLE
Poetry example installation of pendulum is at this moment not usable for Python 3.12

### ISSUE THREAD

**Issue by gerrit-ganthor** [python-poetry/poetry#8648]
- [x ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

Distutils is removed form Python 3.12.0. This makes your pendulum example in the documentation unusable.
The pendulum developer(s?) plans to correct this in V3.0. See https://github.com/sdispater/pendulum/issues/696
I have tested this with:
    poetry add "pendulum>=3.0.0b1"

The installation functions, a temporary update of the documentation could help other developers that want to try out poetry.

Minimal TOML files to reproduce this problem:
https://gist.github.com/gerrit-ganthor/39ee891668e2c2a74e2624b04fb77c0d

**Comment by gerrit-ganthor** [comment]
IMHO this is the best place to change this: https://python-poetry.org/docs/basic-usage/#specifying-dependencies
Specify a second entry for the dependency section if Python >= 3.12.0.

**[tool.poetry.dependencies]
pendulum = "^3.0.0b1"**

**Comment by Secrus** [comment]
I don't think it really matters, that is just an example. If you think it's worth changing it, submit a merge request.

**Comment by abn** [comment]
I agree with @Secrus. Happy to accept a PR with suggestions.  Closing this for now, but updates to docs via PRs getting it current with versions are always welcome.
