### ISSUE TITLE
venv in project is slow

### ISSUE THREAD

**Issue by worthy7** [python-poetry/poetry#8657]
- **Poetry version**: 1.7.0 (not sure if previous versions were affected)
- **Python version**: 2.10 
- **OS version and name**: Debian/dev container
- **pyproject.toml**:  https://gist.github.com/worthy7/23f50f32ad215104e347e357dbf215f6

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
Using venv inside the project instead causes everything to run very very slowly 
https://python-poetry.org/docs/configuration/#virtualenvsin-project

I noticed this issue when trying to use zenml (but I don't think this is relevant, even doing poetry install is slow if using a project level venv)

**Comment by dimbleby** [comment]
not enough information for anyone to say anything useful about this: except that lots of people use in-project virtual environments and do not experience "everything runs very very slowly"

it is hard to guess what you have misunderstood, but it is very likely that whatever you are seeing is not a poetry bug

**Comment by worthy7** [comment]
I think it might be because I am running inside of a devcontainer, and the project directory is actually mounted, so therefore all the  env files are also mounted.
