### ISSUE TITLE
Can't add packages with python 3.11-dev

### ISSUE THREAD

**Issue by hros** [python-poetry/poetry#8663]
- **Poetry version**: 1.7.0
- **Python version**: Poetry/Python: 3.10.6 Virtualenv/Python:3.11.4
- **OS version and name**: Ubuntu 22.04 (in WSL2)
- **pyproject.toml**: https://gist.github.com/hros/cce27480b50bd7fe20a286554cf054fd

- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
can't add packages with poetry using when the python version is specified by `pyenv local 3.11-dev` (the `dev` version is currently set to 3.11.4)
The steps are:
1. create a new directory and `cd` into the directory
2. `pyenv local 3.11-dev`
3. `poetry init` using default settings, changing `Compatible Python versions` from `^3.10` to `^3.11`
4. `poetry shell`
5. `poetry add numpy`, returns with message: 
```
Using version ^1.26.2 for numpy

Updating dependencies
Resolving dependencies... (0.1s)

Invalid PEP 440 version: '3.11.4+'
```

6. trying the same with another package: `poetry add scipy`, returns with message:
```
Using version ^1.11.3 for scipy

Updating dependencies
Resolving dependencies... (0.0s)

The current project's supported Python range (>=3.11,<4.0) is not compatible with some of the required packages Python requirement:
  - scipy requires Python <3.13,>=3.9, so it will not be satisfied for Python >=3.13,<4.0

Because no versions of scipy match >1.11.3,<2.0.0
 and scipy (1.11.3) requires Python <3.13,>=3.9, scipy is forbidden.
So, because toshiba depends on scipy (^1.11.3), version solving failed.

  • Check your dependencies Python requirement: The Python requirement can be specified via the `python` or `markers` properties

    For scipy, a possible solution would be to set the `python` property to ">=3.11,<3.13"

    https://python-poetry.org/docs/dependency-specification/#python-restricted-dependencies,
    https://python-poetry.org/docs/dependency-specification/#using-environment-markers
```

**Comment by dimbleby** [comment]
duplicate #6925

**Comment by hros** [comment]
thanks!!
that solved the issue with numpy (the python version no longer has a `+`, though it is a shame that I can't use the `dev` channel)
the other issue, item `6` installing `scipy`, still does not work

The message points to the docs, and suggests
> For scipy, a possible solution would be to set the `python` property to ">=3.11,<3.13"

I couldn't get this to work. What is the proper way to get such packages to work
moreover, the initial message is unclear: "scipy requires Python <3.13,>=3.9, so it will not be satisfied for Python >=3.13,<4.0" since I'm using Python 3.11.4

**Comment by dimbleby** [comment]
please read the faq

**Comment by hros** [comment]
thanks!
the [faq](https://python-poetry.org/docs/faq/) did not help
I was able to find a solution in a [blog](https://www.markhneedham.com/blog/2023/10/05/poetry-project-python-not-compatible/)

I modified the `pyproject.toml` file:
```
[tool.poetry.dependencies]
python = ">=3.11,<3.12"
```
Initially, `scipy` asked for `<3.13`, another package I installed raised an error asking for stricter version bounds

**Comment by dimbleby** [comment]
please close
