### ISSUE TITLE
Support "Other/Proprietary License"

### ISSUE THREAD

**Issue by thmo** [python-poetry/poetry#867]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

For an internal project, I'd like to use `Other/Proprietary License` as the license (which seems to be a valid choice e.g. according to https://pypi.org/classifiers/), but that doesn't seem to be supported by poetry.

**Comment by HolgerPeters** [comment]
@sdispater I would like to create a PR for this if there are no objections

**Comment by Nateyo** [comment]
+1

A custom license field would be great.

**Comment by sdispater** [comment]
You can now use the special `proprietary` license identifier to specify that the package uses a proprietary license.
