### ISSUE TITLE
The `pre-commit-hooks` page should remove the use of `poetry-lock` as it is deprecated.

### ISSUE THREAD

**Issue by iamibi** [python-poetry/poetry#8674]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

The `pre-commit-hooks` page currently shares the information on using `poetry-lock` plugin which has be deprecated. The `poetry-check` plugin instead can be used with the argument `args: ["--lock"]` as suggested by the following deprecation warning
```
poetry lock --check is deprecated, use `poetry check --lock` instead.
```

**Comment by dimbleby** [comment]
`poetry lock` is not deprecated.

(Only `poetry lock --check` is deprecated, but the hook is more general than that)
