### ISSUE TITLE
`poetry add --group mygroup randompackage` doens't install the package

### ISSUE THREAD

**Issue by baniasbaabe** [python-poetry/poetry#8677]
- **Poetry version**: 1.7.0
- **Python version**: 3.8.7
- **OS version and name**: Windows 10
- **pyproject.toml**: https://github.com/baniasbaabe/air-quality-forecast/blob/main/pyproject.toml

- [x ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [ x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x ] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [ x] If an exception occurs when executing a command, I execute it again in debug mode (`-vvv` option) and have included the output below.

## Issue
When I run `poetry add <somepackage>` everything works fine. But whenever I run `poetry add --group mygroup <randompackage>`, it only adds it to the `pyproject.toml` file, but doesn't install it. When I run `poetry install -with mygroup`, it doesn't install the package.

**Comment by dimbleby** [comment]
does not reproduce:
```
$ poetry add --group mygroup random-poem
Using version ^1.0.1 for random-poem

Updating dependencies
Resolving dependencies... (0.7s)

Package operations: 8 installs, 0 updates, 0 removals

  • Installing certifi (2023.7.22)
  • Installing charset-normalizer (3.3.2)
  • Installing idna (3.4)
  • Installing soupsieve (2.5)
  • Installing urllib3 (2.1.0)
  • Installing beautifulsoup4 (4.12.2)
  • Installing requests (2.31.0)
  • Installing random-poem (1.0.1)
```
please either give a way to reproduce, or close

**Comment by baniasbaabe** [comment]
1. `poetry install --with dev,test,linters,fixers` (should work fine)
2. `poetry add --group linters flake8` (should only add the package to the group without installing it)

**Comment by dimbleby** [comment]
you have marked the linters group as optional, this is expected

**Comment by baniasbaabe** [comment]
Oh okay, so how can poetry still install it even if it's optional?

**Comment by dimbleby** [comment]
please read the docs https://python-poetry.org/docs/master/managing-dependencies/#optional-groups
