### ISSUE TITLE
Poetry picks wrong platform when resolving a local poetry project dependency

### ISSUE THREAD

**Issue by sbadredd-sony** [python-poetry/poetry#8681]
- **Poetry version**: 1.7.0
- **Python version**: 3.12.0
- **OS version and name**: macOS 12.5.1
- **pyproject.toml**: The [two pyproject.toml files ](https://gist.github.com/sbadredd-sony/1aae7759628834af3f0a1e3d16d2d502) to recreate the issue

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
I created two local poetry projects. The first (`local_dependency`) defines a platform-specific dependency. The second (`test_project`) installs the first project using the wrong platform.

Steps to reproduce
1. Create 2 empty projects `local_dependency` and `test_project` with `poetry new`
2. In `local_dependency/pyproject.toml` I have:
```
[tool.poetry.dependencies]
python = ">=3.10,<3.12"
torch = [
    { version = "=2.1.0+cpu", source = "torch_cpu", platform = "linux" },
    { version = "=2.1.0", source = "pypi", platform = "darwin" },
]

[[tool.poetry.source]]
name = "torch_cpu"
url = "https://download.pytorch.org/whl/cpu"
priority = "explicit"
```
3. In `test_project/pyproject.toml` I have:
```
[tool.poetry.dependencies]
python = ">=3.10,<3.12"
local-dependency = {path = "../local_dependency", develop = true}

[[tool.poetry.source]]
name = "torch_cpu"
url = "https://download.pytorch.org/whl/cpu"
priority = "explicit"
```
Note that I need to re-add the `torch_cpu` source otherwise `poetry lock` gives me `Repository "torch_cpu" does not exist.`. I don't know if this is another bug or expected behavior (sources not being imported from local poetry project dependencies) **Edit**: this part is expected behavior; see [dimbleby's answer](https://github.com/python-poetry/poetry/issues/8681#issuecomment-1814308483)

4. In `local_project/`, `poetry lock` and `poetry install` run fine. Poetry uses the `pypi` source for darwin as expected.
5. In `test_project/`, `poetry lock` runs fine but `poetry install` gives a runtime error `Unable to find installation candidates for torch (2.1.0+cpu)`. Poetry tries to install the local dependency as if it was in linux. It seems the platform tag is not transited in the correct way

**Comment by dimbleby** [comment]
sources are a poetry special: there is no way to express them in standard project metadata and so in general project A cannot know about sources defined in project B.

what you are trying to do will not work, you'll have to be explicit about such things in your top-level project

please close

**Comment by sbadredd-sony** [comment]
So I cannot use Poetry if I have a dependency that relies on an OS-specific source. Is that correct?

**Comment by dimbleby** [comment]
your top-level project cannot rely on anything your dependencies say about sources.  

Your mental model should be: imagine that the dependency has been published to pypi, and all source information  is therefore unavailable - because it just isn't part of the wheel metadata

**Comment by sbadredd-sony** [comment]
Thanks for the clarification! Let's say I explicitly add the source `torch_cpu` in every project, like above. 

For my main issue: I am on `darwin`, why is it installing the `linux` dependency?

**Comment by dimbleby** [comment]
a.b.c+local is a match for a.b.c, you still are relying on the unavailable source information to disambiguate

**Comment by sbadredd-sony** [comment]
I may be misunderstanding.
Isn't the `platform` argument supposed to disambiguate?
```
    { version = "=2.1.0+cpu", source = "torch_cpu", platform = "linux" },
    { version = "=2.1.0", source = "pypi", platform = "darwin" },
```

**Comment by dimbleby** [comment]
The requirement `=2.1.0` is met by version `2.1.0+cpu`, it was the sources that allowed differentiation

**Comment by chielk** [comment]
I ran into (almost exactly) the same issue today, so I thought it best to add my comment here.

I have torch 2.1.0 in my primary source and 2.1.0+cu118 in my supplemental source.
Adding the sources resolved the issue, (but wouldn't have worked if they were hosted on the same server).

I would expect poetry to try to install from the primary source before the supplemental one, but it's not.

Something else that's new, and I think related, is that I get a lot of messages like this about my supplemental source when running `poetry lock`:
```
Source (torch): Authorization error accessing https://download.pytorch.org/whl/cu118/<dependency>/
```
All these dependencies are available on the primary source, so I don't think poetry should query the supplemental one (according to the documentation https://python-poetry.org/docs/repositories/#supplemental-package-sources)

This all worked as expected a few days ago, but it broke on poetry 1.5.1 (which I hadn't updated), and wasn't fixed by updating to 1.7.1. I'm running this on MacOS 14.0 (ARM) with python 3.11.4

**Comment by dimbleby** [comment]
@chielk none of that is new and it is discussed in lots of other issues, please search for duplicates.

this issue is specifically about sources that are mentioned in a dependency of the top-level project - and it should be closed, because everything here is working as expected

**Comment by sbadredd-sony** [comment]
> The requirement `=2.1.0` is met by version `2.1.0+cpu`, it was the sources that allowed differentiation

The `platform` also allows differentiation, right?

Even if you remove the sources, you have
```
    { version = "=2.1.0+cpu", platform = "linux" },
    { version = "=2.1.0",  platform = "darwin" },
```

**Comment by dimbleby** [comment]
because that's what the python packaging standards say is the correct behaviour

https://packaging.python.org/en/latest/specifications/version-specifiers/#version-matching

> If the specified version identifier is a public version identifier (no local version label), then the local version label of any candidate versions MUST be ignored when matching versions.

Therefore when matching "=2.1.0" we MUST ignore the "+cpu" on the candidate version "2.1.0+cpu", and it becomes a match

**Comment by sbadredd-sony** [comment]
Ah, now I understand, thanks!

That's a tricky one. My easiest solution is probably to work with, e.g.
``` 
    { version = "=2.0.1+cpu", source = "torch_cpu", platform = "linux" },
    { version = "=2.1.0", source = "pypi", platform = "darwin" },
```
