### ISSUE TITLE
Poetry & Pre-Commit Compatibility

### ISSUE THREAD

**Issue by joeld1** [python-poetry/poetry#8693]
Just out of curiosity, does poetry work well with pre-commit ?

I was wondering if there was a way to automate configuring pre-commit (i.e. running `pre-commit install` ) through the pyproject.toml file after running `poetry install` ? Can this work without breaking when working on various machines ?

Also, I'm unsure, but does running `pre-commit install` affect/consider the dependencies found on the `pyproject.toml` file? Are they installed in separate environments - i.e. can one break the other?

Thank you so much and keep up the work! A lot has changed since I last read the poetry documentation, and I'm impressed !

**Comment by dimbleby** [comment]
`poetry install` will just do what it does, it does not run pre-commit or anything else.

your second question seems to be a question for pre-commit - but also something that you could most easily answer by trying it for yourself

**Comment by Ravencentric** [comment]
Pre commit works entirely seperately from poetry. It will not affect poetry or anything for that matter. It has its own config file that it'll read and make its own isolated environment to run the pre-commit hooks without affecting any of your dependencies in the current project.

**Comment by joeld1** [comment]
Awesome, I just tested things out and stumbled across the [scripts section](https://python-poetry.org/docs/pyproject#scripts) in the docs!

Thanks everyone!
