### ISSUE TITLE
Langchain poetry install triggers degenerate combinatoric explosion

### ISSUE THREAD

**Issue by jwatte** [python-poetry/poetry#8694]
Dockerfile:
https://gist.github.com/jwatte/a5944ec1b81a58cff8ea863a315320b5

pyproject.toml:
https://gist.github.com/jwatte/1f39f0ab0a98b7a637692a4c83c91ee4

It looks like poetry is not only doing the full combinatorics explosion, and very slowly comparing each version number, but also failing to realize that there's going to exist no version of botocore that's >1.17.34 and <1.17.35 -- this should be able to shortcut without doing any evaluation.

**Comment by dimbleby** [comment]
botocore is often problematic: Amazon release a new version every day (!!) so if you depend on it with no lower bound and if the search takes an unlucky wrong turn early on - then poetry can be stuck working its way through thousands of candidate version.

If that's what you're seeing, you should provide a (recent) lower bound for botocore: and if it is a transient dependency, possibly ask your direct dependency to do the same.

> failing to realize that there's going to exist no version of botocore that's >1.17.34 and <1.17.35

it is hard to guess what you have misunderstood, but I expect you have misread the output.  Besides, there are infinitely many versions satisfying this constraint eg 1.17.34.1

please close
