### ISSUE TITLE
`poetry update <package_name>@latest` does not run any updates

### ISSUE THREAD

**Issue by DhenPadilla** [python-poetry/poetry#8705]
- **Poetry version**: Poetry (version 1.7.1)
- **Python version**: Python 3.11.4
- **OS version and name**: MacOS Ventura 13.5
- **pyproject.toml**: [https://gist.github.com/DhenPadilla/b60c05adcfdbc2baaf0b2ddae3713674](https://gist.github.com/DhenPadilla/b60c05adcfdbc2baaf0b2ddae3713674)

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a [recommended method](https://python-poetry.org/docs/#installation).
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
In this case; `<package_name> = openai` but I saw this happen before with other packages.

I was getting quite frustrated with the `poetry update <package_name>` or `poetry update <package_name>@latest` command as in my `pyproject.toml`, the specified `<package_name>` had a version constraint of: `^0.28.0`, and the latest on PyPi was `1.3.4`.

For some reason, Any run of `poetry update <package_name>` or `poetry update <package_name>@^1.3.4` or `poetry update <package_name>@latest` always returned with the following:

```
Updating dependencies
Resolving dependencies... (0.4s)

No dependencies to install or update
```

However, I finally decided to use `poetry add <package_name>@^1.3.4` and this updated my desired package successfully.

Flagging this as a possible issue as [per the docs](https://python-poetry.org/docs/cli/#update), `poetry update` command should be able to check diff and update to latest version.

## Log stack traces:

```
poetry update openai@1.0.0
Configuration file exists at /Users/dhenpadilla/Library/Preferences/pypoetry, reusing this directory.

Consider moving TOML configuration files to /Users/dhenpadilla/Library/Application Support/pypoetry, as support for the legacy directory will be removed in an upcoming release.
Updating dependencies
Resolving dependencies... (0.4s)

No dependencies to install or update
```
```
poetry add openai@1.0.0
Configuration file exists at /Users/dhenpadilla/Library/Preferences/pypoetry, reusing this directory.

Consider moving TOML configuration files to /Users/dhenpadilla/Library/Application Support/pypoetry, as support for the legacy directory will be removed in an upcoming release.

Updating dependencies
Resolving dependencies... (0.7s)

Package operations: 4 installs, 1 update, 0 removals

  • Installing h11 (0.14.0)
  • Installing httpcore (1.0.2)
  • Installing distro (1.8.0)
  • Installing httpx (0.25.2)
  • Updating openai (0.28.1 -> 1.0.0)

Writing lock file
```

**Comment by dimbleby** [comment]
the docs that you link are already clear:

> Note that this will not update versions for dependencies outside their version constraints specified in the pyproject.toml file. 

please close

**Comment by DhenPadilla** [comment]
@dimbleby 

In my pyproject.toml (gist link above), you can see that it was set with `^0.28.0`. 
From the docs, I read the following line:
> In order for foo to be updated, you must update the constraint, for example ^2.3 

and understood that my pyproject.toml has a correctly set constraint that should apply an update when `poetry update` is run?

**Comment by dimbleby** [comment]
I don't understand what it is that you misunderstand.  Perhaps it is that `^0.28.0` does not allow `1.3.4`?

I also don't understand what would lead you to think that this syntax `poetry update <package_name>@^1.3.4 ` was supported - I don't find any docs for `poetry update` that suggest this would work?

Feel free to submit a merge request clarifying whatever it is that you did not find clear: but there is no bug here.  Please close.

**Comment by DhenPadilla** [comment]
>Perhaps it is that ^0.28.0 does not allow 1.3.4?
This was the answer! thanks for replying;
You're correct here that there is no bug.

For completeness of this issue - as I didn't know this and someone else may come across this:
It seems that **_`^` constraints in SemVer only allows patch + minor updates, not major updates._** 
I.e, when attempting 
`update package@latest` with:
- current version: `^0.y.z`, and
- the latest version: `1.a.b`, then `poetry update package@latest` will be a no-op. 

I wrongly assumed that `poetry update package_name` will update package to the latest pypi version published, regardless of _major_ version number.

If it makes sense, I could add a merge request to the docs to reflect this?

**Comment by dimbleby** [comment]
https://python-poetry.org/docs/dependency-specification#caret-requirements seems to me to be pretty clear, but if you can improve it then please do

**Comment by DhenPadilla** [comment]
@dimbleby Opened above PR with the small documentation amendment
