### ISSUE TITLE
Private registry uses two different URLs for uploading and downloading packages. I guess this works with poetry, but I can't find it in the docs.

### ISSUE THREAD

**Issue by feluxe** [python-poetry/poetry#8711]
- [x ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

We are using a Sonatype Nexus registry for our private python packages. We thought of moving from pipenv to poetry, but we can't find a way to make poetry work with our registry.

The problem is that Nexus uses two different URLs for downloading and uploading/publishing packages:

```
Upload:   https://registry.example.com/repository/private-pypi/
Download: https://registry.example.com/repository/private-pypi/simple/
```
I have searched the docs, but I can't find a way to specify two different URLs for a source, or a way to specify two different sources for publishing and downloading.

**Comment by dimbleby** [comment]
hard to see how you have searched the docs and not found https://python-poetry.org/docs/repositories/#publishable-repositories ?

please close
