### ISSUE TITLE
License field in pyproject.toml should accept table value (e.g., `{ file = "LICENSE.txt"}`)

### ISSUE THREAD

**Issue by todofixthis** [python-poetry/poetry#8712]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request
I'm updating a project to use poetry, and in my `pyproject.toml` file I previously had this:

```toml
[project]
license = { file = "LICENCE.txt" }
```

[Python Packaging User Guide supports this syntax for `license`](https://packaging.python.org/en/latest/specifications/declaring-project-metadata/#license):

> * [TOML](https://toml.io/) type: table
> * Corresponding [core metadata](https://packaging.python.org/en/latest/specifications/core-metadata/#core-metadata) field: [License](https://packaging.python.org/en/latest/specifications/core-metadata/#core-metadata-license)
> 
> The table may have one of two keys. The `file` key has a string value that is a file path relative to `pyproject.toml` to the file which contains the license for the project. Tools MUST assume the file’s encoding is UTF-8. The `text` key has a string value which is the license of the project. These keys are mutually exclusive, so a tool MUST raise an error if the metadata specifies both keys.

Following the poetry documentation, I have changed it to this:

```toml
[tool.poetry]
license = { file = "LICENCE.txt" }
```

When I run `poetry check`, however, I get the following error:

> The Poetry configuration is invalid:
>   - data.license must be string

As a workaround I can change it to this:

```toml
[tool.poetry]
license = "MIT"
```

From the perspective of a dev who is new to poetry, it would be nice if poetry supported the same format as the PyPA spec — or at least update the documentation to acknowledge the difference and explain why poetry doesn't follow the PyPA spec 😇

**Comment by dimbleby** [comment]
what part of the poetry documentation makes you think that the table is a valid format?

(PEP621 support is well covered elsewhere in this tracker, no need to duplicate that here.)
