### ISSUE TITLE
Errors are reported when the script is executed using the poetry run command

### ISSUE THREAD

**Issue by RicarTang** [python-poetry/poetry#8722]
Why do I declare dev = "uvicorn testframe_backend.main:app --host 0.0.0.0 --port 4000" in scripts and then get an error when I use poetry run dev: too many values to unpack (expected 2), Can't you use scripts that way?
![image](https://github.com/python-poetry/poetry/assets/107909844/e8b2c545-ad03-4904-91d4-7afd4366e761)

If I can't execute the script, what does this script do that I can't understand

**Comment by dimbleby** [comment]
please follow the issue template, read the docs

docs improvements welcome if and when you find that they are not as helpful as you hoped

**Comment by RicarTang** [comment]
Okay
