### ISSUE TITLE
Cannot install wagtail on Windows 10

### ISSUE THREAD

**Issue by alinlupu** [python-poetry/poetry#8726]
- **Poetry version**: 1.7.1
- **Python version**: 3.11.6
- **OS version and name**: Windows 10 Home 22H2
- **pyproject.toml**: https://gist.github.com/alinlupu/90551f0afd5bc405312d879909ccfc20

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a [recommended method](https://python-poetry.org/docs/#installation).
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

I start with a fresh created project with _**poetry new test-poetry**_. When I try to add wagtail with _**poetry add wagtail**_ I receive a 
```
~\.local\pipx\venvs\poetry\Lib\site-packages\poetry\installation\wheel_installer.py:59 in write_to_fs
       57|             parent_folder.mkdir(parents=True, exist_ok=True)
       58| 
    >  59|         with target_path.open("wb") as f:
       60|             hash_, size = copyfileobj_with_hashing(stream, f, self.hash_algorithm)
       61| 

  FileNotFoundError

  [Errno 2] No such file or directory: 'C:\\Users\\maria\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\Local\\pypoetry\\Cache\\virtualenvs\\test-poetry-ucMLzWLu-py3.11\\Lib\\site-packages\\wagtail\\admin\\templates\\wagtailadmin\\bulk_actions\\confirmation\\form_with_fields.html'

  at C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\pathlib.py:1044 in open
      1040|         the built-in open() function does.
      1041|         """
      1042|         if "b" not in mode:
      1043|             encoding = io.text_encoding(encoding)
    > 1044|         return io.open(self, mode, buffering, encoding, errors, newline)
      1045| 
      1046|     def read_bytes(self):
      1047|         """
      1048|         Open the file in bytes mode, read it, and close the file.

Cannot install wagtail.
```
**Full debug -vvv output:** [debug-output.txt](https://github.com/python-poetry/poetry/files/13499834/debug-output.txt)

It works fine if install wagtail using pip, in another folder.
I experience the same problem with different versions of wagtail.
Thank you!

**Comment by Secrus** [comment]
You didn't provide full debug mode output (run `add` command with `-vvv` option)

**Comment by alinlupu** [comment]
@Secrus Updated, thanks!

**Comment by dimbleby** [comment]
as you can see in the stack, poetry is (i) checking that the parent directory exists (ii) creating it if not (iii) opening the file for writing.  Hard to see what more it could do.

perhaps you have don't have permissions to write files there

do report back when you figure it out, the next person might appreciate it
