### ISSUE TITLE
Can readme section conains several files?

### ISSUE THREAD

**Issue by proofit404** [python-poetry/poetry#873]
Hi, thanks for an awesome tool.

To publish a package to the PyPI I usually combine project long description from the GitHub README and CHANGELOG from the docs site like this:

```python
readme = open("README.rst").read() + open("CHANGELOG.rst").read()

setup(
    ...
    long_description=readme,
    ...
)
```

Is there something similar to this technique in poetry?

Best regards,
Artem.

**Comment by wagnerluis1982** [comment]
If suitable to the maintainer, @sdispater, I would like to implement the ability to combine more than one readme file.

**Comment by yatmanov** [comment]
I second that.

**Comment by zillionare** [comment]
Please have this implemented, thanks!

**Comment by DudeNr33** [comment]
Any news on this? The linked PR is open since last year. This would be a really helpful addition!

**Comment by wagnerluis1982** [comment]
Given python-poetry/poetry-core#118 was reverted, can someone reopen this issue?
