### ISSUE TITLE
Poetry fails to parse concatinated `install_requires` lists in setup.py for dependencies specified with git+ssh 

### ISSUE THREAD

**Issue by samuel-mahoney** [python-poetry/poetry#8734]
- **Poetry version**: 1.7.1
- **Python version**: 3.11.3 + (3.10.x, 3.9.x, 3.8.x)
- **OS version and name**: Ubuntu 22.04 LTS
- **pyproject.toml** (**poetry.lock** & **setup.py**) https://gist.github.com/samuel-mahoney/ed9872eb689a3c549e7083994236a205

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a [recommended method](https://python-poetry.org/docs/#installation).
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
After specifying a (private) repository with git+ssh, Poetry is unable to determine the required dependencies for the project if list concatenation is used to define `install_requires` as part of `setup.py`, shown [here](https://gist.github.com/samuel-mahoney/ed9872eb689a3c549e7083994236a205#file-broken_setup-py). 

`[package.dependencies]` is not populated in `poetry.lock`. Other elements (not using concatenation) such as `[package.extras]` are still populated correctly.

I navigated past this issue by modifying `setup.py` to use `list.extend()` as an alternative to concatenation, as shown [here](https://gist.github.com/samuel-mahoney/ed9872eb689a3c549e7083994236a205#file-working_setup-py). After these changes, Poetry had no issues resolving the correct dependencies. 

- When installing the private repository locally, specified with a path (at the same commit hash), Poetry was able to populate the lock file correctly. 
- `pip + ssh` had no issues resolving and installing the correct dependencies.
- Interestingly, the `poetry.lock` file was being populated correctly earlier this week (Poetry 1.7.1 and Python 3.11.3). Despite the specified commit hash remaining constant in the `pyproject.toml`.

This would indicate this issue is exclusive to the ssh implementation used by Poetry and how the client handles list concatenation. However, this still doesn't explain why this worked earlier this week with the same setup.

**Comment by dimbleby** [comment]
poetry builds cross-platform solutions, `if WINDOWS` is not something that it can evaluate

use pep508 environment markers to express variation between platforms

please close
