### ISSUE TITLE
Compare Two toml/lock Files for Dependencies Differences. 

### ISSUE THREAD

**Issue by moonforsun** [python-poetry/poetry#8747]
- [ x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ x] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request

Thank you for this amazing repo!

I want to do `poetry update` in a repo which depends on two major repos. Currently, the poetry complains, stops and throws an error whenever it finds the version resolving failures. I am wondering would it be possible to throw a warning rather than an error with an optional parameter? In this way, I can know all the dependencies incompatibilities.

**Comment by dimbleby** [comment]
I am quite sure this is not going to happen

**Comment by dimbleby** [comment]
too difficult, too low value, zero prospect of anyone contributing this

**Comment by moonforsun** [comment]
@dimbleby Thank you! Can you navigate me the source code that the poetry in comparing the version compatibility?

**Comment by moonforsun** [comment]
@dimbleby Just searched and found `from poetry.core.constraints.version import parse_constraint` would serve my purpose. Thank you all the same.
