### ISSUE TITLE
Poetry ignoring build-requirement for git dependency

### ISSUE THREAD

**Issue by rashidnhm** [python-poetry/poetry#8755]
- **Poetry version**: 1.7.1
- **Python version**: 3.10.12
- **OS version and name**: Ubuntu 22.04
- **pyproject.toml**: https://gist.github.com/rashidnhm/0f3f5871f2419bb9f5dfd6b0908ebe27

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a [recommended method](https://python-poetry.org/docs/#installation).
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
A similar error was mentioned in #7702 but I am opening this issue as that was closed.

When I attempt to add the package shown in the linked pyproject.toml, then `poetry lock` raises an error: `ModuleNotFoundError: No module named 'Cython'`. However, Cython is listed as a build requirement in the upstream project ([See Here](https://github.com/quantumgizmos/ldpc/blob/1714314b1904c1430ae79b48be8a3c7015952bd5/pyproject.toml#L2)).

I created a fork of the package, and switched the build-system from setuptools to poetry ([See Here](https://github.com/XanaduAI/ldpc/blob/6ec65171c254ccb1c6e8ea137bf0c3a55de180bb/pyproject.toml#L1-L3)), making that change `poetry lock` passes.

This however, seems to be an issue, even if the package is not using poetry as the build system, since it listed `cython` as a build requirement, I was expecting it to be available.

**Steps to reproduce**
- Download linked [pyproject.toml](https://gist.github.com/rashidnhm/0f3f5871f2419bb9f5dfd6b0908ebe27) above and run `poetry lock`

- Then comment out the line and uncomment the other line that points to the fork and run `poetry lock`, it passes.

Error:
```
Updating dependencies
Resolving dependencies... (28.1s)

Unable to determine package info for path: /home/rashid/.cache/pypoetry/virtualenvs/my_test_project-wS6TTyDi-py3.10/src/ldpc

Command ['/tmp/tmpuirn7px6/.venv/bin/python', '-I', '-W', 'ignore', '-c', "import build\nimport build.env\nimport pyproject_hooks\n\nsource = '/home/rashid/.cache/pypoetry/virtualenvs/my_test_project-wS6TTyDi-py3.10/src/ldpc'\ndest = '/tmp/tmpuirn7px6/dist'\n\nwith build.env.DefaultIsolatedEnv() as env:\n    builder = build.ProjectBuilder(\n        source_dir=source,\n        python_executable=env.python_executable,\n        runner=pyproject_hooks.quiet_subprocess_runner,\n    )\n    env.install(builder.build_system_requires)\n    env.install(builder.get_requires_for_build('wheel'))\n    builder.metadata_path(dest)\n"] errored with the following return code 1

Error output:
Traceback (most recent call last):
  File "<string>", line 15, in <module>
  File "/tmp/tmpuirn7px6/.venv/lib/python3.10/site-packages/build/__init__.py", line 239, in get_requires_for_build
    with self._handle_backend(hook_name):
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/tmp/tmpuirn7px6/.venv/lib/python3.10/site-packages/build/__init__.py", line 360, in _handle_backend
    raise BuildBackendException(exception, f'Backend subprocess exited when trying to invoke {hook}') from None
build._exceptions.BuildBackendException: Backend subprocess exited when trying to invoke get_requires_for_build_wheel

Fallback egg_info generation failed.

Command ['/tmp/tmpuirn7px6/.venv/bin/python', 'setup.py', 'egg_info'] errored with the following return code 1

Output:
Traceback (most recent call last):
  File "/home/rashid/.cache/pypoetry/virtualenvs/my_test_project-wS6TTyDi-py3.10/src/ldpc/setup.py", line 2, in <module>
    from Cython.Build import cythonize
ModuleNotFoundError: No module named 'Cython'
```

Error Log (`poetry lock -vvv`):
[poetry_lock_output.log](https://github.com/python-poetry/poetry/files/13603604/poetry_lock_output.log)

**Comment by dimbleby** [comment]
ie this is https://github.com/quantumgizmos/ldpc/issues/17 and needs fixing in ldpc, nothing poetry can do to help you

**Comment by rashidnhm** [comment]
@dimbleby Thank you for such a prompt reply, and you are correct that was indeed the issue. We will raise a PR in that repo to fix this.
