### ISSUE TITLE
Add option for interpreter flags for a Poetry script

### ISSUE THREAD

**Issue by takanuva15** [python-poetry/poetry#8757]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request
I would like to be able to specify interpreter flags when running a Poetry script. In my case, when running my scripts locally, I use the `-O` flag to toggle debug mode as I'm testing my scripts. 

I have already reviewed #3335 where they talk about using an environment variable, but that isn't flexible for cases where an interpreter flag doesn't have an environment variable. Also, that solution doesn't work great on Windows where you can't prepend env variables so simply as unix bash allows.

If there's not a clean way to specify an interpreter flag directly to poetry run, I think the next best thing could be to add a "flags" value in the expanded [scripts table](https://python-poetry.org/docs/pyproject#scripts) where we can put the flags we want to execute for a given script.

**Comment by dimbleby** [comment]
there's no such thing as a "poetry script", they are just regular package [entrypoints](https://packaging.python.org/en/latest/specifications/entry-points/) but defined in poetry syntax.

Therefore it is not desirable to be adding poetry-special bells and whistles.  If you find entrypoints lacking then you should take that to the python packaging authority and write a PEP.

**Comment by Secrus** [comment]
There is no standard for that and we are not going to make Poetry a special case. Once there are PEP-ified standards for that, we can get back to the topic.
