### ISSUE TITLE
Installing google-cloud-pipeline-components from PyPi hangs

### ISSUE THREAD

**Issue by patrickmead** [python-poetry/poetry#8758]
- **Poetry version**:  1.6.1 and 1.5.1
- **Python version**: 3.9.12 and 3.11.1 in the virtual environment
- **OS version and name**: macOS 13.5.2 , macOS 12.7.1, Docker python:3.11.6 image on a Linux GitLab runner 
- **pyproject.toml**:  https://gist.github.com/patrickmead/73e65c904f2df23ea3b1bd14272bcd85

- [x ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a [recommended method](https://python-poetry.org/docs/#installation).
- [ x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x ] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
I've been using `google-cloud-pipeline-components` with the above versions of poetry and python without issues for months. Since last night I've been unable to add that dependency to existing poetry-based projects or ones with empty toml files. The poetry add step runs for hours; I eventually kill the process. 

I piped the output to a file and ran cat against it while the add operation was running. I saw references to conflicts between `google-api-core` and other dependencies. Based on what I found in the log I tried pinning `google-api-core` to version 1.34.0 and added it first. Then I added  `google-cloud-pipeline-components`. Both adds ran in fractions of a second.

Later I tried a poetry install with a lock file built from the two-step process above. It hung. I tried clearing my poetry cache and rerunning. It's been running for hours.

I'm running an add that normally works and trying on multiple machines, operating systems, and networks.  Pinning versions seems to be the workaround. I don't have resolution or even an acceptable workaround but I'm still debugging.

Thank you.

**Comment by patrickmead** [comment]
I tried downgrading this specific project to python 3.10 and all dependencies were pulled quickly, without error, and without pinning. I'm going to keep it on 3.10 for now. 

google-cloud-pipeline-components works in one of my python 3.11 projects so I'm confused.

**Comment by dimbleby** [comment]
Duplicate #8475, #8716
