### ISSUE TITLE
Add --frozen-lockfile flag to error on install with missing lockfile

### ISSUE THREAD

**Issue by chdsbd** [python-poetry/poetry#876]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Feature Request
I would find it useful to have a flag similar to yarn's `--frozen-lockfile` for `poetry install`. `poetry install --frozen-lockfile` would behave like yarn's flag and wouldn't generate a new lockfile and would error if an update was needed.

**Comment by chdsbd** [comment]
@sdispater If you'd be willing to add this as a feature I will to make a PR for it.

**Comment by chdsbd** [comment]
I think this is still valuable and should not be closed.

**Comment by finswimmer** [comment]
I guess `poetry lock` is what you are looking for :)

**Comment by chdsbd** [comment]
I don't think this issue should be closed.

`poetry lock` does not match this request. This request is for a `--frozen-lockfile` flag for `poetry install` that would raise an error if `poetry` was missing a lock file.

This is available in [`yarn`](https://classic.yarnpkg.com/en/docs/cli/install/#toc-yarn-install-frozen-lockfile) for comparison:
> `yarn install --frozen-lockfile`
> Don’t generate a yarn.lock lockfile and fail if an update is needed.

**Comment by abn** [comment]
@chdsbd are you suggesting that there is a need for `poetry install` to not create a lock file if one is not available? Can you provide a scenario where this is required?

**Comment by chdsbd** [comment]
@abn `poetry install --frozen-lockfile` would error if `poetry.lock` was missing or out of date. This would be useful in CI to prevent mistakes when changing `pyproject.toml`.

**Comment by finswimmer** [comment]
> poetry install --frozen-lockfile would error if poetry.lock was missing or out of date.

`poetry` already gives you a warning if the lockfile is not up to date with the latest changes in the `pyproject.toml`. Maybe we can just change it to raise an error? Or provide a config to decide whether we want something like a strict mode, which will raise an error otherwise just a warning?

I'm not sure if there should be a way, that poetry raise an error if the lock file is missing. Isn't this something you can easily check within your CI pipeline?

**Comment by abn** [comment]
I guess what's required is a `strict` install mode. 

That said, there is already a PR that adds`poetry lock --check` for checking if the lock is fresh.

**Comment by max-wittig** [comment]
@abn Is there any feature planned that behaves like the other package managers for installation with frozen lockfiles? (yarn, npm, cargo...).

This is especially important for the installation in CI systems

E.g. 

```
npm ci
yarn --frozen-lockfile
```

Thanks for any help!

**Comment by dmfigol** [comment]
@finswimmer can this be reopened please? I would love to have a way to raise an error during installation if the lockfile is out of date.
