### ISSUE TITLE
Poetry lock file hashes differ depending on the platform

### ISSUE THREAD

**Issue by lilian-delouvy** [python-poetry/poetry#8777]
Poetry lock file hashes differ depending on the platform

- **Poetry version**: 1.7.0
- **Python version**: 3.8 (also tested in 3.10)
- **OS version and name**: Windows 10 (also on other OS)

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a [recommended method](https://python-poetry.org/docs/#installation).
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.

## Issue
Hello everyone,

When using the command ```poetry lock```, the generated hashes differ depending on the OS/Platform. 

Concretely, this means that a lock file generated locally, on a Windows computer, will be different than if it was generated on a Linux CI/CD pipeline. Therefore, it is impossible to use ```poetry install``` on our pipelines as the provided hashes will not work in this environment.

Is there a way to make these hashes platform-agnostic ?

Context : we want to use Poetry to freeze our dependencies versions. The idea here is that the developer generates the lock file, and the CI/CD pipeline will use ```poetry install``` so that the code dependencies will be exactly the same as locally. This allows us to prevent error from transitive dependencies. The problem is that our computers OS is different than the pipeline platform, so we cannot use ````poetry install```, as this will crash due to the hashes not being recognized properly.

Thank you !

**Comment by lilian-delouvy** [comment]
> Which hashes are you talking about? Normally, it does not matter on which platform you create the lockfile and what you want to do already works for the majority of users.

Let's take an example, with the following :

[[package]]
name = "numpy"
version = "1.21.6"
description = "NumPy is the fundamental package for array computing with Python."
optional = false
python-versions = ">=3.7,<3.11"
files = [
    {file = "numpy-1.21.6-cp310-cp310-macosx_10_9_universal2.whl", hash = "sha256:8737609c3bbdd48e380d463134a35ffad3b22dc56295eff6f79fd85bd0eeeb25"}
]

Here,  hash = "sha256:8737609c3bbdd48e380d463134a35ffad3b22dc56295eff6f79fd85bd0eeeb25" would have a different value depending on the platform

**Comment by lilian-delouvy** [comment]
Sorry, my example probably wasn't the best. The problem we have is on local packages. Let's say I've got the following in a pyproject.toml :

[tool.poetry.dependencies]
python = "~3.8"
my_local_package = { path = "./packages/my_local_package-0.0.0-py3-none-any.whl", develop = false }

In my poetry.lock, I have :

[[package]]
name = "my_local_package"
version = "0.0.0"
description = ""
optional = false
python-versions = ">=3.8,<3.9"
files = [
    {file = "my_local_package-0.0.0-py3-none-any.whl", hash = "sha256:3635cb24a8c49d8fee9eaff066529b29989ada949c961aabb92eeec1088f047c"},
]

[package.dependencies]
axa-fr-ocr = "0.0.6.dev0"

[package.source]
type = "file"
url = "packages/my_local_package-0.0.0-py3-none-any.whl"

Here the hash is generated on the user machine when I run ```poetry lock```, but then, on our CI/CD pipeline, which is on a different platform, this hash relates to nothing and so the installation process does not work.

Thank you for your patience !

**Comment by dimbleby** [comment]
> this hash relates to nothing

huh?  it still is the hash of the file

**Comment by lilian-delouvy** [comment]
Yes, but the hash generation and interpretation methods seem to be os-dependent. The generated hash is different depending on whether the lock file is generated on Windows or Ubuntu. This means that our pipeline expects another hash than the one generated on our Windows machines.

**Comment by dimbleby** [comment]
the hash generation is not os-dependent, obviously the files are different.

if that's because you're putting different things in them then that's on you

if you are putting identical things in them and poetry-built wheels are not reproducible eg because there's a timestamp in there or something - then likely a merge request to make them reproducible would be accepted.

you'll need to figure out which it is

**Comment by lilian-delouvy** [comment]
Hello,

I've created a sample project to show you the problem: https://github.com/lilian-delouvy/poetry-hash-test

In this project, I've got a local package that is consumed by another package. The lock files are generated locally, on a Windows machine.
You can see in the github pipeline actions pipeline (https://github.com/lilian-delouvy/poetry-hash-test/actions/runs/7193512483/job/19592126329), step "Compare Hashes", that an error is thrown:

```RuntimeError

  Hash for my-local-package (0.1.0 /home/runner/work/poetry-hash-test/poetry-hash-test/consumer_package/packages/my_local_package-0.1.0-py3-none-any.whl) from archive my_local_package-0.1.0-py3-none-any.whl not found in known hashes (was: sha256:fe4e6016d7ff6225f019d23f[40](https://github.com/lilian-delouvy/poetry-hash-test/actions/runs/7193512483/job/19592126329#step:5:41)7ed79a9d2679c1a66[45](https://github.com/lilian-delouvy/poetry-hash-test/actions/runs/7193512483/job/19592126329#step:5:46)91bd4d2a01200694e70)

  at ~/.local/share/pypoetry/venv/lib/python3.11/site-packages/poetry/installation/executor.py:799 in _validate_archive_hash
      795│         archive_hash: str = "sha256:" + get_file_hash(archive)
      796│         known_hashes = {f["hash"] for f in package.files if f["file"] == archive.name}
      797│ 
      798│         if archive_hash not in known_hashes:
    → 799│             raise RuntimeError(
      800│                 f"Hash for {package} from archive {archive.name} not found in"
      801│                 f" known hashes (was: {archive_hash})"
      802│             )
      803│ 

Cannot install my_local_package.
```


This seems to prove that the hash generation is different depending on the environment. Do I miss something here ?

**Comment by dimbleby** [comment]
yes, as I said, the reason that the hashes are not the same is obviously going to be that the files are not the same

that is the my_local_package-0.1.0-py3-none-any.whl that you build in CI is not the same as the my_local_package-0.1.0-py3-none-any.whl that you built locally and locked against

you will need to understand how they are different
