### ISSUE TITLE
normalize package names for git-sourced packages

### ISSUE THREAD

**Issue by cameronraysmith** [python-poetry/poetry#8783]
### Discussed in https://github.com/orgs/python-poetry/discussions/8781

<div type='discussions-op-text'>

<sup>Originally posted by **cameronraysmith** December 12, 2023</sup>
Is it possible to apply package name normalization to packages installed from git?

If I use 

```toml
HTSeq = {version = "2.0.4", markers = "sys_platform == 'linux' and platform_machine == 'x86_64'", optional = true}
```

I get

<details><summary>normalized htseq poetry.lock record</summary>
<p>

```toml
[[package]]
name = "htseq"
version = "2.0.4"
description = "A framework to process and analyze data from high-throughput sequencing (HTS) assays"
optional = false
python-versions = "*"
files = [
    {file = "HTSeq-2.0.4-cp310-cp310-macosx_10_9_x86_64.whl", hash = "sha256:ab32a9e8ff054b5faaca9be9cfbeb4b60777b53568fc05491153396cef1efdb0"},
    {file = "HTSeq-2.0.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl", hash = "sha256:b7d1b2835619c63fd09c7e5d7e06d4cda8aae5b520a0f345101a28b9f25ab2e0"},
    {file = "HTSeq-2.0.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl", hash = "sha256:506ac5a7ae6d770dc2749bfb9f382469ec61f3ad2840778deeeb04325e28ca26"},
    {file = "HTSeq-2.0.4-cp37-cp37m-macosx_10_9_x86_64.whl", hash = "sha256:ad6abdd738d5d5230d81c69c4dd9e6341cb9d3a95872cd61e91d8bbc9c71c3a4"},
    {file = "HTSeq-2.0.4-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl", hash = "sha256:e74f9d2af92a1f614e6fd51c73c61fcfb205532ac8c41f4085ae21bd9e5dea19"},
    {file = "HTSeq-2.0.4-cp38-cp38-macosx_10_9_x86_64.whl", hash = "sha256:aa708e70be837293dd97bc259d86d4ae6a8b6b52af54635c6df3553e6ca42271"},
    {file = "HTSeq-2.0.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl", hash = "sha256:ff398e8aeeadab013f7e1b36243b97d09bc0775ee54bfda8b6ebfb91c49c9c3f"},
    {file = "HTSeq-2.0.4-cp39-cp39-macosx_10_9_x86_64.whl", hash = "sha256:ab85c30ba0ffb738ecd42f8abec59f1d719662d554db73bf63ce618180e5235e"},
    {file = "HTSeq-2.0.4-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl", hash = "sha256:dfe50aee213f9aab2051280e5ca47397a1bce98255726ffc1f9f65f7185e89d6"},
    {file = "HTSeq-2.0.4.tar.gz", hash = "sha256:5510d855617d61efff2287af4cdc60a73e94bd735e44c15b57f189ea0634e6e0"},
]

[package.dependencies]
numpy = "*"
pysam = "*"

[package.extras]
htseq-qa = ["matplotlib (>=1.4)"]
test = ["matplotlib (>=1.4)", "pandas (>=1.1.0)", "pytest (>=6.2.5)", "scipy (>=1.5.0)"]
```

</p>
</details> 

whereas if I pin to a commit on the upstream source

```toml
HTSeq = {git = "https://github.com/htseq/htseq.git", rev="d312d39187362c8c9664fa8d127ee0fb24733152", optional = true}
```

I get

<details><summary>non-normalized HTSeq poetry.lock record</summary>
<p>

```toml
[[package]]
name = "HTSeq"
version = "2.0.4"
description = "A framework to process and analyze data from high-throughput sequencing (HTS) assays"
optional = false
python-versions = "*"
files = []
develop = false

[package.dependencies]
numpy = "*"
pysam = "*"

[package.extras]
htseq-qa = ["matplotlib (>=1.4)"]
test = ["matplotlib (>=1.4)", "pandas (>=1.1.0)", "pytest (>=6.2.5)", "scipy (>=1.5.0)"]

[package.source]
type = "git"
url = "https://github.com/htseq/htseq.git"
reference = "d312d39187362c8c9664fa8d127ee0fb24733152"
resolved_reference = "d312d39187362c8c9664fa8d127ee0fb24733152"
```

</p>
</details> 

I believe this contributes to an issue where, for example,

```toml
HTSeq = [
  { markers = "sys_platform == 'linux' and platform_machine == 'x86_64'", version = "2.0.4", optional = true},
  { markers = "sys_platform == 'darwin'", git = "https://github.com/htseq/htseq.git", rev="d312d39187362c8c9664fa8d127ee0fb24733152", optional = true}
]
```

places the two records from above side-by-side in poetry.lock and package installation does not respect the markers. Perhaps this is because each record in poetry.lock only ends up being associated with one marker, but then it's impossible to achieve the intended exclusivity.
The same happens with `htseq = [...]`.
I am sure I could fork and rename the package, but that seems quite heavy-handed.

For what it's worth, this also makes it challenging to provide build inputs to the git-installed package with poetry2nix, which still seems to normalize the git-installed package name. For example, [this](https://github.com/pinellolab/DNA-Diffusion/blob/cf466b9059045db01b6f311f23b15030b7cf9080/flake.nix#L65) fails to inject the specified dependency into the build environment when using the git-installed package, even if I declare an alias in nix.</div>

**Comment by dimbleby** [comment]
I cant tell what you are trying to report here.  What did you do, what did you expect to happen, what actually happened?  Please give a reproducible example.

**Comment by cameronraysmith** [comment]
apologies if I converted the discussion to an issue too hastily as the problem seemed clear enough from the nature of the response received in the discussion.

@dimbleby let me know if you think the changes I made above begin to clarify the point sufficiently for you or if you feel I need to create a repo for this issue with instances of all associated files whose contents I only sketch above.

I will leave the issue closed until or unless it is agreed it is clear enough to be open.

**Comment by dimbleby** [comment]
the name in poetry.lock should be only cosmetic, an internal detail that users have no reason to care about.

if you have some bug relating to markers and optional dependencies - please frame your report in terms of the user-visible symptoms.

**Comment by cameronraysmith** [comment]
I'll leave this closed then.

**Comment by cameronraysmith** [comment]
there are downstream tools that use the contents of the poetry.lock file and so this issue as currently framed becomes user-facing at that point
