### ISSUE TITLE
New installers fail to install `_templates` directory in bokeh 1.4.0

### ISSUE THREAD

**Issue by Pathfinder216** [python-poetry/poetry#8793]
- **Poetry version**: 1.7.1, 1.6.1, 1.5.1, 1.4.2, 1.4.0
- **Python version**: 3.11.6
- **OS version and name**: Windows 11
- **pyproject.toml**: https://gist.github.com/Pathfinder216/46619c8a1b4d65937e4d24bc59310096

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a [recommended method](https://python-poetry.org/docs/#installation).
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.

## Issue

<details><summary>When trying to run a python script with `import bokeh.embed`, I get this error:</summary>
<p>

```
Traceback (most recent call last):
  File "C:\Users\<username>\Documents\playground\poetry_test\main.py", line 1, in <module>
    from bokeh import embed
  File "C:\Users\<username>\documents\playground\poetry_test\.venv\Lib\site-packages\bokeh\embed\__init__.py", line 54, in <module>
    from .server import server_document
  File "C:\Users\<username>\documents\playground\poetry_test\.venv\Lib\site-packages\bokeh\embed\server.py", line 29, in <module>
    from ..core.templates import AUTOLOAD_TAG, FILE
  File "C:\Users\<username>\documents\playground\poetry_test\.venv\Lib\site-packages\bokeh\core\templates.py", line 95, in <module>
    JS_RESOURCES = _env.get_template("js_resources.html")
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<username>\documents\playground\poetry_test\.venv\Lib\site-packages\jinja2\environment.py", line 997, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<username>\documents\playground\poetry_test\.venv\Lib\site-packages\jinja2\environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<username>\documents\playground\poetry_test\.venv\Lib\site-packages\jinja2\loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<username>\documents\playground\poetry_test\.venv\Lib\site-packages\jinja2\loaders.py", line 214, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: js_resources.html
```
</p>
</details> 

I tried this with poetry 1.3.2 and all the above-mentioned poetry versions (and locked when switching versions, though there were no differences relevant to this issue), and it only worked on 1.3.2 (with one exception, see below). When I installed with poetry 1.3.2, there was a `Lib/site-packages/bokeh/core/_templates` directory in my virtual environment. When I installed with all the newer poetry versions, that directory did not exist. I noticed in the release notes that 1.4.0 deprecated the old installer, defaulting to a newer installer. I tried using different installers, and it seems to be a bug with the newer installers, introduced in 1.4.0. Here are the configurations I tried:

| poetry version | experimental.new-installer | installer.modern-installation | Error? |
|-----------------|------------------------------|---------------------------------|--------|
| 1.3.2 | false | N/A | No |
| 1.3.2 | true | N/A | No |
| 1.4.0 | false | false | No |
| 1.4.0 | true | false | Yes |
| 1.4.0 | true | true | Yes | 
| 1.7.1 | N/A | false | Yes |
| 1.7.1 | N/A | true | Yes |

**Comment by dimbleby** [comment]
bokeh 1.4.0 is ancient, I suppose it's likely mis-packaged in some way.  But I don't care to investigate and neither should you: upgrade to a recent version.

**Comment by Secrus** [comment]
If anyone is interested enough in this, feel free to dig in, find the issue, and submit a pull request, but generally I agree with @dimbleby, it's probably some miss-packaged version.
