### ISSUE TITLE
Poetry Dependency Resolution Issue while Dependency extras with source

### ISSUE THREAD

**Issue by lucemia** [python-poetry/poetry#8796]
- **Poetry version**:  1.7.1
- **Python version**: python3.10
- **OS version and name**:  MacOs
- **pyproject.toml**: https://gist.github.com/lucemia/ea041236e05d6ca44e6e860d32e1e3e2

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a [recommended method](https://python-poetry.org/docs/#installation).
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

When using `poetry update` to resolve dependencies, Poetry treats dependencies without extras as distinct entities, leading to unexpected behavior. This issue can be illustrated as follows:

1. In repo-a's pyproject.toml, the definition for the source of private-package-a[extra-a] is set to "source-a".
2. repo A has a dependency on pivate-pacakge-b, and pivate-pacakge-b in turn depends on private-package-a (without extra).
3. However, repo-a's pyproject.toml does not define the source for private-package-a without any extras.

The problem arises when Poetry encounters this configuration. It raises an error: "Package private-package-a (*) not found." The issue here is that package source keys are not inherited by their dependencies when extras are involved, which is unexpected behavior.

### repo-a's pyproject.toml

```
[tool.poetry]
name = "repo-a"
version = "0.0.0"
description = ""
[tool.poetry.dependencies]
private-package-a = { version = "*", source = "source-a", extras = ["extra-a"] }
private-package-b = { version = "*", source = "source-a" }
[[tool.poetry.source]]
name = "source-a"
priority = "explicit"
```

### private-package-b's pyproject.toml

```
[tool.poetry]
name = "private-package-b"
version = "0.0.0"
description = ""
[tool.poetry.dependencies]
private-package-a = { version = "*", source = "source-a" }
[[tool.poetry.source]]
name = "source-a"
priority = "explicit"
```

## Expected Behavior:
- Is it considered valid in Poetry to define a package with multiple sources (if they have different extras)? If not, implementing a validation check could be beneficial.

## Temporary Workaround:

To work around this issue, you can temporarily declare the source for the dependency without extras in another group to avoid encountering the error.

```
[tool.poetry]
name = "repo-a"
version = "0.0.0"
description = ""

[tool.poetry.dependencies]
private-package-a = { version = "*", source = "source-a", extras = ["extra-a"] }
private-package-b = { version = "*", source = "source-a" }

[tool.poetry.group.service.dependencies]
private-package-a = { version = "*", source = "source-a" } # add this line

[[tool.poetry.source]]
name = "source-a"
priority = "explicit"
```

**Comment by dimbleby** [comment]
Duplicate #8614 please close

**Comment by lucemia** [comment]
@dimbleby sorry for bothering
