### ISSUE TITLE
Poetry is unable to resolve dependencies when both requests and cloudpathlib[s3] libraries are added to project

### ISSUE THREAD

**Issue by boschmic** [python-poetry/poetry#8799]
- **Poetry version**: 1.7.1
- **Python version**: 3.10.12
- **OS version and name**: Ubuntu 22.04.3 LTS 64bit
- **pyproject.toml**: https://gist.github.com/boschmic/0c889b86c149ca86589031ca9afb2578

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a [recommended method](https://python-poetry.org/docs/#installation).
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
Poetry is unable to resolve dependencies if `requests` and `cloudpathlib[s3]` are included in the `pyproject.toml` (see link above).

I tried with [PDM](https://pdm-project.org/latest/), unlike Poetry it has no issues resolving those dependencies. Here is the `project.toml` that I used for PDM:
```
[project]
name = "foo"
version = "0.1"
dependencies = [
    "requests",
    "cloudpathlib[s3]",
]
requires-python = ">=3.9,<3.12"
```

**Comment by dimbleby** [comment]
please do the things the issue template asks you to do

**Comment by dimbleby** [comment]
anything with aws stuff in it is usually related to https://github.com/boto/botocore/issues/2926 - try putting some recent lower bound on botocore in your dependencies

(amazon like to release zillions of versions of this library, if you get unlucky in the search then poetry can get stuck backtracking through all of them.  There's nothing much to be done about that: except that you can stop it from happening by providing a recent lower bound)

**Comment by boschmic** [comment]
Thanks for the hint.
Indeed, adding a lower-bound i.e. `botocore = ">=1.34"` resolves my problem.
Weirdly enough, the problem is also resolved by adding botocore without any bound (i.e. `botocore = "*"`).

**Comment by dimbleby** [comment]
probably that's enough to tip poetry into resolving botocore first, which means that it has to backtrack on urllib3 - and there are only a reasonable number of versions of urllib3 to backtrack through

I don't think there's anything that's likely to be done about this here, sorry, might as well close please

**Comment by boschmic** [comment]
I see! Sure. I will close the issue then.
Thanks again for your help and your explanations!

**Comment by dimbleby** [comment]
actually one thing you could do, if you were feeling civic-minded, would be to go and ask cloudpathlib to put a recent lower bound on their boto3 dependency - that would help the next person
