### ISSUE TITLE
How are people supposed the lock version of poetry?

### ISSUE THREAD

**Issue by Sequential-circuits** [python-poetry/poetry#8800]
I am trying to install something and it says the lock version is incorrect, even though when I edit /usr/lib/python3/dist-packages/poetry/packages/locker.py it clearly says 1.1, and I have installed that version

And, worse, I get a message saying I should "Upgrade Poetry to be able to read the lock file or, alternatively regenerate the lock file with the `poetry lock` command."

And when I try poetry lock (as the version IS correct as I said) I get the SAME dumb message:

  _The lock file is not compatible with the current version of Poetry.
  Upgrade Poetry to be able to read the lock file or, alternatively, regenerate the lock file with the `poetry lock` command.

  at /usr/lib/python3/dist-packages/poetry/packages/locker.py:481 in _get_lock_data
      477│                 "Upgrade Poetry to ensure the lock file is read properly or, alternatively, "
      478│                 "regenerate the lock file with the `poetry lock` command."
      479│             )
      480│         elif not lock_version_allowed:
    → 481│             raise RuntimeError(
      482│                 "The lock file is not compatible with the current version of Poetry.\n"
      483│                 "Upgrade Poetry to be able to read the lock file or, alternatively, "
      484│                 "regenerate the lock file with the `poetry lock` command."_

**Comment by dimbleby** [comment]
please do the things that the issue template asks you to do

the error message seems to me to be completely clear, I don't understand what you can be asking.  Do what it tells you to do.
