### ISSUE TITLE
"Can't instantiate abstract class IsolatedEnv with abstract methods executable" when installing packages

### ISSUE THREAD

**Issue by styxxx** [python-poetry/poetry#8803]
When trying to install some packages (for example vext) the process fails:

```
TypeError

  Can't instantiate abstract class IsolatedEnv with abstract methods executable, scripts_dir

  at /usr/lib/python3/dist-packages/poetry/installation/chef.py:131 in _prepare
      127│     ) -> Path:
      128│         from subprocess import CalledProcessError
      129│ 
      130│         with ephemeral_environment(self._env.python) as venv:
    → 131│             env = IsolatedEnv(venv, self._pool)
      132│             builder = ProjectBuilder.from_isolated_env(
      133│                 env, directory, runner=quiet_subprocess_runner
      134│             )
      135│             env.install(builder.build_system_requires)
```

Similar issues were mentioned in #8458 and and #8434. But in these cases a wrong python-build version (>=1.0.0) and/or old poetry was the reason. That's not the case here since the python-build version installed on my machine is 0.10.0-1 and poetry is 1.7.1. So not the combination mentioned in those reports and therefore the solution doesn't work. 
```$ dpkg -l|grep poetry
ii  python3-poetry                                   1.7.1+dfsg-1                              all          Python dependency management and packaging made easy (Python 3)
ii  python3-poetry-core                              1.8.1-1                                   all          Poetry PEP 517 Build Backend
ii  python3-build                                    0.10.0-1                                  all          Simple, correct PEP517 package builder (Python 3)
```

Installed packages are up-to-date from the debian testing repositories. I also tried with a new poetry project, same result.

**Comment by dimbleby** [comment]
Debian packages are neither created nor supported from this repository.

You should nstall poetry using a supported method, or take your bug report to Debian.

Please close.

**Comment by radoering** [comment]
To add some context: poetry 1.7.1 is not compatible with build 0.10.0, as you can see in https://github.com/python-poetry/poetry/blob/1.7.1/pyproject.toml#L37

**Comment by ibgp2** [comment]
Hello,
I faced the same problem under Debian and indeed, installing `poetry` via PIP fixed the problem. More precisely, I ran
```sh
sudo apt install python3-pip
sudo apt purge python3-poetry
pip3 install poetry
poetry add git+ssh://git@mygitlabinstance:myuser/myproject.git
```
In my case, this installed the following PIP packages: 
```
Installing collected packages: rapidfuzz, platformdirs, pkginfo, build, poetry-plugin-export, poetry
```
Surprisingly, if afterwards, I reinstall poetry through APT and revert my `pyproject.toml` and `poetry.lock`, it now works
```sh
sudo apt install python3-poetry
pip3 remove poetry
poetry add git+ssh://git@mygitlabinstance:myuser/myproject.git
```
So, I suspect that the Debian package has lazy dependencies, but maybe I'm wrong... Hope it helps...

**Comment by eamanu** [comment]
Hi,

Debian Maintainer here. As you probably deduced, python3-build in Debian is not updated to latest version. 

For more information please follow https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1058670

Cheers,
