### ISSUE TITLE
Unclarity with `poetry show --why`

### ISSUE THREAD

**Issue by ValentinCalomme** [python-poetry/poetry#8816]
> This is in the context of me using `poetry==1.7.1`

Hi! was going through the documentation and saw the `--why` flag for the `poetry show` option.

Currently, the only explanation as to what the flag does is: 

> --why: When showing the full list or a --tree for a single package, display why a package is included.

I'd say what it means is super clear. Of course, I tried out the flag, which is clearer when used with the `--tree` option. Something like this would be more obvious to me:

> --why: When showing the full list, or a --tree for a single package, display whether a package is a direct dependency or which packages require it

Thanks a lot, looking forward to version 1.8!

**Comment by dimbleby** [comment]
To improve docs or help text - submit a merge request!

**Comment by ValentinCalomme** [comment]
I would love to submit a merge request, but I would like to know whether my interpretation is correct to begin with 😊
