### ISSUE TITLE
Poetry should provide a way to move the configuration easily

### ISSUE THREAD

**Issue by hughperkins** [python-poetry/poetry#8818]
- [ ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request

Poetry should provide an option to move the configuration to the new location, without having to google around.  
 couple of options:
- ask 'Do you want me to move this for you? Y/n' , or
- have a command like `poetry self config upgrade`, or `poetry self move-config` or similar.

(this relates to the 'closed' issue https://github.com/python-poetry/poetry/issues/6854, which asks how to move the configuration. This new issue asserts that poetry should provide a way to avoid having to read through that loooonnnggg thread....)

**Comment by dimbleby** [comment]
not convinced this is worthwhile, especially now that this has been settled for several months - most everyone who should have moved their config has already done so by now.

also I'm not honestly sure what the confusion is.  The message says "found configuration files \<here\>, consider moving them \<there\>" - is it not clear that the action to take is simply to move the configuration files from here to there?

suggest that if this is indeed not obvious then a more cost-effective approach is just to improve that message

I'm guessing you're not intending to submit a merge request for the thing that you've asked for, but perhaps you could manage an improved message?

**Comment by hughperkins** [comment]
I mean, I already moved my config, after reading through that long thread...

I suppose you can make the argument that anyone who installed the old version of poetry most likely by now has already decided what they think about poetry, and isn't someone who will just walk off on a whim...

**Comment by dimbleby** [comment]
If you don't care about this enough to do anything about it then I expect nor does anyone else - might as well close it.

**Comment by hughperkins** [comment]
Alright. Go ahead...

**Comment by dimbleby** [comment]
You have the power to close this, I don't
