### ISSUE TITLE
Unable to use latest python 3.12.1 from git with poetry

### ISSUE THREAD

**Issue by matejsp** [python-poetry/poetry#8836]
- **Poetry version**: 1.7.1
- **Python version**: 1.12.1+
- **OS version and name**: MacOSX
- **pyproject.toml**: ... any

- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a [recommended method](https://python-poetry.org/docs/#installation).
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

I wanted to reproduce some error that supposedly fixed in latest unreleased python 3.12.

```
> pyenv install 3.12-dev
> poetry env use `pyenv prefix 3.12-dev`/bin/python
Creating virtualenv bitstamp in /Users/myuser/projects/bitstamp/.venv
Using virtualenv: /Users/myuser/projects/bitstamp/.venv
> poetry install --with=dev --no-root                                          
Installing dependencies from lock file

Invalid PEP 440 version: '3.12.1+'
```

**Comment by dimbleby** [comment]
duplicate #6925 please close
