### ISSUE TITLE
poetry install from a requirements.txt

### ISSUE THREAD

**Issue by Sanix-Darker** [python-poetry/poetry#8837]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request

Hi,
I'm a big fan of this project and seeing how it's growing I was just wondering if it was possible to easily convert dependencies from an "old project" to pyproject.toml, by which I mean if there was any chance that the `poetry init --from-source requirements.txt` command line is inside the poetry roadmap project ?

**Comment by dimbleby** [comment]
not so far as I know, but won't simply `poetry add $(cat requirements.txt)` do the job?

**Comment by Sanix-Darker** [comment]
> not so far as I know, but won't simply poetry add $(cat requirements.txt) do the job?

not if there is not yet a `pyproject.toml` file in the directory... otherwise you will get : 
```
$ poetry add $(cat requirements.txt)

Poetry could not find a pyproject.toml file in /your/project/path or its parents
```

**Comment by dimbleby** [comment]
Of course.  The contents of requirements.txt cannot be used used to create a new pyproject.toml: the needed information just isn't there.

**Comment by Sanix-Darker** [comment]
> Of course. The contents of requirements.txt cannot be used used to create a new pyproject.toml: the needed information just isn't there.
> 
> poetry init

And what about just a basic initialization, just with the basename of the current directory.
`poetry init --from-source requirements.txt --python 3.11` ?

Other than the name and the python version, i don't know if there is a need for more mandatory params... ?

Also,
Note: We can specify that inside the requirements.txt, we separate dev and prod deps just by specifying it as comments 
```
# prod
requests
# dev
type-requests
```
Or better, if we have a `requirements.prod.in` or `requirements.dev.in`, we could add the same flag for `poetry add`... "--group dev" or "--group prod".

**Comment by dimbleby** [comment]
`poetry init` already seems to be to be quite satisfactory for initializing a pyproject.toml.

I am quite sure that having poetry try to interpret comments in a requirements.txt is a bad idea.

To my mind this is a solution looking for a problem, but if you find value in it then by all means submit a merge request and see if maintainers agree with you.

**Comment by Sanix-Darker** [comment]
> poetry init already seems to me to be quite satisfactory for initializing a pyproject.toml.

True, am requesting for a "niche" feature, that's for sure...

>  but if you find value in it then by all means submit a merge request and see if maintainers agree with you.

i would rather prefer a `let's go` from them first... 😅  so that i don't make a Merge Request that could be refused after all. 
that's the purpose of this issue...

**Comment by radoering** [comment]
IMO, this might be better suited for a plugin. Have you already searched for plugins that might cover your use case?
