### ISSUE TITLE
poetry add command does not work behind company proxy

### ISSUE THREAD

**Issue by legosiv** [python-poetry/poetry#8839]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x]   I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x]  If an exception occurs when executing a command, I executed it again in debug mode (-vvv option). 

OS version and name: Windows 11

Poetry (version 1.7.1)

### ISSUE

With the poetry add command I could not install the package typer using `poetry add "typer[all]"`

Before executing `poetry add` the proxy has been added to pip config.

this works ---> `poetry run python -m pip install "typer[all]"`

**Comment by dimbleby** [comment]
pip configuration has nothing to do with poetry: it is for configuring pip, not for configuring poetry

duplicate #3748 etc

**Comment by legosiv** [comment]
i see. is there a way to configure proxy settings for poetry?

**Comment by dimbleby** [comment]
see #3748
