### ISSUE TITLE
Poetry export support for omiting markers (poetry export --without-markers)

### ISSUE THREAD

**Issue by matejsp** [python-poetry/poetry#8840]
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request

There was fearture request to add markers to export:
https://github.com/python-poetry/poetry/issues/1011

And there was pull request that added support for markers but allowed to export without them: poetry export --without-markers
https://github.com/python-poetry/poetry/pull/1233/files

however it was superseded with another PR:
https://github.com/python-poetry/poetry/pull/1277/files
that did not implement this feature.

There is already without-hashes ... 
but without-markers is also usable to us (problem with some deps and incorrect markers).

**Comment by dimbleby** [comment]
(wrong repository)

Duplicate https://github.com/python-poetry/poetry-plugin-export/issues/191, which discusses why it's a wrong idea
