### ISSUE TITLE
`poetry new` silently transforms underscores to dashes

### ISSUE THREAD

**Issue by Gerrit-K** [python-poetry/poetry#8848]
- **Poetry version**: `1.7.1`
- **Python version**: `3.9.18`
- **OS version and name**: `macOS 14.2.1 (23C71)`
- **pyproject.toml**: none, see repro steps below

- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a [recommended method](https://python-poetry.org/docs/#installation).
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
Poetry doesn't handle underscores in package names really well. Two examples are:
- `poetry new test_package`
  - prints `Created package test_package in test_package`
  - but `cat test_package/pyproject.toml` actually prints `name = "test-package"`
- `poetry version` still prints `test-package`, even if you manually change `pyproject.toml` to `name = "test_package"`

**Comment by dimbleby** [comment]
that is the correctly normalized package name, not a bug

**Comment by Gerrit-K** [comment]
You're right, sorry. I somehow didn't find [PEP-503](https://peps.python.org/pep-0503/#normalized-names) when researching this.

**Comment by Gerrit-K** [comment]
Though, on second thought, I'd argue that `poetry version` should at least return whatever is set as `name`. This is done correctly in `poetry publish`, e.g. `name = "test_package"` is correctly published as `test_package`, but `poetry version` results in `test-package 0.1.0`.

@dimbleby is this also by design?

**Comment by dimbleby** [comment]
:shrug:

if you want to submit a merge request changing `package.name` to `package.pretty_name` at https://github.com/python-poetry/poetry/blob/022308e9c4ce1f9dec17fa57d44fa9ab9a0c4a16/src/poetry/console/commands/version.py#L89 then I wouldn't much care either way, but no doubt a maintainer would take a view

**Comment by Gerrit-K** [comment]
Alright, thank you! I'll take a look
