### ISSUE TITLE
Enable Good Practices for Packaged Data for Python Packages in Poetry

### ISSUE THREAD

**Issue by jbadwaik** [python-poetry/poetry#8867]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request

Currently, poetry does not allow good practices while packaging data with python. In particular, poetry expects the data associated with python packages to live alongside the python source files themselves. Furthermore, poetry does not install data files in standard data locations, and instead installs them in unstable locations inside `site-packages` which render the data files to be unusable to non-python programs. 

In order to allow for good practices for data distribution, poetry should explicitly allow for a `data_files` like feature from setup-tools which allows installation to stable locations inside the target file-system.

**Comment by jbadwaik** [comment]
I don't think its completely relevant here. Because, its not necessarily about files being accessible at runtime. Instead, it is about data files that should be installed along with a  python project. Those data files might not need to be accessible from the python runtime. There are multiple use cases here like for example templates to use with the python tool, man pages, data files to be deployed by the server.

**Comment by dimbleby** [comment]
> I don't think its completely relevant here

you are mistaken: the exact mechanism that you are asking for is explicitly un-recommended.

if you want to install things that live outside of the python package: then you should consider building rpms, debs etc.  This is not something that is currently supported by the python packaging ecosystem.

futther references discussing the fact that what you want is deprecated and discouraged eg: https://github.com/pypa/setuptools/discussions/2648, https://discuss.python.org/t/should-there-be-a-new-standard-for-installing-arbitrary-data-files/7853,

**Comment by jbadwaik** [comment]
I see. Does that mean that poetry is not recommended for anything other than pure python packages?

**Comment by dimbleby** [comment]
It means that python packages are not recommended for anything other than python packages
