### ISSUE TITLE
MacOS auto-logout after "poetry shell"

### ISSUE THREAD

**Issue by bfaust-bp** [python-poetry/poetry#8869]
Since last month (without any poetry update), I've been facing auto-logout issues when running the "poetry shell" command.

The "poetry shell" command works well (I believe) because I can see the virtual env activation.
But, in less than 1 second, the venv exits with this message:

prompt: poetry shell
Spawning shell within /Users/xxx/Library/Caches/pypoetry/virtualenvs/xxx-ztWiSVXs-py3.11

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
bash-3.2$ . /Users/xxx/Library/Caches/pypoetry/virtualenvs/xxx-ztWiSVXs-py3.11/bin/activate
(xxx-py3.11) bash-3.2$ timed out waiting for input: auto-logout
prompt:

Poetry version: Poetry (version 1.7.1)
Python version: Python 3.11.2
OS version and name:
    MacOS Sonoma
    ProductName: macOS
    ProductVersion: 14.2.1
    BuildVersion: 23C71
    Darwin ***** 23.2.0 Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:18 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6000 arm64

## Issue
Auto-logout after running the "poetry shell" command.
In less then 1 second, the venv exits with this message: timed out waiting for input: auto-logout

**Comment by dimbleby** [comment]
this is certainly not something that poetry is doing

do leave an update when you figure it out, perhaps the next person will appreciate it

**Comment by abn** [comment]
The issue is most definitely not something Poetry can fix. Looks like you have `TMOUT` set somewhere in your bash profile.

See
- https://unix.stackexchange.com/a/340654
- https://www.howtouselinux.com/post/fix-ssh-timed-out-waiting-for-input-auto-logout-with-tmout-and-stopidlesessionsec-configurations


You can check this by simply executing the following.

```sh
bash -c 'echo $TMOUT'
```
