### ISSUE TITLE
official install from install.python-poetry.org requires SSL UnsafeLegacyRenegotiation with openssl 3.*

### ISSUE THREAD

**Issue by mayorblock** [python-poetry/poetry#8881]
- **Poetry version**: any version using the [official installer](https://python-poetry.org/docs/#installing-with-the-official-installer)
- **Python version**: 3.11 (but related to openssl 3.* and would be the same for all python versions)
- **OS version and name**: any linux / mac with openssl 3 (I am using debian on Docker)
- **pyproject.toml**:  N/A

- [ x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a [recommended method](https://python-poetry.org/docs/#installation).
- [ x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x ] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
Underlying issues described [here](https://github.com/curl/curl/issues/8943):
With openssl 3 `SSL_OP_LEGACY_SERVER_CONNECT` is no longer set by default. When I try to install poetry with curl I get 
``` bash
> curl -sSL https://install.python-poetry.org | python3 -
curl: (35) OpenSSL/3.0.11: error:0A000152:SSL routines::unsafe legacy renegotiation disabled
```

I noticed because the [official python docker images](https://hub.docker.com/_/python/tags?page=1) were updated a few days ago and now ship with openssl 3.0.*:
<img width="939" alt="image" src="https://github.com/python-poetry/poetry/assets/126508264/0957bb2c-012b-4f4c-b522-07cf17a9df89">

A work-around (that I have confirmed work for me at least with the 3.11 image) is described [here](https://github.com/curl/curl/issues/8943#issuecomment-1508916319) and elaborated on [SE](https://stackoverflow.com/a/72245418/6742358). However, and I hope you agree :), the proper solution would be to update install.python-poetry.org.

**Comment by dimbleby** [comment]
(wrong repository, this should be at https://github.com/python-poetry/install.python-poetry.org/)

works fine here, perhaps you have a proxy in the way or something
```dockerfile
FROM python:3.11

RUN curl -sSL https://install.python-poetry.org | python3 -
CMD /root/.local/bin/poetry --version
```
