### ISSUE TITLE
(🐞) Error messages are often non-contextual and completely useless

### ISSUE THREAD

**Issue by KotlinIsland** [python-poetry/poetry#8883]
### Consider:
```comand
> poetry install

Cannot overwrite a value (at line 10, column 20)
```
<details><summary>The actual context</summary>
<p>

```toml
[tool.poetry]
name = "test"
version = "1"
description = ""
authors = ["..."]

[tool.poetry.dependencies]
python = "^3.12"
basedmypy = "2.4.0"
basedmypy = "2.4.0"
```

</p>
</details> 

My only option from here is to supply `-v` and see a wall of source code.

This issue is not this specific scenario, rather, the general content of error messages in Poetry.

# Desired behaviour
The context of any third party error is presented:
```console
> poetry install

An unexpected error was encountered during analysis of the pyproject.toml file:

    Cannot overwrite a value (at line 10, column 20)
```

If there is not specific handling for a third party error then:
```console
> poetry install

An unexpected error occurred during execution of poetry:

    TOMLDecodeError: Cannot overwrite a value (at line 10, column 20)

You can run again with `-v` and raise an issue at https://github.com/python-poetry/poetry/issues
```

## Related
- #7832

**Comment by dimbleby** [comment]
Like its duplicate #5885, this report is too broad to be useful.

Please raise issues - or preferably merge requests - against _specific_ unhelpful errors.

**Comment by KotlinIsland** [comment]
> this report is too broad to be useful

I disagree, there should be some level of explanation on an unhandled exception, not just the raw error message.

**Comment by KotlinIsland** [comment]
- duplicate-of #5885
