### ISSUE TITLE
Fail installation on centos8 with specific python version

### ISSUE THREAD

**Issue by yabb85** [python-poetry/poetry#8884]
- **Poetry version**: 1.7.1
- **Python version**: 3.11.5
- **OS version and name**: Centos8 stream
- **pyproject.toml**: 
```
[tool.poetry]
name = "test"
version = "0.1.0"
description = "test packaging"
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a [recommended method](https://python-poetry.org/docs/#installation).
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
We use CentOS 8 Stream to develop with python.
Like the default version of python (3.6) is not compatible with poetry, we install a new python version (3.11) and install poetry with the following command
```
curl -sSL https://install.python-poetry.org | python3.11 -
```
after install, it is possible to use poetry init but all command used to manage dependencies and environments fails:
```
> poetry add tasklib
Creating virtualenv test-fuH6okzm-py3.11 in /home/laurent/.cache/pypoetry/virtualenvs

failed to query /usr/bin/python3 with code 1 err: '  File "/home/laurent/.local/share/pypoetry/venv/lib64/python3.11/site-packages/virtualenv/discovery/py_info.py", line 7\n    from __future__ import annotations\n    ^\nSyntaxError: fut
ure feature annotations is not defined\n'
```
Same result with poetry install...
The python used is /usr/bin/python3 instead of /usr/bin/python3.11 or /home/space/.local/share/pypoetry/venv/bin/python

## Expected

Correct creation of virtualenv or package managing.

**Comment by dimbleby** [comment]
poetry and 3.6 don't play nice together (previously: #8185).  You'll need to create the virtualenv some other way.

**Comment by yabb85** [comment]
To avoid issue with 3.6 I use the command with call to python3.11
```
curl -sSL https://install.python-poetry.org | python3.11 -
```
If poetry is installed in virtualenv, the commands add and install freeze
```
❯ poetry install -vvvv
Loading configuration file /home/laurent/.config/pypoetry/config.toml
Warning: Found deprecated priority 'secondary' for source 'artifactory' in pyproject.toml. Consider changing the priority to one of the non-deprecated values: 'default', 'primary', 'supplemental', 'explicit'.
Adding repository artifactory (https://hc-eu-west-aws-artifactory.cloud.health.ge.com/artifactory/api/pypi/pypi-awanalytics-prod/simple) and setting it as secondary
Adding repository PyPI (https://pypi.org/simple/) and setting it as primary
Using virtualenv: /home/laurent/.cache/pypoetry/virtualenvs/project-prio-xri3QFtW-py3.11
Updating dependencies
Resolving dependencies...
   1: fact: project-prio is 0.1.0
   1: derived: project-prio
   1: fact: project-prio depends on tasklib (^2.5.1)
   1: fact: project-prio depends on rich (^13.6.0)
   1: fact: project-prio depends on pendulum (^2.1.2)
   1: selecting project-prio (0.1.0)
   1: derived: pendulum (>=2.1.2,<3.0.0)
   1: derived: rich (>=13.6.0,<14.0.0)
   1: derived: tasklib (>=2.5.1,<3.0.0)
[keyring.backend] Loading KWallet
[keyring.backend] Loading SecretService
[keyring.backend] Loading Windows
[keyring.backend] Loading chainer
[keyring.backend] Loading libsecret
[keyring.backend] Loading macOS
^C   1: Version solving took 63463.429 seconds.
   1: Tried 1 solutions.
```
This issue is reproducible on other system with centos8 and python 3.11 installed

**Comment by dimbleby** [comment]
that doesn't seem to be anything much to do with where this issue started.  But if you have a reproducible problem then please provide a way to reproduce it.  eg a dockerfile is often a good way,

**Comment by dimbleby** [comment]
actually that's probably duplicate #8623

so please close this: the first part is duplicate #8185, the second is duplicate #8623

**Comment by yabb85** [comment]
Must I reopen a new ticket for issue seen when poetry is installed in virtualenv or I must continue on this ticket?
for me two possibilities:
- possibility to install poetry with specified version like the command displayed in ticket `curl -sSL https://install.python-poetry.org | /usr/bin/python3.11 -` and continue this ticket
- fix install/add poetry command when poetry is installed in virtualenv.

Thanks

**Comment by yabb85** [comment]
Thanks the workaround in ticket #8623 fix the issue.

**Comment by dimbleby** [comment]
therefore please close this
