### ISSUE TITLE
Support `source` overrides when merging dependencies between groups

### ISSUE THREAD

**Issue by TheKevJames** [python-poetry/poetry#8885]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request
The current logic for setting the same dependency in multiple groups (eg. by merging the keys) does not allow for overrides of the `source` value and thus breaks `path` (and presumably `git` / `url`) overrides.

### Current Behaviour
If we specify a standard dependency as follows:
```
[tool.poetry.dependencies]
common-code = { version = ">=1.0.0, <2.0.0" }
```
Then is is possible to merge in a path dependency at development time, to be able to iterate on library changes, with:
```
[tool.poetry.group.dev.dependencies]
common-code = { path = "../common", develop = True }
```
(so long as the path dependency is still within the `version` range, of course!)

If the former dependency is pulled from a non-default source, though, this no longer becomes possible:
```
[tool.poetry.dependencies]
common-code = { version = ">=1.0.0, <2.0.0", source = "private-index" }

[tool.poetry.group.dev.dependencies]
common-code = { path = "../common", develop = True }

[[tool.poetry.source]]
name = "private-index"
url = "SNIP"
priority = "explicit"  # same behaviour regardless of value here
```

This gives the following error when attempting to `poetry lock`:
```
Incompatible constraints in requirements of application-package (0.0.1):
common-code @ file:///home/kevin/src/REPO/common (1.1.4)
common-code (>=1.1.0,<2.0.0) ; source=private-index
```

It should be possible to override dependencies with explicit sources in the same way as those without.

**Comment by dimbleby** [comment]
Those are plainly incompatible dependencies.

Poetry does not support 'overrides' of any sort: the other works because "no source specified" is taken to mean "any source will do".  

Specifying contradictory sources cannot work.

**Comment by TheKevJames** [comment]
> Specifying contradictory sources cannot work.

I get why not in terms of the current implementation, but why not in terms of usability? If I don't specify the source, poetry might resolve to a given wheel in a given repository and I am allowed to "override" it for development. If I do specify the source to be the exact same one as it would have resolved, suddenly I am no longer able to do the same debugging action.

`source`, especially with the `priority` fields, can end up being used as a deploy-time decision of where to fetch a given package.. it doesn't intuitively make sense that that decision overrides the ability to debug said package.

Maybe there's some other way of accomplishing what I am aiming for here? For example, perhaps `source = "*"` in the `path` dependency could let us re-set that "any source will do" descriptor?

**Comment by dimbleby** [comment]
I don't see that it makes sense to specify that you explicitly want to get a package from two distinct places.  Only one of those things can be true.

Perhaps a supplemental source would be better for whatever your use case is: don't require a particular source on the dependency at all.

**Comment by TheKevJames** [comment]
> I don't see that it makes sense to specify that you explicitly want to get a package from two distinct places. Only one of those things can be true.

I guess only one can be true _at a time_, but not _in all use-cases for installing packages via poetry_.

When I am running my app in production, I want to explicitly ensure that my private package dependencies are installed from our private package index via `priority = 'explicit'`, lest I be subject to supply-chain attacks by a public pypi package which happens to use the same names we use for internal packages.

When I am debugging my app locally, I want to be able to modify a library it depends on and test how it affects that app without needing to release a new version of that library for each line I change.

**Comment by dimbleby** [comment]
If you are installing after packaging (or with pip), the "source" is lost (because there is no space for it in the package metadata).

If you are installing directly via poetry  then apparently your intention is  that the source should be "overridden".

What are the circumstances on which an overridden source was meaningful?

**Comment by TheKevJames** [comment]
> What are the circumstances in which an overridden source was meaningful?

Exactly the above case I described: debugging, ie. installing with dev dependencies via poetry, and being able to have the source be the local working `path` dependency instead of the packaged-and-deployed-to-our-private-index source.

**Comment by dimbleby** [comment]
but what command do you intend to type that will cause poetry to ignore your override?  You can't have it both ways!

**Comment by dimbleby** [comment]
pretty sure that where you're about to end up is duplicating #1168, in which case please close this as a duplicate

**Comment by TheKevJames** [comment]
> In what circumstance was the overridden source meaningful? why even provide the source, if you always intend to override it?

I always intend to overwrite it *at development time*, I never intend to overwrite it *at runtime*, where we do `poetry install --only main` to avoid all the dev/test/docs/etc package groups.

---

Aha! Yes indeed, looks like close enough to be a dupe. Thanks for pointing me there!
