### ISSUE TITLE
Update package version specifier

### ISSUE THREAD

**Issue by chgad** [python-poetry/poetry#8890]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

I face the following situation:

I have django installed with the exact version specification `django = "4.1.13"` and want to update it to, let's say Version `django^5.0.0`.

In my understanding, I should not modify `pyproject.toml` by hand and therefor was looking for a command achieving this.

`poetry add django@^5.0.0` does not work and tries to install the new version alongside the old one.

`poetry update django@^5.0.0` also does not work.

Is my understanding wrong and i should modify the version specifier in the `pyproject.toml` or am I missing an important command?

**Comment by dimbleby** [comment]
> i noticed that i was using poetry 1.3.2 which might be the issue here.

the issue template is there for a reason...

please close this

**Comment by chgad** [comment]
As the template states i searched all ISSUES and did not find anything. Furthermore i searched the changelog and couldn't find
a change justifying an update of poetry itself, which i couldn't have done anyway due to other reasons.

> the issue template is there for a reason...
So no need for passive aggressiveness.

I modified the pyproject.toml and achieved what i wanted to do.
