### ISSUE TITLE
why is it so hard to find a basic sample pyproject.toml file i can use for my new project?

### ISSUE THREAD

**Issue by developer992** [python-poetry/poetry#8896]
How do you start? Create a new folder, create pyproject.toml file, add a few dependencies like django, so after i install it, i could use django-admin startproject ... 

Every time i try to find a basic sample pyproject.toml on google , i waste a lot of time

why isn't it here? https://python-poetry.org/docs/pyproject/

<!-
    Hi there! Thank you for helping improve our documentation!

    Before you submit your issue, please make sure you have completed the checklist below.
-->

- [ ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

**Comment by Secrus** [comment]
Check `poetry new` command. This should help you with your needs.

**Comment by couling** [comment]
`poetry new` is the first command introduced in the documentation under [Basic Usage](https://python-poetry.org/docs/basic-usage/)

**Comment by PedroH183** [comment]
You want a template basic for new projects or only create a new project with poetry ?

**Comment by abn** [comment]
Closing as this issue does not really meet any burden of information.
