### ISSUE TITLE
Cannot use file:/// with absolute path to specify a path dependency

### ISSUE THREAD

**Issue by harrandt** [python-poetry/poetry#8904]
Poetry (version 1.7.1)
Python 3.9
Windows 10

## Issue

According to [this pull request](https://github.com/python-poetry/poetry-core/pull/512) and the [documentation](https://python-poetry.org/docs/dependency-specification/#path-dependencies) it should be a possible to use `file:///` paths to specify a dependency like

```
[tool.poetry.dependencies]
my_package = { path = "file:///C:/wheelhouse/my_package-0.5.2-py3-none-any.whl" }
```

but in my case this does not work.

With `C:\my_project\pyproject.toml` and running the command `poetry install` in `C:\my_project` as the current working directory, I get the following error message:

`Path C:\my_project\wheelhouse\my_package-0.5.2-py3-none-any.whl for my_package does not exist`

Please notice that the current working directory is prepended to the path to the package with `C:` removed.

Is this something that should work in theory or are absolute paths not supported?

**Comment by harrandt** [comment]
Yet another question, I would like to have a feature like pip's find-links to be able to use a local folder as repo and I saw that there were many discussions about that.

Do you think it would be worth a shot to open up a pull request for something like

```
[[tool.poetry.source]]
name = "foo"
path = "file:///C:/wheelhouse/"
```

? It could just look at wheel files in the specified directory.

Or
```
[[tool.poetry.source]]
name = "foo"
url = "file:///C:/wheelhouse/index.html"
```
which would work without a webserver and contains relativ paths, e.g. created by [piprepo](https://pypi.org/project/piprepo/).

**Comment by dimbleby** [comment]
> According to https://github.com/python-poetry/poetry-core/pull/512 and the [documentation](https://python-poetry.org/docs/dependency-specification/#path-dependencies) it should be a possible to use file:/// paths to specify a dependency like

you've misunderstood the pull request: that's about how path dependencies are written in package metadata and not how they are specified in pyproject.toml

so far as I can see, the documentation you've linked to just doesn't say the thing that you say it says.  I find no mention of "file:///" under the path dependencies section at all.

ie there's no reason to expect what you're doing, just provide a regular path as per the documentation

please close

**Comment by harrandt** [comment]
Ok, thanks for the clarification.
