### ISSUE TITLE
Ignore dependency groups that do not exist on `--with` and `--without`.

### ISSUE THREAD

**Issue by eduardostalinho** [python-poetry/poetry#8906]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request

###Problem

I get the following error when running `poetry install` with `--with` option for a group that is not defined on my`pyproject.toml`:
```
poetry install --with invalidgroup

Group(s) not found: invalidgroup (via --with)
```
and with `--without`:
```
poetry install --without invalidgroup

Group(s) not found: invalidgroup (via --without)
```

Considering the case where I have 1 automation definition for 2 packages that I install with poetry and one package (package A) has the group `foobar` defined on `pyproject.toml` and the other (package B) doesn't, I'd like to ignore the dependency group on the automation for package A and reuse the definition for package B. This wouldn't work because of the error described above.

### Request
Invalid group names passed on `--with` and `--without` on `poetry install` should display a warning and proceed with the installation.

Example:
```
poetry install --with nogroup
Installing dependencies from lock file
Warning: group 'nogroup' not found. Please check if the group exists on your pytproject.toml or if it is a typo.

Package operations: 100 installs, 10 updates, 20 removals

  • Installing xxxx (x.x)
  ...
```

**Comment by radoering** [comment]
I do not think that is a path we want to take. Further, it's quite the opposite of  #7529. It's too easy to overlook a warning especially in CI so it's better to fail hard in case of a typo.
