### ISSUE TITLE
Installer should ask the user if the user want to add poetry to PATH like Conda

### ISSUE THREAD

**Issue by Lodimup** [python-poetry/poetry#8913]
## Feature Request
I teach python to devs with zero experiences. I tried to onboard poetry today just to find out that poetry does not add itself to path anymore. (because I develop in dev container it was not an issue there)

Installer should ask the user if the user want to add poetry to PATH automatically like what Conda does

This will speed up the adoptions. With current configuration it is not feasible to teach each, and every student to edit their config as each environment is vastly different, and knowing how to edit shell config is not required at early stage but proper package management is.

**Comment by clintonroy** [comment]
I really don't want programs modifying configuration files. If there was a well accepted drop in directory for this, then of course. ~/.local/bin/ is a well accepted per user binary directory for linux, is it the same for mac? Is there something similar for windows? What does pipx do on these other platforms?
