### ISSUE TITLE
Add support for alternative project config names - specifically, hidden names

### ISSUE THREAD

**Issue by oren-hecht** [python-poetry/poetry#8918]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request
I propose *adding* support for local configuration files with hidden names - for example
`.poetry.toml`
`.poetry.lock`
`.pyproject.toml`

The purpose is for aesthetic purposes, but also for conformity with the way most common tools work.

To explain my motivation, here is an example from a git repo I work on:

![image](https://github.com/python-poetry/poetry/assets/112331674/2724a2de-3d91-4d67-b8e0-d47e87704f79)

you can see that in the top-level directory, there are a plethora of config and settings files, used for many common development tools - pre-commit, vscode, venv, git, mypy, etc.. these can all be see when running `ls -lah`. However, when running `ls`, I would hope to not see these config files, and to only see my project directories and files. Currently, the only settings files visible on `ls` are the poetry ones..

As we see, It is exceedingly common to support several different file names, especially "hidden" filename syntax. So my feature suggestion is to support several file names option - this can be done similarly to other open source projects, with a hierarchy of options, so as not to break backwards compatibility:
![image](https://github.com/python-poetry/poetry/assets/112331674/4054682b-ec93-4c91-8d88-7d9e508cea1f)

**Comment by dimbleby** [comment]
None of `poetry.toml`, `.poetry.lock`, `.pyproject.toml` belong in your home directory, they are not general poetry configuration but relate to the _project_.

`pyproject.toml` in particular is defined by various standards, it is definitely a bad idea for poetry to decide to use a file with a different name.

pretty sure this is going to be thanks-but-no-thanks

**Comment by oren-hecht** [comment]
I edited my original message for clarity - as can be seen, I was not talking about my computer's home directory, but the top-level directory of some project that uses poetry. So maybe there was some confusion here - the relevant config files, are the *local* configuration files, that are specific to a project.

Additionally, I can accept that changing the name of `pyproject.toml` may be problematic. perhaps at some point, the local configuration file will have an option to manually assign some path to the file, so it doesn't need to clutter the top level directory. However - the two other project files can still easily support alternate naming schemes.

**Comment by Secrus** [comment]
I would say that we could make this possible for `poetry.toml`, but `poetry.lock` and `pyproject.toml` won't change. If you want this change to happen, the best way would be to submit a pull request.

**Comment by dimbleby** [comment]
fwiw my vote would still be that it is unnecessary complexity to support more than one configuration file

**Comment by abn** [comment]
I agree with @dimbleby that this is added code complexity for not very much return. The `poetry.toml` (per project) configuration is not something I have seen widely used for starters. Additionally, the ambiguity of having the file in multiple possible locations is not of a lot of use imho.

While I am not really sure if there is a reason why `poetry.toml` needs to be distributed with your project (eg: git, wheel) as it is intended for the development environment, if you reckon there is please raise a discussion discussing possible proposals and once you have consensus provide a pull request for review.
