### ISSUE TITLE
Wrong version installed when using PEP 440 version epochs

### ISSUE THREAD

**Issue by jacebrowning** [python-poetry/poetry#892]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS 10.14.3
- **Poetry version**: 0.12.11
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: N/A

## Issue

`1!2019.2.12` is requested but `1!2015.2.1` is installed:
```
$ poetry new demo
$ cd demo
$ poetry add "foursquare==1\!2019.2.12"
Creating virtualenv demo-py3.7 in /private/tmp/demo/.venv

Updating dependencies
Resolving dependencies... (0.2s)
Package operations: 13 installs, 0 updates, 0 removals

Writing lock file

  - Installing certifi (2018.11.29)
  ...
  - Installing foursquare (1!2015.2.1)
  ...
```

I see code that seems to support this, but no tests: https://github.com/sdispater/poetry/search?q=epoch&unscoped_q=epoch

**Comment by jacebrowning** [comment]
I believe this issue is still valid and should be treated as a bug.

**Comment by JBKahn** [comment]
The semver Version doesn't support it, but the version Version parser does. It seems a bit strange to have two different parsers, I think if the semver Parser only parsed the constraint out but not the versions that could work? @sdispater how do you think this should be structured?
