### ISSUE TITLE
Unable to install multiple branches of the same repository

### ISSUE THREAD

**Issue by juanjomendezhealios** [python-poetry/poetry#8932]
- **Poetry version**: 1.7.1 
- **Python version**: 3.9 
- **OS version and name**: MacOS Ventura 13.4 - Apple M1 
- **pyproject.toml**: See further in the issue. 

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a [recommended method](https://python-poetry.org/docs/#installation).
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

Poetry is not able to install multiple branches of the same git repository. Sometimes install all the branches but sometimes only install a couple. 

### Example
I have a repository called **repo.scripts** which has three different branches called _**scripts_v1**_, _**scripts_v2**_, _**scripts_v3**_. I want all the branches to be installed in another repository using poetry command. This new repository is called **repo.interface**, and it consist on a Flask service which has different endpoints for each version defined in the **repo.scripts** (each branch is a different version).

Each branch within the **repo.scripts** have the following structure:

- branch scripts_v1:
├── scripts_v1
│   ├── functions.py
│   ├── __init__.py
├── pyproject.toml
└── .gitignore

- branch_scripts_v2:
├── scripts_v2
│   ├── functions.py
│   ├── __init__.py
├── pyproject.toml
└── .gitignore

- branch_scripts_v3:
├── scripts_v3
│   ├── functions.py
│   ├── __init__.py
├── pyproject.toml
└── .gitignore

Once the different branches are pushed to the repository and in the **repo.interface**, the **_pyproject.toml_** file looks like this:

`
[tool.poetry]
name = "repo.interface"
version = "1.0"
description = "Interface"
authors = ["author <email>"]

[tool.poetry.dependencies]
python = ">=3.9,<3.10"
Flask = "2.2"
grpcio = "^1.60.0"
grpcio-tools = "^1.60.0"
Werkzeug = "2.2.2"
gunicorn = "^21.2.0"
envyaml = "^1.10.211231"

scripts_v1 = { git = "ssh://git@bitbucket.org/repo.scripts.git", branch = "scripts_v1" }
scripts_v2 = { git = "ssh://git@bitbucket.org/repo.scripts.git", branch = "scripts_v2" }
scripts_v3 = { git = "ssh://git@bitbucket.org/repo.scripts.git", branch = "scripts_v3" }

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
`

After I run the command `poetry install --no-cache` in the prompt appears that all the modules have been installed, but if I enter to the environment and see the packages installed, not all the modules were installed. Sometimes it installs two branches and sometimes it installs all of them. Furthermore, if I take a look at the **poetry.lock** file, all the branches should be installed, but they are not.

I'm worried that once this repo.interface goes to a production environment not all the modules are installed and therefore, not all the endpoints are working.

I have tried to set the config variable `installer.parallel = false` to try to install each branch one by one, I do not mind the time spent to install the dependencies but that all the modules are correctly installed. 

I'm new to poetry so maybe I'm missing something 😅 . Is there a way to ensure that all modules are installed?

Thank in advance 😄

**Comment by dimbleby** [comment]
roughly duplicate #6958, #8635

but your particular variation is kinda nuts!  installing three different packages from different branches of the same project is bizarre, you want three separate repositories.

**Comment by juanjomendezhealios** [comment]
@dimbleby thanks for your fast response. 

Although, theoretically, it has to be possible. In production environment is not only one repository which has multiple branches, but multiple repositories with at least two branches that are needed in the interface. 

Is there a way to install all of them without creating different repositories?

I have observed that when I try to install all the repositories with all the branches, there are some repositories that are not even installed, but the prompt of the `poetry install --vvv` shows that all is being installed, but they are not 😅 .

**Comment by dimbleby** [comment]
rearrange your repositories so that all of the things you want to support in production are supported from one production branch?

so far as poetry goes I dont think this is adding anything over the linked issues: multiple things from the same git repository is long known to be problematic

**Comment by radoering** [comment]
Closing as

> roughly duplicate https://github.com/python-poetry/poetry/issues/6958, https://github.com/python-poetry/poetry/issues/8635
