### ISSUE TITLE
Unable to run poetry add a repo git

### ISSUE THREAD

**Issue by ngo-minh-thang-nguyen** [python-poetry/poetry#8933]
- **Poetry version**: 1.7.1
- **Python version**: 3.10.11
- **OS version and name**: Windows
- **pyproject.toml**: 

- [ x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a [recommended method](https://python-poetry.org/docs/#installation).
- [x ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [ x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

Hello,

I execute the cli 
poetry add git+https://github.com/sdispater/pendulum.git -vvv 
as shown in the documentation of https://python-poetry.org/docs/cli/#add.

However, I got the following error
![image](https://github.com/python-poetry/poetry/assets/12558275/f24b2573-b4f5-4753-bbe1-b47f5188a488)

Could you please help me to review the error to determine if it is really a bug or a bad configuration?

Thank you for your reply.

**Comment by dimbleby** [comment]
per the stack this is a virtualenv bug, not something that this repository can help with

specifically it looks like a duplicate of https://github.com/pypa/virtualenv/issues/2589

**Comment by ngo-minh-thang-nguyen** [comment]
I can do what I want, so I close the topic. Thank you @dimbleby
