### ISSUE TITLE
how to share large packages between projects/environments?

### ISSUE THREAD

**Issue by fancyerii** [python-poetry/poetry#8938]
I have many projects with shared large packages such as pytorch(4G+). Every time I create a new project I need to install it. It wastes time and disk space. Is there any way to share these large packages like maven(java) or docker.

Java's maven is project based-- it manage each projects indenpendently. But all the dependents(jars) are stored centrally in .m2. So If project A and project B share exactly the same version of a lib, There is only one copy of this jar file.

I tried and searched many python package manager tools: pip,conda,pipenv,poetry,PDM. No of them has this features. A similar issue can be found [here](https://github.com/pypa/packaging-problems/issues/328). But I can't find solution there.

**Comment by dimbleby** [comment]
I thought pdm did do something like this; but otherwise your research sounds right to me.  Certainly poetry doesn't.

Please close.

**Comment by fancyerii** [comment]
pdm has this feature. I will try it.
