### ISSUE TITLE
Generate a README.md when using poetry init

### ISSUE THREAD

**Issue by Heus-Sueh** [python-poetry/poetry#8943]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request

generate a generic or empty readme.md file at the end of poetry init, this will prevent the user from encountering an error due to the lack of readme.md when using `poetry install`

example:

```
{project_name}
============

**This app was generated by `Poetry`**

{description_of_project}

.. _`Poetry`: https://python-poetry.org/

```

**Comment by dimbleby** [comment]
```console
$ poetry init --help                                                          
Description:
  Creates a basic pyproject.toml file in the current directory.
```
sounds like you want `poetry new`

**Comment by Heus-Sueh** [comment]
> ```
> $ poetry init --help                                                          
> Description:
>   Creates a basic pyproject.toml file in the current directory.
> ```
> 
> sounds like you want `poetry new`

the `new` command does this automatically, I know, but `init` should do the same thing when you finish filling in the information or at least be optional

**Comment by dimbleby** [comment]
`poetry init` is very clear that it is intended to create `pyproject.toml` and `poetry new` is very clear that it is intended to create a new project.

if you want to create more than only `pyproject.toml`, then you want `poetry new`.  

I might agree that having both of these commands is confusing: but that is not what you are reporting.  (I am fairly sure that there are other issues saying that!)  However: in a world where `poetry new` and `poetry init` both exist - this is working as designed.

**Comment by Heus-Sueh** [comment]
> `poetry init` is very clear that it is intended to create `pyproject.toml` and `poetry new` is very clear that it is intended to create a new project.
> 
> if you want to create more than only `pyproject.toml`, then you want `poetry new`.
> 
> I might agree that having both of these commands is confusing: but that is not what you are reporting. (I am fairly sure that there are other issues saying that!) However: in a world where `poetry new` and `poetry init` both exist - this is working as designed.

For me, `poetry init` would be to initialize a new project, but as you explained in the docs it says that it only generates a `pyproject.toml`, a very strange design choice.

I would close this issue, but I'll wait for others to give their opinions here

**Comment by AllanHOlesenBW** [comment]
> I might agree that having both of these commands is confusing: but that is not what you are reporting. (I am fairly sure that there are other issues saying that!) However: in a world where `poetry new` and `poetry init` both exist - this is working as designed.

That world comes with a paradox:

1. `poetry new` and `poetry init` are mutually exclusive
2. `poetry new` and `poetry init` are both needed to get the total job done

Re 1:
I cannot first run `poetry new` and then `poetry init`.
I also cannot first run `poetry init` and then `poetry new .`.
As soon as I have run one of them, it is game over.

Re 2:
Both these commands have their limitations, which could go away if they were either combined into one command or at least allowed to be run after each other:
`poetry init` will not create a directory structure or a README.
`poetry new` does not offer interactive fill in of pyproject.toml

(Actually, `poetry new .` is so stubborn that it even refuses to run after a `git init`, but that is probably a topic of its own.)
