### ISSUE TITLE
Configuring credentials for private repositories

### ISSUE THREAD

**Issue by AdrianSchneble** [python-poetry/poetry#8959]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

The current documentation on authentication for private repositories ([web link](https://python-poetry.org/docs/repositories/), [source code](https://github.com/python-poetry/poetry/blob/3e98fd8f7c46ccf5d549c3c87cb331ba8a164101/docs/repositories.md)) states that "Depending on your system configuration, credentials might be saved in your command line history".

This is an important disclaimer, as you should generally never type credentials into the terminal prompt itself. However, the only suggested solution is prefixing your command with a space, which does not work for me in the shells I tested (on both Windows and Unix).

There is, however, a much simpler way: just run `poetry config http-basic.foo <username>`, i.e. don't enter the password, and you will be prompted for it with an "invisible" password prompt, which does not show up in the shell history, nor anywhere else as far as I understand (tested on Windows powershell with poetry version 1.7.1).

Should be a pretty trivial fix if you're set up for contributing to this repository, but I don't really want to go through the trouble to set that up - hence this issue.

**Comment by dimbleby** [comment]
issue reports that say they wish someone else would write better docs have a low probability of achieving anything.

please submit a merge request
