### ISSUE TITLE
Pip install editable poetry package fails on conflicting package version, although the exact same version is required

### ISSUE THREAD

**Issue by galCohen88** [python-poetry/poetry#8964]
- **Poetry version**: poetry --version Poetry (version 1.7.1)
- **Python version**: Python: 3.10.0
- **OS version and name**: Mac Os Sonoma 14.2.1 
- **pyproject.toml**: https://gist.github.com/galCohen88/904cf34a15f452637404108308294cc5

- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a [recommended method](https://python-poetry.org/docs/#installation).
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

Pip version resolver fails when installing Poetry package in editable mode if package is required both by TOML file & requirements.txt file:

```
INFO: pip is looking at multiple versions of first-library to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install -r sim_requirements.txt (line 1) and second-library 0.1.0 (from libs/second_library) because these package versions have conflicting dependencies.
```

Example: 

Folder structure
```
requirements.txt
libs/first_library
libs/second_library
```

requirements.txt content
```
-e ./libs/first_library
-e ./libs/second_library
```

first_library pyproject.toml dependencies
```
[tool.poetry.dependencies]
python = "^3.9"
second-library = {path = "../second_library", develop = true}
```

Full error log
```
INFO: pip is looking at multiple versions of first-library to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install -r sim_requirements.txt (line 1) and second-library 0.1.0 (from libs/second_library) because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested second-library 0.1.0 (from libs/second_library)
    first-library 0.1.0 depends on second-library 0.1.0 (from libs/second_library)

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
```

**Comment by dimbleby** [comment]
wrong project, you are reporting pip errors

**Comment by galCohen88** [comment]
Created an issue in Pip repo
https://github.com/pypa/pip/issues/12520
