### ISSUE TITLE
Poetry to manage pip-installed packages in requirements file

### ISSUE THREAD

**Issue by leweex95** [python-poetry/poetry#8969]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

I am setting up poetry for a complex project which relies on a couple of obsolete packages which do not yet conform to PEP517. Therefore, the only current way to install those packages is via pip. 

I would like to ask whether poetry is able to handle such scenarios. In other words, is it possible to separate dependencies in the pyproject.toml depending on whether they are installable via poetry or via pip?

**Comment by Secrus** [comment]
No, this is not possible and (since PEP 517 is the standard now) won't be added to Poetry. 

Side note: you could build those dependencies to wheels that you include in your project tree and add them as path dependencies.
