### ISSUE TITLE
Auto-add stubs to dev dependencies

### ISSUE THREAD

**Issue by YUKI2eN3e** [python-poetry/poetry#8972]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request

So I'm not sure if this is technically a feature request for poetry or not, but this seemed like a good place to ask.
Would it be possible to (either via a plugin or internally) have poetry automatically detect and add stub packages into `[tool.poetry.group.dev.dependencies]`  when `mypy` (or any other typechecker) has be manually added to the project?

Curentry I use a `justfile` with
  ```makefile
  @poetry install
  @(just mypy 2> /dev/null ; yes | poetry run mypy --install-types)
  ```
as part of the `setup` task but it would obviously be much tidier to just have all the stubs in `[tool.poetry.group.dev.dependencies]` from the start and just run `poetry install`.

Thanks.

**Comment by dimbleby** [comment]
this is not something that would belong in poetry itself, if you want to implement this through a plugin then of course that's up to you!

**Comment by Secrus** [comment]
That sounds oddly specific and won't be a part of Poetry, as suggested, you can make a plugin for that.

**Comment by YUKI2eN3e** [comment]
Ok, I'll look into that.
Could I ask where would be a good spot to look for plugin documentation.
