### ISSUE TITLE
Problem installing wheel that depends on a custom repository

### ISSUE THREAD

**Issue by FleischmanRaul** [python-poetry/poetry#8973]
- **Poetry version**: 1.7.1
- **Python version**: 3.12.1
- **OS version and name**: MacOs 14.2.1

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a [recommended method](https://python-poetry.org/docs/#installation).
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
**Problem installing wheel that depends on a custom repository**

I have a package _my-package_ that requires a supplemental source that points to a non pypi URL. The following is in the pyproject.toml file:

```
[tool.poetry.dependencies]
...
my_other_package = {version = ">1.0.0", source = "custom"}

[[tool.poetry.source]]
name = "custom"
url = "https://url/simple"
priority = "supplemental"   # I also tried different types of priorities, with no success
```

I am able to **install** and **build** the package without any errors. The lib (_my_other_package_) from the custom repo is downloaded as expected.

However, when I try to pip install the generated wheel package, it fails with:

> ERROR: Could not find a version that satisfies the requirement _my_other_package_>1.0.0 (from _my-package_) (from versions: none)

> ERROR: No matching distribution found for _my_other_package_>1.0.0

**Comment by dimbleby** [comment]
if you want to use pip to install a package you will need to tell pip about the private repository using pip-specific mechanisms

there is nothing poetry can do for you here, please close

**Comment by FleischmanRaul** [comment]
Maybe I am missing something but isn't there a way to include my repo sources into the metadata?

**Comment by FleischmanRaul** [comment]
understandable, have a nice day
