### ISSUE TITLE
Improve error message to EmptyTableNameError

### ISSUE THREAD

**Issue by biofsphere** [python-poetry/poetry#8980]
- **Poetry version**: 1.7.1
- **Python version**: 3.11.5
- **OS version and name**: win32 nt
- **pyproject.toml**: (https://gist.github.com/biofsphere/89895e6ff22f01cc7ce63100d9fc5ede)

- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a [recommended method](https://python-poetry.org/docs/#installation).
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue (suggestion)
While adding packages, I run into an EmptyTableNameError message **Empty table name at line 1 col 19**. I spent a whole afternoon searching for a solution. It was only when I decided to open this issue that, by testing and retesting my shell commands I realized what was going on. This did not happen to most packages I installed, but it did to django-debug-toolbar and ipython. I went off to search communalities between both packages and tried to understand **poetry debug info --verbose output**, digging something for quite a while. When I gave up and decided to make a gist and open a new issue, voala!! I noticed I run **poetry add django-debug-toolbar --group==local**... ...yes, with double equal signs!!!! 

I am just sharing this so you know the error message threw me way off the mark, for a mere misspelling mistake. If you could improve the EmptyTableNameError message to alert beginners with something like "Check your spelling" or something, that would have me saved hours!. My bad. Checking spelling is pretty basic and I did for letter, but missing the double equal signs was such a bummer.

Anyway, just a quick note. I am really enjoying this package manager. I don't think I will ever get back to pip alone again.

**Comment by dimbleby** [comment]
should be fixable just by putting quote marks around `{group}` at [this line](https://github.com/python-poetry/poetry/blob/48a76fd1e27a7e329b8987407c409ee3eb28347c/src/poetry/console/commands/add.py#L139) - pull request welcome, I'm sure.
