### ISSUE TITLE
How to uninstall an editable package

### ISSUE THREAD

**Issue by newyorker123** [python-poetry/poetry#8983]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

I installed a local project with `poetry install`, and I realized it's in editable mode. Now I want to uninstall it. I tried `poetry remove <pkg>`, but I got `The following packages were not found: <pkg>`.

I can see this package in `conda list`, but it's not shown when I run `poetry show`.

I'm not sure if this is normal behavior or if my installation is corrupted. How should I uninstall the package?

**Comment by newyorker123** [comment]
@dimbleby Thank you for your quick reply. However, I'm not trying to remove a dependency; I'm trying to remove the project itself. Additionally, I'm not trying to undo `poetry add`; I'm trying to undo `poetry install`. So my question is, what's the official command to undo `poetry install`, which ends up as an editable package?

I've tried deleting the environment and starting over, but it's still the same. So I guess a simple `poetry remove` is not the command for the job?

**Comment by dimbleby** [comment]
`poetry remove` is to undo `poetry add`

just delete the environment if you don't want it any more.
