### ISSUE TITLE
Question on Using Poetry with Pyenv

### ISSUE THREAD

**Issue by junrae6454** [python-poetry/poetry#8989]
- **Poetry version**: Poetry (version 1.7.1)
- **Python version**: 
```
Poetry
Version: 1.7.1
Python:  3.10.13

Virtualenv
Python:         3.9.16
Implementation: CPython
Path:           /home/user/.cache/pypoetry/virtualenvs/cleaner-LFdLDTV--py3.9
Executable:     /home/user/.cache/pypoetry/virtualenvs/cleaner-LFdLDTV--py3.9/bin/python
Valid:          True

System
Platform:   linux
OS:         posix
Python:     3.9.16
Path:       /home/user/.pyenv/versions/3.9.16
Executable: /home/user/.pyenv/versions/3.9.16/bin/python3.9
```
- **OS version and name**: Ubuntu 22.04
- **pyproject.toml**: 

- [ ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a [recommended method](https://python-poetry.org/docs/#installation).
- [ ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
Hello, I'm a newcomer interested in Poetry after using pyenv and pyenv-virtualenv. 
I've been utilizing pyenv + virtualenv in zsh to install Python 3.9 and 3.10, and I have set the global Python version to 3.10. 
After creating a project and fixing its Python version to 3.9.x, I specify the project's Python version with pyenv local 3.9.16. 
Then, I activate the Poetry virtualenv using poetry shell.

During this process, it seems like Poetry loses priority to virtualenv, and the VIRTUAL_ENV gets set to ~/.pyenv/versions/xxxx.

Is there a way to use both packages simultaneously without this issue?

```shell
$ poetry run env | grep VIRTUAL_ENV
VIRTUAL_ENV=/home/user/.cache/pypoetry/virtualenvs/cleaner-LFdLDTV--py3.9

$ poetry shell
$ env | grep VIRTUAL_ENV <- no print
```

**Comment by dimbleby** [comment]
your issue report seems inconsistent: "the VIRTUAL_ENV gets set to ~/.pyenv/versions/xxxx." is not what either of your commands shows?

I mostly anti-recommend `poetry shell` - just activate your environment some other way - but for what it's worth I do not see any inconsistency when I try it locally.  

A docker-ised reproduction is always a good way of showing something to someone so that it happens not only on your machine.

**Comment by junrae6454** [comment]
@dimbleby Thanks for the reply. 
When executing the "poetry shell" command, it's expected that pip and python would use the paths designated by poetry, specifically "/home/user/.cache/pypoetry/virtualenvs/cleaner-LFdLDTV--py3.9/bin/". 
However, after activating the poetry shell, using python actually utilizes "~/.pyenv/versions/my_3.9.16/bin/python" instead. 
On the other hand, using the command "poetry run python" correctly used "/home/user/.cache/pypoetry/virtualenvs/cleaner-LFdLDTV--py3.9/bin/python" as intended.

How to make shell to use "/home/user/.cache/pypoetry/virtualenvs/cleaner-LFdLDTV--py3.9/bin/python" after "poetry shell"?

**Comment by dimbleby** [comment]
I can only reiterate: when I do it I get no inconsistency - and suggest producing a docker repro

Either you will find not so easy to do, in which case you likely learn something about what is different on your machine.  Or you will find it easy to do and then it will be possible for other people to help you

**Comment by junrae6454** [comment]
@dimbleby Here is test Dockerfile
Thanks for your attention.

```Dockerfile
FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update; apt install -y build-essential libssl-dev zlib1g-dev \
    libbz2-dev libreadline-dev libsqlite3-dev curl \
    libncursesw5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev \
    git zsh vim

workdir /root
RUN chsh -s $(which zsh)
RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
RUN git clone https://github.com/pyenv/pyenv.git ~/.pyenv

ENV HOME  /root
ENV PYENV_ROOT $HOME/.pyenv
ENV PATH $PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH

RUN echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.zshrc
RUN echo 'command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.zshrc
RUN echo 'eval "$(pyenv init -)"' >> ~/.zshrc
RUN echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.zprofile
RUN echo 'command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.zprofile
RUN echo 'eval "$(pyenv init -)"' >> ~/.zprofile

RUN git clone https://github.com/pyenv/pyenv-virtualenv.git $(pyenv root)/plugins/pyenv-virtualenv
RUN echo 'eval "$(pyenv virtualenv-init -)"' >> ~/.zshrc

RUN pyenv install 3.10.5
RUN pyenv virtualenv 3.10.5 my3.10.5
RUN pyenv install 3.9.16
RUN pyenv global my3.10.5

RUN curl -sSL https://install.python-poetry.org | python3 -

RUN echo 'export PATH="/root/.local/bin:${PATH}"' >> ~/.zshrc

CMD ["/bin/zsh"]
```

## docker build
```bash
docker build -t pyenv -f ./Dockerfile .
```

## docker run
```bash
docker run -it -d --name pyenv pyenv zsh && docker exec -it pyenv zsh
```

## inside docker
```bash
 docker exec -it pyenv zsh
(my3.10.5) ➜  ~ pyenv versions
  3.9.16
  3.10.5
  3.10.5/envs/my3.10.5
* my3.10.5 --> /root/.pyenv/versions/3.10.5/envs/my3.10.5 (set by /root/.pyenv/version)
(my3.10.5) ➜  ~ mkdir package
(my3.10.5) ➜  ~ cd package
(my3.10.5) ➜  package poetry init

This command will guide you through creating your pyproject.toml config.

Package name [package]:
Version [0.1.0]:
Description []:
Author [None, n to skip]:  n
License []:
Compatible Python versions [^3.10]:  ^3.9

Would you like to define your main dependencies interactively? (yes/no) [yes]
You can specify a package in the following forms:
  - A single name (requests): this will search for matches on PyPI
  - A name and a constraint (requests@^2.23.0)
  - A git url (git+https://github.com/python-poetry/poetry.git)
  - A git url with a revision (git+https://github.com/python-poetry/poetry.git#develop)
  - A file path (../my-package/my-package.whl)
  - A directory (../my-package/)
  - A url (https://example.com/packages/my-package-0.1.0.tar.gz)

Package to add or search for (leave blank to skip):

Would you like to define your development dependencies interactively? (yes/no) [yes]
Package to add or search for (leave blank to skip):

Generated file

[tool.poetry]
name = "package"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


Do you confirm generation? (yes/no) [yes]
(my3.10.5) ➜  package poetry shell
Spawning shell within /root/.pyenv/versions/3.10.5/envs/my3.10.5
➜  package emulate bash -c '. /root/.pyenv/versions/3.10.5/envs/my3.10.5/bin/activate'
(my3.10.5) ➜  package which pip
/root/.pyenv/versions/3.10.5/envs/my3.10.5/bin/pip
(my3.10.5) ➜  package which python
/root/.pyenv/versions/3.10.5/envs/my3.10.5/bin/python
(my3.10.5) ➜  package poetry env use /root/.pyenv/versions/3.9.16/bin/python
Creating virtualenv package-7fxUQVQT-py3.9 in /root/.cache/pypoetry/virtualenvs
Using virtualenv: /root/.cache/pypoetry/virtualenvs/package-7fxUQVQT-py3.9
(my3.10.5) ➜  package
(my3.10.5) ➜  package poetry shell
Spawning shell within /root/.cache/pypoetry/virtualenvs/package-7fxUQVQT-py3.9
➜  package emulate bash -c '. /root/.cache/pypoetry/virtualenvs/package-7fxUQVQT-py3.9/bin/activate'
(my3.10.5) ➜  package which pip
/root/.pyenv/shims/pip
(my3.10.5) ➜  package pip -V
pip 22.0.4 from /root/.pyenv/versions/3.10.5/envs/my3.10.5/lib/python3.10/site-packages/pip (python 3.10)
(my3.10.5) ➜  package
```

**Comment by dimbleby** [comment]
Creating new environments from inside a poetry shell, and then trying to nest poetry shells... I am not surprised that this goes badly.

When you want to create a new environment, first exit the sub-shell.

Alternatively - as I say, I mostly anti-recommend poetry shell altogether.

**Comment by junrae6454** [comment]
@dimbleby
I'm still unsure about what the issue is and what solutions I should consider. 
Could you please provide more details?


### log again. I try to activate with poetry shell but doesn't work.
```bash
(my3.10.5) ➜  package poetry shell
Spawning shell within /root/.pyenv/versions/3.10.5/envs/my3.10.5
➜  package emulate bash -c '. /root/.pyenv/versions/3.10.5/envs/my3.10.5/bin/activate'
(my3.10.5) ➜  package which pip
/root/.pyenv/versions/3.10.5/envs/my3.10.5/bin/pip
(my3.10.5) ➜  package which python
/root/.pyenv/versions/3.10.5/envs/my3.10.5/bin/python
```

### The only way I found how to do this
https://github.com/python-poetry/poetry/issues/6012#issuecomment-1184837718
```bash
alias poetry_activate='source "$( poetry env info --path )/bin/activate"'
```
source activate script.

**Comment by dimbleby** [comment]
when I try it I find that even sourcing the venv activate script does not have the expected effect.  Which might or might not help you, but does seem to make this nothing much to do with poetry:
```console
(my3.10.5) ➜  package source /root/.cache/pypoetry/virtualenvs/package-7fxUQVQT-py3.9/bin/activate
(my3.10.5) ➜  package echo $PATH
/root/.local/bin:/root/.pyenv/plugins/pyenv-virtualenv/shims:/root/.pyenv/shims:/root/.pyenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```
nb path does not include the venv bin directory

**Comment by junrae6454** [comment]
@dimbleby 
You are right.
The docker environment seems different with my real environment.
Sorry to bother you.

Here is my real environment shell outputs.
Can you suggest me what should I do?

```bash
$ cd test

$ pyenv versions
  system
* 3.9.16 (set by /home/user/test/.python-version)
  3.11.8
  3.11.8/envs/py311
  py311 --> /home/user/.pyenv/versions/3.11.8/envs/py311

$ which python
/home/user/.pyenv/shims/python

$ echo $SHLVL
1

$ poetry shell
Spawning shell within /home/user/.cache/pypoetry/virtualenvs/test-PTiydL1D-py3.11

$ which python
/home/user/.pyenv/shims/python

$ echo $SHLVL
2

$ echo $PATH
/home/user/.local/bin:/home/user/.local/bin:/home/user/.asdf/shims:/home/user/.asdf/bin:/home/user/.pyenv/plugins/pyenv-virtualenv/shims:/home/user/.pyenv/shims:/home/user/.pyenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/user/.local/bin:/home/user/.fzf/bin

$ exit

$ echo $PATH
/home/user/.local/bin:/home/user/.asdf/shims:/home/user/.asdf/bin:/home/user/.pyenv/plugins/pyenv-virtualenv/shims:/home/user/.pyenv/shims:/home/user/.pyenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/user/.local/bin:/home/user/.fzf/bin

$ source `poetry env info -p`/bin/activate
/home/user/.cache/pypoetry/virtualenvs/test-PTiydL1D-py3.11

$ which python
/home/user/.cache/pypoetry/virtualenvs/test-PTiydL1D-py3.11/bin/python

$ echo $SHLVL
1

$ echo $PATH
/home/user/.cache/pypoetry/virtualenvs/test-PTiydL1D-py3.11/bin:/home/user/.local/bin:/home/user/.asdf/shims:/home/user/.asdf/bin:/home/user/.pyenv/plugins/pyenv-virtualenv/shims:/home/user/.pyenv/shims:/home/user/.pyenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/user/.local/bin:/home/user/.fzf/bin

```

If you still don't know what is wrong with me, I will try to rebuild Dockerfile again.

**Comment by junrae6454** [comment]
I've found the cause of the issue. 
When logging into zsh for the first time, several functions are sourced from ~/.zshrc. 
It appears that when reopening zsh through poetry shell, some of these functions are causing conflicts.

Thanks @dimbleby

**Comment by junrae6454** [comment]
To detail

```bash
# in ~/.zshrc
source clean_wgetrc.sh

clean_wgetrc
```

```bash
# in clean_wgetrc.sh
function clean_wgetrc
{
  sudo sed -i '/http_proxy/ d' ~/.wgetrc
}
```
