### ISSUE TITLE
`poetry search` does not search additional repositories

### ISSUE THREAD

**Issue by Popkornium18** [python-poetry/poetry#8990]
I have added a private Python repository:

```
poetry config repositories
{'artifactory': {'url': 'https://somehost.example.com/artifactory/api/pypi/somerepo/simple'}}
```

I am able to install dependencies from this repository that are not on PyPI. However when I run `poetry search some_private_library` poetry will only return search results from PyPI.

- **Poetry version**: Poetry (version 1.7.1)
- **Python version**: Python:  3.10.12
- **OS version and name**: Ubuntu 22.04
- **pyproject.toml**:

**Comment by dimbleby** [comment]
duplicate #2446
