### ISSUE TITLE
add uv support

### ISSUE THREAD

**Issue by bruceunx** [python-poetry/poetry#8995]
Do you have any plan to use uv to replace pip as installer?

**Comment by dimbleby** [comment]
pip is already not the installer.  

if uv - or anyone else - were to release a better https://github.com/pypa/installer then I could imagine poetry might accept a merge request to use that, but as I understand it they are a long way off declaring stable APIs anywhere other than their command line

also please first search for duplicates, #8978 

please close

**Comment by jorenham** [comment]
But wouldn't it be possible to use `uv` instead of `installer`?
