### ISSUE TITLE
Poetry evaluates `platform_python_implementation` marker incorrectly

### ISSUE THREAD

**Issue by ioannis-balo** [python-poetry/poetry#8996]
- **Poetry version**: 1.7.1
- **Python version**: 3.11.7
- **OS version and name**: macOS 14.3
- **pyproject.toml**: https://gist.github.com/ioannis-balo/54ef5e13090d4e0eecdcd3f9fee5e1f3

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a [recommended method](https://python-poetry.org/docs/#installation).
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
In an empty project, I am trying to install `vcrpy` using `poetry add vcrpy`. It is correctly installing the latest version (6.0.1).
However, in the package's dependencies, `urllib3` is constrained by the `implementation` marker:
```
[package.dependencies]
PyYAML = "*"
urllib3 = {version = "<2", markers = "platform_python_implementation == \"PyPy\""}
wrapt = "*"
yarl = "*"
```
and indeed, `urllib3` version installed is <2:
```
[[package]]
name = "urllib3"
version = "1.26.18"
```

My python implementation is
```
>>> platform.python_implementation()
'CPython'
```

`vcrpy` setup.py https://github.com/kevin1024/vcrpy/blob/v6.0.1/setup.py#L45-L58

I would expect `urllib3` to not be installed based on the markers and my environment.

**Comment by dimbleby** [comment]
does not reproduce:
```
$ poetry add --lock vcrpy
Using version ^6.0.1 for vcrpy

Updating dependencies
Resolving dependencies... (0.8s)

Writing lock file
(foo) dch@DESKTOP-NA4O3IV:~/foo$ poetry install --dry-run
Installing dependencies from lock file

Package operations: 6 installs, 0 updates, 0 removals

  • Installing idna (3.6)
  • Installing multidict (6.0.5)
  • Installing pyyaml (6.0.1)
  • Installing wrapt (1.16.0)
  • Installing yarl (1.9.4)
  • Installing vcrpy (6.0.1)

Installing the current project: foo (0.1.0)
```
please provide a way to reproduce, else close

**Comment by dimbleby** [comment]
poetry builds cross platform lockfiles, it is correct to write the dependency to the lockfile so that the lockfile will be valid if someone tries to install your project using PyPy.

what you said was

> I would expect urllib3 to not be installed based on the markers and my environment.

which is exactly what happens

Please close.

**Comment by dimbleby** [comment]
> Am I missing something?

yes, your pyproject.toml requires python at least 3.10, so the marker for python less than 3.10 is irrelevant

> So that does seem like a bug to me

this is not a bug, if poetry allowed you to install urllib3 2.0 then your project would be broken when running on pypy

**Comment by hartwork** [comment]
Hi @dimbleby,

> > Am I missing something?
> 
> yes, your pyproject.toml requires python at least 3.10, so the marker for python less than 3.10 is irrelevant

I confirm, I get line…

```
urllib3 = {version = "<2", markers = "platform_python_implementation == \"PyPy\" or python_version < \"3.10\""}
                                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

…once I retry with CPython 3.*9*.
