### ISSUE TITLE
Feature: Add "start" Command

### ISSUE THREAD

**Issue by BearingMe** [python-poetry/poetry#9013]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Description:
The current behavior of using `poetry run python script.py` can sometimes feel verbose and cumbersome, especially when needing to rerun programs frequently. To streamline this process, I propose the addition of a new "start" command in Poetry.

## Current Behavior:
Users currently rely on poetry run to execute Python scripts within their Poetry-managed projects. While functional, this command can be verbose and repetitive, especially for frequently rerun programs.

## Desired Feature:
I suggest adding a "start" command in Poetry, which would serve as an alias to poetry run python. This command would allow users to specify the entry point for their scripts via a property in [tool.poetry]. This addition would simplify the process of running programs, making it more intuitive and efficient.

## Benefits:
- Improved user experience: The addition of a "start" command would simplify the process of running programs within Poetry-managed projects.
- Increased efficiency: Users would spend less time typing verbose commands and more time focused on their tasks.
- Enhanced usability: The new command would make Poetry even more accessible to users, especially those new to the tool.

**Comment by dimbleby** [comment]
@BearingMe I see you have raised a series of issues describing possible documentation improvements.

Please understand that by far the best way to get such things to happen is to contribute the change that you would like to see.

**Comment by dimbleby** [comment]
I think this one is unlikely.  

Suggestions:

- expose your scripts as entrypoints, using `poetry.scripts`
- put a shebang in your scripts, so that you do not have to specify `python whatever.py` but can just run `whatever.py` directly
- prefer to live in an active virtual environment, so that you never have to type `poetry run`

**Comment by BearingMe** [comment]
@dimbleby I see, but I had to it try anyway. I'm currently following the same advice you've provided. Yet, as a newcomer to Python and Poetry, I found certain aspects challenging to grasp, especially since I only started using it yesterday. 

It would be beneficial if such functionality were more accessible and integrated into the standard usage flow of the system.

**Comment by abn** [comment]
As the start command would simply be an alias to poetry `poetry run python` this would not be consistent with the ux we want as it creates multiple ways to do the same thing via the command line. 

Aside from the above suggestions, for your own purposes you can maybe create an alias in your shell profile?

```sh
alias poertrypy="poetry run python"
```

Or consider using a plugin a line https://poethepoet.natn.io/poetry_plugin.html for common tasks. 

But as it stands we won't be implementing this feature. 

Thank you for taking the time to raise a detailed issue.
