### ISSUE TITLE
`remove` usage is unclear

### ISSUE THREAD

**Issue by cgalo5758** [python-poetry/poetry#9041]
### Issue Kind

Unclear documentation

### Existing Link

https://python-poetry.org/docs/cli/#remove

### Description

It is not entirely clear what remove does and it would be helpful to be more explicit about the action that `remove` performs. From the current documentation, while it does mention that "The `remove` command removes a package from the current list of installed packages." It should explicitly add that it doesn't actually uninstall packages.

I imagine this would prevent some confusion around issues such as #648 and #468.

Additionally, I am not noticing any difference between the actions performed using `remove` with or without `--lock`. They update both `pyproject.toml` and `poetry.lock`. If there are side effects of `remove`, it'd also be nice to know what those are (Like why does `remove` update and resolve dependencies? Why does "Package operations" without `--lock` say "0 removals" despite the packages being removed?)

**Comment by dimbleby** [comment]
> It should explicitly add that it doesn't actually uninstall packages

But it does.  I don't know whether this makes you more right or more wrong!

Anyway, if you want docs improvements the way to do it is to submit a pull request with the change you want to see.  It doesn't have to be perfect first time, folk will review before merging.

**Comment by cgalo5758** [comment]
> But it does.

Oh yeah. you are right... I just tried it. Okay, I still think this documentation on `remove` should be edited. My assumption, based on it as it currently is, is that it only removes them from `poetry.lock` and `pyproject.toml`.

I can open up a pull request and:
- write in that it does uninstall packages.
- removes them from  `poetry.lock` and `pyproject.toml`.

What I am still not sure about is why using the "--lock" flag edits both `poetry.lock` and `pyproject.toml` (it literally says "Do not perform operations (only update the lockfile)"). Is this a bug that I should open another issue for or is the documentation not clear?

Also, what are the "operations" that the documentation refers to?

**Comment by dimbleby** [comment]
'--lock` does make it "not actually uninstall packages" ie it just updates the lock file

**Comment by abn** [comment]
> Also, what are the "operations" that the documentation refers to?

In this context, an operation is an action poetry takes for the project - install, uninstall, skip (no action). Feel free to raise a documentation change when you are ready. Specifics can be discussed there.

Closing this for now as I believe your questions have been answered. Feel free to start a discussion on GitHub and/or on Discord to discuss further or if you need help around how to make the changes.
