### ISSUE TITLE
PIP replacement for UV

### ISSUE THREAD

**Issue by Luca-Blight** [python-poetry/poetry#9062]
### Issue Kind

Brand new capability

### Description

```Markdown
I would like to replace pip with uv packager installer
```

### Impact

```Markdown
Significant performance gains from a very reliable organization.
```

### Workarounds

```Markdown
No, the package is bound to Rust. There is no other alternative.
```

**Comment by Secrus** [comment]
Poetry is not using pip for package installation for some time now.

**Comment by Secrus** [comment]
`installer` package.

**Comment by dd-ssc** [comment]
@Secrus: care to share a link ? or any other further information ?

**Comment by KyleKing** [comment]
FYI, there a couple of related tickets that have additional context and discussion: https://github.com/python-poetry/poetry/issues/8978
