### ISSUE TITLE
Update publish command documentation to indicate how to set username and password with environment variables

### ISSUE THREAD

**Issue by mwgamble** [python-poetry/poetry#9109]
### Issue Kind

Improving documentation

### Existing Link

https://python-poetry.org/docs/cli/#publish

### Description

In #9053, I was told that it is possible to set the username and password used for publishing with the `publish` command. I was admonished for not reading the documentation, and linked to this page:
https://python-poetry.org/docs/repositories/#configuring-credentials

The thing that @dimbleby didn't account for before telling me to read the documentation is that I had read the documentation, I just apparently hadn't read the _correct_ documentation. I first checked the output of `poetry publish --help`, and then I read this page:
https://python-poetry.org/docs/cli/#publish

And nowhere did it mention configuring credentials via environment variables.

So my request is to please improve the documentation **for the publish command specifically** to indicate that this is possible. It would also be nice if the output of `poetry publish --help` could indicate this too.

**Comment by dimbleby** [comment]
Submit a pull request!
