### ISSUE TITLE
test_executor.py::test_executor_known_hashes fails when poetry built without internet access

### ISSUE THREAD

**Issue by hrnciar** [python-poetry/poetry#9114]
### Issue Kind

Change in current behaviour

### Description

Some tests are failing when Poetry is built without internet access, the issue is simillar to #8288 and #8740. This time `test_executor.py::test_executor_known_hashes` is the culprit. I am happy to open a PR to mark the test with "network" marker, but I'd like to hear your opinion first. Maybe it can be fixed properly somehow. cc @radoering 

Full traceback:
~~~~
=========================== short test summary info ============================
FAILED tests/installation/test_executor.py::test_executor_known_hashes[package_files0-expected_url_reference0]
FAILED tests/installation/test_executor.py::test_executor_known_hashes[package_files1-expected_url_reference1]
FAILED tests/installation/test_executor.py::test_executor_known_hashes[package_files2-expected_url_reference2]
=========== 3 failed, 1596 passed, 6 skipped, 278 warnings in 46.04s ===========
~~~~
See [poetry-log.txt](https://github.com/python-poetry/poetry/files/14492663/poetry-log.txt) for a full log.

### Impact

Downstream distributors, such as Fedora, cannot successfully build poetry without internet access. 

### Workarounds

It's possible to skip the tests, but we are trying to avoid downstream only patches, hence reporting upstream.

**Comment by radoering** [comment]
Is it sufficient if you add the `mock_file_downloads` fixture?

**Comment by abn** [comment]
Tested #9117 local without network and it works.

**Comment by hrnciar** [comment]
Perfect! Thank you!
