### ISSUE TITLE
how to install .whl file which contains apt dependency

### ISSUE THREAD

**Issue by ahmasoum** [python-poetry/poetry#9116]
### Issue Kind

Other

### Description

my project has some apt dependencies and I want to use poetry. I have installed my project apt dependencies using the build.py script. but when the wheel file is created, I can't install it with "pip install" because of these apt dependencies. but when I unzip the wheel file I can install the package using "poetry install". can you please help me with what should i do to install this package using the wheel file without needing to extract it?

### Impact

this issue can help developers use poetry when their project has "apt" dependencies

### Workarounds

no

**Comment by abn** [comment]
This is not within the scope of what Poetry does. Poetry is designed to manage Python package dependencies not OS distribution dependencies.

Based on the sparse information provided, it seems you want Poetry to also install system dependencies. Note that `apt` is not universal. If you really want to manage system packages somehow via Poetry, you probably want to build your own [Poetry Plugin](https://python-poetry.org/docs/plugins/) that somehow extracts the requirements and installs that into your environment. For example it could be an Ansible plugin that parses a config section and then installs the packages specific to the distro in the runtime environment.

Closing this as this is not something that Poetry plans to build.
