### ISSUE TITLE
Install dev-dependencies of `Path`-dependencies

### ISSUE THREAD

**Issue by ErikDeSmedt** [python-poetry/poetry#9124]
### Issue Kind

Change in current behaviour

### Description

If a project has a path-dependency with `develop=true`.
Using `poetry install` should install all dev-dependencies of that path-dependency.

### Impact

Let's use the following motivating example.
I am working on an application and a library that external developers can use to integrate with my app.

This results in the following directory structure.

```
.
├── awesome_app
│   └── __init__.py
├── awesome-lib
│   ├── awesome_lib
│   │   └── __init__.py
│   └── pyproject.toml
├── poetry.lock
└── pyproject.toml
```

The `./pyproject.toml` in the repo-root installs `awesome_lib` as a path-dependency. 
``` toml
awesome-lib = { path = "./awesome-lib", develop=true}
```
and `./awesome-lib/pyproject.toml` includes a few type-stubs as developer dependencies.
``` toml
[tool.poetry.group.dev.dependencies]
types-requests = "^2.31.0"
```

Executing `poetry install` does not install `types-requests`.
i

See this [repo](https://github.com/ErikDeSmedt/poetry-feature-request) for a minimal example

### Workarounds

The first work-around is to change the installation procedure.

```
> poetry install
> cd awesome-lib; poetry install
```

The other work-around is to copy all dev-dependencies from `./awesome-lib/pyproject.toml` to `./pyproject.toml`

**Comment by dimbleby** [comment]
poetry does not and should not install dev-dependencies of any sub-dependencies.

if the type stubs are needed for development of the top-level project, then the top-level project should declare the dependency itself.

please close
