### ISSUE TITLE
Dependency constraints missing documentation

### ISSUE THREAD

**Issue by tenpura-shrimp** [python-poetry/poetry#9146]
### Issue Kind

Missing documentation

### Existing Link

https://python-poetry.org/docs/dependency-specification/

### Description

From the source code, the following dependency constraints are possible: https://github.com/python-poetry/poetry-core/blob/2d02f475ffb6d8b2d66c97ccca0fe8279473f7c0/src/poetry/core/factory.py#L263

Nowhere in the documentation does it list the possible allowed constraints, or the function of each constraint and how it is applied.

**Comment by dimbleby** [comment]
you didn't say exactly what it is that you think is missing.  Much the most useful way to make that clear would be to submit a pull request making the change that you would like to see...

**Comment by dimbleby** [comment]
(not closed!)
