### ISSUE TITLE
Add `--no-binary` flag to `add` action

### ISSUE THREAD

**Issue by ccrvlh** [python-poetry/poetry#9157]
### Issue Kind

Brand new capability

### Description

Currently Poetry doesn't seem to be have a way to install packages with `--no-binary` flag. There were two previous issues that I could find about this: https://github.com/python-poetry/poetry/issues/365 and https://github.com/python-poetry/poetry/issues/1316 both were closed, not sure why. One of them mention the introduction of this option, but I don't seem to have it:

```shell
(.venv) user@imac ~/project (main*?) $ poetry add psycopg2 --no-binary

The option "--no-binary" does not exist
(.venv) user@imac ~/project (main*?) $ poetry add --no-binary psycopg2

The option "--no-binary" does not exist
```

In this specific case, it seems Homebrew changed the logic with postgres/libpq, so `psycopg2` needs to be reinstalled with `no-binary` for it to update the `libpq` path. At this moment there doesn't seem to be a way to do that using Poetry.

It seems I could potentially use the local config with `poetry config --local installer.no-binary all,psycopg2` which I also couldn't make it work. Not only that, it seems unexpected that what is a `pip`'s  installer flag has to be defined on the project configuration level.

### Impact

For this scenario specifically, psycopg needs to be installed with `no-binary` which means that not having this in `Poetry` makes it impossible to handle the package using Poetry only.

### Workarounds

Only workaround I could find was to fallback to an alternative package management tool `pip`:  `pip3 install --no-binary :all: psycopg2 --force-reinstall`. It is expected that the package management tool currently in use would handle that situation, rather than relying on a different tool.

**Comment by dimbleby** [comment]
it's a config option https://python-poetry.org/docs/configuration#installerno-binary please close

**Comment by abn** [comment]
And in your case, you can also use the https://pypi.org/project/psycopg2-binary/ package instead of psycopg2.

Closing as adding a package only as a binary into the project dependencies or lock file is not something Poetry intends to support. Please refer to the `installer.no-binary` configuration linked to in the above comment for ensuring psycopg2 binary distribution is always installed on your system.

**Comment by ccrvlh** [comment]
@dimbleby I understand this is a config option as stated in the original text:

> It seems I could potentially use the local config with poetry config --local installer.no-binary all,psycopg2 which I also couldn't make it work. Not only that, it seems unexpected that what is a pip's installer flag has to be defined on the project configuration level.

Hence the reason this was created as a feature request.

@abn mind sharing the reasoning behind not supporting it on the CLI and moving this to the project config? If it's something that's relevant for a single/handful of packages, wouldn't it make sense to have this being handled on the package level vs on the project level?

**Comment by dimbleby** [comment]
choosing to use binary packages or not is user configuration, a choice that you are making.  it is not package configuration, other users of your package might have different preferences.

**Comment by ccrvlh** [comment]
@dimbleby that makes sense, thanks for the clarification.
