### ISSUE TITLE
I know that poetry is supposed to _replace_ `setup.py`, but how can I develop a package on my local machine when using poetry, I've read that the equivalent of `pip install -e .` in poetry is simply `poetry install` from the root directory of the project, but even though poetry does state it finished installing my package, I get import errors everywhere.

### ISSUE THREAD

**Issue by msbatin2** [python-poetry/poetry#9162]
I know that poetry is supposed to _replace_ `setup.py`, but how can I develop a package on my local machine when using poetry, I've read that the equivalent of `pip install -e .` in poetry is simply `poetry install` from the root directory of the project, but even though poetry does state it finished installing my package, I get import errors everywhere.

I would ideally want to install my package system-wide, or a virtualenv of my choice, so I can run it no after going into `poetry shell`, but even that isn't working.

Edit: one thing I noticed, is that my package is (re?) installed every time I run poetry install..

_Originally posted by @SHxKM in https://github.com/python-poetry/poetry/discussions/1135_

**Comment by abn** [comment]
Please follow the issue templates. This discussion was already resolved.

**Comment by msbatin2** [comment]
.".noreply@google.com"

**Comment by msbatin2** [comment]
.".noreply@google.com"
