### ISSUE TITLE
There is no information on how to use poetry with virtual environment

### ISSUE THREAD

**Issue by crawlchange** [python-poetry/poetry#9181]
### Issue Kind

Missing documentation

### Existing Link

.

### Description

As people working with a package for managing dependencies in python should know, installing python versions in ubuntu and other poorly designed linux operating systems without using a virtual environment breaks the system.

As a consequence, 99% of users need to use python with a virtual environment.

For example, they might need to run a console, which they can't with poetry.

So, people using poetry will often, if not always, need to run poetry inside of a virtual environment.

Now, there are no instructions on how to do this, rendering poetry as a whole basically unusable in practice.

When running the command "poetry env info", one gets a Path and an Executable.

We users need instructions on how to change this.

Also, it is not nearly enough to say "run this command like: poetry set path @path". What is the @path variable supposed to represent? Path to what?

When I have a venv folder, WHAT is the path that I should provide? There are many subfolders and files under the venv folder.

Please add minimal documentation so that this project is usable by people who are not its developers.

**Comment by dimbleby** [comment]
"No information" and "basically unusable" is silly, of course lots of people are able to use poetry.

https://python-poetry.org/docs/managing-environments/ looks like mostly what you want, please contribute improvements if you have them.

**Comment by abn** [comment]
This issue lacks any substantial or usable information to act on. Further, as pointed out above, managing virtual environments is documented.

If you have improvements for the documentation that you want to suggest, feel free to provide a pull request. If you have questions and need help even after reading the documentation, I would suggest you reach out on our [Discord Server](https://discord.com/invite/awxPgve) or raise a [Discussion](https://github.com/python-poetry/poetry/discussions) with specific questions.
