### ISSUE TITLE
 --no-root via ENV variable or poetry.toml ?

### ISSUE THREAD

**Issue by mgzenitech** [python-poetry/poetry#9196]
### Issue Kind

Change in current behaviour

### Description

Right now we can disable it via --no-root switch, ie:
```
poetry install --no-root
```

Can we have ability to set it via ENV variable or poetry.toml in addition to this switch?

### Impact

Just ability to setup this once per project and any developer who gets the code wouldn't have to do `--no-root`.

### Workarounds

Obviously, calling install with `--no-root` all the time

**Comment by finswimmer** [comment]
Hey,

if your project really never needs to be installed in editable mode, setting `package-mode = false` might what you are looking for. See https://python-poetry.org/docs/basic-usage/#operating-modes

Not installing the project itself only makes sense, if you do not have any `import` statements that import modules of your projects. If you are doing this and the project isn't installed you have either have to mess around yourself with manipulating `sys.path` or be aware about how Python discovers moduls that should be imported.

**Comment by mgzenitech** [comment]
> Hey,
> 
> if your project really never needs to be installed in editable mode, setting `package-mode = false` might what you are looking for. See https://python-poetry.org/docs/basic-usage/#operating-modes
> 
> Not installing the project itself only makes sense, if you do not have any `import` statements that import modules of your projects. If you are doing this and the project isn't installed you have either have to mess around yourself with manipulating `sys.path` or be aware about how Python discovers moduls that should be imported.

superb, didn't even know about this setting.
