### ISSUE TITLE
Abortion of `poetry shell` if it doesn't manage to find shell files

### ISSUE THREAD

**Issue by dcguim** [python-poetry/poetry#9269]
### Issue Kind

Change in current behaviour

### Description

Currently in poetry 1.8.2, and I am using zshell (default on macOS). My zshell configuration is slightly different than usual, as I keep my dot-z-shell files in a separate `infra` folder, as I like to version them, in my `$HOME`, I  and a single `.zshenv` file:

```shell
ZDOTDIR=$HOME/work/infra/.zsh
source $ZDOTDIR/.zshenv
```

When I try to enter into a virtualenv with `$ poetry shell` I get the following messages:

```shell
Using python3 (3.11.8)
Spawning shell within /Users/dguim/Library/Caches/pypoetry/virtualenvs/private-gpt-8E1Wl_zS-py3.11
/etc/zshrc:7: command not found: locale
/etc/zshrc_Apple_Terminal:104: command not found: mkdir
env: bash: No such file or directory
```

So `poetry shell` is trying to access the system-wide zshell files at `/etc/`  (I believe this is because it couldn't find the zshell files in my home directory) and in this process it is truncating my `$PATH` as the the values of `$PATH` in the environment do not contain the usual paths, such as `/usr/local/bin`, `/usr/bin`, `/bin`, `/usr/sbin`, ...

Moreover, I was about to ask if it would be desirable to implement a functionality for `poetry bash` that inspects the shell files available, say at `$HOME` and if it can't find any shell files, it aborts the command altogether with the message "Please provide argument '--path' for locating your shell files"

### Impact

`$ poetry shell` command will have limited functionality when user keep their shell files in non-obvious places.

### Workarounds

Looking in the documentation I tried using `VIRTUAL_ENV_DISABLE_PROMPT=1`. Of course I could just activate the shell on my own `source $(poetry env info --path)/bin/activate`, but I am not sure if `poetry bash` is doing some other nice things that I want, or if it is just activating the shell.

**Comment by dimbleby** [comment]
if you want to dig into it then the activation code starts [here](https://github.com/python-poetry/poetry/blob/bd029ac0564b7822efbc903320e24ad021567a48/src/poetry/utils/shell.py#L71)

imo `poetry shell` is a mistake and sourcing the virtual activation script yourself is just better.  More discussion eg in #4216

**Comment by dcguim** [comment]
I will just alias `poetry bash` to `source $(poetry env info --path)/bin/activate` this should do for now.
