### ISSUE TITLE
Add zip_safe support

### ISSUE THREAD

**Issue by AstraLuma** [python-poetry/poetry#928]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Feature Request
I don't see any mention of zip_safe.

Although this option was created for the now-defunct egg format, it's still useful for PEP 441 zipapps.

**Comment by astronouth7303** [comment]
afaik, this has not yet been implemented.

**Comment by kkirsche** [comment]
`zip_safe` is referenced in the Flask documentation for deploying via setuptools, and would be a valuable inclusion for teams who deploy Flask in this manner.

**Comment by dimbleby** [comment]
zip_safe is officially [obsolete](https://setuptools.pypa.io/en/latest/deprecated/zip_safe.html), I very much doubt anyone should be adding support for it anywhere.
