### ISSUE TITLE
Cannot install ipykernel 6.29.4 with poetry

### ISSUE THREAD

**Issue by david-waterworth** [python-poetry/poetry#9288]
### Description

I'm not sure if this is an upstream issue, I have an in-project venv (.venv) and I'm using vscode. I use poetry to maange my dependencies and occasional notebooks for visualization. I prefer to add ipykernel to poetry (vscode will install it automatically but poetry install --sync removes it)

This broke today, after a bit of debugging I discovered that

```
.venv/bin/python -m pip install ipykernel -U --force-reinstall
```

Works fine. This install `ipykernel==6.29.4`, along with dependencies including `jupyer_core`

My poetry.yaml contains

```
[tool.poetry.group.dev.dependencies]
ipykernel = "6.29.4"
```

When I run `poetry lock` this doesn't add the required dependencies (jupyer_core etc) to `poetry.lock` so they're not included and I get an import error.

When I revert to 

```
[tool.poetry.group.dev.dependencies]
ipykernel = "6.29.3"
```

It works, so I guess there's something about 6.29.4 that breaks a poetry install  (but pip install works fine).

This was made worse because the version was specified as "^6.29.3" so it suddenly broke with no indication why. I'd imagine this needs to be reported to the maintainers of ipykernel but I have no idea what to include.

### Workarounds

Downgrade ipykernel

### Poetry Installation Method

pipx

### Operating System

Ubuntu 22.04

### Poetry Version

Poetry (version 1.7.1)

### Poetry Configuration

```bash session
cache-dir = "/home/david/.cache/pypoetry"
experimental.system-git-client = false
installer.max-workers = null
installer.modern-installation = true
installer.no-binary = null
installer.parallel = true
virtualenvs.create = true
virtualenvs.in-project = true
virtualenvs.options.always-copy = false
virtualenvs.options.no-pip = false
virtualenvs.options.no-setuptools = false
virtualenvs.options.system-site-packages = false
virtualenvs.path = "{cache-dir}/virtualenvs"  # /home/david/.cache/pypoetry/virtualenvs
virtualenvs.prefer-active-python = false
virtualenvs.prompt = "{project_name}-py{python_version}"
warnings.export = true
```

### Poetry Runtime Logs

```bash session
n/a
```

**Comment by dimbleby** [comment]
Duplicate #9191, #9266, #9272, with same solution. 

Please close.

**Comment by david-waterworth** [comment]
Thanks, updating `pkginfo` alone didn't work (by itself), but clearing my cache did. It also wasn't 100% clear from the linked issues how to properly update `pkginfo` in a `pipx` installation of poetry (I ran `poetry self add pkginfo==1.10.0` as recommended but then another poster later said "this isn't correct for pipx installs" but didn't elaborate why.

Also is this likely to reoccur? I don't see any permanent fix in any of the linked issues. Having a build server suddenly fail and require manual intervention is a bit of a pain.

**Comment by dimbleby** [comment]
> is this likely to reoccur?

Are you likely to downgrade pkginfo? 
#9130

**Comment by david-waterworth** [comment]
No, it wasn't clear what the actual issue was - but if I'm not mistaken it's packages that use the newer "metadata version 2.3 / PEP 685" which requires pkginfo >= 1.10.0 for poetry (but not pip?).

Ideally though there would be be some sort of warning at least if poetry encounters package metadata that it doesn't support rather than silently not installing (or in my case uninstalling) dependencies - if that's possible? Otherwise it could happen again when "metadata version 2.4" comes out some time in the distant future?

**Comment by dimbleby** [comment]
#9195

Please close
