### ISSUE TITLE
How to point token for private repo?

### ISSUE THREAD

**Issue by solidguy7** [python-poetry/poetry#9307]
### Issue Kind

Missing documentation

### Existing Link

https://python-poetry.org/docs/repositories/

### Description

I use my private repo as poetry dependency like this: ```ecosys-lib = {git = "https://ecosys-lib:${ECOSYS_LIB_TOKEN}@gitlab.dialog.info/analytics/dashsys/ecosys_lib.git", branch = "master", develop = true}```
How can I point ECOSYS_LIB_TOKEN in order to build poetry.lock? I have found this take in documentation only for pypi

**Comment by dimbleby** [comment]
poetry does not support environment variable substitution.  I expect it is unlikely to add this support, this has been rejected as long ago as #337

please close
