### ISSUE TITLE
Overriding required python version for dependency.

### ISSUE THREAD

**Issue by hgaiser** [python-poetry/poetry#9308]
### Issue Kind

Brand new capability

### Description

I am using [`ids-peak`](https://en.ids-imaging.com/download-details/AB12611.html?os=linux&version=&bus=64&floatcalc=) in one of my projects, which is published as .deb files. I uploaded the Debian files to cloudsmith.io. There are 3 files, one for python3.9, python3.10 and python 3.11. Each defines their python requirements as `==python3.9.*`, `==python3.10.*` and `==python3.11.*` respectively.

If I specify `python = ">3.9, <3.12"` as a dependency in my project, I get the following error (running `poetry lock`) :

```
The current project's supported Python range (>3.9,<3.12) is not compatible with some of the required packages Python requirement:
  - ids-peak requires Python ==3.10.*, so it will not be satisfied for Python >3.9,<3.10.dev0 || ==3.11.*

Because ids-peak (1.7.1.0) requires Python ==3.10.*
 and no versions of ids-peak match >1.7.1,<2.0.0, ids-peak is forbidden.
So, because rocsys-vision depends on ids-peak (^1.7.1), version solving failed.

  • Check your dependencies Python requirement: The Python requirement can be specified via the `python` or `markers` properties
    
    For ids-peak, a possible solution would be to set the `python` property to "==3.10.*"
```

There's two things wrong here:

1. I am using python3.11, but somehow Poetry found only the 3.10 version of `ids-peak`. I plan to dive a bit deeper to figure out why this happened and I'll update this issue if I found out why.
2. Poetry is only using one version to decide which python versions are allowed.

(This is wishful thinking: ) In a perfect world I would define `python = "^3.9"` and let Poetry decide that, because of `ids-peak`, only python3.9, python3.10 and python3.11 are acceptable. However that doesn't seem to be how Poetry works.

The next best thing (which is the request that I'm submitting) is to change how Poetry decides the Python version when multiple sources are found, or alternatively allow to override the required Python version.

### Impact

I believe this is clear based on the description, I'm not sure how to describe it further.

### Workarounds

None that I have thought of yet.

**Comment by hgaiser** [comment]
Regarding the issue that poetry finds the wrong wheel: if I navigate to the URL that Poetry is parsing, I see the following:

![image](https://github.com/python-poetry/poetry/assets/716138/4c3a1066-3f78-44a8-8031-f696f4a30f54)

Poetry [checks the first wheel](https://github.com/python-poetry/poetry/blob/main/src/poetry/repositories/http_repository.py#L322-L326) and returns its info. This happens to be the python3.10 wheel, so for further incompatibility checks, it will think there is only a python3.10 wheel available for this dependency.

**Comment by dimbleby** [comment]
> Each defines their python requirements as ==python3.9.*, ==python3.10.* and ==python3.11.* respectively.

dont do that, let the tags in the filenames do the work

poetry assumes that all distributions of a release provide the same metadata, so everything is working as expected here

please close

**Comment by hgaiser** [comment]
> > Each defines their python requirements as ==python3.9._, ==python3.10._ and ==python3.11.* respectively.
> 
> dont do that, let the tags in the filenames do the work 
> 
> poetry assumes that all distributions of a release provide the same metadata, so everything is working as expected here
> 
> please close

Hey, thanks for your quick reply! I would love to do that, but this is a (mostly) automated procedure. I upload the .deb files to Cloudsmith, it analyzes the contents and automatically places it in the location that it chooses. I am guessing that the current behavior of Poetry is as intended, but it doesn't seem to work in combination with how Cloudsmith uploads Python packages.

Do you happen to know if there is some documentation on how these .whl files should've been uploaded in the first place? I realize this is probably not defined somewhere, but if it is then I can show that to people from Cloudsmith and request a change there. In other words: how do we know it's Cloudsmith doing something wrong, versus Poetry doing something wrong?

I prefer to resolve these questions before closing the issue if you don't mind.

**Comment by hgaiser** [comment]
Small addition: I briefly checked how [`rye`](https://rye-up.com) handles this case, using both their `pip-tools` and `uv` backend it managed to pull in this dependency correctly.

**Comment by dimbleby** [comment]
poetry is building cross-platform solutions, in order to make this a tractable problem it assumes that metadata matches across distributions.

if ids-peak puts different metadata in different distributions of the same release then it is not compatible with poetry.  if they want to support this case then they should put the same metadata in all distributions

in particular, requiring specific python versions in wheels is redundant: just dont do that.

**Comment by hgaiser** [comment]
Apologies, I was mistaken earlier. I download a single .deb file, which contains their C library and multiple .whl files for python bindings. These .whl files contain a .so file that links to libpython3.xx.so.

I was thinking, pytorch should have exactly the same setup, but that does appear to work. Indeed, they define the following in their metadata:

```
Requires-Python: >=3.8.0
```

Even if the .whl file is for python3.9. I will make an issue with IDS, thank you for your feedback, apologies for the noise!
