### ISSUE TITLE
Parse environment variable when building spacific package

### ISSUE THREAD

**Issue by zhangyilun** [python-poetry/poetry#9323]
### Issue Kind

Brand new capability

### Description

The issue mainly came from building the `llama-cpp-python` package for different backends. For example, in order to build with CUDA support, the pip equivalent is `CMAKE_ARGS="-DLLAMA_CUDA=on" pip install llama-cpp-python` (see https://github.com/abetlen/llama-cpp-python?tab=readme-ov-file#supported-backends) for more info).

AFAIK, with current poetry this is not possible. Tried to install with `CMAKE_ARGS="-DLLAMA_CUDA=on" poetry add llama-cpp-python` and it's not installing with the correct backend support.

### Impact

This makes package management for project more difficult if someone is using poetry as packages like `llama-cpp-python` has to be installed with`pip` and it won't be managed properly by poetry.

### Workarounds

Workaround is to either not use poetry or have 2 package management systems, mainly poetry for straightforward packages and remaining ones with pip or others that support specifying environment variables.

**Comment by dimbleby** [comment]
environment variables are passed through and so this works today - as we can tell by the error message when I try the install on my system that does not have cuda:
```
$ CMAKE_ARGS="-DLLAMA_CUDA=on" poetry add llama-cpp-python
Using version ^0.2.62 for llama-cpp-python

Updating dependencies
Resolving dependencies... (1.1s)

Package operations: 6 installs, 0 updates, 0 removals

  - Installing markupsafe (2.1.5)
  - Installing diskcache (5.6.3)
  - Installing jinja2 (3.1.3)
  - Installing numpy (1.26.4)
  - Installing typing-extensions (4.11.0)
  - Installing llama-cpp-python (0.2.62): Failed

  ChefBuildError

  Backend subprocess exited when trying to invoke build_wheel

  *** scikit-build-core 0.9.0 using CMake 3.22.1 (wheel)
  *** Configuring CMake...
  loading initial cache file /tmp/tmpa0_n9frt/build/CMakeInit.txt
  -- The C compiler identification is GNU 11.4.0
  -- The CXX compiler identification is GNU 11.4.0
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /usr/bin/cc - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /usr/bin/c++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done                                                                                       -- Found Git: /usr/bin/git (found version "2.34.1")                                                                            -- Looking for pthread.h
  -- Looking for pthread.h - found
  -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
  -- Found Threads: TRUE
  -- Could not find nvcc, please set CUDAToolkit_ROOT.
  CMake Warning at vendor/llama.cpp/CMakeLists.txt:464 (message):
    CUDA not found


  -- CUDA host compiler is GNU
  CMake Error at vendor/llama.cpp/CMakeLists.txt:909 (get_flags):
    get_flags Function invoked with incorrect arguments for function named:
    get_flags


  -- Warning: ccache not found - consider installing it for faster compilation or disable this warning with LLAMA_CCACHE=OFF
  -- CMAKE_SYSTEM_PROCESSOR: x86_64
  -- x86 detected
  INSTALL TARGETS - target llama has PUBLIC_HEADER files but no PUBLIC_HEADER DESTINATION.
  INSTALL TARGETS - target llama has PUBLIC_HEADER files but no PUBLIC_HEADER DESTINATION.
  -- Configuring incomplete, errors occurred!
  See also "/tmp/tmpa0_n9frt/build/CMakeFiles/CMakeOutput.log".

  *** CMake configuration failed
```

**Comment by zhangyilun** [comment]
> environment variables are passed through and so this works today - as we can tell by the error message when I try the install on my system that does not have cuda:
> 
> ```
> $ CMAKE_ARGS="-DLLAMA_CUDA=on" poetry add llama-cpp-python
> Using version ^0.2.62 for llama-cpp-python
> 
> Updating dependencies
> Resolving dependencies... (1.1s)
> 
> Package operations: 6 installs, 0 updates, 0 removals
> 
>   - Installing markupsafe (2.1.5)
>   - Installing diskcache (5.6.3)
>   - Installing jinja2 (3.1.3)
>   - Installing numpy (1.26.4)
>   - Installing typing-extensions (4.11.0)
>   - Installing llama-cpp-python (0.2.62): Failed
> 
>   ChefBuildError
> 
>   Backend subprocess exited when trying to invoke build_wheel
> 
>   *** scikit-build-core 0.9.0 using CMake 3.22.1 (wheel)
>   *** Configuring CMake...
>   loading initial cache file /tmp/tmpa0_n9frt/build/CMakeInit.txt
>   -- The C compiler identification is GNU 11.4.0
>   -- The CXX compiler identification is GNU 11.4.0
>   -- Detecting C compiler ABI info
>   -- Detecting C compiler ABI info - done
>   -- Check for working C compiler: /usr/bin/cc - skipped
>   -- Detecting C compile features
>   -- Detecting C compile features - done
>   -- Detecting CXX compiler ABI info
>   -- Detecting CXX compiler ABI info - done
>   -- Check for working CXX compiler: /usr/bin/c++ - skipped
>   -- Detecting CXX compile features
>   -- Detecting CXX compile features - done                                                                                       -- Found Git: /usr/bin/git (found version "2.34.1")                                                                            -- Looking for pthread.h
>   -- Looking for pthread.h - found
>   -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
> -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
>   -- Found Threads: TRUE
>   -- Could not find nvcc, please set CUDAToolkit_ROOT.
>   CMake Warning at vendor/llama.cpp/CMakeLists.txt:464 (message):
>     CUDA not found
> 
> 
>   -- CUDA host compiler is GNU
>   CMake Error at vendor/llama.cpp/CMakeLists.txt:909 (get_flags):
>     get_flags Function invoked with incorrect arguments for function named:
>     get_flags
> 
> 
>   -- Warning: ccache not found - consider installing it for faster compilation or disable this warning with LLAMA_CCACHE=OFF
>   -- CMAKE_SYSTEM_PROCESSOR: x86_64
>   -- x86 detected
>   INSTALL TARGETS - target llama has PUBLIC_HEADER files but no PUBLIC_HEADER DESTINATION.
>   INSTALL TARGETS - target llama has PUBLIC_HEADER files but no PUBLIC_HEADER DESTINATION.
>   -- Configuring incomplete, errors occurred!
>   See also "/tmp/tmpa0_n9frt/build/CMakeFiles/CMakeOutput.log".
> 
>   *** CMake configuration failed
> ```

What version are you using? I ran on machine with CUDA the above exact command, no error during installation but when I load the model, it's loading it on CPU.

**Comment by dimbleby** [comment]
perhaps you have a cached wheel that was built before you set environment variables, suggest clearing your cache.

per my previous message, this definitely works as expected already

**Comment by zhangyilun** [comment]
@dimbleby Hmm yeah, it's now working, wonder if it's from 0.2.63 as last week it didn't work when I was using 0.2.62.

Another question if you don't mind. I checked `pyproject.toml` file and it just shows `llama-cpp-python = "^0.2.63"`. I'm I'm using the `pyprojet.toml` or the lock file to install packages in another environment, how would `llama-cpp-python` know to install with the CUDA flag as it's not specified anywhere. Thank you!

**Comment by dimbleby** [comment]
poetry does not record environment variables, you will have to be careful of that yourself

**Comment by zhangyilun** [comment]
I guess that's probably the main feature I'm requesting here, maybe I only described the error/wrong behavior. For example when something like above is run with flag, that can be recorded in `pyproject.toml` and lock file.

**Comment by dimbleby** [comment]
python source distributions can do whatever they want at build time: to give a reproducible build poetry would have to store not only the whole environment, but also the result of any network calls, the state of the system random number generator, the phase of the moon, etc.

(this is not going to happen)
