### ISSUE TITLE
poetry update command only lockfile and not toml

### ISSUE THREAD

**Issue by lorypelli** [python-poetry/poetry#9336]
### Description

When I do this command, only the lockfile gets updated and not the toml one

### Workarounds

remove and re-add the dependency (but it changes position, you should order alphabetically)

### Poetry Installation Method

pip

### Operating System

Windows 10

### Poetry Version

Poetry (version 1.8.2)

### Poetry Configuration

```bash session
cache-dir = "C:\\Users\\<username>\\AppData\\Local\\pypoetry\\Cache" (it uses double slash to escape, I don't like it)
experimental.system-git-client = false
installer.max-workers = null
installer.modern-installation = true
installer.no-binary = null
installer.parallel = true
keyring.enabled = true
solver.lazy-wheel = true
virtualenvs.create = true
virtualenvs.in-project = true
virtualenvs.options.always-copy = false
virtualenvs.options.no-pip = false
virtualenvs.options.no-setuptools = false
virtualenvs.options.system-site-packages = false
virtualenvs.path = "{cache-dir}\\virtualenvs"  # C:\Users\<username>\AppData\Local\pypoetry\Cache\virtualenvs (it doesn't use here)
virtualenvs.prefer-active-python = false
virtualenvs.prompt = "{project_name}-py{python_version}"
warnings.export = true
```

### Poetry Runtime Logs

```bash session
I already reinstalled the package so it has correct version but if I try to install it again with old one, if I do update it says no packages need update, why?
```

**Comment by finswimmer** [comment]
Hey,

works as expected. See https://python-poetry.org/docs/cli/#update

To upgrade a dependency to its latest version run `poetry add <package>@latest`.

Maybe also interesting for you: https://github.com/python-poetry/poetry/issues/461

fin swimmer

**Comment by lorypelli** [comment]
> Hey,
> 
> works as expected. See https://python-poetry.org/docs/cli/#update
> 
> To upgrade a dependency to its latest version run `poetry add <package>@latest`.
> 
> Maybe also interesting for you: https://github.com/python-poetry/poetry/issues/461
> 
> fin swimmer

So, is it an expected behaviour that it doesn't update toml file?
