### ISSUE TITLE
poetry config command generated the poetry.toml file outside the project 

### ISSUE THREAD

**Issue by HiNeal** [python-poetry/poetry#9343]
### Description

poetry config command generated the poetry.toml file outside the project, may should generated the poetry.toml file inside the project !,

poetry version: 1.8.2
platform: Mac OS 14.4

### Workarounds

yeah, It's not big problem, just move poetry.toml file inside the project is fine ! 

### Poetry Installation Method

install.python-poetry.org

### Operating System

Mac OS 14.4

### Poetry Version

1.8.2

### Poetry Configuration

```bash session
cache-dir = "/Users/username/Library/Caches/pypoetry"
experimental.system-git-client = false
installer.max-workers = null
installer.modern-installation = true
installer.no-binary = null
installer.parallel = true
keyring.enabled = true
solver.lazy-wheel = true
virtualenvs.create = true
virtualenvs.in-project = true
virtualenvs.options.always-copy = true
virtualenvs.options.no-pip = false
virtualenvs.options.no-setuptools = false
virtualenvs.options.system-site-packages = false
virtualenvs.path = "{cache-dir}/virtualenvs"  # /Users/oyca168/Library/Caches/pypoetry/virtualenvs
virtualenvs.prefer-active-python = false
virtualenvs.prompt = "{project_name}-py{python_version}"
warnings.export = true
```

### Poetry Runtime Logs

```bash session
poetry config command generated the poetry.toml file outside the project, may should generated the poetry.toml file inside the project !,
```

**Comment by finswimmer** [comment]
Hey,

you can already achieve this with the `--local` parameter. See https://python-poetry.org/docs/cli/#options-9

fin swimmer
