### ISSUE TITLE
no commands worked

### ISSUE THREAD

**Issue by CoolNateJr** [python-poetry/poetry#9346]
### Description

no commands worked after install

### Workarounds

none that i know of

### Poetry Installation Method

other

### Operating System

windows 11

### Poetry Version

1.8 i think

### Poetry Configuration

```bash session
i dont know
```

### Poetry Runtime Logs

```bash session
i dont know were no commands work
```

**Comment by finswimmer** [comment]
Hey,

without providing more information about what you have done and what happens exactly it is impossible to help here. So please provide as much information as possible, that will help us to help you.

fin swimmer
