### ISSUE TITLE
Poetry builds broken with PEP 517 error because of pyproject-hooks update on 4/29

### ISSUE THREAD

**Issue by mdagost** [python-poetry/poetry#9351]
### Description

Today, all of our automated package builds started to break with the error:

```
• Installing wget (3.2): Failed

  ChefBuildError

  Backend subprocess exited when trying to invoke get_requires_for_build_wheel
  
  Traceback (most recent call last):
    File "/usr/local/lib/python3.10/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/usr/local/lib/python3.10/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/usr/local/lib/python3.10/site-packages/pyproject_hooks/_in_process/_in_process.py", line 112, in get_requires_for_build_wheel
      backend = _build_backend()
    File "/usr/local/lib/python3.10/site-packages/pyproject_hooks/_in_process/_in_process.py", line 74, in _build_backend
      ep = os.environ['PEP517_BUILD_BACKEND']
    File "/usr/local/lib/python3.10/os.py", line 680, in __getitem__
      raise KeyError(key) from None
  KeyError: 'PEP517_BUILD_BACKEND'
```

Builds ran successfully at the end of last week.  Nothing changed with our poetry version (1.4.0), nothing changed with our poetry lock file.  This is running inside of docker python:3.10.8, which also hasn't been touched in a year.

The truly odd thing is that running `poetry install` a second time succeeds.

Any idea what is going on here?

### Workarounds

Running `poetry install` a second time.

### Poetry Installation Method

pip

### Operating System

docker python:3.10.8

### Poetry Version

1.4.0

### Poetry Configuration

```bash session
cache-dir = "/root/.cache/pypoetry"
experimental.new-installer = true
experimental.system-git-client = false
installer.max-workers = null
installer.modern-installation = true
installer.no-binary = null
installer.parallel = true
repositories.tegus.url = "https://<redacted>/"
virtualenvs.create = false
virtualenvs.in-project = null
virtualenvs.options.always-copy = false
virtualenvs.options.no-pip = false
virtualenvs.options.no-setuptools = false
virtualenvs.options.system-site-packages = false
virtualenvs.path = "{cache-dir}/virtualenvs"  # /root/.cache/pypoetry/virtualenvs
virtualenvs.prefer-active-python = false
virtualenvs.prompt = "{project_name}-py{python_version}"
```

### Poetry Runtime Logs

```bash session
Full stack trace:

• Installing wget (3.2): Failed

  Stack trace:

  8  /usr/local/lib/python3.10/site-packages/poetry/installation/executor.py:271 in _execute_operation
      269│ 
      270│             try:
    → 271│                 result = self._do_execute_operation(operation)
      272│             except EnvCommandError as e:
      273│                 if e.e.returncode == -2:

  7  /usr/local/lib/python3.10/site-packages/poetry/installation/executor.py:357 in _do_execute_operation
      355│             return 0
      356│ 
    → 357│         result: int = getattr(self, f"_execute_{method}")(operation)
      358│ 
      359│         if result != 0:

  6  /usr/local/lib/python3.10/site-packages/poetry/installation/executor.py:477 in _execute_install
      475│ 
      476│     def _execute_install(self, operation: Install | Update) -> int:
    → 477│         status_code = self._install(operation)
      478│ 
      479│         self._save_url_reference(operation)

  5  /usr/local/lib/python3.10/site-packages/poetry/installation/executor.py:515 in _install
      513│             archive = self._download_link(operation, Link(package.source_url))
      514│         else:
    → 515│             archive = self._download(operation)
      516│ 
      517│         operation_message = self.get_operation_message(operation)

  4  /usr/local/lib/python3.10/site-packages/poetry/installation/executor.py:709 in _download
      707│             self._yanked_warnings.append(message)
      708│ 
    → 709│         return self._download_link(operation, link)
      710│ 
      711│     def _download_link(self, operation: Install | Update, link: Link) -> Path:

  3  /usr/local/lib/python3.10/site-packages/poetry/installation/executor.py:737 in _download_link
      735│             self._write(operation, message)
      736│ 
    → 737│             archive = self._chef.prepare(archive, output_dir=output_dir)
      738│ 
      739│         self._populate_hashes_dict(archive, package)

  2  /usr/local/lib/python3.10/site-packages/poetry/installation/chef.py:107 in prepare
      105│             return self._prepare(archive, Path(tmp_dir), editable=editable)
      106│ 
    → 107│         return self._prepare_sdist(archive, destination=output_dir)
      108│ 
      109│     def _prepare(

  1  /usr/local/lib/python3.10/site-packages/poetry/installation/chef.py:188 in _prepare_sdist
      186│             destination.mkdir(parents=True, exist_ok=True)
      187│ 
    → 188│             return self._prepare(
      189│                 sdist_dir,
      190│                 destination,

  ChefBuildError

  Backend subprocess exited when trying to invoke get_requires_for_build_wheel
  
  Traceback (most recent call last):
    File "/usr/local/lib/python3.10/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/usr/local/lib/python3.10/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/usr/local/lib/python3.10/site-packages/pyproject_hooks/_in_process/_in_process.py", line 112, in get_requires_for_build_wheel
      backend = _build_backend()
    File "/usr/local/lib/python3.10/site-packages/pyproject_hooks/_in_process/_in_process.py", line 74, in _build_backend
      ep = os.environ['PEP517_BUILD_BACKEND']
    File "/usr/local/lib/python3.10/os.py", line 680, in __getitem__
      raise KeyError(key) from None
  KeyError: 'PEP517_BUILD_BACKEND'
  

  at /usr/local/lib/python3.10/site-packages/poetry/installation/chef.py:152 in _prepare
      148│ 
      149│                 error = ChefBuildError("\n\n".join(message_parts))
      150│ 
      151│             if error is not None:
    → 152│                 raise error from None
      153│ 
      154│             return path
      155│ 
      156│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with wget (3.2) not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pep517 "wget (==3.2)"'.
```

**Comment by mdagost** [comment]
I suspect that this is related to the timing of the release of pyproject-hooks 1.1.0: https://github.com/pypa/pyproject-hooks/issues/192

**Comment by mdagost** [comment]
Downgrading `pyroject-hooks` from 1.1.0 to 1.0.0 fixes this for me.

**Comment by mdagost** [comment]
I'll leave this issue open in case the change breaks anything in newer versions of poetry as well...

**Comment by mdagost** [comment]
Update: I believe the root cause is that 1.0.0 was locked in the poetry.lock file, but then poetry itself pulled in 1.1.0 when it was pip installed. So there was a conflict. Either downgrading to 1.0.0 after pip installing, or upgrading to 1.1.0 in the lock file fixes things for me.

**Comment by dimbleby** [comment]
> I believe the root cause is that 1.0.0 was locked in the poetry.lock file, but then poetry itself pulled in 1.1.0 when it was pip installed

https://python-poetry.org/docs/#installation please see the big red box

**Comment by rk-spirinova** [comment]
I'm still encountering the same issue, and I haven't utilized pyroject-hooks. This problem arose earlier today.

```
Step #0:     File "/usr/local/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 74, in _build_backend
Step #0:       ep = os.environ['PEP517_BUILD_BACKEND']
Step #0:            ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
Step #0:     File "<frozen os>", line 679, in __getitem__
Step #0:   KeyError: 'PEP517_BUILD_BACKEND'
Step #0:   
```

**Comment by dimbleby** [comment]
you'll want to provide a way to reproduce a problem if you hope for someone to look at it - typically a github repository and / or a dockerfile are good ways to demonstrate such things

**Comment by Secrus** [comment]
I can't reproduce it on the recent version of poetry. As dimbleby suggested, please provide reproduction steps.

**Comment by rk-spirinova** [comment]
hi @dimbleby ,
below is the dockefile
```
# Backend Dockerfile
FROM python:3.11-slim AS base

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY pyproject.toml poetry.lock ./
RUN pip install 'uvicorn[standard]'
RUN pip install --no-cache-dir poetry
RUN poetry config virtualenvs.create false && \
    poetry lock --no-update && \
    poetry install --no-dev --no-root

COPY . .

# Expose port
EXPOSE 8000

# Run the application
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

```

Changing virtualenvs.create from false to true resolves the issue, but during application runtime, it fails with a "modules not found" error. I suspect the virtual environment may not be activating properly

**Comment by Secrus** [comment]
@rk-spirinova we can't use this dockerfile without the actual project files. Right now this will fail on copying the `pyproject.toml` and `poetry.lock` files.

**Comment by rk-spirinova** [comment]
@Secrus , Until this morning, everything was running smoothly, but it suddenly ceased to function.

**Comment by dimbleby** [comment]
also you too are doing the thing that the [big red box](https://python-poetry.org/docs/#installation) tells you not to do

**Comment by rk-spirinova** [comment]
@dimbleby , @Secrus . After following the suggestion to set virtualenvs.create to true, the installation proceeded without any issues. However, a new problem arose where modules couldn't be found. I suspect this might be because the virtual environment isn't being activated. Could you assist in modifying the Dockerfile to address this?

**Comment by Gordon-BP** [comment]
I also ran into this issue, but changing `virtualenvs.create: false` to `true` in poetry config got it to build without error.

**Comment by helioLJ** [comment]
It happened to me too with 2 projects, I added this line in Dockerfile and it solved for me:

```Dockerfile
RUN pip install --no-use-pep517 pypika==0.48.9
```

**Comment by jcharaoui** [comment]
Same problem here: https://gitlab.torproject.org/tpo/web/donate-neo/-/jobs/540338

**Comment by mdagost** [comment]
Going to close this issue because the root root cause was managing poetry with the lockfile, which is no bueno.

**Comment by helioLJ** [comment]
> Going to close this issue because the root root cause was managing poetry with the lockfile, which is no bueno.

In my case, I was not managing the .lock file, and still got the same error of this thread.
I had to add those two lines to make it work: `RUN pip install --no-use-pep517 langdetect==1.0.9
RUN pip install --no-use-pep517 pypika==0.48.9`

```Dockerfile
FROM python:3.11

RUN mkdir app
COPY . /app
WORKDIR /app

RUN pip install poetry
RUN poetry config virtualenvs.create false
RUN pip install --no-use-pep517 langdetect==1.0.9
RUN pip install --no-use-pep517 pypika==0.48.9
RUN poetry install --no-dev
EXPOSE 3978
RUN chmod +x start_services.sh

ENTRYPOINT [ "./start_services.sh" ]
```

**Comment by jcharaoui** [comment]
Sharing here if it helps, but our solution was to remove `poetry-dotenv-plugin` from the project depenencies and regenerate the lockfile.

**Comment by dimbleby** [comment]
> In my case, I was not managing the .lock file

like everyone else who is hitting problems, you are ignoring the big warning telling you not to install poetry in the same environment as the project that poetry is managing

**Comment by david1542** [comment]
@rk-spirinova I also encountered the issue of "module not found". What worked for me what setting `poetry config virtualenvs.in-project true`. This is my Dockerfile:

```dockerfile
FROM python:3.10.5-slim

ENV NLTK_DATA=/tmp/nltk_cache

WORKDIR /app

RUN apt-get update \
    && apt-get install --no-install-recommends -y \
    build-essential
RUN pip install --no-cache-dir poetry==1.7.1

COPY pyproject.toml poetry.lock ./
RUN poetry config virtualenvs.create true && \
    poetry config virtualenvs.in-project true && \
    poetry install --no-root --no-dev --no-interaction

COPY . .

CMD ["poetry", "run", "python", "src/main.py"]
```

**Comment by rk-spirinova** [comment]
> @rk-spirinova I also encountered the issue of "module not found". What worked for me what setting `poetry config virtualenvs.in-project true`. This is my Dockerfile:
> 
> ```dockerfile
> FROM python:3.10.5-slim
> 
> ENV NLTK_DATA=/tmp/nltk_cache
> 
> WORKDIR /app
> 
> RUN apt-get update \
>     && apt-get install --no-install-recommends -y \
>     build-essential
> RUN pip install --no-cache-dir poetry==1.7.1
> 
> COPY pyproject.toml poetry.lock ./
> RUN poetry config virtualenvs.create true && \
>     poetry config virtualenvs.in-project true && \
>     poetry install --no-root --no-dev --no-interaction
> 
> COPY . .
> 
> CMD ["poetry", "run", "python", "src/main.py"]
> ```

I also added ["poetry", "run" ] and it is working.

**Comment by thomasl04wapo** [comment]
I was able to get around this problem by pinning the poetry version to 1.7.1 . I also am using `RUN poetry config virtualenvs.create false`. Using these commands for installing poetry seems to do the trick: 
``` dockerfile
RUN curl -sSL https://install.python-poetry.org | python3 - --version 1.7.1
ENV PATH="/root/.local/bin:$PATH"

RUN poetry config virtualenvs.create false && poetry install --no-interaction --no-ansi
```

**Comment by Ayan-Bandyopadhyay** [comment]
```Update: I believe the root cause is that 1.0.0 was locked in the poetry.lock file, but then poetry itself pulled in 1.1.0 when it was pip installed. So there was a conflict. Either downgrading to 1.0.0 after pip installing, or upgrading to 1.1.0 in the lock file fixes things for me.```

How did you upgrade in poetry.lock? Isn't that auto-generated? Did you edit pyproject.toml instead?
