### ISSUE TITLE
Adding configuration for using --lock by default

### ISSUE THREAD

**Issue by MartinEekGerhardsen** [python-poetry/poetry#9391]
### Issue Kind

Brand new capability

### Description

Add a boolean field `only-lock` to the configuration. By default, `only-lock = false`, and `poetry` behaves as today. If `only-lock = true`, then the `--lock` flag is applied to all relevant commands. 

### Impact

I work a lot with nix (specifically `poetry2nix`), and if I execute e.g. `poetry add numpy`, I would get errors as I try to add a package to a read-only environment. If the behaviour above is implemented, then the relevant `poetry` commands will only change the dependencies and lock-file, without installing packages. One may also imagine other situations where one would not instantly need to install a package, only note that it is one you need, so that in cases where several large packages are added one after another, you wouldn't need to wait for one to be installed to start adding the next. 

While one can imagine situations where this could be annoying (e.g. an environment that is not up-to-date), if this config is explicit then this would only be used when useful to the developer. 

### Workarounds

The simplest way is to always remember to add the `--lock` flag. Other workarounds could be to wrap the `poetry` command, e.g. like this: 
```bash
poetry-add() {
    poetry add "$@" --lock
}
```

**Comment by dimbleby** [comment]
this sounds undesirable for almost everyone.  How should poetry then be instructed that it _should_ install the packages after all, do we add yet another flag?

suggest this should be: thanks but no thanks, setting up your own shortcuts is the way to go

**Comment by MartinEekGerhardsen** [comment]
A simple solution would of course just be to toggle the behaviour of the `--lock` flag, though I don't think that's too much better of an idea.

I didn't think this was something that should be added either, as it was very specific. But as this was an issue I faced, I figured it would be better to document it in case others have the same annoyance. I'll close the issue for now.
