### ISSUE TITLE
SVN support

### ISSUE THREAD

**Issue by ashrasmun** [python-poetry/poetry#9401]
### Issue Kind

Brand new capability

### Description

Hey,

As per https://github.com/python-poetry/poetry/issues/4419, I'm posting just another request to add SVN support. SVN repos are supported with pip install and this seems like a regression when someone considers moving from using requirements.txt or just "naked" pip to poetry.

### Impact

Allow SVN users to work just like git ones.

### Workarounds

I need to checkout the repository locally and then point to the repository with 

```
[tool.poetry.dependencies]
some_repo = {path="checked_out_repo_location"}
```

**Comment by dimbleby** [comment]
this was more recently rejected at #2141

**Comment by Secrus** [comment]
There is close to no interest in SVN among Poetry users and it's surely not enough to excuse an additional maintenance overhead.
