### ISSUE TITLE
No module named 'packaging.metadata'

### ISSUE THREAD

**Issue by FelixBenning** [python-poetry/poetry#9406]
### Description

```shell
$ pipx uninstall poetry
Nothing to uninstall for poetry 😴
$ pipx install poetry
  installed package poetry 1.8.3, installed using Python 3.10.5
  These apps are now globally available
    - poetry
done! ✨ 🌟 ✨
$ poetry

No module named 'packaging.metadata'
```

### Workarounds

```shell

$ pipx install poetry==1.7
  installed package poetry 1.7.0, installed using Python 3.10.5
  These apps are now globally available
    - poetry
done! ✨ 🌟 ✨
$ poetry
Poetry (version 1.7.0)

...
```

### Poetry Installation Method

pipx

### Operating System

Red Hat Enterprise Linux 8.6 (Ootpa)

### Poetry Version

1.8.3

### Poetry Configuration

```bash session
Not really possible to do if the poetry command fails
```

### Poetry Runtime Logs

```bash session
-
```

**Comment by FelixBenning** [comment]
This is a duplicate of https://github.com/python-poetry/poetry/issues/9034#issue-2153769134 but that issue has been auto closed

**Comment by dimbleby** [comment]
poetry declares a dependency on `packaging>=23.1`, which provides `packaging.metadata`.

I don't know what is wrong with your install - you will have to investigate that yourself - but it seems likely that there is nothing more that can or should be done from this repository

**Comment by hxmn** [comment]
@FelixBenning  I came across this after a recent update to `oh-my-zsh`. The problem was that the `virtualenv-autodetect` plugin set the `PYTHONPATH` variable incorrectly. Disabling this plugin allowed me to continue working with poetry.
