### ISSUE TITLE
poetry show --why truncates columns if output is too wide

### ISSUE THREAD

**Issue by jclerman** [python-poetry/poetry#9414]
### Description

When running `poetry show -o --why` with a very wide console, I can see all (or most) of the output - that is, I can see lines like
```
twisted                       23.10.0      24.3.0      from daphne          An asynchronous networking framework wr...
```

However, if the console is too narrow, the last two columns are omitted altogether.

For my particular project, there is a long list of packages I install which all depend on one particular upstream package - so that package has a long list of items in the 4th ("from X") column, something like this, but much longer:

```
typing-extensions             4.8.0        4.11.0      from boto3-stubs,ddtrace,mypy-boto3-sns,mypy-boto3-sqs,psycopg,pydantic,pydantic-core,twisted
```

That list is never wrapped - so in my case, I need a console-width of nearly 400 columns before I can avoid loss of the last 2 columns.  There is also no way (that I can see) to omit the package-summary (5th column), which exacerbates this issue.

It would be great if poetry warned (via output to STDERR?) that columns were being omitted when running `poetry show` - and also if the list of packages that require the package in question were wrapped if there wasn't enough room to show them on one line.

### Workarounds

I can do things like `COLUMNS=380 poetry show -o --why`.  Pretty sub-optimal.

### Poetry Installation Method

install.python-poetry.org

### Operating System

MacOS 13.6.6

### Poetry Version

Poetry (version 1.7.1)

### Poetry Configuration

```bash session
cache-dir = "/Users/xxx/Library/Caches/pypoetry"
experimental.system-git-client = false
installer.max-workers = null
installer.modern-installation = true
installer.no-binary = null
installer.parallel = true
virtualenvs.create = true
virtualenvs.in-project = null
virtualenvs.options.always-copy = false
virtualenvs.options.no-pip = false
virtualenvs.options.no-setuptools = false
virtualenvs.options.system-site-packages = false
virtualenvs.path = "{cache-dir}/virtualenvs"
virtualenvs.prefer-active-python = false
virtualenvs.prompt = "{project_name}-py{python_version}"
warnings.export = true
```

### Poetry Runtime Logs

```bash session
there is nothing in those logs that shows anything about how output is being formatted on the screen - just lines like:

Source (PyPI): 2 packages found for twisted >=23.10.0
```
```

**Comment by dimbleby** [comment]
Duplicate #2880.

Plainly that one is pretty old and no-one has felt the need to do anything about it: if this is important to you then recommend you will want to do it yourself.
