### ISSUE TITLE
force revalidate cache when package with version not found in cache/

### ISSUE THREAD

**Issue by trim21** [python-poetry/poetry#9421]
### Issue Kind

Brand new capability

### Description

I have a package A and package B require A. When I publish a new version of package `A@x.y.z`, I may run `poetry add A@x.y.z` in B. And if A is not published yet, versions of A is cached.

After A is published, when I run `poetry add `A@x.y.z` again, poetry still try to find result from cache, so it raise a error that `A@x.y.z` not found.

Hope in this case poetry could revalidate cache.

### Impact

not sure

### Workarounds

clear all cache, but too much.

**Comment by dimbleby** [comment]
of course poetry is already capable of finding new releases, this is a main line case

I expect what you are seeing is simply that it is respecting cache expiry headers as set by pypi, these should be quite short

if you are impatient there is always `--no-cache`.

no change needed

**Comment by trim21** [comment]
thanks
