### ISSUE TITLE
poetry run pydoc doesn't work for installed libraries

### ISSUE THREAD

**Issue by dimaqq** [python-poetry/poetry#943]
`poetry run pip freeze | grep requests` confirms that requests are installed.
`poetry run pydoc requests` tells me `no Python documentation found for 'requests'`

I suspect that's a virtualenv/venv bug of not installing `pydoc` in `bin/`

**Comment by dimaqq** [comment]
I’m pretty sure this still sucks

**Comment by cazador481** [comment]
Looks like you can do 
`poetry run python -m pydoc <package>` to be able to get pydoc to work.  any chance of adding a poetry command that would wrap pydoc

Also here is the link to the venv issue.  https://github.com/pypa/virtualenv/issues/149

**Comment by finswimmer** [comment]
Hello,

according to the link provided by @cazador481 this doesn't seem to be a poetry issue. That's why I'm closing this for now. If you disagree please leave a comment.

fin swimmer
