### ISSUE TITLE
Files cannot be accessed when outside of the directory that pyproject.toml resides in

### ISSUE THREAD

**Issue by novialriptide** [python-poetry/poetry#9488]
### Issue Kind

Change in current behaviour

### Description

Hi Poetry team!

I am currently in the process of migrating an old project (from 2015) to use Poetry to manage our dependencies and build system. Here is the current repository root directory.

```
backend/pyproject.toml
backend/Dockerfile
frontend/Dockerfile
frontend/...
README.md
docker-compose.yml
```

When setting the readme value to `"../README.md"` in `pyproject.toml`, I get this error:
```
'/Users/novial/Documents/gitprojects/shrunk/README.md' is not in the subpath of '/Users/novial/Documents/gitprojects/shrunk/backend'
```

I assume this is a security implementation.

### Impact

This would help others trying to setup their project using Docker.

### Workarounds

I could move the `README.md` to the `backend` directory, but I don't think that's optimal.

**Comment by dimbleby** [comment]
previously rejected at #5960.  You should move the file.
