### ISSUE TITLE
cache:clear - Add automatic yes option

### ISSUE THREAD

**Issue by fruffy** [python-poetry/poetry#949]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Feature Request

 I have a script which requires me to clear the poetry cache every time I run it because of wonky dependency resolution. 
Currently there does not seem to be any way to pipe "yes" into the cache:clear command and I have to insert the command manually, which is a bit tedious. 
It would be nice to add a flag which automatically passes the option without requiring user input. I have not found anything in the documentation or issues regarding this topic.

**Comment by j178** [comment]
Currently there is a `-n (--no-interaction)` global option, when passed, questions that require user interaction will use its default answer, which is `False` according to this line  [L142](https://github.com/sdispater/cleo/blob/master/cleo/commands/command.py#L142).  
May be we should add another global option to set the default value for `--no-iteraction` ?

**Comment by fruffy** [comment]
Ah this is already quite useful! Yes, it would be nice to allow --no-interaction to specify the default value.

**Comment by fruffy** [comment]
I think this is still something that may be useful, but I do not have the time to submit a pull request.

**Comment by callahad** [comment]
`yes | poetry cache clear --all pypi` works for me on `1.0.0b8` (though it does leave behind an empty `pypoetry/cache/repositories/pypi` folder)

**Comment by fruffy** [comment]
Just tried and it works, thanks for the update!
