### ISSUE TITLE
poetry install Found 0 compatible packages but pip install works well

### ISSUE THREAD

**Issue by candowu** [python-poetry/poetry#9494]
### Description

[urllib3:urllib3.connectionpool] http://pypi.xxx.com:80 "GET /root/pypi/flake8/ HTTP/1.1" 200 28517
Source (foo): 0 packages found for flake8 *
Falling back to installed packages to discover metadata for flake8
Found 0 compatible packages for flake8

pip install flake8
Looking in indexes: http://pypi.xxx.com/root/pypi
Collecting flake8
  Downloading http://pypi.xxx.com/root/pypi/%2Bf/2e4/16edcc62471a6/flake8-7.1.0-py2.py3-none-any.whl (57 kB)
     ---------------------------------------- 57.6/57.6 kB 606.8 kB/s eta 0:00:00
Collecting mccabe<0.8.0,>=0.7.0 (from flake8)
  Downloading http://pypi.xxx.com/root/pypi/%2Bf/6c2/d30ab6be0e4a4/mccabe-0.7.0-py2.py3-none-any.whl (7.3 kB)
Collecting pycodestyle<2.13.0,>=2.12.0 (from flake8)
  Downloading http://pypi.xxx.com/root/pypi/%2Bf/949/a39f6b86c3e15/pycodestyle-2.12.0-py2.py3-none-any.whl (31 kB)
Collecting pyflakes<3.3.0,>=3.2.0 (from flake8)
  Downloading http://pypi.xxx.com/root/pypi/%2Bf/84b/5be138a2dfbb4/pyflakes-3.2.0-py2.py3-none-any.whl (62 kB)
     ---------------------------------------- 62.7/62.7 kB 1.7 MB/s eta 0:00:00
Installing collected packages: pyflakes, pycodestyle, mccabe, flake8
Successfully installed flake8-7.1.0 mccabe-0.7.0 pycodestyle-2.12.0 pyflakes-3.2.0

### Workarounds

NO

### Poetry Installation Method

pip

### Operating System

windows 10

### Poetry Version

3.11.9

### Poetry Configuration

```bash session
poetry config --list
cache-dir = "C:\\Users\\user_name\\AppData\\Local\\pypoetry\\Cache"
experimental.system-git-client = false
installer.max-workers = null
installer.modern-installation = true
installer.no-binary = null
installer.parallel = true
keyring.enabled = true
repositories.foo.url = "http://pypi.xxx.com/root/pypi"
solver.lazy-wheel = true
virtualenvs.create = true
virtualenvs.in-project = null
virtualenvs.options.always-copy = false
virtualenvs.options.no-pip = false
virtualenvs.options.no-setuptools = false
virtualenvs.options.system-site-packages = false
virtualenvs.path = "{cache-dir}\\virtualenvs"  # C:\Users\user_name\AppData\Local\pypoetry\Cache\virtualenvs
virtualenvs.prefer-active-python = false
virtualenvs.prompt = "{project_name}-py{python_version}"
warnings.export = true
```

### Poetry Runtime Logs

```bash session
Checking if keyring is available
[keyring:keyring.backend] Loading KWallet
[keyring:keyring.backend] Loading SecretService
[keyring:keyring.backend] Loading Windows
[win32ctypes:win32ctypes.core.ctypes] Loaded ctypes backend
[keyring:keyring.backend] Loading chainer
[keyring:keyring.backend] Loading libsecret
[keyring:keyring.backend] Loading macOS
Using keyring backend 'Windows WinVaultKeyring'
Creating new session for pypi.xxx.com
[urllib3:urllib3.connectionpool] Starting new HTTP connection (1): pypi.xxx.com:80
[urllib3:urllib3.connectionpool] http://pypi.xxx.com:80 "GET /root/pypi/pytest-xdist/ HTTP/1.1" 200 23759
Source (foo): 0 packages found for pytest-xdist *
Falling back to installed packages to discover metadata for pytest-xdist
Found 0 compatible packages for pytest-xdist
[urllib3:urllib3.connectionpool] http://pypi.xxx.com:80 "GET /root/pypi/pytest-recording/ HTTP/1.1" 200 12084
Source (foo): 0 packages found for pytest-recording *
Falling back to installed packages to discover metadata for pytest-recording
Found 0 compatible packages for pytest-recording
[urllib3:urllib3.connectionpool] http://pypi.xxx.com:80 "GET /root/pypi/pytest-mock/ HTTP/1.1" 200 22158
Source (foo): 0 packages found for pytest-mock *
Falling back to installed packages to discover metadata for pytest-mock
Found 0 compatible packages for pytest-mock
[urllib3:urllib3.connectionpool] http://pypi.xxx.com:80 "GET /root/pypi/pytest-integration/ HTTP/1.1" 200 7945
Source (foo): 0 packages found for pytest-integration *
```

**Comment by nbaju1** [comment]
Have you configured the credentials for the `foo` source? Ref: https://python-poetry.org/docs/repositories/#private-repository-example

**Comment by candowu** [comment]
I have found the cause of the problem, which is caused by the incorrect address of the source I configured.
