### ISSUE TITLE
Main dependency shadows dev-dependency of local package

### ISSUE THREAD

**Issue by DivyanshuBhoyar** [python-poetry/poetry#9497]
##### Main dependencies:
![image](https://github.com/python-poetry/poetry/assets/64900631/3b1a831b-7963-40a2-8dfc-b05d036069b1)

##### Dev dependencies:
![image](https://github.com/python-poetry/poetry/assets/64900631/70e5d504-e8d1-4f28-9f7a-231ae646269a)

#### My usecase is:
*In prod* i run, `poetry install --no-dev`
*In local development*: `poetry install`

but it installs the package in non editable mode. I have tried `--dev-only` but it removes the main dependencies.
Is this expected?
### Workarounds

-

### Poetry Installation Method

install.python-poetry.org

### Operating System

Ubuntu 22.04

### Poetry Version

1.6.1

### Poetry Configuration

```bash session
-
```

### Python Sysconfig

```bash session
-
```

### Example pyproject.toml

```TOML
-
```

### Poetry Runtime Logs

```bash session
-
```

**Comment by finswimmer** [comment]
Hey @DivyanshuBhoyar,

please have a look at this discussion: https://github.com/orgs/python-poetry/discussions/3646

fin swimme
