### ISSUE TITLE
Leading zeros in version are removed when building wheels 

### ISSUE THREAD

**Issue by andrearossiavanade** [python-poetry/poetry#9508]
### Description

`poetry build` does not respect leading zeros.

$ `poetry --version`
Poetry (version 1.8.3)
$ `poetry version 2024.06.20.9+test`
Bumping version from 2024.06.20.9+test to 2024.06.20.9+test
$ `poetry build`
Building test (2024.06.20.9+test)
  - Building sdist
  - Built test-2024.6.20.9+test.tar.gz
  - Building wheel
  - Built test-2024.6.20.9+test-py3-none-any.whl

This issue https://github.com/python-poetry/poetry/issues/3705 is similar, but the fix does not completely solve it

### Workarounds

Unfortunately not found

### Poetry Installation Method

pipx

### Operating System

Endeavour OS WSL

### Poetry Version

1.8.3

### Poetry Configuration

```bash session
experimental.system-git-client = false
installer.max-workers = null
installer.modern-installation = true
installer.no-binary = null
installer.parallel = true
keyring.enabled = true
solver.lazy-wheel = true
virtualenvs.create = true
virtualenvs.in-project = true
virtualenvs.options.always-copy = false
virtualenvs.options.no-pip = false
virtualenvs.options.no-setuptools = false
virtualenvs.options.system-site-packages = false
virtualenvs.path = "{cache-dir}/virtualenvs"  # /home/user/.cache/pypoetry/virtualenvs
virtualenvs.prefer-active-python = false
virtualenvs.prompt = "{project_name}-py{python_version}"
warnings.export = true
```

### Poetry Runtime Logs

```bash session
Loading configuration file /home/user/.config/pypoetry/config.toml
Using virtualenv: /home/user/Documents/sandbox_wheel/.venv
Building test (2024.06.20.9+test)
  - Building sdist
  - Built test-2024.6.20.9+test-py3-none-any.whl
```

**Comment by Secrus** [comment]
This is working as intended. The package version is normalized according to PEP 440 rules, in this case: [integer normalization](https://peps.python.org/pep-0440/#integer-normalization).
