### ISSUE TITLE
Poetry doesn't install

### ISSUE THREAD

**Issue by ilusha0561** [python-poetry/poetry#9512]
### Description

help

### Workarounds

--

### Poetry Installation Method

pip

### Operating System

ubuntu

### Poetry Version

1.7.0

### Poetry Configuration

```bash session
dockerfile
FROM python:3.11
ENV PYTHONUNBUFFERED 1
WORKDIR /usr/local/src/project


RUN apt-get update && \
    apt-get install -y locales python3-dev libldap2-dev libffi-dev libsasl2-dev libssl-dev librdkafka-dev wkhtmltopdf git && \
    echo ru_RU.UTF-8 UTF-8 >> /etc/locale.gen && \
    locale-gen


RUN python -m pip install --upgrade pip && \
    pip install poetry==1.7.0 && \
    poetry config virtualenvs.create false


COPY pyproject.toml poetry.toml /usr/local/src/project/


RUN ls -al /usr/local/src/project


RUN poetry install --no-root


COPY . /usr/local/src/project/

RUN mkdir -p /app/wps_project/static && \
    python manage.py collectstatic --noinput

CMD python manage.py migrate && /usr/local/bin/gunicorn --config /app/conf.py wps_project.wsgi:application -b :80
```

### Example pyproject.toml

```TOML
[tool.poetry]
name = "SM SP"
description = "SM SP"
homepage = "https://git.omega-r.club/SM_SP/project.git"
repository = "https://git.omega-r.club/SM_SP/project.git"
version = "0.0.1"
authors = []

[tool.poetry.dependencies]

python = "^3.11"
Django = "4.1.7"
psycopg2-binary = "2.9.3"
djangorestframework = "3.14.0"
dj-database-url = "0.5.0"
django-extensions = "3.2.1"
django-filter = "22.1"
djangorestframework-camel-case = "1.3.0"
ipython = "8.4.0"
gunicorn = "19.9.0"
uvicorn = "0.20.0"
Werkzeug = "0.15.4"
whitenoise = "4.1.3"
requests = "2.28.1"
django-ordered-model = "3.6"
django-safedelete = "1.3.0"

celery = "5.2.7"
django-celery-beat = "2.4.0"
flower = "1.0.0"
sentry-sdk = "0.10.2"
django-import-export = "3.3.6"
python-dateutil = "2.8.1"
semantic-version = "2.8.4"
djangorestframework-simplejwt = "4.7.2"
openpyxl = "3.0.7"
django-simple-history = "^3.2.0"
drf-yasg = "1.21.4"
coverage = "5.2.1"
django-mptt = "0.14.0"
xlrd = "1.2.0"
xlsxwriter = "1.3.6"
tablib = "3.5.0"

django-guardian = "2.3.0"
django-fsm = "2.8.1"
django-nested-inline = "0.4.5"
typing_extensions = "3.7.4.3"
Pillow = "8.0.1"
transliterate = "1.10.2"
html-sanitizer = "1.9.1"

django-prometheus = "^2.2.0"
django-admin-inline-paginator = "0.3.0"
pydantic = "1.9.1"
boto3 = "1.26.36"
django-storages = "1.13.2"
django-redis = "5.0.0"
python-json-logger = "2.0.2"
pymupdf = "1.21.1"
qrcode = "7.3.1"
imgkit = "1.2.2"
webdavclient3 = "3.14.6"
dependency-injector = "4.41.0"
django-admin-autocomplete-filter = "0.7.1"
fs = "2.4.15"
channels = "4.0.0"
channels-redis = "4.0.0"
django-guid = "3.2.1"
cachetools = "5.2.0"
django-sql-explorer = "2.5"
python-slugify = "6.1.2"
django-rest-framework-proxy = "1.6.0"
posthog = "2.2.0"

pytest-django = "4.5.2"
pytest = "7.2.0"
pytest-cov = "4.0.0"
pytest-xdist = "3.1.0"

aiokafka = { extras = ["zstd"], version = "*" }

django-schema-graph = "2.2.1"


django-gantt = { git = "https://git.omega-r.club/SM_SP/project.git", branch = "Backend" }
django-ckeditor = "^6.7.0"
django-crum = "^0.7.9"
black = "^23.9.1"
striprtf = "^0.0.26"
django-pivot = "^1.10.0"
django-instant = "^4.2.0"
psycogreen = "^1.0.2"
gevent = "^23.9.1"
psycopg2 = "^2.9.9"
django-json-widget = "^1.1.1"

[tool.poetry.group.dev.dependencies]
ruff = "^0.0.194"
isort = "^5.11.4"
pycln = "^2.1.2"

[tool.ruff]
target-version = "py311"
line-length = 100

select = [
    "F",
    "E",
    "W",
    "C90",
    "I",
    #    "D", Док-строки
    #    "UP",
    "N",
    "YTT",
    #    "ANN", Аннотация типов, по хорошему включить хотябы для публичных методов
    "S",
    "BLE",
    "FBT",
    "B",
    #    "A", Совпадение имен с встроенными типами, в models и serializers часто используются id
    "C4",
    "T10",
    #    "EM",
    "ICN",
    "T20",
    "Q",
    "RET",
    "SIM",
    "TID",
    #    "ARG", Неиспользуемые аргументы
    #    "DTZ",
    "ERA",
    "PGH",
    "PLC",
    "PLE",
    "PLR",
    "PLW",
    "RUF",
]

ignore = [
    "RUF001",
    "RUF002",
    "RUF003",
    "ANN101", # Аннотация типов для self
    "Q000", # Двоные кавычки, решается в black
    "FBT001", # Boolean default value in function definition
    "FBT002", # Boolean positional value in function call
]

per-file-ignores = { "__init__.py" = ["F401"] }

fix = false

# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
    "migrations",
    "tests", # TODO: Обсудить
    # autogenerated code
    "bim360_client",
    "pdfy_client",
    # ignore settings
    "wps_project/settings.py",
    "wps_project/ckeditor_settings.py",
    "wps_project/summernote_settings.py",
    # redundant, not using
    "project/services/task_dux_sync_service.py",
]

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.mccabe]
max-complexity = 15

[tool.isort]
multi_line_output = 3
py_version = 311
profile = "black"
line_length = 100
skip = [
    "__pycache__",
    "migrations",
]

[tool.pycln]
all = true
quiet = true
exclude = "bim360_client|pdfy_client|migrations|__init__.py|settings.py|tests"

[tool.black]
line-length = 120
target-version = ['py311']
exclude = '''
/(
  |\.idea
  |\.pyc
  |\.pyi
  |migrations
  |manage\.py
)/
'''
```

### Poetry Runtime Logs

```bash session
#59 [celery 6/9] RUN ls -al /usr/local/src/project
13:35:29   #59 0.417 total 12
13:35:29   #59 0.417 drwxr-xr-x 1 root root   47 Jun 21 10:35 .
13:35:29   #59 0.417 drwxr-xr-x 1 root root   21 Jun 21 10:20 ..
13:35:29   #59 0.417 -rw-r--r-- 1 root root   26 Jun 20 07:14 poetry.toml
13:35:29   #59 0.417 -rw-r--r-- 1 root root 4646 Jun 21 10:18 pyproject.toml
13:35:29   #59 DONE 0.5s
13:35:29   
13:35:29   #60 [app 7/9] RUN poetry install --no-root
13:35:30   #60 0.712 Skipping virtualenv creation, as specified in config file.
13:35:30   #60 0.800 Updating dependencies
13:35:30   #60 0.800 Resolving dependencies...
13:35:37   #60 7.232
13:35:37   #60 7.232 Unable to determine package info for path: /usr/local/src/project
13:35:37   #60 7.232
13:35:37   #60 7.232 Command ['/tmp/tmpwpng0bse/.venv/bin/python', '-m', 'pip', 'install', '--disable-pip-version-check', '--ignore-installed', '--no-input', 'build==1.0.3', 'pyproject_hooks==1.0.0'] errored with the following return code 1
13:35:37   #60 7.232
13:35:37   #60 7.232 Output:
13:35:37   #60 7.232 Traceback (most recent call last):
13:35:37   #60 7.232   File "<frozen runpy>", line 198, in _run_module_as_main
13:35:37   #60 7.232   File "<frozen runpy>", line 88, in _run_code
13:35:37   #60 7.232   File "/tmp/tmpwpng0bse/.venv/lib/python3.11/site-packages/pip/__main__.py", line 8, in <module>
13:35:37   #60 7.232     if sys.path[0] in ("", os.getcwd()):
13:35:37   #60 7.232                            ^^^^^^^^^^^
13:35:37   #60 7.232 FileNotFoundError: [Errno 2] No such file or directory
13:35:37   #60 7.232
13:35:37   #60 7.232 No fallback setup.py file was found to generate egg_info.
13:35:37   #60 ERROR: process "/bin/sh -c poetry install --no-root" did not complete successfully: exit code: 1
13:35:37   ------
13:35:37    > [app 7/9] RUN poetry install --no-root:
13:35:37   7.232 Output:
13:35:37   7.232 Traceback (most recent call last):
13:35:37   7.232   File "<frozen runpy>", line 198, in _run_module_as_main
```

**Comment by dimbleby** [comment]
> 13:35:37   #60 7.232     if sys.path[0] in ("", os.getcwd()):
> 13:35:37   #60 7.232                            ^^^^^^^^^^^
> 13:35:37   #60 7.232 FileNotFoundError: [Errno 2] No such file or directory

this is going to be a problem with your dockerfile and not with poetry

**Comment by ilusha0561** [comment]
#59 [app 7/9] RUN poetry install --no-root
13:49:15   #59 0.808 Skipping virtualenv creation, as specified in config file.
13:49:15   #59 0.901 Updating dependencies
13:49:15   #59 0.901 Resolving dependencies...
13:49:22   #59 7.222
13:49:22   #59 7.222 Unable to determine package info for path: /usr/local/src/project
13:49:22   #59 7.222
13:49:22   #59 7.222 Command ['/tmp/tmp6me8g_3e/.venv/bin/python', '-m', 'pip', 'install', '--disable-pip-version-check', '--ignore-installed', '--no-input', 'build==1.0.3', 'pyproject_hooks==1.0.0'] errored with the following return code 1
13:49:22   #59 7.222
13:49:22   #59 7.222 Output:
13:49:22   #59 7.222 Traceback (most recent call last):
13:49:22   #59 7.222   File "<frozen runpy>", line 198, in _run_module_as_main
13:49:22   #59 7.222   File "<frozen runpy>", line 88, in _run_code
13:49:22   #59 7.222   File "/tmp/tmp6me8g_3e/.venv/lib/python3.11/site-packages/pip/__main__.py", line 8, in <module>
13:49:22   #59 7.222     if sys.path[0] in ("", os.getcwd()):
13:49:22   #59 7.222                            ^^^^^^^^^^^
13:49:22   #59 7.222 FileNotFoundError: [Errno 2] No such file or directory
13:49:22   #59 7.222
13:49:22   #59 7.222 No fallback setup.py file was found to generate egg_info.
13:49:22   #59 ERROR: process "/bin/sh -c poetry install --no-root" did not complete successfully: exit code: 1
13:49:22   failed to solve: process "/bin/sh -c poetry install --no-root" did not complete successfully: exit code: 1
13:49:22   ------
13:49:22    > [flower 7/9] RUN poetry install --no-root:
13:49:22   7.222 Output:
13:49:22   7.222 Traceback (most recent call last):
13:49:22   7.222   File "<frozen runpy>", line 198, in _run_module_as_main
13:49:22   7.222   File "<frozen runpy>", line 88, in _run_code
13:49:22   7.222   File "/tmp/tmp6me8g_3e/.venv/lib/python3.11/site-packages/pip/__main__.py", line 8, in <module>
13:49:22   7.222     if sys.path[0] in ("", os.getcwd()):
13:49:22   7.222                            ^^^^^^^^^^^
13:49:22   7.222 FileNotFoundError: [Errno 2] No such file or directory

**Comment by ilusha0561** [comment]
full logs

**Comment by dimbleby** [comment]
> django-gantt = { git = "https://git.omega-r.club/SM_SP/project.git", branch = "Backend" }

looks like nonsense?

**Comment by ilusha0561** [comment]
yes

**Comment by ilusha0561** [comment]
https://git.omega-r.club/SM_SP/project/-/blob/Backend/django-gantt.git ?

**Comment by ilusha0561** [comment]
django-gantt = { git = "https://git.omega-r.club/SM_SP/project/-/blob/main/django-gantt.git?ref_type=heads" }

**Comment by ilusha0561** [comment]
#60 [flower 7/9] RUN poetry install --no-root
16:32:36   #60 0.757 Skipping virtualenv creation, as specified in config file.
16:32:36   #60 0.927 Updating dependencies
16:32:36   #60 0.927 Resolving dependencies...
16:32:37   #60 1.776
16:32:37   #60 1.776 Redirected from URL https://git.omega-r.club/SM_SP/project/-/blob/main/django-gantt.git/info/refs?service=git-upload-pack to URL https://git.omega-r.club/SM_SP/project/-/tree/main without info/refs?service=git-upload-pack
16:32:37   #60 ERROR: process "/bin/sh -c poetry install --no-root" did not complete successfully: exit code: 1
16:32:37   ------
16:32:37    > [celery_beat 7/9] RUN poetry install --no-root:
16:32:37   0.757 Skipping virtualenv creation, as specified in config file.
16:32:37   0.927 Updating dependencies
16:32:37   0.927 Resolving dependencies...
16:32:37   1.776
16:32:37   1.776 Redirected from URL https://git.omega-r.club/SM_SP/project/-/blob/main/django-gantt.git/info/refs?service=git-upload-pack to URL https://git.omega-r.club/SM_SP/project/-/tree/main without info/refs?service=git-upload-pack
16:32:37   ------
16:32:37   failed to solve: process "/bin/sh -c poetry install --no-root" did not complete successfully: exit code: 1
16:32:37   Process exited with code 17
16:32:37   Process exited with code 17 (Step: Build and Deploy (Command Line))
16:32:37   Step Build and Deploy (Command Line) failed
16:32:37 Stopping performance monitoring process
16:32:41 Performance monitoring process stopped
16:32:41 Publishing performance monitoring build stages data

**Comment by ilusha0561** [comment]
help lpease

**Comment by dimbleby** [comment]
read the docs https://python-poetry.org/docs/dependency-specification/#git-dependencies

**Comment by ilusha0561** [comment]
[image: image.png]
I do the same as in the documentation

пт, 21 июн. 2024 г. в 19:04, David Hotham ***@***.***>:

**Comment by ilusha0561** [comment]
[image: image.png]
docker :
FROM python:3.11
ENV PYTHONUNBUFFERED 1
WORKDIR /usr/local/src/project

# Установка необходимых пакетов
RUN apt-get update && \
apt-get install -y locales python3-dev libldap2-dev libffi-dev libsasl2-dev
libssl-dev librdkafka-dev wkhtmltopdf && \
echo ru_RU.UTF-8 UTF-8 >> /etc/locale.gen && \
locale-gen

# Установка pip и poetry
RUN python -m pip install --upgrade pip && \
pip install poetry==1.7.0 && \
poetry config virtualenvs.create false

# Копирование файлов pyproject.toml и poetry.toml
COPY pyproject.toml poetry.toml /usr/local/src/project/

COPY django-gantt.git /usr/local/src/project/django-gantt.git

# Вывод содержимого директории для отладки
RUN ls -al /usr/local/src/project

# Установка зависимостей
RUN poetry install --no-root

# Копирование остальных файлов проекта
COPY . /usr/local/src/project/

# Сборка статических файлов
RUN mkdir -p /app/wps_project/static && \
python manage.py collectstatic --noinput

# Команда для запуска приложения
CMD python manage.py migrate && /usr/local/bin/gunicorn --config
/app/conf.py wps_project.wsgi:application -b :80

django-gantt = { path = "django-gantt.git" }

пт, 21 июн. 2024 г. в 19:39, Ilya Nosalskiy ***@***.***>:

**Comment by ilusha0561** [comment]
What am I doing wrong

пт, 21 июн. 2024 г., 19:50 Ilya Nosalskiy ***@***.***>:

**Comment by ilusha0561** [comment]
Help please

пт, 21 июн. 2024 г., 23:12 Ilya Nosalskiy ***@***.***>:

**Comment by ilusha0561** [comment]
Help please

сб, 22 июн. 2024 г., 08:42 Ilya Nosalskiy ***@***.***>:

**Comment by ilusha0561** [comment]
logs
   > [app  9/11] RUN poetry install --no-root:
10:58:01   0.688 Skipping virtualenv creation, as specified in config file.
10:58:01   0.788 Updating dependencies
10:58:01   0.788 Resolving dependencies...
10:58:01   0.792
10:58:01   0.792 file could not be opened successfully:
10:58:01   0.792 - method gz: ReadError('not a gzip file')
10:58:01   0.792 - method bz2: ReadError('not a bzip2 file')
10:58:01   0.792 - method xz: ReadError('not an lzma file')
10:58:01   0.792 - method tar: ReadError('invalid header')
10:58:01   ------
10:58:01   failed to solve: process "/bin/sh -c poetry install --no-root"
did not complete successfully: exit code: 1
10:58:01   Process exited with code 17
10:58:01   Process exited with code 17 (Step: Build and Deploy (Command
Line))
10:58:01   Step Build and Deploy (Command Line) failed


dockerfile
FROM python:3.11
ENV PYTHONUNBUFFERED 1
WORKDIR /usr/local/src/project
# Установка необходимых пакетов
RUN apt-get update && \
apt-get install -y locales python3-dev libldap2-dev libffi-dev libsasl2-dev
libssl-dev librdkafka-dev wkhtmltopdf && \
echo ru_RU.UTF-8 UTF-8 >> /etc/locale.gen && \
locale-gen
# Установка pip и poetry
RUN python -m pip install --upgrade pip && \
pip install poetry && \
poetry config virtualenvs.create false
# Копирование файлов pyproject.toml и poetry.toml
COPY pyproject.toml poetry.toml /usr/local/src/project/
COPY django-gantt.git /usr/local/src/project/django-gantt
# Вывод содержимого директории для отладки
RUN ls -al /usr/local/src/project
RUN find /usr/local/src/project -type d -exec chmod 755 {} \; && \
find /usr/local/src/project -type f -exec chmod 644 {} \;
# Установка зависимостей
RUN poetry install --no-root
# Копирование остальных файлов проекта
COPY . /usr/local/src/project/
# Сборка статических файлов
RUN mkdir -p /app/wps_project/static && \
python manage.py collectstatic --noinput
# Команда для запуска приложения
CMD python manage.py migrate && /usr/local/bin/gunicorn --config
/app/conf.py wps_project.wsgi:application -b :80
toml django-gantt = { path = "./django-gantt" }

вс, 23 июн. 2024 г. в 11:00, Ilya Nosalskiy ***@***.***>:

**Comment by ilusha0561** [comment]
help please

пн, 24 июн. 2024 г. в 11:21, Ilya Nosalskiy ***@***.***>:

**Comment by finswimmer** [comment]
Hello,

you haven't come back to this issue for a long while. So I assume this is solved in the meantime and I can close this ticket.

Feel free to leave a comment if you disagree.

fin swimmer
