### ISSUE TITLE
In the docs about clearing the cache, pypi is in lowercase (does not work)

### ISSUE THREAD

**Issue by kmille** [python-poetry/poetry#9516]
### Issue Kind

Improving documentation

### Existing Link

https://python-poetry.org/docs/cli/#cache-clear

### Description

to reproduce: 
1) go there: https://python-poetry.org/docs/cli/#cache-clear
2) You will find `poetry cache clear pypi --all`
3) On my (Arch Linux), it's not called pypi. Instead it's named PyPI

The command with the lower case pypi fails. If it's PyPI on all systems, I recommend updating the docs.

```
kmille@linbox:~ ls ~/.cache/pypoetry/cache/repositories
total 20K
drwxr-xr-x   5 kmille kmille 4.0K Jun 25 22:23 .
drwxr-xr-x   3 kmille kmille 4.0K Dec 27  2022 ..
drwxr-xr-x 207 kmille kmille 4.0K Jun 25 20:11 PyPI
drwxr-xr-x   3 kmille kmille 4.0K Dec 27  2022 _default_cache
```

The `pypi` in the command needs to have the same syntax/case like the directory. The question is if others have also `PyPI` or am I the only one.

Just my 2 cents.

**Comment by Karelaking** [comment]
I does not have linux that's why I can not test it on linux. But I tried PyPi in windows in place of pypi and it is working properly. So yah we can change it in the docs.  does any one else tried this on linux
