### ISSUE TITLE
Support for data_files (peoblix is not maintained anymore)

### ISSUE THREAD

**Issue by faxm0dem** [python-poetry/poetry#9519]
### Issue Kind

Other

### Description

We would like to ship data files (config files, resources) in our packages.
This was possible with setuptools, and lately with the unmainained [poeblix](/spoorn/poeblix) (See also #890).

### Impact

This would allow many users (see #890) to ship external files with the generated packages.

### Workarounds

Today either we can use an older version of poetry with poeblix plugin, or ship data files in a separate package.

**Comment by dimbleby** [comment]
This is an anti-pattern, explicitly anti-recommended by pypa and deprecated at setuptools.  I doubt that poetry should be adding_support for this.

Originally #890, more recently #8867
