### ISSUE TITLE
Support for --only-root in pyproject.toml

### ISSUE THREAD

**Issue by shahar-gamliel** [python-poetry/poetry#9530]
### Issue Kind

Change in current behaviour

### Description

`--only-root`, the equivalent of `--no-deps` was introduced to the cli in https://github.com/python-poetry/poetry/pull/5783.
It would be nice if I'd be able to use it in pyproject.toml.
I tried to look it up in the docs, but found no reference. Sorry in advance if this is already possible.

### Impact

Use cases are the same use cases for using `--only-root`.
Personally for me, I'm trying to install a package with dependencies that are too strict, and I made sure that I'm able to install only the package's root.

### Workarounds

A workaround is to run 2 commands separately:
1. poetry install
2. poetry install <package> --only-root

**Comment by dimbleby** [comment]
if you want your project definition not to result in installation of any dependencies - then simply do not declare any dependencies.

if you want dependencies but you sometimes want not to install them - well that is what the command line option does.

**Comment by clintonroy** [comment]
I think this is covered by package-mode = false option https://python-poetry.org/docs/basic-usage/#operating-modes

**Comment by dimbleby** [comment]
> I think this is covered by package-mode = false

It is not.

**Comment by radoering** [comment]
I do not really understand this feature request and agree with

> if you want your project definition not to result in installation of any dependencies - then simply do not declare any dependencies.
