### ISSUE TITLE
Poetry install also installs a Python environment, if necessary

### ISSUE THREAD

**Issue by robertlagrant** [python-poetry/poetry#9538]
### Issue Kind

Brand new capability

### Description

Typing `poetry install` could:
- check if a correct Python environment already exists to create a venv from
- install a Python environment, if missing
- base the venv off the relevant environment

### Impact

There is a lot of pain associated with pointing Poetry at the correct environment. 10% of the total Github issues for Poetry [mention Pyenv](https://github.com/python-poetry/poetry/issues?q=is%3Aissue+pyenv).

### Workarounds

Use Pyenv, or similar, or roll your own solution.

**Comment by dimbleby** [comment]
this is exactly what poetry does already

please close

**Comment by dimbleby** [comment]
perhaps you are using "environment" not to mean virtual environment, and your intention is to ask that poetry download / build / install python binaries?

this project has resisted that, imo correctly - there are existing solutions and the small group of people who occasionally show up and do stuff here are already unable to keep up with the existing pile of issues.

for those reasons trying to make poetry do everything is likely not desirable

**Comment by robertlagrant** [comment]
Closing as requested.
