### ISSUE TITLE
Add a graceful retry logic for intermittent network failure when downloading packages

### ISSUE THREAD

**Issue by SmartManoj** [python-poetry/poetry#9551]
### Description

Connection broken: IncompleteRead from Urllib3

### Workarounds

Retry like #2813

### Poetry Installation Method

install.python-poetry.org

### Operating System

Ubuntu 22.04.4 LTS

### Poetry Version

1.8.3

### Poetry Configuration

```bash session
Default
```

### Poetry Runtime Logs

```bash session
[Github Action Log](https://github.com/OpenDevin/OpenDevin/actions/runs/9920819642/job/27431228343)
```

**Comment by dimbleby** [comment]
#9422, please close

**Comment by SmartManoj** [comment]
But #3219 is closed.

**Comment by dimbleby** [comment]
if you have comments on #9422 please take them there, not here
