### ISSUE TITLE
Could poetry do magic to fix Python's inability of having multiple versions of the same package installed?

### ISSUE THREAD

**Issue by papb** [python-poetry/poetry#9557]
### Issue Kind

Brand new capability

### Description

Hello!

Today I encountered what I currently believe to be major problem in Python:

https://stackoverflow.com/q/6570635/4135063

In Node.js, this can be done easily, due to the tree structure created of nested `node_modules` folders (and how importing modules work).

I understand this may be outside the scope of Poetry, but I was wondering, perhaps Poetry could do some magic under the hood and make this work somehow? Maybe creating a nested structure of `.venv` folders, and automagically adjusting `PYTHON_PATH` in a crazy way, or even monkey-patching imports, or maybe another sorcery...

Thanks!

### Impact

As the ecosystem grows, it is likely to become more and more common for two community packages X and Y depend on another package Z but in two different versions (more precisely, two incompatible semver ranges). Currently, as I understand, it is simply impossible to have both packages (X and Y) installed.

### Workarounds

The linked question on StackOverflow contains some answers which suggest nasty workarounds, but none of them are practical, especially because you lose all the usefulness of the dependencies section of the pyproject.toml file. The workarounds would require, for starters, to stop using poetry altogether...

**Comment by IgnaciodelaTorreArias** [comment]
I think most poetry users use it to create and distribute packages (my self included), if poetry make a work around that it would break the ability to do that since packages created that way couldn't be uploaded to PyPi or any mirror of PyPi.
Also it sounds too complex and out of the scope of poetry.

**Comment by radoering** [comment]
I agree that this is clearly out of scope. I am not aware of any tool that is able to do this and I think the reason is that it is a very complex feature, which requires a lot of effort.
