### ISSUE TITLE
Allow Custom Installation Order and Conditional Installation/Uninstallation of Dependencies in pyproject.toml

### ISSUE THREAD

**Issue by XDeviation** [python-poetry/poetry#9559]
### Issue Kind

Brand new capability

### Description

I would like to request a feature that allows customizing the installation order of Python libraries in pyproject.toml, with the ability to install certain libraries first and then uninstall them after other dependencies have been installed.

### Impact

In my project, I have some libraries that need to be compiled with Cython and require numpy version 2.0 or above for successful compilation. However, my project itself only requires numpy version 1.x.

A real-world example of this issue can be seen in this Cython issue: https://github.com/cython/cython/issues/6249.

Desired Workflow
1. Install numpy 2.x
2. Install the libraries that need numpy 2.x for compilation
3. Uninstall numpy 2.x
4. Install numpy 1.x

This would allow me to ensure that my project dependencies are correctly installed without manual intervention or complex scripting.

### Workarounds

```bash
# Install numpy 2.x
poetry run pip install numpy==2.x

# Install the library that requires numpy 2.x
poetry run pip install <library_needing_numpy2>

# Uninstall numpy 2.x
poetry run pip uninstall -y numpy

# Install numpy 1.x
poetry run pip install numpy==1.x

# Install remaining dependencies
poetry install
```

**Comment by Secrus** [comment]
This is not something that would be transferable between package installers in the Python ecosystem since package metadata cannot carry such information. For that reason, I have to say no to that request.
