### ISSUE TITLE
locally package installiation 

### ISSUE THREAD

**Issue by MirS0bhan** [python-poetry/poetry#9583]
### Issue Kind

Brand new capability

### Description

hi
in the past approach for installing the packages we need to setup.py but with poetry we just have pyproject.toml,
so for installing the packages locally we need this method:
```bash
$ git clone https://github.com/org/example && cd example
$ pytest # can be configured for running tests
$ poetry install
$ poetry build 
$ pip install dist/example-*.whl
```

i think it is better to create a shortcut for this application 

### Impact

Due to Poetry's innovations, we can no longer use the traditional method for installing packages locally. Therefore, we need a new function for this purpose. Given the complexity of the process, it's advisable to create a shortcut, making the installation process easier.

### Workarounds

i had write it in description

**Comment by finswimmer** [comment]
Hello @MirS0bhan,

it is unclear to me what problem you are trying to solve. So please a step-by-step description about what you are trying to do.

You can use `pip` to install any Poetry project directly. There is no need for building a wheel using poetry before.

fin swimmer

**Comment by MirS0bhan** [comment]
@finswimmer
Look, in almost every open-source project, there is a solution to install it without using a package manager. In this case, `pip` always needs one of two things: `setup.py` or `*.whl`. After this, you need to build it or have a build of it. The problem is that if we are not using the setup.py, then we need to build it and then install it. I'm just trying to say we should create a shortcut way to perform all of this procedure.

**Comment by dimbleby** [comment]
> In this case, pip always needs one of two things: setup.py or *.whl

This is not true.  After cloning your project you can just `pip install .`, if that's what your want to do.

**Comment by MirS0bhan** [comment]
@dimbleby
Yes, but that command would build the project and create a *.whl file, which can then be installed. It would be better if Poetry had a command to do all of this in one step: getting dependencies, building, and then installing the project.

**Comment by dimbleby** [comment]
you are wrong on all counts.  

- `pip install .` will install the project
- `poetry install` also already does what you want

please close

**Comment by MirS0bhan** [comment]
poetry install doesn't install package in python site-packages. ok i close this no matter what
