### ISSUE TITLE
Allow pinning setuptools for poetry install

### ISSUE THREAD

**Issue by gilad-yadgar** [python-poetry/poetry#9588]
### Issue Kind

Change in current behaviour

### Description

There is a new breaking change to setuptools
https://github.com/pypa/setuptools/issues/4519
it would be good to be able to pin the specific setuptools version that poetry uses behind the scenes

### Impact

If setuptools releases a breaking version, poetry breaks

### Workarounds

not using poetry install but using 
poetry export and pip install instead

**Comment by dimbleby** [comment]
duplicate #8216, #8261, #8752, #9586

please close
