### ISSUE TITLE
`poetry format` and `poetry check`?

### ISSUE THREAD

**Issue by jymchng** [python-poetry/poetry#9589]
### Issue Kind

Brand new capability

### Description

I know `poetry check` checks if the `pyproject.toml` is well formed - it is a pity because it could have been used for type checking instead, like how `cargo` does it.

I wonder if we can either have within `poetry` or as a plugin, a `poetry format`, where the formatter is chosen based on existence of configuration file, and/or specified within the `pyproject.toml` manifest.

E.g., if `ruff` is chosen as the formatter, then `poetry format` desugars to `ruff check`.

Similar for `poetry typed`, where it desugars to running a type checker, e.g. `mypy` or `pyright`.

### Impact

Instead of having to use different tools for different purposes, let `poetry` be the main interface for it.

### Workarounds

Of course, you can use a `Justfile`, or even a `Makefile` or bash scripts, but nothing beats having one build tool to rule them all.

**Comment by finswimmer** [comment]
Hey @jymchng,

you can use the Poetry Plugin https://github.com/nat-n/poethepoet for this kind of things.

fin swimmer
