### ISSUE TITLE
('Connection broken: IncompleteRead(54376030 bytes read, 143484550 more expected)', IncompleteRead(54376030 bytes read, 143484550 more expected))

### ISSUE THREAD

**Issue by MohammadAminDHM** [python-poetry/poetry#9592]
### Description

i get this error and don't know how to solve that

(.venv) D:\face-maching>poetry add torch
Using version ^2.4.0 for torch

Updating dependencies
Resolving dependencies... (0.1s)

Package operations: 1 install, 0 updates, 0 removals

  - Installing torch (2.4.0): Failed

  IncompleteRead

  IncompleteRead(42322026 bytes read, 155538554 more expected)

  at d:\face-maching\.venv\Lib\site-packages\urllib3\response.py:894 in _raw_read
       890│                     # to concerns of backward compatibility. We're
       891│                     # addressing it here to make sure IncompleteRead is
       892│                     # raised during streaming, so all calls with incorrect
       893│                     # Content-Length are caught.
    →  894│                     raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
       895│             elif read1 and (
       896│                 (amt != 0 and not data) or self.length_remaining == len(data)
       897│             ):
       898│                 # All data has been read, but `self._fp.read1` in

The following error occurred when trying to handle this error:

  ProtocolError

  ('Connection broken: IncompleteRead(42322026 bytes read, 155538554 more expected)', IncompleteRead(42322026 bytes read, 155538554 more expected))

  at d:\face-maching\.venv\Lib\site-packages\urllib3\response.py:772 in _error_catcher
       768│                 ):
       769│                     arg = "Response may not contain content."
       770│                 else:
       771│                     arg = f"Connection broken: {e!r}"
    →  772│                 raise ProtocolError(arg, e) from e
       773│
       774│             except (HTTPException, OSError) as e:
       775│                 raise ProtocolError(f"Connection broken: {e!r}", e) from e
       776│

The following error occurred when trying to handle this error:

  ChunkedEncodingError

  ('Connection broken: IncompleteRead(42322026 bytes read, 155538554 more expected)', IncompleteRead(42322026 bytes read, 155538554 more expected))

  at d:\face-maching\.venv\Lib\site-packages\requests\models.py:822 in generate
       818│             if hasattr(self.raw, "stream"):
       819│                 try:
       820│                     yield from self.raw.stream(chunk_size, decode_content=True)
       821│                 except ProtocolError as e:
    →  822│                     raise ChunkedEncodingError(e)
       823│                 except DecodeError as e:
       824│                     raise ContentDecodingError(e)
       825│                 except ReadTimeoutError as e:
       826│                     raise ConnectionError(e)

Cannot install torch.

### Workarounds

i don't know

### Poetry Installation Method

pip

### Operating System

win 10

### Poetry Version

1.8

### Poetry Configuration

```bash session
cache-dir = "C:\\Users\\add\\AppData\\Local\\pypoetry\\Cache"
experimental.system-git-client = false
installer.max-workers = 5
installer.modern-installation = true
installer.no-binary = null
installer.parallel = false
keyring.enabled = true
solver.lazy-wheel = true
virtualenvs.create = true
virtualenvs.in-project = null
virtualenvs.options.always-copy = false
virtualenvs.options.no-pip = false
virtualenvs.options.no-setuptools = false
virtualenvs.options.system-site-packages = false
virtualenvs.path = "{cache-dir}\\virtualenvs"  # C:\Users\add\AppData\Local\pypoetry\Cache\virtualenvs
virtualenvs.prefer-active-python = false
virtualenvs.prompt = "{project_name}-py{python_version}"
warnings.export = true
```

### Poetry Runtime Logs

```bash session
(.venv) D:\face-maching>poetry add torch
Using version ^2.4.0 for torch

Updating dependencies
Resolving dependencies... (0.1s)

Package operations: 1 install, 0 updates, 0 removals

  - Installing torch (2.4.0): Failed

  IncompleteRead

  IncompleteRead(42322026 bytes read, 155538554 more expected)

  at d:\face-maching\.venv\Lib\site-packages\urllib3\response.py:894 in _raw_read
       890│                     # to concerns of backward compatibility. We're
       891│                     # addressing it here to make sure IncompleteRead is
       892│                     # raised during streaming, so all calls with incorrect
       893│                     # Content-Length are caught.
    →  894│                     raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
       895│             elif read1 and (
       896│                 (amt != 0 and not data) or self.length_remaining == len(data)
       897│             ):
       898│                 # All data has been read, but `self._fp.read1` in

The following error occurred when trying to handle this error:


  ProtocolError

  ('Connection broken: IncompleteRead(42322026 bytes read, 155538554 more expected)', IncompleteRead(42322026 bytes read, 155538554 more expected))

  at d:\face-maching\.venv\Lib\site-packages\urllib3\response.py:772 in _error_catcher
       768│                 ):
       769│                     arg = "Response may not contain content."
       770│                 else:
       771│                     arg = f"Connection broken: {e!r}"
    →  772│                 raise ProtocolError(arg, e) from e
       773│
       774│             except (HTTPException, OSError) as e:
       775│                 raise ProtocolError(f"Connection broken: {e!r}", e) from e
       776│

The following error occurred when trying to handle this error:


  ChunkedEncodingError

  ('Connection broken: IncompleteRead(42322026 bytes read, 155538554 more expected)', IncompleteRead(42322026 bytes read, 155538554 more expected))

  at d:\face-maching\.venv\Lib\site-packages\requests\models.py:822 in generate
       818│             if hasattr(self.raw, "stream"):
       819│                 try:
       820│                     yield from self.raw.stream(chunk_size, decode_content=True)
       821│                 except ProtocolError as e:
    →  822│                     raise ChunkedEncodingError(e)
       823│                 except DecodeError as e:
       824│                     raise ContentDecodingError(e)
       825│                 except ReadTimeoutError as e:
       826│                     raise ConnectionError(e)

Cannot install torch.
```

**Comment by dimbleby** [comment]
poetry cannot solve your network connectivity, please close

**Comment by Secrus** [comment]
Not a Poetry error
