### ISSUE TITLE
Add functionality to ensure pip respects Python version constraints specified in `pyproject.toml` when installing dependencies.

### ISSUE THREAD

**Issue by rbpasker** [python-poetry/poetry#9595]
### Issue Kind

Brand new capability

### Feature Request: Inherit Python Version Constraints from `pyproject.toml` to Pip

**Description:**
Add functionality to ensure pip respects Python version constraints specified in `pyproject.toml` when installing dependencies.

**Problem:**
Currently, pip does not enforce the Python version constraints defined in `pyproject.toml`, which can lead to compatibility issues if users manually install packages using pip. This can result in environments where the installed Python version does not meet the project's requirements, leading to potential runtime errors or unexpected behavior.

**Use Case:**
When a project specifies Python version constraints in `pyproject.toml` (e.g., `python = ">=3.9,<3.12"`), it is crucial that these constraints are respected during the installation process to ensure compatibility. By enforcing these constraints, developers can avoid inadvertent installation of their project in an incompatible Python environment.

**Proposed Implementation:**
- Extend Poetry's installation process to pass Python version constraints to pip.
- Modify the dependency resolver to check the current Python version against the constraints specified in `pyproject.toml` before proceeding with the installation.
- Provide informative error messages if the current Python version does not meet the specified constraints, guiding users to switch to a compatible version.

**Examples:**
If a project specifies:
```toml
[tool.poetry.dependencies]
python = ">=3.9,<3.12"
```
Attempting to install the project with Python 3.12 using pip should result in a clear error message indicating the version constraint violation:
```
ERROR: This project requires Python >=3.9,<3.12. Your Python version is 3.12.
Please switch to a compatible Python version to proceed with the installation.
```

**Benefits:**
- Ensures environment consistency and compatibility.
- Reduces potential runtime errors due to incompatible Python versions.
- Improves developer experience by providing clear guidance on version requirements.

**Additional Context:**
This feature aligns with Poetry's goal of providing a seamless dependency management experience. Implementing this feature would further enhance the robustness of the tool, ensuring that all dependencies and environment constraints are respected.

### Impact

I spent an hour trying to figure out why `pip install sycamore` wouldn't complete. it was because the dependency was <3.12, and I had 3.12 installed.

### Workarounds

not that I know of

**Comment by Secrus** [comment]
if you want `pip` to show or read some info, go to their issue tracker. Poetry writes standard METADATA file when building packages, which includes the information you are reffering to.

**Comment by rbpasker** [comment]
backlink to pip issue

https://github.com/pypa/pip/issues/12885
