### ISSUE TITLE
Pyproject.toml package list entry cannot be directed to different target

### ISSUE THREAD

**Issue by matgrioni** [python-poetry/poetry#9605]
### Description

Documentation on [pyproject.toml](https://python-poetry.org/docs/pyproject/) suggests that the following syntax is supported.

```
[tool.poetry]
# ...
packages = [
    { include = "my_package", from = "lib", to = "target_package" },
]
```

My understanding of what this should do is that a local install of the package in question should probably support `import target_package`.

I am not seeing this however and `my_package` is resolved as the module name. Is this feature actually supported or do I misunderstand something?

### Workarounds

No real workaround. Rename the folder in the source to the desired target name I suppose.

### Poetry Installation Method

install.python-poetry.org

### Operating System

Windows 11

### Poetry Version

1.8.3

### Poetry Configuration

```bash session
cache-dir = "C:\\Users\\matgr\\AppData\\Local\\pypoetry\\Cache"
experimental.system-git-client = false
installer.max-workers = null
installer.modern-installation = true
installer.no-binary = null
installer.parallel = true
keyring.enabled = true
solver.lazy-wheel = true
virtualenvs.create = true
virtualenvs.in-project = null
virtualenvs.options.always-copy = false
virtualenvs.options.no-pip = false
virtualenvs.options.no-setuptools = false
virtualenvs.options.system-site-packages = false
virtualenvs.path = "{cache-dir}\\virtualenvs"  # C:\Users\matgr\AppData\Local\pypoetry\Cache\virtualenvs
virtualenvs.prefer-active-python = false
virtualenvs.prompt = "{project_name}-py{python_version}"
warnings.export = true
```

### Poetry Runtime Logs

```bash session
Doesn't seem applicable. poetry install command succeeds, and logs don't reveal anything apparently obvious (would rather not scrub data if not needed).
```

**Comment by matgrioni** [comment]
I am using poetry only for dependency management in a monorepo structure.

Folder structure
```
monorepo/
  | my_project/
      | src/
       - component.py
      | tests/
       - test_component.py
  - pyproject.toml
```

pyproject.toml
```
[tool.poetry]
name = "monorepo"
version = "0.0.0"
packages = [
    {include = "src", from = "my_project", to = "my_project"}
]

[tool.poetry.dependencies]
python = "^3.10"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

If I run:

```
poetry lock
poetry install
poetry shell
python

>>> import my_project # <-- raises import error
>>> import src # <-- resolves to monorepo/myproject/src. Expectation is that this line fails and first line succeeds
```

Looking at the change you provided it looks like for local install this might be expected. I have no idea why this is though and if I run `poetry build` the .tar.gz created also has a src/ folder and not a my_module folder.

![image](https://github.com/user-attachments/assets/e2f424ac-01ef-4995-8e0b-b89cbc62e7d8)

**Comment by dimbleby** [comment]
Seems expected then.  Of course the source distribution should look like the source, perhaps you want to care about the wheel.

Please close.
