### ISSUE TITLE
how to change prod/dev dependencies using groups 

### ISSUE THREAD

**Issue by iBuitron** [python-poetry/poetry#9611]
### Issue Kind

Other concerns with documentation

### Existing Link

https://python-poetry.org/docs/managing-dependencies/

### Description

Hi!

Context:

I have several packages:

>**data-management-tools**

> **quickbio_books**

i install 'data-management-tools' on 'quickbio_books' as: `poetry add --editable --group dev ../../data-management-tools`

```
[tool.poetry.group.dev.dependencies]
data-management-tools = {path = "../../data_management_tools", develop = true}

my stuff on quickbio_books works fine.
```
> **quickbio**

but, when i install "quickbio_books" on "quickbio" as `poetry add --editable --group dev ../quickBio-books`

```
[tool.poetry.group.dev.dependencies]
quickbio-books = {path = "../quickBio-books", develop = true}
```
it doesn't install `data-management-tools`

Resume: 
Cuz quickbio_books has data-management-tools ( this is on dev group), 
and quickbio has quickbio_books ( this is on dev group also), 
quickbio should has data-management-tools 

```

## quickbio

poetry show --tree

#There is not data-management-tools
NOTE: when i install data-management-tools outside a group on quickbio_books (as main dependencies) all works


quickbio-books 0.1.0
├── beanie ^1.26.0
│   ├── click >=7 
│   │   └── colorama * 
│   ├── lazy-model 0.2.0 
│   │   └── pydantic >=1.9.0 
│   │       ├── annotated-types >=0.4.0 
│   │       ├── pydantic-core 2.20.1 
│   │       │   └── typing-extensions >=4.6.0,<4.7.0 || >4.7.0 
│   │       ├── typing-extensions >=4.6.1 (circular dependency aborted here)
│   │       └── typing-extensions >=4.12.2 (circular dependency aborted here)
│   ├── motor >=2.5.0,<4.0.0 
│   │   └── pymongo >=4.5,<5 
│   │       └── dnspython >=1.16.0,<3.0.0 
│   ├── pydantic >=1.10,<3.0 (circular dependency aborted here)
│   └── toml * 
├── fastexcel ^0.10.4
│   └── pyarrow >=8.0.0 
│       └── numpy >=1.16.6 
├── odmantic ^1.0.2
│   ├── motor >=3.1.1 
│   │   └── pymongo >=4.5,<5 
│   │       └── dnspython >=1.16.0,<3.0.0 
│   ├── pydantic >=2.5.2 
│   │   ├── annotated-types >=0.4.0 
│   │   ├── pydantic-core 2.20.1 
│   │   │   └── typing-extensions >=4.6.0,<4.7.0 || >4.7.0 
│   │   ├── typing-extensions >=4.6.1 (circular dependency aborted here)
│   │   └── typing-extensions >=4.12.2 (circular dependency aborted here)
│   └── pymongo >=4.1.0 (circular dependency aborted here)
├── pandas ^2.2.2
│   ├── numpy >=1.23.2 
│   ├── numpy >=1.26.0 (circular dependency aborted here)
│   ├── python-dateutil >=2.8.2 
│   │   └── six >=1.5 
│   ├── pytz >=2020.1 
│   └── tzdata >=2022.7 
├── pydantic-settings ^2.3.3
│   ├── pydantic >=2.7.0 
│   │   ├── annotated-types >=0.4.0 
│   │   ├── pydantic-core 2.20.1 
│   │   │   └── typing-extensions >=4.6.0,<4.7.0 || >4.7.0 
│   │   ├── typing-extensions >=4.6.1 (circular dependency aborted here)
│   │   └── typing-extensions >=4.12.2 (circular dependency aborted here)
│   └── python-dotenv >=0.21.0 
├── pyreadr ^0.5.0
│   └── pandas >=1.2.0 
│       ├── numpy >=1.23.2 
│       ├── numpy >=1.26.0 (circular dependency aborted here)
│       ├── python-dateutil >=2.8.2 
│       │   └── six >=1.5 
│       ├── pytz >=2020.1 
│       └── tzdata >=2022.7 
├── tabula-py ^2.9.3
│   ├── distro * 
│   ├── numpy * 
│   └── pandas >=0.25.3 
│       ├── numpy >=1.23.2 (circular dependency aborted here)
│       ├── numpy >=1.26.0 (circular dependency aborted here)
│       ├── python-dateutil >=2.8.2 
│       │   └── six >=1.5 
│       ├── pytz >=2020.1 
│       └── tzdata >=2022.7 
└── xlsx2csv ^0.8.2
```

My question is, is there any way to manage the dependencies on groups?
what i want is to have a dev group (wich has all local dependencies) and a prod group wich is read from private git.

When i works on local use/install all dev dependencies and when deploy use prod dependencies.
There is any way to do that?
I dont wanna change every time between dev/prod on main dependencies

**Comment by iBuitron** [comment]
Related: #9497

**Comment by iBuitron** [comment]
Related: #9369 
Like to split on groups
installing for dev / prod

**Comment by dimbleby** [comment]
there is no place in the standard metadata for the dev dependencies of `quickbio_books`.  That information is not available to `quickbio`.

if both projects have the same dev dependencies, you will just have to copy-paste that information around.

Duplicate #9476, among others.  Please close.

**Comment by iBuitron** [comment]
> there is no place in the standard metadata for the dev dependencies of `quickbio_books`. That information is not available to `quickbio`.
> 
> if both projects have the same dev dependencies, you will just have to copy-paste that information around.
> 
> Duplicate #9476, among others. Please close.



Contributor
[dimbleby](https://github.com/dimbleby) commented [on Jun 7](https://github.com/python-poetry/poetry/issues/9476#issuecomment-2154216499)
All groups (except main) are dev dependencies. Perhaps you want extras.

Shall i install as extra??

**Comment by iBuitron** [comment]
There is my solution:
```
[tool.poetry]
name = "quickbio-books"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"


[tool.poetry.dependencies]
python = "^3.11"
beanie = "^1.26.0"
pyreadr = "^0.5.0"
pandas = "^2.2.2"
pydantic-settings = "^2.3.3"
xlsx2csv = "^0.8.2"
tabula-py = "^2.9.3"
odmantic = "^1.0.2"
fastexcel = "^0.10.4"

# as optional (replace the path with any url for production/git ) ( 1 ) 
data-management-tools = {path = "../../data_management_tools", develop = true,  optional = true}

[tool.poetry.group.dev]
optional = true

# set as dev dependencie ( 2 ) 
[tool.poetry.group.dev.dependencies]
data-management-tools = {path = "../../data_management_tools", develop = true}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

# set as extra
[tool.poetry.extras]
prod = ["data-management-tools"]

# local installation (uses 2 ) 
# poetry install --with dev

# prod installation  (uses 1 ) 
# poetry install --extras prod 

# add as package (uses 2 ) - Here i gonna check later if can change anything for stills using local version.
# poetry add --editable(or not) --extras "prod" ../path
# poetry add --editable --extras "prod" ../path

```
If you add the main dependenci (quickbio-books) in other like "quickbio" it gonna install data_management_tools from quickbio-books ( poetry show --tree)


There is a tricking workaround, mb can implement a easiest way to use one agains other like a switch

**Comment by dimbleby** [comment]
anyway there is no bug and nothing to change in poetry, please close
