### ISSUE TITLE
Poetry Not Respecting Explicit Sources in Dependencies of Dependencies

### ISSUE THREAD

**Issue by IRTCKyleR** [python-poetry/poetry#9621]
### Description

Poetry looks for second order `explicit` dependencies only in PyPI rather than the source that is specified in the dependency dictionary.

EXAMPLE

given the following:
- `private_source` = `https://some/url/pypi/simple`
- `my_project` and all packages have `private_source` added with the following command:
     - `poetry source add private_source https://some/url/pypi/simple --priority=explicit`
     - this results in the following in EACH pyproject.toml file:
![image](https://github.com/user-attachments/assets/f0d133be-62e0-475f-828b-4547d2de4f11)

- `package_a` relies on `package_b`
![image](https://github.com/user-attachments/assets/a7f67c37-73ea-4057-a6f2-eaeb638e8952)

- `package_b` purely relies on packages from PyPI

NOW, when adding `package_a` to `my_project` via: `poetry add package_a@1.0.0 --source private_source`

I receive an error stating that no versions of package_b match 1.0.0.
Running with -vvv reveals the following (edited for example clarity):
```
Source (private_source): 1 packages found for package_a >=1.0.0,<2.0.0
Checking if keyring is available
Using keyring backend 'SecretService Keyring'
Creating new session for pypi.org
   1: fact: package_a (1.0.0) depends on package_b (1.0.0)
   1: selecting package_a (1.0.0)
   1: derived: package_b (==1.0.0)
[urllib3:urllib3.connectionpool] Starting new HTTPS connection (1): pypi.org:443
[urllib3:urllib3.connectionpool] https://pypi.org:443 "GET /simple/package_b/ HTTP/11" 404 13
Source (PyPI): No packages found for package_b
Source (PyPI): 0 packages found for package_b 1.0.0
Falling back to installed packages to discover metadata for package_b
Found 0 compatible packages for package_b
```

As can be seen from the verbose error, `private_source` is never checked for package_b even though it is explicitly set in the pyproject.toml, and in fact ONLY PyPI is checked for the package which is the opposite of the desired behavior.

### Workarounds

I can workaround this by setting `private_source` to `primary` or `supplemental` rather than `explicit` and everything works as expected.

However, I believe this is contrary to good practice that I've seen promoted as it introduces vulnerability to dependency confusion (I believe it's actually suggested against somewhere in the documentation as well).

Alternatively, I can add `package_b` explicitly as a dependency of `my_project`, however this becomes quite tedious with larger numbers of dependencies and essentially bypasses the version solver step and makes it manual.

### Poetry Installation Method

pip

### Operating System

Ubuntu 20.04

### Poetry Version

Poetry (version 1.8.3)

### Poetry Configuration

```bash session
cache-dir = "/home/me/.cache/pypoetry"
experimental.system-git-client = false
installer.max-workers = null
installer.modern-installation = true
installer.no-binary = null
installer.parallel = true
keyring.enabled = true
repositories.private_source.url = "https://some/url/pypi/simple"
solver.lazy-wheel = true
virtualenvs.create = true
virtualenvs.in-project = null
virtualenvs.options.always-copy = false
virtualenvs.options.no-pip = false
virtualenvs.options.no-setuptools = false
virtualenvs.options.system-site-packages = false
virtualenvs.path = "{cache-dir}/virtualenvs"  # /home/me/.cache/pypoetry/virtualenvs
virtualenvs.prefer-active-python = false
virtualenvs.prompt = "{project_name}-py{python_version}"
warnings.export = true
```

### Poetry Runtime Logs

```bash session
The relevant section of the log

Source (private_source): 1 packages found for package_a >=1.0.0,<2.0.0
Checking if keyring is available
Using keyring backend 'SecretService Keyring'
Creating new session for pypi.org
   1: fact: package_a (1.0.0) depends on package_b (1.0.0)
   1: selecting package_a (1.0.0)
   1: derived: package_b (==1.0.0)
[urllib3:urllib3.connectionpool] Starting new HTTPS connection (1): pypi.org:443
[urllib3:urllib3.connectionpool] https://pypi.org:443 "GET /simple/package_b/ HTTP/11" 404 13
Source (PyPI): No packages found for package_b
Source (PyPI): 0 packages found for package_b 1.0.0
Falling back to installed packages to discover metadata for package_b
Found 0 compatible packages for package_b
```
```

**Comment by dimbleby** [comment]
Poetry knows nothing about sources defined by dependencies: please search for duplicates, please close.

**Comment by IRTCKyleR** [comment]
I did, I have, and I will. However, I don't think you've actually evaluated what is being presented as the behavior is _very_ unintuitive.

Why would poetry, which is obviously already reading the pyproject.toml files not respect the sources of second order dependencies. Especially so when the source is actually already defined in the configuration of the primary project where everything is being installed.

I can understand _not_ modifying the tool configuration when discovering sources in a dependency, however when a source is defined at the project level why would it be ignored when EXPLICIT but not primary or secondary.

I maintain this is a bug and contrary to the documented behavior, but I'll respect the "won't fix".

Thanks either way, have a good day.

**Comment by dimbleby** [comment]
https://python-poetry.org/docs/repositories#package-sources is clear:

> Package source keys are not inherited by their dependencies.
