### ISSUE TITLE
Prompt for git credentials when trying to install package from private repository when credential cache is empty

### ISSUE THREAD

**Issue by HYBRID-BEING** [python-poetry/poetry#9627]
### Issue Kind

Other

### Description

One of the dependencies in my project comes from a private repository. I have git's _credential.helper_ set to _cache_, and sometimes credentials in cache expire before i run `poetry install` (usually with `--sync`). This causes following error:
```
Failed to clone https://***.git, check your git configuration and permissions for this repository.
```
I understand that this happens due to the fact that Poetry is unable to get credentials from the cache (although, it was a bit confusing at first, as there is nothing wrong with git configuration and permissions), but it would've been nice, if i was prompted for credentials when this happens.

### Impact

This would make it more obvious for users, why exactly is Poetry unable to install the package in this particular case. It would also save users from having to cache credentials and re-enter the command, by continuing execution after the prompt.

### Workarounds

Executing any git command against repository in question caches credentials and allows Poetry to use credentials until they expire.

**Comment by dimbleby** [comment]
This is the opposite of #9626, #5880, etc

Generally poetry's intention is not to do interactive stuff during poetry install because it tends to get lost and look like a hang.

**Comment by HYBRID-BEING** [comment]
Hmm, from what i see, people were reporting that Poetry was getting stuck because prompts would not be shown properly or they had to enter credentials multiple times per Poetry command in `-vvv` mode. Feels like disabling the prompt is more of a workaround for that, tbh.
But if that is the direction Poetry is taking, than i guess i'll just have to deal with it. From what i gathered detecting this won't be easy either, so maybe, at least, the error message could mention the credentials (i guess they technically fall under "configuration" part, but i think explicit mention would remedy slight confusion like mine)?

**Comment by swills1** [comment]
Maybe I am just lost in space, but can't you just do -
`pip install git+https://<USERNAME>:<TOKEN>@github.com/<USER>/<REPO>.git@<BRANCH>#egg=<PACKAGE_NAME>
`

Where `TOKEN` is the token or password. Then `poetry install`. Then all you have to do is hit the up arrow when you want to reinstall the package again and then run another `poetry install`?

Am I misunderstanding?

**Comment by abn** [comment]
@swills1 that will not work as expected in all cases as Poetry manages vcs dependencies different to how pip manages it. And furthermore, it definitely should not work if you have specified the dependency as a vcs dependency to the project. 

For using git dependencies requiring credentials please see https://python-poetry.org/docs/dependency-specification#git-dependencies.

While the workaround mentioned in the original post, refers to the use of system git client, it is essential to note that this feature will be removed once [Dulwich](https://www.dulwich.io/) gains capability to access [gitcredentials](https://git-scm.com/docs/gitcredentials). 

Users needing credentials must configure credentials prior to use of the repository as described in the documentation. At this time we do not intend to implement the requested feature.

@HYBRID-BEING happy to address any specific concerns, or if we can help solve any particular use case, please do not hesitate to reach out on Discord or raise a Discussion here.

**Comment by swills1** [comment]
@abn 

I mean, we're definitely using a "vcs dependency" in this case since we'e talking about git, a specific type of VCS repository. :) (That's more tongue and cheek.)

Reading through the docs - OP's issue can still be solved using the up arrow and just recalling things.

```
poetry config repositories.git-org-project https://github.com/org/project.git
poetry config http-basic.git-org-project username token
poetry add git+https://github.com/org/project.git
```

I think if @HYBRID-BEING reads the docs oyu linked, it will solve their problem.

**Comment by swills1** [comment]
@abn 

I mean, we're definitely using a "vcs dependency" in this case since we'e talking about git, a specific type of VCS repository. :) (That's more tongue and cheek.)

Reading through the docs - OP's issue can still be solved using the up arrow and just recalling things.

I think if @HYBRID-BEING reads the docs you linked, it will solve their problem.

I also think it's needs to be clarified - this isn't so much about adding or not adding a feature. A solution already exists and @HYBRID-BEING just needed to be made aware. Thank you.

```
poetry config repositories.git-org-project https://github.com/org/project.git
poetry config http-basic.git-org-project username token
poetry add git+https://github.com/org/project.git
```
