### ISSUE TITLE
Terminate the child process when killed

### ISSUE THREAD

**Issue by i3v** [python-poetry/poetry#9632]
### Issue Kind

Brand new capability

### Description

I'd like to have the process `x` started with `poetry run x`  terminated when the parent process (poetry.exe) is killed.

Just in case someone else would want the opposite, I'd suggest to make this behavior optional (maybe one more command, like `poetry exec x` ?). I'm not really sure.

**A rough usage example:**
1.  Create a new task in a Windows Task Scheduler, with Action = "start a program"
     * `program/script` = `C:\path\to\poetry.exe`
     * `arguments` = `run notepad.exe`
     * `start in` = `C:\path\to\some\poetry\project`
3. Run this task. The Task Manager shows the task status as "Running" as long as the Notepad window is open (as desired).
4. In an advanced task manager (example: [System Informer](https://github.com/winsiderss/systeminformer)), see the tree of the processes:
![image](https://github.com/user-attachments/assets/6e38db2d-bab5-4d21-983a-8c367eaefb60)

5. Right-click the task (in the Task Manager) and select "End". The "poetry.exe", the "notepad.exe" remains alive (but is expected to die):
![image](https://github.com/user-attachments/assets/439a8316-4b7d-44a8-b97f-ef61d1477ae0)

This "notepad.exe" was started with `cmd.exe /c "notepad.exe"`:
![image](https://github.com/user-attachments/assets/18357c86-a594-47a3-9280-abf81c115a82)

**Various related discussions:**
  1. https://github.com/python-poetry/poetry/issues/993#issuecomment-514058850 - older related request. The 
      * [current  code](https://github.com/python-poetry/poetry/blob/e5e4b0ce9d2f4a50f6feeacac3a7d995f0880979/src/poetry/utils/env/base_env.py#L353-L354) (v1.8.3)
  3. https://github.com/python/cpython/issues/101191 - a rabbit hole with nuances about starting the processes on Windows vs Linux
  4. [How to terminate a python subprocess launched with shell=True](https://stackoverflow.com/questions/4789837/how-to-terminate-a-python-subprocess-launched-with-shell-true)  - possible workarounds to patch the poetry code with. Unfortunately, with `cmd.exe` in the middle, things get a bit more difficult.
     * BTW, is it documented anywhere, why ` kwargs["shell"] = True`? Is it really necessary?
  6. [Assigning process to a job](https://stackoverflow.com/a/23587108/1032586) - best(?) Windows-specific way to avoid zombies.

### Impact

Running server-like processes with poetry normally requires a start-stop-monitor-restart mechanism much like "Task Scheduler". 
 

### Workarounds

Is there any?

**Comment by dimbleby** [comment]
Just don't use poetry run in such cases.  Activate your virtual environment and run your code directly.

**Comment by i3v** [comment]
> Just don't use poetry run in such cases. Activate your virtual environment and run your code directly.

How exactly? 
In the same scenario with the Windows Task, what exactly should I put into the `program/script`, `arguments`, and `start in`?

**Comment by dimbleby** [comment]
> How exactly?

I don't know windows task scheduler: but exactly whatever you would do for any python program in a virtualenv, nothing to do with poetry.  `path/to/python code.py`
