### ISSUE TITLE
[Project configuration] Licenses to avoid

### ISSUE THREAD

**Issue by caniko** [python-poetry/poetry#9642]
### Issue Kind

Brand new capability

### Description

Some projects are incompatible with certain licenses. For instance GPL is incompatible with proprietary. Would be nice if poetry could, optionally, avoid given list of licenses in its `pyproject.toml` file.

Many licenses are also incompatible with oneanother, meaning poetry would also keep track of the license of my project, and prohibit me from installing given packages in my project if they have an incompatible license.

### Impact

Code that has a valid license, and license safety.

### Workarounds

Manual investigation of dependencies, a lot of work for large dependecy lists.

**Comment by Secrus** [comment]
@caniko I like the idea, but:
1. Do you know of any valid and up-to-date source of truth for those incompatibilities?
2. What about projects that don't provide license info?
3. Do you know of any other packaging-related tool that does this?
4. How would that impact performance? My feeling is that it could add quite an overhead to many operations
5. Until we get standardized license declarations (see PEP 639) it can be difficult to properly parse license information from packages

**Comment by caniko** [comment]
> Do you know of any valid and up-to-date source of truth for those incompatibilities?

Incompatibilities between licenses is common knowledge. You are probably trying ask the source of truth `poetry` would use, it would have to be a new package where this is crystalized.

> How would that impact performance? My feeling is that it could add quite an overhead to many operations

From my POV, performance impact would be minimal; however, I might be missing something.

> Until we get standardized license declarations (see PEP 639) it can be difficult to properly parse license information from packages

Good point. Willing to wait.

**Comment by dimbleby** [comment]
Using license information to cause locking to fail sounds awful to me!

I'd suggest this is better left to a dedicated tool that checks the results eg - not a recommendation,  just the first thing I found - https://pypi.org/project/licensecheck/#description

**Comment by Secrus** [comment]
Given all the information, I would say that it's a plugin candidate or as Dimbleby suggested, a totally separate project. While the idea is nice, the maintenance overhead feels too big for me. 

> Incompatibilities between licenses is common knowledge. 

Well, in poetry-core we have a license list that's over 600 entries long. I doubt anyone but a trained lawyer was able to point out exactly which ones are incompatible with each other.

**Comment by verdverm** [comment]
@Secrus I think what most people want is the ability to specify a list of licenses in their pyproject.toml to fail if found during the adding process.

A middle ground could be to have a command that lists all dependencies and their license, like the `yarn licenses list` command

https://classic.yarnpkg.com/lang/en/docs/cli/licenses/
