### ISSUE TITLE
Poetry fails due to missing SSH keys for downloading optional dependencies

### ISSUE THREAD

**Issue by fergusq** [python-poetry/poetry#9643]
### Description

Our project has "internal" dependencies that are only available on our workplace computers that have the necessary ssh key. When the project is used outside, these dependencies are obviously unavailable.

I tried to mark the dependencies as optional, like this:

```
[tool.poetry.group.internal]
optional = true

[tool.poetry.group.internal.dependencies]
backend-utilities = { git = "git+ssh://git@github.com/example/backend-utils.git" }
```

However, poetry still tries to download the dependency even though it is in an optional group (and even when `--without` is used). The whole installation process fails due to this, as the SSH key is missing.

I also tried adding the dependencies as "extra":

```
backend-utilities = { git = "git+ssh://git@github.com/example/backend-utils.git" }

[tool.poetry.extras]
internal = ["backend-utilities"]
```

This didn't work either.

### Workarounds

Not to my knowledge

### Poetry Installation Method

pipx

### Operating System

MacOS Sonoma 14.2.1

### Poetry Version

Poetry (version 1.8.3)

### Poetry Configuration

```bash session
cache-dir = "/Users/iikka/Library/Caches/pypoetry"
experimental.system-git-client = false
installer.max-workers = null
installer.modern-installation = true
installer.no-binary = null
installer.parallel = true
keyring.enabled = true
solver.lazy-wheel = true
virtualenvs.create = true
virtualenvs.in-project = null
virtualenvs.options.always-copy = false
virtualenvs.options.no-pip = false
virtualenvs.options.no-setuptools = false
virtualenvs.options.system-site-packages = false
virtualenvs.path = "{cache-dir}/virtualenvs"  # /Users/iikka/Library/Caches/pypoetry/virtualenvs
virtualenvs.prefer-active-python = false
virtualenvs.prompt = "{project_name}-py{python_version}"
warnings.export = true
```

### Poetry Runtime Logs

On my computer:

```bash session
poetry -vvv update  
Loading configuration file /Users/iikka/Library/Application Support/pypoetry/config.toml
Using virtualenv: /Users/iikka/Library/Caches/pypoetry/virtualenvs/non-package-mode-piJvQicH-py3.12
Updating dependencies
Resolving dependencies...
   1: fact: non-package-mode is 0
   1: derived: non-package-mode
The authenticity of host 'REDACTED' can't be established.
ED25519 key fingerprint is REDACTED.
This key is not known by any other names.
Are you sure you want to continue connecting (yes/no/[fingerprint])?
```

In the real environment, I get the following error instead:

```
Updating dependencies
Resolving dependencies...
Host key verification failed.
```

**Comment by dimbleby** [comment]
Working as expected, poetry still has to resolve dependencies even of optional dependencies.

**Comment by fergusq** [comment]
If it is working as expected, then what is the preferred way to implement potentially-unavailable dependencies, like in my scenario?

**Comment by dimbleby** [comment]
locking requires that dependencies are available

if you have already locked then you can likely install without needing to download the things that you do not want

**Comment by radoering** [comment]
Without the key you can only `poetry install` from an existing lock file, not `poetry lock` or `poetry update`, which also locks.
