### ISSUE TITLE
RunCommand incorrectly sets sys.argv for Poetry scripts

### ISSUE THREAD

**Issue by chdsbd** [python-poetry/poetry#965]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS 10.13
- **Poetry version**: 0.12.11
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://github.com/chdsbd/poetry-repro/blob/master/pyproject.toml

## Issue
sys.argv varies when running package through `poetry run` vs `poetry shell`

- `poetry run cli`, `sys.argv == ['cli']`
- `poetry shell && cli`, `sys.argv == ['/full/path/to/package/.venv/bin/cli']`

__EDIT:__ I've looked into this a little bit more and it seems like [this RunCommand code](https://github.com/sdispater/poetry/blob/a17a99462e111d3cab9361db32245743b825f27f/poetry/console/commands/run.py#L22-L41) is the root of the issue. We are assigning incorrect values to `sys.argv` for the executable. I believe that `sys.argv` should be args that, if called, will run the same program as the running program.

`poetry shell` is going to always work correctly because it doesn't touch Poetry. The virtualenv is added to the path so we're calling directly to the executable in the virtualenv bin.

For the fix, I think we want to lookup the full path to the Poetry script in virtualenv bin and use that executable path as the first arg in `sys.argv`. I think that should fix this issue and make the behavior of calling scripts through `poetry run` equal to `poetry shell`.

**Comment by dimaqq** [comment]
I think I've hit this issue with `tornado` dev mode hot reload (i.e. tornado restarts when app source code change is detected).
The trouble there is that tornado tries to restart the app as `/path-to-system/python this-app`

**Comment by chdsbd** [comment]
Yes. I hit this with the Django hot reload server.

**Comment by chdsbd** [comment]
@sdispater I've looked into this more and updated the issue with more information. I believe there is bug with `RunCommand` and poetry scripts.

**Comment by chdsbd** [comment]
I've opened PR #1001 to fix this.

**Comment by chdsbd** [comment]
This is still an issue. I have a PR open (#1001) that will fix this.
