### ISSUE TITLE
Backoff (sleep) if http 429 code is returned

### ISSUE THREAD

**Issue by baracudda** [python-poetry/poetry#9673]
### Issue Kind

Brand new capability

### Description

- I have a project with 50+ dependencies and github.com is set as the primary source priority. However, poetry starts to encounter 429 responses from github after about 30 GET requests within a second or three.  When watching with -vvv, poetry clearly does not wait and instead continues retrying the URL until 5 attempts all result in a 429 and crash out of the install command (or lock).  Please respect the 429 response.

### Impact

if 429 is not respected, installation or lock operations cannot succeed, ever.

### Workarounds

github.com cannot be set as "primary" priority

**Comment by dimbleby** [comment]
> github.com is set as the primary source priority

What does this mean?  Github is not a python project repository.

Please provide the details that the issue template asks for, and a way to reproduce whatever it is you are seeing

**Comment by baracudda** [comment]
```
[[tool.poetry.source]]
name = "github"
url = "https://github.com"
priority = "primary"
```

**Comment by baracudda** [comment]
as requested
