### ISSUE TITLE
get-poetry.py to install from git

### ISSUE THREAD

**Issue by cancan101** [python-poetry/poetry#968]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Question
How do I get `get-poetry.py` to install the newest version of poetry from `git`? i.e. to install something even newer than the newest pre-release release on GH?

**Comment by pmav99** [comment]
What's wrong with?
```
git clone ...
cd poetry
python setup.py
```

**Comment by cancan101** [comment]
No setup.py for one.

**Comment by pmav99** [comment]
Ohhh... 
You are right of course... the power of habit... 
Anyway, I am not sure if pip supports this yet. A workaround could be to install a (pre-)released poetry version and then use it to create a wheel using `poetry build`.

**Comment by cancan101** [comment]
Once I have the wheel (which I built along the lines outlined), how do I get `get-poetry.py` to install that wheel such that the install doesn't conflict with the package deps. (i.e. I can't just run `pip install` on the wheel).

**Comment by pmav99** [comment]
You will use pip to install the wheel. 

But all this feels a bit strange. What exactly are you trying to achieve? Help in development? Try a new feature?

**Comment by cancan101** [comment]
I am looking to use: https://github.com/sdispater/poetry/pull/757.

**Comment by drunkwcodes** [comment]
It's not a question for a senior Python & Github user.
And it is not the purpose of `get-poetry.py.`

**Comment by cancan101** [comment]
I am not specifically trying to run `get-poetry.py` against git. What I am trying to do is:
1. Use features that have been added to poetry since the last release (specifically #757)
2. Not pollute my virtualenv with the deps of poetry. `get-poetry.py` handles this, but I am open to other solutions.

**Comment by tommilligan** [comment]
For others who find this - I'm currently using the workaround described by @pmav99 

> A workaround could be to install a (pre-)released poetry version and then use it to create a newer poetry wheel using poetry build.

```bash
#!/bin/bash

set -ex

pip install poetry
git clone --branch develop --single-branch https://github.com/sdispater/poetry
cd poetry
poetry build
pip install dist/poetry*.whl
```

**Comment by finswimmer** [comment]
This is now possible using the new installer script `install-poetry.py`
