### ISSUE TITLE
Use pubgrub to solve dependency conflict. 

### ISSUE THREAD

**Issue by lalmei** [python-poetry/poetry#9742]
### Issue Kind

Change in current behaviour

### Description

Implement use of https://github.com/pubgrub-rs/pubgrub to solve publication conflicts. This seems the largest speed up associated with uv.

### Impact

Should give us speeds up in `poetry install` similar to uv since this the backend they use.

### Workarounds

The current implemented method could be a fall through

**Comment by dimbleby** [comment]
Poetry already uses pubgrub
