### ISSUE TITLE
Running into raw.githubusercontent.com request limit

### ISSUE THREAD

**Issue by remram44** [python-poetry/poetry#976]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: GitLab CI
- **Poetry version**: N/A
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: N/A

## Issue
The only way to get the `get-poetry.py` file is from raw.githubusercontent.com. That domain is apparently subject to usage limits; if installing it on a busy CI server, GitHub might send you an error message instead (apparently XML?)

See similar issue from other tool linking to raw.githubusercontent.com: https://github.com/nltk/nltk/issues/1787
See also [rawgit.com](https://rawgit.com/), which used to be a workaround for this
See [this answer on Quora](https://www.quora.com/What-is-the-recommended-way-to-use-raw-github-com) from technoweenie

Example: https://gitlab.com/remram44/taguette/-/jobs/181975291
```
$ curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  File "<stdin>", line 2
    <?xml version="1.0" encoding="utf-8"?>
    ^
SyntaxError: invalid syntax
```
I suggest the `get-poetry.py` file be distributed through a CDN or similar (or GitHub pages?) which can correctly handle the load without sending error messages.

**Comment by hangtwenty** [comment]
One option to solve: considering a passive mirror on GitLab.com Pages feature. 

https://gitlab.com/gitlab-com/support-forum/issues/2314

Opinion: I’d go for having that be primary raw file host (less likely to be saturated than GitHub), then move to GitHub Pages for secondary (as they are discussing in the NLTK thread linked above)

**Comment by hangtwenty** [comment]
Personally at work I vendorize such things, I should open-source my vendorize+bootstrap Poetry wrapper...

**Comment by remram44** [comment]
Although I'm a fervent supporter of GitLab, there is no need to switch to GitLab over this: GitHub Pages would be equally suitable.

Publishing `get-poetry.py` automatically from the master branch to pages would be a bit easier on GitLab CI, but can easily be done on Travis using a bit of Git trickery or ghp-import.

**Comment by hangtwenty** [comment]
If not clear, I meant primary/secondary as what’s mentioned in the doc example, it doesn’t force anyone’s hand and it would give someone the opportunity to use “||” to have a fallback (handy in bootstrapping to have fallbacks). 

Sure GitHub Pages could be the primary for this ticket though, maybe consider GitLab Pages as a fallback later.

Also note, GitHub→GitLab mirroring for sake of extra CI jobs or another Pages/artifact host, does not mean switching where the repo is. It can just be a mirror. https://docs.gitlab.com/ee/workflow/repository_mirroring.html

**Comment by remram44** [comment]
poetry can be installed from pip now, so the situation is a bit better, but the curl method is still recommended in the README.

**Comment by finswimmer** [comment]
Recommended way is to install from https://install.python-poetry.org now.
