### ISSUE TITLE
Document PEP 440 (Compatible Release) specifiers

### ISSUE THREAD

**Issue by srittau** [python-poetry/poetry#9782]
### Issue Kind

Missing documentation

### Existing Link

https://python-poetry.org/docs/dependency-specification/

### Description

poetry seems to support [PEP 440 "Compatible Release"](https://peps.python.org/pep-0440/#compatible-release) specifiers. Would you accept a PR add a section about them?

**Comment by radoering** [comment]
> Would you accept a PR add a section about them?

I do not see why we should not. 😃
