### ISSUE TITLE
Workaround for CodeArtifact Windows Keyring character limit

### ISSUE THREAD

**Issue by jonapich** [python-poetry/poetry#9791]
### Description

This is related to https://github.com/python-poetry/poetry/issues/6597

The issue should mention the workaround, which is to disable poetry's keyring:

`poetry config keyring.enabled false`

Since the issue is locked for new comments, I am kindly asking for a contributor to add a comment explaining the workaround. It would be a good idea to validate or erase the suggestion of installing the codeartifact poetry plugin since it doesn't fix the problem (it also uses the keyring).

FWIW, when you configure `pip` for AWS CodeArtifact, the token is also saved in plain text in `~/AppData/Roaming/...`.

### Workarounds

- Disabling the keyring works
- I tried the [codeartifact plugin](https://github.com/semgrep/poetry-codeartifact-plugin) but it exhibits the same keyring limitation.
- [I forked the plugin](https://github.com/coveooss/poetry-codeartifact-plugin/blob/1e86c488ef84890d9aa1c6bfc8b8bcf15ea205d7/poetry_codeartifact_plugin/plugin.py#L51) in an attempt to provide a workaround, but in the end what I did was to bypass the keyring. This fork will be deleted soon now in favor of `poetry config keyring.enabled false`

### Poetry Installation Method

pipx

### Operating System

Windows

### Poetry Version

Poetry (version 1.8.3)

### Poetry Configuration

```bash session
(irrelevant)
```

### Python Sysconfig

```bash session
(irrelevant)
```

### Poetry Runtime Logs

```bash session
see https://github.com/python-poetry/poetry/issues/6597
```

**Comment by jonapich** [comment]
https://github.com/python-poetry/poetry/issues/6597

**Comment by radoering** [comment]
> Since the issue is locked for new comments, I am kindly asking for a contributor to add a comment explaining the workaround.

I added a comment that refers to this issue.
