### ISSUE TITLE
BUG: When poetry add failed, package is listed as added but is not installed. Also add proper handling for multiple packages install in "poetry add": when one package is already added, others are not getting added.

### ISSUE THREAD

**Issue by buriy** [python-poetry/poetry#98]
If "poetry add" fails with an error on a package installation,
then after fixing the error it says "already added".
I need to remember to use "poetry install" then instead. 

The same happens if you want to add more than one entry, and the first entry was already installed: it writes that the entry was already added, not doing anything.

And the third issue is that if one issue breaks, "poetry add" doesn't add anything and tries to run an install first!

Fourth, after a "poetry add" fail, I have to add the entry *manually* and then run "poetry install" which writes that "you probably updated your file, run poetry update for that".
That means that while "poetry add" *can* check for the project file updates, "poetry install" can't. That behavior feels wrong.

Suggestions: 
1) remove error "Package A is already present", and when trying to add an existing package, instead, show what is the current version of that package in the project file, like "Package A of version 2.3.1 is selected". Or, maybe, even better it is to replace the already added version instead of displaying current version.
2) on "poetry add", first add *everything* to the project file, only then run install
3) probably, poetry install should be consistent with poetry add, or maybe "poetry add" without arguments should work like "poetry update".

**Comment by stephsamson** [comment]
@buriy Can you provide an example so that I can reproduce these issues on my machine?

**Comment by buriy** [comment]
@stephsamson 
There are several different use cases here. The easiest one is here:
```
poetry add jupyter
poetry add jupyter pydub ```
->
```
[ValueError]           
Package jupyter is already present  
```

**Comment by buriy** [comment]
Here is the recent activity

**Comment by finswimmer** [comment]
I have to investigate it a little bit more. But I guess this it what happens:

When you add  a package and something went wrong during installation and the exception isn't catched properly you and up having the package listed as an dependency in the `pyproject.toml` but it is not listed in the `poetry.lock`.

The simple workaround in this case is to remove the entry from `pyproject.toml` and use `poetry add` again.

**Comment by buriy** [comment]
@finswimmer 
I heard poetry is a tool that helps users, rather than asking doing everything manually ;)
This needs to be fixed.

**Comment by guiemi** [comment]
Same here. Visual Studio Code keeps asking me to install Pylama even if it's already added by Poetry.

**Comment by jacebrowning** [comment]
It's my understanding that the `Package jupyter is already present` error when attempting to `poetry add jupyter` a second time is the expected behavior.

Unless someone can share a way to reproduce `poetry add` failing for a different reason, I don't think this issue is actionable.

**Comment by buriy** [comment]
@jacebrowning problem is not that 
"poetry add jupyter" fails -- that's expected behaviour.

Problem is that attempt to add multiple packages:
"poetry add jupyter numpy" *fails* if jupyter is installed but numpy *is not installed*.
Rather it should say "jupyter is already installed" and install numpy.
