### ISSUE TITLE
Fails concatenation test on 3.14-rc 

### ISSUE THREAD

**Issue by MikeKlem** [python-poetry/poetry#9869]
### Description

Test fails on newest 3.14-rc python Docker image 

### Workarounds

Don't upgrade to 3.14-rc 

### Poetry Installation Method

other

### Operating System

Dockerhub image

### Poetry Version

HEAD

### Poetry Configuration

```bash session
N/A
```

### Python Sysconfig

```bash session
N/a
```

### Example pyproject.toml

```TOML
N/a
```

### Poetry Runtime Logs

```bash session
https://gitlab.com/mikeklem/python-poetry/-/pipelines/1530590897/failures
```

**Comment by Secrus** [comment]
We won't be testing for Python 3.14 until it reaches at least beta state and it's available on GH Actions
