### ISSUE TITLE
`poetry check --lock` ignores recursive dependency changes while `poetry lock` doesn't.

### ISSUE THREAD

**Issue by elongl** [python-poetry/poetry#9871]
### Description

Say I have package A and package B and that package B depends on package A.
```toml
# Package B:
package-a = { path = "../../packages/a", develop = true }
```

If I change a dependency on package A and run `poetry check --lock`, it'll say `All set!`.
But if I run `poetry lock --no-update`, it'll update the `poetry.lock` of package B to account for the changes made in package A.

### Workarounds

Currently my workaround is to always run `poetry lock`, but I'd prefer to run `poetry check` in my CI instead.

### Poetry Installation Method

pip

### Operating System

macOS 15.1.1

### Poetry Version

Poetry (version 1.8.4)

### Poetry Configuration

```bash session
Default
```

### Poetry Runtime Logs

```bash session
There are none.
```

**Comment by dimbleby** [comment]
`poetry check` does not lock.  `poetry lock` locks.

Seems expected.

**Comment by elongl** [comment]
> `poetry check` does not lock. `poetry lock` locks.
> 
> Seems expected.

But it's not checking properly, that's what I'm saying.
I didn't expect it to lock.

**Comment by dimbleby** [comment]
This is a duplicate, please close

**Comment by elongl** [comment]
Duplicate of https://github.com/python-poetry/poetry/issues/8633.
