### ISSUE TITLE
Installation Steps for Windows

### ISSUE THREAD

**Issue by kevinrawal** [python-poetry/poetry#9873]
### Issue Kind

Missing documentation

### Existing Link

https://python-poetry.org/docs/#installing-manually

### Description

In this section, the manual installation steps for Poetry are provided. However, users unfamiliar with macOS might find it confusing because, for Windows, the command should be `Scripts\pip install -U pip setuptools` instead of `/bin/pip install -U pip setuptools`. To improve clarity, we should update the instructions to explicitly include steps for Windows users.

**Comment by swills1** [comment]
The documentation states the instructions are for Unix only, "As this is an advanced installation method, these instructions are Unix-only..."

The complete Windows equivalent would be;
 
```
# Step 1: Create a virtual environment
python -m venv %VENV_PATH%

# Step 2: Upgrade pip and setuptools
%VENV_PATH%\Scripts\pip install -U pip setuptools

# Step 3: Install poetry
%VENV_PATH%\Scripts\pip install poetry
```

In order to match the linked docs formatting;

```
python -m venv %VENV_PATH%
%VENV_PATH%\Scripts\pip install -U pip setuptools
%VENV_PATH%\Scripts\pip install poetry
```
