### ISSUE TITLE
how to downgrade a dependence?

### ISSUE THREAD

**Issue by ghost** [python-poetry/poetry#989]
I have a sdk@1.4.5, and then I want downgrade to 1.4.4, how could I do?

now, I first run poetry remove to delete that sdk, then I edit pyproject to add `sdk = '1.4.4'`, and then I run poetry install. it's little inconvenient.

**Comment by jacebrowning** [comment]
Setting `sdk = "1.4.4"` should be sufficient. Which part is inconvenient?

**Comment by Tomatoo** [comment]
I must use four command to downgrade a dependence.

**Comment by cjw296** [comment]
@Tomatoo - not following, the need for the initial delete, I'd expect just editing pyproject.yaml and re-running `poetry install` should be enough. What happens if you try that?

**Comment by agilgur5** [comment]
Stumbled upon this, and it seems like using `poetry add sdk="1.4.4"` will also downgrade the dependency in one command (and resolve any related deps), no need to `poetry remove sdk` first.

**Comment by finswimmer** [comment]
The way @agilgur5 describes is the intended way :+1:

**Comment by geumilbae** [comment]
https://medium.com/uk-hydrographic-office/developing-and-testing-lambdas-with-pytest-and-localstack-21a111b7f6e8

**Comment by trondhindenes** [comment]
is there no way to do this by directly edit pyproject.toml? It seems much more intiutive to me to do it that way. But if I do that, I can't seem to make poetry realize that it should perform a downgrade (tried poetry lock, poetry install, poetry update)
