### ISSUE TITLE
`version preminor` doesn't update version

### ISSUE THREAD

**Issue by tkossak** [python-poetry/poetry#990]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Linux Mint 18.3 Sylvia
- **Poetry version**: 0.12.11
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/tkossak/7871e36fd0da5daa0fa11ae9132a0b7d

## Issue
`poetry version preminor` doesn't update the version:

```
$ poetry version preminor
Bumping version from 0.6.0-alpha.0 to 0.6.0-alpha.0
$ poetry version preminor
Bumping version from 0.6.0-alpha.0 to 0.6.0-alpha.0
$ poetry self:update
You are using the latest version
$ poetry --version
Poetry 0.12.11
```

Expected behaviour:
The version should be changed from `0.6.0-alpha.0` to `0.6.0-alpha.1`. Similar behaviour is also with `prepatch` and `premajor` verbs.

**Comment by drunkwcodes** [comment]
The command is `prerelease`

https://github.com/sdispater/poetry/blob/master/poetry/console/commands/version.py#L63

**Comment by tkossak** [comment]
Should I understand that it works as intended?

**Comment by fgreg** [comment]
If `prerelease` is supposed to be used, what is `preminor` supposed to be used for then?

**Comment by finswimmer** [comment]
Yes it's intended.

`prepatch`, `preminor` and `premajor` bump to a prelease of the next patch, minor or major version.

`prerelease` bumps to the next prerelease version.
