### ISSUE TITLE
Poetry Hooks

### ISSUE THREAD

**Issue by jefer94** [python-poetry/poetry#9906]
### Issue Kind

Brand new capability

### Description

Installations hooks like NPM and PDM do

### Impact

Could add pre-commit by default during the dependency resolution

### Workarounds

I have no idea, a possible alternative to this is, if we cannot set hooks, we could preselect the Poetry add-ons and these must be installed after a dependency resolution

**Comment by Secrus** [comment]
Duplicate of #5443
